### ISSUE TITLE
Type narrowing not working with multiple adjacent case statements

### ISSUE THREAD

**Issue by johan13** [microsoft/TypeScript#56352] opened 2023-11-09 15:19 UTC
### 🔎 Search Terms

"switch", "type narrowing"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about narrowing and switch statements

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcAUBDATgcwFyIDOUWMYOiAPouACYCmwZ9tAlIgN4BQiviMwRGgCE2HOygALLHADuiMPXkBRLDKxpWAbi48+hWTCgRJQkiHrtufG4ggZC9RGIB0UOAFUADl-pYAwg70mogAvOGIAEQAgpEEAPTxiADyANJ6trZY9FAgWEgxkToZtvaOzrhunj5+gY4h4aFRAEJxiImIfuqIACoAygCMABwADAAsQwQA5GJT-ISIXnCEhDAARgA2AJ6IU3SMzLRTLiU2ZU6u7t6+AUENEZH+bR1dcFi9g6MT07Pzi8urTY7PZgBhMRRHE6ZXjnCo4KrXWp3diNKIAEWeSTSp2h2Vy+RaABpEP5EG9EBidDYAL66Gx4vIFABycCgiGixOaxNJ5MpXFpQA

### 💻 Code

```ts
function foo(arg: string | undefined) {
    if (!arg) throw new Error();

    switch (true) {
        case arg.toUpperCase() === "A": // OK
            return "A";

        case arg.toUpperCase() === "B": // error TS18048: 'arg' is possibly 'undefined'.
        case arg.toUpperCase() === "C": // error TS18048: 'arg' is possibly 'undefined'.
        case arg.toUpperCase() === "D": // OK
            return "B, C or D";
    }

    return "Not A, B, C or D";
}
```

### 🙁 Actual behavior

In two of the four case statements, the `arg` variable has the type `string | undefined` instead of `string`.

### 🙂 Expected behavior

I would expect the `arg` variable to have the same type in all four case statements.

**Comment by RyanCavanaugh** [comment] 2023-11-09 16:30
Not fixed in Nightly

cc @Andarist

**Comment by Andarist** [comment] 2023-11-09 16:31
I'll work on this, thanks for the ping.

**Comment by Andarist** [comment] 2023-11-09 17:51
Interestingly... it's not a new issue. It's just a new manifestation of it: [TS playground](https://www.typescriptlang.org/play?ts=5.4.0-dev.20231109&ssl=5&ssc=10&pln=5&pc=13#code/GYVwdgxgLglg9mABMOcAUBDATgcwFyJggC2ARgKZaIA+ipqANuRkrQM5RYxg42LgATcsG7kBASkQBvAFCJEMYIjQBCbDklQAFljgB3QuQMBRLLqxpxAbhlzEbPTCgQtyqAE8ADuThL1k2Xl5CAw2ckR1PDsgxAB6WMQAPQB+aKCscigQLDAbGJCwiNwomPl4pNT80PDItLKElLrEDKycvMQAX1t5FuzcmS6gA). I think that all of those 3 case clauses should report the same type for `arg`. Of course, this particular code doesn't make a lot of sense 😅 but based on the initial investigation I believe it shows the same root cause. Those fallthrough cases are assigned an unreachable flow and that's why the flow type for `arg` can't be narrowed down using the pre-switch case flow (they are not connected). I'll continue investigating this.

**Comment by johan13** [comment] 2023-11-09 19:54
You are right - this is not new. I verified this behaviour all the way back to Typescript 3.0 before I opened the issue.

I just found it now because Typescript 5.3 adds better support for the `switch (true)` pattern and I wanted to play around with it.

One interesting thing I found is that the _first_ group of case statements in a switch works as expected, but in subsequent groups only the last case gets the narrowed type.

**Comment by Andarist** [comment] 2023-11-09 23:13
A more sane repro of this problem that doesn't rely on `switch (true)`: [TS playground](https://www.typescriptlang.org/play?ts=5.4.0-dev.20231109#code/GYVwdgxgLglg9mABFApgZygCgFCMcOOALlz0QB9EBvRAaxjABMjEAiAQ1YG5EAHAJzi8WGfgwDmiAL6k8lGvSYtWAI259BwxGBABbFSn7TZFanQbM2EdQKEsVhADYp2SKQBpSK9vwD8LKhMoAE9eFGU1LlIPbABKalIYYERMAEJvfnjAskR+FCgQfjAovBlSNAB3GCgIAAsUgjgAOkVGLJMIdjQUNk4SHLwAekHEAD1fEzw8gqKSsk7uxAymkLD++a6e1mt1nOnC4ujsGSA)

**Comment by Karmel0x** [comment] 2023-11-09 23:22
similar problem with array methods ([TS Playground](https://www.typescriptlang.org/play?#code/DYUwLgBAhgXBDOYBOBLAdgcwgHwgVzQBMQAzdEQgbgChqpKB6BiMATwAcQIV4IADRKkw58RUuUJ9aKEhAAUAQigBKFgAskAewDuENCF0BRJFqRzlNOo2ZtO3XgOToMUqADowmgKrtOSAMJQ8CDm1hCaANa0ANoAum4kmkiGUADGanIAbhAAvAB8EADe1ACQ9EwsHFw8-ILOIgTEZPqSEABGeJDwapp4wITtXI5CLqXunj5+gcGhFSAmSRAAKgDKAIwAHAAMACwbcADkUEgYB-YQ7Jrw8ChtwKwQB43iLQfUAL4W1EA))
```ts
let a: string | undefined;

a;// type is `string | undefined`

if (!a) throw new Error();

a;// type is `string`
a.toUpperCase();// ok

[].forEach(v => {
	a;// type is `string | undefined` but should be `string`
	a.toUpperCase();// error TS18048: 'arg' is possibly 'undefined'
});
```

**Comment by jakebailey** [comment] 2023-11-09 23:23
That's unrelated; that's just #9998.

**Comment by fatcerberus** [comment] 2023-11-10 02:52
Wait, how is that 9998?  There’s no function call or closure there, `bar` is narrowed and then later the narrowing disappears *in the same scope*.

**Comment by jakebailey** [comment] 2023-11-10 06:30
I responded to another user who deleted their post. I don't have the code anymore but it was definitely a map or filter. I have no doubt that @Andarist knows all about #9998 😄

**Comment by jakebailey** [comment] 2023-11-10 06:31
From my email...

![image](https://github.com/microsoft/TypeScript/assets/5341706/8d2006c1-d551-4b59-9749-ccfec00df6f3)

**Comment by johan13** [comment] 2023-11-10 09:28
I just stumbled across a similar issue. [Playground](https://www.typescriptlang.org/play?ts=5.3.0-beta#code/GYVwdgxgLglg9mABMOcAUBDATgcwFyIDOUWMYOiAPouACYCmwZ9tAlIgN4BQivRA7jCgQAFojQkQ9dtz5zEEDIXqJsFALyaaYBkzAs8Pecagiscfon2WAolnNY0rANxcjxxctW4AdMWxQhADqQiJoAEQAHuGsBAD0cYj09nBYiAAqAMoAjAAcAAwALLkEAORqpYgwhIgADnCEhDAARgA2AJ6IpXSMzLSlPu7GfFj0UCBYSOEAguGuQ3K6GCCtUIbD8qPjk4jhAEJzQwC+XCdAA)

```ts
function foo(arg: string | undefined) {
    switch (true) {
        case arg === undefined:
            throw new Error();

        case arg.startsWith("x"): // error TS18048: 'arg' is possibly 'undefined'.
            return "A";

        default:
            return "B";
    }
}
```

Is it intended behavior that that I get an error here?

**Comment by Andarist** [comment] 2023-11-10 09:37
This looks like a different case. Could you open a different issue about this and ping me there?

**Closed** 2023-11-13 22:41 UTC
Labels: Bug, Fix Available
