### ISSUE TITLE
Compiler Watch Mode does not re-compile if extended tsconfig changes.

### ISSUE THREAD

**Issue by 12wrigja** [microsoft/TypeScript#40564] opened 2020-09-15 00:19 UTC
**TypeScript Version:**  Version 4.1.0-dev.20200914

**Search Terms:**
Watch mode, tsserver watch, watch
**Code**

/// main/tsconfig.json
```json
{"extends": "../configs/tsconfig_editor.json"}
```
/// configs/tsconfig_editor.json
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node"
  },
  "files": [
          "../main/test.ts"
  ]
}
```
/// main/test.ts
```ts
console.log('hello world');
```

/// main/test1.ts
```ts
console.log('hello world 1');
```
I ran tsc from the `main ` directory like so:
```
./node_modules/typescript/bin/tsc -w -p tsconfig.json
```
`test` is compiled just fine.

I then edit `configs/tsconfig_editor.json` and add an entry for `test1.ts` into the files list.

**Expected behavior:**

tsc notices that the extended config has changed and recompiles, also compiling test1.ts.

**Actual behavior:**

tsc does nothing.

My actual issue lies with vscode's language services integration (that doesn't update the language service results when the underlying extended config is changed by our build system), but it seems that this codepath (based on skimming the tsserver source) is broken here too. Looking at the tsserver logs, it seems a watch is setup for `main/tsconfig.json` but not for the file it extends from.

**Comment by sheetalkamat** [comment] 2020-09-15 03:35
Duplicate of  #17753

**Closed** 2020-09-18 18:00 UTC
Labels: Duplicate
