### ISSUE TITLE
#47100  Interface 'Document' incorrectly extends interface 'FontFaceSource'.

### ISSUE THREAD

**Issue by Gangasree-N** [microsoft/TypeScript#54980] opened 2023-07-12 05:36 UTC
#47100

Error: node_modules/typescript/lib/lib.dom.d.ts:6689:11 - error TS2430: Interface 'Document' incorrectly extends interface 'FontFaceSource'.
  Types of property 'fonts' are incompatible.
    Type '{ ready: Promise<void>; } | undefined' is not assignable to type 'FontFaceSet'.
      Type 'undefined' is not assignable to type 'FontFaceSet'.

6689 interface Document extends Node, DocumentOrShadowRoot, FontFaceSource, GlobalEventHandlers, NonElementParentNode, ParentNode, XPathEvaluatorBase {
               ~~~~~~~~


Error: node_modules/typescript/lib/lib.dom.d.ts:21187:11 - error TS2430: Interface 'ShadowRoot' incorrectly extends interface 'DocumentOrShadowRoot'.
  Types of property 'adoptedStyleSheets' are incompatible.
    Type 'CSSStyleSheet[] | undefined' is not assignable to type 'CSSStyleSheet[]'.
      Type 'undefined' is not assignable to type 'CSSStyleSheet[]'.

21187 interface ShadowRoot extends DocumentFragment, DocumentOrShadowRoot, InnerHTML {
                ~~~~~~~~~~

**Comment by MartinJohns** [comment] 2023-07-12 05:56
You forgot to fill out the issue template for bug reports. Duplicate of #47100.

**Comment by Gangasree-N** [comment] 2023-07-12 05:58
can someone provide solution or fix for this issue

**Closed** 2023-07-16 01:34 UTC
Labels: Duplicate
