### ISSUE TITLE
Property is not definitely assigned in the constructor, but it actually is.

### ISSUE THREAD

**Issue by DiriectorDoc** [microsoft/TypeScript#50643] opened 2022-09-05 18:26 UTC
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When a class property is defined via a setter, it says that the value is not definitely defined, when it actually is. It would be nice if TS could better detect when a property is defined in this way.

## 📃 Motivating Example

Currently, this does not work

```typescript
class Foo {
	bar: number; // Property 'bar' has no initializer and is not definitely assigned in the constructor.

	constructor(){
		this.baz = 3 // this setter will set the value of 'bar'
	}

	set baz(v: number){
		this.bar = v // sets falue of 'bar'
	}
	get baz(): number {
		return this.bar
	}
}
```

I have to do this:

```typescript
class Foo {
	bar!: number; // Non-null assertion operator is required but not necessary because 'bar' is always set in the constructor

	/* ... */
}
```

## 💻 Use Cases

This is a minor suggestion, I know. But it would make for a nice quality-of-life change.

**Comment by MartinJohns** [comment] 2022-09-05 18:39
Duplicate of #9998.

**Comment by whzx5byb** [comment] 2022-09-06 00:52
It could be unsound to initialize property inside a method or an accessor, because they could be overriden in a subclass and their behavior may change.

**Comment by DiriectorDoc** [comment] 2022-09-06 01:11
Hmm. Good point. I had not considered that.

**Comment by MartinJohns** [comment] 2022-09-06 06:51
A more specific duplicate would be #21132 / #28200. The setter is nothing more than a "helper".

**Closed** 2022-09-10 18:00 UTC
Labels: Duplicate
