### ISSUE TITLE
Feature request: recognize modules within an npm package

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#12243] opened 2016-11-14 23:05 UTC
_From @ffxsam on August 31, 2016 2:21_

- VSCode Version: 1.4.0
- OS Version: Mac OS 10.11.6

It would be awesome if VS Code could do what WebStorm does:

![screen_shot_2016-08-30_at_7_13_53_pm__2_](https://cloud.githubusercontent.com/assets/12532733/18113727/cfed5190-6ee6-11e6-93f4-cde923297dbf.png)

If I have the following:

``` js
import {
} from 'material-ui';
```

and I start typing "Table" in the braces, it can see inside the Material UI package and suggest a list of modules (`Table`, `TableBody`, etc).

_Copied from original issue: Microsoft/vscode#11268_

**Comment by waderyan** [comment] 2016-11-14 23:05
_From @dbaeumer on August 31, 2016 7:10_

@ffxsam is this JavaScript or TypeScript

**Comment by waderyan** [comment] 2016-11-14 23:05
_From @ffxsam on August 31, 2016 7:20_

JavaScript.

**Comment by waderyan** [comment] 2016-11-14 23:05
This is a valid feature request. Thank you @ffxsam!

**Comment by waderyan** [comment] 2016-11-14 23:05
_From @ffxsam on August 31, 2016 16:46_

You bet! I come from using WebStorm, which admittedly has probably the best JS code formatting and autocompletion I've seen.. but it suffers from huge bloat, and so I started looking for something more lightweight. VS Code is super impressive so far!

**Comment by waderyan** [comment] 2016-11-14 23:05
@ffxsam can you send me an email? I'm working on the gaps between VS Code and WebStorm and would love to get your feedback in a short 20 minute user interview. 

wade.anderson@microsoft.com

**Comment by mhegazy** [comment] 2016-12-15 22:20
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/10092, and should be covered by the suggestion in  #7849

**Closed by mhegazy** 2016-12-15 22:20 UTC
Labels: VS Code Tracked

**Comment by waderyan** [comment] 2016-12-16 18:47
@mhegazy I believe this should be reopened. This is a different scenario then #7849 and will not be covered. #7849 is to auto add the imports. This is to receive intellisense for the modules within an npm package. 

The user scenario where this is valid is with the popular material-ui library. They have lots and lots of modules in each package. Not having IntelliSense is quite a pain. WebStorm will provide IntelliSense for the modules.

**Comment by mhegazy** [comment] 2016-12-16 21:52
The original snippet works as intended. and has been working like that for a while so i am not sure i understand what you mean.
![animation](https://cloud.githubusercontent.com/assets/8000722/21279748/bfa07088-c396-11e6-990a-a266adb483ea.gif)
