### ISSUE TITLE
"safe navigation operator" linting error with mixed types

### ISSUE THREAD

**Issue by StefanKern** [microsoft/TypeScript#34919] opened 2019-11-05 14:59 UTC
**TypeScript Version:**  3.7-Beta

If the "safe navigation operator" is used with an a variable, which either is a complex type or undefined, a linting error is shown.

Minimal example
```
const test2: { data: { page: []}} | undefined = undefined;
(test2?.data?.page ?? []).forEach(() => { });
```
The following error is incorrectly shown under ´data´
> Property 'data' does not exist on type 'never' (2339)

The code, however, is correctly converted into javascript 

**Playground Link:** 
https://www.typescriptlang.org/play/index.html?ts=3.7-Beta&ssl=5&ssc=46&pln=4&pc=1#code/MYewdgzgLgBFCm0YF4YG8AeAuGBtNMAnjgIwC+AumQNwBQokIANvAHRMgDmAFAtAPysMg3AAYKrQjH78YAcgCuYACbwAZgEsw8ZXICUdeuCR8oAJhwFlAQyjXLMAA7XO8HLipkYAHxhLVmtrKKH4q6lo6dLyI5oI2doLOrtKyHnqsaiAATgCi1sAAFtzceigAfOgwZAZAA

![image](https://user-images.githubusercontent.com/2032760/68218702-0d76e480-ffe5-11e9-9457-1104344af00b.png)

**Comment by nmain** [comment] 2019-11-05 15:56
Duplicate of https://github.com/microsoft/TypeScript/issues/34691

**Comment by RyanCavanaugh** [comment] 2019-11-05 16:15
TypeScript can see that you initialized the variable to `undefined` and is rightly complaining that you are writing code that cannot ever execute. If the initializer could actually return an object, you wouldn't see the error.

**Closed by RyanCavanaugh** 2019-11-05 16:15 UTC
Labels: Working as Intended

**Comment by StefanKern** [comment] 2019-11-06 05:48
@RyanCavanaugh 

thank you for your answer, I did some further test and it really works as you say. 

When writting it like this
```
let test2: { data: { page: [] } } | undefined = undefined;
if (true) {
    test2 = { data: {page: []}}
}

(test2?.data?.page ?? []).forEach(() => { });
```
data is correctly detected as valid property.

![image](https://user-images.githubusercontent.com/2032760/68271527-1b6a4b00-0061-11ea-9002-8e7123ced3a2.png)

However writting it like this
![image](https://user-images.githubusercontent.com/2032760/68271560-3341cf00-0061-11ea-8a02-c4524c2ac7ab.png)
correctly detects two problems

More complex example, such as this 
![image](https://user-images.githubusercontent.com/2032760/68271586-4b195300-0061-11ea-87bd-7b87d3630d8b.png)

are also valid, even if the variable would never be set.
