### ISSUE TITLE
Ignoring tsconfig.json in Angular 2 CLI generated apps

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8523] opened 2016-05-09 09:56 UTC
_From @ncrawlins on May 8, 2016 15:53_

- VSCode Version: 1.0.0
- OS Version: Windows 10

Maybe it's a problem with the project setup, but VSCode doesn't honor the experimentalDecorators flag and other tsconfig settings for any file you open AFTER the first file in an Angular CLI generated project.  You can close all files and wait a second and then open the files in a different order and the ones reporting errors will switch.

Steps to Reproduce:
1. Install angular 2 cli from NPM
2. use "ng new test" to create a new project.
3. Open the created directory in code.  The first TS file you open won't have any problems but all the ones you open after that won't use the tsconfig.json.
![code-ng2-bug](https://cloud.githubusercontent.com/assets/291462/15098770/dfde08a2-1512-11e6-8d05-deaaab3d34cd.gif)

_Copied from original issue: Microsoft/vscode#6200_

**Comment by dbaeumer** [comment] 2016-05-09 09:56
The problem is the generated tsconfig.json file. It contains a files section and list only two files main and typings.d.ts. Therefore the files under source aren't considered part of the project defined by the tsconfig.json file. 

Removing the files section makes it work as expected. Opened https://github.com/angular/angular-cli/issues/684.

I will also move this to the TS team since they should already issue an error on the first opened file in the src folder.

**Comment by ncrawlins** [comment] 2016-05-09 13:39
I'm not sure it's quite that simple.  Aren't files referenced by main.ts or it's dependencies also supposed to be included under that configuration? Because in that image the VtcnetClientAppComponent is included in main.ts and yet it will still occasionally shows errors.

For example, in a larger project, if every single file I open is a dependency of main.ts, everything works fine. No matter how many times I open and close a file it never shows errors.  However, if I open any new files that aren't in the dependency chain yet, then I will sporadically see those errors.  And from that point on I will sporadically see those errors on all files, even ones included in the dependency chain of main.ts that shouldn't be showing the error.  I hope that makes sense.

**Comment by mhegazy** [comment] 2016-05-09 20:00
> I will sporadically see those errors on all files, even ones included in the dependency chain of main.ts that shouldn't be showing the error. I hope that makes sense.

can you provide steps to reproduce the issue?

**Comment by mhegazy** [comment] 2016-05-09 20:01
//cc: @alexeagle,

@alexeagle why does the template include `"files"` and not just include all files in the directory?

**Comment by ncrawlins** [comment] 2016-05-09 20:54
@mhegazy 
the github at this repo is a very simple example.  https://git.io/vrfeN
1. Open the repo in VS Code.  Because main.ts imports A, B, C and D the es6 target is applied to all files as you navigate between them and no errors are shown.
2. Comment out all references to objD in main.ts and reload VS Code.
3. I would expect errors only in objD since it is no longer implicitly in the files list.  However, switching between files will show errors "randomly" on ALL the dependencies.  Sometimes revisiting a file or closing a file and hitting the refresh button can change the error status for a file despite making no changes.

**Comment by mhegazy** [comment] 2016-05-09 21:08
@zhengbli can you take a look

**Comment by zhengbli** [comment] 2016-05-09 21:47
I can't repro either of the issues. @ncrawlins @dbaeumer can you test using the TS nightly?

**Comment by ncrawlins** [comment] 2016-05-09 22:36
@zhengbli 
With the nightly build it's better but it still happens in a special case.   View main.ts but don't have it in your working files.  Then click on any of the objX module files.  It will show an incorrect error.  If you click away from that objX file (but not into main.ts) and then back to it, the error will be gone.

If main.ts is in your list of working files, everything seems to work fine.
![vs-ts-issue](https://cloud.githubusercontent.com/assets/291462/15130247/e399cfc8-1614-11e6-83f6-994924d7c59d.gif)

**Comment by alexeagle** [comment] 2016-05-09 22:40
@hansl for the decision about including only the entry points in `"files"`. I think this is just a tradeoff vs. `exclude` of `node_modules, typings/main, typings/main.d.ts`

**Comment by zhengbli** [comment] 2016-05-09 22:46
@ncrawlins Thanks for the procedure, now I can repro this issue. Investigating.

**Comment by Brocco** [comment] 2016-05-11 14:29
@alexeagle is correct, the reason they are there is in order to support an entry point for a broccoli-typescript plugin to build the appropriate dependency model.

**Comment by alexeagle** [comment] 2016-05-11 16:44
I think the typical treeshaker setup would be to give entry points to some other tool via its configuration (eg rollup https://github.com/rollup/rollup/wiki/JavaScript-API#entry )
But it's an interesting setup to use TypeScript's files config to serve both purposes...

**Closed** 2016-06-15 19:42 UTC
Labels: Bug
