### ISSUE TITLE
Code Transpilation throws an `AbortController` exception

### ISSUE THREAD

**Issue by Qodestackr** [microsoft/TypeScript#51814] opened 2022-12-08 05:57 UTC
# Bug Report
Any code transpilation including React yells an abort controller on TypeScript internal tooling

### 🕗 Version & Regression Information
TypeScript version: `4.9.3`

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```bash
node_modules/@types/node/globals.d.ts:72:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; timeout(milliseconds: number): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.

72 declare var AbortSignal: {
               ~~~~~~~~~~~

  ../../../../../../usr/local/lib/node_modules/typescript/lib/lib.dom.d.ts:2071:13
    2071 declare var AbortSignal: {
                     ~~~~~~~~~~~
    'AbortSignal' was also declared here.


Found 1 error in node_modules/@types/node/globals.d.ts:72
```

**Comment by MartinJohns** [comment] 2022-12-08 07:16
You forgot to fill out the issue template. Duplicate of #51567.

**Comment by Qodestackr** [comment] 2022-12-08 07:51
Thanks closing the issue.
Reason: duplicate

**Closed** 2022-12-08 07:51 UTC
