### ISSUE TITLE
`TypeError: Cannot read property 'kind' of undefined` in vscode build

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/TypeScript#36614] opened 2020-02-04 23:12 UTC
Branch up at https://github.com/microsoft/vscode/tree/jackson/ts-build-error

When I run the typescript build, it crashes with the below error:
```
TypeError: Cannot read property 'kind' of undefined
    at getErrorSpanForNode (/Users/jkearl/Developer/vscode/node_modules/typescript/lib/typescript.js:13429:22)
    at createDiagnosticForNodeInSourceFile (/Users/jkearl/Developer/vscode/node_modules/typescript/lib/typescript.js:13389:20)
    at Object.createDiagnosticForNode (/Users/jkearl/Developer/vscode/node_modules/typescript/lib/typescript.js:13380:16)
    at reportNonExportedMember (/Users/jkearl/Developer/vscode/node_modules/typescript/lib/typescript.js:36179:50)
    at getExternalModuleMember (/Users/jkearl/Developer/vscode/node_modules/typescript/lib/typescript.js:36160:33)
    at getTargetOfImportSpecifier (/Users/jkearl/Developer/vscode/node_modules/typescript/lib/typescript.js:36187:20)
    at getTargetOfAliasDeclaration (/Users/jkearl/Developer/vscode/node_modules/typescript/lib/typescript.js:36238:28)
    at resolveAlias (/Users/jkearl/Developer/vscode/node_modules/typescript/lib/typescript.js:36277:30)
    at checkAliasSymbol (/Users/jkearl/Developer/vscode/node_modules/typescript/lib/typescript.js:64208:26)
    at checkImportBinding (/Users/jkearl/Developer/vscode/node_modules/typescript/lib/typescript.js:64240:13)
```

**Comment by JacksonKearl** [comment] 2020-02-04 23:25
Deleting line
```
import { SearchConfiguration, DEFAULT_SEARCH_CONFIG } from 'vs/workbench/contrib/searchEditor/browser/searchEditorInput';
```

from `searchEditorModel` and `searchEditorSerialization` fixes.

**Comment by DanielRosenwasser** [comment] 2020-02-04 23:57
Probably due to #36187. I'm going to guess that using `valueDeclaration` instead of the first local declaration is a problem for types, uninstantiated namespaces, and imports (aliases).

**Comment by andrewbranch** [comment] 2020-02-05 00:18
Duplicate of #36592, and Daniel is correct in the diagnosis 😁

**Closed** 2020-02-05 16:27 UTC
Labels: Duplicate
