### ISSUE TITLE
Contextually type class property initializers by `extends`/`implements` types

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#3667] opened 2015-06-29 04:50 UTC
When a property has exactly one type from an `extends` or `implements` clause, we should contextually type that property's initializer by the type from the clause. For example:

```ts
interface ThingListener {
	handleEvent: (x: MouseEvent) => void;
}

class Foo implements ThingListener {
	handleEvent = x => {
		// No error, but this code is incorrect
		console.log(x.timestamp);
	}
}
```

Ideally we could take this one step further when widening. The following behavior is also undesirable:
```ts
interface HasLength {
	length: number
}

class Foo implements HasLength {
	// length: any, not really what we intended
	length = undefined;
}

var x = new Foo();
x.length = 'wat'; // should not be allowed
```

e.g. #3666

**Comment by NoelAbrahams** [comment] 2015-06-29 10:41
Is this not the same as #1373?

**Comment by RyanCavanaugh** [comment] 2015-06-29 15:52
#1373 is about methods, this is about properties

**Comment by DanielRosenwasser** [comment] 2015-06-29 16:26
So is this a broader proposal than #1373? In other words, in the following example, is the arrow function in `SortByQueryId` contextually typed?

Additionally, if we declared `getvalue` in `ISortInfo` as a property but defined it as a method in the class, would its parameter's type be inferred?

```TypeScript
    export interface ISortInfo
    {
        getvalue(x: QuerySummary): number | string;
        order: SortDir;
        ordercalc?: number;
    }

    class SortByQueryId implements ISortInfo
    {
        getvalue = x => x.QueryId;
        order = SortDir.Flip;
    }
```

**Comment by RyanCavanaugh** [comment] 2015-06-29 17:10
I don't think we should distinguish between method-style and property-style declarations in the interface - both are an equally valid "source" in terms of type information, regardless of how the class is implementing it.

In the example, I would expect the arrow function to be contextually typed under *this* proposal, but not #1373.

**Comment by jonathandturner** [comment] 2015-07-16 17:37
Agree with @NoelAbrahams - can we merge this with #1373?  If this subsumes that proposal, can we dupe that one to this one?

**Comment by tinganho** [comment] 2015-07-16 17:41
Also merge with #3804 ? Then we include interfaces too.

**Comment by Gaelan** [comment] 2015-09-21 01:01
:+1:

**Comment by omidkrad** [comment] 2015-10-08 20:57
From #5181 the following sample reproduces this issue:

```typescript
declare module Backbone {
	interface RoutesHash {
		[routePattern: string]: string | {(...urlParts: string[]): void};
    }
	class Events { }
	class Router extends Events {
		routes: RoutesHash;
	}
}

declare module Marionette {
	class AppRouter extends Backbone.Router {
	}
}

module Backbone.Tests {
	// Error, routes is not contextually typed
    class MyRouter extends Backbone.Router {
	    routes = {
	        "some/route": "someMethod",
			"some/otherRoute": () => {}
	    };
	}
}

module Marionette.Tests {
	// Error, routes is not contextually typed
    class MyRouter extends Marionette.AppRouter {
	    routes = {
	        "some/route": "someMethod",
			"some/otherRoute": () => {}
	    };
	}
}
```

**Comment by RyanCavanaugh** [comment] 2015-11-03 00:11
Tentatively approved -- this would be a slight breaking change, but probably very much in the "good" direction (i.e. uncovers bugs that were going missed before). We will investigate breakages in our RWC suite to see what the net impact is.

**Comment by omidkrad** [comment] 2015-11-06 17:58
I'd be fine with this breaking change.

**Comment by sandersn** [comment] 2016-05-06 03:51
Unfortunately, we couldn't come up with a solution that was both consistent and backward-compatible. The breaks in our Real World Code suite were more bad than good. See #6118 for details. I'm closing this for now.

**Closed by sandersn** 2016-05-06 03:51 UTC
Labels: Committed, Suggestion
