### ISSUE TITLE
Constructor cannot access own protected instance when typed as union

### ISSUE THREAD

**Issue by JacobLey** [microsoft/TypeScript#59289] opened 2024-07-16 03:36 UTC
### 🔎 Search Terms

protected constructor union accessible

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about protected constructor accessibility

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.3#code/MYGwhgzhAEBiD29oG8CwAoaXoAcCuARiAJbC6EBc0AdngLYECmATgNwba7PwAujwfACZd4VWgxbtM2HM2IA3MHy4Kx9Jmw7YAxAAtIutRM3otWYPGoQezPAPjMAFADNEAfioIkAH2gAhMGYAShQzTmhiZ2gXRBC0aXDwnl1iCAA6fAJoAF5oV3gMwmgAamgARilExIB6augAeWoQAE9oZNToRmobVuZGCDwQHhhiak7mbmYAQjCqtpT02SRc-IzuEvLKuex2xbl5HLzENYUNitmq3bS9A0PVm4hdM63EgF9OkAhGUITtq8zDgBZJS6NLMMDUQTwOiOIIvP4LNbLaDA5JgiFQmFwi6Jf77IEg9GQ6Gw+FzK4PJ65VGg8HErFk7CvMLM9CsjCgSAwALMToADz4kJgXhQryAA

### 💻 Code

```ts
class Foo {
    public pub: number;
    protected pro: number;
    private priv: number;
    #hash: number;

    constructor(foo?: Foo | Bar) {
        if (foo) {
            this.pub = foo.pub + 1;
            // Only this entry results in error!
            this.pro = foo.pro + 1;
            this.priv = foo.priv + 1;
            this.#hash = foo.#hash + 1;
        } else {
            this.pub = Math.random();
            this.pro = Math.random();
            this.priv = Math.random();
            this.#hash = Math.random();
        }
    }
}

class Bar extends Foo {}
```

### 🙁 Actual behavior

The line
```ts
this.pro = foo.pro + 1;
```

Throws an error
> Property 'pro' is protected and only accessible through an instance of class 'Foo'. This is an instance of class 'Foo | Bar'.

### 🙂 Expected behavior

No error.

Neither the private or hash field experience the same issue, despite having (supposedly) stricter requirements.

Supplying the type as `Foo` or `Bar` alone (opposed to `Foo | Bar`) removes this issue.

### Additional information about the issue

A similar issue appears to have existed for `private` fields (the typescript kind, not hash as it wasn't supported) that was resolved in `v3.9.7`.

**Comment by MartinJohns** [comment] 2024-07-16 06:09
Sounds like a duplicate of #46049 to me.

**Comment by JacobLey** [comment] 2024-07-17 00:14
Agreed it is a duplicate, although looks like a PR was opened for this issue (fast 🚀 ) so will keep this open (unless we want to re-point that PR at the other issue)

**Closed** 2024-07-20 01:30 UTC
Labels: Duplicate
