### ISSUE TITLE
items get closed too early

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#8290] opened 2016-04-25 22:15 UTC
It was a few times when an idea that might not fit immediately to the realm of current TypeScript development was prematurely closed without a chance to be seen by the community and get any traction.

Although we admit that not every idea makes minimal sense and some of them to be closed immediately, not all of them are like that.

It's more of a problem of how issue tracking is made: the closed issues go into oblivion, only open ones have a chance.

So rather than closing it on premise of "Too complex" or "By design", why would not you give it some more time just by tagging "Declined" and letting it sit for a month or so?

**Comment by mhegazy** [comment] 2016-04-25 22:30
I apologize if me closing issues felt premature. the problem is we get a high volume of issues daily. and personally, i have found that if i do not respond to an issue when i first see it, chances are i am not going to look at it again. I would do a pass every now and then and close stale issues. so i suppose we can leave it. 

Also worth noting that we leave the issues unlocked as well, and we have reopened issues that the community has commented to. so closing them does not mean no more discussion.

**Comment by mhegazy** [comment] 2016-04-25 22:31
I should also note that we are always look for suggestions to better our processes. so thanks for the input.

**Comment by RyanCavanaugh** [comment] 2018-02-08 23:42
Closing for irony.

**Closed by RyanCavanaugh** 2018-02-08 23:42 UTC
Labels: Discussion

**Comment by aleksey-bykov** [comment] 2018-02-09 02:02
so not fair
