### ISSUE TITLE
Autocomplete does not work for string literals and arbitrary string in single type

### ISSUE THREAD

**Issue by mctep** [Microsoft/TypeScript#25890] opened 2018-07-24 09:30 UTC
**TypeScript Version:**  3.1.0-dev.20180724

**Search Terms:** arbitrary string literals autocomplete

**Code**

```ts
type Type = 'foo1' | 'foo2' | string;
const func = (a: Type) => a;

func('f')
```

**Expected behavior:**

Autocomplete should suggest `foo1` and `foo2` variants.

**Actual behavior:**

Autocomplete does not suggest variants `foo1` and `foo2`. If I remove arbitrary `| string` it works as expected. 

**Playground Link:** [Link](https://www.typescriptlang.org/play/index.html#src=type%20Type1%20%3D%20'foo1'%20%7C%20'foo2'%20%7C%20string%3B%0D%0Aconst%20func1%20%3D%20(a%3A%20Type1)%20%3D%3E%20a%3B%0D%0Afunc1('')%0D%0A%0D%0Atype%20Type2%20%3D%20'foo1'%20%7C%20'foo2'%3B%0D%0Aconst%20func2%20%3D%20(a%3A%20Type2)%20%3D%3E%20a%3B%0D%0Afunc2('f')%0D%0A)

**Comment by j-oliveras** [comment] 2018-07-24 10:38
`type Type = 'foo1' | 'foo2' | string;` is equivalent to `type Type = string;`.

I think this works as intended.

**Comment by mctep** [comment] 2018-07-24 11:04
@j-oliveras I understand, but I think it wold be great to have predefined values for autocomplete in this case.

**Comment by andy-ms** [comment] 2018-07-24 16:13
Duplicate of #20154

**Closed** 2018-08-03 21:09 UTC
Labels: Duplicate
