### ISSUE TITLE
Recursive conditional types seem to hang experience

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#40369] opened 2020-09-03 19:40 UTC
https://en.wikipedia.org/wiki/Collatz_conjecture

So the following **does not** hang TypeScript nightly

```ts
type Unary = ReadonlyArray<1>;
type UZero = [];

type UIncr<U extends Unary> = [1, ...U];
type UDecr<U extends Unary> = U extends UIncr<infer U1> ? U1 : never;

type UOne = UIncr<UZero>;

type Collatz<T extends Unary> = T extends UOne ? UOne : HailstoneHelper<T, UZero, T>;

type TimesThreePlusOne<T extends Unary> = UIncr<[...T, ...T, ...T]>;
type HailstoneHelper<Orig extends Unary, HalfAccum extends Unary, Curr extends Unary> =
    Curr extends UZero ? HalfAccum :
    Curr extends UOne ? Collatz<TimesThreePlusOne<Orig>> :
    Collatz<HailstoneHelper<Orig, UIncr<HalfAccum>, UDecr<UDecr<Curr>>>>;
//  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Type instantiation is excessively deep and possibly infinite.(2589)
```

But introducing a trailing conditional type will cause the following example to seemingly never end:

```ts
type Unary = ReadonlyArray<1>;
type UZero = [];

type UIncr<U extends Unary> = [1, ...U];
type UDecr<U extends Unary> = U extends UIncr<infer U1> ? U1 : never;

type UOne = UIncr<UZero>;

type Collatz<T extends Unary> = T extends UOne ? UOne : HailstoneHelper<T, UZero, T>;

type TimesThreePlusOne<T extends Unary> = UIncr<[...T, ...T, ...T]>;
type HailstoneHelper<Orig extends Unary, HalfAccum extends Unary, Curr extends Unary> =
    Curr extends UZero ? HalfAccum :
    Curr extends UOne ? Collatz<TimesThreePlusOne<Orig>> :
    Curr extends [any, any, ...any[]] ? Collatz<HailstoneHelper<Orig, UIncr<HalfAccum>, UDecr<UDecr<Curr>>> :
    never;
```

[Playground link](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200903#code/C4TwDgpgBAqgdgQwE4igXigJQggJgezgBsQBBJJBEAHgEYA+AbgFgAoUSWALQiX3SgBtALotWbDtBgBJOAGMk1GFAgAPYBDi4AzrEQp6AwbQA0UAHSWYoieCkARCAqUr1mnXuQhDGZWo1aujLyigCWcABmvLAMUAD8MVAAXFBwEABuvGK2nDAA8mkCwc4wPHxMbDnQAML4REQIwABe1AAqrgEe8F4+UO3+7kEF0An5hSkAEgihRNrAhBATEESQiq1mpbz4Zq0V4ux2faEAthDarQAWSBAQAApEAK7aw20dg54GRbLOgpbm6xZLAC-q1hHtJFApjM5gsliteNQ8khQgBzN6BD4gMxTIgRUhyOQPY7orr6LFQaoPCgkoJknxsKCMilUpA07hbeKQhC4-GE4lJBlMynUgYYsYjCl1BrNNonM6Xa53R7PNKI5Eo+iGAWsJmS+qNFpQ2bzNJw1Zq1Ebb6KHF4glE+gbRwlZ2KYVITWasQAem9jIAfoGg8GQ6Gw+GI5Go4G2L7WodwnMEHBgKFGqFCFBQro1HIztpQpkSFBcDcwFBk7goGB8NoCwAjYvhCLhUIacwACgATABWAAcAE4AJRAA)

**Comment by ahejlsberg** [comment] 2020-09-04 00:06
Just took a quick look. It appears we're making bunches of _very_ large tuple types, as in >250,000 elements. We should probably have a limiter in place to cut off the madness at 10,000 elements or so.

**Comment by ahejlsberg** [comment] 2020-09-04 03:50
Actually, doesn't look like it was large tuple types, but rather large type caches I was looking at. Anyways, your seemingly never ending example actually does end after about a minute on my machine:

```
t.ts:15:41 - error TS2589: Type instantiation is excessively deep and possibly infinite.

15     Curr extends [any, any, ...any[]] ? Collatz<HailstoneHelper<Orig, UIncr<HalfAccum>, UDecr<UDecr<Curr>>>> :
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

Files:                6
Lines:            24890
Nodes:           112786
Identifiers:      41026
Symbols:          33488
Types:          1675473
Instantiations: 5000043
Memory used:    379488K
I/O read:         0.00s
I/O write:        0.00s
Parse time:       0.34s
Bind time:        0.14s
Check time:      57.77s
Emit time:        0.01s
Total time:      58.26s
```

Also, according to Wikipedia

> Paul Erdős said about the Collatz conjecture: "Mathematics may not be ready for such problems."[8] He also offered US$500 for its solution.[9] Jeffrey Lagarias in 2010 claimed that based only on known information about this problem, "this is an extraordinarily difficult problem, completely out of reach of present day mathematics."[10]

What makes you think our type checker will do better? 😉

**Comment by DanielRosenwasser** [comment] 2020-09-04 06:24
I will edit the Wikipedia article appropriately:

> Paul Erdős said about the Collatz conjecture: "Mathematics may not be ready for such problems."[8] He also offered US$500 for its solution.[9] Jeffrey Lagarias in 2010 claimed that based only on known information about this problem, "this is an extraordinarily difficult problem, completely out of reach of present day mathematics."[10] In 2020, Anders Hejlsberg said of the conjecture, "Type instantiation is excessively deep and possibly infinite."

**Comment by ahejlsberg** [comment] 2020-09-04 08:41
@DanielRosenwasser So when do I get my $500?

**Comment by ahejlsberg** [comment] 2020-09-08 18:45
Marking this as working as intended. It is indeed possible to write types that take a very long time to resolve and/or relate.

**Closed by ahejlsberg** 2020-09-08 18:45 UTC
Labels: Needs Investigation, Working as Intended
