### ISSUE TITLE
Cannot extend `XMLHttpRequest` when target is `ES5`

### ISSUE THREAD

**Issue by guilhermesimoes** [microsoft/TypeScript#57945] opened 2024-03-26 11:57 UTC
### 🔎 Search Terms

Uncaught TypeError, Failed to construct, DOM object constructor cannot be called as a function

### 🕗 Version & Regression Information

- This is a crash
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [Why doesn't extending built-ins like Error, Array, and Map work?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work)

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=1&ssl=1&ssc=32&pln=1&pc=46#code/MYGwhgzhAECyCeANWAZAEgFwwBwEoFMBHAV3wg2nwA8N8A7AExmXSzyNPOgG8AoaaNgBOASwBuYWtDAAuaHWIBbAEb4hAbl79owAPZ1yQ4sAy6hACgCUPbQIjFsaq5tvQMACxEQAdGGgBeaABGTQEAX14I3gh8EAAzbxZMHAISMgpAhCS2VM4MFz0DCip3IQD5fAB3aGyUjnTnIA

### 💻 Code

```ts
class MyXMLHttpRequest extends XMLHttpRequest {
  private a: number;

  constructor() {
    super();

    this.a = 1;
  }
}

self.XMLHttpRequest = MyXMLHttpRequest;

const xhr = new XMLHttpRequest();
```

### 🙁 Actual behavior

When transpiling to ES5, trying to run the resulting code throws the following error:
> Uncaught TypeError: Failed to construct 'XMLHttpRequest': Please use the 'new' operator, this DOM object constructor cannot be called as a function

This is due to the generated code `_super.call(this)`.

### 🙂 Expected behavior

The ES5 transpile output should behave similarly to the ES2015 transpile output. At least it shouldn't crash.

### Additional information about the issue

Related to https://github.com/microsoft/TypeScript/issues/12949
Related to https://github.com/microsoft/TypeScript/issues/15397

**Comment by nmain** [comment] 2024-03-26 13:05
> Related to https://github.com/microsoft/TypeScript/issues/15397

Does this add any new information or is it just a duplicate of that?

**Closed** 2024-04-14 01:33 UTC
Labels: Duplicate
