### ISSUE TITLE
Type deduction using mapped types and generics

### ISSUE THREAD

**Issue by k34iml0ch** [Microsoft/TypeScript#19211] opened 2017-10-16 13:31 UTC
**TypeScript Version:**  2.5.3, 2.6.0rc

Please consider the following simple type definitions.

```ts
type PropTypes = {
    'prop1': number,
    'prop2': string
}

interface Handler<T> {        
    handle(value: T): T;
}

type HandlerMap = {
    [K in keyof PropTypes]: Handler<PropTypes[K]>
}

let map: HandlerMap;
```

The following is not working. Typescript cannot deduce the actual type of the handler.
**Listing 1:**
```ts
function main1(props: PropTypes) {
    Object.keys(props).forEach((key: keyof PropTypes) => {
        map[key].handle(props[key]); // <--  Cannot invoke an expression whose type lacks a call signature...       
    });
}

main1({
    'prop1': 42 ,
    'prop2': 'Hello World' 
})
```

The followings works.
**Listing 2:**
```ts
function main2(props: PropTypes) {
    Object.keys(props).forEach((key: keyof PropTypes) => {
        let handler = map[key] as Handler<{}> // <-- Works fine using a "cast"
        handler.handle(props[key]);        
    });
}

main2({
    'prop1': 42 ,
    'prop2': 'Hello World' 
})
```

**Listing 3:**
```ts
function main3(props: PropTypes) {
    Object.keys(props).forEach((key: keyof PropTypes) => {
        helper(map[key], props[key]);  // <-- Works fine using a "helper"
    });
}

function helper<K extends keyof PropTypes>(handler: Handler<PropTypes[K]>, value: PropTypes[K]) {
    handler.handle(value);
}

main3({
    'prop1': 42,
    'prop2': 'Hello World'
})
```

**Expected behavior:**

Code in Listing 1 should compile without error 

**Actual behavior:**
```ts
Cannot invoke an expression whose type lacks a call signature. Type '((value: number) => number) | ((value: string) => string)' has no compatible call signatures.
```
[link to playground](https://goo.gl/Wwz6Ht)

**Comment by mhegazy** [comment] 2017-10-25 22:42
Duplicate of https://github.com/Microsoft/TypeScript/issues/7294

**Comment by mhegazy** [comment] 2017-11-09 21:23
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-11-09 21:23 UTC
Labels: Duplicate
