### ISSUE TITLE
Unhelpful error "Two different types with this name exist, but they are unrelated."

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript#19373] opened 2017-10-20 15:13 UTC
**TypeScript Version:**  2.6.0-dev.201xxxxx

**Code**

```ts
interface I {
    m(
        a: number,
        b: number,
        c: number,
        d: number,
        e: number,
        f: number,
        g: number,
        h: number,
        i: number,
    ): number;
}

const x: I = {
    m(a, b, c, d, e, f, g, h, i) { x; }
};
```

**Expected behavior:**

A less confusing error message.

**Actual behavior:**

```
src/a.ts(15,7): error TS2322: Type '{ m(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: nu...' is not assignable to type 'I'.
  Types of property 'm' are incompatible.
    Type '(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: numbe...' is not assignable to type '(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: numbe...'. Two different types with this name exist, but they are unrelated.
      Type 'void' is not assignable to type 'number'.
```

**Comment by DanielRosenwasser** [comment] 2017-10-20 22:59
This should be a matter of just making sure the stringified types are fully displayed before comparing them.

**Comment by DanielRosenwasser** [comment] 2017-10-20 23:00
Also potentially only doing this on type references.

**Comment by MhdTlb** [comment] 2017-11-09 05:03
Can I work on this issue?

**Comment by andy-ms** [comment] 2017-11-10 14:17
@MhdTIb sure.

**Comment by gcnew** [comment] 2017-11-10 14:34
@DanielRosenwasser Isn't full stringification meant to be controlled by `--noErrorTruncation`?

**Comment by mhegazy** [comment] 2017-11-10 22:29
> Isn't full stringification meant to be controlled by --noErrorTruncation?

`--noErrorTruncation` just disables cutting the message if it is too long, before it is written. it does not change how messages are built.

**Comment by gcnew** [comment] 2017-11-11 01:24
Maybe I've misunderstood something. I thought

> This should be a matter of just making sure the stringified types are fully displayed before comparing them.

was referring to the truncated types in the message. I tested with `--noErrorTruncation` and they seemed to be printed in full.

**Comment by mhegazy** [comment] 2017-11-13 18:36
Sorry i miss understood your question.. yes the issue here is caused by truncation. the comparison of the strings should not happen on a truncated one, so the error should not be disabled regardless if `--noErrorTruncation` is on or not.

**Comment by estaub** [comment] 2018-02-26 14:38
I really, really need this error message to point at the files containing the two conflicting definitions!

**Comment by danvk** [comment] 2024-01-18 17:04
This error message seems to have substantially improved with [TypeScript 3.0](https://devblogs.microsoft.com/typescript/announcing-typescript-3-0/), which came out in May of 2018. I assume this is because of the [Improved errors and UX](https://devblogs.microsoft.com/typescript/announcing-typescript-3-0/#improved-errors-and-ux):

2.9.1:

```
issue.ts:15:7 - error TS2322: Type '{ m(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: nu...' is not assignable to type 'I'.
  Types of property 'm' are incompatible.
    Type '(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: numbe...' is not assignable to type '(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: numbe...'. Two different types with this name exist, but they are unrelated.
      Type 'void' is not assignable to type 'number'.

15 const x: I = {
         ~
```

3.0.1:

```
issue.ts:16:5 - error TS2322: Type '(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => void' is not assignable to type '(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => number'.
  Type 'void' is not assignable to type 'number'.

16     m(a, b, c, d, e, f, g, h, i) { x; }
       ~

  issue.ts:2:5
      2     m(
            ~~
      3         a: number,
        ~~~~~~~~~~~~~~~~~~
    ...
     11         i: number,
        ~~~~~~~~~~~~~~~~~~
     12     ): number;
        ~~~~~~~~~~~~~~
    The expected type comes from property 'm' which is declared here on type 'I'
```

So the confusing message about "Two different types with this name exist, but they are unrelated." is gone and both relevant lines are mentioned.

Unless I'm missing something, I think this can be closed as fixed?

**Comment by RyanCavanaugh** [comment] 2024-01-18 17:32
Yep, seems so! 🐦

**Closed by RyanCavanaugh** 2024-01-18 17:32 UTC
Labels: Bug, Help Wanted, Good First Issue, Domain: Error Messages
