### ISSUE TITLE
Find a way to suppress the errors generated by importing modules

### ISSUE THREAD

**Issue by raregrass** [Microsoft/TypeScript#6114] opened 2015-12-16 12:00 UTC
I need to use some external modules without .d.ts files, but, I do not want to use the corresponding third party .d.ts files. Please tell me how to just suppress the errors - "Cannot find the module ...", thinks.

**Comment by DanielRosenwasser** [comment] 2015-12-17 00:51
Would the ideas in #2709 be a suitable way of dealing with this? Something like:

```ts
import * as blah: any from "foo/bar";
```

**Comment by raregrass** [comment] 2015-12-17 01:36
Yes, I will go there for seeking the answer, thinks for your help!
BTW, I think the idea below is good and doesn't need to change any grammar in current project. It's more friendly for developers because sometimes someone maybe want to suppress a special kind of error for debugging and there isn't, maybe I have not noticed, any way to achieve this. Please consider this proposal.

>if it was possible to explicitly ignore specific TS**** errors, that would be an acceptable workaround, e.g. something like this in tsconfig.json:

>```javascript
{
      ignoreRules: {
          "TS2307": true
      }
}
```

**Comment by DanielRosenwasser** [comment] 2015-12-17 04:58
Sure, that's another issue as well (#4094). I'm going to close this as a duplicate of those issues.

**Closed by DanielRosenwasser** 2015-12-17 04:58 UTC
Labels: Duplicate

**Comment by amcdnl** [comment] 2016-06-02 17:08
Would love to see this too.
