### ISSUE TITLE
TypeScript v1.7 MSBuild tooling breaks web application publish

### ISSUE THREAD

**Issue by mattbrooks2010** [Microsoft/TypeScript#5894] opened 2015-12-02 17:27 UTC
# Summary

Installing TypeScript 1.7 tooling for Visual Studio causes different behaviour from 1.6 when publishing web applications, both from within Visual Studio (right click > publish) and via msbuild.exe (`/p:DeployOnBuild=true`).

This issue has only been observed using a file system publish.

# Symptoms

Generated JavaScript is no longer included in the packaged / published output.

# Observations

It appears there is a difference in the MSBuild `Content` ItemGroup's metadata. I believe that previously the generated JavaScript files were being included in the `Content` ItemGroup as paths relative to the `.csproj` file:

    Scripts\App.js    

As of 1.7 it appears the generated JavaScript files are now being included in `Content` as absolute paths:

    C:\Projects\Solution\Web\Scripts\App.js

Perhaps this is causing a problem for the web publishing mechanism?

**Comment by mhegazy** [comment] 2015-12-02 17:56
@paulvanbrenk has been looking into this, we are talking to the azure tools team to figure out the issue and get back to you.

**Comment by mattbrooks2010** [comment] 2015-12-02 18:33
Thanks — please keep me updated. 

What has made this issue worse for me is that uninstalling the VS tooling leaves the MSBuild tooling files in place. 

Repairing the 1.6 tooling installation replaced the .targets and .props files but crucially not the task .dll file which, based on a diff of the compiled code, is possibly where the issue lies. 

I've managed to successfully revert back to the 1.6 tooling for VS 2013 by deleting the TypeScript MSBuild directory before repairing the 1.6 tooling installation. 

To make matters a little more complicated, machines that also had VS 2015 also installed had to have the 1.6 tools for VS 2015 repaired, even though the 1.7 tooling for VS 2015 had not been installed at all.

**Comment by mdsharpe** [comment] 2015-12-02 19:06
:+1:

**Comment by paulvanbrenk** [comment] 2015-12-02 19:55
Can any of you share the `diagnostic` MSBuild log?

**Comment by mattbrooks2010** [comment] 2015-12-02 20:32
I have produced a repro of the issue using `File > New project > Empty ASP.NET Web Application` and can confirm simply overwriting the `TypeScript.tasks.dll` with the one from 1.6 tooling avoids the bug.

How would you like me to supply the repro files?

**Comment by paulvanbrenk** [comment] 2015-12-03 00:53
Ok, I think I have a fix for this specific issue.

**Comment by mattbrooks2010** [comment] 2015-12-03 06:45
Great, thanks. 

Can you indicate when the fix will be available? Is there a workaround other than to avoid 1.7 until the fix is ready?

**Comment by cwmacdon** [comment] 2015-12-03 16:32
This is affecting us.
Is it just a problem with using the custom TypeScriptOutDir?

**Comment by mattbrooks2010** [comment] 2015-12-03 16:34
I'm not using that build output setting.

**Comment by JiriZidek** [comment] 2015-12-03 18:27
StackOverflow here: http://stackoverflow.com/questions/34048228/tfs-build-error-after-installing-visual-studio-2015-update-1

**Comment by paulvanbrenk** [comment] 2015-12-03 20:30
@JiriZidek the issue you linked is VS 2015, the issue discussed here is VS 2013.

**Comment by mattbrooks2010** [comment] 2015-12-03 20:32
But worth noting that VS2015 update 1 ships with TypeScript v1.7 tools. Haven't tried a repro on VS2015 though.

**Comment by paulvanbrenk** [comment] 2015-12-03 21:02
@mattbrooks2010 Don't have an obvious work around, and we're investigating an Azure publishing issue, which makes the timeline uncertain.

**Comment by mattbrooks2010** [comment] 2015-12-03 21:09
@paulvanbrenk thanks for the update.

Given I can swap back to the previous `TypeScript.tasks.dll` from 1.6 and 'fix' the issue, I don't understand how this can be an issue with the web publishing tooling — unless that always had an unsurfaced bug. Please would you elaborate?

**Comment by paulvanbrenk** [comment] 2015-12-03 21:30
There was an issue with the way we calculate the output path when you used the 'outdir' option, however the fix we made wasn't sufficiently tested for the web publishing scenario: we used a full path, where a relative path was expected.

**Comment by mattbrooks2010** [comment] 2015-12-03 21:47
OK so the issue with absolute vs relative paths is consistent with my initial analysis above.

However I don't understand, given this is a behaviour change between the 1.6 and 1.7 tooling, how this is a web publishing or Azure tooling issue. Are absolute `Content` `ItemGroup` paths supposed to be supported?

Thanks for your feedback on this issue so far.

**Comment by paulvanbrenk** [comment] 2015-12-03 21:49
It has to do with how we calculate the path of the generated files, and collect those files for the publishing step. It's not related to the way `.ts` files are represented in the project file.

**Comment by JiriZidek** [comment] 2015-12-03 22:01
I attach full build log, however there is nothing very ineteresting, but the end:

        Creating directory "C:\Builds\3\ICCNG\Development\bin\WebClient\_PublishedWebsites\WebClient\C:\Builds\3\ICCNG\Development\src\Development\WebClient\Scripts".
     1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\WebApplications\Microsoft.WebApplication.targets(182,5): error MSB3021: Unable to copy file "C:\Builds\3\ICCNG\Development\src\Development\WebClient\Scripts\InternalChat.js" to "C:\Builds\3\ICCNG\Development\bin\WebClient\_PublishedWebsites\WebClient\C:\Builds\3\ICCNG\Development\src\Development\WebClient\Scripts\InternalChat.js". Uvedený formát cesty není podporován. [C:\Builds\3\ICCNG\Development\src\Development\WebClient\WebClient.csproj]
         Creating directory "C:\Builds\3\ICCNG\Development\bin\WebClient\_PublishedWebsites\WebClient\C:\Builds\3\ICCNG\Development\src\Development\WebClient\Scripts".
     1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\WebApplications\Microsoft.WebApplication.targets(182,5): error MSB3021: Unable to copy file "C:\Builds\3\ICCNG\Development\src\Development\WebClient\Scripts\InternalChat.js.map" to "C:\Builds\3\ICCNG\Development\bin\WebClient\_PublishedWebsites\WebClient\C:\Builds\3\ICCNG\Development\src\Development\WebClient\Scripts\InternalChat.js.map". Uvedený formát cesty není podporován. [C:\Builds\3\ICCNG\Development\src\Development\WebClient\WebClient.csproj]
     1>Done Building Project "C:\Builds\3\ICCNG\Development\src\Development\WebClient\WebClient.csproj" (default targets) -- FAILED.

Build FAILED.

       "C:\Builds\3\ICCNG\Development\src\Development\WebClient\WebClient.csproj" (default target) (1) ->
       (_CopyWebApplicationLegacy target) -> 
         C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\WebApplications\Microsoft.WebApplication.targets(182,5): error MSB3021: Unable to copy file "C:\Builds\3\ICCNG\Development\src\Development\WebClient\Scripts\InternalChat.js" to "C:\Builds\3\ICCNG\Development\bin\WebClient\_PublishedWebsites\WebClient\C:\Builds\3\ICCNG\Development\src\Development\WebClient\Scripts\InternalChat.js". Uvedený formát cesty není podporován. [C:\Builds\3\ICCNG\Development\src\Development\WebClient\WebClient.csproj]
         C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\WebApplications\Microsoft.WebApplication.targets(182,5): error MSB3021: Unable to copy file "C:\Builds\3\ICCNG\Development\src\Development\WebClient\Scripts\InternalChat.js.map" to "C:\Builds\3\ICCNG\Development\bin\WebClient\_PublishedWebsites\WebClient\C:\Builds\3\ICCNG\Development\src\Development\WebClient\Scripts\InternalChat.js.map". Uvedený formát cesty není podporován. [C:\Builds\3\ICCNG\Development\src\Development\WebClient\WebClient.csproj]

    0 Warning(s)
    2 Error(s)

**Comment by mattbrooks2010** [comment] 2015-12-03 22:08
@paulvanbrenk sure, I understand that. I'm referring to this:

    <ItemGroup>
      <FilesForPackagingFromProject Include="@(GeneratedJavascriptWithTargetPath->'%(Identity)')"/>
      <ContentWithTargetPath Include="@(GeneratedJavascriptWithTargetPath->'%(Identity)')"/>
      <Content Include="@(GeneratedJavascript->'%(Identity)')"/>
    </ItemGroup>

The issue is related to the contents of one of those `ItemGroup`s. The difference in that content between 1.6 and 1.7 is due to different code in `TypeScript.tasks.dll`, am I correct?

So I'm still not clear how this is a web publishing issue.

**Comment by paulvanbrenk** [comment] 2015-12-03 22:13
The files in this collection don't have the right relative path `GeneratedJavascriptWithTargetPath`, which the web publishing task expect.

**Comment by paulvanbrenk** [comment] 2015-12-03 22:16
@JiriZidek the interesting bits are not in this log, I need the 'diagnostic' log, which you can get with the `/v:diagnostic /fl` option.

**Comment by mattbrooks2010** [comment] 2015-12-03 22:35
@paulvanbrenk right! So, why is this an Azure publishing issue, making the timeline for a fix uncertain?

**Comment by paulvanbrenk** [comment] 2015-12-03 22:41
The Azure publishing is a different issue, but touches similar code paths; we need to make sure all publishing scenarios work. And we prefer to publish a single new installer which fixes both issues.

**Comment by mattbrooks2010** [comment] 2015-12-03 22:43
OK thank you for the clarity.

**Comment by SoftwareByBrent** [comment] 2015-12-04 13:20
I can confirm this is happening with an installation of VS 2015 update 1.  We have a build machine that has TFS 2015 update 1 on and VS 2015 update 1 on it.  This machine used to have just the RTM versions of both.  After updating, the same errors occur, but our build machine says the specific error is something like "the path is not supported" I'll update with the log using the /v:diagnostic like you were describing above.  If I do that does it just add more to the log file that I just need to paste in here? which part are you specifically looking for?  

it gave up on doing the rest after one or two of the files failed.  It does as you described, it adds the full path rather than the relative one twice and I get the error of "The given path's format is not supported."

Please let me know where to find this extra diagnostic log info and provide it.  We have CI builds on almost all of our projects, and right now only one the ones with typescript are failing.  so, while it could be related to web publishing, I think it could just be the typescript builder too.

**Comment by pmiddleton** [comment] 2015-12-04 16:02
I am having the same issue.  TFS is 2013 on premise and the build machine is running VS 2015 Update 1.          

I have turn on the flags you mentioned and attached the build output.  Let me know if there is something else you need.

[BHP.txt](https://github.com/Microsoft/TypeScript/files/52218/BHP.txt)

**Comment by paulvanbrenk** [comment] 2015-12-04 23:48
Thanks @pmiddleton that file was useful.

**Comment by JamesDSch** [comment] 2015-12-06 01:00
My team hit the Azure version of this issue.  We worked around it by manually adding ContinueOnError="WarnAndContinue" to the Copy task within the CopyWebRoleFiles target, within Microsoft.WindowsAzure.targets.  The compiled .js files are still copied, possibly via some other mechanism.  There are a lot of warnings, but at least the Azure publishes work.

**Comment by JudahGabriel** [comment] 2015-12-07 17:09
After installing VS 2015 Update 1, we are hitting this issue as well.

This is urgent for us, because it's blocking us from publishing to our Azure cloud service.

The error we get is "Unable to copy file [path to .js file generated from .ts] to file [new file incorrect file path, incorrect due to duplicate absolute path]. The given path's format is not supported.

**Comment by PageEngine** [comment] 2015-12-07 17:42
We have the Azure publish issue as well. Same scenario. Workaround mentioned above does not fix for us, and we still cannot publish. SO here: http://stackoverflow.com/questions/34100740/error-copying-typescript-files-after-packaging-azure-project-visual-studio-201

**Comment by mhegazy** [comment] 2015-12-07 22:58
@PageEngine this is tracked by #4714

**Comment by paulvanbrenk** [comment] 2015-12-07 22:59
Figured out what's happening, when you specify `$(OutDir)` in your project, which generally only happens on build servers, a different code path gets executed for copy-ing files to the final location. I have a fix for this checked in, which we're working on to get into your hands for testing.

Thanks for all the logs and feedback!

**Comment by gaziqbal** [comment] 2015-12-07 23:15
I don't have an $(OutDir) specified in my **web** project. However I am still running into this error when I try to publish the **cloud** project which references the web project. There are no build servers involved. This is all on the local dev box.

Using mattbrooks2010 workaround of reverting to the **TypeScript.tasks.dll** which shipped with Typescript **1.6** fixes this for me.

**Comment by paulvanbrenk** [comment] 2015-12-07 23:27
@gaziqbal Looks like cloud projects specify the $(OutDir) in their build, I don't have any issues building/publishing those with my fixes.

**Comment by PageEngine** [comment] 2015-12-07 23:35
Just a further reference point: we have the same symptom as @gaziqbal. No build server, all on a single dev machine, web project without $(OutDir), compiles fine but fails when we try to package an Azure cloud service which references the web project.

**Comment by nicholashead** [comment] 2015-12-08 05:08
Having same issues but I reported on msbuild repo (see above). Looking forward to a resolution.

**Comment by KentSwan** [comment] 2015-12-09 20:25
I am having this same issue, when it comes time to copy files to to the _PublishedWebsites\app\ folder (as defined in the Microsoft.WebApplication.targets file, Target Name="_CopyWebApplicationLegacy") it has the absolute path twice (eg C:\Builds\1\App\_PublishedWebsites\C:\Builds\1\App\Scripts\SomeScript.js).

It is a problem with the TypeScript.Tasks.dll.  I copied back the 1.6 version and now our automated builds work again.

**Comment by mhegazy** [comment] 2015-12-11 00:48
We think we have a fix for this. 

@KentSwan, @nicholashead, @PageEngine, @gaziqbal, @JudahGabriel, @JamesDSch, @pmiddleton, @mattbrooks2010 , @brentdavid2008 @JiriZidek, and @mdsharpe -- Can you try [VS 2015 TS 1.7.6 Update](http://go.microsoft.com/fwlink/?LinkID=717098) or [VS 2013 1.7.5 Update](http://go.microsoft.com/fwlink/?LinkID=717464) and let us know if it solves the issue?

**Comment by JamesDSch** [comment] 2015-12-11 01:13
@mhegazy Just tried for VS2015 and our Azure cloud service publish worked fine; we're back in business!  Thanks for fixing this prior to the next scheduled release.

**Comment by brentdavid2008** [comment] 2015-12-11 01:24
This works for us too.  TFS 2015 update 1 Xaml Builds normal web publishing - non Azure. Thanks!

**Comment by ckapatch** [comment] 2015-12-11 02:58
@mhegazy Thank you, my azure web project published after the installation of the update.

**Comment by PageEngine** [comment] 2015-12-11 03:36
@mhegazy  Fixed here as well on VS 2015 (did not test VS 2013), packaging for an Azure cloud service. Have answered my SO question with links to the downloads. Thanks for the quick fix.

**Comment by mattbrooks2010** [comment] 2015-12-11 08:59
Tested using VS2013.5 desktop build / publish and also TFS2015.1 CI build and publish. Original reported symptoms have been fixed. Thanks!

**Comment by JiriZidek** [comment] 2015-12-12 13:11
Tested succesfully on TFS2015.1 classical XAML build. Thx.

**Comment by MarcioMonego** [comment] 2015-12-13 14:04
I was caught by the same problem on 1.7.4
Resolved in 1.7.6
Thank you!

**Comment by nicholashead** [comment] 2015-12-14 17:49
Working great here. Thanks for being so fast with a fix! Another test case for the books, eh? :+1:

**Comment by ccrabb** [comment] 2015-12-14 22:09
1.7.6 on our build server solved problems here as well! Thanks!

**Comment by PavelAgejkin** [comment] 2015-12-15 09:14
Hi,
I tried to install VS 2015 TS 1.7.6 Update on my build machine with no luck.
First I installed https://connect.microsoft.com/VisualStudio/ExtendVS Isolated Shell
Then Installed VS 2015 Update 1
Then trying to install TS 1.7.6 I get "This version of TypeScript requires Visual Studio 2015 Update 1 to be installed"

How can I install TS 1.7.6 on my build machine without installing full version of VS?
P.S. same scenario with VS 13 isolated shelled worked fine with TS 1.7.5

**Comment by paulvanbrenk** [comment] 2015-12-15 19:41
The build tools for VS 2013 and VS 2015 are identical, so for your build server installing the VS 2013 bits should be sufficient. 

You may have to copy the files from:

`C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript`

to

`C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\TypeScript`

We'll make sure any future installers work as expected.

**Comment by paulvanbrenk** [comment] 2015-12-17 23:02
Closing this since it's been resolved and verified.

**Closed by paulvanbrenk** 2015-12-17 23:02 UTC
Labels: Bug, Fixed, Visual Studio
