### ISSUE TITLE
TS1003: Identifier expected on correct syntax

### ISSUE THREAD

**Issue by falkenhawk** [microsoft/TypeScript#42313] opened 2021-01-13 09:41 UTC
# Bug Report

### 🔎 Search Terms

TS2300: Duplicate identifier '(Missing)'.
TS1003: Identifier expected.
TS1005: ',' expected.
template literal
arrow function return object literal parentheses

### 🕗 Version & Regression Information

When did you start seeing this bug occur?
- Typescript 4.1.3

- This is a crash
- This changed between versions 4.0.5 and 4.1.3

Tried `typescript@next`, **still occurs with** `typescript@4.2.0-dev.20210113`

One of my files started crashing the compiler with lots of errors. It turned out typescript is triggered by some specific combination of arrow function + return object literal + template string + that `.includes(ctx.state.user.id)` part in the condition inside the funciton.

Removing any of these from the equation makes typescript happy and no errors thrown anymore.

For now I have worked it around by changing the if condition from `if (userIds.includes(ctx.state.user.id))` to `if (userIds && userIds.includes(ctx.state.user.id))` **(prepended `userIds &&`)** and typescript is now content with that. :)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.3#code/MYewdgzgLgBA5gJwIYAcAWBHANjAvDACgEo8A+QgbwCgYYBbAVyiSgEtwIAuGAAxtpgAzEFiwgA7gQYQApggCSAEy4wA2vLBQAhAF0tRbgCEQImUjD8eAGn4IZEEQDc5K6gPpMW7SNzfuhImLi3AQgAEYAVtzmAJ5WMBQw0nJKEDAAvr5JsgrK3GAMdGFyqjoZ8cBQAB7RYDEkuOR+-jCsgoTJuRAAdKxgwFgMivYElVXd0Cwy3Z29ikQkzS0wUGgIEjBgMuIwAKII6wgEAOS7AEpnAPoAcgCCZwDC8gDKzy8AspcA8gBq5wBiABkvgB1Y5EADc-Ba6So0P8digDAQYBWCAYMihMJs7nSOPKVHSkKoQA)

### 💻 Code

Minimal code example I extracted from my failing file:

```ts
const graphql = () => ({
  mutations: `
    follow(userIds: [Int!]!): Boolean
  `,
  resolvers: {
    mutations: {
      follow: (obj: any, { userIds }: { userIds: number[] }, ctx: any) => {
        if (userIds.includes(ctx.state.user.id)) {
          throw new Error('ERR_NARCISSISM_OVERFLOW');
        }

        return true;
      },
    },
  },
});
```

### 🙁 Actual behavior

Compiler errors:
In addition to the errors below, my IDE (jetbrains phpstorm) shows also `TS2300: Duplicate identifier '(Missing)'.` where the template literal starts.

```bash
$ tsc --noEmit true
src/modules/ow-friends/graphql.ts:2:14 - error TS1003: Identifier expected.

2   mutations: `
               ~
3     follow(userIds: [Int!]!): Boolean
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4   `,
  ~~~

src/modules/ow-friends/graphql.ts:4:4 - error TS1138: Parameter declaration expected.

4   `,
     ~

src/modules/ow-friends/graphql.ts:8:20 - error TS1005: ',' expected.

8         if (userIds.includes(ctx.state.user.id)) {
                     ~

src/modules/ow-friends/graphql.ts:8:29 - error TS1005: ',' expected.

8         if (userIds.includes(ctx.state.user.id)) {
                              ~

src/modules/ow-friends/graphql.ts:8:33 - error TS1005: ',' expected.

8         if (userIds.includes(ctx.state.user.id)) {
                                  ~

src/modules/ow-friends/graphql.ts:8:39 - error TS1005: ',' expected.

8         if (userIds.includes(ctx.state.user.id)) {
                                        ~

src/modules/ow-friends/graphql.ts:8:44 - error TS1005: ',' expected.

8         if (userIds.includes(ctx.state.user.id)) {
                                             ~

src/modules/ow-friends/graphql.ts:8:48 - error TS1005: ';' expected.

8         if (userIds.includes(ctx.state.user.id)) {
                                                 ~

src/modules/ow-friends/graphql.ts:8:50 - error TS1005: '=>' expected.

8         if (userIds.includes(ctx.state.user.id)) {
                                                   ~

src/modules/ow-friends/graphql.ts:13:7 - error TS1128: Declaration or statement expected.

13       },
         ~

src/modules/ow-friends/graphql.ts:13:8 - error TS1128: Declaration or statement expected.

13       },
          ~

src/modules/ow-friends/graphql.ts:14:5 - error TS1128: Declaration or statement expected.

14     },
       ~

src/modules/ow-friends/graphql.ts:14:6 - error TS1128: Declaration or statement expected.

14     },
        ~

src/modules/ow-friends/graphql.ts:15:3 - error TS1128: Declaration or statement expected.

15   },
     ~

src/modules/ow-friends/graphql.ts:15:4 - error TS1128: Declaration or statement expected.

15   },
      ~

src/modules/ow-friends/graphql.ts:16:1 - error TS1128: Declaration or statement expected.

16 });
   ~

src/modules/ow-friends/graphql.ts:16:2 - error TS1128: Declaration or statement expected.

16 });
    ~


Found 17 errors.
```

### 🙂 Expected behavior

No compiler errors.

**Comment by Kingwl** [comment] 2021-01-13 10:20
It's seems a regression.

It's works fine at https://www.typescriptlang.org/play?ts=4.1.0-dev.20200907 and not at https://www.typescriptlang.org/play?ts=4.1.0-dev.20200910  

The 0909 and 0908 cannot access

**Comment by RyanCavanaugh** [comment] 2021-01-13 18:17
Short version
```ts
const graphql = () => ({
  mutations: ``,
  follow: () => {
    if (isNaN(0)) {
    }
  }
});
```

This is worrisome from a performance perspective, since the necessary `if (f(x))` block would seem to imply that we're doing some sort of long-ranging lookahead at the template literal

**Comment by IllusionMH** [comment] 2021-01-13 19:23
May be #39014 will help with this case as well?

**Comment by RyanCavanaugh** [comment] 2021-01-13 19:25
Good pointer @IllusionMH; looks like a straight duplicate of https://github.com/microsoft/TypeScript/issues/32914

**Closed** 2021-01-16 18:00 UTC
Labels: Duplicate

**Comment by luismendes070** [comment] 2021-11-08 03:41
type FunctionReturnType = ReturnType<typeof Function | typeof Number>;// typescript 1003 private name

function fun(n:NumberReturnType):FunctionReturnType{
return n*2;
}
