### ISSUE TITLE
Only the last overloaded signature is picked when passing an overloaded function to Array.map

### ISSUE THREAD

**Issue by vfsfitvnm** [microsoft/TypeScript#55840] opened 2023-09-23 15:10 UTC
### 🔎 Search Terms

"overload",  "last overload", "is not assignable to parameter of type", "Array.map"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20230923&ssl=2&ssc=1&pln=3&pc=1#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwAoA3KCZEALngGcMYtUBzAShvsZYG4BYAKFCRYCFOmx4CxMhWrxUyALYAjEDHbylqmH34CweevBgAGDgybMA2gF14AXnhWARFGcAaeM+XObAOkUoAAciAH0HAD4pMNZWbngAegT4HABrfUMMYwBGcy5rO0cXN09vXwDgokRCOMTktRgcGAEgA

### 💻 Code

```ts
declare function foo(value: string): string;
declare function foo(value: number): number;

const r0: string[] = ["a", "b"].map(_ => foo(_)); // ok
const r1: string[] = ["a", "b"].map(foo); // error, number is inferred
```

### 🙁 Actual behavior

It looks like when `foo` is passed "directly" (that is without a wrapper arrow function), its signature is the last one that was declared. Swapping the first two lines works around the issue, indeed.

### 🙂 Expected behavior

It should iterate through all the possible overloads.

**Comment by MartinJohns** [comment] 2023-09-23 15:49
Sounds like a duplicate of #47571.

**Closed** 2023-10-08 01:28 UTC
Labels: Duplicate
