### ISSUE TITLE
Compiler assumes function assigned on declaration exists on prototype

### ISSUE THREAD

**Issue by mootari** [Microsoft/TypeScript#20955] opened 2018-01-01 14:01 UTC
**TypeScript Version:**  2.7.0-dev.20171230

**Code**

```ts
class Foo {
  func = function () { }
}
Foo.prototype.func();
```

**Expected behavior:**
Compiler detects that `Foo.prototype.func()` does not exist.

**Actual behavior:**
`Foo.prototype.func()` passes without errors, but produces error when running the compiled Javascript.

**Comment by HerringtonDarkholme** [comment] 2018-01-02 02:45
Please also see https://github.com/Microsoft/TypeScript/issues/20922#issuecomment-354487214

**Comment by DanielRosenwasser** [comment] 2018-01-02 03:09
Like @HerringtonDarkholme said, this seems to be a duplicate of #20922

In the future using the issue tracker's search functionality can make it easier for us to triage issues. Thanks!

**Comment by mootari** [comment] 2018-01-02 09:31
> In the future using the issue tracker's search functionality can make it easier for us to triage issues. Thanks!

I saw the issue listed but didn't realize it'a the same case. Sorry for the noise!

**Closed** 2018-01-16 18:43 UTC
Labels: Duplicate
