### ISSUE TITLE
 IntelliSense for StyleSheet not working

### ISSUE THREAD

**Issue by josemigallas** [Microsoft/TypeScript#29180] opened 2018-12-21 15:25 UTC
Intellisense won't work inside `StyleSheet.create({})` after adding a second style:

![intellisense-stylesheet-bug](https://user-images.githubusercontent.com/11672286/50349663-e33b4600-053c-11e9-93a8-8029c5c94100.gif)

- VSCode Version: `1.24.1` && `1.30.0-insider`
- OS Version: `macOS 10.14.1`

Steps to Reproduce:

1. Create a StyleSheet using `StyleSheet#create` with a class.
2. Adding the first style, intellisense will work.
3. Adding a second style, intellisense will only work if adding it above the first one but not beneath.
4. Adding more styles, intellisense will not work anymore.

Does this issue occur when all extensions are disabled?: Yes

_Migrated from: https://github.com/Microsoft/vscode-react-native/issues/306_

**Comment by mjbvz** [comment] 2018-12-28 00:49
Tested with typescript@3.3.0-dev.20181222

Example code:

```ts
import { StyleSheet } from 'react-native';

StyleSheet.create({
    class: {
        padding: 1,
        mar
    }
})
```

`padding` is a suggestion; `margin` is not

**Comment by kerrexwong** [comment] 2019-01-02 16:03
I get the same issue now

**Comment by weswigham** [comment] 2019-01-02 19:21
Duplicate of #28470 and probably more issues. Root cause is the object satisfies the constraint and becomes the contextual type at that position, which then informs completions (when really you still want completions to be informed from the uninstantiated type parameter).

**Closed** 2019-01-05 18:00 UTC
Labels: Duplicate

**Comment by HaloWang** [comment] 2019-02-27 09:31
[#306](https://github.com/Microsoft/vscode-react-native/issues/306#issuecomment-467780654)
