### ISSUE TITLE
Type alias circularly references itself (5.4 regression)

### ISSUE THREAD

**Issue by ShacharHarshuv** [microsoft/TypeScript#58302] opened 2024-04-24 13:06 UTC
### 🔎 Search Terms

Type alias circularly references itself (5.4 regression)

### 🕗 Version & Regression Information

- This changed between versions 5.3.3 and 5.4.5

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.5#code/C4TwDgpgBAQg9nANhAhgOwAouACwM4A8AKgHxQC8UewATgJZoDmUAZALABQUUA3p99wDaAaSgMoAawgg4AMyhEAugC4FIxVAgAPYBDQATPFABGCZOn4DuAfijDLV1UXWadew1DjGAVhADGwA4CtqLaugZGaACuALbGEDRQAD5UtAyMQVa2AAYAJDzCAL4AdPnwSKiY2PjE6iSF2ZkCqmgQAG4JTS3tCQDcloWCUjLySv0c-EA

### 💻 Code

```ts
type BooleanPaths<T> = string &
  {
    [K in keyof T]: T[K] extends boolean
      ? K
      : T[K] extends object
      ? K extends number | string
        ? `${K}.${BooleanPaths<T[K]>}`
        : never
      : never;
  }[keyof T];
```

### 🙁 Actual behavior

This code fails with two errors: 

Type alias 'BooleanPaths' circularly references itself.
Type 'BooleanPaths' is not generic.

### 🙂 Expected behavior

The compilation should pass, as it has in previous versions.

**Comment by RyanCavanaugh** [comment] 2024-04-24 22:57
Bisects to #56515

**Comment by ahejlsberg** [comment] 2024-05-06 17:50
The issue is that following #56515 we perform constraint reduction on intersection types `T & P` or `P & T`, where T is a type parameter or indexed access type and `P` is a primitive type, the `object` type, or `{}`, reducing the intersection type to just `T` when the constraint of `T` fully encompasses `P`. For example, for a `T extends string`, the intersection `T & string` is reduced to just `T`. In the repro, we attempt to reduce the intersection `string & {...}[keyof T]`, but resolving the constraint of `{...}[keyof T]` causes a circularity. It's unfortunate, but the price we have to pay to get the benefits of the feature.

I'd suggest rewriting the `BooleanPaths` type to this simpler formulation:

```ts
type BooleanPaths<T, K extends keyof T = keyof T> =
    K extends string ?
      T[K] extends boolean ? K :
      T[K] extends object ? `${K}.${BooleanPaths<T[K]>}` :
      never :
    never;
```

No circularity and handles both object and tuple types.

**Closed** 2024-05-09 01:28 UTC
Labels: Design Limitation
