### ISSUE TITLE
Separate removeComments parameter for js and d.ts

### ISSUE THREAD

**Issue by sosoba** [microsoft/TypeScript#55263] opened 2023-08-04 06:56 UTC
### 🔍 Search Terms

Currently, the `removeComments` setting affects both emitted JS code and type definition files.

In practice, we need both leaving jsDocs in d.ts files and removing completely unnecessary comments (todo markers, eslint, etc.) from js files.

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Add a second parameter `removeJsComments`

### 📃 Motivating Example

This improvement requires minimal code changes:

Function `emitJsFileOrBundle` on `/src/compiller/emitter.ts`  from:
```ts
        const printerOptions: PrinterOptions = {
            removeComments: compilerOptions.removeComments,
```
to 
```ts
        const printerOptions: PrinterOptions = {
            removeComments: compilerOptions.removeJsComments ?? compilerOptions.removeComments,
```

See [emitJsFileOrBundle](https://github.com/microsoft/TypeScript/blob/d045f18928f33bdae2c761615d04cf8aeffd90fc/src/compiler/emitter.ts#L842C1-L860C60) and [emitDeclarationFileOrBundle](https://github.com/microsoft/TypeScript/blob/d045f18928f33bdae2c761615d04cf8aeffd90fc/src/compiler/emitter.ts#L892C1-L919C60).

### 💻 Use Cases

1. What do you want to use this for? 
###  For building library code
2. What shortcomings exist with current approaches?
### Single, common setting.
3. What workarounds are you using in the meantime?
### Use `typescript` [via API](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API) with uggly code:
```js
Object.defineProperty(parsedCommandLine.options, 'removeComments', {
  get: () => new Error().stack?.includes('emitJsFileOrBundle'),
});
```

**Comment by MartinJohns** [comment] 2023-08-04 08:13
Duplicate of #45187 / #38427. Used search terms: `removeComments in:title`

The search terms you used seem very elaborate.

**Closed** 2023-08-07 01:31 UTC
Labels: Duplicate
