### ISSUE TITLE
Output from JavaScript operator `typeof` should be type-checked as a string

### ISSUE THREAD

**Issue by patik** [microsoft/TypeScript#54887] opened 2023-07-05 10:49 UTC
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue: `typeof`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

The [traditional `typeof` operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof) (_not_ [the TS one](https://www.typescriptlang.org/docs/handbook/2/typeof-types.html)!) returns a string, but TypeScript does not always type-check it as such:

```ts
// The compiler throws two exceptions for this:
// This comparison appears to be unintentional because the types 'string' and 'never[]' have no overlap.(2367)
// This condition will always return 'false' since JavaScript compares objects by reference, not value.(2839)
if (typeof foo === []) {
    //
}

// But the compiler does allow this, even though the lefthand side is a string and the righthand side is `undefined`
if (typeof foo === undefined) {
    // 
}
```

[Playground](https://www.typescriptlang.org/play?#code/FDDGHsDsGcBcAIBm5zwLzwOSbFO8AjAQwCd14BvAXxGAHo74AVACwFNo35oXwBXADYATeEQEDCXNiRLgS0SaCJ9O8cInix23WCQCWoBGwCOfMXtgBPeKHagA1sCsAHNuqQp0aDJEECnlq7uyKjeGHyQQmyIepBsQgFBGiFeGMQkQA)

When strict equality is used, I would expect the compiler to also throw `2367` and `2839` when  This seems to be the case for `undefined`, `null`, and `{}`. 

## 📃 Motivating Example

This code is allowed, but I think TS should have caught it:

```ts
if (typeof window === undefined) {
    //
}
```

## 💻 Use Cases

The output of `typeof` is often compared to other variables, and TS should make sure those variables are also strings, at least when using `===`.

**Comment by Josh-Cena** [comment] 2023-07-05 11:18
Duplicate of https://github.com/microsoft/TypeScript/issues/29200

**Comment by fatcerberus** [comment] 2023-07-05 11:29
Also note this is not specific to `typeof`.  `typeof foo` *is* in fact already typed as `string`; [comparison of anything with `undefined` is just always allowed.](https://github.com/microsoft/TypeScript/issues/29200#issuecomment-450572362)

**Comment by Andarist** [comment] 2023-07-05 11:46
It would be fairly easy to improve this situation for `noUncheckedIndexedAccess` but I have no idea how to improve this outside of this setting. The problem is that this code has to work:
```ts
function parse(config: Record<string, number>) {
  if (config.a === undefined) {
  }
}
```
And we have no way of knowing if the left type in this comparison comes from the index signature or not. The check responsible for allowing those comparisons can be found in `isTypeEqualityComparableTo`

**Closed** 2023-07-09 01:34 UTC
Labels: Duplicate
