### ISSUE TITLE
Generic is handled as a greater than comparison using autocomplete

### ISSUE THREAD

**Issue by Nimrodxx** [Microsoft/TypeScript#8754] opened 2016-05-23 12:55 UTC
Hello folks, I have a really irritating bug in Visual Studio 2015 Update 2 using TypeScript. The auto complete dialog in combination with generics works a little bit fuzzy. It treats it like a greater than comparison. Look at the code below.

**TypeScript Version:** 

1.8.30.0

**Code**

```ts
// Function declaration
function invoke<T>(methodName: string, ...args: any[]) {
}
// Call the function, Type first letter of the generic T.
invoke<M
// Auto complete window pops up, which is expected.
// I choose Model from the auto complete window using "enter".
invoke < Model
// Notice the inserted spaces, the compiler thinks its a greater than comparison. While its actually a generic.
```

**Expected behavior:**

```ts
// I expect Model to be inserted without spaces.
this.invoke<Model
```
**Actual behavior:** 
```ts
// I actually inserts it with spaces.
this.invoke < Model
```

**Comment by mhegazy** [comment] 2016-05-23 19:02
This only happens when the commit character is enter.  @CyrusNajmabadi should not the enter here be ignored and used to trigger formatted on the Roslyn side?

**Comment by CyrusNajmabadi** [comment] 2016-05-23 19:20
Yup.  That seems reasonable.   We likely need to have this be a controllable option on the part of the language.  @mattwar would this be somehting we could add configuration support for in our new completion model?

**Comment by falsandtru** [comment] 2016-05-23 19:30
@mhegazy @CyrusNajmabadi Seems a duplicate of #6079 or #6123.

**Comment by mhegazy** [comment] 2016-05-23 19:32
duplicate of #6123. thanks @falsandtru.

**Comment by Nimrodxx** [comment] 2016-05-24 08:04
Sorry actually did a quick search for duplicates but didn't find any. Obviously wasn't paying attention.

**Closed** 2016-05-24 17:03 UTC
Labels: Bug, Duplicate, Visual Studio
