### ISSUE TITLE
Factory closure constructor inferring type act like "not sure" or "confused"

### ISSUE THREAD

**Issue by renjithspace** [microsoft/TypeScript#52245] opened 2023-01-15 08:15 UTC
# Bug Report

### 🔎 Search Terms

closure, infer

### 🕗 Version & Regression Information

- I think this is a generic issue, not a specific version related

### 💻 Code

```ts
// Example 1

class Car {
  speed = 45;
}

/**
 * Vehicle factory constructor
 * 
 * This Vehicle constructor simply return
 * and instance of Car.
 */
class Vehicle {
  speed = 35;

  constructor() {
    return new Car();
  }
}

const vehicle = new Vehicle(); // Inferring as instance of `Vehicle` instead of `Car`, why?

console.log(vehicle.speed); // 45
// If `vehicle` is an instance of `Vehicle` the `vehicle.speed` should return 35, right?
```

```ts
// Example 2

type VehicleType = "car" | "motorcycle";

class Car {
  speed = 35;
}

class Motorcycle {
  speed = 45;
}

class Vehicle {
  static construct(type: VehicleType) {
    switch (type) {
      case "car":
        return new Car();
      case "motorcycle":
        return new Motorcycle();
      default:
        throw new Error("Invalid vehicle type");
    }
  }
}

const vehicle = Vehicle.construct("car"); //Inferring as `Car` | `Motorcycle`, why not just `Car`?
console.log(vehicle.speed); // 35

// There's no confusion for runtime,
// it clearly identifies vehicle is a car and returns its `speed` correctly
// Is this a weakness of inferring types in typescript?
```

### 🙁 Actual behavior

In both examples, the `Vehicle` instance is not inferring the correct type that matches the `runtime` behavior.

### 🙂 Expected behavior

In both examples, the `Vehicle` instance infers the correct type that matches the `runtime` behavior.

**Comment by IllusionMH** [comment] 2023-01-15 08:59
Looks related to or duplicate of #38519, #11588 etc.

**Comment by MartinJohns** [comment] 2023-01-15 09:34
And regarding example 2: Nothing in the functions type signature it indicates that the argument `"car"` will always return a `Car`. TypeScript does not go and analyze the logic within the function to determine the return type.

**Closed** 2023-01-26 18:00 UTC
Labels: Duplicate
