### ISSUE TITLE
Compiler crash on deriving union signature

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#5379] opened 2015-10-23 14:17 UTC
```typescript
function f(...a: string[]) { }

function g(a: string, b: string, c: string) { }

var x1: typeof g | typeof f;

x1(1) 
```

**Comment by zhuravlikjb** [comment] 2015-10-23 14:20
```
C:\Users\Anton.Lobov\Desktop\ts-latest-github\TypeScript\built\local\tsc.js:36478
                throw e;
                      ^
TypeError: Cannot read property 'flags' of undefined
    at getTypeOfSymbol (C:\Users\Anton.Lobov\Desktop\ts-latest-github\TypeScript\built\local\tsc.js:15667:23)
    at compareSignatures (C:\Users\Anton.Lobov\Desktop\ts-latest-github\TypeScript\built\local\tsc.js:18397:107)
    at findMatchingSignature (C:\Users\Anton.Lobov\Desktop\ts-latest-github\TypeScript\built\local\tsc.js:16237:21)
    at findMatchingSignatures (C:\Users\Anton.Lobov\Desktop\ts-latest-github\TypeScript\built\local\tsc.js:16259:59)
    at getUnionSignatures (C:\Users\Anton.Lobov\Desktop\ts-latest-github\TypeScript\built\local\tsc.js:16281:47)
    at resolveUnionTypeMembers (C:\Users\Anton.Lobov\Desktop\ts-latest-github\TypeScript\built\local\tsc.js:16313:34)
    at resolveStructuredTypeMembers (C:\Users\Anton.Lobov\Desktop\ts-latest-github\TypeScript\built\local\tsc.js:16402:21)
    at getSignaturesOfStructuredType (C:\Users\Anton.Lobov\Desktop\ts-latest-github\TypeScript\built\local\tsc.js:16559:32)
    at getSignaturesOfType (C:\Users\Anton.Lobov\Desktop\ts-latest-github\TypeScript\built\local\tsc.js:16569:20)
    at resolveCallExpression (C:\Users\Anton.Lobov\Desktop\ts-latest-github\TypeScript\built\local\tsc.js:21545:34)
```

**Comment by mhegazy** [comment] 2015-10-23 16:31
@sandersn can you take a look.

**Comment by sandersn** [comment] 2015-10-23 16:47
Looking ... I can only get it to repro when one function of the union has a rest parameter and the other function has more than one parameter. Otherwise it dies with "Cannot invoke an expression whose type lacks a call a signature." 

So I suspect that `((...a: string[]) => void) | (a: string, b: string) => void)` is not supposed to have a call signature either, it's just getting missed. I'll see what the spec says.

**Comment by zhuravlik** [comment] 2015-10-23 18:19
This is related to change https://github.com/Microsoft/TypeScript/pull/4200.
(I was studying how it is supposed to work and invented this test case, on which the compiler crashed.)
It's not mentioned in the spec at all (maybe not yet).

As far as I understood from what's done there, `((...a: string[]) => void) | (a: string, b: string) => void)` since 1.6 is supposed to have signature `(a: string, b: string) => void`, because it has partial match with '(...a: string[])' by the first two parameter.
Seems that crash happens because it tries to compare non-existing param of the first signature to the second param 'b', instead of comparing rest-induced parameter to it.

Reproduces always when the first signature has a trailing rest param and less parameters than the second signature.

**Comment by sandersn** [comment] 2015-10-23 18:57
It was just a simple error in `compareSignatures`. The line is 
```ts
let s = source.hasRestParameter && i === sourceLen - 1 ? getRestTypeOfSignature(source) : getTypeOfSymbol(source.parameters[i]);
```

Notice that the comparison is `i === sourceLen - 1`. It should be `i >= sourceLen - 1`. As @zhuravlik says, a fixed signature that is longer than a signature with a rest parameter will incorrectly try to `getTypeOfSymbol` of a non-existing parameter on the signature with the rest-parameter.

I'll have a fix out shortly. After the fix is in place, type checking of the function union proceeds as I expect it to from reading the spec. I added some conformance tests to clarify.

**Closed** 2015-10-23 21:54 UTC
Labels: Bug
