### ISSUE TITLE
Intellisense - JSX element type '{ComponentName}' does not have any construct or call signatures

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24893] opened 2018-06-12 01:19 UTC
_From @ShawnCholeva on June 11, 2018 23:34_

- VSCode Version: 1.24.0
- OS Version: Windows 10

Steps to Reproduce:

1.  Download the project form this repo: https://github.com/ShawnCholeva/matierialui-import-issue
2.  Run yarn command in folder that contains package.json
3.  Navigate to src/home/home.tsx .
4.  View intellisense issue.
5.  Rename home.tsx to home.jsx, and view that the intellisense error is no longer there.

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#51644_

**Comment by roostapour** [comment] 2018-06-12 20:37
I get the same error with the elements from material-ui. The code compiles without any error. Only Visual Studio Code shows lots of these errors:
1) ``` [ts] JSX element type 'TextField' does not have any construct or call signatures. ```

2)  ``` [ts] Argument of type 'typeof import(.../@material-ui/core/...' is not assignable to parameter of type 'Component<{}>'. Type 'typeof import(..../@material-ui/core/...' is not assignable to type 'StatelessComponent<{}>'.```

**Comment by mhegazy** [comment] 2018-06-12 22:11
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/24528. Fix should be in `typescript@next` today, and in `typescript@2.9.2` in two days. 

Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.

**Comment by roostapour** [comment] 2018-06-13 23:02
Thanks for the new release 2.9.2. I've upgraded to 2.9.2, but still get the same errors in Visual Studio Code while the code compiles successfully with no errors.

**Closed** 2018-07-02 19:02 UTC
Labels: Duplicate
