### ISSUE TITLE
PLEASE add search field to your documentation 🚨

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/TypeScript#30844] opened 2019-04-10 09:38 UTC
## Search Terms

typescript search documentation

## Suggestion

🚨 PLEASE 🚨 **PLEASE** 🚨 _**PLEASE**_ 🚨
Add a search field in your typescript documentation.

I love TypeScript, really, i evangelized it anytime in my company, i make talks in french conferences to do so too.
But there is one missing feature in the documentation: **a proper search field**.

This is the only missing feature to make more users use this useful langage.

## Use Cases

Save the world

## Examples

Bootstrap documentation does it well :  https://getbootstrap.com/docs/4.1/getting-started/introduction/
![image](https://user-images.githubusercontent.com/5599375/55868149-308f0200-5b84-11e9-9a96-c579d59fa600.png)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by trotyl** [comment] 2019-04-10 10:19
Duplicate of https://github.com/Microsoft/TypeScript/issues/26956

**Closed** 2019-04-10 16:06 UTC
Labels: Duplicate
