### ISSUE TITLE
Add support for nested generics

### ISSUE THREAD

**Issue by janaszer** [microsoft/TypeScript#41600] opened 2020-11-19 18:28 UTC
## Suggestion

Please add support for deeply nested generics.

## Use Cases

This is mostly useful for React development. We can have higer order components that might take generic class and return generic class. However deeply nested generics are inferred as `unknown` type.

Also `connect` from `react-redux` shows the same behaviour.

## Examples

```js
// Imagine I have generic component like this:
class Comp<T> extends React.Component<{ data: T, width: number}> {}
// and this is my generic function - it takes component and returns component (with one property less)
function WithWidth<T extends { width: number }>(component: React.ComponentType<T>): React.ComponentType<Omit<T, 'width'>>{
    ...
}

// here I want to create component based on Comp, but with one property bounded
const CompWithWidth = WithWidth(Comp);
```

In that example `CompWithWidth` has type: 
```js
React.ComponentType<Pick<{
    data: unknown;
    width: number;
}, "data">>
```
so `data` is no longer generic parameter. It is `unknown` from now on.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by andrewbranch** [comment] 2020-11-24 23:47
Duplicate of #30650

**Closed** 2020-11-27 18:00 UTC
Labels: Duplicate
