### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined in 'unescapeLeadingUnderscores' during 'completions'

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#21809] opened 2018-02-09 01:19 UTC
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.1
**VSCode Version** 1.19.3
**command requested**: completions
**hitting sessions**: 571
**proportion of all sessions**: 0.0021316071421905156
**stack**
```
TypeError: Cannot read property 'length' of undefined
    at unescapeLeadingUnderscores (tsserver.js:9406:18)
    at Object.idText (tsserver.js:9410:16)
    at IdentifierObject.get [as text] (tsserver.js:82149:27)
    at tryGetGlobalSymbols (tsserver.js:67563:130)
    at getCompletionData (tsserver.js:67440:22)
    at Object.getCompletionsAtPosition (tsserver.js:66828:34)
    at Object.getCompletionsAtPosition (tsserver.js:82839:35)
    at IOSession.Session.getCompletions (tsserver.js:89878:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:88979:61)
    at unknown (tsserver.js:90355:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90346:28)
    at IOSession.Session.executeCommand (tsserver.js:90355:33)
    at IOSession.Session.onMessage (tsserver.js:90375:35)
    at Interface.<anonymous> (tsserver.js:91576:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by andy-ms** [comment] 2018-02-09 18:19
Duplicate of #20792

**Closed by andy-ms** 2018-02-09 18:19 UTC
Labels: Bug, Source: Telemetry

**Comment by aozgaa** [comment] 2018-03-05 05:00
This issue reproduced in the following context:
**TypeScript Version Prefix**: 2.7.2
**VSCode Version** 1.21.0-insider
**command requested**: completions
**hitting sessions**: 162
**proportion of all sessions**: 0.0033258740684473094
**stack**
```
TypeError: Cannot read property 'length' of undefined
    at unescapeLeadingUnderscores (tsserver.js:9434:18)
    at Object.idText (tsserver.js:9438:16)
    at IdentifierObject.get [as text] (tsserver.js:82347:27)
    at tryGetGlobalSymbols (tsserver.js:67756:130)
    at getCompletionData (tsserver.js:67633:22)
    at Object.getCompletionsAtPosition (tsserver.js:67005:34)
    at Object.getCompletionsAtPosition (tsserver.js:83037:35)
    at IOSession.Session.getCompletions (tsserver.js:90076:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89177:61)
    at unknown (tsserver.js:90553:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90544:28)
    at IOSession.Session.executeCommand (tsserver.js:90553:33)
    at IOSession.Session.onMessage (tsserver.js:90573:35)
    at Interface.<anonymous> (tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```
