### ISSUE TITLE
Checking truthy falsy doesn't cover all code paths

### ISSUE THREAD

**Issue by danyonedwards** [microsoft/TypeScript#43776] opened 2021-04-22 08:00 UTC
# Bug Report

### 🔎 Search Terms

* Truthy Falsy code paths not returning
* Not all code paths return a value.(7030) double if

### 🕗 Version & Regression Information

- This is the behaviour in every version I tried, and I reviewed the FAQ for entries about Not all code paths return a value.(7030)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/MYewdgzgLgBAZgVzMGBeGAKAlGgfDAbwCgZSZRJYBDNGKAJwQFMBuEsgSzgyp3qagJ6YOo1btSXDAEJeMfoOHwqAGwjiAvkA)

### 💻 Code

```ts
const func = () => {
    const a = true;
    if(a) return true;
    if(!a) return false;
}
```

### 🙁 Actual behaviour

I tried to cover all the code paths (that I thought) and getting `Not all code paths return a value.(7030)`

### 🙂 Expected behaviour

I expect the above snippet to cover all code paths.

**Comment by nmain** [comment] 2021-04-22 11:59
Seems to be a duplicate of https://github.com/microsoft/TypeScript/issues/39386; the code sample linked from that issue gives TS7030 in `hel12`.
Search terms:  never return unreachable

**Comment by RyanCavanaugh** [comment] 2021-04-22 16:05
This would require some substantial work to detect correctly and would ultimately be a bit of an anti-feature -- if it's truly the case that this function never hits the closing brace, then this is a bizarre way to write your code, so it's more likely that someone writing their code this way has some side effects on `a` we're unaware of and we'd be getting in their way.

**Closed** 2024-02-24 00:21 UTC
Labels: Design Limitation
