### ISSUE TITLE
Build caching not working in CI workflows

### ISSUE THREAD

**Issue by alex-statsig** [microsoft/TypeScript#59152] opened 2024-07-05 20:49 UTC
### 🔎 Search Terms

typescript build github actions caching

### 🕗 Version & Regression Information

- This appears to be consistent across all versions

### 💻 Code

n/a

### 🙁 Actual behavior

In CI, when caching the build directory including the "dist/tsconfig.build.tsbuildinfo" file, a repeated execution of identical build takes the same time 

### 🙂 Expected behavior

Similar to using build cache locally, the build should be instant if no files have been modified.

### Additional information about the issue

My suspicion is the build cache relies on modified times of files, and thus is fully invalidated if reused in CI where the repo is checked out fresh every time. Inspecting the tsconfig.build.tsbuildinfo file, I noticed "version" and "signature" on files, as well as "latestChangedDtsFile". I couldn't determine if it was caching on file hashes or modified times fully from this.

I'm not sure if this is expected behavior or not due to the way the caching is done. If its unexpected, I can provide more diagnostics, but I'm assuming it might be expected based on the caching approach. If so, adding an option to cache by file hashes rather than modified times would be valuable for CI caching.

**Comment by MartinJohns** [comment] 2024-07-05 21:02
Sounds like a duplicate of #54563.

**Comment by alex-statsig** [comment] 2024-07-06 05:33
I think my issue is a bit more generic, and focused on the problem rather than one specific solution. I don't necessarily need a mechanism to determine externally if the project needs rebuild. However, I would like any work already completed by typescript for 99% (or even 100%) of a project to carryover despite timestamps of files changing. I'm imagining something like the [cache strategy](https://eslint.org/docs/latest/use/command-line-interface#--cache-strategy) flag in eslint, which enables CI caching by using file content rather than modified timestamps for better CI support.

That being said, happy to consolidate the discussion on the other issue still, although it seems a bit stale

**Closed** 2024-07-09 01:31 UTC
Labels: Duplicate

**Comment by iMouth** [comment] 2025-05-21 08:27
@andrewbranch please reopen this issue it was not a duplicate.
