### ISSUE TITLE
fluent api style method chain formatting problem - 2

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#5831] opened 2015-11-30 16:45 UTC
Seen in 1.8 nightly build (1.8.0-dev.20151130)

```
// given:
new Start().then(
      true,
      false
   ).then(
      1234,
      'xyz'
   ).then(
      'abc',
      '987'
   );
```

```
// actual:
new Start().then(
   true,
   false
).then(
   1234,
   'xyz'
   ).then(
   'abc',
   '987'
   );
```

```
// expected:
new Start().then(
   true,
   false
).then(
   1234,
   'xyz'
).then(
   'abc',
   '987'
);
```

**Comment by mhegazy** [comment] 2015-12-01 19:23
this looks like a dupe of #5830. the base indentation was different in both cases, but the rest of the issue is the same.

**Closed by mhegazy** 2015-12-01 19:23 UTC
