### ISSUE TITLE
`undefined` not inferred when destructuring an empty typed array

### ISSUE THREAD

**Issue by iagoqo** [microsoft/TypeScript#38287] opened 2020-05-01 14:55 UTC
**TypeScript Version:**  3.8.3

**Search Terms:**

array destructuring, destructuring, empty array, undefined

**Expected behavior:**
When destructuring an empty typed array to get a single item the resulting values should include `undefined` as a possible type.

`Array.prototype.shift()` includes `undefined` as a possible return type, the behaviour should be similar when destructuring.

**Actual behavior:**
The destructured values are inferred to only be of the same type as the array.

**Related Issues:**
No

**Code**
```ts
const myArray: string[] = [];

// type: string, should be string | undefined
const [firstItem] = myArray;

//type: string, should be string | undefined
const myItem = myArray[10];
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const myArray = [];
// type: string, should be string | undefined
const [firstItem] = myArray;
//type: string, should be string | undefined
const myItem = myArray[10];

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/#)

**Comment by MartinJohns** [comment] 2020-05-01 19:24
Duplicate of #36635 / #13778.

**Comment by Skillz4Killz** [comment] 2020-05-07 12:13
I am not sure if this should be marked as a duplicate to #13778. I think this issue needs to be separated. Right now Array Destructuring is providing inaccurate types. That issue has gotten away from that topic entirely to create a complex decision on how to handle types inside loop functions. https://github.com/microsoft/TypeScript/issues/36635#issuecomment-594315037

**Comment by RyanCavanaugh** [comment] 2020-05-08 21:24
There's no way we would change this behavior without #13778 or vice versa, so it's a duplicate

**Closed** 2020-05-11 18:00 UTC
Labels: Duplicate

**Comment by trev-dev** [comment] 2021-08-25 00:05
Please re-open this. It's not resolved :) Here's an [example of the problem](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoAtQHMCeyDeAUMicggPYCu4AXMiJQLYBG0hAvoYTNQmMORDIsEMBmzAIAZwDiUCHEhQMcEAAo4UKHXEhcAbQC6AGmSNQdBi2gBKHZj04jBYqXlhKUIZqgA6GMAANkpqYA5YyAC8AHzIYdi+FNRgyLHmIDYA3BxcFCBSKfF6klL22E6GUcj6riREpA1kVLTIAMwADLXI7MZd9Y0kSS0ATJ0NPX1dDUNgdACsY6QTDf0DM3TDXZyG2YR5BdUBUAW6WJWRwqKnJXIKSirqRVglpgDs7VlcAPQAVMhHJ3CTUogQAJshWMhqKCIAEQBBQaZmJQUqgcAAHCAAZQQUGA6JSMHIUGQAHd0IoIAA3aDIeRwKSCZCg8jSEAAchSCE0EF8yGIfwA6igeXF0JQpIE8HBAoFyKSEXFyGY4ABrFBhFBE2Xy7DIKRBKVmYAFNUQAVfPaCRmBXlyrBqAFicKJZpgT4kIA) in version 4.3.5.

I basically have to think _for_ typescript when destructing arrays of objects that might be empty, which TypeScript basically taught me to look out for, but it would be nice if it did as it usually does.

**Comment by andrewbranch** [comment] 2021-08-25 00:16
It is resolved; you have to use `--noUncheckedIndexedAccess`. [[Playground]](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true#code/PTAEAEDsHsFVIMYAsCmCDWKAmBJSWUAPbAQQQRQGdKAuUAFwCcBXFAKDYEtJ6VGAzAIYVQAFSTcA5gE9QAbzagloBNGY86kZgFsARnzYBfDv3UJ6naJFCSU9cVM5UA4oxSDejcYMgAKQYyMdA6QMgDaALoANKDa3Jo6+owAlMESodKR8orKbvTMjNYBjAB0-JwANp6+9OmSoAC8AHwMdSWq6vSgLXGQyQDcRhyqkJRdtY5UaVKZEY2gYTlKCsqrKmoaoADMAAxLoIZR+ytrSh2bAEx7q4fH+6vn9HQArNfKt6snp490F-vGEUGbBGYwW5UYYxCkjmDRsdihTkorncnm8fgmoURMQA7DsBhxgAAqUDgyF1dbMCpYUD6UDqAjlSDYGK6ZhdUTSAAOKAAyghGJxOV1+NBGKAAO5IDwoABufFAbkElCsoCw0CokAA5F0EAEUCVQIpiQB1FCgPWtZiUCqyQQVCrQcXYBjQWKCTCtM0i+2OqSgSiVG2xThjd3sUCE4DAqzKir6h2SXyk+xtR74oA)

**Comment by trev-dev** [comment] 2021-08-25 03:26
Alright, thanks. I guess I had expected this check to be opt out, not opt in.

**Comment by maapteh** [comment] 2021-12-27 14:40
Same, but now i read the reason https://github.com/microsoft/TypeScript/issues/42016#issue-770320240 which makes sense. Also with this flag on it gives so many side effects on things my editor has no problem with inferring it correctly. I just saw the problem with empty arrays :(
