### ISSUE TITLE
Error: No Project. in 'Object.ThrowNoProject' during 'getApplicableRefactors'

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#21787] opened 2018-02-09 01:19 UTC
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.1
**VSCode Version** 1.20.0-insider
**command requested**: getApplicableRefactors
**hitting sessions**: 5458
**proportion of all sessions**: 0.020375327113968188
**stack**
```
Error: No Project.
    at Object.ThrowNoProject (tsserver.js:84179:23)
    at ScriptInfo.getDefaultProject (tsserver.js:84787:46)
    at ProjectService.getDefaultProjectForFile (tsserver.js:87359:39)
    at IOSession.Session.getFileAndProjectWorker (tsserver.js:89734:87)
    at IOSession.Session.getFileAndProject (tsserver.js:89719:29)
    at IOSession.Session.getApplicableRefactors (tsserver.js:90153:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89112:61)
    at unknown (tsserver.js:90355:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90346:28)
    at IOSession.Session.executeCommand (tsserver.js:90355:33)
    at IOSession.Session.onMessage (tsserver.js:90375:35)
    at Interface.<anonymous> (tsserver.js:91576:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mhegazy** [comment] 2018-02-09 18:07
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/20629

**Closed by mhegazy** 2018-02-09 18:07 UTC
Labels: Bug, Source: Telemetry

**Comment by aozgaa** [comment] 2018-03-14 20:17
This issue reproduced in the following context:
**TypeScript Version Prefix**: 2.7.2
**VSCode Version** 1.21.0-insider
**command requested**: quickinfo
**hitting sessions**: 263
**proportion of all sessions**: 0.022322186386012563
**five line hash**: 44e191d9efc2b3f705bd1bd1b98507b4
**stack**
```
Error: No Project.
    at Object.ThrowNoProject (tsserver.js:84377:23)
    at ScriptInfo.getDefaultProject (tsserver.js:84985:46)
    at ProjectService.getDefaultProjectForFile (tsserver.js:87557:39)
    at IOSession.Session.getFileAndProjectWorker (tsserver.js:89932:87)
    at IOSession.Session.getFileAndProject (tsserver.js:89917:29)
    at IOSession.Session.getQuickInfoWorker (tsserver.js:89977:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89132:61)
    at unknown (tsserver.js:90553:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90544:28)
    at IOSession.Session.executeCommand (tsserver.js:90553:33)
    at IOSession.Session.onMessage (tsserver.js:90573:35)
    at Interface.<anonymous> (tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```
