### ISSUE TITLE
interface partial specializations

### ISSUE THREAD

**Issue by xujif** [Microsoft/TypeScript#24400] opened 2018-05-25 04:59 UTC
Is there any way to specialize an generic interface.

## Examples
 ```typescript
interface Gen<T> {
    method1 (): void
}
// not use '='? it is a break change
interface Gen<T = number> {
    method2 (): void
}

let v1 = {} as Gen<string>
v1.method1() // correct ,  Gen<string> has method1
v1.method2() // error,  Gen<string> does not has method2

let v2 = {} as Gen<number>
v1.method2() // correct ,  Gen<string> has method2
```

**Comment by mhegazy** [comment] 2018-05-25 15:31
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/17636

**Closed** 2018-06-08 15:57 UTC
Labels: Duplicate
