### ISSUE TITLE
feature request: readonly only outside and writable inside

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#41643] opened 2020-11-23 06:52 UTC
## Suggestion

Sometime we need a value readonly from outside, but writable of cause inside. Usually we do it by double properties, but that's superfluous and waste of performance.

## Use Cases

```ts
export default class Foo {

    private _value1;
    protected get value1 () { return this._value1; }

    private _value2;
    public get value2 () { return this._value2; }

    protected _value3;
    public get value3 () { return this._value3; }

};
```

We do all things above to make sure the value could only write from inside, otherwise, there will be a TS warn. If we want to save performance (ignore the superfluous problem being worse):

```ts
declare class _Foo {
    protected readonly value1;
    readonly value2;
    readonly value3;
}
const Foo = class {
    value1;
    value2;
    value3;
} as typeof _Foo;
type Foo = _Foo;
export { Foo as default };
```

## Examples

One solution (everyone can suggest a better one of cause, I mainly point out the need):

```ts
export default class Foo {
    protected private value1;
    public private value2;
    public protected value3;
};
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-11-23 08:42
Duplicate of #37487.

**Closed** 2020-11-23 17:11 UTC
