### ISSUE TITLE
Treat `Boolean(x)` equally as double not `!!x`

### ISSUE THREAD

**Issue by maxkomarychev** [microsoft/TypeScript#37180] opened 2020-03-03 06:14 UTC
In complex boolean expressions it's clearer to do `Boolean(x)` cast rather than `!!x` in favor of readability. Also the latter way of casting something to boolean is error prone and it's easy to mistype `!`. Typescript should treat `Boolean(x)` the same way as `!!`.

**TypeScript Version:**  3.6.3,3.7.5,3.8.3 (tried top 3 available in playground)

**Search Terms:**

boolean cast non null 
double negation boolean cast
double not Boolean 

**Code**

```ts
interface A {
    a: number
}

const a: A | undefined

console.log(a && a?.a) // works
console.log(!!a && a.a) // works
console.log(Boolean(a) && a.a) // warns that `Object is possibly 'undefined'.(2532)`
```

**Expected behavior:**
`Boolean(x)` should be treated as equivalent of `!!x`

**Actual behavior:**
Using `Boolean` as a function does not contribute to TS understanding of object existense

**Playground Link:** https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=9&pc=31#code/JYOwLgpgTgZghgYwgAgILIN4Chm+XALmRAFcBbAI2iwF8ssEB7EAZzHyPQB9kSQATCDFAR+9Jq0YAbCADopjAOYAKOMgBk6-AH5ZcAJQNmLaXIUqAhBbWb8ewxJMz5S5QCFGpuCFX6NWuHsgA

**Related Issues:**

**Comment by Ezio1212** [comment] 2020-03-03 19:25
i think your issue may couldnot be sensed by when the parameter of Boolean is another function's parameter, like this:

`function(a?: A) {
    return Boolean(a) && a.a; // the compiler cannot helps you to understanding this case
}`

**Comment by maxkomarychev** [comment] 2020-03-04 08:35
@Ezio1212 I am not sure I follow your suggestion, can you elaborate?


```
interface A {
    a: number
}

function xxx(a?: A) {
    return a && a?.a
}

function yyy(a?: A) {
    return !!a && a.a
}

function zzz(a?: A) {
    return Boolean(a) && a.a;
}
```

expressions work exactly the same way in context of a function as they work outside - `x && x.prop` and `!!x && x.prop` work perfectly fine while `Boolean` one does not.

playground: https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=16&pc=1#code/JYOwLgpgTgZghgYwgAgILIN4Chm+XALmRAFcBbAI2iwF8ssYSQExgB7EZADx4Ao4A-EVQBKTDjxQIYElE5xkAMkX4BAOji16jZqw7IAnkf5C0Y7HmRSZc5AEI7C5fg1aGTFu04AvXyeHmErjWspwAQmxsADYQcCD8Ys5wGgDcWkA

**Comment by nmain** [comment] 2020-03-04 15:31
Duplicate of https://github.com/microsoft/TypeScript/issues/16655
My search terms were "boolean constructor type guard"
If you add the overload from https://github.com/microsoft/TypeScript/pull/29955 to your example, it works as expected:

[Playground](https://www.typescriptlang.org/play/?ssl=12&ssc=33&pln=12&pc=5#code/JYOwLgpgTgZghgYwgAgILIN4Chm+XALmRAFcBbAI2iwF8ssATCBAGzihQQHsQBnMfEXQAfZCRBMYoCA3rc+XFhAB0LLgHMAFHGQAyXfgD8yuAEos83opVqtAQjs79+E+cvXVGzQCEu1uCDapnoGcK70oJCwiCi+-iAAwjz8UCQIYFxQmDh4ADwAKgB8mgBucCwkEIZE+aZEZRUowLzIAKIAHqwkTAUANMjwLLwooqQsLMii4pLSDJPIAOQL8wAMhQDctFhAA)

**Closed** 2020-03-06 18:00 UTC
Labels: Duplicate
