### ISSUE TITLE
Output directory messed up if tsc is triggered as VS Code task.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#8837] opened 2016-05-26 07:36 UTC
This only happens if tsc is executed via Code.

**TypeScript Version:** 

nightly (1.9.0-dev.20160525-1.0)

**Code**

**.vscode/tasks.json**

```js
{
    "version": "0.1.0",
    "command": "node", // Using npm scripts would result the same.
    "isShellCommand": true,
    "args": ["node_modules/typescript/lib/tsc.js"],
    "showOutput": "silent",
    "problemMatcher": "$tsc"
}
```

**tsconfig.json**

```ts
{
    "compilerOptions": {
        "module": "commonjs",
        "allowJs": true,
        "outDir": "bld",
        "rootDir": "src"
    },
    "exclude": [
        "node_modules",
        "bld"
    ]
}
```

**src/foo/bar.ts**

```ts
import '../biu/pia';
```

**src/biu/pia.js**

```js
// Empty file.
```

**Expected behavior:**

Compiles correctly.

**Actual behavior:** 

```txt
error TS5055: Cannot write file '.../src/biu/pia.js' because it would overwrite input file.
```

And if you put another .ts file and import it in `src/foo.bar.ts`, it would be output as .js file nested to its .ts source.

**Comment by Seikho** [comment] 2016-05-27 00:50
Possibly related to Microsoft/Vscode#6719 ?

**Comment by mhegazy** [comment] 2016-06-07 19:54
@zhengbli any thoughts?

**Comment by zhengbli** [comment] 2016-06-08 22:30
Seems to be a VSCode task runner issue, the same as  Microsoft/vscode#6719. Running tsc from command line doesn't repro the error.

**Comment by Seikho** [comment] 2016-06-09 03:20
The regression occurs in the cd1af127 commit.

**Comment by Seikho** [comment] 2016-06-09 04:27
[This](https://github.com/Microsoft/TypeScript/pull/8486/files#diff-08a3cc4f1f9a51dbb468c2810f5229d3R590)  [(L590, program.ts)](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/program.ts#L590) seems to be the offending change. It changes the capitalisation of the Windows drive letter (lower to upper in the case of Microsoft/vscode#6719).

When run from the command line, the drive letter is already capitalised and stays capitalised.

**Comment by yortus** [comment] 2016-06-09 05:14
[Evidence](https://github.com/Microsoft/vscode/issues/6719#issuecomment-224800465) that @Seikho has identified the problem.

**Comment by Seikho** [comment] 2016-06-09 05:17
After further digging, it's a change from Node v5 to Node v6 in the behaviour of `fs.realpath` which is used in [L547 sys.ts](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/sys.ts#L547).

In node v5:
```
$ node
> process.version
'v5.11.1'
> require('fs').realpathSync('c:\\projects')
'c:\\projects'
>                                     
```

In node v6:
```
$ node
> process.version
'v6.2.0'
> require('fs').realpathSync('c:\\projects')
'C:\\projects'
>
```

**Comment by yortus** [comment] 2016-06-09 08:21
@zhengbli could the 'external' tag be removed, and this be dealt with in TypeScript? See https://github.com/Microsoft/vscode/issues/6719#issuecomment-224828922

**Comment by dbaeumer** [comment] 2016-06-09 08:25
Important observations from https://github.com/Microsoft/vscode/issues/6719:

- make sure the symlink code works with drive letters created with subst as well. I have such a setup where I mapped C:\users\dirkb\projects => P:\ and this seems to fail with the latest build TS with wired error messages. See comment: https://github.com/Microsoft/vscode/issues/6719#issuecomment-224296908

- there seems to be issue with drive letter in node 6.x: See nodejs/node#6624

**Comment by zhengbli** [comment] 2016-06-10 09:38
@Seikho Thanks for the finding! The issue should be able to address from TypeScript side.

**Comment by dbaeumer** [comment] 2016-06-13 07:53
@zhengbli shouldn't this be addressed in 2.0. It works in 1.8.x and is broken in @next. I am asking since it is tagged for 2.1

**Comment by yortus** [comment] 2016-06-13 07:57
Fixing in @next would be great - We've had to disable the VSCode build task for all our affected projects since this surfaced, which is a minor hassle but still a hassle.

**Closed** 2016-06-20 21:07 UTC
Labels: Bug
