### ISSUE TITLE
TS2488: Type 'Readonly<Iterable<T>>' must have a '[Symbol.iterator]()' method that returns an iterator.

### ISSUE THREAD

**Issue by electricessence** [microsoft/TypeScript#38649] opened 2020-05-18 22:07 UTC
**TypeScript Version:**  3.9.2
Reproduced in 4.0.0

**Search Terms:**
readonly iterable method that returns iterator

**Code**

```ts
function i (): Readonly<Iterable<string>>
{
	return Object.freeze({
		* [Symbol.iterator] ()
		{
			yield 'a';
		}
	});
}

for(const e of i()) // TS2488 here
{
	console.log(e);
}
```

**Expected behavior:**
Should not error on the `for-of` loop.  Actually works at runtime.

**Actual behavior:**
`TS2488: Type 'Readonly<Iterable<string>>' must have a [Symbol.iterator]()' method that returns an iterator.`

**Comment by electricessence** [comment] 2020-05-18 22:08
Having an immutable `Iterable<T>` is useful.  This should not be an error and magic type coercion for every `Readonly<Iterable<T>>` shouldn't be necessary.

**Comment by IllusionMH** [comment] 2020-05-19 11:05
Looks like duplicate of #37182

**Closed** 2020-06-11 18:00 UTC
Labels: Duplicate
