### ISSUE TITLE
feat: inference of object properties based on a "type" infer out

### ISSUE THREAD

**Issue by alexgwolff** [microsoft/TypeScript#53883] opened 2023-04-18 00:59 UTC
# Suggestion

## 🔍 Search Terms

out parameters, infer out, auto casting

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Currently, TypeScript does not support inference of object properties based on a "type" property that can contain a component type. This can be useful in cases where you want to infer the properties of a component based on its "type" property, regardless of whether it is a React component or another type of component.

## 📃 Motivating Example
```typescript
type Metadata<out T extends React.ComponentType<any>> = {
  type: T;
  props: T extends React.ComponentType<infer Props> ? Props : never;
};

const metadata: Metadata = {
  type: Checkbox,
  props: {
    name: 'checkbox',
    label: 'checkbox',
    value: 'true',
  },
};

```

## 💻 Use Cases

- Better auto complete
- infer types based props

**Comment by fatcerberus** [comment] 2023-04-18 06:02
This feels very similar to/possibly a duplicate of #47755

**Comment by RyanCavanaugh** [comment] 2023-04-18 16:16
The example section here is not well-formed. What is `out` doing there? What is someone who doesn't do React supposed to take away from this? What happens if the React types change and your sample doesn't work? What's the simplest version of this that anyone can understand?

**Closed** 2023-05-26 04:07 UTC
Labels: Needs More Info
