### ISSUE TITLE
source.organizeImports must not remove empty line between import

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24324] opened 2018-05-22 17:46 UTC
_From @nikolay-borzov on May 22, 2018 12:37_

Usually imports are organized in groups separated by empty line (e.g. node packages, services, components). I think that `organizeImports` should respect existing groups and perform organizing within each group.

- VSCode Version: 1.23.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Set user settings:
```
"editor.formatOnSave": true,
"editor.codeActionsOnSave": {
  source.organizeImports": true
}
```
2. Create `.ts` file
```
import path from 'path'

import fs from 'fs'

const currentDir = path.resolve(__dirname)
const data = fs.readdirSync(currentDir)
```

3. Press `Ctrl+S`

4. Result:
```
import fs from 'fs'
import path from 'path'

const currentDir = path.resolve(__dirname)
const data = fs.readdirSync(currentDir)
```

Does this issue occur when all extensions are disabled?: Yes (Disabled TSLint and Prettier)

_Copied from original issue: Microsoft/vscode#50277_

**Comment by mhegazy** [comment] 2018-05-22 18:36
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/22914

**Comment by mjbvz** [comment] 2018-05-22 18:40
I believe #22914 tracks removing the newlines while this issue is about preserving the newlines and the import groups they define

**Comment by mjbvz** [comment] 2018-05-22 23:48
Agreed. Given the work required, unless there are many users requesting this, this kind of more advanced sorting seems like a better fit for an extension

**Closed** 2018-06-06 17:22 UTC
Labels: Design Limitation

**Comment by taoqf** [comment] 2019-02-19 07:01
I have to disable `source.organizeImports` for the same reason.

**Comment by indapublic** [comment] 2021-05-04 07:26
No solution?

**Comment by dobeerman** [comment] 2024-05-31 13:08
We'd like to keep some packages on top of all imports and keep the rest are organised. For instance, "source-map-support/register", datadog tracer, etc must be stick to the top. But it is not possible with `source.organizeImports` enabled.

The issue is 6 year old, so I'm quite surprised there is no solution so far :disappointed: 

Am i missed something? :thinking:
