### ISSUE TITLE
Assignation of incorrect value doesn't type error

### ISSUE THREAD

**Issue by phpcoder2022** [microsoft/TypeScript#58681] opened 2024-05-28 18:59 UTC
### 🔎 Search Terms

incorrect type, incorrect value

### 🕗 Version & Regression Information

TypeScript version: 5.4.5

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAwiArmKBTATgZQJ4FsBGIANjALww4HEAUA5AsmlnoUbQJQDcAUFNgA6p4SFBjIwADDAA+MMIgJiAZDADeMANoNRzKkQC6ALhhR0iIQF8e3APQ2YAFQAWASwgxcAQ3meSniBAYUC7gMG4woOjoqMBQAHQUqJBCIABmJq7ufIJh7i64-CABLvguRC58MGkebsARTt4A5qgQcdygkLAuKACSYHXk1KCMGMbaTOxjIkxkAHwwQ9NiANQwAIzsMP7CI+jWRKiwwzpTu+IS1scz5ADMPFdi5A-oMAC06xIXMHYeiNAw+CEGHQIBe+EQsDAIAANBk-mEoLQsk4hAdPABrMJgEwCFwAL08wXA7SWL1e5DWn0433suD+sEBMGBoIBELkMLheURyNRqAxWJx-HxhJCYG47SI-ncAEE1NwYDB+CC0LFUAATCKk046c7WBX8RD4cp1brAaiTGAANxALg1qnlCoybjiz3ErvelIuDoVUEyLtJbwpVJpv3+jOZYLZUNhvvhFSRGV5-O6guFRLFCos3AsQA

### 💻 Code

```ts
const CounterSymbol = Symbol('CounterSymbol');
type Counter = 0 | number & { [CounterSymbol]: true };

// This manual assertion is correct. Sense of this type is impossibility of misc changes.
const intInc = (counter: Counter): Counter => (counter + 1) as Counter;

let counter: Counter = 0;

counter = 3;
counter = counter - 100; // must be error but no, thus it's the leak in typization
counter -= 100; // must be error but no, thus it's the leak in typization

class A {
  protected counter: Counter = 0;

  public inc(): void {
    this.counter = counter - 100;
    this.counter -= 100; // must be error but no, thus it's the leak in typization
  }
}
```

### 🙁 Actual behavior

Assignation was allow

### 🙂 Expected behavior

Assignation was deny

**Comment by jcalz** [comment] 2024-05-28 19:55
Duplicate of #47027

**Closed** 2024-06-09 01:31 UTC
Labels: Duplicate
