### ISSUE TITLE
Array.filter callback parameter should not be required to return a boolean

### ISSUE THREAD

**Issue by mjohnsonengr** [Microsoft/TypeScript#7850] opened 2016-04-06 14:54 UTC
The TypeScript definition for Array.filter specifies the callback must return a boolean, thus the code example at the bottom of this post fails to compile.  Here's the current definition:

    filter(callbackfn: (value: T, index: number, array: T[]) => boolean, thisArg?: any): T[];

[The spec](https://tc39.github.io/ecma262/#sec-array.prototype.filter) says this about the callback parameter:

> callbackfn should be a function that accepts three arguments and returns a value that is coercible to the Boolean value true or false.

Thus I propose the definition should be changed to:

    filter(callbackfn: (value: T, index: number, array: T[]) => any, thisArg?: any): T[];

_Note: using a double not-operator is a sufficient workaround with negligible implications_

**TypeScript Version:** 
1.8.7

**Code**
[Playground](https://www.typescriptlang.org/play/#src=let%20a%20%3D%20%5B1%2C%202%2C%203%2C%20undefined%2C%200%2C%2042%2C%20%22%22%5D.filter(i%20%3D%3E%20i)%0D%0A%0D%0Aconsole.info(a))
```ts
// the purpose is to weed out falsey values
let a = [1, 2, 3, undefined, 0, 42, ""].filter(i => i)
// "i => i" is an error because it does not return boolean
// the following has no error
let b = [1, 2, 3, undefined, 0, 42, ""].filter(i => !!i)
```

**Expected behavior:**
No compile errors

**Actual behavior:** 
Compile errors

**Comment by RyanCavanaugh** [comment] 2016-04-06 16:08
This appears to be a duplicate of issue #5850

To reduce noise in issue searches, we close issues that are already tracked somewhere else. If you think the linked issue is not actually the same, please leave a comment here (we do read comments on closed issues). Otherwise you can follow or chime in on the linked issue. Thanks!

**Closed by RyanCavanaugh** 2016-04-06 16:08 UTC
Labels: Duplicate
