### ISSUE TITLE
Microsoft.TypeScript.targets  shipped with 1.4 doesn't mention TypeScriptNoEmitOnError or --noEmitOnError

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#2848] opened 2015-04-21 14:47 UTC
So basically no emitting on errors is not configurable (as of 1.4 for VS).

**Comment by mhegazy** [comment] 2015-04-21 16:45
I am not sure i understand the question. 

NoEmitOnError is set to true by default to ensure that incremental build works correctly in MSBuild. To change this behavior, there is no UI for it at the moment in the project property pages. but you can change it by defining the property in your project file as:
```XML
 <PropertyGroup>
    <TypeScriptNoEmitOnError>false</TypeScriptNoEmitOnError>
  </PropertyGroup>

 <!-- before the import statement -->
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets')" />
```

For more information checkout [Setting Compiler Options in MSBuild projects](https://github.com/Microsoft/TypeScript/wiki/Setting-Compiler-Options-in-MSBuild-projects) wiki page.

**Comment by mhegazy** [comment] 2015-04-21 16:45
looks like a dupe of #1915

**Comment by aleksey-bykov** [comment] 2015-04-21 16:51
>I am not sure i understand the question.

setting TypeScriptNoEmitOnError to `true` or `false` doesn't change anything because (as of 1.4 for VS) this property is ignored in `Microsoft.TypeScript.targets` and never gets transformed to the `--noEmitOnError` flag or lack of thereof

is this by design?

**Comment by mhegazy** [comment] 2015-04-21 17:30
>setting TypeScriptNoEmitOnError to true or false doesn't change anything because (as of 1.4 for VS) this property is ignored in Microsoft.TypeScript.targets and never gets transformed to the --noEmitOnError flag or lack of thereof

Why do you say it is ignored? may be we are looking at different target files.. I am looking at %ProgramFiles (x86)%\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets that shipped with TypeScript 1.4; and i see the following:

```XML
  <!-- noEmitOnError default is 'true', this ensures a proper incremental build behavior, where outputs are not generated in the presence of an error. -->
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptNoEmitOnError)' != 'false'">$(TypeScriptBuildConfigurations) --noEmitOnError</TypeScriptBuildConfigurations>
````

In my test project, just before the import to the targets file, i have added:
```XML
    <PropertyGroup>
        <TypeScriptNoEmitOnError>false</TypeScriptNoEmitOnError>
    </PropertyGroup>
```

and when i build i see outputs generated correctly. so what am i missing?

**Comment by aleksey-bykov** [comment] 2015-04-21 17:33
> %ProgramFiles (x86)%\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets

I am looking at

"C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\TypeScript\Microsoft.TypeScript.targets"

**Comment by aleksey-bykov** [comment] 2015-04-21 17:43
I guess it doesn't matter anymore, since it is fixed in the latest version. If so, I think we can close this one.

**Closed** 2015-04-21 17:43 UTC
Labels: Duplicate, Needs More Info
