### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined 

### ISSUE THREAD

**Issue by azaroth001** [Microsoft/TypeScript#15865] opened 2017-05-15 22:59 UTC
[tsc-TypeError.zip](https://github.com/Microsoft/TypeScript/files/1002715/tsc-TypeError.zip)
**TypeScript Version:**  2.3.2

**Description**

Following JavaScript code will cause TypeError when allowJs and checkJs compiler options are turned on.

**Code**
```js
const A = require('A');

class B extends A {
    constructor() {
      super();
      this.y = 5; // If B extends A, this line causes TypeError.
  }
}
```
tsconfig.json:
```ts
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "allowJs": true,
    "checkJs": true,
    "strict": true
  }
}
```
**Expected behavior:**
```
test.js(3,11): error TS2304: Cannot find name 'require'.
test.js(3,19): error TS2307: Cannot find module 'A'.
...
```
**Actual behavior:**
```
TypeError: Cannot read property 'kind' of undefined
    at checkIndexConstraintForProperty (C:\Users\<MyUserName>\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:36176:61)
    at C:\Users\<MyUserName>\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:36141:21
    at Object.forEach (C:\Users\<MyUserName>\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:288:30)
    at checkIndexConstraints (C:\Users\<MyUserName>\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:36139:20)
    at checkClassLikeDeclaration (C:\Users\<MyUserName>\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:36374:17)
    at checkClassDeclaration (C:\Users\<MyUserName>\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:36292:13)
    at checkSourceElement (C:\Users\<MyUserName>\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:37227:28)
    at Object.forEach (C:\Users\<MyUserName>\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:288:30)
    at checkSourceFileWorker (C:\Users\<MyUserName>\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:37296:20)
    at checkSourceFile (C:\Users\<MyUserName>\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:37281:13)
```

**Comment by mhegazy** [comment] 2017-05-15 23:56
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/15525. can you give `typescript@next` a try.

**Comment by azaroth001** [comment] 2017-05-16 07:59
Tested ```typescript@next``` and it works. Also tested on my original (gigantic legacy mess) codebase and it works too.

Thanks!

**Comment by mhegazy** [comment] 2017-05-16 17:11
thanks for confirming. closing.

**Closed by mhegazy** 2017-05-16 17:11 UTC
Labels: Duplicate
