### ISSUE TITLE
Visual studio 2015 high CPU and memory usage

### ISSUE THREAD

**Issue by slaviki** [Microsoft/TypeScript#7208] opened 2016-02-24 06:11 UTC
Hello.

I'm working on a project on Angular2 with Typescript. Now I have around 80 typescript files. The problem is when I editing files CPU usage goes to 25% and memory usage starts to grow. CPU usage stays on this level almost permanently during coding and memory usage is growing up to 3GB until it crashes with OutOfMemoryException. It can happen after every 10-20 minutes. 

It started when I was using Typescript 1.7. Upgrade to 1.8 didn't solved this problem. I'm not using any extension like ReSharper.

Is there a way to fix it?

**Comment by mhegazy** [comment] 2016-02-24 06:13
can you share a sample project where we can diagnose the issue?

**Comment by slaviki** [comment] 2016-02-24 06:17
I'm afraid I can't share my code. I can provide any other information you need to fix this problem.

**Comment by mhegazy** [comment] 2016-02-24 06:51
We would be willing to sign an NDA to get access to your project. if that is not possible, can you share a sample project that exhibits similar behavior?

**Comment by slaviki** [comment] 2016-02-24 07:06
Ok, how can I send my project directly to you?

**Comment by koenswaanen** [comment] 2016-02-24 12:25
I'm having the same problem. VS starts out around 1GB of memory usage.
As soon as I start typing in a .ts file my memory usage skyrockets to around 2.5GB and after that VS will just stop working.
I'm also working on a Angular2 project, and the problem started this morning after upgrading to Angular2 beta 7, and this seems to be causing the issue.
After returning to Angular2 beta 3 the problem stopped and my memory usage is back to normal.

**Comment by koenswaanen** [comment] 2016-02-24 12:34
Apparently returning to Angular2 beta 3 didn't solve the problem.
It was looking good at first, but now I'm back at 2.8GB memory usage...

**Comment by slaviki** [comment] 2016-02-24 12:47
Also tried to return to Angular beta 2 and it didn't help at all. Same problems with memory and CPU

**Comment by vladima** [comment] 2016-02-24 18:08
if project is not very big you can mail it to `vladima` at `microsoft` dot `com`. Otherwise you can use any existing file sharing solution (OneDrive, Dropbox etc..) and then send a link to the email above.

**Comment by slaviki** [comment] 2016-02-24 18:33
I've sent project to your e-mail

**Comment by slaviki** [comment] 2016-02-26 04:02
Were you able to reproduce this issue? Maybe you need any other information?

**Comment by vladima** [comment] 2016-02-26 04:49
yes, thanks for the repro.

**Comment by pamerio** [comment] 2016-03-12 09:10
Exactly the same problem here: Angular2, TypeScript 1.8. Opening a .ts files memory start growing up to 2Gb and CPU as well. All the Visual Studio functionality start to be slow (especially IntelliSense). then, after 15-20 min Visual Studio crashes.
Any news on this problem?

**Comment by KenYates99** [comment] 2016-04-12 14:17
Having the same problem as of 4/11.  Angular2 beta 12 with typescript 1.8.2.  Any update on this issue?

**Comment by mhegazy** [comment] 2016-04-19 18:57
We tracked this issue to RxJS 5.0.0-beta.5, but it should be resolved with 5.0.0-beta.6. what version of RxJS are you using?

**Comment by pamerio** [comment] 2016-04-20 06:13
I'm using RxJS 5.0.0-beta.2 I upgrade and let you know.

**Comment by slaviki** [comment] 2016-04-20 18:57
I've tried with RxJS beta.6. Memory usage looks ok, but CPU still spikes on Intellisense.

**Comment by mhegazy** [comment] 2016-04-20 19:15
the spike is not intellisense, it is more of edit. on every edit we need to do a full check on all files, open and closed. so depending on the size of the project, you can see some CPU utilization. this should subside at some point though, if not, then this is an issue.

**Comment by kvgros** [comment] 2016-04-21 19:14
We are seeing the same thing here.   Seemed fine for the last few weeks and (without any change we know of) our VS 2015 is killing memory.  Suspiciously we are using the same basic projects you are above (ng2, RxJS, etc).   We are currently leaning towards it being TS related either due to compilation behind the scenes or intellisense (thus looking for answers here).   My VS taps out at about 2.7gig of memory after opening the project and then crashes.

**Comment by mhegazy** [comment] 2016-04-21 19:21
is there a chance you can share the project, or a set of repro steps to get to the same behavior?

**Comment by vladima** [comment] 2016-04-21 19:26
also what version of RxJs do you use?

**Comment by kvgros** [comment] 2016-04-21 19:31
Reading through the above we reverted back to RxJs beta 2.  Testing now but it appears to have solved our issue (we are on Ng2.beta.15).

**Comment by kvgros** [comment] 2016-04-22 15:01
I thought we had it fixed yesterday but today it's back (rxJS Beta 2 and NG2.beta.15 just as stated in the last post).   Memory skyrockets to about 2.5gig per developer upon opening the solution.   Intellisense for Typescript is almost non-existent (extremely slow).   Has been working great for months and no issues until the last few days on our end.

**Comment by KenYates99** [comment] 2016-04-22 15:19
I ended up deleting my local repo and cloning local and haven't had the problem again... yet.  Seems like a short term solution.  One thing of note is that I do not currently have Intellisense for rxjs (.map as an example).  When I was having this problem the Intellisense for jxjs was working.  I think there may be a correlation.

**Comment by vladima** [comment] 2016-04-22 15:59
Any changes we can have a look at your projects to figure out the root cause of such behavior? We can sign NDA if necessary?

**Comment by kvgros** [comment] 2016-04-22 16:03
Unfortunately not.  It’s a client project and they have been less than willing to share it for similar purposes in the past.   If it was something I had control over I’d gladly sign an NDA and share.

-Kevin

**Comment by mhegazy** [comment] 2016-04-22 23:51
is there a tsconfig.json in the project? can you share that file?

**Comment by kvgros** [comment] 2016-04-25 17:25
We are using this tsconfig.json file:

{
  "compileOnSave": true,
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": false,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "module": "commonjs"
  },
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ]
}

**Comment by mhegazy** [comment] 2016-04-25 17:44
is this the same file you use for building as well? what do you see when you run the compiler with `tsc --p <your tsconfig.json> --diagnostics`? does disabling compileOnSave make any difference?

**Comment by Aides359** [comment] 2016-05-12 15:04
I am experiencing the same issue with Angular 1.5.3 and Typescript 1.8 - not using RxJS.
VS2015 is on 2.3-2.5 GB RAM while the project is loaded. As soon as I close the project it goes back to normal.

**Comment by aleksey-bykov** [comment] 2016-05-12 15:10
might be related: #8152

**Comment by mhegazy** [comment] 2016-05-12 17:19
@Aides359 can you share your project?

**Comment by Aides359** [comment] 2016-05-13 10:10
It seems as if in my case [nodejstools#44](https://github.com/Microsoft/nodejstools/issues/44) and [nodejstools#88](https://github.com/Microsoft/nodejstools/issues/88) seemed to be related in my case.

I have now added node_modules to my analysis ignore (`<AnalysisIgnoredDirectories>node_modules</AnalysisIgnoredDirectories>`) and VS is back to 1 GB RAM

@mhegazy sharing the project would be quite a fight with my project manager and since it is working now I'd like to avoid that. In any case, I will get back to you if it the problems reoccur.

**Comment by mhegazy** [comment] 2016-05-13 16:43
@Aides359 thanks for getting back to us on this. please let us know if you run into other issues.

**Comment by Aides359** [comment] 2016-06-02 14:56
Just to bring it to notice, VS is still working fine. 
Apparently for me the problem was really caused by nodejstools including my libraries in its analysis.

**Comment by vladima** [comment] 2016-06-08 00:40
closing since it was fixed on [RxJS side](https://github.com/ReactiveX/rxjs/pull/1475).

**Closed by vladima** 2016-06-08 00:40 UTC
Labels: Bug, High Priority
