### ISSUE TITLE
[Transforms] Incorrect down-level export decorated class declaration

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#8206] opened 2016-04-20 00:47 UTC
**Original**
```ts
@dec
export class C {
}
```
**Expected**
```js
var C = (function () {
    function C() {
    }
    return C;
}());
C = __decorate([
    dec
], C);
exports.C = C;
```
**Actual**
```js
exports.C = (function () {
    function C() {
    }
    return C;
}());
C = __decorate([
    dec
], C);
```
- decoratorOnClass2

**Comment by sandersn** [comment] 2016-04-20 18:23
Duplicate of #8073. I'll move this test case over there to make sure we fix it.

**Closed by sandersn** 2016-04-20 18:23 UTC
Labels: Bug, Domain: Transforms
