### ISSUE TITLE
Object.keys' returntype should be specified

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/TypeScript#49502] opened 2022-06-12 11:21 UTC
# Bug Report

when you get keys of some object by `Object.keys`, then assign value to it, will get an error like 
_Element implicitly has an 'any' type because expression of type 'string' can't be used to index type_

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBCBGArGBeGBvAhgLgIwBp5sYAmAXwCgAzEAJwApRJYBrAUwE84qYB5JNsCgA6dhwj0EiAJTT0FGHCQBtMQF1UMAMwUyQA)

### 💻 Code

```ts
const obj = {a:1,b: 2}
for(const key of Object.keys(obj)){
  obj[key] = 3
}
```

### 🙁 Actual behavior

obj[key] will report error
![image](https://user-images.githubusercontent.com/49113249/173230728-d775e6fe-8553-4240-b46c-9fe317c2f133.png)

### 🙂 Expected behavior
narrow `Object.keys` return type like 
```
type Keys<T extends object> = (o:T) =>  UnionToTuple<keyof T>
```

maybe we coule implement `UnionToTuple` like thing

**Comment by jcalz** [comment] 2022-06-12 12:05
Duplicate of #45390 and a bunch of others. Did you search for existing issues?

**Closed** 2022-06-15 18:00 UTC
Labels: Duplicate

**Comment by HomyeeKing** [comment] 2022-06-16 02:48
@jcalz  yes I have searched and still no solution,  just wanna get more attenion about this

**Comment by RyanCavanaugh** [comment] 2022-06-16 16:52
This is the intended behavior and we're not changing it.
