### ISSUE TITLE
Narrowing of indexed access type only allows apparent type access; don't allow assignability

### ISSUE THREAD

**Issue by charles-toller** [microsoft/TypeScript#32502] opened 2019-07-21 20:05 UTC
**TypeScript Version:**  3.6.0-dev.20190720

**Search Terms:** type narrowing undefined generics early return

**Code**

```ts
type BaseEvents = {[event: string]: Array<any>};
type Cbs<A extends BaseEvents> = {
    [P in keyof A]: Array<(...args: A[P]) => boolean | Promise<boolean>> | undefined;
}
export class Events<T extends BaseEvents> {
    private cbs: Cbs<T> = {} as any;
    async emit<P extends keyof T>(event: P, ...args: T[P]) {
        const arr = this.cbs[event]; // typeof arr = ((...args: T[P]) => boolean | Promise<boolean>)[] | undefined
        type NonNullArr = NonNullable<typeof arr>; // ((...args: T[P]) => boolean | Promise<boolean>)[]
        if (typeof arr === 'undefined') {
            return;
        }
        // typeof arr should now be ((...args: T[P]) => boolean | Promise<boolean>)[]
        const nonNullArr: NonNullArr = arr; // TS2322: Type '((...args: T[P]) => boolean | Promise<boolean>)[] | undefined' is not assignable to type 'NonNullable<Cbs<T>[P]>'.
                                            // Type 'undefined' is not assignable to type 'NonNullable<Cbs<T>[P]>'.
        for (const cb of arr) { // TS2488: Type 'Cbs<T>[P]' must have a '[Symbol.iterator]()' method that returns an iterator.

        }
        for (const cb2 of nonNullArr) { // No error

        }
    }
}
```

**Expected behavior:** Compiles without errors.

**Actual behavior:** Several errors relating to arr not narrowing out the `undefined` portion of the argument:

```
Error:(14, 15) TS2322: Type '((...args: T[P]) => boolean | Promise<boolean>)[] | undefined' is not assignable to type 'NonNullable<Cbs<T>[P]>'.
  Type 'undefined' is not assignable to type 'NonNullable<Cbs<T>[P]>'.
Error:(16, 26) TS2488: Type 'Cbs<T>[P]' must have a '[Symbol.iterator]()' method that returns an iterator.
```

**[Playground Link](http://www.typescriptlang.org/play/#code/C4TwDgpgBAQghgZwgUQG4QHbAVAvFAbwG0J0sAuKBYAJwEsMBzAXUoEEaa4QAeODEAD4AvgG4AUKEhQAwgCMEPNlAgAPYJgAmOeEjSZsgvIXFQzUIgAUoDKAGsIIAPYAzKG1bvO3HgAoAdIFwNIwI7FbMAJR4RnJOTgA2EPxQAD5QljROALZ0SDxxickYgkbpAK4YmhAuDBCaEsLiamBONMBQAMYJiDj6WIoAKirqWjqIKGSGJuZQYPSocBpdCpTyQ0b4BMJQiLsCErOIIBidKrnAPNZqGlU4Ds5ug4K+pAaUlgA0UIH+waGUQYRaIEUyzcydJwYai7TjGYAACzy-k6ChIU2YoigAHpsVApBBXLCaMZfAEgiEwlAgZYojEoIUkil0pkcnkIAV4kySpEiMw0lBKtVahh6mDwfjwNAAHJQ6XlBIJDgk-CyjDyxVwORJHgEonBGiCLG4qBk37-Kk0um4WJc4oC1m5fKM4qCXnMcXguhuXx6twGvC4fAAciFNTqmmDIM9ErMNAgwHKNAwh1jTVjOLxfuJVARTgVmigGCcAHcGdAzRSAdTgfSXcyMlknRz6zy+TGIVCYcX1QqlZxKGqNf2VcTjXjBgBlABMAGZp9PAVKoMHK39KYDazaGXaG472Zyivw3XyBWGRfVgzYcMWOr06IwMFqkvinJLpMGh33nxz1jxnhEgjBv4HYZmB4EQSagzLqGVThqKkbXkWTh3ggCAPk+2rQMAb4EiuX6alhPB-gBtJASBGYuG0pqQtCHSolA+qcCCmbUjOAAsAAcnFLh+JGCBEV7ZOUMIInA6C7CuRCTiA2RxAk-h0BoXA4TQzC+JEQkJnmhaIksUDxomyY4CkSkQCpbQgaBUDprGVEkr4tEwqi06MW4PbDsqLEmrKKicG04jWbZZhNMIQA)**

**Related Issues:**

#1726 (closed by design, this is different because we can assume any array is not undefined)

#31456 (this example has a constraint)

**Comment by RyanCavanaugh** [comment] 2019-07-31 19:52
Example with fewer moving parts:
```ts
type Obj<T> = {
  [K in keyof T]: string | undefined;
}

// 2 type parameter version
function foo2<T, K extends keyof T>(obj: Obj<T>, arg: K) {
  const m = obj[arg];
  if (m === undefined) {
    m;
  } else {
    // Error
    const s: string = m;
    // No error (??)
    m.substr(0);
  }
}

// 1 type parameter version
function foo1<T>(obj: Obj<T>, arg: keyof T) {
  const m = obj[arg];
  if (m === undefined) {
    m;
  } else {
    // Error
    const s: string = m;
    // No error (??)
    m.substr(0);
  }
}
```

**Comment by jack-williams** [comment] 2019-08-01 09:27
Is this a duplicate of #31908?

**Modified** version from the linked issue that looks very similar.
```ts
function getValue<T extends Record<keyof T, () => string>, K extends keyof T>(partial: Partial<T>, key: K): T[K] | null {
  const value = partial[key]
  if (value !== undefined) {
      value(); // no error
      return value // error:
  }
  return null
}
```

**Comment by ahejlsberg** [comment] 2019-10-20 14:44
This is a design limitation and effectively a duplicate of #31908. We'd like to do better here, but we don't know of a solution yet. Effectively, we need control flow analysis to use higher order types (such as `NonNullable<T>`) to reflect effects of constructs like `value !== undefined`, but this bring about a host of other issues as we've seen in #22348.

**Closed** 2019-10-22 18:00 UTC
Labels: Design Limitation, Domain: Indexed Access Types, Duplicate
