### ISSUE TITLE
Extracting big typescript interface

### ISSUE THREAD

**Issue by 1alexvash** [microsoft/TypeScript#50924] opened 2022-09-23 17:22 UTC
When we have a big JavaScript object like the one bellow:

![image](https://user-images.githubusercontent.com/46556479/192020118-77f8081f-8fe3-4f87-a5bd-ba9af089b6a3.png)

And when we try to hover over the TS interface, some of those fields don't make it into VS code suggestion

![image](https://user-images.githubusercontent.com/46556479/192020770-765374e8-ab72-41a5-8f3c-bfebbed940f5.png)

Is there an easy way to get a full interface?

If not, it would be cool to add some "copy interface" button

**Comment by mjbvz** [comment] 2022-09-23 18:06
As a follow up to #40750, I suggest we expose a refactoring to add the inferred type to variables too

**Comment by a-tarasyuk** [comment] 2022-09-23 18:12
@mjbvz Is it a duplicate of https://github.com/microsoft/TypeScript/issues/32319?

**Comment by mjbvz** [comment] 2022-09-23 18:25
Yep thanks! Looks like a duplicate of #32319 / #13199

**Closed by mjbvz** 2022-09-23 18:25 UTC

**Comment by a-tarasyuk** [comment] 2022-09-23 18:29
I made a [PR](https://github.com/microsoft/TypeScript/pull/44674) to fix them, however, both issues are not very [popular](https://github.com/microsoft/TypeScript/pull/44674#pullrequestreview-731228971), so we didn't merge it.

**Comment by zardoy** [comment] 2023-03-24 01:27
> I don't understand why it is not accepted.

@yw662 For especially this one you can already use *Split declaration and initialization* from plugin that would write full type without truncation. This is super useful, I actually use it on daily basis.

**Comment by yw662** [comment] 2023-03-24 01:57
@zardoy Is it a vscode plugin or ?

**Comment by zardoy** [comment] 2023-03-24 02:44
> @zardoy Is it a vscode plugin or ?

Yes, I mean this one https://github.com/zardoy/typescript-vscode-plugins which suggests when you put cursor on const keyword. But it's essentially the same as you split initialisation and declaration by hand and then apply infer you quick fix

**Comment by yw662** [comment] 2023-03-24 03:36
Yeah I like it and it works. Thank you for such a handy tool.

For me, I am working on a documentation of a typescript project, and I what to copy-paste some inferred types to the doc. Could I just copy the types with the plugin ?

**Comment by zardoy** [comment] 2023-04-19 21:12
@yw662 Sorry for the delay, I finally added a command to copy full type (without truncation) from the hover: `tsEssentialPlugins.copyFullType`, which you can bind to keybinding

**Comment by yw662** [comment] 2023-04-19 22:29
Thanks @zardoy I have finished that doc by hand but I am sure this will be very helpful for all.

**Comment by yw662** [comment] 2023-04-19 22:37
That's really cool it can copy arbitrary type definitions as long as it has one. I tried everything I can find in my code and it just works. People should know that really.
