### ISSUE TITLE
PropertyKey conflicting definition in lib.d.ts and es6-shim

### ISSUE THREAD

**Issue by andrewkon** [Microsoft/TypeScript#7839] opened 2016-04-05 21:43 UTC
Filed https://github.com/TypeStrong/ntypescript/issues/19, but it was closed due to not being nTypeScript specific. Opening here.

**TypeScript Version:** 

Latest nTypeScript release

**Code**

tsconfig.json:

```
{
  "compilerOptions": {
    "target": "ES5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "outDir": "javascript"
  },
  "files": [
    "./typescript/main.ts",
    "./typed/sha.js.d.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

main.ts:

```
/// <reference path="../typings/browser.d.ts"/>

import "angular2/bundles/angular2-polyfills";

import {bootstrap} from "angular2/platform/browser";
import {AppComponent} from "./app.component";
import {ROUTER_PROVIDERS} from "angular2/router";

bootstrap(AppComponent, [ROUTER_PROVIDERS]);
```

**Expected behavior:**

everything should compile successfully

**Actual behavior:** 

```
node_modules/ntypescript/bin/lib.d.ts(1266,14): error TS2300: Duplicate identifier 'PropertyKey'.
typings/browser/ambient/es6-shim/index.d.ts(8,14): error TS2300: Duplicate identifier 'PropertyKey'.
```

**Comment by mhegazy** [comment] 2016-04-05 21:49
duplicate of https://github.com/Microsoft/TypeScript/issues/7812. should be fixed in tommrow's build.

**Closed** 2016-04-05 21:49 UTC
Labels: Duplicate
