### ISSUE TITLE
Allow blacklisting paths in auto import suggestions

### ISSUE THREAD

**Issue by skog-newglue** [microsoft/TypeScript#47061] opened 2021-12-08 07:48 UTC
# Suggestion

## 🔍 Search Terms

- blacklist path
- exclude path
- blacklist auto import path
- exclude auto import path

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow blacklisting/exclusion of auto import paths.

Here are some possible solutions as I see it:

- Allow blacklisting/excluding paths for auto imports
- Suggest all possible paths and let the developer choose which path is correct

## 📃 Motivating Example

In certain scenarios, such as when using a monorepo with Angular and Nx, you will have an `index.ts` file for your libraries which acts as the entry point. This creates huge issues when using `project-relative` imports in VSC, as it suggests the `index.ts` file instead of the actual file when working with imports that are inside the same library. Using the `index.ts` file will cause any app consuming the library to crash due to what I assume are circular dependencies.

Here I expect to get `../../helpers/global/is-external-url` instead of `../../../index`:

<img width="783" alt="Screenshot 2021-12-07 at 11 08 30" src="https://user-images.githubusercontent.com/83581833/145167377-2bd6409e-7058-447a-a965-4d3390c84dd7.png">

## 💻 Use Cases

**What do you want to use this for?**
See above explanation.

**What shortcomings exist with current approaches?**
It's really easy to mess up without knowing what is wrong, and there isn't a way to solve this currently as far as I'm aware.

**What workarounds are you using in the meantime?**
- Added an ESLint rule that shows an error when using an `index.ts` import, still doesn't prevent compilation so you might not even notice that you have an error until you try to build (assuming you have ESLint check enabled when building)
- Using "Quick Fix" and then choosing the correct import path there, but this is annoying and wastes your time. The correct path should show up when typing.

**Comment by fatcerberus** [comment] 2021-12-08 08:23
Basically the same issue as #45953.

**Comment by RyanCavanaugh** [comment] 2021-12-09 18:30
Yeah, duplicate of either that one or #35395 depending on the use case

**Closed** 2021-12-12 18:00 UTC
Labels: Duplicate
