### ISSUE TITLE
Official recommendation for consuming nodejs modules in a browser-only project?

### ISSUE THREAD

**Issue by DustinWehr** [Microsoft/TypeScript#5268] opened 2015-10-15 17:49 UTC
What is the easiest way to, for example, use the node.js "debug" module in a browser-only application that's currently organized with Internal Modules? 

I've been using Typescript for over 6 months now, and I still have this question that I've had since day 1:
Do you guys recommend using a preprocessor like browserify or webpack as part of the build process for applications meant to run in the browser? That would surprise me, since the Handbook section on External Modules makes it sound like the TS compiler can do at least the basics of what they do (and the basics are all I need).

However, the Handbook says "Applications not using node.js or require.js do not need to use external modules and can best be organized using the internal module concept outlined above."
Perhaps I've misinterpreted what is meant by "using node.js". My code doesn't use the node interpreter. So far that Handbook blurb has made me steer clear of using other people's nodejs modules, or even in one case converting someone's library, that seemed to unnecessarily be packaged as a nodejs module, to plain js (note: I am obviously still fairly new to web development, but I do have a PhD in CS). Other than not being able to use nodejs modules, I've been completely satisfied with Internal Modules.

I would be very grateful to get a response on this.

**Comment by RyanCavanaugh** [comment] 2015-10-15 18:05
I assume you're referring to modules that use something like UMD; literally running node.js modules in the browser is not technically possible.

Normally a module that works in both node and in the browser will either *also* expose a global when run outside of the node platform (debug.js does this), in which case you can just refer to the global object directly, or provide a RequireJS/AMD-compatible module, in which case you would either compile with `--module amd` or compile with `--module commonjs` and use something like browserify to bundle everything together.

I think the Handbook is out of date on those recommendations and we should update it to recommend using ES6 modules or CommonJS compilation with browserify.

**Comment by DustinWehr** [comment] 2015-10-15 21:39
I was trying too hard to use the correct terminology so not to sound like a *total* newb: what I actually meant by "module" is: a library published as an npm package. Some of those don't actually depend, directly or indirectly, on node, but the author, by using require(.) statements, assumes that users writing client-side browser applications are already using something like browserify. An example is immutable/contrib/cursor, where the author wrote:
````
/**
 * Cursor is expected to be required in a node or other CommonJS context:
 *
 *     var Cursor = require('immutable/contrib/cursor');
 *
 * If you wish to use it in the browser, please check out Browserify or WebPack!
 */
````
A minimal example would be a node.js package that uses require(.) exactly once to import debug.js, but is otherwise plain js.

Anyway, you answered my question. Thank you so much! I owe you one.

(I don't know if I should close this or if you wanted it to serve as a todo for updating the docs)

**Comment by RyanCavanaugh** [comment] 2015-10-15 21:50
I'll leave it open so we can update the Handbook. We should also have an official sample that uses browserify or somet other tool to show using a UMD or otherwise module-system-aware module in a cross-platform way.

**Comment by DustinWehr** [comment] 2015-10-15 21:51
Help! I just tried to use "the web browser implementation of `debug()`" looked like the browser version of debug.js, at node_modules/debug/browser.js in my project. But it uses require(.) as well! What am I missing?

**Comment by RyanCavanaugh** [comment] 2015-10-15 21:58
It looks like it's assuming browserify, yes

**Comment by mhegazy** [comment] 2016-02-20 05:02
looks like a duplicate of https://github.com/Microsoft/TypeScript-Handbook/issues/165

**Closed by mhegazy** 2016-02-20 05:02 UTC
Labels: Docs
