### ISSUE TITLE
Cannot set readonly property in IIFE

### ISSUE THREAD

**Issue by medikoo** [microsoft/TypeScript#60413] opened 2024-11-04 15:54 UTC
### 🔎 Search Terms

"readonly", "iife"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### 💻 Code

```ts
class Foo {
	readonly bar: string = "";
	constructor() {
		(() => { this.bar = "test"; })();
	}
}
```

### 🙁 Actual behavior

Fails with `Cannot assign to 'bar' because it is a read-only property.` error

### 🙂 Expected behavior

Should work in exactly same way as:

```typescript
class Foo {
	readonly bar: string = "";
	constructor() {
		this.bar = "test";
	}
}
```

### Additional information about the issue

I assume that's expected for some reason, and I'd love to learn what are the logical grounds for that

**Comment by MartinJohns** [comment] 2024-11-04 16:10
Essentially another duplicate of #9998. #58729 would likely fix this.

**Comment by jcalz** [comment] 2024-11-04 16:12
@MartinJohns aren’t IIFEs already inlined for CFA? I’m guessing initialization of `readonly` fields must be handled separately.

**Comment by MartinJohns** [comment] 2024-11-04 18:03
You're right, my mistake. I swear I saw this issue before, but can't find it. :-/

**Closed** 2024-12-02 19:15 UTC
Labels: Bug, Help Wanted
