### ISSUE TITLE
tslint.json doesn't work in Visual Studio 2015 if line endings are in UNIX format.

### ISSUE THREAD

**Issue by wanton7** [Microsoft/TypeScript#9570] opened 2016-07-08 11:11 UTC
**TypeScript Version:**  1.8.6 (installed from https://www.typescriptlang.org/)

**Expected behavior:**

tslint.json settings work and show warnings for TypeScript files in Visual Studio 2015.

**Actual behavior:** 

No warnings are shown at all if you add tslint.json to project root that has UNIX (\n) line endings.
Only tslint.json with Windows/DOS (\r\n) line endings work.
I was using .xproj project.

**Comment by mhegazy** [comment] 2016-07-08 21:33
looks like an tslint extension issue. should be reported to https://github.com/madskristensen/WebAnalyzer/issues

**Comment by wanton7** [comment] 2016-07-08 21:42
I haven't installed any extensions like that. Only have installed TypeScript 1.8.6, visual studio 2015 update 3  and asp net core tools preview 2.
I'm using tslint support  that those bring. Or do those install that extension you are referring to?

**Comment by mhegazy** [comment] 2016-07-08 21:45
TS does not come with a linter installed. so if you are linting in VS you have installed a linter extension (i guessed it is WebAnalyzer), if on the command line then it would be tslint (https://github.com/palantir/tslint)

**Comment by wanton7** [comment] 2016-07-08 21:47
Nope have not installed any other extensions to my visual studio 2015. Only those i listed.

**Comment by mhegazy** [comment] 2016-07-08 21:58
@sayedihashimi, @madskristensen, where should these issues be reported?

**Comment by wanton7** [comment] 2016-07-08 21:59
My installed extensions

Azure AD Authentication Connect Service
Developer Analytics Tools
Get Xamarin
Microsoft .NET Core Tools
Microsoft ASP.NET and Web Tools
Microsoft ASP.NET Web Frameworks and Tools
Microsoft Azure App Service Tools
Microsoft Azure Mobile Services Connected Service
Microsoft Azure Storage Connected Service
Microsoft Connected Services
Microsoft Office 365 API Tools
NuGet Package Manager for Visual Studio 2015
PowerShell Tools for Visual Studio 2015
TypeScript for Microsoft Visual Studio

And i have Tools/Options/Text Editor/TypeScript/TSLint
So something in that list adds tslint support and i thought it was TypeScript 1.8.6 that's why i'm reporting this here.

**Comment by jwbay** [comment] 2016-07-10 04:52
TSLint support was baked into Visual Studio as of Update 3. No extensions are involved.

**Comment by sayedihashimi** [comment] 2016-07-10 06:37
@wanton7 can you try with a new Empty asp.net core web project to see if you run into same issue?

**Comment by wanton7** [comment] 2016-07-10 07:30
Tried it with empty project, seems that I was wrong. It's not the line endings that causes this problem but file encoding.

Here is how you get broken tslint.json, add new JSON file with Add New Item. It will create json file that has encoding UTF-8-BOM (in Notepad++). That file just refuses to work, no warnings are show for TypeScript files.

Then if you change that files encoding with Notepad++ to UTF-8 it starts to work.

**Comment by adidahiya** [comment] 2016-07-11 18:27
By the way, the handling of BOM in tslint.json was fixed in TSLint 3.12 https://github.com/palantir/tslint/commit/606b94f0de768a93baad0141c71417d1177fd084 (after a regression somewhere between 3.0 and 3.12).

**Comment by sayedihashimi** [comment] 2016-07-11 20:16
I think this issue is due to a component from the ASP.NET team. Could someone file an issue at https://github.com/aspnet/tooling/ with specific steps to reproduce?

**Closed** 2016-09-20 23:14 UTC
Labels: External
