### ISSUE TITLE
Intellisense is not working for self-references and # imports of typescript files in vscode

### ISSUE THREAD

**Issue by magnusriga** [microsoft/TypeScript#57777] opened 2024-03-14 10:06 UTC
### 🔎 Search Terms

"imports", "# imports"

### 🕗 Version & Regression Information

- This is a bug
- As far as I know, it has never worked

### ⏯ Playground Link

https://github.com/magnusriga/my-app

### 💻 Code

```ts
// foo.tsx
import { Bar } from "#app/bar"; // Resolved by TS, but lacking Intellisense (ctrl+space suggestions).
import { Baz } from "my-app/baz"; // Resolved by TS, but lacking Intellisense (ctrl+space suggestions).
import { Qux } from "./qux"; // Resolved by TS and has full Intellisense.
export const Foo = () => {
  return (
    <>
      <Bar bar="bar" />
      <Baz baz="baz" />
      <Qux qux="qux" />
    </>
  );
};
```
```ts
// bar.tsx (baz.tsx and qux.tsx are similar)
export const Bar = ({bar}: {bar: string}) => {
  return <div>{bar}</div>
}
```

```json
// package.json
{
...
 "name": "my-app",
  "imports": {
    "#app/*": "./src/app/*.js"
  },
  "exports": {
    "./*": "./src/app/*.js"
  },
...
```

I am using `"typescript": "5.5.0-dev.20240314"`.

### 🙁 Actual behavior

The import specifiers do not provide Intellisense suggestions. TS is able to resolve the files however, so there is no TS error.

### 🙂 Expected behavior

The expected behavior is for Intellisense to understand the TS resolution and provide suggestions with ctrl+space.

**Comment by magnusriga** [comment] 2024-03-14 10:30
Probably your domain, @andrewbranch ? Or @sheetalkamat. Thank you very much for any/all help,

**Comment by Andarist** [comment] 2024-03-14 10:49
duplicate of https://github.com/microsoft/TypeScript/issues/52460 , it is being worked on here: https://github.com/microsoft/TypeScript/pull/57718

**Comment by magnusriga** [comment] 2024-03-14 11:32
Thanks @Andarist . Shouldn't the self-referencing import work already? That uses `exports`, not `imports`, in package.json.

**Comment by Andarist** [comment] 2024-03-14 15:26
Self-references should also work. @andrewbranch has mentioned before that the code might not be best prepared for this at the moment though. I'm not sure but that might require some new preferences or considering how this would play out with the existing ones. Self-references are not that popular and might be surprising to many people. Suggesting this in import statements would be probably totally fine - but a question stays about how auto-imports should work with that.

**Comment by magnusriga** [comment] 2024-03-14 17:16
@Andarist I am ok using # imports instead of self-references (Intellisense works in neither, as of typescript `5.5.0-dev.20240314`). Any thoughts on when this functionality might be merged into the `next` version of typescript?

**Comment by Andarist** [comment] 2024-03-14 18:49
I'll work on code-level improvements to my PR sometime soon. Other than that, it will require review (and merge) from the team - I can't say when that will happen.

**Closed** 2024-03-17 01:27 UTC
Labels: Duplicate

**Comment by gracefullight** [comment] 2024-09-04 23:01
Is there any plan to support this feature in version 5.6?
