### ISSUE TITLE
error while Readonly<Function>

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#32697] opened 2019-08-03 17:34 UTC
**TypeScript Version:**  3.5.2

**Search Terms:** readonly call

**Code**

```ts
declare const f :Readonly<() => void>;
f();
```

**Expected behavior:**

**Actual behavior:**

```
TS2349: Cannot invoke an expression whose type lacks a call signature.
Type 'Readonly<() => void>' has no compatible call signatures.
```

Had to use below to avoid error:

```ts
declare const f :( () => void ) & Readonly<{}>;
f();
```

**Playground Link:** 

**Related Issues:**

**Comment by jcalz** [comment] 2019-08-03 19:23
🔍🔎🔍🔎  Duplicate of #32566

**Comment by LongTengDao** [comment] 2019-08-03 20:46
> 🔎 Duplicate of #32566

@jcalz Thank you!

I see that issue is auto closed, does that means this bug won't be fixed?

**Comment by AnyhowStep** [comment] 2019-08-03 23:41
It means it isn't a bug

**Comment by nattthebear** [comment] 2019-08-04 00:22
Can I ask what is it that you expected `Readonly<() => void>` to do that `() => void` does not do, but `( () => void ) & Readonly<{}>` does?

**Comment by LongTengDao** [comment] 2019-08-04 03:16
@AnyhowStep In fact, I want to notice the user do not reset the properties of an function/class. It seems that I need to write a custom type to implement that...

**Comment by LongTengDao** [comment] 2019-08-04 03:18
> Can I ask what is it that you expected `Readonly<() => void>` to do that `() => void` does not do, but `( () => void ) & Readonly<{}>` does?

@nattthebear I want to notice the user do not reset the properties of an function/class. I found `( () => void ) & Readonly<{}>` wont do that just now, it only makes the type callable again.

**Comment by nattthebear** [comment] 2019-08-04 12:04
> @nattthebear I want to notice the user do not reset the properties of an function/class, like `prototype` `call` and so on.

Could use `(() => void) & Readonly<Function>;`

[Playground](http://www.typescriptlang.org/play/#code/CYUwxgNghgTiAEA3W8BmAueAKAlPAvAHxID2AlsANwBQ1qAdGFBBAWgK4B2YALmSZ1zwA3vAC+NBgAcYJHnICeUhPnid2LGtVCRYCZDHgBzTFiFFSFPADJ4AJRBRgAiAoA8AMS69+nQlqNGZlZVVG8+ASFRCWpAmTlFZTZ1TWogA)

**Closed** 2019-08-04 16:09 UTC
