### ISSUE TITLE
Inconsistent type narrowing

### ISSUE THREAD

**Issue by ThomasdenH** [Microsoft/TypeScript#27569] opened 2018-10-05 08:04 UTC
**TypeScript Version:**  3.2.0-dev.20181004

**Search Terms:** inconsistent type narrowing inline function

**Code**

Variant 1:
```ts
const props: {a?: number} = {a: 0};
if (typeof props.a !== 'undefined')
  console.log(props.a.toString());
```

Variant 2:
```ts
function acceptsArg(props: {a: number}): void {
  console.log(props.a.toString());
}

const props: {a?: number} = {a: 0};
if (typeof props.a !== 'undefined')
  acceptsArg(props);
```

**Expected behavior:**
Either both variants compile, or neither do. Preferably both do, since the behaviour is save.

**Actual behavior:**
The first variant compiles, while the latter doesn't.

**Playground Link:**
- [Variant 1](https://www.typescriptlang.org/play/#src=const%20props%3A%20%7Ba%3F%3A%20number%7D%20%3D%20%7Ba%3A%200%7D%3B%0D%0Aif%20(typeof%20props.a%20!%3D%3D%20'undefined')%0D%0A%20%20%20%20console.log(props.a.toString())%3B%0D%0A%20%20)
- [Variant 2](https://www.typescriptlang.org/play/#src=function%20acceptsArg(props%3A%20%7Ba%3A%20number%7D)%3A%20void%20%7B%0D%0A%20%20console.log(props.a.toString())%3B%0D%0A%7D%0D%0A%0D%0Aconst%20props%3A%20%7Ba%3F%3A%20number%7D%20%3D%20%7Ba%3A%200%7D%3B%0D%0Aif%20(typeof%20props.a%20!%3D%3D%20'undefined')%0D%0A%20%20%20%20acceptsArg(props)%3B%0D%0A%20%20)

**Related Issues:** -

**Comment by jack-williams** [comment] 2018-10-05 11:20
Think this is a duplicate of #25930

**Comment by ThomasdenH** [comment] 2018-10-05 11:34
If it is, I don't understand why variant 1 does work.

**Comment by jack-williams** [comment] 2018-10-05 11:46
Probably because it's easier to implement and doesn't involve creating a new object type in the compiler. I suspect turning on the behaviour in Variant 2 might have a noticeable performance impact.

**Comment by RyanCavanaugh** [comment] 2018-10-08 11:14
See #10065

**Closed** 2018-10-09 17:42 UTC
Labels: Duplicate
