### ISSUE TITLE
Add IntelliSense option "Only use tab or enter to commit"

### ISSUE THREAD

**Issue by RandScullard** [microsoft/TypeScript#315] opened 2014-07-30 18:45 UTC
In Visual Studio 2013, in Options, Text Editor, JavaScript, IntelliSense, there is a checkbox labeled "Only use tab or enter to commit". Currently, TypeScript always behaves the way JavaScript does with this option turned ON, and provides no similar option to turn it off. 

For those of us who have been working in C# and JavaScript for years with this option turned off -- and who need to work in all three languages in a single project -- it's frustrating that TypeScript doesn't work the same way. It would be a huge improvement to let us set this option.

See also: http://typescript.codeplex.com/workitem/965

**Comment by Peter-Juhasz** [comment] 2015-01-07 20:55
It seems like we will never get this essential (again: **essential**) functionality which **we are used to** and *loved for years* before **since Visual Studio exists**...

Even Visual Studio '97 could complete the selected item while writing the next few characters. All language (JavaScript, T-SQL) has this option, which works this way by default. Or take a look at the HTML editor: when the caret is in this position:
`<script type="|"`
...and you have a selected completion, you can even press a '>' and it will take care of everything: activate the selected completion, insert the typed '>' after (!) the closing '"', close the tag automatically and position the caret into the correct place, so you get:
`<script type="text/javascript">|</script>`

**Comment by jseanxu** [comment] 2015-01-13 21:57
@CyrusNajmabadi 

>@jseanxu Yup. Definitely a bug. Will fix right away!

Could we get an update on this issue? I see the fix has been postponed 3 times :(

**Comment by danquirk** [comment] 2015-01-13 22:53
Status is this:

Previously TS in VS only commit completions on tab and enter so there was no need for an option to toggle what keystrokes commit completions. The intention was to move to the C# style behavior where space and punctuation characters also commit completion lists. This behavior was turned on recently but has some unfavorable interactions with certain completion list scenarios (see #1629). I want to make sure we clean up some of these experiences or else the new completion commit characters can be more annoying than helpful in a lot of cases. In any case we should provide the toggle that JS has for commit keystroke options.

**Comment by jseanxu** [comment] 2015-01-14 00:53
>In any case we should provide the toggle that JS has for commit keystroke options.
For those of us who have been waiting for this feature, couldn't this flag just have been added to the VS editor options without affecting the default while you figure out internally what the correct default behavior is? It sounds like it is absolutely trivial to enable this behind a flag, yet it doesn't exist and devolves the IDE experience for those of us coming from C#. If anything, this would allow the community to experience and contribute on how to evolve this IDE feature.

**Comment by Peter-Juhasz** [comment] 2015-01-14 08:08
+1, I would rather dismiss the completion session a few times by Esc than having to press Enter every time I type a word.

**Comment by danquirk** [comment] 2015-01-16 20:12
You can try TypeScript 1.4 in this release if you want to try the new completion behavior http://blogs.msdn.com/b/visualstudio/archive/2015/01/16/visual-studio-2015-cpt-5-now-available.aspx

**Comment by Peter-Juhasz** [comment] 2015-01-16 21:12
Thank you, it is way better now! I really appreciate it.

**Comment by danquirk** [comment] 2015-01-16 21:26
Great, do let us know of any cases you find annoying with it. I know you're fine hitting Esc periodically but our goal is for you to rarely (if ever) have to dismiss a completion list due to bad suggestions so do let us know if you run into any bad behavior with it.

**Comment by mhegazy** [comment] 2015-01-19 22:03
@paulvanbrenk this looks related to #1629 that is already on your plate.

**Comment by paulvanbrenk** [comment] 2015-02-05 20:26
As @danquirk note above: 
>Previously TS in VS only commit completions on tab and enter so there was no need for an option to toggle what keystrokes commit completions. The intention was to move to the C# style behavior where space and punctuation characters also commit completion lists. This behavior was turned on recently but has some unfavorable interactions with certain completion list scenarios (see #1629). I want to make sure we clean up some of these experiences or else the new completion commit characters can be more annoying than helpful in a lot of cases. In any case we should provide the toggle that JS has for commit keystroke options.

This is now checked in, we're using a new feature in the completionlists in vs 2015, which allows you enter a new identifier, but also allows for the C# style commit characters when there is no disambiguity.

**Comment by danquirk** [comment] 2015-02-06 00:40
To be clear, the actual request here is not fixed, there is no UI to change completion commit characters at the moment. We have inherited this behavior from Roslyn (ie C# in VS2015 also has no UI for this even though they did in VS2013), I've asked them whether the intention is to bring back this UI or not. The fix Paul describes is one that should make the overall completion experience significantly better, hopefully to such a degree that you don't need to change the completion commit characters. That said, I get that there's a certain amount of muscle memory and preference involved in configuration of this sort, so we're still open to adding in an option if necessary but it's not as simple to add as it once was.

**Comment by Pilchie** [comment] 2015-02-09 21:33
Roslyn is NOT currently planning on bringing back the options to control individual commit characters.  Looking at the telemetry we put in place back in VS2005, we can see evidence of anyone ever actually changing that list, so we don't feel it's necessary.  If TS wants to offer it, we can make sure the APIs support it, but we don't plan to add it for C# (or VB).

**Comment by Peter-Juhasz** [comment] 2015-02-09 21:48
Personally, I am completely happy with the current solution and I do not want to change the commit characters or keys. I think the point of this request was that you always had to press Enter to commit the selected completion which was exceptionally annoying - but it has been finally fixed.

**Comment by jseanxu** [comment] 2015-03-22 09:52
Just installed CTP6 and this feature is gone again... was this deliberate?

**Comment by danquirk** [comment] 2015-03-24 02:32
By 'this feature' do you mean the checkbox to toggle "Only use tab or enter to commit"? Because yeah, that never existed in the first place. I meant to re-open this when I added the Suggestion label back in February... my bad. As far as the actual completion behavior, it appears correct to me in CTP6.

**Comment by DanielRosenwasser** [comment] 2015-03-24 04:52
Hey guys, for the record, I started working on this today.

**Comment by jseanxu** [comment] 2015-03-24 19:15
>As far as the actual completion behavior, it appears correct to me in CTP6.

Sorry, I was not referring to the checkbox toggle but on how completion works.

Typing `document.bo` followed by a period again yields `document.bo.` instead of `document.body.`

**Comment by danquirk** [comment] 2015-03-24 20:19
Ah, yeah, you're right, I just quickly checked some fat arrow completion. It is working on some newer internal builds but I've logged #2482 to make sure we verify that it's definitely working correctly in what will be shipped next.

**Comment by csicky** [comment] 2016-07-14 06:39
Hi all, this just came back. VS 2015 update 3 removed the autocomplete on period character. Now I have to use tab or enter again. Before this update it was working OK.

VS 14.0.25422.01 Update 3
TypeScript 1.8.35.0

**Comment by Peter-Juhasz** [comment] 2016-07-14 06:47
I have already opened a new issue on this one #9424 (for version 1.8.34) but it looks like they don't really understand what the problem is...

**Comment by paulvanbrenk** [comment] 2016-07-14 18:17
@csicky This will be fixed in 2.0. autocompletion on most characters... the original issue this bug was created for (i.e. give the user the option to disable that, will be in VS "15")

**Comment by RyanCavanaugh** [comment] 2020-07-21 18:31
Given the lack of recent noise here, I'm going to assume (instead of installing an old version of VS) that this has been fixed.

**Closed by RyanCavanaugh** 2020-07-21 18:31 UTC
Labels: Suggestion, Visual Studio
