### ISSUE TITLE
Mixins documentation is out of date in the handbook

### ISSUE THREAD

**Issue by Taytay** [microsoft/TypeScript#17126] opened 2017-07-12 15:58 UTC
I don't know if this is where documentation bugs are filed, but the Mixins section of the Handbook (https://www.typescriptlang.org/docs/handbook/mixins.html) appears to be incomplete now that enhanced Mixin support of 2.2 is out: 
https://github.com/Microsoft/TypeScript/pull/13743

If there's a better place for this, please just say the word!

**Comment by DanielRosenwasser** [comment] 2017-07-12 16:22
I'd say this is a duplicate of https://github.com/Microsoft/TypeScript-Handbook/issues/574, but I'll keep it open on this side as well.

**Comment by Taytay** [comment] 2017-07-12 21:24
Thanks @DanielRosenwasser! I'll file over there next time around :)

**Comment by RyanCavanaugh** [comment] 2021-12-15 21:58
Handbook has since been rewritten

**Closed by RyanCavanaugh** 2021-12-15 21:58 UTC
Labels: Docs
