### ISSUE TITLE
printer.printNode stripping text within html tags

### ISSUE THREAD

**Issue by yulric** [microsoft/TypeScript#27216] opened 2018-09-19 15:29 UTC
**TypeScript Version:**  3.0.3

**Search Terms:**
printNode JSX
printNode not printing JSX text

**Code**

```ts
const html = '<div>Text within a node</div>';
const jsxAst = ts.createSourceFile(
    'test-file.tsx',
    html,
    ts.ScriptTarget.Latest,
    false,
    ts.ScriptKind.TSX,
);
const printer = ts.createPrinter({
    newLine: ts.NewLineKind.LineFeed,
});
const result = printer.printNode(ts.EmitHint.Unspecified, jsxAst, jsxAst);
```

**Expected behavior:**
Value of the result variable should be the same as the html variable

**Actual behavior:**
result variable is &lt;div>&lt;/div>

**Comment by rbuckton** [comment] 2019-05-09 00:01
I cannot reproduce this. I tried adding the following test case to `src\testRunner\unittests\printer.ts` and got the expected result:

```ts
printsCorrectly("JsxText", {}, printer => {
    const html = '<div>Text within a node</div>';
    const jsxAst = ts.createSourceFile(
        'test-file.tsx',
        html,
        ts.ScriptTarget.Latest,
        false,
        ts.ScriptKind.TSX,
    );
    return printer.printNode(ts.EmitHint.Unspecified, jsxAst, jsxAst);
});
```

It is possible there was an error with either parent pointers or setting the `.text` property of a JsxText node that has been subsequently fixed.

**Comment by rbuckton** [comment] 2019-05-09 00:04
It looks like this was fixed by https://github.com/Microsoft/TypeScript/pull/29439.

**Closed by rbuckton** 2019-05-09 00:04 UTC
Labels: Bug
