### ISSUE TITLE
Abstract function doesn't require implementation to support all parts of union

### ISSUE THREAD

**Issue by kwasimensah** [microsoft/TypeScript#54924] opened 2023-07-07 22:33 UTC
# Bug Report

### 🔎 Search Terms

abstract function parameter union

### 🕗 Version & Regression Information

4.9.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/IYIwzgLgTsDGEAJYBthjAgYge2wg3gFAIkKiQzwIAm2AytgLYCmEAFgJYB2A5gBQAPAFwIK3HgB8EXAK6MQzKAEoRAN2wdqAbkIBfQoRRoMObAGFsXWFFbMEzARGZdqJ3AWKka9Jq069BETFeFQR1TQ8vL1hLMGxkZgA6ZGx+AWTnHnYlHSj9fUNYxGEsdwBeaWYAd1LzS2tbPhzCdNoGFnZxPgBWHKA)

### 💻 Code

```ts
abstract class Foo {
    abstract doSomething(x: string| number): void;
}

class FooConcrete extends Foo {
    // I'd expect the compiler to complain that this doesn't handle a number input
     doSomething(x: string): void {
        console.log(x.length);
     }
}

const x: Foo = new FooConcrete();
// prints undefined instead of being a compile time error
x.doSomething(5);
```

### 🙁 Actual behavior

prints undefined instead of being a compile time error

### 🙂 Expected behavior

The compiler complains that the concrete implementation doesn't handle the number case.

**Comment by fatcerberus** [comment] 2023-07-07 22:57
Duplicate of https://github.com/microsoft/TypeScript/issues/54909.  Refer to https://github.com/microsoft/TypeScript/issues/54909#issuecomment-1625616159

**Comment by kwasimensah** [comment] 2023-07-08 03:42
Weirdly, it looks like I got the behavior I wanted by having the abstract class declare a member variable that points to a function instead of using a method

https://www.typescriptlang.org/play?#code/IYIwzgLgTsDGEAJYBthjAgYge2wg3gFAIkIAOAriMgJawKiQzwJQCmwAJtgHbICeCbgGVsAWzYQAFjR4BzAFwIAFAA8lTWXIA+CHhTEg2UAJQBeAHwIAbthqcA3IQC+hQijQYc2AMK9Y7BBsCGyqQTycXrgExKRC2KIS0lpqGtBaJkq29jFxcbC8YNjIbAB0yNhyauVs8tImTnmuru6FiOpY0WZ6bADunb7+gWzKDYSqpSLikjLyygCsDUA

**Comment by kwasimensah** [comment] 2023-07-08 03:45
It looks like you can work around the method/constructor exceptions mentioned in https://github.com/microsoft/TypeScript/issues/54909#issuecomment-1625616159 by using variables that point to functions

**Comment by kwasimensah** [comment] 2023-07-08 13:13
Even more interesting is that if I make Foo an interface, it errors the way I would expect in FooConcrete even if FooConcrete is a method and not an instance variable

```ts
interface Foo {
    readonly doSomething: (x: string| number)=> void;
}

class FooConcrete implements Foo{
    // this errors now
     public  doSomething(x: string): void{
        console.log(x.length);
     }
}

const x: Foo = new FooConcrete();
x.doSomething(5);
```

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHJQRwAm6IANgJ7LkDK6AthGABagDmAXMgBQAPXgGcwULgB9kIAK5MARtACUAXgB8yAG7pgpANy4AvrlwJKcYcLSYAwhQTFIyYEwAOlCC3BWM6PIWQAekDkdmAraCh0KCsQdAB3fADXGXlKYAQCBmZWDhBOQRExLiVebV1-AMIECmF0DwA6SnQCgSaIfPYlAyrjY1NasGQhaywVaQh40bsQB1YIPm7cNuyWMPy+AFZuoA

**Closed** 2023-07-13 01:34 UTC
Labels: Question
