### ISSUE TITLE
Inconsistent and wrong quick info of variable type when strickNullChecks is on

### ISSUE THREAD

**Issue by aztack** [microsoft/TypeScript#45317] opened 2021-08-04 02:47 UTC
# Bug Report

[Type Widening](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#type-widening) says `let z = null` wil not be widen to any if `strictNullChckes` is on, but:

```ts
// strictNullChecks=true;
let z = null; // hover on z shows 'let z: any' <-- ❓🤔
type A = typeof z; // hover on A shows 'type A = null'; hover on z shows 'let z: null' ✅
```
[Playground (turn on strictNullCheck)](https://www.typescriptlang.org/play?#code/DYUwLgBAXhC8EDsCuxgG4BQYCeAHEEAgnBDvgPYBm0aQA)

```ts
// strictNullChecks=false;
let z = null; // hover on z shows 'let z: any' ✅
type A = typeof z; // hover on A shows 'type A = any'; hover on z shows 'let z: any'<--- ✅
```
[Playground (turn off strictNullCheck)](https://www.typescriptlang.org/play?strictNullChecks=false#code/DYUwLgBAXhC8EDsCuxgG4BQYCeAHEEAgnBDvgPYBm0aQA)

### 🔎 Search Terms

type widening quick info strickNullChecks 

### 🕗 Version & Regression Information

TypeScript v4.3.5

### 🙁 Actual behavior

Quick info of z in `let z = null` is `let z: any` when `strickNullChecks: true`

### 🙂 Expected behavior

Quick info of z in `let z = null` should be `let z: null` when `strickNullChecks: true`

**Comment by jcalz** [comment] 2021-08-04 03:33
I think this is all working as intended, but: **it is curious that the ["type widening" section of the TS2.0 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#type-widening) seems to be incorrect or misleading; `let z = null` does indeed infer `any` for the type of `z`.  According to #21015 that's what's supposed to happen... but why do the release notes seem to say otherwise?**

Anyway, with `--strictNullChecks` enabled, the `any` is [narrowed](https://www.typescriptlang.org/docs/handbook/2/narrowing.html) to `null` via control flow analysis (#8010) upon the assignment.  The `typeof` behavior is the same you get with any bit of control-flow-based type narrowing:

```ts
let a: string | number;
type A1 = typeof a; // string | number
a = "hello";
type A2 = typeof a; // string
a.toUpperCase();
a = 123;
type A3 = typeof a; // number
a.toFixed();
```
[Playground](https://tsplay.dev/Nd4rYN)

With `--strictNullChecks` disabled, there is no `null` type to narrow to; the type of `null` is just `any`.  So the assignment doesn't do any control-flow narrowing.

**Comment by fatcerberus** [comment] 2021-08-04 03:52
It doesn't actually infer `any`; at least not in the same way that `let x = 123;` infers `number`.  TS rather seems to consider it to be an evolving type:

```ts
let x = null;
let y = 123;
x;  // ok - x is typed as null
y;  // also ok - y is typed as number
function foo() {
    x;  // error - implicit 'any'
    y;  // still good - y is number
}
```

[Playground Link](https://www.typescriptlang.org/play?#code/DYUwLgBAHhC8EDsCuxgG4BQpIE84QEYAmAZkyjQggHpqIB7AawgFpoIBLAZwjBwAcQAEwgBDHslQYclGnVHAu9BszZ5uvAcLESkAWwBGIAE4YAZkgQBjMB3oIIZ+vQAUASggBvDFSoUqtBAmxvTGrJx6-MAcVhyQAOSiCDjxPr4yAXRctqgQAObOImqcuoYmGAC+GEA)

**Comment by fatcerberus** [comment] 2021-08-04 03:56
If I had to guess, I would imagine the rationale is that, if you're initializing a variable to `null`, you probably plan to assign something meaningful to it later, so the compiler treats it as uninitialized.

**Comment by ahejlsberg** [comment] 2021-08-04 07:44
This is working as intended. See #11263.

**Comment by ahejlsberg** [comment] 2021-08-04 07:52
Regarding the type shown in quick info, when you hover over an auto-typed variable in a declaration or assignment position we'll show `any` (because anything can be assigned to it). However, when you hover in an expression position, we'll show the type determined by control flow analysis at that particular position.

**Closed** 2021-08-04 08:25 UTC
Labels: Working as Intended

**Comment by jcalz** [comment] 2021-08-04 14:55
I guess the [documentation](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#type-widening) was correct for TS2.0 but became incorrect when TS2.1 [introduced](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#improved-any-inference) auto-typed variables in [microsoft/TypeScript#11263](https://github.com/microsoft/TypeScript/pull/11263)
