### ISSUE TITLE
React import removed on organize imports using "react-jsx", in v1.68.0

### ISSUE THREAD

**Issue by mosesoak** [microsoft/TypeScript#49486] opened 2022-06-10 21:39 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.0
- OS Version: Windows_NT x64 10.0.19044

### Steps to Reproduce:

1. Set `"jsx": "react-jsx"` in tsconfig.json (this is required for use of `jsxImportSource`, which we need to have set to `"@emotion/react"` for our css frameworks)
2. `import React from 'react';` in a `.tsx` file that declares a functional component
3. Run the `Organize Imports` command

### Expected:
`React` import remains, as it is required in tsx files. This worked in the previous version of VS Code.

### Actual: 
`React` import is removed, unless tsconfig is set to `"jsx": "react"`, which is incompatible with `jsxImportSource`.

This only began happening in the latest drop, 1.68.0

Similar past issue: https://github.com/microsoft/vscode/issues/47287

**Comment by yume-chan** [comment] 2022-06-11 23:32
`react-jsx` mode doesn't need `import React`:

> With the new transform, you can **use JSX without importing React**. 
>
> _https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html_

**Comment by andrewbranch** [comment] 2022-06-13 21:12
@yume-chan is correct. This is working as intended.

**Comment by mosesoak** [comment] 2022-06-14 23:19
@yume-chan @andrewbranch Whoa hold up, this can't be right. This is a functional change in VS Code that is causing our team huge headaches because one of our standard settings is organize-imports-on-save.

There needs to be some way to prevent the React import from being eaten every time we save, it makes it impractical to use the (excellent) organize-imports feature, which we want to be able to continue using.

Can someone please reopen this for discussion?

**Comment by andrewbranch** [comment] 2022-06-15 00:53
The reason people used to import `React` in JSX files while apparently not using it is that JSX elements got transformed to `React.createElement` calls by a later build step, so we all had to pretend that `React` was actually being used, since it would be later. But with the options you’ve specified, an import gets automatically added from `@emotion/react/jsx-runtime` and JSX elements get transformed into a call of the factory imported from there. So `React` is no longer being used, so it’s removed like any other unused import. In other words, your expected behavior was wrong:

> `React` import remains, as it is required in tsx files.

It is not required. Perhaps you have an ESLint rule enabled which is giving you bad advice?

**Comment by yume-chan** [comment] 2022-06-15 02:23
I remember seeing `import React` marked as unused as early as TypeScript 4.1, but I forgot whether VS Code before 1.68 will remove them when organizing imports.

Is it an undocumented change in VS Code 1.68 (TypeScript 4.7)?

**Comment by YaYaPao** [comment] 2022-06-15 06:49
Same issue troubles me. When i saved, vscode will auto delete my imports, even some of it is used.
MacOS: 12.3.1 
VSCode: 1.68.0
Typescript: 4.5.0

**Closed** 2022-06-18 20:00 UTC
Labels: Working as Intended

**Comment by mosesoak** [comment] 2022-06-22 18:47
@andrewbranch You're right, we missed that React 17 outdated that import.

For anyone else that missed that memo (especially those using `"jsx": "react-jsx",` in tsconfig) all you need to do is add:

`'plugin:react/jsx-runtime',`

to the `extends:` block of your eslintrc file.

Thanks for the help with this!

**Comment by Bobobobobo12456** [comment] 2022-06-22 18:52
How to get mod menu working properly please

**Comment by rickvian** [comment] 2022-07-18 09:22
Hi, we are using Next.js and `organize import` lately it keeps omitting `import React from 'react'`

we cannot change the next ts configuration to "jsx":"react" as it is always replacing to "jsx" : "preserve"

![Screen Shot 2022-07-18 at 16 19 39](https://user-images.githubusercontent.com/8034141/179481656-a6a211ac-d592-48c4-9f19-9e9835c977ea.jpg)

https://github.com/vercel/next.js/discussions/19155

any suggestion?

**Comment by roypearce** [comment] 2022-08-02 20:50
> Hi, we are using Next.js and `organize import` lately it keeps omitting `import React from 'react'`
> 
> we cannot change the next ts configuration to "jsx":"react" as it is always replacing to "jsx" : "preserve"
> 
> ![Screen Shot 2022-07-18 at 16 19 39](https://user-images.githubusercontent.com/8034141/179481656-a6a211ac-d592-48c4-9f19-9e9835c977ea.jpg)
> 
> [vercel/next.js#19155](https://github.com/vercel/next.js/discussions/19155)
> 
> any suggestion?

This isn't just a nextjs issue, there are other frameworks and packages which rely on `"jsx": "preserve"`, and that requires maintaining the `React` import. I suggest opening a new bug.

**Comment by nx-kevinbischof** [comment] 2023-10-25 08:43
> @andrewbranch You're right, we missed that React 17 outdated that import.
> 
> For anyone else that missed that memo (especially those using `"jsx": "react-jsx",` in tsconfig) all you need to do is add:
> 
> `'plugin:react/jsx-runtime',`
> 
> to the `extends:` block of your eslintrc file.
> 
> Thanks for the help with this!

Adding `'plugin:react/jsx-runtime'` to the eslintrc file produces an error instead of avoiding to remove React from the imports.
![image](https://github.com/microsoft/TypeScript/assets/108737947/1aaf9334-286f-4588-b647-97f990a3bdc0)

**Comment by sagorzaii** [comment] 2024-03-12 03:03
> > Hi, we are using Next.js and `organize import` lately it keeps omitting `import React from 'react'`
> > we cannot change the next ts configuration to "jsx":"react" as it is always replacing to "jsx" : "preserve"
> > ![Screen Shot 2022-07-18 at 16 19 39](https://user-images.githubusercontent.com/8034141/179481656-a6a211ac-d592-48c4-9f19-9e9835c977ea.jpg)
> > [vercel/next.js#19155](https://github.com/vercel/next.js/discussions/19155)
> > any suggestion?
> 
> This isn't just a nextjs issue, there are other frameworks and packages which rely on `"jsx": "preserve"`, and that requires maintaining the `React` import. I suggest opening a new bug.

Hello. Does anyone has any updates on this? It's removing my react imports and causing error in my app.

**Comment by rickvian** [comment] 2024-03-16 11:05
i have do workaround by not using default organize import, as it messed up my workflow, i use import sorter extension instead 
https://marketplace.visualstudio.com/items?itemName=mike-co.import-sorter
