### ISSUE TITLE
narrowing generics to a value doesn't work

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#45209] opened 2021-07-27 21:52 UTC
# Bug Report

### 🔎 Search Terms

narrowing generics

### 🕗 Version & Regression Information

4.4.0-dev.20210727

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210727#code/GYVwdgxgLglg9mABMOcA8AVRBTAHlbMAEwGdEwQBbAI2wCcA+ACgDcBDAGxGwC5EMAlIgDeAKEQTEMYIladuiALzLEABiFjJWxOy7YlKgEwBGRAHozYODjp04dRLQhsQJfVACeAB30wSYAHIocjZbOAB3bCJxSQBfUXjRUEhYBEdQuT0+Chp6DRiJaVldBWVFNXztSRL9MsQTczN+AAs-RAgEIhhUpHCYDg5ETnC2DzI6bCgQOiQA4E43AMQSGEh3ZvdvbDIA1SW2YkQAkyXmthZ9K0Q4C7oONi8AOiZDAGYANgB2AQLEeNigA)

### 💻 Code

```ts
function foo<T extends number>(value: T) {
    if (value === 0) {
        value === 21 //no error because type isn't narrowed
    }
}

function bar(value: number) {
    if (value === 0) {
        value === 21 // This condition will always return 'false' since the types '0' and '21' have no overlap.(2367)
    }
}
```

### 🙁 Actual behavior

no error

### 🙂 Expected behavior

`This condition will always return 'false' since the types '0' and '21' have no overlap.(2367)`

**Comment by eczn** [comment] 2021-07-29 07:30
is it necessary to use generics ?

``` ts
function foo(value: unknown) {
    if (value === 0) {
        value === 21 //no error because type isn't narrowed
    }
}
```

**Comment by DetachHead** [comment] 2021-07-29 09:39
obviously not in that example, it's just a minified version of the issue. say i wanted to return the value or something, now it needs a generic
```ts
function foo<T extends number>(value: T): T {
    if (value === 0) {
        value === 21 // no error
    }
    return value
}
```

**Comment by andrewbranch** [comment] 2021-08-05 00:28
Duplicate of https://github.com/microsoft/TypeScript/issues/41333 and probably more: https://github.com/microsoft/TypeScript/issues?q=is%3Aissue+generic+narrowing+label%3A%22Design+Limitation%22+is%3Aclosed

**Closed** 2021-08-07 18:00 UTC
Labels: Duplicate
