### ISSUE TITLE
Spread operator in method shorthand in object literal is not emitted with "__assign" 

### ISSUE THREAD

**Issue by kobiburnley** [Microsoft/TypeScript#17087] opened 2017-07-11 07:32 UTC
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

[Link to playground](https://www.typescriptlang.org/play/#src=const%20y%20%3D%20%7B%0D%0A%20%20prop%3A%20%22ms%22%0D%0A%7D%0D%0Aconst%20x%20%3D%20%7B%0D%0A%20%20...y%2C%0D%0A%20%20fn(options)%20%7B%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20timestamps%3A%20false%2C%0D%0A%20%20%20%20%20%20...options%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%0D%0A%7D)

**Code**

```ts
const y = {
  prop: "ms"
}

const x = {
  ...y,
  fn(options) {
    return {
      timestamps: false,
      ...options
    }
  }
}
```

Emits to: 
```
var __assign = (this && this.__assign) || Object.assign || function(t) {
    for (var s, i = 1, n = arguments.length; i < n; i++) {
        s = arguments[i];
        for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
            t[p] = s[p];
    }
    return t;
};
var y = {
    prop: "ms"
};
var x = __assign({}, y, { fn: function (options) {
        return {
            timestamps: false,
            ...options
        };
    } });
```

**Expected behavior:**
"...options" will be emitted with "__assign"
**Actual behavior:**
"...options" is not emitted with "__assign"

**Comment by aminpaks** [comment] 2017-07-11 10:35
I think it's supposed to be:
```ts
const y = {
  prop: "ms"
}

const x = {
  ...y,
  ...fn(options) {
    return {
      timestamps: false,
      ...options
    }
  }
}
```

**Comment by kobiburnley** [comment] 2017-07-11 11:18
The issue happens when using method shorthand in object literal

**Comment by aluanhaddad** [comment] 2017-07-26 14:07
This seems to fail when their is a spread in the containing literal.

This works
```ts
const x = {
  fn() {
    return {
      ...{}
    };
  }
}
```
and this fails
```ts
const x = {
  ...{},
  fn() {
    return {
      ...{}
    };
  }
}
```

**Comment by aluanhaddad** [comment] 2017-07-26 14:51
I just realized this is a dupe of #16765

**Comment by mhegazy** [comment] 2017-09-12 19:55
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-12 19:55 UTC
Labels: Duplicate
