### ISSUE TITLE
Enhance type predicates / Enhancing typescripts ability to handle state

### ISSUE THREAD

**Issue by TrevTheDev** [microsoft/TypeScript#50136] opened 2022-08-02 04:13 UTC
# Suggestion
Provide a way to tell the Typescript Compiler that an object's state has changed - enabling Typescript to model state, and state machines well.

## 🔍 Search Terms

state

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

One solution could be to enhance type predicates to include syntax for instructing the compiler the new type of a variable and all variables sharing its reference after that call, become the new type.
E.g.
```typescript
const fooBar : Foo|Bar = { ...
   set changeStateToFoo(value:string): fooBar is Foo { ... }
} as Bar
const otherRefToFooBar : Foo|Bar= fooBar  // type is `Bar`
fooBar.changeStateToFoo = 'hello' // after this call fooBar is now type `Foo` otherRefToFooBar  is now also type `Foo`
```

This is similar to manual reassignment,  but would produce more readable and understandable code.  A downside is that this could unintuitively mutate the type of a variable causing the code to be harder to reason about- but as it would produce better code than is currently the case, this remains a better solution what is currently available in Typescript.

## 📃 Motivating Example

The ability to manual change a variable or this type, would significant enhance Typescript's ability to model state and state machines.

Despite this being a fairly typical use case, Typescript current doesn't handle the following code well:
```typescript
type Bar = {
    type: 'bar'
    changeStateToFoo: string
}
type Foo = {
    type: 'foo'
    sayHello: ()=>void
}

let fooBar = ():Bar=>{
    return {
    type: 'bar',
    set changeStateToFoo(value:string) { 
        delete (fooBar as any).changeStateToFoo;
        (fooBar as unknown as Foo).type = 'foo'; 
        (fooBar as unknown as Foo).sayHello = ()=>console.log(value)
        //fooBar should now change to type `Foo`
        }
    }
}
const fooBarA = fooBar()

fooBarA.changeStateToFoo = 'Hello, Foo' // after this setter, fooBarA should be type `Foo`
fooBarA.sayHello()
```

Implementing this code in typescript would likely require one of the follow sub optimal solutions:
```typescript
/**
 * Workaround One: Type Union
 * Con: types become a fuzzy merge of multiple types addressing multiple concerns. Causing incorrect type checking in some cases
 * and requiring superfulous if(exists) checks in other cases. 
 */
type FooBar = {
    type: 'foo'|'bar'
    sayHello?: ()=>void
    changeStateToFoo?: string
}

let fooBarB = fooBar() as FooBar

fooBarB.changeStateToFoo = 'Hello, Foo'
if(fooBarB.sayHello) fooBarB.sayHello() // con: if required!
fooBarB.changeStateToFoo = 'Hello, Bar' // con: still valid - oops! 
```

or

```typescript
/**
 * Workaround Two: Manual Reassignment
 * Con: requires arbitrary reassignment and requires writer of this code to know
 *      and manually assign the correct type which may be hard to know or complex.
 */
let fooBarC: Foo|Bar = fooBar()

fooBarC.changeStateToFoo = 'Hello, Foo'
fooBarC = (fooBarC as unknown as Foo) // con: requires superfluous reassignment and requires writer of this code to know
                                      // and manually assign the correct type which may be hard to know or complex for built up generic types.
fooBarC.sayHello()
fooBarB.changeStateToFoo = 'Hello, Bar' // pro: correct type checking!
```
[code](https://www.typescriptlang.org/play?#code/PQKhCgAIUglBTAjgVwJYCd4Ft4DsAuAXJABYCGAbqrgOaT4CeADvAM6RYD2AJvADaRW+MvniQAxuVptIAd358oMACokx4nmIBG-TrMi8uuIehEzZ5fJFTtMKDPG6ElwcIxaQAQmXSQAvJAA3lCQoe7wxADkWj6RIaGSZNIAysKiypwAYpycxCbUNOAAvm7MYtmc-kHx9GVRAGY5caGhrGQMABIKuZAAFACUfgB8FJyo3MXg4HzwVo2c3r4BA4SLw8EtkJj4yOi41ZvhUTHokQA0NayzElI08KlmGRW9FGR8yBH5tP1BkDWbvBmoj680WkDI7CSDH6ADpEik0vAnjkANz-Fq9UE+cHsZC4ADWuD0+whkAqsPCVUi80iKL+m02mJyYNJeMJxJxZJysLanW6VQGww0xk4MxhfE4NBebw+-XRoWAwCxvlYJE4yD43EgRP08Lu9EqlIABhUjfLICVNiUSsKhJBlQBBKrKgZTR1w273RHIyoBSJdPgSs5cziRSCK8H1US+fAkGyCWbR4OOwRqjVanS1DwmnJm928gMS13gUAQaCQADqnHQ+J86twWoA8rgIpBlGVIABVXCoTi4JSQADCfeI4XYOg0OHB9uQAC9ZwwOPB0PrOPUOBr8KgmDMszIyNxuJhWKwChu+Fud+o++Jl8YYUOyMhT7RrLgNOhMOIrJTJPBxPiZ7UIInBTuIEJsAOSRanYaDoGerDICw6D1Bq6rsKg9S9PAAAeNj4KwPx-gBGH7JwsbLhIEGsA+LilB4FRggEGwtEckDUk0AA+0SxJc7SFpwAD8xCCiMYwTJsepeo8WQ5MJgj4PBtCTNM1zKp4zrMj4AycoxPhulp6CeB6SR3A86Syb67ECcGFRxJhTILD4xkFt0PzqTCrmBpwOkRsKxCYVsSBwY4ACE4AeVJ5lIpZVI2V4sThsAEgjgpqCBpArx8OMkAALSQDkTCsKFfxTKWA5VjWdZ4lqyiyD0ACySTIG8cDwBCp40LgOAEAOw64MQsEOJC6BaKgik+IumAdagXU9VY0FBfYx5yPB0YFeusbxhovAGpA7KyAODKLVgzVvHwi4zV19BqCln7-j+HYWKgkgcO0kCZuQ6BavglQHQVviTleOEwnRQL2oZg7EBUnFMRDTnoMWyqDiZCIyRUcXdLZTQRZDArI5ybI6iS7DkklKUDUtIXsIhyGoRKz5BVd3V4AtDZU8Nq3jZRa43dtmh7Qd5oMiLoti5sEYnWdgaXSes37BRd1fo9HjPa9p2Lp9Pg-X9OoA5AuG3o42W0Bd9Lixblui35oHA9Ym23ZS8ZkClWB21oaAXpASF7qDyOefx3SupFnrRT6mPecGixhhGTDoD0H7K3uNz-oBtDhWVYADk6rCisgW59hDgN9qevCmAX-bQK44PKgAIqs2LMTUbE8acFybFcVhRd6lnSu8nyKQU-SjnGGGkzkvwKslZBRpR4GBmeW004my7BorlK80v4Ls0ayNGh9-6gTIOacGaYuArMYiOSykK4NCqNmT3FRomL1-YqyBLE7p3IwpSfo0nSc0b9fAfwOiTEMPJA7eQFIMIYtpRTwHFJKPusoajWimEAA)

## 💻 Use Cases

Any code that uses a state machine, or transitions objects between states would significantly benefit from this.

**Comment by MartinJohns** [comment] 2022-08-02 05:44
Sounds like a duplicate of #41339.

**Comment by RyanCavanaugh** [comment] 2022-08-02 16:20
This is already possible with a slightly different variation
```ts
interface FooBar {
    type: 'foo'|'bar'
    sayHello?: ()=>void
    changeStateToFoo(): asserts this is { sayHello(): void }
}

let fooBarB: FooBar = fooBar() as FooBar

fooBarB.changeStateToFoo();
fooBarB.sayHello();
```

I don't think the principle of modifying one property via a setter and causing spooky action at a distance on other properties in the object is common enough to warrant additional modelling.

**Comment by TrevTheDev** [comment] 2022-08-04 02:43
@RyanCavanaugh  Thank you for the third work around - it is a valuable addition to the two I proposed.  A key downside is that it only allows narrowing - so it doesn't allow for example an `unplacedOrder` to become a `placedOrder` or for a `placedOrder` to revert back to being an `unplacedOrder`.   I.e. it also doesn't model state well.

I don't agree with your characterisation of property setters as "causing spooky action at a distance on other properties" being not common.  Its kinda the point of setters that setting them changes the object and typescript should model that.

**Closed** 2022-08-06 18:00 UTC
Labels: Duplicate
