### ISSUE TITLE
Parentheses in typeof expression break narrowing

### ISSUE THREAD

**Issue by crisbeto** [microsoft/TypeScript#60784] opened 2024-12-17 10:58 UTC
### 🔎 Search Terms

- type narrowing
- typeof expression

### 🕗 Version & Regression Information

- This changed between versions 3.3 and 5.7
- This changed in commit or PR: unclear

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.2#code/DYUwLgBAbghsCuIIF4IEYBMBmCMDOEeYATgJYB2A5hAD4TnwC2ARiMQNwBQnA9DxAHUA9sQDWeTqQBmEABRgAngAcQQmbARJk2iAHIGLNroCUEAN6cIEAMZDyeIaAB0wIZVkbEEAFQQMxrgBfbj4IABEhEAJyIUgAdxFRSRlZeWVVdThEU21UfSZWYhNzSxs7B2dXd08kX38gkP4IqPpYiASxZLlFFTVoLK0dWXzDIuNTCytbe0cQFzcPAZ8-AM5g3ibI6LaOpOk5NN7MzRyhkcKTCdLpirmqxc1l+rWgA

### 💻 Code

```ts
let value = 123 as string | number;

// Works
if (typeof value === 'number') {
  console.log(value * 2);
}

// Does not work
if ((typeof value) === 'number') {
  console.log(value * 2);
}

// Does not work
if (typeof value === ('number')) {
  console.log(value * 2);
}

// Does not work
if ((typeof value) === ('number')) {
  console.log(value * 2);
}
```

### 🙁 Actual behavior

As soon as parentheses are added around the `typeof` expression or the value it's being compared against, narrowing no longer works.

### 🙂 Expected behavior

Narrowing shouldn't be affected by parentheses.

**Comment by MartinJohns** [comment] 2024-12-17 11:24
Duplicate of #42203.

**Closed** 2024-12-20 01:32 UTC
Labels: Duplicate
