### ISSUE TITLE
Nested if statement invalidates type guards

### ISSUE THREAD

**Issue by kujon** [microsoft/TypeScript#20504] opened 2017-12-06 16:43 UTC
**TypeScript Version:**  2.6.2

**Code**

```ts
type A = {
    id?: string;
    type: 'bar'
};

type B = {
    id?: string;
    type: 'foo';
};

type C = A | B;

const logId = (id: string) => console.log('id', id);

const doSomething = (value: C) => {
    if (value.id) {

        logId(value.id); // This is fine 

        if (value.type === 'foo') { 
            logId(value.id); // Type 'undefined' is not assignable to type 'string'.
        }
    }
};
```

The above would work just fine, if C was defined as:

```ts
type C = {
    id?: string;
    type: 'foo' | 'bar';
};
```

**Expected behavior:**

The example above compiles.

**Actual behavior:**

The type guard checks are invalidated.

**Comment by kujon** [comment] 2017-12-06 16:45
It turns out it doesn't depend on nesting, but on which expression gets evaluated first:

```ts
type A = {
    id?: string;
    type: 'bar'
};

type B = {
    id?: string;
    type: 'foo';
};

type C = A | B;

const logId = (id: string) => console.log('id', id);

const doSomething = (value: C) => {
    if (value.id && value.type === 'foo') { 
        logId(value.id); // Type 'undefined' is not assignable to type 'string'.
    }

    if (value.type === 'foo' && value.id) { 
        logId(value.id); // This is fine.
    }
};
```

**Comment by bobmoff** [comment] 2018-01-02 09:11
I am having a similar issue. Typescript believes that the p.faces property could be undefined, even though I have guarded against it at the top.

![image 2018-01-02 at 10 03 56 am](https://user-images.githubusercontent.com/1033236/34479078-dcecd9f2-efa4-11e7-8ee6-eb311758f23e.png)

The guard at the top doesnt affect the code below inside the nested if statements. The only way to get rid of the issue is to put a guard inside each of the nested if statements.

**Comment by Kovensky** [comment] 2018-01-02 10:10
The problem there is not that it's nested, it's that it's in a closure that is not immediately invoked.

TypeScript doesn't know it'll only ever be called synchronously so it has to discard the refinements, as other code could reassign the values you just checked in the meantime.

**Comment by bobmoff** [comment] 2018-01-02 11:22
Thx @Kovensky

**Comment by RyanCavanaugh** [comment] 2021-06-23 23:17
This works now.

**Closed by RyanCavanaugh** 2021-06-23 23:17 UTC
Labels: In Discussion, Suggestion
