### ISSUE TITLE
Error: Debug Failure. False expression: `JsxText` tokens should not be the first child of `JsxElement | JsxSelfClosingElement` in 'findRightmostChildNodeWithTokens' during 'quickinfo'

### ISSUE THREAD

**Issue by aozgaa** [microsoft/TypeScript#21815] opened 2018-02-09 01:19 UTC
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.1
**VSCode Version** 1.19.0
**command requested**: quickinfo
**hitting sessions**: 494
**proportion of all sessions**: 0.0018441574925431082
**five line hash**: aa0b19994104f0573fb850c0e70e08e6
**stack**
```
Error: Debug Failure. False expression: `JsxText` tokens should not be the first child of `JsxElement | JsxSelfClosingElement`
    at findRightmostChildNodeWithTokens (tsserver.js:64703:30)
    at find (tsserver.js:64695:33)
    at findPrecedingToken (tsserver.js:64661:22)
    at getTokenAtPositionWorker (tsserver.js:64624:41)
    at getTouchingToken (tsserver.js:64596:16)
    at Object.getTouchingPropertyName (tsserver.js:64592:16)
    at Object.getQuickInfoAtPosition (tsserver.js:82890:27)
    at IOSession.Session.getQuickInfoWorker (tsserver.js:89819:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:88972:61)
    at unknown (tsserver.js:90393:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90384:28)
    at IOSession.Session.executeCommand (tsserver.js:90393:33)
    at IOSession.Session.onMessage (tsserver.js:90413:35)
    at Interface.<anonymous> (tsserver.js:91614:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by andy-ms** [comment] 2018-03-13 17:15
Duplicate of #20788

**Comment by RyanCavanaugh** [comment] 2020-01-27 16:38
♻

**Comment by RyanCavanaugh** [comment] 2020-07-15 22:59
We need a concrete repro for this

**Comment by DanielRosenwasser** [comment] 2022-01-14 21:56
At least one repro at #47446.

**Closed** 2022-01-19 21:37 UTC
Labels: Bug, Source: Telemetry, Fix Available
