### ISSUE TITLE
Inconsistent inference between optional parameter taking Iterable and Array

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#10238] opened 2016-08-09 22:46 UTC
Consider the following:

```ts
declare class KV_Array<K,V> {    
    constructor(entries?: [[K, V]]);
}
const mapFromArray = new KV_Array([
    ["a", 1],
    ["b", 2],
    ["c", 3],
]);
```

The above works as expected. `mapFromArray` has the type `KV_Array<string, number>`.

Now take this sample which instead makes its parameter `Iterable` instead of just an `Array`.

```ts
declare class KV_Iterable<K,V> {    
    constructor(entries?: Iterable<[K, V]>);
}
const mapFromIter = new KV_Iterable([
    ["a", 1],
    ["b", 2],
    ["c", 3],
]);
```

This actually *doesn't* work!

Note that if you make the parameter non-optional in `KV_Iterable`, you will get the desirable result.

**Comment by weswigham** [comment] 2016-08-11 19:56
I can't seem to reproduce this on master, is there more to this issue than the above code and `target: "es2015"`? Also, what's the exact error we give (because I'm not seeing any)?

**Comment by mhegazy** [comment] 2016-09-22 05:00
I do not see it either. closing for now. please reopen if there is more to it than that.

**Closed by mhegazy** 2016-09-22 05:00 UTC
Labels: Bug
