### ISSUE TITLE
ES6 module filename improvement

### ISSUE THREAD

**Issue by danielsedlacek** [Microsoft/TypeScript#27299] opened 2018-09-24 09:00 UTC
## Search Terms

import, module

## Suggestion

When using the import declaration from the documentation

import { ZipCodeValidator } from "./ZipCodeValidator";

the latest Chrome will not find the 'ZipCodeValidator' file. The console will show an error "Failed to load resource: the server responded with a status of 404 (Not Found)".

This can be easily fixed by adding the ".js" suffix to the imported module.

import { ZipCodeValidator } from "./ZipCodeValidator.js";

On one hand, this is a documentation issue (the documentation does not follow implementation), on the other hand, it would be nice if the compiler generated the ".js" automatically. 

Please see https://github.com/Microsoft/TypeScript/issues/27287

## Use Cases

TS script:
import { ZipCodeValidator } from "./ZipCodeValidator"; 

Generated ES6:
import { ZipCodeValidator } from "./ZipCodeValidator"; 

This is invalid and will not work. 

## Examples

TS script:
import { ZipCodeValidator } from "./ZipCodeValidator"; 

Generated ES6:
import { ZipCodeValidator } from "./ZipCodeValidator.js"; 

The compiler will add the ".js" to the module filename. 

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment] 2018-09-24 15:08
Duplicate of #16577

**Closed** 2018-12-14 18:00 UTC
Labels: Duplicate
