### ISSUE TITLE
Suggestion: Add compile flag: StrictNumberBooleanChecks

### ISSUE THREAD

**Issue by bertyhell** [Microsoft/TypeScript#21993] opened 2018-02-16 13:37 UTC
The compiler flag: StrictNumberBooleanChecks would show a warning (or error) when the user writes an boolean evaluation of a number variable.

**Code**

User writes the code with a possible undefined value in mind:
```ts
let myAttribute: number | undefined = undefined;
let value: number = myAttribute || 50;
console.log('value: ' + value);
```

But the value could also be 0. In which case the value will default to 50, which possibly isn't what the user intended.
```ts
let myAttribute: number | undefined = 0;
let value: number = myAttribute || 50;
console.log('value: ' + value); // value === 50, but user expected value === 0
```

Behavior when StrictNumberBooleanChecks=true
```ts
let myAttribute: number | undefined = 34;
let value: number = myAttribute || 50; // Compiler warning/error: number variable could be zero, which would evaluate to false. Possible unintended behavior?
console.log('value: ' + value);
```

To avoid this compiler warning while the flag is true:
```ts
let myAttribute: number | undefined = 34;
let value: number = typeof myAttribute === 'undefined' ? 50 : myAttribute;
console.log('value: ' + value);
```

**Playground Link:** 
https://www.typescriptlang.org/play/#src=let%20myAttribute%20%3D%20undefined%3B%0D%0Alet%20value%20%3D%20myAttribute%20%7C%7C%2050%3B%0D%0Aconsole.log('value%3A%20'%20%2B%20value)%3B%0D%0A%0D%0AmyAttribute%20%3D%2034%3B%0D%0Avalue%20%3D%20myAttribute%20%7C%7C%2050%3B%0D%0Aconsole.log('value%3A%20'%20%2B%20value)%3B%0D%0A%0D%0AmyAttribute%20%3D%200%3B%0D%0Avalue%20%3D%20myAttribute%20%7C%7C%2050%3B%0D%0Aconsole.log('value%3A%20'%20%2B%20value%20%2B%20'%20%2F%2F%20user%20expected%200%20as%20output')%3B

**Search Terms:** 
zero checks boolean value strict avoid evaluate number int

**Comment by mhegazy** [comment] 2018-02-17 01:00
falsy values is a feature of JS, not sure why i would consider these "errors". The compiler correctly identify falsy values under `--strictNullChecks`. Seems to me that this can be a tslint rule instead.

duplicate of https://github.com/Microsoft/TypeScript/issues/8178 and https://github.com/Microsoft/TypeScript/issues/7306

**Closed** 2018-02-17 08:30 UTC
Labels: Duplicate
