### ISSUE TITLE
Possibly Undefined Array References in Typescript Strict Mode

### ISSUE THREAD

**Issue by crgwbr** [Microsoft/TypeScript#29757] opened 2019-02-05 21:10 UTC
## Search Terms

- Strict Mode
- Undefined Array References

## Suggestion

While strict null checking prevents almost all instances of what could be a `TypeError`, I've found a situation where it seems to fail. The code below demonstrates it:

```typescript
interface IMyObj {
    foo: string;
}
const myArr: IMyObj[] = [];
const myObjProp = myArr[0].foo;
console.log(myObjProp);
```

Typescript will compile this without complaint, but when run it will obviously throw a type error:

```
Uncaught TypeError: Cannot read property 'foo' of undefined
```

You could catch this by defining all array types in the codebase as `(IMyObj | undefined)[]` instead of `IMyObj[]`, but that seems error prone as well since it'd be easy to miss one.

It seems like Typescript should be able to catch direct references to array members (like `myArr[0]`), and convert the type from `IMyObj` to `IMyObj | undefined`, incase that array member referenced doesn't exist.

See also: https://stackoverflow.com/questions/54542739/possibly-undefined-array-references-in-typescript-strict-mode

## Use Cases

Improve the quality of strict null checking system by finding additional issues.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by dragomirtitian** [comment] 2019-02-05 21:17
Duplicate of #10530 I believe

**Comment by ahejlsberg** [comment] 2019-02-05 22:02
Duplicate of #13778.

**Closed** 2019-02-05 23:10 UTC
Labels: Duplicate
