### ISSUE TITLE
Discriminants implicitly add `undefined` when strictNullChecks is off.

### ISSUE THREAD

**Issue by casr** [microsoft/TypeScript#46384] opened 2021-10-15 12:18 UTC
# Bug Report

TypeScript is unable to discriminate over JSDoc types.

### 🔎 Search Terms

JSDoc, discriminate type, narrow, narrowing

### 🕗 Version & Regression Information

- This is the behaviour in every version I tried, and I reviewed the FAQ for entries about discriminate types and JSDocs.

### ⏯ Playground Link

  - [JavaScript example]
  - [TypeScript equivalent]

  [JavaScript example]: https://www.typescriptlang.org/play?ts=4.4.3&filetype=js#code/PTAEAEBcGcFoGMAWBTeBrAsAKG-A9gHbSSgBOy0ArgDYkC8oAbgIbUCWAJs5MgBQBEAMzx5+ASgDc2bG0GheAQnJVaAOjxoxoAN7ZQofETzVkq5KVJ5SvZTUhmLVydgC+0rMABUniJACeAA7IOgBqrJzcVgBiBC6gnsDYgpQE8JBshEzhXDy8LNRaulj6svL5oHQMBDQFOnr6ZMiQlKQEOqAaAFyggqzQyAA0oOaWpN38ALZs0NBsBADmjQCOlGzkHFnUlMj8oC5SxXv15M2t7V2gkKTbewduOB7eej7g8KzUAEbM6KBh7DnRAjPCABZikZgTHTEUhzRYAH1AKQ4yEEc2QHDi+WB4BOLSIoWykVIACUKHZ7vFEg8vC9-EFkXJtLw-hFIFZSSpIABlSjweAUaCgBEsgEksm0KLMNhbchiOIiokcuyU9w07F09Eo36Etlizk8vkC7EBSxBUj+HRXbZxDTPKnYNXFWmBTVyBW6pUSqUy5DG03mC3aXrUfo2zBOkH+81+KFXWFxEZWO3YIA
  [TypeScript equivalent]: https://www.typescriptlang.org/play?ts=4.4.3&filetype=ts#code/MYewdgzgLgBATgUwgVwDawLwwG4ENUCWAJrlAgBQBEAZiCJQJQDcAsAFDsHUzkCEiKdADoQAawYwA3uxgxQkEKgRCEcOCDjkBaKCrUbm7AL7t21ZGGBQC4HPmKkKeVAC4Y0OATABzGAB8YCyIEai8EIgY3ADV7EigNACUkHSkZGC4eZxgMLDA0VAlpNllZRChkODApGDE3anwIBAAaGFV1ODdKAFsCCAgvX0QAR2QCRCI7VGQEShgjVmK5tLKKqska0TcoOGm5hZMONigATwAHBBgYwjjE5PRsy9jSW8EoAGVkYGAkCH9H6+ecCSrwAYrgCFNEKY2F4yHB6t9-g54kC7u9Pt8+qlFrUYNtpvtobDVAiLldkS8dGCIRULkVZLj6qhGgtZG0NG4PAN9kA

### 💻 Code

Given a JSDoc definition of:

```javascript
/** @typedef {(ValidatorResultSuccess | ValidatorResultFailure)} ValidatorResult */

/**
 * @typedef ValidatorResultSuccess
 * @property {true} ok
 */

/**
 * @typedef ValidatorResultFailure
 * @property {false} ok
 * @property {string} error
 */
```

I would expect to be able to discriminate over `ok` in a manner like:

```javascript
/** @type {ValidatorResult} */
const result = validate("foo");

if (!result.ok) {
  // TypeScript complains because it still considers `result` possibly `ValidatorResultSuccess`.
  console.error(result.error);
}
```

### 🙁 Actual behaviour

TypeScript errors on when accessing `result.error` because it considers `result` to be both `ValidatorResultSuccess` or `ValidatorResultFailure`.

### 🙂 Expected behaviour

I would expect that TypeScript be able to understand that `result` has now been narrowed down to `ValidatorResultFailure` like it does in the equivalent TypeScript version.

**Comment by sandersn** [comment] 2021-11-09 23:55
The difference is strictNullChecks on/off, not JS vs TS.

**Comment by sandersn** [comment] 2021-11-10 00:06
Here's a smaller repro:

```ts
declare const result: { ok: true; } | { ok: false; error: string; }
if (!result.ok) {
  console.error(result.error);
}
```

You can reproduce the error with `strictNullChecks: true` by adding `| undefined` to `ok`'s type:

```ts
declare const result: { ok: true; } | { ok: false; error: string; }
if (!result.ok) {
  console.error(result.error);
}
```

The important part is `{ ok: true | undefined }`; now narrowing can no longer eliminate the success constituent when it sees `if (!result.ok)` because `ok: true | undefined` contains `undefined`, which is falsy. And of course `ok: false | undefined` is falsy. So inside the if block both sides of `Result` are still there.

**Comment by sandersn** [comment] 2021-11-10 00:07
Duplicate of https://github.com/microsoft/TypeScript/issues/29862

**Closed by sandersn** 2021-11-10 00:07 UTC

**Comment by casr** [comment] 2021-11-10 16:01
Thanks for shedding light on this, @sandersn 

So running through the options you presented, I can confirm that:

  - when `strictNullChecks` is enabled there is no problem
  - when the comparison is explicit to `false` it works, e.g. `result.ok === false`

However, based on what you said I would have expected:

```javascript
if (result.ok != null && !result.ok) {
  console.error(result.error);
}

// or
if (typeof result.ok === "boolean" && !result.ok) {
  console.error(result.error);
}
```

to have worked.

What am I missing?

**Comment by sandersn** [comment] 2021-11-13 00:19
In your first example, `result.ok != null` doesn't do anything without strictNullChecks; all types include `null | undefined`, so you can't narrow it away.
In your second example, `typeof result.ok === "boolean"` is similar.

You can still get it to work with `if (result.ok === false)` because that doesn't use the truthy/falsy mask to narrow.

**Comment by casr** [comment] 2021-11-15 14:28
Okay, I think I understand now. Thank you for the explanations!
