### ISSUE TITLE
3.4 RC: Composite package build not recompiling after file change due to tsbuildinfo

### ISSUE THREAD

**Issue by AlexLandau** [Microsoft/TypeScript#30589] opened 2019-03-25 23:08 UTC
**TypeScript Version:**  3.4.0-dev.20190323

**Search Terms:**
tsbuildinfo, 3.4, 3.4-rc, 3.4.0-rc, recompile, composite

**Code**

Repo with full repro instructions: https://github.com/AlexLandau/tsbuildinfo-no-rebuild

**Expected behavior:**

Running `tsc` in the project will return error results based on the current files, not on the errors it had the last time it ran.

**Actual behavior:**

When running `tsc` in the project (which has `composite` set to true), the build will return the set of errors it previously had until the tsconfig.tsbuildinfo file is deleted. The build errors use the old error locations but the current contents of the file, which can look a little odd:

<img width="618" alt="Screen Shot 2019-03-25 at 4 07 04 PM" src="https://user-images.githubusercontent.com/5733346/54959963-1dd7c480-4f18-11e9-8110-da90b1ce5d29.png">

**Comment by sheetalkamat** [comment] 2019-03-26 21:29
This is duplicate of #30588

**Closed by sheetalkamat** 2019-03-26 21:29 UTC
Labels: Bug, Duplicate

**Comment by AlexLandau** [comment] 2019-03-27 21:45
I can confirm that this is fixed in `3.4.0-dev.20190327`. Thank you!
