### ISSUE TITLE
.mjs=>.mts and .cts => .cts

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/TypeScript#39971] opened 2020-08-10 08:32 UTC
## Use Cases
Create equal extensions for mjs cjs support .mjs=>.mts and .cts => .cts
maybe that will allow us to implement mjs cjs interop and input features more fast #27957 #18442

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by orta** [comment] 2020-08-10 12:20
I'm going to call this of dupe of those issues, as the decision on this is likely a part of the solution for pjs support

**Closed** 2020-08-10 12:52 UTC
Labels: Duplicate
