### ISSUE TITLE
Array.reduce doesn't work 

### ISSUE THREAD

**Issue by ilchenkoArtem** [microsoft/TypeScript#44063] opened 2021-05-12 19:28 UTC
# Bug Report

### 🔎 Search Terms
Array.reduce
Array.reduce doesn't work 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about reduce

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/KYDwDg9gTgLgBDAnmYcBqBDANgV2AFWVQF44BnGKASwDsBzOAHzhpwFsAjYKJuDiCFmAYaAbgCwAKClTQkWHFoxuAMwwBjVAEkAQhjLAAMlQpblbADxx8AeTAwqEGnFDKaAEzJxd+4HYdOcKQ+Bv6ONAB8cADeUnBwEPbhZABc1mFOANoAuhKSAL4yknLQ8EqqGtp6oUmBsZLxYBhQwDQwmLjAAPxpHXiEKHmF0sXgpYptFZreAMrAQuowGc6urZ7e1X61zvXxWBhcWGkU1PR58QBu2HjHlLQMzKyc3ENFJQpIKHBzCzBmwGwBiQNr5jKZzBY4rN5sBFsspBE8rIxh8iN5zECgt8YYt-oC0cwQkYTH9zEV1E4KNYAKIzfAAfUMWjpKTxQJyWMyUOiCW2qTgOXyABpuVD4okAjR+Zlok0Wm0+sA0mosAZ8tkRQ04MKpNkivhaQymXSAHRsDBgAAUluUFDBpIBAEoglFdnAKVL4BLkljbTB7XiTd7KedeZKyCaWu4cJoLIr2dkItaNOohWHws7iK6xYoVJbgzQTXLWu1rsBnW74vEU0WcGQABb57aOnPDKs5lowHBQZwp0PCgXZR1DR1AA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙁 Actual behavior

TS throws error "This expression is not callable."
### 🙂 Expected behavior
TS should let me iterate through array (I tell it the type is either array of IBaseOption OR array of ISelectOption (not an array of mixed types). In any case the variable is an array and those methods should be callable.

**Comment by jcalz** [comment] 2021-05-12 20:42
The example code should be here as plain text, and phrases like "doesn't work" and "works" aren't really descriptive enough to do anybody much good.  Could you make an edit?

Note that this seems to be a duplicate of or strongly related to #36390; that issue is closed as fixed, although the problem with `reduce()` remains; not sure if this one should stay open in its place or if there's a different canonical issue somewhere.

**Comment by RyanCavanaugh** [comment] 2021-05-12 21:06
I think what you want is this (which has two edits)
```ts

TEST_LIST.map((testListItem) => {
  const options = testListItem.options;
  (options as IBaseOption[]).reduce<ValueType[]>((acc, option) => {
    if(option.parentValue) {
      acc.push(option.parentValue)
    }
   
    return acc;
  }, []);
})
```
There's no typesafe way for TS to collapse the different `reduce` definitions without knowing what `reduce` "actually does"; requiring a type assertion here is appropriate.

**Comment by Lafore17** [comment] 2021-05-13 18:23
But one question reading comments above: considering options as `IBaseOption[] | ISelectOption[]` I expect to get type for option inside reduce like `IBaseOption | ISelectOption` and at the same time `never[]` for accum before setting type via generic. am I right?

**Comment by ialexryan** [comment] 2021-06-01 22:47
I poked around in the files of #31023, which fixed .map() on unions of array types (closing #36390), and found this comment in the test suite:

https://github.com/microsoft/TypeScript/pull/31023/files#diff-7a118e355c5fce1fa4374a0e2b34732788f5695be1a6bf5b36bb71bcfa3b7fb9R28

which indicates that .reduce() not working was a known limitation. @weswigham – any chance you already have an issue tracking that somewhere, or is this ticket fine? I've also [checked some other common array methods](https://github.com/microsoft/TypeScript/issues/36390#issuecomment-852533093) and created a [new issue](https://github.com/microsoft/TypeScript/issues/44373) to track the ones that aren't working.

**Closed** 2023-06-08 03:40 UTC
Labels: Unactionable
