### ISSUE TITLE
`| undefined` should be part of type when getting items from an array

### ISSUE THREAD

**Issue by lonewarrior556** [microsoft/TypeScript#38470] opened 2020-05-11 16:23 UTC
**Search Terms:** Array type

**Code**

Simplest code:
```ts
var a: string[] = ['a'];

var shouldBeString = a[0] // string 
var couldBeString = a[10000]; // string 
var notAString = a[Infinity]; // string 
var alsoNotAString = a[NaN]; // string 

```
I get the difficulty in discerning `0`, `10`, `NaN` and `Infinity` since the type of all those is `number`.. but wouldn't it make sense then to make the return type from these queries  `string | undefined`?
For those who don't want that they can turn off `strictNullChecks`

Tuples are only slightly better
```ts
// tuple 
var str = '';
var aa = [str, str] as const

var _shouldBeString = aa[0] //string
var _notString1 = aa[10000]; // type error
var _notString2 = aa[Infinity]; // no error
var _notString3 = aa[NaN]; // no error
```

**Expected behavior:**
```ts
var arr = [''];
var item = arr[10];
// typeof item = string | undefined;
```
**Actual behavior:**
```ts
var arr = [''];
var item = arr[10];
// typeof item = string;
```

**Playground Link:** 
[TS-Playground](https://www.typescriptlang.org/play?#code/G4QwTgBCBcEM4BcwEsB2BzA2gXQgXgkwHIQjsBuAKEtEjgAsB7AVwBsATAIQFMBlJNOnxRMABlwB6CfAEYINcBADGLDj34o5BEJgCMog+PIQpMzUIWRUjBBsG7hOgJKoAZmmQIAnhRPTE5vK0ENa2sugATI6YAHIgMb6mAYLy1KYIzAAOrNxBigHCRERUwSAgwpgBADRmuCBwyoyoiNTBAPoMqlx84Y464n7JGJYQbaF2GA7aOvqGidLembncYGCMYCNjNhORfZgu7qiePsam1hAraxvt4+EAzHtxCafS55frlEA)

**Related Issues:**

**Comment by MartinJohns** [comment] 2020-05-11 16:30
Duplicate of #13778.

**Comment by RyanCavanaugh** [comment] 2020-05-11 16:30
Duplicate #13778

**Comment by RyanCavanaugh** [comment] 2020-05-11 16:31
@MartinJohns easy dupe day eh

**Comment by MartinJohns** [comment] 2020-05-11 16:33
@RyanCavanaugh I spend way too much time reading these issues in this repository, for quite some time already (using TypeScript since preview version), so I often recognize repeated issues. Just sometimes I fail to find the original issue.

**Comment by lonewarrior556** [comment] 2020-05-11 17:02
@RyanCavanaugh @MartinJohns 
Fine, yes part one complete overlap.. 

However I did not see this tuple behavior being address in the other thread.. Can't see how those arguments would apply here:

```ts
// tuple 
var str = '';
var aa = [str, str] as const

var _shouldBeString = aa[0] //string
var _notString1 = aa[10000]; // type error
var _notString2 = aa[Infinity]; // no error
var _notString3 = aa[NaN]; // no error
```

**Comment by RyanCavanaugh** [comment] 2020-05-11 17:16
`Infinity` and `NaN` aren't specially typed; they're just `number`. See #32277 and #28682

**Closed** 2020-05-13 18:00 UTC
Labels: Duplicate
