### ISSUE TITLE
Describing an Interface where unknown properties are of a specific type

### ISSUE THREAD

**Issue by amarzavery** [Microsoft/TypeScript#20597] opened 2017-12-09 20:27 UTC
- This is the json schema definition or a model defined in the OpenAPI specification 2.0.
```json5
{
  "Foo": {
    "properties": {
      "name": {
        "type": "string"
      },
      "age": {
        "type": "number"
      }
    },
    "additionalProperties": {
      "type": "string"
    }
  }
}
```
We would like to model an `Interface` in TS for the above json schema definition as follows:
```typescript
interface Foo {
  name: string;
  age: number;
  [prop: string]: string;
}
```
However, TS gives the following error:
```
Property 'age' of type 'number' is not assignable to string index type 'string'.
```
- Well, we can make the value of the indexed property a loose type `any`
```typescript
interface Foo {
  name: string;
  age: number;
  [prop: string]: any; // but this defeats the purpose of providing good typing.
}
```
The above approach would be perfectly fine for `"additionalProperties": true` or `"additionalProperties": { "type": "object" }`, but not for specific types.

- Another approach would be to make additionalProperties a `Dictionary<string>`.
```typescript
interface Foo {
  name: string;
  age: number;
  additionalProperties: { [prop: string]: string}; 
}
```

This would be convenient for C#, Python, etc. developers (as they deal with objects in that language). However, it would be inconvenient for JS developers to provide (or access) a JSON object that has unknown properties in a **property bag** called additionalProperties.

Any help/idea in solving this problem will be very helpful.

**Comment by alexrock** [comment] 2017-12-10 13:52
Intersection types allow this
```ts
type Foo =
  {
    name: string;
    age: number;
  } & {
    [prop: string]: string;
  };
```

**Comment by amarzavery** [comment] 2017-12-10 17:34
@alexrock - Thanks for letting me know. Learnt something new today. 

I tried the following
```typescript
type Foo = {
  name: string;
  age: number;
} & {
  [prop: string]: string;
};

var f: Foo = {
  name: "foo",
  age: 10,
  color: "red"
};
```
and it still gives an error:
```
Type '{ name: string; age: number; color: string; }' is not assignable to type 'Foo'.
  Type '{ name: string; age: number; color: string; }' is not assignable to type '{ [prop: string]: string; }'.
    Property 'age' is incompatible with index signature.
      Type 'number' is not assignable to type 'string'.
```

NOTE: I also found some info at @basarat's TS gitbook  which explains [why all members must conform to the undex signature](https://github.com/basarat/typescript-book/blob/de70ce929b992de89b5abd9befa7007139e90fd6/docs/types/index-signatures.md#all-members-must-conform-to-the-string-index-signature).

**Comment by alexrock** [comment] 2017-12-11 18:18
@amarzavery - I understand. Object literals don't allow this, but member access is still allowed and correctly typed.
```ts
type Foo =
  {
    name: string
    age: number
  } & {
    [prop: string]: string
  }

let foo: Foo = JSON.parse(`{
  "name": "foo",
  "age": 10,
  "color": "red"
}`)

foo.color = 0x0000ff // type error
foo.color = 'blue'   // ok, color is string
```
I can't say, absolutely, if this is the intended behavior.

**Comment by DanielRosenwasser** [comment] 2017-12-12 09:08
Looks like a potential duplicate of #17867 (partially discussed here https://github.com/Microsoft/TypeScript/issues/18394#issuecomment-330380288).

**Closed** 2018-01-02 18:40 UTC
Labels: Duplicate
