### ISSUE TITLE
Merging namespaces optimization

### ISSUE THREAD

**Issue by blendsdk** [Microsoft/TypeScript#16570] opened 2017-06-15 20:53 UTC
I was wondering if typescript can/will merge classes in the same namespace when module format is set to `amd` and the results written in a single file?

Given tsconfig.json:
```
{
    "compilerOptions": {
        "module": "amd",
        "target": "es5",
        ........
        ........
        "outFile": "../../dist/js/app.js"
    },
    "files": [
           "Hammer.ts",
           "Saw.ts"
    ]
}
```
The generated code is:
```javascript
var Utils;
(function (Utils) {
    var Hammer = (function () {
        function Hammer() {
        }
        return Hammer;
    }());
    Utils.Hammer = Hammer;
})(Utils || (Utils = {}));
(function (Utils) {
    var Saw = (function () {
        function Saw() {
        }
        return Saw;
    }());
    Utils.Saw = Saw;
})(Utils || (Utils = {}));

```

This could be merged to something like:
```javascript
var Utils;
(function (Utils) {

    var Hammer = (function () {
        function Hammer() {
        }
        return Hammer;
    }());
    Utils.Hammer = Hammer;

    var Saw = (function () {
        function Saw() {
        }
        return Saw;
    }());
    Utils.Saw = Saw;
    
})(Utils || (Utils = {}));
```
In our case we have over 100 classes which makes the output considerably larger.

Is there a solution to this?

**Comment by mhegazy** [comment] 2017-06-15 21:07
duplicate of https://github.com/Microsoft/TypeScript/issues/447

**Comment by mhegazy** [comment] 2017-08-17 18:36
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-08-17 18:36 UTC
Labels: Duplicate
