### ISSUE TITLE
`(nullable?.methodOrProperty ?? defaultValue) === defaultValue` should be a type guard

### ISSUE THREAD

**Issue by tats-u** [microsoft/TypeScript#58196] opened 2024-04-15 10:22 UTC
### 🔎 Search Terms

- type guard
- nullish coalescing (`??`)
- optional chaining
- default value

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Type Guards

4.9 & Playground

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcAUAjAhgJwFyIDOUOMYA5gNoC6iAPomCADbP2LgAmApsGd5wCUiAN4AoRJMQ5uUEDiSZcAfgB0zbhSgALRMuWIADMICEAXjNHEAMmuIAslh3q45JTnWbyOwQG4xAL5AA

### 💻 Code

```ts
function foo(bar: string[] | null | undefined) {
    return (bar?.length ?? 0) !== 0 && Math.log(bar.length);
}
```

### 🙁 Actual behavior

'bar' is possibly 'null' or 'undefined'.

### 🙂 Expected behavior

No errors

### Additional information about the issue

`Math.log(bar.length)` can be a React component in real applications.

I have to write the following instead as of now:

```ts
function foo(bar: string[] | null | undefined) {
    return bar != null && bar.length !== 0 && Math.log(bar.length);
}
```

**Comment by MartinJohns** [comment] 2024-04-15 10:47
Duplicate of #54825.

**Comment by uhyo** [comment] 2024-04-16 02:07
I doubt this is a duplicate. The linked issue is all about whether TS should know that `0 < 1`, while this issue only requires the knowledge that `0 === 0`, which TS already uses in many places.

Also the linked issue mentions another issue ( https://github.com/microsoft/TypeScript/issues/48536#issuecomment-1086885375 ) but that's a different topic too. This issue does not include any request to reason about “or” logics.

**Comment by MartinJohns** [comment] 2024-04-16 04:04
The underlying issue is the same.

**Comment by tats-u** [comment] 2024-04-16 09:20
@MartinJohns You have said that that issue is difficult to be fixed for a "design limitation", but this is a more limited form and easier to be fixed. This issue must not be closed just because of the combination of the "duplication" and that "design limitation".
C# can do the similar thing.

**Comment by tats-u** [comment] 2024-04-16 09:28
I have added an additional limitation that the fallback value is the same as the value of the other operand.

**Closed** 2024-04-19 01:26 UTC
Labels: Duplicate

**Comment by tats-u** [comment] 2024-04-19 10:19
Reopen and remove Duplilate
@MartinJohns Why no advanced notice?

**Comment by MartinJohns** [comment] 2024-04-19 10:46
> Reopen and remove Duplilate

Ryan considers it a duplicate, that's why he marked the issue as such. He surely read your comment, but it doesn't change anything. The underlaying issue is still the same. Type narrowing is done on variables, not expressions. By adding the `?? 0` to `bar?.length` you're not checking anything `bar` related for truthiness anymore, but the entire expression, so `bar` is not narrowed. Changing that would require a lot of changes in the code base.

> Why no advanced notice?

It's been marked as Duplicate for 4 days. That's the advance notice.

**Comment by tats-u** [comment] 2024-04-19 14:09
@MartinJohns Do you mean https://github.com/microsoft/TypeScript/issues/48536#issuecomment-1093105323 ?
`a ?? "" === ""` is as simple as `typeof a === "b"`. The only differences are:

- the fallback value propagated from the left operand expression when `a` is nullish can be changed from `"undefined"`
- `??` is a binary instead of unary

 C#'s null flow analysis can recognize this pattern. You will be able to get its specification from https://ecma-international.org/publications-and-standards/standards/ecma-334/ next year. It might as well be considered to be added to the backlog.

> It's been marked as Duplicate for 4 days. That's the advance notice.

FYI, https://github.com/actions/stale, which has been famous, politely writes a post before closing, but your bot does not. However I do not require the bot to be improved because its improvement is just a bullshit job for your team.

**Comment by MartinJohns** [comment] 2024-04-19 14:27
Please note that I am not a member of the TypeScript team. It's not my bot.

Besides that, the bot did write a polite comment before closing the issue.

**Comment by tats-u** [comment] 2024-04-19 14:41
Oh no, you are not Owner or Member. I have misunderstood. Sorry.
