### ISSUE TITLE
Can I ignore generics?

### ISSUE THREAD

**Issue by iamssen** [Microsoft/TypeScript#11422] opened 2016-10-06 16:16 UTC
I find some tsc option or solution for ignore generics check.

```ts
const instance:Type<TypeA, TypeB, TypeC> = new Impl<TypeA, TypeB, TypeC>();
instance.method<TypeD, TypeE, TypeF>({});
```

Some typing libraries need too much generics like this code.
Sometimes too long generics are disturb to coding.

```ts
const instance:Type = new Impl();
instance.method({});
```

Some cases this code is better for understanding.

Typescript have a option ignore generics check?
(just ignore generics check only. not class, interface type check)

**Comment by HerringtonDarkholme** [comment] 2016-10-06 16:29
Possible duplicate of https://github.com/Microsoft/TypeScript/issues/2175

**Closed** 2016-10-06 22:05 UTC
Labels: Duplicate
