### ISSUE TITLE
TSC 1.8.9 - TSConfig.json - Files not used by default

### ISSUE THREAD

**Issue by snerks** [Microsoft/TypeScript#8161] opened 2016-04-18 23:33 UTC
Additional information on Closed issue #8145 (I don't think I have permission to re-open)

**TypeScript Version:** 

1.8.9

Thanks for investigating.

I noticed you are using **tsc v1.8.10** to try to reproduce.

My globally-installed version is currently **1.8.9**.
I think this version may have been installed with the recently-released VS Code 1.0.
It is with VS Code that I first encountered the issue - but it also occurs at the command line (with **tsc v 1.8.9**)

As an experiment, I used a local NPM install of **tsc v.1.8.10**.

If i then invoke the compiler thus:

 .\node_modules\.bin\tsc -p . 

the HelloWorld.js file is generated.

So, for information:
1) Are you able to test this issue with **tsc v1.8.9**?
and/or
2) Is there a VS2015 tools installer for **tsc v1.8.10** (which seems to resolve the problem) I can use?

I usually use this link to install the Typescript compiler and VS2015 tooling:
[https://www.microsoft.com/en-us/download/details.aspx?id=48593&751be11f-ede8-5a0c-058c-2ee190a24fa6=True](https://www.microsoft.com/en-us/download/details.aspx?id=48593&751be11f-ede8-5a0c-058c-2ee190a24fa6=True)

**Comment by mhegazy** [comment] 2016-04-19 00:36
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/7032.

This is a bug in `tsc.exe` in 1.8.* releases. it does not reproduce with `node tsc.js` (which `.\node_modules.bin\tsc` is an alias to).

To work around the issue, pass the complete path:

```cmd
tsc --p c:\test\8145
```
instead of 

```cmd
tsc --p .
```

**Closed by mhegazy** 2016-04-19 00:36 UTC
