### ISSUE TITLE
[Transforms] shorthand properties not transformed within destructuring patterns

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#8042] opened 2016-04-12 22:08 UTC
**Expected**:

```js
function f18() {
    var a;
    var b;
    var aa;
    (_a = { a: a, b: b }, a = _a.a, b = _a.b, _a);
    (_b = { b: b, a: a }, a = _b.a, b = _b.b, _b);
```

**Actual**:

```js
function f18() {
    var a;
    var b;
    var aa;
    (_a = { a, b }, a = _a.a, b = _a.b, _a);
    (_b = { b, a }, a = _b.a, b = _b.b, _b);
```

Failed tests:
*  tests\cases\conformance\es6\destructuring\declarationsAndAssignments.ts

**Comment by sandersn** [comment] 2016-04-13 21:28
Dupe of #7862, you should talk to @rbuckton about this one.

**Closed** 2016-04-13 22:32 UTC
Labels: Bug, Domain: Transforms, Duplicate
