### ISSUE TITLE
Interfaces should extend Record<string, unknown>

### ISSUE THREAD

**Issue by antoine-morvan** [microsoft/TypeScript#43761] opened 2021-04-21 15:06 UTC
# Bug Report

### 🔎 Search Terms

interface type intheritance Record unkown any

### 🕗 Version & Regression Information

This is a behavior that I have been able to observe on 3.9.3 & 4.2.4. I also reproduced it on the different versions of the playground.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/LAKA9AVKAEHQkgOwC4FMBOAzAhgY1dAJaIAWGhy2i+0AjgK6oDOyhA9ojBGKMWlngIAVZsgAM0AN7RE2ALaoAXNBbpiAc2gBfUKGQBPAA4EASswkBeaCJYTUADzSIAJk2hncbdM4A8qjQA00PSIANaIbADuiAB80AD80ADk+sxJ0MpJEenQYGDQAEQRBXpGpswAjNBWNuLQDk6u7qie3n7IaojqQVT6cYkpaRnJ2dC5+QWpTCUgpcbWolVW0rIKyv5d2rogBvNmTABM1QssVQ2oLm4eXr4b3cFhEdH9yVPpmaPjhVMzu+VMAGZjrUzo4Lk1rm07j1EH0Eq8hh82Dk8t9mDM5v8ACzA0R2MGXKTQADaTHWHQ0AF1lCFwlFENp4YMmO8RsivkU2L8ys0mABWXG2eoEprSUnkzrqanQXqMgZvYZZdljMaoybo7Z-XkANkFyFBjTcYrJKgpXWltKeDK0TIVSPSap+mN5AHY9QbwUaSSa7tLZTb5Yi2TkVY6NbNwFAQLBmgAbbBoZzQdAtejoJiEABuBF2GiITCYjC4PB2PIAqo96R4zLQfEI4jVhYbmq1bmb7pb6TEYPCa-RCCnfD2VVJhyOSQBpIgM0KofRsTDWaUVunRauoWtCYkTykxADcY7GOmjKu7J+UQgPpfmAEFYevNw3rE3PS2bu1JTC+j3En2B6ghxPEdJEPFVt2naBZ3nRchGXSs1xaGs623Xcr3HLYgOgM8xgvK9nQAWWwYghDKAARVBF2WHtCwAIwqeJlBAzC2EMVgOAqAB9eiJQ0NCVRYtjEE4g4GNNSU+K0K9JO2PgMBwGhCOIAAFbB0FYbBYxfQlFMQEjjHIxdJGPUBUQAZRINh6FjJNDHQNhnHoGgMDs9AElABxDC8ZBoE8RAWGgTMNLEZQVytB8fB0lS1MIDSnyYsZaIqRixwE9ghK45QCkC2MZiPUBpIjDyvJ8jh-OysQMugO99HCyLVPU2M4uo+g6OS5jWLSziksKbLcowgqTPyAAxLxoGQMhkxaG4gkiLxQjcSJUFjTTMFG8aCDYdbXN81RHMEsltiKtSSr87zsq6kL4MQWqiN0siKKak9ErakdUvYyqso0vrjwKo7vJ2s6NOE5Rqpu4j7swR6Epa7r4v4jr3u6z6cp7H68JAWSBAU26bxrLSmlCqtEI3CLbr01ADLiIzeBQOTBGgHSyzx85CVB4nax08nKakYyQD+k6yo0g5Kp03GN2OOHntHdrBIunqvtR-Kr35gGAqFjiDmURm8aop6YZe+HZY+3rFZAAaQCAA)

### 💻 Code

```ts
interface Test0 { name: string }

type Res0 = Test0 extends Record<string, unknown> ? 'yes' : 'no'  // "no"
type Res1 = Test0 extends Record<string, any> ? 'yes' : 'no'  // "yes"

type Test1 = { name: string }

type Res2 = Test1 extends Record<string, unknown> ? 'yes' : 'no'  // "yes"
type Res3 = Test1 extends Record<string, any> ? 'yes' : 'no'  // "yes"
```

### 🙁 Actual behavior

The type Res0, testing if the `interface` extends `Record<string, unkown>` is resolved to "no", whereas the its `type` counterpart resolves to "yes" (Res2).

### 🙂 Expected behavior

I believe `unkown` encompasses `any` when testing such type scructure. Thus I expect Res0 to resolve to "yes", i.e. an interface extends `Record<string, unkown>`.

**Comment by MartinJohns** [comment] 2021-04-21 15:25
Duplicate of #42825. Used search terms: `interface extends record unknown`

**Closed** 2021-04-23 18:00 UTC
Labels: Duplicate
