### ISSUE TITLE
crypto.getRandomValues is incorrectly typed using a union type

### ISSUE THREAD

**Issue by LiraNuna** [Microsoft/TypeScript#24840] opened 2018-06-10 09:25 UTC
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 
getRandomValues crypto.getRandomValues

**Code**

```ts
function test(): Uint8Array {
    return crypto.getRandomValues(new Uint8Array(16));
}
```

**Expected behavior:**
No error

**Actual behavior:**
```ts
Type 'Uint8Array | Int8Array | Int16Array | Int32Array | Uint16Array | Uint32Array | Uint8ClampedArray ...' is not assignable to type 'Uint8Array'.
  Type 'Int8Array' is not assignable to type 'Uint8Array'.
    Types of property '[Symbol.toStringTag]' are incompatible.
      Type '"Int8Array"' is not assignable to type '"UInt8Array"'.
```

**Playground Link:**  
https://www.typescriptlang.org/play/#src=function%20test()%3A%20Uint8Array%20%7B%0D%0A%20%20%20%20return%20crypto.getRandomValues(new%20Uint8Array(16))%3B%0D%0A%7D

**Related Issues:** 
I found this one: https://github.com/Microsoft/TypeScript/issues/17610
However, while it does appear to suggest this issue shouldn't happen, I am able to reproduce this

**Comment by mhegazy** [comment] 2018-06-11 19:27
Duplicate of https://github.com/Microsoft/TypeScript/issues/23646. should be fixed in `typesript@next`

**Comment by LiraNuna** [comment] 2018-06-11 19:30
man, github search really let me down here, I did a search of this and did not find that issue.

**Closed** 2018-06-13 06:08 UTC
Labels: Duplicate
