### ISSUE TITLE
Overload Doc Comment Issue

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#11910] opened 2016-10-27 23:12 UTC
**TypeScript Version:**  master: commit adfdae0dc47db5ad8248d26929a7b31cb895a539
Tested on Win10 in vscode 1.6.1 (commit 9e4e44c19)
It appears doc comments are shared between only some of the overloads in the following code snippet. this may be desirable -- perhaps each overload deserves a different description. But then the current behavior is strange as well.

**Code**

```ts

class A {}
class B { x: number }
class C { y: number }
class D { z: number }

/**
 * A doc comment.
 */
export function f(d: D): string; 
export function f(c: C): string; 
export function f(b: B): string;
export function f(a: A): string {
    return "";
}
```

**Expected behavior:**

On hover, all overloads get a doc comment description.

**Actual behavior:** 

Only the overloads with argument of type `D` and `A` get the doc comment.

**Comment by kitsonk** [comment] 2016-10-28 19:32
This has "annoyed" me that they can't be shared by default.

**Comment by mhegazy** [comment] 2016-10-29 00:17
duplicate of https://github.com/Microsoft/TypeScript/issues/407

**Closed by mhegazy** 2016-10-29 00:18 UTC
Labels: Duplicate
