### ISSUE TITLE
Module Resolutions: Paths Aren't Transpiled

### ISSUE THREAD

**Issue by djbreen7** [Microsoft/TypeScript#30436] opened 2019-03-15 20:59 UTC
**TypeScript Version:**  ^3.3.3333 (also tried ^3.4.0-dev.20190315)

**Search Terms:**  
- typescript module resolutions not compiling
- typescript paths not working

**Code**
```javascript
// tsconfig.json
{
  "compilerOptions": {
    "resolveJsonModule": true,
    "strictPropertyInitialization": true,
    "outDir": "dist",
    "target": "es5",
    "lib": ["es2015", "dom"],
    "module": "commonjs",
    "strict": true,
    "strictNullChecks": true,
    "noImplicitAny": false,
    "baseUrl": ".",
    "paths": {
      "~game/dragons": ["game/dragons/index.ts"],
      "~game/enums": ["game/enums/index.ts"],
      "~game/interfaces": ["game/interfaces/index.ts"],
      "~game/tuples": ["game/tuples/index.ts"]
    },
    "esModuleInterop": true,
    "allowJs": true,
    "skipLibCheck": true
  },
}
```
```typescript
// index.ts

import { NightFury, Gronckle } from '~game/dragons';
import { Competitors } from '~game/tuples';

const toothless = new NightFury('Toothless');
const enemy = new Gronckle('Enemy');
const competitors: Competitors = [toothless, enemy];

while (toothless.isAlive && enemy.isAlive) {
    toothless.attack(enemy);
    enemy.attack(toothless);
}

const winner = toothless.isAlive ? toothless : enemy;
console.log(`***`, '\n\n', `${winner.name} wins!!!`);
```

**Expected behavior:**
- `ts-node .\index.ts` should run the game
- `tsc; node .\dist\index.js` should run the game
- `paths should transpile to absolute paths. E.g., `~game/dragons` should should up in `index.js` (after `tsc`) as `./game/dragons` or `../../game/dragons`.  
  
**Actual behavior:**  
- Paths are not transpiled and/or resolved
- `Error: Cannot find module '~game/dragons'`  
  
**Playground Link:**   
- There's a repl, but I'm not sure repl.it actually understands the `import` statements for typescript using module resolutions. It appears that it thinks they are `npm packages`: https://repl.it/@djbreen7/typescript-paths
- https://github.com/djbreen7/typescript-paths

**Related Issues:**

**Comment by DanielRosenwasser** [comment] 2019-03-15 23:16
Duplicate of #10866.

**Comment by RyanCavanaugh** [comment] 2019-03-19 18:27
The overriding principle of our module resolution logic is that *you write the path you want to be in the .js output* and that all configuration is about how we resolve that at compile-time.

**Closed by RyanCavanaugh** 2019-03-19 18:27 UTC
Labels: Duplicate
