### ISSUE TITLE
Abstract function parameter typing doesn't pass to implementing functions

### ISSUE THREAD

**Issue by fzzzt** [Microsoft/TypeScript#11708] opened 2016-10-18 14:55 UTC
This might be VS-specific, so maybe this doesn't belong here, but parameter typing information in abstract functions doesn't seem to pass to concrete classes that extend an abstract class.

**TypeScript Version:**  1.8.36.0 (VS2015)

**Code:**

```ts
export abstract class Foo {
    protected abstract bar(baz: string);
}
export class Goo extends Foo {
    protected bar(baz) {
        // baz is any, not string
    }
}
```

**Expected behavior:**

The `baz` parameter with `Goo` should be `string`.

**Actual behavior:** 

The `baz` parameter with `Goo` is `any`.

**Comment by RyanCavanaugh** [comment] 2016-10-18 15:04
Duplicate of #6854 and a number of others

**Closed by RyanCavanaugh** 2016-10-18 15:04 UTC
