### ISSUE TITLE
Constrain consistent discriminating union type usage

### ISSUE THREAD

**Issue by alexeyMohnatkin** [microsoft/TypeScript#44788] opened 2021-06-28 11:19 UTC
# Bug Report

When I use discriminating unions I expect that only one of them will be allowed by TS, not their intersection

### 🔎 Search Terms

Discriminating union

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about union types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.4&strict=true#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBVAtUAAYSQiHgXgAvKAAN7JeDwfLXVCUTjMAC+AG5FFSiAsWXTEAyvAAyNkMbmCXmjYWi6kAIVAkvpjNA8tZ0iVKv5arFKFojgYiGEOuleoAPgsnRqRcVIZBYDQfmwcf0lAhOMrJo5uZayNbbWyOVzQAByACMACYAMxxy7cxOp9OTTPJtNqxSB4OIPAAMWZoAAFAQrTaw3XBABKbUAPjZAuCKg9XohZF9oH9ilLFar7M5eezGfj+ZzRpn2YFTcUQA)

### 💻 Code

```ts
type Common = {foo: string};
type A = Common & {a: string};
type B = Common & {b: string};
type Params = Common | A | B;

// expect error here
const bar: Params = {foo: '123', a: '123', b: '123'};

const myFn = (params: Params) => {}

// expect error here
myFn({foo: '123', a: '123', b: '123'})
```

### 🙁 Actual behavior

TS allows using both fields from A and B types

### 🙂 Expected behavior

TS should treat this as an error

Also if I try to set `never` for fields that I don't want to be set, it doesn't work
```ts
type A = Common & {a: string, b: never};
type B = Common & {a: never, b: string};
```

There's a workaround for this, but it looks hacky

```ts
type A = Common & {a: string, b?: never};
type B = Common & {a: never, b: string};
```

**Comment by MartinJohns** [comment] 2021-06-28 11:47
Duplicate of #20863. And you also want #12936.

**Comment by alexeyMohnatkin** [comment] 2021-06-28 13:04
@MartinJohns thank you.

For those who are looking for an answer:

```ts
type Common = {foo: string};
type A = {a: string, b?: never};
type B = {a?: never, b: string};
type C = {a?: never, b?: never};
type Params = Common & ( A | B | C);
```

**Closed** 2021-06-28 13:04 UTC
