### ISSUE TITLE
Type narrowing forgotten inside function scope for CONST variables

### ISSUE THREAD

**Issue by Zamralik** [microsoft/TypeScript#34557] opened 2019-10-18 09:20 UTC
**Search Terms:**
function const may be null object possibly null constant inside if statement property does not exist on type

**Code**
```ts
function init() : string | number
{
	return (Math.random() < 0.5) ? "Hello, World!" : 42;
}

const value : string | number = init();

if (typeof value === "string")
{
	const message : string = value.substr(0, 5);
	console.log(message);

	function doSomething()
	{
		const message : string = value.substr(0, 5);
		console.log(message);
	}

	setTimeout(doSomething, 100);
}
```

**Expected behavior:**
Remember that "value" is immutable and has been narrowed to only be a string inside the function too.

**Actual behavior:**
Forget that "value" is immutable and has been narrowed to only be a string inside the function too.

**Playground Link:**
https://www.typescriptlang.org/play/?ts=3.7-Beta#code/GYVwdgxgLglg9mABDMMoAoCUiBciDOUATigOaIA+iYIAtgEYCmRAUAN4sCQRjUIRSdAFkAhlAAWAOiIiwAEzi0siADyIADJICs2APyIARAAlGAG1NwANIgDqcIqbkBCA7kQAWAEwBuFgF8WFggEQkQANxFTEEY3QhIwcioaBmZEAF5kVAxMXxYYYER0KABPAAdGOAKIqJi0usM4sgNMdi5gsFDaRnx8EVIYvEaE9PDI6Ml8EHo49HVrHV9Odvw4U0ZJC1J0Lp6+xhzAzlBIWAREBQBlRV5xMiwuDk4lkKhEHd7+2OIyEerxyemxFm8wOT2Wq3Wm223Q++0WAS4+F4ABUYF04CAMJdrhIyNYAIzqdQHPxAA

**Comment by MartinJohns** [comment] 2019-10-18 09:40
Duplicate of #9998.

**Closed** 2019-10-20 18:00 UTC
Labels: Duplicate
