### ISSUE TITLE
SUGGESTION: Set and Map '.has' method as type guard

### ISSUE THREAD

**Issue by jdavidls** [Microsoft/TypeScript#18781] opened 2017-09-26 23:42 UTC
This is a small suggestion, but I think it can be interesting to bring this type of characteristics to the spirit of the typescript language.

**Code**

```ts
function actual(value: string|number) { 
    let numbers = new Set<number>();

    if (numbers.has(value))  // Error: Type 'string' is not assignable to type 'number'.
        value  
         // we need to do
    if (numbers.has(value as number)) 
        value = value as number 
}

declare class MySet<T> {
    has(elem: any): elem is T;
}

function suggested(value: string|number) 
    let numbers = new MySet<number>();

    if (numbers.has(value)) // OK, we are doing a legal checking
        value // <= value is a 'number'
}
```
thank you for your attention.

**Comment by jcalz** [comment] 2017-09-27 15:27
I don't think this is a great idea, for a few reasons.  The most obvious one is this:

```ts
declare let numbers: Set<number>;
declare let value: string | number; 
if (numbers.has(value)) {
  value + 2 // narrowed to number, okay
} else {
  value.charAt(0); // narrowed to string?!
}
```
If a `Set<T>` doesn't contain a value, then the value *isn't* of type `T`?  

Less obvious but possibly more important is that such a declaration subverts the point of type checking.  Mistakes like this will no longer be caught:

```ts
let nums = [0, 1, 2]; // array of numbers
numbers.has(nums); // oops, no error!
```

So I wouldn't want to see this added to the standard libraries. 

---

If these objections don't sway you and you still find this change useful for your own work, you could always modify or augment your local declaration of `Set`:
```ts
// put this in your own code to reap its benefits
interface Set<T> {
    has(elem: any): elem is T;
}
```

Cheers!

**Comment by mhegazy** [comment] 2017-09-28 00:20
Duplicate of https://github.com/Microsoft/TypeScript/issues/13086

**Comment by jcalz** [comment] 2017-09-28 00:28
It's not a duplicate; #13086 is about performing a `get()` after a `has()`.  This is... something else.

**Comment by DanielRosenwasser** [comment] 2017-09-28 04:15
Is there a very compelling scenario for this? I get the idea, but like @jcalz said, this means you could easily screw up and pass anything accidentally which lead to some frustrating behavior.

There's nothing super wrong with adding your own overload if you feel it'd help you out a lot.

**Comment by fasiha** [comment] 2018-08-09 00:42
Wouldn't the narrower use-case, where `has` is just used just as non-`undefined` typeguard, still be really useful? I often have situations along the lines of:
```typescript
function foo(map: Map<String, String>, key: String): String {
  if (map.has(key)) { return map.get(key); } // Error: Type 'String | undefined' is not assignable to type 'String'.
}
```
It feels odd and incomplete that TypeScript doesn't know that `map.get(key)` in the `if`'s clause must return not-undefined thanks to that `has`.

**Comment by jcalz** [comment] 2018-08-09 01:40
It might be useful, but I'm not sure how successfully you can encode that into the type system.  Maybe something like:

```ts
interface MyMap<K, V, KHas extends K = never> {
  has(key: KHas): true;
  has<H extends K>(key: H): this is MyMap<K, V, KHas | H>;
  get(key: KHas): V;
  get(key: K): V | undefined;
}
```

And then you could use it like:

```ts
function foo<K extends string>(map: MyMap<string, string>, key: K): string {
  if (map.has(key)) {
    return map.get(key);
  }
  return "";
}
```

But I don't know if anyone would really want to see that added to the standard library, since it is cumbersome.

**Comment by RyanCavanaugh** [comment] 2018-08-13 19:55
Agree with @jcalz this doesn't seem like a good solution (to say nothing of the problem)

**Closed by RyanCavanaugh** 2018-08-13 19:55 UTC
Labels: Suggestion, Too Complex

**Comment by avin-kavish** [comment] 2022-08-24 06:13
```
interface Set<T> {
    has<U extends T>(elem: U): elem is U;
}
```

Wouldn't this prevent the `else` case problem?
