### ISSUE TITLE
Docs not pass down through Partial<T>

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#12966] opened 2016-12-16 00:18 UTC
_From @unional on December 15, 2016 23:45_

- VSCode Version: 1.8.0

```ts
interface Foo {
  /**
   * x is your name
   */
  x: string
}

function foo(f: Foo) {}
function boo(b: Partial<Foo>) {}

foo({})
boo({})
```
![image](https://cloud.githubusercontent.com/assets/3254987/21246397/4feaff4c-c2dd-11e6-8bb8-1e31e0e54bf4.png)
![image](https://cloud.githubusercontent.com/assets/3254987/21246403/5c6d6458-c2dd-11e6-90fd-a2badcc72c35.png)

_Copied from original issue: Microsoft/vscode#17357_

**Comment by sandersn** [comment] 2017-01-26 20:17
This is likely a duplicate of #13690 and will be fixed when that is. I'll leave this issue open in case there is additional work to do after the fix for that is done.

**Closed** 2017-05-11 19:50 UTC
Labels: Bug, Fixed, VS Code Tracked

**Comment by Jack-Works** [comment] 2017-10-25 00:59
![image](https://user-images.githubusercontent.com/5390719/31975294-b6a75fb0-b962-11e7-9e15-52e1c5d0d9af.png)

@sandersn Hello, will this be fixed?

**Comment by mhegazy** [comment] 2017-10-25 15:38
that is a different declaration. `name` here is the `name` from class `X` and not from interface `People`, you re-declared it.

**Comment by Jack-Works** [comment] 2017-10-25 15:41
So how to inherits from an interface? After all it just provide a type.
Sine it does not emit code, why its jsdoc passed to it?🤔

**Comment by mhegazy** [comment] 2017-10-25 15:47
I think that is a feature request for docs to be inherited from an implemented interface/base class. feel free to log a new issue for that.

**Comment by Jack-Works** [comment] 2017-10-25 15:54
Alright, I'll try it, thanks.
