### ISSUE TITLE
Cannot `infer` the return type of a generic function in a conditional type

### ISSUE THREAD

**Issue by m93a** [microsoft/TypeScript#58779] opened 2024-06-05 11:21 UTC
### 🔎 Search Terms

Conditional type inference, generic return type, type-level lambda, higher-kinded types, mapped types

### 🕗 Version & Regression Information
Present in TS 3.5.1 to 5.5.0-beta.

### ⚪️ Introduction

I need to write a piece of code that would transverse a deeply nested data structure and fetch required data. However, I would prefer to do it in a way that doesn't force me to couple it too strongly to the data structure's specific type. This would be easiest to achieve with a generic replacer. Trying to implement it, I came across a very unintuitive behavior: given a generic function and its type parameter, it is impossible to correctly infer its return type.

### 💻 Code

```ts
type Foo = (<T>(input: T) => T[]) extends ((a: string) => infer R) ? R : never;
// unknown[]
```

### 🙁 Actual behavior

Does not infer the type argument, replaces it with `unknown`.

### 🙂 Expected behavior

Should use the inferred type argument to correctly infer the return type: `string[]`.

### Additional information about the issue

It seems to me that adding inference here would be possible – after all if I actually _call_ the function, the type argument **does** get infered, and so does the return type. The doors this would open are countless, as infering the return type of a generic function is essentially [higher-kinded types](https://github.com/microsoft/TypeScript/issues/55280#issuecomment-1666660060) in a trench coat.

Were this implemented, we could do things like these:
```ts
type GenericReturnType<F extends (arg: any) => any, P> = F extends (arg: P) => infer R ? R : never;

type Box<T> = { value: T };
type Mapped<T, F extends (arg: any) => any> = { [P in keyof T]: GenericReturnType<F, T[P]> };

type Boxified<T> = Mapped<T, <V>(v: V) => Box<V>>;
```
(Compare #27130)

### Possibly Related Issues
#57351, #33594

**Comment by fatcerberus** [comment] 2024-06-05 14:18
> It seems to me that adding inference here would be possible – after all if I actually call the function, the type argument does get infered, and so does the return type.

That sentence makes this a duplicate of https://github.com/microsoft/TypeScript/issues/40179.

> higher-kinded types in a trench coat

That one got a chuckle out of me. 😄

**Closed** 2024-06-10 01:31 UTC
Labels: Duplicate
