### ISSUE TITLE
A DRY-er syntax for jsdoc types imports

### ISSUE THREAD

**Issue by nojvek** [Microsoft/TypeScript#26352] opened 2018-08-10 01:50 UTC
## Suggestion

So the current way of importing things in JS land for types declared in .d.ts is kind of really redundant

```
/** @typedef { import('./my-types').Foo } Foo */
/** @typedef { import('./my-types').Bar } Bar */
/** @typedef { import('./my-types').Hello } Hello */
/** @typedef { import('./my-types').World } World */
```

This violates the DRY principle and kind of looks awful.

Can we have a similar import syntax to the .ts and normal .js versions ?

```
/** @import {Foo, Bar, Hello, World} from './my-types' **/
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by DanielRosenwasser** [comment] 2018-08-10 17:56
Duplicate of #22160?

**Comment by nojvek** [comment] 2018-08-10 18:14
Yeah but the other issue is closed right?

I’ve started campaigning for typed js at my current workplace however the redundant type import syntax makes everyone 🤮

**Comment by andy-ms** [comment] 2018-08-10 18:18
The other issue is open.

**Closed** 2018-11-06 21:54 UTC
Labels: Domain: JSDoc, Domain: JavaScript, Duplicate, Salsa, Suggestion, checkJs

**Comment by nojvek** [comment] 2018-11-06 22:50
@weswigham is this actually fixed now? I’m not sure why it’s being closed without a reason.

**Comment by weswigham** [comment] 2018-11-07 00:30
Because it does sufficiently duplicate #22160 which is actually open.
