### ISSUE TITLE
Parameters (even unused) break generic inference in interfaces

### ISSUE THREAD

**Issue by ShanonJackson** [microsoft/TypeScript#45738] opened 2021-09-06 05:04 UTC
# Bug Report
Parameters in generic interfaces that infer their generic from a return type have there inference break from implementation of parameters (even unused ones).

### 🔎 Search Terms
parameters

### 🕗 Version & Regression Information
Incorrect on all versions as far as i can tell (tested current -> 3.7.5)

### ⏯ Playground Link
[playground link](https://www.typescriptlang.org/play?jsx=0&ts=3.7.5&ssl=23&ssc=6&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgArQM4HsQB4AqAfMgN4CwAUMtciHALYQBcyAFBhHFAgBYsZgooAOYBKZAF5i+ANyUayYRDAAxKFnoA5BhFZ1GLfKJYA3LMAAmcigF9KCHAMXATEdFGwhJyAoVYAHTBwWd09fcSlSeRooZQBXKC84kAsIGFAIK2QAemzkCywIDBAAcjBkejgwSCgAOko7CkpKXPzC4rLkYHp-ABsIRnBkMB4Ufy4GGsphFzcgkFZyKhp9ZjYI4lR1emAOWtjsXtdWAFZRABpo6iVVbe1GAIn6cRIcvK2NXYhcEDj6ACNoIQrgpkLEwAkvOMoAwZG80NsvoRfgCgSDGjZRM0KK0cL0AJ7DHgifLAGAwaAQIa7ZBwJK-DgWZDQybQLpeVbTWahHCLEGrFjsTjcHgbBGfPYHLBHXRnS7La7KNQae66FnPUjwj47Di4ZIAaxAWAA7iBgQrQeDIcynnDWtqvnqQIaTWb0Q1REA)

### 💻 Code
```ts
interface Person<T> {
    name: (search: string) => T;
    getFromName(name: T): void;
}
const givePerson = <T>(person: Person<T>) => {
    return undefined; // doesn't matter.
}


// doesn't implement the paramter
givePerson({
    name: () => Promise.resolve(5),
    getFromName(param) { // Promise<number>
        return param; // Promise>number>
    }
})

// only thing different is an unused paramter in name
givePerson({
    name: (search) => Promise.resolve(5),
    getFromName(param) { // Promise<unknown>
        return param; // Promise<unknown>
    }
})
```

### 🙁 Actual behavior
```Promise<unknown>``` is inferred

### 🙂 Expected behavior
```Promise<number>``` is inferred

**Comment by MartinJohns** [comment] 2021-09-06 06:23
This seems to be a duplicate of #40849. Used search terms: `infer generic unknown callback`

**Comment by ShanonJackson** [comment] 2021-09-06 21:22
Thanks @MartinJohns will close

**Closed** 2021-09-06 21:22 UTC
