### ISSUE TITLE
Generic type check seems cannot infer type

### ISSUE THREAD

**Issue by Delagen** [Microsoft/TypeScript#23763] opened 2018-04-28 12:39 UTC
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
const property: keyof IArrayItem = "test";

interface IArrayItem {
    test: string;
}

function A<T extends IArrayItem = IArrayItem>(array: T[]) {
    const t: Partial<T> = { test: "aaa" }; // Error: Type '{ test: "aaa"; }' is not assignable to type 'Partial<T>'.
    const t2: Partial<IArrayItem> = { test: "aaa" }; // Works
}

const array: IArrayItem[] = [];
A(array);
```

**Expected behavior:**
No type check errors

**Actual behavior:**
Error: Type '{ test: "aaa"; }' is not assignable to type 'Partial<T>'

**Playground Link:** [playground](https://www.typescriptlang.org/play/index.html#src=const%20property%3A%20keyof%20IArrayItem%20%3D%20"test"%3B%0D%0A%0D%0Ainterface%20IArrayItem%20%7B%0D%0A%20%20%20%20test%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20A<T%20extends%20IArrayItem%20%3D%20IArrayItem>(array%3A%20T%5B%5D)%20%7B%0D%0A%20%20%20%20const%20t%3A%20Partial<T>%20%3D%20%7B%20test%3A%20"aaa"%20%7D%3B%20%2F%2F%20Error%3A%20Type%20'%7B%20test%3A%20"aaa"%3B%20%7D'%20is%20not%20assignable%20to%20type%20'Partial<T>'.%0D%0A%20%20%20%20const%20t2%3A%20Partial<IArrayItem>%20%3D%20%7B%20test%3A%20"aaa"%20%7D%3B%20%2F%2F%20Works%0D%0A%7D%0D%0A%0D%0Aconst%20array%3A%20IArrayItem%5B%5D%20%3D%20%5B%5D%3B%0D%0AA(array)%3B)

**Related Issues:**

**Comment by Delagen** [comment] 2018-04-28 12:39
See also this discussion https://github.com/DefinitelyTyped/DefinitelyTyped/commit/64104e9760065bd498a3d62d98bb05ea26500dc2

**Comment by jack-williams** [comment] 2018-04-28 13:15
I _think_ this should be an error. There is no guarantee that the object literal is assignable for all possible `Partial<T>`. A caller is free to instantiate the generic in `A` to be the following type `T`.

```ts
type T = { test: "foo" };
type Extends<T extends IArrayItem> = T // Prove T extends IArrayItem
const example: Partial<Extends<T>> = { test: "aaa" }; // Error
```

**Comment by ahejlsberg** [comment] 2018-04-28 14:39
This is working as intended and is a duplicate of many existing issues, e.g. #19388, #17071, #13442.

**Closed** 2018-04-28 20:03 UTC
Labels: Duplicate, Working as Intended
