### ISSUE TITLE
require('file.json') in JS causes error TS2307.

### ISSUE THREAD

**Issue by akdor1154** [Microsoft/TypeScript#15987] opened 2017-05-22 03:29 UTC
**TypeScript Version:**  2.3

When checkJS is enabled, `require`ing a JSON file in a js src file is treated as an error.

**Code**
```js
const config = require('./config.json');
```

**Expected behavior:**
`config` is treated as a var of type `any`, or for bonus points, an anonymous interface with the shape as defined in the relevant JSON file.
**Actual behavior:**
`error TS2307: Cannot find module './config.json'`.

**Comment by mhegazy** [comment] 2017-05-22 18:33
Duplicate of https://github.com/Microsoft/TypeScript/issues/7071, should be fixed by https://github.com/Microsoft/TypeScript/pull/13665

**Comment by mhegazy** [comment] 2017-06-06 16:42
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-06-06 16:42 UTC
Labels: Duplicate
