### ISSUE TITLE
Not standard behavior in module parsing (import not hoisted)

### ISSUE THREAD

**Issue by Jack-Works** [Microsoft/TypeScript#17475] opened 2017-07-28 01:53 UTC
Come from https://github.com/webpack/webpack/issues/5340
**TypeScript Version:**  2.4.1
**Code**

```ts
console.log('')
import x from './x.js'
export {x}
```

**Expected behavior:**
```js
"use strict";
exports.__esModule = true;
var x_js_1 = require("./x.js");
console.log('');
exports.x = x_js_1["default"];
```
**Actual behavior:**
```js
"use strict";
exports.__esModule = true;
console.log('');
var x_js_1 = require("./x.js");
exports.x = x_js_1["default"];
```

This is the behavior of babel:
```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.x = undefined;

var _x = require('./x.js');

var _x2 = _interopRequireDefault(_x);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

console.log('');
exports.x = _x2.default;
```

**Comment by kitsonk** [comment] 2017-07-28 06:38
`var`s get hoisted already.  What is the concern?  Just because Babel does it doesn't necessarily make it right.  What problem does it cause?  The way TypeScript does it is more accurate to the flow of the code.

**Comment by Kovensky** [comment] 2017-07-28 09:01
TypeScript does many things wrong with modules, this is just another one.

https://tc39.github.io/ecma262/#sec-moduleevaluation

**Comment by kitsonk** [comment] 2017-07-28 09:29
@Kovensky yes, I see the challenge now.

Running the following in Safari 10.1.2, it is clear that all imports are evaluated when the module is loaded:

**a.js**

```js
const a = 'foo';

export default a;
```

**index.js**

```js
console.log(a);

import a from './a';

console.log(a);
```

The output to the console is:

```
foo
foo
```

The transpilation to AMD does not have the issue (because of the way AMD works, evaluating all the imports first, like ES Module loaders):

```js
define(["require", "exports", "./a"], function (require, exports, a_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    console.log(a_1.default);
    console.log(a_1.default);
});
```

The transpilation to UMD and CommonJS though is problematic, resulting in a runtime error when accessing the default:

**CommonJS**

```js
"use strict";
exports.__esModule = true;
console.log(a_1["default"]);
var a_1 = require("./a");
console.log(a_1["default"]);
```

**UMD**

```js
(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    }
    else if (typeof define === "function" && define.amd) {
        define(["require", "exports", "./a"], factory);
    }
})(function (require, exports) {
    "use strict";
    exports.__esModule = true;
    console.log(a_1["default"]);
    var a_1 = require("./a");
    console.log(a_1["default"]);
});
```

**Comment by RyanCavanaugh** [comment] 2017-07-28 20:03
Duplicate of #16166

**Closed** 2017-07-28 23:08 UTC

**Comment by aluanhaddad** [comment] 2017-07-29 05:56
Note that `--module system` also works correctly.

Also, when the `--target` >= es2015, the CommonJS and UMD outputs produce TDZ errors because `const` is used instead of `var`.
