### ISSUE TITLE
Composed Mixins don't work

### ISSUE THREAD

**Issue by Bodhizafa** [microsoft/TypeScript#51651] opened 2022-11-27 07:33 UTC
# Bug Report

### 🔎 Search Terms
mixins composed mixins multiple inheritance

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about mixins

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBqCmAnAngIUvaBvAUNf0wA9gHYQAuiArsOUYgBQCU2eBAvm-gEbwD68AB7AAluXgATBgDcwIAFzQKiESQDmLXAW3RE8clUQloskNADU0AEQBCKwG5oXaJ045iZctACC5SiO4qcQB5EngAWRFBVWgAXmgGdAh4RXJkAAd4IgAzOCQ0DBZYgD5CcChoIXESCRgk+C0CUnhmVh0CPQMjaHIACxEIADpeAWExSQYrZqsme2dXd1IKHz8VQPEAFQB3Ikjo43jEjFSMrNyEFHqi0tBIGCr4GrqMRvxyHdbXnU7DYz6B4b8ISicRSKzvIgzeY4Ny3CqoIh9SqCaq1Fb+dbwUIRKKqBi+DFBeDbXa4kgMC4FZJMTSwpZeVBxaBhLbQBF9Zg4VCDZrMObciF86AAemF0B2iAA1hAADTQdbQCREeAQEgAci8aUywF68GAkqAA)

### 💻 Code

```ts
class VeryBase {
    constructor() {    }
    be_excited(val: string) {
        return val + "!"; 
    }
}

const AttributeOneMixin = (Base: typeof VeryBase) => class extends Base{
    one() {
        return this.be_excited("one");
    }
}
const AttributeTwoMixin = (Base: typeof VeryBase) => class extends Base{
    two() {
        return this.be_excited("two")
    }
}

class Both extends AttributeOneMixin(AttributeTwoMixin(VeryBase)) {}

const b = new Both()
b.one();
b.two(); // works, but doesn't typecheck
```

### 🙁 Actual behavior
JavaScript works (the last line has the value "two!", but the type checker does not allow it. Error on the last line, "Property 'two' does not exist on type 'Both'."

### 🙂 Expected behavior
Should type check

**Comment by MartinJohns** [comment] 2022-11-27 08:38
Essentially a duplicate of #51252. You don't provide enough type information to the compiler. `AttributeOneMixin` extends `Base`, it doesn't extend whatever type you pass in.

**Comment by Bodhizafa** [comment] 2022-11-28 02:21
Is it possible to make it extend the right thing?

**Comment by MartinJohns** [comment] 2022-11-28 10:00
Yes, using generics. Did you take a look at the issue I linked? The author even posted his solution.

**Closed** 2022-12-11 18:00 UTC
Labels: Duplicate
