### ISSUE TITLE
[Feature Request] The type checker should be able to infer string values of fields being switched on and match them to string literal types

### ISSUE THREAD

**Issue by JonathanDCohen** [microsoft/TypeScript#49430] opened 2022-06-08 00:39 UTC
# Bug Report

### 🔎 Search Terms

switch
"string literal"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about switch and "string literal"

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.3.3#code/JYOwLgpgTgZghgYwgAgJLIN4Chm+TYCAGwBMAuZAZzClAHMBuLAXyy1ElkRQEFkIAHpBAlKaTDjwFi5ZACI4cpqywwAriARhgAexD4AFMAqoAlBLxUA7sDAIAFkYB000ueyXLCOJRQK5ZJKenmBwANYQlDxGpkyWrCrqmtp6yKERUQZwFDzuKkA)

### 💻 Code

```ts
interface I {
    field: string;
}

interface A extends I {
    field: "a";
}

function f(i: I) {
    switch(i.field) {
        case "a":
            /*
                Argument of type 'I' is not assignable to parameter of type 'A'.
                Types of property 'field' are incompatible.
                Type 'string' is not assignable to type '"a"'.
            */
            takesA(i);
    }
}

function takesA(a: A) {}
```

### 🙁 Actual behavior

Type checking fails to be able to infer the string value in the passed argument matches the string literal value in the type

### 🙂 Expected behavior

The type checker should know that inside the `case` statement, `i.field === "a"` and pass the type check

**Comment by MartinJohns** [comment] 2022-06-08 04:49
The types are not sealed. Just because there's `"a"` in that field, doesn't mean you're having a `A`. Your suggestion would be unsound and lead to bugs.

**Comment by jcalz** [comment] 2022-06-08 14:02
Duplicate of #16976, I think.  

Narrowing the type of an object by checking a property only happens when the object is a discriminated union type and the property is its discriminant.  But `I` is not a discriminated union (or any kind of union), so checking the `field` property only serves to narrow that property and not the whole object.

**Comment by MartinJohns** [comment] 2022-06-09 09:40
@jcalz I don't see how 16976 is related.

**Closed** 2022-06-11 18:00 UTC
Labels: Duplicate
