### ISSUE TITLE
Allow this as return type from static methods

### ISSUE THREAD

**Issue by ianbytchek** [Microsoft/TypeScript#8460] opened 2016-05-04 13:09 UTC
TypeScript allows to return `this` from instance methods, which is to say the least, is great. It would be even better if it allowed doing the same with static methods. The rationale is consistency and feature. 

Line `public static construct():this` below will report `error TS2526: A 'this' type is available only in a non-static member of a class or interface.`, the line below uses `this` inside static method to create a new instance of the class, the line below that also uses `this` to return static property. The error message is misleading, `this` can be and should be used inside static methods whenever appropriate.

```ts
class Foo {
    public static x:any;
	protected y:any;
    public static construct():this {
        return new this();
    }
    public static getX():any {
        return this.x;
    }
	public getY():any{
		return this.y;
	}
	public setY(value:any):this{
		this.y = value;
		return this;
	}
}
```

I'd like to inherit `Foo` and use `construct` on child classes, the only way I can do this by specifying `Foo` as return type, however, this will require to cast the result to `Bar` and `Baz` whenever called from those classes – inconvenient and inconsistent with instance method behaviour.

This seems to be common sense, since this already done for instance methods, shouldn't be much pain doing this for static methods either? What are your thoughts?

**Comment by mhegazy** [comment] 2016-05-04 16:51
Duplicate of https://github.com/Microsoft/TypeScript/issues/5863

**Closed** 2016-05-04 16:52 UTC
Labels: Duplicate
