### ISSUE TITLE
Parameter `this` could be more inferred for common cases

### ISSUE THREAD

**Issue by olmobrutall** [Microsoft/TypeScript#9649] opened 2016-07-12 18:03 UTC
**TypeScript Version:**  2.0.0 beta with `"noImplicitThis":  true`

**Code**

```ts
interface String {
    contains(this: string, str: string): boolean;
}

String.prototype.contains = function (str) {
    return this.indexOf(str) !== -1;
}
```

**Expected behavior:**
When `"noImplicitThis":  true`, in the absence of a `this` declaration, the type of `this` maybe should be inferred for two common cases: 
* In a interface declaration, the type of the interface itself. 
* When assigning a function to a member, the type of the object that contains the member. 

**Actual behavior:** 

In order to use a typed this you need to declare it in the interface.

**Comment by mhegazy** [comment] 2016-07-12 21:47
This looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/9648. the reason you are getting the error in https://github.com/Microsoft/TypeScript/issues/9648 is because the type for `this` was not inferred from the contextual type.
So closing this in favor of https://github.com/Microsoft/TypeScript/issues/9648 to limit noise.

**Comment by sandersn** [comment] 2016-07-12 21:48
Just to double-check, you'd rather write your declaration like this, right?

```ts
interface String {
  contains(str: string): boolean;
}
```

1. We considered inference for interfaces, but it's currently too expensive &mdash; using `this` causes an interface to get a hidden generic type parameter. We considered some optimisations to avoid this when possible but haven't implemented them yet.
2. Without (1), we could only infer `this` for class declarations, not interface declarations. This seems too inconsistent.

However, the code in the example should at least get `this` in `this.indexOf` from the context. Does it?

**Closed by mhegazy** 2016-07-12 21:47 UTC
Labels: Duplicate

**Comment by olmobrutall** [comment] 2016-07-13 06:08
@sandersn you nailed it, if you're explicit about `this` parameter everything is ok, but being so explicit looks redundant in some cases. 

It's a corner case anyway, it happened only when expanding the prototype of string and array.
