### ISSUE TITLE
Add type predicate to Boolean (BooleanConstructor)

### ISSUE THREAD

**Issue by KSXGitHub** [microsoft/TypeScript#32834] opened 2019-08-13 02:41 UTC
## Suggestion

Add an overload to `Boolean` defintion

```diff
 interface BooleanConstructor {
     new(value?: any): Boolean;
-    <T>(value?: T): boolean;
+    <T>(value?: T): value is Exclude<T, false | null | undefined | 0 | ''>
     readonly prototype: Boolean;
 }
```

[playground](https://www.typescriptlang.org/play/#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwCMccIAeADQD54AKADwH4Auec+AH3lWQggEoWdeFgDO8AKJ1IyUBQA0SKBBEJO3Xh3hpQiLKhDBNABk0ByU5QBQl0JFgIweERiTEWARgBMAZk1ESIFD4nCac2iC6+sDWWIi0-hA0iMR8fPAA3pbw2a44lgC+lkA)

### `Array.filter`

```typescript
declare const actions: Array<(() => void) | null | undefined>
actions.filter(Boolean).forEach(act => act())
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2019-08-13 06:08
Duplicate of #31164, #24063, #16655. Was implemented by #29955, and broken by #31515.

**Closed** 2019-08-16 18:00 UTC
Labels: Duplicate
