### ISSUE TITLE
Variadic Tuples that end in a literal type require explicit as const narrowing

### ISSUE THREAD

**Issue by TrueWill** [microsoft/TypeScript#52760] opened 2023-02-14 21:33 UTC
# Bug Report

### 🔎 Search Terms

variadic, tuple, literal, spread

### 🕗 Version & Regression Information

First saw in v4.9.5; have tested back to 4.4.4 and still present.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about variadic.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.9.5#code/MYewdgzgLgBCDWAuGBtAdB6AnAlmA5igLoA0MYArgLYBGAplkTALyoDkAhm2WzdzAEYiAbgBQogPQSYAASgQAtHQAeABzrAoSrFhBZRoSLApgV6zXQAmydJii4CxHgEI2TVik782rkeMPQMADuevAcuibWqBho2HiEpDA+bizsXC5sMBwQMAFQfgbggSFY8BA2cQQZ7mnevmJAA

### 💻 Code

```ts
const ok: [...string[], number] = ['a', 'b', 1];

// @ts-expect-error
const unexpected: [...string[], '!'] = ['a', '!'];

const workaround: [...string[], '!'] = ['a', '!' as const];

const works: [string, '!'] = ['a', '!'];
```

### 🙁 Actual behavior

For Variadic Tuples that _end_ in a literal type, assigning a matching Tuple gives

> Type '[string, string]' is not assignable to type '[...string[], "!"]'.
>  Type at position 1 in source is not compatible with type at position 1 in target.
>    Type 'string' is not assignable to type '"!"'.

### 🙂 Expected behavior

For normal Tuples and Variadic Tuples that only _begin_ with a literal type, assignments do not need `as const` to prevent widening.

For example this works:

```ts
const works2: ['!', ...string[], ] = ['!', 'x'];
```

It would be more intuitive if all Tuples behaved in the same way.

**Comment by swachter** [comment] 2023-02-15 08:19
I found a similar issue:

```
interface Test {
    s: 'a' | 'b';
}

const works: Test[] = [{ s: 'a'}]

// TS2322: Type '{ s: string; }' is not assignable to type 'Test'.
//   Types of property 's' are incompatible.
//     Type 'string' is not assignable to type '"a"'.
const fails: Test[] = [...[{ s: 'a'}]]
```

**Comment by TrueWill** [comment] 2023-02-15 15:48
This does appear to be a duplicate of https://github.com/microsoft/TypeScript/issues/52684 as per @Andarist.

**Comment by ahejlsberg** [comment] 2023-02-15 16:19
This actually isn't a duplicate of #52684, though the issues are closely related. I will modify #52769 to also handle this one.

**Closed** 2023-02-18 17:35 UTC
Labels: Bug, Fix Available
