### ISSUE TITLE
reducing boilerplate emitted from enum declarations

### ISSUE THREAD

**Issue by lightmare** [microsoft/TypeScript#46684] opened 2021-11-04 13:35 UTC
# Suggestion

## 🔍 Search Terms

enum emit, mapping, boilerplate

Searching for "enum *anything*" yields tons of results, but all I've seen were discussing enum syntax and/or semantics, not the emitted code size.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
    NOTE: unless they observe the keys/values being set on the enum mapping object via prototype/setter hacking
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).
    NOTE: might be at odds with goal 4. which is kinda subjective. In my view the emit I'm proposing is cleaner, but I don't know whether it qualifies as idiomatic.

## ⭐ Suggestion

I'd like to reduce the amount of boilerplate emitted from enum declarations. Currently non-const enum like this:
```ts
enum Color { Red, Green, Blue }
```
produces the following JS:
```js
var Color;
(function (Color) {
    Color[Color["Red"] = 0] = "Red";
    Color[Color["Green"] = 1] = "Green";
    Color[Color["Blue"] = 2] = "Blue";
})(Color || (Color = {}));
```

All the strings are repeated twice. The numbers are usually much shorter, though, so we could emit smaller code if we turned the assignments inside out (only when the repeated value is constant, of course):
```js
var Color;
(function (Color) {
    Color[Color[0] = "Red"] = 0;
    Color[Color[1] = "Green"] = 1;
    Color[Color[2] = "Blue"] = 2;
})(Color || (Color = {}));
```

Another redundancy is the enum name being repeated twice per member. I'm sure you had good reasons for using the full name for the parameter, rather than an auto-generated shortcut, which would likely be cryptic and possibly changing between compilations. However I think it could be replaced with `this` without losing clarity:
```js
var Color;
(function () {
    this[this[0] = "Red"] = 0;
    this[this[1] = "Green"] = 1;
    this[this[2] = "Blue"] = 2;
}.call(Color || (Color = {})));
```

I have a [branch with these changes](https://github.com/lightmare/TypeScript/commits/unbloat-emitted-enum-objects) implemented, so you can check it out. I haven't made it into PR, because the template asked that there be an issue in the backlog first and I couldn't find anything related.

## 📃 Motivating Example

The amount of boilerplate in `tsc.js` itself. Can't link to such a big source here, but a pretty good showcase is for example
[tests/baselines/reference/parserRealSource2.js@main](https://github.com/microsoft/TypeScript/blob/ff75b8a180ac69f5d22c079ae053e4b8db29a307/tests/baselines/reference/parserRealSource2.js)
versus
[tests/baselines/reference/parserRealSource2.js@branch](https://github.com/lightmare/TypeScript/blob/af34f98f34a0a2661b7b5241de429fba795b0d2e/tests/baselines/reference/parserRealSource2.js)

## 💻 Use Cases

n/a

**Comment by ajafff** [comment] 2021-11-04 14:55
Duplicate of https://github.com/microsoft/TypeScript/issues/19848

**Comment by lightmare** [comment] 2021-11-05 00:01
Thanks for finding that other issue. I didn't see it, even though it literally contains the words I searched for in the title. I don't quite understand why that issue was marked as a duplicate of a seemingly unrelated issue about some closure compiler bug. But through links from there I was able to find another, still open #34983 of which this one is a duplicate.

**Comment by fatcerberus** [comment] 2021-11-05 00:28
The Closure Compiler issue was a request to change the enum emit to what you suggest in order to align with how CC works in its Advanced mode (i.e. the CC behavior in question is not a bug but a feature, which the current enum emit is/was apparently not compatible with).

**Closed** 2021-11-07 18:00 UTC
Labels: Duplicate

**Comment by lightmare** [comment] 2021-11-08 13:01
Can I get some feedback on the second part, replacing named parameter with `this[this[0] = "Red"] = 0;`? That thing doesn't appear in any of the referenced duplicates. Is it a bad idea?
