### ISSUE TITLE
[Vue TS Plugin] The tsconfig selected for root file and external file is inconsistent

### ISSUE THREAD

**Issue by johnsoncodehk** [microsoft/TypeScript#57632] opened 2024-03-04 13:33 UTC
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Issues: https://github.com/vuejs/language-tools/issues/3951, https://github.com/vuejs/language-tools/issues/1815

For the root file, tsserver selects the last matching tsconfig in the list of tsconfig references for it.
But for external files, tsserver selects the first matching tsconfig in the list of tsconfig references for it.

### Steps to reproduce

1. Clone [segevfiner/vite-issue-1815](https://github.com/segevfiner/vite-issue-1815)
2. Open the repo in VSCode, install [marketplace.visualstudio.com/items?itemName=Vue.volar](https://marketplace.visualstudio.com/items?itemName=Vue.volar) 2.0.4
3. Open `apps/web/src/main.ts`, and check the tsconfig at status bar, it's `apps/web/tsconfig.app.json`
	<img width="543" alt="image" src="https://github.com/microsoft/TypeScript/assets/16279759/15303003-c5ab-4698-9b8b-f6cec7e49828">
4. Open `apps/web/src/App.vue`, and check the tsconfig at status bar, it's `apps/web/tsconfig.vitest.json`, but expected same as `apps/web/src/main.ts`
	<img width="545" alt="image" src="https://github.com/microsoft/TypeScript/assets/16279759/9cc7927e-6889-424e-a53e-c22cf56c01b5">

**Comment by sheetalkamat** [comment] 2024-03-04 23:49
This is working as intended per configuration. 

When we lookup `apps/web/tsconfig.json`: `main.ts` is marked as root of referenced from  referenced directly but part of referenced project = `{
    "key": "c:/temp/vite-issue-1815/apps/web/src/main.ts",
    "value": "c:/temp/vite-issue-1815/apps/web/tsconfig.app.json"
}` but not `app.vue` because the config file for referenced projects isnt returning the vue files.. They are part of projects as external files but not as "config" file names which results in discrepancy in how ts files are treated vs vue files. 

This can be fixed by plugin by setting `extraFileExtentions` through `ConfigureRequest` : https://github.com/microsoft/TypeScript/blob/main/src/server/protocol.ts#L1496

Eg i passed this command to server before opening the file and `app.vue` works same as `main.ts`
```jsonc
{ "seq": 1, "type": "request",      "command": "configure", "arguments": { "extraFileExtensions": [{ "extension": ".vue", "isMixedContent": false, "scriptKind": 7 }] }}
```

**Closed by sheetalkamat** 2024-03-04 23:49 UTC
Labels: Needs Investigation

**Comment by codethief** [comment] 2024-08-22 11:46
@sheetalkamat Tangentially related question: Putting aside `*.vue`-specific peculiarities, what is the expected outcome when tsconfigs have overlapping `include`s (like `tsconfig.app.json` and `tsconfig.vitest.json` in OP's example)? Which tsconfig ends up being responsible for a given file? Is this documented anywhere?

Background: I have seen overlapping includes in many projects over the last years (in parts due to [how create-vue sets up projects by default](https://github.com/vuejs/create-vue/issues/437#issuecomment-2251054099)) and it has always seemed a bit non-deterministic to me which tsconfig ends up being used for a given file.
