### ISSUE TITLE
Assignment of union type fails when assigning in class definition

### ISSUE THREAD

**Issue by frjonsen** [Microsoft/TypeScript#27423] opened 2018-09-28 11:13 UTC
I apologize if the title is incorrect. I'm fairly new to Typescript and not completely at home with terminology yet. The `const / type` pattern below comes from [another Microsoft repository](https://github.com/Microsoft/TypeScript-React-Starter#adding-actions).

**TypeScript Version:**  3.1.1

**Code**

```ts
const A_CONSTANT = 'A_CONSTANT';
type A_CONSTANT = typeof A_CONSTANT;

class Foo<T> {
    bar: T;
}

class FooExtended extends Foo<A_CONSTANT> {
    // Error: Property 'bar' in type 'FooExtended' is not assignable to the same property in base type 'Foo<"A_CONSTANT">'. Type 'string' is not assignable to type '"A_CONSTANT"'.
    bar = A_CONSTANT;
}

class FooExtended2 extends Foo<A_CONSTANT> {
    constructor() {
        super();
        // Allowed
        this.bar = A_CONSTANT;
    }
}
```

**Expected behavior:**

`FooExtended` and `FooExtended2` should be either both work, or both be invalid

**Actual behavior:**
In `FooExtended`, the assignment `bar = A_CONSTANT;` results in an error, `Property 'bar' in type 'FooExtended' is not assignable to the same property in base type 'Foo<"A_CONSTANT">'.
  Type 'string' is not assignable to type '"A_CONSTANT"'.` In `FooExtended`, the equivalent assignment is allowed.

**Playground Link:** http://www.typescriptlang.org/play/#src=const%20A_CONSTANT%20%3D%20'A_CONSTANT'%3B%0D%0Atype%20A_CONSTANT%20%3D%20typeof%20A_CONSTANT%3B%0D%0A%0D%0Aclass%20Foo%3CT%3E%20%7B%0D%0A%20%20%20%20bar%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Aclass%20FooExtended%20extends%20Foo%3CA_CONSTANT%3E%20%7B%0D%0A%20%20%20%20%2F%2F%20Error%3A%20Property%20'bar'%20in%20type%20'FooExtended'%20is%20not%20assignable%20to%20the%20same%20property%20in%20base%20type%20'Foo%3C%22A_CONSTANT%22%3E'.%20Type%20'string'%20is%20not%20assignable%20to%20type%20'%22A_CONSTANT%22'.%0D%0A%20%20%20%20bar%20%3D%20A_CONSTANT%3B%0D%0A%7D%0D%0A%0D%0Aclass%20FooExtended2%20extends%20Foo%3CA_CONSTANT%3E%20%7B%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20super()%3B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20Allowed%0D%0A%20%20%20%20%20%20%20%20this.bar%20%3D%20A_CONSTANT%3B%0D%0A%20%20%20%20%7D%0D%0A%7D

**Related Issues:** None that I could find. Figuring out a search term was very difficult.

**Comment by ahejlsberg** [comment] 2018-09-28 23:39
Duplicate of #10570.

The `bar` property in the derived class is not contextually typed by the `bar` property in the base class (as one might reasonably assume it would be). Therefore, the derived `bar` is given type `string`, the type resulting from widening `A_CONSTANT`. You can fix this issue by adding an explicit type annotation:

```ts
class FooExtended extends Foo<A_CONSTANT> {
    bar: A_CONSTANT = A_CONSTANT;
}
```

**Closed** 2018-12-13 18:00 UTC
Labels: Duplicate
