### ISSUE TITLE
Can't get correct instance type when extending from Error and target es5.

### ISSUE THREAD

**Issue by WangZishi** [Microsoft/TypeScript#17398] opened 2017-07-25 10:10 UTC
**TypeScript Version:**  2.4.2

**Code**

```ts
class MyError extends Error {
    constructor(msg: any) {
        super(msg);
    }
}

let err = new MyError('msg');

console.log(err instanceof MyError);
```

**Expected behavior:**
true

**Actual behavior:**
`err instanceof MyError`  return `false`, and `err` is an instance of `Error`.

**Comment by j-oliveras** [comment] 2017-07-25 12:35
This is a [breaking change since Typescript 2.1](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work).

**Comment by DanielRosenwasser** [comment] 2017-07-26 01:39
Duplicate of #12123.

**Closed** 2017-07-26 02:15 UTC
Labels: Duplicate
