### ISSUE TITLE
control flow based type analysis for type guards broken in 2.0 dev build

### ISSUE THREAD

**Issue by realityfilter** [Microsoft/TypeScript#9569] opened 2016-07-08 10:17 UTC
**TypeScript Version:**   nightly (Version 2.0.0-dev.20160707)

**Code**

```ts
interface IItem {
    id: string;
}

interface ITextItem extends IItem {
    text: string;
}

function isText(item: IItem): item is ITextItem {
    return item['text'] != null;
}

interface IContent {
    items: IItem[];
}

let contents = [] as IContent[];
let item = { id: 'id', text: '\n' } as IItem;

if (isText(item)) {
    console.log(item.text);
    contents.forEach(content => {
        content.items.forEach(i => {
            if (isText(i) && i.text === item.text) {
                // do soemthing
            }
        });
    });
}
```

**Expected behavior:**

Compilation without errors like with version 1.8.10

**Actual behavior:** 

Error during compilation:
test.ts(24,49): error TS2339: Property 'text' does not exist on type 'Item'.

The first reference of item.text is working correctly. The second in the lambda function in the forEach not.

This might by related to #8010.

**Comment by DanielRosenwasser** [comment] 2016-07-08 17:48
Marking as a duplicate of #7719.

The problem is that we can't guarantee that `item` continues being an `ITextItem` across certain function expression boundaries, because the invocation might be deferred, and something else might have changed the value in the mean time.

**Comment by glennsl** [comment] 2016-08-15 21:59
It can be guaranteed if `item` is `const` though, and it does in fact compile if it is.

**Closed** 2016-09-20 23:09 UTC
Labels: Duplicate
