### ISSUE TITLE
RegexpMatchArray type definition is missing undefined in value type

### ISSUE THREAD

**Issue by vbfox** [microsoft/TypeScript#59147] opened 2024-07-05 09:19 UTC
### ⚙ Compilation target

ES5

### ⚙ Library

es5.d.ts

### Missing / Incorrect Definition

```diff
- interface RegExpMatchArray extends Array<string> {
+ interface RegExpMatchArray extends Array<string | undefined> {
```

Along with  `RegExpExecArray` and `groups` in ES2018.

I know that it might be a big change and break a lot of code if not done careffuly but I was bitten again today by that definition being incorrect and I wonder how it could be fixed (Maybe only with some option, or a different stricter lib) because it's very easy to have regex captures be `undefined` with optional capture groups.

### Sample Code

```TypeScript
const matches = 'a '.match(/(.) (.)?/);
const optionalMatch = matches![3] satisfies undefined;
console.log(optionalMatch === undefined);
```

TypeScript fails the `satisfies` check because `matches![3]` is `string`, but running the equivalent javascript shows that it is `undefined`.

```Javascript
const matches = 'a '.match(/(.) (.)?/);
const optionalMatch = matches[3];
console.log(optionalMatch === undefined);
/// undefined
```

### Documentation Link

https://tc39.es/ecma262/#sec-regexpbuiltinexec

> b. If captureI is undefined, then
>   i. Let capturedValue be undefined.
>   ii. Append undefined to indices.

**Comment by MartinJohns** [comment] 2024-07-05 09:27
This is working as intended and what the `noUncheckedIndexedAccess` compiler option was introduced for.

Duplicate of #51292. Used search terms: `RegExpMatchArray in:title`

**Closed** 2024-07-08 01:31 UTC
Labels: Duplicate
