### ISSUE TITLE
Allow ES Module Type-Only Imports from CJS Modules

### ISSUE THREAD

**Issue by amiller-gh** [microsoft/TypeScript#49721] opened 2022-06-29 01:51 UTC
# Suggestion

## 🔍 Search Terms

es esm module cjs commonjs type import moduleResolution node16 nodenext

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow CommonJS modules to import types from ES Modules without an `async import()` if `import types` is specified.

With `moduleResolution: "node16"` enabled, we now get this very helpful error message when importing an ES Module from a CommonJS module (thank you!):

```ts
// Error: Module 'my-es-module' cannot be imported using this construct. The specifier only resolves to an ES module, which cannot be imported synchronously. Use dynamic import instead.
import MyModule from 'my-es-module';
```

However, it is often the case that module will export a types API as well as a runtime API. Sometimes, we only want to import the types from a package. Typescript has the very helpful `import type` directive to acommodate  this use case. However, if we want to import the types from an ES Module, we still get the following error:

```ts
// Error: Module 'my-es-module' cannot be imported using this construct. The specifier only resolves to an ES module, which cannot be imported synchronously. Use dynamic import instead.
import type { MyTypeDefinition } from 'my-es-module';
```

Because `import type`s are stripped from runtime code, there is no need to throw this error.

## 📃 Motivating Example

Because this error is thrown, it forces us to add an unnecessary async import somewhere in our file, causing non-ergonomic development at best, and unnecessary runtime complexity at worst.

Consider:
```ts
// ES Module "my-es-module"
export type MyTemplateString = `${string}-custom-string`;
```
```ts
function myFunction() {
  const tmp = await import('my-ex-module');
  const custom: tmp.MyTemplateString = 'contrived-custom-string';
  return custom;
}
```

It also (very unfortunately) makes it simply impossible to create and re-export derivative types from a module like this: 

```ts
import type { MyTemplateString } from 'my-es-module';

export interface MyInterfaceDefinition {
  type: MyTemplateString | null;
  value: string;
}
```

## 💻 Use Cases

See above motivating example. I'm currently using `// @ts-expect-error` to get past this, but would be great not to! This error should obviously still throw if `importsNotUsedAsValues` is set to `preserve`.

**Comment by RyanCavanaugh** [comment] 2022-06-30 21:25
Previously discussed at https://github.com/microsoft/TypeScript/issues/47338#issuecomment-1015827116 - this not working is intentional since it's a forward-compat hazard.

The proposed solution at the time was to add import mode assertions, but people didn't like this (see comments #48644) and we couldn't agree on a different syntax that was acceptable, so moved import mode assertions to be nightly-only. There's issue #49055 tracking next steps on this issue.

**Comment by brillout** [comment] 2022-11-13 14:34
Workaround: https://www.npmjs.com/package/@brillout/import.

**Comment by slorber** [comment] 2022-11-18 11:05
Note sure to understand why it doesn't work. For me just adding `// @ts-expect-error` is a good enough workaround to make my program typesafe without complicating things too much.

```ts
// @ts-expect-error
import type { ContainerDirective } from "mdast-util-directive";
```

**Comment by slorber** [comment] 2023-04-21 13:30
In my case (building the Docusaurus framework packages), using `// @ts-expect-error` is not a good solution.

The emitted `.d.ts` files contain the imports but `// @ts-expect-error` is not in the `.d.ts` output of the lib.

This makes the framework users have compilation errors with `skipLibCheck: false`, such as:

```tsx
../packages/docusaurus-mdx-loader/lib/loader.d.ts:9:32 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("unified")' call instead.

9 import type { Pluggable } from 'unified';
```

---

As far as I understand, Import attributes moved to stage 3 again with a new syntax (https://github.com/microsoft/TypeScript/issues/53656)

See also https://github.com/microsoft/TypeScript/pull/53426#issuecomment-1494666088

Do you think the following will fix the problem?

```tsx
import type { Plugin } from 'unified' with { "resolution-mode": "import" };
```

Can we expect it to be available soon @RyanCavanaugh ? 
Looks like you'd rather not rush things according to this comment: https://github.com/microsoft/TypeScript/issues/53656#issuecomment-1496286155

Is there any alternative workaround to the above solution in the meantime?

**Comment by voxpelli** [comment] 2023-06-03 20:04
Duplicate of #52529 which has a fix in #53426 (I know this one was created first, but the other one has more activity)

**Comment by slorber** [comment] 2023-10-04 13:00
Isn't TS 5.3 beta fixing this issue @andrewbranch ? 

<img width="799" alt="CleanShot 2023-10-04 at 14 58 42@2x" src="https://github.com/microsoft/TypeScript/assets/749374/3a575ecb-707a-4af9-916f-8f398645fe5d">

**Comment by andrewbranch** [comment] 2023-10-04 16:28
Yep!

**Closed by andrewbranch** 2023-10-04 16:28 UTC
Labels: Suggestion, Needs Proposal
