### ISSUE TITLE
`[ts] Cannot find module` when project rebuild

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#22349] opened 2018-03-06 02:16 UTC
_From @STayinloves on February 28, 2018 7:41_

- VSCode Version:
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version:

Steps to Reproduce:

1. Clone https://github.com/Microsoft/Recognizers-Text
2. cd javascript path
3. run build script
4. edit a ts file `JavaScript/packages/recognizers-number/src/number/parsers.ts` for example
5. error `[ts] Cannot find module '@microsoft/recognizers-text'`.

reload vscode the error disappears.
```
rm -rf node_modules
npm run build
```
can also reproduce this bug.

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#44710_

**Comment by mjbvz** [comment] 2018-03-06 02:16
_From @vscodebot[bot] on February 28, 2018 7:41_

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
- [Integrated Terminal not working (#43981)](https://www.github.com/Microsoft/vscode/issues/43981)

**Comment by mhegazy** [comment] 2018-04-26 20:30
closing for now. please reopen if more information is available.

**Comment by sheetalkamat** [comment] 2018-04-30 21:17
@STayinloves I followed the repro steps you mentioned but wasnt able to reproduce the issue (that is there is no error shown for module resolution). Then when i looked at your initial report, i realised you were trying ```typescript@2.8```, so i tried this with ```typescript@2.8.3``` and was able to repro the issue. The issue is fixed in the master. You can try using ```typescript@next``` and see if the issue is fixed for you.
Just for record this is what i did to repro the issue.
```
cd Javascript
npm install lerna
npm run build
cd ..
code .
```
Opened ```Javascript\packages\recognizers-date-time\src\dateTime\english\dateConfiguration.ts``` and verified it doesnt show error for resolution of ```@microsoft/recognizer-text```
Then with that file open, opened file ```Patterns\English\English-DateTime.yaml``` and added below text in the end 
```
SpecialDecade2Cases: !dictionary
  types: [ string, int ]
  entries:
    'noughties2': 2000
    'two thousands2': 2000
```
On command prompt
```
cd Javascript
npm run build
```
After compilation was complete checked the open ts file and if the issue repros you see error about resolution of  ```@microsoft/recognizer-text``` which is fixed now.

**Closed** 2018-04-30 22:04 UTC
Labels: Bug, Fixed, VS Code Tracked

**Comment by STayinloves** [comment] 2018-05-02 06:55
@mhegazy  Please reopen the issue. I'm sorry for previous misjudge, I have updated the comment above.

**Comment by sheetalkamat** [comment] 2018-05-04 23:12
@STayinloves I was able to track down the issue and have PR to handle these kind of scenario. Unfortunately handling it with the settings you have, isnt feasible from performance perspective since you have a setup such that your node_modules in the ```JavaScript\packages\recognizers-date-time``` have symbolic link folder in ```JavaScript\packages\recognizers-date-time\node_modules\@microsoft``` which means we cannot just say ```JavaScript\packages\recognizers-date-time\node_modules\@microsoft\recognizers-text``` is same as ```JavaScript\packages\recognizers-text``` folder without doing costly mapping. The solution to this is adding path mapping to the ```tsconfig.json```. I modified ``JavaScript\packages\recognizers-date-time\tsconfig.json``` to 

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2015",
        "outDir": "compiled",
        "sourceMap": true,
        "rootDir": "src",
        "moduleResolution": "node",
        "declaration": true,
        "declarationDir": "dist/types",
        "typeRoots": [
            "node_modules/@types"
        ],
        "baseUrl": "./", 
        "paths": {
            "@microsoft/recognizers-text-number": ["../recognizers-number"],
            "@microsoft/*": ["../*"]
        }
    },
    "include": [
        "src"
    ]
}
```
and used drop from #23910 and was able to see that this issue gets resolved. Can you please give that a try as well.

(Note the ```baseUrl``` and ```paths``` entries and how they help with the resolution. Compiler tries to resolve ```"@microsoft/recognizers-text-number"``` to ```../recognizers-number``` before followings its usual course and hence that helps in us having knowledge that the ```recognizers-number``` will take part in module resolution and to handle it accordingly.)

**Comment by STayinloves** [comment] 2018-05-05 02:26
Thank you @sheetalkamat !
I'll bring this up to our team and provide feedback here.
