### ISSUE TITLE
Suggestion:Add keys enum set for typescript Object

### ISSUE THREAD

**Issue by eos3tion** [Microsoft/TypeScript#16848] opened 2017-06-30 02:14 UTC
TS2.4 brings string type enums.
I suggest make a special namespace `TSKeys` for all Typescript Objects/Interfaces.
TSKeys is const string enums,and contains all the keys of Objects/Interfaces.

```typescript
interface A{
  a:string;
  b:boolean;
  c:number
}
```
tsservice automatically generate const enum `TSKeys` like this
```typescript
module A{
   export const enum TSKeys{
      a="a",
      b="b",
      c="c"
   }
}
```
when refactor rename `A.a` to `A.x`,`A.TSKeys.a` change to `A.TSKeys.x` too.

**Comment by kitsonk** [comment] 2017-06-30 08:53
This seems like a very narrow use case for a specific programming style and a perfect canidite for someone to use the [Compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) to write a tool that does this sort of emit on their code.  Not something that would be generally usable (or even desirable).  TypeScript is designed for the type information to be [fully erasable and not modify the run-time behaviour](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#goals).  This specifically would generate additional run-time code that was not authored.

**Comment by eos3tion** [comment] 2017-06-30 09:24
@kitsonk 
same as keywords `keyof`
`TSKeys` is only in developing-time.
```typescript
interface A{
  a:string;
  b:boolean;
  c:number
}
let m = {} as A;
m[A.TSKeys.a]="hello";
```
after compile,js code will be:
```javascript
let m = {};
m["a"] = "hello";
```

**Comment by kitsonk** [comment] 2017-06-30 14:10
`enum` is not a development time only construct... just saying it is doesn't make it so.

**Comment by mhegazy** [comment] 2017-08-21 19:23
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/1579

**Comment by mhegazy** [comment] 2017-09-05 17:06
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-05 17:06 UTC
Labels: Duplicate
