### ISSUE TITLE
import 'invalid' is not checked

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#56873] opened 2023-12-25 16:35 UTC
### 🔎 Search Terms

none

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and 5.3.3
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

```ts
import 'invalid';
```

### 🙁 Actual behavior

no error

### 🙂 Expected behavior

error same as:

```ts
import {} from 'invalid';
```

**Comment by MartinJohns** [comment] 2023-12-25 16:37
Duplicate of #50394.

**Closed** 2023-12-26 00:04 UTC
