### ISSUE TITLE
Constructor Documentation For Public Parameters Are Ignored

### ISSUE THREAD

**Issue by rjamesnw** [Microsoft/TypeScript#4865] opened 2015-09-18 21:59 UTC
Seems the documentation is being ignored for public constructor parameters. 

For example:
```
module Sayings {
    export class Greeter {
        greeting: string;
		/** @param {string} message A message. */
        constructor(public message: string) {
            this.greeting = message;
        }
        greet() {
            return "Hello, " + this.greeting;
        }
    }
}
```
In this case, the "message" constructor parameter should show "A message." as the documentation (on mouse over or code completion), as well as on the instance property '{Sayings}.message', but it is empty instead.  Removing the "public" modifier makes it work as expected. The workaround is to simple put `/** ... */` immediately before the parameter like so:
```
module Sayings {
    export class Greeter {
        greeting: string;
        constructor(/** A message. */ public message: string) {
            this.greeting = message;
        }
        greet() {
            return "Hello, " + this.greeting;
        }
    }
}
```
... However, this is bad design in cases where many parameters exist.

See here: http://goo.gl/vd0F7R

**Comment by danquirk** [comment] 2015-09-18 22:05
Dupe of https://github.com/Microsoft/TypeScript/issues/4566

**Closed by danquirk** 2015-09-18 22:05 UTC

**Comment by rjamesnw** [comment] 2015-09-19 17:55
Thanks Dan, I looked but didn't find anything. ;)
