### ISSUE TITLE
Typescript unable to infer property type with utility type's index signature

### ISSUE THREAD

**Issue by Kaseano** [microsoft/TypeScript#44102] opened 2021-05-15 02:54 UTC
# Bug Report

### 🔎 Search Terms

Signature Index with Utility Types

### 🕗 Version & Regression Information

This happened with all versions I've tested including nightly

### ⏯ Playground Link

I don't have a playground link unfortunately, except my stackoverflow question:
https://stackoverflow.com/questions/67542115/typescript-compiler-failing-with-different-property-types-on-omit-and-index-sign/67542334

### 💻 Code

interface Obj {
  foo: number
  bar: string
  baz: number
}
type Sub = Omit<Obj, "baz">

const obj: Obj = {foo: 1, bar: "abc", baz: 1}

function fn <K extends keyof Sub>(key: K, val: Sub[K]) {
  obj[key] = val
}

### 🙁 Actual behavior

Typescript should(?) have inferred the data type like it did without the utility type, but is requiring that data types be uniform on the utility type.

### 🙂 Expected behavior

The compiler to still be able to compute the data type

**Comment by whzx5byb** [comment] 2021-05-15 09:00
See https://github.com/microsoft/TypeScript/issues/31694#issuecomment-497688081

**Comment by MartinJohns** [comment] 2021-05-15 09:02
> I don't have a playground link unfortunately

1. Go to the playground: https://www.typescriptlang.org/play
2. Insert your code.
3. Click on "Share".
4. Paste the URL that has been copied to your clipboard here.

**Comment by Kaseano** [comment] 2021-05-15 17:09
Just realized the angle brackets disappeared.  Does that mean I can inject HTML?  That's interesting.

Here's the playground link: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgPICMBWyDeBYAKGWRgHtSAuZEAVwFt1pDj04oraGmjlWAvDvUZRCAX0JgAngAcUAZRrpkAXjR1gYADwZMAGmQAifgYB8hQgBsIYZKSxUdK3GUrIAjPtbt3nuAPfiBIQwNCAIYMCkICTRmgDSyBAAHpAgACYAzsgA1hCSpDDICugmABS5klRx+gBucBZUxQDacQC6AJS4zLZYTRWtTnUWYkA

**Comment by IllusionMH** [comment] 2021-05-17 13:42
Looks like duplicate of #33014

**Comment by RyanCavanaugh** [comment] 2021-05-20 16:44
This is the intended behavior, because this is a legal call to your function:
```ts
fn(Math.random() > 0.5 ? "foo" : "bar", 42);
```

**Closed by RyanCavanaugh** 2021-05-20 16:44 UTC
Labels: Working as Intended
