### ISSUE TITLE
Nightly builds no longer working?

### ISSUE THREAD

**Issue by myitcv** [Microsoft/TypeScript#6008] opened 2015-12-09 08:48 UTC
```
$ cd `mktemp -d`
$ npm install typescript@next
$ ./node_modules/.bin/tsc --version
Version 1.8.0-dev.20151204
```

Or at least npm isn't getting updated:

```
$ npm show typescript
...
     '1.8.0-dev.20151129': '2015-11-29T07:05:09.211Z',
     '1.8.0-dev.20151130': '2015-11-30T07:05:12.727Z',
     '1.7.3': '2015-11-30T20:37:03.883Z',
     '1.8.0-dev.20151201': '2015-12-01T07:05:19.574Z',
     '1.8.0-dev.20151202': '2015-12-02T07:06:55.221Z',
     '1.8.0-dev.20151203': '2015-12-03T07:07:00.179Z',
     '1.8.0-dev.20151204': '2015-12-04T07:06:28.563Z' },
```

Same issue as before perhaps?

**Comment by DanielRosenwasser** [comment] 2015-12-09 09:58
I'll need to look into it tomorrow morning. Thanks for the heads up.

**Comment by DanielRosenwasser** [comment] 2015-12-10 00:32
At least part of the issue is that tslint had errors we weren't supporting. As a result, TypeScript has problems building off of tslint@next. Waiting on https://github.com/palantir/tslint/pull/863 before we can do this, but in the mean time I'm publishing the builds manually.

**Comment by DanielRosenwasser** [comment] 2015-12-10 21:17
I'll wait until tonight and see if the publish works correctly before I close this one.

**Comment by DanielRosenwasser** [comment] 2015-12-11 17:33
Fixed - thanks for reporting @myitcv!

**Closed** 2015-12-11 17:34 UTC
Labels: Bug, Fixed

**Comment by myitcv** [comment] 2015-12-14 09:14
@DanielRosenwasser - thanks
