### ISSUE TITLE
Generic type destructuring & spreading

### ISSUE THREAD

**Issue by kleinerroemer** [Microsoft/TypeScript#17584] opened 2017-08-03 13:18 UTC
**TypeScript Version:**
2.4.2
**Code**

```ts
const parseValue = <T extends {}>(input: T & {val: string}): T & {val: number} => {
    return {
        ...input,
        val: parseFloat(input.val)
    }
}
```

**Expected behavior:**
The return type of _parseValue_ should be of type `T & {val: number}`
**Actual behavior:**
1.) tsc complains about spreading `input`: 

> Spread types may only be created from Object types.

even though _T_ extends _{}_.
This is also true for _T_ extends _object_ or _Object_.
2.) The return type of _parseValue_ is of type `T & {val: string & number}`, which makes no sense, since no such type exists.

**Comment by DanielRosenwasser** [comment] 2017-08-03 16:03
Hey, thanks for filing, but this seems to be a duplicate of #10727.

In the future using the issue tracker's search functionality can make it easier for us to triage issues. Thanks!

**Comment by mhegazy** [comment] 2017-08-17 17:13
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-08-17 17:13 UTC
Labels: Duplicate
