### ISSUE TITLE
Narrow function unions based on argument count

### ISSUE THREAD

**Issue by danielrentz** [Microsoft/TypeScript#28815] opened 2018-12-03 09:16 UTC
## Search Terms

narrow union type
function arguments

## Suggestion

TypeScript could narrow a union of callable types when code inspects the "length" property of the function.

## Use Cases

Playing with Express which uses middleware with (up to) 3 arguments for regular handlers, and (exactly) 4 arguments for error handlers. Code on top of this that wants to do something for the different types of handlers usually checks "handler.length" to distinguish error handlers.

## Examples

```
function test(handler: express.RequestHandler | express.ErrorRequestHandler, ...args: any[]) {

  // ignore error handlers
  if (handler.length === 4) { return; }
  
  ...

  // here, TypeScript could narrow "handler" to "express.RequestHandler", but gives error 2349
  handler(...args);
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by cpplearner** [comment] 2018-12-03 10:10
I suppose this is a breaking change, as the `length` value may disagree with the type:

```typescript
let f: (a: number) => void = (a: number, b?: string) => { };

console.log(f.length); // 2

let g: (a: number, b: undefined) => void = (a: number) => { };

console.log(g.length); // 1
```

**Comment by danielrentz** [comment] 2018-12-03 11:21
> I suppose this is a breaking change, as the `length` value may disagree with the type:

Hm, maybe I am too naive with my expectations :)

**Comment by danielrentz** [comment] 2018-12-03 11:21
> I suppose this is a breaking change, as the `length` value may disagree with the type:

Hm, maybe I am too naive with my expectations :)

**Comment by DanielRosenwasser** [comment] 2018-12-03 21:41
Duplicate of #18422 (and #20866)

**Closed** 2018-12-12 10:00 UTC
Labels: Duplicate
