### ISSUE TITLE
tsc compiler generates wrong JS code with let and casts

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#5133] opened 2015-10-06 08:19 UTC
tsc version 1.6.2

Test case:
```typescript
interface ProblemMatcher {
	owner: string;
}

interface Task {
	problemMatchers: ProblemMatcher[];
}

let matcher: ProblemMatcher = {
	owner: 'ts'
};

(matcher as any).mySpecial = true;

class Parser {
	public process() {
		let task: Task;
		for(let matcher of task.problemMatchers) {
			if ((matcher as any).mySpecial) {
				// Do something.
			}
		}
	}
}
```

The compiler generates
```javascript
var matcher = {
    owner: 'ts'
};
matcher.mySpecial = true;
var Parser = (function () {
    function Parser() {
    }
    Parser.prototype.processOne = function () {
        var task;
        for (var _i = 0, _a = task.problemMatchers; _i < _a.length; _i++) {
            var matcher_1 = _a[_i];
            if (matcher.mySpecial) {
            }
        }
    };
    Parser.prototype.processTwo = function () {
        var task;
        for (var _i = 0, _a = task.problemMatchers; _i < _a.length; _i++) {
            var matcher_2 = _a[_i];
            if (matcher.mySpecial) {
            }
        }
    };
    return Parser;
})();
```

The problematic code is If (matcher.mySpecial) ...  This must be if (matcher_2.mySpecial)

**Comment by vladima** [comment] 2015-10-06 16:30
cannot repro on the latest bits in master. Code
```ts
interface ProblemMatcher {
    owner: string;
}

interface Task {
    problemMatchers: ProblemMatcher[];
}

let matcher: ProblemMatcher = {
    owner: 'ts'
};

(matcher as any).mySpecial = true;

class Parser {
    public process1() {
        let task: Task;
        for (let matcher of task.problemMatchers) {
            if ((matcher as any).mySpecial) {
                // Do something.
            }
        }
    }
    public process2() {
        let task: Task;
        for (let matcher of task.problemMatchers) {
            if ((matcher as any).mySpecial) {
                // Do something.
            }
        }
    }
}
```
is compiled to
```javascript
var matcher = {
    owner: 'ts'
};
matcher.mySpecial = true;
var Parser = (function () {
    function Parser() {
    }
    Parser.prototype.process1 = function () {
        var task;
        for (var _i = 0, _a = task.problemMatchers; _i < _a.length; _i++) {
            var matcher_1 = _a[_i];
            if (matcher_1.mySpecial) {
            }
        }
    };
    Parser.prototype.process2 = function () {
        var task;
        for (var _i = 0, _a = task.problemMatchers; _i < _a.length; _i++) {
            var matcher_2 = _a[_i];
            if (matcher_2.mySpecial) {
            }
        }
    };
    return Parser;
})();
```

**Comment by mhegazy** [comment] 2015-10-06 17:40
looks like a duplicate of #4832

**Closed by mhegazy** 2015-10-06 17:41 UTC
Labels: Needs More Info

**Comment by dbaeumer** [comment] 2015-10-15 09:29
@vladima I saw that behavior with tsc version 1.6.2

**Comment by mhegazy** [comment] 2015-10-15 16:15
@dbaeumer can you give `typescrpipt@next` a try?
