### ISSUE TITLE
`as const` cast wrong colour when using typescript 4.5.2

### ISSUE THREAD

**Issue by Nokel81** [microsoft/TypeScript#47043] opened 2021-12-02 19:48 UTC
*TS Template added by @mjbvz*

**TypeScript Version**:4.5.2

**Search Terms**
- semantic coloring
- encodedSemanticClassifications

---

Does this issue occur when all extensions are disabled?: Yes

Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T07:59:13.865Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Create a typescript file with the line `[1, "hello"] as const`
2. Notice that `const` is green (as in a type) instead of blue since it is a keyword.

**Comment by mjbvz** [comment] 2021-12-06 19:41
Thanks for testing

Moving to TS since this coloring is coming through semantic highlighting. `const` is getting identified as a `type `

**Comment by jakebailey** [comment] 2021-12-06 22:43
I've just merged #47000, which fixes #46988; it doesn't seem to be exactly the same as it appears as though both the TS Playground and VS Code Insiders allow the hover there. That PR is about the hover being wrong, but the semantic token code shouldn't be taking that path as it's only involved in generating the tooltip's contents, not the actual symbol type.

**Comment by a-tarasyuk** [comment] 2021-12-08 13:00
There are two `format` options for `encodedSemanticClassifications-full`:
1. `2020`
2. `original`

For the `2020` TS server returns `const` as `keyword`.
For the `original` TS server returns `const` as `identifier`. Since there is no information about the `format` parameter, I suppose the problem is in the response related to `original`. I've changed that https://github.com/microsoft/TypeScript/pull/47066 to match that same response for both formats.

**Closed** 2021-12-08 18:15 UTC
Labels: Bug, Help Wanted, Good First Issue, Fix Available
