### ISSUE TITLE
Include function this argument in function signature

### ISSUE THREAD

**Issue by iskiselev** [Microsoft/TypeScript#9069] opened 2016-06-10 08:45 UTC
In JavaScript each function, except normal arguments has a special call-time bound this argument. TypeScript greatly helps to find an error when any of normal arguments passed into function is incorrect, but currently doesn't help to find an error when function called against incorrect `this`. It is even covered in [FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-does-this-get-orphaned-in-my-instance-methods).
If only TypeScript calculate (and allow override) `this` type for function, and treat it as additional argument when compare functions type, all such problems would be mitigated.
If function doesn't use any `this` fields, such additional argument simply should have `any` type.

Here is an example of source with such problem:
```
class SampleClass{
  field : string;
  f(){ return this.field};
}

var instance = new SampleClass;
var detachedF = instance.f;
detachedF();
```

In that example, TypeScript has enough info to infer, that `detachedF` could be called only over `interface {field : string}` type.

**Comment by kitsonk** [comment] 2016-06-10 09:08
Dupe of #3694 and already in master and will be released as part of TypeScript 2.0.

**Closed** 2016-06-10 09:14 UTC
