### ISSUE TITLE
JSDoc @template should introduce a type in JS

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#16411] opened 2017-06-09 19:31 UTC
**TypeScript Version:**  nightly (2.4.0-dev.20170609)

**Code**

**a.js**
```ts
/** @template T */
class C {
    /** @param {T} x */
    constructor(x) {
        /** @type {T} */
        this.x = x;
    }
}
```

**Expected behavior:**

No error.

**Actual behavior:**

```ts
app/main.js(3,17): error TS2304: Cannot find name 'T'.
app/main.js(4,17): error TS7006: Parameter 'x' implicitly has an 'any' type.
app/main.js(5,20): error TS2304: Cannot find name 'T'.
```

**Comment by dyst5422** [comment] 2017-06-13 15:49
#16485 is related

**Comment by mhegazy** [comment] 2017-09-01 00:03
duplicate of https://github.com/Microsoft/TypeScript/issues/18135

**Closed by mhegazy** 2017-09-01 00:03 UTC
Labels: Bug, Domain: JSDoc, Salsa
