### ISSUE TITLE
Computed Void is an Expected Param where Void is not

### ISSUE THREAD

**Issue by kalkronline** [microsoft/TypeScript#58231] opened 2024-04-17 20:14 UTC
### 🔎 Search Terms

void, function parameters

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about void.

### ⏯ Playground Link

[Playground Example](https://www.typescriptlang.org/play?ts=3.3.3#code/PTAEElQCwQwNwKahgO1AxKAuoC2MAHAKCIEtsEAnAMxgGMkBRTLAZ1AG8jQfRy4YAG1IATGFgQAuUHAD2o7r0oIYrVqQDmKaSgCuuAEZUiAXxIgIODQjahdrBCL5pcAT2QECwuuNKy0rLKUWDCgwgDWSFhQpKySJNS6KHRYfgEIKCIAPIzoAB4SmeyRrrLUoMwZbAB8ABQYVdKMADR4CKwaTSysANqMALoAlJxmRInJqf6gynRwOfmFIsUIpeWV2Kx1DdhNrXQG0rW47Z0V3X1DoAC81TLyIsMcoxaQqqz6jqDRSDAGsoigQKCXSTNCxdAAR10Qi+slA-yoglkMBE5A0CSSKTS8IA+g5MvUWNIAET8ISicQIYmtY4daRyUSDen3MaY0G4-EiQmNUDE5RvTQoaltOmgPSGKhMu4KcZYqayPEZLnbLDSVhYShomknaSoVyPUay9kKmZwbk7Xlk4RiCTC-aHYY3aUPZkytnYk0IWbm1W8-lqQV2g6gI46sX6IyUR23Bku52siYenGmn1qjVa0D2kO00566POg3mMAAIRBXygVCQDgQuHYWDhRmQYLUuiQAHdSNFy0g6LJcAQQZ9Y6AjdiCDBKDBjhJKKBJLUSArObU+SoA1phQBmABMgwA3ERl6uBRvWjv94vFQTSSgBNbKcSL0erRTbcMLIw8gQvRInNvkJQGgfBsrQGGWGiyDgACMAB0RagAAskEVa6HQdDkCkgiuNI0TgqwUCyLoghOCgkHoJQlBBDB1EkL2-Y4nQ4RZLGdQXqOUx0QQDFMQAKnUvo8YWRAWNRMFGD49hRDE7AiLI7QoAA5DgJCxtxtRse6UyqYxtS+rGQlAA)

### 💻 Code

```ts
// I have an event map

interface Events {
    invalidate: void
    reassign: number
}

// It gets used in my application sorta like this:

function send<E extends keyof Events>(event: E, mesg: Events[E]) {}

function recv<E extends keyof Events>(event: E, cb: (mesg: Events[E]) => void) {}

// I assumed the above solution is equal to overloading

function o_send(event: "invalidate", mesg: void): void
function o_send(event: "reassign", mesg: number): void
function o_send(event: string, mesg: any) {}

function o_recv(event: "invalidate", cb: () => void): void
function o_recv(event: "reassign", cb: (mesg: number) => void): void
function o_recv(event: string, cb: (mesg: any) => void) {}

// But there seems to be an issue with the computed void function parameter :(

o_send("reassign", 32);
send("reassign", 32);

o_send("invalidate");
send("invalidate") // Expected 2 arguments, but got 1.

// More succinctly: this should not error...

comp_ck<void>();
function comp_ck<T>(t: T) {}

// ...because this doesn't 

void_ck();
function void_ck(t: void) {}


```

### 🙁 Actual behavior

The computed void is expected in function parameters where the static void is not.

### 🙂 Expected behavior

I expected this to work the same way in both cases, whether void was computed or not.

**Comment by MartinJohns** [comment] 2024-04-17 20:34
Duplicate of #39600.

**Closed** 2024-04-17 20:58 UTC
Labels: Duplicate

**Comment by MartinJohns** [comment] 2024-04-17 21:18
> ```ts
> // I assumed the above solution is equal to overloading
> ```

That assumption is wrong. Keep in mind that `E` can be a union type as well. It's perfectly valid that the type for `E` is `"invalidate" | "reassign"`. That also means it's possible to provide an *invalid* `mesg` for the `event`.

**Comment by kalkronline** [comment] 2024-04-17 21:32
@MartinJohns Yes that is correct, I do account for this through these

```ts
// helper types
// https://stackoverflow.com/questions/50374908/transform-union-type-to-intersection-type
type UnionToIntersection<U> = 
	(U extends any ? (k: U) => void : never) extends ((k: infer I) => void) ? I : never

// https://stackoverflow.com/questions/53953814/typescript-check-if-a-type-is-a-union
type IsUnion<T, U extends T = T> =
    (T extends any ?
    (U extends T ? false : true)
        : never) extends false ? false : true

export type OneOf<T, K> = IsUnion<K> extends false ? keyof T : never;

recv<E extends OneOf<Events, E>>(event: E, cb: (mesg: Events[E]>) => void) {}
```

I meant equal in the context of the problem, which is how they handle void.

**Comment by MartinJohns** [comment] 2024-04-17 21:37
`UnionToIntersection` has been called an I'll formed type
