### ISSUE TITLE
Union Type Guard Breaks If Expression Has Property

### ISSUE THREAD

**Issue by Joncom** [Microsoft/TypeScript#7288] opened 2016-02-29 03:28 UTC
**TypeScript Version:** 

1.8.2

**Code**

```ts
interface Foo {
    property: (boolean | { bar: number })
}

var foo: Foo = {
    property: { bar: 123 }
};

var p = foo.property;
if (typeof p === 'object') {
	// This works fine!
	console.log(p.bar); // Prints "123"
}

if (typeof foo.property === 'object') {
	// This line produces the following compilation error:
	// "Property 'bar' does not exist on type 'boolean | { bar: number; }'"
    console.log(foo.property.bar);
}
```

**Expected behavior:**

I expected `if (typeof foo.property === 'object') {` to be a valid type guard.

**Actual behavior:** 

It's not.

**Comment by yortus** [comment] 2016-02-29 05:05
Duplicate of #3812?

**Comment by DanielRosenwasser** [comment] 2016-02-29 08:30
Thanks for digging that up @yortus!

**Closed** 2016-02-29 08:31 UTC
Labels: Duplicate
