### ISSUE TITLE
No validation while destructuring array in object of definite type

### ISSUE THREAD

**Issue by carino1** [microsoft/TypeScript#51148] opened 2022-10-12 10:28 UTC
# Bug Report

### 🔎 Search Terms
google
stackoverflow
https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-structural-typing

### 🕗 Version & Regression Information
This is the behavior in every version I tried, and I reviewed all the FAQ for entries

### ⏯ Playground Link

[[
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&target=99&noImplicitOverride=false#code/JYOwLgpgTgZghgYwgAgLIE8AqEDOYCS4E8SyA3gFDLXJwD8AXMnlKAObIA+yIArgDb8A3FRoAjRszCsQHbn0EiAvhQoQAHgAcA9lDDIYvEAjDBtIZAFssuMADEjJsyAAUFAJRMM2PIUgkUShpkBHM8ZDE4HAgvG18iAOQAXnJRYOo4JgByAEYsgBo09LFsgCYCoqURItCQcLgoKGTkAG1kXIL28uQAXWrgqAgwXigLIPTqADppyOjCianphqhKiiUgA)](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&target=99&noImplicitOverride=false#code/JYOwLgpgTgZghgYwgAgLIE8AqEDOYCS4E8SyA3gFDLXJwD8AXMnlKAObIA+yIArgDb8A3FRoAjRszCsQHbn0EiAvhQoQAHgAcA9lDDIYvEAjDBtIZAFssuMADEjJsyAAUFAJRMM2PIUgkUShpkBHM8ZDE4HAgvG18iAOQAXnJRYOo4JgByAEYsgBo09LFsgCYCoqURItCQcLgoKGTkAG1kXIL28uQAXWrgqAgwXigLIPTqADppyOjCianphqhKiiUgA)

### 💻 Code
```ts
interface MyTestInteface {
    a?: string | null;
    b?: string | null;
}

export function myTestFunction(
): MyTestInteface {
    const base: MyTestInteface = {
        a: '1',
        b: '2',
    };

    const arr = [ '1', '2' ];

    return {
        ...base,
        ...arr
    }
}
```

### 🙁 Actual behavior
No typescript error in return statement

### 🙂 Expected behavior
Array is destructuring in object, that should be MyTestInteface. Expecting an error here

**Comment by MartinJohns** [comment] 2022-10-12 11:39
Duplicate of #49667 / #9726.

And the syntax you're using is called "spreading", not destructuring.

**Closed** 2022-10-15 18:00 UTC
Labels: Duplicate
