### ISSUE TITLE
Assigning number values to Record<string, number> will fail in "in" loops

### ISSUE THREAD

**Issue by aronallen** [microsoft/TypeScript#34993] opened 2019-11-08 13:32 UTC
**TypeScript Version:** 
Version 3.7.2

**Search Terms:**
Generics
Record
Addition
Generics
Number

**Code**

```ts
export function add<T extends Record<string, number>>(a: T, b: Partial<T>) {
    for (let key in b) {
        a[key] = b[key]; // works
        a[key] = a[key] + b[key]; //Type 'number' is not assignable to type 'T[Extract<keyof T, string>]'
        a[key] = 0; // Type '0' is not assignable to type 'T[Extract<keyof T, string>]'.
        b[key] = 0; // Type '0' is not assignable to type 'T[Extract<keyof T, string>]'.
    }
}
```

**Expected behavior:**

I would expect all four statements in the loop to be valid.

**Actual behavior:**

In the second statement the value is converted to number this causes type check to fail.
In the third statement the value is inferred to zero this causes the type check to fail.
In the fourth statement the value is inferred to zero this causes the type check to fail.

**Comment by jcalz** [comment] 2019-11-08 15:42
Duplicate of #13442

**Comment by fatcerberus** [comment] 2019-11-08 15:43
`T extends Record<string, number>` doesn't require `T` to have an index signature, or even for the properties to be typed as `number`.  You could just as well call the function like this:

```ts
type Fooey = {
    foo: 1 | 2 | 3;
    bar: 1 | 2 | 3;
    baz: 1 | 2 | 3;
};

let x: Fooey = { foo: 1, bar: 2, baz: 3 };
let y: Partial<Fooey> = { foo: 2 };
add(x, y);
```

The type system knows this, and doesn't let you assign arbitrary numbers into `T`.

**Closed** 2019-11-11 20:00 UTC
Labels: Working as Intended

**Comment by aronallen** [comment] 2019-11-18 10:55
@fatcerberus thanks for your reply.

I am a bit unsure of how to type this accurately.

I have a method that accepts to objects, which must be ```Record<string, number>```.
and B must contain a subset or all of the properties of A.

How would I type this in a way that would let me assign new values to A that is the sum of that property in A and B?
