### ISSUE TITLE
Please open-source your internal collection/shape... libs

### ISSUE THREAD

**Issue by MikeMitterer** [Microsoft/TypeScript#30955] opened 2019-04-16 10:34 UTC
## Search Terms
collections internal libs shapes

## Suggestion
OK, OK + sorry I know this request does not agree with the TSs Design Goals but I think from time to time you have to rethink if the goals are still right...

However - TS is a really cool thing with a very fancy typesystem but it has, for example, no Rectangle or Dictionary class. In my opinion this does not fit. We have 2019 and I'm forced to write such basic classes like a Dictionary, a LinkedList or a Rectangle... (with the usual methods) Really?

You could argue this is not part of the language - OK, but take Kotlin or other modern languages - they provide such things as part of their language. 

Another thing is that I'm sure that you (MS) have all those base classes internally - could you please!!!! open-source and standardise these things?

**Comment by MartinJohns** [comment] 2019-04-16 11:30
Duplicate of #30827.

**Comment by RyanCavanaugh** [comment] 2019-04-16 15:46
Why do we even write things down

**Closed by RyanCavanaugh** 2019-04-16 15:46 UTC
Labels: Duplicate
