### ISSUE TITLE
base64/hex methods missing from `Uint8Array`

### ISSUE THREAD

**Issue by printfn** [microsoft/TypeScript#60743] opened 2024-12-11 20:39 UTC
### ⚙ Compilation target

ESNext

### ⚙ Library

ESNext

### Missing / Incorrect Definition

[`Uint8Array.fromBase64()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/fromBase64)
[`Uint8Array.fromHex()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/fromHex)
[`Uint8Array.prototype.setFromBase64()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/setFromBase64)
[`Uint8Array.prototype.setFromHex()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/setFromHex)
[`Uint8Array.prototype.toBase64()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/toBase64)
[`Uint8Array.prototype.toHex()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/toHex)

These functions are available as of Firefox 133 and Safari 18.2.

### Sample Code

```TypeScript
new TextEncoder().encode('Hello World').toBase64()
// "SGVsbG8gV29ybGQ="
```

### Documentation Link

MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/toBase64

TC39 Proposal: https://github.com/tc39/proposal-arraybuffer-base64

Firefox release notes: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/133#javascript

Safari release notes: https://developer.apple.com/documentation/safari-release-notes/safari-18_2-release-notes#JavaScript

**Comment by MartinJohns** [comment] 2024-12-11 20:43
Duplicate of #60612. Why open another issue?

**Closed** 2024-12-11 20:56 UTC

**Comment by aryzing** [comment] 2024-12-26 17:29
Seems it's now [available in two major engines](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/toHex#browser_compatibility) no? Bun supports this too.
