### ISSUE TITLE
Turning off `noImplicitAny` causes the inferred type of an untyped array to be `never[]`

### ISSUE THREAD

**Issue by yifanwww** [microsoft/TypeScript#50505] opened 2022-08-29 09:13 UTC
# Bug Report

When `strictNullChecks` is enabled, turning off `noImplicitAny` causes the inferred type of an untyped array to be `never[]`, not `any[]` anymore.

My code cannot pass the compilation anymore if I disable `noImplicitAny` for some special reasons.

### 🔎 Search Terms

noImplicitAny, strictNullChecks

### 🕗 Version & Regression Information

- This is a crash
- This is the behavior in every version I tried: `4.7.4`, `nightly`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgJwTAvDA2gXQNwChEIB0ADgK4QAWAFAN4wA2cARgKb0BcMA5AIwBMAZi4AaGADc49Ui078BMAL4BKfEjxA)

Turn off `noImplicitAny` only and you will see the error (if you also turn off `strictNullChecks` the error will disappear).

### 💻 Code

```ts
const arr = [];
arr.push({ label: '123', value: 123 })
arr;
```

### 🙁 Actual behavior

| case | `strictNullChecks` | `noImplicitAny` | result |
| :-: | :-: | :-: | :- |
| 1 | off | off | no errors |
| 2 | on | off | type check error occurs |
| 3 | on | on | no errors |

- In case 1 and case 3: The type of `arr` is inferred as `any[]` initially, so it's ok to push that object into it. On line 3, the type become more specific `{ label: string; value: number }[]`.
- In case 2: The type of `arr` is inferred as `never[]` initially, which prevents us from pushing anything into it. On line 3, the type is still `never[]`.

Is there any specific reason that, the type of that `arr` should be inferred as `never[]` only when `strictNullChecks` is on but `noImplicitAny` is off?

When `noImplicitAny` is off, I can accept that, the inferred type will be changed from `any[]` to `never[]`, after enabling `strictNullChecks`. (case 1 -> case 2)

But I really don't understand that
- when `strictNullChecks` is on, the inferred type will be changed from `never[]` back to `any[]`, after enabling `noImplicitAny`; (case 2 -> case 3)
- (in another words) when `strictNullChecks` is no, the inferred type will be changed from `any[]` to `never[]`, after disabling `noImplicitAny`. (case 3 -> case 2)

### 🙂 Expected behavior

Whatever `noImplicitAny` is enabled or disabled, the behaviours should be the same: both are wrong code, or both are correct code.

**Comment by MartinJohns** [comment] 2022-08-29 12:00
Duplicate of #36987. Used search terms: `noImplicitArray never array in:title`

**Comment by yifanwww** [comment] 2022-08-29 16:55
@MartinJohns Thanks.

Could you please also provide the reason for the backward compatibility of this particular design?

It works as intended, it's ok, but I still want to know why.

**Closed** 2022-08-31 18:00 UTC
Labels: Duplicate
