### ISSUE TITLE
no error when using spread operator with object of incorrect type

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#41698] opened 2020-11-26 12:10 UTC
**TypeScript Version:**  4.2.0-dev.20201126

**Search Terms:**
spread operator type safe
**Code**

```ts
type Foo = {bar: number}
let foo: Foo = {bar: 1}

foo.baz = 1 //Property 'baz' does not exist on type 'Foo'.
foo = {...foo, baz: 1 } //Type '{ baz: number; bar: number; }' is not assignable to type 'Foo'. Object literal may only specify known properties, and 'baz' does not exist in type 'Foo'.
foo = {...foo, ...{baz: 1} } // no error
```

**Expected behavior:**
error on the last line as property `baz` does not exist on type `Foo`
**Actual behavior:**
no error
**Playground Link:** 
https://www.typescriptlang.org/play?ts=4.2.0-dev.20201126#code/C4TwDgpgBAYg9nKBeKBvARgQwE4C4oB2ArgLboTYC+AsAFAA2EwUAZgvvIihjvgIw1adNnAB0WAF7IofKAHo5ABWxxI2UFADkkzVAAmcCAGdCcZhAAeASyPM4BKKEhbOm0cITTUonyIA0UJL8UJTycgAq4NCaqIGYEvjEZBQA3HF4hKTk2GmUujamzJhGRlYA5gSY6IyOiE7RrqJQAPLoAFYQAMbM9FbAFJj0UCSYIFD29GNGkJ1WLGMA1gRwAO4OYCpqwFbGAZgEelo6+oYmy+bWtlBWDvUuCG4eXGg+ov5QrzwJMqGhCqZQCgqbBAA
**Related Issues:**

**Comment by MartinJohns** [comment] 2020-11-26 12:25
Duplicate of #13778.

On a side-note: This is still type-safe. Extra-properties on objects are allowed. Excess property checks are more of a linter feature.

**Closed** 2020-12-05 18:00 UTC
Labels: Duplicate
