### ISSUE TITLE
Expand quick info information for imports

### ISSUE THREAD

**Issue by jwbay** [Microsoft/TypeScript#19364] opened 2017-10-20 02:23 UTC
**TypeScript Version:**  2.6.0-dev.201xxxxx

**Code**

foo.ts
```ts
export class Test<T extends object> {
}
```

bar.ts
```ts
import { Test } from './foo';

Test/* 1 */;
```

**Expected behavior:**
Quick info at 1 displays full type information like this:
![image](https://user-images.githubusercontent.com/1320447/31801869-dfd6bdf2-b518-11e7-87d4-c1054ffaa856.png)
Ideally with a prefix or something to indicate it's an import.

**Actual behavior:**
It only displays `import Test` on hover.

I debated opening this because Peek Definition exists, but that only works if your cursor is on the identifier. When you're scrolling through unfamiliar code, I think it'd be really nice to see fully resolved types as you hover over stuff without having to give up your cursor position, especially if you're jumping around different files. Even if it requires a little 'Loading...' tag first.

This seems like it should have a duplicate or two but I didn't find anything.

**Comment by DanielRosenwasser** [comment] 2017-10-20 07:03
Duplicate of #5515?

**Closed** 2017-10-20 15:01 UTC
