### ISSUE TITLE
Certificate problem

### ISSUE THREAD

**Issue by kwhjvdkamp** [Microsoft/TypeScript#22676] opened 2018-03-17 21:04 UTC
![invalidcertificate](https://user-images.githubusercontent.com/9660415/37559942-20e9cc0e-2a2f-11e8-9f5d-a6c8584a298b.png)

**Comment by RyanCavanaugh** [comment] 2018-03-17 21:12
Duplicate of #22663, please search for existing issues before logging new ones.

**Comment by kwhjvdkamp** [comment] 2018-03-17 21:28
Sorry!

**Closed** 2018-03-19 04:55 UTC
Labels: Duplicate
