### ISSUE TITLE
Spread operator dont fill an empty array

### ISSUE THREAD

**Issue by lucasteles** [Microsoft/TypeScript#28220] opened 2018-10-29 23:01 UTC
**TypeScript Version:**  3.2.0-dev.20181027

**Search Terms:** array, spread

**Code**

```ts
const values = [...Array(2)]
```

**Expected behavior:**
The `values` should be an array with `[undefined, undefined]`

**Actual behavior:**
It return a true empty array (like an `Array(2)`) which cant be mapped

**Playground Link:** [here](https://www.typescriptlang.org/play/index.html#src=%0Aconst%20values%20%3D%20%5B...Array(2)%5D%0A%0A%0A)

**Comment by andy-ms** [comment] 2018-10-30 00:16
Duplicate of #8856

**Closed** 2018-12-13 18:00 UTC
Labels: Duplicate
