### ISSUE TITLE
Introducing error in project requires IDE restart to pick up

### ISSUE THREAD

**Issue by evmar** [Microsoft/TypeScript#11720] opened 2016-10-18 22:59 UTC
**TypeScript Version:**  2.0.3
**VSCode**: 1.6.1
**Code**

1) Create a two-file project.

`magic.d.ts`:
```ts
declare var magic;
```

`foo.ts`:
```ts
magic = 3;
```

`tsconfig.json` (standard tsconfig, with a files block referencing the above two files):
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false
    },
    "files": [
        "foo.ts",
        "magic.d.ts"
    ]
}
```
Load this up into VSCode; everything's fine.

2) Now create a new file:
`foo2.ts`:
```ts
magic = 3;
```
Red squigglies as expected, because it doesn't know about the global declaration.

3) Now edit `foo.ts` to add:
```ts
import './foo2';
```
Errors are fixed.

4) Now comment out that import, reintroducing the error.

**Expected**: error in foo2.ts reappears.
**Actual**: project is error clean until you restart the IDE.

**Comment by vladima** [comment] 2016-10-18 23:15
tried the nightly build and this is not the behavior I'm seeing: if I comment out import then indeed error did not appear, however I got error squiggles once I edit `foo2.ts`. Reason why this is happening - currently VSCode does not re-query diagnostics for file if file was not changed, We already have [workitem](https://github.com/Microsoft/TypeScript/issues/11229) to push notifications from the server in case if they should be updated on the editor side.

**Comment by evmar** [comment] 2016-10-18 23:37
I can confirm that if I edit `foo2.ts`, the squigglies reappear.  Feel free to close this as a dup of your work item if that's all you need.

**Comment by vladima** [comment] 2016-10-18 23:49
duplicate of #11229

**Closed by vladima** 2016-10-18 23:49 UTC
Labels: Duplicate

**Comment by mihailik** [comment] 2017-06-19 17:31
I believe this error is likely triggered by syntactic JSON error in tsconfig.json.

When you edit tsconfig.json with autosave enabled, intermediate edits result in syntactically incorrect JSON. And that crashes compiler. Not errors in TS files, but errors in TSCONFIG.
