### ISSUE TITLE
Provide an abilty to define custom path to tsconfig.json

### ISSUE THREAD

**Issue by max619** [microsoft/TypeScript#50574] opened 2022-08-31 18:39 UTC
# Suggestion

## 🔍 Search Terms

`tsconfig.json`; `custom`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

I'm would like to use VSCode when working on my projects, however it's impossible to setup VSCode (and language server) for a project with multiple ts configurations and/or shared code between those configuration.

## 💻 Use Cases

For example user have such a project structure:

```
├── src
│   ├── some.class.client.ts
│   └── some.class.server.ts
├── tsconfig.client.json
├── tsconfig.server.json
```

And would like to have tsconfigs assined in this way:

```
├── src
│   ├── some.class.client.ts << tsconfig.client.json
│   └── some.class.server.ts << tsconfig.server.json
├── tsconfig.client.json
├── tsconfig.server.json
```

This is impossible to achive in current implemntation, moreover it's impossible to have a name of tsconfig other then `tsconfig.json`. And workaround is quite exhaustive to do, you need to create `tsconfig.json` which extends one of others and modify it every time you would like to work on client side or server side.

## ⭐ Suggestion

Create a mechanism in language server that would allow users to specify which tsconfigs should be used for specific files or directories.

I have found out that function reponsible for selection of configs is [forEachConfigFileLocation](https://github.com/microsoft/TypeScript/blob/394f51aeed80788dca72c6f6a90d1d27886b6972/src/server/editorServices.ts#L1836)

So I suggest to provide a way to configure it in such a way that user can customize it's behaviour for every use case.
I came up with possible solution, we can provide config with wildcards (or regexes) of paths and corresponding paths of tsconfigs. For example:

```json
{
    "src/**/*.client.ts": "tsconfig.client.json",
    "src/**/*.server.ts": "tsconfig.server.json"
}
```

In my example it would give expected result, such as:
```
├── src
│   ├── some.class.client.ts << tsconfig.client.json
│   └── some.class.server.ts << tsconfig.server.json
├── tsconfig.client.json
├── tsconfig.server.json
```

With such config for every file that is matching mask language server would search for corresponding config name in all parent directories in the same way it currently works, but with different filenames. If path is not matching any wildcard project resolving would fallback to default algorithm.

However it is possible to specify full path to tsconfig to cover such scenarios

```json
{
    "src/**/*.client.ts": "${workspaceFolder}/configs/tsconfig.client.json",
    "src/**/*.server.ts": "${workspaceFolder}/configs/tsconfig.server.json"
}
```

Would result in such a selection of configs

```
├── configs
│   ├── tsconfig.client.json
│   └── tsconfig.server.json
├── src
│   ├── some.class.client.ts << ${workspaceFolder}/configs/tsconfig.client.json
│   ├── some.class.server.ts << ${workspaceFolder}/configs/tsconfig.server.json
│   └── some.class.common.ts << ${workspaceFolder}/tsconfig.json
├── tsconfig.json
```

Also such use case might be useful:

```json
{
    "src/**/*.client.ts": ["tsconfig.json", "${workspaceFolder}/configs/tsconfig.client.json"],
    "src/**/*.server.ts": ["tsconfig.json", "${workspaceFolder}/configs/tsconfig.server.json"]
    "src/**/*.ts": ["tsconfig.json"],
}
```

Would result in following selection of configs

```
├── configs
│   ├── tsconfig.client.json
│   └── tsconfig.server.json
├── src
│   ├── some.class.client.ts << ${workspaceFolder}/configs/tsconfig.client.json
│   ├── some.class.server.ts << ${workspaceFolder}/configs/tsconfig.server.json
│   └── some.class.common.ts << ${workspaceFolder}/tsconfig.json
│   ├── lib
│   │   ├── some.class.client.ts << ${workspaceFolder}/src/lib/tsconfig.json
│   │   ├── some.class.server.ts << ${workspaceFolder}/src/lib/tsconfig.json
│   │   └── tsconfig.json
├── main.ts << ${workspaceFolder}/tsconfig.json
├── tsconfig.json
```

As far as noticed the solution would solve all issues mentioned in links bellow.
I can implement it myself an create a PR, however I need to get approvement for such design. 

## Other issues
[#11224](https://github.com/microsoft/vscode/issues/12463)
[#18140](https://github.com/Microsoft/vscode/issues/18140)
[#12463](https://github.com/Microsoft/vscode/issues/12463)

**Comment by andrewbranch** [comment] 2022-09-07 16:25
I appreciate the thought that you put into a a solution, but for organizational purposes I think it’s a duplicate of #11224. Thanks!

**Closed** 2022-09-09 18:00 UTC
Labels: Duplicate

**Comment by max619** [comment] 2022-09-10 18:33
@andrewbranch yeah, I totally get it, but #11224 is closed and new comments are fobidden.

Is it possible that I get some response from dev team regarding my idea? As I mentioned before, I can do it myself, but need to get some kind of approvement. (I don't want to waste my time making PR if it wouldn't be merged)
