### ISSUE TITLE
jsdoc: defining object format with @typedef then using it with @type doesn't seem to work

### ISSUE THREAD

**Issue by balupton** [Microsoft/TypeScript#15812] opened 2017-05-13 04:04 UTC
**TypeScript Version:**  2.3.2

**Code**

example repository: https://github.com/balupton/typescript-typedef-object-issue

`source/index.js`:
```javascript
'use strict'

/**
 * @typedef {Object.<string, function(*):boolean>} TypeMap
 */

/**
 * Get the type of the value in lowercase
 * @param {*} value
 * @param {TypeMap} [customTypeMap] a custom type map
 * @returns {?string}
 */
function getType (value, customTypeMap) {
   // Cycle through our type map
   for (const key in customTypeMap) {
      if (customTypeMap.hasOwnProperty(key)) {
         if (customTypeMap[key](value)) {
            return key
         }
      }
   }

   // No type was successful
   return null
}

/**
 * Get the type of the value in lowercase
 * @param {*} value
 * @param {Object.<string, function(*):boolean>} [customTypeMap] a custom type map
 * @returns {?string}
 */
function getTypeWorkaround (value, customTypeMap) {
   // Cycle through our type map
   for (const key in customTypeMap) {
      if (customTypeMap.hasOwnProperty(key)) {
         if (customTypeMap[key](value)) {
            return key
         }
      }
   }

   // No type was successful
   return null
}
```

`tsconfig.json`:

``` json
{
   "include": [
      "source/*"
   ],
   "compileOnSave": true,
   "compilerOptions": {
      "allowJs": true,
      "checkJs": true,
      "strict": true,
      "alwaysStrict": true,
      "module": "commonjs",
      "newLine": "LF",
      "target": "es2015",
      "outDir": "es2015",
      "lib": [
         "esnext"
      ],
      "rootDir": ".",
      "rootDirs": [
         "."
      ]
   }
}
```

**Expected behavior:**
Expected that `getType` would use the `TypeMap` type definition correctly.

**Actual behavior:**
I get this error message on compile:

```
> tsc

source/index.js(17,14): error TS7017: Element implicitly has an 'any' type because type '{}' has no index signature.
```

**VSCode Screenshots:**

![img_4826](https://cloud.githubusercontent.com/assets/61148/26022305/39c3014e-37d4-11e7-8c00-005d6561e130.JPG)

![img_4827](https://cloud.githubusercontent.com/assets/61148/26022308/481fc2e0-37d4-11e7-90fc-57888a445d1c.JPG)

**Comment by mhegazy** [comment] 2017-05-20 00:13
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/15105

**Comment by mhegazy** [comment] 2017-06-04 21:08
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-06-04 21:08 UTC
Labels: Duplicate
