### ISSUE TITLE
Typeguard of undefined check not working on array property

### ISSUE THREAD

**Issue by elicym** [Microsoft/TypeScript#22199] opened 2018-02-27 09:03 UTC
**Search Terms:** 
typeguard collection array undefined

**Code**

```ts
let c: { tiles: { x?:number }[]} = { tiles:[]};
for (let i = 0; i < c.tiles.length; i++) {
    if (c.tiles[i].x)
        Math.max(1, c.tiles[i].x); //compiler error 'Type undefined is not assignable to type number.'
}
```
Turn on `strictNullChecks`.

**Expected behavior:**
`if (c.tiles[i].x)` should act as a typeguard, and when it is referred to on the next line, it should be treated as type `number`.

**Actual behavior:**
It is treated as `number|undefined`.

**Playground Link:**  
[link](https://www.typescriptlang.org/play/index.html#src=let%20c%3A%20%7B%20tiles%3A%20%7B%20x%3F%3Anumber%20%7D%5B%5D%7D%20%3D%20%7B%20tiles%3A%5B%5D%7D%3B%0D%0Afor%20(let%20i%20%3D%200%3B%20i%20%3C%20c.tiles.length%3B%20i%2B%2B)%20%7B%0D%0A%20%20%20%20if%20(c.tiles%5Bi%5D.x)%0D%0A%20%20%20%20%20%20%20%20Math.max(1%2C%20c.tiles%5Bi%5D.x)%3B%0D%0A%7D%0D%0A)
Turn on `strictNullChecks`.

**Comment by sylvanaar** [comment] 2018-02-27 14:50
Workaround:

``typescript
let c: { tiles: { x?:number }[]} = { tiles:[]};
for (let i = 0; i < c.tiles.length; i++) {
    let x = c.tiles[i].x
    if (x)
        Math.max(1, x);
}
```

**Comment by andy-ms** [comment] 2018-02-27 15:42
Duplicate of #10530

**Closed** 2018-03-13 17:54 UTC
Labels: Duplicate
