### ISSUE TITLE
Type of outer variable inside functions is not affected by narrowing in outer scope

### ISSUE THREAD

**Issue by u130b8** [microsoft/TypeScript#60046] opened 2024-09-24 16:16 UTC
### 🔎 Search Terms

type inside function, scope variable, type narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about this

### ⏯ Playground Link

https://www.typescriptlang.org/play/?target=99&ts=5.7.0-dev.20240924#code/DYUwLgBAtghgngIxAZTAJwJYDsDmAuCAZ3WxwB8sBXYYCAXgipoG4AoWRFE3eiAIgAefNu3hJUmXGwD00iAD0A-K1YBjAPZZiEAGYBGXgAoAlPQB8EAN6sIt6GK6ScbOxFkLlAXxU7KWVWAYmroATCZWNnYc4tzOkbbuSqyeQA

### 💻 Code

```ts
let maybeString: string | null = null;
maybeString = "x";

maybeString;
// ^? let maybeString: string

const f1 = () => {
    maybeString;
    // ^? let maybeString: string | null
}

function f2() {
    maybeString;
    // ^? let maybeString: string | null
}
```

### 🙁 Actual behavior

The type of `maybeString` in both functions is `string | null` .

### 🙂 Expected behavior

The type of `maybeString`  in both functions should be `string` as it was narrowed before these functions were defined.

**Comment by MartinJohns** [comment] 2024-09-24 16:40
Duplicate of #9998.

**Closed** 2024-09-27 01:32 UTC
Labels: Duplicate
