### ISSUE TITLE
outline view is always slow and loading, code cannot be folded.

### ISSUE THREAD

**Issue by qdechochen** [microsoft/TypeScript#28389] opened 2018-07-18 03:01 UTC
Issue Type: <b>Bug</b>

- VSCode Version: 1.25.1
- OS Version: Mac OS 10.13.5

Steps to Reproduce:

Since my last post was closed, I have to post again. 
**I need to say first: I have disabled all extensions, and I've never installed the local history extension.**

1. open a js file.
2. change something, and save
3. outline is loading..... and code cannot be folded until outline view is ready (nothing happends when  click -/+. Sometimes, the fold symbols( -, +) disappear, and when outline view is ready, they will be back.

it's annoying especially when i want to see some code which is folded, and i can't unfold it.

<img width="503" alt="wx20180717-130338 2x" src="https://user-images.githubusercontent.com/1181011/42797623-a13b02ea-89c2-11e8-9f46-a37ca1ed8030.png">

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (1.65GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by mjbvz** [comment] 2018-11-07 01:04
I verified this in the latest typescript version using: https://github.com/qdechochen/osql.git

It includes a some very large and highly nested files which cause the `navtree` request to be queued for a very long time. I confirmed that this seems to be happening in the tsserver based on cpu usage

**Comment by rbuckton** [comment] 2018-11-26 22:09
@sheetalkamat: Can you verify whether this might also be resolved by #28629, given the large number of paths involved in the project? If it isn't, then either you or I can take a look at this for 3.3.

**Comment by sheetalkamat** [comment] 2018-11-29 20:43
@mjbvz @qdechochen The link to git repository is not working. Do I need to do anything special?

**Comment by sheetalkamat** [comment] 2018-11-30 18:32
@qdechochen I don't see any lag with typescript@next . Can you give it a try. Here is documentation on 
using [typescript nightly drop](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code).

**Comment by sheetalkamat** [comment] 2018-11-30 23:32
Assigning to @sandersn since I found out that tsserver gets stuck in suggestion diagnostics of ` ast-translator.js ` and upon breaking noticed that its doing some narrowing. @sandersn to look at improving perf or may be handling cancellation token if needed.

**Comment by sandersn** [comment] 2018-11-30 23:46
@sheetalkamat narrowed the problem to the checker.

From discussion with @sheetalkamat we came up with a few things for investigation:

1. Does this repro with tsc as well?
2. Does this repro with 3.1 or earlier?
3. The code consists of a number of small, non-nested functions. It should check the cancellation token fairly often. I suspect a bug in auto type analysis, which is backed by control flow. This is *probably* another case where we should not be using checkExpressionCached, but checkExpression instead.

**Closed** 2019-08-14 21:09 UTC
Labels: Bug, Domain: Performance, Domain: TSServer, Fix Available
