### ISSUE TITLE
[JS] IntelliSense disregards properties if defined via Revealing Prototype Pattern

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#10794] opened 2016-09-08 22:14 UTC
_From @odonyde on September 7, 2016 1:55_
- VSCode Version: 1.4.0
- OS Version: Windows 10 Pro 64bit 1607
- Language: JavaScript

Likewise issue #11450 concerning the Prototype Pattern with assigned object literal, I observed that IntelliSense also disregards any properties if they are defined using the Revealing Prototype Pattern. For example, IntelliSense does not show property 'greet' in the screenshot below.
![vscode-intellisense-03](https://cloud.githubusercontent.com/assets/21695902/18296719/0c60c918-7482-11e6-9736-393a5d8a6134.jpg)

_Copied from original issue: Microsoft/vscode#11610_

**Comment by waderyan** [comment] 2016-09-08 22:14
Hey @odonyde thank you for opening these issues! As this falls onto TypeScript language service, I am moving it there.

**Comment by yortus** [comment] 2016-09-09 01:03
The code in the screenshot is not a valid releaving prototype pattern. `Person.prototype` is assigned a function, when it should be assigned the result of immediately executing the function (ie an IIFE).

Not sure it that solves the Intellisense problem though.

**Comment by odonyde** [comment] 2016-09-09 12:03
@yortus Oops, thanks for the catch! I corrected the sample code (see screenshot below). The IntelliSense issue persists.
![vscode-intellisense-04](https://cloud.githubusercontent.com/assets/21695902/18386254/0cc0598c-766c-11e6-92cb-5525ca966911.jpg)

**Comment by mhegazy** [comment] 2016-12-16 00:38
this looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/10736.

**Closed by mhegazy** 2016-12-16 00:38 UTC
