### ISSUE TITLE
Static getter executed on class inheritance

### ISSUE THREAD

**Issue by casser** [Microsoft/TypeScript#8420] opened 2016-05-02 16:07 UTC
**TypeScript Version:** 

1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

**Code**

```ts
class A{
    public static get foo(){
        return alert("should not execute getter, without accessing it !");
    }
}
class B extends A {}

```

**Expected behavior:**

Should not alert message above 

**Actual behavior:** 

Alerting message above

Link to [Playground](http://www.typescriptlang.org/play/index.html#src=class%20A%7B%0D%0A%20%20%20%20public%20static%20get%20foo()%7B%0D%0A%20%20%20%20%20%20%20%20return%20alert(%22should%20not%20execute%20getter%2C%20without%20accessing%20it%20!%22)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0Aclass%20B%20extends%20A%20%7B%7D)

**Comment by malibuzios** [comment] 2016-05-02 17:18
Tried it on `1.9.0-dev.20160501` on `ES5` target, same result, the `_extends` helper looks like this:

```ts
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) 
		if (b.hasOwnProperty(p))
			d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
```
I guess perhaps the assignment here could check if the member is a property and then use something like `Object.getOwnPropertyDescriptor` and then `Object.defineProperty` (or alternatively just `Object.assign` the whole thing if possible (but that wouldn't work with non-enumerable members, see below)).

Something like:
```ts
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) 
		if (b.hasOwnProperty(p)) {
			let descriptor = Object.getOwnPropertyDescriptor(b, p);
			
			if (typeof descriptor.get === "function" ||
				typeof descriptor.set === "function") {
				Object.defineProperty(d, descriptor)
			}
			else {
				d[p] = b[p]; // This is only for performance, 'defineProperty' can be used for all cases
			}
		}
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
```

In any case, with #3610 the current solution wouldn't work anyway, and for methods as well, as it only accounts for enumerable properties. They would need to use something like `Object.getOwnPropertyNames(b)`, so I guess this would be changed to something like this:

```ts
var __extends = (this && this.__extends) || function (d, b) {
	var props = Object.getOwnPropertyNames(b);
	
    for (var i = 0; i < props.length; i++) { 
		var descriptor = Object.getOwnPropertyDescriptor(b, props[i]);
		Object.defineProperty(d, descriptor);
	}
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
```

I'm surprised this hasn't been noticed (or at least fixed) yet.

**Comment by mhegazy** [comment] 2016-05-02 17:38
This is a duplicate of #1520. please see reply in https://github.com/Microsoft/TypeScript/issues/1520#issuecomment-67369005.

**Closed by mhegazy** 2016-05-02 17:38 UTC

**Comment by malibuzios** [comment] 2016-05-02 17:43
@mhegazy 

Seems like it would be fixed anyway when #3610 is introduced?

**Comment by malibuzios** [comment] 2016-05-02 18:01
Well, `static` getters/setters/methods seem to actually be enumerable based on my tests, so I'm not sure if it would be fixed any time soon... :'(

**Comment by malibuzios** [comment] 2016-05-02 18:10
@mhegazy 

I think you should seriously consider disallowing static getters and setters for ES3/ES5 targets. There's not really much of a point of having them if they don't actually work?

**Comment by mhegazy** [comment] 2016-05-02 18:19
That would be a breaking change. Today you can do this by overriding the __extends helper, which is a supported scenario.

**Comment by malibuzios** [comment] 2016-05-02 18:59
@mhegazy 

How is it a breaking change to move from something that doesn't work to something that simply tells you it doesn't work? seems like an enhancement maybe?

Anyway, many people come from languages like C# where static classes are the main way to describe global functionality. I tend to use them this way myself. I do use static getters and setters and care a lot about ES5 compatibility. 

(I noticed that compiler you almost don't use classes at all. Maybe if you've used it more extensively personally it would feel more important..?)

It could be true that the pattern is not statistically common but the more popular the language becomes, the more things that were once uncommon or seemed insignificant would start to come to light. I think this is a positive thing that is a sign of success, not failure. Also the more people start to truly understand and care about the language, they would want you to address some relatively minor things that might not have been that important initially (why doesn't it error if..? etc), a lot of the time simply because they like to feel that they are using a 'polished' and 'well-rounded' product.

Also, people's use of the language will be come more sophisticated with time as well, and things like generics, index signatures, static setter/getters, generic constraints etc. will become more widely used, so the impact of some of the 'holes' there may also become more significant..

**Comment by malibuzios** [comment] 2016-05-03 10:23
I don't think overriding helpers is something most people would want to deal with. It feels like something someone would do as an experiment maybe. In any case they would have to do this separately for every one of their project and adapt it to the particular build system used in it, and somehow make sure it is evaluated before anything else (for example, I use a glob based build system so I don't currently have that guarantee as the file list is auto-generated).

I could give you a pull request for:

[Line 341 in `emitter.ts`](https://github.com/Microsoft/TypeScript/blob/71fc58197c9f7d157784a91c52f8d463c48679b1/src/compiler/emitter.ts#L341)

But I'm almost 100% sure it would be rejected, so I'm not even going to try..
