### ISSUE TITLE
const declarations should have inferred index signature

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#28605] opened 2018-11-19 20:42 UTC
This one keeps biting me and it's driving me crazy. Say I have this exported const:

```js
export const defaultInt = {
  'golang': 'int',
  'java': 'int',
  'typescript': 'number'
};
```

it can be easily inferred that the index signature is:

```
[key: string]: string
```

but the problem is when I go to use it:

```js
import {defaultInt} from './defaults'

if(defaultInt['golang']){
   // ...
}

```

I get an error:

`TS7017: Element implicitly has an 'any' type because type '{ 'golang': string; 'java': string; 'typescript': string; }' has no index signature.`

But it clearly does have an inferrable index signature...is there a good way around this. I am sure if I have asked this before but this is a desperate feature request.

Of course, I can do this:

```js
if((defaultInt as any)['golang']){
   // ...
}
```

but that defeats the purpose of typing - I want to know of the key 'golang' exists on defaultInt or not.

If this is too much work for the compiler...maybe have an Infer keyword, something like:

```js
export const defaultInt = <Infer>{
  'golang': 'int',
  'java': 'int',
  'typescript': 'number'
};
```

The Infer keyword will tell the compiler to do the work of inferring the type? idk

**Comment by NN---** [comment] 2018-11-19 21:19
Does it happen only for import ?
Without import there is no [problem](http://www.typescriptlang.org/play/#src=export%20const%20defaultInt%20%3D%20%7B%0D%0A%20%20'golang'%3A%20'int'%2C%0D%0A%20%20'java'%3A%20'int'%2C%0D%0A%20%20'typescript'%3A%20'number'%0D%0A%7D%3B%0D%0A%0D%0Aconst%20e%20%3D%20defaultInt%5B'golang'%5D%3B):

```ts
export const defaultInt = {
  'golang': 'int',
  'java': 'int',
  'typescript': 'number'
};

const e = defaultInt['golang']; // e is string, no error
```

**Comment by ORESoftware** [comment] 2018-11-19 21:22
@NN--- yeah it might just be for imports, I am not 100% sure

**Comment by ORESoftware** [comment] 2018-11-20 07:14
@NN--- for example this is driving me bananas/bonkers/up the wall

![screenshot from 2018-11-19 23-13-39](https://user-images.githubusercontent.com/11139560/48757219-dd59f880-ec50-11e8-9b2a-ee89e5bc79bd.png)

Why on earth is there no inferred index signature there?

**Comment by NN---** [comment] 2018-11-20 07:32
Which TypeScript version do you use ?
I don't see any problem with TypeScript 3.1.6

![image](https://user-images.githubusercontent.com/580536/48757976-289ef600-eca7-11e8-9d79-927b51202a46.png)

**Comment by NN---** [comment] 2018-11-20 07:34
Btw, instead of <> type assertion syntax, there is a nicer syntax with 'as'.
https://basarat.gitbooks.io/typescript/docs/types/type-assertion.html

**Comment by NN---** [comment] 2018-11-20 07:34
Not sure what you want to do in your code sample but definitely assertion to 'any' is not a good idea.

**Comment by RyanCavanaugh** [comment] 2018-11-21 02:11
Duplicate of #27127

**Closed by RyanCavanaugh** 2018-11-21 02:11 UTC
Labels: Duplicate
