### ISSUE TITLE
Emit of union type metadata of two classes inherited from the same parent are Object and not common ancestor 

### ISSUE THREAD

**Issue by dqweek** [Microsoft/TypeScript#12705] opened 2016-12-07 10:03 UTC
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts

function dec(): PropertyDecorator {
    return (target: any, key: string | symbol): void => { };
}

class UseCase { }

class Child1 extends UseCase {
}
class Child2 extends UseCase {
}

class D {
    @dec()
    field: Child1 | Child2;
}


```

**Expected behavior:**

```ts

function dec() {
    return function (target, key) { };
}
var UseCase = (function () {
    function UseCase() {
    }
    return UseCase;
}());
var Child1 = (function (_super) {
    __extends(Child1, _super);
    function Child1() {
        _super.apply(this, arguments);
    }
    return Child1;
}(UseCase));
var Child2 = (function (_super) {
    __extends(Child2, _super);
    function Child2() {
        _super.apply(this, arguments);
    }
    return Child2;
}(UseCase));
var D = (function () {
    function D() {
    }
    __decorate([
        dec(), 
        __metadata('design:type', UseCase)
    ], D.prototype, "field", void 0);
    return D;
}());

```

**Actual behavior:**

```ts

function dec() {
    return function (target, key) { };
}
var UseCase = (function () {
    function UseCase() {
    }
    return UseCase;
}());
var Child1 = (function (_super) {
    __extends(Child1, _super);
    function Child1() {
        _super.apply(this, arguments);
    }
    return Child1;
}(UseCase));
var Child2 = (function (_super) {
    __extends(Child2, _super);
    function Child2() {
        _super.apply(this, arguments);
    }
    return Child2;
}(UseCase));
var D = (function () {
    function D() {
    }
    __decorate([
        dec(), 
        __metadata('design:type', Object) // <-- expected to be UseCase
    ], D.prototype, "field", void 0);
    return D;
}());

```

**Related Issues**
#12703

**Comment by mhegazy** [comment] 2016-12-07 17:44
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/12703. all union types are treated the same way.

**Closed by mhegazy** 2016-12-07 17:44 UTC
Labels: Duplicate

**Comment by dqweek** [comment] 2016-12-07 18:27
Why they need to be treated the same, is it difficult to reflect the common ancestor of Union of types ?
Of course all types have common ancestor (object type) by default, but still it would be nice to emit something more descriptive, so we could use it in runtime
