### ISSUE TITLE
narrow down ts-expect-error with error code

### ISSUE THREAD

**Issue by shahul01** [microsoft/TypeScript#53926] opened 2023-04-20 11:06 UTC
# Suggestion
Example, when there is an error `TS2786 MyComponent cannot be used as JSX Component (for so and so reason)` and you want to block only that and not all the other errors like forgetting to pass down a required prop into that component and so on for the next line(s), this feature will be useful.

Use it like 
// @ts-expect-error TS2786
// @ts-expect-error TS2786, TS2322
etc

## 🔍 Search Terms
ts-expect-error
@ts-expect-error
expect

I checked, no issues available

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

*I marked these to best of my knowledge.

## 📃 Motivating Example

"Don't sacrifice your typesafety because of 1 error"
Narrowing down a ts error, so the entire line works just as normal except that error instead of having to entirely disable all type / error checking  for that line(s). 

## 💻 Use Cases

- What do you want to use this for?
During development it helps if you can ignore error every now and then as you develop

- What shortcomings exist with current approaches?
Disables entire error checking because of 1 error!

- What workarounds are you using in the meantime?
None

**Comment by MartinJohns** [comment] 2023-04-20 11:22
Duplicate of #45937.

**Closed** 2023-04-23 09:05 UTC
Labels: Duplicate
