### ISSUE TITLE
Function argument Type-assertion does not work correctly

### ISSUE THREAD

**Issue by manuth** [microsoft/TypeScript#31716] opened 2019-06-01 11:51 UTC
**TypeScript Version:**  3.6.0-dev.20190601

**Search Terms:**
  * Function argument
  * Type-Assertion
  * Argument-Types
  * promisify
  * Function-overloads
  * Overloads

**Code**

```ts
declare function sourceMaps(): NodeJS.ReadWriteStream;
declare function sourceMaps(path: string): NodeJS.ReadWriteStream;
declare function sourceMaps(path: string, options: object): NodeJS.ReadWriteStream;
declare function sourceMaps(options: object): NodeJS.ReadWriteStream;

declare function queue<TArgs extends any[]>(fn: (...args: TArgs) => NodeJS.ReadWriteStream, ...args: TArgs): any;

declare function altQueue(fn: () => NodeJS.ReadWriteStream): any;
declare function altQueue<TArg1>(fn: (arg1: TArg1) => NodeJS.ReadWriteStream, arg1: TArg1): any;
declare function altQueue<TArg1, TArg2>(fn: (arg1: TArg1, arg2: TArg2) => NodeJS.ReadWriteStream, arg1: TArg1, arg2: TArg2): any;

queue(sourceMaps);              // Reports an error
queue(sourceMaps, "");          // Reports an error
queue(sourceMaps, "", {});      // Reports an error
queue(sourceMaps, {});

altQueue(sourceMaps);
altQueue(sourceMaps, "");       // Reports an error
altQueue(sourceMaps, "", {});   // Reports an error
altQueue(sourceMaps, {});
```

**Expected behavior:**
TypeScript should recognize there is a function-overload which matches the `TArgs`- or `TArg1`- and `TArg2`-type.

**Actual behavior:**
TypeScript reports an error expecting the argument-types to match the last declaration of the function.

**Playground Link:**
[Link to Playground](https://www.typescriptlang.org/play/index.html#src=class%20ReadWriteStream%0D%0A%7B%0D%0A%20%20%20%20pipe()%0D%0A%20%20%20%20%7B%7D%0D%0A%7D%0D%0A%0D%0Adeclare%20function%20sourceMaps()%3A%20ReadWriteStream%3B%0D%0Adeclare%20function%20sourceMaps(path%3A%20string)%3A%20ReadWriteStream%3B%0D%0Adeclare%20function%20sourceMaps(path%3A%20string%2C%20options%3A%20object)%3A%20ReadWriteStream%3B%0D%0Adeclare%20function%20sourceMaps(options%3A%20object)%3A%20ReadWriteStream%3B%0D%0A%0D%0Adeclare%20function%20queue%3CTArgs%20extends%20any%5B%5D%3E(fn%3A%20(...args%3A%20TArgs)%20%3D%3E%20ReadWriteStream%2C%20...args%3A%20TArgs)%3A%20any%3B%0D%0A%0D%0Adeclare%20function%20altQueue(fn%3A%20()%20%3D%3E%20ReadWriteStream)%3A%20any%3B%0D%0Adeclare%20function%20altQueue%3CTArg1%3E(fn%3A%20(arg1%3A%20TArg1)%20%3D%3E%20ReadWriteStream%2C%20arg1%3A%20TArg1)%3A%20any%3B%0D%0Adeclare%20function%20altQueue%3CTArg1%2C%20TArg2%3E(fn%3A%20(arg1%3A%20TArg1%2C%20arg2%3A%20TArg2)%20%3D%3E%20ReadWriteStream%2C%20arg1%3A%20TArg1%2C%20arg2%3A%20TArg2)%3A%20any%3B%0D%0A%0D%0Aqueue(sourceMaps)%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Reports%20an%20error%0D%0Aqueue(sourceMaps%2C%20%22%22)%3B%20%20%20%20%20%20%20%20%20%20%2F%2F%20Reports%20an%20error%0D%0Aqueue(sourceMaps%2C%20%22%22%2C%20%7B%7D)%3B%20%20%20%20%20%20%2F%2F%20Reports%20an%20error%0D%0Aqueue(sourceMaps%2C%20%7B%7D)%3B%0D%0A%0D%0AaltQueue(sourceMaps)%3B%0D%0AaltQueue(sourceMaps%2C%20%22%22)%3B%20%20%20%20%20%20%20%2F%2F%20Reports%20an%20error%0D%0AaltQueue(sourceMaps%2C%20%22%22%2C%20%7B%7D)%3B%20%20%20%2F%2F%20Reports%20an%20error%0D%0AaltQueue(sourceMaps%2C%20%7B%7D)%3B)

This issue is, for example, affecting the `promisify`-function of `node.js`' `util`-module:
```ts
import { promisify } from "util";

declare function test(callback: (error: Error, result: any) => any): void;
declare function test(name: string, callback: (error: Error, result: any) => any): void;
declare function test(options: { name: string, author: string }, callback: (error: Error, result: any) => any): void;

promisify(test)();
promisify(test)("");                        // Reports an error
promisify(test)({ name: "", author: "" });  // Reports an error
```

**Comment by jcalz** [comment] 2019-06-02 00:03
Related to or duplicate of #30369, #29312 ?

**Comment by manuth** [comment] 2019-06-02 16:47
I'm not that sure whether this is the same issue but it sure does look a little similar, that's true

**Comment by RyanCavanaugh** [comment] 2019-06-13 16:11
We can't yet support higher-order overload resolution, which is what all of these would require. The linked issues go into more detail

**Closed** 2021-06-01 22:25 UTC
Labels: Design Limitation
