### ISSUE TITLE
Conditional compilation

### ISSUE THREAD

**Issue by impinball** [Microsoft/TypeScript#4671] opened 2015-09-06 08:09 UTC
Conditional compilation would be fantastic, in my opinion, for things like imports. I would really appreciate something like this:

```ts
@if DEBUG
@define HAS_ASSERT
import assert from "assert";
@elif RELEASE
import aRandomModule from "my-cool-module";
@else
@undef FOO
@endif
```

Not asking for macros (there's not nearly as much of a use case in TypeScript as in e.g. C/C++), but merely having an if-else/define/undef preprocessor would be incredibly helpful.

**Comment by weswigham** [comment] 2015-09-06 13:07
Dupe of #449 ?

**Comment by jesseschalken** [comment] 2015-09-06 13:58
Just import all the things you could need and decide what to use at runtime.

At best all you'd be saving with condition compilation is the overhead of an import.

**Comment by impinball** [comment] 2015-09-06 18:46
Size is a reason to prefer conditional importing and compilation,
particularly in the case of the browser.

**Comment by yortus** [comment] 2015-09-08 16:02
I made a proposal with a working implementation in #4691

**Closed** 2015-09-08 19:37 UTC
