### ISSUE TITLE
DIEGOHJJACOBO/walmer

### ISSUE THREAD

**Issue by DIEGOHJJACOBO** [microsoft/TypeScript#56204] opened 2023-10-24 09:53 UTC
TypeScript has two narrowing-related behaviors that are both intentional. Please do not log additional bugs on this; see #9998 for more discussion.

The first is that *narrowings are not respected in callbacks*. In other words:
```ts
function fn(obj: { name: string | number }) {
  if (typeof obj.name === "string") {
    // Errors
    window.setTimeout(() => console.log(obj.name.toLowerCase());
  }
}
```
This is intentional since the value of `obj.name` "could" change types between when the narrowing occurred and when the callback was invoke. See also #11498

The second is that *function calls do not reset narrowings*. In other words:
```ts
function fn(obj: { name: string | number }) {
  if (typeof obj.name === "string") {
    console.log("Here");
    // Does not error
    console.log(obj.name.toLowerCase());
  }
}
```
This is intentional behavior, *even though `console.log` could have mutated obj*. This rule is consistently applied, even with the function is in-principle inspectable to actually have side effects
```ts
function fn(obj: { name: string | number }) {
  if (typeof obj.name === "string") {
    mut();
    // Does not error
    console.log(obj.name.toLowerCase());
  }

  function mut() {
    obj.name = 42;
  }
}
```

**Comment by MartinJohns** [comment] 2023-10-24 10:12
Duplicate of #9998.

**Comment by fatcerberus** [comment] 2023-10-24 10:39
@MartinJohns Just for the record this is just the 9998-dupe issue template copied and pasted verbatim, and yet it apparently doesn’t *use* that template since it wasn’t auto-tagged as a duplicate.  I have no idea what’s going on here.

**Closed** 2023-10-24 15:46 UTC
Labels: Duplicate
