### ISSUE TITLE
Wrong type inference for block scoped variables

### ISSUE THREAD

**Issue by DavideCanton** [microsoft/TypeScript#42146] opened 2020-12-29 15:00 UTC
**TypeScript Version:**  4.1.3

**Search Terms:** inference, variable, block, wrong

**Expected behavior:**
It should compile just fine.

**Actual behavior:**
Compilation error on row 16 due to wrong inference of variable.

**Related Issues:** not found

**Code:**
```ts
function setToTrue(func: (v: boolean) => void) {
    func(true);
}

function expect<T>(v: T): { toEqual: (t2: T) => void } {
    return {
        toEqual: v2 => {
            if (v !== v2) throw new Error('different values');
        }
    };
}

function foo() {
    let b: boolean | null = null;    
    setToTrue(x => b = x);
    expect(b).toEqual(true);
}
```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.1.3#code/GYVwdgxgLglg9mABAZwKZQCpwwJxKgClEgC5ECA3MgIzjgBtUBDMASkQF4A+RCuGACbsA3gChEExMQgEoeVKwDcogL6jR02AkSoAHgAdU0ADwYulMhlZlhiKHACiARxBN6ZWQCZL7br34CiCqIYpKIOOggOEihYZL2zq7uvJ6cPLFxcTDA5BSIAIQcHCnsUAAWOHAA7ohgqDUOOJU4BADkAtnAqBFgULxu+MitSuKZQaMSKspqGuDQ8EjAdAQiE4iMfdQ0dIwsiAA+tSD09JxHJ8phaJjY8gS6aYjUZ7ojYXqG0ATUrAB0CS43LJ5CM1EA)
      
Type inference for variable "b" at row 14 is wrong, even if I specify explicitly "boolean | null". The compiler is unable to understand that b is effectively assigned immediately at line 15, and I find it to be correct, but it also infers that the actual type of the variable is just "null" and not "boolean | null" as I provided.
As a result, the code at line 16 (which I loosely borrowed from jasmine), does not compile, as the expect function is unable to get the property generic type instantiation, because T gets replaced with "null".

**Comment by MartinJohns** [comment] 2020-12-29 15:09
Duplicate of #9998.

**Comment by DavideCanton** [comment] 2020-12-29 22:20
Sorry, I read the whole issue but I did not find which of the examples is covering my case.

Nobody in #9998 is complaining about block-scoped variables with **explicit type** being wrongly narrowed.

**Comment by MartinJohns** [comment] 2020-12-29 22:29
Type annotations for local variables are not considered if the variable doesn't get any other value assigned anywhere.

Some reason why `foo` is typed `undefined` and not `number | undefined` in this example:

    const foo: number | undefined = undefined;
    foo; // Hover over me.

**Closed** 2021-01-01 18:00 UTC
Labels: Duplicate
