### ISSUE TITLE
Function return typing not working well when depth is higher than 1 

### ISSUE THREAD

**Issue by carlo23666** [microsoft/TypeScript#52893] opened 2023-02-21 10:15 UTC
# Bug Report

### 🔎 Search Terms

Function Return, Optionality, Optional

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Return Optionality

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230221#code/MYGwhgzhAECiAeYC2AHEBTaBvAUNf0SYAlgHYAUKYATsgFzQBGA9sxmKQJTZ4F-DNSEAC7Rq6CAFcQogLzRhAC2IQAdAHN0wgLJbFzACYBhSOgCMlGsm4B6G2InThq4NBXRSzUQDcVxRhjQiuji0OQAQmAGnLx8+HZ8AHoA-LFxAkKi4lIyAEzQ8koqGlq6SoYmEOi5lrRItvbZTi5uMMwowsSCYCBBIZjkAPIA0jFxBAkEKWn8giIOOcIAzAUKymqaOnoVpku11tAJTTIt7u2d3b3BoUOjMxP2U6l8AL44aZtl+samFlR1DBYbHQHG4uHG+GIADN9vUeBC4uJhJJqKQ1sUkNsDBYxhC3vdITCAIT-A7ghEEJEotFFNSY8oGGq48b4hFKajMADuHnQ3Ng1A51HIAHIAHJeaAZYQckAYAzC5nQfEfUpYyrVWGA1jsLjwiHQ2FggnpOZZRwyVa01T0744418Kmo7CqF3HYRvBGs-XE0lw8kUyWmhZOS3ra1Ypn2ylaanO13m93Gr3jdlcnl8gXMIViiVSmVyhVpZPQT5q3aapjakG6-1xA2+o0B-COtFYRh0MwAGkldFyHrx7wRBpJVj9UebMadbYYZn7LMHENT3NIvLgmez4tEebYBcVyr4NsMOL14xb2Hb0C7PegfaLC-wh8Z5EbELP08vc6VOBeQA)

### 💻 Code

```ts
class Example {
    main(param: boolean) {
        const result = this.getMethodCase1(param) // result.c is not visible here (Bad)
        //    ^?
        const result2 = this.getMethodCase2(param) // result.c is optional here (OK)
        //    ^?
        const result3 = this.getMethodCase3(param) // result.c is optional here (OK)
        //    ^?
    }

    getMethodCase1(param: boolean) {
        if(param) {
            return this.method1()
        }

        if(!param) {
            return this.method2()
        }

        throw new Error('Not controlled')
    }


    getMethodCase2(param: boolean) {
        if(param) {
            const result = this.method1()
            return {...result}
        }

        if(!param) {
            const result = this.method2()
            return {...result}
        }

        throw new Error('Not controlled')
    }

    getMethodCase3(param: boolean) {
        if(param) {
            return {b:1, c:2}
        }

        if(!param) {
            return {b: 1}
        }

        throw new Error('Not controlled')
    }


    method1() {
        return {b: 1, c: 2}
    }

    method2() {
        return {b: 1}
    }
}
```

### 🙁 Actual behavior

Result 1 doesn't have optional attribute c

### 🙂 Expected behavior

All results should have optional attribute c

**Comment by whzx5byb** [comment] 2023-02-21 15:49
Duplicate of https://github.com/microsoft/TypeScript/issues/46449

**Comment by RyanCavanaugh** [comment] 2023-02-21 17:46
Optional inference only happens when all input candidates are fresh object literals. See #19513

**Comment by Andarist** [comment] 2023-02-21 18:57
I was expecting that freshness is at play here but the thing that still surprises me is that `getMethodCase1` and `getMethodCase2`. It's only the `getMethodCase3` that is explained by the freshness (I think?).

**Comment by RyanCavanaugh** [comment] 2023-02-21 20:26
I guess you could argue that literals with spreads shouldn't be considered fresh, since the sorts of guarantees that literals provide don't usually apply when a spread is present.

**Comment by RyanCavanaugh** [comment] 2023-02-22 21:47
Sorry, I got something backwards above - the one with spreads is working correctly.

The difference between 2 and 3 is just whether subtype reduction has happened yet. I'm not really sure why one happens and not the other; subtype reduction is *allowed* to happen anywhere, but is not *required* to do so at any time, so either behavior is considered correct from our perspective.

**Closed** 2023-02-25 20:00 UTC
Labels: Working as Intended
