### ISSUE TITLE
Asserts function does not account for function call

### ISSUE THREAD

**Issue by ItHasU** [microsoft/TypeScript#48883] opened 2022-04-29 16:47 UTC
# Bug Report

### 🔎 Search Terms

asserts function never

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about assertion.
- I was unable to test this on versions prior to 3.7.5 because asserts function did not existed.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/GYVwdgxgLglg9mABAQwM6oKYCcoAoIIAmMsCAXCmAJ4A0iAtqgOYD8FqUWMYTAlBWkw5UiAmGKkkAbwBQiRDGCJcAQjET4YXolnz5UABZY4Ad0RgMZgKJZjWXACIAgumxREwZDAA2GQhQdEAGoGZl4AbjlEAF8ZWJluKGxPCAxEABUdKPkAN2RvEAw2cxB6ACNsAG0AXUj40EhJD1w4MoArCnT+RBy4GEIsvURWtoA6PIK0gF5ESoBmWriZGTEOYfbOxBmpaMjBNxb28fzCrZmwEG9vOmdbZCoFETA4d0IMYG4-BwiZYEO2n77HD-Y6TRAqc6Xa6IW5Ye6PcwvRBvD4WQjfPauYEjUGFFijXw8QxnGYARhuTjuD3oIDWBmQOTSpMQGF89AwYCgGJWCFQcF8BLgTEcAGUQBBUugMUA)

### 💻 Code

```ts
function assert(condition: any, msg?: string): asserts condition {
  if (!condition) {
    throw new Error("Assert failed: " + msg);
  }
}

interface T {
    value?: number[];
}

function f(obj: T): void {
    obj.value = [3];
}

const obj: T = {};
assert(obj.value == null, "Array is not defined");
f(obj);
assert(obj.value != null, "Array is not defined");
assert(obj.value?.length === 1, "Array must have 1 element");
console.log("Success");
```

### 🙁 Actual behavior

I get the following error on obj.value?.length : `Property 'length' does not exist on type 'never'.(2339)`

### 🙂 Expected behavior

Since f() is called on obj, I would expect Typescript to reset its type.
At least, since I added an assertion to check that obj.value is defined, I would expect Typescript to reset assertions.

Please, let me know how I should have wrote this if this is not a bug.
Thanks for your support.

**Comment by MartinJohns** [comment] 2022-04-29 16:59
Duplicate of #9998.

**Comment by fatcerberus** [comment] 2022-04-29 18:23
I don’t think that additional bug report template specifically for #9998 is working…

**Comment by fatcerberus** [comment] 2022-04-29 18:27
> Since f() is called on obj, I would expect Typescript to reset its type.

This is already discussed in 9998, but I want to stress that in general, *you don’t want this*.  Since almost any operation in JS can have local side effects (even property accesses!), type narrowing would be next to useless if the compiler did this.

**Comment by MartinJohns** [comment] 2022-04-29 18:28
> I don’t think that additional bug report template specifically for #9998 duplicates is working…

It mentions callbacks, which does not apply here.

**Comment by ItHasU** [comment] 2022-04-30 21:02
Hi, I understand how it is related to #9998. 

Could you please help me to figure out what is the best syntax to use in my code ? 
I've been using a cast to reset assertions on the objects. Is this a good way ?

Thanks

**Closed** 2022-05-05 18:00 UTC
Labels: Duplicate
