### ISSUE TITLE
[isolatedDeclarations][5.5] Disagreement between transpileDeclaration API and typechecker on Symbol.iterator as computed property

### ISSUE THREAD

**Issue by MichaelMitchell-at** [microsoft/TypeScript#58490] opened 2024-05-09 19:52 UTC
### 🔎 Search Terms

isolated declarations transpileDeclaration symbol iterator

### 🕗 Version & Regression Information

- nightly

### ⏯ Playground Link

https://tsplay.dev/wXLvLw

### 💻 Code

```ts
export class Foo implements Iterable<number> {
  public [Symbol.iterator]() {
    return {
      next: () => ({ value: 42, done: false }),
    };
  }
}
```

### 🙁 Actual behavior

`ts.transpileDeclaration` has diagnostic: `Computed properties must be number or string literals, variables or dotted expressions with --isolatedDeclarations.`

`tsc --isolatedDeclarations` completes successfully

### 🙂 Expected behavior

I'm not sure which is more correct here. If we treat this as not an error, then that seems to imply that `Symbol.iterator` is treated specially, which runs into weird edge cases like `Symbol` being overridden in the current scope. But if we do treat this as an error, then the question becomes how does one add an explicit type annotation for this case?

**Comment by MichaelMitchell-at** [comment] 2024-05-09 19:53
@dragomirtitian @weswigham here's a fun one for y'all 🙃

**Comment by dragomirtitian** [comment] 2024-05-13 12:39
For computed properties we allow them to be used in isolated declarations even if we can't determine the type is valid locally. This was due to the fact that computed properties with unique symbols would otherwise be completely unusable with isolated declarations. 

In `transpileDecalarations` the checker should only be used when needed. In this case the checker will not actually find a type for `Symbol.iterator` so it will complain. I think since `transpileDecalarations` uses `noChecck` it should probably fall back on the isolated declaration test and just emit the entity name even if it can't check the type is correct. @weswigham thought?

**Comment by weswigham** [comment] 2024-05-13 18:46
> it should probably fall back on the isolated declaration test and just emit the entity name even if it can't check the type is correct

It is. The issue is that the check for the ID error (in `visitDeclarationSubtree` in `declarations.ts`) relies on elements of the `Symbol` global resolving, in this case. Specifically, that `resolver.isEntityNameVisible` check in the condition. If the checker isn't running and you have no other files in the program, the name isn't gonna resolve for a missing global. Yeah, that would be a checker error *if the checker was running in the same `noResove`-ish single-file mode*, but if you're not even capturing those... ??? The error behavior here is checker dependent because of the entity name lookup - hence the difference in command-line (where the global resolves) and API (where it doesn't) behavior.

Symbols are a big hole in `isolatedDeclarations` usability that we don't have great answer for right now. For builtin symbols, I could easily remove the error by passing a more complete `lib` into the `transpileDeclarations` program, so `Symbol.iterator` is recognized as a valid late-bound property, but that's basically a stop-gap. Custom symbols like
```ts
const sym = Symbol();
export class Foo {
  public [sym]() {
    return {
      next: () => ({ value: 42, done: false }),
    };
  }
}
```
I've currently patched into emitting "correctly", but still issuing the `isolatedDeclarations` error - I imagine this case should be similar. The ID error should appear in all cases (even when the name fails to resolve), but the emit should be reasonably sane.

**Comment by MichaelMitchell-at** [comment] 2024-05-13 19:02
> still issuing the isolatedDeclarations error 

Would you happen to know of a clean and concise way to annotate code following this pattern to satisfy isolatedDeclarations? IIRC they can't be suppressed by `@ts-expect-error` (on my phone so can't validate quickly)

**Comment by MichaelMitchell-at** [comment] 2024-05-13 19:13
Hm. Wonder if it would be too special casey to look for expressions that match the pattern `Symbol.iterator satisfies unique symbol` and emit without error in those cases

**Comment by weswigham** [comment] 2024-05-13 19:16
To be even more explicit, this
```ts
// @filename: defines.d.ts
export const mySymbol: unique symbol;
// @filename: usage.ts
import {mySymbol} from "./defines.js"
export class Foo {
  [mySymbol]() {}
}
```
is something you want to allow because its' how symbols are meant to be used, but
```ts
// @filename: defines.d.ts
export const mySymbol: string;
// @filename: usage.ts
import {mySymbol} from "./defines.js"
export class Foo {
  [mySymbol]() {}
}
```
is something you need to *forbid* because you don't know if `mySymbol` conflicts with anything. And when you only look at `usage.ts`, these two cases are identical. So you're either conservative and forbid basically all computed names (very bad for usability), incredibly loose and allow most computed names (which is a big footgun for anyone relying on the output computed name actually working/existing when transformed into a type), or you slice it in some weird way to sometimes work and sometimes not based on some common usecase heuristics.

**Closed** 2024-05-22 19:28 UTC
Labels: Domain: ts.transpileDeclaration, Domain: Isolated Declarations
