### ISSUE TITLE
for .. in type is wrong for objects as const

### ISSUE THREAD

**Issue by fabio-colella-md** [microsoft/TypeScript#49621] opened 2022-06-21 14:23 UTC
# Bug Report
When declaring a new object as const, if we then use a `for .. in` structure, the type of the key is just inferred as `string` and not as the more restricted type that const defines. This causes issues especially when trying to use that key to get the corresponding property.

### 🔎 Search Terms
`is:issue for in as const`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `const`

### ⏯ Playground Link
https://www.typescriptlang.org/play?ts=4.8.0-dev.20220621#code/MYewdgzgLgBAtgTwMLmgeQEYCsYF4YDeAsAFAwwCGAXDAERQCm0AjLQDSnkY31NQBMtUgF9KEGKEhQA3KVIAzEACcYACknQYIbAGkGCGAEsw8ZKiiYsASkKdTKKZYDa2rHoQBdEaSA

### 💻 Code

```ts
const myConstObj = {
  a: "test1",
  b: "test2"
} as const;

for (const objKey in myConstObj) {
  myConstObj[objKey]
}/* ^^^^^^^^^^^^^^^^
    const objKey: string
    --------------------
    Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 
    '{ readonly a: "test1"; readonly b: "test2"; }'.
        No index signature with a parameter of type 'string' was found on type 
    '{ readonly a: "test1"; readonly b: "test2"; }'.(7053)
*/
```

### 🙁 Actual behavior
When using the key to get the prop, we are told that the prop would have type `any` because the key is of type `string`. 
<img width="773" alt="Screenshot 2022-06-21 at 16 16 46" src="https://user-images.githubusercontent.com/91458244/174822039-c80102bc-79cc-46fa-ba65-90dc1a4dd774.png">

### 🙂 Expected behavior
No error should be reported, as the correct inferred type for the key should be the union of the keys (i.e. `'a' | 'b'` in this case) of the const object.

### 🤔 Workaround
"Coerce" the key type to be what we would have expected, so in this case:
```ts
const myConstObj = {
  a: "test1",
  b: "test2"
} as const;

for (const _objKey in myConstObj) {
  const objKey = _objKey as keyof typeof myConstObj
  myConstObj[objKey]
}
```
<img width="538" alt="Screenshot 2022-06-21 at 16 17 35" src="https://user-images.githubusercontent.com/91458244/174822211-0157bf11-1a3a-41cb-9793-3f50d7d48dde.png">

**Comment by MartinJohns** [comment] 2022-06-21 14:28
Duplicate of #44706.

**Comment by fcole90** [comment] 2022-06-21 14:35
This issue is different, as this one is restricted only to objects `as const` 😉

**Comment by RyanCavanaugh** [comment] 2022-06-21 16:45
The feature needed to make this OK is exact types. `as const` changes the *type of an expression*, it's not something that's reflected in the type system per se. IOW there's nothing from TS's perspective that distinguishes the code in the OP from this code, which would violate the `keyof` assumption:
```ts
const myConstObjTmp = {
  a: "test1",
  b: "test2"
} as const;
const gotcha = { a: "test1", b: "test2", c: "test3" } as const;
const myConstObj: typeof myConstObjTmp = gotcha;
```

**Comment by fabio-colella-md** [comment] 2022-06-22 07:35
I understand your points, indeed there are many valid scenarios where that type I suggested would not be correct 🤔 
Hence, I think I should just keep using the workaround. Do you have any suggestions on making that cleaner and more concise? I think it's a very common scenario. I wanted to specify the type from within the `for` but I couldn't find a way 🤔 At least, I'd like to avoid the need of creating an extra variable 😅

**Comment by MartinJohns** [comment] 2022-06-22 08:32
> So, taking @MartinJohns's example, why can't the inferred type be `'a' | 'b' | 'c'` instead of a very generic `string`?

Because the compiler doesn't know there's a property `"c"`. It sees a type that has only two properties: `"a"` and `"b"`.

**Comment by fabio-colella-md** [comment] 2022-06-22 10:16
Alternative workaround
```ts
const myConstObj = {
  a: "test1",
  b: "test2"
} as const;

for (const objKey of Object.keys(myConstObj) as (keyof typeof myConstObj)[]) {
  myConstObj[objKey]
}
```

**Comment by MartinJohns** [comment] 2022-06-22 11:23
```typescript
function getObjectKeysUnsafe<T extends object>(value: T): (keyof T)[] { return Object.keys(value) as (keyof T)[]; }

for (const objKey of getObjectKeysUnsafe(myConstObj)) {
  myConstObj[objKey]
}
```

**Comment by fabio-colella-md** [comment] 2022-06-22 12:57
Nice, thanks 😊

**Closed** 2022-06-22 16:27 UTC
Labels: Suggestion, Declined

**Comment by Darrick-Oliver** [comment] 2023-09-19 04:34
I found that using a [`for..of` loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) fixed my issue

**Comment by JosXa** [comment] 2024-05-15 09:40
Here's a gist for those cases where you're sure the object is not modified at runtime: https://gist.github.com/JosXa/a76b4e4cde1ef8ac7092a1dff670aa68
