### ISSUE TITLE
Ternary operator result not type checked correctly

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#19213] opened 2017-10-16 13:55 UTC
**TypeScript Version:**  2.6.0rc, also 2.5.2

**Code**

```ts
{
    // expected error, got error
    const x1: { blur?: string } = { blur: 1 };

    // expected error, but got none!
    const x2: { blur?: string } = 'foo' ? { blur: 1 } : {};

    // expected error, got error
    const x3: { blur?: string } = (() => {
        if ('foo') {
            return { blur: 1 };
        } else {
            return {};
        }
    })();
}
```

Related to https://github.com/Microsoft/TypeScript/issues/14758?

**Comment by mhegazy** [comment] 2017-10-16 17:51
Duplicate of #12745, fixed by https://github.com/Microsoft/TypeScript/pull/16363

**Closed** 2017-10-16 17:51 UTC
Labels: Fixed

**Comment by ahejlsberg** [comment] 2017-10-16 22:22
@mhegazy I don't think this is fixed as you indicate. The issue here is that we reduce the type of `'foo' ? { blur : 1 } : {}` to simply `{}` which then is assignable to `{ blur?: string }`.

**Comment by mhegazy** [comment] 2017-10-16 22:29
Sorry about that.. it is not fixed. Marking it as duplicate of #14758
