### ISSUE TITLE
Type of var is automatically being false but should be boolean, as an in-scope defined function changes it.

### ISSUE THREAD

**Issue by SrBrahma** [microsoft/TypeScript#41663] opened 2020-11-24 02:14 UTC
**TypeScript Version:**  4.2.0-dev.20201123

**Search Terms:**
var doesn't recognize its type may change in a function
**Code**

```ts
let A: boolean = false;
let B: boolean = false

const arr = [1,2,3];

arr.forEach((e) => {
  if (e === 2)
    A = true;
})

if (arr[1] === 2)
  B = true;

type A2 = typeof A // false (wrongly)
type B2 = typeof B // boolean

// This led me to a bug like this:
const aBoolean = true as boolean;
const aNumber = 5 as number;

const C = A && (aBoolean || aNumber) // type is false (wrongly)
const D = B && (aBoolean || aNumber) // type is number | boolean
```

**Expected behavior:**
`A` and `A2` should be of type boolean instead of false
**Actual behavior:**
`A` doesn't see that its value may change in a in-scope function execution. I was using a value like this `C` var, and without I knowing, it was passing a number to another function and cascading another bugs, when it should be only a boolean, and warn me for it possibly being a number.

As a workaround, I made let A = false as boolean so this automatic-to-false-type doesn't happen.

I didn't know this behaviour, and 
**Playground Link:**  
https://www.typescriptlang.org/play?ts=4.2.0-dev.20201123#code/DYUwLgBAggXBBGB7RoCGA7CBeCAzVwAziANwCwAUKJAEJxIogbZ4HGWUDGi6hkqAJwEsA2gEYANACYJAZgC65CpUECAdLkQCAoqk4ALABSGQASmwA+CAG9KECAEtcEE9iw4ppu-egswAgFdSSgBfL2UKJxdVcXk3D3D7Gj9A4IiwAE8ABxBoKT9skERnKAgAejLWIlzDAHcBHgBzYAzwzJyIGnycdqLnZIqEZDR0DgpBgBV9B0IIUAATCABbXLBECFQEAMa5hwBrVenCGC4ePg2aYaZMHtSN2YYRpW5efgA5AKX4EGEcAFZ7hB0J9vgIlKdXhAAMIsUoAMjh0UujGYAB9URsPl8fuZBr1HLN8NUXPUmi1wi9zgARFjJBFIq5ojGoLGg3GVfEzIEgn4QDGPa5AA

**Related Issues:**

**Comment by MartinJohns** [comment] 2020-11-24 07:04
And yet another duplicate of #9998.

**Closed** 2020-12-04 18:00 UTC
Labels: Duplicate
