### ISSUE TITLE
Wrong completion list for union type

### ISSUE THREAD

**Issue by arusakov** [Microsoft/TypeScript#11896] opened 2016-10-27 17:33 UTC
**TypeScript Version:** mastet (f307948af01b3586a9b83d38e2bba59d753cec4b)

**VSCode Version:** 1.6.1

**Code**

``` ts
function foo(bar: string | { x: any }) {    
}

foo({
    /*$*/
})
```

**Expected behavior:**
Completion list at `/*$*/` contains `x`

**Actual behavior:** 
Completion list contains `toString` and `valueOf`. But compiler knows, that property `x` is missing:

```
test.ts(4,5): error TS2345: Argument of type '{}' is not assignable to parameter of type 'string | { x: any; }'.                 
  Type '{}' is not assignable to type '{ x: any; }'.                                                                             
    Property 'x' is missing in type '{}'.
```

**Comment by falsandtru** [comment] 2016-10-29 14:01
Maybe #6405

**Comment by mhegazy** [comment] 2016-12-14 00:44
indeed a duplicate of #6405

**Closed by mhegazy** 2016-12-14 00:44 UTC
Labels: Duplicate
