### ISSUE TITLE
Exception accessing undefined array when requesting completions.

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#16537] opened 2017-06-14 22:28 UTC
It's hard for me to repro simply, but start out with the following:

```ts
class C<T, U, V> {}

class D extends C</**/
```

Then start typing at `/**/` to get:

```
[Error - 3:25:29 PM] 'completions' request failed with error.
Error processing request. Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at symbolsToArray (C:\Program Files\nodejs\node_modules\typescript\lib\tsserver.js:27940:20)
    at Object.getExportsOfModuleAsArray [as getExportsOfModule] (C:\Program Files\nodejs\node_modules\typescript\lib\tsserver.js:24293:20)
    at symbolCanbeReferencedAtTypeLocation (C:\Program Files\nodejs\node_modules\typescript\lib\tsserver.js:62854:55)
    at C:\Program Files\nodejs\node_modules\typescript\lib\tsserver.js:62818:36
    at Object.filter (C:\Program Files\nodejs\node_modules\typescript\lib\tsserver.js:1438:25)
    at filterGlobalCompletion (C:\Program Files\nodejs\node_modules\typescript\lib\tsserver.js:62804:27)
    at tryGetGlobalSymbols (C:\Program Files\nodejs\node_modules\typescript\lib\tsserver.js:62800:27)
    at getCompletionData (C:\Program Files\nodejs\node_modules\typescript\lib\tsserver.js:62692:22)
    at Object.getCompletionsAtPosition (C:\Program Files\nodejs\node_modules\typescript\lib\tsserver.js:62312:34)
    at Object.getCompletionsAtPosition (C:\Program Files\nodejs\node_modules\typescript\lib\tsserver.js:74328:35)
```

**Comment by andy-ms** [comment] 2017-06-28 15:11
I can't reproduce this in a fourslash test or in vscode with `typescript@next`.
However, this is probably happening because completions calls `getExportsOfModule` on non-modules. This might be fixed by #16768. It would be nice to have a test case to prove it though.

**Closed** 2017-07-07 17:06 UTC
Labels: Bug
