### ISSUE TITLE
Language service error for quick info

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#13014] opened 2016-12-18 22:38 UTC
1. Create a new package directory
2. `npm install github`
3. write the following file:

   ```ts
   import GH = require("github");

   new GH().activity
   ```

4. Get quick info on the word `activity`

Expected: Quick info.
Actual:

```
TypeError: Cannot read property 'parent' of undefined
    at appendOuterTypeParameters (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:23851:28)
    at getOuterTypeParametersOfClassOrInterface (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:23867:20)
    at getTypeParametersOfClassOrInterface (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:23884:35)
    at appendParentTypeArgumentsAndSymbolName (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:22618:75)
    at walkSymbol (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:22650:25)
    at Object.buildSymbolDisplay (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:22656:21)
    at C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:53274:51
    at mapToDisplayParts (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:53260:9)
    at Object.symbolToDisplayParts (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:53273:16)
    at addFullSymbolName (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:60166:49)
```

**Comment by mhegazy** [comment] 2017-08-23 20:08
seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/14315. reopen if not so.

**Closed by mhegazy** 2017-08-23 20:08 UTC
Labels: Bug
