### ISSUE TITLE
Forgive "No overload matches this call" for union-type arguments, if assignment can satisfy a union of overloads

### ISSUE THREAD

**Issue by Birch-san** [microsoft/TypeScript#44452] opened 2021-06-05 14:48 UTC
# Suggestion

When determining if a union-typed argument is assignable to the parameters of an overloaded function: we should allow the assignment if — for each member in that union — there exists a compatible overload. the returned type should be the union of all applicable overloads.

```ts
// current state of TS compiler, as of TS v4.3.2
function double(val: number): number;
function double(val: string): string;
function double(val: string | number): string | number {
    if (typeof val === 'string') {
        return `${val}${val}`;
    }
    return val*2;
}

const num: number = double(2); // works fine
const str: string = double('hey'); // works fine

const process = (val: string | number): void => {
    double(val); // fails with "No overload matches this call"
    const doubled: string | number = double(val); // fails for same reason
}
```

The externally-visible overloads of `double` are:

```ts
(val: number): number;
(val: string): string;
```

Neither overload (taken individually) can accept a `val: string | number`, but we can see that for each member in the union `string | number`, there **is** a compatible overload.  
There's enough information here to deduce that "assigning either `string` or `number` is supported", and that "if we did so: the result would be either `string` or `number`".

In the current example, the union of applicable overloads `(val: string | number): string | number` **happens** to be equivalent to making the _implementation signature_ visible.  
but this will not be true in the general case — for example if an overload `(val: Date): Date;` existed: it would not be considered applicable (the _implementation signature_ would be required to accommodate it, whereas our union of applicable overloads could exclude it).

## 🔍 Search Terms

```
No overload matches this call.
The call would have succeeded against this implementation, but implementation signatures of overloads are not externally visible.
```

## ✅ Viability Checklist

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

_Elaborated in full above._

## 📃 Motivating Example

_I hope the minimal repro above is sufficiently clear._

A brief summary could be:  
Permit assignment of union-type arguments to overloaded functions, if that assignment can be satisfied by a union of overloads. This eliminates a case where the compiler might reject an assignment, stating "No overload matches this call".

## 💻 Use Cases

A less contrived example is what I'm trying to contribute to the [Snowpack devserver code](https://github.com/snowpackjs/snowpack/blob/77a8b6d5c5f23342d4dcf647be376c8dd57de8ef/snowpack/src/commands/dev.ts#L900) — I receive a request `req: http.IncomingMessage | http2.Http2ServerRequest`, and wish to pluck serializable properties off that union argument, creating a new union `Http1RequestData | Http2RequestData`.

```ts
/**
 * {@link http.IncomingMessage} as a value type -- exposes data properties
 * without exposing access to sockets, streams, methods or iterators.
 */
export type Http1RequestData = Pick<
http.IncomingMessage,
'aborted' | 'httpVersion' | 'httpVersionMajor' | 'httpVersionMinor' | 'complete' | 'headers' | 'rawHeaders' | 'trailers' | 'rawTrailers' | 'method' | 'url'
>
/**
 * {@link http2.Http2ServerRequest} as a value type -- exposes data properties
 * without exposing access to sockets, streams, methods or iterators.
 */
export type Http2RequestData = Pick<
http2.Http2ServerRequest,
'aborted' | 'httpVersion' | 'httpVersionMajor' | 'httpVersionMinor' | 'complete' | 'headers' | 'rawHeaders' | 'trailers' | 'rawTrailers' | 'method' | 'url' | 'authority' | 'scheme'
>
/**
 * {@link http.IncomingMessage} or {@link http2.Http2ServerRequest} as a value type -- exposes data properties
 * without exposing access to sockets, streams, methods or iterators.
 * This is provided so that users of dev-server APIs may make decisions about
 * how to route a request (or transform its response), without being able to perform
 * side-effects upon the request handle.
 */
export type HttpRequestData = Http1RequestData | Http2RequestData;

function isHttp2Request(req: http.IncomingMessage | http2.Http2ServerRequest): req is http2.Http2ServerRequest {
  return req.httpVersionMajor === 2;
}

function dataPropertiesOfRequest(req: http.IncomingMessage): Http1RequestData;
function dataPropertiesOfRequest(req: http2.Http2ServerRequest): Http2RequestData;
function dataPropertiesOfRequest(req: http.IncomingMessage | http2.Http2ServerRequest): HttpRequestData {
  // there's a large number of props common to both request types, but since they have different optionality and readonly-ness:
  // I've opted to resist doing a "destructure common props".
  if (isHttp2Request(req)) {
    const {aborted, httpVersion, httpVersionMajor, httpVersionMinor, complete, headers, rawHeaders, trailers, rawTrailers, method, url, authority, scheme} = req;
    const requestData: Http2RequestData = {aborted, httpVersion, httpVersionMajor, httpVersionMinor, complete, headers, rawHeaders, trailers, rawTrailers, method, url, authority, scheme};
    return requestData;
  }
  const {aborted, httpVersion, httpVersionMajor, httpVersionMinor, complete, headers, rawHeaders, trailers, rawTrailers, method, url} = req;
  const requestData: Http1RequestData = {aborted, httpVersion, httpVersionMajor, httpVersionMinor, complete, headers, rawHeaders, trailers, rawTrailers, method, url};
  return requestData;
}

const server: http.Server | http2.Http2Server = createServer(async (
      req: http.IncomingMessage | http2.Http2ServerRequest,
      res: http.ServerResponse | http2.Http2ServerResponse
    ) => {
  // this assignment fails!
  const requestData: HttpRequestData = dataPropertiesOfRequest(req);

  // this assignment fails too! for brevity I won't show the `convertToSnowpackResponse` function, 
  // or `SnowpackHttpServerResponse` union type — it's the same idea as above.
  // mainly showing this to demonstrate that the problem hit me twice.
  const snowpackResponse: SnowpackHttpServerResponse = convertToSnowpackResponse(requestData, res);
});
```

Other options could be to make the union of overloads externally-visible (which means repeating yourself, and serves counter to the purpose of my providing overloads with correlated parameter/return types):

```ts
function dataPropertiesOfRequest(req: http.IncomingMessage): Http1RequestData;
function dataPropertiesOfRequest(req: http2.Http2ServerRequest): Http2RequestData;
function dataPropertiesOfRequest(req: http.IncomingMessage | http2.Http2ServerRequest): HttpRequestData;
function dataPropertiesOfRequest(req: http.IncomingMessage | http2.Http2ServerRequest): HttpRequestData {
```

Another option is type-narrowing & duplication at the call-site:

```ts
// recall that `type HttpRequestData = Http1RequestData | Http2RequestData;`
let requestData: HttpRequestData | undefined;
if (isHttp2Request(req)) {
  // req is narrowed to http2.Http2ServerRequest; expression returns Http2RequestData
  requestData = dataPropertiesOfRequest(req);
} else {
  // req is narrowed to http.IncomingMessage; expression returns Http1RequestData
  requestData = dataPropertiesOfRequest(req);
}
assert(requestData); // make the variable truthy from now on
```

this wasn't super nice because we had to add a condition, a type-guard, implementation duplication and a truthiness assertion at runtime, purely to satisfy the type-system.

for this particular feature, I have the option of hand-waving a bit — the existing code starts with `req: any`, downstream code assumes `req: http.IncomingMessage`, so I could just tiptoe around that rather than trying to retrofit typesafety.

**Comment by MartinJohns** [comment] 2021-06-05 14:53
Duplicate of #44392 and many more. This is intentional. You're free to add another signature accepting the union type.

**Comment by Birch-san** [comment] 2021-06-05 15:16
@MartinJohns do we know the reason why this is intended? it was unintuitive to me.

**Comment by MartinJohns** [comment] 2021-06-05 15:43
It's computationally too expensive for too little of a benefit. You just picked the most simple case.

https://github.com/microsoft/TypeScript/issues/1805#issuecomment-72902892

**Closed** 2021-06-11 18:00 UTC
Labels: Duplicate
