### ISSUE TITLE
Adding functions to Class Prototype should check type of this

### ISSUE THREAD

**Issue by Zorgatone** [Microsoft/TypeScript#4999] opened 2015-09-28 08:00 UTC
I usually write class method implementations after the class declaration, to separate the code.
In order to do that, I define the method using the prototype property of the class. However I can't get type checking on the `this` variable.

```typescript
class A {
	private x: number;
	method: () => void;
}

A.prototype.method = () => {
	this.x = 'hello'; // No warning because `this` is of type `any`.
};
```

I have to use a workaround for this (that) to statically type it. But I think the compiler should be able to guess the type of `this` on its own. Also if I use `let that: A = this;` the compiler complains about accessing the private variable `that.x`.

I think the compiler should allow using this code pattern, recognize the type of `this` and allow the access of private variables inside prototype's methods.

**Comment by kitsonk** [comment] 2015-09-28 08:23
Dupe of #3694 and being implemented in #4910 in the next release of TypeScript.

**Comment by Zorgatone** [comment] 2015-09-28 08:32
Also the compiled JavaScript catches the wrong `_this` (global window instead of the class), when using the fat arrow function

**Comment by Arnavion** [comment] 2015-09-28 08:58
The fat arrow is working as designed. Fat arrow functions capture lexical this, so if the code in your post is running in global context `this` inside the function will be the global variable. You should use regular functions for that.

For example, try this in babel or any runtime with compliant arrow functions:

```javascript
(function () {
    var y = () => this.x;
    return y.call({ x: 6 }); // 5, not 6
}).call({ x: 5 });
```

**Comment by Zorgatone** [comment] 2015-09-28 09:32
I know that already. I was describing my proposal to allow that syntax to work, when adding to `A.prototype`

**Comment by Arnavion** [comment] 2015-09-28 16:25
That proposal would not be accepted, since it breaks ES semantics of how arrow functions behave.

**Comment by RyanCavanaugh** [comment] 2015-09-28 17:47
What others have said -- this is either addressed by other existing issues, or is not in the scope of TypeScript (e.g. diverging from the ECMAScript specification)

**Closed by RyanCavanaugh** 2015-09-28 17:47 UTC
