### ISSUE TITLE
Regress: Deep recursive type transform gives any

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#29577] opened 2019-01-25 08:43 UTC
**TypeScript Version:**  3.3.0-dev.20190125

**Search Terms:**

It works in 3.1.6, but in 3.2 and 3.3 it gives any

**Code**

```ts
export type Transform<T> = { [K in keyof T]: Transform<T[K]> };
interface User {
    avatar: string;
}

interface Guest {
    displayName: string;
}

interface Product {
    users: (User | Guest)[];
}
declare var product:Transform<Product>;
product.users // any[] 
```

**Expected behavior:**
`Transform<(User | Guest)>[]`
**Actual behavior:**
`any[]`

**Comment by ahejlsberg** [comment] 2019-01-25 15:44
Duplicate of #27881 and `any` results from fix in #27911. With #26063 we map arrays and tuples to transformed arrays and tuples, but because we have to eagerly resolve the element type in order to instantiate an `Array<T>`, we end up triggering a circularity and resolve to `any`.

**Closed** 2019-01-27 18:00 UTC
Labels: Duplicate
