### ISSUE TITLE
TS Compiler has crashed 

### ISSUE THREAD

**Issue by sandy081** [microsoft/TypeScript#36628] opened 2020-02-05 09:59 UTC
Version: 3.8.0-dev.20200128

I am developer from VS Code, today I saw TS compiler got crashed with following error:

```
TypeError: Cannot read property 'kind' of undefined
    at getErrorSpanForNode (/Users/runner/runners/2.164.7/work/1/s/build/node_modules/typescript/lib/typescript.js:13429:22)
    at createDiagnosticForNodeInSourceFile (/Users/runner/runners/2.164.7/work/1/s/build/node_modules/typescript/lib/typescript.js:13389:20)
    at Object.createDiagnosticForNode (/Users/runner/runners/2.164.7/work/1/s/build/node_modules/typescript/lib/typescript.js:13380:16)
    at reportNonExportedMember (/Users/runner/runners/2.164.7/work/1/s/build/node_modules/typescript/lib/typescript.js:36179:50)
    at getExternalModuleMember (/Users/runner/runners/2.164.7/work/1/s/build/node_modules/typescript/lib/typescript.js:36160:33)
    at getTargetOfImportSpecifier (/Users/runner/runners/2.164.7/work/1/s/build/node_modules/typescript/lib/typescript.js:36187:20)
    at getTargetOfAliasDeclaration (/Users/runner/runners/2.164.7/work/1/s/build/node_modules/typescript/lib/typescript.js:36238:28)
    at resolveAlias (/Users/runner/runners/2.164.7/work/1/s/build/node_modules/typescript/lib/typescript.js:36277:30)
    at getSymbol (/Users/runner/runners/2.164.7/work/1/s/build/node_modules/typescript/lib/typescript.js:35137:38)
    at resolveNameHelper (/Users/runner/runners/2.164.7/work/1/s/build/node_modules/typescript/lib/typescript.js:35336:34)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

There was a missing import error in a file that caused this.

Replacing following line

https://github.com/microsoft/vscode/blob/ba25c52127e206e5936f48fb1b429f0f75da92ee/src/vs/workbench/contrib/preferences/browser/settingsTree.ts#L45

with 

`import { getIgnoredSettings } from 'vs/platform/userDataSync/common/settingsSync';`

caused this crash.

**Comment by DanielRosenwasser** [comment] 2020-02-05 10:39
Duplicate of #36614

**Closed** 2020-02-07 18:00 UTC
Labels: Duplicate
