### ISSUE TITLE
Error when treating a Promise as a boolean

### ISSUE THREAD

**Issue by bs85** [microsoft/TypeScript#35435] opened 2019-12-01 23:00 UTC
Treating a Promise as a boolean in an `if` block is currently allowed. Given that it'll always be trueish, I don't think the pattern has any legitimate use.

Turning it into an error would be really useful in code using async validation / assertion functions, e.g.:

```
// always true
if (checkOwnership(subject, account)) {

// should be
if (await checkOwnership(subject, account)) {
```

**Comment by MartinJohns** [comment] 2019-12-02 10:17
Please respect the [issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) and the [issue template for feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md).

---

This is a duplicate of #34717.

**Closed** 2019-12-20 23:10 UTC
Labels: Duplicate
