### ISSUE TITLE
Spread operator "expected X args, got a minimum of Y"

### ISSUE THREAD

**Issue by Ghabriel** [Microsoft/TypeScript#19403] opened 2017-10-22 12:20 UTC
**TypeScript Version:**  2.5.3 / playground

**Code**

```ts
declare function foo(a: string, b: number): void;
type Table = [string, number][];

const table: Table = [["answer", 42]];

for (let pair of table) {
    foo(...pair);
}
```

**Expected behavior:**
Code compiles.

**Actual behavior:**
`Expected 2 arguments, but got a minimum of 0`

This workaround compiles, but I think I shouldn't be forced to destructure the parameters before passing them to the function:
```ts
for (let [a, b] of table) {
    foo(a, b);
}
```

**Comment by mhegazy** [comment] 2017-10-23 18:31
Duplicate of https://github.com/Microsoft/TypeScript/issues/4130

**Comment by mhegazy** [comment] 2017-11-07 00:20
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-11-07 00:20 UTC
Labels: Duplicate
