### ISSUE TITLE
Array destructing from Array constructor, unexpected behavior

### ISSUE THREAD

**Issue by wilomgfx** [Microsoft/TypeScript#26006] opened 2018-07-27 13:29 UTC
**TypeScript Version:**  3.1.0-dev.20180727

**Search Terms:**
Array destructuring, array, spread, spreading, slice, Array constructor
**Code**

```ts
const generateOption = (id: number) => ({
    id,
    // tslint:disable-next-line:object-literal-sort-keys
    checked: Math.random() > 0.5 ? true : false,
    name: 'test' + id,
});

const generateOptions = () => [...Array(100)].map((_, i) => generateOption(i)); //this does not.
const generateOptionsv2 = () => Array.from({ length: 100 }).map((_, i) => generateOption(i)); //expected compilation (works)
const options = generateOptions();
```

**Expected behavior:**
Having a new array of length 100 (indexed)
[How babel transpiles it](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBA5gUzAgTgQygg8gBygS3BgF4YAKfAEwC4YwBXAWwCNUBKEgPnIG8AoGIJhUANAKHAAFgmABrBDRgBZDJIB06MJRCMyHbgAY1AVhgB-GFBT0EMWgDM0AGwgIxQumkYJaAckzQvjAA1MKUYgC-bADcfHygkLCIyOiYuATgECTkHMTcANpqRQCCKOgAnmQAjAYGbAC6aoxoOGRkAPoiwrncyagY2HiEYBRsMfGZSUj9aUOZAG4ATNl6XDClFWr2KDpkPDBOSHBQkrQ1BjBRTS1tnd1rfamDGSP4Y7EJ0DAgc5DZjwN0sMIHpYhNEjAIDoEBs0OVsvkql1Fl0AMxdAAsXWM9XBX2QAHcAMrQhFFNRQ7yw8q4z6wKiyMklMpw6q1BowIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-0%2Cstage-3&prettier=true&targets=&version=6.26.0&envVersion=)
[Trick taken from this article, tested under es6-7 with and without babel and it works](https://itnext.io/heres-why-mapping-a-constructed-array-doesn-t-work-in-javascript-f1195138615a)

**Actual behavior:**
Getting an empty array of length 100 since it does not spread the array after using the `Array` constructor, so calling ` .map()` does not work.

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=const%20generateOption%20%3D%20(id%3A%20number)%20%3D%3E%20(%7B%0D%0A%20%20%20%20id%2C%0D%0A%20%20%20%20%2F%2F%20tslint%3Adisable-next-line%3Aobject-literal-sort-keys%0D%0A%20%20%20%20checked%3A%20Math.random()%20%3E%200.5%20%3F%20true%20%3A%20false%2C%0D%0A%20%20%20%20name%3A%20'test'%20%2B%20id%2C%0D%0A%7D)%3B%0D%0A%0D%0Aconst%20generateOptions%20%3D%20()%20%3D%3E%20%5B...Array(100)%5D.map((_%2C%20i)%20%3D%3E%20generateOption(i))%3B%0D%0Aconst%20generateOptionsv2%20%3D%20()%20%3D%3E%20Array.from(%7B%20length%3A%20100%20%7D).map((_%2C%20i)%20%3D%3E%20generateOption(i))%3B%0D%0Aconst%20options%20%3D%20generateOptions()%3B%0D%0A%0D%0Aconst%20someArray%20%3D%20%5B1%2C%202%2C%203%2C%204%2C%205%5D%0D%0Aconst%20newSome%20%3D%20%5B...someArray%5D%0D%0Aconst%20idk%20%3D%20%5B...Array(100)%5D%20

**Related Issues:** 
no

**Comment by mhegazy** [comment] 2018-07-27 16:41
Duplicate of https://github.com/Microsoft/TypeScript/issues/8856

**Closed** 2018-12-15 18:00 UTC
Labels: Duplicate
