### ISSUE TITLE
Wrong type inference of type variable in generics with circular dependency

### ISSUE THREAD

**Issue by vlazh** [microsoft/TypeScript#30681] opened 2019-04-01 03:43 UTC
**TypeScript Version:**  3.4.1

**Search Terms:** type inference, generic types, union types, distributed types

**Code**

```ts
interface Generic1<T> {
  g: T;
}

interface NonGeneric1 {
  readonly a?: Generic1<number>;
}

type B<A> = A extends Generic1<infer T> | undefined ? T | undefined : never;

type A = B<NonGeneric1['a']>;

const a: A = 'true';
```

**Expected behavior:**

type `A` is `number | undefined`.
 
**Actual behavior:**

With `strictNullChecks` enabled type `A` is `number | {} | undefined`. But you can assign any value to const `a`;
With `strictNullChecks` disabled type `A` is `number`. But you can assign `number | undefined` to const `a`;

With typescript 3.3.4 it worked correctly.
 
**Playground Link:** 

[here](https://www.typescriptlang.org/play/index.html#src=interface%20Generic1%3CT%3E%20%7B%0D%0A%20%20g%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20NonGeneric1%20%7B%0D%0A%20%20readonly%20a%3F%3A%20Generic1%3Cnumber%3E%3B%0D%0A%7D%0D%0A%0D%0Atype%20B%3CA%3E%20%3D%20A%20extends%20Generic1%3Cinfer%20T%3E%20%7C%20undefined%20%3F%20T%20%7C%20undefined%20%3A%20never%3B%0D%0A%0D%0Atype%20A%20%3D%20B%3CNonGeneric1%5B'a'%5D%3E%3B%0D%0A%0D%0Aconst%20a%3A%20A%20%3D%20true%3B%0D%0A)

**Related Issues:**

**Comment by jack-williams** [comment] 2019-04-01 09:10
Type `B` is a distributive conditional type and `NonGeneric['a']` is a union, therefore when instantiating the conditional type it gets applied to each constituent. The reduction looks like this:
- `B<NonGeneric1['a']> => (Generic1<number> | undefiend) extends Generic1<infer T> | undefined ? T | undefined : never;`
- Distribute as below.
- `(Generic1<number> extends Generic1<infer T> | undefined ? T | undefined : never) | (undefined extends Generic1<infer T> | undefined ? T | undefined : never)`

On the right-hand-side we have the conditional type:
```ts
(undefined extends Generic1<infer T> | undefined ? T | undefined : never)
```
which is true, but there are no valid inferences for `T`, so it falls back to the default value `{}`. The resulting combined inferences for `T` are `number` for the left, and `{}` for the right where it failed. This is why we get `number | {} | undefined`.

This type gives the right behaviour:
```ts
type B<A> = [A] extends [Generic1<infer T> | undefined] ? T | undefined : never;
```

On the playground (3.3) I'm seeing the behaviour you describe. Is this a regression when moving to 3.4?

**Comment by vlazh** [comment] 2019-04-01 10:19
Thank you for explanation!
With TS 3.4.1 and without strictNullChecks, type A is number | undefined, but with strictNullChecks, type A is number | {} | undefined.
With TS 3.3 type A is always number | undefined.
Why strictNullChecks in TS 3.4 affects to type inference in conditional types?

**Comment by vlazh** [comment] 2019-04-01 10:26
type B<A> = A extends Generic1<infer T> ? T | undefined : never; - not working with optional properties with TS 3.4, but working with TS 3.3.

**Comment by jack-williams** [comment] 2019-04-01 10:28
As far back as 3.1 I'm still getting `number | {} | undefined` with strict null checks.

[playground](https://typescript-play.js.org/?ts=3.1.6#code/JYOwLgpgTgZghgYwgAgOIRNYCCMAeAFQD5kBvAKGWQHMAuZAgbnIF9zzRJZEUA5AexDpMUbDjKVkUCHAAmggDYBPZHAD89YVlx4QAVwC2AI2hFmbcmCUAHFACE8AQRIBeZI+QQAHpBCyAzmgY2vigMNAMJAA+yHp+EDCgELLIagzIMXGyCUkp9JgAbtDMljYoHm4OAkLBorgA2gDkcI0AumbsCIL+YKr0FciNYFB6EI2MQA)

**Comment by vlazh** [comment] 2019-04-01 10:32
Hmm.. I will check it again...

**Comment by vlazh** [comment] 2019-04-01 15:53
@jack-williams, my apologies I was wrong with my previous code example. It becomes harder to make examples so I show concrete case. Sorry for much code.

```ts
// import { ExcludeKeysOfType, Omit } from '@vzh/ts-types';
export type Omit<
  A extends object,
  K extends
    | keyof A
    | (Extract<keyof A, keyof K> extends never ? never : Pick<K, Extract<keyof A, keyof K>>)
> = Pick<A, Exclude<keyof A, K extends keyof A ? K : keyof K>>;

export type KeysOfType<A extends object, B> = {
  [P in keyof A]: A[P] extends B ? P : never
}[keyof A];

export type ExcludeKeysOfType<A extends object, B> = Pick<A, Exclude<keyof A, KeysOfType<A, B>>>;

// import { Option } from '@vzh/ts-types/fp';
declare abstract class Option<A> {
  get(): A;
}

// import ValidableStoreModel from './ValidableStoreModel';
declare class ValidableStoreModel<Entity extends object> {
  validate(name?: keyof Entity): boolean;
}

// SerializableModel
type JSONPrimitives = string | number | boolean | null | undefined;

type JSONTypes = JSONPrimitives | JSONObject | JSONArray;

interface JSONObject extends Record<string, JSONTypes> {}

interface JSONArray extends ReadonlyArray<JSONTypes> {}

type ExcludeFunctions<A extends object> = ExcludeKeysOfType<A, Function>;

type OnlyProps<A extends object> = ExcludeFunctions<
  Omit<A, keyof ValidableStoreModel<any> & keyof SerializableModel<any>>
>;

interface ValueContainer<A> {
  valueOf: () => A;
}

type UnknownType = string;

type JSONArrayValue<A> = Array<A extends object ? JSONObjectValue<A> : UnknownType>;

type JSONObjectValue<A extends object> = keyof OnlyProps<A> extends never
  ? (A extends ValueContainer<infer R> ? R : {})
  : { [P in keyof OnlyProps<A>]: JSONValue<A[P]> };

type ArrayOrObject<A> = A extends ReadonlyArray<infer T>
  ? JSONArrayValue<T>
  : (A extends object ? JSONObjectValue<A> : UnknownType);

type JSONSomeValue<A> = A extends JSONTypes
  ? A
  : (A extends SerializableModel<infer T>
      ? JSONObjectValue<T>
      : (undefined extends A
          ? ArrayOrObject<Exclude<A, undefined>> | undefined
          : ArrayOrObject<A>));

type JSONValue<A> = A extends Option<infer T> ? JSONSomeValue<T> | undefined : JSONSomeValue<A>;

type JSONModel<Entity extends object> = JSONValue<Entity>;

interface Serializable<A extends object> {
  toJSON(): JSONModel<A>;
}

interface SerializableModel<Entity extends object> extends Serializable<Entity> {
  readonly jsonModel: Entity;
}

// Concrete case
type StoreModel = Partial<Pick<Store, 'accessToken' | 'profile'>>;

class Store implements SerializableModel<StoreModel> {
  readonly jsonModel: StoreModel = this;

  get accessToken(): Option<string> {
    return '' as any;
  }

  get profile(): {} {
    return {};
  }

  toJSON(): JSONModel<StoreModel> {
    throw new Error('Method not implemented.');
  }
}

type A = JSONValue<Store>;
const a: A;
```
With TS 3.3 type A is:
```ts
type A = {
    readonly accessToken?: string | undefined;
    readonly profile?: {} | undefined;
}
```

but with TS 3.4 optional properties are no longer optional:
```ts
type A = {
    readonly accessToken: string | undefined;
    readonly profile: {} | undefined;
}
```

I don't now what is wrong. I have found unknown problem (may be) in `JSONObjectValue` in `{ [P in keyof OnlyProps<A>]: JSONValue<A[P]> }` - here is losing `?` of properties.
If replaced `JSONValue<A[P]>` with `JSONValue` implemetation like this:
`{ [P in keyof OnlyProps<A>]: A[P] extends Option<infer T> ? JSONSomeValue<T> | undefined : JSONSomeValue<A[P]> }` then type A becomes:
```ts
type A = {
    readonly accessToken?: Object | undefined;
    readonly profile?: {} | undefined;
}
```
I'm confused.

**Comment by jack-williams** [comment] 2019-04-01 19:17
Usually when modifiers go missing it's because a previously homomorphic mapped type is no-longer treated as such. I haven't had chance to actually debug your scenario though, I'm afraid.

**Comment by RyanCavanaugh** [comment] 2019-04-01 20:16
@vlazh seems like you have more of a question - if you can get the repro down to a reasonable size we could maybe take a look, but usually these 100-line repros indicate something going wrong from the user code side of things

**Comment by vlazh** [comment] 2019-04-02 02:33
> Usually when modifiers go missing it's because a previously homomorphic mapped type is no-longer treated as such. I haven't had chance to actually debug your scenario though, I'm afraid.

Most likely I am somewhere wrong, but why it works fine with TS 3.2, 3.3 but not working with TS 3.4?

What about this size?
```ts
type Omit<A extends object, K extends string> = Pick<A, Exclude<keyof A, K>>;

declare abstract class Option<A> {
  get(): A;
}

// SerializableModel
type OnlyProps<A extends object> = Omit<A, keyof SerializableModel<any>>;

type JSONObjectValue<A extends object> = { [P in keyof OnlyProps<A>]: JSONValue<A[P]> };

type JSONSomeValue<A> = A extends SerializableModel<infer T>
  ? JSONObjectValue<T>
  : (A extends object ? JSONObjectValue<A> : A);

type JSONValue<A> = A extends Option<infer T> ? JSONSomeValue<T> | undefined : JSONSomeValue<A>;

interface Serializable<A extends object> {
  toJSON(): JSONValue<A>;
}

export default interface SerializableModel<Entity extends object> extends Serializable<Entity> {
  readonly jsonModel: Entity;
}

// Concrete case
interface StoreModel {
  readonly accessToken?: Option<string>;
}

declare class Store implements SerializableModel<StoreModel> {
  readonly jsonModel: StoreModel;

  toJSON(): JSONValue<StoreModel>;
}

type A = JSONValue<Store>;
const a: A = {};
```

**Comment by jack-williams** [comment] 2019-04-02 08:01
That size is way too complex. I've boiled it down to a small issue:
```ts
type Foo = Store extends SerializableModel<infer T> ? T : never;
```
In 3.3 `Foo1` is `StoreModel`; in 3.4 `Foo` is `StoreModel | JSONObjectValue<StoreModel>`. If you take `JSONObjectValue` of `Foo` as a union type you lose the property modifiers.

**Comment by vlazh** [comment] 2019-04-02 08:24
Wow! Thank you!
Looks like TS bug, no?
`SerializableModel` has member `toJSON` (inherited)  which uses type variable of `SerializableModel`. May be inferenced type is overrided from `toJSON`?

**Comment by vlazh** [comment] 2019-04-04 03:44
@RyanCavanaugh, is thit issue still a Question? It maybe necessary change the label to Bug?

**Comment by RyanCavanaugh** [comment] 2019-04-04 04:48
I'm still not seeing a repro that clearly outlines the bug. We did change some inference things between 3.3 and 3.4 so the behavior being different doesn't per se indicate a defect.

**Comment by vlazh** [comment] 2019-04-04 06:48
```ts
// Simple declarations of external deps
type Omit<A extends object, K extends string> = Pick<A, Exclude<keyof A, K>>;

declare abstract class OptionClass<A> {
  get(): A;
}

// Serializable types
type OnlyProps<A extends object> = Omit<A, keyof SerializableModel<any>>;

type JSONObjectValue<A extends object> = { [P in keyof OnlyProps<A>]: JSONValue<A[P]> };

type JSONSomeValue<A> = A extends SerializableModel<infer T>
  ? JSONObjectValue<T>
  : (A extends object ? JSONObjectValue<A> : A);

type JSONValue<A> = A extends OptionClass<infer T>
  ? JSONSomeValue<T> | undefined
  : JSONSomeValue<A>;

interface SerializableModel<Entity extends object> {
  toJSON(): JSONValue<Entity>;
}

// Concrete case
interface StoreModel {
  readonly prop1?: OptionClass<string>;
  readonly prop2?: string;
}

declare class Store implements SerializableModel<StoreModel> {
  toJSON(): JSONValue<StoreModel>;
}

type Foo = Store extends SerializableModel<infer T> ? T : never;
// type Foo = StoreModel | JSONObjectValue<StoreModel>

type A = JSONValue<Store>;
// type A = {
//     readonly prop1: string;
//     readonly prop2: string;
// }
```
[Playground](https://www.typescriptlang.org/play/#src=%2F%2F%20Simple%20declarations%20of%20external%20deps%0D%0Atype%20Omit%3CA%20extends%20object%2C%20K%20extends%20string%3E%20%3D%20Pick%3CA%2C%20Exclude%3Ckeyof%20A%2C%20K%3E%3E%3B%0D%0A%0D%0Adeclare%20abstract%20class%20OptionClass%3CA%3E%20%7B%0D%0A%20%20get()%3A%20A%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Serializable%20types%0D%0Atype%20OnlyProps%3CA%20extends%20object%3E%20%3D%20Omit%3CA%2C%20keyof%20SerializableModel%3Cany%3E%3E%3B%0D%0A%0D%0Atype%20JSONObjectValue%3CA%20extends%20object%3E%20%3D%20%7B%20%5BP%20in%20keyof%20OnlyProps%3CA%3E%5D%3A%20JSONValue%3CA%5BP%5D%3E%20%7D%3B%0D%0A%0D%0Atype%20JSONSomeValue%3CA%3E%20%3D%20A%20extends%20SerializableModel%3Cinfer%20T%3E%0D%0A%20%20%3F%20JSONObjectValue%3CT%3E%0D%0A%20%20%3A%20(A%20extends%20object%20%3F%20JSONObjectValue%3CA%3E%20%3A%20A)%3B%0D%0A%0D%0Atype%20JSONValue%3CA%3E%20%3D%20A%20extends%20OptionClass%3Cinfer%20T%3E%0D%0A%20%20%3F%20JSONSomeValue%3CT%3E%20%7C%20undefined%0D%0A%20%20%3A%20JSONSomeValue%3CA%3E%3B%0D%0A%0D%0Ainterface%20SerializableModel%3CEntity%20extends%20object%3E%20%7B%0D%0A%20%20toJSON()%3A%20JSONValue%3CEntity%3E%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Concrete%20case%0D%0Ainterface%20StoreModel%20%7B%0D%0A%20%20readonly%20prop1%3F%3A%20OptionClass%3Cstring%3E%3B%0D%0A%20%20readonly%20prop2%3F%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20class%20Store%20implements%20SerializableModel%3CStoreModel%3E%20%7B%0D%0A%20%20toJSON()%3A%20JSONValue%3CStoreModel%3E%3B%0D%0A%7D%0D%0A%0D%0Atype%20Foo%20%3D%20Store%20extends%20SerializableModel%3Cinfer%20T%3E%20%3F%20T%20%3A%20never%3B%0D%0A%0D%0Atype%20A%20%3D%20JSONValue%3CStore%3E%3B%0D%0Aconst%20a%3A%20A%20%3D%20%7B%7D%3B%0D%0A)

[Same with TS 3.3](https://typescript-play.js.org/#code/PTAEGUEsFsAcBsCmoAmiDG8CGAnLAXSAewDsBnUIgM1EQA99EcSt5VFYyAofAT1mQB5aJHwAeAIK0GiEigpEARgCsM+ADSgA0tMZyKZfDkgkA5gD5QAXlAAFSOgDWkzQFE6mAK5oxjxL2pQCU0tc3MAbi4uNExcZCxFQzx0fFBYsgpBWEJSAGFsDMlLAG8uUFBTRHwACgBKAC4gyIBfKJAIJkhWSAAvBKRQPgFuIaESeF5bHCJOSV1ZeUoVNUsbYVEXUD8AmnBO7r7FJABZIjR4MSwSXjDInn5kAClwQQA5QWWUgDVWT0Q5+h6RZKVQpVagYqgADatlAJi2-kCgnGk2mswk5gAuo1nm8fvA-pIYZjLM07qNQLjXuAiNBEPjCRjrEF5voOsYDv1EKdzmITFQmKAACrmMqgAD8lJe70++AZ-xFYsa1SkgIWCllEqlbw+oLlv3+TMaElq5Ie2te8qKzNVMjZWRyJHyWEK-MFivKkqpNLpVpFoAAPqBPHJEFQTIgUEqLT76QaincTIwcFQsOhkHsOfBelyeYgLq4SIQ+KzgbKSmL8EQqXUcdKrYXizcWm0wLlSOgcFVkOgXYguEmmKn0xAq1282xSuUu1gUKQJqBYGiAIzixoO4hOgpkMRJEwWSLTxCz+e8RdogBMa9Ae7MLeiGGwXbS29HRGfMAQiDpRYoma62aHCcZz5mI4BjtyIHwBW5RVjWDQWla4HvpB5wRFwrT3AIoAAGJEEQzLIc+apsv+nJHKhoFujgwqWJKQqgI0JCIAAbkwZrYVINhUkhEHoegpCGKAWDGsyxRklwQA)

@RyanCavanaugh, please, look at type `Foo`. Why is it union?

**Comment by vlazh** [comment] 2019-04-06 10:57
I found a solution, but it is not a solution to the problem of circular dependencies in general. It is needed to [create a new type to work around this problem](https://www.typescriptlang.org/play/#src=%2F%2F%20Simple%20declarations%20of%20external%20deps%0D%0Atype%20Omit%3CA%20extends%20object%2C%20K%20extends%20string%3E%20%3D%20Pick%3CA%2C%20Exclude%3Ckeyof%20A%2C%20K%3E%3E%3B%0D%0A%0D%0Adeclare%20abstract%20class%20OptionClass%3CA%3E%20%7B%0D%0A%20%20get()%3A%20A%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Serializable%20types%0D%0Atype%20OnlyProps%3CA%20extends%20object%3E%20%3D%20Omit%3CA%2C%20keyof%20SerializableModel%3Cany%3E%3E%3B%0D%0A%0D%0Atype%20JSONObjectValue%3CA%20extends%20object%3E%20%3D%20%7B%20%5BP%20in%20keyof%20OnlyProps%3CA%3E%5D%3A%20JSONValue%3CA%5BP%5D%3E%20%7D%3B%0D%0A%0D%0Atype%20JSONSomeValue%3CA%3E%20%3D%20A%20extends%20SerializableModel%3Cinfer%20T%3E%0D%0A%20%20%3F%20JSONObjectValue%3CT%3E%0D%0A%20%20%3A%20(A%20extends%20object%20%3F%20JSONObjectValue%3CA%3E%20%3A%20A)%3B%0D%0A%0D%0Atype%20JSONValue%3CA%3E%20%3D%20A%20extends%20OptionClass%3Cinfer%20T%3E%0D%0A%20%20%3F%20JSONSomeValue%3CT%3E%20%7C%20undefined%0D%0A%20%20%3A%20JSONSomeValue%3CA%3E%3B%0D%0A%0D%0Atype%20JSONModel%3CA%20extends%20object%3E%20%3D%20%7B%20%5BP%20in%20keyof%20JSONValue%3CA%3E%5D%3A%20JSONValue%3CA%3E%5BP%5D%20%7D%3B%0D%0A%0D%0Ainterface%20SerializableModel%3CEntity%20extends%20object%3E%20%7B%0D%0A%20%20toJSON()%3A%20JSONModel%3CEntity%3E%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Concrete%20case%0D%0Ainterface%20StoreModel%20%7B%0D%0A%20%20readonly%20prop1%3F%3A%20OptionClass%3Cstring%3E%3B%0D%0A%20%20readonly%20prop2%3F%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20class%20Store%20implements%20SerializableModel%3CStoreModel%3E%20%7B%0D%0A%20%20toJSON()%3A%20JSONModel%3CStoreModel%3E%3B%0D%0A%7D%0D%0A%0D%0Atype%20Foo%20%3D%20Store%20extends%20SerializableModel%3Cinfer%20T%3E%20%3F%20T%20%3A%20never%3B%0D%0A%0D%0Atype%20A%20%3D%20JSONValue%3CStore%3E%3B%0D%0Aconst%20a%3A%20A%20%3D%20%7B%7D%3B%0D%0A): 
```ts
type JSONModel<A extends object> = { [P in keyof JSONValue<A>]: JSONValue<A>[P] };

interface SerializableModel<Entity extends object> {
  toJSON(): JSONModel<Entity>;
}
```
But:
```ts
type Copy<A extends object> = { [P in keyof A]: A[P] };
type JSONModel<A extends object> = Copy<JSONValue<A>>;

interface SerializableModel<Entity extends object> {
  toJSON(): JSONModel<Entity>;
}
```
... [does not work](https://www.typescriptlang.org/play/#src=%2F%2F%20Simple%20declarations%20of%20external%20deps%0D%0Atype%20Omit%3CA%20extends%20object%2C%20K%20extends%20string%3E%20%3D%20Pick%3CA%2C%20Exclude%3Ckeyof%20A%2C%20K%3E%3E%3B%0D%0A%0D%0Adeclare%20abstract%20class%20OptionClass%3CA%3E%20%7B%0D%0A%20%20get()%3A%20A%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Serializable%20types%0D%0Atype%20OnlyProps%3CA%20extends%20object%3E%20%3D%20Omit%3CA%2C%20keyof%20SerializableModel%3Cany%3E%3E%3B%0D%0A%0D%0Atype%20JSONObjectValue%3CA%20extends%20object%3E%20%3D%20%7B%20%5BP%20in%20keyof%20OnlyProps%3CA%3E%5D%3A%20JSONValue%3CA%5BP%5D%3E%20%7D%3B%0D%0A%0D%0Atype%20JSONSomeValue%3CA%3E%20%3D%20A%20extends%20SerializableModel%3Cinfer%20T%3E%0D%0A%20%20%3F%20JSONObjectValue%3CT%3E%0D%0A%20%20%3A%20(A%20extends%20object%20%3F%20JSONObjectValue%3CA%3E%20%3A%20A)%3B%0D%0A%0D%0Atype%20JSONValue%3CA%3E%20%3D%20A%20extends%20OptionClass%3Cinfer%20T%3E%0D%0A%20%20%3F%20JSONSomeValue%3CT%3E%20%7C%20undefined%0D%0A%20%20%3A%20JSONSomeValue%3CA%3E%3B%0D%0A%0D%0Atype%20Copy%3CA%20extends%20object%3E%20%3D%20%7B%20%5BP%20in%20keyof%20A%5D%3A%20A%5BP%5D%20%7D%3B%0D%0Atype%20JSONModel%3CA%20extends%20object%3E%20%3D%20Copy%3CJSONValue%3CA%3E%3E%3B%0D%0A%0D%0Ainterface%20SerializableModel%3CEntity%20extends%20object%3E%20%7B%0D%0A%20%20toJSON()%3A%20JSONModel%3CEntity%3E%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Concrete%20case%0D%0Ainterface%20StoreModel%20%7B%0D%0A%20%20readonly%20prop1%3F%3A%20OptionClass%3Cstring%3E%3B%0D%0A%20%20readonly%20prop2%3F%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20class%20Store%20implements%20SerializableModel%3CStoreModel%3E%20%7B%0D%0A%20%20toJSON()%3A%20JSONModel%3CStoreModel%3E%3B%0D%0A%7D%0D%0A%0D%0Atype%20Foo%20%3D%20Store%20extends%20SerializableModel%3Cinfer%20T%3E%20%3F%20T%20%3A%20never%3B%0D%0A%0D%0Atype%20A%20%3D%20JSONValue%3CStore%3E%3B%0D%0Aconst%20a%3A%20A%20%3D%20%7B%7D%3B%0D%0A).

It still seems like a bug of circular dependencies in 3.4, but unfortunately TS engineers do not want to see about the problem.

**Closed** 2019-07-13 00:00 UTC
Labels: Question
