### ISSUE TITLE
Spread operator does not correctly infer from Record types

### ISSUE THREAD

**Issue by fnimick** [microsoft/TypeScript#40955] opened 2020-10-05 22:53 UTC
**TypeScript Version:**  4.0.2 (& nightly 4.1.0-dev.20201005)

**Search Terms:** spread operator, record type, infer / inference / inferred

**Code**

```ts
const first: Record<string, string> = { foo: 'bar' };

const second = { ...first, baz: '' };

const third = { ...second, qux: '' };

console.log(third.baz);
console.log(second.foo);

```

**Expected behavior:** `second` is of type `Record<string, string> & { baz: string}`; analogous to `third` which is inferred as type `{ baz: string, qux: string }`.

**Actual behavior:** `second` is of type `{ baz: string }` and reports an error accessing any other member.

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-dev.20201005&ssl=1&ssc=12&pln=1&pc=36#code/MYewdgzgLgBAZgSwE7QFwwEoFNRICYA80SCYA5gDQzGlkB8MAvDAN7wgjoDkARgIZIuMAL4BuAFDjQkWBBzg8TVjAB0axCihV+AL25Cxk6dBhQAFskXM2alXOl4qARwCuAD30iJU8BBAAbLBV-EDIACnNLFV0ASgljAKCQ8PsFFTgOOPEgA

**Comment by andrewbranch** [comment] 2020-10-06 21:10
Duplicate of #27273

**Closed** 2020-10-09 18:00 UTC
Labels: Duplicate
