### ISSUE TITLE
Please support SharedWorker.

### ISSUE THREAD

**Issue by Lalavava** [microsoft/TypeScript#36824] opened 2020-02-16 03:45 UTC
## Search Terms

SharedWorker

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jcalz** [comment] 2020-02-16 15:31
This does not seem to be a valid feature request as it does not contain all the required information from the template.  

Likely duplicate of #24323

**Comment by RyanCavanaugh** [comment] 2020-02-21 23:42
SharedWorker

**Closed by RyanCavanaugh** 2020-02-21 23:42 UTC
