### ISSUE TITLE
Type inference regression in 3.7-beta

### ISSUE THREAD

**Issue by leonovalex** [microsoft/TypeScript#33779] opened 2019-10-03 07:39 UTC
**TypeScript Version:**  3.7.0-beta

```ts
type O = { data: string };
type A = () => Promise<O[]>;
type B = () => Promise<O | undefined>;

const f = async (a: A, b: B) => {
    const [_a, _b] = await Promise.all([a(), b()]);
    return _b != null ? _b.data + _a.length : _a.length;
}
```

**Expected behavior:**
Compiles as in 3.6.3

**Actual behavior:**
Errors (Regression)

**Playground Link:** 
https://www.typescriptlang.org/play/index.html?ts=3.7-Beta#code/C4TwDgpgBA8lC8UDeUAmBDY6BcUDOwATgJYB2A5lAL4DcAUKJFAIIJQAUAlAgHxQAKhAPYBbYnggAeGAG0Auj3qNoAITZdeA4WInSoAHygBXUqggAzMhFSK6dAMZDSBKObbo8IUvY44WAGigAI1wVbng+JDooGKhHZ2AoGQB9dEDkoLl3AHd0YkTBUXEIADp0ABty9hl0LkCgrjlOelioQghgI0JSKAyoAEJEUiNKqAB+XqCSjCwoAGpe9BLyiApgAAsoXFTl1fIN+iogA

**Related Issues:**

**Comment by jack-williams** [comment] 2019-10-03 09:14
Duplicate of #33752

**Closed** 2019-10-06 18:00 UTC
Labels: Duplicate
