### ISSUE TITLE
Generic function return value not fully inferred through generic argument

### ISSUE THREAD

**Issue by m-dressler** [microsoft/TypeScript#55553] opened 2023-08-28 21:51 UTC
### 🔎 Search Terms

"typescript generic constraint return type", "typescript generic constraint return type error", "ts 2322", "typescript 2322 constraint return type"

### 🕗 Version & Regression Information

- Tested on nightly & 5.1.6

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20230828#code/MYewdgzgLgBAhjAvDAPAFRgUwB5U2AEwhgCMQQAbTOMGAHxjAFcKKA+ACjgCcBzALhhoAlIIw48hYs1YwA-IyYBbEpm4xB0bgEswvJGxgBvAFAwY2gGYwufJImQyKwmN0xQm3WgAYA3Gdd3T1oAIhD-AF9fIA

### 💻 Code

```ts
const a = <T extends boolean | null>(arg: T): T extends null ? number : string => {
  if (arg === null) return 0;
  return "";
};
```

### 🙁 Actual behavior

Caused a typescript error `Type 'number' is not assignable to type 'T extends null ? number : string'.(2322)`

### 🙂 Expected behavior

No error as argument is used to check type of generic `T` and returns correct return type for function.

**Comment by MartinJohns** [comment] 2023-08-28 22:01
Duplicate of #33912.

**Closed** 2023-09-01 01:27 UTC
Labels: Duplicate
