### ISSUE TITLE
Extract to constant in global scope extracts to local scope, and has bad formatting

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#18845] opened 2017-09-29 17:26 UTC
**TypeScript Version:**  nightly (2.6.0-dev.20170929)

**Code**

```ts
function z () {
    1;
}
```

Select `1` and choose the action "Extract to constant in global scope".

**Expected behavior:**

```ts
function z() {
    newLocal;
}
const newLocal = 1;
```

**Actual behavior:**

```ts
function z () {
    const newLocal = 1;}
```

See also #18844 which made this hard to make a fourslash test for.

**Comment by amcasey** [comment] 2017-10-03 23:19
Inlining `const newLocal = 1;` in place of the original expression statement is by design.  The formatting is, of course, suboptimal.

**Comment by andy-ms** [comment] 2017-10-03 23:44
But it was supposed to extract to *global* scope? I get two options "Extract to constant in enclosing scope" and "Extract to constant in global scope" that do the same thing. What if I want to extract it to *outside* of `z`?

**Comment by amcasey** [comment] 2017-10-03 23:52
The two options should now be distinct: https://github.com/Microsoft/TypeScript/pull/18919.

**Comment by mhegazy** [comment] 2017-10-03 23:53
This should be fixed by https://github.com/Microsoft/TypeScript/pull/18919.

**Comment by mhegazy** [comment] 2017-10-03 23:54
well the formatting is not though.

**Comment by amcasey** [comment] 2017-10-04 00:07
Actually, the formatting is too.

**Closed by amcasey** 2017-10-04 00:07 UTC
Labels: Bug, Domain: Formatter, Domain: Refactorings
