### ISSUE TITLE
Given `Array<T>` const index which not overflow, should indicate element type `T` instead of `T|undefined`

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#52842] opened 2023-02-18 15:44 UTC
# Bug Report

### 🔎 Search Terms

- `Array<T>`
- **const** integer index
- not overflow index
- indicate element type from array and array index
- array element type might be undefined

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
function fn(s: string) {
        console.log(s)
}

function reproduce(input: string[]) {
        switch (reproduce.length) {
                case 0 as const:
                case 1 as const:
                        fn(input[0 as const])
                        break
                default:
                        break
        }
}

const input: string[] = []
switch (input.length) {
        case 0 as const:
        case 1 as const:
                fn(input[0 as const])
                break
        default:
                break
}

```

### 🙁 Actual behavior

```txt
// fn(input[0 as const])
Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
```

### 🙂 Expected behavior

```txt
// fn(input[0 as const])
OK
```

### Additional
I guess there is already an issue.

But seems not easy to find which to track on from tons of issues.

**Comment by MartinJohns** [comment] 2023-02-18 16:31
Duplicate of #38000. Used search terms: `array length in:title`

**Comment by loynoir** [comment] 2023-02-18 17:04
### Background
@MartinJohns

The purpose is parsing column base text into interface.

The column base text definition is in linux kernel.

The column is generated from `str.split`.

Some columns are required, some columns are optional, based on columns length.

### Given
- columns is `Array<string>` or `string[]`
- casting columns into interface
- given const-not-overflow-index


### Actual
- `columns[index]` is `T|undefined`

### Expected
- `columns[index]` is `T`

### Workaround
- columns is `LengthCaseArray<string>`

```ts
// prettier-ignore
type LengthCaseArray<T> =
|[] & {length:0}
|[T] & {length:1}
|[T,T] & {length:2}
|[T,T,T] & {length:3}
|[T,T,T,T] & {length:4}
|[T,T,T,T,T] & {length:5}
|[T,T,T,T,T,T] & {length:6}
|[T,T,T,T,T,T,T] & {length:7}
|[T,T,T,T,T,T,T,T] & {length:8}
|[T,T,T,T,T,T,T,T,T] & {length:9}
|[T,T,T,T,T,T,T,T,T,T] & {length:10}
|[T,T,T,T,T,T,T,T,T,T,T] & {length:11}
|[T,T,T,T,T,T,T,T,T,T,T,T] & {length:12}
|[T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:13}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:14}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:15}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:16}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:17}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:18}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:19}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:20}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:21}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:22}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:23}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:24}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:25}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:26}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:27}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:28}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:29}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:30}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T] & {length:31}
|[T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,...T[]] & {length:number}
```

**Comment by RyanCavanaugh** [comment] 2023-02-23 18:02
This was a well-defined limitation in #39560. We're offering two options here:
 * `noUncheckedIndexedAccess` off, which is convenient in all cases
 * `noUncheckedIndexedAccess` on, which is sound in all cases

Given that we can't fully track all possible array mutations, we don't intend to add a third in-between option, nor unsound behavior in the latter option.

**Closed** 2023-06-21 01:32 UTC
Labels: Suggestion, Declined
