### ISSUE TITLE
Proposal: "as" keyword in structuring/destructuring statement

### ISSUE THREAD

**Issue by eezstreet** [microsoft/TypeScript#42040] opened 2020-12-18 19:42 UTC
This is hopefully pretty simple to understand, but:

This:
```ts
const myObject = {
  someField1,
  someField2: anotherField,
  someField3: someField3 as string
};
```
Should also be able to be typed as this:
```ts
const myObject = {
  someField1,
  someField2: anotherField,
  someField3 as string,
};
```

And likewise, we should be able to do this:
```ts
const { someField1 as string } = myObject;
```

Internally, this is just emitted the same way as:
```ts
const { someField1: someField1 as string } = myObject;
```

A common usecase is with optional interface members:

```ts
interface MyInterface {
  a?: string;
}
```
If you are in a routine where `a` is otherwise guaranteed to be a string (not `undefined`), like this:

```ts
function ReportALength (x: MyInterface): void {
  const { a } = x;
  console.log(a.length); // <-- error, 'a' may be undefined
}

function ReportLengthifValid (x: MyInterface): void {
  const { a } = x;
  if(a !== undefined) {
    ReportALength(x);
  }
}
```

In the current iteration of TypeScript, the fixed code looks like this:

```ts
function ReportALength (x: MyInterface): void {
  const a = x.a as string;
  console.log(a.length); // No error here
}

function ReportLengthifValid (x: MyInterface): void {
  const { a } = x;
  if(a !== undefined) {
    ReportALength(x);
  }
}
```

This is fine for such a small example, but suppose you are taking full advantage of the destructuring statement (like say, if you have a very large object). It might be more wise to do something like this:
```ts
function ReportALength (x: MyInterface): void {
  const { a as string } = x;
  console.log(a.length); // No error here
}

function ReportLengthifValid (x: MyInterface): void {
  const { a } = x;
  if(a !== undefined) {
    ReportALength(x);
  }
}
```
**Limitations:** 
"as" can only be used in this context if the types are trivially convertible. The type may need to be converted to `unknown` first if it is not. For example:

```ts
const myObject = {
// ....
  (someField3 as unknown) as string,
// ....
};
```

Likewise, as in any structuring/destructuring statement, the field name must be valid on the type.

**Breaking behavior:**
This does not break any previous JS or TS behavior. It wasn't valid syntax before to do this, this is just introducing new syntax.

**Comment by DanielRosenwasser** [comment] 2020-12-18 22:50
Looks like a duplicate of #29526

**Closed** 2020-12-21 18:00 UTC
Labels: Duplicate
