### ISSUE TITLE
interface Type inference 

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/TypeScript#20953] opened 2018-01-01 01:03 UTC
**TypeScript Version:**  2.5.2
**Code**

```ts
interface ITest {
  f(x: number): string;
}

class Test implements ITest {
  f(x){
    
  }
}
```

**Expected behavior:**
x is number

**Actual behavior:**
x is any

**Comment by DanielRosenwasser** [comment] 2018-01-01 02:56
Looks like a duplicate of #7011

**Closed by DanielRosenwasser** 2018-01-01 02:56 UTC
Labels: Duplicate
