### ISSUE TITLE
Narrow object types after asserting property types

### ISSUE THREAD

**Issue by ab-pm** [microsoft/TypeScript#47632] opened 2022-01-27 00:51 UTC
## 🔍 Search Terms

type guard narrowing optional properties type assertion

## ⭐ Suggestion

TypeScript can already narrow the types of object properties after testing/asserting their types. However, this does not affect the type of the variable holding the object itself.

## 💻 Motivating Example Code
```ts
interface Wide {
  x: string | number;
}
interface Narrow {
  x: number;
}
function doSomething(val: Narrow): void {}

function example(val: Wide): void {
  if (typeof val.x == 'number') {
    console.log(val.x.toPrecision());
    doSomething(val);
  }
}
```
([Playground](https://www.typescriptlang.org/play?ts=4.5.4#code/JYOwLgpgTgZghgYwgAgOrACYoN4ChnIAeAXMgM5hSgDmyAPsiAK4C2ARtANy4C+uokWIhQA5OFCgB7AO7I8BEo1Yco3PjCYgEYYJJDIMkgMqSWEMAAsaACgBucADakxEmQEpStyZjl9cGrR09ZAhCOBYABwcIO0dSdCwPZC8feWRgGGRrMABPCIhJTPsHADpCZABeCuQAcmZ2aBq3OXwCZAQ9MklokodJaljSwhKwSQAFKAgEYDJdEGs3N242g2NTcysQAeKl1r4eIA))

### 🙁 Current behavior

On the `return result` line, tsc complains:
```text
Argument of type 'Wide' is not assignable to parameter of type 'Narrow'.
  Types of property 'x' are incompatible.
    Type 'string | number' is not assignable to type 'number'.
      Type 'string' is not assignable to type 'number'.
```

### 🙂 Expected behavior

This should typecheck. TypeScript already does know that `val.x` is `number` and not `string` inside the `if` block, as can be seen on the line with `val.x.toPrecision()`. It should also narrow the type of `val` to `{ x: number; }` accordingly, instead of keeping the assumption that it's `Wide`.

## 📃 Use Cases

Using an object after checking it for completeness is quite common. This happens with `typeof` checks or any other type assertions.
This would also be quite useful in constructing objects with optional properties, or when getting a partial object as input to a function, and testing for the existence of a property.

A second motivating example (closer to my original code where this happened and I first assumed a bug, before realising that TypeScript never supported this):

```ts
interface Example {
  x: object;
  y?: unknown // … and some more optional ones
}
function demo(input: Partial<Example>): Example {
  const result = {
    ...input,
    // add some more properties but it's not known whether `x` is in the result
  };
  if (!result.x) throw new Error('Missing x');
  console.log(result.x);
  return result;
}
```
([Playground](https://www.typescriptlang.org/play?ts=4.5.4#code/JYOwLgpgTgZghgYwgAgKIA84FsAOAbFAbwChll0AuZAewCMArCBMAblOQE8B+KgVxADWIagHcQyAPQTkgMgJkcEABNkAZ2pYUWalBTUcYYNRBw8NEBBXEAvsRj9mh8YohaAFKBy8wVAApwoBiYAPBjY+BAAfACUVKG4BMgkZAhGKmDIOiq8eOkAvInsZAB0JR5eADSFktJwispqGshaOsg4UHrQBhbItF7IwGAA5CrIwulCouIiABYQYLNQyAAG6Ev9I6DI8yiZ2WDsVmxkwDDIrgCEuzlF6FFb0+0ioxBPqFDtUK6DALLAKiqgADm5EGUSOyBSIDUBCKeGogNcVzANzB7B0YF4UHESLYViAA))

```text
Type '{ x?: object | undefined; y?: unknown; }' is not assignable to type 'Example'.
  Types of property 'x' are incompatible.
    Type 'object | undefined' is not assignable to type 'object'.
      Type 'undefined' is not assignable to type 'object'.
```
TypeScript already does know that `result.x` is `object` and not missing or `undefined`, so it should be able to narrow the type of `result` to `{ x: object; y?: unknown; }` accordingly.

## Workarounds

For the `Wide`/`Narrow` example, using a discriminated union can solve this, but requires carrying around an additional tag property. It also requires introducing a third type for the `x: string` variant.

A [user-defined type guard](https://2ality.com/2020/06/type-guards-assertion-functions-typescript.html#user-defined-type-guards) like `isNarrow` or [assertion function](https://2ality.com/2020/06/type-guards-assertion-functions-typescript.html#assertion-functions) like `ensureNarrow` can replace the `if` condition, but requires defining an extra function which is very verbose.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by IllusionMH** [comment] 2022-01-27 00:58
Looks like duplicate of #42384

Search: `narrow object by property check `

**Comment by ab-pm** [comment] 2022-01-27 01:30
@IllusionMH Oh indeed. Hidden among 313 other search results. Is there a way to edit the search terms to include the ones I came up with?

**Closed** 2022-02-04 18:00 UTC
Labels: Duplicate
