### ISSUE TITLE
Class interdependency and decorators

### ISSUE THREAD

**Issue by lifaon74** [Microsoft/TypeScript#16395] opened 2017-06-09 12:51 UTC
**TypeScript Version:**  2.3.2
**Build options:**  target: "esnext"

**Code**
In this example, the class A has an attribute decorated with a type B, and the class B has an attribute decorated with a type A.

```ts
function Decorator() {}

class A {
  @Decorator b: B;
}

class B {
  @Decorator a: A;
}
```

Is compiled to (with esnext as target) : 

```js
function Decorator() {
}
class A {
}
__decorate([
    Decorator,
    __metadata("design:type", B)
], A.prototype, "b", void 0);
class B {
}
__decorate([
    Decorator,
    __metadata("design:type", A)
], B.prototype, "a", void 0);
```

**Expected behavior:**
The code should be runnable with es6 like es5.

**Actual behavior:**
Running the code triggers an error : 
```
__metadata("design:type", B)
                              ^
ReferenceError: B is not defined
```

Because class declaration are not [hoisted](https://developer.mozilla.org/en-US/docs/Glossary/Hoisting), the class B doesn't already exists when the decorator of the class A is called.

**Possible solution:**
1) Create a [global](https://github.com/tc39/proposal-global) variable : 
```js
var global = (function() {
  if(typeof global !== 'undefined') return global;
  if(typeof self !== 'undefined') return self;
  if(typeof window !== 'undefined') return window;
  return {};
})();
```
2) Test if class exists or provide Object as default: 
```js
 __metadata("design:type", ('B' in global) ? B : Object)
```

**Comment by mhegazy** [comment] 2017-06-13 23:02
Duplicate of https://github.com/Microsoft/TypeScript/issues/4114 and https://github.com/Microsoft/TypeScript/issues/4521

**Comment by mhegazy** [comment] 2017-08-17 18:07
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-08-17 18:07 UTC
Labels: Duplicate
