### ISSUE TITLE
Type narrowing on properties of object not respected when destructuring into new object

### ISSUE THREAD

**Issue by tubocurarin** [microsoft/TypeScript#46910] opened 2021-11-23 19:02 UTC
# Bug Report

It appears, that when a type is narrowed, the narrowing is ignored when assigning to a technically compatible type.

I skimmed the issue tracker rather quickly, I hope I haven't missed an already known issue with a ticket.

### 🔎 Search Terms

- narrow(ed) 
- destructuring / spread

### 🕗 Version & Regression Information

- TypeScript v4.3.2 & v.4.5.2

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 10 minutes

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAGlC8UDeBYAUFTUCGAuKAzsAE4CWAdgObpZQBG+RZVNWAxoyRZVAD5TkArgBth6AL7p0oSFACaCZK0x5CXFhiwM1zapswcd3CVLRsA9uSJQAHvjiJU+nPgDk2VwBpl9N3S8+hq5sAWiSaOikAGZQABQ2AHRsUACE8IhCogCUSs4WVsBQIPgKjj60CZU2npgA9LVQAKIASs0A8s3lWPVQholsNVA9AKrkFgC24xDkhQAWEMTQwOZQ49gA1tCkhQDu5sTrOJTYFAk+4eFAA)

### 💻 Code

Happens when:

```ts
type X = {
    a: string
    b: string
    c: string | null
}

type Y = {
    a: string
    b: string
    c: string
}

const x: X = {
    a: 'a',
    b: 'b',
    c: 'c',
}

if (x.c !== null) {
    const y: Y = {
        ...x,  // ERROR
    }
}
```
```
error TS2322: Type '{ a: string; b: string; c: string | null; }' is not assignable to type 'Y'.
  Types of property 'c' are incompatible.
    Type 'string | null' is not assignable to type 'string'.
      Type 'null' is not assignable to type 'string'.

20     const y: Y = {
             ~
```

When explicitly passing the field again, it works:
```ts
type X = {
    a: string
    b: string
    c: string | null
}

type Y = {
    a: string
    b: string
    c: string
}

const x: X = {
    a: 'a',
    b: 'b',
    c: 'c',
}

if (x.c !== null) {
    const y: Y = {
        ...x,
        c: x.c,  // WORKS!
    }
}
```

### 🙁 Actual behavior

See above, error is thrown although the "problematic" property was narrowed down to be compatible with the target type in the assignment.

### 🙂 Expected behavior

Should not throw a type error and should not require the workaround in the above code example with the explicit assignment from the narrowed-down field: `c: x.c`

**Comment by fatcerberus** [comment] 2021-11-24 01:05
Narrowing individual properties of an object won’t narrow the containing type except in certain situations, because it’s generally difficult (from a technical standpoint) to do so; if this were possible in general we wouldn’t need to have discriminated unions.

duplicate of #30506.

**Comment by RyanCavanaugh** [comment] 2021-11-24 22:22
See #26645

**Closed by RyanCavanaugh** 2021-11-24 22:22 UTC
Labels: Duplicate
