### ISSUE TITLE
3.6 regression: `error TS2321: Excessive stack depth comparing types 'Function<?>' and 'Function<?>'.`

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#33132] opened 2019-08-29 09:29 UTC
**TypeScript Version:**  3.6.2

**Search Terms:** excessive stack depth regression comparing types function lodash 

**Code**

`tsconfig.json`:

``` jsonc
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,

        // Disable this and you get more information about the errors?
        "strictNullChecks": true
    }
}
```

`package.json`:

```json
{
  "dependencies": {
    "@types/lodash": "4.14.129",
    "typescript": "3.6.2"
  }
}
```

`main.ts`:

```ts
import negate from 'lodash/negate';
```

**Expected behavior:**

Compiles

**Actual behavior:**

```sh-session
$ tsc
error TS2321: Excessive stack depth comparing types 'Function<?>' and 'Function<?>'.


Found 1 error.
```

This error doesn't give any helpful information for debugging.

Upgrading `@types/lodash` to the latest version (4.14.138 at time of writing) seems to fix the issue.

If we disable `strictNullChecks`, we get a bit more information about the error (for some reason?):

```sh-session
$ tsc
error TS2321: Excessive stack depth comparing types 'Function<?>' and 'Function<?>'.

node_modules/@types/lodash/ts3.1/common/common.d.ts:194:15 - error TS2589: Type instantiation is excessively deep and possibly infinite.

194     interface Object<T> extends LoDashImplicitWrapper<T> {
                  ~~~~~~


Found 2 errors.
```

This did not error in TS 3.5, so I think it's a regression?

**Playground Link:** 

**Related Issues:**

**Comment by sandersn** [comment] 2019-08-29 15:48
Conditional types now evaluate more eagerly than before, which means that the assignability cutoff gets hit more. I think this is likely by design, but we should investigate before closing.

**Comment by weswigham** [comment] 2019-08-29 18:36
Actually, this has zero to do with conditional types (which iirc we didn't actually change all _that_ much this release), but everything to do with mapped types and indexed accesses. Specifically, `readonly ListIteratee<?>[]` vs `Many<ListIteratee<?>>`, because it's comparison target also expands forever - `Many<ListIteratee<?>>` becomes `PartialDeep<?>` which becomes `PartialDeep<?[P]>` which expands to `PartialDeep<?[P][P]>` and so on. We blow the comparison stack limit once we start comparing `PartialDeep<?[P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P][P]>` with `readonly ListIteratee<?>[][keyof ? & number & P][keyof ?[P] & keyof readonly ListIteratee<?>[][keyof ? & number & P] & P][keyof ?[P][P] & keyof readonly ListIteratee<?>[][keyof ? & number & P][keyof ?[P] & ... 1 more ... & P] & P][keyof ?[P][P][P] & ... 1 more ... & P][keyof ?[P][P][P][P] & ... 1 more ... & P][keyof...`. For reference, the other side expands `readonly ListIteratee<?>[]` -> `readonly ListIteratee<?>[][keyof ? & number & P]` -> `readonly ListIteratee<?>[][keyof ? & number & P][keyof ?[P] & keyof readonly ListIteratee<?>[][keyof ? & number & P] & P]`.

We probably introduced this in #32071. I think this is fixable with existing mechanisms - we already recognize that the `PartialDeep` type probably infinitely expands - the `ListIteratee`-based type expansion currently avoids that check, as it does not have a symbol with which for us to track how often we've seen derivations of it. I think might be able to modify the deeply nested check to catch it, or at least bail even if only one side is measured as _superduperdeep_. Yes, that is a highly technical term.

**Comment by zetoke** [comment] 2019-08-29 19:00
+1 issue with typeorm in 3.6.2. Rolling back to 3.5 helps.

https://github.com/typeorm/typeorm/issues/4662

**Comment by nappy** [comment] 2019-09-02 11:17
Uprading from 3.5.3 to 3.6.2 gives me this error:

`error TS2321: Excessive stack depth comparing types 'Function' and '{ [K in keyof T]?: Morphism<T[K], T[K]> | { [K in keyof T[K]]?: Morphism<T[K][K], T[K][K]> | { [K in keyof T[K][K]]?: Morphism<T[K][K][K], T[K][K][K]> | { [K in keyof T[K][K][K]]?: Morphism<T[K][K][K][K], T[K][K][K][K]> | { [K in keyof T[K][K][K][K]]?: Morphism<T[K][K][K][K][K], T[K][K][K][K][K]> | { [K in keyof T[K][K][K][K][K]]?: Morphism<T[K][K][K][K][K][K], T[K][K][K][K][K][K]> | { [K in keyof T[K][K][K][K][K][K]]?: Morphism<T[K][K][K][K][K][K][K], T[K][K][K][K][K][K][K]> | { [K in keyof T[K][K][K][K][K][K][K]]?: Morphism<T[K][K][K][K][K][K][K][K], T[K][K][K][K][K][K][K][K]> | { [K in keyof T[K][K][K][K][K][K][K][K]]?: Morphism<T[K][K][K][K][K][K][K][K][K], T[K][K][K][K][K][K][K][K][K]> | { [K in keyof T[K][K][K][K][K][K][K][K][K]]?: Morphism<T[K][K][K][K][K][K][K][K][K][K], T[K][K][K][K][K][K][K][K][K][K]> | { [K in keyof T[K][K][K][K][K][K][K][K][K][K]]?: Morphism<T[K][K][K][K][K][K][K][K][K][K][K], T[K][K][K][K][K][K][K][K][K][K][K]> | any | undefined; } | undefined; } | undefined; } | undefined; } | undefined; } | undefined; } | undefined; } | undefined; } | undefined; } | undefined; } | undefined; }'.`

Unfortunately it does not give me any hint on which dependency is causing this.

**Comment by weswigham** [comment] 2019-09-02 20:12
If anyone having trouble with this could try out the build (that will soon be posted) in https://github.com/microsoft/TypeScript/pull/33144#issuecomment-527235862 and report back/updoot if it fixed your problem, that'd be great. Based on what I've been given, I believe it should, but more input is always appreciated.

**Comment by sam-hunt** [comment] 2019-09-02 21:58
This fixes the issue for me thanks.

**Comment by karol-majewski** [comment] 2019-09-02 22:04
This fixed it for me (or rather for us @OliverJAsh) as well.

(Just a side note: @weswigham I think you meant [this comment](https://github.com/microsoft/TypeScript/pull/33144#issuecomment-527237940) since that's the one with installation instructions.)

**Comment by zetoke** [comment] 2019-09-03 07:37
@weswigham It fixes all the problems for me

**Comment by andrew8er** [comment] 2019-09-03 08:05
I was affected by typeorm/typeorm#4662 and fixed it for me, thanks!

**Comment by nappy** [comment] 2019-09-03 08:43
I can confirm, 3.7.0-insiders.20190902 fixes the issue I posted above.

**Closed** 2019-09-05 00:00 UTC
Labels: Bug, Domain: Indexed Access Types, Domain: Mapped Types

**Comment by enzigma-ajinkya-kumbhar** [comment] 2019-09-05 12:49
I am facing the issue with **typeorm@0.2.16** with **typescript@latest**.
I have even tried downgrading the typescript version to **3.5.2** and **3.5.3** still it did not work for me.

Following is the error for your reference 
```
error TS2321: Excessive stack depth comparing types 'MongoRepository<Entity>' and 'Repository<Entity>'.
node_modules/typeorm/repository/MongoRepository.d.ts(12,22): error TS2589: Type instantiation is excessively deep and possibly infinite.
node_modules/typeorm/repository/MongoRepository.d.ts(45,5): error TS2321: Excessive stack depth comparing types '(optionsOrConditions?: string | number | Date | ObjectID | FindOneOptions<Entity> | Partial<Entity>, maybeOptions?: FindOneOptions<Entity>) => Promise<Entity>' and '{ (id?: string | number | Date | ObjectID, options?: FindOneOptions<Entity>): Promise<Entity>; (options?: FindOneOptions<Entity>): Promise<Entity>; (conditions?: FindConditions<Entity>, options?: FindOneOptions<...>): Promise<...>; }'.
```

**Comment by enzigma-ajinkya-kumbhar** [comment] 2019-09-05 14:46
I have got the solution.This [33259](https://github.com/microsoft/TypeScript/issues/33259) solution worked for the time being and we need the proper solution which will support the latest versions of the typescript.

**Comment by luketanner** [comment] 2019-09-06 03:00
@weswigham That indeed fixed it for me! Thanks!

**Comment by DanielRosenwasser** [comment] 2019-09-09 21:03
Can you all try out `typescript@3.6.3-insiders.20190909` on npm and verify whether that works?

**Comment by sam-hunt** [comment] 2019-09-09 22:02
Works for me thanks. Same successful compilation result as in [3.7.0-insiders.20190902](https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/42509/artifacts?artifactName=tgz&fileId=A82D59BA80DA6FD462A65482799F16EB7C4F6BC924F2F7C4276F7E36EA2B62E702&fileName=/typescript-3.7.0-insiders.20190902.tgz), linked above by @weswigham.

**Comment by OliverJAsh** [comment] 2019-09-10 09:59
@DanielRosenwasser Works for me now in `typescript@3.6.3-insiders.20190909`. Thanks!

**Comment by nappy** [comment] 2019-09-10 13:00
Yes, 3.6.3-insiders.20190909 works for me too.

**Comment by ljosberinn** [comment] 2019-09-11 13:36
Neither the 3.6.3 insiders nor the 3.7.0 insiders currently fix this issue for me in [this repo](https://github.com/ljosberinn/rbx-typescript-issue) - it however might be rbx typings, unsure about that, x-posting to rbx too.
