### ISSUE TITLE
Control Flow Analysis of Aliased Conditions and Discriminants doesn't work with `=== true`

### ISSUE THREAD

**Issue by andrenanninga** [microsoft/TypeScript#49589] opened 2022-06-17 09:57 UTC
# Bug Report

### 🔎 Search Terms

- Control flow
- Type narrowing

### 🕗 Version & Regression Information

This is behavior that exists in every version, expected to work since v4.4 when "Control Flow Analysis of Aliased Conditions and Discriminants" was introduced.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.2#code/LAKAZgrgdgxgLgSwPZQARiUgFAQwE4DmAXKtANZRIDuUAlKgN6iqowoDOcq+BAkuwGU4eBFAKoAvKjgBPAA4BTJGG6FJEqQCJOIsZoDczVEYQrchfkN0F6TECxZso7JABsFAOldIC5gh7gkAFU5RTwAYRx2BSxaWkN7BwB6JNQAOSRUBTw8JDwAGlQqPLJ2bjKFAA9FeAUAEyMAX1ATMx5LYVFxDSlhCAVbI0cON09vXx4A4NDsyOjY+KHUFIdVhwA-TaWVgFEcvIBCVAB5ACMAKwV4VAQy5Wl5BVQAcnJKGmePJtBGoA)

### 💻 Code

```ts
function foo(arg: unknown) {
  const argIsString = typeof arg === "string";
  
  if (argIsString) {
    console.log(arg.toUpperCase());
    // No error, works as expected
  }

  if (argIsString === true) {
    console.log(arg.toUpperCase());
    //          ~~~
    // Error! Object is of type 'unknown'.
  }
}
```

### 🙁 Actual behavior

Using `if (argIsString)` correctly narrows `arg` to type string. Using `if (argIsString === true)` however does not narrow the `arg` parameter to string.

### 🙂 Expected behavior

I expect `if (argIsString)` & `if (argIsString === true)` to have the same behavior in terms of type narrowing in this case.

**Comment by MartinJohns** [comment] 2022-06-17 10:24
Duplicate of #44366. Last duplicate was created not even a day ago: #49573

**Closed** 2022-06-24 07:25 UTC
Labels: Duplicate
