### ISSUE TITLE
_this missing in generated .js when using 2.1.4

### ISSUE THREAD

**Issue by vladeck** [Microsoft/TypeScript#12951] opened 2016-12-15 18:01 UTC
When code is compiled using 2.0.7 I get:

```typescript
__extends(FooView, _super);
function FooView(viewModel) {
    var _this = this;
    _super.call(this, "foo-template", {
        init: function () {
            _this.postInit(_this.model);
        },
        model: viewModel,
        wrap: false,
    });
}
```

However, using 2.1.4 I get:

```typescript
__extends(FooView, _super);
function FooView(viewModel) {
    return _super.call(this, "foo-template", {
        init: function () {
            _this.postInit(_this.model);
        },
        model: viewModel,
        wrap: false,
    }) || this;
}
```

Notice the missing `var _this = this`, yet the code is trying to use it.

Typescript code used (important part):

```typescript
export class FooView extends kendo.View {

    constructor(viewModel: ViewModels.FooViewModel) {
        super("foo-template", {
            init: () => {
                this.postInit(this.model as ViewModels.FooViewModel);
            },
            model: viewModel,
            wrap: false,
        });
    }

    protected postInit(viewModel: ViewModels.FooViewModel): void {
        // ...
    }
}
```

**Comment by mhegazy** [comment] 2016-12-15 18:07
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/12764

can you give `typescript@2.2.0-dev.20161215` a try?

**Comment by vladeck** [comment] 2016-12-15 18:16
It seems so. Using `typescript@2.2.0-dev.20161215` generates (working) code:

```typescript
__extends(FooView, _super);
function FooView(viewModel) {
    var _this = _super.call(this, "foo-template", {
        init: function () {
            _this.postInit(_this.model);
        },
        model: viewModel,
        wrap: false,
    }) || this;
    return _this;
}
```

**Closed** 2016-12-15 18:33 UTC
Labels: Duplicate
