### ISSUE TITLE
JSDoc support @private and @protected annotations within js files

### ISSUE THREAD

**Issue by que-etc** [Microsoft/TypeScript#22047] opened 2018-02-20 12:45 UTC
**TypeScript Version:**  2.8.0-dev.20180217

**Search Terms:**
* jsdoc private
* jsdoc protected

**Code**

```js
class MyClass {
    /**
     * @private
     */
    privateProperty = 'private';

    /**
     * @protected
     */
    protectedProperty = 'protected';
}

const instance = new MyClass();

instance.privateProperty = 'so-much-for-private';
instance.protectedProperty = 'so-much-for-protected';
```

**Expected behavior:**
Following errors should be thrown if `--checkJs` is enabled:
* When accessing private property: `Property 'privateProperty' is private and only accessible within class 'MyClass'.`
* When accessing protected property: `Property 'protectedProperty' is protected and only accessible within class 'MyClass' and its subclasses.`

**Actual behavior:**
`@private` and `@protected` annotations are being ignored.

**Comment by vincedan** [comment] 2018-02-20 13:49
as I known, jsDoc annotation does work for declaration file generation. such as @internal......     try another project which refer to declaration only and test it.

**Comment by que-etc** [comment] 2018-02-20 20:39
It seems that PR https://github.com/Microsoft/TypeScript/pull/21455 provides support of the `@private` annotation.

**Comment by mhegazy** [comment] 2018-02-21 20:16
Duplicate of https://github.com/Microsoft/TypeScript/issues/14009

**Comment by que-etc** [comment] 2018-02-21 20:58
@mhegazy it seems that we got our wires crossed. Issue that you mentioned suggests showing private/protected properties in a suggestions list, while this one suggests making former properties behave seamlessly with those defined in `.ts` files:

```ts
class MyClass {
    private privateProp = 'private';
}

const instance = new MyClass();

// In TS files following error is shown:
// "Property 'privateProperty' is private and only accessible within class 'MyClass'"
instance.privateProp = 'new-value'; 
```

So, I'd expect that in `.js` files, an attempt to access properties marked with `@private` access modifier would raise the same error as in `.ts` files. Of course, only when `--checkJs` flag is enabled.

**Comment by que-etc** [comment] 2018-02-21 21:06
I've just re-read that issue. You are right. Sorry, I wish I had searched better before opening a new ticket.

**Closed** 2018-02-21 21:07 UTC
Labels: Duplicate
