### ISSUE TITLE
Narrowing type of an object property with type guard does not allow us to assign/return the instance as having a narrower prop type.

### ISSUE THREAD

**Issue by IKoshelev** [microsoft/TypeScript#32595] opened 2019-07-28 17:21 UTC
**TypeScript Version:**  3.5.1, 3.5.3

**Search Terms:** guard type-guard property return assignment

**Code**

```ts
type WideProp = {
  prop: (number | string);
}

type NarrowProp = {
  prop: string;
}

function showcase(): NarrowProp {
  const wide: WideProp = {
    prop: 'aaa' as (string | number)
  };

  const guard = (i: (number | string)): i is string => true;

  if(guard(wide.prop)){
    // this works
    const prop: string = wide.prop;

    // this does not?
    let narrow: { prop: string } = wide;

    // and this does not?
    return wide;
  } 
}
```

**Expected behavior:**
Successful type guard check narrowing property `prop` from `string | number` to `string` should allow us to return \ assign containing object instance when a `{ prop: string }` type is expected.

**Actual behavior:**
With successful type guard check we are allowed to assign property `prop` when `string` is expected, but assigning \ returning containing instance as `{ prop: string }` is still forbidden.

**Playground Link:** https://www.typescriptlang.org/play/#code/C4TwDgpgBA6glgEwgBQE4HsxQLxQN4BQUUYGYAXFABQB2ArgLYBGEqUAPlAM7Cpw0BzAJQBuAgF8CBUJCgA5AIaoMAdzSYc+IiTKUefQWMkEAZnRoBjYHHQ1uAC3QqLCrhCpDKi5U-VZCxBa2PFAqiBCU8Eh+mgHEOpiUAOQKqUlQrtT6-AIcUPTMrELa4mLaQTQhAnRKCJpUcJS0jCxsnNmCQp5QcD1c3Lw5OAB8ULx0EGXEcCZU1bVUYUgAdKSYXXHEAPRbY-Zw-SroqADWXNqBwcAJFAMGubhLEKtkU-E7ewdQCOgQ-TToYAAfguUAANhBrjQlKpKHgbnpBoIoOJNE83ttdgoaNdgPt+j8-vlASD4lBUJC6Kg7OiSlAJEA

**Related Issues:**  https://github.com/microsoft/TypeScript/issues/3812

**Comment by jack-williams** [comment] 2019-07-28 18:23
Duplicate of #31755.

**Comment by IKoshelev** [comment] 2019-07-28 19:30
From https://github.com/microsoft/TypeScript/issues/31755
"Narrowing the parent would involve synthesizing new types which would be expensive."

This reasoning seems flawed to me. I'm using TS because I need safe code. If expensive compilation was a problem - I'd be suing plain JS.

**Comment by dragomirtitian** [comment] 2019-07-28 19:37
@IKoshelev There is a balancing act here.. how long are you willing to wait for compilation ? 5s, 10s ? 60s ? How long are you willing to wait for a code completion window to appear before it becomes useless ? 0.5s, 1s? 10s ? 

Not adding features that have limited impact but can seriously degrade performance, keeps typescript usable for all of us.

**Comment by IKoshelev** [comment] 2019-07-28 19:56
@dragomirtitian I don't see how this involves intellisense - I'm returning a var and only its name really needs completion. Once I'm done typing return var name - that's when I expect compiler to check whenever its type is suitable. If it warns me about this error 10 seconds later - it is not a problem compared to the alternative of explicitly casting my instance. I mean, with all the investment into building unit tests and running them before commits, getting a type error 10 seconds later does not seem like a problem to me.

With the --incremental  flag this also won't slow down the build AFAIU.

**Comment by IKoshelev** [comment] 2019-07-28 20:20
@dragomirtitian 

Never mind, got it

```ts
export type NarrowPropTypeByKey<TTarget,
    TKey extends keyof TTarget,
    TNarrow extends TTarget[TKey]> = {
        [key in keyof TTarget]:
        key extends TKey
        /**/ ? TNarrow extends TTarget[key]
        /*  */ ? TNarrow
        /*  */ : TTarget[key]
        /**/ : TTarget[key]
    };

export function narrowArrayElement<TWide, TNarrow extends TWide>(check:(i: TWide) => i is TNarrow ){
    return (i: TWide[]) : i is TNarrow[] => i.every(check); 
}

export function narrowPropType<
    T, 
    TKey extends keyof T, 
    TNarrowedPropType extends T[TKey]>
        (inst: T, key: TKey, guard: (wide:  T[TKey]) => wide is TNarrowedPropType): inst is NarrowPropTypeByKey<T, TKey, TNarrowedPropType> {
    
            const val = inst[key];

    if(guard(val)) {
        return true;
    }

    return false;
}
```

https://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBDAnmYcByBDKUIHcAKOYAKssAEKIDSwiAPMcVgObAwA0AUHD3MTYjigYwAHYATAM5wA1rQgAzPkyisO3XsUzY8QkCInTGLNgG1+tALoA+OAF44Abw29epuYICWo2fKXHVNksALhdXX0FhMSk+ATDXAHoAKiSEuAB+Pm0cXD0DGIC1dyt43mSeVIysrBzSnnK4SuDlExhixEs6uGSmlsC2j07XAF8Abk5OUEhYOAUAV1EAYxhPCB9RGrwAQWwMRABRABtgAFsxGAYAdU9xYHZqnVyowz5r2+sACkWAC2BFmWCH08zWIb2AAEp7LZPHBPEZsrpwc5XFA2HMoD4gSCwaZLJDmjC4Q8criobCAHTAABuwCgiC+v3+4NGcE4wwmU2g8HmSxWazgG0ehAgJDIdDCxHuEoEeWi0g8ij4UtcWk2uGA4mFopQspexHMAhsXSBokkMBB9w8IIE92Ycyw4maH1wN2AzT4BqskLsthdt1h8LVGq1pBQ4IJpvgRIRBCIoYo1FoDHuFkQKZjwbjZFsyN4XVcizWZrgVIwh3ssMj7Us4zCngUHztDo+pcO4MhufCcFRMHRPhgUDmwHGIwmKLRGNmZckw7ZEyQOrBWorubARCdojmJwARrS4AAfOBmqDeZjMuecBeoGPLhyr9dHgen8bszg85arHySb54RYYGcfOG6BqsuuaFpGcB+m6cBLkQK5hGuIrNAA5BgaHIXA-5wB8x6ngeApbruUDghoYxjnA4HFk2UDiBWWLYZuO57oeuGiGeQGEtIrHMGSA5DrWPD1h8go5CGZDOq67DIYhYDIba9o0e2nbdGkMDfESuDQDIkhhJR8Ayc03EVlB5IyQJZSqep0jiBAwDSKIEAwOkYTHPAIl4M0jhwAZj4nmxcDDMZrrmfUaQYKI8BqUSNl2QKjnOeOvaTlBI4BaywxAA

**Closed** 2019-07-28 20:20 UTC
