### ISSUE TITLE
RegExpExecArray is missing a type definition for the groups property

### ISSUE THREAD

**Issue by OmgImAlexis** [microsoft/TypeScript#30921] opened 2019-04-13 22:57 UTC
**TypeScript Version:** I'm using the ts checker with javascript in VS Code so I'm not 100% sure on the version I'm using.

**Search Terms:**
`RegExpExecArray`
`RegExpExecArray groups`
`exec groups`
`regex groups`

**Code**

```ts
// GF116 [GeForce GTX 550 Ti] --> GeForce GTX 550 Ti
const regex = new RegExp(/.+\[(?<gpuname>.+)\]/);
regex.exec('GF116 [GeForce GTX 550 Ti]').groups.gpuname;
```

**Expected behavior:**
No error.

**Actual behavior:**
`Property 'groups' does not exist on type 'RegExpExecArray'.ts(2339)`

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/17094

**Comment by MartinJohns** [comment] 2019-04-14 02:17
Duplicate of #29465.

**Comment by OmgImAlexis** [comment] 2019-04-14 03:07
@MartinJohns looks like `RegExpExecArray` also needs the fix.

Trying the slackbliz from that issue with this code still shows this.
```
Property 'groups' does not exist on type 'RegExpExecArray'.
any
```

```
// GF116 [GeForce GTX 550 Ti] --> GeForce GTX 550 Ti
const regex = new RegExp(/.+\[(?<gpuname>.+)\]/);
regex.exec('GF116 [GeForce GTX 550 Ti]').groups.gpuname;
```

**Comment by MartinJohns** [comment] 2019-04-14 09:19
> Trying the stackblitz from that issue with this code still shows this.

The issue explicitly says that the Stackblitz website is using outdated versions...

When you set your `target` to `es2018`, then your code works. https://github.com/Microsoft/TypeScript/issues/29465#issuecomment-455489648

**Closed** 2019-07-13 00:00 UTC
Labels: Question

**Comment by OmgImAlexis** [comment] 2020-04-09 03:48
Trying this on the playground again no longer works. I tried `es2018`, `es2019`, `es2020` and `esnext`.

Version: `v3.9.0-dev.20200407`
Config: 
![Screen Shot 2020-04-09 at 1 17 29 pm](https://user-images.githubusercontent.com/6525926/78855967-8252bc80-7a64-11ea-950d-e684dbef3303.png)

```ts
const regex = new RegExp(/^.+: ID (?<id>\S+)(?<name>.*)$/);
const line = 'test string';
const groups = regex.exec(line)?.groups;
```

Hovering over `?.groups` shows "Property 'groups' does not exist on type 'RegExpExecArray'.(2339)".

**Comment by counterbeing** [comment] 2020-05-24 15:17
Same on 3.9.3 for me.

**Comment by OmgImAlexis** [comment] 2020-05-24 18:27
This is still an issue. Can it please be reopened?

**Comment by cyrilchapon** [comment] 2020-07-06 09:56
Still an issue, `target` & `lib` => 2020

**Comment by OmgImAlexis** [comment] 2020-07-06 12:21
@RyanCavanaugh please reopen this.
