### ISSUE TITLE
Language service reports error on "export import" use

### ISSUE THREAD

**Issue by quedelsmith** [Microsoft/TypeScript#4727] opened 2015-09-10 19:30 UTC
Using the TypeScript 1.6 beta in an AMD project with the following structure:

In one.ts:
export var something = 7;

In two.ts:
export import Something = require("one");

The project compiles successfully, but the language service for Visual Studio 2013 reports an error "Cannot find module 'one'." in two.ts.

**Comment by DanielRosenwasser** [comment] 2015-09-10 19:35
@quedelsmith are you sure you're using an AMD project? I'm only able to reproduce this error targetting CommonJS (which is not an error, it's a deliberate breaking change - see #2338).

**Comment by mhegazy** [comment] 2015-09-10 19:36
if you are using `--module commonjs` and you are running on node, `require("one")` should be `require("./one")` instead.
if you are not using node, use `--moduleResolution classic`.

**Comment by quedelsmith** [comment] 2015-09-10 19:37
Yes, my csproj file designates amd for both debug and release.

**Comment by DanielRosenwasser** [comment] 2015-09-10 20:05
@paulvanbrenk can you take a look? Does @quedelsmith need to specify something in their csproj to change module resolution? If so, that would seem like a bug.

**Comment by mhegazy** [comment] 2015-09-10 20:08
ooh.. i see the issue now.

**Comment by DanielRosenwasser** [comment] 2015-09-10 20:13
The issue is in an inconsistency between the compiler and language service. Doesn't have to do with the project settings. @mhegazy is working on a fix.

**Comment by mhegazy** [comment] 2015-09-10 21:20
This should be fixed in the next release.

**Closed** 2015-09-10 21:19 UTC
Labels: Bug, Fixed

**Comment by quedelsmith** [comment] 2015-09-10 21:23
Thank you!
