### ISSUE TITLE
Nominal typing support like opaque type

### ISSUE THREAD

**Issue by xiaoxiangmoe** [Microsoft/TypeScript#28515] opened 2018-11-14 06:23 UTC
## Search Terms

Nominal typing/ opaque type
## Suggestion

support https://flow.org/en/docs/types/opaque-types/
## Examples

```js
// @flow
opaque type ID = string;

function identity(x: ID): ID {
  return x;
}
export type {ID};
```
## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jack-williams** [comment] 2018-11-14 08:41
Duplicate of #202, related #4895.

**Closed** 2018-12-13 18:00 UTC
Labels: Duplicate
