### ISSUE TITLE
Typescript Fork ts checker crashes without any details

### ISSUE THREAD

**Issue by ankitrg** [Microsoft/TypeScript#17337] opened 2017-07-21 06:29 UTC
```
Happy[ts]: All set; signaling webpack to proceed.
Starting type checking service...
Using 1 worker with 2048MB memory limit
Watching:
/home/aks/advertkit/app/javascript
/home/aks/advertkit/app/views
/home/aks/advertkit/app/assets/stylesheets
/home/aks/advertkit/app/assets/images
/home/aks/advertkit/node_modules/fork-ts-checker-webpack-plugin/lib/service.js:30
    throw error;
    ^

Error: Debug Failure. 
    at typeToString (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:28777:22)
    at reportRelationError (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:34714:34)
    at isRelatedTo (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:34860:21)
    at checkTypeRelatedTo (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:34697:26)
    at checkApplicableSignature (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:40608:26)
    at resolveCall (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:41011:17)
    at resolveCallExpression (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:41163:20)
    at resolveSignature (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:41398:28)
    at getResolvedSignature (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:41430:26)
    at checkCallExpression (/home/aks/advertkit/node_modules/typescript/lib/typescript.js:41479:29)
ts-loader: Using typescript@2.4.1 and /home/aks/advertkit/tsconfig.json
ts-loader: Using typescript@2.4.1 and /home/aks/advertkit/tsconfig.json

```

Can anyone help me why this is happening or how I can dubug this?

I have posted the same issue on ts-checker repository.
https://github.com/Realytics/fork-ts-checker-webpack-plugin/issues/35

**Comment by RyanCavanaugh** [comment] 2017-07-21 17:04
Same callstack as #16636 - presumably same root cause

Marking Duplicate of #16636

**Comment by mhegazy** [comment] 2017-08-17 17:13
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-08-17 17:13 UTC
Labels: Duplicate
