### ISSUE TITLE
Add side-effect import type statement

### ISSUE THREAD

**Issue by ianschmitz** [microsoft/TypeScript#40051] opened 2020-08-14 18:20 UTC
Apologies if this is a duplicate. My searching yielded _many_ results, but I didn't come across an existing issue.

## Search Terms

> import type side effect

## Suggestion

`import type` was a great addition to TypeScript. However we're currently not able to have side-effect type imports like so:

```ts
import type '@material-ui/lab/themeAugmentation'
```

I'm currently using a workaround:

```ts
import type {} from '@material-ui/lab/themeAugmentation'
```

Using the traditional side-effect import would cause the import statement to be emitted into the runtime code:

```ts
import '@material-ui/lab/themeAugmentation'
```

## Use Cases

I want to be able to `import type` from a module that may change the global types, or do some sort of declaration merging on existing types as in the example above. I want to ensure that this side effect import will have no runtime implications which is what `import type` provides for me.

## Examples

Used for declaration merging in Material UI's `Theme` type: https://material-ui.com/components/about-the-lab/#typescript. I could see uses elsewhere such as importing Jest global definitions in test files without including the types in all source files of the project.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment] 2020-08-14 21:37
Does `/// <reference types="@material-ui/lab/themeAugmentation" />` fit the bill?

**Comment by whzx5byb** [comment] 2020-08-16 08:08
If you are using the "files" property in "tsconfig.json", you can set "include" property to import some global type declarations from .d.ts files

**Comment by DanielRosenwasser** [comment] 2020-08-16 18:25
I think this is a duplicate of #36812

**Comment by ianschmitz** [comment] 2020-08-18 15:42
> I think this is a duplicate of #36812

Ah yes, I figured someone else would have requested this. Thanks for finding it!

Closing in favor of #36812.

**Closed** 2020-08-18 15:42 UTC
Labels: Duplicate
