### ISSUE TITLE
Property assignment in functions called from constructor

### ISSUE THREAD

**Issue by Ionaru** [Microsoft/TypeScript#24446] opened 2018-05-28 15:41 UTC
**TypeScript Version:**  3.0.0-dev.20180526

**Search Terms:** 
Initializer nested function

**Code**
```ts
class Initializer {
    public testValue: string;

    constructor() {
        this.setValue();
    }

    public setValue() {
        this.testValue = 'A value';
    }
}
```
(Compile with `strictNullChecks` and `strictPropertyInitialization` enabled)

**Expected behavior:**
Code compiles because the `testvalue` property is always defined in a class instance. Even though it's not directly in the constructor.

**Actual behavior:**
Compiler gives the error:
```
src/initializer.ts:2:12 - error TS2564: Property 'testValue' has no initializer and is not definitely assigned in the constructor.

2     public testValue: string;
             ~~~~~~~~~
```

**Playground Link:**  
[Link to the playground](http://www.typescriptlang.org/play/#src=class%20Initializer%20%7B%0D%0A%20%20%20%20public%20testValue%3A%20string%3B%0D%0A%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20this.setValue()%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20setValue()%20%7B%0D%0A%20%20%20%20%20%20%20%20this.testValue%20%3D%20'A%20value'%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A)
Enable `strictNullChecks` and `strictPropertyInitialization`

**Related Issues:** 
I did not find any related issues.

**Comment by s-ve** [comment] 2018-05-28 16:10
Seems to be a duplicate of #21132

**Comment by Ionaru** [comment] 2018-05-29 04:43
I'd like to know if this is still a "design limitation" in Typescript 3

**Comment by RyanCavanaugh** [comment] 2018-05-29 04:44
Yes; we have no immediate plans to do aggressive function inlining analysis to prevent/catch more class issues.

**Closed by RyanCavanaugh** 2018-05-29 04:44 UTC
Labels: Duplicate
