### ISSUE TITLE
noUncheckedIndexedAccess does not seem to work on the type level

### ISSUE THREAD

**Issue by asbjornh** [microsoft/TypeScript#46273] opened 2021-10-08 11:58 UTC
# Bug Report

Let me preface this by saying that I realize that this is likely a conscious design decision (seeing as this behavior seems to have existed ever since `noUncheckedIndexedAccess` was introduced). I do think it's highly undesirable though. And sorry in advance if this has already been answered (although I didn't find anything through search)

### 🔎 Search Terms

noUncheckedIndexedAccess

### 🕗 Version & Regression Information

It seems like this has been the behavior ever since `noUnchekedIndexedAccess` was introduced.

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true#code/C4TwDgpgBAglC8UDOwBOBLAdgcwNoF0BuAKGIHoAqCqAFQAsIloBDVaUSKCVVAe1SRQARgFdgyOrxEAbACaYA5OKEQANFGaCABjFyYRAWxWp8WiVLlQsAY2kjZ0LSMwOAZlgiyzFMsWu9MFCgADwAuWD1DY3wEKGc3D1kSf0DxEHDdAAYYxHiId0xPZICggC8M3ABGTJqcuJd8xJJSSmoAdXRgSTEoNmARVEwoDhZMTF5gZmB0AKgfPxLxbAhxRAAeAHl1AGkuYOAIF0EAawgQXlcoDYA+AApecK2oY-DtgEoEa6heXGOiFqoUA6XV6KwGQxGGjGEymMyG8xSQWWwAATLFNjs9gcjs8zhcrncHld1C8oO9Hrhtjkvj8-s1WrBhuBoNw+KgNIIIMFINYDrI5r5EeJmOF9EZuLFkbcqvh1JU3vTAQA5XhMzis-jqFTWZgiJhQLTIlFmOjMMCQQLDVU2OwODSg-qDNWjcaTaazBGLYSiqISxBG6WVWVQeUkIA)

### 💻 Code

```ts
type A = string[];

/** These are type errors but shouldn't be, as `A[number]` should include `undefined` */
const x: A[number] = undefined;
const y: A[0] = undefined;
const z: A[1000] = undefined;
```

The following illustrates how authors might unintentionally introduce unsoundness by including a return type annotation:

```ts
/** Without return type annotation */
const get = <O, K extends keyof O>(o: O, k: K) => o[k];

/** With return type annotation */
const get2 = <O, K extends keyof O>(o: O, k: K): O[K] => o[k];

/** A type error as expected */
const a: number = get([1], 1);

/** No type error, because `get2` happens to include a return type annotation */
const b: number = get2([1], 1);
```

### 🙁 Actual behavior

When doing indexed access on array _types_ (f. ex. `(number[])[number])`), the resulting type does not include `undefined`. This can erode the type safety that `noUncheckedIndexedAccess` provides, without the author realizing it.

This is also the case for `Record` but I haven't included an example for that.

### 🙂 Expected behavior

Property access on an indexed type should resolve to a type that includes `undefined`

**Comment by MartinJohns** [comment] 2021-10-08 12:04
Duplicate of #42471. And I still **strongly** disagree with the expected behaviour. The type should be whatever is stored in the array. According to the type `undefined` is not stored in the array, regardless of `noUncheckedIndexedAccess`.

**Closed** 2021-10-11 11:58 UTC
Labels: Duplicate
