### ISSUE TITLE
Mapping generic types breaks inference/narrowing

### ISSUE THREAD

**Issue by jaredru** [Microsoft/TypeScript#16267] opened 2017-06-05 19:01 UTC
**TypeScript Version:**  2.3.4

**Code**

```ts
interface I {
    x: number | null;
}

function generic<T extends I>(a: T, b: Partial<T>) {
    if (a.x != null) {
        a.x.toFixed(2); // OK
    }

    if (b.x != null) {
        b.x.toFixed(2); // ERROR: Property 'toFixed' does not exist on type 'T["x"]'
    }
}

function notGeneric(a: I, b: Partial<I>) {
    if (a.x != null) {
        a.x.toFixed(2); // OK
    }

    if (b.x != null) {
        b.x.toFixed(2); // OK
    }
}
```

**Expected behavior:**

The mapped generic code should compile without error.

**Actual behavior:**

The mapped generic code does not compile.

For context, the place I'm seeing this issue is React when interacting with `props`.  The React typings for a `Component` are:

```ts
class Component<P, S> {
    props: Readonly<{ children?: ReactNode }> & Readonly<P>;
    // snip
}
```

**Comment by ahejlsberg** [comment] 2017-06-05 21:59
Duplicate of #14091. Fixed by #15576.

**Closed** 2017-06-05 22:15 UTC
Labels: Duplicate, Fixed

**Comment by jaredru** [comment] 2017-06-05 23:43
Ah, I searched but didn't find the dupe.  Sorry about that.  Thanks for the quick follow up!
