### ISSUE TITLE
 Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by Zhennan-Ren** [Microsoft/TypeScript#20528] opened 2017-12-07 03:33 UTC
```
[at-loader]: Child process failed to process the request:  TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:9432:17)
    at assignContextualParameterTypes (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:37839:25)
    at checkFunctionExpressionOrObjectLiteralMethod (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:38136:29)
    at checkExpressionWorker (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:39148:28)
    at checkExpression (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:39077:42)
    at checkBinaryLikeExpression (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:38657:29)
    at checkBinaryExpression (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:38649:20)
    at checkExpressionWorker (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:39169:28)
    at checkExpression (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:39077:42)
    at checkBinaryLikeExpression (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:38657:29)
    at checkBinaryExpression (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:38649:20)
    at checkExpressionWorker (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:39169:28)
    at checkExpression (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:39077:42)
    at checkExpressionStatement (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:41199:13)
    at checkSourceElement (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:43009:28)
    at Object.forEach (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:1500:30)
    at checkBlock (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:40794:16)
    at checkSourceElement (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:43005:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:38178:21)
    at checkDeferredNodes (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:43091:25)
    at checkSourceFileWorker (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:43126:17)
    at checkSourceFile (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:43105:13)
    at getDiagnosticsWorker (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:43169:17)
    at Object.getDiagnostics (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:43155:24)
    at E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:70330:85
    at runWithCancellationToken (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:70295:24)
    at getSemanticDiagnosticsForFileNoCache (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:70318:20)
    at getAndCacheDiagnostics (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:70551:26)
    at getSemanticDiagnosticsForFile (E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:70315:20)
    at E:\works\ucweb\node_modules\_typescript@2.5.3@typescript\lib\typescript.js:70260:24
```

**Comment by RyanCavanaugh** [comment] 2017-12-07 16:14
Likely a duplicate of #16585. Can you upgrade to TypeScript 2.6 and see if that fixes the issue?

**Closed** 2018-01-02 18:40 UTC
Labels: Needs More Info
