### ISSUE TITLE
The type is strange

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/TypeScript#13122] opened 2016-12-22 11:35 UTC
typescript2.1.4

    function f(){
      let x:number|null=null;
      [1].forEach(n=>x=n);
      //The type of x is null
      if(x===null){
        return;
      }
      //The type of x is never
    }

**Comment by krillgar** [comment] 2016-12-22 13:07
Are you complaining that it checks if x is null after you've assigned to it? If so, that would be expected behavior because you've declared x as possibly null. Just because there is a line of code between when it was declared, and when it was checked that assigns it doesn't preclude the ability of the variable to have null assigned to it.

Consider the following example:

`function f(arr){
    let x:number|null=null;
    arr.forEach(n=>n%2 === 0 ? x=n : x=null);
    // The type of x is null
    if(x===null){
        return;
    }
    //The type of x is not null
    }

    f([1]);
    f([1,2]);
    f([2]);
    f([]);`

The problem is that we, as humans, can read that it will never be null in your example. However, to write the code to examine every possibility for what can happen between when the variable is declared as a nullable type, and then when you check to see if it is null would be terribly inefficient. To take my above example further, what should it do if a separate function is called?

**Comment by RyanCavanaugh** [comment] 2016-12-22 19:06
See #11498

Regardless, in this specific example, I'm not sure we'd ever "understand" what was going on - we'd have to special case 0-length and non-0-length arrays at a minimum, and also understand what operations might cause an array to change length.

**Closed by RyanCavanaugh** 2016-12-22 19:06 UTC
Labels: Duplicate
