### ISSUE TITLE
Type assertion too permissive with string literal type

### ISSUE THREAD

**Issue by rdeneau** [microsoft/TypeScript#39275] opened 2020-06-26 12:08 UTC
**TypeScript Version:**  3.9.2

**Search Terms:** type assertion, string literal type

**Code**

```ts
const o = {
    prop: ('a' as const) as 'b' // No error ?!
};
```

**Expected behavior:** Compile error like "Conversion of type "'a'" to type "'b'" may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first." (2352)

**Actual behavior:** No compile error

**Playground Link:** https://www.typescriptlang.org/play/index.html?ssl=2&ssc=5&pln=2&pc=32#code/MYewdgzgLgBCMF4YG8BQMMwA4CcRYC4YAKAcgENSZyIZRIoBKa20gIyoHpOYA5eAKY48OGAH4AhKgC+AblRA

**Comment by MartinJohns** [comment] 2020-06-26 14:01
Duplicate of #37056.

**Comment by rdeneau** [comment] 2020-06-26 14:42
The issues mentioned as being duplicated are closed. Too bad. It's an unexpected behavior.

Yes, it's a "tricky" usage but intuitive and useful. 
Example: when we define our Angular routing modules, we like plain values (like in a config/json file):
- `{ path: 'home' }` ✔️ 
- `{ path: paths.home }` ❌ 

But this path is used elsewhere (in a sidebar for instance). I though this duplication can be securised with type assertions :
- `{ path: 'home' as const as typeof paths.home }` 👌

**Closed** 2020-06-26 15:52 UTC
Labels: Duplicate
