### ISSUE TITLE
Unexpected property access for inner class

### ISSUE THREAD

**Issue by OlegDokuka** [Microsoft/TypeScript#9700] opened 2016-07-13 20:31 UTC
**TypeScript Version:**  1.8.10

**Code**

```ts
export class Builder1 {
    private pipes: { name: string, fn: () => void }[] = [];

    public pipe(fn: () => void) {
        const that = this;

        class Builder2 {
            public on(name: string) {
                that.pipes.push({ name, fn }); //compiller error
                return that;
            }
        }

        return new Builder2();
    }

    public build(): any {
        const server = new Server();

        this.pipes.forEach(({name, fn}) => server.on(name, fn));

        return server;
    }
}
```

**Expected behavior:** Builder2 must have access to private variables of Builder1

**Actual behavior:** Property 'pipes' is private and only accessible within class 'Builder1'

**Comment by RyanCavanaugh** [comment] 2016-07-13 20:56
Duplicate of #7058, which has been fixed

**Closed by RyanCavanaugh** 2016-07-13 20:56 UTC
Labels: Duplicate
