### ISSUE TITLE
No compilation error on later declared variable reference

### ISSUE THREAD

**Issue by koleo9am** [microsoft/TypeScript#57694] opened 2024-03-08 09:38 UTC
### 🔎 Search Terms

variable reference foreach before declaration 

### 🕗 Version & Regression Information

- This is the behavior in every version available on Playground

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.2#code/MYewdgzgLgBADjAXDaAnAlmA5gbQLowC8MOA5AKYAeAhgLZwA25peA3AFBwB0AZiKgFFqwABYAKSkQB8MAN7sYMdDxgTC6ygEo5CxTACeXOAFcI42QF9NHRRfZWOoSLH1ESbIA

### 💻 Code

```ts
const p = [];
p.forEach(x => {
  if (x===x) {
    y.push({});
  }
});
const y = [];
```

### 🙁 Actual behavior

Usage of y in foreeach doesn't lead to compilation error. But it produces a runtime error.

### 🙂 Expected behavior

Compilation error on line `y.push({});`

**Comment by MartinJohns** [comment] 2024-03-08 09:44
Duplicate of #56827 / #11498.

**Closed** 2024-03-11 01:25 UTC
Labels: Duplicate
