### ISSUE TITLE
Typechecking Partial<> works differently for generic types

### ISSUE THREAD

**Issue by jauco** [Microsoft/TypeScript#12751] opened 2016-12-08 08:54 UTC
**TypeScript Version:**  2.1.1 (what's running on the playground)

**Code**
This works
```ts
interface Data {
    a?: "a"|"b",
    b: number,
    c: "a" | "b"
}

type Patch = Partial<Data> 
function copyFields(target: Data, source: Patch): Data {
    for (let id in source) {
        target[id] = source[id];
    }
    return target;
}

function makesrc(): Data { return {b: 1, c: "a"}}


/*1*/copyFields(makesrc(), {d: "d"}); //Should (and does) give an error
/*2*/copyFields(makesrc(), {a: "d"}); //Should (and does) give an error
/*3*/copyFields(makesrc(), {c: "d"}); //Should (and does) give an error

//I don't want to specify all the source properties 
/*4*/copyFields(makesrc(), {b: 2}); //Should not (and doesn't) give an error
/*5*/copyFields(makesrc(), {a: "b"}); //Should not (and doesn't) give an error
```

But the generic version doesn't

```ts
interface Data {
    a?: "a"|"b",
    b: number,
    c: "a" | "b"
}

function copyFields<T>(target: T, source: Partial<T>): T {
    for (let id in source) {
        target[id] = source[id];
    }
    return target;
}

function makesrc(): Data { return {b: 1, c: "a"}}


/*1*/copyFields(makesrc(), {d: "d"}); //Should (and does) give an error
/*2*/copyFields(makesrc(), {a: "d"}); //Should (and does) give an error
/*3*/copyFields(makesrc(), {c: "d"}); //Should (BUT DOES NOT) give an error

//I don't want to specify all the source properties 
/*4*/copyFields(makesrc(), {b: 2}); //Should not (and doesn't) give an error
/*5*/copyFields(makesrc(), {a: "b"}); //Should not (BUT DOES) give an error
```

I expected no change in type safety in the generic version.

**Comment by aluanhaddad** [comment] 2016-12-08 09:45
Error in nightly.

**Comment by timocov** [comment] 2016-12-08 11:32
Workaround. Specify type `T`:
```ts
/*3*/copyFields<Data>(makesrc(), {c: "d"});
/*5*/copyFields<Data>(makesrc(), {a: "b"});
```

**Comment by mhegazy** [comment] 2016-12-08 18:02
duplicate of https://github.com/Microsoft/TypeScript/issues/12633, fixed by https://github.com/Microsoft/TypeScript/pull/12640. should be working as intended in TS 2.1.4

**Closed by mhegazy** 2016-12-08 18:02 UTC

**Comment by jauco** [comment] 2016-12-08 18:15
Thanks! Sorry for reporting the duplicate. I found it hard to find the right keywords to search for.
