### ISSUE TITLE
decorator with 2.6.0-rc and esnext, tsc still transpiles, no way to turn off transpilation even with esnext

### ISSUE THREAD

**Issue by aappddeevv** [Microsoft/TypeScript#19384] opened 2017-10-20 20:07 UTC
**TypeScript Version:**  2.6.0-rc

There is not way to turn off decorator transpilation processing so that it passes through. I use babel for filling and compiling down to my target javascript environment so typically I do not want tsc to transpile modern javascript features. target=esnext helps ensure that tsc assumes that the target environment is quite modern. 

However, if there is a decorator in the ts file, it is translated into __decorate(...) regardless of what settings I might use to try and keep it intact into my next compilation stage, which is babel.

```ts
@freeze
class Foo { ... }
```
Even using esnext as the target, you get in the source:
```javascript
... = __decorate(...)
```
But we really want pass through like many other features of javascript that pass through when esnext is set:
```javascipt
@freeze
class Foo { ... }
```

**Comment by mhegazy** [comment] 2017-10-20 21:23
Duplicate of https://github.com/Microsoft/TypeScript/issues/16882

**Comment by mhegazy** [comment] 2017-11-06 16:51
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-11-06 16:51 UTC
Labels: Duplicate
