### ISSUE TITLE
[Compiler API] `emitBuildInfo` not public in `typescript.d.ts`

### ISSUE THREAD

**Issue by longlho** [Microsoft/TypeScript#30886] opened 2019-04-12 14:01 UTC
Hi guys,

3.4 with `incremental` build support is awesome, but it doesn't seem to get exposed in `Program` type definition so I cannot use it programmatically. Is this intended?

Thanks,

LH

**Comment by longlho** [comment] 2019-04-12 14:24
Nevermind seems like it needs builder API, or is there a way for me to stub `getProgramBuildInfo` somehow?

**Comment by MartinJohns** [comment] 2019-04-12 14:29
Duplicate of #29978.

**Closed** 2019-04-12 17:41 UTC
Labels: Duplicate
