### ISSUE TITLE
Generic mapped as clause regression in 4.7

### ISSUE THREAD

**Issue by samhh** [microsoft/TypeScript#49541] opened 2022-06-14 12:42 UTC
# Bug Report

### 🔎 Search Terms

mapped, generic, as clause

### 🕗 Version & Regression Information

- This changed between versions 4.6.4 and 4.7.2/4.7.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.2#code/PTAEBUAsEsGdQK6wKYBNQBcD2oDuWAnAa1GgDtQAWAOgDZrKAaUAIwQ1FS2VjIHIO+YqQoBDDgBtko2BxoB2agCZQosugXUAzNQBQujAE8ADslABJVAB4AggD5QAXlA2A3PqOnQAeRYArW1BkAA8MZHV4WQJyAHMHZwBvXVBQAG0AaREXVXhLWzsAXQAuUDIECQldAF99VGQAYwlRAjN6rDJZUBjkDF8-EsCQsIjQKNi7AAoASicHPvz9No6OADMnUEHQ8NR4PlE+SamSsorZ0CSUpc6cZ27e-3zp5NAWjAQCCixUvb4clwLqkA)

### 💻 Code

The issue goes away if you remove the `as Id<A>` in `Obj`.

```ts
type Id<A> = A;

type Obj<A extends string> = {
  [K in A as Id<A>]: null
}

declare const getObj: <A extends string>() => Obj<A>

const f = <A extends 'a'>(): null => {
  const o = getObj<A>()
  return o['a' as A]
}
```

### 🙁 Actual behavior

```
1. Type 'Obj<A>[A]' is not assignable to type 'null'.
     Type 'Obj<A>["a"]' is not assignable to type 'null'.
```

### 🙂 Expected behavior

The compiler used to resolve `o['a' as A]` as `null`.

**Comment by nicolas377** [comment] 2022-07-23 23:57
`git bisect`ing locally off this repro landed the first bad commit at 8c060eecaa0a5e317650c23f61372cb375a53fba.

**Comment by nicolas377** [comment] 2022-07-24 00:13
I also narrowed down to [this line](https://github.com/microsoft/TypeScript/pull/47889/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8R15660) in the PR's diff. What to do with it, I'm unsure of, but I thought it might be of use.

**Comment by ahejlsberg** [comment] 2022-08-04 08:30
This is working as intended. The commits above added checks that should have been present in the first place. The issue we have is that when a mapped type includes an `as` clause, we can't _consistently_ reason about the constraint of that mapped type. In the particular example here it is obvious that the constraint is `null` because the `as` clause specifies an identity mapping and the template type `null` doesn't reference the iteration type `K`. However, in most cases the template type does reference the iteration type, and often it isn't even possible to construct a reverse mapping for the `as` clause type.

Also see comment [here](https://github.com/microsoft/TypeScript/issues/48626#issuecomment-1098168620).

**Closed** 2022-08-06 20:00 UTC
Labels: Working as Intended
