### ISSUE TITLE
Compiler 1.8.2 hangs when building an array of two classes

### ISSUE THREAD

**Issue by Tragetaschen** [Microsoft/TypeScript#7293] opened 2016-02-29 11:18 UTC
**TypeScript Version:** 

1.8.2

**Code**

```ts
import {BehaviorSubject} from 'rxjs/Rx';

class Foo extends BehaviorSubject<string> {
}

class Bar extends BehaviorSubject<any>{
}

var ARRAY = [
    Foo,
    Bar,
];

```

The `BehaviorSubject` is a requirement, just using a local, generic class makes it work. I haven't tried further reducing the base class. Once you comment out one of the two array members, the compiler doesn't hang anymore.

Here is my `package.json` snippet:
```
  "devDependencies": {
    "typescript": "1.8.2"
  },
  "dependencies": {
    "rxjs": "5.0.0-beta.2"
  }
```

**Comment by Tragetaschen** [comment] 2016-02-29 22:21
Hmm, isn't this regression introduced with 1.8 not going to be fixed in the 1.8 service release?

**Comment by mhegazy** [comment] 2016-02-29 22:45
We do not know much details about the issue yet, so i can not speculate about which release it will go in.

**Comment by vladima** [comment] 2016-02-29 23:32
1. I don't see  the crash
2. this is not a regression but rather a consequence of the fact that lots of type/method signatures in `rxjs-5.0.0-beta.2` become much more complicated - compilation time when using `rxjs-5.0.0-beta.1` is much smaller than with `beta.2`. We already have a few issues that tracks this behavior. 
```
vladima@vladima-ux31a:~/sources/playground/7293$ cat main.ts 
import {BehaviorSubject} from 'rxjs/Rx';

class Foo extends BehaviorSubject<string> {
}

class Bar extends BehaviorSubject<any>{
}

var ARRAY = [
    Foo,
    Bar,
];
vladima@vladima-ux31a:~/sources/playground/7293$ cat package.json 
{
  "name": "7293",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "typescript": "^1.8.2"
  },
  "dependencies": {
    "rxjs": "^5.0.0-beta.2"
  }
}
vladima@vladima-ux31a:~/sources/playground/7293$ ./node_modules/.bin/tsc --m commonjs main.ts -t es6 --diagnostics 
Files:              60
Lines:           20044
Nodes:           95727
Identifiers:     37260
Symbols:       2089459
Types:          355676
Memory used:   491192K
I/O read:        0.01s
I/O write:       0.02s
Parse time:      0.38s
Bind time:       0.24s
Check time:     13.62s
Emit time:       0.07s
Total time:     14.30s
vladima@vladima-ux31a:~/sources/playground/7293$ npm install rxjs@5.0.0-beta.1 --save
7293@1.0.0 /home/vladima/sources/playground/7293
└── rxjs@5.0.0-beta.1 

npm WARN EPACKAGEJSON 7293@1.0.0 No description
npm WARN EPACKAGEJSON 7293@1.0.0 No repository field.
vladima@vladima-ux31a:~/sources/playground/7293$ ./node_modules/.bin/tsc --m commonjs main.ts -t es6 --diagnostics 
Files:              47
Lines:           19593
Nodes:           89690
Identifiers:     34633
Symbols:       1193175
Types:           39842
Memory used:   104180K
I/O read:        0.01s
I/O write:       0.00s
Parse time:      0.34s
Bind time:       0.22s
Check time:      1.89s
Emit time:       0.03s
Total time:      2.48s
```

**Comment by Tragetaschen** [comment] 2016-03-01 10:10
Ouch:
I try what you did on a Linux machine and it worked (~9 seconds).
I try it on my Windows machine, and it hangs (running for 5 minutes now, on a SP4).

**Comment by vladima** [comment] 2016-03-01 17:50
Can you try to upgrade node on Windows machine to 5 and re-run the test?

**Comment by Tragetaschen** [comment] 2016-03-01 21:43
That works. `v0.12.2` is what's shipping with VS, though.

```
PS C:\Users\kairu\Source\Repos\Typescript-hang> node --version
v5.7.0
PS C:\Users\kairu\Source\Repos\Typescript-hang> .\node_modules\.bin\tsc --m commonjs main.ts -t es6 --diagnostics
Files:              60
Lines:           20044
Nodes:           95727
Identifiers:     37260
Symbols:       2089459
Types:          355676
Memory used:   495664K
I/O read:        0.02s
I/O write:       0.02s
Parse time:      0.26s
Bind time:       0.15s
Check time:      6.72s
Emit time:       0.09s
Total time:      7.22s
```

**Comment by vladima** [comment] 2016-03-01 22:01
this is unfortunate. There were some changes in node 0.12 that significantly regressed performance of TypeScript compiler so this is a known issue.

**Comment by Tragetaschen** [comment] 2016-03-01 22:02
When running against my actual project, the process runs out of memory, though:

```
PS C:\Users\kairu\Source\Repos\Target-sg\App\src\App.Instrument> .\node_modules\.bin\tsc --version
Version 1.8.2
PS C:\Users\kairu\Source\Repos\Target-sg\App\src\App.Instrument> .\node_modules\.bin\tsc -p App --diagnostics

<--- Last few GCs --->

   67568 ms: Scavenge 1418.3 (1514.3) -> 1418.3 (1514.3) MB, 48.5 / 0 ms (+ 0.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   69086 ms: Mark-sweep 1418.3 (1514.3) -> 1413.0 (1514.3) MB, 1510.9 / 0 ms (+ 0.0 ms in 2 steps since start of marking, biggest step 0.0 ms) [last resort gc].
   70571 ms: Mark-sweep 1413.0 (1514.3) -> 1414.0 (1514.3) MB, 1484.5 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000035D73DE3AD1 <JS Object>
    1: propertiesRelatedTo(aka propertiesRelatedTo) [C:\Users\kairu\Source\Repos\Target-sg\App\src\App.Instrument\node_modules\typescript\lib\tsc.js:16210] [pc=000001D2054FAE48] (this=0000035D73D04189 <undefined>,source=0000003E3E0E93C9 <a Type with map 00000364947F3451>
,target=0000025E4C0C6569 <a Type with map 00000364947F3451>,reportErrors=0000035D73D04299 <false>)
    2: objectTypeRelatedT...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

Here is the same using 1.7.5:
```
PS C:\Users\kairu\Source\Repos\Target-sg\App\src\App.Instrument> .\node_modules\.bin\tsc -p App --diagnostics
Files:             466
Lines:           49550
Nodes:          183729
Identifiers:     60901
Symbols:        123768
Types:           51349
Memory used:   166080K
I/O read:        0.04s
I/O write:       0.15s
Parse time:      1.33s
Bind time:       0.37s
Check time:      2.02s
Emit time:       0.50s
Total time:      4.23s
```

**Comment by vladima** [comment] 2016-03-01 22:08
good point, let me check we've regressed

**Comment by Tragetaschen** [comment] 2016-03-01 23:00
I as able to avoid the problem in my code base:

The array of types from the repro was reduced from my angular2 application and contains providers for several services. When I cast all the elements of the array to <any>, then I can successfully use 1.8.2 to compile my project.

So with the equivalent of
```
var ARRAY = [
    <any>Foo,
    <any>Bar,
];
```

I get this:
```
PS C:\Users\kairu\Source\Repos\Target-sg\App\src\App.Instrument> .\node_modules\.bin\tsc --version
Version 1.8.2
PS C:\Users\kairu\Source\Repos\Target-sg\App\src\App.Instrument> .\node_modules\.bin\tsc -p App --diagnostics
Files:             466
Lines:           49654
Nodes:          192369
Identifiers:     68963
Symbols:      17569807
Types:           47212
Memory used:   163919K
I/O read:        0.10s
I/O write:       0.17s
Parse time:      0.78s
Bind time:       0.34s
Check time:      1.99s
Emit time:       0.50s
Total time:      3.61s
```

**Comment by vladima** [comment] 2016-03-01 23:24
I've found the offending commit and now checking if we can partially revert its changes.

**Comment by vladima** [comment] 2016-03-02 03:30
Fix is checked in and should be available on today's nightly build: `typescript@next` on `npm`. Can you give it a try and check if it resolves your issue?

**Comment by Tragetaschen** [comment] 2016-03-02 08:24
I'm running the version published to npm about 1 hour ago, if I understand the UTC timestamp correctly :-), but this doesn't fix this:

```
PS C:\Users\kairu\Source\Repos\Target-sg\App\src\App.Instrument> .\node_modules\.bin\tsc --version
Version 1.9.0-dev.20160302
PS C:\Users\kairu\Source\Repos\Target-sg\App\src\App.Instrument> .\node_modules\.bin\tsc -p App --diagnostics

<--- Last few GCs --->

   76343 ms: Scavenge 1405.2 (1503.3) -> 1405.2 (1503.3) MB, 39.1 / 0 ms (+ 63.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   77758 ms: Mark-sweep 1405.2 (1503.3) -> 1402.6 (1503.3) MB, 1418.2 / 0 ms (+ 156.0 ms in 9 steps since start of marking, biggest step 63.0 ms) [last resort gc].
   79143 ms: Mark-sweep 1402.6 (1503.3) -> 1404.5 (1503.3) MB, 1385.3 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000139B92E3AD1 <JS Object>
    2: objectTypeRelatedTo(aka objectTypeRelatedTo) [C:\Users\kairu\Source\Repos\Target-sg\App\src\App.Instrument\node_modules\typescript\lib\tsc.js:16258] [pc=000001D003672896] (this=00000139B9204189 <undefined>,source=0000036686D6E0D1 <a Type with map 0000022E6BEF0591>,originalSource=0000036686D6E
0D1 <a Type with map 0000022E6BEF0591>,target=000002659D08B0E1 <a Type with map 0000030B3616925...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

Again, casting the array members to `<any>` resolves the issue:

```
 PS C:\Users\kairu\Source\Repos\Target-sg\App\src\App.Instrument> .\node_modules\.bin\tsc -p App --diagnostics
Files:             466
Lines:           49743
Nodes:          192822
Identifiers:     69125
Symbols:      17619128
Types:           47239
Memory used:   152110K
I/O read:        0.02s
I/O write:       0.11s
Parse time:      0.84s
Bind time:       0.36s
Check time:      1.96s
Emit time:       0.52s
Total time:      3.69s
```

**Comment by Tragetaschen** [comment] 2016-03-02 08:48
Using 1.8.2 or today's `next`, I can force Typescript to consume additional 850MiB/800MiB of memory, by commenting out a single member:

```ts
import {BehaviorSubject} from 'rxjs/Rx';

class Foo extends BehaviorSubject<string> { }
class type {
    member: string; // remove me to gain 850MiB memory usage
}
class Bar extends BehaviorSubject<type> { }
var ARRAY = [Foo,Bar];
```
With `member`: 
```
Memory used:    67709K
Parse time:      0.25s
Bind time:       0.15s
Check time:      0.75s
```
Without `member`:
```
Memory used:   920835K
Parse time:      0.33s
Bind time:       0.21s
Check time:     14.88s
```

**Comment by vladima** [comment] 2016-03-02 15:13
I've checked and seems that today's `@next` (`typescript@1.9.0-dev.20160302`) does not contain my changes.

**Comment by Tragetaschen** [comment] 2016-03-03 08:56
Wheee!
```
PS C:\Users\kairu\Source\Repos\Target-sg\App\src\App.Instrument> .\node_modules\.bin\tsc --version
Version 1.9.0-dev.20160303
PS C:\Users\kairu\Source\Repos\Target-sg\App\src\App.Instrument> .\node_modules\.bin\tsc -p App --diagnostics
>>
Files:             466
Lines:           49565
Nodes:          192343
Identifiers:     69004
Symbols:      17594575
Types:           47840
Memory used:   147710K
I/O read:        0.06s
I/O write:       0.09s
Parse time:      0.80s
Bind time:       0.37s
Check time:      2.27s
Emit time:       0.40s
Total time:      3.84s
```

I had to go back a few commits in my code to make it actually crash with 1.8.7. I had changed the contents of the offending array besides the `<any>` cast and it only took a large amount of memory instead of too much.

The 800MiB from my previous post have been reduced to 400MiB with this new nightly (70067K with `member`, 482524K without), so I'd guess there is still something left. Does this warrant a new bug?

I'd like to convince you (and @mhegazy) to put the fix in a service release. Not because it's hitting many people, but because the default Visual Studio experience (with Node 0.12.2) is just incredibly bad when you run into this and the changes in a code base are quite subtle to trigger it. Node 0.12.2 seems to not handle OOMs well and keeps running and VS just crashes out of thin air.

**Comment by vladima** [comment] 2016-03-03 20:15
#7372 ports this fix to the next point release

**Comment by Tragetaschen** [comment] 2016-03-04 21:07
Wonderful. Thanks!

**Comment by vladima** [comment] 2016-03-04 21:57
closing, since the fix is checked-in.

**Closed by vladima** 2016-03-04 21:57 UTC
Labels: Bug, Fixed

**Comment by msklvsk** [comment] 2016-03-13 16:41
just killed a day with this problem (out of memory)
postponing angular update which requires rxjs beta.2, keeping angular on beta.6 until ts 1.8.9

**Comment by danielgerlag** [comment] 2016-03-29 20:13
+1

**Comment by danielgerlag** [comment] 2016-04-01 15:56
Ok, so I get this error using tsc 1.8.9 with Node 4 or Node 5.9, but not with Node 5.0
