### ISSUE TITLE
tsc not recognizing typings in node_modules/@types

### ISSUE THREAD

**Issue by bmurali31** [Microsoft/TypeScript#11109] opened 2016-09-23 20:58 UTC
**TypeScript Version:**  2.0.3

**Code**
tsconfig.json
{
    "compilerOptions": {
        "target": "es2015",
        "jsx": "react",
        "module" :"es2015",
        "allowSyntheticDefaultImports": true,
        "noImplicitAny": true,
        "experimentalDecorators": true,
        "preserveConstEnums": true,
        "sourceMap": true,
        "typeRoots": [
            "node_modules/@types"
        ]
    },
    "compileOnSave": true,
    "exclude": [
        "node_modules"
    ]
}

**tsc could not locate the typings from node_modules/@types folder**. 
It works if I install typings using "typings install"

```ts
// A *self-contained* demonstration of the problem follows...
tsc command fails with the following message. 

index.android.tsx(9,24): error TS2307: Cannot find module 'react'.                                                                       
index.android.tsx(19,8): error TS2307: Cannot find module 'react-native'.                                                                
node_modules/@types/react-native/index.d.ts(19,24): error TS2307: Cannot find module 'react'.                                            
node_modules/@types/react-native/index.d.ts(222,28): error TS2304: Cannot find name 'Component'.

**index.android.tsx** file content

import * as React from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  FlexAlignType,
  ViewStyle,
  TextStyle,
  fetch
} from 'react-native';

```

**Expected behavior:**
tsc should compile without any errors
**Actual behavior:**

**Comment by joselee** [comment] 2016-09-23 21:00
seems somehow related to the issue that I created just before yours:  #11108

**Comment by bmurali31** [comment] 2016-09-23 21:08
@joselee  I am guessing it is something to do with the my tsconfig.json setting. The same tsconfig works fine if I install the typings using "typings install".

**Comment by andy-ms** [comment] 2016-09-23 21:14
Duplicate of #11103

**Closed by andy-ms** 2016-09-23 21:14 UTC
