### ISSUE TITLE
Cannot find module X...

### ISSUE THREAD

**Issue by MCKRUZ** [Microsoft/TypeScript#10567] opened 2016-08-26 19:51 UTC
**TypeScript Version:**  1.8.0

**Code**
I have two projects.  One I'm building general gulp tasks in.  One I'm consuming those general gulp tasks.

Project 1 contains a class called TasksTools that lives in a file called **tasksTools.ts**
```ts
import { existsSync, lstatSync, readdirSync } from 'fs';
import * as gulp from 'gulp';
import * as util from 'gulp-util';
import * as isstream from 'isstream';
import { join } from 'path';
import * as tildify from 'tildify';

export class TasksTools {
	private _gulpConfig: any;

	constructor(config: any) {
		this._gulpConfig = config;
	}

	/**
	 * Loads the tasks within the given path.
	 * @param {string} path - The path to load the tasks from.
	 * @param {any} config		- The configuration file.
	 */
	public loadTasksFromDir(path: string, config: any): void {
		this._readDir(path, taskname => this.registerTask(taskname, path, config));
	}

	/**
	 * Registers the task by the given taskname and path.
	 * @param {string} taskname - The name of the task.
	 * @param {string} path     - The path of the task.
	 * @param {any} config		- The configuration file.
	 */
	public registerTask(taskname: string, path: string, config: any): void {
		const TASK = join(path, taskname);
		gulp.task(taskname, (done: any) => {
			const task = require(TASK);
			if (task.length > 0) {
				return task(config, done);
			}

			const taskReturnedValue = task();
			if (isstream(taskReturnedValue)) {
				return taskReturnedValue;
			}

			// TODO: add promise handling if needed at some point.

			done();
		});
	}

	/**
	 * Reads the files in the given root directory and executes the given callback per found file.
	 * @param {string}   root - The root directory to read.
	 * @param {function} cb   - The callback to execute per found file.
	 */
	private _readDir(root: string, cb: (taskname: string) => void): void {
		if (!existsSync(root)) {
			return;
		}

		walk(root);

		function walk(path: string) {
			let files = readdirSync(path);
			for (let i = 0; i < files.length; i += 1) {
				let file = files[i];
				let curPath = join(path, file);
				if (lstatSync(curPath).isFile() && /\.ts$/.test(file)) {
					let taskname = file.replace(/\.ts$/, '');
					cb(taskname);
				}
				else if (lstatSync(curPath).isDirectory()) { // recurse
					walk(curPath);
				}
			}
		}
	}
}
```

it also has a definitions file that lives in a file called **index.d.ts**

```ts
declare module "@mtm/mtm-ng2-gulp-tasks" {
export class TasksTools {
		public constructor(config: any)

		/**
			* Loads the tasks within the given path.
			* @param {string} path - The path to load the tasks from.
		    * @param {any} config		- The configuration file.
			*/
		public loadTasksFromDir(path: string, config: any): void

		/**
			* Registers the task by the given taskname and path.
			* @param {string} taskname - The name of the task.
			* @param {string} path     - The path of the task.
			* @param {any} config		- The configuration file.
			*/
		public registerTask(taskname: string, path: string, config: any): void
	}
}
```

so I wrap these up and make an NPM library.  Then I import that lib into project 2
Here is my gulp file **gulpfile.ts**
```ts
import * as gulp from 'gulp';
import * as config from './gulp.config';
import * as runSequence from 'run-sequence';
import * as util from 'gulp-util';
// This line doesn't work
import { TasksTools } from '@mtm/mtm-ng2-gulp-tasks';

// If I uncomment this line it works
//import { TasksTools } from './node_modules/@mtm/mtm-ng2-gulp-tasks/utils/momentum.utils';

let _gulpConfig = new config.ProjectConfig();
let _taskTools = new TasksTools(_gulpConfig);

// Load Default Tasks
_taskTools.loadTasksFromDir(_gulpConfig.MOMENTUM_TASKS_DIR, _gulpConfig);

// Load Project Tasks
_taskTools.loadTasksFromDir(_gulpConfig.PROJECT_TASKS_DIR, _gulpConfig);
```
Now when I try to run this I get the error

**Failed to run "C:\TFS\Dev\Momentum.Torques\Client\Gulp\mtm-ng2-gulp-tasks\mtm-ng2-gulp-tasks-test\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
module.js:442
    throw err;
    ^
Error: Cannot find module '@mtm/mtm-ng2-gulp-tasks'**

**Expected behavior:**
I expect that this would work
**Actual behavior:** 
It did not work

**Comment by RyanCavanaugh** [comment] 2016-08-26 19:58
How are you building the gulp task?

**Comment by MCKRUZ** [comment] 2016-08-26 20:04
The idea is that my gulp file utilizes this function to read other files from a directory that creates my tasks.  I can get it to work by directly linking to the file so I know it works.  It just doesn't work when I use the typings reference.

**Comment by MCKRUZ** [comment] 2016-08-26 20:07
I'm going to upload the project and I'll put a link so you can see it happening.

**Comment by MCKRUZ** [comment] 2016-08-26 20:42
https://github.com/MCKRUZ/GulpTypescriptError

Should be up in a few minutes

**Comment by MCKRUZ** [comment] 2016-08-29 13:32
Here is an example https://github.com/MCKRUZ/GulpTypescriptError

**Comment by mhegazy** [comment] 2016-08-29 17:33
running tsc from your repo gives me these errors:

```cmd
c:\test\10567\GulpTypescriptError\mtm-ng2-gulp-tasks\mtm-ng2-gulp-tasks>tsc --v
Version 2.1.0-dev.20160829

c:\test\10567\GulpTypescriptError\mtm-ng2-gulp-tasks\mtm-ng2-gulp-tasks>tsc

1 export * from './utils/momentum.utils.ts';
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~

mtm-ng2-gulp-tasks.ts(1,15): error TS2691: An import path cannot end with a '.ts' extension. Consider importing './utils/momentum.utils' instead.


2 export * from './config/momentum.config.interfaces.ts';
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

mtm-ng2-gulp-tasks.ts(2,15): error TS2691: An import path cannot end with a '.ts' extension. Consider importing './config/momentum.config.interfaces' instead.


3 export * from './config/momentum.config.methods.ts';
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

mtm-ng2-gulp-tasks.ts(3,15): error TS2691: An import path cannot end with a '.ts' extension. Consider importing './config/momentum.config.methods' instead.
```

the errors look right to me.

**Comment by MCKRUZ** [comment] 2016-08-29 19:12
If you run it in studio it compiles just fine.  It doesn't have anything to do with the error that I was originally talking about.  Try running it through studio.

**Comment by mhegazy** [comment] 2016-08-29 19:32
the error is introduced in TS 2.0.2 (post TS 2.0 beta). you should not be requiring a ".ts" file as the file does not exist at runtime, and the compiler will not rewrite this import to `.js`. see https://github.com/Microsoft/TypeScript/issues/9538 and https://github.com/Microsoft/TypeScript/pull/9646 for more details.

I get the same build errors in VS with latest TS drop (has not shipped yet). so looks like the original issue will be fixed with the next release.

**Comment by mhegazy** [comment] 2016-08-29 19:42
nope. fixing the 3 errors leads to a successful build for me from VS and on the commandline.

**Comment by mhegazy** [comment] 2016-08-29 19:43
i am gonna mark this as fixed in TS 2.0 RC for now. feel free to reopen if you see it after installing the next TS version.

**Comment by MCKRUZ** [comment] 2016-08-29 19:45
Sorry sorry...this is my bad.  I accidentally uploaded the file with the fix.  Try pulling again and running it.  If you look at the task runner explorer it will show an error.

**Comment by MCKRUZ** [comment] 2016-08-29 19:45
the line you're looking for is line 5 in gulpfile.ts.  Where it references not the full path.  When I do it like this the task runner explorer doesn't pick up any of the tasks.

**Comment by MCKRUZ** [comment] 2016-08-31 12:06
were you able to get it to error?

**Comment by mhegazy** [comment] 2016-08-31 17:22
Sorry, i did not have time to try it again after your last post.

**Comment by mhegazy** [comment] 2016-08-31 17:36
OK tried again. looks like fixed for me. i am gonna mark it as fixed. if you feel this still an issue please reopen and i would appreciate it if you can provide some additional information why you believe this is a TS issue and not caused by other parts of the tool chain.

**Closed by mhegazy** 2016-08-31 17:36 UTC

**Comment by MCKRUZ** [comment] 2016-08-31 17:41
What version of typescript are you on?

**Comment by mhegazy** [comment] 2016-08-31 17:42
TS 2.0.2: https://blogs.msdn.microsoft.com/typescript/2016/08/30/announcing-typescript-2-0-rc/
