### ISSUE TITLE
Separate Variable Type Check Doesn't Guard Type

### ISSUE THREAD

**Issue by fishcharlie** [microsoft/TypeScript#37855] opened 2020-04-09 06:11 UTC
**TypeScript Version:**  3.8.3

**Search Terms:**

- separate variable type check guard 
- variable type check guard
- variable type guard

**Expected behavior:**

No errors to be thrown.

**Actual behavior:**

When using the variable to check the type, the type of `item` and `itemB` respectively doesn't get narrowed down to the correct type. This works in the first example and it narrows down the type.

This encourages bad practice especially if you are having to repeat the type check over and over. In order to keep code from not becoming repetitive storing that in a variable seems like a much better practice.

**Related Issues:**

None

**Code**
```ts
class User {
    name?: string;
}

type Item = User | string;
const item: Item = Math.random() < .5 ? "Hello World" : new User();

let isItemUser = (item instanceof User);
console.log((item instanceof User) ? item.name : item); // types correct
console.log((isItemUser) ? item.name : item); // types incorrect


//////////////////////////////////////////////////////////////////////////


type ItemB = number | string;
const itemB: ItemB = Math.random() < .5 ? "Hello World" : 2;

let isItemBNumber = (typeof itemB === "number");
console.log((typeof itemB === "number") ? itemB * 100 : itemB); // types correct
console.log((isItemBNumber) ? itemB * 100 : itemB); // types incorrect

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
class User {
}
const item = Math.random() < .5 ? "Hello World" : new User();
let isItemUser = (item instanceof User);
console.log((item instanceof User) ? item.name : item); // types correct
console.log((isItemUser) ? item.name : item); // types incorrect
const itemB = Math.random() < .5 ? "Hello World" : 2;
let isItemBNumber = (typeof itemB === "number");
console.log((typeof itemB === "number") ? itemB * 100 : itemB); // types correct
console.log((isItemBNumber) ? itemB * 100 : itemB); // types incorrect

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=22&pc=1#code/MYGwhgzhAECqEFMBO0DeAoaXoDswFsEB+ALmggBckBLHAcwG50BfddCgTwAcFoBJCgnzQAvHEQoAPuSq1G6YAHsclaNUH4yAoaOgBZMBQAWAOiRgcAE0X4AFAEpoAHmgmArNCLQARAAkEICCK0ADqikgglt7QZDgIAO7iyA5M6CAIFGoQ2vjwyLq26jq0lBbACIoAZklI9kxKKorpJkF0toUaaioUZRXVebWeahomeIQxw0J10AD0M9CcPDBKSEgIwBQKyhBNCC2KbYXZGgOOXkX4owS8ZBfTcwvcCDC0K2sbbOhz3z+-f-8AwFA4GAz6LXg5ABCuhwAFd8AAjfLSSg0ej1baZC6QrQaaFiAzGMwWax2RwudxDPwBIKhcKRaJkABMqXSWOOQkhADl4UiUGJbOCqpN8PiRGJvHDEchvHUto1mq12kLqtjROKfFK+bKhmqAFTQACMAAZjRNsfd5uDluF3psGjtFQd2tQOaKedLBuc8dADSazbc8ZbHksum91psgA)

**Comment by MartinJohns** [comment] 2020-04-09 06:56
Duplicate of #12184.

**Closed** 2020-04-12 18:00 UTC
Labels: Duplicate
