### ISSUE TITLE
octal escapes are not handled correctly in string literal types

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#24209] opened 2018-05-17 18:32 UTC
**TypeScript Version:**  2.9.0-rc

**Search Terms:**  type octal

**Code**

```ts
const a: '\1' = '1'; // 'a' is of type '1' and contains '1'
const b: '\1' = '\1'; // 'b' is of type '1', but contains '\u0001'
const c = '\1'; // same as 'b'
```

**Expected behavior:**

Octal escapes in string literals are handled correctly.

For LiteralTypeNodes I would probably prefer a grammar error, but type inference also needs to handle octal escapes.

**Actual behavior:**

Octal escapes are ignored when converting a StringLiteral to a LiteralType.

**Playground Link:** https://agentcooper.github.io/typescript-play/?target=5#code/MYewdgzgLgBAhgLhgcgDoEZkwLwswbhgHoiU4sBLCGEAMxigE8AHAUzyzjABMZQwocCpA4AoftBgAjJGkw4UGZIRIoplanQYt2yTABppAV1j9Bw6miMAGW5nHhJwBXOXFSEOAFt2cS+qA

**Related Issues:**

**Comment by ajafff** [comment] 2018-05-17 19:09
It seems like this is not specific to literal types. This is caused by incorrect parsing of octal escape sequences in every StringLiteral.

**Comment by DanielRosenwasser** [comment] 2018-05-17 19:27
Duplicate of #396.

**Comment by ajafff** [comment] 2018-05-17 19:32
#396 is about making octal escape sequences an error. Only https://github.com/Microsoft/TypeScript/issues/396#issuecomment-330512903 mentions some difficulties with the scanner / parser.

However, I'm ok with closing this as duplicate. I hope nobody uses octal escape sequences anymore so the type checking inconsistencies are not a problem in real world code.

**Closed** 2018-06-02 19:56 UTC
Labels: Duplicate
