### ISSUE TITLE
Type's generic type constraint on member level

### ISSUE THREAD

**Issue by Igorbek** [microsoft/TypeScript#1290] opened 2014-11-27 22:40 UTC
> This is a suggestion for spec change.
### Problem

Sometimes type's members could only be applicable with some restrictions of enclosing type parameter (generic type constraints).

For instance, this is use case of RxJS:

``` ts
var xs: Observable<Observable<string>>;
xs.mergeAll();  // mergeAll is applicable here

var ys: Observable<string>;
ys.mergeAll();  // mergeAll is NOT applicable here
```

Original Rx.NET [Merge](http://msdn.microsoft.com/en-us/library/hh229740%28v=vs.103%29.aspx) method implemented as C# extension method on type `IObservable<IObservable<T>>`. In RxJS it's implemented as an instance method.

Current RxJS typescript definition just use [unsafe trick](https://github.com/Reactive-Extensions/RxJS/blob/master/ts/rx-lite.d.ts#L258):

``` ts
export interface Observable<T> {
  ...
  mergeAll(): T;
  ...
}
```

But it can be still unsafely called for as instance of any `Observable<T>`.
#### Extension methods

Something like C# extension methods. But don't think it's useful in such cases.

``` ts
declare extensions {
  mergeAll<T>(this Observable<Observable<T>> source): Observable<T>;
}
```

BTW, extensions method could be other cool feature, which change call method (from instance-like to static-like).
#### Multiple interface definitions with different constraints

``` ts
interface A<T> { x(): void; }
interface A<T extends B> { y(): void; }
var a: A<number>;
var b: A<B>;

a.x(); b.x(); // ok
b.y(); // ok
a.y(); // error
```
#### Member-level constraints with reference to enclosing type arguments

``` ts
interface A<T> {
  x(): void;
  y<T extends B>(): void; // only applicable if T extends B
  z<T extends B>: number; // for any property
  // alternative syntax options:
  <T extends B>z: number;  // 1

  z: number where T extends B;  // 2
  y(): void where T extends B;
}
```

I'll suggest this option. Moreover the previous solution options is special case of this one (incompatible constraints are merged on member level).

**Comment by masaeedu** [comment] 2016-01-16 06:54
Possible dupe of #209

**Comment by thorn0** [comment] 2016-01-18 20:25
@RyanCavanaugh  
> Are there other examples of where this would be needed? It seems pretty specific.

There is one more example in #6529.

**Comment by niieani** [comment] 2016-02-17 14:48
Additional explanation and examples + possible usage taken from the duplicate https://github.com/Microsoft/TypeScript/issues/7083: 

It's currently possible to do this:
```ts
  method<A extends Array<number>>(one):number;
  method<A extends Array<string>>(two):string;
```

But not possible to do this:
```ts
interface Example<T extends Array<number>> {
  method(one):number;
}
interface Example<T extends Array<string>> {
  method(two):string;
}
```

This means we cannot have different typings depending on the generic type constraint of the interface.
I've even tried a hack like this:

```ts
interface Example<T extends Array<any>> {
  method<A extends T & Array<number>>(one):number;
  method<A extends T & Array<string>>(two):string;
}
```
I was hoping that TS will infer the type of the T array from the intersect, unfortunately that does not happen (it offers both methods, regardless of whether Example is an instance of `Example<Array<number>>` or of `Example<Array<string>>`).

Among other uses, this feature would be useful for a variety of database libraries that return internal types that can have their own operations done on them. For example, when I `map` an `DbArray<DbNumber>`, I should get a different set of methods than when operating on `DbArray<DbString>`.

The current workaround is to ask the user to explicitly declare both - the outer and the inner type, e.g.:

```ts
interface Example<TOuter, TInner> {
  map<TOut>((item: TInner) => TOut): TOut;
  // ...TOuter used in another method
}
```

However, this `TInner` is redundant (it's already inside of TOuter) and sometimes not relevant at all. 
With more complex types this can cause the introduction of even more generic types, that grow like cancer in the declarations (`interface Example<A, B, C, D, ...>`) - the more possibilities there are, the more explicit declarations need to be done at the interface level. This has been an obstacle to creating proper type definitions for RethinkDB https://github.com/DefinitelyTyped/DefinitelyTyped/issues/4551.

Last example: an interface `DbValue` can be a generic of any primitive type in the database: an `array`, a `string` or a `number`. 
For an instance of an `array`, you'd need to pass in `DbValue<Array<number>, number>`, yet for an instance of string, the second parameter is irrelevant: `DbValue<string, void>`.

What we'd need is to be able to constrain not only by method's own generics, but by the containing interfaces generics, for method signatures themselves, something like:

```ts
interface Example<T> {
  // here the constraint is not of the method, but of the type
  method(one):number where T extends Array<number>;
  method(two):string where T extends Array<string>;
}
```

**Comment by AlexGalays** [comment] 2016-05-21 14:39
This is very useful.

Any type that provides operations only if its type parameter is specialized enough can greatly beneficiate from the type safety this would bring. Ex: Flattening any kind of nested container like Streams, Arrays. You don't want to be able to call flatten on `Array<number>` but you should be able to do it on `Array<Array<number>>`

Another example:  Lodash's `max` method. Calling `max` on a collection is making the assumption that its elements can be compared. `_([ {a: true}, { a: false } ]).max` makes no sense, yet it compiles just fine.

**Comment by niieani** [comment] 2016-07-13 10:48
Would the OP @Igorbek or anyone else like to collaborate on a proposal for this feature?

**Comment by Igorbek** [comment] 2016-07-13 15:32
@niieani Absolutely. Send me if you have something already. If not, I'll start to formulate a proposal.

**Comment by niieani** [comment] 2016-07-13 15:49
I don't have anything yet, but we can use parts of your initial post and mine https://github.com/Microsoft/TypeScript/issues/1290#issuecomment-185236270. If you start working on something, let's use something like Google Docs and link here, so we can collaborate on the document.

**Comment by Igorbek** [comment] 2016-07-13 18:41
I've created a gist to start with https://gist.github.com/Igorbek/21b2bd503fd291d3281def829e2d5fbd

**Comment by ceymard** [comment] 2016-08-26 20:20
Hello,

Does the following example help (it works as of 2.0.0) ;

```typescript
class Test<T> {

    // note that if there is no member of type T, the errors are not spotted
    val: T

    strings<S extends string>(this: Test<S>) {
        console.log('strings !')
    }

    numbers<N extends number>(this: Test<N>) {
        console.log('numberss')
    }

}

let ts = new Test<string>()
let tn = new Test<number>()

// Those work, as intended.
ts.strings()
tn.numbers()

// those don't
ts.numbers()
tn.strings()
```

**Comment by niieani** [comment] 2016-08-26 22:43
@ceymard that's a pretty cool hack, but it still means you need to explicitly type all the generics in case a method has more than one that we want to use. A more complex example:

```ts
class Test<T> {

    // note that if there is no member of type T, the errors are not spotted
    val: T

    strings<S extends string, X>(this: Test<S>) {
        console.log('strings !')
        return 1 as X
    }

    numbers<N extends number, X>(this: Test<N>) {
        console.log('numberss')
        return 1 as X
    }

}

let ts = new Test<string>()
let tn = new Test<number>()

// S and N could be inferred, but I X needs to be explicitly stated here, so I can't do this with good results:
ts.strings()
tn.numbers()

// I'd need to duplicate the typings of S and N, which beats the point of inferrence:
ts.strings<string, number>()
tn.numbers<number, number>()
```

It would be best if we could solve this problem without adding making the methods themselves generic.

**Comment by ceymard** [comment] 2016-08-26 22:58
If you prefer, you can do that too ;

```typescript

class Test<T> {

    // note that if there is no member of type T, the errors are not spotted
    val: T

    strings(this: Test<string>) {
        console.log('strings !')
        return 1 as X
    }

    numbers<X>(this: Test<number>) {
        console.log('numberss')
        return 1 as X
    }

}

```

This still works IIRC, I don't know why I used the <... extends > as it is not mandatory.

Also, if you have a `Test<MyType>`, it will automatically accept anything that extends MyType as well.

I agree it would be best though, but for now that we have nothing, I think this is a "hack" that may help whoever is looking to do just that in 95% of their use case.

Doesn't mean this issue should be closed.

**Comment by niieani** [comment] 2016-08-26 23:06
OK, looks cool! Thanks. Sad you still need the `val: T` in there though.

**Comment by RyanCavanaugh** [comment] 2020-07-21 18:29
I think `this` parameters plus conditional types effectively solve the use cases here. We can take a new suggestion if there are more concrete scenarios that needed addressing

**Closed by RyanCavanaugh** 2020-07-21 18:29 UTC
Labels: Needs Proposal, Suggestion
