### ISSUE TITLE
Ensure required instance variables are set

### ISSUE THREAD

**Issue by matthewmueller** [Microsoft/TypeScript#17184] opened 2017-07-14 04:27 UTC
**TypeScript Version:**  2.4.0

**Code**

```ts
class Greeter {
  greeting: {
    en: 'world!'
  } 
  constructor(message: string) {
 
  }
  greet() {
      return "Hello, " + this.greeting.en;
  }
}

let greeter = new Greeter("world");
greeter.greet()
```

**Expected behavior:**

It would complain that `this.greeting.en` has not been set in the constructor.

**Actual behavior:**

Runtime error 🙀

**Comment by RyanCavanaugh** [comment] 2017-07-14 04:32
Duplicate of #8476

**Closed** 2017-07-14 04:33 UTC
Labels: Duplicate

**Comment by matthewmueller** [comment] 2017-07-14 04:43
@RyanCavanaugh ah there it is. sorry about that!
