### ISSUE TITLE
Unable to properly split conditional types

### ISSUE THREAD

**Issue by MOZGIII** [microsoft/TypeScript#35056] opened 2019-11-12 16:12 UTC
**TypeScript 3.7.2**
[Playground link](https://www.typescriptlang.org/play/?ssl=2&ssc=12&pln=2&pc=9#code/MYewdgzgLgBGCuAbRBBCBVMATApgMwEswcsYBeGAHgBUA+ACgDcBDReHALhmoEovqYOAB5Qc2CHCSIYAfhjxs+IiRj9ytAFAwYLNjnJkKCZLPmLCxUl13sA3BoehIIRDgB0iEAHN6x1BnNlLF8pHh57JwgXd08fPzRMXAsSegUkoLCI8CjXD28Q5ATAy3oAFgAmTKA)

Compiler Options:
```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

**Input:**
```typescript
const nullAsUndefined = <T>(value: T): T extends null ? undefined : T =>
  value === null ? undefined : value;


console.log(nullAsUndefined(null));
console.log(nullAsUndefined(undefined));
console.log(nullAsUndefined(42));
```

**Output:**
```javascript
"use strict";
const nullAsUndefined = (value) => value === null ? undefined : value;
console.log(nullAsUndefined(null));
console.log(nullAsUndefined(undefined));
console.log(nullAsUndefined(42));

```

**Expected behavior:**

There is a type error that I didn't expect.

On the function body:
```
Type 'T | undefined' is not assignable to type 'T extends null ? undefined : T'.
  Type 'undefined' is not assignable to type 'T extends null ? undefined : T'.(2322)
```

**Comment by nmain** [comment] 2019-11-12 16:39
Duplicate of https://github.com/microsoft/TypeScript/issues/33912

**Comment by jcalz** [comment] 2019-11-12 16:41
Duplicate of #22735, related to #33912

**Closed** 2019-11-12 16:45 UTC
