### ISSUE TITLE
TypeError in languageService.getDocumentHighlights

### ISSUE THREAD

**Issue by piotrtomiak** [Microsoft/TypeScript#17396] opened 2017-07-25 09:46 UTC
Querying Language Service API directly through `languageService.getDocumentHighlights` with position after the semicolon (new line is important) in the code below throws TypeError

**TypeScript Version:**  2.4.2

**Code**

```ts
var a;

```

**Expected behavior:**
The method should return empty or undefined results instead of throwing an error.

**Actual behavior:**
A following error is thrown:

```
TypeError: Cannot read property 'kind' of undefined
	at Object.isJsxOpeningElement(.../node_modules/typescript/lib/typescript.js:11058:20)
	at Object.getDocumentHighlights(.../node_modules/typescript/lib/typescript.js:76604:20)
	at Object.getDocumentHighlights(.../node_modules/typescript/lib/typescript.js:89401:42)
        ...
```

**Comment by andy-ms** [comment] 2017-08-23 21:58
Looks like this is already fixed. I could reproduce this error with `typescript@2.4` but not with `typescript@2.5`.

**Comment by andy-ms** [comment] 2017-08-23 22:11
May be a duplicate of #17486 and #17245.

**Closed** 2017-08-23 22:37 UTC
Labels: Bug
