### ISSUE TITLE
Error when extending null

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#3696] opened 2015-07-01 19:34 UTC
```ts
    class C extends null {
        constructor() {
            return Object.create(null);
        }
    }
```
generates error:
> error TS2377: Constructors for derived classes must contain a 'super' call.

in this case, a call to `super` is guaranteed to fail.

**Comment by yuit** [comment] 2015-07-14 23:17
Isn't it a valid ES6 in the sense that you can extend ```null```?

**Comment by DanielRosenwasser** [comment] 2015-07-15 06:51
Yes - the problem is the compiler is saying you need to call `super`, which will cause your code to crash. Does the spec need to account for this as well?

**Comment by yuit** [comment] 2015-07-15 18:44
So it is *not* error when extending null but do not give an error from super when extending null ?

**Comment by yuit** [comment] 2015-07-15 19:51
talk with @mhegazy  we will error when users use super but not vice versa

**Comment by yuit** [comment] 2015-07-16 01:50
We also want to give an error in this case
```typescript
class B extends null {}
```
because of the following, in section [14.5.14] (https://people.mozilla.org/~jorendorff/es6-draft.html#sec-runtime-semantics-classdefinitionevaluation)
> If constructor is empty, then,
>
> * If ClassHeritageopt is present, then
>        Let constructor be the result of parsing the String "constructor(... args){ super (...args);}" using the syntactic grammar with the goal symbol MethodDefinition.

**Comment by mhegazy** [comment] 2015-07-16 02:45
Can you check with @bterlson that this applies to the extends null case.

**Comment by DanielRosenwasser** [comment] 2015-07-16 03:53
I don't think that is an error. It's very clear from the below semantics.

> 6.  Else
     5.  If *superclass* is **null**, then
         2.  Let *constructorParent* be the intrinsic object %FunctionPrototype%.
12. Let *constructorInfo* be the result of performing DefineMethod for *constructor* with arguments *proto* and *constructorParent* as the optional *functionPrototype* argument.


Then in DefineMethod

> 6.  Let *closure* be [FunctionCreate](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-functioncreate)(*kind*, *StrictFormalParameters*, *FunctionBody, scope*, *strict*). If *functionPrototype* was passed as a parameter then pass its value as the *functionPrototype* optional argument of [FunctionCreate](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-functioncreate).

Then in FunctionCreate

> 4.  Let *F* be [FunctionAllocate](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-functionallocate)(*prototype*, *Strict*, *allocKind*).

Then in FunctionAllocate

> 12. Set the \[\[Prototype\]\] [internal slot](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-object-internal-methods-and-internal-slots) of *F* to *functionPrototype*.

[Then of course, you need to understand you the runtime semantics for super calls](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-super-keyword-runtime-semantics-evaluation):

> 3.  Let *func* be [GetSuperConstructor](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-getsuperconstructor)().

And, GetSuperConstructor will

> 4.  Let *superConstructor* be *activeFunction*.\[\[GetPrototypeOf\]\]().

And *obviously*, \[\[GetPrototypeOf\]\]() invoked on activeFunction (known generally as "O") will

> 1.  Return the value of the \[\[Prototype\]\] [internal slot](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-object-internal-methods-and-internal-slots) of *O*.

God.

**Comment by yuit** [comment] 2015-07-16 05:10
I see your point @DanielRosenwasser . However, the default constructor will call ```super```. this will be an error except it is different ``` super``` we are talking about here.

**Comment by DanielRosenwasser** [comment] 2015-07-16 05:31
I see what you mean now @yuit - maybe we should change our emit for `super` calls to be something like

```TypeScript
// No constructor defined:
_super && _super(this, arguments);

// In the presence of an explicit 'super(arg1, arg2, ..., argN)' call
_super && _super.call(this, arg1, arg2, ... argN);
```

**Comment by yuit** [comment] 2015-07-16 18:17
Note: following code fails at execution time in io.js
```javascript
class N extends null {}
var n = new N();  ->  function Empty() {} is not a constructor
```

**Comment by bterlson** [comment] 2015-07-16 20:05
`class A extends null { }` will indeed get the default constructor that includes `super`. This is not an error because ClassDefinitionEvaluation sets the [[prototype]] of the constructor to Function.prototype, which itself is a function. In other words, `Object.getPrototypeOf(A) === Function.prototype`.

Super property references should fail at runtime in methods as the [[prototype]] of the home object (`A.prototype`) is null.

**Comment by yuit** [comment] 2015-07-16 20:43
> Super property references should fail at runtime in methods as the [[prototype]] of the home object (A.prototype) is null.

so calling super will cause an error? (i.e so calling ```new A()``` will give runtime error)

**Comment by DanielRosenwasser** [comment] 2015-07-17 01:25
@bterlson, @yuit found the following:

> ### <span id="sec-12.3.5.1" class="secnum">[12.3.5.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-super-keyword-runtime-semantics-evaluation "link to this section")</span> Runtime Semantics: Evaluation

> *SuperCall* <span class="geq">:</span> `super` *Arguments*

> 1.  Let *newTarget* be [GetNewTarget](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-getnewtarget)().
2.  If *newTarget* is **undefined**, throw a **ReferenceError** exception.
3.  Let *func* be [GetSuperConstructor](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-getsuperconstructor)().
4. [...]

> ### <span id="sec-12.3.5.2" class="secnum">[12.3.5.2](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-getsuperconstructor "link to this section")</span> Runtime Semantics: GetSuperConstructor ( )

> The abstract operation GetSuperConstructor performs the following steps:

> 1.  Let *envRec* be [GetThisEnvironment](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-getthisenvironment)( ).
2.  [Assert](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-algorithm-conventions): *envRec* is a function [Environment Record](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-environment-records).
3.  Let *activeFunction* be *envRec*.\[\[FunctionObject\]\].
4.  Let *superConstructor* be *activeFunction*.\[\[GetPrototypeOf\]\]().
5.  [ReturnIfAbrupt](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-returnifabrupt)(*superConstructor*).
6.  If [IsConstructor](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-isconstructor)(*superConstructor*) is **false**, throw a **TypeError** exception.
7.  Return *superConstructor*.

> ### <span id="sec-19.2.3" class="secnum">[19.2.3](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-properties-of-the-function-prototype-object "link to this section")</span> Properties of the Function Prototype Object

> The Function prototype object is the intrinsic object %FunctionPrototype%. The Function prototype object is itself a built-in function object. When invoked, it accepts any arguments and returns <span class="value">undefined</span>. It does not have a \[\[Construct\]\] internal method so it is not a constructor.

So what it *seems like* is that `activeFunction.[[GetPrototypeOf]]().` in `GetSuperConstructor()` will return `Function.prototype` which itself is not constructible, meaning that this will indeed error. Any idea whether this is the case, or whether we're missing something?

**Comment by bterlson** [comment] 2015-07-21 19:32
I missed the isConstructor check! You're right that's what the spec says, but this is an error. Spec will be fixed. Intention is for this not to throw via not installing a default constructor with a super call in this case.

**Comment by bterlson** [comment] 2015-07-21 19:38
Well, maybe. See bug here: https://bugs.ecmascript.org/show_bug.cgi.

**Comment by RyanCavanaugh** [comment] 2015-07-21 20:17
@bterlson can you fix that link?

**Comment by JsonFreeman** [comment] 2015-07-21 20:51
So for TypeScript, it seems like there are two things to fix:

1. The error we give is actually wrong for `extends null`. In that case, the user should not have a super call. And also, the fact that we require a super call could be bad for extending an expression where the runtime value *could* be null.
2. We need to change our pre-ES6 emit for default constructors if you extend null. Again, this will not work for extending an arbitrary expression. The alternative here is to make a helper that actually checks the value of _super, and only calls it if it's not null. That might be better.

**Comment by yuit** [comment] 2015-07-21 20:57
@JsonFreeman : you are right. I believe we will need to fix our emit default constructor for below es5 to be able to handle ```extends null```

**Comment by bterlson** [comment] 2015-07-21 21:33
Gah, edited. Sorry.

**Comment by JsonFreeman** [comment] 2015-07-21 22:16
I think SameValue(protoParent, null) is a better check, that way it doesn't change the behavior for `extends Function.protoype`. But maybe that will break `extends { prototype: null }`.

**Closed** 2015-07-27 22:59 UTC
Labels: Bug

**Comment by yuit** [comment] 2015-07-27 23:00
I open separate issue to track what our decision is for default constructor
