### ISSUE TITLE
Constraint generics param does not satisfy type infer expression.

### ISSUE THREAD

**Issue by thynson** [microsoft/TypeScript#50606] opened 2022-09-02 10:29 UTC
# Bug Report

### 🔎 Search Terms
Constraint generics param does not satisfy type infer expression.
### 🕗 Version & Regression Information
4.7.4 and 4.8.2, earlier versions may behave the same.
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKuEGcA8MB8UC8UAUMoQA9gIA7AEwSgG8BfKAfigHIB7AIwCsIBjYJqAFxQSEAG4QATlACUUAD7MwEgJYBbZcGXimAKB0AzAK4leyliSgBDbtwhhgKVNktC4kZGllUdNPUZOa5lBsKPhEpBTUNE4usF46UIlWNnYOaNhMSmoaWhBM0gDcUAD0xVAA8gDWliAJSda29o4Z7Fy8+UWlUACiEhIsEq4AygBMAMwALACsdYkNqaEAZFCtPMBOrJxrHSVlVTUANMGGwLBWADYSEJZkIGHE5JT6-apRRwiG3AAWUADuA9V+sYyFAEF9LOdzsIWKc2NArgBHQzKK5kHxAA)

### 💻 Code

```typescript
type Types<T> = (T extends {} ? 'object' : never ) | 'primitive'

function accept<T>(a: Types<T>) {
}

function b<T extends {}>(a: T) {
    accept<T>('primitive'); // Okay
    accept<T>('object'); // Error: TS2345
    accept<T & object>('object'); // Okay, but T already extends from {}, such workaround shall not be required
}
```

### 🙁 Actual behavior
tsc accepts the above code

### 🙂 Expected behavior
the above code is rejected

**Comment by whzx5byb** [comment] 2022-09-02 11:14
Duplicate of https://github.com/microsoft/TypeScript/issues/31096

**Closed** 2022-09-05 18:00 UTC
Labels: Duplicate
