### ISSUE TITLE
Compiler Error: Object is possibly 'undefined' for Map entry even though it is impossible to be undefined 

### ISSUE THREAD

**Issue by rd-malte-mauelshagen** [microsoft/TypeScript#46683] opened 2021-11-04 12:12 UTC
# Bug Report

### 🔎 Search Terms

Map, TS2532: Object is possibly 'undefined'., impossible

### 🕗 Version & Regression Information
4.1.6, 4.4.4

### ⏯ Playground Link
```ts repro
const myMap = new Map<string, number[]>();
const key = 'myKey';

if (!myMap.has(key)) {
  myMap.set(key, []);
}

myMap.get(key).push(1, 2, 3);

```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.4.4#code/MYewdgzgLgBAtgTwLIEMAOMC8MwFMDuMqaAPNAE4CWYA5gDQ4CucARruQNoC6AfABQBKANwAoUJFgBrXAiwwA5IgDSM+aJGUAZjD4BCRMQB0ACxQQ+0hAIEwA3iJjxk6QxFxQLMht2EiAviIiBi407p5WhmiMEMZ8AIwMAEwMAMy+QA)
### 🙁 Actual behavior

Compiler Error: `TS2532: Object is possibly 'undefined'.`

![grafik](https://user-images.githubusercontent.com/67141950/140311449-923144be-0003-44a5-adb6-b1bd03b57995.png)

### 🙂 Expected behavior

No compiler error, because by analyzing the control flow it can be deduced that it is impossible for `myMap.get(key)` to be `undefined`.

**Comment by MartinJohns** [comment] 2021-11-04 12:18
Duplicate of #13086. Used search terms: `map has in:title`

**Closed** 2021-11-07 18:00 UTC
Labels: Duplicate
