### ISSUE TITLE
Refactor: move to new file does not work

### ISSUE THREAD

**Issue by a-x-** [microsoft/TypeScript#59650] opened 2024-08-15 15:44 UTC
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: Version: 1.92.1 (Universal)
- OS Version: MacOS Sonoma 14.5 / Apple M1 Pro

Steps to Reproduce:

1. Refactor > move to new file

What I tried already:
1. Run with `--disable-extensions` to ensure it's not a problem with a package.
2. `typescript.tsserver.enableTrace`
3. find minimal examples
4. search for similar issues: https://github.com/microsoft/vscode/issues/51586, https://github.com/microsoft/vscode/issues/58711

It worked a few versions before. I don't know exactly what version was okay.

UPD: not working:
```ts
import { useLatest } from 'react-use';

export function useUseLatest (data: string) {
    return useLatest(data);
}
```

not working:
```ts
import { selectStore, useSelector } from '@proterm/core';

export function useOrders() {
    return useSelector(selectStore);
}
```

not working:
```ts
import { selectStore } from '@proterm/core';

export function useOrders() {
    return selectStore;
}
```

working:
```ts
import { AnyBaseOrder } from '@terminal/scalp/types';

export function useOrders(symbolId: string): AnyBaseOrder[] {}
```

working:
```ts
import { useSelector } from 'react-redux';

function useOrders() {
    return useSelector((state) => console.log(state));
}
```

working:
```ts
import { selectStore, useSelector } from '@proterm/core';
export function useOrders(symbolId: string): AnyBaseOrder[] {}
```

I though @ import aliases is a problem, however this works too:
```ts
import { FancyAlertCircleIcon } from '@terminal/icons';

export function useOrders() {
    return FancyAlertCircleIcon;
}
```

error:
```
2024-08-15 18:42:15.101 [error] <semantic> TypeScript Server Error (5.5.4)
Debug Failure.
Error: Debug Failure.
    at Object.addImportFromExportedSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:154243:32)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144288:19
    at Map.forEach (<anonymous>)
    at addTargetFileImports (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144282:17)
    at getNewStatementsAndRemoveFromOldFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:143512:3)
    at doChange4 (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144488:3)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144477:77
    at _ChangeTracker.with (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:174306:5)
    at Object.getRefactorEditsToMoveToNewFile [as getEditsForAction] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144477:60)
    at Object.getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:142603:31)
    at Object.getEditsForRefactor2 [as getEditsForRefactor] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:149939:32)
    at IpcIOSession.getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191087:49)
    at getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:189305:43)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191491:69
    at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191483:14)
    at IpcIOSession.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191491:29)
    at IpcIOSession.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191533:51)
    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:523:14)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21): Error: <semantic> TypeScript Server Error (5.5.4)
```

**Comment by Jason3S** [comment] 2024-08-16 12:58
I'm seeing this issue too.

When I try to Move to a New File in vscode, the following errors appear in the Extension Host output.

```
2024-08-16 14:51:23.411 [error] [vscode.typescript-language-features] provider FAILED
2024-08-16 14:51:23.411 [error] Error: <semantic> TypeScript Server Error (5.5.4)
Debug Failure. False expression: Changes overlap
Verbose Debug Information: {"pos":0,"end":1125} and {"pos":455,"end":455}
Error: Debug Failure. False expression: Changes overlap
Verbose Debug Information: {"pos":0,"end":1125} and {"pos":455,"end":455}
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:174932:15
```

**Comment by aureliopetrone** [comment] 2024-08-24 10:44
@navya9singh any update on this?

**Comment by robMolloy** [comment] 2024-09-03 15:21
@navya9singh @aureliopetrone @sheetalkamat  this looks like the fix for a similar issue however it's 
not working for me [](https://github.com/microsoft/TypeScript/pull/59625)

I have just downloaded the newest version and it doesn't seem to work for me.

Additionally there is some comments about disabling/enabling "typescript.tsserver.experimental.useVsCodeWatcher". I have tried both enabled and disabled
[](https://github.com/microsoft/TypeScript/issues/59603#issuecomment-2285035053)

**Comment by sheetalkamat** [comment] 2024-09-03 16:57
This seems more or less duplicate of #58740

**Comment by komichar** [comment] 2024-09-12 13:35
I can confirm that this bug is still present & refactoring is broken for several minor & fix versions. Any plans to fix this?

**Comment by qimmer** [comment] 2024-10-30 12:07
Any news on this? Also getting:
`
2024-10-30 13:06:08.641 [error] [vscode.typescript-language-features] provider FAILED
2024-10-30 13:06:08.641 [error] Error: <semantic> TypeScript Server Error (5.6.3)
Debug Failure.
Error: Debug Failure.
    at Object.addImportFromExportedSymbol (/opt/vscodium-bin/resources/app/extensions/node_modules/typescript/lib/typescript.js:155205:32)
    at /opt/vscodium-bin/resources/app/extensions/node_modules/typescript/lib/typescript.js:145113:19
    at Map.forEach (<anonymous>)
    at addTargetFileImports (/opt/vscodium-bin/resources/app/extensions/node_modules/typescript/lib/typescript.js:145107:17)
    at getNewStatementsAndRemoveFromOldFile (/opt/vscodium-bin/resources/app/extensions/node_modules/typescript/lib/typescript.js:144328:3)
    at doChange4 (/opt/vscodium-bin/resources/app/extensions/node_modules/typescript/lib/typescript.js:145331:3)
    at /opt/vscodium-bin/resources/app/extensions/node_modules/typescript/lib/typescript.js:145320:77
    at _ChangeTracker.with (/opt/vscodium-bin/resources/app/extensions/node_modules/typescript/lib/typescript.js:175529:5)
    at Object.getRefactorEditsToMoveToNewFile [as getEditsForAction] (/opt/vscodium-bin/resources/app/extensions/node_modules/typescript/lib/typescript.js:145320:60)
    at Object.getEditsForRefactor (/opt/vscodium-bin/resources/app/extensions/node_modules/typescript/lib/typescript.js:143419:31)
    at getEditsForRefactor2 (/opt/vscodium-bin/resources/app/extensions/node_modules/typescript/lib/typescript.js:150900:32)
    at Proxy.<anonymous> (/home/kim/.vscode-oss/extensions/unifiedjs.vscode-mdx-1.8.11-universal/node_modules/@mdx-js/typescript-plugin.js:5:1986)
    at IpcIOSession.getEditsForRefactor (/opt/vscodium-bin/resources/app/extensions/node_modules/typescript/lib/typescript.js:192232:49)
    at getEditsForRefactor (/opt/vscodium-bin/resources/app/extensions/node_modules/typescript/lib/typescript.js:190431:43)
    at /opt/vscodium-bin/resources/app/extensions/node_modules/typescript/lib/typescript.js:192651:15
    at IpcIOSession.executeWithRequestId (/opt/vscodium-bin/resources/app/extensions/node_modules/typescript/lib/typescript.js:192640:14)
    at IpcIOSession.executeCommand (/opt/vscodium-bin/resources/app/extensions/node_modules/typescript/lib/typescript.js:192649:29)
    at IpcIOSession.onMessage (/opt/vscodium-bin/resources/app/extensions/node_modules/typescript/lib/typescript.js:192697:68)
    at process.<anonymous> (/opt/vscodium-bin/resources/app/extensions/node_modules/typescript/lib/tsserver.js:525:14)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
	at n.create (/opt/vscodium-bin/resources/app/extensions/typescript-language-features/dist/extension.js:1:474261)
	at v.dispatchResponse (/opt/vscodium-bin/resources/app/extensions/typescript-language-features/dist/extension.js:1:468231)
	at v.dispatchMessage (/opt/vscodium-bin/resources/app/extensions/typescript-language-features/dist/extension.js:1:467029)
	at ChildProcess.<anonymous> (/opt/vscodium-bin/resources/app/extensions/typescript-language-features/dist/extension.js:1:466522)
	at ChildProcess.emit (node:events:519:28)
	at emit (node:internal/child_process:951:14)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
`

**Closed** 2024-11-01 00:03 UTC
Labels: Bug

**Comment by Jason3S** [comment] 2025-04-07 08:56
@fcole90,

I think it is better to create a new issue and refer to this one.

**Comment by iisaduan** [comment] 2025-04-12 11:36
@fcole90 You can make it in this repo

**Comment by Nick2bad4u** [comment] 2025-06-26 22:32
Still here :( 

```logs
2025-06-26 18:32:28.805 [error] [Window] <semantic> TypeScript Server Error (5.8.3)
Debug Failure. False expression: Expected symbol to be a module
Error: Debug Failure. False expression: Expected symbol to be a module
    at Object.addImportForModuleSymbol (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:157416:11)
    at c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:147140:19
    at Map.forEach (<anonymous>)
    at addTargetFileImports (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:147133:17)
    at getNewStatementsAndRemoveFromOldFile (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:146364:3)
    at doChange4 (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:147360:3)
    at c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:147349:77
    at _ChangeTracker.with (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:178070:5)
    at Object.getRefactorEditsToMoveToNewFile [as getEditsForAction] (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:147349:60)
    at Object.getEditsForRefactor (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:145454:31)
    at Proxy.getEditsForRefactor2 (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:152954:32)
    at IOSession.getEditsForRefactor (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:195255:49)
    at getEditsForRefactor (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:193406:43)
    at c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:195676:15
    at IOSession.executeWithRequestId (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:195665:14)
    at IOSession.executeCommand (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:195674:29)
    at IOSession.onMessage (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:195722:68)
    at Interface.<anonymous> (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\_tsserver.js:495:14)
    at Interface.emit (node:events:507:28)
    at [_onLine] [as _onLine] (node:internal/readline/interface:469:12)
    at [_normalWrite] [as _normalWrite] (node:internal/readline/interface:651:22)
    at Socket.ondata (node:internal/readline/interface:263:23)
    at Socket.emit (node:events:507:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:189:23): Error: <semantic> TypeScript Server Error (5.8.3)
Debug Failure. False expression: Expected symbol to be a module
Error: Debug Failure. False expression: Expected symbol to be a module
    at Object.addImportForModuleSymbol (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:157416:11)
    at c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:147140:19
    at Map.forEach (<anonymous>)
    at addTargetFileImports (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:147133:17)
    at getNewStatementsAndRemoveFromOldFile (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:146364:3)
    at doChange4 (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:147360:3)
    at c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:147349:77
    at _ChangeTracker.with (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:178070:5)
    at Object.getRefactorEditsToMoveToNewFile [as getEditsForAction] (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:147349:60)
    at Object.getEditsForRefactor (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:145454:31)
    at Proxy.getEditsForRefactor2 (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:152954:32)
    at IOSession.getEditsForRefactor (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:195255:49)
    at getEditsForRefactor (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:193406:43)
    at c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:195676:15
    at IOSession.executeWithRequestId (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:195665:14)
    at IOSession.executeCommand (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:195674:29)
    at IOSession.onMessage (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\typescript.js:195722:68)
    at Interface.<anonymous> (c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\_tsserver.js:495:14)
    at Interface.emit (node:events:507:28)
    at [_onLine] [as _onLine] (node:internal/readline/interface:469:12)
    at [_normalWrite] [as _normalWrite] (node:internal/readline/interface:651:22)
    at Socket.ondata (node:internal/readline/interface:263:23)
    at Socket.emit (node:events:507:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:189:23)
    at n.create (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:2:497261)
    at y.dispatchResponse (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:2:490340)
    at y.dispatchMessage (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:2:488781)
    at ud.value (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:2:488274)
    at P.B (file:///c:/Users/Nick/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2373)
    at P.fire (file:///c:/Users/Nick/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2591)
    at b.onLengthData (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:2:501159)
    at Socket.<anonymous> (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:2:500806)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Socket.Readable.push (node:internal/streams/readable:392:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:189:23)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)
```

**Comment by iisaduan** [comment] 2025-07-03 22:20
@Nick2bad4u, your error message is different: `Debug Failure. False expression: Expected symbol to be a module`, which means your case has a different cause. In order for us to fix/investigate your case, can you create a new issue with a repro for your error?

**Comment by Nick2bad4u** [comment] 2025-07-03 22:41
> @Nick2bad4u, your error message is different: `Debug Failure. False expression: Expected symbol to be a module`, which means your case has a different cause. In order for us to fix/investigate your case, can you create a new issue with a repro for your error?

I can but it won't be until later today 

What do you guys need? I can give you exact link to my GitHub project and the file/code snippet. 

Anything else besides that and vscode logs?
