### ISSUE TITLE
Allow self-reference in the type annotation of objects

### ISSUE THREAD

**Issue by Dari-K** [microsoft/TypeScript#32738] opened 2019-08-06 17:42 UTC
## Search Terms
circular typing, type annotation, self-reference, index signature, object

## Suggestion

Add some method for typing an object based on the keys/values it has when defined.

## Use Cases
For the following example:
```typescript
export type PizzaType = 'pepperoni' | 'margherita' | 'hawaiian';

export interface Pizza {
    toppings: string[];
    price: number;
}

export const MENU: { [T in PizzaType]: Readonly<Pizza> } = {
    pepperoni: {
        toppings: ['pepperoni'],
        price: 5.00
    },

    margherita: {
        toppings: ['mozzarella'],
        price: 4.00
    },

    hawaiian: {
        toppings: ['pineapple', 'ham'],
        price: 6.50
    }
}

const pizzaTypes = Object.keys(MENU) as PizzaType[];
pizzaTypes.forEach((key) => {
    const pizza = MENU[key];
});
```

Everything works well, we get code completion for the keys of `MENU` when we type `MENU.`, and the type of our `const pizza` in the forEach is `Pizza`, however we've had to duplicate the `PizzaType` information, both there and in the `MENU` const, which feels bad because any time we want to add a pizza to the menu we'll have to make changes in 2 places.

I don't think there's a good way to solve this problem with the tools currently available to us.
To remove the duplication we want to define `PizzaType` as `export type PizzaType = keyof typeof MENU;`. I could see a few ways we could do that:

If we remove the type annotation from `MENU`, but then we lose code completion and type checking when we're adding new pizzas to `MENU`, and in the forEach `const pizza` ends up with a nasty looking union type instead of `Pizza`. Using `as const` has the same issues.

If we change the type annotation for `MENU` to `export const MENU: { [k: string]: Pizza } = {`, but then we lose code completion for `MENU.`, and our `PizzaType` is just `string | number`.

## Examples

Ideally we would be able to do something like:

```typescript
export type PizzaType = keyof typeof MENU;

export interface Pizza {
    toppings: string[];
    price: number;
}

export const MENU: { [T in keyof typeof MENU]: Readonly<Pizza> } = {
    pepperoni: {
        toppings: ['pepperoni'],
        price: 5.00
    },

    margherita: {
        toppings: ['mozzarella'],
        price: 4.00
    },

    hawaiian: {
        toppings: ['pineapple', 'ham'],
        price: 6.50
    }
};

const pizzaTypes = Object.keys(MENU) as PizzaType[];
pizzaTypes.forEach((key) => {
    const pizza = MENU[key];
});
```
Maybe having the circular reference isn't very nice though, so the syntax could look something like this instead.

```typescript
export const MENU: { [T in keyof const]: Readonly<Pizza> } = {
    pepperoni: {
        toppings: ['pepperoni'],
        price: 5.00
    },

    margherita: {
        toppings: ['mozzarella'],
        price: 4.00
    },

    hawaiian: {
        toppings: ['pineapple', 'ham'],
        price: 6.50
    }
} as const;
```
Where the `const` in the type annotation is only allowed for const asserted objects, because we're specifically stating that the keys/values of the object won't be modified after we've set it here.

## Checklist

My suggestion meets these guidelines:

* [*] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [*] This wouldn't change the runtime behavior of existing JavaScript code
* [*] This could be implemented without emitting different JS based on the types of the expressions
* [*] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [from my interpretation of them, I think so] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment] 2019-08-06 17:46
Looks like a duplicate of #7481, since with that you could write
```ts
export type PizzaType = keyof typeof MENU;

export interface Pizza {
    toppings: string[];
    price: number;
}

export const MENU = {
    pepperoni: {
        toppings: ['pepperoni'],
        price: 5.00
    },

    margherita: {
        toppings: ['mozzarella'],
        price: 4.00
    },

    hawaiian: {
        toppings: ['pineapple', 'ham'],
        price: 6.50
    }
} as const as? { [T: string]: Readonly<Pizza> };
```

**Comment by Dari-K** [comment] 2019-08-06 18:12
Ah sorry, yes that looks like it might fit my use case, what would end up being the computed types of `MENU` and `PizzaType`?

**Comment by RyanCavanaugh** [comment] 2019-08-06 18:21
`MENU` would be the same as if you had written the existing object literal followed by ` as const`; `PizzaType` would be `"pepperoni" | "margherita" | "hawaiian"`

**Closed** 2019-08-14 18:00 UTC
Labels: Duplicate
