### ISSUE TITLE
Wrong type narrowing with Boolean(expression)

### ISSUE THREAD

**Issue by Felix-Indoing** [microsoft/TypeScript#37770] opened 2020-04-03 13:16 UTC
**TypeScript Version:**  3.8.3

**Search Terms:** Boolean type narrowing

**Code**

```ts
    const x: {test: string} | null | undefined = something()

    // this works
    if (!!x) {
        console.log(x.test)
    }

    // this can not work
    if (Boolean(x)) {
        console.log(x.test)
    }
```

**Expected behavior:**
Expression inside the second if statement should work.

**Actual behavior:**
The second if statement gives the following error:
```
TS2533: Object is possibly 'null' or 'undefined'.
```

**Related Issues:** None

**Comment by IllusionMH** [comment] 2020-04-03 13:42
Duplicate of #16655

Unfortunately changing `Boolean` declaration breaks cases with `filter` etc.
See #29955

**Closed** 2020-04-05 18:00 UTC
Labels: Duplicate
