### ISSUE TITLE
Allow public getter and private setter for properties

### ISSUE THREAD

**Issue by miniak** [Microsoft/TypeScript#14310] opened 2017-02-25 09:13 UTC
Example:
```
class Foobar {
    private _value = 0;

    public get value() {
        return this._value;
    }

    private set value(value: number) {
        console.log(`setting value to: ${value}`);
        this._value = value;
    }

    public doSomething() {
        this.value = this.value + 1;
    }
}
```

You can do that for example in Objective-C, where it's really useful:

Foobar.h
```
@interface Foobar : NSObject
@property (readonly, nonatomic) int value;
- (void)doSomething;
@end
```

Foobar.m
```
@interface Foobar () {
    int _value;
}
@property (readwrite, nonatomic) int value;
@end

@implementation Foobar

- (int)value {
    return _value;
}

- (void)setValue:(int)value {
    NSLog(@"setting value to: %d", value);
    _value = value;
}

- (void)doSomething {
    self.value = self.value + 1;
}

@end
```

**Comment by mhegazy** [comment] 2017-02-27 20:47
Duplicate of https://github.com/Microsoft/TypeScript/issues/2845

**Closed** 2017-04-21 16:55 UTC
Labels: Duplicate
