### ISSUE TITLE
Incorrect ts(18048) (possibly 'undefined' error) after loop with nullish coalescing assignment

### ISSUE THREAD

**Issue by massic80** [microsoft/TypeScript#53909] opened 2023-04-19 11:07 UTC
# Bug Report
I have a service possibly not returning data, and I inject the fallback value by iterating its values with a nullish coalescing assignment.
TS goes on saying it may be undefined.

### 🔎 Search Terms

nullish assignment , 18048, possibly undefined

### 🕗 Version & Regression Information
I noticed this on 4.9+

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgJwQLgN5ylBB+ZYCuAtgEYCmCAvgNoC6MAvDFepigIwUA0qFNA3ACgAZiAQwAFKEiwAbjBBD4SAJSoBASBkA6DFhjZsjAAyCKAxAi0RRsceLidiy+gD44O1gFpiHrMr5AA)

### 💻 Code

```ts
const arr:{attr?:number}[] = [{attr:1},{}];
for (const x of arr){
	x.attr ??= 0;
}
/*
The same happens with
arr.forEach(x=>{
	x.attr ??= 0;
});
*/
arr.sort((a,b)=>a.attr-b.attr);
```

### 🙁 Actual behavior

TS goes on saying it may be undefined.

### 🙂 Expected behavior

TS should be aware of the "coverage" of all array values with my fallback.

**Comment by MartinJohns** [comment] 2023-04-19 11:40
Duplicate of #9998.

**Closed** 2023-04-21 18:00 UTC
Labels: Duplicate
