### ISSUE TITLE
keyof type not correctly type-checked in function 

### ISSUE THREAD

**Issue by wmichelin** [microsoft/TypeScript#36395] opened 2020-01-24 02:18 UTC
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
keyof param

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

interface BooleanFields {
    a: boolean;
    b: boolean;
}

type BooleanField = keyof BooleanFields;

interface OtherInterface {
    b: boolean;
}

const fooFunc = (dynamicKey: BooleanField): Partial<OtherInterface> => ({
    //why does this work?!?!
    // BooleanField should be 'a' | 'b', and 'a' does not exist in OtherInterface.
    [dynamicKey]: false,
});

const myDynamicKey: BooleanField = 'a';
fooFunc(myDynamicKey);
```

**Expected behavior:**
TypeError in fooFunc, since `BooleanField` has a possible value `a` that does not exist within `OtherInterface`

**Actual behavior:**
The code compiles successfully

**Playground Link:** 
http://www.typescriptlang.org/play/?ts=3.8.0-dev.20200122&ssl=1&ssc=1&pln=19&pc=23#code/JYOwLgpgTgZghgYwgAgEIHt0BsJxAMWAiwBMBnZAbwChk7k4AuZAI0xzwG5b6Xm3suENwC+1amACeABxQZBeQsRLIAvMgDWESehhp2QpaTLdqoSLEQoA8mAAW0AJLho8JFR50+rA12pjqBHQQMjBkGEx8AFcQBDVkAAoSSRA4AFtgBABpbWZ5DgIiUgBKZgAFOCgwYDgsAB5bByhnCzcIAD41ToSaemQAen6AdztJZBJ0CAp7YAoh9CgNAH4AQlXPAf79BULlZDI7dCjSVhQAcjgz5AAfZDOWM4AaBhAVC6uJqeQQdDCIAA9ZmFQMhGk4XJYkAA6DYAbWSqQy2W0AF1mPAsGQII9-MVTEEQmE0pIACIpdKZHKSPK+XYndTvbgRdDRWIJYlkxGU7R4oA

**Related Issues:** 
No

**Comment by jcalz** [comment] 2020-01-24 03:27
Duplicate of #32309 ?

**Comment by wmichelin** [comment] 2020-01-24 03:35
@jcalz 

Hmm, not entirely sure. It may be similar, but what makes me think it's not is the following:
```
interface BooleanFields {
    a: boolean;
    b: boolean;
}

type BooleanField = keyof BooleanFields;

interface OtherInterface {
    b: boolean;
}

const fooFunc = (dynamicKey: BooleanField): Partial<OtherInterface> => ({
    //why does this work?!?!
    // BooleanField should be 'a' | 'b', and 'a' does not exist in OtherInterface.
    [dynamicKey]: false,
});

const myDynamicKey: BooleanField = 'a';
fooFunc(myDynamicKey);

const TestExample: Partial<OtherInterface> = {
    [myDynamicKey]: false,
};

```

In this case, `TestExample` is correctly raising an error. It only doesn't raise an error when the dynamic key value is a function parameter.

Example here:
http://www.typescriptlang.org/play/?ts=3.8.0-dev.20200122&ssl=24&ssc=1&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgEIHt0BsJxAMWAiwBMBnZAbwChk7k4AuZAI0xzwG5b6Xm3suENwC+1amACeABxQZBeQsRLIAvMgDWESehhp2QpaTLdqoSLEQoA8mAAW0AJLho8JFR50+rA12pjqBHQQMjBkGEx8AFcQBDVkAAoSSRA4AFtgBABpbWZ5DgIiUgBKZgAFOCgwYDgsAB5bByhnCzcIAD41ToSaemQAen6AdztJZBJ0CAp7YAoh9CgNAH4AQlXPAf79BULlZDI7dCjSVhQAcjgz5AAfZDOWM4AaBhAVC6uJqeQQdDCIAA9ZmFQMhGk4XJYkAA6DYAbWSqQy2W0AF1mPAsGQII9-MVTEEQmE0pIACIpdKZHKSPK+XYndTvbgRdDRWIJYlkxGU7R48QE0LIAAqUzAAFF-ulpDhypVqrUGvZwa0rJ11L16LCOeSkVS0eFalicSJuEA

**Comment by jcalz** [comment] 2020-01-24 14:15
That's because `const myDynamicKey: BooleanField = 'a';` narrows `myDynamicKey` via control flow analysis to the literal type `"a"`; it is effectively no longer a union type in the `const TestExample` line.  (Control flow analysis narrows union-typed variables upon assignment, as described in #8010).  If you change that assignment to a non-narrowing one (e.g., `const myDynamicKey: BooleanField = 'a' as BooleanField;`) then the issue reported in #32309 recurs.

[Playground link](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20200122#code/JYOwLgpgTgZghgYwgAgEIHt0BsJxAMWAiwBMBnZAbwChk7k4AuZAI0xzwG5b6Xm3suENwC+1amACeABxQZBeQsRLIAvMgDWESehhp2QpaTLdqoSLEQoA8mAAW0AJLho8JFR50+rA12pjqBHQQMjBkGEx8AFcQBDVkAAoSSRA4AFtgBABpbWZ5DgIiUgBKZgAFOCgwYDgsAB5bByhnCzcIAD41ToSaemQAbWTUjOztAF1meCwyCAAaf2LTQODQ5DTJABEU9MycyTzfQuV4gHI4E4YKfMMikk5kAHoH5BBggFpUqCh0AHdQAHNliEwgAVCChACiAA90tIcOVKtVag17E4XJYkJ11L16P11lthrtxpNajN5iJTEFgWtNtsRnsAEwHBRHUjxACycHsADooHgSOg0glisg6sgAIwABklyAA-MgAERwBXIZgKlgK+5PF7vT7fP4gQFU1ZgyEwtJwiBM5AVKo1eqNNGtKxYjx9PG0wmjSQTcKkub+bhAA)

**Comment by wmichelin** [comment] 2020-01-24 18:21
@jcalz 

Another, even worse example (the value doesn't even match the correct type!)

```
type Field = 'x' | 'y';
interface Foo {
    b?: boolean;
}
const func = (dynamic: Field): Foo => ({
    [dynamic]: 1,
});
```

http://www.typescriptlang.org/play/?ts=3.8.0-dev.20200122&ssl=1&ssc=1&pln=9&pc=1#code/C4TwDgpgBAYglhANgEygXigcgB6agHyxEwG4AoOAO2AgCcAzAQwGNoYB7dqAbzKn6gAjAPwAuIZ0QRGlcgF8yzdpQDOwKPQCulZuigAKZCEqMAtnGbj4SZAEorndAD4DvAVADaRk+eYBdcQBGABoyOVtyMiA

**Comment by RyanCavanaugh** [comment] 2020-01-27 20:43
#32309 is basically the same root cause here. None of this represents an actual unsoundness since `{}` is a valid `Partial<X>` (or `Foo`) and `{ b: true }` is a structural subtype of `{}`

**Closed** 2020-02-01 00:00 UTC
Labels: Question
