### ISSUE TITLE
const string or const number as a type between string (or number) and literal types

### ISSUE THREAD

**Issue by zen0wu** [microsoft/TypeScript#51745] opened 2022-12-04 19:30 UTC
# Suggestion

## 🔍 Search Terms

literal string, const literals, infer literals

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

```ts
const x: const string = "abc" // passes
const y = "adsf" as string
const y2: const string = y // fails


function f<T extends const string>(t: T) {}

const x = 'abc' as const
f(x) // passes
f(x as string) // error

function f<T extends const string[]>(...t: T) {}

const xs = ["a", "b", "c"]
f(...xs) // passes
f(...xs as ["a", string, "c"]) // fails

function f<T extends [string, const string]>(...t: T) {}

const a = "a"
const s = some_str
f(a, s) // fails
f(s, a) // passes
```

The same applies to numbers.

## 📃 Motivating Example

I want to define an API for users to specify a fixed path in an object, consider

```ts
type Obj = {
  a: {
    b: {
      c: "123"
    }
  }
}

type Get<T, K> = K extends keyof T ? NonNullable<T[K]> : never

type GetPath<T, P> = P extends PathKey[]
	? P extends []
		? T // If P is empty, return T.
		: P extends [infer K, ...infer Rest]
		? GetPath<Get<T, K>, Rest> // Else, recurse.
		: never
	: never

function set<T, P extends string[]>(obj: T, path: P, value: GetPath<T, P>) {}

set(
  obj, 
  ["a", "b", "c"],
  value
)
```

Currently, typescript would infer this `set` call's `P` as `string[]`, hence value will be inferred as `never`.

This however, works when `P extends string`, so one way of doing this would be 

```ts
function set<T, P extends string>(obj: T, path: [P], value: unknown) {}
function set<T, P1 extends string, P2 extends string>(obj: T, path: [P1, P2], value: unknown) {}
function set<T, P1 extends string, P2 extends string, P3 extends string>(obj: T, path: [P1, P2, P3], value: unknown) {}
// ...
```

This feels both cumbersome and not scalable.

With the proposed change, it'll look like
```ts
funciton set<T, P extends const string[]>(obj: T, path: P, value: GetPath<T, P> {}
```

On the other hand, sometimes people do want their generics to be inferred as `string`, not the literal passed in.

Allowing a `const` bound would allow developers to express precisely what they want.

## 💻 Use Cases

- Enforce string or number literal types for generics, hence forbidding generic strings/numbers passed in

**Comment by fatcerberus** [comment] 2022-12-04 19:33
Looks like a duplicate of https://github.com/microsoft/TypeScript/issues/51513

**Comment by zen0wu** [comment] 2022-12-04 19:40
True. Mine's syntax is a bit more inclusive with the support of `const ???` and `const string[]`, but the crux is the same.

**Comment by zen0wu** [comment] 2022-12-04 19:42
Almost exactly like what https://github.com/microsoft/TypeScript/issues/41114 is proposing :)

**Closed** 2022-12-08 18:00 UTC
Labels: Duplicate
