### ISSUE TITLE
Partial<this> not working as expected

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/TypeScript#16356] opened 2017-06-08 11:40 UTC
[I refactored the typings of sequelize to use `Partial<this>` to type `.update()`](https://sourcegraph.com/github.com/types/npm-sequelize@master/-/blob/lib/model.d.ts?utm_source=chrome-extension#L2550-2551), but it is not working as expected.

**TypeScript Version:**  2.3.4

**Code**

http://www.typescriptlang.org/play/index.html#src=%0D%0Aclass%20User%20%7B%0D%0A%20%20%20%20activated%3A%20boolean%3B%0D%0A%20%20%20%20async%20activate()%3A%20Promise%3Cvoid%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20await%20this.update(%7B%20activated%3A%20true%20%7D)%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20async%20update(keys%3A%20Partial%3Cthis%3E)%3A%20Promise%3Cvoid%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20Do%20SQL%20UPDATE%20query%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A

```ts
// A *self-contained* demonstration of the problem follows...

class User {
    activated: boolean;
    async activate(): Promise<void> {
        await this.update({ activated: true });
    }
    async update(keys: Partial<this>): Promise<void> {
        // Do SQL UPDATE query
    }
}

```

**Expected behavior:**
Should compile, as `{ activated: true }` should satisfy `Partial<User>` and in turn `Partial<this>`

**Actual behavior:**
```
Argument of type '{ activated: true; }' is not assignable to parameter of type 'Partial<this>'.
```

**Comment by drew-r** [comment] 2017-09-12 22:21
I'm suffering with this as well.
```
class Foo {
  constructor() {}
  x: number;
  bar() {
    // compile error - Type '{ x: number; }' is not assignable to type 'Partial<this>'.
    const y: Partial<this> = { x: 10 };
  }
}
```

**Comment by mhegazy** [comment] 2017-10-31 22:48
Duplicate of https://github.com/Microsoft/TypeScript/issues/19388. 

`this` is a generic type. it represents the type of the derived class at instantiation time. The compiler can not guarantee that type of a property on `this` has not been overridden by a derived class.

Seems that what you want here is `Partial<Base>` and not `Partial<this>`

**Closed** 2017-11-16 16:57 UTC
Labels: Duplicate

**Comment by felixfbecker** [comment] 2017-11-16 17:14
@mhegazy if I used `Partial<Base>`, how would this work?

```ts
class Model {
  update(values: Partial<Model>): void {}
}

class User {
  firstName: string
}

const user = new User()
user.update({ firstName: 'Felix' }) // Property firstName does not exist on type Model
```

**Comment by mhegazy** [comment] 2017-11-16 17:23
in this case you need `Partial<this>`, but setting a default in the function body is unsafe.

**Comment by felixfbecker** [comment] 2017-11-16 17:26
Sorry, what do you mean with setting a default in the function body is unsafe?

**Comment by mhegazy** [comment] 2017-11-16 17:38
```ts
    async activate(): Promise<void> {
        await this.update({ activated: true });  // u do not know what type `activated` will be an a more derived type
    }
```

**Comment by felixfbecker** [comment] 2017-11-16 18:32
Maybe I am misunderstanding you, but any subclass should follow Liskov's substitution principle, so if the superclass declared `activated: boolean`, the subclass shouldn't change that type?

**Comment by mhegazy** [comment] 2017-11-16 20:20
they are substituable for read, but not write.. the sub class are guaranteed to have a type `boolean`, but they can have a more specialized type, e.g. `true`. Please see https://github.com/Microsoft/TypeScript/issues/19388 for explanation.

**Comment by felixfbecker** [comment] 2017-11-16 21:20
Hmm, is there any language feature that would solve this use case?

**Comment by mhegazy** [comment] 2017-11-17 01:19
`readonly`/strict variance, see https://github.com/Microsoft/TypeScript/issues/18770 for more links
