### ISSUE TITLE
Spread operator not inferring parameter T[] after setting value

### ISSUE THREAD

**Issue by pikeas** [microsoft/TypeScript#47913] opened 2022-02-16 00:31 UTC
### 🔎 Search Terms

spread, operator, infer, undefined, iterator, 2488, 2532

### ⏯ Playground Link

[Playground for code snippet](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAcznAJgCjCAtgIwFMAnAZwC5EcCSBtAXQEpEBvAKEU8WMKhGKS0ARAEMhAGkRD8EqRCH0AdLhEAHTJgjMAvAD5EtCJMUnqRMkzYBfNm1CRYCRPhFYzJUgH5K74g2bsXFR45qSInp7aBgCM9BxcMMCImACEvqTM6YhRtLHxnInJWdpR4OiEwDBghOiZIR7ZMXFBxU35wTRkiAD03YgAKgDKiFXADekMiADuMFAAFogiYACeiHBJ84SL+HAAboTtPHwCBqKy0ufySirqmjr6hsam9RbMvc4gUIjocISkYAByL6jEgdcyTOYkA5WIA)

### 💻 Code

```ts
function good(numbers: number[]) {
    return ["a", "b", "c"].map((c) => [c, ...numbers])
}

function bad(numbers?: number[]) {
    numbers ??= [1]
    if (!numbers) numbers = [1]
    if (numbers == undefined) numbers = [1]
    numbers = [1]
    numbers // TS infers numbers[] with any of the above
    return ["a", "b", "c"].map((c) => [c, ...numbers]) // but infers number[] | undefined here
}
```

### 🙁 Actual behavior

Compilation error ts(2488): Type 'number[] | undefined' must have a '[Symbol.iterator]()' method that returns an iterator.
Compilation errors ts(2532): Object is possibly 'undefined'.

### 🙂 Expected behavior

TS infers that `numbers` cannot be undefined.

**Comment by MartinJohns** [comment] 2022-02-16 08:17
Another duplicate of #9998. Narrowing of variables is lost in closures.

**Comment by RyanCavanaugh** [comment] 2022-02-17 18:57
See also #11498

**Closed** 2022-02-20 18:00 UTC
Labels: Duplicate
