### ISSUE TITLE
Type assertion for union types within iterators when returning functions

### ISSUE THREAD

**Issue by daniel-stoll** [microsoft/TypeScript#47844] opened 2022-02-11 12:05 UTC
# Bug Report

### 🔎 Search Terms
error 2345
type assertion in returned function 
union type within iterator

### 🕗 Version & Regression Information
our typescript version 4.2.4
does also appear in "nightly"

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about union/iterator/return functions

### ⏯ Playground Link
```ts repro
type Animal = Spider | Dog

enum AnimalType  {
    'spider',
    'dog'
    }
interface AnimalBase {
    animalType: AnimalType
}

interface Spider extends AnimalBase{
    animalType: AnimalType.spider
}
interface Dog extends AnimalBase {
    animalType: AnimalType.dog
    bondsWithHuman: boolean
}

function getBondWithHumansFunction(animals:Animal[]):(()=>boolean)[]{
    //does also work with other iterators like filter/forEach
    return animals.map(animal=>{
        let animalCopy = animal;
        let animalCopy2 = {...animal}
        if(animal.animalType === AnimalType.dog){
            animal.bondsWithHuman //type check returns correct animal (dog)   
            return ()=>doDogAnalysis(animal) // correctly detected dog
        }

        if(animalCopy.animalType === AnimalType.dog){
            animalCopy.bondsWithHuman //type check returns correct animal (dog)
            return ()=>doDogAnalysis(animalCopy) // wrong detected dog
        }
        
        if(animalCopy2.animalType === AnimalType.dog){
            animalCopy2.bondsWithHuman //type check returns correct animal (dog)
            return ()=>doDogAnalysis(animalCopy2) // wrong detected dog
        }
        else 
            return ()=>false
    })
}

function doDogAnalysis(dog:Dog):boolean{
    return dog.bondsWithHuman;
}
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.5.4#code/C4TwDgpgBAggdgSwLYEMA2UC8UDKYEAmEATlAD5QAiA9gOYBQ9EcArkrIqmgCrjRQBvelBFQA5AGd8RYmIA0w0WIJ0xikQF96COMBIAzFAGNo8ZOgBCKCdCGioKTul6QAXB3M8+9Ldt0HjaDxCEigIAA89OAIJDy4rGztRR08XCHczLjSAOikQ4h8-PWJDEyo6MMjmGLjLa1t1BycvN1qWiGyVBnsAI2poiQB1BGAACwAJNkd3Puo0CEdC+n0WOCNgBH6oWghgC36CYbHJ1DgJADFV9c24AAoUrglXTPQAbQBdAEpXW9vPzAAfLN5o5Ph8kiIAPSQlQQWLoCTUKAAd2oxAA1iiRqMoNQxqERiQUMA0bE0Ah0dB9Ag0MVIfo0QBRYyjRrEXYsYhwJqeCTZVBge7NQEQ+xQebAHlcADC1DAICwUvQAG5GvYJUq0LL5QAmRUCbKGh7oLRi0QIfRCzzZY3tLCYbAvdqdOifUVmkS27J9AZHCZTbnQ0CQKBGUYQIyY9nATlnUNo9nrTVQW5dT6iNUe6OxlP-AEqGi0eDoEASBASK1cdPQ+PERPANAKoh6dYQAhQLqZzSMD1QC2V9DakA25ppe2O0d8F20N1dsW2ofeg5DbEnRxQIN8UPhyNQbNc2JGBMRyW2lNpuf2ffcv6Agt0YuNssVhdykDVyEo4j9Wgd3YntsOzoOdTQ9Od+1fXUR1SLcHQnGDIGnWde3sSCQB1JdfVXAMN0hYNoDDCMow5A9a3rZNU1dS9RGvXM72oQtH1LcsBy1N8dQ-L8fz-Fs9HbTte1As0IDQGwoGokRaNvAFDFEiBGg0T4lhWNYNi2e8izgEtn0o2hXELb5gQWOBRVorpMJiP01zgVUNCAA)

### 🙁 Actual behavior
"animal" is correctly inferred 
The animalCopies have been inferred correctly (animalCopy.bondsWithHuman does not assert)
The value in the returned function can't be inferred correctly.
It has to be checked again within the returend function to work properly

We found this in our React application when we tried to return mapped components with onClick functions.

### 🙂 Expected behavior
I would expect that either I have to check the value in the returned function in every case or that, atleast, the real copy of the value does not need a check/double check.

I think, this might be caused, because the copies can be changed later on in the code and therefore the values might have changed?

**Comment by MartinJohns** [comment] 2022-02-11 12:14
Duplicate of #9998.

**Closed** 2022-02-13 18:00 UTC
Labels: Duplicate
