### ISSUE TITLE
Type inference issue with overload signatures and string literal types

### ISSUE THREAD

**Issue by marcomura** [Microsoft/TypeScript#15086] opened 2017-04-08 15:45 UTC
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
interface Base {
    key: string;
}
interface A extends Base {
}
interface B extends Base {
}

export function test(key: "aa"): A;
export function test(key: "bb1"): B;
export function test(key: "bb2"): B;

export function test(key: string): Base {
    return { key: key };
}

export function bbTest(key: "bb1" | "bb2"): B {
    return test(key);
}
```

**playground url:** 
[here](https://www.typescriptlang.org/play/#src=interface%20Base%20%7B%0D%0A%20%20%20%20key%3A%20string%3B%0D%0A%7D%0D%0Ainterface%20A%20extends%20Base%20%7B%0D%0A%7D%0D%0Ainterface%20B%20extends%20Base%20%7B%0D%0A%7D%0D%0A%0D%0Aexport%20function%20test(key%3A%20%22aa%22)%3A%20A%3B%0D%0Aexport%20function%20test(key%3A%20%22bb1%22)%3A%20B%3B%0D%0Aexport%20function%20test(key%3A%20%22bb2%22)%3A%20B%3B%0D%0A%0D%0Aexport%20function%20test(key%3A%20string)%3A%20Base%20%7B%0D%0A%20%20%20%20return%20%7B%20key%3A%20key%20%7D%3B%0D%0A%7D%0D%0A%0D%0Aexport%20function%20bbTest(key%3A%20%22bb1%22%20%7C%20%22bb2%22)%3A%20B%20%7B%0D%0A%20%20%20%20return%20test(key)%3B%0D%0A%7D)

**Expected behavior:**
No compiler errors; type inference to understand that "return test(key)" returns a B type.

**Actual behavior:**
"return test(key)" doesn't compile because of an argument type error

**Comment by aluanhaddad** [comment] 2017-04-09 03:21
This is working correctly since the overloads only differ by the type of one argument but have the same return type.

You should rather write 

```ts
export function test(key: "aa"): A;
export function test(key: "bb2" | "bb1"): B;
export function test(key: string): Base {
    return { key: key };
}
```

See here https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html for more information (end of page)

**Comment by marcomura** [comment] 2017-04-10 13:29
I'm sorry @aluanhaddad, but no, it's not working correctly.
It doesn't make sense to define the test() overloads as you described, because I could have way more definitions and exponentials permutations.

E.g.
```
export function test(key: "bb1"): B;
export function test(key: "bb2"): B;
export function test(key: "bb3"): B;
export function test(key: "bb4"): B;

export function testB1(key: "aa1" | "aa2"): B { return test(key); }
export function testB2(key: "aa1" | "aa3"): B { return test(key); }
export function testB3(key: "aa1" | "aa2" | "aa3"): B { return test(key); }
export function testB4(key: "aa2" | "aa3" | "aa4"): B { return test(key); }
export function testB5(key: "aa1" | "aa2" | "aa3" | "aa4"): B { return test(key); }
// etc ...
```

Typescript has all the information at compile time to understand that calling test() with an argument of type "bb1" | "bb2" will surely produce a return of type B, so it's definitely an issue that it's not working right now.

Thanks

**Comment by mhegazy** [comment] 2018-02-08 21:49
Duplicate of https://github.com/Microsoft/TypeScript/issues/14107

**Closed** 2018-02-26 20:43 UTC
Labels: Duplicate
