### ISSUE TITLE
Elvis Operator

### ISSUE THREAD

**Issue by OlegDokuka** [Microsoft/TypeScript#3829] opened 2015-07-12 09:47 UTC
Hi guys, I have searched around existing ``Elvis Operator`` in TS and no result has found. That`s why I propose include this ability. 

For example, like in C# or Groovy we can write next expression

``` typescript
let result = somevalue?.name;
```  

it desugared to 

``` javascript
var result = somevalue!==undefined?somevalue.name:undefined;
```
Is it good idea, or it has already discussed?

**Comment by SaschaNaz** [comment] 2015-07-12 17:46
#16, maybe?

**Comment by DanielRosenwasser** [comment] 2015-07-12 18:34
Thanks @SaschaNaz, this is a duplicate of #16.

**Closed by DanielRosenwasser** 2015-07-12 18:34 UTC

**Comment by JeremyCarlsten** [comment] 2016-09-27 15:09
In groovy the elvis operator is part of a ternary operation. It's used to say if this results as truthy then return it, otherwise return something else. ex: 

let isCool = "You bet" ; 
...
return isCool ?:  "Not a chance."

// returns "You Bet"

**Comment by SaschaNaz** [comment] 2016-09-27 15:27
@JeremyCarlsten Please post your comment on #16, as this issue is duplicated.

**Comment by JeremyCarlsten** [comment] 2016-09-27 15:35
I was simply describing a difference. I'll go ahead and post it over there aswell; however, it's probably a separate issue altogether.

**Comment by JavierFuentes** [comment] 2018-04-29 14:04
Sorry, but I can write this in #16 because is limited to collaborators...

**+100 for this!**

~20% of my actual Typescript code in Angular are if() nested statements to avoid errors that stops observable.subscribe() workflows and the code is dirty for this reason.

Angular has this operator only for HTML views...

Typescript already does much more complex things than implementing this secure operator.
