### ISSUE TITLE
JS function public variable autocomplete not working

### ISSUE THREAD

**Issue by skwny** [Microsoft/TypeScript#30673] opened 2019-03-30 18:15 UTC
Description:
When trying to access a function public member (inside the function it was defined), autocomplete only provides suggestions for 'abc' options and not the actual public member. 

Works:
![Screen Shot 2019-03-30 at 11 03 52 AM](https://user-images.githubusercontent.com/13693304/55280015-0cf2ce80-52dd-11e9-8786-9ae07fb9270e.png)

Does not work:
![Screen Shot 2019-03-30 at 11 16 42 AM](https://user-images.githubusercontent.com/13693304/55280032-56431e00-52dd-11e9-9b9f-dd48b8b1d53e.png)

- VSCode Version: Version 1.32.3
- OS Version: Mac Mojave 10.14.3

Steps to Reproduce:
1. Create a javascript function with a public member
2. Try to reference same member below it
3. Suggestion shows 'abc' options  only

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-03-31 14:01
Likely duplicate of #18171

**Comment by RyanCavanaugh** [comment] 2019-04-01 18:25
The screenshot shows a parse error due to the missing function name

**Closed by RyanCavanaugh** 2019-04-01 18:25 UTC
Labels: External

**Comment by skwny** [comment] 2019-04-01 18:37
> The screenshot shows a parse error due to the missing function name

Are you saying the error is because the function is unnamed?
