### ISSUE TITLE
Unterminated regular expression literal when using division

### ISSUE THREAD

**Issue by trevorsg** [Microsoft/TypeScript#18607] opened 2017-09-20 18:35 UTC
**TypeScript Version:**  2.5.2 (works in 2.3.4) - [try it in the Playground](http://www.typescriptlang.org/play/#src=declare%20const%20A%3A%20any%3B%0D%0Adeclare%20const%20B%3A%20any%3B%0D%0Adeclare%20const%20C%3A%20any%3B%0D%0Aconst%20x%20%3D%20\(A%20%2F%202\)%3B%0D%0AB\(%0D%0A%20%20%20%20C\(\)%2C%0D%0A%20%20%20%20\(\)%20%3D%3E%20%7B%20%7D%2C%0D%0A%20%20%20%20\(\)%20%3D%3E%20%7B%20%7D%0D%0A\)%3B).

**Code**
The below is a repro as minimal as I could make it. Changing almost anything will fix the parse errors.
```ts
declare const A: any;
declare const B: any;
declare const C: any;
const x = (A / 2);
B(
    C(),
    () => { },
    () => { }
);
```

**Expected behavior:**
No parser errors.
**Actual behavior:**
Several errors starting with "= expected" and "Unterminated regular expression literal".

**Comment by DanielRosenwasser** [comment] 2017-09-21 08:54
Seems to be working with the latest which would make sense since @sandersn and @weswigham have been working on arrow function lookahead stuff.

Can you give our nightlies a try?

```
npm install typescript@next
```

**Comment by DanielRosenwasser** [comment] 2017-09-21 08:55
Let's add a test case here please.

**Comment by DanielRosenwasser** [comment] 2017-09-21 16:39
Sounds like @sandersn believes this is a dupe of #18123

**Comment by trevorsg** [comment] 2017-09-21 16:44
@DanielRosenwasser Seems plausible. Works with latest for me.

**Closed** 2017-09-21 16:54 UTC
Labels: Duplicate
