### ISSUE TITLE
"delete" does not change the type but only reports error

### ISSUE THREAD

**Issue by kkmuffme** [microsoft/TypeScript#55682] opened 2023-09-08 12:39 UTC
### 🔎 Search Terms

object delete TS2790 optional property

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/FDBmFcDsGMBcEsD2kAEpGIBQoIYCcBzALhQCMMAbAUx1QEoUBvYFVlaZAZ1jXiooAmnFAF4mwAJASOUWHgCeJAOQ4lAGkkTuOWFWWqNU6PFiKUK9ZoAOibhwF7zBzTgEC8VTpwD6ARn2WEgC+ANwgbCjwoCiY+ASiImJy4FQMzBERDtS6vPxCAHSu7p4+vmERQeFsHJDcKAAeormCnGFBQA

### 💻 Code

```ts
function foo( arg: boolean ) {
    const fields = {
		country: 'a',
		state: 'a',
		city: 'a',
		postcode: 'a',
		address_1: 'a',
	};

    if (arg === true) {
        delete fields.address_1;
    }

    const x = fields;
}
```

### 🙁 Actual behavior

`address_1` in `x` is non-optional

### 🙂 Expected behavior

`address_1` in `x` should be optional with ? since in some cases it is deleted.

Typescript reports an error for this, however that doesn't mean that `delete` doesn't change the type.
e.g. if errors are ignored for this, the type will be wrong and lead to bugs downstream.

### Additional information about the issue

Followup to https://github.com/microsoft/TypeScript/issues/13783

**Comment by fatcerberus** [comment] 2023-09-08 12:59
> if errors are ignored for this, the type will be wrong and lead to bugs downstream.

I mean, this is true of pretty much all TS errors, since that’s the entire point of the type checker.  “If you ts-ignore this error you might shoot yourself in the foot” isn’t really a good argument for changing the behavior.

**Comment by MartinJohns** [comment] 2023-09-08 13:00
This sounds like a duplicate of #53697.

> if errors are ignored for this, the type will be wrong and lead to bugs downstream.

That basically applies to all errors.

**Closed as completed** 2023-09-10 19:26 UTC
