### ISSUE TITLE
Documentation is wrong about TypeScript being superset of Javascript?

### ISSUE THREAD

**Issue by Pzixel** [microsoft/TypeScript#38229] opened 2020-04-28 08:38 UTC
Here is a slogan on https://www.typescriptlang.org/ which says _TypeScript is a typed superset of JavaScript that compiles to plain JavaScript._ That means that any valid JS code is also a valid ts code. So I can just rename any `.js` file into `.ts` file, possibly mix it with some TS constucts and it should work (possibly, with some compiler options enabled or disabled). Although, here is an example of code that I couldn't make work:

**Code**

```ts
var foo = {};
foo.bar = 42;
window["A"] = 10;
alert(A);
```

**Expected behavior:**
Compiles into 
```js
var foo = {};
foo.bar = 42;
window["A"] = 10;
alert(A);
```
without errors
**Actual behavior:**
Multiple compilation errors

**Comment by WhileTrueEndWhile** [comment] 2020-04-28 09:52
Spontaneously...
```typescript
var foo: {bar?: number} = {};
foo.bar = 42;
(window as any)["A"] = 10;
alert(A);
```

**Comment by MartinJohns** [comment] 2020-04-28 11:24
> TypeScript is a typed superset of JavaScript that compiles to plain JavaScript

This means that all JavaScript syntax and features are supported in TypeScript. It doesn't mean that all JavaScript is valid TypeScript - such a meaning would be ad absurdum, it would invalidate the entire point of TypeScript: additional type safety.

**Comment by Pzixel** [comment] 2020-04-28 11:30
> This means that all JavaScript syntax and features are supported in TypeScript. It doesn't mean that all JavaScript is valid TypeScript - such a meaning would be ad absurdum

I always thought that is what "superset" means.

> it would invalidate the entire point of TypeScript: additional type safety.

No, it would make sense in at least situation when you have a "bad" TS file and enhance it, gradually enforcing more and more strict rules. IIRC that was recommende for migration from JS to TS in 0.x-1.x versions of TypeScript.

**Comment by nmain** [comment] 2020-04-28 11:53
Duplicate of https://github.com/microsoft/TypeScript/issues/37908.  Some useful comments in there from members of the Typescript team.

**Closed** 2020-05-01 16:03 UTC
Labels: Duplicate

**Comment by Pzixel** [comment] 2020-05-01 16:35
I'm still pretty sure #37908 was closed by mistake. I mean Scala has all the features Java have it doesn't make Scala superset of Java. 

There are suggestions how to make migration easier but there is nothing about *why* it should be considered a superset.

**Comment by nattthebear** [comment] 2020-05-01 16:46
The why is covered in https://stackoverflow.com/questions/41750390/what-does-all-legal-javascript-is-legal-typescript-mean
