### ISSUE TITLE
Change in inferred type in 3.6 for function call using generic union instantiated at string literal 

### ISSUE THREAD

**Issue by lukehoban** [microsoft/TypeScript#33227] opened 2019-09-03 23:54 UTC
**TypeScript Version:**  3.6.2

**Search Terms:** regression, string literal, union, 3.6, inference, generic.

**Code**

```ts
type NetworkProtocol = "TCP";
type Input<T> = Promise<T> | T;
function ifUndefined<T>(input:Input<T> | undefined, value: Input<T>): Promise<T> {
    throw new Error();   
}
const y = ifUndefined(new Promise<NetworkProtocol>(() => {}), "TCP") 
const z: Promise<NetworkProtocol> = y;
```

**Expected behavior:**
No error (3.5 and earlier).

**Actual behavior:**
A type error (3.6.2):

```
Type 'Promise<string>' is not assignable to type 'Promise<NetworkProtocol>'.
  Type 'string' is not assignable to type 'NetworkProtocol'.
```

**Playground Link:** [Playground](http://www.typescriptlang.org/play/#code/C4TwDgpgBAchwHcD2AnA1gBRU4SDGSANlALxQBEAKgMIbkDcAUKJFAJIB2YArsADyUAfKShYkAWwCWAZwgDhAHyiUmAM24c8wSUg5RJqgKocAJhFWSOEE-IAUlnsABcnR-KhKNZi1ZMAaKAA3AENCbggndi5eeQBKSLEpWXcAb0YoDKhgAAtsBCgrfIBRFGwUW1j6TMYAX0YCDmlgKBARA2NvS2tbQtFsJLk4RFRMbFwCQkFbCtJhFJrYgKpaclioet0mqAAvBP6ZQfhkdDFxomEyEHogA).  The TypeScript Playground doesn't appear to yet use 3.6.2 though so this doesn't repro in the playground.

Note that this example does work as expected - and looks morally "the same":

```ts
type NetworkProtocol = "TCP";
function ifUndefined<T>(input:Promise<T> | undefined, value: T): Promise<T> {
    throw new Error();   
}
const y = ifUndefined(new Promise<NetworkProtocol>(() => {}), "TCP") 
const z: Promise<NetworkProtocol> = y;
```

**Comment by schlundus** [comment] 2019-09-04 05:40
Yes, i can confirm there seems to be an issue in 3.6.2, simpler example here:

![image](https://user-images.githubusercontent.com/17083185/64228420-1402b600-cee7-11e9-83d3-19bc14340406.png)

It shows the wrong type inference

**Comment by fatcerberus** [comment] 2019-09-04 06:13
I think this probably has to do with https://github.com/microsoft/TypeScript/issues/33131#issuecomment-526391597 and is therefore a bug.

The example above was a generic function with its argument typed as `string | T`.  The call site passes in a string, it matches the `string` part of the union.  The compiler then doesn't bother to infer `T`.  `T` therefore defaults to `unknown` (its constraint), `bar`'s type is instantiated to `string | unknown` which collapses to simply `unknown` by subtype reduction.

**Comment by sandersn** [comment] 2019-09-04 16:15
Yeah, I think it's to do with the changes to naked type parameter inference. @weswigham mind taking a look to confirm before I close this as a duplicate?

**Comment by sandersn** [comment] 2019-09-04 16:17
@lukehoban Here's a link to a build you can try to see if it fixes the problem:

https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/42167/artifacts?artifactName=tgz&fileId=84FA9BD7390E9AE04ED6006D9E265FBCF309C643377CBBC8CB1CE445229AAB2B02&fileName=/typescript-3.7.0-insiders.20190830.tgz

[Some install instructions](https://github.com/microsoft/TypeScript/pull/33154#issuecomment-526408993)

**Comment by ahejlsberg** [comment] 2019-09-05 14:02
(Hi Luke! 👋)

This is an effect of #32460, and I would argue one that is intended. In the call to `ifUndefined` we make two inferences for `T`, in the first argument from `Promise<NetworkProtocol>` to `T | Promise<T> | undefined`, and in the second argument from `string` to `T | Promise<T>`. Previously we'd give lower priority to the second inference because we infer to a naked type parameter in a union, and thus we'd end up inferring `NetworkProtocol` for `T`. Now we give equal priority to the inferences (which really is the correct behavior) and we therefore end up with `string`.

The string literal `"TCP"` is widened to `string` in the second argument because there is nothing to indicate that it shouldn't be. It works as intended if you add a `const` assertion:

```ts
const y = ifUndefined(new Promise<NetworkProtocol>(() => {}), "TCP" as const);
```

**Closed** 2019-09-10 20:00 UTC
Labels: Working as Intended
