### ISSUE TITLE
Conflicting behavior when spreading string inside array

### ISSUE THREAD

**Issue by btroncone** [Microsoft/TypeScript#10114] opened 2016-08-03 15:10 UTC
I have noticed some conflicting output between TypeScript and browser engines for the following code snippet. 

**TypeScript Version:**  1.8.0

**Code**
### TypeScript Output
```ts
[...'abc'] //abc
```

### Chome/Firefox
```js
[...'abc'] //['a','b','c']
```

**Expected behavior:**
Based on behavior from browsers I would expect an array of characters to be returned.
**Actual behavior:** 
It appears TypeScript calls `slice` on `'abc'`, returning `'abc'` instead.

**Comment by kitsonk** [comment] 2016-08-03 16:35
Dupe of #2585

**Closed** 2016-09-20 23:10 UTC
Labels: Duplicate
