### ISSUE TITLE
Please share large source lines when possible

### ISSUE THREAD

**Issue by SnarkBoojum** [microsoft/TypeScript#45849] opened 2021-09-13 06:43 UTC
While packaging 4.4.3 for Debian, the tools complained:
```
E: node-typescript source: source-is-missing lib/tsc.js line 100216 is 9536 characters long (>512)
E: node-typescript source: source-is-missing lib/tsserver.js line 148247 is 9536 characters long (>512)
E: node-typescript source: source-is-missing lib/tsserverlibrary.js line 147421 is 9536 characters long (>512)
E: node-typescript source: source-is-missing lib/typescript.js line 138426 is 9536 characters long (>512)
E: node-typescript source: source-is-missing lib/typescriptServices.js line 138426 is 9536 characters long (>512)
E: node-typescript source: source-is-missing lib/typingsInstaller.js line 103440 is 9536 characters long (>512)
```

and in fact, the problem is with unicodeES3Identifier* variables: it is legitimate source code, but indeed looks suspicious.

I suggest to share those variables instead of copying them in several source files: that will be much safer in the long run.

**Comment by MartinJohns** [comment] 2021-09-13 07:33
It sounds like a duplicate of #35210 / #35561.

**Comment by SnarkBoojum** [comment] 2021-09-13 09:18
No, it's not really a duplicate. Modularizing would probably (but not surely) solve it, but it's not quite the same.

**Comment by MartinJohns** [comment] 2021-09-13 09:25
Then I'm not sure what your issue is. Values in the .js files **can't** be shared, because the compiler is not modularized - every .js file is running independently.

**Closed** 2021-09-13 16:35 UTC
Labels: Unactionable
