### ISSUE TITLE
Inferences from type aliases disregard variance

### ISSUE THREAD

**Issue by ahejlsberg** [microsoft/TypeScript#31659] opened 2019-05-29 18:51 UTC
**TypeScript Version:**  3.5.0 and previous

**Code**

```ts
// @strictFunctionTypes: true

type Func<T> = (x: T) => void;

declare let f1: Func<string>;
declare let f2: Func<"a">;

declare function foo<T>(f1: Func<T>, f2: Func<T>): void;

foo(f1, f2);  // Error
```

**Expected behavior:**

No error.

**Actual behavior:**

Error.

When inferring between instantiations of the same type alias we always make covariant inferences instead of computing and using proper variance information.

**Comment by jcalz** [comment] 2019-05-29 19:29
Possibly duplicate of or related to #31251 and #31295?

**Comment by ahejlsberg** [comment] 2019-05-29 19:59
> Possibly duplicate of or related to #31251 and #31295?

No, I don't think either of those are related.

**Comment by jcalz** [comment] 2019-05-29 22:07
Okay (*@jcalz slinks away*)

**Closed** 2019-05-30 21:09 UTC
Labels: Bug
