### ISSUE TITLE
Internal modifier

### ISSUE THREAD

**Issue by dipacs** [Microsoft/TypeScript#5538] opened 2015-11-05 08:05 UTC
It could be very useful to implement the internal modifier which can be applied on functions, properties and constructors. The member with this kind of modifier only visible inside a module or namespace (no declaration is generated for it in the .d.ts file). It can be very useful when you develop a resuable library.

**Comment by kitsonk** [comment] 2015-11-05 08:12
Dupe of #5228

**Closed** 2015-11-05 21:35 UTC
Labels: Duplicate
