### ISSUE TITLE
Better "Named" Params syntax

### ISSUE THREAD

**Issue by yordis** [microsoft/TypeScript#49294] opened 2022-05-28 20:52 UTC
## 🔍 Search Terms

`named params`, `named arg`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestions

JS doesn't have Named-Parameters (Like Python) and it seems that the answer from TC39 is to use destructuring with one argument input instead of adding more things to the language; then here I am.

Problem Statement: When using destructuring with a combination with inline definitions the code becomes messy and quite long to the point that you end up with the exact same object definition but one is for runtime and the other one for typespec

```ts
function registerCustomer({
  displayName,
  firstName,
  lastName,
  addressOne,
  addressTwo,
  addressCity,
  addressState,
  AddressCountry,
}: {
  displayName: string;
  firstName: string;
  lastName: string;
  addressOne: string;
  addressTwo: string;
  addressCity: string;
  addressState: string;
  addressCountry: string;
}) {}
```

Are you aware of any suggestions or if TypeScript could mitigate such issue somehow?
Maybe be something like

```ts
function registerCustomer({
  displayName as string,
  firstName as string,
  lastName as string,
  addressOne as string,
  addressTwo as string,
  addressCity as string,
  addressState as string,
  AddressCountry as string
}) {}
```

**Comment by fatcerberus** [comment] 2022-05-28 21:25
Duplicate of #29526.

**Closed** 2022-05-28 21:31 UTC
