### ISSUE TITLE
Polymorphic "this" isn't polymorphic in some cases

### ISSUE THREAD

**Issue by xealot** [Microsoft/TypeScript#5493] opened 2015-11-02 16:26 UTC
Sorry for the crap title, I'm not entirely sure what is going on but I think it's a bug. I also think this is somewhat related to #5449 but am unsure.

Library Example:
```typescript
export interface InstanceConstructor<T extends BaseModel> {
    new(fac: Factory<T>): T;
}

export class Factory<T extends BaseModel> {
    constructor(private cls: InstanceConstructor<T>) {}

    get() {
        return new this.cls(this);
    }
}

export class BaseModel {
    constructor(private fac: Factory<this>) {}

    refresh() {
        // get returns a new instance, but it should be of
        // type Model, not BaseModel.
        return this.fac.get();
    }
}
```

User Code Example:
```typescript
export class Model extends BaseModel {
    do() {
        return true;
    }
}

// Kinda sucks that Factory cannot infer the "Model" type
let f = new Factory<Model>(Model);
let a = f.get();

let b = a.refresh();
```

The issue that the compiler complains about is as follows:
```
error TS2345: Argument of type 'typeof Model' is not assignable to parameter of type 'InstanceConstructor<Model>'.
  Types of parameters 'api' and 'api' are incompatible.
    Type 'Factory<this>' is not assignable to type 'Factory<Model>'.
      Type 'this' is not assignable to type 'Model'.
        Type 'BaseModel' is not assignable to type 'Model'.
          Property 'do' is missing in type 'BaseModel'.
```

If I change the extended model to be specific it errors in different way, but same theme.

```typescript
export class Model extends BaseModel {
    constructor(fac: Factory<Model>) {
        super(fac);
    }

    do() {
        return true;
    }
}
```

```
error TS2345: Argument of type 'Factory<Model>' is not assignable to parameter of type 'Factory<this>'.
  Type 'Model' is not assignable to type 'this'.
```

I think the reason is because `this` isn't being polymorphic in either the template or the constructor. When `this` is analyzed in the constructor of `BaseModel` it seems to stick with that context.

I initially posted about the use of polymorphic `this` which was answered by @RyanCavanaugh http://stackoverflow.com/questions/33443793/create-a-generic-factory-in-typescript

**Comment by mhegazy** [comment] 2015-11-02 17:30
this looks like a duplicate of #5449, `this` types are not supported in constructor arguments, nor is it supported in static methods parameters or return types. #5449 tracks adding the correct error message.

**Closed by mhegazy** 2015-11-02 17:30 UTC

**Comment by xealot** [comment] 2015-11-02 17:33
So this use case is not supported? Based on my example is there any other way to accomplish what I'm attempting? This isn't an unusual pattern for Resource/Model implementation.

**Comment by mhegazy** [comment] 2015-11-02 17:40
> So this use case is not supported?

that is correct. constructors are really part of the static side of classes, and for these `this` types do not apply.

> Based on my example is there any other way to accomplish what I'm attempting? This isn't an unusual pattern for Resource/Model implementation.

As mentioned earlier, this was not part of the original implementation. we should reconsider thought.

**Comment by xealot** [comment] 2015-11-02 17:43
Fortunately the type system still seems to inspect and output things correctly so this isn't slowing me down much which is great. I'll keep an eye on these two issues for updates.
