### ISSUE TITLE
Invalid declarations emitted for mixins that use generic type parameters

### ISSUE THREAD

**Issue by appsforartists** [Microsoft/TypeScript#18786] opened 2017-09-27 06:58 UTC
**TypeScript Version:** 2.4.1

**Code**
For simplicity, I've removed anything that isn't essential to demonstrate the problem (hence, the pointless signature/implementation of `withMixin`).
```ts
export function withMixin<S>(superclass: S): S {
  return superclass;
}

export class Base<T> {
  constructor(value: T) {
  }
}

export class MixedTogether<T> extends withMixin<new (value: T) => Base<T>>(Base){}
```

**Expected behavior:**
A valid declaration is emitted.

**Actual behavior:**
The mixed-together class is emitted in two separate pieces, with the generic defined in one statement, but used in another.  This makes the generic `T` unresolvable, and throws errors in any code that depends on the emitted d.ts file.

```typescript
export declare function withMixin<S>(superclass: S): S;
export declare class Base<T> {
    constructor(value: T);
}
declare const MixedTogether_base: new (value: T) => Base<T>;
export declare class MixedTogether<T> extends MixedTogether_base {
}
// Any code that depends on this module will now throw:
//     error TS2304: Cannot find name 'T'.
// even though the module itself built cleanly
```

**Comment by mhegazy** [comment] 2017-09-28 00:22
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/18545

**Comment by appsforartists** [comment] 2017-09-28 00:28
Sorry - issues like this are hard to search for (but I did try).

**Closed** 2017-09-28 00:28 UTC
Labels: Duplicate
