### ISSUE TITLE
Chaining a Function that Returns Promise<any> Results in Incorrect Type

### ISSUE THREAD

**Issue by ChrisGrohHS** [Microsoft/TypeScript#12763] opened 2016-12-08 15:14 UTC
**TypeScript Version:**  2.1.4

**Code**

```ts
declare function loadBlob(): Promise<Blob>;
declare function readBlobAsJson(blob: Blob): Promise<any>;

loadBlob().then(readBlobAsJson).then(d => {
    d.x// d is Type Blob here
});
```

**Expected behavior:**
Compiles without error

**Actual behavior:**
Property 'x' does not exist on type 'Blob'.

This works without error if an explicit type is set on readBlobAsJson instead of any. Compiled without error in 2.0.6

**Comment by Alexander-Taran** [comment] 2016-12-08 20:25
duplicate of  #10977

**Closed** 2017-04-21 16:58 UTC
Labels: Duplicate
