### ISSUE TITLE
language constructs documentation

### ISSUE THREAD

**Issue by AbhinavAtul** [microsoft/TypeScript#41206] opened 2020-10-22 20:42 UTC
read the handbook, features like [async|await](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-1-7.html#asyncawait-support-in-es6-targets-node-v4) are **buried**,
A **comprehensive** one place index of all language constructs that are not deprecated 
1. Classification/Section
    1.1 ...              **since version 1.7**
2. ...    

would be very useful for newbies and backend programmers

**Comment by MartinJohns** [comment] 2020-10-22 21:04
Please respect the issue templates for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) and [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md). :-) This will make the work for the TypeScript team much easier and they can focus on improving the language, instead of deciphering GitHub issues.

---

Duplicate of #36009.

> I think even in the new handbook we probably wouldn't be documenting it in any depth. Perhaps there's a space to say what versions of ECMAScript TypeScript is up to, and what the proposals we've implemented look like, but the TS docs need to focus on the extra layer TS adds and not the many layers of JS underneath.

**Comment by RyanCavanaugh** [comment] 2020-10-22 22:38
async/await is a JS construct; the TS handbook is not intended to teach you all of JavaScript

**Closed** 2020-10-25 20:00 UTC
Labels: Working as Intended
