### ISSUE TITLE
for(...in...) with mapped types cannot see index type (noImplicitAny)

### ISSUE THREAD

**Issue by jameswilddev** [Microsoft/TypeScript#14451] opened 2017-03-04 09:19 UTC
**TypeScript Version:**  2.2.1
**Code**

```ts
// noImplicitAny must be enabled.

type Options = "A" | "B" | "C"
const MappedOptions: {[option in Options]: number } = {
    A: 2,
    B: 3,
    C: 4
}

for (const key in MappedOptions) {
    alert(MappedOptions[key])
}
```

**Expected behavior:**
This compiles, as the index type of MappedOptions is Options.

**Actual behavior:**
A compile-time error occurs as MappedOptions has no index signature.

**Comment by ikatyang** [comment] 2017-03-05 13:28
The type of `key` is considered a `string`, you have to convert it to `Options` manually, since there is no index signature, e.g. `{ [key: string]: number }`.

solution:
```ts
for (const key in MappedOptions) {
  alert(MappedOptions[<Options>key]);
}
```
or
```ts
Object.keys(MappedOptions).forEach((key: Options) => {
  alert(MappedOptions[key]);
});
```
I recommend the second one since it is clearer.

**Comment by jameswilddev** [comment] 2017-03-05 14:32
Thanks.  I'm already doing that (MappedOptions[key as Options]).

**Comment by mhegazy** [comment] 2018-02-09 01:33
Duplicate of https://github.com/Microsoft/TypeScript/issues/20503 or at least the same rational why it works this way. Please see https://github.com/Microsoft/TypeScript/pull/12253#issuecomment-263132208 for more context.

**Closed** 2018-02-26 20:43 UTC
Labels: Duplicate
