### ISSUE TITLE
Class member with decorator is incorrectly marked unused

### ISSUE THREAD

**Issue by yseymour** [Microsoft/TypeScript#19826] opened 2017-11-08 03:03 UTC
**TypeScript Version:**  2.6.1

**decorate.ts**
```ts
const f = (_p,_f) => {};
class foo {
	@f
	private bar():void {}
}
```

Compile with
```
tsc --experimentalDecorators --noUnusedLocals decorate.ts
```

**Expected behavior:**
Successful compile

**Actual behavior:**
Error:
```decorate.ts(4,10): error TS6133: 'bar' is declared but its value is never read.```
In a real world case, the side-effects of the decorator mean that bar() might in fact get called at some point (for instance, the decorator might attach an event listener) and so I believe this error should not be thrown.

**Comment by mhegazy** [comment] 2017-11-08 20:19
Duplicate of https://github.com/Microsoft/TypeScript/issues/13120

**Closed** 2017-11-09 00:26 UTC
Labels: Duplicate
