### ISSUE TITLE
[Feature] Ability to typeof imports

### ISSUE THREAD

**Issue by rraziel** [microsoft/TypeScript#42482] opened 2021-01-25 17:13 UTC
# Suggestion

Expand the (very nice) ability to infer the type of an `import()` call expression so that such imports can be wrapped.

## 🔍 Search Terms

typeof import

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Make it possible to expose the type of what a module exports:

```ts
function loadModule<T extends string>(modulePath: T): Promise<typeof import(T)>;
```

## 📃 Motivating Example

Library code that allows plugins, lazy-loading, etc. needs the user code to perform the import call itself in order to get typing information.

```ts
const plugin = await loadPlugin('@project/x/y', 'exportedFunction');
```

Without the feature, anything can be used instead of `exportedFunction`, but with the feature it would be possible to restrict the name and type the result:

```ts
function loadPlugin<
  ModuleName extends string,
  ExportName extends keyof typeof import(ModuleName)
>(
  moduleName: ModuleName,
  exportName: ExportName
): Promise<Plugin<typeof import(ModuleName)[ExportName]>>;
```

That's a fairly simple example, but it becomes more interesting when passing functions that would receive those exported objects as their parameters, etc.

## 💻 Use Cases

Usage:
- plugin mechanisms
- lazy-loading features
- build-time DSLs

Short-comings with the current approach:
- nothing but import() can be used while keeping type information

Short-comings with the proposed approach:
- tooling may sometimes need to be adapted to "detect" such new import constructs

Workarounds:
- not many are available apart from importing the type/re-declaring separately

**Comment by DanielRosenwasser** [comment] 2021-01-25 22:43
Seems like a duplicate of #26139 and a duplicate of #41550.

**Comment by rraziel** [comment] 2021-01-25 23:54
Hm true, and a little bit #31090 as well
I suppose it's not worth keeping this one opened then, and instead I can go thumb-up the other ones or something 😅

**Closed** 2021-02-01 18:00 UTC
Labels: Duplicate
