### ISSUE TITLE
Invalid ES2023 target suggested

### ISSUE THREAD

**Issue by gabritto** [microsoft/TypeScript#57683] opened 2024-03-07 21:44 UTC
### 🔎 Search Terms

es2023

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### 💻 Code

```jsonc
// tsconfig.json
{
    "compilerOptions": {
        "target": |
    }
}
```

### 🙁 Actual behavior
We get completions for "target" that include "ES2023".
If we accept that, we get the following error:
"error TS6046: Argument for '--target' option must be: 'es5', 'es6', 'es2015', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'es2021', 'es2022', 'esnext'."

### 🙂 Expected behavior

No suggestion of "ES2023".

### Additional information about the issue

**Comment by whzx5byb** [comment] 2024-03-07 21:48
Duplicate of https://github.com/microsoft/TypeScript/issues/56303?

**Comment by gabritto** [comment] 2024-03-07 22:53
@rbuckton suggested we should add `ES2023` so that we can include `ES2023` as a lib if your target is `ES2023`, but @RyanCavanaugh [said we shouldn't](https://github.com/microsoft/TypeScript/issues/56303#issuecomment-1792878848) have it as a target, so I just wanted to double check.

If we do want to remove it, we need to remove it [here](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/tsconfig.json#L596C21-L596C29).

**Comment by RyanCavanaugh** [comment] 2024-03-07 23:31
I think I was wrong in that one and we should just have targets for every named spec version; even if in practice a few are identical syntaxwise for some stuff, it's *way* less confusing.

**Closed** 2024-04-12 01:42 UTC
Labels: Bug, Fix Available
