### ISSUE TITLE
getBBox should return a SVGRect

### ISSUE THREAD

**Issue by iahu** [microsoft/TypeScript#50965] opened 2022-09-27 07:23 UTC
# Bug Report

### 🔎 Search Terms

[getBBox](https://github.com/microsoft/TypeScript/issues?q=is%3Aissue++getBBox+) and [SVGRect](https://github.com/microsoft/TypeScript/issues?q=is%3Aissue++SVGRect+)

### 🕗 Version & Regression Information

- This is the behavior in every [version](https://www.typescriptlang.org/play?ts=3.3.3&install-plugin=playground-typescript-json-schema#) I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBBBuBzAogGwKYFt1lgXhgBMRgBXbXAOmACd0BDKdNLHKAOQGUAKAcgAsoUAA4AuAPTiA7jMpSAzJRA1E4gEwAGLeISJeAGhi9dvAJQAoUJFgAjGyAAeMArpYUolROigAhH4+4Lc0twCBAMSlQQRG47RxgAS2t6MGB0EAAzGE4ANQBxACV0YChTGEkYKBpSdBDIcPRI6Nj7JyToFLTMmAARAHkAWSKSsoqM+lQIWqswiKiYqABPYXSsuIdKGgTEQX0lle6Ydcp7IRBMPeXVmCPWyigQAClOPvZR8SOQKH4YejoYABEpDAhHQGSS6EIAKAA)

### 💻 Code

```ts
const svgElement = document.createElementNS('http://www.w3.org/2000/svg', 'svg')
const bbox = svgElement.getBBox()


console.log(bbox instanceof SVGRect) // true
console.log(bbox instanceof DOMRect) // false
console.log(typeof bbox.right, typeof bbox.bottom, typeof bbox.toJSON) // both are "undefined"
```

### 🙁 Actual behavior

`bbox.getBBox()` now return a `DOMRect` type, it includes some properties, which `getBBox` are not returned.

### 🙂 Expected behavior

`bbox.getBBox()` should return a `SVGRect`

there is a [commit](https://github.com/iahu/TypeScript/tree/getBBox-return-type) try to fix this issues, you can take a look on it.

**Comment by MartinJohns** [comment] 2022-09-27 08:07
Duplicate of https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/974.

**Closed** 2022-09-30 18:00 UTC
Labels: Duplicate
