### ISSUE TITLE
support for iterators with a return value

### ISSUE THREAD

**Issue by Sheyne** [Microsoft/TypeScript#14110] opened 2017-02-16 08:36 UTC
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
function *f(){
    yield 1;
    return "hello";
}
```

When generators in Javascript return, then set `done: true`, but they pass one last `value`. This is typically `undefined`, but is the return value of the function. This could be its own type and and be a second type parameter to the IterableIterator interface. Could also add support for getting values from yield statements e.g.:

```ts
function *f(){
    const x: string = (yield 7);
}
```

With the `Iterator` interface looking something like:

```ts
interface FinishedIterator<V> {
    done: true;
    value: V;
}
interface ProgressingIterator<T> {
    done: false;
    value: T;
}
interface Iterator <T, U, V> {
    next(u: U): FinishedIterator<V> | ProgressingIterator<T>;
}
```

I'm not sure how to do optional type parameters, but this would help with backwards compatibility.

**Comment by mhegazy** [comment] 2017-04-19 19:50
Duplicate of https://github.com/Microsoft/TypeScript/issues/2983

**Closed** 2017-04-20 23:40 UTC
Labels: Duplicate
