### ISSUE TITLE
Type guards in string literals in callbacks

### ISSUE THREAD

**Issue by wallverb** [Microsoft/TypeScript#9774] opened 2016-07-17 12:33 UTC
**TypeScript Version:**  (2.0.0-beta)

**Code**

```ts
interface Test1 {
    type: 'test1'
    label: 'string'
}
interface Test2 {
    type: 'test2'
}

let a: Test1 | Test2

if (a.type == 'test1') {
    console.log(a.label) // works ok
    setTimeout(()=>{
        console.log(a.label) // Error: Property 'label' does not exist on type 'Test1 | Test2'
    })
}

```

**Expected behavior:**
setTimeout case should work ?

**Actual behavior:** 
`Error: Property 'label' does not exist on type 'Test1 | Test2'` in `setTimeout`

**Comment by mhegazy** [comment] 2016-07-17 17:46
Duplicate of https://github.com/Microsoft/TypeScript/issues/7662. please see https://github.com/Microsoft/TypeScript/issues/7719#issuecomment-202684512 for more details.

**Closed by mhegazy** 2016-07-17 17:46 UTC
