### ISSUE TITLE
Intellisense for the 'from' of an import

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#5161] opened 2015-10-07 23:18 UTC
We have a lot of modules which a user might want to import, and it would be nice to show a list of these as a completion hint after `import {} from '`
Additionally, we have so many modules that walking the filesystem is not practical, and some of them are generated external module names, not files. So we would like to run a periodic indexing, and then somehow provide a list of these to the language services (eg. an RPC, or a file we stage on local disk, etc.)

cc @mprobst @rkirov

**Comment by DanielRosenwasser** [comment] 2015-10-07 23:20
Hey Alex, seems like a duplicate of #188.

**Closed** 2015-10-07 23:20 UTC
Labels: Duplicate
