### ISSUE TITLE
Incorrect codegen with emitDecoratorMetadata + ES6 modules

### ISSUE THREAD

**Issue by jods4** [Microsoft/TypeScript#3793] opened 2015-07-09 14:14 UTC
I upgraded from the 1.5 beta to a nightly build (ntypescript 20150709...) and found this regression:

Relevant code:
```
import { autoinject } from 'aurelia-framework';
import { Router } from 'aurelia-router';

@autoinject()
export class X {
  constructor(r: Router) {}
}
```

ES5 + AMD code gen fails at runtime with "Router is not defined", relevant parts:
```
define(["require", "exports", "aurelia-framework", "aurelia-router"], 
  function(require, exports, aurelia_framework_1, aurelia_router_1) {
    // ...
    X = __decorate([
      __metadata('design:paramtypes', [Router])
    ], X);
});
```

With the skeleton, `Router` should be `aurelia_router_1.Router`.

**Comment by mhegazy** [comment] 2015-07-09 18:05
@rbuckton has a fix for this.

**Comment by jods4** [comment] 2015-07-09 18:56
Have to say that I'm disappointed this is scheduled for 1.6. 
It's a show stopper and I can't use any TS release after the bug was introduced.
Hopefully you'll publish a 1.6 beta at the same time as 1.5 (I'm already on the beta "channel" after all).

**Comment by mhegazy** [comment] 2015-07-09 19:37
@jods4 can you give this: https://github.com/Microsoft/TypeScript/pull/3690  a try?

**Comment by jods4** [comment] 2015-07-09 20:33
@mhegazy sure, how can I easily grab it?

**Comment by SnareChops** [comment] 2015-07-09 21:58
Just ran into this issue as well. This is a critical bug for large applications. For example this breaks Angular2. If writing all code in 1 file, this isn't an issue, but really who writes an entire application in a single code file... Terrible practice.

**Comment by jods4** [comment] 2015-07-09 22:35
Just noticed that the underlying bug is most probably the same as for #3663

**Comment by SnareChops** [comment] 2015-07-09 22:37
Yes, that is the exact issue I am having.

**Comment by mhegazy** [comment] 2015-07-13 18:16
@jods4 and @SnareChops  can you give the latest from master a try?

the latest compiler drop should be in: https://raw.githubusercontent.com/Microsoft/TypeScript/master/bin/tsc.js

**Comment by SnareChops** [comment] 2015-07-13 21:21
@mhegazy Hmmm.... It looks better, but still a flaw I feel.

Before this version

```
import MyThing from './MyThing';
...
constructor(thing: MyThing){}
...
```
Was giving a result of
```
var my_thing_1 = require('MyThing');
...
__metadata('design:paramtypes', [MyThing])
...
```
Which was a problem of course as it should be
```
__metadata('design:paramtypes', [my_thing_1.default])
```

Now using the version you linked above I am getting
```
__metadata('design:paramtypes', [Object])
```
Which would probably run, but in my case (Angular2) that information is being used by the dependency injector to select the correct class to instantiate and pass to the constructor. Therefore it must match.

Thoughts?

**Comment by mhegazy** [comment] 2015-07-13 21:33
what is "MyThing"? is it an interface or a class?

**Comment by SnareChops** [comment] 2015-07-13 21:43
It's a class

**Comment by mhegazy** [comment] 2015-07-13 22:26
Can you provide more information then.. i am not seeing the same issue locally:

```ts
import { autoinject } from 'aurelia-framework';
import { Router } from 'aurelia-router';

@autoinject()
export class X {
  constructor(r: Router) {}
}
```
generates:

```js
define(["require", "exports", 'aurelia-framework', 'aurelia-router'], function (require, exports, aurelia_framework_1, aurelia_router_1) {
    var X = (function () {
        function X(r) {
        }
        X = __decorate([
            aurelia_framework_1.autoinject(), 
            __metadata('design:paramtypes', [aurelia_router_1.Router])
        ], X);
        return X;
    })();
    exports.X = X;
});
```

**Comment by SnareChops** [comment] 2015-07-13 23:31
I have created a test repo with the steps to replicate, and sufficient code to reproduce (At least on my machine). If you discover something I am doing wrong then please let me know.

Also I noticed that the import statement is not being outputted in the compiled file. I made a not of it in the repo.

https://github.com/SnareChops/reflect-issue

**Comment by mhegazy** [comment] 2015-07-14 00:06
thanks for the repro. i see the issue now.

**Comment by SnareChops** [comment] 2015-07-14 00:08
Welcome, glad I could help.

**Comment by jods4** [comment] 2015-07-14 08:17
I don't know what's different in @SnareChops case, but my case (ES5 + AMD, code decribed above) now works correctly. :ok_hand:

**Comment by rbuckton** [comment] 2015-07-16 22:54
The issue was due to the fact that both the type annotation and the parameter name were the same: `Service: Service`. The way the type name is resolved is it starts name resolution at the location of the identifier and walks up the tree. When trying to resolve Service as a value, it sees the `Service` parameter name and uses that first.

I have a PR pending that should fix this.

**Comment by mhegazy** [comment] 2015-08-06 23:52
@jods4 and @SnareChops sorry fro the trouble; can you try the latest fix one more time..

**Closed** 2015-08-06 23:52 UTC
Labels: Bug, Fixed, High Priority

**Comment by jods4** [comment] 2015-08-07 10:03
As noted above, my repro was already fixed before. I think @SnareChops had a more complicated case than I did.
