### ISSUE TITLE
Code hint not work at specific situation: Key Remapping + Generic Type Infering + Partial<T>

### ISSUE THREAD

**Issue by k8w** [microsoft/TypeScript#46706] opened 2021-11-06 05:27 UTC
# Bug Report

### 🔎 Search Terms
- code hint key remap partial generic

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about key remapping

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoE8AOECMyDeAsAFDJnJwBcyAzmFKAOYA0J5yARtXQyIyQF8SYLCgzYATMgC8BNuQDaAaWShkAawjoA9jDSi8cGsgAGADwsB9ACT4eTZADJkSgSYC63ek0HDR+7ABmGWQABTgoMGA4ABsAHnEICQA+AG4SEhgAVxAEKO0QZEg6BOQIM0gQABNjRMDkgAoAN1isiGpUAEoCZCFiYQg6BqJScgszSypkAHIAQXnp1lGyAHoVgJRzE2QAC2gIZjKzbDyi7V24JpQEbSqUHdAwQ8QwLNiY9GQQbTAAOkFOkA)

### 💻 Code

```ts
interface Type1 {
    a: string,
    b: string
}
type Type2 = {
    [K in keyof Type1 as `xxx_${string & K}`]: string
}
type Type3 = Partial<Type2>;

function test<T extends Type3>(value: T) { }

test({
    xxx_a: 'AAA',
    // Type `x` here, expect to have code hint, actually not.
})
```

### 🙁 Actual behavior

The code hint can only works on the first field, but not works on the rests.

![image](https://user-images.githubusercontent.com/1681689/140599053-4d2ba747-7609-4291-a3e5-f5e980284a68.png)

### 🙂 Expected behavior
![image](https://user-images.githubusercontent.com/1681689/140599055-858e578c-1ee4-43e3-823b-c425c1f5bb65.png)

**Comment by missannil** [comment] 2021-11-06 05:30
我先留着记号

**Comment by missannil** [comment] 2021-11-06 05:30
I have the same problem

**Comment by andrewbranch** [comment] 2021-11-10 20:03
Duplicate of #46605, just fixed yesterday, will be in nightlies tomorrow

**Closed** 2021-11-10 20:03 UTC
Labels: Duplicate
