### ISSUE TITLE
Lodash's mapValues and empty object type interact confusingly

### ISSUE THREAD

**Issue by seansfkelley** [Microsoft/TypeScript#29901] opened 2019-02-13 18:22 UTC
I had trouble coming up with a good name and search terms for this issue. It looks like it's triggering some heuristic that is misbehaving and is very strange. Please feel free to rename if you can come up with a better summary for it.

**TypeScript Version:**  3.3.1

**Search Terms:** mapvalues ternary side effect unused inference empty object type

**Code**

```ts
// Begin types from Lodash.
interface Dictionary<T> {
  [index: string]: T;
}

interface NumericDictionary<T> {
  [index: number]: T;
}

type ObjectIterator<TObject, TResult> = (value: TObject[keyof TObject], key: string, collection: TObject) => TResult;

type DictionaryIterator<T, TResult> = ObjectIterator<Dictionary<T>, TResult>;

// In lodash.d.ts this function has many overloads, but this seems to be the problematic one.
function mapValues<T, TResult>(obj: Dictionary<T> | NumericDictionary<T> | null | undefined, callback: DictionaryIterator<T, TResult>): Dictionary<TResult> {
  return null as any;
} 
// End types from Lodash.

interface Foo {
    foo: string;
} 

interface Bar {
    bar: string;
}

export function fooToBar(
  foos: Record<string, Foo>,
): Record<string, Bar | null> {
  // The next line, despite being unrelated to the other two lines, causes them to fail.
  // Comment it out to see the function compile erroneously.
  //
  // This behavior only happens when `result` is used as an intermediate: if you return 
  // the ternary directly, the function always compiles.
  //
  // I couldn't find another Lodash function for which this issue reproduced after sampling
  // a few. 
  const wat = mapValues(foos, f => f.foo);
  const result = foos == null ? {} : mapValues(foos, f => f.foo);
  // This line _should_ fail, because `result` is not the right type.
  return result;
}
```

**Expected behavior:** fails to compile without the `const wat` line present.

**Actual behavior:** only fails to compile when `const wat` is present.

**Playground Link:** [link](https://www.typescriptlang.org/play/index.html#src=%2F%2F%20Begin%20types%20from%20Lodash.%0D%0Ainterface%20Dictionary%3CT%3E%20%7B%0D%0A%20%20%5Bindex%3A%20string%5D%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20NumericDictionary%3CT%3E%20%7B%0D%0A%20%20%5Bindex%3A%20number%5D%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Atype%20ObjectIterator%3CTObject%2C%20TResult%3E%20%3D%20(value%3A%20TObject%5Bkeyof%20TObject%5D%2C%20key%3A%20string%2C%20collection%3A%20TObject)%20%3D%3E%20TResult%3B%0D%0A%0D%0Atype%20DictionaryIterator%3CT%2C%20TResult%3E%20%3D%20ObjectIterator%3CDictionary%3CT%3E%2C%20TResult%3E%3B%0D%0A%0D%0A%2F%2F%20In%20lodash.d.ts%20this%20function%20has%20many%20overloads%2C%20but%20this%20seems%20to%20be%20the%20problematic%20one.%0D%0Afunction%20mapValues%3CT%2C%20TResult%3E(obj%3A%20Dictionary%3CT%3E%20%7C%20NumericDictionary%3CT%3E%20%7C%20null%20%7C%20undefined%2C%20callback%3A%20DictionaryIterator%3CT%2C%20TResult%3E)%3A%20Dictionary%3CTResult%3E%20%7B%0D%0A%20%20return%20null%20as%20any%3B%0D%0A%7D%20%0D%0A%2F%2F%20End%20types%20from%20Lodash.%0D%0A%0D%0Ainterface%20Foo%20%7B%0D%0A%20%20%20%20foo%3A%20string%3B%0D%0A%7D%20%0D%0A%0D%0Ainterface%20Bar%20%7B%0D%0A%20%20%20%20bar%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aexport%20function%20fooToBar(%0D%0A%20%20foos%3A%20Record%3Cstring%2C%20Foo%3E%2C%0D%0A)%3A%20Record%3Cstring%2C%20Bar%20%7C%20null%3E%20%7B%0D%0A%20%20%2F%2F%20The%20next%20line%2C%20despite%20being%20unrelated%20to%20the%20other%20two%20lines%2C%20causes%20them%20to%20fail.%0D%0A%20%20%2F%2F%20Comment%20it%20out%20to%20see%20the%20function%20compile%20erroneously.%0D%0A%20%20%2F%2F%0D%0A%20%20%2F%2F%20This%20behavior%20only%20happens%20when%20%60result%60%20is%20used%20as%20an%20intermediate%3A%20if%20you%20return%20%0D%0A%20%20%2F%2F%20the%20ternary%20directly%2C%20the%20function%20always%20compiles.%0D%0A%20%20%2F%2F%0D%0A%20%20%2F%2F%20I%20couldn't%20find%20another%20Lodash%20function%20for%20which%20this%20issue%20reproduced%20after%20sampling%0D%0A%20%20%2F%2F%20a%20few.%20%0D%0A%20%20const%20wat%20%3D%20mapValues(foos%2C%20f%20%3D%3E%20f.foo)%3B%0D%0A%20%20const%20result%20%3D%20foos%20%3D%3D%20null%20%3F%20%7B%7D%20%3A%20mapValues(foos%2C%20f%20%3D%3E%20f.foo)%3B%0D%0A%20%20%2F%2F%20This%20line%20_should_%20fail%2C%20because%20%60result%60%20is%20not%20the%20right%20type.%0D%0A%20%20return%20result%3B%0D%0A%7D)

**Related Issues:**

**Comment by jack-williams** [comment] 2019-02-13 18:26
I think this might caused by the same issue in #29393.

**Comment by seansfkelley** [comment] 2019-02-13 18:29
@jack-williams that seems likely, but I'll keep the issue open and leave it up to the maintainers to judge if that is the case.

**Comment by weswigham** [comment] 2019-02-19 18:46
Oh boy. So this strangeness really is strange. All that differs from the `wat` line existing and not is _the type ids we assign to the object type and the Dictionary<string> instantiation_. With `wat`, `Dictionary<string>` gets a lower type id, which makes the `result` union `Dictionary<string> | {}`, which when subtype reduces (correctly) to `{}`. When the `wat` line is gone, the ordering of the assigned type ids inverts, making the union we make `{} | Dictionary<string>`, which we then seem to say that subtype reduces to `Dictionary<string>` (which is clearly incorrect, `{}` should not be considered a subtype of a `Dictionary<anything>`, since a `Dictionary` has an index signature).

**Comment by jack-williams** [comment] 2019-02-19 19:00
Ahh the type ids. An amateur mistake by me there to overlook that one, haha.

**Comment by weswigham** [comment] 2019-02-19 19:05
It's probably also worth noting that I believe by our normal subtype reduction rules, `result`'s type should always simplify to type `{}`, which _is_ assignable to the return type, despite not having an index signature, and despite having something with potentially incompatible member types assigned to it - which is a manifestation of the aliasing problem we show elsewhere. :(

**Comment by seansfkelley** [comment] 2019-02-19 19:45
Hah, what a bug. Thanks for the explanation @weswigham!

**Closed** 2019-02-26 21:43 UTC
Labels: Needs Investigation
