### ISSUE TITLE
Support also css files for use with import attributes

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/TypeScript#56507] opened 2023-11-22 13:01 UTC
### 🔎 Search Terms

import, css

### 🕗 Version & Regression Information

- This is errors

### 💻 Code

```ts
import wunderbaumStyle from 'wunderbaum/dist/wunderbaum.css' with { type: 'css' };
```

### 🙁 Actual behavior

reports an error cause of not finding the css file

### 🙂 Expected behavior

should find the css file

### Additional information about the issue

https://github.com/whatwg/html/pull/4898/

**Comment by jakebailey** [comment] 2023-11-22 16:52
Duplicate of https://github.com/microsoft/TypeScript/issues/46135

**Comment by jogibear9988** [comment] 2023-11-22 21:40
don't know if it is exactly the same. The other issue is about the type of the import, mine especially that the import errors with file not found if it is a css file

**Comment by jakebailey** [comment] 2023-11-22 21:42
We treat that import as an import of JS code, so it's going to fail without an ambient declaration or a `path/to/style.d.css.ts` file next to `path/to/style.css`.

**Comment by jogibear9988** [comment] 2023-11-23 05:55
So is this planed to be fixed, or need there be a .d.css.ts  file for each stylesheet?

**Comment by jakebailey** [comment] 2023-11-23 06:22
See the other thread, which is about supporting methods to allow resolution with an import attribute of type css.

**Closed** 2023-11-26 01:30 UTC
Labels: Duplicate
