### ISSUE TITLE
Type constraint for function arguments

### ISSUE THREAD

**Issue by aj-r** [Microsoft/TypeScript#20294] opened 2017-11-28 03:47 UTC
There are many times (especially in [lodash](https://lodash.com/docs/4.17.4)) when a function accepts another function as an argument, and returns a similar function with the same arguments but a different return type. Some big examples are `_.flow` and `_.flowRight`, but there are others. To properly implement these type definitions, it would be nice to have a generic type argument that constrained the types of all arguments of the inner function.

## Proposal Syntax

```ts
flow<TArgs extends any[], R1, R2>(f1: (args: ...TArgs) => R1, f2: (arg: R1) => R2)
    : (args: ...TArgs) => R2;
```

Basically, what's happening here is that `flow` returns a function that accepts the same input arguments as `f1`, but the same return value as `f2`.

## Current Workaround

Right now, `(args: ...TArgs) => R1` doesn't work, so we have to make a separate overload for each possible number of arguments of `f1`:

```ts
flow<R1, R2>(f1: () => R1, f2: (a: R1) => R2): () => R2;
flow<A1, R1, R2>(f1: (a1: A1) => R1, f2: (a: R1) => R2): (a1: A1) => R2;
flow<A1, A2, R1, R2>(f1: (a1: A1, a2: A2) => R1, f2: (a: R1) => R2): (a1: A1, a2: A2) => R2;
flow<A1, A2, A3, R1, R2>(f1: (a1: A1, a2: A2, a3: A3) => R1, f2: (a: R1) => R2): (a1: A1, a2: A2, a3: A3) => R2;
flow<A1, A2, A3, A4, R1, R2>(f1: (a1: A1, a2: A2, a3: A3, a4: A4) => R1, f2: (a: R1) => R2): (a1: A1, a2: A2, a3: A3, a4: A4) => R2;
flow<A1, A2, A3, A4, R1, R2>(f1: (a1: A1, a2: A2, a3: A3, a4: A4, ...args: any[]) => R1, f2: (a: R1) => R2): (a1: A1, a2: A2, a3: A3, a4: A4, ...args: any[]) => R2;
```

As you can see, we only properly support up to 4 arguments. If `f1` has more than 4 arguments, we just use `...any[]` as a catch-all. This works, but has much looser types than we would like. Oh, and flow can accept any number of input functions (`f3`, `f4`, `f5`, as many as you want), which means that we need a ridiculous number of overloads just to make this function work. And this doesn't even cover the case where `f1` has a rest parameter (see DefinitelyTyped/DefinitelyTyped#21533), so we'll need to almost double the number of overloads (79 instead of 43) in order to fix that. And this is just for `flow` - there are other lodash functions that have this same issue.

## Caveats

The biggest caveat I see is that, in order to support rest parameters, we need to implement rest types first (#10727). For example, if I do this:

```ts
function test(arg1: number, arg2: string, ...args: boolean[]): string {
    // do something...
}
const escapeTest = _.flow(test, _.escape);
```

then `TArgs` needs to have type `[number, string, ...boolean[]]`. Then `escapeTest` would have type `(arg1: number, arg2: string, ...args: boolean[]) => string`.

**Comment by mhegazy** [comment] 2017-11-28 08:19
Duplicate of https://github.com/Microsoft/TypeScript/issues/5453?

**Closed** 2018-01-02 18:42 UTC
Labels: Duplicate
