### ISSUE TITLE
Enum-based constants can be used as computed property names more than once 

### ISSUE THREAD

**Issue by karol-majewski** [microsoft/TypeScript#41326] opened 2020-10-29 13:32 UTC
**TypeScript Version:**  4.0.3

**Search Terms:** enum, 2300, computed property name, duplicate identifier, duplicates, twice

**Expected behavior:**

Compile-time error. It shouldn't matter if the constant is provided inline or pulled from an enum — a duplicate is still a duplicate. Enum values are known in compile-time, so it's possible to reject duplicate values.

**Actual behavior:**

The `Duplicate identifier '80'.ts(2300)` error is suppressed when enums are used.

**Related Issues:**

#6864 looks similar, but that one is concerned with values within the enum that defines them. I'm talking about using enum values inside an object literal.

**Code**
```ts
enum Port {
  HTTP = 80
}

const good = {
  80: '😇',
  80: '😇', // Error, as expected: Duplicate identifier '80'.ts(2300)
}

const alsoGood = {
  [80]: '😇',
  [80]: '😇', // Error, as expected: Duplicate identifier '80'.ts(2300)
};

const bad = {
  [Port.HTTP]: '😩',
  [Port.HTTP]: '😩' // No error
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
var Port;
(function (Port) {
    Port[Port["HTTP"] = 80] = "HTTP";
})(Port || (Port = {}));
const good = {
    80: '😇',
    80: '😇',
};
const alsoGood = {
    [80]: '😇',
    [80]: '😇',
};
const bad = {
    [Port.HTTP]: '😩',
    [Port.HTTP]: '😩' // No error
};

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/KYOwrgtgBACg9gJwC5QN4CgpQBIBVcxQC8UAHAAzoC+66AxnCAM4oDmccAJsWpmeQC4oAckC8G4HA94QBo+FIWMlSoAemVQAoggSIlAQyZRgADwAOwOkmCchAETAmANgEs6uy1CedQSJwDMnwAgiFMIAdEhMABQATADM5OQAlNS0DMwoug5McADiHNwkGFgA2hQAuvIS0nyl5BUiVUqqGlo6UPqGpuaW1lB2ji5uwB5eID7+gcHkYREx8UnUANypjCxQAEa6Bbwl8MiheAT1YoCUe9W7iEgH+DDHomcqagBycIatCNRAA)
      

This made me waste a fair amount of time debugging. The bug was caused by one enum value overriding the other like this:

```ts
enum TextData {
  CSV,
}

enum BinaryData {
  MPM,
  STL
}

const documents = {
  [TextData.CSV]: false,
  [BinaryData.MPM]: true,
  [BinaryData.STL]: false,
}

if (documents[TextData.CSV]) {
  console.log('Oups! I didn’t expect this to be executed')
}
```

**Comment by IllusionMH** [comment] 2020-10-29 18:01
Duplicate of #25758 and not specific to enums.

**Closed** 2020-10-29 20:44 UTC
