### ISSUE TITLE
union types narrowed incorrectly by assertion functions and type predicate functions

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#43825] opened 2021-04-26 13:10 UTC
# Bug Report

### 🔎 Search Terms
union types narrowed incorrectly

### 🕗 Version & Regression Information
v4.3.0-dev.20210426
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210426#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXygGdCQYMAeAFQD4AKANygmRAC4DUBPASnaJLKF4jZgixDKAWABQM0JFgIweQhiQ4c7VMgC2AI1LwAPvFUwsqAOYyZ-UhQCMx0xnNW6iDdxvTlqVfB6sPAAvOo48AD0kWYWlkA)

### 💻 Code

```ts
declare function assert<T>(value: any): asserts value is T

declare const foo: number | string | boolean

assert<1 | string>(foo)

const bar = foo //string
```

### 🙁 Actual behavior
`foo` is narrowed to `string`

### 🙂 Expected behavior
`foo` should be narrowed to `1 | string`

**Comment by Ethan-Xd** [comment] 2021-04-26 13:11
![allan](https://user-images.githubusercontent.com/24442053/116087971-7da38980-a6f5-11eb-85cc-fd76a8201e07.png)

**Comment by jcalz** [comment] 2021-04-26 13:48
Duplicate of #31156?

**Comment by whzx5byb** [comment] 2021-04-26 13:56
See `Issues with narrowing unions by union types` in https://github.com/microsoft/TypeScript/issues/32158. I think it's a design limitation?

**Closed** 2021-04-26 14:26 UTC
