### ISSUE TITLE
Make type assumptions when using Boolean function

### ISSUE THREAD

**Issue by ostrebler** [microsoft/TypeScript#42572] opened 2021-02-01 02:02 UTC
# Suggestion

Right now, only the last instruction fails in TS with the error `Object is possibly 'null'` :

```typescript
declare const value: null | { x: number };

const foo = value && value.x;
const bar = !!value && value.x;
const baz = Boolean(value) && value.x;
```

[Playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gNyhAriAFzwr4QTwA+8A3vAB4lkC2ARiDPAL4DcAUP2TosAMyRJ4AXhx5C8AGQLZBEADoGA4ZnhtY0+AEJDuVYuWnCGrah16AXgYBCEiCCgoAFJZABKcypWmkA)

Since it's strictly equivalent to the instruction just above, I suggest making the same type assumptions.

## 🔍 Search Terms

Boolean, function, inference, assumption, assertion

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2021-02-01 02:22
Duplicate of #16655.

**Closed** 2021-02-01 02:29 UTC
