### ISSUE TITLE
Spread Types

### ISSUE THREAD

**Issue by pleerock** [Microsoft/TypeScript#24490] opened 2018-05-30 16:21 UTC
I working on a small dependency injection tool, that looks like what angular 1 had years ago if you used and remember that. And I want to make everything type-safe and infer all dependencies automatically. Code example:

```ts
export const PostController = service([PostRepository, PostManager], (repository, manager) => {
    console.log("yai it compiles fine", repository.load());
    console.log("yai it compiles fine", manager.save());
    return {
        id: "hello",
        name: "world"
    };
});
```

To make it to work I have a following signature:

```ts

export type ObjectType<T1> = { new (...args: any[]): T1 };

function service<R, T1>(
    dependencies: [ObjectType<T1>],
    factory: (dependency1: T1) => R
): R;
function service<R, T1, T2>(
    dependencies: [ObjectType<T1>, ObjectType<T2>],
    factory: (dependency1: T1, dependency2: T2) => R
): R;
function service<R, T1, T2, T3>(
    dependencies: [ObjectType<T1>, ObjectType<T2>, ObjectType<T3>],
    factory: (dependency1: T1, dependency2: T2, dependency3: T3) => R
): R;
function service<R, T1, T2, T3, T4>(
    dependencies: [ObjectType<T1>, ObjectType<T2>, ObjectType<T3>, ObjectType<T4>],
    factory: (dependency1: T1, dependency2: T2, dependency3: T3, dependency4: T4) => R
): R;
function service<R, T1, T2, T3, T4, T5>(
    dependencies: [ObjectType<T1>, ObjectType<T2>, ObjectType<T3>, ObjectType<T4>, ObjectType<T5>],
    factory: (dependency1: T1, dependency2: T2, dependency3: T3, dependency4: T4, dependency5: T5) => R
): R;
function service<R, T1, T2, T3, T4, T5, T6>(
    dependencies: [ObjectType<T1>, ObjectType<T2>, ObjectType<T3>, ObjectType<T4>, ObjectType<T5>, ObjectType<T6>],
    factory: (dependency1: T1, dependency2: T2, dependency3: T3, dependency4: T4, dependency5: T5, dependency6: T6) => R
): R;
function service<R, T1, T2, T3, T4, T5, T6, T7>(
    dependencies: [ObjectType<T1>, ObjectType<T2>, ObjectType<T3>, ObjectType<T4>, ObjectType<T5>, ObjectType<T6>, ObjectType<T7>],
    factory: (dependency1: T1, dependency2: T2, dependency3: T3, dependency4: T4, dependency5: T5, dependency6: T6, dependency7: T7) => R
): R;
function service<R, T1, T2, T3, T4, T5, T6, T7, T8>(
    dependencies: [ObjectType<T1>, ObjectType<T2>, ObjectType<T3>, ObjectType<T4>, ObjectType<T5>, ObjectType<T6>, ObjectType<T7>, ObjectType<T8>],
    factory: (dependency1: T1, dependency2: T2, dependency3: T3, dependency4: T4, dependency5: T5, dependency6: T6, dependency7: T7, dependency8: T8) => R
): R;
function service<R, T1, T2, T3, T4, T5, T6, T7, T8, T9>(
    dependencies: [ObjectType<T1>, ObjectType<T2>, ObjectType<T3>, ObjectType<T4>, ObjectType<T5>, ObjectType<T6>, ObjectType<T7>, ObjectType<T8>, ObjectType<T9>],
    factory: (dependency1: T1, dependency2: T2, dependency3: T3, dependency4: T4, dependency5: T5, dependency6: T6, dependency7: T7, dependency8: T8, dependency9: T9) => R
): R;
function service<R, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(
    dependencies: [ObjectType<T1>, ObjectType<T2>, ObjectType<T3>, ObjectType<T4>, ObjectType<T5>, ObjectType<T6>, ObjectType<T7>, ObjectType<T8>, ObjectType<T9>, ObjectType<T10>],
    factory: (dependency1: T1, dependency2: T2, dependency3: T3, dependency4: T4, dependency5: T5, dependency6: T6, dependency7: T7, dependency8: T8, dependency9: T9, dependency10: T10) => R
): R;
function service(dependencies: Function[], factory: (...args: any[]) => any) {

}
```

As you can see I got it working, however I would like to support more dependencies without having to create more overloads, e.g. more scalable solution, something crazy like:

```ts
function service<R, T[]>(
    dependencies: ObjectTypizeEach<T>,
    factory: (...dependencies: T[]) => R
): R;
```

Im already quite satisfied that I was be able to do what I want (great job, as usual), so I'm just dropping another thought and use-case to your bucket.

**Comment by sandersn** [comment] 2018-05-30 16:31
Duplicate of #5453

**Closed by sandersn** 2018-05-30 16:31 UTC
