### ISSUE TITLE
Compiler thinks array.push() doesn't change length

### ISSUE THREAD

**Issue by peterkelly** [microsoft/TypeScript#36975] opened 2020-02-24 12:00 UTC
In the code below, the compiler sees the comparison of `array.length` against 0 and the return statement, and then assumes that comparison remains true even after the array is mutated, presumably based on the logic that "if we get past the return statement this means that array.length is 0 (forever)".

When we modify the array (e.g. by appending items to it, or calling some other mutating functions like `pop` or `splice`), the compiler still thinks the length is 0 and generates an error when the code tries to compare the length with anything else.

The output of the program at runtime is what you would expect:

```
Contains one element
[ 'test' ]
```

**TypeScript Version:**  3.8.2

Search terms: array, array.push(), array.pop(), array.splice(), array.length, properties mutation, property narrowing, array mutation, TS2367

**Code**

```ts
function test(array: string[]): void {
    if (array.length !== 0)
        return;
    array.push("test");
    if (array.length === 1) {
        console.log("Contains one element");
    }
}

function main(): void {
    const values: string[] = [];
    test(values);
    console.log(values);
}

main();
```

**Expected behavior:**

No compile errors.

**Actual behavior:**

Compile error:

sample.ts(5,9): error TS2367: This condition will always return 'false' since the types '0' and '1' have no overlap.

**Another example**

More generally, it appears that the control flow analysis is not aware of the fact that method calls can modify the object on which they are called.

```ts
class Counter {
    public value: number = 0;
    public increment(): void {
        this.value++;
    }
}

function inc(c: Counter): void {
    if (c.value !== 3) {
    }
    else {
        c.increment();
        if (c.value === 4) {
        }
    }
}
```

**Expected behavior:**

No compile errors. The compiler should recognise that a method which it does not know to be pure is being called on the object, and invalidate any assumptions it holds about the value of the object's properties.

**Actual behavior:**

sample.ts:13:13 - error TS2367: This condition will always return 'false' since the types '3' and '4' have no overlap.

**Playground Link:**

https://www.typescriptlang.org/play/?ts=3.8-Beta#code/GYVwdgxgLglg9mABFApgZygCgIYCdfYCeAXIhrjGAOYDaAugJSkBucMAJogN4BQi-iGMEQ58RAHQAbFNSgALRAEIAvMsQAGBnwE7cKKCFxgA3Nv54ChcQAcQaOZgBEqDI4amdQkRYnTZC1TUARi0dHQgENDhpKTgqJwBhBChsSjREBBREFGkAWxkoN1MAXx4eCLAMRGZsSRB0UnJKWjpENXpTFywauvR3csjolFj4nvq0fqA

**Related Issues:**

None

**Comment by IllusionMH** [comment] 2020-02-24 13:02
Exact duplicate of #35795 for details see #9998

**Closed** 2020-02-26 18:00 UTC
Labels: Duplicate
