### ISSUE TITLE
Generic Constraints working incorrectly

### ISSUE THREAD

**Issue by foisonocean** [Microsoft/TypeScript#29000] opened 2018-12-13 09:52 UTC
**TypeScript Version:**  3.2.2

**Code**

```ts
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

interface IName {
  name: string;
}

const callWithName =
  <T extends IName, R>(fn: (origianlArgs: T) => R, name: string) =>
    (arg: Omit<T, 'name'>) =>
      fn({
        ...arg,
        name,
      });

const greeting = (arg: { name: string }) => {
  console.log(`Hello ${arg.name}`);
}

const greetingToTom = callWithName(greeting, 'Tom');

greetingToTom({});
```

**Expected behavior:**
shouldn't have any type error

**Actual behavior:**
has a error:

```
Argument of type '{ name: string; }' is not assignable to parameter of type 'T'.
```

**Playground Link:** 

https://www.typescriptlang.org/play/index.html#src=type%20Omit%3CT%2C%20K%20extends%20keyof%20T%3E%20%3D%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%3B%0A%0Ainterface%20IName%20%7B%0A%20%20name%3A%20string%3B%0A%7D%0A%0Aconst%20callWithName%20%3D%0A%20%20%3CT%20extends%20IName%2C%20R%3E(fn%3A%20(origianlArgs%3A%20T)%20%3D%3E%20R%2C%20name%3A%20string)%20%3D%3E%0A%20%20%20%20(arg%3A%20Omit%3CT%2C%20'name'%3E)%20%3D%3E%0A%20%20%20%20%20%20fn(%7B%0A%20%20%20%20%20%20%20%20...arg%2C%0A%20%20%20%20%20%20%20%20name%2C%0A%20%20%20%20%20%20%7D)%3B%0A%0Aconst%20greeting%20%3D%20(arg%3A%20%7B%20name%3A%20string%20%7D)%20%3D%3E%20%7B%0A%20%20console.log(%60Hello%20%24%7Barg.name%7D%60)%3B%0A%7D%0A%0Aconst%20greetingToTom%20%3D%20callWithName(greeting%2C%20'Tom')%3B%0A%0AgreetingToTom(%7B%7D)%3B

**Related Issues:**

**Comment by jack-williams** [comment] 2018-12-13 10:05
Here is an example why the error is correct.
```ts
interface MyInterface {
  a: number;
  b: string;
}

type Foo = <T extends MyInterface>() => T
const foo: Foo = () => ({ a: 123, b: 'hello' });
const c: number = foo<MyInterface & { c: number }>().c /// no error, but no c!
```

Parametric type variables that _only_ appear in the return type position of a function are usually wrong because they are saying you can conjure something specific out of nothing.

Maybe you want an alias?
```ts
interface MyInterface {
  a: number;
  b: string;
}

type Foo<T extends MyInterface> = () => T
const foo: Foo<MyInterface> = () => ({ a: 123, b: 'hello' });
const c: number = foo().c // error.
```

**Comment by foisonocean** [comment] 2018-12-13 10:53
@jack-williams 

Sorry my fault, I just write a bad example here.

Actually my real world use case is React HOC, but considering there are some people doesn't have a React background, I'll write a high order function with vanilla typescript:

```ts
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

interface IName {
  name: string;
}

const callWithName =
  <T extends IName, R>(fn: (origianlArgs: T) => R, name: string) =>
    (arg: Omit<T, 'name'>) =>
      fn({
        ...arg,
        name,
      });

const greeting = (arg: { name: string }) => {
  console.log(`Hello ${arg.name}`);
}

const greetingToTom = callWithName(greeting, 'Tom');

greetingToTom({});
```

**Comment by foisonocean** [comment] 2018-12-13 11:31
@jack-williams Thanks. And I found a issue here which is similar: https://github.com/Microsoft/TypeScript/issues/28748

So maybe my issue is duplicated?

**Comment by jack-williams** [comment] 2018-12-13 11:51
Possibly; this issue also looks similar #28821. I don't know enough to say if this is a duplicate so I would wait for someone more knowledgeable to drop by.

**Comment by DanielRosenwasser** [comment] 2018-12-13 18:45
Potentially a dupe; I'll let @ahejlsberg decide.

**Comment by sveyret** [comment] 2018-12-15 08:18
Also similar to #28884.

**Comment by ahejlsberg** [comment] 2018-12-17 19:47
Duplicate of #28884.

**Closed** 2018-12-20 18:00 UTC
Labels: Duplicate
