### ISSUE TITLE
TS Server error after deleting jsconfig.json

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#30005] opened 2019-02-20 22:14 UTC
From https://github.com/Microsoft/vscode/issues/68428

**TypeScript Version:**  3.4.0-dev.20190220

**Search Terms:**
- projectLoadingStart
- projectLoadingFinish
 
**Code**
Follow instructions in https://github.com/Microsoft/vscode/issues/68428

**Bug**
After deleting the jsconfig, see this error in the server logs:

```
Info 433  [14:12:22.825] request:
    {"seq":26,"type":"request","command":"reloadProjects","arguments":null}
Info 434  [14:12:22.826] reload projects.
Info 435  [14:12:22.826] Search path: /Users/matb/projects/san
Info 436  [14:12:22.826] For info: /Users/matb/projects/san/index.js :: Config file name: /Users/matb/projects/san/jsconfig.json
Info 437  [14:12:22.826] Reloading configured project /Users/matb/projects/san/jsconfig.json
Info 438  [14:12:22.826] event:
    {"seq":0,"type":"event","event":"projectLoadingStart","body":{"projectName":"/Users/matb/projects/san/jsconfig.json","reason":"User requested reload projects"}}
Err 439   [14:12:22.827] Exception on executing command {"seq":26,"type":"request","command":"reloadProjects","arguments":null}:

    Cannot read property 'length' of undefined

    TypeError: Cannot read property 'length' of undefined
        at createSourceFile (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:17172:110)
        at Object.parseJsonText (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:17006:26)
        at Object.parseJsonText (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16828:23)
        at ProjectService.loadConfiguredProject (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:124433:33)
        at ProjectService.reloadConfiguredProject (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:124536:22)
        at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:124992:39
        at Map.forEach (<anonymous>)
        at ProjectService.reloadConfiguredProjectForFiles (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:124976:27)
        at ProjectService.reloadProjects (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:124964:22)
        at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:126124:46)
        at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:127490:88
        at IOSession.Session.executeWithRequestId (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:127481:28)
        at IOSession.Session.executeCommand (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:127490:33)
        at IOSession.Session.onMessage (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:127512:35)
        at Interface.<anonymous> (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:128773:27)
        at Interface.emit (events.js:182:13)
        at Interface._onLine (readline.js:290:10)
        at Interface._normalWrite (readline.js:433:12)
        at Socket.ondata (readline.js:149:10)
        at Socket.emit (events.js:182:13)
        at addChunk (_stream_readable.js:279:12)
        at readableAddChunk (_stream_readable.js:264:11)
        at Socket.Readable.push (_stream_readable.js:219:10)
        at Pipe.onread (net.js:636:20)
```

Here's the full logs: [tsserver.log.zip](https://github.com/Microsoft/TypeScript/files/2886699/tsserver.log.zip)

(note for these logs I had to create and delete the jsconfig twice. The second delete triggered the error)

**Comment by mjbvz** [comment] 2019-02-20 22:26
@sheetalkamat VS Code sends `reloadProject` requests when we detect the creation or deletion of `jsconfig` files. Are these still needed for files on disk, or will the watcher handle ts/jsconfig file changes properly?

**Comment by sheetalkamat** [comment] 2019-02-20 23:19
we already watch jsconfig files for all the open files so reload project should be unnecessary

**Comment by mjbvz** [comment] 2019-02-21 00:43
Thanks. I'm going to remove the reloadProject calls then. Once those are removed, I don't think we will hit this error anymore but I'll double check

**Comment by mjbvz** [comment] 2019-02-21 01:30
Ok, I confirmed that after removing the `reloadProjects` call, we don't see this error anymore. Up to you if this crash still needs to be fixed or not

**Comment by minestarks** [comment] 2019-12-17 18:51
This still impacts the `configure` and `applyChangedToOpenFiles` commands in VS on a regular basis: https://devdiv.visualstudio.com/DevDiv/_queries/edit/1034761/?triage=true https://devdiv.visualstudio.com/DevDiv/_queries/edit/1034750/?triage=true

**Comment by minestarks** [comment] 2020-04-17 20:54
@sheetalkamat @RyanCavanaugh @mjbvz  is this not a dupe of #36862?

**Comment by sheetalkamat** [comment] 2020-05-06 17:31
@minestarks Thank you this is dulpicate of #36862

**Closed by sheetalkamat** 2020-05-06 17:31 UTC
Labels: Bug, VS Code Priority, help wanted
