### ISSUE TITLE
Distinguish missing and undefined

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#16524] opened 2017-06-14 17:16 UTC
Typescript should distinguish `missing` and `undefined` at the type level in order to distinguish the following two statements:

```ts
// @strictNullChecks: true
type A = { x?: string }
let x: A = {}
let y: A = { x: undefined } // should not be allowed, but currently is
```

**Comment by dgoldstein0** [comment] 2017-06-14 21:31
I believe this is a dupe of #13195

**Comment by mhegazy** [comment] 2017-06-14 22:14
you are right. closing.

**Closed by mhegazy** 2017-06-14 22:14 UTC
Labels: In Discussion, Suggestion
