### ISSUE TITLE
Function overloads as intersection of function types

### ISSUE THREAD

**Issue by tobiasdiez** [microsoft/TypeScript#47626] opened 2022-01-26 20:02 UTC
# Bug Report

### 🔎 Search Terms

overloaded functions

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about overloaded functions

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYgrgOwMbAIxQLxQBQEMBcUCcAtgEYQBOAlJgHxGkWUCwAUKJLIigEyY4CUAM7BKASwQBzWhgaiJ09p2jxkwAWpToAZN3W92AeiNQzUAHoB+dsdMAVABbjhUJAHsSYADa5JrgHdxYEcoACIFSSkoAB9GciooFyJ3DVxhYXEpBFwyb2hgd3jmMPYPBFEoADMUQi0NLDxZBgBvdnMkqpwVdy7cTAwsCLEosOp2jvNKCGA4SgRwgAZStg6Ib2EICcmoadn5qEX2AF9bNhMoAFEARzhxADdcfIQNOEzpKHdKABNJXEoQNUeMBxO4Fu57lRvO5cN9hOwqsDQQsAl8ANbCPCEYgJGjYphUBFIsFQVGUDFYkQjaTUQiRJRsRHqZGk9GYoT0qQxHHMWlUxRcnmJNqrcziLrYHp9AZDTljbaTPZzBZhZYK9abBUdJUHI5sU4ccDQADqbIEUtZ5Ph51M5msZzssD8G1JwVCwlwJGgVEoXwANFAniF3HApKFggByVwhaAer1A5kk4RFYSOEPeb5QRy4SFQGMiT0FI0BiRh4A2NjlSo1YC8Qimq0CJr0KAijri7pG3qBmXhOXjUU7HUqtWDqAarZj7UzZWHE5nC4AGRmeaNwiQEjAGkkwCoVUS+ZUZTB1ZQABYmxzqYKCTQW22xRKLf1BrLr-Kp1MZwdVSs1htJx2MxhznfUEXPR17RtKAAEENiKb53AgYQEAjDRymAPwFlwBBAUkKovhIXAQRJEJiOKKhXH+aAiLASBM0KCjKGEAMcMzTloxTa9rSAA)

### 💻 Code

What I try to achieve is to model functions overloads with types (because in my use case the possible overloads are dynamically inferred).
So the following works of course:
```ts
function works(a: number): number
function works(a: string): string
function works(a: string|number): string|number {
   if (typeof a === "string")
        return "0"
    else
        return 0
}
```
The same using intersection of the function overloads, however, doesn't work:
```ts
type Funct1 = (a: number) => number
type Funct2 = (a: string) => string
type Funct = Funct1 & Funct2

// This complains with "string | number is not assignable to number"
const fct: Funct = (a) => {
    if (typeof a === "string")
        return "0"
    else
        return 0
}
```

Moreover, one cannot even use the working function declaration as a blueprint:
```ts
type Works = typeof works // The function works as defined above with the overloads

// Fails with same error, although it's the same function so should have the same type, right?
const fct2: Works = (a) => {
    if (typeof a === "string")
        return "0"
    else
        return 0
}
```

Finally, let typescript figure out the type on its own:
```ts
// Let typescript interfer the type
const fct4 = (a: string|number) => {
    if (typeof a === "string")
        return "0"
    else
        return 0
}
fct4
// ^?: (a: string | number) => "0" | 0
```
So this doesn't contain any information that numbers are mapped to numbers, and strings to strings

### 🙁 Actual behavior

Intersection of function types behaves differently to function overloads.

### 🙂 Expected behavior

Allow one to specify overloads of functions using intersection of function types.

**Comment by MartinJohns** [comment] 2022-01-26 21:25
Duplicate of #38622. Used search terms: `arrow overload in:title`

**Closed** 2022-01-29 18:00 UTC
Labels: Duplicate

**Comment by DiamondG3m** [comment] 2022-01-29 18:05
J38s 2u
