### ISSUE TITLE
Object literal known props doesn't respect with unions

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#25905] opened 2018-07-24 21:17 UTC
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**

**Code**

I think this is design limitation, but I try :)

```ts
function foo(a: { a: number } | { b: number }) {}
foo({ a: 1, b: 2 }); 
```

**Expected behavior:**
Object literal may only specify known properties, and 'b' does not exist in type '{ a: number; }'.

**Actual behavior:**
no error

**Playground Link:** 

**Related Issues:** 

Some weird example
```ts
type Config = {schema: string}
function graphqlHTTP(config: Config | Promise<Config>){}
// autocomplete contains all promise interface members
graphqlHTTP({ then(){}, finally(){}, schema: '' }); // is ok :)
```

**Comment by mhegazy** [comment] 2018-07-24 21:22
Duplicate of https://github.com/Microsoft/TypeScript/issues/20863

**Closed** 2018-08-02 21:55 UTC
Labels: Duplicate
