### ISSUE TITLE
Type narrowing doesn't work in closure

### ISSUE THREAD

**Issue by vtk13** [microsoft/TypeScript#53105] opened 2023-03-06 01:57 UTC
# Bug Report

### 🔎 Search Terms

union type, type narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type narrowing and guards

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230305#code/JYOwLgpgTgZghgYwgAgKIDcLgBrIN4BQyyYAngA4QBcyA5AB60DcRy9NIArgLYBG0LAL4FQkWIhQYsYAJr5WZSjVqlmrUhx78oQgosnpkAXjSYcyAD6npMlgRicQCMMAD2IZOSiukAZ18AFBBmYL40GADaALoAlPLEMK5QyAEANhBgyMHSyK4wWSG+cYTExMD5QSEAdPpGRiq0caylyAjuvq7pVamuAOaV0lWkMUzIAPRjyADuSQDWvshwCxD0lM4QACbNyOUp2eA1FBB1DI3xLcgRAIxRVdxw5AEBMUYAfG0gHV09-ftgVfQYiNxpMAAreShQMh0RjIDauCALECuTIrYC+TLuEhHOgYWhVbbCYjCYRAA)

### 💻 Code

```ts
interface EventX {
  type: 'x';
  x: number;
}
interface EventY {
  type: 'y';
  y: number;
}
type Ev = EventX | EventY;

function process(events: Ev[]) {
  for (let event of events) {
    if (event.type=='y') 
      console.log(event.y); // works as expected
    if (event.type=='x')
      [1].map(()=>console.log(event.x)); // Property 'x' does not exist on type 'Ev'.
  }
}
```

### 🙁 Actual behavior

compiler doesn't recognize that event is of type EventX inside map callback

### 🙂 Expected behavior

no errors since it is clear what should be the type of event

**Comment by vtk13** [comment] 2023-03-06 02:07
Actually seems like a duplication of https://github.com/microsoft/TypeScript/issues/51773. Can't find how to remove the bug report.

**Comment by fatcerberus** [comment] 2023-03-06 02:28
It’s ultimately a duplicate of #9998 and there’s also an issue template explaining it (“types not correct in/with callback”)

You can’t delete the issue now that you’ve posted it but you should be able to close it.

**Closed** 2023-03-06 02:35 UTC
