### ISSUE TITLE
Union types behaviour bug?

### ISSUE THREAD

**Issue by bartq** [Microsoft/TypeScript#10311] opened 2016-08-13 00:18 UTC
**TypeScript Version:**   2.1.0-dev.20160723

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
export type WebSocketMessage = {type: 'userInfo'} | {type: 'chat'};
export let WSSend = (ws: WebSocket, message: WebSocketMessage) => {
};

let ws = new WebSocket('');
let message = {type: 'chat'};
WSSend(ws, message);
```

**Expected behavior:**
No error. Noticed though that it passes:
```ts
export type WebSocketMessage = {type: 'userInfo'} | {type: 'chat'};
export let WSSend = (ws: WebSocket, message: WebSocketMessage) => {
};

let ws = new WebSocket('');
//let message = {type: 'chat'};
WSSend(ws, {type: 'chat'});
```

**Actual behavior:** 
```
Error:(13, 12) TS2345:Argument of type '{ type: string; }' is not assignable to parameter of type '{ type: "userInfo"; } | { type: "chat"; }'.
  Type '{ type: string; }' is not assignable to type '{ type: "chat"; }'.
    Types of property 'type' are incompatible.
      Type 'string' is not assignable to type '"chat"'.
```

**Comment by wallverb** [comment] 2016-08-13 00:37
It's because `let message = {type: 'chat'}` will by default infer as `{type: string}` which is not assignable to `{type: 'userInfo'} | {type: 'chat'}` which is using string literals. 

There is a discussion about possible syntax for literals https://github.com/Microsoft/TypeScript/issues/10195

**Comment by bartq** [comment] 2016-08-13 00:42
yeah, but IMO it should work as users would expect, which is no error without additional syntax. If it's not planned to be implemented at all, let's close the issue.

**Comment by DanielRosenwasser** [comment] 2016-08-13 00:46
Duplicate of #9489.

**Closed by DanielRosenwasser** 2016-08-13 00:46 UTC

**Comment by DanielRosenwasser** [comment] 2016-08-13 01:11
@bartq A workaround exists to just add a type annotation to your variable,

```ts
let message: WebSocketMessage = {type: 'chat'};
WSSend(ws, message);
```

or to pass the object literal in directly.
