### ISSUE TITLE
Iterator of array intersection incorrectly typed

### ISSUE THREAD

**Issue by rotu** [microsoft/TypeScript#57002] opened 2024-01-10 05:50 UTC
### 🔎 Search Terms

array intersection iterator

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about intersection

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.0-dev.20240109&ssl=22&ssc=1&pln=1&pc=1#code/C4TwDgpgBAglC8UDeUCGAuKBnYAnAlgHYDmUAvgNoC6AUKJFAEILJQBGmhArgLZsS5y1OuGgBhFnABkTGjQDGAe0I40uTBMQUUGKACIAZosV6ANO0wBGAEwBmcrREMAGizEVufAbQD0PqAEAegD8ckaCABRKKsBQAB5QigZqAJTINAF+AdlBoQHRWIoANhAAdEWKxBFxpagpGVAFxWUVVTVs9WRyBbH4sYiouBQAyiB8xaV9AqjAirhUEfXhUFHKqglJUH1pSA1ZObkNTSXlldW19flrzadtpR1QWQAKuIqQuKBQAORsX1AAJooIFgoIRFLEIHF8KplFB6NAvjpMDgCCQANzkL40LpAA

### 💻 Code

```ts
type A = { a: string }[]
type B = { b: number }[]
type C = A & B

const ar: C = [{ a: "foo", b: 123 }]

type X = C[number]
//   ^?

for (const x of ar) {
  //       ^?
  console.log(x.a)
  console.log(x.b)
}

const it = ar[Symbol.iterator]()
for (const x of it) {
  //       ^?
  console.log(x.a)
  console.log(x.b) // Property 'b' does not exist on type '{ a: string; }'
}

```

### 🙁 Actual behavior

Using the iterator protocol (`Symbol.iterator`) to iterate over an intersection array `A[] & B[]`

### 🙂 Expected behavior

I expect the iterator returned by `Symbol.iterator` to have the same element type as the `for...of` syntax sugar, i.e. `(A[number] & B[number])`

**Comment by rotu** [comment] 2024-01-10 06:03
Same cause as #41874, though slightly more egregious example. Perhaps `someArray[Symbol.iterator]`/`Array.prototype[Symbol.iterator]` should return the type of `this[number]` when the function is invoked instead of binding the generic when the property is accessed?

**Comment by jcalz** [comment] 2024-01-10 18:11
Duplicate of #39693 more or less?

**Comment by rotu** [comment] 2024-01-10 21:22
@jcalz As written, #39693 is now fixed. The issue here *is* something you call out in that issue - namely that the typing for `Symbol.iterator` is different from the element type!

**Comment by craigphicks** [comment] 2024-01-13 10:09
So this is bogus:
```ts
const iter: (() => IterableIterator<{
    a: string;
}>) & (() => IterableIterator<{
    b: number;
}>)
```
The result of `getPropertyOfType(A&B,[Symbol.iterator]` should be  
```ts
IterableIterator<{
    a: string;
} & {
    b: number;
}>
```
I suppose it should be able to figure out from first principles without knowing a priori what an iterator has to be, 
but because the rhs of `[Symbol.iterator]` is constrained that makes it a little easier and a short cut can be taken.
Can't actually depend upon it being `IterableIterator`.

**Comment by rotu** [comment] 2024-01-13 16:42
@craigphicks I don’t understand what you’re trying to say.

> the result of `getPropertyOfType(A&B,[Symbol.iterator]` should be

I don’t know if you’re commenting on property access on an intersection type, the return type of calling an intersection of callables, and/or the intersection of two instantiations of `IterableIntersection<T>`.

I think something like this is the correct solution: #41451.

I also think the intersection of callable types should be order-independent, but that’s likely too breaking of a change :-)

**Comment by craigphicks** [comment] 2024-01-13 17:27
> @craigphicks I don’t understand what you’re trying to say.

I was wrong to say "bogus" - it *should* work, even if it is a complex structure.

What I am saying is that anything on the rhs of a `[Symbol.iterator]` has a shape dictated by ECMA specs.
So it is possible, in the case of union or intersection of properties, to hard code a shortcut that reaches into the structures to get  their iterator return type (for the `done` false case) and generate what is effectively `()=>IterableIterator<...>`.  *(Uh, what about the case when a non-iterable iterator is present?)*.

They member of the union/intersection can be unrelated types (not both arrays, for example), it doesn't matter, that would still work because of the ECMA standard for `[Symbol.iterator]`.

**Closed** 2024-01-22 01:31 UTC
Labels: Duplicate

**Comment by craigphicks** [comment] 2024-01-22 17:30
@rotu - Here is a workaround.  Notice, however, that the iterator return is not `A[number]&B[number]` but `A[number]|B[number]`, so you have to use the `in` operator as a guard.

```ts
type A = { a: string }[]
type B = { b: number }[]
type C = (A & B) | (B & A)

const ar: C = [{ a: "foo", b: 123 }]

type X = C[number]
//   ^?

for (const x of ar) {
  //       ^?
  console.log(x.a)
  console.log(x.b)
}

const it = ar[Symbol.iterator]()
for (const x of it) {
  //       ^?
  if ("a" in x) console.log(x.a)
  if ("b" in x) console.log(x.b) // Property 'b' does not exist on type '{ a: string; }'
}

```
