### ISSUE TITLE
Strange type narrowing with Discriminated union types

### ISSUE THREAD

**Issue by Lenne231** [Microsoft/TypeScript#9254] opened 2016-06-19 11:36 UTC
**TypeScript Version:** 

nightly (1.9.0-dev.20160619-1.0)

![image](https://cloud.githubusercontent.com/assets/2046557/16177032/cad4c268-3621-11e6-8063-a23154f364be.png)

**Expected behavior:**

Type of `shape` should be `never` or `Shape` so that we can still access `type` to throw an Error.

```ts
  throw new Error('Unknown type. Type: ' + shape.type);
```

**Actual behavior:** 

Type of `shape` is `{ type: 'rectangle'; width: number; height: number }`.

**Comment by ahejlsberg** [comment] 2016-06-19 14:02
Duplicate of #9246. This is working as intended because of #8548, but it is obviously causing some confusion.

**Comment by yortus** [comment] 2016-06-20 00:53
@ahejlsberg how do the conditions of #8548 come up with this example? The *control flow type* is (or should be?) narrowed to `never` after the two type guards in the `if`/`else if` block. But then there is no *third* type guard that conflicts with that narrowed type, so why should #8548 apply?

**Comment by ahejlsberg** [comment] 2016-08-03 22:00
Fixed in #10118.

**Closed by ahejlsberg** 2016-08-03 22:00 UTC
Labels: Duplicate
