### ISSUE TITLE
Cannot find name 'AggregateError'.ts(2304)

### ISSUE THREAD

**Issue by hungnkb** [microsoft/TypeScript#58971] opened 2024-06-22 06:36 UTC
### 🔎 Search Terms

Cannot find name 'AggregateError'.ts(2304) AggregateError typescript

### 🕗 Version & Regression Information

typescript@5.5.2

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

With typescript@5.5.2 - in lib.es2022.error.d.ts get problems about this:
`interface AggregateErrorConstructor {
    new (
        errors: Iterable<any>,
        message?: string,
        options?: ErrorOptions,
    ): AggregateError;
    (
        errors: Iterable<any>,
        message?: string,
        options?: ErrorOptions,
    ): AggregateError;
}`

I get found Cannot find name 'AggregateError'.ts(2304)
![image](https://github.com/microsoft/TypeScript/assets/117344977/2edc5abe-5b09-4764-a7bd-03c76d0286d1)

### 🙂 Expected behavior

Maybe missing include AggregateError interface?

**Comment by MartinJohns** [comment] 2024-06-22 09:26
What is your tsconfig looking like? Make sure your target is at least es2021.

**Comment by hungnkb** [comment] 2024-06-22 11:03
> What is your tsconfig looking like? Make sure your target is at least es2021.
my tsconfig here: 
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2022",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "allowJs": true
  },
  "exclude": ["node_modules", "dist"]
}

Btw, im using node version 22.3

**Comment by rbuckton** [comment] 2024-06-24 19:30
Odd, if you are using `"target": "es2022"` without a `"lib": []` override, then you shouldn't be getting an error, and I wasn't able to reproduce this with only the tsconfig you provided. If you set `"target": "es2022"` then we load `es2022` by default, `es2022` loads both `es2022.error` and `es2021`, and `es2021` loads `es2021.promise`, which contains the definition for `AggregateError`.

Are you using `tsc` to build your project, or a third-party package that uses the TypeScript API to build, such as `ngc`, a webpack plugin, `ts-node`, etc. If so, I would recommend checking as to whether any of those packages have updates to be installed in the event the installed versions might have issues.

If a third-party build tool was not the issue, then can you try adding `"lib": ["es2022.full"]` to your `"compilerOptions"` in tsconfig.json? If that works, then something in your dependencies might be interfering with default lib detection. If that doesn't work, then try `"lib": ["es2022.full", "es2021.promise"]` as a workaround and report back.

You could also try running `tsc` with `--listFilesOnly` to print a list of all files in the compilation. If `es2021.promise` is in that list, then I'll need to follow up with additional steps to diagnose further. If `es2021.promise` is not in that list, then you would need to go through all of the files in that list that come from your dependencies to see if any dependency contains the text `/// <reference no-default-lib="true"/>`, as that would interfere with default lib detection.

**Comment by marek-benes** [comment] 2024-08-06 11:22
Set "target": "es2022" works for me!

**Comment by RyanCavanaugh** [comment] 2024-08-06 17:29
Sounds like this an external misconfiguration. Closing.

**Closed by RyanCavanaugh** 2024-08-06 17:29 UTC
Labels: Needs Investigation
