### ISSUE TITLE
instanceof doesn't work for extended builtin types

### ISSUE THREAD

**Issue by hbakhtiyor** [Microsoft/TypeScript#12145] opened 2016-11-10 15:19 UTC
**TypeScript Version:**  1.8.7

**Code**

```ts
export class CustomError extends Error {
    name = "CustomError";

    constructor() {
        super();
        this.message = "message";
    }
}
const err = new CustomError();
console.log(err instanceof CustomError); // => false
```

**Comment by vknez** [comment] 2016-11-16 12:11
I have the same issue with TypeScript 2.1.1.

**Comment by vknez** [comment] 2016-11-16 12:17
Apparently, there are other issues referencing the same, i.e. #12279, #12123, #12058.

**Comment by DanielRosenwasser** [comment] 2016-12-06 22:30
I'm marking this as a duplicate of #12123. This is an intentional breaking change and [documented here](https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work). Sorry about the inconveniences due to this change.

**Closed** 2016-12-06 22:59 UTC
Labels: Duplicate
