### ISSUE TITLE
`"module": "node16"` gives contradictory error about import assertions

### ISSUE THREAD

**Issue by kidonng** [microsoft/TypeScript#50653] opened 2022-09-06 15:06 UTC
# Bug Report

### 🔎 Search Terms

module node16 import assertions

### 🕗 Version & Regression Information

Happened in 4.8.2, also 4.7.4 and 4.8 beta in playground.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-beta&module=100#code/MYewdgzgLgBAZgSwDYFMYF4YCI4hAOgCsJwsAoUSWKFaDGAQwHcGFYEBbABxACcoAFIlQAaGAG8GECCn4AuCVACeXFAoDkxcOoC+OgJRkUADx78JOoA)

### 💻 Code

```ts
const file = "foo.json"
const test = await import(file, {assert: {type: 'json'}})
export {}
```

### 🙁 Actual behavior

```
Dynamic imports only support a second argument when the '--module' option is set to 'esnext', 'node16', or 'nodenext'.
```

### 🙂 Expected behavior

No error

**Comment by andrewbranch** [comment] 2022-09-06 17:38
This is not a TypeScript issue, but a Playground issue—so while the symptom is slightly different, it’s a duplicate of #49842. Until fixed, you have to refresh the playground page after switching `module` 😕

**Comment by fatcerberus** [comment] 2022-09-06 20:21
@andrewbranch Still repros after setting `Module` to Node16 and refreshing.  Changing to NodeNext and refreshing makes the error go away.

**Comment by kidonng** [comment] 2022-09-07 02:07
Sorry, I really should have stated this also happens locally:

<img width="969" alt="image" src="https://user-images.githubusercontent.com/44045911/188772712-44dfccf3-b7a8-4ba7-b48b-2b9d33050762.png">

I noticed the Playground has some funky issues, but I assume you already know abou that.

**Closed** 2022-09-08 01:47 UTC
Labels: Bug, Fix Available
