### ISSUE TITLE
Add Array.prototype.groupBy[toMap] to JS lib definitions.

### ISSUE THREAD

**Issue by Pokute** [microsoft/TypeScript#47171] opened 2021-12-16 14:38 UTC
[The proposal for `Array.prototype.groupBy` and `Array.prototype.groupByToMap`](https://github.com/tc39/proposal-array-grouping) reached stage 3 recently.

Search terms: proposal-array-grouping array groupBy ernest

# lib Update Request

With advancement into stage 3, it's time for JS engines, transpilers and toolings to start implementing support for new features and provide feedback for the proposal's advancement into stage 4.

## Configuration Check

This is so new that it needs to go into `ESNext` target.

## Missing / Incorrect Definition

Missing `Array.prototype.groupBy` and `Array.prototype.groupByToMap`.

## Sample Code

```js
const array = [1, 2, 3, 4, 5];

// groupBy groups items by arbitrary key.
// In this case, we're grouping by even/odd keys
array.groupBy((num, index, array) => {
  return num % 2 === 0 ? 'even': 'odd';
});

// =>  { odd: [1, 3, 5], even: [2, 4] }

// groupByToMap returns items in a Map, and is useful for grouping using
// an object key.
const odd  = { odd: true };
const even = { even: true };
array.groupByToMap((num, index, array) => {
  return num % 2 === 0 ? even: odd;
});

// =>  Map { {odd: true}: [1, 3, 5], {even: true}: [2, 4] }
```

Sample code from https://github.com/es-shims/Array.prototype.groupBy

## Documentation Link
Proposal: [proposal-array-grouping](https://github.com/tc39/proposal-array-grouping)

Shim implementation that can the code can be tested against: [es-shims/Array.prototype.groupBy](https://github.com/es-shims/Array.prototype.groupBy)

**Comment by orta** [comment] 2021-12-16 20:41
Open for someone to take a look. I'm not quite sure off the bat what this should look like FWIW. 

I think we probably need to make the same assumptions as we do with `Object.entries` where we can't use `keyof` https://github.com/microsoft/TypeScript/issues/38520

**Comment by orta** [comment] 2021-12-16 21:38
I asked, and we generally think this might be ok to have the more accurate typing accurately reflecting the source object. Will need a bit of testing out when there's a PR

**Comment by DanielRosenwasser** [comment] 2021-12-16 21:48
Yeah, I think we could think of this as closer to `fromEntries`; however, `fromEntries` doesn't try to preserve keys at all (and I don't think it even (cleanly) could).

**Comment by DanielRosenwasser** [comment] 2021-12-16 21:58
I feel like there is something close you can get with reversed mapped types - we discussed this in a recent design meeting about correlated unions.

https://github.com/microsoft/TypeScript/pull/47109 for some description of this.

**Comment by bharadwajduggaraju** [comment] 2021-12-19 05:10
@orta Is this issue still open? If so I would love to try to work on it as my first contribution!

**Comment by Hanaffi** [comment] 2022-01-03 13:39
@orta @DanielRosenwasser Can you assign this to me?

**Comment by orta** [comment] 2022-01-03 19:46
We don't assign issues to external folks, you're welcome to make the PR as long as there isn't an existing one (which you would see in this issue's timeline above) - so go for it

**Comment by Hanaffi** [comment] 2022-01-03 21:35
@orta Thanks. Its my first time to contribute to TypeScript. So can you give me some tips and how to get started on this issue?
I feel lost in the codebase :D

**Comment by yessGlory17** [comment] 2022-08-29 20:34
@DanielRosenwasser I want to work on this issue. It's my first time to contribute to Typescript. Is it possible for you to give me some information?

**Comment by SamB** [comment] 2023-02-24 19:36
@DanielRosenwasser 
> Yeah, I think we could think of this as closer to `fromEntries`; however, `fromEntries` doesn't try to preserve keys at all (and I don't think it even (cleanly) could).

You mean there would be a problem with the following overload, or have I misunderstood?

```typescript
interface ObjectConstructor {
    fromEntries<K extends PropertyKey, T = any>(entries: Iterable<readonly [K, T]>): Record<K, T>;
}
```

**Comment by DanielRosenwasser** [comment] 2023-02-24 21:04
Well, I don't know if you can have multiple overloads, but that fails in the case of [heterogenous property types](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgPICMBWEFgMID2IAzmFAK64FTIDeAUMk8jFAQLYCi4UwExAHgDSyCAA9IIACbFkABTYAHaGACeQiKoA0yACrIAvMjghVAPgAUEHn2IAuZAElIUOOgA2EAVAhwpRd1VkAG0hHV0AXTMASgcAJRxqKWFwswBuegBfenoEIlJjQxDggCI4Ep0AFgAmCJ1S9ArkEoALCHd3AhKIiONZPJIwDIxsXAA6Vg5uMlsLOGigA):

```ts
interface ObjectConstructor {
    fromEntries<K extends PropertyKey, T = any>(entries: Iterable<readonly [K, T]>): Record<K, T>;
}

Object.fromEntries([["a", 42], ["b", "hello"]]); // errors
```

@niieani has a PR at #50203 but [it fails once the value is not `as const`'d or contextually typed](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230224#code/JYOwLgpgTgZghgYwgAgPICMBWEFgMID2IAzmFAK64FTIDeAUMk8jFAQLYCi4UwExAHgDSEAJ4A1OABtyKCAA9IIACbFkUCHGVEpo5AG0ACmwAO0MKJGiANMjghRAXQB8ACkbNPEHn2IAuZABJSCg4dCkIYTFJGQhnaw8mAEoA-SsY2UdkBSVVAyNTc0sxW3snR0TPZAB+OgMAawDSXhAAc0cA9OlZfQBGLIBfSs8A2gMhZFBkLtj9AAZHDuno7rlFbzyNLR09NNtQGGhkcSza8WQAkAgANyOBgG56IfoEIlI7ZABefIAiOB-bAAWABMjls+h+6AByB+AAsIFIpAQfotHhhsLgAHSsDjcMi+VxwJJAA).

```ts
interface ObjectConstructor {
    fromEntries<KeyValue extends readonly [PropertyKey, any]>(
        entries: Iterable<KeyValue>,
    ): [KeyValue] extends [[PropertyKey, any]]
        ? { [k: string]: KeyValue[1] }
        : { [K in KeyValue[0]]: KeyValue extends readonly [K, infer V] ? V : never };
}

const a = [["a", 42], ["b", "hello"]];
Object.fromEntries(a)
//                 ~ error
```

(CC @sandersn)

**Comment by SamB** [comment] 2023-02-25 02:56
Oh, back on-topic, it looks like there were web-compatibility problems with the name **Array.prototype.groupBy** (issue: https://github.com/tc39/proposal-array-grouping/issues/37) and with the next name they tried, **Array.prototype.group** (issue: https://github.com/tc39/proposal-array-grouping/issues/44).

It looks like people are now thinking that adding the next thing to try is adding **groupBy**/**groupToMap** functionality as static factory methods on Object and Map, (PR https://github.com/tc39/proposal-array-grouping/pull/47), with no particular provision for subclasses.

<details><summary>We didn't need provision for subclasses anyway …</summary>

which makes sense to me because:

* For the `ArrayLike` to `object` version, you'll basically always want a **null** prototype to avoid key collisions.
* For the `ArrayLike` to `Map` version, this keeps the engine devs' jobs relatively simple (there's no way for user code to observe any of the steps between "7. Let map be ! [Construct](https://tc39.es/ecma262/#sec-construct)([%Map%](https://tc39.es/ecma262/#sec-map-constructor))." and "9. Return map.", so they can optimize the heck out of it as long as the entries end up in the correct order, without needing to worry about fallback to a "slow" version) but you can easily override the method on a subclass constructor if you want.

Anyway, the functions on Array.prototype didn't make any specific provision for subclasses, either.
</details>

**Comment by mattleonowicz** [comment] 2023-02-27 09:11
Looks like `groupBy` ticket was closed, and there is a separate ticket for it now with the "regression": https://github.com/tc39/proposal-array-grouping/issues/37

**Comment by niieani** [comment] 2023-02-28 06:48
@DanielRosenwasser Just FYI, I've addressed these failure cases, though the overall complexity has increased. The [strict and sound typing for fromEntries](https://github.com/niieani/nesity/blob/main/packages/types/src/fromEntries.ts) is published in an NPM package [`nesity-types`](https://github.com/niieani/nesity/tree/main/packages/types).

**Comment by nickmccurdy** [comment] 2023-07-18 14:20
The [proposal](https://github.com/tc39/proposal-array-grouping) has moved `Array.prototype.groupBy` to `Array.groupBy` and `Array.prototype.groupByToMap` to `Object.groupBy`.

Here are the types I'm using for reference (though I'm not sure about the soundness issue):

```ts
global {
	interface ObjectConstructor {
		groupBy<T>(
			items: Iterable<T>,
			callbackfn: (value: T, index: number) => string,
		): Record<string, T[]>;
	}
		interface MapConstructor {
		groupBy<T, U>(
			items: Iterable<T>,
			callbackfn: (value: T, index: number) => U,
		): Map<U, T[]>;
	}
}
```

If you're committing them to TypeScript or another open source git repository, please attribute me:

```
git commit --author "Nick McCurdy <https://nickmccurdy.com/>"
```

**Comment by karlhorky** [comment] 2023-08-29 12:44
@nickmccurdy thanks for this! Some small improvements that I needed to make:

- `global` -> `declare global`
- `string` -> `string | number` in return type of `callbackfn` in `Object.groupBy` because [Each value returned by `callbackfn` is coerced to a property key](https://tc39.es/proposal-array-grouping/#:~:text=Each%20value%20returned%20by%20callbackfn%20is%20coerced%20to%20a%20property%20key)
- improved expressiveness of generic parameter names

```ts
declare global {
  interface ObjectConstructor {
    groupBy<Item>(
      items: Iterable<Item>,
      keySelector: (item: Item, index: number) => string | number,
    ): Record<string, Item[]>;
  }

  interface MapConstructor {
    groupBy<Item, Key>(
      items: Iterable<Item>,
      keySelector: (item: Item, index: number) => Key,
    ): Map<Key, Item[]>;
  }
}
```

**Comment by bakkot** [comment] 2023-10-10 00:42
Drive-by: the type for the Object version should be at least a _little_ more precise. E.g.

```ts
declare function 
    ObjectGroupBy<Item, K extends PropertyKey>(
      items: Iterable<Item>,
      keySelector: (item: Item, index: number) => K,
    ): Record<K, Item[]>;
```

so that if your selector returns (e.g.) one of a fixed list of string values, that is reflected in the type of the result ([like this](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwCh5j4B5AIwCtwMBxGHZABwCEBPAHgEkMQBbADTwA0vBAAPXqmABneAAUGTEDAxthINgD4AFERLEsvPjIBc8HiqjkIIbsa0D9BgNaaAyiFuYcMczqN+c0tBeCxpCXNUZD5yFQBKeABeLREnA3jzACVwX2AOYSEQgG0AXS0AbgICWwx4cWSyKhp6RlY2HTL4KDlo2JUyoQaU+vgOeABWeAB+eAByGT4oCAg5+HM56BgAcxA5+KqAekPiAD1pgiA)).

**Comment by karlhorky** [comment] 2023-10-11 16:01
Thanks @bakkot, updated [my post above](https://github.com/microsoft/TypeScript/issues/47171#issuecomment-1697373352) with credit to you 🙌

**Comment by aiktb** [comment] 2023-11-12 14:50
`Object.groupBy` is now [fully supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/groupBy#browser_compatibility), need this badly.
![image](https://github.com/microsoft/TypeScript/assets/104723527/fbb2465b-d968-4235-ae4a-ce4e88ae3c60)

**Comment by noahehall** [comment] 2023-11-21 21:48
+1

and its now a [static on Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/groupBy)

**Comment by EgizianoEG** [comment] 2023-11-27 14:39
bump +1

**Comment by Pyrolistical** [comment] 2023-12-01 07:58
`Object.groupBy` and `Map.groupBy` achieved consensus 4 days ago at TC39. https://github.com/tc39/ecma262/pull/3176

**Comment by nikeee** [comment] 2023-12-09 16:12
> ```ts
>     groupBy<Item, Key extends PropertyKey>(
>       items: Iterable<Item>,
>       keySelector: (item: Item, index: number) => Key,
>     ): Record<Key, Item[]>;
> ```

I stumbled upon that: Returning `Record` could lead to a wrong return type. For example, [this](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwCh5j4B5AIwCtwMBxGHZABwCEBPAHgEkMQBbADTwA0vBAAPXqmABneAAUGTEDAxthINgD4AFERLEsvPjIBc8HiqjkIIbsa0D9BgNaaAyiFuYcMczqN+c0tBeCxpCXNUZD5yFQBKeABeLREnA3jzACVwX2AOYSEQgG0AXS0AbgICWwx4cWSyKhp6RlY2HTL4KDlo2JUyoQaU+vgOeAA5KAn4AH54AHIZPigICAX4cwXoGABzEAX4qoB6Y+IAPVmCIA) is always evaluates to the same key. TypeScript doesn't always know that some branch is effectively dead or that the original collection doesn't map something to a specific group (the simplest case is when it's empty).

Using `Partial<Record<Key, Item[]>>` as a return type would be more correct, I think.

**Comment by huw** [comment] 2023-12-16 01:42
I’d like to +1 @nikeee there, I raised DefinitelyTyped/DefinitelyTyped#67896 yesterday but we agreed it might be an issue for TypeScript core to determine, since it revolves around the utility of `noUncheckedIndexedAccess` and whether the design goals of this type lean toward usefulness or correctness.

I’ll argue that a very common (or at least very useful) use of `groupBy` will be to simulate a `.filter()` that returns accepted and rejected items, like so:

```ts
Object.groupBy([2, 4, 6], value => value % 2 === 0 ? "even" : "odd");
```

I think it is reasonable that some number of these filter-like use-cases will pass an array that may not satisfy all branches of the comparator. In all of these cases, the outputs will be incorrectly typed. The example above will produce `{ even: [2, 4, 6] }` but have the type `{ even: number[]; odd: number[] }`. `typeof result.odd satisfies number[]`, _even when `noUncheckedIndexedAccess` is enabled_.

I can understand if it doesn’t make sense to change the output type to `Partial`, but in that case perhaps a compiler flag could be useful to simulate `noUncheckedIndexedAccess`-like behaviour on this output?

**Comment by nikeee** [comment] 2023-12-16 01:45
Well, if the passend array is empty, the result will be an empty object, so the type would be completely wrong if we're not returning a Partial.

**Comment by huw** [comment] 2023-12-16 01:50
And since Daniel is already comparing this to `Object.fromEntries` above, I think [Ryan’s reasoning on the type correctness there](https://github.com/microsoft/TypeScript/issues/35745#issuecomment-1142580335) would probably also apply:

> It's not correct to use the input type to determine the output type, because knowing what might be in an array is not the same as knowing what's actually in it. This program is legal per the above definitions but unsound:

```ts
const arr: Array<["A", 1] | ["B", 2]> = [];
let o = fromEntries(arr);
let m: number = o.A;
```

**Comment by bakkot** [comment] 2023-12-16 01:53
Typing as `Partial<Record<Key, Item[]>>` sounds right to me. You [can still do destructuring](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgPICMBWEFgMID2IAzmFAK64FTIDeAUMsgOZQHkAOAQgJ4A8ASUgBbADTIA0hB7IIAD0ggAJsWQAFNh2hgeUngD4AFIybJgI4gC5kQ6HHQAbCIJH7RJpgGtpAZQhOqKGtDcwhha1sxM2V5axByYXRoAEpkAF59SWl3JmTrNTgoMGA4Bz4AJRxqJT49cUiAbQBdfX0AbnoAX3p6JzA6ZGJhUodxB0LmFE70tCwcMAA6VnZuHkMGgAZxACZxAA4m8Tl0zOO+ZABWZAB+ZAByIZG75Gs78ahJu+SOoA), so it's still usable.

**Comment by bakkot** [comment] 2023-12-16 02:48
Went ahead and opened https://github.com/microsoft/TypeScript/pull/56805. I credited @nickmccurdy in the commit per request above; if anyone else who contributed wants to be credited as well I'm happy to add you.

**Closed** 2024-01-11 19:17 UTC
Labels: Bug, Help Wanted, Domain: lib.d.ts, Effort: Casual

**Comment by fregante** [comment] 2025-03-21 06:44
Opened https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1943 to show why `Partial<>` doesn't make sense here.

`Partial<>` is telling TS that `Object.groupBy` can generate this: `{key: undefined}`. Obviously that doesn't happen. It can generate `{}` or `{key: [obj]}` and nothing in between

**Comment by bakkot** [comment] 2025-03-21 14:37
@fregante According to [the docs](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype) ([and the source](https://github.com/microsoft/TypeScript/blob/4dc677b292354f4b9162452b2e00f4d7dd118221/src/lib/es5.d.ts#L1557-L1562)), `Partial` sets every key to optional, not every value to `| undefined`.

I'm pretty sure your problem is with `Object.values`, not with `Object.groupBy`. You can see this if you [test for property presence explicitly](https://www.typescriptlang.org/play/?checkJs=true&allowJs=true&target=99&types=true&exactOptionalPropertyTypes=true&ssl=21&ssc=1&pln=21&pc=15#code/FAAhGMHsDsGcBcQHMBOkCuAHApgExALwgDyARgFbbjwB0qGmAQgJ4AUoYIA2h55wN68+w6AEMAttgBcIAEQAzSJFkAaIcM4A3UQBt00kACYADGo1gAvmfODzIiQdmlRKVevPa9BgGyn3l6w1bO04xSRknFzcQrV19GQAWPzsLIQBdQJBWfjDsCwBKQgA+EFzrfIBuDmAdbERRQhAAckVIJpAAS2hkNCw8EAB+HoY8GlaQGWMqhqJ0aFxseS68CqA), as long as you have `exactOptionalPropertyTypes` set.

**Comment by fregante** [comment] 2025-03-21 15:06
What's the point of `Partial<Record<string, T>>` though?

> the result will be an empty object, so the type would be completely wrong if we're not returning a Partial.

This is not wrong, it's perfectly valid:

```ts
const x: Record<string, unknown> = {}
```

It does not need Partial

**Comment by bakkot** [comment] 2025-03-21 15:09
If you read [a few comments up](https://github.com/microsoft/TypeScript/issues/47171#issuecomment-1858670761) you'll see a motivating example: `Object.groupBy([], fn).someProperty.length` should not typecheck without errors, but it would if you omitted `Partial`. The properties are, in fact, optional. The types should reflect that.

**Comment by fregante** [comment] 2025-03-21 15:20
This is really confusing. I don't see the difference between what `groupBy` returns and _just any random `Record`_

Yes the object does not have "every key" defined, so yes `Record<string, unknown[]>['someProperty']` might be undefined.

It would be (slightly) different if `groupBy` returned the type `{first: unknown[], someProperty: unknown[]}`, then _yes_ `someProperty` should be made optional by using `Partial<{first: unknown[], someProperty: unknown[]}>`

But `groupBy` currently returns `Record` and to me the `Partial<Record>` does not make sense, as no Record ensures the presence of the keys.
