### ISSUE TITLE
DOM libs are not in sync with reality.

### ISSUE THREAD

**Issue by lifeiscontent** [microsoft/TypeScript#46061] opened 2021-09-26 03:08 UTC
# Bug Report

Typescript doesn't allow to access the constructor of any of the browser's events.

### 🔎 Search Terms

event
constructor

### 🕗 Version & Regression Information

I just came across it because I was trying to create a cloned event as seen here:

https://github.com/mui-org/material-ui/blob/master/packages/mui-core/src/SliderUnstyled/SliderUnstyled.js#L246-L254

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBApgN1gXhmOB3GBJMAHAVygFEE4woAKAcgEt8jqBKAbgCg3RJZgAbcOKRRpM8JADou0AE4FgUENMqIo4qAE88cADRiorGAHpDMPCAgRaAI15wY9GACkAyrqtF7EGAEMYAFU07OGlpRRgAC2C4cSA)

### 💻 Code

```ts
const evt = new InputEvent('input');

const cloneEvt = new evt.constructor(evt.type, evt); // possible in JS, but is a Type error here.
```

### 🙁 Actual behavior

type errors when accessing a constructor of an event object.

### 🙂 Expected behavior

no type errors when creating a new event from the original event's constructor.

**Comment by MartinJohns** [comment] 2021-09-26 05:14
Duplicate of #32452.

**Closed** 2021-10-03 18:00 UTC
Labels: Duplicate
