### ISSUE TITLE
JSDoc prop of typedef wrongly nested

### ISSUE THREAD

**Issue by neekibo** [Microsoft/TypeScript#25118] opened 2018-06-21 08:21 UTC
**VS Code Version:**  1.24.1
**TypeScript Version:**  default of vsc, I think 2.9

![code-jsdocs-error](https://user-images.githubusercontent.com/986167/41706454-2fd89b02-753c-11e8-95ae-9d45a3d3c8bd.png)

**Expected behavior:** All three props should be on the same top level

**Actual behavior:** Every `@prop` definition after a `@prop {object} form` is wrongly nested inside `form`.

**Comment by andy-ms** [comment] 2018-06-21 15:33
Reproduces without react:
```js
/**
 * @typedef {object} I
 * @prop {string} a
 * @prop {object} b
 * @prop {number} c
 */

/**
 * @param {I} i
 * @return {number}
 */
function f(i) {
    return i.c;
}
```

CC @sandersn

**Comment by mhegazy** [comment] 2018-06-21 16:20
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/25072

**Closed** 2018-06-21 23:12 UTC
Labels: Duplicate

**Comment by danielo515** [comment] 2018-08-13 12:07
This is not a duplicate of #25072 albeit the look similar.
This problem is considered to be fixed ? On which version of TS ?

**Comment by andy-ms** [comment] 2018-08-13 15:28
@danielo515 The example I posted works above with `typescript@next`. See the [docs](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions) for how to set it up in vscode.

**Comment by danielo515** [comment] 2018-08-15 12:27
It works on TS 3.0 too
Thanks
