### ISSUE TITLE
Filter predicate function with `instanceOf` issues on type inference

### ISSUE THREAD

**Issue by jmoliugp** [microsoft/TypeScript#51821] opened 2022-12-08 18:09 UTC
# Bug Report

### 🔎 Search Terms
instanceOf
predicate

### 🕗 Version & Regression Information

- This error is appearing to me in versions 4.9.4, 4.8.2 & 4.4.4. Nothing makes me think it worked before in prior versions.

### ⏯ Playground Link

[link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZiEMC8MAUBKFA+GBvAKBhlElgEMUYBWIk8aGAIyrAFMB3GAUQCdeQvNAHImwjHVKNgrTj36CRwcZIawAJlWEAJNgBs9SDoL3rhqsjD0QqAbXIAaZk+BP1AXQJ1rAOjgBLPSg2XgAePgFebDRgAFd+HBJ43hh-MnIwYDYQOHlIiWIAekKYACU2CFiggC50ACYMAALbCMFapidW3lrgTzpimAAVAAsBDhsQyOr+koBBXgBzWIBbNjBYHJgoAE8ABzYYYRjk2uheNIWYAB8YMBWmEOu8wSxkXCZEPTYM4VSbMBAFAgEH8CzA5CYXy2SF25F45FWwRSmx2+0OaAAbuQ9LE2KcoOcwJcbndlg8Ujcuk40uo2AAPWqk8lOOHw7a1NBnC5PJmPSkKXgYWzuV64LE4g7+GxdYQ+GYwADKoPBUHiByOcX4+MJxNu9z5z0F7U+3zAv2WsUYDxglFRB12vDY6n8wHIwR8UAgaDqAGYACzUCQAXyAA)

### 💻 Code

```ts
const foo = () => {
  const a = 5
  const b = new Error('b')
  const c = new Error('c')
  const d = 'Hello world'
  const ls = [a, b, c, d]

  ls.filter<Error>(curr => curr instanceof Error)
  // Result: (2) [Error: b, Error: c]

  // Throws error:
  // Argument of type '(curr: string | number | Error) => boolean' is not assignable to parameter of type '(value: string | number | Error, index: number, array: (string | number | Error)[]) => value is Error'.
  // Signature '(curr: string | number | Error): boolean' must be a type predicate.ts(2345)
}
```

### 🙁 Actual behavior

It is neither recognizing the predicate function nor that the result will be an array of `Error` values.

### 🙂 Expected behavior

Interprets that the function is a predicate and filter the errors with the operator `instanceOf`.

**Comment by MartinJohns** [comment] 2022-12-08 18:22
Duplicate of #38390.

Your function is not a type guard. Add a type annotation to make it a type guard and it will work.

**Comment by MartinJohns** [comment] 2022-12-08 19:57
`ls.filter<Error>((curr): curr is Error => curr instanceof Error)`

**Closed** 2022-12-11 18:00 UTC
Labels: Duplicate
