### ISSUE TITLE
Iterator result of Iterable or AsyncIterable inferred to any 

### ISSUE THREAD

**Issue by ikokostya** [microsoft/TypeScript#33932] opened 2019-10-10 18:18 UTC
**TypeScript Version:**  3.7.0-dev.20191010

**Search Terms:**

Iterable, AsyncIterable, Iterator, IteratorResult

**Code**

Synchronous iterators:

```ts
declare let syncIterable: Iterable<number>;
let res = syncIterable[Symbol.iterator]().next();
let value = res.value;
```

Asynchronous iterator:

```ts
declare let asyncIterable: AsyncIterable<number>;

(async () => {
    let res = await asyncIterable[Symbol.asyncIterator]().next();
    let value = res.value;
});
```

**Expected behavior:**

In both cases `value` has `number` type.

**Actual behavior:**

Variable `value` has `any` type.

***

**Investigation**

Type `IteratorResult` has two type parameters `T` and `TReturn`: https://github.com/microsoft/TypeScript/blob/616200125459bb484b087f33c9925ef17e2768ce/lib/lib.es2015.iterable.d.ts#L41

Because by default `TReturn` is `any` (interface [`Iterable`](https://github.com/microsoft/TypeScript/blob/616200125459bb484b087f33c9925ef17e2768ce/lib/lib.es2015.iterable.d.ts#L50) has only one type parameter), we got `number | any` type, which is narrowed to `any`.

There are two problems:

* There is no way to specify `TReturn` type parameter for `IterableIterator` and `AsyncIterableIterator` types.
* Current behavior is unsafe.

**Playground Link:**  

https://www.typescriptlang.org/play/index.html?ssl=3&ssc=23&pln=1&pc=1#code/CYUwxgNghgTiAEEQBd4GcCeA7MBJZIMUARkgFzz6ElIA8WArgLbGEB8A3AFBKpxrwAvOmx4CRUiADaAZQwsA9hAB0AS3FRkCmAF0AFAEplWEAA9kh7r3gA3KBAYJh-ZXYcgOQA

**Related Issues:** 

https://github.com/Microsoft/TypeScript/issues/2983

**Comment by bterlson** [comment] 2020-02-08 01:19
In addition to also wanting the fix suggested above (plumbing TReturn and TNext from AsyncIterableIterator to IteratorResult), I wonder if `any` is the best type? When I see an `any` I don't suspect I need to narrow, I suspect I've done something wrong. `undefined` could be a better default, though I haven't considered this at length.

**Comment by rbuckton** [comment] 2020-12-16 00:45
This is a duplicate of 33353. Also, your expected behavior is incorrect. Without checking `done`, you cannot guarantee that `value` is a number: 

```ts
const numbers: number[] = [];
const value = numers[Symbol.iterator]().next().value;
console.log(value); // undefined
```

While the correct result should be `number | undefined`, but may be a significant breaking change.

**Closed by rbuckton** 2020-12-16 00:45 UTC
Labels: Needs Investigation, Rescheduled

**Comment by ikokostya** [comment] 2020-12-16 18:14
Duplicate of https://github.com/microsoft/TypeScript/issues/33353
