### ISSUE TITLE
tsc --build takes wrong assumption on project rootDir

### ISSUE THREAD

**Issue by sguillia** [microsoft/TypeScript#41801] opened 2020-12-03 14:43 UTC
**TypeScript Version:**  4.2.0-dev.2020120

**Search Terms:** tsc, project reference, inconsistent rootdir, builds again

**Code**

https://github.com/sguillia/ts-bug-repro-II

```ts
// No code, an empty TS file is enough to reproduce.
```

```
tsc --build --verbose
tsc --build --verbose
```

**Expected behavior:**

Project was built once.

**Actual behavior:**

Project was built twice.

**Playground Link:**

No playground link. Typescript Playground does not offer the `outDir` option.

**Related Issues:**  not found, sorry

**Additional information**

Second build logs this message:

```
[14:36:00] Project 'tsconfig.json' is out of date because output file 'dist/src/index.js' does not exist
```

`dist/src/index.js` is not supposed to exist. `dist/index.js` does.

Setting the following setting in the tsconfig.json fixes the problem:

```
"rootDir": "./src"
```

But the actual behavior should be consistent even without the `rootDir` setting

As explained [here in the docs](https://www.typescriptlang.org/docs/handbook/project-references.html#build-mode-for-typescript), `tsc --build` is supposed to consistently detect whether the project is up-to-date.

**Comment by benmccann** [comment] 2020-12-03 16:36
This is the same behavior I reported into https://github.com/microsoft/TypeScript/issues/41780. In that bug, `getOutputFileNames` was being called directly by the Rollup Plugin and returning `dist/src/index.js` instead of `dist/index.js`. I wonder if `tsc` follows a different code path that also uses the broken implementation of `getOutputFileNames` when the `--build` option is used

**Comment by sheetalkamat** [comment] 2020-12-03 23:31
Duplicate of #41780

**Closed** 2020-12-06 18:00 UTC
Labels: Bug, Duplicate, Fix Available

**Comment by klauszhang** [comment] 2021-11-08 04:55
Why this is still happening after almost one year? This wasted me entire afternoon :(
