### ISSUE TITLE
Intellisense gives "any" type for the original name in a destructuring assignment

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/TypeScript#3457] opened 2015-06-09 22:11 UTC
```typescript
interface A {
	x: number;
}

var a: A;
var { x: x2 } = a;
```

This gives the type "any" when mousing over `x`

![image](https://cloud.githubusercontent.com/assets/1096010/8070646/a8984194-0eb7-11e5-82c6-54bf3f66956c.png)

(Not sure what the corresponding services API is. `getTypeDefinitionAtPosition` ?)

Mousing over `x2` is fine - it gives "number". It would be nice if mousing over `x` gave the same, since it helps with nested destructuring to see the intermediate steps.

**Comment by DanielRosenwasser** [comment] 2015-06-09 22:34
Duplicate of #2675.

**Closed by DanielRosenwasser** 2015-06-09 22:34 UTC
Labels: Bug
