### ISSUE TITLE
React component spread props in version v2.3.2 not compile children module right.

### ISSUE THREAD

**Issue by myxvisual** [Microsoft/TypeScript#15896] opened 2017-05-17 04:47 UTC
**TypeScript Version:**  2.3.2

**Code**

```ts
import * as React from "react";

import A from "./A";

export default class Test extends React.PureComponent<any, void> {
  render() {
    const { a, ...b } = this.props;
    return (
      <div {...b}>
        <A />
        <div>Test</div>
      </div>
    );
  }
}
```
in version `2.3.2`, compile the finished code is wrong:
```js
"use strict";
// var __extends = (this && this.__extends) || function (d, b) {...
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var Test = (function (_super) {
    __extends(Test, _super);
    function Test() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Test.prototype.render = function () {
        var _a = this.props, a = _a.a, b = __rest(_a, ["a"]);
        return (React.createElement("div", __assign({}, b),
            React.createElement(A_1.default, null),
            React.createElement("div", null, "Test")));
    };
    return Test;
}(React.PureComponent));
exports.default = Test;
```
`A` module is not compiled.
in version `2.1.6`,compile the finished code is right:
```js
"use strict";
// var __extends = (this && this.__extends) || function (d, b) {...
var React = require("react");
var A_1 = require("./A");
var Test = (function (_super) {
    __extends(Test, _super);
    function Test() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Test.prototype.render = function () {
        var _a = this.props, a = _a.a, b = __rest(_a, ["a"]);
        return (React.createElement("div", __assign({}, b),
            React.createElement(A_1.default, null),
            React.createElement("div", null, "Test")));
    };
    return Test;
}(React.PureComponent));
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Test;
```

[Test Source Code](https://github.com/myxvisual/react-spread-props-typescript)

OS:  win10 build 1703
nodeJS: v6.10.3

**Comment by faddee** [comment] 2017-05-17 10:22
I just ran into a similar issue where the `import` just disappears in TypeScript v2.3.2

```tsx
import foo from './foo' // This never happens
// ...
<Component {...foo()} />
```

To solve it I have to...
```tsx
import foo from './foo'
// ...
const bar = foo();
<Component {...bar} />
```

**Comment by mhegazy** [comment] 2017-05-17 16:56
Duplicate of https://github.com/Microsoft/TypeScript/issues/15469. should be fixed in TS 2.3 (out later this week). the fix should already be in `typescript@next` please give it a try and let us know if you still running into issues.

**Closed** 2017-05-17 17:22 UTC
Labels: Duplicate

**Comment by myxvisual** [comment] 2017-05-18 06:49
@mhegazy thanks~

**Comment by myxvisual** [comment] 2017-05-18 06:54
@mhegazy I tried the next version and it worked fine.
