### ISSUE TITLE
Issue when class property initialization happen inside, a method called inside of constructor

### ISSUE THREAD

**Issue by iamchathu** [microsoft/TypeScript#33347] opened 2019-09-10 11:29 UTC
**TypeScript Version:**  Version 3.5.3

**Search Terms:**

Class property initialization, error TS2564: Property has no initializer and is not definitely assigned in the constructor.

**Code**

```ts
export class NetworkConnection extends EventEmitter {

  private intervalId: NodeJS.Timeout;

  public constructor(timeout = 60000) {
    super();
    this.start(timeout);
  }

  public start = (timeout: number) => {
    this.intervalId = setInterval(this.broadcast, timeout);  
  };

  public stop = () => {
    clearInterval(this.intervalId);
  };

...
}
```

**Expected behavior:**

Run without compile error.

**Actual behavior:**

error TS2564: Property 'intervalId' has no initializer and is not definitely assigned in the constructor.

**Playground Link:** 

**Related Issues:** #24446 #21132

**Comment by MartinJohns** [comment] 2019-09-10 11:43
Duplicate of #21132, not just a related issue.

**Closed** 2019-09-10 12:00 UTC
