### ISSUE TITLE
Feature Request: Process of Elimination for Unions

### ISSUE THREAD

**Issue by Gaelan** [Microsoft/TypeScript#4893] opened 2015-09-21 03:12 UTC
This should compile without errors:
```typescript
declare function getDBObjectById(id: number): DBObject;
declare function bar(arg: DBObject): void;
function foo(arg: number | DBObject) {
  if (arg instanceof DBObject) {
    bar(arg)
  } else {
    bar(getDBObjectById(arg) // error TS2345: Argument of type 'number | DBObject' is not assignable to parameter of type 'number'.
                             // Type 'DBObject' is not assignable to type 'number'.
  }
}

**Comment by mhegazy** [comment] 2015-09-21 08:21
looks like a duplicate of #1719

**Comment by mhegazy** [comment] 2015-09-21 08:23
also note that `typeof arg !== "number"` will work as you expect.

**Closed by mhegazy** 2015-09-21 08:23 UTC
Labels: Duplicate
