### ISSUE TITLE
Change Array by Copy

### ISSUE THREAD

**Issue by spamshaker** [microsoft/TypeScript#54794] opened 2023-06-27 05:32 UTC
# Suggestion

## 🔍 Search Terms

[Array.prototype.toSpliced()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSpliced)
[Array.prototype.toSorted()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSorted)
[Array.prototype.toReversed()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toReversed)
[Array.prototype.with()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/with)

polyfill: https://github.com/tc39/proposal-change-array-by-copy

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

To support features already implemented in js engines
e.g.
https://caniuse.com/?search=tospliced

## 💻 Use Cases

Workaround /* @ts-ignore */

**Comment by MartinJohns** [comment] 2023-06-27 06:02
Duplicate of #50333. This is already supported in the Nightly version.

**Closed** 2023-07-02 01:34 UTC
Labels: Duplicate
