### ISSUE TITLE
Incorrect type NamedNodeMap

### ISSUE THREAD

**Issue by ststeiger** [microsoft/TypeScript#50650] opened 2022-09-06 08:53 UTC
In lib.dom.d.ts (TypeScript version 4.5), there is

```
interface NamedNodeMap {
    readonly length: number;
    getNamedItem(qualifiedName: string): Attr | null;
    getNamedItemNS(namespace: string | null, localName: string): Attr | null;
    item(index: number): Attr | null;
    removeNamedItem(qualifiedName: string): Attr;
    removeNamedItemNS(namespace: string | null, localName: string): Attr;
    setNamedItem(attr: Attr): Attr | null;
    setNamedItemNS(attr: Attr): Attr | null;
    [index: number]: Attr;
}
```
This type is wrong. 
If I do: 
`let a = document.getElementByid("some element with attributes"); `
and want to set an attribute, e.g. style, like in 
`a.setAttribute("style", "display: none;");`
and I want to do that over a.attributes instead, I have to do: 
`a.attributes.getNamedItem("style").value = "display: none;";`

But in Chrome, Firefox and even IE 11, I can also do 
`a.attributes["style"].value = "display: none;";`
and 
`a.attributes.style.value = "display: none;";
`
TypeScript issues an error for the last two. 
Bug.

**Comment by MartinJohns** [comment] 2022-09-06 09:18
You forgot to fill out the issue template. Duplicate of #30928. Used search terms: `NamedNodeMap in:title`

**Comment by fatcerberus** [comment] 2022-09-06 14:07
It’s not really spelled out in the other issue so the limitation here is that this would require the type to have a string index signature `[name: string]: Attr` which would be rejected because it’s incompatible with the rest of the type.  There’s no mechanism in TS for types to be indexable for only a subset of strings.

**Closed** 2022-09-11 18:00 UTC
Labels: Duplicate
