### ISSUE TITLE
BUG: Array with string type elements

### ISSUE THREAD

**Issue by profhun** [Microsoft/TypeScript#29956] opened 2019-02-18 14:08 UTC
**TypeScript Version:**  3.3.3

**Code**

```
function arrayToString(arr: Array<string>):string {
    arr.forEach((item) => {
        console.log('typeof item',typeof item, item);
    })

    return arr.join("\n");
}

function forwardParams(...args){
    console.log('typeof args', typeof args, args);
    return arrayToString(args);
}

const sampleArr = [
    'foo',
    'bar',
    {
        foo: 'bar',
        bar: 'foo'
    }
];

console.log(forwardParams(...sampleArr));
```

**Expected behavior:**
arrayToString method throws a TypeError

**Actual behavior:**
arrayToString method eats the Object array item

Is it a bug or a feature?

**Comment by dragomirtitian** [comment] 2019-02-18 14:24
`forwardParams` has an untyped parameter `args`. If no type is specified it will implicitly be `any`. Any can be assigned to anything and can be assigned from anything. 

Give this, when you call `forwardParams` you can pass in anything (since `args` is of type `any`). Inside `forwardParams` you can call `arrayToString(args)` again since `args` is of type any.

You should generally specify argument types to help the compiler check you code. This will raise a compilation error:


```ts
function arrayToString(arr: Array<string>):string {
    arr.forEach((item) => {
        console.log('typeof item',typeof item, item);
    })

    return arr.join("\n");
}

function forwardParams(...args: string[]){
    console.log('typeof args', typeof args, args);
    return arrayToString(args);
}

const sampleArr = [
    'foo',
    'bar',
    {
        foo: 'bar',
        bar: 'foo'
    }
];

console.log(forwardParams(...sampleArr));
```
[play link](https://typescript-play.js.org/#code/GYVwdgxgLglg9mABAQwE6uQTwCpwMpSoxgDmAFGqgFyICC6WAPAM6HEkB8AlFa0aYgDeAKERiU6AHTA4qAKLIIACzJkYUAKYBbLogC8HIaPEmICZnAA2GyZbjkA5FEwAHDXGCJ12hwBpnbh5emlq+wdpcANzGYgC+XMIxiKgaUCCoSJSSAFZwxGQARAA6YAVRwrGJoJCwCIgyqADuaAAmAApoyFrMZJJ9aCTMNHzsANoAulwipuZWNnaOAe6eA8x+iEtBq2Gr5SYpaRkSGDj4bKQUqIPllcJmYKyIzF0u1vSo+oijSQ4ycH4-ABGaABJmmJnEfxoDmBqFBELEsOhfwcSUq42id1m1ls9jIDWaqHanW6vT6zy0rw07y4USAA)

There is also a compiler option to force you to specify types of an apropriate type can't be inferred from context, the option is `noImplictAny` [docs](https://www.typescriptlang.org/docs/handbook/compiler-options.html)

**Comment by profhun** [comment] 2019-02-18 14:44
i can agree this, and it's a nice workaround, the forwardParams can checks the ...args, but the main problem is the same. Without that the object will pass through.

**Comment by dragomirtitian** [comment] 2019-02-18 14:53
@profhun 
I am not sure what part you expect would raise an error. As your code is written it works as intended. The omission of the argument type creates a hole in type checking, but this is by design to allow gradual typing of a code base. If you want this code to raise a typescript error you need to use `noImplicitAny` and then use an explicit type annotation (preferably one that does not contain `any` ie not `forwardParams(...args: any[])`

If you are expecting a runtime error, that is out of scope for Typescript.

**Comment by RyanCavanaugh** [comment] 2019-02-19 19:13
It's unclear if this is a question, bug report, or suggestion, or what you're proposing/specifically citing in any case.

**Closed by RyanCavanaugh** 2019-02-19 19:13 UTC
Labels: Unactionable

**Comment by profhun** [comment] 2019-02-20 08:05
it's a bug.

i try to explain in a simple way:

you have this function: 
```
function arrayToString(arr: Array<string>):string
```

the expected behavior is:
drop a typeError when the array has any value is not a string

actual behavior:
it not drops.

Thank you...

p.s.:
that one line matters, the other ones is only the decoration.

**Comment by dragomirtitian** [comment] 2019-02-20 08:57
@profhun  When are you expecting this type error ? At compile time ? At runtime ? 

If you are expecting it at compile time, then you do get an error, as long as you don't leave out a type (which you can make an error with `noImplicitAny`)  or don't type something explicitly as `any`

If you are expecting an error at runtime, then this is not something typescript was designed to do. Typescript does no runtime checking on anything, only static checking when compiling the ts code. The generated JS looses all type information as behaves as any JS code would.

This is working as intended, under the current design.
