### ISSUE TITLE
Add a new flag for strict comparisons

### ISSUE THREAD

**Issue by AlexGalays** [microsoft/TypeScript#31852] opened 2019-06-11 08:41 UTC
## Suggestion

Under a new compiler flag (`strictComparisons`?), TypeScript should check whether if/else, switch, ternaries, type guards, etc statements actually makes sense.

Without this, at best we have a useless check that could be removed for readability and at worst, a bug/incorrect check that the type system didn't challenge.

## Examples

(This one happened in real life)
```ts
function userHasFeatureFlag() {
  return false;
}

// This is a useless check because of a bug typo
const importantDecision = userHasFeatureFlag ? 3 : 10;
```
More generally:

```ts
const config: number | string = 3;

// This is a useless check because the union doesn't even include the type being tested 
const anotherImportantDecision = config === undefined ? 3 : 10;
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jack-williams** [comment] 2019-06-11 09:16
Your first example is tracked here: #9041
Your second example is related / a duplicate of #11920.

**Closed** 2019-06-14 18:00 UTC
Labels: Duplicate
