### ISSUE TITLE
TypeError: b is undefined in __extends

### ISSUE THREAD

**Issue by drake7707** [Microsoft/TypeScript#4341] opened 2015-08-17 18:30 UTC
```

class B extends A {
    constructor(msg:string) { 
        super(msg);
    }
}

class A {
    constructor(public msg:string) {
        
    }
}

```

If the super class of B is defined after A you'll get a runtime error.

Just tested the above code in the typescript playground and I get the same error

**Comment by mhegazy** [comment] 2015-08-17 18:49
This issue has been discussed in  #21 and has been closed for some bigger issue. this has been a reoccurring pain though.

The consensuses in #21 is to show a compiler error about what the wrong order. we should be able to do this easily using `checker.ts::isDefinedBefore`.

**Comment by nbellowe** [comment] 2015-08-20 09:22
Why isn't this expected behavior? 
```
class B extends A {
    constructor(msg:string) { 
        super(msg);
    }
}
class A {
    constructor(public msg:string) {

    }
}
```

Generates
```
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};
var B = (function (_super) {
    __extends(B, _super);
    function B(msg) {
        _super.call(this, msg);
    }
    return B;
})(A);
var A = (function () {
    function A(msg) {
        this.msg = msg;
    }
    return A;
})();
```

The IIFE after `var B =` has a parameter of `A`, but `var A = ...`isn't called until just after that.

I don't know how you could get the above functionality ... maybe:

```
var B;
var A;
(function(){
function b(_super) {
    __extends(B, _super);
    function B(msg) {
        _super.call(this, msg);
    }
    return B;
}
function a(){ ... }
B = b(a);
A = a;
})()
```

**Comment by DanielRosenwasser** [comment] 2015-08-20 17:24
It's expected, it's just that the compiler should warn you that this will happen.

**Comment by danquirk** [comment] 2015-08-20 20:48
As mentioned, dupe of #2854

**Comment by mhegazy** [comment] 2015-08-20 21:24
@sheetalkamat has a fix for the class issue since it has been biting users quite frequently.

**Comment by Tydude4Christ** [comment] 2015-09-18 13:55
I'd love to see this fix soon. It's a huge pain when using a code generator.

**Comment by rodrigogq** [comment] 2015-12-14 20:36
I am having the same issue even if the class is used after the other:

BaseClass.ts:
```
module MyModule {
  class Base {
    constructor() { }
  }
}
```
ChildClass.ts:
```
module MyModule {
  class Child extends Base {
    constructor() { super(); }
  }
}
```

Generates:
```
/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var MyModule;
(function (MyModule) {
  /** Generated from MyModule.Base **/
  var Base = (function () {
    function Base () {
    }
    return Base;
  })();
  MyModule.Base = Base;
})(MyModule || (MyModule = {}));
var MyModule;
(function (MyModule) {
  /** Generated from MyModule.Child **/
  var Child = (function (_super) {
      __extends(Child, _super);
      function Child() {
          _super.apply(this, arguments);
      }
      return Cycle;
  })(MyModule.Base);
  MyModule.Child = Child;
})(MyModule|| (MyModule = {}));

```
It seems that the order is correct, although it doesn't look like it is working as expected.

**Comment by RyanCavanaugh** [comment] 2015-12-14 22:05
@rodrigogq the generated code you posted runs without error. The input code you posted has a compile error because `Base` is not exported from its module and is thus invisible in the second declaration.

**Comment by mhegazy** [comment] 2016-02-22 20:36
closing in favor of https://github.com/Microsoft/TypeScript/issues/5207

**Closed by mhegazy** 2016-02-22 20:36 UTC
Labels: Bug
