### ISSUE TITLE
Missing file extension for named modules from "-m system --outFile foo.js"

### ISSUE THREAD

**Issue by danieleds** [Microsoft/TypeScript#6774] opened 2016-01-31 22:40 UTC
When bundling multiple files with -m system, the module names should include the file extension. Otherwise, they are loaded but not executed by systemjs.

Before:
```javascript
    System.register("app/boot", [...], ...
```
After:
```javascript
    System.register("app/boot.js", [...], ...
```

See here: https://github.com/systemjs/systemjs/issues/1065

**Comment by mhegazy** [comment] 2016-02-01 17:22
looks like a duplicate of #4595.

**Closed by mhegazy** 2016-02-01 17:22 UTC

**Comment by geoff-mci** [comment] 2016-11-09 09:54
@mhegazy I'm not sure this is really a duplicate.  #4595 fixes an import issue for TypeScript, but the comments in [https://github.com/systemjs/systemjs/issues/1065](url) indicate that for systemjs to work with typescript outFile bundles the .js extension must be present in the System.register call.   
...Of course I could be missing something.

My use case:
I'm trying to have the simplest dev setup I can for Angular2 development.  I use webpack in production because it's the one I've managed to grok enough to make work (why is module loading over complicated!) but have found it too slow for development.  I'd like to be able to generate a bundle from typescript and then execute the bootstrap module from within that...but this issue blocks that workflow (except I'll probably write a gulp task to add the extensions myself).

Cheers.

**Comment by tuukkapuranen** [comment] 2017-01-07 17:40
@geoff-mci I agree, this may not be a duplicate of #4595. I just ran into same issue as you and @danieleds with [#1065](https://github.com/systemjs/systemjs/issues/1065) at SystemJS. The `outFile` bundle is generated without .js extension for SystemJS, and this results in the main script not executing. Other calls to `register` seem to work without the extension.

The good news is, I was able to trick `tsc` into generating the extension to the script defined by `outFile`. It turns out that the code is generated by the [`system`](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/transformers/module/system.ts#L99) module, which in turn calls [`tryGetModuleNameFromFile`](https://github.com/Microsoft/TypeScript/blob/4fa8118b01ba231d6910465d3d31a70e32a6ae8e/src/compiler/factory.ts#L2990), and this function reads the `<amd-module name="name">` comment to determine if there is a custom name present.

I added `/// <amd-module name="boot.js" />` to the .ts file with the same name (which is also the name of the `outFile` target), and the result does now get the extension to the name: `System.register("boot.js", ...` However, I am not sure how stable this approach is. Can someone more knowledgeable shed some light on this?

**Comment by aluanhaddad** [comment] 2017-01-07 18:51
@tuukkapuranen I do not recommend using `<amd-module>` as a workaround is definitely not something you want to commit to using. The bundle shouldn't need to use any extensions in the named register output, the names just need to match up. I just tried it and it generates an extensionless bundle that loads just fine provided that you are configuring the loader in the standard way. For TypeScript projects, you want to set 
```js
SystemJS.config({
  packages: {
    "my-package": {
      "main": "my-package-main",
      "defaultExtension": "ts"
    }
  }
});
```
then you can
```html
<script>
  SystemJS.import('my-package').catch(function (e) { console.error(e); });
</script>
