### ISSUE TITLE
Boolean() function is not working with type-guard.

### ISSUE THREAD

**Issue by rockmandash** [Microsoft/TypeScript#30321] opened 2019-03-11 17:22 UTC
When I call `Boolean()` function to test a union type, it doesn't have type-guard working.
Here is a simple code and VSCode screenshot.
 
![image](https://user-images.githubusercontent.com/7580792/54143516-f63b2380-4464-11e9-9aef-67eaff3102ac.png)
```ts
function test(number: number | undefined) {
  if (Boolean(number)) {
    console.log(number)
  }
}
```

**Comment by jack-williams** [comment] 2019-03-11 17:33
Duplicate of #16655, and there is an open PR fixing this here: #29955

**Closed** 2019-03-11 18:39 UTC
Labels: Duplicate
