### ISSUE TITLE
Mapped values don't preserve narrowed type information

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#20199] opened 2017-11-21 18:50 UTC
**TypeScript Version:**  2.7.0-dev.20171121

**Code**

```typescript
type IEventRegistrations<TEvents extends string> = {
    [EventName in TEvents]?: boolean;
};

interface ITypes {
    noise: number | boolean | string;
    taste: number | string;
}

class EventEmitter/*<TTypes = any>*/ {
    private readonly registrations: IEventRegistrations<keyof ITypes> = {};

    public getRegistration<TEventName extends keyof ITypes>(eventName: TEventName): boolean {
        if (this.registrations[eventName] === undefined) {
            this.registrations[eventName] = true;
        }

        const registration = this.registrations[eventName];

        // Type 'IEventRegistrations<"noise" | "taste">[TEventName]' is not assignable to type 'boolean'.
        //  Type 'boolean | undefined' is not assignable to type 'boolean'.
        //    Type 'undefined' is not assignable to type 'boolean'.'
        return registration;
    }
}
```

**Expected behavior:**

We should know for the `const registration` that `this.registrations[eventName]` must exist (and we do when it's a regular `{ [i: string]: ... }` instead of a mapped type).

**Actual behavior:**

Something about being a mapped type is making TypeScript not remember the narrowing.

**Comment by mhegazy** [comment] 2017-11-21 18:57
Duplicate of https://github.com/Microsoft/TypeScript/issues/10530

**Closed** 2017-11-21 19:00 UTC
Labels: Duplicate
