### ISSUE TITLE
Promise<unknown> is not assignable to Promise<void>

### ISSUE THREAD

**Issue by kkirby** [microsoft/TypeScript#44201] opened 2021-05-21 17:12 UTC
# Bug Report

Currently `unknown` is assignable to `void`. However, `Promise<unknown>` is NOT assignable to `Promise<void>`.

### 🔎 Search Terms

promise, type compatibility, assignment

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3&ssl=25&ssc=50&pln=1&pc=1#code/MYewdgzgLgBAbiAlgEwAoCcQFtEQKYBiYMAvDAIYQCeYwMAFAJSkB8MA3gL4BQoksCFEVINmJNlwDc3XuGgwArmADWYEAHcwGbLkLEylGnSYAuGNpz4APEtUawbcfCTIYABml95ttZuFlTRRVffTZBVw8ZL1gocmU8CAA1FwtdfwYAMzAzKCoABzwQDOcUVPwiMQlOTzkYuITkoX1M7JhcgqKS5ArWDmqZAHoBmAAVAAtcGHUQdGUIblj4pJcienCK6SHRiYgpmbmF+uWm+h97DcHh8cnp2fnFhpTMSz01p51ysEZNq52YZBACRgADkAPIjPazQ5LRpoZ5pMCnYL2Mp6b5RWptI6w1EiehZMyoqzhFiVPrSbhba67W4HB7HOEfPD0MB4dTmeHWEn0Ji9LiMdFUv4AoFgiG06GPUqc5ms9lEs6aFg8sn89EyGRAA)

### 💻 Code

```ts
const voidPromiseFn = async () => {}
const voidFn = () => {};

const unknownPromiseFn = async (): Promise<unknown> => void 0;
const unknownFn = (): unknown => void 0;

const takesVoidPromiseFn = (fn: typeof voidPromiseFn) => {};
const takesVoidFn = (fn: typeof voidFn) => {};

// This works
takesVoidFn(voidFn);
// This works
takesVoidFn(unknownFn);

// This works
takesVoidPromiseFn(voidPromiseFn);
// This does NOT work
takesVoidPromiseFn(unknownPromiseFn);

const takesVoidPromise = (fn: Promise<void>) => {};

// This works
takesVoidPromise(new Promise<void>(() => {}));
// This does NOT work
takesVoidPromise(new Promise<unknown>(() => {}));
```

### 🙁 Actual behavior

A function that returns `Promise<unknown>` (`() => Promise<unknown>`) could not be passed as a function argument with the type `() => Promise<void>`. Contradictory, a function that returns `unknown` (`() => unknown`) can be passed to a function argument with the type `() => void`.

### 🙂 Expected behavior

I would expect that passing a `() => Promise<unknown>` to a function argument that accepts `() => Promise<void>` to be allowed.

**Comment by MartinJohns** [comment] 2021-05-21 18:38
Duplicate of #12871.

**Closed** 2021-05-30 18:00 UTC
Labels: Duplicate
