### ISSUE TITLE
Control Flow Analysis should apply to array indexers

### ISSUE THREAD

**Issue by opirci** [Microsoft/TypeScript#28999] opened 2018-12-13 07:46 UTC
## Search Terms

Control Flow Analysis for array indexers

## Suggestion

Control Flow Analysis for indexers should apply for array indexers

## Use Cases

We cannot check the type of array with typeof keyword. So we check it via the value of one of its items. But CFA not applies in this case. Below example it is expected "items[0] = 1;" instruction should not be allowed.

## Examples
```typescript
 function foo(items: number[] | string[]): void {
    const ids: number[] = [];
     if (typeof items[0] === 'number') {
         items[0] = ''; // Should not be allowed
         items[0] = 1;
      for (const i of items as number[]) {
        ids.push(i);
      }
    } 
  }
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment] 2018-12-13 18:38
This is reasonably close to a duplicate of #10530 (though it asks for a bit more)

**Closed** 2018-12-16 18:00 UTC
Labels: Duplicate
