### ISSUE TITLE
Intellisense path suggestions hides file extension referencing .js/x and .ts/x files

### ISSUE THREAD

**Issue by silkfire** [microsoft/TypeScript#44214] opened 2021-05-22 10:20 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Windows 10, 20H2 19042.985

Steps to Reproduce:

1. Have an import path in a JavaScript or a TypeScript file, referring to a module ending in .js/x or .ts/x.
2. Ctrl + Spacebar (IntelliSense) to trigger autocomplete suggestions.

The dropdown shows any JavaScript or TypeScript files without their respective file extensions. Hitting Tab autocompletes their names without the extension, when I actually need the full name of the file.

For some reason, the tooltip in the right margin shows the full name, but this is never resolved when hitting Tab.

![image](https://user-images.githubusercontent.com/1554615/119069446-73b83200-b9e6-11eb-9b4f-84d30af6498d.png)

**Expecting** `index.js`, not `index`; and `webpack.dev.js`, not `webpack.dev`.

**Comment by MartinJohns** [comment] 2021-05-22 10:50
Related: #35926

**Comment by andrewbranch** [comment] 2021-05-27 20:46
@silkfire it sounds like you’re just looking for this setting:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/3277153/119894765-dc754200-bef1-11eb-874c-1c41f33bebb0.png">

**Comment by silkfire** [comment] 2021-05-27 22:23
@andrewbranch To be fair, I've actually already enabled this setting and set it to `.js` (both for JS and TS). I believe there's an ongoing bug where the setting isn't being respected by the TS engine.

Could it be that it was resolved in #39155 but just hasn't been released yet?

**Comment by andrewbranch** [comment] 2021-05-27 22:25
That fix is present in 4.3, which was just released. If you’re on 4.3 in your editor, then there’s still some sort of bug.

**Comment by silkfire** [comment] 2021-05-27 22:26
@andrewbranch I'm on 4.2.4, the version shipped with the latest VSCode. Guess I'll wait then :)

**Comment by andrewbranch** [comment] 2021-05-27 22:29
You can always try the nightly with https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next. Pretty confident this is just a duplicate of #39155 but please come back and correct me if that turns out not to be the case. Thanks!

**Closed** 2021-05-30 18:00 UTC
Labels: Duplicate

**Comment by silkfire** [comment] 2021-06-10 19:01
@andrewbranch Thank you, I can confirm that it's working in the latest VSCode version (May 2021, v1.57).

Is there a way to control the behavior based on the `.tsconfig`? I want my NodeJS code to insert the extension, but I don't want my frontend TypeScript files to do that (I import my own module imports without the file extension).

**Comment by andrewbranch** [comment] 2022-05-06 15:54
You’ll have to provide a repro

<img width="540" alt="image" src="https://user-images.githubusercontent.com/3277153/167168589-454c955b-deb7-4e9f-8048-8f3efd3b8a53.png">

**Comment by andrewbranch** [comment] 2022-05-06 16:13
Provided at #48991. This issue was about string literal completions; I can see the issue in that one is with codefixes.
