### ISSUE TITLE
Type inference for indexed array element

### ISSUE THREAD

**Issue by mhchem** [Microsoft/TypeScript#20301] opened 2017-11-28 10:44 UTC
**TypeScript Version:**  2.6.1

**Code**

```ts
/* EXAMPLE 1 */
var a: (number | undefined)[] = [1, 2, undefined, 4];
var b = a[2];
if (b) {
    b;  // number
}
if (a[2]) {
    var c = a[2];  // SHOULD be number BUT is number | undefined
}

/* EXAMPLE 2 */

function aa(a: (number | undefined)[]) {
    for (var i=0; i<a.length; i++) {
        if (a[i]) {
            var p = a[i]; // SHOULD be number BUT is number | undefined
        }
    }
}
```

**Comment by kitsonk** [comment] 2017-11-28 11:18
Part of #9998

(I thought there was something more specific to tracking array index accesses, but couldn't find it)

**Comment by mhegazy** [comment] 2017-11-28 17:59
Duplicate of https://github.com/Microsoft/TypeScript/issues/10530

**Closed** 2017-12-12 18:20 UTC
Labels: Duplicate
