### ISSUE TITLE
Type instantiation is excessively deep with styled-components 5.0

### ISSUE THREAD

**Issue by thany** [microsoft/TypeScript#37213] opened 2020-03-04 13:22 UTC
**TypeScript Version:**  3.8.3

**Search Terms:** Type instantiation is excessively deep

**Code**

```tsx
const Divider: React.FC<IDivider> = ({ text, ...rest }) => (
  <Base text={text} {...rest} role="separator">
    <Text>{text}</Text>
  </Base>
);
```
Remove `{...rest}` to get rid of the error.

**Expected behavior:**
No error. This worked before.

**Actual behavior:**
TS2589: Type instantiation is excessively deep and possibly infinite.

**Playground Link:** 
[Playground](http://www.typescriptlang.org/play/index.html?downlevelIteration=true&noUnusedLocals=true&noUnusedParameters=true&jsx=2#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwCwAUKJLHKjAJ4A2WAJnERLl23PgFpcJSADss0mKlqNGAegQJGiOABEsqXFGAAjPXBgALLGawAPQtBRxJ4CLPkA6TQhWNg8rFAEeFYAktrAAG7AvAFwAN6aKKgA-ABccADWWBwQBHAAUgDKABruIfKG0qjAuACiPCByCvQMcNZ2aWwwlQDmLQC+ygxqGq1IAEJoVlgNTXAA7sAWXdx+PShgYFzAfJ5jPgySVfCTqFYAvCs8vO68kQA8YZHRAQB8AAaJd6hbyBzpBB4NhabWQ2x60jESywIFQ6SMU22shaiQAZKlUiYCNAsAAaNEY5AEGCxBKtNpOVwk+TpMhKcltb6-f5wIxcCC4DIgimQaowYCudKULjIfkRLDctowCBgdJidwAVlskrglmAPXMMHSAEYwMDEm1FrwLDqAAymgCkKoRnJ6xAArtJeOlcPaoJR5ABhCDsqDcwbk9GYrDYyjxA1wEDIKA9PxiQwarVwAAcev9BNSRJJUHDDMj0djkJ4xPSqf15ID7xRh1c7DgABVbPBLiJru4fshpJ9yYDbDq4KaUPbpS0q0MRl4dM8YjnnDI5hZRXAPTP0J24DMYXNFss7lEZ1c1hstjsbl4Dkc6+F9wF0tg8DB3AAxT2Pa8vKCvOCXAAUcXaMC4nA7ggZQdb9AAlN+X4-ok9ynFYJJ2OccRITA-TxCB7hgehy4+lg5wAERnGA0aitAhGvBG9yNnYryoU2-T3CotEwFR5LMQh7EQdWtgsPAMRBPaXDwO+M4tEAA) doesn't actually make the error show. It's possible the playground still imports the (typings for) old styled-components, or some other magic.

**Related Issues:** 
Loads. But none pertaining to styled-components, and none with any clear workaround.

Please tell me how to *ignore* this error so that our project will at least build. Then we can focus on how to properly solve the error.

**Comment by thany** [comment] 2020-03-04 14:19
I've boiled it down to the use of `as?: keyof JSX.IntrinsicElements;` which is a union-type of 173 possible strings. So it becomes:
```as?: 'a' | 'abbr' | 'address' | 'area' | //etc```

I've narrowed this type by pulling it in locally in the module, and putting the resulting type literally in my code. I then reduced the number of possible strings until the error disappeared. That number is 39.

So my (cautious) conclusion is that typescript now imposes an arbitrary limit on 39 strings on a type like this. 40 strings will cause this error.

Please remove this arbitrary limit (and please refrain from re-introducing it in the future) as it is inhibiting the use of `keyof JSX.IntrinsicElements`.

In another project I'm doing stuff with typed Exif tag collections, and I fear the worst for that project as well. Because that too, will be having types with a large number of members, and `keyof`-ing that will likely result in the same problems. I think it's best to postpone upgrading to TS 3.8 until this issue is resolved.

**Comment by orta** [comment] 2020-03-04 16:19
This feels like a dupe of https://github.com/microsoft/TypeScript/issues/34933

**Comment by thany** [comment] 2020-03-05 09:14
I don't think it's a true duplicate. I read through that issue before opening this one. And like I said, there's no clea solution, and the situation is not identical. It's possible however, that the root cause is identical, but I have no way of knowing, at this point.

In all honesty, I do agree that it's similar.

**Comment by plastikfan** [comment] 2020-03-17 15:17
Please can somebody in the TS team document in general terms what this error means (and put the explanation on the TS website). It appears this is a long running issue, but without a proper explanation of what this error is, we can't work around it.

**Comment by thany** [comment] 2020-03-18 15:37
And it might be unaviodable if we use libraries that expose very large type definitions, like React and styled-components, and undoubtedly a couple more.

Good documentation about this issue will help for sure, but it's also hepful to solve the root cause. Especially the part of the error message that says "possibly infinite" feels like even the compiler doesn't know. And I'm pretty sure it's possible (at least in principle) to calculate if a type definition is truly infinite, versus just being very large and blindly being assumed "possibly infinite".

**Comment by AnyhowStep** [comment] 2020-03-18 20:10
Nope. Not possible in the general case. Halting problem.

**Comment by thany** [comment] 2020-03-24 10:14
Not possible, or don't know how to solve?

How do other languages deal with this problem?

**Comment by AnyhowStep** [comment] 2020-03-26 19:05
Not possible.

https://en.wikipedia.org/wiki/Halting_problem

> ... the halting problem is the problem of determining ... whether the program will finish running, or continue to run forever. Alan Turing proved ... that a general algorithm to solve the halting problem ... cannot exist.

Other languages just impose an arbitrary recursion limit. Like what TS is doing.

**Comment by thany** [comment] 2020-03-27 10:54
Well then it seems that for certain implementation with styled-components, a larger recursion limit is required.

I suppose this can be solved either hardcoded as it is currently, or by a configuration option of some kind.

**Comment by weswigham** [comment] 2020-04-13 21:55
Looks like we're alleviated this in the nightly~

**Closed by weswigham** 2020-04-13 21:55 UTC
Labels: Bug, Domain: Big Unions

**Comment by thany** [comment] 2020-04-22 09:28
@weswigham That's good news! 😎
Do you have a link to a PR or something, so I can take a look? I'm interested to see how this was resolved. Thanks!

**Comment by weswigham** [comment] 2020-04-22 10:00
I don't currently have the exact change on hand, but I expect our change to no longer attempt to instantiate unions of literal types is ultimately what fixed this (as we also use the "excessively deep and possibly infinite" error for very very wide instantiation chains, too).
