### ISSUE TITLE
Different behavior in type narrowing when using `let` instead of `const`

### ISSUE THREAD

**Issue by TommasoAmici** [microsoft/TypeScript#52567] opened 2023-02-02 11:13 UTC
# Bug Report

Typescript seems to produce different results when type narrowing a variable depending on whether the variable was initialized with `let` or `const`

### 🔎 Search Terms

type narrowing let const

### 🕗 Version & Regression Information

I tested this in the playground using the latest v4 releases (v4.9.4, v4.8.4, v4.7.4), I went back to v3 to make sure, and I tested the nightly, the behavior is consistent (consistently wrong, I think) between all versions

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhmYBLANiuAnAngfVJKALhgCIUBXAc0pJgB9SIBTOKWh8sAEyYDMkwTLjAC8MTj36CuAbgBQcpLxgAKBMjSZc+aDACEIsRL4ChAShgBvOTFswdsfiihMMQgOIYQ5AA4RRMADaZFQ0ADSMLGwRJLwoTAAeJAC6AHROLhgqlF6+ogB8MDnePqkCwBQ8EGqIqOjYeODQZmbyAL4K8bDqdVo4XcQh1OyRrCPGUkIBE6ayCkqqPZoNXfqG4twm0hbWdvZNjqiZHrl+AcEUwzHMYzFxiSnpR67ZpwVFp2WIlUzVS-W4LotdpAA)

### 💻 Code

```ts
const ancillary_const: "lugg" | "seat" | undefined = undefined;

if (ancillary_const !== undefined) {
	// works as intended
    const filteredGroups = ["lugg", "seat", "flex"].filter(group => group.includes(ancillary_const));
}

let ancillary_let: "lugg" | "seat" | undefined = undefined;

if (ancillary_let !== undefined) {
	// complains that ancillary_let is undefined
    const filteredGroups = ["lugg", "seat", "flex"].filter(group => group.includes(ancillary_let));
}
```

### 🙁 Actual behavior

Using `const` instead of `let` produces a different result when narrowing types

### 🙂 Expected behavior

No difference in type narrowing when using variables initialized with `let`

**Comment by MartinJohns** [comment] 2023-02-02 11:17
Duplicate of #9998.

**Closed** 2023-02-04 18:00 UTC
Labels: Duplicate
