### ISSUE TITLE
Assigning to `unknown` / `{}` doesn't change its inferred type

### ISSUE THREAD

**Issue by rChaoz** [microsoft/TypeScript#60092] opened 2024-09-28 18:47 UTC
### 🔎 Search Terms

type inference, fail, unknown, {}, assign, inferred type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.0-dev.20240928#code/GYVwdgxgLglg9mABFApgZygRgBQA8Bci4A1mHAO5gCUiA3gFCJOK6IC8iARGnALbpQATjDABzTo2a4AdABsUYqAAt6AX3r1QkWAmQCATHkK1VNBsxbsuPfhmFiJFmfMUr1m8NHhJUGAMxGiHYioogAPohgILwARiiC4YgxcHDyAIZIEVGysongACYowCIo+YlwMQBWKNCJaACesamJANoAuokAbnAwZVkonfGJMTCiIlBmkkysHNx8AvbiUyxyCqLKakA

### 💻 Code

```ts
function test1(x: unknown) {
    x = "somestring"
    x.length // error: Object is of type unknown
}

function test2(x: {}) {
    x = "somestring"
    x.length // error: Property 'length' does not exist on type '{}'
}

function test3(x: string | number | boolean | null | undefined | object | symbol | [] | void | never | bigint) {
    x = "somestring"
    x.length // no error, x is inferred as string
}
```

### 🙁 Actual behavior

It doesn't change inferred type of `x` when it is assigned.

### 🙂 Expected behavior

It should.

**Comment by MartinJohns** [comment] 2024-09-28 20:11
Duplicate of #43584 / #27706.

**Closed** 2024-10-04 01:32 UTC
Labels: Duplicate
