### ISSUE TITLE
Smarter String includes/endsWith/startsWith using template literal type predicates

### ISSUE THREAD

**Issue by btoo** [microsoft/TypeScript#58152] opened 2024-04-11 15:34 UTC
### ⚙ Compilation target

ES2015

### ⚙ Library

ES2015.Core

### Missing / Incorrect Definition

```diff
     /**
      * Returns true if searchString appears as a substring of the result of converting this
      * object to a String, at one or more positions that are
      * greater than or equal to position; otherwise, returns false.
      * @param searchString search string
      * @param position If position is undefined, 0 is assumed, so as to search all of the String.
      */
-    includes(searchString: string, position?: number): boolean;
+    includes<SearchString extends string>(searchString: SearchString, position?: number): this is `${string}${SearchString}${string}`
```

```diff
     /**
      * Returns true if the sequence of elements of searchString converted to a String is the
      * same as the corresponding elements of this object (converted to a String) starting at
      * endPosition – length(this). Otherwise returns false.
      */
-    endsWith(searchString: string, endPosition?: number): boolean;
+    endsWith<SearchString extends string>(searchString: SearchString): this is `${string}${SearchString}`
+    endsWith<SearchString extends string>(searchString: SearchString, endPosition: number): this is `${string}${SearchString}${string}`
```

```diff
     /**
      * Returns true if the sequence of elements of searchString converted to a String is the
      * same as the corresponding elements of this object (converted to a String) starting at
      * position. Otherwise returns false.
      */
-    startsWith(searchString: string, position?: number): boolean;
+    startsWith<SearchString extends string>(searchString: SearchString): this is `${SearchString}${string}`
+    startsWith<SearchString extends string>(searchString: SearchString, position: number): this is `${string}${SearchString}${string}`
```

### Sample Code

```TypeScript
declare const s: string

const searchString = 'searchString'

if (s.includes(searchString)) {
  s
  // ^? const s: `${string}searchString${string}`
}

if (s.endsWith(searchString)) {
  s
  // ^? const s: `${string}searchString`
}

if (s.endsWith(searchString, 0)) {
  s
  // ^? const s: `${string}searchString${string}`
}

if (s.startsWith(searchString)) {
  s
  // ^? const s: `searchString${string}`
}

if (s.startsWith(searchString, 0)) {
  s
  // ^? const s: `${string}searchString${string}`
}
```

[playground link](https://www.typescriptlang.org/play?ts=5.5.0-dev.20240411&ssl=28&ssc=1&pln=56&pc=1#code/JYOwLgpgTgZghgYwgAgMpiqA5sg3gKGSOQHoAqMw45M5AJQjAFcoQBnZDJlYGZNiHCgIAFukwgccAA7TBUDnEX8mAIzYZsyAPZ8wIlFAhsmAGzA6+CbSABu0MFv3A2VYrW2qAVhAQWw2shwaJqSADRBFjYo2lDIALaxKNLabMCONhz6cBZCEG5EtFhGOdCcInAgOnEQAI5McKacgSlpGSAA3Dr60ADuLhARRsysHPCmAgB0BTTIAALSQnDx-PKi4loCQqL8oVgztAtLK63pwDbIAJJ8p+3ILshMIAAmEDCgEM8RAAz3imwmeKfCJsQJKZqrbYiIKmJq6cooDaSabUGgkAqgBCmJivNgAHlQazEe2QEAAHpAXhwNBIsAA+AAUW2ExNpAC40ESkVgIrdziAAPwckBMeKqaAASg5zg4DwABgASXA07AAXyVhKh3PVyr2qrl+AK5EoqNoDBG7E4UG49z0BlW9QgICQllJpggQPAHHhzPWJOsdgcnwhwW5fwRB34yxQ4J6yGsUCMbBSLy0EHdnrA3rtD08Pj8yAZAfsUEgzxDIVpEt2QkckkikadzwACqkzhdAMgEyHdkn0DJlEsmyAA8j0oP0BMhhixLeMpgd0dQm2wAOrpEQErkk8mU57UvaM32s7AczUs7lS8oPeVKlWSHVnv20-UFZdr-SbrXbinL3a0w9buynJfrSERNq2bT8sKorilAl4yuGiq6s+GqAWqt56gaRoUJG5ozlk1o8HaKACI6zoxHw6Yek6WaukeYbFkG5YBEElZaA8PSRmw0ZBFk9oJkmKbPGmGY0dmV7et4vgWEWNglmWFYXjWpZaDkkZ8jYQ6jgY44DFOjD4cgc4QCi1BkIuxAaLWq7rp+57fru+7-kyaGSKerlYPBIjXhwSGPse94Yc+BrUFZpY2R+-lhjuv53vSLkgSewH2aByAaSA0FipK0rebKvlBehuBRXqBX3gaqqGq8WJ5PGmQWGwHJxYaAYaJCKVaAAvMgADk9F7N1hq8IWbCTJi2K4gl7WSBK1YEEQrhECQJDIAAegK+AVfgQ1MpMb7rpNT7YDNeBUAtpDLWtG2DXwO17X2fWpd8x1zfwVBLat62bdtI1hVm74iAdAWebNp1vRdn3XcNky-RFAMPdgPzPaDi3g1dQA)

### Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

**Comment by MartinJohns** [comment] 2024-04-11 15:40
Duplicate of #46958 (and others).

**Comment by btoo** [comment] 2024-04-11 16:10
w.r.t. https://github.com/microsoft/TypeScript/issues/46958#issuecomment-983054296

> Changing a function from not-overloaded to overloaded has fairly pervasive effects in areas like contextual typing, generic inference, and how exactly it can be invoked when the method operand is a union

fwiw the `includes` here still isn't an overload

I believe the `startsWidth`/`endsWIth` need not be either, if that's the blocker, e.g.
```ts
    startsWith<SearchString extends string, Position extends number>(searchString: SearchString, position?: Position):
      this is typeof position extends number
        ? `${string}${SearchString}${string}`
        : `${SearchString}${string}`
```

**Closed** 2024-04-14 01:33 UTC
Labels: Duplicate
