### ISSUE TITLE
Wrong behaviour with decorators (Property 'xxx' is used before its initialization (2729))

### ISSUE THREAD

**Issue by victorgarciaesgi** [microsoft/TypeScript#40259] opened 2020-08-26 09:44 UTC
**TypeScript Version:**  4.02

- ts 2729 vue
- typescript property is used before declaration decorators

**Code**

```ts
@Component
export default class StepViews extends Vue {
  @Prop() steps!: Step[];
  @Prop() initialStep?: number;

  public step = this.initialStep ?? 0;
//               ^^^^^^^^^^^^^^ Error: Property 'initialStep' is used before its initialization
}
```

**Expected behavior:**

Typescript doesn't throws an error because this is valid Vue component

**Actual behavior:**

Take for exemple this valid Vue component using vue-property-decorator.
This code is valid in Vue thanks to the decorators, and the props will be initialized, but typescript think I want to use it before initialization. How can I tell Typescript that I know better and disable this error?

I know if you know Vue you will tell me just put this in a `created` or `mounted` hook. It's fine for a simple type, but it's a hassle for more complex types like big form generators where I want Typescript to infer the type for me.

**Comment by victorgarciaesgi** [comment] 2020-08-26 09:49
For now the workaround I found is 

```ts
@Component
export default class StepViews extends Vue {
  @Prop() steps!: Step[];
  @Prop() initialStep?: number = undefined;

  public step = this.initialStep ?? 0;
}
```

Default values are normaly put inside the decorator `@Prop({default: 0}) initialStep?`

**Comment by jgbpercy** [comment] 2020-08-27 08:11
I don't know how Vue treats decorators and whether the framework has behavior that means `@Prop` will set `initialStep` at construction time, but if that's the case then TypeScript doesn't know about it or take it into account (and that's not a bug).

As far as TS is concerned, at the point `public step = this.initialStep ?? 0;` runs, `initialStep` cannot be initialized, making that line indistinguishable from `public initialStep = 0` and your code indistinguishable from a bug/mistake.

**Comment by victorgarciaesgi** [comment] 2020-08-27 13:30
@jgbpercy Yep Vue's `@Prop` decorator will init `initialStep` at construction time. Typescript can't know it so I wondered if there is a way to tell Typescript that it will be set before?

**Comment by RyanCavanaugh** [comment] 2020-09-09 16:07
If this is always initialized by the `@Prop`, then it shouldn't be marked as optional. Probably what you want is
```ts
@Component
export default class StepViews extends Vue {
  @Prop() steps!: Step[];
  @Prop() initialStep!: number | undefined;

  public step = this.initialStep ?? 0;
}
```

**Closed** 2020-09-11 20:00 UTC
Labels: Working as Intended
