### ISSUE TITLE
Discriminated union isn't working on class property that implements interface

### ISSUE THREAD

**Issue by distinctdan** [Microsoft/TypeScript#29178] opened 2018-12-27 23:25 UTC
**TypeScript Version:**  3.2.2

**Search Terms:** Discriminated unions

**Code**
```
enum WinCondition {
    KillTarget = 'KillTarget',
    SizeGoal = 'SizeGoal',
}

interface IWinConditionKillTarget {
    type: WinCondition.KillTarget;
    targetHash: string;
}

interface IWinConditionSizeGoal {
    type: WinCondition.SizeGoal;
    goal: number;
}

type IWinCondition = IWinConditionKillTarget | IWinConditionSizeGoal

// ---------- Works ----------
var conditions: IWinCondition[] = [];
conditions = [{
    type: WinCondition.SizeGoal,
    goal: 75,
}];

interface ILevel {
    winConditions: IWinCondition[];
}

// ---------- Doesn't work ----------
class Level_01 implements ILevel {
    public winConditions = [{
        type: WinCondition.SizeGoal,
        goal: 75,
    }];
}
```

**Expected behavior:**
This should work
**Actual behavior:**
The compiler throws the error "Types of property 'type' are incompatible. Type 'WinCondition' is not assignable to type 'WinCondition.SizeGoal'."
**Playground Link:** 
http://www.typescriptlang.org/play/index.html#src=enum%20WinCondition%20%7B%0D%0A%20%20%20%20KillTarget%20%3D%20'KillTarget'%2C%0D%0A%20%20%20%20SizeGoal%20%3D%20'SizeGoal'%2C%0D%0A%7D%0D%0A%0D%0Ainterface%20IWinConditionKillTarget%20%7B%0D%0A%20%20%20%20type%3A%20WinCondition.KillTarget%3B%0D%0A%20%20%20%20targetHash%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20IWinConditionSizeGoal%20%7B%0D%0A%20%20%20%20type%3A%20WinCondition.SizeGoal%3B%0D%0A%20%20%20%20goal%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Atype%20IWinCondition%20%3D%20IWinConditionKillTarget%20%7C%20IWinConditionSizeGoal%0D%0A%0D%0A%2F%2F%20----------%20Works%20----------%0D%0Avar%20conditions%3A%20IWinCondition%5B%5D%20%3D%20%5B%5D%3B%0D%0Aconditions%20%3D%20%5B%7B%0D%0A%20%20%20%20type%3A%20WinCondition.SizeGoal%2C%0D%0A%20%20%20%20goal%3A%2075%2C%0D%0A%7D%5D%3B%0D%0A%0D%0Ainterface%20ILevel%20%7B%0D%0A%20%20%20%20winConditions%3A%20IWinCondition%5B%5D%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20----------%20Doesn't%20work%20----------%0D%0Aclass%20Level_01%20implements%20ILevel%20%7B%0D%0A%20%20%20%20public%20winConditions%20%3D%20%5B%7B%0D%0A%20%20%20%20%20%20%20%20type%3A%20WinCondition.SizeGoal%2C%0D%0A%20%20%20%20%20%20%20%20goal%3A%2075%2C%0D%0A%20%20%20%20%7D%5D%3B%0D%0A%7D

**Related Issues:**

**Comment by Nathan-Fenner** [comment] 2018-12-28 01:02
Here's a reduced example, and an explanation for the behavior:

http://www.typescriptlang.org/play/index.html#src=%0D%0Ainterface%20Constraint%20%7B%0D%0A%20%20%20%20val%3A%2042%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Example%20implements%20Constraint%20%7B%0D%0A%20%20%20%20public%20val%20%3D%2042%3B%0D%0A%7D%0D%0A

**Expected Behavior:**

* since `val` is constrained by the `Constraint` interface, we should automatically narrow it to what the interface expects

**Actual Behavior:**

* `implements`/`extends` constraints *don't* help narrow fields; assignability is only checked *after* the type of the field is inferred.

**Potential TypeScript Change:**

* Use types from `implements`/`extends` super types as hints to narrow field initializations in classes

(This is probably reverse-compatible)

**Workaround:**

* add explicit type annotation to the field (e.g. in your original example):

```ts
    public winConditions: IWinCondition[] = [{
        type: WinCondition.SizeGoal,
        goal: 75,
    }];
```

**Comment by ahejlsberg** [comment] 2018-12-28 17:10
Duplicate of #3667.

**Closed** 2018-12-30 18:00 UTC
Labels: Duplicate
