### ISSUE TITLE
Union Types in promise chain not correctly handled

### ISSUE THREAD

**Issue by sliwalker** [Microsoft/TypeScript#14669] opened 2017-03-15 13:39 UTC
**TypeScript Version:**  2.2.1 (IntelliJ IDE through Node.js/NPM)

**Code**

```ts
import * as angular from "angular";

interface AnInterface {
    initialFunctionToCall(stringParameter: string): angular.IPromise<string>;
}
export default AnInterface;

class SomeService implements AnInterface {

    private someStringValue = '';

    constructor(private $q: angular.IQService,
                private someOldSchoolCallbackCordovaPlugin: any) {

    }

    public initialFunctionToCall(stringParameter: string): angular.IPromise<string> {

        return this.doSomethingFirst() // here the error starts
            .then(this.getSomeStringValue)
            .then((someStringValue: string) => {
                this.someStringValue = someStringValue;
                return this.$q.resolve();
            })
            .then(() => {
                return this.doAnotherThing(stringParameter)
            })
            .then(() => {
                return this.$q.resolve(this.userGID);
            });
    }


    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // PRIVATES
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    private doSomethingFirst(): angular.IPromise<void> | angular.IPromise<string> {

        let deferred = this.$q.defer();

        this.someOldSchoolCallbackCordovaPlugin.doSomethingFirst(() => {
                deferred.resolve();
            },
            (error: string) => {
                deferred.reject(error);
            }
        );

        return deferred.promise;
    }

    private getSomeStringValue(): angular.IPromise<string> {

        let deferred = this.$q.defer();

        this.someOldSchoolCallbackCordovaPlugin.getSomeStringValue((someString: string) => {
                deferred.resolve(someString)
            },
            (error: string) => {
                deferred.reject(error);
            }
        );

        return deferred.promise;
    }

    private doAnotherThing(stringParameter: string): angular.IPromise<void> | angular.IPromise<string> {

        let deferred = this.$q.defer();

        this.someOldSchoolCallbackCordovaPlugin.doAnotherThing(() => {
                deferred.resolve();
            },
            (error: string) => {
                deferred.reject(error);
            },
            stringParameter
        );

        return deferred.promise;
    }
}

```

**Expected behavior:**
The promise chain in "initialFunctionToCall" should work like this. TypeScript should not complain.
My expectation is that if I defined union return types like `angular.IPromise<void> | angular.IPromise<string>` that the relevant "then()" of a call to a function with that union type accepts that even if other functions calls in that chain have a different return type (such as "getSomeStringValue()" in my example.

**Actual behavior:**
TypeScript complains with error: `TS2349:Cannot invoke an expression whose type lacks a call signature. Type '{<TResult>(successCallback: (promiseValue: string) => TResult | IPromise<TResult>, errorCallback...' has no compatible call signatures.`

If you change the return type of all participating functions of that promise chain (doSomethingFirst(), getSomeStringValue(), doAnotherThing()) to `angular.IPromise<any>` it works with no problems.

**Comment by dylanmcdiarmid** [comment] 2017-08-08 03:16
Here's a simpler demonstration of this opaque error (in 2.4.2).

```typescript
function foo(): Promise<string> | Promise<null> {
  if (1) {
    return Promise.resolve(null)
  }
  return Promise.resolve('ok')
}

function callfoo() {
  foo().then((val) => {})
}
```

```
Cannot invoke an expression whose type lacks a call signature. Type '(<TResult1 = string, TResult2 = never>(onfulfilled?: ((value: string) => TResult1 | PromiseLike<T...' has no compatible call signatures.'
```

For trivial cases, this can be fixed with a return type of `Promise<string | null>`, but if you are importing something like a type aliased promise from an external library that you'd like to maybe return, it becomes very inconvenient.

**Comment by aluanhaddad** [comment] 2017-08-08 04:20
The error occurs because there is no way to differentiate from the caller which overload of `then` you are using.

Change `Promise<string> | Promise<null>` to `Promise<string | null>` to resolve the error.

The OP suffers from the same exact issue as well (modulo critical bugs).

**Comment by dylanmcdiarmid** [comment] 2017-08-08 04:43
Thanks @aluanhaddad , good to know the cause! For anyone not particularly familiar with the compiler and Promise implementation details, that is a really difficult error to understand. It's definitely something that seems like it *should* work.

For the curious on what 'overloading' means in this case, here is a code snippet that reproduces this same error, with all of the types present
```typescript
interface IFoo<T> {
  foo(v: T): null
}

function makeFoo<T>(v: T): IFoo<T> {
  return {
    foo() {
      console.log(v)
      return null
    }
  }
}

function bar(): IFoo<string> | IFoo<null> {
  if (1) {
    return makeFoo(null)
  }
  return makeFoo('ok')
}

function callbar() {
  bar().foo()
}
```

**Comment by mhegazy** [comment] 2017-10-25 22:39
Another manifestation of https://github.com/Microsoft/TypeScript/issues/7294

**Comment by mhegazy** [comment] 2017-11-09 21:24
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-11-09 21:24 UTC
Labels: Duplicate
