### ISSUE TITLE
wrong condition check after await

### ISSUE THREAD

**Issue by fy0** [microsoft/TypeScript#42295] opened 2021-01-12 16:30 UTC
# Bug Report

### 🔎 Search Terms

typescript enum no overleap.

typescript enum async no overleap.

typescript enum no overleap with async.

typescript enum no overleap promise

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions _4.1.3_ and _nightly(2020/01/12)__
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _enum__
- I was unable to test this on prior versions because _exists on nightly version_

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210112#code/FAUwdgrgtgBAggUUrA3sG8YF4YEYA06MAQtjAEzAC+woAHgA4D2ATgC4wDGANgIYDO-TGgy8yiZADo4Ablqj+ATzCcYAMwgqAFAEoYIjDDYALAJb9JYnBOjS5hrkzD8OasgOWrd2AHz6iDibmluJItsT2hjQOvADuvKauupEYpm5aQRZWWNZhUJLEegYOnE78TNwgktxMAOZaAMxNOikw0W3UtPTM7Fx8gvDk-qJkuHJEHirqmpzexUZmWaOtAPQrMHEJHFqTXnpYfvNrhpkhOOSr61QtATBpMBmLZzkURbcYpc4VVTX1TQ03BztGg0IA)

### 💻 Code

```ts

enum AEnum {
  A = 1,
  B = 2
}

export class A {
  a = AEnum.A;

  async func() {
    this.a = AEnum.A;
    const f = async () => {
      this.a = AEnum.B;
    }
    await f();
    if (this.a === AEnum.B) {  // Error: This condition will always return 'false' since the types 'AEnum.A' and 'AEnum.B' have no overlap.(2367)
      console.log(333);
    }
  }
}
```

### 🙁 Actual behavior

Error

### 🙂 Expected behavior

Success

**Comment by MartinJohns** [comment] 2021-01-12 17:00
Another duplicate of #9998.

**Closed** 2021-01-15 18:00 UTC
Labels: Duplicate
