### ISSUE TITLE
Incorrect return type when using [Array.prototype.map] + [callback function with overloaded signature and using shorthand]

### ISSUE THREAD

**Issue by maple5233** [microsoft/TypeScript#48831] opened 2022-04-25 07:33 UTC
# Bug Report

### 🔎 Search Terms

is:issue array callback function overload 

### 🕗 Version & Regression Information
- This is a crash
- This changed between versions ? and 4.6.2
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about overload
- I was unable to test this on prior versions because it is the latest version

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/JYOwLgpgTgZghgYwgAgIImAWzgG2QbwChlkQ5MIAuZAZzClAHNCBfQ0SWRFAYTjGQQAHpBAATGmgzY8REjQD2AV3HU6DEMzaEYKhGGAKQyABZxxOCOiy4AFOZs5qfMAEpn-HXoNHT5sZbWMvbSuNRBuO5Sjl4g+obGZhZWoTghjh4CAD7RMq4ExMjAMMi2AOSKKmJlRcYOeQUkJFAQYEpQdamFbM2t7Z0x2mIQCDhwLciWAoytLtS2+QC8AHzILoQIRnTICPzIi8gzYC4LhIQA9OfILTRKOGCZG1sCN3cCB0kBKY62u25nw1G4xQUx2-AADI8LlcAO4mCDGJQ0EHAbYw4BgEzIbAABwANLQTAooAIYMTMASwABPHEoBQlHCoh65XAAbQAuoIhLT9BAxJkOU8QNtGdsDqy-uD2QA6XG2T6BVKuM6XZBwhHIJEotEYrG4gm6HB4MlQCnIam05D0yZMgWc4Q8yD8tb8QWbYUCUVgABM+2QEohMrlv34AElIJglqs5DtnmD3n5khE0n9wxBI4UWm0OvHWMrCEA)

### 💻 Code

```ts
interface Animal {
  name: string
}
interface Cat extends Animal {
  sound: string
}

function handleAnimal(animal: Cat): Cat
function handleAnimal(animal: Animal): Animal
function handleAnimal(animal: Cat | Animal) {
  if ('sound' in animal) {
    return animal
  }
  return animal
}

declare let cat0: Cat

// when use in Array.prototype.map with shorthand callback, it is not ok
// typeof list2 will be Animal[]
const list = [cat0].map(handleAnimal)

// when use in Array.prototype.map with not-shorthand callback, it is ok
// typeof list2 will be Cat[]
const list2 = [cat0].map((catItem) => {
  const cat = handleAnimal(catItem)
  return cat
})
```

### 🙁 Actual behavior

```ts
const list = [cat0].map(handleAnimal) // type of list:  Animal[]

```

### 🙂 Expected behavior

```ts
const list = [cat0].map(handleAnimal) // type of list:  Cat[]
```

**Comment by MartinJohns** [comment] 2022-04-25 08:13
Duplicate of #47571. Used search terms: `array map overload in:title`

**Closed** 2022-04-28 18:00 UTC
Labels: Duplicate
