### ISSUE TITLE
Narrowing on obj.prop doesn't propagate to obj

### ISSUE THREAD

**Issue by kevinjwz** [microsoft/TypeScript#57290] opened 2024-02-04 21:12 UTC
### 🔎 Search Terms

narrowing intersection property type guard assertion

### 🕗 Version & Regression Information

occurs on:
5.3.3
5.4.0-dev.20240204

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.0-dev.20240204#code/JYOwLgpgTgZghgYwgAgILIN4Chm+QDwH4AuZEAVwFsAjaAbiwF8tRJZEUAhZCfSEACYBnNJhx58pCjXpMsWGORAIwwAPYhkMABRxSqAJRi8yYDGTawATwAOENebgA6fMgC8H5ACJptKF4NsExNyIQgAOSo-XRcDOmQAegTkNQBrcWDkUIhOXTjE5OgoNSgM5GZmBSUVdU1s3OpSTiNsOSrlVQ0ssMiZKG1JMijoQPlKpNNwaDCaroA3adqsaztkAGF3YwkSIb6GZhWUABFNjYAyLdxB31lKxQ7arQBmbQRSNZayswtDh2QEFzuTw+Yb+UaZXDZXrRAH4fITNJlEJhI6veGFKDFUomCrye6zOoo7QCUhHT5yIA

### 💻 Code

```ts
interface A {
    x?: number;
}
interface B extends A {
    x: number;
}

function f(a: A) {
    if (typeof a.x === "number"){
        useNumber(a.x); // ok
        useB(a); // error
    }
}

function useB(b: B) {}

function useNumber(x: number) {}
```

### 🙁 Actual behavior

Cannot assign `a` to parameter of type `B`. It seems type narrowing works independently on `a.x` and `a`.

### 🙂 Expected behavior

`a` should be assignable to parameter of type `B`.

**Comment by MartinJohns** [comment] 2024-02-04 21:17
Duplicate of #42384 and many many others.

**Comment by fatcerberus** [comment] 2024-02-04 21:19
oops @MartinJohns beat me to it this time

**Closed** 2024-02-08 01:24 UTC
Labels: Duplicate
