### ISSUE TITLE
Feature request: type-only members

### ISSUE THREAD

**Issue by magnushiie** [Microsoft/TypeScript#18556] opened 2017-09-18 19:35 UTC
The following pattern allows one to define run-time structures that also have a compile-time representation:
```ts
type FieldMetadata = {}; // omitted;
type Field<T> = {
  instance: T;
  metadata: FieldMetadata;
};
  
export type QuerySpec<D extends {[P in keyof D]: Field<any>}> = {[P in keyof D]: D[P]["instance"]};
```

However, because `Field<T>` instances would be effectively singletons, the instance field is never going to be filled in because it's only used for compile-time type checking/inference.

Therefore, I propose to have "type-only" members, e.g.:

### readonly inspiration
```ts
type Field<T> = {
  typeonly instance: T;
  metadata: FieldMetadata;
};
```
This would mean that accessing the `instance` member in an expression context would result in an error (only type indexing is allowed).

### member types
```ts
type Field<T> = {
  type InstanceType = T;
  metadata: FieldMetadata;
};
```

**Comment by mhegazy** [comment] 2017-09-18 19:44
why not just use a name that does not show up in completion list, e.g. something that starts with a non-identifier character:

```ts
type Field<T> = {
	"#instance": T;
	metadata: FieldMetadata;
};
```

**Comment by magnushiie** [comment] 2017-09-18 19:50
This would invent non-standard syntax for something that would fool the IDE but not the compiler, `field["#instance"]` would still be a valid expression providing a valid `T`.

Also, consider if TypeScript ever added a definite assignment rule - then this would have to be hacked around with `undefined as any as T` in the constructor.

**Comment by magnushiie** [comment] 2017-09-18 19:58
To clarify - there is no valid value for the `instance` field of `Field<T>` - as `Field<T>` is singleton, some choices of the `instance` field could only be an `undefined` unsafely cast to `T` or some random example/sentinel value of `T`.

So instead of 
```ts
const PersonNameField = new Field<string>({fieldName: "name"});
```
one would have to use
```ts
const PersonNameField = new Field<string>({fieldName: "name", instance: "John Smith"});
```
where the value "John Smith" would never be actually used.

**Comment by mhegazy** [comment] 2017-09-18 20:05
can you elaborate on the issue. not sure why you need to pass in an extra parameter?

**Comment by magnushiie** [comment] 2017-09-18 20:40
The idea is to define a schema using expressions, not types, in a DSL. This way the types are inferred and there is no repetition. Also, sometimes the schema might contain more specific information than the TypeScript type system (e.g. field lengths, number types, etc).

E.g.
```ts
namespace framework {
  type Field<T> = {
    name: string;
    typeName: string;
    instance: T;
  };
  type FieldSchema<D> = {[P in keyof D]: Field<any>};
  type Schema<D extends FieldSchema<D>> = { fieldSchema: D };
  export const makeSchema = <D extends FieldSchema<D>>(fieldSchema: D): Schema<D> => ({ fieldSchema: fieldSchema });
  type FieldSchemaOfSchema<D extends FieldSchema<D>, S extends Schema<D>> = S["fieldSchema"];
  type InstanceTypeOfField<F extends Field<any>> = F["instance"];
  export type SchemaType<D extends FieldSchema<D>, S extends Schema<D>> = {[P in keyof FieldSchemaOfSchema<D, S>]: InstanceTypeOfField<FieldSchemaOfSchema<D, S>[P]>};
  export const StringField: (name: string) => Field<string> = name => ({ name, instance: undefined as any as string, typeName: "string" });
  export const IntField: (name: string) => Field<number> = name => ({ name, instance: undefined as any as number, typeName: "string" });
}
namespace schema {
  export const PersonSchema = framework.makeSchema({
    firstName: framework.StringField("firstName"),
    lastName: framework.StringField("lastName"),
    age: framework.IntField("age"),
  });
  export type Person = framework.SchemaType<typeof PersonSchema.fieldSchema, typeof PersonSchema>;
}

namespace code {
  console.log(JSON.stringify(schema.PersonSchema));
  const person: schema.Person = {
    firstName: "Magnus",
    lastName: "Hiie",
    age: 40 // "", // Types of property 'age' are incompatible. Type 'string' is not assignable to type 'number'.
  };
  console.log(person);
}
```

produces:
```json
{"fieldSchema":{"firstName":{"name":"firstName","typeName":"string"},"lastName":{"name":"lastName","typeName":"string"},"age":{"name":"age","typeName":"string"}}}
{"firstName":"Magnus","lastName":"Hiie","age":40}
```

**Comment by jcalz** [comment] 2017-09-19 02:08
Is this related to or a duplicate of #17588?

**Comment by jcalz** [comment] 2017-09-19 02:17
I agree that it would be nice to do this without adding a phantom property which is not intended to exist at runtime.  Currently if you ever need an instance of the augmented type, you either have to make the property optional (which dilutes `T` into `T | undefined`), or make it required and add a dummy `void 0 as any` value (which becomes obnoxious for object literals).

**Comment by magnushiie** [comment] 2017-09-19 11:43
> Is this related to or a duplicate of #17588?

Yes, thank you. And #9889 which it links to.

**Comment by gcanti** [comment] 2017-09-19 11:50
> The idea is to define a schema using expressions, not types, in a DSL

@magnushiie you may want to take a look at

- https://github.com/pelotom/runtypes
- https://github.com/gcanti/io-ts

**Comment by magnushiie** [comment] 2017-09-19 12:18
Thanks, @gcanti, I will take a look. My use case is actually a little bit more specific, but maybe I can get some ideas.

**Comment by magnushiie** [comment] 2017-09-19 12:26
Both of these projects also have these "phantom" properties:

https://github.com/pelotom/runtypes has [`_falseWitness`](https://github.com/pelotom/runtypes/blob/f21e53caa08939d0e1f848b1d7e380aeeef48523/src/runtype.ts#L49)

https://github.com/gcanti/io-ts has [`_A`](https://github.com/gcanti/io-ts/blob/master/src/index.ts#L76)

**Comment by DanielRosenwasser** [comment] 2017-09-19 22:58
This *might* be a good case for [associated types](https://doc.rust-lang.org/book/first-edition/associated-types.html) (?)

**Comment by magnushiie** [comment] 2017-11-17 22:03
This issue is especially bad where the false witnesses make the types unnecessarily covariant on the generic argument, whereas a type-only member or typedef would not impose covariance on the type.

E.g. the following interface is now invariant on T:
```ts
interface DoSomethingWith<T> {
  public readonly whatCanIDoSomethingWithFalseWitness: T;
  public doSomething(something: T) {
  }
}
```

**Comment by mhegazy** [comment] 2018-07-17 22:44
Duplicate of https://github.com/Microsoft/TypeScript/issues/17588

**Closed** 2018-07-27 23:15 UTC
Labels: Duplicate
