### ISSUE TITLE
Smarter type narrowing

### ISSUE THREAD

**Issue by samchan0221** [microsoft/TypeScript#51348] opened 2022-10-29 07:46 UTC
## ⭐ Suggestion
- Is it possible to have a type in an control flow narrowed without itself being a union type?
```ts
interface Life {
    isMessedUp: boolean;
    difficulty: "hard" | "medium" | "easy";
}

interface MessedUp {
    isMessedUp: true;
}

function laughAt(messedUp: MessedUp){}

const myLife: Life = null as any;

if (myLife.isMessedUp) {
    // Argument of type 'Life' is not assignable to parameter of type 'MessedUp'.
    // type of myLife is still Life, but it could've been {
    //     isMessedUp: false;
    //     difficulty: "hard" | "medium" | "easy";
    // }
    laughAt(myLife);
}
```

## 💻 Use Cases
- Having this possible will help saving many lines of code of strange type and type guard
- Currently in this case I'm using type guard (which incur runtime cost) or union type (which makes code unmaintainable)
- Union type alternative (it is obviously not scalable)
```ts
type LifeUnion = {
    isMessedUp: true,
    difficulty: "hard",
} | {
    isMessedUp: true,
    difficulty: "medium",
} | {
    isMessedUp: true,
    difficulty: "easy",
} | {
    isMessedUp: false,
    difficulty: "hard",
} | {
    isMessedUp: false,
    difficulty: "medium",
} | {
    isMessedUp: false,
    difficulty: "easy",
}

interface MessedUp {
    isMessedUp: true;
}

function laughAt(messedUp: MessedUp){}

const myLifeUnion: LifeUnion = null as any;

if (myLifeUnion.isMessedUp) {
    laughAt(myLifeUnion);
}
```
- `Experimental` type, I cannot come up with a nice name for it
```ts
type Experimental<K extends string, V extends any[], Prev extends {} = {}> = 
    V extends [infer First extends any] ? 
    ({[key in K]: First} & Prev) :
    V extends [infer First extends any, ...infer Rest extends any[]] ?
    (({[key in K]:First} & Prev) | Experimental<K, Rest, Prev>) :
    Prev;

type LifeExperimental = Experimental<"difficulty", ["hard","medium","easy"], 
                        Experimental<"isMessedUp", [true, false]>>;

interface MessedUp {
    isMessedUp: true;
}

function laughAt(messedUp: MessedUp){}

const myLifeExperimental: LifeExperimental = null as any;

if (myLifeExperimental.isMessedUp) {
    laughAt(myLifeExperimental);
}
```

**Comment by MartinJohns** [comment] 2022-10-29 08:35
Your suggestion would be unsound, because object types are not sealed. This would be a valid `MessedUp` type with `isMessedUp` set to `true`, but **not** a valid `Life`.

```typescript
const obj = {
    isMessedUp: true,
    difficulty: 1
} as const;
const asType: MessedUp = obj;
```

**Comment by jcalz** [comment] 2022-10-29 14:10
Duplicate of #42384

**Comment by DanielRosenwasser** [comment] 2022-10-30 07:53
I would say there's a few aspects of this.

First, trying to associate a value with an appropriate named type based on narrowing logic would be prohibitively expensive (and *probably* undecidable), and has some pitfalls that @MartinJohns kind of alludes to.

Closer to what you might want is a way to say the type of `myLife` is equivalent to something *like* `Life & MessedUp`. That seems more likely, and we've brainstormed through it, but has issues with how control flow analysis re-joins types when we encounter unions of intersections. If that's more of the request, I would agree that this is a duplicate of #4238.

**Comment by fatcerberus** [comment] 2022-10-30 13:46
I don’t *really* think this is a duplicate of #4238. 🚎

**Comment by jcalz** [comment] 2022-10-30 15:07
That's just an unfortunate short hash collision, if you want to be sure that it works, you should use the full hash: [#4238486defb1a4cbdb36bd012357ba5bed28f371](https://github.com/microsoft/TypeScript/issues/42384)

**Comment by MartinJohns** [comment] 2022-10-30 16:43
@jcalz:
![image](https://user-images.githubusercontent.com/5269069/198890574-ca7316dc-9207-46a4-a1be-2d1761cc7b8c.png)

**Comment by samchan0221** [comment] 2022-10-30 17:11
> I would say there's a few aspects of this.
> 
> First, trying to associate a value with an appropriate named type based on narrowing logic would be prohibitively expensive (and _probably_ undecidable), and has some pitfalls that @MartinJohns kind of alludes to.
> 
> Closer to what you might want is a way to say the type of `myLife` is equivalent to something _like_ `Life & MessedUp`. That seems more likely, and we've brainstormed through it, but has issues with how control flow analysis re-joins types when we encounter unions of intersections. If that's more of the request, I would agree that this is a duplicate of #4238.

Thank you all for answering and providing related issues. I searched `narrow` and didn't found what I want so I opened this issue. I looked at that issue and think they are pretty similar improvement request.

I agree with the fact that `trying to associate a value with an appropriate named type` is undecidble. What I want is just the structural type changing throughout the control flow as it passes through condition checks (which is already working in if the type is a union type).

**Closed** 2022-11-01 18:00 UTC
Labels: Duplicate
