### ISSUE TITLE
Allow export default interface

### ISSUE THREAD

**Issue by LPGhatguy** [Microsoft/TypeScript#3914] opened 2015-07-17 18:08 UTC
The following snippet is valid, as far as I know:
```ts
export interface User {
	wpUserID: string;
}
```

The following snippet is also valid, but does not compile, but probably should:
```ts
export default interface User {
	wpUserID: string;
}
```

I get errors thrown at me when using TypeScript 1.5-beta:
```
Error: /Models/User.ts(1,26): Error TS1005: ';' expected.
Error: /Models/User.ts(1,31): Error TS1005: ';' expected.
```

**Comment by DanielRosenwasser** [comment] 2015-07-17 21:01
You can get around this with

```TypeScript
interface I {
	
}

export default I;
```

I admit this is a somewhat strange inconsistency, but this is a duplicate of #3194 and is by design in accordance with a decision made on https://github.com/Microsoft/TypeScript/issues/3095#issuecomment-100913384.

**Comment by LPGhatguy** [comment] 2015-07-17 21:03
Interesting. Any chance there could be a warning about the behavior?

**Comment by danquirk** [comment] 2015-07-17 21:10
Linking to https://github.com/Microsoft/TypeScript/issues/3792 because they're very similar. We should just allow this kind of thing. There's no good reason to require you to write it in 2 statements instead of one.

**Comment by dsherret** [comment] 2015-09-30 01:33
:+1:

**Comment by clark-stevenson** [comment] 2015-10-21 19:20
:+1:  Any kind of error would be welcome, it took a StackOverflow question to understand.

**Comment by mhegazy** [comment] 2016-02-22 19:57
closing in favor of https://github.com/Microsoft/TypeScript/issues/3792

**Closed** 2016-02-22 19:57 UTC
Labels: In Discussion, Suggestion
