### ISSUE TITLE
Nested classes

### ISSUE THREAD

**Issue by Serabass** [Microsoft/TypeScript#1551] opened 2014-12-24 05:45 UTC
Why Typescript has not the static classes like in Java, while Javascript has supported this.

If I wrote in JS:
```js
	var ParentClass = (function () {
		function ParentClass() {
	
		}
		ParentClass.prototype.someMethod = function () {
	
		};
	
		ParentClass.StaticClass = (function () {
			function StaticClass() {
	
			}
			StaticClass.prototype.someMethodInStaticClass = function () {
				return "Hello, " + this.greeting;
			};
	
			return StaticClass;
		})();
		return ParentClass;
	})();

	var entity = new ParentClass.StaticClass();
	console.log(entity instanceof ParentClass.StaticClass); // true
```

This is correct, but:
```ts
	class parentClass {
		someMethod() {}
	
		{static} class StaticClass {
		someMethodInStaticClass() {}
		}
	}

	var entity = new ParentClass.StaticClass();
	console.log(entity instanceof ParentClass.StaticClass); // true
```

This is incorrect although it can compile into silimar JS.

P.S. I'm sorry for bad markup

**Comment by danquirk** [comment] 2015-01-06 01:29
Agreed, just gonna close this as a duplicate of #497 unless someone has a very compelling reason for additional syntax on top of that.

**Closed by danquirk** 2015-01-06 01:29 UTC
Labels: ES6, Needs Proposal, Suggestion
