### ISSUE TITLE
Incorrect narrowing when a type guard returns a type union

### ISSUE THREAD

**Issue by octogonz** [microsoft/TypeScript#41871] opened 2020-12-08 05:42 UTC
**TypeScript Version:**  4.1.2

**Search Terms:**

`narrowing` `narrowed` `type guard` `type union`

**Code**

@MickeyPhoenix encountered this bug while implementing type guards for HBOMax data services. The original repro involves `class` inheritance, like this:

[playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAECCB2BLAtmE0DeAoavoAcAnRANzABcBTaADwC5p4BXZAI0sOgF5oAGAbiwBfLKEgwAwhWiUaVeABMYCFGkw48+JqxCJg0AO4ALRBADWHCA2ZsO3aAEZBIsVGgAhQgHsvydXgJiMipoAE9rFnZOHicsDVwtHT1DE3NLCNtox0EAxN19IzBFEEoMqK4AZmc4gDMmeGByRC94aEKIAHVUi0IIAApEeC1yBhVUdAAfD29fAEoGQeHoU2gpcmgpzx8-bADCSnImQlbFpnXBiHIi4EovGtXpCanT8-hL69v7rd9qrDqGpotZYNLyEfaNAZDM6jJDjDbTbbzRiROy7PCIe59dpdUw9fovWazfwBPAAelJ0AAkgA5CQAeQASgyAKISAAqDDZRg41AgRi8TBACmg7GgYGgwF8+EQJU4HG8nG5+wANNB4iTySKztAAAYvHXQADmXlekrBlEaIFCjDAYK8BkowvIXl132QBvVAU1kMulDAwruurW8LdOtmnrw+0Ox2BwwAdIVipR+GqAkJU5GDkdWgBaWIiP71RrNVpm8HkSHDGGqSYIuZlVHqjHQSvai5XBqfB7rJ6xttvDs3QNuoloknQTX0pmsjm6xMKEoGlbwE1i6DISiZaCBnXBzYzd3KiO4TUQF3kbkSqUyuxli3kK3Qfb4UHkGBFGR2xU8uPHp9ZmMXgTIoF2TdV0ziPYANzfM4klAcJWkHh4EoAxuz6WZBE1AAFYh4DfaAACJ6gUSgakGR1CJFC0wCYCBqGAChgKTaAFEQBR4AAcnWMBGiYNBH1kUxyFEFozxKOMQC8Q1ITvCFGPIQlBCAA)
```ts
class Animal {
    private x: number = 0;
}
class Cat extends Animal {
    public whiskers: number = 1;
}
class Broom {
    private y: number = 1;

    public whiskers: number = 1;
    public handle: number=3;
}

function hasWhiskers(input: Animal | Broom): input is Cat | Broom {
    return input instanceof Cat || input instanceof Broom;
}

function incorrect(input: Animal | Broom): number {
    if (hasWhiskers(input)) {
        // INCORRECT: There should be a compiler error here, 
        // but `input` got incorrectly narrowed to `Broom` 
        // (instead of `Cat | Broom`)
        return input.handle; 
    } 
    return -1;
}

function correct(input: Animal | Broom): number {
    if (input instanceof Cat || input instanceof Broom) {
        // CORRECT: `handle` is not a member of `Cat | Broom`,
        // so the compiler correctly reports an error here.
        return input.handle;
    } 

    return -1;
}

const cat = new Cat();
// Prints "undefined" because cat.handle didn't actually exist
console.log(incorrect(cat));
```

But it can also be reproduced using simpler `interface` inheritance, like this:

[playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIImAWzgG2QbwChkTkcIBzAZwC5kQBXTAI2gG5CBfQ0SWRFAGE4YZBAAekEABMqaDNjxFSyAO4ALYFQDW0WvSasoHbr2jwkyAEJQA9rcwFipDVt1R9jFu2cl1cGXI6LyMTQkIYBhAEMGBbEGR-KgB1TR09AApQAAcGMDp0LFxkAB9rOwcASjocvOQtZGFRMpt7R2VSKAgwBigEgHlmACsIGIA6JP7VEAAFO2zoMABPMYRcHCyQXLAAGmQAcld0j33KsIiomLiE0ARbKC6Yze2ChWKWisxqg28oJxVgDBkBkkqk3JlamBKpV-ipSAB6eHIACSADlBP0AEqYgCiggAKnR8epoCgqOpbAwcNJkKxkHBkHdMNlgOQ-tA7H8SV09r44YjaXUAAaQoXICi2US3e6PMA4Jb0OAPWyqCA0sC2ZBC1oOMV8lQCzZUSBwGm2IFCpqlcptIWVfWdbq9G5bPITALSchsZB8zg+lRdHp9ZAAWgAjGEgA)
```ts
interface Animal {
    legs: number;
}
interface Cat extends Animal {
    whiskers: number;
}
interface Broom {
    whiskers: number;
    handle: number;
}

function hasWhiskers(input: Animal | Broom): input is Cat | Broom {
    return Object.hasOwnProperty.call(input, 'whiskers');
}

function incorrect(input: Animal | Broom): number {
    if (hasWhiskers(input)) {
        // INCORRECT: There should be a compiler error here, 
        // but `input` got incorrectly narrowed to `Broom` 
        // (instead of `Cat | Broom`)
        return input.handle; 
    } 
    return -1;
}

```

**Expected behavior:**

One would expect identical type narrowing when extracting this:
```ts
function f(input: Animal | Broom): number {
    if (input instanceof Cat || input instanceof Broom) {
    . . .
```
...into this:
```ts
function hasWhiskers(input: Animal | Broom): input is Cat | Broom {
    return input instanceof Cat || input instanceof Broom;
}

. . .

function f(input: Animal | Broom): number {
    if (hasWhiskers(input)) {
    . . .
```

**Actual behavior:**

The type is incorrectly narrowed to `Broom` instead of `Cat | Broom`.

As a result, clearly incorrect code compiles without any error.

**Related Issues:** https://github.com/microsoft/TypeScript/issues/31156

**Comment by andrewbranch** [comment] 2020-12-08 17:52
This is indeed a duplicate of #31156.

**Closed** 2020-12-10 18:00 UTC
Labels: Duplicate
