### ISSUE TITLE
super keyword strikethrough per erroneous deprecated setting in .js files since Aug 10 update

### ISSUE THREAD

**Issue by minaelee** [microsoft/TypeScript#40511] opened 2020-09-11 21:54 UTC
- VSCode Version: 1.49.0
- OS Version: WindowsNT x64 10.0.19041

Steps to Reproduce:

1. Create a .js file with this content:
```
import React from 'react'; // does not matter if this line is here or not

class Test  {
    constructor(props) {
        super(props);
    }
}
```
2. Add extends React.Component to class Test, like so:
`class Test extends React.Component {`

3. The word 'super' then gets striked through and hovering over seems to say it is deprecated for typescript, but this is not a typescript file. It does not affect the code but is confusing many people. Working around it by disabling the "Editor: Show Deprecated" setting, but would prefer to be able to enable that setting. This has only been happening since the VS Code update on August 10, 2020 (yesterday).

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-09-11 21:59
I confirmed that the `React.component` constructor is marked as deprecated  in the react typings. The deprecated message links to: https://reactjs.org/docs/legacy-context.html

So I suspect this is either: a problem with the react typings or the expected behavior as it points out usage of a deprecated api

**Comment by minaelee** [comment] 2020-09-11 22:20
The legacy-context.html page is referring to a specific React API called Context and is not related to using the extends React.

> Should the example be?
> 
> ```js
> import React from 'react'; 
> 
> class Test extends React.Component  {
>     constructor(props) {
>         super(props);
>     }
> } 
> ```

That is in my Step 2, to demonstrate that the issue occurs exactly when you add "extends React.Component" and not just when you use "super" otherwise.

**Comment by minaelee** [comment] 2020-09-11 22:23
> I confirmed that the `React.component` constructor is marked as deprecated in the react typings. The deprecated message links to: https://reactjs.org/docs/legacy-context.html
> 
> So I suspect this is either: a problem with the react typings or the expected behavior as it points out usage of a deprecated api

The legacy-context.html page is referring to a specific React API called Context and is not related to using the `extends React.Component` syntax. That syntax is required for class components in React and AFAIK is not deprecated, aside from the general move away from class components. The React team themselves have announced that they will _not_ remove class components from React (see: https://reactjs.org/docs/hooks-intro.html#gradual-adoption-strategy). 

See: https://reactjs.org/docs/components-and-props.html. Using `extends React.Component` is the canonical way to create a React class component. It should not cause the super keyword to be marked as deprecated.

**Comment by mjbvz** [comment] 2020-09-11 23:55
Thanks. This sounds like it may be an issue with the react typings then. Let's wait for someone on the TS team to confirm this though

**Comment by IllusionMH** [comment] 2020-09-12 13:34
Duplicate of #39509 - I filled that one starting with this exact deprecation warning.

Most likely workaround is to split second constructor declaration into two: not deprecated without `context` argument at all and deprecated with both `props` and `context` required.

**Comment by Celadora** [comment] 2020-09-12 17:53
You can avoid this by explicitly passing your arguments into super, however I would also like this to return to its previous behavior.

`
class Widget extends React.Component {
  constructor({ foo, baz }) {
    super({foo, baz});
  }
}
`

**Comment by AhammedShaqil** [comment] 2020-09-14 15:42
I had faced the same issue....I just removed the props from super(). By doing this, the strike-through went away. 

```
import React from 'react'; 

class Test extends React.Component  {
    constructor(props) {
        super();
    }
} 
```

PS. I was still able to use this.props in my React class except in the constructor where we don't use this.props but just props.
I think the stackoverflow answer would explain something [](https://stackoverflow.com/a/34995257)

**Comment by RyanCavanaugh** [comment] 2020-09-14 17:55
This is controlled by the definition file on DefinitelyTyped.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L480

Someone should add a third overload here that accepts `props: P` and isn't marked deprecated

**Comment by IllusionMH** [comment] 2020-09-14 18:10
@RyanCavanaugh while fix for declaration is quick workaround here, there is still difference in overloads pick between JS and TS (this exact issue is not observed in TS files) as shown examples for #39509

**Comment by ConradSollitt** [comment] 2020-09-16 23:38
I found this today after experiencing the same issue. However now I came across the same issue in a regular JavaScript file (no JSX or React) with a valid standard DOM event `window.location.reload(true);`.

Here is the file where this showed up for `window.location.reload`:
https://github.com/dataformsjs/dataformsjs/blob/master/js/plugins/clickUrlAction.js#L75

![image](https://user-images.githubusercontent.com/57777521/93402863-bf548380-f83a-11ea-9a2b-941baf5aa5fe.png)

**Comment by IllusionMH** [comment] 2020-09-17 08:33
@ConradSollitt I think `location.reload` is separate issue, because `reload` doesn't support `forceReload` flag in latest specs:
https://html.spec.whatwg.org/multipage/history.html#dom-location-reload
https://www.w3.org/TR/html52/browsers.html#dom-location-reload

Related: https://github.com/w3c/ServiceWorker/issues/597#issuecomment-70087324


`window.location.reload()` works fine

**Comment by ConradSollitt** [comment] 2020-09-17 21:20
@IllusionMH Thanks for the info! I just did some testing in different browsers and confirmed that for modern browsers the `forceReload` flag has no effect however when using IE 11 `reload(true)` results in the browser sending the request header `Cache-Control: no-cache`. In this past (at least 2 years ago) I had to use `reload(true)` to make sure app behavior (login pages, etc) worked properly so now I've updated related code comments that the feature is being kept for IE.

**Comment by GanongLS** [comment] 2020-09-18 08:18
I facing the same issue. And it's really confusing, please some team either from react.js or from ts or eslint need to fix this.

**Comment by milosveljkovic** [comment] 2020-09-18 08:32
This is an issue. 
![image](https://user-images.githubusercontent.com/47954575/93575618-2b99c900-f99a-11ea-9add-65dc168cc48a.png)

**Comment by ninjaasmoke** [comment] 2020-09-19 10:13
> I had faced the same issue....I just removed the props from super(). By doing this, the strike-through went away. 
> 
> ```
> import React from 'react'; 
> 
> class Test extends React.Component  {
>     constructor(props) {
>         super();
>     }
> } 
> ```
> 
> PS. I was still able to use this.props in my React class except in the constructor where we don't use this.props but just props.
> I think the stackoverflow answer would explain something https://stackoverflow.com/a/34995257

Worked like a charm! Thanks

**Comment by preetiipriya** [comment] 2020-09-21 12:19
> > I had faced the same issue....I just removed the props from super(). By doing this, the strike-through went away.
> > ```
> > import React from 'react'; 
> > 
> > class Test extends React.Component  {
> >     constructor(props) {
> >         super();
> >     }
> > } 
> > ```
> > 
> > 
> > PS. I was still able to use this.props in my React class except in the constructor where we don't use this.props but just props.
> > I think the stackoverflow answer would explain something https://stackoverflow.com/a/34995257
> 
> Worked like a charm! Thanks


hey could you please help me out..i didnt get it

**Comment by gustavonikov** [comment] 2020-09-23 06:20
> > > I had faced the same issue....I just removed the props from super(). By doing this, the strike-through went away.
> > > ```
> > > import React from 'react'; 
> > > 
> > > class Test extends React.Component  {
> > >     constructor(props) {
> > >         super();
> > >     }
> > > } 
> > > ```
> > > 
> > > 
> > > PS. I was still able to use this.props in my React class except in the constructor where we don't use this.props but just props.
> > > I think the stackoverflow answer would explain something https://stackoverflow.com/a/34995257
> > 
> > 
> > Worked like a charm! Thanks
> 
> hey could you please help me out..i didnt get it

This is when u don't need to use this.props inside the constructor, if u wont use, u should be fine removing super(props) and putting only super()

**Comment by JesseAyegba** [comment] 2020-09-23 18:38
Thanks a lot Minaelee. This truly is a life saver. This is has been bugging me for a while now

**Closed** 2020-09-26 10:00 UTC
Labels: External

**Comment by noinkling** [comment] 2020-09-29 05:24
Note that while `super()` might be an acceptable workaround for those without JS type-checking on, when it *is* on then removing the argument produces a `Expected 1-2 arguments, but got 0.` error, which is worse for the rest of us.

If #39509 is the root cause then that should be resolved.

**Comment by IllusionMH** [comment] 2020-09-29 08:55
Instead of removing argument from `super` it's possible to add comment
```js
class Example extends React.Component {
    /** @param {Record<string, any>} props */
    constructor(props) {
        super(props);
    
        console.log(props.message);
        console.log(this.props.message);
    }
    // ...
}
```
