### ISSUE TITLE
Suggestion: Add support for jsdoc-based prefix cast syntax for JavaScript files

### ISSUE THREAD

**Issue by rbuckton** [Microsoft/TypeScript#16345] opened 2017-06-08 00:23 UTC
[Original discussion](https://github.com/Microsoft/TypeScript/issues/15618#issuecomment-300632637)

This suggestion proposes we allow a new prefix cast syntax using `/** @type {...} */ `, e.g.:

```ts
// @ts-check

const map = new Map((/** @type {Array<[string, {x?:number, y?:number}]>} */[
    ['a', {x: 1}],
    ['b', {y: 2}]
]));
```

This syntax requires the expression to cast must be enclosed in parenthesis, and the jsdoc comment must be the first comment inside of the parenthesis. This is because it would be fairly expensive (in terms of both time and storage) to scan for jsdoc comments for every expression. This restriction would allow us to significantly reduce the overhead necessary to support this feature.

**Comment by evmar** [comment] 2017-06-16 16:15
FWIW, in Closure code the cast syntax requires parens:
  /** @type {Foo} */ (bar)
and they also allow a shorthand:
  /** Foo */ (bar)

(Though of course the Closure type system is incompatible with the TS one so it's unlikely people will mix the two.)

**Comment by DanielRosenwasser** [comment] 2017-06-18 17:15
Duplicate of #5158?

**Closed** 2017-07-12 22:24 UTC
Labels: Salsa, Suggestion
