### ISSUE TITLE
bad prediction on a file

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9117] opened 2016-06-13 06:47 UTC
_From @gilberto389 on June 13, 2016 4:36_
- VSCode Version:

Versión 1.3.0-insider
Confirmación 7d56f33e508930d3727064481a7525344a227f10
Fecha 2016-06-10T06:08:40.882Z
Shell 0.37.6
Representador 49.0.2623.75
Node 5.10.0
- OS Version: win 7 ultimte 64 bits

Steps to Reproduce:
1. watch video
   https://youtu.be/MTObQB4tm9U

_Copied from original issue: Microsoft/vscode#7592_

**Comment by mhegazy** [comment] 2016-06-13 19:45
@gilberto389 can you please share the project? this way i can navigate through the code and understand the structure better.

**Comment by gilberto389** [comment] 2016-06-14 03:37
I can not share the code, but the problem is that one of the files prediction does not work, I tried all forms of file "jsconfig" and nothing uninstall and reinstall and nothing, place the "jsconfig" in all directories , rename the file, delete all bookmarks uninstall all extensions, finally like I will continue to use, is a good code editor, well this new file ("deNumeros.js") is not so long, but if I need to create another quite extensive and it does not work the prediction will be very serious.

**Comment by gilberto389** [comment] 2016-06-14 03:39
The other is not because they passed the problem to the typescript section?
  I'm not using typescript is javascript with ES5.

**Comment by mhegazy** [comment] 2016-06-14 17:39
The completion you get in VSCode for JS files is driven by the TypeScript analysis engine in the back-end. this is why the issue on VSCode issue tracker has been moved here.

We will need some additional context to be able to investigate and fix the issue. the description above does not allow us to do that.

**Comment by gilberto389** [comment] 2016-06-14 18:29
It does not work as one would like, that this evil, typescript have not done anything.
  there tscript.json? it is necessary ?

https://youtu.be/IVZUPlSgWjA

autocomplete works only for members who have already called in the JS file, for example:

**in file1.js**

```
function dog(){
  this.name="any";
  this.color="black";
}
```


//-----

**in file2.js**

```
var miDog=new dog();

miDog.name="new name";
```

miDog.-----------> here only show "name"

**Comment by mhegazy** [comment] 2016-12-16 00:50
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/7046

**Closed by mhegazy** 2016-12-16 00:50 UTC
Labels: Needs More Info
