### ISSUE TITLE
@‌deprecated JSDoc tag

### ISSUE THREAD

**Issue by DickvdBrink** [microsoft/TypeScript#390] opened 2014-08-07 12:31 UTC
It would be cool to annotate a method or property with a deprecated attribute
## Proposal

If a warning could be issued when using a deprecated method or property it is easier to upgrade to a newer library version (only when the definitions are up to date of course)

Syntax: Same as JSDoc, a simple comment

```
/**
 * @deprecated Use other method
 */
public foo() {
}
```

If supported in .d.ts files, this would really help with upgrading to a newer version.

**Comment by JustinBeckwith** [comment] 2015-01-06 18:01
C# will allow what you've written above, because it does not react to [Obsolete] attributes on interfaces - only base class implementations.  Given the lack of multiple inheritence, this isn't really an issue.  Here's how it's handled in C#:

```cs
class Program
    {
        static void Main(string[] args)
        {
            var x = new Zoo();

            // doThing is allowed, even though it is obsolete on interface X
            x.doThing();

            // doStuff is not allowed. It is not obsolete on the interface, but is obsolete on the base class. 
            x.doStuff();
            Console.Read();
            
        }
    }

    interface X
    {
        /// <summary>
        /// 
        /// </summary>
        [Obsolete("boo", true)]
        void doThing();
    }

    interface Y
    {
        void doThing();
        void doStuff();
    }

    class Zoo : ZooBase, X
    {
        public void doThing()
        {
            Console.WriteLine("boo");
        }

        [Obsolete]
        public override void doStuff()
        {
            Console.WriteLine("boo");
        }
    }

    abstract class ZooBase
    {
        [Obsolete("boo", true)]
        public abstract void doStuff();
    }
```

**Comment by mhegazy** [comment] 2015-01-12 15:36
I think this is fair. the class provided a re-declaration of the method. if you were to use the interface directly you would get an error:

```TypeScript
var g = new Z();
g.doThing(); // OK, this is the class definition of doThing()

var e: X = new Z();
e.doThing(); // Error, X.doThing() is deprecated.
```

**Comment by louy** [comment] 2015-11-27 07:32
I believe this shouldn't cause an error but rather a warning.
For the situation @RyanCavanaugh mentioned, a function would only be deprecated if there doesn't exist any non-deprecated implementation.
As for implementing an interface-deprecated method in a class, you should get a warning once in the class implementation, not each time you're calling the method.

```ts
interface IX {
  @deprecated
  function doSomething(): void;
}

class X implements IX {
  function doSomething(): void; // Warning: IX.doSomething is deprecated

  @deprecated
  function doSomethingElse(): void;
}

const x = new X();
x.doSomething(); // Ok...
x.doSomethingElse(); // Warning: X.doSomethingElse is deprecated
```

**Comment by kitsonk** [comment] 2015-11-27 08:14
That syntax collides with decorators. :frowning: 

Considering this hasn't seen any action in a long time, and now that the compiler parses and integrates JSDoc, it could in theory understand and warn on `/* @depecrated */` JSDoc, but is there yet the concept of warning in TypeScript or does it still consider everything an error?

Otherwise this should be the domain of something like [tslint](https://github.com/palantir/tslint) @adidahiya, thoughts?

**Comment by louy** [comment] 2015-11-27 08:20
Yeah I know. I didn't know that the complier considered JSDoc comments. I thought we might have a reserved keyword or something.
I also think this is beyond the scope of tslint. Linting should be about coding style, not type checking.

AFAIK TS has no concept of warnings. In my opinion however, it should. Similar to ESLint's error/warning concepts.

**Comment by kitsonk** [comment] 2015-11-27 10:10
> Linting should be about coding style, not type checking.

I disagree... It should be about things deal with code quality, things that are syntactical errors.  tslint and other linting tools do lots of [quality checking](https://github.com/palantir/tslint#supported-rules), like unused variables, conditional assignments, switch statement drop through and defaults, etc.

In fact we draw the defenition from the [UNIX `lint` tool which](https://en.wikipedia.org/wiki/Lint_(software)):

> In computer programming, lint is a Unix utility that flags some suspicious and non-portable constructs (likely to be bugs) in C language source code; generically, lint or a linter is any tool that flags suspicious usage in software written in any computer language.

**Comment by louy** [comment] 2015-11-27 15:24
@kitsonk okay I'm convinced. I'll open a new issue in tslint's repo then.

**Comment by felixfbecker** [comment] 2016-03-27 20:30
I also think this is something that does not need a language feature, but belongs to documentation (jsdoc) and can be checked by something like tslint.

**Comment by PanayotCankov** [comment] 2016-12-30 09:06
We have homegrown @Deprecated decorator but adding this in the language feature so it can be better visible in .d.ts-es would be great!

Can you make two flavors of it (like @deprecated and @obsolete) where one will warn and the other will err. The workflow would be to make stuff that is about to be removed with @Deprecated for a version or two so the downstream dependencies can have time to upgrade and then move from @Deprecated to @Obsolete in the .d.ts when the member is deleted. At runtime it would be up to the library to promise the @Deprecated to work even though with degraded quality, while the @Obsolete will be expected to throw.

**Comment by adamvoss** [comment] 2017-07-01 02:37
@PanayotCankov  The distinction you make between **@deprecated** and **@obsolete** is not intuitive to me, though maybe it is or other people.  Perhaps **@removed** would communicate the expected behavior? I am not sure I've ever found myself needing multiple levels of deprecation, but it could still be a good idea.

**Comment by carltoncolter** [comment] 2017-11-22 19:44
Where are we with this issue?  @deprecated on an interface doesn't cause any kind of warning in Visual Studio and it should... I'm not talking about layers deep.  Can we at least get one layer?  So if we are trying to use something that has the @deprecated tag on it, it shows a warning or something in the IDE?

The @deprecated intellisense isn't working in visual studio.... is it working somewhere else?

**Comment by felixfbecker** [comment] 2017-11-22 19:47
@carltoncolter just use https://palantir.github.io/tslint/rules/deprecation/

**Comment by ikokostya** [comment] 2017-11-22 22:26
@felixfbecker The main problem with this solution is it doesn't check external modules. If typescript adds support for this it will work with external modules (and type declarations).

**Comment by carltoncolter** [comment] 2017-11-22 23:41
Thanks @felixfbecker !  I figured out why I couldn't get tslint to work right.  My problemmatcher wasn't working.  I had to setup my own in my lint task...
```json
{
    "version":"2.0.0",
    "tasks": [
        {
            "type":"npm",
            "script": "lint",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": {
                "owner":"tslint",
                "severity": "warning",
                "fileLocation": ["absolute"],
                "pattern":[
                    {
                        "regexp": "^(WARNING|ERROR):(\\s+\\(\\S*\\))?\\s+(\\S.*)\\[(\\d+), (\\d+)\\]:\\s+(.*)$",
                        "severity": 1,
                        "file": 3,
                        "line": 4,
                        "column": 5,
                        "message": 6
                    }
                ]
            }
        }
    ]
}
```

I'm not sure why the regular pattern matcher base $tslint5 wasn't picking up the errors.  Now it is...

**Comment by yawaramin** [comment] 2017-12-26 05:17
IMO this needs to be provided by tsc, using the `/** @deprecated */` JSDoc. Here's why. Evolving a statically-typed codebase is a critical part of the job. Deprecating certain items in the code is the best way to do that while a project is in production. The lack of proper, granular, deprecation holds projects back from evolving their codebase towards safer types.

Let me try to answer @RyanCavanaugh's question ( https://github.com/Microsoft/TypeScript/issues/390#issuecomment-51507194 ) from a type-theoretic perspective. When class `Z` implements interfaces `X` and `Y`, it is essentially an intersection type between `X` and `Y`, hence in `Z` the `doThing` method is considered to be a member of _both_ `X` and `Y`. Hence, it is trivially a member of `X`, so it should trigger the deprecation error.

**Comment by madluxit** [comment] 2018-01-09 16:29
That's correct. As SDK developer, I cannot force all the potential users of my API to use tslint in order to spot warnings that should be spotted at compile time (in addition obviously to IDE inline support).
tslint could be used to improve the quality of the user code style, and expecting that customers are able to spot API misuse issues only through that is oversimplification.

**Comment by RikkiGibson** [comment] 2018-05-26 01:19
@madluxit has got it. `@deprecated` is most useful as a feature for library developers who need to convey changes to their users. If we are only able to provide deprecation warnings to people who have tslint configured to see those warnings, we might as well `console.warn()` on the first call to that function or something instead.

**Comment by Simran-B** [comment] 2019-02-21 11:38
> @PanayotCankov The distinction you make between **@deprecated** and **@obsolete** is not intuitive to me

In the V8 code base I saw the terms `deprecated` (obsolete/removed) and `deprecate_soon` (already warn user). Seems unambiguous in combination.

**Comment by KenanSulayman** [comment] 2019-06-17 11:05
Any updates on this? We just had a meeting on how to communicate internal API library deprecations and using respective deprecation directives (resp. annotations) would be more than useful to achieve this.

We are already using GraphQL directives achieving this on the API level.

In GraphQL the effect of marking as @deprecated is that the respective fields are not listed as field in the documentation anymore (akin to a “hidden” public field); they still function and trigger a respective deprecation notice when the field is used. This would map to TypeScript by not listing methods as being part of the API surface of a class, export or object, and when used, would trigger a warning when compiled by tsc.

**Comment by donaldpipowitch** [comment] 2019-08-15 06:06
FYI: VS Code could now use this: https://github.com/microsoft/vscode/issues/53514#issuecomment-521478877

**Comment by jdom** [comment] 2019-10-16 16:55
Any progress? I'd also like something that integrates better with the compiler without relying on consumers to correctly set up eslint/tslint rules

**Comment by ghiscoding** [comment] 2019-10-16 17:00
That would also work nicely with the new VSCode [Deprecations Tags for Symbols and Completions](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_39.md#deprecation-tags-for-symbols-and-completions) feature.

**Comment by mheiber** [comment] 2019-10-31 17:25
We'd be interested in this as well

**Comment by leonardojimenez** [comment] 2019-12-16 15:18
+1

**Comment by ExE-Boss** [comment] 2019-12-19 20:13
See&nbsp;also: <https://github.com/jasnell/proposal-deprecated>.

**Comment by Kingwl** [comment] 2020-05-13 01:57
I'd like to work on this both ts and vscode side.

**Comment by luke-john** [comment] 2020-06-10 09:32
It's unclear to me from this proposal whether deprecating an entry in a union would be supported.

```tsx
type Props = {
    value:
        | 'a'
        | 'one' 
        /** @deprecated */
        | 'value-one' 
}
```
If so great 👍. If not would it be possible to include that in this proposal or would it be better to create a separate proposal?

**Closed** 2020-06-19 00:41 UTC
Labels: Domain: Decorators, Domain: JSDoc, Needs Proposal, Suggestion

**Comment by ghiscoding** [comment] 2020-09-19 03:36
Since this is now a thing, it could be removed from [Future](https://github.com/Microsoft/TypeScript/wiki/Roadmap#future) section 
> Investigate `Ambient`, `Deprecated`, and `Conditional` decorators

**Comment by haysclark** [comment] 2020-09-24 22:48
> Since this is now a thing, it could be removed from Roadmap [Future](https://github.com/Microsoft/TypeScript/wiki/Roadmap#future) section
> 
> > Investigate `Ambient`, `Deprecated`, and `Conditional` decorators

Before `Deprecated` is removed from the Roadmap, it would be great to learn more about the possibility of supporting deprecated _Unions_. IMHO, this is an extremely common User Case which @luke-john also [mentioned above](https://github.com/microsoft/TypeScript/issues/390#issuecomment-642113877).

e.g.
```typescript
/** @deprecated */
type LegacySizes =
  | "sm"
  | "lg";
export type ButtonSizes =
  | LegacySizes
  | "small"
  | "medium"
  | "large";

export interface ButtonProps {
  size?: ButtonSizes;
}
```

**Comment by devinrhode2** [comment] 2021-04-14 17:13
Is this supported now? If so where are the docs for this? (Or can anyone share an example?)

**Comment by NateScarlet** [comment] 2021-04-14 17:15
@devinrhode2 

![图片](https://user-images.githubusercontent.com/21083014/114751734-1c3ffa00-9d88-11eb-9824-30d878eca3aa.png)

**Comment by SebastianStehle** [comment] 2021-07-25 16:32
Is it possible to mark all deprecated warnings?

**Comment by HolgerJeromin** [comment] 2021-08-11 13:12
@SebastianStehle Perhaps you can use something like https://github.com/gund/eslint-plugin-deprecation

**Comment by xiaoxiangmoe** [comment] 2022-02-27 17:31
Also, we can use https://www.npmjs.com/package/eslint-plugin-sonar

```ts
// .eslintrc.cjs
{
  "plugins": ["sonar"],
  "rules": {
    "sonar/deprecation": 1
  }
}
```

**Comment by clshortfuse** [comment] 2022-09-22 14:10
I have a specific issue filed here: https://github.com/microsoft/TypeScript/issues/50899

But `@deprecated` properties are enforced as mandatory when using `implements`. That seems like a mistake based on the conversation here. If the ECMA says: 

>Programmers should not use or assume the existence of these features and behaviors when writing new ECMAScript code.

That means they should be implicitly be `Optional`. And if `implements` has no concerns about not implementing optional properties (eg: `implements Optional<Foo>`), then that issue goes away.

I'm not sure how other groups define "deprecated", but I'm using the ECMA language. I'm curious to see what the group thinks about this.
