### ISSUE TITLE
String literal function overloads not working as expected

### ISSUE THREAD

**Issue by geoffreak** [Microsoft/TypeScript#11089] opened 2016-09-23 13:10 UTC
I ran into an issue today with string literal function overloads using Typescript 2.0.3 while trying to write a library for Sift Science. I was attempting to create a function with stricter object checking when called with a certain string first. I was a bit surprised this doesn't work in a way I had expected.

```ts
async function addEvent(eventType: '$login', email: string | undefined, data: LoginEvent): Promise<void | Error>;
async function addEvent(eventType: '$logout', email: string, data?: LogoutEvent): Promise<void | Error>;
async function addEvent(eventType: string, email: string | undefined, data: Object = {}): Promise<void | Error> {
  // ...
}

interface SiftScienceBaseEvent {
  $ip?: string;
  $time?: number;
}
interface LoginEvent extends SiftScienceBaseEvent {
  $session_id: string;
  $login_status: '$success' | '$failure';
}
interface LogoutEvent extends SiftScienceBaseEvent {
  // This page intentionally left blank
}

let sid: string | undefined;
addEvent('$login', undefined, {
  $login_status: '$success',
  $session_id: sid,
});
```

The error I expected to see: (and you can indeed see by commenting out the `$logout` overload)
```
Types of property $session_id are incompatible
```

The error I see instead:
```
Argument of type '"$login"' is not assignable to parameter of type '"$logout"'
```

I had assumed that the string literal as the first parameter would specify which overload to use, but it seems that only the object types really work.

**Comment by DanielRosenwasser** [comment] 2016-09-23 14:06
what is the shape of `LoginEvent`?

**Comment by geoffreak** [comment] 2016-09-23 14:21
Here's more of the implementation... but it's suddenly working now? I guess I'll reopen this ticket if I can figure out what makes it break.

```ts
export interface SiftScienceBaseEvent {
  $ip?: string;
  $time?: number;
}
export interface CreateOrderEvent extends SiftScienceBaseEvent {
  $order_id?: string;
  $amount?: number;
  $currency_code?: string;
  $billing_address?: SiftScienceAddress;
  $payment_methods?: SiftSciencePaymentMethod[];
  $shipping_address?: SiftScienceAddress;
  $expedited_shipping?: boolean;
  $items?: SiftScienceItem[];
  $seller_user_id?: string;
  $promotions?: SiftSciencePromotion[];
  $shipping_method?: '$electronic' | '$physical';
}
export interface LoginEvent extends SiftScienceBaseEvent {
  $session_id: string;
  $login_status: '$success' | '$failure';
}
```

```ts
await Siftscience.addEvent('$login', 'test', {
  $login_status: '$failure',
  $session_id: 'test',
});
```

**Comment by geoffreak** [comment] 2016-09-24 21:55
Okay, I've isolated the issue and rewritten the issue into the first post. Hopefully that shows why I'm seeing this as unexpected.

**Comment by mhegazy** [comment] 2016-09-26 19:48
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/10523

**Closed by mhegazy** 2016-09-26 19:48 UTC
Labels: Needs More Info

**Comment by mhegazy** [comment] 2016-09-26 19:50
I should add that the issue here is the overload resolution algorithm decided that the first signature does not match, and then fell through to the next one. we should have better handling in cases of literals, to say that clearly the first one was the correct match, but the arguments were not correct.
