### ISSUE TITLE
feature request: exhaustive if-else should count as implicit return, just like switch

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#32107] opened 2019-06-26 15:55 UTC
Sorry, wasn't sure how to word the title shortly!

## Suggestion

Using a switch statement to filter values from a union of literals works great, and a return statement is not needed after the block.

However, when using if-else, the return statement is said to be missing by the type checker.

## Use Cases

It should work, it makes sense. Sometimes you don't want to convert JS code to use a switch while porting to JS, etc.

## Examples

```ts
// it works
function foo(a: 'foo' | 'bar'): boolean {
    switch(a) {
        case 'foo':
            return true;
        case 'bar':
            return false
    }
}

// doesn't work
function bar(a: 'foo' | 'bar'): boolean {
    if (a == 'foo')
        return true
    else if (a == 'bar')
        return false
}

// doesn't work
function baz(a: 'foo' | 'bar'): boolean {
    if (a == 'foo')
        return true
    if (a == 'bar')
        return false
}
```

[playground](http://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABMOcAUBDAXIg5CuXRAHzwCMMAnXAShzNQBsBTDJAbwChEfEBnAO4woEABaYaiLrxmIIGPszwFcWbrI2VmUEJSRRKIZgG51G+YvJVVZjby069yDI0W2Avp0+dQkWAkQKSkwcfFQiUlwg2nomVg5bGGBETEQAXjTlcJpbGQddfUNmW2ZXJSSUjHTMqOscu0R8p2AXN29faHgkCgAvEKzCEitqOkC4tilE5NSMgdpc+20CxAMjKcrq4fmGpqQWsq8gA)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by sandersn** [comment] 2019-06-26 16:58
duplicate of #21985

**Closed by sandersn** 2019-06-26 16:58 UTC
Labels: In Discussion, Suggestion
