### ISSUE TITLE
Missing definitions for events related to <input type='field' ...>

### ISSUE THREAD

**Issue by simonh1000** [Microsoft/TypeScript#7176] opened 2016-02-21 18:51 UTC
**TypeScript Version:** 

1.7.5 

**Code**

```ts
           var reader = new FileReader();

            reader.onload = function(evt) {
                // console.log(evt.target.result);
                debugger;
                resolve(evt.target.result);
                // resolve(evt.srcElement.result);
            };

```

**Expected behavior:**
code should pass typescript check

**Actual behavior:** 
the `.result` fields are being marked as `does not exist on EventTarget` / `Element`

**Comment by RyanCavanaugh** [comment] 2016-02-22 20:09
ref https://developer.mozilla.org/en-US/docs/Web/API/FileReader/onload

**Comment by YuichiNukiyama** [comment] 2016-02-23 22:54
This issue relate to #299, #4163

**Comment by mhegazy** [comment] 2016-02-23 23:30
looks like a duplicate of #4163

**Closed by mhegazy** 2016-02-23 23:30 UTC
Labels: Accepting PRs, Bug, Domain: lib.d.ts
