### ISSUE TITLE
Strange colourisation of template strings when "#/" present after first placeholder

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/TypeScript#3630] opened 2015-06-25 15:09 UTC
I've noticed some odd behavior with the syntax colourisation for template strings in Visual Studio 2013 (using TypeScript 1.4 plugin).  It occurs when the string "#/" is present within the template string **after** at least one placeholder is present.  I realise reading that is as clear as mud so look at the screenshot below for clarification:

![image](https://cloud.githubusercontent.com/assets/1010525/8357586/821c0ee4-1b53-11e5-9128-7f57eea1a952.png)

As you can see the first 2 examples colourise in the fashion you would hope.  The 3rd example behaves in an unexpected fashion after the "#/".  Here's the code you can use to reproduce it with:

```ts
class highlightingBug {

    demo() {

        var urlWithoutHash =
            `i_look_kind_of_normal_${"I_think"}`;

        var urlWithHash =
            `and_so_do_I_even_with_#/_in_place_${"I_think"}`;

        var urlWithHashAfterFirstPlaceHolder =
            `${"But_me_"}_well_things_look_a_little_odd_colour_wise_after_the_#/_${"That_is_what_I_think_anyway"}`;
    }
}
```

**Comment by DanielRosenwasser** [comment] 2015-06-25 15:23
TypeScript 1.4 didn't have proper template string colorization support in VS2013, so I believe it thinks it's seeing the identifier `_well_things_look_a_little_odd_colour_wise_after_the_`, followed by invalid token `#`, and finally unterminated regex ``/_${"That_is_what_I_think_anyway"}`;``

If you're curious for a more technical explanation, you can check [this page out on our wiki](https://github.com/Microsoft/TypeScript/wiki/FAQs-for-API-Consumers#why-does-the-lexical-classifier-sometimes-give-inaccurate-results-for-nested-template-strings).

The short answer is, [this has been fixed to a reasonable extent and will be available in TypeScript 1.5](https://github.com/Microsoft/TypeScript/pull/2026).

Marking it as a duplicate of #1477.

**Closed by DanielRosenwasser** 2015-06-25 15:23 UTC

**Comment by johnnyreilly** [comment] 2015-06-25 15:26
Ah great! Thanks for the detail.

**Comment by DanielRosenwasser** [comment] 2015-06-25 15:35
No prob; while 1.5 proper should be out pretty soon, you can use [the beta](https://visualstudiogallery.msdn.microsoft.com/107f89a0-a542-4264-b0a9-eb91037cf7af) in the mean time.
