### ISSUE TITLE
Cannot find tsconfig/tsc.json [5.2.2 -> 5.3.2]

### ISSUE THREAD

**Issue by ashumylo** [microsoft/TypeScript#56526] opened 2023-11-24 10:26 UTC
### 🔎 Search Terms

tsconfig/tsc.json

### 🕗 Version & Regression Information

- This changed between versions 5.2.2 and 5.3.2

### 💻 Code

```ts
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "extends": "tsconfig/tsc.json",
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "dist"
  },
  "include": ["**/*.ts"],
  "exclude": ["node_modules", "cdk.out", "**/*.d.ts"]
}
```

### 🙁 Actual behavior

I' getting the following error during `npx ts-node --prefer-ts-exts bin/cdk.ts` :

```ts
TSError: ⨯ Unable to compile TypeScript:
error TS6053: File 'tsconfig/tsc.json' not found.

    at createTSError (/opt/project/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.9.3_typescript@5.3.2/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/opt/project/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.9.3_typescript@5.3.2/node_modules/ts-node/src/index.ts:863:19)
    at createFromPreloadedConfig (/opt/project/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.9.3_typescript@5.3.2/node_modules/ts-node/src/index.ts:874:36)
    at phase4 (/opt/project/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.9.3_typescript@5.3.2/node_modules/ts-node/src/bin.ts:543:44)
    at bootstrap (/opt/project/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.9.3_typescript@5.3.2/node_modules/ts-node/src/bin.ts:95:10)
    at main (/opt/project/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.9.3_typescript@5.3.2/node_modules/ts-node/src/bin.ts:55:10)
    at Object.<anonymous> (/opt/project/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.9.3_typescript@5.3.2/node_modules/ts-node/src/bin.ts:800:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  diagnosticCodes: [ 6053 ]
}
```

`tsc.json` is placed in `packages/tsconfig/tsc.json` and changing tsconfig `"extends"` to an absolute path (`"../packages/tsconfig/tsc.json"` or `"node_modules/tsconfig/tsc.json"`) solves an issue. 

### 🙂 Expected behavior

`npx ts-node --prefer-ts-exts bin/cdk.ts` should work as it did in 5.2.2 version.

### Additional information about the issue

pnpm is used as a package manager for the project.

**Comment by Andarist** [comment] 2023-11-24 10:31
Likely a duplicate of https://github.com/microsoft/TypeScript/issues/56492

**Closed** 2023-11-24 10:49 UTC
