### ISSUE TITLE
IntelliSense Stops Working - cancelled sequence number

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#10735] opened 2016-09-06 21:12 UTC
There are open issues on IntelliSense problems in VS Code. The commonality is IntelliSense stops working. I could use some guidance on where I can look to get to the bottom of this. 

Related Issues
- https://github.com/Microsoft/vscode/issues/11260
- https://github.com/Microsoft/vscode/issues/11258
- https://github.com/Microsoft/vscode/issues/11505
- https://github.com/Microsoft/vscode/issues/12141
- https://github.com/Microsoft/vscode/issues/11938
- https://github.com/Microsoft/vscode/issues/12350
- https://github.com/Microsoft/vscode/issues/13294
- https://github.com/Microsoft/vscode/issues/13346
- https://github.com/Microsoft/vscode/issues/13335
- https://github.com/Microsoft/vscode/issues/14159
- https://github.com/Microsoft/vscode/issues/14230

I opened two of the issues as I observed them. The commonality with all many of issues is an output that includes the phrase "canceled request with sequence number x"

![image](https://cloud.githubusercontent.com/assets/2449568/18291295/e4bd6d80-743b-11e6-822b-c2965d77a270.png)

What could be causing this? 
Are there other logs I can look at to try and debug the problem?

**Comment by waderyan** [comment] 2016-09-08 22:10
I'm seeing this again today in the same ways described in the above issues. 

I am also seeing it in a new way. I am trying to recreate the issue described [here](https://github.com/Microsoft/vscode/issues/11641). The process involves a symbol rename symbol operation. 

Note that there is only one small file in bin

![sequencenumberissue](https://cloud.githubusercontent.com/assets/2449568/18368724/4a7734a8-75d6-11e6-9642-512490706591.gif)

**Comment by dbaeumer** [comment] 2016-09-09 07:33
If requests can be canceled inside VS Code that means they are still in the VS Code's queue. To allow cancelation we only sent requests to the tsserver one by one. In this situation it means that the tsserver is busy processing a request. @waderyan if this happens is there any unusual CPU usage with the tsserver?

**Comment by dbaeumer** [comment] 2016-09-09 07:44
In the specific example the quick info request never returns hence we don't send the rename request over the wire.

**Comment by dbaeumer** [comment] 2016-09-09 07:50
@waderyan do you have any errors in the dev console.

**Comment by mhegazy** [comment] 2016-09-09 19:16
Can you share the tsserver log in these cases?

**Comment by waderyan** [comment] 2016-09-09 19:18
@mhegazy where is the tsserver log? Is it different than what I'm seeing in the output window? 

@dbaeumer I will grab a screenshot of the dev console when I see it again. I have checked before and haven't seen any errors.

**Comment by mhegazy** [comment] 2016-09-09 19:20
first you need to set the environment variable `TSS_LOG=-level verbose`. there should be a log file written next to tsserver.js that would have the form of `.log[0-9]+`

**Comment by waderyan** [comment] 2016-09-13 15:43
I have not been able to reproduce this issue for the last couple of days. This issue came into day, and it might be related - https://github.com/Microsoft/vscode/issues/11938

Asked OP to follow the advise on capturing logs.

**Comment by waderyan** [comment] 2016-09-21 20:54
@mhegazy setting the env variable for logging is not working for me. 

Am I missing something?

![image](https://cloud.githubusercontent.com/assets/2449568/18728625/e9d1a9b2-8002-11e6-9c2e-194fd048eed5.png)

**Comment by mhegazy** [comment] 2016-09-22 19:13
that is mac? i am not a mac user, but i guess you should be are you using setenv to set it... or something

**Comment by waderyan** [comment] 2016-09-23 17:40
This came up again today. Here were the steps. 

```
mkdir test
cd test
yo node-express
# choose no for everything

code-insiders .
```

Go to `app.js`

Type `express.`

![image](https://cloud.githubusercontent.com/assets/2449568/18795591/2089630a-817a-11e6-8575-3dd2064e682a.png)

Note I am on release-2.0.5 bits. I was testing the auto acquire typings experience.

**Comment by waderyan** [comment] 2016-09-23 17:44
@mhegazy I setup the env variable properly. Can I specify the location for the log file?

**Comment by waderyan** [comment] 2016-09-23 17:48
@mhegazy I'm not seeing the log file in the location of `tsc.js`. Please advise. 

![image](https://cloud.githubusercontent.com/assets/2449568/18795834/3df5f6b4-817b-11e6-899f-2480ba05d665.png)

**Comment by mhegazy** [comment] 2016-09-23 23:26
> I setup the env variable properly. Can I specify the location for the log file?

yes, it should be something of the form `-log verbose -file filepath`

**Comment by mhegazy** [comment] 2016-09-24 00:27
I could not get this to repro locally using this yoman template. are there other things you did after opening `app.js`?

**Comment by waderyan** [comment] 2016-09-26 17:32
I did not do anything after opening `app.js`.

**Comment by waderyan** [comment] 2016-09-28 23:12
Saw the same issue today recreating @mousetrap's issue here. 

This is what I saw in the TypeScript output. 

See `TSServer exited with code: 7`. Do you know what that could be from? 

![image](https://cloud.githubusercontent.com/assets/2449568/18935523/6e50aa84-8595-11e6-953e-869e8e0c52fe.png)

I have the env variable setup correctly but I'm not seeing a log file. If someone could take a look at this too, that would be helpful. 

`export TSS_LOG="-log verbose -file /Users/waander/.tslog"

Also tried

`export TSS_LOG="-level verbose -file /Users/waander/.tslog"
 `export TSS_LOG="-level verbose -file '/Users/waander/.tslog'"

**Comment by waderyan** [comment] 2016-09-28 23:24
Here is another trace. 

![image](https://cloud.githubusercontent.com/assets/2449568/18935895/06dc8294-8598-11e6-8e4b-309ba45d885e.png)

**Comment by demeter-macik** [comment] 2016-10-07 15:33
Same issue.

Console:
![screenshot from 2016-10-07 17-31-39](https://cloud.githubusercontent.com/assets/15798474/19195961/f0111872-8cb3-11e6-861a-1926297fd365.png)
TypeScript output:

![screenshot from 2016-10-07 17-32-17](https://cloud.githubusercontent.com/assets/15798474/19195984/03197e96-8cb4-11e6-8c7d-b451b58c2f20.png)

Few minutes later tsserver had crashed. 
Crash report:
![screenshot from 2016-10-07 17-28-46](https://cloud.githubusercontent.com/assets/15798474/19195851/87402464-8cb3-11e6-8450-976aac9d8fbb.png)

![screenshot from 2016-10-07 16-46-24](https://cloud.githubusercontent.com/assets/15798474/19195789/45db0ae8-8cb3-11e6-8cd5-f3a7e867c9ee.png)

![screenshot from 2016-10-07 17-11-00](https://cloud.githubusercontent.com/assets/15798474/19195796/4b73ae56-8cb3-11e6-845d-7859694973f1.png)

**Comment by waderyan** [comment] 2016-10-07 16:14
@demeter-macik thank you for sharing these logs! 

@dbaeumer @mhegazy can you take a look at the logs above? anything stand out to you? 

Exit code 7 - do we know what that indicates?

**Comment by dbaeumer** [comment] 2016-10-11 07:46
Here is what I think happens: the tsserver gets busy. That is why it can't accept any requests anymore. This is why VS Code cancels all outstanding requests after some time. 

And then after a while the tsserver crashes. I am not sure about the exit code 7 but a node crash mostly happens because of out of memory.

**Comment by waderyan** [comment] 2016-10-11 17:09
@dbaeumer @mhegazy any thoughts on what could be holding tsserver up?

**Comment by dbaeumer** [comment] 2016-10-12 20:26
One thing that we see frequently before node runs out of memory is that most of the CPU time is spent in GC runs hence the VM is not able to process any other code. This would explain why the server is not responding anymore.

**Comment by waderyan** [comment] 2016-10-17 17:09
Saw this today. Grabbed these screenshots of the Activity Monitor when it occurred. 

![image](https://cloud.githubusercontent.com/assets/2449568/19447240/70b141b0-9451-11e6-8bb0-6ec2fcac3d70.png)

![image](https://cloud.githubusercontent.com/assets/2449568/19447258/88cb79fa-9451-11e6-8cac-c8261844e626.png)

My workspace was one file `test.js` with the following code. 

```
var _ = require('lodash');
```

I killed all the processes using up a large amount of memory. Did not resolve. 
I killed VS code and verified all processes were killed. Did not resolve.

**Comment by dbaeumer** [comment] 2016-10-17 18:26
@waderyan can you drag @mhegazy or @vladima in when you see this. You could alternatively add tsserver logging to get a trace of what is going on in the server.

**Comment by gitawego** [comment] 2016-12-09 08:35
got ``service died`` very often, the recent one is:
```
[Info  - 2:21:13 PM] Using tsserver from location: 
.../node_modules/typescript/lib/tsserver.js
[Error - 6:05:39 PM] TSServer exited with code: unknown
[Error - 6:05:39 PM] 'navtree' request failed with error.
Error: Service died.
    at /usr/share/code-insiders/resources/app/extensions/typescript/out/typescriptServiceClient.js:442:46
    at Array.forEach (native)
    at TypeScriptServiceClient.serviceExited (/usr/share/code-insiders/resources/app/extensions/typescript/out/typescriptServiceClient.js:441:37)
    at ChildProcess.<anonymous> (/usr/share/code-insiders/resources/app/extensions/typescript/out/typescriptServiceClient.js:362:35)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 6:05:39 PM] Using tsserver from location: 
.../node_modules/typescript/lib/tsserver.js
```

**Comment by ianmurrays** [comment] 2016-12-16 15:49
I'm constantly getting this error now for some reason.

```
TSServer exited with code: unknown
```

macOS 10.11.6
VSC 1.8.0

Using the global typescript installation gets rid of the error though:

```json
{
   "typescript.tsdk": "/Users/myuser/.nvm/versions/node/v4.4.0/lib/node_modules/typescript/lib"
}
```

**Comment by vladima** [comment] 2016-12-16 16:13
@ianmurrays can you please share a repro so we can try to isolate the root cause of the problem?

**Comment by con-ssc** [comment] 2017-01-30 09:43
```
[Trace - 10:17:47] Sending request: navtree (4). Response expected: yes. Current queue length: 2
Arguments: {}
[Trace - 10:19:26] TypeScript Service: canceled request with sequence number 16
[Error - 10:20:33] TSServer exited with code: 3
[Error - 10:20:33] 'navtree' request failed with error.
Error: Service died.
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:442:46
    at Array.forEach (native)
    at TypeScriptServiceClient.serviceExited (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:441:37)
    at ChildProcess.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:362:35)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 10:20:33] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js
```

**Comment by mhegazy** [comment] 2017-01-30 21:09
@con-ssc do you have a consistent repro for this?

**Comment by con-ssc** [comment] 2017-01-31 07:21
No, it is a customer project.

**Comment by con-ssc** [comment] 2017-01-31 07:25
I also encounter this a lot, when not starting as admin 
![image](https://cloud.githubusercontent.com/assets/8189808/22455742/d3df5d36-e78e-11e6-9c87-c74297202168.png)

```
[Info  - 08:23:01] Using tsserver from location: d:\repositories\git\aurelia-subscription-form\node_modules\typescript\lib\tsserver.js
[Error - 08:23:01] TSServer exited with code: 1
```

**Comment by mhegazy** [comment] 2017-01-31 18:42
Can you share the tssever log file. see https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-(tsserver)#logging.

you need to set the `TSS_LOG` environment variable to `-level verbose -file <path to file>`, start VSCode from the same console, and share the log with us.

**Comment by con-ssc** [comment] 2017-02-01 07:37
I'm afraid that is not possible since the tsserver is logging the whole file content and I can publish those files.

**Comment by mhegazy** [comment] 2017-02-01 17:44
feel free to redact parts you do not want to share. we care most about the set of actions before the error occurs.
Also we would be happy to sign any necessary NDA's to get access to the log and/or the code base.

**Comment by pocesar** [comment] 2017-02-09 21:04
getting "TSServer exited with code: 3" with 2.2.0-dev.20170209 randomly on a plain clone of https://github.com/rangle/typescript-react-redux-example

not sure if it's a problem with VSCode or TS nightly. When I try to see the dev tools on vscode, the editor freezes

**Comment by mhegazy** [comment] 2017-03-24 22:48
@pocesar, I am unable to reproduce this locally on latest. is this still an issue? if so can you share any more information to help reproduce the issue.

**Comment by mhegazy** [comment] 2017-03-24 22:50
There has not been any actionable leads in this issue. closing for now. If you are experiencing similar symptoms, please file a new issue and provide us with a project that you experience the server crash on, and/or [tssever log file](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-(tsserver)#logging).

**Closed by mhegazy** 2017-03-24 22:50 UTC
Labels: Bug, Needs More Info, VS Code Tracked
