### ISSUE TITLE
Suggestion: pure abstract classes shouldn't require 'super' call

### ISSUE THREAD

**Issue by jonathandturner** [Microsoft/TypeScript#4429] opened 2015-08-24 23:01 UTC
In this example:

```TypeScript
abstract class Fred { }

class Sam extends Fred {
    constructor() { }
}
```

We currently error on the constructor in Sam saying it's an error to not have a super() call.  But arguably Fred is a purely abstract, has no state, no initialization, and no constructor.  There doesn't seem to be a reason to enforce the super call in this example.

**Comment by danquirk** [comment] 2015-08-24 23:15
This is 'by design' so we'll need a spec bug as well if we decide to change this.

**Comment by RyanCavanaugh** [comment] 2015-08-25 17:55
How would we detect `Fred`'s pureness if it came from an ambient declaration?

**Comment by jonathandturner** [comment] 2015-08-25 20:23
Wouldn't it just look like 

```TypeScript
abstract class Fred { }
```

...in a .d.ts file?  We have to show the state and if it has a constructor, even in the .d.ts file, since that's part of the class's fully shape.

Wouldn't that be enough to know if you should require a constructor?

**Comment by RyanCavanaugh** [comment] 2015-08-25 20:43
What I mean is that these two classes have identical ambient declarations:
```ts
// Requires a super call
abstract class Fred {
  private p = 4;
}

// Does not require a super call
abstract class Bob {
  private p;
}
```
*In theory* we could say that the generated `Fred` declaration should have an empty constructor declaration, but I don't think people would know that was significant if writing .d.ts files by hand.

**Comment by jonathandturner** [comment] 2015-08-25 20:48
This is true.  I guess what I'm saying is that conservatively we can know for sure in some cases, while others might be ambiguous, so we would require them even if technically it's unnecessary.

If I'm following more of a "pure abstract" in the C++ sense (https://en.wikibooks.org/wiki/C%2B%2B_Programming/Classes/Abstract_Classes/Pure_Abstract_Classes).  Quoted: "A pure Abstract class has only abstract member functions and no data or concrete member functions."  The equiv for us would be "A pure abstract class has member functions and no data or constructor"

**Comment by mhegazy** [comment] 2015-10-02 21:38
Though the class is marked as abstract, the class do exist at runtime. as per the ES6 spec, super needs to be invoked. if all you need is the type, either implement the class, and not extend it, or define it as an interface.

**Closed by mhegazy** 2015-10-02 21:38 UTC
Labels: In Discussion, Suggestion
