### ISSUE TITLE
Object's "as const" assertion gets ignored and its values widen to string if the object gets an indexed type with string union.

### ISSUE THREAD

**Issue by An631** [microsoft/TypeScript#45689] opened 2021-09-02 02:05 UTC
## 🔍 Search Terms

string union exhaustive check
as const object indexed type 
const assertion indexed object 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [*] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [*] This wouldn't change the runtime behavior of existing JavaScript code
* [?] This could be implemented without emitting different JS based on the types of the expressions
* [*] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [*] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When using an object with an indexed type signature that uses a string union as its values, typescript should be able to exhaustively check all the possible values the string union can have. The current behavior widens the string union type instead making the exhaustive check not possible.

## 📃 Motivating Example

I have a string union type that is provided by someone else's package (I don't have control over it).
```
// Package type:
export type fruits = 'apples' | 'oranges' | 'berry'

```

I want to implement an object that lists all these values so that I can access them from the object instead of having to type the literal string everywhere it's used. Like this:
```
// My indexed object
const allFruits: {[key: string]: fruits} = {
    Apples: 'apples',
    Oranges: 'oranges',
    Berry: 'berry'
} as const
```
Notice I added 'as const' assertion which should make the values of the object be treated as literal strings.

The problem is that if I now try to use the values of the object in exhaustive checks the type of the values has been widened to string type and the 'as const' modifier has been ignored:
```

function fruitSalad(fruit: fruits) {
    switch(fruit) {
        case allFruits.Apples:
            return
        case allFruits.Oranges:
            return
        case allFruits.Berry:
            return
        default:
            assertNever(fruit)
    }
}

export function assertNever(x: never): never {
  throw new Error('Unexpected object: ' + x)
}
```

## 💻 Use Cases

The object works fine if I don't define a specific indexed type for it like this:

```
const allFruits = {
    Apples: 'apples',
    Oranges: 'oranges',
    Berry: 'berry'
} as const
```

But the issue is that with this the object can incorrectly accept any random string that might not be part of the string union type that I am trying to mirror.
Here is a [minimal repro in tsplayground ](https://www.typescriptlang.org/play?ssl=7&ssc=11&pln=3&pc=1#code/C4TwDgpgBAZgTgVwJbAM5QLxQOQEMxgA2Eq2UAPjgPZy4B2A5iWZdgEYRxwjYBQvAYyp1UwKLkKEAYohTosAb15QVUAIIFiqAFw58RZgBplqgPK1GJXdhr0mpY6qgAhTt2scuPXgF9x6IRFgfhgEOgFgJGFYWWAAZQlcABMACnhkYF10uQBKKCUnVAB3FAEACzTYvIKnVQFcVGgJaVjUADoNAx0TWtq4CGAEODoe2vrG8UkZDPbzOytR3pV+weHFuoamqda21y9tdd6VoZGlqCSIGFwEQkzD2obGuGAAOQgAN05KjJzRn19+BAAB5gGhiULhSLRR6cV4fL5A3R0eFwHJIlH5EzAMpwKhFKDI-EAUS4NBS2AAqsiQRAIhAklAqGwAFa0zI4KAAaigQN+-yAA)so that you can see the problem.

**Comment by MartinJohns** [comment] 2021-09-02 05:23
The `as const` is not ignored. Following the `as const` **your explicit type annotation** gets respected. If you don't want it to get widened to `string`, then.. don't tell the compiler to widen it to `string`..?

**Comment by fatcerberus** [comment] 2021-09-02 05:35
Based on the use case, it seems like maybe this is actually #45139 in disguise?

**Comment by fatcerberus** [comment] 2021-09-02 15:13
While you can't do this purely at the type level right now, what you *can* do is to write a constrained identity function:

[Click here for TS Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYgTgVwJbAM5QLxQOQEMxgA2Eq2UAPjgPZy4B2A5iWZdgEYRxwjYDcAUPwBmCOgGNgSKnShDEKVAB4AKlAgAPYBDoATdAG8oAbQDWEEAC4oqYHCSMAulfjI0UAL4A+ABTqrygEp+fX4oMKg4CGAEOBl1AXdBMWkbKFxCQhcFTFl5NG8Q8KgAQQJiVCs8MuYAGlDwgHlaRhJKmnomUjqigCFObkqOLh5u8IB6MagABSQGSrAaE2wasIm1Lhp+dwCBIA)

```ts
type Fruits = 'apples' | 'oranges' | 'berry';

function fruits<T extends { [key: string]: Fruits }>(x: T)
{
    return x;
}

const allFruits = fruits({
    Apples: 'apples',
    Oranges: 'oranges',
    Berry: 'berry',
    // Pig: 'pork',  // error
});
```

**Comment by andrewbranch** [comment] 2021-09-02 15:56
Yeah, I call this a duplicate of #7481

**Closed** 2021-09-07 18:00 UTC
Labels: Duplicate
