### ISSUE TITLE
map() type inference incomplete

### ISSUE THREAD

**Issue by ithinkihaveacat** [Microsoft/TypeScript#19868] opened 2017-11-09 11:30 UTC
**Code**

```ts
const foo = [1, 2, 3].map(() => [1, 2]);
const bar = new Map<number, number>(foo)
```

**Expected behavior:**

No error.

**Actual behavior:**

Type error: `Argument of type 'number[][]' is not assignable to parameter of type '[number, number][]'`. In this case, `foo` will always be of the form `[number, number][]`.

![screenshot from 2017-11-09 11 23 36](https://user-images.githubusercontent.com/51244/32603364-55c18956-c541-11e7-811e-b1bbb4423322.png)

**Comment by kitsonk** [comment] 2017-11-09 11:57
Essentially duplicate of #16360 (and several other related issues).  At the moment, tuple types are never inferred and have to be asserted.

**Comment by aluanhaddad** [comment] 2017-11-10 03:48
In the case of `Array.prototype.map`, you can write
```ts
interface Array<T> {
  map<U, V>(callbackfn: (value: T, index: number, array: T[]) => [U, V], thisArg?: {}): [U, V][];
}
const foo = [1, 2, 3].map(() => [1, 2]);
const bar = new Map(foo);
```
which will resolve this specific error.

**Closed** 2017-11-27 18:38 UTC
Labels: Duplicate
