### ISSUE TITLE
Object spread operator does not remove readonly when used with generics

### ISSUE THREAD

**Issue by dko-slapdash** [microsoft/TypeScript#55057] opened 2023-07-18 08:13 UTC
# Bug Report

Despite https://github.com/microsoft/TypeScript/issues/14058 works for non-generic types, it still remains `readonly` intact when generics are involved.

### 🔎 Search Terms

spread readonly generics

### 🕗 Version & Regression Information

All including beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-beta#code/MYGwhgzhAECyCeBhcUA8AVACgJwPYAcYBTADwBciA7AExgG9oBbIqMAcyIC5oIzsBLSm2gBfAHzQ6AWABQ0ecFyVe2AK7AyubAApZ8-dHyqARiH7BDeQgEZuDbETDUlIeNADaAaWiDoAayJ4XAAzaCwrCABdbnCCCC9IgG5RABo9A0MTMwt8CIAmO2gHJxc3ZlYObhVBYRF06ABKSTqZeuDVSmBtJuk5DMVlMmgiADcqMmtoAF5JaAA6BbIAC34IOdy4yZFE+v0B3mGxyjI86dmFueXV9fzRHdaH2Se+g1Hx6znyiHYiM4AiMDGYB-e4ZQ7jPKfFjfDj-QHA0HyFoiIA)

### 💻 Code

```ts
class MyClass<TProps extends { message: string }> {
   constructor(
      public props1: { readonly [K in keyof TProps]: TProps[K]; },
      public props2: { readonly message: string }
   ) {}

   func() {
      const event1 = { ...this.props1 };
      const event2 = { ...this.props2 };
      event1.message = "abc"; // error; why?
      event2.message = "abc"; // ok
   }
}
```

### 🙁 Actual behavior

Shows the error: "Cannot assign to 'message' because it is a read-only property".

<img width="687" alt="CleanShot 2023-07-18 at 01 12 26@2x" src="https://github.com/microsoft/TypeScript/assets/46383452/53cd3fc4-1866-4a25-8347-6479e949794d">

<img width="562" alt="CleanShot 2023-07-18 at 01 12 41@2x" src="https://github.com/microsoft/TypeScript/assets/46383452/12aace7a-acd6-4a46-92a6-98880c0d243b">

### 🙂 Expected behavior

Should allow assignment since spread operator creates the object's copy.

**Comment by fatcerberus** [comment] 2023-07-19 15:56
Looks like duplicate of https://github.com/microsoft/TypeScript/issues/53917

**Closed** 2023-07-27 01:29 UTC
Labels: Duplicate
