### ISSUE TITLE
The TypeScript tooling for VS2017 is broken

### ISSUE THREAD

**Issue by Kaelum** [Microsoft/TypeScript#17355] opened 2017-07-22 01:12 UTC
**Windows 10 Version 1607**

**Microsoft Visual Studio Enterprise 2017**
**Version 15.2 (26430.15) Release**

**TypeScript Version:  2.4.1 Release**

Using the exact same solution under VS2015 and VS2017, which uses "compileOnSave", VS2017 will not output "include" files to the "outDir" folder if you save a file listed under "files".  Only the "files" file that is being saved will be transpiled and written to disk.

VS2015 is definitely using version 2.4.1, and works correctly.  However with VS2017, it appears that the Tools / Options setting is being ignored and a random installed version of TypeScript is being used (somewhere in the path, or within NPM).  Running tsc.exe from a command prompt, works as expected.

**Comment by Kaelum** [comment] 2017-07-25 12:04
I'd also like to add that using Tools / Options to define the version of TypeScript being used is an extremely poor decision.  The project, or files within the project, should be the only factor in determining the version of TypeScript to use.  Otherwise, every developer could be using a different version of TypeScript for the exact same code, which is impossible to manage.

**Comment by bowdenk7** [comment] 2017-08-07 20:56
Hi @Kaelum, I believe the issue is with compile on save itself. There was a bug we fixed with compile on save but it won't ship until 15.3. Are you willing to try the [latest 15.3 preview](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-preview-relnotes) and tell us if it still a problem?

Also, I definitely agree the global TypeScript version isn't ideal. Pre-15.2 it wasn't possible to switch TS versions at all, so this was quick and temporary measure to enable users to switch versions until we implemented the full solution. You can also try out the project based TypeScript version tagging in 15.3. You can read more about it [here](https://github.com/Microsoft/TypeScript/wiki/Updating-TypeScript-in-Visual-Studio-2017).

**Closed** 2017-08-31 23:01 UTC
Labels: Needs Investigation, Visual Studio

**Comment by Kaelum** [comment] 2017-08-31 23:08
I forgot that I had this open here.  15.3 did not fix the issue.  The issue still exists, as VS2017 is not working in the same way that VS2015 does.  I believe that VS2015 is using the TSC.exe file watcher, while VS2017 is doing something else.  Because of this, it is not working.
