### ISSUE TITLE
TypeScript does not support bigint literals in type literal keys

### ISSUE THREAD

**Issue by lucacasonato** [microsoft/TypeScript#58532] opened 2024-05-14 13:54 UTC
### 🔎 Search Terms

- type literal
- bigint literal
- type literal key

### 🕗 Version & Regression Information

5.4.5

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/KYDwDg9gTgLgBDAnmYcCCcC8cDeAoOQuASwBNgA7GALgSgFdgAaAogIgGcYo3bvGWROAEY+DZq0LCKtAGYBDADYdgeAL4BuIA

### 💻 Code

```ts
export type A = {
    ident: true,
    "str": true,
    1: true,
    1n: false
};
```

### 🙁 Actual behavior

```
Property or signature expected.
';' expected.
Declaration or statement expected.
```

### 🙂 Expected behavior

1n is parsed correctly.

**Comment by MartinJohns** [comment] 2024-05-14 14:03
Duplicate of #35982.

**Closed** 2024-05-14 18:58 UTC
