### ISSUE TITLE
【Bug?】Optimization of d.ts

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/TypeScript#27135] opened 2018-09-17 09:37 UTC
**TypeScript Version:**  3.0.3

**Search Terms:** Optimization

**Code**
https://github.com/kgtkr/typeclass-ts/tree/c27ea953ea540289aaa32517c8f9487704588b29
↓
`npm run build`

**Expected behavior:**
`lib/index.d.ts`

```ts
export declare function Data<Props>(): <S extends Keys>(...impls: TypeClassImpl<S, Props>[]) => (props: Props) => ImpledData<Props, S>;
```

**Actual behavior:**
`lib/index.d.ts`

```ts
export declare function Data<Props>(): <S extends never>(...impls: TypeClassImpl<S, Props>[]) => (props: Props) => ImpledData<Props, S>;
```

**Playground Link:** 

**Related Issues:**

**Comment by andy-ms** [comment] 2018-09-18 00:12
`Keys = never` so this seems correct.

**Comment by DanielRosenwasser** [comment] 2018-09-18 04:14
Correct: https://github.com/kgtkr/typeclass-ts/blob/c27ea953ea540289aaa32517c8f9487704588b29/src/hkt.ts

**Comment by kgtkr** [comment] 2018-09-18 05:06
TypeScript has a function called Declaration Merging

This is incorrect
https://www.typescriptlang.org/docs/handbook/declaration-merging.html

**Comment by kgtkr** [comment] 2018-09-18 05:09
```ts
//Keys="Array"

declare module "typeclass-ts/lib/hkt" {
    interface HKT<T> {
        Array:T[]
    }
}
```

**Comment by andy-ms** [comment] 2018-09-18 17:05
Duplicate of #27171

**Closed** 2018-09-18 21:43 UTC
Labels: Duplicate
