### ISSUE TITLE
Suggestion: Difference Types

### ISSUE THREAD

**Issue by mattinsler** [Microsoft/TypeScript#15059] opened 2017-04-06 21:19 UTC
## The Problem

Let's say that we're building a redux-style connect method. In order to have well-enforced typing on the resulting component it would be useful to have the idea of a difference type.

```ts
interface Props {
  foo: number;
  bar: string;
}

class FooComponent extends React.Component<Props, void> {
  public render() { /* ... */ }
}

function mapStateToProps(state) {
  return { foo: state.something.value };
}

const Foo = connect(mapStateToProps)(FooComponent);

// Then, the following should pass type-checking
<Foo bar="baz" />
```

The way we could type the connect method would be as follows (sorry, it's long):

```ts
type ConnectMethod = <TState, TProps extends TStateProps, TStateProps>(mapStateToProps: (state: TState) => TStateProps) => (component: React.ComponentClass<TProps>) => React.ComponentClass<TProps - TStateProps>;
```

## Proposed Solution

The proposal is to add difference types. This would be where the keys of one interface could be subtracted from the keys of another interface.

The theoretical syntax would be to use a `-` to specify this.

```ts
interface Foo { foo: number; bar: string; }
interface Bar { bar: string; }
type Baz = Foo - Bar; // equivalent to { foo: number; }
```

**Comment by aluanhaddad** [comment] 2017-04-07 00:28
Duplicate of https://github.com/Microsoft/TypeScript/issues/4183

**Comment by AJamesPhillips** [comment] 2017-04-07 09:23
This is almost exactly my use case here as well:  https://github.com/Microsoft/TypeScript/issues/14626

**Comment by merrywhether** [comment] 2017-05-09 20:59
Yeah, this comes up a lot in the React ecosystem a lot due to the proliferation of HOCs in general. I've upvoted all the relevant issues, including #12215 which seems to be most likely to happen.

**Closed** 2017-05-09 22:23 UTC
Labels: Duplicate

**Comment by mattinsler** [comment] 2017-05-10 05:58
Great to see this is consolidating and moving along!
