### ISSUE TITLE
Define output folder and/or output file for declarations

### ISSUE THREAD

**Issue by NCC1701M** [Microsoft/TypeScript#5793] opened 2015-11-25 17:51 UTC
When using the declaration option the .d.ts files are all generated in the output directory of the .js files. Please provide an option to define the output directory and/or the output file for the declarations.

**Comment by mhegazy** [comment] 2015-11-26 01:03
We would like to limit the complexity of the number of options allowed by the compiler. Can you elaborate on if/why this is a blocking issue, and if using a build tool like grunt or gulp would address the issue.

**Comment by NCC1701M** [comment] 2015-11-26 06:42
I develop a web site with node.js. IDE is Visual Studio Code. I build and run the server witth Code.

At the server I have a data model and I like to use the data model classes or rather their definitions at the client side to. But I don't want to have multiple .d.ts files in the server output folder I need them as a single .d.ts file in the client source folder.

**Comment by mhegazy** [comment] 2015-12-01 21:49
so why not use a build system to manage this for you?

**Comment by NCC1701M** [comment] 2015-12-23 11:53
Tried several things to compile typescript, for example gulp, but I always had problems with the created  js files and their sourcemaps especially when I tried to debug. Only when compiling it with Visual Studio Code and tsc I kan debug correctly

**Comment by DanielRosenwasser** [comment] 2015-12-23 20:09
You might want to file a bug on the gulp plugin owner's repo. Was it [gulp-typescript](https://github.com/ivogabe/gulp-typescript)?

**Comment by NCC1701M** [comment] 2015-12-23 21:50
Yeah, I will file a bug, but my intention was, the change request, so that .d.ts files can be placed in an other directory, at least, they are some kind of "header files" for your .js-lib

**Comment by DanielRosenwasser** [comment] 2015-12-23 22:14
Actually, you'll need to amend the sourceMap URL for each produced file, so it might not be a bug on their end unless the tool specifically allows you to move produced .d.ts files.

**Comment by NCC1701M** [comment] 2015-12-28 06:14
Well I tried setting up the sourcemap url. Didn't work either

**Comment by DanielRosenwasser** [comment] 2015-12-28 17:45
How'd you go about amending the sourcemap url?

**Comment by mhegazy** [comment] 2016-02-23 00:01
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/6723

**Closed by mhegazy** 2016-02-23 00:01 UTC
Labels: Needs Proposal, Suggestion
