### ISSUE TITLE
Add `string` keyword to enum declaration to automatically generate identical key/values for the enum

### ISSUE THREAD

**Issue by dfoverdx** [microsoft/TypeScript#39755] opened 2020-07-26 21:35 UTC
## Search Terms

* `string enum`
* #feature-request tag (both open and closed)

## Suggestion

Many of our enums use identical strings and values.  In fact, my team never uses numeric enums (and I do only rarely).  It would be nice if there was a shortcut for this behavior.

## Use Cases

I'd use this whenever I make an enum with identical keys and string values.

### Current required syntax

```ts
enum ThingType {
  Type1 = "Type1",
  Type2 = "Type2",
}

const enum ConstType {
  Type1 = 'Type1',
  Type2 = 'Type2',
}

const type1 = ConstType.Type1;
const type2 = ConstType.Type2;

enum OverrideType {
  Type1 = 'Type1',
  Type2 = 'OverrideString',
  Type3 = 'Type3',
}
```

#### JavaScript output

```js
var ThingType;
(function (ThingType) {
    ThingType["Type1"] = "Type1";
    ThingType["Type2"] = "Type2";
})(ThingType || (ThingType = {}));
const type1 = "Type1" /* Type1 */;
const type2 = "Type2" /* Type2 */;
var OverrideType;
(function (OverrideType) {
    OverrideType["Type1"] = "Type1";
    OverrideType["Type2"] = "OverrideString";
    OverrideType["Type3"] = "Type3";
})(OverrideType || (OverrideType = {}));
```

### Desired syntax

```ts
string enum ThingType {
  Type1,
  Type2,
}

const string enum ConstType {
  Type1,
  Type2,
}

const type1 = ConstType.Type1;
const type2 = ConstType.Type2;

string enum OverrideType {
  Type1,
  Type2 = 'OverrideString',
  Type3,
}
```

#### Expected JavaScript output (identical)

```js
var ThingType;
(function (ThingType) {
    ThingType["Type1"] = "Type1";
    ThingType["Type2"] = "Type2";
})(ThingType || (ThingType = {}));
const type1 = "Type1" /* Type1 */;
const type2 = "Type2" /* Type2 */;
var OverrideType;
(function (OverrideType) {
    OverrideType["Type1"] = "Type1";
    OverrideType["Type2"] = "OverrideString";
    OverrideType["Type3"] = "Type3";
})(OverrideType || (OverrideType = {}));
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code  
  I'm pretty sure this syntax pattern is still available.
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by IllusionMH** [comment] 2020-07-27 10:01
Looks like duplicate of #16464

**Closed** 2020-08-01 18:00 UTC
Labels: Duplicate
