### ISSUE TITLE
error TS17004: Build: Cannot use JSX unless the '--jsx' flag is provided.

### ISSUE THREAD

**Issue by reyou** [Microsoft/TypeScript#7394] opened 2016-03-04 20:23 UTC
C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe "D:\Projects\FooProject\Foo.sln"

When I run this command I am getting "Build: Cannot use JSX unless the '--jsx' flag is provided." errors.

If I build solution from VS 2013 it is fine, am I missing any parameter to pass into msbuild for TypeScript specific?

**Comment by RyanCavanaugh** [comment] 2016-03-04 21:07
You should be able to set this in the project properties page, or in your tsconfig.json (depending on which you're using)

**Comment by mhegazy** [comment] 2016-03-04 21:58
For commandline options see https://github.com/Microsoft/TypeScript/wiki/Compiler-Options, these also map to tsconfig.json settings
For MSBuild projects, all these properties have a mapping to MSBuild properties. you can find the mapping in https://github.com/Microsoft/TypeScript/wiki/Setting-Compiler-Options-in-MSBuild-projects

**Comment by reyou** [comment] 2016-03-04 22:03
I have following settings;

 <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TypeScriptSourceMap>False</TypeScriptSourceMap>
    <TypeScriptNoEmitOnError>False</TypeScriptNoEmitOnError>
    <TypeScriptJsxEmit>react</TypeScriptJsxEmit>
  </PropertyGroup>

According to link you supplied;

--jsx	TypeScriptJSXEmit should be working fine. But msbuild still gives this error.

**Comment by mhegazy** [comment] 2016-03-04 22:08
tsconfig is not supported in VS2013. so that is not relevant to this discussion. can you share your project file? i am interested in the relative location of your `PropertyGroup` and the `import` to `Microsoft.TypeScript.targets`.

**Comment by reyou** [comment] 2016-03-04 22:14
Hello,

Here is all related tags with my webproject.csproj

```
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />
  <PropertyGroup>
   <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <TypeScriptToolsVersion>1.7</TypeScriptToolsVersion>
	 </PropertyGroup>
	  <ItemGroup>
    <TypeScriptCompile Include="JavaScript\Controllers\CategoryNews.ts" />
    <TypeScriptCompile Include="JavaScript\Controllers\NewsCategories.ts" />
	  </ItemGroup>
	  
	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TypeScriptSourceMap>False</TypeScriptSourceMap>
    <TypeScriptNoEmitOnError>False</TypeScriptNoEmitOnError>
    <TypeScriptJsxEmit>react</TypeScriptJsxEmit>
  </PropertyGroup>
  
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets')" />
  
  </Project>
```

**Comment by mhegazy** [comment] 2016-03-04 22:27
what version of TS are you using? This project seems to be working fine for me on the latest: https://github.com/Microsoft/TypeScript/releases/tag/v1.8.7

**Comment by reyou** [comment] 2016-03-04 22:55
OK, something weird is happening...
So if I run build from vs 2013 folder:

```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:24.93

C:\Program Files (x86)\MSBuild\12.0\Bin>
```

But if I run from "C:\Windows\Microsoft.NET\Framework\v4.0.30319" I am getting error at the first post.

I do not mind using build.exe under 12.0\Bin but the problem happens when I publish this project on Azure.

Please see related question at:

http://stackoverflow.com/questions/35473168/azure-website-cannot-register-typescriptbuildconfigurations-via-kudu

**Comment by mhegazy** [comment] 2016-03-28 22:16
is there a sample project we can look at?

**Comment by mhegazy** [comment] 2016-05-20 06:05
Closing for now. please reopen if you have a project we can look at.

**Comment by kamranayub** [comment] 2016-11-04 22:13
I can reproduce this on a fresh VS project. I cannot compile a React project because the TS targets are trying to execute and not looking at the JSX option in my tsconfig. It will work if I remove all the targets and compile manually, but VS will add the targets back as soon as I add a new TS file to the project.

[ReactVsTest.zip](https://github.com/Microsoft/TypeScript/files/572753/ReactVsTest.zip)

## Versions

```
Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA140
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA140
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA140
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-20000-00000-AA140
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   7.10.01020.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.20624.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9   14.0.20316.0
Azure App Service Tools v2.9

Bundler & Minifier   1.0.21
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DataFactoryProject   1.0
Microsoft Data Factory Package

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2016.2    Build 106.0.20160818.163633
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

Microsoft .NET Core Tools (Preview 2)   14.1.20624.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Data Factory Node Node   1.0
Azure Data Factory extension for Visual Studio Server Explorer.

Microsoft Azure HDInsight HQL Service   2.0.6000.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601

Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.40211.2

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40323.3

Node.js Tools   1.1.31117.00
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.1.31117.00
Profiling support for Node.js projects.

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Rebracer   1.0
Saves editor formatting settings as part of each solution.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

TechTalk SpecFlow   2015.1
TechTalk SpecFlow - Binding business requirements to .NET code, http://www.specflow.org
Copyright © 2009–2013 TechTalk

TypeScript   2.0.6.0
TypeScript tools for Visual Studio

Typewriter   1.8.1
Typewriter generates TypeScript files from c# code files using TypeScript Templates. This allows you to create fully typed TypeScript representations of server side API that automatically updates when you make changes to your c# code.

Visual Studio Tools for Apache Cordova   Update 10
Visual Studio Tools for Apache Cordova

Visual Studio Tools for Unity   2.1.0.0
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   14.0.25420.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Web Compiler   1.11.319
Compiler for LESS, Sass and CoffeeScript files

Web Essentials 2015.3   3.0.235
Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015

Windows Installer XML Toolset   3.10.2.2516
Windows Installer XML Toolset version 3.10.2.2516
Copyright (c) Outercurve Foundation. All rights reserved.

Xamarin   4.1.0.530 (2e39740)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.1.0.71 (4e27558)
Visual Studio extension to enable development for Xamarin.Android.

Xamarin.iOS   9.8.0.323 (39ebb77)
Visual Studio extension to enable development for Xamarin.iOS.
```

**Comment by mhegazy** [comment] 2016-11-07 21:20
@paulvanbrenk can you take a look.

**Comment by paulvanbrenk** [comment] 2016-11-07 21:34
The build action for the `tsconfig.json` has to be set to `Content`, not `None`. How did you add that file?

**Comment by sandersn** [comment] 2016-11-07 21:39
![capture](https://cloud.githubusercontent.com/assets/293473/20077034/90e0f166-a4ef-11e6-9ee7-e45d9cb955f7.PNG)

**Comment by kamranayub** [comment] 2016-11-07 22:27
I added a TS/JS file and renamed it to JSON. It's usually faster for me to
do that via right click menu than searching for the item in the Add Item
dialog. Who knew that made a difference?

**Comment by reyou** [comment] 2016-11-07 22:30
@kamranayub can you please try to build same project from "C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe" "C:\yourSolution.sln" 

I am just wondering you will be getting same error as me.

**Closed** 2016-12-06 23:45 UTC
Labels: Bug
