### ISSUE TITLE
type inference error on Union type with keyof

### ISSUE THREAD

**Issue by sidecus** [microsoft/TypeScript#40639] opened 2020-09-18 23:39 UTC
Seeing some type inference error with simple repro code. Not sure it's a bug or not so posting to get some insights.
Kindly note this is not a critical issue, I am just curious about the behavior.

**TypeScript Version:**  4.0.2 (tried 3.9 as well, same)
**Code**

```ts
class A {
    memberA: string = 'a';
}

class B extends A {
    memberB: string = 'b';
}

class C extends A {
    memberC: string = 'c';
}

class DummyMap<T extends A> {
    constructor(private obj: T) {
        this.obj = obj;
    }
    get<K extends keyof T>(key: K): T[K] {
        return this.obj[key];
    }
}

const map1 = new DummyMap(new B());
const func = (map: DummyMap<B> | DummyMap<C>) => {
    console.log(map.get('memberA')); // compiler error, incompatible signatures
}
func(map1);

//works
const map2: DummyMap<B> | DummyMap<C> = map1;
console.log(map2.get('memberA'));    // ok
```

**Expected behavior:**
First map.get should be able to compile.

**Actual behavior:**
![image](https://user-images.githubusercontent.com/4399408/93653146-7b918380-f9cc-11ea-958d-00989e7aea9d.png)

**Playground Link:**
[Playground repro](https://www.typescriptlang.org/play?ts=4.0.2&ssl=9&ssc=1&pln=13&pc=1#code/MYGwhgzhAECC0G8BQ1XQLYFN0CNMCdYAuaCAF3wEsA7Ac2gF5oByMZgbiQF8klRIYAIWiYAHmUzUAJjHjI0GbHnyCS5KnUYscHbr35RoAYRHjJMuIhRosuAkbUUa9Js2C6efcIYAiAV3R0AE8AWTAABwAeABVTCWlZAD4rBWAAe2p1P2AyNPwACnCqADcwCWg0nAArEmiAShSFNDIAC0oIADpKqq1uzgUeBVpMMkiAaTjzGABrTCC0gDNoaMT82aCSMbragG0xgF1Gpuh8Eb98amhW9q7qnfX9-rQeT3TMsgwIgEYtakwAd2g-kCoQi+T+gME+TqdU4b3I0AWfmowC0+W6JGBwTCUUEyQAPkCAtiIpEjIkGgxkvI0PC0iBMB0QGlaOjqh1hmR8sxbMpYMwYexoAB6YXQdLocKUBn4ET4fB5AA00BoEvCZUoOAZpEotGoZXOmAgeiRKPy6G+sN4ov+eWmxvhHwt4QATJjiaDcQSiSCcWTkkxnV84RkIPTGczWc6XRyRtzeQR+YKFKLoLb8PagA)

**Related Issues:**

**Comment by MartinJohns** [comment] 2020-09-19 12:13
Duplicate of #7294. Search terms used: `union callable`

**Comment by sidecus** [comment] 2020-09-19 18:21
@MartinJohns thanks! Sorry I should have done more searching before opening this. Is this still by design?

**Closed** 2020-09-23 18:00 UTC
Labels: Duplicate
