### ISSUE TITLE
Compiler ignores 'instanceof' type guard after throwing an error

### ISSUE THREAD

**Issue by Hanaasagi** [microsoft/TypeScript#53513] opened 2023-03-26 17:04 UTC
# Bug Report

### 🔎 Search Terms

`throw Error`, `never`, `instanceof`, `TS2339`, `Unreachable`

### 🕗 Version & Regression Information

TypeScript Version 5.0.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=24&ssc=1&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgJIDU4BsCuKDeAvgFDEJZwDOla4EA5tMsALYAOWELE4NG2eZPmLJkAN2wAuZCBwsARtADcpUQgD2ISmCg4EYdVAAUErNNkLoASiEjRyMAAtglAHSnkAXnHYVokiTEMDgg+sCayCGsHFw8kAAmRiyU9NLaUKD0VuYQYkzCok5Q6gDuMhBlAKJQxcYARKhgAOQ0Ueyc3HTxAITIdcgA1MjJWSqBwaFg4SDI8S5scGAIjkYAHtL8uBDZMnKKULaibTGdCUZNE2ERc5QLS45NVip2wDDIa8xaYHChEOpvqDojCgNgK9igEDAOCgM1W7l8dkCoghUJhyAADGNiEA)

### 💻 Code

I am using `instanceof` in a piece of code to execute different operations based on the type of a variable. The code can be compiled successfully after commenting out the `unimplemented` function call. However, if I use `unimplemented` to throw an exception, the type information is missing . In this case, the compiler throws TS2339.

```ts
interface IValue {}

class Integer implements IValue {
  val: number;

  constructor(val: number) {
    this.val = val;
  }
}

function unimplemented(msg: string): never {
  throw new Error("It's unimplemented! " + msg);
}

function dispatch(x: IValue): number {
  unimplemented('function dispatch');

  if (x instanceof Integer) {
    return x.val;
  }

  return 0;
}

```

### 🙁 Actual behavior

![2023-03-27_00-37](https://user-images.githubusercontent.com/9482395/227790486-06372798-a4e1-488c-a0d1-4e4f2f3d6994.png)

`Property 'val' does not exist on type 'IValue'.` is reported.

### 🙂 Expected behavior

The code can be compiled successfully even if there is unreachable code, and the type check of `instanceof` should not be ignored.

**Comment by fatcerberus** [comment] 2023-03-26 17:06
Duplicate of #26914.

**Closed** 2023-03-27 02:28 UTC
