### ISSUE TITLE
TypeError for quick info of property of `export =` class

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#12131] opened 2016-11-09 17:03 UTC
**TypeScript Version:**  2.0.3 / nightly (2.1.0-dev.20161109)

**Code**

```ts
/// <reference path="fourslash.ts" />

// @Filename: /node_modules/@types/foo/index.d.ts
////declare class Foo {
////    x: number | string;
////}
////export = Foo;

// @Filename: /a.ts
////import Foo = require("foo");
////function f(foo: Foo) {
////    return foo./**/x as number;
////}

verify.quickInfoAt("", "");
```

**Expected behavior:**

No error

**Actual behavior:** 

`TypeError: Cannot read property 'parent' of undefined`

**Comment by andy-ms** [comment] 2016-11-17 15:37
I've simplified this to:

```ts
/// <reference path="fourslash.ts" />

// @Filename: /node_modules/@types/foo/index.d.ts
////declare class Foo {
////    x: number | string;
////}
////export = Foo;

// @Filename: /a.ts
////import Foo = require("foo");
////declare const foo: Foo;
////foo./**/x;

verify.quickInfoAt("", "");
```

The error is in `getOuterTypeParametersOfClassOrInterface`: the symbol is an alias and has no `valueDeclaration`, so `declaration` is undefined, causing a crash inside `appendOuterTypeParameters`.
If the type of `x` is not a union, there's no such error. Not sure why that has any effect.

**Comment by mhegazy** [comment] 2017-08-23 20:09
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/14315

**Closed by mhegazy** 2017-08-23 20:09 UTC
Labels: Needs Investigation
