### ISSUE TITLE
Non-deterministic types inferred 

### ISSUE THREAD

**Issue by beerose** [microsoft/TypeScript#45364] opened 2021-08-08 12:34 UTC
# Bug Report

This bug report originates from https://github.com/blitz-js/blitz/issues/2609. 
I and other users started seeing `any` in VS Code where a type should be known. It appears quite randomly (at least for me) and disappeared after e.g. modyfing a file. It's quite non-deterministic, it happens only _sometimes_, and isn't that easy to reproduce consistently, but it does happen often. 

On the following screenshot you can see the type of `getProjects` function is inferred correctly to be `(input: { id?: number }, ctx: Ctx) => Promise<Project>`.

<img width="884" alt="actual type of get projects is inferred in the picture" src="https://user-images.githubusercontent.com/9019397/128630170-8e299372-a87e-4867-91fd-11f3508c9531.png">

However, after making some changes -- e.g. playing with destructuring fields from the second item in `useQuery` result in [projects/projectid.ts#L13](https://github.com/blitz-js/blitz/blob/canary/examples/auth/app/pages/projects/%5BprojectId%5D.tsx#L13)-- the type in the tooltip becomes `any`.

<img width="984" alt="getProjects type is inferred to be any in the picture" src="https://user-images.githubusercontent.com/9019397/128630121-0552fe3d-1570-4155-a0e7-02c14f129717.png">

I guess, some types are complex and take more time to compute (hence a VS Code lag?). The variable in question is returned from a `pipe` function with 11 overloads – can this be the problem?

I tested it with `tsc` in watch mode and `noImplicitAny: true`, and didn't see any errors from `tsc`.
However @ugogo [reported errors from `tsc`](https://github.com/blitz-js/blitz/issues/2609#issuecomment-889666647), so this may not be limited to language server.

#### **My issues/questions are:**
* Do you have any thoughts on what's happening there?
* How to debug these kind of issues, and how to get to know what's happening under the hood?

### 🔎 Search Terms

any, vscode lag, vscode any, inference problem, blitz, zod, prisma, non-deterministic

### 🕗 Version & Regression Information

Tested with TypeScript 4.3.3, 4.4.0-dev.20210803

- I was unable to test this on prior versions because Blitz doesn't work with TS versions lower than 4.3, and I'm unable to reproduce this problem in other codebases.

### ⏯ Playground Link

Unfortunately, the problem doesn't occur in the playground.
I'm attaching the link for completeness' sake: **https://tsplay.dev/Nd42YN**

### 💻 Code

```ts
// getProject is any
const getProject = resolver.pipe(resolver.zod(GetProject), resolver.authorize(), async ({id}) => {
  return "getProject's result" as const
})
```

I'm sorry, but I couldn't show the problem in a minimal code snippet. You can [see the Playground](https://tsplay.dev/Nd42YN) for all relevant code, but the surest way to reproduce this would be the following:

1. Clone _blitz-js/blitz_ repo: `git clone git@github.com:blitz-js/blitz.git` and go to `blitz` directory.
1. Install dependencies: `yarn` and build Blitz with `yarn build` or `yarn dev`.
1. Go to _examples/auth_ directory.
1. Codegen Prisma with `yarn blitz prisma migrate dev`.
1. Open the following files:
  a. _examples/auth/app/projects/queries/getProject.ts_
  b. _examples/auth/app/pages/projects/[projectId]/edit.tsx_
1. Start experimenting with the following line: https://github.com/blitz-js/blitz/blob/canary/examples/auth/app/pages/projects/%5BprojectId%5D/edit.tsx#L13 by destructuring different properties from the object in the second argument of the array. You should start seeing `any` for `project` after few tries. 

<img width="613" alt="project's type is any" src="https://user-images.githubusercontent.com/9019397/128632008-2464aaf8-bf4d-453a-86ef-5792a643be59.png">

### 🙁 Actual behavior

Types in VS Code tooltips are sometimes correct and sometimes `any` in a non-deterministic way.

### 🙂 Expected behavior

The type of the variable is always the same.

**Comment by MartinJohns** [comment] 2021-08-08 12:51
I've had an issue in the past that behaved very similar. It was deterministic, but very very weird and annoying to reproduce. It resolved itself after an automatic VS Code update. 🤷‍♂️ #40868

**Comment by gabritto** [comment] 2022-03-31 21:28
@beerose I know it's been a while, but are you still having this issue? are you using newer versions of TypeScript?
I tried playing around with the project using TS 4.7 nightly, and I couldn't get `any` for the type of `project`.

**Comment by gabritto** [comment] 2023-02-02 00:38
Closing this because I couldn't repro it and haven't received more feedback about it.

**Closed by gabritto** 2023-02-02 00:38 UTC
Labels: Needs Investigation, Rescheduled
