### ISSUE TITLE
Enumeration does not support string enumeration

### ISSUE THREAD

**Issue by ouy-o3o** [microsoft/TypeScript#47715] opened 2022-02-03 10:10 UTC
```javascript
enum B {
    'string' = 'B'
 }
 let key :string = B['B']
 let value :string = B["string"]
```
After compilation
```javascript
var B;
(function (B) {
    B["string"] = "B";
})(B || (B = {}));
var key = B['B'];
var value = B["string"];
```
It seems that the current enumeration does not support the mutual mapping of strings. Will it be supported in the future

**Comment by MartinJohns** [comment] 2022-02-03 12:21
You forgot to fill out the [issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md).

Duplicate of #21935. Used search terms: `enum mapping in:title`

**Closed** 2022-02-03 16:48 UTC
Labels: Working as Intended
