### ISSUE TITLE
Operator overloading？

### ISSUE THREAD

**Issue by takegine** [microsoft/TypeScript#55198] opened 2023-07-29 15:53 UTC
My usage scenario has implemented operator overloading. However, the type is still not supported on TS. Hopefully ts will provide a built-in generics that will allow me to omit strong conversion types。

```typescript

type __NumberLike = number & Record<Exclude<keyof number, 'toString'>, never>;

declare type Vector = __NumberLike & {...}
```

![image](https://github.com/microsoft/TypeScript/assets/64788603/d9e6de31-f556-4cd5-839c-dfef7da52ce7)
![image](https://github.com/microsoft/TypeScript/assets/64788603/bca297f9-fb7e-4633-9e24-28723abd2232)

**Comment by MartinJohns** [comment] 2023-07-29 15:55
You forgot to fill out the issue template for feature requests.

Sounds like a duplicate of #42218 / #5407.

**Comment by RyanCavanaugh** [comment] 2023-07-31 16:34
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Closed by RyanCavanaugh** 2023-07-31 16:34 UTC
