### ISSUE TITLE
Suggestion: Interfaces as string literals

### ISSUE THREAD

**Issue by park9140** [Microsoft/TypeScript#2902] opened 2015-04-24 03:57 UTC
I have been looking at dependency injection and a few issues with refactoring in regards to `_.pluck`.  One of the primary things I run into is that I want these things to enforce the interface for refactoring.

A few examples

Interface used as a symbol for dependency injection
```typescript
interface IExampleInterface {
  interfaceProperty: string;
}

function angularInjection(...fields: string[]) {
  return (target: Function) {
    target.$inject = fields;
  }
}

@angularInjection(nameof(IExampleInterface));
class Controller {
  constructor(injectedExample: IExampleInterface) {
  }
}
```
would compile to 
```javascript
function angularInjection() {
    var fields = [];
    for (var _i = 0; _i < arguments.length; _i++) {
        fields[_i - 0] = arguments[_i];
    }
    return function (target) {
        target.$inject = fields;
    };
}
var Controller = (function () {
    function Controller(injectedExample) {
    }
    Controller = __decorate([
        angularInjection('IExampleInterface')
    ], Controller);
    return Controller;
})();
```

In the case of an interface like pluck we could do something like this

```typescript
interface IExampleInterface {
  prop: string;
}

var items: IExampleInterface[] = [{prop: 'test1'},{prop: 'test1'}];
var props: string[] = _.pluck(items, nameof(IExampleInterface.prop));
```
would compile to
```javascript
var items = [{prop: 'test1'}, {prop: 'test1'}];
var props = _.pluck(items, 'prop');
```

In this way we could enforce some level of type safety in common javascript reflection use cases.

**Comment by RyanCavanaugh** [comment] 2015-04-24 17:48
Are we basically talking about C#'s `nameof` operator?

**Comment by park9140** [comment] 2015-04-24 18:07
Hadn't used it before but seems right.

**Comment by danquirk** [comment] 2015-04-24 19:19
Is this a dupe of #394 then?

**Comment by park9140** [comment] 2015-04-25 03:10
@danquirk, good point.  Guess i wasn't searching for the right things.

**Comment by park9140** [comment] 2015-04-25 03:36
@danquirk, seems to me that the initial suggestion on #394 is quite different.  This `nameof` methodology is primarily aimed at elmination of magic strings that cannot be refactored.  Specifically the pluck use case isn't solved by checking the literal argument.   The proposal in #394 is dangerous as noted in some of the comments and would either need runtime gating or to prevent all non literal strings from being parameters to a method describe with the `memberof` methodology.  It also does not handle using Interface names for injection purposes as the `nameof` methodology would.

**Comment by alex1kirch** [comment] 2015-05-12 14:29
I fully agree with @park9140.
Also, the operator 'nameof' can be used when working with Object.observe() method.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/observe
```javascript
// A user model
var user = {
  id: 0,
  name: 'Brendan Eich',
  title: 'Mr.'
};

// Create a greeting for the user
function updateGreeting() {
  user.greeting = 'Hello, ' + user.title + ' ' + user.name + '!';
}
updateGreeting();

Object.observe(user, function(changes) {
  changes.forEach(function(change) {
    // Any time name or title change, update the greeting
    if (change.name === 'name' || change.name === 'title') {
      updateGreeting();
    }
  });
});

**Comment by mhegazy** [comment] 2015-12-10 03:23
looks like another duplicate of  #3628

**Closed by mhegazy** 2015-12-10 03:23 UTC
Labels: Suggestion
