### ISSUE TITLE
Duplicate exclude paths (in subhierarchy) in tsconfig lead to complete ignorance

### ISSUE THREAD

**Issue by cookiengineer** [Microsoft/TypeScript#9590] opened 2016-07-09 15:21 UTC
The tsc binary falsely parses sub directories of the excludes Array. If you add multiple subpaths that have a `*/subpath` notation, the complete content of `*` will be parsed and all exclude entries will be ignored (not only the ones related to `*/`).

Take this example tsconfig.json:

```json
{
  "exclude": [
    "node_modules",
    "typings/globals",
    "typings/main"
  ]
}
```

Then the tsc compiler will _always_ parse the given subdirectories, even if they are inside the exclude array and even if there's another top-level path hierarchy. So in this case both node_modules and typings are parsed, that means the `typings/*` influence the parsing algorithm so that the `node_modules` entry will be ignored (even if it is parsed correctly itself).

On the other hand, if you only use the `most upper` directory path only, it will work:

```json
{
  "exclude": [
    "node_modules",
    "typings"
  ]
}
```

**Comment by mhegazy** [comment] 2016-07-10 04:09
@riknoll can you take a look.

**Comment by riknoll** [comment] 2016-07-11 18:11
I can't seem to reproduce this behavior. For example, given this set of files:

```
node_modules/a.ts
typings/globals/a.ts
typings/main/a.ts
typings/other/a.ts
typings/a.ts
a.ts
```

and this tsconfig.json:

```json
{
    "exclude": [
        "node_modules",
        "typings/globals",
        "typings/main"
    ]
}
```

The files that I see tsc including are the following:

```
typings/other/a.ts
typings/a.ts
a.ts
```

Can you give a more complete example of the file structure you have? Also, can you make sure that the files you are excluding aren't being included because of imports or triple slash references? That doesn't sound like the case since you said the other exclude pattern worked, but it's worth a check.

**Comment by cookiengineer** [comment] 2016-07-12 04:46
Jep, I'm gonna need some time. Going to make a small reduced test case demo today in a separate repository so that it's easier to follow. Added you as a collab so that we can freely tweak arount things there. ([Link to Repo](https://github.com/cookiengineer/typescript-9590))

**Comment by mhegazy** [comment] 2016-09-21 05:00
Is this still an issue? do you have a smaller repro?

**Comment by mhegazy** [comment] 2016-09-29 04:52
closing for now. please reopen of still an issue.

**Closed by mhegazy** 2016-09-29 04:52 UTC
Labels: Bug, Needs More Info
