### ISSUE TITLE
allow set Property not same as index type for object and array

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#24823] opened 2018-06-09 05:35 UTC
## Suggestion

allow set Property not same as index type for object and array

> Error:(6, 2) TS2411: Property ''$$'' of type 'T' is not assignable to string index type 'ITrieNode1<T>'.
> Error:(11, 2) TS2411: Property ''$$'' of type 'T' is not assignable to string index type 'ITrieNode2<T>'.
> Error:(22, 2) TS2412: Property '0' of type 'true' is not assignable to numeric index type 'string'.

```ts
export interface ITrieNode1<T = number>
{
	[k: string]: ITrieNode1<T>,

	'$$'?: T,
}

export interface ITrieNode2<T = number> extends _ITrieNode<T>
{
	[k: string]: ITrieNode2<T>,
}

export interface _ITrieNode<T = number>
{
	'$$'?: T,
}

export interface IArrayOnlyFirstIsBool
{
	[index: number]: string;
	0: true;
}
```

## Use Cases

for only wanna special property has other type

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment] 2018-06-11 19:48
Duplicate of https://github.com/Microsoft/TypeScript/issues/17867

**Closed** 2018-06-28 23:04 UTC
Labels: Duplicate
