### ISSUE TITLE
`keyof` retrieve invalid type

### ISSUE THREAD

**Issue by nullndr** [microsoft/TypeScript#50138] opened 2022-08-02 08:49 UTC
# Bug Report

The `keyof` operator retrieve an incorrect type with mapped types

### 🔎 Search Terms

keyof

### 🕗 Version & Regression Information

4.7.4
4.8.0-beta

### ⏯ Playground Link

[Version 4.7.4](https://www.typescriptlang.org/play?ts=4.7.4#code/LAKALgngDgpgBAMQPZLgXjgb1HXcDaA1jBAFxwDOYATgJYB2A5gLrkCG9EoAvqKJLDgAhNtXRYceIiXJU6TVnA5cQeOAAZ2nHnxAB6PUri0KcAAb0ArgFsARjDEAfSjQaMzoAMZJ6VJeWIIJAAzRBRxdV0DOFtjUzNAkOFRDxBvXzAYgJIkkTEMdSA)

[Version 4.8.0-beta](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/LAKALgngDgpgBAMQPZLgXjgb1HXcDaA1jBAFxwDOYATgJYB2A5gLrkCG9EoAvqKJLDgAhNtXRYceIiXJU6TVnA5cQeOAAZ2nHnxAB6PUri0KcAAb0ArgFsARjDEAfSjQaMzoAMZJ6VJeWIIJAAzRBRxdV0DOFtjUzNAkOFRDxBvXzAYgJIkkTEMdSA)

### 💻 Code

```ts
type Foo = {
    [key: string]: any
}

type Bar = {
    [key: string]: any
    0: any
}

// a is `number | string`
const a: keyof Foo = 0

// b is `keyof Bar`
const b: keyof Bar = 1
```

### 🙁 Actual behavior

`a` is of type `number | string`, but it should be only `string` or `keyof Foo`, it should not accept numbers.

`b` is of type `keyof Bar`, but it can accept `1`, while it should not.

### 🙂 Expected behavior

`a` to be `string` or `keyof Foo`, accepting only strings.

`b` to accept strings or `0`

**Comment by MartinJohns** [comment] 2022-08-02 08:56
Duplicate of #48269.

**Closed** 2022-08-02 09:00 UTC
