### ISSUE TITLE
Type inference with multiple type parameters

### ISSUE THREAD

**Issue by biqas** [Microsoft/TypeScript#7491] opened 2016-03-12 17:38 UTC
**TypeScript Version:** 

1.9.0-dev / nightly (1.9.0-dev.20160311)

**Code**

```ts
class ModelA<T extends BaseData>
{
    public prop : T;
    
    public constructor($prop : T) { }
    
    public Foo<TData, TModel>(
        $fn1 : ($x : T) => TData,
        $fn2 : ($x : TData) => TModel) { }
        
    public Foo1<TData, TModel extends ModelA<any>>(
        $fn1 : ($x : T) => TData,
        $fn2 : ($x : TData) => TModel) { }
        
    public Foo2<TData extends BaseData, TModel extends ModelA<TData>>(
        $fn1 : ($x : T) => TData,
        $fn2 : ($x : TData) => TModel) { }
}

class ModelB extends ModelA<Data> { }

class BaseData
{
    public a : string;
}

class Data extends BaseData
{
    public b : Data;
}

class P
{
    public static Run()
    {
        var modelA = new ModelA<Data>(new Data());
        
        modelA.Foo(x1 => x1.b, x2 => new ModelB(x2));
        
        modelA.Foo1(x1 => x1.b, x2 => new ModelB(x2));
        
        // Why is this not working??? inferred type for x2 : BaseData
        modelA.Foo2(x1 => x1.b, x2 => new ModelB(x2)); // Error
    }
}
```

**Expected behavior:**
modelA.Foo2 call should infer the type.

**Actual behavior:** 
Is not inferring the actual type.

**Comment by vsiao** [comment] 2016-03-13 01:38
looks like #7234

**Comment by mhegazy** [comment] 2016-03-29 00:22
indeed a duplicate of #7234

**Closed by mhegazy** 2016-03-29 00:22 UTC
Labels: Duplicate
