### ISSUE TITLE
Destructuring types

### ISSUE THREAD

**Issue by splincode** [Microsoft/TypeScript#29792] opened 2019-02-07 08:02 UTC
## Suggestion

Add the possibility of multiple restructuring for types

## Use Cases

Now you can import everything that is inconvenient when many types are exported from a file.

## Examples

table-dk-builder.interfaces.ts

```ts
export interface TableRowDataSource<T = any> {
    [key: string]: T;
}

export interface TableDkBaseInterface {
    drop(event: CdkDragSortEvent): void;
}

export type RowKey = string | number;

... etc
```

my.component.ts

```ts
import * as TableInternals from 'table-dk-builder.interfaces';

type { TableRowDataSource,  RowKey } = TableInternals;
type { TableDkBaseInterface } = TableInternals;

class A {
 public invoke(key: RowKey) {
   ...
  }
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment] 2019-02-07 09:00
Looks like a duplicate of #13135.

**Closed** 2019-02-07 09:07 UTC
