### ISSUE TITLE
Optional function argument type mismatch

### ISSUE THREAD

**Issue by d07RiV** [microsoft/TypeScript#54827] opened 2023-06-29 14:01 UTC
# Bug Report

### 🔎 Search Terms

function optional argument parameter mismatch

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcAUAPAXIsIC2ARgKYBOANIgJ455FmIC8iAjAJSIDeAsAFCIDEpYlBCkkGRAGpqfAL58oVAA7FEAMRZNEmWgRKkOjAHy59ZRSrXqATNt1n6FagH4cAZyikYYAOZHTOgM+PggET2QWHE1tFDhQ8KhkG2i7ZmAWEN4wsHc4ABtiADp8uF80YBs0FkoAcgBDWrY2IA)

### 💻 Code

```ts
function foo(x: number, y: number = 1) {
    return x + y
}
type F1 = (x: number) => number
type F2 = (x: number, y?: string) => number

const f1: F1 = foo
const f2: F2 = f1

console.log(f2(1, 'a'))
```

### 🙁 Actual behavior

The code compiles without errors/warnings, despite an obvious type mismatch

### 🙂 Expected behavior

Should probably complain when narrowing function type from F1 to F2

**Comment by fatcerberus** [comment] 2023-06-29 14:11
I think this is intentional, as it's equivalent to the (also intentional) type hole that exists with optional properties:
```ts
const foo = { x: 777, y: 1206 };
type O1 = { x: number };
type O2 = { x: number, y?: string };

const o1: O1 = foo;
const o2: O2 = o1;
console.log(o2.y);  // oops, not a string
```

**Comment by MartinJohns** [comment] 2023-06-29 14:12
Duplicate of #13043.

**Closed** 2023-07-01 18:00 UTC
Labels: Duplicate
