### ISSUE TITLE
does typescript suppose to treat template literals same as strings as in concatenated strings

### ISSUE THREAD

**Issue by veeramarni** [Microsoft/TypeScript#18686] opened 2017-09-22 14:12 UTC
Would it be right that typescript treat template literals and concatenated string as same?

**TypeScript Version:**  2.4.2
**Code**

```ts
const PATH = '@@test/';
export const LOGGING_IN = `${PATH}LOGGING_IN`;
// export const LOGGING_IN = PATH + 'LOGGING_IN';
export type Actions = {
    LOGGING_IN: {
        type: typeof LOGGING_IN,
        payload: {
            isLoggingIn: boolean,
        },
    },
};
export const actionCreators = {
    loggingIn: (isLoggingIn): Actions[typeof LOGGING_IN] => ({
        type: LOGGING_IN,
        payload: {
            isLoggingIn,
        },
    }),
};


```

**Expected behavior:**
No type error
**Actual behavior:**
[ts] Type 'Actions' has no matching index signature for type 'string'.

**Comment by andy-ms** [comment] 2017-09-22 14:16
It doesn't work if I use the commented-out code instead though?
The type of the concatenation of two strings is always `string` -- we don't do anything smart and give you a string literal type. So `typeof LOGGING_IN` is just `string`. So `Actions[typeof LOGGING_IN]` is just `Actions[string]`, but `Actions` can't be indexed by an arbitrary string.
Note that using `Actions["LOGGING_IN"]` as the return type would work in your example; the name of the property in `Actions` is "LOGGING_IN" and has no relation to the `const` of the same name.

**Comment by mhegazy** [comment] 2017-09-22 17:50
The type system does not do literal type arithmetic operations, (or concat for strings). these all result in strings.

**Comment by mhegazy** [comment] 2017-09-22 17:50
duplicate of https://github.com/Microsoft/TypeScript/issues/15382 and https://github.com/Microsoft/TypeScript/issues/6579

**Comment by mhegazy** [comment] 2017-10-09 16:49
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-09 16:49 UTC
Labels: Duplicate
