### ISSUE TITLE
Don't translate unicode in template literals to `\u123`

### ISSUE THREAD

**Issue by Zzzen** [Microsoft/TypeScript#10031] opened 2016-07-29 15:18 UTC
**TypeScript Version:**  1.8.10
**Code**

```
// index.ts
const str = "なに";
const template = `なに`;

// index.js
var str  = "なに";
var template = "\u306A\u306B";
```

Why is unicode in template literals changed?

**Comment by DanielRosenwasser** [comment] 2017-01-24 20:47
Duplicate of #10498.

**Closed by DanielRosenwasser** 2017-01-24 20:47 UTC
