### ISSUE TITLE
User-defined type guards with ternary operator 

### ISSUE THREAD

**Issue by k8w** [Microsoft/TypeScript#30864] opened 2019-04-11 14:46 UTC
## Search Terms
`type guards ternary`

## Suggestion

Support to use dser-defined type guards with ternary operator 

## Use Cases

More complex type guards function

## Examples

```ts
function checkAnimal(animal: Animal)
  : animal is Cat ? 'Cat'
    : animal is Dog ? 'Dog'
    : animal is Animal
{
  // ...
}

let value: any;
let checkResult = checkAnimal(animal);

if(checkResult === 'Cat'){
  // value is Cat now
}
else if(checkResult === 'Dog'){
  // value is Dog now
}
else if(checkResult){
  // value is other Animal
}
else{
  // value is not Animal
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by zpdDG4gta8XKpMCd** [comment] 2019-04-11 15:38
conditional types can do it:

```
   type NameOfAnimal<A> = A extends Cat ? 'cat' : A extends Dog ? 'dog' : A extends Animal ? 'animal' : never;
   function checkAnimal<A extends Animal>(animal: A): NameOfAnimal<A> { ... }
```

**Comment by nmain** [comment] 2019-04-11 16:09
> conditional types can do it:

That won't work as a type guard, since TS will statically infer `<A>` (or you'll need to statically specify it).

http://www.typescriptlang.org/play/#src=interface%20Animal%20%7B%0D%0A%20%20%20%20%20%20%20%20ugly%3A%20boolean%3B%0D%0A%7D%0D%0Ainterface%20Dog%20extends%20Animal%20%7B%0D%0A%20%20%20%20%20%20%20%20noisy%3A%20boolean%3B%0D%0A%7D%0D%0Ainterface%20Cat%20extends%20Animal%20%7B%0D%0A%20%20%20%20%20%20%20%20annoying%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0A%0D%0Atype%20NameOfAnimal%3CA%3E%20%3D%20A%20extends%20Cat%20%3F%20'cat'%20%3A%20A%20extends%20Dog%20%3F%20'dog'%20%3A%20A%20extends%20Animal%20%3F%20'animal'%20%3A%20never%3B%0D%0Adeclare%20function%20checkAnimal%3CA%20extends%20Animal%3E(animal%3A%20A)%3A%20NameOfAnimal%3CA%3E%3B%0D%0A%0D%0Adeclare%20const%20a%3A%20Animal%0D%0Aif%20(checkAnimal(a)%20%3D%3D%3D%20%22dog%22)%20%7B%0D%0A%0D%0A%7D%0D%0A

**Comment by nmain** [comment] 2019-04-11 16:14
Seems to be a duplicate of https://github.com/Microsoft/TypeScript/issues/30698

**Comment by zpdDG4gta8XKpMCd** [comment] 2019-04-11 16:21
your example is not type narrowing it's type extending (into unknown) although i see what you mean, it looks like a poor design to me, sorry for being rude

**Comment by zpdDG4gta8XKpMCd** [comment] 2019-04-11 16:35
which throws us to the [expression problem](http://wiki.c2.com/?ExpressionProblem) which practically says that oop is a bad idea in general

**Closed** 2019-04-12 10:52 UTC
Labels: Duplicate
