### ISSUE TITLE
Generic parameters info is not inferred in conditional types over ancestor

### ISSUE THREAD

**Issue by mmiszy** [microsoft/TypeScript#55146] opened 2023-07-25 09:50 UTC
# Bug Report

In conditional type over an interface `X`, `infer` seems not to work for generic parameters when applied to interface `Y extends X`.

### 🔎 Search Terms

generic, infer, conditional, interface, extends

### 🕗 Version & Regression Information
It occurs in all tested versions – including latest, nightly, and some older ones.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230720#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgEQmwFcBbYFAFQE8xh9htpMYEIkAeSgJWAGdiAGxgAaOJQBqmKAkwAjQfwB8cAN4BfALAAoUJFiIUaLLnG1gAE0IlyKAHIQLwLrwHCxk6bIXK4oVEgWfAREZBQwNHQMTFAsbJw8-EKi4lIy8op8Kho6Ok7YgtJ4TEh88OgQEABcZnRWobYwDk4cqhXVcGUySADm6mKqctI1Xch9SgDcubrg0PAw5nCuyQDy6ACMXCoAvOJ+IAFBITbhkfSMzKzsHMjoaEtJwmdit-dp3plnSjpwcAD8DzcEXMPzgNSQwAAbmgpjN9PNFsthGsAExbOC7Sj7Q7BM71E72RzOV5QQHJZ6GO6k94ZfhfUEApHAuig8FQmHTHQLOhk4TrDG8mBrTbc4AQdBwdqTOAAehlcGISAA1kgIAB3JBiPSMVAWOAwCBwOR4NqVEYwbp9LmIx4wFECpmojii8WSyrSuVwHoQeCmjqjXrqOCYYLa7C6nRAA)

### 💻 Code

```ts
export interface DocumentTypeDecoration<TResult, TVariables> {}
export interface TypedDocumentNode<TResult, TVariables> extends DocumentTypeDecoration<TResult, TVariables> {}

declare const foo: TypedDocumentNode<{foo: string}, {bar: string}>;

export type ResultOf1<T> = T extends DocumentTypeDecoration<infer ResultType, infer VariablesType>
  ? ResultType
  : never;
export type ResultOf2<T> = T extends TypedDocumentNode<infer ResultType, infer VariablesType>
  ? ResultType
  : never;


type Result1 = ResultOf1<typeof foo>; // unknown, expected to be {foo: string}
type Result2 = ResultOf2<typeof foo>; // got {foo: string} as expected
```

### 🙁 Actual behavior

Got `unknown`.

### 🙂 Expected behavior

Expected to get `{foo: string}`.

**Comment by MartinJohns** [comment] 2023-07-25 09:54
Because you have unused type parameters.

[Why doesn't type inference work on this interface: `interface Foo<T> { }`?](https://github.com/microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot--)

> Remember: You should *never* have unused type parameters!

**Comment by mmiszy** [comment] 2023-07-25 09:55
Yes, but it does work for `Result2`. What's the difference?

**Comment by MartinJohns** [comment] 2023-07-25 10:00
And it will work for `Result1` when you use `DocumentTypeDecoration` directly. I don't know the details of how the inference algorithm works, but there's no guarantee anything meaningful is resolved when you don't use the parameters. Once you actually use them it will resolve correctly:

> export interface DocumentTypeDecoration<TResult, TVariables> { r: TResult; v: TVariables }

**Comment by mmiszy** [comment] 2023-07-25 10:02
Yes, thank you, that's my question. Why does it allow inferring over unused type parameters in this case but doesn't in another one.

**Comment by MartinJohns** [comment] 2023-07-25 10:13
That I don't know. Like I said, I don't know the implementation details of the compilers algorithms in detail. It's probably just an edge case where the type parameter can be taken directly from the declared type, instead of having to actually perform an inference by navigating the type backwards. Maybe someone else can chime in, but generally this repository is not meant for questions.

All I can say is that it's working as intended. [This issue](https://github.com/microsoft/TypeScript/issues/53750#issuecomment-1505467567) is basically the same and closed as `Working as Intended`. Or [this issue](https://github.com/microsoft/TypeScript/issues/40796#issuecomment-699678161).

**Comment by Andarist** [comment] 2023-07-25 11:33
> Why does it allow inferring over unused type parameters in this case but doesn't in another one.

it's because `foo` is typed using `TypedDocumentNode` and `ResultOf2` matches that type alias specifically. So this one is just inferring between those type parameters *directly*. With `ResultOf2` TS infers between contained structures and since your type parameters are unused they don't appear in any position that could act as an inference source.

**Closed** 2023-07-28 01:31 UTC
Labels: Not a Defect
