### ISSUE TITLE
Presence of a binding pattern changes inference for callback function parameters

### ISSUE THREAD

**Issue by yifanwww** [microsoft/TypeScript#43605] opened 2021-04-09 05:28 UTC
# Bug Report

### 🕗 Version & Regression Information

This bugs occurs in typescript 4.2.3, 4.2.4 and 4.3.0-beta, I didn't test the older typescripts.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/PTAEBcE8AcFNQCawGYEsB2ryoPboM6j6oC20ANqmrAqMgE44mgAGAAvTQK4AeAVvmDgcOcgGssLADStOAQwDG4FqDnpaLeUoC0nBLxYBYAFAmocUABFU+aHPAKAFgB4AgqAC8oAN4QYsAC5VdEgAblAAbVgecHo5AAVGaHwg-FiMAHMAXSC1SFAAXwA+Tx9QZwAVUGjwWHVCVyKACkVsPCCKgEoOwtCTJAVyOU46LnQlXHRQLnxYAFlYEhxK5uRWnHpIIKbOzxKKmSRkoIAlWDkEPHJIV3o4yGc8koAfafUUDBpu0Aq+4wGhiNkGMJnhprNrLZ7E5KpC7A5HKU4dCXE9mt8KsiEX8TCBQABJSywNL0LhKLj0TKgABkVmJsTJ4ApmRMZn8BIAYiDCF5fPJLuhrpExLAtkR0uhstsAHSy6C5EK7DwlABuOFQtAKOOM5nghPppPJlMllWqMTqCEI+K543wJV5oH5V3yERF+QwoDdOGQPyyAH4ZXKgvFhnISLBavR8JVXaKskUlar1Zrtbq6STGcyTVUaharTaFPgZABVM21eoEokZo2ZFb20BNBA2eFOIJYmFPGTA20dROgYvavHd0EEVnGBR4NKjW0ARlK3hMoCX04Urm2ciCACMRORzuhvmqNXsfAUpIvl8OAELbTepCUZGSb2-i40ZA-J4-eU-npfDgDC2wKEE6BcCQm6wPQMgKEBoAgWBEFQdBW47nu75HsqJ5nsYWomBOBDgCu+AAEzzj+K6WNsCDIaIqFBIetAYV+WHLiuACi2yBC+mQyLAnEkpkaEMSUTFkcOHLbMgwGgeBkF0JJsHSQhcnyduNFqIJn7fthqbshUBb4HOXi6t6hEzn8aZ6dyJFGf4JnDsRg5gFoBGOCIYj4GOw5tFMMywGc+g8O2jgzqauYVvq1ZMq+lT6TORTNEgkVZhkbYGpm0WWbOMgVAmPQLsYLGcFFPmzAsSxNDsx5NL4srSolDI1pKTS+UFOxdtyM67AUnQyBEWSdH8BSeSC3ngn53CBc2KJEZUc5hZalZpY1GQxR1RTZSR81WlWDVRbWmWFkR8VNGR9WGntkozqlSUZbF2Vxcxy5nelmREddu3JattpERt60mBic60hUJH5YVEYUiV8yLDgFV9tVoC1c9y0zs1EJTQibWmT1COykjF0ZERqOwK12P2URXXY31A0mENpjGHitRTtEYYUMSY6+f5vBBSjZGNl2cO+MOa4NrV0B9ggTTINKQtNKLnSkyCAEi3K4uS9LiuyyrFP-dqeFTgA+qUHMTdzJ0FcufN0ALK7C5r0pi8eEtSzLcsK+M17K-bqvOyCl522L2vGNTdN6wRgsgq47Xu1HCh-oURuzJzk1QgiPPm0ulvINbQuBl7jtq1e-vyzHHtF-nPvu0Xbux7nDsYU76vjH+VeFJ0Ovs4nJvo04hO8wg-NVeH7u197jcKH7rsx0rZf1wXGuu63j0Z-3VuD+RI-l2PlhVzH4me3XJQN2JLfdVhwe4ZOYc20E+tC1PN--jHrG7-HXjGwFQW9+nDYr1na85-vUeLstb30AZvf8J8ep9wHhheGw52JgNnhXBQrEd4rj3jPQ+c9xgckgWfP4QA)

### 💻 Code

```ts
// type definitions simplified from `@reduxjs/toolkit`, `react` and `react-redux`

type Dispatch<A = { type: any; [extraProps: string]: any }> = { <T extends A>(action: T): T };
declare function useMemo<T>(factory: () => T, deps: ReadonlyArray<any> | undefined): T;
declare function useDispatch<TDispatch = Dispatch<any>>(): TDispatch;

// IDestructuring & Destructuring

type IFuncs = { readonly [key: string]: (...p: any) => void };

type IDestructuring<T extends IFuncs> = { readonly [key in keyof T]?: (...p: Parameters<T[key]>) => void };

type Destructuring<T extends IFuncs, U extends IDestructuring<T>> = (dispatch: Dispatch<any>, funcs: T) => U;

// functions

const funcs1 = {
    funcA: (a: boolean): void => {},
    funcB: (b: string, bb: string): void => {},
    funcC: (c: number, cc: number, ccc: boolean): void => {},
};
const funcs2 = {
    funcD: (d: boolean): void => {},
    funcE: (e: string, ee: string): void => {},
    funcF: (f: number, ff: number, fff: boolean): void => {},
};

type TFuncs1 = typeof funcs1;
type TFuncs2 = typeof funcs2;

// react hooks

function useReduxDispatch1<T extends IDestructuring<TFuncs1>>(destructuring: Destructuring<TFuncs1, T>): T {
    return useMemo(() => ({ ...destructuring(useDispatch(), funcs1) }), []);
}

function useReduxDispatch2<T1 extends IDestructuring<TFuncs1>, T2 extends IDestructuring<TFuncs2>>(
    destructuring1: Destructuring<TFuncs1, T1>,
    destructuring2: Destructuring<TFuncs2, T2>,
): T1 & T2 {
    return useMemo(() => ({ ...destructuring1(useDispatch(), funcs1), ...destructuring2(useDispatch(), funcs2) }), []);
}

// test examples

useReduxDispatch1(
    (d, f) => ({ funcA: (...p) => d(f.funcA(...p)), funcC: (...p) => d(f.funcC(...p)) })
);

const _ = useReduxDispatch1(
    (d, f) => ({ funcA: (...p) => d(f.funcA(...p)), funcB: (...p) => d(f.funcB(...p)) })
);

const { funcA, funcB, funcC } = useReduxDispatch1(
    (d, f) => ({ funcA: (...p) => d(f.funcB(...p)), funcB: (...p) => d(f.funcB(...p)), funcC: (...p) => d(f.funcC(...p)) })
);

useReduxDispatch2(
    (d, f) => ({ funcB: (...p) => d(f.funcB(...p)), funcC: (...p) => d(f.funcC(...p)) }),
    (d, f) => ({ funcD: (...p) => d(f.funcD(...p)), funcF: (...p) => d(f.funcF(...p)) }),
);

const { funcA: _funcA, funcC: _funcC, funcE, funcF } = useReduxDispatch2(
    (d, f) => ({ funcA: (...p) => d(f.funcA(...p)), funcC: (...p) => d(f.funcC(...p)) }),
    (d, f) => ({ funcE: (...p) => d(f.funcE(...p)), funcF: (...p) => d(f.funcF(...p)) }),
);
```

### 🙁 Actual behavior

In the function call on line 55, typescript cannot infer the parameters of array functions `funcA`, `funcB` and `funcC`, actually it thinks the parameters `...args` is `any[]`.

But this bugs doesn't occur in function calls on line 46, 50, 58 and 63.
### 🙂 Expected behavior

No compilation errors.

Typescript should infer the parameters `...args` of array function `funcA`, `funcB` and `funcC` correctly.

**Comment by andrewbranch** [comment] 2021-04-09 22:18
Slightly reduced, cleaned up, and emphasizing the nature of the bug: [playground](https://www.typescriptlang.org/play?ts=4.3.0-beta&ssl=23&ssc=7&pln=23&pc=8#code/PTAEBcE8AcFNQCawGYEsB2ryoPboM6j6oC20ANqmrAqMgE44mgAGAAvTQK4AeAVvmDgcOcgGssLADStOAQwDG4FqDnpaLeUoC0nBLxYBYAFBQ4oACKp80OeAUALADwBBUAF5QAbwgxYALlV0SABuUABtWB5wejkABUZofED8GIwAcwBdQLVIUABfAD4Pb1AnABVQKPBYdUIXQoAKRWw8QPKASnaCkJMTEFAASQtYVPouJS56DNAAMktRmInwKYyTM3hBgDEudAVCTx95BDxyPPCxWEgUtPQswMaAOmfoHOCOj2KANxxUWnzeqY-EMRmNlqs7hUqtFaghCNtdvtiodQMdTudLnkMKBMThkKBypkAPwPZ6PV6gOJyWIkWA1ej4CoXK6ZQofdzfX7-QEbBZgybTSGVaqw+E7Pb4GQAVWhNTqIMW4wFGQqhWRoEaCGstnsDkCVhsdkcTlyhRkyERyQJ7OKUsB-TAFr2rQIJgUeFSdEtAEYSl4TKBA169i4HnJAgAjETkWBqLqgH5-T7efJSANBp0KABCDwjN0F6RkEbzRFu6XjidoHJTaeMQeDCgAwg8FIF0FwSBHYPQZApW6B253u72+5Ho7H0BWucmvKmTAC+kDzOVxftfZ4NniG-hvfbjAMtOBQA4RGJ8CYkApyNT4JmXaAuPhYAAlbg8A06xzeqEi+XDRXggWFSrjuaqagByp3PqEErEBK4+jI5Rsu0e4DDUnpRHIZAxue+5gI4ajpPALAAPoqMIqigBGGBancoA6vS6BBLQWCgARdyjBADjwAocjkOQoAYMg3a1AosBuh6R4kSUj4vm+H5Gg43qNOmgaauaNoav6db1hmiKhhqZLQJpCCNMgjyZi4TwvB0HS1rpel7Dmhk2cmpnmZmWbWeStn2Q5DbNi5PluWZFmIo23nGR0qkFNFxgdICQA)

**Comment by andrewbranch** [comment] 2021-07-26 17:23
Moving to 4.5 since the fix will probably be a breaking change

**Comment by andrewbranch** [comment] 2021-09-02 23:08
Looking at this again, it is very weird, but it is expected behavior. See https://github.com/microsoft/TypeScript/pull/39081 for some discussion. The real problem is that `U` in `Destructuring` has no inference target aside from the return type, so there is simply no inference source aside from the binding pattern when used. As #39081 mentions, you could get around this by [giving `T` in `useReduxDispatch1` a default](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/PTAEBcE8AcFNQCawGYEsB2ryoPboM6j6oC20ANqmrAqMgE44mgAGAAvTQK4AeAVvmDgcOcgGssLADStOAQwDG4FqDnpaLeUoC0nBLxYBYAFAmocUABFU+aHPAKAFgB4AgqAC8oAN4QYsAC5VdEgAblAAbVgecHo5AAVGaHwg-FiMAHMAXSC1SFAAXwA+Tx9QZwAVUGjwWHVCVyKACkVsPCCKgEoOwtCTJAVyOU46LnQlXHRQLnxYAFlYEhxK5uRWnHpIIKbOzxKKmSRkoIAlWDkEPHJIV3o4yGc8koAfafUUDBpu0Aq+4wGhiNkGMJnhprNrLZ7E5KpC7A5HKU4dCXE9mt8KsiEX8TCBQABJSywNL0LhKLj0TKgABkVmJsTJ4ApmRMZn8BIAYiDCF5fPJLuhrpExLAtkR0uhstsAHSy6C5EK7DwlABuOFQtAKOOM5nghPppPJlMllWqMTqCEI+K543wJV5oH5V3yERF+QwoDdOGQPyyAH4ZXKgvFhnISLBavR8JVXaKskUlar1Zrtbq6STGcyTVUaharTaFPgZABVM21eoEokZo2ZFb20BNBA2eFOIJYmFPGTA20dROgYvavHd0EEVnGBR4NKjW0ARlK3hMoCX04Urm2ciCACMRORzuhvmqNXsfAUpIvl8OAELbTepCUZGSb2-i40ZA-J4-eU-npfDgDC2wKEE6BcCQm6wPQMgKEBoAgWBEFQdBW47nu75HsqJ5nsYWomBOBDgCu+AAEzzj+K6WNsCDIaIqFBIetAYV+WHLiuACi2yBC+mQyLAnEkpkaEMSUTFkcOHLbMgwGgeBkF0JJsHSQhcnyduNFqIJn7fthqbshUBb4HOXi6t6hEzn8aZ6dyJFGf4JnDsRg5gFoBGOCIYj4GOw5tFMMywGc+g8O2jgzqauYVvq1ZMq+lT6TO9YRQyNbZrFRTNEgkVZhkbYGpm0WWbOMgVAmPQLsYLGcFFPmzAsSxNDsx5NL4srSuliVRZkTS+UFOxdtyM67AUnQyBEWSdH8BSeSC3ngn53CBc2KJEZUc5hZalY5UlGQxX1RSFSRq1WlWbWZdttpEalTRka1hrtZKM7ZRleWxYVcXMcu125ZkREPcdT1WXtu0mBic60hUJGleVEYUlV8yLDgdV9o1oDNR9m0zp1EILQiPWmUNyOyqjt0ZERGOwN1eP2URA14yNY0mBNpjGHitRTtEYYUMSY6+f5vBBejZGNl2iO+MOa4Ns10B9ggTTINKotNBLnQUyCAHi3KUsy3LKsK+r1NA9qeFTgA+qU3NzXzl1lcugt0MLK5izr0qS8e0uy-LivK+M15q07GtuyCl6O5LevGHTjOGwRIsgq4vVe7HCh-oUpuzDz81Qgi-NW0uNvIHbouBr7Lua1eQdK-H3ul0X-te6XnsJwXzsYa7WvjH+teFJ0+tcyn5tY04JMCwgQsNVHXsN37LcKIHHvx6rldN8X2sex3b3Z0Ptsj+R49V5Pli1-H4k+43JTN2J7eDVhYe4ZOkf20ERui7P9--vHrEH0nXhmwFQUD1nDbr7nTe+cj4T3drrJ+ICd7-nPkNQew8MJI2HOxSBC9q4KFYvvFch954n0XuMDkMDL5-CAA). However, the more I look at this example, the more it seems like the root cause of these poor inferences is that nothing here needs to be generic; return type inference is rarely meaningful, and it’s [apparently not meaningful here](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/PTAEBcE8AcFNQCawGYEsB2ryoPboM6j6oC20ANqmrAqMgE44mgAGAAvTQK4AeAVvmDgcOcgGssLADStOAQwDG4FqDnpaLeUoC0nBLxYBYAFAmocUABFU+aHPAKAFgB4AgqAC8oAN4QYsAC5VdEgAblAAbVgecHo5AAVGaHwg-FiMAHMAXSC1SFAAXwA+Tx9QZwAVUGjwWHVCVyKACkVsPCCKgEoOwtCTJAVyOU46LnQlXHRQLnxYAFlYEhxK5uRWnHpIIKbOzxKKmSRkoIAlWDkEPHJIV3o4yGc8koAfafUUDBpu0Aq+4wGhiNkGMJnhprNrLZ7E5KpC7A5HKU4dCXE9mt8KsiEX8TCBQABJSywNL0LhKLj0TKgABkVmJsTJ4ApmRMZn8BIAYiDCF5fPJLuhrpExLAtkR0uhstsAHSy6C5EK7DwlABuOFQtAKOOM5nghPppPJlMllWqMTqCEI+K543wJV5oH5V3yERF+QwoDdOGQPyyAH4ZXKgvFhnISLBavR8JVXaKskUlar1Zrtbq6STGcyTVUaharTaFHbSk0EDZ4U4gliYU8ZMDbR1EwSiRmjZkVtq8XXQQRWcYFHg0qNbQBGUreEygSdDhSubZyIIAIxE5HO6G+ao1ex8BSkE6nXYAQtsF6kJRkZAuT+LjRl18mt94d3vJ12AMLbBRBdBcEgL2D0GQFE-UBv1-f9AKAxdl1XO9N2Vbdd2MLUTH7AhwGnfAACYx2fadLG2BAoNEGCgg3Wh4MfRCp2nABRbZAmvTIZFgBiSUyWDyJKSjcK7DltmQL8fz-AC6AEkChPA0SxKXYi1A4h8nyQ1N2QqAt8FHLxdW9DDhz+NNVO5bDNP8bSuywjswC0dDHBEMR8F7Ls2imGZYDOfQeCrRxhxLA1MxvStfNbbM1OHBMgn1FsmRvSoQq43DOCi5zZgWJYmh2Lcml8WVpSQSKswyJoXM8nZa25YddgKToZAiLJOj+ApezxWpB2iMMKGJXsXLc3hPO83CS1rRtMunWdQCabLoEbBAmmQaUu1cca5U6Krp3fMaJqmma5pBV9FulSaKs6Ew6t7VDBwAfVKLruA8ssUT64xqIGught8ebA32zbZvmvaDtK8Yj3Wpat2m76QQPX7lsKI7jBO0w+wHdC3pBVx-oUA80dfQortmbrbqhBEHqehBBoy5HxlGyGQa2w9IZWw8Psm6mwYBunMcZr7tvGXaNsO46-iAA).

**Closed** 2022-05-24 16:05 UTC
Labels: Bug, Fix Available
