### ISSUE TITLE
Compiler option to combine and downgrade external modules with outFile

### ISSUE THREAD

**Issue by govis** [Microsoft/TypeScript#17537] opened 2017-07-31 20:00 UTC
As per compiler message: <code>Only 'amd' and 'system' modules are supported alongside --outFile.</code> It appears that it also accepts <code>"module": "none"</code>, with no module contents being compiled into the output file.

I was wondering if we could have have this (or other option) still compile the contents but leave the module semantics out instead?

Given that in a combined .js file modules lose their benefit, would it not make sense to replace resulting <code>System.register(system) define(amd)</code> with plain IIFEs in this case?

**Comment by RyanCavanaugh** [comment] 2017-07-31 23:39
Duplicate of #4434 ?

**Comment by govis** [comment] 2017-08-01 01:35
It looks like #4434 is way too broad and suggests preserving ES6 module semantics - why preserve modules in a combined .js file?
#7671 is closer to what I was thinking - convert modules to simple IIFEs while concatenating. Something similar to <code>rollup's</code> <code>--format iife</code> while leveraging <code>tsc</code> options for choosing which files to include and exclude. Thanks.

**Comment by mhegazy** [comment] 2017-08-23 18:20
> It looks like #4434 is way too broad and suggests preserving ES6 module semantics - why preserve modules in a combined .js file?

cause this is what users expect from a compiler, to have consistent semantics :)

> #7671 is closer to what I was thinking - convert modules to simple IIFEs while concatenating. Something similar to rollup's --format iife while leveraging tsc options for choosing which files to include and exclude.

ES6 is the standard of the web, it has a well defined concept of modules, and we believe this is where most future investments would be. we are not planning on adding a new module format.

We believe this is job better left to other tools like rollup, systemjs, webpack.. etc..

**Comment by mhegazy** [comment] 2017-09-06 19:01
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-06 19:01 UTC
Labels: Duplicate
