### ISSUE TITLE
Promise. TS2454: Variable 'resolve' is used before being assigned.

### ISSUE THREAD

**Issue by vyushin** [microsoft/TypeScript#36968] opened 2020-02-23 21:50 UTC
**TypeScript Version:**  
3.9.0-dev.20200222

**Search Terms:**
 Promise TS2454: Variable 'resolve' is used before being assigned.

**Code**

```ts
// TypeScript
let resolve: (data: string) => void;
const promise = new Promise((res, rej) => { resolve = res })
    .then((data) => console.log(`Resolved with ${data}`));

resolve('some data'); // TS2454: Variable 'resolve' is used before being assigned.
```

second example:
```ts
// TypeScript
let resolve;
const promise = new Promise((res, rej) => { resolve = res })
    .then((data) => console.log(`Resolved with ${data}`));

resolve('some data'); TS2722: Cannot invoke an object which is possibly 'undefined'.
```
In examples above variable `resolve` cannot be non-assigned or undefined when I try show its value in console.

I tried the same example in JS and it works as expect.
```js
// JavaScript
let resolve;
const promise = new Promise((res, rej) => { resolve = res })
    .then((data) => console.log(`Resolved with ${data}`));
resolve('some data'); // Resolved with some data
```

I tried make a delay to make shure that passed function executes synchronously. After short delay the message appears. It's a proof that the function executes synchronously.
```js
// JavaScript
let resolve;
const promise = new Promise((res, rej) => { for(let i = 0; i < 1e+9; i++) {} resolve = res })
    .then((data) => console.log(`Resolved with ${data}`));
resolve('some data'); // Resolved with some data
```

**Expected behavior:**
Passed to Promise function executes synchronously. Variable `resolve` cannot be non-assigned in this example;

**Actual behavior:**
Variable `resolve` is non-assigned.

**Playground Link:** 

**Related Issues:**

**Comment by MartinJohns** [comment] 2020-02-24 06:22
Duplicate of #9998.

**Comment by RyanCavanaugh** [comment] 2020-02-24 18:25
Duplicate #11498.

Aside: leaking the Promise resolver is an incredibly bad idea!

**Comment by vyushin** [comment] 2020-02-24 22:09
@RyanCavanaugh, I agree :) But I think the compiler shuold say that this is bad idea or something like this. Or leaking variables is not support. But it say me that a variable is used before being assigned or that the variable possibly undefined. It is not that.

**Closed** 2020-02-25 02:46 UTC
Labels: Duplicate

**Comment by malthe** [comment] 2024-02-06 21:40
@RyanCavanaugh why is it a bad idea to leak the resolver?

There are lots of examples of using promises to wait for some event, whether it's triggered by a simple callback or using something like `EventEmitter`.

**Comment by aayla-secura** [comment] 2024-08-31 14:43
> Duplicate #11498.
> 
> Aside: leaking the Promise resolver is an incredibly bad idea!

Please, could you elaborate why saving resolver is a bad idea? I don't understand why. The executor function passed to the Promise constructor is guaranteed to run synchronously, so by setting an outside variable to the resolve function from inside the executor, that variable will definitely be defined before the Promise constructor returns.
