### ISSUE TITLE
Allow decorators (and metadata) on non-class functions

### ISSUE THREAD

**Issue by Roaders** [microsoft/TypeScript#36049] opened 2020-01-07 06:49 UTC
## Search Terms
function decorators

## Suggestion
Decorators and the metadata that they produce are great. As far as I can see this is only supported on classes, class properties and class functions.
I would like to be able to decorate anything. Specifically I would like to decorate a function that is not defined in a class so that at runtime I can get metadata about the types of parameters it expects.

## Use Cases
Class metadata can be used by DI systems to inject constructor params. I would like to write code that does the same for a function. Specifically I would like to write a DI system for a React Function component to resolve any parameters (or dependencies) that function has.

## Examples

```
@storeMetadata()
function myReactFuntion(params: IParams, service: SomeService, util: SomeUtil){
    return someReactInstance();
}

function performInjectMagic(func: (...args: any[]) => any){
    return (params: IParams) => {
         const diArgs = evaluateAndInstantiateBasedOnMetaData(func);

         return func(params, ...diArgs);
   }
}

export const performInjectMagic(myReactFunction);
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-01-07 08:54
Duplicate of #7318. And this would first require JavaScript to support function decorators.

**Closed** 2020-01-15 01:44 UTC
Labels: Duplicate
