### ISSUE TITLE
Suggestion: resolve .d.ts at higher priority than .ts

### ISSUE THREAD

**Issue by conartist6** [microsoft/TypeScript#47206] opened 2021-12-20 21:03 UTC
I would like to see resolution of `foo` try to locate and use `foo.d.ts` before it looks for `foo.ts`. OK ok, I suspect such a breaking change will never happen, but I think it's sufficient to call attention to a real problem!

The problem is: When building in-place (i.e. not as `--outDir dist`), typescript prefers the sources to the built results, which may cause errors. The errors arise from the fact that some relevant configuration goes into how to generate `.d.ts` files from `.ts` sources. In my case a my package blows up when used because the `.ts` files contain null errors, something which the `tsconfig.json` explicitly permits. Unfortunately when used as a package these files are evaluated as built artifacts (e.g. according to the **including** `tsconfig.json` not the package's own `tsconfig.json`. Meanwhile the real built code is ignored.

This is especially pernicious because in `package.json` I've specified `"types": "index.d.ts"`, but since that file imports other files e.g. as `export * from "./bar"`, the resolution algorithm decides that that means to import `bar.ts` not `bar.d.ts`, which is just plain old wrong in this circumstance.

**Comment by conartist6** [comment] 2021-12-20 21:05
More than anything I want to understand if this is something Typescript has any interest in resoving (and how), because it is my intention to make this problem much, much more common.

**Comment by MartinJohns** [comment] 2021-12-20 21:24
Duplicate of #15272. You forgot to fill out the issue template.

**Comment by conartist6** [comment] 2021-12-20 21:26
Ok, but that was locked and limited and while the technical issue may be the same I have a heck of a lot more to say about why this matters. Sorry about your template.

**Comment by MartinJohns** [comment] 2021-12-20 21:36
It's not my template. It's the issue template provided by the TypeScript team: [for feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Feature_request.md) and [for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md).

Quoting RyanCavanaugh:

> To expedite the triage process, we need everyone to follow the issue template and instructions.
> When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions completely, follow them, and then fill in all the fields in that template.
> We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

Another times where this issue came up: #11196, #42329, #10704.

This is working as intended. If you don't want this behaviour, place the files in a different directory.

**Comment by conartist6** [comment] 2021-12-20 21:38
I reject the idea that I must never talk to the people who have the ability to make decisions unless what I say fits neatly in a form. This is a very complicated topic.

**Comment by conartist6** [comment] 2021-12-20 21:40
The issue you linked says this:
> the rational, is that sources are more up-to-date than an output

Ok, I get that but that implies that the sources should be equivalent to their built output, which is not true due to reading the wrong `tsconfig.json`. If this is the real problem I'm happy to file an issue with the template filled out fully and to help fix it.

I also think I may be able to offer a means to tell whether built outputs are stale. I'm hundreds of hours into a next-gen project called [macrome](https://github.com/conartist6/macrome) which is focused around this capability. For example I could include a header annotation like `@generatedfrom ./foo.js#71d3be`, while providing the tooling that makes sense of that.

**Comment by conartist6** [comment] 2021-12-21 01:19
I also asked a version of this question in a discord help channel and `@blutorange` there noted that when doing npm installs with git package sources that npm itself respects the contents of the `files` attribute of the package. This solves the problem by excluding the sources except during development.

I'm going to close this for now and wait and see what this looks like when esm resolution lands.

**Comment by conartist6** [comment] 2021-12-21 16:46
Nope I'm reopening it because that fix doesn't work. Unfortunately yarn 1.x does not respect the content of the `files` in `package.json`, and it has tremendous usage including all my projects. Its development is also frozen. Aaaaaaaaaaarrrrrrrgh.

**Comment by fatcerberus** [comment] 2021-12-21 19:42
Duplicate of #10704, #14787, and more recently, #46880 - this is by design and, from what I've seen, very unlikely to be changed.

Note this comment:
https://github.com/microsoft/TypeScript/issues/10704#issuecomment-245336321

> We did in the past give .d.ts higher precedence in importing, and that broke scenarios for npm-link for example, where you really want to import the .ts and not the .d.ts as you are developing multiple npm modules that depend on each other.

See also, this one:
https://github.com/microsoft/TypeScript/issues/46880#issuecomment-975806524

> All the rationale from #10704 still applies here and I'm not sure how this option even helps -- the issue is in downstream consumers of the package, who might not be able to enable this option for whatever reason, so they'd just be completely stuck?

**Comment by conartist6** [comment] 2021-12-21 20:21
OK, here's my pitch.

When you see a sources alongside compiled files, you have basically two correct options. Either you can compile the sources or you use the compiled versions.

If you use the compiled versions you risk their being out of date, something which is insanity-inducing because it is a silent failure.

If you compile the sources yourself nothing can ever be stale, **but** you must know how to compile them correctly.

Compile is a bit a of a vague term, as extracting types from a source in `node_modules` is not emitting any new code, but you still have to extract the types correctly and currently this is not the case. The install blows up because the included project has loose nulls and the including project does not. The compiler understands how to extract correct typedefs from sources with loose nulls and does so in the compiled typedefs, but the including project does not extract correct types.

This describes an issue in using Typescript in what I a way that I find to be generally consistent with best practices. It is a surprising failure. But it does not necessarily make clear which part of the behavior is the cause of the problem. You are saying that typescript very intentionally made the choice to recompile instead of using compiled files on disk.

I'm saying I think it was the wrong choice, because the implementation of type extraction is just so hard. For one you need to do it using the project's own `tsconfig.json`, and typescript doesn't seem to have support for nested projects at all. For a second, you can't assume it's safe to use your own version of typescript in place of the version that the package was compiled with. Their version of typescript won't even be installed because it's just a dev dependency, so now we're back where we started and I think the resolution order is just plain old wrong, even if it was a well-intentioned change.

**Comment by conartist6** [comment] 2021-12-21 20:36
As a note I've been thinking about these kinds of problems a lot because I'm working on a build system, and I've wondered if typescript might be interested in integrating it.

The system is called macrome, and I've designed it to use the filesystem as the source of truth for built artifacts by prepending header comments which might look something like this:
```
/* @macrome
 *  generatedby @typescript/macrome-generator
 *  generatedfrom ./foo.ts#f873be2
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `macrome watch` then change the file this is generated from.
 */
 ```
 
My build system is make-inspired and can parse leading comments in source files (with a configurable set of extensions and parsers) using a streaming regex engine that can read a leading comment of any file (by parsing it with a streaming regex engine) and then either close the handle or provide a handle the the remaining content of the file. It also provides watching and caching when coupled with the [watchman](https://facebook.github.io/watchman/) file watching service, but is also capable of running without it. It views files as a dependency graph, and writes can always trigger other writes. Macrome provides protection against cycles in this graph.

It has some pretty cool characteristics then:
- It can check built artifacts for staleness without having to do an actual build at all.
- It can always detect and remove orphaned build artifacts.

Some of these advantages seem like they could be very relevant to this problem.

**Comment by conartist6** [comment] 2021-12-21 20:48
Ah and one last thought. If the built types are stale, won't the the built code stale too? If someone changes code without building I'd rather the type system alert me to the problem rather than than end up running code that doesn't match its own types.

**Comment by conartist6** [comment] 2021-12-21 21:20
Reading those other duplicate issues I see one counterargument is: it's just wrong to create output side by side with input if you have a choice.

Well, I disagree. I think there are fabulous advantages to maintaining locality. I often think of this as the "component" style of organization, thanks to Ember.

The idea is that when your development process starts to become richer than the feature set of the language, you should colocate related assets to the degree possible. For a web component that might mean having `components/foo/index.js` and `components/foo/index.css`. For typescript it can be having `foo/index.ts` alongside `foo/index.d.ts` and `foo/index.js`.

The point is, everything related to foo is in one place. This is tremendously important in the real world because developers need to be able to learn about code, and they often will not get a complete and correct overview of the environment and architecture before they dive in. They need some place to look to understand what it is that they don't understand about the thing they are working with, so hiding your build artifacts is not much of a help.

I don't think I'm too far out on a limb here, after all this is how `make` traditionally works, and its outputs aren't human readable. It's good sense to keep data that represents the same thing together.

The biggest drawback to mixing files has been that if you specify `--outDir dist/` you can always clean up with `rm -rf dist`. Make is usually able to clean because all generated files have a different extension. This will not be true of javascript source trees. Some `.js` files will be transpiled from `.ts` and some will not be, so obviously `rm **/*.js` is out. But I have a third solution which parses header comments (efficiently) so I think the practical obstacle(s) may soon be removed.

**Comment by conartist6** [comment] 2021-12-21 21:23
Such a "componentized" solution would be extremely powerful in allowing projects to mix `js` and `ts` sources seamlessly during incremental adoption.

**Comment by RyanCavanaugh** [comment] 2022-01-03 19:21
> I reject the idea that I must never talk to the people who have the ability to make decisions unless what I say fits neatly in a form. This is a very complicated topic.

This is about being respectful of our time. You might notice the issue number here implies forty-seven thousand prior issues that also needed human attention.

It seems like you're asking for something akin to what project references already does - can you compare/contrast that with what you need to happen?

**Comment by conartist6** [comment] 2022-01-03 19:30
Everyone who has already reported that this behavior is wrong has been dismissed without serious discussion. I'm sorry if you feel that I am wasting your time.

**Comment by RyanCavanaugh** [comment] 2022-01-03 19:40
There was a serious discussion the first time this was raised (and indeed another prior one when we designed module resolution in the first place). There is not sufficient time available to rehash this debate with every person who shows up and wants to have their own iteration of that discussion.

You're very encouraged to log a suggestion that outlines exactly how you think this should work. The suggestion template describes the kinds of things we would need to consider that proposal.

**Closed by RyanCavanaugh** 2022-01-03 19:40 UTC

**Comment by conartist6** [comment] 2022-01-03 19:42
Excuse me, I have outlined exactly how I think this should work and why. It is actionable.

**Comment by conartist6** [comment] 2022-01-03 19:44
Could you link those original design discussions? I do not know where to find them.

**Comment by RyanCavanaugh** [comment] 2022-01-03 19:49
You basically outlined the entirety of it at https://github.com/microsoft/TypeScript/issues/47206#issuecomment-999069431

Simply preferring .d.ts is not a thought-out change. How would any build apart from the first one work in this world?

**Comment by conartist6** [comment] 2022-01-03 19:59
Stale built files would indeed be picked up and used. Alerting users that this had happened would seem to be critical, but their recourse would either be cleaning built assets or running `tsc watch`.

Are you able to comment on why the sources in a package in `node_modules` are being interpreted in accordance with the including package's `tsconfig.json`? You mention project references, but those are for when you own all the interoperating projects. I'm working to unbreak the workflow of using git repos (including forks) as npm packages, which I believe would have great value to the community.

**Comment by conartist6** [comment] 2022-01-03 20:29
Also you're referring to the problem that building once could cause breakages due to usage of stale code, to which I say this: it will break only when the project is actually in a broken state. I prize this property in tools I use.
