### ISSUE TITLE
Implementing interface drops custom primitive types

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#47695] opened 2022-02-02 06:32 UTC
### 🔎 Search Terms

types, implement interface

### 🕗 Version & Regression Information

**Version:** `4.5.4`

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBA4gTgewK5gJIBMIDtgEsBmuEcUAvFFkgLYBGxA3AFCO47H4CGAxtAGIIIoAb0ZQxUGhzgAKXOgBcsRCgzY8hYgEpFANwRymAX2ZcANhwDOFqPwQBhc1ai4qYUxCprrt4aPGNDIA

### 💻 Code

```ts
type GroupIdentifier = number;

interface Foo {
    bar(id: GroupIdentifier): void;
}

class FooClass implements Foo {
    bar(id: number): void {
        throw new Error("Method not implemented.");
    }
}
```

### 🙁 Actual behavior

Implementing the interface via quick fix puts in `bar(id: number): void`

### 🙂 Expected behavior

I would have expected `bar(id: GroupIdentifier): void`

**Comment by MartinJohns** [comment] 2022-02-02 07:17
Duplicate of #36761. Used search terms: `implement interface alias in:title`

**Closed** 2022-02-04 18:00 UTC
Labels: Duplicate
