### ISSUE TITLE
Can I get "narrowing to never" behavior on a non-union type?

### ISSUE THREAD

**Issue by cakoose** [microsoft/TypeScript#46978] opened 2021-12-01 21:00 UTC
# Bug Report

### 🔎 Search Terms

narrow non-union never
narrow record never

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "narrow" and "never".

(I tested on the Playground with v3.3.3333, v4.0.5, v4.6.0-dev.20211201.)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211201#code/KYDwDg9gTgLgBAMwK4DsDGMCWEV0wW0gGcjMAjAG2AAoB9ANwEMKlgAuOFYe4KASg5ceUOAG8AUHClwYACygQA7p2DKAolAVRqAcgLFSlYAEI41RmjTQAJphQBzGRDhEYjLGhkBPMMCJ8dPgBucQBfcXEAeki4ABVZTCI8JNklOEVgOGtgBDtM3i0khGgXCHxMiAQ4CCQRCF8od2wUIgA6cVBIWG9fOAB5BqacAEYNLTgAXklpAB8xGB92OB0UCBhaYtRrHXDpODnRBd8OFbXaRiQ5aEwAL2BtgBos4DdMCiIOVyg7e1CQqJiAHVMkgiJk5Ik4GB3DBeLgYM5ZIwUNYqHACtA2nAAJJVIhlYA4TKMazWJKMFTKepYHBOAH9QY0lCjTTQJ6xADK6TeFBkwAovNB6UyXHucGRa1kvDgZEa6Fk7WQ6CZiGG1AKHAGvCGzLG0AEcHoEEw1jE0ykmCq6s0rSOmQmDuWq3WmxRgTNez20TgrV95rgoXR70ylrMBVti0mjtO6wuV2+d22fA9nqk3t97T2gf5YJTqbkCmU+ggJHIVGt-BCWbCEW9HIJ1SqNTqjOaSTQtSgwBQMAoXjgSJ4cAAVqD4BTSA40XbG+jWVB2p1oPAZ1rGkyAEx6kRTPYHO0nZ0bGpu8L0+KQ6wQPwoHTwRTQADW4qSGQFcAAtB+4lyrze7+KAppEKCJwKC4JSi4jDlFCMJwoqqAYM0iAbhWmqtjgW7zgaRomnmeBWuGM4OhMTpnK6Sb4V6MQZv62bBlR0jepyc5aBwACCUD2Eg5Q9rOM46KIPRLAAREeFEiUEAY6MknBrC+pD2CgjBGE4sGNOUsJ1FUAlCLwOiZqmMjyGkxalkYFbBHRYRAA)

### 💻 Code

```ts
export function impossible(_value: never): never {
    throw new Error('impossible! (according to static types)');
}

// This is how we define errors for some of our operations.
export type Operation1Error =
    | {type: 'not_found'}
    | {type: 'not_authorized', details: string};

// We use this pattern to handle errors. If someone adds a new option to
// Operation1Error, TS will tell us we need another branch.
function f1(err: Operation1Error): void {
    if (err.type === 'not_found') {
        // ...
    } else if (err.type === 'not_authorized') {
        // ...
    } else {
        throw impossible(err);
    }
}

// Some of our operations currently have just a single type of error.
export type Operation2Error =
    | {type: 'not_found'}

// This doesn't work as well -- TS doesn't allow us to use the same pattern.
function f2(err: Operation2Error): void {
    if (err.type === 'not_found') {
        // ...
    } else {
        // TS error: Argument of type '{ type: "not_found"; }' is not assignable to parameter of type 'never'.
        throw impossible(err);
    }
}
```

### 🙁 Actual behavior

In `f2`, I get a type error on `impossible(err)`.  (See comment in code sample.)

### 🙂 Expected behavior

In `f2`, I was hoping that `err` gets narrowed to `never` and I don't get a type error when using `impossible(err)`.

**Comment by MartinJohns** [comment] 2021-12-01 21:11
Duplicate of #38963.

**Comment by RyanCavanaugh** [comment] 2021-12-01 22:02
If you have something that is currently 1 case but will eventually be more than 1, you can use a workaround
```ts
export type Operation2Error =
    | {type: 'not_found'}
    | {type: never}
```

**Closed** 2021-12-04 18:00 UTC
Labels: Duplicate
