### ISSUE TITLE
Type aliases are not displayed when the type alias is defined using an indexed access type

### ISSUE THREAD

**Issue by jluxenberg** [microsoft/TypeScript#50766] opened 2022-09-13 23:46 UTC
# Suggestion

## 🔍 Search Terms

"lookup type" 
"zod" 
"type alias"

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

It appears that _type aliases_ are not used when the type alias is defined using a _lookup type_.

In projects using libraries like `io-ts` and `zod`, the types generated by `tsc` (and then used in IDE integrations and `.d.ts` definition files) are overly verbose and difficult to read. Errors involving the types can be very difficult to understand; the type aliases you have defined are not used, and the entire type itself is used instead.

## 📃 Motivating Example

Here's a simple illustration of the issue:
```ts
type T2 = {_output: {foo: string}};

type TFooObjectDirect = {foo: string};
type TFooObjectIndirect = T2["_output"];

const v1: TFooObjectDirect = {foo: "bar"};
const v2: TFooObjectIndirect = {foo: "bar"};

v1;  /* tsc types this as "const v1: TFooObjectDirect" */
v2;  /* tsc types this as "const v2: {foo: string;}"
        but it should be "const v2: TFooObjectIndirect" */
```
[🔗  Playground link](https://www.typescriptlang.org/play?jsx=0&ts=4.8.2&ssl=13&ssc=43&pln=13&pc=44#code/PQKgUARANg9jDWBXADgAgC4E9kFMKsgC8YATfSLXVAQygEtqBnCMEYMMSnVAFQCZUAXlQBvAPoxE6ZFIBcogGZx5jdACc6AOwDmAX10BuDl14AxOAHkARgCscAY3QAROmofohi5alUadhzmxuHnMYaztHAElNEld3T34AbQgJKRl0CABdIzB7GE1VVAA3AEZ5EMtbdxc3R08RJRh5CCtqNQgAvIKPIr5y0PD3aNjaj2EG7xa2jpzSg1RUUAxGewwgxgwACzoNplQILsLS-sqI5zjHfDYwXvnFkGXVrg30bd2Ng-yjvq8mn3UtNoDLoWAswWCrFJUHQPIxNpIoCRUFZuJ9usUfhUwlUojELhlUNcgA)

## 💻 Use Cases

This is a problem in e.g. codebases using `io-ts` types because:
```ts
import * as t from 'io-ts';

const x = t.type({ field1: t.string });
export type T1 = t.TypeOf<typeof x>;

function fn(x: T1) {}

fn({field2: 1});
/* ERROR:
  Argument of type '{ field2: number; }' is not assignable to parameter of type '{ field1: string; }'.
  Object literal may only specify known properties, but 'field2' does not exist in type '{ field1: string; }'. 
  Did you mean to write 'field1'? */
```

The error should say `is not assignable to parameter of type T1`, rather than `is not assignable to parameter of type '{ field1: string; }'`

For small types with a limited number of fields, this isn't really an issue; but for a real-world use case, types can be quite large. This can even trigger `TS7056: The inferred type of this node exceeds the maximum length` errors as in https://github.com/colinhacks/zod/issues/1040#issuecomment-1076666682

**Comment by MartinJohns** [comment] 2022-09-14 05:59
I believe this is a duplicate of #31940.

**Closed** 2022-09-19 18:00 UTC
Labels: Duplicate
