### ISSUE TITLE
Array type prompt exception

### ISSUE THREAD

**Issue by crazyair** [microsoft/TypeScript#54978] opened 2023-07-12 01:45 UTC
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5IBQRALpAA4rlUCMoAvKANoDkAhqwDSge2sBdUAB8WrAEbde4-gIDcJJAA8KcfKVhwAdpg3IAtnFoAuUDST0mbTl1aCgA)

### 💻 Code

```ts
type type1 = ['a', 'a1'] | ['b', 'b1'];

export const demo1: type1 = ['a','']  // Here is a prompt for b1
```

### 🙁 Actual behavior

![image](https://github.com/microsoft/TypeScript/assets/7971419/9c0ac81a-2588-4494-8689-5ea3bd827246)

**Comment by whzx5byb** [comment] 2023-07-12 04:46
Duplicate of #46457

**Closed** 2023-07-12 04:54 UTC
