### ISSUE TITLE
Verbose version of QuickInfo for Generics

### ISSUE THREAD

**Issue by jantimon** [microsoft/TypeScript#34944] opened 2019-11-06 10:49 UTC
## Search Terms

QuickInfo
Generics

## Suggestion

Most of the time types which include generics are very hard to understand.

It would be great if there would be a _expand_ feature for QuickInfo (e.g. a `+` button inside the tooltip) which tries to evaluate generics.

If that it not possible it would be great if an CompilerAPI would be available to allow IDE plugin developers to create a type explorer.

![Typescript](https://user-images.githubusercontent.com/4113649/68301868-29d85700-00a1-11ea-822a-3bb07f950562.gif)

## Examples

<details>
<summary>
Relevant part of the example (click to enlarge):

```ts
const example1 /** 1 **/ = flatten({
    firstLetter: 'A',
    secondLetter: { value: 'B' }
})

const example1 /** 2 **/: { firstLetter: { id: string }, secondLetter: { id: string } } = example1;
```

</summary>
Full Example

```ts
type FancyGeneric<TBase> = TBase extends string ? { id: string } : TBase extends { value: string } ? { id: string } : TBase;

type FancyGenericMap<
    TInputStructure extends { [key in keyof TInputStructure]: string | { value: string } }
    > = { [key in keyof TInputStructure]: FancyGeneric<TInputStructure[key]> };



function flatten<TInput extends { [key in keyof TInput]: string | { value: string } }>(input: TInput): FancyGenericMap<TInput> {
    const result: FancyGenericMap<TInput> = {} as FancyGenericMap<TInput>;
    (Object.keys(input) as Array<keyof typeof input>).forEach((key) => {
        const value: string | { value: string } = input[key];
        result[key] = { id: typeof value === 'string' ? value : value.value } as FancyGeneric<TInput[keyof TInput]>;
    });
    return result;
}

const example1 = flatten({
    firstLetter: 'A',
    secondLetter: { value: 'B' }
})

const example2: { firstLetter: { id: string }, secondLetter: { id: string } } = example1;
```

</details>

[Playground](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=24&pc=1#code/C4TwDgpgBAYghgOwMYgOIQRATgSyQHgBUAhOAZwgD4oBeKE86CAD2AwBMyozhcEBzKAH4oAbyg52ALm68cAqAF8oMhhSgs2CTmKgA3OABsArhBk8+g5SPGTzchctWkKAbgCwAKC+hIsRCjomLhIALJwYPheUDH0AJIIYMbAAMq8xkjAxlhMrBxc4gDaANYQIBIIUKUgAPYAZvGJyWlYGVk5ALr2llAAProGJmayPcqK0bHUdEXVFVVl9Y1JqemZ2RBd-shoGNh4RAnLLW3rJWUd1Ioe3jdedcbIwDg1lXWGcMBaB03AGnnaBSgZ3K8nmtQahEOyU2Fnkgn64kGpm6cKUSkoAAp5MtVFDgABKGTwbZBPZhCLfZbUUQTGJIF48KA5MjGQzAIkBHbBPDhSKQn5TMTKchbQK7EK8ynJSjXWJQDEAeQARgArCCZAB01TIWJ++KgIoAglgsHAQPhqotfBBFtjpfiNXUalgAKJwJAACwxGOq+po1Npcqg9IQjKRw1hCgR+iMyJGqOUdDtwGBHVlQZizNZKeqHVoujsUGti3DtBodAA5JH+BXhDGhip66YNaXhVxiWLuQR+ctgYse9CZYHFPj05mIO1Klm2ddxjcQ4yWHAALZgQwQACM+beHy0GJpnjldRwWB4ABkJ2wsDIK4aKwAaQMUEPsC+fbAyRGx4YV4i1ucjl4XgLr8S6ruuABMn5QMep7AG+V7QYW1ZKPe3Dqi8r6Xh+BbSPGjhonQYFrpu1xAA)

As you can see the **types are the same** for `/** 1 **/` and `/** 2 **/` but lets compare the QuickInfo:

The first QuickInfo for `/** 1 **/`

```ts
const example1: FancyGenericMap<{
    firstLetter: string;
    secondLetter: {
        value: string;
    };
}>
```

In this case you can not tell the structure of the object without reading the `FancyGenericMap` implementation.

Lets see in contrast the second QuickInfo for `/** 2 **/`:

```ts
const example2: {
    firstLetter: {
        id: string;
    };
    secondLetter: {
        id: string;
    };
}
```

For the second example it is way easier to understand the structure.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jcalz** [comment] 2019-11-06 14:00
Duplicate of #25784 and #28508

**Closed** 2019-11-09 18:00 UTC
Labels: Duplicate
