### ISSUE TITLE
ReturnType of function with generic type is unknown

### ISSUE THREAD

**Issue by GoodbyeNJN** [microsoft/TypeScript#38964] opened 2020-06-06 17:32 UTC
**TypeScript Version:**  3.9.5

**Search Terms:** return type of function with generic type unknown

**Code**

```ts
type Func = <T = string>() => T;

type R = ReturnType<Func>;
```

**Expected behavior:** `type R = string`

**Actual behavior:** `type R = unknown`

**Playground Link:** https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAYgrgOwMZQLxQDwBU1QM7ABOAlggOYB8AFAJRoVRYBQTokUASrhxMHIQizgIGeMgpMgA
P.S. the typescript version of playground is 3.9.1, but this bug still exists in 3.9.5.

**Related Issues:** #26856

**Comment by Harpush** [comment] 2020-06-07 04:17
I am pretty sure duplicate of #37181

**Comment by GoodbyeNJN** [comment] 2020-06-07 07:04
> I am pretty sure duplicate of #37181

Thanks, seems this issue does be duplicated.

**Closed** 2020-06-07 07:04 UTC
