### ISSUE TITLE
Compiler fails to infer that a Date variable is not null even though it's obvious

### ISSUE THREAD

**Issue by devuxer** [microsoft/TypeScript#41266] opened 2020-10-27 07:32 UTC
**TypeScript Version:**  4.03

**Search Terms:** Date, truthy, inference

**Code**

```ts
const date = getDate();

function getDate() {
    return Date.now() > 1000 ? new Date() : null;
}

const y = !date || date.valueOf() > 1000;

if (y) {
    console.log("y is truthy");
} else {
    console.log(getMonth(date));
}

function getMonth(value: Date) {
    return value.getMonth();
}
```

**Expected behavior:**

No error trying to pass `date` to `getMonth`, since it has been proved to be a non-null date due to variable `y` being false.

**Actual behavior:**

The following error is displayed for `date`:

> Argument of type 'Date | null' is not assignable to parameter of type 'Date'. Type 'null' is not assignable to type 'Date'.

Note that if you do `if (!date || date.valueOf() > 1000` instead of `if (y)`, the error disappears, so that one small bit of indirection seems to throw off the compiler.

**Playground Link:** https://www.typescriptlang.org/play?#code/MYewdgzgLgBAJgQygUxgXhgc2VAIk5ACgEoBuAKHIDMBXMYKAS3Cx3xRJgG9yY+YATjhoCwMdsgB0YEAHdOAPhgBGAAzqYAfhhhks8QU4AuHTQA2ZigF9KoSLACe6GAEJEKGAB9P8ApIBuCGY0yADyVIoq6qoU5IxUMIQOxNy8-HYQIGZSZiCYhABETowQMFACNFAAFg4FZORWMMhmEKg8-DAZWTl5hNhQALLg1YTuyMT1NtR0DMxi-UNgI4HByCYSKe38QlAiYishkgvDVSTWQA

**Related Issues:** (not able to find any -- not sure what other key words to search for)

**Comment by MartinJohns** [comment] 2020-10-27 07:40
Duplicate of #12184.

**Closed** 2020-10-27 18:01 UTC
Labels: Duplicate
