### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by Jessidhia** [microsoft/TypeScript#38383] opened 2020-05-07 03:22 UTC
**TypeScript Version:**  3.9.1-rc

**Search Terms:** typeerror kind

**Code**

Unknown

**Expected behavior:**

Compilation

**Actual behavior:**

```
TypeError: Cannot read property 'kind' of undefined
    at getErrorSpanForNode (.../node_modules/typescript/lib/typescript.js:13845:22)
    at createDiagnosticForNodeInSourceFile (.../node_modules/typescript/lib/typescript.js:13794:20)
    at Object.createDiagnosticForNode (.../node_modules/typescript/lib/typescript.js:13785:16)
    at .../node_modules/typescript/lib/typescript.js:41784:135
    at Map.forEach (<anonymous>)
    at getInitializerTypeFromAssignmentDeclaration (.../node_modules/typescript/lib/typescript.js:41766:52)
    at getWidenedTypeForAssignmentDeclaration (.../node_modules/typescript/lib/typescript.js:41660:123)
    at getTypeOfFuncClassEnumModuleWorker (.../node_modules/typescript/lib/typescript.js:42220:34)
    at getTypeOfFuncClassEnumModule (.../node_modules/typescript/lib/typescript.js:42199:51)
    at getTypeOfSymbol (.../node_modules/typescript/lib/typescript.js:42312:24)
```

**Playground Link:**

Unknown

**Related Issues:**

Unknown

**Comment by Jessidhia** [comment] 2020-05-07 03:23
Adding a `console.log` to `createDiagnosticForNode` with all its arguments prints the following:

```
undefined {
  code: 6203,
  category: 3,
  key: '_0_was_also_declared_here_6203',
  message: "'{0}' was also declared here.",
  reportsUnnecessary: undefined,
  elidedInCompatabilityPyramid: undefined
} undefined globals undefined undefined undefined
```

**Comment by Jessidhia** [comment] 2020-05-07 07:44
It looks like the line that is causing the crash itself is:

```js
// @ts-check
// this is a javascript file

const config = makeConfig(/* ... */)

config.globals.__STORYBOOK__ = false // this line
// commenting it out prevents the crash

module.exports = config
```

where the return type of `makeConfig` is `import('@jest/types').Config.InitialOptions`.

**Comment by Multiply** [comment] 2020-05-13 21:49
We're seeing a similar issue, however, I can't seem to find the cause in our code.

@Jessidhia did you add more console.log's in other parts to find the file/line?

**Comment by lukaskl** [comment] 2020-05-13 22:20
I've noticed quite similar (also, looking from stack trace - seemingly different one) issue. I thought that I will better file it as a dedicated issue - #38558. If it will turn out, that it is a duplicate, we can simply close the issue (also it contains reproducible repository).

**Comment by elibarzilay** [comment] 2020-05-18 19:21
@Jessidhia, can you post a precise repro?  I tried a few things with the above snippet but can't get it to happen.

**Comment by pferdone** [comment] 2020-05-19 17:38
@elibarzilay this happened to me today as I was setting up a new nextjs project. Basically if your checkout this [example](https://github.com/zeit/next.js/tree/canary/examples/custom-server-typescript) or `yarn create next-app --example custom-server-typescript custom-server-typescript-app` and run `yarn dev` you get this error:
```
    TypeError: Cannot read property 'kind' of undefined
        at getErrorSpanForNode (../node_modules/typescript/lib/typescript.js:13856:22)
        at createDiagnosticForNodeInSourceFile (../node_modules/typescript/lib/typescript.js:13805:20)
        at Object.createDiagnosticForNode (../node_modules/typescript/lib/typescript.js:13796:16)
        at ../node_modules/typescript/lib/typescript.js:41824:135
        at Map.forEach (<anonymous>)
        at getInitializerTypeFromAssignmentDeclaration (../node_modules/typescript/lib/typescript.js:41806:52)
        at getWidenedTypeForAssignmentDeclaration (../node_modules/typescript/lib/typescript.js:41700:123)
        at getTypeOfFuncClassEnumModuleWorker (../node_modules/typescript/lib/typescript.js:42260:34)
        at getTypeOfFuncClassEnumModule (../node_modules/typescript/lib/typescript.js:42239:51)
        at getTypeOfSymbol (../node_modules/typescript/lib/typescript.js:42352:24)
        at checkPropertyAccessExpressionOrQualifiedName (../node_modules/typescript/lib/typescript.js:57154:53)
        at checkPropertyAccessExpression (../node_modules/typescript/lib/typescript.js:57013:17)
        at checkExpressionWorker (../node_modules/typescript/lib/typescript.js:61646:28)
        at checkExpression (../node_modules/typescript/lib/typescript.js:61567:38)
        at maybeCheckExpression (../node_modules/typescript/lib/typescript.js:60780:34)
        at checkBinaryExpression (../node_modules/typescript/lib/typescript.js:60737:25)
```
If you pin Typescript to 3.8.3 the error goes away. Cheers

**Comment by elibarzilay** [comment] 2020-05-19 18:36
I'm not sure if I'm doing it right, but I tried the following two chunks in an empty directory:

```
$ git clone https://github.com/zeit/next.js
$ cd next.js/examples/custom-server-typescript
$ npm i
$ tsc
```

and

```
$ yarn create next-app --example custom-server-typescript custom-server-typescript-app
$ cd custom-server-typescript-app
$ yarn dev
```

Both ran without any errors...

**Comment by Multiply** [comment] 2020-05-19 19:03
@elibarzilay try to change the typescript version to the latest in package.json before installing.

**Comment by pferdone** [comment] 2020-05-20 14:14
@elibarzilay @Multiply yeah, it installs Typescript 3.9.3 when I setup the project I get the error described above and as I said when I switch to 3.8.3 the error goes away.

**Comment by elibarzilay** [comment] 2020-05-20 20:14
I'm using a `tsc` which is wired to a build from the current master, but just in case, I repeated both of the above after editing `package.json` and removed the TS line, and repeated with editing it to `3.9.3`.

Still no errors...

**Comment by elibarzilay** [comment] 2020-05-21 00:51
To make this more controllable, I used docker.  This is my build file (which doesn't get any errors):

```
FROM ubuntu

RUN apt update \
 && apt upgrade -y \
 && apt install -y curl

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - \
 && apt install -y nodejs

RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
 && echo "deb https://dl.yarnpkg.com/debian/ stable main" >> /etc/apt/sources.list \
 && apt update && apt install -y yarn

RUN mkdir /work
WORKDIR /work

RUN yarn create next-app --example custom-server-typescript t \
 && cd t \
 && sed -i -e 's/\("typescript": "^\)\(.*\)"/\13.9.3"/' package.json
```

**Comment by YaoChing** [comment] 2020-05-21 02:50
When I switch to Nextjs version 9.4.2, Typescript version 3.9.3,  I could no longer see the error

**Comment by Multiply** [comment] 2020-05-21 05:48
> When I switch to Nextjs version 9.4.2, Typescript version 3.9.3, I could no longer see the error

Can confirm 9.4.2 of nextjs fixed it for us as well.

**Comment by elibarzilay** [comment] 2020-05-21 16:22
I changed the docker setup to change the nextjs version to 9.4.1 and to 9.4.0, and still no error...

**Comment by SeyedAlirezaFatemi** [comment] 2020-05-24 11:10
I have the problem with typescript 3.9.3 and next 9.4.2. Switching to typescript 3.8.3 fixes the problem.

**Comment by Hyokune** [comment] 2020-05-25 04:58
I seem to have the same issue with next 9.4.2, typescript 3.9.3 and ts-node 8.10.1.

**Comment by anthanh** [comment] 2020-05-29 15:39
Could be related to bad intersection types documented here https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#intersections-reduced-by-discriminant-properties

**Comment by RyanCavanaugh** [comment] 2020-06-02 19:56
@Hyokune @SeyedAlirezaFatemi @anthanh can you please provide concrete repro steps (ideally involving just a handful of TS/JS files and a config file)? We've tried a bunch of different configurations with the linked repo and haven't been able to cause the exception to occur.

**Comment by SeyedAlirezaFatemi** [comment] 2020-06-03 05:10
> @Hyokune @SeyedAlirezaFatemi @anthanh can you please provide concrete repro steps (ideally involving just a handful of TS/JS files and a config file)? We've tried a bunch of different configurations with the linked repo and haven't been able to cause the exception to occur.

I reproduced the error in this repo:
https://github.com/SeyedAlirezaFatemi/ts-error
Started from https://github.com/vercel/next.js/tree/canary/examples/custom-server-typescript.
build and start and you will see the error.

**Comment by elibarzilay** [comment] 2020-06-03 06:54
(@RyanCavanaugh, FWIW, I tried this one too, and still no failures.)

**Comment by ali4heydari** [comment] 2020-06-03 07:35
@elibarzilay I opened @SeyedAlirezaFatemi  [repo](https://github.com/SeyedAlirezaFatemi/ts-error) in [Gitpod](https://gitpod.io/#https://github.com/SeyedAlirezaFatemi/ts-error) and ran these commands:

```bash
yarn && yarn build && yarn start
```
After opening http://localhost:3000 with preview button in  Open Ports tab I get the error.

**Comment by elibarzilay** [comment] 2020-06-03 17:58
Ah, I never tried `yarn start` before -- I now see the crash, finally...

**Comment by elibarzilay** [comment] 2020-06-03 23:46
So, after digging through that pile of s...tuff, here's an actual minimal repro:

* `x.js`:
  ```
  module.exports.x = 1;
  module.exports = require("./y.js");
  ``
* `y.d.ts`:
  ```
  export declare type x = 1;
  ```

**Closed** 2020-06-04 23:28 UTC
Labels: Bug

**Comment by Multiply** [comment] 2020-06-18 06:38
Bit late with the response, sorry.
After applying your patch locally the issue went away for us. (eagerly waiting for it to be included in a release)

**Comment by CherIgor** [comment] 2020-06-19 10:18
Had the fix been released? I still have the same issue with latest: next 9.4.4, typescript 3.9.5 and ts-node 8.10.2. node -v 12.4.0.

**Comment by imachug** [comment] 2020-07-20 20:57
This is still a problem with TypeScript 3.9.7. @elibarzilay's repro fails without any modifications. Unfortunately downgrading 3.8.3 is not an option for me because old versions ironically have another bug. Will we get this problem fixed?

**Comment by sourabh8003** [comment] 2020-07-26 12:54
@elibarzilay Hi, Even after downgrading the Typescript version the issue still persists, downgrading the Typescript version doesn't solve my issue too. Is anyone working on this issue for a fix?

**Comment by henhen724** [comment] 2020-07-27 20:26
Having the same issue with nextJS version 9.4.4 with Typescript version 3.9.7.

**Comment by elibarzilay** [comment] 2020-07-29 19:31
@sourabh8003 IIRC, it was only included in 4.0.

**Comment by henhen724** [comment] 2020-07-29 20:35
Sorry, I should have read more carefully.  It's working on 4.0.0-dev.20200729. Thank you.

**Comment by StationedInTheField** [comment] 2020-09-23 17:16
I just had the issue with Angular 10.1.1 and Typescript 3.9.7

**Comment by SurjitSahoo** [comment] 2021-05-30 05:01
I am still having this issue on node 14.17.0, typescript 4.2.4, ts-node 9.0.0
```
TypeDoc exiting with unexpected error:
TypeError: Cannot read property 'kind' of undefined
    at Object.isDeclaration (/home/surjit/practice/ds_algo/DataStructures-Algorithms/node_modules/typescript/lib/typescript.js:13449:18)
    at Object.isDeclarationName (/home/surjit/practice/ds_algo/DataStructures-Algorithms/node_modules/typescript/lib/typescript.js:16414:75)
    at getTypeOfSymbolAtLocation (/home/surjit/practice/ds_algo/DataStructures-Algorithms/node_modules/typescript/lib/typescript.js:66938:20)
    at Object.getTypeOfSymbolAtLocation (/home/surjit/practice/ds_algo/DataStructures-Algorithms/node_modules/typescript/lib/typescript.js:45176:35)
    at Object.convertProperty (/home/surjit/practice/ds_algo/DataStructures-Algorithms/node_modules/typedoc/dist/lib/converter/symbols.js:330:176)
    at convertSymbol (/home/surjit/practice/ds_algo/DataStructures-Algorithms/node_modules/typedoc/dist/lib/converter/symbols.js:80:79)
    at convertSymbols (/home/surjit/practice/ds_algo/DataStructures-Algorithms/node_modules/typedoc/dist/lib/converter/symbols.js:86:9)
    at Object.convertClassOrInterface (/home/surjit/practice/ds_algo/DataStructures-Algorithms/node_modules/typedoc/dist/lib/converter/symbols.js:264:5)
    at Object.convertSymbol (/home/surjit/practice/ds_algo/DataStructures-Algorithms/node_modules/typedoc/dist/lib/converter/symbols.js:80:79)
    at Converter.convertExports (/home/surjit/practice/ds_algo/DataStructures-Algorithms/node_modules/typedoc/dist/lib/converter/converter.js:182:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 5
npm ERR! data_structures_and_algorithms@1.0.0 docs: `typedoc --options tsdoc.json --plugin typedoc-plugin-extras --favicon docs/favicon.png`
npm ERR! Exit status 5
npm ERR! 
npm ERR! Failed at the data_structures_and_algorithms@1.0.0 docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by hadnet** [comment] 2021-05-31 19:23
Same thing here, @SurjitSahoo . Previously it was working fine, but now throws that error.

**Comment by Nokel81** [comment] 2021-06-02 18:59
I see this running `typedoc` on `typescript 4.3.2` too
