### ISSUE TITLE
No completion for `asserts` in return type annotations

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#35837] opened 2019-12-24 01:02 UTC
```ts
function assertThing(x: unknown): /**/
```

**Expected**: Completion at `/**/` contains `asserts`
**Actual**: No completion for `asserts`

**Comment by AlCalzone** [comment] 2019-12-26 09:09
Duplicate of https://github.com/microsoft/TypeScript/issues/35187 ?

**Closed** 2019-12-26 17:12 UTC
Labels: Duplicate
