### ISSUE TITLE
File/folder specific skipLibCheck

### ISSUE THREAD

**Issue by boombang** [microsoft/TypeScript#48768] opened 2022-04-19 16:49 UTC
# Suggestion

## 🔍 Search Terms

skipLibCheck, specific skipLibCheck

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add an ability to apply `skipLibCheck` for specific files and folders.

## 📃 Motivating Example

For now, enabling `skipLibCheck` will skip errors in `d.ts` files in all places (codebase/node_nodules). But that's sometimes not needed for actual codebase. Or maybe there is some exotic case when a developer doesn't want to skip some specific lib from node_modules.

## 💻 Use Cases

In my case I don't want to skip `d.ts` files in my codebase. Ideally even skip some specific libs from `node_modules` with broken/not compatible with tsconfig types.
BTW great examples of how `skipLibCheck` works are located in https://github.com/omril321/skip-lib-check-examples

**Comment by MartinJohns** [comment] 2022-04-19 18:11
Related: #30511, #31035.

**Comment by RyanCavanaugh** [comment] 2022-04-19 23:28
This seems like effective a duplicate of #30511 - by far the most common thing we hear is that people want to check "their" files (for some definition of "theirs") but exclude "other" files (for some definition of "other"). I think the problem is simply defining a coherent way to distinguish theirs/others.

**Closed** 2022-04-22 18:00 UTC
Labels: Duplicate
