### ISSUE TITLE
Distribution of union into properties stop working on a big enough union type

### ISSUE THREAD

**Issue by zen0wu** [microsoft/TypeScript#43757] opened 2021-04-21 05:46 UTC
# Bug Report

### 🔎 Search Terms

union type, large union, smart union type checking

### 🕗 Version & Regression Information

- This is a type error
- This did not change between versions 3.3.3 and 4.2.3, happens to all of them.
- I was unable to test this on prior versions because playground does not provide them.

### ⏯ Playground Link

[playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgdgSwPZygXigKCjqAfKAcgEMBGQ7XAkgJgt3yOIGZ6qmAWNna4gVm6MSANkG8A7GKYAOKSQCccsgAYlpcpR5NSdTULKs9vUlyPaBZkqVGWyk26VkPFtmqtcaGvGrq9Mahn60pkHENBahNDaR9pGyUAD0CVAAShAAtkgAbghwAOZQwAAWCADOUFnEAE4IxHDAUOnEANYQ5QgNoJAAxkUQ3c0A-ACEmJhd0ADKRcSQADwAKlAQAB7AEHAAJuXwyHAAfOhQS6vrWzuIKFCDUADeUK0gAFzHUAC+UC9wEFkQVWOrMBIKoNABmAFc4N1gHtCm1gAAKR4vXYoACUL2mswgc1RBzumAAkAhQVAkRAQOg0BgAERkGlogmEwlVCDAcFVVD3R7vIkfCAAG1K0BJZJ51IwtEIjNuRJZbI5XIeFN5hP5QugsoYDFZ7M5d2VlLeemNxqAA)

### 💻 Code

```ts
type Union = 
    | 'a1'
    | 'a2'
    | 'a3'
    | 'a4'
    // omitted, see playground. If this goes over 28, the test function reports type error.

type Shape<T extends Union> = T extends Union ? { key: T } : never

export function test(key: Union): Shape<Union> {
  if (key === "a1") {
    return { key }
  } else if (key === 'a2') {
    return { key }
  } else {
    return { key }
  }
}
```

### 🙁 Actual behavior

It does not typecheck when the union has more than 28 variants, while it's ok if it's less than 28.

### 🙂 Expected behavior

The behavior should at least be consistent despite of how many variants are there in the union.

**Comment by MartinJohns** [comment] 2021-04-21 05:47
Duplicate of #40803 and many others.

**Comment by zen0wu** [comment] 2021-04-21 05:50
@MartinJohns Sorry that wasn't clear, I tested all the versions between 3.3.3 and 4.2.3 that playground provides..

**Closed** 2021-04-23 18:00 UTC
Labels: Duplicate
