### ISSUE TITLE
Add a "throws" decorator to methods

### ISSUE THREAD

**Issue by agonzalezjr** [Microsoft/TypeScript#14599] opened 2017-03-11 23:06 UTC
Could a `throws` decorator be added to methods that could throw an error or raise an exception?

That way methods that call them could be checked to make sure they are either handling it or throwing themselves as well.

Example:

```ts
public doSomethingThatCouldGoWrong(x: int) throws {
  return 1 / x;
}
```

**Comment by DanielRosenwasser** [comment] 2017-03-12 06:23
Closing as a duplicate of #13219.

**Closed by DanielRosenwasser** 2017-03-12 06:23 UTC

**Comment by agonzalezjr** [comment] 2017-03-13 18:11
Thanks! Didn't find it.
