### ISSUE TITLE
🔎📘 Add "Search documentation" based on keywords to the website

### ISSUE THREAD

**Issue by dwiyatci** [microsoft/TypeScript#19555] opened 2017-10-28 22:37 UTC
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code:** -

**Expected behavior:** "Search documentation" input bar should be added for making easy to search relevant sections of the documentation based on keywords, like in, e.g. https://webpack.js.org, https://angular.io, https://reactjs.org.

**Actual behavior:** "Search documentation" does not exist yet.

**Comment by orta** [comment] 2019-07-10 18:59
Closing as a dupe of https://github.com/microsoft/TypeScript/issues/26956 (though this does have better emoji usage...)

**Closed by orta** 2019-07-10 18:59 UTC
Labels: Website
