### ISSUE TITLE
Condition does not differentiate between generic types with help of string literals

### ISSUE THREAD

**Issue by bre1470** [microsoft/TypeScript#33140] opened 2019-08-29 15:56 UTC
**TypeScript Version:**  3.7.0-dev.20190829

**Search Terms:** condition extends generic interface

**Code**

```ts
interface A {
    type: 'a';
    data: Array<number>;
}
interface B {
    type: 'b';
    data: Record<string, string>;
}
class C {
    type: 'c' = 'c';
    data: Array<string> = [];
}
function f<T extends (A|B|C)> (container: T): T['data'] {
    if (container.type === 'a') {
        // container.data is still (Array<number>|Record<string,string>|Array<string>)
        return container.data.map(value => ++value);
    }
    return container.data;
}
function s (container: (A|B|C)): (A|B|C)['data'] {
    if (container.type === 'a') {
        // works
        return container.data.map(value => ++value);
    }
    return container.data;
}
```

**Expected behavior:**
T is internally replaced with extends-types so that it works like you would define argument of type `(A|B|C)`.

**Actual behavior:**
TypeScript fails to differentiate between the interfaces and classes with the help of a string literal property.

**Playground Link:**  https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgILIN4Chm+WATwAcIAuZAcjgoG4c8ATOMOc1KKOAgHhAFcAtgCNoAPjoBfLKEixEKAEKZ6uQiXIUhtFciYtyAJQgIA9lAbcAzmCigA5gBpk12yDvisUhABs4ly8gAwsp4+MRklAgUyAC8kdqheqxoHFxWNvaiscgA2gC6klgwfCAIYMAmIMgw3AAqyBAAHpAgDAEAFKgAPgpdgQCUWe2m4HCg0OS1-ZM5FEkUeSF4wDDIw5Us41AAdGooMQeU1P1LobgA9OfII5sg0NtJyMAB1sDe3mvsnDz8wmJdRlM5nSrkcLkyXS+aXBblE-R0oSgEDAfCgVRuYzuOyS2wEcCI7QAbnBvHx9lkANQU4mkiD9OihKSI5Go9EbTH3JKFYqlcqVZBQNYYrbkTo9Pr9aafcUDWbzRbYUIrIXsra7cKxQ5UCgnRVnXBIlFo66qrEPZhwXH4okksmxSnU210mjIS7IADuZgA1pYdEy8IbWSbRmquZ4sEA

**Related Issues:** Found nothing similar

**Comment by fatcerberus** [comment] 2019-08-29 16:11
Duplicate of https://github.com/microsoft/TypeScript/issues/13995

**Closed** 2019-09-03 18:18 UTC
Labels: Duplicate
