### ISSUE TITLE
Incorrect inference of lookup type members

### ISSUE THREAD

**Issue by magnushiie** [Microsoft/TypeScript#20100] opened 2017-11-17 13:44 UTC
**TypeScript Version:**  2.7.0-dev.20171117

**Code**

Example 1:
```ts
interface Animal {
}
interface Cat extends Animal {
    readonly purr: () => void;
}
interface Dog extends Animal {
    readonly bark: () => void;
}
const cat: Cat = {
    purr: () => {
        // purr
    }
};
const dog: Dog = {
    bark: () => {
        // bark
    }
};
type DictionaryBase = { [name: string]: Animal };
const getFromDictionary = <D extends DictionaryBase, P extends keyof D>(d: D, p: P): D[P] => {
    return dog; // should error, cannot assign to D[P]
};
const dict = {
    cat,
};

const cat2 = getFromDictionary(dict, 'cat');
cat2.purr(); // runtime error: TypeError: cat.purr is not a function

type DogDictionary = { [name: string]: Dog };
// const dogs: DogDictionary = dict; // compile error: Type '{ cat: Cat; }' is not assignable to type 'DogDictionary'
```

Example 2:
```ts
interface Field<T> {
    readonly witness: T;
    readonly parse: (s: string) => T;
}
const stringField: Field<string> = {
    witness: '',
    parse: s => s,
};
const booleanField: Field<boolean> = {
    witness: false,
    parse: s => s === 'true',
};
type DefinitionBase = { [name: string]: Field<{}> };
const parseField = <D extends DefinitionBase, P extends keyof D>(d: D, p: P, s: string): D[P]['witness'] => {
    // return {}; // if this line is uncommented, no compile error but the runtime error below results
    const value = d[p].parse(s); // parse is inferred to be Field<{}>.parse, value inferred to be {}, not D[P]['witness']
    return value;
};
const d = {
    s: stringField,
    b: booleanField,
};
console.log(parseField(d, 's', 'a'));
console.log(parseField(d, 'b', 'a'));
console.log(parseField(d, 's', 'a').length.toString()); // runtime error: TypeError: Cannot read property 'toString' of undefined
// console.log(parseField(d, 'b', 'a').length); // correct compile error: Property 'length' does not exist on type 'boolean'.
```

**Expected behavior:**
In Example 1, `getFromDictionary` should not be able to return a `dog`, a compile time error should occur.

In Example 2:
- `parseField` should not be able to return a `{}`, a compile time error should occur
- `value` in `parseField` should be inferred to be `D[P]['witness']`

**Actual behavior:**
In Example 1, `getFromDictionary` is allowed to return a dog which results in runtime error.

In Example 2:
- `parseField` can return a `{}` results which results in runtime error
- `value` in `parseField` is inferred to be `{}`

**Comment by mhegazy** [comment] 2018-07-18 21:36
Duplicate of https://github.com/Microsoft/TypeScript/issues/19412

**Closed** 2018-07-31 17:11 UTC
Labels: Duplicate
