### ISSUE TITLE
Optional name mangling of private members

### ISSUE THREAD

**Issue by dawidgarus** [Microsoft/TypeScript#25089] opened 2018-06-20 11:10 UTC
## Search Terms

mangle private members

## Suggestion

Introduce optional name mangling of private members of class, similarly how python does name mangling of private members (members which name starts with __).
In order not to make a breaking change I suggest using new keyword (lets say `mangle`) to mark property for mangling, example:
```typescript
class MyClass {
  mangle private myProp: any;
}
```

## Use Cases

First of all - this proposal purpose is not to make private variables inaccessible outside the class.
Primary purpose is to avoid naming collisions in derived class:
```typescript
class MyClass {
  private myProp: any;
}
class DerivedClass extends MyClass {
  private myProp: any; // can't do this
}
```
Currently, we need to expose internals of class definition (private members) to avoid collisions.
Also, it could be possible to configure minifiers like uglifyjs to mangle the names again and produce smaller outputs.

## Examples
With mangling enabled, this code:
```typescript
class MyClass {
    mangle private myProp: any;
    constructor() {
        this.myProp = 1
    }
}
```
should be compiled to something like:
```javascript
var MyClass = /** @class */ (function () {
    function MyClass() {
        this.myProp$MyClass= 1;
    }
    return MyClass;
}());
```
How the names should be mangled is up to debate. It could incorporate class name or some kind of hash in mangled names.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by j-oliveras** [comment] 2018-06-20 12:46
Duplicate or related to #8.

**Comment by dawidgarus** [comment] 2018-06-20 14:02
@j-oliveras it's not releated. The mangling I proposed has nothing to do with minification. In fact, generated code will be probably bigger. It's to avoid name conflicts and as a bonus, it can make external tools that minifies code more efficient.

**Comment by andy-ms** [comment] 2018-06-20 16:14
You may be interested in https://github.com/tc39/proposal-class-fields .

**Comment by mhegazy** [comment] 2018-06-20 22:43
This looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/9950. The private property proposal will be implemented as weak map, removing the chance that a derived classes can step on a base class private property.

**Comment by dawidgarus** [comment] 2018-06-21 08:33
@mhegazy It's a different approach. WeakMap requires polyfill when targeting ES5 and I don't think it's a good idea and there are obvious performance concerns (https://jsperf.com/weakmap-vs-property/1 - even with native WeakMap imprementation, on firefox it's more than 200 times slower). Also, this proposal is more general, as tc39 proposal doesn't mention private functions.

**Comment by mheiber** [comment] 2018-06-21 14:40
@dawidgarus I tested on IE, Firefox and Chrome and found the WeakMap implementation to be 2X slower, not 200X slower.

**Comment by dawidgarus** [comment] 2018-06-21 15:12
I my test (https://jsperf.com/weakmap-vs-property/1) in all the browsers except Chrome weakmaps are slower by 2 or 3 orders of magnitude:

browser | property ops/sec | weakmap ops/s
--- | --- | ---
Chrome 67.0.3396 / Windows 8.1 0.0.0 | 10,652,072 | 520,222
IE 11.0.0 / Windows 8.1 0.0.0 | 5,120,056 | 71,054
Firefox 60.0.0 / Windows 8.1 0.0.0 | 14,287,836 | 63,247
Mobile Safari 11.0.0 / iOS 11.2.5 | 7,732,968 | 182,511

**Comment by mhegazy** [comment] 2018-06-21 16:22
Historically we have not supported such levels of configurability for the emitted code. I do not think we will be supporting emitting private properties differently using mangling and also have private names supported using private maps.

**Closed** 2018-07-05 17:08 UTC
Labels: Duplicate
