### ISSUE TITLE
Types declared in types.d.ts not included in output of tsc --emitDeclarationOnly

### ISSUE THREAD

**Issue by gthb** [microsoft/TypeScript#51784] opened 2022-12-06 16:48 UTC
# Bug Report

### 🔎 Search Terms

emitDeclarationOnly
allowJs
"missing types"
".d.ts file"
"declaration file"

#### When did you start seeing this bug occur?

Only noticed it just now.

- This is the behavior in every version I tried (`typescript@latest`, `typescript@next`, `typescript@4.6`), and I reviewed the FAQ for entries about declaration files

### ⏯ Playground Link

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEEsDsBMFMA8B0ArAzgKAGYFdIGMAXcAe0lACMBDAJ1AAoBKUAb3VFGtgO2rIHIqALz4BudAF906BAAdi1AqBz4ipJcWL0GALlAAhGgDEyrdp268KNMZPQhQBAJ4zYqRNEQEMTl-qNkAXi1QAIA+UFQCaigAczE7MDQ8UkxwGJQMU1AAImSAWxlwABtYagB5GVVIVGzdLPZsghoYrlqc1wAmAAYOgEZsgBo2dhy84mhsErbszp6OweGGvAALWDwAawApGt0o7FghkdHxydgAJVdiIuwq6chx2AWj7MjowgA5SaKAYVWNnYc1H2w3EhxyUDw1zgbQA2otwTAEBkniNGs5XO5PDVhgBdCRSewySgbSgtDKkdBZbKQSh5R66RqoPAAWlgeXABDgkJolCqpCKjmZaBRaJc0zGEymYOyeUoUGmRXA5GAUDgSGF0p8rmmWtQwEVytVSI8XhFTOilQB9RyLUgup1TNAzJkoCSKTS5LIzOZ9wAouzFJhKEVULAncyuUUeVVw2yOQARNZR6i8kiQMqQAXh4g3ePgWj2kHSuAAN0TLkR+HA2rq8NFrjwFoI0wAegAWRAATkQAGZsiD8UA)

### 💻 Code

```ts repro
// index.js
function bar () {
  return 'baz';
}

/** @returns {BarFn} */
export function foo () {
  return bar;
}

// types.d.ts
type BarFn = () => string;

// jsconfig.json
{
  "compilerOptions": {
    "target": "es2021",
    "module": "es2022",
    "checkJs": true,
    "moduleResolution": "node",
    "strictNullChecks": true
  },
  "include": [
    "index.js",
    "types.d.ts"
  ]
}

// package.json
{
  "name": "tsc-emitdeclarationonly-js",
  "type": "module",
  "main": "index.js",
  "types": "types/lib/index.d.ts",
  "scripts": {
    "gentypes": "tsc -p jsconfig.json --noEmit false --declaration --emitDeclarationOnly --outDir types"
  },
  "devDependencies": {
    "typescript": "^4.9.3"
  }
}
```

### 🙁 Actual behavior

The  command `tsc -p jsconfig.json --noEmit false --declaration --emitDeclarationOnly --outDir types` generates this `types/index.d.ts`:

```ts
/** @returns {BarFn} */
export function foo(): BarFn;
```

which is missing the declaration of `BarFn`.

### 🙂 Expected behavior

I expected the `BarFn` declaration to be included in the generated `types/index.d.ts`:
```ts
/** @returns {BarFn} */
export function foo(): BarFn;
export type BarFn = () => string;
```

... as indeed it is if I move the declaration from `types.d.ts` into `index.js`, expressed in JSDoc form:

```js
/** @typedef {() => string} BarFn */
```

... but I don't want it there and in JSDoc form, I want it in a `types.d.ts` file (visible across my codebase) and in TypeScript form. And included in the generated `types/index.d.ts`.

**Comment by MartinJohns** [comment] 2022-12-06 16:55
By design. This is essentially a duplicate of #32624.

**Comment by gthb** [comment] 2022-12-06 17:26
Thanks. So if I have declared some types in a `.d.ts` file to make them global to my JS project, and want to also publish them as part of my project's public interface ... then that's simply out of scope for `tsc` and I should just copy over that additional `.d.ts` file myself. Correct?

**Comment by gthb** [comment] 2022-12-06 17:57
> copy over that additional .d.ts file myself

... hm, and edit the generated `index.d.ts` file to explicitly import types from that `types.d.ts` file? The type names referenced in the generated `index.d.ts` file do not resolve unless I add an explicit import like:
```ts
import { BarFn } from "./types.d.ts";
```
Is that also as designed? It seems contrary to what happens inside the JS project — types in `types.d.ts` are globally resolvable in all `.js` files in the project, but then when referenced in the generated `.d.ts` file they are not resolvable without manually editing that generated file. 😵

Sorry about the basic questions, I have the feeling I'm missing some intended step or config that makes this make sense. :-)

**Comment by RyanCavanaugh** [comment] 2022-12-07 00:35
If you had a .d.ts file which you consumed and you published it along with your package, and someone else did the same thing, then you'd have a conflict in the global scope.

In general if you're hand-authoring something that's local to your project, it should be in a .ts file, not a .d.ts file.

**Comment by gthb** [comment] 2022-12-08 15:43
[I'm almost there!]

> If you had a .d.ts file which you consumed and you published it along with your package, and someone else did the same thing, then you'd have a conflict in the global scope.

Here you mean specifically a .d.ts file _with no top-level imports or exports_ (so it isn't describing a module, so its declarations go into the global scope) ... is that correct?

In contrast, a _module_ .d.ts. file is OK to publish _and_ consume internally (just have to use `import('...my-module').MyType` instead of `MyType`) ... correct?

> In general if you're hand-authoring something that's local to your project, it should be in a .ts file, not a .d.ts file.

Hm, but _if_ that .ts file contains only type declarations, at least one of which is exported (so the file describes a module), then that is exactly the same thing — the only difference in practice is:
* if the file is named `types.d.ts` then `tsc` will not emit it to `outDir` (so imports from it in files that _are_ emitted will be broken)
* if the file is named `types.ts`, then `tsc` _will_ emit it to `outDir`, with the name `types.d.ts` and identical contents (except for possible formatting differences)

... correct? Or are there other differences?

(In my use case, this file should _only_ contain types, no implementation, and I prefer the .d.ts name in order to both convey and enforce that.)

Then the above example becomes:

```ts repro
// index.js
function bar () {
  return 'baz';
}

/** @returns {import("./types").BarFn} */
export function foo () {
  return bar;
}

// types.d.ts
export type BarFn = () => string;
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEEsDsBMFMA8B0ArAzgKAGYFdIGMAXcAe0lACMBDAJ1AAoBKUAb3VFGtgO2rIHIqALz4BudAF906YACoZoAAKduvVC3ABbAA7FqBOgCJEwAgE8tsVAYaIAQjQBikcaBnB0CHXtA58RUj7ExPRMrOzKPGRU1GKS0mBmFqiI0IgEGJ66BKCJsKD21E6gALwhJQB8oKgE1FAA5mLoQA)

Here I can _either_ rename `types.d.ts` to `types.ts` ... _or equivalently_ just copy it to the `outDir` after running `tsc` ... and either way, that's it, I've published my types, and caused no problems. All correct?

**Comment by sahendrickson** [comment] 2023-01-16 07:06
An external tool generates .d.ts and .js files, which I can't seem to get to work with tsc. I tried renaming the .d.ts file to a .ts file as suggested in this thread, and it doesn't compile: 

.d.ts file has:
```
interface IUpdateServerService { value: string }
export const UpdateServerService: IUpdateServerService;
```

As a .ts file, the compiler error I get is:
```
error TS1155: 'const' declarations must be initialized.
```

It would be nice if tsc could be configured to just directly copy over the .d.ts and .js files.

**Closed** 2023-05-11 23:13 UTC
Labels: Question
