### ISSUE TITLE
"cannot invoke an expression whose type lacks a call signature" on union of types both having this call signature

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/TypeScript#11223] opened 2016-09-28 21:00 UTC
**TypeScript Version:**  2.0.3

**Code**

```ts
function foo ( arg: number[] | string[] ) {
    arg.find ( () => false ); // cannot invoke an expression whose type lacks a call signature
} 

function bar ( arg: (number | string)[] ) {
    arg.find ( () => false );
}
```

**Expected behavior:**

Inside `foo`, `arg` is always an array, either of numbers or of strings, so I expect the `find` method to be recognized by the compiler.

**Actual behavior:** 

It doesn't recognize it, and it throws a `cannot invoke an expression whose type lacks a call signature` error. 

I don't see any good reason why inside `bar` the compiler understands that arg is always an array, but not inside `foo`.

**Comment by kitsonk** [comment] 2016-09-28 21:09
Dupe of #10620 (second one today, after #11205)

**Comment by fabiospampinato** [comment] 2016-09-29 12:42
Sorry about that. I didn't find them on my searches.

**Closed** 2016-09-29 16:29 UTC
Labels: Duplicate
