### ISSUE TITLE
Typeguard is not applied inside following anonymous function

### ISSUE THREAD

**Issue by Arctomachine** [microsoft/TypeScript#58006] opened 2024-03-30 17:52 UTC
### 🔎 Search Terms

typeguard anonymous function

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about typeguards and anonymous functions
- I was unable to test this on prior versions because it happens in earliest possible version, 3.3.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.5.0-dev.20240330#code/C4TwDgpgBAkgdgS2AghgGwCrmgXigbwFgAoKKBAEwC4oBnYAJwTgHMoAfKOAVzTQG4SZOCgC2EGvSasOXXgJIBfQcRIAzbnADGyAPZwowFAxYRgAMU06E+gBSVJjZiwA0XMRLpPWASgJCoBjNuBgMAbUo3EXEAXRVFEnUrPQMwYwg4C2SbOFtdACMAKxp4JFRMbD8iUnI1KFsAQgLCgDpKDk4mopboiCqAsiDgELgVMgTVGq19eigUKDwjEzNLbRS87sioZp6PHzGoabhZ-IX6vxwAPkNjUyy1nI3WrZ3e-agAeg+oCAYGXQYUAAFr8IEoSEA

### 💻 Code

```ts
type InitialType = {
  id: string | null;
  name: string | null;
};

function targetFunction(id: string, name: string) {
  return [id, name];
}

function parentFunction(obj: InitialType) {
  if (!obj.id || !obj.name) {
    return;
  }

  const a = targetFunction(obj.id, obj.name);
  const b = () => targetFunction(obj.id, obj.name); // error here
}
```

### 🙁 Actual behavior

It gives following error when passing parameters to `targetFunction` for `b` assignment (line 16). It happens after typeguard that checks both props of object for null values, so this value is already not null. It happens when doing it inside anonymous function.
```
Argument of type 'string | null' is not assignable to parameter of type 'string'.
  Type 'null' is not assignable to type 'string'.
```

### 🙂 Expected behavior

Expected no error here. Same function is called in line 15 without error.

**Comment by fatcerberus** [comment] 2024-03-30 17:53
Duplicate of #9998

**Comment by Arctomachine** [comment] 2024-03-30 18:00
Then is there known workaround for my use case? Other than making identical typeguard inside function?

**Comment by fatcerberus** [comment] 2024-03-30 18:05
Note that in this case the error is *correct* - `obj` may be mutated before `b` is called, and the compiler would have no way to know.  Workaround: Assign the value of `obj.id` and `obj.name` to a local variable after narrowing.

**Closed** 2024-04-14 01:33 UTC
Labels: Duplicate
