### ISSUE TITLE
tsc -w is unacceptably slow

### ISSUE THREAD

**Issue by oliverjanik** [Microsoft/TypeScript#6178] opened 2015-12-20 23:32 UTC
I'm on windows. Typescript version installed via npm is 1.7.5. When I do `tsc -w` typescript watches for changes but its change detection is really slow. I takes about 10s before it notices I made a change and then recompiles.

What could be causing this?

Edit: Node 5.3.0

**Comment by Olgagr** [comment] 2015-12-21 15:40
I have the same problem with 1.7.5 on Mac. In my case, it takes ~ 5 seconds before it notices that something changed.

**Comment by RyanCavanaugh** [comment] 2015-12-21 18:09
What version of node are you using?

**Comment by Olgagr** [comment] 2015-12-21 19:15
I'm using 5.2.0 but the same problem I had on 0.12.2.

**Comment by DanielRosenwasser** [comment] 2015-12-21 21:18
Pinging @zhengbli and @vladima.

**Comment by DanielRosenwasser** [comment] 2015-12-21 21:23
Just as a heads up everyone, you can go back to 1.7.3 with no user-facing issues. 1.7.5's only change was on file watching behavior which is what you're noticing.

**Comment by fergusg** [comment] 2015-12-22 16:51
FWIW, I see same problem (except even slower ~ 20s delay) on Linux w/ `node 4.0.0`.  Still slow with current snapshot  `1.8.0-dev.20151222`

**Comment by oliverjanik** [comment] 2015-12-22 23:01
I tried 1.7.3 on 5.3.0/Win and it's only marginally better: 4-5s.

**Comment by deflexor** [comment] 2015-12-25 20:12
Same issue on Linux with node 0.10. Delay is about 4-5 seconds. Tried 1.7.5 and 1.7.3 - same result.

**Comment by kamilmac** [comment] 2015-12-27 19:42
Same 5s delay here (ver 1.7.5 and 1.5.3 before) with following tsconfig:

```javascript
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by FlorianBELLAZOUZ** [comment] 2015-12-29 17:02
Same issue 
5 second delay
node v4.1.0 on windows.

tsconfig.json :

``````js
{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false
  },
  "exclude": [
    "node_modules",
    ".git"
  ]
}
``````

**Comment by stefk** [comment] 2016-01-07 10:58
Same issue on linux, node 5.1.0. Fixed with 1.7.3.

**Comment by realyze** [comment] 2016-01-08 00:25
Same issue on Mac OS X 10.11. Downgrading to 1.7.3 helps partially - sometimes the watcher fires fast, most of the time there's a big delay.

**Comment by mhegazy** [comment] 2016-01-08 00:46
PR https://github.com/Microsoft/TypeScript/pull/6026 should address this issue. We should have this in shortly. sorry for the delay.

**Comment by johnpapa** [comment] 2016-01-08 13:47
Thanks for the status update @mhegazy

Looking forward for th fix. This explains a slowdown I have in my angular 2 app using lite-server

**Comment by asadsahi** [comment] 2016-01-08 14:57
I am having slow reload with typescript 1.7+, works fine with typescript 1.6.

Anybody else?

**Comment by mhegazy** [comment] 2016-01-08 22:42
@asadsahi this change was introduced between TS 1.7.3 and  TS 1.7.5, if you are running into issues with TS 1.7.3 then it is a different issue.

**Comment by asadsahi** [comment] 2016-01-08 23:40
I am having same issue with typescript 1.7.3.

**Comment by mhegazy** [comment] 2016-01-09 00:18
@asadsahi that is a different issue then. can you provide more details? how many files do you have? can you share your configurations?

**Comment by oliverjanik** [comment] 2016-01-09 00:45
I think it's still the same issue as many commenters pointed out. There's very little difference between 1.7.3 and 1.7.5 they're both slow compared to other watchers like gulp watch or webpack watch.

**Comment by zhengbli** [comment] 2016-01-14 19:31
A fix was merged in master just now and will be published tomorrow via `typescript@next` on npm, so if anyone is willing to give it a shot it would be great. Thanks!

**Comment by mhegazy** [comment] 2016-01-14 19:39
@oliverjanik, @asadsahi, @stefk, @realyze, @johnpapa, @deflexor, @FlorianBELLAZOUZ, @kamilmac, @fergusg and @Olgagr can you give `typescript@next` a try, and let us know if the issue has been resolved?

**Comment by fergusg** [comment] 2016-01-14 20:11
@mhegazy  It's certainly **better** but still slow with a ~7s lag (1.7.3 is <<1s)

**Comment by zhengbli** [comment] 2016-01-14 20:16
@fergusg the fix was just merged, so it wouldn't be published until tomorrow on `typescript@next`. Could you try again tomorrow or build from master if you are willing to? Thank you! It is expected that changes should be detected **instantly**.

**Comment by fergusg** [comment] 2016-01-14 20:22
@zhengbli @mhegazy No probs - but I might need a fresh poke to remember!

**Comment by stefk** [comment] 2016-01-15 08:46
@mhegazy, @zhengbli, the problem is solved for me, changes are detected instantly (built from master).

**Comment by asadsahi** [comment] 2016-01-15 09:13
got "typescript": "1.8.0-dev.20160114" installed, but I am experiencing the same issue unfortunately. Am I missing something?

**Comment by myitcv** [comment] 2016-01-15 09:17
Was just about to try this myself - doesn't look like the nightly for today built:

```
$ npm show typescript
...
     '1.8.0-dev.20160111': '2016-01-11T07:05:35.365Z',
     '1.8.0-dev.20160112': '2016-01-12T07:05:55.664Z',
     '1.8.0-dev.20160113': '2016-01-13T07:05:48.663Z',
     '1.8.0-dev.20160114': '2016-01-14T07:07:42.963Z' },
...
```

CC @DanielRosenwasser

**Comment by stefk** [comment] 2016-01-15 09:29
@asadsahi, @myitcv, looking at previous build times, it seems the nightly build won't be available before a few hours (it's 1:30 AM on the west coast). You should try building from source.

**Comment by myitcv** [comment] 2016-01-15 09:35
@stefk - these times are UTC, hence the build would ordinarily have completed by now.

**Comment by zhengbli** [comment] 2016-01-15 21:32
@oliverjanik, @asadsahi, @stefk, @realyze, @johnpapa, @deflexor, @FlorianBELLAZOUZ, @kamilmac, @fergusg and @Olgagr 
now a new nightly was published via `typescript@next`, can you give it a try? version:
`typescript@1.8.0-dev.20160115`

**Comment by offsky** [comment] 2016-01-15 21:42
Updated to "typescript@1.8.0-dev.20160115" just now, and tried. It took 12 sec to detect a change to a file.  I have maybe twenty .ts files that it is watching.

**Comment by fergusg** [comment] 2016-01-15 21:58
I've just tried @next `1.8.0-dev.20160115` and it doesn't seem to detect **any** changes.

**Comment by zhengbli** [comment] 2016-01-15 22:12
@fergusg @offsky I just found that there is a bug if you have file names with upper case letters. Is that the case for you guys?

**Comment by fergusg** [comment] 2016-01-15 22:24
@zhengbli no uppercase for me. All lower+hyphen `aaa-bbb-ccc.ts`

**Comment by offsky** [comment] 2016-01-15 22:31
Same for me. All files in the form `aaa-bbb-ccc.ts`

**Comment by zhengbli** [comment] 2016-01-15 23:02
@fergusg @offsky I created a new tsc.js at https://gist.github.com/zhengbli/0e63584b3daf3b521671
Would you mind to try again? Sorry for the hassle.

**Comment by offsky** [comment] 2016-01-16 00:27
Your gist works great.  Sub second file change detection.

**Comment by zhengbli** [comment] 2016-01-16 02:02
@offsky thanks for testing! the fix is merged, should be in tomorrow's nightly.

**Comment by fergusg** [comment] 2016-01-16 17:15
@zhengbli I've just tried `1.8.0-dev.20160116` which seems to work mostly well - very fast change detection, though not *instant* (but <1s).  But sometimes it seems to stop detecting changes (e.g., I've been modding a file and the `tsc -w` would detect those changes and then suddenly stop doing so, no matter what changes I made.  Restarting `tsc -w` works.)

I can't make it fail consistently, though - I'll have a play to see if I can.

**Comment by fergusg** [comment] 2016-01-16 17:29
@zhengbli one reason for the still slightly slow change detection may be that `tsc -w` still seems to be watching  `./node_modules` dir, even though `tsconfig.json` has

```json
    "exclude": [
        "node_modules"
    ]
```

i.e., when I `touch` a `.ts` file in `node_modules`, I get change detection.

**Comment by zhengbli** [comment] 2016-01-16 20:20
Is the `.ts` file in your `node_modules` folder referenced by your file somewhere? If so it is supposed to be watched. I tried to put a random `.ts` file in the `node_modules` folder and didn't see changes were picked up. Can you confirm?

Also, it would be of great help if you can put the error log when the `tsc -w` is not working stably, or point me to a sample project that could lead to a repro. Thanks!

**Comment by fergusg** [comment] 2016-01-16 20:45
@zhengbli 

In my case `@next` gives an error not present in `1.7.3`:

```
> tsc -p . --sourceRoot app

node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2661: 
    Cannot re-export name that is not defined in the module.
```

That's what I used to generate the previously described problem:

```bash
$ touch node_modules/angular2/src/facade/promise.d.ts
```

This gives triggers the change detection.

I'll try to get a sample project together...

**Comment by fergusg** [comment] 2016-01-16 20:56
@zhengbli 

You could *try* https://github.com/fergusg/my-ng2-sandbox which is what I'm using.  I'm slightly embarrassed to point you at that a messy hack job (not intended for anyone but me) which is a learning pit for angular 2, but what the hell...

**Comment by mhegazy** [comment] 2016-01-16 20:56
@fergusg this error is caused by the fix for https://github.com/Microsoft/TypeScript/issues/6323, I will send a fix for the angular package to address the issue.

**Comment by zhengbli** [comment] 2016-01-16 21:08
@fergusg Thanks for the sample! Is this where the watching doesn't work consistently? I tried editing all `.ts` files in the app folder, and all changes were detected, so if there is a problem, it is not caused by the file name. Did you see the issue after a long session? How often do you see it stopped working?

**Comment by fergusg** [comment] 2016-01-16 21:18
@zhengbli Sorry, I can't reproduce reliably :-(

I edit `.ts` files (*Visual Studio Code* FWIW) and mostly those changes are detected.  But "from time to time" `tsc -w` just stops picking up those changes.  Completely.  Only restarting `tsc -w` fixes it.

**Comment by fergusg** [comment] 2016-01-16 21:25
@zhengbli To answer youe questions more explicitly:

> *Did you see the issue after a long session?*
I saw it even after a minute or so with only 2 or 3 `.ts` saves

> How often do you see it stopped working?
3 or 4 times in my recent session (2 hrs with constant saves)

**Comment by johnpapa** [comment] 2016-01-20 03:28
I've run several tests and its very slow with TypeScript 1.7+. I wrote `lite-server` which runs browser-sync. If I run tsc with a watch and browser-sync, on typescript v 1.6 it takes about 2 seconds to reload the page when i have a 1s delay on browser sync. this is awesome.

If I run the same thing with typescript 1.7.5 or typescript@next, it takes 20+ seconds

you can repeat this by pulling the https://github.com/johnpapa/angular2-tour-of-heroes sample, `npm i` and run `npm start` from the command line.

**Comment by zhengbli** [comment] 2016-01-20 05:16
@johnpapa a fix for the slowness in watching mode was merged last week, so the one in `typescripe@next` has the fix in.

**Closed** 2016-01-21 19:49 UTC
Labels: Bug, Fixed, High Priority

**Comment by johnpapa** [comment] 2016-01-21 19:58
i see 1.8 is in this repo, is it going to npm shortly too?

**Comment by mhegazy** [comment] 2016-01-21 20:02
we are closing down on 1.8 bugs. we should have something out in the next few weeks. `typescript@next` now should be very close to the final 1.8 drop.

**Comment by johnpapa** [comment] 2016-01-21 20:03
ok. i saw the version here https://github.com/Microsoft/TypeScript/blob/master/package.json#L5 and got excited and confused  :)

**Comment by mhegazy** [comment] 2016-01-21 20:20
:) we bump up the version in master once we ship to make sure that nighties have the correct version number.

**Comment by danieleds** [comment] 2016-01-25 16:35
@fergusg I have the same issue:

    node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2661:
          Cannot re-export name that is not defined in the module.

Is it a bug in tsc or in Angular?

**Comment by vladima** [comment] 2016-01-25 17:36
this is the issue in angular, I think that the fix is already submitted

**Comment by squarewave24** [comment] 2016-07-19 23:30
im on 1.8.10 and the problem continues on mac. 
that same version on windows is instantaneous. in fact it's identical package.json file as i'm following the ng2 quick start template. for some reason on a mac the changes take 5-20s to be detected

**Comment by squarewave24** [comment] 2016-07-26 23:22
@johnpapa running npm install typings@next screwed me up with this error https://github.com/typings/typings/issues/554
fixed it by running _typings install env~node -SG_, but all this did not do anything for tsc change detection speed.

**Comment by squarewave24** [comment] 2016-07-26 23:30
actually never mind, much faster now :)

**Comment by sumant30** [comment] 2017-03-30 11:10
I am using Node Js ver 7.8.0 and file watcher is taking loads of time recognizing my file changes.

**Comment by zhengbli** [comment] 2017-03-30 20:33
@sumant30 Can you share your tsconfig.json / OS / file system? You are using the `tsc -w` right?

**Comment by sumant30** [comment] 2017-03-31 02:00
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [
      "./node_modules/@types/"
    ]
  },
  "compileOnSave": true,
  "exclude": [
    "node_modules/*",
    "**/*-aot.ts"
  ]
}
