### ISSUE TITLE
Error messages report declared names rather than aliased names

### ISSUE THREAD

**Issue by andrejsm** [Microsoft/TypeScript#16486] opened 2017-06-13 15:51 UTC
**TypeScript Version:**  2.3.4

**Code** [https://github.com/andrejsm/ts-type-alias](https://github.com/andrejsm/ts-type-alias)

**Expected behavior:**
When an error occurs I expect to get a proper reference to aliased types:
```
file: 'file:///Users/andrejs.m/Sites/Typescript/type_alias/src/type-alias.ts'
severity: 'Error'
message: 'Type '{ list: { name: string; value: string; }[]; }' is not assignable to type 'ListProps'.
  Types of property 'list' are incompatible.
    Type '{ name: string; value: string; }[]' is not assignable to type 'ItemProps[]'.
      Type '{ name: string; value: string; }' is not assignable to type 'ItemProps'.
        Types of property 'value' are incompatible.
          Type 'string' is not assignable to type 'number'.'
at: '3,7'
source: 'ts'
```

**Actual behavior:**
Instead I get actual type names:
```
file: 'file:///Users/andrejs.m/Sites/Typescript/type_alias/src/type-alias.ts'
severity: 'Error'
message: 'Type '{ list: { name: string; value: string; }[]; }' is not assignable to type 'Props'.
  Types of property 'list' are incompatible.
    Type '{ name: string; value: string; }[]' is not assignable to type 'Props[]'.
      Type '{ name: string; value: string; }' is not assignable to type 'Props'.
        Types of property 'value' are incompatible.
          Type 'string' is not assignable to type 'number'.'
at: '3,7'
source: 'ts'
```

**Comment by mhegazy** [comment] 2018-04-12 23:17
Duplicate of https://github.com/Microsoft/TypeScript/issues/13095

**Closed** 2018-04-27 17:28 UTC
Labels: Duplicate
