### ISSUE TITLE
allow use export as namespace in .ts

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#24719] opened 2018-06-06 07:09 UTC
## Suggestion

we can use `export as namespace ` in .d.ts

but if .d.ts is create by tsconfig.json compilerOptions declaration=true

then we can't make .d.ts have `export as namespace `

so i hope can allow use export as namespace in .ts 

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment] 2018-06-06 19:48
Duplicate of https://github.com/Microsoft/TypeScript/issues/10907

**Closed** 2018-06-20 22:20 UTC
Labels: Duplicate
