### ISSUE TITLE
Completions crash with AMD + Classic + rooted rootDirs entry

### ISSUE THREAD

**Issue by qxo** [microsoft/TypeScript#47398] opened 2022-01-12 04:48 UTC
```
        return str.lastIndexOf(prefix, 0) === 0;
                   ^
TypeError: Cannot read properties of undefined (reading 'lastIndexOf')
    at Object.startsWith (D:\_bazel_admin\zdx3yfxt\execroot\ankidesktop\node_modules\typescript\lib\tsc.js:1695:20)
    at isPathRelativeToParent (D:\_bazel_admin\zdx3yfxt\execroot\ankidesktop\node_modules\typescript\lib\tsc.js:96841:23)
    at D:\_bazel_admin\zdx3yfxt\execroot\ankidesktop\node_modules\typescript\lib\tsc.js:96797:24
    at Object.firstDefined (D:\_bazel_admin\zdx3yfxt\execroot\ankidesktop\node_modules\typescript\lib\tsc.js:158:26)
    at getPathRelativeToRootDirs (D:\_bazel_admin\zdx3yfxt\execroot\ankidesktop\node_modules\typescript\lib\tsc.js:96795:23)
    at tryGetModuleNameFromRootDirs (D:\_bazel_admin\zdx3yfxt\execroot\ankidesktop\node_modules\typescript\lib\tsc.js:96654:40)
    at getLocalModuleSpecifier (D:\_bazel_admin\zdx3yfxt\execroot\ankidesktop\node_modules\typescript\lib\tsc.js:96422:44)
    at computeModuleSpecifiers (D:\_bazel_admin\zdx3yfxt\execroot\ankidesktop\node_modules\typescript\lib\tsc.js:96400:33)
    at getModuleSpecifiersWithCacheInfo (D:\_bazel_admin\zdx3yfxt\execroot\ankidesktop\node_modules\typescript\lib\tsc.js:96368:26)
    at Object.getModuleSpecifiers (D:\_bazel_admin\zdx3yfxt\execroot\ankidesktop\node_modules\typescript\lib\tsc.js:96353:20)
Target //:dist failed to build

```

===>

https://github.com/microsoft/TypeScript/blob/2ce05a82920aced69f31bb3ab9e7d3e710980e91/src/compiler/core.ts#L2138

**Comment by DanielRosenwasser** [comment] 2022-01-12 06:38
Hi, would you be able to provide more detail on how you got this error (including content requested in the original issue template)? This looks like a duplicate of https://github.com/microsoft/TypeScript/issues/37531.

**Comment by DanielRosenwasser** [comment] 2022-01-12 08:00
https://github.com/microsoft/TypeScript/blob/0f1496f3546dd51b64099732ddac1e59a0367905/src/compiler/moduleSpecifiers.ts#L857

Is likely the culprit, which springs up when you have a rooted disk path.

https://github.com/microsoft/TypeScript/blob/0f1496f3546dd51b64099732ddac1e59a0367905/src/compiler/moduleSpecifiers.ts#L909

**Comment by DanielRosenwasser** [comment] 2022-01-12 08:13
Minimal repro

```json5
// tsconfig.json
{
    "compilerOptions": {
        "module": "amd",
        "moduleResolution": "classic",
        "strict": true,
        "outDir": "../out",
        "rootDirs": ["D:/"]
    },
    "files": [
        "./foo.ts"
    ]
}
```

```ts
// ./foo.ts
/**/
```

Request completions at `/**/`.

```
TypeError: Cannot read property 'lastIndexOf' of undefined
    at Object.startsWith ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:2057:20)
    at isPathRelativeToParent ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:119695:23)
    at [USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:119641:24
    at Object.firstDefined ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:207:26)
    at getPathRelativeToRootDirs ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:119639:23)
    at tryGetModuleNameFromRootDirs ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:119457:40)
    at getLocalModuleSpecifier ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:119115:44)
    at computeModuleSpecifiers ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:119083:33)
    at Object.getModuleSpecifiersWithCacheInfo ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:119043:26)
    at getModuleSpecifiers ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:148875:81)
    at [USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:148879:26
    at Object.flatMap ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:502:25)
    at getNewImportFixes ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:148877:28)
    at Object.getModuleSpecifierForBestExportInfo ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:148694:22)
    at Object.tryResolve ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:128427:34)
    at [USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:130129:46
    at [USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:126080:21
    at Map.forEach (<anonymous>)
    at Object.forEach ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:126078:28)
    at [USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:130111:32
    at resolvingModuleSpecifiers ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:128410:26)
    at collectAutoImports ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:130110:17)
    at getGlobalCompletions ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:130015:17)
    at tryGetGlobalSymbols ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:129921:25)
    at getCompletionData ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:129674:22)
    at Object.getCompletionsAtPosition ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:128474:34)
    at Object.getCompletionsAtPosition ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:160304:35)
    at IOSession.Session.getCompletions ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:171774:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:170619:61)
    at [USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:172423:88
    at IOSession.Session.executeWithRequestId ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:172414:28)
    at IOSession.Session.executeCommand ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:172423:33)
    at IOSession.Session.onMessage ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:172449:35)
    at Interface.<anonymous> ([USERDIR]\scratch\example\node_modules\typescript\lib\tsserver.js:175054:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by DanielRosenwasser** [comment] 2022-01-12 20:06
I'm having a hard time making this work in fourslash.

This doesn't trigger any crash:

```ts
/// <reference path="./fourslash.ts" />

// @module: amd
// @moduleResolution: classic
// @rootDirs: D:/
// @Filename: C:/proj/src/bar.ts
//// /*$*/


verify.completions({
    marker: "$"
});
```

And this one has other issues - fourslash says it can't find the file in question (`Error: Could not find source file: 'C:/proj/src/bar.ts'.`).

```ts
/// <reference path="./fourslash.ts" />

// @Filename: C:/proj/src/tsconfig.json
////{
////    "compilerOptions": {
////        "module": "amd",
////        "moduleResolution": "classic",
////        "rootDirs": ["D:/"]
////    },
////    "include": ["./**/*"]
////}

// @Filename: C:/proj/src/foo.ts
//// export function foo() {}

// @Filename: C:/proj/src/bar.ts
//// /*$*/

verify.completions({
    marker: "$",
    includes: {
        name: "foo",
    }
});
```

**Closed** 2022-01-12 21:45 UTC
Labels: Bug, Crash, Fix Available, Domain: Auto-import

**Comment by DanielRosenwasser** [comment] 2022-01-12 21:46
Please verify that this works with tomorrow's nightly version of TypeScript. If you're using VS Code, you can use https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next, or update your project to `typescript@next` and use the language service that's installed locally.

**Comment by gedeagas** [comment] 2022-01-25 03:53
I have been testing the nightly version it works, but the same crash still occured on 4.5.5 @DanielRosenwasser.

**Comment by eincode** [comment] 2022-01-25 03:54
I have the same problem, but using the nightly build (4.6.0-dev.20220124) solved the crash.

**Comment by DanielRosenwasser** [comment] 2022-01-27 02:45
Strange, but thanks for following up!

There are definitely instances of this occurring in 4.5.5 according to crash reports, so take my questions with a grain of salt because I'm just trying to diagnose things.

First, are you certain that your editor is using the workspace version of VS Code? You can typically validate this by hovering over the `{}` in the status bar.

![image](https://user-images.githubusercontent.com/972891/151282078-670d82c9-c586-4ed5-851c-4da91256d28b.png)

Another way to be sure is running VS Code Insiders which currently is definitely 4.5.5.

If it turns out you really are hitting this in 4.5.5, can you please provide the full stack trace you're seeing, possibly with some information from your `tsconfig.json` if you're able to.

**Comment by DanielRosenwasser** [comment] 2022-01-27 02:49
Please disregard all of that!

I see the issue - we cherry-picked the fix into the wrong branch, so it didn't make its way into 4.5.5. 😖

https://github.com/microsoft/TypeScript/pull/47411#issuecomment-1011810434
