### ISSUE TITLE
Error when implementing a class with a private property

### ISSUE THREAD

**Issue by mrh1997** [microsoft/TypeScript#51183] opened 2022-10-14 21:50 UTC
# Bug Report

### 🔎 Search Terms

implements class private

### 🕗 Version & Regression Information

- This is the behavior in every version I tried up to 4.8.4, and I reviewed the FAQ for entries about "private"

### 💻 Code

```ts
class A {
  private test = 1;
}

class B implements A {}
```

### 🙁 Actual behavior

I get the error     
```
Class 'B' incorrectly implements class 'A'. Did you mean to extend 'A' and inherit its members as a subclass?
      Property 'test' is missing in type 'B' but required in type 'A'.
    'test' is declared but its value is never read.
```

### 🙂 Expected behavior

I would expect that this works properly, as the interface of class `A` does not contain any method or property (`test` is private and thus not part of the interface). A class that implement that interface is expected to be allows to contain no method/property, too.

**Comment by MartinJohns** [comment] 2022-10-14 21:58
Duplicate of #42660.

**Comment by RyanCavanaugh** [comment] 2022-10-14 22:23
The upstream issues fail to have a reason for why.

If a `B` is an `A`, which `implements` checks that it is, then this code should be legal:
```ts
class A {
  private test = 1;
  isSameAs(other: A) {
    return other.test === this.test;
  }
}

class B implements A {}

(new A()).isSameAs(new B());
```
but this code accesses the non-existent `test` property of the `B` instance

**Closed** 2022-10-14 22:24 UTC
Labels: Duplicate
