### ISSUE TITLE
reference tag in comment intellisense does not support https file

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#7631] opened 2016-03-22 08:36 UTC
_From @Thaina on March 22, 2016 3:42_

Please allow `/// <reference>` to support online file

![image](https://cloud.githubusercontent.com/assets/1042507/13941487/a264e602-f01a-11e5-95ef-3ee17b34855a.png)

_Copied from original issue: Microsoft/vscode#4539_

**Comment by kitsonk** [comment] 2016-03-22 08:41
Duplicate of #6465 (which was declined as out of scope)

**Comment by Thaina** [comment] 2016-03-22 08:47
@kitsonk That's why originally I was proposed at vscode repo because I think it was scoped of vscode itself (to have download temporary file and serve to any service like its on file system)

Which, it was moved here. And closed at old one while being duplicated here

**Comment by jrieken** [comment] 2016-03-22 10:21
VS Code isn't involved in any fetching and loading of TS/JS source files and that's why the issue moved here

**Comment by Thaina** [comment] 2016-03-22 10:25
@jrieken And in here you have closed it before because out of scope. Out of scope of plugin means it must be scope of vscode already so that's why

**Comment by mhegazy** [comment] 2016-03-22 16:14
indeed a duplicate of #6465. coping the file locally would be the recommendation here.

**Closed by mhegazy** 2016-03-22 16:14 UTC
Labels: Duplicate
