### ISSUE TITLE
String Literal Discriminated Union Types produce wrong message for missing mandatory properties

### ISSUE THREAD

**Issue by anodynos** [Microsoft/TypeScript#13413] opened 2017-01-11 15:04 UTC
**TypeScript Version:**  2.1.4

**Code**
```ts
interface Bird {
  kind: 'bird'
  birdProp: string
}

interface Cat { 
  kind: 'cat'
  catProp: string
}

interface Dog {
  kind: 'dog'
  dogProp: string
}

// ######### Dog - the last declared interface works well
type AnimalType = Bird | Cat |  Dog;
let aDog: AnimalType;
// also tried `let anAnimal: Bird | Cat | Dog;`, same behavior

aDog = { kind: 'dog', dogProp: 'bar' };  // OK - CORRECT

aDog = { kind: 'dog'};
// BREAKS - CORRECTLY, and with CORRECT error message :
// LiteralTypeInterface.ts (29,1): Type '{ kind: "dog"; }' is not assignable to type 'AnimalType'.
//   Type '{ kind: "dog"; }' is not assignable to type 'Dog'.
//   Property 'dogProp' is missing in type '{ kind: "dog"; }'. (2322)

// #########  Cat - NOT the last declared interface
let aCat: AnimalType;
aCat = { kind: 'cat', catProp: 'bar' }; // OK - CORRECT

aCat = { kind: 'cat'};
// BREAKS - BUT WITH WRONG message:
// LiteralTypeInterface.ts (39,1): Type '{ kind: "cat"; }' is not assignable to type 'AnimalType'.
//   Type '{ kind: "cat"; }' is not assignable to type 'Dog'.
//   Types of property 'kind' are incompatible.
//   Type '"cat"' is not assignable to type '"dog"'. (2322)

// The problem is that the message `Property 'catProp' is missing...` is missing

// ######### Bird - again NOT last declared interface
let aBird: AnimalType;
aBird = {kind: 'bird', birdProp: 'foo'}; // OK - CORRECT

aBird = {kind: 'bird'};
// BREAKS - BUT WITH WRONG message:
// LiteralTypeInterface.ts (47,1): Type '{ kind: "bird"; }' is not assignable to type 'AnimalType'.
//   Type '{ kind: "bird"; }' is not assignable to type 'Dog'.
//   Types of property 'kind' are incompatible.
//   Type '"bird"' is not assignable to type '"dog"'. (2322)

// The problem is that the message `Property 'birdProp' is missing...` is missing

// Also it is NOT reporting additional properties as extraneous, if they exist in any of the other union interfaces (but this is reported in https://github.com/Microsoft/TypeScript/issues/12745)
aBird = {kind: 'bird', dogProp:'shouldNotBeHere'};
```

**Expected behavior:**
String Literal Union Types should produce the correct message for missing mandatory properties of values assigned, for example: 
```
//   Type '{ kind: "dog"; }' is not assignable to type 'Dog'.
//   Property 'dogProp' is missing in type '{ kind: "dog"; }'. (2322)
```

**Actual behavior:**
The wrong message is produced *for all but the last interface declared* : 
```
//   Type '{ kind: "bird"; }' is not assignable to type 'Dog'.
//   Types of property 'kind' are incompatible.
//   Type '"bird"' is not assignable to type '"dog"'. (2322)
```

**Comment by ahejlsberg** [comment] 2017-01-11 17:24
Duplicate of #10867.

**Comment by anodynos** [comment] 2017-01-11 17:33
And also duplicate of #10849

**Closed** 2017-04-19 18:54 UTC
Labels: Duplicate
