### ISSUE TITLE
Spurious 'Index signature is missing in type' error when subclassing

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#1887] opened 2015-02-02 13:23 UTC
Hi,

**TS**: 1.4

Not sure that I agree we should have an error here:

```typeScript
interface Indexer {
        [x: string]: number
}

class Base {

 foo() : Indexer {
	return undefined;
 }
}

/*Error: Class 'Foo' incorrectly extends base class 'Base'.
 Types of property 'foo' are incompatible.
 Type '() => { id: number; }' is not assignable to type '() => Indexer'.
 Type '{ id: number; }' is not assignable to type 'Indexer'.
 Index signature is missing in type '{ id: number; }'.
*/	
class Foo extends Base {

 foo() {
	return { id: 10 };
 }
}
```

**Comment by jbrantly** [comment] 2015-02-02 14:34
I ran into a variation of this with properties and static properties that is affecting me:

```
interface Indexer {
  [x: string]: number
}

class Base {
  static foo: Indexer;
  bar: Indexer;
}

class Foo extends Base {
  static foo = { id: 10 } // Class 'Foo' incorrectly extends base class 'Base'
  bar = { id: 10 } // Class 'Foo' incorrectly extends base class 'Base'
}

Foo.foo = { id: 10 } // no error (which seems correct)
```

**Comment by NoelAbrahams** [comment] 2015-02-02 14:56
Seems related. In my case the error goes away when `foo` is annotated:

```typeScript
 foo() : Indexer {
	return { id: 10 };
 }
```

One shouldn't have to do this.

**Comment by ahejlsberg** [comment] 2015-02-02 18:36
This looks to be a duplicate of #1373

**Comment by RyanCavanaugh** [comment] 2015-02-02 18:37
See also http://stackoverflow.com/questions/22077023/why-cant-i-indirectly-return-an-object-literal-to-satisfy-an-index-signature-re

The last piece of the puzzle is that subclass methods are not contextually typed by their base class function signatures.

(aaand Anders found the issue I was about to link)

**Closed by RyanCavanaugh** 2015-02-02 18:37 UTC
Labels: Duplicate, Suggestion

**Comment by NoelAbrahams** [comment] 2015-02-02 19:31
> The last piece of the puzzle is that subclass methods are not contextually typed by their base class function signatures.

Yes, I see that now. It's all the more confusing because the error message contains information about the mismatch between the base and subclasses. And one is left scratching their head thinking "if the compiler already knows about this, why then is it complaining?!"

I keep getting tripped up by the contextual typing of objects with index signatures. (I feel I've been referred to that SO post before!) The fact that it has taken a long post on StackOverflow kind of hints at the usability issues surrounding this.

Nevertheless it's a very informative response. Thanks!

**Comment by lohiarahul** [comment] 2017-06-19 14:23
Can anyone help me with this scenario please

https://stackoverflow.com/questions/44629786/typescript-index-signature-is-missing-in-type-contextual-typing
