### ISSUE TITLE
Spread syntax error on method call.

### ISSUE THREAD

**Issue by thomaseding** [Microsoft/TypeScript#19556] opened 2017-10-28 22:43 UTC
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
namespace Test {
    class Math {
        public add(x: number, y: number): number {
            return x + y;
        }
    }
    const math = new Math();
    const getMath = () => {
        console.log("getMath() called");
        return math;
    };
    const results = [];
    results.push(math.add(1, 2));
    results.push(Math.prototype.add.apply(math, [1, 2]));
    results.push(math.add.apply(math, [1, 2]));
    results.push(math.add(...[1, 2])); // This shouldn't be a syntax error. Emitted code is as expected.
    results.push(getMath().add(...[1, 2])); // This shouldn't be a syntax error. Emitted code is as expected.
    console.log(results);
}

```

**Expected behavior:**
No syntax error.

**Actual behavior:**
Syntax error.

**Comment by andy-ms** [comment] 2017-10-30 14:50
That's not a syntax error: the error is `Expected 2 arguments, but got a minimum of 0.` Looks like a duplicate of #5453.

**Closed** 2017-11-13 18:06 UTC
Labels: Duplicate
