### ISSUE TITLE
Autocomplete doesn't work with multiple infers within same signature

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#25549] opened 2018-07-10 17:40 UTC
**TypeScript Version:**  3.0.0-dev.20180710

**Search Terms:** 

**Code**

```ts
function foo<T>(a: T, b: T & {}) {}
foo({a: 1}, { /* autocomplete doesn't work here */});
```
But the error knows about all required props:
```
Argument of type '{}' is not assignable to parameter of type '{ a: number; }'.
  Property 'a' is missing in type '{}'.
```

**Expected behavior:**
Should be autocompleted

**Actual behavior:**
No autocomplete

**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment] 2018-07-13 23:13
Duplicate of https://github.com/Microsoft/TypeScript/issues/8005

**Closed** 2018-07-25 18:29 UTC
Labels: Duplicate
