### ISSUE TITLE
Error on inference of extended generic type for rest parameters since TS 2.0

### ISSUE THREAD

**Issue by samchon** [Microsoft/TypeScript#11123] opened 2016-09-24 10:23 UTC
Inference of extended generic type for rest parameters, it fails only when the type of rest parameter is ```number``` or ```string``` since **TS2.0**. When the rest parameter is ```number``` or ```string```, then compiler understands the generic type not to _its origin type_ ```number``` or ```string```, but **its value.**

  - There's a method ```push<U extends T>(...args: U[]): number``` in ```std.List<string>```
  - When calls ```List<string>.push("A", "B", "C")```, then U be "A", not string.

The exact error messages is:
  - **The type argument for type parameter 'U' cannot be inferred from the usage. Consider specifying the type arguments explicitly. Type arguments candidate "A" is not a valid type argument because it is not a supertype of candidate "B"**

The code what I used is:
```typescript
namespace std
{
    export class List<T>
    {
        public push<U extends T>(...args: U[]): number;
    }
}

let x std.List<number>;
let y: std.List<string>;

x.push(1, 2, 3, 4, 5); // FAILED. Understands U is 1
y.push("A", "B", "C", "D", "E"); // FAILED. Understands U is "A"

x.push<number>(1, 2, 3, 4, 5); // OK
y.push<string>("A", "B", "C", "D", "E"); // OK
```

**Comment by HerringtonDarkholme** [comment] 2016-09-24 10:40
This is an expected behavior of literal types. `List<string>.push`  is instantiated to `List.push<U extends string>`. So the compiler infer "A" to its literal type.

https://github.com/Microsoft/TypeScript/pull/10676

**Comment by aluanhaddad** [comment] 2016-09-24 17:11
@HerringtonDarkholme I don't think this is correct behavior. In 2.0.3 it fails as stated by the OP but in 2.1.0-dev.20160924 it gives no error and the type of `U` is `1 | 2 | 3 | 4 | 5` in the first call and `"A" | "B" | "C" | "D" | "E"` in the second

**Comment by mhegazy** [comment] 2016-09-24 20:24
This change was caused by changes in the generic type inference rules for literal types in  https://github.com/Microsoft/TypeScript/pull/10676. Now string and numeric literal types will be inferred if the generic type parameter has a constraint of `string` or `number` respectivelly. Moreover the rule of failing if no best common super-type for inferencesis relaxed in the case of literal types if they have the same base type (e.g. `string`). So in TS 2.1 (`typescript@next` today) ,as noted by @aluanhaddad, `U` will be inferred to be `1 | 2 | 3 | 4 | 5` in the first call and  `"A" | "B" | "C" | "D" | "E"` in the second

**Closed** 2016-09-29 04:06 UTC
Labels: Breaking Change
