### ISSUE TITLE
The `super` keyword in a private method leads to the compilation of incorrect JS code

### ISSUE THREAD

**Issue by Qsppl** [microsoft/TypeScript#60126] opened 2024-10-03 11:04 UTC
### 🔎 Search Terms

"super in private method", "incorrect compilation with super"

### 🕗 Version & Regression Information

This bug appeared in version 4.3.5; before this version, private properties were not supported at all.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=4.3.5#code/MYGwhgzhAECyCeBlApgF2sgHq5A7AJjCqgDy4CuAtgEbIBOAfNAN4CwAUNF9MAPa4RUdcsFS86ACgBuYEOWQQAXNAo16AbQC6AShYduB6BHIAHehO37DXVAAsAlhAB0AYmphUwWwEF8+abLyEJac3AC+HFZcbh5evv4ycgrKqrR0WrpsodYAZuLQEnwC6Iny0Lw50KUKusZmdE5gfgFJIQYR7FHQTQmByClUadrKdo562YZ2dLwA7irIcwCidNOSAAYAJMyjEGHQY-aUlOSoYNQgyACEa23hHGFAA

### 💻 Code

```ts
class MySet extends Set<number> {
    constructor(values: number[]) {
        super()
        this.#batchAdd(values)
    }

    #batchAdd(values: number[]) {
        for (const value of values) super.add(value)
    }

    add(value: number): this {
        throw new Error(`${this} is immutable!`)
    }
}
```

### 🙁 Actual behavior

Running typescript-compiled JavaScript code returns the following error:
Uncaught SyntaxError: 'super' keyword unexpected here 

### 🙂 Expected behavior

I expect that the compiled code will create a MySet class that will work correctly.

![image](https://github.com/user-attachments/assets/ac430e65-c97a-4b9d-876e-19a75fa690da)

**Comment by MartinJohns** [comment] 2024-10-03 12:41
Duplicate of #44515. Used search terms: `super private in:title`

**Closed** 2024-10-07 01:32 UTC
Labels: Duplicate
