### ISSUE TITLE
Proposal: Allow 'missing' types to be treated as optional parameters in function assignment

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#22036] opened 2018-02-19 18:10 UTC
I suggest to allow treating undefined, possibly void and never as well, types to be treated as optional arguments in function assignment.

It doesn't break type system since not passing argument is same as passing undefined explicitly.

```ts
let f= (x: undefined) =>{ }
let g = () => { }

f = g; // Compiles today
g = f;
```

**Comment by mhegazy** [comment] 2018-03-10 00:56
Duplicate of https://github.com/Microsoft/TypeScript/issues/12400

**Closed** 2018-03-26 16:22 UTC
Labels: Duplicate
