### ISSUE TITLE
Ternary with computed property object emits invalid JS

### ISSUE THREAD

**Issue by blacktaxi** [Microsoft/TypeScript#12588] opened 2016-11-30 18:01 UTC
**TypeScript Version:**  2.1.1

**Code**

```ts
const x = true ? { ['test']: 5 } : {};
```

**Expected behavior:**
TS 2.0.6 emits this JS:

```js
var x = true ? (_a = {}, _a['test'] = 5, _a) : {};
var _a;
```

**Actual behavior:**
TS 2.1.1 emits this JS:

```js
var x = true ? _a = {}, _a['test'] = 5, _a : {};
var _a;
```

The problem with it is that it's not a valid JS syntactically. Here's the output from node 5.9.0 from attempt at running it:

```
[stdin]:1
var x = true ? _a = {}, _a['test'] = 5, _a : {};
                      ^

SyntaxError: Unexpected token ,
    at Object.exports.runInThisContext (vm.js:53:16)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:413:34)
    at node.js:550:27
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
```

**Comment by mhegazy** [comment] 2016-11-30 18:10
Looks fixed in latest. can you give `typescript@next` a try.

```sh
c:\test>type a.ts
const x = true ? { ['test']: 5 } : {};

c:\test>tsc --v
Version 2.2.0-dev.20161130

c:\test>tsc a.ts

c:\test>type a.js
var x = true ? (_a = {}, _a['test'] = 5, _a) : {};
var _a;
```

**Closed** 2016-11-30 18:11 UTC
Labels: Fixed

**Comment by vladima** [comment] 2016-11-30 18:12
duplicate of #12413
