### ISSUE TITLE
Readonly<TypedArray> lacks Symbol properties

### ISSUE THREAD

**Issue by 00ff0000red** [microsoft/TypeScript#42681] opened 2021-02-07 04:38 UTC
# Bug Report

### 🔎 Search Terms

readonly, missing symbol property, readonly typedarray

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?useDefineForClassFields=true&esModuleInterop=false&experimentalDecorators=false&emitDecoratorMetadata=false&target=99&ts=4.2.0-dev.20210206#code/MYewdgzgLgBARgJxAawKZgFwwEqoIYAm4ANgJ4A8AqgJZhQAcAgggnqQHwwC8MNdTLNgDoQAMwAUARgA0MAEyyAzLIAsASgDcAKC2hIIYqiHEQAc3FaAkIhToA2gGVSAWzgGh1KKlZQQCALowAPRBMGDgALSoAB7U0Hh0Wpo6etAwAO5+yLSmWHwMzKyk3Ly0BYKkIhIy8kqqybrgEAZGJuZWmQjZYKaOLm7EHl4+foEhMChsSRpAA)

### 💻 Code

```ts
const broken: Readonly<Uint8Array> = Uint8Array.of(1, 2, 3, 4);

broken[Symbol.iterator] // non-existant

const working: Uint8Array = Uint8Array.of(1, 2, 3, 4);

working[Symbol.iterator] // okay
```

### 🙁 Actual behavior

TS claims that Symbol.iterator and Symbol.toStringTag do not exist on Readonly<Uint8Array>.

### 🙂 Expected behavior

Code transpiled without error, Symbol.iterator has the same type on Readonly<Uint8Array> as it does on Uint8Array.

**Comment by MartinJohns** [comment] 2021-02-07 06:50
Looks like a duplicate of #37182. Used search terms: `readonly array symbol`

**Comment by ExE-Boss** [comment] 2021-02-07 11:21
This will be fixed by <https://github.com/microsoft/TypeScript/pull/42543>

**Closed** 2021-02-07 19:02 UTC
