### ISSUE TITLE
allow multiline attributes in tsx

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#13328] opened 2017-01-06 21:05 UTC
```typescript
// test.tsx (jsx = "preserve")

declare namespace JSX {
    interface Element {
        'data-bind': string;
    }
    interface IntrinsicElements {
        div: Element;
    }
}
const div = <div data-bind="
    click: tobeRemovedWorkspace // Property 'click' does not exist on type 'Element'
"></div>;
```

![image](https://cloud.githubusercontent.com/assets/937933/21732885/ca8fc1bc-d429-11e6-9f81-0c6036543afe.png)

**Comment by mvirkkunen** [comment] 2017-08-01 17:03
This is somewhat of a regression as I have a medium sizes codebase that is full of multiline attributes. Before [this commit](https://github.com/Microsoft/TypeScript/commit/a8eb4a20dff9107752f0bce2504c2bfc0a2f6af3) you could work around the problem by using the `\` line continuation escape, but this commit disabled escapes in attributes (which is correct behavior), but also made this codebase not compile on the newest version...

The Babel React JSX transform seems to handle linefeeds in attributes just fine so I think the TypeScript compiler should also handle them.

I looked at the code and it looks like it could be fixed by hacking the scanner further similar the mentioned commit, I'll see if I could make a pull request.

**Closed** 2017-11-30 01:08 UTC
Labels: Bug, Domain: JSX/TSX, Fixed
