### ISSUE TITLE
Do vs2015/vscode use ts language service for js files?

### ISSUE THREAD

**Issue by d180cf** [Microsoft/TypeScript#6063] opened 2015-12-11 05:07 UTC
I noticed a considerable regression in how the editor works in js files since vs2012. It's so dramatic that in some cases I have to open vs2012 and edit js files there. The update 1 for vs2015 has made things a bit better, but still editing js files causes too much frustration. vscode behaves similarly, and they say they use the ts language service, hence the title of the question. Particular problems are:

1
vs2015 often crashes when I attempt to simply view a 100kb js file (the output of tsc). It crashes so often that if I have many things open in vs, I don't dare to open big js files there: I open them separately in notepad or vs2012.

2
The "format the document" feature is pretty much broken: it inserts/removes whitespaces in random places and what's worse is that formatting produces a new random result every time. At least the Undo feature works. vs2012 doesn't have this problem.

3
Pressing Enter often moves the caret at the beginning of the next line, irrespectively to where the current line starts. This is very annoying because I have to press Tab multiple times after every Enter.

```ts
    for (const x of [1, 2, 3]) {
| // <-- this is where it puts the caret
```

4
The matching `)`, `}` and `]`s are inserted in a very intrusive manner and there is no way, afaik, to disable this behavior. This is very annoying when I need to wrap an existing chunk of code into, let's say, a function:

```ts
for (const x of [1, 2, 3])
    console.log(x);
```

this is what I get after typing `function f() {`:

```ts
function f(){}for (const x of [1, 2, 3])
    console.log(x);
```

Now I need to manually pick the closing `}` and relocate it to the right place. Then, of course, when I want to reformat the file to add proper indentation to this little for-loop, the entire file gets messed up.

P.S. I added 1..4 numbers in such a strange way because github desperately tried to outsmart me: it tried to replace 4 with 1, for whatever reason, and then tried to guess indentation, but guessed it wrong.

**Comment by vladima** [comment] 2015-12-11 06:53
out of curiosity,  do you have any entries in Windows event log  that approximately match the time when VS crashes? I suspect it should be errors with .NET Runtime as a source

**Comment by SaschaNaz** [comment] 2015-12-12 13:20
+1 for 4 but maybe that's a VSCode issue.

As for markdown numbering you should indent all sub-paragraphs. Example:

1. Foo

   ```typescript
foo // Indenting the first three-backticks should affect the whole code block
```

2. Bar

**Comment by d180cf** [comment] 2015-12-12 22:19
The 4th issue appears in vs2015.

**Comment by DanielRosenwasser** [comment] 2015-12-14 08:07
Pinging @billti

**Comment by g162h3** [comment] 2015-12-17 00:17
@vladima, perhaps the event log has something, but since the crashing is probably the least significant issue, I wouldn't spend much time on it at the moment.

5
Another curious problem is intrusive line breaks. The moment I type `;` in this code, vs2015 inserts a line break before `}` (obviously, the line break is inserted in such a way, that the indentation for the next line is dropped):

```js
        var r2 = t.send({
});
```

After update 1 for vs2015, I have found that vs2012 no longer works: it starts, but when I open a js file (with just 200-300 lines), it silently quits. Now the only way to edit js files with tests is to use vs2015/vscode and it is a pain. Btw, all the issues appear on different machines.

**Comment by billti** [comment] 2015-12-18 18:31
VSCode uses the TypeScript engine for JavaScript files, whereas VS2015 uses an entirely different engine for JavaScript files. If you are seeing similar behavior in both with regards to auto formatting and indenting that you dislike, then it may well be "by design" rather than a bug (else it seems quite a coincidence it behavior identically in the two different codebases).

The goal is that going forward the JavaScript behavior will be on the same underlying codebase as the TypeScript behavior. Do you see any formatting or indent behavior there you dislike? If so, can you detail what you are seeing and what you would prefer to see instead (or have options for)?

**Comment by mhegazy** [comment] 2016-01-05 20:27
All the issues listed above are external to this repo. marking the issue as such.

**Comment by billti** [comment] 2016-01-07 02:22
Regarding the above:

1. If this is crashing this is the most serious, but you indicate this is the least important. Thus I assume it is happening rarely. If you can provide more details on this please do, and we'll investigate.

2. Format document seems fine to me. I'd need to see specific examples of what you are experiencing to investigate further.

3. Similarly, that code indents correctly for me when I type it in my VS2015 Update1 install. If this occurs only in a larger context, please provide it. (I would note though, that it is flagged as invalid syntax in the VS2015 editor, and formatting will often go awry on invalid syntax. We use the chakra engine and you'll notice the Edge browser also gives invalid syntax on that snippet. (I'd also note while Chrome doesn't give invalid syntax, it also just logs "1" for the 3 iterations, which also seems busted if there should be a fresh binding on each iteration).

4. In VS2015 brace matching is on by default. You can turn it off via "Tools / Options / JavaScript / General / Automatic Brace Completion". I agree it's annoying when you *don't* want it and have to move the closing brace manually (i.e. surrounding code like you mentioned), but there are no plans to try and do anything _smarter_ here and change behavior based on context. Auto brace completion is either on or off.

As mentioned above, is some of these are VSCode specific, you should open issues on their GitHub repo. They don't use our code for JavaScript formatting (that I'm aware of).

**Closed by billti** 2016-01-07 02:22 UTC
Labels: External, Needs More Info

**Comment by SaschaNaz** [comment] 2016-01-07 03:45
@billti I heard they do (https://github.com/Microsoft/TypeScript/issues/6059#issuecomment-164165504) but not with the latest version.
