### ISSUE TITLE
Incremental build: removing/adding new files need to restart tsc

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#49078] opened 2022-05-12 05:47 UTC
# Bug Report

Sorry I cannot give a small reproduction because I believe it is related to big projects.

When I'm working on big composited projects, when I added or remove a file, tsc will not be able to compile it correctly, and I need to restart tsc.

## Add a new file

![image](https://user-images.githubusercontent.com/5390719/168000200-39561a19-27e5-4e32-a939-c49b57db412f.png)

```
packages/mask/src/setup.ui.0.ts:4:19 - error TS6307: File 'packages/mask/src/new-file.ts' is not listed within the file list of project 'packages/mask/src/tsconfig.json'. Projects must list all files or use an 'include' pattern.
```

Config of this project:

```json
  "compilerOptions": {
    "rootDir": "./",
    "lib": ["ES2021"]
  },
  "include": ["./", "./**/*.json"],
```

## Removing a file

![image](https://user-images.githubusercontent.com/5390719/168000488-be9def06-e7ff-46e3-b2a5-97734a3a283c.png)

```
error TS6053: File 'packages/mask/src/utils/shadow-root/renderInShadowRoot.tsx' not found.
  The file is in the program because:
    Matched by include pattern './' in 'packages/mask/src/tsconfig.json'     

  packages/mask/src/tsconfig.json:10:15
    10   "include": ["./", "./**/*.json"],
                     ~~~~
    File is matched by include pattern specified here.
```

Once any of these error occurs, I have to restart TSC to get new type check results.

### 🔎 Search Terms

add remove restart tsc incremental

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

**Comment by craigphicks** [comment] 2022-05-14 06:48
`tsc -b -w` , isn't it?  Incremental and watch?

**Comment by Jack-Works** [comment] 2022-05-14 06:59
Yes we're using `tsc -b -w` since we have multiple projects

**Comment by andrewbranch** [comment] 2022-05-24 22:15
Duplicate of https://github.com/microsoft/TypeScript/issues/47274. @Jack-Works are you able to share the repo where this is happening?

**Comment by Jack-Works** [comment] 2022-05-25 03:07
> Duplicate of #47274. @Jack-Works are you able to share the repo where this is happening?

Yes, it is http://github.com/DimensionDev/Maskbook

**Comment by sheetalkamat** [comment] 2022-05-25 17:14
Thank for the repro. Investigating

**Closed** 2022-05-25 19:30 UTC
Labels: Duplicate

**Comment by Jack-Works** [comment] 2022-05-26 02:44
cool! thanks! this is a quick fix
