### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite in version 4.1

### ISSUE THREAD

**Issue by mateja176** [microsoft/TypeScript#41406] opened 2020-11-04 22:15 UTC
*Motivation*
I wrote a type to make [lodash get[(https://lodash.com/docs/4.17.15#get) and especially [formik getFieldProps](https://formik.org/docs/tutorial#getfieldprops) type safe by writing a generic type which is represent a union of string literal types representing `a full .` separated path to leaf nodes of a possibly nested record. 

**TypeScript Version:**  4.1.0

**Search Terms:**

- Type instantiation is excessively deep and possibly infinite.ts(2589)
- Mapped types
- Generics
- Conditional types

**Code**

```ts
// @ts-ignore
type FieldKey<O extends Record<string, unknown>> = { [key in keyof O]: O[key] extends Record<string, unknown> ? `${string & key}.${string & FieldKey<O[key]>}` : key }[keyof O];
type Example = { dog: "Jacky", toys: { mouse: { color: "gray", teeth: "white" }, bone: { color: 'blue', pimples: true }, box: { cube: { ball: 'red' } } } };
type FieldKey2 = FieldKey<Example>;

```

**Expected behavior:**

No error is thrown.

**Actual behavior:**

`Type instantiation is excessively deep and possibly infinite.ts(2589)` error is thrown.

**Playground Link:** 

This is a [link](https://www.typescriptlang.org/play?ts=4.1.0-beta#code/PTAEAEBcGcFoEsDmA7A9gJwKYChIE8AHTUAMXkwBsATAaUzwB4B5UTAD0k2SulACVMAYwxUG0SOnjJEAGlABXZAGs0Ad2QA+DaAC8oAN6gA2kvqgpoU3lQAzUEwC6ALnsn6D1hy49+QkWIkpWQVlNU1QAH5QAAMAEn1xSWlQADJLegBfADp4xKDU0nJqOkYmNzwHDQzo0BcrUAzy23sHAG5cQmIAUTYAQwBbAgpiPUMqVEQXACIAKV7BJTwpuUhUPGgXQ37UeWhMTdBhCgxpxHRepZXMTEgAC2nVW-hOKYa5ACNUZH2DQ9Rj9AuADk7wo8kwQLkBHgg2GG1AEnBb1AnzYB0E8neP0M716FAowKwVCBDVJGQa7XwREKlFo9AATLoacV6AwegMhpgNO1sNgQKAAIKQTiDGC8-lU4hkWklZieTjcXgCYToUR5aRyRQqVDqLRMuIJQLJNJkdDiAAymAAbpRZUwqjlDUlEAUAMp+biWm0UO0O3JGl1pAAqT1VXttrPt1R5Es6zLppXl3iVflVAWdmtCOs02j0LHYCp8yv8fLAoHMyBsmHQoBKMlL5ZC2vUDY0DfLURKScVoHViHbjaiZRKHgLyd8KrVAczzc0A8bkXjdvKlXnjZcJTXLm+NvQA7q9GaTHaQA) to the playground.

**Related Issues:** 

- https://github.com/microsoft/TypeScript/issues/34933
- https://github.com/microsoft/TypeScript/issues/31619
- https://github.com/microsoft/TypeScript/issues/37613

**Comment by paales** [comment] 2020-11-08 09:54
Experiencing the same with a similar approach. I believe the error wasn't there with typescript 4.1.0-beta, but started to occur with 4.1.1-rc

- [4.1.0-beta, no error](https://www.typescriptlang.org/play?ts=4.1.0-beta#code/PQKgBApgzgNglgOwC4FoAmcoEMBGMJhwC2ADgPYBOSwJFEAZhBeg1gK4yoQAe5VYIYACgkATxIEACliQALAJKkYAHgAqAGjABpCKMjckEBGihgA1rrL0wqgHxgAvELDbd+w8dNQkFRAHNnMAB+GwBtHVEAXXcjEzAACkRGCjAAVQBKUMjAlxCAAwASAG8IgF9Q4oAGMAAfMABGWrAAJiaAZiaAFlLIvKbCkt1y3pywAC4wiOieDziAJQgAY0o0ZW9fBD9NNgQzBDIAdwRbUdz+4rKAOmLpOUUSFVVw3UjNAFFuRZg2NAhlC1EVkmL00AKBOz2hwQWVs9gAZGB1v5SnlTi5zoNRKVrkUPl8fn8wdYnlNQZZrBD9kcYWAEUjNii0RMEBAAG5MQLMtlMADcQhE4ikMgUSmaansDjAtxFDzUZMBxPsdSJNj5AokYAA8jgAFZLJCqMjS8WOKXC+4wMV2GKeRE+fxNFWqYJmu6ik0TJ1q9UED5YJQESVFMBoMh+Cb0rZgJBkURQCbBohkNhQCAJsDLGCUCYAIj8FCwohzTRzdDQOc0hggclzB1kcEMxdKmhwZBZ6cz2bAAHI8GwIN3NCRiA9oBMfP2wM2wK3uBNQsHFmwcGmwMGcFgYDAJt2y92p1PoqUp2rgMAwAAJMjslLXpiu2SmGOIiAEOQEchQKBwPAf4Vgeg4AgGATB9B9TElbU9UWA0jWFZQ-QDE5+SAA)
- [nightly: Type instantiation is excessively deep and possibly infinite.](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201108#code/PQKgBApgzgNglgOwC4FoAmcoEMBGMJhwC2ADgPYBOSwJFEAZhBeg1gK4yoQAe5VYIYACgkATxIEACliQALAJKkYAHgAqAGjABpCKMjckEBGihgA1rrL0wqgHxgAvELDbd+w8dNQkFRAHNnMAB+GwBtHVEAXXcjEzAACkRGCjAAVQBKUMjAlxCAAwASAG8IgF9Q4oAGMAAfMABGWrAAJiaAZiaAFlLIvKbCkt1y3pywAC4wiOieDziAJQgAY0o0ZW9fBD9NNgQzBDIAdwRbUdz+4rKAOmLpOUUSFVVw3UjNAFFuRZg2NAhlC1EVkmL00AKBOz2hwQWVs9gAZGB1v5SnlTi5zoNRKVrkUPl8fn8wdYnlNQZZrBD9kcYWAEUjNii0RMEBAAG5MQLMtlMADcQhE4ikMgUSmaansDjAtxFDzUZMBxPsdSJNj5AokYAA8jgAFZLJCqMjS8WOKXC+4wMV2GKeRE+fxNFWqYJmu6ik0TJ1q9UED5YJQESVFMBoMh+Cb0rZgJBkURQCbBohkNhQCAJsDLGCUCYAIj8FCwohzTRzdDQOc0hggclzB1kcEMxdKmhwZBZ6cz2bAAHI8GwIN3NCRiA9oBMfP2wM2wK3uBNQsHFmwcGmwMGcFgYDAJt2y92p1PoqUp2rgMAwAAJMjslLXpiu2SmGOIiAEOQEchQKBwPAf4Vgeg4AgGATB9B9TElbU9UWA0jWFZQ-QDE5+SAA)

**Comment by pedrodurek** [comment] 2020-12-11 18:20
Hey guys, I'm facing a similar issue, but it seems to be more like a typescript limitation (despite the data size not being that large).
You can see on the examples below that when I'm handling 22 namespaces (ns) it doesn't throw any error, but from 23 namespaces (ns) it does. It infers the proper type though.
* [22 namespaces](https://www.typescriptlang.org/play?noUnusedLocals=true&ts=4.1.2#code/C4TwDgpgBAShDOB7ArgJwMYINIRAHgBUoBeKAa10QDNYEUMEA+EqAbQIF0oIAPYCAHYATeGwEQAbhFRcA-FHjBUASwEBzKAC4oBANwAofQHojUAHKJUAWwCGAG2UAvaPFVq70ATasIwNzPqgkFAA8lbKwACCqKg2IAAKqIhg8ITMpACiPOh2yEIQhAA05JQ0NgIgrByMBkHQkWCQwjggqVgAjMVYAEzpUAAGACQA3h1QAGQKSm4AvgB0I2ER0bEJSSl4PcyTiirqM-214NAW1vZOEN1FUFgsFCDUOn23vPzCovePBPpQUPIErCwXFeghEUEQACMAFYQdDAH5-KANJpCFptYqfGgAoHMAA+SMaoLRm2Kp1sDmcV2x1UYCO04ikqDpUAZ0iOwTJ52caTupR0UHxnIplzSBmMpiFFygVmQdmAyjAHhZ3l8-gQgWOUAAqgJlIgBAREABJAT8VDwWHy-V4LV9AAUWu4fFBonKIAR8jtZG0WoAlCRmBJEMohMzWah-SD3lAvdpVFRpFAjf7iIHg6HfvIjWHJGyNcEADI2RQhKg80g6vUG42m6QWuFVvAIohRsFuxF2lPMIj03NM5it0SdgNQeOJmAe2A5xns+qE4RmADKeDMXT6Q2GZgmUz2ahmmhGtx2032h3zJ0s5IuAFlZfLro7ByUHljigWWEWS2XbX130+tZOyKgkueAFqSl5cgUAIFjSArmBBwq3nKyjXFkOR5AUWpvowtK-L2M6GHU5gqvAfiYCwcBIGgmDwC0cGUfQNEtFUYpEQQABiyACOgLQrsURCkAx1FMCwW5Pl6fIEL6VSTpKzhIfeBCkqwAjIFYELSNUzJic60aYjoskIRchCsGYWl4TubisZqHFcQ21o6W8YJmCRZEQH0mxOk5oi2dxvFmDhdoIvc2hYPoXaWeo1nBFqFoELEAjwHYNhWgIlFgPqForl5LrET4pFqn0wwIsA2i+fZAgrjU+gzGK+Q5DYqDQFQdmpVAyBxQlSUpY2La6c5rmFXaiWyGVvo+p15Tdal6WZVB1XGAAVFAAC0a3rRtm1bdtO3bfoy2-IdR3HbFdZQOgiD5Md103VAi36Ltj1Pc962LUYhGakJDCiKQdSPE1VHfWKF2JcAUAA4xCAsMVvyJe02gw4dIVQIjR3wMgEItNoADkuxuNjCK-DMCIzIUCKJd0COE8+ON4+oBNE2TsPwAAzFTR3I7jJ5qAzUCk+T8AACzs0juC09zvP88zACsIu-JzdM8yTTMsvAABscs01AXO7pLKuJQA7JrCsS8rAsABzG2L2uK3rAsAJxWyA4u62bzPtAADE7Lv427qvtPDKPUybruMwL7SU0HHPWzrvth+7bNR6Lzs26b8f+7LSfyzHtt+3DGtZ1rsf03n8DtEbhch3HfP62XluVznac1+HjsNynxdK+nFNe23Psl138DdIHqNF7nA-dJHI9V-3zczFAxbnZlwDA0vKNQGDc+kB1EDxVNyWpXa2Nw9jvoGCDijgwgd4sMAh-3HM6OY7gJ8r6Da+lev3R8yw2+74l+9VjtKwI+ZdsYcFPvoc+YMAZ3i-r9boh84aaHvo-FoL99BAA)
* [23 namespaces](https://www.typescriptlang.org/play?noUnusedLocals=true&ts=4.1.2#code/C4TwDgpgBAShDOB7ArgJwMYINIRAHgBUoBeKAa10QDNYEUMEA+EqAbQIF0oIAPYCAHYATeGwEQAbhFRcA-FHjBUASwEBzKAC4oBANwAofQHojUAHKJUAWwCGAG2UAvaPFVq70ATasIwNzPqgkFAA8lbKwACCqKg2IAAKqIhg8ITMpACiPOh2yEIQhAA05JQ0NgIgrByMBkHQkWCQwjggqVgAjMVYAEzpUAAGACQA3h1QAGQKSm4AvgB0I2ER0bEJSSl4PcyTiirqM-214NAW1vZOEN1FUFgsFCDUOn23vPzCovePBPpQUPIErCwXFeghEUEQACMAFYQdDAH5-KANJpCFptYqfGgAoHMAA+SMaoLRm2Kp1sDmcV2x1UYCO04ikqDpUAZ0iOwTJ52caTupR0UHxnIplzSBmMpiFFygVmQdmAyjAHhZ3l8-gQgWOUAAqgJlIgBAREABJAT8VDwWHy-V4LV9AAUWu4fFBonKIAR8jtZG0WoAlCRmBJEMohMzWah-SD3lAvdpVFRpFAjf7iIHg6HfvIjWHJGyNcEADI2RQhKg80g6vUG42m6QWuFVvAIohRsFuxF2lPMIj03NM5it0SdgNQeOJmAe2A5xns+qE4RmADKeDMXT6Q2GZgmUz2ahmmhGtx2032h3zJ0s5IuAFlZfLro7ByUHljigWWEWS2XbX130+tZOyKgkueAFqSl5cgUAIFjSArmBBwq3nKyjXFkOR5AUWpvowtK-L2M6GHU5gqvAfiYCwcBIGgmDwC0cGUfQNEtFUYpEQQABiyACOgLQrsURCkAx1FMCwW5Pl6fIEL6VSTpKzhIfeBCkqwAjIFYELSNUzJic60aYjoskIRchCsGYWl4TubisZqHFcQ21o6W8YJmCRZEQH0mxOk5oi2dxvFmDhdoIvc2hYPoXaWeo1nBFqFoELEAjwHYNhWgIlFgPqForl5LrET4pFqn0wwIsA2i+fZAgrjU+gzGK+Q5DYqDQFQdmpVAyBxQlSUpY2La6c5rmFXaiWyGVvo+p15Tdal6WZVB1XGAAVFAAC0a3rRtm1bdtO3bfoy2-IdR3HbFdZQOgiD5Md103VAi36Ltj1Pc962LUYhGakJDCiKQdSPE1VHfWKF2JcAUAA4xCAsMVvyJe02gw4dIVQIjR3wMgEItNoADkuxuNjCK-DMCIzIUCKJd0COE8+ON4+oBNE2TsPwAAzFTR3I7jJ5qAzUCk+T8AACzs0juC09zvP88zACsIu-JzdM8yTTMsvAABscs01AXO7pLKuJQA7JrCsS8rAsABzG2L2uK3rAsAJxWyA4u62bzPtAADE7Lv427qvtPDKPUybruMwL7SU0HHPWzrvth+7bNR6Lzs26b8f+7LSfyzHtt+3DGtZ1rsf03n8DtEbhch3HfP62XluVznac1+HjsNynxdK+nFNe23Psl138DdIHqNF7nA-dJHI9V-3zfM90idT43ofNzMUDFudmXAMDm8o1AYOr6QHUQPFU3JaldrY3D2O+gYIOKODCB3iwwAX-cczo5juDX9voO76Ve-dD5iwI+J9EpnyrHaVgl8y7Yw4DffQd8wYAzvIA363QL5w00G-D+LRv76CAA)

We're relying on those types [here](https://github.com/i18next/react-i18next/blob/master/src/ts4.1/index.d.ts), so I cannot simply use `@ts-ignore` to suppress the error.

**Comment by bsssshhhhhhh** [comment] 2020-12-22 13:57
Currently running into this error on 4.1.2 trying to improve the types in my library. Increasing the constraintDepth limit in getImmediateBaseConstraint() makes the error disappear. 

+1 for turning this into a tsconfig setting instead of hardcoding it like this - it seems to be an arbitrary limit rather than a technical one.

**Comment by ClickerMonkey** [comment] 2020-12-23 01:51
My code base is also plagued by this error, sometimes it goes away for a few seconds, sometimes the exact line the error is being thrown changes, even when the code is not modified. It's interestingly inconsistent!

**Comment by ahejlsberg** [comment] 2021-07-13 23:34
This issue no longer reproduces. Closing.

**Closed by ahejlsberg** 2021-07-13 23:34 UTC
Labels: Needs Investigation

**Comment by zilijonas** [comment] 2021-07-22 09:16
Still getting this error.

**Comment by pedrodurek** [comment] 2021-07-22 12:41
Same ☝️

**Comment by Walraz** [comment] 2021-07-27 14:13
Same error still in 4.3.5

**Comment by paales** [comment] 2021-07-29 09:18
Might be worthwhile to create a testcase in the playground https://www.typescriptlang.org/play?ts=4.4.0-beta and create a new issue
