### ISSUE TITLE
No excess properties error on function return type

### ISSUE THREAD

**Issue by mgiedrius** [microsoft/TypeScript#37017] opened 2020-02-25 16:09 UTC
**TypeScript Version:**  Nightly, 3.7.5

**Search Terms:** excess property, computed property

**Code**

```ts
const a = <T>(shape: T | (() => T)): T => {
    return shape instanceof Function ? shape() : shape;
}
        
//Case 1
a<{ x: string }>(() => ({ x: '', o: '' })); // I expect this to fail

//Case 2
a<{ x: string }>({ x: '', o: '' }); // Fails as expected
```

**Expected behavior:**
I expect `Case 1` to show error similar to `Case 2` because returned object contains more properties than described in generic type.

**Actual behavior:**
`Case 1` is a valid typescript

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200224&ssl=9&ssc=57&pln=1&pc=1#code/MYewdgzgLgBAhjAvDAPAFQHwAoIAs4AOApgFwxowA+MWWAlEhuXXWRYkwN4BQMfMAJyJQArgLAw8hIjACWkKHDDAiIAGYwAYiOVRZ4GAH5J+YvRhkpxANzcAvr35PuAehcBhOBBkBGbnBROGAAPSygBeQBzGDtscw4aINCYAHIUgBoYEDI0mJZrGDcYAEkYImDiYFgoXFkIGCgQGDU4WQAbblcPLxkAJn9AkLCIsGjYrCScjKypvIKizVa2+q8yiqIqogATIA)

**Comment by IllusionMH** [comment] 2020-02-25 16:52
Duplicate of #12632 which requires #241

**Closed** 2020-02-28 18:00 UTC
Labels: Duplicate
