### ISSUE TITLE
Type does not follow workspace since 4.3.2

### ISSUE THREAD

**Issue by bodinsamuel** [microsoft/TypeScript#44488] opened 2021-06-07 19:09 UTC
# Bug Report

Hello team,
Not sure if it's a limitation or a bug, but when using types across workspaces, some of them are not following along.
I can not explain why, but I have a small repro

### 🔎 Search Terms

types, express, workspaces, references,

### 🕗 Version & Regression Information

- This changed between versions 4.2.4 -> 4.3.2
- Still happening with @next

### ⏯ Playground Link

- A working example without workspaces: https://www.typescriptlang.org/play?ssl=21&ssc=3&pln=13&pc=1#code/JYWwDg9gTgLgBAUwB5iggzuuAzKERwDkyqG6hA3AFBUAmCAxgDYCGaOArgHYMzARc46GGxgAJGDDABlBFABucgBQBvKnDiRYAGnVwO6DLo0swYXQF8AXHDUatMG1w4gARnLgAfITCjAuAObUGgYYAPw2AEqM0LQAPMJ+gdqIKGiYAHQAgmZMwAwsfAJeqaSZ0QCOHBjiLFy0THJxdQCeAHxtwXCmYBGl6ejZufmF-ILezkxM1BYAlDYACnggwIbNXO3UNMKiElKyCsp2mtCOcAAcAAzXxvqG6DbHGoTYEBAZACpIMIQ2SmgVFLpWZwAC8bVseg0GjQMA4UEEhFcbEoULgFj0GLmQA
- The repro: https://github.com/bodinsamuel/ts-workspace-typing-issue

```sh
git clone https://github.com/bodinsamuel/ts-workspace-typing-issue.git
cd ts-workspace-typing-issue
yarn
yarn tsc -b
```

```sh
$ /Users/samuelbodin/code/test-ts-workspace/node_modules/.bin/tsc -b
test2/index.ts:6:17 - error TS7006: Parameter 'req' implicitly has an 'any' type.

6     'foo.Txt': (req, res) => {
                  ~~~

test2/index.ts:6:22 - error TS7006: Parameter 'res' implicitly has an 'any' type.

6     'foo.Txt': (req, res) => {
```

### 🙁 Actual behavior

Express `req` and `res` are typed as any
![Screen Shot 2021-06-07 at 21 02 29](https://user-images.githubusercontent.com/1637651/121074411-1c7ed380-c7d4-11eb-8841-7e935d1594d2.png)

### 🙂 Expected behavior

Correct express typing

**Comment by RyanCavanaugh** [comment] 2021-06-10 22:23
Condensed as far as I felt needed, this is a 4.2 -> 4.3 regression
```ts
type StringFunc = (a: string) => void;

declare function startHttpServer(x: { uses: Record<string, NumberFunc | StringFunc>; }): void;

export interface BoolFunc {
  (req: boolean): void;
}

export interface NumberFunc extends BoolFunc {
  (req: number): void;
}

startHttpServer({
  uses: {
    'foo.Txt': (req) => {
      
    }
  }
})
```

**Comment by bodinsamuel** [comment] 2021-06-11 07:25
Amazing @RyanCavanaugh !
So no relation to workspaces actually? :D

**Comment by orta** [comment] 2021-06-15 14:21
Shrunk it down even further, seems to be specific to the contextual typing when there's a union of functions in that position

```ts repro
type StringFunc = (a: string) => void;
type BoolFunc = (a: boolean) => void;

declare function startHttpServer(x: Record<string, BoolFunc | StringFunc>): void;

startHttpServer({
  file: (req) => {}
})
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/C4TwDgpgBAysBOBLAdgcwGIFdkGMoF4oAKAQwC4oBnBFVASgID4oA3Ae0QBMBuAKFEhQAQmzYAbLLgLFyUAEaixEEsgb5m7Ln16cIOMSXjQAZthzBEbZFWCHgACWDAwMCPBZuiADzIAlPWzwnAA81EhoADTCipJ4AD6wNGixjHQUmjy8vNR2js6u7p4A3rxQUADkxqIAdAAqXsDlFERGAI5qzEUAvrxddFm8QA)

**Comment by RyanCavanaugh** [comment] 2021-06-15 16:19
@orta that's not a regression, though - longstanding behavior

**Comment by orta** [comment] 2021-06-15 16:50
This seems off. 

It feels like previously working before is a bug though, on 4.2 it the contextual arg is a string but it 'ideally' should be `string | number | boolean` in  your example, there's nothing which should narrow it down to the single union participant of `arg:string => void` except that two members are overloads of the same func

![Screen Shot 2021-06-15 at 5 43 09 PM](https://user-images.githubusercontent.com/49038/122091866-2d959900-ce01-11eb-8a4a-1ec720d50026.png)

The 4.3 changes might have just brought it inline with the rest of the type system?

**Comment by bodinsamuel** [comment] 2021-06-16 08:41
Hi,

My opinion is probably not highly relevant because I lack a lot of information here, and I'm not sure wether it's a bug or a correction. But the fact the this behavior changes between 2 minors is maybe an issue in itself.
I'm fine with breaking cahnges between major, especially if it's documented why and how to solve it, 
but here it's a clear regression between 4.2.4 -> 4.3.2 (on my repro).
If it really need to happen, would be better to introduce it in 5.0.0 imo.

Best Regards,

**Comment by orta** [comment] 2021-06-29 19:05
Both Major and Minors are effectively major versions for TypeScript, see for the general reasoning https://github.com/Microsoft/TypeScript/issues/14116#issuecomment-280592571 which is why you see long release notes for every major/minor combo. 

I chatted with one of the engineers who I figured might have made the changes for this and they said this change is intentional, ignoring the other functions in the type system because they had an overload was a bug fixed in https://github.com/microsoft/TypeScript/pull/42620

**Closed by orta** 2021-06-29 19:05 UTC
Labels: Has Repro, Working as Intended

**Comment by bodinsamuel** [comment] 2021-06-30 08:37
Make sense for the majors thanks.

---

For the rest I'm not sure I agree with the fix then. In the repro provided by you, the `req` become any while it should be perfectly okay to be `number | boolean`, it's not string or object or whatever, I'm not just sure why it becomes `any`. 

More than that, I **can not help the typing**, if I put `(req: number)` the function now complain that  `Type 'boolean' is not assignable to type 'number'`, which is fair warning but a bit annoying. 
You will say I need to check the typing with a **type guard**, which is fair too but with `number | boolean` a simple if `req === true)`  would have restrained the type very closely to the actual type, while `any` is hardly doable. 
In the end **users will do** `req as boolean | number` and now the **type is no longer in sync with the initial definition**. So tomorrow the definition change to `string | number` and typescript will not complain.
[Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAysBOBLAdgcwGIFdkGMoF4oAKAQwC4oBnBFVASgID4oA3Ae0QBMBuAKF84QcAGxLxoAM2w5giNsirAxwABLBgYGBHgttRAB4UA3lEyUIlCgCUhbeJwA81JGgA0UAHKYAtgCNtWLhQAD6wNGiBOIzcUAC+dBTsXHy8EPpgdsBQKMDaEiQ40ABCbGzCkVBGvFDE4gCOFM60CawcPLyx-GkZ8Fk5eQXQXn4B0lBpuciclFAlZRVVNUT1FMg+-vAtSe2dvNTKahpaOnqLpuaWldU1UADkEqUAdAAq+sC3FMsQdQz4zGc3KA4eTUKDwAhg75QEgzNYjcHBAAFvlKwggJGQfEBnRqnXivCAA)


Anyway, in the end if it's to align the typing system, I have no say in this. 
However I would have loved a **union** or `unknown` more than `any`. _any_ let you do a lot of mistake, while unknown at least complain a bit more. I guess a even better type would be `unguessable`
