### ISSUE TITLE
Tsc crashes after upgrading to 2.7

### ISSUE THREAD

**Issue by atasak** [Microsoft/TypeScript#21697] opened 2018-02-06 20:57 UTC
**Search Terms:** 
crash semicolonClassElement 2.7.1 2.7

**Expected behavior:**
After upgrading to typescript 2.7.1, I expected everything to run as normal. 

**Actual behavior:**
The tsc command crashed with:
```
/usr/lib/node_modules/typescript/lib/tsc.js:59841
                throw e;
                ^

Error: Debug Failure.
    at checkUnusedClassMembers (/usr/lib/node_modules/typescript/lib/tsc.js:35757:38)
    at checkUnusedIdentifiers (/usr/lib/node_modules/typescript/lib/tsc.js:35643:29)
    at checkSourceFileWorker (/usr/lib/node_modules/typescript/lib/tsc.js:37913:21)
    at checkSourceFile (/usr/lib/node_modules/typescript/lib/tsc.js:37891:13)
    at Object.forEach (/usr/lib/node_modules/typescript/lib/tsc.js:260:30)
    at getDiagnosticsWorker (/usr/lib/node_modules/typescript/lib/tsc.js:37957:16)
    at getDiagnostics (/usr/lib/node_modules/typescript/lib/tsc.js:37934:24)
    at Object.getEmitResolver (/usr/lib/node_modules/typescript/lib/tsc.js:20122:17)
    at emitWorker (/usr/lib/node_modules/typescript/lib/tsc.js:59783:69)
    at /usr/lib/node_modules/typescript/lib/tsc.js:59757:66
```

After some digging, I found out that in `src/compiler/utilities.ts:5321 - isClassElement()`, you treat `SemicolonClassElement` as a class element. In `src/compiler/checker.ts:21383 - checkUnusedClassMembers()`, you do not have a case for `SemicolonClassElement`. After running tsc in debug mode, I can confirm `checkUnusedClassMembers()` crashes on an element with `member.kind === SemicolonClassMember`. 

**Playground Link:** 
Because the crash happened after the upgrade, I cannot create a minimal example. I can point you to my repository, but I don't know whether you can get something out of it: https://github.com/atasak/ApiOne

Be sure to checkout on branch `dev`

**Comment by mhegazy** [comment] 2018-02-06 21:28
Duplicate of https://github.com/Microsoft/TypeScript/issues/21491. Fix should be available in `typescript@next` today and in the upcoming `typescript@2.7.2` release in the next 2 weeks.

For workarounds on 2.7.1, the crash is triggered by having `;` after a method or accessor declaration in a class body, removing these should avoid the crash. See https://github.com/Microsoft/TypeScript/issues/21491#issuecomment-362390885 for more details.

**Comment by atasak** [comment] 2018-02-06 21:38
Interesting, I tried typescript@next and it did crash...

I'll wait for the update though. Thanks!

**Closed** 2018-02-06 21:38 UTC
Labels: Duplicate

**Comment by mhegazy** [comment] 2018-02-06 22:03
> Interesting, I tried typescript@next and it did crash...

Just tried on typescript@next on your repo and seems to work.
