### ISSUE TITLE
Check field with optional chaining operator in union types

### ISSUE THREAD

**Issue by reforms** [microsoft/TypeScript#35542] opened 2019-12-06 12:03 UTC
## TypeScript Version: 3.7.2
I'm seeing incorrect behavior when I trying to use optional chaining operator in union type. Instead of writing boilerplate code for using field with optional chaining operator  I'm seeing use short construction. But...

## Code
```typescrypt

type OneField = {
    id: string;
}
type TwoField = {
    id: string;
    data: string;
}
function someWork(owner: OneField | TwoField) {
    if (owner.data?.length) { // Property 'data' does not exist on type 'OneField | TwoField'.
        console.log(owner.data);
    }
    // instead of
    // if ("data" in owner && owner.data?.length) {
    //     console.log(owner.data);
    // }
}
```

## Search Terms
chaining operator, use field

## Suggestion

Short construction for use field with optional chaining operator in union is available

**Comment by dragomirtitian** [comment] 2019-12-06 12:36
While this definitely would be useful, I would expand it out to union access in more contexts if it were implemented. For example, following the same logic, the compiler could allow access to non-common members in conditionals and use it as  a type guard :

```ts
function someWork(owner: OneField | TwoField) {
    if (owner.data) { 
        console.log(owner.data);
    }
}

```
[Playground Link](https://www.typescriptlang.org/play/?ssl=13&ssc=1&pln=8&pc=1#code/C4TwDgpgBA8gdhAYgSwgGwCZQLxQN4CwAUFKVMhgFxQDOwATsnAOYDcxAvsaJFACoB3APYp0WXIRJkK1OoxbsppDAENgK2QyZtOxAGYBXOAGNgyIXFpCAthADqQ+gGsAFEIEJ61eElSYoAD78wqKYAJT4xGTkelBuHhD0AHSq6hF4UFHRZMYWNEJoEEloQszxnilqKmGK0VxE9UA)

One could go further and allow access in any context to non-common members by adding an `| undefiend`  to such uncommon properties. (ie `owner.data` is always a valid access, but `owner.data` is of type `string | undefined`)

Just one note, creating a type to transform a union in such a way to allow the code in the original example, is trivial, and the original union is even still compatible with this new type:

```ts
type OneField = {
    id: string;
}
type TwoField = {
    id: string;
    data: string;
}
type MakeAllUnionHaveAllFieldsHelper<T, KAll extends PropertyKey> =
    T extends T ? T & Partial<Record<Exclude<KAll, keyof T>, undefined>> :
    never;

type AllKeys<T> = T extends T ? keyof T : never;
type MakeAllUnionHaveAllFields<T> = MakeAllUnionHaveAllFieldsHelper<T, AllKeys<T>>

function someWork(owner: MakeAllUnionHaveAllFields<OneField | TwoField>) {
    if (owner.data?.length) { 
        console.log(owner.data);
    }
}

declare let o: OneField | TwoField;
someWork(o)/// Comaptible
```

**Comment by jcalz** [comment] 2019-12-06 20:01
Duplicate of the (declined 😿 ) #33736

**Comment by RyanCavanaugh** [comment] 2019-12-09 18:32
This is a correct error because the code is unsound; you have to account for the possibility of aliasing:
```ts
type OneField = {
    id: string;
}
type TwoField = {
    id: string;
    data: string;
}
function someWork(owner: OneField | TwoField) {
    if (owner.data?.length) { // Property 'data' does not exist on type 'OneField | TwoField'.
        // alleged to be OK
        console.log(owner.data.toLowerCase());
    }
    // instead of
    // if ("data" in owner && owner.data?.length) {
    //     console.log(owner.data);
    // }
}

const obj = { id: "", data: 42 };
const alias: OneField = obj;
// Crashes
someWork(alias);
```

**Closed by RyanCavanaugh** 2019-12-09 18:32 UTC
Labels: Duplicate

**Comment by trusktr** [comment] 2021-01-05 21:46
@RyanCavanaugh Doesn't TypeScript have enough information there to know that `data` is a `number` and not a `string` at the call site? It could throw an error for that case, then optional chaining would be totally useful!

These are the sorts of discussions Hegel.js is having. And I think it would be worthwhile to investigate such concepts (f.e. type checking based on usage sites, not just static information from the type definitions).

For example, instead of

```js
// thing is type Foo | Bar, and only Bar has method()
if (foo instanceof Bar) {
  foo.method()
}
```

we can just write

```js
foo.method?.()
```

which is a lot cleaner.

Also maybe TypeScript can investigate a `discriminated` operator or built-in type or something:

```js
type Foo = discriminated OneField | TwoField

function foo(foo: discriminated OneField | TwoField) {}
```

where `discriminated` causes things to behave more nominally than duckish. New strict options could enforce these things. I think many people would prefer more strictness in various ways.

**Comment by RyanCavanaugh** [comment] 2021-01-05 22:42
> Doesn't TypeScript have enough information there to know that data is a number and not a string at the call site? It could throw an error for that case, then optional chaining would be totally useful!

No, it doesn't. It only knows that `alias` has an `id: number` property.
