### ISSUE TITLE
Unexpected "no compatible call signatures" error

### ISSUE THREAD

**Issue by martinandert** [Microsoft/TypeScript#26770] opened 2018-08-30 12:01 UTC
**TypeScript Version:**  2.9+

**Code**

```ts
interface Messages {
  readonly foo: (options: { [key: string]: any            }) => string;
  readonly bar: (options: { [key: string]: any, a: string }) => string;
}

export const messages: Messages = {
  foo: (options) => "Foo",
  bar: (options) => "Bar",
};

const test1 = (type: "foo" | "bar") => 
  messages[type]({ a: "A" }); // error

const test2 = (type: "foo" | "bar") => // weird, but works
  type === "foo"
    ? messages[type]({ a: "A" })
    : messages[type]({ a: "A" });
```

**Expected behavior:**

`test1` and `test2` are semantically the same. So the `test1` function body should compile fine.

**Actual behavior:**

Error TS2349: Cannot invoke an expression whose type lacks a call signature. 
Type '((options: { [key: string]: any; a: string; }) => string) | ((options: { [key: string]: any; a: s...' has no compatible call signatures.

**Playground Link:** [link](http://www.typescriptlang.org/play/#src=interface%20Messages%20%7B%0D%0A%20%20readonly%20foo%3A%20(options%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20any%20%7D)%20%3D%3E%20string%3B%0D%0A%20%20readonly%20bar%3A%20(options%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20any%2C%20a%3A%20string%20%7D)%20%3D%3E%20string%3B%0D%0A%7D%0D%0A%0D%0Aexport%20const%20messages%3A%20Messages%20%3D%20%7B%0D%0A%20%20foo%3A%20(options)%20%3D%3E%20%22Foo%22%2C%0D%0A%20%20bar%3A%20(options)%20%3D%3E%20%22Bar%22%2C%0D%0A%7D%3B%0D%0A%0D%0Aconst%20test1%20%3D%20(type%3A%20%22foo%22%20%7C%20%22bar%22)%20%3D%3E%20%0D%0A%20%20messages%5Btype%5D(%7B%20a%3A%20%22A%22%20%7D)%3B%20%2F%2F%20error%0D%0A%0D%0Aconst%20test2%20%3D%20(type%3A%20%22foo%22%20%7C%20%22bar%22)%20%3D%3E%0D%0A%20%20type%20%3D%3D%3D%20%22foo%22%0D%0A%20%20%20%20%3F%20messages%5Btype%5D(%7B%20a%3A%20%22A%22%20%7D)%0D%0A%20%20%20%20%3A%20messages%5Btype%5D(%7B%20a%3A%20%22A%22%20%7D)%3B)

**Comment by AlCalzone** [comment] 2018-08-30 12:17
Duplicate of https://github.com/Microsoft/TypeScript/issues/7294 I think

**Closed** 2018-12-14 18:00 UTC
Labels: Duplicate
