### ISSUE TITLE
Exhaustiveness checking fails when target is a property in a non-union type object

### ISSUE THREAD

**Issue by zxTheX** [microsoft/TypeScript#59469] opened 2024-07-30 04:52 UTC
### 🔎 Search Terms

Exhaustiveness checking

### 🕗 Version & Regression Information

TS 5.5, v5.6.0-dev.20240729

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABADwIwAoCeAuRBvAL1wHJUAmAZmIF9EAffIxYygFhoEp8BYAKEQGIAzgHcYUCAAssAOgJc8fQcsQQAhkICmzclWxKVhgEYAnTWoDWAbgOH1W5m2L7+hlafPXbKgCabgaiAANlAubiro6AD62GCaAG6aJhwAvAB8eNQcWBw2ruECHpZ5yrR81Hx8oJCwCChkWLiEJLqcPPnCYhLSmHIK3sr22qSUzgNuRV4dyn4BwaHjhpExcYnJ6ZnZmLmL7mbF3mW8FbxV4NDwSMgUjTqj-R2i4lI57eFDd3q7ypMlbrOBEJhAoCZaxBJJVIZLI5P4g36HRDlIA

### 💻 Code

```ts
// ok
function x1(y: {z: '123'} | {z: '234'}) {
    switch(y.z) {
        case '123':
            break;
        case '234':
            break;
        default:
            ((_:never)=>{})(y);
            break;
    } 
}

function x2(y: {z: '123'}) {
    switch(y.z) {
        case '123':
            break;
        default:
            ((_:never)=>{})(y);  // error, y is treated as { z: '123'; } here
            break;
    } 
}

// ok
function x3(y: '123') {
    switch(y) {
        case '123':
            break;
        default:
            ((_:never)=>{})(y);
            break;
    } 
}
```

### 🙁 Actual behavior

function 'x2' get an error : Argument of type '{ z: "123"; }' is not assignable to parameter of type 'never'.

### 🙂 Expected behavior

Compile pass, because function 'x1' shows that TS can narrow the parent type and 'x3' shows that TS can narrow non-union type

**Comment by MartinJohns** [comment] 2024-07-30 06:21
Duplicate of #18056 / #23572.

**Comment by zxTheX** [comment] 2024-07-30 08:44
I am experiencing the exact same situation in #23572.

However, if the non-union type is unsupported as described in issue #18056, there should be 2 separate error message for examples 'x2' and 'x3'.

**Closed** 2024-08-02 01:31 UTC
Labels: Duplicate
