### ISSUE TITLE
VS2015 does not honor MSBuild properties from external file on file save

### ISSUE THREAD

**Issue by wgebczyk** [Microsoft/TypeScript#4131] opened 2015-08-03 16:34 UTC
When project does import properties from separate MSBuild file via `<Import Project="build.props" />`, The MSBuild is using defined properties, but on file save of TS file it is being ignored.
It worked with with VS13/VS15RC and TS 1.5 beta, but after release it is broken.

I can provide ZIP file with example solution, but I cannot add it to github issue.

**Comment by mhegazy** [comment] 2015-08-03 16:40
looks like a duplicate of #4109

**Comment by wgebczyk** [comment] 2015-08-03 16:54
I'm not using macros. If you have below files, then the properties from build.props are ignored, but if you copy paste properties the behavior is different. It seems that on file save on properties from csproj are parsed, without resolving MSBuild script.

csproj
```
  <PropertyGroup>
<!-- No TS related properties -->
  </PropertyGroup>
  <Import Project="build.props" />
```
and build.props
```
  <PropertyGroup>
    <TypeScriptToolsVersion>1.5</TypeScriptToolsVersion>
    <TypeScriptTarget>ES5</TypeScriptTarget>
    <TypeScriptNoImplicitAny>true</TypeScriptNoImplicitAny>
    <TypeScriptNoEmitOnError>true</TypeScriptNoEmitOnError>
    <TypeScriptGeneratesDeclarations>true</TypeScriptGeneratesDeclarations>
    <TypeScriptPreserveConstEnums>true</TypeScriptPreserveConstEnums>
    <TypeScriptEmitDecoratorMetadata>true</TypeScriptEmitDecoratorMetadata>
    <TypeScriptExperimentalDecorators>true</TypeScriptExperimentalDecorators>
    <TypeScriptRemoveComments>true</TypeScriptRemoveComments>
    <TypeScriptOutFile>js\Aaa.js</TypeScriptOutFile>
  </PropertyGroup>
```

**Comment by mhegazy** [comment] 2015-08-03 17:32
@paulvanbrenk can you take a look.

**Comment by paulvanbrenk** [comment] 2016-04-08 00:42
Unfortunately this is not as easy as I expected it to be. We would have to rewrite most of the logic in how we read the properties from the project file. While it's not hard, it is a significant amount of work. So we have to make a trade off between this, and a feature like snippets. And considering the amount of feedback we have had on this issue, we'll have to postpone this. 

A second issue is the behavior when the user changes settings defined in the external `build.props` file. Currently VS doesn't give us an option to write to that file, meaning we would write to the project file. Which we think will be more confusing than helpful.

**Closed** 2016-04-08 00:44 UTC
Labels: Bug, Too Complex, Visual Studio
