### ISSUE TITLE
Allow non null assertion as shorthand for NonNullable on types

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#46629] opened 2021-11-01 21:35 UTC
# Suggestion

## 🔍 Search Terms

non null assertion type alias indexed

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Following discussion from older issues such as #13253 & #14366: could `...!` be added in the type system as an alias for `NonNullable<...>`?

## 📃 Motivating Example

Referring to nested members of nullable types generally requires using the `NonNullable` type to narrow the outer type. Deeply nested types require a `NonNullable` for each, which can get tiresome.

For example, trying to export a type alias named `Bottom` for `{ data: string; }` from this `Top` type:

```ts
interface Top {
  middle?: {
    bottom?: {
      data: string;
    }
  }
}

// Today's world
export type Bottom = NonNullable<NonNullable<Top['middle']>['bottom']>;

// This proposal
export type Bottom = Top['middle']!['bottom']!;
```

## 💻 Use Cases

Auto-generated types such as with Apollo+GraphQL often need to make objects that are both deeply nested and nullable all the way down.

<details>
<summary>Example of a type I'm working with today</summary>

```ts
export type ArticleQuery = {
  article?: Maybe<{
    body?: Maybe<string>;
    description?: Maybe<string>;
    slug: string;
    title?: Maybe<string>;
    paths?: Maybe<
      Array<{
        goal?: Maybe<string>;
        id: string;
        slug: string;
        title?: Maybe<string>;
        lessonCount: number;
        imageUrl?: Maybe<string>;
        type: 'Path';
      }>
    >;
    tracks?: Maybe<
      Array<{
        proExclusive: boolean;
        id: string;
        slug: string;
        title?: Maybe<string>;
        lessonCount: number;
        type: 'Track';
      }>
    >;
    categories?: Maybe<
      Array<{
        classification?: Maybe<string>;
        slug: string;
        title?: Maybe<string>;
      }>
    >;
  }>;
};

// helper type to make things a little more readable...
export type RequiredRecursive<Entity> = NonNullable<
  {
    [P in keyof Entity]-?: RequiredRecursive<Entity[P]>;
  }
>;

export type ArticleCategory = RequiredRecursive<ArticleQuery>['article']['categories'];
```

</details>

I'll note that while #14366 was closed with the resolution of using the then-newly-available `NonNullable` operator, the `readonly T[]` alias for `ReadonlyArray<T>` is something of an example of two type system ways of doing the same thing.

**Comment by DanielRosenwasser** [comment] 2021-11-01 22:36
Duplicate of https://github.com/microsoft/TypeScript/issues/14366

This was a semi-heated conversation https://github.com/microsoft/TypeScript/issues/17621

If I recall correctly, the counter-proposal to a `!` type operator was to just always strip off the `null` and `undefined` from the operand type of an indexed access type. The people who kind of liked the `!` operator didn't entirely like that counter-proposal, so we did neither.

**Comment by fatcerberus** [comment] 2021-11-02 00:35
> the counter-proposal to a ! type operator was to just always strip off the null and undefined from the indexed type in an indexed access type (i.e. T[K] would always be the same as NonNullable<T>[K])

This doesn't make much sense to me.  Given `obj[key]`, I intuitively expect that value to be assignable to `(typeof obj)[typeof key]`.  Also wouldn't that be a massive breaking change?

**Comment by DanielRosenwasser** [comment] 2021-11-02 04:40
> Also wouldn't that be a massive breaking change?

It shouldn't be, nobody was able to write `NullishObjType[Key]` before.

> Given `obj[key]`, I intuitively expect that value to be assignable to `(typeof obj)[typeof key]`.

Yeah - well it is for all valid accesses of `obj[key]`, but I agree with the perspective that it should probably not do any more than that. The devil's advocate position is to ask what else a user could plausibly want from writing out `NullishObjType[SomeProp]`.

**Comment by fatcerberus** [comment] 2021-11-02 04:46
Ah, that's what I was missing - I got confused and thought the proposal was to strip `null` and `undefined` from `T[K]`, i.e. *after* resolving the indexed-access type.  In other words that `T[K]!` and `T[K]` would be equivalent.

**Closed** 2021-11-06 18:00 UTC
Labels: Duplicate
