### ISSUE TITLE
'Cannot find namespace ...' for type declarations using default-exported module import

### ISSUE THREAD

**Issue by pcan** [Microsoft/TypeScript#4395] opened 2015-08-21 09:05 UTC
I found a strange behaviour when importing a default-exported module from file1 and using it for variable/parameter/return value/whatever... type declarations in file2. Please note that the imported namespace is still visible and works correctly when I use it for variable definitions (e.g. invoking class constructor with new). See the code below:

file1.ts
```TypeScript
export module a {
    export module b {
        export class MyClass {
            x: number = 10;
        }
    }
}

export default a.b;
```

file2.ts
```TypeScript
import y from './file1';

function fn(): y.MyClass {      //warning here: Cannot find namespace 'y'.
    return new y.MyClass();     //it works here, no compiler warning
}

var a = fn();                   //works fine
var b: y.MyClass = fn();        //warning here: Cannot find namespace 'y'.

function fn2(i: y.MyClass) {    //warning here: Cannot find namespace 'y'.
}
```

Instead, for class expression (`export default class {...` in file1.ts) it works fine, both for type declarations and variable definitions.

**Comment by mhegazy** [comment] 2015-08-21 19:21
looks like a duplicate of #4325. 

The problem is the compiler will export all meanings of a name, iff it is an identifier and not a dotted name.. i.e:

```ts
export default a.b; // exports only the value a.b, no type or namespace

export default b; // exports all meanings of b, value, type and namespace
```

i agree that this is a wrong behavior. for now, use an alias to work around the issue:

```ts
export module a {
    export module b {
        export class MyClass {
            x: number = 10;
        }
    }
}

import _b = a.b;
export default _b;
```

**Closed by mhegazy** 2015-08-21 19:21 UTC
Labels: Duplicate

**Comment by pcan** [comment] 2015-08-21 19:54
Ok, thanks.
