### ISSUE TITLE
Feature request: Better poly-type support in arguments list (especially string)

### ISSUE THREAD

**Issue by aight8** [Microsoft/TypeScript#15893] opened 2017-05-16 23:41 UTC
**TypeScript Version:** any

Here are two use cases. Test 1 is currently really a big problem because very lot typings has polymorphic types and if a string or another primitive is possible near any other type it breaks the autocompletion
-> It's possible to explicitly type the passing object sometimes, but if the type cannot be accessed - which is often the case - then there is simply no autocompletion support at all (only type checking of course)

**Code**

```TS
interface Opts {
    aaa: number
    bbb: string
}

interface Opts2 {
    ccc: number
    ddd: string
}

function test1(opts: Opts | string) { }
function test2(opts: Opts | Opts2) { }

// TEST 1 (the string is treated as an object)

test1({
    | <- autocomplete: toString, valueOf
    // Better: aaa, bbb
})

// TEST 2

test2({
    | <- autocomplete: 
    // Better: aaa, bbb, ccc, ddd
})

test2({
    aaa: number
    | <- autocomplete: no suggestions
    // Better: bbb
})

// same for if using a number type. suggestions: toLocaleString, toString, valueOf
// boolean: valueOf

```

**Comment by mhegazy** [comment] 2017-05-16 23:57
Looks like a duplicate of #6405 and #15428, should be fixed by https://github.com/Microsoft/TypeScript/pull/15541 in TS 2.4.

**Comment by aight8** [comment] 2017-05-17 00:15
Ou that's strange I just tested it before with nightly and it was not working - maybe some lag while switching the ts version in vscode.

Okey now it's much better wow (related to the top example).
It's now always suggest: **aaa, bbb, ccc, ddd, toString, valueOf**
So is this final or could this be improved to only show possible entries?

**Comment by mhegazy** [comment] 2017-05-17 16:05
https://github.com/Microsoft/TypeScript/issues/15894 is tracking that.

**Comment by mhegazy** [comment] 2017-06-04 21:08
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-06-04 21:08 UTC
Labels: Duplicate
