### ISSUE TITLE
Official coding practice is not used yourself in declaration files

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#13882] opened 2017-02-04 18:31 UTC
> Don't write overloads that differ by type in only one argument position:
>
> /* WRONG */
interface Moment {
    utcOffset(): number;
    utcOffset(b: number): Moment;
    utcOffset(b: string): Moment;
}
Do use union types whenver possible:
>
>/* OK */
interface Moment {
    utcOffset(): number;
    utcOffset(b: number|string): Moment;
}

https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/declaration%20files/Do's%20and%20Don'ts.md#use-union-types

**TypeScript Version:**  master

**Code**

https://github.com/Microsoft/TypeScript/blob/master/src/lib/es5.d.ts#L330-L340

**Expected behavior:**

```ts
    match(regexp: string | RegExp): RegExpMatchArray | null;
```

**Actual behavior:**

```ts
    /**
      * Matches a string with a regular expression, and returns an array containing the results of that search.
      * @param regexp A variable name or string literal containing the regular expression pattern and flags.
      */
    match(regexp: string): RegExpMatchArray | null;

    /**
      * Matches a string with a regular expression, and returns an array containing the results of that search.
      * @param regexp A regular expression object that contains the regular expression pattern and applicable flags.
      */
    match(regexp: RegExp): RegExpMatchArray | null;
```

**Comment by DanielRosenwasser** [comment] 2017-02-06 09:36
Duplicate of #5766. PR out at #13738 😄

**Closed by DanielRosenwasser** 2017-02-06 09:36 UTC
