### ISSUE TITLE
Unexpected behavior with conditional type when using with object destructuring

### ISSUE THREAD

**Issue by deebov** [microsoft/TypeScript#40647] opened 2020-09-19 12:26 UTC
Getting weird behavior with conditional types when using them with object destructuring. I think the code explains better than words in this situation. Please, go to the [playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBACgTgezAZygXgFBSgHygby2ygBMBLOCAY2DIQDsAuKAIgAsE4yAvB4AQwA2LXKwBuEOLSpCWAbiLYGAYTb96AcwjMAFGKEBXbVHoGAtgCNJASnQA+KGIRkSC7AF8ieQsVIVqtAzMLBYIwGzyilAqaprGOvhQAB4ANFAgUO7MiUnMppaScul55lZwmbZoDk4ubpkKGBhUDMjAJmEA6pwA1mSa6FAJ0fSq6lpp5JQ0dPSZzPBIyJUOPlBkAGaDkwEz6GhoUADkHFy89AKCh7arSiOxWjoATNZEnkQbW-7TDHsHh6HhK4EKIxMYQIa5KAADjSIGYABYKq8MG9mvRWu1gF04L1NI8BjowIgUPNiUt7MDsGiMaC4gMiYsAHS0rREaltbbfWYHBkoRmcwL0IjvTY6AW7fZ-E48PhCIE3YajOJPF4eRrYD5ir6C35HAFseUgu5giHMGHFKCI9yqzIoxrsqAAdx6fQ0BN5yFJi2WlLWoo9-O1Ev2R2lZwuht8AZZ4IAzDa3hr-WTA1MdZK9WEDdcotHjcqcmbYQikWr3EA)

**TypeScript Version:**  4.0.3

**Search Terms:** object destructuring, conditional object destructuring 

**Code**

```ts
type Props =
  | {
    direction: "horizontal" | "vertical";
    onChange: (value: number) => void;
  }
  | {
    direction: "both";
    onChange: ({ x, y }: { x: number; y: number }) => void;
  };


const notWorking = ({ onChange, direction }: Props) => {
  if (direction === 'horizontal') {
    onChange(2)
  }

  if (direction === 'both') {
    onChange({ x: 8, y: 4 })
  }
}

const notWorking2 = (props: Props) => {
  const onChange = props.onChange
  const direction = props.direction
  
  if (direction === 'horizontal') {
    onChange(2)
  }

  if (direction === 'both') {
    onChange({ x: 8, y: 4 })
  }
}

const working = (props: Props) => {
  if (props.direction === 'horizontal') {
    props.onChange(3)
  }

  if (props.direction === 'both') {
    props.onChange({ x: 8, y: 4 })
  }
}
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** [playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBACgTgezAZygXgFBSgHygby2ygBMBLOCAY2DIQDsAuKAIgAsE4yAvB4AQwA2LXKwBuEOLSpCWAbiLYGAYTb96AcwjMAFGKEBXbVHoGAtgCNJASnQA+KGIRkSC7AF8ieQsVIVqtAzMLBYIwGzyilAqaprGOvhQAB4ANFAgUO7MiUnMppaScul55lZwmbZoDk4ubpkKGBhUDMjAJmEA6pwA1mSa6FAJ0fSq6lpp5JQ0dPSZzPBIyJUOPlBkAGaDkwEz6GhoUADkHFy89AKCh7arSiOxWjoATNZEnkQbW-7TDHsHh6HhK4EKIxMYQIa5KAADjSIGYABYKq8MG9mvRWu1gF04L1NI8BjowIgUPNiUt7MDsGiMaC4gMiYsAHS0rREaltbbfWYHBkoRmcwL0IjvTY6AW7fZ-E48PhCIE3YajOJPF4eRrYD5ir6C35HAFseUgu5giHMGHFKCI9yqzIoxrsqAAdx6fQ0BN5yFJi2WlLWoo9-O1Ev2R2lZwuht8AZZ4IAzDa3hr-WTA1MdZK9WEDdcotHjcqcmbYQikWr3EA)

**Related Issues:** -

**Comment by MartinJohns** [comment] 2020-09-19 14:14
Duplicate of #12184.

And on a side-note: There is no "conditional type" in your example. You're having a discriminated union type.

**Comment by RyanCavanaugh** [comment] 2020-09-22 17:47
Thanks as usual @MartinJohns

**Closed** 2020-09-24 18:00 UTC
Labels: Duplicate
