### ISSUE TITLE
Flow is improperly narrowing getter values

### ISSUE THREAD

**Issue by craigphicks** [microsoft/TypeScript#56899] opened 2023-12-29 21:24 UTC
### 🔎 Search Terms

getter narrowing
function return narrowing

an issue where setter (not getter) is behaving like a plain property: #56894

### 🕗 Version & Regression Information

same 4.3.5 ~ 5.2.3
prior to 4.3.5 TypeScript rejected the syntax.

### ⏯ Playground Link
[playground](https://www.typescriptlang.org/play?ts=5.3.2#code/GYVwdgxgLglg9mABMAjABgBQA8BciDeiA5gKZSIBOGAlDigD4BMA3JSQIYAmCANgJ6IAbngaIWyHDQC8APgaNEAX1pC4MTvgBQAem2J9Bw-oB6+jAAd2FdgFsyJCtUS4CbLrwEURiemNYUObjB+IW9fcWA8GkRZRBQfPyVNfRhgRGwAOkEpHJRqLUMsLOYdPQNTCwo4cwcoPidhOOSklLTMihypPIKDCAQAZ3IIGOcMihLdIyny9PMqmoo6py8myenTPrBBxAgRZsVm1PSi4Glc-Ob9Te3hqVHT6gmy6aMKuera+ol0p1j48NKLw2AyGYTE+00B00QA)

### 💻 Code

```ts
function f10(x: { get r():1|2; readonly v: 1| 2; f:()=>1|2 }): void{
//            ^  (parameter) x: { readonly r: 1 | 2; readonly v: 1 | 2; f: () => 1 | 2; }
  if (x.v===1){
    x.v;
//    ^ (property) v: 1
  }
  if (x.r===1){
    const c = x.r;
//              ^ (property) r: 1
//        ^ const c: 1
  }
  if (x.f()===1){
    const c = x.f();
//              ^ (property) f: () => 1 | 2
//        ^ const c: 1 | 2
  }
}
```

### 🙁 Actual behavior

```ts
  if (x.r===1){
    const c = x.r;
//              ^ (property) r: 1
//        ^ const c: 1
  }
```
### 🙂 Expected behavior

``` ts
  if (x.r===1){
    const c = x.r;
//              ^ (property) get r: () => 1 | 2
//        ^ const c: 1 | 2
  }
```

### Additional information about the issue

- A getter is a function, not a plain type, and should behave like one, even though it doesn't have wings.
- The getter is converted to a readonly plain property (probably at point of declaration) as can be seen by tool tipping to `x` which shows `(parameter) x: { readonly r: 1 | 2; readonly v: 1 | 2; f: () => 1 | 2; }`.  Related to #56894.

**Comment by fatcerberus** [comment] 2023-12-29 23:09
Duplicate of https://github.com/microsoft/TypeScript/issues/56149.  That TypeScript is “lossy” and encodes the getter as a regular property in the type is more or less by design.

**Comment by fatcerberus** [comment] 2023-12-29 23:15
Maybe some day we could have a `volatile` keyword, like C…

**Comment by craigphicks** [comment] 2023-12-30 01:57
Oh what a shame.  Now if #56894 is deemed a fixable bug, then setters will be acting like (and hopefully displayed as) functions, while getters will be acting like (and continue to be displayed as?) readonly plain properties.  Maybe it would be best to do them as a pair, with a flag of course for back compatibility.  Just thinking out loud.  Pay no notice.

**Closed** 2024-01-05 01:28 UTC
Labels: Working as Intended
