### ISSUE TITLE
The typescript language service died unexpectedly 5 times in the last 5 minutes

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20446] opened 2017-12-04 18:56 UTC
_From @tferullo on December 4, 2017 16:20_

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.1.2
material-icon-theme|PKi|3.1.0
vscode-eslint|dba|1.4.3
prettier-vscode|esb|0.26.0
bem-expand|luk|0.1.4
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.18.1

(7 theme extensions excluded)

---
I have large files and directories ignored using `files.watcherExclude`

Reproduces without extensions: Yes

I know this bug has been reported many times. I've been experiencing this bug anytime i try to use vs code and  I recently switched `files.useExperimentalFileWatcher` to true. That was working fine for a few days up until a couple minutes ago.

**Then i noticed something that I'm hoping might help**:
I pressed return to start a new line, I didn't immediately type, after about 5ish seconds the new line deleted itself, then the cpu usage for Code Helper sky rocketed from about 0.3% to 130% about a minute later I got the typescript error.

this seemed to be the first error that kicked it off in my tslog:
```
[Info  - 11:01:16] Started TSServer
[Info  - 11:02:08] TSServer exited
[Info  - 11:02:08] TSServer log file: /var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tsserver-log-K1ujp2/tsserver.log
[Info  - 11:02:08] Using tsserver from: /private/var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/AppTranslocation/33554DC8-C7F0-49E9-979D-CC7B49080467/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 11:02:08] TSServer log file: /var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tsserver-log-zfxAib/tsserver.log
[Info  - 11:02:08] Forking TSServer
PATH: /usr/local/opt/openvpn/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[Error  - 11:02:08] 'getApplicableRefactors' request failed with error.
Error: Service died.
```

since then it keeps failing with:
```
[Info  - 11:16:55] Started TSServer
[Info  - 11:17:45] TSServer exited
[Info  - 11:17:45] TSServer log file: /var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tsserver-log-sqzNNl/tsserver.log
[Info  - 11:17:45] Using tsserver from: /private/var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/AppTranslocation/33554DC8-C7F0-49E9-979D-CC7B49080467/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 11:17:45] TSServer log file: /var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tsserver-log-JgjwIV/tsserver.log
[Info  - 11:17:45] Forking TSServer
PATH: /usr/local/opt/openvpn/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[Info  - 11:17:45] Started TSServer
[Info  - 11:18:32] TSServer exited
[Info  - 11:18:32] TSServer log file: /var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tsserver-log-JgjwIV/tsserver.log
[Info  - 11:18:32] Using tsserver from: /private/var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/AppTranslocation/33554DC8-C7F0-49E9-979D-CC7B49080467/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 11:18:32] TSServer log file: /var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tsserver-log-DzloKx/tsserver.log
[Info  - 11:18:32] Forking TSServer
PATH: /usr/local/opt/openvpn/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[Info  - 11:18:32] Started TSServer
```

seems to be restarting itself in some sort of infinite loop.

Hope this provides some insight.

_Copied from original issue: Microsoft/vscode#39563_

**Comment by mjbvz** [comment] 2017-12-04 18:57
@tferullo Is the large files and directories excluded in your `jsconfig.json` or `tsconfig.json`? Can you also please try looking in one of the log file printed in the console to see if there is any helpful information

**Comment by tferullo** [comment] 2017-12-04 19:35
@mjbvz thanks for the reply. So my build doesn't actually use typescript -- its just plain js. But I had read that setting up a tsconfig.json could help so I did that. I tried mirroring the same the same ignore paths i had set within vscode and i kept making it more aggressive as it kept failing. This morning when it failed my tsconfig.json looked like this:

```json
{
    "include": [
    ],
    "exclude": [
        "**/*.js"
        "node_modules",
    ]
}
```

To be honest with you, I switched back to atom after I made this ticket so any outputs in the console are gone but when I open `/var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tsserver-log-JgjwIV/tsserver.log` which I grabbed from the snippets above: I see a bunch of lines similar to this:
```
Info 339  [11:18:2.193] FileWatcher:: Added: PathInfo: /Users/tferullo/Documents/fusion/node_modules/mongodb/lib/gridfs-stream/index.js Project:  WatchType: Closed Script info
```

a lot of the paths I see there are files in node_modules or files in my own build I set it to ignore. The files in my own build I set it to ignore very rarely or never, would ever get open in the editor.

This log file only goes back to 11:17am EST today the high cpu usage and ts crash happened around 11:03/04. there are about 30-50 other log directories in `/var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T`I opened some that were closer to the time but they all kind of look the same. is there any term i can search for?

**Comment by mhegazy** [comment] 2017-12-04 19:43
@tferullo can you share your project and/or your server log file?

**Comment by tferullo** [comment] 2017-12-04 19:51
I would like to but do to NDA stuff, I can't I could share the log file perhaps. I do see that in three places the log file actually outputs contents of some of my files, if I can redact those, I should be able to share it. Would that help?

**Comment by tferullo** [comment] 2017-12-04 19:55
let me see if i can spin up a fake project and get it to fail though im guessing it's something related to my codebase.

**Comment by tferullo** [comment] 2017-12-04 20:12
So i threw together a four-file workspace did some requires and some other stuff. the highest it got was 25% cpu usage. I really think this issue is specific to my codebase or at least large data sets. we work with medical codes and medical code translations and some of those files can exceed a mb. Is there anything I can do differently to ignore those files?

**Comment by tferullo** [comment] 2017-12-04 20:21
going back to using vscode, just to better diagnose the issue didn't take long:

```
[Info  - 15:15:16] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 15:15:16] TSServer log file: /var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tsserver-log-9gd99L/tsserver.log
[Info  - 15:15:16] Forking TSServer
PATH: /usr/local/opt/openvpn/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[Info  - 15:15:16] Started TSServer
[Info  - 15:16:24] TSServer exited
[Info  - 15:16:24] TSServer log file: /var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tsserver-log-9gd99L/tsserver.log
[Info  - 15:16:24] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 15:16:24] TSServer log file: /var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tsserver-log-To0yIT/tsserver.log
[Info  - 15:16:24] Forking TSServer
PATH: /usr/local/opt/openvpn/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[Error  - 15:16:24] 'getApplicableRefactors' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:388:32)
	at ChildProcess.childProcess.on (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:291:30)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 15:16:24] Started TSServer
[Error  - 15:16:25] 'quickinfo' request failed with error.
Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:81131:23)
    at ProjectService.getDefaultProjectForFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83831:46)
    at IOSession.Session.getFileAndProjectWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86055:87)
    at IOSession.Session.getFileAndProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86040:29)
    at IOSession.Session.getQuickInfoWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86100:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85266:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86660:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86669:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86689:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:87881:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
[Info  - 15:17:10] TSServer exited
[Info  - 15:17:10] TSServer log file: /var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tsserver-log-To0yIT/tsserver.log
[Info  - 15:17:10] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 15:17:10] TSServer log file: /var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tsserver-log-1JcleK/tsserver.log
[Info  - 15:17:10] Forking TSServer
PATH: /usr/local/opt/openvpn/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[Error  - 15:17:10] 'getApplicableRefactors' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:388:32)
	at ChildProcess.childProcess.on (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:291:30)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 15:17:10] Started TSServer
```

If we could do a screen share, or just an email I can show you some key stuff in the log from this error.

**Comment by tferullo** [comment] 2017-12-05 01:15
@mhegazy

**Comment by mhegazy** [comment] 2018-01-04 19:52
@tferullo is this still happening? if so can you share your project? feel free to use my email if you would rather not share it on github.

**Comment by tferullo** [comment] 2018-02-07 15:15
@mhegazy I would like to but it's from a private company of which I'm an employee. Interestingly, we have two main repos (directories) one of them is pretty large, I'd guess over 1000 files  and it contains some big "data" files which are really just giant js arrays. I've instructed the editor to ignore these big files in every which way... heres my settings.json:

```json
{
  "editor.fontFamily":
    "'Operator Mono', Menlo, Monaco, 'Courier New', monospace",
  "editor.fontSize": 16,
  "workbench.colorTheme": "Dracula Soft",
  "workbench.iconTheme": "material-icon-theme",
  "editor.renderControlCharacters": false,
  "editor.renderWhitespace": "none",
  "editor.minimap.enabled": false,
  "editor.formatOnSave": true,
  "javascript.format.enable": false,
  "prettier.eslintIntegration": true,
  "editor.fontLigatures": true,
  "window.zoomLevel": 0,
  "editor.wordWrap": "on",
  "files.watcherExclude": {
    "**/.git/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/**": true,
    "**/logs/**": true,
    "**/data/**": true,
    "**/Quality/**": true,
    "**/Envision/**": true,
    "**/Predict/**": true,
    "**/Grader/grade_modules/**": true,
    "**/test/**": true,
    "**/build/**": true,
    "**/**/*.xml": true
  },
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true,
    "**/build/**": true
  },
  "typescript.tsserver.log": "verbose",
  "editor.multiCursorModifier": "ctrlCmd",
  "editor.tabSize": 2,
  "files.useExperimentalFileWatcher": false
}
```
the folders I ignored in `files.watcherExclude` are where these big data files reside -- doesn't seem to help the problem at all though.

The second repo is for our frontend and it is considerably smaller. I only experience this problem with the larger repo open in vs code and yes I am still experiencing the issue.

**Comment by tferullo** [comment] 2018-02-07 15:19
@mhegazy are you able to sign an NDA? I may be able to make that work on my end with a screen share if you think you could get a better sense of the problem with a screen share.

**Comment by mhegazy** [comment] 2018-02-07 17:52
do you have a jsconfig.json? can you share that? do you have the data files excluded in the config file? how do you import the data files? are you using `require` ?

**Comment by mhegazy** [comment] 2018-02-07 17:53
and yes we can sign an NDA.

**Comment by tferullo** [comment] 2018-02-07 19:18
@mhegazy yeah, it's a node project so all the files are imported with `require` 
we dont use typescript but I did try adding the following tsconfig.json
```
{
  "compilerOptions": {
    "lib": ["es5", "es6"],
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node"
  },
  "exclude": [
    "node_modules",
    "logs/**",
    "**/data/**",
    "**/Quality/**",
    "**/Envision/**",
    "**/Predict/**",
    "**/Grader/grade_modules/**",
    "test/**",
    "build/**"
  ]
}
```

**Comment by tferullo** [comment] 2018-02-07 19:21
@mhegazy we're in the middle of a sprint right now but maybe we can setup some time the week of the 21st?

**Comment by mhegazy** [comment] 2018-02-07 19:33
> we're in the middle of a sprint right now but maybe we can setup some time the week of the 21st?

sure.

One things to do also is to run `tsc --noEmit --listFiles --p <path to your tsconfig.json>` this will show you the files the compiler picked up for your project.

You can also share/email your tsserver logs, this will allow me to see what files are included in the project and we can see what is going on without having access to the full project. the file will include some information from your project, so you should look at it before posting it on github.

**Comment by tferullo** [comment] 2018-02-07 19:39
when I run that command I get the following:

```
error TS18003: No inputs were found in config file '/Users/tferullo/Documents/fusion/tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["node_modules","logs/**","**/data/**","**/Quality/**","**/Envision/**","**/Predict/**","**/Grader/grade_modules/**","test/**","build/**"]'.
/usr/local/lib/node_modules/typescript/lib/lib.es2015.d.ts
/usr/local/lib/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts
/usr/local/lib/node_modules/typescript/lib/lib.es2015.reflect.d.ts
/usr/local/lib/node_modules/typescript/lib/lib.es2015.proxy.d.ts
/usr/local/lib/node_modules/typescript/lib/lib.es2015.iterable.d.ts
/usr/local/lib/node_modules/typescript/lib/lib.es2015.symbol.d.ts
/usr/local/lib/node_modules/typescript/lib/lib.es2015.promise.d.ts
/usr/local/lib/node_modules/typescript/lib/lib.es2015.generator.d.ts
/usr/local/lib/node_modules/typescript/lib/lib.es2015.collection.d.ts
/usr/local/lib/node_modules/typescript/lib/lib.es2015.core.d.ts
/usr/local/lib/node_modules/typescript/lib/lib.es5.d.ts
```

**Comment by mhegazy** [comment] 2018-02-07 19:42
Since these are all .js files, you need to either use `jsconfig.json`  instead of `tsconfig.json` (name of the file implies some defaults) or add `"allowJs": true` in your `tsconfig.json`.

**Comment by tferullo** [comment] 2018-02-07 19:42
i can get you some logs for sure, is there a quick way to get the .log file?

**Comment by tferullo** [comment] 2018-02-07 19:43
ok cool, I'll try switching the name to jsconfig

**Comment by mhegazy** [comment] 2018-02-07 19:49
what do you see now in `tsc --noEmit --listFiles --p <path to your jsconfig.json>` ?

**Comment by tferullo** [comment] 2018-02-07 19:54
```
#
# Fatal error in , line 0
# API fatal error handler returned after process out of memory

#
# Fatal error in , line 0
#
#
API fatal error handler returned after process out of memory
#
Illegal instruction: 4
Tonys-MacBook-Pro-2:fusion tferullo$
```

**Comment by tferullo** [comment] 2018-02-07 20:24
@mhegazy I have some logs from just the last 10 mins or so that I can share with you, whats your email address?

**Comment by mhegazy** [comment] 2018-02-07 20:31
github username @microsoft.com

**Comment by tferullo** [comment] 2018-02-07 20:41
👍 sent. I also updated the jsconfig.json file to be more specific:
```json
{
  "compilerOptions": {
    "lib": ["es5", "es6"],
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node"
  },
  "exclude": [
    "node_modules",
    "logs/**",
    "Parser/processing/data/**",
    "Grader/grade_modules/**",
    "Quality/2017/data/**",
    "test/**",
    "build/**"
  ]
}
```

didn't help though.

**Comment by mhegazy** [comment] 2018-02-09 18:09
Seems like the same underlying issue as in https://github.com/Microsoft/TypeScript/issues/20629

**Comment by sheetalkamat** [comment] 2018-02-20 19:01
#20629 is fixed now. Can you please try out typescript@next to see if the issue is fixed?

**Comment by tferullo** [comment] 2018-02-21 15:40
@sheetalkamat  sure! will let you know.

**Comment by tferullo** [comment] 2018-02-21 16:07
still experiencing the same behavior :(

here's what I did:

- npm install -g typescript@next
- changed `typescript.tsdk` in settings to `/usr/local/lib/node_modules/typescript/lib`
- restarted vscode
- still getting the same error with the typescript server quiting

Did I miss a step?
@sheetalkamat

**Comment by sheetalkamat** [comment] 2018-02-21 17:40
@tferullo Can you share your tsserver log to see whats going on.. I would suggest getting the verbose log so we can have as much information as needed. You can send it across to shkamat@microsoft.com in case you don't want to share it on github

**Comment by tferullo** [comment] 2018-02-21 17:58
OK getting that for you now, In the typescript terminal in vscode, I keep seeing this error:

```
Error processing request. No Project.
```
happens on signatureHelp and getApplicableRefactors
@sheetalkamat

**Comment by tferullo** [comment] 2018-02-21 18:02
sent the logs @sheetalkamat

**Comment by sheetalkamat** [comment] 2018-04-05 17:29
Closing this since havent heard from @tferullo in last couple of weeks about more info.

**Closed by sheetalkamat** 2018-04-05 17:29 UTC
Labels: Bug, Needs More Info, VS Code Tracked
