### ISSUE TITLE
Private non-nullable fields can still be null after construction (strictnullchecks)

### ISSUE THREAD

**Issue by shand-obs** [Microsoft/TypeScript#12273] opened 2016-11-15 18:25 UTC
**TypeScript Version:**  2.1.1 & nightly (2.2.0-dev.20161115)

**Code**

```ts
class TestStrictNullChecks {
    public test() {
        var x = 0;
        var y = this.notNullable + x; // notNullable is undefined

        console.log(y);
    }

    private notNullable: number; // ERROR: with strictNullChecks, should be required initialized on construction (inline or in ctor)
}

const testObject = new TestStrictNullChecks();
testObject.test();
```

**Expected behavior:**
tsc should error, either on class definition or on object construction; _notNullable cannot be undefined or null.

**Actual behavior:** 
tsc succeeds; NaN is output in console.

**Comment by RyanCavanaugh** [comment] 2016-11-15 18:32
Duplicate of #8476 and many others. Please search before logging a new issue.

**Closed by RyanCavanaugh** 2016-11-15 18:32 UTC
Labels: Duplicate

**Comment by shand-obs** [comment] 2016-11-15 18:38
Honestly, I spent 20 minutes searching for a duplicate issue before posting. The trouble is that the default search criteria restricts to open bugs. It didn't occur to me to search for closed bugs, because to us it's not _closed_. I tested in both the 2.1 RC and the 2.2@next daily.

**Comment by shand-obs** [comment] 2016-11-15 18:49
I added my comment to #8467. Please re-open. This issue is definitely not resolved.
