### ISSUE TITLE
Excessive stack depth comparing types 'FlatArray<Arr, ?>' and 'FlatArray<Arr, ?>'. ts(2321)

### ISSUE THREAD

**Issue by simonsinclair** [microsoft/TypeScript#43258] opened 2021-03-15 22:24 UTC
# Bug Report

### 🔎 Search Terms

- Excessive stack depth comparing types
- FlatArray
- 2321
- JSX

### 🕗 Version & Regression Information

- This changed between versions `4.2.3` and `4.3.0-dev.20210314`.

### 💻 Code

```tsx
const Component = (): JSX.Element => {
  const categories = ['Fruit', 'Vegetables'];

  return (
    <ul>
      <li>All</li>
      {categories.map((category) => (
        <li key={category}>{category}</li>
      ))}
    </ul>
  );
};

export default Component;
```

### 🙁 Actual behavior

The following TypeScript error:
> Excessive stack depth comparing types 'FlatArray<Arr, ?>' and 'FlatArray<Arr, ?>'. ts(2321)

![no-ok](https://user-images.githubusercontent.com/1430787/111216843-d1866300-85cc-11eb-86df-598b8724ecdb.png)

### 🙂 Expected behavior

I expect this code not to produce an error.

**To work around:**
- Remove the preceding list item (`li`) OR
- Switch VSCode's TS version from `4.3.0-dev.20210314` to the workspace's (`4.2.3`).

![ok](https://user-images.githubusercontent.com/1430787/111217023-fd094d80-85cc-11eb-9e5e-0d04d55e3821.png)

**Possible related issue:**
- https://github.com/microsoft/TypeScript/issues/43249

**Comment by andrewbranch** [comment] 2021-03-15 22:35
Duplicate of #43249—different trigger, same bug.

**Comment by KarelHrkal** [comment] 2021-03-17 13:49
Found another workaround - just add an extra fragment:
```typescript
<ul>
  <li>Hello</li>
  <>
    {[1, 2, 3].map((n) => (
      <li key={n}>{n}</li>
    ))}
  </>
</ul>
```

**Closed** 2021-03-19 18:00 UTC
Labels: Duplicate

**Comment by sinanyaman95** [comment] 2021-03-23 18:30
> Found another workaround - just add an extra fragment:
> 
> ```ts
> <ul>
>   <li>Hello</li>
>   <>
>     {[1, 2, 3].map((n) => (
>       <li key={n}>{n}</li>
>     ))}
>   </>
> </ul>
> ```

Thanks, a lot!
