### ISSUE TITLE
missing declaration: the typescript.js has 'getTransformers' function, but in typescript.d.ts missing 'getTransformers' declaration

### ISSUE THREAD

**Issue by halo951** [microsoft/TypeScript#50352] opened 2022-08-18 08:21 UTC
# Bug Report

### 🔎 Search Terms

```
ts.getTransformers = getTransformers
```

### 🕗 Version & Regression Information

branch: main
version: 4.7.4 ~ 4.9.0 

### ⏯ Playground Link

https://github.com/microsoft/TypeScript/blob/66d8b959412d48e4ae827429cbcc5f1b8ec52027/lib/typescript.js#L104442
https://github.com/microsoft/TypeScript/blob/66d8b959412d48e4ae827429cbcc5f1b8ec52027/lib/typescript.d.ts

### 💻 Code

```ts
import * as ts from 'typescript'

// ! this method is hidden, so, I can only call this method through ` as any'.
const transformers = (ts as any).getTransformers({
    target: ts.ScriptTarget.ESNext,
    module: ts.ModuleKind.ESNext,
    declaration: true
})

ts.transpileModule(code, {
        compilerOptions: {
            target: ts.ScriptTarget.ESNext,
            module: ts.ModuleKind.ESNext,
            declaration: true
        },
        transformers: {
            before: t.declarationTransformers
        }
})
```

### 🙁 Actual behavior

the typescript.js has 'getTransformers' function, but in typescript.d.ts missing 'getTransformers' declaration

### 🙂 Expected behavior

in typescript.d.ts, has `getTransformers` declaration. because in some specific cases, this method will be used. 
for example, when the .d.ts declaration file is generated using 'transpilemodule'

**Comment by MartinJohns** [comment] 2022-08-18 08:48
It's not a bug, this is intentional. It's marked as internal: https://github.com/microsoft/TypeScript/blob/cb1bc6169b03c56b9906856ce6e7e9cad0155b7a/src/compiler/transformer.ts#L1

**Closed** 2022-08-20 20:00 UTC
Labels: Working as Intended

**Comment by halo951** [comment] 2022-08-22 08:49
> It's not a bug, this is intentional. It's marked as internal:
> 
> https://github.com/microsoft/TypeScript/blob/cb1bc6169b03c56b9906856ce6e7e9cad0155b7a/src/compiler/transformer.ts#L1


thanks, i didn't notice this before.

**Comment by halo951** [comment] 2022-08-22 08:50
thanks, i didn't notice this before.
