### ISSUE TITLE
Not Immutable Types

### ISSUE THREAD

**Issue by Renstrio24p** [microsoft/TypeScript#57038] opened 2024-01-12 09:17 UTC
### 🔎 Search Terms

.push method is still pushing tru it value to tuples
![image](https://github.com/microsoft/TypeScript/assets/123795328/1bd19a41-046a-4b13-bdd2-2c7fe909105b)

.push method does not exist on type NotImmutableType
however push method is still working as expected please improve this immutable checking to prevent these bugs

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://codesandbox.io/p/sandbox/vanilla-typescript-vanilla-ts?file=%2Fsrc%2Findex.ts%3A9%2C9&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrafalmv00062a6bxii3zb47%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrafalmv00022a6b64bin765%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrafalmv00032a6bk51g8w1p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrafalmv00052a6bo6h4bz33%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrafalmv00022a6b64bin765%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrafalmv00012a6bfql6zb0d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrafbue2003x2a6bbcmua9zm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A9%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A9%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrafalmv00022a6b64bin765%2522%252C%2522activeTabId%2522%253A%2522clrafbue2003x2a6bbcmua9zm%2522%257D%252C%2522clrafalmv00052a6bo6h4bz33%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrafalmv00042a6bgeszh5qa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrafalmv00052a6bo6h4bz33%2522%252C%2522activeTabId%2522%253A%2522clrafalmv00042a6bgeszh5qa%2522%257D%252C%2522clrafalmv00032a6bk51g8w1p%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrafalmv00032a6bk51g8w1p%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 💻 Code

type NotImmutableTuple = readonly [string, number]
type ImmutableTuple = [string, number]

export default function Immutable(DOM: HTMLDivElement) {

  DOM.innerHTML = (`
    <div>
      <h1>Immutable</h1>
    </div>
  `);

  let apples: NotImmutableTuple = ['green', 2];
  let cheese: ImmutableTuple = ['melon',3]
  
  if(apples.length > 2){
    console.log('Immutable')
  } 
  cheese.push('banana') // push method exist on type ImmutableTuple
  
  console.log(apples)

}

### 🙁 Actual behavior

Property 'push' does not exist on type 'NotImmutableTuple'.ts(2339)

however push method still working on NotImmutableTypes

### 🙂 Expected behavior

TypeScript can prevent Immutable types on tuple pairs to pushing through the new value in that array of pairs
it will turn error like this

Property 'push' wasn't unable to push a new value on Tuple pairs consider to add 1 type to make it only 3 pairs. ts(2339)

**Comment by MartinJohns** [comment] 2024-01-12 09:30
Your "Playground link" does not seem to match the code you posted here.

Sounds like a duplicate of #40316 and #6325.

**Comment by RyanCavanaugh** [comment] 2024-01-12 17:56
```
type NotImmutableTuple = readonly [string, number]
type ImmutableTuple = [string, number]
```
It seems like you just reversed these? I don't understand what you're getting at here

**Comment by fatcerberus** [comment] 2024-01-12 19:21
@RyanCavanaugh OP is complaining that the mutable tuple allows `.push()` (and other array mutations), basically

**Comment by craigphicks** [comment] 2024-01-13 08:37
It's just an error message issue:
```
Property 'push' does not exist on type 'readonly [1]'.(2339)
```
could have been 
```
mutating operation 'push' forbidden on type 'readonly [1]'.(2339)
```
The workaround is to read between the lines.

**Closed** 2024-01-16 01:29 UTC
Labels: Unactionable
