### ISSUE TITLE
Type predicate results stored in variables don't narrow guarded types

### ISSUE THREAD

**Issue by bgmort** [Microsoft/TypeScript#22341] opened 2018-03-05 20:53 UTC
**TypeScript Version:**  2.8.0-dev.20180222

**Search Terms:** 
assignable type guards
assignable type guard return value
assign type guard to variable

**Code**

```ts
interface A {
    type: 'A';
    aProperty: string;
}

interface B {
    type: 'B';
    bProperty: number;
}

type AorB = A | B;

function isA(obj: AorB): obj is A {
    return obj.type === 'A';
}

const o = { type: 'A', aProperty: 'value' } as any as AorB;

// this should be an error, and it is
console.log(o.aProperty);

// this should work, and it does
if (isA(o)) {
    console.log(o.aProperty);
}

// this example discards the type guard information, but it 
// ought to set oIsA to type (o is A), and apply the type
// guard inside the if statement. 
const oIsA = isA(o);
if (oIsA) {
    console.log(o.aProperty);
}
```

**Expected behavior:**
`oIsA` should have the type returned by the type guard function.  `if (oIsA)` ... should narrow the type of `o` within the if block.

**Actual behavior:**
`oIsA` is a regular boolean value.  The type guard function can only be used directly within a conditional block.

**Playground Link:**  
https://goo.gl/6Pk5vr

**Related Issues:**

**Comment by DanielRosenwasser** [comment] 2018-03-05 21:50
I can't find the other duplicates, but we only check syntactically whether `isA` is a user-defined type guard at the `if` check (and other syntactic locations). The type predicate return type is really just a `boolean` in any other context. So `oIsA` doesn't track any information about the type of `o` itself.

We've considered this problem, but it seems fairly complex and expensive to solve in a general way.

**Comment by bgmort** [comment] 2018-03-06 05:57
@DanielRosenwasser  I found the duplicates neither of us could find the first time around.  This one seems to be the most similar:  https://github.com/Microsoft/TypeScript/issues/14891

**Comment by mhegazy** [comment] 2018-03-06 20:34
I think #14891 is a different issue.. 

the is a duplicate of https://github.com/Microsoft/TypeScript/issues/15482 #14630, #10976, #12263, #10065, and #10846

**Closed** 2018-03-22 15:41 UTC
Labels: Duplicate
