### ISSUE TITLE
Host @types packages individually on GitHub

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#11973] opened 2016-11-01 15:07 UTC
@types packages are generated from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) and published to the npm registry. These packages are included by listing them as a dependency in a project's `package.json`, just like any other npm dependency. Unlike _most_ npm dependencies, however, there is no simple way to fork an @types package and declare the fork as a dependency.

As an example, I've had need of an updated type definition for [vega](https://github.com/vega/vega), so I started working on a [PR to DT](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12215), except there was no easy way to develop this update (save going into my node modules folder and making changes). I would be incredibly useful if I could find a repository for the published package at a known location (linked to in the package.json), so I could [fork it](https://github.com/weswigham/AtTypes-vega) and list the fork as a dependency (for example: `"@types/vega": "weswigham/AtTypes-vega"`) in my package.json while I work on it/while I wait for the PR to be reviewed.

**Comment by blakeembrey** [comment] 2016-11-01 15:45
Something like https://github.com/Microsoft/types-publisher/issues/4?

**Comment by mhegazy** [comment] 2016-11-01 16:13
looks like a duplicate of https://github.com/Microsoft/types-publisher/issues/4

**Comment by weswigham** [comment] 2016-11-01 18:59
IDK, I don't really care about redirects in DT, just about the packages being easily forkable and thus replaceable. And this affects things which already exist in DT, niy new things. And I'm not asking for individual packages to be published instead of on DT, it'd just be nice to see them alongside the published npm package.

**Comment by blakeembrey** [comment] 2016-11-01 19:21
It seems like it would be the enabler to me. You need a way to fork and have replaceable packages, which means you need some form of individual code repositories. For that to work, the `types-publisher` needs to be updated to make it work. The only other way is to create dozens of mirrors of DefinitelyTyped, but I think that's a huge step backward and confusing.

**Comment by blakeembrey** [comment] 2016-11-01 19:27
FWIW, the issue you're seeing is a pretty normal mono-repo setup with NPM. See `babel` and `lerna`. I guess normal development works through NPM link locally and waiting to be published, but I understand the need to use the definitions immediately (mentioned as a reason for Typings to exist in bullet 2 of https://github.com/typings/typings/issues/72#issuecomment-165571916). Also, the way people can use @types (GitHub) definitions today is by using that same `npm install` from GitHub feature, but I'm not sure anyone actually uses it like this over Typings directly.

**Comment by weswigham** [comment] 2016-11-01 19:36
@blakeembrey Since I'm not concerned with having repos linked back to DT, the repos can just be published alongside their npm packages. Mirroring/forking DT just doesn't work since it's not structured as npm packages - only the publisher build output is. What I'd propose is simply that the same thing that gets uploaded to npm at present also get uploaded to an easily forkable git repo. As I've already demonstrated via my links in the OP, I don't need Typings or any tool to substitute @types packages today, it's just a little cumbersome to do so since I have to manually copy the built package contents (and strip a bunch of installation metadata) as downloaded from npm into a repo that I can redirect npm.

**Comment by blakeembrey** [comment] 2016-11-01 19:49
I understand, but you can't really have both easily. If you have a GitHub repo that has just those contents and nothing else, how do the contributions make it back to DefinitelyTyped? Most people aren't going to fork this mirrored repo, make edits, push them up to use them and _then_ recreate the same PR to DefinitelyTyped.

**Comment by mhegazy** [comment] 2016-11-01 19:52
> What I'd propose is simply that the same thing that gets uploaded to npm at present also get uploaded to an easily forkable git repo.

I would be concerned about where ppl should send their PRs or file issues, is it the main DT repo or the individual repos.

**Comment by mhegazy** [comment] 2016-11-01 19:52
//cc: @andy-ms

**Comment by weswigham** [comment] 2016-11-01 20:04
@mhegazy Disable github issues/pull requests on each repo and set the repo description to the associated folder on DT?

**Comment by blakeembrey** [comment] 2016-11-07 17:29
@weswigham That doesn't help contributing back. What would that look like? Fork it, make changes, push, fork DefinitelyTyped, copy and paste changes, make PR, pull from fork when `types-publisher` runs, repeat?

**Closed** 2024-03-04 22:28 UTC
Labels: Discussion
