### ISSUE TITLE
Partial does not work inside a method that uses the class generic parameter type

### ISSUE THREAD

**Issue by asfernandes** [Microsoft/TypeScript#14265] opened 2017-02-23 12:38 UTC
**TypeScript Version:**  2.1.6

The subject is a bit difficult to write, but look in the code inside `method`.

`{ id: 1 }` should be implicit convertible to `Partial<T>` as `T extends { id: number }`.

```ts
interface Intf<T extends { id: number }>
{
	find: (obj: Partial<T>) => T;
}

interface Obj
{
	id: number;
	name: string;
}

const intf: Intf<Obj> = {
	find(obj: Obj)
	{
		return obj;
	}
}

intf.find({ id: 1, name: '' });	// ok
intf.find({ id: 1 });	// ok

class Component<T extends { id: number }>
{
	constructor (public intf: Intf<T>)
	{
	}

	method()
	{
		this.intf.find({ id: 1 } as T);	// ok
		this.intf.find({ id: 1 });	// error! why?
	}
}

const component = new Component<Obj>(intf);
component.intf.find({ id: 1, name: '' });	// ok
component.intf.find({ id: 1 });	// ok
```

**Comment by mhegazy** [comment] 2017-02-23 18:05
The error is correct since `T` can be more specialized than its constraint `{id: number}`. consider:

```ts
const component = new Component<{id: 2}>(intf);
component.intf.find({ id: 1 });	// Error
```

**Comment by asfernandes** [comment] 2017-02-23 18:46
Then what about this?

```ts
class Component<T extends { id: number }>
{
	constructor (obj: T)
	{
		obj.id = 10;
	}
}

new Component<{id: 2}>({ id: 2 });
```

It works and violates the type system as well the behavior I intended does.

**Comment by mhegazy** [comment] 2017-02-23 19:48
That is a duplicate of https://github.com/Microsoft/TypeScript/issues/14150

**Closed** 2017-04-21 16:55 UTC
Labels: Working as Intended
