### ISSUE TITLE
tsc: watch --build slower than watch without --build 

### ISSUE THREAD

**Issue by mastodon0** [microsoft/TypeScript#46705] opened 2021-11-05 22:20 UTC
# Bug Report

### 🔎 Search Terms

tsc, watch, --build, performance, tryReuseStructureFromOldProgram 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about watch, --build

### ⏯ Playground Link

[Repo link](https://github.com/mastodon0/tscperftest)

### 💻 Code

n/a

### 🙁 Actual behavior

Watching a project using --build takes longer to compile than omitting the --build option. The difference could be up to multiple seconds, depending on the project size.

Here is the trace for my [sample repo](https://github.com/mastodon0/tscperftest) running ```tsc --build tsconfig.json --watch``` after saving notImported.ts
![slow](https://user-images.githubusercontent.com/7924332/140583456-68d225af-1678-4912-8b91-ebff661b6d0a.png)
[trace-slow.txt](https://github.com/microsoft/TypeScript/files/7489158/trace-slow.txt)

Here is the trace when running ```tsc --project tsconfig.json --watch``` and saving the same file.
![fast](https://user-images.githubusercontent.com/7924332/140583441-68452fe2-ff56-423c-a466-b584b9e09767.png)
[trace_fast.txt](https://github.com/microsoft/TypeScript/files/7489154/trace_fast.txt)

The big difference seems to be that --build doesn't run tryReuseStructureFromOldProgram. 
I tried to poke around in the code and it seems that the program state gets released during [emitBuildInfo](https://github.com/microsoft/TypeScript/blob/47cd4d3ecf6f99a33cbc4d2cfe74d1bf8b9443ec/src/compiler/tsbuildPublic.ts#L1138)

### 🙂 Expected behavior

Watching using tsc --build --watch should be able to reuse the last program state to speed up compile times

**Comment by andrewbranch** [comment] 2021-11-05 22:53
Duplicate of #45082, likely also the same thing as https://github.com/microsoft/TypeScript/issues/46420

**Closed** 2021-11-08 18:00 UTC
Labels: Duplicate
