### ISSUE TITLE
intellisense say error on clone new constructor() syntax

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/TypeScript#36721] opened 2020-02-10 19:21 UTC
https://github.com/microsoft/vscode/issues/90311#event-3020816501

**Comment by jcalz** [comment] 2020-02-10 20:10
Likely a duplicate of #3841.  There is a [template](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) you are supposed to follow when filing a new issue here; even if this is not a duplicate it might be closed as unactionable because you have not followed the proper procedure.

**Closed** 2020-02-10 20:33 UTC
