### ISSUE TITLE
Object is incorrectly typed as 'possibly null' after import without ability to check

### ISSUE THREAD

**Issue by ronzeidman** [Microsoft/TypeScript#16408] opened 2017-06-09 18:10 UTC
**TypeScript Version:**  2.3.4

**Code**

```ts
// strictNull1.ts file
let x = true;
export const test = x
    ? { y: () => null }
    : null;

//strictNull2
import {test} from './strictNull1';
if (test) {
    test && test.y(); //<-- Object is possibly 'null' even though I checked!
}
```

**Expected behavior:**
No error

**Actual behavior:**
Object is possibly 'null'

**Comment by andy-ms** [comment] 2017-06-19 23:26
Duplicate of #12081

**Closed** 2017-07-10 16:18 UTC
Labels: Bug, Duplicate, Fixed
