### ISSUE TITLE
Misleading type widening in error message

### ISSUE THREAD

**Issue by Cgg** [microsoft/TypeScript#31890] opened 2019-06-13 14:09 UTC
**TypeScript Version:**  3.6.0-dev.20190613, 3.5.1, playground version

**Search Terms:**
type widening
union
literal

**Code**

```ts
function pluck<T extends object, K extends keyof T>(
  target: T,
  keys: Array<K>
): Array<T[K]> {
  return keys.map(k => target[k]);
}

const a = { abc: 42, def: "42" };

pluck(a, ["abc", "edf"]);
//         ^^^    ^^^
// error: Type 'string' is not assignable to type '"abc" | "def"'
pluck(a, ["abc", "def"]);
// fine

type T = { abc: number; def: string };
type K = keyof T;

const b: K[] = ["abc", "edf"];
//                      ^^^
// error: Type '"edf"' is not assignable to type '"abc" | "def"'
```

**Expected behavior:**
The error highlight and message are consistent between `pluck(a, ["abc", "edf"]);` and `const b: K[] = ["abc", "edf"];`

**Actual behavior:**
For `pluck(a, ["abc", "edf"]);` every item of the array is highlight as erroneous, even correct ones; and the error message is misleading.

**Playground Link:** [link](https://www.typescriptlang.org/play/index.html#src=function%20pluck%3CT%20extends%20object%2C%20K%20extends%20keyof%20T%3E(%0D%0A%20%20target%3A%20T%2C%0D%0A%20%20keys%3A%20Array%3CK%3E%0D%0A)%3A%20Array%3CT%5BK%5D%3E%20%7B%0D%0A%20%20return%20keys.map(k%20%3D%3E%20target%5Bk%5D)%3B%0D%0A%7D%0D%0A%0D%0Aconst%20a%20%3D%20%7B%20abc%3A%2042%2C%20def%3A%20%2242%22%20%7D%3B%0D%0A%0D%0Apluck(a%2C%20%5B%22abc%22%2C%20%22edf%22%5D)%3B%0D%0Apluck(a%2C%20%5B%22abc%22%2C%20%22def%22%5D)%3B%0D%0A%0D%0Atype%20T%20%3D%20%7B%20abc%3A%20number%3B%20def%3A%20string%20%7D%3B%0D%0Atype%20K%20%3D%20keyof%20T%3B%0D%0A%0D%0Aconst%20b%3A%20K%5B%5D%20%3D%20%5B%22abc%22%2C%20%22edf%22%5D%3B%0D%0A)

**Related Issues:** 
#25855 might be?

**Comment by mheiber** [comment] 2019-06-18 13:47
Related: adding 'as const' to the end of the first array with a typo also generates a weird/misleading error message:

```ts
const a = { abc: 42, def: "42" };

pluck(a, ["abc", "edf"] as const);
//         ^^^    ^^^
```

Argument of type 'readonly ["abc", "edf"]' is not assignable to parameter of type '("abc" | "def")[]'.
  Type 'readonly ["abc", "edf"]' is missing the following properties from type '("abc" | "def")[]': pop, push, reverse, shift, and 6 more.

**Comment by RyanCavanaugh** [comment] 2019-06-25 03:16
> also generates a weird/misleading error message:

This one is more correct but still could be better - we should special-case assigning a readonly array to a mutable array, and either tell you that the problem is only the readonlyness, or complain that it's not mutable *and* has the wrong element type

**Comment by mheiber** [comment] 2019-09-20 09:53
Is this issue appropriate for a "Help Wanted" label?

**Comment by mkubilayk** [comment] 2022-06-15 12:01
Looks like this is fixed in recent versions. 

```ts
pluck(a, ["abc", "edf"]);
//                ^^^
// Type '"edf"' is not assignable to type '"abc" | "def"'.(2322)
```

**Comment by RyanCavanaugh** [comment] 2022-06-15 19:37
Thanks!

**Closed by RyanCavanaugh** 2022-06-15 19:37 UTC
Labels: Bug
