### ISSUE TITLE
Spread operator should work with generic types

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#13557] opened 2017-01-18 06:24 UTC
**TypeScript Version:**  master

**Code**

```ts
function f<a extends Object>() {
	return {...<a>{}};
}
function g<a extends object>() {
	return {...<a>{}};
}

```

**Expected behavior:**

ok

**Actual behavior:**

index.ts(2,10): error TS2698: Spread types may only be created from object types.
index.ts(5,10): error TS2698: Spread types may only be created from object types.

**Comment by HerringtonDarkholme** [comment] 2017-01-18 10:45
Another example, it's quite hard for TypeScript to prove a type constraint is spreadable given structural typing

```ts
class NonPrimitive {
    private cannotBePrimitiveBrand
}
function t<T extends NonPrimitive>(a: T, b: NonPrimitive) {
    var c = { ...a }
    var d = { ...b }
}
```

https://github.com/Microsoft/TypeScript/issues/2103#issuecomment-219553288

**Comment by billba** [comment] 2017-04-24 14:31
Another example: 

```typescript
interface Foo {
    foo: string;
}

const addBar = <F extends Foo>(input: F) => ({
    ... input,
    bar: 5
});
```

Throws `error TS2698: Spread types may only be created from object types.` on `...input,`

**Comment by mhegazy** [comment] 2017-04-24 17:17
Duplicate of https://github.com/Microsoft/TypeScript/issues/10727. Fixed by https://github.com/Microsoft/TypeScript/pull/13288

**Closed by mhegazy** 2017-04-24 17:17 UTC

**Comment by billba** [comment] 2017-04-24 17:39
This is still happening in the current build.

**Comment by mhegazy** [comment] 2017-04-24 17:42
yes. #13288 is not merged yet. we do not have an ETA at the moment.

**Comment by billba** [comment] 2017-04-24 18:19
Aha, thanks.

**Comment by LKay** [comment] 2017-04-25 07:30
When it will be fixed finally? The problem persists and it's breaking code all over the place!

**Comment by massimonewsuk** [comment] 2018-05-03 10:43
Is there a milestone or version that we can expect this to be fixed in?

**Comment by nblavoie** [comment] 2018-05-12 13:16
Count me in !

**Comment by mcamou** [comment] 2018-07-23 13:14
Any news on when/whether #13288 will be merged? This bug has been open for over a year now.

**Comment by ivansky** [comment] 2018-08-23 12:32
@mhegazy 
It's not a duplicate! I am interested in fixing too. 
Could you remove label and reopen the issue?

**Comment by RyanCavanaugh** [comment] 2018-08-24 22:51
Please read https://github.com/Microsoft/TypeScript/pull/13288#issuecomment-412230721
