### ISSUE TITLE
Feature request: autocompletion for property names that are not identifiers (e.g. "font-family")

### ISSUE THREAD

**Issue by duanyao** [Microsoft/TypeScript#5335] opened 2015-10-20 05:30 UTC
Currently TS tools can't autocomplete property names that are not identifiers. e.g.:
```JS
interface Style {
	'font-family'?: string;
}
```
There is no autocomplete for the following input:
```
var style: Style = { 'fo // no autocomplete
style[ // no autocomplete
style. // no autocomplete
```
I think maybe TS can do better here: show a list of all properties, after user has selected one, quote it and use brackets if neccesary.

**Comment by DanielRosenwasser** [comment] 2015-10-20 07:07
hey @duanyao, thanks for filing. I think this is a duplicate of #606.

**Closed** 2015-10-20 07:07 UTC
Labels: Duplicate
