### ISSUE TITLE
Incorrect narrowing to `never`

### ISSUE THREAD

**Issue by mheiber** [microsoft/TypeScript#55977] opened 2023-10-04 11:32 UTC
### 🔎 Search Terms

"narrow", "never", "refine never", "property does not exist"

### 🕗 Version & Regression Information

Reproduced in playground, unexpected behavior.
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about: refinement, narrowing

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/FDCGGcE8DsGMAIBmBXOAXAlge2krWAKASgC54AFAJywFsNwBTAHmmRoCMHL4AfeVgDYCAfPADewePAEM08AB5lBA3uMQYGAgCZK2nSgF94AXn7IhAbknxQAd1AY50BrYrU6jAgUoNwWAQBuDEQmohJSUvImahraZADMBtZSPn6BDASoWgzqzlpE1gZEVimyyJS48gD8AHTqmlpWScCI+MQ1aAAWDNAEsDhpDDUCWADmxfAA9JPw8UA

### 💻 Code

```ts
async function foo(): Promise<number | null> {
  let x: null | {field: number} = null;
  await new Promise((resolve) => {
    x = {field: 3}
    resolve(undefined)
  });
  // TS Error: Property 'field' does not exist on type 'never'.(2339)
  return x?.field;
}

foo().then(console.log); // 3


### 🙁 Actual behavior

Error:

```
  // TS Error: Property 'field' does not exist on type 'never'.(2339)
```

On this line:

```
  return x?.field;
```

### 🙂 Expected behavior

No error: the code is correct and prints `3`.

TS seems to be refining `null | {field: int}` to `null` and inferring `never` for `(null).field`.

Some options:
- Don't refine to `null` at all: accept the type annotation indicates user intent that the type is `null | {field: int}`. This is sound
- OR: don't refine variables that are closed-over. TS doesn't know when the callback will be run, so imo should be conservative about what happens to the closed-over `let`s

### Additional information about the issue

_No response_

**Comment by fatcerberus** [comment] 2023-10-04 11:34
Yet another duplicate of #9998

**Closed** 2023-10-04 11:38 UTC

**Comment by mheiber** [comment] 2023-10-04 11:41
fwiw I this behavior really messes with our code: it forces use of `any` or `ts-ignore` and confuses linting with type-checking. Preventing runtime errors or abstraction-breaking is essential: catching smells is not as important, but the "trade-offs" issue seems to treat these as of equal importance.

**Comment by IllusionMH** [comment] 2023-10-04 12:03
To avoid narrowing on initial assignment you can force union as	`let x = {field: 3} as (null | {field: number});` and then TS would even catch "bug" in return declaration
