### ISSUE TITLE
 .map() .reduce() .filter() methods fail with "This expression is not callable." error on valid array with union type

### ISSUE THREAD

**Issue by IvanKalinin** [microsoft/TypeScript#36390] opened 2020-01-24 00:38 UTC
**TypeScript Version**: any

**Code**: 
```ts

const arr: number[] | string[] = [];  // Works with Array<number | string>
const arr1: number[]  = [];
const arr2:  string[] = [];

arr.map((a: number | string, index: number) => { 
    return index
})

arr.reduce((acc: Array<string>, a: number | string, index: number) => { 
    return []
}, [])

arr.forEach((a: number | string, index: number) => { 
    return index
})

arr1.map((a: number, index: number) => { 
    return index
})

arr1.reduce((acc: number[], a: number, index: number) => { 
    return [a]
}, [])

arr1.forEach((a: number, index: number) => { 
    return index
})
arr2.map((a:  string, index: number) => { 
    return index
})

arr2.reduce((acc: string[], a: string, index: number) => { 
    return []
}, [])

arr2.forEach((a: string, index: number) => { 
    return index
})

```

**Expected behavior:** TS should let me iterate through array (I tell it the type is either array of numbers OR array of strings (not an array of mixed types). In any case the variable is an array and those methods should be callable.

**Actual behavior:** TS throws error "This expression is not callable."

**Comment by DanielRosenwasser** [comment] 2020-01-24 01:01
I think this is a duplicate of #7294

**Comment by jcalz** [comment] 2020-01-24 01:03
Duplicate of #7294 (see [comment](https://github.com/Microsoft/TypeScript/issues/7294#issuecomment-465801362)).  Related to #29011.  

Mentioned in documentation as [caveats for improved behavior for calling union types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-3.html#caveats):

> This new behavior only kicks in when at most one type in the union has multiple overloads, and at most one type in the union has a generic signature. That means methods on `number[] | string[]` like `map` (which is generic) still won’t be callable.

**Comment by jcjolley** [comment] 2020-02-12 15:35
Is this really a duplicate?  The 'duplicate' issue is marked as closed, but this issue still exists.

**Comment by dragomirtitian** [comment] 2020-02-12 18:05
The reason stated by @weswigham for not unifying for generic signatures with multiple signatures is that:

>Well, it's because we don't really know if the generics are the same (and so because of that we'd opt to make the parameter type T & T' instead and combine the type parameter lists to <T, T'>), so we opt to not allow the call.

But for function signatures originating from *the same declaration* we can be sure that we are talking about the same overload signatures in the same order and with the same generic parameters. As long as the generics don't have constraints, unifying the signatures should be safe IMO.

I think that unifying for this case would satisfy a lot of use cases. `Array`  and `Promise` would benefit from this and those are the usual place people run into this limitation.

**Comment by weswigham** [comment] 2020-02-12 18:20
Yeah, I have a change around here somewhere that allows it for exactly that situation *rummages through bin of old PRs*

**Comment by dragomirtitian** [comment] 2020-02-12 18:26
@weswigham What was wrong with it? Why did it get stuck ? Can we revive it :D ?

**Comment by weswigham** [comment] 2020-02-12 19:09
#31023 contains the relevant code. It's a bit old, and some parts of it are probably no longer needed thanks to some other signature resolution changes we made.

**Comment by dragomirtitian** [comment] 2020-02-12 19:33
Cool! So is this planned for a release in the future I'm guessing? I wanted to have a look at this over the weekend but glad to see it already there and we will get eventually :)

**Comment by Geo1088** [comment] 2020-02-26 21:57
Looks like my issue #36307 talks about pretty much the same behavior, linking for discoverability. Glad to see there's been some movement!

**Comment by sazzy4o** [comment] 2020-06-10 04:49
Until this gets fix you can do something like:
```
const arr: number[] | string[] = [];
// Add as any[]
(arr as any[]).map((a: number | string, index: number) => { 
    return index
});
```

**Comment by aksdevac** [comment] 2020-07-06 09:40
I got similar error while calling map on `Dictionary<CustomType[]>`, hope this gets fixed soon, currently used lodash-es's map to avoid this.

**Closed** 2020-12-16 21:17 UTC
Labels: Experience Enhancement, Fix Available, Rescheduled, Suggestion

**Comment by jcalz** [comment] 2021-05-12 20:40
This issue is closed, but the `reduce()` example persists:

```ts
const arr: number[] | string[] = [];

arr.reduce((acc: Array<string>, a: number | string, index: number) => {
  return []
}, [])

/* This expression is not callable.
  Each member of the union type '...' has signatures,
  but none of those signatures are compatible with each other. */
```

[Playground link](https://www.typescriptlang.org/play?ts=4.2.3#code/MYewdgzgLgBAhgJwQLhmArgWwEYFMEDaAujAD4zQICWYA5sTALwzEDcAsAFBeIIB0CXABN0wXAApxcYMFQBBJHACeAHko1aAPgA08VBhz4yFKNTq6aQ3AA99WPAgCUTTTADeXGDEFR0CMCxEXAC+usSOXFwA9ABUMAAqABZUEDA2AA6CEBBU4DApaCCwwHAANqVw2KW4fJ4wAKLSiTCYuIYIMCAAZjBQibgw6GC5AVBK6QMA5HwzkzCJcKk5tGBwvlnaddjosGDgA929iSAQA8ur67ipiAOgmOlrVFUDAO5UfWlNnX34fDAxUSAA)

**Comment by ialexryan** [comment] 2021-06-01 22:42
I'm super excited about the improvements in #31023! But it doesn't seem to have completely resolved the issues with calling array methods on unions of arrays.

I tested a few common array methods and found the following results:
- .map() [works](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdHTgABwtgSDpkAF4APlIw33JvZmQgA)
- .forEach() [works](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdDAB7KABRRAALC2BIOmQAXgA+Umjfcm9mZCA)
- .includes() [works](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdKAQAGxoyCB4LHDVkAEYAGg4uKgAiBiT43SxkuCTRb2ZkIA)
- .indexOf() [works](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdKDIIAA8AeRgLHDVkAEYAGg4uKgAiBiT43SxkuCTRb2ZkIA)
- .findIndex() [works](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdJxAyAElAiAAPC2BIOmQAXgA+Umjfcm9mZCA)
- .some() [works](https://www.typescriptlang.org/play?ssl=11&ssc=25&pln=11&pc=29#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdDwB7OggLYEg6ZABeAD5ScN9yb2ZkIA)
- .every() [does not work](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdBAA3aABPC2BIOmQAXgA+Ugjfcm9mZCA)
- .filter() [does not work](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdJwAbaQtgSDpkAF4APlIw33JvZmQgA)
- .find() [does not work](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdJxAyC2BIOmQAXgA+UlDfcm9mZCA)
- .reduce() known not working ([issue](https://github.com/microsoft/TypeScript/issues/44063))

I've created a [new issue](https://github.com/microsoft/TypeScript/issues/44373) to track the remaining functionality.

**Comment by Wharley01** [comment] 2021-09-26 12:47
is this getting fixed anytime soon ?

**Comment by zoeytruong** [comment] 2021-11-17 20:45
> I'm super excited about the improvements in #31023! But it doesn't seem to have completely resolved the issues with calling array methods on unions of arrays.
> 
> I tested a few common array methods and found the following results:
> 
> * .map() [works](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdHTgABwtgSDpkAF4APlIw33JvZmQgA)
> * .forEach() [works](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdDAB7KABRRAALC2BIOmQAXgA+Umjfcm9mZCA)
> * .includes() [works](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdKAQAGxoyCB4LHDVkAEYAGg4uKgAiBiT43SxkuCTRb2ZkIA)
> * .indexOf() [works](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdKDIIAA8AeRgLHDVkAEYAGg4uKgAiBiT43SxkuCTRb2ZkIA)
> * .findIndex() [works](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdJxAyAElAiAAPC2BIOmQAXgA+Umjfcm9mZCA)
> * .some() [works](https://www.typescriptlang.org/play?ssl=11&ssc=25&pln=11&pc=29#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdDwB7OggLYEg6ZABeAD5ScN9yb2ZkIA)
> * .every() [does not work](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdBAA3aABPC2BIOmQAXgA+Ugjfcm9mZCA)
> * .filter() [does not work](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdJwAbaQtgSDpkAF4APlIw33JvZmQgA)
> * .find() [does not work](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdJxAyC2BIOmQAXgA+UlDfcm9mZCA)
> * .reduce() known not working ([issue](https://github.com/microsoft/TypeScript/issues/44063))
> 
> I've created a [new issue](https://github.com/microsoft/TypeScript/issues/44373) to track the remaining functionality.
@ialexryan  What typescript version does this fix go out?

**Comment by shamilovtim** [comment] 2021-12-29 22:06
We're on the latest Typescript and bumped into this. Do you know when it's going out? @ialexryan

**Comment by ivan-oj** [comment] 2022-01-21 09:39
I just bumped into the same issue

**Comment by mikkelwf** [comment] 2023-02-11 13:34
How is this issue closed? 
.filter() and .find() is still not working as of 4.9.5..

**Comment by jcalz** [comment] 2023-02-11 13:40
I think #44373 is the open issue about this

**Comment by mikkelwf** [comment] 2023-02-11 13:43
Thanks, didn't see that.. :)
