### ISSUE TITLE
Workspace diagnostic

### ISSUE THREAD

**Issue by timsofteng** [microsoft/TypeScript#45620] opened 2021-08-29 17:09 UTC
Hello. Is it possible to add workspace diagnostic for whole project into tsserver?

**Comment by DanielRosenwasser** [comment] 2021-08-30 17:46
Please follow our issue template format and search the issue tracker for duplicates.

Duplicate of https://github.com/microsoft/TypeScript/issues/36664

**Closed** 2021-09-01 18:00 UTC
Labels: Duplicate
