### ISSUE TITLE
Strange tsc behavior with if and conditional operator

### ISSUE THREAD

**Issue by azhoshkin** [Microsoft/TypeScript#11443] opened 2016-10-07 12:21 UTC
**TypeScript Version:**  2.0.3

**Code**

```ts
let e1 = 0, e2 = 0, e3 = 0, e4 = 0;
if (e1 < e2) {
    e1 = (e2 > (100 - e2)) ? 100 - e3 : e4;
}
```

**Expected behavior:**
Just work.
**Actual behavior:** 
Strange error in if statment (Cannot invoke an expression whose type lacks a call signature.).

Reproduces on https://www.typescriptlang.org/play/index.html

the same code but with `more than` in `if` works:
```ts
let e1 = 0, e2 = 0, e3 = 0, e4 = 0;
if (e1 > e2) {
    e1 = (e2 > (100 - e2)) ? 100 - e3 : e4;
}
```
the same code but without brackets works
```ts
let e1 = 0, e2 = 0, e3 = 0, e4 = 0;
if (e1 < e2) {
    e1 = e2 > 100 - e2 ? 100 - e3 : e4;
}
```

**Comment by yortus** [comment] 2016-10-07 12:45
I can repro this in the playground (strange indeed) but not in the latest nightly (`2.1.0-dev.20161006`) so it might be fixed already.

**Comment by RyanCavanaugh** [comment] 2016-10-07 21:36
The problem is that we're somehow getting very confused and trying to parse out a generic:
```ts
let a;
if (1 < 3) a = 0 > (1);
//    |----------|
```
Does appear to have been fixed in master

**Closed by RyanCavanaugh** 2016-10-07 21:36 UTC
Labels: Bug, Fixed
