### ISSUE TITLE
No error when passing readonly object in mutation function

### ISSUE THREAD

**Issue by fixiabis** [microsoft/TypeScript#45619] opened 2021-08-29 01:02 UTC
# Bug Report

### 🔎 Search Terms

function readonly parameter bug

### 🕗 Version & Regression Information

Tried 3.x and latest version in playground

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.2#code/JYOwLgpgTgZghgYwgAgCoQM5gPICMBWECYyA3gFDLIBucANgK4QBcyIDAtrtOQL7nkYDEMWAB7EMkhYAShDgATCXQCeACjis5i5SoA86LHkLEAfAEoylGnCjJgHDgzBxcdCAEFkAXmRwA3Na0dk4ubp4+ZMgAdLFwyLyBVKGu7h7RtIwovgBM-sgA9AXIAO5iUADWGAA0UgAWcGAA5BjIEAAeAA5EkArWKZAeainhHub5RaXlVbVgDc2tHd3EEH1UDiNpGfRMkXmFxdBQ5bPzLW1dPav9zo2eahu3o+MHU5U19Y3nIGIkS1cKZAAQhBfAEQhEYHEkgG900aEwOAIPUsFCocG2WUiAGZAvwgA)

### 💻 Code

```ts
interface TestObject {
  value: number
}

function testMutation(a: Readonly<TestObject>) {
  var immutableA = a;
  var mutableA = { ...a };
  mutableA.value = 2; // works, that's expected
  mutateA(mutableA); // works, that's expected
  immutableA.value = 2; // error, that's expected
  mutateA(immutableA); // works, that's not expected !!!
}

function mutateA(a: TestObject) {
  a.value = 3;
}
```

**Comment by MartinJohns** [comment] 2021-08-29 04:26
Duplicate of #13347.

**Closed** 2021-09-02 18:00 UTC
Labels: Duplicate
