### ISSUE TITLE
Locals named `exports` create incorrect down-level module emit

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#39822] opened 2020-07-29 22:48 UTC
Found by @charsleya on https://github.com/microsoft/tslib/issues/120

```ts
export var foo = () => {};

function f(exports: number) {
    foo();
}
```

**Expected**

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.foo = void 0;
exports.foo = () => {
};
function f(exports_1) {
    exports_1.foo();
}
```

or

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var exports_1 = exports;
exports_1.foo = void 0;
exports_1.foo = () => {
};
function f(exports) {
    exports.foo();
}
```

**Actual**

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.foo = void 0;
exports.foo = () => {
};
function f(exports) {
    exports.foo();
}
```

**Comment by a-tarasyuk** [comment] 2020-08-08 08:12
Does it seem the expected result should be like so, or am I wrong? @DanielRosenwasser 

```ts
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.foo = void 0;
exports.foo = () => {
};
function f(exports_1) {
    exports.foo();
}
```

or 

```ts
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var exports_1 = exports;
exports_1.foo = void 0;
exports_1.foo = () => {
};
function f(exports) {
    exports_1.foo();
}
```

**Comment by a-tarasyuk** [comment] 2020-08-09 19:20
The following example produces an incorrect result too

```ts
export const foo = () => {};

function f1() {
    const exports: any = 1;
    foo();
    return exports;
}
```

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.foo = void 0;
exports.foo = () => { };
function f1() {
    const exports = 1;
    exports.foo(); // Error
    return exports;
}
 
```

**Comment by a-tarasyuk** [comment] 2020-10-10 20:46
Additional examples causing the error

```ts
export const foo = () => {};
function f1() {
    const exports: any = 1;
    foo();
    return exports;
}

// .js 

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.foo = void 0;
exports.foo = () => { };
function f1() {
    const exports = 1;
    exports.foo();
    return exports;
}
```
[Playground](https://www.typescriptlang.org/play?module=1#code/KYDwDg9gTgLgBAYwgOwM7wGYQnAvHACgEo8A+OAbwF8BuAKDowFdkEYBLFODARmMrpwhiFOjihIsVAC44AQ2QBPPHB71h3bMXXCowGEyjJx4aDFT0qQA)

---

```ts
export const foo = () => {};
function f1({ exports }: any) {
    foo();
}

// .js

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.foo = void 0;
exports.foo = () => { };
function f1({ exports }) {
    exports.foo();
}
```

[Playground](https://www.typescriptlang.org/play?module=1#code/KYDwDg9gTgLgBAYwgOwM7wGYQnAvHACgEo8A+OAbwF8BuAKAwFdkEYBLFODARgIrlCRYqOFQBccAIbIAniQp04SrtmL0qQA)

---

```ts
export const foo = () => {};
function f1([exports]: any) {
    foo();
}

// .js

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.foo = void 0;
exports.foo = () => { };
function f1([exports]) {
    exports.foo();
} 
```

[Playground](https://www.typescriptlang.org/play?module=1#code/KYDwDg9gTgLgBAYwgOwM7wGYQnAvHACgEo8A+OAbwF8BuAKAwFdkEYBLFODARgIG1QkWKgC6ALjgBDZAE8SFOnCVdsxelSA)

--- 

BTW, At the top level, the ʻexports` identifier is forbidden

```ts
const exports = 1;
      ^^^^^^ - Duplicate identifier 'exports'. Compiler reserves name 'exports' in top level scope of a module.(2441)
export default exports;
```

--- 

Not sure what is the best solution for this issue. Is renaming the variables/binding/parameters an acceptable solution?

/cc @DanielRosenwasser @rbuckton

**Comment by a-tarasyuk** [comment] 2020-10-15 13:51
Additional examples causing the error

```ts
export const foo = () => {};
function f1() {
    const exports: any = 1;
    foo();
    return exports;
}

// .js 

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.foo = void 0;
exports.foo = () => { };
function f1() {
    const exports = 1;
    exports.foo();
    return exports;
}
```
[Playground](https://www.typescriptlang.org/play?module=1#code/KYDwDg9gTgLgBAYwgOwM7wGYQnAvHACgEo8A+OAbwF8BuAKDowFdkEYBLFODARmMrpwhiFOjihIsVAC44AQ2QBPPHB71h3bMXXCowGEyjJx4aDFT0qQA)

---

```ts
export const foo = () => {};
function f1({ exports }: any) {
    foo();
}

// .js

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.foo = void 0;
exports.foo = () => { };
function f1({ exports }) {
    exports.foo();
}
```

[Playground](https://www.typescriptlang.org/play?module=1#code/KYDwDg9gTgLgBAYwgOwM7wGYQnAvHACgEo8A+OAbwF8BuAKAwFdkEYBLFODARgIrlCRYqOFQBccAIbIAniQp04SrtmL0qQA)

---

```ts
export const foo = () => {};
function f1([exports]: any) {
    foo();
}

// .js

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.foo = void 0;
exports.foo = () => { };
function f1([exports]) {
    exports.foo();
} 
```

[Playground](https://www.typescriptlang.org/play?module=1#code/KYDwDg9gTgLgBAYwgOwM7wGYQnAvHACgEo8A+OAbwF8BuAKAwFdkEYBLFODARgIG1QkWKgC6ALjgBDZAE8SFOnCVdsxelSA)

--- 

BTW, At the top level, the ʻexports` identifier is forbidden

```ts
const exports = 1;
      ^^^^^^ - Duplicate identifier 'exports'. Compiler reserves name 'exports' in top level scope of a module. (2441)
export default exports;
```

--- 

Not sure what is the best solution for this issue. @DanielRosenwasser Is renaming the variables/binding/parameters an acceptable solution?

/cc  @rbuckton

**Comment by rbuckton** [comment] 2020-12-17 00:40
Duplicate of #33043

**Closed by rbuckton** 2020-12-17 00:40 UTC
Labels: Bug, Domain: JS Emit, Domain: Transforms, Rescheduled
