### ISSUE TITLE
TS 1.5 formatter – arrow function body should be indented

### ISSUE THREAD

**Issue by ArtemAvramenko** [Microsoft/TypeScript#3074] opened 2015-05-07 19:45 UTC
No matter in which line is dot, code is dislocated after formatting:
![format_bug](https://cloud.githubusercontent.com/assets/11413326/7524334/f7c87c24-f509-11e4-8534-c832cef9cb96.png)

My environment:
Microsoft Visual Studio Community 2013 (12.0.31101.00 Update 4)
TypeScript 1.5.40427.1

**Comment by mhegazy** [comment] 2015-05-07 20:08
looks like a duplicate of #1917. should be fixed in next release.

**Closed** 2015-05-07 20:08 UTC
Labels: Duplicate
