### ISSUE TITLE
Don't emit 'variable x is used before being assigned', when the variable is assigned in every possible case of a switch statement.

### ISSUE THREAD

**Issue by evert** [microsoft/TypeScript#34497] opened 2019-10-15 19:49 UTC
## Search Terms

* `used before assigned` `switch`

## Suggestion

The following source returns `Variable 'hi' is used before being assigned.`:

```typescript
type Foo = 'a' | 'b';

function test(foo: Foo) {
    let hi: string;
    switch (foo) {
        case 'a':
            hi = 'hello';
            break;
        case 'b':
            hi = 'world';
            break;
    }
    console.log(hi);
}
```

It seems like every branch assigns the variable, but maybe I there's a secret branch I can't see.

## Use Cases

I'm forced to add a `!` or a `default`. Neither are really optimal. If `type Foo` changes later to include a third case, at that point I would like typescript to complain about this error. Effectively I would like to be statically guarded to the Foo type changing.

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jack-williams** [comment] 2019-10-15 19:56
Duplicate of #18362 or #30000?

**Comment by evert** [comment] 2019-10-15 20:03
Those two seem similar, but they both deal with `enum`. I don't know TS enough to say if it's the exact same problem.

**Comment by j-oliveras** [comment] 2019-10-16 07:21
This works with version [3.7-beta](https://www.typescriptlang.org/play/?ts=3.7-Beta#code/C4TwDgpgBAYg9nKBeKByAhqqAfNAjVAbgFgAoMgMwFcA7AY2AEs4apgIBnYACgoQC5YCAJRQA3mShSoAGwjAoAC0aCuAJ0Y0A5iVLSoHAO6NgdRVF4jxk-dLroO0DKn43bt5cjSKIMmXCI3d2k8NQh0AGtdYKh7R3wXIJjPFFRDODUZABNAvRiQsMjo6QBfILoWDjg5ADp-LW5lYV0y0iA).

**Comment by jack-williams** [comment] 2019-10-16 09:56
Good spot @j-oliveras 

@RyanCavanaugh I added fixed labels to the associated issues I posted above --- mainly because one was locked and I could only label it. Just letting you know so you can amend my labels.

**Comment by evert** [comment] 2019-10-16 13:19
Wow awesome! excellent news

**Closed** 2019-10-18 18:00 UTC
Labels: Duplicate, Fixed
