### ISSUE TITLE
Inference is broken on intersection type utilizing polymorphic `this`

### ISSUE THREAD

**Issue by 0x706b** [microsoft/TypeScript#53970] opened 2023-04-22 21:56 UTC
# Bug Report

### 🔎 Search Terms

inference, intersection, polymorphic this, deferred index access

### 🕗 Version & Regression Information

- This changed between versions 5.1.0-dev.20230313 and 5.1.0-dev.20230315

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230422&ssl=34&ssc=1&pln=1&pc=1#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgFQE8xgAZTAWwCMATTOAbwCg44phMaIkAbQuAIIAuOAFckAayQQA7kiYBfJk1CRYiFGiy4CxYAGEemAM7GAPADE4oVEhrHdJctToA+RizYcuvfgH0LEQtFZVVoeBg9QTAwPktrEFt7RzJKWkwAGkF3AF44KxtgOwcGL05uPjhIkhFxKVkkOCVWAH44AAorADJGMp9K4UEmgEoAbQByauBxgF1PEVL2ct98oKyl-v5BgSbQ8HCNVAwcPHwzAXdmVgA3TB5RYBEBEJV99WQj7VOiJzS6BKSDh+qRc9CufQq-CmIjOMAAFghjKMAEQCZEzVwvMLqGjAbBGdhwbDcYzwCiYMAieKFYopZzpVydGF6QwmcwWVzDOA5dznLIAIUZmCeMTiFiyFyy6BE7WFgi5PLg-IV7gEosIlgFmKYuPxmEJxKQpKqLKMpmZJFZpjM+GB9Lcyl1BLwhuNcrOSFE1DQ2vJYHaUytxmGTAA9KGCABlOAAVgAdAAGOMAFhErHTGYzfKVQph51cUplcoEKqVpbOgrDEfw0fjAEZEwBaXHXOMAJgTbYAzAnk2221SBFrZTLbXp7fQeotvJDBE8ANwjFFTdGFjrF0vK7nudpj36guBTiErQb8xcKMbIldzJh+gOmtnDWVZdp+UtvzyZr-p8NwAB6UaxomKYaOgaAOJ63pQJ+35fr+rA1kBDYJs2wCth23a9v2oHgWIkjSHITBAA)

### 💻 Code

```ts
export interface TypeLambda {
  readonly A: unknown
}

export interface TypeClass<F extends TypeLambda> {
  readonly _F: F
}

export type Apply<F extends TypeLambda, A> = F extends { readonly type: unknown }
  ? (F & { readonly A: A })['type']
  : { readonly F: F, readonly A: A }

export interface T<A> {
  value: A
}

export interface TTypeLambda extends TypeLambda {
  readonly type: T<this["A"]>
}

export declare const map: <F extends TypeLambda>(F: TypeClass<F>) => <A, B>(a: Apply<F, A>, f: (a: A) => B) => Apply<F, B>

declare const typeClass: TypeClass<TTypeLambda>

declare const a: T<number>

map(typeClass)
// TS 5.0.4:              <A, B>(a: T<A>, f: (a: A) => B) => T<B>
// TS 5.1.0-dev.20230422: <A, B>(a: (TTypeLambda & { readonly A: A; })["type"], f: (a: A) => B) => (TTypeLambda & { readonly A: B; })["type"]

map(typeClass)(a, (_) => _)
                // ^ TS 5.0.4 infers number
                //   TS 5.1.0-dev.20230422 infers unknown

```

### 🙁 Actual behavior

Each version including and after 5.1.0-dev.20230315 defers the index access in the `Apply` type and doesn't allow inference to continue.

### 🙂 Expected behavior

Inference should continue to work in this case.

After a bit of research, I think that #53098 is the PR that introduced this change.

**Comment by mikearnaldi** [comment] 2023-04-23 12:10
This currently breaks the encoding used in `@effect/*` for HKTs and probably a few other libraries that rely on the same pattern (hotscript, storybook, come to mind)

**Comment by ecyrbe** [comment] 2023-04-24 17:27
Same here, zodios is using this pattern to enable policy based interfaces.

**Comment by ethanresnick** [comment] 2023-05-02 05:54
Seems like those packages should be added to the RWC test suite maybe, or snippets of them added to the main compiler tests

**Comment by jakebailey** [comment] 2023-05-02 05:56
Feel free to send a PR: https://github.com/microsoft/TypeScript-error-deltas

See userTests.

**Comment by ahejlsberg** [comment] 2023-05-03 14:55
I can confirm that the change in behavior is caused by #53098. We definitely want the deferred resolution implemented by that PR. However, it means that types like `(TTypeLambda & { readonly A: A; })["type"]` aren't resolved until a non-generic type is substituted for `A` through instantiation and, unfortunately, it also means that no inferences are made for `A` in the `map(typeClass)` invocation.

I think we can implement a targeted fix where, when inferring to types like `(TTypeLambda & { readonly A: A; })["type"]`, we force the resolution that previously happened and then infer to the result of that. This means the type of `map(typeClass)` will still change as in the example above, but inference will infer `number` in the final example.

**Comment by ecyrbe** [comment] 2023-05-04 12:13
I don't think we need to be this dramatic.
I see this as an opportunnity to clarify TS team stance on HKT.
Community started evolving libraries to take advantage of some HKT features.
As a TS team you have a playground feedback on how community took advantage of it.
Based on this feedback, you Can now either :
- officially support a new HKT syntax to address current use cases
- officially announce HKT to not be supported in either way going forward

Clarification is key for us to know if we can leverage some ts features for our use cases.

Again, thank you @ahejlsberg and all ts team for your wonderfull work

**Comment by ahejlsberg** [comment] 2023-05-04 14:48
I understand that esthetically `T<A>` looks nicer than `(TTypeLambda & { readonly A: A; })["type"]`, though the latter really is a more precise representation of what was requested in `Apply`. Are there other issues that are caused by this change and not fixed by #54112?

**Comment by mikearnaldi** [comment] 2023-05-04 14:58
We use:

```ts
export const f = map(typeClass)
```

and let it derive the type of `f`, with this change the typing of `f` will be impractical to use and understand from the reader's perspective, the problem seems to be related to potential reduction to `never` that this change aims to preserve, would there be a way of avoiding it in a class of cases where `never` is known to be impossible? I guess that would require being able to express "TypeLambda is an object without the field `A`" ? or maybe a way to force it to reduce the type?

In a general sense from a user perspective it isn't necessarily the case that something more precise is always better

**Comment by mikearnaldi** [comment] 2023-05-04 15:21
Actually I may have found a way:

```ts
export interface TypeClass<F> {
  readonly _F: F
}

export declare namespace TypeLambda {
  type _A<T> = "A" extends keyof T ? T["A"] : never
}

interface TypeLambda { type: unknown }

export type Apply<F, A> = F extends TypeLambda
  ? (F & {A: A})["type"]
  : { readonly F: F, readonly A: A }

export interface T<A> {
  value: A
}

export declare const map: <F>(F: TypeClass<F>) => <A, B>(a: Apply<F, A>, f: (a: A) => B) => Apply<F, B>

interface TTypeLambda {
  type: T<TypeLambda._A<this>>
}

declare const typeClass: TypeClass<TTypeLambda>

declare const a: T<number>

// const x: <A, B>(a: T<A>, f: (a: A) => B) => T<B>
const x = map(typeClass)

map(typeClass)(a, (_) => _)
```

Not sure if this if considered a bug with the new behaviour or this can be used

**Comment by ahejlsberg** [comment] 2023-05-04 23:59
It turns out there's a simple way to fix this issue and preserve our old behavior. See latest commits in #54112.

**Closed** 2023-05-20 13:36 UTC
Labels: Bug, Fix Available
