### ISSUE TITLE
`ThisType` cant work in the block scope of function

### ISSUE THREAD

**Issue by rudyxu1102** [microsoft/TypeScript#52849] opened 2023-02-19 11:49 UTC
# Bug Report

### 🔎 Search Terms
`ThisType`

### 🕗 Version & Regression Information

- This is a crash
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `ThisType`
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.5#code/GYVwdgxgLglg9mABAEwKbBmVBhOBbABwB4AhAQwCcAaRAETKjID4AKAWAChFE4DYEAzgC5EAb07duAI0ojy1CZOBw4IlgEpEAXiZ0GZRQF9EAMkQAVABYwB5gJ4FURUYhkU5lRIaad1HipygkPxIaBhYuIQsvCHCiGRgdpriXIgUqFAgFEgx8GACAHRunIacnAD05YjAZDAANqjInBCCUPFkZNoo6Jg4+AQsKdzKcBpiitwt+XANBXVwAOYsUNaFbuoTaRlZSEOSk3DgUCIrNkWUY5WIKxRwAO6IqBS3AancpamGVIpuY3vc6Uy2UQAHIAIwgozfDiGDYcCpVO5wCgAa2arVcUikXTCvUiAz2v2Sm0BO1BEKhihGf02UwEM1Qc0Wy1W5wocP2pOB-0kLSOJ1ZRMQVxgUBBAkQSNRmw+72hsM4QA)

### 💻 Code

```ts
function defineComp<Bar, Data>(
  options: {
    bar: Bar,
    foo: () => Data
  } & ThisType<{ bar: Bar }>
): Bar
function defineComp(options: any) {
  return options.bar
}

// failed
const aaa = defineComp({
  foo() {
    console.log(this.bar) // no error
    return {
      count: this.bar() // throw error
    }
  },
  bar() {
    return '1'
  },
})

// work
const bbb = defineComp({
  bar() {
    return '1'
  },
  foo() {
    console.log(this.bar)
    return {
      count: this.bar() // it's work
    }
  },
})
```

### 🙁 Actual behavior
TS error:  `(property) bar: unknown` in `aaa`

### 🙂 Expected behavior
no error

**Comment by MartinJohns** [comment] 2023-02-19 12:30
I believe this is essentially a duplicate of #45213.

When encountering the `this.bar()` call the compiler has no clue what `bar` is because it hasn't been defined yet.

**Closed** 2023-02-26 18:00 UTC
Labels: Duplicate
