### ISSUE TITLE
Can't transpile code residing on network share using node module resolution

### ISSUE THREAD

**Issue by ksj2209** [Microsoft/TypeScript#12126] opened 2016-11-09 14:03 UTC
I am experiencing problems when trying to build a TypeScript project which resides on one of our network shares. I am using Windows 7.

The problem only occurs when using node module resolution and seems to be related to the mapping of network drives to UNC paths.

Suppose I have the following setup:

A drive X: mapped to \\\\server\projects with a folder test containing my files.

**TypeScript Version:**  2.0.6

**Code**

```ts
// module.ts
export interface A {}

// index.ts
import { A } from './Module'

// tsconfig.json
{
 "compilerOptions": {
  "target": "es2015",
  "module": "commonjs"
 }
}

```

**Expected behavior:**
No errors.

**Actual behavior:** 
======== Resolving module './module' from 'X:/test/index.ts'. ========
Module resolution kind is not specified, using 'NodeJs'.
Loading module as file / folder, candidate module location 'X:/test/module'.
File 'X:/test/module.ts' exist - use it as a name resolution result.
Resolving real path for 'X:/test/module.ts', result 'UNC/server/projects/test/module.ts'
======== Module name './module' was successfully resolved to 'UNC/server/projects/test/module.ts''. ========
index.ts (1,24): error TS2307: Cannot find module './Module'.

**Comment by mhegazy** [comment] 2016-11-09 20:13
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/9552 and https://github.com/Microsoft/TypeScript/issues/11613. Should be fixed by https://github.com/Microsoft/TypeScript/pull/12020

**Closed** 2016-11-09 20:13 UTC
Labels: Duplicate
