### ISSUE TITLE
Compilation result is not being provided to Visual Studio app context

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#7146] opened 2016-02-19 01:08 UTC
Environment: Visual Studio 2015 Update 1, Windows 10 Insider Preview 14257, TS 1.8.0-beta

Repro:

1. Create a new project
2. Add a blank TypeScript file named `file.ts`
3. Add a reference to `file.js` in `default.htm` before `/js/default.js`

    ```typescript
    <link href="/css/default.css" rel="stylesheet" />
    <script src="file.js"></script>
    <script src="/js/default.js"></script>
    ```

4. Write `var homu = "homu"` on `file.ts`
5. Build and deploy the app by clicking "Local Machine"
6. It should launch with no error
7. Close the app
8. Click "Local Machine" again
9. Now it says `0x800a1391 - JavaScript runtime error: 'homu' is undefined`

**Comment by mhegazy** [comment] 2016-02-19 01:27
i think i am using a different template. but creating a new project form "TypeScript HTML Application" and adding a new file "file.ts" and following your steps, things seem to work.
if you can share a project, i would be happy to take a look.

**Comment by SaschaNaz** [comment] 2016-02-19 01:29
@mhegazy Ah, I created it using Templates->JavaScript->Blank App (Universal Windows). Can you try once again with it?

**Comment by SaschaNaz** [comment] 2016-02-19 02:11
I'm seeing file.js is correctly generated but somehow VS doesn't get them.

![image](https://cloud.githubusercontent.com/assets/3396686/13164559/87ea38f2-d6f9-11e5-9f59-f5038d2e6f0c.png)

**Comment by mhegazy** [comment] 2016-02-19 04:33
looks like we are not putting the output files in ContentFilesProjectOutputGroup as the windows app deployment expects them, so they are not deployed.
as a work around can you add the .js file in the project, and that will cause it to be deployed.

**Comment by SaschaNaz** [comment] 2016-02-22 15:43
I think this will be breaking bug as it worked before 1.8 beta.

**Comment by billti** [comment] 2016-02-22 16:24
@paulvanbrenk can you see if you can figure what is going on here? We might want to try and pull this in for Update2 of VS if it's a regression.

**Comment by spelltwister** [comment] 2016-04-04 14:28
This issue just appeared for me as well.  I re-imaged my laptop and installed fresh vs enterprise 2015 update 2 and now my app no longer builds.  Anything included via TypeScriptCompile is missing from the project.  It will build and run one time if I re-include the .ts files and delete all the .js files.  New projects do not provide Right-Click > Add > New Typescript file...  They do appear under New Javascript file... but do not compile except one time on build.  I'm starting to get some VMs going with different tool sets to see if it can add some light to where the problem is.

**Comment by spelltwister** [comment] 2016-04-04 14:38
@mhegazy In my tests, adding the js files works, but if you modify the ts file, the js file is not updated.  You have to delete all js files, build and run, stop running, and then include the generated js files again.

**Comment by spelltwister** [comment] 2016-04-04 14:59
Ok, so here are my results.  Both VMs are Azure default VMs.

VM 1:  Visual Studio Enterprise 2015 Update 1 with Universal Windows Tools and Azure SDK 2.8 on Windows 10 1511 Enterprise N (x64)

File > New Project > Installed > Templates > Other Languages > JavsScript > Windows > Universal > Blank App (Universal Windows)

Right Click the js folder and notice that New TypeScript File... is a context menu item.

![update1addtypescriptfile](https://cloud.githubusercontent.com/assets/4492581/14251962/4321be7a-fa53-11e5-8ca7-a2e1d11907d4.jpg)

Add the file.  Right click the project and select properties.  Notice that TypeScript Build is a tab.

![update1propertypage](https://cloud.githubusercontent.com/assets/4492581/14252022/89176808-fa53-11e5-9c9c-eb7c3df9bea3.jpg)

Save all.  Unload project and edit.  Notice that the tag is TypeScriptCompile and the file is visible in project.

![update1typescriptcompile](https://cloud.githubusercontent.com/assets/4492581/14252062/b29f0a0a-fa53-11e5-8c64-739ca863d703.jpg)

This project produces js files on save and runs fine.

VM 2:  Visual Studio Enterprise 2015 Update 2 with Universal Windows Tools and Azure SDK 2.9 on Windows 10 Enterprise N (x64)

Same steps, but ...

No New TypeScript file.. context menu.

![update2noaddtypescriptfile](https://cloud.githubusercontent.com/assets/4492581/14252167/1a814de0-fa54-11e5-9955-842db0d0e9d1.jpg)

No TypeScript Build tab on property page.

![update2propertypagenotypescript](https://cloud.githubusercontent.com/assets/4492581/14252182/286c3b9a-fa54-11e5-886a-2befefc96924.jpg)

No TypeScriptCompile tag.  In fact, changing to TypeScriptCompile causes item to not be included.

![update2contentinclude](https://cloud.githubusercontent.com/assets/4492581/14252200/38e4a4bc-fa54-11e5-9b2d-7fa5975d550d.jpg)

**Comment by mhegazy** [comment] 2016-04-06 00:02
@paulvanbrenk any ideas?

**Comment by paulvanbrenk** [comment] 2016-04-06 00:13
Setup issue? Can you collect logs on the 2 VM using http://aka.ms/vscollect and confirm there is no entry for TypeScript in Help -> About.

**Comment by grork** [comment] 2016-04-06 03:57
I can confirm this appears to be broken for .jsproj files -- I just setup a brand you machine w/ Update 2. and it's all gone south.

I can confirm that in my About Box, I *do* see TypeScript 1.8.29 installed.

It seems to be improved if I bring the items as <None> as well as TypeScriptCompile.

I couldn't attach the logs here -- they're too big, apparently -- so I've uploaded them here:
[http://codevoid.net/vslogs.zip](http://codevoid.net/vslogs.zip)

**Comment by paulvanbrenk** [comment] 2016-04-06 17:30
Thanks for getting the logs, it looks like TypeScript is installed correctly. Does it work as expected in an HTML Application with TypeScript (new Project, from the TypeScript node).

And are there any recent entries in the activity log?

`%appdata%\Microsoft\VisualStudio\14.0\ActivityLog.xml`

**Comment by grork** [comment] 2016-04-06 19:19
Yes, the HTML Application project type seems to show things correctly, and *seems* work. I didn't dig deeply, however.

I can craft a repro project if you're unable to repro w/ WWA proj.

On Apr 6, 2016, at 10:31, Paul van Brenk <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for getting the logs, it looks like TypeScript is installed correctly. Does it work as expected in an HTML Application with TypeScript (new Project, from the TypeScript node).

And are there any recent entries in the activity log?

%appdata%\Microsoft\VisualStudio\14.0\ActivityLog.xml

-

**Comment by spelltwister** [comment] 2016-04-07 13:26
The other projects work fine with typescript.  It's just uwp js apps that have this problem of the ones that I've tried.

**Comment by grork** [comment] 2016-05-16 05:44
Were you able to repro this? I noticed that it still repros even after the latest 1.3.2 tools update.

**Comment by paulvanbrenk** [comment] 2016-05-16 17:50
No, I haven't. Which tools were upgraded to 1.3.2 ? And which version of TypeScript shows in Help > About?

**Comment by grork** [comment] 2016-05-16 18:37
The Win10/UWP tools were upgraded to 1.3.2 -- unclear why. My Typescript Version is 1.8.31.0.

I'll try working on a repro project tonight.

**Comment by mhegazy** [comment] 2016-06-08 00:11
UWP support is tracked by https://github.com/Microsoft/TypeScript/issues/8950

**Comment by RyanCavanaugh** [comment] 2016-08-02 03:40
@paulvanbrenk can you track down a repro or close this?

**Comment by paulvanbrenk** [comment] 2016-08-12 21:22
@minestarks can you see if this repros with your latest changes?

**Comment by minestarks** [comment] 2016-08-12 21:42
There are 2 distinct issues in this thread
[One](https://github.com/Microsoft/TypeScript/issues/7146#issue-134743679) Refers to VS2015 Update 1 - I can't repro this, I believe it to be fixed. 

[Two](https://github.com/Microsoft/TypeScript/issues/7146#issuecomment-205321530) Only applies to VS 2015 Update 2 and beyond, there is a workaround which is documented in #8950.

**Closed** 2016-08-12 21:48 UTC
Labels: Bug, Visual Studio
