### ISSUE TITLE
Infer return type of a function with provided argument types

### ISSUE THREAD

**Issue by int0h** [Microsoft/TypeScript#26043] opened 2018-07-28 18:42 UTC
I'm trying to create something similar to native ReturnType type. In comparison to the later, it should also consider generic types of arguments.

I guess the idea will be clear from the code below.

If it can be done now - I'd be happy to receive some links. Otherways it'd be great to know if there are any plans to cover that behavior. In case it could be achieved by another not-implemented feature I'll be glad for the link to an issue to be able to track its progress. 

**TypeScript Version:**  2.9.2

**Search Terms:** infer function return type

**Code**

```ts
// it works with actual code:
function identity<T>(a: T) {
    return a;
}

const one = identity(1); // typeof one === 1 # everything is great

function call<A, R>(arg: A, fn: Func<A, R>): R {
    return fn(arg);
}

const two = call(2 as 2, i => i) // typeof two === 2 # everything is great

// but won't work with types
type Func<A, R> = (arg: A) => R;
// ReturnTypeByArg is inspired by `ReturnType` from TS 2.8.*
type ReturnTypeByArg<T, F extends Func<T, any>> = F extends Func<T, infer R> ? R : any;

type Identity = <T>(a: T) => T;
type Result = ReturnTypeByArg<4, Identity>; // Result === {} # not what I expect
```

**Expected behavior:**
I expect TS to be able to infer such return type

**Actual behavior:**
Return type is `{}`

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=%0D%0Afunction%20identity%3CT%3E(a%3A%20T)%20%7B%0D%0A%20%20%20%20return%20a%3B%0D%0A%7D%0D%0A%0D%0Aconst%20one%20%3D%20identity(1)%3B%20%2F%2F%20typeof%20one%20%3D%3D%3D%201%20%23%20everything%20is%20great%0D%0A%0D%0Afunction%20call%3CA%2C%20R%3E(arg%3A%20A%2C%20fn%3A%20Func%3CA%2C%20R%3E)%3A%20R%20%7B%0D%0A%20%20%20%20return%20fn(arg)%3B%0D%0A%7D%0D%0A%0D%0Aconst%20two%20%3D%20call(2%20as%202%2C%20i%20%3D%3E%20i)%20%2F%2F%20typeof%20two%20%3D%3D%3D%202%20%23%20everything%20is%20great%0D%0A%0D%0Atype%20Func%3CA%2C%20R%3E%20%3D%20(arg%3A%20A)%20%3D%3E%20R%3B%0D%0Atype%20ReturnTypeByArg%3CT%2C%20F%20extends%20Func%3CT%2C%20any%3E%3E%20%3D%20F%20extends%20Func%3CT%2C%20infer%20R%3E%20%3F%20R%20%3A%20any%3B%0D%0A%0D%0Atype%20Identity%20%3D%20%3CT%3E(a%3A%20T)%20%3D%3E%20T%3B%0D%0Atype%20Result%20%3D%20ReturnTypeByArg%3C4%2C%20Identity%3E%3B%20%2F%2F%20Result%20%3D%3D%3D%20%7B%7D%20%23%20not%20what%20I%20expect)

**Related Issues:**

**Comment by jcalz** [comment] 2018-07-28 18:50
Essentially the same as #6606

**Comment by mhegazy** [comment] 2018-07-30 16:47
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/6606

**Comment by int0h** [comment] 2018-07-31 13:05
@mhegazy I guess #6606 is a much more complex feature request. Mine looks like only one case of "Call" type which was referenced by @treybrisbane. And if such Call type is implemented it will cover my issue also.

But I thought my problem can be solved through new 2.8.* `infer` key-word. So I see it rather as a bug than a feature request.

It would be great if you provided me with a link to an issue about such Call type if one exists.

By the way, since #6606 is closed I'm not sure what do you mean by marking mine as a duplicate. Does it mean this issue won't be fixed?

**Comment by mhegazy** [comment] 2018-07-31 17:37
The underlying scenario is the same. #6606 proposed using `typeof` as syntax, but you can see the same happening using a call syntax `foo(number, string)` without the `typeof` keyword.

The complexity in implementing either is applying overload resolution as a higher-order type operator. the overload resolution is extremely complicated process, that involved multiple passes and required multiple processes like contextual types, inference, and instantiations to interact. Enabling this, at least in the current compiler implementation, for higher order types is tantamount to rewriting the core of the compiler; something we are not looking forward to.
 
You can seem my reply in https://github.com/Microsoft/TypeScript/issues/6606#issuecomment-387186188 as well.

**Comment by malash** [comment] 2018-12-14 06:33
I believe that's not a bug.

`infer R` is the union of all available types.

```ts
const f1: Func<4, 4> = identity;
// @ts-ignore f2 failed
const f2: Func<4, 1> = identity;
const f3: Func<4, number> = identity;
const f4: Func<4, any> = identity;
const f5: Func<4, {}> = identity;
```

As you can see the second argument of Func could be `any`, as known as `{}`. 

So `infer R` should be union of them and it's `{}`.

> For a given infer type variable V, if any candidates were inferred from co-variant positions, the type inferred for V is a union of those candidates. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html

@int0h

**Closed** 2018-12-16 18:00 UTC
Labels: Duplicate
