### ISSUE TITLE
Rename ".tsx" to ".jsx" in import statements

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/TypeScript#7012] opened 2016-02-10 23:44 UTC
Hi, when I compile a ts file which contains following imports

`import Navigations from './navigations.tsx';`

it outputs exactly the same line

`import Navigations from './navigations.tsx';`

This breaks the code in the browser. I would expect that "tsx" import will be renamed to "jsx"

`import Navigations from './navigations.jsx';`

Is this somehow achievable?
Thanks

PS: I am using meteor, not webpack, which does not resolve imports like `import Navigations from './navigations'`;

**Comment by vladima** [comment] 2016-02-11 00:51
shouldn't it be the issue for meteor to resolve module names without extensions?

**Comment by tomitrescak** [comment] 2016-02-11 00:52
Unfortunatelly it is not the case. Only ".js" files are resolved without extension, jsx gets left behind.

**Comment by mhegazy** [comment] 2016-02-12 01:26
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/4595

**Closed** 2016-02-12 01:35 UTC
Labels: Duplicate
