### ISSUE TITLE
Format Code bug for JS file

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11101] opened 2016-09-23 16:49 UTC
Originally from here - https://github.com/Microsoft/vscode/issues/11810

@ramya-rao-a I can reproduce. I will describe steps below
1. use Code open the javascript file in attachment, use `format code` to format code. It can't be formatted now.
2. copy the file's content, and then press `ctrl+n` to create a untitled file, then paste the content to it, change the language mode to javascript. **But do not save the file**, then use `format code` to format the file. It can be correctly formatted.
3. press `ctrl+z`, change the untitled file to compressed status, then save the whole file. And then use `format code` to formate it. Now, it can't be formatted again.

[app_c32294ea.js.zip](https://github.com/Microsoft/vscode/files/466406/app_c32294ea.js.zip)

![format](https://cloud.githubusercontent.com/assets/2631733/18422971/40660124-78d3-11e6-9841-854058e18670.gif)

**Comment by waderyan** [comment] 2016-09-23 16:49
I have reproduced this with Insiders 1.6.0 and release-2.0.5 TS.

**Comment by Treri** [comment] 2016-09-24 00:45
As described in https://github.com/Microsoft/vscode/issues/11810#issuecomment-246349933 and https://github.com/Microsoft/vscode/issues/11810#issuecomment-246547745.

The unsaved file's `format code` command comes from extensions, so it can be formatted correctly.
The saved file's `format code` is vscode's own command, and it can't be formatted correctly.

**Comment by mhegazy** [comment] 2016-12-15 21:25
this is a duplicate of https://github.com/Microsoft/TypeScript/issues/10126

**Closed by mhegazy** 2016-12-15 21:25 UTC
Labels: Duplicate, VS Code Tracked
