### ISSUE TITLE
String Interpolation error with escaped strings

### ISSUE THREAD

**Issue by Proculopsis** [Microsoft/TypeScript#20192] opened 2017-11-21 13:12 UTC
Full example here in the Playground: https://goo.gl/VWEkV5

The transpiler isn't consistent with native JavaScript when using the escaping character.

For example:

`\0` == "\0"  but  `\0000` != "\0000"

**Comment by DanielRosenwasser** [comment] 2017-11-21 16:17
This is either a bug or a symptom/duplicate of #396.

**Comment by mhegazy** [comment] 2017-11-21 17:25
PRs appreciated.

**Comment by Kingwl** [comment] 2017-12-01 08:29
ping @mhegazy and @DanielRosenwasser 
what is the correct behavior?

**Comment by chuckjaz** [comment] 2018-03-14 20:44
This affects `ts.createLiteral()` in transformers as well.

I wouldn't mind giving a crack at a PR if you can direct me to the cases that the `escapeString()` was trying to address.

**Comment by weswigham** [comment] 2018-03-14 21:22
@chuckjaz what's your specific problem? That transpiled strings get rewritten at all, or a problem with their meaning? We recently fixed a bug to do with octals in transpiled strings which may cover your problem?

**Comment by weswigham** [comment] 2018-03-14 21:37
Yeah, #22335 may have fixed this; #21828 probably should have been marked as a dupe of this.

**Comment by chuckjaz** [comment] 2018-03-15 00:18
That appears to be the fix we need, we were running into the `d2` case from #21828.  The linked issue from our repository has a PR we are landing to work around the issue in 2.6 and 2.7. Is this landing in a point release for 2.7 or waiting until 2.8?

**Comment by weswigham** [comment] 2018-03-15 01:16
It should be in the 2.8 RC, I believe, whenever that goes out (if it hasn't already).

**Closed** 2018-03-15 01:59 UTC
Labels: Bug, help wanted
