### ISSUE TITLE
Code duplication when declaring an ambient class implementing an interface

### ISSUE THREAD

**Issue by knuton** [Microsoft/TypeScript#2653] opened 2015-04-07 12:30 UTC
Ambient class declarations implementing an interface require the user to repeat the type members declared in the interface.

For example with the interface

```ts
interface IFoo {
	bar: string;
	qux(): number;
}
```

an ambient declaration of `Foo` as

```ts
declare class Foo implements IFoo {}
```

fails with `Class 'Foo' incorrectly implements interface 'IFoo'. Property 'bar' is missing in type 'Foo'`, while the following works as expected, but duplicates all declarations:

```ts
declare class Foo implements IFoo {
	bar: string;
	qux(): number;
}
```

While it should be possible to specialise when declaring an ambient class, it would be very convenient if unchanged type members would not need to be redeclared.

**Comment by billccn** [comment] 2015-04-07 12:46
Use `declare var Foo: {new(): IFoo};` (per "Class Decomposition" section in the manual)

**Comment by knuton** [comment] 2015-04-07 15:00
Thanks, but this is only a partial solution:

> Standard classes can be inherited from using extends; decomposed classes cannot.

https://github.com/Microsoft/TypeScript/wiki/Writing%20Definition%20Files#class-decomposition

**Comment by mhegazy** [comment] 2015-04-07 17:24
I believe this is a duplicate of #340

@RyanCavanaugh had a good write-up on this issue in https://github.com/Microsoft/TypeScript/issues/340#issuecomment-51098654

**Closed** 2015-04-07 17:24 UTC
Labels: Duplicate
