### ISSUE TITLE
JSDoc Strips indentation in code block

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#17309] opened 2017-07-19 22:18 UTC
From https://github.com/Microsoft/vscode/issues/30062

**TypeScript Version:**  2.4.2

**Code**

```ts
/** Just a simple sugar function for:
 * 
 * @example
 * ```
 * let valueReturned = false;
 * jest.fn(() => {
 *   if (!valueReturned) {
 *     valueReturned = true;
 *     return value;
 *   }
 * });
 * ```
 */
function foo() { }
```

Hover over `foo` to trigger a `quickInfo` request against the ts server

**Bug:**
The returned text strips all leading whitespace in the code block:

```
[Trace  - 3:12:02 PM] Response received: quickinfo (104). Request took 2 ms. Success: true 
Result: {
    "kind": "function",
    "kindModifiers": "",
    "start": {
        "line": 15,
        "offset": 10
    },
    "end": {
        "line": 15,
        "offset": 13
    },
    "displayString": "function foo(): void",
    "documentation": "Just a simple sugar function for:",
    "tags": [
        {
            "name": "example",
            "text": "```\nlet valueReturned = false;\njest.fn(() => {\nif (!valueReturned) {\nvalueReturned = true;\nreturn value;\n}\n});\n```"
        }
    ]
}
```

If a space is added before the code block like so:

```ts

/** Just a simple sugar function for:
 * 
 * @example
 * 
 * ```
 * let valueReturned = false;
 * jest.fn(() => {
 *   if (!valueReturned) {
 *     valueReturned = true;
 *     return value;
 *   }
 * });
 * ```
 */
function foo() { }
```

Then the result has the correct indentation:

```
[Trace  - 3:12:28 PM] Response received: quickinfo (108). Request took 1 ms. Success: true 
Result: {
    "kind": "function",
    "kindModifiers": "",
    "start": {
        "line": 16,
        "offset": 10
    },
    "end": {
        "line": 16,
        "offset": 13
    },
    "displayString": "function foo(): void",
    "documentation": "Just a simple sugar function for:",
    "tags": [
        {
            "name": "example",
            "text": "```\nlet valueReturned = false;\njest.fn(() => {\n   if (!valueReturned) {\n     valueReturned = true;\n     return value;\n   }\n});\n```"
        }
    ]
}
```

**Comment by mhegazy** [comment] 2018-04-12 22:39
Seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/15749

**Closed by mhegazy** 2018-04-12 22:39 UTC
Labels: Bug, Domain: JSDoc, VS Code Tracked
