### ISSUE TITLE
Tooltip rendering of http/https JSDoc `{@link ... }` tags is broken

### ISSUE THREAD

**Issue by dabrowne** [microsoft/TypeScript#46722] opened 2021-11-07 21:21 UTC
# Bug Report

### 🔎 Search Terms

jsdoc, `@link`, comment tag, http, https

### 🕗 Version & Regression Information

- This changed between versions 4.3.5 and 4.4.2

### ⏯ Playground Link

Can't replicate on the sandbox, only VSCode.

### 💻 Code

```
/**
 * This is a JSDoc comment in some typescript code.
 * {@link https://typescriptlang.org}
 */
const abc = 123;
```

### 🙁 Actual behavior

As observed using TS 4.4.2

![image](https://user-images.githubusercontent.com/9211347/140662191-9adc9a68-96a6-43ca-a20b-b430d6b84034.png)

### 🙂 Expected behavior

As observed using TS 4.3.5

![image](https://user-images.githubusercontent.com/9211347/140662226-730ac894-e029-43b5-8d7b-ef9131e87212.png)

**Comment by andrewbranch** [comment] 2021-11-08 20:51
Duplicate of #46734 (this one is older but that one has more info so going to mark this one for closing)

**Closed** 2021-11-11 18:00 UTC
Labels: Duplicate
