### ISSUE TITLE
Build: Property X does not exist on type Y.

### ISSUE THREAD

**Issue by bertrandpsi** [Microsoft/TypeScript#5549] opened 2015-11-06 15:19 UTC
Randomly during build, the typescript compiler will issue such errors while the class does actually have the property set as static:

```ts
class MyClass
{
    static MyProp:string="Hello";
    static MyFunc()
    {
       console.log(MyClass.MyProp);
    }
}
```
As during the next build it may work, this is certainly a compiler bug.

Using Visual Studio 2015 -> TypeScript for MS VS 1.6.3.0

**Comment by mhegazy** [comment] 2015-11-06 18:34
@bertrandpsi can you share more details?

**Comment by mhegazy** [comment] 2015-11-06 18:35
a minimal self-contained msbuild project showing the issue would be ideal.

**Comment by bertrandpsi** [comment] 2015-11-06 20:49
@mhegazy will prepare it on Monday when I'm back at work. But basically what I do is a ts file pro class, and then join then on the build, still, the property issue seems to be triggered from the same class calling static properties so it should not be even an issue of class definition in the wrong order or other similar things.

Remember that this is not always the case but like once every 10 build or so. Could be a timing issue?

**Comment by mhegazy** [comment] 2015-11-06 23:21
wounder if it is related to #4185. We tracked the issue down to bug in the JS engine. if you have a consistent repro that shown the issue (say if i run the same command 100 times it fails once), then we can run it on nodejs and see if it does not repro, and that will point us to the engine. if not then it is a TypeScript compiler issue or a build system race condition.

**Comment by bertrandpsi** [comment] 2015-11-09 08:25
Tried to extract from my project and reproduce the bug and wasn't able. If you want I can send you via email or other means my original project to let you dig into.

**Comment by romanresh** [comment] 2015-11-09 11:33
Have the same problem on our CI server. This error is reproduced randomly for all static members in a project (.csproj, MSBUILD is used for building). One moment - if this error is occurred once, then build will fail (on this virtual machine) until I build the project via Visual Studio.
OS: Win10, msbuild: 12.0.40629.

**Comment by bertrandpsi** [comment] 2015-11-18 07:30
The full message I get is:
C:\tfs\Inventory\SharpInventory\IV4\TypeScript\GUI\DatePicker.ts(16,20): error TS2339: Build: Property 'currentPickers' does not exist on type 'typeof DatePicker'.

While on the DatePicker TS class I clearly have it:
class DatePicker implements IDisposable
{
    static currentPickers: DatePicker[] = [];
...
}

**Comment by mhegazy** [comment] 2015-12-01 23:16
since it is not consistent, i would think it is the same as #4185. @bertrandpsi and @romanresh can you try with `node tsc.js` instead of `tsc.exe` and see if there is any difference?

**Comment by Mauricio2Code** [comment] 2015-12-14 18:15
I'm experiencing the same thing. Using Visual Studio 2013-> TypeScript for MS VS 1.6.3.0 and this is the code that I'm using:
class MessageBus {

    private static _instance: MessageBus = new MessageBus();
..
}


The compiler errors intermittently  with "Build: Property '_instance' does not exist on type 'typeof MessageBus'.

**Comment by mhegazy** [comment] 2016-01-19 17:47
Given the information available so far, this looks like a duplicate of  #4185. TS 1.8 should have a fix for that.

**Closed by mhegazy** 2016-01-19 17:47 UTC
Labels: Bug, Duplicate, Needs More Info, Visual Studio
