### ISSUE TITLE
Problems with symlinks on Azure with Docker

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#13026] opened 2016-12-19 18:04 UTC
We don't have a good repro yet, but created an issue to track these investigations.

**Comment by mhegazy** [comment] 2016-12-19 18:09
another docker issue, may or may not be related: https://github.com/Microsoft/TypeScript/issues/12748#issuecomment-265959565

**Comment by mhegazy** [comment] 2016-12-22 19:51
seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/13060

**Closed by mhegazy** 2016-12-22 19:51 UTC
