### ISSUE TITLE
Tuple issues

### ISSUE THREAD

**Issue by Josh119891** [microsoft/TypeScript#49830] opened 2022-07-08 03:20 UTC
# Bug Report

First time to report issues on typescript...
I am working with Tuple.
The Tuple variable could not directly access the index that larger than its length.
It will show up an error, but it push any types of variable as I want and can access them by for loop.

### 🔎 Search Terms
Tuple

### 🕗 Version & Regression Information

![image](https://user-images.githubusercontent.com/18020366/177909912-5b2df2c0-1ca9-4ebb-84cb-a329b5f5af20.png)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8BtAdgVwLYCMICcA0aWuBG2+AzsDgJbIDmAugNwBQAxgPbKVQCGUALjjwoiAIx4ATHgDMeAORj5zFrwB0YVOQAWACgAsASlUategERjJM88fWaduy9dsmHFqzbunHzr27MnT1d2LnIOABsINQiOOl11ADNqCOBcXV1qQ3gAPmp4AqNDIA)

### 💻 Code

```ts
type A =[number,number,number,string];
const a :A = [1,2,3,'1'];
a.push(4)
a.push("123")
a.push("123")
a.push("123")
a.push("123")
a.push("123")

console.log(a.filter((i)=>i===4))
```

### 🙁 Actual behavior

It did not show up any error.

### 🙂 Expected behavior

It should limit the length of array and show error if excceeds

**Comment by harry0000** [comment] 2022-07-08 03:44
Duplicate of #48465

**Closed** 2022-07-10 18:00 UTC
Labels: Duplicate
