### ISSUE TITLE
Broken behaviour with object property shortcuts and types union

### ISSUE THREAD

**Issue by dfilatov** [Microsoft/TypeScript#21599] opened 2018-02-03 10:20 UTC
**TypeScript Version:**  2.7.1

**Code**

```ts
type WithLoading = { loading: true; } | { loading: false; };

const loading = true;

const a: WithLoading = { loading };
```

**Expected behavior:**
No errors. And TypeScript 2.6.2 properly handles this case.
If I change the last line to `const a: WithLoading = { loading: loading };` then there won't be any error, so it looks definitely like a bug.

**Actual behavior:**
Types of property 'loading' are incompatible. Type 'boolean' is not assignable to type 'false'.

**Playground Link:**  
https://www.typescriptlang.org/play/index.html#src=type%20WithLoading%20%3D%20%7B%20loading%3A%20true%3B%20%7D%20%7C%20%7B%20loading%3A%20false%3B%20%7D%3B%0A%0Aconst%20loading%20%3D%20true%3B%0A%0Aconst%20a%3A%20WithLoading%20%3D%20%7B%20loading%20%7D%3B

**Comment by HyphnKnight** [comment] 2018-02-05 21:58
It should be noted this applies to tuples as well as objects
```
type A = [true,string,string];
type B = [false,string]
const val:A|B = [false,'test'];
```

**Comment by mhegazy** [comment] 2018-02-05 22:15
Duplicate of https://github.com/Microsoft/TypeScript/issues/21436. should be fixed in typescript@next.

**Closed** 2018-02-20 19:07 UTC
Labels: Duplicate
