### ISSUE TITLE
Union of tuples called out as not spreadable.

### ISSUE THREAD

**Issue by craigphicks** [microsoft/TypeScript#57156] opened 2024-01-24 16:55 UTC
### 🔎 Search Terms

A spread argument must either have a tuple type or be passed to a rest parameter.

NOT RELATED TO  #49700

### 🕗 Version & Regression Information

All versions

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.0.5#code/LAKA9GAECqDOCmkAuALeDkoE70QE3gGMAbAQy1KQEsB7AO0irtiXlL2RsgHN4lIsVDjQBmkeFiw0soCJBEBXOoWr1IAMRo0AFADp9AbQBupYgvgAaGgGsAugC5IBugoC2AIwkWkWc7YA+BkoEIkzweBYipgi2AJSORjRCANyyUIrKqgyaOvq6xqbmVnaOzm6eWN6+8AFBdCFhEVHEMYEuHhL+wfChdOEW7lrEbHRxCUl4yZBy-phSAO6wkABEFHS8AKKS0stp8koqtNlaeoYmZpY2Dk7tFVV+gd29-c2tZR1YXfU9jQNDI2NIIkhJAAN6gUAZQ5qHLac7mRy3LyQGyOHzmeJAiapEBQrIaE7w+COJ6-FHWRyveCY4GTSEHfGwomI8oSSCzUl9CLkxyDGjDUh0GnY6ZQVALJarQWbbZYXa4hlHAk6ZmQJFYdmQTn9HmQPkCoXjEHgkCQM2MMTaGyQABkNuQAE8AA7wURAwqIAC83pW6uWsRN5qD7ouUzk6tAQYAvpHzfAWogqJaAITWu2Ol1uomQb2elbavD+wPBs1EsNQCOm80xqtm8U0eYrNYyqRynE10A+B1g2OwgAsACYLPJotTy2quBsAEpTgDyU8cvZOBeH6LHoonkGnc4XkFANcIlEIKG01NBHZABBI5EQJg1qvVmoLOKvZBw7o1qL1-0FOK7ParJkPWHGxYnHOhJxned90gQ8kGPSBT1iMEL1fG9YPoFhIHIbhYFKdVV2qWwzVmOoGi5YcqVsHFYTyHDYDAjcJFbRwAEFIFgJ0cHYbCsG4Nx4DofhXAULD4CoVA2RQUgjEQUhkAUJ1hgzRBpD1RAnVIWAEA4JAuHknAsM0ihXD4CRdG0AcAFYrIANliIA

### 💻 Code

```ts
// Use these three declaration instead to get rid of error
// function Foo(...[value,ok]: [number,true]|[undefined,false]): void;
// function Foo(...[value,ok]: [number,true]|[undefined,false]|[number|undefined,boolean]): void; // | throws "rangeError"
// function Foo(...[value,ok]: [number,true]|[undefined,false]|[number|undefined,boolean]): void {

function Foo(value: number, ok: true): void;
function Foo(value: undefined, ok: false): void;
function Foo(value: number | undefined, ok: boolean): void; // throws "rangeError"
function Foo(value: number | undefined, ok: boolean): void {
    if (ok && typeof value === "number"){
        value; // number
    }
    else if (!ok && typeof value === "undefined"){
        value; // number
    }
    throw "rangeError";
}

try {
  Foo(42, false); // no ERROR: 
  Foo(undefined, true); // no ERROR: 
}
catch(e){}

declare var value: number | undefined;
declare var ok: boolean;
try {
  Foo(value, ok); // no ERROR
} catch (e) {}

declare var args: [number, true] | [undefined, false];
Foo(...args);  // ERROR,  should not be an error 
//       ~~~~
// error: A spread argument must either have a tuple type or be passed to a rest parameter.(2556)
```

### 🙁 Actual behavior

A spread union of tuples cannot be matched unless the parameter declaration being matched is a spread of union of tuples. 

### 🙂 Expected behavior

A spread union of tuples can be matched in this case.

**Comment by MartinJohns** [comment] 2024-01-24 17:13
Duplicate of #49802.

**Comment by craigphicks** [comment] 2024-01-24 18:21
@MartinJohns - Good catch.  Notably, 49802 didn't mention that the spread union of tuple argument will be passed is the parameter is spread tuple argument.

**Closed** 2024-01-27 01:24 UTC
Labels: Duplicate
