### ISSUE TITLE
StrictNullCheck incorrectly prevents the use of the indexed access operator

### ISSUE THREAD

**Issue by RainingChain** [Microsoft/TypeScript#20141] opened 2017-11-19 17:26 UTC
**TypeScript Version:**  2.6.1

**Code**

```ts
class Klass {
  prop1:{innerNumber:number} | null;
  setInnerNumber(newInnerNumber:Klass['prop1']['innerNumber']){
    this.prop1 = {innerNumber:newInnerNumber}
  }
}
//Compile with --strictNullCheck

```

**Expected behavior:**
No error.

**Actual behavior:**
Property `innerNumber` does not exist on type `'{ innerNumber:number;} | null'`

Strict null check should not be checked for indexed access operator.

**Comment by andy-ms** [comment] 2017-11-19 18:30
Duplicate of #14366

**Closed** 2017-12-04 18:35 UTC
Labels: Duplicate

**Comment by mhegazy** [comment] 2018-03-02 18:37
This should be doable today using [`NonNullable` type](https://github.com/Microsoft/TypeScript/pull/21847)
