### ISSUE TITLE
Valid .tsx file can result in an invalid declaration file

### ISSUE THREAD

**Issue by kujon** [Microsoft/TypeScript#18553] opened 2017-09-18 18:50 UTC
**TypeScript Version:**  2.4.2

**Code**

Consider the following silly higher-order component. It all compiles beautifully.

```ts
export type OriginalProps = {
    foo: string;
};

export type HOCProps = {
    bar: string;
};

export function exampleHOC<T extends OriginalProps>(
    WrappedComponent: React.ComponentType<T>
) {
    return class ExampleHOC extends React.PureComponent<T & HOCProps> {
        render() {
            const { foo, bar } = this.props;

            return <WrappedComponent foo={`${foo} - ${bar}`} />;
        }
    };
}

class ExampleComponent extends React.PureComponent<OriginalProps> {
    render() {
        return <span>{this.props.foo}</span>;
    }
}

export default exampleHOC(ExampleComponent);
```

When compiled, the following `*.d.ts` file is yielded:

```ts
/// <reference types="react" />
import * as React from 'react';
export declare type OriginalProps = {
    foo: string;
};
export declare type HOCProps = {
    bar: string;
};
export declare function exampleHOC<T extends OriginalProps>(WrappedComponent: React.ComponentType<T>): {
    new (props?: T & HOCProps, context?: any): {
        render(): JSX.Element;
        setState<K extends never>(f: (prevState: {}, props: T & HOCProps) => Pick<{}, K>, callback?: () => any): void;
        setState<K extends never>(state: Pick<{}, K>, callback?: () => any): void;
        forceUpdate(callBack?: () => any): void;
        props: Readonly<{
            children?: React.ReactNode;
        }> & Readonly<T & HOCProps>;
        state: Readonly<{}>;
        context: any;
        refs: {
            [key: string]: React.ReactInstance;
        };
        componentWillMount?(): void;
        componentDidMount?(): void;
        componentWillReceiveProps?(nextProps: Readonly<T & HOCProps>, nextContext: any): void;
        shouldComponentUpdate?(nextProps: Readonly<T & HOCProps>, nextState: Readonly<{}>, nextContext: any): boolean;
        componentWillUpdate?(nextProps: Readonly<T & HOCProps>, nextState: Readonly<{}>, nextContext: any): void;
        componentDidUpdate?(prevProps: Readonly<T & HOCProps>, prevState: Readonly<{}>, prevContext: any): void;
        componentWillUnmount?(): void;
    };
};
declare const _default: {
    new (props?: OriginalProps & HOCProps, context?: any): {
        render(): JSX.Element;
        /** Cannot find name 'T'. */
        setState<K extends never>(f: (prevState: {}, props: T & HOCProps) => Pick<{}, K>, callback?: () => any): void;
        setState<K extends never>(state: Pick<{}, K>, callback?: () => any): void;
        forceUpdate(callBack?: () => any): void;
        /** Cannot find name 'T'. */
        props: Readonly<{
            children?: React.ReactNode;
        }> & Readonly<T & HOCProps>;
        state: Readonly<{}>;
        context: any;
        refs: {
            [key: string]: React.ReactInstance;
        };
        componentWillMount?(): void;
        componentDidMount?(): void;
        /** Cannot find name 'T'. */
        componentWillReceiveProps?(nextProps: Readonly<T & HOCProps>, nextContext: any): void;
        /** Cannot find name 'T'. */
        shouldComponentUpdate?(nextProps: Readonly<T & HOCProps>, nextState: Readonly<{}>, nextContext: any): boolean;
        /** Cannot find name 'T'. */
        componentWillUpdate?(nextProps: Readonly<T & HOCProps>, nextState: Readonly<{}>, nextContext: any): void;
        /** Cannot find name 'T'. */
        componentDidUpdate?(prevProps: Readonly<T & HOCProps>, prevState: Readonly<{}>, prevContext: any): void;
        componentWillUnmount?(): void;
    };
};
export default _default;

```

Even though the TypeScript code was valid, the generated declaration is not.

**Expected behavior:**
A valid declaration is generated.

**Actual behavior:**
See above.

**Comment by mhegazy** [comment] 2017-09-18 18:56
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/18545

**Comment by kujon** [comment] 2017-09-19 14:42
If it's of any help, here's the workaround:

```ts
export function exampleHOC<T extends OriginalProps>(
    WrappedComponent: React.ComponentType<T>
) {
    const HOC = class ExampleHOC extends React.PureComponent<T & HOCProps> {
        render() {
            const { foo, bar } = this.props;

            return <WrappedComponent foo={`${foo} - ${bar}`} />;
        }
    };

    return HOC;
}
```

**Comment by mhegazy** [comment] 2017-10-05 18:18
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-05 18:18 UTC
Labels: Duplicate
