### ISSUE TITLE
jsdoc type including module: prefix is not parsed correctly

### ISSUE THREAD

**Issue by jkieboom** [Microsoft/TypeScript#25684] opened 2018-07-16 11:25 UTC
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** jsdoc parse type module

**Code**

```ts
/**
 * @module namespaced/class/Type
 */

/**
 * Refers to a module: prefixed type
 * @param {module:namespaced/class/Type} param - A parameter
 **/
function f(type: Type) {}
```

**Expected behavior:**

When inspecting the AST (in this case for a tslint rule), I expected the type of the `JSDocParameterTag` node to be `module:namespaced/class/Type`. Instead, it appears parsing the type stopped at `:` and the `node.comment` part is `:namespaced/class/Type} param - A parameter`.

**Actual behavior:**

I would expect the type to be correctly parsed as well as the remainder of the `@param` tag.

**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment] 2018-07-16 20:55
`@module` is not supported. use `@param {import("namespaced/class/Type")} param - A parameter` instead.

**Comment by mhegazy** [comment] 2018-07-16 21:08
Duplicate of https://github.com/Microsoft/TypeScript/issues/22158

**Closed** 2018-07-17 06:01 UTC
Labels: Duplicate
