### ISSUE TITLE
Array filter on array does not correct types returned from map

### ISSUE THREAD

**Issue by alzalabany** [microsoft/TypeScript#35988] opened 2020-01-03 22:36 UTC
**Search Terms:**
Type Array filter

**Code**
```ts
type T = { id:number };
const obj = [{id:1},{id:2},{id:3}]
const ids = [1,2,5];
const error:T[] = ids.map(id=>obj[id] ? obj[id] : false).filter(Boolean);
```

**Expected behavior:**
`const error` should be T[] only;

**Actual behavior:**
// error type is T | false

**Related Issues:** 
[7657](https://github.com/microsoft/TypeScript/issues/7657)

**Comment by gioragutt** [comment] 2020-01-03 23:35
Dude, `id => obj[id] ? obj[id] : false` literally means that this can be a `false`.
This is working as expected 👍🏻

What you want it `id => obj[id]` instead. If `obj` doesn't have a field with the name specified by `id`, it will return `undefined`.

**Comment by MartinJohns** [comment] 2020-01-04 00:06
Duplicate of #32834, #31164, #24063, #16655. Was implemented by #29955, and broken by #31515.

Search terms used: `filter boolean`

**Closed** 2020-01-09 18:00 UTC
Labels: Duplicate

**Comment by OmgImAlexis** [comment] 2020-05-12 12:19
@MartinJohns since this was broken by #31515 can we get a new issue open to track this? Otherwise you're just going to keep closing issues as duplicates.

**Comment by MartinJohns** [comment] 2020-05-12 12:23
@OmgImAlexis I'm not a member of the TypeScript team, so I have no say in this. But.. why get a new issue? There are existing issues about this, see my comment from before: https://github.com/microsoft/TypeScript/issues/35988#issuecomment-570735297

**Comment by OmgImAlexis** [comment] 2020-05-12 12:25
The first two issues you linked were closed, I had assumed the others were too.
