### ISSUE TITLE
Compiler error es6 and import

### ISSUE THREAD

**Issue by dpinart** [Microsoft/TypeScript#5351] opened 2015-10-21 18:36 UTC
Hi,
I want to compile ts to es6 so I've set -t parameter to es6. The issue is that I'm having a funky compilation error as soon I import modules using ES6 import syntax like:
import {Class2} from './class2';
export class Class1{
  greet(){
    new Class2().greet();
  }

the error I'm gettinge is "error while compiling: TypeError: undefined is not a function TypeError: undefined is not a function". I just installed latest typescript version from npm.

**Comment by vladima** [comment] 2015-10-21 18:45
does not repro for me
```ts
// class1.ts
import {Class2} from './class2';

export class Class1{
    greet() {
        new Class2().greet();
    }
}
```

```ts
/// class2.ts
export class Class2{
    greet() {
        new Class2().greet();
    }
}
```
Running `node built/local/tsc.js class1.ts -m commonjs` yields no compilation errors.
Can  you please provide more information:
- do you get this error in IDE or when you compile from the command line
- if my example does not reflect your scenario can you give a complete sample that shows the problem

**Comment by dpinart** [comment] 2015-10-21 18:49
hi vladina, thanks for your quick response.

I'm using webstorm 10.0.4. and have configured the compiler to point to %ProjectFolder%\node_modules\typescript\lib with just one argument: -t es6

**Comment by dpinart** [comment] 2015-10-21 18:54
I have run the compiler from command line with node node_modules\typescript\lib\tsc.js src/class1.ts -t es6 and it has worked successfully.

It's weird, it looks is a webstorm issue

**Comment by vladima** [comment] 2015-10-21 19:46
this is a dupe of #5247

**Closed by vladima** 2015-10-21 19:46 UTC

**Comment by dpinart** [comment] 2015-10-22 14:13
Yep it seems so.

I'm trying to work with visual studio 2013 and tha latest TypeScript with same result. Visual does not recognize the import statement. Any idea=
