### ISSUE TITLE
TSC crashes during binding in UWP JS project

### ISSUE THREAD

**Issue by uniqueiniquity** [microsoft/TypeScript#34672] opened 2019-10-23 16:07 UTC
**TypeScript Version:**  3.7.1-rc

**Search Terms:**
bindSpecialPropertyAssignment
**Repro Instructions**
In Visual Studio 2017:
1. Create a WinJS APP (Universal Windows) project.
2. Add a TypeScript JSON Configuration file in project.
3. Delete all code in "tsconfig.json" and add code below:
{
  "compilerOptions": {
    "module": "commonjs",
    "allowJs": true,
    "outDir": "out",
      "jsx": "react"
  },
  "exclude": [
    "node_modules",
    "wwwroot",
    "out"
  ],
  "compileOnSave": true,                              
  "typingOptions": { 
    "enableAutoDiscovery": true 
  }  
} 
3. Build project.

**Expected behavior:**
Build successful.
**Actual behavior:**
TSC crashes with the following stack:
```
1>    Unknown output:             throw e;
1>    Unknown output:             ^
1>    Unknown output:     at Object.cast (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsc.js:1309:25)
1>    Unknown output:     at bindSpecialPropertyAssignment (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsc.js:31379:53)
1>    Unknown output:     at bindWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsc.js:30946:29)
1>    Unknown output:     at bind (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsc.js:30825:13)
1>    Unknown output:     at bindExpressionStatement (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsc.js:30033:13)
1>    Unknown output:     at bindChildrenWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsc.js:29494:21)
1>    Unknown output:     at bindChildren (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsc.js:29415:17)
1>    Unknown output:     at bind (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsc.js:30836:21)
1>    Unknown output:     at C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsc.js:29421:94
1>    Unknown output:     at bindEach (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsc.js:29437:21)
```

**Comment by DanielRosenwasser** [comment] 2019-10-23 16:58
Any chance you can provide the code that comes out of the box?

**Comment by uniqueiniquity** [comment] 2019-10-23 17:05
It's also crashing the language service (as one would expect).
Will provide the code in a sec:
```
The JavaScript and TypeScript language service has been disabled due to an error. You may see reduced IntelliSense support for your project. Please try reloading your solution to reenable the language service.
Error processing request. Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isBindableStaticAccessExpression'.
Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isBindableStaticAccessExpression'.
    at Object.cast (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:1333:25)
    at bindSpecialPropertyAssignment (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:31403:53)
    at bindWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30970:29)
    at bind (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30849:13)
    at bindExpressionStatement (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30057:13)
    at bindChildrenWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29518:21)
    at bindChildren (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29439:17)
    at bind (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30860:21)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29445:94
    at bindEach (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29461:21)
    at bindEachFunctionsFirst (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29445:13)
    at bindChildrenWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29561:21)
    at bindChildren (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29439:17)
    at bind (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30860:21)
    at visitNode (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:17572:24)
    at Object.forEachChild (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:17702:21)
    at bindEachChild (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29469:16)
    at bindChildrenWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29564:21)
    at bindChildren (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29439:17)
    at bindContainer (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29385:17)
    at bind (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30863:21)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29444:94
    at bindEach (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29461:21)
    at bindEachFunctionsFirst (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29444:13)
    at bindChildrenWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29561:21)
    at bindChildren (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29439:17)
    at bind (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30860:21)
    at visitNode (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:17572:24)
    at Object.forEachChild (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:17702:21)
    at bindEachChild (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29469:16)
    at bindChildrenWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29564:21)
    at bindChildren (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29439:17)
    at bindContainer (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29385:17)
    at bind (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30863:21)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29444:94
    at bindEach (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29461:21)
    at bindEachFunctionsFirst (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29444:13)
    at bindChildrenWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29561:21)
    at bindChildren (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29439:17)
    at bind (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30860:21)
    at visitNode (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:17572:24)
    at Object.forEachChild (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:17702:21)
    at bindEachChild (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29469:16)
    at bindChildrenWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29564:21)
    at bindChildren (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29439:17)
    at bindContainer (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29385:17)
    at bind (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30863:21)
    at bindEach (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29461:21)
    at visitNodes (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:17577:24)
    at Object.forEachChild (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:17765:21)
    at bindEachChild (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29469:16)
    at bindCallExpressionFlow (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30314:21)
    at bindChildrenWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29546:21)
    at bindChildren (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29439:17)
    at bind (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30860:21)
    at visitNode (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:17572:24)
    at Object.forEachChild (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:17659:21)
    at bindEachChild (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29469:16)
    at bindChildrenWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29564:21)
    at bindChildren (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29439:17)
    at bind (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30860:21)
    at bindEach (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29461:21)
    at visitNodes (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:17577:24)
    at Object.forEachChild (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:17751:24)
    at bindEachChild (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29469:16)
    at bindChildrenWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29564:21)
    at bindChildren (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29439:17)
    at bindContainer (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29420:17)
    at bind (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30863:21)
    at bindEach (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29461:21)
    at visitNodes (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:17577:24)
    at Object.forEachChild (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:17765:21)
    at bindEachChild (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29469:16)
    at bindCallExpressionFlow (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30314:21)
    at bindChildrenWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29546:21)
    at bindChildren (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29439:17)
    at bind (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30860:21)
    at bindExpressionStatement (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30057:13)
    at bindChildrenWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29518:21)
    at bindChildren (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29439:17)
    at bind (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30860:21)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29445:94
    at bindEach (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29461:21)
    at bindEachFunctionsFirst (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29445:13)
    at bindChildrenWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29561:21)
    at bindChildren (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29439:17)
    at bind (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30860:21)
    at visitNode (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:17572:24)
    at Object.forEachChild (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:17702:21)
    at bindEachChild (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29469:16)
    at bindChildrenWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29564:21)
    at bindChildren (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29439:17)
    at bindContainer (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29385:17)
    at bind (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30863:21)
    at bindEach (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29461:21)
    at visitNodes (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:17577:24)
    at Object.forEachChild (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:17765:21)
    at bindEachChild (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29469:16)
    at bindCallExpressionFlow (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:30314:21)
    at bindChildrenWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.7\tsserver.js:29546:21)

```

**Comment by uniqueiniquity** [comment] 2019-10-23 17:07
Here's all the .js and .d.ts files included in the project when running with 3.6.
[371crash.zip](https://github.com/microsoft/TypeScript/files/3763557/371crash.zip)

**Comment by DanielRosenwasser** [comment] 2019-10-23 17:41
Reduced repro in a JS file:

```js
var indexMap = {};
indexMap[-1] = slotsStart;
```

**Comment by minestarks** [comment] 2019-12-17 18:45
@weswigham @RyanCavanaugh  we're still getting hits from this in 3.7.3 in VS. https://devdiv.visualstudio.com/DevDiv/_queries/edit/1041219/?triage=true

**Comment by weswigham** [comment] 2019-12-17 19:19
Hm, @DanielRosenwasser 's reduced repro is definitely fixed, and I'm not seeing an editor crash with the repro @uniqueiniquity linked anymore, at least not with the latest builds of `master`. Do we know more?

**Comment by minestarks** [comment] 2019-12-17 19:32
Possibly. What kind of data might help? With bugs from telemetry, we don't have the source code available but we can look at patterns to help narrow down a repro. If you need to collect more context we can look into adding better error reporting for the next iteration. Just need to know what kind of information would help you investigate.

**Comment by weswigham** [comment] 2019-12-18 00:55
I mean, it's strange, because our check to even attempt a special property bind is
```ts
if (isBindableStaticNameExpression(lhs, /*excludeThisKeyword*/ true) || (isElementAccessExpression(lhs) && isDynamicName(lhs) && lhs.expression.kind !== SyntaxKind.ThisKeyword)) {
```
and our two covered cases here are supposed to be `hasDynamicName(node)` and `isBindableStaticAccessExpression(node.left)`. All I can think of is some mismatch between `hasDynamicName(node)` and `isDynamicName(lhs)`; but I can't think of any code structure that'd cause such a mismatch to make a repro. Honestly the AST/source of `node` around the assertion failure would be nice.

**Comment by minestarks** [comment] 2019-12-18 01:02
Any chance this is related to #35730 ? That also has to do with dynamic names in accessors and that was fixed in 3.7.3.

I will follow up on how we can collect contextual information for debugging while keeping in line with privacy guidelines.

**Comment by weswigham** [comment] 2019-12-18 13:56
? The PR you linked just merged today?

**Comment by minestarks** [comment] 2019-12-18 16:35
Sorry I have no idea how I ended up pasting that number. I meant to link to #35630 . I was wondering if the bugs may be related since that fix was for a bug that was also occurring in 3.7.3 in property accessors.

**Comment by minestarks** [comment] 2020-01-22 00:44
@weswigham any more info you need on this?

**Comment by weswigham** [comment] 2020-02-07 00:51
@uniqueiniquity is this still reproducible with the js in the UWP app template? If so, can I just get a copy of the TS+JS in that template? If not, and it's just that we're still getting similar hits in telemetry: ??? Is this still persisting in current telemetry? I could add some slightly more helpful information to the assertion failure.

**Comment by uniqueiniquity** [comment] 2020-02-07 00:57
@weswigham Nope, that template is fine in 3.7.4 and in 3.8.1.

**Closed** 2020-02-07 01:07 UTC
Labels: Bug, Crash
