### ISSUE TITLE
Array#includes argument type is too narrow

### ISSUE THREAD

**Issue by aquark** [microsoft/TypeScript#36352] opened 2020-01-22 14:32 UTC
**TypeScript Version:**  my project uses `3.5.3` but I can see the issue is still present in the `master` branch.

**Search Terms:** Array includes

**Code**

```ts
const b: string = 'b'
['a' as const].includes(b)
```

**Expected behavior:**
It should compile. Specifically, the type definition for `Array#includes` should allow for any `searchElement` type:

```
interface Array<T> {
    /**
     * Determines whether an array includes a certain element, returning true or false as appropriate.
     * @param searchElement The element to search for.
     * @param fromIndex The position in this array at which to begin searching for searchElement.
     */
    includes(searchElement: unknown, fromIndex?: number): boolean;
}
```

It is type-safe to ask whether an array contains *any* value for the same reason it is type-safe to compare any two types with `===`. The example above is a toy example but this pattern shows up all the time in real-world use, e.g. to check if a `string` is a member of a union of strings.

**Actual behavior:**
`Argument of type 'string' is not assignable to parameter of type '"a"'`

**Related Issues:** None found

**Comment by jcalz** [comment] 2020-01-22 15:04
Duplicate of #26255

**Comment by aquark** [comment] 2020-01-22 19:48
Seems like this keeps coming up because there are common idioms which cannot be expressed without unsafe casts. I hear the argument that TS should prevent stupid errors, at the same time it should also try to support idiomatic code naturally. I would argue that until bivariant argument types are supported, it would be better to give this a less restrictive type which supports all the standard use cases, rather than encourage casting. Compare Java's `Collection#contains` for example.

**Comment by jcalz** [comment] 2020-01-22 19:50
[Relevant SO answer](https://stackoverflow.com/a/53035048/2887218) about this

**Closed** 2020-01-25 18:00 UTC
Labels: Duplicate
