### ISSUE TITLE
Unable to use nested keyof params

### ISSUE THREAD

**Issue by ericanderson** [Microsoft/TypeScript#12586] opened 2016-11-30 16:22 UTC
**TypeScript Version:**  2.2.0-dev.20161130

**Code**

```ts
function deepAssign<T, A extends keyof T, B extends keyof T[A]>(obj: T, a: A, b: B, value: T[A][B]) {
  obj[a][b] = value;
}

const a = {
  foo: {
    bar: 5,
  },
};

deepAssign(a, "foo", "bar", 6);
```

**Expected behavior:**
```ts
a.foo.bar === 6
```

**Actual behavior:**

    src/deepAssign.ts(11,22): error TS2345: Argument of type '"bar"' is not assignable to parameter of type 'never'.

**Comment by ericanderson** [comment] 2016-11-30 16:26
It seems that this works, but it feels like an extra unnecessary step:

```ts
function deepAssign<T, A extends keyof T, U extends T[A], B extends keyof U>(obj: T, a: A, b: B, value: U[B]) {
  (obj[a] as any)[b] = value;
}

const a = {
  foo: {
    bar: 5,
  },
};

deepAssign(a, "foo", "bar", 6);
```

**Comment by mhegazy** [comment] 2016-11-30 17:31
Duplicate of https://github.com/Microsoft/TypeScript/issues/12544

**Closed** 2016-12-29 19:33 UTC
Labels: Duplicate
