### ISSUE TITLE
Why is there no error in this place

### ISSUE THREAD

**Issue by mytheart** [microsoft/TypeScript#41683] opened 2020-11-25 03:02 UTC
![image](https://user-images.githubusercontent.com/42933010/100177866-d33cf580-2f0d-11eb-8764-300dcaed34ce.png)

**Comment by lazytype** [comment] 2020-11-25 03:30
This is not a support forum. There are people who would be happy to answer this question on [stackoverflow](https://stackoverflow.com/)

**Comment by IllusionMH** [comment] 2020-11-25 13:07
Duplicate of #20863 and other.

**Closed** 2020-11-25 17:15 UTC
Labels: Duplicate
