### ISSUE TITLE
Support `jsnext:main` field

### ISSUE THREAD

**Issue by dbrgn** [Microsoft/TypeScript#11677] opened 2016-10-17 11:42 UTC
I'm writing a library that depends on another library I published: https://www.npmjs.com/package/chunked-dc

That chunked-dc library exposes ES2015 modules directly via the [jsnext:main](https://github.com/rollup/rollup/wiki/jsnext:main) field in `package.json`:

https://github.com/saltyrtc/chunked-dc-js/blob/2823d9bb1b2ff42de78129b285069f3396092ed4/package.json#L6

Unfortunately it looks like typescript does not support that field. That means that instead of importing ES2015 classes directly:

```
import {Chunker, Unchunker} from "chunked-dc";
```

...I have to fall back to the ES5 version generated by babel. This prevents tools like rollup from doing their dead code elimination work.

It would be great if the `jsnext:main` field were supported directly.

**Comment by mhegazy** [comment] 2016-10-17 16:34
The issue is not that the library exposed an ES2015 module or not. the issue is the lack of type information. You would need a declaration file for this module (e.g. published to definitely typed).

**Comment by dbrgn** [comment] 2016-10-17 19:59
Hm, that's a good point. Couldn't we add a field to declare the path to the TypeScript sources directly? Most TypeScript npm packages include those anyways.

**Comment by mhegazy** [comment] 2016-10-17 20:07
There is one, `"types"` or `"typings'`. see http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by dbrgn** [comment] 2016-10-17 20:40
I'm using that. The thing is that I apparently can't import ES2015 packages from npm directly as external modules.

**Comment by mhegazy** [comment] 2016-10-17 20:49
can you share a sample i can look at?

**Comment by aluanhaddad** [comment] 2016-10-19 04:11
I think this is an important problem and it's definitely one I have into before, interestingly enough on a Babel project not a TypeScript project, but I think this has to be solved at the package manager, loader, and bundler level as much if not more than on the language level.

You may be able to get this working in this specific case if you used the new `baseUrl` and `paths` features added in 2.0 but an additional issue with your your library is that the declarations file that resides alongside the es2015 bundle has a different file name. This will make it more difficult to support multiple types of consumers. I would consider creating format specific subdirectories under `dist` and putting identically named declaration files beside each one.

**Comment by dbrgn** [comment] 2016-10-19 12:29
> can you share a sample i can look at?

Use this `package.json`:

```json
{
  "dependencies": {
    "chunked-dc": "^0.2.2"
  }
}
```

...and this `test.ts` file:

```
/// <reference types="chunked-dc" />
import {Chunker, Unchunker} from "chunked-dc";
let c: chunkedDc.Chunker = new Chunker()
```

As you can see I both use the type information (via the "reference") as well as the ES2015 module exports (via "import").

I get the following error when compiling with classic module resolution:

```
$ tsc --noEmit -t ES2015 -m es2015 --traceResolution test.ts
======== Resolving type reference directive 'chunked-dc', containing file 'test.ts', root directory not set. ========
Root directory cannot be determined, skipping primary search paths.
Looking up in 'node_modules' folder, initial location ''
File 'node_modules/chunked-dc.ts' does not exist.
File 'node_modules/chunked-dc.d.ts' does not exist.
Found 'package.json' at 'node_modules/chunked-dc/package.json'.
'package.json' has 'types' field 'dist/chunked-dc.d.ts' that references 'node_modules/chunked-dc/dist/chunked-dc.d.ts'.
File 'node_modules/chunked-dc/dist/chunked-dc.d.ts' exist - use it as a name resolution result.
======== Type reference directive 'chunked-dc' was successfully resolved to 'node_modules/chunked-dc/dist/chunked-dc.d.ts', primary: false. ========
======== Resolving module 'chunked-dc' from '/tmp/example/test.ts'. ========
Module resolution kind is not specified, using 'Classic'.
File '/tmp/example/chunked-dc.ts' does not exist.
File '/tmp/example/chunked-dc.d.ts' does not exist.
File '/tmp/chunked-dc.ts' does not exist.
File '/tmp/chunked-dc.d.ts' does not exist.
File '/chunked-dc.ts' does not exist.
File '/chunked-dc.d.ts' does not exist.
======== Module name 'chunked-dc' was not resolved. ========
test.ts(3,34): error TS2307: Cannot find module 'chunked-dc'.
```

This clearly doesn't find the module because it does not look in the `node_modules` directory. So when I switch to `node` resolution kind:

```
$ tsc --noEmit -t ES2015 -m es2015 --moduleResolution node --traceResolution test.ts
======== Resolving type reference directive 'chunked-dc', containing file 'test.ts', root directory not set. ========
Root directory cannot be determined, skipping primary search paths.
Looking up in 'node_modules' folder, initial location ''
File 'node_modules/chunked-dc.ts' does not exist.
File 'node_modules/chunked-dc.d.ts' does not exist.
Found 'package.json' at 'node_modules/chunked-dc/package.json'.
'package.json' has 'types' field 'dist/chunked-dc.d.ts' that references 'node_modules/chunked-dc/dist/chunked-dc.d.ts'.
File 'node_modules/chunked-dc/dist/chunked-dc.d.ts' exist - use it as a name resolution result.
======== Type reference directive 'chunked-dc' was successfully resolved to 'node_modules/chunked-dc/dist/chunked-dc.d.ts', primary: false. ========
======== Resolving module 'chunked-dc' from '/tmp/example/test.ts'. ========
Explicitly specified module resolution kind: 'NodeJs'.
Loading module 'chunked-dc' from 'node_modules' folder.
File '/tmp/example/node_modules/chunked-dc.ts' does not exist.
File '/tmp/example/node_modules/chunked-dc.tsx' does not exist.
File '/tmp/example/node_modules/chunked-dc.d.ts' does not exist.
Found 'package.json' at '/tmp/example/node_modules/chunked-dc/package.json'.
'package.json' has 'types' field 'dist/chunked-dc.d.ts' that references '/tmp/example/node_modules/chunked-dc/dist/chunked-dc.d.ts'.
File '/tmp/example/node_modules/chunked-dc/dist/chunked-dc.d.ts' exist - use it as a name resolution result.
Resolving real path for '/tmp/example/node_modules/chunked-dc/dist/chunked-dc.d.ts', result '/tmp/example/node_modules/chunked-dc/dist/chunked-dc.d.ts'
======== Module name 'chunked-dc' was successfully resolved to '/tmp/example/node_modules/chunked-dc/dist/chunked-dc.d.ts'. ========
test.ts(3,34): error TS2306: File 'node_modules/chunked-dc/dist/chunked-dc.d.ts' is not a module.
```

Now it finds the npm module, but only cares about the types. The ES2015 module import itself does not happen.

Here's the relevant part in the `package.json` of chunked-dc:

```json
{
  // ...
  "main": "dist/chunked-dc.es5.min.js",
  "jsnext:main": "dist/chunked-dc.es2015.js",
  "module": "dist/chunked-dc.es2015.js",
  "types": "dist/chunked-dc.d.ts",
  // ...
}
```

**Comment by dbrgn** [comment] 2016-10-19 12:43
Note: If I import the TypeScript source directly:

```
/// <reference types="chunked-dc" />
import {Chunker, Unchunker} from "./node_modules/chunked-dc/src/main";
let c: chunkedDc.Unchunker = new Unchunker()
```

...then it works. But I'd like to be able to import the ES2015 module as well.

**Comment by mhegazy** [comment] 2016-10-19 17:00
So first of, you do not need `/// <reference types="chunked-dc" />`. this is needed if you want to include global libraries. e.g. `node`. since you can not say `import ... from "node"`.

> Now it finds the npm module, but only cares about the types. The ES2015 module import itself does not happen.

The TypeScript compiler will not rewrite your imports, if this is what you are asking about. if you write `import d form "foo"` in your .ts file you will get `import d from "foo"` in your output (with `--module ES2015`); it will not be rewritten to `import d from "./node_modules/foo/index.js"` for instance. 

The rational here is that module names are resource locators that should not be touched. what the compiler cares about is to find a matching `.d.ts` file to use to check your usage of the import against. i.e. what is the type of `Chunker` from `chunked-dc`. 

In your first example you are using `Classic` module resolution, (see http://www.typescriptlang.org/docs/handbook/module-resolution.html#classic for more details on how this works); `Classisc` does not look inside node modules. so it never looks at your `package.json`. and never looks at the value of `"types"` in your package.json, hence:
```cmd
======== Module name 'chunked-dc' was not resolved. ========
```

In the second, you have used `node` as a module resolution strategy. again see http://www.typescriptlang.org/docs/handbook/module-resolution.html#node for more details on how this works. this time the compiler thinks you are resolving node modules, so it looks at package.json, and it finds types.. so now it known that `Chunker` is actually declared in `/tmp/example/node_modules/chunked-dc/dist/chunked-dc.d.ts`. and then it can use that to check your uses of `Chuncker` correctly.

hence the line:

```cmd
======== Module name 'chunked-dc' was successfully resolved to '/tmp/example/node_modules/chunked-dc/dist/chunked-dc.d.ts'. ========
```

Now, i do not know what is in chunked-dc.d.ts, does not seem to be part of `chunked-dc@0.2.3`. but the error you are getting is telling you that the file is not actually a module:

```cmd
test.ts(3,34): error TS2306: File 'node_modules/chunked-dc/dist/chunked-dc.d.ts' is not a module.
```

A module, is a file with at least one top-level `import` or `export` statement. See http://www.typescriptlang.org/docs/handbook/modules.html for more details.


Hope that answers your question.

**Closed** 2017-04-24 20:37 UTC
Labels: Question
