### ISSUE TITLE
Watch occasionally doesn't apply all imports from ts file

### ISSUE THREAD

**Issue by RyanMitchellWilson** [Microsoft/TypeScript#21778] opened 2018-02-08 22:52 UTC
We just updated our project to use Typescript 2.7.1 and everything seems to be working for the most part. Although every so often the watch process doesn't apply all the imports from the ts file to the generated js file. This in turn causes my app to crash and I have to remove the compiled code and completely rebuild my js code to get the app back to a running state. 

Quick note: When I mention Watch I mean running `npm run tsc --pretty -- -w` to have it watching my files and recompiling my js whenever I change a ts file.

This has happened twice with the same file for me today. It seemed to happen when I added/ removed a comment from inside of an object that was in turn inside of a function like so:
```
const function foo() {
  return {
    bar: 'baz'
    // Some comment right here
  }
}
```

It seemed to have compiled incorrectly when I had the watch process running and then added/ removed the comment. I'm not positive if that is what causes the problem but that is the case that I have seen it happen in.

Here is a quick screenshot of my ts and compiled js files next to eachother:
![image](https://user-images.githubusercontent.com/11371200/36002309-e8f05a4e-0ce6-11e8-9351-248ff9a444ae.png)
Left is ts, right is compiled js; Don't mind all the red in the js file, my linter doesn't work properly with js

Notice how the ts file has this import line:
`import {Social as SocialModel, SocialState} from '../lib/shared/model/Social'`
but in the compiled js, that import is just missing.

This doesn't seem to happen every time but it has happened to me twice now today with watch being the only thing running that was recompiling my js.

Let me know if you'd need any more info on this, I'll try to respond as quickly as I can.

**Comment by RyanMitchellWilson** [comment] 2018-02-08 23:07
Just happened again, same file but all I did was edit a field in one on my objects, didn't have to be a comment. Seems to just be on save of a file, it will occasionally not apply all the imports.

**Comment by mhegazy** [comment] 2018-02-09 00:35
I suspect this is a duplicate of https://github.com/Microsoft/TypeScript/issues/21478. Can you give `typescript@next` a try and let us know if you are still seeing the issue?

**Comment by RyanMitchellWilson** [comment] 2018-02-09 16:18
Yep that seemed to work, thanks

**Comment by sheetalkamat** [comment] 2018-02-09 16:32
Closing this as its confirmed to be duplicate. Thank you.

**Closed by sheetalkamat** 2018-02-09 16:32 UTC
Labels: Duplicate
