### ISSUE TITLE
Go to Definition for a function takes you to the function keyword instead of the identifier

### ISSUE THREAD

**Issue by jramsay** [Microsoft/TypeScript#12230] opened 2016-11-14 20:51 UTC
Go to Definition for a function takes you to the function keyword instead of the identifier

![gotodef](https://cloud.githubusercontent.com/assets/8161247/20282301/0c302ef8-aa69-11e6-97ee-97f49bed011a.JPG)

**Comment by mhegazy** [comment] 2016-12-14 00:56
Duplicate of https://github.com/Microsoft/TypeScript/issues/12270

**Closed by mhegazy** 2016-12-14 00:56 UTC
Labels: Bug
