### ISSUE TITLE
Do not issue ` Left side of comma operator is unused and has no side effects` error on `(0, expr)` this-removing pattern

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#48163] opened 2022-03-07 21:08 UTC
Both our and babel's output emits `(0, expr)` in many places to unbind the `this` from the call that's about to be done. Ergo, the `0, expr` pattern is _not_ without side-effects, and is, in fact, a _very_ highly used pattern that we probably shouldn't issue an error on. It's probably OK to special-case the literal-zero LHS as a signal to silence the error.

**Comment by muuvmuuv** [comment] 2022-10-14 07:02
Damn, any workaround for this? I am in a NX Workspace, and we are trying to compile a custom executor.

```
 >  NX   ⨯ Unable to compile TypeScript:

   apps/entergon/webpack.config.ts:9:19 - error TS2695: Left side of comma operator is unused and has no side effects.

   9 const _default = (0, _webpack.createConfig)("entergon", (config)=>{
```

**Comment by shicks** [comment] 2022-12-21 17:46
This is a duplicate of #35866

**Comment by shicks** [comment] 2023-01-25 17:49
This should be able to be closed now that #51989 is merged.

**Comment by RyanCavanaugh** [comment] 2023-01-25 18:13
Thanks!

**Closed by RyanCavanaugh** 2023-01-25 18:13 UTC
Labels: Bug, Help Wanted, Domain: Error Messages
