### ISSUE TITLE
Control Flow Analysis w/ Inner Functions

### ISSUE THREAD

**Issue by lvpro** [microsoft/TypeScript#46320] opened 2021-10-12 15:44 UTC
# Bug Report

### 🔎 Search Terms

control flow analysis

### 🕗 Version & Regression Information

latest release, did not check prior versions

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/ATBmFcDsGMBcEsD2liwKYGdYAp6QA7iwBcwk4ANhcAD7BYBOeA5gJTADeAUCCPKMFwEiwAIQBecWUoV23XrwD0i4ACU0AWgCGGDPGYo8hWKkTAtkAJ7AKiZvGhaq1gCZp0DALZ54WB-VgmSGZBIyIAOlhEAFV8fDQGAGEdNGxWABpgd2hw1nCeBWBlYABJAVgAC18bPDRgaoY0T0QANzQXTMq6hIZEBmAAIzRbAHdgF0RMMkQTTwt+TFh8wvrhEykAcnQsDYBuLgKFaGQMRAo0cNtmIWNIxAAZRBGE5IxU1lZdopUAdT6Aaww+UOvGOkCwwBaTngLi06GAUjSCIAfJwQUcTmcLlcbhEoo9nkkUmlPt9gAB5AYAKzQcGA+EQungAwo1nIVGWhQAvvt0ZDobD0Gl9gouQUuUA)

### 💻 Code

```ts
  function test(input: null | string) {
    if (input !== null) {
      // Re-assign input to any logically deterministic string (input.toUpperCase(), etc.).
      // If this line is removed, the error below does not manifest.
      input = 'test';

      console.log(input.toLowerCase()); // Works.

      const validate = () => {
        console.log(input.toLowerCase()); // Object possibly null.
      };

      validate();
    }
  }
```

### 🙁 Actual behavior

The compiler thinks the value of input within the inner function validate() could possibly be null.  This occurs when input is re-assigned to a string in its containing block.  If the re-assignment is removed, no issue manifests.

### 🙂 Expected behavior

I do not expect "Object possibly null" here.  I would expect the compiler to track the fact input is still a string.

**Comment by jcalz** [comment] 2021-10-12 17:53
Maybe the bug report / suggestion template should start with a list of the top ten most frequently duplicated non-locked issues, and has a checkbox like "I have made sure that this issue is not a duplicate of the following issues:"  Not sure it would help, though.

**Closed as completed** 2021-10-15 18:00 UTC
Labels: Duplicate
