### ISSUE TITLE
Unexpected "An index signature parameter type must be 'string' or 'number'." error with string union type.

### ISSUE THREAD

**Issue by Strate** [Microsoft/TypeScript#8711] opened 2016-05-20 13:01 UTC
**TypeScript Version:** 

1.8.10

**Code**

```ts
type StringEnum = "one" | "two"

interface IndexedObject {
  [index: StringEnum]: boolean
}

```

**Expected behavior:**
No error

**Actual behavior:** 
error TS1023: An index signature parameter type must be 'string' or 'number'.

**Comment by evansb** [comment] 2016-05-20 14:44
Reproducible in latest master.

It seems that at the moment only `string` or number `keyword` can be used as index parameter type, so a simpler type alias below also fails.

```
type StringEnum = string;

interface IndexedObject {
  [index: StringEnum]: boolean
}
```

**Comment by Strate** [comment] 2016-05-20 14:52
> This is intended behaviour, see the grammar of Index Signatures

I think that Index Signatures could be extended without regression

**Comment by sandersn** [comment] 2016-05-20 15:48
Duplicate of #8336 (and some others, once I track them down).

**Closed by sandersn** 2016-05-20 15:48 UTC
