### ISSUE TITLE
Variable type information ignores mutation done from closure

### ISSUE THREAD

**Issue by safareli** [microsoft/TypeScript#41654] opened 2020-11-23 17:47 UTC
**TypeScript Version:**  v4.1.2

**Search Terms:**  mutation variable type closure

**Code**

```ts
function main(){
  // code will not compile - work properly, if instead you had this:
  // let foo : number | null = null as number | null
  let foo : number | null = null

  const setFoo = () => {
    foo = 1
  };

  setFoo();
  if(foo!= null) {
    absurd(foo)
  }
}


function absurd<T>(x: never):T {
  throw "oops";
}
```

**Expected behavior:**
It's expected to get error on absurd invocation: "Argument of type 'number' is not assignable to parameter of type 'never'.(2345)"

**Actual behavior:**
Code compiles.

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAWwIYzACgJQG8BQiiA9MYgDYCmUiwcciAXImCMgEaUBOiAPiyHLlEAXgFDEqAM4CO3PuPKEK1WvSazOPfqwljdS5RARSaU6gDF1YnKIB8iAkSJ0GYgIzKAvgG58y8ygrOBw-IhhgTFcAQn1BcmxHZSJUdikQLgATKPpsb3wvf3xQSFgESTSMzIAeABU7TAAPZjBKADdubEZapKIoAAsuOAB3RAAiegAHKTG-LyA)

**Related Issues:** no

**Comment by MartinJohns** [comment] 2020-11-23 17:50
Duplicate of #9998.

**Closed** 2020-11-23 17:52 UTC
