### ISSUE TITLE
Faulty type reasoning

### ISSUE THREAD

**Issue by apr-xaml** [Microsoft/TypeScript#18907] opened 2017-10-03 10:14 UTC
**TypeScript Version:**  2.5.3

**Code**

```
class A
{
    readonly AProp = 1;
}

 class B
 {
     readonly BProp = 1;
 }

 export function Test1()
{
    const x: (A | B) = new B();

    if (x instanceof A)
    {
        const prop = x.BProp;
    }
    else
    {
       const prop = x.BProp
    }

}
```
```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
Does not compile, because the property 'BProp' is not available on type A.
**Actual behavior:**
Compiles (VS2017, Ts.2.5.3)

**Comment by jcalz** [comment] 2017-10-03 14:14
This is probably working as intended.

It looks like [control flow type analysis](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#control-flow-based-type-analysis) narrows `x` to type `B` in the assignment, since it knows that the value assigned to `x` is definitely a `B`.  And the `x instanceof A` type guard narrows it further to `A & B`*, which has both `AProp` and `BProp`.   

If you want to prevent that kind of analysis, you can change the assignment to
```ts
const x = new B() as (A | B);
```
which forces the compiler to see the assigned value as an `A | B`, and you get your expected error.

*<sub>You might think that `A & B` should be `never` because `A` and `B` are classes unrelated by inheritance and you cannot make an object which is an instance of both classes at the same time.  But that would require [nominal typing](https://github.com/Microsoft/TypeScript/issues/202), which TypeScript doesn't currently have. </sub>

**Comment by RyanCavanaugh** [comment] 2017-10-03 17:17
@jcalz  is correct

**Comment by apr-xaml** [comment] 2017-10-04 10:04
_Mea culpa_, sorry all for false alert.

**Closed** 2017-10-04 17:18 UTC
Labels: Working as Intended
