### ISSUE TITLE
Allow to use post-fix expression operator "!" in object destructuring

### ISSUE THREAD

**Issue by Ky6uk** [Microsoft/TypeScript#27939] opened 2018-10-17 11:12 UTC
It's much convenient way to use post-fix operator "!" with object destructuring as

```ts
const { a!, b!, c! } = data;
```

instead of

```ts
const a = data.a!;
const b = data.b!;

data.c!();
```

because later in code we can use new variables many times and right now it required to use operator `!` for each usage of the variable in case when `strictNullChecks` is enabled.

**Comment by andy-ms** [comment] 2018-10-17 18:17
Duplicate of #17390

**Closed** 2018-12-13 18:00 UTC
Labels: Duplicate
