### ISSUE TITLE
Evaluate compile-time constants

### ISSUE THREAD

**Issue by n0izn0iz** [microsoft/TypeScript#31352] opened 2019-05-11 09:20 UTC
**TypeScript Version:**  3.5.0-dev.20190511

**Search Terms:** 

compile-time operations numerical constants

**Code**

> main.ts
```ts
const TWO: 2 = 1 + 1;
```

**Expected behavior:**

Transpiles without error

**Actual behavior:**

> $> tsc main.ts

> main.ts:1:7 - error TS2322: Type 'number' is not assignable to type '2'.

**Playground Link:**  

https://www.typescriptlang.org/play/#src=const%20TWO%3A%202%20%3D%201%20%2B%201%3B

**Related Issues:**

**Comment by n0izn0iz** [comment] 2019-05-11 09:37
Fun times:
```
const TWO: 2 = (1 + 3) as 2;
console.log(TWO);
```
Transpiles and executes, printing....
> 4

**Comment by MartinJohns** [comment] 2019-05-11 10:56
> Transpiles and executes, printing....

Type-assertions are a way to tell the compiler: "Trust me on this, I know what I'm doing and what this type is". The compiler trusts you. In this case the compiler resolves the type `number`, and you tell the compiler to assume it is the literal type `2`. You get the same result with `const two: 2 = 4 as 2;`.

**Comment by jcalz** [comment] 2019-05-12 18:34
Duplicate of #15645

**Comment by RyanCavanaugh** [comment] 2019-05-13 20:54
Without some motivating use cases this doesn't look compelling as an area of investment. The intersection of areas where you have a finite domain of numbers (literals) but want to do some *computation* to map to one of those members seems very small.

**Comment by n0izn0iz** [comment] 2019-05-14 10:36
```ts
const MESSAGE_BYTES = 32;
const BYTE_BITS = 8;
type SHA3Size = 224 | 256 | 384 | 512;
const SHA3_SIZE : SHA3Size = MESSAGE_BYTES * BYTE_BITS;
const hasher = SHA3(SHA3_SIZE)
```
I would understand if this not compelling enough.
Code is better than comments IMO. Also I guess my hatred for magic numbers is higher than the average.

**Comment by MartinJohns** [comment] 2019-05-14 10:44
@n0izn0iz That looks more like "Units of measure": #364

**Comment by RyanCavanaugh** [comment] 2019-05-14 15:55
`8 * 32` seems like a much worse way to write `256`, but I guess it's a matter of taste

**Comment by n0izn0iz** [comment] 2019-05-27 18:01
Even if MESSAGE_BYTES is a constant used in another part of the program?

**Comment by Morglod** [comment] 2021-04-02 21:16
https://github.com/Morglod/tsts

Currently working on comptime transformer

```ts
const numbers = [ 1, 2, 3, 4, 5, 6, 7, 8 ];
const result = comptime(() => {
    return numbers.reduce((total, x) => sum(total, x), 0);
});
```

to

```js
const result = (() => { return (36); })();
```

**Closed** 2023-06-21 01:34 UTC
Labels: Suggestion, Too Complex
