### ISSUE TITLE
Implement Enum Expression/Anonymous Enum  

### ISSUE THREAD

**Issue by nexusprime-here** [microsoft/TypeScript#60165] opened 2024-10-08 00:02 UTC
### 🔍 Search Terms

Enum, Enum Expression, Anonymous Enum

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Can use
```ts
class Transation {
    static Status = enum {
        Ok,
        Error
    }
}
```
Instead
```ts
enum TransationStatus {
    Ok,
    Error
}
```

### 📃 Motivating Example

This approach enhances code readability by grouping the enum directly with the class it relates to. It facilitates understanding of the context in which the enum is used and improves code organization.

### 💻 Use Cases

1. What do you want to use this for?
I want to use this feature to enhance code organization and readability by keeping related enums within their respective classes, making it easier to understand their context and usage.

2. What shortcomings exist with current approaches?
The current approach requires enums to be defined outside of their relevant classes, which can lead to a less cohesive structure and makes it harder to maintain and understand the relationship between the class and its associated enums.

3. What workarounds are you using in the meantime?
In the meantime, I’m creating external enums and using comments or documentation to indicate their relationship to specific classes. This is not ideal, as it increases cognitive load and may lead to confusion in larger codebases.

**Comment by whzx5byb** [comment] 2024-10-08 02:00
Duplicate of https://github.com/microsoft/TypeScript/issues/41744. Search terms: `enum expression in:title`.

A workaround is to export the enum in a namespace with the same name:
```ts
class Transation {}
namespace Transation {
    export enum TransationStatus { OK, Error }
}
```

If you want to define it as a private/protected static property, or use a

**Comment by nexusprime-here** [comment] 2024-10-08 11:03
> Duplicate of https://github.com/microsoft/TypeScript/issues/41744. Search terms: `enum expression in:title`.
> 
> A workaround is to export the enum in a namespace with the same name:
> ```ts
> class Transation {}
> namespace Transation {
>     export enum TransationStatus { OK, Error }
> }
> ```
> 
> If you want to define it as a private/protected static property, or use a non-valid variable name such as `Transation-Status`, you can define it in a static block (which is more verbose).
> ```ts
> class Transation {
>     private static TransationStatus;
>     static {
>         enum TransationStatus { OK, Error };
>         this.TransationStatus = TransationStatus;
>     }
> }
> ```

Interesting.. But I think this feature are useful yet

**Comment by RyanCavanaugh** [comment] 2024-10-08 15:21
> This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

This is a runtime feature 👆

**Comment by nexusprime-here** [comment] 2024-10-08 17:20
> > This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
> 
> This is a runtime feature 👆

How? Is a comptime feature

**Comment by RyanCavanaugh** [comment] 2024-10-08 17:36
"non-ECMAScript syntax with JavaScript output"

**Closed** 2024-10-11 01:32 UTC
Labels: Suggestion, Out of Scope
