### ISSUE TITLE
Decorator is in stage3 now.

### ISSUE THREAD

**Issue by ruojianll** [microsoft/TypeScript#49997] opened 2022-07-22 08:52 UTC
# Suggestion

## 🔍 Search Terms

decorator

## ✅ Viability Checklist

* [v ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [v ] This wouldn't change the runtime behavior of existing JavaScript code
* [v ] This could be implemented without emitting different JS based on the types of the expressions
* [ v] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [v ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Decorator in typescript is in stage 2. But newest version is in stage3. Should we update it?

https://github.com/tc39/proposal-decorators

**Comment by MartinJohns** [comment] 2022-07-22 09:35
Duplicate of #48885. Used search terms: `decorators in:title`

**Closed** 2022-07-22 11:17 UTC
