### ISSUE TITLE
Unnamed default exports don't work with `--t es6 --m commonjs`

### ISSUE THREAD

**Issue by joeduffy** [Microsoft/TypeScript#5844] opened 2015-12-01 01:00 UTC
Compiling the following code:

```ts
"use strict";
export default class {};
```
Using the command line `tsc --t es6 --m commonjs` produces illegal JavaScript:

```js
"use strict";
class {
}
exports.default = default_1
;
```
I realize this is a weird combination of switches, however it seems necessary to target current versions of Node.js/V8 that don't yet natively support ES6 modules.

**Comment by weswigham** [comment] 2015-12-01 01:15
[This conditional](https://github.com/Microsoft/TypeScript/pull/5648/files#diff-20a9fa4d3e9d09f60c275a3dda245867L5522) needs to be updated to emit the temp name if the class is an exported default class when not targeting ES6. Forgot about unnamed classes when adding tests in #5648.

While looking at it, it would probably also be a good idea to verify all of the results with functions and unnamed function expressions as well...

**Comment by vvakame** [comment] 2015-12-01 03:11
same as unnamed function.

```
$ tsc -v
Version 1.8.0-dev.20151130
$ cat sub.ts
export default function (name: string) {
    return `Hi! ${name}`;
}
$ tsc --target es6 --module commonjs sub.ts
$ cat "use strict";
function (name) {
    return `Hi! ${name}`;
}
exports.default = default_1;
```

**Comment by nmalaguti** [comment] 2015-12-01 16:39
This also appears to be a problem with named classes that are default exports.

```bash
$ tsc -v
message TS6029: Version 1.7.3
```

**example.ts**
```typescript
// example.ts
export default class Example {
    public get() {
        return 1;
    }
}
```

**subExample.ts**
```typescript
// subExample.ts
import Example from "./example";

export default class SubExample extends Example {
    public get() {
        return 3;
    }

    public foo() {
        return 2;
    }
}
```

```bash
$ tsc -t es6 -m commonjs example.ts subExample.ts
```

**example.js**
```javascript
// example.js
class Example {
    get() {
        return 1;
    }
}
exports.Example = Example;
```

**subExample.js**
```javascript
// subExample.js
var example_1 = require("./example");
class SubExample extends example_1.default {
    get() {
        return 3;
    }
    foo() {
        return 2;
    }
}
exports.SubExample = SubExample;
```

When run with node v5:
```
TypeError: Class extends value undefined is not a function or null
    at Object.<anonymous> (subExample.js:3:35)
```

**Comment by weswigham** [comment] 2015-12-01 18:43
That last bit duplicates #5594 and should be fixed in master. However your original issue still stands.

**Closed** 2015-12-01 22:36 UTC
Labels: Bug, High Priority

**Comment by mhegazy** [comment] 2015-12-01 22:40
@joeduffy and @nmalaguti can you give `typescript@next` a try tomorrow and let us know if the issue has been resolved.

**Comment by joeduffy** [comment] 2015-12-01 22:49
Thanks all, that was fast!  I'll give it a try in the AM.

**Comment by nmalaguti** [comment] 2015-12-02 15:53
This has resolved the issue with default named classes that I was seeing on 1.7 when using ts@next.

How does this interact with libraries compiled to commonjs using babel?

**Comment by joeduffy** [comment] 2015-12-02 18:45
LGTM, works great for me.

**Comment by mhegazy** [comment] 2015-12-02 19:01
> How does this interact with libraries compiled to commonjs using babel?

not sure i understand the question.

**Comment by nmalaguti** [comment] 2015-12-02 20:32
@mhegazy when babel emits code for es6 imports, it includes a method that looks for `__esModule` to determine whether to wrap the import in an object defining a `default`:

```javascript
"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _example = require("./example");

var _example2 = _interopRequireDefault(_example);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

class SubExample extends _example2.default {
    get() {
        return 3;
    }

    foo() {
        return 2;
    }
}
exports.default = SubExample;
```

If `example.ts` in my comment above is compiled with TypeScript, and `subExample.ts` is compiled with babel (simulating a babel project calling a TypeScript compiled project), then the compiled code for `subExample.ts` above breaks.

```
class SubExample extends _example2.default {
                                  ^

TypeError: Class extends value #<Object> is not a function or null
    at Object.<anonymous> (/Users/nmalaguti/git/ts-es6-commonjs/subExample.js:15:35)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/nmalaguti/git/ts-es6-commonjs/test.js:2:20)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

The variable `_example` is `{ default: { default: [Function: Example] } }` because `__esModule` was not set on it.

Is there a plan for how these will interop in the future?

**Comment by weswigham** [comment] 2015-12-02 21:18
Even if there isn't right now, as a workaround on your TS modules you can add the `__esModule` exported member yourself to force babel into doing the right thing with its interop require.

**Comment by mhegazy** [comment] 2015-12-03 01:41
@nmalaguti i think there is something else going on here. TypeScript compiler will emit the "__esModule", so compileing your `example.ts` [results in](http://www.typescriptlang.org/Playground#src=export%20default%20class%20Example%20%7B%0A%20%20%20%20public%20get()%20%7B%0A%20%20%20%20%20%20%20%20return%201%3B%0A%20%20%20%20%7D%0A%7D):

```js
// example.ts
var Example = (function () {
    function Example() {
    }
    Example.prototype.get = function () {
        return 1;
    };
    return Example;
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Example;
```

**Comment by nmalaguti** [comment] 2015-12-03 02:18
@mhegazy it looks like you targeted es5, not es6 (since the class was compiled into a function). The issue is when targeting es6 and using commonjs modules, the "__esModule" isn't emitted.

**Comment by mhegazy** [comment] 2015-12-03 02:37
I thought you were passing the es6 output into Babel...

**Comment by nmalaguti** [comment] 2015-12-03 02:46
Sorry for the confusion. The use case would be I write an npm module in TypeScript with ES6 features like generators. I use `tsc -t es6 -m commonjs` to compile and publish.

A consumer of my library npm installs it and wants to use it with babel in order to take advantage of ES6 features. In that case, when they import my module as a default, babel will compile that down in a way that is incompatible since "__esModule" is missing in the TypeScript output.

**Comment by weswigham** [comment] 2015-12-03 04:20
Ah! So the issue is that we don't emit our `__esModule` shim when targeting ES6 with nonES6 modules! I see!

**Comment by mhegazy** [comment] 2015-12-03 04:44
i have a fix out for this one: https://github.com/Microsoft/TypeScript/pull/5907

**Comment by weswigham** [comment] 2015-12-03 04:52
Oh man, I just put out #5908 with almost the same change.

**Comment by mhegazy** [comment] 2015-12-03 05:04
great mind..

**Comment by mhegazy** [comment] 2015-12-03 05:13
@nmalaguti give `typescript@next` a try later tonight and let us know if you are still running into issues.

**Comment by nmalaguti** [comment] 2015-12-04 03:07
Thanks @mhegazy and @weswigham. I was able to get things working smoothly with `typescript@next`.

**Comment by jaumard** [comment] 2016-05-27 14:09
Hum this was closed but I have the following problem : 

My TS file : 
```
'use strict'

import {Request, Response} from 'express'
import Controller from 'trails-controller'

/**
 * @module DefaultController
 *
 * @description Default Controller included with a new Trails app
 * @see {@link http://trailsjs.io/doc/api/controllers}
 * @this TrailsApp
 */
export default class DefaultController extends Controller {
  app: any;
  /**
   * Return some info about this application
   */
  info(req: Request, res: Response) {
    res.status(200).json(this.app.services.DefaultService.getApplicationInfo())
  }
}
```

The compiled result : 
```
'use strict';
const trails_controller_1 = require('trails-controller');
class DefaultController extends trails_controller_1.default {
    info(req, res) {
        res.status(200).json(this.app.services.DefaultService.getApplicationInfo());
    }
}
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = DefaultController;
```

How can I remove `.default` added in the extends and exports ? Because they not working in v8 I expect this output : 

```
'use strict';
const trails_controller_1 = require('trails-controller');
class DefaultController extends trails_controller_1 {
    info(req, res) {
        res.status(200).json(this.app.services.DefaultService.getApplicationInfo());
    }
}
module.exports = DefaultController;
```

**Comment by mhegazy** [comment] 2016-05-31 20:37
I wil have to look at the trails-controler definition to be able to help. You are importing it as a default export, so the output is what I would expect.

**Comment by jaumard** [comment] 2016-05-31 20:46
@mhegazy thanks. `trails-controller` is a node third module, a simple class : 

```
'use strict'

/**
 * Trails Controller Class.
 */
module.exports = class TrailsController {

  constructor (app) {
    Object.defineProperty(this, 'app', {
      enumerable: false,
      value: app
    })
  }

  /**
   * Controller configuration
   */
  static config () {
  }

  /**
   * Return the id of this controller
   */
  get id () {
    return this.constructor.name.replace(/(\w+)Controller/, '$1').toLowerCase()
  }

  get log () {
    return this.app.log
  }

  get __ () {
    return this.app.__
  }
}
```

If this module doesn't export his class the right way, what is the right way to export it ? I'll make a PR on it.
https://github.com/trailsjs/trails-controller

**Comment by mhegazy** [comment] 2016-05-31 21:01
your import should look like `import Controller = require("trails-controller");` instead. 

the reason is `import Controller from 'trails-controller'` imports the `default` export of the module, and this module is a pre-ES6 module, i.e. it does not have a `default` export.

**Comment by jaumard** [comment] 2016-05-31 21:18
@mhegazy thanks ! That's working (with `"noLib": true,`) because if I remove this flag it doesn't know about `trails-controller`. I try to create a `.d.ts` file but can't manage how to declare the class correctly :(
I try : 
```
declare module "trails-controller" {
  export default class Controller {
    app: any
  }
}
```
With or without `default` I get `ViewController.ts(27,47): error TS2507: Type 'typeof "trails-controller"' is not a constructor function type.`

**Comment by mhegazy** [comment] 2016-05-31 22:00
class Controler {...}
export=Controler;

**Comment by scott-wyatt** [comment] 2016-10-03 19:42
I'm trying to write a definition for the `trails-controller` that @jaumard mentioned, but I lack the experience.  Is this something close?
```ts
declare module TrailsController {
  export class TrailsController {
    app: {
      config: any;
      sitemap: any;
      routes: { path: string, config: {app?: any} }[];
      services: any;
    };
    log: any;
    id: any;
    __: any;
    config: any;

    constructor(app: any);
  }
}
declare module "trails-controller" {
  export = TrailsController;
}
```

**Comment by kitsonk** [comment] 2016-10-04 06:51
General questions should be on StackOverflow, Gitter or IRC, [but the following works](http://www.typescriptlang.org/play/#src=declare%20namespace%20TrailsController%20%7B%0D%0A%20%20class%20TrailsController%20%7B%0D%0A%20%20%20%20app%3A%20%7B%0D%0A%20%20%20%20%20%20config%3A%20any%3B%0D%0A%20%20%20%20%20%20sitemap%3A%20any%3B%0D%0A%20%20%20%20%20%20routes%3A%20%7B%20path%3A%20string%2C%20config%3A%20%7Bapp%3F%3A%20any%7D%20%7D%5B%5D%3B%0D%0A%20%20%20%20%20%20services%3A%20any%3B%0D%0A%20%20%20%20%7D%3B%0D%0A%20%20%20%20log%3A%20any%3B%0D%0A%20%20%20%20id%3A%20any%3B%0D%0A%20%20%20%20__%3A%20any%3B%0D%0A%20%20%20%20config%3A%20any%3B%0D%0A%0D%0A%20%20%20%20constructor(app%3A%20any)%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Adeclare%20module%20%22trails-controller%22%20%7B%0D%0A%20%20const%20TrailsController%3A%20TrailsController.TrailsController%3B%0D%0A%20%20export%20%3D%20TrailsController%3B%0D%0A%7D%0D%0A):

```typescript
declare namespace TrailsController {
  class TrailsController {
    app: {
      config: any;
      sitemap: any;
      routes: { path: string, config: {app?: any} }[];
      services: any;
    };
    log: any;
    id: any;
    __: any;
    config: any;

    constructor(app: any);
  }
}

declare module "trails-controller" {
  const TrailsController: TrailsController.TrailsController;
  export = TrailsController;
}
```
