### ISSUE TITLE
Typescript Tools 1.8.6 breaks publish to File System in VS2015

### ISSUE THREAD

**Issue by simonfanz** [Microsoft/TypeScript#7741] opened 2016-03-31 03:59 UTC
**Summary**

Apologies if this is not the right place to log this, but I seem to have the exact same issue as described here:

https://github.com/Microsoft/TypeScript/issues/5894

but with VS2015 and the latest release of Typescript tools (1.8.6)

I've attached a sample project illustrating the issue. Essentially it's an empty web application with a single app.ts typescript file in a src folder, and a tsconfig.json file redirecting the output to a folder wwwroot. 

**TypeScript Version:** 
1.7.5 (according to tsc -v from commandline - not really sure if Visual studio uses the same?)
Typescript tools for Visual Studio: 1.8.6.0

**Code**

```
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "outDir": "./wwwroot/"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}
```

[TSTest.zip](https://github.com/Microsoft/TypeScript/files/196950/TSTest.zip)

**Expected behavior:**

I can publish the project using File System publish method

**Actual behavior:** 

The publish fails with the error message:

Copying file src\app.js to obj\Release\Package\PackageTmp\src\app.js failed. Could not find file 'src\app.js'.

**Comment by mhegazy** [comment] 2016-03-31 18:14
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/7322

and caused by the same underling issue described in https://github.com/Microsoft/TypeScript/issues/7247. the problem is that the build targets that pass the expected outputs to publishing pipeline does not read the tsconfig.json contents, it only reads the contents in the project file XML configuration, and this it thinks the output fro `src\app.ts` should be `src\app.js` and not `wwwroot\app.js`.

**Comment by simonfanz** [comment] 2016-03-31 20:44
Thanks, feel free to close this issue.

As a workaround I've included my output folder and output javascript files in the project, then I can do a normal build (using tsconfig.json file for the typescript settings) and then to publish I add the following entry to the first PropertyGroup in the csproj file:

<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>

A bit ugly and manual, but at least it works...  I'd be interested if there are any easier workarounds though.

**Comment by mhegazy** [comment] 2016-03-31 20:48
sorry about that. hopefully we have a fix in a nightly nuget package soon.

**Closed by mhegazy** 2016-03-31 20:48 UTC
Labels: Duplicate

**Comment by StefanKern** [comment] 2016-10-12 10:02
Well it's closed an fixed, but I still spent a few hours debugging it.
What solved it was installing the latest Typescipt plugin for VS 2015. 

It can be found here: https://github.com/Microsoft/TypeScript/releases

Direct download link: https://www.microsoft.com/en-us/download/details.aspx?id=48593
