### ISSUE TITLE
Boolean value should be infered boolean instead of false

### ISSUE THREAD

**Issue by Xstoudi** [microsoft/TypeScript#40745] opened 2020-09-24 12:46 UTC
**TypeScript Version:**  3.3.3 to Nightly

**Search Terms:**

- Boolean
- Iteration
- Inference

**Code**
```ts
let value = false;

['a', 'b', 'c'].forEach(str => {
  if (str === 'b') {
    value = true;
  }
})

console.log(value)
```

**Expected behavior:** Type inspection (mouse on variable) should say that `value` type is a `boolean` as the variable can clearly take both `true` and `false` values. 

**Actual behavior:** It says `value` can only be `false`, even after conditionnaly set `value` to `true`.

**Playground Link:** https://www.typescriptlang.org/play?ts=4.0.2#code/DYUwLgBAbghsCuIIF4IDM4GcQG4BQeA2gOQzEA0ExARhVQMbEC6AdGgPYBOAojPQBYAKTGE4oAfBADeeCBACWaCMNEpkqGsQCU02XOhxEKCKMT45AXzwWtBeuwB2mdqBbB2Ac0GwEIW0A

**Related Issues:** Not found, let me know if there is already one.

**Comment by MartinJohns** [comment] 2020-09-24 13:00
Duplicate of #9998.

**Closed** 2020-09-24 13:08 UTC
