### ISSUE TITLE
tsc emits `__esModule` even for `ModuleKind.None`

### ISSUE THREAD

**Issue by CnSimonChan** [Microsoft/TypeScript#14351] opened 2017-02-28 02:46 UTC
**TypeScript Version:**  2.3.0-dev.20170227

**Code**

```` JavaScript
const typescript = require("typescript");

const result = typescript.transpileModule(`let s:string = "string"`, {
    compilerOptions: {
        target: "es5",
        module: typescript.ModuleKind.None // I don't need module!!
    }
});

console.log(result.outputText)
````

**Expected behavior:**

```` JavaScript
"use strict";
var s = "string";
````

**Actual behavior:**

```` JavaScript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true }); // I cannot run this in browsers!!
var s = "string";
````

I believe it's caused by #13709 that fixed #13709, but `ModuleKind.None` also uses CommonJS emit routine ([module.ts#L14](https://github.com/Microsoft/TypeScript/blob/ef25b25c1fb64602f99a6278f24d42c1b6d53d90/src/compiler/transformers/module/module.ts#L14)) so it's also affected.

**Comment by mhegazy** [comment] 2017-02-28 03:18
TranspileModule treats the input as a module regardless of the module option; hence the name of the function.

**Comment by HerringtonDarkholme** [comment] 2017-02-28 03:37
`transpileModule` transpiles *module* as the name. To run in browser you can simply declare a global variable `exports`.

**Comment by CnSimonChan** [comment] 2017-02-28 03:42
@mhegazy Is there any way not to compile as modules using compiler API?

@HerringtonDarkholme You mean declare `exports` in every file?

**Comment by Johnz86** [comment] 2017-02-28 08:18
I have similar problem. 

Today I made an attempt to update our typescript version from 2.1.4 to 2.2.1. We have a stack with electron/react/redux/typescript.
After update to newer version Object.defineProperty(exports, "__esModule", { value: true }); appeared in compiled files. And we get  Uncaught ReferenceError: exports is not defined in browser window. 

This forced me to roll back to previous version, where I do not have this additional line after compilation.

**Comment by rhysd** [comment] 2017-03-01 00:58
I have this problem too on Electron app.

> To run in browser you can simply declare a global variable exports.

It looks too hacky... TypeScript compiler inserts `Object.defineProperty(...)` line just after `use strict`. So adding `(window as any).exports = {}` at head of file does not work.
Even adding `var exports = {}` to head of file is also impossible because of bellow error:

```
> tsc --pretty -p .


4 var exports = {};
      ~~~~~~~

renderer/index.ts(4,5): error TS2441: Duplicate identifier 'exports'. Compiler reserves name 'exports' in top level scope of a module.
```

**Comment by mhegazy** [comment] 2017-03-01 01:06
Just for clarification, the code resulting from traspileModule is not a module? you do not use WebPack/browserify? nor do you wrap the result in AMD/UMD functions? so how did you handle imports in the past?

**Comment by rhysd** [comment] 2017-03-01 01:10
My tsconfig may be wrong. Below is mine:

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "removeComments": true,
    "preserveConstEnums": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noEmitOnError": true,
    "strictNullChecks": true,
    "target": "es2015",
    "sourceMap": true
  },
  "include": [
    "main/**/*.ts",
    "renderer/**/*.ts",
    "webview/**/*.ts",
    "typings/**/*.d.ts"
  ]
}
```

from [here](https://github.com/rhysd/Tui/blob/master/package.json).

I'm not using browserify, webpack and AMD/UMD functions. Just compiled with `tsc` and importing it with `require()` function (commonjs).

**Comment by mhegazy** [comment] 2017-03-01 01:12
If you are on node, then `module.exports` exist, or am i missing something?

**Comment by rhysd** [comment] 2017-03-01 01:23
yeah, `module.exports` exists, but `exports` does not exist. So the line causes an error.

**Comment by rhysd** [comment] 2017-03-01 01:42
I found that I need to use `require('./index.js')` rather than `<script src="./index.js">` to handle it as commonjs code... I'm sorry.

**Comment by iradul** [comment] 2017-03-01 14:58
I have a similar issue with PhantomJS when running JS transpired from TS. There should be an option to totally disable generation of this line:
```js
Object.defineProperty(exports, "__esModule", { value: true }); // I cannot run this in browsers!!
```

**Comment by iradul** [comment] 2017-03-01 15:13
Workaround is to add for example `export = 0;` at the top of your TS file. Got it from [here](https://github.com/Microsoft/TypeScript/blob/bc6860428cb7f7338750ee8e77d6f405da28ec6c/src/compiler/transformers/module/module.ts#L386).

**Comment by kenotron** [comment] 2017-03-02 00:57
This is a bug. We create a tiny bootstrap .ts file to be included inside a page itself, such a generated .js file should not rely on any modules. Yet, we're stuck with 2.1 until this is fixed.

**Comment by mhegazy** [comment] 2017-03-02 01:00
> This is a bug. We create a tiny bootstrap .ts file to be included inside a page itself, such a generated .js file should not rely on any modules. Yet, we're stuck with 2.1 until this is fixed.

Do your files have any `imports` or `exports`?

**Comment by pe8ter** [comment] 2017-03-02 01:22
Whether or not you call this a bug it is still a breaking change in a minor version. We have to pin back at version 2.1.x until we figure out what to do.

**Comment by mhegazy** [comment] 2017-03-02 02:47
The behavior was there for modules with `export default`. now it is for all modules. 

I would like to get some clarity on the issue and why was it working before, and breaking now.

**Comment by pe8ter** [comment] 2017-03-02 03:21
Apologies, I missed important context. This ticket is explicitly about `transpileModule` whereas my issue is with the compiler in general. The compiler always emits the `__esModule` line when before 2.2 it never did, which is a breaking change. ES modules export immutable bindings and our tests use Jasmine spies in a few cases which no longer work since we can't modify imported symbols.

**Comment by mhegazy** [comment] 2017-03-02 03:28
The compiler did this before, but only for `default` exports. the new change expands the emit for this property for all modules.. this is inline with other transpilers as well.

```ts
c:\test>type a.ts
export default 0;

c:\test>tsc --v
Version 1.8.10

c:\test>tsc a.ts --m commonjs  --t es5

c:\test>type a.js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = 0;
```

We sure can add this to the breaking change documentation for the TS 2.2 release.

**Comment by pe8ter** [comment] 2017-03-02 04:27
I had no idea that that was a thing. Yeah, it should be listed in the docs as a breaking change.

**Comment by kenotron** [comment] 2017-03-02 18:18
Okay in reading this I found out that we do exports. Removing this now gets rid of this generated code. Some documentation around this would be helpful.

**Comment by fatcerberus** [comment] 2017-03-04 18:20
I just noticed that passing `ModuleKind.None` to `ts.transpileModule()` results in the following diagnostic being emitted by my build tool:
```
   transpiling '@/scripts/main.js'...
      E: TS5047: Option 'isolatedModules' can only be used when either option '--module' is provided or option 'target' is 'ES2015' or higher..
```

Despite the error diagnostic, a CommonJS module (which is not what I wanted) is emitted anyway.

**Comment by mhegazy** [comment] 2017-03-06 23:11
If your code does not have any `import` and/or `export`, but you still see `__esModule` defined, then it is a bug, and it is tracked by https://github.com/Microsoft/TypeScript/issues/14456, and should be fixed by https://github.com/Microsoft/TypeScript/pull/14493.

**Comment by fatcerberus** [comment] 2017-03-06 23:14
Is the `isolatedModules` error (posted above) when using `ModuleKind.None` fixed too?

**Comment by mhegazy** [comment] 2017-03-06 23:35
> Is the isolatedModules error (posted above) when using ModuleKind.None fixed too?

Not sure i see why this is relevant. the error is accurate.

**Comment by fatcerberus** [comment] 2017-03-06 23:49
You're right, of course, `transpileModule()` only compiles modules by design.  The wording is maybe a bit confusing though, because `isolatedModules` is added internally by the implementation of `transpileModule()`.  In my case I had to read the TypeScript source to find out the cause of the error; my options didn't explicitly include `isolatedModules`.

Passing anything other than `ModuleKind.None` to the function makes the error go away, which also isn't obvious from the error message.  So maybe the wording could be improved?

**Comment by mhegazy** [comment] 2017-03-06 23:57
Sure. feel free to send a PR with your proposed error message enhancements.

**Comment by hansrwindhoff** [comment] 2017-04-14 04:12
So in my case, the library I am using (npm: [type-check](https://www.npmjs.com/package/type-check)) provides its own require function when used inside the browser, 
```
<body>
    <script src="./type-check.js"></script>
    <script src="./index.js"></script>
</body>
```
It does that to enable importing the library via require. Thereby typescript is also happily finding the @types declaration file in node_modules. 

In index.ts one can now...
```
import * as tchecker from 'type-check';
```
With `module: 'none' `setting in tsconfig.json, the compiler emits: 
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tchecker = require("type-check");

```

So to make this work, one has to add the exports object, which is a minor nuisance:

```

<body>
    <script src="./type-check.js"></script>
    <script>
        var exports = {};
    </script>
    <script src="./index.js"></script>

</body>
```
Any ideas?

**Comment by fatcerberus** [comment] 2017-04-14 04:17
@hansrwindhoff Your issue was fixed in #14493 I believe; I assume the fix will be in the next TS release.

**Comment by hansrwindhoff** [comment] 2017-04-14 04:19
Hi Bruce, thanks for the note, I read just now read that it will be
fixed in 2.3. Thanks again

**Closed** 2017-05-01 17:19 UTC
Labels: Working as Intended

**Comment by evil-shrike** [comment] 2017-05-12 11:48
I've upgraded my project with AMD/ES3 from TS 2.1.6 onto 2.3.2 and now TS emits `exports.__esModule = true;` for every files in the project.

Resulting files are AMD:
```js
define(["require", "exports", ... ], function (require, exports, ... ) {
    "use strict";
    exports.__esModule = true;
 });
```
I can't say the new behavior breaks anything, but I can't understand why this field `__esModule` is needed for AMD modules. Is it on purpose? 

My tsconfig.json:
```json
{
	"compileOnSave": true,
	"compilerOptions": {
		"module": "amd",
		"target": "es3",
		"sourceMap": true,
		"noEmitHelpers": true,
		"experimentalDecorators": true,
		"baseUrl": ".", // This must be specified if "paths" is.
		"paths": {
			// map runtime paths to compile-time paths
			"lib/*": [ "src/lib/*" ],
			"modules/*": [ "src/modules/*" ],
			"vendor/*": [ "src/vendor/*" ]
		},
		"typeRoots" : ["src/typings"]
	},
	"include": [
		"src/**/*.ts",
		"src/**/.*.ts", // TS ignores file names starting with dot by default
		"tests/**/*.ts",
		"tests/**/.*.ts"
	]
}
```

**Comment by zaggino** [comment] 2017-05-12 12:00
I've noticed that this `exports.__esModule` doesn't get emitted when you don't use any imports/exports, which is great. But I've also noticed it gets emitted when you only use typing imports (which get removed during compilation) so you get `exports.__esModule` even without any imports/exports in the file. Is this intended ? @mhegazy

**Comment by aluanhaddad** [comment] 2017-05-14 02:17
@zaggino The `__esModule` flag is important for interoperability between various loaders and transpilers.

**Comment by zaggino** [comment] 2017-05-14 03:02
@aluanhaddad But in one of my browser use-cases (quite edge one), this is a breaking change, could this be changed to:
```
if (typeof exports !== "undefined") Object.defineProperty(exports, "__esModule", { value: true });
```
otherwise this breaks in browsers with
```
VM8188:1 Uncaught ReferenceError: exports is not defined
```

**Comment by aluanhaddad** [comment] 2017-05-14 05:52
But it was never valid in the first place. If you are not writing a module then you can't use module syntax and if you are writing a module then you need a loader or a packager. Type declarations are available globally if the module that they describe can be loaded globally. If not the type declaration needs to be revised.

**Comment by zaggino** [comment] 2017-05-14 07:49
@aluanhaddad I'm not writing a module but I'm using module syntax to reference my interfaces which are defined in another file. So the resulting file doesn't have any imports itself although the source has, as all interface imports get removed from the result. It'd be great if `Object.defineProperty(exports` could be removed too if only interface imports are present in the file.

Or is there another way of using interfaces defined in a different file that I could use for this?

**Comment by aluanhaddad** [comment] 2017-05-17 23:16
Yes, there are several options.

You can not export them, effectively making them global. Then they will be available in the global type namespace.
```ts
// global
interface Named {
    name: string;
}
interface Identity {
    id: number;
}
```

You can place them in a namespace, export them from that namespaces, but not export the namespace itself.
```ts
// global
declare namespace interfaces {
    export interface Named {
        name: string;
    }
    export interface Identity {
        id: number;
    }
}
```

You can also follow the UMD pattern which is used by most @types packages to export the name space for used by modules and make it available globally at the same time for non module consumers.
```ts
// UMD globally available from scripts but requiring import from modules
export = interfaces;
export as namespace interfaces;
declare namespace interfaces {
    export interface Named {
        name: string;
    }
    export interface Identity {
        id: number;
    }
}
```

**Comment by TheFirstLairron** [comment] 2017-05-18 00:37
Okay, I think I understand what is going on in this thread, but could anyone help me figure out how to get this fixed? I have a very simple script:
```typescript
import * as $ from "jquery";

$(document).ready(() => {
    setTimeout(() => {
        $("#error-location").fadeOut(2000);
    }, 3000);
});
```

but it is being compiled to this, which has the same issue as above:
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true }); // Offending Line
var $ = require("jquery");
$(document).ready(function () {
    setTimeout(function () {
        $("#error-location").fadeOut(2000);
    }, 3000);
});
//# sourceMappingURL=site.js.map
```

What is the recommended way of fixing that offending line? I am using VS2017 with just a tsconfig.json in an aspnet core mvc project which uses tsc 2.2.

**Comment by goktugyil** [comment] 2017-11-01 13:01
Are we not supposed to use import in the client side? I've tried everything I've found and nothing works, I just get different problems. 

I'm using Typescript 2.4.1 with Webstorm. 

I've experimented with different config files and got different results like:

```
import { hey } from "./a2";
var a2_1 = require("./a2");
Object.defineProperty(exports, "__esModule", { value: true });
```

All of these failed to work.

**Comment by aluanhaddad** [comment] 2017-11-01 15:07
@goktugyil using `import` in client side code is a very common practice. Leaving aside the nascent native support for modules available in a small number of browsers, using them in a browser environment implies a transpilation step.

Since you are using TypeScript, you are already transpiling your code in order to execute it on JavaScript runtimes. However, that step is necessary but not sufficient. In addition to using a transpiler, you also need to incorporate a module tool, such as a loader or a bundler, into your application.

Then you can configure TypeScript to transpile your code into a format recognized by that tool or, in some cases, use a plugin that integrates TypeScript into that tool.

Some options include RequireJS, Browserify, SystemJS/JSPM, Webpack, and Rollup.

**Comment by l5oo00** [comment] 2018-05-11 09:57
I think `if (typeof exports !== "undefined") exports.__esModule = true;` is better.
