### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Khirmati** [microsoft/TypeScript#38413] opened 2020-05-08 09:13 UTC
Please help me i a new in Angular 9 .I am getting below error.
ERROR in TypeError: Cannot read property 'flags' of undefined
    at resolveAlias (E:\Practice-Biru\Project3\node_modules\typescript\lib\typescript.js:36513:37)
    at checkAliasSymbol (E:\Practice-Biru\Project3\node_modules\typescript\lib\typescript.js:64502:26)
    at checkImportBinding (E:\Practice-Biru\Project3\node_modules\typescript\lib\typescript.js:64534:13)
    at checkImportDeclaration (E:\Practice-Biru\Project3\node_modules\typescript\lib\typescript.js:64552:29)
    at checkSourceElementWorker (E:\Practice-Biru\Project3\node_modules\typescript\lib\typescript.js:64961:28)
    at checkSourceElement (E:\Practice-Biru\Project3\node_modules\typescript\lib\typescript.js:64800:17)
    at Object.forEach (E:\Practice-Biru\Project3\node_modules\typescript\lib\typescript.js:317:30)
    at checkSourceFileWorker (E:\Practice-Biru\Project3\node_modules\typescript\lib\typescript.js:65123:20)
    at checkSourceFile (E:\Practice-Biru\Project3\node_modules\typescript\lib\typescript.js:65091:13)
    at getDiagnosticsWorker (E:\Practice-Biru\Project3\node_modules\typescript\lib\typescript.js:65179:17)
    at Object.getDiagnostics (E:\Practice-Biru\Project3\node_modules\typescript\lib\typescript.js:65165:24)
    at E:\Practice-Biru\Project3\node_modules\typescript\lib\typescript.js:98703:85
    at runWithCancellationToken (E:\Practice-Biru\Project3\node_modules\typescript\lib\typescript.js:98665:24)
    at getBindAndCheckDiagnosticsForFileNoCache (E:\Practice-Biru\Project3\node_modules\typescript\lib\typescript.js:98691:20)
    at getAndCacheDiagnostics (E:\Practice-Biru\Project3\node_modules\typescript\lib\typescript.js:98956:26)
    at getBindAndCheckDiagnosticsForFile (E:\Practice-Biru\Project3\node_modules\typescript\lib\typescript.js:98688:20)

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

**Comment by alan-agius4** [comment] 2020-05-08 12:26
Duplicate of https://github.com/angular/angular/issues/36995

The root cause seems to be a bug in the `@angular/compiler-cli`

**Comment by RyanCavanaugh** [comment] 2020-05-08 20:50
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Closed by RyanCavanaugh** 2020-05-08 20:50 UTC
Labels: External
