### ISSUE TITLE
Question, 'any' type compatible type to Object type.

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#1944] opened 2015-02-05 15:46 UTC
I want a type similar to 'any' but can be initialized only with Object compatible type.
Is it possible to do this ?

```typescript
var a : {any};

a.x = 1; // OK
a["x"] = 1; // OK
a = {}; // OK
a = 1; // Error !
```

The workaround is to use indexer, but then syntax 'a.x' doesn't work.

```typescript
var a: {[key: string]: any;};

a = 1; // Error
```

**Comment by danquirk** [comment] 2015-02-06 00:05
I think this is roughly a duplicate of the request here #1809.

**Closed by danquirk** 2015-02-06 00:05 UTC

**Comment by NN---** [comment] 2015-02-06 00:21
Yes, exactly what I want.
Thanks
