### ISSUE TITLE
Union type narrowing doesn't work on `object | OtherType`

### ISSUE THREAD

**Issue by maple3142** [microsoft/TypeScript#37405] opened 2020-03-15 15:19 UTC
**TypeScript Version:** v3.9.0-dev.20200313 

**Search Terms:** union type narrow assign

**Code**

```ts
class Callable {
    call(): void { }
}
function test(arg: object | Callable) {
    if (!(arg instanceof Callable)) {
        arg = new Callable()
    }
    arg.call() // Property 'call' does not exist on type 'object | Callable'.
}
function test2(arg: { a: () => void } | Callable) {
    if (!(arg instanceof Callable)) {
        arg = new Callable()
    }
    arg.call()
}
function test3(arg: string | Callable) {
    if (!(arg instanceof Callable)) {
        arg = new Callable()
    }
    arg.call()
}
```

**Expected behavior:**
I can correctly use `obj.call()` in `test`, `test2`, `test3`.

**Actual behavior:**
TypeScript complains in `test` that `Property 'call' does not exist on type 'object | Callable'.`.

**Playground Link:** https://www.typescriptlang.org/play?ts=next#code/MYGwhgzhAEDCYnAIxAU2gbwLAChr+mARAAoBKALmgDcB7ASwBNNoBfXdnAMwFcA7YABd6tPtEGoIgkmABOAcyq0kAK1RDoAHzjEwKVGUy4C0el2gkAhDIWm+UsANS1z8RHrRlD2PCYJz5aABeaD5UAHcdd31yYwJOEwCAOiJEcj8MzKzsrIB6XOgABVlaAAdUWUEAT2gAclSQWuhGWklQ2kFoVAAPeiloUXEq8rrlNQ1tN2Q0WqSOXF4BYUGJKQAmG0UWMCp0oIA+GgZmVi0o6YMjX3wzC2sAuwcnF3OPA284jIeQsMipt9i1zYn2gyQagM4iyEIjEq0EAGZNlQpLJ6HxApNdPoPkDblZNo9BI5gM5XFjPDist9QhFXjEyCCEv4FCliBDcEA

**Related Issues:**

**Comment by MartinJohns** [comment] 2020-03-15 18:01
Looks like another duplicate of #9998.

**Comment by maple3142** [comment] 2020-03-16 10:49
@MartinJohns I can't find a code in #9998 that is similar to my provided code. If you know which example does it correspond to, please tell me.

**Comment by RyanCavanaugh** [comment] 2020-03-16 18:14
`object | Callable` is just a roundabout way to write `object` due to subtype reduction, so this type doesn't narrow the way you'd expect it to.

**Comment by maple3142** [comment] 2020-03-23 11:54
@RyanCavanaugh Although `arg` is object, but `obj` can only be `Callable` after the `if` block right? So this is just tsc doesn't know about that?

**Closed** 2021-06-01 22:26 UTC
Labels: Design Limitation
