### ISSUE TITLE
ReadonlyArray.some does not perform type narrowing

### ISSUE THREAD

**Issue by JUSTIVE** [microsoft/TypeScript#47574] opened 2022-01-24 04:51 UTC
# Bug Report

### 🔎 Search Terms

type narrowing, array, Array.some

### 🕗 Version & Regression Information

seems to be every version of typescript shows this behavior

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBASglgcwBbADwBUB8UC8UDeAUFFAM5wAmE64EAXAETzLAMA0hAvoYaJFABkIAMzRZcBYmUrVajIaPZSAbgEMANgFd66Ljz7QAyjIzY8zFKYA+CsZh7DNAOwDGwOAHsnUOKQt2ACnIqADUNbTpjKlMASjpgiDCtaF9YREssIhIAJwhgTWzvBKTtADoEmkgcaoByfxq9QkdXdy8oVScQf1MgmRKIAEFs7NUQOhgIVQovdRAhkZBUKIhTTDji8MHh0Z9SWEnpp1n50dRurEwsqFz8wulQzZOQco8AWwgA338Yxua3T28mlIqgQHxiVxcXlIwFgAGZxuk0E5NK8AEYQbJmAgVORMREMbgkSFOaGCACsdFsqGRaIxWPwOMg8hErDYamSdDJhKgxNJMAA7AiWNSUejMRIGTJKvQ8SwCTwSAB6RVUFzqVS5KDs7R7VR7CZTGZzbYgHzeDzZKjZKDADxQMC5ZQQJww14eChwYSm97vMWkKS8mHaiCkcYHI1PJYmGlizBYgDaMFhbAEZLYAoAulJlZNsrNrnkCt44N4XHroB5hO1OlBKzakBBXrs0iwpJ6Ah0uoiAsHSDEYgXbt5kep1AqoMqNOooD6-WaoAxewwyEgPJp1BQoOjBCyRbTxQ3chwlYrUZoYQZSC5snAwDCy04nB4YcI4OpgBja+f7R5SORUW+cDuCGtZVrOn51r2PJrhuW7QN0MZ0lINxFlqmykKUryqGAAQAB44JguGlMGPycEAA)

### 💻 Code

I was writing some kind of type narrowing/validating code with Arrays, and found out that array.some could not narrow types!

I embedded playground code with comments and also pasted it down here.
P.S. I already saw #14963 and it says its already fixed with ReadonlyArray, but not worked for me

```ts
function isRight<T>(sideValue:Side<T>):sideValue is Right<T>{
  return sideValue.sideType==='Right'
}

function anyRight<T>(sideValueArray:ReadonlyArray<Side<T>>):sideValueArray is ReadonlyArray<Right<T>>{
  return sideValueArray.some(isRight)
}

function usage(){
  const R3:Right<number> = {sideType:"Right"}
  const L5:Left<number> = {sideType:"Left",value:5}
  const R7:Right<number> = {sideType:"Right"}

  //declare values as ReadonlyArray in order to prevent modify memebers
  const values:ReadonlyArray<Side<number>> = [R3,L5,R7]
  //early return in case of any of them is Right
  if(anyRight(values)) return null

  //all members in "values" should be Left<number> here,
  //but typescript cannot filter out possibilities of member of values could be Right<number>
  return values.map(x=>x.value)
}
```

### 🙁 Actual behavior

ReadonlyArray.any | ReadonlyArray.some could not filter out specific types with given typeguard functions

### 🙂 Expected behavior

ReadonlyArray.any | ReadonlyArray.some should filter out specific types with given typeguard functions

**Comment by MartinJohns** [comment] 2022-01-24 06:27
Duplicate of #46894. There is no way for TypeScript to type an array where **one** of the values is of a specific type.


> P.S. I already saw #14963 and it says its already fixed with ReadonlyArray, but not worked for me

That issue is about `every`, not about `some`.

**Comment by JUSTIVE** [comment] 2022-01-24 06:33
Yes, of course, there's no way that which member of an array is of a specific type, but from the code above, in case any of member is specific type then returned, lines below the return statement must not be the specified type.

**Comment by RyanCavanaugh** [comment] 2022-01-24 19:14
To supplement @jcalz 's correct response, the key thing is that user-defined type guards (UDTGs) can narrow unions (including in the false branch), but `Array<Side<T>>` is not a union type - it's a type containing a union, which is a different beast. UDTGs can also narrow via intersection, which is why `allLeft` works.

The narrowing of `Array<A | B>` to `Array<B>` by excluding `A` is sound for arrays because of what arrays do, but isn't universally valid for an arbitrary `T<U | V>`.

**Comment by JUSTIVE** [comment] 2022-01-24 19:24
@jcalz Thanks for your kind explanations. First of all, I confused `some` with `any` as you mentioned, so I changed it. thanks.
@RyanCavanaugh also thanks for your kindness. if I want to separate `Array<a|b>` with UDTGs, should I write UDTG like
`(x:Array<a>|Array<b>)=>x is Array<a>`?

**Closed** 2024-02-24 00:19 UTC
Labels: Design Limitation
