### ISSUE TITLE
Type narrowing on a property with disjoint set of values

### ISSUE THREAD

**Issue by tinchou** [Microsoft/TypeScript#16580] opened 2017-06-16 16:41 UTC
**TypeScript Version:**  2.3.4 / Current playground version

**Code**

```ts
export interface AuthenticatedProfile {
    readonly userId: string;
    readonly name: string;
}
export interface AnonymousProfile {
    readonly userId: undefined;
    readonly otherProp: string;
}
export type Profile = AnonymousProfile | AuthenticatedProfile;

function handleProfile(prof: Profile) {
    if (prof.userId !== undefined) {
        console.log(prof.name);
    }
}
```

**Expected behavior:**

Code would compile, since by checking that the `userId` property is not undefined we definitely know we are handling an `AuthenticatedProfile` instance.

**Actual behavior:**

Type checks fail and you need workarounds such as the ones on this question: https://stackoverflow.com/q/44583342/625581.

What makes me think this is a bug (or at least can be added as a feature) is that this other [similar code works](https://www.typescriptlang.org/play/#src=export%20interface%20AuthenticatedProfile%20%7B%0A%20%20%20%20readonly%20userId%3A%20%2233%22%3B%0A%20%20%20%20readonly%20name%3A%20string%3B%0A%7D%0Aexport%20interface%20AnonymousProfile%20%7B%0A%20%20%20%20readonly%20userId%3A%20%2244%22%3B%0A%20%20%20%20readonly%20otherProp%3A%20string%3B%0A%7D%0Aexport%20type%20Profile%20%3D%20AnonymousProfile%20%7C%20AuthenticatedProfile%3B%0A%0Afunction%20handleProfile(prof%3A%20Profile)%20%7B%0A%20%20%20%20if%20(prof.userId%20%3D%3D%3D%20%2233%22)%20%7B%0A%20%20%20%20%20%20%20%20console.log(prof.name)%3B%0A%20%20%20%20%7D%0A%7D). I've read the [handbook](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types) and it seems that casting is an option, but the `userId` property is already part of both instances and I wouldn't want to add the boilerplate of casting when there's information right there.

**Comment by ahejlsberg** [comment] 2017-06-16 17:08
Duplicate of #12600.

**Comment by mhegazy** [comment] 2017-08-17 18:07
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-08-17 18:07 UTC
Labels: Duplicate
