### ISSUE TITLE
Wrong code suggestion when using "Mapped Types" as function parameter

### ISSUE THREAD

**Issue by lNaymonl** [microsoft/TypeScript#55545] opened 2023-08-28 14:03 UTC
Type: **Bug**

Extension version: 5.3.20230827

Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

Problem:
The Codesuggestion shows "1", "2", "3", "4" event though `a` is "valA".  When hovering it also shows that `b` has type "1" | "2". And when i select "3" or "4" it gives me the following error: 
`Argument of type '"3"' is not assignable to parameter of type '"1" | "2"'.`

![Screenshot (7)](https://github.com/microsoft/vscode-typescript-next/assets/65818963/d12aad72-a72e-4c03-bb11-239877e25b36)

Expected:
The Codesuggestion should only display"1" and "2".

Source Code:
```typescript
enum myEnum {
  valA = "valA",
  valB = "valB",
}

interface myEnumParamMapping {
  ["valA"]: "1" | "2";
  ["valB"]: "3" | "4";
}

function myFunction<K extends keyof typeof myEnum>(a: K, b: myEnumParamMapping[K]) {
  console.log({ a, b });
}

myFunction("valA", "2");
```

**Comment by 13OnTheCode** [comment] 2023-08-28 17:46
![微信截图_20230829014357](https://github.com/microsoft/TypeScript/assets/137921275/fb3e5e34-5e0c-47f7-9411-5e4c1d7bef41)

@lNaymonl  My TypeScript version is 5.2.2, and when I tried to reproduce your issue, everything seems to be working fine, unless I missed something.

**Comment by 13OnTheCode** [comment] 2023-08-28 18:10
@andrewbranch 

```json
"compilerOptions": {
    "strict": true,
    "noEmit": true,
    "allowJs": true,
    "skipLibCheck": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "strictNullChecks": true,
    "resolveJsonModule": true,
    "useDefineForClassFields": true,
    "noUncheckedIndexedAccess": true,
    "allowImportingTsExtensions": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true
}
```

**Comment by andrewbranch** [comment] 2023-08-28 18:35
@Andarist does this look familiar to you?

**Comment by andrewbranch** [comment] 2023-08-28 18:45
Could have sworn either you or I have fixed this about 20 times already in the past

**Comment by lNaymonl** [comment] 2023-08-28 20:40
> I can reproduce this. @lNaymonl @13OnTheCode could you both post your tsconfig.json settings please?
```json
{
  "compileOnSave": false,
    "compilerOptions": {
        "downlevelIteration": true,
        "module": "es2020",
        "outDir": "./dist/out-tsc",
        "sourceMap": true,
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es2018",
        "resolveJsonModule": true,
        "allowSyntheticDefaultImports": true,
        "skipLibCheck": true,
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2017",
            "dom"
        ],
        "baseUrl": ".",
        "paths": {
            "globalize": [
                "../node_modules/globalize/dist/globalize"
            ],
            "globalize/*": [
                "../node_modules/globalize/dist/globalize/*"
            ],
            "cldr": [
                "../node_modules/cldrjs/dist/cldr"
            ],
            "cldr/*": [
                "../node_modules/cldrjs/dist/cldr/*"
            ]
        }
    }
}
```

**Comment by lNaymonl** [comment] 2023-08-28 20:58
If i try it in VS, it works like a charm.
I also tried it without the [vscode extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next), which worked as well.

So i don't think it's a typescript specific problem but rather an extension problem.

**Comment by Andarist** [comment] 2023-08-28 21:06
I prepared a fix for this here: https://github.com/microsoft/TypeScript/pull/55552

**Closed** 2023-08-28 22:04 UTC
Labels: Bug
