### ISSUE TITLE
Cannot find namespace `module.SomeClass` when used as type even though module exports it with `export default { SomeClass }`

### ISSUE THREAD

**Issue by elisee** [microsoft/TypeScript#60342] opened 2024-10-25 21:20 UTC
### 🔎 Search Terms

using type of class in default export
using types of a module with a default export containing with a class
cannot find namespace

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about default imports and exports

### ⏯ Playground Link

https://www.typescriptlang.org/dev/bug-workbench/?ts=5.7.0-dev.20241025#code/PTAEAEDMEsBsFMB2BDAtvAXKAzvAxgPaIAmyATgJ4B0ALtgFB6zLbagDKB6Aws66AG8AvvXgAPAA4EyNUMXiRkAV1iyBHLvF4s2I+iAgwEKdFglloqctTr1LUmTnxFSlUJDJdQAIirBchCTW3gDc9AiyAPrIWAEu1lScPHzYYUA

### 💻 Code

```ts
// @filename: secondary.ts
class SomeClass {}
export default { SomeClass }

// @filename: primary.ts
import secondary from "./secondary";
let _a: secondary.SomeClass; // Error 2503: Cannot find namespace 'secondary'.
```

### 🙁 Actual behavior

TypeScript reports "Cannot find namespace 'secondary'."

### 🙂 Expected behavior

TypeScript resolves secondary.SomeClass and lets me use it as the type of a variable

### Additional information about the issue

This is a minimal repro of an issue I encounter when default exporting a bunch of classes each in their own file and then re-exporting them from a common module with `export default { ClassA, ClassB, ClassC }`.

Using the class as a constructor as in `let _a = new secondary.SomeClass();` does work, just not as a type.

Screenshot of the error in VSCode:

![Image](https://github.com/user-attachments/assets/e86a55f4-0e5b-48ed-928e-82ffbe2790d2)

**Comment by Andarist** [comment] 2024-10-25 21:24
To access this type you need to use `typeof secondary.SomeClass`

**Comment by elisee** [comment] 2024-10-25 21:26
> To access this type you need to use typeof secondary.SomeClass

This does not yield the desired result, as can be seen here:

```ts repro
// @filename: secondary.ts
class SomeClass {}
export default { SomeClass }

// @filename: primary.ts
import secondary from "./secondary";
let _a: typeof secondary.SomeClass;
_a = new secondary.SomeClass(); // Error 2741: Property 'prototype' is missing in type 'SomeClass' but required in type 'typeof SomeClass'.

```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?ts=5.7.0-dev.20241025#code/PTAEAEDMEsBsFMB2BDAtvAXKAzvAxgPaIAmyATgJ4B0ALtgFB6zLbagDKB6Aws66AG8AvvXgAPAA4EyNUMXiRkAV1iyBHLvF4s2I+iAgwEKdFglloqctTr1LUmTnxFSlUJDJdQAIirBchCTW3gDc9AiyAPrIWDQUEvAEkE6BrtScPHzYYdGgALygiPAA7iku1lQZWlkAFACUYfRAA)

**Comment by elisee** [comment] 2024-10-25 21:32
Somehow it seems that `let a: typeof secondary.SomeClass.prototype;` does the trick. But that seems like a strange way to express that type. Am I misunderstanding something, is there really something inherent about default exports that prevent TypeScript from exposing the class type directly, or is it a bug?

**Comment by MartinJohns** [comment] 2024-10-26 00:14
Duplicate of #35308.  
Relevant comment: https://github.com/microsoft/TypeScript/issues/30267#issuecomment-470797283

**Comment by uhyo** [comment] 2024-10-26 02:57
In TypeScript, referring to a type with the property access syntax ( `foo.SomeType` ) is only possible when `foo` is a namespace. In your code `secondary` is a normal object, not a namespace, hence the `secondary is not a namespace` error.

In other words... the `class` declaration is a syntax to define a value (class object) and a type at the same time, doing something similar to:

```ts
const SomeClass = class {};
type SomeClass = InstanceType<typeof SomeClass>;
```

When you create an object and export it, you are only putting the value side into the object.

```ts
const _default = { SomeClass }; // ←puts the const SomeClass into object, leaving type SomeClass unused
export default _default;
```

When you put a class into an object, TypeScript no longer remembers its type aspect. At this point you are already unable to use `_default.SomeClass` as a type.

In general, re-exporting stuff by putting everything into one object and default-exporting it is an anti-pattern for several reasons. Instead, you can named-export your classes individually and use namespace import:

```ts
// @filename: secondary.ts
export class SomeClass {}

// @filename: primary.ts
import * as secondary from "./secondary";
let _a: secondary.SomeClass;
```

**Comment by elisee** [comment] 2024-10-26 17:39
Thanks for the helpful answers, I'll try to use the InstanceType<> helper.

> In general, re-exporting stuff by putting everything into one object and default-exporting it is an anti-pattern for several reasons.

I know that's commonly said, and it's probably true for published libraries, but for my own apps it works great for modules that I have no interest in consuming piecewise, and this class type thing is the only papercut I have encountered over years of using them.

The major advantage for me is I can type `secondary` in any file right where I want to use it, and then trigger an auto-import of the module from VS Code with a couple keystrokes. Without a default export, I have to go and manually add `import * as secondary from "../some/path/to/secondary.ts"` at the top of the file. But maybe that points to something to improve in the TypeScript LSP. I'd be happy to stop using default exports/imports if I could generate `import * as` statements automatically with the same ease.

Anyway, I suppose these musings are beyond the scope of a bug report. Feel free to close the issue if the current behavior is expected and desired. Thanks very much to everyone who responded promptly and helpfully.

**Comment by uhyo** [comment] 2024-10-27 10:08
@elisee I see your usecase. Then you could have an intermediate file that default-exports the namespace object:

```ts
// @filename: intermediate.ts
import * as secondary from "./secondary";

export default secondary;
```

Or you could use the `namespace` syntax of TS, which I don't really recommend though:

```ts
// @filename: secondary.ts
namespace secondary {
  export class SomeClass {}
}

export default secondary;
```

**Closed** 2024-11-15 01:34 UTC
Labels: Working as Intended
