### ISSUE TITLE
Enhanced Function Type Inference within Generic Functions

### ISSUE THREAD

**Issue by maxime4000** [microsoft/TypeScript#56195] opened 2023-10-23 22:31 UTC
### 🔍 Search Terms

- Generic Function
- Type Inference
- Function Type
- Automatic Type Inference
- HOF
- Higher Order Function

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

I want to simplify the writing of hooks that will fetch a specific endpoint. I want to define few HOH (Higher Order Hooks for React) that will make different HTTP Calls. (GET, POST, PATCH, PUT, DELETE). I want to reused those function to create "Query/Mutation Hooks" that is wrapping React-query and some custom code. 

Extend TypeScript's type inference in generic functions to automatically deduce argument types for constructing dynamic API URLs within Higher Order Functions/Hooks, enabling a more streamlined and less verbose way to define API calls, particularly in the context of wrapping useQuery and similar functions.

### 📃 Motivating Example

I'm writing a Meta Framework project, simplifying API calls is a priority. By wrapping useQuery and other logic within a HOF, the aim is to allow default behavior to work well while also supporting customization when needed. 

Code example in CodeSandbox :https://codesandbox.io/p/sandbox/dawn-dream-vtdh49?file=%2Fsrc%2Fhooks%2FuseFetch.tsx%3A140%2C1-149%2C3

The goal is to write this : 
```typescript
// hooks/*.tsx

type FetchObjDef = { a: string; b: number; c: { c1:string }; };
export const useFeatureQuery = createFetchQueryHook<FetchObjDef>(
	"feature",
	(idA, idB) => `https://example.com/api/feature/${idA}/${idB}`
);
export const useFeaturePost = createMutationHook<FetchObjDef>("feature", (idA) => `https://example.com/api/feature/${idA}`)
export const useFeaturePatch = createMutationHook<FetchObjDef>(...)
export const useFeatureDelete = createMutationHook<FetchObjDef>(...)

// Component.tsx
const comp: FC = (props) => {
  const { data, isError, isLoading, refetch, status } = useFeatureQuery(props.idA, props.idB);
  return <Table data={data} .../>;
}
```

Right now, this will work but is kinda duplication of the goal. Could we make it so the need to define the function is not required : 
```typescript 
export const useFeatureQuery = createFetchQueryHook<FetchObjDef, (idA: string, idB: string) => string>(
	"feature",
	(idA, idB) => `https://example.com/api/feature/${idA}/${idB}`
);
```
### 💻 Use Cases

1. **What do you want to use this for?** 
   - Creating a higher-order hook to streamline API call definitions across different endpoints, encapsulating additional logic such as authentication seamlessly within the HOF code.
   
2. **What shortcomings exist with current approaches?**
   - Current type inference within generic functions requires verbose type annotations, making the process of defining dynamic API URLs cumbersome and less intuitive.
   
3. **What workarounds are you using in the meantime?**
   - Manually specifying function types when defining API URLs, leading to code duplication and a less streamlined developer experience.

**Comment by RyanCavanaugh** [comment] 2023-10-23 22:52
This seems to be a duplicate of #26242?

**Comment by maxime4000** [comment] 2023-10-24 04:41
I don't believe so. The referenced issue uses similar-looking code, but it doesn't seem to be a duplicate of this feature request.

## Goal:
I'm aiming for optimal Developer Experience (DX) regarding autocomplete from TypeScript. I care about defining the first generic, which implies the API response type. The second generic exists due to the lack of a "flexible function definition" that "implies named args with typing." If possible, I would remove this generic.

There's a working solution, but it necessitates typing the function in a generic, which I find redundant. Ideally, extending the generic to a function with spreadable args should suffice, shouldn't it?

TypeScript requires using a type generic to allow a flexible function shape when calling `Parameters<F>`, which is my goal. However, the function type could be `(...args: any[]) => any` for all I care, but this doesn't work. The "spreadable" args need to be defined within a type generic, or they're not inferable. The function must be a generic, or autocomplete isn't helpful when trying to use `Parameters<typeof fnUrl>`.

The following works, but isn't optimal:
```typescript
const useUserFetch = createFetchQueryHooks<User, (userId: string) => string>(
  "user", (userId) => `/path/to/user/${userId}`
);
```

I would prefer this, but it doesn't work:
```typescript
const useUserFetch = createFetchQueryHooks<User>(
  "user", (userId) => `/path/to/user/${userId}`
);
```
**Why?** Because the function definition is `(...args: string[]) => string`, `userId` can be implied to be `string`. If I want some other types, I would define it in the definition of "createFetchQueryHooks" in my opinion.

### Consideration:
Removing the first generic "RtnType" resolves the issue, and the function is inferred correctly. However, since I want the first Generic to be explicitly defined, I cannot infer the second generic.

I initially thought it was a knowledge/skill issue, and after attempting various alternatives and creating many type utilities, it seems impossible to write this the way I intend. Here are some facts for context:
- This is achievable if I forgo some features, but my ideal version of the HOF function doesn't work.
- I apologize for the extensive code in the example; I've spent multiple nights trying to make this code type work the way I want.
  - I've tried `string | (...args: string[]) => string`,
  - I've tried `(params: Record<string, string>) => string`
  - I've altered the return function argument definition
  - I've removed Generics: `RtnType` and `F`
- Having an optional argument after spread arguments doesn't help TypeScript... 😅

### Side Notes:
I acknowledge this is fancy typing, likely an edge case scenario. I don't fully grasp the implications of this Feature Request. It appears to be an improvement or a bug fix on the type generic, but there might be more beneath the surface. I am willing to help in two ways: If pointed to the files where this issue originates, I can investigate myself and possibly make a PR. Alternatively, I can provide more information, use cases, or code examples if needed.

**Comment by fatcerberus** [comment] 2023-10-24 11:44
> However, since I want the first Generic to be explicitly defined, I cannot infer the second generic.

That's 100% #26242.  Type parameter inference is intentionally all-or-nothing by design; inferring only certain ones would require implementing partial inference.

**Comment by maxime4000** [comment] 2023-10-24 18:43
Maybe? I can't tell as I'm not sure to fully understand the issues refer. But if it is, please close this issues as duplicate. I have subscribe myself to the refers issues for the future.

**Closed** 2023-10-27 01:24 UTC
Labels: Duplicate
