### ISSUE TITLE
How about generic parameters in the "Function" type?

### ISSUE THREAD

**Issue by samchon** [Microsoft/TypeScript#26114] opened 2018-08-01 08:54 UTC
Since v3.0 update, defining [`generic rest parameters`](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#generic-rest-parameters) is possible. The, how about adding generic parameters in the `Function` type and related features? 

By the implementation, specifying those methods' types are possible (who've handled only `any` type):

  - `Function.apply` clearly.
  - `Function.bind` maybe?

```typescript
interface Function<Ret = any, Params extends any[] = any>
{
    // It's possible to specifying types of return and parameters.
    apply(thisArg: any, args: Params): Ret;

    // Well, I don't know the solution... but it seems possible maybe...
    bind<T>(thisArg: any, elem: T): Function<Ret, Pop<Params, T>>;
    bind<Pops extend any[]>(thisArg: any, ...args: Pops): Function<Ret, Remainder<Params, Pops>>;
}
```

**Comment by AlCalzone** [comment] 2018-08-01 10:14
Duplicate of
https://github.com/Microsoft/TypeScript/issues/25973
https://github.com/Microsoft/TypeScript/issues/212

**Closed** 2018-08-02 23:04 UTC
Labels: Duplicate
