### ISSUE TITLE
Issue error if readonly static property has no initializer

### ISSUE THREAD

**Issue by Trias** [microsoft/TypeScript#43897] opened 2021-04-30 09:07 UTC
# Bug Report

### 🔎 Search Terms

static property readonly undefined typecheck literal

### 🕗 Version & Regression Information
As far as i know this is the behavior of all typescript version, but i think it's not intuitive

### ⏯ Playground Link
See my Playground example:

https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwDYEMDOa4BVhpgYWimAXgG8BYAKDlrjxRgEsE5iUATCAOyQE96EALbAAcihFwAvHABEaYWInBZAbmoBfatVCRYiVBmy4YAISgQA1sG5xKNOg2at2XXgIUjxIgFxzPSiJqmtpUOHiEUMSkAHQB3sDqVNRMAGZwABThZhbW3HGKCdIy8oXKsgCU9nSIPApIwDFIEADmGQAGAK4QADRwTADkQnCd3OwIABYoAEYNMXAAgkgKcDATwKt8YBsQ6dnmVjYFXsr9mAOlJ0EDfQDu68T98GgTEJ1IHHDTG4xwDejwAZ4KBMbgtOAAHxG3A4wFSoOAHAGcGgbEYDzgA1GsPh3ERA3aFU0QA

### 💻 Code
```
export class TestCorrect {
    static readonly someName = "someName";
}

export class TestBroken {
     static readonly someName: "someName"; 
     //  spot the error? ----^  
     // note how similar the syntax looks to the class above. 
     // but this time we are declaring a literal type and also prevent any assignment. which makes little sense and is likely a bug. 
     // what was meant is probably the code above.
}

if (TestBroken.someName == "someName") {
    console.log(`uo, i'm unreachable. Also the type of TestBroken.someName is `"someName"`, where it should rather be `undefined` or an error at the class definition)
}
```
### 🙁 Actual behavior

the code is accepted by typescript

### 🙂 Expected behavior

either an error at `TestBroken`-class or a type inference of `"someName" | undefined` (first option preferred)

**Comment by MartinJohns** [comment] 2021-04-30 09:58
Duplicate of #43285.

**Comment by MartinJohns** [comment] 2021-04-30 10:00
Duplicate of #27899.

**Comment by Trias** [comment] 2021-04-30 14:58
@MartinJohns thanks! I think for the mutable version it would be hard for typescript to determine if the property gets initialized somewhere, but it could be typed as `"literal" | undefined` in that case. And if `strictPropertyInitialization` is enabled or `readonly` is specified it should require a static assignment in my opinion.

**Closed** 2021-06-24 18:30 UTC
Labels: Duplicate
