### ISSUE TITLE
Array unions make method find into a field instead of method

### ISSUE THREAD

**Issue by ThePrimeagen** [microsoft/TypeScript#53456] opened 2023-03-23 15:17 UTC
# Bug Report
types that are unions of two types of arrays, ie `string[] | number[]` will make the `find` method go from a `method` to a `field`.

if type is just `string[]` or if i type it as `number[]` or if i type it by `(string | number)[]` in the example below find is a `method`.

### 🔎 Search Terms

find array method

### 🕗 Version & Regression Information
Started seeing it today
- Cannot compile TSC

### ⏯ Playground Link

[TSPlayground Example](https://www.typescriptlang.org/play?strict=false#code/GYVwdgxgLglg9mABAdxFAFAUwG6bFAZwC5ECoAnGMAcwG0BdRAH0TBAFsAjTchgSkQBvAFCJEOPIQB0wKgBN0WAQF4AfIigBPAA6Y4wcYmXHEAIjKUapxAH5Dx5WeBw41kpiMmAbAE4+AbmEAX2FhUEhYBBQ0ABUACxgCAEkCADEqTABGLFx8YkR0CypqZlYObnI+fiFRcVzpWTAFJSN1LV19exNzCmLrOw8HJxc3LsdfAOCw8Gh4JFQoeMSU9LBMACYcyXyimmqRMQk8mXlFTBU2nT0DQe7d6n6x4ddEd09xv0CQoA)

### 💻 Code

```typescript
function wut(events: string[] | number[]) {
  events.find((e) => typeof e === "string" ? e === "foo" : e === 69);
  // --------^  find is not a method
}
```

### 🙁 Actual behavior

TSC has hurt feelings (build fails)

### 🙂 Expected behavior

TSC says this is great (just like `map`, or other array methods)

**Comment by MartinJohns** [comment] 2023-03-23 15:23
Duplicate of #44373.

**Closed** 2023-03-25 18:00 UTC
Labels: Duplicate
