### ISSUE TITLE
[Flow Analysis] `throw` statements in nested function calls

### ISSUE THREAD

**Issue by buschtoens** [microsoft/TypeScript#32602] opened 2019-07-29 09:57 UTC
## Search Terms

flow analysis throw error exception undefined non-null assertion optional nested function call

## Suggestion

Teach flow analysis to understand `throw` statements in nested function calls.

## Use Cases

Many frameworks, even Node's standard library, come with a range of assertion helpers. In its most basic form, they take a `condition`, and an error `message` that will be thrown, when the `condition` evaluates to a false / falsy value.

TypeScript currently does not understand `throw` statements in nested function calls, which makes using `assert` helpers annoying, since you have either have to repeat the same conditional throw statement right after the assertion, use a non-null assertion, or a type cast, to tell TypeScript, that this value is present / fulfills some further criteria.

## Examples

```ts
function assert(message: string, condition: boolean) {
    if (!condition) throw new Error(message);
}

function foo<T>(someArg?: T): T {
    assert('Argument missing.', Boolean(someArg));

    // Toggle this line to fix:
    // if (!someArg) throw new Error('Argument missing.');
    
    return someArg;
}
```

[TypeScript REPL](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABAQwM6oKYCcoAoC2G6yA5hgFyKpRYxgkA0iECAJjLApQEZxwA2GZGACUiAN4AoRDMQxgiXAEIWYdp1GIoACyxwA7ojAZDAUSx6sBIqlIYRAbkkBfSZNCQNiYHwA8AFQA+XFQ4QgBBLBIAfkp-ETiJaVk0TBxcAHJIkhBCMChEfBh0OhIAOgymACE+QWEQsIxskUc3WUQAeg7EfzgSEkEtbWLEfjoMLThvGAAPcmSZLrkFZVCIqLEdPUNjMws4Kyyo3Ix8wuLUUorW9oXELAwoECwkNaaop2cgA)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## Possible Duplicates / Related

- #19415: Possibly undefined but it's not
- #16546: always-throw functions detect in null check
- #9998: Trade-offs in Control Flow Analysis 
-  https://github.com/microsoft/TypeScript/issues/16546#issuecomment-308646888:
    > But it's not currently possible to signal that a function invocation completely changes the control flow graph, and I don't know if we ever will be able to.

**Comment by MartinJohns** [comment] 2019-07-29 10:00
Duplicate of #32130, #10421, #31512, #31879, #17760.

**Comment by yortus** [comment] 2019-07-29 10:14
Sounds like #8655

**Closed** 2019-07-31 18:00 UTC
Labels: Duplicate
