### ISSUE TITLE
[Bug]tsc does not finish

### ISSUE THREAD

**Issue by kgtkr** [microsoft/TypeScript#30890] opened 2019-04-12 16:33 UTC
TypeScript Version:3.4.3
Code:

```ts
export type Head<T extends any[], D = never> = T extends [infer X, ...any[]] ? X : D;
export type Tail<T extends any[]> = ((...x: T) => void) extends ((x: any, ...xs: infer XS) => void) ? XS : never
export type Concat<A extends any[], B extends any[], R extends any[] = []> = {
  0: Reverse<R>,
  1: Concat<Tail<A>, B, Cons<Head<A>, R>>
  2: Concat<A, Tail<B>, Cons<Head<B>, R>>
}[A extends [] ? B extends [] ? 0 : 2 : 1];
export type Reverse<L extends any[], X extends any[] = []> = {
  1: X, 0: Reverse<Tail<L>, Cons<Head<L>, X>>
}[L extends [] ? 1 : 0]
export type Cons<X, XS extends any[]> = ((h: X, ...args: XS) => void) extends ((...args: infer R) => void) ? R : [];
export type Cast<T, P, D=P> = T extends P ? T : D;


type GetIn<T> = <K extends CursorEnum<T>>(path: K) => CursorResult<T, Cast<K, any[]>>;

type CursorEnum<T, R extends any[] = [], Key = keyof T> = {
  0: (CursorEnum<T[Cast<Key, keyof T>], Concat<R, [Key]> extends infer X ? Cast<X, any[]> : X>),
  1: R
}[T extends object ? 0 : 1];

type CursorResult<T, C extends any[]> = {
  0: T,
  1: CursorResult<T[Cast<Head<C>, keyof T>], Tail<C>>
}[C extends [] ? 0 : 1];
```

**Comment by RyanCavanaugh** [comment] 2019-04-12 17:21
... looks like a duplicate of #14833?

**Comment by kgtkr** [comment] 2019-04-12 17:26
This is a bug report

**Comment by RyanCavanaugh** [comment] 2019-04-12 17:34
This really looks like something that is *trying* to induce an infinite loop, not all of which we can detect. We'd really prefer a repro that was simple enough that a human can easily deduce that it should definitely terminate.

**Comment by RyanCavanaugh** [comment] 2021-12-16 00:47
This compiles in finite time now

**Closed by RyanCavanaugh** 2021-12-16 00:47 UTC
Labels: Needs More Info
