### ISSUE TITLE
Type narrowing doesn't recognize mutation by other function

### ISSUE THREAD

**Issue by marijnh** [microsoft/TypeScript#32633] opened 2019-07-31 10:59 UTC
**Code**

```ts
let x = "a"
function next() { x = Math.random() < 0.5 ? "a" : "b" }
function foo() {
    if (x == "a") {
        next()
        if (x == "b") console.log("got b")
    }
}
```

**Expected behavior:**

The code is accepted.

**Actual behavior:**

TypeScript reports an error for the `x == "b"` expression: `This condition will always return 'false' since the types '"a"' and '"b"' have no overlap.` because it ignores the possibility of `next()` mutating `x`.

**Playground Link:** [here](https://www.typescriptlang.org/play/#code/DYUwLgBAHhC8ECICGCBQAzArgOwMZgEsB7bCbEKMACgEoIBvaOCAWSTAAsA6AJyWwAmRALa0IAHggAGLgFYIAfkQoIALkQAjBBAC+GHPmKl0RImPqoIViAXQQqMWPGQI6F6x7IVqNS56u29o7OWnS4JADORKBcwEQA5lQI8USQoX5WejpAA)

I understand that type narrowing is extremely useful and that properly checking for this type of mutation involves expensive, non-local analysis (and can't always be done statically at all). But maybe this type of error should be suppressed in cases where it may not apply, to avoid situations like this, where my only option to get the code to compile is a `@ts-ignore` comment.

**Comment by jack-williams** [comment] 2019-07-31 11:07
Duplicate of #9998, specifically the extracts from the TypeScript compiler [here](https://github.com/microsoft/TypeScript/issues/9998#issuecomment-235963457).

You need to use a function instead:
```ts
let x = "a"
const getA = () => x;
function next() { x = Math.random() < 0.5 ? "a" : "b" }
function foo() {
    if (getA() == "a") {
        next()
        if (getA() == "b") console.log("got b")
    }
}
```

**Closed** 2019-07-31 11:14 UTC
