### ISSUE TITLE
Autocomplete won't choose shortest absolute import path for subfolders or sibling folders - even though Quick Fix works fine.

### ISSUE THREAD

**Issue by dalmo3** [microsoft/TypeScript#44544] opened 2021-06-11 02:09 UTC
# Bug Report
In a project structured like this:
```
.
|- index.tsx
|- components
|  |- index.ts
|  |- A
|     |- index.tsx
|  |- B
|     |- index.tsx
```` 

Where `baseUrl: "."` and `index.ts` files are written in way to export modules up the tree:

```
--  components/index.ts --

export * from './A'
export * from './B'
```

When editing any files under `components` or its subfolders, if you try to import component `A` **using tab to autocomplete**, intellisense will automatically add an import from `components/A` instead of from just `components`. 

Auto importing with quick fix `Ctrl+.` works as expected. The gif below demonstrates both tabbing and using quick fix.

![1](https://user-images.githubusercontent.com/33860060/121619635-05363380-cabd-11eb-90da-bbe19be1db96.gif)
See, quick fix gets the sorting right, and in case the first choice is already imported it even hides the other options which is fine.

In VSCode, that happens regardless of selecting Import Module Specifier as `shortest` or `non-relative`. (Though shortest sometimes results in relative paths).

I haven't seen the problem happen in files not under `components`. It works as expected.

### 🔎 Search Terms

Autocomplete, auto import, intellisense, import module specifier

### 🕗 Version & Regression Information
TS 4.2.2 and up

### ⏯ Playground Link
Fully reproducible here: https://codesandbox.io/s/hidden-lake-9jfk3?file=/src/components/A/index.tsx

### 🙂 Expected behavior

Autocomplete on tab should import module with the shortest possible path, just like quick fix, especially if selected `non-relative` as the specifier.

**Comment by andrewbranch** [comment] 2021-06-15 14:12
Duplicate of #41083

**Closed** 2021-06-17 18:00 UTC
Labels: Duplicate
