### ISSUE TITLE
type check dynamic imports from constant string literal

### ISSUE THREAD

**Issue by scarf005** [microsoft/TypeScript#60593] opened 2024-11-25 14:12 UTC
### 🔍 Search Terms

dynamic import constant string infer type any

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

statically analyze type of dynamic import if path is statically analyzable, such that

```ts
export {}

const polars = "nodejs-polars" as const
//    ^? const polars: "nodejs-polars"

const pl = await import(polars)
//    ^? const pl: typeof import("file:///node_modules/nodejs-polars/bin/index")
```

as type of `polars` is `"nodejs-polars"`, not `string`, typescript should treat `import("nodejs-polars")` the same as `import(polars)`.

### 📃 Motivating Example

https://github.com/denoland/deno/issues/26965

```ts
export {}

const polars = "nodejs-polars" as const

const pl = await import("nodejs-polars")
//    ^? const pl: typeof import("file:///node_modules/nodejs-polars/bin/index")

const pl2 = await import(polars)
//    ^? const pl2: typeof import("file:///node_modules/nodejs-polars/bin/index")
```

[Playground Link](https://www.typescriptlang.org/play/?target=99#code/KYDwDg9gTgLgBAbwL4CgUGMIDsDO9IA2AhlDnALxwBEWEAJsAFY4C0hJOVcRZmuMaPnjhgCFbgHciAS3jSAtpFgAKGvSat2pKgEoUAen1xjcAHoB+QdmGiATOKJTZcBUpjKtOPYZNnLQA)

### 💻 Use Cases

1. What do you want to use this for?

writing type safe javascript module, with version string abstracted away to manage versions easily

```js
const preact = "preact@10.24.3"
const { h, render } = await import(`https://esm.sh/${preact}`)
const { computed, effect, signal } = await import(`https://esm.sh/@preact/signals@1.3.0?deps=${preact}`)

console.log(`preact version is ${preact}`)
```

2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

due to type check not working in above example, version string has to be duplicated, which might cause bug when naively regex-replacing.  

```js
import { h, render }  from "https://esm.sh/preact@10.24.3"
import { computed, effect, signal } from "https://esm.sh/@preact/signals@1.3.0?deps=preact@10.24.3"

console.log("preact version is preact@10.24.3")
```

**Comment by MartinJohns** [comment] 2024-11-25 15:48
Duplicate of #32401.

**Closed** 2024-11-29 01:33 UTC
Labels: Duplicate
