### ISSUE TITLE
VSCode intellisense not working with typescript 3.7.5 in Angular projects

### ISSUE THREAD

**Issue by admosity** [microsoft/TypeScript#37187] opened 2020-03-03 14:41 UTC
*TS Template added by @mjbvz*

**TypeScript Version**: 3.7.5

**Search Terms**
- angular

---

Using the latest vscode with Typescript 3.7.5, intellisense breaks for anything referencing `node_modules`. This is reflected on new projects created with `@angular/cli` as well. Tested on an Angular 7 project to see if the version difference between Angular 7 and Angular 9 made a difference. 

```
> code --version
1.42.1
c47d83b293181d9be64f27ff093689e8e7aed054
x64
```

Steps to Reproduce:

1. Type a symbol that can be indexed from `node_modules` (e.g. ReactiveFormsModule from Angular).
2. Hit `ctrl+space` or whatever is the intellisense hotkey is configured..
3. `No Suggestions` appears.

Switching to the lower workspace Typescript version in my Angular 7 setup I can get the suggestions to show again.

Video reproduction with Typescript version switch:
![intellisense-repro](https://user-images.githubusercontent.com/4655972/75785840-5db34880-5d32-11ea-83ed-11e77864f830.gif)

On a fresh Angular 9 setup:

![image](https://user-images.githubusercontent.com/4655972/75786108-c8fd1a80-5d32-11ea-8176-d634a6fb8c50.png)

Does this issue occur when all extensions are disabled?: **Yes**
![image](https://user-images.githubusercontent.com/4655972/75785235-67887c00-5d31-11ea-960b-7b43309aebb9.png)

Same project in Atom:

![image](https://user-images.githubusercontent.com/4655972/75785357-9141a300-5d31-11ea-97fe-8a00844b9c4f.png)

**EDIT**: This appears to be happening in Atom with Typescript 3.7.5 as well now in the Angular 9 setup. Might be specifically a Typescript 3.7.5 issue.

**EDIT EDIT**: It seems that adding `node_modules/@angular` as a typeRoot fixes some issues:

TSCONFIG:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types",
      "node_modules/@angular"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}

```

It seems that adding `node_modules/@angular` as a typeRoot fixes some issues:
![image](https://user-images.githubusercontent.com/4655972/75794115-57c36480-5d3e-11ea-8c8f-211fac64e698.png)

![image](https://user-images.githubusercontent.com/4655972/75794242-82adb880-5d3e-11ea-9920-29feb0e5b6cc.png)

**Comment by DanielRosenwasser** [comment] 2020-03-04 00:08
Verified in 3.9.0-dev.20200303

**Comment by DanielRosenwasser** [comment] 2020-03-04 00:13
Ideally `typeRoots` shouldn't need to be specified at all here. I'm not sure if Angular CLI itself does that at all. (@mgechev)

**Comment by mgechev** [comment] 2020-03-04 01:09
In the latest Angular CLI in `tsconfig.json` we specify the following `typeRoots`:

```js
...
    "typeRoots": [
      "node_modules/@types"
    ],
...
```

Does TypeScript use `"node_modules/@types"` by default?

**Comment by andrewbranch** [comment] 2020-03-04 20:07
Duplicate of #36042 (canonical), #30033, #30474, and #28773.

**Closed** 2020-03-07 18:00 UTC
Labels: Duplicate

**Comment by cjdreiss** [comment] 2020-08-03 22:40
@admosity did you ever find a solution?  This seems like an issue I have at work.  We have a parent library/project which contains all the dependancies in its package json (angular, rxjs, etc).   Our child apps have only the parent in their package.json now so we don't need to worry about updating every app's package.json, but now imports don't work.  

I've tried adding to `typeRoots` but it doesn't seem to do anything...  Using Angular 10 / TS 3.9.6 (although we had the issue in Angular 9 and whatever TS 3.8.x version it used too).
