### ISSUE TITLE
Rest parameters are not working in array creation

### ISSUE THREAD

**Issue by MDOR** [Microsoft/TypeScript#22142] opened 2018-02-23 04:44 UTC
**TypeScript Version:**  2.7.0-dev.20180222

**Search Terms:**  "destructuring assignment" "array"
**Code**

```ts
[...Array(5)].map((_, i) => i)
```

**Expected behavior:**
Generate an array with all the index values
`[0,1,2,3,4]`

**Actual behavior:**
Generate an array with empty values
`[,,,,]`

**Playground Link:**  [playground](http://www.typescriptlang.org/play/#src=console.log(%5B...Array(15)%5D.map((_%2C%20i)%20%3D%3E%20i))%3B)

**Aditional Evidence**
![image](https://user-images.githubusercontent.com/7268268/36578220-5cc7ad4c-1821-11e8-85b1-dc05085fd1c4.png)

**Related Issues:**

Thanks in advance!

**Comment by mhegazy** [comment] 2018-03-10 00:39
Duplicate of https://github.com/Microsoft/TypeScript/issues/8856

**Closed** 2018-03-26 16:22 UTC
Labels: Duplicate
