### ISSUE TITLE
Type check does not work if it is done in a method call

### ISSUE THREAD

**Issue by maximedupre** [microsoft/TypeScript#35446] opened 2019-12-02 19:07 UTC
**TypeScript Version:**  3.7.2

**Search Terms:** Type check does not work if it is done in a method call

**Code**

```ts
class SomeClass {
    someNumber: number | undefined

    private get someComputedNumber() {
        this.validateSomeNumber()

        return 1 + this.someNumber // ERROR: Object is possibly 'undefined'.
    }

    private validateSomeNumber() {
        if (typeof this.someNumber === 'undefined') { 
            throw new Error('someNumber is undefined')
        }
    }
}
```

**Expected behavior:**
It should not error to "Object is possibly 'undefined'.", because if `this.someNumber` is undefined, `this.validateSomeNumber` will throw

**Actual behavior:**
It errors to "Object is possibly 'undefined'."

**Playground Link:** http://www.typescriptlang.org/play/?ssl=15&ssc=2&pln=1&pc=1#code/MYGwhgzhAEDKD2BbApgYXFaBvAUNf0ESyAcgK6IBGyATgFzQB2F1N0APtGYwCbIBmAS0bIeOPAQAONQQDcwAF2TQA5sgWFiqJJLJKe5KrQAUASmwSCBBQAtBEAHTyQgnouQIUh1mfFWrNOpkNIzQAIzQANTQtvYORF4stJbQAL5+UjLyStDOru6epEk0Zhb+BIL80MYKAJ6SyPBVsY4JRUZsALzd0ADk3HxCIjy95ljQKeX4tjTwAO5MyAsAojSzJb1t3rTQ9ly8AsKio5ME6VbpqUA

**Comment by RyanCavanaugh** [comment] 2019-12-02 19:24
Method bodies are not inlined for CFA purposes

**Comment by IllusionMH** [comment] 2019-12-02 19:30
TS 3.7 provides [assertion functions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions) for complex cases, unfortunately they only assert their values so you'll have to change implementation to validate it's arguments.

[Argument assertion example](http://www.typescriptlang.org/play/#code/MYGwhgzhAEDKD2BbApgYXFaBvAUNf0ESyAcgK6IBGyATgFzQB2F1N0APtGYwCbIBmAS0bIeOPAQAONQQDcwAF2TQA5sgWFiqJJLJKe5KrQAUASmwSCBBQAtBEAHTyQgnouQIUh1sdv2HRF4stKYA3OJWVjTqZDSM0ACM0ADU0H6OgaTBNJbQAL4RUjLyStDOru6eWUY0xs4MYIwAnqYNULQKMM7Q9kzZFpEEgvzQvk2SyPAj3QC8c9AA5Nx8QiI8C+a4g4O2NPAA7kzIhwCiNHu1C5netD0wywLCohu5VgVvOHlAA) or more [weird approach that asserts on this](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=19&pc=2#code/MYGwhgzhAEDKD2BbApgYXFaBvAUNf0ESyAcgK6IBGyATgFzQB2F1N0APtGYwCbIBmAS0bIeOPAQAONQQDcwAF2TQA5sgWFiqJJLJKe5KrQAUASmwSCBBQAtBEAHTyQgnouQIUh1mYDc4qysadTIaRmgARmgAamhbewciLxZaS2gAXwCpGXklVXVoeFtabURdfW8Tc1w0oJCwyJi4u0ck0hSaNMyraTl3aGdXd092oxozBkgIWgUYeJh7OC0MGAAybE1ksYYSeEZyEHBKEGQAHhH0KYBtAHI2ypobgF0APgyLQIJBfmhjBQBPSTIeA-eaJYgPaAAXhh0Bu3D4QhEPBu1Vqn2aNHgAHcmMhcQBRGhY8Z3CEdaCLBECYSiVHo-DdAiZdJAA) 😨

**Comment by jcalz** [comment] 2019-12-02 19:31
This is working as intended (or possibly a design limitation) and probably a duplicate of #9998.  Control flow type analysis in the face of function or method calls is a hard problem to solve.  Right now the compiler more or less assumes that function calls have no effect on control flow.

That being said, TypeScript 3.7 introduced [assertion functions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions) (#32695) which allow you to mark a function as having such an effect on control flow.  So the specific code you have above could be changed to

```ts
    private validateSomeNumber(): asserts this is { someNumber: number } {
        if (typeof this.someNumber === 'undefined') {
            throw new Error('someNumber is undefined')
        }
    }
```

and it will just work for you.  Good luck!

[Playground link](http://www.typescriptlang.org/play/#code/MYGwhgzhAEDKD2BbApgYXFaBvAUNf0ESyAcgK6IBGyATgFzQB2F1N0APtGYwCbIBmAS0bIeOPAQAONQQDcwAF2TQA5sgWFiqJJLJKe5KrQAUASmwSCBBQAtBEAHTyQgnouQIUh1mfFWrNOpkNIzQAIzQANTQtvYORF4stJbQAL5+UjLyStDOru6epEk0ZgyQELQKMLEw9tiaiUb0TMVpFv4EgvzQxgoAnpLI8N018cTetNAAvDPQAOTcfEIiPHPmuB0dtjTwAO5MyPsAojQ7JXMJRU3QdYsCwqJrKVbpLzipQA)

**Comment by maximedupre** [comment] 2019-12-03 00:48
@jcalz Thanks, this seems to work well :).

When I first read your answer, i though that simply adding a property to the class would break your solution, but it did not. I guess that `asserts this is { someNumber: number }` is not strict, because adding, for example, a `someString: string | undefined` property to the class is still working.

**Closed** 2021-06-01 22:25 UTC
Labels: Design Limitation
