### ISSUE TITLE
Can't merge const enum with namespace

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#16804] opened 2017-06-28 15:07 UTC
**TypeScript Version:**  nightly (2.5.0-dev.20170628)

**Code**

```ts
enum E {}
namespace E {}

const enum C {}
namespace C {}
```

**Expected behavior:**

No error.

**Actual behavior:**

`src/a.ts(5,11): error TS2473: Enum declarations must all be const or non-const.`

**Comment by ajafff** [comment] 2017-07-01 13:16
If the namespace contains any statement you get another error: `Duplicate identifier 'C'.`

```ts
const enum C {}
namespace C {;}
```

FWIW I think the behavior is correct in both cases.

**Comment by mhegazy** [comment] 2017-11-09 22:39
Duplicate of #17372

**Closed** 2017-11-09 23:02 UTC
Labels: Duplicate
