### ISSUE TITLE
Lossy argument names when spreading across parameter types

### ISSUE THREAD

**Issue by mindplay-dk** [microsoft/TypeScript#48049] opened 2022-02-27 10:39 UTC
# Bug Report

### 🔎 Search Terms

`argument names spread`, `parameter names spread`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAogjgVwIYBsCWooF4oAokBcUAdggLYBGEATgDRQVGmU0CU2AfAwPbcoRJiAbgCwAKHGhIUAOIB5OQBFseAHTqk1AOYBnIgG11qgAqakZCMBo6APPGTpQHALrssXAG7c0AE1ESxKWgAIQBBZRxcI01dAyNTanNLaztEVAwQDnodYGo0Yi1XTigvX38gA)

### 💻 Code

```ts
type Equality = (a: number, b: number) => boolean;

type GOOD = (...args: [...Parameters<Equality>]) => void;

type BAD = (...args: [...Parameters<Equality>, string]) => void;
```

### 🙁 Actual behavior

As shown here, the argument names are lost in if the argument list expression involves *any* arguments without names:

![image](https://user-images.githubusercontent.com/103348/155878765-f719a7f6-a6b6-4f17-8969-abd833d9aecf.png)

### 🙂 Expected behavior

It should infer the type of `BAD` as `(a: number, b: number, args_2: string) => void`.

### 🤔 Workaround

Declaring an extra function type with the additional arguments seems to work:

```ts
type Equality = (a: number, b: number) => boolean;

type Additional = (lol: string) => void; // 👈

type GOOD = (...args: [...Parameters<Equality>]) => void;

type BAD = (...args: [...Parameters<Equality>, ...Parameters<Additional>]) => void;
```

Inlining a function type seems to work too:

```ts
type Equality = (a: number, b: number) => boolean;

type GOOD = (...args: [...Parameters<Equality>]) => void;

type BAD = (...args: [...Parameters<Equality>, ...Parameters<(lol: string) => void>]) => void;
```

So there are known workarounds, although I would say these are non-obvious - it took me a long time to figure this out, and it's just surprising how the second part of the parameter type expression seems to determine the outcome of the first part.

**Comment by mindplay-dk** [comment] 2022-02-27 10:50
Actually, this workaround didn't work for my case either.

Here's the same workaround wrapped in a `WithMoreParams` type expression:

```ts
type Equality = (a: number, b: number) => boolean;

type WithMoreParams<F extends (...args: any) => any> = (...args: [...Parameters<F>, ...Parameters<(lol: string) => void>]) => void;

type BAD = WithMoreParams<Equality>;
```

As soon as you're doing it from a function declaration or another type expression, it loses the names again.

[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAogjgVwIYBsCWooF4oAokBcUAdggLYBGEATgDRQVGmU0CU2AfAwPbcoRJiAbgCwAKHGhIUAOoYAFgFlu1CAAUk1JGQDOAHgBiUCAA9gEYgBMdeAHT3NAcx1FBIdli5uuOXPdtOLlAA2v4aWmQQ5tT6Bhz0YZraUTT6uCh8RDrA1GjEjh5cAG7caJYcALqFUCVlohJiUtAAQgCCACLYsgrKquHa+vDI6KAc9UA)

**Comment by IllusionMH** [comment] 2022-02-27 13:10
Tuple either all have labeled elements or none. In your example none are.
See what https://github.com/microsoft/TypeScript/issues/39941#issuecomment-778805226 for details.

Much simpler and clear way
```ts
type BAD = (...args: [...factoryParams: Parameters<Equality>, detals: string]) => void;
```

**Comment by mindplay-dk** [comment] 2022-02-28 08:20
I had no idea you could name tuple members! (is that a documented feature? I've never seen this before.)

Using this approach does seem to work:

```ts
type Equality = (a: number, b: number) => boolean;

type WithMoreParams<F extends (...args: any) => any> = (...args: [...params: Parameters<F>, ...details: unknown[]]) => void;

type BAD = WithMoreParams<Equality>;
```

Curiously though, the compiler demands that I name `params` here - even though the name is unused and discarded.

Apparently, tuple members can only have names if the parent tuple has a name?

But yes, this approach works for my use case as well:

```ts
export type Fact = {
  pass: boolean;
  actual: unknown;
  details: unknown[];
}

type Details = (...details: unknown[]) => void;

export function assertion<F extends (...args: any[]) => boolean>(assert: F)
  : (...args: [...params: Parameters<F>, ...details: unknown[]]) => Fact // 👈 fixed!
{
  return (...args: [...Parameters<F>, ...Parameters<Details>]) => ({
    pass: assert(...args.slice(assert.length) as any),
    actual: args[0],
    details: args.slice(1),
  });
}

const isEqual = assertion((a:number, b:number) => a === b);

const fact = isEqual(1, 2, "because reasons");
```

Thanks @IllusionMH !

I do think there is room for some improvements here.

Maybe the error messages could be more helpful?

It's definitely not clear to me why the obvious solution in my original post only works until you wrap it in a type for reuse. Something seems inconsistent here? If there is some practical reason why this doesn't / can't / shouldn't work, perhaps the 5048 error message ("Tuple members must all have names or all not have names") should appear when this is attempted?

**Comment by jcalz** [comment] 2022-02-28 16:46
> I had no idea you could name tuple members! (is that a documented feature? I've never seen this before.)

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#labeled-tuple-elements

**Comment by RyanCavanaugh** [comment] 2022-02-28 18:40
The short answer is that the parameter -> tuple name feature is "best effort" (since nothing in the type system works/doesn't work depending on these names), and the effort to handle this particular case simply hasn't been done yet

**Comment by Vanilagy** [comment] 2023-10-19 07:44
The original reproduction
```ts
type Equality = (a: number, b: number) => boolean;

type GOOD = (...args: [...Parameters<Equality>]) => void;

type BAD = (...args: [...Parameters<Equality>, string]) => void;
```
is fixed now:

![CleanShot 2023-10-19 at 09 31 53](https://github.com/microsoft/TypeScript/assets/1696106/a012b037-8499-4f7b-8b99-7b4c2e105b63)

I say this issue can be closed, then.

**Closed** 2023-10-19 22:38 UTC
Labels: Suggestion, Help Wanted, Experience Enhancement
