### ISSUE TITLE
[TSServer] Definition: Cannot read property 'getSourceFile' of undefined

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15813] opened 2017-05-13 04:24 UTC
**TypeScript Version:**  2.3.3-insiders

**Code**

`main.jsx`:

```js
import { Component } from "react";
import Bar from "./bar";

/**
  * @augments {Component<{x: number}, any>}
  */
class X extends Component {

    render() {
        return <div>
           <Bar></Bar>
        </div>
    }
}
```

`bar.jsx`

```js
import { Component } from "react";

export default class Bar extends Component {
	constructor() {
		super()
	}
	
	render() {
		return <div>bar</div>
	}
}
```

Send definitions request in`main.jsx` a line 11, column 15 (the `<Bar></Bar>` line)

**Expected behavior:**
No errors

**Actual behavior:**

```
[Trace - 9:22:31 PM] Sending request: definition (612). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/main.jsx",
    "line": 11,
    "offset": 15
}
[Trace - 9:22:31 PM] Response received: definition (612). Request took 23 ms. Success: false . Message: Error processing request. Cannot read property 'getSourceFile' of undefined
TypeError: Cannot read property 'getSourceFile' of undefined
    at createDefinitionInfoFromName (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:63696:34)
    at createDefinitionInfo (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:63693:20)
    at Object.getDefinitionAtPosition (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:63584:25)
    at Object.getDefinitionAtPosition (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:71798:38)
    at IOSession.Session.getDefinition (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:76950:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:76491:61)
    at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:77802:88
    at IOSession.Session.executeWithRequestId (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:77793:28)
    at IOSession.Session.executeCommand (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:77802:33)
    at IOSession.Session.onMessage (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:77822:35)
[Error - 9:22:31 PM] 'definition' request failed with error.
```

**Comment by andy-ms** [comment] 2017-05-15 14:34
Looks like a duplicate of #15751.

**Closed** 2017-05-15 14:34 UTC
Labels: Bug, VS Code Tracked
