### ISSUE TITLE
[REGRESSION] Error is not instanceof error

### ISSUE THREAD

**Issue by ninja-** [Microsoft/TypeScript#25016] opened 2018-06-16 01:34 UTC
**TypeScript Version:**  2.9.2
NodeJS: 10.2.1

**Search Terms:** 

**Code**

```ts
let net = require("net"); 1
let x = net.Socket(); 1
x.on('error', e => {
console.log(e instanceof Error, e);
}); 1
x.connect(1234); 1
```

**Expected behavior:**
Native node error from 'net' module is instanceof error
**Actual behavior:**
It works correctly via node, but not via typescript :(

Typescript:
```
# node ..\node_modules\ts-node\dist\bin.js
> let net = require("net"); 1
1
> let x = net.Socket(); 1
1
> x.on('error', e => {
... console.log(e instanceof Error, e);
... }); 1
1
> x.connect(1234); 1
1
> false { Error: connect ECONNREFUSED 127.0.0.1:1234
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 1234 }
```
Node:
```
>node -i
> let net = require("net"); 1
1
> let x = net.Socket(); 1
1
> x.on('error', e => {
... console.log(e instanceof Error, e);
... }); 1
1
> x.connect(1234); 1
1
> true { Error: connect ECONNREFUSED 127.0.0.1:1234
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 1234 }
```
**Playground Link:**  

**Related Issues:**

**Comment by DanielRosenwasser** [comment] 2018-06-16 02:04
Hey, thanks for filing, but this seems to be a duplicate of #12123

https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work

In the future using the issue tracker's search functionality can make it easier for us to triage issues. Thanks!

**Comment by DanielRosenwasser** [comment] 2018-06-16 02:10
actually I'm reopening this because I'm not totally sure. But I think part of the cause is actually that you have ts-node running on Node internals targeting ES5 or earlier. Try targeting ES2015 and seeing if that helps.

**Comment by ninja-** [comment] 2018-06-16 04:20
Here is my tsconfig:
```
{
    "compilerOptions": {
        "outDir": "./lib/",
        "sourceMap": true,
        "noImplicitAny": true,
        "module": "commonjs",
        "target": "es2017",
        "jsx": "react",
        "lib": ["es2017"],
        "experimentalDecorators": true,
        "declaration": true,
        "emitDecoratorMetadata": true
    },
    "include": [
      "./src/**/*",
      "./__tests__"
    ]
}
```
Also I am sure it's being loaded by ts-node...
I don't run ts-node on prod., but I am using Jest+ts-node for unit tests and "instanceof Error" not working breaks the application logic...

**Comment by mhegazy** [comment] 2018-06-19 20:10
Looks like a ts-node issue. please file this under https://github.com/TypeStrong/ts-node/issues instead

**Closed** 2018-07-05 17:08 UTC
Labels: External
