### ISSUE TITLE
Erroneous type narrowing in try / catch / finally with strictNullChecks

### ISSUE THREAD

**Issue by davidni** [Microsoft/TypeScript#18916] opened 2017-10-03 19:00 UTC
**TypeScript Version:**  2.4.1

**Code**
Compile with `strictNullChecks = true`
Playground link: [here](http://www.typescriptlang.org/play/#src=class%20A%20%7B%0D%0A%20%20%20%20a%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Alet%20foo%3A%20A%20%7C%20undefined%20%3D%20void%200%3B%0D%0Atry%20%7B%0D%0A%20%20%20%20foo%20%3D%20new%20A()%3B%0D%0A%20%20%20%20throw%20new%20Error()%3B%0D%0A%7D%20catch%20(e)%20%7B%0D%0A%20%20%20%20if%20(foo)%20%7B%0D%0A%20%20%20%20%20%20%20%20foo.a%3B%20%2F%2F%20ERROR%3A%20Property%20'a'%20does%20not%20exist%20on%20type%20'never'.%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0Afinally%20%7B%0D%0A%20%20%20%20if%20(foo)%20%7B%0D%0A%20%20%20%20%20%20%20%20foo.a%3B%20%2F%2F%20ERROR%3A%20Property%20'a'%20does%20not%20exist%20on%20type%20'never'.%0D%0A%20%20%20%20%7D%0D%0A%7D) (make sure to enable `strictNullChecks`)
```ts
class A {
    a: string;
}

let foo: A | undefined = void 0;
try {
    foo = new A();
    throw new Error();
} catch (e) {
    if (foo) {
        foo.a; // ERROR: Property 'a' does not exist on type 'never'.
    }
}
finally {
    if (foo) {
        foo.a; // ERROR: Property 'a' does not exist on type 'never'.
    }
}
```

**Expected behavior:**
Should compile without errors

**Actual behavior:**
Compilation fails at the indicated lines. Control flow analysis assumes that `foo` is of type `undefined` as it enters the `try` / `catch` / `finally` block, and is unable to detect that `foo` will actually be of type `A` in both the `catch` and `finally` blocks.

Likely related to #15835 and #18478

**Comment by mhegazy** [comment] 2017-10-03 22:52
Duplicate of https://github.com/Microsoft/TypeScript/issues/18478

**Comment by mhegazy** [comment] 2017-10-19 19:53
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-19 19:53 UTC
Labels: Duplicate
