### ISSUE TITLE
Re-assigning to a variable with a recursive type got unexpected type narrowing result.

### ISSUE THREAD

**Issue by ir193** [microsoft/TypeScript#38629] opened 2020-05-18 05:05 UTC
**TypeScript Version:**  3.9.2

**Search Terms:** Control Flow, Type narrowing

**Expected behavior:** 👍 Compile

**Actual behavior:** Property 'next' does not exist on type '{ type: "zero"; }'.(2339)

**Related Issues:** 28763

**Code**
```ts
type SomeType = { type : 'zero' }
              | { type : 'one', hello : string, next : SomeType };

let mutable : SomeType = { type : 'zero' };

for(let i=0; i<2; i++){
    console.log(mutable);
    if( i==0 ){
        mutable = { type : 'one', hello : "hello", next : mutable };
    } else {
        switch( mutable.type ){
            case 'zero' :
                break;
            case 'one' :
                let tmp : SomeType = mutable.next;  // this is ok 
                let s : string = mutable.hello;     // this is ok
                
                mutable = mutable.next;             // this got Property 'next' does not exist on type '{ type: "zero"; }'.
                break;
        }
    }
}

```

In the case 'one' branch, mutable should be narrowed to `{ type : 'one', hello : string, next : SomeType }`. Accessing fields including `next` is OK. But when assign it back to variable mutable back, Ian error. It seems inferring mutable has the type `{ type : 'zero' }` instead. 

<details><summary><b>Output</b></summary>

```ts
"use strict";
let mutable = { type: 'zero' };
for (let i = 0; i < 2; i++) {
    console.log(mutable);
    if (i == 0) {
        mutable = { type: 'one', hello: "hello", next: mutable };
    }
    else {
        switch (mutable.type) {
            case 'zero':
                break;
            case 'one':
                let tmp = mutable.next; // this is ok 
                let s = mutable.hello; // this is ok
                mutable = mutable.next; // this got Property 'next' does not exist on type '{ type: "zero"; }'.
                break;
        }
    }
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=3.9.2#code/C4TwDgpgBAyg9gWwgFXNAvFA3lUkoBcUA5AF4QBOcxUAvgFBRPMssA+2uahJcAdhGIAaKAAsIAGwlweAZ2AUAlnwDmIgQA9gPeElT5aAbnr0JEbQgCuwAIYAjMzsQpumHHmhEylanWP0AMzgKAAozbUV0AAZDKEUAHgAmWMUAalSASixGZgBjflk4MwA6aRUQq1sHCAzjFkUAkLj0aKgsnNYoSvtHNy58L35BEXEpGSIAIlHpCfUILR5u6r8OuihJWWhszqZZAHdFYFzRJqWSjzbtnZZcm02ScioaAlXrljsKCBsAazq3plu92IQ2er3+UHCuAQYCcelcXWsPQgxU0wFiUAA9BjcKJFLI4vi4N8oGD-pD8UR5EpVFBMGdkdM4OjmFicXiCVAiaS3tzrvTaQiqiVUcz-qzgLj8So4NoAApUSAUUAkVE0AAmcAg+L4MvWGjx2n4-WgxHcaEmjzgE1itGIxV5Ow+X1+3IYLAYDCAA)

**Comment by Thrillpool** [comment] 2020-05-19 17:52
I think this is caused by something more fundamental, namely that TypesScript isn't happy with 

```typescript
type SomeType = { type : 'zero' }
              | { type : 'one', hello : string, next : SomeType };

let mutable : SomeType = { type : 'zero' };

switch( mutable.type ){
    case 'zero' :
        break;
    case 'one' : // error is here, says 'zero' is not comparable to 'one'
        break;
}
```

Which is a bit bizarre to me, I would anticipate that the explicit cast of mutable to SomeType doesn't induce the narrowing to realise that mutable is of type { type: 'zero' }. 

The upshot is that if in your example you change it like

```typescript
....
function makeIt(): SomeType {
    return { type : 'zero' }
}

let mutable = makeIt();
...
```
It is happy.

**Comment by ir193** [comment] 2020-05-20 04:18
I think that is actually fine (or as intended). With control flow analysis, TS can make sure when it comes to switch expression, it can only be `{ type:'zero' }`. But control flow analysis somehow does not go into function. 
The point I'm trying to say here is inconsistency. In `case 'one' ` , accessing to `hello` of mutable is OK. Even accessing to `hello` is OK. That means TS already analyzed the type is ` { type : 'one', hello : string, next : SomeType }`. But if you assign it back, it somehow thinks it's another type.

**Comment by Thrillpool** [comment] 2020-05-22 18:30
Yes I understand what you mean, it does seem inconsistent. I would note that it's not quite as simple as you're describing. You're not just assigning it back, you're assigning it iteratively, so while the first call to mutable.next may be able to be verified as legitimate, subsequent calls, if you reassign, might not be.

And my initial feelings were that sicne you don't have the initial type assertion on mutable, it might be that somehow the reassignment is too narrow, and TS is always working with a narrower type then the type annotations might suggest.

All that being said, I'm confused too and have now spent a bit of my free time now trying to work it out myself. Hopefully someone can come and explain it.

**Comment by Mindar** [comment] 2020-05-22 23:08
I think this might be related to the following problem I've just encountered in TS 3.8.3.
When I create a union of two types containing a boolean I can only return the object directly, but **not** if i store it in a const before returning. If I declare the false value as a false type it works even if I store it in a const before returning.

```typescript

interface Foo {
	success: true;
	foo: number;
}

interface Bar {
	success: false;
	bar: string;
}

function works(): Foo | Bar {
	return {
		success: false,
		bar: "hello"
	};
}

function alsoWorks(): Foo | Bar {
	const result = {
		success: false as false,
		bar: "hello"
	};

	return result;
}

function fails(): Foo | Bar {
	const result = {
		success: false,
		bar: "hello"
	};

	return result;
}
```

**Closed** 2020-06-29 22:25 UTC
Labels: Bug, Fix Available
