### ISSUE TITLE
Array method thisArg type not captured

### ISSUE THREAD

**Issue by RasmusAndreassen** [microsoft/TypeScript#50943] opened 2022-09-25 17:11 UTC
The `thisArg` argument of many array methods isn't properly used to determine the type of the `this` object in the callback function. When using strict mode, this forces the source code to be quite much more verbose than necessary

for example,

```ts
const evenTester = {
	test: (a:number):boolean => (a & 1) == 0
};

const array:number[] = [1, 2, 3, 4, 5, 6];

array.forEach(
	/** callbackfn */
	function(number) {
		console.log(this.test(number)? `${number} is even` : `${number} is odd`)
	},
	/** thisArg */
	evenTester
)
```

will yield:

```
file.ts:line:col -error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.
```

whilst

```ts
const evenTester = {
	test: (a:number):boolean => (a & 1) == 0
};

const array:number[] = [1, 2, 3, 4, 5, 6];

array.forEach(
	/** callbackfn */
	function(this,number) {
		console.log(this.test(number)? `${number} is even` : `${number} is odd`)
	},
	/** thisArg */
	evenTester
)
```

will yield

```
file.ts:line:col - error TS7006: Parameter 'this' implicitly has an 'any' type.
```

with only the below properly compiling

```ts
const evenTester = {
	test: (a:number):boolean => (a & 1) == 0
};

const array:number[] = [1, 2, 3, 4, 5, 6];

array.forEach(
	/** callbackfn */
	function(this:{test: (a:number)=>boolean},number) {
		console.log(this.test(number)? `${number} is even` : `${number} is odd`)
	},
	/** thisArg */
	evenTester
)
```

**Comment by fatcerberus** [comment] 2022-09-25 18:12
This isn’t any of the behaviors described in the issue template you used.  Those behaviors would make the issue a duplicate of 9998, which this isn’t.  That’s why your issue got labeled as a duplicate.

**Closed** 2022-09-28 18:00 UTC
Labels: Duplicate

**Comment by RasmusAndreassen** [comment] 2022-10-01 07:19
@fatcerberus
Ok, I thought it would fall under incorrect type in callback function, do you know which issue template would be appropriate?
