### ISSUE TITLE
Experimental Decorator error even after specifying in tsconfig.json 

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8751] opened 2016-05-23 10:42 UTC
_From @rajeevkumarsharma on January 1, 2016 15:7_

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "noEmitOnError": false,
    "rootDir": ".",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": false,
    "sourceRoot": "",
    "inlineSourceMap": false,
    "inlineSources": false
  },
  "files": [
    "app/app.ts"
  ]
}
```
It still show error on decorator class 

_Copied from original issue: Microsoft/vscode#1730_

**Comment by dbaeumer** [comment] 2016-05-23 10:43
This works for me using the latest 0.10.6 build. See attached screen shot:

![capture](https://cloud.githubusercontent.com/assets/1931590/12112703/9b69c2f4-b39e-11e5-8103-18c8e2fe45bf.png)

@rajeevkumarsharma pls ping me if you can reproduce using 0.10.6. Steps would be helpful as well.

**Comment by dbaeumer** [comment] 2016-05-23 10:43
_From @rajeevkumarsharma on January 7, 2016 6:43_

Hi Dirk,

It still persist with 0.10.6 on Linux. Here are some screenshots attacked.

Thanks

![screenshot from 2016-01-07 12 06 20](https://cloud.githubusercontent.com/assets/8169482/12163955/9f7774c8-b537-11e5-9462-4fc0eacf05be.png)
![screenshot from 2016-01-07 12 06 35](https://cloud.githubusercontent.com/assets/8169482/12163956/9f7d5adc-b537-11e5-916e-7c9cb780dd8b.png)

**Comment by dbaeumer** [comment] 2016-05-23 10:43
Duplicates #1740

**Comment by dbaeumer** [comment] 2016-05-23 10:43
Closing

**Comment by dbaeumer** [comment] 2016-05-23 10:43
_From @SergeySolonko on May 20, 2016 12:57_

+1
Have same problem.

VScode Version 1.1.1 (1.1.1)
MacOS X El Capitan

![screen shot 2016-05-20 at 2 59 21 pm](https://cloud.githubusercontent.com/assets/8107129/15428400/784d4c2e-1e9b-11e6-99cc-fc31fb4b2332.png)

**Comment by dbaeumer** [comment] 2016-05-23 10:43
_From @AdamWillden on May 20, 2016 14:48_

I also get the same issue but it is inconsistent (1.1.1 Windows)

**Comment by dbaeumer** [comment] 2016-05-23 10:43
_From @Mosho1 on May 22, 2016 10:58_

+1, (1.1.1 on windows 10)

**Comment by dbaeumer** [comment] 2016-05-23 10:43
Moving to TS team since it still shows up on 1.1.1 which uses 1.8.9 (tsserver)

**Comment by mhegazy** [comment] 2016-05-23 22:28
From these snapshots, looks like the file you are getting the error in is not part of the tsconfig.json file.

`rest.ts` does not seem to be mapped by the `tsconfig.json` specified, which only lists `app/app.ts`. if this is the issue, then it is not going to pick up this `tsconfig.json` as a configuration source.

At this point i do not have much details to piece together a repro. please provide a project i can use to reproduce the issue.

**Comment by SergeySolonko** [comment] 2016-05-24 08:25
try with this configuration
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noImplicitAny": false,
    "outDir": "../dist/",
    "rootDir": ".",
    "sourceMap": true,
    "target": "es5",
    "inlineSources": true
  },

  "files": [
    "main.ts",
    "typings.d.ts"
  ]
}

```
I've played a lot with different versions of config, no luck

**Comment by SergeySolonko** [comment] 2016-05-24 09:47
@dbaeumer I've tried to change ```typescript.tsdk```
```
"typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib"
```
I've used 
```
$ tsc --version
Version 1.8.10
```
No luck, are you sure that this issue is related to ```tsserver``` ?

**Comment by kitsonk** [comment] 2016-05-24 11:56
From the screen shots, the file that is showing the errors is `./app/lib/rest.ts` but in both the config above and the screenshots, the `"files": []` does not include the the displayed file.  When a file is not included in the `"files"` array, they are not part of the project, and vscode will apply default compiler options, which has experimental decorators as false, which would display the errors visible in the screenshot.  I highly doubt this has anything to do with `tsserver` and instead has to do with likely an improperly configured project.

**Comment by SergeySolonko** [comment] 2016-05-24 12:02
ok, what about next example:

![screen shot 2016-05-24 at 2 01 57 pm](https://cloud.githubusercontent.com/assets/8107129/15503102/2373134e-21b8-11e6-8128-29dad163d1d5.png)

**Comment by rajeevkumarsharma** [comment] 2016-05-24 12:15
Hi,

You may use exclude instead files (where u need to put all files reference)
![screenshot from 2016-05-24 17 43 36](https://cloud.githubusercontent.com/assets/8169482/15503365/29241350-21d7-11e6-92ae-927455916e38.png)


If you want to use files options only than add all files you want to apply these settings.

**Comment by mhegazy** [comment] 2016-05-24 17:06
@SergeySolonko i can not reproduce this still.. i have your tsconfig.json, and a file and still can not see any issues.

![image](https://cloud.githubusercontent.com/assets/8000722/15512918/1d6dc6ae-2197-11e6-80e1-7ef76576df2d.png)

Please provide a repro project the exhibits the issue.

**Comment by SergeySolonko** [comment] 2016-05-24 17:19
@mhegazy https://github.com/SergeySolonko/vscode-test try this one

**Comment by mhegazy** [comment] 2016-05-24 18:06
Thanks. i see the issue now. the problem is in your tsconfig.json there is a missing file. `"typings.d.ts"`. the file does not exist which causes a problem in loading the project. we have fixed this issue in nightly builds, here is the issue: https://github.com/Microsoft/TypeScript/issues/8334, and the PR: https://github.com/Microsoft/TypeScript/pull/8504.

Removing the missing file from tsconfig.json, should resolve the issue, or updating to the latest nightly, see https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code

**Comment by mhegazy** [comment] 2016-05-24 18:06
Closing in favor of #8334

**Closed by mhegazy** 2016-05-24 18:06 UTC
Labels: Needs More Info

**Comment by SergeySolonko** [comment] 2016-05-24 18:49
That doesn't make sense, VSCode should read tsconfig and enable all specified options, It shouldn't be related to the project files. 
Other words: if experimentalDecorators option is enabled - VSCode should hide that error

**Comment by mhegazy** [comment] 2016-05-24 19:29
it is not about VSCode. this is coming from the ts side of things.

The server tries to load the config file. before #8504, if a file was not found, it failed to read the config file, which was a bug. the bug should be fixed in the latest nighties, and it should work now.
