### ISSUE TITLE
Assignability to `asserts` type predicate is not checked

### ISSUE THREAD

**Issue by gabritto** [microsoft/TypeScript#58219] opened 2024-04-16 22:43 UTC
### 🔎 Search Terms

asserts assignability

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.5.0-dev.20240416&ssl=9&ssc=2&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHJwDOx0YAFAB4BcyAriANYjoDuIAlHSWVGMWRVkwQQCI4YgNz5CvcgCE4UanUYt2XHqXKCwAC1EjBSqDIC+uXKEixEKU8ghVIIACaCMWPISI7+qgzMrBzcyCD0ALYARtAyvvL8poHqIVrIxGBQoADmFkA

### 💻 Code

```ts
interface Foo {
    assert(x: unknown): asserts x is "a";
    assertBar(x: unknown): asserts this is Bar;
}

interface Bar extends Foo {
    assert(x: unknown): number;
    assertBar(x: unknown): string;
}
```

### 🙁 Actual behavior

No errors on `Bar`.

### 🙂 Expected behavior

Errors on `Bar` about `assert` and `assertBar`'s signatures not being assignable to their counterparts in `Foo`.

### Additional information about the issue

Follow up of #57103.

**Comment by fatcerberus** [comment] 2024-04-17 03:10
Simplified repro:
```ts
declare type Asserter = (x: unknown) => asserts x is "a";
declare const fun: (x: unknown) => number;
const assert: Asserter = fun;  // no error
```

It has nothing to do with assignability checking during inheritance - it's that non-assertion functions are, in fact, assignable to assertion function types.  This is probably a side effect of `(x: unknown) => number` being assignable to `(x: unknown) => void`.

**Comment by mwoenker** [comment] 2024-05-07 13:32
I think this is effectively a duplicate of this issue https://github.com/microsoft/TypeScript/issues/49262

**Closed** 2024-05-21 17:35 UTC
Labels: Duplicate
