### ISSUE TITLE
uninitialized let doesn't error out on unreachable or never

### ISSUE THREAD

**Issue by chrisirhc** [microsoft/TypeScript#48735] opened 2022-04-17 06:25 UTC
# Bug Report

### 🔎 Search Terms

uninitialized let unsafe

### 🕗 Version & Regression Information

I was able to reproduce this on nightly `4.7.0-dev.20220416`.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/DYUwLgBA+gHgXBAdgVwLYCMQCcDaBdAbgCgAzZRAYzAEsB7RCAc3AA0AKASgRQ23wgDeRCBGokIbAISwOg4SIhZwyLA1jERAX3lKwKtTGKagA

### 💻 Code

```ts
let _x: number[];
function getX(): number[] {
  if (!_x) {
    return _x;
  }
  return _x;
}
```

### 🙁 Actual behavior

No type errors.

### 🙂 Expected behavior

Either: 
1) that the never type is found (on the first `return _x` line), and incompatible with `number[]`; 
2) that `_x` can be undefined if it has not been initialized (#30053)
3) error on unreachable code (if it is indeed deemed unreachable based on the typing)

Seems related to #30053 .

**Comment by MartinJohns** [comment] 2022-04-17 07:26
Duplicate of #23305. Used search terms: `let closure undefined`

**Comment by fatcerberus** [comment] 2022-04-17 13:44
> that the never type is found (on the first return _x line), and incompatible with number[];

`never` is the bottom type and is assignable to all other types by definition.

**Closed** 2022-04-21 18:00 UTC
Labels: Duplicate
