### ISSUE TITLE
Improve type narrowing on `switch(true)` statements

### ISSUE THREAD

**Issue by ElianCordoba** [microsoft/TypeScript#46600] opened 2021-10-30 03:28 UTC
# Bug Report

### 🔎 Search Terms

- switch narrowing
- switch(true)

🔗 Related issues

- #37178
- #8934

Maybe these ones too

- #46143
- #43873

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type guards

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBMAWBDATjAvDARACkzREM0yAlmAOYDcAUNSQGYzYIrpoYDk2HAlDAN7UYcJKgD0YkaxKEuHagF9aEAO4koCJlGQBXAKZ9Bw4AT1TU7TtwBcQ4eZgSHMotrLkANEXggdAGwATGAAjMzk7YWDkPUQAaxoFIA)

### 💻 Code

```ts
const char = "(" as string;

// This works fine, char inside the if statements get's property narrowed to type "("
if (char === '(') {
  char;
}

// This doesn't work, char inside the case statement is of type string
switch (true) {
  case char === '(':
    char;
}
```

### 🙁 Actual behavior

Char inside the case statement in a `switch(true)` has a type string

### 🙂 Expected behavior

It should have type `"("`

**Comment by MartinJohns** [comment] 2021-10-30 04:24
Duplicate of #37178.

**Closed** 2021-10-31 20:43 UTC
