### ISSUE TITLE
Visual Studio 2015 is crashed on TypeScript repository

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#8862] opened 2016-05-27 17:28 UTC
VS2015 is crashed when opening an empty `index.ts` file on TypeScript repository that has empty `index.ts` and `tsconfig.json` files.

![vs2015](https://cloud.githubusercontent.com/assets/3143368/15615716/d88a77bc-247a-11e6-9b79-1ea8fd084eee.png)

I got this problem since yesterday. I feel this problem is related to windows update.

**TypeScript Version:** 

1.8.30

**Comment by paulvanbrenk** [comment] 2016-05-27 20:29
@falsandtru do you have an activitylog `%appdata%\Microsoft\VisualStudio\14.0\ActivityLog.xml`

**Comment by falsandtru** [comment] 2016-05-27 20:41
Unfortunately, that file don't have any records for the last few days.

**Comment by paulvanbrenk** [comment] 2016-05-27 20:46
Can you share a project... and which version of TypeScript is mentioned in Help - About?

**Comment by vladima** [comment] 2016-05-27 20:49
can you check Windows Event Log `eventvwr` for any recent entries with source `.NET runtime` related to `devenv`?

**Comment by falsandtru** [comment] 2016-05-27 21:07
I sent event logs to @paulvanbrenk and @vladima . Could you review that?

**Comment by falsandtru** [comment] 2016-05-27 21:12
I already repaired VS2015 Community and reinstalled TypeScript extension, but I'm unable to recover this problem yet.

**Comment by vladima** [comment] 2016-05-27 21:13
Just to clarify, you've added empty `index.ts` and `tsconfig.json` to the root of the repo as a sibling to `src`, `scripts`, `tests`?

**Comment by falsandtru** [comment] 2016-05-27 21:17
Yes, this repro is simple.

0. Clone this TypeScript repository.
0. Create empty `index.ts` and `tsconfig.json` files to TypeScript repo's root directory.
0. Open `index.ts` file by double click.
0. VS is hanged, and will be crashed.

Can you repro?

Note: OS is Windows 7 x64

**Comment by falsandtru** [comment] 2016-05-27 21:33
Note:

- Errors will be displayed a few minutes later. Opend file `index.ts` is **always unable to input any keys**.
- This problem seems only occured on TypeScript repo. Other projects work fine.

**Comment by paulvanbrenk** [comment] 2016-05-27 21:41
I think part of the problem is there are a ton of `.ts.` files in the typescript repo, which all will be made part of the editing context in VS... this looks like it creates an Out of Memory issue.

We're working on making it better, but going to close this as Duplicate since we've seen a ton of those.

**Closed by paulvanbrenk** 2016-05-27 21:41 UTC
Labels: Duplicate, Visual Studio

**Comment by falsandtru** [comment] 2016-05-27 21:57
In short, this crash is an accepted behavior? This usage was working correctly in a few days ago. This is the undesirable change. And please give me original issue if this is duplicate.

**Comment by paulvanbrenk** [comment] 2016-05-27 22:02
No, this is no expected, and we're working on mitigations, but considering the size of the TypeScript repo this is not unexpected, and currently not supported.

I would suggest opening the `src/compiler` folder and any test cases you're working on, and not the entire repo.

**Comment by falsandtru** [comment] 2016-05-27 22:12
Okay, thanks for your kindness.
