### ISSUE TITLE
Instanceof guard doesn't work with arrow function after it

### ISSUE THREAD

**Issue by kkmuffme** [microsoft/TypeScript#51974] opened 2022-12-20 14:18 UTC
# Bug Report

### 🔎 Search Terms

instanceof arrow function type

### 🕗 Version & Regression Information

Always existed

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=9&ssc=3&pln=1&pc=1&filetype=js#code/FAYw9gdgzgLgBAIwIYCc4F44BMwgK4C2AphDAHQDmRMAogDZHGkBCAngJJYAUcA5Mil5wAlAG5gAskixYaANxIwAMgEtYJIii68QdFSADWvADRwAZngggYKyD136D8xSIDewOJ7jho8M2DAMOABtXgALIjo6MBM+AHcwFDosXgBdcS84FTM4ez1DZ1IyGFQqeBVfJCsiMBz6RhcAMkbzALIoMGIePKQoKAA5JGIRDAA+b3ynBSKSlDKyXV6oVVgFyBKKqB6+weHhEf33TMyfDoYyaIoecMjooTEPLwBfYCeHzyA)

### 💻 Code

```js
const bar = document.getElementById( 'bar' );
bar.addEventListener('click', function( clickEvent ){
    const foo = ['hello', 'world'];
    if ( clickEvent.target instanceof Element && foo.some( ( className ) => clickEvent.target.classList.contains( className ) ) ) {
        console.log( 'hello' );
    }
});
```

### 🙁 Actual behavior

Error TS2339

### 🙂 Expected behavior

No error, since I checked with instanceof already.

**Comment by MartinJohns** [comment] 2022-12-20 14:27
Duplicate of #9998.

**Closed** 2022-12-24 18:00 UTC
Labels: Duplicate
