### ISSUE TITLE
Automatic case analysis for assignment

### ISSUE THREAD

**Issue by edemaine** [microsoft/TypeScript#45473] opened 2021-08-16 16:15 UTC
# Suggestion

## 🔍 Search Terms

assignment, cases, case analysis, union, const

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

The assignment operator `=` should automatically do a case analysis for unions of const types.  In a stronger form, `=` should work in the same way like a generic type wrapping the right-hand side already works in terms of case analysis.

## 📃 Motivating Example

The following code is currently invalid, but would be made valid:

```ts
interface AB {
  a: string;
  b: number;
}

function assign(x: AB, y: AB, key: keyof AB) {
  x[key] = y[key];
}
```

[Playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIICFkG8BQzlwBcyAzmFKAOYDceyARsSAK4C290tAvjjjMyARhgAexAESJYJRAAKAB7EMAGmQBPJelUBrCBuS61ImGnQBKbHXkBtQwF1kAXnW29d7jiA)

Currently, TypeScript throws the following error, because `y[key]` naturally has type `string | number`, while `x[key]` has assignable type `string & number` which is `never`.
```
Type 'string | number' is not assignable to type 'never'.
  Type 'string' is not assignable to type 'never'.
```

But `key` has a very simple type here, a union of const types: `'a' | 'b'`.  This code would work if `key` had type `'a'` or type `'b'`.  It would be nice if TypeScript checked that all the cases are valid.

In this simple code, there's a workaround using generic types:

```ts
interface AB {
  a: string;
  b: number;
}

function assign<Key extends keyof AB>(x: AB, y: AB, key: Key) {
  x[key] = y[key];
}
```

I suggest that TypeScript assignments do the automatic case analysis in at least these simple cases, to avoid having to wrap all assignments in a generic `assign` function such as this..

More generally, we can imagine any assignment `lhs(a, b) = rhs(a, b)` (where I'm viewing `lhs` and `rhs` as macros/parse trees, with `a` and `b` being the identifiers they use) being checked in the same way as
```ts
(function<A extends typeof a, B extends typeof B>(a: A, b: B): typeof rhs(a, b) {
  return lhs(a, b) = rhs(a, b);
}) (a, b)
```
(but without the additional scope that this closure would imply)

## 💻 Use Cases

Assignments are a common operation. For example, the pattern `x[key] = y[key]` appears when duplicating objects manually (`Object.keys(y, (key) => x[key] = y[key])`).

For a more complicated example, see [this StackOverflow question](https://stackoverflow.com/questions/68804981/type-string-number-is-not-assignable-to-type-never-in-switch-statement), which motivated me to write this feature request.  In the context of a `switch` statement, it's pretty inconvenient to add a `Key` type as in the above workaround.

**Comment by jcalz** [comment] 2021-08-16 17:03
Duplicate of or strongly related to #32693, although the particular suggestion of “automatic case analysis” reminds me of #25051.

**Comment by edemaine** [comment] 2021-08-16 20:42
@jcalz Thanks for finding that! (And sorry for missing it.)  I assume protocol is I should copy over the relevant ideas into #32693 and close this issue?

**Closed** 2021-08-19 18:00 UTC
Labels: Duplicate
