### ISSUE TITLE
Inconsistency between destructuring and object access in filter-narrowing.

### ISSUE THREAD

**Issue by sparecycles** [microsoft/TypeScript#59581] opened 2024-08-09 21:04 UTC
### 🔎 Search Terms

filter narrow destructuring

### 🕗 Version & Regression Information

This is recent functionality, in 5.5, I think?  (type narrowing via array filter functions).

### ⏯ Playground Link

https://www.typescriptlang.org/play/?target=7&jsx=0&ts=5.5.4#code/KYDwDg9gTgLgBAbwL4G4BQaCGBnAngOwGM4AzAVyJgEsJ84QAKASkTTnbimBjKjoHIAFsAA2IiP3RIMDTAHdMVeAAUoEALZVswAHSYxAZW4wRwACYMA2oyYBdJkzZwdJKiJjAoDBthYBeAD44bB1sGEwebDg-GLgAInIRVzFzOMd2HXVMMG8EOAA3fTJgOCR-IMKRYqZ0NFkFJThVDS1dfREjGBNzKxt7dOdkjy8GPLCIsiiy6KDxyOjYhLIkt1MzNKdM7NyCopLpwN2q4BqMM-O0IA

### 💻 Code

```ts
async function x() {
    return 'hello';
}

(await Promise.allSettled([x()]))
  .filter((s) => s.status === "fulfilled") // narrows type to PromiseFulfilledResult<string>[]
  .map(({ value }) => value);

(await Promise.allSettled([x()]))
  .filter(({ status }) => status === "fulfilled") // does not narrow type
  .map(({ value }) => value); // unsure that value exists
```

### 🙁 Actual behavior

<img width="683" alt="image" src="https://github.com/user-attachments/assets/22fb993d-e15c-494a-940d-9c6ab43ec026">

### 🙂 Expected behavior

Expect the destructured version to narrow the element type as well.

### Additional information about the issue

I found https://github.com/microsoft/TypeScript/issues/28311 when searching for existing bugs, looks like it can be closed by the existing 5.5 features, good work!

**Comment by IllusionMH** [comment] 2024-08-09 21:39
Looks like duplicate of #59497

**Closed** 2024-08-12 01:32 UTC
Labels: Duplicate
