### ISSUE TITLE
Tuple array defined in interface isn't recognized 

### ISSUE THREAD

**Issue by nugaon** [microsoft/TypeScript#43392] opened 2021-03-26 13:49 UTC
# Bug Report

### 🔎 Search Terms
tuple array interface recognized

### 🕗 Version & Regression Information
4.1.3

- This is the behavior in every version I tried
- I was unable to test this on prior versions because I didn't want to (just kidding I tried out in playground versions).

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwg9gOwGYBsCWBjYUC8UDaAzsAE5oIDmANFMWZQLoBQT5wEJSAhhtAJLxk6LFADeTKFAyJUmYIQBcsGcOD5mAXxYYUXQoWVC5MXfqhoAtmBQQLEBPKgCVcsRKkusBvPnwByADcLND8aQOC-Bk0gA)

### 💻 Code

```ts
type Conflict = [string, string]

interface IConflict {
  conflicts: Conflict[]
}

class ConflictClass implements IConflict {
  conflicts = [['foo', 'bar']]
}
```

### 🙁 Actual behavior

It doesn't recognize the correct touple array definition at the class property initialization. 

Error message:
> Property 'conflicts' in type 'ConflictClass' is not assignable to the same property in base type 'IConflict'.
  Type 'string[][]' is not assignable to type 'Conflict[]'.
    Type 'string[]' is not assignable to type 'Conflict'.
      Target requires 2 element(s) but source may have fewer.ts(2416)

### 🙂 Expected behavior

It does.

**Comment by MartinJohns** [comment] 2021-03-26 14:20
Duplicate of #10570.

**Closed** 2021-03-28 18:00 UTC
Labels: Duplicate
