### ISSUE TITLE
noImplicitReturns does not take account of a never return

### ISSUE THREAD

**Issue by daveholladay** [Microsoft/TypeScript#18841] opened 2017-09-29 16:42 UTC
**TypeScript Version:**  2.5.2

**Code**

```ts
function foo(): never {
    throw new Error()
}

function bar(): number {
    if (Math.random() > 0.5)
        return 1;

    foo();
    // compiler should realise we can't get here.
}
```

**Expected behavior:**
Compiles without warnings when compiled with --noImplicitReturns

**Actual behavior:**
error TS7030: Not all code paths return a value.

**Comment by DanielRosenwasser** [comment] 2017-10-01 08:57
If we did this, every single expression statement to a function call would need to tie into the control flow graph which would likely be prohibitively expensive, but we should discuss it anyway.

**Comment by weswigham** [comment] 2017-10-01 23:02
@rbuckton started looking into expanding flow control analysis to allow it to operate for `throw` expressions in #18798, so we're already looking into it.

**Comment by rbuckton** [comment] 2017-10-02 00:03
@bterlson mentioned a similar issue, wanting to be able to use `process.exit()`, but I don't think `never` is the correct type for this case.

**Comment by mhegazy** [comment] 2017-10-04 17:54
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/10470. The main issue really here is how these two features are implemented. implicit return checks happen earlier in the binder. where as control flow analysis happens later on when we are checking. merging the two is not a trivial task.

**Comment by mhegazy** [comment] 2017-10-19 19:53
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-19 19:53 UTC
Labels: Duplicate

**Comment by ethanresnick** [comment] 2018-02-12 05:15
Is there a remaining open issue to track this? If not, should there be? I realize it's hard to implement, but maybe it's worth keeping open as a request? (#10470 has also been closed.)

**Comment by RyanCavanaugh** [comment] 2018-02-12 17:23
@ethanresnick We'd prefer that open issues be actionable rather than serve as an infinite-scroll TODO list. Issues don't need to be open for us to be able to see activity on them
