### ISSUE TITLE
TypeScript Library project type in Visual Studio

### ISSUE THREAD

**Issue by vivmaha** [Microsoft/TypeScript#2466] opened 2015-03-23 19:12 UTC
Just a suggestion, but it would be very cool if one could create a TypeScript Library project to contain nothing but TypeScript files, which would compile to a single JavaScript file that could then be linked from other projects. Maybe have a Definitions folder to contain .d.ts files. If the source-map-based debugging could be made to work with this project type, then even better. 

 I'm guessing the project would need the same kind of ordering semantics as F# projects, so that the output was concatenated in the correct order. 

 Since TypeScript's raison d'etre is large-scale applications, it would seem to make sense to support this level of componentization in a Visual Studio solution, right?

**Comment by RyanCavanaugh** [comment] 2015-03-23 20:00
Duplicate of #11

**Closed by RyanCavanaugh** 2015-03-23 20:00 UTC
Labels: Duplicate, Suggestion
