### ISSUE TITLE
A type parameter does not appear as a completion item for an unfinished signature

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1429] opened 2014-12-10 02:35 UTC
The completion list should include T at the end of the line in the following case:
```ts
function f<T>(x: T
```

Note that this works if you add a closing paren to finish the parameter list.

**Comment by mhegazy** [comment] 2015-03-12 04:35
Dupe of #1410

**Closed by mhegazy** 2015-03-12 04:35 UTC
Labels: Bug, Duplicate
