### ISSUE TITLE
Broken type inference for union of function and object

### ISSUE THREAD

**Issue by Danksa** [microsoft/TypeScript#59573] opened 2024-08-09 11:07 UTC
### 🔎 Search Terms

function union infer

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Structural vs Instantiation-Based Inference

### ⏯ Playground Link

https://www.typescriptlang.org/play/?jsx=0#code/C4TwDgpgBAYgrgOwMbAJYHsEEMA2BhdAWzEwgWAB4AVAPigF4oAKMAJ3TAGcAuKKgSgZ1OwVqgQBzANwAoGUkwiowCEsbUaLdl14BvKADdccVbyoBtALoAaKJwg4IKCABMzUAL6D6dXTKgBUAoISrpGOCactvaOzi4eDFBsHJyygVCsEMBwrAhQAAYqIrwAJGHGqh7RDk4qblBlMbWuHvmyHrLBSgTEpOQAClicIgAW7HASI4kaTArEvPDIaJi4PSQIZJS0-AuIKBjY+ETrmxpCQcey8orAUGt9wACCE4Sb07Szx7tLB6vHDxodrA9stDvcNuQzgAyKD6VD1BBwQgAIwgrE85wA8siAFa1AB0Q04qAkCE+xFscPqAEYAAyefhXLq3LCJcGbQbDYBjdATEZMIrARnXEK3ZFs-4Qp4vTYC1RCqRAA

### 💻 Code

```ts
type FunctionalComponent<T> = (props: T) => string;

const test = <T>(props: { values: T[], selected: T }) => {
    const {values, selected} = props;
    return `test: ${values}, selected: ${selected}`;
};
const ComponentPassthrough = <T>(comp: FunctionalComponent<T>): FunctionalComponent<T> => comp;

const ComponentAugment = <T>(comp: FunctionalComponent<T>): FunctionalComponent<T> & { id: number } => Object.assign(comp, { id: 10 });

const a = ComponentPassthrough(test);
const b = ComponentAugment(test);
```

### 🙁 Actual behavior

Typescript cannot infer/passthrough the type parameter in ComponentAugment

### 🙂 Expected behavior

It should resolve ComponentAugment the same way it does with ComponentPassthrough, but with the added id property in this case. The expected type of b in this example should be:
``` ts
(<T>(props: {
    values: T[];
    selected: T;
}) => string) & { id: number }
```

**Comment by jcalz** [comment] 2024-08-09 13:18
Essentially a duplicate of #49505.  TS has quite limited support for higher order function type inference; it's implemented at #30215 and mentions the very specific circumstances in which you can expect it to work. As soon as you do something like add that intersection, it stops working.

**Closed** 2024-08-12 01:32 UTC
Labels: Duplicate
