### ISSUE TITLE
[JS] IntelliSense disregards properties if prototype defined by assigning object

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#10736] opened 2016-09-06 21:22 UTC
_From @odonyde on September 2, 2016 12:18_
- VSCode Version: 1.4.0
- OS Version: Windows 10 Pro 1607
- Language: JavaScript

I observed that IntelliSense disregards any property inherited from the object's prototype in case the prototype is defined by assigning an object. For example, IntelliSense does not show property 'greet' in the screenshot below.
![vscode-intellisense-02](https://cloud.githubusercontent.com/assets/21695902/18188632/06e87f54-708a-11e6-96e0-4e787e506b7e.jpg)

IntelliSense only lists an inherited prototype property in case it is defined individually (see second screenshot).
![vscode-intellisense-01](https://cloud.githubusercontent.com/assets/21695902/18188606/ddd89b6c-7089-11e6-9c4d-1c45cf6b959f.jpg)

I would expect that IntelliSense presents inherited properties also in case the object's prototype is defined by assigning an object.

_Copied from original issue: Microsoft/vscode#11450_

**Comment by odonyde** [comment] 2016-09-07 02:24
@waderyan Thanks for taking a look into this! I really like the concept of VSCode and am currently evaluating if we could use it as our primary code editor. Unfortunately IntelliSense doesn't work for me on any libraries that follow the above mentioned Prototype Pattern with assigned object literal or the Revealing Prototype Pattern (I submitted a separate issue for the second case: Microsoft/vscode#11610).

**Comment by mhegazy** [comment] 2016-12-16 00:50
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/7046

**Closed** 2016-12-16 00:50 UTC
Labels: Duplicate, Salsa, Suggestion, VS Code Tracked
