### ISSUE TITLE
generic type deduction affected by unrelated factors

### ISSUE THREAD

**Issue by albert-mirzoyan** [Microsoft/TypeScript#26946] opened 2018-09-06 21:19 UTC
**TypeScript Version:**  3.1.0-dev.201808331

**Search Terms:** generic type deduction 

The generic type deduction does something odd. The type deduction should not be affected by extends like it does in this example. Also type "magic" also affects the behavior while all the parts do what they suppose to do. 

**Code**

```ts
class Some {
    foo() { }
    bar() { }
    some:number
    other:string
}
type FunctionPropertyNames<T> = { [K in keyof T]: T[K] extends Function ? K : never }[keyof T];
type T1 = FunctionPropertyNames<Some> //this is "foo" | "bar" which is good. 
interface Result<T> {
    test: T
}
function fun1<E, P extends FunctionPropertyNames<E>>(ctor: {new(...args: any[]): E}, prop: P): Result<P> {
    return ;
}
function fun2<E, P extends keyof E>(ctor: { new(...args: any[]): E }, prop: P): Result<P> {
    return;
}
function fun3<E, P extends "foo"|"bar">(ctor: { new(...args: any[]): E }, prop: P): Result<P> {
    return;
}
let k1 = fun1(Some, "foo") //infer Result<"foo" | "bar"> WHY?
let k2 = fun2(Some, "foo") //infer Result<"foo">
let k3 = fun1(Some, "foo" as "foo") //infer Result<"foo">. Really?
let k4 = fun3(Some, "foo") //infer Result<"foo">


```

**Expected behavior:**
k1 should be Result<"foo">

**Actual behavior:**
k1 deduced to be Result<"foo" | "bar">

**Playground Link:** 
[Playground Link](https://www.typescriptlang.org/play/index.html#src=class%20Some%20%7B%0D%0A%20%20%20%20foo()%20%7B%20%7D%0D%0A%20%20%20%20bar()%20%7B%20%7D%0D%0A%20%20%20%20some%3Anumber%0D%0A%20%20%20%20other%3Astring%0D%0A%7D%0D%0Atype%20FunctionPropertyNames%3CT%3E%20%3D%20%7B%20%5BK%20in%20keyof%20T%5D%3A%20T%5BK%5D%20extends%20Function%20%3F%20K%20%3A%20never%20%7D%5Bkeyof%20T%5D%3B%0D%0Atype%20T1%20%3D%20FunctionPropertyNames%3CSome%3E%20%2F%2Fthis%20is%20%22foo%22%20%7C%20%22bar%22%20which%20is%20good.%20%0D%0Ainterface%20Result%3CT%3E%20%7B%0D%0A%20%20%20%20test%3A%20T%0D%0A%7D%0D%0A%0D%0Afunction%20fun1%3CE%2C%20P%20extends%20FunctionPropertyNames%3CE%3E%3E(ctor%3A%20%7Bnew(...args%3A%20any%5B%5D)%3A%20E%7D%2C%20prop%3A%20P)%3A%20Result%3CP%3E%20%7B%0D%0A%20%20%20%20return%20%3B%0D%0A%7D%0D%0Afunction%20fun2%3CE%2C%20P%20extends%20keyof%20E%3E(ctor%3A%20%7B%20new(...args%3A%20any%5B%5D)%3A%20E%20%7D%2C%20prop%3A%20P)%3A%20Result%3CP%3E%20%7B%0D%0A%20%20%20%20return%3B%0D%0A%7D%0D%0Afunction%20fun3%3CE%2C%20P%20extends%20%22foo%22%7C%22bar%22%3E(ctor%3A%20%7B%20new(...args%3A%20any%5B%5D)%3A%20E%20%7D%2C%20prop%3A%20P)%3A%20Result%3CP%3E%20%7B%0D%0A%20%20%20%20return%3B%0D%0A%7D%0D%0Alet%20k1%20%3D%20fun1(Some%2C%20%22foo%22)%20%2F%2Finfer%20Result%3C%22foo%22%20%7C%20%22bar%22%3E%20WHY%3F%0D%0Alet%20k2%20%3D%20fun2(Some%2C%20%22foo%22)%20%2F%2Finfer%20Result%3C%22foo%22%3E%0D%0Alet%20k3%20%3D%20fun1(Some%2C%20%22foo%22%20as%20%22foo%22)%20%2F%2Finfer%20Result%3C%22foo%22%3E.%20Really%3F%0D%0Alet%20k4%20%3D%20fun3(Some%2C%20%22foo%22)%20%2F%2Finfer%20Result%3C%22foo%22%3E)
**Related Issues:**

**Comment by mattmccutchen** [comment] 2018-09-06 23:08
I believe this is a design limitation.  TypeScript's heuristic is that a literal type inferred for a type parameter is widened to the primitive type unless that type parameter has a constraint involving primitive or `keyof` types.  (See `hasPrimitiveConstraint` in the [checker](https://raw.githubusercontent.com/Microsoft/TypeScript/c401d63c5f0fb937ce53f499ba3872b24470b0fc/src/compiler/checker.ts).)  `fun2` and `fun3` meet the condition to skip widening, while `fun1` doesn't.  To make `fun1` work, you could intersect `FunctionPropertyNames<E>` with `keyof E`, which will make the inference work without changing the final constraint once `E` is known.

**Comment by albert-mirzoyan** [comment] 2018-09-06 23:44
@mattmccutchen Thank you for the workaround.
IMHO if the heuristics understands that the literal type "foo" should be widened to ("foo"|"bar") and not to (string) then it should skip widening. I don't see any sense in widening to ("foo"|"bar"), to (string) yes definitely.

**Comment by mattmccutchen** [comment] 2018-09-06 23:53
What I believe is happening is that the candidate `"foo"` for `P` is being widened to `string` and then being discarded because it doesn't satisfy the evaluated constraint `FunctionPropertyNames<E> = "foo" | "bar"`.  There are no candidates left, so the evaluated constraint `"foo" | "bar"` is used.  We could debug the compiler to be sure.

**Comment by ahejlsberg** [comment] 2018-09-07 00:32
This is a duplicate of #25215. As @mattmccutchen explains above, the issue is that the `FunctionPropertyNames<T>` type isn't considered a primitive type, so the string literal is widened during type inference. Intersecting with `string` as suggested in #25215 fixes the issue:

```ts
type FunctionPropertyNames<T> = { [K in keyof T]: T[K] extends Function ? K : never }[keyof T] & string;
```

**Closed** 2018-09-07 00:32 UTC
Labels: Duplicate
