### ISSUE TITLE
Parameter types checked while shadowing a static method

### ISSUE THREAD

**Issue by pfusik** [microsoft/TypeScript#52408] opened 2023-01-25 13:45 UTC
# Bug Report

### 🔎 Search Terms

- TS2417
- shadowing static method

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about TS2417

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/MYGwhgzhAEBKCmwAuYB2BzE9oG8CwAUNNAA4CuARiAJbDQQpK3TABO8YS8AFAO7UATJAAsAXNFRkAthXisANNGHxq6YUnGSZcgJTRxCZGkzZ8RYtHZIyrVBPi84iFBizcdAbkLEAvoT8EhKCQMADKAI5kYOzQ8AAeXKgCMIYuJrjepJQ0dAyczGwcXNwQ1ABe8JrSsgosAPYgdaziDKzUGHriEVExZhaW8Na29o7d0TyemQEBQA)

### 💻 Code

```ts
class Rectangle {
  public static create(width: number, height: number) : Rectangle {
    return new Rectangle();
  }
}

class Square extends Rectangle {
  public static create(size: number, color: string) : Square {
    return new Square();
  }
}
```

### 🙁 Actual behavior

    shadow-static-method.ts:7:7 - error TS2417: Class static side 'typeof Square' incorrectly extends base class static side 'typeof Rectangle'.
      Types of property 'create' are incompatible.
        Type '(size: number, color: string) => Square' is not assignable to type '(width: number, height: number) => Rectangle'.
          Types of parameters 'color' and 'height' are incompatible.
            Type 'number' is not assignable to type 'string'.

    7 class Square extends Rectangle {
            ~~~~~~


    Found 1 error in shadow-static-method.ts:7

I'm confused about why the signatures of these methods are compared?
The code compiles if I remove the `color: string` parameter.

### 🙂 Expected behavior

<!-- What you expected to happen instead, and why -->
Code compiles successfully. `Rectangle.create` and `Square.create` can be called.

**Comment by jcalz** [comment] 2023-01-25 13:48
Duplicate of #4628

**Closed** 2023-01-28 18:00 UTC
Labels: Duplicate
