### ISSUE TITLE
Feature: Reject `foo as Promise<null> === null` 4.3.2

### ISSUE THREAD

**Issue by devinrhode2** [microsoft/TypeScript#44510] opened 2021-06-08 16:27 UTC
<img width="690" alt="Screen Shot 2021-06-08 at 11 24 24 AM" src="https://user-images.githubusercontent.com/539816/121222704-64d9d800-c84c-11eb-9c75-38f754f05c1b.png">

https://www.typescriptlang.org/play?target=8&strict=true#code/IYZwngdgxgBAZgV2gFwJYHsL3egFAShgG8AnAU2QRKwEYBfAKCYBsKZgYBebPfB1ODFwdOomBATNmhIgxjyYUTCHSsAdM3QBzXAHJkAC1QgYx9jABGCLQBpFmACao0mGAHdUU8WQBuZEpZkMMgkCGRqunx0QA

Tested not working as expected in version 4.3.2

My apologies if this is a duplicate.

**Comment by MartinJohns** [comment] 2021-06-08 17:08
You forgot to fill out the issue template.

---

Duplicate of #11920. Search terms used: `null compare in:title`

**Closed** 2021-06-11 20:37 UTC
Labels: Duplicate
