### ISSUE TITLE
Improve checking of signature help reason

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#25405] opened 2018-07-03 15:54 UTC
**TypeScript Version:**  master

See https://github.com/Microsoft/TypeScript/pull/24915/files#r199650123

Currently the contents of `SignatureHelpTriggerReason` is unused, we just check for `kind === "characterTyped"` and if we're currently in a string.

**Comment by DanielRosenwasser** [comment] 2018-07-03 17:49
Duplicate of #25393?

**Closed** 2018-07-03 17:52 UTC
Labels: Bug, Domain: Signature Help
