### ISSUE TITLE
satisfies operator for generic type constraints

### ISSUE THREAD

**Issue by manucorporat** [microsoft/TypeScript#51679] opened 2022-11-29 08:26 UTC
# Suggestion

I would love to use the new `satisfies` in generic type constrains instead of `extend` because of its ability to detect the conformance of a type with a wider one.

## 🔍 Search Terms

satisfies, generic, constrains, extend, 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

We need to make sure one type is JSON serializable, thanks to recursive types this is now possible, however we also want developers to specify an exact interface for strong types. Today, there is not easy way to check if the provided interface is JSON serializable!

```ts
// Let's assume that we expect that only data which is JSON serializable is a valid response.
type JSONValue =
    | string
    | number
    | boolean
    | undefined
    | null
    | { [key: string]: JSONValue }
    | Array<JSONValue>;


export interface MyData {
    foo: string,
    thisShouldBeAnError?: Date;
}

type FactoryFunction<RET satisfies JSONValue> = () => RET;

export const problematicFactory: FactoryFunction<MyData> = () => {
    return {
        foo: 'ok', 
        thisShouldBeAnError: new Date(),
    };
}
```

## 💻 Use Cases

- Provide even better types when right now any is the only option
- Values that can be serializable, JSON, SQL, any complex recursive type
- Simplified types and less typing since the satisfied operator is part of the generic type

**Comment by MartinJohns** [comment] 2022-11-29 08:50
It sounds like a duplicate of #14520 to me.

**Comment by manucorporat** [comment] 2022-11-29 13:16
Maybe! but sounds like with the introduction with already have a semantic of how this could be implemented

**Comment by jcalz** [comment] 2022-11-29 15:02
This doesn't look like a lower bound.  Actually, I'm not sure what it is.  

@manucorporat could you clarify what you're trying to do? Even without `thisShouldBeAnError`, a value of type `MyData` does not satisfy `JSONValue`, due to #15300:

```ts
interface MyData {
    foo: string,
}

declare const myData: MyData

const oops = myData satisfies JSONValue; // error!
```
[playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAUgygeQHIDUCGAbArtAvAKCiKgB8oBnYAJwEsA7Ac0OLLqwFsAjCK5oszgHtBGCGjp9SULHQAmEAGb0IsyaywYMaqAG8oAbQDWEEAC4K1egwC65+MnTZoAX20BBKlTQgAPPdSYOAB8ANz44RAAHmCCVMBQ9MA8CmgAxtAAsiAAImjAaLqSCsLmlLSMADSSAPTVxMAAFjTkcA2CGrIAQhBudACinrEA-Oa5SWGu+PKpGGhU0KmCdJRQ7Dl5aOZZY2jhi8vxwmDkULir6-kUec1KECf+jjghULVQPFSxAIThQA)


What, specifically, would `T satisfies U` accomplish that `T extends U` does not?

**Comment by RyanCavanaugh** [comment] 2022-12-02 01:02
This isn't well-specified enough to be actionable. It seems like you're asking for either negated types, type parameter upper bounds, or possibly exact types, all of which have open issues already.

**Closed by RyanCavanaugh** 2022-12-02 01:02 UTC
Labels: Suggestion, Declined

**Comment by fatcerberus** [comment] 2022-12-02 01:07
…or possibly even `oneof`-style constraints.

**Comment by galenjiang** [comment] 2023-03-03 09:36
Some thing likes [Opaque Result Types](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/opaquetypes)  in Swift

**Comment by hiddenist** [comment] 2023-09-20 01:39
I'm running into this same problem - I'm not sure if there's even a way to check what I want right now. Here's a [TS playground example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggNnA9gdwgEwGoEM4FcIAq40AvFAM7ABOAlgHYDmUAPlHbgLYBGEVAUKEiwEKdNjwQAShADGiKmihlpchQB5KtRgBphSVJhz4ikAHx8BxPaMMTyAMVx0ZwGojpqCUCAA9gEOjRyawNxfBV5NFMlKAAKADcjCHIALigCAEolaPjEGjQLAHpCqABacvKoYot6fyoAMywZaABZEAAFKkQwYIBvPihBqA5k8iwGCDTNegYBocSJNPZuXjnBmnJ4fXQAfjSuREQ4CCw6PgBfGro6xuaoAHlgAAteTu6+tagQZLSAIgBJKBYDhAijUGa-T4gXBgfaHY6nC4WOR0ShQZ4bADKT0QuDgaAAQhB7PRJlA2m8ejF+kNhqNxmTfi8RL9tJ8Fvg0gBGC4ULCucj1GjJEJiJIRBTI9xojHkbG4-EAOUQwCJJLoZIpXSpZBpQxG5DGEz+zKQrPZSW5bNpxSgAAFgORSr5IC5nVQuvxaRstjY0o04OQIGzznyBUKRb7QuLZJEiiUHU6XbJgO7PVB5XjFI0aHAoDwZFhcEGoAADH0iAylqAbUEHI4nM4otF0FVR9Bpdu2fAOJwuNweLXvaJkWJZEjRXqXPi2ghPWvkHFZ-PQHDbArN4BAysd0Xd5KOZyudxqR4vKiU8gjuLjyeXWkPx9P59P20APSggK4WHINELCBAKAACtiy3ZBTi3WV0UQKAZBeGQAGsww2CNyD4IA)


```ts
type AllowedValueType = string | number
type AllowedValueRecord = Record<string, AllowedValueType>

type AllowedValuesFunction<T extends AllowedValueRecord> = (values: T) => void

// ----- //

interface MyProps {
    message: string
    value: number
    isAllowed?: boolean
}

interface OtherProps {
    yes: "I am a string"
    yup: boolean
}

const thisShouldBeFine: MyProps = {
    message: "hello",
    value: 1
} satisfies AllowedValueRecord

const thisShouldNotBeFine: MyProps = {
    message: "hello",
    value: 1,
    // @ts-expect-error
    isAllowed: false,
} satisfies AllowedValueRecord

// @ts-expect-error Should fail because `isAllowed` is a boolean
const notAllowed: AllowedValuesFunction<MyProps> = () => {}

// This should be allowed
const allowed: AllowedValuesFunction<OtherProps> = () => {}
                                     // ^ I basically just want this to check satisfies

```

**Comment by sinclairnick** [comment] 2024-05-21 05:13
> `X extends Y` means that `X` is a _subset_, not a superset.

@fatcerberus Is this true? If `X` were a superset wouldn't that entail `{ a: number } extends { a: number, b: number }` is `true`?

Or am I somehow confusing my definitions here?

**Comment by fatcerberus** [comment] 2024-05-21 14:15
Yes, it’s true.  Subset vs. superset are in terms of which values are assignable to it, not in terms of their properties.  `{ a: number, b: number }` is a subset of `{ a: number }` because the latter consists of only those members of the former that also have a numeric `b` property.

(I suspect you may have misread that @sinclairnick - I’m specifically saying there that `X` is *not* a superset.)

**Comment by sinclairnick** [comment] 2024-05-21 21:16
I see.So superset and subset in this context have a different definition to the strictly mathematical one - or at least how I interpret it.So in math we might say {2} is a subset of {2,3}, in TS I was thinking in terms of properties as members of the set. Instead you’re saying the correct interpretation is that a subset is “that which can be assigned to a type”?So since {2,3} is _assignable_ to {2}, it would be a subset, in typescript parlance?Have I got this right?On 22 May 2024, at 2:16 AM, Bruce Pascoe ***@***.***> wrote:﻿
Yes, it’s true.  Subset vs. superset are in terms of which values are assignable to it, not in terms of their properties.  { a: number, b: number } is a subset of { a: number } because the latter consists of only those members of the former that also have a numeric b property.
(I suspect you may have misread that @sinclairnick - I’m specifically saying there that X is not a superset.)

**Comment by jcalz** [comment] 2024-05-21 21:22
See [this q/a](https://stackoverflow.com/q/38855908/2887218). Think of a type as the set of values that have that type. Then a subtype corresponds to a subset, and a supertype corresponds to a superset. If you think of object types specifically and only of their sets of declared properties, then you'll be thinking of things "backwards" because `keyof` is contravariant.
