### ISSUE TITLE
Visual Studio 2013 - No able to resolve angular, compile or debug

### ISSUE THREAD

**Issue by acostaf** [Microsoft/TypeScript#8784] opened 2016-05-24 16:14 UTC
Hi everybody

I am using version 1.8.2 installed on Visual Studio 2013 and I am facing lots of issues working with 
the latest version of angular 2 rc1, visual studio 2013 does not discover the right types embedded on angular folder throwing "Cannot find module '@angular/core'", "Cannot find module '@angular/platform-browser-dynamic'",etc since I am not able to compile those into js cannot run my project if I use tsc from npm to regenerate js and maps  them my project does not attach to the debugger.

Any idea?

**Comment by mhegazy** [comment] 2016-05-26 21:09
I am assuming you are following the steps in https://angular.io/docs/ts/latest/quickstart.html, or something similar to it, and that is not working. the issue is probably that VS 2013 does not pick up the correct configurations from the `tsconfig.json` file.

Please note that `tsconfig.json` is not supported in VS 2013. and there are no plans to add support for it in the future. VS 2015 does have that.

You can define the same configuration you are using in the project file. for instance:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  }
}
```
cna be defined in the project file as:
```XML
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TypeScriptTarget>ES5</TypeScriptTarget>
    <TypeScriptModuleKind>commonjs</TypeScriptModuleKind>
    <TypeScriptModuleResolution>node</TypeScriptModuleResolution>
    <TypeScriptSourceMap>True</TypeScriptSourceMap>
    <TypeScriptEmitDecoratorMetadata>True</TypeScriptEmitDecoratorMetadata>
    <TypeScriptExperimentalDecorators>True</TypeScriptExperimentalDecorators>
    <TypeScriptRemoveComments>False</TypeScriptRemoveComments>
    <TypeScriptNoImplicitAny>True</TypeScriptNoImplicitAny>
  </PropertyGroup>
```

you will need to right-click unload the project, then edit the XML file manually.

here is the mapping between the tsconfig property names and the MSBuild property tags: http://www.typescriptlang.org/docs/handbook/compiler-options-in-msbuild.html

**Comment by acostaf** [comment] 2016-05-27 08:19
Hi @mhegazy 

Already done that thanks, that fixed some of the issues but still remain one of the main one, compilation time see in here https://github.com/angular/angular/issues/8812.

Basically 1.8.2 version install in vs2013 does not auto discover TS types embedded from angular packages e.g '@angular/core' or '@angular/platform-browser-dynamic' or pretty much everything from angular then if you force the references into  t.ds.ts file completely ignored them.

I have also done this testing at home with VS2015 with TS version 1.8.4 and works fine, so is there any beta that I can use for VS2013 ? or do you know another workaround to the issue?

**Comment by mhegazy** [comment] 2016-05-27 15:57
Have u set the moduleResolution as I mentioned above? If so and it still does not work please share your project file.

**Comment by acostaf** [comment] 2016-05-27 16:56
HI @mhegazy the key to resolve the modules starting by '@angular/...' was commonjs, however now I am getting issues with those two kind of import { Observable } from 'rxjs/Observable';
and 'rxjs/Rx'

Error	2	Invalid module name in augmentation, module '../../Observable' cannot be found

**Comment by mhegazy** [comment] 2016-06-01 23:40
looks like you are running into https://github.com/Microsoft/TypeScript/issues/8518. this issue has been fixed in master, but has not been released in a VS installer.
I have some notes for a workaround in https://github.com/Microsoft/TypeScript/issues/8518#issuecomment-223156931

**Closed by mhegazy** 2016-06-01 23:40 UTC
Labels: Question
