### ISSUE TITLE
use default generic type automatically 

### ISSUE THREAD

**Issue by tylim88** [microsoft/TypeScript#54830] opened 2023-06-29 17:17 UTC
# Suggestion

## 🔍 Search Terms

use default generic type automatically 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* ✅ This wouldn't be a breaking change in existing TypeScript/JavaScript code
* ✅ This wouldn't change the runtime behavior of existing JavaScript code
* ✅ This could be implemented without emitting different JS based on the types of the expressions
* ✅ This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* ✅ This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

```ts
type A<X = 1, Y = 2, Z = 3> = { x: X, y: Y, z: Z }

type B = A<10, "use default", 5> // { x: 10, y: 2, z: 5 }
```

## 📃 Motivating Example

Make it safer to use default without creating extra type:

usually we do:
```ts
type two = 2

type A<X = 1, Y = two, Z = 3> = { x: X, y: Y, z: Z }

type B = A<10, two, 5> // { x: 10, y: 2, z: 5 }
```
but this is prone to mistake

```ts
type two = 2
type three = 3

type A<X = 1, Y = two, Z = 3> = { x: X, y: Y, z: Z }

type B = A<10, three, 5> // { x: 10, y: 3, z: 5 }, accidentally assign the wrong type
```

**Comment by fatcerberus** [comment] 2023-06-29 17:19
Duplicate of https://github.com/microsoft/TypeScript/issues/26242

**Closed** 2023-06-29 17:21 UTC
Labels: Duplicate
