### ISSUE TITLE
Return type of an inherited static method returning "new this()" is incorrectly the base class, but it's the child class in runtime

### ISSUE THREAD

**Issue by TomMarius** [Microsoft/TypeScript#11793] opened 2016-10-22 09:18 UTC
**TypeScript Version:**  2.0.3

**Code**

``` ts
class A
{
    static X()
    {
        return new this();
    }
}

class B extends A
{
}

const shouldBeB = B.X();
```

**Expected behavior:**
The compiler correctly infers the type of `shouldBeB` as B.

**Actual behavior:** 
The compiler infers the type of `shouldBeB` as A, but it's B in runtime.

**Comment by yortus** [comment] 2016-10-22 12:49
Duplicate of #5863?

**Comment by TomMarius** [comment] 2016-10-22 13:24
@yortus in my mind that is a feature suggestion, but I think it's a critical bug, so I made a separate issue.

**Comment by HerringtonDarkholme** [comment] 2016-10-23 01:32
You can always use https://github.com/Microsoft/TypeScript/issues/5863#issuecomment-242782664 for the same behavior

**Comment by RyanCavanaugh** [comment] 2017-08-12 00:30
Too architecturally difficult to solve given the apparent lack of need for it

**Closed by RyanCavanaugh** 2017-08-12 00:30 UTC
Labels: Suggestion, Too Complex
