### ISSUE TITLE
tsc misunderstands possible value of variable (`TS2367`)

### ISSUE THREAD

**Issue by smallkirby** [microsoft/TypeScript#48620] opened 2022-04-09 09:45 UTC
# Bug Report

In the below code, tsc emmits the error toward `flag = flag === 'B' ? 'B' : 'A';`.

```ts
type TestType = 'A' | 'B' | 'C';

const f = (strs: string) => {
  let flag: TestType = 'A';
  let other_flag = false;

  for (const line of strs.split('\n')) {
    if (line.length !== 0 && flag === 'B') {
      flag = 'A';
    }

    if (line.startsWith('#')) {
      flag = 'C';
      other_flag = false;
    } else if (line.length !== 0 && other_flag) {
      flag = 'B';
      other_flag = false;
    } else if (line.length !== 0) {
      flag = 'A';
      other_flag = false;
    } else if (line.length === 0) {
      console.log(`flag: ${flag}`);
      flag = flag === 'B' ? 'B' : 'A';
      other_flag = true;
    }

    if (flag === 'C') {
      // DO WORK
    }
  }
};

f(`
# Hello

hello

hello
`);
```
error message:
```txt
index.ts:23:14 - error TS2367: This condition will always return 'false' since the types '"A"' and '"B"' have no overlap.

23       flag = flag === 'B' ? 'B' : 'A';
```

However, if I set `ts-ignore` at the line, compile it, and then run it, the condition can actually be `true`.

```
$ node ./index.js
flag: A
flag: C
flag: B
flag: B
```

### 🔎 Search Terms

`This condition will always return`

### 🕗 Version & Regression Information

I tested it by `tsc v4.5.5` on local, and `tsc nightly` on Playground.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKhDOwbmgXigcgIIagH0wCFcCMBhDAbgChqBjAewDtEoAzKdACkQCd4AXFD4BLJgHMAlJwB8UAN7UoUADYRg7FQENxQuImSROmHDWVqNDYAAsIvAPptt442y0r4EGkvYNeULkYWDRUxaAYOPngAOngwUOAuDAAdJgxJaUVlZREOLlCmCGi1CRsoAEJUdAAGKAAyOs0dTiqidIUfbKaXdGwqTqgAX1ou3ICCosQtXmB4AHURGySAYnTMgeUnZt6KMy6oK1sHLZ72d0895UGoCA9oMfyw4ohS6wrW2oaDmztHZ3X9t1jBhiJdsodfidXOcvANrrdPFAHhNnq93jUAfsob1TBtvkc-tszncwfC7ki8iiSuIylUMR1AUF4Aw1MUGOIuAADE5CAAk8hOg05kjBm2crnFdLaUAA-NKhH1RfjIZKoMBeABXWFdYYDB7Y1rkdpZfYAelNUAAIgB5KBza0AJQA0nCfMNBt42FzqMsoAAJW4qBi0WwqIMhwPB4WUIA)

**Comment by smallkirby** [comment] 2022-04-09 09:48
Oh, it might be duplicate of #46475 , I guess? I'm sorry for my poor search, if it's just same.

**Comment by MartinJohns** [comment] 2022-04-09 10:25
It does sound like a duplicate of #46475 to me too.

**Closed** 2022-04-13 18:00 UTC
Labels: Duplicate
