### ISSUE TITLE
The value check by index is ignored in the right-hand side of the logical conjunction

### ISSUE THREAD

**Issue by s1owjke** [microsoft/TypeScript#56647] opened 2023-12-02 17:05 UTC
### 🔎 Search Terms

- is not assignable to parameter of type
- noUncheckedIndexedAccess &&
- logical conjunction

### 🕗 Version & Regression Information

- This occurs since `4.1` when the `noUncheckedIndexedAccess` option was added

### ⏯ Playground Link

https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&target=7&module=6&noFallthroughCasesInSwitch=true&ts=5.4.0-dev.20231202#code/MYewdgzgLgBA0gUQJoH0BKCDiCAaMC8MA9AHoC0ZAFAHQBUAlEQNwBQoksAhgE4DmEALhjRuASzC8A2gF0CMSQCIKnYFFEA3AKYKANDCVkwAVwC2AI03dd+gIwLprNuGgxxAE00APOQAZWogDNKHn5Jdy8YAGoYG1kAMjj4ZHQsXGooTWhgvggwsA9vaNj6ehgAbwBfFicOGDAvKABJfIjCcMKY-wCYbND6zyaWz3jExFQMbBx0zKhe3P7BgukS8qqalwXGjJM5EPmG5qWuns3tmASk8dSpjKzTzRMVyqA

### 💻 Code

```ts
const KEY_REGEX = /^--(.*)/;
const args: string[] = ["--active", "--number", "1"];

// error
const index = 0;
if(args[index + 1] && KEY_REGEX.test(args[index + 1])) {}

// error
const nextIndex = index + 1;
if (args[nextIndex] && KEY_REGEX.test(args[nextIndex])) {}

// no error - can be used as workaround
const nextItem = args[nextIndex];
if (nextItem && KEY_REGEX.test(nextItem)) {}
```

### 🙁 Actual behavior

If we do an check by index, we get the following error:

```
Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'. (2345)
 ```

### 🙂 Expected behavior

No error

### Additional information about the issue

This only happens if the `noUncheckedIndexedAccess` option is set to true

**Comment by MartinJohns** [comment] 2023-12-02 17:23
Duplicate of #56389.

**Closed** 2023-12-02 18:08 UTC
