### ISSUE TITLE
Infer Type of Array after Filter

### ISSUE THREAD

**Issue by 2426021684** [Microsoft/TypeScript#7985] opened 2016-04-09 12:37 UTC
**TypeScript Version:** 

Lastest Commit

**Code**

```ts
const a = [5, 6, "7", "8"]
const b = a.filter(x => typeof x === "number")

```

**Expected behavior:**
b is `number[]`
**Actual behavior:** 
b is `(number|string)[]`

**Comment by DanielRosenwasser** [comment] 2016-04-09 18:32
Looks like a duplicate of #7657.

**Closed by DanielRosenwasser** 2016-04-09 18:32 UTC
Labels: Duplicate
