### ISSUE TITLE
partial application typing fail with custom error type

### ISSUE THREAD

**Issue by samuela** [microsoft/TypeScript#46699] opened 2021-11-05 20:06 UTC
# Bug Report

### 🔎 Search Terms

partial application, currying, type inference, higher-order functions, polymorphism

### 🕗 Version & Regression Information

Affects typescript@4.4.4 and v4.5.0-beta.

- I was unable to test this on prior versions because of the following error:
```
❯ npm i -D typescript@next
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: typescript@4.6.0-dev.20211105
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"4.6.0-dev.20211105" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@">=3.3.1" from eslint-config-next@12.0.2
npm ERR! node_modules/eslint-config-next
npm ERR!   dev eslint-config-next@"12.0.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/skainswo/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/skainswo/.npm/_logs/2021-11-05T19_54_53_547Z-debug.log
```

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=8&jsx=0&ts=4.5.0-beta#code/PTAEGUFNNALAXeAHAzgLhAcwJb1gVwCMA6AYwHsBbYAWW1ICdyVyAzeYAFQE8lJxG2JB2woU+SCmAB2AKyyAbMQBQ8XjACiDJg06gAvKADeoAHaQA7qAAUlSSgCGmSGlAp4DbKcwBKV1p1QAF8AbmVlVnxTUnhsclNQAH1TcngAOXwAG0yAHk4APmtIbXJddX8S3QAaUAA3Vz0AHzMszNBmqIATSFYvSE6-UD0jZVBQbFYbWoN9Q1NW9ubp2cMunr6B41Gx0DwmK3MrYp0ePmsAImPS0DsxJ0hznzCxoO2GSHh8BgTasNflCimdygJAOBixBxtfTbHIAQRqACEagVrKxXNYHK54aBCK4ET4DPkhjVMaBYQT9PlttZcaB8YTtmNWBiaoQnuFItFYvEQWCIZkAExwxHIwpomyk7G0+mU4mgSUEkZjd6fb42aUUonMhys9n-ECgTDkciddG0+aUQjFTUtS3FAHxYHiSgABT52EhBl54I9mWsGNcFqtDFZgfwdoYNocoAA1DiarJ2YCneG3T7IQKvaD04L-aSg8VQ7bg1HY-HQImwsoDUaTa48oV6kN2i1si21r1zJtZZwHUD4GZUhk24YG9Ym01W20OqZup3+jbkkPWtYAqUarV2dWwIQHKapq4ogBrFIWUw24+n0x94EpdKtTOGJf37LEQheTrWebZGpryNhZMBzvYdMgAZizd1IWsZ8QN-Sok0dIDl2yAAWCCcwFaDgNaOCdC3SAAA8kFKAcjFCZQgA)

### 💻 Code

```ts
// See https://github.com/Microsoft/TypeScript/issues/7556.
type ErrorT = { new (message: string): Error };

function _notNull<T>(errorType: ErrorT, v: T | null | undefined): T {
  if (v === null || v === undefined) {
    throw new errorType("error message");
  }
  return v;
}

const partial =
  <A, B, T>(f: (a: A, b: B) => T, a: A) =>
  (b: B) =>
    f(a, b);

function partial2<A, B, T>(f: (a: A, b: B) => T, a: A) {
  return (b: B) => f(a, b);
}

// good: (b: number) => number
const sumPartial = partial((a: number, b: number) => a + b, 5);
const sumPartial2 = partial2((a: number, b: number) => a + b, 5);

// good: <T>(v: T | null | undefined) => T
const notNull = <T>(v: T | null | undefined) => _notNull(Error, v);

// bad: (v: unknown) => unknown
const notNull2 = _notNull.bind(null, Error);
const notNull3 = partial(_notNull, Error);
const notNull4 = partial2(_notNull, Error);

export {};
```

### 🙁 Actual behavior

`_notNull.bind(null, Error)`, `partial(_notNull, Error)`, and `partial2(_notNull, Error)` are typed unhelpfully as `(v: unknown) => unknown`. I can understand that `bind` is messy to infer types on, but I don't understand the trouble with `partial` and `partial2` which are defined with simple type signatures.

### 🙂 Expected behavior

For everything to have the type `<T>(v: T | null | undefined) => T`.

**Comment by andrewbranch** [comment] 2021-11-10 21:49
Duplicate of https://github.com/microsoft/TypeScript/issues/30727 (different example, same problem)

**Closed** 2021-11-13 18:00 UTC
Labels: Duplicate
