### ISSUE TITLE
ts-expect-error covers following two lines

### ISSUE THREAD

**Issue by alexeagle** [microsoft/TypeScript#38433] opened 2020-05-08 22:57 UTC
I noticed that ts-expect-error is suppressing errors it shouldn't be. It seems that both of the two lines following it are suppressed.

Here is a repro which you can see with typescript@3.9.1-rc and typescript@4.0.0-dev.20200429
```
alex.eagle@ip-192-168-86-150 tsexpecterror % cat > f.ts
// @ts-expect-error
const a: number = ''
const b: string = 1
alex.eagle@ip-192-168-86-150 tsexpecterror % npx tsc f.ts
alex.eagle@ip-192-168-86-150 tsexpecterror % cat > f.ts
// @ts-expect-error
const a: number = ''

const b: string = 1
alex.eagle@ip-192-168-86-150 tsexpecterror % npx tsc f.ts
f.ts:4:7 - error TS2322: Type '1' is not assignable to type 'string'.

4 const b: string = 1
        ~


Found 1 error.
```

/cc @JoshuaKGoldberg

**Comment by sheetalkamat** [comment] 2020-05-08 23:06
Duplicate of #38289

**Closed by sheetalkamat** 2020-05-08 23:06 UTC
