### ISSUE TITLE
VSCode does not provide suggestions/auto-complete for NPM package installed as a dependency of another

### ISSUE THREAD

**Issue by paul-uz** [microsoft/TypeScript#55594] opened 2023-08-17 15:47 UTC
I have my own "SDK" package which has a dependency of a popular ORM package.

I can installed my SDK package in a project, and I can import the ORM package and use it, however, autocomplete, and suggestions when i write a method belonging to the ORM hasn't yet been imported, simply do not work, unless I add the ORM package explicitly to my projects package.json, which seems a bit redundant?

Is there anything I can add to my project package.json file to get it working?

**Comment by andrewbranch** [comment] 2023-09-01 18:50
Duplicate of #38768

**Closed** 2023-09-04 01:25 UTC
Labels: Duplicate

**Comment by mrleblanc101** [comment] 2025-02-28 18:31
It would be nice ot have an option to not filter sub-dependencies
