### ISSUE TITLE
With "strictNullCheck" = true a local-scoped function is not used for narrowing

### ISSUE THREAD

**Issue by EvgenyRodygin** [microsoft/TypeScript#43058] opened 2021-03-03 11:21 UTC
# Bug Report
With "strictNullCheck" = true a local-scoped function is not used for narrowing

### 🔎 Search Terms
strictNullCheck,
variable assignment,
function scope

### 🕗 Version & Regression Information
This is the behavior in every version I tried, and I reviewed the FAQ for entries about strictNullCheck
Versions: 3.9.5, 4.2.2

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.2#code/DYUwLgBAhgXBDOYBOBLAdgcwgHwmgrsMBALx6HADcAUNQGb5oDGYKA9mguAIIAUAlBADe1AJBRSEAORQpNAL614PATWoo6EXlEEjRTDvDagAdMDYZtZkJjAALfgqA)

### 💻 Code

```ts
let a: string | null = null;

function setA() {
	a = 'a';
}

setA();

if (a) {
	console.log(a.length);
}
```

### 🙁 Actual behavior
Under the **if (a)** branch the 'a' var has the 'never' type.

### 🙂 Expected behavior
Under the **if (a)** branch the 'a' var has the 'string' type.

**Comment by MartinJohns** [comment] 2021-03-03 11:29
Duplicate of #9998.

**Closed** 2021-03-06 18:00 UTC
Labels: Duplicate
