### ISSUE TITLE
Suggestion: Tuple literal may only specify known properties

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#12308] opened 2016-11-16 21:21 UTC
**TypeScript Version:**  nightly (2.2.0-dev.20161116)

**Code**

```ts
const p1: { x: number, y: number } = { x: 0, y: 1, z: 2 };
const p2: [number, number] = [0, 1, 2];
```

**Expected behavior:**

Errors on both lines.

**Actual behavior:** 

Only the first line has an error.

**Comment by mhegazy** [comment] 2017-04-27 21:51
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/6229

**Closed by mhegazy** 2017-04-27 21:51 UTC
Labels: In Discussion, Suggestion

**Comment by andy-ms** [comment] 2017-05-01 15:18
I don't know -- even if using a non-exact tuple type, it still seems like it would be useful to report an error in the case of a tuple literal with an extra property. Similar to the relationship between object excess property checking and exact types (#12936).
