### ISSUE TITLE
Array is not assignable to array of string literal type in overwritten class method

### ISSUE THREAD

**Issue by leonclaus** [microsoft/TypeScript#42115] opened 2020-12-25 23:07 UTC
# Bug Report

### 🔎 Search Terms

- array of string literals
- array specific string values
- TS2416

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about string literals

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.3#code/C4TwDgpgBAEgKnACgWQsAFgewCYGcoC8UARAOZrFQA+JYmuwxA3AFAsQB2ArgLawIo0WPAEFcAUW58A3iyhQA4uLiES5RgBo5URAHkAyiqLE6DYiwC+bAIYAjBgCdrAY2BRnAG2u58IxAEkoWXkwB0xgCFcIbCg7Rxc3aw8PTAB3aNQMHFwALn4kTOFcAG0AXVYQsIiomLjgJ1dY5LSMoWyAJjyACjIKalp6RgBKMoqoUPDIiNr7eoSmlPTsQuyxSV48+AK20QkpUcs2CAAPOgc3T298ACUIXEwuB2doE4iOPCg-QODxqqnohYtZY7fBEYq9TQDMzlbQTarTQFLFZ4dqqcHqYgaKGMGGVSY1RGtLK7dZ8MHaeRbQTE3BrKQAOiUcC08kpAmRtL2vHpekM2hhVhYHjQhOBNIAzJt2SCDklFkSiuK0RDMdjiDCTmc3NgIAAzaxcDyJZpIkHi+kAK0wAEsOD1iENWEA)
[Codesandbox mirror](https://codesandbox.io/s/frosty-williams-1n9z0?file=/src/index.ts)

### 💻 Code

```ts
type HTTPMethods = "get" | "post";

abstract class API {
  protected abstract allowedMethods2: HTTPMethods[];
}

export class Resource extends API {
  protected allowedMethods2 = ["get", "post"];
}
```

### 🙁 Actual behavior

The following error occurs:

```
Property 'allowedMethods' in type 'Resource' is not assignable to the same property in base type 'API'. Type 'string[]' is not assignable to type 'HTTPMethods[]'. Type 'string' is not assignable to type 'HTTPMethods'.
```

However, when we do the following:

```
let allowedMethods3: HTTPMethods[];
allowedMethods3 = ["get", "post"];
```

Everything works as expected.

### 🙂 Expected behavior

I would expect TypeScript to not throw an error when implementing an abstract class method. The same issue also occurs in non-abstract classes when overriding initial methods. For replication of the latter, have a look into the CodeSandbox example.

### Workaround

For workarounds, `const enum` could be used.

**Comment by jcalz** [comment] 2020-12-26 14:29
Duplicate of or strongly related to #3667

**Comment by andrewbranch** [comment] 2020-12-28 20:01
As another workaround, if the base declaration was a `readonly` array, in the subclass you could do `protected allowedMethods2 = ["get", "post"] as const;`.

**Closed** 2020-12-31 18:00 UTC
Labels: Duplicate
