### ISSUE TITLE
tsc doesn't recognize coercion of object keys to strings

### ISSUE THREAD

**Issue by cmwilhelm** [Microsoft/TypeScript#6267] opened 2015-12-27 19:27 UTC
I ran into a scenario yesterday that surprised me a bit. I was using an object literal to store some unique keys that I later extracted with a for-in loop. The keys were all numbers, but I quickly ran into a problem at runtime because i had forgotten that JavaScript coerces number type keys to strings for objects.

To wit, given the coercion of keys to strings, I was surprised that this type checked:

```typescript
var ids: Array<number> = [];
const myCollection = {
    0: true,
    1: true
};

for (var key in myCollection) {
    ids.push(key);
}

console.log(ids); // => ["0", "1"]
```

Is this expected behavior, or should this throw a compile time warning?

(TSC Version 1.7.5)

**Comment by vladima** [comment] 2015-12-28 18:08
duplicate of #4518

**Closed by vladima** 2015-12-28 18:08 UTC
Labels: Duplicate
