### ISSUE TITLE
Fields have an invisible "never make it undefined" state

### ISSUE THREAD

**Issue by verytactical** [microsoft/TypeScript#60411] opened 2024-11-04 14:21 UTC
### 🔎 Search Terms

undefined forever

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAqgdgZwseATCAzAlnCqAqA9gPIBGANlgG5aFwA8+AfFALxQDeUA2gApQ4oAawghCGKPgC6AWgD8ALkl8pUAD5QArnHTZcqANxQAvlABQoSFADKyNJhx5GLdlz4C4w0eMlSl+FXUtHQd9E3NLaHwACwgAdWiAQ2A2GzsQvSd4JBQMxwISCmpaBi5ExSgARhMmJjMgA

### 💻 Code

```ts
type UnsetUndefinedToOblivion<T> = { [P in keyof T]-?: T[P] | undefined; } 
type SetUndefined<T> = { [P in keyof T]: T[P] | undefined } 
type TheWhat = SetUndefined<UnsetUndefinedToOblivion<{ a?: 1 }>>
```

### 🙁 Actual behavior

```ts
type TheWhat = {
    a: 1;
}
```

### 🙂 Expected behavior

```ts
type TheWhat = {
    a: 1 | undefined;
}
```

### Additional information about the issue

Temporary fix:

```ts
type UnsetTheUnset<T> = { [P in keyof T & {}]: T[P] }
type TheWhat = SetUndefined<UnsetTheUnset<UnsetUndefinedToOblivion<{ a?: 1 }>>>
```

**Comment by jcalz** [comment] 2024-11-04 15:06
Duplicate of #31025

**Comment by verytactical** [comment] 2024-11-04 15:36
@jcalz This is a different issue. Here it's not only removed, it's impossible to even set it afterwards.

**Comment by jcalz** [comment] 2024-11-04 15:46
Ah, yeah, I see. It's probably still *related* to #31025, since removing `undefined` is happening at the *end* of the type manipulation, but you're showing a case where "the end" is much much *later* than makes any sense. 

To be painstakingly explicit about this, you can perform your two steps with an intermediate named type and it still happens:
```ts
type AOne = UnsetUndefinedToOblivion<{a?: 1}>
//   ^? type AOne = { a: 1 } // okay

type TheWhat = SetUndefined<AOne>
//   ^? type TheWhat = { a: 1 } // 🙃
```
[Playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAqgdgZwseATCAzAlnCqAqA9gPIBGANlgG5aFwA8+AfFALxQDeUA2gApQ4oAawghCGKPgC6AWgD8ALkl8pUAD5QArnHTZcqANxQAvlABQoSFADKyNJhx5GLdlz4C4w0eMlSl+FXUtHQd9E3MLcGgAQWJcNlhEOxC9PCIySho6eg4AQ0UoAEZjJjMAejKoKoA9OUirfAALCAB1RtzgBNsUFMdUeljcUoqqqFqzMyA)

**Comment by verytactical** [comment] 2024-11-04 16:26
> removing undefined is happening at the end of the type manipulation

Honestly I would never expect _that_. Thanks for explaining!

> It's probably still related to https://github.com/microsoft/TypeScript/issues/31025

It's definitely related, because if `undefined` was never removed along with optionality, it wouldn't be removed at incorrect time :)

**Comment by jcalz** [comment] 2024-11-04 16:34
Note that we *want* `undefined` to be removed along with optionality, but we want it removed from the input type's property, not from the *output* type's property.  That is, the expectation looks like `{[K in keyof T]-?: F<T[K]>}` should behave like `{[K in keyof T]-?: F<Exclude<T[K], undefined>>}` and not like `{[K in keyof T]-?: Exclude<F<T[K]>, undefined>}` (which is #31025). Unfortunately this behavior has existed for so long that I doubt they can really fix it because I imagine lots of real world code actually depends on it. 

But what's going on here is that even `{[K in keyof T]-?: Exclude<F<T[K]>, undefined>}` doesn't capture the extent of the weirdness. It really looks like the output of the mapped type is decorated with a permanent "no `undefined`" marker that operates through later type manipulations. Maybe they an at least fix *this*, since it's so weird.

**Comment by Andarist** [comment] 2024-11-04 18:21
I believe this is just a display issue as this works alright:
```ts
type UnsetUndefinedToOblivion<T> = { [P in keyof T]-?: T[P] | undefined };
type SetUndefined<T> = { [P in keyof T]: T[P] | undefined };
type TheWhat = SetUndefined<UnsetUndefinedToOblivion<{ a?: 1 }>>;

const theWhat: TheWhat = {
  a: undefined, // ok
};
```

It's likely a duplicate of https://github.com/microsoft/TypeScript/issues/59948 and likely is being fixed by https://github.com/microsoft/TypeScript/pull/59957

**Comment by jcalz** [comment] 2024-11-04 19:15
Okay, okay this has nothing to do with #31025 then. Sorry! I'll hide my comments (including this one, soon) to cut down on noise.

**Closed** 2024-11-07 01:32 UTC
Labels: Duplicate
