### ISSUE TITLE
Imports get lost, when classes are only referenced in switch/case

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#5666] opened 2015-11-14 03:43 UTC
Reported by @mechanoid  here https://github.com/TypeStrong/atom-typescript/issues/719#issue-116718119  Tested with TypeScript nightly

Sample from original issue report : https://github.com/mechanoid/ts-import-error-test

**Comment by DanielRosenwasser** [comment] 2015-11-14 03:53
Probably a duplicate of #5637. Appears to be fixed in the latest nightly.

**Closed by DanielRosenwasser** 2015-11-14 03:53 UTC

**Comment by mechanoid** [comment] 2015-11-14 18:42
thx! :)
