### ISSUE TITLE
Incorrect type inference on union type, unless using a third property as a discriminant

### ISSUE THREAD

**Issue by FrenchDilettante** [microsoft/TypeScript#57758] opened 2024-03-13 09:57 UTC
### 🔎 Search Terms

"inference" "inference narrow" "inference discriminant" "inference union"

### 🕗 Version & Regression Information

Tested on multiple versions, this is not a new bug.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.2#code/C4TwDgpgBA6gTgewHYHMCSSBmE4SQY2gF4oBvAKAEgBbAVwBtgBLMeiALimDlogG4qANwCG9XpwDO3JqgDaAXQGV8o+gCNh+ANacAFAH1J0ufICUUIgD4oghEwAmAgL5QAPmSp1GLNp0yiJfiFRcSgpOBkUJRV6dU0dKAMjCNRzKxs7R3InAXJMWgJmZCg2YABVCQxsOF1hTnhkdCwcPEJzCkphADoYuO1arpExCFMlJkxE7q9mVhGPSk6e1Q1+7qHeUaoXCHpA+cXela0B9ZGlJ2zyIA

### 💻 Code

```typescript
type Selection = {
	multiple: true;
	value: string[];
	callback: (_: string[]) => void;
} | {
	multiple: false;
	value: string;
	callback: (_: string) => void;
};

function test(a: Selection) {
	// Error: Typescript does not recognise that `value` and `callback` use the same type.
	a.callback(a.value);
	if (a.multiple) {
		// Valid: Typescript narrowed down the type to `string[]`
		a.callback(a.value);
	} else {
		// Valid: Typescript narrowed down the type to `string`
		a.callback(a.value);
	}
}
```

### 🙁 Actual behavior

Typescript does not recognise that `callback` will always accept `value` as a parameter, since they both use either `string` or `string[]`.

Interestingly, Typescript can infer the types properly using the `if (multiple) { ... }` condition.

### 🙂 Expected behavior

All three `callback(value)` calls should be valid, from a type point of view.

**Comment by MartinJohns** [comment] 2024-03-13 11:17
Essentially a duplicate of #30581. Not sure why that is closed.

**Comment by Andarist** [comment] 2024-03-13 11:59
It's probably closed because it has been determined that it would be too computationally expensive to do it and the current best solution is to use the "indexed mapped type as a union" pattern from TS 4.6 (see [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-6.html#indexed-access-inference-improvements)).

However, this discriminant value isn't easily used as a property key so while we can make the internal implementation of a function happy about it... it still doesn't quite infer a concrete `K` that is used and it doesn't discriminate the input argument for contextual parameters etc: [TS playground](https://www.typescriptlang.org/play?ts=5.4.2&ssl=20&ssc=15&pln=20&pc=10#code/JYOwLgpgTgZghgYwgAgCoE8AOECydPIDeAUMsmFAK4QBcyAzhaAOYDcpy8ANvbQ0yGYBtALrsAvsWJgsKAKohgAexAAlCAiVQAJgB4ACsggAPSCG31kAawjolMNLLwEAvNdv3H2ZwD5kbkjIhAGlkUGR9ETpAsmQAW0ouMGBMLj5QkzMLZAADABJCUBhoZAAhI1MIc0sAIyUlNLgQcRzkAH4y5DoQCAA3aHZY5F64Lmo6DG98ELEOMgRRrhrEKzoACkwJp2ngkQBKfz9epWBtQeRxCSFI9mIYShAEZJVkNLA5egBJEGKoXQzKtV3HYHJNcPgfGs4HQFMo1BotHpgj4DjE4AA6BZcJYrKHokZjCB7VjIAD0pOQ6Dg6AAhMRJMQ3h9vr81jEEkkUmk6BRqAAaDgE8bIABEMHqIoF80WywQq2QawA+gcXH4YmRFXMyRSAHptDjiAXiYlSEyYLRgIiXYhAA)

Using some intersections we can fix the latter: [TS playground](https://www.typescriptlang.org/play?ts=5.4.2#code/JYOwLgpgTgZghgYwgAgCoE8AOECydPIDeAUMsmFAK4QBcyAzhaAOYDcpy8ANvbQ0yGYBtALrsAvsWJgsKAKohgAexAAlCAiVQAJgB4ACsggAPSCG31kAawjolMNLLyYANMgBCR0xHOWARkpKXBBwIAB8yAC8RBxCANLIoMj6InQkZGQAtpRcYMCYwXSeAGTIABQJJmYWyAAGACSEoDDQHgBMXtX+gcGh4rXIAPztyHQgEABu0ACU7BnIE3Bc1HQY2M7xYhxkCEtcfohWdGWYq074m9NRERNKwNpzyOISQinsxDCUIAh5KsjBYDk9AAkiAWlBdJVvL5rLZ7I51vg3J4qj4agEgiFwmU4HQFMo1BotHo4siwld0sg4AA6XZcfaHHHUxbLCCzZAAeg5yHQcHQAEJiJJiACgaDwWVKdlcvlCuQqBAXBwWStkAAiGCBNVKnZ7A4II7lAD6V0iEUpZCN2053IAeoMOOIleJZlITJgtGAiM9iEA). It still doesn't infer `K` though and I'm not sure how to make `true`/`false` a viable inference source for `"true"`/"false"

**Comment by Andarist** [comment] 2024-03-13 12:16
kudos to @ssalbdivad: [TS playground](https://www.typescriptlang.org/play?ts=5.4.2#code/JYOwLgpgTgZghgYwgAgCoE8AOECydPIDeAUMsmFAK4QBcyAzhaAOYDcpy8ANvbQ0yGYBtALrsAvsWJgsKAKohgAexAAlCAiVQAJgB4ACsggAPSCG31kAawjolMNLLyYAfMgC8RDkIDSyUMj6InQkZGQAtpRcYMCYXHx+JmYWyAAGACSEoDDQyABCRqYQ5pYARkpK8XAg4qnIAPz5yHQgEABu0OxhyG1wXNR0GNjOvmIcZAh9XKWIVnQAFJiDTvijAJQebm1KwNpdyOISQkHsxDCUIAgxKsjxYHL0AJIgOVC6iUUlaZl5tQA0TSSxRS5UqEGqLnmHDgdAUyjUGi0eh8bgAZERkJForF4nQCuI-sQNqFkHAAHSTLjTWbzcm9foQNasZAAehZyHQcHQAEJiJJiHcHs9XvMSViYnE+BRqISyPSBsgAEQwCqK2XISnUhBzZDzAD6G3cbhJZD141Z7IAevUOAS+UypCZMFowERDsQgA)

it's not particularly intuitive how to put all the pieces together but this one works very well

**Comment by fatcerberus** [comment] 2024-03-14 15:58
It looks like #30581 was auto-closed when https://github.com/microsoft/TypeScript/pull/47109 got merged.

**Closed** 2024-03-18 01:25 UTC
Labels: Design Limitation
