### ISSUE TITLE
Introduce "extends const" syntax

### ISSUE THREAD

**Issue by pleerock** [microsoft/TypeScript#32666] opened 2019-08-01 20:37 UTC
Imagine we have some interface:

```ts
export type User = {
    id: number
    name: string
}
```

**Working as expected:**

And we have a function `register1` that accepts Partial of this type:

```ts
function register1(userProperties: Partial<User>) {
}

register1({
    id: 1,
    name: "Anders",
})
```

And I want to prevent incident properties passing to that function:

```ts
register1({
    id: 1,
    name2: "Anders", // gives me error, great!
})
```

**Not working as expected:**

Now imagine I have a `register2` function that does the same, and a bit more:

```ts
function register2<T extends Partial<User>>(properties: T) {
    // I want to pass T down the road to another function, 
    // and that function returns type-safe result based on actually passed properties
    // let's imagine that function changes given property values to boolean
    return someAnotherFunctionCall<T>(properties)
}

register2({
    id: 1,
}) // returns { id: boolean }

register2({
    id: 1,
    name2: "Anders"
}) // returns { id: boolean } as expected 
```

Everything works as I need besides one thing - I would like compiler to throw error on `name2` property - "missing property name2 on Partial<User>" (to prevent mistakes or refactoring consequences). I understand why I have this error - because `T extends Partial<User>` means T is extended version of Partial<User> and supposed to have any additional properties. But how can I achieve what I need? Looks like I need a "final" version of Partial<User>. Maybe something like `T extends const Partial<User>` syntax should be suggested? 

It can be a duplicate, I didn't know how to describe problem properly. If it's a new feature please help me to update the issue title. Thanks.

**Comment by AnyhowStep** [comment] 2019-08-01 21:18
```ts
export type User = {
    id: number
    name: string
}
function someAnotherFunctionCall<T extends Partial<User>> (properties : T) {

}
function register2<T extends Partial<User>>(
	properties: (
		T &
		(
			keyof T extends keyof User ?
			unknown :
			["Extra property not allowed; ", Exclude<keyof T, keyof User>]
		)
	)
) {
    // I want to pass T down the road to another function, 
    // and that function returns type-safe result based on actually passed properties
    // let's imagine that function changes given property values to boolean
    return someAnotherFunctionCall<T>(properties)
}

register2({
    id: 1,
}) // returns { id: boolean }

register2({
    id: 1,
    name2: "Anders"
}) // returns { id: boolean } as expected 
```
[Playground](http://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBDAnmYcCqBnYU4F44DeAsAFBzlwCWAJgFxwB2ArgLYBG2pFjAhi8PQwwolBgHNSAX1IAzJgwDGMShAZwMEfgEEGEGAAtsAMXlKVDAMI8ANtYA8AFTigYwBtQxwACj1iUbdpjYAHzBcAAUYFAQKH7AnvQOAJSEpFKypsqqcFDAYpRC2ABMjs4gru6ePn4BQVCh4aQAkFEx2Mrx9I0kTU1OAGTNTd29TQDWwIgQMnBOLm4ecBNTM3VwAPxDTfJjugDuarRbANoARACi5VA8cK2xSIx6cDbWEHvA1ADccKcANHCXBTWJjUYB2ZbTWb-CGrLD1AC6QySzWRJBSxDIFAA9Fi4ABJOB7HgMeAwCC3HgYTxOahvNQGVDRHjUBDk4l6Qw4OSKLIMf5cbG44ksgw8eDcszZXIwJhQBieJAoAC0GB4MkZ8SY1ngbEpHzg2R4SiYL0QFKp+ru7Uo8QF5BxcGswBgAHJPJQWDx8gxUKLxZlzHAFPpiWJ4nB8gA3Ny3aL3M2RmxMcNkuBsCAQJ3Eu05Z2ytQabS6BlQEw88xWWyOYKROPW+Ko6QkUi5fKFKBFcIY7g0egARl+UhSDul+c8BCodDTGazaibLbyBVcHa7Od7cAHOYYfGARXopx0oKgGFOQ7gI7zcvHk-o6czwGJcEkz08oBQSn1QA)

Not sure if there's another way at the moment

**Comment by RyanCavanaugh** [comment] 2019-08-01 21:22
It's very rare that these signatures can't be rewritten in a way that works. What's the definition of `someAnotherFunctionCall` ?

**Comment by pleerock** [comment] 2019-08-01 22:19
Let me write a very simple implementation of what I have:

```ts
export type User = {
    id: number
    name: string
}

export type Selection<T, K extends keyof T> = {
    [P in K]?: boolean
}

export type ModelSelection<T, S extends Selection<T, keyof T>> = {
    [P in keyof T]: S[P] extends true ? T[P] : never
}

function select<T, S extends Selection<T, keyof T>>(model: T, selection: S): ModelSelection<T, S> {
    return undefined as any
}

const user: User = {
    id: 1,
    name: "Anders",
}

const selection = select(user, {
    id: true,
    name2: false // I want to have error here
})

// type of selection is { id: number, name: never } here
// is expected (but really would like not to have "name" in type signature at all, but that's another case)

```

**Comment by fatcerberus** [comment] 2019-08-02 05:52
It seems like what you really want is exact types, in which case this would be a duplicate of #12936.

**Comment by pleerock** [comment] 2019-08-02 06:35
@fatcerberus yes, it looks so, thanks for reference

**Comment by AnyhowStep** [comment] 2019-08-02 15:12
@fatcerberus seems like your observation is true once again. The people that want exact types and similar things tend to be people working with data stores

**Closed** 2019-08-05 18:00 UTC
Labels: Duplicate
