### ISSUE TITLE
(event: TouchEvent) => void is not assignable "touchstart" event.

### ISSUE THREAD

**Issue by Glinkis** [Microsoft/TypeScript#22565] opened 2018-03-14 10:19 UTC
**TypeScript Version:**  2.8.0-dev.20180314

**Code**

```ts
const onTouchStart = (event: TouchEvent) {}
document.addEventListener("touchstart", onTouchStart);
```

**Expected behavior:**
`onTouchStart` should be treated as an event listener.

**Actual behavior:**
```
Argument of type '(event: TouchEvent) => void' is not assignable to parameter of type 'EventListenerOrEventListenerObject'.
  Type '(event: TouchEvent) => void' is not assignable to type 'EventListenerObject'.
```

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=const%20onTouchStart%20%3D%20(event%3A%20TouchEvent)%20%3D%3E%20%7B%20%7D%3B%0Adocument.addEventListener(%22touchstart%22%2C%20onTouchStart)%3B)
Though the playground does not really demonstrate the issue, as it's not on the newest typescript version.

**Comment by RyanCavanaugh** [comment] 2018-03-14 17:17
Doesn't repro for me on latest. Are you passing any commandline flags as well?

**Comment by Glinkis** [comment] 2018-03-14 17:21
No, just running it normally after updating to the latest @next.

**Comment by timocov** [comment] 2018-03-23 13:27
@RyanCavanaugh 

we have the same errors in our project with 2.8. Steps to reproduce is very simple:
1. `mkdir test && cd test`
1. `npm install typescript@2.8-rc`
1. `./node_modules/.bin/tsc --init`
1. `touch file.ts`
1. Insert the following code into `file.ts`:
    ```ts
    declare function onTouchStart(event: TouchEvent): void;
    document.addEventListener('touchstart', onTouchStart);
    ```
1. `./node_modules/.bin/tsc`

As result:
```
file.ts(2,41): error TS2345: Argument of type '(event: TouchEvent) => void' is not assignable to parameter of type 'EventListenerOrEventListenerObject'.
  Type '(event: TouchEvent) => void' is not assignable to type 'EventListenerObject'.
    Property 'handleEvent' is missing in type '(event: TouchEvent) => void'.
```

**Comment by MaceWindu** [comment] 2018-03-26 11:14
The reason of it is that typing of touch events changed in lib.dom.d.ts from TouchEvent to Event.

**Comment by mhegazy** [comment] 2018-03-26 15:49
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by jakearchibald** [comment] 2018-03-26 17:27
Created a PR https://github.com/Microsoft/TSJS-lib-generator/pull/394.

This is a pretty big regression and it doesn't seem easy to workaround. Feels like 2.8 shouldn't ship without a fix.

**Comment by timocov** [comment] 2018-03-27 22:19
@mhegazy as soon it is already fixed in tsjs repo, is it possible to include it in 2.8.2?

**Closed** 2018-03-28 20:42 UTC
Labels: Bug, Domain: lib.d.ts, Fixed, help wanted
