### ISSUE TITLE
Intellisense does not work for properties that are added after declaration

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#13271] opened 2017-01-03 18:52 UTC
_From @saravanaj on December 30, 2016 3:8_

- VSCode Version: 1.8.1
- OS Version: Windows 8.1 Home

I am running code with `--disable-extensions` flag.

Steps to Reproduce:

1. Write some code where properties are added to objects added after declaration. Intellisense does not work:
![actual](https://cloud.githubusercontent.com/assets/1573565/21559060/019b5f46-ce6b-11e6-8417-5766805f5c33.png)

2. If the properties are defined during declaration it works:
![expected](https://cloud.githubusercontent.com/assets/1573565/21559067/315cbfc2-ce6b-11e6-8d7d-8ada87b7999a.png)

_Copied from original issue: Microsoft/vscode#17923_

**Comment by mjbvz** [comment] 2017-01-03 18:52
_From @Spown on December 31, 2016 4:13_

I think it is a proper behavior. If you had something like this:
```js
var obj = {};
if (someGlobalVariable===true) {
  obj.test = {
    one: 1
  }
} else if (someGlobalVariable===false) {
  obj.test = "I'm a string now!"
}

obj
```
then Intellisense wouldn't really know whether the obj variable always has this ``test`` property and what type it is. Intellisense doesn't evaluate your code - it only makes assumptions where it can. Thats why you still have  word suggestions:
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-12/firefox_2016-12-31_05-12-58.png)
as a compromise.

**Comment by mjbvz** [comment] 2017-01-03 18:52
_From @saravanaj on December 31, 2016 6:26_

@Spown  I agree it is impossible to autocomplete properties that are added conditionally, but the example I posted does not add any properties conditionally. The same code gives intellisense in Visual Studio.

The major use case where this type of intellisense is needed is when I namespace methods and properties like below:

**In VS Code:**
![2016-12-31_115010](https://cloud.githubusercontent.com/assets/1573565/21576316/ff2fdfee-cf4f-11e6-9fbe-b1b29c1ca9fd.png)

**In Visual Studio:** (which handles this perfectly)
![vs](https://cloud.githubusercontent.com/assets/1573565/21576317/1a1cc236-cf50-11e6-906e-61a6b598c2e3.png)

**Comment by mjbvz** [comment] 2017-01-03 18:58
I verified this intellisense limitation for JS using both TS 2.1.5 and typescript@next. 

I believe it may be a duplicate of an existing issue but wasn't able to find a proper parent, so feel free to mark it as such if that is the case. We already handle property assignment to the `prototype` for classes, so this may be similar.

**Comment by unional** [comment] 2017-01-06 00:39
Please note that `obj = {}; // without var` doesn't work either. This prevent JavaScript namespacing across multiple files.

https://github.com/Microsoft/vscode/issues/18196#issuecomment-270799174

**Comment by unional** [comment] 2017-01-06 00:46
Add minimal test case:

```js
// a.js
A = A || {};
A.a = 1;

// b.js
A = A || {};
A.b = 2;

// test.js
assert(A.a);
assert(A.b);
```

**Comment by mhegazy** [comment] 2017-01-06 00:54
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/7632

**Closed** 2017-01-06 00:54 UTC
Labels: Duplicate, VS Code Tracked
