### ISSUE TITLE
Make type predicates combinable with other types

### ISSUE THREAD

**Issue by LinqLover** [microsoft/TypeScript#45890] opened 2021-09-15 14:52 UTC
# Suggestion

## 🔍 Search Terms

TS1228, type predicate, type guards

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Type predicates using the `asserts` keyword should be combinable, i.e. intersectable, unionable, etc. with other types.

## 📃 Motivating Example

Consider this snippet:

```ts
function getExtension(path: string | undefined) {
    assert(path !== undefined)
    const positionOfLastDot = path.lastIndexOf('.')
    if (!positionOfLastDot) { return path }
    return path.slice(positionOfLastDot + 1)
}

function stripExtension(path: string | undefined) {
    const extension = getExtension(path)
    return path.slice(0, path.length - extension.length - 1)
}
```

Currently, the compiler complains in the last line of `stripExtension()`:

```
error TS2532: Object is possibly 'undefined'.
    return path.slice(0, path.length - extension.length - 1)
           ~~~~
```

So I need to check the type again or cast it, e.g. using `path!`. But this is redundant! Since we have called `getExtension()` before and the execution has continued here, we already know that the path exists and is not `undefined`. **I would like to able to write a declaration l like this:**

```typescript
function getExtension(path: string | undefined): string & asserts path
```

Formally, I propose that function return types should support the combination of types that includes `asserts` and other type predicates (if any).

Furthermore, tsc should also be able to infer this information from the implementation of the function.

## 💻 Use Cases

- see example from above
- currently, you either need to repeat your assertion or do a cast (`path!.slice(...)`), or in more complicated scenarios, `(<string>path).slice(...)`)

**Comment by jcalz** [comment] 2021-09-15 16:05
Duplicate of #40562 for the assertion type predicate part.  

I feel like I've seen discussion of non-boolean non-assertion type predicates before, but I can't find it now.  Maybe #12798 (combine type predicate types) and #15048 (one-sided type predicates) and #29317 (negated types)?  So `(0 & x is Foo) | (1 & x is not Foo)` or something?

**Comment by LinqLover** [comment] 2021-09-15 16:17
Thank you, closing as a filibuster l duplicate of #40562.

**Closed** 2021-09-15 16:18 UTC
