### ISSUE TITLE
Supporting type `self` or something that can represents the current instance.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#2179] opened 2015-03-02 08:21 UTC
When I am writing a declaration file, I found it really frustrating repeating the inherited method that returns the instance itself for a correct return type.

E.g. for animation library GSAP, many classes are inherited from class `Animation`, I have to repeat almost every method to update return type `Animation` to the current class.

```typescript
class Animation {
    chain(): Animation;
}

class TweenLite extends Animation {
    ownProperty: any;
    chain(): TweenLite;
}
```

It would be great if we may use some type like `self` to make this easier, like this:

```typescript
class Animation {
    chain(): self;
}

class TweenLite extends Animation {
    ownProperty: any;
}
```

**Comment by DanielRosenwasser** [comment] 2015-03-02 09:29
Seems like a duplicate of #285.

**Closed** 2015-03-02 09:29 UTC
Labels: Duplicate

**Comment by danquirk** [comment] 2015-03-02 20:08
Also see #513
