### ISSUE TITLE
can not get correct params type when using `Parameters` to overloaded function

### ISSUE THREAD

**Issue by LaamGinghong** [microsoft/TypeScript#54721] opened 2023-06-21 08:54 UTC
# Bug Report

### 🔎 Search Terms

- overloaded funciton
- type
- `Parameters`

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/LAKAlgdgLgpgTgMwIYGMYAIBiF0G9TroAUMAbjNAFzoDOUckA5gDToAOScSAtjQPzUkEAJ4BKaqQD2YACYFiZClBrUA2nQYQW6IcL4BdVfvHops0AF9QoKMLYZsABU48a6ALzpnXbjFhwaAB5sAD5QAHpwwkIAPT4gA

### 💻 Code

```ts

interface Fn {
  (event: string, params?: any): void
  (events: [string, any?][]): void
}

type FnParams = Parameters<Fn>
//    ^?
```

### 🙁 Actual behavior

only get last case's type.

### 🙂 Expected behavior

get all cases's type

**Comment by fatcerberus** [comment] 2023-06-21 12:02
Duplicate of https://github.com/microsoft/TypeScript/issues/43731.

This is a known (and documented) design limitation:
https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types

> When inferring from a type with multiple call signatures (such as the type of an overloaded function), **inferences are made from the *last* signature** (which, presumably, is the most permissive catch-all case). It is not possible to perform overload resolution based on a list of argument types.

**Closed** 2023-06-25 01:33 UTC
Labels: Duplicate
