### ISSUE TITLE
Installing TypeScript 2.6.1 for Visual Studio 2017 breaks Typescript support 

### ISSUE THREAD

**Issue by Thieum** [Microsoft/TypeScript#19714] opened 2017-11-03 13:38 UTC
**TypeScript Version:**  2.6.1

**Expected behavior:**

Installing Typescript 2.6.1 for Visual Studio 2017 in Visual Studio 2017 15.4.2 should give access to the new version of typescript in the properties page of the project, and in the compilation.

**Actual behavior:**

Installing Typescript 2.6.1 for Visual Studio 2017 in Visual Studio 2017 15.4.2 breaks the project page:

![image](https://user-images.githubusercontent.com/944894/32375861-86763adc-c079-11e7-8625-b2a2d82ca3b8.png)

And breaks the Typescript support in Visual Studio:

![image](https://user-images.githubusercontent.com/944894/32375931-b0e38d74-c079-11e7-802b-d10cce11e4e1.png)

**Workaround:**

fall back to Visual Studio 2015, as I didn't find a way to repair the typescript installation (uninstall the extension, uninstall / reinstall the sdk, install all typescript sdks available in Visual Studio Setup)

**Comment by mhegazy** [comment] 2017-11-03 22:57
Can you share your install logs. these should be under `%temp%\dd_TypeScript*`

**Comment by gerbendekker** [comment] 2017-11-06 11:42
Same issue here.
Installed this:
https://www.typescriptlang.org/#download-links
Then:
https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.TypeScript261forVisualStudio2017

When opening a VS project that uses Typescript, an error occurs. 
ActivityLog.xml:
```xml
<entry>
  <record>423</record>
  <time>2017/11/06 11:10:45.449</time>
  <type>Error</type>
  <source>VisualStudio</source>
  <description>CreateInstance failed for package [Microsoft.VisualStudio.LanguageServices.TypeScript.TypeScriptPackage, Microsoft.VisualStudio.LanguageServices.TypeScript, Version=15.0.0.0, Culture=neutral]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.LanguageServices.TypeScript, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.LanguageServices.TypeScript, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.LanguageServices.TypeScript, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Activator.CreateInstance(String assemblyName, String typeName)&#x000D;&#x000A;   at System.AppDomain.CreateInstance(String assemblyName, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
  <guid>{2FFE45C4-5C73-493C-B187-F2E955FF875E}</guid>
  <hr>80004005 - E_FAIL</hr>
  <errorinfo></errorinfo>
</entry>
``
[dd_TypeScript_SDK_20171106120938.log](https://github.com/Microsoft/TypeScript/files/1446065/dd_TypeScript_SDK_20171106120938.log)
[dd_TypeScript_SDK_20171106120938_000_TypeScript_SDK.msi.log](https://github.com/Microsoft/TypeScript/files/1446066/dd_TypeScript_SDK_20171106120938_000_TypeScript_SDK.msi.log)

`

**Comment by gerbendekker** [comment] 2017-11-06 12:39
When using the link https://www.typescriptlang.org/#download-links then I'm getting the version 2.5.3 of the SDK.
Bet then I found the [link](http://download.microsoft.com/download/7/0/A/70A6AC0E-8934-4396-A43E-445059F430EA/2.6.1-TS-release-dev14update3-20171027.2/TypeScript_SDK.exe) in the announcement from [here](https://blogs.msdn.microsoft.com/typescript/2017/10/31/announcing-typescript-2-6/).
This is pointing to the 2.6.1 SDK.
The problem remains but a different behavior.
An error is shown when opening a TS file.
```xml
<entry>
    <record>1078</record>
    <time>2017/11/06 12:35:18.192</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.CodeAnalysis.Workspaces, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.CodeAnalysis.Workspaces, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos;&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.TextMateClassificationTaggerProvider.CreateTagger[T](ITextBuffer buffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
  </entry>
    <entry>
    <record>1083</record>
    <time>2017/11/06 12:35:18.247</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Appid denied the loading of package</description>
    <guid>{2FFE45C4-5C73-493C-B187-F2E955FF875E}</guid>
  </entry>
  <entry>
    <record>1084</record>
    <time>2017/11/06 12:35:18.247</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Package failed to load; error message suppressed by skip flag</description>
    <guid>{2FFE45C4-5C73-493C-B187-F2E955FF875E}</guid>
  </entry>
```

**Comment by gerbendekker** [comment] 2017-11-06 12:55
In Programs and features, the verion of this [TypeScript Tools for MVS vNext](https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.TypeScript261forVisualStudio2017) installation is 2.5.0.0
I would expect to see 2.6.1 here.

**Comment by Thieum** [comment] 2017-11-06 15:10
@mhegazy TypeScript_Dev15.msi from https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.TypeScript261forVisualStudio2017#overview doesn't generate any dd_Typescript. 

I thought dd_typescript files were only generated by Wix bundles - like the one from https://www.microsoft.com/en-us/download/details.aspx?id=55258

**Comment by gerbendekker** [comment] 2017-11-06 18:33
MSI log doesn't show something special. Succesful but its product version 2.5.0.0.
@Thieum do you also have version 2.5.0.0 when installing TypeScript_Dev15.msi?

```
Property(C): INSTALLLEVEL = 1
=== Logging stopped: 6-11-2017  18:25:05 ===
MSI (c) (18:BC) [18:25:05:837]: Note: 1: 1707 
MSI (c) (18:BC) [18:25:05:837]: Product: TypeScript Tools for Microsoft Visual Studio vNext -- Installation completed successfully.

MSI (c) (18:BC) [18:25:05:838]: Windows Installer installed the product. Product Name: TypeScript Tools for Microsoft Visual Studio vNext. Product Version: 2.5.0.0. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

MSI (c) (18:BC) [18:25:05:839]: Grabbed execution mutex.
MSI (c) (18:BC) [18:25:05:839]: Cleaning up uninstalled install packages, if any exist
MSI (c) (18:BC) [18:25:05:841]: MainEngineThread is returning 0
=== Verbose logging stopped: 6-11-2017  18:25:05 ===
```

**Comment by Thieum** [comment] 2017-11-06 18:44
@gerbendekker  I do:

![image](https://user-images.githubusercontent.com/944894/32457766-30b4446e-c2f8-11e7-9e27-fd36c91be78c.png)

Maybe it's pedantry, but the marketplace page also shows a "2.4.1 version for VS 2015" instead of 2.6.1 for VS2017: https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.TypeScript261forVisualStudio2017#overview

The vNext part still makes me wonder if this install is intended for Visual Studio 15.4.2.? 15.5.0? 16.0.0?

**Comment by Thieum** [comment] 2017-11-06 18:58
The [blog post announcing 2.6.1](https://blogs.msdn.microsoft.com/typescript/2017/10/31/announcing-typescript-2-6/) is even more confusing considering the url offered for VS2017: http://download.microsoft.com/download/7/0/A/70A6AC0E-8934-4396-A43E-445059F430EA/2.6.1-TS-release-dev14update3-20171027.2/TypeScript_SDK.exe

compare it to the VS2015 link:

http://download.microsoft.com/download/6/D/8/6D8381B0-03C1-4BD2-AE65-30FF0A4C62DA/2.6.1-TS-release-dev14update3-20171027.2/TypeScript_Dev14Full.exe

Current version of VS2017 is dev15update4, dev14update3 being VS2015...

Whatever TypeScript_Dev15.msi tries to install, it's not 2.6.1 sdk, and it breaks typescript integration beyond repair in VS2017, even after uninstalling it, and reinstalling the appropriate program.

**Comment by gerbendekker** [comment] 2017-11-06 21:11
I didn't get any further and recovered to TS sdk 2.3.5.0.

Used Visual Studio Installer - Individual Components to uninstall TS sdk 2.3 and all depending components.
Then uninstalled all TypeScript SDK versions in Programs and features.
Installed all removed components again.
After that did another try, but the same issue again, no TypeScript.

**Comment by mhegazy** [comment] 2017-11-06 21:30
There seems to be a few issues we identified with the installers so far.. 

* Download links on Download Center are incorrect. These are ones referenced to from  https://www.typescriptlang.org/#download-links.
  - These should be updated now to point to 2.6.1
  - VS 2015: https://www.microsoft.com/en-us/download/details.aspx?id=48593
  - VS 2017: https://www.microsoft.com/en-us/download/details.aspx?id=55258

* Download links on the VS Gallery are not correct either
  - This should be fixed now and pointing to 2.6.1
  - VS 2015: https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.TypeScript261forVisualStudio2015
  - VS 2017: https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.TypeScript261forVisualStudio2017#overview

Please give the new installers a try and let us know if you are still running into issues.

**Comment by Thieum** [comment] 2017-11-06 21:46
@mhegazy following @gerbendekker  advices with the recovery to install the newer version with your installer worked. Uninstalling TS Sdks through visual studio installer (and a good part of the web stack, as TS2.3 is a dependency), then reinstalling the web stack, and the sdk with the appropriate file works:

![image](https://user-images.githubusercontent.com/944894/32465541-d0e1c664-c311-11e7-9259-8b2ab5a69ac8.png)

**Comment by gerbendekker** [comment] 2017-11-06 23:21
I can confirm that the issues is resolved. Thanks!

**Comment by mhegazy** [comment] 2017-11-07 01:46
thanks @gerbendekker and @Thieum for confirming, and sorry for the confusion with the installers in the first place.

**Closed by mhegazy** 2017-11-07 01:46 UTC
Labels: Needs More Info
