### ISSUE TITLE
Type string does not narrow when checked for equality with a string literal.

### ISSUE THREAD

**Issue by aaronlahey** [Microsoft/TypeScript#11306] opened 2016-10-02 18:44 UTC
**TypeScript Version:**  2.1.0-dev.20160918

**Code**

```ts
export function returnAnyString(): string {
  return "";
}

export function acceptsOnlyFoo(value: "foo"): void {
  // ...
}

const value = returnAnyString();

if(value === "foo")
  acceptsOnlyFoo(value); // error TS2345: Argument of type 'string' is not assignable to parameter of type '"foo"'.
```

**Expected behavior:**

The `===` to narrow type `string` to a string literal type when checking for equality with a string literal. I would expect the above example to be the same as the following example which **does** work...

```ts
export function returnAnyString(): string {
  return "";
}

export function acceptsOnlyFoo(value: "foo"): void {
  // ...
}

function isFoo(s: string): s is "foo" {
  return s === "foo";
}

const value = returnAnyString();

if(isFoo(value))
  acceptsOnlyFoo(value);
```

**Actual behavior:** 

The type is still `string`.

**Comment by kitsonk** [comment] 2016-10-03 05:54
Essential a dupe of #7447 which was supposed to be implemented in #9407 but doesn't appear to be working.

**Closed** 2016-10-13 20:59 UTC
Labels: In Discussion, Suggestion
