### ISSUE TITLE
.git directory installed in 3.3.333

### ISSUE THREAD

**Issue by XCMP** [Microsoft/TypeScript#30122] opened 2019-02-27 10:50 UTC
**TypeScript Version:** 3.3.333

**Search Terms:**
3.3.333 Not a git repository

**Code**

```shell
git init
npm install typescript
git add package-lock.json
git commit -m "init"
git clean -xdf
```

**Expected behavior:**
clean node_module folder

**Actual behavior:**
fatal: Not a git repository: /home/daniel/shared/TypeScript/.git/worktrees/TypeScript3
The .git file should not be included in release package.

**Playground Link:**

**Related Issues:**

**Comment by j-oliveras** [comment] 2019-02-27 11:21
Duplicate of #30100, #30077 and fixed by #30078.

**Closed** 2019-02-27 17:00 UTC
Labels: Duplicate
