### ISSUE TITLE
string literal can't be used as a type of a parameter

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#6991] opened 2016-02-10 00:14 UTC
```typescript
type Boots = 'boots';
let lala = {
    nowBoots(saying: Boots): void; // works
    nowCats(saying: 'cats'): void; // doesn't works
}
```

**Comment by DanielRosenwasser** [comment] 2016-02-10 06:09
Looks like a duplicate of #6143.

**Comment by mhegazy** [comment] 2016-02-11 07:02
should be fixed in master.

**Closed by mhegazy** 2016-02-11 07:02 UTC
Labels: Bug, Domain: Literal Types, Duplicate
