### ISSUE TITLE
TS 1.5.4, VS2015, compile on save is not working

### ISSUE THREAD

**Issue by Lanayx** [Microsoft/TypeScript#4296] opened 2015-08-13 07:15 UTC
I've tested this on two different machines with vs2015 pro and enterprise versions. 1.5.4 broke the compile on save.  ( I didn't touch default settings, compilation type is AMD).  When I reverted to 1.5.3 it worked fine again.

**Comment by danquirk** [comment] 2015-08-13 15:56
Hm, we shipped 1.5.4 in part to fix a compile on save issue in 1.5.3 with --out https://github.com/Microsoft/TypeScript/issues/3939, haven't seen other reports like this yet. Are you using any other tools/extensions in your build process that could be affecting it?

**Comment by UTGuy** [comment] 2015-08-13 19:36
is it like this #3949?

**Comment by Lanayx** [comment] 2015-08-14 06:54
Here are all the VS extensions I have. I have neither tsconfig.json nor Redirect JavaScript output to directory set (Project type is Telerik Appbuilder project and it doesn't have such an option). What I notieced is when I saved .ts file, I got a visual studio message in the left bottom corner which said "output generation cancelled".

![ce3b1-clip-63kb 1](https://cloud.githubusercontent.com/assets/3329606/9268602/659d5290-4269-11e5-923e-f297415a9c64.png)
![b4b00-clip-34kb 1](https://cloud.githubusercontent.com/assets/3329606/9268606/6e9a17f2-4269-11e5-8623-74bea0a9e5f9.png)

**Comment by paulvanbrenk** [comment] 2015-08-14 17:00
What kind of project is this, can you share a small sample project this happens in?

**Comment by Lanayx** [comment] 2015-08-14 19:13
Here is the sample template project telerik provide
https://github.com/Lanayx/TelerikAppbuilderTypescriptSample
To run it you need to create a temp account here: https://platform.telerik.com/. Also, Telerik Appbuilder extension is needed. What I expect is when saving index.ts file, index.js should also be changed. It has been working for me more than a year before 1.5.4 typescript version.

**Comment by paulvanbrenk** [comment] 2015-08-14 22:12
Is this the only project type where Compile on Save doesn't work for you?

**Comment by Lanayx** [comment] 2015-08-15 09:11
I've found out the actual issue, that happens for any type of project.
It depends on the TypeScriptCompile tag for the file. If it exists, compile succeeds, if not it fails. All my existing files doesn't have such a tag, that's why none of them compiles. 
Currently, if you add a .ts file through the Add new item, this tag is added to the project file, but if you copy a .ts file from existing one, this tag is not added and compile on save fails.

**Comment by Knecke** [comment] 2015-08-17 06:40
I'm running 1.5.4 and I still have the problem when using "${ProjectDir}/output" as the place to compile the files. If I specify the absolute path, compile on save works as expected.

**Comment by paulvanbrenk** [comment] 2015-08-17 18:09
@cannehag Yes, the aliases don't work for 1.5.4, that's something we're looking at for 1.6.

**Comment by paulvanbrenk** [comment] 2015-08-17 18:10
@Lanayx where do you copy the file from, a project in the same solution or a file from the file explorer?

**Comment by Lanayx** [comment] 2015-08-18 05:04
A project in the same solution. Haven't you reproduced that? What I want is files to be compiled even without TypeScriptCompile tag like in previous versions.

**Comment by ProfessionalNihilist** [comment] 2015-08-18 09:58
Hey,

Both myself and a colleague have hit this issue today.

We have a number of projects that use TypeScript, each .TS file has been added through the `Add New Item` menu and so each one has a `TypeScriptCompile` element in the project file. The projects in question are either library or console projects. 

We are compiling our typescript as AMD modules, the JavaScript files are not combined or minified or have any other processing done to them as they are simply embedded resources in the assemblies.

**Comment by paulvanbrenk** [comment] 2015-08-18 16:45
@ProfessionalNihilist did that work before? Which version of VS are you using? And to confirm you're using a "Windows Console App".

**Comment by paulvanbrenk** [comment] 2015-08-18 17:04
@Lanayx I couldn't reproduce that with any of the standard project in Visual Studio, it seems to only happen in the Telerik Appbuild project, and in there Compile on Save works as expected when you set the content type to TypeScriptCompile.

So closing this as External.

@ProfessionalNihilist since you're issue doesn't seem related I copied it over to #4350

**Closed by paulvanbrenk** 2015-08-18 17:04 UTC
Labels: Bug, External, Needs More Info

**Comment by Serguzest** [comment] 2015-08-18 17:05
@ProfessionalNihilist  @Lanayx  do you see "output generation cancelled" when you save ts files?
![image](https://cloud.githubusercontent.com/assets/841238/9336796/2592a2d0-45e4-11e5-82ce-c5c5ccf566d6.png)

**Comment by Lanayx** [comment] 2015-08-18 18:20
@Serguzest - yes, I do

**Comment by seldary** [comment] 2015-08-23 14:03
I get the "Output generation canceled" too.

**Comment by dorad007** [comment] 2015-08-27 17:49
Me either. Had a big project developed in VS 2015 RC without any problem, and now after the uprade it's happing even if i open a new templated ts project.

**Comment by homesar** [comment] 2015-09-06 04:48
Verify your tsconfig.json file.  I was getting the Output generation canceled message and when I added my .ts file to the config, it worked.

**Comment by dorad007** [comment] 2015-09-06 05:48
Already tried without success... Thanks

**Comment by mhegazy** [comment] 2015-09-06 21:42
@dorad007 can you try the latest [1.6-beta release](http://blogs.msdn.com/b/typescript/archive/2015/09/02/announcing-typescript-1-6-beta-react-jsx-better-error-checking-and-more.aspx)

**Comment by dorad007** [comment] 2015-09-11 12:33
Thanks for your reply, I didn't understand how to install it into vs. Anyway, I downgraded to vs2015rc until it's expirtaion, hope the issue to be resolved.

**Comment by mhegazy** [comment] 2015-09-11 17:44
why not use [VS 2015 RTM](https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx) if i may ask. you can always install community edition, with no expiration periods.

**Comment by dorad007** [comment] 2015-09-12 17:41
Because of this issue the community edition is useless for me, ts is not compiling on save...

**Comment by mhegazy** [comment] 2015-09-14 22:32
@dorad007 this issue is fixed in latest release: https://github.com/Microsoft/TypeScript/releases/tag/v1.6.0-beta, can you give this a try?

**Comment by Lanayx** [comment] 2015-09-15 13:54
I have checked, 1.6.0-beta does fixes the issue

**Comment by dorad007** [comment] 2015-09-15 17:24
OK, Reinstalling.

**Comment by mhegazy** [comment] 2015-09-15 17:26
@Lanayx there are multiple issues referenced in this post. which issue are we talking about here? is it copying files do not set their content type to "TypeScriptCompile"? or something else?

**Comment by Lanayx** [comment] 2015-09-15 20:26
@mhegazy It's about the header issue - compile on save was broken in 1.5.4 and fixed in 1.6.0, I guess all the issues in this thread originate from the same root.

**Comment by mhegazy** [comment] 2015-09-15 21:05
@Lanayx there are a few different issues. if 1.6 beta is not working for you, then your issue is one we are not aware of. i would appreciate it if you can point us to which issue you are still running into so we can fix it.

**Comment by setiabud** [comment] 2015-09-15 21:38
I can confirm that 1.5.4 also broke compile on save for ts file without a project (or with virtual project). Steps to replicate: File - New - File - TypeScript File then add anything valid TS - save to desktop (or where ever), then edit and save again. The js is not updated with new compilation. I am running VS 2015 Community.

**Comment by setiabud** [comment] 2015-09-15 21:45
Just tried installing 1.6.10 (beta) and it fixes the compile on save for non-project ts file.

**Comment by dorad007** [comment] 2015-09-16 10:51
I reinstalled VS2015 Community, opened a new project and put "npm install -g typescript" in command line

![image](https://cloud.githubusercontent.com/assets/5598420/9902819/02bcc87e-5c7a-11e5-87f2-bf4e8429e4c4.png)


What else do i have to do, because it's not working yet.

**Comment by dorad007** [comment] 2015-09-16 13:49
It's working. thanks!
