### ISSUE TITLE
Compile error with overloads and or types

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#11382] opened 2016-10-05 13:34 UTC
**TypeScript Version:**  2.0.3
**Code**

```ts
let x: string | number;

function foo(x: string);
function foo(x: number);
function foo(x: string | number) {

}
foo(x);
```

Produces a compile error. IMO the code should be fine.

**Comment by yortus** [comment] 2016-10-05 13:49
Duplicate of #1805

**Comment by RyanCavanaugh** [comment] 2016-10-05 15:15
In the future, all TypeScript bugs are duplicates.

**Closed by RyanCavanaugh** 2016-10-05 15:15 UTC
Labels: Duplicate
