### ISSUE TITLE
TypeScript is not infering the type properly in this case

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#37129] opened 2020-02-29 07:34 UTC
**TypeScript Version:**  3.8.x

**Code**

```ts
interface Bar {
    property: boolean;
}

let foo: ReadonlyArray<string> | Bar;
if (Date.now() === 0) {
    foo = { property: true};
} else {
    foo = ['Hello'];
}

if (Array.isArray(foo)) {
    console.log(foo[0]);
} else {
    console.log(foo.property); // <-- error
}
```

**Expected behavior:**
The else branch correctly understands that `foo` is of type `Bar`

**Actual behavior:**
TypeScript still thinks foo is `ReadonlyArray<string> | Bar`

**Playground Link:** [link](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgEJysg3gKGf5ABygHtDowBPALmQCMSSAbCOEAbhwF8ccWxkMRrQBKrACYkQTSgEEoUOJQA8AZzBRQAcwB8yAD5oMnYDGQAKACJxIAOhAkA7uYCUyALyfkABje4Cgowe2ESk5FBUtBoArhBcnFzIEEyqKP4EQiTBANoA5AASyUwkuQC6CbymFvKKlLbAqjVK5pkufngECFKqzBC2xVotjNnepS4JSSlpHfhdID0s-SSDmbbEZBSU49xAA)

**Comment by jcalz** [comment] 2020-02-29 20:43
Looks like a duplicate of #17002.  Please note that the bug report template asks for search terms and related issues.

**Comment by RyanCavanaugh** [comment] 2020-03-02 22:41
Please track at #36554

This is the correct behavior given the definition of `Array.isArray`

**Comment by HolgerJeromin** [comment] 2020-03-03 07:56
IMO this has nothing to do with Array stuff:

	let foo: boolean | string;
	if (Date.now() === 0) {
		foo = true;
	} else {
		foo = "hello";
	}
	foo; // still of type: boolean | string

Not possible without defining a specialized type "positive number" (no zero and even no negative value, no decimal points)

**Closed** 2020-03-05 18:00 UTC
Labels: Duplicate
