### ISSUE TITLE
Type inference when destructuring a lambda parameter doesn't work

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/TypeScript#4949] opened 2015-09-24 09:33 UTC
Paste this snippet in the [playground](http://www.typescriptlang.org/Playground):

```typescript
const result = [{ foo: 'hello' }]
	.map(({ foo }) => foo)
	.map(foo => foo);
```

If you hover over `foo` in the first `map()` call, you'll notice that its type is `any` (should be `string`).

The type of `result` is correctly inferred to be `string[]`, though. It just seems that there is no type information for destructured function parameters.

**Comment by danquirk** [comment] 2015-09-24 19:10
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/4937

**Comment by joaomoreno** [comment] 2015-09-24 20:00
You should then simplify the title of #4937, since it has nothing to do with generics.

```typescript
function f(fn: (o: { a: number })=>void) {}
f(({ a }) => { a /* is any, should be number */ })
```

**Comment by ahejlsberg** [comment] 2015-09-24 20:20
It's actually not a duplicate, but the two issues are related. I will put up a PR that fixes both shortly.

**Closed** 2015-09-24 22:55 UTC
Labels: Bug
