### ISSUE TITLE
Continual CPU usage from typingsInstaller process

### ISSUE THREAD

**Issue by MohamedWagih96** [microsoft/TypeScript#36950] opened 2020-02-19 12:23 UTC
- VSCode Version: 1.42.1
- OS Version: Ubuntu 18.04.4 LTS

Steps to Reproduce:

1. Launch VSCode.
2. Enable Typescript and Javascript language features extension.

Does this issue occur when all extensions are disabled?: 

No, As a matter of fact I disabled all the built-in extensions except **Typescript and Javascript language features** extension and the problem remains untacked but if I disabled it no more loud fans nor overheat.
Also, I tried the` code --status` command mentioned [here](https://github.com/microsoft/vscode/wiki/Performance-Issues) and I found that extensionHost is listed in the output and as they stated 

> When the process listing in the Process Explorer or the output of code --status shows that the extensionHost is consuming a high percentage of CPU then this is likely caused by an extension.

Finally, I monitored the CPU usage % while running VSCode with and without the mentioned extension I found the following:

- When the extension is disabled: 0%
- When the extension is enabled: Starts at 30% to 28% to 16% then keeps bouncing between 16% and 9%.

This issue overheats my laptop and I think that was not intended I mean why only this extension is causing me issues while the others are not? and no I can't just disable it and move on because I need it. The whole point of me using VSCode is this feature.

*P.S: I tried clean install and disabled gpu acceleration nothing worked.

**Comment by mjbvz** [comment] 2020-02-21 23:06
Moving upstream. A TS team member should be able to help you investigate why the typings installer process cpu usage never dies down

**Comment by MohamedWagih96** [comment] 2020-03-01 02:14
Hello, is there any updates on this issue?

**Comment by CN91** [comment] 2020-03-04 11:14
I am experiencing high memory usage caused by the language features for js/tslint. Disabling the tslint extension i had didn't solve the problem and also the language features itself seamed very slow.

It eats up my entire memory of 32gb.

**Comment by MohamedWagih96** [comment] 2020-04-18 11:52
Ok, So this problem now only occurs with ReactJS projects no matter how small or big the project is.
I tried editing NodeJS project with VSCode with no issues.
So what is going on here now?

**Comment by MohamedWagih96** [comment] 2020-04-18 13:01
Ok so it seems this [answer](https://github.com/microsoft/TypeScript/issues/22702#issuecomment-398871461) solves the problem completely.
However, autocomplete is not working for some required/imported packages.

**Comment by sheetalkamat** [comment] 2020-04-22 18:42
Duplicate of  #25104 
@MohamedWagih96  Please provide more details on repro and tsserver and ti log using [typescript nightly drop](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code) and open new issue 

You can upload logs by following these steps:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. In vscode or vscode insiders, run the `TypeScript: Open TS Server log` command
5. This should open a large file called `tsserver.log`. Please share this file. Additionally you can also share file `ti.log` created next to it.

**Closed** 2020-04-22 18:42 UTC
Labels: Needs Investigation

**Comment by MohamedWagih96** [comment] 2020-04-26 14:42
@sheetalkamat How exactly am I supposed to share these log files? Is there any conventional way of doing it? Because `code --upload-logs` is not working.

**Comment by sheetalkamat** [comment] 2020-04-26 15:24
You can upload logs by following these steps:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. In vscode or vscode insiders, run the `TypeScript: Open TS Server log` command
5. This should open a large file called `tsserver.log`. Please share this file. Additionally you can also share file `ti.log` created next to it.

**Comment by jessietang** [comment] 2020-10-13 02:36
Hello, Are there any updates on this issue?

**Comment by dixitanmol97** [comment] 2021-05-05 05:44
The answer here helped me, but is there any better solution without compromising with the features available yet?

https://stackoverflow.com/questions/60297386/typescript-javascript-language-features-extension-in-vscode-causes-my-laptop-t/61289034#61289034

**Comment by adicandra1** [comment] 2021-12-03 13:35
Hei, I just want to let you know that the stackoverflow answer mentioned by @dixitanmol97 above worked for me without breaking the autocomplete feature.

So in my case, I had a:
- vue 2 + typescript (v.4.4) + Element UI + Storybook project, 
- running in vscode 1.62
- OS Ubuntu 20.04
 
I had the same problem as mentioned above with vscode takes up constant cpu usage around 30%. I search around, then found that somehow VSCode built-in typescript extension watches node_modules folder outside the project (according to this [comment](https://github.com/microsoft/TypeScript/issues/46351#issuecomment-944021960) ) .
I believe, this behaviour is caused by default feature for javascript project mentioned [here](https://stackoverflow.com/a/53284005) that should be turned off for typescript project. 

I also add some setting mentioned in this [comment](https://github.com/microsoft/TypeScript/issues/34801#issuecomment-902555692) .

Summary I add these commands to my vscode workspace settings:
```
{
    "typescript.disableAutomaticTypeAcquisition": true,
    "typescript.workspaceSymbols.scope": "currentProject"
}
```

**Comment by teknology** [comment] 2025-01-14 23:16
I'm surprised that this is still an issue.

**Comment by jslmariano** [comment] 2025-02-23 06:24
Gosh how time flies and this is still an issue

**Comment by gainkode** [comment] 2025-03-11 15:26
It's still affecting me too, please fix it!

**Comment by mjbvz** [comment] 2025-03-11 15:31
If you're still seeing a problem, open a new issue and we'll take a look. Locking this one to make that clear

For any new issues, also make to include info such as an example project that triggers the problem
