### ISSUE TITLE
String.split is defined as returning string[], but values in the array can be undefined.

### ISSUE THREAD

**Issue by fpintos** [microsoft/TypeScript#52299] opened 2023-01-19 02:53 UTC
# Bug Report

### 🔎 Search Terms

string.split undefined

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about string.split

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230118#code/MYewdgzgLgBA2gQwDQCMC6MC8MBEALAUwBsiQcA6CAByIEsoAKAcgAEmBKAbgChRIQiBcqQDmDRKjRcYAehkwUMWhBhQAnlQIATGAhXQATrTAikCgK6x6MYAjAKCMc2C0EAZse3ldZ8KsIwIFCEBjB4dlpmyjAi5ggGdlAE2qogDjCGxiK6LjBgQU4u7p5a5NzccjAAkm4KSipUehApUGkIMG7OwFC0fsEIsJndRGowBAAemt0qAG4IdDqZJmYA7o4iBLDtBs49ALaOBAYGIAZllQDCIHtUtIKhEHgg5kQ64TOOVAYEH2BJOtYUKNXElull-AM6rZ7ChHEsRAAfZyuDxgLy8cAQARCUQMNwgEAMZAodhcbidMBgvz4wkIABc8LMKAZUCMJnYMAA3twYLyYN8oOYDPYEMICCZgjAANQKMUSvA8AC+QA)

### 💻 Code

```ts
const [a,b] = "hello".split('@');
console.log([a,b]); // b is typed as string, but it can be undefined. a, on the other hand, is guaranteed to be string and not undefined.

// If b is passed to a function that strictly expects valid string, we get a runtime error.
// Compiler should have prevented it by detecting that b can be string|undefined.
console.log(foo(a,b));
function foo(a:string, b:string) {
    return a.length + b.length;
}
```

### 🙁 Actual behavior

Variable `b` is typed as `string`, when it can have an `undefined` value. Correct type would be `string | undefined`, so compiler can detect if it is being incorrectly passed to a function that strictly expects a valid string value.

### 🙂 Expected behavior

String.split() return type should be `[string, ...(string | undefined)[]]` to be correct.
This would be breaking change for programs using strict checks, but it will help catch unexpected undefined values being passed around.

Current workaround is to fix the type on every split() call:
```ts
const [a,b] = "hello".split('@') as [string, ...(string | undefined)[]];
```

The compiler will then flag invalid calls using `b` as string.
[Playground Link](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230118#code/MYewdgzgLgBA2gQwDQCMC6MC8MBEALAUwBsiQcA6CAByIEsoAKAcgAEmBKGBCeaAJ1pgA5khjlxDfoKEwAPjACuYACYEAZoILL2cNGgDcAKFCQQRAuVJCGiVGnb6YAeicwUMWjygBPKlq48UsKiKAqw9DDACGBuBIoq6prK5Fyi4DBQhDAgmQR8MHjRyqKeMEIKCHzRUAT+UCCxMEEyRTBgOfGqGmBa5IaGLjAAkmpuHjxU3BB1DQgwakrAULTpmQiwUktE3jAEAB5+SzwAbgh0yk1QAsEwAO5xQgSwc3xKywC2cXl8IHx9gwBhEDvKi0cz5CB4EAKIgXQrHOJUPgEBFgGoXCIoHaqGpLaQZQqwdxRGIoOLNWRKLpJPomCBmCxWBhqEAgBjIFDsByGBZgPHpFlshAALmaIVFV2knAA3oYYPKYMioAo+DEEJYCMJMjAANRuDVavBGAC+hiAA)

**Comment by whzx5byb** [comment] 2023-01-19 03:22
> String.split() return type should be [string, ...(string | undefined)[]] to be correct.

That's not true because `''.split('')` returns `[]`.

And if you want to include `undefined` type you can enable `noUncheckedIndexedAccess`.

**Comment by MartinJohns** [comment] 2023-01-19 06:39
Duplicate of #49635. Used search terms: `split in:title`

**Closed** 2023-01-21 18:00 UTC
Labels: Duplicate
