### ISSUE TITLE
Make it possible to have partially discriminated unions

### ISSUE THREAD

**Issue by erik-kallen** [microsoft/TypeScript#48073] opened 2022-03-01 16:44 UTC
# Suggestion

I want to be able to write code like this:

```
type MyElement = { tag: 'img', src: string } | { tag: 'a', href: string } | { tag: string };

function f(el: MyElement) {
    if (el.tag === 'img') {
        console.log({ src: el.src });
    } else if (el.tag === 'a') {
        console.log({href: el.href })
    } else {
        console.log('other element');
    }
}
```

However, in the first branch, TypeScript doesn't want to decide whether I have a `{ tag: 'img', src: string }` or just a `{tag: string}`.

I understand that strictly speaking, it is correct, but in practice I have found myself wanting to write code like this a few times and failed.

Solutions I can think of is to either:

1. Make it "just work", or
2. Allow the use of a type like `Exclude<string, 'img' | 'a'>`, or
3. Add some kind of qualifier so I can write something like ` { tag: fallback string }` or something.

## 🔍 Search Terms

discriminated union
discriminated union fallback
exclude string

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment] 2022-03-03 18:57
I agree this is a shadow duplicate of negated types. Soundness trade-offs are made when the upside is very high and I don't think this meets the bar.

**Closed** 2022-03-06 18:00 UTC
Labels: Duplicate
