### ISSUE TITLE
Undefined values propagating unexpectedly when using exactOptionalPropertyTypes

### ISSUE THREAD

**Issue by ceremonious** [microsoft/TypeScript#45623] opened 2021-08-29 19:55 UTC
# Bug Report

When creating a new object from values in an object that were optional, the "optionality" of the property seems to propagating to the new object.

### 🕗 Version & Regression Information

This is a new bug that started occurring with Typescript 4.4 & the new exactOptionalPropertyTypes flag

### ⏯ Playground Link

[Playground](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true#code/C4TwDgpgBAkgZgOQgNwgJwDwBVwQDRQ6TxKpoFEQkD2wp6AfFALxQDalAulBAB7AQAdgBMAzu0Ep0nAFBQoAfkK4SUtHKgAuZcUS16aANwyZoSFADiEYAGkIIeAGEAhoIBCEAKoiIcAJaSwtgENjz8QmJQANb21HCETKyqZBgaAKL8aM4AxsDYbDacBACuPv6BDHgakmRV8jYyDMZm0HYgolgAFs7ALu5eZQEQQViJUADeGgVQAdGx8QBKEACOxX5ow9gMnNpWtvZOrh7ewr5DQUur65ujIU0yAL5sMSBxhJzGMgECaHA50FgIKJgBMNP4IAAbYRdHp9Y6DQIKbSCYoAWwARuhjPJwVCYb1XIJaPDTuVhsi0ZijI9TLgoCczoE2qI4oDgSwoMz8XCBqTztggcB7l9BD8-tkAYKAEygnF+SHQ7oE-oMsnCCkY9BQAA+UFKfMC2KguMVsMJxN5jPJUBRmupD1p5lV52ZrOlHK5Sp5zsCAuBUuF2WognZAmBAHl0QArCC5bRskGsSZyhXco6WtXaACMdWN8rxXvNwBJVvVUClNJkAHoq5IAO6RmO5KAAMhtEAb0djwBl3VQUGAnWgomcqOgLQI6OKIJ9w2Z4bg9cb3db9IRc-sogXS67uV7zn7wj8cDg6CEIJaomrVYAgtkg2gj4IAOYD6hQCFDcsAFgIg-HdJvLOwjzouHbLs2oidNQxRQlAmJQAARCaaYquuwiITIQYhiCO5Nomsp5qmhZoQa1phsAEHAAAdChJElmquZ0WaghEsWGbnNoFFUbR+amsqbEMecVQOi0a5kSBm7buBu4EZ6LFCb6LRvHh3YMCY2Hsqpe4csmREFgpHGBNmihQFmWh6uhTF8ahglGdaWY0mJwGgdpPYepuqGKZsynxG5AYyEAA)

### 💻 Code

```ts
type IfNever<Type, TypeIfNever, TypeIfNotNever> = [Type] extends [never]
  ? TypeIfNever
  : TypeIfNotNever;

type GetKeyIfCanBeUndefined<T, K extends keyof T> = IfNever<
  Extract<T[K], undefined>,
  never,
  K
>;
type KeysThatCanBeUndefined<T> = {
  [K in keyof Required<T>]: GetKeyIfCanBeUndefined<Required<T>, K>;
}[keyof T];

interface Test {
  fieldThatCanBeUndefined?: number;
  fieldThatCannotBeUndefined: number;
}
type UndefinedKeysofTest = KeysThatCanBeUndefined<Test>;

interface Test2 {
  fieldThatCanBeUndefined: number | undefined;
  fieldThatCannotBeUndefined: number;
}
type UndefinedKeysofTest2 = KeysThatCanBeUndefined<Test2>;

const testObject: Test = {
  fieldThatCanBeUndefined: 1,
  fieldThatCannotBeUndefined: 2
}

//newObject & newObject2 have the same type, but UndefinedKeysOfnewObject & UndefinedKeysOfnewObject2 have different types
//According to line 24, the type of UndefinedKeysOfnewObject should be "fieldThatCanBeUndefined"
const newObject = {
  fieldThatCanBeUndefined: testObject.fieldThatCanBeUndefined,
  fieldThatCannotBeUndefined: testObject.fieldThatCannotBeUndefined,
}
type UndefinedKeysOfnewObject = KeysThatCanBeUndefined<typeof newObject>

const newObject2 = {
  fieldThatCanBeUndefined: 1 ? 1 : undefined,
  fieldThatCannotBeUndefined: 1
}
type UndefinedKeysOfnewObject2 = KeysThatCanBeUndefined<typeof newObject2>

```

### 🙁 Actual behavior

The type of `UndefinedKeysOfnewObject` is never

### 🙂 Expected behavior

The type of `UndefinedKeysOfnewObject` should be `fieldThatCanBeUndefined`

**Comment by andrewbranch** [comment] 2021-08-30 18:56
This is a great theoretical demonstration of the issue. I’m curious though, did you discover it through more realistic code? I’m curious how often this comes up when people aren’t piping properties through a bunch of mapped types and conditional types.

**Comment by ceremonious** [comment] 2021-08-30 19:18
Yes! I ran into this bug while trying to implement a `makeUndefinedValuesOptional` function. This is actually a function that already existed in our codebase, but the addition of Typescript 4.4 & exactOptionalPropertyTypes meant we could type the function more correctly. The core idea is to have a function that converts an input like: `{sampleField: number | undefined}` to `{sampleField?: number}` using the delete operator.

This [playground](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true&ts=4.4.2&ssl=18&ssc=17&pln=18&pc=44#code/C4TwDgpgBAkgZgOQgNwgJwDwBVwQDRQ6TxKpoFEQkD2wp6AfFALxQDalAulBAB7AQAdgBMAzu0Ep0nAFBQoAfkK4SUtHKgAuZcUS16aANwyZoSFADiEYAGkIIeAGEAhoIBCEAKoiIcAJaSwtgENjz8QmJQANb21HCETKyqZBgaAKL8aM4AxsDYbDacBACuPv6BDHgakmRV8jYyDMZm0HYgolgAFs7ALu5eZQEQQViJUADeGgVQAdGx8QBKEACOxX5ow9gMnNpWtvZOrh7ewr5DQUur65ujIU0yAL5sMSBxhJzGprhQGdkANsVTiczoEAGrOAEQURbFgTKahWYvN5YHY-Xj-QEQfKFEqDCrGB6fPhgahoYBQOClXJ+aiCKAAW2cMWB5WG4MhogA8mBgDTBBCtgAKDTUABGACttFgqgBKbSc+l+PLSqBtDrdXpHAanVkjBhMABkGgACs4yX4Bca-NkohhfgCgXi2RDilCtiF7Oqen1jk69fq4fJORKILkAHQvUSCsXimVhuCktI5TqCwUvGUsJiTeTybK00Tk5AQ2Ex572KDOcRI+Io4w5mbxQVFv4sZisUo684Z7P1qCnP7WaCll4Vqvzd51nMPDQPGWTjbAYpoOkxgkmAICNBwHLQTyidCBnN+YTaAtoAIAc0n8gHqD+Cm0gmK9NF6DXMkpgmptKg2Q2PQgJAAHc93QQVj1PYBz0EC8CFETpqGKP5hAAQVEUQ-AvQQABkpD+bRRWoagB1cOUoFAtBD3kAB6ajCE6PxxG6cRXB4NA0FJKBX2yZxin3KBbwgFtGKgQRaArP4-moIDhigYBqC46BiT+a0lT+EAoH3clKygDsQWGDQaLohclzpHsjN7CCZmEOoc1o3tBPwzSEKQ1D0MwnC8MUKAAEYtF0v1bIs6dDKgWiuhEoDSSicRRWKckRNcMSQEvOSFJaKBEOAUL7LzQQC10-c0G0CjYXMsK6PrKzjxyujp3rey-EbeDEOQtCMKw3C727Wrez49Aw0c2EfOvCqoHquzjOsUzCrfEwGuoiLxGEagoVE8TulQCs6XQDjKO43j+MZZk-XZV0uR5Pli38Xg1uATpoEY0RXV6vKCv64ryKK2Fju1fThDOqFuV5WkIUFcr7Kqk9rKCsb60c08XLa9zOq8pQ-O0PTdVh+zZ16kzl1mox5smpbnNa4QoCitAogIOLyRWtaxPJA7+sy+J7pEuKL1Ct7yQEekwGDcVQ2AbRxkch9ROfV80AeMqEd8wlefzckPpK77WF+llzkBi6Qf5P5wdC+RqpsqATYEvDtAFoWQ3DRzQtnUaCbpD6CSAA) shows how I discovered the bug.

**Comment by ceremonious** [comment] 2021-08-31 06:59
FYI, I ended up finding a different way of implementing what I want to do ([playground here](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true&ts=4.4.2&ssl=53&ssc=1&pln=54&pc=1#code/C4TwDgpgBA4hwGkIgJIDMDCBDAdgIQgFUcATCNASxwhIB4AVAGigSggA9gJSBnKAa2QB7NFHoA+KAF4oAV1LkqNNp24k+9ANoIAulAD8LKAC4o1AG4QATgG4AUKEgtkPegAsswbPiILK1OglpKABvOygobSgqAWFRACUIAEdZCisaBnEdUzhEZHRvAmIyfwzElLSMiWYEcXsAX01BEBExHXsHcGgAUXYAYwAbWTJixQCANSwhiB5M4LCIqJjm1vpsqF7B4YgGbR1meRKlEjq7eo6OMCErYCg0eT7gCiEcKABbLEFR0pJJ6Z4APJgJ4vKaZAAU4SgQgARgArUxMOwASlMALeFGADBqLncnkKviOAUykgAZFCAApYG4UMEUih9fi0TZDEZ+Y5-WQzTI4kCuDxeXBFdnEiTiSQLKAA+EQR4AOmaPHBsLhyLlaGu3SwfTc4PBzWR0glUIifRePFu5imwRVTWQUCwfBWojW9giEQoonBVoG0ikMkOYxohsl7qgZAG8GgtuaDqdcTabvd9Sh9WRSfSwFkVleKoadjsVC4VjQ2ughB41lCJuiJFMFqsVAA5kmIpHLAN9KYcLI3jDrPm7PccI9nq8+ulPBAAHIQADuFes4IodagDebzB4biEsgGJAAgjweBQmzgADIQDumGFCISR3CoqCLqzVsMAejfYjcFD4Hj4uDYKwrGuKB+z6LBZErKB2wgX0fzMIRbimAYhDnZRgCEUDoEuAYGUxAYQDXeA4zkEUaBrD8oEzbNXlDKBKLDFdTBXRgKM-MMYIGett13A8jxPc9L1ggwoAARhMUiiRoVj30-FM2PceC52ufg+BhWRbng3AcCEEBmygDCDK6aENLYqAzRwC05ErKxTGfeYzMY1cVzMlNZOiL0tx3PdD2PU8Lw7ENHPdSDrDlTjglE1t6LkszqJzayBwLWTFL4EghBmBDbg8SwHVeaxgJfMCIKgj4vjI34pi5QFgTHa1KHYTLgDcaAfx4LkzIsqzQtsp8bOCMrCSDSr-iBEEcCmcE6IY90mNrGT3RmtshK4tceJ8-j-JWkTxNMQMfgWiJKLTOL4BoxLbGSxa31StbvJIKBlKsfhmHU250synTbmK0LoVEZr4PUpsay624uDeMBpThWVgFMEJOK7Mxe37Kx6nmTjTFE84QfNW4eoGz4hp+TkZjGuqBimmsPWckhmCp6CVtMcHIZleVOJrNNovi14eoaIA))

The conditional I was using to check if a value could be undefined was unnecessarily complicated. I'm now doing `undefined extends T[K] ? K : never` instead of `IfNever<Extract<T[K], undefined>, never, K>`

**Comment by jcalz** [comment] 2021-09-30 14:44
@andrewbranch Is this the same underlying problem which is causing the following assignment to fail?

```ts
declare const x: { a?: { b: string; }; } & { a?: { c: string; }; }
const y: { a?: { b: string } } = x; // error with --exactOptionalPropertyTypes enabled
/*
Type '{ a?: { b: string; }; } & { a?: { c: string; }; }' is not assignable to
type '{ a?: { b: string; }; }'. 😲 Types of property 'a' are incompatible.
*/
```
[Playground link](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true#code/CYUwxgNghgTiAEYD2A7AzgF3gDwFzwG94oB+fIgI30xgEsUBzAbngF8XX4AyQ4s3sNQx1GHDgChk6LAE9yfeVXg16DNuoC8OFgHod8EDBhIY8AO60MAC3gBaWyGxQwGAPIAHDLVRQIABWN3QwwZABUZILQDFCgKCBBgcR0AKnFwoPgAciJSRSERZjYObl5cgXzVMTZM+FoolCQsKDQ0WgYYuIQMJHEQjOyFXiUVUSLqgDp4QF4NwCY9+HSQKKQAM3h3QOCZLKga2AR6ZABbdygvTvHxZJ0gA)

This is causing, for example, conditional type inference from contravariant positions to fail (see [this SO comment](https://stackoverflow.com/questions/50374908/transform-union-type-to-intersection-type/50375286?noredirect=1#comment122652191_50375286) about `UnionToIntersection`).

If this is the same bug then I guess 👍 for fixing it.  If it's a different bug (or not a bug) then I guess I'll file it separately.

**Comment by andrewbranch** [comment] 2021-10-04 18:06
It looks like this is all fixed in the nightly, probably by https://github.com/microsoft/TypeScript/pull/46052

**Closed by andrewbranch** 2021-10-04 18:06 UTC
Labels: Bug
