### ISSUE TITLE
[noUnusedLocals] JSX spreading with type "any" excludes children from used variables

### ISSUE THREAD

**Issue by alitaheri** [Microsoft/TypeScript#15478] opened 2017-04-30 08:50 UTC
**TypeScript Version:**  2.4.0-dev.20170429

**Code**

```ts

export function render() {
    const foo = 'foo'; // Gives error when noUnusedLocals are enabled.

    // foo is used here, but the compiler doesn't "see" it
    return <div {...{} as any}>{foo}</div>;
}
```

**Expected behavior:**
Since `foo` is used it should compile properly.

**Actual behavior:**
`'foo' is declared but never used.`

**Comment by mhegazy** [comment] 2017-05-03 23:12
This is caused by the same underlying issue as https://github.com/Microsoft/TypeScript/issues/15469. it should be fixed by https://github.com/Microsoft/TypeScript/pull/15548. The fix should be available in `typescript@next` tomorrow (5/4), please give it a try and let us know if you are still seeing issues.

**Closed by mhegazy** 2017-05-03 23:12 UTC
Labels: Bug, Fixed
