### ISSUE TITLE
TypeError: Cannot read property 'escapedName' of undefined in `symbolName` during `getOccurences`

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#20786] opened 2017-12-19 22:04 UTC
tsserver version: 2.6.1
hits: 37972

stack:
```
TypeError: Cannot read property 'escapedName' of undefined
    at symbolName (tsserver.js:67404:23)
    at getImport (tsserver.js:67344:36)
    at Object.getImportOrExportSymbol (tsserver.js:67271:68)
    at getImportOrExportReferences (tsserver.js:68097:56)
    at getReferencesAtLocation (tsserver.js:68045:17)
    at getReferencesInContainer (tsserver.js:68007:21)
    at getReferencedSymbolsForSymbol (tsserver.js:67748:25)
    at Object.getReferencedSymbolsForNode (tsserver.js:67664:24)
    at Object.getReferenceEntriesForNode (tsserver.js:67502:58)
    at getSemanticDocumentHighlights (tsserver.js:66388:57)
    at Object.getDocumentHighlights (tsserver.js:66377:20)
    at getDocumentHighlights (tsserver.js:79870:42)
    at getOccurrencesAtPositionCore (tsserver.js:79873:46)
    at Object.getOccurrencesAtPosition (tsserver.js:79859:27)
    at IOSession.Session.getOccurrences (tsserver.js:85781:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:85403:61)
    at tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId (tsserver.js:86660:28)
    at IOSession.Session.executeCommand (tsserver.js:86669:33)
    at IOSession.Session.onMessage (tsserver.js:86689:35)
    at Interface.<anonymous> (tsserver.js:87881:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mhegazy** [comment] 2018-01-20 20:31
The `Source: Telemetry` have limited information. we only have the call stack from the crash report. We need to either mitigate the crash, or add additional asserts to get more information in future crash reports.

**Comment by andy-ms** [comment] 2018-03-12 20:57
Duplicate of #21792

**Closed by andy-ms** 2018-03-12 20:57 UTC
Labels: Bug, Source: Telemetry
