### ISSUE TITLE
Function returning Partial<T> allows incorrect objects

### ISSUE THREAD

**Issue by nicolaslaplume** [microsoft/TypeScript#49821] opened 2022-07-07 04:52 UTC
# Bug Report

### 🔎 Search Terms

Partial

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220706#code/C4TwDgpgBAChBOBnA9gOygXigbwFBQKlQEMBbCALikWHgEtUBzAbn0OMcqIFdSAjBKwC+uAMZoaUSEjQUYxeMDrEANgB44M1AD5MOEuSoByACLEAbhCMAaKB0RUAzENbjUkzsE0pUVABQAlBja8orK6t5ouliBwX7YBlymFla29k5CAawEQA)

### 💻 Code

```ts
type Person = {
    name: string;
    age: number;
}
const person:Partial<Person> = {name: 'Dave', ags: 3};
const getPerson: ()=>Partial<Person> = ()=>({name: 'Dave', ags: 3});
```

### 🙁 Actual behavior

There is a single error, when assigning directly to `person`.

### 🙂 Expected behavior

There are two errors, with the same error about `Object literal may only specify known properties, and 'ags' does not exist in type 'Partial<Person>'` for the returned value of `getPerson`

**Comment by nicolaslaplume** [comment] 2022-07-07 04:58
and it looks that doing a direct cast also prevents the error from showing:
```ts
const person:Partial<Person> = {name: 'Dave', ags: 3} as Partial<Person>;
```

**Comment by fatcerberus** [comment] 2022-07-07 12:30
See also https://github.com/microsoft/TypeScript/issues/12936 (proposal for Exact Types).

**Comment by jcalz** [comment] 2022-07-07 12:40
Also duplicate of #37017 and quite a few others, and ultimately #241

**Closed** 2022-07-09 18:00 UTC
Labels: Duplicate
