### ISSUE TITLE
Intersected function type returns only first constituent's return type

### ISSUE THREAD

**Issue by vsiao** [Microsoft/TypeScript#10508] opened 2016-08-23 20:00 UTC
**TypeScript Version:**  1.8/Playground

**Code**

```ts
interface A {
	a: boolean;
}
interface B {
	b: boolean;
}

declare const fooAB: (() => A) & (() => B);
const ab = fooAB(); // A
```

**Expected behavior:** `ab` has type `A & B`

**Actual behavior:** `ab` has type `A`

Perhaps this is being treated as an overloaded call signature, and `() => A` just happens to be first. If this is by design, it would be great to learn about any known workarounds.

cc @kevinder

**Comment by kitsonk** [comment] 2016-08-24 17:57
this is covariance, right? dupe of #1394?

**Comment by mhegazy** [comment] 2016-08-24 18:51
`(() => A) & (() => B);` is not equivalant to `(() => A & B);`. 

`(() => A) & (() => B);` is equivalent to 
```ts
declare const fooAB: {
    (): A;
    (): B
};
```

**Comment by aluanhaddad** [comment] 2016-09-04 05:55
@mhegazy I understand that the current behavior is practical, but the only way a function could actually implement the intersection would be by returning `A & B`. Maybe it is not realistic but since, IIRC the compiler will always pick the first overload, it would be reasonable to expect the intersection.

**Comment by mhegazy** [comment] 2016-09-07 00:26
The compiler has no way of merging signatures in the general case. this one seems simple enough, but what happens if there are parameters involved, what if they have different count, what if one of them is generic, what if the parameter types do not agree.. for instance
`(a: number, b:string) => A` and `(a: string, b: number) => B`  is this `(a: number|string, b: number|string) => A&B` ? i do not think this is correct.

**Closed** 2016-09-07 00:26 UTC
Labels: Working as Intended

**Comment by aluanhaddad** [comment] 2016-09-07 01:59
@mhegazy I agree that's not correct specifically because the functions have different parameter types. This means that using the union of each corresponding parameter is not accurate. Interestingly though, this also means that there is a way to select the overload that you want, so I don't think these signatures need to be merged.

Obviously it's not a trivial problem.

I think the intuitive behavior would be to only merge signatures when they match exactly in arity and parameter types. 

My reasoning is that there's no way to statically select and thus differentiate between the different signatures that are available without using a type assertion.
