### ISSUE TITLE
Erroneous javascript generated with "export default function" and es6 target

### ISSUE THREAD

**Issue by srowan** [Microsoft/TypeScript#6777] opened 2016-02-01 03:50 UTC
Typescript 1.7.

When targeting commonjs / es6, the following typescript produces no errors on compilation:

> export default function() {
>     var hello = "world";
> }

but generates invalid javascript:

> function () {
>     var hello = "world";
> }
> exports.default = default_1;

**Comment by DanielRosenwasser** [comment] 2016-02-01 04:01
Duplicate of #5844. Should be fixed in 1.8 beta and the nightlies.

**Closed** 2016-02-01 04:01 UTC
Labels: Duplicate
