### ISSUE TITLE
Intermittent type errors when opening or editing files with typescript 3.7

### ISSUE THREAD

**Issue by KaelWD** [microsoft/TypeScript#34999] opened 2019-11-08 07:54 UTC
- VSCode Version: 1.40.0 (and 1.39.2)
- OS Version: Kubuntu 18.04

Steps to Reproduce:

1. `git clone -b refactor/ts37 https://github.com/vuetifyjs/vuetify.git`,  run `yarn && yarn build`, then open it in vscode
2. Open `VTreeView.ts` and `VtreeViewNode.ts`
3. Reload the window, wait for the language server to start then switch to the other open file
4. When the errors appear, make a small edit, save the file, then undo it

[Video demonstrating the problem](https://github.com/microsoft/vscode/files/3823455/2019-11-08_18-09-06.mkv.zip)
[And anotha one](https://github.com/microsoft/vscode/files/3824958/2019-11-09_00-47-53.zip)

This doesn't seem to occur with ts 3.5 (master branch)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-11-08 18:54
Confirmed with TS 3.8.0-dev.20191105. Does not depend on VS Code version and does not happen with TS 3.6.3

**Comment by AnyhowStep** [comment] 2019-11-08 19:03
Is this a composite project?

**Comment by AnyhowStep** [comment] 2019-11-08 19:37
Okay, I feel like this is probably the most relevant issue,
https://github.com/microsoft/TypeScript/issues/33067

**Comment by KaelWD** [comment] 2019-11-09 04:19
Yep, it works fine when you build it. Those related issues look a lot like this other problem I had a while ago, where recursive types worked in vscode but were `never` in tsc: https://github.com/microsoft/TypeScript/issues/23897#issuecomment-417872711

**Comment by sheetalkamat** [comment] 2020-01-29 21:05
Duplicate of #23897 where in order of resolution changes the result

**Closed** 2020-02-01 18:00 UTC
Labels: Duplicate
