### ISSUE TITLE
instance.constructor type narrowing not working in switch

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#41721] opened 2020-11-29 12:58 UTC
**TypeScript Version:**  4.2.0-dev.20201127

**Search Terms:** switch, narrow, constructor

**Code**

```ts
function foo(o: any) {
    switch (o.constructor) {
        case Array: {
            o // o: any
        }
    }
}
function bar(o: any) {
    if (o.constructor === Array) {
        o // o: any[]
    }
}
```

**Expected behavior:** Both functions narrow the value to `any[]`

**Actual behavior:** Switch fails to narrow value

**Playground Link:** [playground](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201129#code/GYVwdgxgLglg9mABMOcAUcBciCGYCeAlIgN4CwAUItYgM4DuMUEAFohgHQQK1QBOIaHD7FyVGhIg5aAU0QBBPnxz5sYiRppxEAeh2IsuApU3UAviZoWK10JFgJEAIxx8M2PEVKXqMYOzguHn5BKGFEAF4ohSUVUR8NbT0DDwIAbQBdBOszIA)

**Related Issues:** https://github.com/microsoft/TypeScript/issues/2214#issuecomment-431470212, #32774

**Comment by MartinJohns** [comment] 2020-11-29 13:17
Related / duplicate of #28936, #3841. Search terms used: `constructor narrow`

**Comment by pushkine** [comment] 2020-11-29 13:58
The issue is that IfBlocks have a special `<var>.constructor === <class>` handling that isn't mirrored in switch blocks
The issues mentioned by @MartinJohns are not related to switch blocks

**Comment by MartinJohns** [comment] 2020-11-29 14:07
You're right. It's actually a duplicate of #16035.

**Closed** 2020-12-04 18:00 UTC
Labels: Duplicate
