### ISSUE TITLE
Type guard does not work with object properties

### ISSUE THREAD

**Issue by tkrotoff** [Microsoft/TypeScript#6238] opened 2015-12-24 12:35 UTC
This works:

```TypeScript
let strOrArray: Array<string> | string;
let str: string;
if (typeof strOrArray === 'string') {
  // No error
  str = strOrArray;
}
```

But not this:
```TypeScript
interface Data {
  strOrArray: Array<string> | string;
}
let data: Data;
let str: string;
if (typeof data.strOrArray === 'string') {
  // Error:
  // Type 'string[] | string' is not assignable to type 'string'.
  // Type 'string[]' is not assignable to type 'string'.
  str = data.strOrArray;
}
```

![typeguard](https://cloud.githubusercontent.com/assets/643434/11994668/e42384d6-aa42-11e5-9816-9b9779e8d801.png)

Tested with tsc 1.7.5 and Visual Studio Code 0.10.6

**Comment by ahejlsberg** [comment] 2015-12-25 01:34
This is a duplicate of #3812.

**Closed by ahejlsberg** 2015-12-25 01:34 UTC
