### ISSUE TITLE
The 'async' keyword could include an implicit 'Promise<>' in the return value

### ISSUE THREAD

**Issue by paleo** [microsoft/TypeScript#32551] opened 2019-07-25 13:26 UTC
## Search Terms

- async
- promise
- return
- declaration

## Suggestion

More and more APIs provide asynchronous functions, and it is unnecessary verbose to always suround the return value with a `Promise<>` annotation. In TypeScript annotations, would it be possible to use the `async` keyword in order to skip the `Promise<>` part in the return type?

### Example 1:

    async function f1(): number {
      return 12;
    }

… would be equivalent to:

    async function f1(): Promise<number> {
      return 12;
    }

### Example 2:

    interface I1 {
      f1: async () => number
    }

… or:

    interface I1 {
      f1: async () => Promise<number>
    }

… would be equivalent to:

    interface I1 {
      f1: () => Promise<number>
    }

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by dsherret** [comment] 2019-07-25 21:29
Duplicate of #7284.

**Closed** 2019-07-26 07:57 UTC
