### ISSUE TITLE
Offer to navigate to implementation(s) of a function

### ISSUE THREAD

**Issue by chrmarti** [microsoft/TypeScript#1093] opened 2014-11-07 18:58 UTC
Currently navigation using VS commands ends at interfaces. A "navigate to implementation(s)" action on function definitions would be great.

**Comment by zhangenming** [comment] 2019-08-21 12:04
like it

**Comment by DanielRosenwasser** [comment] 2019-08-21 18:30
Duplicate of #6209 (even though this issue is older). This now exists in the form of `Go To Implementation`. You can view the command via the Command Palette in VS Code.

**Closed by DanielRosenwasser** 2019-08-21 18:30 UTC
Labels: Duplicate
