### ISSUE TITLE
Type narrowing not respected for callback functions

### ISSUE THREAD

**Issue by bdirito** [microsoft/TypeScript#44934] opened 2021-07-07 21:09 UTC
A type narrowed variable is not respected as being type narrowed when used in a callback function. 

In the following code line 17 `aList.map(() => found.toLowerCase());` produces the following error: `Object is possibly 'undefined'.`

```
function fn(a: string, aList: Array<string>): void {

  // type of found will be string | undefined
  let found = aList.find(v => v === a);

  // type of should now be narrowed to just string
  found = 'abc';
  
  // type narrowed - ok!
  found.toLowerCase();

  // aliasing found is fine
  let f = found;
  aList.map(() => f.toLowerCase());

  // ERROR: found should be narrowed now...
  aList.map(() => found.toLowerCase());
}
```

[Playground Link 4.3.5](https://www.typescriptlang.org/play?ts=4.3.5#code/GYVwdgxgLglg9mABMMAKAhgLkQZygJxjAHMAaRdAGRj2wEF990BPAHj0JID4BKbANzgwAJogDeAWABQ0xIgD08xFGYAHAKaI4wZHHCiA7jAA2xxACNNHIsUQAfRPvXAi64bMTH1UXfsQBeCmo8ADoXMGFUfgCuRGj-BIoeAG5pD0VlNU1tXAALPWNRMDgDC00wdEYSt2U4RAArEDxcAhsPYD0IgMQAcnRzCB7UqTl0pRUNRAqqgxqAWi0AawBCds7hEKg4Smr8AGF0HHVUFLSRhSV0YxhDm18ummRXDy8fHUCO-WG5KhooEIAtuhVKgTjFkJttrsDkcTqcZOcMgBRABKKIA8ijsJ8ujh8iBCmUppV8NUiiUQpSPL9QkCQWD-LEcRstjtZvtDscePCAL7SIA)

[Playground Link 4.4.0-beta](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/GYVwdgxgLglg9mABMMAKAhgLkQZygJxjAHMAaRdAGRj2wEF990BPAHj0JID4BKbANzgwAJogDeAWABQ0xIgD08xFGYAHAKaI4wZHHCiA7jAA2xxACNNHIsUQAfRPvXAi64bMTH1UXfsQBeCmo8ADoXMGFUfgCuRGj-BIoeAG5pD0VlNU1tXAALPWNRMDgDC00wdEYSt2U4RAArEDxcAhsPYD0IgMQAcnRzCB7UqTl0pRUNRAqqgxqAWi0AawBCds7hEKg4Smr8AGF0HHVUFLSRhSV0YxhDm18ummRXDy8fHUCO-WG5KhooEIAtuhVKgTjFkJttrsDkcTqcZOcMgBRABKKIA8ijsJ8ujh8iBCmUppV8NUiiUQpSPL9QkCQWD-LEcRstjtZvtDscePCAL7SIA)

**Comment by MartinJohns** [comment] 2021-07-07 21:13
Another duplicate of #9998.

**Closed** 2021-07-07 21:33 UTC
