### ISSUE TITLE
isNaN parameter should be any (or unknown?)

### ISSUE THREAD

**Issue by victorz** [microsoft/TypeScript#37449] opened 2020-03-18 10:37 UTC
According to the spec (see references below), `isNaN()` should be able to take any kind of value, which would be coerced into a number (using something like `Number(value)`, which seems to make sense from my tests).

Forcing the parameter to be `number` breaks legacy code which relies on being able to pass string arguments to `isNaN()`.

```ts
function f(value: string) {
  if (isNaN(value)) { // compilation error, but should be OK
    ...
  }
}
```

Removing the `string` type from the `value` parameter admittedly fixes the compilation error, but breaks the "no implicity any" rule.

References:

- Spec: https://tc39.es/ecma262/#sec-isnan-number
- Type declaration: https://github.com/microsoft/TypeScript/blob/f8083d291719c7671a876578234edea0ee33d624/lib/lib.es5.d.ts#L53

**Comment by MartinJohns** [comment] 2020-03-18 10:46
Please respect the issue templates for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) and [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md).

---

Both issue templates urge you to first search for existing issues and asks for information (including the search terms you have used to search for existing issues).

This is a duplicate of:

- #3947
- #4002
- #11414
- #12302
- #13227
- #15173
- #16427
- #19153
- #21065
- #23464
- #29607
- #34609

Search terms used: `isNaN`

**Closed** 2020-03-18 18:30 UTC
Labels: Duplicate

**Comment by victorz** [comment] 2020-03-18 18:36
Huh. Fair enough. I see your point in alternate solutions.

However, the original reason for closing the first report of this issue is incorrect. https://github.com/microsoft/TypeScript/pull/3947#issuecomment-123558773

> Reading more the ecmascript doc the argument is specified as Number.

"Number" in the spec is not the type, confusingly enough. It's the parameter name. That becomes evident when you read the algorithm for isNaN().

Regarding searching for issues and issue templates: I simply found the line of code I was looking for in the GitHub project file browser, clicked the little ellipsis next to the line number, and selected "Reference this in a new issue." There was no issue template. Sorry for that, I suppose. I typed "isNaN" in the title but none of the "similar issues" were the same as this one in my opinion. I don't mean to get defensive but I tried and sometimes mistakes happen.

Either way, I still feel like this is in violation of the spec, and that `Number.isNaN()` should be the one whose parameter should have type `number`.

Thank you for your consideration.

**Comment by MayCXC** [comment] 2023-08-16 20:35
Ah, I was using issues search incorrectly, as were some of the others. However, I do think that both the issue reporters and issue closers are making misinterpretations of the ECMA spec. `Number.isNaN` and `isNaN` are both intended to be used on non-number values and should be typed accordingly, for the same reason that both `===` and `==` are valid operators in typescript. An example/counterexample is that `isNan("NaN")` is `true` while `Number.isNan("NaN")` is `false`, not because `isNan` is coercing `"NaN"` incorrectly, but because it is meant to coerce "NaN" as per the spec. I can see the benefit to code clarity of making ts users do `toNaN(Number("NaN"))` rather than rely on ECMA's `ToNumber` algorithm, but it would be more appropriate to make your own standard library to address those concerns rather than misrepresent ECMA's.

**Comment by victorz** [comment] 2023-09-01 10:51
I don't know where this comment by "Aaron Paterson" went (removed?), but I thought it was very insightful:

> I do think that both the issue reporters and issue closers are making misinterpretations of the ECMA spec. Number.isNaN and isNaN are both intended to be used on non-number values and should be typed accordingly, for the same reason that both === and == are valid operators in typescript. An example/counterexample is that isNan("NaN") is true while Number.isNan("NaN") is false, not because isNan is coercing "NaN" incorrectly, but because it is meant to coerce "NaN" as per the spec. I can see the benefit to code clarity of making ts users do toNaN(Number("NaN")) rather than rely on ECMA's ToNumber algorithm, but it would be more appropriate to make your own standard library to address those concerns rather than misrepresent ECMA's.
