### ISSUE TITLE
for...of supported array/collection types

### ISSUE THREAD

**Issue by djarekg** [Microsoft/TypeScript#2973] opened 2015-04-30 19:43 UTC
If for (var v of expr) { } is emitted as..

for (var _i = 0, _a = expr; _i < _a.length; _i++) {
    var v = _a[_i];
}

then shouldn't HTMLCollections be allowed since were just looping over the indexes?

**Comment by mhegazy** [comment] 2015-04-30 19:48
This looks like a dupe of #2695. It should be fixed in the TS 1.6

**Closed** 2015-07-09 00:13 UTC
Labels: Duplicate
