### ISSUE TITLE
Narrowing generic union function argument doesn't narrow return type based on generic

### ISSUE THREAD

**Issue by zachstence** [microsoft/TypeScript#57190] opened 2024-01-26 16:35 UTC
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

I am using the generic "Other" template for this issue because I am not sure if it is a bug, I am misunderstanding something, or it would be a feature request. I would be happy to close and reopen with another template if necessary!

**Reproduction:**
https://www.typescriptlang.org/play?ts=5.4.0-dev.20240126#code/MYewdgzgLgBAZjAvDAPAFRgUwB5U2AEwhgHIBDEmAH1ICMSA+ACigC4Y0BKdjHPQ4uUoB+UtkrsSAT0qIGMAN4BYAFAwYASwQskiZEM4wATpigBXI2DElV6k+cukZqgL6qgA
```ts
const f = <T extends 'a' | 'b'>(t: T): T extends 'a' ? 'x' : 'y' => {
  if (t === 'a') return 'x' // Type '"x"' is not assignable to type 'T extends "a" ? "x" : "y"'. (2322)
  return 'y' // Type '"y"' is not assignable to type 'T extends "a" ? "x" : "y"'. (2322)
}
```

**Expected behavior:**
Compiles without error, and function return type is narrowed by control flow in function body checking type of argument

**Actual behavior:**
`Type '"x"' is not assignable to type 'T extends "a" ? "x" : "y"'.(2322)`
`Type '"y"' is not assignable to type 'T extends "a" ? "x" : "y"'.(2322)`

**Notes:**
This is a minimal reproduction of a problem I came across when trying to do something similar with class generics and fields. I would be happy to provide some more detail about why this would be useful if necessary.

**Comment by zachstence** [comment] 2024-01-26 16:38
I have also taken a look at https://github.com/microsoft/TypeScript/issues/7294 and https://github.com/microsoft/TypeScript/issues/13995, but I think this issue is different from those. However I may be overlooking something inherently wrong with the code, and would love some insight here.

**Comment by MartinJohns** [comment] 2024-01-26 17:12
Duplicate of #33912.

**Closed** 2024-01-29 01:25 UTC
Labels: Duplicate
