### ISSUE TITLE
Valid JavaScript with `in` inside `for` produces syntax errors and invalid JavaScript output

### ISSUE THREAD

**Issue by evanw** [microsoft/TypeScript#54769] opened 2023-06-25 13:34 UTC
# Bug Report

### 🔎 Search Terms

for in syntax error

### 🕗 Version & Regression Information

- This is the behavior in every version available in the playground

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYewTgBAFANgpgFwgbQB4QLwQOQENsQCWAdhAN4C+AuhCMCslVQJQQDGIxAziPAHQwQAcyipmAKFCRYicuix4CJchQq16ySi3ace-QSLHjJ4aPCRpMOfEVJbb5HNgBcEAAwQKrDt15wBwqISUmayZPLWSnaqDmROrh5eOr76gUYm0uYoEYqx1FaMANwQAISoxRFl3rp+AYbBpjJI4Va5ypRqWJTFZRVWVcl6-gZB4kA)

### 💻 Code

```ts
for (let [x = 'a' in {}] of [[]]) console.log(x)
for (let {x = 'a' in {}} of [{}]) console.log(x)

for (let [x = 'a' in {}] in { '': 0 }) console.log(x)
for (let {x = 'a' in {}} in { '': 0 }) console.log(x)

for (let [x = 'a' in {}] = []; !x; x = !x) console.log(x)
for (let {x = 'a' in {}} = {}; !x; x = !x) console.log(x)
```

### 🙁 Actual behavior

When run, this code should print `false` six times. Each `false` is the value of `x` which has been default-initialized.

### 🙂 Expected behavior

TypeScript incorrectly generates syntax errors and generates the following invalid JavaScript output:

```js
"use strict";
for (let [x = 'a'] in {})
    ;
of[[]];
console.log(x);
for (let { x = 'a', in: {} } of [{}])
    console.log(x);
for (let [x = 'a'] in {})
    ;
 in { '': 0 };
console.log(x);
for (let { x = 'a', in: {} } in { '': 0 })
    console.log(x);
for (let [x = 'a'] in {})
    ;
[];
!x;
x = !x;
console.log(x);
for (let { x = 'a', in: {} } = {}; !x; x = !x)
    console.log(x);
```

This came up because I was using VSCode to look at some JavaScript language tests and it was incorrectly showing syntax errors. I'm reporting this because it doesn't seem ideal that VSCode's JavaScript language support would treat valid JavaScript as invalid, and also because I believe the fix for this is relatively straightforward (probably something to do with `DisallowInContext` in the parser?).

**Comment by MartinJohns** [comment] 2023-06-25 13:49
Sounds like a duplicate of #9978.

**Comment by evanw** [comment] 2023-06-25 14:38
I believe this issue is different because a) TypeScript is incorrectly generating syntax errors in valid JavaScript files in this case but not in #9978 and b) TypeScript generates garbled JavaScript output in this case but not in #9978. I think it's also worth fixing because the fix is pretty trivial:

```patch
diff --git a/src/compiler/parser.ts b/src/compiler/parser.ts
index f49b48bb44..c70bf754d1 100644
--- a/src/compiler/parser.ts
+++ b/src/compiler/parser.ts
@@ -7411,7 +7411,7 @@ namespace Parser {
     function parseObjectBindingPattern(): ObjectBindingPattern {
         const pos = getNodePos();
         parseExpected(SyntaxKind.OpenBraceToken);
-        const elements = parseDelimitedList(ParsingContext.ObjectBindingElements, parseObjectBindingElement);
+        const elements = allowInAnd(() => parseDelimitedList(ParsingContext.ObjectBindingElements, parseObjectBindingElement));
         parseExpected(SyntaxKind.CloseBraceToken);
         return finishNode(factory.createObjectBindingPattern(elements), pos);
     }
@@ -7419,7 +7419,7 @@ namespace Parser {
     function parseArrayBindingPattern(): ArrayBindingPattern {
         const pos = getNodePos();
         parseExpected(SyntaxKind.OpenBracketToken);
-        const elements = parseDelimitedList(ParsingContext.ArrayBindingElements, parseArrayBindingElement);
+        const elements = allowInAnd(() => parseDelimitedList(ParsingContext.ArrayBindingElements, parseArrayBindingElement));
         parseExpected(SyntaxKind.CloseBracketToken);
         return finishNode(factory.createArrayBindingPattern(elements), pos);
     }
```

**Closed** 2023-07-20 19:13 UTC
Labels: Bug, Help Wanted
