### ISSUE TITLE
5.5.0 regression - importHelpers do not work with moduleResolution: bundler

### ISSUE THREAD

**Issue by Knagis** [microsoft/TypeScript#58325] opened 2024-04-26 07:18 UTC
### 🔎 Search Terms

importHelpers
This syntax requires an imported helper but module 'tslib' cannot be found.
TS2354

### 🕗 Version & Regression Information

fails on 5.5.0-beta

- This changed between versions 5.4.5 and 5.5.0

reproduces on 5.5.0-dev.20240425
can't be reproduced on playground as it seems to ignore importHelpers

### ⏯ Playground Link

https://github.com/Knagis/importHelpers-5.5.0

### 💻 Code

tsconfig.json:

```json
{
    "compilerOptions": {
        "importHelpers": true,
        "target": "es2017",
        "module": "ESNext",
        "moduleResolution": "Bundler"
    },
    "include": [
        "./src/**/*",
    ],
}
```

src/index.ts
```ts
export function foo(args: any) {
    const { bar, ...extraArgs } = args;
    return extraArgs;
}
```

### 🙁 Actual behavior

```
node_modules\.bin\tsc -b
src/index.ts:2:21 - error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.

2     const { bar, ...extraArgs } = args;
                      ~~~~~~~~~


Found 1 error.
```

### 🙂 Expected behavior

Code compiles without errors.

**Comment by RyanCavanaugh** [comment] 2024-04-26 16:19
Bisects to #57896

**Comment by andrewbranch** [comment] 2024-05-06 21:30
Duplicate of https://github.com/microsoft/TypeScript/issues/57688

**Closed by andrewbranch** 2024-05-06 21:30 UTC
Labels: Needs Investigation
