### ISSUE TITLE
 please update the pdf docs of "TypeScript Language Specification"  to version 2.1!

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [microsoft/TypeScript#14108] opened 2017-02-16 07:07 UTC
# please update the pdf docs of "TypeScript Language Specification"  to version 2.1!

https://www.typescriptlang.org/index.html

https://github.com/Microsoft/TypeScript/blob/master/doc/TypeScript%20Language%20Specification.pdf?raw=true

https://github.com/Microsoft/TypeScript/blob/master/doc/TypeScript%20Language%20Specification.docx?raw=true
```
Open Source
TypeScript is being developed on GitHub. The TypeScript compiler is implemented in TypeScript and can be used in any JavaScript host.

Read the specification on GitHub or download it as a docx or pdf.

Play with the bits and file bugs.

Join the #typescript Twitter discussion and follow the GitHub project.
```

**Comment by cbfrank** [comment] 2017-03-08 02:44
TypeScript 2.2 is release while the docx and pdf version document is still for 1.8.
https://github.com/Microsoft/TypeScript/blob/master/doc/TypeScript%20Language%20Specification.docx?raw=true
https://github.com/Microsoft/TypeScript/blob/master/doc/TypeScript%20Language%20Specification.pdf?raw=true

Please help to update them. Thanks

**Comment by frankgerhardt** [comment] 2017-06-22 10:24
The TS release is now at version 2.4 and I can't believe that the TS language spec version 1.8 from January 2016 is still the current one. Really no updates to the language spec? So many new features all know already in January 2016? Or undocumented?

Please help to update them. Thanks

**Comment by dicarlo2** [comment] 2018-01-11 22:53
@DanielRosenwasser any updates on this?

**Comment by ShadowManu** [comment] 2018-01-11 22:56
I would like to contribute to this (if possible). Language Spec was my it-will-save-me resource when I wanted to do fancy stuff and wanted to know if the language allows it. Want to keep it that way :)

**Comment by xgqfrms-GitHub** [comment] 2018-01-28 07:27
So, just give it up. I'm just using vanilla js for now.

**Comment by xgqfrms-GitHub** [comment] 2018-01-28 07:29
I can't wait for it anymore!

**Comment by ShadowManu** [comment] 2018-01-28 20:30
It's unfortunate that it couldn't work out for you. However, the issue is still open (AND VERY IMPORTANT FOR THE FUTURE OF TYPESCRIPT!!!).

Could you reopen it? We must keep the awareness of it. Thanks.

**Comment by DanielRosenwasser** [comment] 2018-01-28 22:27
We have a set of updates in flight that we need to get merged in, though as usual many other things have come up. Keep an eye on the Spec label.

**Comment by MartinJohns** [comment] 2018-04-16 12:43
@DanielRosenwasser Any update on this?

**Comment by xgqfrms-GitHub** [comment] 2018-04-16 14:37
just keep it opening.

**Comment by tneward** [comment] 2018-05-08 01:47
Nudge. This really does require some love.

**Comment by RyanCavanaugh** [comment] 2020-07-20 19:32
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.

**Closed by RyanCavanaugh** 2020-07-20 19:32 UTC
Labels: Spec
