### ISSUE TITLE
It is recommended that type assertions work on the variables themselves

### ISSUE THREAD

**Issue by zhbnh9988** [Microsoft/TypeScript#17772] opened 2017-08-14 07:54 UTC
**TypeScript Version:**  2.4.0
```ts
interface I {
    data: string
}
let a: any = {data: 'string'}
a as I
a.da  // Now it should be wrong
a.data  // There should be smart tips here
```
**We want the type assertion to work on the variable itself in the code block**

**Comment by jcalz** [comment] 2017-08-15 02:11
Related to #17760?

**Comment by zhbnh9988** [comment] 2017-08-15 02:49
@jcalz This method is valid
But converted to Javascript,some become redundant
```js
function assert(x) {
    return true;
}
var a = { data: 'string' };
if (!assert(a))
    throw null; // like "a as I"
a.da; // error
a.data; // smart tips galore
```
if expression will always be correct, it becomes an extra code with assert()
I think your ways like:
```ts
interface I {
    data: string
}
let a: any = {data: 'string'}
let b: I = a
```
Both of these methods will generate extra Javascript code

### **Is it possible to have a method that only plays the role of type assertions in the Typescript, without generating extra JavaScript code**

**Comment by RyanCavanaugh** [comment] 2017-08-15 23:45
Duplicate of #10421

**Closed by RyanCavanaugh** 2017-08-15 23:45 UTC
Labels: Duplicate
