### ISSUE TITLE
Allow intersection of return types and multiple type-assertions

### ISSUE THREAD

**Issue by Geordi7** [microsoft/TypeScript#50006] opened 2022-07-22 17:58 UTC
# Suggestion

## 🔍 Search Terms

type assertions
assertions
linear types
affine types

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

On point 1: it may cause existing typescript code to fail to compile, but that would be because an error was found (in the case of the `propagateTypeErasure` option discussed below).

## ⭐ Suggestion

Allow function return types to be intersections of concrete types and multiple type-assertions such that the function can both assert the types of its arguments AND produce a result (currently it is restricted to asserting a single argument's type and returning void OR it can return a value).

> TS can **already** represent type erasure with a type assertion `asserts arg is never`, but when this is used it is very awkward to capture an output from the same function as the return value is required to be `void`.

Also add a compiler option `propagateTypeErasure` to require propagating type erasure to a calling function IF an argument of that function is directly passed into a called function which erases its type.

I have explored this idea in this [Playground](https://www.typescriptlang.org/play?#code/FAehAIAUEECUBVwEYBc4CWAXcB3A9gE4DWAzuJngCYCGAnqBAK4noB2A5uNeAOSsCmAN34EeXEiRGZ0eVuTzgAxrJKMAtvy7hB1ADaN+wYADNGrRdNnlqRfgAoAHmjNFWeHKwCUaahKlkHDDIBYQJwAG8QACpwKJAAXyNw4HBUpRVsQIBecABtJABdAG4UtIcAOl1+DkwACxK061tHTwayyur2OqLwMHBWdEV+AEJgRIYoOEQAJjQAMX5qTEYCTVWARwMSTAm9XXcMVkwRSQsZOTxjcloAB01fSQJLVjIcLFrwPDqRclq2dhIRlM5meTX4AH0KAAeaAAGgAQgA+OzUNBw8DGVhoFFozzgLKI8Dw7xE8AAMnAKL8TzI3HQwSEIjxyUaq2WBDkmJRrTGRmUL2w3By+WKwH523AACN8WDIXgUbCtAS8uVVdRYdMCjzqB0avVehASLU8IxdJRwLVqMItJhbpoRARCBaRCMjH0YAhwABmNE4Ig4agEc34YgAWkDJtYlEBfWNOHAtBNSmockUtUW2G+6TUN3QVTCFBotBQwFtd3AAGUkDLwqj+upJSJ4iUy5oK9Ma3XtgR-s2jGxjgRjNQhuAAMKW1gCXQRUqpbZLfgAfjQ7dhc-IBBTLGedhIqErSBJD384H3QX6jII68ayl0VQsdmP1MwZDq9Iv4QXx1X03i6-GYEzisNMU2nJ80AnMD+BnFk0jZFY5FnRpGm-fhnCjfhjDYfhKHXDdGkwLcXiwc49wPKtn0eV8z2rD8Qh+OCUJQ98SHKNDOzQHhqB4cpVjuJZyPKahPD7ZjUn-IxxPSe9+EfZkCPE9ArjsYZWPYzBFzxOpHXjAR4wAUQIR0CCfNpmMkxpEnGSg5N0QNNHFbB91XJBgCY9IBSUSDJ2nGVQKnGCzI3RRyiI7dSNkcieVQpBhLCvA5nQBxcLMg1wHYPAqGGcAAElkzkNxwH2Dgfg0CRcHeWiQvKO8H0wNK+klahKBy-KjRNM1WB4bBLWtChwEoBRWJCjIzw7HJQrQ8zxviqo9V5CZIEDbAABY0EgR0bmodglnOT4rhEXwVkMEwzGAzkkDsLF6zURsCCo085Hoq8IkA87QWMaZrrQVgGyZNBBDwdBzQ84wrq8Ga+me4IDgYghVXKKVGEzdNk3vf5POOBxsCG-gSG67BXAOOolkWoDPq9H7bvux6aX6C94eQtJweumK0mhxm4avRUU3NLNFD2TH+WxwVdBIBRiZwQF4iAA)

## 📃 Motivating Example

For the purposes of representing a protocol or transformation of values, it would be convenient to hide the transformation in a function such that a value which is passed in can no longer be used, and the value that comes out represents the new protocol state.

```typescript
type S1 = {a: number};
type S2 = {a: string};

function transition(state: S1): S2 & (asserts state is never) {/*...*/}

declare const s1: S1;
const s2 = transition(s1);
// s1 is now 'never' type and cannot be reused
```

It would ALSO be convenient if multiple such assertions could be combined so that perhaps more values could have their types erased.

## 💻 Use Cases

Providing APIs that properly represent the consumption of inputs while still being able to provide an output.

This suggestion has a narrow scope and does not purport to look for newer and deeper soundness or correctness guarantees, while still offering meaningful tools to API designers to more correctly express the behavior of their libraries in the type system.

**Comment by whzx5byb** [comment] 2022-07-23 12:47
Duplicate of https://github.com/microsoft/TypeScript/issues/40562

**Closed** 2022-07-31 18:00 UTC
Labels: Duplicate
