### ISSUE TITLE
Overly strict type narrowing in tuple

### ISSUE THREAD

**Issue by westonpace** [Microsoft/TypeScript#27557] opened 2018-10-04 20:47 UTC
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:**
type narrowing tuple
type inference tuple

**Code**

```ts
const x: [number, number] = [0, 0];
if (x[0] === 0) {
    x[0] = -1;
}
```

**Expected behavior:**
The code should compile.  The above code does compile with `typescript@3.0.3`.

**Actual behavior:**

error TS2322: Type '-1' is not assignable to type '0'.

**Playground Link:** http://www.typescriptlang.org/play/

**Related Issues:**

**Comment by ahejlsberg** [comment] 2018-10-05 17:54
Duplicate of #27412.

**Closed** 2018-10-05 18:30 UTC
Labels: Duplicate
