### ISSUE TITLE
`noUncheckedIndexedAccess` w/ destructuring

### ISSUE THREAD

**Issue by arcanis** [microsoft/TypeScript#56154] opened 2023-10-19 12:43 UTC
### 🔍 Search Terms

noUncheckedIndexedAccess, destructuring

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

The `!` qualifier should be allowed in destructuring patterns:

```ts
const [x!, y!, {z!}!] = someArrayValue;
```

### 📃 Motivating Example

This feature makes migrating a large codebase to `noUncheckedIndexedAccess` easier, as we no longer need to migrate all existing destructuring patterns in one go.

### 💻 Use Cases

We're working to enable `noUncheckedIndexedAccess` on a very large codebase (10k+ files). I wrote a codemod adding the `!` qualifier to existing unchecked accesses, but while it's easy to do this on `foo[expr]` and `foo.prop` nodes, I didn't find a good solution for destructured accesses:

```ts
const [x, y, {z}] = someArrayValue;
```

The following doesn't parse, where it seems it should:

```ts
const [x!, y!, {z!}!] = someArrayValue;
```

**Comment by MartinJohns** [comment] 2023-10-19 13:07
Partially a duplicate of #17390.

**Closed** 2023-10-22 01:28 UTC
Labels: Duplicate
