### ISSUE TITLE
Assertion function must be enforced over flow type inference

### ISSUE THREAD

**Issue by SQReder** [microsoft/TypeScript#36150] opened 2020-01-12 13:03 UTC
**TypeScript Version:**  3.7.2

**Search Terms:**
callback, never, narrow, assert

**Expected behavior:**
1. foo type should be inferred as Foo, as described in the variable declaration
```ts
let foo: Foo | null = null;
/* ... */
if (foo != null) {
  /* foo must be Foo type here */
}
```
Actually, if IIFE used inference behave as expected

```ts
let foo: Foo | null = null;

(function () { foo = {} })()

if (foo != null) {
  /* foo is of type Foo here */
}
```

2. Assertion function must be preferred over flow type inference

**Actual behavior:**
`foo` type inferred as `never` and even assertion does not change it

**Related Issues:**
no

**Code**
```ts
function assertNonEmpty<T>(value: T | null | undefined): asserts value is T {
    if (value == null) {
        throw new Error("Should not be null or undefined");
    }
}

function absurd<T extends never>(value: T): asserts value is never { };

type AssertEqual<A, B> = A extends B ? B extends A ? true : never : never;

function runCallback(cb: () => void) { cb() };

type Foo = { __TYPE__?: any };

let foo: Foo | null = null;

runCallback(() => foo = {});

if (foo != null) {
    const shouldBeInferredAsFoo: AssertEqual<typeof foo, Foo> = true;

    assertNonEmpty<{}>(foo);

    const mustBeFoo: AssertEqual<typeof foo, Foo> = true;

    absurd(foo); // foo actually is never
} else {
    const nullish: AssertEqual<typeof foo, null> = true;
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function assertNonEmpty(value) {
    if (value == null) {
        throw new Error("Should not be null or undefined");
    }
}
function absurd(value) { }
;
function runCallback(cb) { cb(); }
;
let foo = null;
runCallback(() => foo = {});
if (foo != null) {
    const shouldBeInferredAsFoo = true;
    assertNonEmpty(foo);
    const mustBeFoo = true;
    absurd(foo); // foo actually is never
}
else {
    const nullish = true;
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=29&pc=2#code/GYVwdgxgLglg9mABAQwM6oKYCcoDkECiAtgA5QCeAPACoB8AFAG7IA2IGAXItYgD6JgQLFn0TgAJhmAwwGcQEouaTDlSJmbDIhhqeAbwBQiY9uCImrdogC81gUJbzEhk68RQAFljgB3ARj8CLG8segAiAGUPOCFxATgoRAAjLUFhRDgsMTBJaVlxMPkAbiMTAF8DCoNQSFgEFCTUECxxGkQMAA8oDBy1WUZsBg12LmpFFHRsKDVhrR1-Aay9RDKSgwoSLQBBSZwCAEcQVkotgBpEACFaG0Qt9q6e8TULxAB+S-vu3tu39ywrLj9bCIQEYRZrGrQeBIf5gADCrBYSWQEAA1vQIEkuPQnNZrow4DAFM5EJicSs1hstAAxOBwG7LAD6jOoAE0AAoEZmvJRgcgUgwGFgYRLAOlcWn0-hpER2GVrWEI4TItH0cl4xBi+l2PRlYqCmBmehaxAAQjlDicLhMEAQqESqGisQuGAAkmBgNgsHIdpKuDsVFADkcWJQqXAzFrzpLrnYoP8MGtXMopvgwMQyFRdQwtfrSsZbWB7YgiCB7S6-bddkHDsdw5G6dG6bG-uwkyZkI1muJjXTiogAPQDzV0lDQEMsfnzIFYSrtFiYZz50l2xIynQef3V4N18ibCMjuDnGUt+NtypAA)

**Comment by MartinJohns** [comment] 2020-01-12 15:24
Duplicate of #9998 and #26914 (you run into both issues).

**Comment by nmain100** [comment] 2020-01-15 15:51
The very first example given is explained well in https://github.com/microsoft/TypeScript/issues/31734.  In short, `foo` is pre-narrowed to `null` only because typescript saw you assign null to it.

**Comment by SQReder** [comment] 2020-01-15 15:59
Ok, I've replaced null with undefined, remove the assignment and it begins to work as expected.
[Playground](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABAQwM6oKYCcoDkECiAtgA5QCeAPACoB8AFAG7IA2IGAXItYgD6JgQLFn0TgAJhmAwwGcQEouaTDlSJmbDIhhqeAbwBQiY9uCImrdogC81gUJbzEhk68RQAFljgB3ARj8CLG8segAiAGUPOCFxATgoRAAjLUFhRDgsMTBJaVlxMPkAbiMTAF8DCoNQSFgEFCTUECxxGkQMAA8oDBy1WUZsBg12LmpFFHRsKDVhrR1-Aay9RDKSgwoSLQBBSZwCAEcQVkotgBpEACFaG0Qt9q6e8TULxAB+S-vu3tu39ywrLj9bCIQEYRZrGrQeBIf5gADCrBYSWQEAA1vQIEkuPQnNZrow4DAFM5EJicSs1hstAAxOBwG7LAD6jOoAE0AAoEZmvJRgcgUgwGFgYRLAOlcWn0-gSKQyORrWEI4TItH0cl4xBi+l2PRlYqCmBmehaxAAQjsMrycicLhMEAQqESqGisQuGAAkmBgNgsHIdpKuDsVFADkcWJQqXAzFrzpLrnYoP8MGtXMopvgwMQyFRdQwtfrSsZ7WBHYgiCBHW6A7ddiHDsdI9G6bG6fG-uwSmV2ixMM5C6SHYk0iwdB5A7XQw3yJso5rm9lcnLxG3Ex3KkA)

**Closed** 2020-01-17 18:00 UTC
Labels: Duplicate
