### ISSUE TITLE
\u{61} is a valid variable name in JS but not in TS

### ISSUE THREAD

**Issue by Jack-Works** [Microsoft/TypeScript#20250] opened 2017-11-24 14:00 UTC
**TypeScript Version:**  2.6.1

**Code**

```ts
var \u{61} = 1
```

**Expected behavior:**
Transpile it into `var \u{61} = 1`
![image](https://user-images.githubusercontent.com/5390719/33213504-c888492a-d162-11e7-8aec-d58d7f478312.png)
(In Firefox)

**Actual behaviour:**
![image](https://user-images.githubusercontent.com/5390719/33213526-e1585986-d162-11e7-9d43-f0cac48f9f3f.png)

**Comment by sanex3339** [comment] 2017-11-24 16:19
It's a valid variable name for es6

**Comment by mhegazy** [comment] 2017-11-27 19:41
Duplicate of https://github.com/Microsoft/TypeScript/issues/5291

**Closed** 2017-12-12 18:21 UTC
Labels: Duplicate
