### ISSUE TITLE
Renaming property in interface is not reflected in Pick

### ISSUE THREAD

**Issue by ackvf** [microsoft/TypeScript#37767] opened 2020-04-03 11:12 UTC
**TypeScript Version:**  3.9.0-dev on my local machine
But online repro only uses 3.6.2 due to web ide limitations

**Search Terms:**
interface property name refactoring rename

**Code**

###### before:
```ts
import * as React from "react";
import "./styles.css";

interface Abc {
  abc: boolean // <- rename abc here
  def: boolean
}

const Abcdef: React.FC<Abc> = ({ abc, def }) => <div></div>
const Abc: React.FC<Pick<Abc, 'abc'>> = ({ abc }) => <div></div>


export default function App() {
  const abc = true
  const def = true
  return (
    <div className="App">
      <Abcdef abc={abc} def={def}/>
      <Abc abc={abc}/>
    </div>
  );
}

```

###### after:
```ts
interface Abc {
  xyz: boolean // <- rename abc here
  def: boolean
}

const Abcdef: React.FC<Abc> = ({ xyz: abc, def }) => <div></div>
const Abc: React.FC<Pick<Abc, 'abc'>> = ({ xyz: abc }) => <div></div> // <- errors


export default function App() {
  const abc = true
  const def = true
  return (
    <div className="App">
      <Abcdef xyz={abc} def={def}/>
      <Abc xyz={abc}/>
    </div>
  );
}
```

**Expected behavior:**
Expected is that renaming the `abc` property to `xyz` rename all references to the same interface.
###### expected:
```ts
const Abc: React.FC<Pick<Abc, 'xyz'>> = ({ xyz: abc }) => <div></div> // <- no errors
```

**Actual behavior:**
Does not modify the string key in `Pick`.

**Playground Link:** 
https://codesandbox.io/s/type-refactor-frzrx
**Related Issues:**

**Comment by IllusionMH** [comment] 2020-04-03 13:44
Duplicate of #30263

**Closed** 2020-04-05 18:00 UTC
Labels: Duplicate

**Comment by ackvf** [comment] 2020-04-07 14:07
Can we rename literals when the type is simple enough to avoid ambiguity?
