### ISSUE TITLE
String negative number as index produces wrong declaration

### ISSUE THREAD

**Issue by christianalfoni** [microsoft/TypeScript#38133] opened 2020-04-23 04:32 UTC
**TypeScript Version:**  3.8.3

**Search Terms:** decleration, object, index, negative number

**Code**

```ts
export const rotate = {
  "-180": "-180deg",
  "-90": "-90deg",
  "-45": "-45deg",
  "0": "0",
  "45": "45deg",
  "90": "90deg",
  "180": "180deg",
};
```

**Expected behavior:**

Should produce the following decleration:

```ts
export declare const rotate: {
    "-180": string;
    "-90": string;
    "-45": string;
    0: string;
    45: string;
    90: string;
    180: string;
};
```

**Actual behavior:**

Missing quotes, causing errors in the declaration

```ts
export declare const rotate: {
    -180: string;
    -90: string;
    -45: string;
    0: string;
    45: string;
    90: string;
    180: string;
};
```

**Comment by a-tarasyuk** [comment] 2020-04-23 08:00
It seems duplicate of the issue https://github.com/microsoft/TypeScript/issues/37292
The fix for the negative numbers was added in this PR https://github.com/microsoft/TypeScript/pull/37936 (https://github.com/microsoft/TypeScript/issues/37866)

cc @RyanCavanaugh

**Comment by nmain** [comment] 2020-04-23 12:04
Works in nightly: [Playground Link](https://www.typescriptlang.org/v2/en/play?ts=3.9.0-dev.20200422#code/KYDwDg9gTgLgBAYwgOwM7yhGBDGw4C8cA3gLABQccARALQCMAHAAzUBcNDLAJsAObUANBSp0AnKw7jmvAcMqcALAFZ2S5bKEiaknVoXUVawxv77RE4xM3zRTXdXs2KAXwDcQA)

The issue template does ask you to try in nightly before reporting a bug 😃

**Comment by christianalfoni** [comment] 2020-04-23 12:12
Great to hear it is fixed! 😄 

Sorry, but I did not understand that this playground was different than the one on Typescript website? Cause that one only shows the JS output. I see this other Playground shows everything, is this some special playground?

**Comment by nmain** [comment] 2020-04-23 12:30
Ahh yes, that's the beta version of the next playground.  Eventually we all will have the power!

**Closed** 2020-04-26 18:00 UTC
Labels: Duplicate
