### ISSUE TITLE
Class ambient declaration should not require redeclaring interface methods

### ISSUE THREAD

**Issue by niagr** [Microsoft/TypeScript#6266] opened 2015-12-27 18:13 UTC
``` typescript
interface IFoo {
    func (str: string): number;
}

declare class CFoo implements IFoo {
    func2 (): void;
}
```
> error TS2420: Class 'CFoo' incorrectly implements interface 'IFoo'.
> Property 'func' is missing in type 'CFoo'.

Since this is just a declaration, we shouldn't have to manually redeclare all implemented methods, this should be implied by declaring that the class implements the interface. We are simply declaring that this class exists and it implements said interface and additionally defines these methods. The requirement for the class to implement those methods should only apply to the actual class definition.

**Comment by vladima** [comment] 2015-12-28 18:18
duplicate of #5468

**Closed** 2015-12-28 18:22 UTC
Labels: Duplicate
