### ISSUE TITLE
Provide a SortedMap<T> collection type as part of the language. 

### ISSUE THREAD

**Issue by grapevinegizmos** [microsoft/TypeScript#39724] opened 2020-07-24 03:03 UTC
## Search Terms
'Sorted Map' 'Sorted Collection' 'Ordered Collection'

## Suggestion

Introduce a type of ordered, Map-type object which supports the ability the consumer to define an arbitrary order of elements within the collection _and to provide a persist-able index key_ that enables map items to be stored in a nosql db in a manner that does not require rewriting of multiple documents fields in order to retrieve the map in the order last defined by the user.

## Use Cases

When working on applications that contain multiple documents whose order is independent of the actual contents of the documents and where objects or groups of object may be moved within the collection in random ways, it can become tedious to develop a persistence strategy that requires _only the documents whose order has changed to_ be rewritten back to the db.  Consider the representation of budget where each of 1,000 accounts represented by documents of 100kb needs to be presented in a particular order.  How to avoid having to update 500 documents with a new sort key when the user inserts a single account int he middle of the collection?  Coming up with strategy for designating sort keys that can accommodate multiple insertions and documents moves within the documents collection can be painful and time consuming. 

All kinds of 'lists of things' that users interact with depend on an arbitrary sort order depending on the whim of a user, particularly tools that enable user to create documents of various types.  It always seemed to take more code than it should to be able to maintain a user defined sort order for a list, and to enable users to move items or groups of items so I ended up writing a SortedMap<T> type object which provided methods like:
  `getAt(index : number)`    
  `insertAfter(id : string)`
  `moveItem(fromPosition: index, toPosition: index)`
the `sortedMap.list` property returns an array of all the items in the currently defined sort order.
SortedMap<T> also provides a SortItem<T> object from which the user can simply set the sort order relative to another item, and it is immediately repositioned relative in the list relative to the specified position.  Nevertheless there was still the persistence problem -- how to define a sort key that won't have to be updated when other items are added or moved within the collection.

the SortedMap concept manages that internally by calculating a string  sort key that is derived from adjacent sort keys.  The .masterIndex property returned for each item in the collection solves the persistence problem with key that doesn't require mutation except when a document is inserted or moved within a collection.    (That is, the masterIndex for surrounding items need not change as a result of multiple insertions or deletions, even if say, 5000 items are inserted between two existing adjacent items.  This means that only new items or items who's position has been changed need to be updated on the backend.   

## Examples

Assume a class `Recipe`, which has a property `Ingredients` which is a `SortedMap<Ingredient>`

You would add ingredients to the recipe by calling `myRecipe.ingredients.add(myIngredient)`
You would get an array of Ingredients in the proper order by calling `myRecipe.list`
So assume you insert 4 ingredients into the Recipe, `[eggs, salt, flour, water]`
Those 4 elements are assigned a masterIndex like `[AAAAA, AAAAC, AAAAE, AAAAG], 
and persisted to the backend.
Then the user wants to insert two more ingredients before water -- sugar, and butter;
She would call `recipe.ingredients.insertAfter(2, sugar)
And perhaps then `recipe.ingredients.insertAfterId(sugar.id, butter)` 
The list of masterIndexes would now be `[AAAAA,AAAAC,AAAAD,AAAAD2,AAAAE,AAAAG]`
The masterIndices of the list are available by calling `recipe.ingredients.sortList` which the returns the list supported the SortItem interface, which provides the methods .masterIndex and .index from which the  computed masterIndex can be obtained.   Using the masterIndex as the sort key would then require only that the two new added elements would have to be persisted, since ther previously written documents are unchanged.  

If this is of any interest to the team, I have written such an object SortMap<T> supported by SortItem<T> and would be happy to share details if this sort of enhancement to the collection objects provided out of the box to Typescript developers is desired.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x ?] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
           (I'm not 100% sure what "library functionality" means)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-07-24 07:52
> [x] This feature would agree with the rest of TypeScript's Design Goals.

It would be against the non-goal 6. And this is a (smaller) duplicate of #30827.

**Comment by RyanCavanaugh** [comment] 2020-07-24 14:54
> This isn't a runtime feature (e.g. **library functionality**

**Closed by RyanCavanaugh** 2020-07-24 14:54 UTC
Labels: Out of Scope, Suggestion
