### ISSUE TITLE
Using conditional typing to check for `extends null` does not seem to work correctly

### ISSUE THREAD

**Issue by not-mike-smith** [microsoft/TypeScript#29627] opened 2019-01-28 21:27 UTC
**TypeScript Version:**  3.3.0-dev.201xxxxx

**Search Terms:**
Domain: Conditional Types
extends null

**Code**
```ts
type CannotBeNull<T> = {
    readonly [P in keyof T]: T[P] extends NonNullable<T[P]> ? true : false;
};

type DoesntCheckNull<T> = {
    readonly [P in keyof T]: T[P] extends null ? false : true;
};

type MyData = {
	name: string,
	age: number,
	hasChild: boolean,
	childAge: null | number,
	childName: null | string
};

type DataWhichArentNull = CannotBeNull<MyData>;
type DataAreAllTrue = DoesntCheckNull<MyData>;
```

**Expected behavior:**
The `DoesntCheckNull<T>` should have the same result as `DataWhichArentNull<T>` because it re-uses the logic in `NonNullable<T>`

i.e. `DataWhichAreAllTrue` should look like: 
```ts
{
	name: true,
	age: true,
	hasChild: true,
	childAge: false,
	childName: false,
}
```

**Actual behavior:**
`DataWhichAreAllTrue` actually looks like:
```ts
{
	name: true,
	age: true,
	hasChild: true,
	childAge: true,
	childName: true,
}
```

**Playground Link:**
[playground](https://www.typescriptlang.org/play/#src=type%20RequiredVariable%3CT%3E%20%3D%20%7B%0D%0A%09value%3A%20null%20%7C%20T%2C%0D%0A%09readonly%20_isRequired%3A%20true%0D%0A%7D%3B%0D%0A%0D%0Atype%20OptionalVariable%3CT%3E%20%3D%20%7B%0D%0A%09value%3A%20null%20%7C%20T%2C%0D%0A%09readonly%20_isRequired%3A%20false%0D%0A%7D%3B%0D%0A%0D%0Aconst%20required%20%3D%20%3CT%3E(initialValue%3A%20null%20%7C%20T%20%3D%20null)%3A%20RequiredVariable%3CT%3E%20%3D%3E%20%7B%0D%0A%09return%20%7B%0D%0A%09%09value%3A%20initialValue%2C%0D%0A%09%09_isRequired%3A%20true%0D%0A%09%7D%3B%0D%0A%7D%3B%0D%0A%0D%0Aconst%20optional%20%3D%20%3CT%3E(initialValue%3A%20null%20%7C%20T%20%3D%20null)%3A%20OptionalVariable%3Cnull%20%7C%20T%3E%20%3D%3E%20%7B%0D%0A%09return%20%7B%0D%0A%09%09value%3A%20initialValue%2C%0D%0A%09%09_isRequired%3A%20false%0D%0A%09%7D%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20Proto%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20readonly%20%5BP%20in%20keyof%20T%5D%3A%20T%5BP%5D%20extends%20NonNullable%3CT%5BP%5D%3E%20%3F%20RequiredVariable%3CT%5BP%5D%3E%20%3A%20OptionalVariable%3CT%5BP%5D%3E%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20FailsProto%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20readonly%20%5BP%20in%20keyof%20T%5D%3A%20T%5BP%5D%20extends%20null%20%3F%20OptionalVariable%3CT%5BP%5D%3E%20%3A%20RequiredVariable%3CT%5BP%5D%3E%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20MyData%20%3D%20%7B%0D%0A%09name%3A%20string%2C%0D%0A%09age%3A%20number%2C%0D%0A%09hasChild%3A%20boolean%2C%0D%0A%09childAge%3A%20null%20%7C%20number%2C%0D%0A%09childName%3A%20null%20%7C%20string%0D%0A%7D%3B%0D%0A%0D%0Atype%20ProtoData%20%3D%20Proto%3CMyData%3E%3B%0D%0Atype%20FailedProtoData%20%3D%20FailsProto%3CMyData%3E%3B%0D%0A%0D%0Aconst%20protoData%20%3D%20()%3A%20ProtoData%20%3D%3E%20%7B%0D%0A%09return%20%7B%0D%0A%09%09name%3A%20required%3Cstring%3E()%2C%0D%0A%09%09age%3A%20required%3Cnumber%3E()%2C%0D%0A%09%09hasChild%3A%20required%3Cboolean%3E()%2C%0D%0A%09%09childAge%3A%20optional%3Cnumber%3E()%2C%0D%0A%09%09childName%3A%20optional%3Cstring%3E()%0D%0A%09%7D%3B%0D%0A%7D%3B%0D%0A%0D%0Aconst%20failedProtoData%20%3D%20()%3A%20FailedProtoData%20%3D%3E%20%7B%0D%0A%09return%20%7B%0D%0A%09%09name%3A%20required%3Cstring%3E()%2C%0D%0A%09%09age%3A%20required%3Cnumber%3E()%2C%0D%0A%09%09hasChild%3A%20required%3Cboolean%3E()%2C%0D%0A%09%09childAge%3A%20optional%3Cnumber%3E()%2C%20%2F%2F%20error!%0D%0A%09%09childName%3A%20optional%3Cstring%3E()%20%2F%2F%20error!%0D%0A%09%7D%3B%0D%0A%7D%3B%0D%0A) **N.B.** turn on `--strictNullChecks` flag in Options

**Related Issues:**
Possibly related to [25413](https://github.com/Microsoft/TypeScript/issues/25413).
I thought it was related to [23843](https://github.com/Microsoft/TypeScript/issues/23843), but that was fixed in a PR that was merged 19 days ago, but I could reproduce this issue even when using typescript@next.

**Comment by jack-williams** [comment] 2019-01-28 21:42
You have flipped the branches in `DoesntCheckNull`, but you have not flipped the condition itself. Try:
```ts
type DoesntCheckNull<T> = {
    readonly [P in keyof T]: null extends T[P] ? false : true;
};
```

**Comment by smithmb-code** [comment] 2019-01-28 21:51
@jack-williams, that works! I have no idea why.  I don't understand why `(null | T)` doesn't extend `null` but is extended by null.  Especially since the implementation of `NonNullable<T>` is 
```ts
type NonNullable<T> = T extends null | undefined ? never : T;
```

**Comment by jack-williams** [comment] 2019-01-28 22:03
For any types `A` and `B`, you can read `A extends B` as that I can _always_ transform an `A` into a `B`.

The type `null` can be read as _always_ having a `null`; the type `null | T` can be read as _sometimes_ having a `null`, _sometimes_ having a `T`.

Always having a `null` implies sometimes having a `null` which is why I can go from `null` to `null | T`. However, sometimes having a `null` does not imply I always have a `null`. In this instance, I cannot _always_ transform `null | T` into `null` because sometimes I might actually have a `T` instead. 

Hope that makes sense!

**Comment by smithmb-code** [comment] 2019-01-28 22:23
Yes, that makes sense, thank you!  Seems like this issue can be closed as working as designed.

I'm still confused why the lib.es5.d.ts file has the `T` on the left side of `extends` instead of the right, but that is not really relevant

**Comment by jack-williams** [comment] 2019-01-28 22:34
@smithmb-code 

> I'm still confused why the lib.es5.d.ts file has the T on the left side of extends instead of the right, but that is not really relevant

When you put the type parameter on the left hand side you get a distributive conditional type. This lets you do filtering on the type, so you can return the non-nullable parts. When you put the type parameter on the right hand side you reduce the conditional type to basically a yes/no answer.

```ts
type NonNullable<T> = T extends null  ? never : T;
type IsNullable<T> = null extends T ? T : never


NonNullable<number | string | null>` // returns number | string, filtering null.
Nullable<number | string | null> // just returns the original type number | string | null
```

**Comment by smithmb-code** [comment] 2019-01-29 01:06
Wow, that all makes sense now. Thanks again for explaining it! I see it explained in the docs now too.

**Closed** 2019-07-13 00:01 UTC
Labels: Question
