### ISSUE TITLE
Compiler crashes with Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by ttv86** [Microsoft/TypeScript#29661] opened 2019-01-31 16:27 UTC
**TypeScript Version:** 
Tested on both 3.2.2 & 3.4.0-dev.20190131

**Search Terms:**
Cannot read property 'kind' of undefined

**Code**
Got reduced the error down to this: When there are 2 files in compilation, and other contains some command, but isn't called, whole TypeScript compiler crashes on an exception.

[HistTest.zip](https://github.com/Microsoft/TypeScript/files/2818092/HistTest.zip)
Extract attached zip file to the directory, run "npm install" and then "webpack"

**Expected behavior:**
Either clear error what went wrong or a successful compilation.

**Actual behavior:**
Webpack throws an exception:
TypeError: Cannot read property 'kind' of undefined
    at Object.isBinaryExpression (c:\....\node_modules\typescript\lib\typescript.js:13389:21)
    at getTypeReferenceTypeWorker (c:\....\node_modules\typescript\lib\typescript.js:38553:51)

**Related Issues:**
#29365 
#28810

**Comment by cancerberoSgx** [comment] 2019-02-27 01:52
Don't know if is the same cause, but I'm having the same error with the following code that, although is weird, tsc is not emitting any diagnostics and it crash without stacktrace (was able to get a stacktrace with ts-node). 

```

class C<S> {
  a={}
  m(s: S) {
    const b = { ...this.a, ...s } = {   }
  }
}
```

```

class C<S> {
  a={}
  m(s: S) {
    const b = { ...this.a, ...s } = {   }
  }
}


```

My two cents, keep it up

**Comment by sheetalkamat** [comment] 2019-03-06 23:32
@cancerberoSgx your issue is actually #29610 already reported and unrelated to this issue. Thanks.

**Comment by sheetalkamat** [comment] 2019-03-07 21:00
Duplicate of  #28810 which already has PR #29339

**Closed by sheetalkamat** 2019-03-07 21:00 UTC
Labels: Bug, Crash
