### ISSUE TITLE
Compiler generates code that uses an undefined variable when decorating properties that have nullable types

### ISSUE THREAD

**Issue by nsnichols** [Microsoft/TypeScript#13955] opened 2017-02-08 19:51 UTC
**TypeScript Version:**  2.1.5 

**Code**
```json
"compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "strictNullChecks": true
}
```

```ts
// In file thing.ts
export class Thing {}
```

```ts
// In file thing-holder.ts

import {Thing} from "./thing";

function decorator() {
    return (...v: any[]) => {};
}
export class ThingHolder {
    @decorator()
    private thing: Thing | null;
}
```
The compiled javascript for ThingHolder looks as follows:

```js
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
function decorator() {
    return function () {
        var v = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            v[_i] = arguments[_i];
        }
    };
}
var ThingHolder = (function () {
    function ThingHolder() {
    }
    return ThingHolder;
}());
__decorate([
    decorator(),
    __metadata("design:type", thing_1.Thing)
], ThingHolder.prototype, "thing", void 0);
exports.ThingHolder = ThingHolder;
```
Notice the reference to ```thing_1``` in the call to ```__decorate``` which should have been the result of a call to ```require("./thing")```.

If I change the type of ```thing``` in ```ThingHolder``` and remove the ```| null```, the call to ```require("./thing")``` gets added as expected.

**Expected behavior:**

```Thing``` gets imported

**Actual behavior:**

```Thing``` is not imported

**Comment by mhegazy** [comment] 2017-02-10 17:35
Duplicate of https://github.com/Microsoft/TypeScript/issues/13449

**Closed** 2017-04-21 16:58 UTC
Labels: Duplicate
