### ISSUE TITLE
Type narrowing for `if (!Array.isArray(a)) {` fails to eliminate a readonly array

### ISSUE THREAD

**Issue by brad4d** [microsoft/TypeScript#57566] opened 2024-02-27 23:01 UTC
### 🔎 Search Terms

"Array.isArray", readonly, narrow, "!Array.isArray"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried from the latest back to 4.9.5, and I reviewed the FAQ for entries about `Array.isArray`, narrowing, and readonly arrays.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMAFAQwFyLCAtgIwFMAnRAH0WMLQBMEAbAT2zyOIG0BdASkQG8AUIkQxgiFAEIAgsWJpGAOhgBnGXMbpuvQcOEQEyuPUIL6cAObpEAakRpuAbiGIAvgLcDQkWAkSXMLAQk5IFsXNrOouLSsvJKqrEa9hG6iPpghsamFla29k7Cbm5AA

### 💻 Code

```ts
function f(a: number | readonly number[]) {
  if (!Array.isArray(a)) {
    console.log(a + a); // error here
  }
}

function g(a: number | number[]) {
  if (!Array.isArray(a)) {
    console.log(a + a); // no error here
  }
}
```

### 🙁 Actual behavior

TypeScript reports "Operator '+' cannot be applied to types 'number | readonly number[]' and 'number | readonly number[]'."

for the `a + a` expression inside

```ts
function f(a: number | readonly number[]) {
  if (!Array.isArray(a)) {
    console.log(a + a); // error here
  }
}
```

### 🙂 Expected behavior

Expect that narrowing variable `a` of type `number | readonly number[]` using `if (!Array.isArray(a)) {` should narrow the type of `a` to `number`.
That is what happens when `a` is of type `number | number[]`.

**Comment by Andarist** [comment] 2024-02-27 23:13
Duplicate of https://github.com/microsoft/TypeScript/issues/53395

This function is defined as `(method) ArrayConstructor.isArray(arg: any): arg is any[]`. A readonly array doesn't satisfy the return type of this predicate (a readonly array has no `.push` method and more) and thus it's not eliminated from the union.

**Closed** 2024-03-01 01:28 UTC
Labels: Duplicate
