### ISSUE TITLE
Feature request: Validation typeguard (validation functions which typecheck inputs or throw errors)

### ISSUE THREAD

**Issue by aneilbaboo** [Microsoft/TypeScript#28257] opened 2018-10-31 18:27 UTC
## Search Terms

typeguard type guard throw error

## Suggestion

Validation functions which throw an error should be able act as typeguards for their inputs. The typeguard asserts that successful completion of the function means that the guarded input has passed a type test. 

## Examples

```typescript
interface Foo {
   bar: string;
}

// Proposed functionality - a validation typeguard
function checkIsFoo(json: any): validates json is Foo {
  if (!json || !isString(json.bar)) {
    throw new Error('Not a Foo');
  }
}
```

Now, we can write code like this:
```typescript
function handleResponse(json: any): string {
   checkIsFoo(json);
   // type system knows json is an instance of Foo here
   return json.bar.toLowerCase();  
}
```

## Use Cases

Throwing an error rather than handling branching logic is sometimes preferable for validation logic. While a standard typeguard can be used with an error-throwing validation function, it produces both redundant and misleading code.

For example,

```typescript
// this would work, but...
function throwErrorIfNotString(s: any): s is string {
   if (!isString(s)) { throw new Error('not a string!'); }
   return true;
}

if (throwErrorIfNotString(s)) { // unnecessary test
   // s is string here
}

// this code is unreachable if s is not a string
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by AnyhowStep** [comment] 2018-10-31 18:45
What I currently do is,

```ts
declare function checkIsFoo (input : any) : string;
json = checkIsFoo(json);
```

Shameless plug for [inspiration,](https://github.com/AnyhowStep/schema-decorator)

But I can see how such a validation would be useful.

**Comment by ajafff** [comment] 2018-10-31 19:03
Duplicate of #17760

**Comment by aneilbaboo** [comment] 2018-10-31 20:51
Thanks for finding that @ajafff. Should we close this?

**Comment by weswigham** [comment] 2018-10-31 23:53
Aye.

**Closed by weswigham** 2018-10-31 23:53 UTC
Labels: Duplicate
