### ISSUE TITLE
Type inference not works inside function while works well on params

### ISSUE THREAD

**Issue by k8w** [microsoft/TypeScript#32436] opened 2019-07-17 02:35 UTC
**TypeScript Version:**  3.5.3

**Search Terms:** Type inference function

**Code**

```ts
interface ValueType {
    a: { a: string };
    b: { b: string };
    c: { c: string };
}

function setValue<T extends keyof ValueType>(key: T, value: ValueType[T]) {
    if (key === 'a') {
        console.log(value.a);
    }
}
```

**Expected behavior:**
Compile succ

**Actual behavior:**
test.ts:9:27 - error TS2339: Property 'a' does not exist on type 'ValueType[T]'.
9         console.log(value.a);

**Playground Link:** 

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/31904

**Comment by Dj-jom2x** [comment] 2019-07-17 07:06
kinda weird how you use interface.

```


interface ValueType {
    a: { a: string };
    b: { b: string };
    c: { c: string };
}

function setValue1(key: any , value:ValueType ) {
    if (key === 'a') {
        console.log(value.a);
    }
}
```

this works

**Comment by Dj-jom2x** [comment] 2019-07-17 07:33
```
interface ValueType {
    a: { a: string };
    b: { b: string };
    c: { c: string };
}

function setProperty<T, K extends keyof T>(obj: T, key: K, value: ValueType) {
    // obj[key] = value;
    if (key === 'a') {
        console.log(value.);
    }
}

```

 i think this is what you are trying to do ? 

![image](https://user-images.githubusercontent.com/12135498/61356083-2d549200-a8a8-11e9-93e6-9189c657dbba.png)

**Comment by jack-williams** [comment] 2019-07-17 14:18
Duplicate of #13995.

**Comment by RyanCavanaugh** [comment] 2019-07-23 16:52
This is a correct error. A legal call to this function is
```ts
setValue<"a" | "b">("a", { b: "" } );
```

**Closed by RyanCavanaugh** 2019-07-23 16:52 UTC
Labels: Working as Intended

**Comment by k8w** [comment] 2019-07-24 15:41
@RyanCavanaugh @Dj-jom2x 
`setValue("a", { b: "" });` is not a legal call.

It would get error as expect
> error TS2345: Argument of type '{ b: string; }' is not assignable to parameter of type '{ a: string; }'.
  Object literal may only specify known properties, and 'b' does not exist in type '{ a: string; }'.

What I try to achieve is to let `key` and `value` match.

The issue is:
1. Type inference works well on function call
2. But it do not works inside the function
