### ISSUE TITLE
Allow index signature parameter type to be String Literal Type and enum member.

### ISSUE THREAD

**Issue by RainingChain** [Microsoft/TypeScript#8921] opened 2016-06-01 15:07 UTC
At the moment, index signature parameter type must be string or number.
Now that Typescript supports String literal types, it would be great if it could be used for index signature parameter type as well.

For example:

	type MyString = "a" | "b" | "c";

	var MyMap:{[id:MyString] : number} = {};
	MyMap["a"] = 1; // valid
	MyMap["asd"] = 2;	//invalid

--- 

It would be also useful if it could also work with Enums. For example:

	enum MyEnum {
		a = <any>"a",
		b = <any>"b",
		c = <any>"c",
		d = <any>"d",
	}

	var MyMap:{[id:MyEnum] : number} = {};
	MyMap[MyEnum.a] = 1; // valid
	MyMap["asd"] = 2;	//invalid

	var MyMap:{[id:MyEnum] : number} = {
		[MyEnum.a]:1,	// valid
		"asdas":2,	//invalid
	}

**Comment by Arnavion** [comment] 2016-06-02 00:19
Duplicate of #2491 and #5683

**Closed** 2016-06-02 00:21 UTC
