### ISSUE TITLE
ES6 class decoration output means property, method & parameter decorations can not get type information from target

### ISSUE THREAD

**Issue by jamcoupe** [Microsoft/TypeScript#6293] opened 2015-12-30 05:53 UTC
```
function Decoration() {}
function PropertyDecoration(target: any) {
  console.log(target);
}

@Decoration
export class ClassName {

  @PropertyDecoration
  property: string = 'null';
}

```

compiles to: 

```
function Decoration() { }
function PropertyDecoration(target) {
    console.log(target);
}
let ClassName = class {
    constructor() {
        this.property = 'null';
    }
};
```

However this means that the console.log result will be `{}`. Removing the `@Decoration` class decorator outputs: 

```
function PropertyDecoration(target) {
    console.log(target);
}
class ClassName {
    constructor() {
        this.property = 'null';
    }
}
```

with the better console.log result of `ClassName {}`.

**Comment by mhegazy** [comment] 2016-01-05 21:03
looks like a duplicate of #6132

**Closed by mhegazy** 2016-01-05 21:03 UTC
