### ISSUE TITLE
Type not automatically changing after .filter

### ISSUE THREAD

**Issue by git-no** [microsoft/TypeScript#47194] opened 2021-12-19 09:25 UTC
# Bug Report

Type not automatically changing after .filter

### 🔎 Search Terms

`typescript error filter undefinied`

Found 
[issue 20707](https://github.com/microsoft/TypeScript/issues/20707)
[issue 20812](https://github.com/microsoft/TypeScript/issues/20812)

### 🕗 Version & Regression Information

Typescript 4.5.3 and below
ESNext and below

Please keep and fill in the line that best applies:
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?target=99#code/MYewdgzgLgBAtgSwB4FMAmBBATlghgTxgF4YBtAcmiwTAHNyAaAVzDRQDMb0HKpq7yAXRgB6ETCwoITADawQ7GLgDuuBLAAKWEIggoAdLhkyAFLgAO5iPrgWzl4gD4Y7FFGAALACK4oue+YAlMEAUGFiMGDgKDAKMFAeKHAuIMYgyjS0kSjKSjgEEHkxAFZM0PH45jFUmaSCDPGJhLiSMNAIxjAmNXQwAD4wLGycYOiBdSGgkLAQHiCyaABCKADKfJnYeIQkiKiY+fj6nHIoWCYAbk4wlwCEJEMcXGiBk+DlsyBYUABqpxAI4BWcwWyzW-FomwIxHgyHQkMOxygpwuVxuN3OLym5SglRQAGFEsAANZA+YyJardZ0eHQ3Zwg5HDpIs6XIjOADekigTCwYAqVTirJIACIerRhQBfF4hIA)

### 💻 Code

```ts
const mixedArray = ['string',undefined,'string'] // result of await Promise.all(apps.map(app => fetchData(app)))

// none of them following new arrays are just type string[], they are still (string | undefined)[]
const shouldBeStringArray = mixedArray.filter(v => v != undefined)
const shortVersionShouldBeStringArray = mixedArray.filter(v => !!v)
const typeCheckShouldBeStringArray = mixedArray.filter(v => {return typeof v == "string"})
```

### 🙁 Actual behavior

```ts
const mixedArray = ['string',undefined,'string'] // result of await Promise.all(apps.map(app => fetchData(app)))
const shouldBeStringArray = mixedArray.filter(v => v != undefined)
// shouldBeStringArray is type (string | undefined)[]
```

### 🙂 Expected behavior

```ts
const mixedArray = ['string',undefined,'string'] // result of await Promise.all(apps.map(app => fetchData(app)))
const shouldBeStringArray = mixedArray.filter(v => v != undefined)
// shouldBeStringArray type string[]
```

**Comment by MartinJohns** [comment] 2021-12-19 09:33
Duplicate of #20218. You're not passing a type guard function to `filter`.

**Comment by Jamesernator** [comment] 2021-12-19 09:38
In these situations I feel like it would be helpful for TypeScript to infer these functions as typeguards automatically. In particular if we have one of the following callbacks to infer as a typeguard:

```js
v => v != undefined;
v => typeof v === "string"; // and others
v => v instanceof SomeClass;
v => v === "someLiteral"; // and other types
// ideally disriminants as well but this might be harder to statically analyze
v => v.kind === "someKind"
```

**Comment by MartinJohns** [comment] 2021-12-19 09:45
@Jamesernator See #38390.

**Comment by git-no** [comment] 2021-12-19 14:14
> Duplicate of #20218. You're not passing a type guard function to `filter`.

Im doubt that it would work. I do miss your specific solution.

This type guard does not work correct

```ts 
type A = string | undefined
const array: A[] = ['hello', undefined, 'salve'];
const a1 = array.filter((e): e is string => e == undefined);
```

because a1 is type string[] but got no string value, got only undefined.
Conclusion, Typescript has the next error, it does not check the types assigned to a1. There is no warning.

**Comment by git-no** [comment] 2021-12-19 14:34
## SOLUTION

This solution works

```ts
// Create this helper function
function isNotNullOrUndefined<T extends Object>(input: null | undefined | T): input is T {
    return input != null;
}
// This actually determines that result is of type (string|undefined)[]
let correctStringArray = mixedArray.filter(isNotNullOrUndefined);
```

Source / found in [16069](https://github.com/microsoft/TypeScript/issues/16069#issuecomment-369374214)

**Comment by MartinJohns** [comment] 2021-12-20 06:39
> This type guard does not work correct

Type guards are not checked for correctness. You can say the very same about the helper function from your last comment.

**Comment by conartist6** [comment] 2021-12-22 20:50
`iter-tools` contains a bunch of type guards, and is the only library I know of that has:
1. users
2. not guards (which are critical because the types are written differently)
3. the guards you need as of `v7.2.0`, which I just released.

I should probably split this out into a separate `@iter-tools/predicates` package, but I have not done this yet.

**Closed** 2022-01-03 16:40 UTC
Labels: Duplicate
