### ISSUE TITLE
Class private members with decorators should not be marked as unused

### ISSUE THREAD

**Issue by mantou132** [microsoft/TypeScript#59482] opened 2024-07-31 06:24 UTC
### 🔎 Search Terms

class private unused decorators 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.0-dev.20240303#code/GYVwdgxgLglg9mABAU2MZ0AUBKRBvAWAChFEAnZKEMpTANwC5EBDMATwBpEIEpkAPKEwDCAG2YBnCQFlKACzgATACIY4ZZlHXDeAqLgC8APnzFSpHmD6CAdM0WKAkmBixmomAC9kZTKEiwCIiYUHIwEkysbLiEJOYWurbMEBDIUjYA5pQhYRLYOADcZuYAvtjFJcSVRMQQ4lKIAIKmcQACqOhY5XEAxBRgij44LfGWEnCiyDaicBmYAIwATADM3aTV1cRgyADuTThAA

### 💻 Code

```ts
function effect() {
  return (v: any, context: ClassMethodDecoratorContext) => {
    context.addInitializer(function (this: any) {
      context.access.get(this)();
    })
  }
}

class A {
  @effect()
  #render() {
    console.log(123)
  }
}

new A()
```

### 🙁 Actual behavior

`#render` be marked as unused

### 🙂 Expected behavior

`#render` should not be marked as unused

**Comment by MartinJohns** [comment] 2024-07-31 06:30
Duplicate of #13120. Used search terms: `private unused in:title`

**Closed** 2024-08-03 01:30 UTC
Labels: Duplicate
