### ISSUE TITLE
Add typings for PerformanceObserver

### ISSUE THREAD

**Issue by bfrost2893** [Microsoft/TypeScript#25651] opened 2018-07-13 20:35 UTC
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 
* PerformanceObserver
* performance observer

**Code**

```ts
let ob1 = new window.PerformanceObserver(); // property 'PerformanceObserver' does not exist on type 'Window'
```

**Expected behavior:**
`PerformanceObserver` (and residual interfaces) are defined on `Window`.

**Actual behavior:**
Currently, this is only defined in [`lib.webworker.d.ts`](https://github.com/Microsoft/TypeScript/blame/cca2631a90fb414f7c830f2d2895a3b5f0db896f/lib/lib.webworker.d.ts#L1741). `PerformanceObserver` should also be defined on `Window` in `lib.dom.d.ts` as it is not an experimental technology [according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver).

**Playground Link:** http://www.typescriptlang.org/play/#src=let%20ob1%20%3D%20new%20window.PerformanceObserver()%3B

**Comment by mhegazy** [comment] 2018-07-13 22:35
Duplicate of https://github.com/Microsoft/TypeScript/issues/19816

**Closed** 2018-07-25 18:29 UTC
Labels: Duplicate
