### ISSUE TITLE
Issue with keyof passed to a generic with conditional types

### ISSUE THREAD

**Issue by sharshuv-quotient** [microsoft/TypeScript#47159] opened 2021-12-15 13:23 UTC
**EDIT: I wrote this completely wrong, please see comments**

# Bug Report

### 🔎 Search Terms

Issue with keyof passed to a generic with conditional types (Sorry can't think of a better description)

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.5.1#code/GYVwdgxgLglg9mABMAPAcQHwAoAeAuRNASgIG00BdRAUxymrABMBnRUuAIwCtroqB+QogJpEAbwBQiRACdqUEDKQ4A3BIC+EoA)

### 💻 Code

```ts
function f<G>(x: G): [G] extends [object] ? G : G {
  return x;
}
```
or:
```ts
function f<G>(x: G): G extends object ? G : G {
  return x;
}
```

### 🙁 Actual behavior

Fails with the following error:
```
Type 'G' is not assignable to type '[G] extends [object] ? G : G'
```

### 🙂 Expected behavior

G should be assignable to [G] extends [object] ? G : G.

### Additional clues
Without condition it works 

```ts
function f<G>(x: G): G {
  return x;
}
```
With condition that is always true it works:
```ts
function f<G>(x: G): [G] extends [any] ? G : G {
  return x;
}
```
With a condition that is always false it doesn't work:
```ts
function f<G>(x: G): [G] extends [never] ? G : G {
  return x;
}
```

**Comment by MartinJohns** [comment] 2021-12-15 13:44
Sounds like a duplicate of #26933.

**Comment by fatcerberus** [comment] 2021-12-15 14:41
> This is the behavior in every version I tried

Your playground is set to TS 3.5.1.  Using 4.3.5 or higher makes the error go away, so this is apparently already fixed:

* https://www.typescriptlang.org/play?ts=4.5.3#code/GYVwdgxgLglg9mABMAjAHgOID4AUAPALkQwEoiBtDAXUQFM8pawATAZ0XIEMwBPGgfmKIiGRAG8AUIkQAnWlBAykeANwSAvhImhIsBMgBMmXIWJkO1OgyZsOYWgDdaMgUJHips+YuVrNQA

That being said, I have to question why someone would use a conditional type *at all* if they know in advance it will always take the same branch.

Also:
> Issue with keyof passed to a generic with conditional types

There's no `keyof` in any of your examples.

**Comment by sharshuv-quotient** [comment] 2021-12-16 11:45
This is embarrassing. 
I was trying different versions to make sure that this wasn't a regression, then I found out I can simplify the minimal-reproduction even more. Apparently, with the latest version, this is the minimal reproduction of my original problem:
https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiAq4IB4DiA+KBeKBtVAulBAB7AQB2AJgM54D2ARgFYQDGwRA-FKlAFy8A3ACgRAMwCuFDgEt6FKOLToAFCUEBrCCHrjeASkFxEkFVADeIqFABOEYJNuKSogL4igA
```ts
type MyType<G> = [G] extends [object] ? G : G;

function f<G>(x: keyof G): MyType<G> {
  return x;
}
```
Should I create a new issue and close this one or edit this issue accordingly?

**Closed** 2021-12-18 12:00 UTC
Labels: Question
