### ISSUE TITLE
Lookup type on `this` unexpectedly takes `true` branch of conditional type

### ISSUE THREAD

**Issue by thetutlage** [microsoft/TypeScript#37778] opened 2020-04-03 19:21 UTC
- Asked on Gitter
- Tried my best to search existing issues
- Tried questioning my understanding, but still the behavior feels weird to me
- Finally, I am forced to create this issue (though I know, the issues list is too big)

TypeScript Version: `v3.8.3` and `Nightly`
Search Terms: **Generics within class body**, **Generics in class body**

**Code**

```ts
type IsString<T extends any, K extends keyof T> = T[K] extends string ? T[K] : never

class Foo {
  public username!: string
  public age!: number
  public dob!: { [key: string]: any }

  public getStringAttr<T, K extends keyof T>(this: T, key: K): IsString<T, K> {
    return {} as unknown as IsString<T, K>
  }

  public someInternalFunction() {
    this.getStringAttr('dob')
  }
}

new Foo().getStringAttr('dob')
```

The above is just a dummy code to reproduce the issue with minimum effort. 

- The class `Foo` has a method `getStringAttr`, which accepts the name of the class property and returns it back if it is a string, or `never` if it is not a string

**Expected behavior:**

Regardless of where the `getStringAttr` method is called, it should have consistent behavior.

**Actual behavior:**

- Calling `getStringAttr` by creating a new class instance works fine
- Calling `getStringAttr` from a different class method (within the class body) makes it infer incorrect types
- The `getStringAttr('dob')` should return `never` in both cases. But within the class body it returns `string`.
- The `getStringAttr('age')` should return `never` in both cases and it does so.

**Playground Link:** https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=17&pc=31#code/C4TwDgpgBAkgzgZWAJwJYDsDmAeAKlCAD2AnQBM4oBDdEAGigGkDjSKoBrCEAewDMouAHxQAvIIDajALosS5SnBQZMUAPySZUAFxR0EAG4RkAWABQ5gMYAbKnEoAxHjygBvc1ChgArgCNrqJZQ3nDG6FQAthAAhLpKaFgeXn4BQVSYMbro3hG+xkk+-oFQZDy+sW5QElwgccpY0ro0IFAAvuYFKcUZwEgJmACCwCh4DMxE8uw1-IJCABTAABaocLq4DDW6jACUuvB9KqNMIu5mnp7IEMDeyOhurdSU3ugc6DwA7nd2sIj1OOvHJLtCxnZJFIJwHhRGDoEi3KjWBzPSzAVA8dBzbZuJKeJYrAB0PQOWCGKDmAHJSr5ydsgeZgeZ9O8oE4eJjCVdiYNhsgKVSaUA

**Related Issues:** Cannot find any

**Comment by thetutlage** [comment] 2020-04-03 20:42
Not to dictate. But does this really has to be part of `4.0`? I am not sure, how release cycle really works, but there is a `3.9` iteration plan https://github.com/microsoft/TypeScript/issues/37198 and I am happy to contribute, if it can be added to `3.9` vs waiting till August

**Comment by RyanCavanaugh** [comment] 2020-04-03 20:46
We have too many bugs to fix in 3.9 already. If you're capable of fixing this, feel free to, but this is likely a very complex issue.

**Comment by thetutlage** [comment] 2020-04-03 20:54
Okay, makes sense. Just wanted to know. Thanks for quick response 😄

**Comment by jack-williams** [comment] 2020-04-06 14:21
> The getStringAttr('age') should return never in both cases and it does so.

Can you post code for this? I wasn't able to reproduced it.

I'm not sure this is a bug. Inside the method the type parameter `this` is used, and because type parameter constraints are ignored in conditional types, `IsString<this, 'dob'>` remains an unresolved type. Outside the class a concrete type `Foo` is used which can be resolved.

This shows the same behavior, but without the confusion of `this` types.
```ts
function foo<T extends { dob: { [key: string]: any } }, K extends keyof T>(t: T, k: 'dob', w: IsString<T, 'dob'>) {
  w // IsString<T, 'dob'> because the conditional type is unresolved
}

foo(new Foo, "dob", ); // third argument is never
```

**Comment by thetutlage** [comment] 2020-04-08 03:52
I shared the link to the playground already

**Comment by SpringNyan** [comment] 2020-04-08 20:35
```typescript
type Test<T> = T extends never ? 0 : 1;

class Foo {
  str!: string;
  result!: Test<this['str']>;

  foo() {
    return this.result;
  }

  bar(): string {
    return this.result; // Type is '0 | 1'
  }
}

const result = new Foo().foo(); // Type is 1
```

Also hit error which may caused by this issue.

**Comment by weswigham** [comment] 2020-04-08 20:49
@SpringNyan no...? `Test` returns `0` or `1`, neither of which are strings... the error on `bar` there seems perfectly valid.

**Comment by SpringNyan** [comment] 2020-04-09 04:41
@weswigham I means the error should be `Type '1' is not assignable to type 'string'`, but not `'0 | 1'`. 

Another comparison:
```typescript
type Test<T> = T extends never ? 0 : 1;

class Foo {
  str!: string;
  result!: Test<this['str']>;
  testStr!: Test<string>;

  result0(): 0 {
    return this.result; // Type '0 | 1' is not assignable to type '0'.
  }

  result1(): 1 {
    return this.result; // ok, but should be error if the result is inferred as '0 | 1' as above
  }

  testStr0(): 0 {
    return this.testStr; // Type '1' is not assignable to type '0'.
  }

  testStr1(): 1 {
    return this.testStr; // ok
  }
}
```

**Comment by weswigham** [comment] 2020-04-09 07:35
`this['str']` is open ended and generic - it  acknowledges that you could subclass `Foo` with something where the property `str` is `never`.

**Comment by SpringNyan** [comment] 2020-04-09 14:58
@weswigham Thanks for the explanation. I'm now using `type Test<T> = T extends infer U ? U extends never ? 0 : 1 : never;` to workaround this case.

**Comment by thetutlage** [comment] 2020-09-04 11:35
Any change of this getting fixed in the next release 🙂

**Comment by thetutlage** [comment] 2020-11-12 12:08
Checking back to see if it can be prioritised

**Comment by thetutlage** [comment] 2020-12-18 06:44
Still waiting for it 🙂

**Comment by thetutlage** [comment] 2021-02-24 11:25
Did it make its way to 4.2?

**Comment by thetutlage** [comment] 2021-02-24 20:02
@RyanCavanaugh Is there any way to understand how bugs are prioritized? Moving it to next version everything is not really helping.

I know, I should be entitled on an open source project. But after maintaining a few for years, atleast, we can have some conversation to understand the reasoning behind the delay and if you need something on my end to help it move forward

**Comment by RyanCavanaugh** [comment] 2021-02-24 21:31
@thetutlage we fix bugs in milestones as quickly as we can. Sometimes we're not able to get through every bug in a milestone, so it moves to the next milestone. I'm sorry you encountered a delay on this bug but as a team staffed with humans, we're just doing as much as we can while still delivering a few features in each release.

We do not apply a global sorting algorithm to prioritize bugs, but data I look at would be:
 * Is this a regression? No, the behavior dates back to at least 3.3
 * How many users have reported encountering the problem, and over what length of time? In other words, how frequently is the problem encountered? Looks like approximately 1 over the multiple years (?) this behavior has been in the product
 * What's the impact? This looks like a corner case around `this` types since there isn't any other reported manifestation
 * Is a workaround available? I haven't checked, but probably
 * Is this even definitely a bug? It's not super clear to me TBH, but it's likely

So on net it's marginal for this one to be scheduled into a milestone as opposed to in the "eventually fix" backlog. That's my assessment of the priority here.

**Comment by RomainLanz** [comment] 2021-02-24 21:45
Maybe you are not aware of this, but this bug creates an issue in AdonisJS ORM.
Many people are encountering this bug, not only one. We tell them to wait since we created this issue.

Some discussions about it:
- [Cannot call this.related inside a model](https://github.com/adonisjs/core/discussions/1555)
- [Missing relationship intellisense inside model methods](https://github.com/adonisjs/core/discussions/1872)
- [How to access a relationship inside a Model method?](https://github.com/adonisjs/core/discussions/1917)

**Comment by danpospisil** [comment] 2021-03-20 18:48
I am have encountered this issue as well. So I hope it will get fixed soon.

**Comment by thetutlage** [comment] 2021-09-18 03:28
Any chance this will be fixed in 4.5.0?

**Comment by thetutlage** [comment] 2021-11-20 03:28
Hello 👋

Do I have to do anything special to get this fixed. It is a bug and I don't think that a bug should be in demand to get attention

**Comment by manansharma91** [comment] 2021-12-21 03:23
Faced this issue today.

Such a big company like Microsoft is rescheduling a bug for 2 years with no explanation altogether. No wonder why teams (Deno) are slowing moving away from TS

**Comment by thetutlage** [comment] 2022-04-28 11:17
How about moving the milestone to 4.7?

**Comment by RyanCavanaugh** [comment] 2023-02-15 05:39
This seems to be fixed now
```ts
type IsString<T extends any, K extends keyof T> = T[K] extends string ? T[K] : never

class Foo {
  public username!: string
  public age!: number
  public dob!: { [key: string]: any }

  public getStringAttr<T, K extends keyof T>(this: T, key: K): IsString<T, K> {
    return {} as unknown as IsString<T, K>
  }

  public someInternalFunction() {
    let d = this.getStringAttr('dob');
    // d: IsString<this, "dob"> (this is a correct deferral)
  }
}

const d = new Foo().getStringAttr('dob')
```

**Closed by RyanCavanaugh** 2023-02-15 05:39 UTC
Labels: Bug, Rescheduled
