### ISSUE TITLE
Strange error with name's resolving

### ISSUE THREAD

**Issue by ifle** [Microsoft/TypeScript#16893] opened 2017-07-02 19:41 UTC
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)
Strange error that cause in VS Code. I have a folder with 2 files : foo.ts, foo2.ts.
In foo.ts there is a function Foo. The foo2.ts file contain function foo2 that called foo. 
When I open the foo2.ts file only I have uresolved name 'Foo' error. 
If I open the foo.ts file and back to foo2.ts file, the function 'Foo' is resolved as expected

**Code**
foo.ts
```ts
function Foo()
{
	
}
```

foo2.ts
```ts
function Foo2()
{
	Foo();
}

```
**Expected behavior:**
'Foo' function will be resolved
**Actual behavior:**
Error: Cannot find name 'Foo'

**Comment by ikatyang** [comment] 2017-07-04 10:39
You have to either use `import/export` or specify `tsconfig.json` to resolve those names, otherwise they won't know where to find them (they'll know those names once you open that file).

**Comment by ifle** [comment] 2017-07-04 10:52
I haven't any import\export, because these global functions and not a module, these files in one folder. Why VS Code can't resolve names without open them?

**Comment by kitsonk** [comment] 2017-07-04 11:01
What do you have your module format set to?  It should be `none` if you are dealing with a global JS project, which is really questionable these days, but...

Also, these basic type of questions are better asked on Gitter or StackOverflow.

**Comment by ifle** [comment] 2017-07-04 12:50
I agree about using of global JS, but this is legacy project. If that is The names are resolved as expected after adding the empty tsconfig.json

**Comment by rbuckton** [comment] 2017-08-05 06:58
If you do not have a _tsconfig.json_ file in your VS Code workspace, then we only know about:
- Files open in the editor.
- Files referenced via `import` or `export` declarations in files open in the editor.
- Files referenced via `/// <reference path="" />` directives in files open in the editor.

This is the intended behavior. If you need more control over which files are automatically type-checked in your workspace, please consider adding a _tsconfig.json_ file to your workspace.

**Closed by rbuckton** 2017-08-05 06:58 UTC
