### ISSUE TITLE
'index' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

### ISSUE THREAD

**Issue by plantain-00** [microsoft/TypeScript#51659] opened 2022-11-28 10:09 UTC
# Bug Report

### 🔎 Search Terms

implicitly has type 'any'  7022

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221128#code/DYUwLgBAxgFglsAJgJxAOwFwQM5mXNAcwgB8IBBAbQF0IBeCGgKAHd5QIAKMATwAcQAewBm0dinQQAhHQYByXPiJyAlBADeTCNuiC0uCAUQgAHvTEIJaAHSgiYGBAC0EAIxadsS6jTmvSH0ojU2prfysmAF8mJgIwEGRhAEMoEAoND3CfLCpaMkUCQiigA)

### 💻 Code

```ts
let children: string | A[] = []
while (typeof children !== 'string') {
    const index = children.length - 1
    children = children[index].children
}

interface A {
  children: A[] | string
}
```

### 🙁 Actual behavior

`'index' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer`

### 🙂 Expected behavior

No error here

**Comment by MartinJohns** [comment] 2022-11-28 10:17
Duplicate of #43047. The type of `index` depends on the type of `children`, the type of `children` depends on the type of `index` (due to the reassignment).

Just add a type annotation.

**Closed** 2022-11-28 10:22 UTC
