### ISSUE TITLE
Using spread operator allows invalid keys

### ISSUE THREAD

**Issue by jakeleventhal** [microsoft/TypeScript#52783] opened 2023-02-15 19:28 UTC
# Bug Report

### 🔎 Search Terms

spread invalid

### 🕗 Version & Regression Information

 I noticed this on 4.9.4

### 💻 Code

```ts
interface MyType {
  a: number;
  b: string;
}

const x: MyType = {
  a: 2,
  b: 'asdf',
  ...{ c: 2 }
};
```

### 🙁 Actual behavior

There was no error

### 🙂 Expected behavior

I get an error that `c` is not a valid property of `MyType`

**Comment by MartinJohns** [comment] 2023-02-15 22:18
Duplicate of #39998.

**Closed** 2023-02-19 18:00 UTC
Labels: Duplicate
