### ISSUE TITLE
Generics are ignored on function(this: Foo<A>).

### ISSUE THREAD

**Issue by Jomik** [Microsoft/TypeScript#23173] opened 2018-04-05 17:40 UTC
**TypeScript Version:**  2.8.1 & 2.9.0-dev-20180405

**Search Terms:** this generic function restriction

**Code**

```ts
class Bar<A> {
  foo(this: Bar<string>): void {}
}

new Bar<number>().foo();
```

**Expected behavior:**
Type error when trying to call `foo` with `this` having type `Bar<number>`.

**Actual behavior:**
`foo` is callable on `Bar<number>` and throws no error.

**Playground Link:** http://www.typescriptlang.org/play/#src=class%20Bar%3CA%3E%20%7B%0D%0A%20%20foo(this%3A%20Bar%3Cstring%3E)%3A%20void%20%7B%7D%0D%0A%7D%0D%0A%0D%0Anew%20Bar%3Cnumber%3E().foo()%3B

**Related Issues:**

**Comment by RyanCavanaugh** [comment] 2018-04-05 17:47
Thank you for logging an issue! This is a common source of confusion. The compiler is acting according to the intended behavior. You can [read a longer explanation in the FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ). Only bugs with concrete future engineering work are left open on the tracker, so I'll close this. If you have specific follow-up questions, you can still post them in this issue.

**Closed by RyanCavanaugh** 2018-04-05 17:47 UTC

**Comment by Jomik** [comment] 2018-04-05 18:06
Ah! Okay. So my issue is in reality that 
```ts
class Bar<A> {
  constructor(f: Bar<A>[]) {}
  foo(this: Bar<string>): void {}
}

new Bar<number>().foo();
```
Doesn't "use" `A`.
Adding `private v: A;` fixes this, but is a bit obsolete.

Luckily I suppose this is fixed as I add more code! Thanks a lot.
