### ISSUE TITLE
Suggestion: Add support for symbol type in index signatures

### ISSUE THREAD

**Issue by achugaev93** [Microsoft/TypeScript#18569] opened 2017-09-19 07:57 UTC
I tried to define such interface:

```typescript
export interface IPropertyAccess {
    [key: PropertyKey]: any;
}
```

Where `PropertyKey` has such declaration:

```typescript
declare type PropertyKey = string | number | symbol;
```

But I got compile-time error: _TS1023: An index signature parameter type must be 'string' or 'number'_.

I think it's inconsistent behavior and index signature param type MUST support `symbol` as well.

**Comment by mhegazy** [comment] 2017-09-19 17:22
Duplicate of https://github.com/Microsoft/TypeScript/issues/1863

**Comment by achugaev93** [comment] 2017-09-19 17:42
@mhegazy , I read that topic. Latest comment was in 2016. Since that it seems nothing happened.
Can you please explain, why I can'y use `symbol` as index key type?

**Comment by mhegazy** [comment] 2017-09-19 18:55
> why I can'y use symbol as index key type?

cause it was not implemented.  #1863 tracks adding that, and it is marked as "Accepting PRs" so PRs to add this support are welcomed.

**Comment by mhegazy** [comment] 2017-10-04 16:10
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-04 16:10 UTC
Labels: Duplicate
