### ISSUE TITLE
Narrowing with switch/case not working

### ISSUE THREAD

**Issue by iduuck** [microsoft/TypeScript#51132] opened 2022-10-10 16:50 UTC
# Bug Report

### 🔎 Search Terms

- Narrowing
- Inferring
- Generic Types

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about narrowing

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDeVSQFxQEQEMtQF8AoNaAIQWVXAkywCN9iSaoBLAOwDMIAnAGQjBgfAPIBXYGEkAeQcL5QIADxEcAJgGdYUAD5QyAPkryRvANpZSWALpLVEDdtz4A-FA7iAtvUWZTfJbWdipqWtiMUO6awLycAOZQmBwQAG58REQqYAD2vMBQAMY5HDGovDilXHleAOpswAAWAMoA7g2FjQDCOJrQiHJCZvZh2nD6RgAURFCzUAA2Q3z+S7wANDNznNLAmDFxHPFEAJSYnDwCqxJSsgG8xvDGSJuzmu3AnVCTiwq8AHSkY7IF5zWaFXrQFzoEGg0G8ITiXgcKBgHC8PoASQ4wEm20kaygAEYAAzHADcMLm4L6ESw0NhDKg8OAiOReOAAJyzViCUm5Mps3UEC4OHE812AthzNZIOIxGyeQKxVKBVilU01V4dQajQxXAAovMaQM7iNHOFxgZDNNQT8zCtfhtQey9jzDicztw+HdrjtBr8Hk8QWwuF87XwAax4NHsHggc9GUyEUiUWjMdjcRwdgSSfzQQQlEboCGw6tI5AEDGGFh45LpSn2ZzuQd4nyKfnMnDkxwiAQgA)

### 💻 Code

```ts
type A = { type: "a" }
type B = { type: "b" }

type inferLetterOutput<Letter extends A | B> = Letter["type"] extends "a" ? number : Letter["type"] extends "b" ? string : never

export const transformWithSwitchCase = <Letter extends A | B>(
    letter: Letter,
    input: string
): inferLetterOutput<Letter> => {
    switch (letter.type) {
        case "a":
            return parseInt(input, 10);
        case "b":
            return input.toString();
        default:
            return
    }
}
```

### 🙁 Actual behavior

I am sure this should be possible to be typed correctly. I am trying to infer/narrow the return type of a function, but once the function is returning something, I am not able to type this correctly.

### 🙂 Expected behavior

I am expecting the function "return" statements to be correctly typed and not raising an error.

**Comment by MartinJohns** [comment] 2022-10-10 17:39
This is a design limitation. Resolving of conditional types that involve unbound type arguments is deferred. Within the body of your function the compiler has **no clue** what type `inferLetterOutput<Letter>` is, because at this point it doesn't know what type `Letter` is, so it can't verify the value you return matches.

You should use overloads in this case instead.

**Comment by jcalz** [comment] 2022-10-10 18:31
duplicate of #33912

**Comment by fatcerberus** [comment] 2022-10-10 20:29
There's also the fact that, in general, narrowing the type of the argument `letter` doesn't tell you anything about the type parameter `Letter`.

**Closed** 2022-10-13 18:00 UTC
Labels: Duplicate
