### ISSUE TITLE
missing used props type in generated d.ts file when generate typs from JavaScript

### ISSUE THREAD

**Issue by Rvtea** [microsoft/TypeScript#60088] opened 2024-09-27 22:33 UTC
### 🔎 Search Terms

dts infer type missing

### 🕗 Version & Regression Information

- This changed between versions 5.5.4 and 5.6.2

### 💻 Code
Below is a minimal reproduce of JavaScript code.

```js
export class ViewPluginBase {
  constructor({ name, customUiKeyMap = undefined } = {}) {
    this.viewName = [null, undefined, ''].includes(name) ? this.constructor.name : name;
    this.customUiKeyMap = customUiKeyMap;
  }
}

export class ViewPlugin extends ViewPluginBase {
  constructor({
    name = 'ViewPlugin',
    customUiKeyMap,
    useDefaultClass = true // may change name for easier understand meaning
  } = {}) {
    super({ name, customUiKeyMap });  // <- customUiKeyMap is being used here but generated type lost it
    
    if (useDefaultClass) {
      console.log("print here to simulate useDefaultClass is used");
    }
  }
}
```

### 🙁 Actual behavior

I use `npx -p typescript tsc src/**/*.js src/*.js --declaration --allowJs --emitDeclarationOnly --strictNullChecks --outDir dist` to generate d.ts for me in one of my JavaScript lib and the behavior changed recently when I found the type changed between 5.5.4 and 5.6.2 . I do not find any clue yet so I raised a bug, but if you find it expected changes per the upgrade, feel free to mark it as more reasonable type, thx! 

Now 5.6.2 generated type is 
```ts
export declare class ViewPluginBase {
    constructor({ name, customUiKeyMap }?: {
        customUiKeyMap?: undefined;
    });
}
export declare class ViewPlugin extends ViewPluginBase {
    constructor({ name, customUiKeyMap, useDefaultClass }?: {
        name?: string | undefined;
        useDefaultClass?: boolean | undefined;
    });
}
```

### 🙂 Expected behavior

```ts
export declare class ViewPluginBase {
    constructor({ name, customUiKeyMap }?: {
        name: any;
        customUiKeyMap?: undefined;
    });
}
export declare class ViewPlugin extends ViewPluginBase {
    constructor({ name, customUiKeyMap, useDefaultClass }?: {
        name?: string | undefined;
        customUiKeyMap: any;
        useDefaultClass?: boolean | undefined;
    });
}
```

### 5.5 playground result
![image](https://github.com/user-attachments/assets/ef5f2126-ddc5-4999-abe1-a53862f087fb)

link: https://www.typescriptlang.org/play/?ts=5.5.4#code/KYDwDg9gTgLgBAYwDYEMDOa4DUCWwDuACkgK4DmOAdgELrBwDeAUHIhJWjFCQjNABQM4lFAFtgAGkQlOEUQFUcAaWABPALIowcALxwSlACbAAZlWCG4AX12MrASkYtWcGAAscaAHQA3PPgA5MXo9AG1KEiQkKQNjM0oLKQByJIBdLypkEmM0fhFxRwB+Vw9vBHZObl5oL3z6AC5hYIBuZ1Z3Ty8EGT4FZTVNbT1u2T6VDS1W1ismGaZQSFhEVAxsf2JyKjhQGGAjTFwCDYoaOidWco4uHj4oQTam8Vskw6JSE6SJB5HexXHBr4ufRoYAAEVMKEiMAAwitMHprvQAPRIuCiFCqRBuFCUMj0OpwEzQbboPBQfRGYBQTg4yziHFUMjOGx6BgOc4uNAkMBUwSPSTSUZ-AZaaz2KYuB44ExwfgyMEQqGw9BoRzMIEXCoQJDALxICBkfgAIjAUCo8DcVPofDgaBwokiKF2wIVJkhSBhcLgnhdhiN4oeM2msyAA

### 5.6 playground result
![image](https://github.com/user-attachments/assets/5684f7cc-e061-41c7-b90b-37ffcb58e80d)

link: https://www.typescriptlang.org/play/?ts=5.6.2#code/KYDwDg9gTgLgBAYwDYEMDOa4DUCWwDuACkgK4DmOAdgELrBwDeAUHIhJWjFCQjNABQM4lFAFtgAGkQlOEUQFUcAaWABPALIowcALxwSlACbAAZlWCG4AX12MrASkYtWcGAAscaAHQA3PPgA5MXo9AG1KEiQkKQNjM0oLKQByJIBdLypkEmM0fhFxRwB+Vw9vBHZObl5oL3z6AC5hYIBuZ1Z3Ty8EGT4FZTVNbT1u2T6VDS1W1ismGaZQSFhEVAxsf2JyKjhQGGAjTFwCDYoaOidWco4uHj4oQTam8Vskw6JSE6SJB5HexXHBr4ufRoYAAEVMKEiMAAwitMHprvQAPRIuCiFCqRBuFCUMj0OpwEzQbboPBQfRGYBQTg4yziHFUMjOGx6BgOc4uNAkMBUwSPSTSUZ-AZaaz2KYuB44ExwfgyMEQqGw9BoRzMIEXCoQJDALxICBkfgAIjAUCo8DcVPofDgaBwokiKF2wIVJkhSBhcLgnhdhiN4oeM2msyAA

**Comment by Andarist** [comment] 2024-09-28 07:28
Duplicate of https://github.com/microsoft/TypeScript/issues/59920 , see the @ahejlsberg's recent comment [there](https://github.com/microsoft/TypeScript/issues/59920#issuecomment-2379478733)

**Closed as completed** 2024-09-30 01:48 UTC
Labels: Duplicate
