### ISSUE TITLE
Restrict destructuring to satisfy the destructured object's values

### ISSUE THREAD

**Issue by KATT** [microsoft/TypeScript#50674] opened 2022-09-07 16:29 UTC
# Suggestion

It seems reasonable to me that any destructured property needs to [satisfy](https://github.com/microsoft/TypeScript/issues/47920) the base type instead of extending it.

**tl;dr:** I would like this two examples fail in the same way:

```tsx
interface MyProps {
  color?: "green" | "blue";
}


// 😻 "Type '"red"' is not assignable to type '"green" | "blue"'.(2322)"
function MyComponent1({ color = 'red'}: MyProps)  {
  return null;
}


// 😿 Doesn't validate that 'red' is a bad option
function MyComponent2(props: MyProps)  {
  const {color = 'red'} = props;
  return null;
}
```

[Playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgLIE8AKUD2AHAZ2QG8BYAKGWQRwBscoB+ALmQCIBzKCCEN5AD7sARrQCuENgG4KAXwoLyAeiXJAvBuBuPfYAVdHhQByNtwAmbA8mBEQOMMjgECwDiDiiUYHMjB7Dnbrz8QmyiEuYAdAAUAEwAzNHRAJRsFDBiIAhgwDggaOgAwjgAtng5vGAAjJHE1HQMyAC8yAamBrKsGNj4BIlUZJTI3GBiULkgYrS0MuTy5Ioq6oD8e6npmdm5GIUlZeDRkXi4hB1Yhz19FFQLACI4EAQgBnYAbnC0wCZwkN4AFp-NrZYiHBkMI4CZkPgsjkLrUQAQ7MQaPQoI1-hATG1UQdutMqEMRmMJlM5EA)

## 🔍 Search Terms

restrict destructuring function declaration satisfies

## ✅ 

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

- Restrict destructuring to satisfy the base option.
- This could be a `strict`-mode thing.

```ts
interface Options {
  color?: "green" | "blue";
}

const opts: Options = {}

const {
  // @ts-expect-error this should fail because "red" doesn't exist in `Options['color']`
  color = 'red'
} = opts;
```

[Playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgPIAczAPYgM7IDeAsAFDLILYA22UA-AFzIBEA5lBBCC8gD6sARtQCuEFgG4yAXzJkq+MMmyY8zDFlwEAvEVml5WpSXLIA9GeQABMHgC0EAB7oICMA6hQ6yMAAtgBHi+2CLUACbI8MDUyIKucCJ4KCycYbxh2BB4IADkSk4BSqDIAAYaOPgA2jlUtFA5ALolZBS13ro5qTkyyLoqthJAA)

## 📃 Motivating Example

The motivation of this issue is that we had a bug in a React-component because we had a typo in our default value.

In this React-component, I would never want a size `large`, that's a typo. 

```tsx
interface MyProps {
  size?: "sm" | "md" | "lg";
}

function MyComponent(props: MyProps)  {
  const {size = 'large'} = props;
  
  // imagine some code here
  return null;
}
```

[Playground link](https://www.typescriptlang.org/play?#code/LAKAlgdgLgpgTgMwIYGMYAICyBPACnAewAcBndAb1HXRLAC8YB+ALnQCISBbN9AH3c4ATHvzYAbAOZsA3KAC+oUAgCuEFFDAEIWbAGECnIlpjQAFEUKlWOfMRIBKapRDUUWklAq0G6ALzoAcjEkOAkYALk-dAs7WRd0KnQAeiT0ME4kCUgMEgMMN0EMAAt4GES4GChlOG0IZTExOLkgA)

## 💻 Use Cases

Anywhere you define an options object and want to set a default.

## Extra notes

- I know this isn't a bug - it's a feature request
- I raised this as I had a bug in my application which I think the TypeScript compiler could have prevented
- Maybe the `satisfies` operator helps here?
- I know the two examples are not _exactly_ equivalent, I'm using the above example to showcase that most developers would likely expect the same behavior in the two cases
- `const { color = 'red' }: MyProps = props;` is a bit weird and would be nice if it wasn't needed, especially not in `strict`-mode

**Comment by MartinJohns** [comment] 2022-09-07 16:33
Duplicate of #43795. Used search terms: `destructure default in:title`

**Comment by fatcerberus** [comment] 2022-09-07 16:35
The two cases are not equivalent - the function parameter destructuring has an explicit type annotation.  You can do the same for variable declarations:

```ts
// should error now
const { color = 'red' }: MyProps = props;
```

**Comment by KATT** [comment] 2022-09-07 16:38
- I know this isn't a bug - it's a feature request
- I know the two examples are not _exactly_ equivalent, I'm using the above example to showcase that most developers would likely expect the same behavior in the two cases
- `const { color = 'red' }: MyProps = props;` is frankly weird & not what I would ever _want_, especially not in `strict`-mode

**Comment by MartinJohns** [comment] 2022-09-07 16:44
> I'm using the above example to showcase that most developers would likely expect the same behavior in the two cases

At the same time you have developers that expect this to work as syntax sugar for `const color = props.color === undefined ? 'red' : props.color;`, which wouldn't be the case anymore with your suggestion.

> especially not in `strict`-mode

The `strict`-mode is about soundness. There's nothing unsound about this, the type is correctly inferred.

Your suggestion would break existing code for little gain; or require yet-another-feature-flag.

**Comment by fatcerberus** [comment] 2022-09-07 16:46
> `const { color = 'red' }: MyProps = props;` is frankly weird & not what I would ever want, especially not in strict-mode

It’s no weirder than what you’re doing in the function parameter case - assigning a type to a destructuring pattern.  By leaving it out you’re asking the compiler to infer the types from what you’ve written.  Note that in cases where function parameters can be inferred, you can leave the `MyProps` annotation off of the function case too, and you get the same inference behavior (demonstrated in #43795).

At any rate, this is working as intended per https://github.com/microsoft/TypeScript/issues/43795#issuecomment-825887773 so the suggestion is not likely to be taken.

**Comment by KATT** [comment] 2022-09-07 17:01
I only raised this because it resulted in a bug in my application which I think the TypeScript could have prevented.

To me, [and to a bunch of other experienced TypeScript-developers](https://twitter.com/alexdotjs/status/1567534426237575168), this behaviour was not intuitive. 

Let's stop going in circles and let the TS-team decide if they like this or not, your comments won't convince me to close this.

**Comment by fatcerberus** [comment] 2022-09-07 17:15
That’s fine, but for the record the comment I linked to above is from a primary TS maintainer.

**Comment by andrewbranch** [comment] 2022-09-09 23:13
Hah, I’m glad you linked the tweet, because I was baffled by how this had 12 👍. Anyone with more than 1k followers who tweets an issue has to accept that from that point on, issue reactions are going to be a meaningless signal to me—or at least, I’m going to weight them to correct for the unnatural publicity 😄.

But yeah, just because #43795 was pitched as a bug and this is pitched as a feature request doesn’t make it not a duplicate.

```ts
function MyComponent(props: MyProps)  {
  const {size = 'large'} = props;
```

FWIW, it seems to me that there’s a weak link in whatever you passed `size` to.

**Closed** 2022-09-12 18:00 UTC
Labels: Duplicate
