### ISSUE TITLE
JAVA output

### ISSUE THREAD

**Issue by tailot** [microsoft/TypeScript#35100] opened 2019-11-14 10:16 UTC
## Search Terms
JAVA output

## Suggestion
Enable tsc to generate JAVA code

## Use Cases
I want to learn one programming language to do everything.

## Examples
I’ve met a group of people who are afraid of technology and change and are anchored in their tools. With this change they will probably become more kind to the world.

## Checklist
* [ ] Statements
* [ ] Conditional blocks
* [ ] Loop blocks
* [ ] Boolean expressions
* [ ] Variables
* [ ] Primitive Types
* [ ] Arithmetic expressions
* [ ] Literals
* [ ] Methods
* [ ] String
* [ ] Objects
* [ ] Packages
* [ ] Arrays
* [ ] Mathematical functions
* [ ] Large numbers
* [ ] Random numbers
* [ ] Unicode
* [ ] Comments
* [ ] Keywords
* [ ] Coding conventions
* [ ] Lambda expressions

**Comment by MartinJohns** [comment] 2019-11-14 12:34
You should check out the [TypeScript Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by tailot** [comment] 2019-11-14 13:42
@MartinJohns I have read Design Goals, I believe that this feature could change the world. When typescript will be native on browsers everything will seem clearer.

**Comment by jcalz** [comment] 2019-11-14 13:57
Duplicate of #9202, #29095.

**Closed** 2019-11-14 14:59 UTC
Labels: Out of Scope, Suggestion
