### ISSUE TITLE
Object is possibly null when referenced in array methods but not in for loop

### ISSUE THREAD

**Issue by greg-finley** [microsoft/TypeScript#43397] opened 2021-03-26 19:12 UTC
# Bug Report

### 🔎 Search Terms

array methods

### 🕗 Version & Regression Information

- This is the behavior in Nightly

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIC2wA5gBZgBCEAcgK4A2DAXDsgNoDWEAnqwM5gooEgF1WdEJxDoA7iGQBfZAB9kIRgwDcuRblwxJCMMHQKARnABeAChiZWGdABpkg4SBL8BQke1EAlDj4yMAwyDYAhPboAHTE5FS0mkFQEGB0UArwDPwQOiEA9IXICOiEAA7ADBD8IfZQETVgocgAvMgADFqtADxuvp78sTWeYGQ9wADUU0F4BARlIPzoNSPoJHaY8aQU1PRM7O4i-OzAooE6BHpFJdBQ6I0AKgDKAEwArADMAIysAPLmABWEGMoX4yAq6H4-GA5gYPGQAHINEwkSFjkNYg0AKKIMg2GyYkhBNoAPmCC1KZhWawYGy2cQSe2Sh2JlxCigCOkUQA)

### 💻 Code

```ts
interface Foo {
  mightBeNull: { [key: string]: unknown } | null;
}

function baz(foo: Foo, strings: string[]) {
  if (!foo.mightBeNull) return false;

  // compiles
  for (let i = 0; i < strings.length; i++) {
    console.log(foo.mightBeNull[strings[i]]);
  }

  // error TS2531: Object is possibly 'null'
  strings.forEach((string) => {
    console.log(foo.mightBeNull[string]);
  });
}
```

### 🙁 Actual behavior

In the code above, early return if `foo.mightBeNull` is null. `foo.mightBeNull` is still marked as possibly null when called within an array method (forEach, map, some, etc.) but not within a for loop.
 
### 🙂 Expected behavior

Compile, as `foo.mightBeNull` cannot be null at this place in the code.

**Comment by MartinJohns** [comment] 2021-03-26 19:22
Duplicate of #9998.

**Comment by greg-finley** [comment] 2021-03-26 19:32
Thanks for the link. If I do mutate this key in a for loop, it correctly complains about nullability again:

```
  // now errors
  for (let i = 0; i < strings.length; i++) {
    console.log(foo.mightBeNull[strings[i]]);
    foo.mightBeNull = null;
  }
  ```
  
  I could imagine something similar in array methods.

**Comment by greg-finley** [comment] 2021-03-26 19:37
Maybe it's the opposite problem, because nulling it out in a function call within a for loop is not safe. This compiles but throws a run-time error.

```
interface Foo {
  mightBeNull: { [key: string]: unknown } | null;
}

function baz(foo: Foo, strings: string[]) {
  if (!foo.mightBeNull) return false;

  // does not error
  for (let i = 0; i < strings.length; i++) {
    console.log(foo.mightBeNull[strings[i]]);
    nullOutFoo(foo);
  }

  return true;
}

function nullOutFoo (foo: Foo) {
  foo.mightBeNull = null;
}

baz({mightBeNull: {a: true, b: true}}, ['a', 'b'])
```

**Comment by MartinJohns** [comment] 2021-03-26 19:41
The problem is described in #9998. The narrowing is lost within closures, you need to either narrow in your closure or use the non-null assertion operator. Or alternative store the narrowed value in a const variable.

**Closed** 2021-03-27 06:08 UTC
Labels: Duplicate
