### ISSUE TITLE
Control flow analysis and never type

### ISSUE THREAD

**Issue by impworks** [microsoft/TypeScript#11098] opened 2016-09-23 15:53 UTC
**TypeScript Version:**  2.0.0

**Code**

``` ts
function test(x:string) {
    var y = typeof x === "function" ? [x] : x;
}
```

**Expected behavior:**
Type of `y` is `string`. A warning is issued for a condition that is always false.

**Actual behavior:** 
Type of `y` is `never[] | string`.

**Comment by kitsonk** [comment] 2016-09-23 15:57
Essentially dupe of #10991 when CFA produces confusing errors.

**Closed** 2019-07-23 04:03 UTC
Labels: Working as Intended
