### ISSUE TITLE
Why isn't "a.length > 0" an type-guard that help me Narrowing?

### ISSUE THREAD

**Issue by ttttttssssss** [microsoft/TypeScript#46638] opened 2021-11-02 07:21 UTC
# Bug Report

### 🔎 Search Terms
array length narrowing

### 🕗 Version & Regression Information

- This is a crash
- This changed versions is 4.4.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgLhAIwFYFNhQNoF0YC8MeAsAFBwB0ADgK4QAWAFAN4C+AlOQO4MCWAG3QwmVIWADmUBjAB8MAAwcYLcjBihIsFKkLwaIaky5l1miCCGUBICUx2UoIAMpQATn0km2QA)

### 💻 Code

```ts
const a:object[] = []
/**
* It can be 'push' 0 or multiple times.
* a[] is an array of arbitrary length
*/
a.push({});a.push({});a.push({});a.push({});a.push({});
while (a.length > 0) {
  // obj: object | undefined
  const obj = a.pop()
  // Object is possibly 'undefined'.
  console.log(obj.toString)
}
```

### 🙁 Actual behavior
**Object is possibly 'undefined'.** 

I've obviously determined that the `a []` length is greater than zero, which means `pop` cannot return `undefined`.

But `TS` is still telling me that obj might be `undefined`.I had to use`const obj = a.pop()!` to make right.

Is this a bug or is ts not implemented？

If not implemented, Why didn't you do it(I'm very interested in it) ?

![image](https://user-images.githubusercontent.com/58020640/139802551-97b2f5f4-0a8b-477b-bb0c-da79f48a333e.png)
### 🙂 Expected behavior

`obj` type is not included undefined

****

**Comment by MartinJohns** [comment] 2021-11-02 07:46
Duplicate of #30406. Used search terms: `array pop in:title`

**Closed** 2021-11-02 08:01 UTC
