### ISSUE TITLE
Generated JS code's style is not correct.

### ISSUE THREAD

**Issue by lygstate** [Microsoft/TypeScript#3646] opened 2015-06-26 06:57 UTC
The generated code for
```
type NameOrNameArray = string | string[];

function createName(name) {
    if (typeof name === "string") {
        return name;
    } else if (typeof name == 'number') {
        return name.toString();
    } else {
        return name.join(" ");
    } 
}

var greetingMessage = `Greetings, ${createName(3213) }`;
alert(greetingMessage);
```

is 
```
function createName(name) {
    if (typeof name === "string") {
        return name;
    }
    else if (typeof name == 'number') {
        return name.toString();
    }
    else {
        return name.join(" ");
    }
}
```

the else after } should not newline.

**Comment by DanielRosenwasser** [comment] 2015-06-26 13:25
Hi there @lygstate, this is actually a duplicate of #3297. The decision we came to there is that one can use a JS formatter to get output that conforms to different users' standads.

**Closed by DanielRosenwasser** 2015-06-26 13:25 UTC
