### ISSUE TITLE
Add a keyword for skipping optional type parameters in generics (to fallback to the default definition)

### ISSUE THREAD

**Issue by parzhitsky** [microsoft/TypeScript#60550] opened 2024-11-21 12:56 UTC
### 🔍 Search Terms

unset type parameter default

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

The suggestion is to add a keyword that says "I don't need to specify this optional type parameter, I am only passing by to a later one, please resolve to whatever the fallbace default type

### 📃 Motivating Example

Considering the case:

```ts
import express from 'express'

interface CreateUserParams {
    name: string
    age: number
}

export type CreateUserRequest = express.Request<
    Record<string, string>, // ❌ unrelated, but there's no way if skipping this
    any,                    // ❌ could've specified it, but decided to not bother
    CreateUserParams        // ✅ actually what is needed and relevant
>
```

_[Try it](https://tsplay.dev/wE6MZN)_.

All of the type parameters of `express.Request` are optional. In the case when I only need to specify the third parameter, there is no way of skipping the first two. Instead, I have to go to the definition, see what the fallback type is, and provide the fallback type here explicitly; this gets words if the fallback type isn't exported.

Sometimes this can be mitigated by a better design, sometimes not.

The suggestion is to add a keyword (e.g., CSS's `unset` or SQL's `default`) that would do the lookup itself:

```ts
export type CreateUserRequest = express.Request<unset, unset, CreateUserParams>
```

This might be a breaking change for codebases where `unset` is an existing identifier. If that's a concern, consider `?` as the keyword:

```ts
export type CreateUserRequest = express.Request<?, ?, CreateUserParams>
```

### 💻 Use Cases

1. _What do you want to use this for?_ – Skipping optional parameters in generics defined by upstream libraries.
2. _What shortcomings exist with current approaches?_ – The need to lookup the definition.
3. _What workarounds are you using in the meantime?_ – I look the definition up.

**Comment by MartinJohns** [comment] 2024-11-21 12:58
Duplicate of #26242.

**Closed** 2024-11-21 13:04 UTC
