### ISSUE TITLE
TS doesn't narrow arrays in a union

### ISSUE THREAD

**Issue by ShubhamCanMakeCommit** [microsoft/TypeScript#45301] opened 2021-08-03 02:36 UTC
# Bug Report
### 🔎 Search Terms
narrowing array union

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBACg9gSwHbCgXigbwFBSgDwC4okBXAWwCMIAnAblyhELKtoYF9tRJYBDBDXRQA2q2o0ANCQoSAutm7hoAYThwaAEwDOw+MlQAffoMUAzUkgDGwBHCRQwNAwEYAFH2JqNOgJTFxWhw8BDM3ACJ8cKhkKD5fYLwoGghgUhoHPgA6fAY8DigIABttCES8FLSMuJEABjk8qC4ubAtrW3tHZxQAJg9iGAEaETkoY30UEf8oADdETUTQiKiYzLq5BMY8K3ttOCKILKK4AHMPdZzfRgLi0vKoHaQ9g6PT8-r1q-zsDiA)

### 💻 Code
```ts
type Point = {
  x: number;
  y:number;
}
type Pair = [number, number]

type Coords = Point | Pair

function print1(a: Coords): number{
  if("x" in a){
    return a.x;
  } else{
    return a[0];
  }
}

function print2(a: Pair[] | Point[]): void{
  if("x" in a[0]){
    console.log(a[0].x)
  } else{
    console.log(a[0][0])
  }
}
```

### 🙁 Actual behavior
It should correctly narrow array type as `Point[]` instead of `Point[] | Pair[]` in `print2()`.

### 🙂 Expected behavior
It should have done it because I don't have a mixed type where if `a[0]` is `Point` then `a[1]` could be `Pair` which is what I mean when I do `Point[ ] | Pair[ ]`

[Also this SO link could help to explain.](https://stackoverflow.com/questions/68626400/how-to-type-narrow-array-types-passed-in-functions/68626508#68626508)

**Comment by DanielRosenwasser** [comment] 2021-08-03 18:25
This works correctly if you use TypeScript nightly (or 4.4 beta) and use `--exactOptionalPropertyTypes`.

**Comment by DanielRosenwasser** [comment] 2021-08-03 18:28
Sorry, misread the issue - maybe I'm missing something but [everything seems correctly narrowed in the playground](https://www.typescriptlang.org/play?ts=4.3.5&exactOptionalPropertyTypes=false#code/C4TwDgpgBACg9gSwHbCgXigbwFBSgDwC4okBXAWwCMIAnAblyhGLKtoYF9tRJYBDBDXRQA2q2o0ANCQoSAutm7hoAYThwaAEwDOw+MlQAffoMUAzUkgDGwBHCRQwNAwEYAFH2JqNOgJQtZWixGBDMoNwAifAioZCg+X2C8PBoIYFIaBz4AOnwGPA4oCAAbbWgcZKhU9Mz4kQAGOXyoLi5sC2tbe0dnFAAmD2IYARoROShjfRQx-ygAN0RNJNiwyOjYrIa5RIrk4rTHRBRhPi3GQpKy5bx91DARk7OC7A4gA).

**Comment by fatcerberus** [comment] 2021-08-04 01:58
Maybe OP was expecting `a` itself to be narrowed rather than just `a[0]`?  TypeScript doesn't narrow the containing object when you perform a check on one of its properties except in specific situations.  Thus why we have discriminated unions.

If I'm right, this is effectively a duplicate of #42384.

**Closed** 2021-08-07 18:00 UTC
Labels: Duplicate
