### ISSUE TITLE
Can't deploy from VS2013 (or TeamCity) after TypeScript 1.6 upgrade

### ISSUE THREAD

**Issue by joelmdev** [Microsoft/TypeScript#5248] opened 2015-10-13 23:52 UTC
Today I updated to TypeScript 1.6, and now the `CopyPipelineFiles` task is failing when trying to deploy web applications.

I redirect TypeScript's compiled JavaScript output directory to `scripts\compiled\` in the Web project's settings (via `TypeScriptOutDir` entry in the csproj file) and this has always worked fine up until now. Typescript files are being compiled correctly, and to the correct directory (ie `scripts\compiled\` under the web project directory).

However, the `CopyPipelineFiles` task seems to be getting confused about the root directory of TypeScript files, and now always assumes that it is the root directory of the web project. As a result, it's adding folders to the path that don't exist, for example, after compiling `scripts\foo.ts`, instead of grabbing `scripts\compiled\foo.js` MSBuild is looking for `\scripts\compiled\scripts\foo.js`. I have tried using `$(ProjectDir)` in the output directory, and I've also tried setting the `TypeScriptRootDir` to the appropriate root directory (e.g. `scripts\`) but the problem persists.

The only way I've been able to remedy the situation is to remove the output directory and allow the compiled JavaScript files to be output to the same locations at their TypeScript counterparts.

The following is an example of a real error I've received, where the path of the TypeScript file would be `scripts\account\app.ts`:

> Copying file scripts\compiled\scripts\account\app.js to obj\Release\AspnetCompileMerge\Source\scripts\compiled\scripts\account\app.js failed. Could not find a part of the path 'scripts\compiled\scripts\account\app.js'

This happens on all local machines with Typescript 1.6 installed, as well as our TeamCity build server with 1.6 installed.

**Comment by joelmdev** [comment] 2015-10-13 23:52
Crosspost [here](http://stackoverflow.com/questions/33114436/cant-deploy-from-vs2013-or-teamcity-after-typescript-1-6-upgrade)

**Comment by mhegazy** [comment] 2015-10-14 07:07
We have not made any changes to this part in the targets file in 1.6, I believe all the changes were adding new properties. Can you share a sample project?

**Comment by joelmdev** [comment] 2015-10-14 14:39
https://github.com/joelmdev/TypeScript16PublishProblems

This is a brand new project where I've set the outDir and the rootDir in the csproj file. Same result as the original post. As an aside, rootDir appears to be case sensitive, where outDir is not

**Comment by joelmdev** [comment] 2015-10-14 15:19
I have since uninstalled TS 1.6.2 and 1.6.3 to see if it alleviates the problem, but it does not. I'm not sure if this is indicative of residual changes from 1.6.x or if this problem affects 1.5.x as well and some other update is causing the problem. What I know without a doubt is that I was able to publish my web applications using TypeScript 1.5.3 when specifying the TypeScriptOutDir and now I cannot. I have tried removing TypeScriptRootDir, but the problem persists. I cannot publish web applications at this time without removing the TypeScriptOutDir.

**Comment by mhegazy** [comment] 2015-10-14 23:29
- uninstalling TS1.6.*, 
- verifying no .targets file in C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript and C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\TypeScript, 
- then installing TS1.5.*
should get you back to exactly where you were before the setup.

the only part that interacts with the build process is the .targets file. so if that has not changed, i would say it is not caused by a TS change. it is still possible that there is a bug in the targets that was exposed by a change in a different component.. a log file with `/verbosity:diagnostic` would definitely be helpful.

**Comment by joelmdev** [comment] 2015-10-15 03:51
Since I can't attach files here I'm pushing the log up to the root directory of the same repository from earlier. It's the only addition to the latest commit (/buildlog.txt).

**Comment by awcab** [comment] 2015-10-15 19:49
Same here - no typescript getting deployed after upgrade to 1.6.

**Comment by joelmdev** [comment] 2015-10-15 20:40
@awcab is the application deploying without the compiled Javascript or is the build/deploy failing?

**Comment by awcab** [comment] 2015-10-15 20:43
@joelmdev It's deploying with the javascript.

**Comment by joelmdev** [comment] 2015-10-16 17:00
@awcab that sounds like a different issue. Here, the build is failing to deploy altogether.

**Comment by awcab** [comment] 2015-10-16 17:42
@joelmdev  Sorry, meant to say it's deploying _without_ the javascript.  I guess it is a different issue, but seems maybe related.

**Comment by joelmdev** [comment] 2015-10-19 17:24
@mhegazy was the provided log helpful?

**Comment by joelmdev** [comment] 2015-10-21 16:17
The first time the problem appears in the build log is in the AssignTargetPath task that occurs directly after the TypeScript compiler task completes. I can't figure out why it's not honoring the rootDir that's been specified in the project file. Even without the rootDir being set, this would be incorrect behavior as the computed rootDir would not be the root of the project.

> ...
1>Done executing task "VsTsc". (TaskId:13)
1>Task "AssignTargetPath" (TaskId:14)
1>  Task Parameter:
1>      Files=
1>          C:\Users\Joel\Desktop\delete\TypeScript16PublishProblems\TestingTypeScript16WebDeploy\scripts\compiled\Scripts\typescript\controller1.js
1>                  DestinationRelativePath=C:\Users\Joel\Desktop\delete\TypeScript16PublishProblems\TestingTypeScript16WebDeploy\scripts\compiled\Scripts\typescript\controller1.js
1>          C:\Users\Joel\Desktop\delete\TypeScript16PublishProblems\TestingTypeScript16WebDeploy\scripts\compiled\Scripts\typescript\controller1.js.map
1>                  DestinationRelativePath=C:\Users\Joel\Desktop\delete\TypeScript16PublishProblems\TestingTypeScript16WebDeploy\scripts\compiled\Scripts\typescript\controller1.js.map (TaskId:14)
1>  Task Parameter:RootFolder=C:\Users\Joel\Desktop\delete\TypeScript16PublishProblems\TestingTypeScript16WebDeploy (TaskId:14)
1>Done executing task "AssignTargetPath". (TaskId:14)
...

**Comment by mhegazy** [comment] 2015-10-21 23:35
I started looking at the log then got pulled into a couple of other tasks. looking into it again. i think i see the issue. will report back soon.

**Comment by joelmdev** [comment] 2015-10-23 17:25
I meant to mention that this affects all of my projects across multiple machines, including those that I haven't touched since the TS update that have no rootDir set. I can't deploy anything without the workaround of removing the outDir.

**Comment by mhegazy** [comment] 2015-10-28 05:22
Sorry for the delay. I think i got it working now, there were two issues, both in TypeScript.Tasks.dll. both issues were caused by having to do with handling absolute paths. The issues caused `PreComputeCompileTypeScript` task to not compute the correct output path when rootDir is used.

To work around it for now, update both your rootDir and outDir to be relative instead of absolute. So use:

```XML
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TypeScriptOutDir>Scripts\compiled</TypeScriptOutDir>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <TypeScriptOutDir>Scripts\compiled</TypeScriptOutDir>
  </PropertyGroup>
  <PropertyGroup>
    <TypeScriptRootDir>Scripts\typescript</TypeScriptRootDir>
  </PropertyGroup>
```
instead of:

```XML
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TypeScriptOutDir>$(ProjectDir)scripts\compiled</TypeScriptOutDir>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <TypeScriptOutDir>$(ProjectDir)scripts\compiled</TypeScriptOutDir>
  </PropertyGroup>
  <PropertyGroup>
    <TypeScriptRootDir>$(ProjectDir)Scripts\typescript</TypeScriptRootDir>
  </PropertyGroup>
```

We will try to get this in the next release, but can not promise. will update the issue once the fix has landed in the release branch.

**Comment by mhegazy** [comment] 2015-10-28 05:22
if the work around listed above does not work for you, please let me know.

**Comment by joelmdev** [comment] 2015-10-29 16:51
@mhegazy this seems to work just fine. I thought I'd tried every permutation of relative and absolute paths for both outDir and rootDir, but somehow I missed this one. I really don't know how.

Removing the rootDir does cause the issue I first posted, so I guess if you leave TypeScript.Tasks.dll to its own devices in its current state it calculates the absolute path incorrectly, but if you explicitly set the rootDir to a relative path it bypasses the issue, is that a correct explanation?

**Comment by mhegazy** [comment] 2015-10-30 18:57
Should be in the next public release.

**Closed by mhegazy** 2015-10-30 18:57 UTC
Labels: Bug, Fixed
