### ISSUE TITLE
Find references even when TypeScript sub-projects not yet open

### ISSUE THREAD

**Issue by dcecile** [microsoft/TypeScript#30823] opened 2019-02-19 20:16 UTC
From https://github.com/Microsoft/vscode/issues/65102...

It seems like with a multiple-tsconfig.json setup, VS Code can't find all references. (Even though technically all of them should be "joined" via a root tsconfig.json that uses project references.)

Here's a minimal repro of my setup: https://github.com/dcecile/typescript-references-test

```
common/
  message.ts
  tsconfig.json
server/
  hello.ts
  tsconfig.json
client/
  sharedMain.ts
  tsconfig.json
```

- Both client and server reference the common project
- "Find references" fails to find the references to the common function
- "Rename symbol" also fails to rename the references
- After loading files from the client and server projects, find references works

**Comment by mjbvz** [comment] 2019-04-09 00:18
Confirmed with TypeScript 3.5.0-dev.20190407

**Comment by sheetalkamat** [comment] 2019-04-11 16:40
This is currently known issue in which if the file is not open or declaration maps are not present it cannot find all references in sibling projects. #28261 is wip for this but needs more work before can be merged in since we need to be smart about when to lookup symbol in other projects(as loading projects in most common scenarios is costly and can result in delay when someone does first time find all references)

**Comment by awerlang** [comment] 2019-04-17 01:16
@RyanCavanaugh I believe the `Duplicate` label is a mistake here.

**Comment by hediet** [comment] 2019-05-28 14:04
This blocks us from splitting our code into multiple smaller projects as (consistent!) renaming across the entire codebase is very important to us. We would love to have this feature!

**Comment by bajtos** [comment] 2019-05-31 14:13
>  #28261 is wip for this but needs more work before can be merged in since we need to be smart about when to lookup symbol in other projects(as loading projects in most common scenarios is costly and can result in delay when someone does first time find all references)

Personally, I will happily trade off performance for "Find all references" and "Rename symbol" that actually works.

In https://github.com/strongloop/loopback-next, we have configured TypeScript to treat the entire monorepo as a single project, so that we can use "Find all references" and "Rename symbol". 
We also don't use declaration maps, therefore cross-project imports are resolved against the original TypeScript sources, not via `.d.ts` and `.d.ts.map` files. 

This setup works pretty well for us and I am not aware of any performance or memory limitation when working in VS Code. If the performance of #28261 is similar, then I would happily accept it.

Why we want to migrate from our single-project setup to project references when VS Code experience is good now? The problem is that our build times are super slow. We are building each monorepo package independently, because each package has its own `outDir`, e.g. `packages/{name}/dist`. Because cross-project imports are resolved against the original TypeScript sources, I suspect that the compiler is repeatedly parsing each TypeScript source file again and again for each top-level package depending on it.

Anyhow. Is there a way how to finish #28261 sooner, possibly without performance optimizations and perhaps behind a new feature flag?

**Comment by AnyhowStep** [comment] 2019-06-25 08:41
I currently have a code base that uses composite projects and has **34** sub-projects.

Having to open all 34 sub-projects to "Find all references" is a little tiring =/

**Comment by alextreppass** [comment] 2019-10-08 02:55
Hi, any updates on this? We've recently migrated a very large frontend codebase to sub-projects, and opening files from each before finding references isn't feasible.

**Comment by pablobirukov** [comment] 2019-12-03 17:54
I have a similar problem in a case implementing scenario described in [the project references documentation](https://www.typescriptlang.org/docs/handbook/project-references.html).

There is a root `tsconfig.json`, referencing packages which are a set of composite projects (implementation and tests). In case there is no `tsconfig.json` with non-empty `files` in a package, VS Code won't pick up the config for the files in the package.

https://github.com/pablobirukov/vs-core-project-references

**Closed** 2020-03-04 19:53 UTC
Labels: Experience Enhancement, Suggestion

**Comment by pokey** [comment] 2023-03-02 17:59
For what it's worth, in order to get this to work, we had to add a "solution" [`tsconfig.json`](https://github.com/cursorless-dev/cursorless/blob/pokey/pnpm-workspace/tsconfig.json) at the root of our repo that references all projects, as [recommended in the Typescript handbook](https://www.typescriptlang.org/docs/handbook/project-references.html#overall-structure):

> Another good practice is to have a “solution” tsconfig.json file that simply has [references](https://www.typescriptlang.org/tsconfig#references) to all of your leaf-node projects and sets [files](https://www.typescriptlang.org/tsconfig#files) to an empty array (otherwise the solution file will cause double compilation of [files](https://www.typescriptlang.org/tsconfig#files)). Note that starting with 3.0, it is no longer an error to have an empty files array if you have at least one reference in a tsconfig.json file.

We were able to automate generating this list using [meta-updater](https://github.com/pnpm/meta-updater).  See [our meta-updater config](https://github.com/cursorless-dev/cursorless/blob/fab139fd972a91e17852cc8a00a163980f69b208/packages/meta-updater/index.ts#L40-L52) for more details

**Comment by aliakbarazizi** [comment] 2023-07-04 20:43
I did all, i created a root `tsconfig` with `references`, I set `tsconifg` in all project with `composite: true`  and still I need to open project to use find references.

I found a hack, I added `"files": ["./project1/tsconfig.json", "./project2/tsconfig.json"]` to root `tsconfig` and it seems it force vscode to load all `tsconfig` and its working very well.
