### ISSUE TITLE
Proposal: auto-complete import paths

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#3430] opened 2015-06-09 00:51 UTC
Would be awesome if we could add auto-completion on import paths.

```typescript
import {} from "./" // gives you an auto-complete suggestions
```
```typescript
/// <reference path="./" // gives you an auto-complete suggestions
```

**Comment by danquirk** [comment] 2015-06-09 00:58
Dupe of #188

**Closed by danquirk** 2015-06-09 00:58 UTC
