### ISSUE TITLE
Type guard on generic parameter gives error inside array callback

### ISSUE THREAD

**Issue by SLaks** [microsoft/TypeScript#38376] opened 2020-05-06 22:58 UTC
**TypeScript Version:**  4.0.0-dev.20200505, 3.8.3

**Search Terms:** generic type guard array

**Code**

```ts
function isArrayOf<T>(
    array: unknown[], ctor: {new (...args: never[]): T}): array is T[] {
  return array[0] instanceof ctor;
}

function test<T>(arr: T[]) {
    if (isArrayOf(arr, Date)) {
        arr[0].getDate();
        arr.forEach(d => d.getDate());
    }
}
```

**Expected behavior:**

No compiler errors

**Actual behavior:**

Second call (in `forEach()`) gives `Property 'getDate' does not exist on type 'T'. (2339)`, because `arra` is `T[] & Date[]` and `d` is just `T`.

**Playground Link:** [link](https://www.typescriptlang.org/play/index.html?ts=4.0.0-dev.20200505&ssl=1&ssc=1&pln=11&pc=2#code/GYVwdgxgLglg9mABDAzgQQE4YIYE8DywAPACoB8AFAFCK2LZZ4Bci4A1mHAO5gDaAugBpE0OBhYBvMAFMuiCgDolDAOYoWMgG7SMAgJQsSAXwP1GuZCkQkBiCTUQZpUEBiQMcuXgAZ+yMChQ2JDScMAiUGIA3FRGVFSgkLAIiFDSgaSUHob6dg60MOEUqJiehBQewgAi2Gl6enl0TWa6vgoqzjVpFHoxzXQeCsBiAKLYEAAWFAAmiAC8ZIjT7Z210j29+YhxRkA)

**Comment by jack-williams** [comment] 2020-05-06 23:21
This looks to be the same issue as #11961.

`arr` is an intersection of arrays and `forEach` is selecting the first overload (of type `T`).

Does this work for your scenario?
```ts
function isArrayOf<T,U>(
    array: U[], ctor: {new (...args: never[]): T}): array is (U & T)[] {
  return array[0] instanceof ctor;
}
```

**Comment by RyanCavanaugh** [comment] 2020-05-11 20:41
@weswigham any odds we could improve this?

**Comment by weswigham** [comment] 2020-05-11 20:54
I think @jack-williams 's suggestion is correct here - when you have a `T[] & U[]`, `forEach` implicitly has two overloads, one for `T`, and one for `U`. Changing intersected signature logic isn't quite right, either, since if the signature had multiple parameters, you'd still want to ensure their intra-signature consistency (like an overload list does). So changing the guard to narrow the element type of the array, rather than the array type as a whole, seems more appropriate here.

**Comment by RyanCavanaugh** [comment] 2023-02-15 05:46
Closing as duplicate of #11961

**Closed by RyanCavanaugh** 2023-02-15 05:46 UTC
Labels: Duplicate
