### ISSUE TITLE
Type narrowing over `x` does not reflect in a statement of the format `false && x`

### ISSUE THREAD

**Issue by awalgarg** [microsoft/TypeScript#44156] opened 2021-05-19 00:35 UTC
# Bug Report

### 🔎 Search Terms

type narrowing, object is possibly undefined, false &&

### 🕗 Version & Regression Information

4.3 - nightly

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210518#code/GYVwdgxgLglg9mABMOcCMAKAHgfgFyIDOUATjGAOYCUiA3gFCKIzCIYCEWNDTTJAplBAkwAbkaIAvvQlYAdFDgBlUuQoYqoxAHptycvwmkQ-RADIzieYpVlKGrbv1hDTYAEMANoVMWrC5VV7TR09AHkAIwArfmhmQkQABzhCQhgIzwBPRHAAE35gA1yJAAZzS2tAu3UQp0KXdnpJIA)

### 💻 Code

```ts
function foo1(x?: string) {
  if (!x) {
    return;
  }

  x.toString(); // fine
  true && x.toString(); // fine
  false && x.toString(); // Object is possibly undefined
  0 && x.toString(); // fine!
}
```

### 🙁 Actual behavior

`x` is not narrowed from `undefined | string` to `string` in `false && x.toString()`.

### 🙂 Expected behavior

`x` is narrowed from `undefined | string` to `string` in `false && x.toString()`.

**Comment by MartinJohns** [comment] 2021-05-19 05:47
Most likely a duplicate of #26914.

**Closed** 2021-05-21 18:00 UTC
Labels: Duplicate
