### ISSUE TITLE
`satisfies` alters type inference of some (generically-typed?) variable assignments

### ISSUE THREAD

**Issue by stwlam** [microsoft/TypeScript#56623] opened 2023-11-30 20:35 UTC
### 🔎 Search Terms

satisfies narrows generic assignment

### 🕗 Version & Regression Information

This is the behavior in every version I tried (from 4.9.5), and I reviewed the FAQ for entries about Generics

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.2#code/C4TwDgpgBAChxQLxQEQGMCGwVQD6oBMB7AcxQG4AoNIgOwGcFJh6koBtdLFAGkNJQBdKPSwBLegDMxEVnGDtBVZvQB0Y2mgA2AVwKyAFCgBGYgE4EUASigB6W1FpEERANZA

### 💻 Code

```ts
type Pet = "cat" | "dog";
const pets = ["cat", "dog"] satisfies Pet[];
pets.includes("bird") // not ok
```

### 🙁 Actual behavior

`pets` is of type `Pet[]`

### 🙂 Expected behavior

`pets` is of type `string[]`

**Comment by fatcerberus** [comment] 2023-11-30 20:41
Yes, `satisfies` induces contextual typing, so it can sometimes affect the type of an array or object literal.  If it didn’t, then the above would fail because `string[]` isn’t assignable to `Pet[]`.

**Comment by stwlam** [comment] 2023-11-30 20:48
I suppose the announcement reads a little off, then: perhaps when it's documented it could be clarified further?

> The new `satisfies` operator lets us validate that the type of an expression matches some type, without changing the resulting type of that expression.

**Comment by fatcerberus** [comment] 2023-11-30 20:52
I agree that should be clarified, but to be fair, technically if `pets` is allowed to be widened to `string[]` then it no longer satisfies `Pet[]` right? :wink:

**Comment by stwlam** [comment] 2023-11-30 20:56
I assumed it would confirm that the value is assignable to the `satisfies` type, narrowing as necessary, but then returning the actual type assignment to normal inferencing procedure.

**Comment by jcalz** [comment] 2023-11-30 21:07
Duplicate of #55189… the documentation is indeed misleading here

**Closed** 2023-11-30 21:10 UTC
