### ISSUE TITLE
--outDir is not recognized if --build is used when running tsc

### ISSUE THREAD

**Issue by gh-andre** [microsoft/TypeScript#43557] opened 2021-04-06 18:40 UTC
# Bug Report

If `tsc` is executed with `--build`, supplying `--outDir` fails:
```bash
tsc --build --outDir /var/tmp/my-app tsconfig.myapp.json
```
The error is reported as:
```bash
error TS5072: Unknown build option '--outDir'.
```
### 🔎 Search Terms

"--outDir" "--build"

### 🕗 Version & Regression Information

tsc v4.2.2

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _**build, outDir, incremental**_
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

N/A

### 💻 Code

N/A

### 🙁 Actual behavior

Error reported instead of generating compiled files in the specified directory.
```bash
error TS5072: Unknown build option '--outDir'.
```

### 🙂 Expected behavior

Expect compiled files generated in the specified directory. This is required for CI pipelines to work without having to modify the source, so build output is generated in the build directory for the current pipeline run and not in the source directory, as it is done in development.

I also will add that the docs are written like a novel not as a technical documentation and it's very hard to navigate them. For this specific issue, it should list which options `--build` can be combined with and which won't work with it. If somehow, in some unimaginable way, this turns out to be behavior by design, you should update the docs saying that `--build` generates incremental builds only in the project's `outDir` and cannot be changed via CLI options.

**Comment by sheetalkamat** [comment] 2021-04-06 19:33
Duplicate of #25613

**Closed by sheetalkamat** 2021-04-06 19:33 UTC
