### ISSUE TITLE
Unsound handling of unions with multiple type variables (real this time)

### ISSUE THREAD

**Issue by mheiber** [microsoft/TypeScript#49432] opened 2022-06-08 08:23 UTC
# Bug Report

> Note: I previously opened a similar report, but made a mistake in the code example there #49186

### 🔎 Search Terms

unsound,union,generic

### 🕗 Version & Regression Information

- This is a runtime error
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about: **unions**
   - 4.7.0-beta, 4.6.4, 4.5.5, 4.4.4, 4.2.3, 4.1.5, 4.0.5, 3.9.7, 3.8.3, 3.7.5, 3.6.3, 3.5.1, 3.3.3 

### ⏯ Playground Link

[playground link](https://www.typescriptlang.org/play?ts=4.7.0-beta#code/GYVwdgxgLglg9mABAUwB5QE4ENoB4DSAfABSoBciAghtgJ4GGIA+VNW91dDhAlBfogDeAKESIICAM5REWGogC8iVAG0ADAF0A3KMQxgiYp3YA6GJOO1icjDx5DdYjMiggMSG+u26Avrueu7rI0On7CoJCwCCjo2NAATLgAKiTkrFwpfIhJDk4ubkhomDhQpDyhwsISYNLKijHFCcQqKgDMGhrliAD03YgAFnAAbsgYiFBwiJLIyOO0AA7IFAAGYCAAtgBGoyoay1VScAA2yCZHcADmZVo9fZsgMkNYRyCz5ojLrfuoJutY86RFIxUF1eogAO79GAQfqIE5YAAmknGkww4Fg61mowwcAwFAA5D8-vM9MiwHAZFhEBFoPAwPjhEA)

### 💻 Code

```ts
function extract<K>(x: Array<K> | Array<Array<K>>): K {
  const arr = x[0];
  if (Array.isArray(arr)) {
    return arr[0];
  }
  return arr;
}

function extract2<T>(x: Array<T>): T {
  return extract(x);
}

const x = extract2([[3]]); // hover to see type: `number[]`
console.log(x); // but value is `3`
x.map(x => x); // which leads to runtime error: 'x.map is not a function'
```

### 🙁 Actual behavior

Runtime error not caught by TypeScript, due to incorrect inference.

### 🙂 Expected behavior

Type error.

**Comment by fatcerberus** [comment] 2022-06-08 14:01
If this is the same bug, why didn’t you just post the corrected repro in the original issue?

**Comment by jcalz** [comment] 2022-06-08 16:18
Looks like a duplicate of #45686.  This sort of filtering is very useful but unsound, but without negated types there's not really much better we can do.  If you care strictly about safety then the call signature `<T>(x: T[] | T[][])=>T` cannot be implemented,  because nothing stops someone from writing both of these:

```ts
const num = extract<number>([[3]]); 
const arr = extract<number[]>([[3]]);
```

but of course at runtime those are the same call.  If you want to work around it in your own code you can try to be more explicit like

```ts
function extract<T>(x: Exclude<T, readonly any[]>[] | T[][]): T { /* impl */ }

extract<number>([[3]]); // okay
extract<number[]>([[3]]); // error

function extract2<T>(x: T[]): T {
  return extract(x); // error
}
```

[Playground link](https://www.typescriptlang.org/play?ts=4.7.2&ssl=7&ssc=2&pln=6&pc=14#code/GYVwdgxgLglg9mABAUwB5QE4ENoB4AqAfABSoBciAoqhADYgAmyBANIhslgwrQJ6JYwvANoBdQmMQAfRPjFiAlBXyIA3gChEiCAgDOUARgyIAvIlTCADKIDcmxDGCJiAQSNZeAOhi632XsRYRgoKavZaHFAgGEhBGFa29gC+9pHRsUZ2KepomDhQuGAgALYARsgYJMLCAMyiogo2iAD0zYhwANYeOejYeEVlFWJVtfWNLW0VGHAY6uqgkLAIKL35AEwEJOSyisphEchRMSt50KTjrShGM+rZQA)

**Comment by mheiber** [comment] 2022-06-09 12:50
@jcalz  thanks for taking a look, but I think I disagree on the diagnosis and am more hopeful the problem is solvable

> If you care strictly about safety then the call signature `<T>(x: T[] | T[][])=>T` cannot be implemented

I agree such signatures (where there are overlapping unions with type variables) are probably mistakes, but they do occur in the wild.

I think it's main the job of a type checker to error on unsound code, not to assume that what the user wrote is intentional.

> ... without negated types there's not really much better we can do

Here are some options:
- Flow approach [playground](https://flow.org/try/#0FA0MwVwOwYwFwJYHsoAIBGBDAJgVSslADwDSAfABQAeAXKgIIBOjmAnqWagD4PNtFMW7cmQCUdEqgDewVKgRhUFQWwB0CAM4rW1UaOmy5qRgFM4ERmioBtAAwBdANyGAvodPnLqKs7fAYADaYGhoM0n6QsIgoqBAaJgBCOBT6MnJYeAQoFNb2os5yMCgacN50UBAAtugmjKgAvBg4+IQ5AMx5Bd6qcEgAYghUJtgpXQD0Y6gAwphQUEilwRoIAOZoAAYZLdmqu6LrqL2o61QHNTCYcSaoFdW1qNYAjPbyoQiwSJUADpiI6AHXADuCDgAAtjvQDtYAEz2VSGCYPd5Fb6-BD-EwAWjgrC+JjhqgmmOALiAA), where the implementation of such a whacky function is rejected. Imo, it would be even better if the signature could *also* be rejected, at least in the common cases.
- Typed Racket, iuc, accepts the definition by doing multiple rounds of constraint solving. I wasn't able to trick it like TypeScript is tricked here.

And in general: saying that negated types are needed to patch this soundness hole doesn't seem right to me. There are plenty of type checkers with unions+generics that don't have this soundness hole. Whereas I suspect negated types would only produce more soundness holes (like conditional types have) in the absence of semantic subtyping.

**Comment by mheiber** [comment] 2022-06-09 12:54
I see how the issue may have a common cause with #45686, but will leave this open for a bit because a different solution might be available. Thanks for the triage @jcalz

**Comment by jcalz** [comment] 2022-06-09 14:41
> I think it's main the job of a type checker to error on unsound code, not to assume that what the user wrote is intentional.

Welcome to the TypeScript Unsoundness Support Group! I'm @jcalz and I have been a member for four years.  Please enjoy the complimentary coffee; the cups leak a little bit so don't hold them directly over your lap.  Today we'll be discussing TypeScript Language Design [Non-Goal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals) #3 and how it can be used as a mantra to stay calm in the face of logical contradictions.

**Comment by RyanCavanaugh** [comment] 2022-06-09 16:57
I don't consider Flow's handling of this to be sound either. Example that checks in both checkers:
```ts
type Cat<T> = { name: T, meow: string }
type Mortgage<T> = { length: T, amount: number };

declare function fn<T>(x: Cat<T> | Mortgage<T>): T;
// if isCat(x) return x.name else return x.amount

const m: Cat<"whiskers"> & Mortgage<30> = { amount: 0, length: 30, meow: "", name: "whiskers" };
const n: Mortgage<30> = m;
function fn(x: Mortgage<30>) {
  const o: number = fn(x); // allowed but is "whiskers"
}
```

There's not much we can do here that's useful. It's not plausible to warn on this kind of signature -- for one, it's effectively the same signature as `Array#flat`! Aliasing is always going to be capable of inducing incorrect inference results if the implementation isn't extremely watertight, but functions that are a tiny bit leaky are very common.

Switching to a sort of whole-program unification like Racket is clearly out of scope.

**Comment by mheiber** [comment] 2022-06-09 18:08
> Switching to a sort of whole-program unification like Racket is clearly out of scope.

Typed Racket uses Local Type Inference, just like TypeScript
Section 4.3 of "Occurrence Typing Modulo Theories" https://arxiv.org/pdf/1511.07033.pdf

> I don't consider Flow's handling of this to be sound either. Example that checks in both checkers:

Flow's approach seems to be such that one can't define the "bad" functions. At least, I haven't managed to trick it yet:

```ts
function badUnion<K>(x: Array<K> | Array<Array<K>>): K {
  if (Array.isArray(x)) {
    return x[0]; // Error
  }
  return x;
}
```

[playground link](https://flow.org/try/#0FA0MwVwOwYwFwJYHsoAIBGBDAJgVSslADwDSAfABQAeAXKgIIBOjmAnqWagD4PNtFMW7cmQCUdEqgDewVKgRhUFQWwB0CAM4rW1UaOmy5qRgFM4ERmioBtAAwBdANyGAvodPnLqKs7fAYADaYGhoM0n6QsIgoqBAaJgBCOBT6MnJYeAQoFNb2os5yMCgacN50UBAAtugmjKgAvBg4+IQ5AMx5Bd6qcEgAYghUJtgpXQD0Y6gAwphQUEilwRoIAOZoAAYZLdmqu6LrqL2o61QHNTCYcSaoFdW1qNYAjPbyoQiwSJUADpiI6AHXADuCDgAAtjvQDtYAEz2VSGCYPd5Fb6-BD-EwAWjgrC+JjhqgmmOALiAA)

I'm not following the alternative example you provided, which omits the definition but has a comment that seems to refer to type predicates. Type predicates are a TypeScript feature that Flow doesn't have: https://github.com/facebook/flow/issues/34.

**Closed** 2022-06-11 20:00 UTC
Labels: Working as Intended

**Comment by mheiber** [comment] 2022-06-12 00:36
Was this issue closed by mistake?

**Comment by RyanCavanaugh** [comment] 2022-06-15 23:40
Won't Fix would be that we identified it as a defect, but decided fixing it wasn't worth the cost. That isn't the case here.

Here, we think this is the right behavior. The actual prevalence of the sort of problematic aliasing here is not common enough to justify issuing many false positive warnings.

**Comment by mheiber** [comment] 2022-08-02 22:26
The TS-Hack-and-Typed-Racket-inspired type checker I worked on at WhatsApp was released this week. Thought it might be helpful to share the behavior, which was pretty simple to implement but required fine-tuning:

Given input:

```erl
-module(sample).
-export([main/1]).

-spec extract([T] | [[T]]) -> T.
extract([[T]]) -> T;
extract([T]) -> T.

-spec extract2([T]) -> T.
extract2([T]) -> extract(T).

-spec main(any()) -> ok.
main(_) ->
    X = extract2([[3]]),
    %io:format("~s~n", [X]),
    lists:map(fun(Z) -> Z end, X),
    ok.
```

We report these errors:

```
error: expected_subtype
  ┌─ wa_util/src/sample.erl:5:19
  │
5 │ extract([[T]]) -> T;
  │                   ^ T.
Expected: T
Got     : any()

See https://fburl.com/eqwalizer_expected_subtype

error: expected_subtype
  ┌─ wa_util/src/sample.erl:6:17
  │
6 │ extract([T]) -> T.
  │                 ^
  │                 │
  │                 T.
Expected: T
Got     : T | [T]

See https://fburl.com/eqwalizer_expected_subtype
  │

  T | [T] is not a subtype of T
  because
  [T] is not a subtype of T

error: expected_subtype
  ┌─ wa_util/src/sample.erl:9:26
  │
9 │ extract2([T]) -> extract(T).
  │                          ^
  │                          │
  │                          T.
Expected: [T] | [[T]]
Got     : T

See https://fburl.com/eqwalizer_expected_subtype
  │

  T is not a subtype of [T] | [[T]]
  because
  T is not a subtype of [T]

3 ERRORS
```

There are still obscure cases where we generate silly-looking errors, but the behavior is at least consistent and sound.
The type checker uses very simple local type inference (Pierce and Turner 2000 Local Type Inference).

**Comment by mheiber** [comment] 2022-08-02 22:55
Summarizing the reasons for marking "working as designed":
- @jcalz saying soundness isn't a design goal. But then why did TS fix a [similar bug in a previous version](https://www.typescriptlang.org/play?ts=3.3.3#code/GYVwdgxgLglg9mABAUwB5QE4ENoB4DSAfABSoBciAghtgJ4GGIA+VNW91dDhAlBfogDeAKESIICAM5REWGogC8iVAG0ADAF0A3KMQxgiYp3YA6GJOO1icjDx5DdYjMiggMSG+u26Avrueu7rI0On7CwhJg0sqKKOjY0MQqKgDMGho8WogA9NmIABZwAG7IGIhQcIiSyMjltAAOyBQABmAgALYARqUqGs0RUnAANsgmQ3AA5qSZOXmdIDJFWEMgteaIzSn9qCbtWPWkioyoM7mIAO75MBD5iCNYACaS5ZUY4LDttaUYcBgUAOQ7Pb1PTPMBwGRYRCgSCwBD-YRAA)? And isn't it better, ceteris paribus for the type checker to check types?
- @RyanCavanaugh  perceived as too difficult to implement: but see Flow, Typed Racket, and now EqWAlizer, which has less ~15 lines of code for the interaction of unions and generics
- @RyanCavanaugh said that Flow's solution is unsound, but gave an example omitting the line where Flow would error
- @RyanCavanaugh  perceived the solution as requiring whole-program type inference: But none of Flow, Typed Racket, and eqWAlizer use global type inference
- @jcalz  perceived a solution as needing negated types: but none of the type checkers above have negated types. 
- @RyanCavanaugh perceived any solution as incompatible with well-typed `Array#flat`: but [TS' `Array#flat` declaration doesn't use unions, so seems to be irrelevant](https://github.com/microsoft/TypeScript/blob/35c1ba6/lib/lib.es2019.array.d.ts#L52)!
- @RyanCavanaugh  empirical claim: "The actual prevalence of the sort of problematic aliasing is not common enough to justify issuing many false positive warnings." This could be measured by implementing the fix and seeing what happens. I have a hunch this kind of issue is really rare: the minimal repro is big!. On the other hand, fixing the soundness hole could prevent real production crashes in users' products.

**Comment by mheiber** [comment] 2024-07-10 11:53
It's ~20 LOC to handle this soundly, and the only cases that are rejected are cases where the user wrote something ambiguous: https://github.com/WhatsApp/eqwalizer/blob/1dbdbbd/eqwalizer/src/main/scala/com/whatsapp/eqwalizer/tc/generics/Constraints.scala#L163
