### ISSUE TITLE
Variable type wrong if one branch can only be reached via an async function

### ISSUE THREAD

**Issue by m1cm1c** [microsoft/TypeScript#54810] opened 2023-06-28 14:08 UTC
# Bug Report

In the code I provided, `v` can be `null` or a number. TS does recognize the null case but not the number case. For this reason, `v` is of type `never` (according to TS server) in the else branch, even though `v` is a number in this case.

### 🔎 Search Terms

async; never

### 🕗 Version & Regression Information

I'm using typescript@5.0.4.

> If possible, please try testing the nightly version of TS to see if it's already been fixed.
> For npm: `typescript@next`
> This is also the 'Nightly' version in the playground: http://www.typescriptlang.org/play/?ts=Nightly

In the playground, the bug occurs even when using the nightly version.

- This is the behavior in every version I tried.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230628#code/IYZwngdgxgBAZgV2gFwJYHsIwLbFRACgEoYBvAKBhikxGRgCcYBeGAWWGQAsA6B4CABN02YgG5KMADYBTegDcAXDAgJsAIxlMAPioRSpLPQYlUaEOjBAi5XfAHMjTAHwwADDwCsMAPySqwADuePQEoJCwxCyuFFRx1LT09KxBIVY2AILg0ABiSFBomOL+cfJG9ADUMACMpvGMcggMWJUwAMx1VAC+RFGKJamooeHQMFHMMSVmiTDJMIP01tgyWRF5KBiERJ1xDI3NszBVnjs9xdMW6LI8Uuj2BEu2DtuSqHAEZcxfxlIksXHmazXW73ADkABUAMpWLTyLRWYBgECzOzIqACGBcYAAB2xMggPFBL3igKuMhudw+xJgXRgMikIBkZBKpOBlIh0MZDDhTBAiOR3FQaIEEHQ9CxuPxYzKQpg6DgszAeJUMh5REJ1IuQPJIKpdS65AN5Fw+GK5BGsEQG0w6WWq1y+UKW2ZVD2yCaWBOhvIQA)

### 💻 Code

```ts
async function main() {
  const r = Math.random();
  let v: number | null = null;
  const something = r > 0.5 ?
    await (async () => {
      const t = await someAsyncFunction();
      v = t + 1;
      return t + 3;
    })() :
    await (async () => {
      const t = await someAsyncFunction();
      return t + 5;
    })();
  console.log(something);
  if(v === null) {
    console.log('TS server says this can happen.');
    console.log(v);
  } else {
    console.log('TS server says this cannot happen (v is of type never).');
    console.log(v);
  }
}

main();

async function someAsyncFunction() {
  return 5;
}

```

### 🙁 Actual behavior

never

### 🙂 Expected behavior

number

**Comment by MartinJohns** [comment] 2023-06-28 14:11
Duplicate of #9998.

**Closed** 2023-06-30 18:00 UTC
Labels: Duplicate
