### ISSUE TITLE
Salsa: dynamic require seems to break Code's language service

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/TypeScript#7149] opened 2016-02-19 09:16 UTC
**TypeScript Version:** 1.8.0-beta

VS Code's Javascript Salsa language service seems to break down as soon as I type a dynamic require into the buffer. I lose all language features: intellisense, mark occurrences, etc. I can only get out of that state by reloading Code's window.

```javascript
require('' + '');
```

![bug2](https://cloud.githubusercontent.com/assets/22350/13171194/b87f0ff4-d6f1-11e5-9da7-7213791dfbd6.gif)

**Comment by joaomoreno** [comment] 2016-02-19 09:17
ping @alexandrudima @dbaeumer @egamma

**Comment by vladima** [comment] 2016-02-19 19:23
I can repro this issue 1.8. It looks like a dupe of #6703, should already be fixed in master.

**Closed by vladima** 2016-02-19 19:23 UTC
Labels: Duplicate
