### ISSUE TITLE
Array.isArray guard drops the type of the 

### ISSUE THREAD

**Issue by geon** [microsoft/TypeScript#56842] opened 2023-12-21 11:27 UTC
### 🔎 Search Terms

isArray

### 🕗 Version & Regression Information

Bug occurs in 5.3.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgLIE8CS5rycgbwChlkBnAewFsIAFKCgB2jHQC5ywpQBzAbiIBfIkQQUQZMMiroAwuMkcM2SLEQoAPsgCCUKHHQAeZTjVIAfMgC8hctToNmUVhwBEACwgAbLxVfJBASJgGGQACl19dAA6YDJIgzCZeQkwAEo0whJkAHoc5DFU6TkFMCUsUzwUADJkOBB0AG0AXWzk0saABmbosHc4+iYWdAARCggyADkKMABRAA84qRtXAHcKKC8AE1c+XPzZ1ei2ktToyhpBp1ZrZDWN7d395EPj4SIYAFcQBDBgcWQACMIGBVJh4noDIYACrmMIwCgUDjQ5BaBJGWFpDgIijIOI6SEYyzEUhQEGfKAgAlRWIQqLwxFpATvELhYGg6Dg9FJU6SDJZUh5ZBXYbIADkfQGjmGYwm0zmi0kYuQW3GZGQIBmyAgiqkANYzHFJlUVTFvTIYQATABma0ATjSJxSki6PUlZBFzlGavlCyWt3umx2QUF+QAyn8fECGABrCAgY6kdpnC4OIZegPrIO7IREIA

### 💻 Code

```ts
interface MyInterface {
  someProperty: string;
}

const myConst: MyInterface | Array<MyInterface> = { someProperty: "hello" };

if (Array.isArray(myConst)) {
  // const myConst: MyInterface & any[]
  myConst[0].thisPropertyDoesNotExist = "world"; // Ew.
  myConst.someProperty = "world"; // Ew.
}

```

### 🙁 Actual behavior

It compiles.

### 🙂 Expected behavior

Accessing thisPropertyDoesNotExist should be an error.

Accessing someProperty when isArray says it's an array should be an error.

**Comment by jcalz** [comment] 2023-12-21 15:04
Duplicate of #33700 probably

Also: Issue title drops the object of the

**Comment by fatcerberus** [comment] 2023-12-21 15:22
@jcalz #33700 is definitely related, but see below.

You only lose the array type here because the value is narrowed to `MyInterface` on assignment, so the type guard has to remanufacture the array type from whole cloth.  If you *actually* have a `MyInterface | MyInterface[]` then it works as expected:
```ts
declare const myConst: MyInterface | Array<MyInterface>;

if (Array.isArray(myConst)) {
  // const myConst: MyInterface[]
  myConst[0].thisPropertyDoesNotExist = "world"; // error
  myConst.someProperty = "world"; // also error
}
```

`betterIsArray()` doesn't fare much better in this situation - it narrows the value to `MyInterface & MyInterface[]`, which is clearly not what you want (and allows the assignment to `myConst.something` to succeed).  That's not observable in your playground as-is because for some reason (this might be a separate bug) it gets re-widened to `MyInterface | MyInterface[]` after the first check.

**Comment by RyanCavanaugh** [comment] 2023-12-21 19:00
This is correct behavior. On this line you said

```ts
const myConst: MyInterface | Array<MyInterface> = { someProperty: "hello" };
```

*TypeScript can see this line of code*, and can see that `{ someProperty: "hello" }` is a `MyInterface`, not an array.

So then when you write
```ts
if (Array.isArray(myConst)) {
```
The only situation where this is `true` is one where whatever initialized `myConst` was *also* an array. What kind of array? Well, we don't know, so it's `any[]`.

If the initializer of `myConst` isn't statically-determined to be `MyInterface`, then you see the error on line 9 as expected.

**Comment by fatcerberus** [comment] 2023-12-21 19:08
@RyanCavanaugh Is it a bug that `myConst` widens to the declared type *after* the `isArray` check?

**Comment by geon** [comment] 2023-12-21 19:52
> What kind of array? Well, we don't know, so it's any[]

But we *do* know. The array is typed before the if, and elements should have the same type inside the if.

**Comment by jcalz** [comment] 2023-12-21 20:14
No, [`in` operator narrowing](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#the-in-operator-narrowing) has apparently precluded the possibility of ` Array<MyInterface>`.

**Comment by fatcerberus** [comment] 2023-12-21 20:24
> But we do know. The array is typed before the if, and elements should have the same type inside the if.

The declared type, yes, but the value is narrowed on assignment (TS knows that you didn't assign an array so removes that possibility from the union) so the type system has essentially "forgotten" about the array type by the time you do the `isArray` check.

**Closed** 2023-12-24 01:30 UTC
Labels: Working as Intended
