### ISSUE TITLE
Subclass property sharing name with type parameter can't be resolved

### ISSUE THREAD

**Issue by ssalbdivad** [microsoft/TypeScript#56689] opened 2023-12-06 10:44 UTC
### 🔎 Search Terms

subclass property type parameter resolution 2339

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://tsplay.dev/wEYkOw

### 💻 Code

```ts
class Leg {}

class Foo<t> extends Leg {
    t = {} as t

    // should allow this access since t was declared as a property on Foo
    foo = this.t 
}
```

### 🙁 Actual behavior

Error on accessing `t`: `Property 't' does not exist on type 'Foo<t>'.ts(2339)`

### 🙂 Expected behavior

Should allow `t` to be accessed.

**Comment by MartinJohns** [comment] 2023-12-06 11:03
Duplicate of https://github.com/microsoft/TypeScript/issues/56620.

**Closed** 2023-12-09 01:27 UTC
Labels: Duplicate
