### ISSUE TITLE
MsBuild (VsTsc): Incremental TypeScript build: Build 2x: The 2. build is skipped, even if the 1. failed

### ISSUE THREAD

**Issue by nvirth** [microsoft/TypeScript#41969] opened 2020-12-15 15:01 UTC
Use TypeScript incremental build in an MsBuild project.
(With NuGet package Microsoft.TypeScript.MSBuild)
Have a TypeScript build error
The 1. MsBuild will fail, and show you the error.
The 2. MsBuild will succeed, because TypeScript compilation is skipped. You can see in build output:

    Skipping target "CompileTypeScriptWithTSConfig" because all output files are up-to-date with respect to the input files

**TypeScript Version:**  4.1.2

**Search Terms:** msbuild vstsc incremental "skipping CompileTypeScriptWithTSConfig"

**Code**

tsconfig.json:

```json

{
  "compilerOptions": {
    "tsBuildInfoFile": "obj/tsconfig.tsbuildinfo",
    "incremental": true,
  }
}

```

Any typescript file with any error:

```ts
let a = somethingThatBreaks();
```

**Expected behavior:**
Tsc should run and fail the 2. time as well

**Actual behavior:**
Tsc is skipped the 2. time

**Repro repo**
https://github.com/nvirth/tsc-incremental-issue

**Comment by uniqueiniquity** [comment] 2020-12-15 20:50
@nvirth Thank you for reporting this!
We are investigating ways to properly support TypeScript's incremental build feature in MSBuild and will update this issue as we make progress.
Thanks again!

**Comment by Sc0tTyXL** [comment] 2021-03-30 10:30
I have the same issue with the incremental setting off. 
MSBuild thinks the files haven't changed and will therefor not call TSC the 2nd time.
This might be the cause: https://github.com/microsoft/TypeScript/issues/7247

MSBuild should simply always call TSC and let TSC figure out if it needs recompilation

TypeScript v4.1
Visual Studio 2019 (latest update)

**Comment by uniqueiniquity** [comment] 2021-04-03 00:30
@nvirth Apologies for the delay on getting back to this.
In Microsoft.TypeScript.MSBuild 4.2, we introduced a new MSBuild property `TypeScriptEnableIncrementalMSBuild`.
If you set this to false in your project file, MSBuild will always invoke `tsc`. 

@Sc0tTyXL it sounds like this will address your issue as well. 

I'll close this ticket for now. Please ping me if you have any issues with this new property!

**Closed by uniqueiniquity** 2021-04-03 00:30 UTC
Labels: Needs Investigation

**Comment by Sc0tTyXL** [comment] 2021-04-06 11:08
@uniqueiniquity I cannot find any documentation on that setting yet.

Is it a part of the TypeScriptBuildMode setting found here https://www.typescriptlang.org/docs/handbook/project-references.html#msbuild ?

Currently it seems MSBuild is still building all the tsconfigs in the Project (or at least calling TSC). 
Will this setting just call the root tsconfig and have TSC figure it out from there?
