### ISSUE TITLE
There should be a compiler option to disallow assignment of object literals to variables of type class

### ISSUE THREAD

**Issue by peabnuts123** [Microsoft/TypeScript#23248] opened 2018-04-07 21:08 UTC
**TypeScript Version:**  2.7.2

**Search Terms:** object assign class

**Code**

```ts
class DummyClass {
  public name: string;
  public value: number;

  constructor(name: string, value: number) {
    this.name = name;
    this.value = value;
  }
}

// Totally fine, even though `myThing instanceof DummyClass === false`
let myThing: DummyClass = {
  name: "Hello",
  value: 20,
};
```

Apologies if this is a duplicate, it's a very keyword-laden topic and my searches for this topic are fairly polluted by many other features of TypeScript. 

**Behavior:**
In the above example, the TS compiler allows my assignment of an object literal to a variable of type `DummyClass`, which is a class type. It has exactly the same signature, and so as far as JavaScript is aware this is equivalent. 
Now, I totally understand why TypeScript allows this behaviour, and I understand TypeScript's philosophy with regards to things like this. What I would like to see is an option to disallow this in the compiler options, as I personally would like to disallow this in my project.
My rationale for this is that when it comes to members of a class type that are not simply variables of a specific type (e.g. functions, private members, etc.) it can easily create unexpected behaviour in your code, and at a project level, I would like to disallow people from doing this.

For example: 

```ts
class DummyClass {
  public name: string;
  public value: number;

  constructor(name: string, value: number) {
    this.name = name;
    this.value = value;
  }

  public log() {
    // Output values for parsing key:value, comma-separated
    console.log(`name:${this.name},value:${this.value}`);
  }
}

// Totally fine, even though log has been re-implemented
let myThing: DummyClass = {
  name: "Hello",
  value: 20,
  log() {
    console.log("Hello!!!");
  },
};
```

In this example I have added a log method for some theoretical process to parse my logs later expecting a specific format (this could be implemented in better ways). The instance of `myThing` does not have the correct implementation of log(), and this is now a code smell as far as I am concerned. 
It would be nice to be able to disable this kind of behaviour at a compiler-level. People will be able to work around it if they want, sure, but the level of effort required between this and, say, making an inheriting sub-class are orders of magnitude different in terms of intention required; this kind of assignment could happen by accident, especially if you had, say, objects passing around with very similar signatures (and one got assigned to another accidentally).

**Comment by andy-ms** [comment] 2018-04-09 15:05
Duplicate of #202

**Comment by peabnuts123** [comment] 2018-04-13 01:41
I guess? I can see how one might implement what I'm describing using #202, but it seems like a workaround. TypeScript can duck-type an object into a class instance, but in certain lights these objects are not the same (e.g. prototypes are different). This issue is about how it would be nice at a compiler-level to optionally disable this behaviour. I would have to physically restructure the way my system works to utilise different nominals to achieve this behaviour.

**Closed** 2018-04-27 17:27 UTC
Labels: Duplicate
