### ISSUE TITLE
type guard is fail when use in `case`

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#37886] opened 2020-04-10 07:06 UTC
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts
case line instanceof Pair:
	return foldLine(pairWithSeparator(line.key, line.value, keySep, latin1))
```

**Expected behavior:**

`line` should infer to `Pair:`

**Actual behavior:**

> Error: TS2339: Property 'key' does not exist on type 'string | string[] | Comment | EmptyLine | Pair'.
  Property 'key' does not exist on type 'string'.

**Playground Link:** 

**Related Issues:**

**Comment by DanielRosenwasser** [comment] 2020-04-10 19:27
Please post complete examples.

Duplicate of https://github.com/microsoft/TypeScript/issues/37178

**Closed by DanielRosenwasser** 2020-04-10 19:27 UTC
Labels: Duplicate
