### ISSUE TITLE
Compiler option to rewrite import file paths

### ISSUE THREAD

**Issue by alshdavid** [microsoft/TypeScript#35351] opened 2019-11-26 06:09 UTC
## Problem 

When using paths to apply an alias to an import, the  files do not represent the expected target path.

Not rewriting the paths is the correct and expected behaviour from the TypeScript compiler and further rewriting belongs to extra tooling layers, like Webpack.

Webpack can be used to rewrite the paths in the emitted javascript bundles, however this rewrite is not represented in declaration files or maps so its behaviour is incomplete. This means that modules which are expected to have consumable declarations are unable to rely on the generated files. 

## Proposal

It would be awesome if TypeScript included the ability to alias + rewrite imports which worked on both emitted `.js`, `.d.ts` files and source maps.

Perhaps the inclusion of a new compiler option called something similar to `rewriteImports` is a solution.

Below I am setting `~` as a path which represents an absolute import path from the root of the source directory.

```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "rewriteImports": {
      "~": "."
    }
  }
}
```

## Example

Given the following folder structure:
```
/a
  index.ts
/b
  index.ts
```

Imagine that `a/index.ts` looks like:

```typescript
import { foo } from '~/b'
console.log(foo)
export type Foo = typeof foo
```

The output javascript and declaration files would look like:

```typescript
// a/index.js
import { foo } from '../b'
console.log(foo)
```
```typescript
// a/index.d.ts
import { foo } from '../b'
export type Foo = typeof foo
```

**Comment by denis-sokolov** [comment] 2019-11-26 11:57
Duplicate of #26722.

(Other mentions: #10866, #16640, #18951, #19453)

**Comment by alshdavid** [comment] 2019-11-26 23:21
I have been experimenting with webpack and rollup with no success.
Check out the repo (webpack branch):

https://github.com/alshdavid-sandbox/typescript-library

**Comment by fatcerberus** [comment] 2019-11-27 05:58
Not likely to happen:
https://github.com/microsoft/TypeScript/issues/31643#issuecomment-496995677

**Closed** 2019-12-05 18:00 UTC
Labels: Duplicate

**Comment by tobico** [comment] 2024-05-07 06:32
I ran into this issue today while developing a component library using TypeScript and had good results using the package [tsc-alias](https://www.npmjs.com/package/tsc-alias) to fix my imports after compilation.
