### ISSUE TITLE
Improve 'Cannot compile modules unless the '--module' flag is provided.' message

### ISSUE THREAD

**Issue by BretJohnson** [Microsoft/TypeScript#4448] opened 2015-08-25 20:35 UTC
I'm fairly new to TypeScript, having been working with it a few days to create d.ts files, in VSCode, for some Node components.
I'd been persistently seeing this message in VSCode for my d.ts files:
  `Cannot compile modules unless the '--module' flag is provided.`
That threw me, at least as a noob, as I wasn't using tsc at all--I was just using IntelliSense.   How was I supposed to provide a --module flag?  Is IntelliSense just buggy?
Later after googling for the error I first learned about the tsconfig.json file--something I didn't learn about previously reading the TypeScript docs.
Anyway, my recommendation would be to update to the message to say something like:
`Cannot compile modules unless the '--module' flag is provided.  Do you need to provide a tsconfig.json file?`
That would have been a big help for noobs like myself, cluing us into the existence of tsconfig.json and it being the way to fix this up.  Thanks.

**Comment by DanielRosenwasser** [comment] 2015-08-25 20:40
Discussed with @mhegazy - we could make the message

> Cannot compile modules unless the '--module' flag is provided. Consider setting the 'module' compiler option in a 'tsconfig.json' file.

Or we could conditionally elaborate if in a language-service context, though this might not be appropriate.

**Comment by mhegazy** [comment] 2015-08-25 20:50
Feel free to send a PR for this. The text is in https://github.com/Microsoft/TypeScript/blob/master/src/compiler/diagnosticMessages.json#L438,
to run tests `jake runtests` and then `jake baseline-accept` to get all messages update in baselines.

**Comment by plantain-00** [comment] 2015-10-01 11:36
I find that 3 files was deleted when run `jake baseline-accept`, and I committed it, I'm checking this now.

**Comment by mhegazy** [comment] 2015-12-08 04:03
thanks @plantain-00!

**Closed** 2015-12-08 04:03 UTC
Labels: Accepting PRs, Suggestion

**Comment by timofeysie** [comment] 2015-12-24 22:38
So where does the '--module' flag go in the tsconfig.json file?  A search for that on https://github.com/Microsoft/TypeScript/wiki/tsconfig.json returns too many results...

**Comment by plantain-00** [comment] 2015-12-25 00:27
@timofeysie `module` in `compilerOptions` in `tsconfig.json`

**Comment by timofeysie** [comment] 2015-12-25 03:53
@plantain-00 , so from the Angular2 seed, in the tsconfig.json file, it already has "compilerOptions": {
        "module": "commonjs",
...
So how to solve this error?  In the TypeScript wiki it shows things like this:
{
  "compilerOptions": {
    "out": "test.js",
    "allowJs": true
  }
}
It would be a good idea to link to a description of this flag in the docs in the error message.

**Comment by plantain-00** [comment] 2015-12-25 05:22
@timofeysie 
+ How did you get the error? from `tsc` command or IDE's tips?
+ Which version of typescript or what kind of IDE do you use?
+ You can go https://gitter.im/Microsoft/TypeScript to get a faster answer.
+ Once, I got the error from VS Code's tips, so I add `module` into `tsconfig.json`, the error is still on, but the `tsc` command is all right, so I restart the VS Code, then everything is fine.

**Comment by viztastic** [comment] 2016-01-06 03:26
@plantain-00 Fyi I get the same issue too, see screenshot for a real example.

I'm using VSCode (latest version at time of this post)

![image](https://cloud.githubusercontent.com/assets/8556736/12134229/62056520-b481-11e5-9f48-310c440ab420.png)

**Comment by plantain-00** [comment] 2016-01-06 07:29
@viztastic I think the problem is the `files`.

According to : https://github.com/Microsoft/TypeScript/wiki/tsconfig.json

If no "files" property is present in a tsconfig.json, the compiler defaults to including all TypeScript (*.ts or *.tsx) files in the containing directory and subdirectories. When a "files" property is present, only the specified files are included.

So try to remove files or include your files in it.
