### ISSUE TITLE
Typescript does not use declared type in object literal

### ISSUE THREAD

**Issue by BSG-75** [microsoft/TypeScript#40107] opened 2020-08-18 07:24 UTC
**TypeScript Version:**  4.1.0-dev.20200807

**Search Terms:**
Object literal, initialization, declared type
**Expected behavior:**
The created object literal from variables should have its properties' type as same as variables' declared type.
**Actual behavior:**
The created object literal from variables have its properties' type as same as variables' literal type.

**Related Issues:**
Did not find any related issues, because there are too many unrelated issues which contains "object literal" as keyword.
**Code**
Playground link: https://www.typescriptlang.org/play?ts=4.1.0-dev.20200807#
```ts
const x: string | null = null
const obj = { x }
obj.x = 'a' // will trigger error saying  `Type '"a"' is not assignable to type 'null'.`
```
The type of `obj` should have been `{ x: string | null }`, since `x` has been declared with the type of `string | null`.
But actually typescript think `obj` is `{ x: null }`...

<details><summary><b>Output</b></summary>

```ts
"use strict";
const x = null;
const obj = { x };
obj.x = 'a';
```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.1.0-dev.20200807#code/MYewdgzgLgBAHgLhtATgSzAcxgHxmAVwBsiYBefYogKFElhACMArcmAb3hgF9qnmAdHDYByAIYigA)

**Comment by MartinJohns** [comment] 2020-08-18 08:07
The type of `x` is `null`, not `string | null`. You can see this in the tooltip when you hover over the `x ` in your object literal, or when you assign it to another variable e.g. `const f = x;`.

This is the intended behavior, but I can't find the related issue right now.

**Comment by RyanCavanaugh** [comment] 2020-08-18 16:04
Inference here uses the control-flowed type of the variable. This example is isomorphic to an example you *definitely* wouldn't want to be an error:
```ts
function returnObj(x: string | null): { x: string } {
  if (typeof x === "string") {
    // Proposed alteration would cause an error here
    return { x };
  }
  return { x: "default" };
}
```

**Closed** 2020-08-20 20:00 UTC
Labels: Working as Intended
