### ISSUE TITLE
Dynamic class from TypeScript can't be used on NodeJS

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#23553] opened 2018-04-20 01:00 UTC
tsc: 2.8.3

```ts
// dynamic.ts
export function dynamic(subject) {
  return class extends subject {
    extended = true
  }
}
```

Transpiles to
```js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
exports.__esModule = true;
function dynamic(subject) {
    return /** @class */ (function (_super) {
        __extends(class_1, _super);
        function class_1() {
            var _this = _super !== null && _super.apply(this, arguments) || this;
            _this.extended = true;
            return _this;
        }
        return class_1;
    }(subject));
}
exports.dynamic = dynamic;
```

When using in NodeJS 9.4.0 (and likely many versions before this):
```js
const d = require('./dynamic')

class Foo { foo() { return 'foo' } }

const s = d.dynamic(Foo)
new s() // throws
```

Error message:
`TypeError: Class constructor Foo cannot be invoked without 'new'`
due to this line:
```js
 _super.apply(this, arguments)
```

**Comment by DanielRosenwasser** [comment] 2018-04-20 01:01
Duplicate of #17088 and a proposal exists at #15397.

**Comment by unional** [comment] 2018-04-20 01:16
Thanks. 
Want to point out that while the cause is the same as #17088,
this applies to all class in JavaScript, not just build-in classes like `Error` and `Map`.

Also, the `Object.setPrototypeOf(this, new.target.prototype)` workaround does not work here.

**Closed** 2018-07-30 16:23 UTC
Labels: Duplicate
