### ISSUE TITLE
`x</x>/` fails to parse

### ISSUE THREAD

**Issue by antimatter15** [microsoft/TypeScript#51649] opened 2022-11-26 20:58 UTC
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about it

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/B4AgPA9MB8FA)

### 💻 Code

```ts
x </x>/
```

### 🙁 Actual behavior

There is a parse error for a perfectly valid expression 

```
Unexpected keyword or identifier.
Declaration or statement expected.
Unterminated regular expression literal.
```

### 🙂 Expected behavior

It should instead parse the expression as 

```ts
x < /x>/
```

This is the behavior that is found in Babel and ESBuild.

**Comment by MartinJohns** [comment] 2022-11-26 21:06
Why would you ever write code like this? Any practical example?

**Comment by Josh-Cena** [comment] 2022-11-26 22:10
@MartinJohns A parser error is a parser error; it indicates a bug. If TS wants to remain a superset of JS it must parse all valid JS as JS. This seems like a lexing error; I'm not sure if the TS lexer follows the ES model, but the first `/` should definitely be consumed as `InputElementRegExp` because a `<` punctuator, whether as the start of a generic or as the less than operator, cannot be directly followed by a `/` punctuator.

**Comment by MartinJohns** [comment] 2022-11-26 22:22
I'd argue the team has better things to do than to make sure some obscure code that's never really written works. Resources are finite.

**Comment by fatcerberus** [comment] 2022-11-26 23:25
Given that the code parses successfully when adding a space after the `<`, the bug is likely caused by the ambiguity between JS and JSX interpretations of the same code, which wouldn't be unprecedented (this is not valid JSX because there's no opening `<x>` tag but error recovery in the parser muddies the waters).

I think there have been similar bugs in the past caused by parsing ambiguities that were deliberately not fixed (or at least not completely) due to design limitations in the parser, so I could definitely see "nobody would write this code" being the justification given for not fixing it.  See for example https://github.com/microsoft/TypeScript/issues/16241 (an extreme example where the JS and TS interpretations of the code are mutually exclusive) which looks like it *did* get fixed but took several years and a few attempts to do so.

**Comment by jcalz** [comment] 2022-11-27 01:10
Reminds me of to #33639, which was considered "won't fix" even though it does technically mean that TS isn't exactly a superset of JS.

**Comment by Josh-Cena** [comment] 2022-11-27 01:44
Originally I thought it was confused with instantiation expressions; but ambiguity with JSX seems harder to fix (albeit not impossible). However, #33639 was due to _actual_ grammar ambiguity, but this one is simply a faulty lexer.

**Comment by RyanCavanaugh** [comment] 2022-12-01 19:15
If someone can fix this without negative side effects, feel free to send a PR, but this is just a "You tried to break it on purpose and were successful" situation.

**Closed by RyanCavanaugh** 2022-12-01 19:15 UTC
Labels: Won't Fix

**Comment by fatcerberus** [comment] 2022-12-01 21:54
> this is just a "You tried to break it on purpose and were successful" situation

someone pick up that phone because I called it
