### ISSUE TITLE
Union literal string value type degenerate to string type in function params destructuring

### ISSUE THREAD

**Issue by zheeeng** [Microsoft/TypeScript#29073] opened 2018-12-18 04:41 UTC
**TypeScript Version:**  3.2.2

**Search Terms:** Union literal string,  destructuring

**Code**

```ts
interface Prop { 
    foo: number,
    bar?: 'apple' | 'banana',
}

type Fn<T> = (p: T) => T

const test: Fn<Prop> = (p) => p

const test2: Fn<Prop> = ({ foo, bar }) => ({ foo, bar })

// bar -> string ?
const test3: Fn<Prop> = ({ foo, bar = 'apple' }) => ({ foo, bar })
```

**Expected behavior:**
All test functions pass type checking

**Actual behavior:**
`test3` be reported: Type 'string' is not assignable to type '"apple" | "banana" | undefined'.
the `bar` in `test3` is inferred as string type.

**Playground Link:** http://www.typescriptlang.org/play/index.html#src=interface%20Prop%20%7B%20%0A%20%20%20%20foo%3A%20number%2C%0A%20%20%20%20bar%3F%3A%20'apple'%20%7C%20'banana'%2C%0A%7D%0A%0Atype%20Fn%3CT%3E%20%3D%20(p%3A%20T)%20%3D%3E%20T%0A%0Aconst%20test%3A%20Fn%3CProp%3E%20%3D%20(p)%20%3D%3E%20p%0A%0Aconst%20test2%3A%20Fn%3CProp%3E%20%3D%20(%7B%20foo%2C%20bar%20%7D)%20%3D%3E%20(%7B%20foo%2C%20bar%20%7D)%0A%0A%2F%2F%20bar%20-%3E%20string%20%3F%0Aconst%20test3%3A%20Fn%3CProp%3E%20%3D%20(%7B%20foo%2C%20bar%20%3D%20'apple'%20%7D)%20%3D%3E%20(%7B%20foo%2C%20bar%20%7D)%0A%0A

**Related Issues:**

**Comment by weswigham** [comment] 2018-12-18 17:49
Duplicate of #28835?

**Comment by DanielRosenwasser** [comment] 2018-12-18 19:41
Can you try out a nightly and determine if this is fixed for you @zheeeng?

**Comment by mrliptontea** [comment] 2018-12-19 11:10
Getting the same on typescript@3.3.0-dev.20181219

It seems to be specific to object keys, example with node's crypto module and @types/node:

This is fine:

```js
const crypto = require('crypto');
const encoding = 'hex';
const hash = crypto.createHash('sha1').update('fries123').digest(encoding);
```

This is not:

```js
const crypto = require('crypto');
const conf = { encoding: 'hex' };
const hash = crypto.createHash('sha1').update('fries123').digest(conf.encoding);
//                                                               ^^^^^^^^^^^^^
// Argument of type 'string' is not assignable to parameter of type 'HexBase64Latin1Encoding'
```

**Comment by zheeeng** [comment] 2018-12-19 11:18
@DanielRosenwasser TS 3.3.0 fixed this issue.

**Comment by mrliptontea** [comment] 2018-12-19 11:50
Reproduced my case in the [playground](http://www.typescriptlang.org/play/index.html#src=type%20Encoding%20%3D%20%22hex%22%20%7C%20%22base64%22%3B%0D%0A%0D%0Afunction%20digest(encoding%3A%20Encoding)%3A%20string%20%7B%0D%0A%20%20%20%20return%20encoding%3B%0D%0A%7D%0D%0A%0D%0Adigest(%22hex%22)%3B%0D%0A%0D%0Aconst%20enc%20%3D%20%22base64%22%3B%0D%0Adigest(enc)%3B%0D%0A%0D%0Aconst%20conf1%20%3D%20%7B%0D%0A%20%20%20%20algo%3A%20%22sha1%22%2C%0D%0A%20%20%20%20enc%3A%20%22hex%22%0D%0A%7D%3B%0D%0Adigest(conf1.enc)%3B%0D%0A%0D%0Aconst%20conf2%20%3D%20%7B%0D%0A%20%20%20%20%2F**%20%40type%20Encoding%20*%2F%0D%0A%20%20%20%20enc%3A%20%22hex%22%0D%0A%7D%3B%0D%0Adigest(conf2.enc)%3B%0D%0A%0D%0A%2F**%0D%0A%20*%20%40typedef%20%7Bobject%7D%20DigConf%0D%0A%20*%20%40property%20%7BEncoding%7D%20enc%0D%0A%20*%2F%0D%0A%2F**%20%40type%20%7BDigConf%7D%20*%2F%0D%0Aconst%20conf3%20%3D%20%7B%0D%0A%20%20%20%20enc%3A%20%22hex%22%0D%0A%7D%3B%0D%0Adigest(conf3.enc)%3B%0D%0A%0D%0Ainterface%20Config%20%7B%0D%0A%20%20%20%20enc%3A%20Encoding%0D%0A%7D%0D%0A%0D%0Aconst%20conf4%3A%20Config%20%3D%20%7B%0D%0A%20%20%20%20enc%3A%20%22hex%22%0D%0A%7D%3B%0D%0Adigest(conf4.enc)%3B%0D%0A).

I know this is infering types but in my case it would make sense to define an interface and I would expect either of these to work, especially with `@type`.

**Closed** 2018-12-19 18:39 UTC

**Comment by weswigham** [comment] 2018-12-19 18:40
@mrliptontea that's unrelated to this issue, and is behaving as expected. You'll need to write `{ encoding: 'hex' as 'hex' }` so we know to keep the literal type of the encoding member.
