### ISSUE TITLE
Incorrect type deduced for first element of tuple after reversing it.

### ISSUE THREAD

**Issue by yeah-boi** [microsoft/TypeScript#53774] opened 2023-04-14 05:56 UTC
The following typescript program gives no warning or errors, but crashes at runtime. Typescript incorrectly thinks that p[0] is a string after reversing the tuple, but it is a number:

```
const p: [ string, number ] = [ "x", 1 ];
p.reverse();
p[0].toUpperCase();
```

Playground: https://www.typescriptlang.org/play?#code/MYewdgzgLgBADgLhgbRtATgSzAcwDQxgCuAtgEYCm6MAujALwowBEAHswQIy0DcAUHAB06CgDcqECgAoAlPzjIADDUFQQAVThwqAYQCGk2fyA

**Comment by MartinJohns** [comment] 2023-04-14 06:07
You forgot to fill out the issue template.

It's a design limitation. Duplicate of #52375.

**Closed** 2023-04-15 17:56 UTC
Labels: Duplicate
