### ISSUE TITLE
Compile-on-save not resolving macros

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#4245] opened 2015-08-09 20:43 UTC
Hi,

**Version**: VS 2015/TS 1.5.4

I have the following settings.

On the "Build" settings page I have
![image](https://cloud.githubusercontent.com/assets/1106823/9156813/ef56d8f0-3ede-11e5-8004-cb3c6eaa4d7a.png)

On the "TypeScript Build" settings page I have
![image](https://cloud.githubusercontent.com/assets/1106823/9156820/16b1662c-3edf-11e5-9dd2-0ac408bf74c0.png)

When I build the whole project, things work correctly and the output is written to `bin`.

However, compile-on-save writes the output to a folder called `$(OutDir)`.

![image](https://cloud.githubusercontent.com/assets/1106823/9156828/86f480a4-3edf-11e5-97bf-42fd3dc1aefe.png)

**Comment by DickvdBrink** [comment] 2015-08-09 20:46
Looks a bit like https://github.com/Microsoft/TypeScript/issues/4109

**Comment by NoelAbrahams** [comment] 2015-08-09 20:48
Ah, yes, thanks... looks like a duplicate. Leaving it open for the moment as it works on build but fails on compile-on-save.

**Comment by NoelAbrahams** [comment] 2015-08-09 21:01
Incidentally, writing `bin` in the box (instead of `$(OutDir)` does fix the problem, but then we have the output directory hard-coded in two places.

**Comment by mhegazy** [comment] 2015-08-10 17:45
That is a dupe of  #4109. @paulvanbrenk is looking into it.

**Closed by mhegazy** 2015-08-10 17:45 UTC
