### ISSUE TITLE
Use tsconfig inside package.json

### ISSUE THREAD

**Issue by ColdHandz** [microsoft/TypeScript#39999] opened 2020-08-11 15:56 UTC
Search terms: tsconfig.json tsconfig package.json config

## Suggestion

# Use tsconfig.json inside package.json
#### Just like you can use other tools like *Babel*.
It is a very basic feature but in a world where we have so many config files having one less is great (especially for starting projects and templates).
It's simple and allows for more flexibility.
If your tsconfig.json is very basic and consists of a few lines.
If you want your project to be a little bit tidier.
It's a little bit more convenient for online coding environments.
No extra file.

## Use Cases

* Online coding environment.
* Simple starting project.
* Project template.
* Giant config loaded project.

## Examples
`package.json`

```
{
  "name": "Foo",
  "version": "1.0.0",
  "babel": {
    "presets": [
        "@babel/preset-env"
    ]
  },
  "tsconfig": { ... },
}
```

## Checklist

My suggestion meets these guidelines:

* [✓] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [✓] This wouldn't change the runtime behavior of existing JavaScript code
* [✓] This could be implemented without emitting different JS based on the types of expressions
* [✓] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [✓] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-08-11 21:44
Duplicate of #32830.

**Closed** 2020-08-13 18:01 UTC
Labels: Duplicate
