### ISSUE TITLE
async/await: direct transpilation to .then(...)?

### ISSUE THREAD

**Issue by d180cf** [Microsoft/TypeScript#12196] opened 2016-11-12 09:57 UTC
It's good that the current implementation can handle arbitrarily complex async functions, even with `await` statements inserted in arithmetic expressions run in a loop, but in most practical cases async functions can be easily transpiled into a chain of .then(...) calls. I'm wondering why this approach wasn't taken: transpiling to .then(...) if possible and transpiling to `yield` if not.

If would be nice to switch to async/await in my project, which is full of .then(...) chains, but it's not possible because even simplest async functions would turn into huge state machines that are neither readable nor debuggable.

**Comment by aluanhaddad** [comment] 2016-11-12 11:22
Duplicate of #11725

**Closed** 2016-11-12 18:21 UTC
Labels: Duplicate
