### ISSUE TITLE
Cannot access indexed type of constrained type parameter

### ISSUE THREAD

**Issue by HerringtonDarkholme** [Microsoft/TypeScript#12340] opened 2016-11-18 05:04 UTC
Related: https://github.com/Microsoft/TypeScript/issues/12311

**TypeScript Version:**  nightly
**Code**

```ts
type Boxed = {
    [k in string]: {value: any}
}

type Unboxed<T extends Boxed> = {
    [K in keyof T]: T[K]['value']
}
```

**Expected behavior:**
Should compile since `Boxed` has index signature. T with constraint `Boxed` should also be indexable, with `T[K]` constrained by `Boxed`'s value type, in this case, `{value: any}`

**Actual behavior:**

Error, `Property 'value' does not exist on type 'T[K]'`

**Comment by ahejlsberg** [comment] 2016-11-18 21:36
Duplicate of #12311.

**Closed** 2016-11-18 23:45 UTC
Labels: Duplicate
