### ISSUE TITLE
JSX union signatures broken in nightly

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#27990] opened 2018-10-19 16:10 UTC
**TypeScript Version:**  3.2.0-dev.20181019

**Code**

```ts
declare const MyComponent: (new (props: any) => any) | ((props: any) => any);
<MyComponent />
```

**Expected behavior:**

No error.

**Actual behavior:**

`src/a.tsx:2:2 - error TS2604: JSX element type 'MyComponent' does not have any construct or call signatures.`

This is breaking tests for `react` on DefinitelyTyped, so it would be nice to get the fix in soon even if it means reintroducing a kludge.

**Comment by weswigham** [comment] 2018-10-19 17:53
Duplicates #27948

**Comment by DanielRosenwasser** [comment] 2018-10-25 22:17
Duplicate of #27948

**Closed** 2018-10-25 22:17 UTC
Labels: Duplicate
