### ISSUE TITLE
Compiler API -  `ts.ModuleKind` and `ts.ScriptTarget` is `undefined`

### ISSUE THREAD

**Issue by yxshv** [microsoft/TypeScript#56903] opened 2023-12-30 03:14 UTC
### 🔎 Search Terms

I tried search searching on the internet for
- "ts.Modulekind undefined"
- "ts.ScriptTarget undefined"

but found nothing that could help me :(
but i found this issue - https://github.com/microsoft/TypeScript/issues/26535

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about

### 💻 Code

This is the same code as given in the example of [Typescript compiler api](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API)
```ts
import * as ts from "typescript";

const source = "let x: string  = 'string'";

let result = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS }});

console.log(JSON.stringify(result));
```

### 🙁 Actual behavior

An error occurred, saying that `ts.Modulekind` is `undefined`

```
let result = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS }});
                                                                                   ^

TypeError: Cannot read property 'CommonJS' of undefined
    at file:///Users/balkrishnaverma/Documents/yash/testum/src/index.mjs:5:84
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

### 🙂 Expected behavior

The `result` should've been printed

**Comment by yxshv** [comment] 2023-12-30 06:07
Ok, I replaced `ts.Modulekind.CommonJS` to `1`, then i received a new error
```
let result = ts.transpileModule(source, { compilerOptions: { module: 1 }});
                ^

TypeError: ts.transpileModule is not a function
```

so I thought there is something wrong with my import statemenet
so i changed it to
```ts
import ts from "typescript"
// earlier was: import * as ts ...
```

and it worked, but still in [Compiler API Wiki](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API) example it used `import * as ts ...` maybe its outdated?

**Comment by jakebailey** [comment] 2023-12-30 07:46
The is a duplicate of #56366.

That code only works when in a TS file such that import helpers are in use. In native ESM in Node, you must write:

```ts
import ts from "typescript";
```

At some point, a namespace import used to cause Node to throw, but that is no longer true and I'm not sure why. Potentially we could update the wiki to use the default import for safety as that should work elsewhere.

**Comment by yxshv** [comment] 2023-12-30 07:58
it didn't work in the typescript file either

**Comment by jakebailey** [comment] 2023-12-30 08:17
Do you have esModuleInterop enabled?

**Comment by yxshv** [comment] 2023-12-30 12:45
> Do you have esModuleInterop enabled?

Oh yeah I do

**Closed** 2023-12-31 05:11 UTC
