### ISSUE TITLE
Node.cloneNode returns the wrong type

### ISSUE THREAD

**Issue by kkapsner** [Microsoft/TypeScript#17818] opened 2017-08-15 21:30 UTC
Node.cloneNode should return the type of "this". Therefore this line
https://github.com/Microsoft/TypeScript/blob/93abebc04af5d443a930ad84258cf2d6101d8513/lib/lib.es6.d.ts#L14166

should be 
```   cloneNode(deep?: boolean): this;```

**Comment by divyamamgai** [comment] 2017-08-28 19:31
Can I take this up as a starting point?

**Comment by mhegazy** [comment] 2017-08-28 23:48
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mhegazy** [comment] 2017-08-28 23:50
One thing to note, we do not want to add `cloneNode(deep?: boolean): this` as this will turn all HTMLElement* interfaces into generic interfaces and increase the cost of checking the standard library. instead we can update the generator to emit a `cloneNode` for every element to return the right type. see https://github.com/Microsoft/TSJS-lib-generator/pull/166 for guidance.

**Comment by HolgerJeromin** [comment] 2018-06-20 07:13
duplicate of the older ref #283

**Closed** 2018-07-05 17:09 UTC
Labels: Duplicate
