### ISSUE TITLE
Partial type inference failures with tagged union types

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#13754] opened 2017-01-30 13:53 UTC
Probably an example without the type guard of #13454.

**TypeScript Version:**  master

**Code**

```ts
declare function f<P, R, S>(process: Supervisor.Process<P, R, S> | Supervisor.Process.Call<P, R, S>): void;
namespace Supervisor {
  export type Process<P, R, S> = {
    readonly init: Process.Init<S>;
    readonly call: Process.Call<P, R, S>;
    readonly exit: Process.Exit<S>;
  };
  export namespace Process {
    export type Init<S> = (state: S) => S;
    export type Call<P, R, S> = (param: P, state: S) => [R, S] | PromiseLike<[R, S]>;
    export type Exit<S> = (state: S, reason: any) => void;
  }
}
f<void, void, void>({
  init: s => s,
  call: (p, s) => <[void, void]>[p, s],
  exit: s => void s,
});
```

**Expected behavior:**

ok

**Actual behavior:**

```
$ node built/local/tsc.js -t es6 index.ts --noImplicitAny
index.ts(16,10): error TS7006: Parameter 'p' implicitly has an 'any' type.
index.ts(16,13): error TS7006: Parameter 's' implicitly has an 'any' type.
```

**Comment by HerringtonDarkholme** [comment] 2017-01-30 15:18
It seems the problem comes from `call` in `Process` clashes with `call` in `Function`.

Smaller reproduction.

```ts
declare function f<P, R, S>(process: Process<P, R, S> | Call<P, R, S>): void;
type Process<P, R, S> = {
  readonly call: Call<P, R, S>;
};
type Call<P, R, S> = (param: P, state: S) => [R, S] | PromiseLike<[R, S]>;

f<void, void, void>({
  call: (p, s) => <[void, void]>[p, s],
});
```

Change the name from `call` to something like `kall` will resolve this.

**Comment by falsandtru** [comment] 2017-01-30 15:48
Oh it is a nice workaround! Thanks!

**Comment by falsandtru** [comment] 2017-01-31 12:41
I found a problem in this workaround. The overload should be:

```ts
declare function f<P, R, S>(process: Supervisor.Process.Call<P, R, S>): void;
declare function f<P, R, S>(process: Supervisor.Process<P, R, S>): void;
```

details: #13780

**Comment by mhegazy** [comment] 2017-05-25 22:47
looks like a duplicate of #13780

**Comment by mhegazy** [comment] 2017-05-25 22:49
The contextual type for the function is the union type. the union type property does not have a call signature because they are not identical. see https://github.com/Microsoft/TypeScript/issues/7294 for more details.

**Comment by mhegazy** [comment] 2017-06-09 17:14
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-06-09 17:14 UTC
Labels: Duplicate
