### ISSUE TITLE
Object literal: All `this` are implicitly any

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#12945] opened 2016-12-15 14:52 UTC
**TypeScript Version:**  nightly (2.2.0-dev.20161215)

**Code**

(with `--noImplicitThis`)

```ts
class C {
    a() {}
    b() {
        this.a();
    }
}

const obj = {
    a() {},
    b() {
        this.a();
    }
}
```

**Expected behavior:**

No errors.

**Actual behavior:**

`a.ts(11,9): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.`

**Comment by ahejlsberg** [comment] 2016-12-15 15:01
Duplicate of #12785.

**Closed** 2016-12-15 15:05 UTC
Labels: Duplicate
