### ISSUE TITLE
Order of type guards in &&-statement changes inferred type

### ISSUE THREAD

**Issue by harti768** [microsoft/TypeScript#39653] opened 2020-07-18 16:04 UTC
**TypeScript Version:**  3.5.3, 3.9.2, 4.0.0-beta

**Search Terms:** type guard, incorrect type

**Code**
```
function doSomething(value: unknown): object {
  
  if (value !== null && typeof value === 'object'){
    return value //value: object | null
  } 
  if (typeof value === 'object' && value !== null){
    return value //value: object
  } 
  return {}
}
```

**Expected behavior:**
The variable "value" is correctly narrowed down to object in both cases

**Actual behavior:**
The variable is narrowed down to "object | null" in the first case and to only "object" in the second case.

**Playground Link:** [test on playground](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABAEzgZTgWwKZQBYxgDmAFAG4CGANiNgFyLgDWYcA7mAJQNwBGAVtmiIA3gFgAUIkSTpMYInLVaiAIQBedYjAgqVRADIDiKAE8ADtjgLKNbIk1aA5H0HQnncVOmIATrhBfJFsVAHpQkPpEVyEoRAAfbV0qWUQAXxlveUUzS2tESIdNRBcBWKdDY0KNLR09T1TpfyhA4OV7cMieMuhUjNTm1tE0yRGJIA)

**Comment by MartinJohns** [comment] 2020-07-18 17:56
Duplicate of #28131. Used search terms: `narrow null object`

**Closed** 2020-07-21 18:00 UTC
Labels: Duplicate
