### ISSUE TITLE
Incorrect type inference when using spread operator with index signature and adding another prop

### ISSUE THREAD

**Issue by danmana** [microsoft/TypeScript#49920] opened 2022-07-15 09:04 UTC
# Bug Report

### 🔎 Search Terms

typescript spread wrong type inference

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (ex: 3.3.3-4.7.4)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.3.3&ssl=8&ssc=34&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgILIN4Chm+WYMAGwgC5kBnMKUAcxzwG0BPCOKckAVwFsAjaAF1OvAVCwBfLCTDI45dAF5MBYmWQByVBoA0yAEwAGI+QCM+gMwSA3FmkRZfZMozIAdB7hSZyBM8zunnpEcAJE5BpQEABuENwQGlJAA)

### 💻 Code

```ts
interface A {
    title: string
    [year: number]: number
}
let a: A = {title: 'A', 2020: 123};

let b = { ...a}
let c = { ...a, label: 'revenue'}
```

### 🙁 Actual behavior

```ts
// d.ts inference
declare let b: {
    [x: number]: number;
    title: string;
};
declare let c: {
    label: string;
    title: string;
};
```

### 🙂 Expected behavior

```ts
// d.ts inference
declare let b: {
    [x: number]: number;
    title: string;
};
declare let c: {
    [x: number]: number; // <--- this is missing
    label: string;
    title: string;
};
```

It seems that when I add an extra property to the spread object, it loses the `index signature` properties from the spread source.  
But, if I do not add any extra property it does infer correctly the type...

**Comment by MartinJohns** [comment] 2022-07-15 09:12
Duplicate of #27273. Used search terms: `spread index in:title`

**Closed** 2022-08-01 18:00 UTC
Labels: Duplicate
