### ISSUE TITLE
Polymorphic this for Static Methods

### ISSUE THREAD

**Issue by c1moore** [Microsoft/TypeScript#19788] opened 2017-11-07 00:15 UTC
## Background

I am attempting to write a polymorphic hierarchy of classes that involves abstract classes.  From a JS POV, the best way I have found to do this is by creating "pseudo-constructors".  These pseudo-constructors are static methods that (surprisingly) act as constructors.  These pseudo-constructors may look something like:

```javascript
function MyClass(param1, param2) {
	this.param1 = param1;
	this.param2 = param2;
}

MyClass.create = function create() {
	return new this('some default', 'another default');	
};

MyClass.createWithOptions = function createWithOptions(options) {
	/* Create and return new MyClass instance using options */
};

MyClass.createFromDatabase = function createFromDatabase(rawMyClass) {
	return new this(rawMyClass.param1, rawMyClass.param2);	
};
```

The use of the `this` keyword in the pseudo-constructors allows me to subclass `MyClass` and polymorphically use the pseudo-constructors as if they were real constructors.  For example,

```javascript
function MySubclass(param1, param2) {
	MyClass.call(this, param1, param2);

	/* Further setup for MySubclass */
}

MySubclassClass.createWithOptions = function createWithOptions(options) {
	/* Create and return new MySubClass instance using options */
};

MySubclass.createFromDatabase = function createFromDatabase(rawMySubclass) {
	let mySubclass = MyClass.createFromDatabase.call(this, rawMySubclass);

	/* Further setup for mySubclass using rawMySubclass elided */

	return mySubclass;
};
```

This notation is actually pretty powerful and flexible.  I can define different pseudo-constructors for the various number and types of arguments I would accept in a true OO language without the need for ugly conditional logic (like in a true OO language).  A similar approach is even used by [Node.js](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_array) (or at least they appear to be transitioning to this approach).

Transitioning to TypeScript, I _technically_ don't need to use this same approach since we have constructor overloading.  For example, I could do something like

```ts
class MyClass {
	constructor(param1 = 'some default', param2 = 'another default');
	constructor(param1: {/* options definition */});
	constructor(param1: any);
	constructor(param1: any, param2?: any) {
		/* Some messy type-checking and constructor logic omitted for simplicity. */
	}
}
```

However, you might see the problem already.  `param1` could be a `string`, an `options` object, or an object that represents raw data from the database.  Now, instead of calling the correct pseudo-constructor, which simply converts all of that information into the appropriate format and calls the real constructor, I have to add a ton of conditional logic (literally a ton, I weighed it).  As I'm sure you're aware, conditional logic == potential bugs == bad.  That's what's so great about polymorphism/OOP, it just works.

Ok, so I'm stuck with pseudo-constructors, but wait... what's that error?  "`Cannot create an instance of the abstract class 'MyAbstractClass'.`"  Come on!  Are you serious!?!

So, what if a tried redefining `this` by making it a parameter?  I don't get much further.  If I make the signature `createFromDatabase(this: typeof MyAbstractClass, rawData: any)`, I get the same error as above.  I _could_ change it to `createFromDatabase(this: new (/* MyAbstractClass constructor params) => MyAbstractClass)` (suggested [here](https://stackoverflow.com/questions/12802317/passing-class-as-parameter-causes-is-not-newable-error), not sure if it would _really_ work), but this limits the subclasses' constructors to use the same signature as `MyAbstractClass`.

## The Problem

**So here's the problem: I can't use true constructor overloading or pseudo-constructors.**  This means my constructors will (potentially) be larger than the rest of my class and (almost definitely) uglier than the JS equivalent.

## Potential Solutions

1. I'm sure this has been requested before, but true constructor/method overloading would be great.  It seems odd that TypeScript isn't already able to handle this natively given it should have enough information to do so.  A couple of potential solutions might be:
   - Name Mangling - change the name of the functions and define a single function that calls the correct mangled function based on the number of parameters and types passed to it.
   - Make TS handle the conditional logic - Same as above, but no need to create different functions, just create one where the conditional logic is handled automagically and the correct logic executed.
2. Allow `this` to refer to subclasses in the compiler.

## Similar Issues

This is a very similar issue to #5863; however, that issue appears to deal more with inheriting static methods and/or using `this` as a return type for static methods.

**Comment by aluanhaddad** [comment] 2017-11-07 01:04
Your factories or pseudo-constructors, as you call them, can work fine as static members.
```ts
class MyClass {
  classProperty = 0;

  static createFromDatabase<T extends MyClass>(this: new (...args: any[]) => T, databaseOptions: DatebaseOptions) {
    return new this(databaseOptions);
  }
}

class MySubclass extends MyClass {
  subclassProperty = 1;
}

MyClass.createFromDatabase({connectionString: '%'}).classProperty;

MySubclass.createFromDatabase({connectionString: '$'}).subclassProperty;

interface DatebaseOptions {
  connectionString: string;
}
```

**Comment by HerringtonDarkholme** [comment] 2017-11-07 02:33
Possible duplicate of https://github.com/Microsoft/TypeScript/issues/5863

**Closed** 2017-11-21 20:25 UTC
Labels: Question

**Comment by c1moore** [comment] 2017-11-30 16:24
Circling back to this finally.  While the behavior is a little quirky, especially with inheritance, that did solve my problem.  Thanks.
