### ISSUE TITLE
Error "Exported variable has or is using name... but cannot be named" not always suppressed by * imports

### ISSUE THREAD

**Issue by danielearwicker** [Microsoft/TypeScript#11534] opened 2016-10-11 15:48 UTC
**TypeScript Version:**  2.0.3

**Code**

See this repository: https://github.com/danielearwicker/tsrepro1

**Expected behavior:**
In `test5.ts` we don't get the error because we import `SomeType` explicitly.

In `test4.ts` we don't get the error because we import everything from the `source` module using `import * as...`

In the remaining three tests it seems we should not get the error, as we are doing the same thing as `test4.ts` except via various wrapper modules which import and re-export all the contents of the `source` module.

**Actual behavior:** 

In `test1` through `test3` we get:

```
Exported variable 'foo' has or is using name 'SomeType' 
from external module ".../source" but cannot be named.
```

For example `wrapper1` says:

``` ts
export * from "./source"
```

So it seems like what works with `source` should work with `wrapper1`.

**Comment by robyoder** [comment] 2016-11-22 19:49
#9944 is the same issue (I think), but this one more clearly describes my setup.

**Comment by mhegazy** [comment] 2016-11-22 20:39
I believe the original issue is a duplicate of https://github.com/Microsoft/TypeScript/issues/8612 and https://github.com/Microsoft/TypeScript/issues/5938 and

**Closed** 2017-04-21 16:56 UTC
Labels: Duplicate
