### ISSUE TITLE
The addition of a continue statement makes the compilation fail

### ISSUE THREAD

**Issue by dan-ros** [microsoft/TypeScript#51632] opened 2022-11-23 11:46 UTC
# Bug Report

The addition of a continue statement in a for loop make some code unreachable (see screenshots below).
After the addition of the continue statement the unreachable part of the code gives compilation errors. The errors are also highlighted in VS Code.
If no continue statement is present everything compiles without an error.

### 🔎 Search Terms

continue

### 🕗 Version & Regression Information

I saw the bug today, in tsc version 4.8.4

Please keep and fill in the line that best applies:
-->
- This is a crash

### 🙁 Actual behavior

Not working:
![non_working](https://user-images.githubusercontent.com/22822509/203538920-1dbb128d-f834-413f-a203-5cdc65e1b8f4.png)

Working
![working](https://user-images.githubusercontent.com/22822509/203538900-33b67783-b274-4b5b-bdce-89b13973674f.png)

### 🙂 Expected behavior

The addition of the continue statement shouldn't yield additional compilation errors, especially since they happen in unreachable code.

**Comment by fatcerberus** [comment] 2022-11-23 12:14
Because the code is unreachable, the type narrowing machinery essentially can’t see it.  Duplicate of https://github.com/microsoft/TypeScript/issues/26914

**Comment by dan-ros** [comment] 2022-11-23 12:18
Can't the type narrowing machinery be turned off for unreachable code?

**Comment by fatcerberus** [comment] 2022-11-23 12:24
> Can't the type narrowing machinery be turned off for unreachable code?

Well, in a way it already *is* - any existing narrowings get undone the minute the subsequent code is determined to be unreachable.  You probably meant to ask if *type checking* can be turned off, and while that’d be an option, there are reasons to keep it on - see https://github.com/microsoft/TypeScript/issues/26914#issuecomment-501376739.

Note that 26914 is tagged as a bug - it’s something they do want to fix, despite the current design limitations.

**Comment by jcalz** [comment] 2022-11-23 15:30
The bug report template asks for plaintext code and a Playground link.  A screenshot isn't appropriate for various reasons: you can't copy and paste it into an IDE without an image-to-text step; it's less accessible for visually impaired users who otherwise are able to code; et cetera.

Also, this isn't a crash. (Maybe the template should be edited to define the term?)  A crash is when the compiler itself fails to run, not when it merely reports warnings for the code it's compiling.  If the compiler were a professor and your code were an exam to be graded, it isn't a crash if you disagree with the grade.  A crash would be that the professor has a heart attack and dies while grading your exam.

**Comment by dan-ros** [comment] 2022-11-23 15:50
Thanks for your feedback. I suspected this was already reported in some way. If it would have turned out to be a new bug, I could have provided a playground link.

**Closed** 2022-11-23 15:53 UTC
