### ISSUE TITLE
add functionality  for supporting new native web api s

### ISSUE THREAD

**Issue by saeednoruzi** [microsoft/TypeScript#60728] opened 2024-12-10 16:54 UTC
### 🔍 Search Terms

add functionality  for supporting new native web api  

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

add functionality for supporting new native web api i get error when i try using new native web apis such as cookieStore navigation and etc it is so anoyying always geting errors there are planty native web api in mdn web api section

### 📃 Motivating Example

document.cookieStore.setCookie("my cookie","the path","expire date");

### 💻 Use Cases

document.cookieStore.setCookie("my cookie","the path","expire date");

**Comment by MartinJohns** [comment] 2024-12-10 16:57
Duplicate of #47314.

**Comment by uhyo** [comment] 2024-12-10 22:48
Not a duplicate of that issue; OP is asking for a general way of using a new Web API without waiting for TS implementing it. CookieStore is only an example.

However TS already allows you to use new APIs. You can define relevant types by yourself.

**Comment by MartinJohns** [comment] 2024-12-10 22:54
> OP is asking for a general way of using a new Web API without waiting for TS implementing it.

Then it's just: https://www.typescriptlang.org/docs/handbook/2/type-declarations.html

**Comment by saeednoruzi** [comment] 2024-12-13 13:59
i think those api that are mentioned in mdn and are not exprimenatl  should be implemened

**Closed** 2024-12-16 01:33 UTC
Labels: Duplicate
