### ISSUE TITLE
Complement operator

### ISSUE THREAD

**Issue by remojansen** [Microsoft/TypeScript#20189] opened 2017-11-21 12:08 UTC
Hi,

We are able to map from an object into a partial object using a mapped type. For example, given:

```ts
interface User {
    name: string;
    age: number;
}
```

We can map it using `Partial<T>`:

```ts
type PartialUser = Partial<User>;
```
The type `PartialUser` is equivalent to:

```ts
interface PartialUser {
    name?: string;
    age?: number;
}
```

But we are not able to map from a partial object to a non-partial object? For example, given:

```ts
interface PartialUser {
    name?: string;
    age?: number;
}
```
If would be nice to be able to map it into the following:

```ts
interface NotPartialUser {
    name: string;
    age: number;
}
```

Using a mapped type:

```ts
type NotPartialUser = NotPartial<PartialUser>;
```

To implement `NotPartial<T>` we need the complement operator? or there is a way to achieve this today?

The complement operator could look as follows. I don't really care about the syntax but here are some options:

```ts
type NotPartial<T> = {
    [P in keyof T]: T[P] ~ undefined;
};
```

```ts
type NotPartial<T> = {
    [P in keyof T]: T[P] \ undefined;
};
```

```ts
type NotPartial<T> = {
    [P in keyof T]: T[P] \\ undefined;
};
```

```ts
type NotPartial<T> = {
    [P in keyof T]: T[P] - undefined;
};
```

```ts
type NotPartial<T> = {
    [P in keyof T]: T[P] -- undefined;
};
```

This operator [exists in other programming languages](https://en.wikipedia.org/wiki/Complement_(set_theory)#Complements_in_various_programming_languages) but not always at the type system.

We have unions an intersections already. It seems reasonable to me to expect other set operations to be available but please let me know if I'm wrong and I'm missing something.

Thanks!

**Comment by remojansen** [comment] 2017-11-21 12:09
Duplicate of #10727 and #4183

**Comment by kitsonk** [comment] 2017-11-21 12:27
Duplicate of #15012

**Closed** 2017-11-21 12:59 UTC
