### ISSUE TITLE
2.3.1 TSX spread with union types

### ISSUE THREAD

**Issue by kryops** [Microsoft/TypeScript#15432] opened 2017-04-28 08:41 UTC
**TypeScript Version:**  2.3.1, 2.4.0-dev.20170427

**Code**

```ts
type Foo = { foo: string }
type Bar = { bar: string }
type Baz = { baz: string }

type FBB = Foo | Bar | Baz

declare const obj: FBB

const FbbComponent = (props: FBB) => (
    <div>{JSON.stringify(props)}</div>
)

const comp1 = React.createElement(FbbComponent, { ...obj }) // works
const comp2 = <FbbComponent {...obj as Foo} /> // works
const comp3 = <FbbComponent {...obj} /> // does not work
```

**Expected behavior:**

Compiles without errors

**Actual behavior:**
Error:
```
Type '{}' is not assignable to type '(IntrinsicAttributes & Foo) | (IntrinsicAttributes & Bar) | (IntrinsicAttributes & Baz)'.
  Type '{}' is not assignable to type 'IntrinsicAttributes & Baz'.
    Type '{}' is not assignable to type 'Baz'.
      Property 'baz' is missing in type '{}'.
```

**Comment by luca-moser** [comment] 2017-04-28 19:30
Similar problem here on 2.3.1:

```js
interface Props {
    ui?: UIState; session?: SessionState; scopes?: any;
    users?: any; roles?: any;
    plugins?: any;
    userAdjustablePlugins?: any;
    meta?: MetaSchemasState;
    uiActions?: UIActionsExecutor;
    userActions?: UserActionsExecutor;
    roleActions?: RoleActionsExecutor;
    pluginActions?: PluginActionsExecutor;
    userAdjustablePluginActions?: PluginActionsExecutor;
    sessionActions?: SessionActionsExecutor;
    scopeActions?: ScopeActionsExecutor;
    metaActions?: MetaActionsExecutor;
}

interface State {
    dataReady: boolean;
}

@connect((store) => {
...
}, (dispatch) => {
...
})
export class App extends React.Component<Props, State> {
}

```

Error:
```
ERROR in ./spa/js/comps/App.tsx
(120,49): error TS2322: Type '{ ui?: UIState; session?: SessionState; scopes?: any; users?: any; roles?: any; plugins?: any; us...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Content> & Props & { children?: ReactNode; }'.
  Property 'scopes' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Content> & Props & { children?: ReactNode; }'.
```

**Comment by mhegazy** [comment] 2017-04-28 23:18
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/14112, https://github.com/Microsoft/TypeScript/issues/15420, https://github.com/Microsoft/TypeScript/issues/13557, and https://github.com/Microsoft/TypeScript/issues/14409 fixed by https://github.com/Microsoft/TypeScript/pull/13288.

**Comment by mhegazy** [comment] 2017-05-19 16:47
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-05-19 16:47 UTC
Labels: Duplicate
