### ISSUE TITLE
Partial does not work well with generic guards

### ISSUE THREAD

**Issue by RReverser** [Microsoft/TypeScript#18072] opened 2017-08-27 13:51 UTC
**TypeScript Version:**  2.4.2

**Code**

(Note this is a simplified example and easy to workaround, but it gets dirtier in a real-world code)

```ts
type Obj<B> = { body: B };

function acceptPartial<O extends Obj<string>>(obj: Partial<O>) {}

function acceptFull<O extends Obj<string>>(obj: O) {
    acceptPartial<O>({
        body: obj['body']
    });
}
```

**Expected behavior:**

No type errors.

**Actual behavior:**

```
temp.ts(8,22): error TS2345: Argument of type '{ body: string; }' is not assignable to parameter of type 'Partial<O>'.
```

This doesn't make much sense because `{ body: obj['body'] }` is correctly determined as `{ body: string }` which is same as `Obj<string>`, and so compatible with `Partial<Obj<string>>` and any `Partial<O>` in this context.

Moreover, calling `acceptPartial<Obj<string>>` instead of `O` works which seems to mean that `Partial` doesn't currently "understand" that `Partial<O>` is just a superset of `Partial<Obj<string>>` when `O extends Obj<string>`.

**Comment by mhegazy** [comment] 2017-10-31 23:30
The core issue here is that this is not allowed:

```ts
var p: Partial<O> = { body: "" };
```
Since the compiler can not verify that `body` is not specialized in `O` further.

Duplicate of https://github.com/Microsoft/TypeScript/issues/19388

**Comment by RReverser** [comment] 2017-11-01 00:24
Well #19388 is newer so that one is technically a duplicate of this :P

**Closed** 2017-11-16 16:57 UTC
Labels: Duplicate
