### ISSUE TITLE
Suggestion: Support for some form of typing on catches

### ISSUE THREAD

**Issue by grofit** [Microsoft/TypeScript#18302] opened 2017-09-07 07:55 UTC
Within C# (and other languages) you can do typed error catching ([as seen here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch)) where you have a singular try with multiple catch statements per type you are wanting to handle.

I appreciate that this is not really an ES feature of any kind, and is quite niche but I would love for there to be some sort of helper syntax/convention for handling typed exceptions within typescript as currently I am refactoring a lot of promise code over to use async/await, which currently looks like:

```
doSomethingWhichReturnsPromise()
	.then(send(200))
	.catch(NotFoundError, (error) => { send(404); })
	.catch(SomeBadDataError, (error) => { send(400); })
	.catch(CantSeeThisError, (error) => { send(403); })
	.catch((error) => { send(500); })
```
Then in the new world it looks like this:

```
try
{
	await doSomethingWhichReturnsPromise();
	send(200);
}
catch(error)
{
	if(error instanceof NotFoundError) { send(404); } 
	else if(error instanceof SomeBadDataError) { send(400); } 
	else if(error instanceof CantSeeThisError) { send(403); } 
	else { send(500); } 
}
```

Which is ok but requires more code and is slightly less readable in some ways, so it would be great if there was some form of support for:

```
try
{
	await doSomethingWhichReturnsPromise();
	send(200);
}
catch(NotFoundError, error) { send(404); }
catch(SomeBadDataError, error) { send(404); }
catch(CantSeeThisError, error) { send(404); }
catch(error) { send(404); }
```

Which would output the previous bit, but as syntactic sugar, you could even do it as generics but its not as nice to read:

```
try
{
	await doSomethingWhichReturnsPromise();
	send(200);
}
catch<NotFoundError>(error) { send(404); }
catch<SomeBadDataError>(error) { send(404); }
catch<CantSeeThisError>(error) { send(404); }
catch(error) { send(404); }
```

So the idea is that there be *some* convention/syntax for you to basically have multiple catches for a singular try, and it be output as a singular catch which contains the `instanceof` checks for you (or a better approach to checking the type of an error).

This is mainly useful when doing API related interactions where you want to map contextual exceptions to generic http exceptions, and it just feels like the typescript rich typing system could make life slightly easier in this area.

**Comment by RyanCavanaugh** [comment] 2017-09-07 17:30
This should go to TC39 / es-discuss. We're really trying to not add new runtime sugar at this point

**Comment by mhegazy** [comment] 2017-09-07 18:39
Duplicate of https://github.com/Microsoft/TypeScript/issues/14191

**Comment by mhegazy** [comment] 2017-09-21 22:42
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-21 22:42 UTC
Labels: Duplicate
