### ISSUE TITLE
Properties in union type not type checking

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#22268] opened 2018-03-01 18:43 UTC
**TypeScript Version:**  2.7.2

**Search Terms:** 
union

**Code**

```ts
type Photo = { id: string };

type UserWithoutPhotos = {
    name: string;
};

type UserWithPhotos = UserWithoutPhotos & { photos: Photo[] };

const user: UserWithoutPhotos | UserWithPhotos = {
    name: 'foo',
    // Expected type error, but got none
    photos: 1
};
```

**Comment by andy-ms** [comment] 2018-03-01 19:04
Duplicate of #20863

**Closed** 2018-03-22 15:41 UTC
Labels: Duplicate
