### ISSUE TITLE
`Object.fromEntries` loses all types on the key

### ISSUE THREAD

**Issue by hfhchan** [microsoft/TypeScript#49305] opened 2022-05-30 04:49 UTC
# lib Update Request

## Configuration Check

My compilation *target* is `es2020` and my *lib* is `ES2020`.

## Missing / Incorrect Definition

````ts
fromEntries<T = any>(entries: Iterable<readonly [PropertyKey, T]>): { [k: string]: T };
````

should be

````ts
fromEntries<K extends PropertyKey, T = any>(entries: Iterable<readonly [K, T]>): { [k in K]: T };
````

## Sample Code
````ts
enum Period {
  M1 = '1m',
  M3 = '3m',
  M6 = '6m',
  Y1 = '1y',
  Y3 = '3y',
  Y5 = '5y',
  Y10 = '10y',
}

const list: [Period, moment.Moment][] = [
  [Period.M1, moment().subtract(1, 'month')],
  [Period.M3, moment().subtract(3, 'months')],
  [Period.M6, moment().subtract(6, 'months')],
  [Period.Y1, moment().subtract(1, 'year')],
  [Period.Y3, moment().subtract(3, 'years')],
  [Period.Y5, moment().subtract(5, 'years')],
  [Period.Y10, moment().subtract(10, 'years')],
];

const object: { [k in Period]: moment.Moment } = Object.fromEntries(list);
````

Returns error for object:
````
Type '{ [k: string]: Moment; }' is missing the following properties from type '{ "1m": Moment; "3m": Moment; "6m": Moment; "1y": Moment; "3y": Moment; "5y": Moment; "10y": Moment; }': "1m", "3m", "6m", "1y", and 3 more.ts(2740)
````

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries

## Notes

I've read the soundness issues discussion on Object.keys(), but I'm not seeing how that should/would apply to `Object.fromEntries()`.

Say if I am passing a [A, B][] into Object.fromEntries() where A is union of a class C and another enum D, I am going to get `C.toString()` | `D`. I am already hitting `fromEntries(entries: Iterable<readonly any[]>): any;` instead.

**Comment by hfhchan** [comment] 2022-05-30 05:05
See also: https://github.com/microsoft/TypeScript/pull/37457#issuecomment-1106615558

I just noted that this doesn't work because it's possible to omit a particular row in `list`, but the resulting type for `Object.fromEntries()` would generate an object that has all possible `Period`s as keys.

Apparently
````ts
fromEntries<K extends PropertyKey, T = any>(entries: Iterable<readonly [K, T]>): { [k: K]: T };
````
doesn't work either

**Comment by MartinJohns** [comment] 2022-05-30 05:32
Duplicate of #35745.

This is intentional. Objects are **not** sealed. It's very possible that you get properties with names not compatible with `PropertyKey`.

**Comment by hfhchan** [comment] 2022-05-30 06:11
Essentially a duplicate of #35745 but that issue has been closed without resolution.

**Comment by RyanCavanaugh** [comment] 2022-05-31 17:53
It wouldn't be correct to do this, because the type of an array tells you want *might* be in it, not what *is* in it. For example, `list` could be entirely empty, which would make `object`'s value be `{ }`, despite the type of `object` saying that it had a `M1` property.

**Closed** 2022-06-02 20:00 UTC
Labels: Working as Intended

**Comment by lbfalvy** [comment] 2024-01-09 16:59
Why not type it as `fromEntries<K, V>(entries: [K, V][]): {[k: K]?: V}`?
