### ISSUE TITLE
Infer type in conditional types

### ISSUE THREAD

**Issue by dardino** [microsoft/TypeScript#32990] opened 2019-08-20 13:53 UTC
**TypeScript Version:**  3.5.1

**Search Terms:**
conditional type inference
**Code**

```ts
function betterSort<T extends "t1" | "t2" >(
    t: T, 
    v: T extends "t1" ? string[] : number[]
): T extends "t1" ? string[] : number[] {
    switch (t) {
        case "t1":
            return v.sort((a,b) => a.toLowerCase() < b.toLowerCase() ? -1 : 1);   //  !!!   (A)
        case "t2":
        default:
            return v.sort((a,b) => a -b);   //  !!!   (B)
    }
}

betterSort("t1", ["hello", "hi"]); // OK > type of 2nd param is string[]
betterSort("t1", [0, 1]); // Error > Type 'number' is not assignable to type 'string'.

betterSort("t2", [0, 1]); // OK > type of 2nd param is number[]
betterSort("t2", ["hello", "hi"]); // Error > Type 'string' is not assignable to type 'number'.

```

**Expected behavior:**
The inferred type of var "v" in (A) must be Array<string> because the type of "t" is  "t1"
The inferred type of var "v" in (B) must be Array<number> because the type of "t" is  "t2"

**Actual behavior:**
The inferred type of var "v" in (A) and (B) is T extends "t1" ? string[] : T extends "t2" ? number[] : never

**Playground Link:** 

http://www.typescriptlang.org/play/?noImplicitAny=false#code/GYVwdgxgLglg9mABAIwKZSqgTgZTlqAHgBVFUAPTMAEwGdEAiKARgcQB9GoAmNgPgAUAKESjEUAFyJiAGkQixANymkKVOl1aIA-IlpQsMMAHMA2gF1EUsCAC2aLBaEBKFWUqoa9Jlt37DJhZWiDb22EEA3gqitADuMFAQABaIAlDOiFFi2YgQAIa0qJoMEtE52VjoIFhIigB0tPhQAgJ5MsgZALx8iHl1UHAAMnCx2ADCBagCGYQo-UMj45PTOogAtMzBzM4A3OWiZdn5hVy8pfuI1KjAeSAANpKH+5VQ1bUNTS1tHYjdvesoXZlAC+QlBQjQGGweAIAh8DDkpgYSVQdzucARjCSMAY5l2iAA9ATEAB5ADSiB6UAAngAHIpwYCIbg0RC0vJYPK2RAwej+IxmcwQ9CYXCfeGIgAMcmYeL2RMQAFEsFh8JTpHSigByUIOLU8+hgOBQXq0WgwYxgPLIO5FAbiTWILX8kxaupCYVQsWwpi8KUyuWE4nk9U0+mIRnM1nsznc3khOwOJyQ0Uw5q+zFIlFojFyZE4wMK5WqrDq4iO50GAX6+NGk0Fc2W6228RwB3hnWJ7Buj1CIA

**Related Issues:**

**Comment by jcalz** [comment] 2019-08-20 15:37
I think this is essentially a duplicate of #13995; generic type parameters simply do not get narrowed via control flow analysis.  Since `T` never gets narrowed to the concrete `"t1"` or `"t2"` inside the implementation, the type of `v` stays an unresolved conditional type, and so the compiler is not able to verify that what you are doing is safe.

You could use type assertions to suppress the error, or possibly refactor to use more concrete types inside your implementation like a union of [rest tuples](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#rest-parameters-with-tuple-types):

```ts
function betterSort<TV extends ["t1", string[]] | ["t2", number[]]>(
  ...tv: TV
): TV[1];
function betterSort(
  ...tv: ["t1", string[]] | ["t2", number[]]
): string[] | number[] {
  switch (tv[0]) {
    case "t1":
      return tv[1].sort((a, b) => (a.toLowerCase() < b.toLowerCase() ? -1 : 1));
    case "t2":
    default:
      return tv[1].sort((a, b) => a - b);
  }
}

betterSort("t1", ["hello", "hi"]); // OK > type of 2nd param is string[]
betterSort("t1", [0, 1]); // Error > Type 'number' is not assignable to type 'string'.

betterSort("t2", [0, 1]); // OK > type of 2nd param is number[]
betterSort("t2", ["hello", "hi"]); // Error > Type 'string' is not assignable to type 'number'.
```
[Playground](http://www.typescriptlang.org/play/?noImplicitAny=false#code/GYVwdgxgLglg9mABAIwKZSqgTgZTlqAHgBUA1RVAD0zABMBnRAbQCIoBGFgGkXqixhgA5kwC6oxAB9mbAEzdEYEAFs0WMaIB8ACgBQiRADpjUAG4AuRGV0BKS2SbtRAbl2hIsBCnSZc+KHoGxoZmlqwcCnwCwhpSMlDyPEqq2Bq2llGCIhLSyWpiiADe+rwA7jBQEAAWiNpmTAAMojZFJQYQAIb0qIhsnOZtBohY6CBYSPVOhvT+2todPMgtALyatR0hcAAycKXYAMJdqNothCibO3tYh90niAD8iAC07IiW7DY2rkOInd29CRYAx+tFQwA6IAANlBgT9hqNxohJqJprN5osVmsOs8UF8SgBfXSE3RoDDYPAEbR9BSsKqoSGQuAKFhVGAsZrORAAei5iAA8gBpRBrKAATwADj04MBELI6IhxR0sB1lIgYIxMjFRCSfOTZtSeI0eE4vtzeQBRLBYfDCqwSnoAcjy2AdasYYDgUEQXXoMCEYA6yEhPSgcCR9sQDs1Qgdhl0OrJfkpchpDWNHLN-KFIoj0tl8sVytV6sUKny2tJvgpARThpZ9MZzNZ7NNPMQlutWFtxAjUf4WVdJY9Xp9foDQZDYbFksjzqwsd0QA)

**Comment by dardino** [comment] 2019-08-22 19:34
Thank you for your solution, it is not possible to apply that solution in all cases but yes, in my case it works perfectly.

**Closed** 2019-09-05 18:24 UTC
Labels: Duplicate
