### ISSUE TITLE
Missing class name when use decorator

### ISSUE THREAD

**Issue by Brooooooklyn** [Microsoft/TypeScript#6132] opened 2015-12-17 13:09 UTC
```
const bar = (target: any, name: any, value: any) => {
  const parentName = target.constructor.name
  console.log(parentName)
}
class a {
  @bar
  public foo() {
  }
}
```

It works. *But*
```
const bar = (target: any, name: any, value: any) => {
  const parentName = target.constructor.name
  console.log(parentName)
 // it would be an empty string here!!!!!!!!
}
const log = (target: any) => {}

@log
class a {
  @bar
  public foo() {
  }
}
```
these code is ok when compile target was `ES5`, but missing class name when target was `ES6`

**Comment by mhegazy** [comment] 2016-01-07 19:27
duplicate of #5386

**Closed by mhegazy** 2016-01-07 19:27 UTC
Labels: Bug
