### ISSUE TITLE
Function names in source maps in async functions broken

### ISSUE THREAD

**Issue by mprobst** [microsoft/TypeScript#34977] opened 2019-11-07 16:01 UTC
**TypeScript Version:**  Version 3.8.0-dev.20191105

**Search Terms:** source map async function

**Code**

```ts
async function asyncMapped() {
  const trace = {stack: ''};
  (Error as any).captureStackTrace(trace);
  return trace;
}

function plainMapped() {
  const trace = {stack: ''};
  (Error as any).captureStackTrace(trace);
  return trace;
}

console.error(plainMapped().stack);

asyncMapped().then(s => {
  console.error(s.stack);
});
```

**Expected behavior:**

```
test.ts:14 Error
    at plainMapped (test.ts:9)
    at test.ts:14
(anonymous) @ test.ts:14
test.ts:16 Error
    at asyncMapped (test.ts:3)
    at step (test.js:32)
    at Object.next (test.js:13)
    at test.js:7
    at new Promise (<anonymous>)
    at __awaiter (test.js:3)
    at asyncMapped (test.ts:1)
    at test.ts:16
```

**Actual behavior:**

```
test.ts:14 Error
    at plainMapped (test.ts:9)
    at test.ts:14
(anonymous) @ test.ts:14
test.ts:16 Error
    at test.ts:3
    at step (test.js:32)
    at Object.next (test.js:13)
    at test.js:7
    at new Promise (<anonymous>)
    at __awaiter (test.js:3)
    at asyncMapped (test.ts:1)
    at test.ts:16
```

Note how there is no function name emitted for the asyncMapped version.

**Playground Link:** n/a

**Related Issues:**

Possibly https://github.com/microsoft/TypeScript/issues/13522 ?

**Comment by mprobst** [comment] 2019-11-07 16:02
I believe this is a regression introduced in TypeScript 3.5.

**Comment by rbuckton** [comment] 2020-12-16 01:51
This doesn't seem to be a regression, as nothing has really changed in the emit. The reason line 3 isn't source mapped is that the function you are evaluating doesn't have a name:

![image](https://user-images.githubusercontent.com/3902892/102293999-1aab1600-3efd-11eb-8a3a-cdf3e9c36248.png)

The best we could do is give it a name like `asyncMapped_1` so that we don't collide with possibly recursive calls of the function.

That is something we discussed in #13522, but the downside is that it adds additional text to the output for a function name that is never used except when debugging.

I'm going to close this as a duplicate of #13522, and we can continue discussion in the original bug.

**Closed by rbuckton** 2020-12-16 01:51 UTC
Labels: Bug, Rescheduled
