### ISSUE TITLE
structNullChecks doesn't detect undefined members of a class

### ISSUE THREAD

**Issue by e98cuenc** [Microsoft/TypeScript#9863] opened 2016-07-21 07:17 UTC
**TypeScript Version:**  2.0.0

**Code**

```ts
    class FooBar {
        bar: string;

    	foo() {
    	    console.log(this.bar.length); // at runtime: Cannot read property 'length' of undefined
        }
    }

    new FooBar().foo();
```

**Expected behavior:**

tsc should fail because `bar` can be undefined after the construction of FooBar.

**Actual behavior:** 

tsc compiles and you get an error at runtime.

**Comment by yortus** [comment] 2016-07-21 11:19
Duplicate of #8476

**Closed** 2016-07-21 19:51 UTC
Labels: Duplicate
