### ISSUE TITLE
Variable type incorrectly narrowed to null when a callback is passed to a function

### ISSUE THREAD

**Issue by tothdavid** [Microsoft/TypeScript#15380] opened 2017-04-25 21:14 UTC
**TypeScript Version:**  2.2.2
Compile with StrictNullChecks enabled.

**Code**

```ts
class Foo {
    public bar: string = "";
}

function test() {
    let foo: Foo | null = null;

    [1].forEach((item) => {
        foo = new Foo();
    });

    // Here Typescript compiler incorrectly thinks that 'foo' has null type 
    // although it will always be an instance of Foo class.
    if (foo) {
        // The next line does not compile because 'foo' variable has never type here.
        foo.bar;
    }
}
```

**Expected behavior:**
Should compile. 
**Actual behavior:**
Does not compile. The compiler incorrectly narrows the type of foo variable to null type as it seems to ignore the callback given to the forEach function call, which actually will always be called.

Notes:
The code compiles without StrictNullChecks just fine.
The below code works as expected, and I believe the same would be the expected behavior for the example code as well:
```ts
class Foo {
    public bar: string = "";
}

function test() {
    let foo: Foo | null = null;

    // When calling a simple lambda explicitly this works as expected
    (() => {
        foo = new Foo();
    })();
    if (foo) {
        foo.bar;
    }
}
```

**Comment by mhegazy** [comment] 2017-04-26 17:10
Duplicate of https://github.com/Microsoft/TypeScript/issues/10982 and https://github.com/Microsoft/TypeScript/issues/10613. See https://github.com/Microsoft/TypeScript/issues/9998 for relevant discussion.

**Closed** 2017-04-26 17:10 UTC
Labels: Duplicate
