### ISSUE TITLE
[VS2015] Intellisense opens when typing "(" within a string

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#3936] opened 2015-07-20 19:55 UTC
in VS2015 (beta and release) when editing a string, if I type an open parenthesis the intellisense function signature pop-up opens.

e.g.
```
console.log("hello"); 
```
editing in `"hello("` causes `log([message: any)` to be displayed.

**Comment by DanielRosenwasser** [comment] 2015-07-20 20:41
This is a duplicate of #1150 but I would strongly favor reopening that issue.

**Closed** 2015-07-20 20:52 UTC
Labels: Bug, Duplicate
