### ISSUE TITLE
Incorrect type inference of 'unknown'

### ISSUE THREAD

**Issue by rav2040** [microsoft/TypeScript#38051] opened 2020-04-20 02:08 UTC
**TypeScript Version:**  3.8.3

**Search Terms:**
unknown, null, incorrect, conditional, type inference

**Expected behavior:**
There should not be an error when using a conditional to correctly narrow down an `unknown` variable to a variable of type `object`.

**Actual behavior:**
Given a variable `foo` of type `unknown`, it is correctly inferred to be of type `object` when the following are both `true`:
1. `typeof foo === 'object'`
2. `foo !== null`

However, when the order is swapped, the type of `foo` is incorrectly inferred to be of type `object | null`.

**Related Issues:**
Could not find related issues.

**Code**
```ts
const foo = {} as unknown;

let bar: object;

if (typeof foo === 'object' && foo !== null) {
    bar = foo; // type of 'foo' is correctly inferred to be 'object'
}

if (foo !== null && typeof foo === 'object') {
    bar = foo; // type of 'foo' is incorrectly inferred to be 'object | null'
}

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const foo = {};
let bar;
if (typeof foo === 'object' && foo !== null) {
    bar = foo; // type of 'foo' is correctly inferred to be 'object'
}
if (foo !== null && typeof foo === 'object') {
    bar = foo; // type of 'foo' is incorrectly inferred to be 'object | null'
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=3.8.3#code/MYewdgzgLgBAZiEMC8MDeBfGBDCMCuYA1mCAO5gDcAsAFB0A2AprAEbYBOAXDCKwFZNgUGvVoBLODAAUUAJ4AHJiCkIkyDTADkfQcK0wAZIfiIYAQk1h8DBgEp0dGM5jsOKUyEowA9D5jySrxSWmoG4nigHBxCUAxyMOJgcEzRTAAmAUisTNq6sVp0GHR0kjJqFlY2DEYmgcqqZhqoOgIFDmhOLm4eat5+AYq5KtphiXhJUTHC8YnJqTGZUNm5rXqwAD4w1raFtMW0QA)

**Comment by MartinJohns** [comment] 2020-04-20 06:58
Duplicate of #37658.

**Closed** 2020-04-22 18:00 UTC
Labels: Duplicate
