### ISSUE TITLE
statically typed array not reporting error

### ISSUE THREAD

**Issue by a8775** [Microsoft/TypeScript#13264] opened 2017-01-03 10:23 UTC
**TypeScript Version:**  2.1.4 

**Code**

```ts
let easy1: [string, string] = ["value1"]; // this is an error
let easy2: [string, string] = ["value1", "value2"]; // this is ok
let easy3: [string, string] = ["value1", "value2", "value3"]; // could it be an error?
```

**Expected behavior:**
Could the third statement be marked as an error?

The example above could be scaled to the following example as well:

```ts
let myArray: [string, string][] = [["key1", "value1"], ["key2", "value2"]];

let vx = myArray[0][2]; // could it be marked as an error?
```

**Actual behavior:**
Third statement is treated as correct.

**Comment by aluanhaddad** [comment] 2017-01-03 12:39
Possible duplicate of https://github.com/Microsoft/TypeScript/issues/6229

**Closed** 2017-02-28 00:28 UTC
Labels: Duplicate
