### ISSUE TITLE
Switch not performing exhaustive check when a default with unreachable assert is specified

### ISSUE THREAD

**Issue by fcole90** [microsoft/TypeScript#45415] opened 2021-08-11 17:16 UTC
# Bug Report

### 🔎 Search Terms
`is:issue is:open exhaustive switch `

### 🕗 Version & Regression Information

- This is the behaviour in every version I tried, and I reviewed the FAQ for entries about `switch` exhaustiveness and I didn't find anything about this.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210811#code/MYewdgzgLgBAhhCBTATlAqmFS7ABZwBGANkjALwwAUAHgFwxhIBuqAlA06yhQHwwBvAFAxRMKHhQgA7oySyAoiikoqAIkzZcBEmVAATJGrZCAvkKEB6SzAAqeAJYQYTmAHkA0jABmIHhL0QAFsABwdSFCFQSFgkGgIAV2gHVgAxBLBgKAdwACUkKASUME8KamY4YgSkBjU4NRgAHxg1QmNOBKDCVD5BETEIaQcofCoKqqQ2PrEZmGAEMjq1On7Z2exC4pgABlXZ+eQWtpW1tY2isBgARj3zcysbe1dXOEuFXNy3XJ8-cTxA0LhVArawwfjpTLZcAwYi4ADWziQYH0DjAAHMYOcttA4FAkEEkbBXvpMQULuIAJ4hMj6EBIZxgECwVHAKqGGAAcgyhm8qKQ+g5ADoqAAmADMADYJSZotAYHFEsk0hksjkwABZJzICD5TaXShjSrVWr1JpHdqMTrdHjkfjCGaDYajcbVKb204HRb1E6nGZYy67X2e80+32if3XPYzHlwBLEKChsMIZBoTQ4fBEUiGiYmGZ3IA)

### 💻 Code

```ts
const assertUnreachable = (x: never): never => {
    throw new Error("Unreachable code")
}

// This is OK for the compiler
const exhaustiveFunctionReturnOK = (value: "a" | "b"): number => {
    switch(value) {
        case "a":
            return 0
        case "b":
            return 1
    }
}

// This is an ERROR for the compiler:
// > Function lacks ending return statement and return type does not include 'undefined'.(2366)
const exhaustiveFunctionMissesReturn = (value: "a" | "b"): number => {
    switch(value) {
        case "a":
            return 0
        case "b":
            return 1
        default:
            assertUnreachable(value)
    }
}

// I think both should be OK instead
```

### 🙁 Actual behavior

I have a function with a parameter which is a string union (e.g. `value: "a" | "b") and a return of some type (e.g. `number`). I want to perform an exhaustive `switch` to decide what `number` to return based on the value, if it's `"a"` or `"b"`. The compiler correctly identifies that the branches match all the possible values (exhaustive), so it's happy and compiles. 

However, if I add a `default` branch, with an unreachable assert of type `never`, then the compiler complains that I'm missing a return of type `number`. This seems weird to me, given that the reason for the assert itself is exactly to ensure that such a branch is actually unreachable, and hence every option of the `switch` is exhausted.

### 🙂 Expected behavior

Both behaviours to work and the compiler to understand that a default branch with an unreachable-code assertion is not going to happen and behave like in the case without such a branch, inferring that the only possible return type is `number` (or whatever type the function is returning).

**Comment by fcole90** [comment] 2021-08-11 17:19
Possibly related issue: https://github.com/microsoft/TypeScript/issues/36884

**Comment by fcole90** [comment] 2021-08-11 17:25
Other possibly related issue: https://github.com/microsoft/TypeScript/issues/12825

As for [this comment](https://github.com/microsoft/TypeScript/issues/12825#issuecomment-472217983) a workaround is to return the `assertUnreachable(x: never)`, like this:

```ts
// Now the compiler doesn't complain anymore
const exhaustiveFunctionMissesReturn = (value: "a" | "b"): number => {
    switch(value) {
        case "a":
            return 0
        case "b":
            return 1
        default:
            return assertUnreachable(value)
            //  ^ Note this "return" was added
    }
}
```

**Comment by MartinJohns** [comment] 2021-08-11 18:15
Duplicate of #12825.

**Closed** 2021-08-15 18:00 UTC
Labels: Duplicate
