### ISSUE TITLE
Can't narrow on discriminant when multiple values map to a type

### ISSUE THREAD

**Issue by xirzec** [microsoft/TypeScript#37555] opened 2020-03-24 20:33 UTC
**TypeScript Version:**  3.8.3

**Search Terms:** discriminant, narrowing

**Expected behavior:**

Else block has narrowed the type when it's not possible for any other subtype to be present.

**Actual behavior:**

Else block can only narrow if a user defined type guard is used or if there is only a single value for a particular subtype (e.g. Complex only had one string value)

**Related Issues:**

#33546

**Code**
```ts
type Simple = "string" | "boolean";
type Complex = "complex" | "verycomplex";

interface SimpleThing {
    type: Simple;
    searchable?: boolean;
    sortable?: boolean;
}

interface ComplexThing {
    type: Complex;
    fields: Thing[];
}

type Thing = SimpleThing | ComplexThing;

function test(arg: Thing) {
    // this does not work, but a manual type guard for "is ComplexThing" does work
    if (arg.type === "complex" || arg.type === "verycomplex") {
        return arg;
    } else {
        // this should work, but arg is still typed as Thing
        arg.searchable
    }
}
```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/#code/C4TwDgpgBAyglgWzAG2gXigIgM7AE5wB2A5plAD5YBGA9jagIaGYDcAsAFCiRQDCNSVAA8oGTAGMBKCELKVMANwh4QkwTNadORYMoBmDcdHjqAKgAsixKAG9OUB1G4QAXLETT2HR1GwQGeOLmDFSoAPxutPT+hF4+2DR4wCHhkXSMsZwAvlocOvqG0PzqQhZWtvaOzm7F0kJxjnpwEMgAJthuZSQA2gC6XjkcnM5QXdYYJtJjFHxSwmNenHoAroTiwHA0hE4QuAAUAcSdliQAlBXejnB6UAd4xAB0I2gvWGp1cpSHT+Dor4rKVRzDTnOyXHwOPAQYDLPDbQ4NBxZKAtPwXCGOAD0mKclmwvnMNGWbSgAHdEgBrSoY75+AJBFIQalQQaDThAA)

**Comment by ahejlsberg** [comment] 2020-04-28 03:52
This is effectively a duplicate of #32748, though written slightly differently. The suggested fix in #32748 applies here as well, just declare individual interfaces for each of the discriminants.

**Closed** 2020-04-30 18:00 UTC
Labels: Duplicate
