### ISSUE TITLE
Multicore --build

### ISSUE THREAD

**Issue by natew** [Microsoft/TypeScript#30900] opened 2019-04-12 21:32 UTC
## Search Terms

Multicore build

## Suggestion

I see an [old issue that was closed](https://github.com/Microsoft/TypeScript/issues/12987) but realize that was from before `-b` exists. It makes sense now with `-b` to support multi-core, it seems.

## Use Cases

Much faster initial builds.

**Comment by DanielRosenwasser** [comment] 2019-04-12 23:22
Duplicate of #30235

**Closed by DanielRosenwasser** 2019-04-12 23:22 UTC
Labels: Duplicate
