### ISSUE TITLE
add codefix for extracting method/function 

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#13081] opened 2016-12-21 02:52 UTC
for any valid block of code inside a method, provide a way to extrac it to an instance or better yet a static method

same for a valid block inside a function to be taken out to another function

**Comment by mhegazy** [comment] 2016-12-21 18:39
Duplicate of https://github.com/Microsoft/TypeScript/issues/4985

**Closed by mhegazy** 2016-12-21 18:39 UTC
