### ISSUE TITLE
Conditional type not narrowed by control flow

### ISSUE THREAD

**Issue by PaperStrike** [microsoft/TypeScript#45766] opened 2021-09-07 09:44 UTC
# Bug Report

### 🔎 Search Terms

conditional guard, conditional flow

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about conditional types.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0&ts=4.4.2#code/C4TwDgpgBACghgYwNZwOYQGIHsBOGCuAdgsAJZaEDOAPACoB8UAvFLVBAB7ASEAmlUAsTIUoAfigAKHBACO+UjN4AuKMBz4IASmaM2q2gG4AsACgzCCpWBR0wAPI5SqUoTgAbZlDr1JANw9NVXhkNExcIRJyKh8tA10oAG8zKFSoAHp0qABlAAssfHdeNVycLAB3KDhCdhwynCqBYFzoGXlFCGKwOBw4AFsoUgEAA3VNYYA6FLTSADMpUEgseYD3TWYmFgByWaIoii2dGWB8HBrVzUlZj0ptE1M0jKy8gqKoQiwbZrLKiDrcRqDGx9fDWKAAI2gw1ow3eFSmDzSx1O50CEHuAF97kA)

### 💻 Code

```ts
type PackageForFunctions<T> = T extends Function ? (required: true) => T : T;

const getOriginal = <T>(value: PackageForFunctions<T>): T => {
  if (typeof value === 'function') return value(false);
  return value;
};
```

### 🙁 Actual behavior

- No error on `value(false)`. Wrong for `value` can only be a function when it is `(required: true) => T`.
- Error "`not assignable to type 'T'`" in the last return. Wrong for `value` must be `T` if it is not a function.

### 🙂 Expected behavior

- Throw an error as the required param is `true` on `value(false)`.
- No error in the last return as it must be `T` at that line.

**Comment by jcalz** [comment] 2021-09-07 11:27
Duplicate of #33912

**Closed** 2021-09-08 14:21 UTC
Labels: Duplicate
