### ISSUE TITLE
Incorrect type for Set.prototype.values().next Iterator

### ISSUE THREAD

**Issue by vezaynk** [microsoft/TypeScript#53223] opened 2023-03-12 21:54 UTC
# Bug Report

Default iterator `TReturn` type is `any`. This causes code which works with iterators without a defined `TReturn` type to return `any` when getting `next().value`.

```ts
const set1 = new Set<string>();

// Should be `string | undefined` but is `any`
const e1 = set1.values().next().value;
//    ^?
```

[Playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBBCmUCMMC8MzwO4wMqIB5oAnASzAHMA+ACgEoBuAWAChWB6dvACxAFcANgBMYAI3gwABiXIUYAHxh8wQ+ADNy8IZLF9YpCFICGYAJ6TWoSLHgp0CZADoAbkYF94Eeo8wAPKN6u7vDMLJwwETAAegD8QA)

### 🔎 Search Terms

iterator, set, treturn, next any

### 🕗 Version & Regression Information

- This is the behavior in every version I tried. Seems like it was introduced in #30790

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBBCmUCMMC8MzwO4wMqIB5oAnASzAHMA+ACgEoBuAWAChWB6dvACxAFcANgBMYAI3gwABiXIUYAHxh8wQ+ADNy8IZLF9YpCFICGYAJ6TWoSLHgp0CZADoAbkYF94Eeo8wAPKN6u7vDMLJwwETAAegD8QA)

### 💻 Code

```ts
const set1 = new Set<string>();

// Should be `string | undefined` but is `any`
const e1 = set1.values().next().value;
//    ^?
```

### 🙁 Actual behavior

`e1` should be `string | undefined`

### 🙂 Expected behavior

`e1` is `any`

**Comment by whzx5byb** [comment] 2023-03-13 02:12
Duplicate of https://github.com/microsoft/TypeScript/issues/33353

**Closed** 2023-03-13 17:26 UTC
