### ISSUE TITLE
typecheck dictionary-key access

### ISSUE THREAD

**Issue by devdoomari3** [microsoft/TypeScript#35264] opened 2019-11-21 10:50 UTC
## Search Terms

Dictionary, key, strictness

## Suggestion

add a stricter typechecking for dictionary key-access.

Suppose we have a dict:

```
const someDict: {
  [key: string]: SomeValueType
}  = { ... }
```

Now, the type of `const someValue = someDict[someKey]` is `SomeValueType`. \
But `someDict[someNonexistingKey]` results in `undefined` at runtime.

So the proposal is to make `someDict[someKey]` to be `someType | undefined` instead of `someType`

## Background
with TS 3.7+, a stricter dictionary-key typecheck access can be ergonomic enough using optional chaining.
Before, a stricter dictionary-access means requiring TS-users to do:
```
someDict[someKey] && someDict[someKey].someProp // ... and so on
```
so it wasn't feasible to do strict-dictionary-access typechecking.

But now, with TS optional chaining, we can do:
```
someDict[someKey]?.someProp?. // and so on.....
```

so it's quite ergonomic enough, and adheres more to the actual runtime behavior: \
`someDict[someInvalidKey]` is `undefined` at runtime

## Checklist

('I don't know much about these... I'll edit this checklist later)

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

ps: yay optional chaining! 🎉

**Comment by MartinJohns** [comment] 2019-11-21 11:17
Duplicate of #13778.

**Comment by AnyhowStep** [comment] 2019-11-21 11:19
What would happen to this pattern of access?

```ts
for (const key of Object.keys(someDict)) {
  //Realistically, this will always be `T`,
  //if `someDict` is `Record<string, T>`
  someDict[key];
}
```

**Comment by devdoomari3** [comment] 2019-11-21 12:13
@MartinJohns hm that looks similar! sorry if this is a duplicate (I searched through the issues / google though 😱 )

@AnyhowStep

```
for (const key of Object.keys(someDict)) {
  //Realistically, this will always be `T`,
  //if `someDict` is `Record<string, T>`
  someDict[key];
}
```
the inconveniences are somewhat alleviated by optional-chaining (`?.`).
And as you mentioned dependent-types, another way is to make nominal-key types with some big changes on the dict type that might look like:

```
type someDict = {
  [key: string]: someItem,

  // could be implicit? 
  [key: keyof_someDict<string>]!: someItem, // `!` is for "this 100% exists"
                                                                            //   maybe `someItem!` ?
}
```

and `keyof someDict` should be given nominal types:
```
keyof_someDict<'a'>, keyof_someDict<'b'>, ...
```

so `key`s in `for (const key of Object.keys(someDict))` will be of type `keyof_someDict<string>`

-----

as for `hasOwnProperty`, I don't mean to make this 100%-safe. Just more-stricter checks.

To be safe from hasOwnProperty, TS might need "any string except 'A'" kind of type:
```
{
  [key: stringWithout<'hasOwnProperty' | 'prototype' | ....>]: someItem,
  hasOwnProperty: ...
}
```

anyway, I should probably read the original issue+comments for more ideas...

**Comment by fatcerberus** [comment] 2019-11-21 21:37
> the inconveniences are somewhat alleviated by optional-chaining (?.).

Somewhat, but not entirely.  In cases where you know you have a valid key (e.g. `Object.keys`), `?.` adds branch costs at runtime (which could be a performance issue) just to satisfy a type system which has no runtime presence.  Not a fair tradeoff IMO, and without dependent types like @AnyhowStep mentioned, there's no reasonable way to distinguish the safe and unsafe keys at compile time.

See comment here re: safe and unsafe keys: https://github.com/microsoft/TypeScript/issues/13778#issuecomment-286859503

**Closed** 2019-11-24 18:00 UTC
Labels: Duplicate
