### ISSUE TITLE
Allow decorators to change input value

### ISSUE THREAD

**Issue by CodySchaaf** [Microsoft/TypeScript#5647] opened 2015-11-13 02:55 UTC
Right now while using decorators the javascript seems to work, but the types are too strict.

As you can see [here](http://www.typescriptlang.org/Playground#src=declare%20var%20_%3A%20any%3B%0Aexport%20function%20Throttle(milli%3A%20number)%20%7B%0A%09interface%20Throttled%20extends%20Function%20%7B%0A%09%09%09now%3A%20Function%0A%09%7D%0A%09return%20function%3CT%20extends%20Throttled%3E(target%3A%20Object%2C%20propertyKey%3A%20string%2C%20descriptor%3A%20TypedPropertyDescriptor%3CFunction%3E)%3A%20TypedPropertyDescriptor%3CT%3E%20%7B%0A%09%09%09let%20originalMethod%20%3D%20descriptor.value%3B%0A%09%09%09%2F%2F%20NOTE%3A%20Do%20not%20use%20arrow%20syntax%20here.%20Use%20a%20function%20expression%20in%0A%09%09%09%2F%2F%20order%20to%20use%20the%20correct%20value%20of%20%60this%60%20in%20this%20method%0A%09%09%09descriptor.value%20%3D%20%3Cany%3E_.throttle(function()%20%7B%0A%09%09%09%09originalMethod.apply(this%2C%20arguments)%3B%0A%09%09%09%7D%2C%20milli)%3B%0A%09%09%09(%3CThrottled%3Edescriptor.value).now%20%3D%20%3Cany%3Efunction()%20%7B%0A%09%09%09%09originalMethod.apply(this%2C%20arguments)%3B%0A%09%09%09%7D%3B%0A%09%09%09return%20%3CTypedPropertyDescriptor%3CT%3E%3Edescriptor%3B%0A%09%09%7D%0A%7D%0A%09%0A%0A%0A%09class%20Ctrl%20%7B%0A%0A%09%09constructor(scope%3A%20any)%20%7B%20%0A%09%09%20%20%20%20scope.%24watch(%22foo%22%2C%20this.throttledByClassWatch)%3B%0A%09%09%09this.throttledByClassWatch.now()%20%2F%2Funrecommended%20now%20call%0A%09%09%7D%0A%09%09%40Throttle(100000)%0A%09%09private%20throttledByClassWatch()%20%7B%0A%09%09%7D%0A%09%7D%0A) the following does not compile:

```ts

declare var _: any;
export function Throttle(milli: number) {
	interface Throttled extends Function {
			now: Function
	}
	return function<T extends Throttled>(target: Object, propertyKey: string, descriptor: TypedPropertyDescriptor<Function>): TypedPropertyDescriptor<T> {
			let originalMethod = descriptor.value;
			// NOTE: Do not use arrow syntax here. Use a function expression in
			// order to use the correct value of `this` in this method
			descriptor.value = <any>_.throttle(function() {
				originalMethod.apply(this, arguments);
			}, milli);
			(<Throttled>descriptor.value).now = <any>function() {
				originalMethod.apply(this, arguments);
			};
			return <TypedPropertyDescriptor<T>>descriptor;
		}
}
	


	class Ctrl {

		constructor(scope: any) { 
		    scope.$watch("foo", this.throttledByClassWatch);
			this.throttledByClassWatch.now() //unrecommended now call
		}
		@Throttle(100000)
		private throttledByClassWatch() {
		}
	}

```

I might have the types a little wrong but I have tried many other permutations. It seems to be because the expected type is `declare type MethodDecorator = <T>(target: Object, propertyKey: string | symbol, descriptor: TypedPropertyDescriptor<T>) => TypedPropertyDescriptor<T> | void;` and so the input T must match the output T.

Ideally the `now` could also inherit the generic type `T` so it could be type checked.

**Comment by mhegazy** [comment] 2015-11-13 05:07
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/4881. you might find my comment in https://github.com/Microsoft/TypeScript/issues/5627#issuecomment-155955170 helpful as a work around ins some cases, though would not work in your sample.

**Closed by mhegazy** 2015-11-13 05:07 UTC
