### ISSUE TITLE
TypeScript language service breaks down when wrong casing is used for imports

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#5430] opened 2015-10-28 08:35 UTC
Copied from: https://code.visualstudio.com/Issues/Detail/20178

I was experiencing a bizarre issue where the TS language service broke down and wouldn't underline errors in my code. After pulling my hair out for half an hour, I figured out it was because I was doing a file import with the wrong case e.g.

import Engine from "./Engine"

instead of

import Engine from "./engine"

The default class exported was named 'Engine' which I think might have also had something to do with it.

Open the attached folder in VS Code, then pick the "engine.ts" file and notice that there is an undefined symbol ("jjj_this_is_an_error") that is not red underlined.

I would expect a better error on the erroneous import instead of the imported file no longer having proper language services. :)

**Comment by mhegazy** [comment] 2015-10-28 16:08
looks like #5149.

I do agree a better experience is needed here.

**Comment by mhegazy** [comment] 2015-10-28 16:09
@vladima, what can we do here?

**Comment by mhegazy** [comment] 2015-10-28 17:04
thanks to @vladima, this is not a duplicate, this is a bug in tsserver. fix queued.

**Comment by mhegazy** [comment] 2015-10-28 17:11
The issue is that tsserver was using a case sensitive map to store files, so looking up a file with a different case did not work. this should be fixed in TS 1.7, by #5436.

Now ideally, you would want a warring if you reference a module with the wring case, for this use the new flag `--forceConsistentCasingInFileNames` added in #5275, to check that you always reference the  same file using consistent naming this will be available in TS 1.8.

**Closed** 2015-10-28 20:48 UTC
Labels: Bug, Fixed

**Comment by xirzec** [comment] 2015-10-29 22:20
@mhegazy Thanks for the quick fix! :+1:
