### ISSUE TITLE
JSON.stringify(undefined) has wrong type

### ISSUE THREAD

**Issue by locriacyber** [microsoft/TypeScript#48492] opened 2022-03-30 22:57 UTC
# lib Update Request

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Missing / Incorrect Definition

- `JSON.stringify`

## Sample Code

This will type check but shouldn't.
```
const s: string = JSON.stringify(undefined)
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description

**Comment by whzx5byb** [comment] 2022-03-30 23:04
Duplicate of https://github.com/microsoft/TypeScript/issues/18879

**Closed** 2022-04-02 18:00 UTC
Labels: Duplicate
