### ISSUE TITLE
It is unclear to me how tsconfig.json is used in Visual Studio 2015

### ISSUE THREAD

**Issue by Gitgiddy** [Microsoft/TypeScript#3983] opened 2015-07-22 20:27 UTC
It is unclear to me how tsconfig.json is used in Visual Studio 2015.  And what happens when the TypeScript panel in the Project Properties conflicts?  Does switching to use tsconfig.json kill features like Save-On-Compile?

**Comment by mhegazy** [comment] 2015-07-22 20:59
Sorry for the confusion.. we are working on cleaning this up. An easy way to think of this, is a project file (.csprox, .jsproj, .vbproj or .njsproj) and a tsconfig.json are mutually exclusive. if you have a project file the tsconfig is ignored. if you want to use a tsconfig file, do not use a project.

In the future, i would see us adding an option in the project property pages to allow you to use tsconfig or not, and if so, the project property pages will all be grayed out..

**Comment by paulvanbrenk** [comment] 2015-07-22 22:46
tsconfig.json is only supported in Asp.net 5 and Cordova projects currently. Since neither has a Project Properties for TypeScript they won't conflict, and tsconfig.json will take precedence. 

To enable Compiler on Save, you need to enable Compile on Save for files that are not part of a project, in the Tools/Options/Text Editor/TypeScript.

We plan to have more comprehensive support in 1.6.

**Comment by paulvanbrenk** [comment] 2015-08-12 22:58
Closing this as by design, using #4161 to track this.

**Closed by paulvanbrenk** 2015-08-12 22:59 UTC
Labels: Bug

**Comment by ltlombardi** [comment] 2018-01-14 15:13
Jan 2018, this is still a issue. Every single official documentation and blog talks about tsconfig.json file, and nothing about how to configure the same in the project.
For example: 
https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

**Comment by mhegazy** [comment] 2018-01-16 19:03
@ltlombardi i am not sure i understand your issue. this issue has been closed over 3 years ago. Please file a new issue, and include enough context for use to investigate

**Comment by ltlombardi** [comment] 2018-01-16 19:07
@mhegazy thank you. ;-)  I'll do that
