### ISSUE TITLE
Erases Type Parameter for Generic Class Expression in Type Declarations

### ISSUE THREAD

**Issue by swissmanu** [Microsoft/TypeScript#18502] opened 2017-09-15 15:17 UTC
**TypeScript Version:**  2.5.2

**Code**

```ts
// Replicate React Component Type Structure:
class Component<P = {}, S = {}> {
    props: P;
}
interface ComponentClass<P = {}> {
    new (props?: P): Component<P>;
}

// Define Factory for Higher Order Component:
interface HOCState {}
function hocFactory<P>(WrappedComponent: ComponentClass<P & HOCState>) {
	return class HigherOrderComponent extends Component<P, HOCState> {
        // pass HOCState content as props to WrappedComponent instance
    }
}

// Apply Factory:
const AugmentedComponent = hocFactory(
    class ComponentToWrap extends Component<{} & HOCState> {}
);
```

**Expected behavior:**

Type declaration for `AugmentedComponent` should not erase definition for type parameter `P`.

Referring to the code snippet below, line 15 should read `new <P>(): {`.

**Actual behavior:**

TypeScript 2.5.2 generates following type declaration:

```typescript
declare class Component<P = {}, S = {}> {
    props: P;
}
interface ComponentClass<P = {}> {
    new (props?: P): Component<P>;
}
interface HOCState {
}
declare function hocFactory<P>(WrappedComponent: ComponentClass<P & HOCState>): {
    new (): {
        props: P;
    };
};
declare const AugmentedComponent: {
    new (): {
        props: P;
    };
};
```

TypeScript bails with `error TS2304: Cannot find name 'P'` on line 16 when consuming the declaration later on because there's no definition for that type parameter.

**Comment by mhegazy** [comment] 2017-09-18 16:52
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/18545

**Comment by swissmanu** [comment] 2017-09-19 08:38
not that good, my search skills are. 😣
sorry for the duplicate & thx for the linking!

**Comment by mhegazy** [comment] 2017-10-04 16:10
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-04 16:10 UTC
Labels: Duplicate
