### ISSUE TITLE
Visual Studio 2015 intellisense broken after installing Typescript 1.8.1.0 Beta

### ISSUE THREAD

**Issue by codewithtomi** [Microsoft/TypeScript#6958] opened 2016-02-07 19:39 UTC
Just installed latest typescript from download link available in typescript blog (https://blogs.msdn.microsoft.com/typescript/2016/01/28/announcing-typescript-1-8-beta/)

and downloaded installation exe from link provided 
http://download.microsoft.com/download/6/D/8/6D8381B0-03C1-4BD2-AE65-30FF0A4C62DA/TS1.8.1-Beta-TS-master.20160126.1/TypeScript_Dev14Full.exe

When i open any ts file in vs2015, code is entiry black and reserved words do not appear blue. Also when trying to use '.' to list class members, nothing happens.

Noticed also another issue with 1.8 beta with .sln web projects (not sure is it related?) . In Project.Projerties.TypeScript Buid tab, the Tab Header is empty text and content of tab displays only text
An error occurred trying to load the page.
d4683cae-88c4-4b85-863d-ac8014f3ba36

**Comment by codewithtomi** [comment] 2016-02-07 20:53
Update: Visual Studio 2015 is installed on D: drive. Could this be installer problem?

**Comment by vladima** [comment] 2016-02-07 22:16
// cc @yuit @paulvanbrenk

**Comment by mhegazy** [comment] 2016-02-07 22:34
This is an issue with the installer. we should have this fixed in the next 1.8 release. 

As a workaround, you should have a folder on your C drive under, `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript`, please copy that to `D:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript`, and from a Visual Studio Command prompt, run devenv /setup.

Sorry about the trouble.

**Comment by codewithtomi** [comment] 2016-02-08 07:56
Thank you very much! Workaroud helped and You really saved my week! 
Hopefully this is fixed also in coming TypeScript betas in the future. Looking forward and thanks again.

**Comment by codewithtomi** [comment] 2016-02-08 11:33
Seems that I am not able to debug TypeScript applications any more after upgrading 1.8 beta. Js files and symbols  (map files) are generate, so the compiler is working but breakpoints says 'The breakpoint will not currently be hit. No symbols have been loaded with this document.' I was able to debug prior update. I have an ASP.NET web application which I usually debug with Internet Explorer. I appreciate any help to get debug working again.

**Comment by rgripper** [comment] 2016-02-08 12:50
:+1:

**Comment by mhegazy** [comment] 2016-02-08 17:47
@codewithtomi another set of dlls need to be copied to the correct location manually for debugging to work. the binaries are in `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Packages\Debugger` (**\TypeScriptDebugEngine.resources.dll, TypeScriptDebugEngine.dll, and TypeScriptDebugEngine.vsdconfig)

**Comment by mhegazy** [comment] 2016-02-08 17:48
@rgripper is your VS installed to `D:\Program Files (x86)\Microsoft Visual Studio 14.0` ?

**Comment by codewithtomi** [comment] 2016-02-08 19:36
I copied missing files (an resource folders)  that was missing. Here's comparison result of files that was missing. 
![typescriptdebugdlls](https://cloud.githubusercontent.com/assets/3198840/12896414/857611c4-ceaa-11e5-93a3-a14bd22a244e.png)

At the moment I start application debug, all breakpoints in ts code turns to  white and hovering over one shows the same message ' will not be hit...' . I did run also devenv /setup just in case. Perhaps I am missing something still?

**Comment by rgripper** [comment] 2016-02-08 20:55
@mhegazy Argh, good point! I have VS on D: but in different folder, but I also have rubbish `D:\Program Files (x86)\Microsoft Visual Studio 14.0` left from other installation of windows %). Now everything works, thanks!

**Comment by paulvanbrenk** [comment] 2016-02-08 20:57
@codewithtomi I think you may be missing this file:

`C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\TypeScriptSourceMapReader.dll`

**Comment by codewithtomi** [comment] 2016-02-08 21:34
Hi

Good news! I get TS debugging working....

Following folders are under C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7

1) Need to copy IDE\PrivateAssemblies
    TypeScriptSourceMapReader.dll

2)  IDE\Remote Debugger   (x86 and x64 foders) file TypeScriptDebugEngine.dll in both...
   I replaced older version from December in correspoding folder in D:

3) IDE\Remote Debugger\x64\TypeScriptDebugEngine.dll


Thank you very much!

**Comment by codewithtomi** [comment] 2016-02-08 21:37
Could you please verify, should I revert the steps 2) and 3). I was just investigating by my self before reading @paulvanbrenk's comment.

**Comment by paulvanbrenk** [comment] 2016-02-08 23:05
@codewithtomi your changes all look good, they may only be needed in some specific scenarios, but they don't hurt.

**Closed** 2016-02-10 21:35 UTC
Labels: Bug, Fixed

**Comment by davismj** [comment] 2016-02-18 23:24
I seem to have the same issue, but all of the above DLLs are in place and still no debugging. Intellisense is working, however.

**Comment by mhegazy** [comment] 2016-02-18 23:36
@davismj this looks like a different issue. can you provide more information. what did you install and what is working and what is not, do you see this on multiple machines or a single one? does repair on the installer solves the issue?

**Comment by davismj** [comment] 2016-02-20 23:41
I only have one machine so I can only test on this one.

Link to the typescript install I'm using here:

[http://download.microsoft.com/download/6/D/8/6D8381B0-03C1-4BD2-AE65-30FF0A4C62DA/TS1.8.1-Beta-TS-master.20160126.1/TypeScript_Dev14Full.exe](http://download.microsoft.com/download/6/D/8/6D8381B0-03C1-4BD2-AE65-30FF0A4C62DA/TS1.8.1-Beta-TS-master.20160126.1/TypeScript_Dev14Full.exe)

From this page: 

[Announcing TypeScript 1.8](http://download.microsoft.com/download/6/D/8/6D8381B0-03C1-4BD2-AE65-30FF0A4C62DA/TS1.8.1-Beta-TS-master.20160126.1/TypeScript_Dev14Full.exe)

**Comment by davismj** [comment] 2016-03-01 03:42
I am having the same issue in 1.8.2 (Visual Studio 1.8.4)

**Comment by mhegazy** [comment] 2016-03-01 18:09
@davismj can you please file a new issue and share your install logs, `%temp%\dd_Typescript*`

**Comment by jzabroski** [comment] 2016-05-12 12:31
@mhegazy  How can I tell if @davismj ever submitted a new issue and shared his install logs?

I am having the same exact issue.  I will file a new issue, but would like the team's help in knowing what I can do to help reproduce and fix.

My issue only happened after I uninstalled Enterprise Edition trial, then re-installed it using a Corporate provided installer.  I notice this Corporate provided installer has the /NoWeb flag set, probably for security purposes, since as developers we are allowed to run VS in admin mode in order to effectively debug code.
