### ISSUE TITLE
const / let scopes are different from native JS engines (V8 and SpiderMonkey)

### ISSUE THREAD

**Issue by gfx** [Microsoft/TypeScript#26764] opened 2018-08-30 02:37 UTC
**TypeScript Version:**  3.0.1

**Search Terms:** variable scope es2015 label:Bug

**Code**

```ts
function f() {
  console.log("foo:", foo);
}

f(); // => foo: undefined
let foo = 42;
f(); // => foo: 42
```

**Expected behavior:**

In V8 (nodejs, chrome) and SpiderMonkey (firefox), <del>it can't compile</del> it runs with ReferenceError if foo is not initialized.

**Actual behavior:**

It compiles and runs, showing `foo: undefined` and `foo: 42`.

**Playground Link:** [playground](https://www.typescriptlang.org/play/#src=function%20f()%20%7B%0D%0A%20%20console.log(%22foo%3A%22%2C%20foo)%3B%0D%0A%7D%0D%0A%0D%0Af()%3B%20%2F%2F%20foo%3A%20undefined%0D%0Alet%20foo%20%3D%2042%3B%0D%0Af()%3B%20%2F%2F%20foo%3A%2042%0D%0A)

**Related Issues:** https://github.com/Microsoft/TypeScript/issues/19503 looks similar, I guess.

**Comment by andy-ms** [comment] 2018-08-30 03:49
Seems like a duplicate of #11498.
Currently TypeScript never considers *when* a function is called when checking it. So it assumes any variables it closes over will have been defined by the time the function is called.

If this was instead a suggestion to copy the runtime behavior and throw `ReferenceError` instead of getting `undefined` when transpiling to es5, that's probably too expensive to do for every variable that happens to be used in a closure -- and we currently have no way of detecting that a function is called only when its closed-over variables have already been defined, so we *would* have to do that for every variable.

**Closed** 2018-12-14 18:00 UTC
Labels: Duplicate
