### ISSUE TITLE
esnext does not include es2020

### ISSUE THREAD

**Issue by chrisblossom** [microsoft/TypeScript#32737] opened 2019-08-06 17:37 UTC
**TypeScript Version:**  3.5.3

**Search Terms:** `esnext es2020`

**Code**

```ts
// tsconfig.json
{
	"compilerOptions": {
		"target": "esnext", // es2020 works as expected
	},
}

// TS2339: Property 'matchAll' does not exist on type 'String'.
String.prototype.matchAll(/exists/);
```

**Expected behavior:**
`target: "esnext"` includes `es2020`

**Actual behavior:**
`target: "esnext"` does not include `es2020`

**Playground Link:** https://www.typescriptlang.org/play/index.html?target=6#code/MoFwTglgdg5gdABzAexKgnggpnAtgQxAGMALAQQBsKAKAeiwA8IBnEZ2gSgG4g

**Comment by MartinJohns** [comment] 2019-08-06 18:02
Duplicate of #32679. Search term used: `es2020`

**Closed** 2019-08-15 17:06 UTC
Labels: Bug
