### ISSUE TITLE
Potentially incorrect return type inference for enum types

### ISSUE THREAD

**Issue by michaelgeorgeattard** [Microsoft/TypeScript#23504] opened 2018-04-18 11:36 UTC
Hi,

In the following case, why is type of `z` inferred as `Bar` instead of `Bar.Baz`?

```ts
enum Bar {
    Baz = "Baz",
    Abc = "Abc"
}

function foo() {
    return Bar.Baz;
}

const z = foo();
```

**Comment by MartinJohns** [comment] 2018-04-18 12:24
Because `Bar.Baz` is not a type. It's an identifier for the value `"Baz"`, and the type is `Bar`.

**Comment by michaelgeorgeattard** [comment] 2018-04-18 12:45
`Bar.Baz` should be a type too.

Also the below works:

```ts
enum Bar {
    Baz = "Baz",
    Abc = "Abc"
}

function foo(): Bar.Baz {
    return Bar.Baz;
}

const z = foo();
```

**Comment by andy-ms** [comment] 2018-04-18 14:48
Duplicate of  #241

**Comment by RyanCavanaugh** [comment] 2018-04-18 14:48
@andy-ms these are function declarations, not expressions

**Closed** 2018-05-02 22:53 UTC
Labels: Question
