### ISSUE TITLE
Promise's `then` method allows to get wrong type for term depends of its type-argument.

### ISSUE THREAD

**Issue by Renegatto** [microsoft/TypeScript#43642] opened 2021-04-12 10:18 UTC
# Bug Report

### 🔎 Search Terms

then, Promise, async

### 🕗 Version & Regression Information

v 4.2.3
v 4.3.0-dev.20210412

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210412&ssl=4&ssc=90&pln=1&pc=1#code/MYewdgzgLgBAZiEAuGAFATiAtgSwgUwB4Ns8iwBXLAI33QD56YBeGAKBk7U1wIDp0+CCAA2ANyIle5KrQb0AFFLIChoiQoBs2gJQ62CEHygALfGAUKAHimUFClGnXo6WTUJFH4+IkAHMFKABPAAd8EDgYKz02AHpYrkSYAD1UtPSM1JhTAEMoCBgc4CgKHJERIJgAd0wwP2zQ-HgQdBgAcis2gBp2zpg8QuLS8sqc9sc5NqA)

### 💻 Code

```ts
const foo: Promise<Promise<number>> = 
    Promise.resolve<Promise<number>>(Promise.resolve(666))
//                  ^^^^^^^^^^^^^^^ type argument
foo.then((x: Promise<number>) => console.log(typeof x))
//        ^^^^^^^^^^^^^^^^^ thats actually wrong type for 'x', 'x' is actually a 'number'
```

### 🙁 Actual behavior

Output: `"number"` 
This is wrong because `x` annotated as `Promise<number>` and it typechecks.

### 🙂 Expected behavior

 Compilation error or output: `"object"`

**Comment by MartinJohns** [comment] 2021-04-12 11:13
Duplicate of #27711. `Promise<Promise<T>>` should result in an error.

**Closed** 2021-04-15 18:00 UTC
Labels: Duplicate
