### ISSUE TITLE
Formatter adds a extra space around embedded expressions in template literals

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#5745] opened 2015-11-21 18:55 UTC
```typescript
function fn() {}
`blah${fn()}blah`
// actual:
`blah${fn() }blah`
// expected:
`blah${fn()}blah`
```

**Comment by DanielRosenwasser** [comment] 2015-11-21 19:08
Looks like a duplicate of #5030, which should have a fix in 1.7.

**Closed by DanielRosenwasser** 2015-11-21 19:08 UTC
