### ISSUE TITLE
Add support for `duplex: "half"` in `RequestInit` interface

### ISSUE THREAD

**Issue by ruochenjia** [microsoft/TypeScript#56882] opened 2023-12-26 19:31 UTC
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Latest Chrome browser requires setting `duplex: "half"` flag for the construction of all requests with a streaming body:
![image](https://github.com/microsoft/TypeScript/assets/66373748/db3049c0-1c1d-4f30-8be8-340a96354ec9)
However this option does not seem to exist in the `RequestInit` interface in `lib.dom.d.ts`, so users cannot construct a `Request` object with a `ReadableStream` body without causing an error when running in Chrome.

Currently the only workaround for this issue is to cast the `RequestInit` object to `any`, but it is not considered to be a proper solution.

```javascript

const body: ReadableStream<any> = ...
const request = new Request("https://example.com/", {
  body: body,
  method: "POST",
  duplex: "half"
} as any);

```

**Comment by MartinJohns** [comment] 2023-12-26 21:23
Duplicate of https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1483.

> Currently the only workaround for this issue is to cast the `RequestInit` object to `any`

Or use declaration merging and extend the type locally.

**Comment by RyanCavanaugh** [comment] 2024-01-02 18:46
There's a lib change template, please use it.

**Closed by RyanCavanaugh** 2024-01-02 18:46 UTC
