### ISSUE TITLE
String.split, low cost lib modification for narrowing return type of non-empty strings

### ISSUE THREAD

**Issue by craigphicks** [microsoft/TypeScript#56333] opened 2023-11-07 02:44 UTC
### 🔍 Search Terms

#52299 (closed)
#30406 (marked as design limitation)

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

In `es5.d.ts`

before:
```
interface String {
    split(separator: string | RegExp, limit?: number): string[];
}
```
after:
```
interface String {
    split<S extends string>(separator: S): string extends S ? string[] : 
        S extends "" ? string[] : [string, ...string[]];
    split(separator: string | RegExp, limit?: number): string[];
}
```

### 📃 Motivating Example

```
@noUncheckedIndexAccess: true
function checkField(fieldName: string){
    let firstPathPart = fieldName;
    if (fieldName.includes('.')) {
        const partParts = fieldName.split('.');
        firstPathPart = partParts[0]; // error
    }
}
```

### 💻 Use Cases

1. What do you want to use this for?

As shown above

2. What shortcomings exist with current approaches?

As shown above.

3. What workarounds are you using in the meantime?

```
@noUncheckedIndexAccess: true

interface String {
    split<S extends string>(separator: S): string extends S ? string[] : 
        S extends "" ? string[] : [string, ...string[]];
    split(separator: string | RegExp, limit?: number): string[];
}

function checkField(fieldName: string){
    let firstPathPart = fieldName;
    if (fieldName.includes('.')) {
        const partParts = fieldName.split('.');
        firstPathPart = partParts[0]; // no error
    }
}

{
// #53362 & #56332 & #56333 all give these results
const x1 = "".split('.'); // [string, ...string[]]
const x10 = x1[0]; // string
const x11 = x1[1]; // string | undefined
const x31 = "".split('.')[0]; // string
const x32 = "".split('.')[1]; // string | undefined
const x4 = "".split(''); // string[] 
const x5 = "".split((0 as any as string)); // string[]
}

[playground](https://www.typescriptlang.org/play?#code/FDCWDsBcFMCcDMCGBjaACAypWEDmaBvYNEtAZwAcAbUSAHgzWgA8ZwATM87PAPgAoy0ColiJIAe1gAuTAEpZZHuHws2nTGgD83HCoDaAXTSzipc4zXQOXAES3tuvEZNp9SvbgA0aAHT+PZ0NDAG4zEkoaSEFhUXEpRWV8AB80ACVoXABRZgofGgBbWi1ZcABXAoAjOAUnA1DgAF8QeDLwZEhQCXA0ZAALaGQAawAxUGgqdn54ccmAOUQC6ETPOSJzKmhINBnYJQAFcT7D2G2AXh3Z9gWlsPNQeDRpq5voXwhkKjL2aDJ+AHJfP85HJCOFzL1uko0CJTidIFwLjMJtdFm9IrQAUC5HcISRdgcjvC0BdYZB4WR9AAGUJoAD0dLQ4AkTFgsCk4OazWAyCh22YAEYSWh7L4MdFAcCQvTGW5AiofP4xUkjIYeXy0MwAEzCwXU2kMuq4dXgaHMADMwtF4qxwP10sN8uNvNN-IALFbbGLqJj-lKZUajCazQBWT3eqL8fhUtCILiIcAAT1jXCdIIdjKdQaAA)

**Comment by MartinJohns** [comment] 2023-11-07 02:56
Duplicate of #53362.

**Comment by fatcerberus** [comment] 2023-11-07 03:43
How does this differ from https://github.com/microsoft/TypeScript/issues/56332?

**Comment by craigphicks** [comment] 2023-11-07 21:39
## The proposal #53362:
```
interface String {
    split<T extends string | RegExp>(separator: T, limit?: number): T extends `${string}${infer U}` ? [string, ...string[]] : string[];
}
```
clearly is not the same.  I'm going to go out on a limb, and guess the details of what [the comment](https://github.com/microsoft/TypeScript/issues/56333#issuecomment-1797380127) means by "Duplicate of https://github.com/microsoft/TypeScript/issues/53362.":

1. The type result is same (that is true).

2. The apparent reason for the rejection of #53362 would also apply to This proposal 56333.  That reason is:
> FWIW: we have a pretty low appetite for making the standard library definitions extremely complex for the sake of NUIA, which is a flag we added with significant hesitation because it makes things like these difficult to handle.

The NUIA flag is the "noUncheckedIndexAccessFlag".


## The proposal in #56332 
```
interface String {
    split<S extends string>(separator: S): string extends S ? string[] : 
        S[0] extends undefined ? string[] : [string, ...string[]];
    split(separator: string | RegExp, limit?: number): string[];
}    
```
It is also not literally the same. Moreover, 56332 has a prerequisite that the element access part of proposal #34692 be implemented, and This proposal 56333 does not.

## Discussion 

There is a question I have about what "extremely complex" means exactly:

I initially interpreted that to mean that a type definition which included "infer" would be extremely complex. 
If my assumption is correct, then the commenter (comment)[https://github.com/microsoft/TypeScript/issues/56333#issuecomment-1797380127]  is of the opinion that any conditional type expression is too complex. 

If it is the case that any conditional type expression (used to accommodate NUIA) is unacceptable, then this proposal is unacceptable.

But still we can get something beneficial out this proposal by clarifying/asking some things:

1.  Do any conditional return types exist in any js standard library lib file at all? (Sorry I don't know this).
2.  Are any new conditional return types for any js standard library lib file highly discouraged?
3.  Are any changes to js standard library, solely to accommodate NUIA, highly discouraged (and do any exist)?

I wrote "highly discouraged" rather than "unacceptable" because, well, you never know.  "Highly discouraged" is enough of a guide to help streamline the proposal process, which is a good thing.  

@RyanCavanaugh - I really hate to take your time, but I would like to ask you to clarify what you mean by "extremely complex" in (this comment)[https://github.com/microsoft/TypeScript/issues/53362#issuecomment-1478293505], if you don't mind.  Also if you have time, yes/no answer my above questions about library changes in general, although it's not really necessary.  Thanks.

**Comment by RyanCavanaugh** [comment] 2023-11-08 17:05
Complexity is relative to value provided. The value of `String#split` being a "provably non-empty" array is, in estimation, pretty low, in line with what you're saying.

> I'm inclined to believe that these would be good explicit rules:

I'd say these are very good (especially re: NUIA), but not 100% rules (maybe 95%) ?

I don't really have a good place to write these down, but feel free to reference this comment (and I will likely do the same).

**Comment by MartinJohns** [comment] 2023-11-08 19:25
> Why it is not a duplicate of https://github.com/microsoft/TypeScript/issues/53362

But it is. #53362 is about improving the type definitions for `String#split`, and this issue is about improving the type definitions for `String#split`. The only difference is the approach suggested, but that does not really warrant a new issue, it can be added as a comment instead. Besides that, #53362 is not (yet) declined, it's awaiting more feedback.

**Closed** 2023-11-11 01:25 UTC
Labels: Duplicate
