### ISSUE TITLE
Visual Studio 2015 crashes when saving package.json

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#7517] opened 2016-03-15 11:57 UTC
**TypeScript Version:** 

1.8.6

**Code**

https://github.com/falsandtru/localsocket/tree/v0.0.2

**Comment by mhegazy** [comment] 2016-03-15 16:31
Can you share the stack from the event log?

what makes you believe this is TypeScript related? TypeScript is not aware of any json files. 

//CC: @madskristensen

**Comment by falsandtru** [comment] 2016-03-15 16:51
How can I get the event log?

This crash is caused when opening json files in TypeScript project.

repro:

0. open `localsocket.csproj`.
0. show all files in the sidebar(solution explorer).
0. open `package.json` using the sidebar.
0. save `package.json`.
0. crash

Can you repro?

**Comment by vladima** [comment] 2016-03-15 17:19
look for `eventvwr` in the list of programs. After you open it, look for `Windows logs` -> `Applications` and then search for recent entries with level `Error`, source `.NET Runtime` where application is `devenv.exe`
![eventlog](https://cloud.githubusercontent.com/assets/8052307/13787008/531439f0-ea97-11e5-8db9-666be24b18ae.PNG)

**Comment by mhegazy** [comment] 2016-03-15 17:21
here is the stack:

```txt
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.VisualStudio.Web.PackageManagement.Npm.NpmCommandServiceFactory.TryGetNpmCommandServiceFromProject(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, System.String, Microsoft.VisualStudio.Web.PackageManagement.Npm.INpmCommandService ByRef)
   at Microsoft.VisualStudio.Web.PackageManagement.Npm.NpmCommandServiceFactory+<>c__DisplayClass2_0+<<GetNpmCommandService>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`1<System.Threading.Tasks.Task`1<System.__Canon>>, Microsoft.VisualStudio.Threading.JoinableTaskCreationOptions)
   at Microsoft.VisualStudio.Web.PackageManagement.Npm.NpmCommandServiceFactory.GetNpmCommandService(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, System.String)
   at Microsoft.VisualStudio.JSON.Package.Npm.NpmPackageManagerInitializer.GetNpmCommandService(Microsoft.VisualStudio.Text.ITextBuffer)
   at Microsoft.VisualStudio.JSON.Package.Npm.NpmPackageManagerInitializer+<<get_InstallPackagesAction>b__4_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)


```

**Comment by mhegazy** [comment] 2016-03-15 17:29
Found the right owner, and rerouted the issue.

**Comment by falsandtru** [comment] 2016-03-15 17:29
Thanks, this is my event log.

```
アプリケーション:devenv.exe
フレームワークのバージョン:v4.0.30319
説明: ハンドルされない例外のため、プロセスが中止されました。
例外情報:System.NullReferenceException
   場所 Microsoft.VisualStudio.Web.PackageManagement.Npm.NpmCommandServiceFactory.TryGetNpmCommandServiceFromProject(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, System.String, Microsoft.VisualStudio.Web.PackageManagement.Npm.INpmCommandService ByRef)
   場所 Microsoft.VisualStudio.Web.PackageManagement.Npm.NpmCommandServiceFactory+<>c__DisplayClass2_0+<<GetNpmCommandService>b__0>d.MoveNext()
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   場所 Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   場所 Microsoft.VisualStudio.Threading.JoinableTask`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CompleteOnCurrentThread()
   場所 Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`1<System.Threading.Tasks.Task`1<System.__Canon>>, Microsoft.VisualStudio.Threading.JoinableTaskCreationOptions)
   場所 Microsoft.VisualStudio.Web.PackageManagement.Npm.NpmCommandServiceFactory.GetNpmCommandService(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, System.String)
   場所 Microsoft.VisualStudio.JSON.Package.Npm.NpmPackageManagerInitializer.GetNpmCommandService(Microsoft.VisualStudio.Text.ITextBuffer)
   場所 Microsoft.VisualStudio.JSON.Package.Npm.NpmPackageManagerInitializer+<<get_InstallPackagesAction>b__4_0>d.MoveNext()
   場所 System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   場所 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   場所 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   場所 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   場所 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   場所 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   場所 MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   場所 System.Windows.Threading.DispatcherOperation.Invoke()
   場所 System.Windows.Threading.Dispatcher.ProcessQueue()
   場所 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   場所 MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   場所 MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   場所 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   場所 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

```

**Comment by jodavis** [comment] 2016-03-25 17:30
@mhegazy @falsandtru Thanks for the callstacks. This will be fixed in the next release of the Web Tools for Visual Studio.

I would like to find a workaround for you, but I'm not sure how you are hitting this case. I have a few questions.
1. Is the package.json file part of your project?
2. Are you editing the file in a "special" view (e.g. in the diff viewer)?
3. Can you reproduce this in a simple project that you could share with us?

Thanks.

**Comment by falsandtru** [comment] 2016-03-26 06:05
@jodavis thanks for the fix. Can you see my project and workflow for repro?

https://github.com/falsandtru/localsocket/tree/v0.0.2
https://github.com/Microsoft/TypeScript/issues/7517#issuecomment-196919585

**Comment by mhegazy** [comment] 2016-05-20 05:57
@jodavis any updates on this issue?

**Comment by jodavis** [comment] 2016-05-20 17:48
It is fixed in this week's release of Web Tools: https://go.microsoft.com/fwlink/?LinkId=798481.

Since these tools are labeled "Preview", they will not be shipping in an official VS Update.

There's more info about the release (mostly focused on ASP.NET Core) here: https://blogs.msdn.microsoft.com/visualstudio/2016/05/16/announcing-updated-web-development-tools-for-asp-net-core-rc2/

**Comment by mhegazy** [comment] 2016-05-20 22:03
thanks for the update. closing.

**Closed by mhegazy** 2016-05-20 22:03 UTC
Labels: External

**Comment by falsandtru** [comment] 2016-10-05 06:07
@jodavis VS still crashes. This bug is not fixed yet.

```
Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586
```

**Comment by mhegazy** [comment] 2016-10-05 17:27
@jodavis where should this issue be tracked?

**Comment by jodavis** [comment] 2016-10-05 20:08
@mhegazy It should be tracked in TFS.

@falsandtru Do you have the latest ASP.NET Core tools installed? The fix didn't ship in any official VS 2015 update, because the component that contains the code was still in a "preview" state. With that update, the crash does not repro for me with your sample project.

**Comment by falsandtru** [comment] 2016-10-05 21:48
I didn't install its preview edition yet. When can we use the fixed version via installing VS2015?

**Comment by jodavis** [comment] 2016-10-10 18:13
The fix didn't make it into any of the VS 2015 Updates, and no further updates are currently planned. It is only available in the ASP.NET Core tools preview for VS 2015, and the Visual Studio "15" preview releases.

**Comment by falsandtru** [comment] 2016-10-11 02:59
I see, thanks for letting me know.
