### ISSUE TITLE
Checking whether a property is defined or not using the dot notation should not be an error.

### ISSUE THREAD

**Issue by qyuga** [microsoft/TypeScript#42167] opened 2020-12-31 21:33 UTC
# Bug Report

### 🔎 Search Terms
Property Definition Check
Property Undefined Check

### 🕗 Version & Regression Information

- This is the behavior in every version I tried.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/FAUwHgDg9gTgLgAjgTwiBAFKBLAdnAJgBEEBeBAbwTAC4FcBXAWwCMQYAaBZOx19hAF8A3KEixEKNJhz4AzCXJY8hEgDJKCAF69mbGENHho8JKnTL8ZGSuIIAPjflFRYk4gBmDXAGM42KFwEABMYAEMAdwAKCDpLOABKSmAEBAB6NIQAFQALbABnBB8ckB8AawR8nKgGABtg+ihENgQwoPYYWABCFIRsDwQYgDotBC7Scm9gkA88EGCkqh9A-KhakCHaqABzKIAieIU9hOEhXpBa-PQllbWNrd2D2VVj08Fgd+B1xAgARjjntYqLQEL8uDwEAQuDoEHJDMBQpEYr8TsBgEA)

### 💻 Code

```ts


export type Point2D = { x: number, y: number };
export type Point3D = Point2D & { z: number };
export type Point = Point2D | Point3D;

export function draw(p: Point) {
  // This check should not be an error!
  if (p.z != undefined) { console.log("Point3D"); }
  else { console.log("Point2D"); }
}

let p1: Point = { x: 1, y: 2, z: 3 };
draw(p1);



// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙁 Actual behavior
```
Property 'z' does not exist on type 'Point'.
  Property 'z' does not exist on type 'Point2D'.(2339)
```

### 🙂 Expected behavior
Checking if the property is defined should not be an error.

**Comment by andrewbranch** [comment] 2020-12-31 23:45
Duplicate of #39065

**Comment by qyuga** [comment] 2021-01-01 00:10
Okay. It seems to be a duplicate which I didn't find that earlier in my search.

Please note that @RyanCavanaugh  mentioned the following:
The "lack" of this feature is very much intentional; this pattern is not safe to use because object types aren't closed, so the existence of a value in some property slot is really not a solid indication that anything correct is happening. The `in` operator is granted an exception to this because there's nothing else you might be intending to do with the `in` operator.

See e.g. https://github.com/microsoft/TypeScript/issues/37343#issuecomment-597765489

_Originally posted by @RyanCavanaugh in https://github.com/microsoft/TypeScript/issues/39065#issuecomment-643826453_

Even though, the claim is valid, that's possibly not a common case, and additional type checks can be performed if the code is doing something weird.

Using `in` operator works fine, but it has certain limitations such as if the original property is renamed, the conditional check might not be updated properly.

**Closed** 2021-01-03 18:00 UTC
Labels: Duplicate
