### ISSUE TITLE
--outDir + --watch + path bug after file changes

### ISSUE THREAD

**Issue by materliu** [Microsoft/TypeScript#8656] opened 2016-05-18 02:36 UTC
**TypeScript Version:** 
1.8.10

**OS Version:**
MacOS

In fact, I just begin to learn typescript, because the angular2.0, I use the `https://github.com/angular/quickstart` as the begining, and I change it's file structure, add ts folder, and move the typescript file to ts folder, change npm scripts: 

`"start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",`   ---->
`"start": "npm run build:css && tsc --outDir ./app/scripts/ --rootDir ./app/ts/ && concurrently \"npm run tsc:w\" \"lite-server\" ",`

`"tsc:w": "tsc -w", ` ---->
`"tsc:w": "tsc -w --outDir ./app/scripts/ --rootDir ./app/ts/",`

I start the project by run npm start, the tsc generate related js file to app/scripts folder, but when I change some typescirpt file, instead of outputing to the --outDir folder, it outputs .js files to where the .ts file is. It just happens after changing the file, the first compilation is right.

**Comment by mhegazy** [comment] 2016-05-18 22:02
i see you are not passing any files on the commmandline, do you have a `tsconfig.json` in this folder? can you share that?

**Comment by materliu** [comment] 2016-05-19 02:24
yeah, the project has a tsconfig.json file in it's root folder, and I don't change it, the content is:

```javascript
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  },
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ]
}
```

**Comment by zhengbli** [comment] 2016-05-19 04:39
Your build step is embedded in a quite complex npm script. Have you tried to run `tsc` directly from commandline? Just `tsc -w` with the `--OutDir` parameters and see if the output was correct.

**Comment by materliu** [comment] 2016-05-19 06:40
after I move the --outDir configuration to tsconfig.json file, the problem get fixed, thx so much. But I still don't know why it not work with the CLI.

**Comment by shaddyz** [comment] 2016-05-25 23:51
This is still a problem. It happens to me on Windows. The behavior of tsc changes when watching is enabled. The fact that a workaround exists doesn't solve the problem. This is preventing me from overriding a setting in tsconfig and will force me to have yet another config for a total of 3 so far.

**Comment by mhegazy** [comment] 2016-05-25 23:53
can you provide more information?

**Comment by shaddyz** [comment] 2016-05-26 20:08
Assume a folder structure:
```
-- project/
   |
   |-- src/
   |    |
   |    |--- code.ts
   |    |
   |    \--- tsconfig.json
   |
   \-- dist/
```

Assume tsconfig has outDir set to "dist"

1. I execute the following command from the project directory:
 * `tsc -p src --outDir dist -w`
 * -> compiled output goes to project/dist/code.js
2. Modify and save code.ts
 * -> compiled output goes to project/src/code.js
 * expectation is the original destination is overwritten, and that destination is the value in the command line argument (which should take precedence over the config file)

**Comment by mhegazy** [comment] 2016-05-26 20:29
i can not reproduce this issue.. here is what i am doing:

```txt
c:\test\8656>tsc --v
Version 1.8.10

c:\test\8656>tree /f .
└───project
    └───src
            a.ts
            b.ts
            tsconfig.json

c:\test\8656>type project\src\tsconfig.json
{
    "compilerOptions": {
    }
}

c:\test\8656>cd project

c:\test\8656\project>tsc -p src --outDir dist -w
1:26:15 PM - Compilation complete. Watching for file changes.

c:\test\8656>tree /f .
C:\TEST\8656
└───project
    ├───dist
    │       a.js
    │       b.js
    │
    └───src
            a.ts
            b.ts
            tsconfig.json

c:\test\8656>touch project\src\a.ts

1:28:10 PM - File change detected. Starting incremental compilation...
1:28:11 PM - Compilation complete. Watching for file changes.

c:\test\8656>tree /f .
C:\TEST\8656
└───project
    ├───dist
    │       a.js
    │       b.js
    │
    └───src
            a.ts
            b.ts
            tsconfig.json

````

**Comment by mhegazy** [comment] 2016-06-07 22:20
closing for now. please reopen if this still an issue and provide a project we can use to reproduce and diagnose the problem.

**Closed by mhegazy** 2016-06-07 22:20 UTC
Labels: Needs More Info

**Comment by shaddyz** [comment] 2016-06-07 22:27
As I explain in my comment, tsconfig has outDir set to "dist", you left it empty.

**Comment by ENikS** [comment] 2016-06-26 16:59
@mhegazy I can reproduce this issue in Version 1.9.0-dev.20160620-1.0
Going back to typescript@1.8.10 fixes this issue

**Comment by mhegazy** [comment] 2016-06-27 18:17
can you share a repro project? a github repo i could try maybe?

**Comment by ENikS** [comment] 2016-06-27 18:29
Get my LINQ project and try to build it with TS@next
https://github.com/ENikS/LINQ

**Comment by mhegazy** [comment] 2016-06-27 20:14
i am sorry but i still can not see the issue. running `tsc --w`, `tsc --w --out lib`, `tsc --p ./tsconfig.json --w` all seem to generate the output under `lib` correctly. so what do i need to do to reproduce the issue?

**Comment by ENikS** [comment] 2016-06-27 20:39
I get this error every time I run tsc  without any command line arguments

**Comment by mhegazy** [comment] 2016-06-27 21:00
> I get this error every time I run tsc without any command line arguments

which error? i see a bunch of errors about missing `Enumerable` and `IEnumerable`, but i was only looking at output locations.

**Comment by ENikS** [comment] 2016-06-27 21:42
It seems something else is broken:
https://travis-ci.org/ENikS/LINQ/builds/140653700
If I change to TS@next build breaks before it has a chance to report the error. Looks like it is not picking up typings from the package.json.

The same repository builds just fine with stable TS
https://travis-ci.org/ENikS/LINQ/builds/140654729
