### ISSUE TITLE
Nullable property in interface

### ISSUE THREAD

**Issue by MuratovBektur** [microsoft/TypeScript#57316] opened 2024-02-07 03:24 UTC
### 🔍 Search Terms

Nullable property in interface

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

## now

sometimes some properties coming from the backend are nullable and you have to write something like this:

interface IUserResponse {
&nbsp;&nbsp;&nbsp;&nbsp; id: string;
&nbsp;&nbsp;&nbsp;&nbsp; about_me: string | null
}

## But I wanted to write more abbreviated code, something like this:

interface IUserResponse {
&nbsp;&nbsp;&nbsp;&nbsp; id: string;
&nbsp;&nbsp;&nbsp;&nbsp; about_me|: string // adding Vertical bar ( | )
}

## And for a value that is nullable and undefined or may have a value that is not defined

interface IUserResponse {
&nbsp;&nbsp;&nbsp;&nbsp; id: string;
&nbsp;&nbsp;&nbsp;&nbsp; about_me?|: string // or about_me|?: string 
}

**Comment by xiBread** [comment] 2024-02-07 07:03
Duplicate of #18430 and friends

**Closed** 2024-02-10 01:23 UTC
Labels: Duplicate
