### ISSUE TITLE
TypeScript assigning `{}` type for generic functions

### ISSUE THREAD

**Issue by ducin** [Microsoft/TypeScript#25269] opened 2018-06-27 12:37 UTC
**I'm trying to achieve a type-safe functional processing pipiline.** In other words, I've got generic functions that do bits of processing, then I _compose_ then (such as Ramda's compose) to build a bigger pipiline and I'd like the return type to be type-safe.

For composition, I'm using following implementation:
```ts
function compose<T, U, V>(f: (t: T) => U, g: (u: U) => V): (x: T) => V;
function compose<T, U, V>(f: (t: T) => U, g: (u: U) => V): (x: T) => V;
function compose<T, U, V, W>(f: (t: T) => U, g: (u: U) => V, h: (v: V) => W): (x: T) => W;
function compose<T, U, V, W, X>(f: (t: T) => U, g: (u: U) => V, h: (v: V) => W, i: (w: W) => X): (x: T) => X;
function compose<T, U, V, W, X, Y>(f: (t: T) => U, g: (u: U) => V, h: (v: V) => W, i: (w: W) => X, j: (x: X) => Y): (x: T) => Y;
function compose<T, U, V, W, X, Y, Z>(f: (t: T) => U, g: (u: U) => V, h: (v: V) => W, i: (w: W) => X, j: (x: X) => Y, k: (y: Y) => Z): (x: T) => Z;

function compose(...fns: Function[]) {
    return (value) => fns.reduce((res, fn) => fn(res), value);
}
```
The input of the first function and the output of last function is the signature of `compose` invocation.

```ts
let simpleProcess = compose(
    (n: number) => n ** 2,
    (n: number) => n > 0,
    (b: boolean) => b ? 'positive' : 'negative'
)
```
Type inference for functions without generics work exactly as expected: `let simpleProcess: (x: number) => "positive" | "negative"`

**The issue**
However, when I try to compose functions that accept generics, such as those two:

```ts
// unique([1,1,2,2,3]) == [1,2,3]
const unique = <T>(items: T[]): T[] => {
    const s = new Set<T>()
    return items.filter(t => {
        let found = s.has(t)
        return !found && s.add(t)
    })
}

// chunk(2)([1,2,3,4,5]) == [[1,2], [3,4], [5]]
const chunk = (size: number) => <T>(items: T[]) => items.reduce((aggr, item, idx) => {
    if (idx % size === 0) aggr.push([])
    aggr[aggr.length - 1].push(item)
    return aggr
}, [] as T[][])
```
and their composition:
```ts
let genericProcess = compose(unique, chunk(3))
```
the signature becomes: `let genericProcess : (x: {}) => {}[][])`.
And I'm trying to achieve following: `let genericProcess : <T>(t: T[]) => T[][])`

**2 question here**:

1. Why does `x: {}` gets inferred? I see it's a default, but it's something I would not expect, somehow misleading, since I've used `{}` nowhere.
2. since both `unique` and `chunk` (and many other underscore-ish functions I ignore here for clarity) are generic, I would like `compose` function to **expose** the generic type higher. How can I achieve that in TypeScript?
The first function, `f`'s generc parameter is unknown when `compose` is being invoked.

----

I'm trying to expose a generic on the result of the `compose`:
```ts
// instead of:
function compose<T, U, V>(f: (t: T) => U, g: (u: U) => V): (x: T) => V;
// I tried:
function compose<T, U, V>(f: (t: T) => U, g: (u: U) => V): <T>(x: T) => V;
// and got: `let genericProcess : <T>(x: T) => {}[][]`, there is <T> declaration twice
// also tried:
function compose<T, U, V>(f: (t: T) => U, g: (u: U) => V): <R extends T>(x: R) => V;
// and got: let genericProcess : <R extends {}>(x: R) => {}[][]
// also tried:
function compose<U, V>(f: (t) => U, g: (u: U) => V): <T>(t: T) => V;
// and got: let genericProcess : <T>(t: T) => {}[][]
```
but didn't get satisfying result.

**Comment by mhegazy** [comment] 2018-07-18 23:06
Duplicate of https://github.com/Microsoft/TypeScript/issues/10247

**Closed** 2018-07-30 16:23 UTC
Labels: Duplicate
