### ISSUE TITLE
Type inference after 'await'

### ISSUE THREAD

**Issue by asurance** [microsoft/TypeScript#38085] opened 2020-04-21 05:56 UTC
**TypeScript Version:**  3.8.3
**Code**
```ts
class demo {
    id: number | null = 1
    main() {
        // this.id => number | null
        if (this.id) {
            // this.id => number
            this.cbFn(() => {
                // this.id => number | null
                console.log(this.id)
            })
        }
    }
    async main2() {
        // this.id => number | null
        if (this.id) {
            // this.id => number
            await new Promise(resolve => {
                this.id = null
                resolve()
            })
            // this.id => number
            // but this.id can be null too
            console.log(this.id)
        }
    }
    cbFn(cb: () => void) {
        this.id = null
        cb()
    }
}
new demo().main()
new demo().main2()
```
**Description**
Type of previous inference with `if` become invalid when variable used in callback function for it can be changed before callback function called. I think statement after `await` can use the same rules.
**Expected behavior:**
`this.id` after `await` is inferred as `number|null`
**Actual behavior:**
`this.id` after `await` is inferred as `number`
**Playground Link:** 
https://www.typescriptlang.org/play/index.html?ssl=32&ssc=19&pln=1&pc=1#code/MYGwhgzhAEAmCmBbA9tA3gWAFDV9AlrAFzQB2ArogEbwBO0APmeSCNALzQCM2e0iYfKQAUASnS8+eAPTToAFwAW+CADpCHAHzNqdRs1aSpBAGbRhSletjjMOY1NkLlaje20VdtIw9yW1wFQAYiJiWhL2vsZO-tbhnjT0TBSGkVF8wMikEMgg8KogyADmFi7Woj6+AL4VaXxVPg1pkACepMD8gqQATGF2vjFlbh6UifopIJV4+GalVoS2U9FyscM6iUtSYADugvJk8NvQAAq0yIgq8MK08DkgAG7w4f3pUquwHAaTda83d49iTb1WqvaCDeYfdzrOhAmRyKjkfbvaDAMCkaA0L4KZDIWG4TLZXL5Qold4ghxNeo+QIhYSBEhhKH3ZALCK+ZGcCabQKAtJNJqkQ5wJDIMSqARCXmCo4IFBiiU9MRAA

**Comment by IllusionMH** [comment] 2020-04-21 11:42
Looks like duplicate of #9998 but with `await` instead of regular function call.

**Comment by nmain** [comment] 2020-04-21 14:06
Also see https://github.com/microsoft/TypeScript/issues/27900 for specific discussion around `await` and narrowing.

**Closed** 2020-04-24 18:00 UTC
Labels: Duplicate
