### ISSUE TITLE
TypeScript strange working with " and ' quotes in import

### ISSUE THREAD

**Issue by mixalbl4-127** [Microsoft/TypeScript#7616] opened 2016-03-21 15:42 UTC
**TypeScript Version:** 

1.7.5

**Code**

```
import {HTTP_PROVIDERS} from 'angular2/http'; // <-- one quotes !
import {Component} from "angular2/core";
import {Http} from "angular2/http"; // <-- two quotes !

@Component({
    templateUrl: 'tst.html',
    viewProviders: [HTTP_PROVIDERS]
})

export class tst {
    constructor(private http1:Http) {
        http1.get('tst');
    }
}
```

**Expected behavior:**
After compilation (js file):
System.register(['angular2/http', "angular2/core"] ...

**Actual behavior:** 
After compilation (js file):
System.register(['angular2/http', "angular2/core", "angular2/http"] ...

I have a many problems with this bug
bug example (with demo): http://stackoverflow.com/q/36134033/2051938

**Comment by kitsonk** [comment] 2016-03-21 16:28
Silly question, why are you not destructuring all your desired objects from a module with a single import statement?

**Comment by vladima** [comment] 2016-03-21 16:31
duplicate of #6681, already fixed in master

**Comment by mixalbl4-127** [comment] 2016-03-21 16:32
1. inattention
2. WebStorm editor automatically generates imports

**Closed by vladima** 2016-03-21 16:31 UTC
Labels: Duplicate
