### ISSUE TITLE
FormData needs additional constructor

### ISSUE THREAD

**Issue by epirion** [Microsoft/TypeScript#2707] opened 2015-04-10 08:35 UTC
Additional constructor that takes in HTMLFormElement as parameter as here: 

https://developer.mozilla.org/en-US/docs/DOM/XMLHttpRequest/FormData 

declare var FormData: {
prototype: FormData;
new (): FormData;
new (form: HTMLFormElement): FormData;
};

This is copied from https://typescript.codeplex.com/workitem/720, the fix isn't incorporated into TS v 1.4.
It's possible to write the constructor in the optional form as well:
new (form?: HTMLFormElement): FormData;

Thanks in advance!

**Comment by RyanCavanaugh** [comment] 2015-04-10 17:35
Duplicate of #1074

**Closed by RyanCavanaugh** 2015-04-10 17:35 UTC
Labels: Bug, lib.d.ts, Revisit
