### ISSUE TITLE
Infer keyword in typearg constraint

### ISSUE THREAD

**Issue by MichalMarsalek** [microsoft/TypeScript#59158] opened 2024-07-06 09:43 UTC
### 🔍 Search Terms

"implicit conditional type", "conditional type without extends",  "infer outside conditional type", "infer in generic constraint", "conditional type sugar"

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Currently it's not possible touse the `infer` keyword outside of the "extends type" in a conditional type. I'd like to propose allowing it in a type arg constraint position.

### 📃 Motivating Example

This seems like a perfectly valid thing to do
```ts
type FirstWord<T extends `${infer Result} ${string}`> = Result
```

but it is not alowed.

There is a workaround using a conditional type
```ts
type FirstWord<T extends `${string} ${string}`> = T extends `${infer Result} ${string}` ? Result : never;
```

but it feels weird having to type the same condition twice. Also, the false branch is provably never hit, which makes it feel more weird having to use the conditional type.

It would probably be easiest to implement if the proposed syntax was simple treated as a syntactic sugar for the conditional type above.

### 💻 Use Cases

1. What do you want to use this for?
Irrefutable pattern matching in type space.
3. What shortcomings exist with current approaches?
Having to duplicate the same condition twice, worse readability.
5. What workarounds are you using in the meantime?
A conditional type
```ts
type FirstWord<T extends `${string} ${string}`> = T extends `${infer Result} ${string}` ? Result : never;
```

**Comment by MartinJohns** [comment] 2024-07-06 11:40
Duplicate of #39736. Used search terms: `infer constraint in:title`

**Closed** 2024-07-12 01:30 UTC
Labels: Duplicate
