### ISSUE TITLE
Object result of import all from module has no index signature

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#16248] opened 2017-06-04 11:30 UTC
**TypeScript Version:**  2.3.4

Given an `actions` module where each exported member satisfies the type `type MyFn = (...args: any[]) => any`, when I collect those exports using `import *`, the resulting object has no index signature, leading to unwanted type errors.

**Code**

```ts
import * as actions from 'actions';
type MyFn = (...args: any[]) => any;
type MyMap = { [key: string]: MyFn };
const myMap: MyMap = actions;
```

**Expected behavior:**
No error.

**Actual behavior:**
```
Type 'typeof "/Users/OliverJAsh/Development/unsplash-web/app/actions/index"' is not assignable to type 'MyMap'.
  Index signature is missing in type 'typeof "/Users/OliverJAsh/Development/unsplash-web/app/actions/index"'.
```

**Comment by OliverJAsh** [comment] 2017-06-04 11:32
One workaround is to spread the object:

``` ts
import * as actions from 'actions';
type MyFn = (...args: any[]) => any;
type MyMap = { [key: string]: MyFn };
const myMap: MyMap = actions; // error
const myMap2: MyMap = { ...actions }; // no error!
```

**Comment by anticrisis** [comment] 2017-06-06 08:25
Just ran into the same problem. Thanks for the workaround.

**Comment by mhegazy** [comment] 2017-08-23 16:40
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/17622

**Comment by mhegazy** [comment] 2017-09-07 17:44
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-07 17:44 UTC
Labels: Duplicate
