### ISSUE TITLE
returning new Class Expression, returns constructor instead of instance

### ISSUE THREAD

**Issue by michalstocki** [Microsoft/TypeScript#6619] opened 2016-01-26 08:02 UTC
The problem I found can be reproduced with the [following code](http://www.typescriptlang.org/Playground#src=function%20builder()%20%7B%0D%0A%09return%20new%20class%20House%20%7B%0D%0A%09%09public%20open()%3Avoid%20%7B%0D%0A%09%09%09console.info('house%20is%20open')%3B%0D%0A%09%09%7D%0D%0A%09%7D%0D%0A%7D%0D%0Aconst%20house%20%3D%20builder()%3B%0D%0Ahouse.open()%3B), on typescript version 1.7.5. The problem exists in typescript from the release when class expressions (#497) were introduced.

```typescript
function builder() {
	return new class House {
		public open():void {
			console.info('house is open');
		}
	}
}
const house = builder();
house.open();
```
is compiled to 
```javascript
function builder() {
    return new (function () {
        function House() {
        }
        House.prototype.open = function () {
            console.info('house is open');
        };
        return House;
    })();
}
var house = builder();
house.open();
```
and looks good, but throws in the console:
```
Uncaught TypeError: house.open is not a function
```
Thats, because from `builder()` is returned constructor of `House` instead of an instance. The example above works, [when we assign constructor to a variable](http://www.typescriptlang.org/Playground#src=function%20builder()%20%7B%0D%0A%09const%20houseConstructor%20%3D%20class%20House%20%7B%0D%0A%09%09public%20open()%3Avoid%20%7B%0D%0A%09%09%09console.info('house%20is%20open')%3B%0D%0A%09%09%7D%0D%0A%09%7D%0D%0A%09return%20new%20houseConstructor()%3B%0D%0A%7D%0D%0Aconst%20house%20%3D%20builder()%3B%0D%0Ahouse.open()%3B) and then, create instance with the `new` keyword.

**Comment by ahejlsberg** [comment] 2016-01-26 14:45
Duplicate of #4630. It was fixed in #6004 and your example works with current compiler in master.

**Closed by ahejlsberg** 2016-01-26 14:45 UTC
