### ISSUE TITLE
HTML string inside TypeScript and JavaScript files

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#6778] opened 2016-02-01 08:54 UTC
Copied from https://github.com/Microsoft/vscode/issues/2000

When using Angular 2 and TypeScript I noticed that editing `template` strings of components in TypeScript files are not working as one expect. There is not autocomplete for tags and other usual HTML editing features. 

For example

```ts
import {Component} from 'angular2/core';

@Component({
    selector: 'my-app',
    template: '<h1>My First Angular 2 App</h1>'
})
export class AppComponent { }
```

Of course it's because the type definition has declared `template` as a String and no part of VSCode knows that it's an HTML string.

My proposal is to define a `HTMLString` type where it's basically just string but helps tooling in cases like this.

If it was possible to do this, then we can define `CSSString`, `JavaScriptString`, `SCSSString` and so on...

**Comment by dbaeumer** [comment] 2016-02-01 08:55
What is the take of the TS team on this?

**Comment by DanielRosenwasser** [comment] 2016-02-01 09:25
See also #6508

**Comment by mhegazy** [comment] 2016-02-01 17:29
this looks like a duplicate of #4856. please see my reply in https://github.com/Microsoft/TypeScript/issues/4856#issuecomment-141552809. the possible change here is as @DanielRosenwasser mentioned by allowing extensibility for the typescript language service.

**Closed by mhegazy** 2016-02-01 17:29 UTC
