### ISSUE TITLE
Inferring and typeof at the same time loses inference

### ISSUE THREAD

**Issue by darklight9811** [microsoft/TypeScript#51264] opened 2022-10-21 16:39 UTC
# Bug Report

If you both infer a value from usage and use a typeof, it loses it's inference capability

### 🔎 Search Terms

```
infer, typeof
```

### 🕗 Version & Regression Information

Present on all versions I used (4.8.4, 4.4.2). It doesn't crash, it just fallback to the method inference extension.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABCADgEwIZQKaIBQDW2AngFyIDOUATjGAOYA0iAbhgDYjbkZjECUiAN4BYAFDiAvuPGhIsBIgBGIGOzTZqAHgCy2KAAs4aComwAPHGBOIAStghxqaLVVoNmvYgD5veCErk-lDm5ELI6FjciFDEKNhwwBGYOIiSggC83oh6hsYUgqJiiCWI1Pog1EgBeOGoKbjpUjJijmBUZdgUIOxQiBnKquqaweb92bUxXVDkAEQAVnAGYLPMOFQATPiFkmn8-EA)

### 💻 Code

```ts
function update (key: string, value: any) {

}

function builder<Methods extends Record<string, any>>(cb: (ctx: { update: typeof update }) => Methods) {
    return cb({ update })
}

const result = builder(ctx => ({ test: "john", test2 () {} }))
```

### 🙁 Actual behavior

result's type returns `Record<string, any>>`

### 🙂 Expected behavior

result's type should return `{ test: string; test2(): void }`, for this to happen, you just need to remove `update: typeof update` of the code

**Comment by ahejlsberg** [comment] 2022-10-23 14:37
This is a duplicate of #48134. It is fixed in the nightly builds and will be in 4.9.

**Closed** 2022-10-24 17:36 UTC
Labels: Duplicate, Fixed
