### ISSUE TITLE
Visual Studio JS completion blocks main thread leading to typing delays

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#3199] opened 2015-05-18 13:22 UTC
![vs_main_thread](https://cloud.githubusercontent.com/assets/4499495/7681497/089ea55e-fd71-11e4-8532-0f2ced02d667.png)

Typing in JS editor is sometimes very laggy. I took a snapshot using dotTrace Timeline, and it shows that some Visual Studio's activity locks the main thread, leading to slowdowns.

I don't know whether JS editor is powered by the same engine as TS editor, that's why I create the request here. If it's a wrong place, I'm sorry, and please redirect it to the JS team in Visual Studio project. Thanks a lot!

**Comment by zhuravlikjb** [comment] 2015-05-18 13:36
VS 2015 Enterprise RC

Full snapshot: https://www.dropbox.com/s/qnbxq58wrj3qsgx/vs_lags.zip?dl=0

**Comment by mhegazy** [comment] 2015-05-18 17:09
@zhuravlikjb can you share some details about the project you are using? @vladima is looking into similar issues with large projects, and any details would help in getting the right fix in.

**Comment by zhuravlikjb** [comment] 2015-05-18 18:05
Solution is here: https://www.dropbox.com/s/70q69ngmg1e19fu/Messenger.zip?dl=0
file "Silly.js"
type "length.length.length.length.length"

ReSharper is enabled in VS.
From time to time, VS freezes for a few moments.
Several profiler snapshots had shown the same picture as attached, with VS operations taking most of time on main thread.
No such problems with VS2013, with the same version of ReSharper, everything is fast.

If to disable ReSharper, some lag is still seen before VS completion appears, though it's smaller and less visible (seems that ReSharper allows VS to finish its activities before showing it's own completion, and that's why with it this lag becomes really bad).

Perhaps, VS-completion in this case doesn't feel good when something else is doing text operations on the text control.

If you need some extra snapshots (e.g., in tracing mode), I'll do them.

**Comment by NoelAbrahams** [comment] 2015-05-19 10:26
This is similar to the problem I'm having, but with TypeScript files #3054

**Comment by mhegazy** [comment] 2015-05-19 22:13
just as a clarification, blocking the UI thread is the expected behavior. The issue we need to look into is why the completion list is taking that long to show up.

**Comment by mhegazy** [comment] 2015-05-19 22:44
marking it as external since the JS and TS intellisense implementations are different. @billti what do you want to do with this issue?

**Closed** 2015-08-11 00:05 UTC
Labels: External
