### ISSUE TITLE
"useDefineForClassFields" compiles invalid code which fails at runtime.

### ISSUE THREAD

**Issue by AlexanderFarkas** [microsoft/TypeScript#57543] opened 2024-02-26 13:23 UTC
### 🔎 Search Terms

"useDefineForClassFields" "vite" "esbuild" "invalid initialization order" "property initializers are executed before constructor initializers"

### 🕗 Version & Regression Information

Version 5.3.3, tried 5.4-beta with the same bug.

### ⏯ Playground Link

https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99&resolvePackageJsonImports=false&ts=5.3.3#code/LAKAxgNghgzjAEBBeBvU95gPYDsYBcAnAVzHy0IAoAHQgSwDcp8BTeKALlSgFstic+LjmI8ARi0IBfAJSp0GTLhhYILAHQQsAc0r4AFnRjqwMgNwKpoBdpb54YynLQhF8QneKEcGA0fVQAXwC+Bau8FYgCmDCohKE8AC88H7GYvAAVPAAzGGRoDgsAO5IlCi8-IJc2bJmQA

### 💻 Code

```ts
class A {
  constructor(private a: {amount: number}) {
    console.log(this.c);
  }

  get b() {
    return  this.a.amount;
  }

  c: number = this.b * 3;
}

new A({amount: 3});
```

### 🙁 Actual behavior

When I run the code, it fails with 
```
[ERR]: Cannot read properties of undefined (reading 'amount') 
```

### 🙂 Expected behavior

Code shouldn't compile

**Comment by MartinJohns** [comment] 2024-02-26 14:07
Related: #55132

**Comment by rbuckton** [comment] 2024-02-28 16:33
This is a duplicate of #55132

**Closed by rbuckton** 2024-02-28 16:33 UTC
Labels: Duplicate, Needs Investigation
