### ISSUE TITLE
Implicit Member Expression with Leading Dot Notation for Member Access

### ISSUE THREAD

**Issue by NoodleOfDeath** [microsoft/TypeScript#50611] opened 2022-09-02 14:56 UTC
# ⭐ Suggestion

### Current Implementation

I feel like this is not a huge ask since the following can already be done but it's a bit ungly having to use type unions and conditionals:

`stroke.ts`
```typescript
enum Color {
  red   = '#ff0000',
  green = '#00ff00',
  blue  = '#0000ff',
}

export let globalStroke = Color.red;
export default function setStroke(color: keyof Color | Color) {
  globalStroke = (typeof color === 'string') ? Color[color] : color;
}
```

`index.ts`
```typescript
import setStroke, { globalStroke } from './stroke.ts';

console.log(globalStroke); // Color.red

setStroke('green');
console.log(globalStroke); // Color.green
```

### Preferred Implementation

`stroke.ts`
```typescript
enum Color {
  red   = '#ff0000',
  green = '#00ff00',
  blue  = '#0000ff',
}

// Notice the leading dot notation, because I 
// explicitly provided the `Color` type already
export let globalStroke: Color = .red;
export default function setStroke(color: Color) {
  globalStroke = color;
}
```

`index.ts`
```typescript
import setStroke, { globalStroke } from './stroke.ts';

console.log(globalStroke); // Color.red

// No need to import `Color` to access member `.green`
setStroke(.green);
console.log(globalStroke); // Color.green
```

##  🔍 Search Terms

- dot access typescript
- dot member typescript
- dot notation typescript
- dot syntax typescript
- implicit access typescript
- implicit member typescript
- implicit types typescript
- leading dot typescript
- shorthand member access typescript

## ⭐ Suggestion

> Leading Dot Access to Members Added! No need to import all of your enums and classes just to access properties and methods of already implicitly known types!

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2022-09-02 15:02
Duplicate of #45956.

**Closed** 2022-09-02 17:24 UTC

**Comment by NoodleOfDeath** [comment] 2022-09-22 15:11
@fatcerberus could this be supported for `static` methods of classes?

```typescript
class MyClass {
  name: string;
  constructor(name: string) {
    this.name = name;
  }
  static default() { return new MyClass('defaut-name'); }
}

const a: MyClass = .default();
```
