### ISSUE TITLE
"bind" and ES3 - no compiler warning

### ISSUE THREAD

**Issue by Vadorequest** [Microsoft/TypeScript#3321] opened 2015-05-31 16:00 UTC
I ran into some issue because I used `bind` which is ES5 compatible while targeting `ES3`. 

The problem is that the compiler didn't gave me any warning, so it worked fine until I tested the code on IE8.

Shouldn't the compiler warn us when we use such incompatible functions that aren't available for the targeted version? I thought it did.

**Comment by mhegazy** [comment] 2015-06-01 17:21
The problem is there is no ES3 version of lib.d.ts, you can create a local copy for IE8/ES3 that would not have definition for bind as well as other APIs then add it to your compilation along with `--noLib`; this will tell the compiler to not use the default lib.d.ts and use yours. and use of bind will be an error.

**Comment by Vadorequest** [comment] 2015-06-01 17:23
Oh, interesting, I thought that whas done behind the scene by the compiler,
to apply a specific version of lib.d.ts depending on the targeted version.
I guess that's the case, excepted for ES3, too old maybe.

Thanks for the insight!

2015-06-01 19:21 GMT+02:00 Mohamed Hegazy <notifications@github.com>:

> The problem is there is no ES3 version of lib.d.ts, you can create a local
> copy for IE8/ES3 that would not have definition for bind as well as other
> APIs then add it to your compilation along with --noLib; this will tell
> the compiler to not use the default lib.d.ts and use yours. and use of bind
> will be an error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/TypeScript/issues/3321#issuecomment-107644534>
> .
>



-- 
Cordialement,

M. Ambroise Dhenain.

**Comment by kitsonk** [comment] 2015-06-01 17:33
I think the bigger problem is that while ES5 has some very clear features that were essentially universally implemented, ES3, while it was a standard, in practice everything varied greatly from it and there was a lot of stuff that was implemented that wasn't formally part of ES3.  If you tried to create an authoritative set of what was ES3 which was then shared by every "non-modern" browser, you might have only ended up with a lib.d.ts that had one line of `declare var window: any;`

**Comment by Vadorequest** [comment] 2015-06-01 17:36
XD

Encouraging! I understand now why they didn't do it for ES3 directly.
It sucks to have to support old browsers like IE8, really sucks. Hopefully
we'll get rid of IE7-19 soon...

**Comment by mhegazy** [comment] 2015-06-01 17:37
I think it is fine to have a lib.ie8.d.ts on definitelyTyped that users with a constraint on IE8 can get the compiler to help out.

**Comment by mhegazy** [comment] 2015-06-12 18:57
closing this issue for now, please reopen if there further details needed.

**Closed by mhegazy** 2015-06-12 18:57 UTC
Labels: Question
