### ISSUE TITLE
Varargs doesn't inherit overloads properly.

### ISSUE THREAD

**Issue by Griffork** [microsoft/TypeScript#41558] opened 2020-11-17 06:01 UTC
**TypeScript Version:**  
- Playground 4.1.0 beta with ESNext types.
- 3.9.x

**Search Terms:** ...args, call, typescript, varargs.

**Code**

```ts
type foo = ((val: true, obj: any)=>void) & ((val: false)=>void);
var test!: foo;
test(true, {});
test(false);
test.call(window, true, {}); //This errors, and shouldn't.
test.call(window, false);
```

[Playground Link](https://www.typescriptlang.org/play?target=99&jsx=0&ts=4.1.0-beta#code/LAKALgngDgpgBAMwPZLgXjgCkwNwIYA2AXHGAE4CuMANHEgEYBWJeAdhAJRoB8OSAlgBMOcAGRZchEgkIBnGF14DhAblD4ypGLLABCaSjXhtYTOSq0A3gF8ORsCcwyC8u6Ac6AdAGNCBTADu-KyCSAG05jRwNm7GXr4E-kEhYbTOripAA)

**Expected behavior:**
test.call with 3 arguments doesn't error.

**Actual behavior:**
test.call with 3 arguments does error, because typescript force-chooses the last overload of an overloaded method.

**Related Issues:** 
This issue is impossible to search for because "...args" and "call" are such generic terms, that a bunch of unrelated issues come up in the search result. I did go looking for duplicates but there is a high possibility that there's a duplicate out there that  I wasn't able to find.

**Comment by jcalz** [comment] 2020-11-17 13:43
Duplicate of #38353, putting "overload" in the search term found it for me.

**Comment by Griffork** [comment] 2020-11-19 00:49
Thanks! I didn't try searching for that word on it's own.

**Closed** 2020-11-21 18:00 UTC
Labels: Duplicate
