### ISSUE TITLE
Destructuring assignment doesn't narrow undefined, inconsistent with regular property access

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/TypeScript#10846] opened 2016-09-10 23:45 UTC
**TypeScript Version:**  2.1.0-dev.20160910

**Code**

```ts
declare const foo: { bar: string | undefined };

if (foo.bar !== undefined) {
	foo.bar.length; // Property access (1)
}

if (foo.bar !== undefined) {
	const bar = foo.bar; // Property access
	bar.length; // (2)
}

if (foo.bar !== undefined) {
	const { bar } = foo; // Destructuring assignment
	bar.length; // (3)
}
```

`tsc -t es5 -m amd --strictNullChecks ./foo.ts`

**Expected behavior:**

All three compile, or all three complain that `.length` is being invoked on `string | undefined`

**Actual behavior:** 

Only (3) complains that `error TS2532: Object is possibly 'undefined'.` In (1) `foo.bar` is inferred as `string`, and thus in (2) `bar` is also inferred as `string`. But in (3) `bar` is `string | undefined`

---

I'm actually surprised that a check on `foo.bar` narrows it down within the `if` blocks at all, since I remember this only used to narrow bindings. I guess this changed at some point to support narrowing properties, but then it should also narrow (3) identically to (2).

**Comment by mhegazy** [comment] 2016-09-21 04:04
This is essentially the same as https://github.com/Microsoft/TypeScript/issues/10065. control flow analysis only narrows the type of the right most symbol. in this case `foo.bar`; it does not narrow the type of `foo` to `{bar: string}`. the first two cases you check on `foo.bar` and you use `foo.bar` so no issues, in the third you are looking at the type of `foo`. since it was not narrowed, you get the original type, and thus `bar` is still `string | undefined`.

closing as a duplicate of https://github.com/Microsoft/TypeScript/issues/10065

**Closed by mhegazy** 2016-09-21 04:04 UTC
Labels: Bug
