### ISSUE TITLE
Type of a generic is not narrowed

### ISSUE THREAD

**Issue by Nlicro** [microsoft/TypeScript#60245] opened 2024-10-16 17:50 UTC
### 🔎 Search Terms

generic narrowed class instance enum

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about narrowed.

### 💻 Code

```ts
enum Tag {
  A,
  B,
  C,
}

interface InterfaceByTag {
  [Tag.A]: {
    type: string;
  };
  [Tag.B]: {
    type: number;
  };
  [Tag.C]: {
    type: boolean;
  };
}

class C<
  T extends Tag = Tag,
> {
  tag: T;
  type: InterfaceByTag[T]["type"];

  constructor(tag: T, type: InterfaceByTag[T]["type"]) {
    this.tag = tag;
    this.type = type;
  }
}

const tagIsA = new C(Tag.A, "string");
const tagIsAError = new C(Tag.A, 123);

function test(instance: C) {
  switch (instance.tag) {
    case Tag.A: {
      const type = instance.type; // should get string, but get string | number | boolean.
      break;
    }
    case Tag.B: {
      const type = instance.type; // Same as above
      break;
    }
    case Tag.C: {
      const type = instance.type; // Same as above
      break;
    }
  }
}
```

### 🙁 Actual behavior

It is not narrowed in the switch statement. In all case, the type of `instance.type` is `string | number | boolean`.

### 🙂 Expected behavior

I think the specific type has been identified In the switch statement. What I expected:
```ts
  switch (instance.tag) {
    case Tag.A: {
      const type = instance.type; // string
      break;
    }
    case Tag.B: {
      const type = instance.type; // number
      break;
    }
    case Tag.C: {
      const type = instance.type; // boolean
      break;
    }
  }
```

**Comment by MartinJohns** [comment] 2024-10-16 17:54
This is working as intended. You do not specify the type parameter for `C` in your `test` function, so it falls back to the default `Tag`. That means the type is `C<Tag>`, which results in the type `{ tag: Tag, type: string | number | boolean }`. This is not a union type that can be narrowed.

**Comment by Nlicro** [comment] 2024-10-16 18:16
> This is working as intended. You do not specify the type parameter for `C` in your `test` function, so it falls back to the default `Tag`. That means the type is `C<Tag>`, which results in the type `{ tag: Tag, type: string | number | boolean }`. This is not a union type that can be narrowed.

I'm sorry that my example is a little wrong and you misunderstood it. I have updated the code. I mean the type in the switch statement, not the return type of `test` function

**Comment by MartinJohns** [comment] 2024-10-16 18:34
> you misunderstood it.

I did not. The type of `instance` is `C<Tag>`, which results in the type `{ tag: Tag, type: string | number | boolean }`. It's **not** the type `{ tag: Tag.A, type: string } | { tag: Tag.A, type: number } | { tag: Tag.C, type: boolean }`, so it can't be narrowed the way you expect it to. It's perfectly valid to have the value `{ tag: Tag.A, type: true }` assigned to `C<Tag>`.

**Comment by Nlicro** [comment] 2024-10-17 04:09
> > you misunderstood it.
> 
> I did not. The type of `instance` is `C<Tag>`, which results in the type `{ tag: Tag, type: string | number | boolean }`. It's **not** the type `{ tag: Tag.A, type: string } | { tag: Tag.A, type: number } | { tag: Tag.C, type: boolean }`, so it can't be narrowed the way you expect it to. It's perfectly valid to have the value `{ tag: Tag.A, type: true }` assigned to `C<Tag>`.

I see. Thank you for your explanation.
Now I'm using `is` to narrow it. But as the number of enumerations grows and each `is` function needs to be defined, the if expression looks unpretty:
```ts
function isTagA(instance: C): instance is C<Tag.A> {
  return instance.tag === Tag.A;
}

function test(instance: C) {
  if (isTagA(instance)) {
    const type = instance.type; // string
  } else if(isTagB(instance)) {}
  // more...
}
```
I tried to refactor it in other ways like using `switch`, and here's the problem. 
Is there any way to associate the type of `tag` with  the type of `type`? I have no idea because  the type of `C` is a class instance and cannot be turned into a union type.

**Comment by MartinJohns** [comment] 2024-10-17 06:22
This approach is unsafe, as it does not align with your types. Again, `{ tag: tag.A, type: true }` is a perfectly valid assignment to the type `C`, but using your `isTagA` type guard it would wrongly assume the type of `type` is `string`, when it's actually `boolean`.

You seem to wrongly assume that `InterfaceByTag[T]["type"]` is a type depending on what's assigned to `tag`, but that's not the case. The type depends on whatever `T` is, which can be a union type as well - and actually is a union type when your type argument defaults to `Tag`.

You need to use a union of the types you want:
- `C<Tag.A> | C<Tag.B> | C<Tag.C>`, which results in `{ tag: Tag.A, type: string } | { tag: Tag.A, type: number } | { tag: Tag.C, type: boolean }`
- **not** `C<Tag>` or `C` (they're the same), which results in `{ tag: Tag, type: string | number | boolean }`

You could use a helper type and make use of distributive conditional types to get a union based on your tags: `type AllTagC<T extends Tag> = T extends Tag ? C<T> : never`  
Then use it: `function test(instance: AllTagC<Tag>) { ... }`

It's crucial to understand what structure your types actually look like.

**Closed** 2024-10-20 01:32 UTC
Labels: Question
