### ISSUE TITLE
Use local compiler if available in node_modules

### ISSUE THREAD

**Issue by borekb** [Microsoft/TypeScript#12063] opened 2016-11-05 13:03 UTC
I'd like to install TypeScript globally but when I execute `tsc` in a folder that has `node_modules/.bin/tsc` available, I'd like this local version to be used.

This would save me from writing a `npm run tsc` (or similar) task and, more importantly, instructing all the colleagues to use it instead of plain `tsc`.

**Comment by alitaheri** [comment] 2016-11-05 13:10
Sometimes one might need the globally installed tsc to compile the code. Maybe an option in `tsconfig` like `compilerPath` would be good. It can also help those who want to test typescript and install it as a git submodule.

**Comment by mhegazy** [comment] 2016-11-07 20:14
Duplicate of https://github.com/Microsoft/TypeScript/issues/5157. We can not do this because of npm v3 flattening. see response in https://github.com/Microsoft/TypeScript/pull/5465#issuecomment-152669949

**Closed by mhegazy** 2016-11-07 20:14 UTC

**Comment by borekb** [comment] 2016-11-07 20:21
I'm not sure I get the reason. If in my `tsconfig.json` was something like

```
"tsc": "./node_modules/.bin/tsc"
```

or, even better, some boolean key like `preferLocalTsc`, it would always try to resolve as `./node_modules/.bin/tsc` and fall back to the global `tsc`. It seems pretty deterministic to me.

**Comment by shivamsngh** [comment] 2018-05-28 12:08
People coming to this thread, please use "npx tsc" to use the local typescript (from node modules).
