### ISSUE TITLE
`unknown` narrowing works by checking type but not by assigning typed value

### ISSUE THREAD

**Issue by yukulele** [microsoft/TypeScript#57459] opened 2024-02-21 09:44 UTC
### 🔎 Search Terms

"unknown" "narrowing"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "narrow" or "unknown"

### ⏯ Playground Link

https://www.typescriptlang.org/fr/play?useUnknownInCatchVariables=true&ts=5.3.3#code/GYVwdgxgLglg9mABACwIZgCYBsCmBBAJwNQE8BGAClSNIC5FwBrMOAdzAEpEBvAKEQGIYwCgEJCxEgDoYAZwmkqNEhy4EcUEASTVJASTDA4FANq7SAXQ79B6zdsTmSBo0slcA9B8SA+DcAne4iyyHAgWBiIAEY4iAAGTCzsJhYxNgJeghmZGQB6APy8AL68vKCQsAgo6Nj4ygBMbnQMYMxsnDypjsqIALyIZsoWHXZaOsouxk6e3oCcZIDwf4HBoeFRsfGtSSkZ6Vk7AnmFxaXQ8EhomLgKJADMDST0a+xcfBnCYpcy8sq3qp2SPX1OQYZYYOJzjb6IdJzBYhMKRaJxZoJMAbDrbXZZfZFQ7gY4VMGGCbKe5I9ZWdrAjQjWJORC4MAAcygyHoABJuE4pPSmcgCikCkA

### 💻 Code

```typescript
function handleArray1(array: unknown) {
    if(!Array.isArray(array)) return arrayInfo([array])
    return arrayInfo(array) // :/ `array` type is `any[]` (shouldn't be `unknown[]`?)
}

function handleArray2(array: unknown) {
    array = [array]
    return arrayInfo(array) // :( `array` type is `unknown` (should be `unknown[]`)
}

function handleArray3(array: unknown) {
    if(!Array.isArray(array)) array = [array]
    return arrayInfo(array) // :( `array` type is `unknown` (should be `unknown[]`)
}


function arrayInfo(array: unknown[]) {
    return `array length: ${array.length}`
}
```

### 🙁 Actual behavior

`array` keep `unknown` type

### 🙂 Expected behavior

`array` type should be narrowed to `unknown[]`

### Additional information about the issue

by way of comparison, we can see that narrowing works for type `number | string`

by checking type:
```typescript
let a = Math.random() >.5 ? 123 : 'abc'
if (typeof a !== 'string') throw 'not a string'
a.toUpperCase()
```

or by assigning typed value:
```typescript
let a = Math.random() >.5 ? 123 : 'abc'
a = "foo"
a.toUpperCase()
```

it should work the same way when the type is unknown.
```typescript
let a = 'x' as unknown
if (typeof a !== 'string') throw 'not a string'
a.toUpperCase() // :) a is `string`
```

```typescript
let a = 0 as unknown
a = "foo"
a.toUpperCase() // :( a is `unknown`
```

[playground](https://www.typescriptlang.org/fr/play?useUnknownInCatchVariables=true&ts=5.3.3#code/PTAEDsEMCdoewO4EtwHNQLtA1gZ1AGZagAuAngA4CmoABuAK4C2ARldKAD6i4nQqpaAKCEAbKiR58BAeWgA5Zm2gBGUAF5QAWUgkAFgDpokcABM4TABQBKUAD4DAVlAB+UCoBMAZlAAuUADkkCwAxgFCIKAsZKAhelQh2AKklFS+QkgEoJbk1HBZvPxocoqs7GoAhOqaAYUCAbb68AiB4HCSkFJFqAGgQnXFCkrlBiRwAKoU1NAAwpC4VDYRYAB6LiLikgOoJcPQHhrauobGZhY29k6u7t5+gcFhy6DE0aDzuEio4Mm5VKagADdIKIGGl+tJBqVlAdNAAiIhwWF9ba7Mr7UYTKbsOYLJaRNYiJ5ILZ6OAMUT-TA4UjxHiQJg0BCQGIIeLgGk0X6gJD4BjgbBtBDgAwbCSgPkCxDgNQ1AAevXm4v5gvAT1ecQSSTQKWo2SpeGs6Uy2V++SVkqFlWqgW2DRpzVa7TeXXqQglKpUGMm0xxi2sTwJYjF7qlMNAAAY3rzlVKni8Yu9Pt9tb9-kCQTRLOYqLhwAFJPrcIa3TGhWH4XBESWLeAPF6sbN5n6A+sgA)

**Comment by MartinJohns** [comment] 2024-02-21 10:11
Duplicate of #43584.

**Closed** 2024-02-24 01:22 UTC
Labels: Duplicate
