### ISSUE TITLE
error TS1206: Decorators are not valid here. in anonymous class

### ISSUE THREAD

**Issue by Redvik80** [microsoft/TypeScript#51507] opened 2022-11-13 21:18 UTC
```
function testDecorator(target: any, key: string) {
    console.log(target, key);
}

export const testMixin = (superClass: any = Object) => class extends superClass {
    @testDecorator testField: string;
}
```
This produces the following compiler error:
`error TS1206: Decorators are not valid here.`

```
export const testMixin = (superClass: any = Object) => {
    class Mixin extends superClass {
        @testDecorator testField: string;
    }
    return Mixin;
}
```
In the second case, there are no problems.

**Comment by MartinJohns** [comment] 2022-11-13 22:47
Duplicate of #7342.

**Closed** 2022-11-20 18:00 UTC
Labels: Duplicate
