### ISSUE TITLE
Unable to make use of string literal types to type guard/narrow optional properties.

### ISSUE THREAD

**Issue by cliffkoh** [Microsoft/TypeScript#25491] opened 2018-07-06 22:22 UTC
**TypeScript Version:**  3.0.0-dev.20180705

**Search Terms:**  type guard string literal optional parameter

**Code**

```ts
interface Foo {
    Bar?: string;
}

const BAR_NAME: 'Bar' = 'Bar';

declare let foo: Foo;
if(foo[BAR_NAME] !== undefined){
    foo.Bar.length;
}
```

Alternatively
```ts
const BAR_NAME: 'Bar' = 'Bar';

interface Foo {
    [BAR_NAME]?: string;
}

declare let foo: Foo;
if(foo[BAR_NAME] !== undefined){
    foo.Bar.length;
}
```

**Expected behavior:**
Given the check for foo["bar"], the type guard should have gotten rid of the `undefined` and narrowed `foo.bar` to be of type `string`.

**Actual behavior:**
```
tmp.ts:10:5 - error TS2532: Object is possibly 'undefined'.

10     foo.Bar.length;
       ~~~~~~~
```

**Playground Link:** [Link](https://www.typescriptlang.org/play/#src=const%20BAR_NAME%3A%20'Bar'%20%3D%20'Bar'%3B%0D%0A%0D%0Ainterface%20Foo%20%7B%0D%0A%20%20%20%20%5BBAR_NAME%5D%3F%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20let%20foo%3A%20Foo%3B%0D%0Aif(foo%5BBAR_NAME%5D%20!%3D%3D%20undefined)%7B%0D%0A%20%20%20%20foo.Bar.length%3B%0D%0A%7D%0D%0A) (needs strictNullCheck to repro).

**Related Issues:**

**Comment by mhegazy** [comment] 2018-07-06 23:18
Duplicate of https://github.com/Microsoft/TypeScript/issues/10530

**Closed** 2018-07-06 23:20 UTC
Labels: Duplicate
