### ISSUE TITLE
With "Organize Imports," sort by the import name rather than by file path

### ISSUE THREAD

**Issue by IceCreamYou** [Microsoft/TypeScript#29016] opened 2018-12-01 00:45 UTC
The "TypeScript: Organize Imports" command sorts the imports by their file path. This means it results in something like this:

```ts
import { SearchResults } from '../components/search-results';
import { Router } from '../router/router';
import { API } from '../utils/api';
```

This is hard to scan, reducing the value of organizing the imports. What I'd like to see is:

```ts
import { API } from '../utils/api';
import { Router } from '../router/router';
import { SearchResults } from '../components/search-results';
```

**Comment by IceCreamYou** [comment] 2018-12-14 18:49
For context, this request comes from the fact that other people on my team are using [this VSCode extension](https://marketplace.visualstudio.com/items?itemName=miclo.sort-typescript-imports), and wanting to have matching / non-conflicting sort orders.

So I would sort named imports for the same file, and then sort files by the first named import:

```ts
import { API, Zebra } from '../utils/api-and-zebra';
import { Router } from '../router/router';
```

**Comment by glen-84** [comment] 2019-03-01 13:13
Duplicate of #23279.

**Closed** 2019-03-08 18:00 UTC
Labels: Duplicate
