### ISSUE TITLE
emitDecoratorMetadata does not preserve array types on fields

### ISSUE THREAD

**Issue by arciisine** [Microsoft/TypeScript#12463] opened 2016-11-23 08:35 UTC
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)
All Typescript Versions

**Code**

```ts
class Post {
     tags: string[];
}

```

**Expected behavior:**
There should be metadata added to indicate the type of array.  
```js
class Post {
   constructor() {}
}
__decorate([
    __metadata('design:type', [String])
], Post.prototype, "tags", void 0);
```
**Actual behavior:**
```js
class Post {
   constructor() {}
}
__decorate([
    __metadata('design:type', Array)
], Post.prototype, "tags", void 0);
```

If you look at how rest parameters are handled, there is precedent for preserving array type:

**Given:**
```ts
class Post {
     tags: string[];
     constructor(...tags:string[]) {}
}
```

**The output is:**
```ts
class Post {
   constructor() {}
}
__decorate([
    __metadata('design:type', Array)
], Post.prototype, "tags", void 0);
Post = __decorate([    
    __metadata('design:paramtypes', [String])
], Post);
```

**Comment by arciisine** [comment] 2016-12-06 01:55
@rbuckton It looks like you have done a great deal of the work on the file (src/compiler/transformers/ts.ts).  Do you know if PRs would be accepted for this change, or if this change is even acceptable?

**Comment by arciisine** [comment] 2016-12-19 22:09
So after thinking about this for a bit, I realized that the param types is actually reducing `string[]` to `String` to handle the variadic arguments.  Would it be possible to treat the array as a generic class? `Array<string>`, and perhaps store all generic types in the metadata?

**Comment by DanielRosenwasser** [comment] 2016-12-20 23:52
Closing as a duplicate of #3015.

**Closed** 2016-12-21 00:33 UTC
Labels: Duplicate
