### ISSUE TITLE
Tooltip drill down

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#13304] opened 2017-01-05 22:17 UTC
_From @unional on January 4, 2017 2:14_

- VSCode Version: 1.8.0
Steps to Reproduce:
```ts
interface FooOption {
  /**
   * Doing boo stuff
   */
  boo(x: number): boolean
}

function foo(option: FooOption) {

}

foo({
  boo()
})
```
![image](https://cloud.githubusercontent.com/assets/3254987/21629779/2145d0a6-d1e0-11e6-965c-e674fe53d86d.png)

![image](https://cloud.githubusercontent.com/assets/3254987/21629764/08958916-d1e0-11e6-975a-87a74eb3f80c.png)

Currently, autocomplete is doing a better job than the tooltip. When you type `boo`, autocomplete gets the definition of `boo` and display it. But once you type `(`, it falls back to the tooltips and only show the tooltip of `foo(...)` instead. 

It would be nice to have the tooltips shows the info for `boo()`. 🌷 

_Copied from original issue: Microsoft/vscode#18070_

**Comment by mjbvz** [comment] 2017-01-05 22:17
_From @sandy081 on January 4, 2017 9:31_

@unional This is happening because you are not accessing function `boo` using object of type `FooOption`. If you does that tool tip provides you proper information.

**Comment by mjbvz** [comment] 2017-01-05 22:17
_From @unional on January 4, 2017 18:54_

Yes, I understand it is not:

```ts
let b: FooOption;
b.boo(
      ^ cursor here
```

However it is very common practice in JS to do this kind of option bag, and it would be better to drill down and display the same information in this scenario.

**Comment by mjbvz** [comment] 2017-01-05 22:17
_From @sandy081 on January 5, 2017 13:13_

I see. Reopening and assigning to correct owner to provide correct feedback on this.

**Comment by mjbvz** [comment] 2017-01-05 22:19
After investingating, it seems like TS is returning the wrong signigutreHelp response in this case. For the code:

```ts
interface FooOption {
  /**
   * Doing boo stuff
   */
  boo(x: number): boolean
}

function foo(option: FooOption) {

}

foo({
boo| {
  return false;
}
})
```

By typing `(` as the location of the `|` character on line 13, we see the following:

```
Trace - 2:18:02 PM] Sending request: signatureHelp (395). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/sand/bla.ts",
    "line": 13,
    "offset": 5
}
[Trace - 2:18:02 PM] Response received: signatureHelp (395). Request took 2 ms. Success: true 
Result: {
    "items": [
        {
            "isVariadic": false,
            "prefixDisplayParts": [
                {
                    "text": "foo",
                    "kind": "functionName"
                },
                {
                    "text": "(",
                    "kind": "punctuation"
                }
            ],
            "suffixDisplayParts": [
                {
                    "text": ")",
                    "kind": "punctuation"
                },
                {
                    "text": ":",
                    "kind": "punctuation"
                },
                {
                    "text": " ",
                    "kind": "space"
                },
                {
                    "text": "void",
                    "kind": "keyword"
                }
            ],
            "separatorDisplayParts": [
                {
                    "text": ",",
                    "kind": "punctuation"
                },
                {
                    "text": " ",
                    "kind": "space"
                }
            ],
            "parameters": [
                {
                    "name": "option",
                    "documentation": [],
                    "displayParts": [
                        {
                            "text": "option",
                            "kind": "parameterName"
                        },
                        {
                            "text": ":",
                            "kind": "punctuation"
                        },
                        {
                            "text": " ",
                            "kind": "space"
                        },
                        {
                            "text": "FooOption",
                            "kind": "interfaceName"
                        }
                    ],
                    "isOptional": false
                }
            ],
            "documentation": [],
            "tags": []
        }
    ],
    "applicableSpan": {
        "start": {
            "line": 12,
            "offset": 5
        },
        "end": {
            "line": 16,
            "offset": 2
        }
    },
    "selectedItemIndex": 0,
    "argumentIndex": 0,
    "argumentCount": 1
}
```


The requested `signatureHelp` position is within the `boo` function at this point, but we still get the result for `foo`

**Comment by andy-ms** [comment] 2018-07-20 00:05
I think this is a duplicate of #25265. In both cases, we should show signature help coming from a contextual signature the user should be *implementing*. Currently we only show signature help from a function you're *calling*.

**Closed by andy-ms** 2018-07-20 00:05 UTC
Labels: Bug, VS Code Tracked
