### ISSUE TITLE
TypeError: Cannot read property 'startRecordingFilesWithChangedResolutions' of undefined at InferredProject.Project.updateGraph

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#19003] opened 2017-10-07 01:03 UTC
**TypeScript Version**:
2.5.3-insiders.20170919
**VSCode Version**
1.17.0-insider
**command requested**
getApplicableRefactors
**hit count**
11993
**stack**
```
at InferredProject.Project.updateGraph in tsserver.js (line: 79253, column: 28)
at InferredProject.Project.getLanguageService in tsserver.js (line: 78994, column: 26)
at IOSession.Session.getApplicableRefactors in tsserver.js (line: 82616, column: 32)
at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) in tsserver.js (line: 81586, column: 61)
at IOSession.Session.executeWithRequestId in tsserver.js (line: 82790, column: 28)
at IOSession.Session.executeCommand in tsserver.js (line: 82799, column: 33)
at IOSession.Session.onMessage in tsserver.js (line: 82819, column: 35)
at Interface.<anonymous> in tsserver.js (line: 83945, column: 27)
at emitOne in events.js (line: 96, column: 13)
at Interface.emit in events.js (line: 191, column: 7)
at Interface._onLine in readline.js (line: 241, column: 10)
at Interface._normalWrite in readline.js (line: 384, column: 12)
at Socket.ondata in readline.js (line: 101, column: 10)
at emitOne in events.js (line: 96, column: 13)
at Socket.emit in events.js (line: 191, column: 7)
at readableAddChunk in _stream_readable.js (line: 178, column: 18)
at Socket.Readable.push in _stream_readable.js (line: 136, column: 10)
at Pipe.onread in net.js (line: 560, column: 20)
```

**Comment by sheetalkamat** [comment] 2017-10-09 19:23
resolutionCache is undefined only if project is closed. To investigate this further, it would be helpful to have tsserver log to get the information as to why closed inferred project is used to get the applicable refactors

**Comment by mhegazy** [comment] 2017-10-09 19:27
These issues are crash reports, we will not get more information from these. so we need a speculative and defensive fix here. otherwise we will need to add additional asserts.

**Comment by sheetalkamat** [comment] 2017-10-10 19:20
Duplicate of #18928

**Closed** 2017-10-10 23:01 UTC
Labels: Bug, Duplicate, Needs More Info
