### ISSUE TITLE
「Bug」multiple candidates for the same type variable in contra-variant positions causes an intersection type to be inferred

### ISSUE THREAD

**Issue by BengBu-YueZhang** [microsoft/TypeScript#34732] opened 2019-10-25 08:40 UTC
According to the https://github.com/Microsoft/TypeScript/pull/21496 PR, there should be ` string & number ` expected results

```ts
type Bar<T> = T extends { a: (x: infer U) => void; b: (x: infer U) => void } ? U : never;
type T20 = Bar<{ a: (x: string) => void; b: (x: string) => void }>; // string
type T21 = Bar<{ a: (x: string) => void; b: (x: number) => void }>; // string & number
```

However, under ts version 3.6.4, the results are not as expected

![QQ20191025-163119.png](https://i.loli.net/2019/10/25/eIShEmAX7nyxWja.png)

![QQ20191025-163934.png](https://i.loli.net/2019/10/25/PKR5d69njMq2lON.png)

**Comment by fatcerberus** [comment] 2019-10-26 14:50
`string & number` is an empty intersection (there is no value that can satisfy that type) and now collapses to `never` eagerly per #31838.  It still collapsed to `never` before that PR, but was lazy and didn't happen until the type was used in a distributive context.  Now (as of TS 3.6) it happens immediately.

**Comment by IllusionMH** [comment] 2019-10-29 12:24
Looks like duplicate of #34684

**Closed** 2019-10-30 06:09 UTC
