### ISSUE TITLE
Go to definition shows Node require statement as definition

### ISSUE THREAD

**Issue by gorgos** [microsoft/TypeScript#39895] opened 2020-08-04 03:33 UTC
I'm simply doing

```
const { calcMargin } = require('../../order-utils');
...
calcMargin()
```

and the `calcMargin` call shows two definitions: 1. the require line and 2. the actual function definition that I want to go to.

![vs-goto-small](https://user-images.githubusercontent.com/659390/89249826-ab303a80-d66f-11ea-98dd-3ebc7cc8f5d1.gif)

```
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z (1 wk ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
```

Related but not identical to https://github.com/microsoft/TypeScript/issues/37816.

**Comment by andrewbranch** [comment] 2020-08-05 18:50
@sandersn, this could be impacted by your explorations into making CommonJS requires actual alias symbols. Is that still something you’re looking at?

**Comment by sandersn** [comment] 2020-08-05 22:25
Yes, I've been distracted by other JS prototypes for 4.1, but I'll get back to it pretty soon. I'll add this bug to the list of ones to check on.

**Comment by sandersn** [comment] 2020-08-12 23:26
Well, on digging into the code, I found two things:

1. We actually have quite different code for goto-def.
2. For goto-def to work the same way as with ES imports, both `const = require` AND `module.exports=` need to create aliases. #39770 only does the former. (Alternatively, we could add more ad-hoc resolution code in gotoDefinition.ts.)

#39770 does fix find-all-refs and improves goto-def -- it jumps to the `module.exports` -- but it still doesn't jump all the way to the original declaration like ES exports to. So, although the OP's screenshot is a dupe of #25533 for find-all-refs, the title requests a goto-def fix. Let's use this bug to track that now.

**Comment by andrewbranch** [comment] 2020-09-21 19:25
> both `const = require` AND `module.exports=` need to create aliases.... (Alternatively, we could add more ad-hoc resolution code in gotoDefinition.ts.)

@sandersn do you have an opinion on which of these is a better solution? I.e., is making `module.exports` aliases valuable beyond the benefits to go-to-definition? I have a feeling that might be a bit risky for this post-beta period, but is it something we should be aiming for otherwise?

**Comment by sandersn** [comment] 2020-09-24 21:55
As of 4.0, both `module.exports.x=` and `module.exports=` create an alias for entity names and class expressions, although not for other expressions. So the rest of this fix is likely in gotoDefinition.ts -- but it's hopefully less ad-hoc than before.

Changes in goto-def are less core to the compiler, but are likely to be more complex. It's hard to guess whether this should ship in the RC without making the fix first.

**Comment by andrewbranch** [comment] 2020-09-25 22:39
I actually don’t know if this need be specific to `module.exports` or even to JavaScript. I kind of feel like we should always just jump past shorthand property assignments... maybe? They feel very alias-y, not very declaration-y.

**Comment by andrewbranch** [comment] 2020-09-28 20:21
There’s really not a lot of user feedback on this, and offering too-granular definitions is generally better than making a non-obvious leap past the definition the user was interested in (skipping past an uninteresting declaration is usually as simple as an additional ⌘-click). So, I’ll limit this to skipping past the shorthand property assignments in `module.exports = { one, two, three, ... }` as I feel confident from personal experience that those are a nuisance when they show up in go-to-definition.

**Closed** 2020-10-05 18:47 UTC
Labels: Bug, Domain: Symbol Navigation, Fix Available
