### ISSUE TITLE
Function parameters with types that are unioned with `undefined` should be optional.

### ISSUE THREAD

**Issue by legowerewolf** [microsoft/TypeScript#40930] opened 2020-10-03 22:42 UTC
**TypeScript Version:** 4.0.2

**Search Terms:**

* parameters undefined optional
* parameters union undefined should be optional

**Code**

```ts

function ex(a: number, b: number | undefined) {
    return a + (b ?? 0);
}

ex(5);

```

**Expected behavior:**

`ex(5)` should return 5, because the above signature for `ex()` should be analogous to 

```ts
function ex(a: number, b?: number);
```

**Actual behavior:**

```
Expected 2 arguments, but got 1. 
An argument for 'b' was not provided.
```

**Playground Link:** 
[Link](https://www.typescriptlang.org/play?ts=4.0.2#code/GYVwdgxgLglg9mABAUwB4AoCGAuRYQC2ARsgE4A0iRu+xZiAPouACbLAxjIsCUiA3gChEIxKWRQQpJJkQBqROiKIA-CsQAGHgG5BAX0GC06AKw6gA)

**Related Issues:**

**Comment by legowerewolf** [comment] 2020-10-03 22:44
This came up as I was working with lookup types where the type I was looking up was optional. Like this:
```ts
interface i{
   b?: number;
}

function ex(a: number, b: i["b"]) {
    return a + (b ?? 0);
}

ex(5);

**Comment by MartinJohns** [comment] 2020-10-04 09:49
Just pointing out that `arguments.length` will be different depending on an optional and a non-optional argument. But I can't think of a way that value would be used in a meaningful way.

**Comment by jcalz** [comment] 2020-10-04 14:34
Looks like a duplicate of #12400 and quite a few others.

**Closed** 2020-10-08 18:00 UTC
Labels: Duplicate
