### ISSUE TITLE
'symbol' is not allowed as an index signature parameter type

### ISSUE THREAD

**Issue by malibuzios** [Microsoft/TypeScript#7667] opened 2016-03-24 09:18 UTC
**TypeScript Version:** 

1.8.7 (ES6 mode)

**Code**
```ts
type SymbolKeysGiveNumbers = { [x: symbol]: number };
```
**Expected behavior:**
Should work

**Actual behavior:** 
`Error: an index signature parameter must be 'string' or 'number'`

However:
**Code**
```ts
let x: { [key: string]: any };
x[Symbol("abcd")] = 12;
```
**Expected behavior:**
Should not work based on the error above

**Actual behavior:** 
Works

**Conclusion**
`Symbol` type should be allowed as an index signature parameter type as in practice it is accepted as a valid index key type. Even the error message when doing something like:
```ts
let x: { [key: string]: any };
x[true] = 1;
```
includes 'symbol' as a valid option:
```
An index expression argument must be of type 'string', 'number', 'symbol' or 'any'
```

**Comment by mhegazy** [comment] 2016-03-24 16:38
duplicate of #1863

**Comment by mhegazy** [comment] 2016-03-24 16:39
![image](https://cloud.githubusercontent.com/assets/8000722/14023971/4a18b0f6-f1a4-11e5-8503-f411d0ad0624.png)

**Closed by mhegazy** 2016-03-24 16:38 UTC

**Comment by malibuzios** [comment] 2016-03-24 16:42
Sorry, I was quick to open an issue. I usually search extensively but I was so surprised the feature didn't exist so I assumed there wasn't one.. :)
