### ISSUE TITLE
Bug with type discrimination and string literal types.

### ISSUE THREAD

**Issue by johnfn** [Microsoft/TypeScript#13628] opened 2017-01-23 05:47 UTC
The following code gives an error on the assignment to x:

```
type Bar = "A" | "B"
type Foo = { key: "a", name: string } | { key: "b", name: Bar }

const x: Foo = { key: "b", name: "A" }
```

There are multiple weird things that get rid of the error, including:
1. Changing `{ key: "a", name: string }` to `{ key: "a" }`.
2. Changing `name: "A"` to `name: "A" as Bar`

**Comment by alitaheri** [comment] 2017-01-23 06:00
This issue have been around for a while, it boils down to this:

```ts
const obj = {b: 'A'};
type A = 'A';
const a: A = obj.b; // ---> [ts] Type 'string' is not assignable to type '"A"'.
```

Not much can be done here. typing `b` as `'A'` has too many consequences and breaks way too many code. This issue can't be solved until [Expando Objects](https://github.com/Microsoft/TypeScript/issues/10566) come to rescue. With those around `b` can just be typed `'A'` and **expand** to include more literals or morph into `string`. no code will break and this issue will be solved for good ❤️

**Comment by johnfn** [comment] 2017-01-23 06:03
I understand why your code doesn't work, but I still don't see why mine doesn't, as I have explicitly given the type of `x` to be `Foo`. 

If I wrote `const obj: { b: A } = { b: 'A' }` in your code, I would expect it to work as well.

**Comment by alitaheri** [comment] 2017-01-23 06:10
Right, sorry, I didn't initially understand the issue you reported. I think what you expect the compiler to do is valid. This is a bug indeed 👍

**Comment by mhegazy** [comment] 2017-01-23 20:56
Duplicate of https://github.com/Microsoft/TypeScript/issues/13580

**Closed** 2017-01-24 00:12 UTC
Labels: Duplicate
