### ISSUE TITLE
Suggestion for autocompletion does not work in second type parameter

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6322] opened 2016-01-02 17:28 UTC
VS2015 and Playground.

```ts
class C<T, U> {
}

new C<number, number>(); // work
var c = new C<number, n
                       ^
```

**Comment by mhegazy** [comment] 2016-01-07 18:13
:) that is subtle. the completion position is a valid identifier definition location, it is parsed as:
`var (c = ((new C) <  number)) , n`, where parens indicate nodes.

I think this is a valid grammar production, and thus behaves as intended.

**Comment by DanielRosenwasser** [comment] 2016-01-07 18:18
I'm going back and forth on this. Just because this is grammatically valid one way doesn't mean it should be a complete completion blocker. We have made efforts elsewhere to speculatively prepare for other constructs. I wonder if we could do better. But I'll close this for now.

**Closed by DanielRosenwasser** 2016-01-07 18:18 UTC
Labels: By Design
