### ISSUE TITLE
Symbols disallowed as object keys

### ISSUE THREAD

**Issue by 00ff0000red** [microsoft/TypeScript#39756] opened 2020-07-27 02:48 UTC
**TypeScript Version:**  4.0.0-dev.20200725

**Search Terms:**
Symbols as object keys

**Code**
```ts
type symbolKey = {
    [key: symbol]: any
};
```

**Expected behavior:**
The code compiles without error.

**Actual behavior:**
TSC throws an error disallowing symbols to be used as object keys.

**Playground Link:** <https://www.typescriptlang.org/play?ts=4.0.0-dev.20200725#code/C4TwDgpgBAziC2AjA9gGwNIRFAvFA3gFBQlQDaA1lgFywIqoC6tAhgHYiEC+A3EA>

**Related Issues:** Couldn't find anything related

Symbols were introduces with the primary purpose of being used as object keys, and are still primarily, if not only, used with that purpose. To not be usable as keys makes no sense whatsoever. They can be used on any object type too, array, generic object, map, Element, etc.

**Comment by SancheZz** [comment] 2020-07-27 19:24
#26797

**Comment by kitsonk** [comment] 2020-07-28 02:28
Duplicate of #1863

**Comment by 00ff0000red** [comment] 2020-07-28 09:52
Yeah okay, I'm a bit late.

**Closed** 2020-07-28 09:52 UTC
