### ISSUE TITLE
Cannot assign type which should be compatible when conditional generics are used

### ISSUE THREAD

**Issue by EnkeyMC** [microsoft/TypeScript#50672] opened 2022-09-07 14:43 UTC
# Bug Report

Cannot assign type which should be compatible when conditional generics are used (also posted on [SO](https://stackoverflow.com/questions/73627926/cannot-assign-type-which-should-be-compatible-when-conditional-generics-are-used?noredirect=1#comment130033794_73627926) but was only suggested to open issue here)

## 🕗 Version & Regression Information

Throws error on all versions available in TypeScript playground.

## Playground Link

⏯ [Playground Link](https://www.typescriptlang.org/play?ts=4.7.4#code/PTAECUFMBcFcCcB2BnUBrSBPSroAsBDaUQgN0lGkwAcLIAPaSRAEwEtEBzUAFRpwBQVWqADSWZAFkiAYzwdOAHh4AaXv2QA+UAF5QAb1ABtUaA7osAewBmvALoAuXibugGTVqj61UAfjGgTjygAL5GGJg29gDcAkL8oNLU1Aq6BgKgmaAAyjzgTsjQ8AqxWaAAcgCqkk6IsAC2AEaQ8KVZAEIA8p0AMk6NlpYANpAEiLEhccIUAGoEQ7A4aUkpXOFWtisKdrHxIgDizC1sMspujMwsqHMLONp6+hlZ09lFTuKYUrLyXIpbXGoeJoBJMBDJLChiNZBk5DohjqcBsNRoh7gZKPxXvAnAByLq9HGhWLgyGgRoEbGgOEIxQ3RZaNLQyy7EC8eSoADulngaFQ1g4kD2FAAwhD2NA2BD5so1DM0cF3JdrqB-MEnLBEGhEJYOeMwRDCqAmQAmJyi1hsCVSoaKQrFAGgOl3NI4u0KHHEg3EcnwU2gc3iyWIaVO5Cy+b0tEm2JAA)

## 💻 Code

```
// Returns keyes that have type extending Types
type KeysMatching<T, Types> = { [K in keyof T]: T[K] extends Types ? K : never }[keyof T];

type Mapping = {
    STR: string;
    NUM: number;
    BOOL: boolean;
}

type Values = Mapping[keyof Mapping];

type Generic<T extends Values> = {
    typeStr: KeysMatching<Mapping, T>
}

const foo: Generic<boolean> = { typeStr: 'BOOL' };
const bar: Generic<Values> = foo;
// Type 'Generic<boolean>' is not assignable to type 'Generic<Values>'.
//  Type 'Values' is not assignable to type 'boolean'.
//    Type 'string' is not assignable to type 'boolean'.(2322)

// This works fine
type Conditional<T, V> = T extends V ? T : unknown;
const foo2: Conditional<string, Values> = 'string';
const bar2: Conditional<Values, Values> = foo2;
```

## 🙁 Actual behavior

TS throws error that foo is not assignable to bar

## 🙂 Expected behavior

TS does not throw error as the types should be compatible

**Comment by whzx5byb** [comment] 2022-09-07 15:40
A shorter repro:
```ts repro
type V<T> = { value: 0 extends T ? T : never };
type V0 = V<0>; // V0 = { value: 0 }
type VNumber = V<number>; // VNumber = { value: number }

type R1 = V<0> extends V<number> ? true : false;
//   ^?
type R2 = V0 extends VNumber ? true : false
//   ^?
```

**Comment by fatcerberus** [comment] 2022-09-07 15:57
Probably something to do with variance measurement - it seems like `V<T>` is incorrectly being measured as contravariant in `T`, likely because `T` occurs on the RHS of an `extends` check.  `R2` is correctly determined to be true because `V0 extends VNumber` bypasses variance measurement and does a full structural check.

**Comment by andrewbranch** [comment] 2022-09-09 23:01
Yeah, duplicate of #48070

**Closed** 2022-09-12 18:00 UTC
Labels: Duplicate
