### ISSUE TITLE
Support string literal export names

### ISSUE THREAD

**Issue by justinfagnani** [microsoft/TypeScript#57017] opened 2024-01-11 07:34 UTC
### 🔍 Search Terms

export string name literal

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

JavaScript allows exporting and importing names that are _string literals_ and not just identifiers. This is for compatibility with future non-JS modules types that might not have the same restrictions on export names, like WASM, CSS, HTML, etc.

See https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#prod-ModuleExportName

### 📃 Motivating Example

```ts
import {'product-card' as productCard} from './product.html` with {type: 'html'};
import {'fast-inverse-square-root' as fastInverseSquareRoot} from 'carmack.wasm';
```

### 💻 Use Cases

1. What do you want to use this for?
  Importing from non-JS modules and defining types for non-JS modules

2. What shortcomings exist with current approaches?
  You can't do either of the above

3. What workarounds are you using in the meantime?
  None?

**Comment by MartinJohns** [comment] 2024-01-11 08:19
Duplicate of #40594.

**Closed** 2024-01-15 01:30 UTC
Labels: Duplicate, Fix Available
