### ISSUE TITLE
Provide info diagnostics/quick fixes for JSDoc/TS mismatches

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#31451] opened 2019-05-17 22:13 UTC
```ts
/**
 * @param foo {number} desc
 */
function stuff(bar: string) {
    // ...
}
```

We should consider popping up an info diagnostic in the editor when a parameter name/type mismatches that of the JSDoc, along with a quick fix. We already do this in `checkJs`.

**Comment by ajafff** [comment] 2019-05-18 05:56
Duplicate of #11378?

**Comment by sandersn** [comment] 2019-05-20 15:55
Yep. Duplicate of #11378

**Closed by sandersn** 2019-05-20 15:55 UTC
Labels: Domain: JSDoc, Suggestion
