### ISSUE TITLE
Error: Debug Failure. False expression - 2.9.0-dev.20180420

### ISSUE THREAD

**Issue by TheLarkInn** [Microsoft/TypeScript#23588] opened 2018-04-20 21:50 UTC
To access some of the newest JSDoc annotation support for webpack, I locally upgraded the newest nightly for typescript (see version below). However, I was coming across errors locally on my console (also seen below).

In addition, I have submitted a PR for webpack so our CI builds can fail and showcase this same failure (as it will run `tsc --pretty there also`). The PR is referenced also down below. 

**TypeScript Version:** 2.9.0-dev.20180420

**Expected behavior:**
Running TSC with JSDoc annotations doesn't error. 

**Actual behavior:**
```bash
> webpack@4.6.0 type-lint /Users/wecomm/Desktop/webpack
> tsc --pretty

/Users/wecomm/Desktop/webpack/node_modules/typescript/lib/tsc.js:62227
                throw e;
                ^

Error: Debug Failure. False expression.
    at Object.getJSDocHost (/Users/wecomm/Desktop/webpack/node_modules/typescript/lib/tsc.js:7787:18)
    at resolveEntityNameFromJSPrototype (/Users/wecomm/Desktop/webpack/node_modules/typescript/lib/tsc.js:22406:33)
    at resolveEntityName (/Users/wecomm/Desktop/webpack/node_modules/typescript/lib/tsc.js:22352:76)
    at resolveTypeReferenceName (/Users/wecomm/Desktop/webpack/node_modules/typescript/lib/tsc.js:26701:20)
    at getTypeFromTypeReference (/Users/wecomm/Desktop/webpack/node_modules/typescript/lib/tsc.js:26843:30)
    at checkTypeReferenceNode (/Users/wecomm/Desktop/webpack/node_modules/typescript/lib/tsc.js:37095:24)
    at checkSourceElement (/Users/wecomm/Desktop/webpack/node_modules/typescript/lib/tsc.js:39938:28)
    at checkSourceElement (/Users/wecomm/Desktop/webpack/node_modules/typescript/lib/tsc.js:39982:28)
    at checkJSDocParameterTag (/Users/wecomm/Desktop/webpack/node_modules/typescript/lib/tsc.js:37767:13)
    at checkSourceElement (/Users/wecomm/Desktop/webpack/node_modules/typescript/lib/tsc.js:3
```

**Related Issues or PR's:** https://github.com/webpack/webpack/pull/7091

**Comment by mhegazy** [comment] 2018-04-20 21:52
I beleive this is a duplicate of https://github.com/Microsoft/TypeScript/issues/23574 and should be addressed by https://github.com/Microsoft/TypeScript/pull/23575.

@sandersn can you confirm please.

**Comment by TheLarkInn** [comment] 2018-04-20 21:52
Ahh sorry I missed the closed issues, thanks!

**Comment by sandersn** [comment] 2018-04-20 22:04
Yep, they are the same issue. Sorry about that.

**Closed by sandersn** 2018-04-20 22:04 UTC
Labels: Duplicate
