### ISSUE TITLE
Unable to make class generic with JSDoc

### ISSUE THREAD

**Issue by JoelEinbinder** [Microsoft/TypeScript#18135] opened 2017-08-30 06:31 UTC
**TypeScript Version:**  2.6.0-dev.20170829

```js
/**
 * @template T
 */
class MyArray {
  constructor() {
    /** @type {Array<T>} */
    this.array = [];
  }
}
/** @type {MyArray<string>} */
let x = new MyArray();
```

**Expected behavior:**
`x` should contain an array of strings.

**Actual behavior:**
`[js] Cannot find name 'T'.`
`[js] Type 'MyArray' is not generic.`

**Comment by kitsonk** [comment] 2017-08-30 07:06
Could this be a duplicate of #17140?

**Comment by sandersn** [comment] 2017-08-30 15:58
Just to make sure, this is in a .js file, right?

**Comment by JoelEinbinder** [comment] 2017-08-30 16:49
Yes, this is in a .js file.

My `compilerOptions`:
```json
{
    "noEmit": true,
    "allowJs": true,
    "checkJs": true,
    "target": "es2017"
}
```

**Closed** 2018-04-19 22:58 UTC
Labels: Bug, Domain: JSDoc, Fixed, Salsa
