### ISSUE TITLE
Const with non-widening type as dynamic object literal key

### ISSUE THREAD

**Issue by arusakov** [Microsoft/TypeScript#12884] opened 2016-12-13 15:45 UTC
**TypeScript Version:**  master (c76a3a6feff5bc0bdf10b304373453fd295aa1ca)

**Code**
```ts
const x: 'x' = 'x';
const y: 'y' = 'y';

const z = {
  [x]: y
};
```

**Expected behavior:**
`z` has type `{ x: "y" }`

**Actual behavior:**
`z` has type `{ [x: string]: 'y' }`. It's inconsistency.

**Comment by NN---** [comment] 2016-12-13 17:13
Did you mean "z has type"?;)

**Comment by arusakov** [comment] 2016-12-13 17:22
@NN--- thank you

**Comment by mhegazy** [comment] 2016-12-14 00:00
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/5579. 
The issue here is that the compiler does things in phases. the first phase, binding, it setts the names of properties on a type/symbol. the second is type resolution, that is when it knows about types of symbols. this change requires these two phases to be interleaved in a way, which is not a small change.

**Closed** 2016-12-14 06:59 UTC
Labels: Duplicate
