### ISSUE TITLE
Wrong union behaviour

### ISSUE THREAD

**Issue by dfilatov** [Microsoft/TypeScript#15778] opened 2017-05-11 20:24 UTC
**TypeScript Version:**  2.3.2

**Code**

```ts
interface Action<Type> {
    type: Type;
}

interface ActionWithPayload<Type, Payload> extends Action<Type> {
    payload: Payload;
}

type MyAction = Action<'type1'> | ActionWithPayload<'type2', number>;

const action: MyAction = {
    type: 'type1',
    payload: 3
};

```

**Expected behavior:**
I'd expect to see an error about unexpected `payload` property. And if I use only one type from union I'll get it:
```ts
const action: Action<'type1'> = {
    type: 'type1',
    payload: 3
};
```
> ﻿Object literal may only specify known properties, and 'payload' does not exist in type 'Action<"type1">'.

**Actual behavior:**
There is no any errors

**Comment by mhegazy** [comment] 2017-05-11 20:32
duplicate of https://github.com/Microsoft/TypeScript/issues/10575

looks like you are looking for https://github.com/Microsoft/TypeScript/issues/14094

A workaround would be to define your `MyAction` as:
```ts
type MyAction = ActionWithPayload<'type1', undefined> | ActionWithPayload<'type2', number>;
```

**Comment by dfilatov** [comment] 2017-05-11 20:49
@mhegazy Yes, exclusive unions would solve this. Thank you.

**Comment by dfilatov** [comment] 2017-05-11 21:05
@mhegazy If I use suggested workaround I can't do anymore:
```ts
const action: MyAction = {
    type: 'type1'    
};
```
I have to do:
```ts
const action: MyAction = {
    type: 'type1',
    payload: undefined
};
```

**Comment by mhegazy** [comment] 2017-05-11 21:15
that is correct. consider setting `payload?: undefined` instead:

```ts
type MyAction = { type: "type1", payload?: undefined } | { type: "type2", payload: number };
```

**Comment by dfilatov** [comment] 2017-05-11 21:24
Cool! This works.

**Comment by AJamesPhillips** [comment] 2017-05-12 11:14
This works like a charm.  Just use it as discussed here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16416#issuecomment-301048853  Thanks @mhegazy

**Comment by mhegazy** [comment] 2017-05-30 18:59
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-05-30 18:59 UTC
Labels: Duplicate
