### ISSUE TITLE
Strange inference failure

### ISSUE THREAD

**Issue by jods4** [Microsoft/TypeScript#20596] opened 2017-12-09 20:08 UTC
**TypeScript Version:**  2.6.2

**Code**

```ts
let x: { nodes: DocumentFragment, _start: Comment };
let iter: Node | null, nodes: DocumentFragment;
({ nodes, _start: iter } = x!);
while (iter) {
    let next = iter.nextSibling;
    nodes.appendChild(iter);
    iter = next;
}
```

**Expected behavior:** `next` is typed as `Node | null`.

**Actual behavior:** `next` is typed as `any`, which raises an error under `noImplicitAny`.

**Comment:** This is really strange because tooltips indicate that at this point `iter` is narrowed to `Node` and `iter.nextSibling` is of course `Node | null`.
So it makes no sense that `let next = iter.nextSibling` isn't type as such.

**Comment by jcalz** [comment] 2017-12-11 15:45
Essentially a duplicate of #1146 ?

**Comment by jods4** [comment] 2017-12-11 15:54
@jcalz There is a similarity but the reproductions look a bit different (loop vs `super` usage).
From outside it's not obvious that they are the same bug.
If someone with internal knowledge can confirm it's the same bug, feel free to close this one!

**Closed** 2018-01-25 23:25 UTC
Labels: Duplicate

**Comment by jods4** [comment] 2018-01-26 08:44
@mhegazy This was closed as a duplicate of #1146, which it _might_ be, but that issue was closed without resolution...

Is the repro above really not fixable?
Tooltips in VS correctly say `iter` is `Node`, so there's no reason that `let next = iter.nextSibling` isn't typed properly, is there?

**Comment by mhegazy** [comment] 2018-01-29 21:08
This is a design limitation of the current compiler implementation. The type of `next` in the loop depends on the compiler understanding of what the type of `iter` is, and that in terns depend on type of `next`. the compiler resolves cycles like such by using `any`. in theory, yes, the compiler could keep iterating on both types untill a fix point is reached, but this is not how the compiler is currently designed.

**Comment by jods4** [comment] 2018-02-13 13:07
@mhegazy OK

I'm still confused by the VS tooltip indicating `iter` is `Node` in `iter.nextSibling`. Where does that information come from? If it's incorrect (compiler sees `iter` as `any`) does it imply there's a bug in Typescript tooling inside VS?
