### ISSUE TITLE
Contextual this in prototype functions

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#8317] opened 2016-04-26 21:37 UTC
Hi,

When adding new functions to object prototype, `this` could be hard-typed in below scenario:

```ts
interface Array<T> {
  first(): T;
}

Array.prototype.first = function() {
  return this.length > 0 ? this[0] : undefined;
}
```

`this` is of type `any`, why it can't be of type `Array` ?

typescript: 1.8.30

**Comment by RyanCavanaugh** [comment] 2016-04-26 22:56
Duplicate of #8024 ?

**Closed** 2016-05-20 05:51 UTC
Labels: Duplicate
