### ISSUE TITLE
Record property string literal and <typeof classType["name"]> not working

### ISSUE THREAD

**Issue by andtii** [microsoft/TypeScript#47203] opened 2021-12-20 14:53 UTC
# Bug Report

### 🔎 Search Terms

typeof ["name"] 
get class name

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwgNgQwM5IDwBUB8UC8UDeAUFFAHYQDuAFAHR0IBOA5kgFxQKkgDaAugJTt0AbkIBfQoQgAPMAHsGwKADMArqQDGwAJZzSUVUggBJUgCsIWhACM4ENOnjIkARgA0UR4hQAmTFQ1vJHRwCHYnFAwI10wPQOcQyB9woKigv0EoACVLBQATVAADABJ8AFVNBDBtYAQ4bQAvCFRQSDllKHiURIhuACJSBABbCD7eTDFCjy9nF2wAMmzchgKS8srq2vqmltD2zqCen37BkbGJqc9ovylZBSU1TR09AyNTCytbezTnfy7g0IpZw-FCYTI5DT5IqlCoaKo1OqNZqtCD7f49E7DUbjSbTaKYW7yRQqdRaXT6QwmcyWWpfBz42j0ZhsKAAQQYDAQIFQ0RBSEwYPY+Cg3AA1hAQOwkMAGNpSExeOxOCAoGICMQoAB6TXoADyABFdVBtEMwHYRqQlBQABYQfStOVMKAUBSipAahgQYCqBj6YXAezAdikVRwOCq0QSQj-KC68jqkg6YB2XBQProQN9SOSGPoF0JqBIOQjYDWx2pvoAUTgRizGqGCmgeD6trAYDrUchpGlBCgeggHmA+bVeEp7xpNjsSCocYHnhd-FEhG1ldkNKgwDkfdIcBV1oQADdoEmU2AGHIwIR+zQTxBRNeiyWy-LJCu11oN1u9LuoPuj4Xiy9Z8nTPC9CCHOQaEfIDHVECCbxqOxCCAA)

### 💻 Code

```ts
type Class<T> = {
  new(...args: any[]): T;
}

export function useInjectables<TClass1, TClass2>(classType: Class<TClass1>, classType2: Class<TClass2>): Record<`${Uncapitalize<typeof classType["name"]>}`, TClass1> & Record<`${Uncapitalize<typeof classType2["name"]>}`, TClass2>
export function useInjectables<TClass>(classType: Class<TClass>): Record<`${Uncapitalize<typeof classType["name"]>}`, TClass>
export function useInjectables<TClass>(...args: Array<Class<TClass>>): { [key: string]: any } {
  //TODO implement when typing works
  return { test: null };
}

class One {
  title = "Test";
}

class Two {
  something = "Else";
  more = "hepp";
}

const { one, two } = useInjectables(One, Two);

//Expect to only have title prop
one.title;
one.something

//Expect to only have something prop
two.something;
two.title

```

### 🙁 Actual behavior

The Record<`${Uncapitalize<typeof classType["name"]>}`, TClass1> does not set the propertyName to be the name of the classType.
and both objects is merged into one. If i change it to hardcoded value like this: Record<`${Uncapitalize<'one'>}` it will work.

### 🙂 Expected behavior

The propertyNames should automatically be inferred by <typeof classType["name"]>

**Comment by MartinJohns** [comment] 2021-12-20 15:00
Your issue can be simplified to:

    type Class<T> = { new(...args: any[]): T; }

    class One { title = "Test"; }

    type TName = Class<One>["name"]
    // Expected "One", is string.

And then it's a duplicate of #43325, which was closed by the author in favour of #1579, which will most likely not happen in TypeScript.

There's also #32527, which is basically the same as well.

**Comment by fatcerberus** [comment] 2021-12-20 15:00
I think this is because `typeof Class["name"]` is just `string`?

**Comment by andtii** [comment] 2021-12-20 15:27
Okey, thnx for the explanation. Is there another way to get the incoming types so it can be used as the property name on the returning object? To achieve the goal here or something similar?

**Comment by MartinJohns** [comment] 2021-12-20 16:05
Only by passing a name manually.

**Comment by xiBread** [comment] 2021-12-20 18:25
If you don't mind using plugins then I suggest <https://github.com/dsherret/ts-nameof>

**Closed** 2021-12-23 08:07 UTC
