### ISSUE TITLE
Type manipulation: Removing field optionality but trying to keep undefined as part of field type requires workaround.

### ISSUE THREAD

**Issue by 2bam** [microsoft/TypeScript#54172] opened 2023-05-07 20:52 UTC
# Bug Report

Doing type manipulation and trying to remove optionality from fields using `-?`, but **also wanting to keep them as possibly undefined** so I can use the syntax check to avoid forgetting them when copying/cloning an object, doesn't work as expected.

I believe it's because the removal of optionality via `-?` is applied **_after_** the field type redeclaration and it removes `undefined`.

Better explained with code later on.

### 🔎 Search Terms
optional undefined

### 🕗 Version & Regression Information

TS 5.0.4

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `-?` or `optional`

### ⏯ Playground Link

[Playground link **_without_** workaround](https://www.typescriptlang.org/play?#code/LAKApgHgDg9gTgFwAQIJ5TEg8lBBLGAOwEMAbAZwEFyAxPMUgEwBV0ws4BVQxsAMzyEwjADzMAfEgC8SAN6gkipAG0ACkkFIA1mFQw+SZgF0AtAH4AXEgCuPfoOFJICMD3KG1RpGY+qvAHxs7ASFGJCtmTwBuUABfGJBQQRc4PmIAY0wAETAAWxg5BSU+K0JrXIAjMDgEpSQAc1LyqrgkQNteEOFapQALJsrqtqQy0lIexT4YSxHm6omG6YGW4Y77UIXepdnB1sDR8bjQUD5bdPwiJHSYKFRucmI+MAAKCqsc-IBKd7yC+RA6nAwAhrHBCIUAXVilYKgA6PgAGiKUIaMNh9SRkJR-SQcN6mJRkxgaKmBMJAHpyUgaPB6jBkAgCtdbkhiIRUEgbhcSKQkAIGIxyBZkVDKYSTBKkAA5ArVODwACESqQEpMIrqYsJzF6eHcutZSCg8oqpDysJF8SOiRAp0I5wI4OZqAAyo9qgBGV4-L7ev4i66EcjIB5POBWHDcshUWj0JisDAcbidByiD4wSQyf6Evkkskoxq49F5qE4vHFjVUmlwOnIYgVGDWWvszm4B1kPmxwVWajkPD1Qi5VwMthOODyuAWhZAkFgpAh+ZWk5nblXG4ut1wABMXqQae+u9+ELqAaDc434dbRCj1DoAvj7C4wRTIjTGaPhJKhcR6qUBbhGJ-RRS1hfFAL5YkvxgBEkDFABhNkAHJa3IXt+xQAoyl2Pl5VyHYWn8NYukYMC6TROloLgxDkNQ8FGTwoY+Bw+i4AIp9QjArY0S2CiqXgwgkNZFC+1ojC5laRiYFwzD8MIlNJxFadQXBecakXEAgA)

[Playground link with workaround](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKhC2YDKJ4CMD2AbKBeKA3lAE4QCGAJhgHZYhQD6AHgFxQCu1AlgI7vQBnVJhwBfANwBYAFAzQkKAAkIWSMQA8MAHx5CMqAagBtAApQu1KAGsIIDADNYAXQC0AfjacKEexYgUoCCZgCGoKAVhTJyg3SJNogB9YBGRhbCg2GCipaQkZGSCwDGJgKHloAHkwYC4aMiwBAEEBADEuFQoYcAgK4gBVMJ8-Ck0dfAJ9Q1NzSxs7R2VVCA1tJ0yUlHR0oJCwiKz4mKgAUSYAYyx2b3VFtVGogBpkxE2RHSSvIep-DLinHLysmkFhCxHsZDO0AAIggMHppIYoPY2NR2OhljlEQBzFFotDLKAfQa+b4UTGGAAWuPRxEJUFRWCw5IM9gwHnpeIxkwMWLZ1PxtKJ3hJ-mZUApfI5NLpDKZMlE+Wk9k4ZxqNCgZwwYBAAwEZHsEAAFGg2DD4BgAJSm2HwxGkYDsYiWCYIxGGZFQNAAOnsD25bpxnq9WL9rrd4rY3opofDLIwkZ9GBjsYA9CmoC1irzSsA4ZrtVAyNR6Fq1dR6kj2lhwix-Yi07GXE2oAA5OHLYjFACEPagTZcdcMDdjMApXAi48LUDAnbQWAQXv9gIVQOV1FVtUs+ZASH1ywAjMbrearVAzXCXYjNdQBKU9QbiGwqmX6k1WlXOt1egNhcN1OexltWMPW9X1Bx5BMQ3AiMg2jaCG0zYhs0LTB2FKIsS2qTcK18DoBDYZoBC4LFqHgUIc26QJiE7YglzFe1HUse8uVyRU1w3dVt13B8ACYjzPWFT3PICDGvW8oGYx8oGfbCGmaNoOi6SBv2JP8AN0S9gITMCwwDSDk3DKlYIMt1WW0pMoAbAB1LhgApKAAHdiisMhOy8MoxwiJziCsARoN5SCLOs2z7O8ly3LCDzJzCvzdMRCUEwlJ5grsxznNcjB3Ls6LnNixFATtCAHSdCS92IAFFSAA)

Please look at the functions syntax errors. The code itself doesn't run but the Playground link shows the syntax errors anyway.

#### Type manipulation
```
interface Demo {
    f: number;
    g: number | undefined;
    h: number | null;
    fo?: number;
    go?: number | undefined;
    ho?: number | null;
}

export type OptionalsAsFieldTypeOrUndefined<T> = {
    [P in keyof T]-?: undefined extends T[P] ? T[P] | undefined : T[P];
};
```

I expect `OptionalsAsFieldTypeOrUndefined<Demo>` to be

```
{
    f: number;
    g: number | undefined;
    h: number | null;
    fo number | undefined;
    go: number | undefined;
    ho: number | null | undefined;
}
```

But instead becomes

```
{
    f: number;
    g: number | undefined;
    h: number | null;
    fo: number;                 // undefined type missing here
    go: number;                 // undefined type missing --and removed-- here
    ho: number | null;          // undefined type missing here
}
```

#### Use case

This is the concrete use case, avoid making mistakes forgetting fields on this kind of copy-like operations
```

function copyUnsafe(b: Demo): Demo {
    return {
        f: b.f,
        g: b.g,
        h: b.h,
        fo: b.fo,
        // Forgot to copy any optional fields:
        //       --- No error!!! ---
        //        This is a problem.
    };
}

function copySafer1(b: Demo): Demo {
    const safer: OptionalsAsFieldTypeOrUndefined<Demo> = {
        f: b.f,
        g: b.g,
        h: b.h,
        // Forgot about any optional fields: Assignment type error (Nice!)
    };
    return safer;
}

function copySafer2(b: Demo): Demo {
    const safer: OptionalsAsFieldTypeOrUndefined<Demo> = {
        f: b.f,
        g: b.g,
        h: b.h,
        fo: b.fo, // Can't assign to number from number|undefined
        go: b.go, // Can't assign to number from number|undefined
        ho: b.ho, // Can't assign to number|null from number|null|undefined
    };
    return safer;
}
```

#### Workaround

I found this workaround which requires two steps and uses a temporary symbol, but it does seem a bit tricky and not tidy.

```
type TempSymbol = { readonly _x: unique symbol };

type Helper<T> = {
    [P in keyof T]-?: undefined extends T[P] ? T[P] | TempSymbol : T[P];
};

export type OptionalsAsFieldTypeOrUndefined<T> = {
    [P in keyof Helper<T>]: TempSymbol extends T[P] ? Exclude<Helper<T>[P], TempSymbol> | undefined : T[P];
};
```

Am I doing something wrong here? I couldn't find any resources about this.

Thank you for your time.

### 🙁 Actual behavior

Undefined is removed from field type by the `-?` operator to remove optionality from field key.

```
{
    f: number;
    g: number | undefined;
    h: number | null;
    fo: number;                   // undefined type missing here
    go: number;       // undefined type missing --and removed-- here
    ho: number | null;             // undefined type missing here
}
```

### 🙂 Expected behavior

Allow me to add undefined to the field type to keep syntax checks (e.g. to not forget when copying _possibly_ `undefined` values)

```
{
    f: number;
    g: number | undefined;
    h: number | null;
    fo number | undefined;
    go: number | undefined;
    ho: number | null | undefined;
}
```

**Comment by fatcerberus** [comment] 2023-05-07 22:49
For the record, there's already a built-in type alias that does what your original code does: `Required`.  And it does *almost* what you expect **if you enable `exactOptionalPropertyTypes`**:

* [Playground link](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true#code/JYOwLgpgTgZghgYwgAgCIQLYHtkG8CwAUMicjAFzIgCuGARtANxGnIDmlN90yAPstRAATCDFAQhzYqQAWnWgyh8q1ADaqprGFgD887lE2k2u-YuWCRYkBKMkZplQeU11UgL5EiMQQjDAsEGQELAAHAE8AVRAAZzgYCAAKOkp0bABKVMwcAmkSKAgwaigg3NYtSjoAOhgAGhZykg5karZ6vPK5FqqZdsaSbUqarD7+gHox5AAxLCgTMGQwHBCI5DgQcOQw-0C4VTJgCFUhGPIGxon+gFob5AA5HGgoWYBCN+Qbq-Pyy-6AFRkwBiyCBa2QoWedFUmCq33cHi8hB8ID8ASCK3CAGV4tAAIzJLIZQk5b4hWILOIJKCUABKEAAjtRgAUhAAeNJYAB8yAAvHhvhVunUBcYhm0RfYhr0JchLjM5lgFnA6FhqEqNltQjsQHsDkcTpQAIIxGLANggDAQcCLcKhFBPWZwuzIApFErISlMIieQjeXza4JhLE4qAAJgJaGymUj2H5HTJMQpIdpDKZLPZ2W5fLK-QoQtGjWarQLnSlJa0WCG2lqssmAHVgGAZMgAO6zADWcGelkWgOBbag7ZiMpMYpGteQDabrY7XdVwl7oIHQ5lDil48uU+by7nPabS47w468O+ruKQU9hm9iKAA)

Which is about as close as you can probably get without workarounds - since "optional" is intended to mean "the property is either present with the specified value, or else non-present", unconditionally including optional properties that don't explicitly have `undefined` in their type when copying an object is technically unsound, and `exactOptionalPropertyTypes` will enforce that.

**Comment by jcalz** [comment] 2023-05-08 01:58
Duplicate of #31025 probably?  This was listed as a bug, but I really doubt this will ever change.

**Comment by fatcerberus** [comment] 2023-05-08 03:14
@jcalz Nowadays I’d wager the “fix” for #31025 is to enable exactOptionalPropertyTypes

**Comment by 2bam** [comment] 2023-05-08 11:31
Thank you for your answers and taking the time to configure the Playground.

Sadly, if I try the code that would be a _correct_ copy with your suggestion, it fails ([Playground link](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true&ssl=21&ssc=1&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgCIQLYHtkG8CwAUMicjAFzIgCuGARtANxGnIDmlN90yAPstRAATCDFAQhzYqQAWnWgyh8q1ADaqprGFgD887lE2k2u-YuWCRYkBKMkZplQeU11UgL5EiMQQjDAsEGQELAAHAE8AVRAAZzgYCAAKOkp0bABKVMwcAmkSKAgwaigg3NYtSjoAOhgAGhZykg5karZ6vPK5FqqZdsaSbUqarD7+kyGTUcaHIYcGkncPL0IgA)):

```
function copyUnsafe(b: Demo): Demo {
    return {
        f: b.f,
        g: b.g,
        h: b.h,
        fo: b.fo, // Fails here
        go: b.go, // here
        ho: b.ho, // and here
    };
}
```
`Required` also removes `undefined` from the type, and `exactOptionalPropertyTypes` will work against my purpose.

I noticed my example wasn't too good as you may be asking, _why don't I use the spread operator?_.
But it's purposes is copying and patching the original value with a diff either using a remove sentinel symbol or a sieve of bools for optional fields.

Maybe I should use another pattern altogether to not forget to copy optional fields?

* Can you share with me what would be the common pattern to achieve it?
* Being part of the hot path I'm trying to minimize iterations and key enumerations. That's why I want syntax checks, to unroll the patching ourselves but keeping some safety on type changes.

It's ok though, I can use my two-step interim type to do what I want.
Only seemed odd that `-?` removed `undefined`.
As you well said, optionality is about _existence_ not types (strictly speaking), so it's strange `-?` it interferes with field typing.

**Comment by fatcerberus** [comment] 2023-05-08 11:53
You could try using `exactOptionalPropertyTypes` in combination with `Required` and then make sure *all* the objects you need to do this with have their optionals declared with `| undefined`.  Don't know how feasible that is for your project(s), but it's an option if you want to avoid ugly workarounds like the one you show in the OP.

> Only seemed odd that `-?` removed `undefined`.

The reason that `-?` behaves the way it does with eOPT off is that making a property optional actually *adds* `undefined` to its type, so `-?` must remove it again otherwise it's not a perfect round-trip.  Effectively, the logic for `-?` can't tell the difference between a property which is `T | undefined` just because it's optional, vs. one that was actually declared that way.

> As you well said, optionality is about *existence* not types (strictly speaking), so it's strange `-?` it interferes with field typing.

Yep, the difference in practice between an actually optional property vs. one that's just `T | undefined` is a bit fuzzy normally, which is exactly why `exactOptionalPropertyTypes` was implemented, to make optional properties behave more predictably.  But it tends to be a pretty disruptive breaking change to enable it, so that's why it's not enabled by default even with `strict: true`.

**Comment by 2bam** [comment] 2023-05-08 12:28
Thanks for the explanation and sharing your knowledge.

I was reading the duplicate thread and user _gordonmleigh_ suggested `export type NonPartial<T> = { [K in keyof Required<T>]: T[K] };` which works like a charm, even if it's a bit more cryptic to understand.

If I do understand correctly, it bypasses optionality by getting all the keys "de-optionalized" using Required<> (without undefined) and, as keys are not longer _tagged (?)_ with being optional, requesting field types using that "name" returns the type in union with `undefined` as there is no other way to communicate "optionality" at that point as it doesn't include the keys themselves in the operation🥴 .

**Comment by fatcerberus** [comment] 2023-05-08 12:39
Yep, `T[K]` for an optional property gives you `T | undefined`, even if the property wasn't declared with `| undefined` (you're effectively asking, if I read from `T[K]` what type of value will I get).  `NonPartial` is actually pretty clever, as it's not broken by enabling `exactOptionalPropertyTypes`, yet remains easy to understand.

**Comment by RyanCavanaugh** [comment] 2023-05-08 17:44
Does everyone agree this is working as intended then?

**Comment by 2bam** [comment] 2023-05-08 18:17
Not as intended: When developers are opting-in explicitly specifying `| undefined` on the field type, the majority will expect it to respect that. I.e. to be applied _after_ the key-optional operator `-?`, as most ops are left-to-right.

But it's not a blocker, and I asume at the bottom of the priority barrel, sort of speak. I'm ok with closing the issue, keeping it as reference.

**Comment by jcalz** [comment] 2023-05-08 18:18
Can we all agree that this is a duplicate of #31025?  Then can we go there and mark it with something like "As Good As It Gets" or "Won't Fix" or "Working As Expected If You Manage Your Expectations" or something?

**Comment by Andarist** [comment] 2023-05-08 18:22
I think it’s a duplicate of that other issue but the proposed labels for it hurt my soul a little bit 😢

**Closed** 2023-06-17 01:32 UTC
Labels: Duplicate
