### ISSUE TITLE
ArrayBufferView constructors do not accept ArrayBuffer as correct type

### ISSUE THREAD

**Issue by LiraNuna** [Microsoft/TypeScript#24266] opened 2018-05-19 06:57 UTC
**TypeScript Version:**  2.9.0-rc

**Search Terms:** 
ArrayBuffer, ArrayBufferView

**Code**

```ts
function test(a: ArrayBuffer|ArrayBufferView): Uint8Array {
    return new Uint8Array(a);
}
```

**Expected behavior:**
No error - this works correctly in the browser if given a view (such as an instance of `Uint8Array` or a straight up ArrayBuffer either given from browser API (such as WebCrypto) or from `ArrayBufferView.buffer`

**Actual behavior:**
This error message:
```
error TS2345: Argument of type 'BufferSource' is not assignable to parameter of type 'ArrayBuffer | ArrayLike<number> | SharedArrayBuffer'.
  Type 'ArrayBufferView' is not assignable to type 'ArrayBuffer | ArrayLike<number> | SharedArrayBuffer'.
    Type 'ArrayBufferView' is not assignable to type 'SharedArrayBuffer'.

     return new Uint8Array(a);
                           ~
```

**Playground Link:**  
https://www.typescriptlang.org/play/#src=function%20test(a%3A%20ArrayBuffer%7CArrayBufferView)%3A%20Uint8Array%20%7B%0D%0A%20%20%20%20return%20new%20Uint8Array(a)%3B%0D%0A%7D

**Related Issues:** 
N/A

**Comment by mhegazy** [comment] 2018-05-19 19:11
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/24195

**Comment by LiraNuna** [comment] 2018-05-19 20:15
I saw this one but figured it's related to the definition of the webgl types rather than the constructor of `Uint8Array` and friends.

**Closed** 2018-06-04 16:03 UTC
Labels: Duplicate
