### ISSUE TITLE
Prefer union type parameters instead of function overloads

### ISSUE THREAD

**Issue by rveerd** [microsoft/TypeScript#46925] opened 2021-11-26 13:51 UTC
# lib Update Request

The type definitions for `String.replace` and `String.replaceAll` are written using overloads. Should they not be written with union type parameters?

Overloads give problems when creating wrapper functions for `String.replace`; see example below.

This has already been proposed in [this comment in another issue](https://github.com/microsoft/TypeScript/issues/13889#issuecomment-277554799) but I cannot find a follow-up issue or discussion.

The [documentation](https://www.typescriptlang.org/docs/handbook/2/functions.html#writing-good-overloads) describes a similar problem and also advises to prefer union types, when possible.

## Sample Code

```ts
export class Foo {
  constructor(
    private name: string
  ) { }

  replace(searchValue: RegExp | string, replaceValueOrReplacer: string | ((substring: string, ...args: any[]) => string)): string {
    return this.name.replace(searchValue, replaceValueOrReplacer);
  }
}
```

```
src/stream.ts:7:43 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'string | ((substring: string, ...args: any[]) => string)' is not assignable to parameter of type '(substring: string, ...args: any[]) => string'.
      Type 'string' is not assignable to type '(substring: string, ...args: any[]) => string'.

7     return this.name.replace(searchValue, replaceValueOrReplacer);
                                            ~~~~~~~~~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.es5.d.ts:454:5
    454     replace(searchValue: string | RegExp, replacer: (substring: string, ...args: any[]) => string): string;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The last overload is declared here.
```

**Comment by IllusionMH** [comment] 2021-11-26 14:50
Looks like duplicate of #44919

**Closed** 2021-12-01 18:00 UTC
Labels: Duplicate
