### ISSUE TITLE
strictNullChecks limits what types can be accessed with indexed access types

### ISSUE THREAD

**Issue by nomcopter** [Microsoft/TypeScript#21975] opened 2018-02-15 19:49 UTC
**TypeScript Version:**  2.7.1-insiders.20180127

**Search Terms:** strictNullChecks mapped types property undefined generated types

**Code**
```ts
interface Foo {
    bar?: {
        baz: string;
    }
}

type ShouldBeString = Foo['bar']['baz'];
```

**Expected behavior:** Type `ShouldBeString` is a string type. This is useful especially for generated types where it isn't possible to write `{ baz: string }` as a separate type.

**Actual behavior:** Accessing `'baz'` errors with `Property 'baz' does not exist on type '{ baz: string; } | undefined'.`

**Playground Link:** 
Make sure to toggle `strictNullChecks` on: https://www.typescriptlang.org/play/#src=interface%20Foo%20%7B%0D%0A%20%20%20%20bar%3F%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20baz%3A%20string%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Atype%20ShouldBeString%20%3D%20Foo%5B'bar'%5D%5B'baz'%5D

**Related Issues:** #16108 #6606

**Comment by mhegazy** [comment] 2018-02-15 20:39
Duplicate of https://github.com/Microsoft/TypeScript/issues/16108, and https://github.com/Microsoft/TypeScript/issues/17370

**Comment by nomcopter** [comment] 2018-02-15 20:42
I'm not sure this is a duplicate. This involves mapped types instead of the typeof operator.

**Comment by nomcopter** [comment] 2018-02-20 21:53
This issue may generalize more correctly to a feature request that the compiler should chose the "more useful" type when mapping through union types. For example the following example applies without `strictNullChecks`:

```
interface Foo {
    bar: {
        baz: string;
    } | {
        qux: number;
    }
}

type ShouldBeString = Foo['bar']['baz']
```

https://www.typescriptlang.org/play/index.html#src=interface%20Foo%20%7B%0D%0A%20%20%20%20bar%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20baz%3A%20string%3B%0D%0A%20%20%20%20%7D%20%7C%20%7B%0D%0A%20%20%20%20%20%20%20%20qux%3A%20number%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Atype%20ShouldBeString%20%3D%20Foo%5B'bar'%5D%5B'baz'%5D

**Comment by DanielRosenwasser** [comment] 2018-02-20 21:57
#14366

**Comment by nomcopter** [comment] 2018-02-20 22:04
Would it be better to handle #14366 in the more general case by handling all union types? Should I update this issue?

**Closed** 2018-03-07 17:41 UTC
Labels: Duplicate
