### ISSUE TITLE
union type {x, y} | {x, z} sometimes incorrectly allows {x, y, z}

### ISSUE THREAD

**Issue by felix9** [microsoft/TypeScript#43691] opened 2021-04-15 17:30 UTC
# Bug Report

### 🔎 Search Terms

union type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about union types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=7&ts=4.2.3#code/C4TwDgpgBAGgmgHgCoD4oF4oG8BQV9QAeAXFEgNx4EikU4C+loksAWggKpqa4FGkdKfAF4DKjHDgD0UsgAsAlgGcoyqAGMA9gCdtEdcAA2IKAEMAdlAi6dOLeaXAzpeAgBGmzYYgW0AHzYER20FcwBzbmx+KGBtAFcIABooGhj4pKhRKAByYWyoCWlZJEUVNVCtXX0jE1NDQ00AdwgAEztNByc3F0RzOIBbN2t-QODQiIwokigARmTUuczSXPzGIA)

### 💻 Code

```ts
type XY<T> = {
    x: T;
    y: T;
};
type XZ<U> = {
    x: U;
    z: U;
};

// This is correctly an error
const a: XY<boolean> | XZ<string> = { x: true, y: true, z: 'z' };

// This is incorrectly allowed
const b: XY<number> | XZ<string> = { x: 1, y: 1, z: 'z' };
```

**Comment by DanielRosenwasser** [comment] 2021-04-15 18:03
I think this is a duplicate of #20863.

**Comment by felix9** [comment] 2021-04-16 06:42
It's similar? but I'm not sure I understand why it behaves differently when I change the type from number to boolean.

this irregularity makes me completely confused about union types, I don't feel like I can predict at all what will and won't work.

**Closed** 2021-04-18 18:00 UTC
Labels: Duplicate
