### ISSUE TITLE
`strictNullChecks` fails to prevent undefined assignments

### ISSUE THREAD

**Issue by start** [Microsoft/TypeScript#17236] opened 2017-07-16 21:18 UTC
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

This example currently compiles in the TypeScript playground with `strictNullChecks` enabled.

**Code**

With `strictNullChecks` enabled:

```ts
class Widget {
  price: number

  // This example compiles with and without a constructor
  constructor() { }
}

const widget = new Widget()
const somePrice: number = widget.price
```

**Expected behavior:**

I expect a compilation error. `Widget`'s `price` field is not nullable, but every constructed widget will have an `undefined` price.

The constructor should ensure `price` is non-null. 

**Actual behavior:**

The code compiles. Two non-nullable `number`s are set to `undefined`: `somePrice` and `widget.price`.

_P.S. I'm in love with TypeScript. Thank you for your amazing work!_

**Comment by RyanCavanaugh** [comment] 2017-07-16 23:07
Duplicate of #8476

**Comment by start** [comment] 2017-07-16 23:36
Oops. Sorry about that!

**Comment by mhegazy** [comment] 2017-08-17 17:13
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-08-17 17:13 UTC
Labels: Duplicate
