### ISSUE TITLE
Implement '--watch' for tsc.exe

### ISSUE THREAD

**Issue by urbanhop** [Microsoft/TypeScript#2375] opened 2015-03-16 21:11 UTC
error TS5001: The current host does not support the '--watch' option.

I got the really cool watch option working using the typescript spirce cde. but wouldn it be cool to have it working with tsc?

**Comment by gintsgints** [comment] 2015-05-11 06:33
So watch does not work on windows?

+ for making it work on .win too.

**Comment by DanielRosenwasser** [comment] 2015-05-11 08:20
Just to be clear, `--watch` does work on Windows if you're using node.js/io.js, but the tsc.exe program distributed with VS does not support it; you still have Compile on Save for similar functionality anyhow.

**Comment by urbanhop** [comment] 2015-05-11 13:39
As Daniel says, and as I wrote: "The current *host*" does not support the watch. I use node now as a host and come along well. So for me this is not an issue anymore and I think others will be fine as well with node as a host.

**Comment by gintsgints** [comment] 2015-05-11 15:01
I realy do not get what means - "node as a host"

**Comment by urbanhop** [comment] 2015-05-11 15:23
javascript code needs some program that executes it. That is either a browser or node.js or something else, like tsc.exe.

The typescript compiler is tsc.js and you can use it for instance by running

    tsc.exe
    node tsc.js

First time, tsc.exe is a javascript runner, or in other words a "host" for tsc.js . In the second line, node.js is the runner, or "host". Besides executing the js code, the host provides some services like file-watching to the js code. And here is the missing piece: tsc.exe does not implement file watching, while node.js does. So using 

    node tsc.js -w  mycode.ts

you get file watching while

    tsc.exe -w  mycode.ts

will throw

    error TS5001: The current host does not support the '--watch' option.

**Comment by CyrusNajmabadi** [comment] 2015-05-11 15:37
I'm not sure why this was closed.  Supporting --watch for our tsc.exe host would both be possible and desirable.  Right now the limiting factor is that our tsc.exe host is a bit of ugly C++, that uses some ancient COM interfaces for Chakra that we haven't spent much effort on.  Our options are:

1. Implement --watch functionality in that C++ code.  Given an appropriate C++ file watcher, this shouldn't be too difficult.
2. Move to a managed code host and use the rich .Net functionality here.  This would be a lot of work, but it would be nice to have a cleaner and more welcoming host for people to work in.
3. Move to a more modern, native, Chakra host API (i.e. [jsrt](https://msdn.microsoft.com/en-us/library/dn249673%28v=vs.94%29.aspx), and then expose file watching through that as well.

**Comment by urbanhop** [comment] 2015-05-11 18:44
i closed it, because i opened it and found a workaround. 
but appreciate your efforts for a watching tsc.exe.

**Comment by gintsgints** [comment] 2015-05-13 13:33
So workaround for winodws is to search tsc.js and make cmd file to start it with node. :)

**Comment by DickvdBrink** [comment] 2015-05-13 15:38
`jsrt` is only available on Windows 10 right? So that might not be the best solutions right?
Or is It that on Windows 8 the current `tsc.exe` would be used and for Windows 10 a new one? BTW I know this (probably) isn't happening anytime soon :)

**Comment by DanielRosenwasser** [comment] 2015-05-13 17:20
> So workaround for winodws is to search tsc.js and make cmd file to start it with node. :)

No, if you're going to use node, we'd recommend you install TypeScript via `npm` and make sure that node's `tsc` comes before Visual Studio's `tsc` in your `PATH`.

**Comment by urbanhop** [comment] 2015-05-13 20:02
@DanielRosenwasser : right, this is clean and portable
@gintsgints; yes, this is what I ended up with. since I have several tsc verisons, i brutally hard coded the path getting this ts.cmd:

rem usage: ts app
node X:\typescript\bin\tsc.js -w --sourcemap %1.ts --out js\%1.js

**Comment by DanielRosenwasser** [comment] 2015-05-13 20:20
@urbanhop hope you won't mind, I modified your script to be in a code block so it's a little more readable.

**Comment by urbanhop** [comment] 2015-05-13 20:31
thx!

**Comment by gintsgints** [comment] 2015-05-16 17:23
one more funny way to start tsc would be npm run.
* put tsc script run into npm config like this:

```
  "scripts": {
    "tsc": "tsc -w"
  },
```

Then execute your tsc by issuing:

```
npm run tsc
```

**Comment by fjanon** [comment] 2015-05-29 22:58
Please add to the "tsc --watch" doc that it is not supported on straight windows hosts but works on node on windows. That would save everyone's time.
Thanks

**Comment by fjanon** [comment] 2015-05-29 23:00
Would it be possible to get a cmd file that watches the .ts files and recompiles them?
Thanks

**Comment by DanielRosenwasser** [comment] 2015-05-29 23:05
@fjanon not really, we'd be better off adapting the host to take on this functionality.

**Comment by mihailik** [comment] 2015-06-05 18:33
How about this approach around this line:
https://github.com/Microsoft/TypeScript/blob/master/src/compiler/sys.ts#L324

``` typescript
        declare hostSystemSupport: ts.System;

        if (typeof hostSystemSupport !== 'undefined') {
          return hostSystemSupport;
        }
        else if (typeof WScript !== "undefined" && typeof ActiveXObject === "function") {
            return getWScriptSystem();
        }
        else if (typeof module !== "undefined" && module.exports) {
            return getNodeSystem();
        }
        else {
            return undefined; // Unsupported host
        }
```

So rather than faking WSH or node (both rich and complex apis), your Chakra host will implement exactly what tsc needs in the first place.

And as a side effect it will open the door for easy hosting of tsc in other weird and wonderful scenarios.

**Comment by jamesxv7** [comment] 2015-08-07 04:10
Correct me if I'm wrong but if I create a new `.ts` file into the folder been watched by the `--watch` option of the tsc compiler, I need to execute again the `tsc --watch` command in the bash or terminal? It is this behavior by design? This occurs on Mac and also on Windows.

Will be possible to add into the `--watch` options the functionality to not be necessary to re execute the command each time a new file is added to the project (or folder)?

**Comment by mhegazy** [comment] 2015-08-07 16:00
currently the compiler only adds watches to files. the problem is node does not provide a native directory watcher capabilities. we would have to either do it based on file watchers, which would not scale, or include a timestamp based implementation. we are open to suggestions here if any one has better ideas on how to get this to work.

I do not think this is related to this issue. this issue is to enable --watch for tsc.exe. we should file a different issue for the directory watcher in --w.

**Comment by jamesxv7** [comment] 2015-08-07 18:32
I agree with you @mhegazy, that was my impression when I start writing the comment. I will continue the discussion in other issue. Thanks for the feedback and the information about Node.js.

**Comment by mindplay-dk** [comment] 2016-12-06 16:04
This has been implemented, I think this issue can be closed?

**Comment by mhegazy** [comment] 2016-12-06 17:26
> This has been implemented, I think this issue can be closed?

no. this has not been implemented.

**Comment by saturn72** [comment] 2018-11-13 10:18
This is the solution which works for me. [see](https://stackoverflow.com/questions/40650803/typescript-wwatch-is-not-working-in-my-installation/53278689#53278689)

**Comment by jsmunroe** [comment] 2018-12-30 23:53
I'm looking for a way to build ts into javascript files not run them. Those are two completely different things. So I don't need node. I need tsc.exe.  If tsc.exe does not support --watch, then why does Visual Studio Code have that as an out-of-the-box build task to do that? Nothing in this entire post makes any sense at all. I just want my ts project to build when I save something in VS code.

Any help would be appreciated. I've been a developer for 14 years on the .Net stack, but working in the JavaScript/NPM world everything is like pulling teeth! Sorry, just really frustrated. I should be off the ground by now. I already know TS and I've been writing javascript for more than a decade. It's the tooling that is terrible.  I just can't get VS Code to work right. I think I might just go back to Visual Studio where things actually work. I just feel like you all make things way harder than they need to be just so you can feel like hackers.

**Comment by jsmunroe** [comment] 2018-12-30 23:55
Sorry again. I think I'll just get by manually building after every single save like it's the 1990's.

**Comment by jsmunroe** [comment] 2018-12-31 00:07
Can someone explain to me if `tsc.exe` does not support `--watch`. Why does Visual Studio Code have a `tsc --watch -p` build task? Also, `tsc` doesn't run code. I have no idea what you guys are talking about there. It compiles typescript into javascript. Personally, I'm writing typescript to run in the browser.  I don't need node. I just want VS Code to build javascript from my tsconfig.json when I save a typescript file. I'm new to VS Code, but this is a really simple thing for a program to solve. Building it manually works just fine.

Sorry, but I'm really frustrated and finding this command line stuff to be a bit unnecessary.

**Comment by DanielRosenwasser** [comment] 2018-12-31 04:14
Since `tsc.exe` is being discontinued ([new versions of Visual Studio and NuGet will be shipping with `tsc.js` and expect Node to be installed](https://blogs.msdn.microsoft.com/typescript/2018/11/29/announcing-typescript-3-2/)), I think it's appropriate to close this issue. Users will now be able to install Node and get the expected `--watch` functionality.

**Closed** 2018-12-31 04:14 UTC
Labels: Unactionable, Visual Studio
