### ISSUE TITLE
`tsc --init` should generate `tsconfig.json` without comments

### ISSUE THREAD

**Issue by yukulele** [microsoft/TypeScript#53746] opened 2023-04-11 21:59 UTC
# Suggestion

## 🔍 Search Terms

- tsconfig comments tsc init

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

`tsc --init` creates a configuration file with all possible parameters commented with their descriptions. 
* It is very difficult to read and use. 
* Each time I start with the tedious task of deleting all these comments.

I think `tsc --init` should create a `tsconfig.json` file without comments.

Why?
* `tsconfig.json` is not the documentation.
* `tsc --init` give a link to the documentation (https://aka.ms/tsconfig) in the terminal.
* A modern editor is able to suggest possible options and display their descriptions and link to their documentation.
* 

Expected `tsconfig.json` content after `tsc --init`:

```jsonc
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
  }
}
```

**Comment by MartinJohns** [comment] 2023-04-11 22:47
Duplicate of #46150.

**Comment by yukulele** [comment] 2023-04-11 22:51
> Duplicate of #46150.

I make the same observation as on this issue but it is not the same proposal.

**Closed** 2023-04-14 18:00 UTC
Labels: Duplicate
