### ISSUE TITLE
Visual Studio freezes/hangs when stepping into functions while debugging

### ISSUE THREAD

**Issue by BernardHymmen** [Microsoft/TypeScript#1994] opened 2015-02-10 02:27 UTC
I've been using TypeScript successfully in my project for a while now (love it!), but after making some changes to my code recently I've run into an issue where Visual Studio now hangs whenever I step into a function while debugging.  I won't claim that my changes were bug-free, but bringing Visual Studio to a full stop doesn't seem like something my changes should have caused.  Also, I continue to see this behavior after reverting those recent changes to a point where I'm certain things were still working fine with TypeScript.

I'm running Visual Studio Ultimate 2013 Update 4 and I did a repair installation on it while struggling with this problem.  I originally was using TypeScript v1.0 but upgraded to v1.4 in hopes it would solve the problem, but it did not.  I'd be happy to provide logs and traces and so forth if someone can tell me where to find them.

**Comment by RyanCavanaugh** [comment] 2015-02-10 03:06
(Note: internal customer -- contact for repro details)

**Comment by softwarekontor** [comment] 2015-02-12 08:47
Totally the same problem here! Looking forward for a bugfix! Greetz

**Comment by BernardHymmen** [comment] 2015-03-11 01:33
Any progress on this?  I have a project I'd be happy to share for investigation.  

My problems with this bug have only gotten worse (i.e. more frequent) since I first reported it and I'm also now starting to see the following weird breakpoint behaviors

* Unable to set breakpoints on certain lines
* Breakpoints wil get set on lines above or below where I actually selected
* Breakpoint will highlight only a fragment of a line
* Breakpoint will highlight nonsensical ranges across multiple lines.  

I haven't been able to find any way to reset whatever corrupted underlying data stucture guides the breakpoint locations.  Normal tricks like deleting the \*.suo file or \*.js.map files don't seem to help.  This *feels* like it's realted to the crashing problem, but I have no way to really know

**Comment by mhegazy** [comment] 2015-03-11 04:42
@BernardHymmen can you share your project? My email is my github user name @micrsoft.com

**Comment by paulvanbrenk** [comment] 2015-03-13 21:54
Found a workaround and checked in a different workaround which should make this less painful in the future.. looks like an issue somewhere in the Asp.Net stack, following up with them.

The workaround is too disable 'ASP.Net' debugging in the project properties when you want to debug the script code.

**Comment by paulvanbrenk** [comment] 2015-03-13 23:07
Going to mark this as a dupe of #1999  since that has workaround and more contributors. We can re-open a new bug for the breakpoint issue when that re-occurs (as discussed via email).

**Closed by paulvanbrenk** 2015-03-13 23:07 UTC
Labels: Bug, Duplicate
