### ISSUE TITLE
Type guard doesn't work on nested fields when wrapped in a function

### ISSUE THREAD

**Issue by drew-vanta** [microsoft/TypeScript#54318] opened 2023-05-18 23:11 UTC
# Bug Report

Type guards are applied for some expressions referenced in a nested arrow function. This, however, isn't the case if the expression is a property access expression.

In particular, if I have the following code:
```ts
type NestedType = {
  field: number | string;
}

type NestedType = {
  field: number | string;
}
type NotNestedType = number | null;

const doNothingFn = <T>({
  fn,
} : {
  fn: () => T;
}) : T => {
  return fn();
}
```

the following type checks just fine:
```ts
const needsToReturnNum = (arg: NestedType):number => {
  return typeof arg.field === "number" ? arg.field : 0;
}

const needsToReturnNumNotNested = (arg: NotNestedType):number => {
  return typeof arg === "number" ? arg : 0;
}

const needsToReturnNumNotNested2 = (arg: NotNestedType):number => {
  return typeof arg === "number" ? doNothingFn({
    fn: () => arg,
  }) : 0;
}
```

This code, however, doesn't type check:
```ts
const needsToReturnNum2 = (arg: NestedType):number => {
  return typeof arg.field === "number" ? doNothingFn<number>({
    fn: () => arg.field,
  }) : 0;
} 
```

with the following error:
```ts
Type 'string | number' is not assignable to type 'number'.
  Type 'string' is not assignable to type 'number'.
```

### 🔎 Search Terms
I used the search expression. `is:issue is:open label:Bug type guard narrowing property access expression`

### 🕗 Version & Regression Information
This fails in the typescript all versions available: 
- 5.1.0-beta
- 5.0.4
- 4.9.5
- 4.8.4
- 4.7.4
- 4.6.4
- 4.5.5
- 4.4.4
- 4.3.5
- 4.2.3
- 4.1.5
- 4.0.5
- 3.9.7
- 3.8.3
- 3.7.5
- 3.6.3
- 3.5.1
- 3.3.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0&ts=5.1.0-beta&ssl=22&ssc=3&pln=18&pc=1#code/C4TwDgpgBAchDOwIBMAq5oF4oG8CwAUFFAGYCWEANsgFxQB2ArgLYBGEATlAD5SIdl6AcwDchAL6FQkWAHtgcRCnQzsTNpx4NGlSmIKEAxrPqIoyWTHkALQUIBi9KNgA8qAHwAKfEVL0ANBJQdD7EJPR0ngCUzu5QqPriMXSosbiExBwQwIwcTuHRiYRGJmb0ECjwqLIAStm59DAszlCeAIYcQnSKSGgYUTTq7FyYcaFQWTl5UNIQsiRQHUIAdORUyM6Y2ABEQ5zbUAD8i52rFNTBUAAMRQYExqbADBXIVbX1eU3MAEwt7Z3dBC9FQQAZ7EZjDITD5OWbzE4rNYXLY7cEHY4WKzAWzCRwucFecZhCKtGKjBFndaBXxJS43ILFO4lR7PSrVOpTRosLE9FB-JbdeS8vqQMEsYZpcaTBozDDwpabVHi-ZHBF027MsovN4chpfHlAlC-bD-LpyBSGkWgwbKiHpXzS6ZwhYKlFQXa29HmSw2OyObxQ4mRMlxJbU4i0uj0gjiIA)

note that JSX needs to be turned off/set to "None".

### 💻 Code

```ts
type NestedType = {
  field: number | string;
}
type NotNestedType = number | null;

const doNothingFn = <T>({
  fn,
} : {
  fn: () => T;
}) : T => {
  return fn();
}

const needsToReturnNum = (arg: NestedType):number => {
  return typeof arg.field === "number" ? arg.field : 0;
}

const needsToReturnNum2 = (arg: NestedType):number => {
  return typeof arg.field === "number" ? doNothingFn<number>({
    fn: () => arg.field,
  }) : 0;
} 



const needsToReturnNumNotNested = (arg: NotNestedType):number => {
  return typeof arg === "number" ? arg : 0;
}

const needsToReturnNumNotNested2 = (arg: NotNestedType):number => {
  return typeof arg === "number" ? doNothingFn({
    fn: () => arg,
  }) : 0;
}
```

### 🙁 Actual behavior

This fails to type check.

### 🙂 Expected behavior

The code presented in the playground should type check.

**Comment by jcalz** [comment] 2023-05-19 02:34
Duplicate of #9998 (and therefore many others).   I think #52055 probably explains what's going on here more or less.

**Closed** 2023-05-25 18:00 UTC
Labels: Duplicate
