### ISSUE TITLE
instanceof narrowing inference not working on references

### ISSUE THREAD

**Issue by idoros** [Microsoft/TypeScript#5702] opened 2015-11-17 16:32 UTC
```jsx
var htmlElement:HTMLElement = getElement()

// 
var offsetParent = htmlElement.offsetParent;
if(offsetParent instanceof HTMLElement){
	htmlElement = offsetParent; // OK!
}

// alternatively this will cause an error:
if(htmlElement.offsetParent instanceof HTMLElement){
	htmlElement = htmlElement.offsetParent; // ERROR: Assigned expression type Element is not assignable to type HTMLElement 
}
```

**Comment by mhegazy** [comment] 2015-12-02 05:06
looks like a duplicate of #1260

**Closed by mhegazy** 2015-12-02 05:06 UTC
