### ISSUE TITLE
Default parameter discards undefined type

### ISSUE THREAD

**Issue by whitneyit** [Microsoft/TypeScript#22476] opened 2018-03-12 01:47 UTC
**TypeScript Version:**
2.7.2

**Search Terms:** 
[deconstruct function arguments](https://github.com/Microsoft/TypeScript/search?q=deconstruct+function+arguments&type=Issues)
[default parameters](https://github.com/Microsoft/TypeScript/search?q=default+parameters&type=Issues)

**Code**

```ts
// --strictNullChecks
type Options = {
    prop?: string;
};

function test({ prop }: Options = {}): void {
    if (prop === undefined) {
        prop.toLowerCase() // prop is always of type `string`
        return;
    }
}

test();
```

**Expected behavior:**
prop is type `string` | `undefined`

**Actual behavior:**
prop is type `string`

**Playground Link:**
[playground](http://www.typescriptlang.org/play/#src=%2F%2F%20--strictNullChecks%0D%0Atype%20Options%20%3D%20%7B%0D%0A%20%20%20%20prop%3F%3A%20string%3B%0D%0A%7D%3B%0D%0A%0D%0Afunction%20test(%7B%20prop%20%7D%3A%20Options%20%3D%20%7B%7D)%3A%20void%20%7B%0D%0A%20%20%20%20if%20(prop%20%3D%3D%3D%20undefined)%20%7B%0D%0A%20%20%20%20%20%20%20%20prop.toLowerCase()%0D%0A%20%20%20%20%20%20%20%20return%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Atest()%3B)

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/17667

**Notes:**
The fix suggested by @sandersn in https://github.com/Microsoft/TypeScript/issues/17667#issuecomment-335550946 also fails when no value for `a` or `b` is provided.
```ts
const want = ({ a, b }: { a?: number, b?: number} = {}) => {
    a.toFixed(2)
};
want()
```

**Comment by KrisChambers** [comment] 2018-03-12 17:12
This seems to also be an issue even without any deconstructing.

**Playground link:** [playground](http://www.typescriptlang.org/play/#src=%2F%2F%20--strictNullChecks%0D%0A%0D%0Afunction%20test(options%3F%3A%20%7B%20prop%3F%3A%20string%20%7D)%0D%0A%7B%0D%0A%20%20%20%20console.log(%22This%20executes%22)%3B%0D%0A%0D%0A%20%20%20%20const%20x%20%3D%20options.prop%3B%20%20%20%20%2F%2F%20Runtime%20error%20%3A%3A%20TypeError%3A%20Cannot%20read%20property%20'opt1'%20of%20undefined%0D%0A%0D%0A%20%20%20%20console.log(x)%3B%0D%0A%7D%0D%0A%0D%0Atest())

**Comment by yortus** [comment] 2018-03-13 01:17
I can't reproduce this issue with either 2.7.2 or a recent (0307) nightly. They both error on the `prop.toLowerCase()` line.

BTW your playground example does not appear to have `strictNullChecks` enabled in the options.

**Comment by yortus** [comment] 2018-03-13 01:27
The following version shows the issue you are talking about in 2.7.2 ([playground](http://www.typescriptlang.org/play/index.html#src=%2F%2F%20--strictNullChecks%0D%0Atype%20Options%20%3D%20%7B%0D%0A%20%20%20%20prop%3F%3A%20string%3B%0D%0A%7D%3B%0D%0A%0D%0Afunction%20test(%7B%20prop%20%7D%3A%20Options%20%3D%20%7B%7D)%3A%20void%20%7B%0D%0A%20%20%20%20prop.toLowerCase()%3B%20%2F%2F%20TSC%20says%20type%20of%20prop%20is%20string%20here%0D%0A%7D%0D%0A%0D%0Atest()%3B%20%2F%2F%20this%20will%20crash%20because%20prop%20will%20be%20undefined%0D%0A)):
```ts
// --strictNullChecks
type Options = {
    prop?: string;
};

function test({ prop }: Options = {}): void {
    prop.toLowerCase(); // TSC says type of prop is string here
}

test(); // this will crash because prop will be undefined
```

However it appears to be fixed in the nightlies.

**Closed** 2018-04-03 23:14 UTC
Labels: Fixed
