### ISSUE TITLE
Why doesn't an implementation use the types on its parameters from its interface?

### ISSUE THREAD

**Issue by Wideshanks** [Microsoft/TypeScript#6854] opened 2016-02-02 21:54 UTC
```typescript
interface Bank {
	balance: number;
	withdraw(x: number): number;
}

class PowellCountyBank implements Bank {
	balance: number = 0;
	
	withdraw(x) {
		return (this.balance - x);
	}
}

var b = new PowellCountyBank();

console.log(b.withdraw({}));
                     // ^ Expect type error here.
```

([Playground](http://www.typescriptlang.org/Playground#src=interface%20Bank%20%7B%0D%0A%09balance%3A%20number%3B%0D%0A%09withdraw(x%3A%20number)%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aclass%20PowellCountyBank%20implements%20Bank%20%7B%0D%0A%09balance%3A%20number%20%3D%200%3B%0D%0A%09%0D%0A%09withdraw(x)%20%7B%0D%0A%09%09return%20(this.balance%20-%20x)%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Avar%20b%20%3D%20new%20PowellCountyBank()%3B%0D%0A%0D%0Aconsole.log(b.withdraw(%7B%7D))%3B%0D%0A))

The implementation shows the return type of `withdraw` but not type for the parameter:

![image](https://cloud.githubusercontent.com/assets/2061925/12765569/39a063da-c9cd-11e5-933c-880c44828a69.png)

**Comment by ahejlsberg** [comment] 2016-02-02 22:37
Duplicate of #3667. Fix available in #6118.

**Comment by ahejlsberg** [comment] 2016-02-02 22:40
Actually, #6118 doesn't affect methods, only property initializers. Reopening as suggestion.

**Comment by sandersn** [comment] 2016-02-02 22:52
Commit 055ae8cd5ca9838ad03a37f2386802c7cebea1b3 from #6118 adds method contextual typing as well. Here's a cut-down sample from the test (it works for extending classes, too):

```ts
interface Ringer {
	ring: (times: number) => void;
}
class Alarm implements Ringer {
	str: string;
	ring(times) {
		this.str = times; // error
	}
}
```

**Closed by sandersn** 2016-02-02 22:52 UTC
Labels: Suggestion
