### ISSUE TITLE
Adding throws to function signatures

### ISSUE THREAD

**Issue by Mike96Angelo** [microsoft/TypeScript#52145] opened 2023-01-08 17:07 UTC
# Suggestion

## 🔍 Search Terms

- throw
- throws
- try catch

## ✅ Viability Checklist

My suggestion meets these guidelines:

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I have seen that people have been asking for this for years. There are two main reasons that people want this, first to get better typing in `try catch` statements, and second to get the compiler to warn or error when a function that throws is called without handling the possible thrown value. As it is the goal of TypeScript to bring type safety to JavaScript, I think this would be huge in helping TypeScript developers write code that is more reliable and deterministic.

See: https://github.com/microsoft/TypeScript/issues/13219

My goal here is to propose a design that provides the desired features while being backwards compatible. In this proposal we will look at:

1. Adding a compiler option for `strictThrows: boolean`
1. Adding `throws` to function signatures.
1. Getters/Setters can throw, how do we handle that?
1. How `throws` is inferred.
1. How `catch(e)` is inferred in non-async functions.
1. Working with `throws` in generics and conditionals.
1. Updates to `Promise` types.
1. How this effects `async/await`.
1. How catch(e) is inferred in async functions

## Adding a compiler option for `strictThrows: boolean`

With `strictThrows` set to `false` we still get the benefit of better typing in `try catch` statements, however the compiler does not warn/error when functions that throw are called and not handled. There are a few other nuances that will be addressed in later sections.

## Adding `throws` to function signatures.

The thrown type is declared following the return signature separated by `throws`. If there is no `throws <type>` in the signature it is equivalent to `throws never` which means that the function does not throw -- this is important for generics which we will discuss later. In intellisense we can omit the `throws` clause if the thrown type is `never`, however in this proposal I am going to include them for clarity.

```ts
function test(): string {...}

type test = typeof test;
//   ^? () => string throws never

function testThrows(): string throws Error {...}

type testThrows = typeof testThrows;
//   ^? () => string throws Error

function testPromiseThrows(): Promise<string> throws Error {...}

type testPromiseThrows = typeof testPromiseThrows;
//   ^? () => Promise<string> throws Error

async function testAsync(): Promise<String> throws Error {...}
//                                          ^^^^^^^^^^^^
// Error: async function signatures can't specify throws as any awaited Promises that reject
// or any thing thrown within its body causes it to return Promise.reject(<thrown/rejected value>)
// rather than throwing.
```

## `Getters/Setters` can throw, how do we handle that?
Because `Getters/Setters` can throw, it might be helpful to think of `throws` as a type modifier rather than only something that functions can do. `throws` is followed by one or two type separated by a coma, the first type represents a type that could be throws while trying to `get` the value, the second type represents a type that could be throws while trying to `set` the value.  In the case of functions it is illegal to declare the `set` case as you can only `get` the return value and not `set` it. For object properties you can declare both, perhaps the setter throws but the getter doesn't, or perhaps they both throw but different types.
```ts
let a: string | undefined;

const o = {
    get value() {
        if (a == null) {
            throw new Error('a is not a string');
        }
        
        return a;
    }
    
     set value(val: unknown) {
        if (typeof val !== 'string') {
            throw new TypeError('cannot set val to a because val is not a string');
        }
        
        return a = val;
    }
}

type o = typeof o;
//   ^? { value: string throws (Error, TypeError) }

function doSomething(v:  { value: string }) {...}

// compiler option strictThrows: false
doSomething(o); // ok

// compiler option strictThrows: true
doSomething(o); 
//          ^
// Error type `{ value: string throws (Error, TypeError) }` is not assignable to 
// type `{ value: string throws (never, never) }`
// because type `Error` is not assignable to type `never` and
// because type `TypeError ` is not assignable to type `never`
```

## How `throws` is inferred.

The thrown type can be inferred in two ways depending on a new compiler option `strictThrows: boolean`. The first way is to look at the type of the value thrown in a `throw` statement. The second way is to take the union of all thrown types from functions called within a the function being inferred (this does not apply if the compiler option `strictThrows` is set to `true`).

```ts
function mayThrowError(shouldThrow: boolean) {
    if (shouldThrow) throw new Error("message");
}

type mayThrowError = typeof mayThrowError;
//   ^? (shouldThrow: boolean) => void throws Error

function mayThrowString(shouldThrow: boolean) {
    if (shouldThrow) throw "my error" as const;
}

type mayThrowString = typeof mayThrowString;
//   ^? (shouldThrow: boolean) => void throws 'my error'

// compiler option strictThrows: false
function test1() {
    mayThrowError(true); // allowed
    mayThrowString(true); // allowed
}

type test1 = typeof test1;
//   ^? () => void throws Error | 'my error'

// compiler option strictThrows: true
function test2() {
    mayThrowError(true);
//  ^^^^^^^^^^^^^^^^^^^
// Error: unhandled possible thrown `Error`.
// Place this in a try catch or add `Error` to test2's throws signature.
    mayThrowString(true);
//  ^^^^^^^^^^^^^^^^^^^^
// Error: unhandled possible thrown `'my error'`.
// Place this in a try catch or add `'my error'` to test2's throws signature.
}

type test2 = typeof test2;
//   ^? () => void throws never

// asserts should infer throws even if compiler option strictThrows: true
function assertString(str: unknown): asserts str is string {
    if (typeof str !== "string") {
        throw new TypeError(`Expected a string but got a ${typeof str}`);
    }
}

type assertString = typeof assertString;
//   ^? (str: unknown) => asserts str is string throws TypeError
```

## How `catch(e)` is inferred in non-async functions.

In `non-async function` the `catch(e)` is inferred as a union of the thrown type of any `functions` called, and any `throw` statements within the associated try block.

```ts
function doesNotThrow(): void {...};

try {
    doesNotThrow();
} catch (e) {
//       ^? unknown
}

function doesThrowError(): void throws Error;

try {
    doesThrowError();
    throw 'my error' as const
} catch (e) {
//       ^? Error | 'my error'
}
```

## Working with `throws` in generics and conditionals.

When restricting a generic type or in conditional types with `extends`, if compiler option `strictThrows` is `false` and throws is left out, it is treated as if it was set to `throws any`. If compiler option `strictThrows` is `true` and throws is left out, it is treated as if it was set to `throws never`.

```ts
// helpful utility type to inspect the thrown type
type Throws<T> = T extends (...args: any[]) => any throws infer K ? K : never;

function square(num: number): number {...}
function squareThrows(num: number): number throws Error {...}

function wrap<T extends (...args: any) => any>(func: T): T {...}

wrap(square); // ok
// compiler option strictThrows: false
wrap(squareThrows); // ok

// compiler option strictThrows: true
wrap(squareThrows);
//   ^^^^^^^^^^^^
// Error: type `(num: number) => number throws Error` is not assignable to
// type `(...args: any) => any throws never`
// because type `Error` is not assignable to type `never`.

// this function throws what the pasted in mapper function throws.
// so if mapper doesn't throw then map doesn't as well and vice versa.
function map<T, M extends (item: T) => any throws any>(arr: T[], mapper: M): ReturnType<M> throws Throws<M>;

const nums: number[];

const mapped1 = map(nums, square);
//              ^? (arr: number[], mapper: (num: number) => number throws never) => number[] throws never

const mapped2 = map(nums, squareThrows);
//              ^? (arr: number[], mapper: (num: number) => number throws Error) => number[] throws Error
```

## Updates to `Promise` types and async/await.

Because `awaiting` a Promise that rejects acts like throwing a value in an `async function` we need to capture the rejected type in the Promise to get the same benefits of the `throws` as `non-async functions`.

```ts
type ThenReturn<T> = T extends (v: any) => infer P extends Promise<any, any>
    ? P
    : T extends (v: any) => infer Return throws infer Thrown
    ? Promise<Return, Thrown>
    : never

interface Promise<T, R = never> {
    then<Resoled extends (value: T) => any throws any, Rejected extends (reason: R) => any throws any>(onresolved: Resoled, onrejected?: Rejected): ThenReturn<Resoled | Rejected>

    catch<Rejected extends (reason: R) => any throws any>(onrejected?: Rejected): ThenReturn<Rejected>

    finally(onfinally?: (() => void) | null | undefined): Promise<T, R>
}

interface PromiseConstructor {
    new <T, R = never>(cb: (resolve: (value: T) => void, reject?: (reason: R) => void) => void): Promise<T, R>
}
```

## How this effects `async/await`.

`Async functions` are a bit more complicated. An `async function` returns a rejected Promise when one of the following occurs: it executes a `throw` statement within its body, it calls a `non-async function` that `throws`, or it `awaits` a promise that rejects.

```ts
function throwsString(): void throws 'thrown error';
function neverRejects(): Promise<string>;
function rejectsWithError(): Promise<string, Error>;
function rejectsWithString(): Promise<string, "rejected promise">;

// Compiler option strictThrows: false
async function test1() {
    throwsString(); // ok
    await neverRejects(); // ok
    await rejectsWithError(); // ok
    await rejectsWithString(); // ok
}

type test1 = typeof test1;
//   ^? () => Promise<void, Error | 'rejected promise' | 'thrown error'> throws never

// Compiler option strictThrows: true
async function test2() {
    throwsString();
//  ^^^^^^^^^^^^^^
// Error: unhandled possible thrown `'thrown error'`
    await neverRejects(); // ok
    await rejectsWithError();
//  ^^^^^^^^^^^^^^^^^^^^^^^^
// Error: unhandled possible thrown `Error`
    await rejectsWithString();
//  ^^^^^^^^^^^^^^^^^^^^^^^^^
// Error: unhandled possible thrown `'rejected promise'`
}

type test2 = typeof test2;
//   ^? () => Promise<void, never> throws never

async function test3(): Promise<void, Error | 'thrown error'> {
    throwsString(); // ok as test3's throws signature allows it
    await neverRejects(); // ok as this never rejects
    await rejectsWithError(); // ok as test3's throws signature allows it
    await rejectsWithString();
//  ^^^^^^^^^^^^^^^^^^^^^^^^^
// Error: unhandled possible thrown `'rejected promise'`
}

type test3 = typeof test3;
//   ^? () => Promise<void, Error | 'thrown error'> throws never
```

## How `catch(e)` is inferred in `async functions`

In an `async function` the `catch(e)` is inferred the same as `non-async functions` with one addition. The inferred value is a union of the thrown type of any `non-async functions` called, `throw` statements, and the rejected reason of any awaited `Promises` within the associated try block.

```ts
function throwsString(): void throws 'thrown error';
function neverRejects(): Promise<string>;
function rejectsWithError(): Promise<string, Error>;
function rejectsWithString(): Promise<string, "rejected promise">;

async function test() {
    try {
        throwsString(); // might throw `'thrown error'`
        await neverRejects(); // ok never throws
        rejectsWithError(); // ok not awaited
        await rejectsWithString(); // might throw `'rejected promise'`
    } catch (e) {
//           ^? 'thrown error' | 'rejected promise'
    }
}

type test = typeof test;
//   ^? () => Promise<void, never> throws never
```

**Comment by MartinJohns** [comment] 2023-01-08 19:42
Duplicate of #13219.

**Comment by RyanCavanaugh** [comment] 2023-01-09 18:08
I don't think there's much to work out in terms of *how* this would work, it's more a matter of *whether*. The linked issue is the place for discussion there.

**Closed** 2023-01-12 18:00 UTC
Labels: Duplicate
