### ISSUE TITLE
Split compiler component and common utils

### ISSUE THREAD

**Issue by Kingwl** [Microsoft/TypeScript#29454] opened 2019-01-17 06:02 UTC
## Search Terms
build

## Suggestion

provide signal compiler component and  tree shark

## Use Cases

I'd like to publish a web app with typescript (actually, factory and emitter only), but there are only one 'typescript.js' file has been provided, and that file is almost 7mb(before gzip), and that is sooooooo bit to a website

eg: https://ts-creator.js.org/ and each other typescript playground 

~~I have tried to pack the typescript with rollup and after tree shark, the factory has only 200kb size,~~
~~I consider to add ts as a submodule and build with myself config...~~

it does not work

As the result, could we provide more signal compiler components? that is useful to other terminal program too (ts-lint?)  

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2019-01-17 18:08
Duplicate of #27891

**Closed** 2019-01-20 18:00 UTC
Labels: Duplicate
