### ISSUE TITLE
support narrowing types of function arguments based on overloads

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#46422] opened 2021-10-19 01:17 UTC
# Suggestion

## 🔍 Search Terms
overload narrowing

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
it would be nice if you could rely on function overloads to more easily narrow parameters

## 📃 Motivating Example
in this case, it's impossible for `value2` to be undefined if `value1` isn't
```ts
function foo(): void
function foo(value1: number, value2: number): void
function foo(value1?: number, value2?: number): void {
    if (typeof value1 !== 'undefined') {
        //Type 'number | undefined' is not assignable to type 'number'.
        // Type 'undefined' is not assignable to type 'number'.(2322)
        const bar: number = value2
    }
}
```

**Comment by fatcerberus** [comment] 2021-10-19 04:57
I know there's at least one other issue discussing this, but I don't know what to search for to find it.

**Comment by MartinJohns** [comment] 2021-10-19 07:17
Related: #28167

**Comment by MartinJohns** [comment] 2021-10-19 07:19
Duplicate of #14515.

**Closed as completed** 2021-10-23 09:23 UTC
