### ISSUE TITLE
typescript throws error when you want to initialize an arrow function that returns different objects  based on overloaded string literal union type

### ISSUE THREAD

**Issue by reza-ss** [microsoft/TypeScript#55606] opened 2023-09-01 22:41 UTC
### 🔎 Search Terms

arrow function
union
overload

### 🕗 Version & Regression Information

all TS versions

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/PTAEDsHsCcFsEMA2oBmBXcBjALgS0uKJAG4Cm0ik8AJqAO4wDWAzvaYogIQBQ36WeAqGylm2ABTEAXACIAFu0oyAlFIDeCjpCng0sAEbkAvgG4+GHPkIixk2XNwr1DqfsiREpeOFO9zAq2FRbFA7UDFoXHAAc2U1blBQXBRJUABeDNB5RUgVeMTE6FJsNGhCDRypAEYAJgBmX0SjdmZSUCKSstANXClsaDRSI25hkHbi0vAAFQBPAAc23FZMGCKcTjMbCWytFTNuMew5aEg6VnIT6CTCeGgTulQLQXAebmx5tpJyShp07oSCnYdkpVBUtDo9IZoI1AdJ5I5QS43B4vD4zE0AQCVuAxEExDUpF8KFRaGlQsRlGkAHz5JIpYjpTLA3JxAGFCZdMGUar1GHNRCtcadcoufqDYYYg5gDqTWYLJLLVakdbovHYGriZl7IA

### 💻 Code

```ts
// normal function overload works well!

function test(v:"hello"):{hello:number};
function test(v:"hi"):{hi:boolean};


function test (v: string){
  if(v === "hello"){
    return {hello:123};
  }else return {hi:true}
}
// returnType is correct!;
test("hello");

// throws error in arrow function!

type overload = {
    (v:"hello"):{hello:number};
    (v:"hi"):{hi:boolean};
  }
  
  const test2:overload = (v)=>{
  if(v === "hello"){
    return {hello:123};
  }else return {hi:true}
  }

// returnType is correct!;
  test2("hello");
```

### 🙁 Actual behavior

typescript throws error when you want to initialize an arrow function that returns different objects  based on overloaded string literal union type. 

### 🙂 Expected behavior

TS most not throws error in this case as it does not throws error in normal function

**Comment by MartinJohns** [comment] 2023-09-01 23:13
Duplicate of #47669. Currently arrow functions do not support overloading.

**Closed** 2023-09-04 01:25 UTC
Labels: Duplicate
