### ISSUE TITLE
Get the correct type of elements with querySelector

### ISSUE THREAD

**Issue by zuhairtaha** [microsoft/TypeScript#45787] opened 2021-09-08 16:49 UTC
# Suggestion

## 🔍 Search Terms

document query selector elements type

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When we use `document.querySelector` and `querySelectorAll` I suggest getting the correct element type instead of `Element` if it starts with a valid HTML tag

## 📃 Motivating Example

```ts
const ul = document.querySelector('ul.list');
const input = document.querySelector('.container input[type=text]');
```
The inferred type of `ul` should be `HTMLUListElement` instead of `Element`
and for `input` it should be `HTMLInputElement` not `Element`

## 💻 Use Cases

With this feature we will not need to write something like this
```ts
const input = document.querySelector('.container input[type=text]') as HTMLInputElement;
```
*Note* 
In some cases, it is obviously an item type, but in other cases cannot be discovered like `querySelector('.menu')`

**Comment by andrewbranch** [comment] 2021-09-08 16:57
Duplicate of https://github.com/microsoft/TypeScript/issues/29037

**Closed by andrewbranch** 2021-09-08 16:57 UTC
