### ISSUE TITLE
TypeScript removes JSDoc comments for overloaded functions

### ISSUE THREAD

**Issue by joshuat** [microsoft/TypeScript#47228] opened 2021-12-23 01:15 UTC
# Bug Report

TypeScript removes JSDoc comments from above overloaded functions regardless of `removeComments`.

### 🔎 Search Terms

comment; removeComments; overloaded comments;

### 🕗 Version & Regression Information

This is present in all versions from v3.3.3 and above, likely below as well.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/PQKhCgAIUgFAnApgZ0fAbogJpAVsgEQHsBjSEogW0sQDsAXKEYcRADwAcj57IAzAK60S9AJZFakWkQDymeABsiAQywAKKJHTKFAxAC4pAygCM0AGnABKQ7WNn4kAN6ak9AfEnbdiaJABM4AC+4OCgEH4AsqLIyKK0AOZ4hKTkVDQMTCzsXDz8QiLikkTySqrYGpBaOnq29hbWdaZoANysnNy8gsJiEpAlaGVYFZretZDI9PDxCZY2E1MzbTmd+T1F-aUqw+qjNQZGzY4APgvTiXNNDpCnk+dJLlWifJBq9ACeHIhEL2O+ALyAyAAcjsR2BVmcmiqbg8Xn2fn8bSqISeLzen2+vwRgP+ILuMwhUKqMMQ7k81R8kAA1CDgcjICE9lTlMgpIh5Az6AALeBEADu7MFAFF4Hz4GpgQBJWjeUQ4P4TAQcDgKUTYCFtJkrPLdQp9AaKbbYACCCWU8UqlPGYIcl0ODmWHV1BV6xS25SwZottCtf0MBIujTOSzCYCYcCQqAw2GSxDIFGodEY0Gyzq6ro2hqGpvNluZNvqJxDQfmtrQNxLD00z1eHy+P2tAKBoKLRMeJNhFMVMCRmlRkFrGIb2KpuPxi0S7ehkC78KptOB9P7oSqitZ7M5mh5fMFtEQIrF3ElMrlCoRyGVqvVWE1wXAQA)

### 💻 Code

```ts
/**
 * Missing jsDoc comment
 */
export function overloaded(
  value: number,
): number;
export function overloaded(
  value: string,
): string;
export function overloaded(
  value: number | string,
): number | string {
  if (typeof value === 'number') {
    return value * 2;
  }
  if (typeof value === 'string') {
    return value + '';
  }
}
```

### 🙁 Actual behavior

```js
export function overloaded(value) {
    if (typeof value === 'number') {
        return value * 2;
    }
    if (typeof value === 'string') {
        return value + '';
    }
    value;
    throw new Error('Invalid value supplied');
}
```

### 🙂 Expected behavior

```js
/**
 * Missing jsDoc comment
 */
export function overloaded(value) {
    if (typeof value === 'number') {
        return value * 2;
    }
    if (typeof value === 'string') {
        return value + '';
    }
    value;
    throw new Error('Invalid value supplied');
}
```

**Comment by david-shortman** [comment] 2021-12-23 02:36
Function overloads don't exist in JS, and the doc comments are removed. The comment is preserved when it is applied to the base method: [playground](https://www.typescriptlang.org/play?ts=4.5.4#code/PQKhCgAIUgFAnApgZ0fAbogJpAVsgEQHsBjSEogW0sQDsAXKEYcRADwAcj57IAzAK60S9AJZFakWkQDymeABsiAQywAKKJHTKFAxAC4pAygCM0AGnABKQ7WNn4kAN6ak9AfEnbdiaJABM4AC+4KHsXDz8QiLikkTySqrYGpBaOnq29hbWmaZoANysnNy8gsJiEpDxaIlYyZreGZDI9PCitADmljbNre0dhaAQfmoAckSQSp1oVpAAsqLIyP14hKTkVDQMTCzhJVHlsVUJKnXqDekGRnmOAD69bZ3duQ6Q9y2PHc6aonyQavQAJ4cRBEP6NXwAXmhkAA5HYbrDZi5Uqk3B4vJc-P5CqkQqlfv8gSCwWkfJBoZC4R9+kjvqjIOjPGS9JAANRw2G4yAhC7k5TIKSIeTc+gAC3gRAA7kKZQBReCS+BqWEASVo3lEOAhzQEHA4ClE2CRhV5e0iZRilWqilO2AAgh1lO0UiyrgiHM9rg5CubStEKnETkksI7nbRXRDDDSnjkHv1BmAmHAkKgMNhVsQyBRqHRGNBdsULQGjjbag6nS6+U0PWg3vHYz1a3cG18UZBCQDgaDwVjKXDm3T22jEO5mTqYDjNPiO38uyTe+T+7CYx0h5oR2PMeSObCudPQqkdQKhSLNOLJTLaIh5YruCr1ZrtVjkHqDUasCbguAgA)

**Comment by MartinJohns** [comment] 2021-12-23 07:03
Duplicate of #27981. Used search terms: `JSDoc overload in:title`

**Closed** 2021-12-23 07:05 UTC
