### ISSUE TITLE
Object literal is not a valid instance of any of the types in the declared type union

### ISSUE THREAD

**Issue by philipahlberg** [microsoft/TypeScript#40109] opened 2020-08-18 10:51 UTC
**TypeScript Version:**  3.9.2 (or 3.5.1 and up)

**Search Terms:**
Union types, object literal

**Code**

```ts
interface AB {
  a: string;
  b: number;
}

interface C {
  c: boolean;
}

const abc: AB | C = {
  b: 123,
  c: true,
};
```

**Expected behavior:** 
The declaration of the variable `abc` should not be valid. 

The error could be something along the lines of:

```
The type '{ b: number; c: true }' is not assignable to type 'AB | C'.
	Object literal may only specify known properties, and 'b' does not exist in 'C', and 'c' does not exist in 'AB'.
```

**Actual behavior:**
The declaration of the variable `abc` is valid.

**Playground Link:** [typescriptlang.org](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIICFkG8BQzlwBcyAzmFKAOYDceyARsSAK4C290tAvjjqJLEQoAwtjoJi9APZSANhDghuvAPQrkAESkQSyYGGQALOADcUYAJ4AHFBgD8ONcgByUm9WQADBJ+QATbRIQAHIDCAAPYDI9EDR0ADocBCkQaLhGOOQAXjF8ImRgmBlggBo6DIBGACYAZjL8CWRyZggyrlpHdS0dPQNjMybrEQcnV3cvel8AnRCwyOjQZGFE5NSDRtEc3DziQuL6hmJquvFiZtacdtUuwN6jUxQIfUNoQZs4kuQpKDfhzuQAJo6ByrNL0RoYZAAHyW2Vyh2QxwOjXObVoQA)

**Related Issues:** Couldn't find any.

**Comment by MartinJohns** [comment] 2020-08-18 13:01
Duplicate of #20863 (and many many more). Excess property checks are not performed for union types.

**Comment by RyanCavanaugh** [comment] 2020-08-18 15:52
Notably, object types are not sealed, so an excess property is not a per se error

**Closed** 2020-08-20 18:00 UTC
Labels: Duplicate
