### ISSUE TITLE
Error inheritance bug

### ISSUE THREAD

**Issue by elderapo** [Microsoft/TypeScript#25383] opened 2018-07-03 00:32 UTC
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** error inheritance

**Code**

```ts
class CustomError extends Error {}

try {
  throw new CustomError();
} catch (ex) {
  console.log(ex instanceof CustomError);
}

```

**Expected behavior:** should print `true` in both TypeScript and vanilla JS.

**Actual behavior:** if compiled with TypeScript and then ran in browser/node environment prints `false` but if ran without compilation prints `true`.

**Playground Link:**  http://www.typescriptlang.org/play/#src=class%20CustomError%20extends%20Error%20%7B%7D%0D%0A%0D%0Atry%20%7B%0D%0A%20%20throw%20new%20CustomError()%3B%0D%0A%7D%20catch%20(ex)%20%7B%0D%0A%20%20console.log(ex%20instanceof%20CustomError)%3B%0D%0A%7D%0D%0A

**Related Issues:**

**Comment by DanielRosenwasser** [comment] 2018-07-03 00:34
https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work

Duplicate of #12123

**Closed by DanielRosenwasser** 2018-07-03 00:34 UTC
Labels: Duplicate

**Comment by RyanCavanaugh** [comment] 2018-07-03 17:11
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work
