### ISSUE TITLE
Bug in transpileModule in ts 2.9.1

### ISSUE THREAD

**Issue by arackaf** [Microsoft/TypeScript#24729] opened 2018-06-06 17:26 UTC
Please try to reproduce the issue with `typescript@next`. It may have already been fixed.

**TypeScript Version:**  3.0.0-dev.20180606 - still fails

Search terms you tried before logging this (so others can find this issue more easily)

transpileModule, 2.9.1 

**Code**

No publicly available repro

This issue was originally raised here  

https://github.com/TypeStrong/ts-loader/issues/787#issuecomment-395145357

until it was realized this was a bug with TS itself.  It seems transpileModule is dropping valid, needed imports, which is creating runtime errors

**Expected behavior:**

Used imports will not be dropped

**Actual behavior:**

They're dropped

**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment] 2018-06-06 17:51
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/24551. should be fixed by https://github.com/Microsoft/TypeScript/pull/24591. 

The fix should be in `typescript@next` today, and in `typescript@2.9.2` next week.

Can you give typescript@next a try and confirm that my analysis is correct?

**Comment by arackaf** [comment] 2018-06-06 19:17
@mhegazy - my apologies, I said I had tested with ts@next, and I did, but I think webpack's cache-loader incorrectly served me old (wrong) results.  ts@next does indeed work.

Any idea when 2.9.2 will be out?  You said next week - I don't suppose there's any chance it could be sooner?

**Comment by manu-st** [comment] 2018-06-08 04:39
I have a reproducible project where even the latest version of TypeScript available did not work. See https://github.com/TypeStrong/ts-loader/issues/787#issuecomment-395644414

**Comment by mhegazy** [comment] 2018-06-08 16:06
here is the file text:

```ts
import { Options } from "./Options";
import { Parent } from "./Parent";

export class Child extends Parent
{
   constructor (name: string)
   {
      super ("1", name, new Options ());
   }
}
```

**Comment by mhegazy** [comment] 2018-06-08 16:07
So `super(new Options())` work, `super("", new Options())` does not.

thanks for the repro.

**Comment by mhegazy** [comment] 2018-06-11 20:17
Fixed by https://github.com/Microsoft/TypeScript/pull/24802

**Closed by mhegazy** 2018-06-11 20:17 UTC
Labels: Bug

**Comment by arackaf** [comment] 2018-06-11 20:27
@mhegazy you guys are awesome. Any idea when 2.9.2 will be out?

**Comment by mhegazy** [comment] 2018-06-11 20:47
Original plan is to get it out Wednesday. we are still looking at one final issue. so it could be Thursday. but barring any unforeseen circumstances, it should be out this week.

**Comment by arackaf** [comment] 2018-06-11 20:56
thanks a ton!
