### ISSUE TITLE
.includes or .indexOf does not narrow the type

### ISSUE THREAD

**Issue by minderov** [microsoft/TypeScript#36275] opened 2020-01-18 00:40 UTC
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:** `.includes type narrowing`, `.indexOf type narrowing`

**Code**

```ts
interface TextMessage {
    type: 'text',
    text: string
}

interface ImageMessage {
    type: 'image',
    url: string
}

type Message = TextMessage | ImageMessage;

// This is an example to reproduce the error in Playground.
// In practice, assume this message comes from outside our control (e.g. HTTP request)
const message: Message = JSON.parse(prompt('') as string) as Message;

if (message.type === 'text') {
    // No error here
    message.text = message.text.trim();
}

// Same for ['text'].includes(message.type)
if (['text'].indexOf(message.type) > -1) {
    // Error: Property 'text' does not exist on type 'ImageMessage'
    message.text = message.text.trim();
}
```

**Expected behavior:**
I expect `message` to narrow its type to `TextMessage` inside `if (['text'].indexOf(message.type) > -1)`.

Same way it does inside `if (message.type === 'text')`

**Actual behavior:**
`message` is typed as `TextMessage | ImageMessage` inside the `if` block
```ts
if (['text'].indexOf(message.type) > -1) {
    // Error: Property 'text' does not exist on type 'ImageMessage'
    message.text = message.text.trim();
}
```

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?target=1&module=5#code/JYOwLgpgTgZghgYwgAgCoQB5gLIQM55wDmKA3gFDJXJgCeADhAFzIDkkWrANJdR2CzxgooIuQC+5cqEixEKAJIBbYhFwFVyCtRoNmbYCpLdeVAK5QANoOGiJUuo2TrCJZAF40mHPlcoAPsjKqi6qANxSAPSRaAAWwHjICchwIMiYcEr0lihgAPbIUBD0UHkAJmZINLEo0KVQSWkACpZwtESlZiBlAHTk0UFpJYhgwEhcKQRmSrnxiTMabgh5C8gwpUrIeWZgeMBlKNsNy+CllsgAFBA9RD3IABKoqE2FEACOZvhgAJTkJ0LIBZ+FihNyeABSAGUAPIAOR69DgUDwEAuJRW9DAF1YrG+k2QQhEICIeLgiVBEAi0hglyBqh6jhQ7mZbH4uK0pmQA1hBTqeQaNSKnLpJAZ3g8gN89P4DJESgu3wikn6MUhmRQMH5yAA2uxvKwALo9UAISxmA54C4i66M37AGkXXVso2gA4YaEwK1S0W25AAPmQAFoAIx47TUAYAUSg9RYTVKjCgdFZ+uQZTy+GQIDyYHSGASubyaUZbGCJAprGF3pt4s81rFWFlhgVSqAA)

**Related Issues:** https://github.com/microsoft/TypeScript/issues/9842

My argument is that `if (message.type === 'text')` should be considered equivalent to `if (['text'].includes(message.type))`.

It might seem irrelevant on a small example like this, but if the array (`['text']`) is large, the workaround is difficult to maintain.

**Comment by RyanCavanaugh** [comment] 2020-01-21 18:36
This pattern doesn't occur often enough in ways that would produce useful narrowings to justify implementing whatever we'd have to do to detect it

**Comment by iansan5653** [comment] 2020-06-12 16:42
If #36352 were revisited, the `includes` function could be a lot more useful if the return type were an assertion, like:

```diff
interface Array<T> {
-    includes(searchElement: T, fromIndex?: number): boolean;
+    includes(searchElement: any, fromIndex?: number): searchElement is T;
}
```

IMO this is a much better way to type it than the current restriction, considering that the way it's currently typed makes `includes` pretty much useless with arrays of enumerated types.

**Comment by JGJP** [comment] 2020-10-01 05:25
@RyanCavanaugh What is the reason for practically making `.includes()` useless in conditionals? Is it really "we don't think enough people do this"? What is this assumption based on?

**Comment by RyanCavanaugh** [comment] 2020-10-01 15:59
@JGJP We didn't *make* it behave this way; this is the behavior absent the implementation of a feature that would cause it behave the way the OP is proposing. None of the existing narrowing mechanics apply here; we're talking about probably a thousand lines of new code to *correctly* detect and narrow arrays based on these methods, along with a performance penalty paid by every program because the control flow graph would have to be more granular to set up the possible narrowings caused by any method call, along with a bug trail and confusion trail caused by people expecting non-method versions of these functions to also behave the same way.

The proposed `includes` definition above is not correct because that's now how type guards work. You can trivially induce an unsoundness to occur using that definition:
```ts
interface Array<T> {
    includes2(searchElement: any, fromIndex?: number): searchElement is T;
}

declare let s: string | number;
if (["foo"].includes2(s)) {

} else {
    // 's' might be "bar" or any other string that's not "foo"
    s.toFixed();
}
```

**Comment by JGJP** [comment] 2020-10-02 12:52
@RyanCavanaugh Thanks for your detailed reply.

I can appreciate that it could be super difficult to implement what is suggested in this issue, but how about just not implicitly typing the array? Why are other variables implicitly typed as `any` but these arrays here aren't `any[]`? I would personally prefer that behavior, because it would allow us to use `.includes()` for its intended purpose (IMO) and we could configure the type error with `noImplicitAny`. Typescript is supposed to be building on Javascript, but in this case it's restrictive, and I don't see how the default behavior is useful (if not assigned to a variable).

**Comment by RyanCavanaugh** [comment] 2020-10-02 14:55
I'm not sure what you're proposing.

The current typing detects many kinds of errors, like
```ts
function fn(s: string) {
  const bannedUsers = ["bob", "alice"];
  if (bannedUsers.includes(s.toLowerCase)) {
    // you are banned
```

**Comment by JGJP** [comment] 2020-11-18 03:29
@RyanCavanaugh 
Sorry for the late reply. What we want to be able to do is something like this:
```js
function fn(s: string | null) {
	const bannedUsers = ["bob", "alice"]
	if (bannedUsers.includes(s)) {
		// you are banned
	}
}
```
Here, `bannedUsers` is being implicitly cast as `string[]`, which IMO is useful in some cases, but here the `includes()` call gives:
```
Argument of type 'string | null' is not assignable to parameter of type 'string'.
  Type 'null' is not assignable to type 'string'.
```
It also won't let us do things like `bannedUsers.push(somethingThatsNotAString)`

What solves these issues is changing the `bannedUsers` definition to:

```js
const bannedUsers = ["bob", "alice"] as any[]
```

I would personally prefer it if `any[]` was the default type of an array, instead of Typescript trying to type it without being able to look into the future to check usage. I can understand, however, that other users won't want this as the default behavior, so how about being able to set an option in tsconfig.json?

**Comment by RyanCavanaugh** [comment] 2020-11-18 18:17
@JGJP see #26255; the problem here is that `includes` should really be bivariant instead of covariant

**Comment by JGJP** [comment] 2020-11-19 02:42
@RyanCavanaugh I'm wondering why you're linking that issue, because it just shows the community making reasonable arguments and trying to come up with a solution, whereas your general stance seems to just be `just use Javascript`. Is this really the best we can do?

**Comment by RyanCavanaugh** [comment] 2020-11-20 00:50
@JGJP Why doesn't TypeScript already have every feature it will eventually need? The answer is that we haven't designed or completed those features yet, which is why we have an issue tracker and are employing a large team of developers to work on it. Having humans work on the product at a finite speed is in fact the best we can do, for now.

**Comment by RyanCavanaugh** [comment] 2020-11-25 19:46
Here's a declaration you can put in your project if you want the proposed "anything goes" behavior

```ts
interface Array<T> {
  includes(element: unknown, startIndex?: number): boolean;
}
```

**Comment by iansan5653** [comment] 2020-11-30 19:45
> The proposed includes definition above is not correct because that's now how type guards work. You can trivially induce an unsoundness to occur using that definition.

@RyanCavanaugh Thanks for the example. So just to clarify, the issue here is that there is no way to express something like "if true, element is T, else element may or may not be T"?

**Comment by RyanCavanaugh** [comment] 2020-11-30 20:08
@iansan5653 correct; see #15048

**Comment by JDBS** [comment] 2021-09-01 13:52
I think a distinction must be made between 2 situations:

** for value **
```js
const value: any = // some value;
```

**Case 1:  Generic type array**
```js
const possibleValues = ['red', 'pink'];
if (possibleValues.includes(value)) {
 // here possibleValues is Array<string> so  value will be of type string
}
```

**Case 2:  Literal Tuples array**
```js
const possibleValues: ['red', 'pink'] = ['red', 'pink']; // literal tuple array specified
// const possibleValues: Array<'red'|'pink'> = ['red', 'pink'];  
// also this one should be considered a valid alternative
if (possibleValues.includes(value)) {
 // here possibleValues is Array<'red' | 'pink'> and  value will be of type string
}
```

I think, for case 2, where array content can be only of the specified types, value makes sense to be considered that it is one of specified literals ('pink' | 'red') which is a type union. However right now, value stills being typed as any anyway.

This is not crazy due to array tuples brings errors in situations like the following one

```js
const possibleValues: ['red', 'pink'] = ['purple']; 
```

**Use case:**

I think there is an important use case for this feature.

```js
// dynamic enum generation
const allColors = {
  red: 'Red' as 'Red',
  blue: 'Blue' as 'Blue',
  Yellow: 'Yellow' as 'Yellow',
};

// enum keys
type AllColorsKeys = keyof typeof allColors;
// specific value related to key -> const red: ColorValue<'red'> = 'Red';
type ColorValue<Key extends keyof typeof allColors> = typeof allColors[Key];
// all values union ('Red' | 'Blue')
type AllColorsUnion = ColorValue<AllColorsKeys>;

```

```js
// safe available array typed as Array<AllColorsUnion>
const availableColorsTuple: Array<AllColorsUnion> = [
  allColors.red,
  allColors.blue,
];

if (availableColorsTuple.includes(specificValue)) {
  // specificValue should typed as AllColorsUnion
  switch (specificValue) {
    case allColors.red:
      break;
    case allColors.blue:
      break;
    default:
      break;
  }
}
```
So if you add any option to "allColors" object, everything will be safely updated (since object until the if or switch case).

**Comment by ilibar-zpt** [comment] 2022-05-30 17:40
@RyanCavanaugh what do you think about this [example](https://www.typescriptlang.org/play?#code/MYewdgzgLgBBCuAHApgJws2BeGBtA5AIb4A0+ARqfsPgLoyEQyiRQBQL0c85G2eRKpXqNm4aGygBPFDAAqyaAB45MZAA8oyMABMm0lCABm3FOky4w8ALbk09HAeTHTaPpZt3UtAHwwcAN5sMCEwggBcMAGE4QCMJFDhcgC+JMGhFPiRAeThAEwJSanpIdRZUcDhAMyFKWnJuHK0HOKwWlyByQxM8GAA1mAgAO5g3fKK7ACWJgAUCLyYAHSTYMAANvA6ijPtUItQAJQHMLuLhDAAPhcnE4vkQA)?
```ts
const superset = ['a','b','c'] as const
const subset = ['a','b'] as const
type Test<T extends typeof superset[number] = typeof superset[number]> = {
    'a': {a:1,t:T},
    'b': {b:2,t:T},
    'c': {c:3,t:T},
}[T]
const test = {} as unknown as Test
if (subset.includes(test.t)) // error 
```
`Array.prototype.includes` is intended for testing whether a value of a superset is part of a subset, current lib clearly misses that and requires that subset === superset

**Comment by HolgerJeromin** [comment] 2022-12-09 10:37
More simple example:

> Argument of type '"string" | "number" | "bigint" | "boolean" | "symbol" | "undefined" | "object" | "function"' is not assignable to parameter of type '"number" | "bigint"'.
> Type '"string"' is not assignable to type '"number" | "bigint"'.

```ts
const value = 'hello';
const allowedTypes = ['number', 'bigint'] as const;
const numberIsh = allowedTypes.includes(typeof value);

**Comment by jaredrethman** [comment] 2022-12-22 15:25
Echo'ing @HolgerJeromin findings. Wound up here trying to find information on the below scenario.

```ts
const varStr: string | number | object = 7;

if (["string", "number"].includes(typeof varStr)) {
  const foo = varStr; // foo is still inferred as "const foo: string | number | object"
}
```

**Comment by johnsoncodehk** [comment] 2023-01-27 06:57
> Here's a declaration you can put in your project if you want the proposed "anything goes" behavior
> 
> ```ts
> interface Array<T> {
>   includes(element: unknown, startIndex?: number): boolean;
> }
> ```

#52451 is an alternative, appreciate if you can help fix tests, otherwise I'll check it out when I have time.

**Comment by noppa** [comment] 2023-01-27 15:09
If you are willing to overwrite the global type with a more complex definition, you can also make it refine string union types [with this](https://github.com/microsoft/TypeScript/issues/26255#issuecomment-736971438)
```typescript
interface ReadonlyArray<T> {
  includes<S, R extends `${Extract<S, string>}`>(
    this: ReadonlyArray<R>,
    searchElement: S,
    fromIndex?: number
  ): searchElement is R & S;
}
```

```typescript
const varStr: string | number | object = 7;
if (["string", "number"].includes(typeof varStr)) {
  const foo = varStr; // foo is number, as expected
}
```

**Closed** 2023-06-21 01:34 UTC
Labels: Suggestion, Too Complex

**Comment by PieterjanDeClippel** [comment] 2024-06-23 10:35
How hard is this? Shouldn't tsc be able to simply transform an expression like

```
// This doesn't work
quality: 'low' | 'medium' | 'high' | number = 5;
if (['low', 'medium', 'high'].includes(quality)) {
   // It's a string
} else {
    // It's a number
}
```

to

```
// This works
if ((quality === 'low') || (quality === 'medium') || (quality === 'high')) {
}
```

Internally?

**Comment by RyanCavanaugh** [comment] 2024-06-24 20:58
That's not going to be a very common way to do things -- once you need it more that once, you'll move to the array to a local, and once it's not a literal, it's not sound to negatively narrow. You can legally write
```ts
const arr: ('low' | 'medium' | 'high')[] = [];
if (arr.includes(quality)) {
  // not hit, of course
} else {
  // 'quality' can be anything; cannot safely conclude it is number here
}
```

**Comment by Gin-Quin** [comment] 2025-04-07 08:11
I agree with @iansan5653 that the `includes` method should definitely have this typing:

```ts
interface Array<T> {
-    includes(searchElement: T, fromIndex?: number): boolean;
+    includes(searchElement: unknown, fromIndex?: number): searchElement is T;
}
```

There are many patterns where you need this.

Example 1: you have an constant array of strings and you want to test if a user message is part of this array.

```ts
let [userInput, setUserInput] = useState("")
const forbiddenInputs = ["danger", "warn"] as const

// the following line triggers a TS error
if (forbiddenInputs.includes(userInput)) {
  console.log("Forbidden!")
}
```

The most common workaround is to do this:

```
- if (forbiddenInputs.includes(userInput)) {
+ if (forbiddenInputs.includes(userInput as typeof forbiddenInputs[number])) {
```

But that's obviously not elegant code. You have to lie on the real type of the value just to shut the Typescript compiler.

Another workaround is to remove the `as const` in the array definition, but maybe you need this `as const` elsewhere, so that's not a solution.


Example 2: you have a value that is wider than the array.

```ts
type Foo = { foo: string }
type Bar = { bar: string }
type FooOrBar = Foo | Bar

const arrayOfFoos: Array<Foo> = [ ... ]

const fooOrBar: FooOrBar = ...

// we could a TS error as well
if (arrayOfFoos.includes(fooOrBar)) {
  ...
}
```

To solve this, once again we have to **lie on the type** and use a type assertion:

```ts
- if (arrayOfFoos.includes(fooOrBar)) {
+ if (arrayOfFoos.includes(fooOrBar as Foo)) {
```

---

I don't know how your typechecker internally works but that seems weird that this is "too complex to implement". You do narrowings in "if statements" already, so that's not a new concept to implement. And I could myself create the right signature and make it work with a utility function:

```ts
interface Array<T> {
-    includes(searchElement: T, fromIndex?: number): boolean;
+    includes(searchElement: unknown, fromIndex?: number): searchElement is T;
}
```

**Comment by RyanCavanaugh** [comment] 2025-04-07 17:23
@Gin-Quin 

> I agree with @iansan5653 that the includes method should definitely have this typing:

This typing is wrong and would lead to incorrect programs being accepted. This is addressed [earlier in the thread](https://github.com/microsoft/TypeScript/issues/36275#issuecomment-702233949)

> And I could myself create the right signature and make it work with an utility function:

It's not the right signature, though. That's the problem.
