### ISSUE TITLE
Go to definition doesn't work with ES modules using .mjs extension

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19119] opened 2017-10-11 22:45 UTC
_From @mfidemraizer on October 9, 2017 10:53_

- VSCode Version: 1.17
- OS Version: Any

Newer NodeJS versions including latest have broad native support to ES2015 and ES2017 and they already support ES modules. NodeJS team decided to support ES modules instead of CJS on files using the `.mjs` file extension.

Visual Studio Code currently won't be able to direct to symbol's definition using *Go to definition* when JavaScript code files are using `.mjs` extension.

Steps to Reproduce:

1. Rename a Node package source files to use the *.mjs file extension
2. Press F12 or click on *Go to definiton* in editor's context menu.

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#35892_

**Comment by mjbvz** [comment] 2017-10-11 22:46
Related to #10939 and possibly #18442

**Comment by mhegazy** [comment] 2017-10-11 23:20
I would say this is a duplicate of #18442. the issue is not just modules, .mjs has different semantics about importing modules and resolving them; we need to support the whole things not just the file extension. #18442 tracks that.

**Closed** 2017-10-11 23:20 UTC
Labels: Duplicate, VS Code Tracked

**Comment by NeskireDK** [comment] 2018-01-10 12:48
Still no love for this one.
