### ISSUE TITLE
Should not give suggestions when typing spread operator `...`.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#3350] opened 2015-06-02 22:38 UTC
```typescript
foo(./* expecting no suggestion */);
foo(../* expecting no suggestion */);
foo(.../* expecting suggestions */);

function foo(./* expecting no suggestion */) { }
function foo(../* expecting no suggestion */) { }
function foo(.../* expecting no suggestion */) { }
```

I think this is also related to a bug of Visual Studio Code:

![image](https://cloud.githubusercontent.com/assets/970430/7948920/2958e574-09bb-11e5-8e64-dad6593ea351.png)

**Comment by danquirk** [comment] 2015-06-02 22:44
Dupe of https://github.com/Microsoft/TypeScript/issues/3242

**Closed by danquirk** 2015-06-02 22:44 UTC
