### ISSUE TITLE
TypeScript - ability to move export to another file (refactoring)

### ISSUE THREAD

**Issue by timruffles** [Microsoft/TypeScript#10343] opened 2016-08-15 16:36 UTC
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Expected behavior:**

It'd be nice to be able to `Move export to file`, to quickly break down large sets of exports into focussed, smaller files.

**Comment by mhegazy** [comment] 2017-04-21 00:12
Duplicate of https://github.com/Microsoft/TypeScript/issues/6487

**Closed by mhegazy** 2017-04-21 00:12 UTC
Labels: Suggestion
