### ISSUE TITLE
don't support multiple constructors?

### ISSUE THREAD

**Issue by GerryLon** [Microsoft/TypeScript#16518] opened 2017-06-14 12:29 UTC
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
class Person {
    private name: string;

    constructor() {
        
    }

    constructor(name: string) {
        this.name = name;
    }
}
```

**Expected behavior:**
compile pass

**Actual behavior:**
error: Multiple constructor implementations are not allowed.

**Comment by ikatyang** [comment] 2017-06-14 13:09
Did you mean constructor overloads?
```ts
class Person {
    private name: string;

    constructor();
    constructor(name: string);
    constructor(name?: string) {
        this.name = name;
    }
}
```

---

Or what you mean is something just like C++ does? See https://github.com/Microsoft/TypeScript/issues/12041#issuecomment-272782978.

**Comment by GerryLon** [comment] 2017-06-22 02:45
I mean, Multiple constructor implementations, just like below: 
```ts
class Person {
    private name: string;

    constructor() {}

    constructor(name: string) {
        this.name = name;
    }
}
```
as you see, there are **two  implementations**

**Comment by ikatyang** [comment] 2017-06-22 02:50
I think multi-implementations should be duplicate of https://github.com/Microsoft/TypeScript/issues/12041.

**Comment by GerryLon** [comment] 2017-06-23 03:24
thank you!

**Closed** 2017-06-23 03:27 UTC
Labels: Question

**Comment by melodyJie** [comment] 2017-08-04 09:49
I don't know why the construct can't be more.
It's ok in JAVA or C++

**Comment by ikatyang** [comment] 2017-08-04 09:54
Because Javascript itself does not allow, and TS does not want to add more runtime behavior (see [TS design goal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals)).
