### ISSUE TITLE
as operator doesn't work correctly with CommonJS

### ISSUE THREAD

**Issue by oryol** [Microsoft/TypeScript#5245] opened 2015-10-13 19:08 UTC
I'm trying to use generic class in the TSX file and generic class is implemented in the another module. I have tried to use code like in the https://github.com/Microsoft/TypeScript/issues/3960#issuecomment-144529141 but it doesn't work because old style casting is not allowed in the TSX file. Ok, I have changed it to the ``as`` operator but it emits incorrect code. It refers to the generic class directly without using ``require``.

After that I have created simple example without JSX which demonstrates that old style casting and ``as`` operator are different.

File **generic.ts**: ``export default class Generic<T> {}``

File **sample.ts**:
```
import Generic from "./generic";
type Ctor = new() => Generic<number>;
const x = Generic as Ctor;
```

Compile ``tsc sample.ts --module commonjs``. Result:
```
var generic_1 = require("./generic");
var x = Generic;
```

As you see generic_1 variable isn't used at all and undeclared ``Generic`` variable is assigned to ``x``.

Workaround:
```
import Generic from "./generic";
type Ctor = new () => Generic<number>;
const x = Generic;
const y = x as Ctor;
```

Also please note that using old-style casting also helps:
```
import Generic from "./generic";
type Ctor = new() => Generic<number>;
const x = <Ctor>Generic;
```

So it looks like it is the problem in the ``as`` operator only.

**Comment by RyanCavanaugh** [comment] 2015-10-13 20:33
Duplicate of #4832

**Closed** 2015-10-13 20:33 UTC
Labels: Duplicate
