### ISSUE TITLE
Proposal: Support React.Native Platform Specific Code

### ISSUE THREAD

**Issue by alexpomsft** [Microsoft/TypeScript#17681] opened 2017-08-08 14:12 UTC
https://facebook.github.io/react-native/docs/platform-specific-code.html#platform-specific-extensions

React.Native's packager allows you to create multiple implementations of a module/file that are specific to target platforms.  During build/package time it will pick up the right file based on the target platform.  This is super useful.

TypeScript can play reasonably well with this by explicitly including all platform files during the build.  However, you lose type safety since TypeScript will only really build against one of the files.  For example:

```ts
// foo.ts
export const color = "red"
```

```ts
// foo.ios.ts
export const colour = "blue" // British spelling!
```

```ts
// bar.ts
import { color } from "foo"
```
This will compile correctly, but result in a runtime failure during an iOS execution.  It would be great if we could specify the target platform and have the module resolver use that when evaluating which file to load.

Thoughts?

**Comment by mhegazy** [comment] 2017-08-21 23:15
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/8328

**Comment by enginehenryed** [comment] 2017-08-25 15:21
@mhegazy #8328 has not been solved and this is a **LEGITIMATE** issue. Files with extensions such as `android.ts`, `ios.ts` are not understandably recognized by TS compiler, for example when they are referenced with relative path. 

And not only for React Native which promotes file extensions as such, if custom extensions support is added, allowing for example `file.test.ts`, the entire structure of any typescript could become ever more elegant. Workaround as [this](https://stackoverflow.com/a/43531355) is just so painful.

**Comment by mhegazy** [comment] 2017-08-29 23:47
I do not think there is a simple change that we can do to enable this scenario. The assumptions built on  the file extensions goes deep in the system, if we were to enable this scenario we will have to handle this in input files, module resolution, type checking, language service and output generation. again this is not a simple change and rewiring the whole compiler is not something we can take lightly. In https://github.com/Microsoft/TypeScript/issues/8328 i have outlined a few workarounds.

**Comment by mhegazy** [comment] 2017-09-14 16:47
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-14 16:47 UTC
Labels: Duplicate
