### ISSUE TITLE
Private fields in class declaration expose internal identifier in declarations

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#56145] opened 2023-10-18 12:56 UTC
### 🔎 Search Terms

class expressions private fields declaration

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAHjAvDYAbAhhCMDeBYAKBmJgGIBLAEyRgEYAGGAeiZgCIB9D0gZgBYArAIACFSmwBcMMAFcAtgCMApgCcA3DHJgYlJWnQr0UcuGyEAvkA)

### 💻 Code

```ts
const x = class {
    #id = 10 // "__#3455@#id": number; in declarations 
}
```

### 🙁 Actual behavior

The class expression is rendered in declarations as `declare const x: { new (): { "__#34@#id": number; }; }` exposing the internal identifier of the private field. 
 

### 🙂 Expected behavior

Since we can't emit `#private` in an object type (like for class declarations) and we don't have class types, it's hard to come up with a solution that preserves the nominal nature of the type. I see 3 possible solutions:

1. Remove the type from the field (at least the internally used type will not end up being exposed) `declare const x: { new (): { "__#34@#id": unknown ; }; }` (partial fix)
2. Remove the private fields and lose the nominal nature of the class
3. Remove the private fields and add a unique symbol that ensures the class behaves nominally (mostly)

```ts
declare const x_private: unique symbol;
declare const x: {
    new (): {
        [x_private]: "#private"
    };
}; 
```

Third option would be the ideal one IMO. There is precedent for adding 'fake' declarations in declaration emit (`_default` for default exports, `Name_Base` for  classes that use expressions in the heritage clause)

### Additional information about the issue

The numeric id is not stable, and can change based on what other private fields are seen before the one emitted in the declaration

```tsx
class C { #x = 1 } // Comment out this line id is different 
export  const x = class {
    #id = 10 // "__#3455@#id": number; in declarations 
}
```

[Playground Link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEDC0G9oGIAe0C80CM0C+0A9IXAPYC25ApgHYAu0pArg3QBYCWMIHNV0HACYCYgjgDNxVAE60GAWABQVVAAdS0htGCkaEBuiyhIMBEugWUQzDgAMREgCIA+s+QBmACwBWbwAFkIUcALmgaJnIAIxkAbgEaaEEqY2kwOg5dGCU8JSA)

(It is even worse in a language service, as the id changes each time you make a change anywhere in the file)

**Comment by MartinJohns** [comment] 2023-10-18 13:11
Duplicate of #36548. Used search terms: `private emit in:title`

**Closed** 2023-10-21 01:24 UTC
Labels: Duplicate
