### ISSUE TITLE
Cannot add methods when inheriting native Array class

### ISSUE THREAD

**Issue by cosmozhang1995** [Microsoft/TypeScript#18107] opened 2017-08-29 09:19 UTC
I want to create a class that inherits the native Array class (as its prototype). However, I found that the methods I append to the inherited class are missed when being compiled.

**TypeScript Version:**  2.4.2

**Code**

```ts
// This class inherits the native Array class
// and has its own method "getFirst"
class MyNewArray<T> extends Array<T> {
    getFirst() {
        return this[0];
    }
}

// Create a new "MyNewArray" instance
var myArray = new MyNewArray<string>();
myArray.push("First Element");
// Print the first element by calling its "getFirst" method
console.log("getFirst", myArray.getFirst()); // "First Element"
```

**Expected behavior:**
The code should print the first element of `myArray`, i.e., `"First Element"`

**Actual behavior:**
The code raised an exception, saying as following:
```
console.log("getFirst", myArray.getFirst()); // "First Element"
                                ^

TypeError: myArray.getFirst is not a function
    at Object.<anonymous> (/Users/cosmozhang/work/temp/t.js:23:33)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by kitsonk** [comment] 2017-08-29 09:32
Duplicate of #18035 (and many others)

Also covered in the FAQ [Why doesn't extending built ins like Error,
 Array, and Map work?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work)

Search is [your friend](https://github.com/Microsoft/TypeScript/search?q=extend+array&type=Issues&utf8=%E2%9C%93)!

**Comment by RyanCavanaugh** [comment] 2017-08-29 15:42
Should really just have a bot that detects the string "extends Array" in bug reports

**Closed by RyanCavanaugh** 2017-08-29 15:42 UTC
Labels: Duplicate
