### ISSUE TITLE
Generic type on class prevents access of protected entries with explicitly typed 'this' function argument

### ISSUE THREAD

**Issue by adekau** [microsoft/TypeScript#35067] opened 2019-11-12 21:52 UTC
**TypeScript Version:**  Tested on 3.2.4, 3.6.3, 3.8.0-dev.20191112

**Search Terms:** Property, protected, accessible, through, instance, generics, decorator

**Code**
```ts
class Accessor<T> {
    private _properties: { [key: string]: any } = {};

    constructor() { }

    protected _get(key: string): any {
        return this._properties[key];
    }

    protected _set(key: string, value: any): void {
        this._properties[key] = value;
    }
}

function property() {
    return function (target: any, key: string): void {
        const getter = function (this: Accessor<any>) { return this._get('something')}
    };
}
```

**Expected behavior:** Should allow access to protected function _get since this is typed as an instance of the class Accessor<T>.

**Actual behavior:** 
```ts
index.ts:17:69 - error TS2446: Property '_get' is protected and only accessible through an instance of class 'Accessor<any>'.

17         const getter = function (this: Accessor<any>) { return this._get('something')}
                                                                       ~~~~
```

**Note:** this does not occur without the generic type on Accessor. If it is just `class Accessor` with `function (this: Accessor)` there is no error on calling `this._get('something')`.

**Playground Link:** [Playground Link](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=2&pc=22#code/MYGwhgzhAECCzAKZQPYCcA8AVAfNA3gFDQnQAOaAlgG5gAui0A+hSmYmnZcgFwHQBtANaIAnnwh0qAOwDmAXT5hpo6AF9oAXgJqA3IWKlgKaZLQBXYHXQAKAJT81B0uTQoGVxABNmsxHRsRcWgzSjk7JRUCQxcSNH9zNGloOgALSggAOhY3dk5uCGExeX0XJxjXd0RPHyYIf0CxCSkw2QAaaFoQc0RI0QjOlEofIljSNIzs1jyuZCLReS1OsG7EUtIncoAzc2krShNKmdF7aJd4ukTknb2uQ5s6MDQ-Oj6OoOaZWQHqIZGKlzGUx0aAvBhoJY3fb3CYQPjwJCoTDKUQ4Bz4aAXK4pdJZJgvGwAcggKAAtv50nJCXYnGVCGogA)

**Related Issues:** #10302, Potentially a duplicate of #29132. This was supposedly fixed in #24645 however it is problematic with generics as mentioned above.

**Comment by andrewbranch** [comment] 2019-12-17 00:14
This is a better description of the problem, but it is indeed a duplicate of #24645.

**Closed** 2019-12-19 18:00 UTC
Labels: Duplicate
