### ISSUE TITLE
Typed error handling

### ISSUE THREAD

**Issue by lucasteles** [microsoft/TypeScript#55639] opened 2023-09-05 19:50 UTC
### 🔍 Search Terms

"thows", "typed error handling", "strict error"

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Would be great to have a way to define the type of error(s) a function or method can throw

### 📃 Motivating Example

*Safer error handling and dev experience on exceptions*

Type-safe error handling would improve the code experience, giving faster feedback on which kind of exception is possible or even with a `catch` error type inference.

### 💻 Use Cases

1. What do you want to use this for?

basic throw annotation:
```ts
class MyCustomError extends Error {
  constructor(msg: string, public code: number) {
    super(msg)
    this.name = MyCustomError.name
  }
}

function failableFn(code: number): number throw MyCustomError { // <- here
    if (code < 0)
      throw new MyCustomError('Bad code!', code)
    return code
}

function doStuff(code: number) {
    try{
      console.log('Code: ', failableFn(code))
    }
    catch (ex) { // inferred as MyCustomError
      console.log(`Failure for ${code}: ${ex.message}`)
    }
}
console.log(doStuff(1)) // Code: 1
console.log(doStuff(-1)) // "Failure for -1: Bad code!" 
```
I think ideally the `throw` could even be optional, as I believe the compile could infer the `throw` types in the function body.

3. What shortcomings exist with current approaches?

Feels like a hole in the _possible_ very strict type check philosophy of TypeScript

5. What workarounds are you using in the meantime?

We have to manually type check the exception or weak type it 

```ts
function failableFn(code: number): number {
    if (code < 0)
      throw new MyCustomError('Bad code!', code)
    return code
}

function doStuff(code: number) {
    try{
      console.log('Code: ', failableFn(code))
    }
    catch (ex) { // unknown
      if (ex instanceof MyCustomError)
          console.log(`Failure for ${code}: ${ex.message}`)
      else
         console.error(`other? `, ex)
    }
}
```

**Comment by MartinJohns** [comment] 2023-09-05 20:04
Duplicate of https://github.com/microsoft/TypeScript/issues/23060 / https://github.com/microsoft/TypeScript/issues/13219 and others.

The last time it was suggested... two days ago: #55614.

**Closed** 2023-09-09 01:23 UTC
Labels: Duplicate
