### ISSUE TITLE
Suggestion︱Class﹣Property Assertion Detection from Methods in Constructor

### ISSUE THREAD

**Issue by Malix-Off** [microsoft/TypeScript#53630] opened 2023-04-02 14:49 UTC
# Suggestion

## 🔍 Search Terms

- Class
- Property
- Assertion
- Detection
- Type
- Check
- Methods
- Constructor

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

In Classes, add Property Assertion Detection from Methods in Constructor Classes

## 🧪 Exemple
```ts
class Car {
	
	name: string;

	constructor() {
		this.setName();
	}

	setName() {
		this.name = "famousBrand famousModel";
	}

}
```
Produces:
```txt
Property 'name' has no initializer and is not definitely assigned in the constructor.ts(2564)
```
![image](https://user-images.githubusercontent.com/76160668/229360311-376b6e57-5230-4461-8c68-04162a3cbbca.png)

## 💻 Workaround

Use definite assignment assertion (`!` after the propriety name)

**Comment by fatcerberus** [comment] 2023-04-02 15:08
Duplicate of #21132.  Also worth considering: https://github.com/microsoft/TypeScript/issues/50643#issuecomment-1237553642

**Closed** 2023-04-02 15:20 UTC
Labels: Duplicate

**Comment by Malix-Off** [comment] 2023-05-28 10:10
This issue can be deleted
