### ISSUE TITLE
Suggestion: Quick Fix for import taking file names into account 

### ISSUE THREAD

**Issue by olmobrutall** [Microsoft/TypeScript#17052] opened 2017-07-10 12:27 UTC
The new import Quick Fix is great when importing exporting symbols.

```TS
import { Panel, FormGroup } from 'react-bootstrap';
```

but some modules are meant to be imported completely, like: 

```TS
import * as React from "react"
``` 
or the module export one default component: 

```TS
import MyComponent from './MyComponent';
```

The second and the third scenario are currently not covered, since they typically depend on the name of the file and not on the exported symbols, and is just a convention on the client code to use the same name. 

Still, I think the convention is well extended and reasonable enough to be included in the suggestions of the Quick Fix.

So, if an identifier X is not bound, consider if there are file with name 'X.ts/.d.ts/.tsx' (case insensitive), if there are, use

 ```TS
import * as X from "./X.ts" //no default export
import X from "./X.ts"  //default export
```

Thanks for the great work!

**Comment by mhegazy** [comment] 2017-08-24 19:14
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/14663

**Comment by mhegazy** [comment] 2017-09-08 16:56
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-08 16:56 UTC
Labels: Duplicate
