### ISSUE TITLE
Unable to import JSX types, Error: "no interface JSX.IntrinsicElements exists", although it exists

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#47072] opened 2021-12-08 22:44 UTC
**TypeScript Version:**  4.5.2

**Search Terms:**

no interface JSX.IntrinsicElements exists

**Code**

```js
import type {JSX} from 'solid-js'

type test = JSX.IntrinsicElements // <-- no error, the type exists.

const d = <div /> // Error: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
```

[playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnA3gKQMoA0C+cAZlBCHAOQDOEANsACYC0AVlRQLABQ3SqCKKvAC8cHLgB0ASQB2MKMBlVgAYwCitFCBRyqcAPT64AHiZM4MiHBRRSUADQIAFmnEJkaFAA9gQqhO5uFQgleAY4UWMGYAA3AwA+AyM1W2gALjE8a01tOThQMHoVYBhaRDgnAEM9PjQKSplECjgAIxQVSoBXKjRLfLkbIkqVOvFpOQUlVQ0tHRh2ax8-CSA)

**Expected behavior:**

It should see the definition of `JSX.IntrinsicElements` which is present due to the `import` statement.

**Actual behavior:**

"no interface JSX.IntrinsicElements exists"

**Comment by weswigham** [comment] 2021-12-09 21:00
I explained this to you in the other issue with mostly the same premise you commented in; we don't look for a local name JSX, only a global one, nor do we document doing so anywhere, nor do we want to add a 3rd way to find JSX definitions, beyond the global method (which is around for legacy reasons), and the factory-local method (which works for any library which defines a JSX namespace under their factory function).

**Comment by weswigham** [comment] 2021-12-09 21:09
Yeah, this is a dupe of #41813.

**Closed by weswigham** 2021-12-09 21:09 UTC
Labels: Working as Intended

**Comment by trusktr** [comment] 2021-12-10 01:07
@weswigham I also previously explained all the issues, summarized here:

- This goes against developer intuition: devs expect that `import`ing something makes it visible.
- tools relying on static analysis of `import` statements are built around `import` syntax, not around non-standard `@jsxImportSource` syntax.
  - VS Code's `Go To Definition` has no idea what to do with `@jsxImportSource` syntax, despite being powered by TypeScript.
    ![Screenshot 2021-12-09 163646](https://user-images.githubusercontent.com/297678/145497495-b0b46216-7ef2-4552-a764-879fc3ef8afc.png)
    ![Screenshot 2021-12-09 163716](https://user-images.githubusercontent.com/297678/145497496-4e9efa30-2364-4e98-8ce5-04120dc4d845.png)
- Using the `@jsxImportSource` syntax to import JSX.... doesn't work:
  ![Screenshot 2021-12-09 164414](https://user-images.githubusercontent.com/297678/145498268-20674c59-828c-4c97-88cc-d73499edcad7.png)
- TS playground even gets bugged out:
  ![Screenshot 2021-12-09 170305](https://user-images.githubusercontent.com/297678/145499730-cd419e00-67d0-44cb-8155-5d27cd07c0d7.png)
- Or worse yet, if a global type package like `@types/react` is in place, the _**wrong**_ `JSX` type will be used on accident. Even if `@jsxImportSource solid-js` is used at the top of a file, running `Go To Definition` on `JSX` in that previous example,
  ![Screenshot 2021-12-09 164856](https://user-images.githubusercontent.com/297678/145498514-ba1de98b-631d-44ce-a820-1c654f127100.png)
  will take you to this,
  ![Screenshot 2021-12-09 165050](https://user-images.githubusercontent.com/297678/145498617-297bd7da-9c4c-47a5-b525-cffd9f6d4f7c.png)
  which is going to make things confusing.
- To get around this issue, we have to import JSX _twice:_
  ```tsx
  /* @jsxImportSource solid-js */
  import {JSX} from 'solid-js'

  type test = JSX.IntrinsicElements

  function Foo() {
      return <div />
  }
  ```
  ([playground](https://www.typescriptlang.org/play?#code/PQKgBAAgVgzgHgSQLYAcD2AnALgZTQVwwGMBTMGNAGwEsATAWljBGAFgAoa1TLMAbwBSOABoBfMADMMaJGADkFGg1hyOHLAE8UZLCRi8AvGCHCAdAgB2WDNQsxqRAKKUSSElZhr2E-BaJZqNAswADE0NAAKAEp+DjB4sAwSLEJggB5aagA3MGAAPg5RDiA))


This is simply problematic, and I'd place bets on standard `import` syntax solving these issues.

**Comment by weswigham** [comment] 2021-12-10 05:02
The JSX namespace of a package should never be the place you go to to find types for it - they're an ugly implementation detail to tell the compiler how JSX works for them - there's a reason all the entries in the react JSX namespace that can be are pointers to other types outside the JSX namespace.

Hell, part of the reason we _don't_ let a local JSX name interfere with jsx resolution is so those ugly implemention details don't interfere with working with normal stuff, so you can still use the name "JSX" in code and not have it break your JSX!

**Comment by trusktr** [comment] 2021-12-10 22:22
I can't make much sense of that reasoning. If someone write `import JSX from 'whever'`, then obviously they can't make an additional identifier of the same name within scope (apart from performing type augmentation). This is fully expected from ES Modules; no one is going to have an issue with that.

**Comment by ryansolid** [comment] 2021-12-22 23:23
I find it amusing this got closed as a duplicate when @trusktr was specifically instructed in the other issue to make this as a new issue. It's clear there is no interest by maintainers to address this, which your prerogative but it does seem like there are gaps in the current implementation with no solution in sight. I'm sure there are good reasons not to address this. Might be good to at least talk to that.

**Comment by weswigham** [comment] 2021-12-23 04:17
He was asked for a concrete proposal - repeating the same bug report as the other OP makes it a pretty clear duplicate, since this is a "bug" report that is, in fact, "working as intended" as written. Unless you wanna propose a new behavior (which I've already said (in both issues) why _I_ don't support the new behavior he'd probably want to propose) with the "feature request" template and actually write out why someone would want JSX to work in this new way (in detail), what advantages it offers and disadvantages vs current mechanisms for the same, and the details of how it should actually work alongside existing behavior without breaking code in the wild, because what's being alluded to is definitely a _new_ feature. One I obviously don't support, as my comments should make clear, so I won't make such a proposal myself, but hey, if you make a compelling proposal and change other team members hearts and minds (or mine) I can't stop you~
