### ISSUE TITLE
Array‘s includes and indexOf parameters whether is any more suitable

### ISSUE THREAD

**Issue by 1587315093** [microsoft/TypeScript#55090] opened 2023-07-20 11:34 UTC
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
const test1 = [123].includes("456")
const test2 = [true].includes(123)
```

### 🙁 Actual behavior
Argument of type 'string' is not assignable to parameter of type 'number'.
![image](https://github.com/microsoft/TypeScript/assets/77056991/3f694588-45bd-4128-bd7e-a1c5656c7fcf)
### 🙂 Expected behavior

I think includes should accept any type, after all it is a judgment function

![image](https://github.com/microsoft/TypeScript/assets/77056991/96e7bc9e-58aa-41bb-8ae2-479761360217)

**Comment by MartinJohns** [comment] 2023-07-20 11:43
Duplicate of #14520.

**Comment by fatcerberus** [comment] 2023-07-20 13:20
For the record: proposals to re-type the parameter to `any` (in lieu of #14520) have been outright rejected in the past on the grounds that it should be an error if, e.g., you check whether `string[]` contains a number.

**Comment by 1587315093** [comment] 2023-07-21 11:18
> For the record: proposals to re-type the parameter to `any` (in lieu of #14520) have been outright rejected in the past on the grounds that it should be an error if, e.g., you check whether `string[]` contains a number.

But it feels a bit inflexible. When I use [null, undefined]. includes (value) to detect whether an external source's value is null and undefined, a prompt will appear. shouldn't the judgment of includes be more flexible

**Comment by RyanCavanaugh** [comment] 2023-07-21 17:02
You're totally free to add the `any` overload to your project if that's the behavior you'd prefer.

**Closed by RyanCavanaugh** 2023-07-21 17:02 UTC
Labels: Duplicate
