### ISSUE TITLE
Suggestion to prevent infinite accessor loops at compile time

### ISSUE THREAD

**Issue by OceansFourteenth** [Microsoft/TypeScript#20921] opened 2017-12-28 17:47 UTC
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**
Person.ts (Produces `RangeError`)
```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
export class Person {
  private _name: string;

  get name(): string {
    return this.name; // Code producing recursive call, should be `return this._name;`
  }

  set name(name: string) {
    this.name = name; // Also compiles but should be `this._name = name`
  }
}
```

Person.ts (No errors)
```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
export class Person {
  private _name: string;

  get name(): string {
    return this._name;
  }

  set name(name: string) {
    this._name = name;
  }
}
```

**Actual behavior:**
Code compiles without errors or warnings but throws `RangeError: Maximum call stack size exceeded` on runtime.

**Suggested behavior:**
Compiler should recognize accessors being called within their own bodies, potentially creating a recursive loop. Suggest an error or warning at compile-time as the mistake is a very easy one to make. In this case, the omission of an underscore.

**Comment by SalathielGenese** [comment] 2017-12-28 18:07
The [Proposal Guide](https://github.com/Microsoft/TypeScript-wiki/blob/master/Writing-Good-Design-Proposals.md) says we should think of the impact on the compiler. I hope the compile will not struggle to see the this mutator is being called within himself, thus creating and infinite loop at runtime.

**Comment by ajafff** [comment] 2017-12-28 19:11
I have written a custom TSLint rule to warn about accessor recursion: https://github.com/ajafff/tslint-consistent-codestyle/blob/master/docs/no-accessor-recursion.md

**Comment by DanielRosenwasser** [comment] 2017-12-28 23:58
Duplicate of #3407, duplicate of #14708.

**Closed** 2018-01-12 19:50 UTC
Labels: Duplicate
