### ISSUE TITLE
Slow code completion when using material ui

### ISSUE THREAD

**Issue by li1234yun** [microsoft/TypeScript#48122] opened 2022-02-05 13:15 UTC
When I use VSCode to write Python/Go language, the completion is fine. When I use it to write `nextjs` application, it's completion is slow, maybe I miss some plugins. I hope to improve the ts-language-server preformance, maybe only my problem.

Webstorm completion is very fine, maybe can refer it.

Thank you for excellent editor!

### VSCode Version Info

Version: 1.64.0
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:20:17.224Z (2 days ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0

### VSCode Plugin Info

alefragnani.Bookmarks
anweber.vscode-httpyac
bierner.markdown-mermaid
bierner.markdown-preview-github-styles
bradlc.vscode-tailwindcss
cweijan.vscode-database-client2
DavidAnson.vscode-markdownlint
dbaeumer.vscode-eslint
Dunn.redis
eamodio.gitlens
esbenp.prettier-vscode
GitHub.copilot
golang.go
GraphQL.vscode-graphql
Gruntfuggly.todo-tree
jock.svg
johnsoncodehk.volar
LeetCode.vscode-leetcode
mathematic.vscode-pdf
mongodb.mongodb-vscode
ms-azuretools.vscode-dapr
ms-azuretools.vscode-docker
ms-kubernetes-tools.vscode-kubernetes-tools
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-wsl
ms-vscode-remote.vscode-remote-extensionpack
msjsdiag.vscode-react-native
redhat.vscode-yaml
streetsidesoftware.code-spell-checker
tamasfe.even-better-toml
tsandall.opa
usernamehw.errorlens
VisualStudioExptTeam.intellicode-api-usage-examples
VisualStudioExptTeam.vscodeintellicode
vscode-icons-team.vscode-icons
vscodevim.vim
yzhang.markdown-all-in-one
zxh404.vscode-proto3

**Comment by mjbvz** [comment] 2022-03-04 21:46
Thanks for the additional info. This seems like a duplicate of:

- #43717
- #47793
- https://github.com/mui/material-ui/issues/19113

Moving upstream so the TS team is aware of the problem

**Comment by RyanCavanaugh** [comment] 2022-03-04 21:49
Duplicate #34801

**Closed** 2022-03-07 18:00 UTC
Labels: Duplicate
