### ISSUE TITLE
certificate expired for  https://www.typescriptlang.org/ 

### ISSUE THREAD

**Issue by Alexander-Taran** [Microsoft/TypeScript#22671] opened 2018-03-17 12:10 UTC
Ignoring the template, sorry.
Can close straight away after acknowledgement.

First attempt to report the issue here lead me to gitter channel  https://gitter.im/Microsoft/TypeScript?at=5aac57f227c509a7747000dc
![image](https://user-images.githubusercontent.com/1029452/37555231-44610f38-29f5-11e8-8e66-6f58c1b49e61.png)

Didn't know who to mention to get attention.

**Comment by j-oliveras** [comment] 2018-03-17 13:26
Duplicate of #22663.

**Closed** 2018-03-17 13:34 UTC
