### ISSUE TITLE
TSServer High CPU usage

### ISSUE THREAD

**Issue by kasik96** [microsoft/TypeScript#31248] opened 2019-03-21 10:24 UTC
- VSCode Version: 1.32.3
- OS Version: Fedora 29 

Steps to Reproduce:

1. Install clean stable VSCode with neo extensions or setting
2. Open large project with sub projects
3. Check System Monitor -> HIGH CPU Usage, almost non usable OS

I tried to turn off some settings, but nothing help.
It caused by TSServer.js build-in "TypeScript and JavaScript Language Features" extension.

Solution: Disable "TypeScript and JavaScript Language Features" build-in extensions.

![Screenshot from 2019-03-21 11-18-59](https://user-images.githubusercontent.com/7235992/54746201-d7a6fc00-4bcb-11e9-8786-899c9e974a3e.png)
![Screenshot from 2019-03-21 11-19-27](https://user-images.githubusercontent.com/7235992/54746202-d7a6fc00-4bcb-11e9-81e1-975e4d673091.png)
![Screenshot from 2019-03-21 11-19-56](https://user-images.githubusercontent.com/7235992/54746203-d7a6fc00-4bcb-11e9-9bd3-40345783019d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-05-04 03:31
Moving this upstream as I don't see anything that stands out in those logs.

Can you please try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions) just to make sure this hasn't already been fixed

**Comment by kasik96** [comment] 2019-05-05 19:49
@mjbvz Same problem, did not help.

**Comment by Mozar10** [comment] 2019-05-06 02:53
I have tried pretty much every solution listed here and in other gh issues. Have tried removing extensions, upgrading TS, etc.. and I'd really hate to switch to atom. Is there any fix for this? Pretty sure it's limited to linux os

**Comment by brokenalarms** [comment] 2019-05-06 18:06
no @Mozar10, this is happening for me on MacOS as well.

**Comment by sheetalkamat** [comment] 2019-05-06 19:17
@kasik96 From your shared log it seems like file watcher being invoked too many times and is suppose to be a file not found.. Enabling `--traceResolution` might give you why this file is being requested. It seems like that location is directory in the package and not file.

```
Info 179  [20:40:57.774] FileWatcher:: Triggered with /home/jsdev/Work/hidden-clients-js/node_modules/socks/typings 0:: WatchInfo: /home/jsdev/Work/hidden-clients-js/node_modules/socks/typings 500 Project: /dev/null/inferredProject1* WatchType: Missing file

Info 180  [20:40:57.774] FileWatcher:: Close:: WatchInfo: /home/jsdev/Work/hidden-clients-js/node_modules/socks/typings 500 Project: /dev/null/inferredProject1* WatchType: Missing file
```

**Comment by whitecolor** [comment] 2019-05-10 13:31
It happens very often (several times during a day) to me with my medium size projects, tsserver (eletron_node tsserver.js) stats to eat 30%-70% CPU on any currently active file in the editor (I see it in vscode's Process Explorer).

When I restart vscode it working fine on the same files, sometime later it begins again. It really hard to believe that there is something "wrong" with the app's TS code.

**Comment by whitecolor** [comment] 2019-05-11 16:05
BTW in my case I have a strong suspicion that is was caused by typescript-tslint-plugin, tracelog was full of messages regarding it, and have removed it from tsconfig for a while. The problem didn't show again yet.

**Comment by SeedyROM** [comment] 2019-05-12 11:55
Just downgrade your [version](https://code.visualstudio.com/updates/v1_32), the last update doesn't have anything that's actually's worth upgrading for if this bug is affecting you. Wait till they figure it out guys! 
 
@Mozar10 You don't need to go to Atom, just download the last release [here](https://code.visualstudio.com/updates/v1_32)!

**Comment by Mozar10** [comment] 2019-05-12 20:46
@SeedyROM Thanks for the tip. That didn't cross my mind and so far so good :+1:

**Comment by whitecolor** [comment] 2019-06-10 13:18
I have downgraded to vscode 1.32 but the problem is the same

**Comment by sheetalkamat** [comment] 2019-07-25 22:40
@kasik96 Have you tried investigating this further as per my comment at https://github.com/microsoft/TypeScript/issues/31248#issuecomment-489741278 
This seems more like a configuration issue rather than actual tsserver issue.

**Comment by graupe** [comment] 2019-09-02 15:44
I had the same issue when opening files in larger typescript projects. I would say it's a bug at some level, but I could make it go away by using `sudo sysctl fs.inotify.max_user_watches=524288 ` on my Linux system. Hope this helps someone.

**Comment by cushmatt** [comment] 2019-10-10 14:48
This just started happening to me out of the blue in DeepinOS but I just switched a couple days ago so I'm not sure if I hadn't been paying attention and it was doing it all along.  Extremely frustrating as my laptops fans start going full speed and typescript's intellisense takes forever to load instead of the instantaneous feedback I'm used to.

Going into htop shows usally all CPUs having an increase in usage with one of them at 99%.
Looking at my processes, there are literally TONS of the same tsserver popping up like my processes are being flooded with multiples of the same process.

I first noticed this yesterday when I tried to run Gatsby and it errored out saying I had too many file watchers.  I have also tried every solution I could find and even upgraded from I believe 1.31 to 1.39 and that didn't work so finally decided to post here.  I haven't enabled verbose logging and looked at the logs yet so I'll do that now and report back. 

Makes me so sad :(.  I love VSCode too much for this to ruin my experience but there's no way I can handle my laptop sounding like a turbine and my intellisense taking 5-10 seconds to load while I type.

As an aside, this only starts happening when I start typing.

**Comment by cushmatt** [comment] 2019-10-10 15:00
Alright, I attached my tsserver log.  I REALLY hope this helps.  I literally turned on verbose logging, exited VSCode, re-opened VSCode, typed a couple characters in a .tsx file and everything spiked.  So this is like a log of a minute of time frame and I hope it helps point down the issue.
[tsserver_log.txt](https://github.com/microsoft/TypeScript/files/3713200/tsserver_log.txt)

**Comment by mordka** [comment] 2019-12-17 04:00
Same problem in WebStorm https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003579280-IntelliJ-node-processes-using-a-lot-of-CPU-on-TypeScript-project-IntelliJ-performance-suffers-?flash_digest=13598a0eb3a2ffbcf8004d50e974872587e71957

Disabling tsserver in WebStorm fixes the excessive CPU usage

**Comment by viljamis** [comment] 2019-12-21 22:39
Have been facing this exact issue as well on the latest macOS for the past few weeks and haven’t been able to solve it.

**Comment by sheetalkamat** [comment] 2020-01-30 20:10
@cushmatt can you please try typescript@next to see if the issue still repros.. We made some changes to directory watching for Linux and it might have fixed the issue with the files being watched..

**Comment by puppeteer701** [comment] 2021-04-22 10:41
I am still experiencing this issue with VSCode Insider and typescript@next.

**Comment by mjbvz** [comment] 2021-04-23 23:30
@puppeteer701  Please open a new issue with information about your project

Closing this since we cannot investigate this without more info from the original poster

**Closed by mjbvz** 2021-04-23 23:30 UTC
Labels: Domain: Performance, Needs More Info

**Comment by fenvalle** [comment] 2023-03-05 18:19
https://github.com/microsoft/TypeScript/issues/52876

To investigate: Git commands (like checking diff) are causing ts server to rebuild files, maybe there is a chance of this being related to the cause of this issue
Could someone check if ts server with cpu usage without git still have spikes in cpu usage?
