### ISSUE TITLE
vs code, auto import error

### ISSUE THREAD

**Issue by zen1tex** [Microsoft/TypeScript#21250] opened 2018-01-18 01:45 UTC
**TypeScript Version:**  2.6.2
**Angular:**  2+
**OS**  win10
**vs code:** 1.19.2

**This error still exists!!**

When working with files that I created - no errors, but it should be used when you need to combine nothing works.

**Expected behavior:**

```ts
import { Component, OnInit, Input, Output, EventEmitter, ViewEncapsulation } from '@angular/core';

@Component({
  ...
  encapsulation: ViewEncapsulation.Emulated
})
```

**Actual behavior:**
```ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { ViewEncapsulation } from '@angular/compiler/src/core';

@Component({
  ...
  encapsulation: ViewEncapsulation.Emulated
})
```
Such errors are not limited to the connection of this package

**Comment by DanielRosenwasser** [comment] 2018-01-18 06:13
Looks like a duplicate of #19694, should be fixed in TypeScript 2.7 RC.

**Comment by zen1tex** [comment] 2018-01-18 10:12
updated to 2.7, the problem remains, maybe the fix will be later(

**Comment by Cfrany** [comment] 2018-01-18 10:29
Not sure if you guys knew this, but a little while ago tonight, I realized one of your fellow Githubsters has been f****** with me, malicious harassment and hacking, Identity theft; she had remotely downloaded some super nasty keylogging malware on my MacBook Air, installing Windows software and Kaspersky.  She then went on to sell my info on the darkweb, so people all over the world have my identity.  She or one of her cohorts have started a business online, setting me up for all the tax liability.  THis malware webkit makes it look like everything is coming from my IP, so she seems to be setting me up for some criminal activity.  I am using a little Pixel Book that I just bought; but one of them has hacked into my new iphone after I set up ALL the security you can imagine-except for the little Fido keys.  I had that Mac wiped to Network Settings NINE times-right now it's at the Geeksquad in Tukwila, and I never want to see it again.
I notice that Apple is the only company not represented here.  Grrr.   
AND I feel so badly about the amount of time you all have spent; as soon as I get this device clean..$$$ is coming your way.

**Closed** 2018-02-01 20:48 UTC
Labels: Duplicate
