### ISSUE TITLE
Can not build TypeScript: Duplicate identifier 'CompileStream'.

### ISSUE THREAD

**Issue by kpreisser** [Microsoft/TypeScript#11121] opened 2016-09-24 09:10 UTC
Hi,
when I tried to build TypeScript today on a fresh Windows 10 x64 Version 1607 machine with Node.js 6.6.0, using the current master branch (95c3eccbe9f3f7e1857ce157d437e6b80b3c9c6f), using the commands as specified in the readme:
```
git clone https://github.com/Microsoft/TypeScript.git
cd TypeScript
npm install -g gulp
npm install
gulp local
```
I am getting the following error:
```
C:\Users\VPC\Desktop\TypeScriptOrg\TypeScript>gulp local
[11:02:25] Requiring external module ts-node/register

C:\Users\VPC\Desktop\TypeScriptOrg\TypeScript\node_modules\ts-node\src\index.ts:253
          throw new TSError(diagnosticList)
                ^
TSError: ⨯ Unable to compile TypeScript
gulpfile.ts (20,15): Duplicate identifier 'CompileStream'. (2300)
    at getOutput (C:\Users\VPC\Desktop\TypeScriptOrg\TypeScript\node_modules\ts-node\src\index.ts:253:17)
    at C:\Users\VPC\Desktop\TypeScriptOrg\TypeScript\node_modules\ts-node\src\index.ts:263:16
    at Object.compile (C:\Users\VPC\Desktop\TypeScriptOrg\TypeScript\node_modules\ts-node\src\index.ts:398:17)
    at Module.m._compile (C:\Users\VPC\Desktop\TypeScriptOrg\TypeScript\node_modules\ts-node\src\index.ts:299:46)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\VPC\Desktop\TypeScriptOrg\TypeScript\node_modules\ts-node\src\index.ts:302:14)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
```

Note: gulpfile.ts contains the following declaration at line 20:
```ts
interface CompileStream extends NodeJS.ReadWriteStream { } // Either gulp or gulp-typescript has some odd typings which don't reflect reality, making this required
```

If I comment that line out, some files are built, but then I get another error:
```
[11:07:55] Starting 'built\local\diagnosticMessages.generated.json'...
[11:07:55] Finished 'built\local\diagnosticMessages.generated.json' after 972 μs
[11:08:04] Finished 'built\local\typescriptServices.js' after 8.48 s
[11:08:04] Starting 'built\local\tsc.js'...
[11:08:04] 'built\local\tsc.js' errored after 2.64 ms
[11:08:04] Error: Cannot find module './built/local/typescript.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    (...)
```

However the build (with the original gulpfile.ts) worked some days ago. Do you have any ideas?

Thanks!

**Comment by johanssj** [comment] 2016-09-24 09:44
Confirming exactly the same happening for me which is why I'm looking here at recent issues to see if anyone else has just reported ditto.
tsc --version
Version 2.1.0-dev.20160924

**Comment by andimarek** [comment] 2016-09-25 06:38
This seems to be happening because of a new release of`gulp-typescript` (3.0.0, 2 days ago). When I change the dependency from `latest` to `2.14.1` it works for me.

**Comment by Istar-Eldritch** [comment] 2016-09-29 18:42
Looks like gulp-typescript is now added the proper type definitions making the interface CopileStream no longer required: https://github.com/Microsoft/TypeScript/blob/master/Gulpfile.ts#L20

**Comment by johanssj** [comment] 2016-09-30 06:11
Confirming that commenting out line 20 of Gulpfile.tst gets past the CompileStream DuplicateIdentifier error previously reported. However now we get another error, exactly as reported by @kpreisser above, so **the latest and greatest release still does not build as at September 30, 2016** 6 days after this issue was opened.

Unfortunately this territory is too unfamiliar for me to offer a diagnosis and a fix.  It just means that I cannot work on other open issues that I was going to have a crack at.


```
node scripts/processDiagnosticMessages.js src/compiler/diagnosticMessages.json
[15:29:30] Finished 'built/local/lib.dom.d.ts' after 4.02 s
[15:29:30] Finished 'built/local/lib.dom.iterable.d.ts' after 4 s
[15:29:30] Finished 'built/local/lib.webworker.d.ts' after 4 s
[15:29:30] Finished 'built/local/lib.scripthost.d.ts' after 4 s
[15:29:30] Finished 'built/local/lib.es5.d.ts' after 3.99 s
[15:29:30] Finished 'built/local/lib.es2015.d.ts' after 3.99 s
[15:29:30] Finished 'built/local/lib.es2016.d.ts' after 3.99 s
[15:29:30] Finished 'built/local/lib.es2017.d.ts' after 3.99 s
[15:29:30] Finished 'built/local/lib.es2015.core.d.ts' after 3.98 s
[15:29:30] Finished 'built/local/lib.es2015.collection.d.ts' after 3.97 s
[15:29:30] Finished 'built/local/lib.es2015.generator.d.ts' after 3.97 s
[15:29:30] Finished 'built/local/lib.es2015.iterable.d.ts' after 3.97 s
[15:29:30] Finished 'built/local/lib.es2015.promise.d.ts' after 3.97 s
[15:29:30] Finished 'built/local/lib.es2015.proxy.d.ts' after 3.96 s
[15:29:30] Finished 'built/local/lib.es2015.reflect.d.ts' after 3.96 s
[15:29:30] Finished 'built/local/lib.es2015.symbol.d.ts' after 3.96 s
[15:29:30] Finished 'built/local/lib.es2015.symbol.wellknown.d.ts' after 3.96 s
[15:29:30] Finished 'built/local/lib.es2016.array.include.d.ts' after 3.96 s
[15:29:30] Finished 'built/local/lib.es2017.object.d.ts' after 3.96 s
[15:29:30] Finished 'built/local/lib.es2017.sharedmemory.d.ts' after 3.96 s
[15:29:30] Finished 'built/local/lib.d.ts' after 4 s
[15:29:30] Finished 'built/local/lib.es6.d.ts' after 4 s
[15:29:30] Starting 'lib'...
[15:29:30] Finished 'lib' after 12 μs
[15:29:30] Finished 'src/compiler/diagnosticInformationMap.generated.ts' after 235 ms
[15:29:30] Starting 'generate-diagnostics'...
[15:29:30] Finished 'generate-diagnostics' after 5.39 μs
[15:29:30] Starting 'built/local/typescriptServices.js'...
gulp-typescript: ts(tsProject) has been deprecated - use .pipe(tsProject(reporter)) instead
  As of gulp-typescript 3.0, .pipe(ts(tsProject)) should be written as .pipe(tsProject()).
  More information: http://dev.ivogabe.com/gulp-typescript-3/
[15:29:30] Starting 'built/local/diagnosticMessages.generated.json'...
[15:29:30] Finished 'built/local/diagnosticMessages.generated.json' after 351 μs
[15:29:48] Finished 'built/local/typescriptServices.js' after 18 s
[15:29:48] Starting 'built/local/tsc.js'...
[15:29:48] 'built/local/tsc.js' errored after 723 μs
[15:29:48] Error: Cannot find module './built/local/typescript.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)

```

**Comment by vilic** [comment] 2016-09-30 06:19
@mhegazy Any comment?

**Comment by Istar-Eldritch** [comment] 2016-09-30 07:22
So the deprecation warning are there and should be fixed. Nevertheless the compilation works for me in a clean environment. I tried the current master branch and release-2.0.5

Try running it in a docker container:
```bash
docker run --name ts -v /home/istar/workspace/personal/TypeScript:/app -w /app --rm node /bin/sh -c "npm i && node node_modules/gulp/bin/gulp.js local"
```

**Comment by johanssj** [comment] 2016-09-30 08:33
Just freshly installed node, npm, typescript@next + deleted ~/.npm cache. I cannot see node-js-wise that my system could be cleaner to warrant installing docker & running in that.

Now, and to be sure we are using the gulp that the ts package.json demands:

```
> node --version
v6.7.0

> npm --version
3.10.8

> tsc --version
Version 2.1.0-dev.20160930

> cd TypeScript
> npm install
> node node_modules/gulp/bin/gulp.js --version
[17:57:47] Requiring external module ts-node/register
[17:57:47] CLI version 3.9.1
[17:57:47] Local version 3.9.1

> node node_modules/gulp/bin/gulp.js local
[17:59:26] Requiring external module ts-node/register

/home/dev/TypeScript/node_modules/ts-node/src/index.ts:253
          throw new TSError(diagnosticList)
                ^
TSError: ⨯ Unable to compile TypeScript
Gulpfile.ts (20,15): Duplicate identifier 'CompileStream'. (2300)
    at getOutput (/home/dev/TypeScript/node_modules/ts-node/src/index.ts:253:17)
    at /home/dev/TypeScript/node_modules/ts-node/src/index.ts:263:16
    at Object.compile (/home/dev/TypeScript/node_modules/ts-node/src/index.ts:398:17)
    at Module.m._compile (/home/dev/TypeScript/node_modules/ts-node/src/index.ts:299:46)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/dev/TypeScript/node_modules/ts-node/src/index.ts:302:14)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)

```

**Comment by Istar-Eldritch** [comment] 2016-09-30 08:42
@johanssj once you remove the line 20 from the gulpfile that error is gone.

**Comment by johanssj** [comment] 2016-09-30 09:22
Thanks for your help @Istar-Eldritch.  Same as previously reported.

Commented out line 20 in Gulpfile.js

//    interface CompileStream extends NodeJS.ReadWriteStream { } // Either gulp or gulp-typescript 

> npm install

> node node_modules/gulp/bin/gulp.js local

That error is gone but a new error is reported. A bunch of files are generated into 'built' but this error sounds like 'built' is incomplete.

```
[18:41:39] 'built/local/tsc.js' errored after 751 μs
[18:41:39] Error: Cannot find module './built/local/typescript.js'
```

Last 50 or so line of console output:

```
node scripts/processDiagnosticMessages.js src/compiler/diagnosticMessages.json
[18:41:21] Finished 'built/local/lib.webworker.d.ts' after 4.35 s
[18:41:21] Finished 'built/local/lib.scripthost.d.ts' after 4.35 s
[18:41:21] Finished 'built/local/lib.es2015.d.ts' after 4.34 s
[18:41:21] Finished 'built/local/lib.dom.d.ts' after 4.38 s
[18:41:21] Finished 'built/local/lib.es2016.d.ts' after 4.34 s
[18:41:21] Finished 'built/local/lib.es2017.d.ts' after 4.34 s
[18:41:21] Finished 'built/local/lib.es5.d.ts' after 4.35 s
[18:41:21] Finished 'built/local/lib.es2015.core.d.ts' after 4.33 s
[18:41:21] Finished 'built/local/lib.es2015.generator.d.ts' after 4.33 s
[18:41:21] Finished 'built/local/lib.es2015.iterable.d.ts' after 4.33 s
[18:41:21] Finished 'built/local/lib.es2015.promise.d.ts' after 4.33 s
[18:41:21] Finished 'built/local/lib.es2015.collection.d.ts' after 4.33 s
[18:41:21] Finished 'built/local/lib.es2015.symbol.d.ts' after 4.32 s
[18:41:21] Finished 'built/local/lib.es2015.proxy.d.ts' after 4.32 s
[18:41:21] Finished 'built/local/lib.es2015.reflect.d.ts' after 4.32 s
[18:41:21] Finished 'built/local/lib.es2015.symbol.wellknown.d.ts' after 4.32 s
[18:41:21] Finished 'built/local/lib.es2017.object.d.ts' after 4.31 s
[18:41:21] Finished 'built/local/lib.es2016.array.include.d.ts' after 4.31 s
[18:41:21] Finished 'built/local/lib.dom.iterable.d.ts' after 4.36 s
[18:41:21] Finished 'built/local/lib.es2017.sharedmemory.d.ts' after 4.31 s
[18:41:21] Finished 'built/local/lib.d.ts' after 4.35 s
[18:41:21] Finished 'built/local/lib.es6.d.ts' after 4.37 s
[18:41:21] Starting 'lib'...
[18:41:21] Finished 'lib' after 12 μs
[18:41:22] Finished 'src/compiler/diagnosticInformationMap.generated.ts' after 259 ms
[18:41:22] Starting 'generate-diagnostics'...
[18:41:22] Finished 'generate-diagnostics' after 5.66 μs
[18:41:22] Starting 'built/local/typescriptServices.js'...
gulp-typescript: ts(tsProject) has been deprecated - use .pipe(tsProject(reporter)) instead
  As of gulp-typescript 3.0, .pipe(ts(tsProject)) should be written as .pipe(tsProject()).
  More information: http://dev.ivogabe.com/gulp-typescript-3/
[18:41:22] Starting 'built/local/diagnosticMessages.generated.json'...
[18:41:22] Finished 'built/local/diagnosticMessages.generated.json' after 475 μs
[18:41:39] Finished 'built/local/typescriptServices.js' after 17 s
[18:41:39] Starting 'built/local/tsc.js'...
[18:41:39] 'built/local/tsc.js' errored after 751 μs
[18:41:39] Error: Cannot find module './built/local/typescript.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at getCompilerSettings (/home/dev/TypeScript/Gulpfile.ts:263:27)
    at Gulp.<anonymous> (/home/dev/TypeScript/Gulpfile.ts:379:82)
    at module.exports (/home/dev/TypeScript/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/dev/TypeScript/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/dev/TypeScript/node_modules/orchestrator/index.js:214:10)
    at /home/dev/TypeScript/node_modules/orchestrator/index.js:279:18
    at finish (/home/dev/TypeScript/node_modules/orchestrator/lib/runTask.js:21:8)
    at /home/dev/TypeScript/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/home/dev/TypeScript/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/home/dev/TypeScript/node_modules/end-of-stream/index.js:31:18)
    at emitNone (events.js:91:20)
    at DestroyableTransform.emit (events.js:185:7)
    at /home/dev/TypeScript/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)


```

**Comment by Istar-Eldritch** [comment] 2016-09-30 09:33
@johanssj Sorry, I was finally able to reproduce it. Looks like I had previous state in built from previous compilations.

I'll look into it after work, I should come with a solution by the end of the day.

**Comment by johanssj** [comment] 2016-09-30 09:51
Thank you so much @Istar-Eldritch

**Comment by mhegazy** [comment] 2016-10-01 09:17
Should be fixed by https://github.com/Microsoft/TypeScript/pull/11290.

**Closed by mhegazy** 2016-10-01 09:17 UTC
