### ISSUE TITLE
Wrong conclusions for variables being possibly undefined

### ISSUE THREAD

**Issue by dilyanpalauzov** [microsoft/TypeScript#39503] opened 2020-07-08 16:23 UTC
With tsc 3.9.2:

**Code**

```ts
type t = {
    x?: string
}

let f = (s:string) => s

let a = (m: t, n: t) =>  m.x || n.x ? "a" + f(m.x || n.x) + "g" : "ag"
```

**Expected behavior:**
No error
**Actual behavior:**

The parameter of `f()`  produces error:
>  Argument of type 'string | undefined' is not assignable to parameter of type 'string'.  Type 'undefined' is not assignable to type 'string'.(2345)

The same happens, when `||` are replaced with `??`.  Since logically `m.x||n.x` is truthy, from the first parameter of the ternary operator, it cannot be undefined in the second parameter.

**Comment by MartinJohns** [comment] 2020-07-08 16:29
Duplicate of #31603.

**Closed** 2020-07-08 16:38 UTC
