### ISSUE TITLE
Array destructuring puts declaration after assignment

### ISSUE THREAD

**Issue by sixinli** [Microsoft/TypeScript#7691] opened 2016-03-26 00:04 UTC
**TypeScript Version:** 

1.8.7

**Code**

```ts
let firstValue = 1;
let secondValue = 2;
[firstValue, secondValue] = [3, 4];
```

**Expected behavior:**
```javascript
var firstValue = 1;
var secondValue = 2;
var _a;
_a = [3, 4], firstValue = _a[0], secondValue = _a[1];
```

**Actual behavior:** 
```javascript
var firstValue = 1;
var secondValue = 2;
_a = [3, 4], firstValue = _a[0], secondValue = _a[1];
var _a;
```
Closure Compiler reports `_a` as unreachable code / use before definition. While this works at runtime, it's not a good practice and looks like a bug in tsc.

**Comment by mhegazy** [comment] 2016-03-26 00:22
duplicate of  #7017

**Closed by mhegazy** 2016-03-26 00:22 UTC

**Comment by mhegazy** [comment] 2016-03-26 00:24
as explained in https://github.com/Microsoft/TypeScript/issues/7017#issuecomment-182989037, we intend to change this in the future, just to make the code more idiomatic and less machine-generated-like.
