### ISSUE TITLE
Stricter react props checking with discriminated unions

### ISSUE THREAD

**Issue by barmaglot92** [Microsoft/TypeScript#29931] opened 2019-02-15 11:16 UTC
Hi. Sorry if it's already solved problem but i can't find it
I want if sortable props occurred it orderBy will be required, and it works, but it don't work for opposite case when i don't pass sortable passing orderBy must occur error props not exists but it's not.

So is it my issue or react typings issue?

```
type CTableProps = {
    items: any[]
    columns: any[]
} & SortableTableProps


type Sortable = {
    sortable: true
    orderBy: string
}

type SortableTableProps = Sortable | {sortable?: false}


class CTable extends React.Component<CTableProps> {

    static defaultProps = {
        sortable: false,
    }

}


// using with "stictNullChecks": true

class Wrapper extends React.Component {
    render() {
        return <CTable items={[]} columns={[]} sortable />  // here orderBy is required
    }
}


class Wrapper extends React.Component {
    render() {
        return <CTable items={[]} columns={[]} orderBy="testField" /> // here must be error: there is no orderBy props but its not
    }
}
```

**Comment by jack-williams** [comment] 2019-02-15 17:38
Smaller repro: 
```ts
interface Foo {
    a: number;
    x: true;
}

interface Bar {
    b: string;
    x?: false;
}

type FooBar = (Foo | Bar)

const x: FooBar = { b: "hello", a: 3 };
```
Missing properties are not being used to discriminate in EPC.

**Comment by jack-williams** [comment] 2019-02-15 18:07
To follow up on my rather opaque post; this is not to do with react, and appears to be an issue caused by the design of excess property checking. 

Regarding changing this behaviour: I'm not sure fixing this is worth the cost, given the current aims of EPC. Right now discrimination is driven by the source properties in the literal (small) to check on-demand against properties in the target union (large). To fix this case would require checking the complete target type to determine the properties that have been implicitly missed by not providing them in the literal.

Obviously, this is assuming that I haven't misunderstood something, or missed an obvious fix. Both are probable.

**Comment by RyanCavanaugh** [comment] 2019-02-15 18:33
This is correct; without an identifiable discriminant (which is definitely not present in this example), EPC can only warn about properties excess to the entire union. When we can't tell *exactly which* union constituent you're trying to assign to, EPC can't be too aggressive or you quickly start to get false positives.

**Comment by barmaglot92** [comment] 2019-02-15 22:05
I forgot to say that if pass sortable={false} then behaviour is expected.
I reply you later, when I can read response more carefully.
I agree this isn't important issue.
Also as I remember it works without using JSX (via directly calling createElement) but I need to check it again (I'll do it tomorrow)

**Comment by barmaglot92** [comment] 2019-02-17 19:20
I check, this isn't TS issue exactly.
```
type CTableProps = {

    
} & SortableTableProps


type Sortable = {
    sortable: true
    orderBy: string
}

type SortableTableProps = Sortable | { sortable?: false }

function f(p: CTableProps) {}

f({
    orderBy: "test",
})
```
![feb-17-2019 22-17-13](https://user-images.githubusercontent.com/3037173/52917939-dac77780-3301-11e9-946a-08d395dc788d.gif)

**Closed** 2019-02-19 06:22 UTC
Labels: Question

**Comment by andrewvarga** [comment] 2019-03-02 12:07
It looks related, but I'm not sure if it's the same issue I have or a problem in the React type definitions.
Basically there is no compile error when I add an existing correct key into listeners ("stop"), but there is a compile error as expected when I only supply the wrong key ("startX" instead of "start")

```typescript
import * as React from "react";
import { render } from "react-dom";

interface TestProps {
	label: string;
	listeners: {
		start?: () => void;
		stop?: () => void;
	}
}

class Test extends React.Component<TestProps> {
	constructor(props: TestProps) {
		super(props);
	}

	public render() {
		return <div>{this.props.label}</div>;
	}
}

function App() {
	return (
		<div className="App">

			{/* No error :( */}
			<Test label="hey" listeners={({
				startX: () => {},
				stop: () => {}
			})} />

			{/* Compile error as expected
				TS2322: Type '{ startX: () => void; }' is not assignable to type '{ start?: () => void; stop?: () => void; }'.
				Object literal may only specify known properties, but 'startX' does not exist in type '{ start?: () => void; stop?: () => void; }'. Did you mean to write 'start'?
			 */}
			<Test label="hey" listeners={{
				startX: () => {}
			}} />
		</div>
	);
}

const rootElement = document.getElementById("appHolder");
render(<App />, rootElement);
```
