### ISSUE TITLE
Error in definition of interface IteratorResult

### ISSUE THREAD

**Issue by lord-saumagen** [Microsoft/TypeScript#15912] opened 2017-05-17 19:03 UTC
Dear Ladies and Gentlemen,

I would like to bring to your attention, that the following interface is not conform to the specification in the "lib.es6.d.ts".

Currently defined as:

interface IteratorResult&lt;T&gt; {
    done: boolean;
    value: T;
}

The specification tells that the last IteratorResult returned form an iterator has the following values assigned:

done = true;
value = undefined,

So the correct interface definition would be:

interface IteratorResult&lt;T&gt; {
    done: boolean;
    value: T | undefined;
}

[See the description ad MDN: ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield)

![image](https://cloud.githubusercontent.com/assets/9468599/26171061/1eac42fa-3b33-11e7-9e3e-b420868b7635.png)

This issue might also be related to:
[TypeScript 2.0 change in IterableResult<T> makes implementing iterators harder](https://github.com/Microsoft/TypeScript/issues/11375)

Kind regards,

Lord Saumagen.

**Comment by mhegazy** [comment] 2017-05-17 19:35
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/2983 and https://github.com/Microsoft/TypeScript/issues/11375

**Comment by mhegazy** [comment] 2017-06-02 01:36
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-06-02 01:36 UTC
Labels: Duplicate
