### ISSUE TITLE
In JS, @template with @typedef is not equivalent to a generic type alias

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#23745] opened 2018-04-27 21:21 UTC
```js
/**
 * @template T
 * @typedef {[T, T]} TPair
 */
/** @type {TPair<number>} */
var tp = [1,2]
```

TPair doesn't correctly create a generic type alias.

**Expected behavior:**

TPair's typedef is equivalent to `type TPair<T> = [T, T]`

**Actual behavior:**

TPair's typedef is equivalent to `type T; type TPair = [T, T]` (where T is unique and inexpressible). So `@type {TPair}` is legal, but nothing can be assigned to it, and `@type {TPair<number>}` says that TPair is not generic.

**Comment by DanielRosenwasser** [comment] 2018-04-28 17:09
Isn't this a duplicate of #23385?

**Comment by sandersn** [comment] 2018-04-30 00:27
This is the first repro in #23385, which covered both template tags on classes and on typedefs. Notably, this bug has not come up in real code yet, only in our discussions and webpack’s discussions of style guidelines.

**Comment by sandersn** [comment] 2018-04-30 00:32
Basically, there were two bugs to fix, so I went for the one that @TheLarkInn was waiting on. 😸

**Comment by TheLarkInn** [comment] 2018-04-30 02:00
Thanks for submitting this, I wasn't 100% sure it was a bug but got distracted. I'm glad I was right so yay we can fix it! 😍😂

**Comment by sandersn** [comment] 2018-05-07 21:54
Fix is up at #23947

**Closed** 2018-05-17 16:28 UTC
Labels: Bug, Domain: JSDoc, Fixed, Salsa
