### ISSUE TITLE
Non const enums breaking Closure Compiler Advanced mode in 1.5

### ISSUE THREAD

**Issue by jbrosi** [microsoft/TypeScript#2655] opened 2015-04-07 14:23 UTC
Starting with 1.5 alpha non-const enums preserve their names. Though on initialization they are defined with String constants and in the code without. This breaks google closure compiler in advanced mode, as it thinks of the enums as two different pairs of shoes:

```
export enum ResourceType {
    STRING,
    JSON
}
var a = ResourceType.JSON;
```

compiles to:

```
(function (ResourceType) {
    ResourceType[ResourceType["STRING"] = 0] = "STRING";
    ResourceType[ResourceType["JSON"] = 1] = "JSON";
})(test.ResourceType || (test.ResourceType = {}));
var ResourceType = test.ResourceType;
var a = ResourceType.JSON;
```

I'd expect the ResourceType.JSON in the last line also to be ResourceType["JSON"] or vice versa. Of course I could write "ResourceType["JSON"]" myself everywhere I use the enum, but that kills off my auto-completion and seems not to be intended.

**Comment by DanielRosenwasser** [comment] 2015-04-07 14:39
I'm not exactly sure what the issue is. Can you post exactly where this breaks? Also, please update the code sample that causes the issue as well as the generated closure code; it looks like you meant to post something like the following:

```TypeScript
module test {
    export enum ResourceType {
        STRING,
        JSON
    }
    var a = ResourceType.JSON;
}
```

instead of

```TypeScript
export enum ResourceType {
    STRING,
    JSON
}
var a = ResourceType.JSON;
```

**Comment by jbrosi** [comment] 2015-04-07 15:15
Tanks for your quick answer and sorry for not being clear, here my updated example:

    module test {
        export enum ResourceType {
            STRING,
            JSON
        }

        function test(v1: ResourceType, v2: ResourceType) {
            console.log(v1, v2, v1 == v2);
        }

        var example = ResourceType.STRING;
        test(example, ResourceType.STRING);
    }

Compiles to

    var test;
    (function (test_1) {
        (function (ResourceType) {
            ResourceType[ResourceType["STRING"] = 0] = "STRING";
            ResourceType[ResourceType["JSON"] = 1] = "JSON";
        })(test_1.ResourceType || (test_1.ResourceType = {}));
        var ResourceType = test_1.ResourceType;
        function test(v1, v2) {
            console.log(v1, v2, v1 == v2);
        }
        var example = ResourceType.STRING;
        test(example, ResourceType.STRING);
    })(test || (test = {}));

Which compiles with closure compiler to (debug mode and pretty print active):

    var $test$$;
    (function($ResourceType_test_1$$) {
      (function($ResourceType$$1$$) {
        $ResourceType$$1$$[$ResourceType$$1$$.STRING = 0] = "STRING";
        $ResourceType$$1$$[$ResourceType$$1$$.JSON = 1] = "JSON";
      })($ResourceType_test_1$$.$ResourceType$ || ($ResourceType_test_1$$.$ResourceType$ = {}));
      $ResourceType_test_1$$ = $ResourceType_test_1$$.$ResourceType$;
      (function test$$1($v1$$, $v2$$) {
        console.log($v1$$, $v2$$, $v1$$ == $v2$$);
      })($ResourceType_test_1$$.$STRING$, $ResourceType_test_1$$.$STRING$);
    })($test$$ || ($test$$ = {}));


If you execute the closure compiled code you will see "undefined undefined true" whereas in the non-closure-compiled variant you will see "1 1 true".

The problem is, that if the closure compiler sees ResourceType.STRING it will try to minify it and rewrites the variable (in this case to ResourceType.$STRING$ because of the debug option). However it will not touch variables written in this notation: ResourceType["STRING"]. The problem is that typescript now is using both for the enum compilation. The one with ["STRING"] in the enum definition and the one without throughout the code.

I hope I made it more clear.

**Comment by RyanCavanaugh** [comment] 2015-04-07 18:05
Isn't it just a bug in the closure compiler that those two known-equivalent syntax variants aren't treated identically?

We don't use the form `ResourceType[ResourceType.JSON = 1] = "JSON";` because enum members can have names that can't be written in dot notation (e.g. `enum X { "who does this" }`).

Using a consistent emit pattern makes it easier for tools to reason about the emitted code (e.g. you want to write a tool that specially minifies enums, so we should make enum emit easy to identify). I think that applies here -- if closure is screwing up its minification, maybe the right fix is a pre-minifier step that cleans up conforming enums to dotted notation where appropriate?

**Comment by jbrosi** [comment] 2015-04-07 18:22
@RyanCavanaugh  Thanks for your answer! 

Closure compiler needs to handle them differently as you might have variables from other sources (for example webservice json stuff) where it is *not* allowed to change variable names.

It would be no problem to use the `EnumType["who does this"]` syntax when you really specify your enum like this (e.g. `enum X { "who does this" }`). Typescript behaves the same in other conditions like when you write your function/variable name in "" (like `public "onCustomEvent"() { ...`) it will still compile it with "" if you don't it doesn't.

Of course it would be possible to make a pre-compile step in order to make everything closure compatible, but I'd really like typescript in general be compatible by default. We're using typescript in our company for quite a large project completely written in typescript and this enum thing in 1.5 is the very first problem we encounter with the closure compiler compatibility.

I see the point with the consistent emit pattern though, but I still hope for a way to fix this :). Closure compiler is a great tool (so is typescript!) and they both work very well together (well excluding that enum thing).

**Comment by timmyzaid** [comment] 2015-06-19 15:22
It seems like the way TypeScript currently generates enums, it would require you to access them with enumX['value'] when you are intending to minify your code.  Some people may prefer accessing them this way but in the project I work on we exclusively access enums with dot notation.  To get the best of both worlds, why not include a compiler option to specify how you want enums to be constructed?  It could be a simple flag that tells the compiler to generate them the current way or using dot notation.

**Comment by mhegazy** [comment] 2015-06-19 17:32
@timmyzaid have you considered using const enums instead?

**Comment by timmyzaid** [comment] 2015-06-19 17:39
Interesting, I had not.  While that does get around the mangling problem, it also produces code that is harder to debug.

**Comment by timmyzaid** [comment] 2015-06-19 17:45
Now maybe if there was conditional compilation?

**Comment by jbrosi** [comment] 2015-06-19 19:57
I assume const enums would solve my problem too, but as timmyzaid said: it's harder to debug, and so I'd like the normal enums to be compatible, too. The direct access to my enums with enum['asd'] for me is not acceptable as it would kill all the autocompletion / typechecking my ide offers.

**Comment by reshadi** [comment] 2015-08-08 03:30
Google closure uses the o["x"] as a hint to the compiler to not rename the x. It is just their way of "exporting" stuff. 
const enums are not always the answer, specially when reverse conversion from string to number is needed.

As @jbrosi mentioned, if the typescript generate normal enums with no ", it would work find in closure. So,
for:
    export enum ResourceType {
        STRING,
        JSON
    }
instead of: 
    ResourceType[ResourceType["STRING"] = 0] = "STRING";
    ResourceType[ResourceType["JSON"] = 1] = "JSON";

simply generate:
    ResourceType[ResourceType.STRING = 0] = "STRING";
    ResourceType[ResourceType.JSON = 1] = "JSON";

So, I guess the fix would be simply changing 3 lines starting from https://github.com/Microsoft/TypeScript/blob/master/src/compiler/emitter.ts#L5194
to something like:
                write(".");
                writeTextOfNode(currentSourceFile, node.name);
                write(" = ");

**Comment by RyanCavanaugh** [comment] 2015-08-08 04:31
Enum members need not be identifiers; `enum Foo { 'bar with a space' }` is legal (and needs the string literal to appear in the emit).

**Comment by reshadi** [comment] 2015-08-09 08:02
@RyanCavanaugh thanks for clarification, I did not know about that.
Would it make sense to at least create the . notation instead of [], whenever the enum member is a valid identifier?

**Comment by symaxian** [comment] 2015-10-07 15:01
This is an issue for me as well, I have a large TypeScript project that uses enumerations extensively and is ultimately run through the Closure compiler. The workaround I use now is to just declare a module to hold the enumerated values, though this doesn't provide any actual type support beyond number/string.

It would be nice to have a compilation mode in TypeScript where only valid dot-notation enum names are accepted and used without bracket notation in order to play nicely with Closure.

**Comment by RyanCavanaugh** [comment] 2015-10-07 17:21
We're generally not going to add flags that can be solved trivially in a build pipeline. In this case, replace the regular expression

 > `(\w+)\[(\1)\["([^"]*)"] = (\d+)] = "(\3)";`

with
 > `$1[$1.$3 = $4] = "$3";`

using the tool of your choice before running through Closure.

```ts
// Input
ResourceType[ResourceType["STRING"] = 0] = "STRING";
// Replacement
ResourceType[ResourceType.STRING = 0] = "STRING";
```

**Comment by jbrosi** [comment] 2015-10-07 19:37
Unfortunately this regex won't help us because sometimes (especially when working with external javascript libraries) we have to use the quoted identifier notation to mark variables which do *not* have to be changed by google closure compiler. The regex would match on those cases, too (not only on the enums).

I am still wondering why it would be a problem to handle the enums just the way typescript handles identifiers in other cases. 

For example when I write a class method with quotes like public "thisisAMethod" typescript compiles it with the quotes, if I write it without quotes, typescript compiles it without. Also, like with enums a classname like "this is a class" would be invalid in typescript and javascript if you omit the quotes.

Same problem with enums! The following is *invalid* anyway and would have to be written in quotes:

    export enum ResourceType {
        this is a long identifier
    }

...This one would work:

    export enum ResourceType {
        "this is a long identifier"
    }

So you in fact you can't have an invalid enum type with spaces if you don't add quotes yourself in typescript. So if typescript just would stick to the definition you used within the quotes, it should be fine for google closure compiler, too.

    enum ResourceType {
        "this is enum"
    }

should compile to:

    (function (ResourceType) {
        ResourceType[ResourceType["this is enum] = 0] = "this is enum";
    })(...);

whereas

    enum ResourceType {
        thisIsEnum
    }

should compile to:

    (function (ResourceType) {
        ResourceType[ResourceType.thisIsEnum = 0] = "thisIsEnum";
    })(...);

**Comment by RyanCavanaugh** [comment] 2015-10-07 19:56
> Unfortunately this regex won't help us because sometimes (especially when working with external javascript libraries) we have to use the quoted identifier notation to mark variables which do not have to be changed by google closure compiler

The regex *only* matches things in the form `X[X[Y] = N] = Y` where both `X`s are the same and both `Y`s are the same and `N` is a number. I can't imagine that there are any uses of that pattern that aren't enum emit?

**Comment by jbrosi** [comment] 2015-10-07 20:12
@RyanCavanaugh Thanks for your answer! While I must admit, it would be a very rare case if anything else matches this regex... It still *could* happen and it still doesn't feel right for me - it's more like a workaround.

(Though that workaround might work well for us at the moment and we're definitely going to evaluate it, thanks for the idea!)

**Comment by knuton** [comment] 2015-12-16 11:34
Maybe I am missing something, but the easiest solution that should make everybody happy seems to be always emitting

```js
var example = ResourceType["STRING"];
```

for member access instead of

```js
var example = ResourceType.STRING;
```

which solves the issue with Closure Compiler, and also allows for a uniform emit pattern not only for member creation, but also for member access.

**Comment by jbrosi** [comment] 2015-12-16 17:51
@knuton You're right, this would compile correctly (in terms of compatibility to closure compiler), but breaks Code completion for most IDEs :). So I'd still prefer the suggested output of typescript to be directly compatible with closure compiler while having the code completion features and stuff.

**Comment by knuton** [comment] 2015-12-16 18:10
@jbrosi Where do you want code completion? In the emitted JavaScript?

My suggestion is not for *you* to write `ResourceType["STRING"]`, but for the TypeScript compiler to recognize whatever you write (probably one of `ResourceType["STRING"]`/`ResourceType.STRING`) as an enum member access and produce `ResourceType["STRING"]` in the generated JavaScript.

Doesn't change anything about your input.

**Comment by jbrosi** [comment] 2015-12-16 20:25
@knuton ah sorry, I indeed missunderstood. If the compiler would emit it like you suggest everything would be fine :)!

**Comment by knuton** [comment] 2016-01-14 16:32
@RyanCavanaugh The proposed regex is too restrictive to capture all possible emits, e.g. if we have some `x : number`, then

```ts
enum Foo {
  A = x
}
```

produces JavaScript source that won't be captured. And we could in principle substitute any expression of type `number` for `x`. I find it non-trivial to think of a regex that captures exactly the outputs of legal enum member definitions. Maybe `(\w+)\[(\1)\["([^"]*)"] = (.+?)] = "(\3)";` would work in most cases, but in any case I would disagree that this is _trivial_ to solve with extra build tools.

In **summary**:

1. The TypeScript compiler normalizes property accessor notation in enum member _definitions_ but not in enum member _access_. In member definition, the bracket notation is used no matter whether the member name was written as `A` or `"A"`. In member access, the property access notation is preserved as written in the TypeScript source, `Enum.A` stays `Enum.A`, `Enum["A"]` stays `Enum["A"]`.
2. Up to version 1.4 the TypeScript compiler used to emit number literals for enum member accesses where those were known statically. Since version 1.5 it always emits the property access expression found in the source.

Point (1.) causes the Closure Compiler to perform inconsistent renaming in advanced optimization mode, leading to defective output as described by @jbrosi. Before 1.5 this was not problematic for simple enum member definitions (`A` or `A = 0`), where number literals could always be emitted for member access. But with the change in 1.5 this problem surfaces for any enum member not _defined_ as a string literal.

So (1.) and (2.) together make an edge case an issue that affects anyone using the Closure compiler to optimize TypeScript output.

The **proposed solution** is to normalize enum member access in the same way as enum member definition, and always emit `Enum["A"]`, no matter whether the access is written as `Enum["A"]` or `Enum.A` in the TypeScript source. It is in line with your stated goal of having uniform emit patterns.

There is a price of 3 extra characters per member access, but the same price is already payed for the uniformity in member definition.

I understand that you do not want to fix issues arising from interactions with arbitrary build tools (though the Closure compiler is not any random tool), so let me make the appeal that if you opt for uniformity in definition emits, you should also opt for uniformity in access emits.

What do you think?

**Comment by RyanCavanaugh** [comment] 2016-01-14 17:32
I don't like this because it simply *changes* who gets screwed over -- odds are good there's someone else depending on dotted access in emit. Our mantra has always been that we try to emit code as similar to how you wrote it as is possible; no guessing games about which emit is the one you *actually* wanted.

It's pretty easy to write a TSLint rule to enforce a particular property accessing mode for a particular symbol so that you can just enforce `Enum['Member']` in your codebase. I'd be happy to help out here if that's a route you're interested in.

As an aside -- not to question your use case, but if you're running through an advanced minifier, why not just use `const enum`s everywhere in your code?

**Comment by knuton** [comment] 2016-01-14 18:00
> I don't like this because it simply changes who gets screwed over -- odds are good there's someone else depending on dotted access in emit. Our mantra has always been that we try to emit code as similar to how you wrote it as is possible; no guessing games about which emit is the one you actually wanted.

This is a good point. However, in this case I'd ask to reconsider emitting member definitions according to the notation used in the source as well.

If what you wrote above,

> We don't use the form `ResourceType[ResourceType.JSON = 1] = "JSON";` because enum members can have names that can't be written in dot notation (e.g. `enum X { "who does this" }`).

is your only reason for the current behaviour, consider that this interaction between Closure and TypeScript is subtle and likely to continue to bite people. If on the other hand definition and access notation vary "in harmony", no one has to be screwed over.

`const enum`s are unfortunately not an option for us. We actually assign member values from non-literal expressions to reduce potential breakage in the context of independent package compilation.

The TSLint rule would be a solution, though not likely to be popular with developers who value IDE support.

I will evaluate search-replace as part of the build chain and am reasonably confident that this will work reliably. Yes, our setup is unusual and I am willing to adjust for that, yet I still think that it would be preferable if TypeScript produced JavaScript that works with Closure out of the box.

**Comment by staff0rd** [comment] 2016-02-24 07:01
Whilst this is still being discussed, is there any workaround for enums when using the closure compiler?

**Comment by knuton** [comment] 2016-02-24 10:18
@staff0rd There are two workarounds as suggested by @RyanCavanaugh:

1. "It's pretty easy to write a TSLint rule to enforce a particular property accessing mode for a particular symbol so that you can just enforce `Enum['Member']` in your codebase." (suggested [here](https://github.com/Microsoft/TypeScript/issues/2655#issuecomment-171715882))

   There is a pretty significant downside: You lose both IDE support and type-checking for member access.
2. Postprocess the JavaScript code emitted by the TypeScript compiler to de-normalize enum member definitions (suggested [here](https://github.com/Microsoft/TypeScript/issues/2655#issuecomment-146268149)). This takes some more finesse but is less intrusive on developer workflow.

   If you know you have a specific usage pattern of enums that is captured by the suggested regexp, go for it.

   For the **general case**, the challenge is to find a pattern that captures the complexity of identifying legal identifier names, [illustrated here](http://www.typescriptlang.org/Playground#src=declare%20var%20someDict%3A%20%7B%20%5B%20key%3A%20string%5D%3A%20number%20%7D%3B%0A%0Aenum%20Adventurous%20%7B%0A%09A%2C%0A%09%E1%83%9A_%E0%B2%A0%E7%9B%8A%E0%B2%A0_%E1%83%9A%20%3D%20someDict%5B%22just%20mean%22%5D%2C%0A%09%22no-pe%22%20%3D%205%0A%7D%0AAdventurous.A%3B%0Aalert(Adventurous.%E1%83%9A_%E0%B2%A0%E7%9B%8A%E0%B2%A0_%E1%83%9A)%3B%0AAdventurous%5B%22no-pe%22%5D%3B):

   ```ts
   declare var someDict: { [ key: string]: number };

   enum Adventurous {
	A,
	ლ_ಠ益ಠ_ლ = someDict["just mean"],
	"no-pe" = 5
   }
   Adventurous.A;
   alert(Adventurous.ლ_ಠ益ಠ_ლ);
   Adventurous["no-pe"];
   ```

   The TypeScript scanner actually has code to do just this (identify identifiers): https://github.com/Microsoft/TypeScript/blob/v1.5.4/src/compiler/scanner.ts#L158-L246

   A Java/Groovy implementation using regular expressions is [in the Spaghetti project](https://github.com/prezi/spaghetti/blob/4c91070f104283fb1a8411abe414395fc412544f/spaghetti-typescript-support/src/main/groovy/com/prezi/spaghetti/typescript/bundle/TypeScriptEnumDenormalizer.groovy).

**Comment by evmar** [comment] 2016-10-18 16:51
The tsickle project (https://github.com/angular/tsickle) changes enum definitions as a preprocessing step.

You can see a test case here:
https://github.com/angular/tsickle/tree/master/test_files/enum
(the .ts file is the input, the .tsickle.ts is what tsickle generates, and the .js is the resulting tsc output)

**Comment by mprobst** [comment] 2016-10-19 22:04
FWIW, there's https://github.com/angular/tsickle. That takes TypeScript and produces code that is Closure Compiler compatible, including advanced mode. It has a specific pass to transform enum output to be compatible.

**Comment by RyanCavanaugh** [comment] 2020-07-21 22:20
Closing as Won't Fix; there are many different workarounds available and we can't cater to every minifier at once.

**Closed by RyanCavanaugh** 2020-07-21 22:20 UTC
Labels: Needs Proposal, Suggestion
