### ISSUE TITLE
Type deduction is not correct in switch case.

### ISSUE THREAD

**Issue by Mng12345** [microsoft/TypeScript#51284] opened 2022-10-24 08:03 UTC
**typescript version: v4.8.4**
**[online playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBApmArgWxgMQJYBs4BUCeADnDAN4BQMVMA4hgGYwC8MADADSXUAKGwUiAE4kWARnIBfcuShESdegFkAhlDiCMyrMzJcq9bHjkAudIYLEAdAr0wMAE1PQNYAOa37q5aYCqGMFAAHACCgoLK+JLSssQwvPxCcCpqGlo6FNQwBjgWcKaYOXKW8QLCtg5OUC7umZ5Q3jB+ASFhEVEycjDJ6praLArdqdoAPnF8pUmqPVrRnQCi9hhQIIKDvem2yFNDpmszmRUwzv7uUuT0iGD8GOAwatAAFACUupmgkLBbKesspBIwyggMAWSxWeywtggAHclsAABYwB5faZYSzIoaWbJGYgvDKZajAQEkArYuDWBimPH4-HvaAwVAsdG9NHbXq2alUABGwmUAGt2dQpByYISIMTzEUSolKQLqbTPqIdEytCzvloANyy-EAbVE7BgACZ9QBmAC6LMIDyWcAZAD5XsKOfL6QalayVcqIY7BU8tZkAPT+u6dECMZCKjBAqXCcH6zmIWAxOChl12IHgv3UblwPlaoWCyRAA)**
```typescript
function test() {
    const material = {} as EditorMaterial // just for test
    switch (material.material.fileType) {
        case FileType.Gif: {
            const m = material.material
            break
        }
        case FileType.Picture: {
            const m1 = material.material;
            [1, 2, 3].map(item => {
                const m2 = material.material
            })
            // type of m1 is PictureMaterial, but typeof m2 is Material
            break
        }
    }
}
```
As you can see in the two pictures below, the type of m1 and m2 in the `case FileType.Picture` arm is not the same, type information losed in annoymous functions.
![image](https://user-images.githubusercontent.com/21278900/197476986-c9f411cd-5fbd-4ca1-abd6-f31859291074.png)
![image](https://user-images.githubusercontent.com/21278900/197477020-3d739cee-8c8d-454a-a5ad-5ffa44f85f56.png)

**Comment by MartinJohns** [comment] 2022-10-24 09:15
You forgot to fill out the issue template. This is a duplicate of #9998.

**Comment by fatcerberus** [comment] 2022-10-24 14:14
Note there's an issue template that explicitly calls out this behavior and instructs you not to file the issue because it's by design:
https://github.com/microsoft/TypeScript/issues/new?assignees=&labels=Duplicate&template=types-not-correct-in-with-callback.md&title=

But nobody ever seems to click that template except for unrelated issues... 😢

**Closed** 2022-10-26 18:00 UTC
Labels: Duplicate
