### ISSUE TITLE
Type deprecation failure when trying 4.2

### ISSUE THREAD

**Issue by thewilkybarkid** [microsoft/TypeScript#42956] opened 2021-02-25 13:48 UTC
# Bug Report

### 🔎 Search Terms

`jsDocCache` `getJSDocTagsWorker` `addDeprecatedSuggestion`

### 🕗 Version & Regression Information

- This changed between versions 4.1.5 to 4.2.2 (https://github.com/sciety/sciety/pull/506)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-beta&ssl=1&ssc=10&pln=1&pc=20#code/JYWwDg9gTgLgBAbzgIQIYBMBKBTAjgV2wGd4BfOAMyghDgHIALGGMAWmymqiLoG4AofjAbUA7nAB22cWix5CJABQBKAUA) (doesn't fail, but `4.2.2` isn't available)

### 💻 Code

Locally, just the import is required for it to fail:

```ts
import { BadRequest } from 'http-errors';
```

After a little debugging, `target` inside `checkAliasSymbol` looks like:

```ts
<ref *1> Symbol {
  flags: 33554436,
  escapedName: 'BadRequest',
  declarations: undefined,
  valueDeclaration: undefined,
  id: undefined,
  mergeId: undefined,
  parent: undefined,
  checkFlags: 262144,
  mappedType: <ref *3> Type {
    flags: 524288,
    id: 22589,
    objectFlags: 201326688,
    symbol: Symbol {
      flags: 2048,
      escapedName: '__type',
      declarations: [Array],
      valueDeclaration: undefined,
      id: undefined,
      mergeId: undefined,
      parent: undefined,
      members: Map(0) {}
    },
    members: Map(82) {
      'BadRequest' => [Circular *1],
      'Unauthorized' => [Symbol],
      'PaymentRequired' => [Symbol],
      'Forbidden' => [Symbol],
[...]
```

Seems like `declarations` should never be undefined.

### 🙁 Actual behavior

Build fails.

### 🙂 Expected behavior

Build doesn't fail.

**Comment by RyanCavanaugh** [comment] 2021-02-25 21:29
I'm assuming this is a duplicate of #42957 but we'll track them separately just in case not

**Comment by sandersn** [comment] 2021-02-25 22:29
The repros are the same; the culprit is `@types/http-errors` in both cases.

**Closed by sandersn** 2021-02-25 22:29 UTC
Labels: Bug
