### ISSUE TITLE
JSX Auto-format adds unnecessary space in attributes

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8683] opened 2016-05-19 08:40 UTC
_From @AlecBoutin on May 18, 2016 19:55_

- VSCode Version: 1.1

The .tsx/.jsx auto-formatter adds an unnecessary space on the end of certain dynamic attributes.

E.g. `<button id={fn()} />` becomes `<button id={fn() } />` after the file is auto-formatted. A space is inserted after the closing parenthesis of the fn() call.

The problem appears to be related to having parenthesis in the attribute.

E.g. <button id={""} /> is left unchanged by auto-format. `<button id={("")} />` becomes `<button id={("") } />` (the space is inserted)

I have also observed the auto-formatter preserves the spaces in the id attribute of `<button id={ ("") } />`

_Copied from original issue: Microsoft/vscode#6498_

**Comment by evansb** [comment] 2016-05-20 07:18
Duplicate of https://github.com/Microsoft/TypeScript/issues/6716

**Comment by mhegazy** [comment] 2016-05-23 22:30
indeed a duplicate of #6716. thanks.

**Closed by mhegazy** 2016-05-23 22:30 UTC
Labels: Accepting PRs, Bug, Domain: Formatter
