### ISSUE TITLE
[Proposal] More consistency with redundant or unreachable conditionalities

### ISSUE THREAD

**Issue by zaclummys** [Microsoft/TypeScript#21593] opened 2018-02-03 00:16 UTC
## Proposal

TypeScript doesn't have consistency in denying redundant or unreachable conditionalities.

Conditionals are generally good for testing values that aren't actually `boolean`. But in strict environments this may not be a very friendly feature.

It's possible we forget to check what type a function returns before we use it in a conditional. For example, if a function always returns `undefined`, it would be redundant to wrap this value in a conditional.

**Why is this important?**

I believe that one of the TypeScript's philosophy is to reduce to the maximum the unexpected situations.

If I'm using a conditional for a value that will never be truthy, that is, coding a block that will never actually be used, my software inevitably becomes inconsistent.

**How can this be solved?**

TypeScript could allow us to configure a strict environment where we will be warned when detected scenarios similar to what I am describing.

Note: **Conditional** is a refence to **conditional statements**.

**Example**

```ts
// block 1
function hello (): void {
    alert('hello')
}

// block 2
if (hello()) {
     alert('world')
}
```

**Block 2** will always be unreachable because the value returned from `hello ` is always `undefined ` . 

It would be possible to argue that TypeScript doesn't know if there will be **extra modifications** to the value. But notice that it's used directly in IF-BLOCK, preventing any change in type/value.

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=function%20hello%20()%3A%20void%20%7B%0D%0A%20%20%20%20alert('hello')%0D%0A%7D%0D%0A%0D%0Aif%20(hello())%20%7B%0D%0A%20%20%20%20%20alert('world')%0D%0A%7D

**Search Terms:** 

- Redundant
- Unreachable
- Conditional

**TypeScript Version:**  2.7.1

**Comment by mhegazy** [comment] 2018-02-03 00:19
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/9041

**Comment by zaclummys** [comment] 2018-02-03 00:23
This proposal is not restricted to the example I have used, I'm pointing out a general way of dealing with redundant/unreachable situations.

**Comment by mhegazy** [comment] 2018-02-03 00:33
if you look at https://github.com/Microsoft/TypeScript/issues/9041#issuecomment-280419494 we tried doing the general solution, and that broke multiple common code patterns.

**Closed** 2018-02-20 19:07 UTC
Labels: Duplicate
