### ISSUE TITLE
Error: Could not find file in 'getValidSourceFile' during 'quickinfo'

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#21813] opened 2018-02-09 01:19 UTC
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.1
**VSCode Version** 1.20.0-insider
**command requested**: quickinfo
**hitting sessions**: 517
**proportion of all sessions**: 0.001930019076204022
**stack**
```
Error: Could not find file
    at getValidSourceFile (tsserver.js:82737:23)
    at Object.getQuickInfoAtPosition (tsserver.js:82889:30)
    at IOSession.Session.getQuickInfoWorker (tsserver.js:89819:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:88972:61)
    at unknown (tsserver.js:90393:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90384:28)
    at IOSession.Session.executeCommand (tsserver.js:90393:33)
    at IOSession.Session.onMessage (tsserver.js:90413:35)
    at Interface.<anonymous> (tsserver.js:91614:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mhegazy** [comment] 2018-02-09 18:01
looks related to https://github.com/Microsoft/TypeScript/issues/20785

**Comment by aozgaa** [comment] 2018-03-05 05:00
This issue reproduced in the following context:
**TypeScript Version Prefix**: 2.7.2
**VSCode Version** 1.20.1
**command requested**: quickinfo
**hitting sessions**: 113
**proportion of all sessions**: 0.00231989981317621
**stack**
```
Error: Could not find file
    at getValidSourceFile (tsserver.js:82897:23)
    at Object.getQuickInfoAtPosition (tsserver.js:83049:30)
    at IOSession.Session.getQuickInfoWorker (tsserver.js:89979:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89132:61)
    at unknown (tsserver.js:90553:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90544:28)
    at IOSession.Session.executeCommand (tsserver.js:90553:33)
    at IOSession.Session.onMessage (tsserver.js:90573:35)
    at Interface.<anonymous> (tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by andy-ms** [comment] 2018-03-12 21:07
Duplicate of #20785 
@aozgaa These (this and #20786 and #21795) are all the same error, with the only difference being that they started with a different services call (which all immediately call `getValidSourceFile`) -- could we disambiguate these automatically?

**Closed by andy-ms** 2018-03-12 21:07 UTC
Labels: Bug, Source: Telemetry
