### ISSUE TITLE
[Feature request] Detect when type guards are exhaustive

### ISSUE THREAD

**Issue by inlined** [microsoft/TypeScript#45881] opened 2021-09-14 23:47 UTC
# Suggestion

TypeScript's compiler should recognize code that is unreachable based on exhaustive checks of type guards.

## 🔍 Search Terms

* Case class
* Type guard
* Dead code
* Unnecessary return

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Whenever I have a type that is a union of other types, I would like TypeScript to understand that I've exhausted all possible types.

## 📃 Motivating Example

TypeScript's type system is very rich and is _almost_ powerful enough to support case classes like Scala has. One of the best features of case classes is that I can write code that selects through all possibilities and I'm guaranteed to get compiler errors when the case class is expanded to hold new subtypes.

Consider the following code:

```
interface Fish {
  kind: "fish";
};

interface Bird {
  kind: "bird";
}

type Animal = Fish | Bird;

function isFish(animal: Animal): animal is Fish {
  return animal.kind === "fish";
}

function isBird(animal: Animal): animal is Bird {
  return animal.kind === "bird";
}

function getPasstime(animal: Animal): string {
  if (isFish(animal)) {
    return "swim";
  } else if (isBird(animal)) {
    return "fly";
  }
}
```

This code is perfectly safe, but won't transpile because `tsc` thinks `getPasstime` is missing a final return statement. Instead, TypeScript could recognize that these type guards are exhaustive and all code will lead to a return statement. That would ensure that when we add `Dog` as a new type of `Animal` the code would no longer be exhaustive and would fail until `getPasstime` is modified to handle or ignore the new case.

## 💻 Use Cases

I would use this to write forwards-compatible codebases where I can, if I adhere to a coding style, feel safe adding a new type because I know that my previous exhaustive type guards will break until they add the new case.

**Comment by IllusionMH** [comment] 2021-09-15 00:54
Looks like duplicate of #21985

**Closed** 2021-09-17 18:00 UTC
Labels: Duplicate
