### ISSUE TITLE
Compiler option for stricter implicit truthy and falsy checks

### ISSUE THREAD

**Issue by Ziriax** [Microsoft/TypeScript#8178] opened 2016-04-19 16:13 UTC
We have a large `Typescript` application, and sometimes we have code like

`if (shouldFireNuclearMissiles)...`

while we should have written

`if (shouldFireNuclearMissiles())...`

(pun intended).

So forgetting to evaluate a function results in a `truthy` value. 

I forked the `tsc` compiler to add basic checks for this in the conditional operator, the `if-then-else`, `while`, `do` and `for` statements, and that was very easy. We found several bugs in our large code using this forked compiler.

Would such a stricter compiler option (maybe even emitting warnings) be a sound idea?

These automatic `truthy` and `falsy` conversions are very handy, but IMHO, for large projects, the comfort they bring does not outweigh the dangers.

Most likely this idea is too much non-`Javascript`-like, but we're coming from sharp & strongly-typed languages, so I must make this suggestion ;-)

Thanks,
Peter

PS: I first [suggested this as a TSLINT rule ](https://github.com/Microsoft/tslint-microsoft-contrib/issues/112), but from the friendly feedback I got, it seems this belongs in the compiler instead.

**Comment by myitcv** [comment] 2016-04-19 16:16
Covered here https://github.com/palantir/tslint/issues/253 in the actual `tslint` repository

**Comment by RyanCavanaugh** [comment] 2016-04-19 17:18
Duplicate of #7306

**Closed by RyanCavanaugh** 2016-04-19 17:18 UTC
Labels: Duplicate
