### ISSUE TITLE
`unknown` is narrowed to `never` inside reachable conditional blocks

### ISSUE THREAD

**Issue by rsimoes** [microsoft/TypeScript#41833] opened 2020-12-05 19:55 UTC
**TypeScript Version:**  4.1.2 & 4.2.0-dev.20201205

**Search Terms:** unknown never NOT generic

**Code**

```ts
const logIfFoo = (maybeFoo: unknown) => {
  if (maybeFoo instanceof Object && "bar" in maybeFoo) {
    console.log(maybeFoo);
  }
}

logIfFoo({ bar: "baz" });
```

**Expected behavior:**
Transpiled JS that yields no output--given the inferred typing of `maybeFoo` to `never` inside the conditional block

**Actual behavior:**
Output of `{ bar: 'baz' }`

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.2#code/MYewdgzgLgBANiA5gSQGYDEQhgXhgCgFsBDATwCMBTTEALhgFcwBrMEAdzAEpcA+GAN4BYAFAwYAS1QESFalkmQoxMMEohpAeXIArSsFgAyQzABE5YgCdTimLKo0ewseJihIIOJQB0CRETIHLC4AblFxAF9RCLCRUXdoGFQFPAEYC0t6c2IALxsY0T80GnxkkFDRIA

**Comment by MartinJohns** [comment] 2020-12-05 21:11
Duplicate of #38608.

**Closed** 2020-12-05 22:10 UTC
