### ISSUE TITLE
Typed bind, apply and call?

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#25973] opened 2018-07-26 17:52 UTC
Tuples with rest are landed, so where my typed `bind`, `apply` and `call`? :)

**Comment by cevek** [comment] 2018-07-26 18:05
Currently is not possible to rewrite `lib.d.ts` typings
```ts
type RetType<T> = T extends (...args: any[]) => infer R ? R : any;
type Args<T> = T extends (...args: infer A) => infer R ? A : any;
declare global {
    interface Function {
        bind<This>(this: This, this_: {}, ...a: Args<This>): RetType<This>;
        foo<This>(this: This, this_: {}, ...a: Args<This>): RetType<This>;
    }
}

df.bind({}, ''); // bad - no error
df.foo({}, ''); // ok - error
```

**Comment by mhegazy** [comment] 2018-07-26 18:48
That is a duplicate of https://github.com/Microsoft/TypeScript/issues/212. 

We need to make the change, run the local tests and see if there are any interesting breaks.

**Closed** 2018-07-27 18:55 UTC
Labels: Duplicate
