### ISSUE TITLE
completions for locals should have higher "sortOrder" than completions for globals

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18398] opened 2017-09-11 22:30 UTC
From https://github.com/Microsoft/vscode/issues/34049

**TypeScript Version:**  2.5.2

**Code**

```ts
const WorkerActions = 1

WA|
```

Trigger completions at the `|` after `WA`

**Expected behavior:**
The local `WorkerActions` suggestion has higher weight than suggestions from the global scope.

**Actual behavior:**
TSServer returns global and local suggestions with the same `sortText`

```
[Trace  - 3:27:09 PM] Sending request: completions (353). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/d.js",
    "line": 3,
    "offset": 3
}
[Trace  - 3:27:09 PM] Response received: completions (353). Request took 19 ms. Success: true 
Result: [
   ....
       {
        "name": "WaveShaperNode",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "WorkerActions",
        "kind": "const",
        "kindModifiers": "",
        "sortText": "0"
    },
 ...
]
````

**Comment by mhegazy** [comment] 2017-09-12 01:03
Seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/15024

**Comment by mhegazy** [comment] 2017-09-26 16:11
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-26 16:11 UTC
Labels: Duplicate
