### ISSUE TITLE
Compile-on-save generates `_references.d.ts` with absolute paths

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#4252] opened 2015-08-10 16:02 UTC
Hi,

**Version**: VS 2015 / TS 1.5.4

To reproduce:

* Set `"Redirect JavaScript output to directory"` to say `bin`.
* Set `"Generate declarations files"`.
* Set `"Compile on save"`.
* Add file `_references.ts` to the project, with content

 ```xml
 /// <reference path='../../foo/bar1/bin/bar1.d.ts' />
 /// <reference path='../../foo/bar2/bin/bar2.d.ts' />
 ``` 

* Build the project and check the output directory. The content of `_references.d.ts` should be

 ```xml
 /// <reference path="../../../foo/bar1/bin/bar1.d.ts' />
 /// <reference path="../../../foo/bar1/bin/bar2.d.ts' />
 ```

* Now modify one file in the project and trigger `compile-on-save` by saving the file. Now the content of the same file should have changed to 

 ```xml
 /// <reference path="d:/x/y/z/foo/bar1/bin/bar1.d.ts' />
 /// <reference path="d:/x/y/z/foo/bar1/bin/bar2.d.ts' />
 ```

This together with #4245 appears to be a regression introduced in the fix for #3939.

This is interfering with some systems we have in place.

**Comment by sheetalkamat** [comment] 2015-08-10 23:04
This seems to be resulting because outputdirectory path isn't expanded. Its duplicate of #4109

**Comment by mhegazy** [comment] 2015-08-10 23:51
just to explain. the value of outDir should be passed to the compiler as the realized value of "$(ProjectDir)\bin". with #4109 this is not happening.

@NoelAbrahams is this a new issue? we believe this has been broken in VS2015 prereleases as well.

**Comment by NoelAbrahams** [comment] 2015-08-11 00:06
@mhegazy, compile-on-save only started working after 1.5.4, so I can't say.

**Comment by mhegazy** [comment] 2015-08-11 00:16
thanks @NoelAbrahams

**Comment by NoelAbrahams** [comment] 2015-08-11 08:50
@sheetalkamat,

I'm not entirely sure that this issue is an exact duplicate of #4109. The point is things work normally when selecting Project > Build. It only fails on compile-on-save. 

Furthermore, I currently don't have any macros in the output path. It's set simply as `"bin"`.

**Comment by danquirk** [comment] 2015-08-11 17:54
Re-opening for further investigation.

**Comment by sheetalkamat** [comment] 2015-08-11 18:46
The issue here is that just setting it as bin - during build it will change that to (ProjectOutputPath)/bin but in compile on save - compiler gets it as bin and hence resulting in full paths.

**Comment by NoelAbrahams** [comment] 2015-08-11 18:49
@sheetalkamat, thanks that makes sense. I think the title for #4109 should be changed to reflect the fact that it is only a problem with compile-on-save.

**Comment by paulvanbrenk** [comment] 2015-08-17 21:11
The bugs are related, but it's a different issue.. re-opening.

**Comment by paulvanbrenk** [comment] 2015-08-17 21:11
https://github.com/Microsoft/TypeScript/issues/4252

**Comment by paulvanbrenk** [comment] 2015-08-19 20:22
@sheetalkamat there is an issue in the emit in the script side. The compile doesn't hand an expanded path to the 'outdir' argument either.

**Comment by sheetalkamat** [comment] 2015-08-20 19:27
@paulvanbrenk : Language service implementation of getCurrentDirectory is to return empty string but it should be project directory instead. That's what msbuild task does when asked for current directory. Assigning this bug back to you to fix.

**Comment by paulvanbrenk** [comment] 2015-08-21 20:53
This should be in the next release of TS for Visual Studio 2015.

**Closed** 2015-08-21 21:19 UTC
Labels: Bug, Fixed, Visual Studio
