### ISSUE TITLE
Suggestion: Index signatures that exclude certain names

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#36782] opened 2020-02-13 18:39 UTC
## Search Terms

index signatures, else, negation

## Suggestion

Most immediately inspired by https://github.com/mui-org/material-ui/blob/01b8b09fd6a28d6092ad0b192305ebe8e11c97ea/packages/material-ui-styles/src/withStyles/withStyles.d.ts#L38.  The goal is to say that "this type contains all the properties of the base type and _for any other property name_ a `CreateCSSProperties` will be returned".

I can imagine implementing this as either an "anything else" signature or as an explicit/computed list of excluded names (the added flexibility of which may or may not be desirable).

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by amcasey** [comment] 2020-02-13 18:39
I've previously discussed this with @RyanCavanaugh

**Comment by jcalz** [comment] 2020-02-14 15:32
Duplicate of #17867

**Closed** 2020-02-24 18:00 UTC
Labels: Duplicate
