### ISSUE TITLE
Promise chain syntax in ES3

### ISSUE THREAD

**Issue by grofit** [Microsoft/TypeScript#6608] opened 2016-01-25 10:15 UTC
First of all I am not sure if this is really a valid issue, as I am not sure if it is the responsibility of typescript but I have an issue with ES3 output.

In ES3 apparently you cannot do 

```
Promise.resolve(...)
.then(...)
.catch(...);
```

you have to do 

```
Promise.resolve(...)
["then"](...)
["catch"](...);
```

However when targetting ES3 TS does not seem to notice this and lets it through, again I am not entirely sure if this is legit etc but I have spent ages tracking down an issue and it seems that ES3 does not support chaining like shown

should this be added as an issue or is this not really TS' responsibility?

Here is a related question on SO:
http://stackoverflow.com/questions/23105089/angular-q-catch-method-fails-in-ie8

**Comment by grofit** [comment] 2016-01-28 20:36
Also I am not entirely sure if this is down to ES3 not allowing keywords as properties so it may just be that it needs to wrap `catch`, as the then syntax seems to work ok so that SO article may not be 100% accurate, but the catch bit is definitely an issue.

**Comment by mhegazy** [comment] 2016-01-28 20:59
looks like a duplicate of #2296. same underlying issue, the compiler does not rewrite reserved words as property access.

**Closed** 2016-01-28 20:59 UTC
Labels: Bug, Duplicate
