### ISSUE TITLE
TSX cannot compile React's Stateless Components

### ISSUE THREAD

**Issue by pdeva** [Microsoft/TypeScript#6353] opened 2016-01-05 01:29 UTC
Using Typescript 1.7.3.

Here is some sample code:

```
var MainMenu:React.StatelessComponent<{}> = (props)=>(<div>
	<h3>Main Menu</h3>
</div>);

var App:React.StatelessComponent<{children}> = ({children}) => (
	<div >
		<MainMenu/>
	</div>
);
```

The line containing `<MainMenu/>` inside `App` will throw this error msg:

```
Error:(5, 3) TS2605: JSX element type 'ReactElement<any>' is not a constructor function for JSX elements.
 Property 'render' is missing in type 'ReactElement<any>'.
```

At first I thought this was #6349 but even assigning a type to props in `MainMenu` doesnt help.

**Comment by RyanCavanaugh** [comment] 2016-01-05 01:30
I believe this is a duplicate of #6349?

**Comment by pdeva** [comment] 2016-01-05 01:32
as i mentioned, it isnt.
so i do this:

```

So even if i do this:

```
```
// added type to props
var MainMenu:React.StatelessComponent<{name:string}> = (props:{name:string})=>(<div>
	<h3>Main Menu</h3>
</div>);
```

it still throws the same error when referenced inside `App`

**Comment by RyanCavanaugh** [comment] 2016-01-12 23:41
Fixed in `master`

**Closed by RyanCavanaugh** 2016-01-12 23:41 UTC
Labels: Bug, Fixed
