### ISSUE TITLE
There was something wrong about compile a typescript file with code comments at the end

### ISSUE THREAD

**Issue by wxqqh** [Microsoft/TypeScript#2789] opened 2015-04-16 05:13 UTC
I wrote a typescript file like this:
```typescript
// source to typescript
var Test = {};
export = Test;

/**
some infomation about this module
*/
```

when i run commond `tsc --module commonjs test.ts`, the javascript file was

```javascript
/**
 * @fileOverview ...
 */
// source to typescript
var Test = {};
module.exports = Test;
/**
some other infomation about this module
/**
 * @fileOverview ...
 */
// source to typescript
var Test = {};
export = Test;

/**
some other infomation about this module
 
```

of course, Syntax error
```
D:\Users\wxq\test.js:14
export = Test;
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
There will be such a problem in typescript.org [playground](http://www.typescriptlang.org/Playground#src=%2F**%0D%0A%20*%20%40fileOverview%20...%0D%0A%20*%2F%0D%0A%2F%2F%20source%20to%20typescript%0D%0Avar%20Test%20%3D%20%7B%7D%3B%0D%0Aexport%20%3D%20Test%3B%0D%0A%0D%0A%2F**%0D%0Asome%20other%20infomation%20about%20this%20module%0D%0A*%2F)

But i just want to write some msgs at the end of the file.

If there is no problem by [using `//`](http://www.typescriptlang.org/Playground#src=%2F**%0D%0A%20*%20%40fileOverview%20...%0D%0A%20*%2F%0D%0A%2F%2F%20source%20to%20typescript%0D%0Avar%20Test%20%3D%20%7B%7D%3B%0D%0Aexport%20%3D%20Test%3B%0D%0A%0D%0A%2F%2Fsome%20other%20infomation%20about%20this%20module%0D%0A), or move the comments at the end [to top](http://www.typescriptlang.org/Playground#src=%2F**%0D%0A%20*%20%40fileOverview%20...%0D%0A%20*%2F%0D%0A%2F%2F%20source%20to%20typescript%0D%0A%2F**%0D%0Asome%20other%20infomation%20about%20this%20module%0D%0A*%2F%0D%0Avar%20Test%20%3D%20%7B%7D%3B%0D%0Aexport%20%3D%20Test%3B%0D%0A%0D%0A)

**Comment by DanielRosenwasser** [comment] 2015-04-16 05:59
This is a duplicate of #1714, which we've since fixed. TypeScript 1.4.2, and TypeScript 1.5-alpha, should both have the fix.

**Closed by DanielRosenwasser** 2015-04-16 05:59 UTC
