### ISSUE TITLE
SystemJS transformer use outdated information leads to wrong result

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#39608] opened 2020-07-15 10:10 UTC
**TypeScript Version:**  4.0.0-dev.20200715

**Search Terms:**

**Code**

Dependency:

> npm i @magic-works/ttypescript-browser-like-import-transformer

```ts
const ts = require('typescript')
const tf = require('@magic-works/ttypescript-browser-like-import-transformer/cjs/node').default
const sourceCode = `
import { GetContext } from '@holoflows/kit/es'
GetContext() === 'content'
`
const config = {
    importHelpers: '/ttsclib.js',
    rules: {
        '/(.+)/': {
            type: 'umd',
            target: '__deps__.default',
        },
    },
}
function halfCorrect() {
    const out = ts.transpileModule(sourceCode, {
        compilerOptions: {
            target: ts.ScriptTarget.ESNext,
            module: ts.ModuleKind.ESNext,
        },
        transformers: {
            before: [tf({}, config)],
        },
    }).outputText
    console.log('Middle result\n', out)
    const out2 = ts.transpileModule(out, {
        compilerOptions: {
            target: ts.ScriptTarget.ESNext,
            module: ts.ModuleKind.System,
        },
    }).outputText
    return out2
}
function wrong() {
    const out = ts.transpileModule(sourceCode, {
        compilerOptions: {
            target: ts.ScriptTarget.ESNext,
            module: ts.ModuleKind.System,
        },
        transformers: {
            before: [tf({}, config)],
        },
    }).outputText
    return out
}

console.log(halfCorrect(), wrong())
```

**Expected behavior:**

```js
System.register(["/ttsclib.js"], function (exports_1, context_1) {
    "use strict";
    var ttsclib_js_1;
    var __moduleName = context_1 && context_1.id;
    return {
        setters: [
            function (ttsclib_js_1_1) {
                ttsclib_js_1 = ttsclib_js_1_1;
            }
        ],
        execute: function () {
            const GetContext = ttsclib_js_1.__UMDBindCheck(globalThis["__deps__.default"], ["GetContext"], "@holoflows/kit/es", "globalThis.__deps__.default", false).GetContext;
            GetContext() === 'content';
        }
    };
});
```

**Actual behavior:**

Wrong result: (Notice the "es_1" part, which make the output invalid).
```js
System.register(["/ttsclib.js"], function (exports_1, context_1) {
    "use strict";
    var GetContext, ttsclib_js_1;
    var __moduleName = context_1 && context_1.id;
    return {
        setters: [
            function (ttsclib_js_1_1) {
                ttsclib_js_1 = ttsclib_js_1_1;
            }
        ],
        execute: function () {
            es_1.GetContext = __UMDBindCheck(globalThis["__deps__.default"], ["GetContext"], "@holoflows/kit/es", "globalThis.__deps__.default", false).GetContext;
            es_1.GetContext() === 'content';
        }
    };
});
```

If I split it into two steps, (see the `halfCorrect` function in my reproduction), the result becomes:

It's can run correctly now but still not correct. the `GetContext` should be defined in the `execute` function, not hoisted to the top level.

```js
System.register(["/ttsclib.js"], function (exports_1, context_1) {
    "use strict";
    var GetContext, ttsclib_js_1;
    var __moduleName = context_1 && context_1.id;
    return {
        setters: [
            function (ttsclib_js_1_1) {
                ttsclib_js_1 = ttsclib_js_1_1;
            }
        ],
        execute: function () {
            GetContext = ttsclib_js_1.__UMDBindCheck(globalThis["__deps__.default"], ["GetContext"], "@holoflows/kit/es", "globalThis.__deps__.default", false).GetContext;
            GetContext() === 'content';
        }
    };
});
```

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment] 2020-07-15 16:38
If I run this without your transformer in there, I get something that looks like the "expected" result minus the magic-works changes. This doesn't seem like a TypeScript bug?

**Comment by Jack-Works** [comment] 2020-07-15 16:47
After running my transformer, the import statement is removed, but in the incoming SystemJS transform, it grab the 
"es_1" from somewhere.

I guess the SystemJS transformer still think the "GetContext" identifier is imported from other module instead of a local variable.

If I make it into text and let ts re-parse it, (in the halfCorrect), the problem gone. So I think there're some information or cache on the Identifier or SourceFile object becomes invalid after the transformer runs, and SystemJS transformer read the invalid info out then leads to the wrong emit.

**Comment by RyanCavanaugh** [comment] 2022-02-04 21:49
Resolving as external since we don't have a repro that doesn't involve a third-party transformer. Please open a new issue if this is reproducable with just TS components.

**Closed by RyanCavanaugh** 2022-02-04 21:49 UTC
Labels: External
