### ISSUE TITLE
Narrowing of mapped types fails

### ISSUE THREAD

**Issue by erik-kallen** [microsoft/TypeScript#50504] opened 2022-08-29 08:54 UTC
# Bug Report

Sometimes narrowing of discriminated unions fails with mapped types. See the attached playground

### 🔎 Search Terms

narrowing mapped types

### 🕗 Version & Regression Information

Happens in latest. don't know about other versions.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDeUCGAuKByVWDcUARpgHYCuAtoRAE4EAepl1NUAvlAD7JqZaH4oAY0wBnYDQCWJAOYMmVWgTYAoFaEhQAcgHsAGgB4AKgD4EUAPIVJwYwBps9LCbxqA9G6gB1HTQDWomiBEPSQQsAQACYqAGZkJOGSOiRQMQCMABRgmDAAlMgqUFCiAO42QgAWUFkAdKj5SIVFwqii0DhY6E3NwsmiOgA2EDUDOjK1hLmuPUWENBCoftPNQq3tAl0zvST9QyNjtUJT3c1zC0tNqqoqHlAAEq1QGtC0NL7BAG4QKcAVOmQyKq-WjQSSBEg6KDzVrJVK+KA2WLxRKwmIAJiymF0hhgJgaTVK5SqtXqBR6qza2FwmxmQj6g2Go3GYBqk2WPTOi3ZLUp-E6JyKdJ2DP2zJqR25s2hFyKVxUQA

### 💻 Code

```ts
type A = { a: 'a'; b: number; x: number } | { a: 'b'; c: string; x: number; }

type NoX<T> = Omit<T, 'x'>;

// Works as expected
function f1(p: A) {
  switch (p.a) {
    case 'a':
      console.log(p.b);
      break;
    case 'b':
      console.log(p.c);
      break;
  }
}

// Has type errors even though there is no reason for it
function f2(p: NoX<A>) {
  switch (p.a) {
    case 'a':
      console.log(p.b);
      break;
    case 'b':
      console.log(p.c);
      break;
  }
}
```

### 🙁 Actual behavior

TypeScript does not realize that the member `p.b` exists if `p.a === 'a'` in the function `f2`

### 🙂 Expected behavior

The function `f2` should typechek without errors, since it does not in any way touch or care about the removed member `x`.

**Comment by whzx5byb** [comment] 2022-08-29 09:12
`p` is narrowed only when it's type is a discriminated union. `A` is, but `Omit<A, 'x'>` is not.

To produce your expected behavior you need a "distributive" omit type to produce a discrinimated union result:
```ts
type DistributiveOmit<T, K extends string | number | symbol> = T extends unknown ? Omit<T, K> : never;
```

**Comment by erik-kallen** [comment] 2022-08-29 10:32
Then perhaps this should be considered a feature request to make `Omit<A, 'x'>` stay a discriminated union if `A` is one.

The suggested hack is way out of reach for the regular devleoper.

**Comment by jcalz** [comment] 2022-08-29 11:43
Duplicate of #31501

**Closed** 2022-09-05 18:00 UTC
Labels: Duplicate
