### ISSUE TITLE
Auto import suggests different paths based on if any import is exported in parent index.ts

### ISSUE THREAD

**Issue by JonWallsten** [microsoft/TypeScript#46753] opened 2021-11-09 16:44 UTC
Issue Type: <b>Bug</b>

Auto import in VS Code suggests different import paths for export from the same source file if any of the exports are re-exported in for example the library's entry point. When working with our library we want to import from the source file in the library and not the entry point exposing thing for consumers. We use project-relative as Import Module Specifier since we have a monorepo using paths. But we have tried every setting without luck.
This is relatively new behavior, but I can't say exactly when it started to occur.

![image](https://user-images.githubusercontent.com/5993909/140967143-382470c9-6b23-4a93-828b-c6cc22915d96.png)
![image](https://user-images.githubusercontent.com/5993909/140967810-1d4dc5e7-c0e4-4059-a3ca-1e6b48a1a06a.png)
![image](https://user-images.githubusercontent.com/5993909/140967819-000a1864-2112-4044-b576-26eee7f459c3.png)
![image](https://user-images.githubusercontent.com/5993909/140967938-566079fc-2342-42cf-8677-8212372c7dd4.png)
![image](https://user-images.githubusercontent.com/5993909/140968033-6f09136b-3711-43fc-94d8-edbb0fbb6bc6.png)

Repro:
https://github.com/JonWallsten/vscode-repro
1. npm i
2. Open ./lib/utils.ts in VSCode
3. Remove imports
4. Put cursor after double and use ctrl+space to show auto import suggestion (it will be "..")
5. Put cursor behind power and use ctrl+space to show auto import suggestion (it will be "./number") 

We are not interested in consuming our own entry point and would like the imports to be the source file and not the entry point since it's for external consumer.

VS Code version: Code - Insiders 1.63.0-insider (b614fb5db84b3ac07fc3e8b12c69c1dd581924ce, 2021-11-09T10:02:27.095Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (17.47GB free)|
|Process Argv|--crash-reporter-id fc1c87ea-0388-48f3-b9dd-ecad6ea37b51|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|13.0.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.6.1
vscode-npm-script|eg2|0.3.23
docthis|oou|0.8.2
vscode-versionlens|pfl|1.0.9
vscode-scss-formatter|sib|2.3.2
es6-string-html|Tob|2.11.0
vscode-icons|vsc|11.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30382699
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedc:30350118
pythonvspyt187:30365360
pydsgst2:30361790
vsaa593cf:30376535
vsc1dsc:30394499

```

</details>

**Comment by andrewbranch** [comment] 2021-11-09 22:35
Duplicate of #45953

**Comment by JonWallsten** [comment] 2021-11-10 06:50
@andrewbranch 
I started to dig around a bit. This is from 4.3.5 (latest VSCode Insiders) mentioned in #45953:
![image](https://user-images.githubusercontent.com/5993909/141063783-fb9524d5-ad3b-464e-9a9d-d4f5d2aee86b.png)
![image](https://user-images.githubusercontent.com/5993909/141063786-414b8d7a-68e6-496c-af93-ab98ac95fea3.png)
![image](https://user-images.githubusercontent.com/5993909/141064029-2b4528bc-50b5-43a0-becf-e5484b48196d.png)

It shows the wrong path in the auto import suggestion but gets the correct path when I chose it.

**Comment by JonWallsten** [comment] 2021-11-10 06:59
It broke in **typescript@4.4.0-dev.20210626**

**Comment by JonWallsten** [comment] 2021-11-10 07:03
@andrewbranch Probably this commit: 
**Resolve module specifiers for auto imports in completion list**
https://github.com/microsoft/TypeScript/commit/328e888a9d0a11952f4ff949848d4336bce91b18

**Comment by JonWallsten** [comment] 2021-11-10 07:44
I appreciate that it's hard to figure out what to do, because it's impossible to know the users intentions. One solution could be to either have an option for or always also show the "source file path" when it's reexported. I think it was like that before:
![image](https://user-images.githubusercontent.com/5993909/141068025-f69d0bf3-e034-40bd-977c-e23566955cee.png)
It would at least give a choice to the user.

Another solution could be to have an option for or always ignoring re-exports from the entry point or all index.ts (or all re-exports and always you source file).
That entry point at least is most likely for consumers of the package, and not to be used internally. 
I'm conflicted about other nested index.ts files in the project. It could be a case where you have a utils/index.ts to expose utils for your own needs, but auto imports removes the need for that. I guess it also messes with tree shaking.
But if it's about all or nothing, I would be glad to have the option to always use the source file when importing files locally in a package.

**Closed** 2021-11-12 18:00 UTC
Labels: Duplicate
