### ISSUE TITLE
Stacktrace does not work on "spaced" filename

### ISSUE THREAD

**Issue by Den368** [microsoft/TypeScript#46307] opened 2021-10-11 13:35 UTC
# Bug Report

The source-map doesn't trace to the original `.ts` file but to a `.js` file, when the filename is named with spaces.
When there is no space in the `.ts` filename, the source-map does trace to the original `.ts` file.
screenshot attached:
![image](https://user-images.githubusercontent.com/19152348/136797378-21e0009e-e7e2-449e-948a-6f6df3f36419.png)

I've created a small minimal example to reproduce the bug.
https://github.com/Den368/typescript-filename-bug

### 🔎 Search Terms

github open/closed issues. 

### 🕗 Version & Regression Information

I'm using version ^4.2.4 (in `package-lock.json` - 4.4.3).
however, it might also be in all of the previous versions.

### ⏯ Playground Link

not relevant

### 💻 Code

same code for `t1.ts` and `t 1.ts` file.
```ts
type SomeType = {
    something: string;
};

const someType: SomeType = { something: "something" };
console.log("someType", someType);
const stack = new Error().stack;
console.log("stack", stack);
console.trace();
```

### 🙁 Actual behavior

```
    at Object.<anonymous> (C:\repos\github\nodetest\build\t 1.js:4:17)
```

### 🙂 Expected behavior

```
    at Object.<anonymous> (C:\repos\github\nodetest\src\t 1.ts:7:15)
```

**Comment by gabritto** [comment] 2022-01-25 20:53
Hi, I'm trying to reproduce this issue and, when I run the examples without relying on `source-map-support/register`, the source maps and stack traces seem to be the same and have the right behavior to me. I might be missing something, so could you help me understand how this is an issue with the source maps the typescript compiler generates, and not an error in `source-map-support` itself?

**Comment by gabritto** [comment] 2023-02-02 00:38
Closing this because I couldn't repro it and haven't received more feedback about it.

**Closed by gabritto** 2023-02-02 00:38 UTC
Labels: Bug, Rescheduled
