### ISSUE TITLE
Incorrect inferred return type when returning object literal from lambda bound to generic parameter

### ISSUE THREAD

**Issue by russpowers** [Microsoft/TypeScript#5487] opened 2015-11-01 21:28 UTC
When passing a function as a generic type T, the compiler correctly infers the return type when passing a previously declared function, but not when the same function is passed as an inline lambda.  This seems to only happens with object literals.  Classes and builtin return types are inferred properly.

``` TypeScript
function wrapper<T>(fn: T): T { return fn };

var fn = function(x: number) { return { x } };

// Correct: type of fnWrapper is (x: number) => { x: number }
var fnWrapper = wrapper(fn);

// Incorrect: type of inlineWrapper is (x: number) => any 
var inlineWrapper = wrapper(function(x: number) { return { x } });
```

**Comment by sandersn** [comment] 2016-03-02 18:02
I guess that function return type inference (maybe kicked off by contextual typing of the object literal?) interferes with fixing the type parameters.

**Comment by sandersn** [comment] 2016-03-04 23:06
Unfortunately, this is a real circularity in the contextual typing algorithm:

1. To find the return type of the inline function in the call to `wrapper`, the compiler looks at the type of each `return` statement.
2. To find the type of the `return { x }` statement, the compiler first checks the contextual type of `{ x }`.
3. To find the contextual type of `{ x }`, the compiler checks the contextual type of the containing statement, then the contextual return type of the containing function.
4. To find the contextual return type of the containing function, the compiler checks its return type. At this point, circularity detection notices that we started checking the return type of the function at (1) and gives up on finding the contextual type.
5. It returns `unknownType` to (3) and records the circularity for when the compiler gets back to (1).

The funny part is that after the circularity is detected, the compiler can get the type of the object literal in `checkObjectLiteral` *without* a contextual type -- that's why `var fn = function ...` works. But the circularity detection back at (1) throws this result away and returns `any` instead.

I'm not sure if the circularity detection that throws away the result is correct. I'll look at that next.

**Comment by sandersn** [comment] 2016-03-04 23:37
@ahejlsberg, in `getReturnTypeOfSignature`, if `popTypeResolution` returns false, then it always ignores the type found earlier in the function and just uses `any`, even if the previous type turns out to be correct as in this case. Is this correct when the circularity arises from contextual typing like it does in this case?

**Comment by kitsonk** [comment] 2017-08-28 15:11
I came across what I believe this issue is today, where literals could be contextually inferred, but don't seem to be... Even more surprising, is where they appear to be inferred _contextually_ they suddenly widen without implicit types.  The real world use case was using `Promise.resolve()` to return a literal value.  Here is the example in the [playground](http://www.typescriptlang.org/play/#src=function%20truePromise()%3A%20Promise%3Ctrue%3E%20%7B%0A%20%20%20%20return%20Promise.resolve(true)%3B%20%2F%2F%20Type%20'boolean'%20is%20not%20assignable%20to%20type%20'true'.%0A%7D%0A%0Ainterface%20Wrap%3CT%3E%20%7B%0A%20%20%20%20value%3A%20T%3B%0A%7D%0A%0Afunction%20wrap%3CT%3E(value%3A%20T)%3A%20Wrap%3CT%3E%20%7B%0A%20%20%20%20return%20%7B%20value%20%7D%3B%0A%7D%0A%0Afunction%20wrappedFoo()%3A%20Wrap%3C'foo'%3E%20%7B%0A%20%20%20%20return%20wrap('foo')%3B%20%2F%2F%20Type%20'string'%20is%20not%20assignable%20to%20type%20'%22foo%22'.%0A%7D%0A%0Afunction%20wrappedBar()%3A%20Wrap%3C'bar'%3E%20%7B%0A%20%20%20%20const%20value%20%3D%20'bar'%3B%20%2F%2F%20const%20value%3A%20%22bar%22%0A%20%20%20%20return%20wrap(value)%3B%20%2F%2F%20Type%20'string'%20is%20not%20assignable%20to%20type%20'%22bar%22'.%0A%7D%0A%0Afunction%20wrappedBaz()%3A%20Wrap%3C'baz'%3E%20%7B%0A%20%20%20%20const%20value%3A%20'baz'%20%3D%20'baz'%3B%0A%20%20%20%20return%20wrap(value)%3B%0A%7D%0A#src=function%20truePromise()%3A%20Promise%3Ctrue%3E%20%7B%0A%20%20%20%20return%20Promise.resolve(true)%3B%20%2F%2F%20Type%20'boolean'%20is%20not%20assignable%20to%20type%20'true'.%0A%7D%0A%0Ainterface%20Wrap%3CT%3E%20%7B%0A%20%20%20%20value%3A%20T%3B%0A%7D%0A%0Afunction%20wrap%3CT%3E(value%3A%20T)%3A%20Wrap%3CT%3E%20%7B%0A%20%20%20%20return%20%7B%20value%20%7D%3B%0A%7D%0A%0Afunction%20wrappedFoo()%3A%20Wrap%3C'foo'%3E%20%7B%0A%20%20%20%20return%20wrap('foo')%3B%20%2F%2F%20Type%20'string'%20is%20not%20assignable%20to%20type%20'%22foo%22'.%0A%7D%0A%0Afunction%20wrapBar(value%3A%20'bar')%3A%20Wrap%3C'bar'%3E%20%7B%0A%20%20%20%20return%20%7B%20value%20%7D%3B%0A%7D%0A%0Afunction%20wrappedBar()%3A%20Wrap%3C'bar'%3E%20%7B%0A%20%20%20%20const%20value%20%3D%20'bar'%3B%20%2F%2F%20const%20value%3A%20%22bar%22%0A%20%20%20%20const%20inferred%20%3D%20wrapBar(value)%3B%20%2F%2F%20const%20inferred%3A%20Wrap%3C%22bar%22%3E%0A%20%20%20%20return%20wrap(value)%3B%20%2F%2F%20Type%20'string'%20is%20not%20assignable%20to%20type%20'%22bar%22'.%20%3F!%3F!%3F!%0A%7D%0A%0Afunction%20wrappedBaz()%3A%20Wrap%3C'baz'%3E%20%7B%0A%20%20%20%20const%20value%3A%20'baz'%20%3D%20'baz'%3B%0A%20%20%20%20return%20wrap(value)%3B%0A%7D%0A#src=function%20truePromise()%3A%20Promise%3Ctrue%3E%20%7B%0A%20%20%20%20return%20Promise.resolve(true)%3B%20%2F%2F%20Type%20'boolean'%20is%20not%20assignable%20to%20type%20'true'.%0A%7D%0A%0Ainterface%20Wrap%3CT%3E%20%7B%0A%20%20%20%20value%3A%20T%3B%0A%7D%0A%0Afunction%20wrap%3CT%3E(value%3A%20T)%3A%20Wrap%3CT%3E%20%7B%0A%20%20%20%20return%20%7B%20value%20%7D%3B%0A%7D%0A%0Afunction%20wrappedFoo()%3A%20Wrap%3C'foo'%3E%20%7B%0A%20%20%20%20return%20wrap('foo')%3B%20%2F%2F%20Type%20'string'%20is%20not%20assignable%20to%20type%20'%22foo%22'.%0A%7D%0A%0Afunction%20wrapBar(value%3A%20'bar')%3A%20Wrap%3C'bar'%3E%20%7B%0A%20%20%20%20return%20%7B%20value%20%7D%3B%0A%7D%0A%0Afunction%20wrappedBar()%3A%20Wrap%3C'bar'%3E%20%7B%0A%20%20%20%20const%20value%20%3D%20'bar'%3B%20%2F%2F%20const%20value%3A%20%22bar%22%0A%20%20%20%20const%20inferred%20%3D%20wrapBar(value)%3B%20%2F%2F%20const%20inferred%3A%20Wrap%3C%22bar%22%3E%0A%20%20%20%20const%20literal%20%3D%20wrapBar('bar')%3B%20%2F%2F%20no%20error!%0A%20%20%20%20const%20value2%3A%20string%20%3D%20'bar'%3B%0A%20%20%20%20const%20literal2%20%3D%20wrapBar(value2)%3B%20%2F%2F%20Argument%20of%20type%20'string'%20is%20not%20assignable%20to%20parameter%20of%20type%20'%22bar%22'.%0A%20%20%20%20return%20wrap(value)%3B%20%2F%2F%20Type%20'string'%20is%20not%20assignable%20to%20type%20'%22bar%22'.%20%3F!%3F!%3F!%0A%7D%0A%0Afunction%20wrappedBaz()%3A%20Wrap%3C'baz'%3E%20%7B%0A%20%20%20%20const%20value%3A%20'baz'%20%3D%20'baz'%3B%0A%20%20%20%20return%20wrap(value)%3B%0A%7D%0A)

```ts
function truePromise(): Promise<true> {
    return Promise.resolve(true); // Type 'boolean' is not assignable to type 'true'.
}

interface Wrap<T> {
    value: T;
}

function wrap<T>(value: T): Wrap<T> {
    return { value };
}

function wrappedFoo(): Wrap<'foo'> {
    return wrap('foo'); // Type 'string' is not assignable to type '"foo"'.
}

function wrapBar(value: 'bar'): Wrap<'bar'> {
    return { value };
}

function wrappedBar(): Wrap<'bar'> {
    const value = 'bar'; // const value: "bar"
    const inferred = wrapBar(value); // const inferred: Wrap<"bar">
    const literal = wrapBar('bar'); // no error!
    const value2: string = 'bar';
    const literal2 = wrapBar(value2); // Argument of type 'string' is not assignable to parameter of type '"bar"'.
    return wrap(value); // Type 'string' is not assignable to type '"bar"'. ?!?!?!
}

function wrappedBaz(): Wrap<'baz'> {
    const value: 'baz' = 'baz';
    return wrap(value);
}
```

The surprising one was `wrappedBar()` where the contextually inferred type gets widened when passed as an argument.  It only seems to widen when checking assignability to generics, in other situations, where the value could be assignable to the literal, it is treated as such.

**Comment by aleclarson** [comment] 2019-01-14 01:13
@kitsonk This issue might interest you: https://github.com/Microsoft/TypeScript/issues/10195

Here's the workaround for your example: ([playground][1])

The error for `wrapBar(value2)` is intended.

[1]: http://www.typescriptlang.org/play/#src=function%20truePromise()%20%7B%0A%20%20%20%20return%20Promise.resolve(true%20as%20true)%3B%20%2F%2F%20OK%0A%7D%0A%0Ainterface%20Wrap%3CT%3E%20%7B%0A%20%20%20%20value%3A%20T%3B%0A%7D%0A%0Afunction%20wrap%3CT%3E(value%3A%20T)%3A%20Wrap%3CT%3E%20%7B%0A%20%20%20%20return%20%7B%20value%20%7D%3B%0A%7D%0A%0Afunction%20wrappedFoo()%20%7B%0A%20%20%20%20return%20wrap('foo'%20as%20'foo')%3B%20%2F%2F%20OK%0A%7D%0A%0Afunction%20wrapBar(value%3A%20'bar')%3A%20Wrap%3C'bar'%3E%20%7B%0A%20%20%20%20return%20%7B%20value%20%7D%3B%0A%7D%0A%0Afunction%20wrappedBar()%3A%20Wrap%3C'bar'%3E%20%7B%0A%20%20%20%20const%20literal%20%3D%20wrapBar('bar')%3B%0A%0A%20%20%20%20const%20value%20%3D%20'bar'%20as%20'bar'%3B%0A%20%20%20%20const%20inferred%20%3D%20wrapBar(value)%3B%0A%20%20%20%20return%20wrap(value)%3B%20%2F%2F%20OK%0A%7D%0A%0Afunction%20wrappedBaz()%3A%20Wrap%3C'baz'%3E%20%7B%0A%20%20%20%20const%20value%3A%20'baz'%20%3D%20'baz'%3B%0A%20%20%20%20return%20wrap(value)%3B%0A%7D

**Comment by ahejlsberg** [comment] 2019-01-30 17:40
Closing as the bug no longer reproduces. We now infer the correct type.

**Closed by ahejlsberg** 2019-01-30 17:40 UTC
Labels: Bug
