### ISSUE TITLE
`Parameters<FnInterface>` return only last overload arguments type

### ISSUE THREAD

**Issue by iamolegga** [microsoft/TypeScript#34432] opened 2019-10-15 09:32 UTC
**TypeScript Version:**  3.7.x-dev.201xxxxx  ("nightly" on http://www.typescriptlang.org/play/)

**Search Terms:** 
typescript parameters of overloading function interface

**Code**

```ts
interface LogFn {
  // move lines oreder to see different behavior 
  (msg: string, ...args: any[]): void;
  (obj: object, msg?: string, ...args: any[]): void;
}

class Logger {
  private readonly logger!: LogFn;

  log(...args: Parameters<LogFn>) {
    this.logger(...args);
  }
}

const loggerInstance = new Logger();

loggerInstance.log('test');
                   ^^^^^^ Argument of type '"test"' is not assignable to parameter of type 'object'.(2345)
loggerInstance.log({});
```

**Expected behavior:**
`Parameters<FnInterface>` should return all types of arguments

**Actual behavior:**
`Parameters<FnInterface>` return only last overload arguments type

**Playground Link:** http://www.typescriptlang.org/play/?ts=Nightly&ssl=1&ssc=1&pln=19&pc=1#code/JYOwLgpgTgZghgYwgAgDIHsDmAxEyDeAUMsgPSnIC26AbigDagQDOy6UEAJtMmOsswgpOwGDGgRwyAEYQAFnBrB2yYsgAUlZpgBcAsFFCYANMgB0FuFEzM9cEAE8A2gF0AlHprpgnANxr1dGkAKz0g4IgEMFMtTAB+PWYDI1MLMysbO0dXD2QvH38AX0JCBHo4ZlYMTEweIhIAB0MaOEhkDjhOdBB6B2R6LFqoAEI9atx-NQHMdTSM22QABSs4SghIKGYAHnGQAD43AjUSMDlgZjNpodnLa2Y3fxJi4tLupP7B6ABJECT7JGQAF5kCAIAB3NCfKDqB4lK7fX5gf4QS5YdQAckgSXRsPhUB+fxASFRM3whVhQA

**Related Issues:**

**Comment by jack-williams** [comment] 2019-10-15 10:14
Duplicate of #29732

**Closed** 2019-10-17 18:00 UTC
Labels: Duplicate
