### ISSUE TITLE
Object keys written in Unicode (Cyrillic) with spaces inside them are breaking down into Unicode Entities

### ISSUE THREAD

**Issue by Eleseer** [microsoft/TypeScript#52015] opened 2022-12-24 13:00 UTC
# Bug Report

### 🔎 Search Terms

suggestion cyrillic unicode entities object key breaks

### 🕗 Version & Regression Information

- This is the behavior in all versions since v.3.8.3, prior to that (the least available version for playground is 3.3.3) the problem is non-existent. No related entries in FAQ were found.

### ⏯ Playground Link

[Last working version (3.7.5)](https://www.typescriptlang.org/play?ts=3.7.5#code/C4TwDgpgBAQghgJygXigbwFBW1A5IfhBABEEA4QQJhBBWEECEQXALijgDsQMBfDDUSKAMQHteU6LDgIkKlKIB4QYoVr0mrIA)
[First version where the problem was introduced (3.8.3)](https://www.typescriptlang.org/play?ts=3.8.3#code/C4TwDgpgBAQghgJygXigbwFBW1A5IfhBABEEA4QQJhBBWEECEQXALijgDsQMBfDDUSKAMQHteU6LDgIkKlKIB4QYoVr0mrIA)
[Most relevant version (Nightly 5.0.0-20221224)](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221224#code/C4TwDgpgBAQghgJygXigbwFBW1A5IfhBABEEA4QQJhBBWEECEQXALijgDsQMBfDDUSKAMQHteU6LDgIkKlKIB4QYoVr0mrIA)

### 💻 Code

Code on the most relevant version of Typescript.
```ts
// type of Bar, showing as expected

// type Bar = {
//     привет: any;
// }
type Bar = {
    'привет': any
}

// type of Foo, the 'привет мир' key breaks down

// type Foo = {
//     '\u043F\u0440\u0438\u0432\u0435\u0442 \u043C\u0438\u0440': any;
// }
type Foo = {
    'привет мир': any
}
```

Code on the last working version (3.7.5)
```ts
// type of Bar, showing as expected

// type Bar = {
//     привет: any;
// }
type Bar = {
    'привет': any
}

// type of Foo, showing as expected

// type Foo = {
//    'привет мир': any;
// }
type Foo = {
    'привет мир': any
}
```

### 🙁 Actual behavior

When using cyrillic object keys which contain spaces, the type information (when hovering your cursor over the type) breaks down the Unicode characters into their respective «Unicode Entities», which is confusing of what the actual value is.

### 🙂 Expected behavior

No Unicode characters are breaking down on the type information of a an object with a key containing Unicode characters and spaces, as it was prior to the version 3.8.3.

**Comment by MartinJohns** [comment] 2022-12-24 13:36
Duplicate of #36174.

**Closed** 2023-01-05 18:00 UTC
Labels: Duplicate
