### ISSUE TITLE
Why type/interface/class types does not extend explicitly Object class.

### ISSUE THREAD

**Issue by hadson172** [microsoft/TypeScript#39959] opened 2020-08-07 23:13 UTC
**TypeScript Version:**  3.9.7

**Search Terms:** types in typescript does not extend Object

**Code**

```ts
const o = {};
//no method completion from Object class in tsplayground, vscode, intellij
o.toString();
o.hasOwnProperty();

// always true
if(o instanceof Object) { 
//method completion from Object class in tsplayground, vscode, intellij
o.toString();
o.hasOwnProperty();
}

class MyClass {

} 
//no code completion
new MyClass().toString()

class MyClass2 extends Object {

}
//code completion present
new MyClass2().toString(); 

```

**Expected behavior:**  Typescript suggest methods from Object class. Almost all object in javascript are sub-type of Object class (with exception to Object.create(null) and those with replaced prototype during runtime).  I would expect that for almost every object the methods from Object class will be suggested for me.

**Actual behavior:** Typescript is prompting me about methods from Object class only if a will use explicit type annotation or extend Object class (in the interface or class or type).

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play?ts=4.0.0-beta#code/DYUwLgBAhhC8EG8C+BuAUFAdGA9gZTACcBLAOwHMAKASjTWIDNKYyBnMKUgYxBwYgDyAIwBWILmGqI0EWdGz4iZKtXRz5ACyisBAd1IAFQjgAOIQmACelAES4CJCjdVokEIA)

**Related Issues:**

**Comment by jack-williams** [comment] 2020-08-09 14:36
Duplicate of #14291.

**Closed** 2020-08-12 18:00 UTC
Labels: Duplicate
