### ISSUE TITLE
Unexpected "Object is possibly undefined" error

### ISSUE THREAD

**Issue by DashwoodIce9** [microsoft/TypeScript#53721] opened 2023-04-10 13:13 UTC
# Bug Report

Hi, I stumbled upon this weird behavior that I couldn't wrap my head around. I searched with "object is possibly undefined bug typescript github" on Google and went through the first 5-6 bugs but didn't find any which quite resembled this case. I am new to Typescript so it is entirely possible that this is expected behavior. If that's the case I apologize and humbly ask for an explanation. Thanks!

### 🔎 Search Terms

"Object is possibly undefined"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "[common-bugs-that-arent-bugs](https://github.com/Microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs)."

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.3#code/JYOwLgpgTgZghgYwgAgCoQM5gJLmvJZAbwCgBIAewAcxgKQ4AbABTijgFsB+ALmPLIBtANYQAnnyxRQAcwC6ksNJAyA3OQC+6jSRIJ6WZFEwBXRmD7osuSLEQoAvP0o06DFm059SZMgGlxAEY+ACIANSYTCECQgBpNeK1dYwwzMAA6alp6JlZ2DkEQgLEAJhC5ZCdwyIgy9SA)

### 💻 Code

```ts
interface TestInterface {
    optionalParam?: {
        [key: string]: string;
    };
}

const result: TestInterface = {
    optionalParam: {
        Key1: "Value1",
    },
};

result.optionalParam["Key2"] = "Value2"; // 'result.optionalParam' is possibly 'undefined'.
```

### 🙁 Actual behavior

`'result.optionalParam' is possibly 'undefined'` error on the last line.

### 🙂 Expected behavior

Code compiles without any errors. `optionalParam` is typed as though it can be `undefined` however, in the example above `result.optionalParam` is clearly defined. There is no code in between `result` initialization and `result.optionalParam` which could set it to `undefined`. So, this should've worked I think.

**Comment by MartinJohns** [comment] 2023-04-10 14:11
Duplicate of #50357.

**Comment by DashwoodIce9** [comment] 2023-04-12 17:33
Hi Martin, thanks for pointing me to the duplicate. I've read through that and #47920 several times over the past 2 days but I couldn't make sense of it. The discussion at #47920 is unfortunately a bit too complicated for me. Could you please let me know (or point me to) if this functionality should be implemented some other way and/or is this not supported by Typescript yet?

The comment at https://github.com/microsoft/TypeScript/issues/50357#issuecomment-1220602103 says to use -
```typescript
const anObject: Required<Pick<typeof anotherVar, LongListOfKeys>> = {
  // object initializer with keys from LongListOfKeys
}
```

But, what are `Required` and `Pick`? I didn't get that.

**Closed** 2023-04-14 18:00 UTC
Labels: Duplicate
