### ISSUE TITLE
Usage of const enum breaks file import

### ISSUE THREAD

**Issue by Spodii** [Microsoft/TypeScript#4110] opened 2015-07-31 19:24 UTC
TypeScript version: "TS6029: Version 1.5.3"

Using `const enum` can, at least in the case below, cause needed `require`d statements to get removed from the generated javascript.

Sample case:

```ts
/// file: main.ts
import foo = require('./foo');
console.log(foo.test());

/// file: foo.ts
class foo {
	public static test() { return "it works!"; }
}

module foo {
	export /*const*/ enum testEnum {
		a = 1,
	}
}

export = foo;

/// build & run
tsc --module commonjs main.ts foo.ts
node main.js
```

The sample above will work as expected, printing out "it works!". main.js will include the following:

```
var foo = require('./foo');
console.log(foo.test());
```

If you change `testEnum` to a const enum, the generated main.js will instead be the following, and fail at runtime:

```
console.log(foo.test());
```

**Comment by vladima** [comment] 2015-07-31 20:39
Dupe of #3938

**Closed by vladima** 2015-07-31 20:39 UTC
Labels: Bug, Duplicate
