### ISSUE TITLE
Type guards wrapped in lambda lose the guard type

### ISSUE THREAD

**Issue by jovdb** [Microsoft/TypeScript#21310] opened 2018-01-19 22:25 UTC
**TypeScript Version:**  2.7.0-dev.20180119

**Search Terms:** 
array guard lambda

**Code**
```ts
declare function isString(arg: any): arg is string;

var items: (number | string)[] = [];
var a = items.filter(isString); // a: string[]
var b = items.filter(i => isString(i)); // b: (string | number)[]
```
When guard is wrapped in a lambda, guard type is gone
Other example:
```ts
// Get non-empty strings
var c = items.filter(i => isString(i) && i.length > 0); // c: (string | number)[]
```

**Expected behavior:**
b: string[]

**Actual behavior:**
b: (string | number)[]

**Playground**
[link](https://www.typescriptlang.org/play/#src=declare%20function%20isString(arg%3A%20any)%3A%20arg%20is%20string%3B%0D%0A%20%20%20%0D%0Avar%20items%3A%20(number%20%7C%20string)%5B%5D%3B%0D%0Avar%20a%20%3D%20items.filter(isString)%3B%20%2F%2F%20a%3A%20string%5B%5D%0D%0Avar%20b%20%3D%20items.filter(i%20%3D%3E%20isString(i))%3B%20%2F%2F%20b%3A%20(string%20%7C%20number)%5B%5D)

**Related Issues:**
#18562

**Comment by mhegazy** [comment] 2018-01-19 23:32
Duplicate of https://github.com/Microsoft/TypeScript/issues/5101 and https://github.com/Microsoft/TypeScript/issues/20812

**Closed** 2018-02-05 18:28 UTC
Labels: Duplicate
