### ISSUE TITLE
checkjs doesn't allow type annotations with types from required modules

### ISSUE THREAD

**Issue by akdor1154** [Microsoft/TypeScript#18460] opened 2017-09-14 03:51 UTC
**TypeScript Version:**  2..5.2

**Code**

```
npm install --save-dev typescript @types/express
npm install --save express
```

tsconfig.json
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "allowJs": true, 
    "checkJs": true,
    "strict": true  
  }
}
```

test.js
```js
const localExpressName = require('express');
/**
 * @type {localExpressName.Application}
 */
let app;
```

**Expected behavior:**
`app` is typed as an express Application.

**Actual behavior:**
```
error TS2503: Cannot find namespace 'localExpressName'.
```
`app` is hence typed as `any`.

**Comment by DanielRosenwasser** [comment] 2017-09-14 08:30
Looks like a duplicate of #16489.

**Comment by akdor1154** [comment] 2017-09-15 06:35
does indeed, sorry.

**Closed** 2017-09-15 06:36 UTC
Labels: Duplicate
