### ISSUE TITLE
Return type is checked on `return` statements that are overwritten by a `finally` `return`

### ISSUE THREAD

**Issue by phryneas** [microsoft/TypeScript#55802] opened 2023-09-20 20:49 UTC
### 🔎 Search Terms

"finally", "return"

### 🕗 Version & Regression Information

I've checked this back to version 4.5 and it is the same in all versions.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.5.5#code/GYVwdgxgLglg9mABAMTnAFASgFyIIyIDeAUIolAE4CeRpZiA9A4jFIgM4AWcIANgCaIARgFNEABxEVgI6LxrAYYMVDiIKIqCApIAVAHdOAQygiAblN2JOUseyUQVNxAANFYI73kv1m7Un0YL0Q4Cwp9ClYxVjoyDS0dRAAidjgAW01OJQBzRBFedhEkugBfOndPeVp6XwSkPFLiEqA

### 💻 Code

```
function Foo(): 1 {
  try {
    // it should be perfectly fine to return *whatever* here since the `finally` return will overwrite it
    return "something else"
  }
  finally {
    return 1
  }
}
```

or, more practical, 

```
function Foo(): 1 {
  try {
    // this could be used as a "break out of the try block" statement and actually use the `return` value from the `finally` block
    return
  }
  finally {
    return 1
  }
}
```

### 🙁 Actual behavior

A type error on the `return` in the `try` block:

First example:

`Type '"something else"' is not assignable to type '1'.(2322)` 

Second example:

`Type 'undefined' is not assignable to type '1'.(2322)`

### 🙂 Expected behavior

This should not end up in a type error, since the `return` statement in the `try` block does not actually return a value from the function if there is also a non-conditional `return` statement in the `finally` block.

I get that the first example is weird, but the second example - using the `return` for flow control - could actually be used in real code bases.

**Comment by RyanCavanaugh** [comment] 2023-09-20 20:54
If you really want to do this, `return 0 as never`.

This isn't idiomatic JS and I don't think there's any upside to complicating the return value logic to support it -- we'd need to start considering things like *conditional* returns out of `finally`, etc.

**Comment by MartinJohns** [comment] 2023-09-20 20:55
Duplicate of #27454.

**Comment by phryneas** [comment] 2023-09-20 21:00
Seems like a valid workaround :) Thanks for the fast reply!
And yeah, I missed that duplicate - even though I searched through 5 pages of issues. I think I only looked through the open ones - apologies!

**Closed** 2023-09-20 21:01 UTC
Labels: Suggestion, Declined
