### ISSUE TITLE
[FEATURE REQUEST] "baseUrl" should update the paths in generated JavaScript

### ISSUE THREAD

**Issue by SamuraiJack** [Microsoft/TypeScript#22029] opened 2018-02-19 09:22 UTC
Hello,

The "baseUrl" option is awesome, as it removes the mess with `../../..`, but it keeps the "import" paths unchanged in generated JavaScript. I guess that was done to be compatible with "RequireJS" loader.

However, now, that browsers starts to support JS modules natively, this becomes an inconvenience.

Use case is simple:
1) Compile project
2) Open it in browser - kaboom, paths are wrong.

One will say that you need to use webpack for that, but why extra tool, which slows everything down? For quick coding, typescript is enough.

I guess there should be an additional config to configure this behavior.

**Comment by andy-ms** [comment] 2018-02-20 15:25
Duplicate of #21918 -- it's out of scope to change the meaning of the code.

**Comment by SamuraiJack** [comment] 2018-02-21 06:56
Hm.. Is it in scope to generate broken JS though? My point is simple:
- The project compiles fine, because of the "baseUrl" compiler config
- The generated JS is broken, because "baseUrl" does only half of its job.

**Comment by andy-ms** [comment] 2018-02-21 15:24
> The project compiles fine, because of the "baseUrl" compiler config

That option means you told the compiler those paths would work. Just like `declare var x: number;` is you promising the compiler that `x` will exist and be a number, setting `baseUrl` tells the compiler that your module loader works from that url.

**Comment by SamuraiJack** [comment] 2018-02-22 07:02
Not convincing for me. The decision about "baseUrl" should be reconsider, since browsers started to support ecma modules natively.

**Closed** 2018-03-08 17:07 UTC
Labels: Duplicate
