### ISSUE TITLE
`Set.has` might narrow the type of a variable if the Sets type doesn't totally overlap with the argument

### ISSUE THREAD

**Issue by wegry** [microsoft/TypeScript#52326] opened 2023-01-20 13:49 UTC
# Suggestion

`Set.has` should act as a guarantee that a type has been narrowed.

## 🔍 Search Terms

- type narrowing
- Set
- ts
- typescript

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

For something like 

```typescript
const validValues = new Set(['a', 'b', 'c'] as const)

const maybeValid: unknown = 'd'

if (validValues.has(maybeValid)) {
    console.log(maybeValid)
}
```

The validValues set is `'a'|'b'|'c'` but won't narrow string arguments to `Set.has`.

## 📃 Motivating Example

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAbgQwDYEsAmA1ZBXAphGAXhjFwHcYBlXKACgG0ByBRgGhkYCM2PhGBdGAgKhIUAJQAoSaOgwAtggCenXFlRoAXNjABrMCDJgiHNI2koAZjFqIN6vBAB0AC2G1FKtcnTjxMAG9JGBCYWRAkXCckEABzD2VVdV9JAF8gA

## 💻 Use Cases

One way this could be used is to guarantee that broad string input matches a DSL.

**Comment by jcalz** [comment] 2023-01-20 15:49
Duplicate of #13086

**Closed** 2023-01-23 17:05 UTC
Labels: Duplicate
