### ISSUE TITLE
When spread array into object literal, Returns a type containing unnecessary properties

### ISSUE THREAD

**Issue by GunseiKPaseri** [microsoft/TypeScript#52060] opened 2022-12-31 15:10 UTC
# Bug Report

### 🔎 Search Terms

Spread Syntax, Array into object literal

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about rest syntax.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/MYewdgzgLgBAHjAvDA2gIgIZoDQzQIxz2DQF0BYAKFEhABsBTAOjpAHMAKOASipuhgBPJDADeTCXAC+VAPSyYimAD0A-HIVKGcAA4NgUBgBMxKOAC4YYAK4BbfAwBOpS9EcBLMGykwGUYFQavrr6hibWYEYMAGaexnzgEPTMrJyCLAxeUAAWvJTySoVFakFFZRzaegbGMBFRsWDG3EA)

### 💻 Code

```ts
const x = ["a", "b", "c"]
console.log(x)
const y = {...x}
//    expected {[x: number]: string} etc, but got {[x: number]: string, length: number, toString(): string .....}

console.log(y.length) // undefined
//  expected undefined, but got number
```

### 🙁 Actual behavior

`y`(spread array into object literal) 's property type is same as Array<string>

### 🙂 Expected behavior

`y`(spread array into object literal) 's property has only array value.

**Comment by MartinJohns** [comment] 2022-12-31 15:41
Essentially a duplicate of #9726.

**Closed** 2023-01-05 18:00 UTC
Labels: Duplicate
