### ISSUE TITLE
Generic Tagged Template Literals

### ISSUE THREAD

**Issue by victorandree** [Microsoft/TypeScript#14517] opened 2017-03-07 19:14 UTC
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

[styled-components][styled-components] makes heavy use of tagged template literals to embed CSS directly in JavaScript/TypeScript. One construct is tagged CSS literals which can adapt based on props:

```javascript
css`
  color: ${ props => props.whiteColor ? 'white': 'black' }
`;
```

styled-components comes with TypeScript definitions built-in, and defines the `css` function interface like so ([full typings here][sc-typings]):

```typescript
export interface ThemedCssFunction<T> {
  (strings: TemplateStringsArray, ...interpolations: SimpleInterpolation[]): InterpolationValue[];
  <P>(strings: TemplateStringsArray, ...interpolations: Interpolation<ThemedStyledProps<P, T>>[]): FlattenInterpolation<ThemedStyledProps<P, T>>[];
}
```

When using the above, TypeScript's type checker will not be able to know that `props` in the interpolated functions contains a `whiteColor` key. I would have expected to be able to tell it by explicitly "calling" the tagged template literal function with my props interface (as I can with a normal function):

```typescript
interface Props {
  whiteColor: boolean;
}

css<Props>`
  color: ${ props => props.whiteColor ? 'white': 'black' }
`;
```

**Expected behavior:**
The above code works.

**Actual behavior:**
This is a syntax error in TypeScript 2.2.1: "Operator '>' cannot be applied to types 'boolean' and 'string'".

[sc-typings]: https://github.com/styled-components/styled-components/blob/master/typings/styled-components.d.ts
[styled-components]: https://github.com/styled-components/styled-components

**Comment by RyanCavanaugh** [comment] 2017-03-07 19:22
@DanielRosenwasser thoughts?

**Comment by mhegazy** [comment] 2017-03-07 19:23
Duplicate of https://github.com/Microsoft/TypeScript/issues/11947

**Closed** 2017-03-08 06:58 UTC
Labels: Duplicate
