### ISSUE TITLE
Conditional type inference regression in 4.2*

### ISSUE THREAD

**Issue by robertf224** [microsoft/TypeScript#43192] opened 2021-03-11 15:56 UTC
# Bug Report

### 🔎 Search Terms

"conditional type inference"

### 🕗 Version & Regression Information

This changed between versions 4.1.5 and 4.2.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgSQDEoBXBGAZzgG8AoOBuGKCMBbTAGwC4b7GBYTEICemXkhIBbAEZoA3PwEM2SYMLCdgE6XKiLljAOYlMAN3FxJshUrgBfRXYowIa3nUMr12ABY6bfTsBNWwYTChkbStdWwFHWjs9KBEPYMYXKEwAd2TUmMCDLxlOEmA8gL0ihgT7RIB6ACpG+ka4AEEjIyhgI0wYZCM4Lk4mXzwKYGw3ABM4LTNgUYBrYBEqAAoYcbh0UnIKAEpEFAhhuApBrTgSJAQ3JhEwYAA6VvraUEhYR+e4YjIMAA0ms4ABePgCADaHFQRmgIhOcFWIgg6AIAIOAF1eCi0Rj9pQYf1egisYp7FC8eiiISKOSGs1WnAABJLZ5QJhnNjYZZwNycRF7QFwWGkyLATboBBQFzzYCLTjHbb9YY9OA9ACOZB6c3Q0DGeC1ZRcwD1hORawobzgjQ+MCeeAASsBtTKzZiYABhEnwiUUAA8QLgoFQSBmVE9IJEAD5wZDGMS4QikdSCYD6bwAKIgZg4GBBgA0ltRNM9FCT4pEWLjoeA4aoakWnIA-FYFWg4LwxX6RBSqWt8bSMwzGS1bXAACqYVZUTDt01zCicdh4fHbPDDg4nVAYHB4GbAZ7hwb8pCG3YWlGbSbTcPyxXK3z9ZnZPCYCh8-WcgC0P5DFCTCgCAjIi85qIucAAAYAArsMsUEvAwADKZxQeWyEkDIkwFgAREIoiYLhcAAD5wPhPi+LhMZQSGDY3GAcByIM3DMp4bTKMwrDsFwaQTl4KjCJgYiVHEHHxAY4kZK47iQlJhjPDg-gFFUzLKAkE51La9qOv8dKYdhwAFsGdb0VGaxxhCniJj2KbIHALpurqno+sm-pBjGOJwHBvIBukDBbkStkpFihb+XAOZ5mERYlkO5aVr2NZ2DGFJOE045tAAUiQcrZFkYCqEMG7DDIECLEimDnsgu5YLguwGhAG6ctVaC1ZKcAbAgLyvA5PjwGALBgEcXIhrm9YzDadq0C1e51RhWE4QA8mAlBBqNYYRnpgLRnG1kMMKBy8PNhnGSltB1LQDp-AAsiIhDmNA5DAMdOHxi9RkBvhQliMRZEUUp1GKPU9QEEg6BoJESBFTsKKXhAUglWVeB-mMCBUONVAkIxzFQ9BX2Eb95GKX4uG0Q8k7IXAAAsLwAIwvAArExJDwFBTZoGT540wATC8ADMl26bd91mI9qDvcCoIQsLD2ROL+kLUZ60Y1tBwGThAbIODnJAnGbbBhIHZBILN13bLT0S8tlBvQrJ1W4G+PCURpFE5RgO0MDoPa5D0N4LDezw4j5Uo9saN0ZtWNMcAp5QY7P0u-9JOc0xjW+FOlM0-TTOVXMPP8x7IMwT0MAOqKbjoDlp5yBwOV4JbK1UGHABWOXwPOeUaJ2EQQLccwSwAhCbeAy6LcvPbbS0N9G8Yj2L48ZurRn28rZkT0vDea2Dna63A+tdu2zbyEAA)

### 💻 Code

```ts
export interface IFruits {
    tropical: {
        papaya: number;
        pineapple: number;
        guava: number;
    };

    stone: {
        peach: number;
        nectarine: number;
    };

    berry: {
        strawberry: number;
        blueberry: number;
    };
}

/**
 * Aggregating all the second level keys (the fruits) into a single union type.
 */
export type FruitKey = {
    [category in keyof IFruits]: keyof IFruits[category];
}[keyof IFruits];

/**
 * Helper to pick only fruit categories (first level) that are required for the requested fruit keys.
 */
type RequiredFruitCategories<K extends FruitKey> = {
    [category in keyof IFruits]: Extract<K, keyof IFruits[category]> extends never ? never : category;
}[keyof IFruits];


/**
 * Takes a nested slice of the IFruits interface depending on the fruit keys (second level) that
 * we ask for -- essentially a nested `Pick`.  So `FruitsSubset<"papaya" | "peach">` ends up being:
 * {
 *      tropical: {
 *          papaya: number;
 *      };
 *      stone: {
 *          peach: number;
 *      };
 * }
 */
type FruitsSubset<K extends FruitKey> = {
    [category in RequiredFruitCategories<K>]: Pick<
        IFruits[category],
        Extract<K, keyof IFruits[category]>
    >;
};

/**
 * Just wrapping the above in an interface for other interfaces (i.e. React props) to extend.
 */
interface FruitsSubsetOpts<K extends FruitKey> {
    fruits: FruitsSubset<K>;
}

type MyFavoriteFruitsSubset = FruitsSubset<"papaya" | "peach">;
// Inferring the key from above -- this ends up being `"papaya" | "peach"` on TS 4.1.5 but `never` on 4.2.3
type MyFavoriteFruitsSubsetKey = MyFavoriteFruitsSubset extends FruitsSubset<infer K> ? K : never;

type MyFavoriteFruitsSubsetOpts = FruitsSubsetOpts<"papaya" | "peach">;
// Inferring the key from above -- this ends up being `"papaya" | "peach"` on both TS 4.1.5 and 4.2.3
// Pretty confusing because FruitsSubsetOpts is just a wrapper around FruitsSubset!
type MyFavoriteFruitsSubsetOptsKey = MyFavoriteFruitsSubsetOpts extends FruitsSubsetOpts<infer K> ? K : never;
```

### 🙁 Actual behavior

`MyFavoriteFruitsSubsetKey` can be properly inferred on TS 4.1.5 but not on 4.2.3 (we tried migrating to 4.2.2 locally and this broke so the change in behavior is somewhere between 4.1.5 and 4.2.2) 

### 🙂 Expected behavior

`MyFavoriteFruitsSubsetKey` should be properly inferred on both versions.  Could be we're doing a thing we shouldn't be doing in the first place, but it's strange that it only kind of breaks and doesn't completely break.

**Comment by MartinJohns** [comment] 2021-03-11 16:04
You forgot to fill out the issue template. 🤔

**Comment by robertf224** [comment] 2021-03-11 16:06
ah sorry will edit

**Comment by ahejlsberg** [comment] 2021-03-29 18:42
This is an effect of #42284 and basically a duplicate of #42421.

Previously, the `MyFavoriteFruitsSubset` type alias would resolve to the exact same type identity as `FruitsSubset<"papaya" | "peach">`, and when printing back types in diagnostics and quick info, that's what we'd show. Now, we create a separate type identity for `MyFavoriteFruitsSubset` and preserve the alias when printing back the type. In the `MyFavoriteFruitsSubsetKey` conditional type this means we're no longer inferring from one instantiation of the `FruitsSubset<...>` type alias to another (where we can just infer between the type arguments). Rather, we're performing *structural* type inference between two mapped types, and, because the transformation is lossy, we can't produce an inference for `K`.

**Closed** 2021-03-31 20:00 UTC
Labels: Breaking Change, Working as Intended
