### ISSUE TITLE
Awaiting on a Promise<never> doesn't make the rest of the block unreachable

### ISSUE THREAD

**Issue by besfahbod** [microsoft/TypeScript#49902] opened 2022-07-14 09:56 UTC
# Bug Report

### 🔎 Search Terms

TS2534 await

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I couldn't find any related FAQ entries.

Versions tried on:
- 4.6.4 (local)
- Nightly = 4.8.0-dev.20220714) (playground)

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.8.0-dev.20220714#code/GYVwdgxgLglg9mABAWwIYGsCmARTUGr4BOAFAJQBciACkXMjAM6YA8YmAbpkQHyIDeAKEQjERPCCJJa9JpgB04gFaZoJdgHdEAUSJ1SAIgBCcegEIDZMgG5BAX0GDQkWAkQATPASiYAjOSoZBmY2Tm4+IREIBEYoDy8wQjgiILlEAF4UDBwEpNIbYTEJKXj8ROJU5lsHQVRGAE9IRGdoeCRPMsJMACYAmjpg1nYuXgFC6LBY0u9kyswMrKxcTuJyWxFUDVQYOI6ZlIG5aqA

### 💻 Code

```ts
function makeDetonator(): Promise<never> {
    return Promise.reject(new Error("Boom!"));
}

function detonate1(): Promise<never> {
  const detonatorPromise = makeDetonator();
  return detonatorPromise;
}

async function detonate2(): Promise<never> {
  const detonatorPromise = makeDetonator();
  await detonatorPromise;
}
```

### 🙁 Actual behavior

detonate1 has no issues, but get the following error for detonate2:
```
A function returning 'never' cannot have a reachable end point.
```

### 🙂 Expected behavior

detonate2 is semantically equivalent to detonate1, and there should be no such error.

It looks like the general rule that's missing is: awaiting on a Promise<never> would make the rest of the block unreachable.

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/45701775/178956316-432a77e9-4985-426b-a59c-413672f09e51.png">

**Comment by MartinJohns** [comment] 2022-07-14 10:36
Duplicate of #34955. Used search terms: `promise never in:title`

**Closed** 2022-07-14 11:16 UTC
