### ISSUE TITLE
`get Property 'length' does not exist on type` error inside if Array.isArray block

### ISSUE THREAD

**Issue by KingMario** [microsoft/TypeScript#53671] opened 2023-04-05 15:08 UTC
# Bug Report

The Operand is a union type, but after tested by Array.isArray, the `get Property 'length' does not exist on type` error message still displayed.

![image](https://user-images.githubusercontent.com/3956876/230123572-e82e35d2-fde9-454e-8694-d7aa6b6b3519.png)

### 🔎 Search Terms

Array.isArray

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8pBOBDYB7eUC8UDkBqbUAPjgLQHHYBU5OA9NgNwBQTAlgHbATwBmiAxtADCiADb8ArqOSsU7AHIoAJtADeTKFBQJE7JQGcAXLB16A2gF1mm7d2RpjcO6njWo8CPqnBj7CQFsAI25mAF8WUEgoeQDMKABGIigAJiSAZiSAFiSAViSANiSAdiSADiSATiT4gAZqxOJ41Ma05iZI6CckPTiRcSkZOUUVSySY-yS+UX0IZg6oPslpYFl2AEF2fQB3bjiu3SU2-jl9YCh-CH8UOPYILagAWUQwAB5T+A4AcwAaBbElwbrTY7eAAPgAFABKNo8CTsfgrORQCAADzAB0WA0RCmUEHBGig7Fxxkxy1Wwwg3wJrF8AWC8CYkJJ-yx5Nxo3UmmOmzOqi0pgMUFCN1xbU0rB4UHBa3gSBAADpWPoZXLwbZugYzKwLJDIVBOZooNzTlBRBB2J9gAALOLqg76LUWeVmi3WsWG41nVHovQQJT7PT6OIqxAgcEuy1WyHynisUSicFElTQgmaHhoKVms6sOI1BhQHMvU3myP51i4XB6g2G5Fog5+gMGGNoACiAit4PB3vrSgpvwAVnqMKD9ama7WfSpe7j5XbA47bQKHdqzP2rGPNKEUzXwmOPMAJPB2BOe439G5d5p94fj2YkxB1+EgA)

### 💻 Code

```ts
  if (Array.isArray(operands[i])) {
    const length = operands[i].length;
```

### 🙁 Actual behavior

Error message displayed.

Run properly in stackblitz.

But got runtime error while run by ts-node

```
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
calc24.ts:241:30 - error TS2339: Property 'length' does not exist on type 'Operand'.
  Property 'length' does not exist on type 'false'.

241   const length = operands[i].length;
```

### 🙂 Expected behavior

No error should display

**Comment by MartinJohns** [comment] 2023-04-05 15:12
Duplicate of #52014 and many many many many others. This definitely should be added to the FAQ.

**Comment by KingMario** [comment] 2023-04-06 04:36
Seems like it's a regression issue?

**Comment by MartinJohns** [comment] 2023-04-06 05:28
It's always been like this.

**Closed** 2023-04-08 18:00 UTC
Labels: Duplicate
