### ISSUE TITLE
type guard doesn't seem to work on interfaces

### ISSUE THREAD

**Issue by donnut** [Microsoft/TypeScript#1957] opened 2015-02-06 08:04 UTC
The type guard `instanceof Array` does not seem to recognize the type of the interface IMessage.
```
interface IMessage {
    name: string;
}

function itemFn(pipIn: IMessage[]) {
    return pipIn;
}

function baseFn(pipIn: IMessage) {
    return [pipIn];
}

function main(pipIn: IMessage|IMessage[]) {
    if (pipIn instanceof Array) {
        return itemFn(pipIn);
    } else {
        return baseFn(pipIn);
    }
}
```

The compiler outputs the error message:
```
unions6.ts(19,23): error TS2345: Argument of type 'IMessage | IMessage[]' is not assignable to parameter of type 'IMessage'.
  Type 'IMessage[]' is not assignable to type 'IMessage'.
```

I'm using master of today.

Thanks

**Comment by danquirk** [comment] 2015-02-06 20:39
This is working as intended according to the latest spec. 

From section 4.20 Type Guards:

* A type guard of the form x instanceof C, where x is not of type Any, C is of a subtype of the global type 'Function', and C has a property named 'prototype'
	- when true, narrows the type of x to the type of the 'prototype' property in C provided it is a subtype of the type of x, or, if the type of x is a union type, removes from the type of x all constituent types that aren't subtypes of the type of the 'prototype' property in C, or
	- when false, has no effect on the type of x.

That said, I'm not aware of the rationale here to do no narrowing in the else clause, it seems like this should work. @ahejlsberg can weigh in.

**Comment by NoelAbrahams** [comment] 2015-02-06 20:45
Seems related to #1719

**Comment by danquirk** [comment] 2015-02-06 21:07
Thought I had seen this before... don't know why I couldn't find it. Closing this as a dupe then.

**Closed by danquirk** 2015-02-06 21:07 UTC

**Comment by donnut** [comment] 2015-02-09 09:07
Ok, this limits the usage of type guard to primitives only. Type guard 
```
function(x: string|string[]) {
    if (x instanceof Array) {
       A(x);
    else {
       B(x);
    }
}
``` 
should be replaced by 
```
function(x: string|string[]) {
    if (typeof x === 'string') {
       B(x);
    else {
       A(x);
    }
}
```
We are working with interfaces a lot, so I hope there will be a solution soon. 
Thanks
(A TypeScript Fan)

**Comment by NoelAbrahams** [comment] 2015-02-09 10:14
@danquirk, this may not be a duplicate. It's not about narrowing in the else block.

**Comment by NoelAbrahams** [comment] 2015-02-09 10:28
This may be related to #1587, in which case it's fixed in 1.5.


@donnut, there's also a bug in there. once #1785  is fixed it should be possible to write

```TypeScript
function(x: string|string[]) {
    if (x instanceof Array) {
       A(x);
    else {
       B(x);
    }
}
```

**Comment by donnut** [comment] 2015-02-09 10:35
Thanks @NoelAbrahams. I just tried the example:
```javascript
function(x: string|string[]) {
    if (x instanceof Array) {
       A(x);
    else {
       B(x);
    }
}
```
with the latest `master`, but the compiler still errors. Can you confirm this?

**Comment by donnut** [comment] 2015-02-09 10:38
See https://gist.github.com/donnut/64ad9017ea7b78da379d

**Comment by danquirk** [comment] 2015-02-10 23:01
That would be #1719, the else block isn't getting a narrowed type by design at the moment.
