### ISSUE TITLE
Use extends on a variable declaration

### ISSUE THREAD

**Issue by GINCHER** [microsoft/TypeScript#36778] opened 2020-02-13 18:00 UTC
## Search Terms

extends, generic

## Suggestion

Add `self extends` as a possible type for a variable, which acts like extends in generic - typechecks, but not sets a type. 

Eg:
```typescript
// Invalid
const func: self extends Function = "hello"; 

// Valid
const obj: self extends Object = {firstName: "John", lastName: "Doe"}; 
// typeof obj will return {firstName: string, lastName: string}
```

## Use Cases

I want to extend Jest's matchers. Jest's website suggests duplicating code - creating an interface to extend the matchers interface, and separately, extend the matchers themselves. 

What I did is create a function with a generic parameter that returns itself, and the generic is required (using `<T extends ...>`) to be a record with a function that returns Jest's `CustomMatcherResult`, which is to enforce the typing required for `expect.extend()`. Below, I extended Jest's `Matchers` interface with the object (after modifying it).

## Examples

Currently can be achieved by:
```typescript
// The function will simply return the first argument.
const PermissionExtends = <T extends Record<string, {guest: boolean, user: boolean, admin: boolean>}>(v: T) => v;
const permissions = PermissionExtends({
    readMessage: {guest: true, user: true, admin: true},
    writeMessage: {guest: false, user: true, admin: true},
    deleteMessage: {guest: false, user: false, admin: true}
});
type Permissions = keyof typeof permissions;
// Permissions = 'readMessage' | 'writeMessage' | 'deleteMessage'
```

Ideally:
```typescript
const permissions: self extends Record<string, {guest: boolean, user: boolean, admin: boolean> = {
    readMessage: {guest: true, user: true, admin: true},
    writeMessage: {guest: false, user: true, admin: true},
    deleteMessage: {guest: false, user: false, admin: true}
};
type Permissions = keyof typeof permissions;
// Permissions = 'readMessage' | 'writeMessage' | 'deleteMessage'
```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment] 2020-02-13 21:17
I think this is a duplicate of #7481, but restricted to binding declarations.

**Comment by GINCHER** [comment] 2020-02-14 12:26
@DanielRosenwasser I don't agree. 

Correct me if I'm wrong, but it seems like #7481 OK with overriding the type, as `asType<MyComponentActions>({selectSomething})` will have the type of `MyComponentActions`.

Not only that, but what I'm asking is the opposite. 
If I were to use my suggestion with the example in the second reply in #7481, 
```typescript
const mapDispatchToProps: self as MyComponentActions = {selectSomething};
```
It should throw an error, as the return type is not void, but Promise<void>. Also, the type of mapDispatchToProps will be `{selectSomething: (id: string) => Promise<void>}` and not `{selectSomething: (id: string) => void}` as it would be in `asType<MyComponentActions>({selectSomething})`

**Comment by RyanCavanaugh** [comment] 2020-02-21 18:35
Still marking as duplicate since OP isn't something we would do (type space syntax should be valid in all type locations, but this would be constrained to declaration positions). The use cases here are still fundamentally the same as #7481; I think you've misunderstood the linked issue.

**Closed** 2020-02-24 18:00 UTC
Labels: Duplicate
