### ISSUE TITLE
Code completion missing entries in VSCode 1.20

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#21894] opened 2018-02-12 19:28 UTC
_From @tobiasviehweger on February 12, 2018 9:26_

- VSCode Version: 1.20.0
- OS Version: Windows 10 Pro 16299.192

Steps to Reproduce:

1. Use the following minimal example.
[repro.zip](https://github.com/Microsoft/vscode/files/1715820/repro.zip)

2. When using Ctrl + Space to show code completions for MyModel (a sequelize-typescript model), many static methods are missing (e.g. findAll). This was working in 1.19.
![image](https://user-images.githubusercontent.com/2111803/36090061-0ece0e14-0fdf-11e8-8e1f-56914a60582d.png)

However, if I type the full method name, it seems to find it, as it then suggests the correct parameters:
![image](https://user-images.githubusercontent.com/2111803/36090076-24e9ac44-0fdf-11e8-8319-0f14d0de037f.png)

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#43489_

**Comment by mjbvz** [comment] 2018-02-12 19:30
Possible cause  is that `findAll` is declared as a static extension method:

```ts
  static findAll<T extends Model<T>>(this: (new () => T), options?: IFindOptions<T>): Promise<T[]>;
```

I confirmed that it does not get returned as a suggestion but does get resolved properly if you type it out

**Comment by mhegazy** [comment] 2018-02-12 20:08
seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/21711

**Comment by tudor33sud** [comment] 2018-02-13 09:37
+1 ! After update, even if I spell the method name, I still get no suggestions. This was working until the update for me too.

**Closed** 2018-02-27 20:54 UTC
Labels: Duplicate
