### ISSUE TITLE
Generic mixin classes don't support overriding class methods

### ISSUE THREAD

**Issue by joyt** [Microsoft/TypeScript#14849] opened 2017-03-24 19:53 UTC
**TypeScript Version:**  2.2.1

**Code**
```ts
type Constructor<T> = new (...args: any[]) => T;

class GenericBase<T> {
  protected meta: T;
  public getMeta() {
    return this.meta;
  }
}

function Mixin<B, T extends Constructor<GenericBase<B>>>(BaseClass: T) {
  return class extends BaseClass {
    _id: string;
  }
}
const MixedGenericBase = Mixin(GenericBase);
class NewMixedGeneric extends MixedGenericBase<string> {
  // Overriding getMeta()...
  // Results in a compile error because getMeta is defined as instance member property,
  // not an instance member function.
  public getMeta() {
    return this._id + "_" + this.meta;
  }
  // However this works fine:
  public getMeta = () => {
    return this._id + "_" + this.meta;
  }
}

// Possibly related problem?
let g = new MixedGenericBase<string>();
let metaString = g.getMeta(); // metaString is typed as {} instead of string

```
**Expected behavior:**
User should be allowed to override instance functions of generic mixin classes.
This example without a generic base class works fine:
```ts
class SimpleBase {
  protected name: string;
  public getName() {
    return this.name;
  }
}

function SimpleMixin<T extends Constructor<SimpleBase>>(BaseClass: T) {
  return class extends BaseClass {
    _id: number;
  }
}

const MixedSimpleBase = SimpleMixin(SimpleBase);
class NewMixedSimple extends MixedSimpleBase {
  // This compiles correctly:
  public getName() {
    return this._id + "_" + this.name;
  }
}
```
**Actual behavior:**
Compiler error:
```
Class 'Mixin<{}, typeof GenericBase>.(Anonymous class) & GenericBase<string>' defines instance member property 'getMeta', but extended class 'NewMixedGeneric' defines it as instance member function.
```

**Comment by DanielRosenwasser** [comment] 2017-03-25 00:25
Looks like a duplicate of #14615. Can you try out our nightly build?

**Closed** 2017-03-25 00:25 UTC
