### ISSUE TITLE
Downcast leads to compiler error TS2352

### ISSUE THREAD

**Issue by k7sleeper** [Microsoft/TypeScript#17338] opened 2017-07-21 08:16 UTC
Compiling
```
interface Base { v2: string; }
interface A extends Base { v1: number; }
interface B extends Base { v3: object; }
const x: A = { v1: 5, v2: "I'm a c", v3: { hans: 'franz' } } as A;
const y: B = x as B;
```
with TypeScript 2.4.2 leads to
```
error TS2352: Type 'A' cannot be converted to type 'B'.
  Property 'v3' is missing in type 'A'.
```
I expect that this code compiles!

**Comment by RyanCavanaugh** [comment] 2017-07-21 16:58
That is not a downcast.

Duplicate of #7531, #16995, etc

**Closed by RyanCavanaugh** 2017-07-21 16:58 UTC
Labels: Duplicate
