### ISSUE TITLE
Inconsistency: Computed values are not permitted in an enum with string values members

### ISSUE THREAD

**Issue by ngolin** [microsoft/TypeScript#37411] opened 2020-03-16 14:33 UTC
**TypeScript Version:**  3.8.3

**Search Terms:** enum member

**Code**

```ts
enum Reply {
    YES = 'YES',
    NO = 1 + 2
}
```
```ts
enum Reply_ {
    YES = 'Y' + 'E' + 'S',
    NO = 1 + 2
}
```

**Expected behavior:**
Two snippets both compile okay, at least stay consistency.

**Actual behavior:**
The first snippet compiles **error**, the second snippet compiles **okay**.

**Playground Link:** 
https://www.typescriptlang.org/en/play?#code/KYOwrgtgBASsAOAbAnlA3gKCtqBNAogMpQC8UA5AYeQDRY4ByA8qVAIxQDUUATBgL4YMoSLAQoA+unrYqrSuS4V8i7uWp0cUZqw7c+-IA

**Related Issues:** 
Not Found.

**Comment by MartinJohns** [comment] 2020-03-16 14:40
Duplicate of #27976.  Search terms used: `enum computed`

**Closed** 2020-03-16 21:41 UTC
Labels: Duplicate
