### ISSUE TITLE
Report @ts-ignore'd diagnostics 

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#29843] opened 2019-02-10 03:50 UTC
## Search Terms

`@ts-ignore`, diagnostics 

## Suggestion

To implement an ESLint rule that warns agains unnecessary `// @ts-ignore` comments we need to know about ignored type errors. 

**suggestion*** 

Emit  ignored diagnostics under a different property so ESLint can use it while it's not breaking existing ecosystem that relies on diagnostics array for checking if a program has type errors. 

## Use Cases
ESLint rule 
https://github.com/typescript-eslint/typescript-eslint/issues/236

## Examples

We start with a code like this
```ts
type A = string;
// @ts-ignore
let a: A = 1; 
```
then we make a change that renders the `@ts-ignore` comment unnecessary:
```ts
type A = number;
// @ts-ignore
let a: A = 1; 
```

We want linter to warn against that comment since it's ignoring other type errors that we might not be interested in ignoring 
 
## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AlCalzone** [comment] 2019-02-11 14:37
@ajafff is that something for wotan?

**Comment by ajafff** [comment] 2019-02-11 14:46
@AlCalzone if there was the necessary API, I would add such a rule. I asked for that some months ago.

This is more or less a duplicate of #25238

**Closed** 2019-02-21 18:00 UTC
Labels: Duplicate
