### ISSUE TITLE
Inline await-ed promise breaks assignment type

### ISSUE THREAD

**Issue by ericvicenti** [microsoft/TypeScript#42152] opened 2020-12-30 01:01 UTC
# Bug Report

TypeScript fails to infer types that are defined inside an awaited "new Promise". The contents of the inline promise is guaranteed to be executed prior to the next instruction in the surrounding async function, but TS does not see that.

### 🔎 Search Terms

`await new Promise(` `new Promise` `inline promise`

### 🕗 Version & Regression Information

Affects all versions of TS

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/IYZwngdgxgBAZgV2gFwJYHsIwLYFNgSoQDmA8nADKpy4AUAlAFwwAKATutqiLgDwQJsAI1xsAfDADeAKBgwANrmQxkAC1wBZfIRIBuabJjAA7sFTKIuY6w5cevAG7pUAEzG1abXCHTyHuehgAXgkZOTk1TW0iYmCYABYAJn1wmC8fPzp6FJgAX2yDOQB6IphqGGNcNPwoVRVVbhgAB2cIZAAaeqiCGLKQGChRZDMIeTAjGAFhUU6hBGUAFQBlGFVQGAADJBdcOCJcFw3C6uQENixIrR69aVyDPGuySmosgDpIiFoHYHkEKpCBpgMrhXvJ0MRaBsFg1+iBVOgEPIXDARAlEswACSSb6-XC5Db0egGEowaFVYBCdD+GC4AAewGwTUUfUBbTYqH8LleMAAklgmmxgFA0INOjyKgRlMh0BV2cgqpF4L4wcZelB0DtGMSAFSGRTKHhsfxsdjoKA5V6WwwmMwWKw2TjcOieby+fydLwAK1wwsCALC4UNxriICaJk+lteBVSQdEkcwS2GbHlXMtLoy-iJcnyFqtxVKlSMXgGQxGKPGEHQxmYsbYLOAMAAwg0kabBiAQIZa68ANaoeTyBi6GAk5BgJreKDsprKNb9Ag0tgcOvqLydRqDZNltTAA2iYONSvKMBKGA7PaWFzSbVFYmlBYy4zoNg9osIiDIxXLPogP5iozYEqbCDJ+MouDKipwMqVYxFq0hFLqcj6jAtZtswzb9i4bbeP0AA+kyIvIcQCAOuavNapjmJM9qmnYzrpG6uAerg3q+sEoSGHItYhmGxgRpa0aBvucaWgmSYppG6aMVmeSCZGhgkoWwDFpuwxEOWkxVjWwl1o0DYYa2HDtp2XE6TAABk5kwLQ3HrAZWFGTh9C9v2g4FDe0hAA

### 💻 Code

```ts
async function meaningOfLife(): Promise<number> {
  let theMeaning;

  await new Promise<void>((resolve) => {
    theMeaning = 42;
    resolve();
  });

  // if we reach this point, theMeaning is certainly a number, but TS has `undefined`

  return theMeaning;
}
```

### 🙁 Actual behavior

On the `return` line:

`Type 'undefined' is not assignable to type 'number'.(2322)`

### 🙂 Expected behavior

Expected no type errors.

### Practical Example + Workaround

In practice, I want to write the following code:

```ts
  let serverProc;
  ...
  await new Promise((resolve, reject) => {
    serverProc = spawn(...);
    serverProc...onStarted...(resolve)
  });
  ...
  // we are certain by now: server is a ChildProcess
  serverProc.kill(); // typescript has an error here, it thinks that server is not yet defined
```

This is how I work around the issue:

```ts
  let serverProc: ChildProcess | null = null;
  ...
  await new Promise((resolve, reject) => {
    serverProc = spawn(...);
    serverProc...onStarted...(resolve)
  });
  ...
  // we are certain by now: server is a ChildProcess
  serverProc && (serverProc as ChildProcess).kill();
```

**Comment by MartinJohns** [comment] 2020-12-30 07:18
Another duplicate of #9998.

**Comment by MartinJohns** [comment] 2020-12-30 12:47
And IMO the clean approach would be to just return the result from your promise and assign it to the variable.

**Closed** 2021-01-02 18:00 UTC
Labels: Duplicate
