### ISSUE TITLE
Support Go-to-Implementation

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9413] opened 2016-06-29 08:52 UTC
_From @frogcjn on June 28, 2016 7:36_

Intellisense allows us using command + click to jump into definition (*.d.ts) or other typescript source files,
but some module needs us to quick view its javascript source file. like 'express' module or 'mongoose' module.

Is there is a quick way to jump into /node_modules/express/index.js or /node_module/express/mongoose/index.js from symbols in TypeScript source file?

_Copied from original issue: Microsoft/vscode#8244_

**Comment by dbaeumer** [comment] 2016-06-29 08:52
I am not aware of one. I tried to do a import and then use navigation but that didn't work. Will move to the TS team since such a smartness has to come from them.

**Comment by mhegazy** [comment] 2016-09-15 20:36
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/6209, and should be fixed by https://github.com/Microsoft/TypeScript/pull/10482

**Closed by mhegazy** 2016-09-15 20:36 UTC
Labels: Duplicate, Suggestion, Visual Studio
