### ISSUE TITLE
The type definition for JSON.stringify erroneously has return type `string`

### ISSUE THREAD

**Issue by mpiroc** [microsoft/TypeScript#34630] opened 2019-10-21 22:12 UTC
`JSON.stringify` currently has type:

```typescript
stringify(value: any, replacer?: (this: any, key: string, value: any) => any, space?: string | number): string;
stringify(value: any, replacer?: (number | string)[] | null, space?: string | number): string;
```

For all inputs (including `null`) *except* `undefined`, this type is correct. However, `JSON.stringify(undefined)` returns `undefined`. Therefore, the return type of `JSON.stringify` should be changed to `string | undefined`.

Solution 1: Change return type for existing overloads
```typescript
stringify(value: any, replacer?: (this: any, key: string, value: any) => any, space?: string | number): string | undefined;
stringify(value: any, replacer?: (number | string)[] | null, space?: string | number): string | undefined;
```

Solution 2 (untested): Only change the return type for undefined inputs
```typescript
stringify(value: {} | null, replacer?: (this: any, key: string, value: any) => any, space?: string | number): string;
stringify(value: {} | null, replacer?: (number | string)[] | null, space?: string | number): string;
stringify(value: undefined, replacer?: (this: any, key: string, value: any) => any, space?: string | number): undefined;
stringify(value: undefined, replacer?: (number | string)[] | null, space?: string | number): undefined;
```

**TypeScript Version:**  `3.6.3` and `3.7-Beta` (on typescript playground), `3.6.4` (locally)

**Search Terms:**
* `stringify`
* `JSON.stringify`

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
const result = JSON.stringify(undefined)
console.log(result) // undefined
console.log(result.length) // Uncaught TypeError: Cannot read property 'length' of undefined
```

**Expected behavior:**
Code that assumes that the result of `JSON.stringify` is not `undefined` should fail to compile.

**Actual behavior:**
Code that assumes that the result of `JSON.stringify` is not `undefined` compiles, but fails at runtime.

**Playground Link:** 
http://www.typescriptlang.org/play/?ssl=3&ssc=93&pln=3&pc=61#code/MYewdgzgLgBATgUwgVwDawLwwFIGUDyAcgHTRwCWYA5uQGYCeAFMmACYK2UKsCUAUKEghUCYqhBVGiFOh4wA9PJgt2nMNwHgIw0eMnS0UMQmpQAFnMUwAqmGABDZFTOwAKvQAOCAKJw4IOAAuGABhezAwEFhEe1YYD38vOCh6GAByEVMzNJgQWmU2Di5WIA

**Related Issues:**

**Comment by DanielRosenwasser** [comment] 2019-10-21 22:35
Duplicate of #18879.

**Closed** 2019-10-24 18:00 UTC
Labels: Duplicate
