### ISSUE TITLE
[proposal] Add a new option not to transform decorators if targeting `esnext`

### ISSUE THREAD

**Issue by JounQin** [microsoft/TypeScript#37620] opened 2020-03-26 14:28 UTC
## Search Terms

decorators esnext

## Suggestion

```ts
// input
const decorator = (target: any) => {}

@decorator
class A {}

// expected output with targeting `esnext`
const decorator = target => {}

@decorator
class A {}

// actual output
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
const decorator = (target) => { };
let A = class A {
};
A = __decorate([
    decorator
], A);
```

https://www.typescriptlang.org/play/index.html?experimentalDecorators=true&target=99&ssl=1&ssc=1&pln=5&pc=1#code/MYewdgzgLgBAJgU1AJwIZRMmBeGAKKVZAcwSgC4ZUwBPAShwD4YBvGAXwFgAoHgAUQp0mHsAA2qCBBgBBVhx5A

Can we add a new option to output plain `esnext` codes?

## Use Cases

Decorator is an ESNext feature, why they are transformed even targeting `esnext`?

I want to compile `.ts` to plain `.js` and use `babel` to compile `esnext` features.

## Examples

As above

## Checklist

My suggestion meets these guidelines:

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
- [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by nmain** [comment] 2020-03-26 16:38
Duplicate of https://github.com/microsoft/TypeScript/issues/29299
My search terms were _decorators transform_

**Comment by JounQin** [comment] 2020-03-26 18:52
> Duplicate of https://github.com/microsoft/TypeScript/issues/29299
> 
> My search terms were _decorators transform_

Thx for your point.

**Closed** 2020-03-26 18:53 UTC
