### ISSUE TITLE
Cannot Find Name For Some Files

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11009] opened 2016-09-20 17:07 UTC
_From @maestroh on September 16, 2016 11:53_

- VSCode Version: 1.5.2
- OS Version: Windows 10 Pro 1607
- Typescript Version: 1.8.10

Steps to Reproduce:

1. Open a Typescript project
2. Only the first file I navigate to can find modules

I have a Node project running with Typescript support. When I start Code, Typescript modules are only found for the first file I open. The remaining files have the "Cannot Find Name" error for all modules. In some cases the modules are the same ones on the first file, so I know the definitions are available. If I restart VS Code or run the reload window command, then the error goes away from the first file I open, and will now show the error for all others.

Any ideas on a fix?

_Copied from original issue: Microsoft/vscode#12145_

**Comment by waderyan** [comment] 2016-09-20 17:07
@maestroh thank you for opening this issue. Could you provide me with some code that I can copy and paste or clone to reproduce this behavior? 

I'm not understanding the context of "Cannot Find Name." If you could include a screenshot or a short video that would be helpful. 

Thank you.

**Comment by waderyan** [comment] 2016-09-20 17:07
_From @maestroh on September 17, 2016 2:34_

@waderyan Here you go. To add a bit of explanation to what you're seeing here: I've got two files open, middleware.ts and index.ts. middleware.ts is the first one I navigate to and the types are recognized. In index.ts nothing is recognized. Notice that both files import 'express'. I reload the window and the types are recognized in index.ts, but not middleware.ts. It seems that the types are only recognized in the first file I open or focus on. I may be doing something silly, but I can't think of what could be wrong here. I have tried restarting both VS Code and my machine.

![vscode-error](https://cloud.githubusercontent.com/assets/2009595/18605326/e98d584c-7c5c-11e6-8344-2c3f14683881.gif)

**Comment by waderyan** [comment] 2016-09-20 17:07
@maestroh thank you for your explanation. Moving this to the TypeScript language service repo.

**Comment by mhegazy** [comment] 2016-09-20 20:10
I can not get a reproduction of this behavior. what version are you using of vscode and of TS? can you share a project that we can use to debug?

**Comment by maestroh** [comment] 2016-09-22 12:01
@mhegazy I think I've found the problem. I've been using Bash on Ubuntu on Windows as my command line tool and my version of typescript matched the version in VS Code. However, when I checked my globally installed version from the Windows command line, the version was way out of date. I've updated all of my versions to 1.8.10 and everything seems to work now.

**Comment by waderyan** [comment] 2016-09-22 16:24
Closing per OP.

**Comment by maestroh** [comment] 2016-09-22 16:26
@waderyan Would you mind reopening? It looks like the problem is still happening. See my previous post.

**Comment by mhegazy** [comment] 2016-09-22 17:16
without a sample project there is not much we can do here. 

A good tool to help diagnose the issue, is run `tsc --listFiles --p <path to tsconfig.json>` and see if the file containing the module declaration is loaded by the compiler. if not then make sure it is not excluded.

**Comment by maestroh** [comment] 2016-09-22 18:20
I'm trying to put together a sample now. 

Everything works correctly when running tsc. The issue is that VS Code doesn't recognize modules in some of the ts/tsx files. I can reload the window to clear the issue for the file I'm working in, but others may have lost the definitions. 

I understand this is pretty vague, but it's happening regularly on my machine. Perhaps you can help me to understand how VS Code works. That might help me to narrow down the issue. 

- How does VS Code know where the definition files are located? 
- Is there a difference in how active files in the editor window locate the definitions versus files that don't have focus?

BTW, I just updated to VS Code 1.5.3 and I'm still seeing the same issue.

**Comment by maestroh** [comment] 2016-09-23 15:10
I want to thank you both for your time. It looks like this was in issue in my project. Specifically, I have multiple tsconfig files and I was excluding part of my folder structure in the main tsconfig. What was confusing is that in some cases, even files in excluded paths would find the definitions. 

This story can really be closed this time. Thanks again

**Closed** 2016-09-23 15:12 UTC
Labels: Needs More Info, VS Code Tracked
