### ISSUE TITLE
private Members

### ISSUE THREAD

**Issue by Mephiztopheles** [Microsoft/TypeScript#8847] opened 2016-05-26 21:30 UTC
HI, i wanted to look at typescript and saw, that private members are not really private in console :D
i searched in your FAQ and found an entry to this, but i think this might be a solution for private members. 

**TypeScript Version:** 

1.8.9

**Code**

```ts

// you all know it:
class Foo {
  private x = 0;
  increment(): number {
      this.x++;
      return x;
  }
}
```

**Wished behavior:**
```js
// what about something like this?
var Foo = (function () {
    var privates = {};

    function Foo() {
        privates[ this ] = { x: 0 };
    }

    Foo.prototype.increment = function () {
        privates[ this ].x++;
        return privates[ this ].x;
    };
    return Foo;
})();
```

**Actual behavior:** 

```js


// generates
var Foo = (function () {
    var x = 0;

    function Foo() {
    }
    Foo.prototype.increment = function () {
        x++;
        return x;
    };
    return Foo;
})();
```

**Comment by mhegazy** [comment] 2016-05-26 21:34
Please see https://github.com/Microsoft/TypeScript/wiki/FAQ#you-should-emit-classes-like-this-so-they-have-real-private-members

duplicate of https://github.com/Microsoft/TypeScript/issues/564

**Closed by mhegazy** 2016-05-26 21:34 UTC

**Comment by Mephiztopheles** [comment] 2016-05-26 21:40
I gave a different solution than your example why is this duplicate?
Did you even read my post? I eon'the think so 
Say something more than duplicate instead of just closing it!

**Comment by RyanCavanaugh** [comment] 2016-05-26 21:47
Try running your proposed code with two instances of Foo and see what happens. It doesn't work.

Suffice to say if there were a good simple solution here, we would have done it. There are no small clever tricks that generate private members without seriously bad trade-offs.

**Comment by Mephiztopheles** [comment] 2016-05-26 21:51
But I tried... I would never post a solution if I wouldn't test it before... due to var a = {}, but = {a:a}; a === b.a will return true , the privates object will creates privates for each instance of foo. In case you use the new Operator.

**Comment by RyanCavanaugh** [comment] 2016-05-26 21:52
![image](https://cloud.githubusercontent.com/assets/6685088/15591353/7e06b906-2351-11e6-9376-b31e4bd767b0.png)

**Comment by Mephiztopheles** [comment] 2016-05-26 22:00
ya, seems to be in my check i typed last line x instead y :D
and how a bout this? I just want to help :)

```
var Foo = (function () {
    var privates = [];
var instances = [];
    function Foo() {
        instances.push(this);
        privates.push( { x: 0 } );
    }

    Foo.prototype.increment = function () {
        privates[ instances.indexOf(this) ].x++;
        return privates[ instances.indexOf(this) ].x;
    };
    return Foo;
})();
```

**Comment by RyanCavanaugh** [comment] 2016-05-26 22:02
Now doing something with a list of `Foo`s is an O(n^2) operation instead of an O(n) operation. That's not a good trade-off!

**Comment by Mephiztopheles** [comment] 2016-05-26 22:03
i don't get it... its too slow? or what's the matter?

**Comment by RyanCavanaugh** [comment] 2016-05-26 22:05
O(n^2) complexity to walk a list of n elements and access their private members is too slow, yes.

**Comment by Mephiztopheles** [comment] 2016-05-26 22:10
hm... seems to be that i am not programming in high performance :D
and whot does O(n^2) mean? Object with n*n properties?
i never used private members before ... so never in that case... i just saw the docs and tested and came to that point but if it's too slow (especially when you created a lot of `Foo`) then never mind

**Comment by DanielRosenwasser** [comment] 2016-05-26 22:22
Hey @Mephiztopheles, it's called Big O Notation. Check out a [simple explanation](https://simple.wikipedia.org/wiki/Big_O_notation) or a more [in-depth one](https://en.wikipedia.org/wiki/Big_O_notation) on Wikipedia for more details.
