### ISSUE TITLE
Rename symbol

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#10791] opened 2016-09-08 22:11 UTC
_From @microshine on September 7, 2016 16:49_
- VSCode Version: 1.4.0
- OS Version: Windows 10 x64

Source code

``` typescript
let arr = {
    item: "Hello"
};

const {item} = arr;

console.log(item);
console.log(arr.item);
```

Trying to rename `item` symbol (F2) to `itemA`

Result

``` typescript
let arr = {
    itemA: "Hello"
};

const {item} = arr; // TSError: Has no property `item`

console.log(item);
console.log(arr.itemA);
```

_Copied from original issue: Microsoft/vscode#11641_

**Comment by waderyan** [comment] 2016-09-08 22:11
@microshine thank you for opening this issue. This is a TypeScript service issue. Moving to their repo.

**Comment by andy-ms** [comment] 2017-05-11 22:16
Looks like a duplicate of #6312.

**Comment by mjbvz** [comment] 2017-12-22 00:26
Duplicate of #6312 / #15787

**Closed by mjbvz** 2017-12-22 00:26 UTC
Labels: Bug, Duplicate, VS Code Tracked
