### ISSUE TITLE
Type narrowing doesn't work with declared enums

### ISSUE THREAD

**Issue by SLaks** [microsoft/TypeScript#43681] opened 2021-04-14 22:44 UTC
# Bug Report

### 🔎 Search Terms
narrowing enum declare 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about narrowing

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-beta&ssl=1&ssc=1&pln=9&pc=2#code/CYUwxgNghgTiAEIB2BXAtvAoqjBvAUPPAIL4C+++oksCEIALvAB4BcWOA3JQJYBm8ABTN4AQgC84jugB0xAJTwCRMAHskAZyag0q9khAA3EDHhTm3MkA)

### 💻 Code

```ts
declare enum Enum {
  A
}

declare let x: Enum;

if (x !== Enum.A) {
  const demo: never = x;
}
```

### 🙁 Actual behavior

> Type 'Enum' is not assignable to type 'never'.

Delete the word `declare` and the error goes away.

### 🙂 Expected behavior

No error; `x` should be narrowed to `never`.

**Comment by andrewbranch** [comment] 2021-04-14 23:07
Duplicate of #16977

**Closed** 2021-04-17 18:00 UTC
Labels: Duplicate
