### ISSUE TITLE
If you have comment at the end of typescript file, Javascript generation contains Typescript code

### ISSUE THREAD

**Issue by dsenthilraj** [Microsoft/TypeScript#2411] opened 2015-03-18 16:08 UTC
It was accident i encounter this issue. 
if i have a typescript file as follows
module myMoudle {
interface iTest {
	
	t2:iTest;
	x3:number;
}

class test implements iTest {
	t2: iTest;
	x3: number;
	constructor(){
		this.t2 = new test();
		this.x3 = 1;
	}
}

}
/*   

*/

Correpsonding Javascript file contains JS + TS code and it is not commenting the typescript code properly. comment like  /* /* instead of /* */. It does not matter if the comment has any thing inside or not.  Test it from this link

http://www.typescriptlang.org/Playground#src=module%20myMoudle%20%7B%0D%0Ainterface%20iTest%20%7B%0D%0A%09%0D%0A%09t2%3AiTest%3B%0D%0A%09x3%3Anumber%3B%0D%0A%7D%0D%0A%0D%0Aclass%20test%20implements%20iTest%20%7B%0D%0A%09t2%3A%20iTest%3B%0D%0A%09x3%3A%20number%3B%0D%0A%09constructor()%7B%0D%0A%09%09this.t2%20%3D%20new%20test()%3B%0D%0A%09%09this.x3%20%3D%201%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0A%7D%0D%0A%2F*%20%20%20%0D%0A%0D%0A*%2F

var myMoudle;
(function (myMoudle) {
    var test = (function () {
        function test() {
            this.t2 = new test();
            this.x3 = 1;
        }
        return test;
    })();
})(myMoudle || (myMoudle = {}));
/*

module myMoudle {
interface iTest {
	
	t2:iTest;
	x3:number;
}

class test implements iTest {
	t2: iTest;
	x3: number;
	constructor(){
		this.t2 = new test();
		this.x3 = 1;
	}
}

}
/*

**Comment by DanielRosenwasser** [comment] 2015-03-18 17:25
Looks like a duplicate of #1714.

**Closed by DanielRosenwasser** 2015-03-18 17:25 UTC
