### ISSUE TITLE
Rest parameter fails to compile with `strictNullChecks` and `target es6` 

### ISSUE THREAD

**Issue by seanchas116** [Microsoft/TypeScript#8430] opened 2016-05-03 03:57 UTC
**TypeScript Version:** 

1.9.0-dev.20160502

**Code**

```ts
const xs = [1,2,3];
const ys = [4,5];
xs.push(...ys);
```

Compiled with `tsc --target es6 --strictNullChecks test.ts`

**Expected behavior:**

Compile without errors (without `--target es6` option, the code compiles successfully)

**Actual behavior:** 

Errors are emitted:

```
test.ts(3,9): error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.
```

Seems like values are treated nullable. (similar to #8357)

**Comment by mhegazy** [comment] 2016-05-03 22:44
indeed a duplicate of https://github.com/Microsoft/TypeScript/issues/8357

**Closed by mhegazy** 2016-05-03 22:44 UTC
