### ISSUE TITLE
Bug in control flow analysis with mutable variables

### ISSUE THREAD

**Issue by nkallen** [microsoft/TypeScript#45658] opened 2021-08-31 11:08 UTC
# Bug Report

### 🔎 Search Terms

mutable variable, control flow analysis

### 🕗 Version & Regression Information

Just noticed it (09/2021), tsc 4.4.2

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about control flow analysis

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/DYUwLgBAzmCGYgFwQOQ1gJzCiAfVAZrAJagAmO+KArgA5nwgV6p0NjEB2A5jgLyp0WFAG4AUGKgB3YmADGACwgAKdAgCUEAN5iIeiHNhQQguMMS79+sgHsAqvUbL14q-uIEVakwEI+AlCJSJhRNORtOKBtQADpgG25lACIoajk5ECgoJJdLNwAjDBBYAGtxAF8JAmpOOQ4IiFsHdhBnbTzoOAQIAKDyUTFyoA)

### 💻 Code

```ts
let state: 'start' | 'failed' | 'updated' | 'updating' = 'start';

switch (state) {
    case 'start':
       doUpdate();
       if (state !== 'failed') console.log("success");
       break;
}

function doUpdate() {
    state = 'failed';
}
```

### 🙁 Actual behavior

The type checker errors because it assumes the value cannot change, however it's a "let" and not a "const" variable. The example above is contrived but in my case I have a long running async job that can be aborted by the user.

### 🙂 Expected behavior

The analysis should only assume a variable cannot change if it's const or readonly

**Comment by MartinJohns** [comment] 2021-08-31 11:28
Another duplicate of #9998.

**Closed** 2021-09-03 18:00 UTC
Labels: Duplicate
