### ISSUE TITLE
private property is declare but value never read

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/TypeScript#44294] opened 2021-05-27 08:40 UTC
# Bug Report

### 🔎 Search Terms
private value never read

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBHAxgGwIYGd1wIJwN4BQAkGFAJYBuqMwcA+qgO6oDWwAwhAK4B28AvHAAMAbjgB6cXACEcALbd0wABIQKwKMTBcARsjKI4TVsAAUASnzEiMABZl0AOgbM2nXjADUnkcQC+BAFAA)

### 💻 Code

```js
export  class A {
	private _awakeCount = 0; // ! mouseHover
	public awake() {
		this._awakeCount++; // should mark the private value as used !
	}
}
```

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/24865815/119794282-63e89400-bea5-11eb-87ea-d7b30f1c28df.png)

### 🙂 Expected behavior

should have same "usage detection" behavior as if not `private` ! 
![image](https://user-images.githubusercontent.com/24865815/119794391-7fec3580-bea5-11eb-82b3-9877b8568224.png)
 
note: is not so hellish because vscode detect all reference , but if we have visual linter ! its polluting codes.

**Comment by MartinJohns** [comment] 2021-05-27 08:49
The property is never read, thus unused.

**Comment by djmisterjon** [comment] 2021-05-27 08:53
> The property is never read, thus unused.

yes it used.
This thing
`this._awakeCount++ ;`
is same as 
`this._awakeCount = this._awakeCount+1 ;`

one not lint warning, the other active the warning.

**Comment by MartinJohns** [comment] 2021-05-27 08:55
It's not **read** anywhere, it's just updated.

This is a duplicate of #30177.

**Closed** 2021-05-27 09:01 UTC
