### ISSUE TITLE
flag to make comments go to .d.ts files instead of the js files

### ISSUE THREAD

**Issue by championswimmer** [Microsoft/TypeScript#26987] opened 2018-09-09 10:31 UTC
I would like the my JSDoc style comments of functions/classes go into the type declaration files instead of the emitted JS files.

That way, if I chose to use my JS without any minification, I can use it, while the comments would serve their purpose during autocomplete/intellisense in Webstorm/VSCode as well. 

Right now, except interfaces, all other comments go into the emitted JS not into the d.ts files.

**Comment by DanielRosenwasser** [comment] 2018-09-10 01:17
Duplicate of #14619

**Closed** 2018-09-10 02:40 UTC
Labels: Duplicate
