### ISSUE TITLE
Mapped types key remapping `as K` is converting array/tuple into object

### ISSUE THREAD

**Issue by Alexsey** [microsoft/TypeScript#52264] opened 2023-01-16 22:07 UTC
# Bug Report

### 🔎 Search Terms

Generics, Mapped types, key remapping, Array, Tuple

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/C4TwDgpgBAwg9mEBGAPAFQHxQLxQN4DaA0lAJYB2UA1hCHAGZRoC6AXE8cwL4BQPokWAhAAmdFlyESFarQZMoAQwDOUImw7re-cNDQRlwJDiGJUBJABooI6wGZmWAPROoAczhwAJlAC0UC2tbKAc+AT0DYBETeEQxQJt7RygXKAAjRR9-PACAD3ZyAFcAWzSIACcNOygAHyhjOuDgOABlYHKKN3YACgBKHCxDDvI3awA6CaguIA)

### 💻 Code

```ts
type Copy1<T> = {[K in keyof T]: T[K]}

type Copy2<T> = {[K in keyof T as K]: T[K]}

type Test1 = Copy1<[1, 2, 3]> // good - [1, 2, 3]

type Test2 = Copy2<[1, 2, 3]> // bad - { [x: number]: 3 | 1 | 2, toString: () => string, ... }
```

### 🙁 Actual behavior

Trivial `as K` key remapping is causing tuple/array to be converted into an object (yes, same thing for arrays)

### 🙂 Expected behavior

trivial key remapping should not change the behavior of the mapped type. [Tuple/array should not become object since TS 3.1](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#mapped-types-on-tuples-and-arrays). `Copy1` and `Copy2` should be equivalent

Notes:
Of course, it's a simplified example. In my actual use case, I had a conditional type like `as T extends unknown[] ? K : ...`. The workaround was to move the conditional type out of the mapped type and write the mapped type twice

**Comment by jcalz** [comment] 2023-01-17 15:58
Duplicate of #40586

**Closed** 2023-02-05 18:00 UTC
Labels: Duplicate
