### ISSUE TITLE
Compiled folder structure wrong when using folder link

### ISSUE THREAD

**Issue by twoeo** [Microsoft/TypeScript#10364] opened 2016-08-16 08:16 UTC
**TypeScript Version:** 2.0.0  (on Windows)

**Project structure**

```
|- shared
    |- abc.ts

|- src
    |- shared (link to ../shared, not real folder)
    |- app.ts
    |- tsconfig.json
```

**Code**

``` ts
//abc.ts
console.log('abc');

//app.ts
import './shared/abc.ts';
console.log('app')
```

**And run cmd on Windows to create folder link:**

```
mklink /J src\shared shared
```

**Finally run compile command:**

```
cd src
tsc -p . --outDir dist
```

**Expected behavior:**

file structure in folder dist as below:

```
|- shared
    |- abc.js
|- app.js
```

It works well on TypeScript@1.8.0,
and can't work after I updated it to 2.0.0.

**Actual behavior:** 

```
|- shared
    |- abc.js
|- src
    |- app.js
```

Note that [shared] and [src] were placed at different with it on 1.8.0

**The same problem on Linux**

using command below to create folder link

``` ts
ln -s $(pwd)/shared src/shared
```

**Comment by RyanCavanaugh** [comment] 2016-08-16 17:50
@vladima would you be able to take a look?

**Comment by mhegazy** [comment] 2016-08-16 23:41
this looks like another manifestation of the issue in https://github.com/Microsoft/TypeScript/issues/9552.

**Comment by flts** [comment] 2016-09-23 14:33
I'm using Parallels with Shared Folders and I have symlinked my projects folder to c:\projects. 
I see the following path resolving happening with tracing on:

`Resolving real path for 'C:/projects/TestProject/node_modules/@angular/router/index.d.ts', result 'UNC/psf/Home/Projects/TESTPROJECT/NODE_MODULES/@angular/router/INDEX.D.TS'
======== Module name '@angular/router' was successfully resolved to 'UNC/psf/Home/Projects/TESTPROJECT/NODE_MODULES/@angular/router/INDEX.D.TS'. ========`

This happens for both npm packages and project files.

**Comment by btgoodwin** [comment] 2016-09-26 18:38
@flts I'm seeing the same issue with Typescript 2.0.2 and 2.0.3 when using `npm link` to pull in modules that are in development into an app's node_modules folder.

**Comment by pawelczak** [comment] 2016-10-24 10:27
I'm facing same issues. It would be nice to have it working in next release.

**Comment by jasonswearingen** [comment] 2016-10-24 12:47
I was able to work around the problem,:

basically the structure is like this:

```
myNodeApp --> slib --> xlib
            \
            +--> myInteropLib --> xlib
           /
myWebApp --> blib --> xlib
```

each of the references to ```xlib``` and ```slib``` are symlinked using ```npm link```

part of the trick (of this workaround) is that you need to make sure that none of the linked module dependencies are installed into the consuming project's folder.   for me, this was accomplished by deleting everything under my entire ```node_modules``` directory, then ```npm link xlib```, and then finally ```npm install``` the remainder of the ```project.json``` dependencies.

hope that helps someone.   good luck!

**Comment by andy-ms** [comment] 2016-11-01 20:50
I was able to reproduce this.
I modified the example because the `import "./shared/abc.ts"` syntax does nothing on invalid imports.

```sh
mkdir shared
echo 'export const x = 0;' > shared/abc.ts

mkdir src; cd src
ln -s ../shared shared
echo 'import { x } from "./shared/abc"; x + 1;' > app.ts
echo '{ "compilerOptions": { "outDir": "bin" } }' > tsconfig.json
tsc
find bin -type f
```

Produces:

```
bin/src/shared/abc.js
bin/src/app.js
bin/shared/abc.js
```

I would expect just `bin/app.js` and `bin/shared/abc.js`.

I also wrote a test case, but the test harness only seems to output 2 files.

```ts
// @noImplicitReferences: true
// @traceResolution: true
// Test of GH#10364

// @filename: /shared/abc.ts
// @symlink: /src/shared/abc.ts
export const x = 0;

// @filename: /src/app.ts
import { x } from './shared/abc';
x + 1;

// @filename: /src/tsconfig.json
{
    "compilerOptions": {
        "outDir": "bin"
    }
}
```

**Closed** 2016-11-11 21:52 UTC
Labels: Bug
