### ISSUE TITLE
Type narrowing of string literal unions

### ISSUE THREAD

**Issue by gcnew** [Microsoft/TypeScript#9314] opened 2016-06-22 16:50 UTC
**TypeScript Version:** 

nightly (1.9.0-dev.20160217) + strictNullChecks

**Code**

```ts
type Easing = 'ease-in' | 'ease-out' | 'ease-in-out';

function getEasingFunction(easing: Easing): (val: number) => number {
    switch (easing) {
        case 'ease-in':     return t => t * t;
        case 'ease-out':    return t => t * (2-t);
        case 'ease-in-out': return t => t<0.5 ? (2*t*t) : -1+(4-2*t)*t;
    }
    // `easing` should be of type `never` here
    // however the actual type is `'ease-in' | 'ease-out' | 'ease-in-out'`
}
```

**Expected behavior:**
After an exhaustive `switch` the switched variable should be of type `never` as per https://github.com/Microsoft/TypeScript/pull/9163. Conversely, if the `switch` is not exhaustive and the return type does not accomodate for `undefined`, an error should be issued.

**Actual behavior:** 
String literal union types are not narrowed thus an error is always issued.

**Comment by gcnew** [comment] 2016-06-22 16:52
PS: Kudos for https://github.com/Microsoft/TypeScript/pull/9163 and all the work you've put in TS. It's a trully amazing language.

**Comment by aluanhaddad** [comment] 2016-06-22 19:41
@gcnew interestingly, this works:
```TypeScript
type Easing = { val: 'ease-in' } | { val: 'ease-out' } | { val: 'ease-in-out' };

function getEasingFunction(easing: Easing): (val: number) => number {
    switch (easing.val) {
        case 'ease-in': return t => t * t;
        case 'ease-out': return t => t * (2 - t);
        case 'ease-in-out': return t => t < 0.5 ? (2 * t * t) : -1 + (4 - 2 * t) * t;
    }
    // `easing` should be of type `never` here
    // however the actual type is `'ease-in' | 'ease-out' | 'ease-in-out'`
}
```

**Comment by gcnew** [comment] 2016-06-22 20:04
@aluanhaddad Yeah, another workaround that doesn't change `Easing` allias:

```ts
type Easing = 'ease-in' | 'ease-out' | 'ease-in-out';

function assertNever(x: never): never {
    throw `Not a never ${ x }`;
}

function getEasingFunction(easing: Easing): (val: number) => number {
    const x = { test: easing };
    switch (x.test) {
        case 'ease-in':     return t => t * t;
        case 'ease-out':    return t => t * (2-t);
        case 'ease-in-out': return t => t<0.5 ? (2*t*t) : -1+(4-2*t)*t;

        default:
            return assertNever(x);
    }
}
```

**Comment by ahejlsberg** [comment] 2016-06-22 21:44
This is a duplicate of #7447.

**Closed** 2016-06-22 21:45 UTC
Labels: Duplicate
