### ISSUE TITLE
allowJs crashing on moments JS file

### ISSUE THREAD

**Issue by erikcharlebois** [Microsoft/TypeScript#6790] opened 2016-02-01 19:22 UTC
tsc --allowJs moment-with-locales.min.js 

on min/moment-with-locales.min.js
from https://github.com/moment/moment/archive/2.11.1.zip

gives
node_modules/typescript/lib/tsc.js:32405
        if (moduleName.indexOf("!") != -1) {
                      ^
TypeError: Cannot read property 'indexOf' of undefined
    at classicNameResolver (node_modules/typescript/lib/tsc.js:32405:23)
    at resolveModuleName (node_modules/typescript/lib/tsc.js:32308:28)
    at resolveModuleNamesWorker (node_modules/typescript/lib/tsc.js:32573:40)
    at processImportedModules (node_modules/typescript/lib/tsc.js:33156:35)
    at findSourceFile (node_modules/typescript/lib/tsc.js:33132:17)
    at processSourceFile node_modules/typescript/lib/tsc.js:33059:27)
    at processRootFile (node_modules/typescript/lib/tsc.js:32982:13)
    at node_modules/typescript/lib/tsc.js:32594:60
    at Object.forEach (node_modules/typescript/lib/tsc.js:98:30)
    at Object.createProgram (node_modules/typescript/lib/tsc.js:32594:16)

**Comment by mhegazy** [comment] 2016-02-01 19:33
looks like a duplicate of #6703

**Comment by mhegazy** [comment] 2016-02-01 19:35
looks fixed on` typescript@next` and latest in release-1.8

**Closed** 2016-02-02 05:45 UTC
Labels: Bug, Duplicate
