### ISSUE TITLE
Passing files on the command line in a different order produces different errors

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1954] opened 2015-02-06 00:32 UTC
This bug is very similar to #1953.

0.ts:
```ts
///<reference path="1.ts"/>
///<reference path="2.ts"/>
var i: A | B;
var param: any;
i.foo(param); // May or may not produce an error
```
1.ts:
```ts
///<reference path="0.ts"/>
///<reference path="2.ts"/>
interface A {
    foo(): string;
}
```
2.ts:
```ts
///<reference path="0.ts"/>
///<reference path="1.ts"/>
interface B {
    foo(x?): string;
}
```
These three files form a clique because they all reference each other. If you pass any subset of these files on the command line, you may observe different output depending on which one is first. If you pass 0.ts or 1.ts first, you can an error. If you pass 2.ts first, you get no error.

**Comment by mhegazy** [comment] 2015-04-22 00:40
this looks like a dupe of #1953

**Closed by mhegazy** 2015-04-22 00:40 UTC
Labels: Bug
