### ISSUE TITLE
Array<T>.filter should be able to refine T|undefined to T

### ISSUE THREAD

**Issue by Firehed** [Microsoft/TypeScript#20707] opened 2017-12-14 22:49 UTC
**TypeScript Version:**  2.6.1

**Code**

```ts
interface EntityType {
  id: number,
  name: string,
}
const ids = [1, 2, 3]
const entities = new Map<number, EntityType>()
let relevantEntities: EntityType[] = []
if (ids) {
  relevantEntities = ids.map(id => entities.get(id)).filter(Boolean)
}
```

Note that I have tried many variants of the argument to `filter` (`x => !!x`, `x => x !== undefined`, etc). I'm only using `Boolean` here since it [works in Flow](https://github.com/facebook/flow/issues/2846)

Further note that making the following change allows the error checker to proceed, but only through basically lying about the data:
```
if (ids) {
  // get(id) becomes get(id)!
  relevantEntities = ids.map(id => entities.get(id)!).filter(Boolean)
}
```

**Expected behavior:**
Assignment proceeds without error, since any `undefined` values produced in the `map` operation are filtered out.

**Actual behavior:**
```
error TS2322: Type '(EntityType | undefined)[]' is not assignable to type 'EntityType[]'.
  Type 'EntityType | undefined' is not assignable to type 'EntityType'.
    Type 'undefined' is not assignable to type 'EntityType'.
```

**Comment by RyanCavanaugh** [comment] 2017-12-15 00:08
This is already possible, you just need to define an explicit user-defined type guard:
```ts
function notUndefined<T>(x: T | undefined): x is T {
    return x !== undefined;
}
if (ids) {
    relevantEntities = ids.map(id => entities.get(id)).filter(notUndefined);
}
```

**Comment by Astrophizz** [comment] 2017-12-15 21:22
That only works if you pass the type guard as a function reference and don't, for example, call it with an arrow function. This does _not_ work:

```typescript
function notUndefined<T>(x: T | undefined): x is T {
    return x !== undefined;
}
if (ids) {
    relevantEntities = ids.map(id => entities.get(id)).filter(id => notUndefined(id));
}
```

**Comment by Firehed** [comment] 2017-12-15 21:57
Thanks @RyanCavanaugh - that solution does appear to work as-is. 

It is, however, fairly unintuitive (hence my being here in the first place!) and I think it would be immensely helpful if this "just worked" out of the box. I think it's a fairly common pattern, particularly when working with a normalized store of entities (e.g. Redux).

At the very least, having this documented on the Typescript website (rather than digging around in github issues and stackoverflow) would go a long way for the language's usability, even if it's not (currently?) practical to add first-class support into the language.

**Comment by mhegazy** [comment] 2018-01-10 19:35
Duplicate of https://github.com/Microsoft/TypeScript/issues/20812

**Closed** 2018-01-25 23:25 UTC
Labels: Duplicate
