### ISSUE TITLE
No typechecking error in code that uses an uninitialized variable due to circular reference

### ISSUE THREAD

**Issue by jthemphill** [microsoft/TypeScript#59723] opened 2024-08-22 22:09 UTC
### 🔎 Search Terms

uninitialized variable, lexical scoping, circular reference

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about uninitialized variables
- I encountered this error on my company's TypeScript version (5.3.3), and reproduced it on Nightly in the playground.
- I encountered this issue, though it seems to be filled with people asking for _fewer_ errors when their code has circular references😅 https://github.com/microsoft/TypeScript/issues/35546

### ⏯ Playground Link

https://www.typescriptlang.org/play/?noUncheckedIndexedAccess=true&allowUnreachableCode=true&allowUnusedLabels=true&noUnusedLocals=true&noUnusedParameters=true&target=99&strictBuiltinIteratorReturn=true&useUnknownInCatchVariables=true&exactOptionalPropertyTypes=true&noFallthroughCasesInSwitch=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true&suppressImplicitAnyIndexErrors=true&ts=5.7.0-dev.20240822#code/PTAEEkDtQFwCwKagE4IIYBtQGMD2ATBAGlEy1wDNZEBnJCgV0mxgEtdIbTVSaBPZqUj4UCGA2TQADslwBbVnRoBuAFAgIoAFYMaMUHLSFQCAG4JkfeK0gBzUP2ZxZkXLtCIeMXAZusFAF5I8MEIejhodKrqYAAqiKKYoObINOzQlNSKoIzMbByg+LhhEdhwNvZ6DBQUqrks6TliZQDCaGUI+ABqmAxhADxdAHwAFBTNcADykG0dALKKNABcoCMAlKAAvEOgXWsrXaAA3qqgouKSTTBl07OICzQ062oAvtF4nPq2Yi24uBiQMI0ACqaTsdyQm1W+1AACM-hh0NBtsdTjgOOFFL9-lsrq12ohur0wiN1it4f8kVsdiczmcNPFsjA+FIEB1sABrLg6cIUGzEEzmaDwNy2OCgAAGWIREtA2Vc+j8bEwrCCIk8CAAhGizqgLtBpf81GcXmtjecJAaaNiMK9ohoAEpMNhyJAWWTIFZtSAK0jYbBA0AAckNGCDcIQFFwPCVrBVATQ+Wgqm+MBtgMeoIqEOeqiAA

### 💻 Code

```ts
// In the real code, all of these functions are async and return promises;
// I just made everything synchronous here to minimize the test case

// The real version of this function does caching stuff
function fetchCachedValues<V>(fetchOnCacheMiss: () => V): V {
  return fetchOnCacheMiss();
}

const getCoolnessUsingCache = (): boolean => {
  const isCool = fetchCachedValues((): boolean => {
    // This typechecks just fine, even though `isCool` is not initialized here!
    return isCool;
  });
  return isCool;
}

// Runtime error: Cannot access 'isCool' before initialization 
getCoolnessUsingCache();
```

### 🙁 Actual behavior

TypeScript reports no errors. Running the code gives a runtime error: `Cannot access 'isCool' before initialization`

### 🙂 Expected behavior

I think TypeScript should report an error! Possibly `Block-scoped variable 'isCool' used before its declaration.(2448)`

**Comment by MartinJohns** [comment] 2024-08-22 22:30
Essentially a duplicate of #11498.

**Comment by RyanCavanaugh** [comment] 2024-08-26 19:37
If `fetchCachedValues` defers execution of its callback, this code is fine, but we don't know if it defers or not. If we did error, there'd be no 'correct' way to write correct code, thus there isn't an erorr.

**Comment by jthemphill** [comment] 2024-08-26 21:36
Yeah, after reading #11498 I understand why that would resolve this issue.

I'm mostly surprised, and annoyed, that ECMAScript allows

```js
const x = function() { return x; }
```

in the first place, and I agree that a `defer` keyword in TypeScript would let the typechecker differentiate between lambdas that do and don't work with circular references.

**Closed** 2024-08-29 01:32 UTC
Labels: Duplicate
