### ISSUE TITLE
Readonly prevents indexer assignment in class constructor

### ISSUE THREAD

**Issue by axefrog** [Microsoft/TypeScript#17845] opened 2017-08-16 21:21 UTC
**TypeScript Version:**  2.4.2

**Code**

```ts
class Environment {
  readonly [key: string]: Domain;

  constructor (domains: Domain[]) {
    for (let domain of domains) {
      this[domain.name] = domain;
    }
  }
}
```

**Expected behavior:**

I'm assigning the values in the constructor, so I would assume that the readonly modifier would not take effect yet.

**Actual behavior:**

> Index signature in type 'Environment' only permits reading.
> (property) Domain.name: string

Is this a bug or does TypeScript disallow assignment to readonly indexers due to implementation difficulties?

**Comment by mhegazy** [comment] 2017-08-22 18:10
duplicate of https://github.com/Microsoft/TypeScript/issues/6781

**Comment by mhegazy** [comment] 2017-09-06 19:01
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-06 19:01 UTC
Labels: Duplicate
