### ISSUE TITLE
Type incorrectly narrowed down to null when using forEach

### ISSUE THREAD

**Issue by patrickszmucer** [microsoft/TypeScript#45181] opened 2021-07-26 12:30 UTC
# Bug Report

```
let a: number | null = null;
[1].forEach(() => {
    a = 1;
});
a // incorrectly inferred to null
```

**Expected** - type is inferred to `number | null`.
**Actual** - type us narrowed down to `null`

The "for const of" version works correctly.

### 🔎 Search Terms

`forEach`, `null`, `type narrowing`

### 🕗 Version & Regression Information

This started happening when trying to migrate from 4.2.3 to 4.3.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/DYUwLgBAhgXBB2BXAtgIxAJwgHwY4wEAvHgQNwBQA2gIwC6AdAGYD2GAolAMYAWAFHwCUxAHwQA3hQjToxCDUoBfQZSgQA9OtLAgA)

**Comment by MartinJohns** [comment] 2021-07-26 13:30
Another duplicate of #9998.

**Closed** 2021-07-26 13:59 UTC
