### ISSUE TITLE
Unable to await on Promise.all to return value

### ISSUE THREAD

**Issue by xeoneux** [Microsoft/TypeScript#8916] opened 2016-06-01 10:30 UTC
**TypeScript Version:** 

1.8

**Code**

```ts
async function scanPorts() {
    let result = await Promise.all(devices.map((device) => {
        return getPortStatus(device)
    }));
    return result.indexOf("open");
                          ^
}
```

**Error**

`error TS2345: Argument of type 'string' is not assignable to parameter of type 'Promise<{}>'.`

**Comment by Arnavion** [comment] 2016-06-02 00:16
It sounds like `getPortStatus` returns a `Promise<string>`, and `result` is being inferred as `Promise<Promise<string>>[]` so `result.indexOf` wants a `Promise<string>` instead of a `string`, which would make this a duplicate of #7566

**Comment by mhegazy** [comment] 2016-06-02 00:18
indeed a duplicate. thanks.

**Closed by mhegazy** 2016-06-02 00:18 UTC
