### ISSUE TITLE
Allow Unicode string imports and exports

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#43870] opened 2021-04-28 21:48 UTC
https://github.com/tc39/ecma262/pull/2154

```ts
import { "😊" as yay } from "...";

yay();

export { yay as "🦈" };
```

The above code should be supported.

The minimum viable product should have tests for:

* `esnext` module output
* `es2015` or similar module output just to get an error
* `--declaration` emit
  * Specific declaration emit where the compiler might generate `import()` type syntax.
* Quick info, and error message tests where we might generate `import()` type syntax
* Completions in `import {}` and `export {}` lists
* Go-to-definition

It is likely that we would never try to emit our own `import()` type syntax.

**Comment by Kingwl** [comment] 2021-04-30 03:23
I’m happy to work on this (If @weswigham does not started)

**Comment by weswigham** [comment] 2021-04-30 03:56
I have not, and probably wouldn't until after the RC cut. If.you do work on it, just keep in mind that something like https://github.com/microsoft/TypeScript/pull/40708 we intend as a followup for this change, rather than a part of it. For this, we just wanna get the new syntax down, without expanding any TS syntax yet.

**Comment by ExE-Boss** [comment] 2021-05-08 15:33
Duplicate of <https://github.com/microsoft/TypeScript/issues/40594>

**Closed** 2021-05-10 01:32 UTC
Labels: Duplicate
