### ISSUE TITLE
`internal` modifier suggestion

### ISSUE THREAD

**Issue by SergioMorchon** [Microsoft/TypeScript#2774] opened 2015-04-15 08:11 UTC
As a typescript developer, I am building libraries for my client enterprise at work. The libraries has a lot of interfaces, types, clases, enums, variables... that are not intended to be public on the final comiled file, but I'm forced to export them to reuse at the other inner modules (before coupling them into one single file).

I would like to be able to generate de .d.ts file of my .js without the `internal` members. I know they will be really accesible at JavaScript, but not at the definitions file.

This is really significant because others could use those definicion files to use the libraries, or to generate automatically public documentation (ie. http://typedoc.io/).

**Comment by DanielRosenwasser** [comment] 2015-04-15 08:22
This is a duplicate of #892, but it's definitely something we'd find useful as well.

**Closed by DanielRosenwasser** 2015-04-15 08:22 UTC

**Comment by SergioMorchon** [comment] 2015-04-15 09:12
Thanks and sorry for the duplicated inconvenience...
