### ISSUE TITLE
type invariants assertions

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#20188] opened 2017-11-21 11:27 UTC
### closed in favor of #16605

in my code i often use, let's call them, type invariants assertions:
```ts
function mustBe<T>(_: () => T): void {}
interface A {
    isThat: true;
    text: string;
}
interface B {
    isThat: false;
    value: number;
}
type C = A | B;
declare const C: C;
mustBe<true>(() => C.isThat); // <-- type error as expected
```

now i wish i could do type invariant assertions without emitting any useless code, making it a zero cost abstraction:

```ts
makesure C.isThat sameas true;
```

where `makesure` is a new TS syntax/construct that participates in type checking, but doesn't get emitted

few more examples
```ts
makesure typeof c.isThat subtypeof boolean
makesure MyClass subtypeof BaseClass
// ...
```

**Comment by gcnew** [comment] 2017-11-21 16:14
I use type aliases for pseudo static asserts.

```ts
type HasType<T, Q extends T> = Q;

type StaticAssert1 = HasType<true, A['isThat']> // OK
type StaticAssert2 = HasType<true, C['isThat']> // Error as expected
```

**Comment by mhegazy** [comment] 2017-11-21 17:29
duplicate of https://github.com/Microsoft/TypeScript/issues/16605?

**Closed** 2017-11-21 17:41 UTC
Labels: Duplicate
