### ISSUE TITLE
Generic parameter default cant reference the same class

### ISSUE THREAD

**Issue by ivanpopelyshev** [Microsoft/TypeScript#17167] opened 2017-07-13 15:39 UTC
**TypeScript Version:**  2.4.1

**Code**

```ts
export class A<TA extends A<any> = A<any>> {
	clone(): TA {
		return null;
	}
}

class B extends A<B> {
}

let b = new B(); 
let c : B = b.clone();
```

**Expected behavior:**

Compilation succeeded.

**Actual behavior:**

Maximum call stack exceeded at resolveNameHelper.

**Comment by ikatyang** [comment] 2017-07-13 17:26
Duplicate of https://github.com/Microsoft/TypeScript/issues/16533 or https://github.com/Microsoft/TypeScript/issues/16221.

**Comment by RyanCavanaugh** [comment] 2017-07-13 17:30
Thanks @ikatyang !

**Closed by RyanCavanaugh** 2017-07-13 17:30 UTC
Labels: Duplicate
