### ISSUE TITLE
"Two different types with this name exist, but they are unrelated" emitted when same

### ISSUE THREAD

**Issue by shanehsu** [microsoft/TypeScript#26627] opened 2018-08-23 08:15 UTC
**TypeScript Version:**  Version 3.1.0-dev.20180823

**Search Terms:** Different types with same name

**Code**

```ts
export type Constructor<T> = new (...args: any[]) => T
export type MappedResult<T> =
    T extends Boolean ? boolean :
    T extends Number ? number :
    T extends String ? string :
    T


interface X {
    decode<C extends Constructor<any>>(ctor: C): MappedResult<C extends Constructor<infer T> ? T : never>
}

class Y implements X {
    decode<C extends Constructor<any>>(ctor: C): MappedResult<C extends Constructor<infer T> ? T : never> {
        throw new Error()
    }
}
```

**Expected behavior:** It should compile without any error. Everything is in the same namespace, so it should be the same type.

**Actual behavior:** The quoted error below is emitted.

```text
$ tsc tsc-test.ts
tsc-test.ts:14:5 - error TS2416: Property 'decode' in type 'Y' is not assignable to the same property in base type 'X'.
  Type '<C extends import("tsc-test").Constructor<any>>(ctor: C) => import("tsc-test").MappedResult<C extends import("tsc-test").Constructor<infer T> ? T : never>' is not assignable to type '<C extends import("tsc-test").Constructor<any>>(ctor: C) => import("tsc-test").MappedResult<C extends import("tsc-test").Constructor<infer T> ? T : never>'. Two different types with this name exist, but they are unrelated.
    Type 'import("tsc-test").MappedResult<C extends import("tsc-test").Constructor<infer T> ? T : never>' is not assignable to type 'import("tsc-test").MappedResult<C extends import("tsc-test").Constructor<infer T> ? T : never>'. Two different types with this name exist, but they are unrelated.

14     decode<C extends Constructor<any>>(ctor: C): MappedResult<C extends Constructor<infer T> ? T : never> {
       ~~~~~~
```

**Playground Link:** [Here][0]

**Related Issues:** None I can find

[0]: https://www.typescriptlang.org/play/#src=export%20type%20Constructor%3CT%3E%20%3D%20new%20(...args%3A%20any%5B%5D)%20%3D%3E%20T%0D%0Aexport%20type%20MappedResult%3CT%3E%20%3D%0D%0A%20%20%20%20T%20extends%20Boolean%20%3F%20boolean%20%3A%0D%0A%20%20%20%20T%20extends%20Number%20%3F%20number%20%3A%0D%0A%20%20%20%20T%20extends%20String%20%3F%20string%20%3A%0D%0A%20%20%20%20T%0D%0A%0D%0A%0D%0Ainterface%20X%20%7B%0D%0A%20%20%20%20decode%3CC%20extends%20Constructor%3Cany%3E%3E(ctor%3A%20C)%3A%20MappedResult%3CC%20extends%20Constructor%3Cinfer%20T%3E%20%3F%20T%20%3A%20never%3E%0D%0A%7D%0D%0A%0D%0Aclass%20Y%20implements%20X%20%7B%0D%0A%20%20%20%20decode%3CC%20extends%20Constructor%3Cany%3E%3E(ctor%3A%20C)%3A%20MappedResult%3CC%20extends%20Constructor%3Cinfer%20T%3E%20%3F%20T%20%3A%20never%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20throw%20new%20Error()%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A

**Comment by jcalz** [comment] 2018-08-23 13:12
duplicate of #25373 ?

**Comment by andy-ms** [comment] 2018-08-23 16:01
I think this is a different issue having to do with conditoinal types.
```ts
interface I {
    m<T>(): T extends Array<infer U> ? U : never
}

class C implements I {
    m<T>(): T extends Array<infer U> ? U : never { // Error?
        throw new Error();
    }
}
```

Also, the following *should* be an error but isn't:
```ts
interface I {
    m<T>(): T extends Array<infer U> ? U : never
}

class C implements I {
    m<T>(): T {
        throw new Error();
    }
}
```

**Comment by ahejlsberg** [comment] 2018-08-26 15:35
@andy-ms The second issue isn't really meaningful because `T` is never used in a parameter position. It's basically just another way of writing a type assertion.

Consider this instead:

```ts
interface A {
    m<T>(x: T[]): T[];
}

interface B extends A {
    m<U>(x: U): U;
}
```

The above example is fine because when we instantiate `B.m` in the context of `A.m` we infer `T[]` for `U`. But we report an error on this:

```ts
interface A {
    m<T>(x: T): T[];
}

interface B extends A {
    m<U>(x: U): U;
}
```

This error is caused by inferring both `T` and `T[]` for `U` which isn't consistent.

**Comment by micah8719** [comment] 2018-11-22 22:07
The same sort of issue still exists from #16786. Consider the following (this works in C# if you look at the Enumerable.cs class: https://github.com/Microsoft/referencesource/blob/4.6.2/System.Core/System/Linq/Enumerable.cs)

```typescript
export interface IOrderedEnumerable<T> extends IEnumerable<T> {
	thenBy<TKey>(selector: (in1: T) => TKey, comparer?: IComparer<TKey>): IOrderedEnumerable<T>;
	thenByDescending<TKey>(selector: (in1: T) => TKey, comparer?: IComparer<TKey>): IOrderedEnumerable<T>;
}

export class OrderedEnumerable<T, TKey> extends Enumerable<T> implements IOrderedEnumerable<T> {
        // other code here omitted

	thenBy(selector: (in1: T) => TKey, comparer?: IComparer<TKey>): IOrderedEnumerable<T> {
		throw new Error("Not implemented");
	}

	thenByDescending(selector: (in1: T) => TKey, comparer?: IComparer<TKey>): IOrderedEnumerable<T> {
		throw new Error("Not implemented");
	}
}
```

As you see in the concrete class above, the TKey generic *should* be inferred from the class for those **thenBy** functions, but the compiler fails with the **"Two different types with this name exist, but they are unrelated"** error.

**Comment by PachowStudios** [comment] 2019-08-01 17:52
@ahejlsberg Your workaround works great, thanks!

This is pretty confusing when you run into it the first time. The documentation on conditional and inferred types should mention something about this.

**Closed** 2019-08-19 20:01 UTC
Labels: Bug

**Comment by ties-s** [comment] 2021-09-12 10:32
@ahejlsberg this work around works! Finally found it after wasting hours searching for the solution. 

This is especially annoying when trying to wrap a type as a promise, since that also doesn't work correctly with specifying a separate promise-wrapped type.

Any new on if this is going to be fixed?
