### ISSUE TITLE
`object` type is casted to `any` when `-checkJs` is used

### ISSUE THREAD

**Issue by Hotell** [Microsoft/TypeScript#27633] opened 2018-10-09 17:00 UTC
**TypeScript Version:**  3.1.1

**Search Terms:** object in js, object check-js

**Code**

```js
// @ts-check

/**
 * @param {object} value
 */
function debug(value) {
  return JSON.stringify(value, null, 2)
}

// $ExpectError 
// but no error is thrown as object is casted to any 👀
debug('hello')
```

When a indexed object is used it works correctly

```
/**
 * @param {{[key]:string}} value
 */

```

**Expected behavior:**

Compile error and `object` works like in TS file

**Actual behavior:**

value is casted to `any`

**Comment by andy-ms** [comment] 2018-10-09 17:19
Duplicate of #25624

**Comment by andy-ms** [comment] 2018-10-09 17:38
@Hotell reopened that issue, add your :+1:

**Closed** 2018-12-13 18:00 UTC
Labels: Duplicate
