### ISSUE TITLE
Unable to include a literal `NaN`, `Infinity`, or `-Infinity` in a union type

### ISSUE THREAD

**Issue by ljharb** [microsoft/TypeScript#47347] opened 2022-01-07 20:54 UTC
# Bug Report

See the link below. I want to define a function as returning either `NaN`, `1`, `2`, or `3`. I can do `1 | 2 | 3`, but TS errors when I do `NaN | 1 | 2 | 3`, and if i do `typeof NaN` it allows any number.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=7&ssc=84&pln=7&pc=1#code/MYewdgzgLgBAhgLhgCgJQwLwD4ZQJ4AOApiAGYwBycFMAPjAIyYrraXUDcMA9NzEQA8CAGwCWwUVGF54w4SADuEeGBlgArgFsARkQBOAKFCRYApBp37mcNF14wIACxDrhAExgE4ECABoYbiBEEAZG4NAw2khomDhM9ABMMMwxbAx2fAogegDWyqSiYERhJjB4SEwYkbY8fKRwosJ+8MqSDs6ubqHGEcDRrDhUNPQAkmAFYJIy9AC0YxNTdIwpA+wUGfx6etnN2uqwTi7uYADkUCURAF4VzMA19oedMGAgsF4+-nuwgcFAA)

### 💻 Code

```ts
const a: () => typeof NaN | 1 = () => NaN; // explicitly allows any number
const x: number = a(); // should pass, does

const b: () => 1 | 2 = () => 1; // works fine
const y: 1 = b(); // fails, as it should

const c: () => NaN | Infinity | -Infinity | 1 = () => NaN; // errors, but shouldn't
const z: 1 = c(); // should not pass, but does
```

### 🙁 Actual behavior

The `c` declaration errors, and the `z` assignment does not fail.

### 🙂 Expected behavior

The `c` declaration works, and the `z` assignment should fail. Why? Because `NaN` and the Infinities are just as much a number as `1` and `2` are, and I want to correctly type my API.

**Comment by fatcerberus** [comment] 2022-01-07 21:01
Note https://github.com/microsoft/TypeScript/pull/9407#issuecomment-229721835 - this was apparently a deliberate choice.

**Comment by ljharb** [comment] 2022-01-07 21:03
My compelling scenario is that npm's lockfileVersion can be 1, 2, or 3, but my API (before I tried to add typings to it) returned NaN when it can't detect the version being used.

**Comment by MartinJohns** [comment] 2022-01-07 21:16
Duplicate of #15135.

**Comment by ljharb** [comment] 2022-01-07 21:37
@MartinJohns thanks for the pointer :-) the downvote was for the decision.

**Closed** 2022-01-13 18:00 UTC
Labels: Duplicate
