### ISSUE TITLE
error TS2367:  comparison appears to be unintentional  

### ISSUE THREAD

**Issue by bcq028** [microsoft/TypeScript#54691] opened 2023-06-18 14:28 UTC
# Bug Report

### 🔎 Search Terms

enum overlap ts(2367)

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about enums

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/zh/play?ts=5.2.0-dev.20230618#code/GYVwdgxgLglg9mABBANnAzgUwCYEl0oCGY2AFAOYBOM2AXImCALYBGmlA2gLrcCU9jVu0QBvAFCJJiTIMQBlKISiZREqepzkVAXkQByTZj0AaNeskA3GOhiww5RLr1Wbd8ibPnBARkf6fHuZSNCg6+iFGngC+nqFQiNgwlJjQ8GDofhwcALTexogADFz5HHmFxYgcBfm5FVX53lxcANyeAPRtudLYWoUMcPEutjiIvj6SAEyIQ26IsZjxEHBolH5gmADuiACClJSEAJ4U1NgAdKH2UAAWvKfAMCgopAW3TIQADqSkvI4AfAybHZ7Q7HGhVLjnGTka63e6PUgKJSYU4RXi8VrqOKIGAkPwFDFSLHAIjkWiI5R+cnIiIEyRY7D7La6UgwATMNiUfIAKzZQkoP20-3EQUkMGAiFISxWHBgPC5XEQAEJdFSUdhQj9klAQJQwLTzGKJVQwbKOPLHLpvD9hSL1FK4JxTeaVYplKcfPrbVqdXrPOoYrbDSyLX0AD6hxBckMFRDh7Eh41nC7Qq6IbKjWMRqPaXSJ8GQy6p9NW1S29TEwgOF1I06GT0i+2OuUK6tuut+kXe3X1yQBhvLB0y5uU13ImY48g9xDAB0SrEcRL5bDmuDixLJVIIdDWjtBedgGD5MDOyowRAAagSh8jF4S8qn6iDB5DZ4AZK+GNndFyfkswHYQEwB9gnFSUB04A8eGPFtW2RHwdzLft-xxQDgN7XcDVAxsOEgnDnVg05x3sBDEPMP8AKAjD-SokCJWw3DoJDVVUVLUj1AZQgNlIA8jx-NDED7RCg3o01GJzeRR1rHpMBItjJGwp0Wwkmt2zkqQKyrZS22k-j1C7X02KiaQUCwbEsPAnDRPwrS4OYEsbTU8iUMowyMMEgTPBnVZSCxM9dHxeMAB5EETAsU2aC9zxgWTzC8ucFhvfyIqjYK8yKMLrgi89zx-VjEI4rjrz4mjJDinyEufJKGDPVKTgyq4svPA8YrYsqsWPPEIo62qwXS5NMsi48WrUsy6IshjrNVIjyGGkapBEqCTw0pjJMMRAAH4bKk3p6BxbBdJFdzXOO0jloImkStGsDpUUl8SFmss9ovS1+KOqR3Pc-TsRIVoolaMQAaxeJdFQDAcHwIgSFILJqkKBp4bh0Z8lh2GyiKEoyjRhGsaR3G0bqHHMYRlHseRupUeJ5GqcRwnyepknEYpvGyZKJm2cp5nRgJ6nCY5hnGgx0nOZxhn0cqIncf5nmee5zmmd5yWml4MQ-3QZZkTQchSCgZWgA)

### 💻 Code

```ts
function closedIsland(grid: number[][]): number {
    enum State {
        edge = 'edge',
        visiting = 'visiting',
        num1 = 'num1',
        idle = 'idle'
    }
    let directions = [[-1, 0], [1, 0], [0, -1], [0, 1]];
    let color = new Array(grid.length).fill(0).map(() => new Array(grid[0].length).fill(State.idle));
    let ind = 0;
    let flag:State = State.idle;
    let draw = (i: number, j: number) => {
        if (color[i][j] != State.idle) return;
        if (grid[i][j] == 1) {
            color[i][j] = State.num1;
            return;
        }
        if (i == 0 || j == 0 || i == grid.length - 1 || j == grid[0].length - 1) {
            flag = State.edge;
            color[i][j] = State.edge;
            return;
        }
        color[i][j] = State.visiting;
        for (let [di, dj] of directions) {
            let [ni, nj] = [i + di, j + dj];
            if (ni == i && nj == j) continue;
            if (color[ni][nj] == State.num1) {
                continue;
            }
            if (color[ni][nj] == State.visiting) {
                continue;
            }
            if (color[ni][nj] == State.idle) {
                draw(ni, nj);
            }
            if (color[ni][nj] == State.edge) {
                color[i][j] = State.edge;
                flag = State.edge;
                return;
            } else if (color[ni][nj] == State.num1) {
                continue;
            }
        }
    }
    for (let i = 0; i < grid.length; ++i) {
        for (let j = 0; j < grid[0].length; ++j) {
            draw(i, j);
            for (let ni = 0; ni < grid.length; ++ni) {
                for (let nj = 0; nj < grid[0].length; ++nj) {
                    if (color[ni][nj] == State.visiting) {
                        color[ni][nj] = flag == State.edge ? State.edge : ind;
                    }
                }
            }
            flag = State.idle;
            if (color[i][j] == ind) {
                ind += 1;
            }
        }
    }
    return ind;
};



let t = closedIsland([[0, 0, 1, 1, 0, 1, 0, 0, 1, 0], [1, 1, 0, 1, 1, 0, 1, 1, 1, 0], [1, 0, 1, 1, 1, 0, 0, 1, 1, 0], [0, 1, 1, 0, 0, 0, 0, 1, 0, 1], [0, 0, 0, 0, 0, 0, 1, 1, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1, 1, 1], [1, 0, 1, 0, 1, 1, 0, 0, 0, 1], [1, 1, 1, 1, 1, 1, 0, 0, 0, 0], [1, 1, 1, 0, 0, 1, 0, 1, 0, 1], [1, 1, 1, 0, 1, 1, 0, 1, 1, 0]])
console.log(t)

```

### 🙁 Actual behavior

TSError: ⨯ Unable to compile TypeScript:
index.ts(52,41): error TS2367: This comparison appears to be unintentional because the types 'State.idle' and 'State.edge' have no overlap.

    at createTSError (D:\Projects\playground\ts\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (D:\Projects\playground\ts\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (D:\Projects\playground\ts\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (D:\Projects\playground\ts\node_modules\ts-node\src\index.ts:1433:41)
    at Module.m._compile (D:\Projects\playground\ts\node_modules\ts-node\src\index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (D:\Projects\playground\ts\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [ 2367 ]

### 🙂 Expected behavior

I cannot figure out where something wrong. if I add @ts-ignore, the code snippiest can run well.

**Comment by MartinJohns** [comment] 2023-06-18 15:03
Duplicate of #9998.

**Closed** 2023-06-19 03:20 UTC

**Comment by c0dezer019** [comment] 2024-02-21 21:50
In addition to @MartinJohns response, TS does not like it when you try to compare values of two different data types, they need to be of the same type or of type "unknown".

**Comment by sridhar-neartekpod** [comment] 2024-07-31 06:47
in Next js 14 i faced this ts error

`
const TablesPage = ({ params }: { params: { slug: "add" | "edit" } }) => {
  const { slug } = params;

  <h4 className="mb-px text-lg font-bold text-dark dark:text-white">
                                  Expense{" "}
                                  {slug === "add" ? "created" : "updated"}
                                </h4>
`
  
  err:  This comparison appears to be unintentional because the types '"edit"' and '"add"' have no overlap
  
  
![image](https://github.com/user-attachments/assets/35cc9ffa-60fd-49fe-ab08-f5dabbd9e4d5)

**Comment by NightSpector** [comment] 2025-05-22 16:46
import { cn } from '@/lib/utils'
import Image from 'next/image'
import React from 'react'

enum callStatus {
    INACTIVE = "INACTIVE",
    CONNECTING = "CONNECTING",
    ACTIVE = "ACTIVE",
    FINISHED = "FINISHED",
}

const Agent = ({ userName }: AgentProps) => {

    const isSpeaking = true

    return (
        <>
            <div className="call-view">
                <div className="card-interviewer">
                    <div className="avatar">
                        <Image
                            src="/ai-avatar.png"
                            alt="profile-image"
                            width={65}
                            height={54}
                            className="object-cover"
                        />

                        {isSpeaking && <span className="animate-speak" />}
                    </div>

                    <h3>AI Interviewer</h3>
                </div>

                <div className="card-border">
                    <div className="card-content">
                        <Image
                            src="/user-avatar.png"
                            alt="profile-image"
                            width={539}
                            height={539}
                            className="rounded-full object-cover size-[120px]"
                        />

                        <h3>{userName}</h3>
                    </div>
                </div>
            </div>

            <div className="w-full flex justify-center">
                {callStatus !== "ACTIVE" ? (
                    <button>
                        <span>
                            {callStatus === "INACTIVE" || callStatus === "FINISHED"
                                ? "Call"
                                : ". . ."}
                        </span>
                    </button>
                ) : (
                    <button className="btn-disconnect">
                        End
                    </button>
                )}
            </div>
        </>
    )
}

export default Agent


same error please help
