### ISSUE TITLE
TypeScript autocompletion broken for generic function parameter with optional properties

### ISSUE THREAD

**Issue by timsuchanek** [Microsoft/TypeScript#30212] opened 2019-03-04 15:28 UTC
- VSCode Version: Version 1.31.1 (1.31.1)
- OS Version: macOS High Sierra 10.13.6

Steps to Reproduce:

![typescript autocompletion](https://user-images.githubusercontent.com/1094804/53742843-de2e3780-3e99-11e9-8cec-d85a28736f91.gif)

Open a TypeScript file with this content:

```ts
type Params = {
  foo?: string
  bar?: number
  visible?: boolean
}

export const obj = {
  paramsIdentityInline<T extends Params>(params: T): T {
    return params
  },
}

obj.paramsIdentityInline({
  
})

function direct(params: Params) {}

direct({

})
```

When you have a type which only consists of optional properties and use it in a generic context as a type parameter, the autocompletion doesn't work, while it works when you use that type directly without being generic in the function signature.
However, as soon as at least one of the properties on that type is non-optional, the autocompletion works, even for the optional properties.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-03-06 22:06
Looks like a duplicate of #30058

Please try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions) to see if this issue has been fixed for you

**Closed** 2019-03-10 18:00 UTC
Labels: Duplicate

**Comment by timsuchanek** [comment] 2019-03-11 11:02
Thanks! I just checked it - it works in `@next`!

**Comment by hediet** [comment] 2019-03-11 12:22
It however does not work for me in `@next`
![image](https://user-images.githubusercontent.com/2931520/54123648-8b580100-4400-11e9-9a22-2561bc85b418.png)

@mjbvz It's not an exact duplicate, as it only does not work when using type constraints (see `paramsIdentityInline`).

**Comment by timsuchanek** [comment] 2019-03-14 13:47
**Edit**
@hediet  It indeed doesn't yet work. I checked it on another example, but this exact example indeed still doesn't work.

@mjbvz please reopen 🙂

And let me know if we can do anything to speed up the fixing / where to look into the code to fix it ourselves, as we need it for the library we're building 🙏

**Comment by hediet** [comment] 2019-03-20 16:37
@timsuchanek I just noticed that you were also a student at the KIT ;)
As luck would have it, I guess you are also following [an approach similar to this one](https://gist.github.com/hediet/1daa00a21ef69dd8cabb86c6e6558223) to implement a typescript graphql query library without the need of generating source code? :D
At least this is what me made looking for this issue...
