### ISSUE TITLE
[Feature request] allow use  T<any>, without TS2315: Type 'T' is not generic.

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#31625] opened 2019-05-28 18:31 UTC
## Suggestion

> allow use  T<any>, without TS2315: Type 'T' is not generic.

## Use Cases

```ts
interface F1<T>
{
	(a: boolean): boolean;
	(a: string): string;
}

interface I1<T extends F1<any>>
{
	fr1: Parameters<T<any>>[0]
}
```

> TS2315: Type 'T' is not generic.

## Examples

maybe looks like this

```ts
interface I1<T extends F1<any>>
{
	fr1: Parameters<T<any>>[0]
}
```

or

```ts
interface I1<T extends typeof F1>
{
	fr1: Parameters<T<any>>[0]
}
```

or

```ts
interface I1<T extends import F1>
{
	fr1: Parameters<T<any>>[0]
}
```

or

```ts
interface I1<T extends is F1>
{
	fr1: Parameters<T<any>>[0]
}
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jcalz** [comment] 2019-05-28 19:06
This kind of looks like a duplicate of #1213 but I can't tell.

The example is strange because `F1<T>` does not depend structurally on `T`, which is a bad idea (see FAQ [here](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at--) and [here](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot---)).  What does your expect `I1` to mean?  Like, what does `I1<F1<boolean> & {foo: string}>` evaluate to?

Also, *please*, fill this out when you file an issue:

> ## Search Terms

You should be searching for existing issues so you're not just making extra work for the maintainers of this repository.

**Comment by RyanCavanaugh** [comment] 2019-05-28 21:58
I'm also going to assume it's a duplicate of #1213 but it would be nice to not have to guess.

**Closed by RyanCavanaugh** 2019-05-28 21:58 UTC
Labels: Unactionable
