### ISSUE TITLE
Playground + JS: Errors not underlined

### ISSUE THREAD

**Issue by sKopheK** [microsoft/TypeScript#38389] opened 2020-05-07 11:05 UTC
**TypeScript Version:**  3.9.0-beta

**Search Terms:**
playground, errors, js

**Code**
```js
/** @param {number} n */
function tripple(n) {
    return n * 3;
}

class A {
    mygod() {
        return "yes?";
    }
}

tripple('x'); // <-- Argument of type '"x"' is not assignable to parameter of type 'number'.
tripple(2);

const i = new A();
i.xx(); // <-- Property 'xx' does not exist on type 'A'.
```

[Playground Link](https://www.typescriptlang.org/v2/en/play?ts=3.9.0-beta&useJavaScript=true#code/PQKhAIAEAcEMCdYFtwG8B2BXJAjApvAL7jrgjABQAZpugMYAuAlgPakPxPTQA2eAFOgCUaCuHHh4eBpnilSEAMwBuCoQoU6PWAGcd4AIKiJ4JAE8A5iwAm-EajEmJUmXPAAiM3h0B+d6pN1dQoOLl4BAHIADwihZXBgYHAAHgBaVMN4C2w8dAZwFipwBjNoPHAI9yj3CPAmfXQWfN0dJgt0WBw+YpZwOEQkaQICopKyiqxcAgiAOhDObj5+ACY4jTo2HXymcABeEjwAd0M7VSYZqKjThKS0jIAFeBYy+BKKy9rrFm8SJvA8KL1fJsYqlcoRAyzDRAA)

![image](https://user-images.githubusercontent.com/5802917/81287188-fb532d00-907f-11ea-8b58-5bba3e9e9268.png)

**Expected behavior:** Statements with invalid argment type / non-existing type property errors are underlined. 

**Actual behavior:** No underline of invalid argment type / non-existing type property errors. Currently, errors are displayed only in the side Errors tab and can be clicked upon which navigates you the problematic line. However, underlining of syntax errors works ok. 

**Related Issues:** N/A

**Comment by IllusionMH** [comment] 2020-05-07 14:31
Duplicate of https://github.com/microsoft/TypeScript-Website/issues/201

**Closed** 2020-05-11 18:00 UTC
Labels: Duplicate
