### ISSUE TITLE
package.json#imports doesn't get IDE suggestions when typing the import path directly

### ISSUE THREAD

**Issue by anthonyshew** [microsoft/TypeScript#57680] opened 2024-03-07 18:49 UTC
### 🔎 Search Terms

package.json imports, package.json imports intellisense, package.json imports autocomplete, package.json import suggestions

### 🕗 Version & Regression Information

This feature released with v5.4 yesterday so not too much bisection to be done. 😄

### ⏯ Playground Link

https://github.com/anthonyshew/packagejson-imports-typescript-suggestions

### 💻 Code

I apologize for not following the standards of the template to provide a TypeScript playground. I couldn't find a way to work with imports or a package.json there. If that is possible and I missed it, please let me know so I can update appropriately.

Reproduction repository: https://github.com/anthonyshew/packagejson-imports-typescript-suggestions

package.json#import: https://github.com/anthonyshew/packagejson-imports-typescript-suggestions/blob/b33225588c9ca061807f8c1cb55c50dff66ef581/package.json#L6

Attempted inference: https://github.com/anthonyshew/packagejson-imports-typescript-suggestions/blob/b33225588c9ca061807f8c1cb55c50dff66ef581/app/page.tsx#L1

### 🙁 Actual behavior

With your cursor on the path string for the import on line 1 of `./app/page.tsx`, opening suggestions does not provide autocomplete.
![CleanShot 2024-03-07 at 11 39 38@2x](https://github.com/microsoft/TypeScript/assets/35677084/0007dd4e-8d37-41c6-8040-876356b76d0f)

### 🙂 Expected behavior

I was hoping to see a suggestion for `#components/TestComponent.tsx`. Notably, if I write it out fully myself, my editor is happy and my build compiles/bundles successfully so I'm relatively certain that I am set up correctly.

### Additional information about the issue

I did some light futzing with the `"allowImportingTsExtensions"` and `"verbatimModuleSyntax"` compiler options in my `tsconfig.json` and was noticing some un-aligned behavior. I'm not sure if this is deserving of another bug report or is related.

As an example, auto-importing seems to use `verbatimModuleSyntax` (or something like it) even when I don't have that flag enabled. Again, not certain if related.
![CleanShot 2024-03-07 at 11 43 15@2x](https://github.com/microsoft/TypeScript/assets/35677084/3a80b987-6cf8-4f00-933c-de8544a8a47a)

**Comment by Andarist** [comment] 2024-03-07 19:14
The primary focus of the related PR was on auto-imports. I suspect that completions in import sources might be using an entirely different set of methods. With auto-imports, it was a question of figuring out an algorithm to return an alternative module source for a relative source. What you are asking for here is to generate all of those potential extra sources ahead of time and fuzzy-match~ against them when suggesting completions in import statements.

It's quite unfortunate that we've missed this use case - but I'm not sure if this can be fast-pathed to 5.4 as it's not exactly a critical bug fix. cc @andrewbranch WDYT?

> As an example, auto-importing seems to use verbatimModuleSyntax (or something like it) even when I don't have that flag enabled. Again, not certain if related.

To get it right - you expect `#components/TestComponent.tsx` to be used by the auto-import here, right?

**Comment by fatcerberus** [comment] 2024-03-07 19:18
> I apologize for not following the standards of the template to provide a TypeScript playground. I couldn't find a way to work with imports or a package.json there. If that is possible and I missed it, please let me know so I can update appropriately.

Yeah no, you can't.  The playground is just a simple single-file environment with a GUI for setting `tsconfig.json` options and that's about it.  Anything more complex you need to provide a GitHub repo or something.

@Andarist What related PR?  I didn't see one mentioned in the OP and you didn't link to one.

**Comment by Andarist** [comment] 2024-03-07 19:19
https://github.com/microsoft/TypeScript/pull/55015

**Comment by andrewbranch** [comment] 2024-03-07 19:38
Duplicate of https://github.com/microsoft/TypeScript/issues/52460

**Comment by anthonyshew** [comment] 2024-03-07 19:38
@Andarist Gotcha, that all makes sense and definitely respect the difference.

I also just noticed while messing around some more that this works correctly - so it's very specifically the fuzzy matcher that doesn't work.
![CleanShot 2024-03-07 at 12 36 30@2x](https://github.com/microsoft/TypeScript/assets/35677084/b165cc2d-9c46-4d27-8152-1c467cfc19f8)


> To get it right - you expect #components/TestComponent.tsx to be used by the auto-import here, right?


Correct, the auto-import is pointing at `.jsx` when the file on disk is `.tsx`.

**Comment by anthonyshew** [comment] 2024-03-07 19:41
@andrewbranch Oops, wasn't savvy enough to put "subpath" in my search terms. Feel free to close here.

**Comment by andrewbranch** [comment] 2024-03-07 19:49
> I also just noticed while messing around some more that this works correctly - so it's very specifically the fuzzy matcher that doesn't work.

The screenshot you’re showing is an extension of auto-imports, and came for free with #55015. Path completions, when you’re typing inside an existing string literal module specifier, is a totally different code path and is just missing an implementation. Subpath exports work in path completions, so it shouldn’t be too hard to make subpath imports work, but the code there is not super approachable. The issue is marked Help Wanted and would be a really high-value contribution IMO.

**Comment by Andarist** [comment] 2024-03-07 22:20
> The issue is marked Help Wanted and would be a really high-value contribution IMO.

<img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYXVzeGR1OXpidnBzNXE0dTIyMXVmZWpwY2Vzc2NycnM2Nm1lMWl6biZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/srTYyZ1BjBtGU/giphy.gif" alt="That's bait"/>

**Comment by fatcerberus** [comment] 2024-03-09 01:58
@Andarist I know this is off-topic but curiosity got the better of me… what movie is that?

**Comment by Andarist** [comment] 2024-03-09 11:44
Mad Max: Fury Road, I think

**Closed** 2024-03-12 01:24 UTC
Labels: Duplicate
