### ISSUE TITLE
[Transforms] Where should comment after "{" in getter be placed when emitting down-level

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#8205] opened 2016-04-20 00:22 UTC
**Original**
```ts
    get X() { // ok
        return '';
    }
```
**Expected**
```js
    get: function() { // ok
        return '';
    }
```
**Result**
```js
        get: // error
        function () {
            return '';
        }
```

numericIndexerConstrainsPropertyDeclarations.js

**Comment by sandersn** [comment] 2016-04-20 19:22
This is likely a duplicate of #8209 but I'll leave it open in case it's not.

**Comment by yuit** [comment] 2016-04-20 23:54
There are related and share similar fix though at slightly different location

**Closed** 2016-04-21 21:53 UTC
Labels: Bug, Domain: Transforms, Duplicate
