### ISSUE TITLE
Class properties are not definitely assigned in constructor when using Object.assign

### ISSUE THREAD

**Issue by c-o-l-o-r** [Microsoft/TypeScript#28883] opened 2018-12-06 22:29 UTC
**TypeScript Version:**  3.1.6

**Search Terms:**
- merge objects typescript
- object.assign typescript

**Code**

```ts
interface Identity {
    name: string
}

class Person implements Identity {
    name: string

    constructor(id: Identity) {
        Object.assign(this, id)
    }
}
```

**Expected behavior:**
Assign the `Person`'s `name` property to the `name` property in `id`.

**Actual behavior:**
Compilation error: `Property 'name' has no initializer and is not definitely assigned in the constructor. [2564]`

**Playground Link:** http://www.typescriptlang.org/play/#src=interface%20Identity%20%7B%0D%0A%20%20%20%20name%3A%20string%0D%0A%7D%0D%0A%0D%0Aclass%20Person%20implements%20Identity%20%7B%0D%0A%20%20%20%20name%3A%20string%0D%0A%0D%0A%20%20%20%20constructor(id%3A%20Identity)%20%7B%0D%0A%20%20%20%20%20%20%20%20Object.assign(this%2C%20id)%0D%0A%20%20%20%20%7D%0D%0A%7D

be sure to click on `strictNullChecks`, `strictFunctionTypes`, and `strictPropertyInitialization`

**Comment by weswigham** [comment] 2018-12-06 23:20
Duplicate of #26792

**Closed** 2018-12-12 10:00 UTC
Labels: Duplicate
