### ISSUE TITLE
FEATURE: support for mixin/trait (by language new keyword)

### ISSUE THREAD

**Issue by kamil-kielczewski** [Microsoft/TypeScript#16787] opened 2017-06-28 06:22 UTC
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

In typescript [documentation about mixins](https://www.typescriptlang.org/docs/handbook/mixins.html) is described that typescript support mixins/traits - this is in fact not true because programmer need implements everything himself - so where is support?. 

Proper support for mixin should be by language KEYWORD like **mixin** or **trait & use** ([like in php](http://php.net/manual/en/language.oop5.traits.php)). And programer should use it in this way (without double mixin methods definition stub):

```ts
class SmartObject mixin Disposable, Activatable {
    constructor() {
        setInterval(() => console.log(this.isActive + " : " + this.isDisposed), 500);
    }

    interact() {
        this.activate();
    }
}
```

(i use example context from documentation for which link I give above) 

And thats all! Any rendundant mehtod/fields deinition shouldn't be inside class **SmartObject** and also any **applyMixins** should not be written by TS programmer. If we will achieve this, then we can say that TS support mixins/traits. 

**Expected behavior:**

Look description above

**Actual behavior:**

Look description above

**Comment by andy-ms** [comment] 2017-06-28 15:34
Duplicate of #7798 and #2919.
See TypeScript's [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals). Specifically: Avoid adding expression-level syntax. (Classes count as expressions.)

**Comment by mhegazy** [comment] 2017-09-11 16:13
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-11 16:13 UTC
Labels: Duplicate, Out of Scope
