### ISSUE TITLE
EventTarget interface not generic

### ISSUE THREAD

**Issue by lilred** [Microsoft/TypeScript#3599] opened 2015-06-22 18:32 UTC
`EventTarget` objects expose an `addEventListener` method, which registers an `EventListener` (or `EventListenerObject`) with the target. An `EventListener` is simply a function from some `Event` to `void`; however, many `EventTarget` objects pass an argument to their `EventListener`s with more structure than just `Event`.

This is a problem because we completely lose type safety when using `addEventListener`. We're forced to let the argument to the `EventListener` be `any`; coercing it to a more specific type gives an error.

`EventTarget` objects should be generic on the type of events being emitted. This would be a breaking change, though.

**Comment by RyanCavanaugh** [comment] 2015-06-22 19:05
> This is a problem because we completely lose type safety when using addEventListener. We're forced to let the argument to the EventListener be any

Can you post some examples of how this happens? In general you should be able to provide a function that takes a more-specific type as an argument.

**Comment by mhegazy** [comment] 2015-06-23 16:38
is this different from  #299?

**Comment by danquirk** [comment] 2015-07-08 19:08
Gonna call this a dupe of the issue Mohamed mentioned unless we get more info.

**Closed by danquirk** 2015-07-08 19:08 UTC
