### ISSUE TITLE
using a toLowerCase function inside the if block type error

### ISSUE THREAD

**Issue by Ravi-exe** [microsoft/TypeScript#59091] opened 2024-07-01 16:28 UTC
### 🔎 Search Terms

toLowerCase if block is in typescript.

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

type getIDSNoResBody = {
     status: "success",
    IdsNo: string;
}  |  {
    status: "fail",
    message: string;
}

const loginAPIResBody = await getIDSNo(data) as getIDSNoResBody 

if (loginAPIResBody.status.toLowerCase() === "success"){
  const IdsNo = loginAPIResBody.IdsNo
}

### 🙁 Actual behavior

I have response body with only two possible object. either one is 

1> {
 status: success, 
 IdsNo: string 
} 
 
2> {
status: 'fail',
message: string
}

When using the toLowerCase() function in an if condition to check for a match with the keyword 'success', the compiler reports an error stating that 'IdsNo' does not exist on type error.

### 🙂 Expected behavior

If the response object contains a "status" field with the value "success", it is expected to include an "IdsNo" field of type string, regardless of whether we use the toLowerCase() function to check the "status" key in an if block.

**Comment by nmain** [comment] 2024-07-01 17:11
>Search Terms: toLowerCase if block is in typescript.

This is a duplicate of https://github.com/microsoft/TypeScript/issues/44268, which those search terms do find.

**Closed** 2024-07-04 01:30 UTC
Labels: Duplicate
