### ISSUE TITLE
Generic methods are not properly inferred when used as a value

### ISSUE THREAD

**Issue by david-driscoll** [Microsoft/TypeScript#5251] opened 2015-10-14 14:10 UTC
I think I have noticed a problem with Generic Methods, not properly inferring their types, when they are used as a value, instead of as a method.   I'm not sure if it's a known issue or not.

It's easy enough to work around by using a function, but I'd prefer to just hand in the method, since it's already a method that can be called.

This case is in Rx, but I've seen other examples of it too.

```typescript
var observableOfAny = Observable.from(items)
    .flatMap(Observable.from); // using as a variable doesn't work

var observableOfString = Observable.from(items)
    .flatMap(x => Observable.from(x)); // Using a delegate works

var fromString: (arr: string[]) => Observable<string> = Observable.from;
var observableOfString = Observable.from(items)
    .flatMap(fromString); // Properly casting the method works
```

I've got an example, again using rx interfaces (so maybe something is wrong with them? it's possible).  [playground example](http://www.typescriptlang.org/Playground#src=%2F%2F%20Type%20alias%20for%20observables%20and%20promises%0Atype%20ObservableOrPromise%3CT%3E%20%3D%20IObservable%3CT%3E%20%7C%20Observable%3CT%3E%20%7C%20Promise%3CT%3E%3B%0A%2F%2Ftype%20ArrayLike%3CT%3E%20%3D%20Array%3CT%3E%20%7C%20%7B%20length%3A%20number%3B%5Bindex%3A%20number%5D%3A%20T%3B%20%7D%3B%0A%2F%2F%20Type%20alias%20for%20arrays%20and%20array%20like%20objects%0Atype%20ArrayOrIterable%3CT%3E%20%3D%20ArrayLike%3CT%3E%3B%0Ainterface%20Promise%3CT%3E%20%7B%0A%20%20%20%20then%3CR%3E(onFulfilled%3A%20(value%3A%20T)%20%3D%3E%20R%7CPromise%3CR%3E%2C%20onRejected%3A%20(error%3A%20any)%20%3D%3E%20Promise%3CR%3E)%3A%20Promise%3CR%3E%3B%0A%20%20%20%20then%3CR%3E(onFulfilled%3A%20(value%3A%20T)%20%3D%3E%20R%7CPromise%3CR%3E%2C%20onRejected%3F%3A%20(error%3A%20any)%20%3D%3E%20R)%3A%20Promise%3CR%3E%3B%0A%7D%0Ainterface%20IPromise%3CT%3E%20extends%20Promise%3CT%3E%20%7B%20%7D%0Aexport%20type%20_Selector%3CT%2C%20TResult%3E%20%3D%20(value%3A%20T%2C%20index%3A%20number%2C%20observable%3A%20Observable%3CT%3E)%20%3D%3E%20TResult%3B%0Aexport%20type%20_ValueOrSelector%3CT%2C%20TResult%3E%20%3D%20TResult%20%7C%20_Selector%3CT%2C%20TResult%3E%3B%0Ainterface%20IObservable%3CT%3E%20%7B%20%7D%0Ainterface%20Observable%3CT%3E%20%7B%0A%20%20%20%20flatMap%3CTResult%3E(selector%3A%20_ValueOrSelector%3CT%2C%20ObservableOrPromise%3CTResult%3E%3E)%3A%20Observable%3CTResult%3E%3B%0A%20%20%20%20toArray()%3A%20Observable%3CT%5B%5D%3E%3B%0A%7D%0Aexport%20interface%20ObservableStatic%20%7B%0A%20%20%20%20from%3CT%3E(array%3A%20ArrayOrIterable%3CT%3E)%3A%20Observable%3CT%3E%3B%0A%7D%0Aexport%20var%20Observable%3A%20ObservableStatic%3B%0Avar%20fromString%3A%20(arr%3A%20string%5B%5D)%20%3D%3E%20Observable%3Cstring%3E%20%3D%20Observable.from%3B%0A%0Avar%20items%20%3D%20%5B'1'%2C'2'%2C'3'%5D%3B%0A%0Avar%20observableOfAny%20%3D%20Observable.from(items)%0A%20%20%20%20.flatMap(Observable.from)%3B%0A%0Avar%20observableOfAny%20%3D%20Observable.from(items)%0A%20%20%20%20.flatMap(x%20%3D%3E%20Observable.from(x))%3B%0A%0Avar%20observableOfAny%20%3D%20Observable.from(items)%0A%20%20%20%20.flatMap(fromString)%3B%0A%0A%0A)

**Comment by mhegazy** [comment] 2015-11-13 05:54
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/3410.  also see https://github.com/Microsoft/TypeScript/issues/5616#issuecomment-155908235.

**Closed by mhegazy** 2015-11-13 05:54 UTC

**Comment by mhegazy** [comment] 2017-05-18 18:06
tracked by https://github.com/Microsoft/TypeScript/issues/5616
