### ISSUE TITLE
Cannot export a default abstract class inline

### ISSUE THREAD

**Issue by danfma** [Microsoft/TypeScript#10553] opened 2016-08-26 04:49 UTC
The compiler does not allow me to export a default abstract class from a file.

Example:

```typescript
export default abstract class MyClass {
}
```

but I can do export when separating the definition from the export.

tsconfig.json

```json
{
  "compilerOptions": {
    "module": "amd",
    "target": "es5",
    "lib": [
      "es5", "es2015"
    ],
    "jsx": "react",
    "noEmitHelpers": true,
    "noImplicitAny": false,
    "noEmitOnError": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "moduleResolution": "node",
    "rootDir": "src"
  },
  "exclude": [
    "node_modules",
    "jspm_packages",
    "lib"
  ]
}
```

**Comment by mhegazy** [comment] 2016-08-26 04:53
Duplicate of https://github.com/Microsoft/TypeScript/issues/3792

![image](https://cloud.githubusercontent.com/assets/8000722/17994524/4dcf7af2-6b0e-11e6-8e99-66d08ee9dc3d.png)

**Closed by mhegazy** 2016-08-26 04:53 UTC
Labels: Duplicate
