### ISSUE TITLE
Overloading methods in multiple implementations

### ISSUE THREAD

**Issue by fuson** [microsoft/TypeScript#53720] opened 2023-04-10 11:38 UTC
# Bug Report

### 🕗 Version & Regression Information
5.0.3

### 💻 Code

interface A<P1, P2> {
    pick(p: P1): P2;
}

interface A1 extends A<11, 12> {
}

interface A2 extends A<21, 22> {
}

class CA implements A1, A2 {
    pick(p: 11): 12;
    pick(p: 21): 22;
    pick(p: any): any {
        if (p === 11) return 12;
        if (p === 21) return 22;
    };
}

type AType = A1 | A2;

const a: AType = new CA();
const e: 11 = 11;

const yyy = a.pick(e);

### 🙁 Actual behavior

Parameter looks like never

### 🙂 Expected behavior

Parameter looks like 11 | 21

**Comment by jcalz** [comment] 2023-04-10 11:43
This is working as intended; `AType`’s `path` is a union of functions and takes an intersection of its parameters, as described in https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-3.html#improved-behavior-for-calling-union-types

If you want `AType`’s path to be an overload of two call signatures then you should use an intersection `A1 & A2` instead.

**Comment by MartinJohns** [comment] 2023-04-10 11:44
This is working as intended.

You have the type `AType` that is either `A1` **or** `A2`. The compiler doesn't know which of those two it is, so in order to safely call the method you must provide an argument that is compatible with **both** types: `11 & 21`. Such a type is invalid, resulting in `never`.

**Comment by fuson** [comment] 2023-04-10 11:49
Martin, tnx for explanation, but any idea how to implement same logic proper way? I need from CA class to support both A1 and A2 interface.

**Comment by MartinJohns** [comment] 2023-04-10 11:56
Your class `CA` supports both interfaces, your type `AType` doesn't. Instead of `A1 | A2` (either of) you should use `A1 & A2` (both of) as suggested by jcalz.

**Comment by fuson** [comment] 2023-04-10 11:59
@MartinJohns but A1 & A2 don't give an option to call it with  
pick(p: 11): 12;
 OR
pick(p: 21): 22;

I cant write 
class CA implements A1 | A2 

so i have no idea how to implement class then support A1 AND A2, and call instance methods like A1 OR A2 :)

**Comment by MartinJohns** [comment] 2023-04-10 12:10
> so i have no idea how to implement class then support A1 AND A2, and call instance methods like A1 OR A2 :)

You do it **exactly** as you do it in your code example. That's how you do it. The issue here is your type `AType`, as mentioned several times.

Your class `CA` can be assigned to these types:
- `A1`, allowing you to call it **only** with `11`.
- `A2`, allowing you to call it **only** with `21`.
- `A1 & A2`, allowing you to call it with **either** `11` **or** `21`.
- `CA` , allowing you to call it with **either** `11` **or** `21`.

You can **not** assign it to a variable typed `A1 | A2` and call it with either `11` or `21`, because this type says the implementation is **either** `A1` **or** `A2`. So if it's implemented as `A1` calling it with `21` would be invalid, and vice versa.

This might be better suited to some kind of support forum. The TypeScript issue tracker is not meant as a support forum to understand the fundamentals of TypeScript.

**Comment by fuson** [comment] 2023-04-10 12:13
Looks like no idea how to receive result with type resolution to 12 when call with 11 and type 22 when call with 21. Sorry if my issue looks like bullshit.

**Comment by jcalz** [comment] 2023-04-10 12:53
I'm not sure why there seems to be a communication breakdown here.  All concrete evidence points to you wanting `A1 & A2` instead of `A1 | A2`. If it needs to be explicitly written out, here it is: 

```ts
type AType = A1 & A2; // <-- intersection is what you want, not union
const a: AType = new CA();
const e: 11 = 11;
const yyy = a.pick(e); 
//    ^? const yyy: 12 // <-- right? this is what you want?
const zzz = a.pick(21);
//    ^? const zzz: 22 // <-- this too?
```
[Playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIIB4AKBGANMzAJgD5kBvZAB2AQGsAKSgLgOwEoWiBuZAXwChQkWIhSpsyCAA9IIACYBnNOmx5k2EuT6Dw0eEjSFJMiPKUZCawpooCEAGzgKlAYVTJgAW0r2In02DmaqhGZPzIEVQ0DMzq7CwaXOGR1HSMLJYcyNZJkVFpsXAgAJ5ZRcXkyXkRwDDIjMgAvM1xbMhQEGAArlAg6oS51TV1Dc2N2eztnT19OVV8SQL8YMWUYgAqqyjj4sgAZIZJCAD2IApgyHAsqJtrTcggEADuyG70bEen55IJEuOqnzOF2KIPucAAdKkGBAPsh+AB6eF5AB6AH5+CcgcgAF64sGQ6L0TJJREo9H8ClAA)

There's no TypeScript bug here.  @fuson, if you want to be helpful you should close the issue so that the TS team doesn't have to spend time reviewing and closing it themselves.  And after that if you still want to discuss this because something doesn't make sense to you, the [TypeScript Discord server](https://discord.com/invite/typescript) might be a more appropriate place.  Good luck!

**Closed** 2023-04-10 13:04 UTC
