### ISSUE TITLE
TS2.1 regression in emit for emitDecoratorMetadata 

### ISSUE THREAD

**Issue by evmar** [Microsoft/TypeScript#13704] opened 2017-01-26 20:25 UTC
Minimal repro:

In api.d.ts:
```
export declare class Entity {}
```

In use.ts:
```
import {Entity} from './api';

declare var Decorate: any;
class User {
  @Decorate() x: Entity|undefined;
}
```

In tsc 2.0.6, the emit for use.js looks like:

```
    __decorate([
        Decorate(), 
        __metadata('design:type', Object)
    ], User.prototype, "x", void 0);
```
Note the `Object`.

In tsc 2.1.5, the emit becomes:
```
__decorate([
    Decorate(),
    __metadata("design:type", api_1.Entity)
], User.prototype, "x", void 0);
```

where `api_1` is undefined (there's no `require` statement).

Note that if you add another reference to `Entity`, e.g. you add a property like
```
  @Decorate() x: Entity;
```
then in both tsc 2.0 and 2.1 the emit produces a `require` statement so either version of the generated code (with `Object` or `api_1`) works.

Somehow `Entity|undefined` causes the `require` statement to be elided.

**Comment by vladima** [comment] 2017-01-26 20:44
looks like a dupe of https://github.com/Microsoft/TypeScript/issues/13449

**Closed** 2017-04-21 16:56 UTC
Labels: Duplicate
