### ISSUE TITLE
Optional parameters indicated via JSDoc are not respected

### ISSUE THREAD

**Issue by mihaip** [Microsoft/TypeScript#8734] opened 2016-05-21 23:13 UTC
**TypeScript Version:** nightly (1.9.0-dev.20160521) (same behavior in 1.8.10).

Given this plain JavaScript file annotated with JSDoc for the Closure Compiler (included via `allowJs`):

```js
/**
 * @param {number=} input
 * @return {number}
 */
function legacyMethod(input) {
    if (typeof input === "undefined") {
        return 0;
    }
    return input * input;
};
```

And this TypeScript file:

```ts
console.log(legacyMethod(1));
console.log(legacyMethod());
```

I would expect that the second `legacyMethod` call to also be fine, due to the `=` suffix on the type (see https://developers.google.com/closure/compiler/docs/js-for-compiler#types for more details on the Closure Compiler type language). Based on Visual Studio Code's Intellisense the extracted type for `legacyMethod` is `function legacyMethod(input?: number): number` which seems correct. However, when running, I get:

```main.ts(2,13): error TS2346: Supplied parameters do not match any signature of call target.```

Out of curiosity, I tried `legacyMethod(undefined)` which worked (as did `legacyMethod(null)`, which the Closure Compiler would not have allowed, since optional parameters are undefined, not null).

**Comment by sandersn** [comment] 2016-06-10 22:16
Duplicate of #6992 -- that bug also has some interesting discussion about what to do in the case that we still can't find a matching signature.

**Closed by sandersn** 2016-06-10 22:16 UTC
Labels: Bug, Duplicate, Salsa
