### ISSUE TITLE
Property with getter: This condition will always return 'false'

### ISSUE THREAD

**Issue by blaumeise20** [microsoft/TypeScript#46771] opened 2021-11-11 08:01 UTC
# Bug Report

### 🔎 Search Terms

- getter condition

### 🕗 Version & Regression Information

- This seems like intended behavior (it is sometimes, but not in this case)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAECiAeYC2AHEBTaBvAUNaKATgJYBuYALpgOboXQD6AZgPYsAUAlNnvtIXQCuhAHbQAspQAWAOkJgRAExZIu0ADzQADDICs0APzQARGGPQAXCYBGxgNy8Avjl7WwhNbj7RiTaOwopYggZZjZoAF4okzNuL29oYBYRCBYMGRAWanZjahZ6AHIwAuNOBwToAHpK6EDg6HRCQhZCaAgpFkEQRWgRfOgWYGBhC15vX386kLCWSOjjWzixhKSUtPQMrJyQQWAAawBPRMh0ABpoPMLrAtq2UvKE528n6GdnHFBIGABlFAUefC0ejoJSefhCUS1IIhCAUdz0ADUUOCGRB1ECr14q1hhF2FBa7BQgmsIGIwDacMIFCsIkESGsjXORJJZOgGBE6KkNLpDMIcTeLmx9AgfzEEV66AA7tBfgp2AAWc4AJjKLgm7BFChkIJ60QAbEt8JqRKiORiEeKAIwPaptZCYKSNdCjfDq43apRzaAAdkNfGx6022WMkpae3QinuThwjiAA)

### 💻 Code

```ts
class Example {
  private get _foo() {
    return Math.random() < 0.5 ? "a" : "b";
  }

  bar() {
    if (this._foo === "a") {
      console.log("got 'a'");
      // this error should not occur:
      if (this._foo === "b") {
        console.log("lucky case, got 'b' too");
      }
    }
  }
}

class Span {
  get end() { return this.start + this.length }
  constructor(public start: number, public length: number) {}
}

const span = new Span(4, 2);

if (span.end == 6) {
  span.length += 1;
  // same here:
  if (span.end == 7) {
    console.log("worked");
  }
}
```

### 🙁 Actual behavior

An error occured because TypeScript thinks `this._foo`/`span.end` doesn't change until that if-check, but in these examples it does.

### 🙂 Expected behavior

There shouldn't be such checks with getters.

**Comment by MartinJohns** [comment] 2021-11-11 08:04
Another duplicate of #9998.

**Closed** 2021-11-13 18:00 UTC
Labels: Duplicate
