### ISSUE TITLE
VS 2015 occasional file save failure when editing TypeScript files

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#2566] opened 2015-03-31 20:15 UTC
Hi,

**VS**: 2015 CTP 5

Occasionally when editing a TypeScript file the save (Cntrl+S) fails to work. The asterisk next to the file name on the tab doesn't go away.

Attempting to close the offending file causes the following to pop up:

![image](https://cloud.githubusercontent.com/assets/1106823/6928101/b3a5c21e-d7e9-11e4-988a-4ee3c03a556c.png)

The VS process (today) shows about 2.1 GB of memory.

After that, other files in the same project also have the same problem. However, I am able to edit and save files in other projects.

At this point the only solution is to kill VS and start again.

I get this about 3-4 times a day.

**Comment by danquirk** [comment] 2015-03-31 20:27
Is this only in a particularly large project?

**Comment by NoelAbrahams** [comment] 2015-04-01 10:13
Hi, Dan,

I ran into the same problem today, but on quite a small project - less than 10 files. This particular project is NTVS, but I have experienced it in TypeScript-only projects as well (the common denominator are the `.ts` files and `compile-on-save`).

After the problem occurs, when I right-click on the project and build I get the following:

![image](https://cloud.githubusercontent.com/assets/1106823/6938877/e7a7eb12-d85e-11e4-9599-0bd66928ff7e.png)

The VS memory today was 1.5 GB.

There's nothing in the event log.

**Comment by danquirk** [comment] 2015-04-01 19:06
Odd, I'm assuming you're working in your usual project where this hadn't been occurring to prior to CTP5? Have you seen it in CTP6?

**Comment by mhegazy** [comment] 2015-04-02 19:31
@CyrusNajmabadi is investigating a possibly related issue.

**Comment by CyrusNajmabadi** [comment] 2015-04-02 23:36
Are you running any 3rd party addons/extensions (like resharper)?  If you are and you disable all of them, do you still encounter the issue?

**Comment by NoelAbrahams** [comment] 2015-04-03 08:56
@CyrusNajmabadi, I am only using NTVS as a plugin. No resharper or web essentials.

**Comment by NoelAbrahams** [comment] 2015-04-03 10:51
@CyrusNajmabadi,

I don't think this is an NTVS problem. I just encountered it in a standard TypeScript project.

Sometimes when this happens, the file name gets removed from the tab, as in the image below.

![image](https://cloud.githubusercontent.com/assets/1106823/6981343/897c8274-d9f7-11e4-9366-77719e539f33.png)

**Comment by NoelAbrahams** [comment] 2015-05-05 10:23
This problem has not gone away with 1.5 Beta in VS 2015 RC.

I have not been able to find a repro for this. It typically occurs when a change is made in, say, an interface shared by many types that causes breakages. When attempting to edit one of the types implementing the interface I run into this problem.

This seems to occur much more frequently when working with CommonJS (via NTVS) but it also occurs on TypeScript only projects - albeit with much less frequency.

I normally have to kill VS with the unsaved changes and restart about 8 - 10 times a day.

**Comment by mhegazy** [comment] 2015-05-05 16:57
@vladima can you take a look.

**Comment by vladima** [comment] 2015-05-05 18:26
@NoelAbrahams do you use DevMode or custom locations for 'typescriptServices.js'

**Comment by vladima** [comment] 2015-05-05 21:08
@NoelAbrahams also, when this error starts to happen, does it then appear every time? if yes - can you then attach the debugger to the VS, enable first-chance exceptions and try to catch this error? I cannot reproduce it locally and I'll appreciate any extra details that will help to shed some light on this issue

**Comment by NoelAbrahams** [comment] 2015-05-06 10:37
@vladima,

>  do you use DevMode or custom locations for 'typescriptServices.js'

No, this is the standard 1.5 beta installation.

> can you then attach the debugger to the VS, enable first-chance exceptions and try to catch this error?

I did as you suggested and enabled all exceptions:

![image](https://cloud.githubusercontent.com/assets/1106823/7491605/b8501958-f3e2-11e4-860b-9cabb3cfced8.png)


After about an hour and a half of working, I ran into the problem:

![image](https://cloud.githubusercontent.com/assets/1106823/7491655/49f64652-f3e3-11e4-8f16-67158ff5dd0b.png)

This was a plain TypeScript project - no NTVS. Unfortunately, the debugger did not break. I don't think that is surprising, though, because this seems to be a problem with a memory leak - not an exception as such.

While the debugger was attached, I ran into a number of other exceptions, all occurring on the same line, but with different stack traces. These are listed below. I was not doing anything exceptional for these to occur. Just simply working on the IDE.

What can we do about this? It's a significant hindrance.

![image](https://cloud.githubusercontent.com/assets/1106823/7491547/37644e36-f3e2-11e4-937b-01336ff8d47d.png)

![image](https://cloud.githubusercontent.com/assets/1106823/7491562/4e5cfb42-f3e2-11e4-8dc3-f6a16db5bc42.png)

![image](https://cloud.githubusercontent.com/assets/1106823/7491586/88c6dbb8-f3e2-11e4-8523-dbfc31856262.png)

**Comment by vladima** [comment] 2015-05-06 15:33
@NoelAbrahams 
> No, this is the standard 1.5 beta installation.

Ok, and just to clarify - have you used DevMode before on this machine? The registry entry might not be wiped out by the 1.5 Beta installation process. I'm curious because AFAIR exceptions on the script side should not be reported by debugger unless you are in the DevMode and on your screenshots exception is clearly in the script. BTW this exception is safe - it is just a way to abort long running operation in the script  if operation was canceled on the managed side.

Also it used to be that when you attach debugger to the process you have to pick either Managed Code or Script as a target but you cannot choose both. Maybe this side was changed in VS2015 beta but I don't have high confidence in that. If this is the case then you was debugging only javascript and all exceptions on the managed side went unnoticed. Can you try to attach only a managed debugger, ignoring `OperationCanceledException` and `TaskCanceledException` and see if you'll get anything interesting. If nothing is reported then can you try to also uncheck 'Enable Just My Code' checkbox in Options -> Debugging -> General to make sure that we are definitely not missing anything?

**Comment by vladima** [comment] 2015-05-06 18:37
@NoelAbrahams and one more question, what is the size of the project that you are working on? Is it a big project or you can see the problem even on some small repros

**Comment by jasonwilliams200OK** [comment] 2015-05-10 13:05
Might be that there are some pointers here: https://support.microsoft.com/en-us/kb/2494124. See the `Cause` section.

@NoelAbrahams, as suggested:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/4587dc3d-90e2-42d7-857d-b221d0ae0327/problem-generating-manifest-insufficient-memory-to-continue-the-execution-of-the-program?forum=clr

and 

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/ac66c0da-fb33-4b8a-b232-5030c0d7b22d/insufficient-memory-to-continue-the-execution-of-the-program-microsoft-visual-studio?forum=sqlanalysisservices

you may want to try uninstalling RC > Rebooting > Reinstalling > Rebooting and retrying. It is a tall order, but yours might just be a faulty installation case.

**Comment by NoelAbrahams** [comment] 2015-05-10 13:20
@jasonwilliams200OK,

This problem has persisted across both the CTP 5 and RC versions. I'm actually not using any .Net components so the memory leak appears to be in the VS or NTVS plugins.


@vladima,

>  just to clarify - have you used DevMode before on this machine

You were right on this. I had had a brief look at DevMode and the registry key was still left at 1. I have since deleted the registry key.

> what is the size of the project that you are working on? Is it a big project or you can see the problem even on some small repros

The VS solution  itself is quite large with over 700 .ts files. Individual projects may have as little as 5 files. This problem does also occur on small projects. But there are references to .d.ts.

> Can you try to attach only a managed debugger, ignoring OperationCanceledException and TaskCanceledException and see if you'll get anything interesting

I tried this. However, the IDE with the original code is pretty unusable. I get a large number of `EventSourceException` lines being written to the output window - perhaps one every 10 milliseconds.

![image](https://cloud.githubusercontent.com/assets/1106823/7554382/9e6406fa-f71e-11e4-8be6-6a4a162df586.png)

I did not manage to run into the actual problem, but when I unchecked "Enable Just My Code" there were a number of exceptions, some of them from NTVS:

```
System.ArgumentException occurred
Message: Exception thrown: 'System.ArgumentException' in Microsoft.NodejsTools.dll
Additional information: InvalidParameter

System.NotImplementedException occurred
Message: Exception thrown: 'System.NotImplementedException' in Microsoft.NodejsTools.dll
Additional information: The method or operation is not implemented.

System.Reflection.TargetInvocationException occurred
Message: Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
Additional information: Exception has been thrown by the target of an invocation.
```

![image](https://cloud.githubusercontent.com/assets/1106823/7554388/f9a021c0-f71e-11e4-9607-83fd2ff6f6d5.png)

![image](https://cloud.githubusercontent.com/assets/1106823/7554389/0342f3d8-f71f-11e4-8fb4-0216318cb701.png)

![image](https://cloud.githubusercontent.com/assets/1106823/7554390/12af213e-f71f-11e4-9413-e72807da53c0.png)

copying @mousetraps from NTVS.

**Comment by jasonwilliams200OK** [comment] 2015-05-10 14:48
@NoelAbrahams, I am not suggesting either that it is related to .NET. If you do some research (Google, Bing, whatever), you will find that folks have encountered this bug with SQL server type projects and SQL server management studio as well. In most of those cases, Microsoft support teams have suggested to have a "clean" reinstall and OPs replied that it fixed the issue. In case here, you may find a different (better or worse) experience which is worth pursuing for the team.
Besides, if the teams are not able to reproduce this bug, chances are it might not get fixed ever. My interest is same as yours to have it fixed properly but it require some bandwidth and time investment for reinstallation process on your part (since the code for repro steps is probably not shareable?).

**Comment by vladima** [comment] 2015-05-10 14:50
@NoelAbrahams 
>You were right on this. I had had a brief look at DevMode and the registry key was still left at 1. I have since deleted the registry key.

Great, good to know. Out of curiousity, did the situation with memory (and with CPU usage if [this issue](https://github.com/Microsoft/TypeScript/issues/3054)) was observed on the same machine?

>The VS solution itself is quite large with over 700 .ts files. Individual projects may have as little as 5 files. This problem does also occur on small projects. But there are references to .d.ts.

Can you please also tell (at least approximately) what is the size of all .ts files in solution? And does the problem appear more or less frequently on small projects (and what do you define as a small project)? I apologize for a large amount of questions but since I cannot repro the problem locally I'd like to get complete understanding of the context.

>I tried this. However, the IDE with the original code is pretty unusable. I get a large number of `EventSourceException` lines being written to the output window

Yeah, I can see that, the overall situation with throwing and handling exceptions in VS is quite annoying. Can you please break on `EventSourceException` once, copy exception details and stack trace and paste it here - maybe this is not connected to the problem but I don't recall this exception being raised so often.

I think that in addition to `TaskCanceledException` / `OperationsCanceledException` it is safe to uncheck `SocketException` / `WebSocketException` / `NotImplementedException` / `EventSourceException` (once you capture exception details)

**Comment by NoelAbrahams** [comment] 2015-05-10 16:01
@vladima,

> Out of curiousity, did the situation with memory (and with CPU usage if this issue) was observed on the same machine

Yes, it's the same set of projects. It may have been due to the DevMode being set, but I wanted to make sure before I closed that issue. I need to monitor this a bit more before I can be sure.

> what is the size of all .ts files in solution?

I'm not sure how I'm going to measure that.

> And does the problem appear more or less frequently on small projects (and what do you define as a small project)

The problem occurs most frequently on the CommonJS (NTVS) projects. These are normally small projects, most with less than ten files, but a few with some 30 odd files. I have provided more information further up on this thread.

> Can you please break on EventSourceException once, copy exception details and stack trace and paste it here

I am not able to break on `EventSourceException`. There is no entry in the list of breakable exceptions. I added a new entry for `System.Diagnostics.Tracing.EventSourceException`, but there was no break. The entry just keeps getting printed out to the output window.

I have however, managed to capture another exception which I believe is relevant:

**Exception 1**

```
Microsoft.VisualStudio.OnlineLicensing.Token.CertificateValidationSubjectNameException occurred
Message: Exception thrown: 'Microsoft.VisualStudio.OnlineLicensing.Token.CertificateValidationSubjectNameException' in Microsoft.VisualStudio.Shell.Connected.dll
Additional information: certificate chain element[0] has invalid value ("cn=app.vssps.visualstudio.com")
```

Stack
![image](https://cloud.githubusercontent.com/assets/1106823/7555008/983936e4-f735-11e4-886e-db5e92b40712.png)

**Exception 2-3**
```
System.NullReferenceException occurred
Message: Exception thrown: 'System.NullReferenceException' in Microsoft.Build.dll
Additional information: Object reference not set to an instance of an object.

System.InvalidCastException occurred
Message: Exception thrown: 'System.InvalidCastException' in EnvDTE.dll
Additional information: Specified cast is not valid.
```

Stack
![image](https://cloud.githubusercontent.com/assets/1106823/7555011/de39d7c0-f735-11e4-855c-7636fe8d063a.png)


The reason I suspect this to be relevant is that normally when the file save fails, the Visual Studio login box also pops up. The first exception appears to be related to that somehow.

**Comment by NoelAbrahams** [comment] 2015-05-10 19:33
> what is the size of all .ts files in solution

If that were to find out if we have individual files with a large amount of code, then no: the average LOC per file is less than 300.

**Comment by vladima** [comment] 2015-05-11 18:23
>LOC per file is less than 300.
got it, thanks!

Please let me know disabling of the DevMode works for you. Having it enabled (and as a consequence being able to to debug script side of language service) definitely has a significant cost.

**Comment by mhegazy** [comment] 2015-07-09 18:10
This should be fixed in the next release. thanks @NoelAbrahams soooo much for the help!

**Closed by mhegazy** 2015-07-09 18:10 UTC
Labels: Bug, Visual Studio

**Comment by NoelAbrahams** [comment] 2015-07-21 16:21
@vladima, @mhegazy,

The memory and CPU for the version released with VS 2015 RTM look very stable and normal. The performance of the intellisense engine is also markedly faster.

Good job with fixing this!
Thanks.
