### ISSUE TITLE
The narrow-able type object gets omitted from type alias when emitting declarations

### ISSUE THREAD

**Issue by alitaheri** [Microsoft/TypeScript#13489] opened 2017-01-14 09:16 UTC
**TypeScript Version:**  nightly (2.2.0-dev.20170114)

**Code**

```ts
export type A = object;
export type B = A | object;
```

Compiled with `-d`:

**Expected behavior:**

```ts
export type A = object;
export type B = A | object;
```

**Actual behavior:**

```ts
export type A = ; // Syntax error O.o
export type B = A | ; // More Syntax error X.x
```

**Comment by aluanhaddad** [comment] 2017-01-14 11:36
Reproduced on 2.2.0-dev.20170113

**Comment by mhegazy** [comment] 2017-01-16 05:19
Duplicate of https://github.com/Microsoft/TypeScript/issues/13504

**Closed by mhegazy** 2017-01-16 05:19 UTC
