### ISSUE TITLE
.filter should narrow down output type

### ISSUE THREAD

**Issue by ArashMotamedi** [Microsoft/TypeScript#20812] opened 2017-12-20 00:46 UTC
**TypeScript Version:**  2.6.2

The output of `filter` can be a further constrained/narrowed-down type. For example, you can use `filter` to find items in an array that have a certain property. TS is great at inferring these constraints within the filter predicate, but should also carry the inference forward into `filter` results. See usage of `filter` and `map` in the example below:

**Code**

```ts
interface A { text?: string }
let array: A[] = [{}, {text: "hello"}, {}, {text: "world"}];
let lengths = array.filter(e => e.text).map(e => e.text.length);
                                                 ^^^^^^
// [ts] Object is possibly 'undefined'.
// (property) A.text: string | undefined
```

**Expected behavior:**
The output type of `filter` should be `{text: string}` because TS correctly understands the filter predicate: only elements with `text` property are returned. 

**Actual behavior:**
The type output of `filter` is still `{text?: string}`.

**Comment by studds** [comment] 2017-12-20 09:30
If you use a [user defined type guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) in combination with explicit types, you can do this. I also find it useful to use [discriminated unions](https://www.typescriptlang.org/docs/handbook/advanced-types.html#discriminated-unions). I feel like it ought to be possible to cut this example down a bit further, but this is what I could put together quickly

```typescript
interface A1 { }
interface A2 { text: string }
type A = A1 | A2;
const array: A[] = [{}, { text: "hello" }, {}, { text: "world" }];
const a2s: A2[] = array
    .filter((e): e is A2 => e.hasOwnProperty('text'));
const lengths = a2s
    .map(e => e.text.length);

// no compile errors
```

**Comment by andy-ms** [comment] 2017-12-20 14:56
Duplicate of  #5101 -- we won't infer that `e => e.text` is a type predicate without an annotation `(e): e is { text: string } => e.text`.

It may be easier to define a `mapDefined` helper like so:
```ts
function mapDefined<T, U>(array: ReadonlyArray<T>, mapFn: (x: T, i: number) => U | undefined): U[] {
    const result: U[] = [];
    for (let i = 0; i < array.length; i++) {
        const mapped = mapFn(array[i], i);
        if (mapped !== undefined) {
            result.push(mapped);
        }
    }
    return result;
}

interface A { text?: string }
let array: A[] = [{}, {text: "hello"}, {}, {text: "world"}];
let lengths = mapDefined(array, e => e.text === undefined ? undefined : e.text.length);
```
then there is only a single closure and type guards will work.

**Comment by JannesMeyer** [comment] 2017-12-26 06:52
This doesn't seem to work with primitives. Am I missing something?

```ts
interface A { id?: number }
let array: A[] = [ {id: 1}, {}, {id: 2} ];
let ids: number[] = array.map(e => e.id).filter((id): id is number => id != null);
```

**Comment by JannesMeyer** [comment] 2017-12-26 07:00
Shouldn't it be possible to leave off the explicit type on the result?

```ts
interface A1 { }
interface A2 { text: string }
type A = A1 | A2;
const array: A[] = [{}, { text: "hello" }, {}, { text: "world" }];
const a2s = array
    .filter((e): e is A2 => e.hasOwnProperty('text'));
const lengths = a2s
    .map(e => e.text.length);

// The type of a2s is {}[]
```

**Comment by andy-ms** [comment] 2018-01-02 19:55
@JannesMeyer In `typescript@next` it is.

**Closed** 2018-01-17 17:36 UTC
Labels: Duplicate

**Comment by seanpoulter** [comment] 2018-06-20 21:08
Where should I add that this explicit type guard is required in the docs? We really shouldn't have to turn to GitHub to figure something like this out ...

> Duplicate of #5101 -- we won't infer that e => e.text is a type predicate without an annotation (e): e is { text: string } => e.text.

**Comment by dfee** [comment] 2019-05-17 23:02
Hello friends (who've come here before me and discovered how to do this!). Like @seanpoulter, I feel this should be documented somewhere.

For anyone coming after me, here's a practical example of how you should use something like `filter`:
```ts
const getNumbers = (v: Record<string, number | string>): number[] =>
  Object.keys(v)
    .map<number | string>(k => v[k])
    .filter<number>((i: number | string): i is number => typeof i === "number");
```

Now I'm not clear on *why* this is the case. Perhaps someone could enlighten us?

**Comment by seanpoulter** [comment] 2019-05-18 03:43
I'd say we should add a note on the [Type Inference](https://www.typescriptlang.org/docs/handbook/type-inference.html) section of the TypeScript Handbook. Let's ask the contributors of that section if they'd welcome a PR. Would you review a PR @DanielRosenwasser, @arthanzel, @RyanCavanaugh, @vomvoru, and @karptonite? Would you rather it go in [Type Inference](https://www.typescriptlang.org/docs/handbook/type-inference.html) or [Advanced Types](https://www.typescriptlang.org/docs/handbook/advanced-types.html)?

**Comment by narkowicz** [comment] 2019-05-18 04:21
@dfee No claim to enlightenment, but I think the core problem is summed up quite well in the original issue description and in #10734 - type narrowing doesn't flow through scopes.

The issue is unrelated to the implementation of `filter` which, as in your example, correctly narrows types when a type predicate is declared as the return type.

The problem is that functions never infer a type predicate as a return type. So the below `isNumber` function infers a return type of `boolean` rather than `a is number` and can't be used for type narrowing (consumers of `isNumber` correctly do not inspect the implementation, only the signature).

```ts
function isNumber(a: any) {
  return typeof a === 'number';
}
```

The situation is the same for inline arrow functions commonly used with `filter`.

What we're effectively asking for is that the type narrowing provided by an `if` statement (which can be quite complex) be flowed through as an inferred predicate return type when a function returns that same statement (which otherwise equates to a boolean). I can't imagine it's trivial to implement, but it would be _very_ handy.

In such a world, the below `isCardinalNumber` function would also infer a return type of `a is number` and support type narrowing if used with `filter`.

```ts
function isCardinalNumber(a: any) {
  return isNumber(a) && a >= 0 && a%1 === 0;
}
```

**Comment by JamesMcMahon** [comment] 2019-11-08 18:07
For those not wanting to track through multiple closed duplicate issues, this issue/discussion appears to be alive at https://github.com/microsoft/TypeScript/issues/16069.

**Comment by SmileJayden** [comment] 2020-11-20 00:16
After es2019, you can use [flatMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap).

Here is my [ts-playground](https://www.typescriptlang.org/play?target=99#code/MYewdgzgLgBAtgTwIICcUwLwwNoHIAWApgDbEi4A0MYArqVbgO4grEAmlMNYbhAZgEswhNgF0A3AChQkWIOJRCKEZnjI0AOj7EAhlACyOgA4AKEwA8AlAAKMAPhjmYAfkcwAXDlGXxQA).

```
const myArr = ['hello', null, 'world', undefined];
const filteredArr = myArr.flatMap((x) => x ? x : []);
```
Above `filteredArr` is inferred as `string[]`.

**Comment by naivefun** [comment] 2020-12-25 02:24
in latest ts document there is the solution:
https://www.typescriptlang.org/docs/handbook/advanced-types.html

![image](https://user-images.githubusercontent.com/10683378/103114874-5bdcbc00-469b-11eb-8382-7368e2c6ae66.png)

**Comment by rossmartin** [comment] 2023-05-19 19:04
Here is a generic one that I came up with after needing TS to properly narrow the type returned from `Array.filter`.

```ts
function isObjectWithKey<T, K extends keyof T>(key: K) {
  return function (obj: T): obj is Required<T> {
    return typeof obj[key] !== 'undefined';
  };
}

// usage (files is an array of objects with an optional uuid key)
files.filter(isObjectWithKey('uuid'))?.map((f) => f.uuid)

// more usage
type File = {
  uuid?: string;
};
const obj1: File = {};
console.log(isObjectWithKey<File, 'uuid'>('uuid')(obj1));
// false
const obj2: File = {
  uuid: '1',
};
console.log(isObjectWithKey<File, 'uuid'>('uuid')(obj2));
// true
```

This can be shortened to this below to be more succint.

```ts
const isObjectWithKey = <T, K extends keyof T>(key: K) => {
  return (obj: T): obj is Required<T> => typeof obj[key] !== 'undefined';
};
````

Shared on stackoverflow - https://stackoverflow.com/a/76291666/1673842

**Comment by mahmoudmoravej** [comment] 2024-07-29 17:50
> After es2019, you can use [flatMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap).

Although `flatMap` fixes the issue, but it is using a wrong tool for a specific problem: We fix typecheck error, with using an unneeded call to `flat`.
