### ISSUE TITLE
Allow access to non overlapping properties in a union type

### ISSUE THREAD

**Issue by ja-iy** [microsoft/TypeScript#54069] opened 2023-04-30 01:36 UTC
# Suggestion

## 🔍 Search Terms

Allow access to non overlapping properties in a union type
Access a property that doesn't always exist on a type,
Access a property that isn't always defined in a union containing an object,
property 'key' does not exist on type, 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* This wouldn't be a breaking change in existing TypeScript/JavaScript code
* This wouldn't change the runtime behaviour of existing JavaScript code
* This could be implemented without emitting different JS based on the types of the expressions
* This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

##  Motivation

We can access properties that potentially exist on an object without runtime checks or type casting, but only when the property is possible (exists somewhere in the type).

## ⭐ Suggestion

Allowing access to properties that potentially don't exist using . and ?. operators, If and only if the type of the item we are trying to access is a union where one of the members contain the property.
* The resulting type of the accessed property becomes the union of all possible types of the property & undefined
* Exclude primitives (eg array.map)
* ( Should this be Implemented as a utility type or a tsconfig option that has to be opted into, so we know typescript is behaving this way ? )
   
## 📃 Motivating Example

for example: 
`const getBar = ( foo: 'bar' | {bar: 'bar' } ) => foo.bar ?? foo`

Normally typescript will reject this as Property 'bar' does not exist on type '"bar" | { bar: "bar"; }'. 
With this new feature we would gain access to foo.bar with its type being 'bar' | undefined

But why should we gain access to foo.bar?
Because we know that foo.bar might exist, we might need to access it, and if it does not exist then foo.bar will return undefined

note that if: 
`const getBar = ( foo: 'bar' ) => foo.bar ?? foo`
then typescript still retains its current behaviour & prevents access to foo.bar, as it will never exist on the typeof foo and hence accessing it will never be valid/desired. (So this example is still dis allowed)

This feature improves typescript by allowing us access to a greater set of javascript code within typescript.

## 💻 Use Cases

Some use cases for this feature:
* useful for accessing non overlapping properties of a union of objects
* defining arrays (and mapping): currently typescript will add non overlapping keys as undefined in the type definition when defining arrays, this allows accessing the non overlapping properties when accessing, with this feature that would no longer be necessary
* useful for config objects with lots of non overlapping properties

Some shortcomings of current approach:
* to access non overlapping properties we currently need to narrow the type being accessed by doing runtime checks or explicit typecasting
* accessing properties of a const array when mapping: if an array is declared as const typescript will not add undefined (mentioned above in use cases) so runtime checks or explicit typecasting is required to access the the non overlapping properties.

Some current workarounds:
* using the in operator to check for existence at runtime which allows typescript to narrow the type successfully (only works if the type is a union of objects)
* adding & { key : undefined } to every type in the union missing the specified key
* using as to force the type at some point before access
    
I couldn't find any discussion on this kind of feature, if anybody knows about one , or any reasons why this feature shouldn't be implemented please let me know, ty for reading : D

**Comment by MartinJohns** [comment] 2023-04-30 01:57
Duplicate of #50495 and several others.

**Comment by fatcerberus** [comment] 2023-04-30 02:31
In particular refer to https://github.com/microsoft/TypeScript/issues/50495#issuecomment-1229469965

**Comment by ja-iy** [comment] 2023-04-30 11:11
Makes sense from your example ty
`const foo: Foo = bar;  // this proposal would only work if this errors unless exact type match (no extra properties)`

So if/when #12936 will be supported this feature might be possible?

sorry for duplicate

**Closed** 2023-04-30 11:12 UTC

**Comment by MartinJohns** [comment] 2023-04-30 11:43
Theoretically it could work with exact types, but I wouldn't expect exact types to be supported in the next 5 years.

**Comment by o-alexandrov** [comment] 2023-12-18 19:46
@MartinJohns could you please explain, why not treating missing properties in other objects within a union as:
```ts
{
  missingProperty?: never
}
```

adding `missingProperty?: never` to other objects within a union works as a workaround to silence TypeScript's error in this case

**Comment by MartinJohns** [comment] 2023-12-18 23:30
Because that would just be wrong. The properties may exist on the object as objects are not sealed.

**Comment by o-alexandrov** [comment] 2023-12-19 05:02
Giving an option in tsconfig.json, similar to `strict`, would let users to choose objects as sealed.

Would you consider adding an option, so the missing properties are considered as: `never`?
It would satisfy a lot of users, as there have been many issues on this topic

**Comment by MartinJohns** [comment] 2023-12-19 05:28
Sealed objects would go fundamentally against how TypeScript is designed and just cause issues left and right. Treating missing properties as `never` would not solve the issue.

What would solve it are "Exact Types". The issue has been linked already.

If sealed objects are currently a hard requirement for you, then TypeScript is simply the wrong tool for your problem.

**Comment by noncom** [comment] 2025-04-18 14:52
Just for anyone who stumbles upon this, there's an [article](https://oida.dev/typescript-hasownproperty/) that describes a workaround that would help in most cases. You need to be careful, though.

Citing from the article, this function gives you a type predicate that allows casting based on field presence:

```typescript
function hasOwnProperty<X extends {}, Y extends PropertyKey>
  (obj: X, prop: Y): obj is X & Record<Y, unknown> {
  return obj.hasOwnProperty(prop)
}
```

Here's a small example ([playground link](https://www.typescriptlang.org/play/?ssl=11&ssc=1&pln=10&pc=15#code/GYVwdgxgLglg9mABACwIYGcDyB3MAFAJzgAcBTAqATwB4ANRUgDylLABN1EBvAXwBpEATQbNWHRIRLkqAaVKUAfAChEiABRwARgCsAXIloDiRYvsEBKfVu2IYnegDJEAJVIQ4BNtUEDwAazA4XAVuFUQCUigQAiRrADo0LFxJMgpKNWMScyUeJSUYMBYCYFQIUkQAQW5ERn0wEABbTXIAbkQAL310KAICgHNEXIKikrLEACFq2sR6ptbESi6e-sQAHxnG5oJBvKoyRABZRABeSrWJpT3ygDkTifOKvNBIWARbdAqAfQBGNXQ4BqkfQHSyIf6A95nLjhSLRJCJHD4EzSdLg0gCABEjAx5kQDicagqBAIqEocTsRJJqIBpDijHMuNyz2g8CQdnGPz+NP011BaMhk2hESiMRQGERKRRXMBmOxuPx6iucGAYJpdJOx1OGNmWxxO2ZrzZH0+ACZpUDDnyaZCqkLYaKEclkWlzZj2nqmeAWW92abzTyrRC7Pc7SL4eKnVIXWjMZQPXkADaRRANYF3LjTb4CRaIDEY3JJqAzHnp6YAVgEnVzGOz+gAzLklO4wP8k3EE3A+moMQBJTipo6lKKoBMJyiVAD8iFQLew5GOGMQAGp3l9fg0GU2EK3aR2u73+7pB9AQCOxxMpzP0HOCAvl+8OevN82d+3O92+8XbkPT6PxxVL1nedFxXClOTAZ9tzgNs9w-TgwF0b8TzPcdxkA69gPvX1fgg7ItxbaDd3fA8UyPadkL-SdpyA28QNXP0N2yF9CLffdPwHcjh0otDqIw2isPQDkzUY-DX1gkiEKQrjzwA3ibzvUDjTNXDRJY8TP0kzjf3PHir3kujfWUhkgA)):

```typescript
function hasOwnProperty<X extends {}, Y extends PropertyKey>
  (obj: X, prop: Y): obj is X & Record<Y, unknown> {
  return obj.hasOwnProperty(prop)
}

interface A { x: number; z: string }
interface B { x: number; y: string | number }

type M = A | B
type N = B | A

function isA_1(some: M): some is A { return hasOwnProperty(some, "x") && (Array.isArray(some.x)) }
function isB_1(some: N): some is B { return hasOwnProperty(some, "x") && (typeof some.x === "number") }
function isA_2(some: M): some is A { return hasOwnProperty(some, "z") }
function isB_2(some: N): some is B { return hasOwnProperty(some, "y") }

let m: M = {x: 1, y: ""}
let n: N = {x: 5, z: "", y: 3}

console.log("Is m:M actually A? answer=" + isA_1(m))
console.log("Is m:M actually B? answer=" + isB_1(m))
console.log("Is n:N actually A? answer=" + isA_1(n))
console.log("Is n:N actually B? answer=" + isB_1(n))

console.log("Is m:M actually A? answer=" + isA_2(m))
console.log("Is m:M actually B? answer=" + isB_2(m))
console.log("Is n:N actually A? answer=" + isA_2(n))
console.log("Is n:N actually B? answer=" + isB_2(n))
```
