### ISSUE TITLE
property functions being flagged as invalid code in js files

### ISSUE THREAD

**Issue by sandy081** [Microsoft/TypeScript#9207] opened 2016-06-16 08:22 UTC
_From @jefflindholm on June 15, 2016 12:33_

- VSCode Version: 1.2.1
- OS Version:
windows 10
Steps to Reproduce:

1. create a js file
2. create a class file and add a property
get "[js] 'property declarations' can only be used in a .ts file." with the property code highlighted. 
I am attempting to use code to do react coding and using the property functions keep me from littering my code with myfunc = myfunc.bind(this); unless I actually need to rebind something. It is more an annoying visual thing to have a lot of code underlined than anything else, but it would seem to be something you should allow in js/jsx files.
```javascript
class MyClass {
  someFunction = () => {

  }
}
```

_Copied from original issue: Microsoft/vscode#7718_

**Comment by mhegazy** [comment] 2016-06-16 19:23
Duplicate of #6997. Fixed in https://github.com/Microsoft/TypeScript/pull/9189.

**Closed** 2016-06-16 19:23 UTC
