### ISSUE TITLE
[feat] experimental-network-imports

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#50124] opened 2022-08-01 08:02 UTC
# Suggestion

Suprisingly, found nobody feature request on `network-imports`, which
- has been deno builtin
- and part of nodejs experimental for a while.

```
$ node --help
  --experimental-network-imports
                              experimental https: support for the ES
                              Module loader
```

```ts
import { expect } from 'https://cdn.skypack.dev/chai'
// Cannot find module 'https://cdn.skypack.dev/chai' or its corresponding type declarations.
```

## 🔍 Search Terms

`network-imports` `.d.ts`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2022-08-01 09:06
Duplicate of #48678.

**Closed** 2022-08-06 18:00 UTC
Labels: Duplicate
