### ISSUE TITLE
Fault in `tsc --noEmit` on mixed up params in complex function

### ISSUE THREAD

**Issue by llaenowyd** [microsoft/TypeScript#49966] opened 2022-07-20 01:06 UTC
# Bug Report

### 🔎 Search Terms

fault
Object
parameter
symbol
cached
type
differs
assigned

### 🕗 Version & Regression Information

- This is a crash in tsc version 4.7.4

### ⏯ Playground Link

[Please find an example reproduction here](https://github.com/llaenowyd/tsc-fault-useRecoilCallback)

### 💻 Code

[This is correct and passes `tsc --noEmit` as expected! 🎉](
https://github.com/llaenowyd/tsc-fault-useRecoilCallback/blob/66b512d15864e47d9c9787c58eb0851c19ae2c82/src/useSpin.ts#L8-L10
)
```ts
  useRecoilCallback(({ set }) => (i: number, nextSymbol: string) => {
```

[This is incorrect but instead of printing a diagnostic tsc faults. Unfortunately without a good diagnostic.](
https://github.com/llaenowyd/tsc-fault-useRecoilCallback/pull/1/files#diff-071095b49cb3209d31d35f4f0b0283f74d2f2178e98c250b729c7fda407303c5R8
) 
```ts
  useRecoilCallback((i: number) => ({ set }, nextVal: string) => {})
```

### 🙁 Actual behavior

```txt
$ tsc --noEmit
/src/tsc-fault-useRecoilCallback\node_modules\typescript\lib\tsc.js:96888
                throw e;
                ^

Error: Debug Failure. Expected [object Object] === [object Object]. Parameter symbol already has a cached type which differs from newly assigned type
    at assignParameterType (/src/tsc-fault-useRecoilCallback\node_modules\typescript\lib\tsc.js:64862:26)
    at assignContextualParameterTypes (/src/tsc-fault-useRecoilCallback\node_modules\typescript\lib\tsc.js:64827:21)
    at contextuallyCheckFunctionExpressionOrObjectLiteralMethod (/src/tsc-fault-useRecoilCallback\node_modules\typescript\lib\tsc.js:65229:29)
    at checkFunctionExpressionOrObjectLiteralMethod (/src/tsc-fault-useRecoilCallback\node_modules\typescript\lib\tsc.js:65208:13)
    at checkExpressionWorker (/src/tsc-fault-useRecoilCallback\node_modules\typescript\lib\tsc.js:66805:28)
    at checkExpression (/src/tsc-fault-useRecoilCallback\node_modules\typescript\lib\tsc.js:66707:38)
    at checkExpressionCached (/src/tsc-fault-useRecoilCallback\node_modules\typescript\lib\tsc.js:66411:24)
    at getReturnTypeFromBody (/src/tsc-fault-useRecoilCallback\node_modules\typescript\lib\tsc.js:64931:30)
    at contextuallyCheckFunctionExpressionOrObjectLiteralMethod (/src/tsc-fault-useRecoilCallback\node_modules\typescript\lib\tsc.js:65236:42)
    at checkFunctionExpressionOrObjectLiteralMethod (/src/tsc-fault-useRecoilCallback\node_modules\typescript\lib\tsc.js:65208:13)

Node.js v18.2.0
```

### 🙂 Expected behavior

Normally `tsc` should print a diagnostic instead of failing its assertion.

I bet it's because these functions have complex types.

Here in a simple case with

```ts
export const f = (a: string, b: number) => {}
f(123, 'abc')
```

then it behaves like this

```txt
$ tsc --noEmit
/src/simpleParamsError.ts(2,3): error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.
```

**Comment by MartinJohns** [comment] 2022-07-20 05:56
Duplicate of #49383.

**Closed** 2022-07-22 18:00 UTC
Labels: Duplicate
