### ISSUE TITLE
JSON.parse should accept more types thant string

### ISSUE THREAD

**Issue by KuSh** [microsoft/TypeScript#45922] opened 2021-09-16 22:19 UTC
Hi,

TypeScript Version: 4.3.4

Code

```ts
var foo = JSON.parse(localStorage.getItem('foo'));
console.log(foo); //null
```

Expected behavior:
No error. Console logs null
Actual behavior:
TS2345: Argument of type 'string | null' is not assignable to parameter of type 'string'.

According to [ecma262 spec](https://tc39.es/ecma262/#sec-json.parse), the first step of the parse function is :

> 1. Let jsonString be ? ToString(text).

And [ToString returns meaningful values for most types](https://tc39.es/ecma262/#table-tostring-conversions)

So IIUC `JSON.parse` should accept `string | boolean | number | bigint | null`

And testing it in Firefox, Chrome and NodeJS confirms that it works:

```js
["{}", true, 42, 3.14, 2n ** 54n, null].map(JSON.parse);
```
returns

```json
[
  {},
  true,
  42,
  3.14,
  18014398509481984,
  null
]
```

Workaround is to use `JSON.parse(String(...))` which result in the exact same behaviour

regards,
Nicolas

**Comment by MartinJohns** [comment] 2021-09-16 23:07
You forgot to fill out the issue template. It asks for search terms you used to find existing issue. Duplicate of #43232.

**Comment by KuSh** [comment] 2021-09-17 07:53
Sorry about that .. the template didn't popout when I created the bug (directly from the es5.d.ts file)

And #43232 seems close without a valid explanation to me.
The linked SO question does not seem to apply here as the ecma spec clearly allows null and other values

**Comment by MartinJohns** [comment] 2021-09-17 08:29
Jcalz and me provided the reasoning for it.

**Comment by KuSh** [comment] 2021-09-17 11:34
Ok.

I don't necessarily agree with the reasoning, especially since workarounds could induce more harm than a more relaxed interface.

Imagine something like the example I provided `JSON.parse(String(localStorage.getItem('foo')))` where String accept more types than just `string | boolean | number | bigint | null` it will work but we won't get a warning if someone refactor the code to use something else than localStorage but keep String around it
IMHO it lessens the safeguards provided by TS

But I won't argue anymore. Thanks a lot for your time (and sorry for the dup)

**Closed** 2021-09-19 18:00 UTC
Labels: Duplicate

**Comment by MartinJohns** [comment] 2021-09-21 19:11
I don't understand your argumentation. You want the signature to be more spec compliant, and the spec allows any value that can be coerced to a string, so the only meaningful type would be `any`. But then you say you wouldn't get a warning for specific values..?
