### ISSUE TITLE
Regression: Seemingly swapped or incomplete type inference for Decorators in 2.4.1

### ISSUE THREAD

**Issue by benno-dreissig-schwab** [Microsoft/TypeScript#17264] opened 2017-07-18 13:37 UTC
**TypeScript Version:**  2.4.1

Since 2.4.1 TypeScript is outright hating my decorated classes due to following problem:

```ts
abstract class BaseType {
}

class ImplementingType {
	value = 1;
}

abstract class BaseClass<W extends BaseType> {
	abstract test(baseValue: W): void;
}

function Decorator(target:typeof BaseClass) {
}

@Decorator
class ImplementingClass extends BaseClass<ImplementingType> {
	test(implementValue:ImplementingType) {
		return;
	}
}
```

**Expected behavior:**
There should be no error in this. ImplementingClass is an implementation of BaseClass and ImplementingType extends BaseType.

**Actual behavior:**
Mind the swap of assigns in the error stack in "Type 'W' is not assignable to type 'ImplementingType'."
```
error TS2345: Argument of type 'typeof ImplementingClass' is not assignable to parameter of type 'typeof BaseClass'.
  Type 'ImplementingClass' is not assignable to type 'BaseClass<W>'.
    Types of property 'test' are incompatible.
      Type '(implementValue: ImplementingType) => void' is not assignable to type '(baseValue: W) => void'.
        Types of parameters 'implementValue' and 'baseValue' are incompatible.
          Type 'W' is not assignable to type 'ImplementingType'.
            Type 'BaseType' is not assignable to type 'ImplementingType'.
              Property 'value' is missing in type 'BaseType'.

```

**Comment by ikatyang** [comment] 2017-07-18 13:48
It seems duplicate of #16985, and it's caused by stricter generic checks (#16368), if you don't like this feature, you may have to enable `--noStrictGenericChecks` option.

**Comment by mhegazy** [comment] 2017-08-17 17:13
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-08-17 17:13 UTC
Labels: Duplicate
