### ISSUE TITLE
Bug intellisense when use with DocJs tag in Visual Studio

### ISSUE THREAD

**Issue by XHighIntell** [microsoft/TypeScript#50534] opened 2022-08-30 14:16 UTC
# Bug Report

### 🕗 Version & Regression Information

- This is a bug. This bug doesn't appear in TS itself or TS playground, but when using with others JS files and DocJS tags
- Visual Studio Community 2019 v16.11.16
- This bug appears in both TS v4.4.4 and v4.7.4
- I was unable to test this on others or older versions

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/PQKgsAUABDUCoAsCWBnKAjArgcygghgA6ECmAdiQCZRJlQBuqm+ANlCgC6aVID2UAdwTlBvAE4BrWrgFIOCKACkAygBFeAYygd82FADookSLCgBJPPnokoAJigAzJCxIoAXFABELJOn2V9DhRPKAAyL3x8fQArYOMIEGB44GAoHz8AoKMIWg4SMQd8DRszMjyCopIARigAbxNYSIAKeVQPAAk4AFkAGQBRFwBbcg4ASg96XiRKAG5IAF9k1MiYlEhQECgAAQ4AT1JzMvzC4prEyHp8MSgADygAXjr5uYgb-UiHx0wyDQ4+Miao3q0FgrQMtAoYk6vU+AHJYTMoCkoAAeAC0aMEwjoAhshDErjQlF4HCgTX0owANNphGlUKTeA4oMNBuh8mhGVBof0hiMoERSFcGjAwYZTOKJcj0ZihCJcVB8YSoMTSeSqVAyCTkGRcAKSEKIIsIEA)

### 💻 Code

```ts
// lib.d.ts 
interface Interface1 {
    aa(this: HTMLElement): void;
}

// aa.js
/** @type Interface1 */
var x = {};
x.aa = function(){
    this.innerHTML = ''; // <-- when we press dot (.), the list of members of HTMLElement appear
    this.                // <-- when we press dot (.), nothing appear. This only happened after setting any property.
}
```

### 🙁 Actual behavior
<img src="https://user-images.githubusercontent.com/15198165/187459365-59a42b52-c8f6-4710-9eba-76cc7e4275fb.png" width="300px"/>

### 🙂 Expected behavior
<img src="https://user-images.githubusercontent.com/15198165/187459629-d8b54b51-09af-49e1-9ab6-be05458369fb.png" width="300px"/>

**Comment by fatcerberus** [comment] 2022-08-30 16:51
Duplicate of #50338 and #50240.

**Comment by XHighIntell** [comment] 2022-08-31 03:55
> Duplicate of #50338 and #50240.

Nice, now we have the same issues on both Visual Studio and Visual Studio Code. It is good to know for dev.

**Comment by fatcerberus** [comment] 2022-08-31 04:05
It affects both because the bug is in the TypeScript language service, which is used by both VS and VS Code.

**Closed** 2022-09-05 18:00 UTC
Labels: Duplicate
