### ISSUE TITLE
Promise.all types inferred incorrectly

### ISSUE THREAD

**Issue by clurdish** [microsoft/TypeScript#36232] opened 2020-01-16 17:56 UTC
**TypeScript Version:**  3.8.0-dev.20200115

**Search Terms:** Promise.all 

**Code**

```ts
interface A {
    id: string
}

interface B {
    id: string
    fieldB: string
}

async function countEverything(): Promise<number> {
    const providerA = async (): Promise<A[]> => { return [] }
    const providerB = async (): Promise<B[]> => { return [] }

    const [resultA, resultB] = await Promise.all([
        providerA(),
        providerB(),
    ]);

    const dataA: A[] = resultA;
    const dataB: B[] = resultB;
    if (dataA && dataB) {
        return dataA.length + dataB.length;
    }
    return 0;
}
```

**Expected behavior:**
Compiles without errors.

**Actual behavior:**
Compile fails.

```
Type 'A[]' is not assignable to type 'B[]'.
  Property 'fieldB' is missing in type 'A' but required in type 'B'.(2322)
input.ts(7, 5): 'fieldB' is declared here.
```

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=2&pc=15#code/JYOwLgpgTgZghgYwgAgILIN4Chm+cAEwC5kBnMKUAcywF8stRJZEUAhTHPQk8ykGnmQxgEADYE2vCtToM4pAJ4gEwgK4qwwAPYhkCbRrABRAG7RFYABbUAFAEoSABSjaAtsFIQAPCDVuAI2gAPk4hAxByZAAHV1NCaHQAXmQFZVUHZ1cPL29UAG0AXVCk0IxkKAgwNSg9IuR6cN0o2O14gmgOFLSVZEzkF3dPHzYikrKKqpq6woaGJsiwZHzK0jUxMFQAGkm1jbZZ7oB3OGAlwZyIADo4MTFbfK4hXFb2xIctp+fXhKg2D6+hXsAG55ngIlECHAwHBUCQCoddutNqCFpDoXApMhRojVsi2KjuDA+lCYegAGTk5CkzH2MLPXCVaq1akY1BXMQQATWZAAalZMLYHK5VGshNwjTwTOmyAADKDaEA)

**Related Issues:** #16017

This appears to be the exact same issue as #16017, just reappearing in version 3.7+.

**Comment by MartinJohns** [comment] 2020-01-16 18:29
Duplicate of #35626, #34937, and several others.

**Closed** 2020-01-20 18:00 UTC
Labels: Duplicate
