### ISSUE TITLE
`export default abstract class` doesn't work

### ISSUE THREAD

**Issue by alexlur** [Microsoft/TypeScript#9513] opened 2016-07-05 09:03 UTC
**TypeScript Version:**  1.8.10

**Code**

```ts
export default abstract class Sample {
  // methods here.
}
```

**Expected behavior:**
```ts
"use strict";
var Sample = (function () {
    function Sample() {
    }
    return Sample;
}());
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Sample;
```
**Actual behavior:** 
```js
[ts] Cannot find name 'abstract'.
[ts] ';' expected.    // at the word `class`
```

**Combinations that work:**
```ts
export abstract class Sample {}

abstract class Sample {}
export default Sample;
```

**Comment by kitsonk** [comment] 2016-07-05 12:13
Two second search to find it is a duplicate of #3792

**Comment by alexlur** [comment] 2016-07-05 12:53
@kitsonk Sorry. I couldn’t find it.

**Comment by kitsonk** [comment] 2016-07-05 13:28
["export default abstract"](https://github.com/Microsoft/TypeScript/search?q=export+default+abstract&type=Issues&utf8=%E2%9C%93) returns the original issue and about 5 other duplicates of it...

**Comment by mhegazy** [comment] 2016-07-05 17:01
![image](https://cloud.githubusercontent.com/assets/8000722/16592844/757f1db8-4297-11e6-8495-75552d6bbb71.png)

**Closed by mhegazy** 2016-07-05 17:01 UTC
