### ISSUE TITLE
lodash types weird intellisense output

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#13374] opened 2017-01-10 00:34 UTC
_From @Luchillo on December 26, 2016 16:56_

- VSCode Version: 1.8.1
- OS Version: OSX Sierra

This is the output of VSCode with the `@types/lodash` package:

![image](https://cloud.githubusercontent.com/assets/9698639/21484318/855756b0-cb5e-11e6-8b78-bb8e38d91ea0.png)

I expected to see at least `map` intellisense, and most likely `flatMap` and a few others.

tsconfig file:

```ts
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "noEmitHelpers": true,
    "strictNullChecks": false,
    "baseUrl": "./src",
    "paths": {},
    "lib": [
      "dom",
      "es6"
    ],
    "types": [
      "hammerjs",
      "jasmine",
      "node",
      "selenium-webdriver",
      "source-map",
      "uglify-js",
      "webpack",
      "lodash"
    ]
  },
  "exclude": [
    "node_modules",
    "dist"
  ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": { "rewriteTsconfig": false }
}
```

Steps to Reproduce:

1. Install with `npm i -D lodash @types/lodash`.
2. Create ts file and try to import lodash map function, it will not even show `map`, nor `flatMap` nor others.

_Copied from original issue: Microsoft/vscode#17831_

**Comment by mjbvz** [comment] 2017-01-10 00:39
I confirmed this issue. Here's the TSServer communication in the first case when trying to get a suggestion for the import:

```
[Trace - 4:34:47 PM] Sending request: completions (424). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/sand/test/main.js",
    "line": 1,
    "offset": 12
}
[Trace - 4:34:47 PM] Response received: completions (424). Request took 3 ms. Success: true 
Result: [
    {
        "name": "AssignCustomizer",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "Cancelable",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "CloneDeepWithCustomizer",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "CloneWithCustomizer",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "CurriedFunction1",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "CurriedFunction2",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "CurriedFunction3",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "CurriedFunction4",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "CurriedFunction5",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "DebounceSettings",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "Dictionary",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "DictionaryIterator",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "Function0",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "Function1",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "Function2",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "Function3",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "Function4",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "FunctionBind",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "FunctionBindKey",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "InvertByIterator",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "IsEqualCustomizer",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "List",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "ListIterator",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "ListOfRecursiveArraysOrValues",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "LoDashExplicitArrayWrapper",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "LoDashExplicitNumberArrayWrapper",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "LoDashExplicitObjectWrapper",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "LoDashExplicitStringWrapper",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "LoDashExplicitWrapper",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "LoDashExplicitWrapperBase",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "LoDashImplicitArrayWrapper",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "LoDashImplicitNumberArrayWrapper",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "LoDashImplicitObjectWrapper",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "LoDashImplicitStringWrapper",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "LoDashImplicitWrapper",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "LoDashImplicitWrapperBase",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "LoDashStatic",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "LoDashWrapperBase",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "Many",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "MapCache",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "MapCacheConstructor",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "MemoIterator",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "MemoVoidArrayIterator",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "MemoVoidDictionaryIterator",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "MemoVoidIterator",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "MemoizedFunction",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "MergeWithCustomizer",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "MixinOptions",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "NumericDictionary",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "NumericDictionaryIterator",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "ObjectIterator",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "PH",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "Partial",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "PartialRight",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "RecursiveArray",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "SetWithCustomizer",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "StringIterator",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "StringRepresentable",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "TemplateExecutor",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "TemplateOptions",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "TemplateSettings",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "ThrottleSettings",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "TruncateOptions",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "isMatchCustomizer",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "isMatchWithCustomizer",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    }
]
[Trace - 4:34:47 PM] Sending request: completionEntryDetails (425). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/sand/test/main.js",
    "line": 1,
    "offset": 12,
    "entryNames": [
        "Many"
    ]
}
[Trace - 4:34:47 PM] Response received: completionEntryDetails (425). Request took 2 ms. Success: true 
Result: [
    {
        "name": "Many",
        "kindModifiers": "declare",
        "kind": "type",
        "displayParts": [
            {
                "text": "type",
                "kind": "keyword"
            },
            {
                "text": " ",
                "kind": "space"
            },
            {
                "text": "_",
                "kind": "localName"
            },
            {
                "text": ".",
                "kind": "punctuation"
            },
            {
                "text": "Many",
                "kind": "aliasName"
            },
            {
                "text": "<",
                "kind": "punctuation"
            },
            {
                "text": "T",
                "kind": "typeParameterName"
            },
            {
                "text": ">",
                "kind": "punctuation"
            },
            {
                "text": " ",
                "kind": "space"
            },
            {
                "text": "=",
                "kind": "operator"
            },
            {
                "text": " ",
                "kind": "space"
            },
            {
                "text": "T",
                "kind": "typeParameterName"
            },
            {
                "text": " ",
                "kind": "space"
            },
            {
                "text": "|",
                "kind": "punctuation"
            },
            {
                "text": " ",
                "kind": "space"
            },
            {
                "text": "T",
                "kind": "typeParameterName"
            },
            {
                "text": "[",
                "kind": "punctuation"
            },
            {
                "text": "]",
                "kind": "punctuation"
            }
        ],
        "documentation": [],
        "tags": []
    }
]
```

While for the program:

```ts
import * as _ from 'lodash'
_.ma
```

We get the expected suggestions for `map`:

```
[Trace - 4:36:36 PM] Sending request: completions (483). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/sand/test/main.js",
    "line": 3,
    "offset": 5
}
[Trace - 4:36:36 PM] Response received: completions (483). Request took 11 ms. Success: true 
Result: [
    {
        "name": "AssignCustomizer",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    ...
    {
        "name": "map",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
   ...
]
```

**Comment by andy-ms** [comment] 2017-01-12 15:35
Duplicate of #13218.

**Closed by andy-ms** 2017-01-12 15:35 UTC
Labels: Bug
