### ISSUE TITLE
Inconsistent Type Inference for data with Generic Parameter F in Async Function

### ISSUE THREAD

**Issue by seiyeah78** [microsoft/TypeScript#60389] opened 2024-11-01 14:21 UTC
### 🔎 Search Terms

Generic Parameter, async functions, return unknown

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about declared vs anonymous function inference.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.3#code/C4TwDgpgBAYhwGMAWEBOAFAhiANge0wBMAeAFQD4oBeKUqCAD2AgDtCBnKACk1QHMAXFACWLAGZoo6AJTVKmFiABQUKAH4pKqELqNmbTlwB0J3n3ZDRE1FACCsqvMVbVG2y+1QWEAG5oA3EpKCHgs7MD0DJgAtmA4EHCISNRQxFqkADRaMJH6HNxmFlAKIA6U6Kh40cLsEMQA3lCEmMCYOlAAvuRZqui5rPmJyGhYuAQkMN1K5FxaAPRzUBJJaEI8-EUlZVKV1bUNTS1ttJ1TqsvDqEIwPVBg2PhEakLoWdv1WqjwAK6oLEvwS5ce5jIjSQIdQLBULhJbfFgIFKYdggBEFDZCRrCQhCFjfaIAI0kHXenx+fygjWarUxXnxQkKRmxnU6EKhITCES+7G+OAiNEYMTiCUBSC4YnhCAylJEOKgAEZOuClNzecAjMAUCwuFxUNsOew8PEjPg+LqjNTMEY8dFpOCgA

### 💻 Code

```ts
type FetcherPayload<T> = T extends (arg: infer P) => any
  ? P
  : T extends (...args: infer A) => any
    ? A
    : never;

const exampleFetch = <
  T,
  F extends (args: any) => Promise<{ data: T }>,
  P extends FetcherPayload<F>,
>(
  // fetcher: (args: any) => Promise<{ data: T }>, // ← no error
  fetcher: F,  // ← error TS18046: 'r.data' is of type 'unknown'.
  payload?: P,
) => {
  return fetcher(payload);
};

const func = async (args: { id: number }) => {
  return { data: { num: args.id } };
};

const result = exampleFetch(func, { id: 1 });
result.then((r) => console.log(r.data.num));
```

### 🙁 Actual behavior

When defining an asynchronous function type using a generic parameter, TypeScript may incorrectly infer the return type of nested properties as unknown. For example, when the function type is defined with a generic parameter for the function itself, TypeScript fails to infer a property type within the resolved data correctly, resulting in unknown. However, if the function type is defined directly (without using a generic parameter), the correct type is inferred. This inconsistency affects the usability of the function with generic asynchronous types.

### 🙂 Expected behavior

TypeScript should consistently infer the types of return values and arguments when a generic parameter is used in the function definition, regardless of whether the function is defined with a generic parameter or directly.

Additionally, if fetcher is not defined as F, TypeScript fails to infer the argument type from payload: P. For example, when calling exampleFetch(func, { id: 1 }), the expected { id: 1 } inference for the argument does not work as intended.

**Comment by jcalz** [comment] 2024-11-01 14:43
Essentially a duplicate of #7234, TS will never infer from a constraint, so `T` has no inference site in your function as written. There may well be ways to rewrite your function to get inference to work how you want, but this isn't considered a bug in TypeScript.

**Closed** 2024-11-04 01:33 UTC
Labels: Duplicate
