### ISSUE TITLE
Compiler expects arrow functions of type `(): never` to return, but they do not

### ISSUE THREAD

**Issue by josh-berry** [microsoft/TypeScript#46892] opened 2021-11-22 05:06 UTC
# Bug Report

### 🔎 Search Terms

* arrow function does not return
* arrow function always throws
* arrow function never returns
* function returns never

### 🕗 Version & Regression Information

- This is the behavior in every version I tried
- I tried every version of TypeScript available on the playground (including Nightly) as of this writing
- I reviewed the FAQ and handbook for entries about functions which do not return, and to be sure I understood the semantics of the `never` type

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211121#code/PTAEBUAsEsGdQO4HsBOBrWAuAsAKDyKAGYCuAdgMYAu0SZoVkKSCAoisygBQCUmoZAKYA3QSlABvAmFCyGTFgMEJQ7TlwBESJAAdYGngG5poAL54TAIRJV5cYgENoAG3hUkoCkgC2Ol4Jx8XC8yWFtGZjYOVFAAXlBefiFRcViAPkkIxSEVNVRNbT0DU2MgwgB1SEF6ElhBABNEaEY7NxRoYWgHZ1BBAA8HX2dBYnJqWjJAvFJKGjpPKoo0LgcUAHN+MPayNdAAH1ByesEiaCF6vlAts92pXDlQaCIE1bWeUBRBKhIUelfSh5ZKLqIx4UxAA)

### 💻 Code

```ts
// This works:

function throwError(): never {
    throw new Error("oops");
}

// But this fails to compile:

const throwError = (): never => {throw new Error("oops")};

// When used with this trivial example function:

function check(arg: string | undefined): string {
    if (arg) return arg;
    throwError();
}
```

### 🙁 Actual behavior

An arrow function which returns `never` seems to be treated just like any other function with an irrelevant/unchecked return value. The compiler seems to expect control to resume after `throwError()`, and it complains that:

```
Function lacks ending return statement and return type does not include 'undefined'.
```

### 🙂 Expected behavior

Just like with plain old `function`s that return `never`, I would expect the compiler to know that an arrow function which returns `never` does not return at all.

**Comment by MartinJohns** [comment] 2021-11-22 05:52
Duplicate of #37998.

**Comment by fatcerberus** [comment] 2021-11-22 06:26
To be fair, that wording is somewhat misleading/vague w.r.t. this case.  Here, the function itself *does* have an explicit return type annotation (i.e. the return type is not inferred) - it's just that the type of the *variable* the function is assigned to is inferred.

**Closed** 2021-11-24 18:00 UTC
Labels: Duplicate
