### ISSUE TITLE
DecoratorsOf<TClass, TFieldName> - Expose decorators to the type system

### ISSUE THREAD

**Issue by olegbl** [microsoft/TypeScript#58836] opened 2024-06-12 14:53 UTC
### 🔍 Search Terms

decorators, decorated, tc39

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Implement a new generic type that exposes the existence of decorators to the type system:
```
DecoratorsOf<TClass>  // returns decorators applied to class
DecoratorsOf<TClass, TFieldName> // returns decorators applied to field in class
```

The type would return a union of the *types* of all decorators applied to the field/class/etc... which allows deriving new types based on the presence or absence of decorators.

Note: This proposal becomes unnecessary if decorators gain the ability to *modify* the type of the fields/classes/etc... that they decorate.

### 📃 Motivating Example

You can see a full example in the [TypeScript Playground](https://www.typescriptlang.org/play/?#code/PTAEBUE8AcFMGUDGAnAltALqAJge1gM6gB2uWAFgIYBusJuAtqsZQDagYzMDmANKAVygA7nQBmlANZ1UWAEaRQlbNh5LiAKBCgArsR0FY2Jcm46GsYlmGzyS3cVQBHHXQKQGc3O05wOQ2EpEO2xYRFxkSgwI0AsMclxsLTB41CI2VlxhIgN-B2dXVkVVAkpPVDMoulDwyOjkImpUSg5yWFRkDhhYDQ1w4gIsADlYDGEI6WwAETCIqIiASSmALnyXNw8vdgBeUHhN7wAKAHIRsYmjY4BKAG4NMT1EDFRcYlAz8eRJgB5wAGFWJQCAR+OAAGpsVwAPkOAH0MJRTKNVnpQmJmEZ+P0MLAAB4YVYAoEEABiqFgrGmszqET+rxx+N+ROBoIhrGh-FQ2AA-KtfLBcGJ3qNPpMZrV5sglldQABvAC+vX6g1AJNwuHFc3qSxRjnWAgOOz2hpOatw1zuD2ITxebzNTMBLIgbOhcIRSIJDjRGOwWPpeM9zNJ5MpmppyDpVgDDuJrMhsChnJ5fO6gtV6rDkulcsVfVeKoAQojM9qVmtXAbPN5QLt9lXWCci8gLfdHs9XqAmzGneD4zD4YjuMivbB0cRMaBsQHCY7gxSqRL6pGGRhuyDnX2k7yunA002S4spjKFUrZ6AALKQINyjSgO+gAACHwuSXvJBFL5dsFW+k8sE6uwAAx3Le94PmaoF3g+TaQaAmSIGwX4-uYcj-jWoDARoubaNsuF4fhBGEURxEkQRyStGk75GOkoDIIE7CoAw0CsLAFhWFEtrLORpE8bxfH4Ro-KgAeDQAPJiGuoJkvOQxlAmNawf8Z4BpY2BEJe17crBb7gNJlKyRYoAqcQamgMc47nF8RhfscoBaW+Dn3vyabPlZr6OaAqy6SG2AGXQxmmcc8GIfGtn2R5b7OUKZqgAAPjuApCjBEWrAA2gAurBaXpXcOH8flBUCYJ3TCdSVTYAA6rYkkQHpvlyaCIlQgpOkiUZ+KqUQIkEOJNXeTJcnNdyHDIBWqwSKwhggUJAAKqCIJIdUEFV8QiX1TXobKsGpdp979fpcmgMwoDSJAaZKcSSgELtd77fVhkBUQgxoMQ3A3Q5w0lkYK3kH1dV+Y1ZX1M1j0ja470RcNd1+RDHk-rAtDILDd7w4jsHpV5QapdDcmZfK00lQASqxZCwL8zW7HNC1LT9a3gPwUXCpZkxQiBVo2h2OKDMTDCkxps6HAwV6zqsPOk98-PElCx6wULQYAHQWaK1nxuhmFvtoD4YAQAC0eJwE8evIMgESrMFrBfgICQ6JS9DyP5uLQLghjuXecuzvL5uW0BdzYWACSI3khjVP+qC0MY-LXUJkvArCSufqruzdb1MfruZH5uTZrPFX4qewl7ielYuEQ9RJqf8EFuAIRboXZ9HwvErCrmTOhVOLT5y22Gt5cJS5Gcs3c9dBrCMWU-N7fzp3q1AxEEsN06jNmnXJV502rfjzTXcz8gc9BgzqZJYi2dAA).

As a brief inline example, consider an application with networking capabilities on its data structures. It uses decorators to annotate which fields are networked (and provide the networking implementation for them).

A client that only has remote access to some data structures would only be able to access these remote fields, and not any local ones, but there is currently no way to generate this TypeScript type.
```
class MyClass {
    @Networked
    networkedValue: number = 0;

    localValue: number = 0;
}

// Note: Using the proposed DecoratorsOf<> type
type DecoratedWith<TClass, TFieldName, TDecorator> =
    TDecorator extends DecoratorsOf<TClass, TFieldName> ? true : false;

type PickFieldsWithDecorator<TClass, TDecorator> = {
    [
        TFieldName in keyof TClass as
        TFieldName extends string
            ? DecoratedWith<TClass, TFieldName, TDecorator> extends true
                ? TFieldName
                : never
            : never
    ]: TClass[TFieldName]
};

type Remote<T> = PickFieldsWithDecorator<T, typeof Networked>;

function testRemoteMyClass(myClass: Remote<MyClass>) {
    myClass.networkedValue = 0;
    // @ts-expect-error: localValue should not be exposed
    myClass.localValue = 0;
}
```

### 💻 Use Cases

1. This functionality would allow deriving types based on decorators.
2. There are no existing solutions for doing this with *only* decorators.
3. Existing workarounds all involve directly or indirectly storing the presence of decorators in other data structures. For example, storing a map of all decorators applied to a class' members as a POJO.

**Comment by fatcerberus** [comment] 2024-06-12 17:10
As you noted, decorators don’t affect the type of a class at all, so how would this even work?  The information just isn’t there.  Decorators modifying types is, AFAICT, a *prerequisite* for this feature.

Also:
> This isn't a request to add a new utility type

It is.

**Comment by olegbl** [comment] 2024-06-12 17:30
Good point, I should clarify.

This feature requires decorators to be exposed to the typing system (which is why this is a feature request to TypeScript, instead of just some library), but it does not require the decorators API to allow an end-user to modify the typing system in some way. The latter is what I referred to by:

> Note: This proposal becomes unnecessary if decorators gain the ability to modify the type of the fields/classes/etc... that they decorate.

-----

> This isn't a request to add a new utility type

> It is.

I suppose it could have a different format to make it look more like a language feature than a type - I don't have any particular requirements on that subject. Since this isn't a type possible *to derive*, it needs *something*.

**Comment by IllusionMH** [comment] 2024-06-12 20:19
Looks similar to or duplicate of #48413

**Comment by olegbl** [comment] 2024-06-12 20:33
Yup! Very similar. Only a couple of minor differences:
1. This is a bit "lower level" and can be used to implement the `PickByDecorator<>` API from #48413 (shown in the example as `PickFieldsWithDecorator<>`).
2. This would also allow fetching decorators on a class, rather than only for class members.

I should also mention #4881 which I think is the  equivalent of:

> Note: This proposal becomes unnecessary if decorators gain the ability to modify the type of the fields/classes/etc... that they decorate.

**Comment by RyanCavanaugh** [comment] 2024-06-14 21:33
This doesn't seem to generalize very well. Decorators can have arguments and those arguments will absolutely be needed to make the kinds of decisions being discussed here. #4881 or its alternatives seem like the scalable approach.

**Closed** 2024-06-17 01:31 UTC
Labels: Duplicate
