### ISSUE TITLE
JS/TS auto-import is not as good as Webstorm's

### ISSUE THREAD

**Issue by darkbasic** [microsoft/TypeScript#36816] opened 2020-02-13 11:48 UTC
*TS Template added by @mjbvz*

**TypeScript Version**: 3.7.5

**Search Terms**
- auto import
- auto imports

---

- VSCode Version: 1.42.0
- OS Version: Arch Linux amd64

Steps to Reproduce:

1. `npm install graphql-tools`
2. Try to auto-import `makeExecutableSchema`

It will say `No code actions available`, but if you manually import it then it works:
```
import { makeExecutableSchema } from 'graphql-tools';
```

The same function gets automatically imported in Webstorm.

Some auto-imports do work in vscode, like `join`:
```
import { join } from 'path';
```

but not all of them.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-02-15 00:41
Here's what I see in VS Code insiders in a new project:

<img width="1280" alt="Screen Shot 2020-02-14 at 4 39 58 PM" src="https://user-images.githubusercontent.com/12821956/74578295-a902e400-4f48-11ea-9906-9fef7b73046c.png">

Do auto import suggestions work for you? Is it just the lightbulb that doesn't? The lightbulb for auto imports are only enabled if you [enable semantic checking](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_type-checking-javascript) in your JavaScript

**Comment by darkbasic** [comment] 2020-02-17 10:24
@mjbvz in this particular example you're right: `makeExecutableSchema` gets the import suggestion when you type it, but it was taking so much time to display it that I didn't notice.

*BUT* other imports still don't get the suggestion, like for example `MikroORM`.
If you kindly help vscode adding the following to the beginning of your file
```
import {} from 'mikro-orm';
```
then it will manage to suggest `MikroORM` when you type it, otherwise it will display no suggestions at all.

**Comment by andrewbranch** [comment] 2020-02-26 18:34
Duplicate of #36042

**Closed** 2020-02-29 18:00 UTC
Labels: Duplicate
