### ISSUE TITLE
 Enhanced type system

### ISSUE THREAD

**Issue by x1shi** [microsoft/TypeScript#38627] opened 2020-05-18 02:54 UTC
## Search Terms

enhanced type system

## Suggestion

Support to create type with custom detection function in TS

## Use Cases

I hope to strengthen the type system of TS,

To meet more complex requirements (such as creating a string type with limited length), and simplify code operation.

(there is a drawback and that can be made up:)
1. The high uncertainty brought by the custom detection function (especially the unknown performance overhead required to execute the function during type checking).  
  (this can be achieved by limiting the custom detection function to: type will be further checked when typescript is compiled to JavaScript, and only type structure existing in the current version will be checked when writing code; to maintain the experience when writing code)

2. It may take a lot of work to realize it.

And I have a gradual proposal, which can completely avoid the above shortcomings, but also castrate the function I proposed:  
Instead of adding a custom detection function to a compiler or type check, you can simply add an optional "validation function" property to the type, and then you can reference its validation function while referencing the type

## Examples

```
//old
type T_Second = number

//new
supertype T_Second = (p:number)=>{
    return (p > 0 && p < 60)
}

/*
let s = somefn() //s = 2
T_Second testfn(s) // true
*/
```
Supertype receives a function whose parameter is unique and must indicate the type (the function parameter is the basic type), and the return value of this function can only be Boolean (used to further verify the type)

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-05-18 08:42
Essentially a duplicate of #202.

**Comment by RyanCavanaugh** [comment] 2020-05-20 19:37
We've seen a number of proposals like this; all of them run afoul of at least one core constraint:

 * The typechecker should not *execute* user code
 * No type-directed emit
 * No new runtime syntax

This proposal is somewhat underspecific but it's definitely violating at least one of those constraints.

**Comment by x1shi** [comment] 2020-05-30 20:39
@RyanCavanaugh I suddenly have an accurate implementation method, as follows:
```
supertype MyNumber (p:number):boolean{
    return (p > 0 && p < 60)
}
//use example
function use_example(num:MyNumber){
    //typeof num = Error | number
}
```
convert to current ts:
```typescript
type MyNumber = number
function __supertype_MyNumber (p:MyNumber):boolean{
    return (p > 0 && p < 60)
}
//use example
function use_example(__supertype_num:MyNumber){
    let num: MyNumber | Error
        = __supertype_MyNumber (num) ?
            __supertype_num
            : new Error("supertype MyNumber returned false")
}
```

**Comment by RyanCavanaugh** [comment] 2020-06-02 16:24
That is type-directed emit.

**Closed by RyanCavanaugh** 2020-06-02 16:24 UTC
Labels: Suggestion, Too Complex
