### ISSUE TITLE
paths alias maps

### ISSUE THREAD

**Issue by eng-dibo** [microsoft/TypeScript#41782] opened 2020-12-02 19:56 UTC
using the property paths in tsconfig.json file allows you to alias or shorten paths. that is great, but we need a method to rewrite the imported path in the output file, without the need to use any external bundling tool.

example:

tscofig.json
```
{ 
  paths: {"exp/*": ["example/*"] },
  rewrite: { "example/*": "real/path/*",  "another/path/*": "ok/*"}
}
```

anyfile.ts
```
import x from "exp/something"
import y from "another/path/something"
```

the suggested output should be something like:
```

//rewrite the path "example/*" into "real/path/*"
const x = require("real/path/something.js");

//rewrite the path "another/path/*" into "ok/*"
const y = require("ok/something")
```

**Comment by DanielRosenwasser** [comment] 2020-12-02 20:47
Duplicate of #26722.

**Closed** 2020-12-05 18:00 UTC
Labels: Duplicate
