### ISSUE TITLE
Type of thisArg is not captured properly

### ISSUE THREAD

**Issue by RasmusAndreassen** [microsoft/TypeScript#51020] opened 2022-10-01 07:59 UTC
# lib Update Request

## Configuration Check

My compilation *target* is `ES5` and my *lib* is `[ES7, DOM, es2019, es2020.promise, es2020.bigint, es2020.string]`.

## Incorrect Definition

Various objects, mostly `ArrayLike` objects, have methods that accept a callback function and a `thisArg`.

For example:
```ts
interface Array {

    ...

    /**
     * Executes a provided function once per each key/value pair in the Map, in insertion order.
     */
    forEach(callbackfn: (value: V, key: K, map: Map<K, V>) => void, thisArg?: any): void;

    ...

}
```

However this completely ignores the fact that the type of `thisArg` can be used to determine the type of `this` in the callback function

## Sample Code

```ts
function testNumbers (array:number[]) {
	const evenTester = {
		test: (a:number):boolean => (a & 1) == 0
	};

	array.forEach(
		/** callbackfn */
		function(number) {
			console.log(this.test(number)? `${number} is even` : `${number} is odd`)
		},
		/** thisArg */
		evenTester
	)
}
```

The above code should properly compile, since the type of `evenTester` is known at the time of calling `array.forEach`. Instead, the programmer has to specify the type of `this` manually.

```ts
function testNumbers (array:number[]) {
	const evenTester = {
		test: (a:number):boolean => (a & 1) == 0
	};

	array.forEach(
		/** callbackfn */
		function(this:{test: (a:number)=>boolean},number) {
			console.log(this.test(number)? `${number} is even` : `${number} is odd`)
		},
		/** thisArg */
		evenTester
	)
}
```

Of course the above could be simplified by adding an interface for evenTester, but a one-off interface is an inelegant solution that will end up cluttering the namespace.

## Documentation Link
An example of how `thisArg` is treated in the standard:
[Ecmascript 2015 Array.forEach documentation](https://262.ecma-international.org/6.0/#sec-array.prototype.foreach)

**Comment by MartinJohns** [comment] 2022-10-01 08:53
Duplicate of #32512. This was once added, but then removed again in #16223 for performance reasons.

**Closed** 2022-10-07 18:00 UTC
Labels: Duplicate
