### ISSUE TITLE
Type Narrowing incorrect in Promises

### ISSUE THREAD

**Issue by Gurran** [microsoft/TypeScript#57320] opened 2024-02-07 13:39 UTC
### 🔎 Search Terms

Ts Promise type narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [Type Guards](https://github.com/Microsoft/TypeScript/wiki/FAQ#type-guards)

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABBAFgUwgawGIwDZoDCCUaYUAFAFCKLD5oBciA3siWVMwM5QBOMMAHNEAH0S8BwgNoBdRAF8ANDWQBDPHgBGarMwrcQAW2ZhjWtHwCUiALwA+RADc4MACYqrzF+9aqYwIgUAIJ8fGoAngB0MNyh4REU9ARREBzkVjYsqrQEUBLGdogADADcOXRwfEF5iIJuaAAeRWV1YA3NADx0DKnpUFEEwlAopW0dANQTWRW0aWC8iGgERpxFyWh95JzS9U2y5bMFRogTtksrnINkQiPltLQKFRAa2rqYBsZW94oX3Gh+B7qTQ6LBJXrzUjka7DFDfVRPJ5UCB4NTcbiIACyEUIqPRgIkUDUsAgiDREUgiAA6uEAA60yzggjMNiQzg8fiCETiSRcuRiRDgBr0MBoNyKGZAgJBDZbKH5WyKwXtNAisWSoGIPhoKAgPhIAAKfDgRlim21ACsMJQAKJhKoUADkuAIdQxaCMtKgEUdmR+jyoFW1uv1iFFAHdEEaTWaKBRtdw4HgnGglFq0FboDYHASpYEmZs2eQ7EqharBOrc5rLdaKBHEHbjXwnS6AbElp7vb74ZrFIHe6gMDgGMRtuQC2n42hDHgoNnHNle7RpQW5WtFecy2q3Bql+nM5R642Hc6GG6O16fX6jgGb+nE8m0FOZ3P-Q8FD335-EYH5oshHAcBuK2RSsv0zDSI6wCAY6aaOjofCwYg8FqAAXo68gKOUf75ABQGtgATKB7BjlwyHQXAjqKNhCCLDowFnucYGkcwW4VuKWG-rRSabHgcBCBQ2K4mi3BRDSaj0oyeEMQQ15-jxgz8YJOJ4qJ4mSc20mEXJ3EpHxAlCapYl0gyzb0a215AA

### 💻 Code

```ts
function checkFileContent(
  file: { content: string | string[] },
  callback: (sum: number) => void,
): void {
  if (Array.isArray(file.content)) {
    let sum = 0;
    for (let index = 0; index < file.content.length; index++) {
      const element = file.content[index];

      sum += element.length;
    }
    callback(sum);
  } else {
    callback(file.content.length);
  }
}

class MyClass {
  static async Wrapper(file: { content: string | string[] | undefined }) {
     // should type narrow here
    if (file.content === undefined) {
      return Promise.reject(Error('File is empty'));
    }

    return new Promise((resolve, reject) => {
      // should type narrow here
      if (file.content === undefined) {
        reject(new Error('File is empty'));
      }

      checkFileContent(file, (result) => {
        if (file.content === undefined) {
          reject(new Error('File is empty'));
        }

        resolve(result);
      });
    });
  }
}

const goodFile = { content: ['foo', 'bar', 'baz'] };
const goodFile2 = { content: 'foo' };
const badFile = { content: undefined };

console.log(MyClass.Wrapper(goodFile));
console.log(MyClass.Wrapper(goodFile2));
console.log(MyClass.Wrapper(badFile));

```

### 🙁 Actual behavior

foo.ts:29:24 - error TS2345: Argument of type '{ content: string | string[] | undefined; }' is not assignable to parameter of type '{ content: string | string[]; }'.
  Types of property 'content' are incompatible.
    Type 'string | string[] | undefined' is not assignable to type 'string | string[]'.
      Type 'undefined' is not assignable to type 'string | string[]'.

29       checkFileContent(file, (result) => {
                          ~~~~


Found 1 error in foo.ts:29

### 🙂 Expected behavior

Clean compilation. The if statement should narrow the type. But TS still complains. 

### Additional information about the issue

This was compiled locally with the `--strict` flag
`npx tsc --strict foo.ts`

**Comment by MartinJohns** [comment] 2024-02-07 13:58
Another duplicate of #9998.

**Comment by MartinJohns** [comment] 2024-02-10 11:28
> Is the solution to just force ignore errors for that line?

All options are mentioned in the linked issue. 

Mainly:
- Store the narrowed value in a local `const` variable (best approach).
- Use a type assertion (`as`).
- Narrow within the closure.
- Ignore the error.

**Closed** 2024-02-13 01:25 UTC
Labels: Duplicate
