### ISSUE TITLE
Template Literal Types as key types get lost when implementing Interface

### ISSUE THREAD

**Issue by RS-Sautter** [microsoft/TypeScript#49889] opened 2022-07-13 05:57 UTC
# Bug Report

### 🔎 Search Terms

template literal key remapping interface inheritance

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about template literal types.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/LAKALgngDgpgBAeQHYGUwCcCWSDmcC8cABgPZIAkA3gM4bY4C+RA3KKJLHAKIBuMSYALIBDKFHoE4lUHDgBtANYwIALkSo6uALpraWXKAZsQAYzK04AW1Fre-IaPG5J0kLLIBhADaYTCtQDkJj5+AbIA9OFwJAqGxthgMOgAZsIm8AAK6CQ8mAAmMNR2AiJiEq6yMHwlNtzVDmUGIEYgoMHC1NRwghAeJJZQcJgDXjCW9l1ZOfmFxQ1OeBVwVfalLjKycMG+-nBBIQphcJFwYAAWmF3UZyQArl55cKmYXgA0cABGt2BweSSFSACYAAhBsWgwgA)

### 💻 Code

```ts
type OnString = `on${string}`;

type EventMapping = {
  [key: OnString]: string
}

const map: EventMapping = {
  onClick: 'click'  // ok
}

interface ProvidesEventMapping {
  eventMap: EventMapping
}

class MyComp implements ProvidesEventMapping {
  eventMap = {
    click: 'click'  // this should fail, but doesn't!
  }
}
```

### 🙁 Actual behavior

no TS error when defining key `click`.

### 🙂 Expected behavior

Error:
```
Type '{ click: string; }' is not assignable to type 'EventMapping'.
Object literal may only specify known properties, and 'click' does not exist in type 'EventMapping'.
```

**Comment by MartinJohns** [comment] 2022-07-13 06:41
Duplicate of #10570.

**Comment by MartinJohns** [comment] 2022-07-13 06:58
Duplicate of #10570.

The type of your `eventMap` property is **not** taken from the implementing interface. It's inferred, and then checked whether it's compatible with the interface, and the type you have is compatible.

When you add an explicit type annotation you will get the excess-properties check: `eventMap: EventMapping = {...}`

**Comment by RS-Sautter** [comment] 2022-07-13 07:02
@MartinJohns thanks for the explanation. What would be a way in TS to achieve what I would like to do here then? I would not want to explicitly redeclare the type of `eventMap` but I would want to enforce it to be EventMapping.

**Closed** 2022-07-17 20:00 UTC
Labels: Working as Intended
