### ISSUE TITLE
Function with union typed argument allows for unsafe parameters

### ISSUE THREAD

**Issue by samijaber** [Microsoft/TypeScript#26270] opened 2018-08-07 18:29 UTC
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**
function union types args params unsafe

**Code**

```ts
type Props = { a: string } | { b: string };
const f = (props: Props) => 'a' in props ? props.a : props.b;

f({ a: 'foo', b: 'bar' });
f({ a: 'foo', b: 123 });
```

**Expected behavior:**
Both calls in the example should error.

**Actual behavior:**
Neither calls error.

This feels like it definitely would've been caught by somebody, but I had trouble finding an existing issue about it. 🙂

**Comment by andy-ms** [comment] 2018-08-07 18:32
Duplicate of #20863

**Closed** 2018-12-15 18:00 UTC
Labels: Duplicate
