### ISSUE TITLE
Rename refactoring the constructor initialized property does not rename the property usage in the constructor body

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#5279] opened 2015-10-16 02:16 UTC
# Sample 

```ts
class Foo {
	something;
	constructor(public bar /*rename bar*/) {
		this.something = bar;
	}
}
```

Rename `bar` to `foo` and you **expect**: 

```ts
class Foo {
	something;
	constructor(public foo /*rename bar*/) {
		this.something = foo;
	}
}
```
But you get: 

```ts
class Foo {
	something;
	constructor(public foo /*rename bar*/) {
		this.something = bar; // Error here
	}
}
```

Error reproduce-able on playground. Fortunately we get an error on usages ;) so nothing bad happens *silently* :rose:

**Comment by seanfreiburg** [comment] 2015-10-16 03:26
I can reproduce when you use shorthand for accessibility (like public, private, protected). It does not reproduce without the accessibility modifier.

**Comment by basarat** [comment] 2015-10-16 03:53
@seanfreiburg True. That's because its not a property if an access modifier isn't used

**Comment by DanielRosenwasser** [comment] 2015-10-16 07:20
Duplicate of #4686. Thanks for filing @basarat.

**Closed by DanielRosenwasser** 2015-10-16 07:20 UTC
