### ISSUE TITLE
Type guard does not handle object properties

### ISSUE THREAD

**Issue by Strate** [Microsoft/TypeScript#7655] opened 2016-03-23 13:33 UTC
**TypeScript Version:** 

actual version on http://www.typescriptlang.org/Playground

**Code**

```ts
// A self-contained demonstration of the problem follows...
interface Props {
	options: {
		name: string | boolean
	}
}

let v: Props

if (typeof v.options.name === "string") {
	v.options.name.indexOf("123")
}
```

**Expected behavior:**
No error

**Actual behavior:** 
Error: Property "indexOf" does not exist on type "string | boolean"

**Comment by yortus** [comment] 2016-03-23 14:38
Yet another duplicate of #3812. This issue is getting really popular. See also [this comment](https://github.com/Microsoft/TypeScript/issues/7603#issuecomment-199081847).

**Closed** 2016-03-23 16:23 UTC
Labels: Duplicate
