### ISSUE TITLE
Wrong type when function signature changes

### ISSUE THREAD

**Issue by NilsIrl** [microsoft/TypeScript#55720] opened 2023-09-12 11:27 UTC
### 🔎 Search Terms

* function signature
* wrong type
* changed
* re-assigned
* re-declared
* type inference

### 🕗 Version & Regression Information

- This is the behavior in every version (`3.3.3333` and `5.2.2`) I tried, and I reviewed the FAQ for entries about bugs that aren't bugs. 

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/DYUwLgBAzg9gtiAYgVwHYGMIF4IAoCGAXBAPIBGAViOmAJTYB8E+A3AFDoypST7bTwkadLgDeAX1rtYCFBn656WJgFZ2nbpDL8ZQjIpZA

### 💻 Code

```ts
let someFunc = (a: Object) => a;
const a = someFunc({});
someFunc = () => 5;
const b = someFunc();
```

### 🙁 Actual behavior

It doesn't compile and there is an error on the second call to `someFunc` saying that an argument is not supplied.

### 🙂 Expected behavior

Because `someFunc` was redefined it doesn't actually expect an argument and the code is correct.

### Additional information about the issue

When using the `function` keyword, the inferred type is correct (although it doesn't compile either but this time because there is a duplicate function implementation):

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAZzgWwKYDFwQBQCGAXIgPIBGAVhtAJSIDeiAThlCM0gQNyIC+AKAgJkURAUQBeFOmy48DPrW4DQkWAhmYckPPSat2nRn16DhYUYnJStc3cqA

**Comment by MartinJohns** [comment] 2023-09-12 11:55
Possibly a duplicate of #27706, although there's no narrowing happening in this case.

Point 2 and 3 of this comment sound relevant: https://github.com/microsoft/TypeScript/issues/36579#issuecomment-617311386

> Variables initialized with some expression always assume the widened form of the initializer's type
> Assignment will only create a narrowing to a more-specific type if the declared type of the assigned variable is a union

**Closed** 2023-09-16 01:23 UTC
Labels: Not a Defect

**Comment by NilsIrl** [comment] 2023-09-18 11:21
Even with a union type it doesn't work: https://www.typescriptlang.org/play?ts=5.2.2#code/DYUwLgBAzg9gtiAYgVwHYGMBcEAUBDbAeQCMArEdMASggF4A+CE8yiAH1xxoabIurq4CvFgJ54A3ACh0MVFEh5BsBCgw4A3gF8q0lUjTpBXOowCs02fMjFl8A+t1A
