### ISSUE TITLE
Mapped types cannot be reassigned to union type

### ISSUE THREAD

**Issue by gutentag2012** [microsoft/TypeScript#55616] opened 2023-09-03 11:36 UTC
### 🔎 Search Terms

mapped types, union, union types, extract, narrow

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about **mapped type**

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20230903#code/JYOwLgpgTgZghgYwgAgPICMBWBGZBvAKGWQGsIBPALmQHJsaBuI5EOAWwmoGcwpQBzJgF8CoSLEQoMmAEz5mZKrRmNm7APYBXcNRCa26aMIJhyABylYICMF2QBeNFlwAfJ7KYnzlzNbABZODMAFW8HeWIAbQBpClCLZFB3Py5ImkUaAF1MgH5qAFEAD15EMAAeaRSAGnxSCmpY8niUIQA+YU8EdRAeZHUrG0CzakrBoObwwmJsainiOqU6GirmYlYOahp1iGXmIRWhJhhtG2Bu5DgAE0vRsGD1IYqsZAhiiBBLu1uuVoAKfswIywAEoIn0BgEgpEAQA6RSZcIA4RAA

### 💻 Code

```ts
interface Obj1 {
  key: '1';
  name: string;
}
interface Obj2 {
  key: '2';
  amount: number;
}
type Objects = Obj1 | Obj2;

type ObjectMapType = {
  [KeyType in Objects['key']]?: Extract<Objects, { key: KeyType }>;
};

const objectMap: ObjectMapType = {
  1: {
    key: '1',
    name: 'name',
  },
};
function addObjectToMap<Obj extends Objects>(obj: Obj) {
  objectMap[obj.key] = obj;
}
```

### 🙁 Actual behavior

The object map does not accept a new entry unless it is specifically typed as `Obj1` or `Obj2`, therefore more broadly typed `Objects` are not accepted.

### 🙂 Expected behavior

Since the `ObjectMapType` uses a mapped type for `Objects`, all of its variations are included, so everything that is typed as `Objects` should be accepted.

**Comment by andrewbranch** [comment] 2023-09-05 23:09
Duplicate of https://github.com/microsoft/TypeScript/issues/31445 (the repro there looks a little different, but the explanation works perfectly, and many of the other issues linked to that one look more similar to this)

**Closed** 2023-09-08 01:24 UTC
Labels: Duplicate
