### ISSUE TITLE
Conditional on property not propagated

### ISSUE THREAD

**Issue by Sainan** [microsoft/TypeScript#59125] opened 2024-07-03 06:13 UTC
### 🔎 Search Terms

property undefined propagation

### 🕗 Version & Regression Information

Not a regression as far as I can tell.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240702#code/JYOwLgpgTgZghgYwgAgJICUIHc5QCbIDeAUMmcmAJ4AOEAXMgM5hSgDmA3KedVAPYAjOAOAAbYFQD8DEAFcAtgOhdyyKLgmVpTFuy4BfYsVCRYiFBhBtMjWaLBFuZKrQbNWVlT35CR4qjIKSlAGRgh8IMxq2Lh4AAp8fKIAKnw2dmAJScgAvMgAFFAx+IwMGMV4ANoAugCUZehW6fY1uQB8jqoA9F1oeBBwoqKUADQUABbAjMhYfHYEs1AA1nROyD1FYLJQINE4JQB0MGKm+QAe7chnB7yCwmKayACEOXmyIP3HIBB4tV5kPWQACFZGAxhAAG4QXagCYod78IY-ZAIOCMCBjCTIUDhKBFBBgYbIaD8KClNbhSIOaiJUQNJoQWwtaq5ZA1f7IGB8KAFSlRIr7Ah8GB7WKMWqdVTkYAiwoVG4+e7+SjPV7Id6fUA-CUkKV65A0pI3WSMcZywV-NaqQzWtabba7Q2iAxcIA

### 💻 Code

```ts
interface IReward {
    type: string;
    probability?: number;
    rarity?: string;
}

interface IRngResult {
    type: string;
    probability: number;
}

const rewardPoolToResultPool = (rewards: IReward[]): IRngResult[] => {
    // Ideally, this would work:
    //return rewards.filter(x => x.probability !== undefined);
    // But, even in the unrolled case, it incorrectly errors:
    const pool: IRngResult[] = [];
    for (const reward of rewards) {
        if (reward.probability !== undefined) {
            pool.push(reward);
        }
    }
    return pool;
};
```

### 🙁 Actual behavior

It complains that the `probability` property may be undefined, even tho it was explicitly checked for that.

### 🙂 Expected behavior

It accepts the `push` as valid.

**Comment by yaKsirhC** [comment] 2024-07-03 06:48
You can convert the type on your own `pool.push(reward as IRngResult);`

**Comment by Sainan** [comment] 2024-07-03 06:50
I know that casting is an option, but it's generally more desirable to _prove_ than _promise_ something to a compiler.

**Comment by MartinJohns** [comment] 2024-07-03 07:15
Duplicate of #42384.

**Comment by Sainan** [comment] 2024-07-03 08:09
I don't think these are quite the same issue, since in that case it's about inferring which variant of a union type is active in the given branch.

**Comment by MartinJohns** [comment] 2024-07-03 08:50
It's about narrowing a property propagating to the parent type. You expect by checking the property `probability` that your `IRewad` type suddenly is compatible with `IRngResult`, but that's not how narrowing works. Checking the property does not change the parent type.

**Comment by Sainan** [comment] 2024-07-03 08:56
Inheritance is involved nowhere here. Please don't speak if you have nothing of value to add.

**Comment by MartinJohns** [comment] 2024-07-03 09:03
I did not mention inheritance anywhere. Please don't say I have nothing of value to add when you don't understand the problem at hand. 🙃

Checking a property like `probability` can be used to narrow the type of the object (what I referred to as parent) when it's a union type. It does not change the type of the parent from `{ probability?: number }` to `{ probability: number }`, that's not supported.

[Quoting @jack-williams:](https://github.com/microsoft/TypeScript/issues/31755#issuecomment-498669080)

> Type guards do not propagate type narrowings to parent objects. The narrowing is only applied upon access of the narrowed property which is why the destructing function works, but the reference function does not. Narrowing the parent would involve synthesizing new types which would be expensive. More detail in this [comment](https://github.com/microsoft/TypeScript/issues/30506#issuecomment-474802840).

**Comment by RyanCavanaugh** [comment] 2024-07-09 19:45
The duplicate link is correct.

> Please don't speak if you have nothing of value to add

Not an acceptable way to interact with someone here. [Please refer to the code of conduct](https://microsoft.github.io/codeofconduct/):

> Disagreements, both social and technical, are useful learning opportunities. Seek to understand the other viewpoints and resolve differences constructively.

**Closed by RyanCavanaugh** 2024-07-09 19:45 UTC
Labels: Duplicate

**Comment by Sainan** [comment] 2024-07-09 20:08
I still fail to see how that issue is remotely related, but okay.

Also, I think "Please don't speak if you have nothing of value to add." is good advice sometimes, especially to eager noobies, which this person appeared to me as.

**Comment by MartinJohns** [comment] 2024-07-09 23:57
Yep, it's my first day using TypeScript, I'm such a noobie.
