### ISSUE TITLE
Type narrowing generics/unknown doesn't seem to work with typeof and null check

### ISSUE THREAD

**Issue by 43081j** [microsoft/TypeScript#43997] opened 2021-05-07 17:52 UTC
# Bug Report

### 🔎 Search Terms

typeof object, null checks, narrowing object, narrow generics

### 🕗 Version & Regression Information

All

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&noUnusedLocals=true&noUnusedParameters=true&ts=4.3.0-dev.20210507#code/GYVwdgxgLglg9mABKSAeAKgPgBRwEYBWAXIugJQl5xwA2ApgIZIDeAUIojMIroYgGT8eUAJ4AHOnG74CiALwLEAchl1oSsgKEyAdAAsGAZwDyAdzAAFAE5wJV0diUAPEQC8Nmthw5W6UEFZIUFYgdADc7IgAvpG+-oHIDDSG4awxrAAmajQMvogQCIZQiFB0RQBquTAMePQk4ADWYHDmEaxcwmVQlVbVtXSIAISKYCA0NFrC4pLcpRVVNfTyiiqEalAak3PdC-36RmaWNnYOzm4eiGzpHdjYohJSJV09fUsKcsqq6pqCT-O9iwGww+o3GW2eu3o+xM5mstjo9hEjhc7jInjSQA)

### 💻 Code

```ts
function func<T>(obj: T): boolean {
  if (obj && (typeof obj === 'object') && obj.hasOwnProperty('xyz')) {
    return true;
  }
  return false;
}

declare const testVariable: unknown;

if (testVariable !== null && (typeof testVariable === 'object') && testVariable.hasOwnProperty('xyz')) {
}

if ((typeof testVariable === 'object') && testVariable !== null && testVariable.hasOwnProperty('xyz')) {
}
```

### 🙁 Actual behavior

The generic function doesn't infer that `obj` must be an `object` of some sort.

The first if doesn't infer that `testVariable` can't be null.

### 🙂 Expected behavior

The generic function should infer that `T` is an `object` because we did a null check and checked `typeof`.

Both ifs should infer that `testVariable` can't be null.

### Notes

Is this just me missing some 'known behaviour' typescript has? the two conditions seem to depend on ordering, maybe thats just a known thing i was unaware of (i.e. by design)?

**Comment by MartinJohns** [comment] 2021-05-07 17:57
Duplicate of #28131.

**Comment by 43081j** [comment] 2021-05-07 17:58
The second part of this is. There are two issues i would say, the generic function can be re-ordered to have the same order and will still error.

**Comment by MartinJohns** [comment] 2021-05-07 18:01
T extends Object

**Comment by 43081j** [comment] 2021-05-07 18:04
`T` doesn't extend `object`...

```ts
function func<T>(obj: T): boolean {
  if ((typeof obj === 'object') && obj !== null && obj.hasOwnProperty('xyz')) {
    return true;
  }
  return false;
}

func('foo'); // false
func(123); // false
func({xyz: 123}); // true
// etc etc
```

**Comment by 43081j** [comment] 2021-05-07 18:19
out of interest, why isn't that behaviour the same without generics?

`unknown` could also be `{ hasOwnProperty: () => "example" }` could it not?

```ts
const foo: unknown = {hasOwnProperty: () => "blah"};

if (typeof foo === 'object' && foo !== null && foo.hasOwnProperty('blah')) {
  // WORKS
}
```

so why is it any different just because we have a `T` rather than `unknown`? which is just as lacking in type

**Comment by MartinJohns** [comment] 2021-05-07 18:40
I don't know about the specifics, you'd need to wait for the TypeScript team or someone else more knowledgable.

But your guess sounds like a good one to me. It's similar to this example:

    function func<T extends Object>(value: T) {
      if (isTest(value)) { value; }
    }

    type Test = { test: string }
    function isTest(val: unknown): val is Test { return true }

`value` is not narrowed to `Test`, it's narrowed to `T & Test`. The generic type argument is kept.

**Comment by RyanCavanaugh** [comment] 2021-05-11 21:24
There are some weird corner cases here I don't recall that lead to this. It's certainly not desirable.

**Closed** 2022-05-27 21:02 UTC
Labels: Bug, Fix Available
