### ISSUE TITLE
Including "Microsoft.TypeScript.MSBuild" in a project breaks Typescript compile on save

### ISSUE THREAD

**Issue by mperdeck** [Microsoft/TypeScript#27567] opened 2018-10-05 05:50 UTC
**TypeScript Version:**  3.2.0-dev.201xxxxx
Tested, bug still present.

**Search Terms:**
Microsoft.TypeScript.MSBuild

**Descriptions and Steps to reproduce**

Including the latest version of the Nuget package "Microsoft.TypeScript.MSBuild" in a project breaks Typescript compile on save. However, it is required to have your Typescript files generated during a dotnet publish.

Reproduced in Visual Studio Professional 2017, Version 15.8.6.

1) Create new "ASP.NET Core Web Application" project in Visual Studio 2017.
2) Choose "Web Application (Model-View-Controller). Do not configure for HTTPS.
3) In the wwwroot directory, create a new .tsx file - click wwwroot directory | add | new item | Web | Typescript JSX file.
4) The properties of the new file show "Package Action" is "TypeScriptCompile".
5) Enter some simple TypeScript in the new file, for example "var x: number = 5;". On save, the file is automatically compiled.
-----
6) Perform a "dotnet publish" on the command line in the root directory of the project. The .tsx does not get compiled as part of the publish.
-----
7) Add the line "<PackageReference Include="Microsoft.TypeScript.MSBuild" Version="3.*" />" to an ItemGroup in the .csproj of the project.
8) The properties of the .tsx file added earlier no longer show a "Package Action".
9) Edit the .tsx file - it is no longer compiled on save. It is still compiled though when you build the project.
-----
10) Perform a "dotnet publish" on the command line in the root directory of the project. The .tsx now does get compiled as part of the publish.

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
Including the Microsoft.TypeScript.MSBuild package should not break compile on save.

**Actual behavior:**
Including the Microsoft.TypeScript.MSBuild package breaks compile on save.

**Playground Link:** 

**Related Issues:**

**Comment by minestarks** [comment] 2018-12-14 21:59
Closing this as my understanding is this is working as intended.

**Closed by minestarks** 2018-12-14 21:59 UTC
Labels: Bug, Visual Studio
