### ISSUE TITLE
Intersection order matters when inferring generics.

### ISSUE THREAD

**Issue by RebeccaStevens** [microsoft/TypeScript#51092] opened 2022-10-07 13:32 UTC
# Bug Report

### 🔎 Search Terms

intersection order
inferring generics

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about inferring generics.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4#code/C4TwDgpgBAYg9nAPAQQDRQEID4oF4oAUYAXFAN5QBmCpyUAvgJR44XVykYMDcAUKJEwBDAE4p02PIRLkoAI1G0GzXK3mLMPXv3DR4cDKPGYc+fcckAyYWLQm+AegdQBehIdsTTNizmvm7bG4ASGCnKABJSigAA30PGKgASwBnKABjAAshADsAcwgAExc4F0zU9GBM6GAIFOAoETqAVwAbYDSmgDcIERSIADptVygANSFW5ohEABVvCi6JqdIZrV5CiHTW0WhKZpz04CS4HKhmlKT8gK8iAEZSccnp5Cx0MAAmUmuTRgel6aC6022yaVH2h2Op3OlzyHl8dz+TxQrygH04RkCWF+Y3+iEBQK2OwyJ3qUEWT0RU0QACJkNSsHwNoTQekSQ12AoRF93EZadT0NSMPS+LxWTlSbV6rcpNCrggCOSpugOaJGNwoOFUpTpvsANY5OAAdxyOCgZqgAFpkml9hsLk1Cug7UkHdbtTShVhRWyXHVgO8ZRd8h4Ff9lQhOWqNc4tTikYL6eak2arakoM6HbwgA)

### 💻 Code

```ts
type Foo<A, B> = (p: { foo: A }) => { foo: B };
type Bar<A, B> = (p: { bar: A }) => { bar: B };

type FooBar<A, B> = Foo<A, B> & Bar<A, B>;
// type FooBar<A, B> = Bar<A, B> & Foo<A, B>;		// If `FooBar` is changed to this, the test results reverse.

type Value<T> = { value: T };

declare function usingFoo<A, B>(p1: Value<A>, p2: Foo<A, B>): Value<B>;
declare function usingBar<A, B>(p1: Value<A>, p2: Bar<A, B>): Value<B>;

declare const value: Value<"A">;
declare const foobar: FooBar<"A", "B">;

const test1 = usingFoo(value, foobar); // is: Value<unknown>     - is undesired, desired is: Value<"B">
const test2 = usingBar(value, foobar); // is: Value<"B">         - is desired
```

### 🙁 Actual behavior

TypeScript can only infer the return type properly depending on the order of the elements in the `FooBar` intersection.

### 🙂 Expected behavior

The order of the elements shouldn't matter, TypeScript should be able to infer the type of both `test1` and `test2` correctly.

**Comment by fatcerberus** [comment] 2022-10-07 13:37
Duplicate of #26591 by way of #50975/#50708.

**Closed** 2022-10-09 18:00 UTC
Labels: Duplicate
