### ISSUE TITLE
Format code doesn't do the right thing with TSX/JSX

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#5925] opened 2015-12-04 10:55 UTC
_From @prencher on December 3, 2015 20:0_

When formatting the following snippet:

```
ReactDOM.render(
    <Router history={createHistory() }>
        <Route path='/' component={App}>
            <IndexRoute component={SplashView} />
            <Route path='home' component={HomeView} />
            <Route path='chat' component={ChatView} />
            <Route path='/chat/:contact' component={ChatView} />
        </Route>
    </Router>,
    document.getElementById('app')
);
```

The closing tags are not properly unindented, and outputs the following:

```
ReactDOM.render(
    <Router history={createHistory() }>
        <Route path='/' component={App}>
            <IndexRoute component={SplashView} />
            <Route path='home' component={HomeView} />
            <Route path='chat' component={ChatView} />
            <Route path='/chat/:contact' component={ChatView} />
            </Route>
        </Router>,
    document.getElementById('app')
);
```

_Copied from original issue: Microsoft/vscode#985_

**Comment by SaschaNaz** [comment] 2015-12-04 19:03
#3838 is related and #4398/#4757 to fix this.

**Comment by mhegazy** [comment] 2015-12-07 03:45
in dead a duplicate of #3838

**Closed by mhegazy** 2015-12-07 03:45 UTC
