### ISSUE TITLE
Type is still narrowed down after value is changed in a function

### ISSUE THREAD

**Issue by ficristo** [microsoft/TypeScript#52013] opened 2022-12-24 09:18 UTC
# Bug Report

### 🕗 Version & Regression Information

TypeScript 4.9.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyyARnFAFzIDOYUoA5gNwEC+BBMAriAmMOiGT0IYDOgAUAShwEiCATWQxMlMcgC8MwkRJlKAImXp9s5G21QRnKIKPN85jt179BCABZwQwgEJlxRqqY0njaRgB0pFAayPoeXsIAJvr2jvhcPHwCulABKmjBWkTAMMh56JFkGpqGmPohpnKe3hB+uUaS9jrIJWURUdWxUfVFOuZE5ixAA)

### 💻 Code

```ts
interface Foo {
  bar: string;
}

function getFoo() {
  const foo: Foo = {
    bar: "foo"
  }
  return foo;
}

function changeBar(foo: Foo) {
  foo.bar = "changed";
}

function bar(foo: Foo) {
  if (foo.bar == "foo") {
    changeBar(foo);
    if (foo.bar == "bar") {
    }
  }
}
```

### 🙁 Actual behavior

In the last if statement the type is still narrowed down

### 🙂 Expected behavior

Given the value is changed inside a function before the second if, shouldn't the type be again the one of the interface?

**Comment by MartinJohns** [comment] 2022-12-24 09:39
Duplicate of #9998.

**Closed** 2022-12-24 13:06 UTC
