### ISSUE TITLE
feat(tsconfig.json): Allow extends: to be array

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/TypeScript#48437] opened 2022-03-26 10:42 UTC
# Suggestion
Allow tsconfig.json property extends: to be array. with merge from right to left Behavior.

## 🔍 Search Terms

tsconfig.json, extends, extend multiple configs, compose tsconfig, composite, monorepo, large scale project, code reuse. 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
Allow tsconfig.json property extends: to be array. with merge from right to left Behavior.

## 📃 Motivating Example
it allows me to reduce all kind of how should i call them entryPoints with diffrent extend chains into a more clean reuseable concept
at present i create large folder structures only for my tsconfig files that link each other with diffrent defaults for diffrent module situations that i handle programaticaly but i found out that i could reduce all that into simple arrays and all would benefit from that.

the current situation:

tsconfig.node12.extended-compat.json
```
{ extends: './tsconfig.node12.no-compat.json' }
```

now imagin 900 + files for that with diffrent sets of compiler options only to unify and link single sets of tsconfig defaults for diffrent situations. you can expect that we replicate the complete matrix of possible tsconfig settings + 1 file at last per project (composit) that uses many up to 5 files that extend each other. and this sets of each 5 files exist in N configuration sets with diffrent mixed options.

i can reduce all that with a single collection of indipendent settings per set and then write

tsconfig.json
```
{ // Project tsconfig that only references the used config sets.
  extends: ["tsconfig.node12.no-compat.json", "tsconfig.node12.extended-compat.json"] 
} 
```

## 💻 Use Cases
I want to use it to make consumption of typescript projects more easy as also implement it in the rollup loader to test if i can get types with diffrent settings it would simply reduce the amount of dump entryPoint files needed so it would enable users with big repos to write more solid configs.

**Comment by MartinJohns** [comment] 2022-03-26 12:06
Duplicate of #29118. Used search terms: `extends array in:title`

**Comment by frank-dspeed** [comment] 2022-03-26 12:21
@MartinJohns good spotted! but i keep that open till @weswigham did reconsider and answered on #29118. i commented there now thanks for spotting that.

**Comment by frank-dspeed** [comment] 2022-03-27 09:33
@MartinJohns ok it looks like you would not agree with the process do you got a other way that you can teach me to bump issues up that got now more related then before? New issues are always better visible then the old once because the old once are cluttered most time. Also they could be on filter lists and so on. You should not fear this additional issue it will algin nice in any graph and also will produce good stats for any team member that handels it! Also i would even implement it my self so this issue can directly link the PR if i should do that. 

i hope that makes some sense to you i only wanted to explain my reasoning a bit.

**Comment by RyanCavanaugh** [comment] 2022-03-28 22:00
> New issues are always better visible then the old once because the old once are cluttered most time. Also they could be on filter lists and so on

The time we spend triaging new (duplicate) issues is time we spend not implementing/planning/evaluating popular feature requests like the one this is a duplicate of.

**Closed by RyanCavanaugh** 2022-03-28 22:00 UTC
Labels: Duplicate

**Comment by frank-dspeed** [comment] 2022-03-29 04:41
@RyanCavanaugh maybe you should consider to put some labels in a "good first issue" queue so that Contributors can catch up and implement that as they know it will get merged.
