### ISSUE TITLE
Maintain string litteral types when used as index signature type 

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#17784] opened 2017-08-14 18:16 UTC
**TypeScript Version:**  2.4.0

**Code**

```ts
function makeObj(foo: 'FOO') {
    return { [foo]: 1 };
}

makeObj('FOO') // return type: `{ [x: string]: number}`
```

**Expected behavior:**
Index signatures should have narrower types. Return type should be `{ [x: 'FOO']: number}`

**Actual behavior:**
return type is: `{ [x: string]: number}`

**Use case**

When making forms in React components I often use a method that returns an `onChange` method to be used on input `onChange` properties:

```tsx

class Component<S> {
    state: S;
    setState(partialState: Partial<S>) { }
    onFiledChanged = (filedName: keyof S) => (value) => {
        this.setState({ [filedName]: value });
    }
    render() {
        return <form>
                <input onChange={ this.onFiledChanged('foo') } />
                <input onChange={ this.onFiledChanged('bar') } />
            </form>
    }
}
```

TypeScript fails to understand `filedName` is type `'foo' | 'bar'`

**Comment by mhegazy** [comment] 2017-08-22 22:13
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/16687

**Comment by mhegazy** [comment] 2017-09-06 19:01
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-06 19:01 UTC
Labels: Duplicate
