### ISSUE TITLE
TypeScript paths config doesn't work with leading slashes.

### ISSUE THREAD

**Issue by trusktr** [Microsoft/TypeScript#13730] opened 2017-01-27 21:16 UTC
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

2.1.5

**Code**

> app.ts
> ```ts
> import Foo from '/common/Foo'
> console.log(new Foo)
> ```

> tsconfig.json
> ```json
> {
>     "compilerOptions": {
>         "paths": {
>             "/common/*":  ["../../common/*"]
>         }
>     }
> }
> ```

> Filesystem:
> ```
> website/
>     common/
>         Foo.js
>     somewhere/
>         project/
>             tsconfig.js
>             app.js
> ```

**Expected behavior:**

`tsc` should be able to recognize that when it sees a dependency like `/common/Foo` it should look for `website/common/Foo.js` in the filesystem.

**Actual behavior:**

It can't.

** More details **

I can get the following to successfully resolve files, by simply removing the leading slashes:

> app.ts
> ```ts
> import Foo from 'common/Foo'
> console.log(new Foo)
> ```

> tsconfig.json
> ```json
> {
>     "compilerOptions": {
>         "paths": {
>             "common/*":  ["../../common/*"]
>         }
>     }
> }
> ```

> Filesystem:
> ```
> website/
>     common/
>         Foo.js
>     somewhere/
>         project/
>             tsconfig.js
>             app.js
> ```

In this case, however, the output module contains something like

> output.js
> ```js
> define(['common/Foo'], function(Foo) { /*...*/ })
> ```

But this is problematic, because if `baseUrl` in RequireJS config is set,

```js
require.config({baseUrl: '/some/place'})
```

then RequireJS will look for the module at `example.com/some/place/common/Foo.js` which doesn't exist. I need it to look for the dependency at `example.com/common/Foo.js`, f.e. TypeScript would output the following including the leading slash:

> output.js
> ```js
> define(['/common/Foo'], function(Foo) { /*...*/ })
> ```

It would be great if TypeScript could support this case, then the output can still have an absolute path and work as expected.

Unfortunately, RequireJS doesn't support map configs like the following:

```js
require.config({
    baseUrl: '/some/place',
    map: {
        common: '../../common'
    }
})
```

I think solving this in TypeScript is the best options because then it can be taken advantage of in other environments besides RequireJS.

**Comment by trusktr** [comment] 2017-01-30 10:14
Side note, I discovered that I was using RequireJS' `map` option wrong, so it is indeed possible to solve the problem in RequireJS:

```js
require.config({
    baseUrl: '/some/place',
    map: {
        '*': {
            common: '../../common'
        }
    }
})
```

**Comment by hexsprite** [comment] 2017-10-17 22:40
I'm also having this problem when attempting to migrate my Meteor application to use TypeScript.

I have code like:
```
import { logger } from '/imports/logging'
```

Where Meteor maps `/imports/logging` to `<srcdir>/imports/logging.js`

Meteor doesn't use the RequireJS runtime so I don't have the ability to workaround like this.

My ideal would be to able to re-configure the root to my liking in `tsconfig.json`, ala: "absoluteRootPath": "./"

**Comment by mhegazy** [comment] 2017-10-19 19:23
Leading slash refers to the root directory, so this is an absolute path. path mapping does not work on absolute or relative paths.

**Comment by hexsprite** [comment] 2017-10-19 19:57
@mhegazy that's not compatible with Meteor JS which is a VERY popular Javascript application framework. (currently 38,469 stars on their GitHub Repo) https://github.com/meteor/meteor

all that would be required to solve this is a way to override the absolute path behavior for frameworks that desire it. The default could remain but just a flag as I described in my previous comment would work great.

**Comment by hexsprite** [comment] 2017-10-19 19:58
@mhegazy here's some further info on how Meteor structures applications. https://guide.meteor.com/structure.html

**Comment by mhegazy** [comment] 2017-10-19 20:16
it is not just a flag. it has implications on module names in output and generated declarations, which can then be consumed by third party apps. 

The is really the same behavior as node today. `/` means the root.

**Comment by hexsprite** [comment] 2017-10-19 20:53
This seems to go against the design goals of TypeScript because it introduces an opinion about import paths should be interpreted which is clearly not the same across all Javascript frameworks and platforms.

Bare node interprets it this way, sure, but many frameworks including the popular Meteor framework and also users of babel support mapping the leading slash to mean the project root not filesystem root. 

Let's face it, importing a file from the filesystem root is about as useful as a caps lock key and we know many people remap that key as well.

And not that I think you should support everything that Flow does, but they also support mapping the leading slash to something else: https://www.npmjs.com/package/babel-plugin-root-import#dont-let-flow-be-confused

Here's some other examples of platforms that use the leading slash to mean something else:
https://www.npmjs.com/package/babel-root-slash-import

If you can't tell I REALLY want to use TypeScript on this project but this is a show-stopper. Thanks for considering this.

**Comment by mhegazy** [comment] 2017-10-19 20:59
> This seems to go against the design goals of TypeScript because it introduces an opinion about import paths should be interpreted which is clearly not the same across all Javascript frameworks and platforms.

This is about what a path means. we have mirrored the node module resolution in our module resolution strategy, and that is how `@types\node\index.d.t.s`  works for instance. not sure why we should pick and chose what parts of the node module names is good and what is bad.

> Here's some other examples of platforms that use the leading slash to mean something else:
https://www.npmjs.com/package/babel-root-slash-import

Here is you are expecting the compiler to rewrite your module name in the otuput. this is something the compiler does not do... it only needs to know where the file is, module names do not change.
Please see similar discussion in #18951 and #16640

**Comment by hexsprite** [comment] 2017-10-19 21:25
Thanks for the extra details.

Actually, I just want the compiler to pass it through unchanged as Meteor in this case will properly interpret the paths in the resulting JS. It implements its own module loader.

I might have hijacked this thread a bit but ideally I just want TypeScript to find the files in the right location so that it can typecheck everything but I'm fine if it just passes the paths through unchanged and have the framework handle it at in its existing way at runtime.

So perhaps I should open a different issue for my case as it's somewhat different than the OP's issue (though related).

**Comment by mhegazy** [comment] 2017-10-19 23:20
sure.

**Comment by mgrivera** [comment] 2017-11-03 13:37
Hi @hexsprite, 
have you opened that issue already. I am interested in this theme because, like you, I use meteor and VS code and typescript, and have been experiencing this problem myself. Bye ...

**Comment by trusktr** [comment] 2017-11-03 16:14
@mhegazy

> not sure why we should pick and chose what parts of the node module names is good and what is bad.

Hello Mohamed, you don't have to pick, you can let the end user pick by giving the user a configurable option. Then everyone will be happy doing it their own way.

**Comment by ribrdb** [comment] 2018-01-08 18:59
There should at least be a way to make this work for javascript.
I'm trying to get vscode to understand my .js files that are written for the browser. Browsers can import from absolute paths, but the path is obviously different in the url than it is on my disk.

**Comment by Bettelstab** [comment] 2018-02-06 16:58
I have the same issue as @ribrdb. I am working at a project with other devs and the idea is to use typescript to analyze javascript with jsdoc annotations as the project should stay vanilla js, with using es6 modules in the browser. Removing the leading slash just doesn't work for that.

**Comment by krailler** [comment] 2018-02-26 10:20
I have same issue :/

**Comment by dtruel** [comment] 2018-03-17 17:17
Having the same issue with meteor and typescript... Just need to be able to map the "/" to the root of my project.  Right now I have to use `const Utilities = require("/imports/Utilities").default;` and I don't get any intellisense.  It seems to me like allowing a person to map "/" to any path they like is the easiest option. But maybe there is a better one out there.  Regardless, there are a lot of people who want to use Meteor & typescript, and I think supporting Meteor would help the typescript project gain even more popularity.

**Comment by EECOLOR** [comment] 2018-04-18 22:11
> The is really the same behavior as node today. / means the root.

While you are of course technically correct we could ask 'What does root mean?'. In web applications this means the web root. There are exactly 0 use cases where I want to include anything from the root of my system, my build server or my production server. One could even argue that it's unsafe to allow that.

In any case, to me it makes much more sense that `/` refers to the root of the application (for example `./src/`). I however understand that for some other people (like the meteor crew) `/` should mean the directory that contains `imports/`.

I would recommend you to either allow for extensions to influence the resolving process ([an example for webpack](https://github.com/kaliberjs/build/blob/master/library/webpack-resolver-plugins/absolute-path-resolver-plugin.js) and [an example for eslint](https://github.com/kaliberjs/build/blob/master/library/eslint-resolver-plugins/absolute-path-resolver-plugin.js)) or allow the `paths` setting to contain absolute paths:

```json
{ "paths": {  "/*": "./src/*" } }
```

The default behavior can remain the same and from a naive perspective this change does not seem to involve much as testing for an absolute path is rather easy: `path.startsWith('/')`.

**Comment by rconnamacher** [comment] 2018-04-20 21:06
FYI, this issue prevents VSCode from working with native web browser module loaders. Browsers don't support named imports, only relative paths starting with `.` or absolute paths relative to the web server's root starting with `/`. In a web browser not using a `file:` URL, `import "/foo.js"` doesn't attempt to access the root of the filesystem.

**Comment by Guema** [comment] 2018-06-11 12:20
> While you are of course technically correct we could ask 'What does root mean?'. In web applications this means the web root. There are exactly 0 use cases where I want to include anything from the root of my system, my build server or my production server. One could even argue that it's unsafe to allow that.

Best point so far IMO. even for nodejs code, server code, there is no real sence to use root directory.
perhaps, it can be more understandable if you code an Electron.js desktop app, but it is quite a special case...

The problem is, that the actual "NO WAY TO HACK" is pretty annoying, to me, at least, as it prevent plenty of framework using this syntax to be intellisence-compatible, and im not able to hack it... Im currently using meteor, and it is quite laborious, especially when coding large apps with great amount of data model. Intellisence is really usefull to get instantly in the code, get desciptions on the go, and correct eventual spelling problem.

I suggest please to at least add a a js/tsconfig flag, allowing to compute initial "/" as app path instead of system root for intellisence, as it is not possible at all to hack it afterward, as glob does not interpret "/" as any other character.

**Comment by EECOLOR** [comment] 2018-06-16 21:35
I have not heard any convincing arguments to not put this in.

I am willing to dive in and create a pull request but I would need some confirmation from the maintainers before I start working on it. TypeScript is a new codebase for me and I never typed anything in TypeScript. So it will take some effort to get to know the conventions, setup the test environment, etc. The investment in time would be too large to just add it and later discover that the change was rejected.

I had a peek at the code (at least [one place](https://github.com/Microsoft/TypeScript/blob/v2.9.2/src/services/pathCompletions.ts#L168) that the configuration was used) and it looks very readable. There is quite some indirection and here some `console.log` or breakpoints would be needed to find out how it is used.

Anyway, do the maintainers want to add this feature? And if so, would accepting the following form be ok?

```
{ "paths": {  "/*": "./src/*" } }
```

**Comment by benjamn** [comment] 2018-06-22 00:18
@EECOLOR You have my support.

**Comment by EECOLOR** [comment] 2018-06-22 19:46
According to the contribution guidelines we need a label on this issue:

> Features (things that add new or improved functionality to TypeScript) may be accepted, but will need to first be approved (marked as "Milestone == Community" by a TypeScript coordinator with the message "Approved") in the suggestion issue.

**Comment by Megabyteceer** [comment] 2018-07-07 06:48
ES6 modules specification requires all **absolute** paths to start with '/'. Its will be good if tsserver will start to resolve such imports from webRoot path.

**Comment by Megabyteceer** [comment] 2018-07-08 13:19
Browsers throw errors when meet import path started not with '/' for absolute  or '.' for relative pathes.
Usually in web pathes started not from slash treated as relative. But for imports specification is clear and relative pathes should start from dot.

**Comment by kitsonk** [comment] 2018-07-09 05:22
> Browsers throw errors when meet import path started not with '/' for absolute or '.' for relative pathes.
> Usually in web pathes started not from slash treated as relative.

There is a big difference between convention and specification.  Traditionally, both with AMD, CommonJS and SystemJS, a MID (module ID) that does not start with a `.` or `..` indicates a package name, of which the module loader is configured to resolve.  All of them make some _assumptions_ about how to resolve this module.

The ES6 Module specification specifically does not assert _anything_ about how modules would be loaded and how MIDs should be formed and resolved.  TC39 specifically avoided this.  They indicated that the WHATWG would address it, but the [WHATWG worked for a while](https://github.com/whatwg/loader), under trying to get SystemJS and the WHATWG specification to be aligned, but then they have all but halted their work about a month ago, because the browser vendors were pressing forward and no one can agree on how it should work and service workers, and dynamic `import()` came along.

So, in my opinion it is inaccurate to say any specification requires anything when it comes to MIDs and how they are resolved.

**Comment by Guema** [comment] 2018-07-09 10:55
> `{ "paths": {  "/*": "./src/*" } }`

Just technical speak, as im not really into code norm creation, but more code norm respect.
I think this solution has weaknesses. IMO, Without a dirty hack, it won't be possible to make glob compute a starting slash as a path, because, glob never interprets the slash other than as a sub folder.

in other words, the best solution should probably be something like :

**Comment by EECOLOR** [comment] 2018-07-19 06:52
@Guema as far as I can tell, the code does not use glob to resolve anything. The syntax here is typescript specific and the `*` is used to bind the parts together. Having `{ "paths": { "/*": "./src/*" } }` is in my opinion in no way confusing.

> The real problem being that /-starting imports are already resolved, but, are resolved as system root.

And you're free to keep that. We just want to add an alias restricting that behavior.

> the best solution should probably be something like ...

I value your input. Whether we go with an `alias` or `resolveRootPath` configuration setting totally depends on what the typescript teams deems the best solution for their library.

**Comment by EECOLOR** [comment] 2018-07-27 12:43
@andy-ms @DanielRosenwasser @ahejlsberg I got your names from the commit history in master.

I am willing to attempt a pull request for this issue, but as I mentioned in [this comment](https://github.com/Microsoft/TypeScript/issues/13730#issuecomment-397840083) I need a maintainer to sign off on the idea.

Are you the people who should sign off on this? Or should I contact someone else?

**Comment by RobertCZ** [comment] 2018-08-14 08:31
Regarding the "In Discussion" tag: This issue is a blocker for using VSCode with native EcmaScript modules (w/o RequireJS, Webpack & Co). It blocks us from finally moving to loader-less devel setup.

PS Ideally it would be also fixed for dynamic imports.

**Comment by davismj** [comment] 2018-09-21 08:51
> Leading slash refers to the root directory, so this is an absolute path. path mapping does not work on absolute or relative paths. (@mhegazy )

My code. Windows 10. TypeScript 3.0.3. 

```
import { JobsService as js1 } from '/src/services/jobs'; // doesn't work, --traceResolution says the directory doesn't exist, js3 says otherwise
import { JobsService as js2 } from '/services/jobs'; // doesn't work, expected
import { JobsService as js3 } from 'src/services/jobs'; // works, expected
import { JobsService as js4 } from 'services/jobs'; // doesn't work, expected
```

It is possible I don't understand what is meant by the root directory. Thought it would be the directory of my tsconfig.js. Maybe the directory I'm running tsc from. Maybe the `rootDir` property in my tsconfig. Perhaps you mean C:/Windows/System32?

There's nothing I can write with a leading slash that will resolve. Something is broken.

**Comment by Guema** [comment] 2018-09-25 15:27
@davismj 
Currently on Windows, the leading slash "/" is resolved as your system disk. Basically "C:", not system32 (i don't know anymore if your system can be other than C:)

As far i understand, extrapolating from what i read and @mhegazy said :

- Resolving leading slash as system root is as far as i know a Linux/Unix norm that is currently being gradually adopted on multiple Microsoft techs (PowerShell, for exemple, but i suppose TS too) allowing more cross-platform consistency for scripts and other things.

- As VsCode is a multi-language editor, i suppose path resolve is system-driven by default, because there is no webroot notion in a Py or Ruby app for exemple.

- At the same time, Es6/7/8/9/2015/2016/2017 (idk witch one exactly) decided that "/" could be a cool way to resolve root es6 imports as an Nodejs App or WebRoot depending where you build.

- TypeScript is a language you want to use for server and/or client and/or prototypes/scripts, so in some case, you want to access filesystem too.

My speculation is that Intelliscence and/or TypeScript are being in the middle of 2 (maybe more) norms collision, making things a bit more complicated than it seems in a design perspective. But i could be wrong.

**Comment by EECOLOR** [comment] 2018-10-17 21:40
It makes me a bit sad that there has been no response from maintainers on this issue that affects a large part of the community. Do not mistake my words, there is no judgement in them.

The hard part for me personally is that I understand it. Maintaining a popular library is tough, with a small group of people you are trying manage thousands of interactions. Just look at the amount of issues and pull requests in this repository, that's hard to keep track of.

It would be great if there was a way to sort issues by some sort of value/effort/impact ratio. I think this issue has the potential to be high on that list.

Anyway, if anyone reading this has contacts with any of the maintainers, please ask them to take a look at this issue. The only thing we want to add is the ability to add aliases that start with a slash. No default behavior has to change and it allows us to:

- Prevent access to our system root using `/`
- Treat `/` as the root of our project
- Get awesome typescript (and javascript) language support in IDE's

**Comment by davismj** [comment] 2018-10-18 01:08
@mhegazy Thoughts?

**Comment by EECOLOR** [comment] 2018-10-18 22:37
It turns out the matching is not holding us back. It's that leading slash imports are not passed into the path mapping facility. I created a pull request that checks all boxes except for the 'has a label on the issue' one.

The essential code that I needed to add was:

```js
if (baseUrl && paths && startsWithSlash(moduleName) && getOwnKeys(paths).find(startsWithSlash)) {
  const resolved = tryLoadModuleUsingPaths(extensions, moduleName, baseUrl, paths, loader, /*onlyRecordFailures*/ false, state);
  if (resolved) return resolved.value;
}
```

**Comment by EECOLOR** [comment] 2018-10-18 22:51
I forgot to mention in this conversation that are using leading slash imports instead of adding `{ "*": "./src/*" }` to prevent problems (collisions) with node modules. We have had a case where a module in our source directory had the same name as a node module. Because the module in our source directory was added (quite some time) later and the original reference was in an untested module, we only found the problem in a later (more problematic) stage.

**Closed** 2018-11-08 17:20 UTC
Labels: In Discussion, Suggestion

**Comment by coagmano** [comment] 2018-11-08 22:31
Thanks @EECOLOR and the team for all the work you put into this!

**Comment by nexsodev** [comment] 2019-09-05 03:30
Has this not been resolved yet?

**Comment by EECOLOR** [comment] 2019-09-05 06:28
@nexsodev It has been resolved: https://github.com/microsoft/TypeScript/pull/27980

```json
{
  "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "/*": ["./src/*"]
        }
    }
}
```

**Comment by red-meadow** [comment] 2020-01-10 02:31
@EECOLOR,  I've just noticed that with `javascript.updateImportsOnFileMove.enabled`, file renaming/move replaces paths with leading slashes with relative ones. I've found no way to configure this behavior. Should it be reported as a separate issue?

**Comment by EECOLOR** [comment] 2020-01-10 07:02
@red-meadow I should indeed be reported as separate issue. I don't think I'm qualified to help with this issue. A quick search on Github let me to: https://github.com/microsoft/TypeScript/blob/master/src/services/getEditsForFileRename.ts

That code is used throughout the code base. From a glance it seems that `paths` (aliases) are not taken into account when determining the target rename.

If this feature would be added it would probably be something like `preferPathsAliases` or something.  This however is probably not preferred when dealing with 'child' directories (from `./a/a.js` to `./a/b.js`). On top of that it will probably have performance implications.

In any case, I would create a separate issue for it and see what direction the Typescript core team would want to go.

**Comment by red-meadow** [comment] 2020-01-10 09:20
It turns out that path mapping entries are respected, but only the first one and only if it doesn't start with `/` (eg. `$/file` or `|file` is updated correctly). I will create a separate issue.

**Comment by andremarcondesteixeira** [comment] 2020-03-14 16:34
This is happening with pure javascript as well. I currently have a Spring boot project and I am trying to use Intelissense with js, but it is currently impossible.

Here is my jsconfig.json:

`
{
    "compilerOptions": {
        "baseUrl": "src/main/resources/static",
        "rootDir": "src/main/resources/static",
        "paths": {
            "/*": ["/*"]
        }
    }
}
`

When I try something like `import { FormValidation } from '/js/app/lib/forms/forms.js';` it can't find the file. But if I remove the trailing slash, Intelissense works, but my code stops working because the import point to an inexistent file. I am not using Babel, not Webpack, nor anything. Just pure javascript, that is published as is, and VSCode just can't handle it.

**Comment by EECOLOR** [comment] 2020-03-14 17:12
@andremarcondesteixeira Where do you expect `/js/app/lib/forms/forms.js` to be mapped to? If it is `src/main/resources/static/js/app/lib/forms/forms.js`, your config should probably look like this:

```json
{
  ...
  "compilerOptions": {
    ...
   "baseUrl": "./src/main/resources/static",
    ...
    "paths": {
      "/*": ["*"]
    }
  }
}
```

I am not sure if `*` as a path mapping works, so you could do something like this:

```json
{
  ...
  "compilerOptions": {
    ...
   "baseUrl": ".",
    ...
    "paths": {
      "/*": ["src/main/resources/static/*"]
    }
  }
}
```

**Comment by jeoy** [comment] 2020-03-15 02:06
> @nexsodev It has been resolved: #27980
> 
> ```json
> {
>   "compilerOptions": {
>         "baseUrl": ".",
>         "paths": {
>             "/*": ["./src/*"]
>         }
>     }
> }
> ```

Hi EECOLOR,  I just try this feature in a [brand new project](https://github.com/jeoy/test-start-with-slash) created with nest-cli.  However it seems not working as expected： check the [detail](https://github.com/jeoy/test-start-with-slash/blob/84cf1eab6271737108c9ffdf4cd4114bc509b857/src/app.module.ts#L3)

I was wondering if you could help me with this,

Thank you so much

**Comment by EECOLOR** [comment] 2020-03-15 07:42
@jeoy I will check it out as soon as I have time. You could try to add `"include": ["./src/**/*", "./node_modules/**.*"]`

**Comment by jeoy** [comment] 2020-03-15 09:33
Thanks @EECOLOR ,  added `"include": ["./src/**/*", "./node_modules/**.*"]` still doesn't work.

**Comment by andremarcondesteixeira** [comment] 2020-03-16 16:55
@EECOLOR 
I have a file called `vlan.js` in `src/main/resources/static/js/app/modules/equipments/equipment-options/network/vlan.js`.

Inside this file I have an ES6 import like this:

`import { FormValidation } from '/js/app/lib/forms/forms.js';`

when using this path with the trailing slash, I expect it to look for the file in `src/main/resources/static/js/app/lib/forms/forms.js`.

I tried using both your suggestions, but both didn't work as expected.

If I remove the trailing slash, vscode can find the file and show me the JSDocs for my class, however, my app stops working because without the trailing slash, ES6 will treat the import as a relative import and will try to find the file in `src/main/static/js/app/modules/equipments/equipment-options/network/js/app/lib/forms/forms.js` which doesn't exist.

**Comment by trusktr** [comment] 2020-08-05 00:19
@jeoy I checked your link, and I don't see the `include` option in tsconfig. Can you add that, and push the update, so we can see if it works?

**Comment by AjManoj** [comment] 2021-08-28 03:02
@andremarcondesteixeira Were you able to resolve it ?

**Comment by andremarcondesteixeira** [comment] 2021-08-29 03:30
still an issue

**Comment by EECOLOR** [comment] 2021-08-29 07:53
@AjManoj  @andremarcondesteixeira Does one of you have a pubic test project that I could check out?

I noticed in one of the cases a `jsconfig.json` was used. I have had problems in the past with that and we switched all javascript projects to `tsconfig.json` with `allowjs` and `checkjs` set to `true`.

**Comment by EECOLOR** [comment] 2021-08-30 05:57
@jeoy Previously I only checked vscode with your example and it worked. I now ran your code and discovered @nest made it fail. Upon digging I found it uses https://www.npmjs.com/package/tsconfig-paths which explicitly states: _ (that doesn't start with "/" or ".")_.

That library might not be aware of this change in paths, so you could file an issue with them.

**Comment by VityaSchel** [comment] 2022-07-14 20:43
Can someone share an example project that uses root imports please? :)
I configured tsconfig.json and reloaded TS server in Visual Studio Code, but I'm still getting `Cannot find module '/path' or its corresponding type declarations.` error
