### ISSUE TITLE
Type is not narrowed when inferring number-like string

### ISSUE THREAD

**Issue by graphemecluster** [microsoft/TypeScript#48635] opened 2022-04-10 12:05 UTC
# Bug Report

Is this working as intended?

### 🔎 Search Terms

infer with extends

### 🕗 Version & Regression Information

New feature in 4.7.0

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220408#code/C4TwDgpgBAZg9nKBeKAiALAJlVCAPYCAOwBMBnKAAwBIBvASyJggCcoAVXA48qIgVwC2AI1YBfSlAD8HKAC4+EAG6sgA)

### 💻 Code

```ts
type foo = "42" extends `${infer T extends number}` ? T : never
```

### 🙁 Actual behavior

Type of `foo` is inferred as `number`.

### 🙂 Expected behavior

Type of `foo` is inferred as `42`.

**Comment by jcalz** [comment] 2022-04-10 13:07
It is working as intended until and unless #48094 is merged.

**Comment by graphemecluster** [comment] 2022-04-10 15:00
Ah, OK. So this is a duplicate of #47141. Sorry for that.

**Closed** 2022-04-11 17:21 UTC
Labels: Duplicate
