### ISSUE TITLE
Spread operator ignores object type check

### ISSUE THREAD

**Issue by aspic-fish** [microsoft/TypeScript#51400] opened 2022-11-03 20:51 UTC
# Bug Report

### 🔎 Search Terms
spread operator object wrong type

### 🕗 Version & Regression Information

This is the behavior in every version I tried up to 5.0.0-dev.20221103

### ⏯ Playground Link

[Playground](https://www.typescriptlang.org/play?ts=4.8.4#code/C4TwDgpgBAYg9nKBeKBvAZggXFA5AIwEMAnXAXwCgKBjOAOwGdgpgd5EVUKopM4cCJXABpuUAHSSA2gEZhAJmEBmYQBZhAVmEA2YQHYAusKgB6E1DqIIxYnGLGA7rboBzMZPGoixAUQBe5MZmFlY2do7ObjzB3r6EAabm1rb2UHAA1hSUFMGYxFAkxIQgDFAAlswOdumlhKUQAB6Q1MAQACY55gACwAwAtI3NwANh+QAq4NC4dACuALb41lIGuOWllsx1DGUudIT4ADbQwIigkHjLuOI09EwFNjjLyFBS7tJyiirqWrqGFAadEJQZLhNKZWiMTY2eSPGQGZ6vHgeWTwuovOH-Kg3SG8Z4AChILhwqCk6QgIBwTGIZVcBjYCDIAEpkAA+NDZdB4rjRcwACzgADdrCwoGBbJBiKAWIhqLyINR0uVgLh1nBmOwxKw0GIeHw4qRRDwkZIvCQ4gEyEFzJZgaMIvQokaYma8P4RIlbSljBkxJQmVQgA)

### 💻 Code

An object type can be assigned with any other object type via spread operator without any errors
```ts
const foo: {} = {
  ...{
    foo: 'bar'
  },
  ...['including arrays'],
};
```

for arrays it works as expected

```ts
// type number[] is not assignable to type []
const arr: [] = [  
  ...[1,2,3,4,5,6,7]
];
// no error, ok
const arr2: [1] = [
  ...[1] as [1]
];


```

in the following code `t` property is infered correctly, but no error
```ts
const f = (arg: {[key: string]: {foo: 'bar'}}) => {}
f({
  t: {
    foo: 'bar',
    ...{bar: 'baz'}, // no error, wrong
    // bar: 'baz', // error, ok
  }
})
```

![Screenshot 2022-11-03 233547](https://user-images.githubusercontent.com/84775894/199828971-206183f3-f43e-4245-8b7c-5f4475728628.png)

### 🙁 Actual behavior
Spread operator ignores object type

### 🙂 Expected behavior
Spread operator must respect object type

**Comment by MartinJohns** [comment] 2022-11-03 21:07
Duplicate of #39998.

**Closed** 2022-11-06 18:00 UTC
Labels: Duplicate
