### ISSUE TITLE
Certificate just expired on https://www.typescriptlang.org/

### ISSUE THREAD

**Issue by fr6nco** [Microsoft/TypeScript#22667] opened 2018-03-16 23:29 UTC
Looks like the certificate has just expired

**Comment by fr6nco** [comment] 2018-03-16 23:29
https://imgur.com/a/uMYHF

**Comment by DanielRosenwasser** [comment] 2018-03-16 23:32
Duplicate of #22663.

**Comment by RyanCavanaugh** [comment] 2018-03-16 23:33
@DanielRosenwasser the site is down

🔔 

the

site

is


down

**Closed by DanielRosenwasser** 2018-03-16 23:32 UTC
Labels: Duplicate

**Comment by DanielRosenwasser** [comment] 2018-03-16 23:42
https://www.youtube.com/watch?v=ILVfzx5Pe-A
