### ISSUE TITLE
Generic interface type assertion can lose precision of typing on function parameters

### ISSUE THREAD

**Issue by coddoy** [microsoft/TypeScript#33638] opened 2019-09-27 19:46 UTC
**TypeScript Version:**  3.6.3

**Search Terms:** Generic type inference interface function

**Code**

```ts
interface ITest {
  str: string;
  num: number;
  numQuestion?: number;
}

// This type would be more expansive in a real world case
type IGenericParamater<T> = T;

interface IFunParameter<T, TKey extends keyof T>
  extends IGenericParamater<any> {
  typ: T;
  val: T[TKey];
  prop: TKey;
}
function FUN<T, TKey extends keyof T>(
  _param: IFunParameter<T, TKey>
): IGenericParamater<T> {
  return {} as any;
}

interface IGenericAssertion<T = {}> {
  paramForTest: T;
}

// This should always fail type checks because val should
// be ITest["str"] which is a string, not a number
FUN({
  typ: { num: 3, str: "boop" } as ITest,
  prop: "str",
  val: 3 //incorrect type
});

// In 3.6 val gets a more expansive type than in 3.5 allowing
// val to be string | number | undefined
let testObject: IGenericAssertion = {
  paramForTest: FUN({
    typ: { num: 3, str: "boop" } as ITest,
    prop: "str",
    val: 3 //incorrect type
  })
};
```

**Expected behavior:**
In TestObject.paramForTest's parameter the val property should type to string because ITest.str is a string and can be inferred from Prop and Typ. This was true in 3.5. It is easiest to see the change in type assertion if you go to the playground link and switch between 3.5 and 3.6 while checking the type of Val, Prop, etc.

**Actual behavior:**
In TestObject.paramForTest's parameter the val property is typed to string | number | undefined. This is keyof ITest without being restricted by the types of Prop and Typ.

**Playground Link:** [PlayGround](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgJIBUIGczIN4CwAUMsjlAFxlhSgDmA3MaSAK4C2Vb7ARtEyWTcAiq2xhgAexAB+Lhz5QBAX2LEA9OuToAFsCzIwATwAOKAO6TWAGwAmyPsnaSoKCAA8TcEFmAA3FFBkOGRXOGtkSyg7ZAQ4LAhiYzM0AHEIEGhgBAAFOCg4djhIKAAedAA+ZABebQFiUBL4JDQAMVYQPIL2CBLygBptAGkII2QPSBBbAwBrUckYbQrmcfdJ6bSMrNz8wuLoUu8jKsJBZKp0AVI-cIuAbXQRowBdK+QTKEkTC6eVYhgOggJNJkK0AKoAOQGw1Gq3Ws3mi0qAAoVgB9LzdKiodqdXY9ProQaPUbLIgASmx6UytB23X2ZUq+BWrjArCgIHwymCBiOfyIDXA0GaKFQ1O2AEEsAkoMCQOUalyTitMYVWi5MDgLvyNFpdPoyDorDFwuY4EYDPBgBFkigEDoIAgZgY+HFWAlkDcIlgjTZbLqHKLNWA7gAicih56RPT25AGkLkeiDECSXAhbiKYjgiHI06kc74IQcKgAZkG5CooZ4ki+oeQ3PiaGD-RVn2+yHDNFDLcEXtLyE0oAQLlcQMMpkSRGU5PqRE0aE5JYAdAA2T3hZB0Xq8pwuNyeby+ALjlJgHTeOOLpcAVmC1msknM9ADXsMkkD1FoIDoyAAPkXeGgP9kA6WwIBgUAIH9IhrF6QxxAAeR4AArR0wCpLZaSlGU5UVPN3nxdUoGDKhs1zFZ81MKg8AA0tyxoStq1reseSbcQe1IUgPi+SsIw4zi+2QEsB3UIcRzQk9J1IadiGUAQgA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment] 2019-10-03 22:11
This is the expected behavior due to the `{}` default of `IGenericAssertion` providing a fallback candidate of `{}` for `T` through the contextual return type of `FUN`, which is chosen due to the other parameters not providing a non-union candidate for `T`. This doesn't result in an unsoundness because `testObject` is `IGenericAssertion<{}>`.

There are bunch of other weird things going on in the example; if you'd like any advice on alternatives for how to write this, it'd be great to get something either simpler or more representative (`extend`ing `any` is not a great idea, for example, which this example does)

**Comment by coddoy** [comment] 2019-10-03 22:53
Why was the behavior in the previous versions incorrect? It seemed correct to be determining the type of `FUN({...})` the same regardless of the type of a higher level generic. I'm having trouble figuring this out since explicitly typing to `FUN<ITest, "str">` is still valid so it seems odd to now assert that the type is less strict i.e. `FUN<ITest, "str" | "num" | "numQuestion">`.

I can work on a more representative example, I was trying to cut out unnecessary types to keep the already complex example as simple as possible. The example is coming from a case where `paramForTest` would contain an object, a property of said object and a function which can be performed on the value of the object's specified property.

**Comment by RyanCavanaugh** [comment] 2019-10-04 03:00
There are fairly subtle tweaks to inference as we fix bugs and this example depends on *a lot* of different things; really it'd be necessary to do a `git bisect` to figure out which aspect changed between releases.

Having an outer type provide a more-general but still valid inference is generally never considered a bug. Inference is desired to *succeed* with the tightest *valid* type among the candidates presented, and `{}` is certainly a potential candidate here.

**Comment by Manish3177** [comment] 2019-10-04 16:14
Ryan, firstly thanks for looking into this issue. This is an oversimplification but consider this code:

```
function echo<T = any>(value: T): T { return value; }
parseInt(echo("3"));
```

Now, it doesn’t specify T when echo was invoked but the compiler was intelligent enough to infer that the return value must be a string from the input. If instead it concluded that it must be any because it wasn’t specified and the default is any, would it be wrong? No. But would it cause a degraded experience? Yes. Would it be a breaking change? Also, yes since the parseInt doesn't allow any. This oversimplified example is obviously not the one under discussion and still works just as well in 3.6 but it illustrates the kind of problem it has created for us.

The breaking change can be addressed by updating several (coddoy can provide a number if it helps) places in our code but it would still lead to a bulkier/clunkier coding pattern. To provide some context, the API affected in our code is a binding function that's use in JSX so something like:
```
<control num={binding(ob1, "num")} str={binding(ob1, "str")} ... />
```
Has to be changed to something like:
```
<control num={binding<number>(ob1, "num")} str={binding<string>(ob1, "str")} ... />
```
Again, this is somewhat of an oversimplification.

**Comment by coddoy** [comment] 2019-10-04 22:02
A colleague came up with a simpler example which I feel better demonstrates the issue, as it doesn't use `any` or `{}`.

```
interface aA<Z> {
    something?: Z;
}
interface aB<T, K extends keyof T, Z> extends aA<Z> {
    source: T;
    property: K;
    convert: (a: T[K]) => void;
}
declare function aFn<T, K extends keyof T, Z>(p: aB<T, K, Z>): aB<T, K, Z>;

const aX1: aA<string> = aFn({
    source: { strProp: "hi", numProp: 33 },
    property: "strProp",
    convert: a => a.startsWith("-"), // typescript@^3.6 error because `a: string | number`
});
```
[Playground](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAjgQQDwC0B8yDeAsAFDJnIDOA9gLYRgAWoA5gPwBcyWA3CQL4lQkWIhRwAQhgAqAGmQBpZBAAekEABMKyANYQAnlRjJZXPCrWbUmXARLlKVAK5QknKb1LkADlCpfoYHqc8h72CFQgAG4BnAAUcG4A2vIAugCUyAC8eJFUwOoeAsTqEAgANnBQKDCOIAhgwBGoAGIg0nKK5hAaWroGRia4sV6cEu0Kcrhpo5Im8pM4HiThIBRgqAAaAIyjmGtQLHiZLSCxRJ5k1M6uBJRgUAAKviPIAERMr3IgjjRPfpwAZgByD4Mjs3meASCb32fy8n3BZBW0SgYFGWTwcAAdGtKmAKAB1YCMWKvAC0rzScgA9NTkIF-BQEAcvGAAAIAPQBWIAbEooL4oMgAEalOCOCgoAAGCTuBxAzGQAB9kN8aKKoFL+GluEA)

And here is the same example without the unused Z generic. [Playground](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=16&pc=4#code/JYOwLgpgTgZghgYwgAgEYEFkG8CwAoZQ5AZwHsBbCMAC1AHMB+ALhLCnoG58BffUSWIhSoAQgB4AKgBpkAaWQQAHpBAATYsgDWEAJ6kYyCQD4FyiGo0Zs+IiVIBXKEhYSuBIgAcopD9DA6WWTdbBFIQADc-FgAKOBcAbVkAXQBKZABeE3DSYFU3XjxVCAQAGzgoFBh7EAQwYDC0ADEQSRl5JRV1LV19QyNojxZRVrkjFKHxaVG3fFCQYjBkRSHMdKaQaNx3QjJHZ2xWKAAFb0HkACJac5kQe3ITnxYAZifkbikbT1O-AIuF49O10+hDmkSgYBYcAyJjgADoFuUwMQAOrAGjRc4AWnOKQ+eG4KTcQA) I'm including this one because it is interesting that despite being unused, adding the generic changes the type inference of the inner property to be less strict.

**Closed** 2019-10-07 20:00 UTC
Labels: Working as Intended

**Comment by SlurpTheo** [comment] 2019-10-08 15:16
The [simpler repro](https://github.com/microsoft/TypeScript/issues/33638#issuecomment-538574264) above from Friday has the undesired `ts(2339)` error `Property 'startsWith' does not exist on type 'string | number'.`.

This error has gone away when testing with `typescript@3.7.0-dev.20191008` (like was the case in `typescript@3.5` and earlier).

Intentional/expected (will it stay this way?)?
