### ISSUE TITLE
Nested index signatures confuse type inference

### ISSUE THREAD

**Issue by jgzuke** [Microsoft/TypeScript#23460] opened 2018-04-17 06:17 UTC
**TypeScript Version:**  2.8

**Code**

```ts
type Maybe<T> = void | null | undefined | T;

const isSome = <T>(m: Maybe<T>): m is T => {
    return typeof m !== "undefined" && m !== null;
};

const valueOrElse = <T, U extends T>(m: Maybe<T>, orElse: () => U): T => {
    return isSome(m) ? m : orElse();
};

// Fails on double indeing
type Model1 = {
    [Name: string]: {
        foo: Maybe<string>
    }
}
function update1<Name extends keyof Model1>(name: Name, foo: Model1[Name]["foo"]) {
    // Maybe inner type is not inferred when we are indexing into Model
    let fooString1: string = valueOrElse(foo, () => "")

    // When we explicitly state the inner type it lifts the Maybe properly
    let fooString2: string = valueOrElse<string, string>(foo, () => "")
}

// Works if we remove second layer and Name indexing
type Model2 = {
    foo: Maybe<string>
}
function update2(foo: Model2["foo"]) {
    let fooString1: string = valueOrElse(foo, () => "")
}
```

**Expected behavior:**
fooString1 in update1 should not have any errors

**Actual behavior:**
`fooString1` has error as `valueOrElse(foo, () => "")` is inferred as `Maybe<string>` instead of `string`.
```
Type 'Model1[Name]["foo"]' is not assignable to type 'string'.
  Type 'Maybe<string>' is not assignable to type 'string'.
    Type 'void' is not assignable to type 'string'.
```
Note that switching to
```
let fooString1: string = valueOrElse(foo, () => {
    throw new Error("");
})
```
Gives a different error on foo
```
Argument of type 'Model1[Name]["foo"]' is not assignable to parameter of type 'void'.
  Type 'Maybe<string>' is not assignable to type 'void'.
    Type 'string' is not assignable to type 'void'.
```

**Playground Link:** https://www.typescriptlang.org/play/#src=type%20Maybe%3CT%3E%20%3D%20void%20%7C%20null%20%7C%20undefined%20%7C%20T%3B%0D%0A%0D%0Aconst%20isSome%20%3D%20%3CT%3E(m%3A%20Maybe%3CT%3E)%3A%20m%20is%20T%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20typeof%20m%20!%3D%3D%20%22undefined%22%20%26%26%20m%20!%3D%3D%20null%3B%0D%0A%7D%3B%0D%0A%0D%0Aconst%20valueOrElse%20%3D%20%3CT%2C%20U%20extends%20T%3E(m%3A%20Maybe%3CT%3E%2C%20orElse%3A%20()%20%3D%3E%20U)%3A%20T%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20isSome(m)%20%3F%20m%20%3A%20orElse()%3B%0D%0A%7D%3B%0D%0A%0D%0A%2F%2F%20Fails%20on%20double%20indeing%0D%0Atype%20Model1%20%3D%20%7B%0D%0A%20%20%20%20%5BName%3A%20string%5D%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20foo%3A%20Maybe%3Cstring%3E%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0Afunction%20update1%3CName%20extends%20keyof%20Model1%3E(name%3A%20Name%2C%20foo%3A%20Model1%5BName%5D%5B%22foo%22%5D)%20%7B%0D%0A%20%20%20%20%2F%2F%20Maybe%20inner%20type%20is%20not%20inferred%20when%20we%20are%20indexing%20into%20Model%0D%0A%20%20%20%20let%20fooString1%3A%20string%20%3D%20valueOrElse(foo%2C%20()%20%3D%3E%20%22%22)%0D%0A%0D%0A%20%20%20%20%2F%2F%20When%20we%20explicitly%20state%20the%20inner%20type%20it%20lifts%20the%20Maybe%20properly%0D%0A%20%20%20%20let%20fooString2%3A%20string%20%3D%20valueOrElse%3Cstring%2C%20string%3E(foo%2C%20()%20%3D%3E%20%22%22)%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Works%20if%20we%20remove%20second%20layer%20and%20Name%20indexing%0D%0Atype%20Model2%20%3D%20%7B%0D%0A%20%20%20%20foo%3A%20Maybe%3Cstring%3E%0D%0A%7D%0D%0Afunction%20update2(foo%3A%20Model2%5B%22foo%22%5D)%20%7B%0D%0A%20%20%20%20let%20fooString1%3A%20string%20%3D%20valueOrElse(foo%2C%20()%20%3D%3E%20%22%22)%0D%0A%7D%0D%0A

**Related Issues:** Could not find any

**Comment by ahejlsberg** [comment] 2018-04-17 14:03
This is working as intended. The type of the `foo` parameter in `update1` is `Model1[Name]["foo"]`. The compiler defers resolution of that type (instead of immediately resolving to `Maybe<string>`) because `Name` is a type parameter and, presumably, properties in `Model1` might have different types. In this particular case the properties all have the same type (because they're declared using a string index signature), but the compiler isn't factoring that in (and I don't think that it should).

It works as you expect if you instead write the type as `Model1[string]["foo"]`, indicating that you want the combined type of all properties in `Model1`.

**Comment by ahejlsberg** [comment] 2018-04-17 15:50
Alternatively, you could have `valueOrElse` just take a single type parameter (i.e. replace `U` with just `T`). That would give the compiler two positions to infer from instead of just one.

**Comment by jgzuke** [comment] 2018-04-18 23:58
This might be a stupid question, but if `Model[string]["foo"]` works as `Maybe<Primitive>`, why can `Model[Name]["foo"]` not be inferred to at least the same type when `Name` extends string?

The use case here is having a `GenericModel` and saying `Model extends GenericModel` while remaining type safe with both the generic and specific model, this means we cannot use `[string]` as when substituting in the specific model we want the type safety here.

Ie if we had
```
type Primitive = string | number | boolean;

type GenericModel = {
    [ObjName: string]: {
        value: Maybe<Primitive>
    }
}

type SpecificModel = {
    object1: {
        value: Maybe<string>
    },
    object2: {
        value: Maybe<number>
    }
}

function update<
    Model extends GenericModel, ObjName extends keyof Model
>(
    name: ObjName, value: Model[ObjName]["value"]
) {
    const nonNullValue: Primitive = valueOrThrow(value)
    // Some work
}
```
We want to still constrain value passed in to be of the type specified in SpecificModel, but it would be nice to have the compiler know that `Model[ObjName]["value"]` must be of type `Maybe<Primitive>`.

**Closed** 2018-05-04 17:30 UTC
Labels: Working as Intended
