### ISSUE TITLE
Weak typings for Array.prototype.map

### ISSUE THREAD

**Issue by kujon** [Microsoft/TypeScript#17015] opened 2017-07-07 17:10 UTC
**TypeScript Version:**  2.4.0

**Code**

The following blows up nicely as expected:

```ts
type A = {
    foo: string;
};

/** 'baz' does not exist in type 'A' */
const test1: A[] = [{ foo: 'foo', baz: 42 }];
```
Put it through the `map` method though, and any extra fields will be silently accepted:

```ts
/** no error */
const test2: A[] = ['foo'].map(val => ({ foo: val, baz: 42 }));
```

**Expected behavior:**
Both examples blow up w/ `'baz' does not exist in type 'A'`

**Actual behavior:**
Only the compilation of the first example fails.

**Comment by andy-ms** [comment] 2017-07-07 17:54
Duplicate of #11152.
Currently we can't determine a contextual type for the returned expression, so extra properties aren't checked.

**Comment by mhegazy** [comment] 2017-08-17 17:25
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-08-17 17:25 UTC
Labels: Duplicate
