### ISSUE TITLE
ES6 export interface using *

### ISSUE THREAD

**Issue by AlexanderMattoni** [Microsoft/TypeScript#6284] opened 2015-12-29 17:29 UTC
When exporting interfaces from a .d.ts file using the es6 module format, using a * symbol will generate an equivalent line in the javascript even if no file is generated by tsc.

test.d.ts:
```
export interface Test {

}
```

module_no_asterisk.ts:
```
export {Test} from "test";
```

generates an empty file. However: 

module_asterisk.ts:
```
export * from "test";
```
generates the following.
module_asterisk.js:
```
export * from "test";
```
even though no test file is generated due to it being a definition file.

Would it be possible to detect when an export * is nothing but interfaces and not generate any output?

**Comment by DanielRosenwasser** [comment] 2015-12-29 17:34
I don't recall exactly why `export *`s do not get elided, but @vladima, @mhegazy, and @weswigham probably have a clue.

**Comment by vladima** [comment] 2015-12-29 17:40
duplicate of #4492 that should be fixed in master

**Closed by vladima** 2015-12-29 17:40 UTC
Labels: Duplicate

**Comment by DanielRosenwasser** [comment] 2015-12-29 17:46
:tada:
