### ISSUE TITLE
Debug Failure when writing Promise<[]>

### ISSUE THREAD

**Issue by jeanvitor06** [Microsoft/TypeScript#17266] opened 2017-07-18 16:43 UTC
![captura de tela de 2017-07-18 12-13-27](https://user-images.githubusercontent.com/18332853/28325610-a5568a0c-6bb4-11e7-9105-b6d97e210677.png)
![captura de tela de 2017-07-18 12-16-35](https://user-images.githubusercontent.com/18332853/28325625-b1ce3366-6bb4-11e7-8b45-34138df98b63.png)

**TypeScript Version:**  2.4.1

Expected behavior:
There should be no error in this.

Actual behavior:
When returning Promise<[ ]> without the type, an error occurs in the tsc(Debug failure).

**code**
```javascript

export async function get(): Promise<[]> {
  let emails = [];
  return emails;
}

```
error message: 

```shell
yarn tsc
$ tsc
/home/jean/abrafarma/node_modules/typescript/lib/tsc.js:55776
                throw e;
                ^

Error: Debug Failure.
    at typeToString (/home/jean/abrafarma/node_modules/typescript/lib/tsc.js:23526:22)
    at reportRelationError (/home/jean/abrafarma/node_modules/typescript/lib/tsc.js:28855:34)
    at isRelatedTo (/home/jean/abrafarma/node_modules/typescript/lib/tsc.js:28972:21)
    at checkTypeRelatedTo (/home/jean/abrafarma/node_modules/typescript/lib/tsc.js:28838:26)
    at checkTypeAssignableTo (/home/jean/abrafarma/node_modules/typescript/lib/tsc.js:28578:20)
    at checkReturnStatement (/home/jean/abrafarma/node_modules/typescript/lib/tsc.js:37576:33)
    at checkSourceElement (/home/jean/abrafarma/node_modules/typescript/lib/tsc.js:38751:28)
    at Object.forEach (/home/jean/abrafarma/node_modules/typescript/lib/tsc.js:298:30)
    at checkBlock (/home/jean/abrafarma/node_modules/typescript/lib/tsc.js:36918:16)
    at checkSourceElement (/home/jean/abrafarma/node_modules/typescript/lib/tsc.js:38730:28)
error Command failed with exit code 1.

```
TsConfig:
```json
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "noEmitOnError": true,
    "importHelpers": true,
    "alwaysStrict": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "rootDir": "server",
    "outDir": "dist_server",
    "noUnusedLocals": true
  },
  "include": [
    "server/**/*.ts"
  ],
  "compileOnSave": false,
  "exclude": [
    "node_modules",
    "bower_components"
  ]
}


```

**Comment by andy-ms** [comment] 2017-07-18 17:47
Could you paste the text of the error message here as text?
Also, do you have a code sample that reproduces the error?

**Comment by DanielRosenwasser** [comment] 2017-07-19 22:21
Looks like the same issue as #17303. Closing in favor of that one since it seems to have a minimal test case.

**Comment by DanielRosenwasser** [comment] 2017-07-19 22:23
Probably related to #17303.

**Closed** 2017-07-20 17:09 UTC
Labels: Bug
