### ISSUE TITLE
Property initializer should get the same completion as property assignment

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15361] opened 2017-04-24 22:38 UTC
_From @unional on April 22, 2017 9:12_

- VSCode Version: 1.11.2
- OS Version: OSX

```ts
abstract class Foo {
  options: {
    x: string
  }
}

class Koo extends Foo { // already know options is missing x
  options = {
    // should get `x` as property
  }
  do() {
    this.options = {
      // does recognize `x` as property
    }
  }
}
```

![image](https://cloud.githubusercontent.com/assets/3254987/25303098/dd4f1864-2700-11e7-83d4-c32ea155bc26.png)

![image](https://cloud.githubusercontent.com/assets/3254987/25303091/ce5143fa-2700-11e7-801a-cf3eea2a9d10.png)

_Copied from original issue: Microsoft/vscode#25181_

**Comment by sandersn** [comment] 2017-04-24 23:04
Typescript sees Koo's options as distinct from Foo's options when declaring them. It just checks that Koo's options is assignable to Foo's options after it has been created. 

In contract, `this.options` is referring to something that is already declared. Note that if you provide a more specific type for Koo's options, like `options = { x: "string literal type" }`, then the completion for `this.options` in Koo will have that more specific type.

**Comment by sandersn** [comment] 2017-04-24 23:06
A full explanation of the approaches we have tried is at #6118. Both would provide completions here, but neither works well as part of the language.

**Comment by sandersn** [comment] 2017-04-24 23:06
Duplicate of #3667

**Closed** 2017-04-24 23:06 UTC
Labels: Duplicate, VS Code Tracked
