### ISSUE TITLE
Mapped type with enum keys produces {}

### ISSUE THREAD

**Issue by tyrielv** [Microsoft/TypeScript#23084] opened 2018-04-02 19:33 UTC
**TypeScript Version:**  2.9.0-dev2.0180402

**Search Terms:** mapped generic type array

**Code**

```ts
enum Fruits {
    Mango = 0,
    Banana = 1
}

interface IFruitMetadata<T> {
    [Fruits.Mango]: T;
    [Fruits.Banana]: T;
}

const onSale1: IFruitMetadata<boolean>[] = [{
    [Fruits.Banana]: 22,
    [Fruits.Mango]: 32,
}];

const onSale2: Partial<IFruitMetadata<boolean>>[] = [{
    [Fruits.Banana]: 22,
}];

```

**Expected behavior:**
Both assignments have compile errors (number not assignable to boolean) (This is the behavior on 2.7.2)
**Actual behavior:**
Only the unmapped type assignment has a compile error.
**Playground [Link](http://www.typescriptlang.org/play/#src=enum%20Fruits%20%7B%0D%0A%20%20%20%20Mango%20%3D%200%2C%0D%0A%20%20%20%20Banana%20%3D%201%0D%0A%7D%0D%0A%0D%0Ainterface%20IFruitMetadata%3CT%3E%20%7B%0D%0A%20%20%20%20%5BFruits.Mango%5D%3A%20T%3B%0D%0A%20%20%20%20%5BFruits.Banana%5D%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Aconst%20onSale1%3A%20IFruitMetadata%3Cboolean%3E%5B%5D%20%3D%20%5B%7B%0D%0A%20%20%20%20%5BFruits.Banana%5D%3A%2022%2C%0D%0A%20%20%20%20%5BFruits.Mango%5D%3A%2032%2C%0D%0A%7D%5D%3B%0D%0A%0D%0Aconst%20onSale2%3A%20Required%3CIFruitMetadata%3Cboolean%3E%3E%5B%5D%20%3D%20%5B%7B%0D%0A%20%20%20%20%5BFruits.Banana%5D%3A%2022%2C%0D%0A%20%20%20%20%5BFruits.Mango%5D%3A%2032%2C%0D%0A%7D%5D%3B%0D%0A%0D%0A)**

**Related Issues:**

**Comment by andy-ms** [comment] 2018-04-02 20:17
The problem is that `Partial<IFruitMetadata<boolean>>` is `{}`. Simplified example:

```ts
const enum E { A }
interface I { [E.A]: number; }

type T = { [K in keyof I]: boolean }; // Fails

type Bools<T> = { [K in keyof T]: boolean };
type B = Bools<I>; // No error, returns {}
```

**Comment by mhegazy** [comment] 2018-04-02 23:12
Duplicate of https://github.com/Microsoft/TypeScript/issues/13042.

**Comment by mhegazy** [comment] 2018-04-02 23:12
`keyof I` should be `never` really. but that is a different bug.

**Closed** 2018-04-17 15:50 UTC
Labels: Duplicate
