### ISSUE TITLE
sweeter syntax for creating new anonymous subclass instance

### ISSUE THREAD

**Issue by ORESoftware** [microsoft/TypeScript#56262] opened 2023-10-30 18:15 UTC
### 🔍 Search Terms

anonymous superclass subclass cast casting coercion type-coercion 

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Right now we have this:

```typescript
const x = new (class extends A(){
    method1(){}
})()
```

But I am looking for something sweeter, like this instead:

```typescript
const x = new A(){
    method1(){}
};
```

technically it's correct since it's always type A (even it's a subclass (not just an implementation) it's automatically coerced/casted to the superclass A).

can this happen?

other languages have ugly things like this which we should avoid:

```typescript
const x = new A(){{
    method1(){}
}};
```

### 📃 Motivating Example

For terseness and beauty's sake.

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

yes

**Comment by nmain** [comment] 2023-10-30 18:16
Is this not a duplicate of https://github.com/microsoft/TypeScript/issues/56245?

**Comment by MartinJohns** [comment] 2023-10-30 18:35
And from the viability checklist:

> This isn't a runtime feature (e.g. library functionality, **non-ECMAScript syntax** with JavaScript output, new syntax sugar for JS, etc.)

The words "sweeter syntax" in the title should ring some bells.

**Comment by RyanCavanaugh** [comment] 2023-10-30 18:48
@ORESoftware I'm sorry to say it, but it's time for you to stop logging issues here. People creating bugs/suggestions are expected to have a minimal understanding of the scope and operation of TypeScript, but you've consistently not demonstrated that. 46 of your last 50 issues were categorized as some variant of "noise". Out of the 100 issues you've logged, zero got labelled "Bug", and only 1 was an accepted change as far as I can tell. This in particular appears to be exact duplicate of an issue logged a few days ago, which is not acceptable behavior. This is not your [first warning](https://github.com/microsoft/TypeScript/issues/32477#issuecomment-514294695) on using the issue tracker responsibly; future misuse will result in an org block.

**Closed** 2023-10-30 18:49 UTC
Labels: Suggestion, Out of Scope
