### ISSUE TITLE
Allow excess properties in assignment if they were used in a `satisfies` check

### ISSUE THREAD

**Issue by vpzomtrrfrt** [microsoft/TypeScript#59399] opened 2024-07-23 20:07 UTC
### 🔎 Search Terms

known properties satisfies, subtype

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about the known properties check

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240723#code/JYOwLgpgTgZghgYwgAgILIN4Chm+TAewIC5kQBXAWwCNoBuLAXyy1ElkRQCFkIAPSCAAmAZzSYceanCikRYKKADmDZlgA2EMMgLUAVqVQMsuvcgC8mQiWQAmADTJps5ACIlUCAE9XjZCLgwYBEYYAgxLjogA

### 💻 Code

```ts
interface A {
    foo: number;
}

interface B extends A {
    bar: string;
}

let obj: A;

obj = {foo: 2, bar: "grey"} satisfies B;
```

### 🙁 Actual behavior

Throws error:
```
Object literal may only specify known properties, and 'bar' does not exist in type 'A'.
```

### 🙂 Expected behavior

The property should be allowed, since I specify the type in `satisfies` and it's a subtype of the variable's type

**Comment by snarbies** [comment] 2024-07-23 20:59
It certainly defies intuition, but I've never seen anything to suggest that a `satisfies` check would cause excess property checks to be elided.

Adding a type assertion to the literal wards off the except property check.
```typescript
obj = {foo: 2, bar: "grey"} satisfies B as B;
````

**Comment by Andarist** [comment] 2024-07-23 21:05
In this situation this object literal is a subject to two excess property checks (:

```ts
obj = {foo: 2, bar: "grey", extra: 42} satisfies B
```

**Comment by RyanCavanaugh** [comment] 2024-07-23 22:12
Per the design of `satisfies`, it's trying as hard as possible to act consistently as if you separately wrote
```ts
{foo: 2, bar: "grey"} satisfies B;
obj = {foo: 2, bar: "grey"};
```
We don't really have a type operation that corresponds to what's being requested here - once the object literal is "unfreshened", then other operations would start to fail (e.g. literal narrowing).

**Comment by MartinJohns** [comment] 2024-08-09 18:43
Duplicate of #52999.

**Closed** 2024-08-12 01:32 UTC
Labels: Duplicate
