### ISSUE TITLE
CFA with undefined disjoint works weird

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#25899] opened 2018-07-24 18:52 UTC
**TypeScript Version:**  3.1.0-dev.20180724

**Search Terms:**

**Code**

```ts
type A = { a: number; b: undefined } | { a: undefined; b: number };
var a!: A;
if (a.a === undefined) {
    // type a = {a: number | undefined; b: number | undefined}
    a.b + 1; // Object is possibly 'undefined'.
}
```

**Expected behavior:**
No error

**Actual behavior:**
Object is possibly 'undefined'.

**Playground Link:** 

**Related Issues:**

**Comment by mhegazy** [comment] 2018-07-24 19:24
Duplicate of https://github.com/Microsoft/TypeScript/issues/24193

**Closed** 2018-08-02 21:55 UTC
Labels: Duplicate
