### ISSUE TITLE
Constructor assignment with default parameter is not stated as accepting undefined (if there is non-optional parameters after it)

### ISSUE THREAD

**Issue by yukulele** [microsoft/TypeScript#53727] opened 2023-04-10 20:02 UTC
# Bug Report

### 🔎 Search Terms

- Constructor Assignment
- Default parameters
- undefined

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "Constructor assignment"

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.1.0-dev.20230410&ssl=10&ssc=1&pln=1&pc=1#code/MYGwhgzhAECC0G8BQ1rAPYDsIBcBOArsDungBQqrQAOBARiAJbDQBm660AvNAKwA00APRDoEABboCIACbQ6AU2hlMBALaK80AD7QCmGQtaNMCmQEpKqOmDwAuMfhMBzSucTQAvkm9IM2HGgwAEZuaFMAdzgyACYABkEAcgAPRPcRaHQAaz8sXCCYsMjo-UNjUxkk1PTRbKQgA

(click on **.D.TS** button to see the type definition)

### 💻 Code

```ts
class A {
  constructor(public foo = 5, bar: string) { }
}
```

### 🙁 Actual behavior

type definition is:

```ts
declare class A {
    foo: number;
    constructor(foo: number, bar: string);
}
```

editor suggest `A(foo: number, bar: string): A`. \
Fortunately using `new A(undefined, 'x')` is not marked as error.

### 🙂 Expected behavior

type definition should be:

```ts
declare class A {
    foo: number;
    constructor(foo: number | undefined, bar: string);
}
```

editor should suggest `A(foo: number | undefined, bar: string): A`.

**Comment by a-tarasyuk** [comment] 2023-04-13 18:16
Duplicate of https://github.com/microsoft/TypeScript/issues/48547

/cc @RyanCavanaugh

**Closed** 2023-04-13 18:24 UTC
Labels: Duplicate
