### ISSUE TITLE
Whole number / integer range type / operator

### ISSUE THREAD

**Issue by ismail-codinglab** [microsoft/TypeScript#40936] opened 2020-10-04 21:23 UTC
## Search Terms

Whole number range, integer range, range operator

## Suggestion
Unlike https://github.com/microsoft/TypeScript/issues/15480
I would like to propose a whole number only range operator, which is easy to implement and can be improved iteratively. 

## implementation logic
`x..y` for whole numbers only.
✅`-10..-1`
✅`1..100`
❌`0.1..2`
❌`1..2.1`
❌`"a".. "c"`
Any detectable non whole number would not be accepted as input.

Fully working and well tested implementation used by millions of developers (rust, Ada & kotlin) : 

- https://en.m.wikibooks.org/wiki/Ada_Programming/Types/range
- https://kotlinlang.org/docs/reference/ranges.html
- https://doc.rust-lang.org/reference/expressions/range-expr.html

✅No need to reinvent the wheel
✅No need to account for floats
✅Consistency across popular languages
✅Tested and stable code from existing popular languages

## Use Cases
Inputs like percentages, score etc can be range limited and allow for less human errors. 

## Examples

`setMatch(percentage: 1..100)`
`setTestGrade(grade: 1..10)`

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by nikeee** [comment] 2020-10-04 21:54
Loosely related proposal ("Range Types (`T[X:Y]`) for TypeScript"), althoug focused on ranges for arrays:
https://gist.github.com/rbuckton/5fd81582fdf86a34b45bae82d842304c

**Comment by ismail-codinglab** [comment] 2020-10-04 23:03
Yeah might not be best example, I'd recommend going to the popular languages for proper examples. It does look related, perhaps the range operator can be used in arrays like seen in the links of other languages

**Comment by MartinJohns** [comment] 2020-10-05 06:16
Duplicate of #195 and #15480.

**Closed** 2020-10-09 18:00 UTC
Labels: Duplicate
