### ISSUE TITLE
TypeScript 2.0.3: Can't find @types installation

### ISSUE THREAD

**Issue by arahansen** [Microsoft/TypeScript#11193] opened 2016-09-27 21:26 UTC
The compiler doesn't seem to be picking up on my npm installed @types modules. Is there a specific configuration I might be missing?

**TypeScript Version:**  2.0.3

**Code**

```ts
installed:
npm install @types/angular --save-dev

// tsconfig.json

{
		"compileOnSave": false,
		"compilerOptions": {
			"types": ["angular"],
			"typeRoots": [
      	"node_modules/@types"
      ],
			"module": "amd",
			"noImplicitAny": false,
			"preserveConstEnums": true,
			"target": "es5",
			"declaration": false,
			"moduleResolution": "classic",
			"experimentalDecorators": true,
			"suppressImplicitAnyIndexErrors": true,
			"sourceMap": true,
			"jsx": "react"
		},
		"include": [
			"node_modules/@types/**/*",
			"app/**/*.ts",
			"app/**/*.tsx"
		]
}

run:
node_modules/typescript/bin/tsc -p .

```

**Expected behavior:**
Typescript compiler can find @types npm installations and successfully compile.

**Actual behavior:** 
Several errors thrown throughout my source code that reference not finding the angular typings:
`error TS2307: Cannot find module 'angular'.`

**Comment by mhegazy** [comment] 2016-09-27 21:30
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/11103. currently `@types` are not loaded unless `moduleResolution === node`.

**Closed** 2016-09-27 21:30 UTC
Labels: Duplicate
