### ISSUE TITLE
TS1.8.2 Compile on save not working when combining to a single js file

### ISSUE THREAD

**Issue by rankida** [Microsoft/TypeScript#7210] opened 2016-02-24 10:03 UTC
Hi.

I have a large ASP.MVC site that has numerous `.ts` files. Having upgraded from TS 1.6 to 1.8 the _compile on save_ functionality was no longer working. We _Combine JavaScript output into file_ but if I remove this it generated the individual file on save without issue.

So I am lead to believe it is an issue with TS1.8 when combining to a single file the _Compile on save_ function is not working. When we build the solution the file is generated correctly.

I am running VS2015 Update 1 on Windows 10.
We are running TS1.8.2 installed via the VS2015 tool download from typescriptlang.org

Any help on this issue would be greatly appreciated.

Thanks

![image](https://cloud.githubusercontent.com/assets/295619/13281802/c359a2aa-dadd-11e5-8280-222796a429e1.png)

**Comment by Lanayx** [comment] 2016-02-24 12:41
Same issue (just updgraded to 1.8.4). Compile on build works, compile on save doesn't

**Comment by mhegazy** [comment] 2016-02-24 18:08
Do you see this on newer projects? do you see any error messages in the status bar? e.g.:
![image](https://cloud.githubusercontent.com/assets/8000722/13295615/9138f5f4-dade-11e5-9e54-c57bea68e0c0.png)
Can you share a project we can reproduce this on?

**Comment by Lanayx** [comment] 2016-02-24 19:59
No errors, and compile on build works well without any issues. The message on saving is just - 'file saved', but no js is generated. Will check this in the new project tomorrow.

**Comment by paulvanbrenk** [comment] 2016-02-24 20:28
@Lanayx Can you search the drive for that file... it may not be generated in the right location.

**Comment by rankida** [comment] 2016-02-24 21:08
Hi @mhegazy 

I also didn't see any indication from the status bar that anything was happening (other than _File Saved_ )

My entire office is experiencing issues with TypeScript 1.8. Some people are reporting that the file is generated after *minutes* and extremely high CPU usage.

A two typescript file project appears to work on save so I am now wondering if it is because we have a large number (most likely hundreds) of typescript files in the project. In TS 1.6 it could take 3-5 seconds to tell us _Generations successful_ in the status bar, but now many people just see 100% CPU load.

Happy to run some tests if they would be of help, but the repo is not publicly accessible.

Thanks

**Comment by mhegazy** [comment] 2016-02-24 21:32
@rankida We would love to look at your project. can you share your project? we would be happy to sign an NDA for it. you can email a sample directly to `mhegazy` at `microsoft`

**Comment by rankida** [comment] 2016-02-24 21:49
@mhegazy Thanks for responding so soon. We have hived off all the typescript from the rest of the app so that we can test the TS1.8 issues, so this might be able to be shared with Microsoft, but I would obviously need approval from my bosses.

**Comment by vladima** [comment] 2016-02-24 22:55
This issue looks like a dupe of #7221 - fix for it will go in soon and should be available in today's nightly builds (available via `typescript@next` on npm). You can pick `typescriptServices.js` in `<VS2014-INSTALL-PATH>\Common7\IDE\CommonExtensions\Microsoft\TypeScript` with one from the nightly build see if it fixes problem

**Comment by Lanayx** [comment] 2016-02-25 08:51
Just tested with a new project. Compile on save does work until you add a tsconfig file. After it is added, compile doesn't work anymore. After I removed tsconfig, compile on save worked again.

**Comment by mwijnands** [comment] 2016-02-25 09:17
+1. Also I added `"compileOnSave": true,` to the tsconfig.json but still... doesn't work.

**Comment by mhegazy** [comment] 2016-02-25 17:46
@Lanayx compileOnSave is turned off by default for new tsconfig.json files. did you add "compileOnSave" property to your tsconfig? (see https://github.com/Microsoft/TypeScript/wiki/tsconfig.json#compileonsave)

**Comment by mhegazy** [comment] 2016-02-25 22:59
looking at @rankida solution, seems like https://github.com/Microsoft/TypeScript/issues/7221 is the source here. 

We are working on a new release to address this issue in the next few days, and untill then here are some workarounds:
 1.	Set `<TypeScriptNoEmitOnError>false</TypeScriptNoEmitOnError>` in your project file or `"noEmitOnError": false` in your tsconfig.json
 2.	Use nigtly nuget package: https://github.com/Microsoft/TypeScript/wiki/Nightly-drops#using-nuget-with-msbuild
 3.	Copy typescriptServices.js in https://github.com/Microsoft/TypeScript/blob/release-1.8/lib/typescriptServices.js to `<VS2015-INSTALL-PATH>\Common7\IDE\CommonExtensions\Microsoft\TypeScript`

**Closed by mhegazy** 2016-02-25 22:59 UTC
Labels: Bug, High Priority

**Comment by Lanayx** [comment] 2016-02-26 07:37
Thank you. "noEmitOnError": false worked
