### ISSUE TITLE
TypeScript inference doesn't consider assignments inside callbacks

### ISSUE THREAD

**Issue by stringham** [Microsoft/TypeScript#18208] opened 2017-09-01 17:29 UTC
**TypeScript Version:**  2.1.6 -- Also happening on master.

**Code**

```ts
let foo: string | number = 0;

[1, 'a', 3].forEach(val => {
    if (typeof val == 'string') {
        foo = val;
    }
});

if (typeof foo == 'string') {
    console.log(foo.toLocaleLowerCase()); // Error: Property 'toLocaleLowerCase' does not exist on type 'never'.
}
```

**Expected behavior:**
Because of the potential assignment in the callback closure, TypeScript should know that `foo` could be of type `string`

**Actual behavior:**
TypeScript doesn't use the assignment inside of the callback to expand the possible type of `foo`.

If you add:

```ts
if(Math.random() < 0) {
    foo = 'a';
}
```
then the type is properly expanded.

**Comment by kitsonk** [comment] 2017-09-01 20:12
Duplicate of #11498

**Closed** 2017-09-01 21:06 UTC
