### ISSUE TITLE
Incorrect Type Intelligence for `in` operator

### ISSUE THREAD

**Issue by JounQin** [microsoft/TypeScript#31356] opened 2019-05-12 07:10 UTC
**TypeScript Version:**  3.5.0-dev.20190512

**Search Terms:** `Incorrect Type Intelligence`

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

function isPromise(obj: {}) {
  return 'then' in obj && typeof obj.then === 'function'
}
```

**Expected behavior:**
No Error

**Actual behavior:**
`Property 'then' does not exist on type 'never'.`

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=function%20isPromise(obj%3A%20%7B%7D)%20%7B%0D%0A%20%20return%20'then'%20in%20obj%20%26%26%20typeof%20obj.then%20%3D%3D%3D%20'function'%0D%0A%7D

**Related Issues:**

**Comment by jcalz** [comment] 2019-05-12 18:32
Duplicate of #21732

**Closed** 2019-05-15 18:00 UTC
Labels: Duplicate
