### ISSUE TITLE
Return type not inferred correctly in static method

### ISSUE THREAD

**Issue by SylvainEstevez** [Microsoft/TypeScript#7497] opened 2016-03-13 17:28 UTC
**TypeScript Version:** 
1.8.7

**Code**
```ts
'use strict';

class User {
  firstName: string;
  lastName: string;  
  
  static getInstance() {
    return new this();
  }
}

class StaffUser extends User {  
  position: string;
}

let staffUser = StaffUser.getInstance();

console.log(staffUser.position); // error TS2339: Property 'position' does not exist on type 'User'
```

**Expected behavior:**

`staffUser` should be of type `StaffUser`, not simply `User`.

**Actual behavior:** 
The compiler doesn't guess that `getInstance` in `StaffUser` returns instances of `StaffUser`.

**Comment by vladima** [comment] 2016-03-13 22:44
duplicate of #5863

**Closed** 2016-03-14 03:53 UTC
Labels: Duplicate
