### ISSUE TITLE
Go To Definition(F12) option need to be enhanced (Even the Definition one is in another page with in the project))like sublime text?i'm facing this issue from long since i install VS code ?Any help on this? 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#8547] opened 2016-05-10 15:41 UTC
_From @vinod-a-ext on May 10, 2016 10:49_

- VSCode Version:Latest 1.1.0
- OS Version:windows

Steps to Reproduce:

1. In your controller inject a service/factory for a http call
2. press F12 (go to definition ) to visit the factory which results negative?

_Copied from original issue: Microsoft/vscode#6238_

**Comment by jrieken** [comment] 2016-05-10 15:41
_From @isidorn on May 10, 2016 12:38_

Please provide a short code snippet for which this behavior can be reproduced. Or even better create a repository on gitHub which we can clone and see this behavior

**Comment by jrieken** [comment] 2016-05-10 15:41
_From @vinod-a-ext on May 10, 2016 14:50_

1.factory.js file
```
(function() {
'use strict';

    app.factory('Service', function() {
        return{
            Callmefromcontroller : function() {
           return '1';
                }
        }  
});
});
```
2.controller.js

```
 // Controller of the App
 
app.controller('Aboutus2Ctrl', function ($scope,Service) {
Service.Callmefromcontroller();

  });
```

**Comment by jrieken** [comment] 2016-05-10 15:41
_From @vinod-a-ext on May 10, 2016 14:52_

when i press F12 on Callmefromcontroller in controller.js I need to go to Callmefromcontroller defintion method which is in factory.js file?Any help on this

**Comment by jrieken** [comment] 2016-05-10 15:41
@vinod-a-ext I formatted the snippet to your previous comment, hope it's still correct.

**Comment by jrieken** [comment] 2016-05-10 15:41
and to clarify, you want `go to definition` understand the service injection tricks such that the editor knows that the `Service` argument has been injected and find where it was defined?

**Comment by jrieken** [comment] 2016-05-10 15:41
_From @vinod-a-ext on May 10, 2016 15:16_

Spot on @jrieken i need same thing which done perfectly in sublime text editor

**Comment by jrieken** [comment] 2016-05-10 15:41
ok. moving to the TypeScript team which provides the brain the behind JavaScript and TypeScript smartness in VS Code. I know they have been starting some work on support for angular et al

**Comment by mhegazy** [comment] 2016-05-11 21:15
There are no plans on supporting this understanding of angular code. such deep understanding of the run-time behavior of a framework is out of scope at the current time.

**Closed by mhegazy** 2016-05-11 21:15 UTC

**Comment by jrieken** [comment] 2016-05-12 07:18
@mhegazy out of curiosity and cos I met angular folks yesterday: I remember talk about compiler plugins etc. What happened to that?

**Comment by vinod-a-ext** [comment] 2016-05-12 09:43
So I think we have to compile the Runtime complier of sublime text editor 3 which is the best one to do this so far.Moving to sublime Text 3 editor from VS Code.Hoping to come back to Vs code onces i got this feature.

**Comment by jrieken** [comment] 2016-05-12 09:45
@vinod-a-ext what package are you using with ST?

**Comment by vinod-a-ext** [comment] 2016-05-12 09:53
when I press F12 on the 44 line (refer below image) it (sublime text editor) comes with a pop up listing l files ( by comparing all files in the project with the same  name--- on the word I pressed F12)  ,so that gives me a quick access to jump to my wanted file.Hope I clarified  my question with this?

![image](https://cloud.githubusercontent.com/assets/12810078/15210576/b596a79e-1854-11e6-9255-58b92a03b295.png)

**Comment by vinod-a-ext** [comment] 2016-05-12 09:56
@jrieken No need to add any packages.it's a inbuilt thing!

**Comment by kitsonk** [comment] 2016-05-12 09:56
@jrieke, Compiler Extensibility is tracked by #6508 and has references to related tickets (including #6477 which was essentially a duplicate of this already raised by the vscode team 😄 )

**Comment by jrieken** [comment] 2016-05-12 10:55
@vinod-a-ext Thanks, I learnt something. Let me see what our extension API allows you to do...

**Comment by jrieken** [comment] 2016-05-12 15:25
@vinod-a-ext I gave it a try: https://marketplace.visualstudio.com/items?itemName=jrieken.fuzzy-definitions. 

It's an extension that hooks into `go to definition` and it uses a combination of [symbol search](https://code.visualstudio.com/docs/editor/editingevolved#_open-symbol-by-name)  and full text search tricks to find _potential_ definitions. 

![readme](https://cloud.githubusercontent.com/assets/1794099/15220076/808b7dd8-1866-11e6-9a0c-1338824b3e77.gif)

**Comment by AllaKishore** [comment] 2016-05-13 09:25
@jrieken ,
i installed ext install fuzzy-definitions but it's not working as you explained in the above screen shot.
Any OS limitation?

**Comment by jrieken** [comment] 2016-05-13 10:38
shouldn't be the case. it's a bit quite and dirty and uses some full test searching tricks. it will surely have issue with large workspaces (hello node_modules folder). can you check the dev tools from within vscode and check if it contains useful info?

**Comment by vinod-a-ext** [comment] 2016-05-13 11:40
Installed-->Tryed-->Resulted as Below But you are on right path Buddy
![image](https://cloud.githubusercontent.com/assets/12810078/15246842/89eb4ed6-192d-11e6-897b-fe2bbe6ab6b0.png)

**Comment by jrieken** [comment] 2016-05-13 16:45
Thanks for checking, I pushed an update which hopefully fixes that... Let's continue to track more issues here: https://github.com/jrieken/fuzzy-definitions/issues. I want to make this a thing 💪

**Comment by vinod-a-ext** [comment] 2016-05-16 09:18
@jrieken  --->Refer this https://github.com/jrieken/fuzzy-definitions/issues/1
