### ISSUE TITLE
`this` type in constructor

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#22430] opened 2018-03-09 15:00 UTC
**TypeScript Version:** 2.8.0-dev.20180308

**Code**

```ts
class Node {
    constructor(readonly next?: this) {}
}
class SubNode extends Node {
    constructor(readonly value: number, next?: this) {
        super(next);
    }
}
new SubNode(0, new SubNode(1));
```

**Expected behavior:**

No error.

**Actual behavior:**

`this` type not available in a constructor. I don't know how hard that would be to implement and didn't see an issue for it.

It can be worked around like so:
```ts
export class Node {
    readonly next?: this;
    // Protected as it's not type-safe
    protected constructor(next?: Node) {
        this.next = next as this;
    }
}
class SubNode extends Node {
    static nu(value: number, next?: SubNode) {
        return new SubNode(value, next);
    }
    private constructor(readonly value: number, next?: SubNode) {
        super(next);
    }
}
SubNode.nu(0, SubNode.nu(1));
```

**Comment by mhegazy** [comment] 2018-03-09 18:30
duplicate of https://github.com/Microsoft/TypeScript/issues/5863

**Closed** 2018-03-23 19:02 UTC
Labels: Duplicate
