### ISSUE TITLE
type predicates don't narrow the type of the parent object

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#43547] opened 2021-04-06 10:36 UTC
# Bug Report

### 🕗 Version & Regression Information
4.3.0-dev.20210406

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210406&ssl=1&ssc=1&pln=23&pc=2#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXywGcAhWAChwCMArcDALnjQGtUcB3VASkatswKF4pGAChRGAJ4AHBCPgBeeAG9R8dfACOyAB6NUyALaUQYgL7ips+ADEcOADwAVeCB0YQqYEPkAfFWYAfIoqahqUsIxOYeoRAF76Ribm4qCQsAhgeIQYSPaMdo5+AYGp4NBwSGiYuPiI9iJkAG5QEMggBfYOIoE88E04WMDiWIjwZESN9TgAdBEwXFyhGvAA9KvTc7DwWTBwmBCS8KiwMBwgwPAYOMKRMTvZuVAhm-P3Wag58JQv9lswM20OnEK3W03gwBwIEIqAA5LkAOYgXInPbnS5QLyCeA5LAQCC2LrKMzwfw9AA0rianiuAAscMgEbT4OwEKwOAQMLChM9Ct1YKUVtMpvYuKIzEA)

### 💻 Code

```ts
declare function isBar(object: unknown): object is Bar

type Bar = {
    qux: number
}

type Foo<T extends Bar | {}> = {
    bar: T
    baz: number
}

declare const foo: Foo<Bar | {}>

declare function fooBar(value: Foo<Bar>): void

if (isBar(foo.bar)) {
    //foo.bar correctly narrowed to Bar:
    const a = foo.bar
    const b = foo.bar.qux

    //foo doesn't get narrowed and is still Foo<{} | Bar>, even though we know it's a Foo<Bar>
    fooBar(foo)
}
```

### 🙁 Actual behavior
`foo.bar` is narrowed, but `foo` remains the same type

### 🙂 Expected behavior
`foo`  is narrowed to Foo<Bar>

**Comment by MartinJohns** [comment] 2021-04-06 10:43
Duplicate of #42384. Used search terms: `narrow parent`

**Closed** 2021-04-06 10:44 UTC
