### ISSUE TITLE
Expect type go to optional to be unoptional...

### ISSUE THREAD

**Issue by hpachy** [microsoft/TypeScript#55007] opened 2023-07-13 13:21 UTC
# Bug Report

### 🔎 Search Terms

-Make some properties optional in a TypeScript type
-typescript pick optional

### 🕗 Version & Regression Information

currrent version : "typescript": "^5.1.6"
Don t know if that bug existed before, just got the issue right now

### ⏯ Playground Link

[Bug on the typescript playground](https://www.typescriptlang.org/play?#code/PTAEF5K6dv4Y6AoEEn1AMwJYCcBnAF1AFMAPUgWwAcAbU9DBVMZ9jz8ZZIgTxqMA8jSI4A9gDsAhnQCi5AMalRAMXF4APABUANKG0AlUgEcArvlIATMuSKlJVgqADWpPuKwGAfBFAAFaTwxWR1fADIAnEUXHX0jUws8a28eHEl7PCxpZQNSYlAAb2RQUtAicQrQAC5QYjx0gHNQErKKioBGGrqiBslG1tL28QAmbvqmwfLK8QBmcd7JgF8efkEAoJC6bXyScFARMSlZBWU1DU1WneJdVoByYbvQAB8HmZGn1+HZp+RU5EUUgKADdZGZSABBbqBYI4WTXIj7YplaZVWp3Cb9O76KbDLrozGNbG497dDGLLG3FHfMmE4krZA4LwAClBdHBEIAdHiAJRTQGSEFg0gAIRqCL8bI5rCYXDl8sgMoVdVIApsFGo9EYCqgSp1+o4qwEjG0xq6SNaWHE4g6tUJlutIztFIGDLWJuNYwtpStNudfQGPsdAH5-cseFgzJJFEdJNhJAjWcLaqbBB0eUVWskiGY8HGpaRkAyBQV3V6iktQNJnKnSCMeDK5Hg8BpGSyy5zfSMM8j44my3yGWgmy28KAAO44IgAC1AaqnEjjUlAUaspFwkmsbdAzI7XdAAEJICvHOv0tYe5aE7td57Bzxh82NBOp7P3Z5t7fBJ5yp7O46mFAckAzuS8fWvYgvzre8gA)

### 💻 Code

Code inside the playground

### 🙁 Actual behavior

Even if I condition the type I still got an error raise by typescript which is `Type 'string | undefined' is not assignable to type 'string'`

### 🙂 Expected behavior

I expect type go to optional to be unoptional

**Comment by MartinJohns** [comment] 2023-07-13 13:45
Duplicate of #42384 and many others.

It would be a fairly unsafe operation as well. `fnTest` could store a reference to the object to be used later, but meanwhile `undefined` could be assigned to the objects property.

**Closed** 2023-07-16 01:34 UTC
Labels: Duplicate
