### ISSUE TITLE
Exclude<T, U> type not working like Diff<T, U>

### ISSUE THREAD

**Issue by yortus** [Microsoft/TypeScript#21929] opened 2018-02-14 02:36 UTC
**TypeScript Version:**  2.8.0-dev.20180213

**Search Terms:** 
- Exclude
- Diff

**Code**

```ts
// Old 'Diff' type, superseded since #21847 by new 'Exclude' builtin type
type Diff<T extends string, U extends string>
    = ({[P in T]: P } & {[P in U]: never } & { [x: string]: never })[T];

type NonFooKeys1<T extends object> = Diff<keyof T, 'foo'>;      // remove 'foo' using Diff
type NonFooKeys2<T extends object> = Exclude<keyof T, 'foo'>;   // remove 'foo' using Exclude

type Test1 = NonFooKeys1<{foo: 1, bar: 2, baz: 3}>; // Test1 is "bar" | "baz"
type Test2 = NonFooKeys2<{foo: 1, bar: 2, baz: 3}>; // Test2 is "foo" | "bar" | "baz"
```

**Expected behavior:**
`Test2` should be `"bar" | "baz"`, the same as `Test1`.

**Actual behavior:**
The key `"foo"` was not removed from `keyof T` when using the `Exclude` builtin type.

**Related Issues:**
- [Predefined conditional types #21847](https://github.com/Microsoft/TypeScript/pull/21847)
- [Add Omit<T,K> and Diff<T,U> to lib.d.ts #19569](https://github.com/Microsoft/TypeScript/issues/19569)

**Comment by DanielRosenwasser** [comment] 2018-02-14 08:25
Of note, I'm getting some strange quick info. When defined as

```ts
type NonFooKeys<T> = Exclude<keyof T, 'foo'>;
```

I get

```ts
type NonFooKeys<T> = keyof T
```

**Comment by jack-williams** [comment] 2018-02-14 10:30
Is this related to #21664 ? `Exclude` works when used directly for me.

```ts
type BarBaz = Exclude<keyof { foo: 1, bar: 2, baz: 3 }, 'foo'> // BarBaz = "bar" | "baz"
```

**Comment by falsandtru** [comment] 2018-02-14 11:18
related #21862.

**Comment by ahejlsberg** [comment] 2018-02-14 17:08
Duplicate of #21862.

**Comment by tycho01** [comment] 2018-02-15 20:52
The other issue is marked fixed now.

**Closed** 2018-02-16 05:11 UTC
Labels: Duplicate
