### ISSUE TITLE
Expression classes emit incorrect js code

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#5342] opened 2015-10-20 15:32 UTC
```
var a = new class {
	foo(){
		return 123;
	}
}
a.foo();

```
Generate this code
```
var a = new (function () {
    function class_1() {
    }
    class_1.prototype.foo = function () {
        return 123;
    };
    return class_1;
})();
a.foo(); // throw error, because a is Function -> new (fn)()

```

**Comment by xLama** [comment] 2015-10-20 15:39
Maybe? 
```
var a = new ((function () {
    function class_1() {
    }
    class_1.prototype.foo = function () {
        return 123;
    };
    return class_1;
})());

```

**Comment by vladima** [comment] 2015-10-20 16:06
dupe of #4630

**Closed by vladima** 2015-10-20 16:06 UTC
Labels: Duplicate
