### ISSUE TITLE
VS Code TypeScript started failing with "To enable project-wide ... language features, exclude large folders..."

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#53492] opened 2023-03-24 20:34 UTC
# Bug Report

I was fine yesterday, and between then and today at some point VS Code starts to always show me the error

```
To enable project-wide JavaScript/TypeScript language features, exclude large folders with source files that you do not work on.
```
### 🔎 Search Terms

^ the error above

### 🕗 Version & Regression Information

- This is a crash **No**

- This changed between versions ______ and _______

Here's my version as of today:

```
Version: 1.76.2 (Universal)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:54:09.061Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes
```

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

This just started happening today. I was fine before today. Nothing has changed in the project, I have not pulled new code today, and now VS Code will not load Intellisense features, showing a tooltip with that message:

![Screenshot 2023-03-24 at 12 42 01 PM](https://user-images.githubusercontent.com/297678/227633030-23048af8-288e-4de5-8922-a50c966a4eaf.png)

I tried adding exclusions (didn't have to before) but no luck. Warning persists.

- I was unable to test this on prior versions because ___time____

### ⏯ Playground Link

N/A

### 💻 Code

N/A

### 🙁 Actual behavior

The warning

### 🙂 Expected behavior

No warning

**Comment by trusktr** [comment] 2023-03-26 01:12
Is there some sort of numerical limit that prevents VS Code TypeScript features from turning on (similar to how other things like folding, syntax, etc, are disabled for large files)? If so, has that changed recently? And is there an option to turn off the limit?

**Comment by mjbvz** [comment] 2023-03-27 15:21
We haven't seen other users reporting this on the VS Code side. @trusktr What version did you update from?

**Comment by falldowngoboone** [comment] 2023-04-19 18:53
I'm seeing this as well. Just started today after updating to 1.77.3.

**Comment by rkstar** [comment] 2023-04-19 20:38
for me... it was after i had ran `expo build:web` which created a massive `web-build` directory. i added that dir to my `exclude` list in `tsconfig.json` and everything was right with the world.

**Comment by JustinPierce** [comment] 2023-05-10 21:37
I started seeing this issue earlier this week when our organization installed the GitHub Copilot extension. I don't know what the conflict is, but I can reliably resolve the issue by disabling Copilot in my IDE. I'm apparently the only one on my team seeing the issue at the moment, but it definitely seems to be related to Copilot.

**Comment by mindbrave** [comment] 2023-05-24 11:42
I had the same problem for quite some time now, but I had it only in one project where I am working on few different project and what was interesting is that it was the smallest project, like just a bunch of files for some experiments.
I found out that I had `"allowJs": true` in tsconfig so it was also checking all js files, so I started to look for a big js file. It turned out it was bundle file that I was building using webpack, when I excluded that bundle file then error disappeared.

**Comment by nobreferreira** [comment] 2023-09-29 09:14
Although I very aggressively tried to exclude everything I could, I still have the warning.

More annoying than the warning is not having a proper autocomplete.

**Comment by Ajdija** [comment] 2023-12-13 11:33
Same issue, exclude "*" resolves the warning, but even listing all hidden and non-hidden files individually is not helping. Of course "*" is not an option - no autocomplete.

**Comment by AbhiBhutani** [comment] 2023-12-15 03:35
> I started seeing this issue earlier this week when our organization installed the GitHub Copilot extension. I don't know what the conflict is, but I can reliably resolve the issue by disabling Copilot in my IDE. I'm apparently the only one on my team seeing the issue at the moment, but it definitely seems to be related to Copilot.
> 
> Adding an aggressive list of includes to `jsconfig.json` allows Intellisense to load, but it takes a long time (several minutes) and seems really flaky. I'll regularly see the "initializing JS/TS features" message in the info bar, and Intellisense will not function while that is happening.
> 
> [Update] In my case, this appears to be an issue that was introduced in v1.85.75 of the Copilot extension for VSCode. Reverting to the version before that makes the issue go away. I believe my situation is entirely unrelated to the TS server, but maybe this will help someone.

After removing Copilot, it resolved my issue too. Thanks.

**Comment by AbhiBhutani** [comment] 2023-12-15 04:20
Had to exclude some folders to get it working again.

**Comment by mschipperheyn** [comment] 2024-02-29 20:38
This has suddenly started happening for us. Huge blocker. Concerned to see this open for a year already without solution or workaround.

**Comment by RyanCavanaugh** [comment] 2024-02-29 22:36
We need a way to reproduce the problem to investigate it. It'd be great if someone could provide one.

**Comment by RyanCavanaugh** [comment] 2024-03-29 16:27
I'm really sorry that people are encountering problems, but if we don't have a way to reproduce the problem, we have zero chance of fixing it.

**Comment by prafed** [comment] 2024-04-03 11:20
I am having constant issues with VSCode doing this and becoming unresponsive. Anytime I do a `build` of our packages in our monorepo VSCode goes unresponsive and unusable .... the only solution is hard restart of the app.

I've tried this with all extensions disabled

**Comment by RyanCavanaugh** [comment] 2024-04-05 17:27
That's very unfortunate. We need a way to reproduce the problem so that we can fix it. Can you help?

**Comment by RyanCavanaugh** [comment] 2024-04-11 22:12
Locking / closing due to lack of repro. If you're seeing this, please log a new issue

# including enough information to reproduce the problem

and we'll be happy to investigate. Thanks!

**Closed by RyanCavanaugh** 2024-04-11 22:12 UTC
Labels: Needs More Info
