### ISSUE TITLE
Inconsistency between type literal and interface assignability to index signature

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#25880] opened 2018-07-23 22:44 UTC
**TypeScript Version:**  3.1.0-dev.20180721

**Code**

```ts
type T = { x: number };
interface I { x: number; }

let index: { [key: string]: number };
let t: T = { x: 0 };
let i: I = { x: 0 };

index = { x: 0 }; // OK
index = t; // OK
index = i; // Error
```

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.ts:10:1 - error TS2322: Type 'I' is not assignable to type '{ [key: string]: number; }'.
  Index signature is missing in type 'I'.

10 index = i; // Error
```

**Comment by mhegazy** [comment] 2018-07-23 22:48
Duplicate of https://github.com/Microsoft/TypeScript/issues/15300

**Comment by andy-ms** [comment] 2018-07-23 22:53
What's relevant to the linked PR is, how can one constrain a type such that all of the *values* of that type extend something?
```
type ValuesAreStringOrNumber = { [key: string]: string | number };
declare function f<T extends ValuesAreStringOrNumber>(t: T): T;
interface XNumber {
    x: number;
}
const o = f<XNumber>({ x: 0 });
```
The example works perfectly without the type annotation (and errors on `{ x: {} }`), but fails when an interface type is provided.

**Closed** 2018-08-01 00:26 UTC
Labels: Duplicate
