### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined in 'Object.find' during 'getApplicableRefactors'

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#22555] opened 2018-03-14 02:54 UTC
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.2
**VSCode Version** 1.21.0-insider
**command requested**: getApplicableRefactors
**hitting sessions**: 141
**proportion of all sessions**: 0.010049893086243763
**five line hash**: 277ac3a53c1b3f452c23d053fa87d60e
**stack**
```
TypeError: Cannot read property 'length' of undefined
    at Object.find (tsserver.js:1524:34)
    at recordUsagebySymbol (tsserver.js:81757:41)
    at recordUsage (tsserver.js:81726:36)
    at collectUsages (tsserver.js:81719:25)
    at visitNode (tsserver.js:12623:24)
    at Object.forEachChild (tsserver.js:12986:24)
    at collectUsages (tsserver.js:81722:28)
    at visitNode (tsserver.js:12623:24)
    at Object.forEachChild (tsserver.js:12977:24)
    at collectUsages (tsserver.js:81722:28)
    at collectReadsAndWrites (tsserver.js:81595:17)
    at getPossibleExtractionsWorker (tsserver.js:81041:38)
    at getPossibleExtractions (tsserver.js:80998:26)
    at Object.getAvailableActions (tsserver.js:80597:35)
    at unknown (tsserver.js:77283:128)
    at getIterator (tsserver.js:1734:23)
    at Object.next (tsserver.js:1729:35)
    at Object.arrayFrom (tsserver.js:2268:32)
    at Object.getApplicableRefactors (tsserver.js:77282:23)
    at Object.getApplicableRefactors (tsserver.js:83497:32)
    at IOSession.Session.getApplicableRefactors (tsserver.js:90354:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89310:61)
    at unknown (tsserver.js:90553:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90544:28)
    at IOSession.Session.executeCommand (tsserver.js:90553:33)
    at IOSession.Session.onMessage (tsserver.js:90573:35)
    at Interface.<anonymous> (tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by andy-ms** [comment] 2018-03-14 14:51
Duplicate of #21803

**Closed by andy-ms** 2018-03-14 14:51 UTC
Labels: Duplicate, Source: Telemetry
