### ISSUE TITLE
Support multiple tsconfig files for different environments

### ISSUE THREAD

**Issue by SonofNun15** [Microsoft/TypeScript#8500] opened 2016-05-06 13:46 UTC
Most tools allow you to specify a specific configuration file if desired. For example, with Karma, the default config file is karma.conf.js, but you can pass a different file to the command line to target a different file. This lets you have multiple configurations for different environments.

The primary use case for this is test environments. Often the compilation settings and more specifically the files (type definitions!) included are very different.

When the test environment has to share the same tsconfig with the application, sometimes ambient type definitions for test libraries have to be included with the application build. This could easily result in a `spyOn()` jasmine call passing the application build and failing hard at run time.

It would be really nice to have a `tsconfig.tests.json` next to the application `tsconfig.json`.

**Comment by SamGraber** [comment] 2016-05-06 13:47
+1

**Comment by TheOriginalJosh** [comment] 2016-05-06 14:04
+2

**Comment by kitsonk** [comment] 2016-05-06 15:27
Dupe of #6109

**Comment by mhegazy** [comment] 2016-05-06 16:51
this is already supported today. `--p` argument can be a folder (implicitly meaning `tsconfig.json`) or a filename, to which you can pass whatever file you need.

see https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#the---project--p-flag-can-now-take-any-file-path for more details.

**Closed by mhegazy** 2016-05-06 16:51 UTC

**Comment by SonofNun15** [comment] 2016-05-06 17:38
Might I suggest an improvement to the documentation then? It is very unclear that -p can refer to a file. Believe me, I looked. 😀

**Comment by mhegazy** [comment] 2016-05-06 22:40
updated in https://github.com/Microsoft/TypeScript-Handbook/commit/fdd9621c877bb2ab010f7499696609a5723752cd
