### ISSUE TITLE
no error report for auto prop type

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#56461] opened 2023-11-19 11:47 UTC
### 🔎 Search Terms

.

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and 5.2.2
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZgLhgChAIwFZIN4wA4BOIeSAjDAL4CUMAvAHwwBuIAlgCZ0q6HFcBMlGg3xE8AbiA

### 💻 Code

```ts
const f: (obj: { prop: 1 }) => any = ({ prop = 2 }) => prop;
```

### 🙁 Actual behavior

no error

### 🙂 Expected behavior

report error like:

```ts
const f: (value :1) => any = (value = 2) => value;
```

```ts
const f = ({ prop = 2 }: { prop: 1 }) => prop;
```

**Comment by MartinJohns** [comment] 2023-11-20 09:01
I would call this a duplicate of #35190.  The default value is not used to narrow the type of your property, so it resolves to `number`, which is fine for your implementation.

**Closed** 2023-11-21 04:50 UTC
Labels: Duplicate
