### ISSUE TITLE
Generated JavaScript has unnecessary amd dependency

### ISSUE THREAD

**Issue by alvarorahul** [Microsoft/TypeScript#8231] opened 2016-04-20 23:39 UTC
TypeScript version 1.8.9

**Code**

File 1

```ts
export const enum Foo {
    Bar
}
```

FIle2.ts

```ts
import file1 = require("./file1");
var x = file1.Foo.Bar;
```

Generated JavaScript File2.js

**Expected behavior:**

define(["require", "exports"], function (require, exports) {
    "use strict";
    var x = 0 /* Bar */;
});

**Actual behavior:** 

define(["require", "exports", "./file1"], function (require, exports, file1) {
    "use strict";
    var x = 0 /* Bar */;
});

It would be great if file2.js doesn't pull in file1.js as a dependency.

We noticed this happens when we use const enums.

**Comment by mhegazy** [comment] 2016-04-21 00:18
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/4690.

**Comment by mhegazy** [comment] 2016-04-21 00:22
as a workaround consider using:

```ts
import {Foo} from "./file1";
```

**Closed by mhegazy** 2016-04-21 00:22 UTC
Labels: Bug
