### ISSUE TITLE
Support direct typing when using instanceof for better intellisense

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/TypeScript#6518] opened 2016-01-17 10:56 UTC
Hello,

Here is my code:
```
let value: any
 if (value instanceof MyClass) {
     // value is any. needs to typecast like this to get intellisense working:
     (<MyClass>value).prop=true;
}
```

It would be great to support this feature.

Thanks in advance and I hope this could help others.

**Comment by Arnavion** [comment] 2016-01-17 20:47
`instanceof` already narrows types.

```typescript
let value2: MyClass | string;
if (value2 instanceof MyClass) {
    value2.prop = true; // value2 is a MyClass inside the if-block. No typecast needed.
}
```

The reason it doesn't in your example is specifically because `value` is of `any` type, which `instanceof` doesn't narrow. See https://github.com/Microsoft/TypeScript/issues/1426 for why it works this way.

**Comment by DanielRosenwasser** [comment] 2016-01-18 00:10
Duplicate of #1595, #1938, and #6301.

**Closed by DanielRosenwasser** 2016-01-18 00:10 UTC
Labels: By Design, Duplicate
