### ISSUE TITLE
incompatible types error unless I use an inline object literal for a dictionary object

### ISSUE THREAD

**Issue by robianmcd** [Microsoft/TypeScript#7759] opened 2016-04-01 01:54 UTC
**TypeScript Version:** 
1.8.7

**Code**

```ts
interface Test {
    field: {[key: string]: string};
}

var test: Test;
var foo = {qwerty: 'qwerty'};

test = {
    field: foo
};
```

**Expected behavior:**
I don't see any errors.

**Actual behavior:** 
I get the following error:

> app\app.ts(46,1): error TS2322: Type '{ field: { qwerty: string; }; }' is not assignable to type 'Test'.
  Types of property 'field' are incompatible.
    Type '{ qwerty: string; }' is not assignable to type '{ [key: string]: string; }'.
      Index signature is missing in type '{ qwerty: string; }'.

If I modify my code to this then I don't get an error

```
interface Test {
    field: {[key: string]: string};
}

var test: Test;

test = {
    field: {qwerty: 'qwerty'}
};
```

**Comment by DanielRosenwasser** [comment] 2016-04-01 07:43
Thanks but this looks like a duplicate of #6041. Should be fixed in our nightlies. Give it a try with `npm install -g typescript@next`!

**Closed by DanielRosenwasser** 2016-04-01 07:43 UTC

**Comment by robianmcd** [comment] 2016-04-01 14:14
Thanks I'll give that a shot
