### ISSUE TITLE
CodeFix to import entire module into single variable

### ISSUE THREAD

**Issue by normalser** [microsoft/TypeScript#13295] opened 2017-01-05 11:46 UTC
Not sure if this would be possible but it would be nice if one could import entire module into single variable.

For example CodeFix on `bluebird` or on `mapSeries`

![image](https://cloud.githubusercontent.com/assets/1723815/21679467/46c9d04c-d312-11e6-906e-51b217fb3c91.png)

would offer `import * as bluebird from 'bluebird'`

**Comment by aleksey-bykov** [comment] 2017-01-05 21:40
it would require a long list of configurable aliases #13270 just like for #13084:
```json
"codefixes": {
    "import": {
        "aliases": {
            "bluebird": "../../bluebrid.js"
        }
     }
 }
```

**Comment by aluanhaddad** [comment] 2017-01-10 04:24
This comment seems relevant https://github.com/leebyron/ecmascript-more-export-from/issues/11#issuecomment-214422001 Specifically the performance characteristics of this pattern are perhaps significant.

**Comment by Aarilight** [comment] 2017-05-01 06:48
I wonder if this could be fixed relatively easily by piggybacking on the exports from the module. For instance, in the screenshot that @normalser provided, he requests a specific property of the bluebird file. If you take off the `bluebird` part, and just do `mapSeries`, it should already offer you to import that as `import { mapSeries } from "bluebird";`
As a result, the codefixer could see `bluebird.mapSeries`, see that `bluebird` is undefined, but see you're trying to get something specific from it, look for that specific thing that you're getting (in this case, `mapSeries`), then suggest importing everything into the `bluebird` variable you're using. `import * as bluebird from "bluebird";`

**Comment by mhegazy** [comment] 2018-01-12 00:32
This should not be needed with the auto-import feature.
![animation](https://user-images.githubusercontent.com/8000722/34854191-ff86758c-f6ec-11e7-8520-274c78475370.gif)

**Comment by Yuudaari** [comment] 2018-01-12 00:46
See the OP. The request is to import an entire module into one variable, not to import one export of a module.

**Comment by DanielRosenwasser** [comment] 2018-11-12 20:32
We now have a refactoring to go between the two:

![image](https://user-images.githubusercontent.com/972891/48373562-05f15980-e677-11e8-99ea-fa122cb44ef7.png)

Is that reasonable?

**Comment by Yuudaari** [comment] 2018-11-12 20:49
That'll be nice for refactoring. I think this issue is still useful for writing the code, as that code fix will be more of a workaround since it takes more steps. 

I can imagine being used to using the namespace import in one file and then moving to another and starting to do it that way, but it's not imported yet. There's no code fix for that, so then you have to first import the child, then change it to a namespace import at the top of the file. I could also imagine copying code that uses the namespace style and having to do the workaround for that as well.

As a result I still think this issue is worth keeping, even if it's implemented a long way down the road.

**Comment by RyanCavanaugh** [comment] 2024-03-11 19:05
This doesn't seem to be a common request.

**Closed by RyanCavanaugh** 2024-03-11 19:05 UTC
Labels: Suggestion, Declined, Domain: Quick Fixes

**Comment by DanielRosenwasser** [comment] 2024-03-11 19:11
Was this a duplicate of #23830?
