### ISSUE TITLE
TS 1.8.2 Error: Debug Failure. False expression on mismatched enum declaration

### ISSUE THREAD

**Issue by ZachHardin** [Microsoft/TypeScript#10945] opened 2016-09-16 05:54 UTC
Typescript 1.8.2

This error is pretty cryptic. Thanks to the enumRelatedTo clue I was able to figure it out pretty quickly. If you have a d.ts file with a declared enum and the same declared in a class with a value mismatch this will throw. A similar issue was reported at https://github.com/Microsoft/TypeScript/issues/10522 but there's a different stack in this case.

something.d.ts
declare enum Something {
   ONE, TWO
}

something.ts
declare enum Something {
   ONE
}

C:\Users\Zach\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:32989
                throw e;
                ^

Error: Debug Failure. False expression:
    at Object.assert (C:\Users\Zach\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:757:23)
    at reportError (C:\Users\Zach\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:15894:26)
    at enumRelatedTo (C:\Users\Zach\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:16444:29)
    at isRelatedTo (C:\Users\Zach\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:15922:34)
    at checkTypeRelatedTo (C:\Users\Zach\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:15882:26)
    at checkApplicableSignature (C:\Users\Zach\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:18968:26)
    at chooseOverload (C:\Users\Zach\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:19251:30)
    at resolveCall (C:\Users\Zach\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:19175:26)
    at resolveCallExpression (C:\Users\Zach\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:19312:20)
    at getResolvedSignature (C:\Users\Zach\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:19408:47)

**Comment by mhegazy** [comment] 2016-09-16 22:18
Duplicate of https://github.com/Microsoft/TypeScript/issues/7629. should be fixed in TS 2.0 and later.

**Closed by mhegazy** 2016-09-16 22:18 UTC
