### ISSUE TITLE
Breaking changes for types with union/recursive/generic when upgrading from v2.9.2 to v3.4.0

### ISSUE THREAD

**Issue by foresightyj** [Microsoft/TypeScript#29992] opened 2019-02-20 10:23 UTC
**TypeScript Version:**  3.4.0-dev.201xxxxx

The latest version 3.4.0-dev.20190220 still has this issue.

![image](https://user-images.githubusercontent.com/1296736/53084473-e1413380-353b-11e9-9229-f4ff5e7299d7.png)

**Search Terms:**
Sorry. I do not even know any keyword that can describe my problem. I am not that good at compiler jargons.

**Code**

```ts
export interface WidgetBase {
    title?: string,
    widgetKey: string,
}

type NonOptionalKeys<T> = { [k in keyof T]-?: undefined extends T[k] ? never : k }[keyof T];

type Child<T extends WidgetBase> = { [P in NonOptionalKeys<T>]: T[P] }

export interface NumberWidget extends WidgetBase {
    type: "number",
    minimum: number,
    maximum: number,
}
export interface ListWidget extends WidgetBase {
    "type": "list",
    "minimum_count": number,
    "maximum_count": number,
    "each": ChildWidget //MARK1
}

export type PrimitiveWidget = | NumberWidget

export type ChildWidget =
    | Child<NumberWidget>
    | Child<ListWidget> //MARK2

type ListChild = Child<ListWidget>

```

**Expected behavior:**

`ListChild` should be equivalent to (exactly as it behaves in v2.9.2)

```
 {
    type: "list";
    minimum_count: number;
    maximum_count: number;
    each: ChildWidget;
    widgetKey: string;
}
```
![image](https://user-images.githubusercontent.com/1296736/53084615-2e250a00-353c-11e9-8e92-9980c415d6eb.png)

**Actual behavior:**
```
type ListChild = {
    [x: string]: any;
}
```

**DO NOTE** that, if you comment out either the line containing **MARK1** or the line containing **MARK2**, the type inference works correctly.

![image](https://user-images.githubusercontent.com/1296736/53084715-5ca2e500-353c-11e9-8040-b39df11ac52d.png)

**Playground Link:** 

[Playground Link](https://www.typescriptlang.org/play/#src=export%20interface%20WidgetBase%20%7B%0D%0A%20%20%20%20title%3F%3A%20string%2C%0D%0A%20%20%20%20widgetKey%3A%20string%2C%0D%0A%7D%0D%0A%0D%0Atype%20NonOptionalKeys%3CT%3E%20%3D%20%7B%20%5Bk%20in%20keyof%20T%5D-%3F%3A%20undefined%20extends%20T%5Bk%5D%20%3F%20never%20%3A%20k%20%7D%5Bkeyof%20T%5D%3B%0D%0A%0D%0Atype%20Child%3CT%20extends%20WidgetBase%3E%20%3D%20%7B%20%5BP%20in%20NonOptionalKeys%3CT%3E%5D%3A%20T%5BP%5D%20%7D%0D%0A%0D%0Aexport%20interface%20BooleanWidget%20extends%20WidgetBase%20%7B%0D%0A%20%20%20%20type%3A%20%22boolean%22%2C%0D%0A%20%20%20%20trueTitle%3F%3A%20string%0D%0A%20%20%20%20falseTitle%3F%3A%20string%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20ListWidget%20extends%20WidgetBase%20%7B%0D%0A%20%20%20%20%22type%22%3A%20%22list%22%2C%0D%0A%20%20%20%20%22minimum_count%22%3A%20number%2C%0D%0A%20%20%20%20%22maximum_count%22%3A%20number%2C%0D%0A%20%20%20%20%22collapsable%22%3F%3A%20boolean%2C%20%2F%2Fdefault%20to%20false%2C%20means%20all%20expanded%0D%0A%20%20%20%20%22each%22%3A%20ChildWidget%20%2F%2FMARK%201%0D%0A%7D%0D%0A%0D%0Aexport%20type%20PrimitiveWidget%20%3D%20%7C%20BooleanWidget%0D%0A%0D%0Aexport%20type%20ChildWidget%20%3D%0D%0A%20%20%20%20%7C%20Child%3CBooleanWidget%3E%0D%0A%20%20%20%20%7C%20Child%3CListWidget%3E%20%2F%2FMARK%202%0D%0A%0D%0Atype%20ListChild%20%3D%20Child%3CListWidget%3E%0D%0A)

**Related Issues:**

**Comment by RyanCavanaugh** [comment] 2019-02-20 19:35
Simplified
```ts
type NonOptionalKeys<T> = { [k in keyof T]: T[k] extends number ? k : never }[keyof T];
type Child<T> = { [P in NonOptionalKeys<T>]: T[P] }

export interface ListWidget {
    "type": "list",
    "minimum_count": number,
    "maximum_count": number,
    "collapsable"?: boolean, //default to false, means all expanded
    "each": Child<ListWidget>;
}

type ListChild = Child<ListWidget>
```

**Comment by foresightyj** [comment] 2019-02-21 00:04
@ryancavanaugh Thanks for the response. I suppose your simplified code is just another case similar to MARK1 and MARK2 in my question. The code I presented above is a minimal test case simplified from my original code. I have all sorts of widgets, primitive widgets like BooleanWidget, NumberWidget, etc and complex widgets like ListWidget, CompositeWidget which can contain other widgets. And child widgets can be any type of widget, not just Child<ListWidget>.

**Comment by foresightyj** [comment] 2019-02-21 01:16
@RyanCavanaugh After verifying your simplified code against v2.9.2, it is actually different from my original code. Your simplified version produces the same type in both v2.9.2 and v3.4.0.

```ts
type ListChild = {
    [x: string]: any;
}
```

![image](https://user-images.githubusercontent.com/1296736/53136251-4b4bee00-35b9-11e9-8525-e883c32c6278.png)

**Comment by ahejlsberg** [comment] 2019-02-25 17:49
It previously (sometimes) worked because our circularity detection wasn't particularly robust in 2.9. `Child<T>` generally isn't circular, but ends up having a circular constraint type if `T` itself has a property of type `Child<T>`. We now detect the circularity as we're resolving `NonOptionalKeys<ListWidget>` and then substitute the error type (basically an `any`) for `NonOptionalKeys<ListWidget>`. That's how we end up with the `{ [x: string]: any }` type.

The core issue really is that we aren't reporting an error when we detect the circularity. It's tricky to do so because it only happens for certain instantiations and only when we actually resolve the members of the mapped type. Thus, there's no good source location to associate with the error.

Arguably, if we're not going to report an error, we should at least substitute `never` for a circular constraint in a mapped type such that the resolved type becomes `{}`.

**Closed** 2019-02-28 20:57 UTC
Labels: Bug

**Comment by ahejlsberg** [comment] 2019-02-28 20:59
To be clear, what's fixed is that we now error upon detecting the circular constraints during type instantiations.

**Comment by foresightyj** [comment] 2019-03-04 09:28
@ahejlsberg Thanks for the quick response. I tried the nightly build （Version 3.4.0-dev.20190302 which I suppose contains the fix). But it seems to behave the same as v3.4.0. See both the screenshot and the result from command line.

![image](https://user-images.githubusercontent.com/1296736/53723519-edfe4980-3ea2-11e9-9608-e6c897e074a6.png)

```
➜  ts node node_modules/typescript/bin/tsc -V
Version 3.4.0-dev.20190302
➜  ts node node_modules/typescript/bin/tsc test.ts
```

Also, to be sure, is this fix meant to drop the support of such circular constraint type which actually worked in 2.9.2, and I need to figure out new ways to solve my problem?

**Comment by ahejlsberg** [comment] 2019-03-04 14:28
The issue isn't uncovered until the compiler resolves the members of `Child<ListWidget>`, so you won't see an error until you include code in your program that actually references a member of `ListChild`. Just hovering over `ListChild` isn't enough. For example, add the following an the error appears:

```ts
declare let x: ListChild;
x.type;
```

Yes, you'll need to write the types in a manner that doesn't involve circular constraints.
