### ISSUE TITLE
Improved union/intersection type inference bug?

### ISSUE THREAD

**Issue by bartq** [Microsoft/TypeScript#7603] opened 2016-03-20 20:25 UTC
Just read about [this new TypeScript feature](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#improved-unionintersection-type-inference) and tried to use it in my project, but...

**TypeScript Version:** 

1.8.9

**Code**

```ts
type T = {a:any} | {b:any};

let myObject:{c:T};

function hasA(value:T):value is {a:any}{
  return 'a' in value;
}
if(hasA(myObject.c)){
  myObject.c.a; // <- the error goes from here
}
```

**Expected behavior:**

No error.

**Actual behavior:** 

`Error:(24, 14) TS2339: Property 'a' does not exist on type '{ a: any; } | { b: any; }'.`

Shouldn't it be considered as a bug?

**Comment by yortus** [comment] 2016-03-21 01:38
Duplicate of #3812?

That is, the problem is that type guards don't yet work with property accesses (like `myObject.c`). Your example works if the property access is done *before* the type guard, which can then use a simple variable:

```ts
let c = myObject.c;
if(hasA(c)){
  c.a; // <- no error here anymore
}
```

**Comment by vladima** [comment] 2016-03-21 01:40
@yortus is correct, also https://github.com/Microsoft/TypeScript/pull/7140 should also address this issue, see section `Dotted names in type guards`

**Closed by vladima** 2016-03-21 01:40 UTC
Labels: Duplicate
