### ISSUE TITLE
Type parameter does not appear in completion list for unfinished object type in return position

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1674] opened 2015-01-14 23:40 UTC
```ts
interface I<TString, TNumber> {
    [s: string]: TString;
    [s: number]: TNumber;
}

declare function foo<TString, TNumber>(obj: I<TString, TNumber>): { str: TString
```

Trigger a completion list at the end of the TString reference in the return type. TString does not appear in the completion list, although it should.

If you put a close brace to terminate the object type, and then trigger the same completion, it works.

It also works if you trigger completion in the middle of the name TString, without adding the close brace.
![tstringcompletion](https://cloud.githubusercontent.com/assets/8052525/5750074/3b9be4a4-9c04-11e4-93cc-e5778293ab96.gif)

**Comment by JsonFreeman** [comment] 2015-01-14 23:44
![tstringcompletion](https://cloud.githubusercontent.com/assets/8052525/5750071/2dcfe6fe-9c04-11e4-9a9b-7b07ca0c1c6f.gif)

**Comment by mhegazy** [comment] 2015-03-12 04:35
dupe of #1410

**Closed by mhegazy** 2015-03-12 04:35 UTC
Labels: Bug
