### ISSUE TITLE
Convert to ES2015 Class Refactor does not observe tab size

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#17129] opened 2017-07-12 17:10 UTC
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

From https://github.com/Microsoft/vscode/issues/30528

**Code**
With tab size set to two spaces:

```js
function foo() {
  this.x = 1
}
```

Run the convert to es2015 class refactoring

**Expected behavior:**
Two spaces are used for indents

```js
class foo {
  constructor() {
    this.x = 1;
  }
}
```

**Actual behavior:**
Four spaces are used for indents

```js
class foo {
    constructor() {
        this.x = 1;
    }
}
```

**Comment by mhegazy** [comment] 2017-09-21 18:07
@mjbvz looks like we are not getting the format options before the refactor command. looks like we are getting these once per session before the first format command.

**Comment by DanielRosenwasser** [comment] 2017-09-21 18:09
Is this not a duplicate of #18328?

**Comment by mhegazy** [comment] 2017-09-21 18:10
@mjbvz give it a try, and if you see no issues if the format options are sent, we can close this issue. if we have other issues we can keep it open.

**Comment by mhegazy** [comment] 2017-09-21 18:11
thanks. closing as duplicate of https://github.com/Microsoft/TypeScript/issues/18328

**Closed by mhegazy** 2017-09-21 18:11 UTC
Labels: Bug, VS Code Tracked
