### ISSUE TITLE
Get return value type of a function

### ISSUE THREAD

**Issue by kube** [Microsoft/TypeScript#12229] opened 2016-11-14 20:41 UTC
I'm sorry to repost this here, (I originally posted on StackOverflow) but it seems that there's no way to do that.

Admit I have a function defined like this:

    const createPerson = () => ({ firstName: 'John', lastName: 'Doe' })

Would it be possible to get its return value type?

Something like this:

```ts
type Person = typeof createPerson()
```

****

## Example Scenario

I have a Redux container that maps state and dispatch actions to props of a component.

### containers/Counter.tsx

```ts
// ... Here I also define MappedState and mapStateToProps

// The interface I would like to remove
interface MappedDispatch {
  increment: () => any
}

// And get the return value type of this function
const mapDispatchToProps =
  (dispatch: Dispatch<State>): MappedDispatch => ({
    increment: () => dispatch(increment)
  })

// To export it here instead of MappedDispatch
export type MappedProps = MappedState & MappedDispatch
export default connect(mapStateToProps, mapDispatchToProps)(Counter)
```

### components/Counter.tsx

```ts
import { MappedProps } from 'containers/Counter'

export default (props: MappedProps) => (
  <div>
    <h1>Counter</h1>
    <p>{props.value}</p>
    <button onClick={props.increment}>+</button>
  </div>
)
```

Getting the return value type of `mapDispatchToProps` would permit in this case to remove code duplication by declaring an interface.

**Comment by mhegazy** [comment] 2016-11-14 20:54
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/6606

**Closed** 2017-04-21 16:58 UTC
Labels: Duplicate
