### ISSUE TITLE
Way to specify that type can't be null

### ISSUE THREAD

**Issue by Pajn** [Microsoft/TypeScript#14967] opened 2017-04-01 12:44 UTC
**TypeScript Version:**  2.2.1

**Code**

With the code
```ts
function filterMap<T, U>(data: Array<T>, fn: (element: T) => U): Array<U> {
  let newArray: Array<U> = []
  data.forEach(element => {
    let newElement = fn(element)
    if (newElement != null) {
      newArray.push(newElement)
    }
  })
  return newArray
}

let fruits = ['apple', 'banana', 'pear']
let filteredAndMapped = filterMap(fruits, e => e.startsWith('a') ? null : e.toUpperCase())
```
`filteredAndMapped` now have the type `Array<string | null>` but in reality only contain elements of type string.

It would be nice if it was possible to do a non-null assertion or similar for types, allowing me to write something similar to
```
function filterMap<T, U>(data: Array<T>, fn: (element: T) => U): Array<U!> {
  let newArray: Array<U!> = []
  // ...
```
so that `filteredAndMapped` and `newArray` have the type `Array<string>`.

**Comment by NN---** [comment] 2017-04-01 15:25
You can try  f<T extends {}>(x: Array<T>)

**Comment by aluanhaddad** [comment] 2017-04-01 22:43
@Pajn that is already supported
```ts
declare function filterMap<T, U>(data: Array<T>, fn: (element: T) => U | null): Array<U>;
```

**Comment by Pajn** [comment] 2017-04-02 20:28
@aluanhaddad 
That works if the types are inferred (which is great!) but if you explicitly pass a nullable type into U. It would be nice to be able to do that to. Especially as you must specify the type parameters when using a type in a type bound and thus can not rely on that trick inside a type.

**Comment by aluanhaddad** [comment] 2017-04-03 00:07
I'm not sure I follow you. When you say explicitley pass a nullable type for `U` do you mean
```ts
filterMap(fruits, e => null))
```
or
```ts
filterMap<string, string | null>(fruits, e => null))
```
If so, you can write overload such as
```ts
declare function filterMap<T, U extends null>(data: T[], fn: (element: T) => U): [never];
declare function filterMap<T, U>(data: T[], fn: (element: T) => U | null): U[];
```

**Comment by Pajn** [comment] 2017-11-29 10:52
I have wanted this a couple of times the last days with the use case of taking property from another type but requiring it.

Example
```
type A = {prop?: string}
type B = {prop: A['prop']} // type of B is {prop: string|undefined}
// I would like
type B = {prop: A['prop']!} // type of B is {prop: string}
```

**Comment by mhegazy** [comment] 2017-11-29 21:58
Duplicate of https://github.com/Microsoft/TypeScript/issues/14366

**Closed** 2018-01-02 18:42 UTC
Labels: Duplicate

**Comment by mhegazy** [comment] 2018-03-02 18:20
This should be possible now with `NonNullable<A["prop"]>`. see https://github.com/Microsoft/TypeScript/pull/21847
