### ISSUE TITLE
Breaking Change: Unexpected narrowing to never when "in" guard used on intersection

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#38162] opened 2020-04-24 17:25 UTC
**TypeScript Version:**  3.8.3 vs nightly

**Search Terms:** intersection in operator

**Code**

```ts
type MaybeFoo = {
    bar: string;
    foo?: number;
};
type AlwaysFoo = {
    foo: number | undefined;
    always: string;
};

declare const f: AlwaysFoo & MaybeFoo;
if ("foo" in f) {
    f.bar;
} else {
    // 3.8.3: f: AlwaysFoo & MaybeFoo
    // 3.9: 'f' is 'never'
    f.bar;
}
```

**Expected behavior:** Well...

This is probably technically the correct behavior. However, for the specific case of `window`, this is problematic. There are globals like `ontouchstart` which are declared as being `var ontouchstart: whatever | undefined` in the global scope; these get intersected with the global `Window` type, and because we believe "variables can't be optional", we start narrowing to `never` in the else branch here.

It's unclear what we should do differently here, but this caused a break in a few different places in real world code where people are doing feature detection. We're incorrectly telling people that e.g. `ontouchstart` is *always* present, *even though* you would get an error to unconditionally invoke it (because it is indeed possibly-`undefined`).

Since there's still no "optional var" and still no "missing vs undefined", we should maybe treat properties that include undefined as "possibly not `in`" for the purposes of narrowing.

**Actual behavior:** Described

**Playground Link:** [Link](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200423&ssl=1&ssc=1&pln=18&pc=1#code/C4TwDgpgBAsghiARhAYgezVAvFA3gKCiKkTgCcAuKAZ2DIEsA7AcwG5DiAzDAfisYCuAW2Rl2AX3ahIUAIIAbAO4Jq6TDgLEo3NP2GioAHygDGAEwicmEM+y1wlKqrQYsJ7fBYDG88tC9ojLTaVArKIKoYUABksAjIauz0nFAAFABEOulQTNoAlHgcRJwAdKRi+OJQEPLU0JrEAPSNUADMJQAcJa1UnKGOEWoxcUioGEVQzW0lAJxUAOSc8znUUPOMEABuEGTzE6XlEvhAA)

**Related Issues:** Possible root cause: #37106

**Comment by eramdam** [comment] 2020-05-19 03:54
@RyanCavanaugh We've been running into this issue with the following pattern

```typescript
interface A {
  type: 'A'
}
interface B {
  type: 'B'
}
type Combined = A & B;
```

Is it supposed to be a volontary breaking change or is it a regression? I haven't been able to figure this out by digging around the PRs/issues referenced in this thread 😅

**Comment by sandersn** [comment] 2020-07-17 17:37
See discussion at the fix; briefly, the minimal fix for this bug is the right one because the real fix for the whole feature is to introduce the `missing` type.

**Closed** 2020-07-30 21:58 UTC
Labels: Bug, Fix Available
