### ISSUE TITLE
Find all references on a Typescript class constructor returns no results.

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#8023] opened 2016-04-12 13:26 UTC
_From @jockjocko on April 12, 2016 9:39_

- VSCode Version: 0.10.15-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Create class and constructor.
2. Create a new instance of the newly created class
3. Shift + f12 or right click find all references

I would expect it to find all references of the class being constructed "new ExampleClass()".

_Copied from original issue: Microsoft/vscode#5185_

**Comment by egamma** [comment] 2016-04-12 13:26
Moving to TypeScript for investigation.

**Comment by RyanCavanaugh** [comment] 2016-04-12 17:48
@jockojocko can you please provide a code sample that demonstrates the problem? Thanks!

**Comment by basarat** [comment] 2016-04-13 05:44
> Find all references on a Typescript class constructor

I think he is trying it here: 

```ts
class Foo {
    constructor/* <= here */(){}
}
const foo = new Foo();
```
Indeed I get zero results :rose: 

> Note : References on the class name `Foo` work just fine :heart:

**Comment by DanielRosenwasser** [comment] 2016-04-13 05:56
If so, then it's a duplicate of #2114.

**Comment by RyanCavanaugh** [comment] 2016-04-13 17:33
I'm assuming that's what's going on. Please comment if that's not the case and we'll re-open. Thanks!

**Comment by jockjocko** [comment] 2016-04-13 18:33
Yes this is the same as #2114, thanks for the info.

**Closed** 2016-04-14 17:31 UTC
Labels: Duplicate
