### ISSUE TITLE
`F1 extends F2` in conditional typing for function doesn't work in certain cases.

### ISSUE THREAD

**Issue by shevchenkobn** [microsoft/TypeScript#50018] opened 2022-07-23 16:23 UTC
# Bug Report

### 🔎 Search Terms

function, extends, type inference, conditional typing, function type extends

### 🕗 Version & Regression Information

- This is the behaviour in every version I tried, and I reviewed the FAQ for entries about conditional function types with extends.

### ⏯ Playground Link

[Totally Self-sufficient Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/C4TwDgpgBACglpA8pATgQ2AexQHgJIB2ANFIgK7BQC8UhAfNVABRzATpYoBctbH2+AnQCU1Bnj4YB5YHQDcAKAWhIUAKIAPNgQAmAZxwAVEgCE0eiAxqGoELRF16oZi1AD8UYCjLQeAMzQAGwtFBT8yAgBjYDhMAigAWzQwQRIZOiYksFQeJgA3IJ8eQlEqBhlhHngkVClcQjSKBgBvBSh2qBQIYDIUePComLiAKigwBAgdAFlklklOYvmBelFWjvWoAHcACzhA6CYvH1W2jbPIuL1KZqgCwJ8SHTjoAF9GVnY6gDoCO2AmYSKM5nOB+ZhPX4nYHQqAAIy6aAA1kCYe0XqdUSA4BBAjpEslUPlChBARiNuj1i9FOiFAB6Wm0KARHTsK5oXSebYYTkQVwAJigmDy7ECmDQ+igaC6UD0ZFQfnumDIehIsIoUFYAHInAArZWUPzYOFdPKsECSjlYDWBe5XDjQBLmsCYOAEYBfKAAZQg0ENKElNsFwpQovFeh422AwDA4fpAHNWNsyLCvhcErS9NsIHlIlmCIjMLCCLTgHoALSRQLmcsfFBluxgWmw0Ww2lJK7sWm1r6lgDEABkAKwARjCEWisXi6AIcYgAJ4AHEHJ9ODgCGQErD2CR2SASMyIH5XZN5GPBpPOuzZ0wHDoeOvN+xKlAl79+LgH1uUDuCHumbpD2PHQ6DPCcRkvGc51vRgADkNy-L4pgAQQADQAfU9JCADE1DQvAYMMNQFzUAAlZ9XxXARP23C0-wPI9fmAqA1igP1mH2Sg4EYAAGOQNSgHBbF0PiuIAahoYcoQ6LEcTxOAUXRGl6SgLCjUwYAs39IURTFCULAgCMoxjLh40TZNU0wdNM2zXMHALIsS3LStqzLWt6w0Rtm0LNtzD4Ls+B7PQB2HAB2biFBZZzpQGMD+jgFArkQFAABFDzQMhAmAIwMguG0IFixZKNwQw6BIMAuh0OBIgwCA3FyO4iigQxSgYWFMEwfZ2WfGwAB9-xZBjJlCGKhniKUUBIq852faiUAAbQAXWYskuh6PooDm7iSGHEg+RIABmBbqSUEaL1redeCKtd4PYFoVu6Xp4huX4tFyFrmBuCEDM8bwIBIBrvvooCoBeYRFKUDioDQnhNG0fQcABMQZS8V04xIIl7m+2b3rtVGrB+nxQguAgrnxbJJiqCZkCu3cSFxmd8ayJhPRRmdSUhtgrm4mH7EcHAVAgTAwSySAdBIaoIGp98cFp-9EQITBNiEfGjggRQOd5YBhx5uGDAFoWyfFqnalXWWInlxXlcYAJgjVhQNauPkddvPXwEFsFxsmyCjZqGnf33fMFaVuh8ZtkI6QZQw3doAg-HYBxImgNQUBQbAAEJ7e6TxNf252+f1sFp1nH3JZNgQzcDy2Q+toJw+UqPVEIOOuiiJOU-TzPKE54AABY8-hgvWPixKUrSjLgBLqW6hl-25aDq2aDDtWgA)

_If you want more context_: I noticed it while trying to think of improvement to [iterare](https://www.npmjs.com/package/iterare) library. All my experiments can be found at my [repo](https://github.com/shevchenkobn/ts-class-iter-exp/blob/master/main-pipe.ts#L24).

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
type PipeOperator<In, Out = In> = (iterator: Iterator<In>) => Iterator<Out>;

type Extends<T, Base> = T extends Base ? true : false;

function map<In, Out>(mapper: (value: In) => Out): PipeOperator<In, Out> {
    return function* pipedMap(iterator: Iterator<In>) {
        while (true) {
            const { value, done } = iterator.next();
            if (done) {
                break;
            }
            yield mapper(value);
        }
    };
}

// I understand that these 2 overloads are superfluous, but it's just for brevity and to illustrate my point. See for all overloads: https://github.com/shevchenkobn/ts-class-iter-exp/blob/master/iter.ts#L51
function range(): Generator<number, any, undefined>;
function range(end: number): Generator<number, any, undefined>
function* range(end = Number.MAX_SAFE_INTEGER): Generator<number, any, undefined> {
  for (let i = 0; i < end; i += 1) {
    yield i;
  }
}

// For other overloads see: https://github.com/shevchenkobn/ts-class-iter-exp/blob/master/iter.ts#L170
declare function firstOrDefault<T>(collection: Iterator<T>, predicate?: (value: T) => boolean): T | undefined;

function arrRange(): number[] {
    return [0, 1, 2, 3];
}

function iter(): Iterator<number> {
    return { next: () => ({ done: true, value: undefined })}
}

let _: Extends<() => string, (value: number) => string> = true;

const mapped: PipeOperator<any, string> = map(String);
let test0: Extends<typeof mapped, PipeOperator<any, unknown>> = true;
let test1: Extends<typeof map, PipeOperator<any, unknown>> = false;
let test2: Extends<typeof arrRange, PipeOperator<any, unknown>> = false;
// Type Inference Error!
let test3: Extends<typeof range, PipeOperator<any, unknown>> = false;
// Type Inference Error!
let test4: Extends<typeof firstOrDefault, PipeOperator<any, unknown>> = false;
```

### 📔 Background

TypeScript has an outstanding tool `A extends B`, which allows checking if `A` can be considered a subtype of `B`.

Let's say there is an expression `F1 extends F2`, where `F1` and `F2` are function definitions (regardless, if they are inline, `type` or `interface`).

For simplicity let's ignore rest parameters and any non-function properties on `F1` and `F2`. Also, for type matching let's consider optional and default parameters as required, but with type `T | undefined`, where `T` - original type of a certain optional or default parameter.

Several steps are followed (algorithm exit with **result is in bold**):
1. The minimum arity of all `F1`'s overloads is less than or equal to the minimum arity of all `F2`'overloads, **otherwise `F1` doesn't extend `F2`**.
2. Create an array `matches` of type `Set<F1Overload>` of size _n_, where _n_ - maximum arity of `F1`, `F1Overload` - overload of `F1` of arity _n_. Initialize the `matches` with empty sets.
3. For all arities _n_ of each overload of `F1` create a union `cartesianProduct` of [Cartesian products](https://en.wikipedia.org/wiki/Cartesian_product) of all overloads with arity _n_ of `F1` with/vs all overloads with arity _n_ of `F2`.
4. For each pair `[F1Overload, F2Overload]` from `cartesianProduct`, where `F1Overload` - an overload of `F1`, `F2Overload` - an overload of `F2`, `n` - arity of both overloads, do:
    1. `ReturnType<F1Overload> extends ReturnType<F2Overload>` (covariant).
    2. For each _i-th_ inferred parameter with type `A1` of `F1Overload` and corresponding _i-th_ parameter with type `A2` of `F2Overload` do:
        - `A2 extends A1` (contrvariant).
    3. `matches[n].add(F1Overload)`
5. If `matches` contains any empty sets, **`F1` doesn't extend `F2`**.
6. **`F1` extend `F2` with `matches` being an array of `F1`'s overloads, which actually extend all `F2`'s overloads.**

I am not sure, but it seem that current implementation doesn't consider `matches`. Probably, after checking with `F1 extends F2`, the `F1` must be transformed into `F1_`, which would consist _only_ of all overloads inside `matches`.

### 🙁 Actual behavior

The example on TypeScript playground has type errors because:
1. `typeof range extends PipeOperator<any, unknown>` shouldn't work because the `range`'s overload with one parameter doesn't have `Iterator` as its first parameter. However, it works, simply because there is an overload with zero arity. This will definitely fail at runtime.
2. `typeof firstOrDefault extends PipeOperator<any, unknown>` shouldn't work because the return value of `firstOrDefault` is not `Iterator`.

### 🙂 Expected behavior

The example on TypeScript playground shouldn't have type errors.

**Comment by RyanCavanaugh** [comment] 2022-07-28 15:46
This appears to be a duplicate of #598

**Comment by shevchenkobn** [comment] 2022-07-29 07:52
Yes, but I tried to create an algorithm of resolving the correct overloads in "Background". Should I post it to #598?

**Comment by shevchenkobn** [comment] 2022-07-30 11:17
@RyanCavanaugh I have mentioned my suggestion in #598, so you can close this issue if you need to.

**Closed** 2022-08-01 18:00 UTC
Labels: Duplicate
