### ISSUE TITLE
After upgrading from v4.2 to v4.3, same code reports [2589]

### ISSUE THREAD

**Issue by zhaoyao91** [microsoft/TypeScript#44787] opened 2021-06-28 11:16 UTC
# Bug Report

### 🔎 Search Terms

v4.3.4 2589

### 🕗 Version & Regression Information

- This changed between versions v4.2.3 and 4.3.4

### ⏯ Playground Link

- [work, at v4.2.3](https://www.typescriptlang.org/play?ts=4.2.3#code/C4TwDgpgBAogdgZwK4CcIB4AaAaKBNAPigF4pMoIAPYCOAEwXygH4yoAuKOCANwhQDcAWABQoSFADKAQwBmEANIQQ6ACpFSqitVoMoCYCgCWcAOZQAPlyQBbAEb8WUAAYASAN6qAvs45de-MJi4NAy8gBq0gA2SBgA8rgKGlAK2jT0jADWygD2slBxTnEA2goAun7cfIKiolRgOSjAUOLQAArSwAAWCOgJUG0kUABEw8mFVOl6OXYAVhAAxsCiUE7uK6ubpVAmUNkgeQVl7Bubm1YAFIOTuoyjTqmcbu5hisrobQReAHQer0oqJI+ACUpzOlgGnR6fVKZVw1x0GRGwwefme-3enx+fzkb0BX2cBCCZy8xX2hziZQ2nCqgVqInqjWarSgAHEIMA+vC0rdId1enECMkEVNGM8TPIUGRse4JY5MJIfBtWOzOa9IjF4rhMARcPBkGgsJJ4VDeurorEuWQhULqVJcRrLf1PkEgA)
- [not work,at v4.3.4](https://www.typescriptlang.org/play?ts=4.3.4#code/C4TwDgpgBAogdgZwK4CcIB4AaAaKBNAPigF4pMoIAPYCOAEwXygH4yoAuKOCANwhQDcAWABQoSFADKAQwBmEANIQQ6ACpFSqitVoMoCYCgCWcAOZQAPlyQBbAEb8WUAAYASAN6qAvs45de-MJi4NAy8gBq0gA2SBgA8rgKGlAK2jT0jADWygD2slBxTnEA2goAun7cfIKiolRgOSjAUOLQAArSwAAWCOgJUG0kUABEw8mFVOl6OXYAVhAAxsCiUE7uK6ubpVAmUNkgeQVl7Bubm1YAFIOTuoyjTqmcbu5hisrobQReAHQer0oqJI+ACUpzOlgGnR6fVKZVw1x0GRGwwefme-3enx+fzkb0BX2cBCCZy8xX2hziZQ2nCqgVqInqjWarSgAHEIMA+vC0rdId1enECMkEVNGM8TPIUGRse4JY5MJIfBtWOzOa9IjF4rhMARcPBkGgsJJ4VDeurorEuWQhULqVJcRrLf1PkEgA)

### 💻 Code

```ts
type Ensure<X, Y> = X extends Y ? X : never;
type SafeKey<T> = T extends string | number ? `${T}` : never;
type SafeValue<O, K> = K extends keyof O ? O[K] : never;

export type Paths<O, P = ""> = O extends object
  ? {
      [K in keyof O]:
        | (P extends "" ? K : `${SafeKey<P>}.${SafeKey<K>}`)
        | Paths<O[K], P extends "" ? K : `${SafeKey<P>}.${SafeKey<K>}`>;
    }[keyof O]
  : never;

export type Get<O, P extends Paths<O>> = P extends `${infer X}.${infer XS}`
  ? Get<SafeValue<O, X>, Ensure<XS, Paths<SafeValue<O, X>>>>
  : SafeValue<O, P>;
```

### 🙁 Actual behavior

line 14 errored: `Type instantiation is excessively deep and possibly infinite.(2589)`

### 🙂 Expected behavior

all work

**Comment by andrewbranch** [comment] 2021-06-28 19:48
Duplicate of https://github.com/microsoft/TypeScript/issues/43877

**Closed** 2021-07-01 18:00 UTC
Labels: Duplicate
