### ISSUE TITLE
Generic argument is being narrowed to {}

### ISSUE THREAD

**Issue by asvetliakov** [Microsoft/TypeScript#16028] opened 2017-05-23 15:34 UTC
**TypeScript Version:**  2.3.3 / nightly (2.4.0-dev.20170523)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
interface TestProp<T> {
    a: number;
    b: T;
}

declare function TestC<T>(props: TestProp<T>): void;
declare function TestW<Props>(comp: (props: Props) => void): Props;

const p = TestW(TestC);
```

**Expected behavior:**
```p``` is type ```TestProp<any>``` or ```TestProp<{}>```

**Actual behavior:**
```p``` is type ```{}```

**Comment by mhegazy** [comment] 2017-05-23 17:41
Duplicate of https://github.com/Microsoft/TypeScript/issues/9366

**Comment by mhegazy** [comment] 2017-06-07 16:31
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-06-07 16:31 UTC
Labels: Duplicate
