### ISSUE TITLE
Tsconfig show typescript file not found error after moving it to another directory or delete it.

### ISSUE THREAD

**Issue by kimlimjustin** [microsoft/TypeScript#43838] opened 2021-04-24 10:18 UTC
Issue Type: <b>Bug</b>

When I move a typescript file from a directory into another directory or delete the file from vscode, it shows a problem in `tsconfig.json` file:

```
File '/home/justin/Projects/dochub/src/menu.ts' not found.
The file is in the program because:
Matched by include pattern '**/* ' in '/home/justin/Projects/dochub/tsconfig.json' ts [1, 1]
```

I mean, yeah of course it's not found because I moved it into another directory.

Reopening vscode will solve this, but it is annoying ... Hope this will be fixed soon :)

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:02.931Z)
OS version: Linux x64 5.11.0-16-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx (4 x 545)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 3, 3|
|Memory (System)|14.66GB (0.16GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id faba7d7b-2fa9-4f50-9547-77949d63445b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.4.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
cpptools|ms-|1.3.1
es6-css-minify|olb|3.3.2
material-icon-theme|PKi|4.6.0
LiveServer|rit|5.6.1
material-theme|zhu|3.10.13

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by mjbvz** [comment] 2021-04-26 23:22
Please share your tsconfig and a overview of your project structure

**Comment by kimlimjustin** [comment] 2021-04-27 06:45
It's an electron project, structure:

```
...
├── node_modules
├── src                          # Source code
│   ├── config                 
│           ├── theme.json
│   ├── drives.ts
│   ├── main.ts
│   ├── preload.js
│   ├── theme.js
├── package-lock.json
├── package.json
├── README.md
└── tsconfig.json
```

My [tsconfig.json](https://github.com/kimlimjustin/xplorer/blob/master/tsconfig.json) file is generated by `tsc --init` command.

**Comment by kimlimjustin** [comment] 2021-05-12 13:20
You can repro this bug by these steps:
1. Clone the [`electron-quick-start`](https://github.com/electron/electron-quick-start)
2. Change `main.js` to `main.ts`
3. Edit the `main` value on `package.json` to `main.ts` 
4. Create a new file called `hello.ts`
    Code for `hello.ts`:
    ```
    const Hello = () => {
       return "Hello World"
    }
    
    module.exports = Hello
    ```
5.  Inside the `preload.js` file add these line:
    ```
    const hello = require('./test/hello.ts')
    hello()
    ```
6. Create a new folder called `test`, move `hello.ts` into the folder, update import on the `preload.js` file
7. Problem occurs

[tsserver.log](https://github.com/microsoft/TypeScript/files/6466405/tsserver.log)
[ti-66130.log](https://github.com/microsoft/TypeScript/files/6466409/ti-66130.log)

**Comment by anandvc** [comment] 2021-06-23 17:10
Following. 
I had a similar issue come up after duplicating a .tsx file and then renaming the copy.

**Comment by Ark-kun** [comment] 2021-06-25 19:37
I always have this error when moving **unused** `*.ts` files to another folder or deleting them.
```
TypeScript error in undefined(undefined,undefined):
File '<path>/pipeline-editor/src/DragNDrop/Sidebar copy.tsx' not found.
  The file is in the program because:
    Matched by include pattern 'src' in '<path>\pipeline-editor\tsconfig.json'  TS6053
```

I have to kill and re-run `npm start` to make it work again

**Comment by LuisAlejandro** [comment] 2021-06-29 15:21
The same hapening to me here.

**Comment by alirezaghey** [comment] 2021-07-04 00:20
I'm also having the same problem.
The general steps I took is as follows:
1- Setup a project with `npx create-react-app . --template typescript`
2- Setup `tailwindcss`
3- Delete some boilerplate files, including `App.test.tsx`, which was the source of the error.
4- ‍`tsconfig.json` shows an error stating that:
```
File '%PROJECT_ROOT/src/App.test.tsx' not found.
  The file is in the program because:
    Matched by include pattern 'src' in '%PROJECT_ROOT/tsconfig.json'ts
```
My first guess was that it may have something to do with the changes not being committed, but git commit didn't help.
Then I simply closed and reopened vs code and everything was fine.
It seems that vs code is referring to some stale cache.
I'm on an Ubuntu focal with vs code 1.57.1

I can try to reproduce the error and give more detailed steps if it helps. Although it may heavily depend on context and difficult to reproduce.

**Comment by Dr4kk0nnys** [comment] 2021-07-07 21:16
It just happened to me, when I decided to switch from relative imports ( '../../../' ) to normal imports ( import { strategy } from 'utils/strategies' ), my tsconfig:

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "target": "esnext",
        "noImplicitAny": true,
        "moduleResolution": "node",
        "outDir": "dist",
        "baseUrl": "src"
    },
    "include": [ "src" ]
}
```


The error after I changed 'src/utils/handleIsValidStrategy' to 'src/utils/handleStrategy'
```
File '/home/.../src/utils/strategies/handleIsValidStrategy.ts' not found.
The file is in the program because:
Matched by include pattern 'src' in 'home/.../myProject/tsconfig.json'
```

**Comment by koltday** [comment] 2021-07-14 00:32
Good to know I'm not alone! Thought this was a problem with CRA-TypeScript. I did find (someone else's solution which I scoured upon) that deleting node-modules and then running "yarn" or "npm install" to reinstall them will fix it. A huge pain though, especially with large projects on a slower/older computer..

**Comment by kimlimjustin** [comment] 2021-07-14 00:37
> Good to know I'm not alone! Thought this was a problem with CRA-TypeScript. I did find (someone else's solution which I scoured upon) that deleting node-modules and then running "yarn" or "npm install" to reinstall them will fix it. A huge pain though, especially with large projects on a slower/older computer..

Actually reopening vscode will fix this, but it's really really annoying tho, that's why I opened this issue.

**Comment by koltday** [comment] 2021-07-14 00:45
> > Good to know I'm not alone! Thought this was a problem with CRA-TypeScript. I did find (someone else's solution which I scoured upon) that deleting node-modules and then running "yarn" or "npm install" to reinstall them will fix it. A huge pain though, especially with large projects on a slower/older computer..
> 
> Actually reopening vscode will fix this, but it's really really annoying tho, that's why I opened this issue.

aaaaa oh no, my mistake. I should I have read a bit closer. Went a little blind with annoyance from thinking I had to reinstall the project again :smile:  Thanks for the heads up, though, that's really helpful to know

**Comment by lucasbasquerotto** [comment] 2021-07-16 15:32
I was able to avoid this issue by restarting the typescript server (in vscode: `Ctrl+Shit+p` -> `Typescript: Restart TS Server`). I would prefer a proper solution tough.

**Comment by stanleyowen** [comment] 2021-09-10 09:38
> I was able to avoid this issue by restarting the typescript server (in vscode: `Ctrl+Shit+p` -> `Typescript: Restart TS Server`). I would prefer a proper solution tough.

Thanks! This method works for me, however I hope this issue could be fixed asap (this issue has been opened for 5 months) since it's really annoying, especially for the early dev. I've been spending around 2 hours and finally found this issue though. Thanks!

**Comment by sahin52** [comment] 2021-09-10 16:41
Renaming a file causes the same problem too, I need to restart it, which takes nearly a minute, so pretty annoying

**Comment by sahin52** [comment] 2021-09-12 09:59
I have a small **solution** (just to not need ```npm start``` again):   
- go to tsconfig.json
- delete "src" string in "include" array and save
- undo and save (get back to normal state, "src" string must come back)
- in your project's src directory, save any file. It will compile succesfully

But still, if you are working on vscode, the tsconfig.json file will show error, which is just distracting

**Comment by ecorona** [comment] 2021-09-14 13:56
> I was able to avoid this issue by restarting the typescript server (in vscode: `Ctrl+Shit+p` -> `Typescript: Restart TS Server`). I would prefer a proper solution tough.

I can live with this as this problem only pops once in a while.

**Comment by igorer88** [comment] 2021-09-18 01:53
It happens to me too. :disappointed:

**Comment by fperaltalitebox** [comment] 2021-09-20 15:27
Same here :(

**Comment by arnav7633** [comment] 2021-09-26 04:37
Same here ;(

**Comment by bviala** [comment] 2021-09-27 01:42
bump

**Comment by mkmladja** [comment] 2021-09-30 11:01
Another one...

**Comment by adobrov-arcadia** [comment] 2021-09-30 22:15
Pretty annoying, yeah...

**Comment by Mazata** [comment] 2021-10-11 11:59
Same here, bump bump bump

**Comment by Mazata** [comment] 2021-10-11 12:02
> I have a small **solution** (just to not need `npm start` again):
> 
> * go to tsconfig.json
> * delete "src" string in "include" array and save
> * undo and save (get back to normal state, "src" string must come back)
> * in your project's src directory, save any file. It will compile succesfully
> 
> But still, if you are working on vscode, the tsconfig.json file will show error, which is just distracting

Do you have to do this everytime you rename/move/delete a file or does this solution carry some longevity?

**Comment by kimlimjustin** [comment] 2021-11-06 07:04
I'm not sure why but this does not occur with stable reproducible steps anymore, I mean, using the latest version, the reproducible steps I wrote there months ago do not reproduce again. However, this issue still remains an issue cuz I sometimes got into this problem when working hard on my code (I usually just restart the TS server to make it works), but I got no idea about the reproducible steps. Maybe others?

**Comment by nichitaa** [comment] 2021-11-12 07:15
bump

**Comment by thanosades** [comment] 2021-11-16 21:05
Happened to me all day and Google gave me this thread. I'm so sad this has no solution other than "edit ts.config.json and undo" someone above posted.

**Comment by r4hulp** [comment] 2021-11-18 07:11
Happening to me as well whenever I delete/move/rename files... The temporary solution is to restart TS server but it is not a feasible solution.

**Comment by Chasen-Zhang** [comment] 2021-11-24 02:05
restart vscode

**Comment by kimlimjustin** [comment] 2021-11-24 02:17
> restart vscode

Restart vscode is just a stupid action, especially you got multiple tasks running. The `TypeScript: Restart TS Server` is a better solution although it's not a perfect solution, fixing the problem from the core would be much better, cuz you know, restarting the TS server needs some seconds (sometimes minutes) to get it restarted.

**Comment by arnav7633** [comment] 2021-11-24 06:22
For me it was just the ts server being extremely slow, you can run `tsc --extendedDiagnostics` to diagnose this. Personally mongoose was the package causing this issue. Got rid of it and voila

**Comment by kimlimjustin** [comment] 2021-11-24 09:12
> Personally mongoose was the package causing this issue. Got rid of it and voila

I don't have mongoose in my project and this issue sometimes occur when I operate large operation (ex: switching branch with different project dependencies and different structure , usually when switching to refactoring branch), hence I can't really write a reproducable steps as its quite impossible to test the large operation.

**Comment by ArtyomSevyan** [comment] 2021-12-22 07:02
We've encountered this error, while deleting files or moving branches (React project). Imports also haven't worked in newly-created files (Had to restart TS server).
```
Failed to compile.

undefined
TypeScript error in undefined(undefined,undefined):
```
Changing  `"include": ["src"]` to  `"include": ["src/**/*"]` in tsconfig.json helped. No errors so far.

**Comment by feliciakri** [comment] 2021-12-29 07:33
I encountered the same problem after renaming files and folders. Restarting TS Server mentioned by lucasbasquerotto worked for me

**Comment by q7y331xk** [comment] 2022-01-15 16:23
I think I found a easy solution. just make some change in tsconfig.json and return the change.
In my case
"baseUrl" : "./", -> "."      <- solved here but I want to return it
"baseUrl" : "./"

**Comment by jespadas** [comment] 2022-01-16 13:26
> I was able to avoid this issue by restarting the typescript server (in vscode: `Ctrl+Shit+p` -> `Typescript: Restart TS Server`). I would prefer a proper solution tough.


This worked for me. Thanks a lot !!

**Comment by SHAgility** [comment] 2022-02-17 18:23
Bump

**Comment by OswalDev** [comment] 2022-04-08 03:36
> I was able to avoid this issue by restarting the typescript server (in vscode: `Ctrl+Shit+p` -> `Typescript: Restart TS Server`). I would prefer a proper solution tough.

This worked perfectly for me, thank you

**Comment by PiyushDuggal-source** [comment] 2022-04-23 06:27
Hey, Just add `"include" : ["**/*"]` after "compilerOptions"

**Comment by JRRS1982** [comment] 2022-05-17 18:54
> Hey, Just add `"include" : ["**/*"]` after "compilerOptions", it works fine for me :)

The default is ** so I think this wouldn't really do anything.

**Comment by alanvitalp** [comment] 2022-07-18 14:02
I think the proper way to solve this, is trying to change tsconfig.json by putting `"include": ["src/**/*.ts(x)"]`

**Comment by mkaulfers** [comment] 2022-08-14 01:40
I just had this issue come up. I was able to resolve it by `Shift+Ctrl+P > Restart TS Server > adding a dummy function` then `rollup` and it was resolved. I removed the dummy function and now it's working.

**Comment by seerviashish** [comment] 2022-08-20 18:24
> > Good to know I'm not alone! Thought this was a problem with CRA-TypeScript. I did find (someone else's solution which I scoured upon) that deleting node-modules and then running "yarn" or "npm install" to reinstall them will fix it. A huge pain though, especially with large projects on a slower/older computer..
> 
> Actually reopening vscode will fix this, but it's really really annoying tho, that's why I opened this issue.

This one worked

**Comment by aminsoraya** [comment] 2022-09-07 09:47
I have this structure : components/Login/index.tsx
How do I handle Error in tsconfig.json file?

**Comment by Luxcium** [comment] 2022-12-01 14:29
For the moment I have changed my keybindings (using VS Code) and I think I will be using them often so I will probably change them again... 

![Screenshot_000001_20221201_092230](https://user-images.githubusercontent.com/42672814/205078271-8ea47cb1-2be1-421d-9750-f35860fa0d44.png)


It remaps some default keybindings, You probably need something similar depending on your workflow...

**Comment by khaled-300** [comment] 2022-12-15 21:08
I had the same issue, due to change of version in ts i had the latest version before and for the need in other project of mine i had to downgrade to typescript@4.4.2 and the issue started to happen.
It got resolved simply by same way **`Shift+Ctrl+P > Restart TS Server`**

**Comment by DanielRosenwasser** [comment] 2022-12-16 23:37
It sounds a whole lot like [TypeScript 4.8's file-watching fixes](https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#file-watching-fixes) and [TypeScript 4.9's usage of file system events](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#file-watching-changes) should alleviate this issue. These fixes typically targeted Unix-like systems (including Linux and macOS) so I'm curious to hear if anyone is experiencing this with the latest version of TS.

**Comment by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [comment] 2022-12-21 11:37
@DanielRosenwasser Still happens with 4.9.4 (with "using workspace version").

**Comment by WarrenWongCodes** [comment] 2022-12-23 17:12
Tried all different options and hasn't worked:

- Restarting TS Server
- Restarting VSCode
- Adding different src variations to `tsconfig.json`

Not sure what I am doing wrong here...

**Comment by renweibo** [comment] 2022-12-28 12:38
遇到同样的问题，@WarrenWongCodes的思路临时可以解决，不过总是很烦人的小问题

Same issue here, annoying even with workaround from @WarrenWongCodes

**Comment by mgolden6** [comment] 2022-12-29 17:44
The following is super quick and worked for me (I'm running an expo project):

1. Open `tsconfig.json`
2. Change `"strict":` from `true` to `false`
3. save the file (error goes away)
4. Change `"strict:` back to `true` and save
5. Move on with your life

example tsconfig.json below:
```
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true  // This is where you (2) change strict from TRUE to FALSE, (3) save, (4) change it back to true and save
  }
}
```

**Comment by gabriel-cheng** [comment] 2023-01-16 05:55
this is usually an import error. Make sure the module is being imported correctly!

**Comment by daniel-bergmann** [comment] 2023-02-06 16:21
had the same error, all i had to do was restart the dev server

**Comment by aguschapuis** [comment] 2023-02-07 14:39
I had the same issue because i had a file duplicated. Remove it and thats it!

**Comment by Tagaca19e** [comment] 2023-02-20 04:19
Had the same issue, but I got it to get away by reloading my Developer Window on VS Code 🙌

**Comment by jpausa** [comment] 2023-03-21 20:28
Had the same issue, hope it can be solved soon. In the meantime restarting VSCode solves the issue

**Comment by slacle** [comment] 2023-04-06 04:10
>
2 years later still happening. When changing the file name. Restarting TS Server fixed it.

**Comment by virtuallyunknown** [comment] 2023-05-18 19:39
Keep in mind that if you restart VSCode, you lose your undo/redo history, so for that reason it's probably better to restart just the TS server instead.

Either way, on the scale of annoyance this is probably a 1/10, but would love to see this fixed eventually.

**Comment by Sharjeel-22** [comment] 2023-06-03 22:59
> "include" : ["**/*"]

thanks its working for me :)

**Comment by wpyoga** [comment] 2023-06-18 15:15
@alanvitalp 's solution:
> I think the proper way to solve this, is trying to change tsconfig.json by putting `"include": ["src/**/*.ts(x)"]`
Doesn't work for me. I'm on TypeScript 5.1.3 .

@PiyushDuggal-source 's solution:
> Hey, Just add `"include" : ["**/*"]` after "compilerOptions", it works fine for me :)
Doesn't work for me either.

**Comment by linonetwo** [comment] 2023-06-25 10:25
```jsonc
{
  "extends": "../../tsconfig.json",
  "include" : ["./src/**/*"],
  "compilerOptions": {
    "rootDir": "./src"
  }
}
```

works for me.

https://github.com/SukkaW/rollup-plugin-swc/issues/35#issuecomment-1606014182

**Comment by slince-zero** [comment] 2023-08-03 02:35
> > I was able to avoid this issue by restarting the typescript server (in vscode: `Ctrl+Shit+p` -> `Typescript: Restart TS Server`). I would prefer a proper solution tough.
> 
> Thanks! This method works for me, however I hope this issue could be fixed asap (this issue has been opened for 5 months) since it's really annoying, especially for the early dev. I've been spending around 2 hours and finally found this issue though. Thanks!

Thanks, I've been troubled by this question for a long time, it's useful

**Comment by matjaeck** [comment] 2023-09-07 11:21
Should be put on Backlog milestone. Assigning the OP was a good joke but now lets be honest, this is not making it into 5.3.0. I'm glad to be proven wrong, but so far DX seems to be one of the lowest priorities.

**Comment by Revan99** [comment] 2023-10-04 07:59
> I was able to avoid this issue by restarting the typescript server (in vscode: `Ctrl+Shift+p` -> `Typescript: Restart TS Server`). I would prefer a proper solution tough.

this solved for me

**Comment by mohamedsaleh1984** [comment] 2023-11-10 17:19
It's very crazy, I have a lot to finish and I can continue like this.
It's crazy. Is there any solution ??

**Comment by Leonelmarianog** [comment] 2023-12-29 13:43
I'm experiencing this error only in WSL2. It may not be related, but VSCode also seems unable to automatically fix imports of files that were renamed or moved if you are using TS path aliases. If you are not using path aliases the `updateImportsOnFileMove` seems to work ok but the error in `tsconfig.json` still shows up, but in this case is more an annoyance than a problem. On Windows 10 or Ubuntu as main SO these errors don't show up at all.

Main SO: Windows 10
Development SO: Ubuntu 22.04.3 LTS (WSL2)

Test cases:

1. If I'm using WSL but not using TS path aliases, this error pops up and VSCode prompts me to automatically fix import paths. Accepting the changes makes VSCode automatically fix the imports to reflect my changes.

2. If I'm using WSL and using TS path aliases, this errors pops up and VSCode doesn't prompt me to automatically fix import paths. Import paths remain broken.

3. If I use Windows 10 but not TS using path aliases, the error doesn't appear, and VSCode prompts me to automatically fix import paths. Accepting the changes makes VSCode automatically fix the imports to reflect my changes.

4. If I use Ubuntu 22.04.3 from another machine without TS path aliases, the error doesn't appear, and VSCode prompts me to automatically fix import paths. Accepting the changes makes VSCode automatically fix the imports to reflect my changes.

**Comment by artilishes** [comment] 2024-01-18 11:46
I solved by adding `"**/*"` to my tsconfig's include and setting up the excludes properly.
```
...
"include": [
    "next-env.d.ts",
    "next.config.js",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts",
    "./*.config.js",
    "**/*",
  ],
  "exclude": ["node_modules", "build"],
  ...
  ```

**Comment by navjotSingh2000** [comment] 2024-01-26 06:41
I fixed it by deleting the component's file that I was importing using `Finder`, then going back to the VS CODE and then creating that file again using `Finder`

**Comment by divmgl** [comment] 2024-01-27 11:19
The `**/*` fix or `src/**/*` does not work. Renaming a file will crash the TypeScript `--watch` server and require me to restart it:

```
[6:18:16 AM] File change detected. Starting incremental compilation...

error TS6053: File '/Users/dimiguel/dev/packages/app/src/posthog.ts' not found.
  The file is in the program because:
    Matched by include pattern '**/*' in '/Users/dimiguel/dev/packages/app/tsconfig.json'

  packages/app/tsconfig.json:13:15
    13   "include": ["**/*"],
                     ~~~~~~
    File is matched by include pattern specified here.

[6:18:19 AM] Found 1 error. Watching for file changes.
```

This is causing other issues, such as new files not being detected inside of a project. 

Would really appreciate a fix for this as I'm having to constant restart my TypeScript server for new files, file renames and deleted files.

**Comment by divmgl** [comment] 2024-01-27 11:41
Hey all, I found a temporary workaround that solves this problem. In your `tsconfig.json`:

```tsx
{
  "watchOptions": {
    "watchFile": "fixedpollinginterval" // or "dynamicPriorityPolling"
  }
}
```

This issue is happening because of the way TypeScript handles file system events. It's unfortunate, but with this method you no longer need to downgrade to version 4 and you'll no longer need to restart VSCode or your TypeScript tasks.

**Comment by Virtute90** [comment] 2024-01-31 10:28
I solved the problem with this modification (in linux environment):

`"include": ["src/**/*.ts", "src/js/**/*.tsx"]`

to 
`"include": ["./src/**/*.ts", "./src/js/**/*.tsx"]`

**Comment by ShahabDadKhan** [comment] 2024-02-06 04:58
> > Good to know I'm not alone! Thought this was a problem with CRA-TypeScript. I did find (someone else's solution which I scoured upon) that deleting node-modules and then running "yarn" or "npm install" to reinstall them will fix it. A huge pain though, especially with large projects on a slower/older computer..
> 
> Actually reopening vscode will fix this, but it's really really annoying tho, that's why I opened this issue.

It sucks man, I was looking for the solution then I was told just close your VS code and reopen it, it.s gone now.

**Comment by Prem-Dharshan** [comment] 2024-06-06 18:41
I had a similar issue

```
File 'd:/Tutorials/ProLeap/proleap-backend/src/users/entities/user0session.entity.ts' not found.
  The file is in the program because:
    Matched by default include pattern '**/*'ts
JSON schema for the TypeScript compiler's configuration file
```

This happened when I cancelled the popup by VSC which asked `refactor the imports?`. I simply ignored it and that resulted in this error.

`Solution`:
I re-created the file `user0session.entity.ts` and then deleted it correctly. The error was gone like magic.

Probably in your case, copy the contents and delete the config file. Re-create it with the same contents.

Hope this helps.

**Comment by danilofuchs** [comment] 2024-06-21 13:46
Enabling
`typescript.tsserver.experimental.useVsCodeWatcher: true` and `typescript.tsserver.experimental.enableProjectDiagnostics: true` at the same time causes this error.

**Comment by uphiago** [comment] 2024-06-26 21:38
We have several temporary solutions in this thread, but I haven't yet found a permanent one to my case. If i restart the TypeScript server in the IDE, the error disappears, we don't need to make any changes, as long as they were not related to really missing paths in the `"include"` of `tsconfig.json`

The same bug occurs when I move modules, change names, or create a new one.

Just **open** `tsconfig.json` and **save again**, **without making any updates**. It's probably a failure in the real-time update of the module's state, location, etc.

I'll look more deeply into it and if I find any permanent solutions to this specific bug, I will come back here to send updates.

**Comment by virtuallyunknown** [comment] 2024-06-26 23:53
Update to Typescript 5.5, it fixes this problem. The current version of VSCode ships with Typescript 5.4.5, however you can easily change it to use the "workspace" version, assuming you have installed latest Typescript in your project.

Open the command palette (`ctrl+shift+p`) -> `Typescript: Select Typescript Version`.

#58120 (I think).

**Comment by uphiago** [comment] 2024-06-27 08:56
We can just update it in VSCode, as @virtuallyunknown mentioned. This should fix the problem.

```
"devDependencies": {
    "typescript": "^5.5.2"
  }
```

![2024-06-27_09-53](https://github.com/microsoft/TypeScript/assets/129319177/d892c1f8-b279-4b1e-9f59-d9e004ac1d15)

**Comment by sheetalkamat** [comment] 2024-06-27 16:41
If you are still facing issues after updating to typescript@latest or typescript@next , please open new issue as this one is old and things have changed since then,. 

We need clear repro steps and tsserver log when you open the issue to be able to investigate it.
Thanks

**Closed by sheetalkamat** 2024-06-27 16:41 UTC
Labels: Bug, Needs More Info, Rescheduled

**Comment by velara3** [comment] 2024-08-05 16:08
This happened on 5.5.4. . Deleted a ts file in /src/routes/my.ts. Found this thread. Restarted TS server and now the message is gone. Will try to add a new issue if it happens again and steps to reproduce.

**Comment by Sanan4li** [comment] 2024-09-23 13:08
Not sure if this will help but another developer working on the same project created a folder `Activity` but we had all the pages with lowercase characters. After renaming `Activity` to `activity` it worked.

**Comment by DonnyVerduijn** [comment] 2024-11-04 00:09
For those looking for a workaround that actually does work. When using vscode, you can install the extension [https://marketplace.visualstudio.com/items?itemName=gabrielgrinberg.auto-run-command](https://marketplace.visualstudio.com/items?itemName=gabrielgrinberg.auto-run-command) 

Add this to .vscode/settings.json

```json
"auto-run-command.rules": [
  {
    "event": "onFileRename",
    "command": "typescript.restartTsServer"
  },
  {
    "event": "onFileDelete",
    "command": "typescript.restartTsServer"
  },
],
```

Relaunch window and you're done.

**Comment by rookbreezy** [comment] 2025-03-16 13:52
Adding to donverduyns clever workaround:

auto-run-command did not work for me but I found another extension that did: https://marketplace.visualstudio.com/items?itemName=appulate.filewatcher

Add another object for the `onFileRename` event if you need.

settings.json:

```json
"filewatcher.commands": [
    {
      "match": ".*\\.tsx?$",
      "event": "onFileDelete",
      "vscodeTask": "typescript.restartTsServer",
      "isAsync": true
    }
  ]
```
