### ISSUE TITLE
const enum compiler error

### ISSUE THREAD

**Issue by eile** [microsoft/TypeScript#32549] opened 2019-07-25 10:07 UTC
**Search Terms:** typing, enum

**Code**

```ts
const enum State {
  CLEAN,
  DIRTY,
  UPDATED
}

let state: State = State.DIRTY;
const update = () => {
  state = State.UPDATED;
};

for (let i = 0; i < 100; ++i) {
  switch (state) {
    case State.UPDATED:
      state = State.CLEAN;
      break;
    case State.CLEAN:
      state = State.DIRTY;
      break;
  }
}
```

**Expected behavior:** compiles cleanly

**Actual behavior:**
```
foo.ts:14:10 - error TS2678: Type 'State.UPDATED' is not comparable to type 'State.CLEAN | State.DIRTY'.

14     case State.UPDATED:
            ~~~~~~~~~~~~~


Found 2 errors.
```

**Playground Link:** https://www.typescriptlang.org/play/#code/MYewdgzgLgBApmArgWxgZSgQynGBvAKBhgGEAZAUQEEA5AGiJgBEBJAJQBUBNB4gVQAKTKhwpMCAXwIEANnFjRscAFzosOGAF41SgHStOXANwFQkWIgAOAEyVaYACgCUWgHz5Gijdox7Bw0SYTCRMCADMQACdHOVgAS3sABiMYBIAeGABGROSYAGo8uJdCYggAdzioYAALRy84YsZiYEwIXF8cXX8RMWUm4hh6+w64XXJqGhMBgYAjSLhMAGspgZa2nU7x2j7p0vVcH339dm4V6bmF5cYpKQIgA

**Related Issues:** n/a

**Comment by jcalz** [comment] 2019-07-25 15:54
duplicate of #9998

**Comment by RyanCavanaugh** [comment] 2019-07-25 17:13
@jcalz joining the club of people who have that issue number memorized

**Closed by RyanCavanaugh** 2019-07-25 17:13 UTC
Labels: Duplicate
