### ISSUE TITLE
Intellisense shows type `any` for inferred field in object.

### ISSUE THREAD

**Issue by osyrisrblx** [Microsoft/TypeScript#28277] opened 2018-11-01 05:43 UTC
**TypeScript Version:**  3.1.1

**Search Terms:**
intellisense any recursion 

**Code**

```TS
type Check<T> = (value: any) => value is T;
type Static<T> = T extends Check<infer U> ? U : never;
type Interface<T extends { [index: string]: Check<any> }> = Check<{ [P in keyof T]: Static<T[P]> }>;

type IPlayer = Static<
	Interface<{
		name: Check<string>;
		data: Interface<{
			score: Check<number>;
		}>;
	}>
>;
```

**Expected behavior:**
Hovering over `IPlayer` should show:
![image](https://user-images.githubusercontent.com/9200592/47834718-f7ea3180-dd76-11e8-8c40-6625ef4129cf.png)

**Actual behavior:**
Hovering over `IPlayer` shows the following:
![image](https://user-images.githubusercontent.com/9200592/47834677-ca9d8380-dd76-11e8-9cd6-dd85a05f8675.png)

**Playground Link:** 
[Playground Link](https://www.typescriptlang.org/play/#src=type%20Check%3CT%3E%20%3D%20(value%3A%20any)%20%3D%3E%20value%20is%20T%3B%0D%0Atype%20Static%3CT%3E%20%3D%20T%20extends%20Check%3Cinfer%20U%3E%20%3F%20U%20%3A%20never%3B%0D%0Atype%20Interface%3CT%20extends%20%7B%20%5Bindex%3A%20string%5D%3A%20Check%3Cany%3E%20%7D%3E%20%3D%20Check%3C%7B%20%5BP%20in%20keyof%20T%5D%3A%20Static%3CT%5BP%5D%3E%20%7D%3E%3B%0D%0A%0D%0Atype%20IPlayer%20%3D%20Static%3C%0D%0A%09Interface%3C%7B%0D%0A%09%09name%3A%20Check%3Cstring%3E%3B%0D%0A%09%09data%3A%20Interface%3C%7B%0D%0A%09%09%09score%3A%20Check%3Cnumber%3E%3B%0D%0A%09%09%7D%3E%3B%0D%0A%09%7D%3E%0D%0A%3E%3B%0D%0A%2F*%0D%0A%20%20%20%20type%20IPlayer%20%3D%20%7B%0D%0A%20%20%20%20%20%20%20%20name%3A%20string%3B%0D%0A%20%20%20%20%20%20%20%20data%3A%20any%3B%0D%0A%20%20%20%20%7D%0D%0A*%2F%0D%0A%0D%0Atype%20IPlayerData%20%3D%20IPlayer%5B%22data%22%5D%3B%0D%0A%2F*%0D%0A%20%20%20%20type%20IPlayerData%20%3D%20%7B%0D%0A%20%20%20%20%20%20%20%20score%3A%20number%3B%0D%0A%20%20%20%20%7D%0D%0A*%2F%0D%0A)

**Related Issues:** 
N/A

***

If I index the type further, it seems to resolve correctly.
```TS
type IPlayerData = IPlayer["data"];
```
Hover:
![image](https://user-images.githubusercontent.com/9200592/47834800-50b9ca00-dd77-11e8-9eef-b0a6ab39f4a1.png)

This issue also effects the intellisense when trying to index the object of that type.

Also, I'm not really sure what to title this issue. If anyone has a better phrase for what's going on here, I'm happy to edit the title.

**Comment by AnyhowStep** [comment] 2018-11-01 06:03
When you compile, does the emitted .d.ts file also show `any`?

**Comment by weswigham** [comment] 2018-11-01 18:18
`Interface` creates what we call within the compiler a "reverse mapped type". These types lazily compute their children. This is done to avoid blowing up when a type anonymously reverse maps itself (as there's nothing to name and reuse to terminate the circularity with). In declaration emit/node printing, we currently limit printing of these types to 1 level deep.

Duplicate of #23897 BTW - I'd chime in there.

**Closed** 2018-11-01 18:18 UTC
Labels: Duplicate
