### ISSUE TITLE
Generic constraint with index doesn't allow interface as type parameter

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#30359] opened 2019-03-13 12:34 UTC
**TypeScript Version:**  3.4.0-dev.20190313

**Search Terms:**

**Code**

```ts
interface Schema {
    users: {id: string};
}
declare function foo<T extends { [key: string]: { id: string } }>(): T;
foo<{users: {id: string}}>(); // ok
foo<Schema>(); // Type 'Schema' does not satisfy the constraint '{ [key: string]: { id: string; }; }'
foo<Pick<Schema, keyof Schema>>(); // ok

type Schema2 = {
    users: {id: string};
}
foo<Schema2>(); // ok
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by jack-williams** [comment] 2019-03-13 13:15
I think this is a duplicate of #15300

**Closed** 2019-03-28 18:00 UTC
Labels: Duplicate
