### ISSUE TITLE
Update language specification

### ISSUE THREAD

**Issue by avchugaev** [Microsoft/TypeScript#27903] opened 2018-10-15 08:08 UTC
Please update language specification. [Actual specification](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md) covers very old version **1.8**

**Comment by MartinJohns** [comment] 2018-10-15 10:36
Duplicate of all these: https://github.com/Microsoft/TypeScript/issues?q=is%3Aopen+is%3Aissue+label%3ASpec

And mainly: #15711. But given PRs like #20971 it's clear that there won't be any progress on this any time soon.

**Comment by weswigham** [comment] 2018-10-16 18:41
Duplicates #15711. Put your upvotes over there

**Closed by weswigham** 2018-10-16 18:41 UTC
Labels: Duplicate
