### ISSUE TITLE
Generic uses `any` instead of the default one when deconstructing an array

### ISSUE THREAD

**Issue by enisdenjo** [microsoft/TypeScript#35291] opened 2019-11-22 11:30 UTC
**TypeScript Version:**  3.8.0-dev.20191121

**Search Terms:**
generic uses any instead of the default one when deconstructing a tuple

**Code:**

```ts
// lib

interface SelectProps<T, K> {
  selector?: (obj: T) => K;
}

type SelectResult<T, K> = [K, T];

function select<T, K = T>(
  obj: T,
  props: SelectProps<T, K> = {},
): SelectResult<T, K> {
  // default selector just returns the same object
  const { selector = obj => obj } = props;
  return [selector(obj), obj];
}

// usage

interface Person {
  name: string;
  surname: string;
}

function selectJohn<K = Person>(props?: SelectProps<Person, K>) {
  const john: Person = {
    name: 'John',
    surname: 'Doe',
  };
  return select(john, props);
}

// 👍
//    vvvvvvvv => correct type `Person`
const [person] = selectJohn();

// 👎
//    vvvv => type `any`?
const [any, whatever] = selectJohn();

// 👍
const john = selectJohn();
//     vvvvvvvvvvv => correct type again `Person`
const [personAgain, nufinspecial] = john;
```

**Expected behavior:**
Deconstructing a tuple uses the default generic type.

**Actual behavior:**
Deconstructing a tuple infers `any` for when the default generic type should be used.

**Playground Link:** [check the repro out here](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191121&ssl=1&ssc=1&pln=44&pc=42#code/PTAEBsEsCMChcgOwC4FMBOAzAhgY1aAMqriq7IAK6A9gA4DOAPACoA0oA0gHygDesoUPRJlk1dAH4AXKAAU1aACsZzAJSgAvDw4BuWAF94yAJ60CxUuQBKqegFdwyFu26bQAbQ7tmAXT2xMO0RySGpEIRFyZ043Zi5ZAVAFZVA2RNoaBhkLUSo6JjZOHg0+fVZYVWzI5Bt7R2jXfkEQUAATVBwHZAjLMXRQWmx6YXpQRTt6bvRUZDt0RFHkAAsCemwAWwJk0UTcMMm+HtFxN2TNHjP9Nwz8vUFp2fmPYV7xeSVVdmS-A3gWiewAHNUPAkGgsHgCBQMPQwnxEogNqgZJN0EhAXchHNEZsUcg0YgMb8AkEQnCXqIAFLUJaIRgcNzQ9CwxDxG4MaREap5BiMJkslxcdRNUB7BbdRQ0xAyflwkoiwQ45GgADk1NpKvKgkE9nmSJkKoAItRUJrEvpMQ9sUdyLJJbT2Oz6Ko9IZYC1ALwbgFkd91gbUAN0DQcD51F4mm5FAJjMoAABrLELHYGKDu4zMywj43BTyOrELIXX8wB7AHI7vu1oGDoejBFj2EQxljEmT+267nrxnYAHcltg0P6MFmSjnkHmC-5PT6UxKpdnqmPCy0K8GVyGtGH0BHujXQEDsEg4wmk9OPOmWQBBQH7xDsRB2TBIehmXCQbDgIdjKU6IA)

**Related Issues:** Couldn't find any.

**Comment by RyanCavanaugh** [comment] 2019-11-22 21:48
There's a duplicate of this but I can't find it. Anyway, short repro:
```ts
declare function makeTuple<T1>(arg: T1): [T1];
declare function stringy<T = string>(arg?: T): T;

// isStringTuple: [string]
const isStringTuple = makeTuple(stringy());
// isAny: any (should be string)
const [isAny] = makeTuple(stringy());
```

@ahejlsberg I'm assuming the issue is that the contextual index signature candidate from the binding pattern is incorrectly being considered above the generic default

**Comment by jack-williams** [comment] 2019-11-28 00:14
@RyanCavanaugh this one? #30379

**Closed** 2019-12-05 15:09 UTC
Labels: Bug, Fix Available
