### ISSUE TITLE
String#matchAll should return iterable of RegExpExecArray instead of RegExpMatchArray

### ISSUE THREAD

**Issue by ZhangYiJiang** [microsoft/TypeScript#36788] opened 2020-02-13 21:33 UTC
**TypeScript Version:**  3.7 (issue is with lib typing) 

**Search Terms:** regex, matchall, es2020 

**Code**

```ts
const matches = Array.from('xxx'.matchAll(/x/g));
matches[0].index; // TS reports index may be undefined, when it should always be defined
```

Currently `matchAll` returns an iterable of `RegExpMatchArray`. However, the `index` and `input` properties on `RegExpMatchArray` are optional because `String#match` returns a match object without those if the regex has the global flag (https://github.com/microsoft/TypeScript/issues/35157).

`matchAll` on the other hand doesn't have the same behavior, so it should use `RegExpExecArray` where both of those properties are non-optional (or maybe create a `RegExpMatchAllArray` type) 

``` js 
> Array.from('xxx'.matchAll(/x/g)) 
[
  [ 'x', index: 0, input: 'xxx', groups: undefined ],
  [ 'x', index: 1, input: 'xxx', groups: undefined ],
  [ 'x', index: 2, input: 'xxx', groups: undefined ]
]
> Array.from('xxx'.matchAll(/a/g)) 
[]
> Array.from('aaa'.matchAll(/x/g)) 
[]
``` 

**Expected behavior:**

`input` and `index` on the match objects are not optional 

**Actual behavior:**

TS reports that `input` and `index` may be optional 

**Playground Link:** (Can't use playground since lib cannot be configured) 

**Related Issues:**  https://github.com/microsoft/TypeScript/pull/30936 introduced `String#matchAll`

**Comment by RyanCavanaugh** [comment] 2020-02-20 02:22
We don't have any mechanism for carrying around the flags of a RegExp, so the current definitions err on the side of making you assert that those properties will be there in cases where you know that the regexp is in fact global.

**Comment by ZhangYiJiang** [comment] 2020-02-20 03:07
I believe the global flag changing the return value only applies to `String#match`. All objects returned from `String#matchAll` will have the two properties, without any exceptions

**Comment by sholladay** [comment] 2020-05-24 04:50
A regex given to `.matchAll()` will _always_ be global. JavaScript throws an error if you attempt to pass it a non-global regex. Thus, unlike the return value of `.match()`, the return value of `.matchAll()` is always guaranteed to have `.index` and `.input`.

I think the types for `.match()` make sense given that TypeScript has a limited understanding of regex flags and `.match()` has a return type that is conditional on those flags, but the flags and limitations surrounding them are irrelevant to `.matchAll()`, as the only possible return value from `.matchAll()` is a type where `.index` and `.input` are _required_ (always present).

**Comment by clemyan** [comment] 2021-04-30 06:05
According to the [spec](https://tc39.es/ecma262/#sec-createregexpstringiterator), `String#matchAll` actually executes with the semantics of `RegExp#exec` instead of `String#match`. 

So, OP is correct, the return type of `String#matchAll` should be `IterableIterator<RegExpExecArray>`, not the current `IterableIterator<RegExpMatchArray>`.

**Comment by younesaassila** [comment] 2023-08-02 15:36
This is still an issue in 2023

**Comment by RyanCavanaugh** [comment] 2023-08-02 18:12
We still don't have a way to fix it!

**Comment by younesaassila** [comment] 2023-08-02 18:23
@RyanCavanaugh Sure, but why have you closed the issue? Just because "the mechanism isn't there" doesn't mean the problem is fixed

**Comment by clemyan** [comment] 2023-08-03 01:47
> We still don't have a way to fix it!

Untrue.

https://github.com/microsoft/TypeScript/blob/main/src/lib/es2020.string.d.ts#L9

Simply changing this line to

```typescript
    matchAll(regexp: RegExp): IterableIterator<RegExpExecArray>;
````

will fix this.

----

> According to the [spec](https://tc39.es/ecma262/#sec-createregexpstringiterator), `String#matchAll` actually executes with the semantics of `RegExp#exec` instead of `String#match`.
> 
> So, OP is correct, the return type of `String#matchAll` should be `IterableIterator<RegExpExecArray>`, not the current `IterableIterator<RegExpMatchArray>`.

**Comment by NilsIrl** [comment] 2023-08-25 13:21
Can this be re-opened? This was closed by mistake. This is actionable and was never blocked on there being a way to fix it (because there always has been).

**Comment by DanielRosenwasser** [comment] 2023-08-29 21:47
It seems like there was a misreading here - there has been a longstanding issue around typing `match`, but `matchAll` - while not being able to reject non-global regexps - will only function when given one, and can have its return type amended.

At least that's what we've gathered revisiting this.

**Comment by sholladay** [comment] 2023-10-04 09:43
@DanielRosenwasser yes, exactly!

While it would certainly be a welcome improvement for TypeScript to reject non-global regexps being passed to `.matchAll()`, that's a separate, unrelated issue.

This issue is strictly about the return type of `.matchAll()`, which does _not_ depend on the function's arguments whatsoever. Thus, TypeScript does not need to know or care about regexp flags to fix this.

TypeScript can safely assume that `.matchAll()` always returns a type with `.index` and `.input`. Right now, it lies and says they may not exist.

**Closed** 2023-11-30 21:51 UTC
Labels: Bug
