### ISSUE TITLE
Function name lost when compiling

### ISSUE THREAD

**Issue by sabrehagen** [microsoft/TypeScript#33408] opened 2019-09-13 07:30 UTC
I have identified a case when TypeScript compiled to JavaScript produces different functionality.

I have created a repro here: https://github.com/sabrehagen/tsc-function-repro

The crux of the issue is that `tsc` transforms a named function to an anonymous function, thereby changing the functionality as observed in the `console.log` output.

```sh
> git clone https://github.com/sabrehagen/tsc-function-repro

> yarn --cwd tsc-function-repro test:native
Function name is set correctly? true

> yarn --cwd tsc-function-repro test:compiled
Function name is set correctly? false
```

Input TypeScript

```ts
export const myFunction = () => {
}

console.log('Function name is set correctly?', myFunction.name === 'myFunction');
```

Compiled JavaScript

```js
"use strict";
exports.__esModule = true;
exports.myFunction = function () {
};
console.log('Function name is set correctly?', exports.myFunction.name === 'myFunction');
```

**Comment by AnyhowStep** [comment] 2019-09-13 07:42
Repro is on TS 3.6.3,

TS 3.5.1 [Playground](http://www.typescriptlang.org/play/#code/AQYw9gdgzgLsC2BPAYgVwiGBLSwC8wAFAJT4B8wA3gFAC+1140YANgKYB0LYA5oQORoM2XBACG8NsCxRgUNnHAAnJW0wtEAfn4AaBCnSYcEDuMn48BfkiFHI-YgG4gA) shows transpiled JS works fine

**Comment by MartinJohns** [comment] 2019-09-13 07:44
Duplicate of #6433.

**Comment by AnyhowStep** [comment] 2019-09-13 07:51
Not a duplicate, though.

It looks like the transpiled JS between 3.5.1 and 3.6.3 are different, and it's causing changes in behaviour for OP.

3.5.1,
```js
//transpiled JS
export const myFunction = () => {
};
```

Alleged by OP on 3.6.3,
```js
//transpiled JS
exports.myFunction = function () {
};
```

**Comment by MartinJohns** [comment] 2019-09-13 08:56
In the GitHub repository he linked he's targeting ES3, which does not support arrow functions.

**Comment by AnyhowStep** [comment] 2019-09-13 15:45
Ah. Right. No tsconfig.json file. So the default target is ES3

3.5.1, ES3 [Playground](http://www.typescriptlang.org/play/?target=0#code/AQYw9gdgzgLsC2BPAYgVwiGBLSwC8wAFAJT4B8wA3gFAC+1140YANgKYB0LYA5oQORoM2XBACG8NsCxRgUNnHAAnJW0wtEAfn4AaBCnSYcEDuMn48BfkiFHI-YgG4gA)

**Comment by sabrehagen** [comment] 2019-09-14 08:06
[Targeting `esnext`](https://github.com/sabrehagen/tsc-function-repro/commit/6e5aa56c4bde2e89f38cabeb8763e3150f319877#diff-e5e546dd2eb0351f813d63d1b39dbc48R3) I observe the same result.

> 3.5.1, ES3 [Playground](http://www.typescriptlang.org/play/?target=0#code/AQYw9gdgzgLsC2BPAYgVwiGBLSwC8wAFAJT4B8wA3gFAC+1140YANgKYB0LYA5oQORoM2XBACG8NsCxRgUNnHAAnJW0wtEAfn4AaBCnSYcEDuMn48BfkiFHI-YgG4gA)

That playground repro isn't the same. It has been changed from `export const` to `const`, and this is the crux of the issue. When using `export const` [this result](https://github.com/sabrehagen/tsc-function-repro/commit/6e5aa56c4bde2e89f38cabeb8763e3150f319877#diff-168726dbe96b3ce427e7fedce31bb0bcR3) is produced.

![image](https://user-images.githubusercontent.com/1094600/64905338-071d6800-d71a-11e9-9c05-1c6889b7cd02.png)

**Comment by AnyhowStep** [comment] 2019-09-14 08:53
`esnext` [Playground](http://www.typescriptlang.org/play/?target=6#code/KYDwDg9gTgLgBAYwgOwM7wLYE8BiBXZBGASxTgF44AKASgoD44BvAKAF8WWk0IAbYAHS8IAcyoByfIRJlkAQwzA4xVHFTB4SKFGBFeWAPziANHGxSipZAPmKK5SuPMFLKcTQDcQA) is fine.

**Comment by sabrehagen** [comment] 2019-09-15 01:08
I am unfamiliar with the playground and don't know how to use it to
reproduce my issue. Why are you using that instead of the reproduction I
crafted that demonstrates the issue?

**Comment by AnyhowStep** [comment] 2019-09-15 01:14
Take this,
```
"test:compiled": "yarn; yarn tsc --project tsconfig.json index.ts 2>&1 >/dev/null; node index.js",
```

Change to this,
```
"test:compiled": "yarn; yarn tsc --project tsconfig.json 2>&1 >/dev/null; node index.js",
```

Your tsc command has errors. But you never saw the errors because you keep throwing them away. You can't run from your problems forever.

**Comment by sabrehagen** [comment] 2019-09-15 23:54
> Did you even read my previous comment?

No, I replied by email meaning I did not see your edit history.

> Ah. Right. No tsconfig.json file. So the default target is ES3

Once I target `es2015`/`ES6` or higher this is resolved.

**Comment by sabrehagen** [comment] 2019-09-16 02:25
By setting `module: commonjs` it [reverted the success](https://github.com/sabrehagen/tsc-function-repro/commit/ad77269fca54830b89d410ce5496cf4065b308a6#diff-76b3dfe0496c32499513288d006d6aa6R3) achieved through `target: es2015`.

Reproducable with:

```sh
git clone https://github.com/sabrehagen/tsc-function-repro
yarn --cwd tsc-function-repro test
```

**Closed** 2019-09-18 18:00 UTC
Labels: Duplicate
