### ISSUE TITLE
TypeCheck: any number can be assigned to number-value enums

### ISSUE THREAD

**Issue by git9am** [microsoft/TypeScript#49967] opened 2022-07-20 04:23 UTC
# Bug Report

### 🔎 Search Terms

enum, number

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about enums

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?&code/KYOwrgtgBAKgngB2AQSgbwFBW1VBeKABgBoscAhKAgRlJygGEqoAmUgXwwwGMB7EAM4AXKADcAhgBswKagC5YiFMwC0AFgDcPfsLFSZyFgvhJ8UAORrzWjKEiKklTPTPnC5uhWbnqHstiYCcxY-Tm1BEQlpYHJ5BxjvKy0%20CL1o8iN4ygJNIA=#)

### 💻 Code

```ts
enum TypeA {
    A = 0,
    B = 1,
    C = 2,
}

const valueA1: TypeA = 4; // <-- no error
const valueA2: TypeA = '4';

enum TypeB {
    A = '0',
    B = '1',
    C = '2',
}

const valueB1: TypeB = '4';
const valueB2: TypeB = 4;
```

### 🙁 Actual behavior

The number can be assigned to an enum without errors.

### 🙂 Expected behavior

Errors.

**Comment by MartinJohns** [comment] 2022-07-20 05:19
Duplicate of #26362, which provides plenty of reasoning for this behaviour. Used search terms: `enum number in:title`

**Closed** 2022-07-22 18:00 UTC
Labels: Duplicate
