### ISSUE TITLE
Improve Control Flow Analysis for a || b Conditions in Combination with a ?? b

### ISSUE THREAD

**Issue by AbdessamadELmouden** [microsoft/TypeScript#60306] opened 2024-10-21 21:46 UTC
## Suggestion:
TypeScript currently does not infer that after checking multiple nullable values with `a || b || c`, the subsequent use of `a ?? b ?? c` should not result in a `null` or `undefined` type. I suggest that TypeScript improves control flow analysis to handle such cases, where a logical OR (`||`) check ensures that at least one of the values is truthy before the nullish coalescing operator (`??`) is used.

## Use Case:
In many situations, we check for multiple nullable or undefined values with a pattern like `a || b || c`, and then we safely use `a ?? b ?? c` in the next step. However, TypeScript currently still raises a type error because it does not infer that `a ?? b ?? c` is guaranteed to be non-null after the `||` checks.

Example:

```typescript
const a: string | null = null;
const b: string | undefined = undefined;


if (a || b) {
  const value = a ?? b ; // TypeScript should infer that value is cannot be null or undefined here because of the if statment . 
}
```

## Expected Behavior:
After the if (a || b ) check, TypeScript should infer that a ?? b  will return a non-null, non-undefined value.

## Potential Benefits:
This improvement would eliminate unnecessary type assertions and make TypeScript smarter at handling typical use cases in JavaScript, improving developer experience and code quality.

**Comment by jcalz** [comment] 2024-10-22 01:21
Already marked as a duplicate because of the template you chose, but this is a duplicate of #56221 and of many others, so, hooray?

**Closed** 2024-10-25 01:32 UTC
Labels: Duplicate
