### ISSUE TITLE
JSX and Salsa: Intellisense for ReactComponents does not work

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#7000] opened 2016-02-10 14:44 UTC
_From @nwehrle on February 10, 2016 11:52_

Salsa is enabled:
<img width="392" alt="bildschirmfoto 2016-02-09 um 22 13 44" src="https://cloud.githubusercontent.com/assets/832234/12930762/7cfdc1ba-cf7a-11e5-86d8-fffef477db6c.png">

But intellisense fails to offer proper React Elements:

![bildschirmfoto 2016-02-10 um 10 57 12](https://cloud.githubusercontent.com/assets/832234/12946423/a71b58d4-cff4-11e5-866c-beabfb1208c4.png)

![bildschirmfoto 2016-02-10 um 10 59 01](https://cloud.githubusercontent.com/assets/832234/12946411/8af7874a-cff4-11e5-90be-4c1e9f1c556d.png)

System:
OSX 10.11.2
vscode 0.10.8
db71ac615ddf9f33b133ff2536f5d33a77d4774e

jsconfig.json:

```
{
  "compilerOptions": {
    "target": "ES6",
    "module": "system",
    "experimentalDecorators": true
  },

  "exclude": [
    "node_modules"
  ]
}
```

User settings:

```
{
  "javascript.validate.enable": false,
  "editor.tabSize": 2,
  "files.trimTrailingWhitespace": true,
  // Migrated from previous "File | Auto Save" setting:
  "files.autoSave": "onFocusChange"
}
```

Partial eslintrc:

```
 "rules": {
    "func-names": 0,
    "no-unused-expressions": 0,
    "id-length": 0,
    "no-multi-spaces": 0,
    "no-mixed-spaces-and-tabs": 2,

    "no-unused-vars": [1, {"vars": "all", "args": "none"}],
    "react/jsx-uses-react": 1,
    "react/prop-types": 0,
    "no-console": 0
  },
  "plugins": [
    "react"
  ]
```

_Copied from original issue: Microsoft/vscode#2886_

**Comment by egamma** [comment] 2016-02-10 14:44
Did you install the corresponding .d.ts files?

>To get IntelliSense for React/JSX, install the typings for react-global by running tsd install react-global from the terminal.

**Comment by egamma** [comment] 2016-02-10 14:44
Does it work in this simple hello world example:

```jsx
var CommentBox = React.createClass({
  render: function() {
    return (
      <div className="commentBox">
        Hello, world! I am a CommentBox.
      </div>
    );
  }
});

ReactDOM.render(
  <CommentBox />,
  document.getElementById('content')
);
```

**Comment by egamma** [comment] 2016-02-10 14:44
_From @nwehrle on February 10, 2016 12:13_

You are right, I forgot to install the .d.ts file for the screenshot (but I tried before).
![bildschirmfoto 2016-02-10 um 13 04 57](https://cloud.githubusercontent.com/assets/832234/12946907/fb930df0-cff7-11e5-858c-8f8612f76bb7.png)


It does not offer the React-Component as the best option in your minimal example:
![bildschirmfoto 2016-02-10 um 13 08 08](https://cloud.githubusercontent.com/assets/832234/12946821/7aaa03ce-cff7-11e5-81ea-ef7af66af159.png)

**Comment by egamma** [comment] 2016-02-10 14:44
I see in your screenshot that you are using ES7 bind operator which is not yet supported by TypeScript which powers Salsa. As a consequence you get syntax errors and red squiggles which can make Intellisense fail.

In the second screenshot you are correct that the React-Component could be proposed first, but the React-Component is proposed so Intellisense is working but the sorting isn't optimal.

Moving over to TypeScript as an FYI.

**Comment by billti** [comment] 2016-02-10 17:22
I've discussed this internally before with @RyanCavanaugh . The challenge is with things like stateless functional components, any function really could be a valid React element, not just those types which derive from React classes/components.

I assume the identifier you require is in the list and starts filtering down when you type?

Arguably we could do a better job of filtering out things like interface names from the list, but that is a general issue with the global identifier list, and orthogonal to React.

Assigning to Ryan to see if he has any further input, else I believe this is by design.

**Comment by nwehrle** [comment] 2016-02-10 20:45
> I assume the identifier you require is in the list and starts filtering down when you type?
Yes it does, but it does not look like your screenshot, https://code.visualstudio.com/images/January_jsx-salsa.png - it looks like any other available var.

**Comment by prashaantt** [comment] 2016-02-18 16:09
I'm new to TypeScript so excuse me if this is silly. I do get IntelliSense for React via typings if I try accessing typings statically or inside the `React.createClass()` syntax, but not inside a component if I have declared an ES6 class the `class Test extends React.Component` way.

<img width="412" alt="screenshot 2016-02-18 21 31 51" src="https://cloud.githubusercontent.com/assets/390540/13149311/166374f4-d687-11e5-99bf-f525557dc7e5.png">

<img width="425" alt="screenshot 2016-02-18 21 38 16" src="https://cloud.githubusercontent.com/assets/390540/13149580/f3d3947c-d687-11e5-9ae0-842cd1b1fa39.png">


Is this rather an issue with the `react.d.ts` definition or some limitation of typings with the ES6 class syntax itself?

**Comment by mhegazy** [comment] 2016-02-19 23:07
There are two issues going on here:

1. the completion inside the class doe not show inherited properties at the moment, this is a feature that the TS language service does not support. but it is a fair request to add. added issue for it:https://github.com/Microsoft/TypeScript/issues/7158

2.  the completion on `React`. the problem is that the react module does not rely have a default export, the importing code uses the default import `import React from "react"` instead of the namespace import `import * as React from "react"`. Transpilers like Babel fudge this difference by a runtime check, but it is really a lie, and the module does not have a default export, and would not work without a transpiler. 
Ideally you should see a helpful message about this, and that is what we should fix.

**Comment by mhegazy** [comment] 2016-02-19 23:08
This issue is tracking item 2 above, i.e. showing appropriate error message.

**Comment by prashaantt** [comment] 2016-02-20 09:48
@mhegazy As I mentioned in my last comment, auto-complete on `React.` does works well for me if I have the typings in place.

<img width="369" alt="screenshot 2016-02-20 15 11 47" src="https://cloud.githubusercontent.com/assets/390540/13195904/49a55ca2-d7e4-11e5-9b8a-fc8ed276bb0e.png">

For this to work, though, like I posted over on https://github.com/Microsoft/vscode/issues/2898#issuecomment-185734544 I have had to change the `module` in my `jsconfig.json` to `system`. I discovered that accidentally, because if I now switch back to `commonjs` this only works for the commonjs `require`s and no longer for the ES6 imports, like you say in point 2 above.

**Comment by billti** [comment] 2016-02-22 17:32
> this only works for the commonjs requires and no longer for the ES6 imports, like you say in point 2 above

This sounds like the same issue as #7166 . I'm looking into that.

**Comment by billti** [comment] 2016-02-29 17:21
I have a fix out for the ES6-style imports, and confirmed it works in this scenario. See https://github.com/Microsoft/TypeScript/pull/7249#issuecomment-190297728

**Comment by patsissons** [comment] 2016-05-05 22:18
I'm running into a similar issue, but I'm not sure if it is the same as what has been discussed here. Most of the comments here appear to be with intellisense in a code block. My issue is that my react components are not showing up in the intellisense only for JSX blocks. Once I create the JSX element, the intellisense works for the attributes on the JSX element, just not for the initial creation of the element.

**Comment by mhegazy** [comment] 2016-05-07 00:43
@patsissons what version of VSCode / TypeScript are you using?

**Comment by patsissons** [comment] 2016-05-07 00:56
![VSCode version](https://cloud.githubusercontent.com/assets/5505280/15089223/c8f8984c-13b3-11e6-94a7-14d626d61e67.png)
![typescript version](https://cloud.githubusercontent.com/assets/5505280/15089224/d9d5db5c-13b3-11e6-8b7a-65fd39646e55.png)

**Comment by mhegazy** [comment] 2016-05-09 20:39
this issue is fixed in https://github.com/Microsoft/TypeScript/pull/7326. so should be available in the nightly builds (see https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code) or in the next release.

**Comment by billti** [comment] 2016-06-20 23:42
I believe all the issues discussed above are either fixed or explained, with the exception of @mhegazy 's comment that the error message should be improved when trying to use a default import that doesn't exist (and without `allowSyntheticDefaultImports`).

@mhegazy, did you have any thoughts on how this should behave? This is for JavaScript, so it may well be that you have no definitions for the imported module, and that is not an error. Seems that if: a) There is a definition we can use for the imported module, and b) That definition does not contain a `default` property, and c) You do not have `allowSyntheticDefaultImports` set - then if you try to use a default import from the module perhaps a message like `The module referenced does not export a default property.  Did you mean to import an identifier list or a namespace, or set "allowSyntheticDefaultImports" to true?`.

Even then, this is a little weird, as this is still a 'type system' error on a JavaScript file, and users may not be aware of the "synthetic default" and how different module systems interact with it.

**Comment by mhegazy** [comment] 2016-09-29 04:42
@billti would this be handled by https://github.com/Microsoft/TypeScript/issues/10895?

**Closed** 2016-12-16 01:21 UTC
Labels: Bug, Salsa, VS Code Tracked
