### ISSUE TITLE
Checking assignability without losing inferred types and without runtime code

### ISSUE THREAD

**Issue by wkrueger** [microsoft/TypeScript#26045] opened 2018-07-29 03:29 UTC
## Search Terms
type erase assert validat assign

## Suggestion

Recently I've been using a construct like the following in order to validate structures against a determinate type while still keeping their inferred type:

```ts
const validateType = <Requirement>() => <T extends Requirement>(i: T) => i
const aFunctionRecord = validateType<Record<string, Function>>() => ({
  hello: (world: string) => { ... },
  typescript: (cool: number) => { ... }
})
//aFunctionRecord retains its inferred type and will error if does not confirm the requirement
```
Oh, and this sometimes even infers parameters for functions, saving the need for some type annotations.

This is different from writing something like

```ts
const anotherFunctionRecord: Record<string, Function> = { ... }
//the inferred type is "lost"
```

While `validateType` works great, it feels a bit hacky, since we need to create a "concrete" JS function in order to achieve that. It would be great if that type of check could be achieved just with type annotations. Example:

```ts
const aFunctionRecord : * extends Record<string, Function> = { ... }
//or
const aFunctionRecord = { ... } extends Record<string, Function>
```

I have used `extends` in the example here since it's an already existing keyword, if you come up with a better idea...

thanks!

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by vilic** [comment] 2018-07-30 04:12
Possibly duplicate of #16605?

**Comment by wkrueger** [comment] 2018-07-31 00:36
Hmm got quite confused on comparing both issues. But they seem slightly different.

This issue (26045) seems quite alike Daniel's comment on that issue https://github.com/Microsoft/TypeScript/issues/16605#issuecomment-309290725. On the other hand, the 1st post of #16605 seems to ask something slightly different.

**Comment by RyanCavanaugh** [comment] 2021-12-16 00:21
Tracking at #7481

**Closed by RyanCavanaugh** 2021-12-16 00:21 UTC
Labels: Duplicate
