### ISSUE TITLE
--noUnusedParameters does not work good enough

### ISSUE THREAD

**Issue by KnisterPeter** [Microsoft/TypeScript#9860] opened 2016-07-21 06:47 UTC
**TypeScript Version:**  2.0.0

**Code**

```ts
function fn(p1: any, p2: any): void {
  return p2;
}
```

**Expected behavior:**
This should compile even with --noUnusedParameters

**Actual behavior:** 
Fails when p1 is unused.

Since this is method signature and callside may not be possible to fix this, the compiler should only flag unused from the end.

**Comment by mhegazy** [comment] 2016-07-21 07:30
Change the name of p1 to start with _. Parameters with underscores are exempt from error reporting.

**Comment by KnisterPeter** [comment] 2016-07-21 08:23
Interesting hidden feature. :laughing: 
Did you mean with 'working as intended' that this is not subject to change and this is not a bug?
Then I would say 'noUnusedParameters' is unusable, because developers need to know the hidden '_' prefix feature. This does not lead to clean and readable code (IMHO).

**Comment by yortus** [comment] 2016-07-21 11:25
This is a duplicate of #9458

**Closed** 2016-07-21 16:57 UTC
Labels: Duplicate

**Comment by mhegazy** [comment] 2016-07-21 17:28
>Interesting hidden feature

Please see documentation at https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#flag-unused-declarations-with---nounusedparameters-and---nounusedlocals
