### ISSUE TITLE
Wrong inferred never type

### ISSUE THREAD

**Issue by Brooooooklyn** [microsoft/TypeScript#44529] opened 2021-06-10 04:13 UTC
# Bug

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8BQ1XQGYHtMC5HQDswBbAUzwgBcAnASwIHNoBfaAH0IFcQRoBeLjxRoADtUwjS1SrVIwBAbQDkYJQBpoSgEbrNwJQF0kw1MEwEq1TsEqZqACjG0AbmEqlo1UmAAm5kACe0GYE6LQMeAjQPqToYNyUFDT0TMwAlIjMxmgYnATA9hnIOTmUABa0EAB0WJj8giDZJabmVNAQpJQAYtj19kRkSXSMGXwAfIgmzWjllTW9AlEDHlnTLE3NWNTQ9iFtBNCY6NCz1WISUjJyRVNrtMf9-HwCp1UhYQxVMXEJN2trHW62H6aVu01W4LBqHuO1etT+-1QcOwVWWUPWOSyzCAA

### 💻 Code

```ts
class A {
    foo: { name: string } | null = null
    properties = ['a', 'b', 'c']

    constructor(private readonly config: { default: string }) {}

    func() {
        this.foo = null

        const setFoo = (name: string) => {
            this.foo = { name }
        }

        for (const n of this.properties) {
            if (n === this.config.default) {
                setFoo(n)
            }
        }
        if (this.foo) {
            this.foo.name // Property 'name' does not exist on type 'never'.(2339)
        }
    }
}
```

### 🙁 Actual behavior
`this.foo` in if condition is inferred to `never`

### 🙂 Expected behavior

`this.foo` in if condition is inferred to `{ name: string }`

**Comment by MartinJohns** [comment] 2021-06-10 05:09
Duplicate of #9998.

**Closed** 2021-06-12 18:00 UTC
Labels: Duplicate
