### ISSUE TITLE
Event.currentTarget returns Element and not EventTarget

### ISSUE THREAD

**Issue by DaSchTour** [microsoft/TypeScript#13383] opened 2017-01-10 09:04 UTC
**TypeScript Version:**  2.1.4

**Code**
Example from MDN: https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget
```js
function hide(e){
  e.currentTarget.style.visibility = "hidden";
  // When this function is used as an event handler: this === e.currentTarget
}

var ps = document.getElementsByTagName('p');

for(var i = 0; i < ps.length; i++){
  ps[i].addEventListener('click', hide, false);
}
```

```ts
function hide(e: Event){
  e.currentTarget.style.visibility = "hidden";
  // When this function is used as an event handler: this === e.currentTarget
}

var ps = document.getElementsByTagName('p');

for(var i = 0; i < ps.length; i++){
  ps[i].addEventListener('click', hide, false);
}
```

**Expected behavior:**

e.currentTarget should be of type Element or EventTarget should extend Element

**Actual behavior:**
e.currentTarget is of type EventTarget which only has 3 properties

**Comment by FranklinWhale** [comment] 2017-01-10 15:59
This issue appears to be a duplicate of #299

**Closed** 2019-09-21 18:00 UTC
Labels: Duplicate

**Comment by ubay1** [comment] 2023-04-01 05:51
work for me

```ts
const test = (event: Event) => {
    const eventt = (event.currentTarget as HTMLInputElement);
}
```
