### ISSUE TITLE
Difference in type narrowing behavior between `!!` and `Boolean`

### ISSUE THREAD

**Issue by HJain13** [microsoft/TypeScript#46952] opened 2021-11-30 10:54 UTC
# Bug Report

### 🔎 Search Terms

* Boolean type inference 
* double bang

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about **Boolean** and **double bang**  

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.2#code/DYUwLgBAHgXBDOYBOBLAdgcwgHwgVzQBMQAzdEQgbgChqBjAezUQjBBYF4IAKdABzxg4iVJgCUEDgD4IAb2oRFEAPTKIAOQDymgArUAvrQCERqBABk51uzDcoY2gCEGDUAEM0diZeuIv1IA)

### 💻 Code

```ts
let x: string | undefined;

const test = (input: string) => {
    // NOOP
}

!!x && test(x)

Boolean(x) && test(x)
```

### 🙁 Actual behavior

`x` type doesn't get narrowed to `string` with `Boolean(x)` (test method errors out) but does with `!!x`

### 🙂 Expected behavior

Type to get narrowed to `string` with both

**Comment by MartinJohns** [comment] 2021-11-30 11:01
Another duplicate of #16655.

**Closed** 2021-12-03 18:00 UTC
Labels: Duplicate
