### ISSUE TITLE
Type of variables lost when returning a function that reuses them

### ISSUE THREAD

**Issue by MrChocolatine** [microsoft/TypeScript#42275] opened 2021-01-10 14:09 UTC
# Bug Report

### 🔎 Search Terms

type
lost
unknown

### 🕗 Version & Regression Information

- ~This is a crash~
- ~This changed between versions ______ and _______~
- This is the behaviour in every version I tried, and I reviewed the FAQ for entries about "lost, type".
- I was unable to test this on prior versions because I started on v4.
  However I tried with every versions in the Playground and I get the same result.

### ⏯ Playground Link

[Playground link with relevant code - v4.1.3](https://www.typescriptlang.org/play?ts=4.1.3#code/GYVwdgxgLglg9mABAQylZEAWBRAbgUzCgAp8AbfAW0KgC5FsLqiAaRAB2QCdlKBnegEEuPAJ4AecAGswcAO5gAfAEp64ACb5gMMPnWIAPomLFliALyLEuODHVmA3gChEiClEQBtRH3L5ocFxs+AREACqi7PhswEgAuhYc3Lx8Ti6IMMDG6a5QkfhwWb4UAVyIAITm5ogA5HxQXDoA5jU5hkZ5UYWIITQRURVVtfWNYC1tBh353bGD1TWgkLAIra6ObVz4UCBcYOkAvmmuAPTHiAAGxf5QgecZfIgQgZvQZKI++IQoD5cNzefpdyIdBcJpbRhURJ+ZhQAB0AEcQPguKIAMp+UrEK6lZRHDJZYgVEFgqAQyiIdauVybba7A5406IADCyHqiE2iJgm30rOB+QuADFwNB4GA7jAHrIPIQ4CAmphEMBAhdkOp1HgaAAZCVQQjIgGuIG9IgACWQYHUFDK1VmvNMFis0lkCgZZ3Oxqg-Xw4oeTxE1zeHy+vN+oyaBuB3BJZNhqvVoSg2vqeq4pATXuCCbNFqtuPSjPOxPBTB9iAARhgpMC4BcAPJlgBW13uHDgfD4MDLgbAIDIZAjBY9XtLzqDSBDTvkYpQTWQOnSNJ2SHtlkjoOLVFhm0ocAIGqISd1ulTQ-ymZo2ctyLzJzOqLgZBAyzA9FkYAAtD2+99fFxn4g4CiHh-wAakeVkPHOXkRn+NgyyfRA5EwUQAH58zORddmMMxVyLUkmHKLcqF3fB90THUUzTPp+Wgv4xnPU1zSvLhcX2IA)

[Playground link with relevant code - Nightly / v4.2.0-dev.20210108](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210108#code/GYVwdgxgLglg9mABAQylZEAWBRAbgUzCgAp8AbfAW0KgC5FsLqiAaRAB2QCdlKBnegEEuPAJ4AecAGswcAO5gAfAEp64ACb5gMMPnWIAPomLFliALyLEuODHVmA3gChEiClEQBtRH3L5ocFxs+AREACqi7PhswEgAuhYc3Lx8Ti6IMMDG6a5QkfhwWb4UAVyIAITm5ogA5HxQXDoA5jU5hkZ5UYWIITQRURVVtfWNYC1tBh353bGD1TWgkLAIra6ObVz4UCBcYOkAvmmuAPTHiAAGxf5QgecZfIgQgZvQZKI++IQoD5cNzefpdyIdBcJpbRhURJ+ZhQAB0AEcQPguKIAMp+UrEK6lZRHDJZYgVEFgqAQyiIdauVybba7A5406IADCyHqiE2iJgm30rOB+QuADFwNB4GA7jAHrIPIQ4CAmphEMBAhdkOp1HgaAAZCVQQjIgGuIG9IgACWQYHUFDK1VmvNMFis0lkCgZZ3Oxqg-Xw4oeTxE1zeHy+vN+oyaBuB3BJZNhqvVoSg2vqeq4pATXuCCbNFqtuPSjPOxPBTB9iAARhgpMC4BcAPJlgBW13uHDgfD4MDLgbAIDIZAjBY9XtLzqDSBDTvkYpQTWQOnSNJ2SHtlkjoOLVFhm0ocAIGqISd1ulTQ-ymZo2ctyLzJzOqLgZBAyzA9FkYAAtD2+99fFxn4g4CiHh-wAakeVkPHOXkRn+NgyyfRA5EwUQAH58zORddmMMxVyLUkmHKLcqF3fB90THUUzTPp+Wgv4xnPU1zSvLhcX2IA)

### 💻 Code

```ts
function attachEvent(element: Element, params: Array<unknown>): undefined | (() => void) {
  let [ selector, eventType, fn ] = params

  if (
    typeof selector !== 'string'
    || typeof eventType !== 'string'
    || typeof fn !== 'function'
  ) {
    return
  }

  // `selector` is correctly seen as `string`
  let targetElem = element.querySelector(selector)

  if ( !targetElem ) {
    return
  }

  // Cast required as type `Function` is not enough for `addEventListener`
  let eventHandler = fn as () => unknown

  // `eventType` is correctly seen as `string`
  targetElem.addEventListener(eventType, eventHandler)

  // `targetElem` is back to `Object is possibly null`
  // `eventType` is now seen as `unknown` again
  return () => targetElem.removeEventListener(eventType, eventHandler)

  // Solution: non-null assertion operation + cast `as string`, but why?
  // return () => targetElem!.removeEventListener(eventType as string, eventHandler)
}
```

### 🙁 Actual behaviour

- Type of variable `targetElem` is lost and fallback to its initial type.
- Type of variable `eventType` is lost and fallback to its initial type.

### 🙂 Expected behaviour

Since the context does not change and their type has been narrowed down, the types of the variables `targetElem` and `eventType` should be kept.

### Possible related issues

- https://github.com/microsoft/TypeScript/issues/27706

Thank you for your feedback.

**Comment by MartinJohns** [comment] 2021-01-10 14:20
Duplicate of #9998.

**Closed** 2021-01-14 18:00 UTC
Labels: Duplicate

**Comment by MrChocolatine** [comment] 2021-02-14 22:19
Despite this ticket having been closed, just a heads-up for whoever that might come across the same issue:

Declaring variables with `const` instead of `let` fixed my initial issue, see [this playground with TypeScript v4.1.3](https://www.typescriptlang.org/play?ts=4.1.3#code/GYVwdgxgLglg9mABAQylZEAWBRAbgUzCgAp8AbfAW0KgC5FsLqiAaRAB2QCdlKBnegEEuPAJ4AecAGswcAO5gAfAEp64ACb5gMMPnWIAPomLFliALyLEuODHVmA3gChEiCAj5REAbUR9y+NBwXGz4BEQAKqLs+GzASAC6FhzcvHxOLogwwMaZrlDR+HA5-hRBXIgAhObmiADknlw6AOZ1eYZGBTHFiGE0UTFVNfWNLW2urgadhT3xQ7V1oJCwCOOIju1c+FAgXGCZAL4ZrgD0J4gABqWBUMEXWXxuwVvQZKJ++IQoj1dQTWDNC6ZdxgTyIdBcZrbRhUZIBZhQAB0AEcQPguKIAMoBcrEa7lZTHLI5YhVCFQqAwyjrRDOCaILY7PaHIlnRAAYWQYK2qJgW30XPBhUuADFwNB4GB7jBHrIvIQ4CBmphEMBgpdkOp1HgaAAZGVQQjooGuEFgvpEAASyDA6goFVqc0FpgsVmksgUrPOFwtUAG+Glj3cIhubw+X0Fv3+gMy5OhTERmu14Sg+s8Rq4pBT-tCKettvthMybIuccpTEDiAARhgpOC4JcAPJVgBWNweHDgfD4MCrYbAIDIZBNiBLvv9lY94aQkfd8ilKGayB0mUZuyQLss4O4FKpiK2lDgBB1RDTht0mfHhVzNHzdvRRdO50xcDIIBWYHosjAAFoB0Pvn8LgP0QOAYh4ECAGo3C5LwLkFUYAQuNgq3fRA5EwUQAH5i3ONc9mMMwtzLKlKn3Kgj3wE9UwNDMs36YUEL+FobytG17y4QkDiAA).

--- 

To give a bit of a context, I was working on an Ember.js project and historically we had this lint rule that recommended to only use `const` at the top-level of any file:
https://github.com/DockYard/eslint-plugin-ember-suave/blob/5c1e256254768172aeba3e10843036d7b3503484/docs/rules/no-const-outside-module-scope.md

Since we migrated the codebase to TypeScript this rule was not relevant anymore and, as we can see, in this case it fixed the issue.
