### ISSUE TITLE
Variable incorrectly inferred across await boundary

### ISSUE THREAD

**Issue by sceutre** [Microsoft/TypeScript#31009] opened 2019-04-18 08:02 UTC
**TypeScript Version:**  3.4.0

**Search Terms:** enumeration async await

**Code**

```ts
function wait(tm: number) {
   return new Promise((resolve, reject) => {
      setTimeout(() => resolve(true), tm);
   });
}

let x: "foo" | "bar";

async function baz() {
    x = "bar";
    await wait(1000);
    if (x == "foo") {
        // erroneous: This condition will always return 'false' since the types '"bar"' and '"foo"' have no overlap.
        console.log("could be reached");
    }
}

setTimeout(() => x = "foo", 500);
baz();
```

**Expected behavior:**

Code should compile fine

**Actual behavior:**

Compiler believes x must be "bar" since it was assigned such at the start of the method.  However since there is an await this is not true.

**Playground Link:** 

[Playground link](https://www.typescriptlang.org/play/#src=function%20wait(tm%3A%20number)%20%7B%0D%0A%20%20%20return%20new%20Promise((resolve%2C%20reject)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20setTimeout(()%20%3D%3E%20resolve(true)%2C%20tm)%3B%0D%0A%20%20%20%7D)%3B%0D%0A%7D%0D%0A%0D%0Alet%20x%3A%20%22foo%22%20%7C%20%22bar%22%3B%0D%0A%0D%0Aasync%20function%20baz()%20%7B%0D%0A%20%20%20%20x%20%3D%20%22bar%22%3B%0D%0A%20%20%20%20await%20wait(1000)%3B%0D%0A%20%20%20%20if%20(x%20%3D%3D%20%22foo%22)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20erroneous%3A%20This%20condition%20will%20always%20return%20'false'%20since%20the%20types%20'%22bar%22'%20and%20'%22foo%22'%20have%20no%20overlap.%0D%0A%20%20%20%20%20%20%20%20console.log(%22could%20be%20reached%22)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0AsetTimeout(()%20%3D%3E%20x%20%3D%20%22foo%22%2C%20500)%3B%0D%0Abaz()%3B)

**Related Issues:**

**Comment by MartinJohns** [comment] 2019-04-18 08:46
Duplicate of #9998.

**Comment by sceutre** [comment] 2019-04-19 18:22
Ah I had seen that issue but didn't read the comments in enough detail.  In particular this issue is exactly what was written up in this comment: https://github.com/Microsoft/TypeScript/issues/9998#issuecomment-439610488

**Closed** 2019-04-22 18:00 UTC
Labels: Duplicate
