### ISSUE TITLE
Provide shortcut for annotating destructured params

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/TypeScript#28145] opened 2018-10-25 23:09 UTC
## Search Terms

destructured label:Suggestion

## Suggestion

It would be great to have a shorter way of annotating destructured params.

## Use Cases

Annotations for destructuring have to be verbosely typed out, e.g.:
```ts
{ a, b, c }: { a: string, b: number, c: string }
```

This could be shortened to decrease the amount of code needed.

## Examples

```ts
  public pipeThroughProcess({
    bucket,
    key,
    process,
  }: {
    bucket: string;
    key: string;
    process: ChildProcess;
  }) {
    //
  }
```

This is extremely redundant and there's no way to avoid it, other than creating an `interface` which also feels unnecessary for something that will be only be used once.

It would be ideal to just be able to do this instead:

```ts
public pipeThroughProcess({ bucket, key, process }: { string, string, ChildProcess }) {}
```

I've tried to think of some reason this wouldn't work, but it seems like this would work and would _not_ be a breaking change (it could be optional).

## Checklist

My suggestion meets these guidelines:
* [X] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [ ] (unsure) This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by andy-ms** [comment] 2018-10-25 23:36
Duplicate of #7576

**Closed** 2018-12-13 18:00 UTC
Labels: Duplicate
