### ISSUE TITLE
Object is possibly undefined in arrow function

### ISSUE THREAD

**Issue by icecream17** [microsoft/TypeScript#42848] opened 2021-02-17 23:10 UTC
# Bug Report

### 🔎 Search Terms

Object is possibly undefined
ts(2532)

### 🕗 Version & Regression Information

I just started using typescript, so this is the latest version.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210217&ssl=1&ssc=1&pln=16&pc=1#code/JYOwLgpgTgZghgYwgAggDzgWwA4BsUDeAUMqWAJ7YQDOA-AFzJwjkDaAuiaQG5y4CuNBkxYciAXyJEY-EAjDAA9iGQBlRZggAVGmAAUAawgRsjdFjwoAvMgLiAlI26LgAE1tdkRkwDoKVamQbb2xaP0oaZFpaZDFSL2NsH14BSODEsJTBQOjYzk8AegLkACIQ8ICS5AB3RSgDak8EZWpFfB9cRQBzQ0SKmh9QBAFXGj0AZnt7KXii0vKsmirXRRoQAHIwWiaWtogO7r09RcZmcnsggD4E30XqQbkRscWpiSIgA)

### 💻 Code

```ts
interface example {
   types?: any[]
   values?: any[]
}

function SomeTest(keep: example = {}): void {
   keep.types = keep?.types ?? []
   keep.values = keep?.values ?? []

   // "keep.types" works
   console.log(keep.types.includes(3))

   // "keep.values" doesn't?
   console.log((value: any) => keep.values.includes(value))
}

```

### 🙁 Actual behavior

I got ```Object is possibly 'undefined'. ts(2532)``` even though that was already checked.

Weirdly it only fails in ```keep.values```, ```keep.types``` works correctly.

### 🙂 Expected behavior

No errors for both properties

**Comment by IllusionMH** [comment] 2021-02-18 00:30
Most likely duplicate of #9998

**Comment by icecream17** [comment] 2021-02-18 01:20
Hmm. Maybe in the above code the variables could've changed.

If it helps, the original code was like this, where the function is called immediately
```typescript
   const testValues = Array.from(toTest.values()).filter(testValue => !without.values.includes(testValue))

   // Shorter, to match with above
   [].filter((value: any) => keep.values.includes(value))
```

**Comment by MartinJohns** [comment] 2021-02-18 06:39
Still a duplicate of #9998. ;-)

**Comment by RyanCavanaugh** [comment] 2021-02-18 18:52
Working as intended: narrowings on mutable expressions aren't applied to closures because the function might get run at a point where the narrowing is no longer valid

**Comment by icecream17** [comment] 2021-02-19 15:05
> Working as intended: narrowings on mutable expressions aren't applied to closures because the function might get run at a point where the narrowing is no longer valid

See my 2nd comment

**Comment by MartinJohns** [comment] 2021-02-19 15:09
> See my 2nd comment

The compiler is not aware that the callback passed to `filter` (or any callback, really) is immediately invoked, so this changes nothing. You would need #11498 for this.

**Closed** 2021-02-21 18:00 UTC
Labels: Duplicate
