### ISSUE TITLE
VS 2015/2017 ignored the "extends" property of tsconfig during save

### ISSUE THREAD

**Issue by ifle** [Microsoft/TypeScript#15326] opened 2017-04-23 11:19 UTC
**TypeScript Version:**  2.2.1

**Code**

tsconfig.json
```ts
{
    "extends": "../../../../tsconfig.base.json",
    "compilerOptions": {
        "outDir": "../../js"
    },
    "include": [
        "../../../../Common/html/scripts/"
    ],

    "exclude": [
        "node_modules"
    ]
}

```
tsconfig.base.json
```ts
{
    "compileOnSave": true,
    "compilerOptions": {
        "noImplicitAny": false,
        "noEmitOnError": false,
        "removeComments": false,
        "sourceMap": true,
        "listEmittedFiles": true,
        "target": "es5",
        "lib": [
            "dom",
            "es5",
            "es2015.promise"
        ],        
        "allowJs": true
    },    
    "exclude": [
        "node_modules"     
    ]
}
```
**Expected behavior:**
Edited file to be outputted. The compileOnSave property defined in the base tsconfig file
**Actual behavior:**
Edited file is not outputted.

**Comment by mhegazy** [comment] 2017-04-24 18:55
Duplicate of https://github.com/Microsoft/TypeScript/issues/13910, Fixed by https://github.com/Microsoft/TypeScript/pull/15255

**Closed** 2017-04-24 18:55 UTC
Labels: Duplicate
