### ISSUE TITLE
Add missing import adds import before file header

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#25907] opened 2018-07-24 21:48 UTC
**TypeScript Version:**   typescript@3.1.0-dev.20180724

**Search Terms:**
- Add missing import
- copyright header

**Code**
In a project:

`a.ts`
```ts
export const abc =123;
```

`b.ts`:

```ts
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
'use strict';

abc
```

1. Trigger the add missing import quick fix on `abc` in `b.ts`

**Expected behavior:**
Import added after copyright header and use strict:

```ts
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
'use strict';

import { abc } from './a'

abc
```

**Actual behavior:**
Import added at top of file:

```ts
import { abc } from './x';

/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
'use strict';

abc
```

**Playground Link:** 

**Related Issues:**

**Comment by mhegazy** [comment] 2018-07-24 21:56
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/15515

**Comment by mjbvz** [comment] 2018-07-24 22:03
Yes. This also applies if you only have a header comment and no `'use strict';`

**Closed** 2018-08-02 21:55 UTC
Labels: Duplicate
