### ISSUE TITLE
[Proposal] Simpler class transformation

### ISSUE THREAD

**Issue by bigopon** [Microsoft/TypeScript#12516] opened 2016-11-26 20:28 UTC
Please ignore if this already discussed.
* Current problem
Suppose I have a class like this:

```js
class MyClass {
   //....
   // Here I have 100 class methods
}
```

This will be transformed into:

```js
function MyClass() {}
// 100 times of this repeated: MyClass.prototype.method... = fn
```

* **Expected behavior** - Ideal transformation
Can we have something like this instead:

```js
var _proto = MyClass.prototype
// 1000 class methods ?
_proto.method1 = fn
_proto.method2 = fn
```

* After minification
// a lot less output code after minification

```js
// var a = MyClass.prototype;
// a.method1 = fn
// a.method2 = fn
```

Imagine if we have 20 of classes like this, the amount of prototype repeated will be big, not counted the long class names

Can we have it enhanced in this way ?

**Comment by aluanhaddad** [comment] 2016-11-27 01:15
This looks like a duplicate of #9638

**Comment by bigopon** [comment] 2016-11-27 04:08
Hmm it is indeed. This should be closed.

**Closed** 2016-11-28 18:08 UTC
