### ISSUE TITLE
wrong indent after formatting

### ISSUE THREAD

**Issue by jrieken** [microsoft/TypeScript#8644] opened 2016-05-17 13:23 UTC
**TypeScript Version:** 

1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

**Code**

``` ts
// A self-contained demonstration of the problem follows...
this._register('vscode.diff', (left: URI, right: URI, label: string) => {
    return this._commands.executeCommand('_workbench.diff', left, right, label);
}, {
    description: 'Opens the provided resources in the diff editor to compare their contents.',
    args: [
        { name: 'left', description: 'Uri of the resource for the left hand side of the diff editor', constraint: value => value instanceof URI },
        { name: 'right', description: 'Uri of the resource for the right hand side of the diff editor', constraint: value => value instanceof URI },
        { name: 'label', description: 'Label to use for the diff editor', constraint: value => typeof value === 'string' }
    ]
});
```

**Expected behavior:**
- goto ts playground 
- paste the code and invoke format
- you get this (note the wrong indent on the last 7 lines):

```
this._register('vscode.diff', (left: URI, right: URI, label: string) => {
    return this._commands.executeCommand('_workbench.diff', left, right, label);
}, {
        description: 'Opens the provided resources in the diff editor to compare their contents.',
        args: [
            { name: 'left', description: 'Uri of the resource for the left hand side of the diff editor', constraint: value => value instanceof URI },
            { name: 'right', description: 'Uri of the resource for the right hand side of the diff editor', constraint: value => value instanceof URI },
            { name: 'label', description: 'Label to use for the diff editor', constraint: value => typeof value === 'string' }
        ]
    });
```

**Actual behavior:** 

indent properly

**Comment by SaschaNaz** [comment] 2016-07-31 13:25
Should be fixed by #3827.

**Comment by Animeshz** [comment] 2020-05-10 13:08
@saschanaz issue still persists.

**Comment by saschanaz** [comment] 2020-05-10 13:20
@Animeshz Which TS version do you use? Can you reproduce your issue in https://www.typescriptlang.org/play, and if you can, share it?

**Comment by RyanCavanaugh** [comment] 2020-12-09 19:38
Seems to be fixed now

**Closed by RyanCavanaugh** 2020-12-09 19:38 UTC
Labels: Bug, Domain: Formatter, VS Code Priority, help wanted
