### ISSUE TITLE
Boolean inference is too strict

### ISSUE THREAD

**Issue by hipolipolopigus** [microsoft/TypeScript#31249] opened 2019-05-04 04:44 UTC
**TypeScript Version:**  3.5.0-dev.20190503

**Search Terms:** Boolean inference true false

**Code**

```ts
type State<TStateKeys extends string = string> = {
	[k in TStateKeys]: boolean | number | string
};

class Foo<TState extends State> {
	constructor(public state: TState) {}
}

const obj = new Foo({
	a: 1,
	b: "string",
	c: true,
	d: false,
	// Workaround
	e: !!false
});

obj.state.a = 2; // No error
obj.state.b = "another string"; // No error

// Accepts only `false`, should accept either
obj.state.c = false; // TS2322: Type 'false' is not assignable to type 'true'.

// Accepts only `true`, should accept either
obj.state.d = true; // TS2322: Type 'true' is not assignable to type 'false'.

// Accepts either boolean
obj.state.e = true; // No error

```

**Expected behavior:** `obj.state.c` and `obj.state.d` accept either boolean.

**Actual behavior:** `obj.state.c` and `obj.state.d` are hard-typed to `true` and `false`, respectively.

**Comment by ahejlsberg** [comment] 2019-05-04 22:49
This issue has the same root cause as #30390, so I'm marking it as a duplicate.

**Closed** 2019-05-07 18:00 UTC
Labels: Duplicate
