### ISSUE TITLE
[JavaScript construction -> this.constructor.<STATIC>]

### ISSUE THREAD

**Issue by eugene-matvejev** [Microsoft/TypeScript#9742] opened 2016-07-14 17:20 UTC
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**

``` js
# VALID JS [ECMA6]
class A {
    constructor() {
         console.log(this.constructor.resources.random)
    }
}

A.resources = {
    random: 123
}
```

``` ts
// A *self-contained* demonstration of the problem follows...
class A {
    constructor() {
//not-work
         console.log(this.constructor.resources.random)
    }
    public static resources = {
       random: 123
   }
}
// WORK
class A2 {
    constructor() {
//not-work
         console.log(A2.resources.random)
    }
    public static resources = {
       random: 123
   }
}
```

**Expected behavior:**
case of A should work.
**Actual behavior:** 
case of A do not work.

more info:

> > > λ: tsc --version
> > > Version 1.8.10

**Comment by Arnavion** [comment] 2016-07-15 02:02
Duplicate of #3841

**Closed** 2018-11-29 07:51 UTC
Labels: Duplicate
