### ISSUE TITLE
Wrong type inferred for array of tuples

### ISSUE THREAD

**Issue by chinhodado** [Microsoft/TypeScript#28336] opened 2018-11-05 05:43 UTC
**TypeScript Version:**  3.1.6

**Search Terms:**
array tuple inference inferred argument

**Code**

```ts
let x = [["a", [1]]];

function f(arg: [string, number[]][]) {
}

f(x);

// If I declare x's type directly like this then it works:
// let x: [string, number[]][] = [["a", [1]]];
```

**Expected behavior:**
No error

**Actual behavior:**
Error:
```
Error:(352, 3) TS2345: Argument of type '(string | number[])[][]' is not assignable to parameter of type '[string, number[]][]'.
  Type '(string | number[])[]' is not assignable to type '[string, number[]]'.
    Property '0' is missing in type '(string | number[])[]'.
```

**Playground Link:** 
[Link](https://www.typescriptlang.org/play/#src=let%20x%20%3D%20%5B%5B%22a%22%2C%20%5B1%5D%5D%5D%3B%0D%0A%0D%0Afunction%20f(arg%3A%20%5Bstring%2C%20number%5B%5D%5D%5B%5D)%20%7B%0D%0A%7D%0D%0A%0D%0Af(x)%3B)

**Comment by DanielRosenwasser** [comment] 2018-11-05 06:00
Duplicate of https://github.com/Microsoft/TypeScript/issues/16389

**Comment by ahejlsberg** [comment] 2018-11-05 14:59
Also see my comment [here](https://github.com/Microsoft/TypeScript/issues/27179#issuecomment-422472039).

**Comment by chinhodado** [comment] 2018-11-05 15:07
I see, thank you for the quick response!

**Closed** 2018-12-13 18:00 UTC
Labels: Duplicate
