### ISSUE TITLE
`Nullable<T>` built-in type alias

### ISSUE THREAD

**Issue by isiahmeadows** [microsoft/TypeScript#39800] opened 2020-07-29 07:39 UTC
## Search Terms

nullable type alias
optional type alias
nullable built-in type
optional built-in type

## Suggestion

I'd like this added to the list of global built-in types, as an inverse of `NonNullable<T>`:

```ts
type Nullable<T> = T | null | undefined;
```

## Use Cases

- Sometimes, when I'm coding at the application level, I want a type that can be either `null`, `undefined`, or a value, and I don't want to have to pick one.
- In library definitions, it's quite common for an API to accept both `null` and `undefined` as equivalent.
- It would also make for more easily understood errors and autocomplete, as `Nullable<{some: "really", complex: "object", type: true} | number>` would be a lot faster and easier to read than `{some: "really", complex: "object", type: true} | number | null | undefined`.

## Examples

Just to name a couple right off:

- [This part in React's type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2818-L2822) could be simplified to `Validator<null | undefined extends T[K] ? Nullable<T[K]> : T[K]>`
- [Lodash's `_.chunk` definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/common/array.d.ts#L14-L17) could just use `chunk<T>(array: Nullable<List<T>>, size: number): T[][]`. (That file is full of similar types of the form `T | null | undefined.)
- There are over 400 results in searching the DTS repo alone for [`"null | undefined"`](https://github.com/DefinitelyTyped/DefinitelyTyped/search?l=TypeScript&q=%22null+%7C+undefined%22) and [`"undefined | null"`](https://github.com/DefinitelyTyped/DefinitelyTyped/search?l=TypeScript&q=%22undefined+%7C+null%22). (Some of the results are of unrelated things, but at least 80% of them are of a type like this.)

Chances are, if you've done significant TS development in general applications or if you've done significant type definitions work, you've probably run into something where this could've helped.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code **Probably, but not 100% sure.**
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-07-29 09:28
Duplicate of #39522. Search terms: `Nullable` (remember to check closed issues)

**Closed** 2020-07-31 18:00 UTC
Labels: Duplicate

**Comment by isiahmeadows** [comment] 2020-07-31 18:37
@MartinJohns I did, it just failed me this time around. 😕
