### ISSUE TITLE
Newly initialized object with non-optional properties are not initialized and generate no TS transpiler error

### ISSUE THREAD

**Issue by Asvarduil** [Microsoft/TypeScript#14488] opened 2017-03-06 19:16 UTC
**Description:**
Assume that a class *Foo* exists with no constructor or default assignments, with a number of member fields or properties, that are not optional (they lack the ? token after the type declaration, and don't include the ability to be null or undefined).  These non-optional properties are not set up with default values.  If referenced at runtime, the code creates an Undefined Reference JavaScript exception.

**TypeScript Version:**  2.1.5

**Code**
```ts
// A *self-contained* demonstration of the problem follows...
export class Foo {
    public name: string;
    public someThing: Bar;
}

export class Bar {
    public isActive: boolean;
}

let foo : Foo = new Foo();

// foo's contents are { __proto__: {...}}, no fields or properties exist on it at this point.
// foo.someThing is undefined!
if(foo.someThing.isActive === true)
{
    // JS Undefined reference exception here when executed
    // When transpiling, TypeScript does not catch that foo.someThing is undefined
}
```

**Expected behavior:**
There are two possibilities for what is expected of an instantiation to do, in regards to the TS transpiler:

1. Non-optional fields/properties have default values generated by the TypeScript transpiler.  This is how C#, Java, and other languages that TypeScript syntactically are based on, actually work.
1. TypeScript warns you of a possibly undefined field as a transpiler warning or error.  This is helps the end-user prevent a JavaScript exception that the TS compiler should be helping you avoid.  This warning or error is not raised if the type is appended with the optional modifer (in the example above, 'public someThing: Bar?', or 'public someThing: Bar | null | undefined')

**Actual behavior:**
1. The above code compiles without issue, when it will cause the end-user to encounter an Undefined Reference exception.
1. The above code as-is is not type-safe even with explicit non-'any' types, as the value of the variables is undefined, and not a default value of the non-optional type that was defined.

**Comment by RyanCavanaugh** [comment] 2017-03-06 19:21
#8476

**Comment by Asvarduil** [comment] 2017-03-06 19:26
@RyanCavanaugh - even if Expected Result 1 isn't feasible, it would be helpful to know upon compilation that what is trying to be done in the code snippet given is a no-no.  This is easily worked around, but breaks continuity with other languages (or, is a little _too_ continuous with JavaScript.)

```ts
export class Foo {
    public name: string = '';
    public someThing: Bar = new Bar();
}

export class Bar {
    public isActive: boolean = true;
}

// ...Rest of example code, should now work...
```

**Comment by RyanCavanaugh** [comment] 2017-03-06 19:44
Please leave comments in the linked bug, or clarify if you think this isn't a duplicate of the other

**Comment by Asvarduil** [comment] 2017-03-06 19:48
I've clarified the Issue title to note the primary point of divergence from the issue you linked, which is that you can do this sort of thing, but get no warnings.  

While initializing the value would be awesome if it can be done, having the TSC tell me I'm doing something dumb is a nice consolation prize, and probably more realistic in the short term.

**Comment by RyanCavanaugh** [comment] 2017-03-06 20:04
There's no way we could initialize a satisfactory value for an arbitrary type (even if we wanted to). For example `number | string`, or a class type with no parameterless constructor, or a generic type all lack a plausible initializer. This also directly conflicts with our stated design goals.

**Comment by Asvarduil** [comment] 2017-03-07 00:55
@RyanCavanaugh - I don't find that argument entirely accurate, as languages like C# and Java don't implicitly instantiate child complex types, but do implicity instantiate primitives on construction, which is what I'm talking about - bringing TypeScript in to parity with the languages it's aping.  In C# if you have the following code:

```c#
public class Foo
{
    public string Name;
    public Bar SomeThing;
}

public class Bar
{
    public bool IsActive;
}

// ...Boilerplate...
public static void Main()
{
    var foo = new Foo();

    if(string.IsNullOrEmpty(foo.name)
        Console.WriteLine("foo has no name!");

    if(foo.Bar.IsActive)
        Console.WriteLine("This throws an exception because Bar isn't initialized!");
}
```

...The first Console.WriteLine will be presented, as string primitives initialize as a string with length of zero (or, to use C# parliance, 'string.Empty'), but the program given above will throw an exception due to Bar not being initialized.

As noted in my original bug report above, this is what I would count as a valid expected behavior as it's in-line with how the languages that TypeScript's syntax is modeled off of, behaves.

**Comment by RyanCavanaugh** [comment] 2017-03-07 01:39
Just to clarify: TypeScript is not based on C#. It's JavaScript with static typing. Classes are an ES6 feature which originated in the abandoned ES4 spec; these classes did not have automatic member initialization either.

**Closed** 2017-03-07 01:40 UTC
Labels: Duplicate
