### ISSUE TITLE
No errors reported for use-before-definition with block-scoped declarations across files

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#6853] opened 2016-02-02 21:52 UTC
See `tests/cases/compiler/constDeclarations-useBeforeDefinition2.ts`.

file1.ts:
```ts
c
```

file2.ts
```ts
const c = 0;
```

Compile with `tsc --outFile hello.js file1.ts file2.ts`

Expected: Use before declaration error.
Actual: No error.

Pinging @vladima and @zhengbli for bringing this up.

**Comment by ahejlsberg** [comment] 2016-02-02 22:46
Since we don't know anything about the final ordering unless you compile with `-outFile`, are you proposing we only do this with `-outFile`? Seems a bit odd.

**Comment by mhegazy** [comment] 2016-02-02 22:51
@ahejlsberg, this is what we do, or were doing, anyways. see https://github.com/Microsoft/TypeScript/blob/master/src/compiler/checker.ts#L487-L493

**Comment by vladima** [comment] 2016-02-02 23:22
I can repro the issue only if I specify `-t ES6` (the same setting is set in the test from the issue description). Root cause: we skip this check for modules because we cannot reason about ordering. However in current codebase having target `ES6`  also implies `moduleKind=ES6` and this causes us to bypass the check.

**Comment by mhegazy** [comment] 2016-02-02 23:23
@zhengbli has a change to this logic already, to change module default. so i guess this should be covered.

**Comment by vladima** [comment] 2016-02-02 23:26
@zhengbli can you test if this issue still reproduces with your change?

**Comment by zhengbli** [comment] 2016-02-02 23:36
@vladima @mhegazy this issue can be fixed by changing the default module. I brought it up to make sure that this is the desired behavior. I'll send a PR soon.

**Closed** 2016-06-15 19:43 UTC
Labels: Bug
