### ISSUE TITLE
feature request: type guards for multi params

### ISSUE THREAD

**Issue by isLishude** [Microsoft/TypeScript#27308] opened 2018-09-24 13:26 UTC
## Examples

```typescript
import { isString, isNubmer } from "util";

function Case(name?: string, symbol?: string, decimals?: number): name is string => {
  return isString(name) && isString(symbol) && isNumber(decimals);
};
```

not only `name is string` but `symbol is string` && `decimals is nubmer`

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by jack-williams** [comment] 2018-09-24 14:06
I think this is a duplicate of #26916

**Closed** 2018-09-24 22:44 UTC
Labels: Duplicate
