### ISSUE TITLE
Documentation claims conditional types can replace overloads - provided example doesn't compile

### ISSUE THREAD

**Issue by colemars** [microsoft/TypeScript#50932] opened 2022-09-23 23:28 UTC
# Bug Report

### 🔎 Search Terms

conditional types, conditional type docs, overloads

### Problem

[Conditional type docs](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html) reference two code examples:

Overloads: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJIBMAycBGEA2yA3gFDLLDoBcyIArgLZ5TID0AVMgM4D2DKMYAXRdk7VgG4SAXxKhIsRCgBycftjyFS5EGog0uYKKADmbTjzAALaMkHDR4qbJIw6IBGGA8QyBFAg4SA0CAApKGnomaABKGgwQ-Ck3Dy8fPwCgiETQ3X4DI1M45FV1XAJk909vX39A4PL8XL0AeSgMAuMQMwAfWkZmYoTG5D7S7MbK1JqM+onNZv42ju5C7tH+6KghrBGxvUTiMmRrKB4Ad2QAIndgBgAHfAh+cAh0K+cgA

Conditional types: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJIBMAycBGEA2yA3gFDLLDoBcyIArgLZ5TID0AVMgM4D2DKMYAXRdk7VgG4SAXxKhIsRCgBycftjyFS5EGog0uYKKADmbTjzAALaMkHDR4qbLABPAA4q9AeSgYAPAAqyBAAHpAgIrSMzMgAPtxGpgB8yAC8yMFhEVH0TNBkyAD8aFi4BIU0qurl+FKsrMgAtC0IdGAtTSQwdCAIYMA8IMgIUBBwkBoEQSHhEJGiebEJhsYgJskAFJS+1fqZAJRVPn7oQanayNZQPADuyABEvcAM7vgQ-OAQ6A-OJCTvMDIODpEZjCYQKb4TYPNyeLijYDuMAPA71RrIAB6RX+gOQOFBo3Gk1qmwATAA6AAcaJIDXI2NxECBCEJ4JJmk2AFkJlYKVA4JE+JsDsVHjZ8PgeA9kDQACxk2n0rFFIA

It's stated that the latter is an alternative to the former - however, the only reason the latter compiles is that it lacks any sort of implementation. As soon as anything is attempted to be returned [the conditional example fails.](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJIBMAycBGEA2yA3gFDLLDoBcyIArgLZ5TID0AVMgM4D2DKMYAXRdk7VgG4SAXxKhIsRCgBycftjyFS5EGog0uYKKADmbTjzAALaMkHDR4qbLABPAA4q9AeSgYAPAAqyBAAHpAgIrSMzMgAPtxGpgB8yAC8yMFhEVH0TNBkyAD8aFi4BIU0qurl+FKsrMgAtC0IdGAtTSQwdCAIYMA8IMgIUBBwkBoEQSHhEJGiebEJhsYgJskAFJS+1fqZAJRVPn7oQanaFDDIm26ePNc7UHvpaRkARKum7wfIY2B0KDDIi0PQ0T5JdbvZDSKTkf6A4EUajIABMMOcJBI+AgYGQcHSIzGEwgU3wm3edwgXFGwHcYB+9UayAAekUsTi8ThCaNxpNaptUQA6AAcByZ5DZHNxIx5xP5mk2AFkJlYhVA4JE+JtfiV3jZ8PgeNCaAAWVHikgNSVFIA), whereas [the override example compiles](
https://www.typescriptlang.org/play?ssl=13&ssc=20&pln=12&pc=1#code/JYOwLgpgTgZghgYwgAgJIBMAycBGEA2yA3gFDLLDoBcyIArgLZ5TID0AVMgM4D2DKMYAXRdk7VgG4SAXxKhIsRCgBycftjyFS5EGog0uYKKADmbTjzAALaMkHDR4qbJIw6IBGGA8QyBFAg4SA0CAApKGnomaABKGgwQ-Ck3Dy8fPwCgiETQ3X4DI1M45FV1XAJk909vX39A4PL8XL0AeSgMAuMQMwAfWkZmYoTG5D7S7MbK1JqM+onNZv42ju5C7tH+6KghrBGxvUTiMgoYZFCwAE8ABwgeU7yIZfRkAF435AAiQy6TD5jkAJgOhQXxEWh6GhfNa-ZDSKTkQHA0EUajIABMsOcJCAA)

Is this behavior expected?

**Comment by fatcerberus** [comment] 2022-09-23 23:44
Just another brick in the wall for why I feel the v1 handbook was superior to v2…

**Comment by jcalz** [comment] 2022-09-23 23:47
Duplicate of #47627

**Comment by fatcerberus** [comment] 2022-09-23 23:48
Conditional return types and overloads are definitely not equivalent, and the former will usually be a lot more painful to use (as you see here).

**Closed** 2022-09-29 18:00 UTC
Labels: Duplicate
