### ISSUE TITLE
Broken d.ts generation for destructuring

### ISSUE THREAD

**Issue by Kinchkun** [Microsoft/TypeScript#4250] opened 2015-08-10 14:05 UTC
Hello,

we moved recently from TS 1.4 to TS 1.5 with Visual Studio 2013.

When we have the following class definition:

    export class ErrorClass {
        public foo({bar: number}) { }
    }

With the Option "Generate declaration files" and "combine javascript output into file" to true, the resulting declaration for this file will be:

    class ErrorClass {
        foo({bar: }: {
            bar: any;
        }): void;
    }

Which is syntactically incorrect: The first "bar" is missing the type specifier (and is of type number instead of any).

This will cause that projects using this declaration file fails to compile.

Can anyone reproduce this? Is there a fix available?

Kind regards,
Timo

**Comment by mhegazy** [comment] 2015-08-10 17:48
duplicate of #3912

**Closed by mhegazy** 2015-08-10 17:48 UTC

**Comment by mhegazy** [comment] 2015-08-10 18:21
Fix is in master now. please give it a try on the nightly build later tonight/tomorrow using `npm install typescript@next`
