### ISSUE TITLE
Circular reference ReturnType errors

### ISSUE THREAD

**Issue by andrew1007** [microsoft/TypeScript#35181] opened 2019-11-19 03:19 UTC
### Summary
Circular references don't work for a `ReturnType` circular reference

**TypeScript Version:**  3.8.0-dev.20191116

**Search Terms:**
Return type annotation circularly references itself
Return type circular reference
ReturnType circular 
**Code**

```ts
type cb = () => ReturnType<cb>
```

**Expected behavior:**
No compiler error
**Actual behavior:**
```
type ReturnType<T extends (...args: any) => any> = T extends (...args: any) => infer R ? R : any
Return type annotation circularly references itself.ts(2577)
```
[Playground link](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191116#code/C4TwDgpgBAxgRlAvFAFASiQPigJQsAVwCcA7AFXAgB55Mg)

**Comment by fatcerberus** [comment] 2019-11-19 08:41
“`cb` is a function type with no parameters and whose return type is the return type of `cb`.”  This is a complete tautology; what do you expect it to resolve to?  The recursion will never terminate and it can’t just manufacture a return type out of thin air...

**Comment by fatcerberus** [comment] 2019-11-19 09:07
Duplicate of #35181

**Comment by AlCalzone** [comment] 2019-11-19 16:05
@fatcerberus you had me confused for a second

**Comment by RyanCavanaugh** [comment] 2019-11-19 18:24
To be clear, the feature is "*sensible* circular type references are OK". Plainly circular types that require immediately resolution of themselves are not; I'm not sure what you're trying to do with this example.

**Closed by RyanCavanaugh** 2019-11-19 18:24 UTC
Labels: Working as Intended

**Comment by fatcerberus** [comment] 2019-11-19 18:45
Just to play devil's advocate, the only thing this type can reasonably model at runtime seems to be:

```ts
function f() {
    return f();
}
```

Which will never terminate, but will eventually smash the stack (assuming the engine doesn't support tailcalls).  I suppose the type could resolve to `never` if you *really* wanted to support it.  But that's not particularly useful when you can just annotate such functions as `never` in the first place.
