### ISSUE TITLE
Wrong Type Function Overload

### ISSUE THREAD

**Issue by fishcharlie** [microsoft/TypeScript#38186] opened 2020-04-25 18:37 UTC
**TypeScript Version:**  3.8.3

**Search Terms:**

- wrong type
- function overload

**Code**

```ts
enum SettingsOutput {
    request,
    response
}

interface Settings {
    return?: SettingsOutput;
    metadata: {[key: string]: any};
}

class User {
    save(data: string): boolean;
    save(data: string, settings: Settings & {return: SettingsOutput.request}): string;
    save(data: string, settings: Settings & {return: SettingsOutput.response}): boolean;
    save(data: string, settings?: Settings): string | boolean {
        if (typeof settings === "undefined" || settings.return === SettingsOutput.request) {
            return data;
        } else {
            return true;
        }
    }
}

const z: boolean = new User().save("hello");
console.log(z);
```

**Expected behavior:**

It to throw an error. Probably (but not sure) on the line `return data;` saying that you can't return `string` for type `boolean` since `settings` is undefined.

**Actual behavior:**

It prints `hello` in the log. Which makes 0 sense. There is no way that printing a `boolean` type should print a `string` type in the console.

Obviously it thinks that `z` is of type `boolean` because of `save(data: string): boolean;`. Which is correct. But the implementation of the function doesn't conform to that overload.

Also **important** to note there is a bug in the code I provided. But this is the exact thing that TypeScript should help guard against. I expected a `boolean` in this case, the function returned a `string` and TypeScript didn't catch it (which it should have).

**[Playground Link](https://www.typescriptlang.org/v2/en/play?ts=3.8.3#code/KYOwrgtgBAysAu8CWIDmBnA8meAHHUA3gFBRlQBOwAjmMOvADSnlXq4D2I6wxAvsWIp4wCgDMAhgGNgsBMjToiLMlXhgKIAPwAuOYhQZseHAG4VUCAgkATCfAl7CAbQDWwAJ56GFQwF09CRAPPnMBYikAGwl0JQBVHgplcih0CQA3YAAKOwdveF80AEo9ACMODkjgIPMUtMyc+0dUgsNGVPlDdD04A0UoADIiNQ0QHs7FY3x4ADoqWnp4PhKWwtRa8nrs3OafNo6+jHHDpSHCEc1jhSMcabn6Tm5gZbKKqpqLLca81f2eE90+mu6BWezQUAAPlBypVqiBkilyEgxFAsvAPLhgBwUf9gVAALyEqAAIjAIBswDEKGANmJkKhuK693UmgJRN6wKmOHuCwYRQRiMRF3hOw2gr4UGAkR4AsFrAQoygBToYsRAhSAnCUi4DCgAC9XrCggSoCBgAB3KAJURZIozL7EgAWUsiHGJRXM2u4sJmrtQWT1HqAA)**

**Related Issues:**

NA

**Comment by nmain** [comment] 2020-04-25 22:57
Duplicate of https://github.com/microsoft/TypeScript/issues/13225

**Closed** 2020-04-30 18:00 UTC
Labels: Duplicate
