### ISSUE TITLE
Generalize missing token hints to more constructs

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#35597] opened 2019-12-10 00:34 UTC
@Toxyxer recently fixed #34870. As mentioned:

_____

A great follow-up would be to make this work for

* `}` braces in
    * [ ] object literals
    * [ ] interfaces and object type literals
    * [ ] namespaces and augmentations
    * [ ] jsx expressions
* Parentheses in
    * [ ] parenthesized expressions
    * [ ] parenthesized types
    * [ ] argument lists
    * [ ] parameter lists
* Square brackets for
    * [ ] arrays
    * [ ] element accesses
    * [ ] indexed access types
    * [ ] tuple types
* Angle brackets for
    * [ ] type parameter lists
    * [ ] type argument lists
    * [ ] jsx tags
* [ ] For the `:` in ternaries, eg `a ? b : c` (maybe?)

_Originally posted by @DanielRosenwasser in https://github.com/microsoft/TypeScript/issues/34870#issuecomment-563504462_

**Comment by JvPy** [comment] 2019-12-10 16:25
I would like to help on this, but I may need help,If thats ok

**Comment by Akshaykataria08** [comment] 2019-12-12 17:47
I would also like to help on this. I want an entry point in the Open Source community

**Comment by sheonhan** [comment] 2020-01-20 14:26
Hi @DanielRosenwasser, I created a PR to make this work for closing braces here. https://github.com/microsoft/TypeScript/pull/36317

**Comment by sheon-han-zocdoc** [comment] 2020-03-12 23:14
Shouldn't this still be open since #36317 covers only one case?

**Comment by sheonhan** [comment] 2020-03-12 23:15
Shouldn't this issue remain open because #36317 only covers the first case?

**Comment by sandersn** [comment] 2020-03-13 23:34
Yep, sorry about that auto-close.

**Comment by ayazhafiz** [comment] 2020-03-20 17:44
Hints for more constructs that may have missing closing braces: https://github.com/microsoft/TypeScript/pull/37497.

**Comment by richa008** [comment] 2020-10-01 19:10
I would like to work on this as a part of Grace Hopper OSD.

**Comment by richa008** [comment] 2020-10-02 18:43
@DanielRosenwasser, I have 2 questions!!

1. From what I understand the issue is that `parseDiagnostics`  will not always return the most recent error message? In that case should the de-duping logic be removed?

2. As per your comment you want the `parseErrorAtPosition` to create a diagnostic outside of the `if (!lastError || start !== lastError.start)` and return it correct? And that needs to be used instead on the last entry in `parseDiagnostics`. What do you think of keeping a "currentDiagnostic" member variable on the Parser, setting the value in `parseErrorAtPosition` and using that value in the parseCloseBrace method? That would avoid a significant refactor.

**Closed** 2021-03-30 20:13 UTC
Labels: Domain: Error Messages, Domain: Related Error Spans, Experience Enhancement, PursuitFellowship, Suggestion, good first issue, help wanted
