### ISSUE TITLE
Problem when renaming file

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#8752] opened 2016-05-23 10:51 UTC
_From @Brakkar on May 20, 2016 9:47_

- VSCode Version: 1.1.1
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. Have vscode open with ts compiler running and watching.
2. Create a new ts file.
3. Rename this file

Problem: it didn't rename this file, it created another one, leaving the original one with the old name.
Also ignored js file now appear on the file browser for one of those file.

_Copied from original issue: Microsoft/vscode#6574_

**Comment by zhengbli** [comment] 2016-05-25 00:22
Does not repro with nightly. It may have been caused by file locking that we used to do, however that was fixed in master.

**Closed** 2016-05-25 00:23 UTC
Labels: API, Bug
