### ISSUE TITLE
Unresolved TypeScript definition paths (when using node-esm with `imports`)

### ISSUE THREAD

**Issue by schmannie** [microsoft/TypeScript#48639] opened 2022-04-11 06:16 UTC
Hey there!

# Bug Report

I'm writing a small, shared module to be imported in other TypeScript programs and I noticed a slight error with my generated TypeScript definitions (that might not be a bug, yet I'm unsure of how to fix).

I wanted to be able to reference my `src` folder in my project root as `#src`, so I added the required `imports` and `paths` in my `package.json` and `tsconfig.json` respectively.

After letting `tsc` generate my JavaScript, I'm able to run the project just fine -- however, importing my library in another TS project showed me that the TypeScript definitions were also using the Node.js-like `#src` path, but were obviously not resolving properly and couldn't be loaded.

What would be my best course of action to fix this? I understand that this type of module resolution is just something Node.js's doing (based off of `packge.json/imports`), so what would TypeScript's solution be to projects using this feature? Can I use custom, local imports in my `package.json` yet resolve emitted type definitions correctly?

### 🔎 Search Terms

`package.json esm imports type declarations emitted path incorrect resolve`

### 🕗 Version & Regression Information

- This can be a crash if: an ESM-based Node.js package, with `imports`, generates types that are consumed anywhere
- This has only been tested on the `TypeScript@4.7.0-dev.20220408` nightly build

### 💻 Code

Here are the relevant bits from my `package.json` file:
```json
{
  "type": "module",
  "exports": {
    ".": {
      "types": "./dist-types/index.d.ts",
      "import": "./dist-esm/index.js"
    }
  },
  "imports": {
    "#src/*": [
      "./dist-esm/*.js"
    ]
  },
  "devDependencies": {
    "typescript": "^4.7.0-dev.20220408"
  }
}
```
...and `tsconfig.json` file:
```json
{
  "compilerOptions": {
    "lib": [
      "es2022"
    ],
    "target": "es2022",
    "module": "es2022",
    "moduleResolution": "node"
    "esModuleInterop": true,
    "baseUrl": ".",
    "paths": {
      "#src/*": [
        "./src/*.ts"
      ]
    },
    "outDir": "./dist-esm",
    "declarationDir": "./dist-types",
    "declaration": true,
    "declarationMap": true
  }
}
```

### 🙁 Actual behavior

The resulting type declarations, `./dist-types/index.d.ts` in my project for example, has imports such as:
```ts
import { AuthMessageType, LoginRequestMessage, LoginSuccessMessage, LoginFailureMessage } from '#src/messaging/auth';
```
...and while generated JS in `./dist-esm` resolves `#src` just fine, TypeScript has no idea where to find the rest of my type definitions.

### 🙂 Expected behavior

I'm not sure to be honest. The TypeScript config's `paths` definition is technically working just fine, as my source files are mapped correctly -- what would the equivalent, or generally correct way of fixing this for just the type definitions be?

**Comment by IllusionMH** [comment] 2022-04-11 11:24
`"module": "es2022", "moduleResolution": "node"` doesn't have support for Node.js ESM features. You should use `node12` or `nodenext` instead
https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#ecmascript-module-support-in-node-js

**Comment by DanielRosenwasser** [comment] 2022-04-11 18:28
Is it possible to warn a user when we find a `package.json` that has an `exports` field but not a `"main"`, `"type"`, or `index.js`

**Comment by RyanCavanaugh** [comment] 2022-04-11 20:11
@weswigham thoughts?

**Comment by weswigham** [comment] 2022-04-11 21:22
If resolution outright fails, yeah, we should be able to. Most package authors have a `main`/`types` fallback, though.

**Comment by schmannie** [comment] 2022-04-11 22:53
> `"module": "es2022", "moduleResolution": "node"` doesn't have support for Node.js ESM features. You should use `node12` or `nodenext` instead https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#ecmascript-module-support-in-node-js

Hey! So if my `package.json` defines `#src/*` as `./dist-esm/*.js` -- how will my generated TypeScript definitions resolve them with just the `tsconfig.json` (with `paths` as configured above)?

I thought the node module resolution itself was working just fine, as even though my compiled JavaScript files were still using `#src` in imports, Node.js had no trouble locating any modules (thanks to the `package.json/imports` mappings I'm guessing). Now that I've switched to `nodenext` for my `moduleResolution` method, the generated JS files are using relative imports (they're fine as they're transformed correctly) -- but, the TypeScript path generation is still incorrect.

`./dist-types/index.d.ts`
```js
import { AuthMessageType, LoginRequestMessage, LoginSuccessMessage, LoginFailureMessage } from './messaging/auth.js';
```

**Comment by schmannie** [comment] 2022-04-11 23:09
> `"module": "es2022", "moduleResolution": "node"` doesn't have support for Node.js ESM features. You should use `node12` or `nodenext` instead https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#ecmascript-module-support-in-node-js

Hey! So if my `package.json` defines `#src/*` as `./dist-esm/*.js` -- how will my generated TypeScript definitions resolve them with just the `tsconfig.json` (with `paths` as configured above)? Setting my module resolution to `nodenext` wasn't enough, as my generated source files with `#src/*` imports were already working just fine. The issue arises when my TypeScript definition files start doing the same.

`./dist-esm/index.js`: WORKS FINE ALREADY ✔
```js
import { AuthMessageType, LoginRequestMessage, LoginSuccessMessage, LoginFailureMessage, } from '#src/messaging/auth';
```

`./dist-types/index.d.ts`: DOES NOT WORK FINE ❌
```ts
import { AuthMessageType, LoginRequestMessage, LoginSuccessMessage, LoginFailureMessage } from '#src/messaging/auth';
```

Another module importing this library shows all imported types as `any`.

---

I still don't know what the best solution might be, but my brain keeps falling back to the idea of another `paths`-like field that mirrors the `paths` entry but resolves them with type definition-specific paths, i.e.

```json
{
  "compilerOptions": {
    "paths": {
      "#src/*": [
        "./src/*.ts"
      ]
    },
    "typeDefPaths": {
      "#src/*": [
        "./dist-types/*.d.ts"
      ]
    }
  }
}
```

-but I don't know how philosophically compatible or elegant this solution would be.

**Comment by DanielRosenwasser** [comment] 2022-04-11 23:34
I appreciate you stress testing these features!

My personal recommendation would be to not split out your `.d.ts` and `.js` file emit; however, if that ends up being our only recommendation for library authors, I don't really think there's a reason for any library author to use the `"imports"` field (while it would still have some utility for application developers).

**Comment by weswigham** [comment] 2022-04-11 23:47
@schmannie You just need https://github.com/microsoft/TypeScript/pull/48563 - your non-relative imports point to the _output_ location for your project (correctly), but TS currently isn't smart enough to remap those output files back to the program's input files for nonrelative imports.

**Comment by schmannie** [comment] 2022-04-12 04:03
> I appreciate you stress testing these features!
> 
> My personal recommendation would be to not split out your `.d.ts` and `.js` file emit; however, if that ends up being our only recommendation for library authors, I don't really think there's a reason for any library author to use the `"imports"` field (while it would still have some utility for application developers).

I understand. Thank you very much! I've just opted to switch to regular imports as @weswigham suggest. Looking forward to seeing how #47925 pans out! Should I do anything in particular to this issue in the meanwhile?

**Comment by RyanCavanaugh** [comment] 2022-04-12 21:56
Tracking as duplicate of https://github.com/microsoft/TypeScript/issues/46762. Thanks!

**Closed** 2022-04-15 18:00 UTC
Labels: Duplicate
