### ISSUE TITLE
tsserver: version typescript@1.6.0-dev.20150825 crashes on simple example after consuming ~800MB of memory

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#4439] opened 2015-08-25 09:00 UTC
- install VSCode
- open folder
- point to use the latest tsserver installed using npm install typescript@next
{
	"typescript.tsdk": "C:\\Playgrounds\\testpass-08-25\\node_modules\\typescript\\lib"
}

- open simple TS file
class A {
	public foo() {
		this.foo();
	}
	
	public bar() {
		this.foo();
	}
}

Select foo > find all reference

Observe: tsserver crashes

**Comment by zhengbli** [comment] 2015-08-25 19:35
I cannot reproduce it on my machine. I got the references as the following:
![capture](https://cloud.githubusercontent.com/assets/1171301/9477158/9530aa88-4b25-11e5-827b-0e4d72825f65.PNG)

And my settings.json:
```json
// Place your settings in this file to overwrite default and user settings.
{
	"typescript.tsdk": "C:/Users/tinza/Desktop/testVsCode/node_modules/typescript/lib"
}
```

typescript package version: "1.6.0-dev.20150825"

**Comment by vladima** [comment] 2015-08-26 20:27
@dbaeumer when you specify path, do you use backslashes (like in your example) or forward slashes? If former one is true can you please try to use forward slashes and see if this will fix the problem?

**Comment by dbaeumer** [comment] 2015-08-31 08:41
@vladima: Mistake on my end: I do use backslashes bau of course it looks like this:

{
 "typescript.tsdk": "C:\\Playgrounds\\testpass-08-25\\node_modules\\typescript\lib"
 }

I tested it today and it still crashes for me. Even if I put forward slashes in. I do have a tsconfig.json in my workspace with the following content:

{
	"compilerOptions": {
		"target": "ES5",
		"jsx": "react",
		"module": "commonjs"
	}
}

Removing the tsconfig.json makes everything work as normal.

**Comment by dbaeumer** [comment] 2015-08-31 08:42
@vladima looks like GitHub changes \\ to \. So here is how it really looks like:

{
 "typescript.tsdk": "C:\\\\Playgrounds\\\\testpass-08-25\\\\node_modules\\\\typescript\\\\lib"
 }

**Comment by zhengbli** [comment] 2015-08-31 22:47
I still cannot repro the issue with the given tsconfig.json file. Can you share your folder somehow?

**Comment by dbaeumer** [comment] 2015-09-03 14:35
@zhengbli: send you a zip by mail.

**Comment by zhengbli** [comment] 2015-09-03 18:52
Thanks! I tried the project, and indeed cannot get the language functioning with the latest build (settings.json file in .vscode folder). However when I switch back to 0.7.2 (settings.json file in .settings folder), all the functions work fine when I point the typescript.tsdk to my local build of the latest bit from ts repo. So is that a vs code issue?

**Comment by mhegazy** [comment] 2015-09-03 22:52
looks like the issue was not a tsserver issue. closing for now. please reactive if this is not the case.

**Closed by mhegazy** 2015-09-03 22:52 UTC
Labels: Bug, High Priority, Needs More Info

**Comment by dbaeumer** [comment] 2015-09-07 07:02
@mhegazy: we fixed the issue in VSCode last week.

**Comment by johnpapa** [comment] 2015-09-21 02:09
I'm having an issue getting TS 1.6 set up in VS Code, too. The path below is correct, but none of the TS features work after I do this.

```
"typescript.tsdk": "~/.npm-packages/lib/node_modules/typescript/lib",
```

**Comment by vladima** [comment] 2015-09-21 02:16
I suspect that VSCode does not do tilde expansion (as it is feature of the shell, not OS). Will it work if you use full path to the home directory instead of ~?

**Comment by johnpapa** [comment] 2015-09-21 02:29
Ah, yes, this works `	"typescript.tsdk": "/Users/john/.npm-packages/lib/node_modules/typescript/lib",`
