### ISSUE TITLE
Incorrect indentation for tsx closing tags

### ISSUE THREAD

**Issue by louy** [Microsoft/TypeScript#6288] opened 2015-12-29 20:50 UTC
I wonder how this one slipped through all this time

When I hit "format code"...

```tsx
<div>
</div>
```

becomes

```tsx
<div>
  </div>
```

Can be seen in #6281. Possibly related to #6271.

**Comment by vladima** [comment] 2015-12-29 22:41
looks like a duplicate of #3838 and should be covered by #4398

**Closed by vladima** 2015-12-29 22:41 UTC
Labels: Duplicate
