### ISSUE TITLE
Arrow function name is not defined.

### ISSUE THREAD

**Issue by Podlas29** [Microsoft/TypeScript#15871] opened 2017-05-16 05:32 UTC
Hi everyone. Afaik arrow functions should have names copied from names of variables they are assigned to at creation time.

This is a problem for example with stateless React components, where function name is a basis for component name (which now in react development tools are seen as `Unknown`).
Babel sets arrow function names properly.

**Code**

```ts
const x = (a: number, b: number) => a + b;
console.log(x.name);
```

**Expected behavior:**
Compiles to 
```js
const x = function x(a, b) { return a + b; };
console.log(x.name);
```

Prints `"x"`.

**Actual behavior:**
Compiles to 
```js
const x = function (a, b) { return a + b; };
console.log(x.name);
```

Prints `undefined`.

**Comment by kitsonk** [comment] 2017-05-16 05:38
Dupe of #6433

**Comment by Podlas29** [comment] 2017-05-16 05:40
@kitsonk thanks. could not find one.

**Closed** 2017-05-16 07:39 UTC
Labels: Duplicate
