### ISSUE TITLE
tsc says types are not exported but they are

### ISSUE THREAD

**Issue by jasonkuhrt** [Microsoft/TypeScript#21447] opened 2018-01-29 01:00 UTC
`tsconfig.json`
```
{
  "compilerOptions": {
    "strict": true,
    "noImplicitReturns": true,
    "target": "es2015",
    "module": "commonjs",
    "outDir": "./build"
  },
  "include": ["./repro.ts"],
  "exclude": ["./source/**/*"]
}
```

Working:
```
$ /Users/jason.kuhrt/projects/ssense/experiment/node_modules/.bin/tsc --project ./tsconfig.json --declaration --outDir build
✨  Done in 1.98s.
```
```ts
export interface Bar {
  a: boolean
}

export interface Foo {
  bar: Bar
}

const f = (x: any): Foo => {
  return { bar: { a: false } }
}

export { f }

```

Not working:
```
$ /Users/jason.kuhrt/projects/ssense/experiment/node_modules/.bin/tsc --project ./tsconfig.json --declaration --outDir build
repro.ts(9,7): error TS4025: Exported variable 'f' has or is using private name 'Foo'.
```
```ts
interface Bar {
  a: boolean
}

interface Foo {
  bar: Bar
}

const f = (x: any): Foo => {
  return { bar: { a: false } }
}

export { f, Bar, Foo }

```

I Don't see mention of support for `export { A, B, C }` style in https://www.typescriptlang.org/docs/handbook/modules.html but nor do I see it mentioning lack of support. So I assume there is support? Maybe I missed something.

**Comment by weswigham** [comment] 2018-01-30 19:22
What version are you seeing issues in? This doesn't repro on `master`, so I think this is likely a duplicate of one of the issues fixed by #19929.

**Comment by jasonkuhrt** [comment] 2018-01-31 15:40
@weswigham 

```
❯ yarn -s build
$ rm -rf build
source/Experiment/index.ts(18,12): error TS4033: Property 'variant' of exported interface has or is using private name 'Variant'.

❯ yarn -s tsc --version
Version 2.6.2
```

**Comment by mhegazy** [comment] 2018-01-31 17:40
@jasonkuhrt can you try with `typescript@2.7` instead?

**Comment by jasonkuhrt** [comment] 2018-02-01 03:42
@mhegazy works!

```
❯ yarn -s build && yarn -s tsc --version
$ rm -rf build
Version 2.7.1
```

**Closed** 2018-02-01 17:11 UTC
Labels: Bug, Domain: Declaration Emit
