### ISSUE TITLE
Feature Request: use type narrowing information to infer return type

### ISSUE THREAD

**Issue by tomcumming** [Microsoft/TypeScript#18601] opened 2017-09-20 16:13 UTC
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
type Test = { a: number, b: string };

function foo<K extends keyof Test>(k: K, inp: Test[K]): Test[K] {
    if (k === 'a')
        return 123; // ok
    else if (k === 'b')
        return 123; // wrong, Test[K] is a string here
}
```

**Expected behavior:**
A type error in the `k === 'b'` branch.

**Actual behavior:**
No type error. 

Could it be possible to use the infered type of `k` (`'b'`) to specify the correct return type `Type['b']`(`string`) ?

**Comment by tomcumming** [comment] 2017-09-20 16:21
Also i feel like the type of `Type['a' | 'b']` should be `string & number` rather than `string | number`

**Comment by mhegazy** [comment] 2017-09-21 16:59
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/17859

**Comment by mhegazy** [comment] 2017-10-05 18:18
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-05 18:18 UTC
Labels: Duplicate
