### ISSUE TITLE
[Possible Bug?] Different behavior when exporting with full syntax

### ISSUE THREAD

**Issue by bigopon** [Microsoft/TypeScript#16994] opened 2017-07-07 01:19 UTC
**TypeScript Version:**  2.4.1

Sorry if this is not a bug, but it looks like so to me.

**Code**

```ts
// module_a.ts
export class Abc {}
class Def { }

export { Def as Def }

// module_b.ts
import  {
    // Here if you type 'Abc', it gets the suggestion that you are importing a class
    // Here if you type 'Def', it shows import 'Def'
}
```

**Expected behavior:**
Importing `Abc` & `Def` should have same `class` suggestion.

**Actual behavior:**
Only importing `Abc` has `class` suggestion.

**Comment by mhegazy** [comment] 2017-08-24 19:34
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/14003. we are not showing the kind of an alias based on what it aliases but based on weather it is an alias or not.

**Comment by mhegazy** [comment] 2017-09-08 16:56
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-08 16:56 UTC
Labels: Duplicate
