### ISSUE TITLE
TS2365 

### ISSUE THREAD

**Issue by zq8024** [Microsoft/TypeScript#16854] opened 2017-06-30 08:28 UTC
code:
`function(){
return 1 == 0;
}`

compile,then typescript show TS2365 error

**Comment by kitsonk** [comment] 2017-06-30 08:46
Essentially a dupe of #12794 and works as intended.

TypeScript is intentionally smart enough to know that this is illogical code and you are making an invalid comparison.

**Comment by zq8024** [comment] 2017-06-30 09:44
I think it is a warnning,  not a error, because it can execute.
that function is auto generated by tool.

**Comment by kitsonk** [comment] 2017-06-30 11:45
That tool is generating illogical code and should be fixed.

Please see this question on [StackOverflow](https://stackoverflow.com/questions/41750390/what-does-all-legal-javascript-is-legal-typescript-mean).  TypeScript does not have, intentionally, the concept between errors and warnings.  You can always choose to ignore the errors as it does not effect the emit.

**Comment by jcalz** [comment] 2017-06-30 14:17
I don't know that it helps much to dismiss the generated code as illogical; `1 == 0` has an obvious meaning (`false`), and makes sense even to TypeScript pre-2.1.  TypeScript 2.1 and up interprets `1` and `0` more narrowly than the tool author probably intended.  Inferring literal types (#10676) in this case is a [feature](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#literal-types-are-inferred-by-default-for-const-variables-and-readonly-properties) that presumably catches enough legitimate errors to justify the occasional pain point like this.

@zq8024: As mentioned, you can ignore the error if you want.

If you have any control over the output of the tool and if the tool is supposed to be outputting TypeScript, then something like 
```ts
… (function () { return <number>1 == 0; }
```
would more clearly communicate to the type checker the intent of the comparison.

If you don't have any control over the output of the tool, or if the tool is only supposed to output plain JavaScript as opposed to TypeScript; and you don't want to ignore errors, maybe having TypeScript check and compile it isn't a great idea?  Without knowing more about your build configuration, I don't know if it makes sense, but could you reconfigure it to get the tool and the TypeScript compiler out of each other's way?

**Comment by mhegazy** [comment] 2017-08-17 17:25
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-08-17 17:25 UTC
Labels: Working as Intended
