### ISSUE TITLE
Exhaustive check fails to narrow type when union has only 1 type

### ISSUE THREAD

**Issue by Freak613** [microsoft/TypeScript#43056] opened 2021-03-03 06:29 UTC
**TypeScript Version:** nightly

 **Code**
 
 ```ts
   type SkippedError = {
    tag: "Skipped"
  };

  const error: SkippedError = {} as any;

  switch (error.tag) {
    case "Skipped":
      const a1: SkippedError = error;
      return 1;
    default:
      const a2: never = error;
      return 0;
  }
 ```
 
 **Expected behavior:**
Exhaustive check should narrow `error` type to `never` for `a2`.
 
 **Actual behavior:**
 `Type 'SkippedError' is not assignable to type 'never'.(2322)`
 
The type of error at the `a2` is still `SkippedError`

* I included happy-path variant of same code in playground link, where union for `error` has 2 types and code works correctly.
* The problem reproduces not only for literal types, but also with classes.
* Trying to narrow type with `if` has same result.
* Only working solution in this case is checking classes with `instanceof`, but can not be applied for literals.
 
 **Playground Link:** [Playground Link](https://www.typescriptlang.org/play?ts=4.2.2#code/MYewdgzgLgBAZgQwJYBsCmATASgVzDAXhgAoBKQgPhgG8BYAKBiagE8AHNGAZQGsk2OGAKIAnESBGEaDJswQBzAFwwARL36CVMmAF8A3A22hIsNGInL1AzKPGSi1HTAQRnYFgfraIAdyRRgAAsSMzsAOigFcjpGWWAXTjU+awwVRW1ZGGNoZwBGS2TBWwkpUIlPTKYRNCgcEXxcitkMNEQcFCh02Mzs2AQAJmUwNAA3M1LzESbM6tr6mAAGJp0GFa96XpgIHGBgNAgIXHwiMkppWNYObkKbSakYzMilVStNbX1DC-ZOADkQKFetzs9wyMCeyhUf1ggNS708RnAOTKIgKGiBJQAPjAoTDivYaE4XG4PJ8mL5-EEQpMIlFzj0Ei8bqkupUsoi+vlrmjhHciMjprJZnUGgL4hBElCuSk0qCmJsBsocUy8RM7AKqjVhTBGqCWm0OizKvKAMxDUbjPmTdUwIXzJbvVYMIA)

**Comment by MartinJohns** [comment] 2021-03-03 09:30
> when **union** has only 1 type

What union? You don't have a union type.

Duplicate of #16976.

**Closed** 2021-03-03 09:43 UTC
