### ISSUE TITLE
Type guards: support `true & (maybe is X)` 

### ISSUE THREAD

**Issue by krisdages** [Microsoft/TypeScript#31021] opened 2019-04-18 19:10 UTC
## Search Terms

type guards union assert

## Suggestion

I'd like to be able to define a type guard's return type as `true & (maybe is X)`
and have any statements after calling the type guard function recognize that the value is of the correct type.

Technically `false & (maybe is X)` should probably be supported also if this is implemented, but that isn't in my particular use case.
## Use Cases

The use case is an assertion helper
```
Assert.isType<T>(predicate <-- type guard for T, maybe: any, message: string): maybe is T {
   if (!predicate(maybe)) {
      throw Error(message);
   }
}
```
I'd like to be able to use `maybe` after the call since the Assertion will throw if the value is not of the right type.
.

## Examples
```
Assert.isType<T>(predicate <-- type guard for T, maybe: any, message: string): true & (maybe is T) {
   if (!predicate(maybe)) {
      throw Error(message);
   }
}
...
function timesTwo(num: number) {
    Assert.isType(maybe => typeof maybe === "number", num, "Non-numeric value passed where number was expected."));

    return num * 2;
}

const val: any = "two";
console.log(timesTwo(val));	
```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2019-04-18 19:17
Duplicate of #17760.

**Comment by jcalz** [comment] 2019-04-18 19:18
Yeah, seems [familiar](https://github.com/Microsoft/TypeScript/issues/17760#issuecomment-322246015) 🙂

**Comment by RyanCavanaugh** [comment] 2019-04-18 20:22
#15048

**Comment by krisdages** [comment] 2019-04-18 21:46
@jcalz Thanks for pointing out your comment ... I saw that issue before I posted but I didn't see the syntax discussion below and for some reason the description didn't register as covering the same use case. 

Sorry for the dupe. :)

**Closed** 2019-04-21 18:00 UTC
Labels: Duplicate
