### ISSUE TITLE
Allow omitting generic when it can be inferred from argument value.

### ISSUE THREAD

**Issue by dzek69** [microsoft/TypeScript#52939] opened 2023-02-23 17:59 UTC
# Suggestion

TypeScript should allow to omit to specify generic if it's type matches an argument.

## 🔍 Search Terms

infer argument generic, single generic required, omit single generic

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Let's assume I want something like that (this is oversimplified example of something I wanted to achieve):

```typescript
class DataStorage<Type, Name extends string> {
    private data: Type | undefined;

    public readonly name: Name;

    public constructor(n: Name) {
        this.data = undefined;
        this.name = n;
    }

    public set(d: Type) {
        this.data = d;
    }

    public get() {
        return this.data;
    }
}
```

Some kind of generic data storage class, where I can specify the data type it holds, or just leave it and have a data storage with type of unknown.

When I don't pass any generics when calling the constructor the `name` property is correctly inferred and data type is unknown:

```typescript
const x = new DataStorage("x");
x.set(1); // I can set whatever I want
const val = x.get(); // val is unknown
const name = x.name; // name is literal "x"
```

Now when I want to pass just the type of data the storage can hold, like that:

```typescript
const y = new DataStorage<number | boolean>("y");
y.set(1);
const val = y.get(); // val is number | boolean | undefined
const name = y.name; // name is just string, not literal "y"
```

TypeScript gives me `TS2558: Expected 2 type arguments, but got 1.` error. So it's either all or nothing. `// ts-ignore` won't help here as `y.name` cannot be inferred anyway, plus this is a public facing API, I don't want developers of this class to use `// ts-ignore` everytime

Of course I can just pass both generics:

```typescript
const y = new DataStorage<number | boolean, "y">("y");
y.set(1);
const val = y.get(); // val is number | boolean | undefined
const name = y.name; // name is "y"
```

But this requires repetition that could be avoided in this case (as passing nothing clearly shows).

Using defaults is not helpful as well:
```typescript
class DataStorage<Type, Name extends string = ""> {
 // ...
}

const y = new DataStorage<number | boolean>("y");
// TS2345: Argument of type '"y"' is not assignable to parameter of type '""'
```

## 📃 Motivating Example

It lets users to have an automatic typesafety without repetition.

## 💻 Use Cases

Use case is explained in `Suggestion` section.

Shortcomings? I don't see any.

Such tweak looks like totally possible to implement, of course it should only allow to omit these generics that are last on the list (similar to when I'd give default value for first generic and not second - typescript errors with `TS2706: Required type parameters may not follow optional type parameters.` in such case) and these that are specified in arguments list.

Implementing it should only make the currently invalid code to compile, never other way around.

My current workaround is repetition. I require users to repeat the `name` in generics and then in arguments.

**Comment by MartinJohns** [comment] 2023-02-23 18:20
Duplicate of #26242.

**Closed** 2023-02-23 18:45 UTC
