### ISSUE TITLE
Module augmentation seems to break when namespace and class have same name

### ISSUE THREAD

**Issue by entropitor** [microsoft/TypeScript#52933] opened 2023-02-23 10:29 UTC
# Bug Report

### 🔎 Search Terms

Module Augmentation
Namespace
Class
Same name
Jupyterlab

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries

### ⏯ Playground Link

Doesn't work because it's about module augmentation.

### 💻 Code

```ts
// index.ts
    import {CodeMirrorEditor} from '@jupyterlab/codemirror';
    const newEditor = new CodeMirrorEditor({
      config: {
        myExtraOption: true,
      },
      host: {} as any,
      model: {} as any,
    });

```

The above fails because `myExtraOption` is an option not officially in `@jupyterlab/codemirror`.

However, when I add

```ts
// jupyterlab-codemirror.d.ts
import '@jupterlab/codemirror';

declare module '@jupyterlab/codemirror' {
  declare namespace CodeMirrorEditor {
    interface IConfig {
      myExtraOption: boolean;
    }
  }
}
```

it starts failing instead with

```
typescript: Cannot use namespace 'CodeMirrorEditor' as a value. [2708]
```

it seems that the declaration file somehow starts shadowing the class `CodeMirrorEditor` which is also in `@jupyterlab/codemirror`

### 🙁 Actual behavior
Declaration merging is hiding the class

### 🙂 Expected behavior
The namespace is extended while the class is still visible

**Comment by egonSchiele** [comment] 2023-03-05 23:43
@entropitor , I can't reproduce this issue. Could you clone [this repo](https://github.com/egonSchiele/ts-52933) and see if you still get the issue? It's a react app that includes `@ jupyterlab/codemirror` (I took a guess at how your code is structured). The code matches your code above (see [here](https://github.com/egonSchiele/ts-52933-react/blob/main/src/index.ts) for example).

I also created a [simpler version](https://github.com/egonSchiele/ts-52933-simple) that doesn't include codemirror or react. I have a module `animals` [here](https://github.com/egonSchiele/ts-52933-simple/blob/main/animals.ts), which exports a class and a namespace, both with the same name. The namespace includes an interface. I then augment the interface in that namespace [here](https://github.com/egonSchiele/ts-52933-simple/blob/main/animals.d.ts). [Here](https://github.com/egonSchiele/ts-52933-simple/blob/main/test.ts) I use the augmented interface, and it works fine.

My guess is you are somehow importing `CodeMirrorEditor` the namespace instead of `CodeMirrorEditor` the class.

As a side note, I didn't see a test covering this specific type of declaration merging. Should I add a `mergedDeclarations8` similar to [this test](https://github.com/microsoft/TypeScript/blob/main/tests/baselines/reference/mergedDeclarations7.js)?

**Comment by entropitor** [comment] 2023-03-06 09:56
@egonSchiele Is it possible the repo is still private?

**Comment by entropitor** [comment] 2023-03-06 10:02
Yeah, it seems that on the latest version, it's not reproducible. Sorry for bothering you 😭

**Closed** 2023-03-06 18:46 UTC
Labels: Bug, Help Wanted, Good First Issue
