### ISSUE TITLE
Want to have a "when" like in kotlin a switch were all values are mandotary

### ISSUE THREAD

**Issue by Mansi1** [microsoft/TypeScript#52156] opened 2023-01-09 10:01 UTC
# Suggestion

## 🔍 Search Terms

When, switch mandatory  

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

It would be nice to have an transpile check that some cases are missing in switch case.
The keyword when is already used so we can use strict before switch case, that everyone know thats an special switch.

In runtime this keyword will be removed. 
## 📃 Motivating Example
if we have an type | enum and want to switch over all known types:

```ts
type status = 'none' | 'loading' | 'done' | 'intermediate'
// missing Intermediate dont show any compile errors
switch (status){
 case 'none':
  ...
 case 'loading':
  ...
 case 'done':
  ....
 default:
  ....
}
```
```ts
type status = 'none' | 'loading' | 'done' | 'intermediate'
strict switch (status) {
 case 'none':
  ...
 case 'loading':
  ...
 case 'done':
  ....
}
// get compiler error because types are missing
```

## 💻 Use Cases

###What do you want to use this for?
Dont forget states in switch cases any more, will make the code more robust for changes and give us an hint that we are missing something.

What workarounds are you using in the meantime?
Write nicer code instead of using a Record as map

**Comment by MartinJohns** [comment] 2023-01-09 11:16
Duplicate of #33160.

**Comment by MrAndersen1** [comment] 2023-01-09 12:18
When I want this behaviour I usually assign to never in default.
```typescript
type Status = 'none' | 'loading' | 'done' | 'intermediate'
declare let s: Status;
let neverHere: never;
switch (s) {
    case 'none':
        break;
    case 'loading':
        break;
    case 'done':
        break;
    default:
        neverHere = s;
        break;
}
```
You can then hover over 's' to see the values you forgot to handle.

I'm pretty sure I picked it up from this tracker somewhere but I don't remember to whom I should give credit.

**Comment by RyanCavanaugh** [comment] 2023-01-09 17:20
There are several ways to do this already (using `never` in the `default` branch). I don't think this merits a new top-level syntax production.

**Closed** 2023-01-10 13:11 UTC
Labels: Suggestion, Declined
