### ISSUE TITLE
Narrowed types do not flow into callback functions

### ISSUE THREAD

**Issue by kolpav** [microsoft/TypeScript#44869] opened 2021-07-02 16:00 UTC
# Bug Report

Previous discussion https://github.com/microsoft/TypeScript/issues/37255#issuecomment-779665895

Title is borrowed from @danielrentz https://github.com/microsoft/TypeScript/issues/37255#issuecomment-779668433  I don't know if its accurate description of the problem.

### 🔎 Search Terms

None

### 🕗 Version & Regression Information

Any

### ⏯ Playground Link

[Playground](https://www.typescriptlang.org/play?jsx=4&ts=4.1.0-dev.20201028#code/JYWwDg9gTgLgBAbzgMQK4DsDGNgXQYQnDwFN0YAaOVAZxIFkSQI4BfOAMyiLgHIoSAQ2y8AsACgJJAB6RYcYORJQOwknABCqGDDwAFbmBqIJcODWAAvEgH4AXHxohecAD58ARoLov3vADYA5mLirBJSstDwmHg08Fo6eA5oWDh4hMToZDAAPAm66AYQRgB8cAC8cGCGxuVlCKZVNQB0FtZwNjaVvF4+jTHoceZWJPj+3jQAcoIgJLXUdIzMABTLAJQV9Y1mAjCoUOgm4mYn5iAOvGDSALQAzFUAntcATHAwMjDXTrwU2ye9JAuV2uABZHi83h8vs5fsdTnAgkCbmCwE9Xu9pJ8ASFTqwANrVYo0VojAC6jVYVAJLTaJFJa3CcN2+0Oyz+OQ82gKfzMMAeYBI5QARJzEughTy4JhxjQpjNBQhaWMJtNZjQwnCzCVJfk8JDMeyAPSigrauEM0ISIA)
### 💻 Code

```ts
import { FunctionComponent, useMemo } from 'react'

export interface ButtonProps {
  size?: 'sm' | 'base' | 'lg'
}

export const Button: FunctionComponent<ButtonProps> = props => {
  props.size ??= 'base'
  const sizeClassNames = useMemo(() => {
    return {
      sm: 'px-3 py-2 text-sm',
      base: 'px-4 py-2 text-sm',
      lg: 'px-4 py-2 text-base'
    }[props.size] // << Type 'undefined' cannot be used as an index type.(2538)
  }, [props.size])

  return (
    <button
      type="button"
      className={sizeClassNames}
    >
      Button text
    </button>
  )
}

```

### 🙁 Actual behavior

Type 'undefined' cannot be used as an index type.(2538)

### 🙂 Expected behavior

`props.size` should not be considered as `undefined`

**Comment by MartinJohns** [comment] 2021-07-02 16:35
Another duplicate of #9998.

**Closed** 2021-07-02 19:37 UTC
Labels: Duplicate
