### ISSUE TITLE
Class method with `this` typing cannot access private or protected members

### ISSUE THREAD

**Issue by krryan** [microsoft/TypeScript#13815] opened 2017-02-01 16:19 UTC
**TypeScript Version:**  2.2.0-dev.20170116

**Code**

```ts
class Foo {
    constructor(
        protected bar: string | null,
        protected baz: number
    ) {}

    doThing(this: Foo & { bar: string }) {
        return this.bar.length > 0 ? this.baz : -1;
    }
}
```

**Expected behavior:**
Compiles without error.

**Actual behavior:**
>Property 'baz' does not exist on type 'Foo & { bar: string; }`.

Notably, though, even if `baz` is `public`, attempting to use `doThing` here even from within another method fails:
```ts
class Foo {
    constructor(
        protected bar: string | null,
        public baz: number
    ) {}

    doThingIfYouCan() {
        if (this.bar != null) {
            return this.doThing(); // error here
        }
    }

    doThing(this: Foo & { bar: string }) {
        return this.bar.length > 0 ? this.baz : -1;
    }
}
```

Here the error is
>The 'this' context of type 'this' is not assignable to method's 'this' of type 'Foo & { bar: string; }'.
>[...]
>Property 'bar' is protected in 'Foo' but public in type '{ bar: string; }'.

This is a very similar problem, where the `this` typing on `doThing` requires that `bar` is public even though both `canDoThing` and `doThing` should have access to it.

My use-case here is that I have a method that is currently only being called in non-null cases, and only makes sense to call in non-null cases, so I'm currently throwing in a null case (that should never happen). But I would like to enforce that at compile time.

**Comment by jakebailey** [comment] 2023-07-06 23:58
This issue had the same root cause as #11454 and is now fixed in TS 3.9+ (see linked issue).

**Closed by jakebailey** 2023-07-06 23:58 UTC
Labels: Bug
