### ISSUE TITLE
@ts-expect-error snapshotting mechanism

### ISSUE THREAD

**Issue by devinrhode2** [microsoft/TypeScript#50645] opened 2022-09-05 20:15 UTC
# Problem:

`// @ts-expect-error` comments can hide whether or not an error has _changed_ or _mutated_. It's also possible that a line had 1 error, but now has 2 errors.

<sub>Although IMO it's best practice to isolate the smallest of piece of code underneath a `// @ts-expect-error`, this doesn't actually solve the problem, just reduces the odds of it happening.</sub>

# ⭐ Suggestion

Create a "snapshotting" syntax for @ts-expect-error comments.

Syntax proposals:
1. Enforce that only one appear appears on the given line, and it's error code has a 100% match.
```ts
// @ts-expect-error-obj { file: 'ui/root.tsx', lineNo: 12, columnNo: 4, errorMessage: [... string array ...]
```
Advantages: if you make a change which _slightly_ affects this line, you'll know, cause you'll get an error to update this inline snapshot.
2. List error codes:
```ts
// @ts-expect ts1234, ts9876
```
3. Additionally, to help users learn the tradeoffs around certain tsconfig compilerOptions, snapshots could include the related tsconfig setting:
```ts
// @ts-expect strictNullChecks ts1234, exactPropertyThings ts9876
```
Hovering over "ts1234" could show the full error.

Alternatively, there could be full "snapshot" files which are stored as sibling files:
```
./foo.tsx
./foo.ts-errors.txt
```

Context:
I'm in a new project with 500-5000 ts errors, `ts-migrate`'s `ts-ignore` script was creating syntax errors around some styled components. Checking/fixing those manually is not feasible. We'll probably just store all errors from `tsc` in a file and enforce that this file is kept up to date with a ci check. This just helps us understand how our changes are fixing the rest of the codebase.

## 🔍 Search Terms

```
"@ts-expect-error" snapshotting snapshot
```

## ✅ Viability Checklist

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) (I think it does).

## 📃 Motivating Example

TODO, see above description of issue

## 💻 Use Cases

TODO

**Comment by jakebailey** [comment] 2022-09-07 18:21
I think this is functionally a duplicate of #19139.

**Comment by devinrhode2** [comment] 2022-09-07 20:37
Hmmmm, more or less, yeah.

**Closed** 2022-09-12 18:00 UTC
Labels: Duplicate
