### ISSUE TITLE
Constructor Uint8Array requires 'new' when targeting ES5

### ISSUE THREAD

**Issue by MicahZoltu** [microsoft/TypeScript#29910] opened 2019-02-14 04:41 UTC
**TypeScript Version:**  typescript@3.4.0-dev.20190213

**Search Terms:**
Constructor Uint8Array requires 'new'
TypedArray requires 'new'
Uint8Array requires 'new'

**Code**
```json
{
	"compilerOptions": {
		"target": "es5",
		"lib": [ "es5", ],
	}
}
```
```ts
abstract class Bytes extends Uint8Array {
	static factory<T extends typeof Bytes & { new() }>(this: T): InstanceType<T> {
		return (new this()) as InstanceType<T>
	}
}

class Bytes4 extends Bytes {
	constructor() { super(4) }
}

const bytes4 = Bytes4.factory()
```

**Expected behavior:**
Either a compiler error giving me better insight into why I cannot instantiate a Uint8Array in this way, or it working at runtime.

**Actual behavior:**
At runtime:
```
TypeError: Constructor Uint8Array requires 'new'
source-map-support.js:444
    at Bytes4.Uint8Array (<anonymous>)
    at Bytes4.Bytes [as constructor] (.\test\test.ts:17:42)
    at new Bytes4 (.\test\test.ts:8:18)
    at Function.Bytes.factory (.\test\test.ts:3:11)
    at Object.<anonymous> (.\test\test.ts:11:23)
    at Module._compile (internal/modules/cjs/loader.js:686:14)
    at Module.m._compile (.\test\node_modules\ts-node\src\index.ts:413:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (.\test\node_modules\ts-node\src\index.ts:416:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

**Playground Link:** [Playground](https://www.typescriptlang.org/play/#src=abstract%20class%20Bytes%20extends%20Uint8Array%20%7B%0D%0A%09static%20factory%3CT%20extends%20typeof%20Bytes%20%26%20%7B%20new()%20%7D%3E(this%3A%20T)%3A%20InstanceType%3CT%3E%20%7B%0D%0A%09%09return%20(new%20this())%20as%20InstanceType%3CT%3E%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Bytes4%20extends%20Bytes%20%7B%0D%0A%09constructor()%20%7B%20super(4)%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20bytes4%20%3D%20Bytes4.factory()%0D%0A)

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/24195
https://github.com/Microsoft/TypeScript/issues/1168

Note: I don't actually understand the error, so I apologize if this isn't actually a bug in TypeScript.  I think it has to do with Uint8Array being special and not actually a class (even though it looks like a class).  You _can_ do `new Uint8Array(4)` and `new Uint8Array()` in node and browser, but for some reason you cannot do `Uint8Array.apply({}, 4)`.

Note2: This works if you target ES2015 or higher.

**Comment by kitsonk** [comment] 2019-02-14 05:12
You cannot extend built-ins in ES5.  Classes in theory don't exist in ES5 (let alone Uint8Arrays) and so TypeScript tries to down emit items that look like classes in a way that is not compatible with extending built in.  When you target ES2015 and beyond, TypeScript doesn't do a down emit, and therefor the extension is passed directly to the runtime and does not cause an error.

There is no logic in TypeScript to be able to differentiate between a built in and any other class, therefore TypeScript always tries to down emit the extension the same way.  If the Uint8Array was a polyfill, because you were really running in a ES5 environment, the extension would likely work.

**Comment by MicahZoltu** [comment] 2019-02-14 05:29
Oh, so the real problem here is that `Uint8Array` should not be available in `lib: [ "es5" ]` and I should have received a compiler error telling me as much?

**Comment by DanielRosenwasser** [comment] 2019-02-14 18:41
No it exists. The issue is that there's no way to correctly extend built-ins without `Reflect.construct` which is ES6.

**Comment by MicahZoltu** [comment] 2019-02-15 00:37
According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array it wasn't added until es2015.

**Comment by kitsonk** [comment] 2019-02-15 03:15
While it wasn't added to the language specification until ES2015, it was present in IE10+ and most other browsers, so TypeScript has traditionally included it in the ES5 typings.  It is highly unlikely that you would find an ES5 environment that didn't support it.  Still, _all_ built ins were not extensible in ES5.  It was something that was only addressed in ES2015.

**Comment by MicahZoltu** [comment] 2019-02-15 03:27
Is there some reason that the compiler can't error/warn when someone tries to extend a built-in while targeting ES5?

**Comment by kitsonk** [comment] 2019-02-15 10:26
TypeScript has no concept of what is a built in and what isn't.

It would be a guess on my part, implementing a system would be complicated and only benefit a very narrow use case (extending builtins when targeting ES3/ES5).

**Closed** 2019-07-13 00:01 UTC
Labels: Question
