### ISSUE TITLE
[1.30.0] Rename ES6 object-property inside method-parameter not working

### ISSUE THREAD

**Issue by Friksel** [microsoft/TypeScript#29029] opened 2018-12-13 08:52 UTC
After updating Vs Code to 1.30.0 renaming objects-properties used as method-parameters in an ES6 class don't rename as they should.

![rename-not-working](https://user-images.githubusercontent.com/3089978/49926828-c78ccb80-febc-11e8-8408-e5e5b96d5496.gif)

- VSCode Version: 1.30.0
- OS Version: Windows 10

Steps to Reproduce:
1. Have a class with an object as param
2. Rename one property of that object

Does this issue occur when all extensions are disabled?: Yes

**Comment by weswigham** [comment] 2018-12-14 22:03
I don't think this is a bug - we rename the name used within the class, but not the name used outside of it, since that's a separate symbol (though a destructuring operation ties them together).

**Comment by weswigham** [comment] 2018-12-14 22:09
Like, this is so intentional that it's listed as a feature on the release announcement: https://code.visualstudio.com/updates/v1_30#_renames-handle-jsts-destructuring-properly

**Comment by Friksel** [comment] 2018-12-15 07:51
Yes this is a bug. It's unwanted behaviour and it's doing something completely different then renaming. Look at the video in my post. This is not renaming, this is adding something and changing a structure into something we don't want in Javascript and doesn't work.

The link you sent is clearly a different situation; that's about interfaces. Next to that renaming looks to work on that example, but isn't in this situation in 1.30.0.

This is how it was working in 1.29.1 and is suppose to work:
![renaming-in-1 29 1](https://user-images.githubusercontent.com/3089978/50040562-14e87480-0046-11e9-83b1-c3b2953fff33.gif)

**Comment by Friksel** [comment] 2018-12-27 08:40
Still happening in 1.30.1. Any news on this?

**Comment by justingrant** [comment] 2019-02-01 21:33
Dupe of #29238?

**Comment by justingrant** [comment] 2019-02-11 23:17
@Friksel - Looks like this PR will be included in TypeScript 3.4 which should be out in a month or two.

**Comment by Friksel** [comment] 2019-02-12 01:50
Thanks for the updates guys @justingrant @weswigham . Great it's changing!

**Closed** 2019-07-16 18:25 UTC
Labels: Awaiting More Feedback, Needs Proposal, Suggestion

**Comment by Friksel** [comment] 2019-07-20 11:28
@justingrant  I see the PR you are talking about is merged to master a while ago and this issue is closed, but in version 1.36.1 the result I get is still exactly the same as when I opened this issue, so so far I don't see any change.

Do I perhaps need to change some setting to make this work as expected?

**Comment by Friksel** [comment] 2019-07-20 11:37
@justingrant  I see the PR you are talking about is merged to master a while ago and this issue is closed, but in version 1.36.1 the result I get is still exactly the same as when I opened this issue, so so far I don't see any change.

Do I perhaps need to change some setting to make this work as expected?

**[edit]** Ah, my bad. I just in the commit message of the PR a setting has indeed been added. For future reference for people having the same issue:

* **Via Settings UI**: The setting is called `Javascript --> Preferences --> Rename Shorthand Properties` in the UI and if you remove the tick it's working as expected in Javascript.
* **Via settings.json**: Or just add `"javascript.preferences.renameShorthandProperties": false` to the settings.json

![image](https://user-images.githubusercontent.com/3089978/61578165-eefee300-aaf2-11e9-8be9-35a59af72c4a.png)
