### ISSUE TITLE
Narrowing a union type loses narrowing from previous non-null check

### ISSUE THREAD

**Issue by jmhain** [microsoft/TypeScript#32475] opened 2019-07-18 22:39 UTC
**TypeScript Version:**  3.5.1

**Search Terms:**

**Code**

```ts
type Thing = { variant: 'a', prop: number } | { variant: 'b', prop?: number };

function f(t: Thing) {
  if (t.prop) {
    if (t.variant === 'b') {
      t.prop.toString();
    }
  }
}
```

**Expected behavior:**

No errors, because we checked that `t.prop` is defined in the outer `if`'s condition.

**Actual behavior:**

`tsc` says that `t.prop` is possibly undefined.

**Playground Link:** 

http://www.typescriptlang.org/play/#code/C4TwDgpgBAKgFgSwHYHMoF4oG8oDcCGATgvksAFxQDk+VANFGIQPZiVICuAtgEYSFQAvlAA+2PERJlKVHvUYswAfnbc+AwQG4AUNoBmHJAGNgCZkih6AFBViJUASmzaoUBHqg2AdE1ZOsLq5uHt4ExKTAGOiYslT+gUFQwD6KXsDMAMrAxKhWDjqJgoFFgkA

**Related Issues:**

**Comment by fatcerberus** [comment] 2019-07-18 23:10
It works if you swap the order of the checks.  It seems that discriminant narrowing discards any prior narrowings of individual non-discriminant properties.

**Comment by jack-williams** [comment] 2019-07-19 14:39
Duplicate of #31495

Searched phrase: _narrow discriminant property_

**Closed** 2019-08-02 18:00 UTC
Labels: Duplicate
