### ISSUE TITLE
VS Code - missing refactoring options

### ISSUE THREAD

**Issue by MintMissy** [microsoft/TypeScript#52216] opened 2023-01-12 22:08 UTC
# Bug Report

Hello!

Recently I've noticed that typescript has a built-in option to add missing properties to a variable. I've noticed it so late because the quick-fix menu opened by using a shortcut doesn't show all available refactoring options. (typescript). When I use the link in the hover widget everything runs smoothly.

I've created an issue on the abracadabra extension repository but they said it's not their fault and I had been redirected here.
Previous Issue on abracadabra: https://github.com/nicoespeon/abracadabra/issues/792

I've tried disabling the abracadabra extension - it didn't fix anything.

### 🔎 Search Terms

Missing "quick fix options"
Missing refactoring options in vs code
"Add missing properties" option is missing

### 🕗 Version & Regression Information

I don't remember seeing the option to add missing properties before, so I guess this bug has been here for longer.

### ⏯ Playground Link

Not applicable since it's a vs code problem

### 💻 Code

Not applicable since it's a vs code problem

### 🙁 Actual behavior

- The hover widget. It opens refactor menu with all properties after clicking in **Quick Fix... (Alt + Enter)**
![Hover](https://i.postimg.cc/tTK5VKp5/quickfix3.png)

- Menu with all properties opened by using a quick-fix link
![Menu with all properties](https://i.postimg.cc/gJXsjzFj/quickfix2.png)

- Menu with missing properties
![Menu with missing properties](https://i.postimg.cc/g0B4Gw71/quickfix1.png)

### 🙂 Expected behavior

Show all available refactoring options in the menu opened by using a shortcut.

**Comment by mjbvz** [comment] 2023-01-18 17:10
In the `Quick Fix...` case, VS Code requests all quick fixes in the diagnostic range:

https://github.com/microsoft/vscode/blob/990a496681948ec274da5503b35cd49a7d06c0a2/src/vs/editor/contrib/hover/browser/markerHoverParticipant.ts#L244


In this case, the diagnostic range comes from eslint so it covers `sth: GameStats`.  The VS Code behavior here is not correct, as detailed in Microsoft/vscode#161331

In the second case, it looks like we are requesting quick fixes at a specific position. 

Closing this as a duplicate of Microsoft/vscode#161331 (after fixing this, the `quick fix...` link should only show eslint quick fixes

**Closed by mjbvz** 2023-01-18 17:10 UTC
