### ISSUE TITLE
keyof an interface that extends an anyObject

### ISSUE THREAD

**Issue by dolphinlin** [microsoft/TypeScript#35600] opened 2019-12-10 04:05 UTC
**TypeScript Version:**  3.7.2

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
type AnyObject = {
  [key: string]: any;
};

interface Test extends AnyObject {
  name: string;
  age: number;
  handsome: boolean;
}

type TestKey = keyof Test;

const testObject: Test = {
  name: 'Dolphin',
  age: 999,
  handsome: true,
};
```

**Expected behavior:**
```ts
type TestKey = 'name' | 'age' | 'handsome';
```
**Actual behavior:**
```ts
type TestKey = string | number;
```

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAggdiA8gIwFYQMbCgXigbwCgooBtAawhAC4oBnYAJwEs4BzAXVoEMEBuQgF8BhVsAiMAZtwzQAKhAZQIAD3FwAJnVgIU6LAWJQ43ALYRaDFuwElubC8YCup5BIGDChUJCgKGANJUuFCUIAD2kn6KwCIY4XBK4gx6mMC0-th4RCQm5rQA5AAi4QA2YAAWrAUANEb2jgCczUJ8QA

**Related Issues:**

**Comment by dolphinlin** [comment] 2019-12-10 04:08
if Test ain't extends `AnyObject `, `TestKey` will be correct.

**Comment by jcalz** [comment] 2019-12-10 16:48
This is working as intended.  `testObject.blarf = 1;` is acceptable because `Test` has an index signature because `Test extends AnyObject`.  so `keyof Test` is going to reflect that index signature type which absorbs all string literals.

**Comment by dolphinlin** [comment] 2019-12-10 16:53
> This is working as intended. `testObject.blarf = 1;` is acceptable because `Test` has an index signature because `Test extends AnyObject`. so `keyof Test` is going to reflect that index signature type which absorbs all string literals.

Yes, agree ur opinion, but that maybe shouldn’t lost the keys of Test type ('name' | 'age' | 'handsome').

**Comment by jcalz** [comment] 2019-12-10 17:06
So is this a duplicate of #33471 then?

**Closed** 2019-12-12 20:00 UTC
Labels: Working as Intended
