### ISSUE TITLE
JavaScript IntelliSense not recognizing dynamically added properties

### ISSUE THREAD

**Issue by minkir014** [microsoft/TypeScript#31910] opened 2019-06-14 20:48 UTC
There is a problem with objects intellisense. I'll show two examples.

![er](https://user-images.githubusercontent.com/42807112/59537054-c1bc8500-8ef5-11e9-8e3e-d663d200ceee.jpg)

This should show `City` as property not only as text.

![er1](https://user-images.githubusercontent.com/42807112/59537265-650d9a00-8ef6-11e9-9c9c-0ca28cde1138.jpeg)

This should also shows `name` as property not only as text.

**Comment by minkir014** [comment] 2019-06-15 12:16
Any look at this issue???

**Comment by minkir014** [comment] 2019-06-17 16:16
Hey, Is there anyone here? Can anyone look at this issue??

**Comment by dragomirtitian** [comment] 2019-06-17 16:35
@minkir014  Duplicate of #31854 and #12416 ?

**Comment by minkir014** [comment] 2019-06-17 16:51
Is there any intend to fix these issues???

**Comment by minkir014** [comment] 2019-06-18 00:13
@dragomirtitian Can you response? Is there a near fix???

**Comment by dragomirtitian** [comment] 2019-06-18 07:03
@minkir014 I am not the right person to answer that, I am not a member of the typescript team an have no insight into their priorities (the contributor badge on my comments just means at least one of my PRs was merged to master, nothing more). All I can say is I am not planning to fix it, but that does not count for much 😊

The tickets I reference have been around for a while so I suspect a fix is not coming in the near future, but that is just speculation on my part.

**Comment by minkir014** [comment] 2019-06-18 12:15
@dragomirtitian Someone suggested a solution but I didn't know how to apply it see this and if you know how to apply that, tell me  https://github.com/Microsoft/TypeScript/issues/12278#issuecomment-261000712

**Closed** 2019-06-28 18:00 UTC
Labels: Duplicate
