### ISSUE TITLE
nodemon - change files on disk that really changed

### ISSUE THREAD

**Issue by wallverb** [Microsoft/TypeScript#9364] opened 2016-06-26 14:38 UTC
Similar to #8660 but probably different.
Is it possible for `tsc` to only "replace/modify" files on disk if they really got changed.
I understand that entire project needs to be "compiled" but it would be great if only changed 'js' files on disk would be overwritten.
Otherwise it creates issues with tools like nodemon - it picks up change in first file - restarts, then another file - restarts, etc ... - for now I need to put delay in nodemon config - which is not the best approach.

**Comment by kitsonk** [comment] 2016-06-27 06:54
Really more a duplicate of #3204 which has been pushed to TS2.1.

**Comment by mhegazy** [comment] 2016-06-27 17:59
This is already handled by https://github.com/Microsoft/TypeScript/issues/3113. it should be available in `typescript@next`. please give it a try and let us know if you are still running into issues.

**Comment by mhegazy** [comment] 2016-06-27 17:59
closing in favor of #3113

**Closed by mhegazy** 2016-06-27 17:59 UTC
