### ISSUE TITLE
TypeError: Cannot read property 'escapedName' of undefined in 'symbolName' during 'occurrences'

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#22557] opened 2018-03-14 02:54 UTC
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.2
**VSCode Version** 1.21.0-insider
**command requested**: occurrences
**hitting sessions**: 123
**proportion of all sessions**: 0.008766928011404135
**five line hash**: 2b3eb8f347df62ccb2a167d4be20ec57
**stack**
```
TypeError: Cannot read property 'escapedName' of undefined
    at symbolName (tsserver.js:69569:23)
    at getImport (tsserver.js:69509:36)
    at Object.getImportOrExportSymbol (tsserver.js:69436:68)
    at getImportOrExportReferences (tsserver.js:70283:56)
    at getReferencesAtLocation (tsserver.js:70231:17)
    at getReferencesInContainer (tsserver.js:70186:21)
    at getReferencedSymbolsForSymbol (tsserver.js:69904:25)
    at Object.getReferencedSymbolsForNode (tsserver.js:69820:24)
    at Object.getReferenceEntriesForNode (tsserver.js:69660:58)
    at getSemanticDocumentHighlights (tsserver.js:68595:57)
    at Object.getDocumentHighlights (tsserver.js:68584:20)
    at getDocumentHighlights (tsserver.js:83133:42)
    at getOccurrencesAtPositionCore (tsserver.js:83136:46)
    at Object.getOccurrencesAtPosition (tsserver.js:83122:27)
    at IOSession.Session.getOccurrences (tsserver.js:89656:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89272:61)
    at unknown (tsserver.js:90553:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90544:28)
    at IOSession.Session.executeCommand (tsserver.js:90553:33)
    at IOSession.Session.onMessage (tsserver.js:90573:35)
    at Interface.<anonymous> (tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by andy-ms** [comment] 2018-03-14 15:36
Duplicate of #22557

**Closed by andy-ms** 2018-03-14 15:36 UTC
Labels: Source: Telemetry

**Comment by aozgaa** [comment] 2018-03-14 17:31
The hash-search seems to give incomplete results, eg https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=2b3eb8f347df62ccb2a167d4be20ec57 only gives one result, even when this issue and its duplicate share the same hash in their body.

If searching for issues by a hash in their body fails to recover an existing issue with that hash (and we would prefer a complete list, so we could filter by the newest one), we may need to revert to the old strategy (loop through all existing `Source: Telemetry` issues).

**Comment by aozgaa** [comment] 2018-03-14 20:08
Updated digest to be a hash of the first five *methods* called. So, both hashes were changed to a new value (`fa266db034566074bb8afcb10a53a88a`). Now both seem to appear as search results. I'm still not sure why only one showed up before.
