### ISSUE TITLE
Uncaught TypeError: React.__spread is not a function

### ISSUE THREAD

**Issue by solodii** [Microsoft/TypeScript#7959] opened 2016-04-08 12:41 UTC
**TypeScript Version:** 

1.8.9

**React Version:** 

15.0.0

**Code**

```ts
import * as React from 'react';
import * as ReactDOM from 'react-dom';

let test = {a: 1, b: 2};

ReactDOM.render(
    <div {...test} />,
    document.getElementById('app')
);
```
**Actual behavior:** 
Browser console error "Uncaught TypeError: React.__spread is not a function".

**Comment by BernieSumption** [comment] 2016-04-08 14:17
Just came across this myself. React/babel have changed the way that spread attributes compile. Instead of relying on a utility function React.__spread, the transpiler now emits its own function that does the same job (i.e. merge all spread attributes into one object).

TypeScript should be updated to do the same, but in the mean time here's a polyfill that restores the old function and permits code compiled by TypeScript 1.8.9 to work:

```javascript
// universal
(React as any).__spread = function(target: any) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

// if you're compiling to ES6
(React as any).__spread = Object.assign;
```

It's created by copying the function emitted by the latest babel transpiler so i figure it should work perfectly. Initial testing hasn't shown any issues.

**Comment by RyanCavanaugh** [comment] 2016-04-08 15:37
Duplicate of #7270

**Closed by RyanCavanaugh** 2016-04-08 15:37 UTC
Labels: Duplicate
