### ISSUE TITLE
tsc crashes in generic types without error message (regression in TS 4.8.2)

### ISSUE THREAD

**Issue by AndreiSoroka** [microsoft/TypeScript#50966] opened 2022-09-27 10:18 UTC
# Bug Report

This code compiles successfully in TypeScript 4.7.4 and crashes tsc in TypeScript 4.8.3:

```typescript
export type Guard<T extends V, V = unknown> = {
  (v: V): v is T;
  optional?: boolean;
};

export type OptionalGuard<T extends V, V = unknown> = {
  (v: V): v is T;
  optional: true;
};

// Error here:
export type TypeOfGuard<G extends Guard<any>> = G extends Guard<infer P> ? P : never;

export type Maybe<T> = T | undefined;
export type Nullable<T> = T | null;

```

Console:
```
/Users/andreisoroka/git/ui-lib-type-utils/node_modules/typescript/lib/tsc.js:98438
                throw e;
                ^

TypeError: Cannot read properties of undefined (reading 'kind')
    at getTypeFromTypeNodeWorker (/Users/andreisoroka/git/ui-lib-type-utils/node_modules/typescript/lib/tsc.js:53098:26)
    at getTypeFromTypeNode (/Users/andreisoroka/git/ui-lib-type-utils/node_modules/typescript/lib/tsc.js:53095:49)
    at getEffectiveTypeArgumentAtIndex (/Users/andreisoroka/git/ui-lib-type-utils/node_modules/typescript/lib/tsc.js:68358:24)
    at Array.<anonymous> (/Users/andreisoroka/git/ui-lib-type-utils/node_modules/typescript/lib/tsc.js:50332:52)
    at getMappedType (/Users/andreisoroka/git/ui-lib-type-utils/node_modules/typescript/lib/tsc.js:53241:46)
    at instantiateTypeWorker (/Users/andreisoroka/git/ui-lib-type-utils/node_modules/typescript/lib/tsc.js:53554:24)
    at instantiateTypeWithAlias (/Users/andreisoroka/git/ui-lib-type-utils/node_modules/typescript/lib/tsc.js:53547:26)
    at instantiateType (/Users/andreisoroka/git/ui-lib-type-utils/node_modules/typescript/lib/tsc.js:53533:37)
    at _loop_15 (/Users/andreisoroka/git/ui-lib-type-utils/node_modules/typescript/lib/tsc.js:50334:58)
    at getInferredTypeParameterConstraint (/Users/andreisoroka/git/ui-lib-type-utils/node_modules/typescript/lib/tsc.js:50365:21)
npm ERR! code 1
npm ERR! path /Users/andreisoroka/git/ui-lib-type-utils
npm ERR! command failed
npm ERR! command sh /var/folders/p2/fz0tgpp14w34hrkzpjzgkgx80000gn/T/prepare-f40f29d0.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andreisoroka/.npm/_logs/2022-09-27T10_07_39_844Z-debug-0.log

```

### 🔎 Search Terms

https://github.com/microsoft/TypeScript/issues/50717 (error in `tsc.js:98438` too)

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions4.7.4 and 4.8.2

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBA4grgQwE4BMA8AVKEAewIB2KAzlAGoA05UAvFHAQNYED2A7gQHy1QDeAUFCgAKAG4AucgEpJoqAEtSGANyCoLMMHksCCADYB+SQCMWLPRAQFVAX1X9QkKAHlN23XvjJ0WXPiKklNR0DMzsXDwCQmKSZDJQcopQKmoaWjr6ksBIcBC29gD0BVCO0BjgEM4AZl6oaDDYeIQksIh1ViCc3HQNfs2ktejyBFUQSFAACtwGk1CSBBCiY-alUACyCCDGEJjdyVAAPvREEFXDECiqqwBycHp6CMYWuzxYRwR3eqpAA)

Open tab: .D.TS and try to comment and uncomment 11 line
<img width="1413" alt="Screenshot 2022-09-27 at 13 19 24" src="https://user-images.githubusercontent.com/6079139/192501150-f96f98e7-0c2c-4917-98f4-0e6095f91ae2.png">

### 🙁 Actual behavior

tsc crashed

### 🙂 Expected behavior

get an understandable error message or not crashing

**Comment by JoostK** [comment] 2022-09-27 13:51
Duplicate of #50479, has already been fixed but is pending a release (4.8.4).

**Closed** 2022-09-29 18:00 UTC
Labels: Duplicate
