### ISSUE TITLE
Nested object type inference

### ISSUE THREAD

**Issue by Jomik** [Microsoft/TypeScript#25295] opened 2018-06-28 16:10 UTC
**TypeScript Version:**  3.0.0-dev.20180628

**Search Terms:** infer nested type object

**Code**

```ts
class Foo<A> {
  private a: A;
}

class ObjectFoo<A> extends Foo<A> {
  constructor(private b: { [k in keyof A]: Foo<A[k]> }) {
    super();
  }
}

const a = new ObjectFoo({ b: new Foo<string>() });
const obj = new ObjectFoo({ a });
```

**Expected behavior:**
Expect `obj` to have type `{ a: { b: string } }`

**Actual behavior:**
`obj` has type `{ a: { b: any } }`

**Playground Link:**  
[playground](http://www.typescriptlang.org/play/#src=class%20Foo%3CA%3E%20%7B%0D%0A%20%20private%20a%3A%20A%3B%0D%0A%7D%0D%0A%0D%0Aclass%20ObjectFoo%3CA%3E%20extends%20Foo%3CA%3E%20%7B%0D%0A%20%20constructor(private%20b%3A%20%7B%20%5Bk%20in%20keyof%20A%5D%3A%20Foo%3CA%5Bk%5D%3E%20%7D)%20%7B%0D%0A%20%20%20%20super()%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20a%20%3D%20new%20ObjectFoo(%7B%20b%3A%20new%20Foo%3Cstring%3E()%20%7D)%3B%0D%0Aconst%20obj%20%3D%20new%20ObjectFoo(%7B%20a%20%7D)%3B%0D%0A)

**Related Issues:**

**Comment by RyanCavanaugh** [comment] 2018-06-28 17:38
This is just a bug in the typeToString code; the actual type of `b` is `string`

Duplicate of #23897

**Comment by Jomik** [comment] 2018-06-28 17:49
@RyanCavanaugh so the actual type is inferred for multiple layers of nested objects? :)
Thank you, I will follow that issue, feel free to close this!

**Comment by RyanCavanaugh** [comment] 2018-06-28 18:02
Yep, you can try in the Playground - the properties of `string` will show up on `obj.a.a.b` (once you remove the `private` modifier)

**Closed by RyanCavanaugh** 2018-06-28 18:02 UTC
Labels: Duplicate
