### ISSUE TITLE
Addition of string (or template) literal types should result in a string literal type

### ISSUE THREAD

**Issue by bradzacher** [microsoft/TypeScript#51583] opened 2022-11-18 01:28 UTC
# Suggestion

## 🔍 Search Terms

string literal type template addition sum add

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I was playing around today and I noticed that if I add two string literals together, TS does not understand that the result of adding two string literal types is always going to be another string literal type.

## 📃 Motivating Example

```ts
declare const x: 'x';
declare const y: 'y';

const xy = x + y;
//     ^?
//     expected: 'xy'
//     actual:   string

declare const a: `${number}`;
declare const b: `${boolean}`;

const ab = a + b;
//     ^?
//     expected: `${number}${boolean}`
//     actual:   string

const foo = 'a' + 'b';
//     ^?
//     expected: 'ab'
//     actual:   string

declare const f: 'a' | 'b';
declare const g: 'c' | 'd';

const fg = f + g;
//     ^?
//     expected: 'ac' | 'ad' | 'bc' | 'bd'
//     actual:   string
```
[playground](https://www.typescriptlang.org/play?ssl=29&ssc=24&pln=22&pc=1#code/CYUwxgNghgTiAEYD2A7AzgF3gDwFzwHJsCBuAWAChRJYFl0sBPfAx0yy+zHR+AXhzwA1PEbkKAegnwZMgHoB+SlNkyQ2AA7gMIYC2xtl01VDAYArlAj4ZmGAEsUAcw5Vw0OIlTco+AAYAJADeKOYAtgBGIDAAvn7i1B503lgR-sERSEgQIFAoceKcKfBQEfwlwvAR4iqqikaq8OpaZrrpIeFRsRlZOXlxDSZmltaydo4uFEUM8ABmWeUEUASVBBHsksay9ZuNzdpthKUEg7KmFlY28OPOrpSJtF4zsyzL8AA+hOsJ7o9cWE4WGAVp8CMANtNuLMnOVZpUnDUtvIlLtVPtWnojsCPkdwTi1tjQRFwacZOcRlcbpNKEA)

Maybe even including number literal types and boolean literal types would be good as well? Eg
```ts
declare const t: 1;
declare const u: 'a';
declare const v: true;

const tuv = t + u + v;
//     ^?
//     expected: '1atrue'
//     actual:   string
```
[playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3hgXPAjANwCwAUKJLAsulgK54DkUjJ540ciqm8Abngww6INmRq8MdPvAC82eAGp4dJfzYB6DfB06AegH4yW3TpAAPAA7gMIYE3xQhIxse2moYKVAh4dmGABLFABzMiA)

## 💻 Use Cases

I don't have any *real* usecases, I just thought it would be a neat property to have in the type system rather than always widening the type to `string`.

One case that it would improve would be computed class/object members:
```ts
declare const x: 'x';
declare const y: 'y';

class Foo {
   [x + y] = 1;
   // expected: 'xy'
   // actual:   error A computed property name in a class property declaration must have a simple literal type or a 'unique symbol' type.(1166)
}

const obj = {
    [x + y]: 1,
};
    obj;
//  ^?
//  expected: { xy: number }
//  actual:   { [x: string]: number }
```
[playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gDwFzwHJsCBuAWAChRJYFl0sBPfAx0yymtNeAMSSTwA3pXhiA2tngBqeIwC68ALzwAjOQpj4Aem3wQ2AA7gMIYC2xtRY3fChgMAVygR8YkDBhIY8AIKIkAFtDR1NgeEMvYxgMRngUKECEAEsUO0Robgioj1j4amgYKAxk1HhAx0x4AAsoADcEKHg0ZOCIBAhk0yKIeFjjeG90gkcUZIBHRwQ0RkCAIyQIAj7GYwA6AApVVQA2HYBKSgBfDgp6KqQ5gCtlYWsJKVkFfFUAGmONLUHrjVt4AD0APyUP4GYwOMz4IQ4ZjxRzzDzwE4UP72JwuNzCeCSfCYGCpADm8nwKHhc0RyKAA)

----

As an extension - if you were brave you could probably also do the same for adding number literal types eg:
```ts
declare const x: 1;
declare const y: 2;

const xy = x + y;
//     ^?
//     expected: 3
//     actual:   number
```
[playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gDwFzwEYBuAWAChRJYFl0sBPfAJlLPNsx3vgF4d4A1PHqsA9KPiTJAPQD85cVMkhsAB3AYQwfAGYFEpVDAYArlAj5JKEwFsARiBjkgA)

or bigint types:
```ts
declare const x: 1n;
declare const y: 2n;

const xy = x + y;
//     ^?
//     expected: 3n
//     actual:   bigint
```
[playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gDwFzwEYUBuAWAChRJYFl0sBPfAJhIorsxwfgF4d4AangMy5APTj406QD0A-BUkzpIbAAdwGEMHwBmFEqkqoYDAFcoEfNIBGASwDm9lBiA)

**Comment by MartinJohns** [comment] 2022-11-18 08:53
Duplicate of the very old #13969.

**Comment by bradzacher** [comment] 2022-11-18 09:16
@MartinJohns most of that seems to specifically be talking about template literal strings - which seems like a great idea, that I didn't consider for my issue!

I do see one or two comments mentioning addition, but most seem to talk about template literals.

**Comment by MartinJohns** [comment] 2022-11-18 09:24
The templates are probably the "similar expressions", but the title also mentions "literal types for string concatenations" (also in several examples in the comments).

**Comment by bradzacher** [comment] 2022-11-18 10:54
Also worth noting (as I just commented in that issue) if you add `as const` to the template literal string, then it will work as expected! The same isn't true of string literal typed variables - it is a semantic error to use `as const` on non-literal expressions.

**Comment by RyanCavanaugh** [comment] 2022-11-18 17:37
We need there to be some way to opt out of this behavior since this is potentially combinatorially explosive (imagine writing `hexDigit1 + hexDigit2 + hexDigit3 + hexDigit4`), and it's not clear how you would do that here. Since you can already get this behavior with `${f}${g}` as const` I think the use case is fully addressed.

**Comment by bradzacher** [comment] 2022-11-18 19:22
> We need there to be some way to opt out of this behavior

Couldn't that be like assert one of the summands to string? `(a as string) + b +...`

That would make it an explicit opt-out instead of an explicit opt-in like template literal strings.

---

> Since you can already get this behavior with <template literals> I think the use case is fully addressed.

I would agree that the usecase of "I want to concatenate string literal types" is addressed!

But in terms of addressing the usecase of better typing for code as it's written - there is a gap. Using template literals to concentrate strings is a stylistic choice which many codebases don't opt-in to unless there's string literals involved (I.e. `a + b` is stylistically okay, but `a + '.' + b` is stylistically preferred to be a template literal). So there is a lot of existing code which uses addition to join string variables which could be stricter typed!

**Comment by fatcerberus** [comment] 2022-11-18 21:23
Problem is that if you infer `hexDigit + hexDigit` to be `${typeof hexDigit}${typeof hexDigit}`, this easily creates combinatorially explosive unions and then users start to wonder why they're getting "union is too complex to represent" errors in perfectly mundane code that doesn't even *look* like a type operator.  At least if that user is forced to write `${Hex}${Hex}${Hex}` or similar they know they're opting in to a construct that can potentially create enormous unions.

**Comment by RyanCavanaugh** [comment] 2022-11-18 22:00
> Couldn't that be like assert one of the summands to string?

In principle no, there's no reason not to construct the type `${string}000` | `${string}001` | `${string}002` | `${string}003` | ... `${string}fff`

**Closed** 2023-06-21 01:32 UTC
Labels: Suggestion, Declined
