### ISSUE TITLE
Emit error on 'use strict' in function with non-simple parameter list

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#25616] opened 2018-07-12 19:59 UTC
**TypeScript Version:**  2.9.1

**Search Terms:** use strict

**Code**

```ts
// rest parameter
function rest(...args: any[]) {
  'use strict';
}
// parameter defaults
function paramDefault(param = 1) {
  ' use strict';
}
// destructuring
function bindingPattern([foo]: any[]) {
  'use strict';
}
```

**Expected behavior:**

Type error on all Use Strict Directives above.
The Spec defines this as Early Errors for all function-like declarations: http://www.ecma-international.org/ecma-262/9.0/#sec-method-definitions-static-semantics-early-errors

**Actual behavior:**

No type error. Instead this throws a syntax error when executed.

**Playground Link:** https://agentcooper.github.io/typescript-play/?alwaysStrict=false&target=0#code/PTAECcFMGcBdQA4ENxILaVpcAoAZgK4B2AxrAJYD2REMsAFAHTMoDm0AXKEkQJ4DaAXQCUoAN45QoAOQFokUHHDky0gNw4AvjhCIU6TNlAATSHiQEANrGj5iZKjWSo0AETMXr9Z+lABeUABGUQkpaVA5BSUVWHUtHTBTJQIyAmUiVjtSCmpQACNyImNC1gAFJFgscCJ6fjxKSkEuHgERcUkZSMVYZVUNTSA

**Related Issues:**

**Comment by RyanCavanaugh** [comment] 2018-07-12 20:03
TIL

**Comment by DanielRosenwasser** [comment] 2018-07-12 23:38
Duplicate of #6815

**Comment by DanielRosenwasser** [comment] 2018-07-12 23:38
> TIL

No you absolutely didn't.

**Comment by RyanCavanaugh** [comment] 2018-07-13 15:30
LYIF (Last Year I Forgot) 😆

**Closed** 2018-07-25 18:29 UTC
Labels: Duplicate
