### ISSUE TITLE
es6 import should not emit a 'require' for d.ts file with const enum

### ISSUE THREAD

**Issue by nojvek** [Microsoft/TypeScript#9821] opened 2016-07-19 15:41 UTC
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**

example.ts:
```ts
// A *self-contained* demonstration of the problem follows...
import * as foo from './foo'
if (foo.Commands.Yay) {
   console.log("yay")
}
```

foo.d.t.s
```
export const enum Commands {
   Yay = 1,
   Boo = 2
}
```

**Expected behavior:**

foo.d.ts is  purely a typescript declaration. It doesn't have a foo.js file

when example.js is emitted it should have

```
if (1 /* Commands.Yay */){
   console.log("yay")
}
```

**Actual behavior:** 

```
foo = require("./foo") // Should not be emitted for const enum uses

if (1 /* Commands.Yay */){
   console.log("yay")
}
```

**Comment by vladima** [comment] 2016-07-19 17:02
duplicate of #4690

**Closed by vladima** 2016-07-19 17:02 UTC
Labels: Duplicate
