### ISSUE TITLE
Support annotating if/else blocks with inline type guard hints

### ISSUE THREAD

**Issue by kherock** [microsoft/TypeScript#44192] opened 2021-05-20 23:25 UTC
# Suggestion

## 🔍 Search Terms

`if/else` `narrowing` `type guard`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When I think of narrowing in TS, I think of how it's used with `if/else`, so it's kind of surprising to see that there's no direct syntax for narrowing without defining a special kind of function first. In pure JS, I'd normally do all of my narrowing with `if/else` statements first, and then in a later refactor I might extract common checks into dedicated functions. It's jarring that I need to define a function up-front before writing a `if/else` statement, my only alternative being a manual narrowing in each block with casting.

## 📃 Motivating Example

Consider a simple type guard like this one:
```typescript
function isDateIsh(value: unknown): value is number | Date {
  return !isNaN(Number(value));
}

declare const myValue: number | Date | string;
if (isNumberIsh(myValue)) {
  myValue; // number | Date
} else {
  myValue; // string
}
```

## 💻 Use Cases

The check here is so simple that it's tempting to directly inline it into an `if/else`, but I'd lose out on the narrowing since `isNaN` isn't a type guard. It would be great if there were a way to directly hint that an `if/else` block should narrow the type, like this:

```typescript
declare const myValue: number | Date | string;
if (!isNaN(Number(myValue))): myValue is number | Date {
  myValue; // number | Date
} else {
  myValue; // string
}
```

What's really great about this syntax is that it's self documenting. In a real codebase where I don't want to dirty up a file with one-off functions or don't have a robust set of utility functions, you'd probably see me writing code like this:

```typescript
declare const myValue: number | Date | string;
if (!isNaN(Number(myValue))) { // ensure myValue can be treated like a number
  const myValueDateIsh = myValue as number | Date;
  myValueDateIsh; // number | Date
} else {
  const myValueString = myValue as string;
  myValueString; // string
}
```

As far as I'm aware, there aren't really any downsides to this approach if the syntax allows for it. It allows for "lazier" code and functions with greater apparent cyclomatic complexity, but I don't think a helpful feature like this is actually prescribing those coding styles.

**Comment by RyanCavanaugh** [comment] 2021-05-20 23:54
Looks like a duplicate of #10421.

OT but `isNaN(Number("0"))` is `false` 😅

**Comment by kherock** [comment] 2021-05-21 00:08
> Looks like a duplicate of #10421.
> 
> OT but `isNaN(Number("0"))` is `false` 😅

😂 I *knew* I was missing something, thank you. I'll come up with a more convincing example when I have a chance.

#10421 seems more general, but I agree that this is a duplicate. My proposal is more limited since it only pertains to `if/else` syntax.

**Comment by IllusionMH** [comment] 2021-05-21 08:57
Look closer to #6474

**Closed** 2021-05-23 18:00 UTC
Labels: Duplicate
