### ISSUE TITLE
Excessive properties are not checked if variable is passed

### ISSUE THREAD

**Issue by ojab** [microsoft/TypeScript#52228] opened 2023-01-13 20:51 UTC
# Bug Report

EDIT: ok, reproducer works even without generics

### 🔎 Search Terms

`may only specify known properties`

### 🕗 Version & Regression Information

/shrug

Please keep and fill in the line that best applies:
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about everything

### 💻 Code
```tsx
// My code goes here

type Foo = {
    x: number
}

const bar = (baz: Foo) => {
    console.log(baz)
}

const qux = {x: 1, y: 2}
bar(qux) # OK
bar({x: 1, y: 2}) # KO
```

[Playground Link](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5IBQRALpAA4oBiccoAvKAN5GjugAeAXKAHYBXALYAjAkQC+JeH0ylQIgIb5GoABRKAXr1pwAlIwB8LNhxmY4AGyQA6S3FQbFmvZOlxZ8gI4DOq5jygAIwANKCQvABMUkr4aj6crrFqAbyh4VESriRAA)

### 🙁 Actual behavior

It doesn't typechecks when variable is passed

### 🙂 Expected behavior

`Argument of type '{ x: number; y: number; }' is not assignable to parameter of type 'Foo'.` 	just like when object is passed directly

**Comment by MartinJohns** [comment] 2023-01-13 21:01
This is working as intended. Excess property checks only applies to object literals.

**Comment by ojab** [comment] 2023-01-13 21:38
um, but why? I'm passing the same object, so typechecking _should_ be consistent?

**Comment by MartinJohns** [comment] 2023-01-13 21:40
Excess property checks is more of a linter feature. TypeScript is structurally typed, if the structure of the types are compatible you can assign it. Your object with the two properties is compatible with the parameter type.

**Comment by ojab** [comment] 2023-01-13 21:46
Ah, got it, but is my initial bugreport with 
```tsx
export type Exact<T> = {[K in keyof T]: K extends keyof T ? T[K] : never};

type Foo = {
    x: number
}

const bar = (baz: Exact<Foo>) => {
    console.log(baz)
}

const qux = {x: 1, y: 2}
bar(qux)
bar({x: 1, y: 2})
```
stands then? AFAIU it should enforce that excessive properties are not passed.
[Playground Link](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5IBQRSAHgA5z4AuoNkFKAomQIYw0A8AKgHygAvKADeAbQDSoAJYA7UAGskkOADNQPALoAuUFPI0kshNiUr1PUAH4NkzaF2ykANwIBfANwkGTUADE4OCFRIlAw0DJHAFcAWwAjAiI3EnhZTDo4tnxggApMgC9dVg5uALg+AEohARFQ8NTMOAAbJAA6JrhUPLZ8iqSUuDS6AEcosmCRSNAARgAaUEhdACZkzPwc0bI+tZzJ3TmF5bc+kiA)

**Comment by MartinJohns** [comment] 2023-01-13 21:55
TypeScript is structurally typed. [TypeScript is structurally](https://github.com/microsoft/TypeScript/wiki/FAQ#what-is-structural-typing)

The type of `{x: 1, y: 20}` is compatible with the type `Exact<Foo>`, so passing it to the function is allowed.

**Closed** 2023-01-16 20:00 UTC
Labels: Working as Intended
