### ISSUE TITLE
Union of objects with union property is not eliminated

### ISSUE THREAD

**Issue by awerlogus** [microsoft/TypeScript#51552] opened 2022-11-16 12:11 UTC
# Bug Report

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221116#code/C4TwDgpgBAglC8UDeUCGAuKByAjFgNFAEaYDOwATgJYB2A5lAL5QA+yamWATFq9gMy9GAWABQYgCYQAxgBtUFaNID2Nch1hixVAGZQAFKgB0qKAEJ4ibrwBkNtCfOWBWAJTIxUKAHpvBsBTKkBSg7hhQAEQ4EZ4OqFqiXr5QAAqBwaDYRLwSyhCkUDTKwFAQAB5U6qpQoJDYMFhGscleaUEQISBZOXkFRSXllSXVtdBYKOERXBF8EfwRANxMjfpc-PwAnK6xxkRiIqJAA)

### 💻 Code

```ts
type A = { a: '1', b: string } | { a: '2' | '3' }

declare const a: A

if (a.a !== '2' && a.a !== '3') {
  // (property) a: "1"
  a.a

  // Property 'b' does not exist on type 'A'.
  //   Property 'b' does not exist on type '{ a: "2" | "3"; }'.(2339)
  a.b
}
```

### 🙁 Actual behavior

Error: Property 'b' does not exist on type 'A'.

### 🙂 Expected behavior

No error

**Comment by MartinJohns** [comment] 2022-11-16 14:02
Duplicate of https://github.com/microsoft/TypeScript/issues/43026#issuecomment-789220358.

**Closed** 2022-11-19 18:00 UTC
Labels: Duplicate
