### ISSUE TITLE
Feature request: built in method to get Typescript instances from JSON

### ISSUE THREAD

**Issue by baloodevil** [Microsoft/TypeScript#7233] opened 2016-02-25 03:53 UTC
The capability has been discussed [here](http://stackoverflow.com/questions/29758765/json-to-typescript-class-instance) and [here](http://stackoverflow.com/questions/22885995/how-do-i-initialize-a-typescript-object-with-a-json-object) and [here](http://stackoverflow.com/questions/22875636/how-do-i-cast-a-json-object-to-a-typescript-class).  I would like to see a built-in way of doing this in the Typescript language itself.  Sort of like a deserializer.

JSON is the language of data.  Typescript will have greater adoption if there is an easy way to 'cast' a JSON string (or the javascript object created from it) into an instance of a Typescript class.  If it is just the javascript object, it doesn't have methods of the class and items initialized with the constructor.

In the links above, one challenge is complex classes, ie: instance of Car class that has instance of Engine class in the same JSON.  There is not an elegant way of doing this.  The closest is to adopt a convention for metadata in the JSON which shows the subclass name.  For example, a property like \_\_name\_\_ = "Engine", so the 'deserializer' knows what type of class to instantiate for the subclass items.  One suggestion to make the convention less arbitrary would be to use metadata that Typescript adds to the javascript when using Typescript's reflection.  If that was the approach, it would probably make sense to also create a 'serializer' that when stringifying the Typescript instance, also included the necessary metadata.

Could there be a way to accomplish this with Typescript [declaration merging](http://www.typescriptlang.org/Handbook#declaration-merging) or [mixins](https://typescript.codeplex.com/wikipage?title=Mixins%20in%20TypeScript&referringTitle=Declaration%20Merging)?

**Comment by stunaz** [comment] 2016-04-01 17:26
Looking forward for it.
Have a look at this solution https://github.com/pleerock/serializer.ts

**Comment by mhegazy** [comment] 2016-04-22 00:35
duplicate of https://github.com/Microsoft/TypeScript/issues/2064

**Comment by baloodevil** [comment] 2016-04-22 12:40
@mhegazy I believe #7233 and #2064 are distinct.  #2064 is focused on validating json against a type definition.  #7233 is focused on creating an *instance* of an object according to a type definition.  The latter is similar to what underscore and jquery libraries do with "extend".

**Comment by baloodevil** [comment] 2016-04-22 12:53
@stunaz Great!  That is exactly what is needed.  I hope something like this can be integrated into the Typescript library itself.  Re: "Since Typescript does not have good reflection abilities yet, we must implicitly specify what type of object each property contain."  Could properties created with emitDecoratorMetadata be used for this purpose to avoid new annotations specific to your lib?  Minor tweak suggestion: change "Skip" to "NotMapped" (term from Entity Framework code first annotations).

**Comment by mhegazy** [comment] 2016-04-27 19:12
Providing a runtime library and/or builtin reflection capabilities are out of scope of the typescript project for the time being.

**Closed** 2016-04-27 19:12 UTC
Labels: Out of Scope, Suggestion
