### ISSUE TITLE
class property with no defined value get's compiled out, it should be assigned a default value.

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/TypeScript#12476] opened 2016-11-23 21:04 UTC
In the following code the property `count` will be compiled out. A more appropriate thing to do would simply assign the property `count` with a value of `undefined` or the types default value.
```
class Foo {
  title = "Foo";
  count: number;
}
```

This is a problem in Augury, which is a debug tool for Angular 2. Right now there is no way for us to display all available properties when viewing a component, so for code like this:

```
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-root',
  template: require('./app.component.html'),
  styles: [require('./app.component.css')]
})
export class AppComponent {
  title = 'Angular Input Output';
  count: number;

  @Input() message = "Message Board";
```

Augury will show that AppComponent has properties: `title` and `message` but `count` will not be shown since it get's compiled out by TS. 

Maybe the default value for the type number should be zero, while for string it could be the empty string, so the property type would at least be respected and more so the property would not get compiled out.

In TS we know that property `count` is a member of the class, we've explicitly declared it, therefore it makes sense not to have it compiled out.

tsc Version 2.0.10

**Comment by mhegazy** [comment] 2016-11-23 21:12
Duplicate of https://github.com/Microsoft/TypeScript/issues/12437

**Closed** 2016-11-23 23:33 UTC
Labels: Duplicate
