### ISSUE TITLE
Incorrect type inference with destructuring assignment

### ISSUE THREAD

**Issue by alienvspredator** [microsoft/TypeScript#38259] opened 2020-04-30 06:34 UTC
**TypeScript Version:**  3.8.3

**Search Terms:**

typecheck, union, type inference, destructuring assignment, tuple

**Code**

```ts
function print(str: string) {
    console.log(str);
}

type Union = [string, null] | [null, string];

function getTuple(): Union {
    return ['str', null];
}

const [a, b] = getTuple(); // Destruct the tuple.
if (b === null) {
    // a should be inferred as string here. But it inferred as string | null.
    print(a);
    // Typecheck error. Argument of type 'string | null' is not assignable to parameter of type 'string'.
    //     Type 'null' is not assignable to type 'string'
}

```

**Expected behavior:**
Successful compilation.

**Actual behavior:**
Compilation error.

**Playground Link:** 

[Playground Link](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABABwE4zFAFAZyqgLkT3TAHMBKRAbwChEHEIEc4AbAUwDo24zd8FANy0AvrVpQAnsg6IAqmHhIAvIgDaJDGQA0iMCDZsAuogA+Gg0b1byxkbWZg8iKCGScii5YjXqA5CT+elYmDk4u6gCGegBGpmpuHhxCiAD0aYgAIhwkINCuABZySZxctDDAiFhRvipqoVR0jCik2LHC9IwZiAAqMhwQxRAA1ogcqKhwqFyIAIKoZCAAthyYiHBV0rKIgfja5vqGbP6IMDj6cFCIUTg4MGRgUbGcrnAoUahRq1ATG1sDXa2Mj+cotHotfo7fyhU7nS7XW73R7PV5Qd7bOR7UggsS0IA)

**Related Issues:**

**Comment by IllusionMH** [comment] 2020-04-30 11:09
Duplicate of #12184

**Closed** 2020-04-30 18:41 UTC
