### ISSUE TITLE
`true ||` leads to "Object possibly 'undefined'"

### ISSUE THREAD

**Issue by yonilerner** [microsoft/TypeScript#35238] opened 2019-11-20 18:43 UTC
**TypeScript Version:**  Nightly (as of date of issue creation)

**Search Terms:**
- "Object is possibly undefined" (and variations)
- "true ||"

**Code**

```ts
interface Foo {
    bar?: boolean
}
function test(x: Foo | undefined) {
    if (!x?.bar) {
        return
    }
    return true || x.bar
}
```

**Expected behavior:**
Compiles with no errors

**Actual behavior:**
"Object is 'undefined'" on `x` in the statement `return true || x.bar`
This is especially weird because if you remove the `true ||` so you just have `return x.bar`, there is no error, and if you move the extra condition to the end so you have `return x.bar || true` there is also no error.

**Playground Link:** http://www.typescriptlang.org/play/index.html?ts=Nightly#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyRyARnFAPwBcpmANhHCAQL4EwCuICYw6IySAGcwACgAeNDFgA+yLgBMIMUBAUBKHAWLJgMZKICE4igDoyUTXkI7iUCGA5RmNom1fJ7j54KgcUMnLi5uSsQA

**Comment by jack-williams** [comment] 2019-11-20 18:48
I think this is duplicate of #26914.

**Comment by yonilerner** [comment] 2019-11-20 19:11
Makes sense. Should I close this or wait for someone else to mark it duplicate?

**Comment by RyanCavanaugh** [comment] 2019-11-20 19:58
Always OK to self-close here. Thanks for asking!

**Closed by RyanCavanaugh** 2019-11-20 19:58 UTC
Labels: Duplicate
