### ISSUE TITLE
Possible regression or breaking change in TS 4.3 beta

### ISSUE THREAD

**Issue by markusjohnsson** [microsoft/TypeScript#43758] opened 2021-04-21 06:00 UTC
# Bug Report

### 🔎 Search Terms

spread assignment generic constraint

### 🕗 Version & Regression Information

version 4.3.0-dev.20210418
version 4.3.0-beta

- This changed between versions 4.2 and 4.3

### ⏯ Playground Link

Errors with ts 4.3.0-beta:
https://www.typescriptlang.org/play?ts=4.3.0-beta#code/FAFwngDgpgBAgjAvDA3jA1gSwHYBMBcMARAIZEwC+A3KJLAEJKoY4HEBG51t0MAwgHsAthAHYo2EEwQAfGPRrAAZgFdsAYxCYxMAE5R2KzABtcAHgAqMKAA8QE3AGd+w0eMkA+ABTrCFgJR+qMAwoTDqYo5S4gDufEHIKCFhKQB06erJodwp+iAqutgwsXw0FMBAA

Works fine with ts 4.2.3:
https://www.typescriptlang.org/play?ts=4.2.3#code/FAFwngDgpgBAgjAvDA3jA1gSwHYBMBcMARAIZEwC+A3KJLAEJKoY4HEBG51t0MAwgHsAthAHYo2EEwQAfGPRrAAZgFdsAYxCYxMAE5R2KzABtcAHgAqMKAA8QE3AGd+w0eMkA+ABTrCFgJR+qMAwoTDqYo5S4gDufEHIKCFhKQB06erJodwp+iAqutgwsXw0FMBAA

### 💻 Code

```ts

type A = { kind: "a" };
type B = { kind: "b" };
type Component = A | B;

function rebuild<T extends Component>(c: T): T {
    const newC: T = { // <------- error: cannot assign
        ...c
    };
    return newC;
}

```

### 🙁 Actual behavior

```
Type '{ kind: "a"; } | { kind: "b"; }' is not assignable to type 'T'.
  '{ kind: "a"; } | { kind: "b"; }' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'Component'.
    Type '{ kind: "a"; }' is not assignable to type 'T'.
      '{ kind: "a"; }' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'Component'.(2322)
```

### 🙂 Expected behavior

No error, since `c` is `T`, `{ ... c }` should also be `T`.

**Comment by MartinJohns** [comment] 2021-04-21 06:11
Duplicate of #43749.

**Closed** 2021-04-21 14:15 UTC
