### ISSUE TITLE
Autoimport always imports relative to baseUrl

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19920] opened 2017-11-10 19:05 UTC
_From @artaommahe on November 9, 2017 11:38_

- VSCode Version: 1.18.0
- OS Version: Windows 10

Steps to Reproduce:
1. ts project with provided `baseUrl`
2. add autoimport for smth from same directories sub-tree
3. see `baseUrl` relative import
```ts
/// auth/routing.ts
import {MobileStubComponent} from "auth/component/mobile-stub/mobile-stub";
```

expected import relative to current file
```ts
import {MobileStubComponent} from "./component/mobile-stub/mobile-stub";
```

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#37928_

**Comment by mjbvz** [comment] 2017-11-10 19:05
_From @Martaver on November 9, 2017 20:17_

Also seeing this behavior, in 1.18 and previous, on both manually chosen import fixes and the new auto-import on completion feature.

**Comment by mjbvz** [comment] 2017-11-10 19:05
_From @Martaver on November 9, 2017 20:34_

For me, removing the baseUrl entry from my tsconfig.json file fixed the issue.

**Comment by kumarharsh** [comment] 2017-11-16 11:46
@mjbvz would this issue also affect autoimport in JS/JSX? I'd have a few suggestions for the feature, but don't know if this is the correct place for it.

**Comment by andy-ms** [comment] 2017-11-16 14:38
@kumarharsh Yes, they're the same feature.

**Comment by kumarharsh** [comment] 2017-11-17 07:08
OK, so I found the feature useful, although a little rough to use because the import paths it produces are not how the rest of the code is written.

Many times, I export code from the `index.js` file, for example: `constants/Widgets/index.js`. Then, I import in this style:
```js
import { A, B, C } from 'constants/Widgets';
```
* I drop the `/index` part because it's redundant in JS/TS-based systems, as far as I know.
* I also drop the extension part for JS files.
* I use webpack, and it has a nifty feature which let's me define custom module resolutions (`resolve.modules`)[https://webpack.js.org/configuration/resolve/#resolve-modules], so instead of writing `../../../ui/Input`, I can just write `ui/Input` and keep my code clean. It also allows me to move the component somewhere else in the future without worrying about breaking import paths.

If the vscode solution can take these into account, it'd be awesome.

**Comment by andy-ms** [comment] 2017-11-17 14:38
* For `/index` see #19962.
* We should be dropping the `.js` extension already.
* Setting up [`--rootDirs`](http://www.typescriptlang.org/docs/handbook/compiler-options.html) should make the third part work.

**Comment by kumarharsh** [comment] 2017-11-17 14:59
Oh, awesome! I think No. 2 is already working as expected (my mistake to point that out). About No. 3, my project is a JS project, so there's no tsconfig, but a jsconfig is there.

**Comment by mhegazy** [comment] 2017-11-18 00:22
you should be able to set the same options in `jsconfig.json` as you do in `tsconfig.json`

**Comment by 0x80** [comment] 2017-11-18 09:32
@andy-ms I am confused about rootDirs vs paths. I can only get non-relative imports to work using the paths setting.

```json
 "paths": {
      "*": ["*", "src/*"]
    },
```

Setting `rootDirs: ["*", "src"]`  doesn't seem to change anything in that context. Also I don't quite get what rootDirs is for if you already tell the compiler what to compile with the "include" setting. 

And with the paths setting I still have the issue that I reported [here](https://github.com/Microsoft/vscode/issues/38061)

Here's my full tsconfig:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "react",
    "lib": ["es6", "es7", "esnext", "dom"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmitOnError": false,
    "noImplicitAny": false,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "outDir": "build/dist",
    "paths": {
      "*": ["*", "src/*"]
    },
    "plugins": [
      {
        "name": "tslint-language-service"
      }
    ],
    "rootDirs": [".", "src"],
    "skipLibCheck": false,
    "sourceMap": true,
    "strictNullChecks": false,
    "suppressImplicitAnyIndexErrors": true,
    "target": "es6"
  },
  "exclude": ["build", "config-overrides.js", "jest", "scripts"],
  "include": ["src/**/*"]
}
```

**Comment by kumarharsh** [comment] 2017-11-20 12:30
@mhegazy - the rootDirs setting is not working for me.

**Comment by stevematdavies** [comment] 2017-11-20 14:31
paths is completely broken in my case

**Comment by mhegazy** [comment] 2017-11-20 19:11
https://github.com/Microsoft/TypeScript/pull/19724 should give multiple imports anyways.. this will address some of these requests..

**Comment by mhegazy** [comment] 2017-11-20 19:11
You find more info about `rootDirs` and `paths` mapping in https://www.typescriptlang.org/docs/handbook/module-resolution.html

**Comment by andy-ms** [comment] 2017-11-28 19:04
Is this fully fixed by #19724?

**Comment by mhegazy** [comment] 2017-11-28 20:44
@kumarharsh, @stevematdavies and @0x80 can you give #19724 a try? the fix should be in `typescript@next` tomorrow. 
 VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.

**Closed by mhegazy** 2017-11-28 20:44 UTC
Labels: Bug, Fixed, VS Code Tracked

**Comment by 0x80** [comment] 2018-01-06 15:47
@mhegazy I did not notice any change in behavior so far. 

I'm trying to use `~/` or `@src/` imports. The compiler and linter get it, but the path auto-completion in VSCode still messes things up once I hit `tab`.

I've tried this:

```json
"rootDirs": [
      "src"
    ],
    "baseUrl": "src",
    "paths": {
      "@src/*": [
        "*"
      ],
      "~/*": [
        "*"
      ]
```

And this:

```json
"baseUrl": ".",
    "paths": {
      "@src/*": [
        "src/*"
      ],
      "~/*": [
        "src/*"
      ]
    },
```

When I try to import the file from `src/helpers/fetch`: Hitting tab at `~/helpers/fet` completes it to `~/helpers/node-fetch`, because that module is one of my projects dependencies.

**Comment by andy-ms** [comment] 2018-01-08 16:35
@0x80 I made an issue for that: #21067

**Comment by asvetliakov** [comment] 2018-01-20 03:47
Is it broken again? I remember 1-1.5 months ago VS code (using 1.19-insider version) had been displaying the picker with 2 choices: relative path and baseurl path. Now it's autoimporting only baseurl derived paths without any prompts.

TS: 2.7.0-dev.20180119
VSCode: 1.19.2 (tried latest insider version too)

**Comment by travikk** [comment] 2018-01-24 04:38
@mhegazy @andy-ms this issue seems to be broken again as well. Adding "baseUrk": "." causes all relative import to go from "src/...." when using auto suggestions.

TS: 2.7.0-dev-20180119
VSCode: both the insider and 1.19.2

**Comment by mhegazy** [comment] 2018-01-30 06:31
@travikk can you try again with latest insiders build? #21398 should have a fix for that.

**Comment by guillaumep** [comment] 2018-02-17 02:41
@mhegazy Since 1.20 Visual Studio Code uses the shorter relative path. This is an issue for the project I'm working on since we stated we prefer using the full path, in order to ease refactoring.

How to I tell VS Code to prefer the full path? I can't find documentation about this, and the behaviour seems to be hard-coded.

**Comment by mikfoo** [comment] 2018-02-19 12:59
@guillaumep we had the same issue and fixed it by adding the following in our `tsconfig.json` under `compilerOptions`

```
"paths": {
  "components/*": ["src/components/*"]
}
...
```

That makes the auto import set the import string to `components/YourComponent` and it looks at `src/components/YourComponent` for the file/folder.

**Comment by guillaumep** [comment] 2018-02-19 21:52
@mikfoo All my imports are from 'src', so this workaround would not work.

**Comment by mikfoo** [comment] 2018-02-20 09:08
@guillaumep Actually, we are using `src` as well (and our imports are `src/foo/bar`) but I forgot to mention you need to add `baseUrl` too.

```
"baseUrl": "./",
"paths": {
  "src/*": ["src/*"]
}
...
```

**Comment by guillaumep** [comment] 2018-02-21 16:43
@mikfoo I have changed my config from:

<pre>
         "baseUrl": "./",
         "paths": {
            "src": ["./src"]
         }
</pre>

to:

<pre>
         "baseUrl": "./",
         "paths": {
            "src/*": ["src/*"]
        }
</pre>

and VS Code now imports from `src`!
You have all my gratitude for helping me solve this irritating issue!

**Comment by rsheptolut** [comment] 2018-03-21 11:05
@andy-ms Um, but can I hide the new relative entries I am now getting in TypeScript 2.7.2? I actually don't like these as it's hard to understand where they point to, and they break when moving a file. The only thing I don't like even more is that apparently now they are being suggested "randomly" - sometimes the relative is the first one, other times the "absolute" is. Mixing relative with non-relative in one project will be even more confusing. And I already added a couple of those, because I'm used to just pressing Ctrl+. and Enter for the fix without actually looking at it much. 

So, in the source code for the fix I've found a preference called "**importModuleSpecifierPreference**" which, when set to "non-relative" seems to be designed to do what I want (only show the "absolute" import suggestion), but I just spent half an hour trying to figure out how and where to set it (I'm using a blank VS Code), to no avail. Can you help me out with how to set this one please? For now I just switched back to the workspace version of TypeScript (which for me is 2.5.3).

**Comment by foote-Greg** [comment] 2018-04-15 15:55
@mjbvz Your solution worked for me as well

**Comment by tomitrescak** [comment] 2018-07-07 02:53
Guys, sorry to write in the closed issues, but all my package imports are imported using relative paths ;(

<img width="785" alt="image" src="https://user-images.githubusercontent.com/2682705/42406105-8930e5a6-81e4-11e8-911c-6d65a3b327dc.png">

This is my tsconfig.json and typescript 2.9.2

```json
"compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "moduleResolution": "node",
    "lib": ["es2017", "dom"],
    "jsx": "react",
    "noEmit": true,
    "skipDefaultLibCheck": true,
    "skipLibCheck": true,
    "pretty": true,
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "strictNullChecks": false,
    "experimentalDecorators": true,
    "typeRoots": ["src/shared/models", "node_modules/@types"]
  }
```

**Comment by kitsonk** [comment] 2018-07-08 09:29
@tomitrescak I believe it is related to #25279.  What happens with `typescript@next`?

**Comment by tomitrescak** [comment] 2018-07-08 12:31
@kitsonk yup, the issue is gone! thanks ... now I do not get the auto correct helper with "CMD + ." but I guess that will arrive later ;)

**Comment by tobiasmuecksch** [comment] 2018-07-22 17:53
I'm having this issue. There is no baseUrl in my tsconfig. How can we fix this?
