### ISSUE TITLE
Calling only super() in a derived class constructor after some comment produce wrong output.

### ISSUE THREAD

**Issue by dardino** [Microsoft/TypeScript#12909] opened 2016-12-14 11:20 UTC
**TypeScript Version:**  2.1.2 for visual studio

writing a costructor in a derived class with comments before calling super() generate an unexpected behaviour in javascript, 
the compiler puts the "return" statement before comments, this produce at runtime a wrong  behaviour because the super method will never be executed.

**Code**

```ts
class A {

}
class B extends A {
	constructor() {
		// comment
		super();
	}
}
```

**Expected behavior:**
```javascript
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var A = (function () {
    function A() {
    }
    return A;
}());
var B = (function (_super) {
    __extends(B, _super);
    function B() {
        // comment
        return _super.call(this) || this;
    }
    return B;
}(A));
```
**Actual behavior:**
```javascript
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var A = (function () {
    function A() {
    }
    return A;
}());
var B = (function (_super) {
    __extends(B, _super);
    function B() {
        return 
        // comment
        _super.call(this) || this;
    }
    return B;
}(A));
```

**Comment by dardino** [comment] 2016-12-14 11:29
[duplicated](https://github.com/Microsoft/TypeScript/issues/12906)

**Comment by RyanCavanaugh** [comment] 2016-12-14 17:41
I can't repro this on the 2.1.6 branch or in master. Can you verify your version (`tsc -v`) ?

**Comment by mhegazy** [comment] 2016-12-14 19:56
what is `2.1.6`? that version does not exist any where.

**Comment by mhegazy** [comment] 2016-12-14 20:02
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/12764

**Comment by dardino** [comment] 2016-12-15 07:26
sorry, the version was 2.1.4

**Closed** 2016-12-15 07:51 UTC
Labels: Needs More Info
