### ISSUE TITLE
Type inference elimination bug shows Arthur Conan Doyle was right.

### ISSUE THREAD

**Issue by nickshanks** [microsoft/TypeScript#54388] opened 2023-05-25 08:20 UTC
# Bug Report

Type inference fails to notice when a possibility has been eliminated by prior code.
In the code example, there are only four possibilities: both x & y are true, only x is true, only y is true, neither x nor y are true.
The first if/return eliminates the last possibility.
The second if/return eliminates the first and second possibilities, leaving only the third, that y is true, but code that expects y to be truthy after this point (e.g. when y is an object and you try to dereference a property) complains that y might be falsey (i.e. undefined/null) which we know it cannot be.

### 🔎 Search Terms

🤷🏻‍♂️

### 🕗 Version & Regression Information

$ npx tsc --version
Version 4.9.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcAUAPAXIgRqgGwFMBDMAGkQE8d85iyBKRAbwChFEZhE0BCDIgBkQxHyrMATkSghJYANwcuPTFJlzFyqgsQB6PYgAqAZURQAFjDABrAM7UuDgAZRJIIogA+yEgTtEznggUFyhEGSICARUeJ6u7oGIFkTSAHRsAL5sQA)

### 💻 Code

```ts
function yIsTrue(x: boolean, y: boolean) {
  if (!x && !y) return;
  if (x) return;
  y; // TS thinks y is `true | false` but it can only be `true` here.
}
```

bug also present when logic flipped:

```ts
function yIsFalse(x: boolean, y: boolean) {
  if (x && y) return;
  if (!x) return;
  y; // TS thinks y is `true | false` but it can only be `false` here.
}
```

### 🙁 Actual behavior

When hovering over it with the mouse cursor in VSCode, the type of `y` on third line of yIsTrue() resolves to `boolean` i.e. `true | false`.

### 🙂 Expected behavior

The type of `y` on third line of yIsTrue() should resolve to `true` here, and vice versa for yIsFalse()

“When you have eliminated all which is impossible, then whatever remains, however improbable, must be the truth.”

**Comment by MartinJohns** [comment] 2023-05-25 10:06
Essentially a duplicate of #54252.

**Comment by fatcerberus** [comment] 2023-05-25 12:18
Took me a second to realize that famous quote was what you were referencing with “Arthur Conan Doyle was right”; that was clever.  But yeah, the TS compiler is not actually Sherlock Holmes: https://github.com/microsoft/TypeScript/issues/52822#issuecomment-1434989002

**Closed** 2023-05-28 18:00 UTC
Labels: Duplicate
