### ISSUE TITLE
[Suggestion] switch import and from

### ISSUE THREAD

**Issue by timschwallie** [Microsoft/TypeScript#23496] opened 2018-04-18 03:50 UTC
Currently, the standard is something like
import { NgModule } from '@angular/core';
aka: import { class } from 'location'

Lets switch it to:
from 'location' import { class }

Currently, the flow is a bit non-intuitive with intellisense in IDE's.

For example, lets say a coder is working with a unfamiliar module:
the coder could type in
import {  } from '@angular/core';
Then they can go back to the { } to maybe see a list of available classes.

To be more intuitive, how about the coder can type in:
from '@angular/core' import {
once typed in, the IDE can present possible classes to use from the file at the 'from' location along with the class' comments.

I'm not sure how it could make things easier for the compiler code, cause of the standards.

**Comment by j-oliveras** [comment] 2018-04-18 10:06
Duplicate of #20773 and [already rejected](https://github.com/Microsoft/TypeScript/issues/20773#issuecomment-352798003).

**Closed** 2018-04-18 14:43 UTC
Labels: Duplicate
