### ISSUE TITLE
Can only access protected members from merged base class in constructor of derived class

### ISSUE THREAD

**Issue by NathanJPhillips** [Microsoft/TypeScript#17004] opened 2017-07-07 11:17 UTC
**TypeScript Version:**  2.4.1

**Code**

```ts
// Base1 is not merged so works fine
export class Base1 {
  protected constructor() { }
}

export class Derived1 extends Base1 {
  public static create() { return new Base1(); }      // No error
}

// Base2 is merged and exhibits the error
export class Base2 {
  protected constructor() { }
}

export class Derived2 extends Base2 {
  public static create() { return new Base2(); }      // Error
}

// Base3 is merged
export class Base3 {
  protected constructor() { }
}

// Here the error is worked around by accessing the protected member from the constructor
export class Derived3 extends Base3 {
  public constructor() { super(); }

  public static create() { return new Derived3(); }   // No error
}

declare module "./bug-demo" {
  interface Base2 {
    mergedMethod(): void;
  }
}

Base2.prototype.mergedMethod = function () { }

declare module "./bug-demo" {
  interface Base3 {
    mergedMethod(): void;
  }
}

Base3.prototype.mergedMethod = function () { }
```

**Expected behavior:**
No compilation errors.

**Actual behavior:**
`bug-demo.ts(16,35): error TS2674: Build:Constructor of class 'Base2' is protected and only accessible within the class declaration.`

**Comment by RyanCavanaugh** [comment] 2017-07-07 22:34
I don't see an error on line 16. Can you double-check that you posted the same code as you're trying to compile? Or perhaps post a minimum repro that demonstrates the issue?

**Comment by NathanJPhillips** [comment] 2017-07-08 09:59
I'm surprised you can't reproduce. If I make an empty folder and paste the code above into a file called `bug-demo.ts` I can then run the following commands:
```
C:\Users\Nathan.Phillips\Source\Repos\bug-demo>npm install typescript
C:\Users\Nathan.Phillips\Source\Repos\bug-demo
`-- typescript@2.4.1

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Nathan.Phillips\Source\Repos\bug-demo\package.json'
npm WARN bug-demo No description
npm WARN bug-demo No repository field.
npm WARN bug-demo No README data
npm WARN bug-demo No license field.

C:\Users\Nathan.Phillips\Source\Repos\bug-demo>node node_modules\typescript\bin\tsc -v
Version 2.4.1

C:\Users\Nathan.Phillips\Source\Repos\bug-demo>node node_modules\typescript\bin\tsc bug-demo.ts
bug-demo.ts(16,35): error TS2674: Constructor of class 'Base2' is protected and only accessible within the class declaration.

C:\Users\Nathan.Phillips\Source\Repos\bug-demo>
```

**Comment by RyanCavanaugh** [comment] 2017-07-09 22:51
Couldn't reproduce earlier because it wasn't apparent that the file itself has to be named `bug-demo.ts` (hence it doesn't repro in the Playground).

Shorter repro (note: filename matters)
```ts
// Base2 is merged and exhibits the error
export class Base2 {
  protected constructor() { }
}

export class Derived2 extends Base2 {
  public static create() { return new Base2(); }      // Error
}

declare module "./bug-demo" {
  interface Base2 {
    mergedMethod(): void;
  }
}
```

**Comment by RyanCavanaugh** [comment] 2017-07-09 22:51
@NathanJPhillips can I ask why you're merging a file *with itself* like that?

**Comment by NathanJPhillips** [comment] 2017-07-10 07:00
Obviously in real life you wouldn't do this, I only did it with the same file to give a simple repro of a problem I found when doing this across two files.

**Comment by mhegazy** [comment] 2018-07-20 00:12
Seems fixed in latest.

**Closed by mhegazy** 2018-07-20 00:12 UTC
Labels: Bug, Fixed
