### ISSUE TITLE
No object key completions on discriminated union of function signature and object literal

### ISSUE THREAD

**Issue by rozzzly** [Microsoft/TypeScript#13744] opened 2017-01-30 00:33 UTC
>**TypeScript Version:**  nightly (2.2.0-dev.20170129)

## Consider the following contrived example:
```typescript
type ZooAnimals = {
    a: 'alligator';
    b: 'baboon';
    c: 'cat';
    // ...
    o?: 'optional ostrich'
    // ...
};
type ZooKeeper = (name: string) => void;
type ZooResidents = ZooAnimals | ZooKeeper;
function VisitZoo(thingsToSee: ZooResident): void { /* ... */ }
```

### Expected behavior:
Typescript sees that the argument is an object literal and therefor `ZooKeeper` is discriminated out of the union. This leaves `ZooAnimals` as the only possible type. Language server proceeds to provide completions for **both the keys and values** of the `ZooAnimals` object literal.
```typescript
VisitZoo({
    '<key completions provided (ie: 'a', 'b', etc.)>':  '??',
    'c': '<value completion provided (ie: 'cat')>'
})
```
### Actual behavior:
No key completions are provided... However, **value completions are.** 
```typescript
VisitZoo({
    '<no key completions provided>':  '??',
    'c': '<value completion provided (ie: 'cat')>'
});
```
Manually providing a type assertion results in the desired behavior, but is quite tedious.
```typescript
VisitZoo({
    // works as desired
} as ZooAnimals);
```
Nor is this unique to function arguments:
```typescript
const zooTrip: ZooResidents = {
    // no key completions here either
};
```
Another thing I've noticed is:
```typescript
VisitZoo((name) => {
    // name's type is correctly inferred as string
});
```

I'm working on a (non-zoo themed) project that has a similar api (union of function & object literal) that would be much smoother for consumers to use if the desired behavior were there.

----

About a month back, I saw a post in one of this repo's issues that touched along the same lines as this. I searched for almost half an hour an was unable to find it, if anyone recalls where that was, please link it. IIRC however, that post didn't receive much attention so I deemed it prudent to post a detailed report of the problem myself in hopes that it might get fixed in the near future. Thanks for taking the time to review this, and thanks for all of your great work!

**Comment by mhegazy** [comment] 2017-01-30 20:54
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/6405

**Comment by rozzzly** [comment] 2017-02-10 01:48
@RyanCavanaugh anyway this could get added to the 2.3 milestone? :crossed_fingers: The issue @mhegazy linked has 4 other links so 6 total issues about this, it's something people want  :pray:

**Comment by mhegazy** [comment] 2017-02-11 01:29
The issue is marked as `Accepting PRs`. Be the PR you want to see in the world :)

**Closed** 2017-04-21 16:31 UTC
Labels: Duplicate
