### ISSUE TITLE
The actual type of the function return value is inconsistent with the expected type

### ISSUE THREAD

**Issue by lppking** [microsoft/TypeScript#44221] opened 2021-05-23 08:23 UTC
# Bug Report

### 🔎 Search Terms

spread operator, incorrect type check information,
### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about TS4.2.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/JYOwLgpgTgZghgYwgAgDLAM5gJKQLbIDeAUMsiHHhAFzJZSgDmpycjN5ArngEbTEBfYsRicQCMMAD2IZJCwAKAJS10WXBDwBtALpEWCGVlbIAvMi0kyZClVoBGADQsybDvYAcLATpZQIYJxQslbWAHQRcN6CQA)

### 💻 Code

```ts
interface ListItem {
  name: string
  age: number
}

function test(): ListItem[] {
  const a = [{
    name: "name",
    age: 18
  }]
  return {
    ...a
  }
}
```

### 🙁 Actual behavior

- First of all, the expected return value type is an array, but there is no error message when returning an object
- Secondly, TypeScript seems to have an array attribute on the return value of the test function, which is a bit abnormal

### 🙂 Expected behavior

I hope that the type information can be matched correctly, and the corresponding type error message will be given，thanks

**Comment by jcalz** [comment] 2021-05-23 13:27
Looks like a duplicate of #35778.

**Closed** 2021-05-24 10:58 UTC
