### ISSUE TITLE
function on class: method signature vs function type literal - same js output - one errors the other doesn't

### ISSUE THREAD

**Issue by stacey-gammon** [microsoft/TypeScript#38453] opened 2020-05-10 13:37 UTC
**TypeScript Version:**  3.8.3

**Search Terms:**

class function vs parameter error generic 

**Code**

Version 1, shows an error:
```ts
interface Renderer<Props extends object = object> {
  id: string;
  render: (props: Props) => void;
}

type Renderers = { [key: string]: Renderer };
const renderers: Renderers = {};

function addRenderer<P extends object>(renderer: Renderer<P>) {
  // Error: Type 'Renderer<P>' is not assignable to type 'Renderer<object>'.
  // Type 'object' is not assignable to type 'P'.
  //  'object' is assignable to the constraint of type 'P', but 'P' could be instantiated 
  // with a different subtype of constraint 'object'.
  renderers[renderer.id] = renderer;
}
```

Version 2, no error:
```ts
interface Renderer<Props extends object = object> {
  id: string;
  render(props: Props): void;
}

type Renderers = { [key: string]: Renderer };
const renderers: Renderers = {};

function addRenderer<P extends object>(renderer: Renderer<P>) {
  // No error
  renderers[renderer.id] = renderer;
}
```

**Expected behavior:**

The same result for each version, which, think should be that an error does show up. 

**Actual behavior:**

The latter version emits no comile error.

**Playground Link:** 

https://www.typescriptlang.org/play?#code/LAKA9GAEC0t-C6gpAagUwE4GcCWB7AO0gEYAuSAOX0i0302SkRflFF0IBcsAzAQwDG6SACV0hACZYsAHgAK9AA7ZaADx5TV+AEYArdIK6QAvJF0GjAPkgBvUJEi5JFbF0ycA5gG4HkTBLSmBQAFErK2BSK+CoAlKY2AG74zr4gAL7sIFwAnkoi4lIyOKZ2kADaANboOa7uXgC6FIVBWJDpaYJEbv6BxZFifQElZrYdWbwAroRGBMT8kpItxQrqmpLa+oZcViEBRcPNQ3LyVvH2II4oAKKY9JgAhH77rTjlL8UAdM4NpR-DaUyICYMFYYJBGBwc0gACYKNRaHcGCCwawspweJgBMJBgcsDCFBE1oFNpZjGYLNsbBdHM46h5CD5nkMwhEohFYhRkqlQEDQLl8rjXtgYaVbBVqrVIG4GZ4mkLiqLxiAuoQev8sCKjnicKLRsrQFMZlxoQslsdMAT5MStOYttY9hbta8rWc7H4UAi6AxPsydSL3hbvpJfmYNZhAUA

**Related Issues:**

**Comment by nmain** [comment] 2020-05-10 15:28
Duplicate of https://github.com/microsoft/TypeScript/issues/33610
Search terms: bivariant function

**Closed** 2020-05-11 14:38 UTC
Labels: Working as Intended
