### ISSUE TITLE
TypeScript references _this, but never assigns it

### ISSUE THREAD

**Issue by trevorsg** [Microsoft/TypeScript#13202] opened 2016-12-28 18:08 UTC
**TypeScript Version:**  2.1.4

**Code**

```ts
class A {
    constructor(param: any) {}
}
class B extends A {
    constructor() {
        super(() => this.foo());
    }
    public foo() { }
}
```

***Compiles to...***
****TS 2.0****
```ts
var A = (function () {
    function A(param) {
    }
    return A;
}());
var B = (function (_super) {
    __extends(B, _super);
    function B() {
        var _this = this;
        _super.call(this, {
            foo: function () {
                _this.foo();
            }
        });
    }
    B.prototype.foo = function () {
    };
    return B;
}(A));
```
****TS 2.1.4****
```ts
var A = (function () {
    function A(param) {
    }
    return A;
}());
var B = (function (_super) {
    __extends(B, _super);
    function B() {
        return _super.call(this, {
            foo: function () {
                _this.foo();
            }
        }) || this;
    }
    B.prototype.foo = function () {
    };
    return B;
}(A));
```

**Expected behavior:**
TypeScript emits an assignment to `_this` (otherwise issues a compile error)
**Actual behavior:**
TypeScript emits code that references `_this` but never declares or assigns `_this`.

**Comment by mhegazy** [comment] 2016-12-28 18:31
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/12764. The fix should be available in `typescript@next`. it should also be pushed out in TS 2.1.5 early January.

**Closed** 2016-12-28 18:31 UTC
Labels: Duplicate

**Comment by trevorsg** [comment] 2016-12-28 18:54
Thanks Mohamed!
