### ISSUE TITLE
Missing import qualification in declaration emit for generic parameters

### ISSUE THREAD

**Issue by Bobris** [Microsoft/TypeScript#27115] opened 2018-09-15 02:23 UTC
**TypeScript Version:**  Version 3.1.0-dev.20180914

**Code**

Let's have 3 TypeScript files:

bbb.ts:

```ts
export interface INode<T> {
  data: T;
}

export function create<T>(): () => INode<T> {
  return (undefined as any) as () => INode<T>;
}
```

lib.ts:

```ts
export type G<T extends string> = { [P in T]: string };

export enum E {
    A = "a"
}

export type T = G<E>;
```

index.ts:

```ts
import { T } from "./lib";
import { create } from "./bbb";

export const fun = create<T>();
```

**Expected behavior:**

when compiled with `tsc index -d` it generates valid index.d.ts:
```ts
export declare const fun: () => import("./bbb").INode<import("./lib").G<import("./lib").E>>;
```
or another valid would be:
```ts
export declare const fun: () => import("./bbb").INode<import("./lib").T>;
```

**Actual behavior:**

when compiled with `tsc index -d` it generates invalid index.d.ts:
```ts
export declare const fun: () => import("./bbb").INode<import("./lib").G<E>>;
```

**Comment by mattmccutchen** [comment] 2018-09-17 02:28
Possible duplicate of #26969?

**Comment by Bobris** [comment] 2018-09-17 06:11
Could be duplicate, why type `T` is expanded is another question. Sorry that I didn't found your reported bug.

**Closed** 2018-10-30 21:55 UTC
Labels: Bug, Domain: Declaration Emit
