### ISSUE TITLE
Add option for Array.prototype.fill to have no arguments

### ISSUE THREAD

**Issue by EnderShadow8** [microsoft/TypeScript#44887] opened 2021-07-04 03:15 UTC
# lib Update Request

## Configuration Check

My compilation *target* is `ES2020` and my *lib* is `ESNext`.

## Missing / Incorrect Definition

`Array.prototype.fill`

## Sample Code
```ts
const arr: number[][] = new Array(100).fill().map(() => new Array(100).fill(0))
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill
The lib.dom.ts is correct according to the spec, however, `Array.prototype.fill` is commonly called without arguments to eliminate any holes in an array which are otherwise skipped when calling `Array.prototype.map`. Useful for initialising an array of arrays, objects, etc.

**Comment by MartinJohns** [comment] 2021-07-04 05:49
Duplicate of #25392.

**Closed** 2021-07-08 18:00 UTC
Labels: Duplicate
