### ISSUE TITLE
-? (or Required<T>) swallows undefined during mapped types

### ISSUE THREAD

**Issue by entropitor** [microsoft/TypeScript#60255] opened 2024-10-17 10:07 UTC
### 🔎 Search Terms

swallows undefined -? mapped types

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.0-beta&ssl=15&ssc=1&pln=17&pc=1#code/C4TwDgpgBAKhDOwbmgXigbygezMAltgHYCGANgGL4RkAmA-AFxSIBO+RA5gNxRisIIRAMYQAShACOAV3wDaAIWnAAwiSIKIAVSK0IAMw4RazItIC2AIwisoAHyjTdBo7V4CZc480vZsZCHUoAF8AKFDQSCgAQTIAdxIQeABlYHYuAHlWHT1DImMAHhgAPih0DFCoKABtAGkIECgOKABrBux9KAlPeSLigF1mNg5Oe0dnPONuUODpyOgYAEYymPjElLSRrJyXfNoihCQUYtCAelOqqAA9ejOLq5w8QlJKajooAAsSeCgAK2lEFAAAbDLhAgA0UCI2HGuVc4XmqwSSVS6U42wmriyADlpGQyH0VhUqnUGk0iK12p1urJeiVBixNlwxk44XsxmZ8dNZhEULBFpYVrFkRs0Ri2YU4IhkJATudLjc7tdHgRiOQqDRaJ9vn8AcBgaDOBCoTDWbtjOFeVEAOr4YAfWKvTXwACiAA8wGR8MI7YTypUavVGs02iAOl0pLTJQNmBlzL6YJCg6UIG7gEJaD8YFB6LBSSB+hy8WQoMwYPn+ty5nyYAAmFa2+2OjV0V0er0+4AHaXHabyqqK+UACRs0DtUDi2FYLR++E6YekUBItC1ACIHJyyKvIfahFBd7DzVqSGBICRWD8SJwSBwAHT3oA

### 💻 Code

```ts
type TestType = { optionalField?: string; presenceRequiredButCanBeUndefined: number | undefined; required: boolean }

type AlwaysStringOrUndefined<T> = {
  [Key in keyof Required<T>]: string | undefined;
};
type T1 = AlwaysStringOrUndefined<TestType>
//   ^?
// ^ optionalField has just `string`, no undefined

type AlwaysStringOrUndefinedOrNull<T> = {
  [Key in keyof Required<T>]: string | undefined | null;
};
type T1b = AlwaysStringOrUndefined<TestType>
//   ^?
// ^ optionalField has just `string`, no undefined


type WithAllFieldsExplicit<T> = {
  [Key in keyof Required<T>]: Omit<T, Key> extends T ? T[Key] | null : T[Key];
};
type T2 = WithAllFieldsExplicit<TestType>;
//   ^?
// Here it works if you add "| null", then the undefined appears again... If you just do `| undefined` it gets swallowed
```

### 🙁 Actual behavior

The `| undefined` gets swallowed from mapped types when mapping from a type with optional fields which are removed through `Required<T>` or through `-?`

### 🙂 Expected behavior

The undefined should not be swallowed. Especially not when using `keyof Required<T>` instead of `-?`

**Comment by jcalz** [comment] 2024-10-17 10:29
Duplicate of #31025

**Closed** 2024-10-21 01:33 UTC
Labels: Duplicate
