### ISSUE TITLE
Remove automatic adding whitespace and semicolon with return statement

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#22401] opened 2018-03-08 08:40 UTC
**TypeScript Version:**  2.7.0-dev.20180302

**Search Terms:** 

**Code**

This is annoying especially as follows.

```ts
function f() {
  0
}
```

```ts
function f() {
  return ;0
}
```

With the plane code, this semicolon prevents to make a newline.

```ts
function f() {
  if (cond) return ;
  ;
}
```

It should be

```ts
function f() {
  if (cond) return
                  ^ cursor, no adding whitespace.
}
```
 or

```ts
function f() {
  if (cond) return;
                  ^ cursor, don't make duplicate semicolon as with closing brackets.
}
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:**  

**Related Issues:**

**Comment by andy-ms** [comment] 2018-03-08 16:02
It may be your editor doing this? With the default vscode settings I don't see any whitespace+semicolon getting added for me when I type `return`.

**Comment by falsandtru** [comment] 2018-03-08 16:22
Thanks for your info. But probably it is not true. Here is my settings.

```
// Place your settings in this file to overwrite the default settings
{
    "window.zoomLevel": 0,
    "workbench.colorTheme": "Visual Studio Dark",
    "vim.ignorecase": false,
    "vim.useSystemClipboard": false,
    "typescript.tsdk": "./node_modules/typescript/lib",
    "typescript.locale": "en"
}
```

I believe this problem is caused by update of TypeScript or VSCode. Probably this is the change of TypeScript in nightlies. I don't see this problem in Playground. Can you try again with typescript@next?

**Comment by andy-ms** [comment] 2018-03-08 16:42
Try testing with `code --disable-extensions`.

**Comment by falsandtru** [comment] 2018-03-08 16:49
I succeeded in reproducing it with `code --disable-extensions`.

**Comment by falsandtru** [comment] 2018-03-08 16:51
Here is the details.

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Linux x64 4.13.0-36-generic

Extensions disabled

**Comment by andy-ms** [comment] 2018-03-08 16:56
To clarify, the issue is that when you type `return`, a whitespace and semicolon appears? I've never seen any behavior like that from TypeScript, and I can't reproduce that using your vscode settings and `code --disable-extensions .` in an empty directory.

**Comment by falsandtru** [comment] 2018-03-08 17:10
Not correct a little. I type `ret` and choose `return` from suggested candidates. Then autocompletion inputs `return ;`.

**Comment by andy-ms** [comment] 2018-03-08 17:14
OK, now I see the issue -- there is an extra completion getting added by "TypeScript Support for VSCode". TypeScript's own completion is *also* available and doesn't include the semicolon. @mjbvz

**Comment by falsandtru** [comment] 2018-03-08 17:17
Thanks! I want to use the previous completion. The current completion is not useful.

**Comment by mjbvz** [comment] 2018-03-08 19:03
Duplicate of https://github.com/Microsoft/vscode/issues/45217 

I've reopened it on the vscode side

**Closed by mjbvz** 2018-03-08 19:03 UTC
Labels: Needs More Info
