### ISSUE TITLE
Unexpected `A class must be declared after its base class.` error with class expression

### ISSUE THREAD

**Issue by vvakame** [Microsoft/TypeScript#10624] opened 2016-08-31 04:28 UTC
**TypeScript Version:**  2.0.2

**Code**

```ts
let cat = new class extends class {
	speak() {
		return "???";
	}
} {
	speak() {
		return "meow";
	}
}();
console.log(cat.speak());
```

**Expected behavior:**

We can compile this code.

**Actual behavior:** 

```
$ tsc -v
Version 2.0.2
$ tsc sample.ts
$ sample.ts(1,29): error TS2690: A class must be declared after its base class.
```

This code can compiled by tsc 2.0.0.

**Comment by RyanCavanaugh** [comment] 2016-08-31 14:55
Isn't this illegal? What should `new class extends class` even do?

**Comment by RyanCavanaugh** [comment] 2016-08-31 14:56
You write some weird code :wink:

**Comment by vvakame** [comment] 2016-09-01 00:00
It is testcase 😉.

**Comment by kitsonk** [comment] 2016-09-01 02:35
Wow, that is [valid ES6](https://jsfiddle.net/zhbsoz5h/).  The crazy things people write.

**Comment by aluanhaddad** [comment] 2016-09-04 04:45
I don't know, this sample is making me warm up to class based programming in JavaScript ;) It's great when everything is first class!

**Comment by pankleks** [comment] 2016-09-12 16:13
Well actually it's real case when you don't use modules and you compile into single file.
Looks like in some cases TSC is lost with solving dependencies.
I have this issue with base class in one file / derived class in another.

I'm using TS 2.1 dev.
Checking on 2.0 RC ...

**Comment by pankleks** [comment] 2016-09-12 16:21
Same on 2.0.2 :(

**Comment by kitsonk** [comment] 2016-09-12 16:34
This is still an open issue, with a milestone target of being fixed in TypeScript 2.1.

Expecting it to be magically fixed before it is closed and marked as fixed and has an associated commit that has been merged into master is folly.

**Comment by pankleks** [comment] 2016-09-12 16:47
Just informing that's it's not regression of 2.1 as it exist on 2.0.2

**Comment by kitsonk** [comment] 2016-09-12 16:59
Which is what the issue was opened up under:

> **TypeScript Version**: 2.0.2

**Comment by RyanCavanaugh** [comment] 2016-09-12 18:30
@pankleks we pushed this to the 2.1 milestone because the provided repro is not realistic code. If you're still seeing this with "real" code we could use a repro -- this is something we'd fix for 2.0 in that case.

**Comment by pankleks** [comment] 2016-09-16 13:30
I have this issue constantly when using outFile and no modules.
I have lots of classes in multiple files, for majority of them it works - am'I just lucky or TSC have some logic to resolve dependencies?

**Comment by RyanCavanaugh** [comment] 2016-09-16 15:19
Your files will be ordered first according to any `reference` directives, then by the order they were specified as build inputs, then by luck and happenstance. But anyway you *should* only see this error in cases where the code *definitely* fails early at runtime. Can you provide a repro?

**Comment by pankleks** [comment] 2016-09-16 15:51
Will try to reproduce it on some small repo - can't share the one I'm mentioning here.
BTW - is there plan to introduce full dependency resolution to avoid "luck" scenarios?:)

**Comment by RyanCavanaugh** [comment] 2016-09-16 15:57
We strongly recommend using modules at this point. With the advent of good bundlers there's not much reason not to. If you can't for whatever reason, using `reference` paths to declare all your dependencies, or having a references.ts file that list all files in the desired order are the only good options.

**Comment by yortus** [comment] 2016-10-04 05:36
> we pushed this to the 2.1 milestone because the provided repro is not realistic code. If you're still seeing this with "real" code we could use a repro

@RyanCavanaugh I've just run into this with real code. Minimal repro below.

```ts
class Derived extends makeBaseClass() {} // ERROR class must be declared after base class

function makeBaseClass() {
    return class Base {};
}
```

The above works fine at runtime. It relies on `makeBaseClass` being hoisted to the top of the scope, and for various reasons we do not wish to unnecessarily move `makeBaseClass` to the top of the file.

**Closed** 2016-10-19 18:47 UTC
Labels: Bug

**Comment by aluanhaddad** [comment] 2016-10-23 22:17
Very fixed https://gist.github.com/aluanhaddad/acaa0ccfa7922a8d4be77b8f1489d283
