### ISSUE TITLE
Extended class's "super" class always assumed to return "void"

### ISSUE THREAD

**Issue by 00ff0000red** [microsoft/TypeScript#39758] opened 2020-07-27 05:55 UTC
**TypeScript Version:**  4.0.0-dev.20200725

**Code**

```ts
class T extends Array {
	constructor() {
		console.log(super(10) as any[]);
	};
};

new T;
```

**Expected behavior:**
Compiles cleanly, as `super` in this case refers to `Array`, as by using `Array(10)` we get an array of type `any` with `length === 10`.
**Actual behavior:**
TSC seems to think that `super` returns `void`, which is incorrect, and inconsistent with ECSMAScript / JavaScript itself. TSC seems to assume `super: (...items: any[]) => void` while `Array`'s type signature is `Array: (...items: any[]) => any[]` (*or more precisely: `Array: <T extends any[]>(...items: T) => T`*).

**Playground Link:** https://www.typescriptlang.org/play?ts=4.0.0-dev.20200725#code/MYGwhgzhAEDKAuZ4EtgEEBOGwE8A8AKtAKYAe8xAdgCYxiU4DaAugHwnlW3SbY7QBvAFABIYAHtKEeBgCuweOIwAKAHTrklAA6z4ALmgEAlINEiASsQBmIYgtVaMxAG5V4AUU5TkkiMoiyWsQq6qqaOvBGRgDcogC+sQlCQhJS4raqIOIA5sqiljZ28GEQnhTeAEa2eSIilMQA7nCIKOhYuMoAjAA00ABMvQDMvQAsvQCsvQBsvQDsRqILMUA

**Comment by MartinJohns** [comment] 2020-07-27 18:41
Duplicate of #37847, tho your issue is slightly better documented. Related to #38519 and #27594.

**Comment by 00ff0000red** [comment] 2020-07-28 09:54
> Duplicate of #37847, tho your issue is slightly better documented. Related to #38519 and #27594.

Oh... so should I just close this down?

**Closed** 2020-08-01 18:00 UTC
Labels: Duplicate
