### ISSUE TITLE
`satisfies` with functions

### ISSUE THREAD

**Issue by kaaax0815** [microsoft/TypeScript#53743] opened 2023-04-11 20:15 UTC
# Suggestion

## 🔍 Search Terms

satisifes, function

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

`satisifes` keyword works with functions

## 📃 Motivating Example

```ts
type AllowedTypes = string | number | boolean | symbol | object | undefined | null;
type LoaderType = () => AllowedTypes;
type LoaderReturn = ReturnType<LoaderType>;

function loader1(): AllowedTypes {
  return 'anything';
}

const value1 = loader1();
//     ^? value1: AllowedTypes 

function loader2() {
  return 'anything';
} satisfies LoaderType

const value2 = loader2();
//     ^? value2: string 

function loader3() {
  loader1()
} satisfies LoaderType
// ^? error: () => void does not satisfy () => AllowedTypes 
```

## 💻 Use Cases

In Libaries like [Remix](https://remix.run) you have a loader which has to return something other than `void`. But there is no good method to check for that
This would check that you return anything, but the frontend is still able to infer what types are returned

**Comment by MartinJohns** [comment] 2023-04-11 21:15
Sounds like a duplicate of #52902.

**Comment by kaaax0815** [comment] 2023-04-11 21:42
yes this only extends it with arrow functions and the already existing `satisfies` keyword

**Closed** 2023-04-12 19:05 UTC
Labels: Duplicate
