### ISSUE TITLE
behavior of `noUncheckedIndexedAccess` is inconsistent.

### ISSUE THREAD

**Issue by 13OnTheCode** [microsoft/TypeScript#57794] opened 2024-03-15 19:06 UTC
### 🔎 Search Terms

"noUncheckedIndexedAccess" "undefined"

### 🕗 Version & Regression Information

5.4.2

### ⏯ Playground Link

https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&exactOptionalPropertyTypes=false&noPropertyAccessFromIndexSignature=false#code/C4TwDgpgBAggTnKBeKBnYcCWA7A5gbQF0AoY0SKAFQEZlYF8AGEgehag4D0B+UgEwgBjADYBDONEEB7bOiji4ALnpxS02cCjBaKBU1bsOUHsSA

### 💻 Code

```ts
type Arr = string[]

type T1 = Arr[0]
//     ^?  type T1 = string

declare const arr: Arr

const t1 = arr[0]
//      ^?  const t1: string | undefined
```

### 🙁 Actual behavior

behavior of `noUncheckedIndexedAccess` is inconsistent.

### 🙂 Expected behavior

The type obtained from `type T1 = Arr[0]` should be `string | undefined`.

**Comment by RyanCavanaugh** [comment] 2024-03-15 19:12
Intentional; see discussion on this at #39560

**Comment by MartinJohns** [comment] 2024-03-15 19:13
Duplicate of #42471.

**Closed** 2024-03-15 19:13 UTC
Labels: Working as Intended
