### ISSUE TITLE
unknown type is narrowed to `{}` in strict equality condition since 4.8

### ISSUE THREAD

**Issue by 43081j** [microsoft/TypeScript#50567] opened 2022-08-31 15:02 UTC
# Bug Report

### 🔎 Search Terms

narrowing, object type, unknown, unknown narrowing

### 🕗 Version & Regression Information

- This changed between versions 4.7.x and 4.8.x
- Happens in nightly (4.9.x)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.2#code/MYewdgzgLgBAZiEMC8MAUA3AhgGwK4CmAXDHmANZggDuYAlCdAE4CWYA5igHwwDeAUDCEwWcdAEJs+AnT6DhCpgSh4mYGAHIEIDQG55QgL4GRYzLkIpkqDQA8AngC8NsgQsXLV6qYX0LjHipqmnr8hrpAA)

### 💻 Code

```ts
const foo = (value: unknown): string => {
    if (!value) {
        return 'foo';
    }
    if (value === 'xyz') {
        return value; // Type '{}' is not assignable to type 'string'.
    }
    return '';
};

// This one compiles fine
const bar = (value: unknown): string => {
    if (value === 'xyz') {
        return value;
    }
    return '';
};
```

### 🙁 Actual behavior

> Type '{}' is not assignable to type 'string'.

Even though we've clearly inferred that the `unknown` is literally the string `"xyz"`, the compiler somehow thinks it is instead `{}`.

### 🙂 Expected behavior

Builds fine.

### More info

You can see [here](https://www.typescriptlang.org/play?ts=4.8.2#code/MYewdgzgLgBAZiEMC8MAUA3AhgGwK4CmAXDHmANZggDuYAlCdAE4CWYA5igHwwDeAUDCEwWcdNnwEUyVAHIAHgE8AXrLp9BwrUwJQ8TMDAmEA3JqEBfczB16DMWbLMWTQA) that its specific to having the false-check at the start of the function.

Removing the `if(!value)` condition causes the code to compile as expected.

So it seems that turns the `value` into `{}` somehow.

**Comment by jcalz** [comment] 2022-08-31 16:10
This is working as intended as per #49119 and [documented in the TS4.8 release notes](https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#improved-intersection-reduction-union-compatibility-and-narrowing).

**Comment by fatcerberus** [comment] 2022-09-01 15:38
Related: #50531

**Comment by andrewbranch** [comment] 2022-09-01 22:58
I would have definitely marked this as a duplicate of #50531 if we hadn’t just traced #50531 to some code specific to the `in` operator...

[panda_smashing_computer.gif]

**Comment by andrewbranch** [comment] 2022-09-01 23:03
I mean, this actually makes total sense under long-standing narrowing rules plus the changes to `unknown` in #49119. Narrowing in most cases only happens on unions, and now `unknown` is equivalent to a union of `{} | null | undefined`. So narrowing it to `{}` is absolutely correct; the issue is we don’t narrow `{}` to `"xyz"`, but `{}` has never had to do that before. Maybe it should get some of the same special-case rules that narrowing `unknown` already had before becoming union-like.

**Comment by fatcerberus** [comment] 2022-09-01 23:24
> I would have definitely marked this as a duplicate of https://github.com/microsoft/TypeScript/issues/50531 if we hadn’t just traced https://github.com/microsoft/TypeScript/issues/50531 to some code specific to the in operator...

Yeah, #50531 is a weirder issue where the narrowing behavior for `{}` actually *differs* depending on whether it's a direct `{}` or came from narrowing `unknown`.

**Comment by fatcerberus** [comment] 2022-09-01 23:32
> now `unknown` is equivalent to a union of `{} | null | undefined`

I'm going to *hope* this isn't reflected under conditional type distribution the same way `boolean` is `true | false` because that sounds like a huge breaking change...

**Comment by andrewbranch** [comment] 2022-09-01 23:57
Sorry, did I say “equivalent”? I meant ✌️EQUIVALENT✌️***™️

<sup>*</sup> NOT ACTUALLY EQUIVALENT

**Closed** 2022-09-02 16:47 UTC
Labels: Bug, Fix Available
