### ISSUE TITLE
Destructuring type declarations

### ISSUE THREAD

**Issue by Ustice** [microsoft/TypeScript#57249] opened 2024-01-31 16:22 UTC
### 🔍 Search Terms

destructure type declaracters

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Destructuring properties from runtime objects added to the readability of Javascript. This convenience feature could be expanded to the type declarations. 

Note that this is just syntactic sugar. 

### 📃 Motivating Example

```Typescript
const Enums = {
  UserType: [ 'user', 'admin' ],
  PostType: [ 'feature', 'blog', 'other' ],
  HTTPMethod: [ 'get', 'post', 'patch', 'option', 'delete' ],
} as const

// How we need to create aliases now
type UserType = typeof Enums['UserType']
type PostType = typeof Enums['PostType']
type HTTPMethod = typeof Enums['HTTPMethod']

// Proposed 
type { UserType, PostType, HTTPMethod } = typeof Enums

namespace Types {
  type Foo = string
  type Goo = number
}

// Maybe this could work for namespaces too?

// Currently
type Foo = Types.Foo
type Goo = Types.Goo

// Proposed
type { Foo, Goo } = Types
```

### 💻 Use Cases

1. What do you want to use this for?

Clarity and convenience.

2. What shortcomings exist with current approaches?

It's verbose, which makes it harder to read.

3. What workarounds are you using in the meantime?

Setting aliases for each property separately.

**Comment by whzx5byb** [comment] 2024-01-31 17:06
Duplicate of https://github.com/microsoft/TypeScript/issues/35396

**Closed** 2024-02-03 01:23 UTC
Labels: Duplicate
