### ISSUE TITLE
Typescript compiler crashes when mapped type uses unknown type

### ISSUE THREAD

**Issue by lorefnon** [Microsoft/TypeScript#28927] opened 2018-12-09 07:08 UTC
**TypeScript Version:**  3.3.0-dev.20181208

**Search Terms:**
"type parameter: 181"

**Code**

```ts
export type Foo = {[I in (keyof Bar)]: Bar[I]} // Bar type is not defined
```

**Expected behavior:**
Compiler reports that Bar type is not defined

**Actual behavior:**
Compiler crashes and does not provide any information on what needs to be done to resolve the issue.

```
loref@DESKTOP-BBHGJ2D MINGW64 ~/Projects/ts-test (master)
$ yarn run tsc
yarn run v1.3.2
$ tsc
C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:71073
                throw e;
                ^

Error: Debug Failure. This is unknown parent for type parameter: 181
    at getTypeParameterConstraintVisibilityError (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:64666:37)
    at handleSymbolAccessibilityError (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:64792:33)
    at checkEntityNameVisibility (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:65116:13)
    at visitDeclarationSubtree (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:65262:25)
    at visitNode (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:53426:23)
    at Object.visitEachChild (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:53594:56)
    at visitDeclarationSubtree (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:65340:31)
    at visitNode (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:53426:23)
    at Object.visitEachChild (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:53592:57)
    at visitDeclarationSubtree (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:65340:31)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Playground Link:**  Not reproducible in playground

**Related Issues:** 

- https://github.com/Microsoft/TypeScript/issues/28728
- https://github.com/Microsoft/TypeScript/issues/25456

**Comment by lorefnon** [comment] 2018-12-09 07:09
A reproducer can be found in this repo: https://github.com/lorefnon/ts-issue-28927

**Comment by weswigham** [comment] 2018-12-10 22:10
Probably a duplicate of #25456

**Closed** 2018-12-12 10:00 UTC
Labels: Duplicate
