### ISSUE TITLE
Indirect distributed conditional allows invalid assignment

### ISSUE THREAD

**Issue by bookmoons** [microsoft/TypeScript#32070] opened 2019-06-24 19:05 UTC
**TypeScript Version:**  3.6.0-dev.20190623

**Search Terms:** conditional

**Code**

```ts
type BodyType = 'text' | 'numeric';
type MessageBody<BT extends BodyType> =
    BT extends 'text' ? string
    : BT extends 'numeric' ? number
    : never;
interface Message<BT extends BodyType> {
    body: MessageBody<BT>
}

declare function value<T>(): T;

// Direct distribution refuses to assign to a too narrow type
let bodyText: MessageBody<'text'>;
let bodyNumeric: MessageBody<'numeric'>;
bodyText = value<MessageBody<'text'>>(); // OK
bodyNumeric = value<MessageBody<'numeric'>>(); // OK
bodyText = value<MessageBody<'text' | 'numeric'>>(); // Correctly errors

// Indirect distribution of the same conditional allows the assignment
let messageText: Message<'text'>;
let messageNumeric: Message<'numeric'>;
messageText = value<Message<'text'>>(); // OK
messageNumeric = value<Message<'numeric'>>(); // OK
bodyText = value<Message<'text' | 'numeric'>>().body; // Correctly errors
messageText = value<Message<'text' | 'numeric'>>(); // Incorrectly OK
// messageText.body: string
// value().body: string | number
```

**Expected behavior:**

Cannot assign `Message<'text' | 'numeric'>` to `Message<'text'>`.

**Actual behavior:**

Allows assignment of `Message<'text' | 'numeric'>` to `Message<'text'>`.

[**Playground**](https://www.typescriptlang.org/play/#src=type%20BodyType%20%3D%20'text'%20%7C%20'numeric'%3B%0D%0Atype%20MessageBody%3CBT%20extends%20BodyType%3E%20%3D%0D%0A%20%20%20%20BT%20extends%20'text'%20%3F%20string%0D%0A%20%20%20%20%3A%20BT%20extends%20'numeric'%20%3F%20number%0D%0A%20%20%20%20%3A%20never%3B%0D%0Ainterface%20Message%3CBT%20extends%20BodyType%3E%20%7B%0D%0A%20%20%20%20body%3A%20MessageBody%3CBT%3E%0D%0A%7D%0D%0A%0D%0Adeclare%20function%20value%3CT%3E()%3A%20T%0D%0A%0D%0A%2F%2F%20Direct%20distribution%20refuses%20to%20assign%20to%20a%20too%20narrow%20type%0D%0Alet%20bodyText%3A%20MessageBody%3C'text'%3E%3B%0D%0Alet%20bodyNumeric%3A%20MessageBody%3C'numeric'%3E%3B%0D%0AbodyText%20%3D%20value%3CMessageBody%3C'text'%3E%3E()%3B%20%2F%2F%20OK%0D%0AbodyNumeric%20%3D%20value%3CMessageBody%3C'numeric'%3E%3E()%3B%20%2F%2F%20OK%0D%0AbodyText%20%3D%20value%3CMessageBody%3C'text'%20%7C%20'numeric'%3E%3E()%3B%20%2F%2F%20Correctly%20errors%0D%0A%0D%0A%2F%2F%20Indirect%20distribution%20of%20the%20same%20conditional%20allows%20the%20assignment%0D%0Alet%20messageText%3A%20Message%3C'text'%3E%3B%0D%0Alet%20messageNumeric%3A%20Message%3C'numeric'%3E%3B%0D%0AmessageText%20%3D%20value%3CMessage%3C'text'%3E%3E()%3B%20%2F%2F%20OK%0D%0AmessageNumeric%20%3D%20value%3CMessage%3C'numeric'%3E%3E()%3B%20%2F%2F%20OK%0D%0AbodyText%20%3D%20value%3CMessage%3C'text'%20%7C%20'numeric'%3E%3E().body%3B%20%2F%2F%20Correctly%20errors%0D%0AmessageText%20%3D%20value%3CMessage%3C'text'%20%7C%20'numeric'%3E%3E()%3B%20%2F%2F%20Incorrectly%20OK%0D%0A%2F%2F%20messageText.body%3A%20string%0D%0A%2F%2F%20value().body%3A%20string%20%7C%20number)

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/32066 - Some types are incorrectly assignable from a generic distributive conditional type

**Comment by jack-williams** [comment] 2019-06-24 23:10
This isn't related to #32066. The issue is that variance measurements mark the parameter in `Message` as bivariant, and as a consequence, you fail to get an error when relating `Message<'text' | 'numeric'>` to `Message<'text'>` because `'text'` is related to `'text' | 'numeric'`.

Duplicate of #31295.

**Closed** 2019-06-27 18:00 UTC
Labels: Duplicate
