### ISSUE TITLE
Strict null check can't "remember" array lookups

### ISSUE THREAD

**Issue by xnnkmd** [Microsoft/TypeScript#19829] opened 2017-11-08 10:52 UTC
**TypeScript Version:**
2.6.2 with "strictNullChecks" = true,

**Code**

```ts
interface Test {
  a?: {
    b?: {
      c?: number;
    }
  }[];
}

should_compile_but_does_not() {
    const data: Test = null as any as Test; // dummy value

    if (data.a && data.a[0].b && data.a[0].b.c) {
      const value: number = data.a[0].b.c;
    }
 }

```

**Expected behavior:**

The above should compile as all nullable values are checked before addressed.

**Actual behavior:**
Compiler errors:

![ts-limit](https://user-images.githubusercontent.com/26216976/32545173-21d1a778-c47b-11e7-9979-e2a3cbc7d750.PNG)

![errors](https://user-images.githubusercontent.com/26216976/32545151-137d45ba-c47b-11e7-8b1f-5df25f652a9a.PNG)

**Comment by andy-ms** [comment] 2017-11-08 15:13
Duplicate of #17567.

**Comment by ahejlsberg** [comment] 2017-11-08 16:51
Actually, duplicate of #10530.

**Closed** 2017-11-08 17:00 UTC
Labels: Duplicate

**Comment by xnnkmd** [comment] 2017-11-24 10:16
@ahejlsberg The duplicate you refer to has stalled because the dev could not provide an impl. that performed. Does this means we have to give up on getting strict null check to work on arrays ?
