### ISSUE TITLE
can't pass `--skipLibCheck` at command line when using `--build`

### ISSUE THREAD

**Issue by dinofx** [microsoft/TypeScript#41185] opened 2020-10-21 14:30 UTC
```
error TS5072: Unknown build option '--skipLibCheck'.
```

During development, my team uses a tsc watch task on a root tsconfig config that pulls in many other "project" tsconfigs.  **Only** during a development/watch build, we would like all of these projects to be built with skipLibCheck `true`, since it is ~5 times faster.

The only way to do this seems to be to duplicate every tsconfig file (over 25 files), since the CLI doesn't support passing this option through to the references projects' tsconfigs.

**Comment by MartinJohns** [comment] 2020-10-21 17:04
Please respect the issue templates for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) and [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Feature_request.md). :-) This will make the work for the TypeScript team much easier and they can focus on improving the language, instead of deciphering GitHub issues.

---

This is a duplicate of #25613.

**Comment by RyanCavanaugh** [comment] 2020-10-22 18:27
👆

**Closed by RyanCavanaugh** 2020-10-22 18:27 UTC
Labels: Working as Intended

**Comment by dinofx** [comment] 2020-10-22 21:58
@RyanCavanaugh thanks, I'm aware of the due diligence expected when opening an issue.  (I was an eclipse project lead for several years).  I did try searching for `skipLibCheck` for a duplicate issues (even closed ones).  If I had found "Allow regular flags to mix with --build", I would have gone out and bought a lottery ticket.
