### ISSUE TITLE
Abilities to prevent some symbols appeared in the completion list (or auto import)

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#46806] opened 2021-11-15 11:52 UTC
# Suggestion

## 🔍 Search Terms
completions, auto import

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add something （jsdoc? modifiers? etc.）to disallow a (or some) symbols be includes in the completion list。

## 📃 Motivating Example

```ts

//// a.ts

/*
* @hiden
*/
export const aaaaa = 1

//// b.ts

aa/*here*/

// The `aaaaa` who has been defined with hidden tag should not be included in the completion list 

```

## 💻 Use Cases

```ts

//// generated.ts
export type Request = {
//... 
}

// we do not want something like `Request` be included in completions (or auto import)
// because we may do some type level operation before use.

```

```ts

//// foo.d.ts

declare module "foo" {
  export * from "other-module"
}

// we do not want import from 'other-module', it's should from 'foo'.

```

**Comment by andrewbranch** [comment] 2021-11-15 21:20
Essentially a duplicate of #35395?

**Closed** 2021-11-18 18:00 UTC
Labels: Duplicate
