### ISSUE TITLE
[Bug]  '&' keyword Type recognition bug when used with array methods

### ISSUE THREAD

**Issue by rhkdgns95** [microsoft/TypeScript#49239] opened 2022-05-25 06:20 UTC
# Bug Report

### 🔎 Search Terms

`Generic Type` `Array` `& keyword` `map method`

### 🕗 Version & Regression Information
```
"typescript": "^4.4.3"
```

### 💻 Code

```ts
interface ITool {
  name: string;
  count: number;
}

interface IUser {
  name: string
  age: number;
  tools: ITool[];
}

const users: Array<
  IUser & { uid: number; tools: Array<ITool & { uid: number }> }
> = [
  {
    uid: 1,
    name: "Brian",
    age: 29,
    tools: [
      {
        uid: 1,
        name: "pen",
        count: 1,
      },
      {
        uid: 2,
        name: "book",
        count: 20,
      },
    ],
  },
];

users.map(user => {
  // Ok
  console.log('user.uid: ', user.tools[0].uid);
  
  user.tools.map(tool => {
    // Error
    console.log('tool.uid: ', tool.uid);
  });

  return user;
})

```

### 🙁 Actual behavior
![bug1](https://user-images.githubusercontent.com/46029124/170193173-3e606bc8-a0e6-40be-903c-f3de899d5f80.jpg)
![bug2](https://user-images.githubusercontent.com/46029124/170193168-5d8055db-763c-45ea-8743-6f319e7fd141.jpg)

![ezgif com-gif-maker](https://user-images.githubusercontent.com/46029124/170192994-d33cb60b-5540-4fd0-8386-70074cc9d3cd.gif)

### 🙂 Expected behavior
In the normal case, the `uid` field within the array (of 'users' or 'tools') should be resolvable.

**Comment by MartinJohns** [comment] 2022-05-25 08:10
Most likely a duplicate of #41874.

**Comment by rhkdgns95** [comment] 2022-05-25 08:13
@MartinJohns 

Oh, I see.
Confirmed with the same issue!

**Closed** 2022-05-29 18:00 UTC
Labels: Duplicate
