### ISSUE TITLE
Proposal: add  ?.  (Safe Navigation Operator)

### ISSUE THREAD

**Issue by vcrobe** [Microsoft/TypeScript#14389] opened 2017-03-01 17:19 UTC
I think the safe navigation operator **?.** introduced in C# v6 must be added to TypeScript.

More info about the operator here
https://blogs.msdn.microsoft.com/jerrynixon/2014/02/26/at-last-c-is-getting-sometimes-called-the-safe-navigation-operator/

**Comment by mhegazy** [comment] 2017-03-01 17:54
Duplicate of https://github.com/Microsoft/TypeScript/issues/16.

![image](https://cloud.githubusercontent.com/assets/8000722/23473431/0dc39de0-fe65-11e6-9330-3b63953f082d.png)

**Closed** 2017-03-01 17:54 UTC
Labels: Duplicate
