### ISSUE TITLE
error in type inference when using keyof

### ISSUE THREAD

**Issue by dardino** [Microsoft/TypeScript#15099] opened 2017-04-10 13:32 UTC
**TypeScript Version:**  2.2.1

**Code**

```ts
interface TestObj {
	P1: string;
	P2: number;
} 
function register<T, K extends keyof T>(pName: K, callback: (data: T[K]) => void): void { }
register<TestObj>("P1", data => {
   // data is string because "P1" is string
});
```

**Expected behavior:**
compile with no errors.
**Actual behavior:**
compile error:
[playground](https://www.typescriptlang.org/play/#src=interface%20TestObj%20%7B%09P1%3A%20string%3B%09P2%3A%20number%3B%7D%20%0D%0Afunction%20test%3CT%2C%20K%20extends%20keyof%20T%3E(pName%3A%20K%2C%20callback%3A%20(data%3A%20T%5BK%5D)%20%3D%3E%20void)%3A%20void%20%7B%20%7D%0D%0Atest%3CTestObj%3E(%22P1%22%2C%20(data)%20%3D%3E%20%7B%20%7D)%3B%0D%0Atest%3CTestObj%2C%20%22P1%22%3E(%22P1%22%2C%20(data)%20%3D%3E%20%7B%20%7D)%3B)
the only way I found is to write P1 "twice":
```ts
register<TestObj, "P1">("P1", (data) => { }); // compile ok, data type is correctly 'string'
```
but in my honest opinion this is not so good.

**Comment by jinder** [comment] 2017-04-10 17:09
@dardino does ```function test<T>(pName: keyof T, callback: (data: T[keyof T]) => void): void { }``` work for you?

**Comment by dardino** [comment] 2017-04-11 08:26
No.
Your example don't cover my case:
```ts
interface IMsg1 { p1: string; }
interface IMsg2 { pn: number; }
interface IMsg3 { pd: Date; }
interface IMessages { // interface that expose alla available messages
	M1: IMsg1;
	M2: IMsg2;
	M3: IMsg3;
}
// writing this:
function Register<T>(pname: keyof T, c: (m: T[keyof T]) => void): void {
}
// and then calling this:
Register<IMessages>("M1", (msg) => {
   // in this closure the var "msg" has three type: IMsg1 | IMsg2 | IMsg3
   // but I want only the type corresponding to "M1" that is IMsg1
});
```
to achieve this goal I need to write this:
```ts
function Register<T, P extends keyof T>(pname: P, c: (m: T[P]) => void): void {
}

Register<IMessages, "M1">("M1", (msg) => {
   // in this closure msg type is correctly IMsg1.
});
```

**Comment by dmichon-msft** [comment] 2017-04-12 01:04
The error is coming from the generic parameters. If you do:
```ts
declare function test<T, K extends keyof T>(obj: T, pName: K, callback: (data: T[K]) => void): void;
let obj: TestObj;
test(obj, 'P1', data => {
    // 'data' is inferred as 'string' here
});
```

TypeScript (as of the version in the playground) supports either specifying all generic parameters or none of them.

**Comment by dardino** [comment] 2017-04-18 14:54
In your example you need to give an object as first parameter.
I don't want this. I only want a constraint check between the 1st argument (message key) and 2nd argument (message body), another case:

```ts
// My framework defined method (framework doesn't know the available frames and their commands)
function SendCommandToIFrame<T, P extends keyof T>(key: P, msg: T[P]) {
	window.postMessage({
		command: key,
		body: msg
	}, "*");
}

// region User owned file:
type ImportCommand = { Name: string, Type: string };
type ExportCommand = { OriginalName: string, Type: string };

type AvailableIFrames = { Iframe1: ImportCommand, Iframe2: ExportCommand };

SendCommandToIFrame<AvailableIFrames, "Iframe1">("Iframe1", {
	Name: "prova.wav",
	Type: "audio/wav"
});

SendCommandToIFrame<AvailableIFrames, "Iframe2">("Iframe2", {
	OriginalName: "prova.wav",
	Type: "audio/wav"
});

```

**Comment by mhegazy** [comment] 2017-04-19 01:19
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/10571

**Closed** 2017-04-21 10:34 UTC
Labels: Duplicate
