### ISSUE TITLE
Union type overload inference don't match if types are in different definitions

### ISSUE THREAD

**Issue by kzarist** [microsoft/TypeScript#47480] opened 2022-01-17 15:23 UTC
# Bug Report

### 🔎 Search Terms

overload inference union type

### 🕗 Version & Regression Information
4.5.4
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about  it.

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEBsEsCMCcENYE9QDMCuA7AxgF0gPaagAmApqpJpPkQFB0Y63FTQBiWehmAFJCQBcoAM65YVAOagAPqEzoAttDKwAlMIBuBAQG5GXFhBidmPXtiIkaPEcIDeAbQDWZJMLETMkgLofxUgC+GqDaegZmRMYchuYCAPKwAMJWNkR2ogHesvJKKrA5Tq7umV6+-mXBWjokoPZ0oI2glpgiBOBkAHTgBJL8JIkpmNYsImr6gQwgoADuBLDOUqBkAB7wigAOHaC4ABbwuKCKB9i7ZCKg8KJS2+SU1CwR3FGKSADqCBsbqv0VS3IKZSqNT1JrRUzPPgCcZ0SZ0V4feBfH4AIjaijIeykKJhCM+31gvAATABmNQMOjTOYLJardZbMjNeBiJZ7RkbRDrHYES6YJCUsAAFX2uAA5BcZiLQABJWbwTCHXA8+BhEgC0DxdAFSzkUDQZmMyAXTyQPC82roERLAAG8qQ1tABDgkEk4AOZHVGO5oEtjOt5ygCoAtNYRPBoB0HWRNKokJLVIynkY8UiCQBBPn9QapUZ-bJyIpuPPlUpBEENJrTANUXAho3hjpBzCrWuBj1gtgQlhZ5I52yXC52mFwlPI2AZpC8NEEDFY7w4-Sj9OZ+yYdZkYQogBSBF2mBRwX06swUWpi2yM3xqnVAFEY8RIKgdmdYIzEIyCDHYD14CQLqhYBnPUCD2HYkG+ER1WFI1QAAK0tQ4SCIUVDksTZIG2JMeCOd4r1gIkeyGEZbGLQoXCLUtvD8SjJGCUEmk7WIiEIvt0mHBgl1UAjp1nXZsVxXDUy43hV3XTcdz3A9xiAA)

### 💻 Code

```ts
// library function definition

function libFunction(id: string | number): void;
function libFunction(conditions: {[key: string]: string}): void;
function libFunction(idOrConditions: string | number | {[key: string]: string}): void {
    console.log(idOrConditions);
}

// working example that matches a single definition
function myWrapper(id: string | number){
    libFunction(id);
}

myWrapper("something");
myWrapper(23)


// working example casting the param to any
// That's what I want to avoid
// Our code base is strict and using `any` obriglate
// me to use `eslint-disable` everywhere 
function myWrapperAny(idOrConditions: string | {[key: string]: string}){
    // eslint-disable-next-line
    libFunction(idOrConditions as any);
}

myWrapperAny("something");
myWrapperAny({name: "John"});

// non working wrapper
// Even if there are overloads from both types
// This just don't compile 
function myWrapper2(idOrConditions: string | {[key: string]: string}){
    libFunction(idOrConditions);
}

myWrapper2("something");
myWrapper2({name: "John"});
```

### 🙁 Actual behavior

No overload signature matches and code don't compile

### 🙂 Expected behavior

Overload signature matches and code compile

**Comment by whzx5byb** [comment] 2022-01-17 16:02
Duplicate of https://github.com/microsoft/TypeScript/issues/14107

**Closed** 2022-01-21 18:00 UTC
Labels: Duplicate
