### ISSUE TITLE
TypeScript should be able to support method overloading

### ISSUE THREAD

**Issue by series0ne** [Microsoft/TypeScript#11702] opened 2016-10-18 13:08 UTC
Since TypeScript is statically typed, it should be able to infer method usage based on supplied parameters, however I can already see a potential limitation in the emitted code - as long as JS is considered "read-only" this probably wont matter (much)

## Example

```
class Test {
    public getResult(value: string): boolean {
        ...
    }

    public getResult(x: number, y: number, z: number): string {
        ...
    }
}
```

## Compiled

```
var Test = (function () {
    function Test() {
    }

    Test.prototype.getResult$s0 = function(value) {
        ...
    }

    Test.prototype.getResult$n0$n1$n2 = function(x, y, z) {
        ...
    }

    return Test;
})();
```

**Comment by kitsonk** [comment] 2016-10-18 13:17
Dupe of #3442

**Comment by RyanCavanaugh** [comment] 2016-10-18 15:06
Please search for existing issues before logging new ones.

**Closed by RyanCavanaugh** 2016-10-18 15:06 UTC
Labels: Duplicate
