### ISSUE TITLE
Generic that extends a type with a generic

### ISSUE THREAD

**Issue by bgrieder** [Microsoft/TypeScript#5929] opened 2015-12-04 13:35 UTC
Say I have an interface

    interface Applicative<T> {}
Now I want to define a function f that:

 - takes a `Function` and takes a type `U` extending an `Applicative` wrapping `any`
 - returns an `U` wrapping `Function`

My naive attempts were   

      function f<U extends Applicative>(fn: Function, a: U<any>): U<Function>

and

      function f<T, U<T> extends Applicative<T>>(fn: Function, a: U<any>): U<Function>

but none is valid

Can we have a Generic extend a type with a generic ?

**Comment by sandersn** [comment] 2015-12-04 20:07
No, typescript doesn't have higher-kinded types.

**Comment by sandersn** [comment] 2015-12-04 20:08
Duplicate of #1213 and probably others.

**Comment by bgrieder** [comment] 2015-12-04 21:31
> Duplicate of #1213 and probably others.

Yes it is.  This can be closed

**Closed** 2015-12-04 21:32 UTC
Labels: Duplicate
