### ISSUE TITLE
incoming Safari 10.1 module support

### ISSUE THREAD

**Issue by gertcuykens** [microsoft/TypeScript#14861] opened 2017-03-26 11:43 UTC
I'm experimenting with Safari 10.1 and so far looking good, I am so happy to get rid of `/// <amd-module name="i_hate_doing_this"/>` and all the requirejs shenanigans

Basically you just do 

```html
<script type="module" src="scripts/index.js"></script>
```

in your html and we are in es2015 module world, FINALLY!

now the me starting to panic part, Safari 10.1 wants `import './menuelement.js';` not `import 'menuelement';`

Went trough https://www.typescriptlang.org/docs/handbook/module-resolution.html and I didn't notice mention of this.

Suggestion a new module mode named `es2015.js` that just replaces `import 'menu'` to `import './menu.js'` on compile time. PS also notice the required `./` part not only `.js`

```
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es2017",
    "module": "es2015.js", <========
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "sourceMap": true,
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```
PS I made a working Safari 10.1+ demo at https://github.com/gertcuykens/mollie-api-go Com'on TypeScript don't let me down on this, we are this close to getting rid of the webpack familie.

**Comment by jwbay** [comment] 2017-03-26 16:19
I asked about this when module resolution started to support baseUrl + path mapping. This was basically the answer - https://github.com/Microsoft/TypeScript/issues/5039#issuecomment-232470330. Maybe it could be revisited though.

**Comment by tkrotoff** [comment] 2017-08-29 08:31
Duplicate of #13422?

**Closed** 2019-09-16 21:37 UTC
Labels: Duplicate
