### ISSUE TITLE
Unique symbols are not preserved via destructuring

### ISSUE THREAD

**Issue by rockwotj** [microsoft/TypeScript#45068] opened 2021-07-16 15:26 UTC
# Bug Report

### 🔎 Search Terms

unique symbol, destructuring

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ + existing issues for entries about unique symbols

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.5#code/LAKAJgpgxgNghgJwgAigewHYGcAuyBmaaAXMgK4YCWAjmSlgJ4C2ARmjKKDgwA4oBiRZAF5k3PmnwEiAbk4h02PC0SlBaEdLRyQoRbmSIEaogG0AuptOE0AGmQqE5nfrxoWAK1IBvHBFwmaAC+mr7+OKQ2QTqgAPSxyAAqABaUWMgA7mgIANbp+JQYEMSgMBBuOYGaRqYADM6gaDma7h6mAER+uO0NIPHIAEJkeJC4CGRQOIUA5g5wAF7IZXBg6TgaEGVMEBg4axosKGBoGRjTCCsQYGIaAAaMrOy3epgGprQAHpaiRjplymRplVRJ8XK88GFcCFRK0dCxAZoujgZEA)

### 💻 Code

```ts
declare const foo: unique symbol
type Foo = typeof foo;
const bar: Foo = foo;
const arr: Foo[] = [foo, bar];
const obj: {test: Foo} = {test: foo};
// This works fine:
let ok: Foo = arr[0];
ok = obj["test"];
// But destructing arr or obj leads to elements to be downgraded to `symbol`
const [qux] = arr;
let bug: Foo = qux;
const {test} = obj;
bug = test;
```

### 🙁 Actual behavior

Type check error

### 🙂 Expected behavior

It to compile without type checking errors

**Comment by andrewbranch** [comment] 2021-07-20 22:49
Duplicate of https://github.com/microsoft/TypeScript/issues/43657:

> A `unique symbol` type is never transferred from one declaration to another through inference.

What’s happening in the destructuring examples is exactly the same as what would happen without destructuring if you didn’t add the explicit `: Foo` annotation on variable declarations:

```ts
const bar: Foo = foo; // ok
const bar2 = foo; // type is `symbol`

const ok: Foo = arr[0]; // ok
const ok2 = arr[0]; // type is `symbol`

const test: Foo = obj.test; // ok
const test2 = obj.test; // type is `symbol`
```

Writing `const { test } = obj` behaves exactly the same way that `const test = obj.test` behaves; the destructuring is irrelevant here.

**Comment by rockwotj** [comment] 2021-07-21 00:25
This is working as intended based on the referenced issue? That's disappointing. I don't understand**why** this is intended? What's the benefit?

**Comment by rockwotj** [comment] 2021-07-21 00:29
This also seems inconsistent with the rest of typescript. For example the type isn't widened when I do this:

```ts
declare const foo: 5;

const a = foo

// a's type is still 5
```

**Comment by RyanCavanaugh** [comment] 2021-07-21 16:56
The basic rule to understand is that `unique symbol` *always* widens to `symbol`. The desirability of this is based in the fact that, without this rule, you would frequently run into situations where the type of a `unique symbol` couldn't be named in its enclosing scope during declaration emit. A simple example:
```ts
function fn() {
  const u: unique symbol = Symbol();
  return function() {
    return u;
  }
}
const f = fn();
export const p1 = f();
export const p2 = f();
```
Now we need to emit a declaration file for this program. What should we do?
 * Issue an error and say that this code is illegal for... reasons?
 * Declaration-emit `p1` and `p2` as `: symbol`
 * *Incorrectly* claim that `p1` and `p2` have different `unique symbol` types

A declaration emit of `: symbol` is *correct* and not burdensome. If you didn't like that emit, you could go (try to) write a type annotation on `p1` and `p2`, at which point the ununtterability of `u` becomes apparent.

If we just made a best-guess of the utterability of `unique symbol` originations, it'd be very easy to accidently render an originating symbol unutterable and break your downstream consumers randomly. Consistently *not* using `unique symbol` (or an equivalent `typeof` reference) is the most predictable behavior.

**Comment by rockwotj** [comment] 2021-07-21 17:29
Thank you for the detailed explanation.

**Closed** 2021-07-21 17:29 UTC
Labels: Duplicate
