### ISSUE TITLE
Compiler doesn't understand Partial<T> function argument without explicit cast

### ISSUE THREAD

**Issue by yvbeek** [microsoft/TypeScript#22229] opened 2018-02-28 15:06 UTC
**TypeScript Version:**  2.7.1 up to latest 2.8.0-dev.20180228

**Search Terms:** generics,type,inference

**Code**

```ts
interface IEntity {
  id: number;
}

class Student implements IEntity {
  id: number;
  name: string;
}

class Repository<T extends IEntity> {
  public filter(criteria: Partial<T>): T[] {
    return [];
  }

  public first(criteria: Partial<T>): T {
    return this.filter(criteria)[0];
    // Works fine
  }

  public find1(id: number): T {
    return this.first({ id });
    // Argument of type { id: number } is not assignable to parameter of type 'Partial<T>'.
  }

  public find2(id: number): T {
    return this.first({ id } as Partial<T>);
    // Works fine
  }
}

// Sample code
const repository = new Repository<Student>();
const p1 = repository.filter({ id: 10 });
const p2 = repository.find1(10);
const p3 = repository.find2(10);
```

**Expected behavior:**
The compiler should be able to figure out that an argument of `{ id: 10 }` is a valid argument to provide to a `Partial<T>` where `T extends IEntity`.

**Actual behavior:**
The compiler doesn't understand that `{ id: 10 }` is a valid argument without an explicit cast.

**Playground Link:**
[Playground Code](https://www.typescriptlang.org/play/#src=interface%20IEntity%20%7B%0D%0A%20%20id%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Student%20implements%20IEntity%20%7B%0D%0A%20%20id%3A%20number%3B%0D%0A%20%20name%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Repository%3CT%20extends%20IEntity%3E%20%7B%0D%0A%20%20public%20filter(criteria%3A%20Partial%3CT%3E)%3A%20T%5B%5D%20%7B%0D%0A%20%20%20%20return%20%5B%5D%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20public%20first(criteria%3A%20Partial%3CT%3E)%3A%20T%20%7B%0D%0A%20%20%20%20return%20this.filter(criteria)%5B0%5D%3B%0D%0A%20%20%20%20%2F%2F%20Works%20fine%0D%0A%20%20%7D%0D%0A%0D%0A%20%20public%20find1(id%3A%20number)%3A%20T%20%7B%0D%0A%20%20%20%20return%20this.first(%7B%20id%20%7D)%3B%0D%0A%20%20%20%20%2F%2F%20Argument%20of%20type%20%7B%20id%3A%20number%20%7D%20is%20not%20assignable%20to%20parameter%20of%20type%20'Partial%3CT%3E'.%0D%0A%20%20%7D%0D%0A%0D%0A%20%20public%20find2(id%3A%20number)%3A%20T%20%7B%0D%0A%20%20%20%20return%20this.first(%7B%20id%20%7D%20as%20Partial%3CT%3E)%3B%0D%0A%20%20%20%20%2F%2F%20Works%20fine%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Sample%20code%0D%0Aconst%20repository%20%3D%20new%20Repository%3CStudent%3E()%3B%0D%0Aconst%20p1%20%3D%20repository.filter(%7B%20id%3A%2010%20%7D)%3B%0D%0Aconst%20p2%20%3D%20repository.find1(10)%3B%0D%0Aconst%20p3%20%3D%20repository.find2(10)%3B%0D%0A)

**Related Issues:**

**Comment by andy-ms** [comment] 2018-02-28 15:14
Note that the following is not sound:
```ts
function f<T extends { x: number }>(): Partial<T> {
    return { x: 0 };
}
interface I { x: 1 | 2 | 3; }
const i: Partial<I> = f<I>();
```

However, the following should work:
```ts
function f<T extends { x: number }>(x: T["x"]): Partial<T> {
    return { x }; // Does not work even with `x: x as any`
}
interface I { x: 1 | 2 | 3; }
const i: Partial<I> = f<I>(1);
```

**Comment by Zyphrax** [comment] 2018-02-28 17:06
Intellisense in VS Code also indicates something's wrong:
```typescript
public first(criteria: Partial<T>): T {
    // criteria.id seems to be a T["id"] instead of number
    
    let typedCriteria = criteria as Partial<IEntity>;
    // typedCriteria.id is a number as expected
```

**Comment by RyanCavanaugh** [comment] 2018-02-28 17:09
@andy-ms what's the behavior changed implied by the "bug" label? I think this is WAI, for the same reason as the one shown by your example

**Comment by RyanCavanaugh** [comment] 2018-02-28 17:19
Misread the intent of "should" up there

**Comment by Zyphrax** [comment] 2018-03-02 12:55
WAI = work as intended? I don't believe this is working as intended.
In my example the `{ id } as Partial<T>` explicit cast shouldn't be necessary IMO.

**Comment by andy-ms** [comment] 2018-03-02 15:16
It's marked as a bug -- we should make the second example in my comment work, but it doesn't work right now.

**Comment by mhegazy** [comment] 2018-03-02 17:29
@andy-ms you do not need `Partial` in your example above. I would argue that the correct signature here is 
```ts
function f<T extends { x: number }>(t: T): { x: T["x"] } {
    return { x: t.x };
}
```

The current behavior is really how it is intended to behave. we have two affordances for `T` being assignable to `Partial<T>`, and `{}` being assignable to `Partial<T>`. I assuming the proposal here is to add a new rule where `{ x: Y }` is assignable to `Partial<T>` if for all `x`, `Y` is assignable to `T["x"]`.

**Comment by andy-ms** [comment] 2018-03-02 17:34
>  I assuming the proposal here is to add a new rule where { x: Y } is assignable to Partial<T> if for all x, Y is assignable to T["x"].

:+1:
In the original example we can't just make the type be `{ id: T["id"] }` because we want to support other criteria too.

**Comment by RyanCavanaugh** [comment] 2021-06-24 18:57
This is a correct error; if allowed, the code would be unsound
```ts
interface IEntity {
  id: number;
}

class Student implements IEntity {
  id!: 42;
  name!: string;
}

class Repository<T extends IEntity> {
  public filter(criteria: Partial<T>): T[] {
    return [];
  }

  public first(criteria: Partial<T>): T {
    return this.filter(criteria)[0];
    // Works fine
  }

  public find1(id: number): T {
    return this.first({ id });
    // Argument of type { id: number } is not assignable to parameter of type 'Partial<T>'.
  }

  public find2(id: number): T {
    return this.first({ id } as Partial<T>);
    // Works fine
  }
}

// Sample code
const repository = new Repository<Student>();
const p2 = repository.find1(10);
const n: 42 = p2.id; // 10 inhabits 42
```

**Closed by RyanCavanaugh** 2021-06-24 18:57 UTC
Labels: In Discussion, Suggestion

**Comment by yvbeek** [comment] 2021-06-24 19:23
@RyanCavanaugh Thank you, that example really helps!

I'm still trying to wrap my head around why this then wouldn't work:

```typescript
interface IEntity {
  id: number;
}

class Student implements IEntity {
  id!: 42;
  name!: string;
}

class Repository<T extends IEntity> {
  public filter(criteria: Partial<T>): T[] {
    return [];
  }

  public first(criteria: Partial<T>): T {
    return this.filter(criteria)[0];
    // Works fine
  }

  public find1(id: T["id"]): T {
    return this.first({ id });
    // Argument of type { id: T["id"] } is not assignable to parameter of type 'Partial<T>'.
  }

  public find2(id: T["id"]): T {
    return this.first({ id } as Partial<T>);
    // Works fine
  }
}

// Sample code
const repository = new Repository<Student>();
const p2 = repository.find1(42);
```

Doesn't `{ id: T["id"] }` satisfy `Partial<T>`?

**Comment by RyanCavanaugh** [comment] 2021-06-24 19:48
Shortened (discussing this offline)
```ts
function fn<T extends { id: number }>(id: T["id"]): Partial<T> {
    return { id };
}
```
