### ISSUE TITLE
the build result is wrong

### ISSUE THREAD

**Issue by yuu2lee4** [Microsoft/TypeScript#21624] opened 2018-02-05 09:01 UTC
original code:
```javascript
import User from '../models/user';
import * as ldap from '../utils/ldap';

import User from '../models/user';
import * as ldap from '../utils/ldap';

export const register = async ctx=>{
    ctx.body = 'register';
}

export const ldapLogin = async ctx=>{
    try {
        const { username, password } = ctx.request.body;
        const isValid = await ldap.ldapQuery(username, password);
        console.log('isVaild', isValid);

        let user:any = await User.findOne({username});

        if (!user || !user._id) {
            user = new User({
                username,
                password,
            });
            user = await user.save();
        }
        delete user.password
        ctx.session.user = JSON.parse(JSON.stringify(user))
        console.log(123);
        ctx.body = {code:0,data: ctx.session.user}
    } catch (e) {
        console.log(e);
        return ctx.body = {code: 401, msg: e.message};
    }
}

export const logout = async ctx=>{
    ctx.body = 'logout';
}
```

when i run `tsc -w`,it get the right reslut:
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const user_1 = require("../models/user");
const ldap = require("../utils/ldap");
exports.register = async (ctx) => {
    ctx.body = 'register';
};
exports.ldapLogin = async (ctx) => {
    try {
        const { username, password } = ctx.request.body;
        const isValid = await ldap.ldapQuery(username, password);
        console.log('isVaild', isValid);
        let user = await user_1.default.findOne({ username });
        if (!user || !user._id) {
            user = new user_1.default({
                username,
                password,
            });
            user = await user.save();
        }
        delete user.password;
        ctx.session.user = JSON.parse(JSON.stringify(user));
        console.log(123);
        ctx.body = { code: 0, data: ctx.session.user };
    }
    catch (e) {
        console.log(e);
        return ctx.body = { code: 401, msg: e.message };
    }
};
exports.logout = async (ctx) => {
    ctx.body = 'logout';
};
//# sourceMappingURL=user.js.map
```

but when i save the original code again no matter i modify the code or not, it get the wrong result:
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.register = async (ctx) => {
    ctx.body = 'register';
};
exports.ldapLogin = async (ctx) => {
    try {
        const { username, password } = ctx.request.body;
        const isValid = await ldap.ldapQuery(username, password);
        console.log('isVaild', isValid);
        let user = await user_1.default.findOne({ username });
        if (!user || !user._id) {
            user = new user_1.default({
                username,
                password,
            });
            user = await user.save();
        }
        delete user.password;
        ctx.session.user = JSON.parse(JSON.stringify(user));
        console.log(123);
        ctx.body = { code: 0, data: ctx.session.user };
    }
    catch (e) {
        console.log(e);
        return ctx.body = { code: 401, msg: e.message };
    }
};
exports.logout = async (ctx) => {
    ctx.body = 'logout';
};
//# sourceMappingURL=user.js.map
```

here is my tsconfig.json:

```javascript
{
    "compilerOptions": {
        "target": "es2017",//将编译的.ts文件编译为指定标准js
        "module": "commonjs",//模块规范
        "sourceMap": true, //生成资源映射，以便于调试
        "noEmitHelpers": true,//不生成辅助方法，对应importHelpers
        "importHelpers": true,//引用外部的辅助方法 
        "allowUnreachableCode": true,//允许代码中途return产生无法执行代码
        "lib": ["es2017"],//定义编译时依赖 
        "allowJs": true,
        "typeRoots": ["node_modules/@types"],//定义类型定义文件的根目录
        "outDir": "./build" //编译输出文件目录，默认等于rootDir
    },
    "exclude": [
        "build",
        "node_modules", //忽略目录
        "**/*.test.ts" //忽略指定类型文件
    ] 
}
```
and my ts version is 2.7.1.

**Comment by DanielRosenwasser** [comment] 2018-02-05 09:23
Here's the diff between the two:

```diff
- const user_1 = require("../models/user");
- const ldap = require("../utils/ldap");
```

**Comment by DanielRosenwasser** [comment] 2018-02-05 09:26
I'm not able to reproduce the issue in TypeScript 2.7.1 or in the nightlies. Can you confirm that `tsc -v` is definitely giving you the right version @yuu2lee4? @sheetalkamat can you give it a quick shot?

**Comment by yuu2lee4** [comment] 2018-02-05 09:40
Yeah, it is the right ver 2.7.1, my system is macOS 10.13.3, VScode's version is 1.19.3.What is strange is only one file being transpiled to wrong. If needed,I can give you all my code.

**Comment by Dom-HMH-MTL** [comment] 2018-02-05 17:18
I confirm the regression: 
- correct behavior with `tsc --watch` 2.6.2, 
- correct behavior with `rm -rf dist/; tsc` 2.7.1, 
- failure with `tsc --watch` 2.7.1.

**Comment by sehrope** [comment] 2018-02-05 17:49
I confirm this on Linux x64 with node 8.9.4 and Typescript 2.7.1. The first compile of a watch works correctly. A delta build triggered by saving a changed file does not.

The bad compiled file is missing a bunch of `const = require(...)` clauses at the top of the file that was saved. Oddly it's not missing all of them and I don't see a particular pattern to the one's that it is missing, though it is consistently missing the same ones. Besides the missing require clauses everything else is the same between the bad / good outputs.

**Comment by sehrope** [comment] 2018-02-05 18:14
I just tried with `@next` (2.8.0-dev.20180204) and I think the problem is resolved.

**Comment by mhegazy** [comment] 2018-02-05 19:01
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/21478. The issue should be fixed in `typescript@next` and in the upcoming `typescript@2.7.2` release.

**Closed** 2018-02-05 19:02 UTC
Labels: Duplicate
