### ISSUE TITLE
Union types aren't always narrowed properly after predicate functions

### ISSUE THREAD

**Issue by dplumlee** [microsoft/TypeScript#35299] opened 2019-11-22 20:29 UTC
**TypeScript Version:**  3.8.0-dev.20191122

**Search Terms:**
union types, narrowing, guarding 
**Code**

```ts
// Imagine redux here. Redux reducers get actions from various places. They have a vague type
type Action = {
  type: any
}

// Our app has 2 actions
type ActionA = {
  type: 'a'
  payload: () => void
}

type ActionB = {
  type: 'b'
  payload: string
}

// This type is a union of all of em. They have distinct types, which can 
// be used to discriminate them
type AllOurActions = ActionA | ActionB

// This function takes any action, and determines if it happens to
// be one of ours. If so, it narrows the action's type
declare function isActionOneOfOurs(action: Action): action is AllOurActions

// This is how you could narrow our action type to a specific action type
declare const wereSureAlready: AllOurActions
// This guard usually works
if (wereSureAlready.type === 'a') {
  // Since the `type` property is 'a', we know the payload is a function
  // since 'b' actions have a string payload
  wereSureAlready.payload()
}

// We got this action in our reducer.
// It could be from anywhere(e.g.redux dev tools or a third party lib)
declare const someGivenAction: Action

// If this is true, we know the action is one of ours
if (isActionOneOfOurs(someGivenAction)) {
  // can be narrowed by switch
  switch (someGivenAction.type) {
    case 'a': someGivenAction.payload()
  }
  // can't with other stuff?
  if (someGivenAction.type === 'a') {
    // Why doesn't this work if someGivenAction was narrow by a predicate
    // function. 
    someGivenAction.payload()
  }

  // it works if you rebind it
  const worksIfYouRebindIt = someGivenAction
  if (worksIfYouRebindIt.type === 'a') {
    // Why doesn't this work if someGivenAction was narrow by a predicate
    // function. it works if you cast it
    worksIfYouRebindIt.payload()
  }
}
```

**Expected behavior:**
Action type properly narrowed by the predicate function and an `if` statement

**Actual behavior:**
Action type not narrowed unless you rebind it prior to narrowing or a `switch` statement is used

**Playground Link:** 
http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=58&pc=2#code/PTAEEkFsEMHMEsB2BTUAnZATArgD1ABbIYB0oASlnulQMbEDOosyALqNLa-APaJMAzND0igAbtDS9sTAA4AbTsgZkAKkQCehaGNTRxcbKlYbZyAFAmzoAIJdeiUAF5QAb3OhQV5AC4OiDXMAX3NzEFAAeWw0DllZbSYAJg57PgZLU1Q7bj4bZzcPL0y-AHJoEsLZaA15HmhMPwAKAEpnAD5xHnhMYNDvW1TEACF8909vUoAjCs8qmrqG0AZWKURYXrCwdXgmfp2OUGxEB1AeAQ55eVPz5Eg1TW1dUEwd7kQuIrMGABpQAHcCPBaARQLRoI5NqBJqgZFgvDxnjtaFJIEhoKxjERIBlrDZLlE0NkHEwXETcqAAD4DHLDULhbaCI6DLzQADWyn8Wk4NN+4MwzzYxFRKCY8HO8HYBGgcWQ-HhkOhpxQ11O0RUEHODB4vwloEQkmEf12RBSNJKu0y5kwyFoigwoAETJpoB2ZMQERQEQEBIYjW5Dj8buafn9fBdTDx8gJbvSkIZ4cIPD+oA0PGwoLT8n5+rQhtVMVDjn6rAR+gYZloYqBppO3itNrtqFoaXYf2IyAAytFkHiMPUNIH8dEY3HAUxYNhJPyZJPLlo-jw0Kz0mLQI02xguxhe8h+yR+k5D6AyiVWmNQOEO0h6F4TQADbx30CyYRmNAmBMn35t0CsxBJ29UDmWp6gTfRHXeGlCnCBhr1QEpphrNJHj0JYViQWBn2qECek8DdO27Hc92AhYWg2cIAHVUFgHh2FYMckMcJB8xoHB6DQEhIXAdhm2wLMoVQIQRE5AF20aZASFgEgMBwfBrTEeEeHkJhFwOej4DQfkqnfLR5HgSZmnrW1JCbFslhEZAAHF4F0RA3UDQY6TAcBznU0VdjQIxv1QP8APovRmX2PhUDOfMV3ORpXUGD1kC9H1Gi1SArJs2UgzPaCwDBRxFRzQ04UmLQGD+CVgUKIqSpBBKLOs2y3X3TJ0s8TwwQYeDyj8RLktqwYSBI+oyM8EJPHCLKSlbCUQVoogYmWbABAEAB+QpVyqpKatSnqDyPE9GqayiCC0TAeGURAxtvfYFyXF1NWqlK7OZP5oCYXKAIKg4XywIF0QsJqLzACCetAQpPE69b7ppXrsNIwzBtCYawF1S7l2ulM0xoSYkH5CVCmbfhW0XZcXIATTTSgMcQTBuPyUG7rdZaIqRhhidJ5Bycp1h6usQ8XB2gpfv2w7joYU66IYpGUZp7rnUe56DVerlnxkr6MWBv6HSdBwyERgnRXOVN0xa9hsd+xnmewMnMe4yH5n6mHQBCIIgA
**Related Issues:** 
Couldn't find anything directly related

**Comment by nmain** [comment] 2019-11-22 20:48
Duplicate of https://github.com/microsoft/TypeScript/issues/13962

**Comment by oatkiller** [comment] 2019-11-22 20:59
This shows that the binding can be narrowed despite not being a union, as long as its narrowed with a switch statement: http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=27&pc=2#code/C4TwDgpgBAggxsAlgewHZQLxQN4CgpSiQBcUAhqiLgL665HTxJoyY76HgSkDkZPHMGRAAbZGQAmpABQBKTAD4oAN2SIJNOg1gIUqAEJs8BBrwBGAgkNHipUAM7AATolQBzTfS6wRIgPIArk5MevZsISxQAD46zAZ0EhBwImRO0ABmAai6aFCI9hGofqgQfumBTvbSZDmopIWypDVxeWEwvhWF9glJKWlQcGiODsgAthAA4ojKEKiF9bV0APRLUACS6YQAFvmthE4BEAA0UADu0ADWqMin29DNento0MibyEHdiJvS+YXFpeUPtJ7GNJtNZg15MYoCsBhQoGZoKhUk4bhAJAiQA5TohgHAthx7Di8VsoMDQVMZnNagA6BhQjgEOBkezQPg8Ugg8aUiG06xiSRyDi0ahAA
```ts
type Action = {
  type: any
}

type ActionA = {
  type: 'a'
  payload: () => void
}

type ActionB = {
  type: 'b'
  payload: string
}

type AllOurActions = ActionA | ActionB

declare function isActionOneOfOurs(action: Action): action is AllOurActions

declare const someGivenAction: Action

// If this is true, we know the action is one of ours
if (isActionOneOfOurs(someGivenAction)) {
  // can be narrowed by switch
  switch (someGivenAction.type) {
    case 'a': someGivenAction.payload()
  }
}
```

**Comment by RyanCavanaugh** [comment] 2019-11-22 21:15
Duplicate  #30557

**Comment by fatcerberus** [comment] 2019-11-23 04:12
> Narrowing by discriminant only applies when the declared type of the identifier is a union type

What makes the `switch` statement different that narrowing works for that but not for `if`?  I couldn't find anything in the linked issues that explained this discrepancy.

**Closed** 2019-11-25 18:00 UTC
Labels: Duplicate
