### ISSUE TITLE
Error 2367 on second same check after modification

### ISSUE THREAD

**Issue by wgebczyk** [microsoft/TypeScript#53220] opened 2023-03-12 20:33 UTC
# Bug Report

### 🔎 Search Terms

- This comparison appears to be unintentional because the types 'false' and 'true' have no overlap (2367)
- This comparison appears to be unintentional because the types
- error 2367
   - seems similar to #50839, but inline modification does not result in error

### 🕗 Version & Regression Information

- I've just spotted that in newly written code

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAEzgSSgCgJSIN4BQiiECAzlIsADYCGA5mYgLz5HFV30BcVt1ZAKYAadgF8A3AXahIsBCQAWtMPUEZMwXnk4NeAIzhxqglYjHZeANzgxkbDlQB0NBi0RQATiEFTiY6WIYYERNLjIXLhZmVi8fXEJHT0EoEE8wP3N2CGVVdSxXRmxM4NDCiMLo2O9BBPZiZNT0zICAoA)

### 💻 Code

(BTW: Why you are asking for playground and code here?)
```ts
function doIt() {
  const flags = {
    flag: false,
  };

  function changeIt(f: { flag: boolean }): void {
    f.flag = true;
  }

  if (flags.flag === true) {
    return;
  }
  changeIt(flags);
  if (flags.flag === true) {
    return;
  }
}
```

### 🙁 Actual behavior

There is error.

### 🙂 Expected behavior

There should be no error as if changeIt function is inlined to `flags.flag = true;`

**Comment by MartinJohns** [comment] 2023-03-12 20:58
Duplicate of #9998.

**Closed** 2023-03-12 21:00 UTC
