### ISSUE TITLE
get array from const enum

### ISSUE THREAD

**Issue by wangzhilongh** [microsoft/TypeScript#38960] opened 2020-06-06 10:57 UTC
I hope there is a way to get an array from const enum.

for example:

const enum gender{
 male = 1,
 female = 2,
}

I need to there is a way to get an array from the const enum gender, and the result like this: 
[1,2]

Thanks a lot!

**Comment by wangzhilongh** [comment] 2020-06-06 11:03
const enum gender{
male = 1,
female = 2,
}
const genderValue = gender.toArray() // maybe just like this

**Comment by MartinJohns** [comment] 2020-06-06 12:39
Duplicate of #21391.

**Comment by Harpush** [comment] 2020-06-06 16:23
I am pretty sure he meant to allow some syntax that like const enum which is replaced with literal strings at runtime will be replaced with the literal array of the const enum options.
So if we have say:
```ts
const enum Test {
  A = 'a',
  B = 'b'
}
const values = valueof Test;
```
It will get compiled to `const values = ['a', 'b']`

**Comment by wangzhilongh** [comment] 2020-06-06 16:37
Yes. Please implement it.
Thanks!

**Comment by fatcerberus** [comment] 2020-06-08 05:11
> It will get compiled to const values = ['a', 'b']

This would be type-directed emit, which is unlikely to be implemented.  See point 5 at https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals:
> 5. [Do not] Add or rely on run-time type information in programs, or **emit different code based on the results of the type system**. Instead, encourage programming patterns that do not require run-time metadata.

**Comment by Harpush** [comment] 2020-06-08 05:19
@fatcerberus Which means const enum goes against it too... I believe its just an enhancement to the already existing functionality

**Comment by RyanCavanaugh** [comment] 2020-06-08 17:15
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Closed by RyanCavanaugh** 2020-06-08 17:15 UTC
Labels: Unactionable

**Comment by HKhademian** [comment] 2023-05-03 07:49
```
enum X { A='A', B='B'};
const enum Y { A='A', B='B'};
```
every `enum` is defining a group of related values

we can use them like:
```
const x:X = X.A;
const y:Y = Y.A;
```
compiles to
```
const x = X.A;
const y = 'A';
```

then it is logical to have also a way to access the whole group of values.
like:
``` const Xs = Object.values(X);```
and (((or any other syntax which doesn't matter at all)))
``` const Ys = valuesof Y; ```
then they compile to:
``` const Xs = Object.values(X);```
and
``` const Ys = ['A','B'];```
