### ISSUE TITLE
Type guards in switch statement

### ISSUE THREAD

**Issue by Mosho1** [Microsoft/TypeScript#19861] opened 2017-11-09 06:15 UTC
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```
function foo(baz: boolean | (() => boolean)) {
    switch (typeof baz) {
        case 'boolean':
            break;
        case 'function':
            baz();
            break;
    }
}
```

**Expected behavior:**

Should compile, similar to the equivalent usage of `if` statement type guards.

**Actual behavior:**

Does not compile with error:

`[ts] Cannot invoke an expression whose type lacks a call signature. Type 'Boolean' has no compatible call signatures.`

**Comment by mhegazy** [comment] 2017-11-09 17:07
Duplicate of https://github.com/Microsoft/TypeScript/issues/2214

**Closed** 2017-11-27 18:38 UTC
Labels: Duplicate
