### ISSUE TITLE
Strict mode: deep check if property is initialized

### ISSUE THREAD

**Issue by pmattke** [Microsoft/TypeScript#28200] opened 2018-10-29 12:58 UTC
## Search Terms

optional property definitely initialized

## Suggestion

When I implement a class, where the constructor calls an `init()` method or so, properties that are initialized in that method have to be made optional, because typescript thinks they are not definitely initialized in the constructor

## Use Cases

An `init` method makes sense if you want some kind of `reset` functionality in your class but don't want (or can't) just create a new instance of it. So you would want to put all your initialization code into that `init` method, so you can call it from the constructor as well as from your `reset` method. The problem there is, that all properties that are initialized in the `init` method, have to be made optional, although they are definitely initialized in the constructor (which is by calling the `init` method

### Currently:

The following code compiles:

```
  private prop: string;

  constructor() {
    this.prop = 'asdf';
  }
```

The following code does not compile:

```
  private prop: string;

  constructor() {
    this.init();
  }

  private init() {
    this.prop = 'asdf';
  }
```

It says: `[ts] Property 'prop' has no initializer and is not definitely assigned in the constructor.`

The fix would be to make `prop` optional:

`private prop?: string;`

### Requested

I think there is, in such examples, no way how the property could *not* be initialized. So Typescript should even check for methods called in the constructor, and if it sees there that properties are definitely initialized, the code posted above should compile without problems.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by weswigham** [comment] 2018-10-29 18:33
Duplicate of #21132

**Closed by weswigham** 2018-10-29 18:33 UTC
