### ISSUE TITLE
instanceof typeguard fails if classes have similar structure

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#7271] opened 2016-02-26 23:38 UTC
**TypeScript Version:** 

1.8.x and nightly

**Code**

```ts
class C1 { item: string }
class C2 { item: string[] }
class C3 { item: string }

function Foo(x: C1 | C2 | C3): string {
    if (x instanceof C1)
        return x.item;
    else if (x instanceof C2)
        return x.item[0];
    else if (x instanceof C3)
        return x.item; // Error property item does not exist on C2
}
```

**Expected behavior:**
Code should compile

**Actual behavior:** 
Code has an error as shown 

# More 

 The following works i.e. if `C1` and `C3` differ in structural compatibility: 

```ts
class C1 { item: string }
class C2 { item: string[] }
class C3 { items: string }

function Foo(x: C1 | C2 | C3): string {
    if (x instanceof C1)
        return x.item;
    else if (x instanceof C2)
        return x.item[0];
    else if (x instanceof C3)
        return x.items; // Ok
}
```

:rose:

**Comment by ivogabe** [comment] 2016-02-27 09:08
I'm afraid this is by design. I get a lot trouble with this too, so I hope this could be changed. Adding a brand to one of the classes fixes it, but I don't like that approach very much. I think `x instanceof C1` should only remove `C1` in the else branch, not both `C1` and `C3`, or it shouldn't remove any types in the else branch. The current behavior doesn't match what happens at runtime, for instance this does not give any compile error:
```typescript
function Foo(x: C1 | C2 | C3): string {
    if (x instanceof C1)
        return x.item;
    else
        return x.item[0];
}
```
The type of `x` is `C2` in the else block, but at runtime it could also be `C3`.

**Comment by yortus** [comment] 2016-02-27 11:25
I've also run into this problem, and wish that the compiler behaviour could be brought more into line with what happens at runtime. It's not specific to `instanceof`, it's really just about the structural similarity of the types in the union. E.g., this works fine at runtime, but fails at compile time:

```ts
type UnaryFunction = (a: any) => any;
type BinaryFunction = (a: any, b: any) => any;
function isUnaryFunction(fn: Function) : fn is UnaryFunction {
    return fn.length === 1;
}
function isBinaryFunction(fn: Function) : fn is BinaryFunction {
    return fn.length === 2;
}
function foo(fn: UnaryFunction | BinaryFunction) {
    if (isBinaryFunction(fn)) {
        fn(1, 2);   // OK: fn is BinaryFunction here
    } else {
        fn(1);      // ERROR: Cannot invoke an expression whose type lacks a call signature
    }
}
```

I think the problem is similar to @basarat's, because from a structural typing viewpoint, a `UnaryFunction` is just a subtype of a `BinaryFunction`, triggering different narrowing behaviour than if the types were structurally independent. However there is no subtype relationship according to the runtime checks in `isUnaryFunction` and `isBinaryFunction`.

---

Here is another case that brings up this type guard behaviour because the compiler sees the types as structurally related. Consider a function that takes either (a) an options object, where all options are optional, or (b) a function that returns an options object:
```ts
interface OptionsObject {
    option1?: string;
    option2?: number;
}
interface OptionsFunction {
    (): OptionsObject;
}
function isOptionsObject(opts: OptionsObject | OptionsFunction) : opts is OptionsObject {
    return opts && typeof opts === 'object'; // definitely not a function
}
function bar(opts: OptionsObject | OptionsFunction) {
    let option1: string;
    if (isOptionsObject(opts)) {
        option1 = opts.option1 || 'none';   // ERROR: no option1 on OptionsObject|OptionsFunction
    } else {
        option1 = opts().option1 || 'none'; // OK
    }
}
```

---

I have learned how to spot and work around these cases now. But that involves taking valid runtime code, and rearranging it just right so the compiler won't complain. It's a (rare) case where the tool is fighting me rather than helping me. Probably also quite unintuitive for beginners.

**Comment by yortus** [comment] 2016-02-27 11:48
@basarat here is a version of your example without `instanceof`. It has the same error as your example, which is why I think this is about the structural type similarity and not related to the presence of `instanceof`:

```ts
class C1 { item: string }
class C2 { item: string[] }
class C3 { item: string }

function isC1(c: C1 | C2 | C3): c is C1 { return /*some test*/ }
function isC2(c: C1 | C2 | C3): c is C2 { return /*some test*/ }
function isC3(c: C1 | C2 | C3): c is C3 { return /*some test*/ }

function Foo(x: C1 | C2 | C3): string {
    if (isC1(x))
        return x.item;
    else if (isC2(x))
        return x.item[0];
    else if (isC3(x))
        return x.item; // Error property item does not exist on C2
}
```

**Comment by yortus** [comment] 2016-02-27 12:05
Another example, this time with `typeof`, that's *maybe* the same problem? Since `Function` is a subtype of `Object`. But isn't `string` also a special case of `Object` structurally? Not sure about this one...

```ts
function ok(x: string | Object) {
    if (typeof x === 'string') {
        x // string
    }
    else {
        x // Object
    }
    if (typeof x === 'object') {
        x // Object
    }
    else {
        x // string
    }
}


function fail(x: Function | Object) {
    if (typeof x === 'function') {
        x // Function | Object
    }
    else {
        x // Function | Object
    }
    if (typeof x === 'object') {
        x // Function | Object
    }
    else {
        x // Function | Object
    }
}
```

**Comment by falsandtru** [comment] 2016-03-13 02:53
+1 this behavior is buggy.

**Comment by falsandtru** [comment] 2016-05-06 16:46
from #6589 because it merged into this issue.

---

# Type narrowing strategy for most closest type selection

Narrowing to the closest runtime type by `instanceof` operator:

```ts
class A<T> {
    prop: T;
}
class B<T> extends A<T> {
}
class C extends B<any> {
}

var x: A<string> | B<any> | C;
if (x instanceof A) {
    x; // closest type is A, now B
}
if (x instanceof B) {
    x; // closest type is B, now B
}
if (x instanceof C) {
    x; // closest type is C, now B
}
if (x instanceof Object) {
    x; // closest type is A, now B
}
if (x instanceof Array) {
    x; // no closest type, must be contextual type `A<string> | B<any> | C`
}
```

## Motivation

Sometimes we must check the instance type instead of pattern matching. TypeScript should provide the way that select the most closest type for alternate method of pattern matching.

```ts
// maybe monad
  public bind<U>(f: (val: T) => Maybe<U>): Maybe<U> {
    return new Maybe<U>(() => {
      const m: Just<T> | Nothing | Maybe<T> = this.evaluate();
      if (m instanceof Just) {
        return f(m.extract());
      }
      if (m instanceof Nothing) {
        return m;
      }
      if (m instanceof Maybe) {
        return (<Maybe<T>>m).bind(f); // `m` is `Nothing | Maybe<T>`, should be `Maybe<T>`
      }
      throw new TypeError(`ArchStream: Maybe: Invalid monad value.\n\t${m}`);
    });
  }
```

Searching and showing of all derived types is useless and too complex when there are many derived types, and TypeScript should reduce those unnecessary costs for optimization.

```ts
class A<T> {
    prop: T;
}
class B<T> extends A<T> {
}
class C extends B<any> {
}

var x: A<string> | B<any> | C;
if (x instanceof A) {
    x; // this scope narrowed by A, B and C are useless, but x is B
}
```

In general, sets of types must narrow by operations, but `instanceof` operator widen types. Roles and effects of typings for abstraction is reducing of calculation size based on sets size.

```ts
class A<T> {
    a: T;
}
class B<T> extends A<T> {
	b: T;
}
class C extends A<any> {
    c: any;
}

var x: A<string> | B<string> | C;
if (x instanceof A) {
    x; // x should narrow to A of the most closest type from `instanceof` operator specified type.
    // if you want B or C, it should narrow by those types.
}
```

`instanceof` operater compare constructors in js engine, but TypeScript compiler compare structural types. It is mismatch behavior.

**Comment by mhegazy** [comment] 2016-05-06 20:03
As noted in #8503, classes should be treated definitely for instanceof checks. 

note this applies to instanceof type guards only, and not for user defined type guards; the later stays structural as we have no guarantees on how they will be implemented, where as instanceof is known to always be nominal.

**Comment by mprobst** [comment] 2016-06-30 17:09
Another example, in this case TS picks the `never` type:

```ts
class A { field: string; }
class B { field: string; }

function f(x: A|B) {
  if (x instanceof A) {
    x.field; // all good.
  } else if (x instanceof B) {
    x.field;  // error: no property `field` on `never` type.
  }
}
```

**Closed** 2016-08-09 05:14 UTC
Labels: Committed, Suggestion

**Comment by yortus** [comment] 2016-08-09 11:51
Just retried all the examples on this page with the nightly, and they all work except for the `UnaryFunction | BinaryFunction` one (which I know was not addressed by #10216). Nice that as well as the OP example, the other non-`instanceof` examples all work now too. CFA is getting very good indeed.

**Comment by kitsonk** [comment] 2016-09-15 13:28
I just wanted to mention that I came across a situation where TypeScript does treat classes nominally.  We (Dojo 2) have a `Promise` shim which introduced a protected property named `_state`.  While at run-time we load the same module, when we are developing we will often `npm link` in development branches of our packages and those packages then import in physically different locations of the `.d.ts` UMD file from the shim package.  Once that occurs, TypeScript then starts to complain that `Promise<T>` is not assignable to `Promise<T>` because they are different class instances.  We worked around the issue by npm linking in the package to all the other dependent packages, so the `class Promise` definition was coming from exactly the same physical file location, but I will admit it was surprising to see TypeScript treat it this way, especially with the "TypeScript is structural typing" booming in my head.

I guess the thought there will be quite a few other surprises like that, where for various reasons the typings appear to be nominally distinct but they are actually the same at run-time.

**Comment by mhegazy** [comment] 2016-09-15 17:19
`private` and `protected` properties are nominal. treating them structurally defies the whole point of visibility modifiers.

**Comment by mkusher** [comment] 2016-10-14 22:35
Is this a problem with structural classes or wrong if-else instanceof?
```js
class Foo {
    foo: string;
}

class Bar {
    bar: string;
}

function test(x: Foo | Bar) {
    if (x instanceof Foo) {
        x.foo.toUpperCase()
    } else { // somewhy x is Bar here
        x.bar.toUpperCase();
    }
}
test({ foo: 'foo' });
```

**Comment by yortus** [comment] 2016-10-14 23:44
@mkusher at runtime, obviously `{foo: 'foo'}` is not an instance of the `Foo` class so you end up in the `else` block.

At compile time, the only questionable thing here is the last line, where the compiler allows the call to `test` with an argument that is not a `Foo` or a `Bar`. That's where structural typing comes into play. AFAIK TypeScript sees no difference in type between `new Foo()` and `{foo: 'foo'}` in this case.

**Comment by mkusher** [comment] 2016-10-15 08:16
@yortus I understand why it happens so now, but the question is more about what needs to be fixed: type guard(if-else instanceof) or nominal classes

**Comment by kitsonk** [comment] 2016-10-15 09:24
@mkusher the core team are looking at a solution for this under #202 (and this ticket).  It will be some form of nominal support most likely, but something that doesn't break/incompatible with the rest of the structured typing system.

**Comment by mikelehen** [comment] 2017-05-03 20:17
Why is this closed?  I've spent the last 20 minutes trying to find the canonical (open) issue on this, but I've failed.  There are lots of dupes, but the only open ones (at the moment) I can find are https://github.com/Microsoft/TypeScript/issues/11664 and https://github.com/Microsoft/TypeScript/issues/10934.  I assume they'll get closed as dupes eventually.  

This is the best bug to track I've found so far (best title and description).  I see #202 has been referenced a couple times as covering this issue, but it seems to be much broader and it's not obvious if/how it will address the concrete issue reported here where the compiler has chosen to implement "instanceof" different from how it behaves at runtime.

I ask because our code is getting littered with hacks to work around this behavior and I'd like to reference an appropriate issue so that we can easily check if/when it gets addressed.

I'd also love to see a solution for this sooner than later, since the behavior is non-intuitive and the resulting errors are varied and often appear nonsensical.

**Comment by kitsonk** [comment] 2017-05-03 21:17
This issue was closed by PR #10216 which the core team felt dealt partially with this issue, enough to close it.  For broader nominal type, that is still #202 and is on the [Future Roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap#future)

**Comment by mikelehen** [comment] 2017-05-04 16:25
Thanks @kitsonk.  I see that the specific issue here does seem to be solved.  I've gone ahead and opened new issues for the instanceof cases I'm still hitting.

**Comment by drewnoakes** [comment] 2017-11-17 01:28
See #19671 for a recent relevant merged PR.

**Comment by bennadel** [comment] 2018-01-24 12:57
I think I just ran into this issue as well on TypeScript 2.6.2. I have a method that looks like this:

```js
function ( target : Window | Element ) : string {
    if ( target instanceof Window ) {
        return( "__window__" );
    } else {
        return( target.tagName );
    }
}
```

I get `Property 'tagName' does not exist on type 'Window'.`. It doesn't matter if I change it to be `else if ( target instanceof Element )`. Seems like what other people are seeing.

**Comment by mikelehen** [comment] 2018-01-24 19:33
It'd be useful to know what version you're on, since https://github.com/Microsoft/TypeScript/pull/19671 fixed a bunch of issues in this area...

**Comment by bennadel** [comment] 2018-01-24 19:59
@mikelehen according to my npm package (I'm using TS through ts-loader in WebPack), I'm on versions:

```json
"ts-loader": "3.3.0",
"typescript": "2.6.2",
```

**Comment by RyanCavanaugh** [comment] 2018-01-24 20:16
The fixes are in TypeScript 2.7

**Comment by bennadel** [comment] 2018-01-24 20:54
@RyanCavanaugh Ahhh, player. I didn't realize there was a new version. Time for a bit of the old `npm outdated` :)

**Comment by kitsonk** [comment] 2018-01-24 20:57
TypeScript 2.7 is still only an RC at the moment:

```
$ npm view typescript
{ latest: '2.6.2',
     next: '2.7.0-dev.20180124',
     beta: '2.0.0',
     rc: '2.7.0-rc',
     insiders: '2.7.0-insiders.20180119' }
```
