### ISSUE TITLE
Type inference for keys in for...in loops

### ISSUE THREAD

**Issue by Mosho1** [Microsoft/TypeScript#12988] opened 2016-12-16 22:37 UTC
**TypeScript Version:**  2.1.4

**Code**

```ts
const obj = {x: 1, y: 2};
for (let k in obj) {
   const prop = obj[k];
}

```

**Expected behavior:**
```
let k: "x" | "y";
let prop: number;
```

**Actual behavior:**
```
let k: string;
let props: any;
```

**Comment by ahejlsberg** [comment] 2016-12-16 23:08
Duplicate of #12314.

**Closed** 2016-12-19 18:00 UTC
Labels: Duplicate
