### ISSUE TITLE
Proposal: foreach loop

### ISSUE THREAD

**Issue by vadimzzz** [Microsoft/TypeScript#3835] opened 2015-07-13 07:25 UTC
The most common case of iterating an object is:
```javascript
var object = {a:1, b:2, c:3};
for (var key in object) {
	if (!object.hasOwnProperty(key)) {
		continue;
	}
	var value = object[key];
	// do stuff here
}
```
and for arrays is:
```javascript
var array = ['a', 'b', 'c'];
for (var i = 0; i < array.length; i++) {
	var value = array[i];
	// do stuff here
}
```

It would be very useful if TypeScript provide a simple foreach loop that can combine both of above.
Something like this (PHP style):
```javascript
foreach (object as key => value) {
	// do stuff here
}
```
and for arrays:
```javascript
foreach (array as i => value) {
	// do stuff here
}
```
Needed type of underlying for-loop should depend on the type of iterating variable.
If compiler cannot definitely determine variable type (whether it's an array or object) - it should use for..in loop and show a warning

**Comment by OlegDokuka** [comment] 2015-07-13 07:35
in TS available next format of foreach loop expresion

``` Typescript 
let array = ["a","b","c"];
array["qwerty"] = 123456;
for(let val of array){
     console.info(val);
}
/// in console we will see something like "a", "b", "c", 123456

for(let key in array){
     console.info(key);
}
/// in console we will see something like 1, 2, 3, "qwerty"

**Comment by tinganho** [comment] 2015-07-13 07:35
I also hate the for loops in JS/TS, but I think that the problem is in ES/TC39 and not in TypeScript. Sometimes I just need the value in an array, so I use a `for..of` loop. But then, I find out that I need the index too, then I need to rewrite my for loop. Happens all the time for me.

I would rather just put an `index` variable in the current `for..of` loop:
```typescript
for(let index, value of values) { ... }
```

**Comment by kitsonk** [comment] 2015-07-13 12:16
What is wrong with?

```typescript
let array = [ "a", "b", "c" ];
array.forEach((value, index) => { ... });
```

**Comment by vadimzzz** [comment] 2015-07-13 12:23
You cannot use `this` inside the function without additional complications. 
And you cannot call `forEach` on objects

**Comment by kitsonk** [comment] 2015-07-13 12:26
> You cannot use `this` inside the function without additional complications.
> And you cannot call `forEach` on objects 

I was referring to @tinganho last use case.  I am questioning the value of adding something that is already functionally available and @tinganho says the "drawback" is sometimes needing the index and having to rewrite is code.

The fat arrow function will address the `this` scope complications.

**Comment by tinganho** [comment] 2015-07-13 13:22
@kitsonk same argument as all other syntaxes introduced in +ES6. Productivity and cleanness.  `forEach` can also not break a loop, continuing and go to outer loop with without dirty hacks.

I still think:
```typescript
for(let index, value of values) { ... }
```

is easier than:
```typescript
array.forEach((value, index) => { ... });
```
less punctuation tokens to type.

**Comment by DanielRosenwasser** [comment] 2015-07-13 16:54
> You cannot use `this` inside the function without additional complications. 

That was the reason arrow functions were introduced; they don't introduce a new `this` value.

**Comment by RyanCavanaugh** [comment] 2015-07-13 17:00
> I also hate the for loops in JS/TS, but I think that the problem is in ES/TC39 and not in TypeScript. 

Quoted for truth. We don't add non-ES control flow structures to the language, especially ones we hope might be addressed in the future.

**Closed by RyanCavanaugh** 2015-07-13 17:00 UTC
Labels: Out of Scope, Suggestion

**Comment by tinganho** [comment] 2015-07-14 02:50
Just brought the discussion to esdiscuss:
https://esdiscuss.org/topic/for-statement-with-index-and-value
