### ISSUE TITLE
TS2532: Object is possibly undefined

### ISSUE THREAD

**Issue by Dirain1700** [microsoft/TypeScript#49121] opened 2022-05-16 02:34 UTC
# Bug Report

### 🔎 Search Terms

TS2532, possibly undefined

### 🕗 Version & Regression Information

typescript@4.6.2
@types/node@17.0.33

Node.js v16.14.2
npm v8.1.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&jsx=0&module=1&filetype=ts#code/PTACBcEMCcHMFNwC4AE8DOA7eAPcAoEUAWwHsATAVwBt4AlDU6y8AS1M1UwvkLDKq1UAY1LEymAFbp85eMOox4KAG4wUAB2ilhGdKkiYAngG5Z8xdGVroKAMId0TeAeNmAFO4CUKALwA+FABvfBQwlFFMdHAUGFhUaOhWTFg-TW1ddHQAOjiVAG0AJgBdAEIzcIjHGJhoBPAklPzitK0dPVy4FQrw2hjkgDNSesbUgB8USkw5AeT4cjSpmbnyM1DwwdI0uLXK1gGUd02-X19J6fhZ7HIfEMrKyKdabOpSWHdmrx77lCtwSmgmG+KAAvvh1mFHs4Xm93LVsldyJ54D4AmgTmdNl4viAUAA5LbwaDaaAQqpRaGvd7wxHI1GBeAveApcAACwxKE2TJZrOxJlxAFFiaQ6igACoAZUKAFYAMyFVAAeQARpJ5P10JpSFlWMrqEZzstrmSoc8qUdMEMccB8YThbZ3GLWaxNS6qsT1V4TY5KbCubQedbbWh7fgQV5vCYgA)

### 💻 Code

```ts
//@target: esnext
//@moduleResolution: node
//@module: commonjs
declare var process: any;
declare var Console: any;
(() => {
    const arg: string = process.argv[2]!;
    const arr: string[] = process.argv;
    let info: string | undefined = undefined;

    info = arg;

    if (info === undefined) {
        console.log([]);
        return;
    }

    console.log(arr.find((e) => e === info));// No error
    console.log(arr.find((e) => e.length === info.length));// Error: TS2532: Object is possibly undefined
    console.log(info);// No error (This is correct)
    console.log(info.length);// No error
})();
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
(() => {
    const arg = process.argv[2];
    const arr = process.argv;
    let info = undefined;
    info = arg;
    if (info === undefined) {
        console.log([]);
        return;
    }
    console.log(arr.find((e) => e === info)); // No error
    console.log(arr.find((e) => e.length === info.length)); // Error: TS2532: Object is possibly undefined
    console.log(info); // No error (This is correct)
    console.log(info.length); // No error
})();

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "Latest",
    "module": "CommonJS",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?target=99&jsx=0&module=1&filetype=ts#code/PTACBcEMCcHMFNwC4AE8DOA7eAPcAoEUAWwHsATAVwBt4AlDU6y8AS1M1UwvkLDKq1UAY1LEymAFbp85eMOox4KAG4wUAB2ilhGdKkiYAngG5Z8xdGVroKAMId0TeAeNmAFO4CUKALwA+FABvfBQwlFFMdHAUGFhUaOhWTFg-TW1ddHQAOjiVAG0AJgBdAEIzcIjHGJhoBPAklPzitK0dPVy4FQrw2hjkgDNSesbUgB8USkw5AeT4cjSpmbnyM1DwwdI0uLXK1gGUd02-X19J6fhZ7HIfEMrKyKdabOpSWHdmrx77lCtwSmgmG+KAAvvh1mFHs4Xm93LVsldyJ54D4AmgTmdNl4viAUAA5LbwaDaaAQqpRaGvd7wxHI1GBeAveApcAACwxKE2TJZrOxJlxAFFiaQ6igACoAZUKAFYAMyFVAAeQARpJ5P10JpSFlWMrqEZzstrmSoc8qUdMEMccB8YThbZ3GLWaxNS6qsT1V4TY5KbCubQedbbWh7fgQV5vCYgA)
      

### 🙁 Actual behavior

Unable to compile TypeScript and compiler says "'info' is undefied".
if my code is wrong,  I should get same error at line 18 and 21, but I didn't get that error.

### 🙂 Expected behavior

"info" is not undefined because already returned, so it should be compiled.

I don't know that cause.

**Comment by Josh-Cena** [comment] 2022-05-16 04:16
Duplicate of #9998?

Narrowing is not preserved across callback boundaries.

**Comment by Dirain1700** [comment] 2022-05-16 05:54
Should I add a note to that Issue?

**Comment by Josh-Cena** [comment] 2022-05-16 06:59
No, there's no need.

**Closed** 2022-05-16 09:14 UTC
