### ISSUE TITLE
Discriminate return type based on property in input object

### ISSUE THREAD

**Issue by timsuchanek** [microsoft/TypeScript#31335] opened 2019-05-10 13:49 UTC
**TypeScript Version:**  3.5.0-dev.20190509

**Search Terms:**
discriminate return type, keyof, extends

**Expected behavior:**
I want to discriminate the return type to "if a property in an object exists, return something different".

These are the 2 approaches I try, both don't work.

1. Using `'select' extends keyof T`   [Playground Link](https://www.typescriptlang.org/play/#src=type%20Args%20%3D%20%7B%0D%0A%20%20select%3F%3A%20boolean%0D%0A%7D%0D%0A%0D%0Ainterface%20Search%20%7B%0D%0A%20%20findIt%3CT%20extends%20Args%3E(a%3A%20T)%3A%20'select'%20extends%20keyof%20T%20%3F%20number%20%3A%20boolean%0D%0A%7D%0D%0A%0D%0Afunction%20Search()%3A%20Search%20%7B%0D%0A%20%20const%20search%20%3D%20()%20%3D%3E%20null%0D%0A%20%20search.findIt%20%3D%20%3CT%20extends%20Args%3E(a%3A%20T)%20%3D%3E%20a.select%20!%3D%3D%20undefined%20%3F%201%20%3A%20false%0D%0A%20%20return%20search%0D%0A%7D)
```ts
type Args = {
  select?: boolean
}

interface Search {
  findIt<T extends Args>(a: T): 'select' extends keyof T ? number : boolean
}

function Search(): Search {
  const search = () => null
  search.findIt = <T extends Args>(a: T) => a.select !== undefined ? 1 : false
  return search
}
```
Error:
```
Type '{ (): any; findIt<T extends SomeArgs>(a: T): false | 1; }' is not assignable to type 'Search'.
  Types of property 'findIt' are incompatible.
    Type '<T extends SomeArgs>(a: T) => false | 1' is not assignable to type '<T extends SomeArgs>(a: Subset<T, SomeArgs>) => "select" extends keyof T ? number : boolean'.
      Type 'false | 1' is not assignable to type '"select" extends keyof T ? number : boolean'.
        Type 'false' is not assignable to type '"select" extends keyof T ? number : boolean'.ts(2322)
```

2. Using `T extends ArgsWithSelect`   [Playground Link](https://www.typescriptlang.org/play/#src=type%20Args%20%3D%20%7B%0D%0A%20%20select%3F%3A%20boolean%0D%0A%7D%0D%0A%0D%0Atype%20ArgsWithSelect%20%3D%20%7B%0D%0A%20%20select%3A%20boolean%0D%0A%7D%0D%0A%0D%0Ainterface%20Search%20%7B%0D%0A%20%20findIt%3CT%20extends%20Args%3E(a%3A%20T)%3A%20T%20extends%20ArgsWithSelect%20%3F%20number%20%3A%20boolean%0D%0A%7D%0D%0A%0D%0Afunction%20Search()%3A%20Search%20%7B%0D%0A%20%20const%20search%20%3D%20()%20%3D%3E%20null%0D%0A%20%20search.findIt%20%3D%20%3CT%20extends%20Args%3E(a%3A%20T)%20%3D%3E%20a.select%20%3D%3D%3D%20undefined%20%3F%20false%20%3A%201%0D%0A%20%20return%20search%0D%0A%7D)
```ts
type Args = {
  select?: boolean
}

type ArgsWithSelect = {
  select: boolean
}

interface Search {
  findIt<T extends Args>(a: T): T extends ArgsWithSelect ? number : boolean
}

function Search(): Search {
  const search = () => null
  search.findIt = <T extends Args>(a: T) => a.select === undefined ? false : 1
  return search
}
```
Error:
```
Type '{ (): any; findIt<T extends SomeArgs>(a: T): false | 1; }' is not assignable to type 'Search'.
  Types of property 'findIt' are incompatible.
    Type '<T extends SomeArgs>(a: T) => false | 1' is not assignable to type '<T extends SomeArgs>(a: T) => T extends SomeArgsWithSelect ? number : boolean'.
      Type 'false | 1' is not assignable to type 'T extends SomeArgsWithSelect ? number : boolean'.
        Type 'false' is not assignable to type 'T extends SomeArgsWithSelect ? number : boolean'
```

I'm running on `typescript@3.5.0-dev.20190509`.
Testing both interface definitions on a type level - they work perfectly. The only problem here is that TypeScript is not able to correctly infer the types from the ternary expression in the actual implementation.

In other words, I'm able to express this on a TypeSystem level, but I'm not able to provide an implementation that the compiler accepts.

**Playground Link:** 

[First Playground](https://www.typescriptlang.org/play/#src=type%20Args%20%3D%20%7B%0D%0A%20%20select%3F%3A%20boolean%0D%0A%7D%0D%0A%0D%0Ainterface%20Search%20%7B%0D%0A%20%20findIt%3CT%20extends%20Args%3E(a%3A%20T)%3A%20'select'%20extends%20keyof%20T%20%3F%20number%20%3A%20boolean%0D%0A%7D%0D%0A%0D%0Afunction%20Search()%3A%20Search%20%7B%0D%0A%20%20const%20search%20%3D%20()%20%3D%3E%20null%0D%0A%20%20search.findIt%20%3D%20%3CT%20extends%20Args%3E(a%3A%20T)%20%3D%3E%20a.select%20!%3D%3D%20undefined%20%3F%201%20%3A%20false%0D%0A%20%20return%20search%0D%0A%7D)
[Second Playground](https://www.typescriptlang.org/play/#src=type%20Args%20%3D%20%7B%0D%0A%20%20select%3F%3A%20boolean%0D%0A%7D%0D%0A%0D%0Atype%20ArgsWithSelect%20%3D%20%7B%0D%0A%20%20select%3A%20boolean%0D%0A%7D%0D%0A%0D%0Ainterface%20Search%20%7B%0D%0A%20%20findIt%3CT%20extends%20Args%3E(a%3A%20T)%3A%20T%20extends%20ArgsWithSelect%20%3F%20number%20%3A%20boolean%0D%0A%7D%0D%0A%0D%0Afunction%20Search()%3A%20Search%20%7B%0D%0A%20%20const%20search%20%3D%20()%20%3D%3E%20null%0D%0A%20%20search.findIt%20%3D%20%3CT%20extends%20Args%3E(a%3A%20T)%20%3D%3E%20a.select%20%3D%3D%3D%20undefined%20%3F%20false%20%3A%201%0D%0A%20%20return%20search%0D%0A%7D)

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/28597

**Comment by jack-williams** [comment] 2019-05-10 19:56
Duplicate of #22735.

**Comment by timsuchanek** [comment] 2019-05-11 08:52
Thanks a lot for the answer! Looks like I'll have to go with an explicit return type annotation for now.

**Closed** 2019-05-16 18:00 UTC
Labels: Duplicate
