### ISSUE TITLE
Index signature parameter should be able to accept types derived from 'string' or 'number'

### ISSUE THREAD

**Issue by garkin** [Microsoft/TypeScript#17528] opened 2017-07-31 10:54 UTC
**TypeScript Version:**  2.4.2 / nightly (2.5.0-dev.20170727)

**Code**

```ts
type EntityId = number;
const entityMap: { [id: EntityId]: number | undefined } = {};  // error

enum SomeEnum { A, B, C }
const someEnumMap: { [id: SomeEnum]: number | undefined } = {};  // error

const enum ConstEnum { A, B, C }
const constEnumMap: { [id: ConstEnum]: number | undefined } = {};  // error
```
[Playground](http://www.typescriptlang.org/play/#src=type%20EntityId%20%3D%20number%3B%0D%0Aconst%20entitykMap%3A%20%7B%20%5Bid%3A%20EntityId%5D%3A%20number%20%7C%20undefined%20%7D%20%3D%20%7B%7D%3B%0D%0A%0D%0Aenum%20SomeEnum%20%7B%20A%2C%20B%2C%20C%20%7D%0D%0Aconst%20someEnumMap%3A%20%7B%20%5Bid%3A%20SomeEnum%5D%3A%20number%7Cundefined%20%7D%20%3D%20%7B%7D%3B%0D%0A%0D%0Aconst%20enum%20ConstEnum%20%7B%20A%2C%20B%2C%20C%20%7D%0D%0Aconst%20constEnumMap%3A%20%7B%20%5Bid%3A%20ConstEnum%5D%3A%20number%20%7C%20undefined%20%7D%20%3D%20%7B%7D%3B)

**Expected behavior:**  Succesfull compilation.

**Actual behavior:**  Getting an error: 
```
index.ts(2,21): error TS1023: An index signature parameter type must be 'string' or 'number'.
index.ts(5,23): error TS1023: An index signature parameter type must be 'string' or 'number'.
index.ts(8,24): error TS1023: An index signature parameter type must be 'string' or 'number'.
```

**Comment by kitsonk** [comment] 2017-07-31 10:57
Duplicate of #2491
Duplicate of #13042

Search is your friend!

**Comment by garkin** [comment] 2017-07-31 11:05
Searched for good half an hour. I'm not love to fill issues, for real. 
Okay, i see there enums, but no `type EntityId = number`.

**Closed** 2017-07-31 11:09 UTC
