### ISSUE TITLE
Enable devs to hook into "require" and extend module loading

### ISSUE THREAD

**Issue by robertsundstrom** [Microsoft/TypeScript#2232] opened 2015-03-06 19:43 UTC
A require hook, when installed, will hook into the require-function, replace the current functionality, to make TypeScript compiler transpile files on-the-fly (through Node.js) when required.

Should be configurable. 

Babel (formerly e6to5) has this feature: https://babeljs.io/docs/usage/require/

Required for a Node CLI #2231.

**Comment by realyze** [comment] 2015-05-20 00:17
+1

**Comment by jedmao** [comment] 2015-08-03 21:13
I'm in dire need of this feature as well. :+1: 

Currently, I'm transpiling from TypeScript into an ES6 target, then I transpile that code with Babel into ES5. It works like a charm, but it's not the most graceful.

This would also be useful for a `gulpfile.ts`.

**Comment by mhegazy** [comment] 2015-08-04 18:10
We now have a `transpile` method. see [documentation](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-simple-transform-function) for more details. 

with this i would call this completed.

**Comment by jedmao** [comment] 2015-08-04 19:01
@mhegazy this doesn't resolve the issue at all. @robertsundstrom is asking for a require hook so you can:

```js
require('typescript/register')({ /* options */ });
```

This would load a polyfill ([like Babel does](https://github.com/babel/babel/blob/master/packages/babel/src/polyfill.js)) and register with Node (also [like Babel does](https://github.com/babel/babel/blob/master/packages/babel/src/api/register/node.js)).

This must be a part of the `typescript` npm package to work this way.

Please re-open the issue.

**Comment by mhegazy** [comment] 2015-08-04 19:40
> This must be a part of the typescript npm package to work this way.

@jedmao should not this be done in a different package, e.g. typescript-cli for instance?

**Comment by jedmao** [comment] 2015-08-05 01:11
@mhegazy I don't see [`typescript-cli`](https://www.npmjs.com/search?q=typescript-cli) published on npm, nor am I intimately familiar w/ how the TypeScript project is structured, but I'm inclined to think it doesn't belong there either. This is a core feature; hence, why it exists on [`babel-core`](https://www.npmjs.com/package/babel-core).

I don't see how this feature is related to the CLI, but rather the API, as it hijacks the Node require function so that all subsequent require calls load TypeScript files instead of raw JavaScript files.

**Comment by adrianhara** [comment] 2015-09-03 09:40
+1 for this, the Babel way would be very nice

**Comment by hsinha** [comment] 2015-12-01 06:37
+1 A require hook (like Babel) would be extremely useful

**Comment by mhegazy** [comment] 2015-12-09 22:16
Looks like a duplicate of #1823.

**Closed by mhegazy** 2015-12-09 22:16 UTC
Labels: Fixed, Suggestion
