### ISSUE TITLE
TypeScript incorrectly narrows `boolean` type to `true` for variable updated within `Map<...>.get(...)?.forEach(...)` block.

### ISSUE THREAD

**Issue by paulkim3151** [microsoft/TypeScript#60357] opened 2024-10-28 06:55 UTC
### 🔎 Search Terms

"type narrowing", "map of set"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (including v5.6.3 and 5.7.0-beta in playground)

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.3#code/MYewdgzgLgBAtgQwA4HkBmBlAplAXDAWWQB5oAnASzAHMAaGbKUqSmgPjZgF4YwsB3QsgAUASgDcAKESpMOAHQQcwgEQBrLAE8V9PoMaqEK0RMmSANjhhoQIbjBYBXLFJnpG86svVbjAfnkbMgBRBGAAC2Exbk4Ab0kYa1t7NARzJSkAX1NJUEgQS3lzEGphGxBTIA

### 💻 Code

```ts
const mapOfSet: Map<string, Set<string>> = new Map();
mapOfSet.set("key", new Set("a"));

let foo = true;
mapOfSet.get("key")?.forEach(() => {
  foo = false;
});

console.log(foo); 
```

### 🙁 Actual behavior

The `foo` variable is expected to be of type `boolean` because it may change to `false` within the `.forEach(...)` block. However, TypeScript incorrectly narrows `foo`'s type to `true`, assuming it will not change.

### 🙂 Expected behavior

TypeScript should maintain the `boolean` type for the `foo` variable, as it can change to `false` inside the `.forEach(...)` block when the map's value is accessed and iterated over.

**Comment by MartinJohns** [comment] 2024-10-28 07:04
Duplicate of #9998.

**Closed** 2024-10-28 07:23 UTC
