### ISSUE TITLE
Invalid emit for class using decorators plus static properties that reference other static properties of the same class

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#44931] opened 2021-07-07 17:38 UTC
# Bug Report

### 🔎 Search Terms

- tsc 
- emit 
- compiled

### 🕗 Version & Regression Information

Regression  from at least 4.4.0-dev.20210701 

Also tested in 4.4.0-dev.20210707

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=5&ts=4.4.0-dev.20210707#code/JYOwLgpgTgZghgYwgAgJIDED2nkG9kC+AUEQCYQIA2cUKCmIAzmGlpgFzJwgCeA3CSpxGjZACEArpQDWAUVLAwABVoA3YBADuKzOvJQ8JZMeTM4YYAmS04pBpR7IAyggAWEALZxkAXmQByVUZ6cgBaACMpaQgFMAAHNQ1NfwEiE1Mwc0tkTziwHhUIdS1fPFM3TwhOSRl5RULi7ShdYH0AOhd3L0JU9PomMCgJBDBMKAAKNPSTAAEMbGQE4FVzFBs7EAdkAH0PTHInaHUkTnnMABop4wBKMuICIA

### 💻 Code

```ts
interface IFoo { }
declare const IFoo: any;

class BulkEditPreviewProvider {

    static readonly Schema = 'vscode-bulkeditpreview';

    static emptyPreview = { scheme: BulkEditPreviewProvider.Schema };

    constructor(
        @IFoo private readonly _modeService: IFoo,
    ) { }
}
```

### 🐛  Bug
The compiled code for this is:

```js
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __param = (this && this.__param) || function (paramIndex, decorator) {
    return function (target, key) { decorator(target, key, paramIndex); }
};
var _a;
let BulkEditPreviewProvider = (_a = class BulkEditPreviewProvider {
        constructor(_modeService) {
            this._modeService = _modeService;
        }
    },
    _a.Schema = 'vscode-bulkeditpreview',
    _a.emptyPreview = { scheme: BulkEditPreviewProvider.Schema },
    _a);
BulkEditPreviewProvider = __decorate([
    __param(0, IFoo)
], BulkEditPreviewProvider);
```

The bug is that ` _a.emptyPreview = { scheme: BulkEditPreviewProvider.Schema },` uses `BulkEditPreviewProvider` before that variable is defined

**Comment by rbuckton** [comment] 2021-07-07 17:53
Looking into it now

**Comment by MartinJohns** [comment] 2021-07-07 18:28
Sounds like a duplicate of #44908.

**Comment by rbuckton** [comment] 2021-07-07 22:30
#44908 has a different root cause.

**Closed** 2021-07-07 23:58 UTC
Labels: Bug, Fix Available, High Priority
