### ISSUE TITLE
"Cannot update a CallChain using updateCall. Use updateCallChain instead."

### ISSUE THREAD

**Issue by Burgov** [microsoft/TypeScript#33780] opened 2019-10-03 07:46 UTC
**TypeScript Version:**  3.7.0-dev

**Search Terms:**
"Cannot update a CallChain using updateCall. Use updateCallChain instead."

**Code**

```ts
        fsProduct.integrations = product
            .fields
            .Integrations
            ?.map((integration): FS.Integration => {
                return {
                    productId: integration
                };
            });
```

**Expected behavior:**
compiles

**Actual behavior:**
Gives this error:

```
/Users/bart/workspace/firebase-test/functions/node_modules/typescript/lib/typescript.js:66648
        ts.Debug.assert(!(node.flags & 32 /* OptionalChain */), "Cannot update a CallChain using updateCall. Use updateCallChain instead.");
                 ^
Error: Debug Failure. False expression: Cannot update a CallChain using updateCall. Use updateCallChain instead.
    at Object.updateCall (/Users/bart/workspace/firebase-test/functions/node_modules/typescript/lib/typescript.js:66648:18)
    at visitCallExpression (/Users/bart/workspace/firebase-test/functions/node_modules/typescript/lib/typescript.js:74685:23)
    at visitTypeScript (/Users/bart/workspace/firebase-test/functions/node_modules/typescript/lib/typescript.js:73300:28)
    at visitorWorker (/Users/bart/workspace/firebase-test/functions/node_modules/typescript/lib/typescript.js:73033:24)
    at saveStateAndInvoke (/Users/bart/workspace/firebase-test/functions/node_modules/typescript/lib/typescript.js:72971:27)
    at visitor (/Users/bart/workspace/firebase-test/functions/node_modules/typescript/lib/typescript.js:73024:20)
    at visitNode (/Users/bart/workspace/firebase-test/functions/node_modules/typescript/lib/typescript.js:70510:23)
    at Object.visitEachChild (/Users/bart/workspace/firebase-test/functions/node_modules/typescript/lib/typescript.js:70765:46)
    at visitTypeScript (/Users/bart/workspace/firebase-test/functions/node_modules/typescript/lib/typescript.js:73324:31)
    at visitorWorker (/Users/bart/workspace/firebase-test/functions/node_modules/typescript/lib/typescript.js:73033:24)
```

**Playground Link:** 
https://www.typescriptlang.org/play/?ts=3.7-Beta#code/FAAj7AzBnAFAnA9gEwK4GMAuA6AlgO0wFMBzeAQ010X2hAF4QAHJNLUCTsbSXIgG2TQOXCNgCShUhSo1hozgH5sAW3JMAFBoLEylavgCUALhAAxAMoSpe2fgYA+EAG8RCzvCKZU8e6-cBzKwYmOLIpjrS+jRugSAAvgDcsaLxholAA

**Related Issues:** 
no

**Comment by nmain** [comment] 2019-10-03 13:02
Possible duplicate of https://github.com/microsoft/TypeScript/issues/33744

**Comment by andrewbranch** [comment] 2019-10-03 14:11
Yep, this is fixed.

**Closed** 2019-10-05 18:00 UTC
Labels: Duplicate

**Comment by Burgov** [comment] 2019-10-21 08:18
The error seems to be back in 20191018. Runs fine in 20191017

**Comment by andrewbranch** [comment] 2019-10-21 16:16
Confirmed, but it doesn’t repro in master for me. Strange 🤔
