### ISSUE TITLE
Support design metadata emitting for new ES decorators 

### ISSUE THREAD

**Issue by m-bednar** [microsoft/TypeScript#57811] opened 2024-03-17 09:33 UTC
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

This can be probably classified as bug, but also partially as new feauture. 

With legacy typescript decorators "design" metadata (e.g. `design:returntype`, `design:paramtypes`) were added to the emitted Javascript, when options `experimentalDecorators` and `emitDecoratorMetadata` were enabled. With the recent support of ES-style decorators (see [tc39 proposal](https://github.com/tc39/proposal-decorators)) the same metadata are missing. 

Option `emitDecoratorMetadata` cannot be enabled, when `experimentalDecorators` are disabled, but `experimentalDecorators` supress the behaviour of ES decorators and thus not allowing for metadata to be created for them (see [example in playground](https://www.typescriptlang.org/play?experimentalDecorators=true&emitDecoratorMetadata=true#code/FAMwrgdgxgLglgewgAgCYFMoIE4EMboCy6MAFgqgBQy7YDmJAXMgGKSyIQA0yWEBADxjMAwgBtcAZ0nEyFACKYc+HCKSCYASmQBvYMl5JJCMegB0YhHWq0GMHnw2bgAX2DAoE6cgDKCALbo4lKSuu4GAAIYWHgEsuSo+sgADmAARmJwUMiBcqgAjJS2+cwQYP5p6Ng8tgBMzJIw2HAQdNo6bq7uQA)). 

#### Possible solutions

- add design metadata to DecoratorContext.metadata object 
- allow emitting of metadata without `experimentalDecorators` option

**Comment by MartinJohns** [comment] 2024-03-17 10:16
Duplicate of #57533 and #55788. Used search terms: `metadata in:title`

**Closed** 2024-03-17 16:33 UTC
