### ISSUE TITLE
TypeScript to understand null checking with Boolean() function

### ISSUE THREAD

**Issue by MalinnaLeach** [microsoft/TypeScript#43546] opened 2021-04-06 10:16 UTC
# Suggestion

## 🔍 Search Terms

Boolean null-check &&

## ✅ Viability Checklist

My suggestion meets these guidelines: Yes, I hope so!

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I would like that when I null check something in the following way, that TS will understand that the property is not null in the code following &&

`Boolean(something) && following code should know something is not null`

If there is a good reason why this is not possible, or should not be possible, I will be curious to know it.

## 📃 Motivating Example

Here is a sandbox to show what I mean:

https://www.typescriptlang.org/play?#code/FAAhEsDsBcFMCcBmBDAxrEAxA9tkBvUMYgI2XgC4CQ4APaAfioGdp4oBzEAXxAB8QkAK4AbEQG4i3YEVTZIrEAAd2MAELkQAXhAAKRLiZZcASm0A+AkWIg1uEbGSR9hgHRl4DV3WhmAZH4gcgrYDq4i2Bwu2O7k3rD0JpLWxOCIegbYXh5ePmaENoVB8syhsOGR0bHw8YmSRdJg3EA

## 💻 Use Cases

We currently use this approach a lot in React components where we want to render a component only if certain properties are not null.  We can use this pattern instead: `{something ? <Component /> : false}`, but it isn't as neat / readable as `{Boolean(something) && <Component />}`

**Comment by MartinJohns** [comment] 2021-04-06 10:31
Duplicate of #16655.

**Closed** 2021-04-08 18:00 UTC
Labels: Duplicate
