### ISSUE TITLE
Intellisense sees exported `exports.property`, but not `module.exports.property`

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9360] opened 2016-06-25 19:48 UTC
_From @shakvaal on June 24, 2016 13:22_

Intellisense ignores exported properties when they are written as `module.exports.property`, while `exports.property` works fine.

- VSCode Version: 1.2.1
- OS Version: Windows 10 x64 Enterprise

![jsconfig_david](https://cloud.githubusercontent.com/assets/4275080/16338797/8646dba4-3a27-11e6-9270-b27afac2354e.png)
![b](https://cloud.githubusercontent.com/assets/4275080/16338798/8999b54c-3a27-11e6-84ec-ede9fc6d1e0a.png)
![a](https://cloud.githubusercontent.com/assets/4275080/16338802/8b23ccfe-3a27-11e6-93a2-1ffe1de46d8b.png)

_Copied from original issue: Microsoft/vscode#8104_

**Comment by mhegazy** [comment] 2016-06-27 23:08
duplicate of https://github.com/Microsoft/TypeScript/issues/7824, should be fixed in TS 2.0

**Closed by mhegazy** 2016-06-27 23:08 UTC
Labels: Duplicate
