### ISSUE TITLE
Mark that method/function throws an error

### ISSUE THREAD

**Issue by k3nsei** [microsoft/TypeScript#54176] opened 2023-05-08 11:37 UTC
# Suggestion

## 🔍 Search Terms

- throws

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I would like to know whether class method or function can throw an error and which error could it be.

## 📃 Motivating Example

When using 3rd party libraries or native JS API's information about that error could be thrown usually isn't there. In JSDoc there is tag `throws` https://jsdoc.app/tags-throws.html for this purpose. It would be nice to have it built in to TypeScript.

## 💻 Use Cases

```ts
class FileNotFoundException extends Error {} 

class NoAccessException extends Error {} 

/**
 * I would like to have equivalent of tags below build in into TypeScript itself
 * @throws { FileNotFoundException }
 * @throws { NoAccessException }
 * @throws { Error }
 */
const readFile = (filePath: string): Promise<Blob> throws FileNotFoundException | NoAccessException | Error => {
  const stats = FileAPI.stats(filePath);

  if (!stats.exists) {
    throw new FileNotFoundError();
  }

  if (!stats.canRead) {
    throw new NoAccessError();
  }

  return FileAPI.readFile(filePath).then(file => file.asBlob());
}

/**
 * Somewhere in code `readFile` function would be used.
 * As a developer I want that tsc would show me warrning or error,
 * that there is possibility of errors and function call should be wrapped in try/catch
 */ 

try {
  readFile('dummy.txt');
} catch(e) {
  // handle error
}
```

**Comment by MartinJohns** [comment] 2023-05-08 11:44
Duplicate of #23060 / #13219 and others.

**Comment by k3nsei** [comment] 2023-05-08 11:50
@MartinJohns These are closed and I definitely expect this to be implemented in TypeScript.

**Comment by MartinJohns** [comment] 2023-05-08 11:53
> These are closed

🤷‍♂️ Because this request has been rejected over and over again. Opening yet another issue about it and saying that you *expect* it to be implemented won't help.

Recently Ryan wrote an elaborate comment about this in the issue I linked: https://github.com/microsoft/TypeScript/issues/13219#issuecomment-1515037604

**Comment by k3nsei** [comment] 2023-05-08 11:56
I can't agree with his comment. It's totally possible to implement those check during type checking.

**Comment by MartinJohns** [comment] 2023-05-08 11:59
> It's totally possible to implement those checks during type checking.

An explicit goal of TypeScript is to **not** generate additional code based on the types.

> It would be possible also to implement it as eslint rule, but we need mechanism to tag method/function that it would throw.

I'm certain eslint rules can read comments, so you could create something like `/** @throws .... */`. 🤷‍♂️

---

Anyway, this feature suggestion has been discussed to death already. I'm out.

**Comment by fatcerberus** [comment] 2023-05-08 12:04
#13219 is explicitly tagged `Declined`.  That’s a very clear signal IMO that the team has no intention of implementing it.  Ultimately, TypeScript development is not a democracy, the project maintainers have the final say, and (as far as I can tell) this issue doesn’t bring anything new to the table in terms of discussion.

**Comment by k3nsei** [comment] 2023-05-08 12:04
> An explicit goal of TypeScript is to not generate additional code based on the types.
It would be only added to .d.ts and it could be added as JSDoc comment

> I'm certain eslint rules can read comments, so you could create something like /** @throws .... */. 🤷‍♂️
Provided built-in types provided by TypeScript should add `throws` tag to provide this for eslint to be used

**Comment by k3nsei** [comment] 2023-05-08 12:07
@MartinJohns @fatcerberus at lease provide `throws` tag as JSDoc comment in built-in types provided by TypeScript

**Closed as completed** 2023-05-08 17:19 UTC
Labels: Duplicate
