### ISSUE TITLE
Public property has or is using name but cannot be named - intersection types

### ISSUE THREAD

**Issue by aj-r** [Microsoft/TypeScript#23679] opened 2018-04-25 14:48 UTC
**TypeScript Version:**  2.8.3

**Search Terms:** exported variable but cannot be named

**Code**

`animal.ts`:
```ts
export interface Dog {
    type: "dog";
    ...
}
export interface Cat {
    type: "cat";
    ...
}
export type Animal = Dog | Cat;
```

`otherFile.ts`:

```ts
import { Animal } from "./animal"

export class MyClass {
    pulbic checkAnimal = (animal: Animal | undefined): void => {
        ...
    }
}
```

NOTE: if I use function syntax instead of arrow syntax, or if I remove `| undefined`, there is no error:

```ts
// This works fine:
public checkAnimal(animal: Animal | undefined): void {
}
// So does this:
public checkAnimal = (animal: Animal): void => {
}
```

**Expected behavior:** Behaviour should be the same whether function syntax or arrow syntax is used. Ideally no error.

**Actual behavior:**

```
ERROR in [...]/otherFile.ts
./otherFile.ts
[tsl] ERROR in [...]/otherFile.ts(170,5)
      TS4029: Public property 'checkAnimal' of exported class has or is using name 'Cat' from external module "[...]/animal" but cannot be named.
```

(Only when using arrow syntax. When using function syntax, there is no error. However in this situation I need to use arrow syntax to preserve `this`.)

**Playground Link:**  

**Related Issues:** https://github.com/palantir/tslint/issues/3854

**Comment by mhegazy** [comment] 2018-04-25 22:58
I can not get a repro for this issue locally. my guess is that `Cat` or `Dog` are not imported in the actual case.

```shell
c:\test\23679>type animal.ts
export interface Dog {
    type: "dog";
}
export interface Cat {
    type: "cat";
}
export type Animal = Dog | Cat;

c:\test\23679>type index.ts
import { Animal, Cat, Dog } from "./animal"

export class MyClass {
    public checkAnimal = (animal: Animal | undefined): void => {

    };
}

c:\test\23679>tsc --v
Version 2.9.0-dev.20180422

c:\test\23679>tsc --declaration

c:\test\23679>echo %ERRORLEVEL%
0
```

**Comment by mhegazy** [comment] 2018-04-25 22:59
Regardless of the details of the repro, this seems to be a duplicate of https://github.com/Microsoft/TypeScript/issues/9944.  see https://github.com/Microsoft/TypeScript/issues/9944#issuecomment-244448079 for more context.

Also the fix here is to write an explicit type annoation. i.e.:

```ts
    public checkAnimal: (animal: Animal | undefined) => void = (animal: Animal | undefined): void => {

    };
```

**Closed** 2018-05-18 19:46 UTC
Labels: Duplicate
