### ISSUE TITLE
Index key accessed nullable index type is not narrowed from nullable

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#12636] opened 2016-12-03 14:34 UTC
```ts
interface S {
    hello: any;
}

interface R {
    [i: string]: S | undefined;
}

function f<K extends keyof R>(p: K) {
    let r: R = {};
    if (r[p]) {
        r[p].hello // Error: hello does not exists on type R[K]
    }
}
```
Removing the type `undefined` from `S | undefined` fixes the error and also the `if` check is no longer required.

**Comment by DanielRosenwasser** [comment] 2016-12-03 22:54
I think this might be a duplicate of #10530. Could you post your example on #10565 just so we can add a test case?

**Comment by DanielRosenwasser** [comment] 2016-12-03 22:58
This is actually a little iffy - despite how we'd like to think about it, there's not anything fundamentally tying `keyof R` to `R` because `keyof R` is really just equivalent to `string`.

**Comment by tinganho** [comment] 2016-12-08 09:03
@DanielRosenwasser though it does ties to `R` if you remove `undefined`?

```ts
interface S {
    hello: any;
}

interface R {
    [i: string]: S;
}

function f<K extends keyof R>(p: K) {
    let r: R = {};
    if (r[p]) {
        r[p].hello // No error
    }
}
```

**Comment by ahejlsberg** [comment] 2017-01-10 22:36
Aside from not supporting narrowing with element access expressions (which is tracked by #10530), we would have to introduce a new type operator that records the fact that a truthy check has been performed on some generic type. For example, given a `T!` operator that represents a truthy check on `T`, within the `if` block, `r[p]` would have type `R[K]!`. Then, when we obtain the apparent type of `R[K]!` in the property access `r[p].hello` we would know to remove `undefined` from the type.

However, introducing new type operators is not a trivial matter, and I'm not sure it is worth the effort in this particular scenario.

**Comment by mhegazy** [comment] 2017-04-24 20:43
Closing in favor of #14366 and #10530.

**Closed by mhegazy** 2017-04-24 20:43 UTC
Labels: Design Limitation, Suggestion
