### ISSUE TITLE
Inconsistent behaviour of enum. 

### ISSUE THREAD

**Issue by pociej** [microsoft/TypeScript#50507] opened 2022-08-29 11:35 UTC
### 🔎 Search Terms

`wrong enum behaviour` `numeric enum wrong check` `inconsistent enum behaviour` 

### 🕗 Version & Regression Information

I see it in all versions of ts 
### ⏯ Playground Link
https://tsplay.dev/N9PO8w

### 💻 Code

```
enum myEnum {
    a = 'a',
    b = 'b',
}


enum extendedEnum {
    a = "a", 
    b = "b", 
    //use any number here, 11 is random value 
    c = 11, 
}


//use any number here, 48 is random value 

const returnsMyEnum = function() : myEnum {
    return 48;  
}

const returnMyExtendedEnum = function() : extendedEnum {
    return 48; 
}
```

### 🙁 Actual behavior

Only `returnsMyEnum` gives typescript error. 
### 🙂 Expected behavior

Both functions are wrong.

**Comment by jcalz** [comment] 2022-08-29 11:45
Duplicate of #26362

**Comment by fatcerberus** [comment] 2022-08-30 16:56
> ```ts
> // use any number here, 11 is random value 
> c = 11,
> ```

I’m suddenly reminded of this
https://xkcd.com/221/

**Closed** 2022-09-01 18:00 UTC
Labels: Duplicate
