### ISSUE TITLE
"Go to symbol..." does not work in JS IIFE

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#7365] opened 2016-03-03 11:56 UTC
_From @kuechlerm on March 2, 2016 9:27_

In 0.10.10-insider the following code causes the "Go to symbol..."-box to state "No symbols found".

`(function() {
    function foo() { }
})();`

I would expect to see 'foo' listed as a symbol, which is the case without the IIFE.

_Copied from original issue: Microsoft/vscode#3618_

**Comment by RyanCavanaugh** [comment] 2016-03-03 16:52
Duplicate of #7134

**Closed by RyanCavanaugh** 2016-03-03 16:52 UTC
Labels: Duplicate
