### ISSUE TITLE
TypeError: Cannot read property 'flags' of undefined in 4.4.0-beta

### ISSUE THREAD

**Issue by samreid** [microsoft/TypeScript#44981] opened 2021-07-12 00:15 UTC
# Bug Report

### 🔎 Search Terms

TypeError: Cannot read property 'flags' of undefined
crash

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions Version 4.3.5 and Version 4.4.0-beta

### ⏯ Playground Link

The problem goes away if you rename the *.js file to *.ts, so I couldn't create a playground for it.

### 💻 Code

```json
// tsconfig.json
{
    "compilerOptions": {
        "target": "ES2020",
        "allowJs": true,
        "outDir": "out/"
    }
}
```

```js
// TestClass.js
const map = new Map();
const memoize = () => key => map.get( key );

class U {}

const T = memoize();

class V extends T( U ) {
  /**
   * @override
   */
  initialize() {
  }
}
```

### 🙁 Actual behavior

```
$ tsc --version
Version 4.4.0-beta

$ tsc
/Users/samreid/.npm-global/lib/node_modules/typescript/lib/tsc.js:92222
                throw e;
                ^

TypeError: Cannot read property 'flags' of undefined
    at getMembersOfSymbol (/Users/samreid/.npm-global/lib/node_modules/typescript/lib/tsc.js:45197:27)
    at getSuggestedSymbolForNonexistentClassMember (/Users/samreid/.npm-global/lib/node_modules/typescript/lib/tsc.js:59370:68)
    at checkClassMember (/Users/samreid/.npm-global/lib/node_modules/typescript/lib/tsc.js:66799:42)
    at _loop_29 (/Users/samreid/.npm-global/lib/node_modules/typescript/lib/tsc.js:66779:17)
    at checkMembersForMissingOverrideModifier (/Users/samreid/.npm-global/lib/node_modules/typescript/lib/tsc.js:66783:17)
    at checkClassLikeDeclaration (/Users/samreid/.npm-global/lib/node_modules/typescript/lib/tsc.js:66727:13)
    at checkClassDeclaration (/Users/samreid/.npm-global/lib/node_modules/typescript/lib/tsc.js:66646:13)
    at checkSourceElementWorker (/Users/samreid/.npm-global/lib/node_modules/typescript/lib/tsc.js:68014:28)
    at checkSourceElement (/Users/samreid/.npm-global/lib/node_modules/typescript/lib/tsc.js:67856:17)
    at Object.forEach (/Users/samreid/.npm-global/lib/node_modules/typescript/lib/tsc.js:132:30)
```

### 🙂 Expected behavior

Build completes successfully in 4.3.5:

```
$ tsc --version
Version 4.3.5

$ tsc
$
```

**Comment by a-tarasyuk** [comment] 2021-07-12 06:06
Duplicate of https://github.com/microsoft/TypeScript/issues/44981

**Comment by a-tarasyuk** [comment] 2021-07-12 06:12
Duplicate of https://github.com/microsoft/TypeScript/issues/44902

**Closed** 2021-07-15 18:00 UTC
Labels: Duplicate
