### ISSUE TITLE
'Foo' is not assignable to 'Partial<T>' where generic 'T extends Foo'

### ISSUE THREAD

**Issue by GregorioBR** [Microsoft/TypeScript#19467] opened 2017-10-25 11:17 UTC
**TypeScript Version:**  2.5.3

**Code**

```ts
interface IViewState {
    data?: string;
}

class View<S extends IViewState> {

    public processState(): Partial<S> {
        return {data: "test"};
    }
}

```

**Expected behavior:**

Code to compile

**Actual behavior:**
```
C:\Users\Greg\Desktop\demo-app\greg>tsc --version
Version 2.5.3

C:\Users\Greg\Desktop\demo-app\greg>tsc --init
message TS6071: Successfully created a tsconfig.json file.

C:\Users\Greg\Desktop\demo-app\greg>tsc
test.ts(12,9): error TS2322: Type '{ data: string; }' is not assignable to type 'Partial<S>'.
```

**Comment by DanielRosenwasser** [comment] 2017-10-25 14:29
Hey, thanks for filing, but this seems to be a duplicate of #19388, a duplicate of #17071, and a duplicate of #13442

In the future using the issue tracker's search functionality can make it easier for us to triage issues. Thanks!

**Comment by DanielRosenwasser** [comment] 2017-10-25 14:40
However, I did try using a type assertion which your example doesn't use and that is indeed an error. I've filed #19470 for you there.

**Comment by GregorioBR** [comment] 2017-10-25 22:28
Thank you very much!

**Comment by mhegazy** [comment] 2017-11-09 21:23
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-11-09 21:23 UTC
Labels: Duplicate
