### ISSUE TITLE
Allow `this` type in constructor

### ISSUE THREAD

**Issue by nin-jin** [Microsoft/TypeScript#16703] opened 2017-06-23 02:23 UTC
```ts
class Base
{
    constructor( donor : Partial<this> )  // <---
    {
        Object.assign( this , donor )
    }
}

class Duration extends Base
{
    readonly year: number
    readonly month: number
    readonly day: number
    readonly hour: number
    readonly minute: number
    readonly second: number
}

class Moment extends Base
{
    readonly year: number
    readonly month: number
    readonly day: number
    readonly hour: number
    readonly minute: number
    readonly second: number
    readonly offset: Duration
}

cost today = new Moment({ year : 2017 , month : 5 , day : 22 })
```

Throws error: **A 'this' type is available only in a non-static member of a class or interface.**

Current workaround:

```ts
class Base
{
    setup( donor : Partial<this> ) : this
    {
        return Object.assign( this , donor )
    }
}

// ...

const today = new Moment().setup({ year : 2017 , month : 5 , day : 22 })
```

**Comment by DanielRosenwasser** [comment] 2017-06-23 06:20
Note that technically `this` types on parameter annotations isn't type-safe anyway.

**Comment by aluanhaddad** [comment] 2017-07-03 13:33
Assuming `this` would be the instance type, how does this relate to #5863?

_Sent from my Samsung SM-G920T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nin-jin** [comment] 2017-07-03 14:45
`connstructor` is instance method too.

**Comment by nin-jin** [comment] 2017-07-03 15:06
Thank you. My workaround:

```
class Base
{
	public static make< T >( this : { new() : T } , config : Partial<T> ) : T {
        const obj = new this()
	for( let key in config ) obj[ key ] = config[ key ]
		return obj
	}
}
```

```
const today = Moment.make({ year : 2017 , month : 5 , day : 22 })
```

**Comment by andy-ms** [comment] 2018-04-10 20:07
Duplicate of #22430

**Closed** 2018-04-25 20:28 UTC
Labels: Duplicate
