### ISSUE TITLE
The type reduction of the in operator is invalid in ts 5.5

### ISSUE THREAD

**Issue by codeflyA** [microsoft/TypeScript#59061] opened 2024-06-28 07:10 UTC
### 🔎 Search Terms

The type reduction of the in operator is invalid in ts 5.5

### 🕗 Version & Regression Information

ts 5.5

### 💻 Code

export type IZhgztDeptTreeChildren = {
  organizationCode: string
  deptId: string
  name: string
  sort: number
  parentId: string
  divisionCode: string
  deptType: string
  children: IZhgztDeptTreeChildren[]
  id: string
}
type userInfo = { name: string; userId: string; id: string; isLeaf: boolean }
const handleNodeClick = (data: IZhgztDeptTreeChildren | userInfo) => {
  if ('userId' in data) {
    data = handleFullPeopleName(JSON.parse(JSON.stringify(data)) as userInfo) as userInfo
  }
  console.log(data)
}
function handleFullPeopleName(data: userInfo): userInfo {
  return data
}
![image](https://github.com/microsoft/TypeScript/assets/51228740/ec77e203-8ff8-45cd-b298-c6e241219d3b)
![image](https://github.com/microsoft/TypeScript/assets/51228740/7d07616e-6aab-4062-8168-042a69804729)

### 🙁 Actual behavior

data Type inference (parameter) data: IZhgztDeptTreeChildren | userInfo  ，but i expect only userInfo  。is bug？how to solve this problem

### 🙂 Expected behavior

expect only userInfo 

### Additional information about the issue

data Type inference (parameter) data: IZhgztDeptTreeChildren | userInfo  ，but i expect only userInfo  。is bug？how to solve this problem

**Comment by nmain** [comment] 2024-06-28 16:04
This seems to be just a quickinfo confusion, the expected narrowed type is seen on subsequent lines:  [playground](https://www.typescriptlang.org/play/?ts=5.4.5#code/C4TwDgpgBAglC8UDeUCGAuNA7EUC+A3ALABQokUAQgslAEaao77EmkAmEAxgDaoBO0AGYBXLF2ABLAPZYokgM4wAFCMxwAPlQCUmEfIWxWnXgOFiJMuQFtUAawgqMsXUdKlR4qbKjtpAZWlrCGAAC0ksAHNVdSgtSm1kUigUqBECKAB6TNg4qmTUySEoZUUVEW1EpALU1PSsnJga2rSaWwdy7VYWuozs2Ga8UiGSIA)

Do you have any examples where consuming `data` fails to have the right types?

**Comment by andrewbranch** [comment] 2024-06-28 22:20
Duplicate of https://github.com/microsoft/TypeScript/issues/52547

**Comment by codeflyA** [comment] 2024-06-29 00:31
> This seems to be just a quickinfo confusion, the expected narrowed type is seen on subsequent lines: [playground](https://www.typescriptlang.org/play/?ts=5.4.5#code/C4TwDgpgBAglC8UDeUCGAuNA7EUC+A3ALABQokUAQgslAEaao77EmkAmEAxgDaoBO0AGYBXLF2ABLAPZYokgM4wAFCMxwAPlQCUmEfIWxWnXgOFiJMuQFtUAawgqMsXUdKlR4qbKjtpAZWlrCGAAC0ksAHNVdSgtSm1kUigUqBECKAB6TNg4qmTUySEoZUUVEW1EpALU1PSsnJga2rSaWwdy7VYWuozs2Ga8UiGSIA)
> 
> Do you have any examples where consuming `data` fails to have the right types?
![image](https://github.com/microsoft/TypeScript/assets/51228740/0d741ef6-2aa5-41a2-8508-dbb2df4e8c2c)
![image](https://github.com/microsoft/TypeScript/assets/51228740/57f15d8c-aa3f-4f0b-a136-3d6e5bea6394)

**Comment by nmain** [comment] 2024-06-29 00:35
> Duplicate of #52547

I replied to that one too and didn't even remember it 🤦

**Comment by codeflyA** [comment] 2024-06-29 00:40
> > Duplicate of #52547
> 
> I replied to that one too and didn't even remember it 🤦

in my example ，Subsequent uses of value will type incorrectly:

**Comment by nmain** [comment] 2024-06-29 03:07
@codeflyA That's #9998, because TS doesn't know when the callback passed to `findIndex` will be invoked.

**Comment by codeflyA** [comment] 2024-06-30 08:32
> @codeflyA That's #9998, because TS doesn't know when the callback passed to `findIndex` will be invoked.

i read you answer，but  if i delete code
   // if (index == -1) {
    //   data = handleFullPeopleName(JSON.parse(JSON.stringify(data)))
    // }
the ts error disappear
![image](https://github.com/microsoft/TypeScript/assets/51228740/4c68347e-1496-4353-8acc-6a61439d036f)

**Closed** 2024-07-03 01:30 UTC
Labels: Duplicate
