### ISSUE TITLE
Incorrect type narrowing of variables from outside scope in IIAFE's

### ISSUE THREAD

**Issue by csorfab** [microsoft/TypeScript#56447] opened 2023-11-17 19:02 UTC
### 🔎 Search Terms

async narrowing let variable iiafe immediately invoked

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type narrowing

This is definitely a bug, the type information Typescript gives is easily demonstrably incorrect.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.0-dev.20231117#code/GYVwdgxgLglg9mABAQ0QCgJSIN4ChGIA2AplIhMpMYSQCaIC8iwyhAzsQNz7rJsCekdFgYA+HDwIUqNYrU6IA9IvJwATmuLRC-RDDDBiGuSjaIARC3bFzklAHdkMMmGL3EABTVwAtjA5ommxwhABuxIziHFAAKjA+xHAgUIHEwWHEADSIAIwADHkYGArKKMBQRohQABYRwDBqbGTIjs7ZlLpgyBpw9voA5ohs1UmE9ABGEbT+FGq0cnYwwOjSENR0WNhKKjH8AA5pEGowe2T6ho16zWaWrBzmiPa1SM6PMDSIk1VqIBHIZDV-Ig9nB9FA7FIEOliAA6QhwfpoVbrOTFbaIXYHNhHE5nAxGMyvPgWVzhNS2AgEAC+PCpGEw3B4yNk9CYUB+XFwNNwpQAImk9s4Ik9-hj9odjqchsh+GxsoCzHtjmAoDd2b9bMgGbggA

### 💻 Code

```ts
function a () {
  let cancelled = false;
  (async () => {
    cancelled; // correctly inferred as "false"
    await new Promise(resolve => setTimeout(resolve, 100)); // after the first await, any narrowing should be discarded
    if (cancelled) { // Typescript infers it as "false" when it will be true at this point
      console.log(cancelled); // Typescript infers it as "never"
    }
  })();

  cancelled = true;
}

// Despite what Typescript says, this prints "true"
a();

```

### 🙁 Actual behavior

Typescript incorrectly narrows the type of a variable in an IIAFE

### 🙂 Expected behavior

Type should revert to the broadest possible type after the first "await" in an IIAFE

**Comment by MartinJohns** [comment] 2023-11-17 19:02
Duplicate of #9998.

**Closed** 2023-11-20 01:29 UTC
Labels: Duplicate
