### ISSUE TITLE
Parameter destructuring loses type information

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/TypeScript#5416] opened 2015-10-27 14:12 UTC
I've just noticed this problem:

```
var myBooks = [
	{title: 'Sherlock Holmes'},
	{title: 'Moby Dick'}
];

var bookTitles = myBooks.map(({title}) => title); // Boo!  no type information; title is `any`
```

So if I use parameter destructuring I lose the type information which is kinda sad.

I can work around it like this:

```
var bookTitles = myBooks.map(b => {
    const { title } = b;
    return title;
}); 
```

or this:

```
var bookTitles = myBooks.map(b => b.title); 
```

But ideally I shouldn't need to.

**Comment by vladima** [comment] 2015-10-27 14:27
dupe of #4937, that was already fixed in master.

**Closed by vladima** 2015-10-27 14:27 UTC
Labels: Duplicate

**Comment by johnnyreilly** [comment] 2015-10-27 14:29
Fantastic - thanks @vladima.  Did a little digging through existing issues but didn't spot this.
