### ISSUE TITLE
require with slash makes IntelliSense extremely unresponsive

### ISSUE THREAD

**Issue by octref** [Microsoft/TypeScript#19459] opened 2017-10-24 22:44 UTC
**TypeScript Version:**  2.6.1-insiders.20171019

**OS**: macOS 10.12.6

**Code**

- Use https://github.com/Microsoft/vscode-generator-code to generate a JavaScript VS Code extension
- `npm install sass.js`
- Add a file `scss.js`

  ```ts
  //@ts-check
  const compile = require('sass.js/dist/sass.node')

  compile('test.scss', { style: compile.Sass.style.compressed }, (res) => {
    console.log(res.text);
  })
  ```

**Expected behavior:** IntelliSense still works

**Actual behavior:** IntelliSense in any of the js files in the project takes 5 second to load

![ts](https://user-images.githubusercontent.com/4033249/31971760-11baf79a-b8d2-11e7-9fdd-f8750bd2c18c.gif)

Zipped workspace (no node_modules, install them before trying)
[matb.zip](https://github.com/Microsoft/TypeScript/files/1412734/matb.zip)

/cc @mjbvz

**Comment by mjbvz** [comment] 2017-10-24 22:45
Duplicate of #19458

**Closed by mjbvz** 2017-10-24 22:45 UTC
