### ISSUE TITLE
Omit<A | B> works unexpectly, cannot keep union relationship

### ISSUE THREAD

**Issue by k8w** [microsoft/TypeScript#41772] opened 2020-12-02 14:16 UTC
**TypeScript Version:**  3.7.x-dev.201xxxxx
4.0.3

**Search Terms:**
`Omit Union` `Omit<A|B>`

**Code**

```ts
type A = {
    type: 'A',
    valueA: string,
    common: string
}
type B = {
    type: 'B',
    valueB: string,
    common: string
}
type AB = A | B;
type NoCommon = Omit<AB, 'common'>;

let value: NoCommon = {
    type: 'A',
    valueA: 'XXX'
}
```

**Expected behavior:**
No compile error

**Actual behavior:**
> error TS2322: Type '{ type: "A"; valueA: string; }' is not assignable to type 'Pick<AB, "type">'.
  Object literal may only specify known properties, and 'valueA' does not exist in type 'Pick<AB, "type">'.
16     valueA: 'XXX'

**Playground Link:** 

**Related Issues:**

**Comment by MartinJohns** [comment] 2020-12-02 14:59
Duplicate of #39556. Search terms: `omit union`

> Search Terms: Omit Union Omit<A|B>

A tip for the future: Something overly specific to your example, such as the types `A` and `B`, don't make good search terms. :-)

**Comment by RyanCavanaugh** [comment] 2020-12-03 00:22
To get the behavior you wanted, the syntax is
```ts
type NoCommonHelper<T> = T extends unknown ? Omit<T, 'common'> : never;
type NoCommon = NoCommonHelper<AB>;
```

**Closed** 2020-12-05 18:00 UTC
Labels: Duplicate
