### ISSUE TITLE
Every file change breaks references with declarationMap until reopening file

### ISSUE THREAD

**Issue by asvetliakov** [Microsoft/TypeScript#28479] opened 2018-11-12 04:23 UTC
**TypeScript Version:**  3.2.0-dev.20181110

**Search Terms:**
declarationMap
references
Debug failure. False expression at computePositionOfLineAndCharacter

**Code**
1. Clone https://github.com/asvetliakov/typescript-references-error
2. yarn
3. run ```yarn run tsc -w``` in ```packages/a``` and ```packages/b``` (in different terminals)
4. Open ```packages/a/src/a.ts``` and ```packages/b/src/index.ts```
5. See references are ok in ```a.ts```
6. Add empty line in ```a.ts``` between ```a1``` and ```a2``` and save file
7. See references are broken and TS output this in the log:

```
Error: Debug Failure. False expression.
    at computePositionOfLineAndCharacter (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:6421:22)
    at Object.getPositionOfLineAndCharacter (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:6411:16)
    at processMapping (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:64616:26)
    at Object.arrayFrom (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:1172:31)
    at getDecodedMappings (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:64630:35)
    at getSourceMappings (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:64646:39)
    at Object.getGeneratedPosition (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:64674:34)
    at Object.tryGetGeneratedPosition (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:103468:76)
    at getDefinitionInProject (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:123527:91)
    at /Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:123514:38
    at /Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:121723:25
    at Map.forEach (<anonymous>)
    at ProjectService.forEachProject (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:121717:41)
    at ProjectService.forEachEnabledProject (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:121721:22)
    at combineProjectOutputWorker (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:123511:32)
    at combineProjectOutputForReferences (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:123463:13)
    at IOSession.Session.getReferences (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:124497:34)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:123643:61)
    at /Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:125199:88
    at IOSession.Session.executeWithRequestId (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:125190:28)
    at IOSession.Session.executeCommand (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:125199:33)
    at IOSession.Session.onMessage (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:125221:35)
    at Interface.<anonymous> (/Users/asvetl/work/test2/node_modules/typescript/lib/tsserver.js:126479:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```
**Expected behavior:**
No broken references

**Actual behavior:**
References are broken. Only one way to fix them - reopen the file

**Playground Link:** 

**Related Issues:** 
May be #25844

**Comment by sheetalkamat** [comment] 2018-11-12 16:31
Duplicate of #25844

**Closed by sheetalkamat** 2018-11-12 16:31 UTC
Labels: Duplicate
