### ISSUE TITLE
Narrowing information lost when inside sub-function

### ISSUE THREAD

**Issue by Nixinova** [microsoft/TypeScript#45511] opened 2021-08-19 05:16 UTC
# Bug Report

### 🔎 Search Terms

- variable narrowing in function
- Object is possibly 'null'

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about: narrowing

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/DYUwLgBAxghmIHMD2AnAliAzgLgps6AdggNoC6EAPhIQK7DAQC8EJA5DGwDQRsBGbMgCghaAGYQAFLHjJ0WAJQQA3kIjrocRKgyYAdGkJRgtACZZJHNgrUaA9HYgB5ANK31oSAA9mrMnrE0YHgUSTR4AFtmAD5NWR0sAyMTc0wwyIUbDQgHCABRFBRUAEJssvL1AD1nPgArEChINEwIAAckTEw0PmAAT146BjY9SQAmAFYAZgBGGwBfIA)

### 💻 Code

```ts
let categories: string[] | null = ['a', 'b']

if (categories) {
    categories.includes('a')
    // OK

    let x = [].filter(item => categories.includes(item))
    // Error!                 ^ Object is possibly 'null'.(2531)
}
```

### 🙁 Actual behavior

Errors with `Object is possibly 'null'. (2531)`

### 🙂 Expected behavior

No error as it has been checked earlier.

**Comment by Nixinova** [comment] 2021-08-19 05:19
Oh, this is #10530, didn't seem like it from the title until I read https://github.com/microsoft/TypeScript/issues/10530#issuecomment-633507950

**Comment by MartinJohns** [comment] 2021-08-19 05:47
Another duplicate of #9998.

**Closed** 2021-08-19 05:48 UTC
