### ISSUE TITLE
Assignment in closure is assumed to never happen

### ISSUE THREAD

**Issue by cakoose** [microsoft/TypeScript#40706] opened 2020-09-22 18:36 UTC
Playground: [link](https://www.typescriptlang.org/play?#code/C4TwDgpgBACg9gSwHbCgXigbwB4C4pICuAtgEYQBOANFCPkWZQL4DcAsAFCcBmhSAxsARwkUAOYRg8ZMAAUASnzSUWTlHVQKkwhVE58ARhp0oB1pyadOAQwDOIAVF4ChIpwtUcNUADaSoYEqIKgA+BIQ+PujhkexeGtYA7tYIqEgQibAUcMQIthCyslq2cD4AbhA0WgBWEILy6AB8nt7eYNESUsFy8nHeTL1qGgjcULLtAIRoGESRDZhDrVD8IiV+AHQ+cGLj69i96gD0h1AAKgDKStmQFKBQAOTY91AAJnAQtgRwqBDYeahuUCQB7pCoUe6LKCWDhMIA)

```typescript
type Point = {x: number, y: number};

function getPoint(): Point {
    return {x: 1, y: 1};
}

async function f() {
    let p: Point | null = null;
    await new Promise((resolve, reject) => {
        p = getPoint();
    });
    if (p !== null) {
        console.log(p.x);  // TS: Property 'x' does not exist on type 'never'
    }
}
```

The function passed to the `Promise` constructor assigns `p`.  The `Promise` constructor will _always_ call that function, but I realize TS doesn't know that.  But TS seems to assume the closure definitely doesn't run, and `p` is always `null`.

Issue occurs on 4.0.2 and on nightly (v4.1.0-dev.20200921).

**Comment by MartinJohns** [comment] 2020-09-22 19:54
And yet another duplicate of #9998.

**Comment by cakoose** [comment] 2020-09-22 20:03
Oh sorry.  I searched for "closure assignment never" and a bunch of variants of that.

**Comment by RyanCavanaugh** [comment] 2020-09-22 20:10
👍

**Closed** 2020-09-25 18:00 UTC
Labels: Duplicate
