### ISSUE TITLE
Debug Failure. This is unknown parent for type parameter: 176

### ISSUE THREAD

**Issue by bysdxt** [microsoft/TypeScript#25456] opened 2018-07-05 17:04 UTC
**TypeScript Version:**  2.9.2

**Search Terms:** 
This is unknown parent for type parameter

**Code**
interface i { a: number; }
type x = { [K in Exclude<keyof i, keyof j>]: i[K]; }

**Step**
Run command 'tsc a.ts' and 'tsc a.ts --declaration true'
The output of command 'tsc a.ts' is right, "error TS2304: Cannot find name 'j'".
But command 'tsc a.ts --declaration true' output something wrong in tsc:
C:\Users\bysdxt\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:63860
                throw e;
                ^

Error: Debug Failure. This is unknown parent for type parameter: 176
![a](https://user-images.githubusercontent.com/13766766/42337119-4c7e2a74-80b8-11e8-84f5-74373b9b28af.jpg)

**Comment by jakebailey** [comment] 2023-07-11 18:47
This was fixed by #30244; #30201 was a duplicate of this.

**Closed by jakebailey** 2023-07-11 18:47 UTC
Labels: Bug, Crash
