### ISSUE TITLE
Cannot add decorators to anonymous class declarations

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#9152] opened 2016-06-14 07:57 UTC
**TypeScript Version:** 

1.8.9

**Code**

```ts
// A self-contained demonstration of the problem follows...

function deco() {
	
}

class Foo {
	
}

let a = class extends Foo {
	constructor(@deco a:number) {
		super();
	}
}
```

**Expected behavior:**

I'd expect that I can add a the decorator in the anonymous class constructor

**Actual behavior:** 

I get a compile error in the actor

**Comment by jrieken** [comment] 2016-06-14 07:58
https://www.typescriptlang.org/play/#src=%0D%0Afunction%20deco()%20%7B%0D%0A%09%0D%0A%7D%0D%0A%0D%0Aclass%20Foo%20%7B%0D%0A%09%0D%0A%7D%0D%0A%0D%0Alet%20a%20%3D%20class%20extends%20Foo%20%7B%0D%0A%09constructor(%40deco%20a%3Anumber)%20%7B%0D%0A%09%09super()%3B%0D%0A%09%7D%0D%0A%7D

**Comment by mhegazy** [comment] 2016-06-14 17:12
duplicate of https://github.com/Microsoft/TypeScript/issues/7342

**Closed by mhegazy** 2016-06-14 17:12 UTC
