### ISSUE TITLE
Usage of requestIdleCallback leads to window of never type

### ISSUE THREAD

**Issue by y-a-v-a** [microsoft/TypeScript#52932] opened 2023-02-23 09:57 UTC
# Bug Report

```js
function chatController() {
  console.log('blah');
}

const initializeChat = () => {
  if ('requestIdleCallback' in window) { // var window: Window & typeof globalThis
    window.requestIdleCallback(chatController);
  } else if ('MessageChannel' in window) { // var window: never
    const channel = new MessageChannel();
    channel.port1.onmessage = chatController;
    channel.port2.postMessage(undefined);
  } else {
    window.setTimeout(chatController, 1); // Property 'setTimeout' does not exist on type 'never'.
  }
};
```

`requestIdleCallback` is not available in Safari. I have a fallback as per the above. Why Typescript makes `window` of type `never`? I think because it assumes `requestIdleCallback` is always available. But it clearly isn't.

Within the playground I get mixed results, but within VS Code I get issues independent of setting the target in the preferences.

### 🔎 Search Terms

requestIdleCallback

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?target=1&lib=lib.dom.d.ts&ts=4.9.5#code/PTAEAEBsEsCMC5QFMDOA7JAPALgWAFAgQwKgAmA9gLYB002SATgIayRIFFRyKVUEEAZgFc0AY2zQKaUGIAWzbAGFp2RhUjtGACgCUoAN4FQs6Sg1IakCgHNtAcjbM593QG4CAXwH4xZ7KDQaPTQzDAAXkhKCgEAvKB6oLEAfIbGgYIJ9oxIAI7CqNgAkmTsSmGQsMxiANb2gTIA7kGUjfpG+CYmzWitNDn5hSVlFVW12vKKKmhqGlru6Z7IkChIGVkAsqgozDZRCmgYkPVBoD2t7ekmfmgoAZOHSJBJoBiNoFsoO3vRzI+Qeg8nS6DyONAADhRGNgAIw0aRUba7NbxSbKVTqTRMIFdWQHMGQ6EAJghFDun2+SG0ojISEEQSQZAWwKWT1WaWB3RaFEaNFW2AAKtBERRhNgJjFprMsYwADSgGHMkzefAqoA)

Strangely in playground 4.8.4 it seems to work as expected, but in 4.9.5 in the [playground](https://www.typescriptlang.org/dev/bug-workbench/?target=1&lib=lib.dom.d.ts&ts=4.9.5#code/PTAEAEBsEsCMC5QFMDOA7JAPALgWAFAgQwKgAmA9gLYB002SATgIayRIFFRyKVUEEAZgFc0AY2zQKaUGIAWzbAGFp2RhUjtGACgCUoAN4FQs6Sg1IakCgHNtAcjbM593QG4CAXwH4xZ7KDQaPTQzDAAXkhKCgEAvKB6oLEAfIbGgYIJ9oxIAI7CqNgAkmTsSmGQsMxiANb2gTIA7kGUjfpG+CYmzWitNDn5hSVlFVW12vKKKmhqGlru6Z7IkChIGVkAsqgozDZRCmgYkPVBoD2t7ekmfmgoAZOHSJBJoBiNoFsoO3vRzI+Qeg8nS6DyONAADhRGNgAIw0aRUba7NbxSbKVTqTRMIFdWQHMGQ6EAJghFDun2+SG0ojISEEQSQZAWwKWT1WaWB3RaFEaNFW2AAKtBERRhNgJjFprMsYwADSgGHMkzefAqoA) it seems to fail.

### 🙁 Actual behavior

`window` is cast to `never` type.

### 🙂 Expected behavior

`window` remains `Window & typeof globalThis`

**Comment by IllusionMH** [comment] 2023-02-23 12:23
Duplicate of #51780 and similar issue
https://github.com/microsoft/TypeScript/issues/51780#issuecomment-1339024050 provides explanation and workaround.

**Closed** 2023-02-26 18:00 UTC
Labels: Duplicate
