### ISSUE TITLE
TypeScript build is slow, compileOnSave/--watch taking ~1minute

### ISSUE THREAD

**Issue by bforsythe** [Microsoft/TypeScript#22953] opened 2018-03-28 16:44 UTC
Hi all, first I'll say our team has been big TypeScript fans for a while now (pre-2.x)!  But unfortunately, performance issues have been getting rough, and some people on the team are starting to feel that the type safety isn't worth the substantial build time increase (perhaps a little hyperbolic, but it's definitely frustrating).

First off, here's the diagnostic output:
> node_modules\.bin\tsc -project web/tsconfig.json --diagnostics
Files:           2771  
Lines:         205202  
Nodes:         934381  
Identifiers:   308819  
Symbols:       233717  
Types:          57830  
Memory used: 1191180K  
I/O read:       0.91s  
I/O write:      0.17s  
Parse time:     4.99s  
Bind time:      4.46s  
Check time:    14.12s  
Emit time:     30.09s  
Total time:    53.67s

And here's our tsconfig.json:
>{
  "compileOnSave": true,
  "compilerOptions": {
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "module": "none",
    "noEmitOnError": true,
    "noImplicitAny": false,
    "sourceMap": true,
    "target": "es5",
    "outFile": "./path/to/our/outfile.js",
    "declaration": true,
    "removeComments": true,
  },
  "include": [
    "Content"
  ],
  "exclude": [
    "./path/to/our/outfile.d.ts",
    "node_modules"
  ]
}

Other things worth noting:  
1) We still have a significant amount of .js files in our solution
2) We are still using namespaces and a single outfile for the vast majority of our files.  We have made a small push to start writing modules, but it's pretty painful to mix the two (who loves shim files?  No one), and we have too much code to rewrite everything, so it's been slow going.

If there's anymore information I can provide, please let me know, or if you have any thoughts or suggestions we can try, I'd love to hear them!  The switch to TS has been the number 1 development/debugging time-saving measure we've made since I've been here.  But now it feels like those savings are being reclaimed by the build times :(

Thanks for your help,
Brandon

**Comment by mhegazy** [comment] 2018-04-05 18:00
> performance issues have been getting rough

we would like to know more about the regressions you are having..

**Comment by bforsythe** [comment] 2018-04-05 18:01
Thanks for the response @sheetalkamat !  So is moving to modules and using webpack probably going to be the best solution to this? We've got over 2700 TS files, so turning everything into modules is going to be a process.
Or if we come up with a way to get all the individual JS files included on our pages, do you think just killing the single outFile would be a good step (we were worried about the number of requests that might be performed loading a given page, as well as potential ordering concerns that the TS compiler might take into account when generating the outFile, that we would have to keep in mind when doing our <script> includes)? 

Thanks again,
Brandon

**Comment by bforsythe** [comment] 2018-04-05 20:00
@mhegazy I'll need to run that by my manager, I'll get back to you tomorrow morning.  Is there a secure way I can send it?

Thanks, 
Brandon

**Comment by devuo** [comment] 2018-04-30 09:46
In my team we're seeing the same thing with initial compilation times take ~1 minute from 6-8 seconds. We had to rollback to 2.7 in order to have acceptable initial compilation times.

**Comment by sheetalkamat** [comment] 2018-04-30 17:43
@devuo Can you please share the code to investigate this. We can sign NDA if needed.

**Comment by sheetalkamat** [comment] 2018-05-08 18:57
Closing this bug since this was technically question. If anyone running into issues like slow build, please open new bug with detailed logs. Thanks

**Closed by sheetalkamat** 2018-05-08 18:57 UTC
Labels: Bug, Needs More Info
