### ISSUE TITLE
Control Flow Analysis Doesn't Correctly Narrow Types in Unreachable Code After a Return Statement

### ISSUE THREAD

**Issue by hmzakhalid** [microsoft/TypeScript#55731] opened 2023-09-13 11:44 UTC
### 🔎 Search Terms

"code after return", "dead code typecheck"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Type System Behavior.

### ⏯ Playground Link

[Typescript Lang Link](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMGYAmAKGUCmBbALkQGcoAnVAcwEoiA3OGNRAbwChFPEB6bkuPDkQAbOJRgREACxxkcbAL5s2oSLASIcADwCGeAA7CcWXHmJEAsjv0AeUhTCUANCXJUAfLVcPKiAD6IDEysHFwQCKSIOogAvIjY+MQAdJQ4UBgARACMGdQA3KGcclAgZEg6BYU8fAAqMshwwqIA7lSIEDIQANaaYMSlOMSIAAY6w-FDYHBQiOBoOChgOGhJVTDAiBgAhDrUiMWlSBkAcnCIAIIZlVzViACidDjlwLhkiFD1OgBGcI-tnV0XDUAJ76HAAZQgFH0Mw+ZDgzSGOiQsnhb2AcDeHyEwlQQi+OBaTiqvHi6AkOlgjneUkpIzG7WRiAJs3QCzxKyq4T6My+sWQqEwuzytzuZDRRHOZEoIEEYBmcA2UFBQgA5PY2gE5uylmhVRNEFMZjpiMQYJQwN8jO8zvodGQ9GlZIhFe8VYh1W5HKrVjc-f6A7cQWCPdrFst9TBJtMoqbzZavtaoGdlSHPT4fYo2EA)

### 💻 Code

```ts
function find(item: string): void {
    // some logic here
}

function example(items: Map<string, string>): string | void {
    const a = items.get("1");
    return a;

    // The following check ensures `a` is not undefined.
    if (!a) return "No A";

    // Even after the above check, TypeScript throws an error for the line below,
    // indicating that `a` can be undefined.
    const b = find(a); // Error: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
                       // Type 'undefined' is not assignable to type 'string'.
}
```

### 🙁 Actual behavior

When there's unreachable code following a return statement, TypeScript's control flow analysis seems not to correctly narrow the type based on the checks present in the unreachable code.
TypeScript throws an error indicating `a` can be undefined.

### 🙂 Expected behavior

Even though the code after the return statement is unreachable, TypeScript should recognize that the check `if (!a)` ensures `a` cannot be `undefined` when passed to `find(a)`.

### Additional information and Questions

- Firstly, could you please confirm if this behavior is indeed unintended and not by design?
- If this is an issue worth fixing, could you point me towards the relevant parts of the codebase or any related issues/pull requests that might give me a head start?
- I am eager to take this up and provide a fix. I hope this can be a valuable contribution to the TypeScript community.

**Comment by MartinJohns** [comment] 2023-09-13 11:56
Duplicate of #26914.

**Comment by hmzakhalid** [comment] 2023-09-14 06:38
Hey @RyanCavanaugh, I see the issue is still open. if it needs to be fixed, I'm very keen on contributing and helping resolve it.
Would it be possible to get some pointers or guidance on where to start or any context from the ongoing discussions on the original issue?

**Comment by RyanCavanaugh** [comment] 2023-09-14 17:27
@hmzakhalid this isn't the kind of issue someone unfamiliar with the area would be able to fix

**Closed** 2023-09-17 01:27 UTC
Labels: Duplicate
