### ISSUE TITLE
Cannot use keyof on one type to index fields in another type with the same keys, but different types for the values

### ISSUE THREAD

**Issue by dbinnersley** [microsoft/TypeScript#46928] opened 2021-11-26 19:42 UTC
# Bug Report

### 🔎 Search Terms

keyof types

### 🕗 Version & Regression Information

4.2.3 when running on my own machine
4.5.2 when running on ts playground

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDSxEGcDyAzAFWWAB4CAaOAVUoCE4BeOPAQwBstgA+RuAbwCwAKDhwA2gAU4ASwB2cANaYIeOAQC6ALjj1QMYLIAmWBFACuwYaNEB+NZPVw9B49SvXb1JyH1GTBB3cPTwkg4O1ZYAA3YCgw0Qjo2LDtAIlHZz83EWs7UJyEuEiYqABuYQBfMSVEFTV1cqFhUEhYBGIdaQBzAElZGAxsMh4mQdxCYjJKACNuuRhKGHNuYWbwaHgkFDgAYQgAWzAWGCIUYd4cfekYKc7e-rHhngAyd0EC8QkoCBRYRBl5LRun0BpgsMMtHAsEs5F1GqIKo01q14HgzLIAMYwaQQeQYg5HGAAWQghmAbGGAAp9qTyakAJTaPaHY6nUgEHjvUT42TQuD4lkwbQSFiwaTsEjMwlsp68PiI9x4aBwSk8vkKOB1HDTABWwCxADoalhqbS2PS4CwTABBKBQFiIEg1Ooci1c6xq+BRXg0slsaoNMICwkB3hbYB1b0MaNwABEsy681jcDsUQNMAgAGUYbIupSLdoovC4BV3FBgDAzFA8QTjpaTFLWZMOY1EUA)

### 💻 Code

```ts
export type KeysOfType<T, U, B = false> = {
  [P in keyof T]: B extends true
    ? T[P] extends U
      ? U extends T[P]
        ? P
        : never
      : never
    : T[P] extends U
    ? P
    : never;
}[keyof T];

export type BigIntKeys<T> = KeysOfType<T, bigint, true>

export type CompatType<T> = Omit<T, BigIntKeys<T>> &
  {
    [Property in BigIntKeys<T>]: string;
  };

export function compatModel<T>(model: T): CompatType<T> {
  const compat: Partial<CompatType<T>> = {};
  for (const k of Object.keys(model) as Array<keyof T>) {
    const v = model[k];
    compat[k] = typeof v === "bigint" ? v.toString() : v;
  }
  return compat as CompatType<T>;
};
```

### 🙁 Actual behavior

The final compat[k] shows a type error indicating `Type 'keyof T' cannot be used to index type 'Partial<CompatType<T>>`

### 🙂 Expected behavior

The keys from `T` should be allowed to index `CompatType<T>` since the keys contained in both of the types are identical. The only difference is the values which have changed from bigints to strings.

**Comment by jcalz** [comment] 2021-11-26 23:18
Duplicate of #28884.

**Comment by RyanCavanaugh** [comment] 2021-11-29 19:39
Nice find @jcalz

**Closed by RyanCavanaugh** 2021-11-29 19:39 UTC
Labels: Duplicate
