### ISSUE TITLE
Visual Studio is not implicitly referencing d.ts files in the solution

### ISSUE THREAD

**Issue by davismj** [Microsoft/TypeScript#7128] opened 2016-02-18 03:40 UTC
**TypeScript Version:** 

1.8.0-beta (Visual Studio 2015 Community)

**Code**

According to [this StackOverflow question](http://stackoverflow.com/questions/21803257/how-is-visual-studios-implicit-referencing-of-typescript-files-supposed-to-work), I have checked and double-checked that all files in question have been set, unset, and reset to `Build Action: TypeScriptCompile`. Code is arranged as follows:

>
src
| - modules
| | - config.d.ts
| | - config.ts

**config.d.ts**
```ts
interface Configuration {
  debug?: boolean;
}
```

**config.ts**
```ts
export var config: Configuration = { // "Cannot find name 'Configuration'."
  debug: true
};
```

**tsconfig.json (for reference)**
```json
{
  "compilerOptions": {
    "rootDir": "src/",
    "outDir": "dist/",
    "target": "es5",
    "module": "system",
    "diagnostics": true,
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "noLib": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
  "exclude": [
    "typings/main.d.ts",
    "typings/main",
    "node_modules"
  ]
}
```

**Expected behavior:**
Visual Studio should discover the `d.ts` file and expose the interface to all other TypeScript modules.

**Actual behavior:** 
Visual Studio does not expose the interface to any other module unless the reference is explicitly declared using `/// <reference path="config.d.ts" />`.

**Comment by vladima** [comment] 2016-02-18 04:26
looks like a dupe of #7102 since `.d.ts` file is not automatically picked up

**Comment by davismj** [comment] 2016-02-18 05:12
This is a different issue and here's why:

> For example, hovering Aurelia and pressing F12 (Go to Definition) opens up the correct aurelia-framework.d.ts

In the previous issue, Visual Studio is able to find the d.ts, and activate Intellisense for the contents of the d.ts. The problem is instead with the compiler.

In this case, Intellisense is unaware of the interface and yields the error: `Cannot find name 'Configuration'.`

Screenshots of each issue for reference.

### Intellisense with installed module
![image](https://cloud.githubusercontent.com/assets/3845823/13134378/b6f738b0-d5d3-11e5-903a-984f3b5f00b0.png)

### No Intellisense with local module
![image](https://cloud.githubusercontent.com/assets/3845823/13134422/28ef5448-d5d4-11e5-9fd6-40afe79ee202.png)

**Comment by mhegazy** [comment] 2016-02-19 23:42
the problem is the file names and locations. when using tsconfig with no "files" property, the compiler walks your directory and tried to figure out what files to include. it excludes by default files that it thinks are outputs of other inputs. since you have two files config.d.ts and config.ts it thinks the .d.ts was generated from a .ts at some point and including it will cause duplicate definitions, so it is discarded. 
options:
- add a /// reference to include the file,
- add an import and make your .d.ts file a module
- change the name of the files, config.d.s, config.default.ts and config.production.ts for instance.

**Closed by mhegazy** 2016-02-19 23:42 UTC

**Comment by davismj** [comment] 2016-02-20 03:18
Awesome, great info!

**Comment by davismj** [comment] 2016-02-21 00:10
I deleted the d.ts files and included the interface definitions in their corresponding .ts files:

![image](https://cloud.githubusercontent.com/assets/3845823/13199996/7e4e5f0a-d805-11e5-8af5-0a691ed9dfe6.png)

![image](https://cloud.githubusercontent.com/assets/3845823/13199998/8faba686-d805-11e5-9912-193daf971f0c.png)

However, Visual Studio is still not picking up the definitions.

![image](https://cloud.githubusercontent.com/assets/3845823/13199992/686aa2c0-d805-11e5-9276-46c6009eb082.png)

**Comment by billti** [comment] 2016-02-22 17:23
Seeing as the interface Notification is an export (i.e. not just a globally available type), are you importing it in app.ts?

**Comment by davismj** [comment] 2016-02-22 20:36
I'm not sure what the proper syntax is here, because changing from `export interface` to `declare interface` to `interface` yields no change in behavior.

Right now, I have it as `export` and am manually importing it into `app.ts`.

**Comment by mhegazy** [comment] 2016-02-22 22:09
if it is exported, you need to import it, i.e. `import {Notification} from "notification"`.

**Comment by davismj** [comment] 2016-02-22 22:12
Sure, and that's what I'm doing as a workaround. But I thought Visual Studio would parse all the files in the tree and expose all types to other files. 

I can't get that to work whether I include `export` or `declare` or neither.

**Comment by mykohsu** [comment] 2016-02-23 01:26
@davismj I believe parsing all the files and exposing all types only works with internal modules, which is also not the recommended build option

Same as having to use using "some namespace" in C#, or import in Java, it makes sense to have to import external files that you want to use.

**Comment by davismj** [comment] 2016-02-23 01:33
In my case, this `Notification` is an internal module.

**Comment by mhegazy** [comment] 2016-02-23 18:07
A file with a top level `export` or `import` is considered a "module". Modules introduce a scope; all declarations within that module are not visible outside it unless imported. On the other hand, a non-module file is a script file. all top level declarations in this file are in the global scope and can be accessed everywhere.

you can find more information about modules in https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Modules.md

**Comment by mykohsu** [comment] 2016-02-26 02:11
@davismj You are using the system module loader compile option, that means all files with exports (as mhegazy mentioned) are modules that need to be imported.

**Comment by davismj** [comment] 2016-02-26 03:05
Understood. Thank you!
