### ISSUE TITLE
Performances greatly degrades on parsing very long object literal

### ISSUE THREAD

**Issue by LucasBrazi06** [microsoft/TypeScript#33528] opened 2019-09-20 08:31 UTC
**TypeScript Version:**
typescript@3.7.0-dev.20190920

**Search Terms:**
json performance slow

**Code**
Create a tsx file and put that code below, don't pay attention on the errors but focus on how long it takes to tsc to come back (on my side I never get to the end)

I used the command: tsc --diagnostics --listFiles

```ts
import { PixelRatio, StatusBar } from "react-native";
import { PLATFORM } from "./../variables/commonColor";
import variable from "./../variables/platform";

export default (variables /* : * */ = variable) => {
  const platformStyle = variables.platformStyle;
  const platform = variables.platform;

  const headerTheme = {
    ".span": {
      height: 128,
      "NativeBase.Left": {
        alignSelf: "flex-start"
      },
      "NativeBase.Body": {
        alignSelf: "flex-end",
        alignItems: "flex-start",
        justifyContent: "center",
        paddingBottom: 26
      },
      "NativeBase.Right": {
        alignSelf: "flex-start"
      }
    },
    ".hasSubtitle": {
      "NativeBase.Body": {
        "NativeBase.Title": {
          fontSize: variables.titleFontSize - 2,
          fontFamily: variables.titleFontfamily,
          textAlign: "center",
          fontWeight: "500",
          paddingBottom: 3
        },
        "NativeBase.Subtitle": {
          fontSize: variables.subTitleFontSize,
          fontFamily: variables.titleFontfamily,
          color: variables.subtitleColor,
          textAlign: "center"
        }
      }
    },
    ".transparent": {
      backgroundColor: "transparent",
      borderBottomColor: "transparent",
      elevation: 0,
      shadowColor: null,
      shadowOffset: null,
      shadowRadius: null,
      shadowOpacity: null,
      paddingTop: platform === PLATFORM.ANDROID ? StatusBar.currentHeight : undefined,
      height: platform === PLATFORM.ANDROID ? variables.toolbarHeight + StatusBar.currentHeight : variables.toolbarHeight
    },
    ".noShadow": {
      elevation: 0,
      shadowColor: null,
      shadowOffset: null,
      shadowRadius: null,
      shadowOpacity: null
    },
    ".hasTabs": {
      elevation: 0,
      shadowColor: null,
      shadowOffset: null,
      shadowRadius: null,
      shadowOpacity: null,
      borderBottomWidth: null
    },
    ".hasSegment": {
      elevation: 0,
      shadowColor: null,
      shadowOffset: null,
      shadowRadius: null,
      shadowOpacity: null,
      borderBottomWidth: null,
      "NativeBase.Left": {
        flex: 0.3
      },
      "NativeBase.Right": {
        flex: 0.3
      },
      "NativeBase.Body": {
        flex: 1,
        "NativeBase.Segment": {
          marginRight: 0,
          alignSelf: "center",
          "NativeBase.Button": {
            paddingLeft: 0,
            paddingRight: 0
          }
        }
      }
    },
    ".noLeft": {
      "NativeBase.Left": {
        width: platform === PLATFORM.IOS ? undefined : 0,
        flex: platform === PLATFORM.IOS ? 1 : 0
      },
      "NativeBase.Body": {
        "NativeBase.Title": {
          paddingLeft: platform === PLATFORM.IOS ? undefined : 10
        },
        "NativeBase.Subtitle": {
          paddingLeft: platform === PLATFORM.IOS ? undefined : 10
        }
      }
    },
    "NativeBase.Button": {
      justifyContent: "center",
      alignSelf: "center",
      alignItems: "center",
      ".transparent": {
        "NativeBase.Text": {
          color: variables.toolbarBtnTextColor,
          fontWeight: "600"
        },
        "NativeBase.Icon": {
          color: variables.toolbarBtnColor
        },
        "NativeBase.IconNB": {
          color: variables.toolbarBtnColor
        },
        paddingHorizontal: variables.buttonPadding
      },
      paddingHorizontal: 15
    },
    ".searchBar": {
      "NativeBase.Item": {
        "NativeBase.Icon": {
          backgroundColor: "transparent",
          color: variables.dropdownLinkColor,
          fontSize: variables.toolbarSearchIconSize,
          alignItems: "center",
          marginTop: 2,
          paddingRight: 10,
          paddingLeft: 10
        },
        "NativeBase.IconNB": {
          backgroundColor: "transparent",
          color: null,
          alignSelf: "center"
        },
        "NativeBase.Input": {
          alignSelf: "center",
          lineHeight: null,
          height: variables.searchBarInputHeight
        },
        alignSelf: "center",
        alignItems: "center",
        justifyContent: "flex-start",
        flex: 1,
        height: variables.searchBarHeight,
        borderColor: "transparent",
        backgroundColor: variables.toolbarInputColor
      },
      "NativeBase.Button": {
        ".transparent": {
          "NativeBase.Text": {
            fontWeight: "500"
          },
          paddingHorizontal: null,
          paddingLeft: platform === PLATFORM.IOS ? 10 : null
        },
        paddingHorizontal: platform === PLATFORM.IOS ? undefined : null,
        width: platform === PLATFORM.IOS ? undefined : 0,
        height: platform === PLATFORM.IOS ? undefined : 0
      }
    },
    ".rounded": {
      "NativeBase.Item": {
        borderRadius: platform === PLATFORM.IOS && platformStyle !== PLATFORM.MATERIAL ? 25 : 3
      }
    },
    "NativeBase.Left": {
      "NativeBase.Button": {
        ".hasText": {
          marginLeft: -10,
          height: 30,
          "NativeBase.Icon": {
            color: variables.toolbarBtnColor,
            fontSize: variables.iconHeaderSize,
            marginTop: 2,
            marginRight: 5,
            marginLeft: 2
          },
          "NativeBase.Text": {
            color: variables.toolbarBtnTextColor,
            fontSize: platform === PLATFORM.IOS ? 17 : 0,
            marginLeft: 7,
            lineHeight: 19.5
          },
          "NativeBase.IconNB": {
            color: variables.toolbarBtnColor,
            fontSize: variables.iconHeaderSize,
            marginTop: 2,
            marginRight: 5,
            marginLeft: 2
          }
        },
        ".transparent": {
          marginLeft: platform === PLATFORM.IOS && platformStyle !== PLATFORM.MATERIAL ? -3 : 0,
          "NativeBase.Icon": {
            color: variables.toolbarBtnColor,
            fontSize:
              platform === PLATFORM.IOS && variables.platformStyle !== PLATFORM.MATERIAL
                ? variables.iconHeaderSize + 1
                : variables.iconHeaderSize,
            marginTop: 0,
            marginRight: 2,
            marginLeft: 1,
            paddingTop: 1
          },
          "NativeBase.IconNB": {
            color: variables.toolbarBtnColor,
            fontSize:
              platform === PLATFORM.IOS && variables.platformStyle !== PLATFORM.MATERIAL
                ? variables.iconHeaderSize + 1
                : variables.iconHeaderSize - 2,
            marginTop: 0,
            marginRight: 2,
            marginLeft: 1,
            paddingTop: 1
          },
          "NativeBase.Text": {
            color: variables.toolbarBtnTextColor,
            fontSize: platform === PLATFORM.IOS ? 17 : 0,
            top: platform === PLATFORM.IOS ? 1 : -1.5,
            paddingLeft: platform === PLATFORM.IOS && platformStyle !== PLATFORM.MATERIAL ? 2 : 5,
            paddingRight: platform === PLATFORM.IOS && platformStyle !== PLATFORM.MATERIAL ? undefined : 10
          },
          backgroundColor: "transparent",
          borderColor: null,
          elevation: 0,
          shadowColor: null,
          shadowOffset: null,
          shadowRadius: null,
          shadowOpacity: null
        },
        "NativeBase.Icon": {
          color: variables.toolbarBtnColor
        },
        "NativeBase.IconNB": {
          color: variables.toolbarBtnColor
        },
        alignSelf: null,
        paddingRight: variables.buttonPadding,
        paddingLeft: platform === PLATFORM.IOS && platformStyle !== PLATFORM.MATERIAL ? 4 : 8
      },
      flex: platform === PLATFORM.IOS && platformStyle !== PLATFORM.MATERIAL ? 1 : 0.4,
      alignSelf: "center",
      alignItems: "flex-start"
    },
    "NativeBase.Body": {
      flex: 1,
      alignItems: platform === PLATFORM.IOS && platformStyle !== PLATFORM.MATERIAL ? "center" : "center",
      alignSelf: "center",
      "NativeBase.Segment": {
        borderWidth: 0,
        alignSelf: "flex-end",
        marginRight: platform === PLATFORM.IOS ? -40 : -55
      },
      "NativeBase.Button": {
        alignSelf: "center",
        ".transparent": {
          backgroundColor: "transparent"
        },
        "NativeBase.Icon": {
          color: variables.toolbarBtnColor
        },
        "NativeBase.IconNB": {
          color: variables.toolbarBtnColor
        },
        "NativeBase.Text": {
          color: variables.inverseTextColor,
          backgroundColor: "transparent"
        }
      }
    },
    "NativeBase.Right": {
      "NativeBase.Button": {
        ".hasText": {
          height: 30,
          "NativeBase.Icon": {
            color: variables.toolbarBtnColor,
            fontSize: variables.iconHeaderSize - 2,
            marginTop: 2,
            marginRight: 2,
            marginLeft: 5
          },
          "NativeBase.Text": {
            color: variables.toolbarBtnTextColor,
            fontSize: platform === PLATFORM.IOS ? 17 : 14,
            lineHeight: 19.5
          },
          "NativeBase.IconNB": {
            color: variables.toolbarBtnColor,
            fontSize: variables.iconHeaderSize - 2,
            marginTop: 2,
            marginRight: 2,
            marginLeft: 5
          }
        },
        ".transparent": {
          marginRight: platform === PLATFORM.IOS ? -9 : -5,
          paddingLeft: 15,
          paddingRight: 12,
          paddingHorizontal: 15,
          borderRadius: 50,
          "NativeBase.Icon": {
            color: variables.toolbarBtnColor,
            fontSize: variables.iconHeaderSize - 2,
            marginTop: 0,
            marginLeft: 2,
            marginRight: 0
            // paddingTop: 0
          },
          "NativeBase.IconNB": {
            color: variables.toolbarBtnColor,
            fontSize: variables.iconHeaderSize - 2,
            marginTop: 0,
            marginLeft: 2,
            marginRight: 0
            // paddingTop: 0
          },
          "NativeBase.Text": {
            color: variables.toolbarBtnTextColor,
            fontSize: platform === PLATFORM.IOS ? 17 : 14,
            top: platform === PLATFORM.IOS ? 1 : -1.5,
            paddingRight: platform === PLATFORM.IOS && variables.platformStyle !== PLATFORM.MATERIAL ? 0 : undefined
          },
          backgroundColor: "transparent",
          borderColor: null,
          elevation: 0,
          shadowColor: null,
          shadowOffset: null,
          shadowRadius: null,
          shadowOpacity: null
        },
        "NativeBase.Icon": {
          color: variables.toolbarBtnColor
        },
        "NativeBase.IconNB": {
          color: variables.toolbarBtnColor
        },
        alignSelf: null,
        paddingHorizontal: variables.buttonPadding
      },
      flex: 1,
      alignSelf: "center",
      alignItems: "flex-end",
      flexDirection: "row",
      justifyContent: "flex-end"
    },
    backgroundColor: "transparent",
    flexDirection: "row",
    paddingLeft: platform === PLATFORM.IOS ? 5 : 0,
    paddingRight: platform === PLATFORM.IOS ? 5 : 0,
    justifyContent: "center",
    paddingTop: platform === PLATFORM.IOS ? 18 : 0,
    borderBottomWidth: platform === PLATFORM.IOS ? 1 / PixelRatio.getPixelSizeForLayoutSize(1) : 0,
    borderBottomColor: variables.toolbarDefaultBorder,
    height:
      variables.platform === PLATFORM.IOS && variables.platformStyle === PLATFORM.MATERIAL
        ? variables.toolbarHeight + 10
        : variables.toolbarHeight,
    top: 0,
    left: 0,
    right: 0
  };

  return headerTheme;
};
```
my tsconfig.json

```
{
  "compilerOptions": {
    "target": "ES2016",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    "lib": ["es6"],
    "allowJs": false,                       /* Allow javascript files to be compiled. */
    "checkJs": false,                       /* Report errors in .js files. */
    "jsx": "react-native",                    /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    "noEmit": true,                        /* Do not emit outputs. */
    "noImplicitAny": true,                 /* Raise error on expressions and declarations with an implied 'any' type. */
    "strictNullChecks": false,              /* Enable strict null checks. */
    "noUnusedLocals": true,                /* Report errors on unused locals. */
    "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
    "moduleResolution": "node",            /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    "baseUrl": "src",                       /* Base directory to resolve non-absolute module names. */
    "rootDirs": ["src"],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
    "allowSyntheticDefaultImports": true,  /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
    "esModuleInterop": true                   /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
  },
  "include": [
    "src/theme/components/index.tsx"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}
```

**Expected behavior:**
That tsc returns after few seconds.

**Actual behavior:**
It never comes back!

**Playground Link:**
none

**Related Issues:**
none

**Comment by MartinJohns** [comment] 2019-09-20 10:30
The title is confusing, as there is no JSON involved (except the `tsconfig.json`).

**Comment by AnyhowStep** [comment] 2019-09-20 14:46
Try adding explicit type annotations. They usually speed things up for me for really complex/large types

**Comment by RyanCavanaugh** [comment] 2019-09-20 16:45
I would try to avoid having such a large object literal in your code itself - it's never going to be particularly fast. But this seems small enough that it shouldn't *never finish*; we might have a bug here.

**Comment by ahejlsberg** [comment] 2019-09-21 15:12
I'm unable to reproduce the issue. If I put your example in a file and use your `tsconfig.json` verbatim I get the following error:

```ts
error TS18003: No inputs were found in config file 'c:/tc/test2/tsconfig.json'. Specified 'include' paths were '["src/theme/components/index.tsx"]' and 'exclude' paths were '["node_modules","**/*.spec.ts"]'.
```

When I remove the `"include"` property from `tsconfig.json` the example compiles (in less than a second) and produces 37 errors, all of which I would expect to see.

**Comment by ahejlsberg** [comment] 2019-09-21 15:14
BTW, the object literal in the example isn't particularly large and shouldn't be a problem at all. There is something else going on, likely related to your setup.

**Comment by ahejlsberg** [comment] 2019-10-21 20:22
Closing since it's been a month with no reply.

**Closed by ahejlsberg** 2019-10-21 20:22 UTC
Labels: Needs More Info

**Comment by LucasBrazi06** [comment] 2019-10-21 21:58
@ahejlsberg , thanks for your investigations and your feedbacks !
And I'm sorry to have not answered you sooner !
Indeed you don't have the full project, so it's difficult to reproduce !
Anyway, I split up the object above into small parts and it works now like a charm.
Here is the new format: 

```
import { PixelRatio, StatusBar } from "react-native";
import { PLATFORM } from "./../variables/commonColor";
import variable from "./../variables/platform";

const buildTheme = (variables: any) => {
  // Forced to break up the theme to avoid typescript infinite run!
  const platformStyle = variables.platformStyle;
  const platform = variables.platform;

  const headerTheme: any = {
    backgroundColor: "transparent",
    flexDirection: "row",
    paddingLeft: platform === PLATFORM.IOS ? 5 : 0,
    paddingRight: platform === PLATFORM.IOS ? 5 : 0,
    justifyContent: "center",
    paddingTop: platform === PLATFORM.IOS ? 18 : 0,
    borderBottomWidth: platform === PLATFORM.IOS ? 1 / PixelRatio.getPixelSizeForLayoutSize(1) : 0,
    borderBottomColor: variables.toolbarDefaultBorder,
    height:
      variables.platform === PLATFORM.IOS && variables.platformStyle === PLATFORM.MATERIAL
        ? variables.toolbarHeight + 10
        : variables.toolbarHeight,
    top: 0,
    left: 0,
    right: 0
  };

  headerTheme[".span"] = {
    height: 128,
    "NativeBase.Left": {
      alignSelf: "flex-start"
    },
    "NativeBase.Body": {
      alignSelf: "flex-end",
      alignItems: "flex-start",
      justifyContent: "center",
      paddingBottom: 26
    },
    "NativeBase.Right": {
      alignSelf: "flex-start"
    }
  };

  headerTheme[".hasSubtitle"] = {
    "NativeBase.Body": {
      "NativeBase.Title": {
        fontSize: variables.titleFontSize - 2,
        fontFamily: variables.titleFontfamily,
        textAlign: "center",
        fontWeight: "500",
        paddingBottom: 3
      },
      "NativeBase.Subtitle": {
        fontSize: variables.subTitleFontSize,
        fontFamily: variables.titleFontfamily,
        color: variables.subtitleColor,
        textAlign: "center"
      }
    }
  };

  headerTheme[".transparent"] = {
    backgroundColor: "transparent",
    borderBottomColor: "transparent",
    elevation: 0,
    shadowColor: null,
    shadowOffset: null,
    shadowRadius: null,
    shadowOpacity: null,
    paddingTop: platform === PLATFORM.ANDROID ? StatusBar.currentHeight : undefined,
    height: platform === PLATFORM.ANDROID ? variables.toolbarHeight + StatusBar.currentHeight : variables.toolbarHeight
  };

  headerTheme[".noShadow"] = {
    elevation: 0,
    shadowColor: null,
    shadowOffset: null,
    shadowRadius: null,
    shadowOpacity: null
  };

  headerTheme[".hasTabs"] = {
    elevation: 0,
    shadowColor: null,
    shadowOffset: null,
    shadowRadius: null,
    shadowOpacity: null,
    borderBottomWidth: null
  };

  headerTheme[".hasSegment"] = {
    elevation: 0,
    shadowColor: null,
    shadowOffset: null,
    shadowRadius: null,
    shadowOpacity: null,
    borderBottomWidth: null,
    "NativeBase.Left": {
      flex: 0.3
    },
    "NativeBase.Right": {
      flex: 0.3
    },
    "NativeBase.Body": {
      flex: 1,
      "NativeBase.Segment": {
        marginRight: 0,
        alignSelf: "center",
        "NativeBase.Button": {
          paddingLeft: 0,
          paddingRight: 0
        }
      }
    }
  };

  headerTheme[".noLeft"] = {
    "NativeBase.Left": {
      width: platform === PLATFORM.IOS ? undefined : 0,
      flex: platform === PLATFORM.IOS ? 1 : 0
    },
    "NativeBase.Body": {
      "NativeBase.Title": {
        paddingLeft: platform === PLATFORM.IOS ? undefined : 10
      },
      "NativeBase.Subtitle": {
        paddingLeft: platform === PLATFORM.IOS ? undefined : 10
      }
    }
  };

  headerTheme["NativeBase.Button"] = {
    justifyContent: "center",
    alignSelf: "center",
    alignItems: "center",
    ".transparent": {
      "NativeBase.Text": {
        color: variables.toolbarBtnTextColor,
        fontWeight: "600"
      },
      "NativeBase.Icon": {
        color: variables.toolbarBtnColor
      },
      "NativeBase.IconNB": {
        color: variables.toolbarBtnColor
      },
      paddingHorizontal: variables.buttonPadding
    },
    paddingHorizontal: 15
  };

  headerTheme[".searchBar"] = {
    "NativeBase.Item": {
      "NativeBase.Icon": {
        backgroundColor: "transparent",
        color: variables.dropdownLinkColor,
        fontSize: variables.toolbarSearchIconSize,
        alignItems: "center",
        marginTop: 2,
        paddingRight: 10,
        paddingLeft: 10
      },
      "NativeBase.IconNB": {
        backgroundColor: "transparent",
        color: null,
        alignSelf: "center"
      },
      "NativeBase.Input": {
        alignSelf: "center",
        lineHeight: null,
        height: variables.searchBarInputHeight
      },
      alignSelf: "center",
      alignItems: "center",
      justifyContent: "flex-start",
      flex: 1,
      height: variables.searchBarHeight,
      borderColor: "transparent",
      backgroundColor: variables.toolbarInputColor
    },
    "NativeBase.Button": {
      ".transparent": {
        "NativeBase.Text": {
          fontWeight: "500"
        },
        paddingHorizontal: null,
        paddingLeft: platform === PLATFORM.IOS ? 10 : null
      },
      paddingHorizontal: platform === PLATFORM.IOS ? undefined : null,
      width: platform === PLATFORM.IOS ? undefined : 0,
      height: platform === PLATFORM.IOS ? undefined : 0
    }
  };

  headerTheme[".rounded"] = {
    "NativeBase.Item": {
      borderRadius: platform === PLATFORM.IOS && platformStyle !== PLATFORM.MATERIAL ? 25 : 3
    }
  };

  headerTheme["NativeBase.Left"] = {
    "NativeBase.Button": {
      ".hasText": {
        marginLeft: -10,
        height: 30,
        "NativeBase.Icon": {
          color: variables.toolbarBtnColor,
          fontSize: variables.iconHeaderSize,
          marginTop: 2,
          marginRight: 5,
          marginLeft: 2
        },
        "NativeBase.Text": {
          color: variables.toolbarBtnTextColor,
          fontSize: platform === PLATFORM.IOS ? 17 : 0,
          marginLeft: 7,
          lineHeight: 19.5
        },
        "NativeBase.IconNB": {
          color: variables.toolbarBtnColor,
          fontSize: variables.iconHeaderSize,
          marginTop: 2,
          marginRight: 5,
          marginLeft: 2
        }
      },
      ".transparent": {
        marginLeft: platform === PLATFORM.IOS && platformStyle !== PLATFORM.MATERIAL ? -3 : 0,
        "NativeBase.Icon": {
          color: variables.toolbarBtnColor,
          fontSize:
            platform === PLATFORM.IOS && variables.platformStyle !== PLATFORM.MATERIAL
              ? variables.iconHeaderSize + 1
              : variables.iconHeaderSize,
          marginTop: 0,
          marginRight: 2,
          marginLeft: 1,
          paddingTop: 1
        },
        "NativeBase.IconNB": {
          color: variables.toolbarBtnColor,
          fontSize:
            platform === PLATFORM.IOS && variables.platformStyle !== PLATFORM.MATERIAL
              ? variables.iconHeaderSize + 1
              : variables.iconHeaderSize - 2,
          marginTop: 0,
          marginRight: 2,
          marginLeft: 1,
          paddingTop: 1
        },
        "NativeBase.Text": {
          color: variables.toolbarBtnTextColor,
          fontSize: platform === PLATFORM.IOS ? 17 : 0,
          top: platform === PLATFORM.IOS ? 1 : -1.5,
          paddingLeft: platform === PLATFORM.IOS && platformStyle !== PLATFORM.MATERIAL ? 2 : 5,
          paddingRight: platform === PLATFORM.IOS && platformStyle !== PLATFORM.MATERIAL ? undefined : 10
        },
        backgroundColor: "transparent",
        borderColor: null,
        elevation: 0,
        shadowColor: null,
        shadowOffset: null,
        shadowRadius: null,
        shadowOpacity: null
      },
      "NativeBase.Icon": {
        color: variables.toolbarBtnColor
      },
      "NativeBase.IconNB": {
        color: variables.toolbarBtnColor
      },
      alignSelf: null,
      paddingRight: variables.buttonPadding,
      paddingLeft: platform === PLATFORM.IOS && platformStyle !== PLATFORM.MATERIAL ? 4 : 8
    },
    flex: platform === PLATFORM.IOS && platformStyle !== PLATFORM.MATERIAL ? 1 : 0.4,
    alignSelf: "center",
    alignItems: "flex-start"
  };

  headerTheme["NativeBase.Body"] = {
    flex: 1,
    alignItems: platform === PLATFORM.IOS && platformStyle !== PLATFORM.MATERIAL ? "center" : "center",
    alignSelf: "center",
    "NativeBase.Segment": {
      borderWidth: 0,
      alignSelf: "flex-end",
      marginRight: platform === PLATFORM.IOS ? -40 : -55
    },
    "NativeBase.Button": {
      alignSelf: "center",
      ".transparent": {
        backgroundColor: "transparent"
      },
      "NativeBase.Icon": {
        color: variables.toolbarBtnColor
      },
      "NativeBase.IconNB": {
        color: variables.toolbarBtnColor
      },
      "NativeBase.Text": {
        color: variables.inverseTextColor,
        backgroundColor: "transparent"
      }
    }
  };

  headerTheme["NativeBase.Right"] = {
    "NativeBase.Button": {
      ".hasText": {
        height: 30,
        "NativeBase.Icon": {
          color: variables.toolbarBtnColor,
          fontSize: variables.iconHeaderSize - 2,
          marginTop: 2,
          marginRight: 2,
          marginLeft: 5
        },
        "NativeBase.Text": {
          color: variables.toolbarBtnTextColor,
          fontSize: platform === PLATFORM.IOS ? 17 : 14,
          lineHeight: 19.5
        },
        "NativeBase.IconNB": {
          color: variables.toolbarBtnColor,
          fontSize: variables.iconHeaderSize - 2,
          marginTop: 2,
          marginRight: 2,
          marginLeft: 5
        }
      },
      ".transparent": {
        marginRight: platform === PLATFORM.IOS ? -9 : -5,
        paddingLeft: 15,
        paddingRight: 12,
        paddingHorizontal: 15,
        borderRadius: 50,
        "NativeBase.Icon": {
          color: variables.toolbarBtnColor,
          fontSize: variables.iconHeaderSize - 2,
          marginTop: 0,
          marginLeft: 2,
          marginRight: 0
          // paddingTop: 0
        },
        "NativeBase.IconNB": {
          color: variables.toolbarBtnColor,
          fontSize: variables.iconHeaderSize - 2,
          marginTop: 0,
          marginLeft: 2,
          marginRight: 0
          // paddingTop: 0
        },
        "NativeBase.Text": {
          color: variables.toolbarBtnTextColor,
          fontSize: platform === PLATFORM.IOS ? 17 : 14,
          top: platform === PLATFORM.IOS ? 1 : -1.5,
          paddingRight: platform === PLATFORM.IOS && variables.platformStyle !== PLATFORM.MATERIAL ? 0 : undefined
        },
        backgroundColor: "transparent",
        borderColor: null,
        elevation: 0,
        shadowColor: null,
        shadowOffset: null,
        shadowRadius: null,
        shadowOpacity: null
      },
      "NativeBase.Icon": {
        color: variables.toolbarBtnColor
      },
      "NativeBase.IconNB": {
        color: variables.toolbarBtnColor
      },
      alignSelf: null,
      paddingHorizontal: variables.buttonPadding
    },
    flex: 1,
    alignSelf: "center",
    alignItems: "flex-end",
    flexDirection: "row",
    justifyContent: "flex-end"
  };
  return headerTheme;
};

export default (variables /* : * */ = variable) => {
  return buildTheme(variables);
};

```
