### ISSUE TITLE
VS 2015 project build ignores TypeScriptOutFile setting

### ISSUE THREAD

**Issue by Gitgiddy** [Microsoft/TypeScript#4748] opened 2015-09-11 16:05 UTC
My VS 2015 project build ignores TypeScriptOutFile setting and builds each `.js` file next to its `.ts` source even though the `<TypeScriptCompileOnSaveEnabled>True</TypeScriptCompileOnSaveEnabled>` behavior is working as intended.

On save of any .ts file the single file /scripts/app.js is correctly generated.  But on project build, it is not and the individual .js files are generated instead.  This impacts working through source control since we don't check in the .js output.

I have as the first line in the project:

    <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />

and as the last line:

    <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets')" />

And `<TypeScriptToolsVersion>1.5</TypeScriptToolsVersion>` is set.

Is this a bug in 1.5 and/or something I can fix in my proj file?  What else do I need to check?

Thanks!

**Comment by mhegazy** [comment] 2015-09-11 18:34
looks like a dupe of #3939. do you have TypeScript 1.5.4 installed?

**Comment by Gitgiddy** [comment] 2015-09-11 18:36
Yes, I do have "1.5.4.0" installed as reported by the Extensions & Updates pane.

**Comment by mhegazy** [comment] 2015-09-11 18:37
@paulvanbrenk can you take a look.

**Comment by paulvanbrenk** [comment] 2015-09-11 18:40
Can you post the detailed msbuild logs. You can get the log by running `msbuild yourprojectfile.csproj /fl`

**Comment by Gitgiddy** [comment] 2015-09-11 19:22
<?xml version="1.0" encoding="utf-8"?>
    <Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
      <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />
      <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
      <PropertyGroup>
        <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
        <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
        <ProductVersion></ProductVersion>
        <SchemaVersion>2.0</SchemaVersion>
        <ProjectGuid>{...}</ProjectGuid>
        <ProjectTypeGuids>{349c5851-65df-11da-9384-00065b846f21};{fae04ec0-301f-11d3-bf4b-00c04f79efbc}</ProjectTypeGuids>
        <OutputType>Library</OutputType>
        <AppDesignerFolder>Properties</AppDesignerFolder>
        <RootNamespace>MyApp</RootNamespace>
        <AssemblyName>MyApp</AssemblyName>
        <TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>
        <TypeScriptToolsVersion>1.5</TypeScriptToolsVersion>
      </PropertyGroup>
      <ItemGroup>
        <Reference Include="System" />
        
      </ItemGroup>
      
      <ItemGroup>
        
        <TypeScriptCompile Include="AppScriptsTS\AppTS.ts" />
        
      </ItemGroup>
      <PropertyGroup>
        <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
        <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
      </PropertyGroup>
      <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />
      <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|Any CPU'">
        <TypeScriptTarget>ES5</TypeScriptTarget>
        <TypeScriptCompileOnSaveEnabled>True</TypeScriptCompileOnSaveEnabled>
        <TypeScriptNoImplicitAny>True</TypeScriptNoImplicitAny>
        <TypeScriptModuleKind>None</TypeScriptModuleKind>
        <TypeScriptRemoveComments>False</TypeScriptRemoveComments>
        <TypeScriptOutFile>Scripts/app.js</TypeScriptOutFile>
        <TypeScriptOutDir />
        <TypeScriptGeneratesDeclarations>False</TypeScriptGeneratesDeclarations>
        <TypeScriptNoEmitOnError>True</TypeScriptNoEmitOnError>
        <TypeScriptSourceMap>True</TypeScriptSourceMap>
        <TypeScriptMapRoot />
        <TypeScriptSourceRoot />
      </PropertyGroup>
      
      <Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />
      <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v10.0\WebApplications\Microsoft.WebApplication.targets" Condition="false" />
      <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets')" />
    </Project>

And

    ....
    Target "PreComputeCompileTypeScript" in file "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets" from project "C:\[...]\Source\MyAppWeb\MyAppWeb.csproj" (target "CompileTypeScript" depends on it):
    Using "VsTsc" task from assembly "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\TypeScript.tasks.dll".
    Task "VsTsc"
      C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.5\tsc.exe  --sourcemap --target ES5 --noEmitOnError COMPUTE_PATHS_ONLY "C:\[...]\Source\MyAppWeb\AppScriptsTS\es6Polyfill.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\KOModels\KOModels.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\KOModels\AppStatusRecord.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\KOModels\AppReportCriteria.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\Logger.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\AppTS.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\Pages\Home.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\ServerProxy.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\ServerTypes.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\typings\bootstrap.v3.datetimepicker\bootstrap.v3.datetimepicker.d.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\typings\bootstrap\bootstrap.d.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\typings\highcharts\highcharts.d.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\typings\improvelyDateRangePicker\dateRangePicker.d.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\typings\jquery\jquery.d.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\typings\knockout\knockout.d.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\typings\moment\moment-node.d.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\typings\moment\moment.d.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\typings\toastr\toastr.d.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\typings\tsd.d.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\typings\typeahead\typeahead.d.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\ViewModels\DatePicker.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\ViewModels\DateRangePicker.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\ViewModels\HomeChart.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\ViewModels\ViewModels.ts" "C:\[...]\Source\MyAppWeb\AppScriptsTS\ViewModels\HomeViewModel.ts"
    Done executing task "VsTsc".
    Task "AssignTargetPath"
    Done executing task "AssignTargetPath".
    Done building target "PreComputeCompileTypeScript" in project "MyAppWeb.csproj".
    Target "CompileTypeScript" in file "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets" from project "C:\[...]\Source\MyAppWeb\MyAppWeb.csproj" (target "Compile" depends on it):
    Skipping target "CompileTypeScript" because all output files are up-to-date with respect to the input files.
    Input files: AppScriptsTS\es6Polyfill.ts;AppScriptsTS\KOModels\KOModels.ts;AppScriptsTS\KOModels\AppStatusRecord.ts;AppScriptsTS\KOModels\AppReportCriteria.ts;AppScriptsTS\Logger.ts;AppScriptsTS\AppTS.ts;AppScriptsTS\Pages\Home.ts;AppScriptsTS\ServerProxy.ts;AppScriptsTS\ServerTypes.ts;AppScriptsTS\typings\bootstrap.v3.datetimepicker\bootstrap.v3.datetimepicker.d.ts;AppScriptsTS\typings\bootstrap\bootstrap.d.ts;AppScriptsTS\typings\highcharts\highcharts.d.ts;AppScriptsTS\typings\improvelyDateRangePicker\dateRangePicker.d.ts;AppScriptsTS\typings\jquery\jquery.d.ts;AppScriptsTS\typings\knockout\knockout.d.ts;AppScriptsTS\typings\moment\moment-node.d.ts;AppScriptsTS\typings\moment\moment.d.ts;AppScriptsTS\typings\toastr\toastr.d.ts;AppScriptsTS\typings\tsd.d.ts;AppScriptsTS\typings\typeahead\typeahead.d.ts;AppScriptsTS\ViewModels\DatePicker.ts;AppScriptsTS\ViewModels\DateRangePicker.ts;AppScriptsTS\ViewModels\HomeChart.ts;AppScriptsTS\ViewModels\ViewModels.ts;AppScriptsTS\ViewModels\HomeViewModel.ts
    Output files: AppScriptsTS\es6Polyfill.js;AppScriptsTS\es6Polyfill.js.map;AppScriptsTS\KOModels\KOModels.js;AppScriptsTS\KOModels\KOModels.js.map;AppScriptsTS\KOModels\AppStatusRecord.js;AppScriptsTS\KOModels\AppStatusRecord.js.map;AppScriptsTS\KOModels\AppReportCriteria.js;AppScriptsTS\KOModels\AppReportCriteria.js.map;AppScriptsTS\Logger.js;AppScriptsTS\Logger.js.map;AppScriptsTS\AppTS.js;AppScriptsTS\AppTS.js.map;AppScriptsTS\Pages\Home.js;AppScriptsTS\Pages\Home.js.map;AppScriptsTS\ServerProxy.js;AppScriptsTS\ServerProxy.js.map;AppScriptsTS\ServerTypes.js;AppScriptsTS\ServerTypes.js.map;AppScriptsTS\ViewModels\DatePicker.js;AppScriptsTS\ViewModels\DatePicker.js.map;AppScriptsTS\ViewModels\DateRangePicker.js;AppScriptsTS\ViewModels\DateRangePicker.js.map;AppScriptsTS\ViewModels\HomeChart.js;AppScriptsTS\ViewModels\HomeChart.js.map;AppScriptsTS\ViewModels\ViewModels.js;AppScriptsTS\ViewModels\ViewModels.js.map;AppScriptsTS\ViewModels\HomeViewModel.js;AppScriptsTS\ViewModels\HomeViewModel.js.map
    Done building target "CompileTypeScript" in project "MyAppWeb.csproj".
    ....
    Target "GetTypeScriptCopyToOutputDirectoryItems" in file "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets" from project "C:\[...]\Source\MyAppWeb\MyAppWeb.csproj" (target "GetCopyToOutputDirectoryItems" depends on it):
    Task "AssignTargetPath"
    Done executing task "AssignTargetPath".
    Task "Message"
      Adding items with BuildAction=TypeScriptCompile to the same collections that will be populated (with items of other BuildActions) by the GetCopyToOutputDirectoryItems target
    Done executing task "Message".
    Done building target "GetTypeScriptCopyToOutputDirectoryItems" in project "MyAppWeb.csproj".
(I have the rest of it, but do you need more?  Of course it's huge)

There is no `tsconfig.json` in the files and I'm not using modules other than for namespacing.

**Comment by mhegazy** [comment] 2015-09-11 19:30
can you share your project file?

**Comment by Gitgiddy** [comment] 2015-09-11 19:43
(Just in case you missed it, I did post most of the .csproj file there.)  

Can I email it to you?

**Comment by Gitgiddy** [comment] 2015-09-11 19:47
Same thing happens when `<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets')" />` is above the `<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|Any CPU'"><TypeScriptTarget>ES5</TypeScriptTarget>` stuff too.  I just read that it had to be last so I tried that.

**Comment by mhegazy** [comment] 2015-09-11 20:06
yes. your import has to be the last.
MSBuild will execute these in order of appearance, so if you already imported the targets, before setting the properties, the property values will be ignored.

so move your configuration above your import.

**Comment by Gitgiddy** [comment] 2015-09-11 20:07
Ok, it is already that way.

**Comment by mhegazy** [comment] 2015-09-11 20:09
my email is mhegazy at microsoft. feel free to email me your project file.

**Comment by mhegazy** [comment] 2015-09-11 20:17
looks like a the same issue in https://github.com/Microsoft/TypeScript/issues/4077

**Comment by Gitgiddy** [comment] 2015-09-11 20:21
Yes, that seems to have fixed it.  Thanks!

**Closed** 2015-09-11 20:24 UTC
Labels: Needs More Info
