### ISSUE TITLE
Should remove tailing whitespaces when auto formatting.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#3340] opened 2015-06-02 10:48 UTC
```typescript
class Test { /* enter */}
```

results in:

```typescript
class Test { /* remaining space */ 
    /* cursor */
}
```

expects:

```typescript
class Test {/* no spaces */ 
    /* cursor */
}
```

**Comment by DanielRosenwasser** [comment] 2015-06-02 17:47
Do you mean that even if there's a comment, the whitespace should be removed? Or that only if nothing follows whitespace on the same line, it should be removed?

**Comment by DanielRosenwasser** [comment] 2015-06-02 17:47
Also, @CyrusNajmabadi does Roslyn have this sort of functionality?

**Comment by mhegazy** [comment] 2015-06-02 18:31
Spaces are removed when formatting the document or closing the paren but not on enter.  @vladima has recently looked into this issue. the problem is that the rule that formats the `{` is disabled on enter to avoid removing the line. a fix for this issue can be to split the rule into two, one that formats and removes line, and one that formats only, and enable one on format on enter and disable the other; and vice versa.

**Comment by zhengbli** [comment] 2015-09-28 03:29
This issue appears to be fixed on my machine. @vilic can you confirm?

**Comment by vilic** [comment] 2015-09-28 15:00
@zhengbli Not on the playground.

**Comment by zhengbli** [comment] 2015-09-28 17:18
@vilic I don't think the playground has the most up-to-date bit. Here is what I tried on VS with the master branch:
![gif](https://cloud.githubusercontent.com/assets/1171301/10142887/372c3e38-65ca-11e5-9c99-e83b5289c6a1.gif)

**Comment by mhegazy** [comment] 2015-09-28 18:16
looks fixed. thanks @zhengbli

**Closed by mhegazy** 2015-09-28 18:16 UTC
Labels: Accepting PRs, Bug
