### ISSUE TITLE
Type arguments for type aliases are displayed inappropriately

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#10258] opened 2016-08-10 18:56 UTC
**TypeScript Version:**  nightly

**Code**

```ts
type ConstructorOf<T> = { new(): T }
function f<A, B, C, D, E>(x: ConstructorOf<Object>): void {}
f(class {});
```

**Expected behavior:**

Hovering over the second `f` shows `function f<{}, {}, {}, {}, {}>(x: ConstructorOf<Object>): void`

**Actual behavior:** 

Hovering over the second `f` shows `function f<{}, {}, {}, {}, {}>(x: ConstructorOf<{}, {}, {}, {}, {}>): void`

**Comment by mhegazy** [comment] 2016-09-21 04:20
Duplicate of https://github.com/Microsoft/TypeScript/issues/10337

**Closed by mhegazy** 2016-09-21 04:20 UTC
Labels: Bug
