### ISSUE TITLE
Include doesn't import files from outDir

### ISSUE THREAD

**Issue by GiedriusGrabauskas** [Microsoft/TypeScript#10168] opened 2016-08-05 07:35 UTC
**TypeScript Version:**  2.0.0-beta

**Code**

tsconfig.json

``` json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "jsx": "react",
    "rootDir": "src",
    "outDir": "wwwroot",
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "include": [
    "src/**/*",
    "wwwroot/libs/**/*.d.ts"
  ]
}
```

**Expected behavior:**
All `.d.ts` files in `wwwroot/libs` folder should be imported in project.

**Actual behavior:** 
Files not imported and I get `Cannot find module` error.

When I change `outDir` to `wwwroot/app`, its work.

**Comment by mhegazy** [comment] 2016-12-14 06:29
This should be working as intended in `typescript@2.1.4`.

**Comment by mhegazy** [comment] 2016-12-14 06:29
closing in favor of https://github.com/Microsoft/TypeScript/issues/12334

**Closed by mhegazy** 2016-12-14 06:29 UTC
