### ISSUE TITLE
Auto import completion entries still causing debug failure in resolveEntityName, getTargetOfExportAssignment with TS 3.1.3 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#28149] opened 2018-10-26 00:18 UTC
**TypeScript Version:**  3.1.3

This is reopening #27636 for TS 3.1.3. A few users on VS Code 1.28.2 using TypeScript 3.1.3 still seem to be hitting this: https://github.com/Microsoft/vscode/issues/61660, https://github.com/Microsoft/vscode/issues/61452

@sandersn @andy-ms @DanielRosenwasser Can you please just verify that this issued has been fully fixed in 3.1.3. If not, can we try getting the fix in for 3.1.4. I'll follow up with the users on the VS Code side to see if this is fixed in typescript@next

**Comment by sandersn** [comment] 2018-10-26 15:12
@andy-ms can confirm, but I'm pretty sure this fix is ca6e2e7bb169b486c0626be52c4d53b03d603f4a (in #28008), which is ***not*** in 3.1.3. In fact, it is the reason we're doing 3.1.4, as far as I know.

**Comment by mjbvz** [comment] 2018-10-26 18:57
Ok, I'm seeing a different stack here than was original reported in #27471

Do these issues have the same root cause?

**Comment by ConneXNL** [comment] 2018-10-30 11:56
Tried 1.28.2 with 3.1.3 default didnt work
Tried 1.28.2 with workspace 3.1.3, didnt work
Tried 1.28.2 with workspace 3.1.4, didnt work
Tried 1.28.2 with workspace 3.1.2, didnt work
Tried 1.28.2 with workspace 3.1.1, didnt work
Tried 1.27.2 with custom 3.1.3, didnt work
Tried 1.27.2 with 3.0.3 default worked
Back to 1.28.2, with workspace 3.0.3, worked

**Comment by andy-ms** [comment] 2018-10-30 16:17
@mjbvz That stack trace isn't related to #27471, but I think it is a duplicate of #27317 which should already be fixed in `release-3.1` (#27696).
@ConneXNL Could you test with `typescript@next`?

**Comment by djensen47** [comment] 2018-10-30 19:50
Hi, I was asked to post here.

I'm using VS Code 1.28.x and Auto Import is not working. I tried using typescript@next but it did not resolve the issue.

**Comment by gcazaciuc** [comment] 2018-11-01 12:06
Same issue as @djensen47 above. Same VSCode version(1.28.2), tried with TS 3.1.3, 3.1.5 and next but Auto import still not working.

Stack trace:
```console
'getCodeFixes' request failed with error.
Error processing request. Debug Failure.
Error: Debug Failure.
    at Object.assertDefined (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:1446:24)
    at getDefaultExportInfoWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108210:80)
    at getDefaultLikeExportInfo (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108191:24)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108174:35
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108318:21
    at forEachExternalModule (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108331:21)
    at forEachExternalModuleToImportFrom (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108316:13)
    at getExportInfos (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108172:13)
    at getFixesInfoForNonUMDImport (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108158:57)
    at getFixesInfo (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108099:50)
    at Object.getCodeActions (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107861:28)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:106400:121

```console

**Comment by ConneXNL** [comment] 2018-11-01 21:40
@andy-ms typescript@next did not solve it.

**Comment by andy-ms** [comment] 2018-11-01 21:44
@ConneXNL Can you sure sample code that reproduces the error?

**Comment by blikblum** [comment] 2018-11-02 00:09
I get the following stack trace using typescript 3.2.

To trigger: 
* load this app: https://github.com/blikblum/pdfmake-playground
* Go to main.js
* Try to expand `container`

```
Info 317  [21:5:34.150] getCompletionData: Get current token: 0
Info 318  [21:5:34.150] getCompletionData: Is inside comment: 0
Info 319  [21:5:34.150] getCompletionData: Get previous token 1: 0
Info 320  [21:5:34.151] getCompletionData: Get previous token 2: 1
Info 321  [21:5:34.151] getCompletionsAtPosition: isCompletionListBlocker: 0
Info 322  [21:5:34.153] getCompletionData: Semantic work: 2
Err 323   [21:5:34.158] Exception on executing command {"seq":31,"type":"request","command":"completionEntryDetails","arguments":{"file":"d:/repositories/pdfmake-playground/src/main.js","line":7,"offset":4,"entryNames":[{"name":"container","source":"d:/repositories/pdfmake-playground/src/common/di"}]}}:

    Debug Failure. Unknown entity name kind. SyntaxKind: BinaryExpression

    Error: Debug Failure. Unknown entity name kind. SyntaxKind: BinaryExpression
        at resolveEntityName (C:\Users\Luiz Américo\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:32374:32)
        at getTargetOfExportAssignment (C:\Users\Luiz Américo\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:32200:29)
        at getTargetOfAliasDeclaration (C:\Users\Luiz Américo\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:32222:28)
        at Object.getImmediateAliasedSymbol (C:\Users\Luiz Américo\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:30616:45)
        at getDefaultExportInfoWorker (C:\Users\Luiz Américo\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:109270:39)
```

**Comment by andy-ms** [comment] 2018-11-02 21:53
@blikblum Thanks, reproduced it.

**Comment by andy-ms** [comment] 2018-11-02 22:07
Update: I can reproduce it in `typescript@next` but not with a local build. May have been fixed by #28303.

**Comment by MadaraUchiha** [comment] 2018-12-02 09:37
Howdy! Thanks for your work on this matter so far, I can see you've been battling it for a few months now.

Wanted to add to the log that I'm still affected by this as of vscode
```
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

And TypeScript version 3.2.1.

**Comment by sandersn** [comment] 2019-05-17 23:18
@mjbvz Are you still seeing these errors?

@blikblum I tried to follow your repro steps and couldn't find `container` in main.js, even after checking out the commit from October 20, 1c21a8c, which I guess is the one that was current when you found the crash originally. 

I found a declaration of 'container' in common/di.js by looking at the stack trace, but it doesn't crash anymore for me. Does it still crash for you?

**Comment by blikblum** [comment] 2019-05-18 00:09
> I tried to follow your repro steps and couldn't find container in main.js

It did not exists in main.js, to reproduce write yourself "cont" somewhere in main.js and try to invoke auto import. It should add the container import from di module.

I'm not with my dev machine. Will try to reproduce ASAP

**Comment by blikblum** [comment] 2019-05-19 10:27
@sandersn working fine now (vscode 1.34)

**Closed** 2019-05-20 16:06 UTC
Labels: Bug, VS Code Tracked
