### ISSUE TITLE
Possible to get a "difference" type i.e. type A - type B ?

### ISSUE THREAD

**Issue by AJamesPhillips** [Microsoft/TypeScript#14626] opened 2017-03-13 11:08 UTC
Given:

```
interface Base {
  field1: string;
}
interface ConcretePartial {
  field2: string;
}
interface Concrete extends Base, ConcretePartial {
}

var some_base_fields: Base = {field1: ''};
var extra_fields_for_concrete: ConcretePartial = {field2: ''};
var new_object: Concrete = _.assign<{}, Base, ConcretePartial>({}, some_base_fields, extra_fields_for_concrete)
```

I'm wondering if it is possible to get a type with the structure of `Concrete ∖ Base` (i.e. `{field2: string }`)  so that instead you could use:

    var new_object: Concrete = _.assign<{}, Base, Concrete ∖ Base>({}, some_base_fields, extra_fields_for_concrete)

I've read https://www.typescriptlang.org/docs/handbook/advanced-types.html and checked the issues and it doesn't seem possible.  I wanted to confirm that that's the case and if there were any plans for this "shorthand" type difference notation?  Also if there's a better pattern to use when dealing with extended interfaces, for example the OOP class approach would simplify this but I was curious if it's possible to do easily with interfaces?

**Comment by kitsonk** [comment] 2017-03-13 14:07
Dupe of #4183

**Closed** 2017-03-13 17:28 UTC
Labels: Duplicate
