### ISSUE TITLE
Inconsistent Treatment of Shorthand Functions

### ISSUE THREAD

**Issue by ChrisGrohHS** [Microsoft/TypeScript#11062] opened 2016-09-22 17:35 UTC
**TypeScript Version:**  2.0.3

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
function testFunction(x: string | Function): any {
    if (typeof x === 'string') {
        return {
            key: function (a: any, b: any) {
                // Fine, x is string
                return a[x];
            }
        };
        return {
            key(a: any, b: any) {
                // Fails, x is string | Function here
                return a[x];
            }
        };
    }
}
```

**Expected behavior:**
Compiles fine

**Actual behavior:** 
Error: An index expression argument must be of type 'string', 'number', 'symbol', or 'any'.

**Comment by mhegazy** [comment] 2016-09-22 17:41
duplicate of https://github.com/Microsoft/TypeScript/issues/10501

**Closed by mhegazy** 2016-09-22 17:41 UTC
