### ISSUE TITLE
Erroneous control flow type narrowing in loops

### ISSUE THREAD

**Issue by dead-claudia** [microsoft/TypeScript#15835] opened 2017-05-14 22:33 UTC
**TypeScript Version:**  2.3.2

**Code**

```ts
const enum Escape {None, Any}

function scan(): void {
    let escape: Escape = Escape.None;

    while (true) {
        // Error: Operator '===' cannot be applied to types 'Escape.None' and 'Escape.Any'.
        escape = escape === Escape.Any ? Escape.None : Escape.Any;
    }
}
```

**Expected behavior:**

The type to be correctly broadened, since it's in a loop.

**Actual behavior:**

The error denoted in the code comment above the line in question.

**Comment by isiahmeadows** [comment] 2017-05-14 22:37
Note that neither of these variants reproduce the bug:

```ts
// Variant 1
const enum Escape {None, Any}

function scan(): void {
    let escape = Escape.None as Escape;

    while (true) {
        escape = escape === Escape.Any ? Escape.None : Escape.Any;
    }
}

// Variant 2
function scan(): void {
    let escape = false;

    while (true) {
        escape = escape === true ? false : true;
    }
}
```

My current workaround is casting the `escape` in the condition, like in this:

```ts
const enum Escape {None, Any}

function scan(): void {
    let escape: Escape = Escape.None;

    while (true) {
        // No error here
        escape = (escape as Escape) === Escape.Any ? Escape.None : Escape.Any;
    }
}
```

Also, note that in my code, I have about 8-10 cases, for a `while`/`switch`-based finite state machine loop.

**Comment by JShabtai** [comment] 2018-03-15 22:22
I just noticed what I believe is the same bug, but without the loop:

```typescript
enum MyEnum {
    Foo,
    Bar
}

class MyClass {
    private state: MyEnum;

    // Set state to Bar
    private modify(){
        this.state = MyEnum.Bar;
    }

    public fn() {
        this.state = MyEnum.Foo

        this.modify();

        if (this.state === MyEnum.Bar) {
            // Do stuff here...
        }
    }
}
```

This produces the following error

```
tmp.ts(19,13): error TS2365: Operator '===' cannot be applied to types 'MyEnum.Foo' and 'MyEnum.Bar'.
```

Just tested this with `tsc` version 2.7.2

Seems that typescript doesn't think that variables of enum type can ever change?

**Comment by isiahmeadows** [comment] 2018-03-16 14:37
@JShabtai Yours is subtly different:

- Mine is purely with local variables, where yours is with properties.
- Yours *could* change between checks, where mine theoretically couldn't.

**Comment by RyanCavanaugh** [comment] 2024-03-05 00:36
Works now. Other comment is a dupe of 9998

**Closed by RyanCavanaugh** 2024-03-05 00:36 UTC
Labels: Bug
