### ISSUE TITLE
we can define any number which is not in our enum.

### ISSUE THREAD

**Issue by guoard** [microsoft/TypeScript#46759] opened 2021-11-10 11:24 UTC
# Bug Report

we expect not to be able to define a role number which is not in our enum, but we can :|

```
enum Role {
    ADMIN,
    AUTHOR
}

interface User {
    role: Role
}

const user1: User = {
    role: 1234
}
```

#### 🙁 Actual behavior

Compiles with out any Error.

#### 🙂 Expected behavior

Type 'number' is not assignable to type 'Role'.

## Different behavior with String

but this code gives us correct error message: 
> Type '"c"' is not assignable to type 'Role'.
```
enum Role {
    ADMIN = 'a',
    AUTHOR = 'b'
}

interface User {
    role: Role
}

const user1: User = {
    role: 'c'
}
```

**Comment by MartinJohns** [comment] 2021-11-10 12:19
Duplicate of #26362, which provides plenty of reasoning for this behaviour. Used search terms: `enum number in:title`

**Closed** 2021-11-10 13:11 UTC
