### ISSUE TITLE
“cannot be named” when generating declarations for re-exported classes

### ISSUE THREAD

**Issue by dakisxx** [Microsoft/TypeScript#8612] opened 2016-05-15 21:16 UTC
**TypeScript Version:** 

1.8.10 / nightly (1.9.0-dev.20160515)

**Code**

```ts
// file ThingA.ts
export class ThingA { } 

// file ThingB.ts
export class ThingB { }

// file Things.ts (re-export)
export {ThingA} from "./ThingA";
export {ThingB} from "./ThingB";

// file Test.ts (uses re-exported classes)
import * as things from "./Things";

export class Test {
    public method = (input: things.ThingA)  => { };
}

// compile
tsc Test.ts --declaration --outDir compiled

```

**Expected behavior:**
No errors
**Actual behavior:** 
> Test.ts(5,5): error TS4029: Public property 'method' of exported class has or is using name 'ThingA' from external module ".../ThingA" but cannot be named.

It seems declaration file can't be generated due to the `things.ThingA` reference, but in a similar case without re-exporting it works fine (I will give an example of this in the next post). 

If I change the import statement in Test.ts to this:
```ts
import {ThingA,ThingB} from "./Things";
```
(instead of `import * as things`) and further use `ThingA` directly, there are no errors, but this defeats the purpose of re-exporting.

**Comment by dakisxx** [comment] 2016-05-15 21:21
Here is a similar example without a re-export which works fine:

````ts
// file Things.ts
export class ThingA { } 
export class ThingB { }

// file Test.ts
import * as things from "./Things";

export class Test {
    public method = (input: things.ThingA)  => { };
}

// compile
tsc Test.ts --declaration --outDir compiled
````

This is the generated `Test.d.ts`
````ts
import * as things from "./Things";
export declare class Test {
    method: (input: things.ThingA) => void;
}
````

**Comment by mhegazy** [comment] 2016-05-16 17:37
this is the same root cause as https://github.com/Microsoft/TypeScript/issues/5938. the compiler follows the `export *` references to their sources, then it does not find this file explicitly imported and and thus thinks that the name is not available on any of the imports.

**Comment by mhegazy** [comment] 2016-05-16 17:37
closing in favor of #5938

**Closed by mhegazy** 2016-05-16 17:37 UTC
