### ISSUE TITLE
'string | number' is not allowed as an index signature parameter type

### ISSUE THREAD

**Issue by malibuzios** [Microsoft/TypeScript#7666] opened 2016-03-24 09:17 UTC
**TypeScript Version:** 
1.8.7

**Code**

```ts
type StringOrNumberKeys: { [key: string | number]: number };
```

**Expected behavior:**
Should work

**Actual behavior:** 
```ts
Error: an index signature parameter must be 'string' or 'number'
```

**Comment by mhegazy** [comment] 2016-03-24 16:22
duplicate of https://github.com/Microsoft/TypeScript/issues/1705

**Closed by mhegazy** 2016-03-24 16:22 UTC

**Comment by mhegazy** [comment] 2016-03-24 16:24
also note, that using string indexer will achieve what you want.

```ts
type StringOrNumberKeys: { [key: string]: number };
```
