### ISSUE TITLE
Typescript doesn't handle reexporting modules with default exports correctly

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#4513] opened 2015-08-28 00:10 UTC
`check.ts`:
```ts
import it from './a';
```

`a.ts`:
```ts
export * from './b';
export * from './c';
```
b.ts
```ts
export default function foo() { console.log('b') };
```

c.ts
```ts
export default function bar() { console.log('c'); };
```

TS complains that it can't find a default export in `a` with which to define `it`.

Since both `b` and `c` export a member named 'default' (since that's all the default keyword really means), `a` should, transitively, have a `default` for `check` to import. 

The JS language service in VSCode also has the same (incorrect) assumption. 

Additionally, for my own information, I ran some ES6 JS through traceur/systemjs - it looks like the convention is that in the case of "collisions" in `export *` situations, the latter exports overshadow the prior - so in this case, `it` is `c`'s `bar`, as `a` imported it second.

**Comment by DanielRosenwasser** [comment] 2015-08-28 00:15
I believe this is by design. See [ResolveExport](http://www.ecma-international.org/ecma-262/6.0/#sec-resolveexport):

> c. NOTE A `default` export cannot be provided by an `export *`.

**Comment by weswigham** [comment] 2015-08-28 00:17
If that's the case then I'll need to go file a bug for this against system js/traceur. They were the implementation I checked against.

**Comment by DanielRosenwasser** [comment] 2015-08-28 00:20
I do think this is the case - note that the ability to re-export a default export is currently a [Stage 1 proposed addition to ES7](https://github.com/leebyron/ecmascript-more-export-from), so it would imply that `export * from "blah"` currently doesn't work.

**Comment by weswigham** [comment] 2015-08-28 00:21
If that's the case then I'll need to go file a bug for this against system js/traceur. They were the implementation I checked against.

**Comment by vladima** [comment] 2015-08-28 00:30
for reference: 
- Babel - https://github.com/babel/babel/issues/1426
- Traceur - https://github.com/google/traceur-compiler/pull/1914

Closing as "By Design"

**Closed by vladima** 2015-08-28 00:30 UTC
