### ISSUE TITLE
useDefineForClassFields breaks augmentation/overwrite of class members with decorators

### ISSUE THREAD

**Issue by mzeiher** [microsoft/TypeScript#35081] opened 2019-11-13 09:29 UTC
**TypeScript Version:**  3.8.0-dev.20191113

**Search Terms:**
decorators, useDefineForClassFields, useDefineForClassFields decorators bug 
**Code**

```ts
function Decorator() {
    return function (target, propKey, descriptor) {
        const symbol = Symbol();
        target.constructor.prototype[symbol] = descriptor ? typeof descriptor.initializer !== 'undefined' ? descriptor.initializer() : undefined : undefined;
        return {
            configurable: true,
            enumerable: true,
            set(value) {
                this[symbol] = value;
            },
            get() {
                return this[symbol] + 'decorated';
            }
        }
    }
}

class TestTSDefine {
    @Decorator()
    myProp = "test";
}

console.log(new TestTSDefine().myProp);
```

**Expected behavior:**
output should be 'testdecorated'

**Actual behavior:**
output is 'test'

Use the same code with "useDefineForClassFields = false"
output is the expected 'testdecorated'

with babel (also [[Define]] behaviour) everything works.

**Playground Link:** http://www.typescriptlang.org/play/?useDefineForClassFields=true&experimentalDecorators=true&ssl=1&ssc=1&pln=23&pc=40#code/GYVwdgxgLglg9mABAEQKYTgJwIZSwCgEpEBvAKEUsU1ShEyVElgUXym0wHNaAaRAA6Y4AgNKoAnvwAmqAM4RMMAXkzFyVTYgxg5URHIkBbAEZwANogC8iAMrGz5ogG4KWyh260AdDr2YQaCxvITg8KAkBVABtQ1MLAF1rRFkFJRUsRAB+RAiouGAU+UVlVW8YMBhYbHMYAC9UTEQAQisbAHJwWWAK1Gl27KK00uCKqpga+saiRAAuRC7UHrA+uYWwbt7pV3dKGjoGUjddqh0ernpsE3NUeagA1F5jk8RUMBAjRqubu4enl6oclo+AAbjUQKh1M8AR4ABYwOSxByJZJg8wQnYwgC+-xhPCgMw0MM0+3oSCg8MRcUcSQA1Ih2rIMDgoH12piAVjoVQuZouVyyBBzNg5HJEAAVeRQcW2NDLVBHTQAATQzNwBEIzyMEgACsIBMkAESsvSG1wCvwWVDecxwLj4FYAdwlUplct6RG82r1IkIziAA

** Repository to reproduce with Babel and Typescript **: https://github.com/mzeiher/decorator-ts-define-bug (see README)

**Comment by rictic** [comment] 2020-01-22 21:50
Simpler example:

```typescript

const Decorator: PropertyDecorator = () => {
    return {
        get() {
            return 'decorated value';
        }
    }
};

class TestTSDefine {
    @Decorator
    myProp = 'property initializer value';
}

console.log(new TestTSDefine().myProp);
```

 http://www.typescriptlang.org/play/?useDefineForClassFields=true&experimentalDecorators=true#code/FAYw9gdgzgLgBAEQKbgE4EMZlQLjgBVTAAclUYBPZNTbOAXjgAoBKBgPjgG9g4+5USGAFdUEbr35SA5kNYSpi-oJFi4AcgAmKbJiSa4AN3QAbYUnUBuSUoC+NuPdvXQJ9FChwAKklheAysgAZgCWEEgK-AAC1LpYqA4AthSEJAxwAETERKTkFHBhITAhpiEAXmRGpuYZ1vagkFBgJkgAdCZg0kzhAO7evjABwWFIrK3JqcQs1kA

**Comment by mzeiher** [comment] 2020-03-29 09:10
Regarding this bug, it would be nice if the typescript team could align the implementation for decorators and define semantics for fields to the current babel implementation (legacy mode) this would make a lot of things much easier especially for framework developers who ship decorator libraries (currently I'm detecting and testing TS legacy, Babel Legacy and the Babel Stage 2 implementation) a 4th decorator flavor makes it just harder to maintain (yes I know decorators are highly experimental ;))

one thing regarding inheritance, currently the useDefineForClassFields just overrides the property descriptor of super (defines a new one on the instance), it would be nicer if something like the babel helper could be used: this will just update the value but leave a possibly augmented (by a decorator or manual) intact (just the initalizer value is overridden)
```
function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }
```

**Comment by Kukkimonsuta** [comment] 2020-04-02 23:17
In relation to replacing a class field/property/method - following code works on existing implementations of decorators with exception of TypeScript fields when using `useDefineForClassFields`. Unfortunately this is breaking without workaround. If fully aligning implementation with either babels "modern" or "legacy" decorators is too much work, perhaps consider implementing [#29299 Option to disable decorator transform](https://github.com/microsoft/TypeScript/issues/29299) instead and let people further transform them themselves.

|  | Fields | Properties | Methods |
|------------------------------------------------|--------|------------|---------|
| Babel "modern" | ✅ | ✅ | ✅ |
| Babel "legacy" | ✅ | ✅ | ✅ |
| TypeScript (without "useDefineForClassFields") | ✅ | ✅ | ✅ |
| TypeScript (with "useDefineForClassFields") | ⛔️ | ✅ | ✅ |

Code here:

[Gist](https://gist.github.com/Kukkimonsuta/88c8ff566d1b1d8a4cd81806cf637cb4)

[TypeScript playground](https://www.typescriptlang.org/play/index.html?experimentalDecorators=true&ts=3.8-Beta&ssl=1&ssc=1&pln=10&pc=1#code/JYOwLgpgTgZghgYwgAgApQPYAdpgJ4AiEAzglMFmBlMgN4BQyTyA9C8jMBADYAmyoYGGBxuwAF7QO1ZNwgBzRHmS8ICanCpRijZoOGiJ0APwAuZAAoAlMgC8APmQBXEAGsQGAO4gA3PQC+9PQwLgjCGCDIALZwrhAA8gBGxNAAbnCJcujYuHgWIHBREObEYOQg8gA0KiRkFFrm2ThQ+ESk5JTU1foiYpJQZpY2Ds5uHt42DMzI6iClyCAQnm11nVCNmM2ttR1adnS600wQIE5FUBly5qrt9dQAdCdn0JcQlYdHs5zyTheZxTVbmt7l9gD8-nJ3tN-H4PsAYJYbqstPd5BAwMgAD6YwHIh4pMCTD7TeGInZ3KCo9FEo60mYReZosCQGi2XG7B5M2F0o6LZbk4FM-YhEBhYARIYHHk82bzdLcJwoNlMlkg0TcCxgAAWwGIVj80rpsowcnu3Aw8gsAHJkABaZBW6oFIrVK1C+WKx3ID0QfXEw3IKDo36RH0GgMw-1MQI80kWJEcykEmkB2UYgks-YJin3AncgN8laJ3Po4WhcKRCw+8wudxeEApgPMY2m82Wm32r3Ot4Ogne0SK5BUL0+v1N6YZ6Bq7ga7W66qj8OGyM8mPMfzIHgpKV0uQYnqGST8NnwbgpJdHPfIUrUAG18aRNnZ4FhoI8wsClFCk-l8WVxvSnGACEB59BAvAAU2bBDjqxACHBVAYLImgoKSoFGDQWpwHBxDAKom4wDAahgMQ1SJE4+5gFacFYJgiSXMoiQkBingoAgcCRLwGBRoBCIWOh-SQeOTA3kG+wCVO7EzpqsFjsJyBrsJEnHkOUCKheq5vqmDImhAZoWtadoOk6hQ9m6pY+l6om+hpdJBmAIbXloEC2dGrkCHxz4op45BgK8Qm0h+QIon2P6ihWljVqMdYTDuSl8SBIBCL0RgQXF8lMNBxCuBQAhJQYfSaH+16gEgJX4RAhHEXBcBBiAVoYrRORQNwyjEE4WBYNQkD8BxeCeHAeA8U2yn7GU6nDXSgSTbS0EeJA5gACoAMrIJ4QhahgFHIAABk4KREJwiwAGLUAAwtw2HEMdXB8MQO1rcAM6qWCaI0LwvygPI9JzONYTUDNRzQaS2ooJwPD8FhcGqPATjcBiPqA9MLZ6W2hmdiZLq9hZA4oMOC643JwnWfsr5NiuU0fNN0z2Y5QV4lAfjTSKYoShgyRpK8mq1Uy5h9dUTVbHgADSEB4CUZRfdUXnUIMTS5EWFJWHzIDKFMeh8fgOAYAigu5KLyi2EbDouDDoDgTaABkltDng2sIjLrLG1apuVebvBWgFrDsAARFEGCqFAIA+zU6gXFoOgyjprYGVaAAC7MpFA6T-F6flQEy9xxHgrp2I4Xou7hFTRAH0CcWoGgR57+a0rTQfpTyOUgLw5h++im28D7UIBtn5jp5n2fd4aWCXUgRTgK39Zd4DjvmDEcRJEnKdZJsuTcxn6JZ2L1T95vjs7zzm8SVAVhD0cFPRpuZ6oZrdsQDr7IUsgQHO67R0W170E+3IigIHgIeqDDpoagpFkCLTvstZEodK4gOkDQIo2oA4C1Xi0LgkcjTR1RrHBOHNk6vC9HrFoItt4OjzsZE2Rdvo-yUNA8OICvSOz9DxOukR54JFwcvCA8siEWEIfgA20tPxdEfsCY+RMFJX23OrWa7BwE4EgbsWhwDtBwI4LdXg6DaQo30u2HBS98HIOavwkhNoRgF32l9MBECoGAJgdoauWla7BnrmwxenN-jcPwLwlBxic4NzpE8c4rw+5qTeIDUE4JgmqUVGfHkPkhBRPGmE1c4jAjTQQJdYgcFTpIWkcgPR7i5AfCiHgG6EMJblG+myK0oErQ13yYnQpEBil4AALLtwDtYOgClHHIAAPolKaPsAAjBeApeD-gfCFIMzYXTaCBmcZEOcxB7gDLwE0HwPSJylhmdgKsuNzCnCiExE+3TlmrN2VgUmuNNlpKCGmaQSE2R8mQDk6wfhtFo3MsySxJSyl8AcTADAGB7h-PUbCT5scMy-NKeowFwLQWwohvsH26gMA5RID7CFmCdHWikmIYuJT2mII9n6IFIKiUdN4O8+5OKvkqhhU0eFFL1mbGxXMXSuLqLomEIS1l2BmWIqGWyAALAAJh8EAA)

[Babel repl](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYOwLgpgTgZghgYwgAgApQPYAdpgJ4AiEAzglMFmBlMgN4BQyTyA9C8jMBADYAmyoYGGBxuwAF7QO1ZNwgBzRHmS8ICanCpRijZoOGiJ0APwAuZAAoAlMgC8APmQBXEAGsQGAO4gA3PQC-9PQwLgjCGCDIALZwrhAA8gBGxNAAbnCJcujYuHgWIHBREObEYOQg8gA0KiRkFFrm2ThQ-ESk5JTU1foiYpJQZpY2Ds5uHt42DMzI6iClyCAQnm11nVCNmM2ttR1adnS600wQIE5FUBly5qrt9dQAdCdn0JcQlYdHs5zyTheZxTVbmt7l9gD8_nJ3tN_H4PsAYJYbqstPd5BAwMgAD6YwHIh4pMCTD7TeGInZ3KCo9FEo60mYReZosCQGi2XG7B5M2F0o6LZbk4FM_YhEBhYARIYHHk82bzdLcJwoNlMlkg0TcCxgAAWwGIVj80rpsowcnu3Aw8gsAHJkABaZBW6oFIrVK1C-WKx3ID0QfXEw3IKDo36RH0GgMw_1MQI80kWJEcykEmkB2UYgks_YJin3AncgN8laJ3Po4WhcKRCw-8wudxeEApgPMY2m82Wm32r3Ot4Ogne0SK5BUL0-v1N6YZ6Bq7ga7W66qj8OGyM8mPMfzIHgpKV0uQYnqGST8NnwbgpJdHPfIUrUAG18aRNnZ4FhoI8wsClFCk_l8WVxvSnGACEB59BAvAAU2bBDjqxACHBVAYLImgoKSoFGDQWpwHBxDAKom4wDAahgMQ1SJE4-5gFacFYJgiSXMoiQkBingoAgcCRLwGBRoBCIWOh_SQeOTA3kG-wCVO7EzpqsFjsJyBrsJEnHkOUCKheq5vqmDImhAZoWtadoOk6hQ9m6pY-l6om-hpdJBmAIbXloEC2dGrkCHxz4op45BgK8Qm0h-QIon2P6ihWljVqMdYTDuSl8SBIBCL0RgQXF8lMNBxCuBQAhJQYfSaH-16gEgJX4RAhHEXBcBBiAVoYrRORQNwyjEE4WBYNQkD8BxeCeHAeA8U2yn7GU6nDXSgSTbS0EeJA5gACoAMrIJ4QhahgFHIAABk4KREJwiwAGLUAAwtw2HEMdXB8MQO1rcAM6qWCaI0LwvygPI9JzONYTUDNRzQaS2ooJwPD8FhcGqPATjcBiPqA9MLZ6W2hmdiZLq9hZA4oMOC643JwnWfsr5NiuU0fNN0z2Y5QV4lAfjTSKYoShgyRpK8mq1Uy5h9dUTVbHgADSEB4CUZRfdUXnUIMTS5EWFJWHzIDKFMeh8fgOAYAigu5KLyi2EbDouDDoDgTaABkltDng2sIjLrLG1apuVebvBWgFrDsAARFEGCqFAIA-zU6gXFoOgyjprYGVaAAC7MpFA6T_F6flQEy9xxHgrp2I4Xou7hFTRAH0CcWoGgR57-a0rTQfpTyOUgLw5h--im28D7UIBtn5jp5n2fd4aWCXUgRTgK39Zd4DjvmDEcRJEnKdZJsuTcxn6JZ2L1T95vjs7zzm8SVAVhD0cFPRpuZ6oZrdsQDr7IUsgQHO67R0W170E-3IigIHgIeqDDpoagpFkCLTvstZEodK4gOkDQIo2oA4C1Xi0LgkcjTR1RrHBOHNk6vC9HrFoItt4OjzsZE2Rdvo_yUNA8OICvSOz9DxOukR54JFwcvCA8siEWEIfgA20tPxdEfsCY-RMFJX23OrWa7BwE4EgbsWhwDtBwI4LdXg6DaQo30u2HBS98HIOavwkhNoRgF32l9MBECoGAJgdoauWla7BnrmwxenN_jcPwLwlBxic4NzpE8c4rw-5qTeIDUE4JgmqUVGfHkPkhBRPGmE1c4jAjTQQJdYgcFTpIWkcgPR7i5AfCiHgG6EMJblG-myK0oErQ13yYnQpEBil4AALLtwDtYOgClHHIAAPolKaPsAAjBeApeD_gfCFIMzYXTaCBmcZEOcxB7gDLwE0HwPSJylhmdgKsuNzCnCiExE-3TlmrN2VgUmuNNlpKCGmaQSE2R8mQDk6wfhtFo3MsySxJSyl8AcTADAGB7h_PUbCT5scMy_NKeowFwLQWwohvsH26gMA5RID7CFmCdHWikmIYuJT2mII9n6IFIKiUdN4O8-5OKvkqhhU0eFFL1mbGxXMXSuLqLomEIS1l2BmWIqGWyAALAAJh8EAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2017%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.8.4&externalPlugins=)

**Comment by justinfagnani** [comment] 2020-10-08 16:24
Ay updates here? We're increasingly seeing users complain that their components are broken because of this issue, and the symptom is very hard to track back to this unless you already know about it.

For some reason many tools that integrate the TypeScript compiler are enabling `useDefineForClassFields` and some of them don't give users control of the config, so there's no good workaround (except to delete own properties which puts objects into dictionary mode).

**Comment by brandon-marginalunit** [comment] 2020-10-20 22:02
We're still seeing this in TypeScript 4.0.3. It breaks the Aurelia framework, which is blocking us from using a library that requires `useDefineForClassFields`.

**Comment by Haprog** [comment] 2020-11-10 14:55
I just ran into this because this seems to mean that it's not possible to use [MobX decorators](https://mobx.js.org/enabling-decorators.html#typescript) and lit-element decorators together with TypeScript. MobX decorators seem to require `"useDefineForClassFields": true` but that breaks lit-element decorators (like `@property` and `@query`).

**Comment by rbuckton** [comment] 2020-12-16 02:07
This isn't a bug, but rather the expected behavior. It is unfortunate, but is a consequence of several interactions:

1. `--useDefineForClassFields` mimics the proposed behavior of ECMAScript fields.
2. The proposed behavior for ECMAScript fields is that they are _defined_ in the constructor (i.e., using `Object.defineProperty`).
3. _Defining_ a field on an instance means that a prototype walk will not occur, so the `get`/`set` you are defining on the `prototype` will never occur.
4. _Defining_ a field does not trigger setters.
5. Even declaring a field like `myProp: string;` with `--useDefineForClassFields` will result in a new field definition on the instance that will shadow the prototype.

We introduced `declare` fields in TS specifically for this reason:

```ts
function Decorator() {
    return function (target, propKey, descriptor) {
        const symbol = Symbol();
        target.constructor.prototype[symbol] = descriptor ? typeof descriptor.initializer !== 'undefined' ? descriptor.initializer() : undefined : undefined;
        return {
            configurable: true,
            enumerable: true,
            set(value) {
                this[symbol] = value;
            },
            get() {
                return this[symbol] + 'decorated';
            }
        }
    }
}

class TestTSDefine {
    @Decorator()
    declare myProp: string; // does not result in redefinition
//  ^^^^^^^
    constructor() {
        this.myProp = "test"; // initializer must be moved to constructor
    };
}

console.log(new TestTSDefine().myProp);
```

[Playground Link](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=1&module=1&ts=4.1.2#code/GYVwdgxgLglg9mABAEQKYTgJwIZSwCgEpEBvAWAChFrFNUoRMlRJYFF8ptMBzegGkQAHTHCEBpVAE9BAE1QBnCJhhC8mYuSo0dGMAqiIFUgLYAjOABtEAXkQBlUxctEA3JR06uvegDo9Bpgg0Fi+InB4UFJCqADaxuZWALq2iPJKKmpYiAD8iFExcMBpisqq6r4wYDCw2JYwAF6omIgAhDZ2AOTg8sBVqLKduSUZ5aFVNTB1jc1EiABciD2ofWADC0tgvf2y7tqetPSMSFoHB3p9PIzYZpaoi1BBqPweZzqoYCAmzTd3D08vfZvIz0fAANzqIFQmlewM8UAAFjAFPEnMlUhDLFC9nDqABfQG4xB8KBzU5Emh0BhMfJIlEJZwpADUiE68gwOCgA06ONxeNhnn5QKFQsoEEs2AUCkQABVFFAZfY0KtUKQBQABNAc3AEQgC9kSuiIExSAAKoiEi0CVR4vOoAUewXUZIFXjpvhN5rEqQARFyDD67Yg8XtRRQAlZUL5LHAePg1gB3WXyxXK-pED1mi2EVxAA)

**Comment by rbuckton** [comment] 2020-12-16 02:21
Babel's decorators support permits two things TypeScript never has: 
1. Decorating a "descriptor" for a field.
2. A decorator can intercept the `initializer` of a field descriptor.

These were part of an early draft for stage-2 decorators that has since been abandoned. Implementing this would be a major change for TypeScript decorators, a feature which is essentially "frozen" until a stable decorators proposal reaches Stage 3 in TC39.

Changing the behavior of decorators is out of scope, and changing the field definition semantics in `--useDefineForClassFields` to be incompatible with the ECMAScript fields proposal is also out of scope. 

Until a stable decorators proposal reaches consensus, we don't intend to make any substantial changes to our decorators implementation. It may not be much, but we added `declare` fields as an alternative to further complicating the decorator landscape.

**Closed by rbuckton** 2020-12-16 02:21 UTC
Labels: Bug, Domain: JS Emit, Rescheduled, Working as Intended

**Comment by justinfagnani** [comment] 2020-12-16 02:30
The problem here is that some toolchains set this compiler flag and it breaks existing decorator usage. Previously, decorators could assume that they could define accessors and they would work. I think it would be reasonable to automatically use set semantics for decorated fields to keep them working even in the presence of this flag.
