### ISSUE TITLE
satisfies operator breaks with callback on Partial object literals

### ISSUE THREAD

**Issue by JDMathew** [microsoft/TypeScript#55803] opened 2023-09-20 21:14 UTC
### 🔎 Search Terms

"satisfies", "callback", "function"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (above 4.8), and I reviewed the FAQ for entries about "Bugs that Aren't Bugs"

### ⏯ Playground Link

Link to [playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggrsAFgZWAQ2NAvFA3gKCigEsBnAGQHs0ATYgOwHMAuKAI0soBsI16BuQiQqVGjCDQCS9Vh268BQuKQgAnACqUA1hBlRSwVQ0ZQAPlHpwuXQQF9B+UJFgBjYMUr0AYnHpuP9FA4ABRoqixQfCAAlEEAfHhCThCsBkZMgkRgaCBc1DSsAAqqEMDuAGYgADyFYe5oXFXwSKgYEHFxdg4QAB5glKrAUC6eBpEIiDD+o0GJRKTEjPQA8giswbFYCcEERETJrGjT9OrgEKQAdMiSAOIAcgD6ywCq6gA0Qlk5ebSsuFDKNSaHR6SzWN7CKhiCTSVjlBoqKC2D5EWzRFFQPKMBjrf6AjTaXRIv4AlQEkGpQzGJGbba7PYHSLHU6QS7kZY3SR3DFfXL5En44G6CFkKHiKR6QxwaDIoRojElAwDCBCvQ7UlAwmBWwCsmqynpExo+JQHafKCMgBMlohAHpbVA1KoBlBPBazlByi7rawWdAAOSWAC2bDU-uEFkoQzQpAWSzQbB4Fso7uc-rSxn9F3N2T5vzwGvJwsh+WMcIREAh9CjMAAag1iDQANIQECsf31rjS8PIqD2yOO1TO1SuwLV4AwFsgCGkRCUKw0QfDqDLNgAKwgbkxxEwqgaUCDOVHXBA+kgLmIlSgWmrAHdAmBnZBBsRzhC+IvAzWp+GaJRzpGQy9GQQwMKmAa1C+DRNBMrSYHE-pyui+C2PoGBkOUr6kFAABKm4DDQVQZkwEJTO4ng+H45H0J0+D4L0-SDMMozRscsz0jobZzHsoqiOKsIWqo0o8oBk6tu2nbdhisqoaQ6GkJhAF4SMqiEcRjAQpB9SNM0KDoPBnRAA)

### 💻 Code

```ts
type AuthState = {
  isLoading: boolean;
  isLoggedIn: boolean;
  userToken: string | null;
};

type ActionFunction = (arg: any) => {
  type: string;
  payload: Prettify<Partial<AuthState>>;
};

export const authActions = {
  signOut: () => ({
    type: actionTypes.SIGN_OUT,
    payload: { userToken: null, isLoggedIn: false },
  }),
  login: ({ userToken }: { userToken: string }) => ({
    type: actionTypes.LOGIN,
    payload: { userToken, isLoggedIn: true },
  }),
  restoreToken: ({ userToken }: { userToken: string }) => ({
    type: 22, // error on type for 22: Type 'number' is not assignable to type 'string'.
    payload: { userToken, isLoading: false, notAValidKey: 'Value' }, // no error on notAValidKey, should error Object literal may only specify known properties, and 'notAValidKey' does not exist in type 'Partial<AuthState>'
  }),
} satisfies Record<string, ActionFunction>;
```

### 🙁 Actual behavior

There is no error thrown on `payload` for the key `notAValidKey` as one would expect since this key isn't inside the Partial type `AuthState`. There is an error thrown for `type` with value `22` so the callback type `ActionFunction` isn't breaking the satisfies operator.

### 🙂 Expected behavior

This should throw an error on `restoreToken` in the above `authActions` const. 
The behaviour should mimic what happens when there is no callback in the object. For example as it errors here: 
```ts
type AuthState = {
  isLoading: boolean;
  isLoggedIn: boolean;
  userToken: string | null;
};


export const action = {
  key: {
    isLoggedIn: true,
    notAValidKey: 'Value', // error thrown: Object literal may only specify known properties, and 'notAValidKey' does not exist in type 'Partial<AuthState>'.
  },
} satisfies Record<string, Partial<AuthState>>;
```

**Comment by fatcerberus** [comment] 2023-09-20 21:33
Functions aren’t contextually typed in their return type afaik so EPC doesn’t apply.  Note that the excess property check is more of a built-in lint rule than a type check, so it’s intentionally not comprehensive.

**Comment by fatcerberus** [comment] 2023-09-20 22:34
Simplified repro ([Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggrsAFgZWAQ2NAvFA3gKCigEsBnAGQHs0ATYgOwHMAuKAI0soBsI16BuQiQqVGjCDQCS9Vh268BQuKQgAnACqUA1hBlRSwVQ0ZQAPlHpwuXQQF9B+UJFgBjYMUr0AYnHpuP9FA4ABRoqixQfCAAlEEAfHhCThCsBkZMgkRgaCBc1DSsAAph7mhcADzwSKgYEHF2Di6eBpH+nkFQwcG4UMpqmjqBtqw9fRrauqmGxlC2sVgJ3UJEyawARABmvmsANMtQ2bn5I70q44M7wlS0xqwbZSqX9JTAMABqZcQ0ANIQIKwAcg+XDgEABsz2c1ipAwZA2xAgpFc7k8Pj8KMUQA)):

```ts
type AuthState = {
  isLoading: boolean;
  isLoggedIn: boolean;
  userToken: string | null;
};

type ActionFunction = (arg: any) => {
  type: string;
  payload: Partial<AuthState>;
};

const action1 = (({ userToken }: { userToken: string }) => ({
    type: "fun",
    payload: { userToken, isLoading: false, notAValidKey: 'Value' },
})) satisfies ActionFunction;  // no EPC error

const action2: ActionFunction = (({ userToken }: { userToken: string }) => ({
    type: "fun",
    payload: { userToken, isLoading: false, notAValidKey: 'Value' },
}));  // also no EPC error
```

which I'm almost positive is a duplicate of like 10 other issues.  tl;dr you shouldn't rely on the excess property check to enforce runtime invariants - you need #12936 for that.

**Comment by fatcerberus** [comment] 2023-09-21 00:07
The closest thing to a canonical duplicate afaict is https://github.com/microsoft/TypeScript/issues/7547

**Comment by RyanCavanaugh** [comment] 2023-09-26 16:25
#241 is also relevant

**Closed** 2023-09-29 01:25 UTC
Labels: Not a Defect
