### ISSUE TITLE
Proposal: Revoke types narrow-downs/guards on object properties for the rest of the block after function call

### ISSUE THREAD

**Issue by Bnaya** [Microsoft/TypeScript#19715] opened 2017-11-03 15:16 UTC
I couldn't find a better title, you are welcome to edit it for a better one :) 

Given this code:
```ts
const tree: {
  branch: "banana" | undefined,
  pick(): void
} = {
    branch: "banana",
    pick() {
      this.branch = undefined;
    }
};

function climb() {
  if (tree.branch) {
    const { branch } = tree;

    tree.pick();
     // this will work
    branch.toString();

    // this will throw
    // Uncaught TypeError: Cannot read property 'toString' of undefined
    // But ts typecheck strict null check won't catch it
    // If you revoke the narrow downs the checker would can't it 
    tree.branch.toString();
  }
}

climb();
```
The expression 
```ts 
 tree.branch.toString(); 
```
Typescript compiler with strictNullCheck, won't report any error, but it will throw runtime error, because the code in `tree.pick()`changed it to another possible type.

It doesn't have to be null/undefined, but any types narrow-downs. 

We could make the type checker more robust and to catch more possible  runtime errors by revoking any type narrow-down on object props, forcing the developer the handle the possibility the function call changed the type

**Comment by andy-ms** [comment] 2017-11-03 15:21
So basically:
```ts
const obj: { x?: number } = { x: 0 };
if (obj.x !== undefined) {
    evil();
    obj.x.toString(); // Should we allow this?
}

function evil() {
    obj.x = undefined;
}
```

Looks like a duplicate of #9998.

**Comment by Bnaya** [comment] 2017-11-03 15:22
Seems so,
Thanks!

**Closed** 2017-11-03 15:22 UTC
Labels: Duplicate
