### ISSUE TITLE
`instanceof` refuse to accept mutable variable with broken type deduction

### ISSUE THREAD

**Issue by hopeless-programmer-online** [microsoft/TypeScript#42571] opened 2021-01-31 22:21 UTC
# Bug Report

### 🔎 Search Terms

- `instanceof` + `let` + `never`
- broken type deduction for mutable variables

### 🕗 Version & Regression Information

- Version 3.9.5

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210131#code/MYGwhgzhAEAa0G8C+AoUkYE1GpSApgC7TEBcc0APtNgLzQB2+A7nCigGYCuDwhAlgHsG0DgAoAlIhTRZJaPSatMKXPw7QxxfgwiEwvfII2wpCGXPET2c6Os3bd+w8bhnUt-CAj47GrXZOBsBGGpjuqihAA)

### 💻 Code

```ts
class X {}
class Y {}

let t : X | Y = new X

function f() {
    t = new Y
}

if (t instanceof X) {
    f()

    if (t instanceof X) {}
    else if (t instanceof Y) {}
}
```

### 🙁 Actual behavior

`t instanceof Y` refuse to compile as `t` has type `never`.
I believe this happens because first `if` constrain the possible type of `t` to `X` and for some reason typescript can't see that call to `f` actually mutates the variable.
So after a second check for `instanceof X` variable `t` is constrained to `never` type and `instanceof` refuses to work on it.

### 🙂 Expected behavior

I believe the `t instanceof Y` should work in this case.

**Comment by MartinJohns** [comment] 2021-02-01 02:21
Duplicate of #9998.

**Closed** 2021-02-04 18:00 UTC
Labels: Duplicate
