### ISSUE TITLE
Can't use list export for interfaces with --declaration

### ISSUE THREAD

**Issue by Avol-V** [Microsoft/TypeScript#15120] opened 2017-04-11 10:56 UTC
**TypeScript Version:**  2.2.2

**Code**

```ts
function main( options: Options )
{
	console.log( options );
}

interface Options
{
	option: string;
}

export {
	main as default,
	Options,
};
```

```json
{
	"compilerOptions": {
		"target": "es2015",
		"declaration": true
	},
	"files": [
		"index.ts"
	]
}
```

**Expected behavior:**

It should compile without errors.

**Actual behavior:**

```
index.ts(1,25): error TS4078: Parameter 'options' of exported function has or is using private name 'Options'.
```

But all works with this change:

```ts
function main( options: Options )
{
	console.log( options );
}

export interface Options
{
	option: string;
}

export {
	main as default,
};
```

It's the same code, but TypeScript can't recognise export of the interface in list. I want to see module interface in one place and I prefer to use list export.

**Comment by mhegazy** [comment] 2017-04-19 18:34
Duplicate of https://github.com/Microsoft/TypeScript/issues/14753

**Closed** 2017-04-21 16:59 UTC
Labels: Duplicate
