### ISSUE TITLE
Declaration merging conflicts when using export statement

### ISSUE THREAD

**Issue by aleung** [Microsoft/TypeScript#9639] opened 2016-07-12 10:47 UTC
**TypeScript Version:**  1.8.10 & 2.0.0@beta

I follow the example in [Module Augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) and write below code. The only different is that I use export statement in `someclass.ts`.

```ts
// someclass.ts
class SomeClass {
}
export {SomeClass}

// augmented.ts
import { SomeClass } from "./someclass";
declare module "./someclass" {
  interface SomeClass {
    hello(): void;
  }
}
SomeClass.prototype.hello = function() {
  return this;
}

// consumer.ts
import { SomeClass } from "./someclass";
import "./augmented";
new SomeClass().hello();
```

It gives compile error:

> augmented.ts(7,1): error TS2304: Cannot find name 'SomeClass'.
> consumer.ts(3,5): error TS2304: Cannot find name 'SomeClass'.
> someclass.ts(6,1): error TS2484: Export declaration conflicts with exported declaration of 'SomeClass'

I change back `someclass.ts` to use declaration export, then compile success.

```ts
// someclass.ts
export class SomeClass {
}
```

Suppose two export forms should behave the same. Is it a bug?

**Comment by mhegazy** [comment] 2016-09-22 04:56
Duplicate of https://github.com/Microsoft/TypeScript/issues/9127

**Closed by mhegazy** 2016-09-22 04:56 UTC
Labels: Bug
