### ISSUE TITLE
Nested Omit type with same constraints incompatible.

### ISSUE THREAD

**Issue by Chr15t0pher** [microsoft/TypeScript#54508] opened 2023-06-03 07:09 UTC
# Bug Report

### 🔎 Search Terms

nested Omit, util type

### 🕗 Version & Regression Information

* This is the behavior in every version i tried on the typescriptlang playground.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.0.5#code/JYOwLgpgTgZghgYwgAgKIA8D2ZgOQbwChllgATALmQGcwpQBzQgX0MLAE8AHFAdWDAALTAFcwGbLgA8ABWQR0kEGWrIAShASYoZKbXogGAGmQiQAaxCYA7iAB8yALwFmD5wHkAtgNkmA5OR+dmycPMj8QhI4CLLyihDKqhpaOnp0jCZmljb2Ti5u4QLCYlHSMg4AZGhY0WyEMGYIOJggyDAgsQpKKuqa2rr6GaYWVrZ2dgAUcFAM1FQRgqUx5QCU80Wi4jVldkQkWiC0BKRkJgB0F1AQtMx507PEyFdgIlCtV7QsQA)

### 💻 Code

```ts
interface Exotic {
  id: string
}

type WithoutExotic<P extends Record<string, unknown> = {}> = Omit<P, 'id'>

type WithExotic<P extends Record<string, unknown> = {}> = WithoutExotic<P> & Exotic

function fn<P extends Record<string, unknown>>(args: WithExotic<P>): WithoutExotic<P>{
  const { id, ...rest} = args
  return rest    // errors, not assignable
}
```

### 🙁 Actual behavior

Error occurs at line 12. First line in error message says `Type 'Omit<WithExotic<P>, "id">' is not assignable to type 'WithoutExotic<P>'.`, however, second line shows `Type 'Exclude<keyof P, "id">' is not assignable to type 'Exclude<Exclude<keyof P, "id">, "id">'.`,  the assignment direction described is reverse.

```bash
Type 'Omit<WithExotic<P>, "id">' is not assignable to type 'WithoutExotic<P>'.
  Type 'Exclude<keyof P, "id">' is not assignable to type 'Exclude<Exclude<keyof P, "id">, "id">'.
    Type 'keyof P' is not assignable to type 'Exclude<Exclude<keyof P, "id">, "id">'.
      Type 'string | number | symbol' is not assignable to type 'Exclude<Exclude<keyof P, "id">, "id">'.
        Type 'string' is not assignable to type 'Exclude<Exclude<keyof P, "id">, "id">'.
          Type 'keyof P' is not assignable to type 'Exclude<keyof P, "id">'.
```

### 🙂 Expected behavior

* There should be no error. `Omit<WithExotic<P>, "id">` is assignable to type `WithoutExotic<P>`. Because `Omit<Omit<P, K>, K>`  is equivalent to `Omit<P, K>` when P and K stay the same.
* Better error messages. The assignment direction of first two error messages is reverse, it should not happened in typescript which allow variance.

**Comment by jcalz** [comment] 2023-06-03 19:19
Duplicate of #37768 which is listed as a bug, but I wonder if this isn't more of a design limitation.  See #43846 for a similar issue classified as a design limitation and #28884 for one classified as a feature request.  So who knows how this will go?

The underlying issue for all of these is that TS can't really infer very much about conditional types that depend on generic type parameters, even in some situations where it seems obvious to a human developer.  The human developer has the potential to reason abstractly and to understanding the meaning of words like "`Exclude`" and "`Omit`", whereas the compiler has to make do with mindlessly applying a heuristic algorithm whose design is subject to performance constraints.

**Closed** 2023-06-15 01:32 UTC
Labels: Duplicate
