### ISSUE TITLE
Add unsafe sub- type definitions

### ISSUE THREAD

**Issue by fgarcia** [Microsoft/TypeScript#23600] opened 2018-04-21 05:53 UTC
**TypeScript Version**: 2.8.3

**Search Terms**:
 - explicit cast
 - require cast
 - unsafe type

**Code**

```
function queryOutsideWorld(queryName) : unsafe {
   // ... some fetch() or RPC call
  // ... some JSON.parse()
  // ... extract body with random interface
  return someRandomData
}

// fail
let data = queryOutsideWorld('user-profile')

// ok
let data: UserProfile = queryOutsideWorld('user-profile')
```

**Related Issues**:

#10715
#22716
#9999

I've read similar issues and the closest one is the `unknown` type #10715. However I believe there is room for a less complex solution.

Currently if I fetch something from the outside world I must do some kind of runtime validation and cast to a known type / interface. If I start looking for common functionality I will be forced to create functions and even libraries that must return `any` but I would like a way return a value and force the programmer to do an explicit cast. 

In my example I've used a new type keyword as a basic example, but I would rather like to have something where I can define unsafe subtypes such has:

```
// global.d.ts
type Unsafe extends any as unsafe
type RiskyAny extends any;

if (process.env.NODE_ENV === 'production') {
  type RiskyAny extends any as unsafe;
}
```

This would enable a second case. I want to prototype code/ideas in a non very strict environment, and only increase the typing-strictness later, if/when the library "matures". There is code that is OK to have type `any` in development, but in production (or at a more mature version) it will have to go away before other `any` types

**Comment by mhegazy** [comment] 2018-04-21 19:39
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/10715

**Closed** 2018-05-08 15:33 UTC
Labels: Duplicate
