### ISSUE TITLE
Incorrect type declaration emitted for object with numeric string keys

### ISSUE THREAD

**Issue by kazushisan** [microsoft/TypeScript#55292] opened 2023-08-07 11:17 UTC
### 🔎 Search Terms

numeric string key object

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ 

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAygFQIIIKpxgXhgbwFAyEwDaARACwAM5pAugFwylgiwBmIArmACal4BfGAEMIMUJCgBuPHigBPAA4BTeFGFROY7AGtl8kGxgKVh+MjRwgA

### 💻 Code

```typescript
const STATUS = {
    ["404"]: "not found"
} as const;

type Status = keyof typeof STATUS;
```

### 🙁 Actual behavior

the type of `Status` will be the following.

```typescript
type Status = "404"
```

however when I create a .d.ts file, the type of `Status` will not be the same. This is caused by the incorrect `declare const` in the declaration file that changes the numeric string keys to a number.

```typescript
type Status = 404
```

### 🙂 Expected behavior

Given the example source code, the type for `Status` when referring to the declaration file will be the same as in the source code.

```typescript
type Status = "404"
```

Note: this issue does not reproduce if the numeric string key used in the object is not a variable.

```typescript
const STATUS = {
    "404": "not found"
} as const;

type Status = keyof typeof STATUS;
// type Status = "404"
// the result will be the same for both the source file and the type declaration file
```

**Comment by MartinJohns** [comment] 2023-08-07 13:56
Duplicate of #50358. Used search terms: `number string declaration in:title`

**Closed** 2023-08-14 20:13 UTC
Labels: Bug, Help Wanted
