### ISSUE TITLE
Invalid file emmited when a file ends with a multiline comment

### ISSUE THREAD

**Issue by alonweiss** [Microsoft/TypeScript#2366] opened 2015-03-15 17:04 UTC
The compiler emits invalid JS code a .TS file ends with a multi-line comment.

The following file will not be generated correctly
```
module Module1
{
    class Class1
    {
    
    }
}
/*This is a multiline comment*/
```

This can be resolved by adding a trailing line break.

Another form of the issue:
```
module Module1
{
    class Class1
    {
    
    }
}
/*This is a 
multiline comment*/
```

(Using TSC Version 1.4.0.0)

**Comment by mhegazy** [comment] 2015-03-15 18:52
Looks like a dupe of #1714

**Closed** 2015-03-16 19:49 UTC
