### ISSUE TITLE
Add support for generic types on a index accessor

### ISSUE THREAD

**Issue by ruochenjia** [microsoft/TypeScript#58258] opened 2024-04-19 21:11 UTC
### 🔍 Search Terms

index accessor
generic index accessor

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Allow type parameters to be used for an index accessor. This allows users to declare additional supporting methods within an interface that has a string index accessor with a value set to a non `any` or `Function` type, by using an overlay interface.

Example:
```typescript
interface SuperRecord<Key extends keyof any, Value, Overlay = {}>{
	<E extends Key>[k: E]: E extends keyof Overlay ? Overlay[E]: Value;
};
interface K extends SuperRecord<string, string, { func1: () => void; }> {
	// Properties declared through the `SuperRecord` interface.
	// [k: string not "func1"]: string;
	// func1(): void;
}

let d: K = ...

d["anystringkey"] = "anystringvalue"; // properties not whitelisted in the overlay have the same behavior as a `Record<string, string>` interface type in this case.

d.func1(); // properties whitelisted by the overlay uses the value declared in the whitelist.

d.func1 = "A"; // error, as 'func1' exists in the overlay, so its corresponding type takes the priority.

```

### 📃 Motivating Example

This fixes #58256 and #17867, without using an intersection type. This would allow the type to be declared as an `interface`, which means it can be implemented by a `class` or extended by another `interface` without any errors caused by conflicting properties.

### 💻 Use Cases

1. What do you want to use this for?
Various cases where an interface requires both an index accessor and other properties that could cause conflict in the type.
Furthermore some types in `lib.dom.d.ts` can be improved, for example a `string` valued index accessor can be used for the `Storage` interface without affecting other supporting functions.

3. What shortcomings exist with current approaches?
It might slow down the type checking process.

5. What workarounds are you using in the meantime?
An intersection type like this:
```typescript
type E = { [k: string]: string; } & { func1(): void };
```
which cannot be extended by an interface, or implemented by a class, due to property type conflicts.

**Comment by RyanCavanaugh** [comment] 2024-04-19 21:32
This seems like just an exact duplicate of #17867.

You can already write
```ts
type SuperRecord<Key extends keyof any, Value, Overlay = {}> = {
    [E in Key]: E extends keyof Overlay ? Overlay[E]: Value;
};
```
to get the generic behavior on an index signature's output type, nothing new is needed.

**Comment by RyanCavanaugh** [comment] 2024-04-22 22:22
Right, you'd still need rest signatures. But `K` would be declared as this:
```ts
type O = { func1(): void; };
interface K extends SuperRecord<keyof O, string, O> {
  // TODO: Be able to uncomment.
  // [...rest: string]: string
}
```

**Closed** 2024-04-25 01:28 UTC
Labels: Duplicate
