### ISSUE TITLE
type guard with array element

### ISSUE THREAD

**Issue by Kingwl** [Microsoft/TypeScript#25219] opened 2018-06-26 08:14 UTC
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 
type guard, array, strict, undefined
**Code**

```ts
const foo: (number | undefined)[] = []

foo[0] && foo[0].toFixed // error

const one = foo[0]
one && one.toFixed()
```

**Expected behavior:**

`foo[0] && foo[0].toFixed` is ok

**Actual behavior:**

`Object is possibly 'undefined'.`

**Playground Link:**  

https://www.typescriptlang.org/play/index.html#src=const%20foo%3A%20(number%20%7C%20undefined)%5B%5D%20%3D%20%5B%5D%0A%0Afoo%5B0%5D%20%26%26%20foo%5B0%5D.toFixed%0A%0Aconst%20one%20%3D%20foo%5B0%5D%0Aone%20%26%26%20one.toFixed()

**Related Issues:**

**Comment by jcalz** [comment] 2018-06-26 16:12
Duplicate of #10530 ?

**Comment by RyanCavanaugh** [comment] 2018-06-26 16:29
Soooooo many duplicates

**Closed** 2018-06-26 21:59 UTC
Labels: Duplicate
