### ISSUE TITLE
Forced to pass `undefined` when a method accepts `void` or `undefined`

### ISSUE THREAD

**Issue by inad9300** [Microsoft/TypeScript#19259] opened 2017-10-17 20:37 UTC
If a method accepts `void` as the type of one of its arguments, passing `undefined` to it should not be explicitly required, in my opinion, as the method will receive `undefined` anyway if no argument is provided.

My use case is as follows:

```typescript
class C<T> {

    f(a: T) {}
}

const c = new C<void>() // Or: new C<undefined>()
c.f(undefined) // OK.
c.f() // Expected 1 arguments, but got 0.
```

Might be an uncommon case, but what I would like to effectively indicate from the the user of class `C` is the need or not to provide the argument `a`. In other words, the method `f()` of `C` should force you to send an argument to it if the type is different than `void` (so an optional argument doesn't work, unless there is a way to condition this to the argument type), but also allow you to say "I don't need an argument in `f()`" (and using a default type, e.g. `any` wouldn't be very type-safe, of course, so I would like to avoid this option).

What is the best possible way to achieve this for the time being? If none, does my proposal make sense?

**Comment by mhegazy** [comment] 2017-10-17 23:50
I think `void` here is the wrong type. only use `void` in return type positions for functions to indicate the lack of a return value.

I think there is merit in general in allowing parameters that accept `undefined` to be skipped in a call under `--strictNullChecks`, in other words, treat `f(a: number|undefined)` as `f(a?: number)`.

**Comment by inad9300** [comment] 2017-10-18 06:20
I think you expressed it perfectly; that's it: `T | undefined` should be semantically equivalent to `T?`. And probably, if not under strict mode, `T | undefined | null` should be equivalent to `T?`.

**Comment by mhegazy** [comment] 2017-10-18 06:59
No just T|undefined. Null has a different value.

**Comment by inad9300** [comment] 2017-10-18 16:56
Well, you are the expert :)

**Comment by mhegazy** [comment] 2017-10-20 21:16
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/12400

**Comment by inad9300** [comment] 2017-10-22 18:34
So it seems indeed.

**Comment by mhegazy** [comment] 2017-11-06 16:51
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-11-06 16:51 UTC
Labels: Duplicate
