### ISSUE TITLE
I can't use interface with key value pair

### ISSUE THREAD

**Issue by GrayAi0** [microsoft/TypeScript#45732] opened 2021-09-05 13:16 UTC
# Bug Report

### 🕗 Version & Regression Information

- This is a crash: no
- I'm running in typescript 4.4.2 and Node.js v14.17.6

### 💻 Code
I write this code to save data to storage
```ts
// index.ts

type NativeSaveableTypes = string | number | boolean | null | undefined | string[] | number[] | boolean[] | null[] | undefined[];
interface ObjectPair { 
    [key: string]: string | NativeSaveableTypes | ObjectPair | ObjectPair[]
}

export default class StorageManager<D extends ObjectPair> {
    // ...
}

// code1.ts
interface Product {
    name: string;
    //...
}

const ProductsStorage = new StorageManager<{ products: Product[] }>('products', { products: [] })

// code2.ts

const ProductsStorage = new StorageManager<{ products: { name: string }[] }>('products', { products: [] })


```

### 🙁 Actual behavior

The code 1 is give me that error
![image](https://user-images.githubusercontent.com/48690308/132128155-e2242d08-e748-4931-8d0e-3c6f4245e83a.png)

But code 2 have no errors
![image](https://user-images.githubusercontent.com/48690308/132128175-d93db8f3-c49e-42ba-b8dc-060cec5948e6.png)

**Comment by jcalz** [comment] 2021-09-05 18:52
The code here does not reproduce the particular behavior you're describing, nor have you provided a playground link to it.  Images of errors are also not the best.  Maybe you could edit this to conform completely to the template?

**Comment by fatcerberus** [comment] 2021-09-05 19:22
I think, ultimately, this is just:
```ts
interface Foo { 
    [key: string]: string;
}

type Bar = { what: string };
interface Baz { what: string };

declare let foo: Foo;
declare const bar: Bar;
declare const baz: Baz;
foo = bar;  // ok, no error
foo = baz;  // error, index signature missing
```

**Comment by jcalz** [comment] 2021-09-05 19:29
That was my guess too, (which would make this a duplicate of#15300), but presumably a bug report should be self-contained enough so as not to require guesses about what's being reported.

**Comment by andrewbranch** [comment] 2021-09-07 19:37
If your question hasn’t already been answered by the discussion above, please open a new issue with a code sample that clearly demonstrates the problem in a playground.

**Closed by andrewbranch** 2021-09-07 19:37 UTC
Labels: Unactionable
