### ISSUE TITLE
first element of an array and shift function

### ISSUE THREAD

**Issue by myriamdb** [microsoft/TypeScript#52587] opened 2023-02-03 11:29 UTC
# Bug Report

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/LAKANgpgLgBADgQygCxgXhgbQOQOwGhmwCMCiBjM7AEyomwF1RQBLAMwAp4lkA6SAHYBzFDAB8MAEwwAZDO4pMABgbo0GAEQAxAPIAlALIBBACoaAlKADeoGAr4BnZOygdLIO+y6IU-CMNEJAEZ3OxsPOxgvH2RlVXUMGmxQyPDbSIBfdLsIMAcIbMiAJ2gAVyKBdIygA)

### 🙁 Actual behavior

function shift on array not toke in consideration

### 🙂 Expected behavior
first element of an arrayupdated  after a call to shift function

**Comment by MartinJohns** [comment] 2023-02-03 11:33
Duplicate of #33443. You forgot to fill out parts of the issue template.

**Closed** 2023-02-06 18:00 UTC
Labels: Duplicate
