### ISSUE TITLE
Add a warning when compile a class that extends another class which is not include 

### ISSUE THREAD

**Issue by ybootin** [Microsoft/TypeScript#2045] opened 2015-02-16 11:24 UTC
for exemple : 

   module mymodule {

    export class myclass extends anotherclass {

should throw a warning because another class is not referenced as this in the header : 

   `/// <reference path="./anotherclass.ts" />`

this cause in error in code, because extends class is not includes in base class at runtime : 

   `Uncaught TypeError: Cannot read property 'prototype' of undefined`

**Comment by RyanCavanaugh** [comment] 2015-02-16 16:01
Duplicate of #21

**Closed by RyanCavanaugh** 2015-02-16 16:01 UTC
Labels: Duplicate
