### ISSUE TITLE
auto import broken that import as a relative path

### ISSUE THREAD

**Issue by Kingwl** [Microsoft/TypeScript#25186] opened 2018-06-25 05:59 UTC
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 
import, auto import
**Code** 

```ts
// node_module/xxx/lib/index.d.ts
export declare a: number;

// src/a.ts
a/*here*/
```

**Expected behavior:**
insert the code: import { a } from 'xxx'
**Actual behavior:**
insert the code: import { a } from 'node_module/xxx/lib'

**Related Issues:** 

seems by https://github.com/Microsoft/TypeScript/issues/24742

**Comment by andy-ms** [comment] 2018-06-25 16:31
@Kingwl this seems to be working for me with `typescript@next`, with the caveat that I need `import {} from "xxx/lib";` in a different file or else the package is not included in the project and can't be auto-imported. But if so, I'll get an auto-import from `xxx/lib`. This is with an empty `tsconfig.json`.

**Comment by andy-ms** [comment] 2018-07-03 21:35
Duplicate of #25279. Wasn't showing up on my computer since it was a windows-only issue.

**Closed by andy-ms** 2018-07-03 21:35 UTC
Labels: Needs More Info
