### ISSUE TITLE
Decorators not working for class properties with union type

### ISSUE THREAD

**Issue by vuorinem** [Microsoft/TypeScript#15046] opened 2017-04-06 09:40 UTC
If one of the types in union type is an imported class (say _TestClass_), it does not get defined for the module. When a decorator is added for the property, TS calls `__metadata("design:type", test_class_1.TestClass)`, but `test_class_1` is undefined, causing runtime error.

If the class is used elsewhere within the module, it will get properly defined. So an easy workaround is to call `new TestClass()` somewhere.

**TypeScript Version:**  2.2.2

**Code**

```ts
import { TestClass } from "./test-class";

function myDecorator(target, key) {
    console.log("Decorate...");
}

export class Things {
    @myDecorator
    private thing: TestClass | null;
}
```

**Expected behavior:**
```
define(["require", "exports", "./test-class"], function (require, exports, test_class_1) {
    // ...
    __decorate([
        myDecorator,
        __metadata("design:type", test_class_1.TestClass)
    ], Things.prototype, "thing", void 0);
    exports.Things = Things;
});
```

**Actual behavior:**
```
define(["require", "exports"], function (require, exports) {
    // ...
    __decorate([
        myDecorator,
        __metadata("design:type", test_class_1.TestClass)
    ], Things.prototype, "thing", void 0);
    exports.Things = Things;
});
```

**Comment by aluanhaddad** [comment] 2017-04-07 05:25
Reproduced in latest nightly.
It simply blows up on the execution of the class declaration with a `ReferenceError` exception.

**Comment by mhegazy** [comment] 2017-04-27 16:39
Duplicate of #13449

**Closed by mhegazy** 2017-04-27 16:39 UTC
