### ISSUE TITLE
Array destructuring typing in generic callbacks

### ISSUE THREAD

**Issue by jamiewinder** [Microsoft/TypeScript#6225] opened 2015-12-23 14:56 UTC
```javascript
var a = [1, 'abc'] as [number, string];

var [b, c] = a;
[a].forEach(([d, e]) => {
    alert(d);
    alert(e);
});
```
There's something amiss with the typing in the above code snippet. TypeScript can figure out that `b` is a `number` and `c` is a `string`, it can even figure out that the `callbackFn` of my `forEach` is a `(value: [number, string], index: number, ...) => void`, but it says `d` and `e` are `any`. I'd have expected it to also know that these are `number` and `string` respectively.

**Comment by ahejlsberg** [comment] 2015-12-23 16:58
Which version of the compiler are you using? I'm seeing the expected result (`d` and `e` are `number` and `string`) with the compiler currently in master.

**Comment by vladima** [comment] 2015-12-23 17:11
looks like a duplicate of #4949 that should already be fixed in master

**Closed by vladima** 2015-12-23 17:11 UTC
Labels: Duplicate

**Comment by jamiewinder** [comment] 2015-12-23 17:13
I'll try the latest. I'm on the latest Visual Studio version (so 1.7.x I believe). Thanks!
