### ISSUE TITLE
type inferrence with override methods in child class

### ISSUE THREAD

**Issue by dislido** [microsoft/TypeScript#31470] opened 2019-05-20 03:48 UTC
## Use Cases
```typescript
interface TestProps {
  foo(num: number): number;
}
class Test extends React.Component<TestProps> {
  /**
   * sometimes we override functions and keep their parameters unchanged
   * in this case, the type of `nextProps` should be `Readonly<TestProps>` but inferred as `any`
   * we have to specify its type `nextProps: TestProps`
   * is there any way to tell typescript that we need to keep its parameters unchanged?
   * and typescript can find its type from the overridden function
   */
  componentWillReceiveProps(nextProps) {
    nextProps.foo(123);
  }
}
```
![image](https://user-images.githubusercontent.com/25094788/57995604-fb1ff180-7afd-11e9-92ef-2ac4efa14d38.png)
![image](https://user-images.githubusercontent.com/25094788/57995656-49cd8b80-7afe-11e9-92e2-74c55bc677c7.png)

## Examples
in parent classes
```typescript
interface TestProps {
  foo(num: number): number;
}
namespace React {
  class Component<T> {
    /**
     * Any function that override it will inferred as (T) => void by default 
     */
    [some keywords?] componentWillReceiveProps(nextProps: T);
  }
}
```

in child classes
```typescript
interface TestProps {
  foo(num: number): number;
}
class Test extends React.Component<TestProps> {

  /**
   * use (Readonly<P>) => void declared at React.Component
   */
  [some keywords?] componentWillReceiveProps(nextProps) {
    nextProps.foo(123);
  }
}
```

**Comment by jcalz** [comment] 2019-05-20 15:16
Duplicate of #1373

**Closed** 2019-05-20 21:04 UTC
Labels: Duplicate
