### ISSUE TITLE
Go-to-definition (F12 in Visual Studio) does not work for Mapped Types

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#13022] opened 2016-12-19 13:01 UTC
**TypeScript Version:**  2.1.4

**Code**

```ts
type Mapped<T> = {
     readonly[P in keyof T]: T[P];
};
    
interface Foo {
    foo: Mapped<{
        aaa: string;
        bbb: string;
    }>;
}

var x: Foo;
x.foo; // Okay: F12 works
x.foo.aaa; // Not okay: F12 does not work on `aaa`
```

**Expected behavior:**

Go-to-definition on `.aaa` in `x.foo.aaa` should navigate to that property.

**Actual behavior:**

Doesn't

**Further notes**
This is reproducible in the playground with `Control+F12`.

**Comment by NoelAbrahams** [comment] 2016-12-21 11:38
Bug/no bug/By design?

**Comment by RyanCavanaugh** [comment] 2016-12-21 20:24
🐛

**Comment by olmobrutall** [comment] 2017-01-29 19:05
Hi guys, 

Any roadmap for this bug? 

Since the type definitions for react have been updated https://github.com/DefinitelyTyped/DefinitelyTyped/commit/9b5329839558a78550bf078c3e5f323c2f0f3b86 Go To Definition fails very often.

**Comment by mhegazy** [comment] 2017-01-30 21:54
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/13690

**Comment by mhegazy** [comment] 2018-04-12 23:01
Should be fixed in latest.

**Closed by mhegazy** 2018-04-12 23:01 UTC
Labels: Bug, Fixed
