### ISSUE TITLE
Excessive stack depth comparing types with 2.7.1

### ISSUE THREAD

**Issue by adrianhara** [Microsoft/TypeScript#21671] opened 2018-02-06 10:54 UTC
I found this issue in the archives as already solved in 2.5. However it seems to appear again: https://github.com/typeorm/typeorm/issues/1544

Any suggestions?

**Comment by mhegazy** [comment] 2018-02-06 17:53
here is what i am seeing locally:

```sh
c:\test\21671\typeorm>git remote -v
origin  https://github.com/typeorm/typeorm.git (fetch)
origin  https://github.com/typeorm/typeorm.git (push)

c:\test\21671\typeorm>git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean

c:\test\21671\typeorm>tsc --v
Version 2.7.1

c:\test\21671\typeorm>tsc --diagnostics
Files:          1332
Lines:        117889
Nodes:        572747
Identifiers:  170270
Symbols:      844659
Types:         78716
Memory used: 379295K
I/O read:      0.21s
I/O write:     3.10s
Parse time:    2.87s
Bind time:     0.85s
Check time:   25.98s
Emit time:    10.41s
Total time:   40.11s
```

**Comment by daniel-lang** [comment] 2018-02-09 16:56
TypeORM users get the error:
```
Excessive stack depth comparing types 'Entity' and 'DeepPartial<Entity>'
```
where `DeepPartial` is defined as
```ts
export type DeepPartial<T> = {
    [P in keyof T]?: DeepPartial<T[P]>;
};
```
In TypeORM this is used to check if a given variable is part of the complete entity. At least that's how I understand it. Don't know if that's of any help to you @mhegazy

**Comment by mhegazy** [comment] 2018-02-09 17:07
do you have a sample i can look at?

**Comment by daniel-lang** [comment] 2018-02-09 17:54
[typeorm/typescript-example](https://github.com/typeorm/typescript-example) should give the error if you update it to typescript@2.7.1
`src/index.ts` should show the error when using TypeORM's `save()` method.

**Comment by jmlopez-rod** [comment] 2018-02-13 20:31
Glad I found this issue because I am able to reproduce something similar and I have no idea how some simple types provided by `@types/colors` is messing with my code. Here is how to I get the errors:

In a brand new project do

```
npm install typescript@2.7.1
``` 

Here is some code that works fine:

```typescript
// test.ts
type DeepPartial<T> = { [P in keyof T]?: DeepPartial<T[P]> };
type PayLoad<T> = DeepPartial<T> | DeepPartial<T>[];

interface ISimpleUser {
  id: number;
  firstName: string;
  lastName: string;
}

const payLoadObject:Partial<ISimpleUser> = { id: 0, firstName: 'Leo' };
const payLoadArray: Partial<ISimpleUser>[] = [
  { id: 0, firstName: 'Leo' },
  { id: 1, lastName: 'Austen' },
];

class Endpoint<C> {
  post<I = C, O = I>(customPath: string | number, body: PayLoad<I>): void;
  post(...args: any[]): void {
    console.log(args);
  }
}

const endpoint = new Endpoint();
endpoint.post('path', payLoadObject);
endpoint.post('path', payLoadArray);
endpoint.post('path', { id: 0, room: { id: 1, color: 'red' } });
```

Things work fine:

```
jmlopez in ~/typescript-debug$ tsc test.ts
```

That should give you no errors.

But as soon as we bring in some types:

```
jmlopez in ~/typescript-debug$ npm install @types/colors
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN typescript-debug@1.0.0 No description
npm WARN typescript-debug@1.0.0 No repository field.

+ @types/colors@1.1.3
added 1 package in 0.982s
jmlopez in ~/typescript-debug$ tsc test.ts
test.ts(24,23): error TS2345: Argument of type 'Partial<ISimpleUser>' is not assignable to parameter of type 'PayLoad<{ id: { toString: any; toFixed: any; toExponential: any; toPrecision: any; valueOf: any; ...'.
  Type 'Partial<ISimpleUser>' is not assignable to type 'DeepPartial<{ id: { toString: any; toFixed: any; toExponential: any; toPrecision: any; valueOf: a...'.
    Property 'length' is missing in type 'Partial<ISimpleUser>'.
test.ts(26,23): error TS2345: Argument of type '{ id: number; room: { id: number; color: string; }; }' is not assignable to parameter of type 'PayLoad<{ id: { toString: any; toFixed: any; toExponential: any; toPrecision: any; valueOf: any; ...'.
  Type '{ id: number; room: { id: number; color: string; }; }' is not assignable to type 'DeepPartial<{ id: { toString: any; toFixed: any; toExponential: any; toPrecision: any; valueOf: a...'.
    Property 'length' is missing in type '{ id: number; room: { id: number; color: string; }; }'.
```

If we look into the color types we can see that there are two files. The culprit is `index.d.ts` which has this definition:

```typescript
declare global {
    interface String {
        strip: string;
        stripColors: string;

        black: string;
        red: string;
        green: string;
        yellow: string;
        blue: string;
        magenta: string;
        cyan: string;
        white: string;
        gray: string;
        grey: string;

        bgBlack: string;
        bgRed: string;
        bgGreen: string;
        bgYellow: string;
        bgBlue: string;
        bgMagenta: string;
        bgCyan: string;
        bgWhite: string;

        reset: string;
        bold: string;
        dim: string;
        italic: string;
        underline: string;
        inverse: string;
        hidden: string;
        strikethrough: string;

        rainbow: string;
        zebra: string;
        america: string;
        trap: string;
        random: string;
        zalgo: string;
    }
}
```

If we remove this extension everything works. Any idea why typescript sent me in a wild hunt to see what is wrong with my code? For now I'll have to remove the colors type and hope that no other library interferes.

By the way, my IDE is the one that tells me about the excessive stack error. I am not able to see it by using the `tsc` command alone.

**Comment by jmlopez-rod** [comment] 2018-02-27 21:02
Whoa there buddy... I have submitted a reproducible example and a temporary solution I'm using. There is a still an issue here. Any library that messes with the global object will mess typescript. I'm lucky I found out that the colors types was messing up but I don't think I'll find it that easy to find another culprit in the future (or if it would be easy to not depend on it). Can this looked at please?

**Comment by Conaclos** [comment] 2018-03-03 19:24
Is this related to https://github.com/Microsoft/TypeScript/issues/21592?

**Comment by sandersn** [comment] 2018-03-14 17:43
@Conaclos yes this is a duplicate of #21592. I'll track the bug there since it has a very small repro.

**Closed** 2018-03-14 17:43 UTC
Labels: Bug, Duplicate
