### ISSUE TITLE
Why do the dynamic key types [propName: string]: any and [propName: string | symbol]: any behave the same?

### ISSUE THREAD

**Issue by yaodaoboy** [microsoft/TypeScript#60209] opened 2024-10-12 14:51 UTC
### Acknowledgement

- [x] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Now I'm creating an object obj with dynamic keys, and the only key type defined by the type is string; But when I give a **symbol** key to obj, TypeScript doesn't get an error. In JavaScript, the key types of objects can only be the two primitive types string and symbol, and the two types are relatively independent without implicit conversion; The code is as follows:
```js
let obj: {
    name: string;
    [propName: string]: any;
};

obj = {
    [Symbol(5)]: Symbol(6),
    name: "hhh"
}
```

As a beginner, I knew that index signature keys could only be string, number, symbol, or template text types, but since Numbers and template text types can be implicitly converted to string, I usually wrote `[propName: string]: any` for objects declaring any key type: any or `[propName: string | symbol]: any`, But strictly speaking, since Symbols and Strings don't implicitly convert, should it be written this way? `[propName: string | symbol]: any`

I wanted to know, in **TypeScript**, there's an implicit conversion between object key types symbol and string, like calling the toString method on a symbol key, Or maybe **TypeScript** doesn't prevent a symbol key by default if the object's type is declared as `[propName: string]: any`

**Comment by jcalz** [comment] 2024-10-12 15:48
duplicate of #44794

**Closed** 2024-10-17 01:32 UTC
Labels: Duplicate
