### ISSUE TITLE
Obscure "type cannot be used to index type" error when a mapped type is nested into another mapped type

### ISSUE THREAD

**Issue by shau-kote** [microsoft/TypeScript#54289] opened 2023-05-17 06:56 UTC
# Bug Report

### 🔎 Search Terms

- mapped type
- nested mapped type

### 🕗 Version & Regression Information

- It reproduces in TS of versions from 3.8.3 to 5.0.4 (there are other compiler errors in earlier versions).
- It reproduces in Nightly (v5.2.0-dev.20230516) as well.
- I failed to find out a description of similar cases in the FAQ.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.4#code/C4TwDgpgBAaghgGwK4QM4B4AqUIA9gQB2AJqlAPYBGAVhAMbAB8UAvFJgNoDWEI5AZuwC6AKBF1yhVMCgBRAHKYAkpgCaAfQDCAeXkAxJQHFWUAN4ioUAORFgAS1ABGKwC4zFy9ekQwzt+89PSnJiEDdTKDgot0coAF8PSziAGkSvAjAAJldLc0DLYNDwqEpSmPi0lI8qyxtCe1Bs8LSrb18cgPzCsLMoOn7yhMCaz1aMpty0gpCeiOJ5wcrUpJE4yLIJKWAxUEg5eocQTUl+OwBzE12IATlFFQ0dfSMd8GhZA9BMV5N4ZDR0PJQDjYOyEKA8PiCd4NI4nc5CZqBWyHeRwAC2EDcmFSaTabl+KAwgMCHAAylBQeDeDdoYdjoRTmdgUIEZ18lA2qiMW5SVMgjM3LTQPTGcyyUIOFZulZROyhp44oxqqslWJiPQEHAAE7QTbSHAfHpCkBfSBiPUyAjScJROAxNYAHzMpUo9qgTtM-Tobo982IbrYyNAADo2sHumI7IIABRBkDBuNc6AsFPWOPOACUnQtUCtwBt0SgjkdzrKRbWgcNoYy4ZmYksUagsarYc56OTqbGPkzbL6kn1eYLdvLJjj1Z8tdC1RwCFQ0GJfa2ubQ+dLrpHlZh47Ak5AyrWEFn848OcHZi9PrMfoDBq3YYjCREjebd5rbYxrE7bR7gNPK6Hl6egMG63oc267vWFIxmOibtp+bB1DC2RZguf7WuewHFqOLY1hGSQznOvZoaupi2jeY73nWKwHke2b9pa-5roB14gRRuF1nEQA)

### 💻 Code

```ts
type Values<T extends object> = T[keyof T]

const ENTITY_CONFIG = {
  'entity1': {
    'step1':  {
      body: { aaa: 1 }
    },
    'step2':  {
      body: { bbb: 1 }
    },
  },
  'entity2': {
    'step1':  {
      body: { ccc: 1 }
    },
    'step2':  {
      body: { ddd: 1 }
    },
  }
} as const

type EntityConfig = typeof ENTITY_CONFIG

type EntityType = Values<{
  [T in keyof EntityConfig]: {
    entityName: T,

    step: Values<{
      [S in keyof EntityConfig[T]]: {
        stepName: S
        body: EntityConfig[T][S]['body'] // <-- TS2536 error
      }
    }>
  }
}>
```

### 🙁 Actual behavior

I see an error around the `EntityConfig[T][S]['body']` type expression with the following error message: `Type '"body"' cannot be used to index type '{ readonly entity1: { readonly step1: { readonly body: { readonly aaa: 1; }; }; readonly step2: { readonly body: { readonly bbb: 1; }; }; }; readonly entity2: { readonly step1: { readonly body: { readonly ccc: 1; }; }; readonly step2: { ...; }; }; }[T][S]'.`. 

Firstly, I don't expect any errors in my type definition. Although it's possible of course that my mental model is wrong, or I don't understand some compiler limitations.

Secondly, the error message is quite obscure to me, it doesn't help to understand what I do wrong and how to fix it.

### 🙂 Expected behavior

I expect that the `EntityType` will be successfully constructed and will be something like this:

```
type EntityType = {
  entityName: 'entity1'
  step: {
    stepName: 'step1'
    body: { aaa: 1 }
  } | {
    stepName: 'step2'
    body: { bbb: 1 }
  }
} | {
  entityName: 'entity2'
  step: {
    stepName: 'step1'
    body: { ccc: 1 }
  } | {
    stepName: 'step2'
    body: { ddd: 1 }
  }
}
```

In fact, it seems to me based on my "tests" in the playground above that the `EntityType` type construction works well, despite the error in the type definition.

**Comment by shau-kote** [comment] 2023-05-17 07:03
Also, I found out that it's possible to kinda suppress the error by using the EntityConfig[T][S] extends infer U ? U extends { body: infer B } ? B : never : never expression for specifying the type of the body property, but it seems to me as a weird and should-be-needless hack.

**Comment by shau-kote** [comment] 2023-05-17 07:07
Lastly, I tried to explicitly declare that all steps of all entities should have a `body` declaration — so it's safe to index any step definition by the `'body` type.
But still no luck.

[Playground Link](https://www.typescriptlang.org/play?ts=5.0.4#code/C4TwDgpgBAaghgGwK4QM4B4AqUIA9gQB2AJqlAPYBGAVhAMbAB8UAvFJgNoDWEI5AZuwC6AKBGhIUAMLlC-AJYBzVlADeIqFABOEOMVkIQUDkWDzQAOTgBbCAC4oqYFvmFFQh+s2adeg0Y4nCDArWwcnFzcPNQ1vH119QkMoSnJiEAcqWgZYzQBfWIKCkTpZJygAUQtMAElMAE0AfSkAeQsAMRqAcRUvKAByU3MQAEZ+z1yBoLAxhxi4zVT0zyg4NYcRqAK4vIAaSf7pgCZxzT64pYy1FMpKDa3JvcL9zUHCM1ATibjDghnT+YLS4rOig+7bbxPH7HAHnbzA67EJHgx4vB55RxwMyoBRoaSyBSKMQSaAVd7DGRyJQqEkCSrVOpNVodbrE8Ck8mgTDslTwZBodB9DjYVxQHh8QRkj4gSmE6JwoaWGz2dj7SbTBx8lAYOGaDgAZSgovFdKlFIJSmFQnlkzi01CKv1tvhaSuZtAsstmCEBp9-Uu-VECweO0YhREeTDYmI9AQcB0UFKhHKirdnJA3MgYiT5QITk8azgGwxAB81Lc7lARqW1KC6MWoGXVEjiA22KmAHTTDuXMTyQQACk7qYdrBYbDe0rGAEpATngFA88AC+sqzXVBW2zh012-j3XWJNP2oEOd937cqxxPpjPAZp54u0Mu1IWt53u738jgEKhoHCH0unibmuKjvnun7ot+v5zmUC6AbWYIgU2LZvme4EHsUx6ntKu7BLhISXuO15-LefQAU+K5FkhCH1iB7ZoXhvaxFhw7pqOREDKmJyzv+sGPvmNGoThH4Hl+EA-n+kzkQJqivnR27Ceh6Thhi4nQWRfHwRutwNshyLyWBjEYUAA)

```ts
type Values<T extends object> = T[keyof T]

type Config = {
  readonly [entityName: string]: {
    readonly [stepName: string]: {
      readonly body: object
    }
  }
}

const ENTITY_CONFIG = {
  'entity1': {
    'step1':  {
      body: { aaa: 1 }
    },
    'step2':  {
      body: { bbb: 1 }
    },
  },
  'entity2': {
    'step1':  {
      body: { ccc: 1 }
    },
    'step2':  {
      body: { ddd: 1 }
    },
  }
} satisfies Config

type EntityConfig = typeof ENTITY_CONFIG

type EntityType = Values<{
  [T in keyof EntityConfig]: {
    entityName: T,

    step: Values<{
      [S in keyof EntityConfig[T]]: {
        stepName: S
        body: EntityConfig[T][S]['body']
      }
    }>
  }
}>
```

**Comment by Andarist** [comment] 2023-05-17 09:31
It's likely a duplicate of https://github.com/microsoft/TypeScript/issues/21760

**Comment by shau-kote** [comment] 2023-05-17 14:24
Thank you for the quick answer, @Andarist!

It really looks like a related problem. It's very sad that there's no visible success in finding a solution in this area.

Could you please also let me know if you're aware of any other (maybe better) workarounds except the double `extends infer` I described above?

**Comment by Andarist** [comment] 2023-05-17 14:51
You could try using something like this if you think that it makes your life easier ([TS playground](https://www.typescriptlang.org/play?ts=5.0.4&ssl=41&ssc=4&pln=24&pc=1#code/C4TwDgpgBAaghgGwK4QM4B4AqUIA9gQB2AJqlAPYBGAVhAMbAB8UAvFJgNoDWEI5AZuwC6AbgBQYuuUKpgUAKIA5TAElMATQD6AYQDyigGIqA4qygBvMVByFgAS1ABGAFwWr1qLIhgXbjx8pyYhBXcyg4CNdHKABfABp3a3jEzwIwACZQlOtA4NCoSkKo2IT-ZKTSm3tQTL8PLx8s-xygkIsoOk7i8o8e6wbay2aC1vzice7KivdkmPCyKRlgcTFQSAVbBxBtaX47AHMzNYgBBWU1LT1DExXj9jg7BCwcfCJScMIQDiFmNmw8AgkMgcOCfOJQAB0ULshH4EAATlAAEpCKAAfmRUFchAgADcEeI7sYIMAAArw8hgLDggDSvygNJegPePD4gmwGM4NNR2LxBNW4GgxLJcGAAAtqVBSUy3mRQV8fmZpQDZVAQZ8hO4McLyZTJaSOAAGH7uVw60USnUUqmYcEG42McGYB5PUmMRi3QUbaogTBetjwZBodBDNXYGFQVmneSbUA7WEHIRNDxEH2KOAAWwgrkwK38DVcgZQGFD-g4AGUoBGo4IYz743t9hxMEIk3Vhg101nXOXxMMWnkoObxeg61sGwdwc3weXwQAiXIgOc-PvNGKrpIembiGJbsTEegIODw6CLWRVLauMegP2QFZnuQEWT5CJwbpQAA+7UKlHfX7CnR0H+7TjMQ74sO4qZbBCDQQouKx2IIAAUUGgBCqEgF20AsDhUBzhhjhzgAlHUD5QE+wAvpEUDRHM-4FEUNGxGYGEwWkcGtHmVbIaxsGdpm2G4XODSESRpYdNI54UVRb5MXMbC8ex8EzDgCCoNA4lkdJ36MbRLGxiAbHeBxwSrjEYhzBAakae4WloJR7SAcBYSgeBF5obBynmWIiFQChBlGWAgVYawQkicRpGSY+9kyc5HRdHJ+k+oFJkgFxvn+clGEhThbD4QZ6QRZpUXkTFjkJXpCkBZ5nEqVZ6nthJSylc+7Svm5inGcpSQWapDWhnZrVhD+cWuYlVXJTVpkWWIQA)):
```ts
type Tail<T extends any[]> = T extends [any, ...infer R] ? R : never;
type GetProp<T, K> = K extends keyof T ? T[K] : never;
type GetPath<T, P extends any[]> = P extends [any]
  ? GetProp<T, P[0]>
  : GetPath<GetProp<T, P[0]>, Tail<P>>;

type EntityType = Values<{
  [T in keyof EntityConfig]: {
    entityName: T;

    step: Values<{
      [S in keyof EntityConfig[T]]: {
        stepName: S;
        body: GetPath<EntityConfig, [T, S, "body"]>;
      };
    }>;
  };
}>;
```

**Comment by shau-kote** [comment] 2023-05-17 16:40
I'm not sure whether it will be proper to close this issue now, but feel free to do it if it is.

**Comment by Andarist** [comment] 2023-05-17 19:45
> I'm not sure whether it will be proper to close this issue now, but feel free to do it if it is.

I don't have such privileges - I think that the issue cane be closed though (since it's a duplicate). Might be worth posting your case in that main thread though, this way it's likely that it will be added as a test case when that issue gets fixed.

**Closed** 2023-06-14 15:48 UTC
Labels: Duplicate
