### ISSUE TITLE
Transpilation-Free Syntax Proposal for JavaScript Developers

### ISSUE THREAD

**Issue by DevScholar** [microsoft/TypeScript#60699] opened 2024-12-06 08:58 UTC
### 🔍 Search Terms

transpilation-free, /*:

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

This proposal aims to introduce a transpilation-free syntax that allows developers to add certain TypeScript features without transpiling TypeScript to JavaScript. This syntax will be implemented through special comment markers, enabling TypeScript's type safety while reducing transpilation steps. This proposal is not intended to eliminate the transpilation step of TypeScript, but rather to provide an alternative option for JSDoc users.

**Transpilation-Free Syntax:**
   - Introduce a new comment marker `/*:`  
   - For example:
     ```javascript
     /*:
     type Point = {
         x: number;
         y: number;
     };
     */

     let point/*: Point*/ = {
         x: 10,
         y: 20
     };
     ```
   - In this syntax, content between `/*:` and `*/` is considered TypeScript features.

The syntax is primarily designed for type annotations, so certain specific TypeScript syntax (such as enum, interface) may not be available. If developers want to use these potentially unavailable syntaxes, JavaScript developers may need to write code twice in one file, once for TypeScript and once for JavaScript.

### 📃 Motivating Example

By introducing transpilation-free syntax, JavaScript developers can use TypeScript's powerful type system and development tool support without transpilation. 

### 💻 Use Cases

1. What do you want to use this for?
Use TypeScript's powerful type system and development tool support without transpilation. 
2. What shortcomings exist with current approaches?
TypeScript needed to be transpiled before running.
4. What workarounds are you using in the meantime?
Use JSDoc. JSDoc is more verbose than TypeScript.

**Comment by MartinJohns** [comment] 2024-12-06 09:33
Duplicate of #48650. Used search terms: `comments in:title label:Suggestion`

**Closed** 2024-12-06 10:37 UTC
