### ISSUE TITLE
Read-only tuple type with rest element

### ISSUE THREAD

**Issue by miyaokamarina** [Microsoft/TypeScript#28587] opened 2018-11-17 16:09 UTC
**TypeScript Version:**  3.2.0-rc, 3.1 (playground), strict, non-strict.

**Search Terms:** read-only tuple

**Code**

_Case 1: `Readonly`_

```ts
const t1: Readonly<[string, ...number[]]> = ['', 0];

// As expected...
t1.pop();
t1.pop();

t1[0] = ''; // Lol, readonly, you say?
// Expected: error

const [s1, ...n1] = t1; // string, number[], as expected
```
_Case 2: custom `ReadonlyTuple`_

```ts
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

type ReadonlyTuple<T extends any[]> = ReadonlyArray<unknown> &
  Readonly<
    Omit<
      T,
      | 'fill'
      | 'copyWithin'
      | 'pop'
      | 'push'
      | 'sort'
      | 'splice'
      | 'unshift'
    >
  >;

const t2: ReadonlyTuple<[string, ...number[]]> = ['', 0];

// Erorr, as expected
t2.pop();
t2.pop();

t2[0] = ''; // Error, as expected

const [s2, ...n2] = t2; // Ha, string, (string | number)[] again
// Expected: string, number[]
```

**Expected behavior:**

See code.

**Actual behavior:**

See code.

**Playground Link:** [link](https://www.typescriptlang.org/play/index.html#src=%2F%2F%20Case%202%3A%20Readonly%0D%0A%0D%0Aconst%20t1%3A%20Readonly%3C%5Bstring%2C%20...number%5B%5D%5D%3E%20%3D%20%5B''%2C%200%5D%3B%0D%0A%0D%0A%2F%2F%20As%20expected...%0D%0At1.pop()%3B%0D%0At1.pop()%3B%0D%0A%0D%0At1%5B0%5D%20%3D%20''%3B%20%2F%2F%20Lol%2C%20readonly%2C%20you%20say%3F%0D%0A%2F%2F%20Expected%3A%20error%0D%0A%0D%0Aconst%20%5Bs1%2C%20...n1%5D%20%3D%20t1%3B%20%2F%2F%20string%2C%20number%5B%5D%2C%20as%20expected%0D%0A%0D%0A%2F%2F%20Case%203%3A%20ReadonlyTuple%0D%0A%0D%0Atype%20Omit%3CT%2C%20K%20extends%20keyof%20T%3E%20%3D%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%3B%0D%0A%0D%0Atype%20ReadonlyTuple%3CT%20extends%20any%5B%5D%3E%20%3D%20ReadonlyArray%3Cunknown%3E%20%26%0D%0A%20%20Readonly%3C%0D%0A%20%20%20%20Omit%3C%0D%0A%20%20%20%20%20%20T%2C%0D%0A%20%20%20%20%20%20%7C%20'fill'%0D%0A%20%20%20%20%20%20%7C%20'copyWithin'%0D%0A%20%20%20%20%20%20%7C%20'pop'%0D%0A%20%20%20%20%20%20%7C%20'push'%0D%0A%20%20%20%20%20%20%7C%20'sort'%0D%0A%20%20%20%20%20%20%7C%20'splice'%0D%0A%20%20%20%20%20%20%7C%20'unshift'%0D%0A%20%20%20%20%3E%0D%0A%20%20%3E%3B%0D%0A%0D%0Aconst%20t2%3A%20ReadonlyTuple%3C%5Bstring%2C%20...number%5B%5D%5D%3E%20%3D%20%5B''%2C%200%5D%3B%0D%0A%0D%0A%2F%2F%20Erorr%2C%20as%20expected%0D%0At2.pop()%3B%0D%0At2.pop()%3B%0D%0A%0D%0At2%5B0%5D%20%3D%20''%3B%20%2F%2F%20Error%2C%20as%20expected%0D%0A%0D%0Aconst%20%5Bs2%2C%20...n2%5D%20%3D%20t2%3B%20%2F%2F%20Ha%2C%20string%2C%20(string%20%7C%20number)%5B%5D%20again%0D%0A%2F%2F%20Expected%3A%20string%2C%20number%5B%5D%0D%0A).

**Related Issues:** Destructured rest of tuple intersected with everything except `{}` and `unknown` results in at least union of all tuple's elements (or even `never`/`any`). Picking from tuple results in non-array type.

**Comment by ahejlsberg** [comment] 2018-11-18 15:56
Duplicate of #26864. In your second case the checker can no longer track that the input type was a tuple, so the rest element constraint is effectively lost. To really fix this, we need proper support for tuples with read-only elements as suggested in #26864.

**Closed** 2018-11-18 21:35 UTC
Labels: Duplicate
