### ISSUE TITLE
`this` not correctly captured when using it inside a lambda that is a super constructor parameter

### ISSUE THREAD

**Issue by RafaelSalguero** [Microsoft/TypeScript#12889] opened 2016-12-13 18:16 UTC
**TypeScript Version:**  2.1.4 (latest stable)

**Code**
The following code works ok on 2.0.10
```ts
class A {
    constructor(func: () => void) {
        func();
    }
}

class B extends A {
    constructor() {
        super(() => console.log(this.name));
    }
    public name : string;
}
```

**Expected behavior:**
Variable `this` correctly captured *before* calling `_super.call`
This is works on typescript 2.0.10
```
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var A = (function () {
    function A(func) {
        func();
    }
    return A;
}());
var B = (function (_super) {
    __extends(B, _super);
    function B() {
        var _this = this;
        _super.call(this, function () { return console.log(_this.name); });
    }
    return B;
}(A));
```
**Actual behavior:**
Variable `_this` doesn't exists. On more complex examples variable this is assigned to the result of `_super.call`which is still incorrect, since the variable should be setted *before* calling this method
```
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var A = (function () {
    function A(func) {
        func();
    }
    return A;
}());
var B = (function (_super) {
    __extends(B, _super);
    function B() {
        return _super.call(this, function () { return console.log(_this.name); }) || this;
    }
    return B;
}(A));
```

**Comment by wallverb** [comment] 2016-12-13 19:25
https://github.com/Microsoft/TypeScript/issues/12764

**Comment by mhegazy** [comment] 2016-12-13 19:28
in deed a duplicate of #12764.

**Closed** 2016-12-13 19:34 UTC
Labels: Duplicate
