### ISSUE TITLE
Allow non-named function parameters in type aliases and generic types (optionally)

### ISSUE THREAD

**Issue by MaxGraey** [microsoft/TypeScript#49634] opened 2022-06-22 12:01 UTC
# Suggestion

Add optional support of shorthand notation (non-named) for function parameters in type aliases and generic parameter declarations. For example:

```ts
type Fn = (number, string) => void

function foo<Cb = (number) => void>(callback: Cb) {}
```

instead:

```ts
type Fn = (num: number, str: string) => void

function foo<Fn = (num: number) => void>(callback: Fn) {}
```

Which strictly required for now. 

Maybe I have missed something and this is an important feature of TS without which the type checking system will not work properly?

## 🔍 Search Terms

function parameters named non-named notation declaration type alias

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

Most of the languages support shorthand function notation in type aliases for such cases like Rust, Dart, Kotlin, Swift  and etc

**Comment by MartinJohns** [comment] 2022-06-22 12:10
Duplicate of #16668 and others.

See this comment: https://github.com/microsoft/TypeScript/issues/13152#issuecomment-269099764

**Comment by MaxGraey** [comment] 2022-06-22 12:23
Thanks! While that issue was closed I would like to bring it up again.

From https://github.com/microsoft/TypeScript/issues/13152#issuecomment-269099764
> I think it is too late to make this sort of change. Because of the current behavior, interpreting a single identifier as a type would be a breaking change.

I disagree about breaking change. If this feature will be optional. For example has compiled could handle mixed cases:
```ts
lat b = 0;
type Fn1 = (a, string) => void // Error: 'a' unknown type
type Fn2 = (b, string) => void // Error: 'b' is not a type
```
mixed cases:
```ts
type Fn1 = (num: number, string) => void  // Ok
type Fn2 = (num: number, str: string) => void  // Ok
type Fn3 = (number, str: string) => void  // Ok
```

> I also believe that it helps with documentation. Having used Haskell in the capacity that I have, I will say that omitting parameter names helps doesn't help anybody when they're learning a new library. While there's something to be said about an easier syntax, types being the only form of documentation for people often makes it difficult to understand intent, so requiring a parameter has its benefits.

Yes, I agree with that, and it is probably the only useful feature of this convention. But I'm not suggesting to remove naming in signatures at all, just to make it optional; it's quite feasible and won't lead to any breaking changes or deprive the possibility to declare parameter names more explicitly for, say, a better docs

**Comment by MaxGraey** [comment] 2022-06-22 12:31
It even could be very easy implement without any huge changes. Just syntactically de-sugar this
```ts
(number, string) => void
```
to
```ts
(number: number, string: string) => void
```

**Comment by fatcerberus** [comment] 2022-06-22 13:43
It *is* a breaking change, because `(number, string) => void` currently means `(number: any, string: any) => void`.

**Comment by MartinJohns** [comment] 2022-06-22 13:43
> Just syntactically de-sugar this [..] to [..]

This would be a massive breaking change, which according to the comment in #13152 the team is not willing to do (see also goal 11 of the TypeScript Design Goals).

**Comment by MaxGraey** [comment] 2022-06-22 13:49
> > Just syntactically de-sugar this [..] to [..]
> 
> This would be a massive breaking change, which according to the comment in #13152 the team is not willing to do (see also goal 11 of the TypeScript Design Goals).

I already mentioned [this comment] above. I don't see any breaking changes. Could you elaborate how this may break existing code? I would like to see a counterexample

**Comment by fatcerberus** [comment] 2022-06-22 13:50
It's not invalid syntax.  It's an implicit-any error, but only with `strict` (specifically, `noImplicitAny`) enabled.

**Comment by MartinJohns** [comment] 2022-06-22 14:02
> Wait, what? So language syntax / behavior depends on config option?

Of course language behaviour depends on the config option, otherwise flags like `strictNullChecks` wouldn't work. But the config options do not have an effect on the syntax of the language. No matter if you have `noImplicitAny` enabled or not, the syntax and behaviour are the same.

> TS has already made much more serious breaking changes in recent releases

These are usually a worthwhile trade-off to improve type-safety.

**Comment by MartinJohns** [comment] 2022-06-22 14:16
> This seems to be the case.

:shrug: Personally I'd say no. The team apparently thought the same in the other issue. This hardly brings any benefit, is a huge breaking change and will lead to less documentation (people omit the parameter names).

> And expects that `parse` accept only string inputs, but in fact `parse` allows inputs with any types. (with `noImplicitAny` disabled). Isn't this unsound?

It's not unsound, because that's what the `any` type is there for. Unsoundness refers to cases where the type system is simply wrong (compile time and run time type differ).

And yes, you should avoid writing this code, that's why `noImplicitAny` exists and is part of the `strict` family.

**Comment by RyanCavanaugh** [comment] 2022-06-22 16:20
> Wait, what? So language syntax / behavior depends on config option?

The confusion here is what you're asking to *introduce*, because to not make this a breaking change, we'd have to interpret `type F = (string) => number` differently depending on whether `noImplicitAny` is set. In general the syntactic interpretation of a line of TS code is not configurable at all, and that's a good thing.

**Closed** 2022-06-24 18:00 UTC
Labels: Duplicate
