### ISSUE TITLE
Wrong overload resolution with generics

### ISSUE THREAD

**Issue by aikoven** [Microsoft/TypeScript#11343] opened 2016-10-04 07:00 UTC
**TypeScript Version:**  1.8.10

**Code**

``` ts
declare function compose<A, B, R>(f1: (b: B) => R, f2: (a: A) => B): (a: A) => R;

declare function compose<R>(...funcs: Function[]): (arg: any) => R;


type Creator<S> = () => S;
type Enhancer = <S>(creator: Creator<S>) => Creator<S>;

declare const enhancer1: Enhancer;
declare const enhancer2: Enhancer;

const enhancer = compose(enhancer1, enhancer2);

const creator = enhancer(() => '');
creator();
```

**Expected behavior:**
Should compile with no error.

**Actual behavior:** 
Compiler gives error on the last line:

```
Uncaught Semantic: Cannot invoke an expression whose type lacks a call signature.
```

However if we remove the second oveload of `compose`, everything works fine, which means that the first overload actually matches but for some reason the second one is selected.

Also, if we remove type variable from `Enhancer` definition and replace it with `string`, it compiles again.

**Comment by gcnew** [comment] 2016-10-04 09:04
TypeScript is not good at preserving templated types (i.e. inferring most general type of polymorphic functions). This is generally a duplicate of https://github.com/Microsoft/TypeScript/issues/9949. Note that even if you comment out the second overload, the types are still not correct, as the template param `S` of `Enhancer` is substituted with `{}`. I.e. the inferred signature for `enhancer` is:

```ts
creator: (a: {}) => () => {}
```

While the correct one would be:
```ts
creator: <T>(a: T) => () => T
```

**Comment by aikoven** [comment] 2016-10-04 09:30
I'm not sure I understand. I acknowledge that TypeScript is unable to preserve type argument and the best we can get from `compose` is `(creator: Creator<{}>) => Creator<{}>`

The main question is: if TypeScript selects the first matching overload, and the first one actually matches, then why does it selects the second one?

**Comment by gcnew** [comment] 2016-10-04 09:42
I see, yes it does seem odd.

**Comment by gcnew** [comment] 2016-10-04 10:22
This behaviour is triggered whenever the return type must be inferred.

The following works as expected:
```ts
declare const f: (x:number) => string;
declare const g: (x:boolean) => number;
const c = compose(f, g) // (a: boolean) => string
```

However if we change `f` to return a generic, it is the second overload that gets selected:
```ts
declare const f: <T>(x:number) => T;
declare const g: (x:boolean) => number;
const c = compose(f, g) // (arg: any) => {}
```

The above example is logically incorrect, because we can't produce a value of type `T` for any arbitrary type `T` just from the input argument `x: number`. In this case TS is being lax and chooses the signature that has no restrictions.

Your example, however, is a special case, because the given signature of `Enhancer` is the signature of the identity function (or is it? what do you use it for?).

```ts
// according to the type signature we can do nothing with `creator: Creator<S>` except to
// return it because this signature must be valid for every type `S`.
// Or have side effects :( which the the type system doesn't track
type Enhancer = <S>(creator: Creator<S>) => Creator<S>;
```

However, TypeScript seems to not be able to notice that and doesn't use the argument `creator` as an inference point, thus it falls back again to the more lax signature.

**Comment by aikoven** [comment] 2016-10-04 10:47
Our use case is creating Redux Store:

```ts
interface Store<S> {
  getState(): S;
  // bunch of other methods
}
```

And actually the signature of `Creator` is more like:

```ts
type Creator<S> = (...params) => Store<S>;
```

I just tried to get the minimal failing example.

Enhancer doesn't have to be identity, it may take one creator and produce another that e.g. creates the store, does some behaviour enhancements on it and returns the new one without altering its state type `S`.

**Comment by mhegazy** [comment] 2017-05-17 22:51
looks like a duplicate of  #9949

**Closed by mhegazy** 2017-05-17 22:51 UTC
Labels: Duplicate

**Comment by mhegazy** [comment] 2017-05-18 20:06
Actually a better one to dupe against is https://github.com/Microsoft/TypeScript/issues/9366
