### ISSUE TITLE
Type Inference Incorrect in Closure (Possibly Undefined)

### ISSUE THREAD

**Issue by shortstuffsushi** [microsoft/TypeScript#48698] opened 2022-04-14 14:16 UTC
# Bug Report

In a situation where you first declare a variable as `let foo: MyType | undefined`, then optionally set it, followed by checking its presence or returning, and then trying to use in a closure, it will revert to being "possibly undefined." Sorry if there is a similar report here, I had a hard time finding matching terms.

### 🔎 Search Terms

Possibly Undefined Closure

### 🕗 Version & Regression Information

We are using 4.6.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIhwC2EAXMgM5hSgDmA3LgL666iSyIoboBCcKDnzIYmAEaCK1WiEYiAbnAA2AV3KFVxcdCas2uGKpAIwwdCGSRqACjHpJUShV4CoAbQC6ASmEFlEGDIxACevC6YyAA+yMYAJhAwoBBxTCLAMMg2IBAA7sgAInCQNt4AdHSBACrApKXIAKTIAEzIALwdyAAMvngEBKG87X79BESkFADk9pMANCIEzEyLbAQZWQCEg5i9C8hQgapQliCqysrLyPprmTbb6GXjKB1tyNOYzZO7owgWlOgBMrKdB0GwAImowHOyDomDiYO8l2u+0Ox1EEkElDKxDgAAcbHYMVBfG0AHwjG5Ze6PEjPTrvdCfb6jFFgI6WVoAKnRDkEZSUagglxWewObLR9kc-JU6iRiLYzCAA)

### 💻 Code

```ts
let foo: MyFoo | undefined;
if (new Date().getTime() % 2 === 0) {
  myFoo = {
    name: 'foo',
  };
}

if (!foo) {
  return;
}

otherFoos.map((ofoo) => {
   if (foo.name === 'bar') { // ---- foo object is possibly undefined
     ofoo.name = foo.name;
   }
});
```

### 🙁 Actual behavior

Dereferencing foo.name is marked as possibly undefined though we've asserted that it is not

### 🙂 Expected behavior

foo should be known to be defined. We are able to use it in the same scope, but once we get into a closure, it reverts to unknown.

**Comment by fatcerberus** [comment] 2022-04-14 14:27
Duplicate of #9998

**Comment by MartinJohns** [comment] 2022-04-14 14:42
When creating an issue:
![image](https://user-images.githubusercontent.com/5269069/163414362-45d2b49f-f628-4947-bf9c-46f483cd8ef4.png)
https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/types-not-correct-in-with-callback.md

**Closed** 2022-04-16 18:00 UTC
Labels: Duplicate
