### ISSUE TITLE
Type narrowing context is lost within closures

### ISSUE THREAD

**Issue by ramyhhh** [microsoft/TypeScript#46118] opened 2021-09-28 17:45 UTC
# Bug Report
### 🔎 Search Terms

typescript union typed narrowing lost in closures
type narrowing closures

### 🕗 Version & Regression Information
Typescript versions 4.4.3  and still exists on Nightly 4.5.0-dev

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiCqA7Alge0VAvFA3lUkAXFAOQA2EAZsCQDRRgBOqkjoAogB7IDOwPAeUQAZKsGJ9GyRAHMoAXygAfXPnARiJKTIAWNekxYQ2ILr35CASsl3iok6XPkAoZxWBROWXIoCGPWAQUdABuVx4Ad2RgAGMdKAAKTgA6AggASlxnKByoGP9ocjESQmzc8pj0PigQbxTDVg5uPkERMRCoAHpO3zIyKBlUVAATKB1jaGSpsvKcysQeVApkslQZBITMzAA+T2SG4ybzVtFqTO6eHVQo2ShjZkYoACIABWZG2pIDkzMWoVOaFBhqgIAFEKgPBBmh50GpIKQ4Eg0IgSE8ZrMAEaMCC+ADWYXkQA)

### 💻 Code

```ts
type MyUnion = { type: 'left', propertyExistsOnLeft: string } | { type: 'right', propertyExistsOnRight: string }

let x = {} as MyUnion;

switch (x.type) {
    case 'left':
        const y = x.propertyExistsOnLeft; //all good here ...
        console.log(() => x.propertyExistsOnLeft) //showing error "Property 'propertyExistsOnLeft' does not exist on type 'MyUnion'"
        break;
}
```

### 🙁 Actual behavior
Type narrowing is working as expected when following control flow, however when the variable is used inside a closures scope (arrow functions or normal functions) it reverts back to it's declared type losing all narrowing inferred from the containing scope.

### 🙂 Expected behavior
Type narrowing should continue to work inside the context of closures.

**Comment by MartinJohns** [comment] 2021-09-28 17:48
And another duplicate of #9998.

**Comment by ramyhhh** [comment] 2021-09-28 17:57
Yeah, that issue looks like a master issue collecting all control flow analysis issues :)

**Comment by MartinJohns** [comment] 2021-09-28 18:03
The exact same issue you describe comes up again and again and again. I probably have seen at least 50 issues already. It's all due to the difficulties described in #9998.

**Comment by fatcerberus** [comment] 2021-09-28 18:10
> Yeah, that issue looks like a master issue collecting all control flow analysis issues :)

More specifically, control flow analysis issues *across function boundaries*.  Which is not an easy problem to solve.

**Closed** 2021-10-03 18:00 UTC
Labels: Duplicate
