### ISSUE TITLE
Assert failure in goto def

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#21766] opened 2018-02-08 17:04 UTC
```ts
new Date
```

goto def on `Date`.

```log
[Error  - 9:02:52 AM] 'definition' request failed with error.
Error processing request. Debug Failure. Expected declaration to have at least one class-like declaration
Error: Debug Failure. Expected declaration to have at least one class-like declaration
    at getConstructSignatureDefinition (C:\ls\tsserver.js:86387:88)
    at getDefinitionFromSymbol (C:\ls\tsserver.js:86382:20)
    at Object.getDefinitionAtPosition (C:\ls\tsserver.js:86305:20)
    at Object.getDefinitionAtPosition (C:\ls\tsserver.js:100249:38)
    at IOSession.Session.getDefinition (C:\ls\tsserver.js:107879:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\ls\tsserver.js:107379:61)
    at C:\ls\tsserver.js:108879:88
    at IOSession.Session.executeWithRequestId (C:\ls\tsserver.js:108870:28)
    at IOSession.Session.executeCommand (C:\ls\tsserver.js:108879:33)
    at IOSession.Session.onMessage (C:\ls\tsserver.js:108899:35)
    at Interface.<anonymous> (C:\ls\tsserver.js:110160:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)

```

**Comment by sheetalkamat** [comment] 2018-02-08 17:24
Duplicate of #21501 and should be fixed now.

**Closed by sheetalkamat** 2018-02-08 17:24 UTC
Labels: Bug, Duplicate
