### ISSUE TITLE
Crash in checkTypeReferenceNode deep inside checkJSDoc on @next

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#17525] opened 2017-07-31 07:03 UTC
**TypeScript Version:**  2.5.0-dev.20170727

**Stack trace**

```
.../node_modules/typescript/lib/tsc.js:55939
                throw e;
                ^

TypeError: Cannot read property 'flags' of undefined
    at checkTypeReferenceNode (.../node_modules/typescript/lib/tsc.js:32628:52)
    at checkSourceElement (.../node_modules/typescript/lib/tsc.js:35245:28)
    at checkSourceElement (.../node_modules/typescript/lib/tsc.js:35278:28)
    at checkSourceElement (.../node_modules/typescript/lib/tsc.js:35265:28)
    at checkJSDocComment (.../node_modules/typescript/lib/tsc.js:33243:21)
    at checkSourceElement (.../node_modules/typescript/lib/tsc.js:35263:28)
    at Object.forEach (.../node_modules/typescript/lib/tsc.js:267:30)
    at checkJSDoc (.../node_modules/typescript/lib/tsc.js:33237:16)
    at checkFunctionOrMethodDeclaration (.../node_modules/typescript/lib/tsc.js:33248:13)
    at checkFunctionDeclaration (.../node_modules/typescript/lib/tsc.js:33224:17)
```

The value of `getNodeLinks(node)` is `{ flags: 0, resolvedSymbol: undefined, resolvedType: Type }`. Calling `typeToString()` on the `resolvedType` produces `any[]`. The crash is caused through unconditionally accessing `resolvedSymbol.flags`.

**Code**

The crash seems to be caused when trying to parse `chai` or `chai/core/assertions.js`, as the `node.parent.parent.parent.comment` is this:

```
### .oneOf(list[, msg])

Asserts that the target is a member of the given array `list`. However,
it's often best to assert that the target is equal to its expected value.

     expect(1).to.equal(1); // Recommended
     expect(1).to.be.oneOf([1, 2, 3]); // Not recommended

Comparisons are performed using strict (`===`) equality.

Add `.not` earlier in the chain to negate `.oneOf`.

     expect(1).to.equal(1); // Recommended
     expect(1).to.not.be.oneOf([2, 3, 4]); // Not recommended

`.oneOf` accepts an optional `msg` argument which is a custom error message
to show when the assertion fails. The message can also be given as the
second argument to `expect`.

     expect(1).to.be.oneOf([2, 3, 4], 'nooo why fail??');
     expect(1, 'nooo why fail??').to.be.oneOf([2, 3, 4]);
```

Given this, I suspect that the crashing line is `@param {Array<*>} list` in the jsdoc comment.

---

This crash does not seem to happen with 2.4.2. Installing `@types/chai` also works around the crash.

**Comment by RyanCavanaugh** [comment] 2017-07-31 23:42
Duplicate of #17383

**Comment by Kovensky** [comment] 2017-08-01 01:37
This crash is happening with an actual generic, though (`Array<T>`). I _think_ it's caused by its template argument not being itself a TypeScript type but the closure compiler `*`.

**Closed** 2017-08-02 20:55 UTC
Labels: Duplicate
