### ISSUE TITLE
Type x is not assignable to {conditional return type y}

### ISSUE THREAD

**Issue by anurbol** [Microsoft/TypeScript#28917] opened 2018-12-08 02:16 UTC
Hello, TS team. I bet this is easy one for you. And I 95% sure it's not a bug (then what?). The code is not entirely mine, but still I wonder why it fails to compile **and** why TS doesn't break down the error as it usually does.

**TypeScript Version:**  3.3.0-dev.20181207 (3.1.6 gives the same result, as does the current playground)

**Search Terms:** "Type x is not assignable to {conditional return type y}"

**Code**

```ts
const fn = <D extends string | undefined>(someParam: string, defaultValue?: D) : D extends undefined ? string | undefined : string => {

  const result = '';

  return result;
}
```

**Expected behavior:**
To compile or at least to break down the error.

**Actual behavior:**
Fails and shows a not very useful error "Type '""' is not assignable to type 'D extends undefined ? string : string'."

**Playground Link:** 
 the [playground](http://www.typescriptlang.org/play/index.html#src=const%20returnSomething%20%3D%20%3CD%20extends%20string%20%7C%20undefined%3E(someParam%3A%20string%2C%20defaultValue%3F%3A%20D)%20%3A%20D%20extends%20undefined%20%3F%20string%20%7C%20undefined%20%3A%20string%20%3D%3E%20%7B%0A%0A%20%20const%20result%20%3D%20''%3B%0A%0A%20%20return%20result%3B%0A%7D)

Is it at all OK to use a conditional type as a return type? Am I missing something?

P.S. This problem came from [stackoverflow](https://stackoverflow.com/questions/53677204/return-type-strengthening-depending-on-whether-optional-param-is-passed), I've tried to answer.

**Comment by jack-williams** [comment] 2018-12-08 12:51
There are two things going on here: one is an issue with the code; one is a design limitation or bug.

First issue: the conditional type in the return type is distributive, meaning that it will short correct when `D` is instantiated to `never`. As a consequence it is not _always_ correct to return a string, the function might be expected to return nothing. Example:


```ts
const fn = <D extends string | undefined>(someParam: string, defaultValue?: D) : D extends undefined ? string | undefined : string => {
  const result = '';
  return result as any; // turn off error
}

// x claims to be never, or nothing, but will be some string
const x: never = fn<never>("a string");
```

To turn off distribution you want to use 1-tuples:
```ts
const fn = <D extends string | undefined>(someParam: string, defaultValue?: D) : [D] extends [string] ? string : (string | undefined) => {
  const result = '';
  return result as any; // turn off error
}

// error: string not assignable to never
const x: never = fn<never>("a string");
```

The second issue: even when you handle the never case this is still an error because the type checker is missing the corresponding assignability rule. This is tracked by this issue: #26933. I think there is an open PR fixing the problem here: #27932.

**Comment by anurbol** [comment] 2018-12-08 13:43
@jack-williams I *feel* that's a great explanation, but due to lack of english knowledge, failed to comprehend things like "short correct" :smile: Maybe as a result I didn't understand what `never` has to deal with this.

**Comment by anurbol** [comment] 2018-12-08 13:49
If this issue can be considered as a duplicate by TS team (I am not 100% sure if it is), then I am not against closing it.

**Comment by Nathan-Fenner** [comment] 2018-12-10 20:46
The following type will do what you wanted:

```ts
const fn = <D extends string | undefined>(someParam: string, defaultValue?: D) : string | (D extends undefined ? undefined : never) => {

  const result = '';
  return result;
}
```

The trick is to pull the `string | ...` out of the conditional, so that it is always an option.

(depending on where your typings are coming from, this may not actually solve your problem).

**Comment by weswigham** [comment] 2018-12-10 21:30
Duplicate of  #26933

**Closed** 2018-12-12 10:00 UTC
Labels: Duplicate
