### ISSUE TITLE
Casing is not preserved when compiling `<reference path="...">` triple slash directives

### ISSUE THREAD

**Issue by craxal** [microsoft/TypeScript#52110] opened 2023-01-04 23:39 UTC
# Bug Report

### 🔎 Search Terms

reference types

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about triple slash directives.

### ⏯ Playground Link

Unable to produce playground link, as this involves the use of several files.

GitHub repository: https://github.com/craxal/triple-slash-path

#### module-one/PanelWindow.d.ts
```ts
declare global {
    interface CustomWindow {
        getSomething(): any;
    }

    interface Window {
        customWindow: CustomWindow;
    }
}
```

#### module-two/Class.ts
```ts
// <reference path="../../node_modules/storage-explorer/dist/PanelWindow.d.ts" />

import * as $ from "jquery";
import { IContextMenuItem } from "storage-explorer";

export interface ICustomType {
    someProperty: string;
}

export async function doSomething(args: ICustomType): any {
    const obj = await window.customWindow.getSomething();
    return obj;
}
```

### 🙁 Actual behavior

The triple slash directive is compiled to something similar to the following (note the casing is not preserved, even if `forceConsistentCasingInFileNames` is set to `true`):

```js
// <reference types="module-one/customwindow" />
```
Because of this issue, I cannot compile on macOS. This is not an issue on Windows.

### 🙂 Expected behavior

I expect the triple slash directive in module-two/Class.ts to be compiled to something similar to the following (note the casing ought to be preserved if `forceConsistentCasingInFileNames` is set to `true`):
```js
// <reference types="module-one/CustomWindow" />
```

**Comment by fatcerberus** [comment] 2023-01-05 00:03
Duplicate of https://github.com/microsoft/TypeScript/issues/50544 and several others

**Comment by fatcerberus** [comment] 2023-01-05 00:05
Weirdly, this seems to have been implemented this way *intentionally*: https://github.com/microsoft/TypeScript/pull/10340

**Closed** 2024-03-20 22:06 UTC
Labels: Bug, Help Wanted, Fix Available
