### ISSUE TITLE
Wrong type when using keyof

### ISSUE THREAD

**Issue by danikaze** [microsoft/TypeScript#46971] opened 2021-12-01 11:19 UTC
# Bug Report

### 🔎 Search Terms

`keyof type string object `

### 🕗 Version & Regression Information

Tested in the playground on versions 3.3.3, 4.5.2 and Nightly.
Happens in each of them.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gPAFShAHsCA7AJgZyj4AJwEsMBzAPigF4oBvKANwEMAbAVwgC4oEBfANwAoIQGNWzHHgDCcAKLI0mXFABKEUQHtCWOARLkANFHYYA1hk0B3DBSp0hUJ1AD0LqMQBmUYAAtoZhAgUJreCsR4+qRkUJJQWBoShBBYHhg+-lBkmBAkooaOzm5QVr7BAAaBIKFQcuXxmhA4GADkwPjMwBGewX7QWtjEXZoYAPyFTmCEmuii6KmexIQEANJBPPBVNXIUwhNQA-rsc9oAFJoARgBWPHIAlPT7zhkRAHSLy8BrwbQw1xrAV5VHDna53ADaAAYALrCZ58IR8IA)

### 💻 Code

```ts
type O<T extends string> = { value: T};

class C<E extends Record<string, unknown>> {
    // if the key of E is string as declared in the generic,
    // why `keyof E` doesn't satisfy the condition?
    protected firstKey: O<keyof E>; // Type 'keyof E' does not satisfy the constraint 'string'.

    constructor(obj: E) {
        this.firstKey = Object.keys(obj)[0]; // Type 'string' is not assignable to type 'O<keyof E>'.
    }
}
```

### 🙁 Actual behavior

Generic `E` is defined to extend a Record with string key, but `keyof` is returning `string | number | Symbol` as if there was no `Record<string, ->` definition

### 🙂 Expected behavior

`keyof E` to return string

**Comment by MartinJohns** [comment] 2021-12-01 12:06
Duplicate of #45447.

**Comment by fatcerberus** [comment] 2021-12-01 13:18
To be clear, `E` is not guaranteed to *only* have string keys.  `Record<string | number, unknown>` is a valid subtype of `Record<string, unknown>` because the type system only guarantees that an object has *at least* the properties named in its type.

in general, narrower types have a wider `keyof`.

**Comment by RyanCavanaugh** [comment] 2021-12-01 16:16
This is a frequent source of misunderstanding; see also https://twitter.com/SeaRyanC/status/1418678669975834627

**Closed by RyanCavanaugh** 2021-12-01 16:16 UTC
Labels: Working as Intended

**Comment by danikaze** [comment] 2021-12-04 13:46
The more you know...
