### ISSUE TITLE
Type narrow with switch(obj.constructor)

### ISSUE THREAD

**Issue by pauldraper** [microsoft/TypeScript#54404] opened 2023-05-26 02:05 UTC
# Suggestion

## 🔍 Search Terms

constructor property, type narrowing

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I would like the `.constructor` property to narrow the type in a switch statement.

## 📃 Motivating Example

Today, the following fails type checking:

```ts
class Success<T> { constructor(readonly value: T) {} }
class Failure { constructor(error: any) {} }
type Result<T> = Success<T> | Failure;

const result: Result<string> = new Success("example");

switch (result.constructor) {
  case Success:
    console.log(`Success: ${result.value}`);
    break;
  case Failure:
    console.log(`Failure: ${result.error}`);
    break;
}
```

## 💻 Use Cases

Ad-hoc polymorphism.

Many people think this already works.

Request (2018) redirected to a (completed, but different) issue: https://github.com/microsoft/TypeScript/issues/2214#issuecomment-431470212

Blog post (2020) claiming this feature exists: https://log.havrlant.cz/typescript-switch-instanceof/ (Sadly, the author's demonstration was flawed.)

`if` can work instead, but gives up the performance advantages of `switch` for a lot of branches.

**Comment by fatcerberus** [comment] 2023-05-26 02:32
Duplicate of #16035

**Closed** 2023-05-28 18:00 UTC
Labels: Duplicate
