### ISSUE TITLE
Highlighting of imported types in Visual Studio

### ISSUE THREAD

**Issue by MizardX** [Microsoft/TypeScript#9053] opened 2016-06-09 12:38 UTC
**TypeScript Version:** 

Extension version 1.8.30 / TypeScript version 1.8.9

**Code**

```ts
namespace M1 {
    export interface Foo {}
    export const enum Bar { A = 1 }
}

namespace M2 {
    type Foo = M1.Foo;
    import Bar = M1.Bar;
    interface Baz { }

    var x: Foo;
    var y: Bar = Bar.A;
    var z: Baz;
}
```

**Expected behavior:**
`Foo`, `Bar` and `Baz` should all be highlighted as types (blue)

**Actual behavior:** 
`Bar` is highlighted as a normal identifier (black)

![importhighlight](https://cloud.githubusercontent.com/assets/277403/15929861/cda2967a-2e4f-11e6-92f1-976170f7a7fc.png)

**Comment by mhegazy** [comment] 2016-06-09 16:47
Duplicate of https://github.com/Microsoft/TypeScript/issues/2890

**Closed by mhegazy** 2016-06-09 16:47 UTC
