### ISSUE TITLE
Super slow compilation in rare cases when mixing explicit typing, generics and type-inference

### ISSUE THREAD

**Issue by choeller** [Microsoft/TypeScript#7460] opened 2016-03-10 14:49 UTC
**TypeScript Version:** 

1.8.7

**Code**

Having three classes like this:

```ts

import {Subject} from 'rxjs/Rx';
import {Task} from '../../models/task'
import {TaskStore} from "../task-store/task-store";

export class TaskService {
  //foo = "bar";   // -> commenting in solves slow compilation
  tasks: Subject<Task[]>;
}

```

```ts

import {Task} from "../../models/task";
import {BehaviorSubject} from "rxjs/Rx";

export class TaskStore {
  tasks =  new BehaviorSubject([]);
  //tasks = new BehaviorSubject<Task[]>([]); // -> change above line withis this one solves slow compilation
  //_tasks =  new BehaviorSubject([]);  // -> change above line withis this one solves slow compilation
}

```

```
import {bootstrap} from 'angular2/platform/browser';
import {TaskStore} from "./app/services/task-store/task-store";
import {TaskService} from './app/services/task-service/task-service';

class TestClass {
}

bootstrap(TestClass, [
    TaskService,
    TaskStore,
]);

```

leads to super slow compilation. Commenting  in any of the lines above makes the compilation about 6 times faster. 

See this repositiory as a reference for the problem:

https://github.com/choeller/slow-ts-compiler-demo/

**Comment by sandersn** [comment] 2016-03-10 15:57
This looks like a dupe of #7082 or the other problems with compiling RxJs. @vladima can you take a look?

**Comment by sandersn** [comment] 2016-03-10 16:01
As a quick overview of the problem, caching is broken for class `this` types and RxJs is a commonly used project that relies on caching common base types to be able to compile fast enough.

**Comment by vladima** [comment] 2016-03-10 20:23
I would keep this open, fix for `this` types does not make this issue completely go away - compilation time is dropped from 8-9 to ~6 seconds but still it is kind of slow. Crux of the problem - `rxjs-5.0.0.beta2` exposes a number of types that look similar and quite complicated in  structure and doing a full structural comparison of them takes a lot of time

Simplified repro: https://github.com/vladima/rxjs-issue - majority of time is spent doing subtype reduction.

**Comment by vladima** [comment] 2016-06-08 00:39
closing as [fix to RxJS](https://github.com/ReactiveX/rxjs/pull/1475) was already merged

**Closed by vladima** 2016-06-08 00:39 UTC
Labels: Bug
