### ISSUE TITLE
writable should not accept readonly

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#39405] opened 2020-07-03 13:44 UTC
**TypeScript Version:**  3.9.3

**Search Terms:**

**Code**

```ts
const obj :{ prop: number } = { prop: 0 } as { readonly prop: number };
obj.prop = 1;
```

**Expected behavior:**

error

**Actual behavior:**

no error

**Playground Link:** 

**Related Issues:**

**Comment by MartinJohns** [comment] 2020-07-03 14:05
Duplicate of #13347.

**Comment by mathieucaroff** [comment] 2020-07-03 17:04
**Playground link:** [link](https://www.typescriptlang.org/play/#code/MYewdgzgLgBATgUwIYBNwBsCeB5ARgKwC4YBveZNMLGABzhBuLAFcBbXBOGAXxgF5SteoxgAGHgFgAUAHoZ5VBhwEAdHQb8YARhhyYnenGIBhJGDAhYSCBACWAczAwoIGAHJ1NNzA7AkzCAQYW1hbCBgkBRQAWiUhBk4oTBUACgAmAFYAFlEASmlQSFgQAmIyTyY2Di5eAURFKmV8AG5pEvw1YU0tVqkgA)

**Code**
```ts
const readonlyObj: { readonly prop: number } = { prop: 0 }
// readonlyObj.prop = 1 // error: Cannot assign to 'prop' because it is a read-only property.(2540)
const obj: { prop: number } = readonlyObj;
obj.prop = 1;
```

**Closed** 2020-07-04 03:30 UTC
