### ISSUE TITLE
Resolution of @types packages only works with Node-style resolution

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#9831] opened 2016-07-19 23:05 UTC
While it makes sense conceptually, the ideal experience doesn't work out of the box with AMD. We should discuss whether a behavior change makes sense here.

**Comment by mhegazy** [comment] 2016-08-16 23:07
We need to refactor the module resolution code to repeat the resolution process if it failed under moduleResolution==Classic and only look under `node_modules\@types`.

**Comment by mhegazy** [comment] 2016-09-29 05:07
Duplicate of https://github.com/Microsoft/TypeScript/issues/11103

**Closed by mhegazy** 2016-09-29 05:07 UTC
Labels: @types, Bug
