### ISSUE TITLE
es2022 decorated class with static field initialization runtime error

### ISSUE THREAD

**Issue by salemebo** [microsoft/TypeScript#48818] opened 2022-04-23 10:58 UTC
# Bug Report

### 🔎 Search Terms

decorated class with static field initialization runtime error

### 🕗 Version & Regression Information

Typescript version 4.6.2
Target: ES2022
Module: ES2022 

- This changed between versions 4.5.5 and 4.6.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?useDefineForClassFields=true&downlevelIteration=true&removeComments=true&importHelpers=true&target=9&jsx=0&module=7&inlineSources=true&pretty=false&ts=4.6.2&ssl=11&ssc=3&pln=2&pc=1#code/FAMwrgdgxgLglgewgAgCYFMoIE4EMY4AUEuAtugFzIDOM2cEA5gJRW4QCeyA3sMstnQww2FIWbIAvAD5kWCNQQAbdADolCRsTLpmwAL7BgAAQxY8BbIQBEAI0G4A1tb1QluatWQAhB44DKMPjo5BAwPHz8NEHwUD5+-hyktspSyInJyqogRADk9uhOucwA3JH8tPhwcd4ASgCiAIIA0gD6AJIAcv4AKo2dAML1aQDytgBWmDDZgugAXujE6ADu8YUBMSHoYYS+64HBodN7ThkpSsyl5XJItNhgsEQADmC2StU0SedUZ8rM3IZ9CUgA)

### 💻 Code

```ts
function decorator(name: string): any {
  return () => console.log(name)
}

@decorator("break")
class BreakStatement {
    static BreakSymbol = Symbol.for('break');
    static BREAK_INSTANCE = Object.freeze(new BreakStatement(BreakStatement.BreakSymbol));
    constructor(public symbol: Symbol){}
};
```

### 🙁 Actual behavior

- compile successfully and print 'break' at runtime
- at run time 

![Screenshot from 2022-04-23 12-56-13](https://user-images.githubusercontent.com/7586302/164891667-9c0ed6f9-bef5-4c09-8a8a-99f552feb818.png)

### 🙂 Expected behavior

 no runtime error and print 'break'

execute  ` static BREAK_INSTANCE = Object.freeze(new BreakStatement(BreakStatement.BreakSymbol));`
after the decorator applied

OR 
execute decorator definition in the first static initialization block 

```js
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var BreakStatement_1;
function decorator(name) {
    return () => console.log(name);
}
let BreakStatement = BreakStatement_1 = class BreakStatement {
    static {
        BreakStatement_1 = __decorate([
            decorator("break"),
            __metadata("design:paramtypes", [Object])
        ], BreakStatement);
    }
    symbol;
    static BreakSymbol = Symbol.for('break');
    static BREAK_INSTANCE = Object.freeze(new BreakStatement_1(BreakStatement_1.BreakSymbol));
    constructor(symbol) {
        this.symbol = symbol;
    }
};

``` 
![Screenshot from 2022-04-23 12-57-31](https://user-images.githubusercontent.com/7586302/164891714-ea647146-f79a-478c-819c-b5e4702e99a0.png)

**Comment by MartinJohns** [comment] 2022-04-23 12:08
See #48814.

**Comment by MartinJohns** [comment] 2022-04-23 16:52
Sounds like a duplicate of #44908.

**Comment by salemebo** [comment] 2022-04-23 18:20
sorry for the duplication
> Sounds like a duplicate of #44908.
>
sorry for the duplication
 
> But good news: Since the decorators proposal recently hit stage 3, we might get actual support for decorators in TypeScript in one of the next versions.

yes it is a good news

**Comment by andrewbranch** [comment] 2022-04-25 18:24
You probably want to set `useDefineForClassFields: false` or use a lower target. Related: #48814

**Comment by salemebo** [comment] 2022-04-26 09:35
no, this doesn't solve the problem 

[useDefineForClassFields: false](https://www.typescriptlang.org/play?downlevelIteration=true&removeComments=true&importHelpers=true&target=9&jsx=0&module=7&inlineSources=true&pretty=false&ts=4.6.2&useDefineForClassFields=false#code/FAMwrgdgxgLglgewgAgCYFMoIE4EMY4AUEuAtugFzIDOM2cEA5gJRW4QCeyA3sMstnQww2FIWbIAvAD5kWCNQQAbdADolCRsTLpmwAL7BgAAQxY8BbIQBEAI0G4A1tb1QluatWQAhB44DKMPjo5BAwPHz8NEHwUD5+-hyktspSyInJyqogRADk9uhOucwA3JH8tPhwcd4ASgCiAIIA0gD6AJIAcv4AKo2dAML1aQDytgBWmDDZgugAXujE6ADu8YUBMSHoYYS+64HBodN7ThkpSsyl5XJItNhgsEQADmC2StU0SedUZ8rM3IZDEA)

it didn't solve the problem

![Screenshot from 2022-04-26 11-30-57](https://user-images.githubusercontent.com/7586302/165269623-e622f791-2264-4a03-8429-bf440766ba69.png)

the 'static initialization blocks' is running before define `BreakStatement_1`

**Comment by salemebo** [comment] 2022-04-26 09:50
- you can't apply the decorators after executing the `static initialization blocks`, that will mean you have an old code still runnig before appliying the decorators

let assume that an decorator 'logger' is applied on method

```ts
function logger(target: any, propertyKey: string, descriptor: PropertyDescriptor) {
  const original = descriptor.value;

  descriptor.value = function (...args: any) {
    console.log('params: ', ...args);
    const result = original.call(this, ...args);
    console.log('result: ', result);
    return result;
  }
}

class Foo {
  static instance = new Foo('instance');
  static {
    // logger is not applied yet
    console.log('instance 4 + 6 = ', Foo.instance.add(4,6));
  }
  constructor(private name: string){}
  @logger
  add(x: number, y:number ) {
    console.log('name', this.name);
    return x + y;
  }
}

const foo = new Foo('foo');

console.log('instance 4 + 1 = ', Foo.instance.add(4,1)); // run normal as expected, after apply the MethodDecorator
console.log('foo 1 + 2 = ', Foo.instance.add(1,2)); // run normal as expected, after apply the MethodDecorator

```
[@logger Playground Link](https://www.typescriptlang.org/play?target=9&module=7#code/FAMwrgdgxgLglgewgAgDYIOYYKYCcAUMAhrjjAFzJEQCeANMgA64KN4w0DS2NlAzjFxwIGBgBNsfKEMYwEuSgAUWbXBwAik6XFnyAlMgDewZMihIByeXAzCiqZAF5kEqTLm4AdADd7YbADcwCYuWu7yPn7YTsjg0PBIyPieKSQYfJTUNAbGpqbmEHwIqNie6Bj4AOSMJEQAthnIlQwpnml8ekF5ZhYwyLiSYKh9zta2EPaeUPaohAAWcHwtqaQdXXkFRSVlmFUDfEMUTQz7h50hpgMwYLgop8PrAL7Az8BQqER8fMgAYggIRhCAiI8CgyGEwOg0WcEGwAHdfv98OdTMDQYDugB6TFoTA4XDg74QBB9IiMRioODYMTIGjYGAXHqFYqlcpVCHEKHIAAsyAA1MgAGwxZqIhCeDnUKClIhiMT4bl0QV6FHIZ6mAAC5XxIVl8oAHpQIGA6gAjPAMXjGs14ZA5RlXG4ofX82lPF7BTZ9ED-GKwhF-BDIoJvCwsnYVSqSrm8gUARhFDEDEsKnOlbTlCrocZVAWQ2P6kGQxNwdXsVG+2H1bFg1IYRBAMFtZIpNGQMDm0QAsvS5ggxJpzLgQfJQ8ztmzKj6AQmBQAmRNilOQ9N6-Bxuhz3P5nG4IslssOT7IKs1ptieuN5vk1Btjvd3v9wfyEe4YJAA)

![Screenshot from 2022-04-26 11-50-00](https://user-images.githubusercontent.com/7586302/165273345-fea01f9b-f795-4e13-bfd7-e62c891d2280.png)

**Comment by fatcerberus** [comment] 2022-04-26 17:39
Your playgrounds all have `target` set to ES3.  Any higher target seems to work.

**Closed** 2022-04-29 18:00 UTC
Labels: Duplicate

**Comment by andrewbranch** [comment] 2022-05-02 17:50
> Not sure why this confuses Andrew

It’s more of a sad face at the playground bug
