### ISSUE TITLE
Resolving contextual `this` type in object like a class declaration

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#5817] opened 2015-11-28 11:20 UTC
Graceful type inference proposal.

```ts
var o = {
  method() {
    this; // `this` is `o` object
  },
  anon: function () {
    this; // `this` is `o` object
  }
};
```

**Comment by mydiscogr** [comment] 2015-11-28 19:21
+1
I Agree with you, I've post this proposal, but I dunno why is dissapear, such declaration correct some issues... and for me the current "traspiling" of a class is wrong... (for me)
so give a look here https://github.com/mydiscogr/jscontextproblem this is the demostration that current implementation is bugus :) and seems to there's not an hack to avoid such porblem

**Comment by DanielRosenwasser** [comment] 2015-11-28 19:58
I think this is partially a duplicate of #3694 (see "Functions and 'this'").

**Comment by falsandtru** [comment] 2015-11-28 21:07
I agree. Should I merge into #3694 ?

**Comment by mhegazy** [comment] 2015-12-01 19:32
@falsandtru please post that comment in #3694.

**Closed by mhegazy** 2015-12-01 19:32 UTC
Labels: Duplicate

**Comment by falsandtru** [comment] 2015-12-03 08:58
All right, thanks.
