### ISSUE TITLE
a const type can be unlocked in a seemingly simple way

### ISSUE THREAD

**Issue by troywweber7** [microsoft/TypeScript#51360] opened 2022-10-31 17:42 UTC
# Bug Report

If you have a type asserted as a const, you can assign it to much wider type with writable properties which allows you to mutate the original type.

### 🔎 Search Terms

"const assertion unlock"  or "const assertion reassigned"

### 🕗 Version & Regression Information

Not sure which version this started in. Just something I noticed today. Perhaps whatever version introduced the "const" keyword.

Also, could not find an answer in FAQs. Code snippet below shows errors exists in nightly.

Please keep and fill in the line that best applies:
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "const"

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20221025#code/JYOwLgpgTgZghgYwgAgDIHt0GcIBUCeADigN4BQylyhU6hAXMlmFKAOYDcZAvmWQuhDNkAoWADyAIwBWEBGGQBeZCWq0GyAOQALCABs96Tcm7I4WEYOZcyAelvIAkgpgR9FvcADWKMLuQw6AboAO7sTNroAK56ACbIIOgKkihwwSEQsXYOMFEg8sCCaXr4TMRwXuwANMhgRBDoMMgAtvgExMjAFqpQEHCxgiUt+AAK6ow6wMa8osJ5hgg+sVKy8owY2Hj1SpZiK3JgXPPoi5n78gB0NHQ7mmyYsZL4EJo29sjSUcKiMMBQzRY-F1kCFzJ0QLE3PFmlEwHBIFlZkEIBdDGwABSzCQyA4ASg4QA)

### 💻 Code

```ts
interface LooseType {
    prop: string;
}

const constObject = { prop: 'hello' } as const;

// It feels like the following should not be allowed
// functionally speaking, typeof myType is { readonly myProp: 'hi' }
const unlockedObject: LooseType = constObject;
unlockedObject.prop = 'goodbye';

// just confirms this was indeed mutated
console.log(constObject);
```

### 🙁 Actual behavior

I'm able to assign to an asserted const to a non-readonly, broader type and then mutate the property on the broader type, therefore mutating the original type.

### 🙂 Expected behavior

I should not be able to reassign const unless it is functionally identical. This line should not be possible:

```ts
const unlockedObject: LooseType = constObject;
```

Unless `LooseType` is defined as follows:

```ts
interface LooseType {
    readonly prop: 'hi';
}
```

UPDATE: edited code example to use clearer constant and interface names and help avoid confusion.
UPDATE 2: forgot to remove comment entirely, lead to missing information

**Comment by fatcerberus** [comment] 2022-10-31 18:42
Partial duplicate of https://github.com/microsoft/TypeScript/issues/13347 (I say “partial” because the part about `{ foo: 42 }` being assignable to `{ foo: number }` is definitely by design—the type system basically pretends non-local mutation doesn’t happen).

**Comment by troywweber7** [comment] 2022-10-31 18:58
@fatcerberus in my opinion, `{ foo: 42 }` should be assignable to `{ foo: number }`. `{ foo: 42 as const }` should not be assignable to `{ foo: number }`.

**Comment by fatcerberus** [comment] 2022-10-31 18:59
@troywweber7 Yes, that’s #13347.

**Comment by troywweber7** [comment] 2022-10-31 20:05
@fatcerberus @RyanCavanaugh if addressing #13347 will result in this issue going away with it, then I'm okay with that.

**Comment by fatcerberus** [comment] 2022-10-31 20:14
This issue is the same as 13347: `{ readonly foo: T }` is assignable to `{ foo: T }`.  There’s nothing special about `as const` in that regard—it just tells TS to infer a narrower type with `readonly` properties.

**Closed** 2022-11-03 18:00 UTC
Labels: Duplicate
