### ISSUE TITLE
[BUG REPORT] [Please Close this] Typescript breaks with conditional branching if an text gets converted into an array

### ISSUE THREAD

**Issue by Autumnlight02** [microsoft/TypeScript#47605] opened 2022-01-26 00:48 UTC
# Bug Report

#Solved

my grasp of TS wasn't good enough to solve it. Sorry for the inconvenience!

 What search terms did you use when trying to find an existing bug report?
 List them here so people in the future can find this one more easily.
 Array, Conditional branching, If statements

When did you start seeing this bug occur?
Version 4.6.0

### ⏯ Playground Link
https://www.typescriptlang.org/play?ts=4.6.0-dev.20220116#code/JYOwLgpgTgZghgYwgAkgZzARmQbwLABQyyAJgPYC2AKgJ4AOEAXMgEQCiANhBROCwNyFi5Cp268wzMT3CCipOGDjMcAXznEEAC2AcSUXswAU6LMgA+qCBgBMASgDaAXTmrChUJFiIUpm7iFSSloGZhYqCAAPMAFAkWkJZgjo13cCAHp05ABhMhIUAHcyKABrNGQAKwBXDGQYUEKtXiDqehRgcpAyMGQ4EF6oKDgaZAAjKp64ZAwoUABzNJgqkAQwYDJ+0yMyUYrmU2xLPzsA+WAYZG3dgDoREJQAXifWBL4T-HliHYrbyleeh5BBBVGRga4IAyKCD-IwsUwsOwaYjIBAbNBkLjXDhkOZXH4kRRwRGBYgwYqXLg9YDIQEABn4yGpAB5kN9wTo9AYQFjeHMwFoGcAANRC94k5FbNnaXT6XgOYBOYmfZBueSqZAQDhodoXPG-VoMGnPcJRGJi5XkYGg8GQyDJMAAOTyEFh8KVxFVqrSnmg8CQVgwmAA+uM5qdhME2swHOwuKCWC44n844lkP8kQSlCp1IFpZzDJcDiGqmGjtYwDZi3NHImCF6CD7vP6-FXwy17tGTdEExnk+JwElTakCIRMsgAJI9UaQsrIApNfrAMDlVEgABu0EgJEZ4DIvX6AEFBsM58ASPzSBB6iAINuAMqaiCrdYgRbLZ8bANgKt4qv7cvBqGFhfpWobmsQ5yXN8Vb6vcDi0k4RqArG-Zmm2Xy7DB8QpuANJAiCEg2hAUIwnC5YIkixDiqu6KYtiuLQaGtyEu6yJklAFIQFSeH0oyyAsoxJbsjKXI8iAfICoyIrgcixCSphTF5rKIDyoqlEqoE6qatqjK6oJcywW08GIU8yH2gi6H4daELEXappOvkrrkaxnqEEAA

The code: 
```ts
interface test1 {
  domType: "Element";
  domElement: Element;
  data: {};
  children: (test1 | test2)[];
}

interface test2 {
  domType: "Text";
  domElement: Text;
}

// Code works just fine when domType is not an array but a string

function test(obj: test1 | test2) {
  if (obj.domType === "Element") {
    obj.domElement = document.createElement("test");
    console.log(obj.data);
    for (let i = 0; i < obj.children.length; i++) {
      test(obj.children[i]);
    }
  } else if (obj.domType === "Text") {
    document.createTextNode("test");
  }
}


interface test1_bug {
  domType: ["Element"];
  domElement: Element;
  data: {};
  children: (test1_bug | test2_bug)[];
}

interface test2_bug {
  domType: ["Text"];
  domElement: Text;
}

// It breaks when its converted into an Array width defined Selection

function test_bug(obj_bug: test1_bug | test2_bug) {
  if (obj_bug.domType[0] === "Element") {
    obj_bug.domElement = document.createElement("test");
    console.log(obj_bug.data);
    for (let i = 0; i < obj_bug.children.length; i++) {
      test(obj_bug.children[i]);
    }
  } else if (obj_bug.domType[0] === "Text") {
    document.createTextNode("test");
  }
}
```

### 🙁 Actual behavior

When I put the domType into a predefined array Typescript doesn't run the if statements in the function correctly. It only works if its a string

### 🙂 Expected behavior

There shouldnt be a difference if 
type: "Element" 
Or
type: ["Element"]

Both should work the same since its a predefined and Required Array

Edit, fix suggested by @ajitjha393

**Comment by ajitjha393** [comment] 2022-01-26 07:32
@Autumnlight02 
![image](https://user-images.githubusercontent.com/42679346/151120774-83b0c72b-2a9d-41ed-b6c7-06cd0e1caddf.png)

There was typo in accessing the "data" from the interface 
You have named it as "data_bug"

[Playground link with Updated change ](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220116#code/JYOwLgpgTgZghgYwgAkgZzARmQbwLABQyyAJgPYC2AKgJ4AOEAXMgEQCiANhBROCwNyFi5Cp268wzMT3CCipOGDjMcAXznEEAC2AcSUXswAU6LMgA+qCBgBMASgDaAXTmrChUJFiIUpm7iFSSloGZhYqCAAPMAFAkWkJZgjo13cCAHp05ABhMhIUAHcyKABrNGQAKwBXDGQYUEKtXiDqehRgcpAyMGQ4EF6oKDgaZAAjKp64ZAwoUABzNJgqkAQwYDJ+0yMyUYrmU2xLPzsA+WAYZG3dgDoREJQAXifWBL4T-HliHYrbyleeh5BBBVGRga4IAyKCD-IwsUwsOwaYjIBAbNBkLjXDhkOZXH4kRRwRGBYgwYqXLg9YDIQEABn4yGpAB5kN9wTo9AYQFjeHMwFoGcAANRC94k5FbNnaXT6XgOYBOYmfZBueSqZAQDhodoXPG-VoMGnPcJRGJi5XkYGg8GQyDJMAAOTyEFh8KVxFVqrSnmg8CQVgwmAA+uM5qdhME2swHOwuKCWC44n844lkP8kQSlCp1IFpZzDJcDiGqmGjtYwDZi3NHImCF6CD7vP6-FXwy17tGTdEExnk+JwElTakCIRMsgAJI9UaQsrIApNfrAMDlVEgABu0EgJEZ4DIvX6AEFBsM58ASPzSBB6iAINuAMqaiCrdYgRbLZ8bANgKt4qv7cvBqGFhfpWobmsQ5yXN8Vb6vcDi0k4RqArG-Zmm2Xy7DB8QpuANJAiCEg2hAUIwnC5YIkixDiqu6KYtiuLQaGtyEu6yJklAFIQFSeH0oyyAsoxJbsjKXI8iAfICoyIrgcixCSphTF5rKIDyoqlEqoE6qatqjK6oJcywW08GIU8yH2gi6H4daELEXappOvkrrkaxnqEEAA)

**Comment by ajitjha393** [comment] 2022-01-26 09:19
Typescript at the moment, only supports type guards which work only one level of depth
Hence when you are accessing obj_bug.domType[0]  // `Depth => 2`

Hence the inference fails, this is how the tsc compiler works 
Not a bug! 
In order to achieve this functionality, you can create your own type guard like this to solve your problem

```ts
const getType = (x: test1_bug | test2_bug): x is test1_bug => x.domType[0] === 'Element'
```

![image](https://user-images.githubusercontent.com/42679346/151135963-cdb92920-9cd4-4c72-a591-94a04679432d.png)


[Link to Playground](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220116#code/JYOwLgpgTgZghgYwgAkgZzARmQbwLABQyyAJgPYC2AKgJ4AOEAXMgEQCiANhBROCwNyFi5Cp268wzMT3CCipOGDjMcAXznEEAC2AcSUXswAU6LMgA+qCBgBMASgDaAXTmrChUJFiIUpm7iFSSloGZhYqCAAPMAFAkWkJZgjo13cCAHp05ABhMhIUAHcyKABrNGQAKwBXDGQYUEKtXiDqehRgcpAyMGQ4EF6oKDgaZAAjKp64ZAwoUABzNJgqkAQwYDJ+0yMyUYrmU2xLPzsA+WAYZG3dgDoREJQAXifWBL4T-HliHYrbyleeh5BBBVGRga4IAyKCD-IwsUwsOwaYjIBAbNBkLjXDhkOZXH4kRRwRGBYgwYqXLg9YDIQEABn4yGpAB5kN9wTo9AYQFjeHMwFoGcAANRC94k5FbNnaXT6XgOYBOYmfZBueSqZAQDhodoXPG-VoMGnPcJRGJi5XkYGg8GQyDJMAAOTyEFh8KVxFVqrSnmg8CQVgwmAA+uM5qdhME2swHOwuKCWC44n844lkP8kQSlCp1IFpZzDJcDiGqmGjtYwDZi3NHImCF6CD7vP6-FXwy17tGTdEExnk+JwElTakCIRMsgAJI9ADqxTKyAAClAyAwoBwRl0CshFstVutNuWq3iq-ty8HQxYAxWq+biOdLnMIGB7kfQ3Yb8jvlX9f8aUCQRIbQgKEYThcsESRYhxVREB0UxbFcU-UNbkJd1kTJKAKUfRlf3pbCWUQkt2RlLkeRAPkBUZEV32RS9DwIuYiPzEB5UVCCVUCdVNW1RldXo-V7gcWknCNQEuzNNsIytACISAu1TSdfJXTA1DPTSaDagfJ82l-IxIhPQNWzLWxr2YSJGXKItzweAA+ZBIn4tpBOEp5AQAcn+VygA)

**Comment by Autumnlight02** [comment] 2022-01-26 09:52
Thank you and sorry for reporting it as a wrong bug, I'm new to ts and thought that this is a strange behavior, I was not aware that this is a current limitation by the engine. Now I got a better grasp of ts!

**Comment by ajitjha393** [comment] 2022-01-26 10:06
Hey It's totally fine, we all learn by experimenting!
All the best :)

**Comment by fatcerberus** [comment] 2022-01-26 15:30
@Autumnlight02 You know you can close the issue yourself, right?

**Closed** 2022-01-26 21:57 UTC
Labels: Question

**Comment by Autumnlight02** [comment] 2022-01-27 08:51
@fatcerberus Did not know that, thank you for that info!
@ajitjha393 Sorry for bothering you again, but how would I convert that into a switch statement check? I could build more functions and run them with if-else but I am unsure if that's the best approach with it.

**Comment by fatcerberus** [comment] 2022-01-27 09:03
If you’re using switch statements you really want to have a discriminated union — which is what you had when `domType` was a string literal.  Using type predicates would be really inconvenient for that use case.

**Comment by Autumnlight02** [comment] 2022-01-27 09:14
Ohh okay, i guess if Statements for the go then!

**Comment by ajitjha393** [comment] 2022-01-27 09:29
I totally agree with @fatcerberus 
Discriminated Union is the better approach for this use case!

As far as type guard inference depth limitation 
There is a library that allows you to overcome it up to any level of nesting

``` ts
import { pa, p } from '@sthir/predicate'

if(pa(obj_bug, p('.domType.0 === ', "Element"))) {
    // obj_bug will be inferred as test1_bug and so on 
}

 
``` 

Repo -> [sthir](https://github.com/devanshj/sthir)
