### ISSUE TITLE
Array optional chain prototype is undefined

### ISSUE THREAD

**Issue by kaysonwu** [microsoft/TypeScript#45958] opened 2021-09-19 09:12 UTC
# Bug Report

### 🔎 Search Terms

`Array.prototype.length`, `undefined`, `optional chaining`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about refinements

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.2#code/JYOwLgpgTgZghgYwgAgLIRAVwJKQLbIDeAUMmciHHhAFzIDOYUoA5gNynkIAWwANgBMoGAPx10WXBDwBtALocAvsWIIA9iEbJg+cRhz5kAXiIUqtZAHJM9aJeSKOqjVsLIe-IRgfHt+J8AwyAAUHoLCICIAdHwYLGDcyAB8yAAMAJREnGTqmmqxMWosobzhGOlKxEA)

### 💻 Code

```ts
interface MenuItem {
    name: string;
    children?: MenuItem[];
}

const item: MenuItem = { name: 'user' };

const { children } = item;

if (children?.length > 0) {
    console.log(children);
}
```

### 🙁 Actual behavior

Object is possibly 'undefined'

### 🙂 Expected behavior

No error

**Comment by MartinJohns** [comment] 2021-09-19 09:47
You get this error because you're trying to compare a potential `undefined` value with `0`. This is completely unrelated to the optional chaining.

    const num = Math.random() > 0.5 ? undefined : 1
    if (num > 0) {
        console.log(children);
    }

**Comment by kaysonwu** [comment] 2021-09-19 12:31
@MartinJohns I know, but I want to allow them to compare without reporting error.

**Comment by MartinJohns** [comment] 2021-09-19 16:18
You can remove the `undefined` type from the equation in several ways:

- Avoid it, by adding a check: `children && children.length > 0`
- Add a fallback value: `children?.length ?? 0 > 0`
- Add a type assertion: `children?.length as number > 0`
- Disable `strictNullChecks`.

Alternatively you could create a **feature request** to ask the TypeScript team to specifically support the pattern you use.

**Comment by jcalz** [comment] 2021-09-19 20:07
Feels like a duplicate of #45543 to me

**Closed** 2021-09-21 12:46 UTC
