### ISSUE TITLE
Symbol-named properties unable to be used as a discriminator

### ISSUE THREAD

**Issue by tcf909** [microsoft/TypeScript#43220] opened 2021-03-12 21:54 UTC
# Bug Report

Unable to use a symbol as an index for a discriminator.

### 🔎 Search Terms

symbol discriminator discriminated union

### 🕗 Version & Regression Information
4.2.2

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=37&ssc=2&pln=1&pc=1#code/KYOwrgtgBAogbqALgFQJ4AdhQN4CgpQDKqIAxgDT5QCCAziRVQPIBOAJsC8G5QL664OpADYBDLlFIB7ELURQ0mAFxQwIAJYBHMFnoQARlOEBuAepCJOAM1GksxMvCQ4qbUYlEq5LcwHNTBADaisAAuipOFiEAdA6kpvy45pYsNnY09I4IFi4Ebh5eiD4g-lTBGGER2SgV0XQMCWYW1rZYrBxcbJHyeHnunlDefgFQ5ZjhsNUx7ZzcjbhWaqSI6jJQbOq06O6kABYAFMBwiCpx3VAAPhkM51cznd0AlLmDAO7qiHuHx2Nhz70ESSiWhYboxOJKKiAyQyOSDBinG7VKAAXigR0QI2h+i4ogA1ligSDJkgYvUyJDoQRpLJ5MCSCpyaRzmiMYSCDjgPjCaRgaCprV7txKYCODYwMITlDATS4VJ2CohV1kazjuyoJzuVR+LwgA)

### 💻 Code

```ts
enum EventType {
  Sync,
  Async,
  Ordered,
}

declare const Type: unique symbol;

interface SyncEvent {
  data: string;
  [Type]: EventType.Sync;
}

interface AsyncEvent {
  data: string;
  [Type]: EventType.Async;
}

interface OrderedEvent {
  data: string;
  [Type]: EventType.Ordered;
}

function dispatch(evt: SyncEvent | AsyncEvent | OrderedEvent) {
  switch(evt[Type]) {
    case EventType.Sync:
      const sync: SyncEvent = evt;
      break;
    case EventType.Async:
      const asyn: AsyncEvent = evt;
      break;
    case EventType.Ordered:
    default:
      const ord: OrderedEvent = evt;
      break;
  }
}
```

### 🙁 Actual behavior

No discrimination happens.

### 🙂 Expected behavior

Discrimination.

**Comment by DanielRosenwasser** [comment] 2021-03-12 23:56
I think this is a duplicate of #10530.

**Closed** 2021-03-15 18:00 UTC
Labels: Duplicate
