### ISSUE TITLE
No error accessing non-existent method on string with strictNullChecks on

### ISSUE THREAD

**Issue by steadicat** [Microsoft/TypeScript#26426] opened 2018-08-13 21:50 UTC
**TypeScript Version:**  3.0.1

**Search Terms:** strictNullChecks, inferred any, no error, parameter, argument, implicit any, property does not exist

**Code**

```ts
function getString(required: {}): string {
  return '';
}

function functionThatReturnsAString() {
  const optional: {} | null = null;
  return getString(optional);
}

const s = functionThatReturnsAString(); // s is correctly inferred as 'string'
s.foo(); // no error?
```

**Expected behavior:**

Expected to get error `Property 'foo' does not exist on type 'string'` on the last line.

**Actual behavior:**

No error on the last line.

With all the strict settings on, there's a different error on the argument to the `getString` call, but that should not affect the return type of `functionThatReturnsAString`. The function could be in a completely separate part of the codebase. Inspecting that should not be required when trying to debug the `s.foo()` call.

**Playground Link:**  https://www.typescriptlang.org/play/#src=function%20getString(required%3A%20%7B%7D)%20%7B%0D%0A%20%20return%20''%3B%0D%0A%7D%0D%0A%0D%0Afunction%20functionThatReturnsAString()%20%7B%0D%0A%20%20const%20optional%3A%20%7B%7D%20%7C%20null%20%3D%20null%3B%0D%0A%20%20return%20getString(optional)%3B%0D%0A%7D%0D%0A%0D%0Aconst%20s%20%3D%20functionThatReturnsAString()%3B%0D%0As.foo()%3B%0D%0A

Tested with all strict options on. (Note that Playground has been finnicky today.)

**Related Issues:**

**Comment by andy-ms** [comment] 2018-08-13 22:41
I believe this is because of this line in `checker.ts`:
`return produceDiagnostics || !args ? resolveErrorCall(node) : getCandidateForOverloadFailure(node, candidates, args, !!candidatesOutArray);`

If `produceDiagnostics` is true, we just return `anySignature` (from `resolveErrorCall`) and don't get downstream errors. But if not, we get the best candidate we can (which happens to be the only one). Maybe we could just always `getCandiateForOverloadFailure`?

**Comment by andy-ms** [comment] 2018-08-30 17:26
That PR didn't fix this, the line I pointed out still exists.

**Comment by sheetalkamat** [comment] 2018-08-30 17:34
But I see error reported by running tsc as well as from language service so its fixed?

**Comment by andy-ms** [comment] 2018-08-30 17:49
![s_string](https://user-images.githubusercontent.com/19274678/44869393-56ddde00-ac42-11e8-94c6-2151bd195749.jpg)

We get `s: string`, but there's no compile error when calling a method that doesn't exist on `string` -- because the diagnostics-producing TypeChecker has different behavior than the one used for services.

**Comment by sheetalkamat** [comment] 2018-08-31 17:54
![image](https://user-images.githubusercontent.com/8052792/44928263-3c703700-ad0c-11e8-8c76-1715974438c8.png)

**Comment by andy-ms** [comment] 2018-09-04 16:05
@sheetalkamat You probably don't have `strictNullChecks` enabled since `getString(optional)` should be an error.

**Comment by andy-ms** [comment] 2018-09-04 18:16
Duplicate of #19686 .

**Closed by andy-ms** 2018-09-04 18:16 UTC
Labels: Bug
