### ISSUE TITLE
[salsa] [jsdoc] Support for doted properties type assignment in destructive parameters. 

### ISSUE THREAD

**Issue by michaeljota** [Microsoft/TypeScript#15553] opened 2017-05-03 13:57 UTC
**TypeScript Version:**  2.2.2 (VSCode integrated)

**Code**

```js
/** Some description
 *
 * @param {PropsType} props The props of the component.
 * @param {string} props.one One property of the props.
 * @param {number} props.two Another property of the props.
 * @return {JSX.Element} A ReactElement.
 */
const SomeReactElement = ({ one, two }) => (
  <div>
    // `one` and `two` should be `string` and `number`, but they are `any`.
  </div>
);
```

**Expected behavior:**

Destructive parameters should retain type declaration in JSDoc tags

**Actual behavior:**

Destructive parameters lose the type definition, and are being declared as `any`

**Comment by mhegazy** [comment] 2017-05-03 23:28
Duplicate of https://github.com/Microsoft/TypeScript/issues/11597

**Comment by mhegazy** [comment] 2017-05-19 16:47
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-05-19 16:47 UTC
Labels: Duplicate
