### ISSUE TITLE
Extending a class of an imported script (<script>) that is typed with TS Defs looses the parameters in the overridden method

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#26886] opened 2018-09-04 20:58 UTC
_From @enjikaka on August 28, 2018 8:33_

 

- VSCode Version: Version 1.26.1 (1.26.1)
- OS Version: macOS 10.13.4 (17E199)

Steps to Reproduce:

Reproducible setup and steps here -> https://github.com/enjikaka/type-fail-params-vscode

_Copied from original issue: Microsoft/vscode#57339_

**Comment by andy-ms** [comment] 2018-09-04 21:08
Duplicate of #23911 -- currently we won't inherit parameter types from a superclass.

**Closed** 2018-09-19 23:49 UTC
Labels: Duplicate
