### ISSUE TITLE
Array of functions return types not combined

### ISSUE THREAD

**Issue by tsu-complete** [microsoft/TypeScript#19508] opened 2017-10-26 21:04 UTC
**TypeScript Version:**  2.5.3

**Code**

```ts
// This code compiles successfully
function test_direct <A> (args: Iterable<A>): Array<A> {
  return Array.slice.call(args);
}
function test_fn <A> (args: Iterable<( ) => A>): Array<A> {
  return Array.slice.call(args).map(invoke);
}
```

**Expected behavior:**

```ts
// Compiles, type is Array<number|string>
test_direct([1, "1"]);

// Compiles, type is Array<number,string>
test_fn([( ): number => 1, ( ): string => "1"]);
```

**Actual behavior:**

```ts
// Fails, `((()=>number) | (()=>string))[]` is not assignable to parameter of type `Iterable<() => number`
// Looks like it only takes the first, and expects the rest to be the same
test_fn([( ): number => 1, ( ): string => "1"]); 

// Confirmed as this works
test_fn([( ): number => 1, ( ): number => 2]); 
// And so does this (which is possible to circumvent the problem but needlessly verbose)
test_fn<number|string>([( ): number => 1, ( ): string => "1"]);
```

**Comment by mhegazy** [comment] 2017-10-26 21:10
@ahejlsberg has a fix for this one.

**Comment by RyanCavanaugh** [comment] 2018-08-22 20:40
@tsu-complete can you provide a self-contained repro or verify that the issue is now fixed? Thanks!

**Comment by RyanCavanaugh** [comment] 2021-12-16 00:30
This is the intended behavior

**Closed by RyanCavanaugh** 2021-12-16 00:30 UTC
Labels: Working as Intended
