### ISSUE TITLE
Allow rest parameter may not be the last one.

### ISSUE THREAD

**Issue by heroboy** [Microsoft/TypeScript#4437] opened 2015-08-25 06:51 UTC
For example, a function takes any number of parameters and return the last one.
```
function GetLastOne<T>(...rest:any[], last:T)
{
    return last;
}
```
and this: http://createjs.com/docs/easeljs/classes/Container.html#method_addChild

**Comment by kitsonk** [comment] 2015-08-25 08:00
That is not valid ES6, therefore I suspect the TypeScript team will not be interested in implementing it.  Even then it is tricky...  The clue is in the name (*rest*) as in: "the *rest* of the arguments".  How would you propose to deal with:

```typescript
GetLastOne(undefined, undefined);
/* or */
GetLastOne(1, 2, undefined);
/* or depending on what you would suggest to emit this */
GetLastOne(undefined, 1, undefined, 2);
```

**Comment by heroboy** [comment] 2015-08-26 01:54
I want this because I want a strong typed way to declare a function like http://createjs.com/docs/easeljs/classes/Container.html#method_addChild .
```
GetLastOne(undefined, undefined);
/* or */
GetLastOne(1, 2, undefined);
/* or depending on what you would suggest to emit this */
GetLastOne(undefined, 1, undefined, 2);
```
And what's the problem with the codes?
for the 1st and 2nd the type `T` is `undefined`,and `last` is `undefined`.
I think `GetLastOne` can emit like this:
```
//function GetLastOne<T,U>(first:U,...rest:any[], last:T)
function GetLastOne()
{
    var first = arguments[0];
    var rest = [];
    for(var i=1;i<arguments.length-1;++i)
        rest.push(arguments[i]);
    var last = arguments[arguments.length-1];
}
```

**Comment by danquirk** [comment] 2015-09-10 19:30
@heroboy  Beyond the issues mentioned I'm not sure I understand why you need this feature for ```addChild```. The signature should just be:
```ts
interface Container {
    addChild(child: DisplayObject): DisplayObject;
    addChild(...children: DisplayObject[]): DisplayObject;
}
```
That the implementation of the second overload returns ```children[children.length-1]``` (as opposed to any other element of ```children```) is not something that is encoded in the type system.

**Comment by danquirk** [comment] 2015-09-10 19:32
In any case, this is a duplicate of https://github.com/Microsoft/TypeScript/issues/1360

**Closed by danquirk** 2015-09-10 19:32 UTC

**Comment by heroboy** [comment] 2015-09-11 03:56
@danquirk Because I want
```
container.addChild(new Text()).text = "xxxx";
```
not
```
(<Text>container.addChild(new Text())).text = "xxxx";
```

**Comment by danquirk** [comment] 2015-09-11 19:47
Then you just need a generic declaration of ```addChild```:

```ts
interface DisplayObject {
		name: string;
	}
	
	class Text implements DisplayObject {
		name: string;
		text: string;
	}
	
	interface Container {
	    addChild<T extends DisplayObject>(child: T): T;
	    addChild<T extends DisplayObject>(...children: T[]): T;
	}
	
	var c: Container;
	var r = c.addChild(new Text()).text;
    var r2 = c.addChild(new Text(), new Text()).name;
```

**Comment by heroboy** [comment] 2015-09-12 02:13
```typescript
class Shape implements DisplayObject {
    name:string;
}
//then this is not allowed.
c.addChild(new Shape(), new Text()).text = "xxx";
```
