### ISSUE TITLE
Color Names

### ISSUE THREAD

**Issue by BobFrGit** [Microsoft/TypeScript#4769] opened 2015-09-13 23:49 UTC
Typing color names is risky since there is no checking for typos. It would be nice to have named colors as in Color.Wheat or something like that. Even nice would be to type a field like backgroundColor typechecked as an HTML color though I'm not sure how to do that while keeping fully compatible with JS.

For an application that had only a limited number of valid colors I created a static class
class Kolor {
    static black: string = "black";
    static silver: string = "silver";
    static gray: string = "gray";
..
}
it didn't solve the type checking but did reduce typos.

**Comment by eyalsk** [comment] 2015-09-14 03:05
You should use enum instead of a class for that where each member in the enum will have a numerical representation of the color instead of string, it's better for many reasons.

http://www.typescriptlang.org/Handbook#basic-types-enum

**Comment by BobFrGit** [comment] 2015-09-14 03:14
I do use enums but in this case the color names are string and I'm using them as strings. If I used an enum I'd have a more awkward syntax in converting to strings explicitly every time. (Were this C# I could get far fancier for better or worse).

**Comment by basarat** [comment] 2015-09-14 04:59
> I do use enums but in this case the color names are string and I'm using them as strings.

Here's what I've done commonly (taking advantage of TypeScript's type inference on assigment to infert the type of `colors`): 

```ts
let colors = {
   red : 'red',
   blue: 'blue',
  // so on
}
```

Now : 
```ts
colors.blue; // okay 
colors.invalid; // Error
```

**Comment by BobFrGit** [comment] 2015-09-14 06:01
Thanks. That's a reasonable solution. The only point I'm making is that this should part of the standard Typescript offering because it's so fundamental to doing HTML5.

**Comment by basarat** [comment] 2015-09-14 06:06
There is this issue : https://github.com/Microsoft/TypeScript/issues/3192

**Comment by danquirk** [comment] 2015-09-14 19:54
Yeah, dupe of the mentioned string enums issue.

**Closed by danquirk** 2015-09-14 19:54 UTC
