### ISSUE TITLE
lib.dom.d.ts: MediaDeviceInfo requires a toJSON property

### ISSUE THREAD

**Issue by hypetsch** [microsoft/TypeScript#36202] opened 2020-01-15 16:51 UTC
**TypeScript Version:** e.g. 3.7.2

```
let info: MediaDeviceInfo = {
    deviceId: 'fake',
    kind: 'audiooutput',
    groupId: '',
    label: 'audio.devices.all'
};
```

**Expected behavior:**
toJSON() should not be required

**Actual behavior:**
toJSON() is required to be defined

**Playground Link:**
https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=6&pc=3#code/AQGwpgLsCWB2BmB7AXMAsmAJtAhgETADdoBjMASQUWAF5gBvAKGBeEyNIs1QHJ4cA1mB4AaZqwFxuwHjgCu2RIjkQADitHiWAcwBOy1eWk9NrUDgBGYEL3mKAdO2JkAzvZwgQPRgF8A3EA

**Comment by IllusionMH** [comment] 2020-01-15 17:44
Looks like duplicate of #32727 but with different type. At least same root cause - face "native" objects that doesn't have exposed constructors.

Objects with `MediaDeviceInfo` that retrieved from actual browser API have `toJSON` method available and any consumer on `MediaDeviceInfo` can use this method.
IMHO if you create fake object you should either provide all required methods or just use `as MediaDeviceInfo` and hope that non of consumers will actually use non implemented methods/properties.

**Closed** 2020-02-11 00:00 UTC
Labels: Question
