### ISSUE TITLE
Destructing doesnt allow for discriminated union

### ISSUE THREAD

**Issue by maraisr** [microsoft/TypeScript#41644] opened 2020-11-23 08:59 UTC
**TypeScript Version:**  4.1.0-beta

**Code**
```ts
function generate(who: string): {json: true, body: {hello: string}} | {json: false, body: string} {
    return {json: true, body: {hello: who}}
}

const {body, json} = generate('world');

if (json) {
    body // should give you auto-complete, for `.hello`
} else {
    body // should be a string, thus giving `includes` as an example
}
```

**Issue**
As you'll find from the code example, `body` on line 8 doesnt autocomplete with `.hello`

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.1.0-beta#code/GYVwdgxgLglg9mABAcwKZlQJwIZVQCgHcALOALkQGcpMYxkBKCgbwCtKEKaRUAaRAEZwAJgE8WxVABsp5KjTrIAvksQAfRGw5gKwbFMp9BI8fNr1VzALAAoRPcSZUUEJiRbOibkaFiJ02QoSOBVbJVtbCARqTV9RfnYEVQBeFHQsXAIAckI4TClhLIYAbgibGGBEfESwBk1bB2MxRAB6FqpSEAKUGAA3VERROBBEbBAoOABaKIBbAAcpZyNgPMQAAwA6SRk4NbDEaUN6uwc41vbKTu6BAewzRX4oYhBKHt7FdboIKRBhVEo1qNXtgkKgAB7YeaLMJlIA)

**Comment by MartinJohns** [comment] 2020-11-23 09:29
Duplicate of #12184.

**Comment by maraisr** [comment] 2020-11-23 11:31
Sometimes issues are academic speak that I have no clue if it's even the same thing! Thanks for the "duplicate" advice, I shall subscribe to that issue. Maintainers feel free to close this perhaps.

**Closed** 2020-11-28 18:00 UTC
Labels: Duplicate
