### ISSUE TITLE
Catch on Promise of Array Results in never[] Type

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15413] opened 2017-04-27 17:00 UTC
**TypeScript Version:**  2.3.1 

**Code**

Using `lib: ["es6"]`

```ts
const z = Promise.resolve([1]).catch(() => {
    return []
});

z.then(array => array.map(x => x + 1))
```

**Expected behavior:**
The type of `z` should be `Promise<number[]>` and the above code should work.

**Actual behavior:**
The type of `z`is `Promise<number[] | never[]>`. This causes `array.map(x => x + 1)` to produce the cryptic error:

```
message: 'Cannot invoke an expression whose type lacks a call signature. Type '{ <U>(this: [number, number, number, number, number], callbackfn: (this: void, value: number, ind...' has no compatible call signatures.'
```

**Comment by mhegazy** [comment] 2017-10-25 22:41
Duplicate of https://github.com/Microsoft/TypeScript/issues/7294

**Comment by mhegazy** [comment] 2017-11-09 21:24
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-11-09 21:24 UTC
Labels: Duplicate
