### ISSUE TITLE
Error TS2339 with Shadow Dom

### ISSUE THREAD

**Issue by Cokser** [Microsoft/TypeScript#19028] opened 2017-10-09 11:34 UTC
**TypeScript Version:**  2.5.3
**Code:**
```ts

let tmpl = document.querySelector('template'),
  host = document.getElementById('host-container');

let myRoot = host.createShadowRoot();

myRoot.appendChild(document.importNode(tmpl.content, true));
```
**console:**
   `: error TS2339: Property 'createShadowRoot' does not exist on type 'HTMLElement'.`

when i change main.ts >> main.js
Everything works fine, that's reason why i make this topic.

_Maybe i did something wrong, so don't judge too hard :smile:_

**Comment by kitsonk** [comment] 2017-10-09 13:11
Duplicate of #10401

The [Shadow DOM](https://caniuse.com/#feat=shadowdom) currently has limited browser support, therefore it not included in the libraries included with TypeScript.  You will either have to create them yourself or acquire them somewhere.

**Comment by mhegazy** [comment] 2017-10-23 18:38
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-23 18:38 UTC
Labels: Duplicate

**Comment by CH-RhyMoore** [comment] 2018-01-25 00:36
What's your threshold for browser support that merits inclusion?

**Comment by morewry** [comment] 2018-01-25 00:37
What's your threshold for browser support that merits inclusion?

**Comment by mhegazy** [comment] 2018-01-25 03:58
We have lowered the bar recently to allow experimental APIs. That said I am hoping that we would get this for free the next time we update our drop of the edge’s webidl
