### ISSUE TITLE
Type predicate callbacks

### ISSUE THREAD

**Issue by roobscoob** [microsoft/TypeScript#47249] opened 2021-12-25 19:17 UTC
# Suggestion

## 🔍 Search Terms

"type predicate"

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

The following code does not function, though it can be expected to.
```ts
class ExtendedType {
    isExtended: this is ExtendedType { return true }
}

class BaseType {
    isExtended: this is ExtendedType { return false }
}

declare const array: BaseType[]

function takesCb<T extends BaseType>(cb: (arg: BaseType) => arg is T): T {
    for (let item of array) {
        if (cb(item)) return item;
    }
}

const extended = takesCb(t => t.isExtended());

// extended is expected to be of type ExtendedType
```
## 📃 Motivating Example

I'm building a client for a server, the client emits packets when received.
I have a base `ClientBoundPacket` class, which other packets extend.
all `ClientBoundPacket`s have methods that look like `packet.isKeepAlive()` for easily checking and casting their type.
A useful pattern is being able to call an async function and have it resolve when it receives a packet that passes a boolean check.
(e.g. check for a keep alive packet):
```ts
const packet = client.waitForPacket(packet => packet.isKeepAlive());

// packet should be of type ClientBoundKeepAlivePacket (packet.isKeepAlive() returns this is ClientBoundKeepAlivePacket)
```

## 💻 Use Cases

I wish for this to be implemented to extend the power of an already awesome tool, type predicates.

**Comment by roobscoob** [comment] 2021-12-25 19:22
To go into more detail here (re-reading, i noticed it was missed by accident) the core issue here is that in this code sample:
```ts
let cb = (t) => t.isXyz()
```

`cb` does not share the return type of `t.isXyz` (that is, `this is Xyz`) but rather `boolean`, which I feel is unexpected.

**Comment by MartinJohns** [comment] 2021-12-25 19:41
Duplicate of #38390.

**Closed** 2022-01-07 18:00 UTC
Labels: Duplicate
