### ISSUE TITLE
no error when comparing typeof to undefined or null

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#42090] opened 2020-12-23 16:18 UTC
# Bug Report

### 🔎 Search Terms

typeof undefined null 
### 🕗 Version & Regression Information
v4.2.0-dev.20201223

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `typeof`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201223#code/PTCmCdwe3AuACAKgCwJYGd4GMoDsAmqALqnvAO6oA2V8AhleXQJ6bihECu4u8A5ADMG6UH3jpUuLKHhFkMoswAOodAFgAUCD4AidEXCSA5jvgAfeDtycAtgCMIpizruojkok8t2oUKqDpcLz1mez9gzgJQAUlQfGCoOwArUCxPc0sBSLTSILFA-H4dOnR8AR0xZDoANxlcKHgoWvAqOiUAOk1FFSgBeEj8aNjCgF4x-hKyvk1NEHr4CGhwABoF2t45KE4jZFl5EWw8QhI8TEoaeip0BoYmVngHeCEr0Fgu5VBe-qiY3Dj4MYjb6DX5xd49PoDIZ-Ubjaw0IA)

### 💻 Code

```ts
//error: This condition will always return 'false' since the types
//'"string" | "number" | "bigint" | "boolean" | "symbol" | "undefined" | "object" | "function"' and '"asdf"' have no overlap.
typeof undefined === 'asdf'

//no error, even though these conditions will also always be false:
typeof undefined === undefined
typeof undefined === null
```

### 🙁 Actual behavior
no error when comparing `typeof undefined` to `null` or `undefined`

### 🙂 Expected behavior
"This condition will always return 'false'" error, as there is no overlap with the return type of `typeof` (which is `"string" | "number" | "bigint" | "boolean" | "symbol" | "undefined" | "object" | "function"`)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#Description

**Comment by MartinJohns** [comment] 2020-12-23 16:57
Duplicate of #29405 / #29200. Used search terms: `typeof undefined null in:title`

**Closed** 2020-12-23 20:03 UTC
Labels: Working as Intended
