### ISSUE TITLE
`ts2339` on union type with boolean guard does not work

### ISSUE THREAD

**Issue by Lonli-Lokli** [microsoft/TypeScript#53437] opened 2023-03-22 18:21 UTC
# Bug Report

### 🔎 Search Terms

union type function boolean 

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about

### ⏯ Playground Link

https://tsplay.dev/WJAeRm

### 💻 Code

```ts

type None = {
  isEmpty(): true;
  isNotEmpty(): false;
};

type Some<T> = {
  get(): T;
  isEmpty(): false;
  isNotEmpty(): true;
};

const None: None = {
  isEmpty: () => true,
  isNotEmpty: () => false
};

function Some<T>(value: T): Some<T> {
  return {
    get: () => value,
    isEmpty: () => false,
    isNotEmpty: () => true
  };
}

type Option<T> = Some<T> | None;
 

// Property 'get' does not exist on type 'Option<number>'.
//  Property 'get' does not exist on type 'None'.(2339)
const calculate = (state: Option<number>, item: number) => state.isNotEmpty() ? Some(state.get() + item) : Some(item);


```

### 🙁 Actual behavior

Property 'get' does not exist on type 'Option<number>'.
  Property 'get' does not exist on type 'None'.(2330)

### 🙂 Expected behavior

No error

**Comment by MartinJohns** [comment] 2023-03-22 18:27
Duplicate of #49771.

**Comment by Lonli-Lokli** [comment] 2023-03-22 19:03
@MartinJohns what search term did you use?!

**Comment by RyanCavanaugh** [comment] 2023-03-22 19:20
I want to know too 😅

**Closed** 2023-03-22 20:04 UTC
Labels: Duplicate

**Comment by IllusionMH** [comment] 2023-03-22 21:08
`union method guard`allows to find that issue (but I've checked link in @MartinJohns comment couple hours ago, so a bit of cheating)

**Comment by fatcerberus** [comment] 2023-03-22 21:41
I would never even have *thought* to try this.  The fact that there’s even a dupe just makes me go 🤯

**Comment by MartinJohns** [comment] 2023-03-22 21:47
@Lonli-Lokli @RyanCavanaugh This was slightly more cumbersome, my usual approach using `in:title` did not work. So I first tried `narrow union return label:"Working as Intended"` and had a quick glance over the closed issues, then tried the same with `label:Suggestion`. The linked issue was number 8.
