### ISSUE TITLE
callback inside generated object type doesn't allow implicit arguments types

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#30238] opened 2019-03-06 14:07 UTC
**TypeScript Version:**  3.4.0-dev.20190223

**Search Terms:**

**Code**

```ts
declare function x<T>(obj: T, args: {[P in keyof T]: (arg: number) => void}): void;
x({get: 1}, {get: arg => arg + 1});
// Parameter 'arg' implicitly has an 'any' type.
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by dragomirtitian** [comment] 2019-03-06 14:41
Just as a workaround you can do the following:

```
declare function x<T>(obj: T, args: Record<keyof T, (arg: number) => void> & Record<string, (arg: number) => void>): void;
x({ get: 1 }, { get: arg => arg + 1 });
```

`arg` would be correctly inferred but you will still get errors if the key was not in `T`.

**Comment by cevek** [comment] 2019-03-06 18:17
Yeah, but I want something more complex, this example just a repro
for example `arg` should be `ReturnType<T[P]>`

**Comment by yortus** [comment] 2019-03-07 00:44
Duplicate of #24694? There's a PR to fix it, to be discussed 'next week' on the [Design Meeting Docket](https://github.com/Microsoft/TypeScript/projects/9) - but I think it's been on 'next week' for quite a few weeks now.

**Closed** 2019-03-10 18:00 UTC
Labels: Duplicate
