### ISSUE TITLE
Shallow copy of Map class produce incorrect typings

### ISSUE THREAD

**Issue by bacebu4** [microsoft/TypeScript#59389] opened 2024-07-22 08:09 UTC
### 🔎 Search Terms

shallow copy, wrong shallow copy type, destructuring map class

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.3#code/MYewdgzgLgBAhjAvDMBTA7jAsnADgCgEoBuAKFElgCMkYBvAOibgF9zwIQAbVBrkAOb4qDAaiiEgA

### 💻 Code

```ts
const a = new Map();
const b = {...a}
console.log(b.get)
```

### 🙁 Actual behavior

According to types, `b.get` is defined, but it is actually `undefined`

### 🙂 Expected behavior

`b` should not have methods of `Map` class after shallow copying it

**Comment by MartinJohns** [comment] 2024-07-22 08:13
Duplicate of #53765. Used search terms: `spread map in:title`

**Closed** 2024-07-22 08:23 UTC
