### ISSUE TITLE
Switch allows case undefined: even when parameter cannot be undefined

### ISSUE THREAD

**Issue by krryan** [microsoft/TypeScript#60369] opened 2024-10-29 17:46 UTC
### 🔎 Search Terms

`switch case undefined`, `switch "case undefined:"`, `"case undefined:"`

Note, all of these result in a **lot** (100+ pages) of hits, so I haven’t gone through them all in detail. None of them appeared to match based on their titles, but it’s possible I’ve missed something.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `switch` (there are none)

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.0-dev.20241029#code/BQMw9mBCCGBOBcACAROMzEB8UCM7IEpEBeAPkQG8AoRWxAZwHcBLAFwGMALRUCGWItTrDE7aPQCmKNMng0RC2BNYBXWADtErWCokBueQrGTc+OQsXK1mkNAA2kgxcQB6F4gACregFoJADwAHCXZWP1hYMFhEZnV2KKVQuwBPRE5xRHUwRAkIqIAaBk4wFTsAExy86JwQ6BUTFXUyiRBYiQrmekywVkRxemYAc3VoHDspVmzUCAxsZDxYZEMRYylG5tb1dvNnOlZOSMZMiSOAUSrgZABJAFtAsHoBsbWmlraywic6AF8qX6peFA4EhpugsKZFkQyJRlkw2FweGh+IJlsJVtIZjtdoglKoNFodPpUXR0fMzMTLHibPZHBTXO4vL4AsFQuFItF4hEQqwUpV2V0MmSAF4YTrdXr9IYjZ5aKYycFkxZ00l4EVY3b7Q7HM4Xa53B5PcaIVWfZa-b5AA

### 💻 Code

```ts
(fooBar: "foo" | "bar") => {
    switch (fooBar) {
        case "foo":
            return true;
        case "bar":
            return false;
        // @ts-expect-error incorrectly has no error, should error because undefined is not assignable to "foo" | "bar"
        case undefined:
            throw new Error("Impossible undefined");
    }
}

(fooBar: "foo" | "bar") => {
    switch (fooBar) {
        case "foo":
            return true;
        case "bar":
            return false;
        // @ts-expect-error correctly errors as "baz" is not assignable to "foo" | "bar"
        case "baz":
            throw new Error("Impossible baz");
    }
}
```

### 🙁 Actual behavior

Typescript allows `case undefined:` even if `undefined` is not assignable to the `switch` parameter and `strictNullChecks: true`. This despite the fact that it does not allow other cases that can’t be assigned to the `switch` parameter.

### 🙂 Expected behavior

Typescript errors on `case undefined:` when

1. `strictNullChecks: true`, and
2. `undefined` is not assignable to the `switch` parameter.

### Additional information about the issue

`null` has exactly the same issues as `undefined` in this situation.

**Comment by MartinJohns** [comment] 2024-10-29 18:26
Duplicate of #11920.

**Closed** 2024-11-02 01:32 UTC
Labels: Duplicate
