### ISSUE TITLE
Make 'this' redundant

### ISSUE THREAD

**Issue by panuganti** [Microsoft/TypeScript#7663] opened 2016-03-23 23:58 UTC
When writing code using Typescript, too many 'this...' needs to be used. 
In most places, it should be automatically inferred. Makes code look lot nicer

**TypeScript Version:** 

1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

**Code**

```ts
// A self-contained demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by DanielRosenwasser** [comment] 2016-03-24 00:12
We're not changing the semantics of of identifier lookups in classes, since the ambiguities can be harmful, and could potentially cause breaking changes.

```ts

```

**Comment by mhegazy** [comment] 2016-03-24 00:12
duplicate of https://github.com/Microsoft/TypeScript/issues/679

**Closed by DanielRosenwasser** 2016-03-24 00:12 UTC
Labels: By Design, Declined, Out of Scope
