### ISSUE TITLE
skipLibCheck and exclude do not work under monorepos project

### ISSUE THREAD

**Issue by WeijieZhu0204** [microsoft/TypeScript#38538] opened 2020-05-13 12:55 UTC
**TypeScript Version:**  3.8.3

**Search Terms:**

**Code**

```
// ./packages/visual-editor/tsconfig.json

{
  "compilerOptions": {
    "skipLibCheck": true,
    /* Basic Options */
    // "incremental": true,                   /* Enable incremental compilation */
    "target": "ESNEXT" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */,
    "module": "commonjs" /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */,
    "lib": [
      "DOM",
      "ES2015",
      "ES2016",
      "ES2017",
      "ES2018"
    ] /* Specify library files to be included in the compilation. */,
    "allowJs": true /* Allow javascript files to be compiled. */,
    // "checkJs": true,                       /* Report errors in .js files. */
    "jsx": "preserve" /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */,
    // "declaration": true,                   /* Generates corresponding '.d.ts' file. */
    // "declarationMap": true,                /* Generates a sourcemap for each corresponding '.d.ts' file. */
    // "sourceMap": true,                     /* Generates corresponding '.map' file. */
    // "outFile": "./",                       /* Concatenate and emit output to single file. */
    // "outDir": "./",                        /* Redirect output structure to the directory. */
    // "rootDir": "./",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    // "composite": true,                     /* Enable project compilation */
    // "tsBuildInfoFile": "./",               /* Specify file to store incremental compilation information */
    // "removeComments": true,                /* Do not emit comments to output. */
    // "noEmit": true,                        /* Do not emit outputs. */
    // "importHelpers": true,                 /* Import emit helpers from 'tslib'. */
    // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    // "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */

    /* Strict Type-Checking Options */
    "strict": true /* Enable all strict type-checking options. */,
    "noImplicitAny": true /* Raise error on expressions and declarations with an implied 'any' type. */,
    "strictNullChecks": true /* Enable strict null checks. */,
    // "strictFunctionTypes": true,           /* Enable strict checking of function types. */
    // "strictBindCallApply": true,           /* Enable strict 'bind', 'call', and 'apply' methods on functions. */
    // "strictPropertyInitialization": true,  /* Enable strict checking of property initialization in classes. */
    // "noImplicitThis": true,                /* Raise error on 'this' expressions with an implied 'any' type. */
    // "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */

    /* Additional Checks */
    // "noUnusedLocals": true,                /* Report errors on unused locals. */
    // "noUnusedParameters": true,            /* Report errors on unused parameters. */
    // "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
    // "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */

    /* Module Resolution Options */
    "moduleResolution": "node" /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */,
    "baseUrl": "./src",
    "paths": {
      "actions/*": ["./actions/*"],
      "apis/*": ["./apis/*"],
      "components/*": ["./components/*"],
      "constants/*": ["./constants/*"],
      "helpers/*": ["./helpers/*"],
      "hooks/*": ["./hooks/*"],
      "reducers/*": ["./reducers/*"],
      "types/*": ["./types/*"],
      "models/*": ["./models/*"]
    },
    // "rootDirs": [],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
    // "typeRoots": [],                       /* List of folders to include type definitions from. */
    // "types": [],                           /* Type declaration files to be included in compilation. */
    // "allowSyntheticDefaultImports": true,  /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
    "esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */,
    // 与webpack resolve symlinks保持一致
    // "preserveSymlinks": true /* Do not resolve the real path of symlinks. */,
    // "allowUmdGlobalAccess": true,          /* Allow accessing UMD globals from modules. */

    /* Source Map Options */
    // "sourceRoot": "",                      /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "",                         /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true,               /* Emit a single file with source maps instead of having a separate file. */
    // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */

    /* Experimental Options */
    // "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
    // "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */

    /* Advanced Options */
    "forceConsistentCasingInFileNames": true /* Disallow inconsistently-cased references to the same file. */
  },
  "include": ["./src"],
  "exclude": ["node_modules"]
}
```

```ts
// list my project structure

├── lerna.json
├── node_modules
├── package.json
├── packages
│   ├── visual-editor
│   │   ├── dist
│   │   ├── example.config.js
│   │   ├── favicon.ico
│   │   ├── node_modules
│   │   ├── package.json
│   │   ├── readme.md
│   │   ├── src
│   │   ├── tsconfig.json
│   │   └── webpack.config.js
│   └── ....
├── readme.md
└── yarn.lock


// Execute tsc in the root directory of the project
tsc -p ./packages/visual-editor/tsconfig.json --noEmit --pretty
```

**Expected behavior:**
Hope that i can ignore the syntax check of the node_modules module through exclude and skipLibCheck configuration.But these configurations did not work.

**Actual behavior:**

Tsc throws errors about node_modules ,as follows :

> Note : The `@tencent/visual-material-wesing` module was promoted to the root node_modules directory by lerna hosit.

```

9   extends BackgroundDataSetField,
            ~~~~~~~~~~~~~~~~~~~~~~

node_modules/@tencent/visual-material-wesing/src/components/head-module/head-module.tsx:10:5 - error TS2304: Cannot find name 'FontColorDataSetField'.

10     FontColorDataSetField,
       ~~~~~~~~~~~~~~~~~~~~~

node_modules/@tencent/visual-material-wesing/src/components/head-module/head-module.tsx:11:5 - error TS2304: Cannot find name 'PositionDataSetField'.

11     PositionDataSetField {
       ~~~~~~~~~~~~~~~~~~~~

node_modules/@tencent/visual-material-wesing/src/components/head-module/head-module.tsx:18:5 - error TS2339: Property 'top' does not exist on type 'Data'.

18     top,
       ~~~

node_modules/@tencent/visual-material-wesing/src/components/head-module/head-module.tsx:20:5 - error TS2339: Property 'left' does not exist on type 'Data'.

20     left,
       ~~~~

node_modules/@tencent/visual-material-wesing/src/components/head-module/head-module.tsx:21:5 - error TS2339: Property 'color' does not exist on type 'Data'.

21     color,
       ~~~~~

node_modules/@tencent/visual-material-wesing/src/components/head-module/head-module.tsx:23:5 - error TS2339: Property 'backgroundColor' does not exist on type 'Data'.

23     backgroundColor,
       ~~~~~~~~~~~~~~~

node_modules/@tencent/visual-material-wesing/src/components/head-module/head-module.tsx:24:5 - error TS2339: Property 'backgroundImage' does not exist on type 'Data'.

24     backgroundImage,
       ~~~~~~~~~~~~~~~

node_modules/@tencent/visual-material-wesing/src/components/head-module/head-module.tsx:25:5 - error TS2339: Property 'backgroundRepeat' does not exist on type 'Data'.

25     backgroundRepeat,
       ~~~~~~~~~~~~~~~~

node_modules/@tencent/visual-material-wesing/src/components/head-module/head-module.tsx:26:5 - error TS2339: Property 'backgroundSize' does not exist on type 'Data'.

26     backgroundSize,
       ~~~~~~~~~~~~~~

node_modules/@tencent/visual-material-wesing/src/components/ranking/definition.ts:12:34 - error TS2304: Cannot find name 'Theme'.

12 export const THEME_MAP = new Map<Theme, ThemeInfo>([
                                    ~~~~~

```

**Playground Link:** 

**Related Issues:**

**Comment by abhijithvijayan** [comment] 2020-06-14 16:16
I get these errors
```
error TS2403: Subsequent variable declarations must have the same type.

error TS2300: Duplicate identifier ...
```
in a yarn workspace [monorepo](https://github.com/abhijithvijayan/OpenAir).

The project root has a base configuration and the workspace folders have extended this configuration.

As a workaround, I had to set 
```
  "compilerOptions": {
    // overrides
    "skipLibCheck": true
  },
```

**Comment by jsbroks** [comment] 2020-10-16 03:56
Im running tsc in a monorepo with the --skipLibCheck and --listFiles flags, my output still contains node_module `d.ts` files.

```
...
/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.d.ts
/node_modules/aws-sdk/lib/credentials/process_credentials.d.ts
/node_modules/aws-sdk/lib/credentials/temporary_credentials.d.ts
/node_modules/aws-sdk/lib/credentials/chainable_temporary_credentials.d.ts
/node_modules/aws-sdk/lib/credentials/web_identity_credentials.d.ts
/node_modules/aws-sdk/lib/credentials/token_file_web_identity_credentials.d.ts
...
```

Is this related?

**Comment by lukas1994** [comment] 2020-11-28 00:58
Same issue here. It takes ages to load all the node_modules d.ts files.

**Comment by wzxinchen** [comment] 2020-12-17 02:07
Same issue here. It takes ages to load all the node_modules d.ts files.

**Comment by PhilippMolitor** [comment] 2021-01-03 01:16
Any update on this? This sadly is completely blocking any sort of builds for my projects.

**Comment by mizchi** [comment] 2021-01-07 04:04
I have same error. I doubt `.ts(x)` under `node_modules` with skipLibCheck.

**Comment by waah42** [comment] 2021-02-05 09:26
we are running into same issue after updating our  aws-javascript-library to [v3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/). Any pointers to how can we keep using new library and still be able to compile things?

**Comment by tylerthecoder** [comment] 2021-04-08 14:36
Having the same issue. Blocking me on a bunch of projects. `--listFiles` shows `.d.ts` files in `node_modules`

**Comment by kamranayub** [comment] 2021-04-08 14:48
Using explicit `types` helps greatly, we reduced monorepo build time by about 2X (with `--skipLibCheck`) by specifying `types` packages to load instead of letting `tsc` detect them within our monorepo.

**Comment by borekb** [comment] 2021-05-03 12:48
I think that the example in the issue description is, at its core, #41883 – TypeScript does not apply `skipLibCheck` to `.ts` files – and note how all the example errors are from `.ts(x)` files:

```
9   extends BackgroundDataSetField,
            ~~~~~~~~~~~~~~~~~~~~~~

node_modules/@tencent/visual-material-wesing/src/components/head-module/head-module.tsx:10:5 - error TS2304: Cannot find name 'FontColorDataSetField'.
```

BTW we're not seeing issues like [above](https://github.com/microsoft/TypeScript/issues/38538#issuecomment-709716028) that `.d.ts` would be included when we set `skipLibCheck`; that works reliably for us.

**Comment by ahtokca** [comment] 2021-07-20 12:06
Same here, `skipLibCheck` is ignored and `tsc` checking files in node_modules folder

Any ideas how to solve it?

**Comment by alisalim17** [comment] 2021-07-21 10:16
Same issue

**Comment by lll000111** [comment] 2021-07-22 16:44
@ahtokca @alisalim17 

According to explanatory blogposts for this skip option the .d.ts are not completely ignored. Checks that lead there from your source files still take place. It's just that any internal issues in the .d.ts files are ignored.

Example blog post: https://dd.engineering/blog/typescript-the-skiplibcheck-option-explained

> But this doesn't mean TypeScript won't check your code against the declaration files (it doesn't check the declaration files as a whole). When you use a type from a declaration file, TypeScript still checks your code against that type as far as it can trace that type in that declaration file.

**Comment by dengnan123** [comment] 2021-07-28 08:09
Has anyone solved it?

**Comment by Vict0rd** [comment] 2021-08-04 10:42
@dengnan123 There is some magic workaround

package.json
```json
{
  "scripts": {
    "prebuild": "node add-ts-nocheck",
    "build": "tsc"
  }
}
```

add-ts-nocheck.js
```js
const fs = require('fs')

const ADDED_STR = '// @ts-nocheck\n\n'
const FILES = [
  'node_modules/some-package/some-file.ts',
  ...
]

Promise.allSettled(FILES.map(addTsNoCheck)).then(results => {
  let hasErrors = false

  for (const result of results) {
    if (result.status === 'rejected') {
      hasErrors = true
      console.error(result.reason)
    }
  }

  if (hasErrors) {
    process.exit(1)
  }
})

async function addTsNoCheck(file) {
  const content = fs.readFileSync(file).toString()

  if (content.includes(ADDED_STR)) {
    console.log(JSON.stringify(ADDED_STR), 'is already in', file)
  } else {
    fs.writeFileSync(file, ADDED_STR + content)
    console.log(JSON.stringify(ADDED_STR), 'added into', file)
  }
}
```

**Comment by borekb** [comment] 2021-08-04 12:19
@Vict0rd Wow, what a workaround 😄.

**Comment by xgqfrms** [comment] 2021-11-02 02:11
TypeScript `skipLibCheck` and `exclude` not work under single project, too

https://github.com/microsoft/TypeScript/issues/46634

**Comment by Ai01** [comment] 2022-01-18 12:44
> @dengnan123 There is some magic workaround
> 
> package.json
> 
> ```json
> {
>   "scripts": {
>     "prebuild": "node add-ts-nocheck",
>     "build": "tsc"
>   }
> }
> ```
> 
> add-ts-nocheck.js
> 
> ```js
> const fs = require('fs')
> 
> const ADDED_STR = '// @ts-nocheck\n\n'
> const FILES = [
>   'node_modules/some-package/some-file.ts',
>   ...
> ]
> 
> Promise.allSettled(FILES.map(addTsNoCheck)).then(results => {
>   let hasErrors = false
> 
>   for (const result of results) {
>     if (result.status === 'rejected') {
>       hasErrors = true
>       console.error(result.reason)
>     }
>   }
> 
>   if (hasErrors) {
>     process.exit(1)
>   }
> })
> 
> async function addTsNoCheck(file) {
>   const content = fs.readFileSync(file).toString()
> 
>   if (content.includes(ADDED_STR)) {
>     console.log(JSON.stringify(ADDED_STR), 'is already in', file)
>   } else {
>     fs.writeFileSync(file, ADDED_STR + content)
>     console.log(JSON.stringify(ADDED_STR), 'added into', file)
>   }
> }
> ```

good job bro

**Comment by RyanCavanaugh** [comment] 2022-01-20 23:40
It looks like a lot of people have landed in this thread thinking that `skipLibCheck` can cause files to not be included in the program -- this is not what `skipLibCheck` does. If you have a file in your compilation that you don't want to be there, use `--explainListFiles` to see how it got there.

**Closed by RyanCavanaugh** 2022-01-20 23:40 UTC
Labels: Question

**Comment by ipmcc** [comment] 2022-03-22 19:08
`error TS5023: Unknown compiler option '--explainListFiles'.` 
I'm using TypeScript v4.5.5. This is very recent. Am I missing something here? This is epically frustrating.

**Comment by RyanCavanaugh** [comment] 2022-03-22 19:48
Sorry, misremembered the name - it's `explainFiles` https://www.typescriptlang.org/tsconfig/#explainFiles

**Comment by weagle08** [comment] 2022-09-15 16:10
So this still occurs. For some reason when `"strict": true` in the tsconfig.json it makes the tsc compilier completely ignore the skipLibCheck and skipDefaultLibCheck settings. Set strict to false and you should be good to go (other than the complaint about this in your tsconfig, the typescript team should fix this)

**Comment by neotan** [comment] 2023-01-03 04:22
In case someone ended up landing here for a workaround, **the point is just to include my ts/tsx files specifically** when working with Next.js v13. Btw, [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) can eighter be `true` or `false` as it's not related here.

## tsconfig.json (required parts)
```json
{
  "compilerOptions": {
    "strict": true,
    "skipLibCheck": false, 
    "include": [
      "next-env.d.ts",
      "apps/**/*.ts",
      "apps/**/*.tsx",
      "src/**/*.ts",
      "src/**/*.tsx",
      "components/**/*.ts",
      "components/**/*.tsx",
      "icons/**/*.ts",
      "icons/**/*.tsx"
    ],
    "exclude": [
      "node_modules"
    ]
}
```

**Comment by sneko** [comment] 2023-01-05 09:56
On my side my storybook package was looking for types specific to another workspace package. I tried tons of "solutions" but none worked.

The only one working was to tell my package to look for types of the other package (since it's a monorepo, relative path going back is not an issue):
```
{
  ...
  "include": ["**/*.ts", "**/*.tsx", "../../apps/main/@types"],
  "exclude": ["node_modules"]
}
```

Hope this helps :)

**Comment by LoserAntbear** [comment] 2023-01-17 12:26
So I see that there's no 'official' solution but in my case non of the suggested variants worked.
I've got monorepo (react-native + typescript, just in case). And I want to utilise typescript solely for static type checking. Although it renders me unable to do that.

**Description.**

Technologies:
- react-native
- typescript
- yarn workspaces

**Project structure:**
./packages
   ./projectA
   ./projectB
   ./projectC
   
B depends on A. C depends on A+B.
All of them have own tsconfig's, which extend the root one.

I need to perform type-check on git hooks (pre-push) only for the single project (e.g. working on project C type check to be performed only for projectC files). I need no .js outputs.

For some reasons, when I run `tsc --project . --skipLibCheck` in `projectC` folder, it still performs type-check for packageA and packageB, despite these projects are stated in 'package.json' dependencies. Thus, flag `skipLibCheck` should exclude them from compilation and type-check stage, shouldn't it?
The issue is that packageA and packageB have their path aliases and typescript throws an error that modules cannot be found for these paths aliases.

**What have I tried:**
- Setting unique path aliases for each project (eg. "projectA:@assets/*": ["./assets/*"] | "projectB:@utils/*": ["./utils/*"]) in **root** tsconfig and own tsconfigs.
- Adding project references (with composite: true, declaration: true, emitDeclarationOnly: true (I do not need js output))

Non of this worked and I beg you guys for the help with  the solution of the problem, since it blocks us from having a proper type handling on the project.

_Fun fact is that VSCode handles all the types correctly and produce no type errors, while TSC does._

**Comment by nterraza** [comment] 2023-03-17 08:38
I am also having this issue with lerna. All instructions given to the `tsconfig.json` are ignored. Is there any way at least to diagnose which library is overwriting the explicit instruction I am giving ?

The way I understand the purpose of tsconfig is that it overwrites the parent tsconfig. But other libraries installed apparently can also overwrite it ? 

It feels like I have no control typescript config, rather other dependencies do. Is this something particular of lerna forcefully overwriting ?

**Comment by foloinfo** [comment] 2023-06-01 07:49
It happens to me with wagmi (nextjs 13.x config) and I've already set `"skipLibCheck": true` and it didn't help.
[wagmi-dev/wagmi#344](https://github.com/wagmi-dev/wagmi/issues/344)

I don't know why, but I just upgraded typescript to 5.0.4 and now the error is gone.
Now I only need `"skipLibCheck": true` (I didn't need `"exclude": ["node_modules"]`) and it works fine.

It might be worth trying to upgrade the ts version if you can.

**Comment by sesh92** [comment] 2023-09-22 13:23
I guess I got stuck with the same problem:

monorepo:
- packages/app/tsconfig.json
```
    "noUnusedLocals": true,
    "noUnusedParameters": true,
```
- packages/some-typegen-package/tsconfig.json
```
    "noUnusedLocals": false,
    "noUnusedParameters": false,
```
`error TS6196: '<variable>' is declared but never used.`

cli `tsc --noEmit` in app is ignoring tsconfig in `some-package`
but after adding to `app/tsconfig.json`
```
"references": [
    {
      "path": "../some-typegen-package"
    }
  ]
```
the problem was solved

**Comment by LINGyue-dot** [comment] 2025-01-13 13:27
Same issue
