### ISSUE TITLE
Type inference incorrect when accessing empty index in array

### ISSUE THREAD

**Issue by DrewML** [Microsoft/TypeScript#26339] opened 2018-08-09 20:25 UTC
**TypeScript Version:**  Version 3.0.1

**Search Terms:**
- Inference
- Empty array index

**Code**
This is the most boiled down example I could derive from the original code. The actual use-case where I ran into this is less contrived.
```ts
const str = 'abc';
// Inferred type for `value` is `string`
const value = str[199];
```

**Expected behavior:**
Inferred type for `value` is `string | undefined`

**Actual behavior:**
Inferred type for `value` is `string`

**Playground Link:** [Click Me](http://www.typescriptlang.org/play/#src=const%20str%20%3D%20'abc'%3B%0D%0Aconst%20value%20%3D%20str%5B199%5D%3B)

**Related Issues:**

**Comment by ajafff** [comment] 2018-08-09 20:31
duplicate of #13778

**Comment by DrewML** [comment] 2018-08-09 20:33
Thanks @ajafff!

**Closed** 2018-08-09 20:32 UTC
