### ISSUE TITLE
Object spreads should retain shallow type narrowing

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#26645] opened 2018-08-23 22:01 UTC
**TypeScript Version:**  3.1.0-dev.20180822

**Search Terms:** object spread assignability inference equals undefined throw error assignable

**Code**

```ts
interface IModel {
    index?: number;
}

function fillOut(model: IModel) {
    if (model.index === undefined) {
        throw new Error("");
    }

    const index: number = model.index; // OK

    const directModel: Required<IModel> = model;
//        ~~~~~~~~~~~ 
//  Type 'IModel' is not assignable to type 'Required<IModel>'.
//    Property 'index' is optional in type 'IModel' but required in type 'Required<IModel>'.

    const spreadModel: Required<IModel> = {
//        ~~~~~~~~~~~ 
//  Type 'IModel' is not assignable to type 'Required<IModel>'.
//    Property 'index' is optional in type 'IModel' but required in type 'Required<IModel>'.
        ...model,
        // index: 0,
    };
}
```

**Expected behavior:**

`spreadModel` should be allowed, as we've inferred that `model.index` must be of type `number`, and unlike `directModel`, there's no allowed way to modify `spreadModel` after the fact.

**Actual behavior:**

The type narrowing on `model` is forgotten in the `...` spread.

**Playground Link:** http://www.typescriptlang.org/play/#src=interface%20IModel%20%7B%0D%0A%20%20%20%20index%3F%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Afunction%20fillOut(model%3A%20IModel)%20%7B%0D%0A%20%20%20%20if%20(model.index%20%3D%3D%3D%20undefined)%20%7B%0D%0A%20%20%20%20%20%20%20%20throw%20new%20Error(%22%22)%3B%0D%0A%09%7D%0D%0A%0D%0A%09const%20index%3A%20number%20%3D%20model.index%3B%0D%0A%0D%0A%20%20%20%20const%20directModel%3A%20Required%3CIModel%3E%20%3D%20model%3B%0D%0A%0D%0A%20%20%20%20const%20spreadModel%3A%20Required%3CIModel%3E%20%3D%20%7B%0D%0A%20%20%20%20%20%20%20%20...model%2C%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20index%3A%200%2C%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A

**Comment by JoshuaKGoldberg** [comment] 2018-08-23 22:27
@andy-ms sorry if nitpicking, but isn't this a bug?

**Comment by andy-ms** [comment] 2018-08-23 22:41
It's a kind of inference that the type system currently doesn't perform. Note that we also don't allow this:
```ts
interface I { readonly x: number | string; }
function f(i: I): { readonly x: number } {
    return typeof i.x === "number" ? i : { x: 0 };
}
```

This may be too expensive to do in the general case of a variable access, but maybe in the case of a spread, since we're iterating over all properties anyway, we could see if some of them have local narrows.

**Comment by eamodio** [comment] 2018-09-29 03:43
Here is another case of the same issue, I believe: http://www.typescriptlang.org/play/#src=interface%20Obj%20%7B%0D%0A%20%20%20%20num%3F%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Afunction%20foo(obj%3A%20Obj)%20%7B%0D%0A%20%20%20%20if%20(obj.num%20%3D%3D%3D%20undefined)%20%7B%0D%0A%20%20%20%20%20%20%20%20obj.num%20%3D%201%3B%0D%0A%09%7D%0D%0A%0D%0A%09bar(obj.num)%3B%0D%0A%0D%0A%20%20%20%20const%20objCopy%20%3D%20%7B%20...foo%20%7D%3B%0D%0A%20%20%20%20bar(objCopy.num)%3B%0D%0A%7D%0D%0A%0D%0Afunction%20bar(num%3A%20number)%20%7B%0D%0A%0D%0A%7D

**Comment by RyanCavanaugh** [comment] 2018-10-09 18:23
Same root cause as #10065

**Comment by eamodio** [comment] 2018-10-09 19:08
@RyanCavanaugh since #10065 is closed, does that mean this issue won't be fixed?

**Comment by RyanCavanaugh** [comment] 2018-10-09 19:31
@eamodio correct (for some definition of "won't")

**Closed** 2018-12-14 18:00 UTC
Labels: Duplicate
