### ISSUE TITLE
Union strings for Discriminated Unions

### ISSUE THREAD

**Issue by mushishi78** [Microsoft/TypeScript#23569] opened 2018-04-20 16:23 UTC
**TypeScript Version:**  2.8.1, 2.6.1
**Search Terms:** Union strings, Discriminated Unions
**Code**

```ts
const a: { type: '1' } | { type: '2' } = null as { type: '1' | '2' }
```

**Expected behavior:** The types should be recognized as equivalent

**Actual behavior:**
> Type '"1"' is not assignable to type '"2"'

**Playground Link:** https://www.typescriptlang.org/play/#src=const%20a%3A%20%7B%20type%3A%20'1'%20%7D%20%7C%20%7B%20type%3A%20'2'%20%7D%20%3D%20null%20as%20%7B%20type%3A%20'1'%20%7C%20'2'%20%7D%0D%0A

**Comment by RyanCavanaugh** [comment] 2018-04-20 16:30
Duplicate of #12052

**Closed** 2018-05-04 17:29 UTC
Labels: Duplicate
