### ISSUE TITLE
Wrong control flow analysis in async function.

### ISSUE THREAD

**Issue by Mng12345** [microsoft/TypeScript#56988] opened 2024-01-09 03:49 UTC
### 🔎 Search Terms

"async", "control flow analysis"

### 🕗 Version & Regression Information

TS5.3.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/FAiGGcE8DsGMAIBmBXOAXAlge2vAtqBtABQCU8A3sPPADYCma84aoa9AXPAOQBGyAL0jd4AHx4ssAByn0AJiIC8EtNNkLqzVgCc0ZTaADuhJsYxoAyqqn6asHOCwMAdLSwBzYgANJM+c69SEBoIGAQUdGxcM0trMi4ABW0sPAxwegAeADcsDDkAPkpNGgxEeGIWNnp4RVqVNXlucioaVvhtRmRtaGL4AF9exCxtcoBueFHm3pKyitZ2GrruX3Umora2jrQuno3++HpadPhS8sqF2uU+QWEpvZCY5gZ6GwBWAAYgvYG2n-7g+ChOBIVCwTA4LSgXTxeBJFJpTI5PKFFqtc7VK78ITcQbDcoMJgYGrwd7jIkZeAARlJJwA1LS7hsAPRM+ByLDMFKMAAWRHc00Bj3Azze70+Avs0EcLjcni8bmk8AAJBQibSqX0TrhKroAl9Wn8aOjictrKtNANNBEwVEnvQXsQ8OAuNBkHhePRtKREslUulsrkCutWlsdvBoPRDLDfQjiB1pVkMSiBek0AAVDB4ehYZB6eNORMAGnw4H1ND6+oGloIRH0IGAQA

### 💻 Code

```ts



async function main() {
  let state: 'buzy' | 'stopped' = 'stopped'
  start()
  await waitStop()
  console.log(`stopped.`)

  async function waitStop(): Promise<void> {
    if (state === 'stopped') {
      return
    }
    for (; ;) {
      if (state === 'stopped') {
        return
      } else if (state === 'buzy') {
        await sleep(50)
      }
    }
  }

  async function start(): Promise<void> {
    state = 'buzy'
    for (let i = 0; i < 10; i++) {
      // do something
      await sleep(500)
      console.log(`loop ${i + 1} in start.`)
    }
    state = 'stopped'
  }

  function sleep(ms: number): Promise<void> {
    return new Promise(resolve => {
      setTimeout(resolve, ms)
    })
  }
}

main()




```

### 🙁 Actual behavior

![image](https://github.com/microsoft/TypeScript/assets/21278900/7017680e-cf78-4de3-b034-7d348d20c2bd)

The line 5 shows an error that the typeof state in this line should only be `buzy` because it is already narrowed by `if (state === 'stopped')` expression before in `waitStop` function. This is wrong for the function `waitStop` is an async function, when the state is `buzy`, the function `waitStop` will wait 50ms and let other functions like `start` to take over the cpu, and the `start` function will modify the state.

### 🙂 Expected behavior

the type of `state` at line 5 should not be narrowed.

**Comment by Mng12345** [comment] 2024-01-09 03:53
The type of `state` only narrowed to `buzy` in the first time of for loop.

**Comment by MartinJohns** [comment] 2024-01-09 05:21
Duplicate of #9998.

**Closed** 2024-01-12 01:29 UTC
Labels: Duplicate
