### ISSUE TITLE
inference doesn't work

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#21644] opened 2018-02-05 20:36 UTC
```typescript
type Unknown = {} | null | undefined | void;
void function f<T, K extends keyof T>(
   fn: (data: T) => T[K]
): (data: T) => Unknown {
    return fn; /* <-- expected to work, actual:
    Type '(data: T) => T[K]' is not assignable to type '(data: T) => Unknown'.
      Type 'T[K]' is not assignable to type 'Unknown'.
        Type 'T[K]' is not assignable to type '{}'.
*/
}
```

**Comment by ajafff** [comment] 2018-02-05 20:40
Duplicate of  #21368

**Comment by aleksey-bykov** [comment] 2018-02-05 20:58
how is it a duplicate or work as intended? excuse me `Unknown | null | undefined | void` is a top type to any other type out there, and it is in co-variant position, so in must work

**Closed** 2018-02-20 19:07 UTC
Labels: Duplicate
