### ISSUE TITLE
Rest types may only be created from object types

### ISSUE THREAD

**Issue by testerez** [Microsoft/TypeScript#17281] opened 2017-07-18 21:38 UTC
**TypeScript Version:**  2.4.0

**Code**

```ts
interface Foo{
  foo: number;
}
function test<T>(arg: T & Foo) {

  // Error: [ts] Rest types may only be created from object types
  const { foo, ...rest } = arg; 

  return rest;
}
```

**Expected behavior:**
No error

**Actual behavior:**
Error: [ts] Rest types may only be created from object types

**Comment by sccolbert** [comment] 2017-07-19 17:03
Duplicate of #16780

**Closed** 2017-11-27 18:39 UTC
Labels: Duplicate
