### ISSUE TITLE
Import simplification too aggressive for transpileOnly in super call

### ISSUE THREAD

**Issue by MehdyKarimpour** [Microsoft/TypeScript#24620] opened 2018-06-02 08:31 UTC
**TypeScript Version:** 2.9.1

**Search Terms:** transpile-only import 

**Code**

```ts
import { QueryEntity } from '../../../Framework/Signum.React/Scripts/Signum.Entities.Basics'
import { ToolbarConfig, ToolbarResponse } from './ToolbarClient'

export default class QueryToolbarConfig extends ToolbarConfig<QueryEntity> {
    constructor() {
        super(QueryEntity);
    }
}
```

**Expected behavior:**
QueryEntity is imported in the generated JS. 

**Actual behavior:**
QueryEntity is simplified away. 

```js
"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _Framework_Signum_React_Scripts_Reflection__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../../../Framework/Signum.React/Scripts/Reflection */ "../Framework/Signum.React/Scripts/Reflection.ts");
/* harmony import */ var _Framework_Signum_React_Scripts_Finder__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../../../Framework/Signum.React/Scripts/Finder */ "../Framework/Signum.React/Scripts/Finder.tsx");
/* harmony import */ var _ToolbarClient__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./ToolbarClient */ "../Extensions/Signum.React.Extensions/Toolbar/ToolbarClient.tsx");
var __extends = (undefined && undefined.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var QueryToolbarConfig = /** @class */ (function (_super) {
    __extends(QueryToolbarConfig, _super);
    function QueryToolbarConfig() {
        return _super.call(this, QueryEntity) || this; //<--- problem here 
    }
}
```

```
bundle.main.1e1e130d262a7c0b7498.js:6772 Uncaught (in promise) ReferenceError: QueryEntity is not defined
    at new QueryToolbarConfig (bundle.main.1e1e130d262a7c0b7498.js:6772)
    at bundle.main.1e1e130d262a7c0b7498.js:30387
````

The problem is fixed just by assigning QueryEntity to a variable first: 
```ts
export default class QueryToolbarConfig extends ToolbarConfig<QueryEntity> {
    constructor() {
        var a = QueryEntity; 
        super(a);
    }
}
```

**Comment by mhegazy** [comment] 2018-06-02 23:15
Duplicate of https://github.com/Microsoft/TypeScript/issues/24551, fixed by https://github.com/Microsoft/TypeScript/pull/24591. 

Fix should be already in `typescript@next` today, and in `typescript@2.9.2` in two weeks.

**Comment by phiresky** [comment] 2018-06-05 21:35
This is pretty annoying since it blocks use of TS 2.9 when running with a large project with type errors / partially typed files (forcing use of transpileOnly). Any way to get this fix to a stable version faster?

I'm assuming this is the issue causing https://github.com/TypeStrong/ts-node/issues/591

**Comment by phiresky** [comment] 2018-06-05 21:49
This also happens when using webpack. Even worse: This error is only noticed once an instance of the corresponding class is constructed at runtime, which might only happen seldom and thus not be noticed.

I have many files that look like this:

```ts
import config from "client/config";

class Something extends XYZ {
	constructor() {
		super(config.var); [...]
	}
```

I can't even find all instances of this error without it crashing my code randomly and fixing it when it does.

**Closed** 2018-06-20 22:21 UTC
Labels: Duplicate
