### ISSUE TITLE
Rename string literal values

### ISSUE THREAD

**Issue by maxime1992** [Microsoft/TypeScript#15370] opened 2017-04-25 09:32 UTC
I have interfaces in my app. 

Let's take a dog as example : 

```typescript
interface Dog {
  name: string
  id?: number
}
```

When I `post` a `Dog` on the server, I ask the user to give me the dog's name and the server will return an object of `Dog` type.

So my function to post the `Dog` only needs his name : 
```typescript
function postDog(name: string) {
   // ...
}

const dog: Dog = { name: 'wouaf' }
postDog(dog.name)
```

The thing is, if I decide to rename the `Dog`'s `name` property,  my function won't have the parameter renamed. (yes this is pure luxury :gem: and it wouldn't break anything *in frontend at least because if my interface matches what the server is expecting ...*)

So a collegue (@vnoel) helped me figure that out : 
```typescript
// utility
type Prop<T, K extends keyof T> = { [P in K]: T[P] }

type Doggy = Prop<Dog, 'name' | 'id'>

function f(o: Doggy) {
  console.log(o.id, o.name)
}

f({
  id: 5,
  name: 'wouaf'
})
```

**This is great !** The only thing is that when I use `F2` to rename the property (in VSC) : 
![image](https://cloud.githubusercontent.com/assets/4950209/25378513/92517620-29aa-11e7-8d13-8ca51a8a1229.png)

Would it be possible to auto-rename the property everywhere ?  
At least we have an error which is great for now :) But doing that automatically would be :1st_place_medal: 

PS : I think it's related to https://github.com/Microsoft/TypeScript/issues/7611 and https://github.com/Microsoft/TypeScript/issues/9257 but a little bit different

**Comment by mhegazy** [comment] 2017-04-26 18:48
This is actually a duplicate of https://github.com/Microsoft/TypeScript/issues/13690. rename is built on top of find all refs.

**Comment by andy-ms** [comment] 2017-05-08 19:25
This actually looks more like a duplicate of #11997.

**Closed** 2017-05-08 21:39 UTC
Labels: Duplicate
