### ISSUE TITLE
tsc emitting tripleslash reference to devDependencies when using @types

### ISSUE THREAD

**Issue by endel** [Microsoft/TypeScript#11948] opened 2016-10-30 20:58 UTC
**TypeScript Version:**  2.0.6

**Code**

It's happening on [SignalsJS](https://github.com/GoodgameStudios/SignalsJS). See the [package.json](https://github.com/GoodgameStudios/SignalsJS/blob/870327bebe833f0cb324f294acdaf0299a9bc7f2/package.json#L33-L37) and [tsconfig.json](https://github.com/GoodgameStudios/SignalsJS/blob/870327bebe833f0cb324f294acdaf0299a9bc7f2/tsconfig.json) configs.

```ts
    "include": [
        "./src/**/*.ts",
        "./test/**/*.ts"
    ]
```

- The problem persists removing the `"./test/**/*.ts"` include from `tsconfig.json`. 
- It works removing `"./test/**/*.ts"` and adding `"types": []` in `tsconfig.json`, but it doesn't make sense for me.

**Expected behavior:**

Not having `///<reference types="chai">` in files not using them.

**Actual behavior:** 

```
$ ag chai lib/
lib/org/osflash/signals/DeluxeSignal.d.ts
1:/// <reference types="chai" />

lib/org/osflash/signals/events/GenericEvent.d.ts
1:/// <reference types="chai" />

lib/org/osflash/signals/events/IEvent.d.ts
1:/// <reference types="chai" />

lib/org/osflash/signals/ISlot.d.ts
1:/// <reference types="chai" />

lib/org/osflash/signals/Slot.d.ts
1:/// <reference types="chai" />
```

What is odd is that only `"chai"` is being included automatically.

**Comment by mhegazy** [comment] 2016-10-30 21:04
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/11849. should be fixed in latest `typescript@next`.

**Closed** 2016-10-30 21:04 UTC
Labels: Duplicate

**Comment by endel** [comment] 2016-10-30 21:11
Thanks for your quick reply @mhegazy. Confirmed, this is not happening on `Version 2.1.0-dev.20161030`. Cheers!
