### ISSUE TITLE
Missing HTML comment support

### ISSUE THREAD

**Issue by nowindowsowrking** [Microsoft/TypeScript#16733] opened 2017-06-26 01:49 UTC
Any plans to support HTML comments? All decent parses nowadays seems to support it except TS.

**Comment by acullather** [comment] 2017-06-26 03:38
What would think take the form of? Typescript is a superset that compiles into JavaScript. I'm not aware of an HTML comment in JavaScript...

**Comment by DanielRosenwasser** [comment] 2017-06-26 05:04
Duplicate of #10512. Feel free to send a PR.

**Closed by DanielRosenwasser** 2017-06-26 05:04 UTC
