### ISSUE TITLE
allow type bound function references and classes and values

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#30567] opened 2019-03-24 21:24 UTC
quite often i run into a situation were i need a reference to a generic function to be pre-filled with some type arguments, example:

```ts
declare function toArrayOf<T>(): T[];
declare function fn<T>(make: () => T): void;

// currently it takes
fn(() => [] as string[]);

// i wish, i could do
fn(toArrayOf<string>); // <-- a reference to a generic function pre-filled with type arguments
```

**Comment by jack-williams** [comment] 2019-03-28 11:08
Duplicate of #29043?

**Closed** 2019-03-28 13:12 UTC
