### ISSUE TITLE
Interface Overloads Resolving Different Return Type Than Method Overloads

### ISSUE THREAD

**Issue by martinmckenna** [microsoft/TypeScript#44846] opened 2021-07-01 12:04 UTC
# Bug Report
 
Hi. I'm seeing an issue where using interface overloads and method overloads don't seem to behave the same way (even though I appear to be writing the same type of logic in both scenarios.

What I'm trying to achieve is an overload in an interface that has different return types based on whether a boolean argument is `true` or `false`. Below you can see this works no problem with function overloads but doesn't work with using interfaces.

### 🔎 Search Terms

"conditional return type overloads"
"conditional boolean overloads"

### ⏯ Playground Link

Code that doesn't work

https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBBCcQQ0MwAUVWDEQNUgADVHBQGNJ3KAALygABEAAkYNAMOB4GRogLFFTBPB3AExcwABT0xnM9zsyhc9wASmCKhwDQ8ZC8iElzhB7Bo3zcZmY7AYzEg-Fg0HUiS58D0Ii8AoZTJZggFSRxAvADlQAHJhAA5SASAVBFQAeW+ZF2gldWkgx1QjgUrmkeFATgtOlGWH0KAQiBhwiudokkuiIgMHBx3RYbC43CCigyCjIyR6KAAIvAcHExgBvRQlNVkZj5NBkdiQPWr2egNSrmmUThjAC+AG4F6AlyvcQxoNmt6Ad9hoGLV5x2IhpD9QGfFMfgpCko0HKNDcFOM6rpO05VvyjhjLyAB8j4Xoil5wXqyElCUTgEmamFYSUe6gNGz5itGF4lL+lHBNheaEl484EaR8CrgAzBev5UaAQA

Code that works

https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBBCcQQ0MwAUVWDEQNUgADVHBQGNJ3KAALygABEAAkYNAMOB4GRogLFFTBPB3AExcwABT0xnM9zsyhc9wASmCKhwDQ8ZC8iElzhB7Bo3zcZmY7AYzEg-Fg0HUiS58D0Ii8AoZTJZggFSRxAvADlQAHJhAA5SASAVBFQAeW+ZF2gldWkgx1QjgUrmkeFATgtOlGWH0KAQiBhwiudokkuiIgMHBx3RYbC43CCimSXFgqAo8C83HgODiqsczHyaDI7EgeoXAG9QGoFzTKJwxgBfQfD0fj+FTmdqsjz3EMaDZ1egDfYaBihecdiIaQ-UCHofmE8TueoyXteIIKh4nB6o+iglIioAgVBa4wSUZZ5oSXhIShKFbqA0bPmK0bISU+4ANzIYeyFOASZrQVh+HwAuADM5FkYeJRAA

### 💻 Code

```ts
/* broken code */
interface DoThing {
  (arg: true): { hi: string };
  (arg: false): { hello: number };
}

/* errors here */
export const doThing: DoThing = arg => { // return type typed as { hi: string; hello?: number } | { hi?: string; hello: number }
  if (arg) {
    return {
      hi: 'hello'
    };
  }

  return {
    hello: 3
  };
};
```

```ts
/* working code */
function doThing(arg: true): { hi: string }
function doThing(arg: false): { hello: number }
function doThing(arg: boolean) {
  if (arg) {
    return {
      hi: 'hello'
    };
  }

  return {
    hello: 3
  };
}
```

### 🙁 Actual behavior

Function's return type is a union type between the two possible interfaces

### 🙂 Expected behavior

Function's return type observes the overload and return type correctly

**Comment by MartinJohns** [comment] 2021-07-01 13:07
Seems like a duplicate of #44441.

**Comment by sandersn** [comment] 2021-07-01 17:25
Agree. This is working as intended, unfortunately. I'd class it as Design Limitation -- it might be possible to fix this but it would require rethinking the design of contextual typing.

**Closed** 2021-07-01 17:25 UTC
Labels: Duplicate

**Comment by martinmckenna** [comment] 2021-07-01 17:47
makes sense. Thanks for the responses on this. I'll just use function overloads :+1:

**Comment by martinmckenna** [comment] 2021-07-01 19:12
Also seems like it works if I do `const someFunction () => {} as SomeInterface` instead of `const someFunction: SomeInterface = () => {}` 🤷
