### ISSUE TITLE
Acces of object with index signature via key with generic type returns wrong type

### ISSUE THREAD

**Issue by r00ger** [Microsoft/TypeScript#22053] opened 2018-02-20 16:24 UTC
**TypeScript Version:**  typescript@2.8.0-dev.20180220, typescript@2.7.2

**Code**

```ts
declare const dict: { [K: string]: number | undefined };
function foo<S extends string>(betSpot: S): number {
    const value = dict[betSpot];
    return value ? value : 0;
//  ~~~~~~~~~~~~~~~~~~~~~~~~~
}
```

**Expected behavior:**

No error

**Actual behavior:**
```
Type '{ [K: string]: number | undefined; }[S]' is not assignable to type 'number'.
  Type 'number | undefined' is not assignable to type 'number'.
    Type 'undefined' is not assignable to type 'number'.
```

**Playground Link:** http://www.typescriptlang.org/play/index.html#src=declare%20const%20dict%3A%20%7B%20%5BK%3A%20string%5D%3A%20number%20%7C%20undefined%20%7D%3B%0D%0Afunction%20foo%3CS%20extends%20string%3E(betSpot%3A%20S)%3A%20number%20%7B%0D%0A%20%20%20%20const%20value%20%3D%20dict%5BbetSpot%5D%3B%0D%0A%20%20%20%20return%20value%20%3F%20value%20%3A%200%3B%0D%0A%7D

**Related Issues:**

https://github.com/Microsoft/TypeScript/issues/21770 https://github.com/Microsoft/TypeScript/issues/21760 seem related

**Comment by mhegazy** [comment] 2018-03-10 00:43
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/22214

**Comment by mhegazy** [comment] 2018-03-10 00:44
`dict[betSpot]` is considered to be generic by the compiler, and thus not narrowed. but it does not have to be since `dict` has a string indexer.

**Closed** 2018-03-26 16:22 UTC
Labels: Duplicate
