### ISSUE TITLE
BUGS: Compiler removes inline comments for objects

### ISSUE THREAD

**Issue by microshine** [Microsoft/TypeScript#17001] opened 2017-07-07 10:29 UTC
**TypeScript Version:**  2.4.1

**Code**

```ts
/**
 * Comment
 */
// Comment
const val1 = 1; // comment
const val2 = 1; /* comment */

const obj = {
    prop1: 1, // comment
    prop2: 2, /* comment */
}

// Comment
```

**Compiled JS**

```js
"use strict";
/**
 * Comment
 */
// Comment
var val1 = 1; // comment
var val2 = 1; /* comment */
var obj = {
    prop1: 1,
    prop2: 2,
};
// Comment 

```

TypeScript compiler removed comments after `prop1` and `prob2` for `obj`

**Comment by ikatyang** [comment] 2017-07-07 10:55
It seems duplicate of https://github.com/Microsoft/TypeScript/issues/13939?

**Comment by mhegazy** [comment] 2017-09-12 19:55
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-12 19:55 UTC
Labels: Duplicate
