### ISSUE TITLE
It's not possible to make a iteration over a map with strictNullChecks and target to ES6

### ISSUE THREAD

**Issue by dashaus** [Microsoft/TypeScript#8413] opened 2016-05-01 18:58 UTC
**TypeScript Version:** 

nightly (1.9.0-dev.20160430)

**Code**

```ts
var myMap = new Map();
myMap.set(0, "zero");
myMap.set(1, "one");
for (var [key, value] of myMap) {
    alert(key + " = " + value);
}

```

**Expected behavior:**

Possibility to do a iteration over map.

**Actual behavior:** 

The compiler raises the follow error: `Type must have a '[Symbol.iterator]()' method that returns an iterator.`

**Comment by mhegazy** [comment] 2016-05-01 19:03
duplicate of https://github.com/Microsoft/TypeScript/issues/8357

**Closed by mhegazy** 2016-05-01 19:03 UTC
