### ISSUE TITLE
Inferred type does not resolve completely, contains free variables

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#19086] opened 2017-10-10 23:35 UTC
**TypeScript Version:**  2.5.3

**Code**

```ts
function weird<T extends Record<string, { x: any }>>(o: T) {
  type Additional = T & { extra: { x: number } }
  type XValues = { [K in keyof Additional]: Additional[K]['x'] }
  const results: XValues = undefined as any // implementation not important
  return results
}

const results = weird({
  foo: { x: 'hello' },
  bar: { x: true },
})
```

**Expected behavior:**

The type of `results` should be

```ts
{
    foo: string;
    bar: boolean;
    extra: number;
}
```

and was, prior to 2.5.3.

**Actual behavior:**

The type of `results` is

```ts
{
    [K in keyof (T & {
        extra: {
            x: number;
        };
    })]: (T & {
        extra: {
            x: number;
        };
    })[K]["x"];
}
```

I'm not even sure what that type means, since it contains the free variable `T` that only existed in the scope of the function that produced the result. `T` should've resolved to `{ foo: { x: 'hello' }, bar: { x: true } }`.

This is a minimal repro whittled down from a much larger body of code in our app, and the problem is preventing us from being able to migrate beyond TypeScript 2.5.2.

**Comment by pelotom** [comment] 2017-10-10 23:41
Interestingly, this reformulation using a `WithAdditional` type constructor makes it resolve correctly:

```ts
type WithAdditional<T> = T & { extra: { x: number } }

function weird<T extends Record<string, { x: any }>>(o: T) {
  type XValues = { [K in keyof WithAdditional<T>]: WithAdditional<T>[K]['x'] }
  const results: XValues = undefined as any // implementation not important
  return results
}

const results = weird({
  foo: { x: 'hello' },
  bar: { x: true },
})
// results: {
//   foo: string;
//   bar: boolean;
//   extra: number;
// }
```

**Comment by ahejlsberg** [comment] 2017-10-11 00:27
This is a duplicate of #19043. I will have a fix up soon.

**Comment by pelotom** [comment] 2017-10-11 00:38
Duplicate of #19043

**Comment by pelotom** [comment] 2017-10-11 00:39
GitHub has a [first-class notion of issue duplication](https://help.github.com/articles/about-duplicate-issues-and-pull-requests/) now, but apparently you have to be very specific in your wording :)

**Closed** 2017-10-12 00:30 UTC
Labels: Duplicate
