### ISSUE TITLE
typescript@next breaking node typings

### ISSUE THREAD

**Issue by nojvek** [Microsoft/TypeScript#10049] opened 2016-07-31 07:05 UTC
**TypeScript Version:**   nightly (2.0.0-dev.201xxxxx)

**Code**

```
typings/globals/node/index.d.ts(1863,36): error TS2690: A class must be declared after its base class
```

node typings are perhaps the most used of all typings. Typescript@next should not break this.

This is my typings.json file.
```
{
  "globalDependencies": {
    "chai": "registry:dt/chai#3.4.0+20160601211834",
    "mocha": "registry:dt/mocha#2.2.5+20160720003353",
    "ws": "registry:dt/ws#0.0.0+20160405094435"
  },
  "dependencies": {
    "requirejs": "registry:npm/requirejs#2.2.0+20160319062357",
    "sinon": "registry:npm/sinon#1.16.0+20160427193336"
  }
}
```

**Comment by alitaheri** [comment] 2016-07-31 07:20
@nojvek Well that error is valid, in run-time that might cause problems, but in type-checking (which ambient deceleration files are for) it shouldn't matter. I guess there are 2 options here:

1. TS eases this rule for ambient declarations
2. The error is fixed in the [type definition repo](https://github.com/types/env-node/blob/master/6/node.d.ts)

I'd personally prefer the second option. Less complex compiler = easier life for all humans :sweat_smile:

**Comment by nojvek** [comment] 2016-07-31 07:26
Yeah I looked at the line to see if I could figure out why it was
happening. The import of net.stream was happening before it was use.

I still have no idea what ambient modules are though.

Typescript is slowly becoming this complex insane beast. When i see some
newer errors, it's not straightforward how to fix them.

**Comment by alitaheri** [comment] 2016-07-31 07:28
Hmmm, I just tried to fix this. The files seems to be compiled fine using the latest nightly build. Please make sure you're have the most updated definition files and latest installation of typescript. It might be already fixed.

**Comment by nojvek** [comment] 2016-07-31 07:30
I re-installed typings with dt~node. Using typescript@next which i
re-installed just now.

No luck.

**Comment by kitsonk** [comment] 2016-07-31 07:35
Duplicate of #10045 right?

**Comment by alitaheri** [comment] 2016-07-31 07:36
It is, but the node file compiles well. @nojvek could you try replacing the contents of your `typings/globals/node/index.d.ts` with [these](https://raw.githubusercontent.com/types/env-node/master/6/node.d.ts)?

**Comment by alitaheri** [comment] 2016-07-31 10:50
This issue broke a lot of type definitions. seems like this bug and typings don't play well.

**Comment by RyanCavanaugh** [comment] 2016-07-31 21:59
Apologies for the break, the nightly on Tuesday should have a fix (I'm assuming I'll be able to merge on Monday)

**Comment by RyanCavanaugh** [comment] 2016-07-31 21:59
Also this week we should have `typescript@next` validating against the `@types` (2.0) branch of DefinitelyTyped so this won't happen again

**Closed by RyanCavanaugh** 2016-07-31 21:59 UTC
Labels: Duplicate
