### ISSUE TITLE
Type 'number[]' is missing the following properties from type '[any, any, ...any[]]': 0, 1

### ISSUE THREAD

**Issue by ChangXiaojiejie** [Microsoft/TypeScript#30306] opened 2019-03-10 12:41 UTC
The following code, why the call to the incoming arr will give an error？

code:
var arr = [1, 2, 3, 4]
function someArr([num1, num2, ...others]) {
console.log(num1)
console.log(num2)
console.log(others)
}
someArr(arr)

error:
![Snipaste_2019-03-10_20-31-55](https://user-images.githubusercontent.com/44471663/54085094-a2511180-4374-11e9-84b2-3ba8bd27266c.png)

**Comment by ChangXiaojiejie** [comment] 2019-03-10 13:11
I've found a way to declare arrays and define variable types, and I don't know why I'm doing that, but I hope someone can explain why？

update code：
`var arr: [number, number, ...any[]] = [1, 2, 3, 4]
function someArr([num1, num2, ...others]) {
  console.log(num1)
  console.log(num2)
  console.log(others)
}
someArr(arr)`

success:
![Snipaste_2019-03-10_21-10-35](https://user-images.githubusercontent.com/44471663/54085426-fc53d600-4378-11e9-8f66-3b5fa151dccf.png)

**Comment by jack-williams** [comment] 2019-03-10 13:36
Duplicate of #30252.

**Closed** 2019-03-21 18:00 UTC
Labels: Duplicate
