### ISSUE TITLE
Can't discriminate based on fixed size array / Tuple length

### ISSUE THREAD

**Issue by safareli** [microsoft/TypeScript#42139] opened 2020-12-28 17:06 UTC
# Bug Report
Can't discriminate based on fixed size array / Tuple length. when you have Tuple in Union, and you try to discriminate based on it's length typescript can't handle it. Better to look at the code snippet.

### 🔎 Search Terms
discriminate based on Tuple length
### 🕗 Version & Regression Information
- This is the behavior in every version I tried (Nightly, 4.1.3 and 3.9.7)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggTgcxgOwCYDECuyDGAeAFQD4oBeAKCigB8oBvKAQ0QGcAuKAbQF0BuKAGbYcHABQBKMiQBuAewCWqKAF9KNek1YdOzBBwJ9Bwsbv2TSMhUuW9y5APT2oBABbyWUFi9mYANkoB3WTgAa3IhXGB5WWQmMDBfEABGQiJRXRQMY1hETKxcVMk6NUcoAFEAJQqAeQqoAAlKso4ygA9IHGAIJSTNBEwAWwhkYBYAGigAI0xgKARZWYAGKGCoAeCIADpRACYAVj2ANnE1DLR8nE2InFFNu7Os3E3dFhPVBycYWd8IRhZZ4BuDxeHz+KBBULhYRRGJxBIgHapdK5c7ZeBIVEFYhFEpOeoQODQVAE+TSbpQUCQDzMaACeTIaCMNDglyMWYxaBBPxKCDtCCdU4ox6XF78Uo8dQ6RD6biCjHCq7CMVOMQSKRQOSKSS0UTIvTOcyWLV2KjyARQPV5YTPVibH7IBCAsikUhQJI4qhUUr4wkU8C01YAAweFxtCBYgag7igxLgpPJYDgskgcESaioIetLygpW0pmcss9OacACEZlBkAtBKtM09rum+la60ri1BVYaNVZtRa9WZ1ZrUCciw3Sq5oxCQtSPNcYbFZObK31BsNZtGWJhJiwIOzzRyl0MRkZItFkA3a5drpbMSLWJxFtxxLYqKpTearwqXnbho6XM7XYsPU9b0CWgSkAzgKBgyFUMXkjaNY3jJRE2TAk0yLc8wxYZU2y4QsgNLctK1mAQa2g6163Qsjm1wbD237Lt1F1fMCA7Ach09EcnEqGo6kaCpmnKPlOnJXpdGXEZximct5iWbZ9j2AAWdiMyoi9hAkJ8VHIZQgA)

### 💻 Code

```ts
type ArgAndFunc<T> =
  | { args: []; func: () => void }
  | { args: [arg: T]; func: (arg: T) => void };

// This should work
function apply1<T>(argAndFunc: ArgAndFunc<T>) {
  // ERROR HERE: Expected 1 arguments, but got 0 or more.(2556)
  argAndFunc.func(...argAndFunc.args)
}

// At least this should work
function apply2<T>(argAndFunc: ArgAndFunc<T>) {
  // Here derived types are fine and what one would expect
  argAndFunc.args; // [] | [arg: T]
  argAndFunc.func; // : (() => void) | ((arg: T) => void)

  if (argAndFunc.args.length === 1) {
    // Here type for `argAndFunc.args` is derived properly
    argAndFunc.args // : [arg: T]
    // But not for argAndFunc.func
    argAndFunc.func; // : (() => void) | ((arg: T) => void)
    
    // This works as function of no argument is subset of one argument function
    argAndFunc.func(argAndFunc.args[0]);
  }
  if (argAndFunc.args.length === 0) {
    // Here type for `argAndFunc.args` is derived properly
    argAndFunc.args; // : []
    // But not for argAndFunc.func
    argAndFunc.func; // : (() => void) | ((arg: T) => void)
    
    // ERROR HERE: Expected 1 arguments, but got 0.(2554)
    argAndFunc.func();
  }
}
```

**Comment by safareli** [comment] 2020-12-28 17:17
"Solution" to this issue is to define custom type guard:

```ts
type ArgAndFunc<T> =
  | ArgAndFunc0
  | ArgAndFunc1<T>

type ArgAndFunc0 = { args: []; func: () => void }

type ArgAndFunc1<T> = { args: [arg: T]; func: (arg: T) => void };

function hasEmptyArgs<T>(r: ArgAndFunc<T>): r is ArgAndFunc0 {
    return r.args.length === 0;
}

// This way it "WORKS"
function apply2<T>(argAndFunc: ArgAndFunc<T>) {
  // Here derived types are fine and what one would expect
  argAndFunc.args; // [] | [arg: T]
  argAndFunc.func; // : (() => void) | ((arg: T) => void)

  if (hasEmptyArgs(argAndFunc)) {
    argAndFunc.args; // : []
    argAndFunc.func; // : (() => void)
    argAndFunc.func();
  }else {
    argAndFunc.args // : [arg: T]
    argAndFunc.func; // : ((arg: T) => void)
    argAndFunc.func(argAndFunc.args[0]);
  }
}
```
[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggTgcxgOwCYDECuyDGAeAFQD4oBeAKCigB9ZEUNscAGSmupNLXARkKPLlQkDg24syUAN5QAhogDOALigBtALoBuKADMmKgBQBKMiQBuAewCWqKAF9Bw6PE6Ne-STPkJla7yoItXX0oA38oAhNSc2tbO01BPVxgKwtkKAALWQUAUQBbMFAXBX4DOBUXMSZ+IxU4KCsFUS4mZmk2KjgIYEw4dLgAOm8FAYAbCGQEYAyyUlIoZgSHcgB6FYiMxqgAd1kQBuAoACIAdQB5ACUAaQBlI-IknBS0uTAwUZAAJlLvKtwK+gtXA1dpUNZQAASEC6UFQ0KsZggticTXk0B0VmQ0FkaB2WUOaWg2wsmFGtggAA9IE82L8gTghoptOCNOxVOFArTAW4GY9metDMZTFBLDYTLQDGFEAEojExYIqFYdKEsrkCkVFFLXOIjCYpB05NzxIyfPyoCoNAa6TyBnyoODBbKRbEjFajUxbUxjAkqHYIKMFNB9VQqNbjcN7QK-NKIuo3dqPXaHaEtTLhaLUK6Q4aE7hPbgtX8GcNVMx1EYffZyHYgA)

**Comment by andrewbranch** [comment] 2020-12-29 00:17
Neither is obvious, but:

- `apply1` is a duplicate of #30581.
- `apply2` is a duplicate of #18758. You’re trying to narrow the outer union (`ArgAndFunc0 | ArgAndFunc1<T>`) based on guarding the inner union (`0 | 1`, actually nested two properties down).

**Closed** 2020-12-29 12:03 UTC
Labels: Duplicate
