### ISSUE TITLE
Type of elements not inferred if array type param extends tuple in conditional

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#28913] opened 2018-12-07 23:08 UTC
**TypeScript Version:**  3.3.0-dev.20181129

**Search Terms:** array, tuple, conditional, infer

**Code**

```ts
type ExpectNumber<T extends number> = (
    ["You gave me", T]
);
type Foo<ArrT extends number[]> = (
    ArrT extends [infer T0] ?
    //Type 'T0' does not satisfy the constraint 'number'.
    ExpectNumber<T0> :
    ArrT extends [infer T0, infer T1]?
    [
        //Type 'T0' does not satisfy the constraint 'number'.
        ExpectNumber<T0>,
        //Type 'T1' does not satisfy the constraint 'number'.
        ExpectNumber<T1>
    ] :
    never
);
```

**Expected behavior:**

`T0` and `T1` should satisfy the constraint `number`

**Actual behavior:**

`T0` and `T1` do not satisfy the constraint `number`

-----

My specific use-case is that it's an array of objects of a certain type and I want to merge them a certain way. Right now, the below code works for me but I decided to file this issue anyway because it felt weird to me that it didn't infer the elements to be of type `number`

```ts
export type IntersectTuple<ArrT extends NonEmptyTuple<ColumnRef>> = (
    ArrT["length"] extends 1 ?
    ArrT[0] :
    ArrT["length"] extends 2 ?
    Intersect<ArrT[0], ArrT[1]> :
    ArrT["length"] extends 3 ?
    Intersect<Intersect<ArrT[0], ArrT[1]>, ArrT[2]> :
    //add more lengths
    never
);
```

Unrelated to this issue but nesting `Intersect<Intersect<Intersect<Intersect<.....`  gave me an out-of-memory error =(

**Playground Link:** [here](http://www.typescriptlang.org/play/#src=type%20ExpectNumber%3CT%20extends%20number%3E%20%3D%20(%0A%20%20%20%20%5B%22You%20gave%20me%22%2C%20T%5D%0A)%3B%0Atype%20Foo%3CArrT%20extends%20number%5B%5D%3E%20%3D%20(%0A%20%20%20%20ArrT%20extends%20%5Binfer%20T0%5D%20%3F%0A%20%20%20%20%2F%2FType%20'T0'%20does%20not%20satisfy%20the%20constraint%20'number'.%0A%20%20%20%20ExpectNumber%3CT0%3E%20%3A%0A%20%20%20%20ArrT%20extends%20%5Binfer%20T0%2C%20infer%20T1%5D%3F%0A%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%2F%2FType%20'T0'%20does%20not%20satisfy%20the%20constraint%20'number'.%0A%20%20%20%20%20%20%20%20ExpectNumber%3CT0%3E%2C%0A%20%20%20%20%20%20%20%20%2F%2FType%20'T1'%20does%20not%20satisfy%20the%20constraint%20'number'.%0A%20%20%20%20%20%20%20%20ExpectNumber%3CT1%3E%0A%20%20%20%20%5D%20%3A%0A%20%20%20%20never%0A)%3B)

**Comment by falsandtru** [comment] 2019-01-31 21:04
Duplicate of #21937.

**Comment by AnyhowStep** [comment] 2019-08-25 18:29
Ah... I remember this.
This was before I knew of the `UnionToIntersection<>` trick.

Now, this can be rewritten as,
```ts
UnionToIntersection<ArrT[number]>
```

**Closed** 2019-08-26 12:30 UTC
Labels: Domain: Conditional Types, Duplicate
