### ISSUE TITLE
Add compiler flag to collapse module IIFEs   

### ISSUE THREAD

**Issue by mbebenita** [Microsoft/TypeScript#4652] opened 2015-09-04 20:42 UTC
If you have multiple classes in the same module namespace but defined in different files (or even just different `module` blocks) TypeScript's `tsc` will wrap every one of them into its own nest of IIFEs; one for each level of namespace nesting.

For deep namespace hierarchies this produces large amounts of code that increases code size and hurts parsing / loading performance.

To solve this problem, we use a post processing tool (https://github.com/tschneidereit/typescript-module-merger) to merge subsequent modules that appear in the same namespace. This is not a sound optimization but works well in practice. Such a feature should be part of the TypeScript compiler, perhaps under a compiler flag.

**Comment by danquirk** [comment] 2015-09-04 20:52
We've certainly had this request many times over the years (back before the GitHub era). We generally do few optimizations (and particularly not type directed ones) and have been very hesitant to ever do one that isn't guaranteed to be safe, even if it's under a special flag. How much is your code size changed using this tool vs not?

**Comment by mbebenita** [comment] 2015-09-04 21:41
We've seen `~3-4%` overhead due to module IIFEs in the final build, after running the closure compiler and removing whitespace on fairly large files (1MB+).

**Comment by danquirk** [comment] 2015-09-04 22:39
Did you run closure with other minifications on or just removing whitespace?

**Comment by mbebenita** [comment] 2015-09-05 02:41
We use a custom build of closure that renames locals but leaves property names alone.

**Comment by aleksey-pastuhov** [comment] 2015-09-14 17:04
Similar to my [Suggestion](https://github.com/Microsoft/TypeScript/issues/4779)

**Comment by mhegazy** [comment] 2016-02-22 21:12
duplicate of https://github.com/Microsoft/TypeScript/issues/447

**Closed by mhegazy** 2016-02-22 21:12 UTC
Labels: Needs Proposal, Suggestion
