### ISSUE TITLE
Emitted design type metadata depends on the order of the declaration

### ISSUE THREAD

**Issue by mtrivolli** [Microsoft/TypeScript#7841] opened 2016-04-05 22:46 UTC
**TypeScript Version:** 

1.8.7

**Code**

```ts
import "reflect-metadata";

function dec(target: Object, propertyKey: string) {
}

it("Check emitted design types", () => {
    class B {
    }

    class A {
        @dec
        b: B;
    }
    
    // Works as expected
    expect(Reflect.getMetadata("design:type", A.prototype, "b")).toBeDefined();
});

it("Check emitted design types - reverse order", () => {
    class A {
        @dec
        b: B;
    }

    class B {
    }

    // Fails!!!
    expect(Reflect.getMetadata("design:type", A.prototype, "b")).toBeDefined();
});
```

**Expected behavior:** I'd expect design type metadata to be defined in both cases

**Actual behavior:** Only first case works as expected

**Comment by mhegazy** [comment] 2016-04-28 23:03
duplicate of https://github.com/Microsoft/TypeScript/issues/4114

**Closed by mhegazy** 2016-04-28 23:03 UTC
