### ISSUE TITLE
`String.startsWith`, `String.endsWith`, and `String.includes` should have type assertion for when search string is a string subtype

### ISSUE THREAD

**Issue by KSXGitHub** [microsoft/TypeScript#57929] opened 2024-03-25 15:48 UTC
### 🔍 Search Terms

"startsWith type assertion"
"endsWith type assertion"
"includes type assertion"

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

When I do `if (string.startsWith('https://'))`, I wish `string` turns into `${'https://'}${string}` because I use string subtype heavily in my code.

I wish for the following:

```typescript
interface String {
  startsWith<SearchString>(searchString: SearchString, position?: 0): this is `${SearchString}${string}`
  endsWith<SearchString>(searchString: SearchString, position?: undefined): this is `${string}${SearchString}`
  includes<SearchString>(searchString: SearchString, position?: 0): this is `${string}${SearchString}${string}`
}
```

### 📃 Motivating Example

```typescript
declare function handleHttpsUrl(url: `https://${string}`): Promise<void>
declare const url: string

if (url.startsWith('https://') {
  return handleHttpsUrl(url)
}
```

### 💻 Use Cases

1. What do you want to use this for? Codebase with strict typings
2. What shortcomings exist with current approaches? Has to either redefine the methods manually or use `as`
3. What workarounds are you using in the meantime? Redefine the methods manually

**Comment by MartinJohns** [comment] 2024-03-25 16:02
Duplicate of #46958.

**Closed** 2024-03-28 01:25 UTC
Labels: Duplicate
