### ISSUE TITLE
Discrimination partially lost for nested union type in closure

### ISSUE THREAD

**Issue by char-cole** [microsoft/TypeScript#34854] opened 2019-10-31 20:30 UTC
I have a union type, and one of the interfaces used to construct it has a property that is itself a union type. A conditional that narrows down both unions works in most cases (the first console.log has no errors ).

But a closure inside the if block loses the nested discrimination and causes an error. In the code below, `example.props` is narrowed to SavedQueryType in the if block, but is no longer narrowed in innerFunc. However, `example` remains discriminated

I searched around and wasn't sure if any of the other issues I saw were related or not. apologies if this has been addressed but nothing else looked like it was addressing quite the same issue

**Search Terms:** `control flow`, `discriminate`, `nested`, `closure`, `union`

**Code**

```ts
interface SavedQueryType {
  queryid: string
}

interface NewQueryType {
  tempid: number
}

interface QueryType {
  type: 'query'
  props: SavedQueryType | NewQueryType
}

type ExampleType = 
  | QueryType
  | { type: 'other' }

const func = (example: ExampleType) => {
  if (example.type === 'query' && 'queryid' in example.props) {
    console.log('outer', example.props.queryid)
    const innerFunc = () => {
      console.log('inner', example.props.queryid)
    }
    innerFunc()
  }
}
```

**Expected behavior:** `queryid` is logged from inner closure

**Actual behavior:** error given: `Property 'queryid' does not exist on type 'SavedQueryPropsType | NewQueryPropsType'.`

**Playground Link:** [Playground link](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191030&ssl=17&ssc=2&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgIoFdoE8AqWAOKA3gFDLJgEQBcyA5AI6ZRZ1nL5QD2+AzrUWRNswACa1eYKKADmyAL7IAPskGQAtvjG0Q6dQCNoCkvJKVCyAKIAPOJoA2EPBYC8ydiozZnED6opUtHRcYAAW0HTGJAhcIJLIMOggCMhuABQQtg40Vln4jj4AlKkAfKrswDDIGXmOAHTmKC7N9MIskQBkHa3MWGKRoMiZdvkQdZw8vMWk5OQxcVz19lwyNSP1E3x1bX2ihexzsfGgINAAYkkp6cUuZTOzhwtLK2vZ49xbO2L7D6YPJ+dLmkfsZTNEjmAhrUIAB5fQAKwgCDAtBs6ycVFS5XIjSCOzoABp2Jt+NjZl9xPQANYgLgAdxAAFp8exTGDEslXqM4YjkYUgA)

**Related Issues:**

**Comment by MartinJohns** [comment] 2019-10-31 21:38
Duplicate of #9998.

**Closed** 2019-11-07 18:00 UTC
Labels: Duplicate
