### ISSUE TITLE
NuGet package Microsoft.TypeScript.MSBuild is incompatible with .NET Framework 4.0

### ISSUE THREAD

**Issue by flcdrg** [Microsoft/TypeScript#10244] opened 2016-08-10 05:02 UTC
**TypeScript Version:**  1.8.11

Trying to build a .NET 4.0 project that references Microsoft.TypeScript.MSBuild 1.8.11 on a computer that only has .NET Framework 4.0 (not .NET Framework 4.5) fails.

**Expected behavior:**

Package should indicate a dependency on .NET 4.5 because an included .targets file makes use of the KeepDuplicates attribute ([which was only introduced in .NET Framework 4.5](https://msdn.microsoft.com/en-us/library/ms171453.aspx#BKMK_KeepDuplicates))

**Actual behavior:** 

Error:
`packages\Microsoft.TypeScript.MSBuild.1.8.11\tools\Microsoft.TypeScript.targets (159,44): error MSB4066: The attribute "KeepDuplicates" in element &lt;ConfigFiles&gt; is unrecognized.`

**Comment by mhegazy** [comment] 2017-04-27 22:52
Duplicate of https://github.com/Microsoft/TypeScript/issues/12739

**Closed by mhegazy** 2017-04-27 22:52 UTC
