### ISSUE TITLE
The literal type extends corresponding to the parent class has no expected result

### ISSUE THREAD

**Issue by Nctdtman** [microsoft/TypeScript#42643] opened 2021-02-04 14:02 UTC
# Bug Report
### 🔎 Search Terms
`StringLiteral extends string has no expected result`
`NumberLiteral extends number has no expected result`
`The literal type extends corresponding to the parent class has no expected result`
### 🕗 Version & Regression Information
- This is the behavior in every version I tried
### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggdgSwLYEMA2UC8UDeU4pIQBcUAzsAE4JwDmUAvgFCiRQAiA9vdvMulABkuKACMUlANYAKAJSkAbpwQATRi3DQAQgkpreiVBmF4AZmhBzFytcxUQAxmgnRTAVzgPgCTnCgB1TgB3AB4AFQA+aQlaUjD5KDCoCAAPYAg4FTJYQwEAfkSoUg9JOGC4JnsnFygHXwoxXRVSHT1Kx2dKaDq4BpVuUi5aJkCg6VEm2SgAemmod09vXwDgkNaVKJiWye229uqu+Y8vHz8tCXDNyljEhLD9ztdjpbOUAC8AZSpL6Ou4u+SaQyWXIVBo9AKSWKcFK5QeNQWJ2W5zeADk3EgfltbnFAelMtk4BjRBBKFBIUUoCUykEKudKNIAOQARgATABmRlTWZHRanKD0kIAIjZ7KFVxuIo5QoSUrFTHp0lF3LmiJeAouoolpGVOo5CveXwZLI5XJmque-JRIQo1Do2tBdtoCVt4INaIxSo5Kt5SNeHsxRKQJMoDqDIYS4dJQA)

### 💻 Code
```ts
type Animal = { name: string }
type Dog = Animal & { bark(): void }
type Bird = Animal & { fly(): void }
declare function Wow<T>(arg: T): T extends Animal ? T : unknown
declare const bird: Bird
declare const dog: Dog
Wow(bird) // function Wow<Bird>(arg: Bird): Bird 

declare function Bar<T>(arg: T): T
declare function BazStr<T>(arg: T): T extends string ? T : unknown
declare function BazNum<T>(arg: T): T extends number ? T : unknown
Bar('123') // function Bar<"123">(arg: "123"): "123"
Bar(123) // function Bar<123>(arg: 123): 123
BazStr('123') // function Baz<string>(arg: string): string
BazNum(123) // function BazNum<number>(arg: number): number
```

### 🙁 Actual behavior
Generic subclass extends parent class can return correct generic subclass.
But Generic literal extends Corresponding to the parent class return the parent class.

### 🙂 Expected behavior
```
BazStr('123')// function BazStr<'123'>(arg: '123'): '123'
BazNum(123) // function BazNum<123>(arg: 123): 123
```

**Comment by MartinJohns** [comment] 2021-02-04 14:19
Duplicate of #22839.

**Comment by Nctdtman** [comment] 2021-02-05 17:59
> Duplicate of #22839.
> 
> You can work around this using const contexts: `BazStr('123' as const)`

...I think it is different.
I clearly stated method generics and method return value types.
But the type inference inside TS infers the string literal generic as the string generic.

**Comment by RyanCavanaugh** [comment] 2021-02-05 18:09
This is the intended widening behavior

**Comment by Nctdtman** [comment] 2021-02-05 18:43
> This is the intended widening behavior

Thanks, but I still have some curiosity.
How to infer the generic `T` when `BazStr('123')` is running.
- 
  1. `T` start with `'123'`
  2. `T` meets `extends`, TypeChecker thinks that the function includes changes, so `T`. is inferred to be string type and returns.
-
  1. `T` start with `string`
  2. `string extends string ? string : unknown`, so `T` is string type.
Finally, I want to learn some knowledge about TypeChecker at runtime. Can you recommend some ways, thank you.

**Closed** 2021-02-08 20:00 UTC
Labels: Working as Intended
