### ISSUE TITLE
Error: Could not find file in 'getValidSourceFile' during 'getApplicableRefactors'

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#21791] opened 2018-02-09 01:19 UTC
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.1
**VSCode Version** 1.20.0-insider
**command requested**: getApplicableRefactors
**hitting sessions**: 3432
**proportion of all sessions**: 0.012812041527141594
**stack**
```
Error: Could not find file
    at getValidSourceFile (tsserver.js:82699:23)
    at Object.getApplicableRefactors (tsserver.js:83298:24)
    at IOSession.Session.getApplicableRefactors (tsserver.js:90156:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89112:61)
    at unknown (tsserver.js:90355:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90346:28)
    at IOSession.Session.executeCommand (tsserver.js:90355:33)
    at IOSession.Session.onMessage (tsserver.js:90375:35)
    at Interface.<anonymous> (tsserver.js:91576:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mhegazy** [comment] 2018-02-09 18:00
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/20785

**Closed** 2018-02-09 18:00 UTC
Labels: Bug, Duplicate, Source: Telemetry

**Comment by aozgaa** [comment] 2018-03-05 05:00
This issue reproduced in the following context:
**TypeScript Version Prefix**: 2.7.2
**VSCode Version** 1.21.0-insider
**command requested**: getApplicableRefactors
**hitting sessions**: 609
**proportion of all sessions**: 0.012502822886940811
**stack**
```
Error: Could not find file
    at getValidSourceFile (tsserver.js:82897:23)
    at Object.getApplicableRefactors (tsserver.js:83496:24)
    at IOSession.Session.getApplicableRefactors (tsserver.js:90354:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89310:61)
    at unknown (tsserver.js:90553:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90544:28)
    at IOSession.Session.executeCommand (tsserver.js:90553:33)
    at IOSession.Session.onMessage (tsserver.js:90573:35)
    at Interface.<anonymous> (tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```
