### ISSUE TITLE
"Decorators are not valid here" for methods inside an instantiated class

### ISSUE THREAD

**Issue by nevir** [Microsoft/TypeScript#8257] opened 2016-04-22 21:49 UTC
**TypeScript Version:** 1.8.10

**Code**

```ts
export default new class Foo {
  @someDecorator
  someMethod() {}
}
```

Will result in an error on `@someDecorator`:

```
error TS1206: Decorators are not valid here.
```

---

It can be worked around via

```ts
class Foo {
  @someDecorator
  someMethod() {}
}
export default new Foo();
```

**Comment by mhegazy** [comment] 2016-04-22 23:15
duplicate of https://github.com/Microsoft/TypeScript/issues/7342

**Closed by mhegazy** 2016-04-22 23:15 UTC
