### ISSUE TITLE
namespace-private

### ISSUE THREAD

**Issue by JonathanMEdwards** [Microsoft/TypeScript#7277] opened 2016-02-28 01:39 UTC
When building a large library many classes need to define fields and methods that are meant only for use by other classes within the library, not the client. There is no simple way to express this in TypeScript. One can duplicate the entire public API in a set of mirror interfaces classes, but that creates a lot of duplicated code & doc maintenance, and sometime you really want to expose class names to the client. There appears to be a common convention of using the @internal JSDoc tag in this situation but it is not enforced by the compiler nor recognized by JSDoc. 

The solution in Java is package-private access. The analogous mechanism in TS would be namespace-private access.

**Comment by DanielRosenwasser** [comment] 2016-02-28 03:10
> but it is not enforced by the compiler nor recognized by JSDoc.

The compiler flag you're looking for is `--stripInternal`, but it's not fully supported.

Is it fair to say this is a duplicate of #321?

**Comment by JonathanMEdwards** [comment] 2016-02-28 03:40
Ah thanks. Perhaps more closely a duplicate of #5228
A fully supported --stripInternal would solve the problem. An 'internal' declaration modifier is a cleaner way to provide that without the noisy @internal JSDoc flag.

**Closed** 2016-03-03 20:32 UTC
