### ISSUE TITLE
TS2532 when class member assigned to local variable

### ISSUE THREAD

**Issue by AkhmedovValikhan** [Microsoft/TypeScript#26628] opened 2018-08-23 10:36 UTC
TS version: 3.0.1

Hi, I have weird situation. The code below seems pretty simple to infer that `myVar` cannot be null or undefined, but I am still getting this error (TS2532). Is ts compiler not capable to do this yet?
Please ignore render and console being underlined red, those are tslint errors.
Thanks.
P.S. Sorry if this question was asked before, I look through all issues related to this error code.

![image](https://user-images.githubusercontent.com/9393189/44520523-bd11b080-a6d8-11e8-96ea-c02d1261458d.png)

**Comment by AlCalzone** [comment] 2018-08-23 10:52
I don't recall the prior issues, but AFAIK typescript does not narrow based on the value of other variables. If you used
```ts
if (this.myVar) { ... }
```
you wouldn't get the error. I'm assuming this is a simplified repro, as you could always just remove the `|null` from the type declaration (after all, myVar is readonly).

**Comment by mattmccutchen** [comment] 2018-08-23 14:01
AlCalzone is right.  Duplicate of #24865.

**Closed** 2018-12-14 18:00 UTC
Labels: Duplicate
