### ISSUE TITLE
type alias is not inferred in async functions 

### ISSUE THREAD

**Issue by fogfish** [microsoft/TypeScript#32681] opened 2019-08-02 12:15 UTC
**TypeScript Version:**  3.5.3

**Search Terms:** promise, async function, return type in ES5/ES3

**Code**

```ts
type Response = {statusCode: number, body: string}
type IO = Promise<Response>

export async function main(): IO {
  return Promise.resolve({statusCode: 200, body: "ok"})
}
```

**Expected behavior:**
Successful compilation 

**Actual behavior:**

```
error TS1055: Type 'IO' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.

4 export async function main(): IO {
```

```
// tsconfig.json
{
  "compilerOptions": {
    "target":"ES2018",
    "module": "commonjs",
    "lib": ["es2016", "es2017.object", "es2017.string", "dom"],
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": false,
    "inlineSourceMap": true,
    "inlineSources": true,
    "experimentalDecorators": true,
    "strictPropertyInitialization":false
  }
}
```

**Playground Link:** 
Unable to reproduce in playground
 
**Related Issues:** 
No

**Comment by MartinJohns** [comment] 2019-08-02 17:15
Duplicate of #32574.

**Closed** 2019-08-05 18:00 UTC
Labels: Duplicate
