### ISSUE TITLE
React transform uses wrong `this` in arrow functions.

### ISSUE THREAD

**Issue by JabX** [Microsoft/TypeScript#8006] opened 2016-04-11 13:26 UTC
**TypeScript Version:** 
1.8.9 (using `"jsx": "react"`)

**Problem**
When outputting a JSX element in an arrow function, the `this` calls in a JSX element properties aren't properly transpiled to `_this`, causing runtime errors when trying to access it.

**Exemple**
This piece of code
```ts
render() {
  return (
    <div>
        {data.map((line, index) => {
             const props = this.props;
             return  <li style={this.state.style}>{props.text}</li>;
        })}
    </div>
  );
}
```
gets transpiled like this (in ES5)
```ts
render() {
  var _this = this;
  return (
    React.createElement('div', null,
        data.map(function (line, index) {
             var props = _this.props; // OK
             return React.createElement('li', {style: this.state.style}, {props.text}); // Not OK
        }));
  );
}
```
EDIT : It looks like the behaviour is not consistent. Sometimes it gets properly transpiled, some other times it doesn't, even for the same component.

This is happening in JS files being transpiled by the way. I don't know if it makes any difference.

**Comment by RyanCavanaugh** [comment] 2016-04-11 15:22
> Sometimes it gets properly transpiled, some other times it doesn't, even for the same component.

Do you mean it's inconsistent between compilations (non-deterministic), or inconsistent within a file (deterministic, but not predictable)?

The code snippet here doesn't show the behavior you're describing; can you post a self-contained example that does?

**Comment by JabX** [comment] 2016-04-11 15:48
It's deterministic, but inconsistent. I've updated my post to show the transpiled file I'm getting.

Below is an exemple of inconsistance:
```ts
render() {
        return (
            <div>
                {data.map(item => {
                    return item.isEdit ?
                        <Checkbox
                            name={this.props.name}
                            onChange={this._onClickCheckBox.bind(null, code)}
                        /> :
                        <DisplayCheckBox
                            name={this.props.name}
                        />
                })}
            </div>
        );
    }
```
gets transpiled in
```ts
render() {
        var _this = this;
        return React.createElement('div', null,
            data.map(function(item) {
                return item.isEdit ?
                    React.createElement(Checkbox, {
                        name: this.props.name, // Not OK
                        onChange: _this._onClickCheckBox.bind(null, code) // OK
                    }, null)
                    :
                    React.createElement(DisplayCheckbox, {
                        name: _this.props.name // OK
                    }, null);
                    
            }));
    }
```

**Comment by RyanCavanaugh** [comment] 2016-04-11 15:54
I can't get this to repro (using either `master` or `release-1.8`).

Input:
```ts
class X {
    render() {
        return (
            <div>
                {data.map(item => {
                    return item.isEdit ?
                        <Checkbox
                            name={this.props.name}
                            onChange={this._onClickCheckBox.bind(null, code)}
                        /> :
                        <DisplayCheckBox
                            name={this.props.name}
                        />
                })}
            </div>
        );
    }
}
```

Output:
```ts
var X = (function () {
    function X() {
    }
    X.prototype.render = function () {
        var _this = this;
        return (React.createElement("div", null, data.map(function (item) {
            return item.isEdit ?
                React.createElement(Checkbox, {name: _this.props.name, onChange: _this._onClickCheckBox.bind(null, code)}) :
                React.createElement(DisplayCheckBox, {name: _this.props.name});
        })));
    };
    return X;
}());
```

**Comment by JabX** [comment] 2016-04-12 06:43
I can't get to repro either at home on the exact same file that gets wrongly transpiled at work, using the same TS version (1.8.9). I'll try to investigate more and come back at you when I can repro it consistently (I hope).

**Comment by mhegazy** [comment] 2016-04-14 18:21
closing for now. please reopen if you have more information.

**Closed by mhegazy** 2016-04-14 18:21 UTC
Labels: Needs More Info

**Comment by rankida** [comment] 2016-05-06 09:02
Hi,

I, strangely, have stared seeing this problem. I have just updated to VS2015 Community Update 2. I uninstalled TypeScript and Visual Studio then did a fresh install of VS2015 UP2.

Now when I save a `.ts` file it fails to swap references for `this` in lamda functions for `_this`. Oddly a build of the project in visual studio **works**.

So what I have just now is working javascript from a VS project build (it is a C# MVC proj) but **faililng** javascript from _Compile on Save_

Can anyone tell me how I can work out what the differences are between build and compile on save?

My colleagues have also updated to VS2015 UP2 and have no issues, so it appears to be a strange environmental issue.

It is worth saying that I have had problems in the past with TS1.8 installs (#7210) so I wonder if there is something kicking about on my machine from a previous bad install (though I did uninstall everything I could see for TypeScript and Visual Studio).

Any help would be appreciated.

Thanks

**Comment by mhegazy** [comment] 2016-05-06 20:07
can you share a project we can look at?

**Comment by rankida** [comment] 2016-05-10 15:10
Hi @mhegazy 

I am having problems working out what causes it. I managed to go through all of yesterday without an issue, but today the compile on save is causing problems occasionally. Interestingly one of my colleagues has seen the same issue once today.

So I don't have a easy example for you. What would help?

David

**Comment by mhegazy** [comment] 2016-05-10 16:29
Ideally we would have a consistent reproduction for the issue. if not, can you think of events that are correlated with this issue? looks like it is only compile-on-save, and not build. has a full build ever caused this? are there specific errors you remember seeing when this issue happened? is it after adding a new file? does it happen when you save a specific file? or a specific file save sequence?

**Comment by rankida** [comment] 2016-05-10 20:01
It only appears to happen for a few lamda captures.

I think I have an example I can send through to you'r microsoft email within the hour.

**Comment by rankida** [comment] 2016-05-10 20:31
@mhegazy I have just sent you an email with various zip attachments so hopefully it wont bounce.

Let me know if you don't see it in the next few minutes

Thanks!

**Comment by rankida** [comment] 2016-05-12 09:48
Yes, I thought the issue appeared to be very similar to #7212. I have previously had this version of TS installed and uninstalled it (with difficulty) after problems arose. Since then I have always been suspicious of what version of TypeScript was actually being invoked, in spite of what Add/Remove programs says.

I have been unable to find the registry key `HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\TypeScriptLanguageService\CustomTypeScriptServicesFileLocation` There is no `TypeScriptLanguageService` key inside `14.0`. I checked on another machine and I didn't find it there either. I have attached a list of some TypeScript relevant keys in my registry, but none appear to be paths.
[TypeScriptRegistry.txt](https://github.com/Microsoft/TypeScript/files/261000/TypeScriptRegistry.txt)

Attached is a copy of my `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript\typescriptServices.js`
[typescriptServices.zip](https://github.com/Microsoft/TypeScript/files/260964/typescriptServices.zip)

**Comment by smeeke** [comment] 2016-05-13 07:31
I too am having this issue with the same code but on a different machine. Clean Surface Pro 4, new install of VS2015 at start of year. Having been working with code base since then with no issues. A week after updating to update 2, typescript 1.8.30 I've started having 'this' issues. I skipped all previous updates due to the issues others have had.
Un-touched code now fails, removing the single js output file and rebuilding made the issue go away a few times but it has now returned and I'm unable to build working output.

**Comment by mhegazy** [comment] 2016-05-13 16:45
@smeeke do you have this happening consistently? can you share a repro?

**Comment by smeeke** [comment] 2016-05-14 07:49
Same code base as already supplied by @rankida I'm afraid - just wanted to highlight issue was happening on a different machine to give input on possible install / environment issues.
Got it building in the end but had to re-boot machine. Exiting visual studio didn't seem to be enough but that could just have been the same fault hitting after re-start.
It seems to go wrong in bursts then go away for a while. Mostly, clearing out the composite files and rebuilding makes it go away for the next build but haven't been able to determine a repeatable pattern.
Will try to isolate, but it's a pretty sprawling code base.
