### ISSUE TITLE
Support JSDoc parameters with properties using `@param`

### ISSUE THREAD

**Issue by BrunnerLivio** [Microsoft/TypeScript#16056] opened 2017-05-24 12:08 UTC
This is a suggestion/feature request for the @ts-check feature.

When using `// @ts-check` in a JavaScript file, TypeScript-check should be able to identify object properties types using JSDoc.

For example:
```TypeScript
// @ts-check
/*
 * @param {Object} bar The bar object
 * @param {Number} bar.id The id of the bar object
 * @param {Object} bar.foo The foo object
 * @param {Number} bar.foo.id The id of the foo object
 */
export function Foo(bar) {
  console.log(bar.id); // TypeScript: "Holy moly it is a number"
  console.log(bar.foo.id); // TypeScript: "OMG another one"
}
```
Also described on [JSDoc](http://usejsdoc.org/tags-param.html#parameters-with-properties).

I hope you get the idea :)
Keep up the good work!

**Comment by mhegazy** [comment] 2017-05-24 16:54
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/11597

**Comment by mhegazy** [comment] 2017-06-08 16:13
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-06-08 16:13 UTC
Labels: Duplicate
