### ISSUE TITLE
consider allowing to specify the exact file instead of a folder that has a tsconfig.json

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#5705] opened 2015-11-17 20:32 UTC
seriously, each tsconfig.json has to have its own folder in order to be referenced with `--project` parameter

- **What if I need 2 projects based on the same set of files?**

**Comment by RyanCavanaugh** [comment] 2015-11-18 05:51
This would be really nice.

**Comment by DanielRosenwasser** [comment] 2015-11-18 07:54
Behold, ask and ye shall receive a ~2 month old pull request from @SaschaNaz which incredibly has absolutely no merge conflicts right now: #4883

Also that sort of makes this a duplicate of #2869, though I'm leaving this open for the sake of discussion.

**Comment by aleksey-bykov** [comment] 2015-11-19 14:07
Since `--project` is taken already I suggest the `--configuration` parameter

**Comment by mhegazy** [comment] 2015-11-19 18:07
this is a duplicate of  #2869. we should revive  #2869 as well as #4883

**Closed by mhegazy** 2015-11-19 18:08 UTC
Labels: In Discussion, Suggestion
