### ISSUE TITLE
Separated internal module to a single function

### ISSUE THREAD

**Issue by aleksey-pastuhov** [Microsoft/TypeScript#4779] opened 2015-09-14 16:32 UTC
Why TS generates two functions, but not one?

We have one module separated between two files in TS, or in one file, but separated by other code. And we need to call F1 from F2. But do not need to cal F1 outside of `Main` module. Now we can write just like this:
```TypeScript
module Main {
    export function F1() {
    }
}
module Main {
    export function F2() {
        F1();
    }
}
```
And it compiles to JS as two independent functions, so user can access F1 function:
```JavaScript
var Main;
(function (Main) {
    function F1() {
    }
    Main.F1 = F1;
})(Main || (Main = {}));
var Main;
(function (Main) {
    function F2() {
        Main.F1();
    }
    Main.F2 = F2;
})(Main || (Main = {}));
```
But it seems to me that it will be better to concatenate the content of the modules with single name to one function. Like this JS output:
```JavaScript
var Main;
(function (Main) {
    function F1() {
    }
    function F2() {
       F1();
    }
    Main.F2 = F2;
})(Main || (Main = {}));
```
So there will be no need to create additional export members just to allow execute one members from the others inside one module.

p.s. Such code will fail:
```TypeScript
module Main {
    function F1() {
    }
}
module Main {
    export function F2() {
        F1(); // error TS2304: Cannot find name 'F1'.
    }
}
```

**Comment by aleksey-pastuhov** [comment] 2015-09-14 18:48
I know that I can write:
```TypeScript
module Main {
    function F1() {
    }
    export function F2() {
        F1();
    }
}
```
But it is not a good idea, because sometimes I have very big classes and functions.

**Comment by danquirk** [comment] 2015-09-14 19:11
The problem is that it is not generally safe to merge module/namespace declarations like this. We would have to figure out if/when it's safe and only merge then (or does the user need to specify it?). We'd like also need https://github.com/Microsoft/TypeScript/issues/892. In any case, there is another suggestion already logged to track this idea but I can't find it at the moment. Someone wrote a node package that can perform the optimization for you but it is up to you to ensure the optimization is safe for your codebase.

**Comment by aleksey-pastuhov** [comment] 2015-09-14 19:23
@danquirk Yes, user need to specify. I found that suggestion after I created this one. It was created 10 days ago [#4652](https://github.com/Microsoft/TypeScript/issues/4652). You are right, there is an NPM package which will concatenate the output.. but IDE(VSCode, VS2015 or other) will message me an error(read P.S. of the issue). Internal is good idea. and probably what I want as result.

**Comment by danquirk** [comment] 2015-09-14 19:28
Thanks for finding that, I knew it was just the other day but search was failing me. I'm going to close this issue as a dupe, feel free to add your support/ideas to either of those suggestions.

**Closed by danquirk** 2015-09-14 19:28 UTC
