### ISSUE TITLE
No syntax highlighting for imported types in VS 2017.4.4

### ISSUE THREAD

**Issue by mtman** [Microsoft/TypeScript#20167] opened 2017-11-20 20:42 UTC
**Expected behavior:**
Colored `Category` and `Date`, at least.

**Actual behavior:**

![devenv_2017-11-20_21-31-02](https://user-images.githubusercontent.com/15874394/33040026-250dffcc-ce3a-11e7-8958-d79df3d23022.png)

I have tried everything mentioned here https://github.com/Microsoft/TypeScript/issues/14422:
- Installed and Uninstalled Syntax Highlighting Pack
- Deleted ~\\.vs\Extensions
- Deleted tmLanguage cache
- Copied TS tmLanguage files from Program Files to ~\\.vs\Extensions

**Comment by mhegazy** [comment] 2017-11-20 21:05
Duplicate of https://github.com/Microsoft/TypeScript/issues/2890. should be fixed in next release.

**Closed** 2017-11-20 21:15 UTC
Labels: Duplicate
