### ISSUE TITLE
Incorrect object is possibly undefined inside nested if statement

### ISSUE THREAD

**Issue by zainbhaila** [microsoft/TypeScript#55834] opened 2023-09-22 21:42 UTC
### 🔎 Search Terms

object is possibly undefined
type inference fails
if statement with two values followed by an if else

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about narrowing, undefined

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/DYUwLgBAbghsCuIIF4IDt7GAbgFAGMB7NAZ0lgRAEEAuCMgJwEs0BzAbQF0IIAfCeGgAmIAGYsQQlBC4FiZaHEQAhOoxYdu-QSPFpJ0nWIlDcTURAAUFRFT78bIZQEoIAb1w8e5q46quPLyDFSmk-ADpQNjAACzwggF9PLxBgEiRA4J5HMKUnSJBouOSeJKSgA

### 💻 Code

```ts
let value = null;
// these values are fixed here, but imagine that they are coming from query
const valueA: string[] | undefined = []
const valueB: string[] | undefined = undefined
if (valueA || valueB) {
    if (valueA) {
        value = valueA.length;
    }
    else {
        value = valueB.length;
    }
}

```

### 🙁 Actual behavior

'valueB' is possible undefined

one of valueA or valueB is truthy -> valueA is falsy if the `valueB.length` line is reached so `valueB` must be truthy

### 🙂 Expected behavior

No error (at least if the values are actually set at runtime and not static like in my example)

`valueB` is guaranteed to be truthy if that line is reached

### Additional information about the issue

My use case is slightly more complicated than my dumbed down demonstration of the issue, and I can't just do
```ts
if (valueA) {
    value = valueA.length;
}
else if (valueB) {
    value = valueB.length;
}
```

**Comment by fatcerberus** [comment] 2023-09-22 21:49
Duplicate of #30869.
[The compiler is not a proof solver](https://github.com/microsoft/TypeScript/issues/54252#issuecomment-1547984904)

**Comment by fatcerberus** [comment] 2023-09-22 21:57
More prosaically, the design of the type narrowing machinery is such that narrowing is atomic - it either happens or it doesn’t.  `a || b` is not enough information to narrow either one individually and there isn’t an intermediate state where the compiler can go “this check was done here, I’ll check back later to see if it affects any future type guards”.

**Closed** 2023-09-25 14:04 UTC
