### ISSUE TITLE
Design Meeting Notes, 4/19/23

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#53920] opened 2023-04-19 21:55 UTC
# Poor type inference when using `satisfies` with default function parameters

https://github.com/microsoft/TypeScript/issues/53780

* Should the contextual type implied by a `satisfies` be different from a type annotation?
* If the contextual type on something is `any`, does that change our mind?
  * It’s been in TS so long, might not want to mess with it
* Guiding principle: it should behave like you were assigning it to something of that type
* It does feel weird to say “`satisfies` doesn’t change the type of the expression!” and then it does in context-sensitive positions
* Conclusion: by design

**Comment by RyanCavanaugh** [comment] 2023-04-20 16:24
Adding my own color commentary to the above

 * Should the contextual type implied by a satisfies be different from a type annotation?
   *  No, this is going to create more confusion/consistency than it solves
 * If the contextual type on something is `any`, does that change our mind?
   * No
 * It’s been in TS so long, might not want to mess with it
   * Yes (this behavior, I believe, dates back to 0.8)
 * Guiding principle: it should behave like you were assigning it to something of that type
   * To reinforce: Given a piece of code with one operative type annotation, it's not per se surprising (and certainly not *wrong*) to prefer the type annotation over any other inferential hint (in this case, a parameter default). A common view (not shared by me FWIW) is "Everything should typecheck like its desugaring", and in this case the desugaring of the parameter default makes the implied behavior unambiguous.
 * It does feel weird to say “satisfies doesn’t change the type of the expression!” and then it does in context-sensitive positions
   * This was always an over-simplification and we should back off from this description
 * Conclusion: by design

I'd add two things that I think are useful axioms:
 * It's never wrong for TypeScript to see a program that would otherwise have a type error and make it not have an error by **safely upcasting** the type of an expression
 * It's never wrong for TypeScript to see a program that would otherwise have an implicit `any` and make it not have an implicit `any` by providing a type sourced from code that someone wrote on purpose

In any case, I think the motivating example is really this one, extracted from the PR discussion:
```ts
type StringOrNumberFunc = (x: string | number) => any;

const fn1: StringOrNumberFunc = ((x = "ok") => null);
fn1(32);

const fn2 = ((x = "ok") => null) satisfies StringOrNumberFunc;
fn2();
fn2(32);
```
The initialization of `fn1` should be legal. This is extremely longstanding behavior without complaint, and follows from the "It's ok to safely upcast" axiom. It also follow from the "check it like a desugar" POV, where `x` is transiently an optional implicit `any` until it picks up a type from context.

The initializer of `fn2` should not be an error either; this code isn't *so much different* from `fn1` that it needs its own new special set of rules. The programmer's intent on whether the zero-arg call is allowed is manifested in their choice to use `satisfies` versus a type annotation on the `const`.

Now, all of that said, invoking the "safe upcast" rule on `any` sucks. But having the contextual logic apply uniformly here is much more consistent, and avoids questions like how this would interact with things like generic cases where you might be contextually typed by a `T` that can obviously *be* `any`, and so on.

The scenario in OOP is probably the one place in TS where you should actually use the `Function` type (as `satisfies {[key: string]: Function; }`), since that's the only way to describe a function without implicitly creating a description of its parameters.

**Closed** 2023-10-26 16:51 UTC
Labels: Design Notes
