### ISSUE TITLE
Rogue debugger statement in src/compiler/debug.ts

### ISSUE THREAD

**Issue by mansona** [microsoft/TypeScript#51998] opened 2022-12-23 10:59 UTC
# Bug Report

### 🔎 Search Terms

debugger 

### 🕗 Version & Regression Information

This debugger statement was added in https://github.com/microsoft/TypeScript/pull/5358 and it seems to be intentional at the time. From my perspective, I find it odd that there would be a debugger statement committed to the code base that would interfere with other people's debugging sessions 🤔 

### ⏯ Playground Link

N/A

### 💻 Code

N/A

### 🙁 Actual behavior

When starting a debug session trying to debug something in **my** code I am breaking in the TS compiler code. 

### 🙂 Expected behavior

Only hit debugger statements in **my** code.

**Comment by MartinJohns** [comment] 2022-12-23 11:50
Duplicate of #46883. Used search terms: `debugger in:title`

**Comment by fatcerberus** [comment] 2022-12-23 13:27
From the discussion in the other issue: If you’re hitting this breakpoint at all, you’re doing something wrong.

**Closed** 2022-12-26 18:00 UTC
Labels: Duplicate
