### ISSUE TITLE
Type inference behave different with or without destructure

### ISSUE THREAD

**Issue by ngolin** [Microsoft/TypeScript#28599] opened 2018-11-19 12:39 UTC
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:** type inference behave different

**Code**

```ts
type Shape = {
  kind: 'circle',
  data: {
    radius: number
  }
} | {
  kind: 'square',
  data: {
    size: number
  }
};

function getAreaOkay(shape: Shape) {
  switch (shape.kind) {
    case 'circle':
      // okay
      return shape.data.radius;
  }
}
function getAreaFail({ kind, data }: Shape) {
  switch (kind) {
    case 'circle':
      // fail
      return data.radius;
  }
}
```

**Expected behavior:** the above two should be identical.

**Actual behavior:** they are not.

**Comment by AlCalzone** [comment] 2018-11-19 13:08
AFAIK, typescript doesn't narrow the type from one variable (`kind`) to a seperate one (`data`).

**Comment by ahejlsberg** [comment] 2018-11-19 14:40
This is a duplicate of #23613 and several others like it. The core design limitation is that the control flow analyzer doesn't track mutually dependent variables. We're tracking the issue in #12184.

**Closed** 2018-12-12 10:00 UTC
Labels: Duplicate
