### ISSUE TITLE
Repeated conditional spreading of object literals results in OOM

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#40754] opened 2020-09-24 21:25 UTC
**TypeScript Version:**  nightly (fc03982b73ebaabfdfd2ef25bc1538e86a635b7b)

**Search Terms:** spread, union, oom

**Playground Link:** [link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF0S4AueASuEjMADwoCuAtgEYgwA08tSSEIUKAfANwCwAKCEAzSijAYAlqngiAFAEoA3kPjr4Aek3wAKgE8ADgilp4UeOJkp4SEfABMAPXkoAtAEZF8aiDoM0ZgB3AAsGBBtTeAww+Cp-GFt7NEM4KGBbWgArcAw0NQ04DEoYG1VBDUqtHQB1KRikSiwYqNQQZnrEdmhDNBAzDCR4ZQBfeAB+Aqr4ADo5+TAcAG0PAF14ADINqemNReAlh3Wt4Z3d+FSkQwAGfGvGM40RxQfhCt3teDqY2xQES8M8E4YBCHSwyAgPT6AyGFjQUhQAHMOJkcpJ4PIAMQAZgALAAOACs2PGike6jmMwWy2xxw2p3e53UAOxUHwHleTI0LNo7M5u2e-OmlOpB1xdIZXOZMCuuLZ8A55KqANxvIVQqqgqVIv2S0JEvKUouMsMhPlisZTIBhLVFvOWstlR1ywAbAalZUAS7zRrzl7bb6ni9tfNdQB2d2O3YAsM+j3ck1hgNKh3nZ0HfGRo0A-FxqPTHPJ-PwVO7dNLACcWalAIreezJorRftweL5Y812rXIBHfrNZNHebAtbadDyw8a029MN-auE773YHHiH01LwrHBw8Rynktnhi3C6tA4cK81I7LG5WtJ3M8Xc9ZfPj0vvp8qa6q7fFN6fxrncsfxaegOqoAS2gYUpeHj6t+gEJnOZqgXuUGvkG4GzJBbowQ2c7eohd77i6KHqO+TqQRGWFIbGeFHnOSbUW+57rlSuoeJmFH4axh5+gO+JESWjEfpBVbsTR+51vR0YDk2EnEQJpHMcsDidiJ3FXEpXGSWp1x8SRGifOWDiTicyjVPAABiUgwJg8AAPI2QAsswEBIGAUCQvoSqfEBakeBp6heXBhiGXxny6f5OgGduxmeTo3lBQ4fmmXFDgnjJplhaZBnXtFxYBc+QUPuqMXKiaDjYiFOgZfpl4OF+OXnHlv5Bf+RW5bFgW1RV-FodVCkHA40H1R87X5QNiWNQCA1dVVEU1ZhQ3TBNpW4a1DUjU1DiEWloVyXps19Yc5ELVUS1qVRq3DSVZ3Tbt4XoQdDhscdlSnUFubbetk28R93XFQZwnPXtV1BeJF2LZ9pXSWDJ2VbdmWXtiymA3dcWI+NENXIjN09ftopLNiRnTsVqO+T9JPY39CNRUTbXA9iCVk4F9MU7T5bYtlNNrXThV2pdqPlT9M33XjeJdjDdMtbz4MSyzXNs4NnN80zCHQy9GOGNiNqC3DvUi-NivS6jK1S+LRuy5dbNHQbptM+dJtq3TdGq0DQts091sO6j73OyjTPfT76U67jurYgDHtA6joP2xHTNQ9Hd0OsVADCYRgAA1giiLwJgUD6GYIKcIC4jSBA0RhHAADkZgWH8mAgBkSDZLkydINZUCGMYsAwvAiIykE8AQAinAwBA+jwEE9QhGXEQ0PQiR2NP1DFQAogAHhgMAWKAhg-OkwD563GDMLQTTmB3sAgCgGCjwP-QDCEXAD0PsCjyGB0dkj4cFgOK23kaTUeG9B4dkP4RhoTioAviDsewujAPgP+XMIGwOAQHB2YCUwCRGAIQQIwgA)

**Related Issues:** #34853 addressed a related issue

An internal partner team is using this to conditionally override CSS properties (e.g. `...sizeLimited && { width: 100, height: 100 }` and is seeing OOM crashes in tsc and poor editor responsiveness.

**Comment by amcasey** [comment] 2020-09-24 21:28
The two most obvious solutions are:
1) Produce an error message before attempting something that will cause an OOM (in this case, in `getSpreadType`).
2) Handle it.  It might be possible to generalize #34853 to handle cases like this.  Arguably, once you get past 50 or so object literals in the union, you're probably no longer interested in their individual shapes and we can squash the type into a single object literal full of optional properties.

**Comment by weswigham** [comment] 2020-09-24 21:30
#34853 Originally handled objects with more than one key - it was just pared down to lower potential impact. If we have a good usecase, the fix can be broadened to objects with multiple keys.

**Comment by amcasey** [comment] 2020-09-24 21:35
I think retaining the union is valuable if it's small - a few dozen shapes - but not if it's large.  In the examples I'm looking at, they don't want the union at any size - the result is immediately cast to an uber type with all properties as optional.

**Comment by MrAndersen1** [comment] 2020-09-25 07:25
Just wanted to say that there are those of us who very much are interested in the individual shapes of 50+ literal objects in a union. I realise the performance impact though and perhaps our setup is sub-optimal, so maybe the solution for us would be to sacrifice some usability and create smaller unions that would have some overlap but would clear the bar.
However I'm not trying to start an argument here :) I just wanted to make it known.

**Comment by amcasey** [comment] 2020-09-25 16:55
@MrAndersen1 can you tell me more about your use case?  How many shapes do you usually need?  Hundreds?  Thousands?

**Comment by amcasey** [comment] 2020-09-25 16:58
Follow-up question: if you're already doing this, are you having performance problems?

**Comment by MrAndersen1** [comment] 2020-09-25 17:27
@amcasey Oh no I don't expect us to ever breach 100. Usually old content gets removed which reduces the unions some. 
Yeah we do have performance issues, however I have not sat down to find the root cause. Whenever you edit structures of these unions, however, vsCode is rather sluggish. Compilation time is high too but I'm not confident to point fingers at anything.
So the use-case goes something like: we have a lot of standalone projects, ~50-60, they do share a lot of code though. This shared codebase contains code to write, let's call it a tutorial, for all projects. Now most projects use the same shapes/instructions that composes a tutorial but whenever a new project needs a new shape they all get access to it. These tutorials are written in the shared codebase in order to be easy to expose.
We could obviously make these tutorials/tutorial-instructions project-specific but that won't happen unless it becomes a big issue.
Hope I made any sense.
Oh and  while I don't invoke tsc manually we do increase node's --max-old-space-size=8192 for the script that does, otherwise it crashes.

**Comment by amcasey** [comment] 2020-09-25 17:29
@MrAndersen1 50 is a made-up number, so I certainly have no objection to using 100 instead. :smile:

I don't suppose you can share a link to your repo?

**Comment by MrAndersen1** [comment] 2020-09-25 17:33
@amcasey well, see, thats all up to you guys :) we did get issues on an earlier version of typescript, 3.7.3 I think it was, which I believe was due to some limit being hit. That could be resolved by updating to 4.0.2 however, which I was grateful for heh.

No I can't share it sorry, would if I could.

**Comment by amcasey** [comment] 2020-09-25 18:31
Sounds like we want to do something similar to reverting https://github.com/microsoft/TypeScript/pull/34853/commits/7181c2af0922bf5d4f343abb5f9d2977487a5989, probably in the 4.2 timeframe.

**Comment by amcasey** [comment] 2020-09-30 20:45
Re-opening, since we decided to fix the perf issue too.

**Comment by amcasey** [comment] 2020-09-30 20:46
The remaining work is targeting post-4.1.

**Closed** 2020-10-12 22:40 UTC
Labels: Committed, Domain: Performance, Fix Available, Suggestion
