### ISSUE TITLE
Type guard is not working with `noUncheckedIndexedAccess` and destructuring

### ISSUE THREAD

**Issue by PunGy** [microsoft/TypeScript#52623] opened 2023-02-05 19:27 UTC
# Bug Report

When `noUncheckedIndexedAccess` is on and you try to use a type guard like `typeof list[index] !== undefined`, it would not work if `index` was created via destructuring assignment or from the tuple.

### 🔎 Search Terms

noUncheckedIndexedAccess index destructuring undefined tuple

### 🕗 Version & Regression Information

- Compiler error
- Tested in 4.1.5, 4.5.5, and 4.9.5.

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=4.9.5#code/MYewdgzgLgBAlmAJgUwB4wLwwIwCheiSwDaCKqAIgLqYzHZX6HQxQCuADgDbIBcdYNgFsARsgBONLPUbNYZNABVa7bsmIAGRgXAsucaPwCC48QEMAngB5BoiQD5a9ADQwATK4DM2uADMYABRQFhzIIP760KRIaFIYWADktmLiCQCUMADeuDAwcjC2tJFQ0eSMAL64foHBoeEwxaVo1JjxMEnCKelZOXm6sIVYjQqUFVX+QSFhEQYlI4pxickS3dm5+YMNs02oC7jlQA)

### 💻 Code

```ts
// index is a number
const index = 1
// indexD is a number
const [indexD] = [1]

const tuple: [number] = [1]
const indexT = tuple[0]

const list: Array<number> = [1, 2, 3]

// Block A
if (typeof list[index] === 'number') {
  // `num` has a `number` type
  const num = list[index]
}
// Block B
if (typeof list[indexD] === 'number') {
  // `num` has a `number | undefined` type
  const num = list[indexD]
}
// Block C
if (typeof list[indexT] === 'number') {
  // `num` has a `number | undefined` type
  const num = list[indexT]
}
```

### 🙁 Actual behavior

Type guard does not work with the `num` in the Block B and C

### 🙂 Expected behavior

`num` in the Block B and C should have the same type as the `num` in the Block A

**Comment by MartinJohns** [comment] 2023-02-05 20:22
Duplicate of #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.

**Comment by fatcerberus** [comment] 2023-02-05 20:26
Workaround: Assign `list[index]` to a `const` first then type-guard that.

**Comment by PunGy** [comment] 2023-02-06 14:08
> Duplicate of #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.

I see... But still quite strange that even when you declare something as a constant literal, for example:
```ts
const [indexT] = [1] as const // here indexT has a type '1', and still doesn't work
const index: number = 1 // index has a 'number' type, not literal 1

if (typeof list[indexT] === 'number') num = list[indexT] // number | undefined
if (typeof list[index] === 'number') num = list[index] // number
```

Very confusing behavior

**Closed** 2023-02-16 18:00 UTC
Labels: Duplicate
