### ISSUE TITLE
Provide access to property literals from an interface/class

### ISSUE THREAD

**Issue by UppaJung** [microsoft/TypeScript#13857] opened 2017-02-03 02:52 UTC
In many situations, programmers will need to create string literals that match the name of a property of an interface or class.  For example, if I'm creating a DynamoDb table to match a TypeScript interface for the data to be stored in that table, I'll need to provide string literals that match it to describe the data structure in my create table parameters.

   Programmers can currently use keyof to ensure a string matches a literal, but not to generate a string that matches the literal.  As such, when using the rename feature in Visual Studio/Visual Studio code to change the name of a property, programmers are left to manually change the literal strings to remove the type errors, whereas it would be better to see the string literals changed automatically.

   Something like the following would lead to code that is easier to maintain:

```ts
interface SampleInterface {
  prince: string;
}

if ("prince" === PropertyNames(SampleInterface).prince) {
  // the property is still named "prince"
} else {
  // the property is only formerly known as "prince" 
}
```

**Comment by mhegazy** [comment] 2017-02-03 03:03
Duplicate of https://github.com/Microsoft/TypeScript/issues/1579

**Closed** 2019-09-18 18:22 UTC
Labels: Duplicate
