### ISSUE TITLE
Ternary operator result not type checked correctly in getter

### ISSUE THREAD

**Issue by vstebunov** [microsoft/TypeScript#33592] opened 2019-09-25 14:03 UTC
**TypeScript Version:**  3.6.3
**Search Terms:** ternary operator type checked getter
**Code**

```ts
interface ITest {
        xxx: string;
}

class FailedState {
    private p: any;
    public get serverErrorTest (): ITest[] {
        return this.p ? 'jjj' : this.p;
    }
}
```

**Expected behavior:**

As this code:

```ts
interface ITest {
        xxx: string;
}

class SuccessState {
    private p: any;
    public get serverErrorTest (): ITest[] {
         if (this.p === true) {
            return 'jjj';
        } else {
            return [];
        }
    }
}
```
Catch error in compile time.
```
TS2322: Type '"jjj"' is not assignable to type 'ITest[]'.
```
**Actual behavior:**

Compile without errors.

**Comment by jcalz** [comment] 2019-09-25 14:37
... but that's just what happens when you use [`any`](https://www.typescriptlang.org/docs/handbook/basic-types.html#any), right?  

The whole point of `any` is to (mostly) disable type checking.  `any | "jjj"` is just `any`, so you're returning `any`, which matches `ITest[]` and everything else.  The lack of compiler error there is a feature, not a bug.  

On the other hand, your `SuccessState` code has two separate `return` statements, one of which returns `"jjj"` which does not match `ITest[]`.   There's no `any` in there, so you get the expected type checking.  

Is there something I'm missing here?

**Comment by wellrus** [comment] 2019-09-25 14:47
@jcalz 

The ternary operator is equivalent to the conditional operator. So why is the result different?

The ternary operator returns either type any or string, and not just a union of types any | string

In any case, consistent behavior of equivalent operators is expected.

**Comment by wellrus** [comment] 2019-09-25 14:52
@jcalz 

If you write an example in this form, there is also no error. But it is obvious that the result is erroneous.

interface ITest {
    xxx: string;
}

class FailedState {
    private p: any;
    public get serverErrorTest (): ITest[] {
        return true ? 'jjj' : this.p;
    }
}

**Comment by jack-williams** [comment] 2019-09-25 14:59
Duplicate of #31518.

**Comment by jcalz** [comment] 2019-09-25 15:03
> an example in this form

That part is a duplicate of #14206.

**Comment by RyanCavanaugh** [comment] 2019-09-25 15:35
I don't see what we could do here in a way that generalizes. A `return` statement is checked by seeing if its expression is assignable to the return type, and the expression is definitely of type `any` (the type `any | string` isn't really coherent; it's a different way of spelling `any`).

Any amount of indirection with `any` is liable to cause a program to be ill-formed; it's no different than if you had written
```ts
// arr: any[]
const arr = [null as any, "jjj"];
return arr[Math.random() > 0.5 ? 0 : 1];
```
There's not really a principled way of picking where to stop with "This rewritten program with more indirection should typecheck identically to some other form". Maybe we'll modify something in the future and cause this to be an error but the infectiousness of `any` is a known trade-off of its use.

**Closed by RyanCavanaugh** 2019-09-25 15:35 UTC
Labels: Design Limitation
