### ISSUE TITLE
Node 10 types are incompatible with typescript lib types

### ISSUE THREAD

**Issue by nojvek** [Microsoft/TypeScript#23769] opened 2018-04-29 16:18 UTC
```
node_modules/@types/node/index.d.ts(2381,15): error TS2300: Duplicate identifier 'URL'.
node_modules/@types/node/index.d.ts(2399,15): error TS2300: Duplicate identifier 'URLSearchParams'.
node_modules/@types/node/index.d.ts(2417,14): error TS2661: Cannot export 'URL'. Only local declarations can be exported from a module.
node_modules/@types/node/index.d.ts(2417,19): error TS2661: Cannot export 'URLSearchParams'. Only local declarations can be exported from a module.
node_modules/typescript/lib/lib.es2017.full.d.ts(13409,11): error TS2300: Duplicate identifier 'URL'.
node_modules/typescript/lib/lib.es2017.full.d.ts(13425,13): error TS2300: Duplicate identifier 'URL'.
node_modules/typescript/lib/lib.es2017.full.d.ts(13432,11): error TS2300: Duplicate identifier 'URLSearchParams'.
node_modules/typescript/lib/lib.es2017.full.d.ts(13459,13): error TS2300: Duplicate identifier 'URLSearchParams'.
node_modules/typescript/lib/lib.es2017.full.d.ts(15745,13): error TS2300: Duplicate identifier 'URL'.
node_modules/typescript/lib/lib.es2017.full.d.ts(15746,13): error TS2300: Duplicate identifier 'URLSearchParams'.
node_modules/typescript/lib/lib.es2017.full.d.ts(16508,11): error TS2300: Duplicate identifier 'URLSearchParams'.
```

```
  "devDependencies": {
    "@types/node": "^10.0.0",
    "typescript": "^2.8.3"
  }
```

```
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true,
        "removeComments": false,
        "target": "es2017",
        "outDir": "../out",
        "moduleResolution": "node",
        "typeRoots": [
            "node_modules/@types"
        ],
        "types": [
            "node"
        ]
    }
}
```

**Comment by styfle** [comment] 2018-04-30 13:38
I think this is a duplicate of #25342

**Closed** 2018-05-18 19:46 UTC
Labels: External
