### ISSUE TITLE
Typescript should get error when not all values passed

### ISSUE THREAD

**Issue by kitsoRik** [microsoft/TypeScript#39849] opened 2020-07-31 14:27 UTC
TypeScript Version:  3.9.2 (3.9.6 too)

**Code**

```ts
interface Parent {
	name: string;
}

interface Child extends Parent {
	firstName: string;
}

interface SubChild extends Child {
	secondName: string;
	lastName?: string;
}

export type GoodChild = Child | SubChild;

const child: GoodChild = {
	name: "name",
	firstName: "firstName", // 19-th string is below
        lastName: "lastName" // need get error, `cause lastName passed without secondName
}

if (child.lastName) { } // error when take lastName

const child2: GoodChild = {
	name: "name",
	firstName: "firstName",
	secondName: "secondName",
	lastName: "lastName"
}

if (child2.lastName) { } // no error, `cause secondName passed
```

Expected behavior: I expect to get error, when not all fields passed to object, see 19 string, I passed `lastName` field from `SubChild`, but not passed `secondName` which is required for `SubChild`.

Actual behavior: Good wotk, my field `lastName` perished.

Playground Link: [TSPlay](https://www.typescriptlang.org/play/?ssl=10&ssc=2&pln=10&pc=12#code/JYOwLgpgTgZghgYwgAgApyhcyDeAoASBDgFsIAuZAZzClAHMBuPAXzz1ElkRQGEALYABsAJsggAPSCBFU0GLGFyEYwKDQBypCtVoNmbDuGjwkyAMoBXAEYDhYydNnI7o5QSoQEAexlaylDR0IEyEQnCa2gD8gXohBuySAA7eUEpgAJ5JKADi3t4irmIAvC6CbgA+FjZFzHg+IDTICOUilHkFRcil+ETalABExGQDADQqapEByAOq6mD+EGNhEQv9M+FTS8gA9DvIIBAQYvQQStBQqaPIAAYIcJaeyJtrZMhJEZ5iAO7AYPzeSxKTwNESLVjsYAwZAACha9gAdC9FgBKXDIFi7fYXVLIb78LDIMBwADWKGR2nYDSa8NEACZ2vlCq1uu5hjohtplgQ5ltBrzXktxh4vL4wesBiCxYtuRTpgM5UsIRxoXDWnSkatUejMXsDt5xFBLlBrncHk8pX5tO9PscgA)

Related Issues: -

**Comment by MartinJohns** [comment] 2020-07-31 14:34
Duplicate of #20863. Excess property checks are not performed for union types.

**Closed** 2020-07-31 14:39 UTC
