### ISSUE TITLE
Proposal: "is keyof" type guard

### ISSUE THREAD

**Issue by fathyb** [Microsoft/TypeScript#13719] opened 2017-01-27 12:47 UTC
Today I found that `Map<T, U>` does not use type guards for it's `has()` and `get()` method. I really like type guards and always use strict null checks and try to avoid using `!` when possible.
However I need to use them when working with `Map`, like here:
```typescript
const ResolutionMap = new Map<Resolution, [number, number]>([
	[Resolution.HD1920x1080, [1920, 1080]],
	[Resolution.HD1280x720, [1280, 720]],
	[Resolution.SD640x480, [640, 480]]
])

export function toSize(resolution: Resolution): [number, number] {
	return ResolutionMap.has(resolution) ?
		ResolutionMap.get(resolution)! :
		ResolutionMap.get(Resolution.SD640x480)!
}
```

This is just a little detail but it would be great to write type guards for those kind of functions, like this for example:

```ts

interface TestMap<T, U> extends Map<T, U> {
	private map: {[key: T]: U}

	has(key: T): key is keyof map // key may not be a string
	get(key: T): map[key]
}
```

```ts
export function toSize(resolution: Resolution): [number, number] {
	 // inferred type = (resolution) keyof (ResolutionMap.private map)
	const hasResolution = ResolutionMap.has(resolution)

	if(hasResolution) { // in this branch we are sure that resolution is a key of map
		// ResolutionMap.get(key) => map[key] so it's [number, number]
		return ResolutionMap.get(resolution)
	}
	else {
		// the type is undefined and ts throws an error because it should be [number, number]
		return ResolutionMap.get(resolution)
	}
}
```

**Comment by mhegazy** [comment] 2017-01-27 17:34
@DanielRosenwasser has a type guard declaration to make this work in https://github.com/Microsoft/TypeScript/issues/13086#issuecomment-269695308.

**Comment by mhegazy** [comment] 2017-01-27 17:34
Duplicate of https://github.com/Microsoft/TypeScript/issues/13086

**Comment by fathyb** [comment] 2017-01-27 17:41
Shame on me to not have found out, thank you, you can close this if needed.

**Closed** 2017-01-27 17:42 UTC
Labels: Duplicate
