### ISSUE TITLE
Property type update not continued inside next block after checking

### ISSUE THREAD

**Issue by silverlight513** [microsoft/TypeScript#48183] opened 2022-03-09 11:16 UTC
# Bug Report

When an object contains an optional property that could either be an array or undefined. Checking that property exists as an array changes its type to only an array instead of optional. Later on, inside a `.some` of another array, the first array goes back to being possibly undefined. If I destructure the item before checking it's value, ts works perfectly but the destructure would be unnecessary in this case.

### 🔎 Search Terms

"Object is possibly 'undefined'."
"type guard not applied"
"possibly undefined inside method"

### 🕗 Version & Regression Information

This is the behavior in every version of the playground and could not find anything in the FAQ's that related.
I did find this issue but I'm unsure if it's related - https://github.com/microsoft/TypeScript/issues/10530

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgKoGdrIN4FgBQyyADtALbDrrAD2I6A-AFzLphSgDmA2gLoDcBAL4ECMAK4gEYWiGQIAFhAQBrAArlK1OugAUBIuMxQWGaABoDyKBACO44DYAmGqBSqzGLNhxA9elvgAlDhWAPRhyAByNCSaHjrIcDbWdg7OVsAwyLoAhDb2jhAu8dr0DAB0ADYQfmAKITZg4lBy7OIQgvjhkWZQyApw6MggsaRuWp7IAEbiYHETCfRJKQXpxZkweQCCUFBwAJ4VlLv7B7pG0BXj7mXoIQA+D8i5l1DXpZ7VtZz1IVZEJotOTwKqYLo9ZDbeY1IbzOgoNZFJwLW6yZBkIzzaYoMhwMCKDaEVLNVqpQrOVxonQVdA0MgQXRIymfOjIAC8AD5QsSiBEoXJqH4aqjJmyEHA5DiMfjCU4AcgsjlmcUqWK5OzNcgAOSQNjakJ4XlEEnA5BvD6LO7HKRVcROCB6FUlK2yIJdE3IETdY1Asmg8FWITu4RAA)

### 💻 Code

```ts
interface User {
  permissions?: string[];
}

function checkPermissions(
  user: User,
  requiredPermissions?: string[],
) {
  if (!requiredPermissions?.length) return true;

  // destructure user.permissions here fixes the errors
  // const { permissions } = user; 

  if(!Array.isArray(user.permissions) || !user.permissions.length) 
    return false;

  return requiredPermissions.some(requiredPermission => {
    if (requiredPermission === 'test') {
      return user.permissions.includes(requiredPermission);
    }

    return false;
  });
}
```

### 🙁 Actual behavior

Error: Object is possibly 'undefined'. 
Above error is shown for user.permissions inside the `some` function. 

### 🙂 Expected behavior

The `user.permissions` object should be an array inside the some. It is an array in the second condition of the if statement above it.

**Comment by MartinJohns** [comment] 2022-03-09 12:43
Another duplicate of #9998.

**Comment by silverlight513** [comment] 2022-03-09 13:51
@MartinJohns Thanks for tagging as a dupe so quick. I tried my best to make sure I wasn't raising a dupe but issues use very domain specific terminology making it hard to do this (obviously makes it easier for maintainers though).

Would it make sense having a note in the FAQ's about narrowing not preserved in closures? It appears as a fundamental part of TS that I'd expect to work. I checked in with my team who were also shocked by this issue.

**Comment by MartinJohns** [comment] 2022-03-09 14:17
The issue comes up quite often. Often enough for me to remember the issue number, and I'm terribly bad at remembering numbers.

> Would it make sense having a note in the FAQ's about narrowing not preserved in closures?

I absolutely agree, and I would expect the TypeScript team to agree as well. It's likely that just no one did it yet. Why don't you go ahead? :-)

![image](https://user-images.githubusercontent.com/5269069/157459406-b0a0b472-caf2-4fdd-aaa9-ead96809405e.png)
https://github.com/Microsoft/TypeScript-wiki

**Comment by jcalz** [comment] 2022-03-09 14:50
Yeah, the [Common "Bugs" That Aren't Bugs](https://github.com/Microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs) page linked from the [bug report template](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md) hasn't been touched since 2019.  

I kind of wish something would keep track of the top ten existing issues duplicated by new issues. and then when you file a report/suggestion you are asked to make sure that your issue isn't already covered by one of them.  If I had to guess I'd say that #9998 is probably the most common one, so even something in the template that just briefly summarizes #9998 might help?  Not that extra stuff in the template necessarily helps; at some point additional info starts to overwhelm/annoy people and then they are less likely to comply.  Maybe even the current level is too much... it's not *very* often that people say "lol that template was too confusing or tedious for me so I ignored it completely yolo" but it does happen.

**Comment by MartinJohns** [comment] 2022-03-09 15:53
> so even something in the template that just briefly summarizes https://github.com/microsoft/TypeScript/issues/9998 might work?

Like [this](https://twitter.com/atcb/status/1449148857800019971)?

![image](https://user-images.githubusercontent.com/5269069/157478404-79fa1a2b-cf46-48a6-9638-3987f8701164.png)

**Comment by MartinJohns** [comment] 2022-03-09 21:13
> We're not really bothered by the duplicate inflow on this

But it'd still be nice to point people to this issue before they spend time on creating another issue and filling out the issue template.

**Comment by fatcerberus** [comment] 2022-03-10 03:39
> before they spend time on creating another issue and filling out the issue template.

Then again... #48148 🚎

**Closed** 2022-03-12 18:00 UTC
Labels: Duplicate

**Comment by MartinJohns** [comment] 2022-03-14 19:57
Related: #48261
