### ISSUE TITLE
TypeError: Cannot read property '243' of undefined

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#22499] opened 2018-03-13 02:00 UTC
Weird error when using global tsc command; the error causes tsc to crash, seems to be internal to tsc.

I get this:

```console
18:57:49 - Starting compilation in watch mode...


/Users/alexamil/.nvm/versions/node/v9.2.0/lib/node_modules/typescript/lib/tsc.js:59957
                throw e;
                ^

TypeError: Cannot read property '244' of undefined
    at getDeclarationSpaces (/Users/alexamil/.nvm/versions/node/v9.2.0/lib/node_modules/typescript/lib/tsc.js:35312:52)
    at /Users/alexamil/.nvm/versions/node/v9.2.0/lib/node_modules/typescript/lib/tsc.js:35304:84
    at Object.forEach (/Users/alexamil/.nvm/versions/node/v9.2.0/lib/node_modules/typescript/lib/tsc.js:260:30)
    at getDeclarationSpaces (/Users/alexamil/.nvm/versions/node/v9.2.0/lib/node_modules/typescript/lib/tsc.js:35304:28)
    at checkExportsOnMergedDeclarations (/Users/alexamil/.nvm/versions/node/v9.2.0/lib/node_modules/typescript/lib/tsc.js:35256:41)
    at checkVariableLikeDeclaration (/Users/alexamil/.nvm/versions/node/v9.2.0/lib/node_modules/typescript/lib/tsc.js:36153:17)
    at checkVariableDeclaration (/Users/alexamil/.nvm/versions/node/v9.2.0/lib/node_modules/typescript/lib/tsc.js:36189:20)
    at checkSourceElement (/Users/alexamil/.nvm/versions/node/v9.2.0/lib/node_modules/typescript/lib/tsc.js:37859:28)
    at Object.forEach (/Users/alexamil/.nvm/versions/node/v9.2.0/lib/node_modules/typescript/lib/tsc.js:260:30)
    at checkVariableStatement (/Users/alexamil/.nvm/versions/node/v9.2.0/lib/node_modules/typescript/lib/tsc.js:36198:16)
```

I got both

> TypeError: Cannot read property '243' of undefined

and 

> TypeError: Cannot read property '244' of undefined

As a hint..I got the latter after reinstalling

`npm install -g typescript`

**Comment by ORESoftware** [comment] 2018-03-13 02:04
Here is my package.json:

```json
{
  "name": "cdt-models",
  "version": "0.0.101",
  "description": "CDT shared models",
  "main": "index.js",
  "scripts": {
    "test": "suman test"
  },
  "repository": {
    "type": "git",
    "url": "ssh://git@gitscm.cisco.com/it-gats-cdtechnologyarchitecture-cdtsdaas/cdt-models.git"
  },
  "keywords": [
    "models",
    "cdt",
    "mongoose",
    "mongodb",
    "mongo"
  ],
  "author": "CDT Team",
  "license": "SEE LICENSE IN LICENSE.md",
  "devDependencies": {
    "@types/core-js": "^0.9.46",
    "@types/node": "^9.4.7"
  },
  "dependencies": {
    "mongoose": "^5.0.10"
  }
}
```

and this is what is in my node_modules folder:

![screenshot 2018-03-12 19 04 07](https://user-images.githubusercontent.com/11139560/37318508-28850a10-2628-11e8-94f6-c696d6b8d47d.png)


**I get the feeling that perhaps the tsc global version is picking up a local dependency. Because tsc works in my other projects.

I get the feeling that perhaps the tsc global version is picking up a local dependency. Because tsc works in my other projects.

I get the feeling that perhaps the tsc global version is picking up a local dependency. Because tsc works in my other projects.**

**Comment by ORESoftware** [comment] 2018-03-13 02:08
I figured out what it was....

I had this:

```js
import models from './vals';
export const models = m;
```

I got the error. I changed that to this:

```js
import m from './vals';
export const models = m;
```

now it works, no error, strange tho!

**Comment by j-oliveras** [comment] 2018-03-13 12:43
Related to #21173.

**Comment by andy-ms** [comment] 2018-03-13 15:25
@ORESoftware Are you using `typescript@next`? The error message should be improved as of #21945. This also looks like a duplicate of #21928.

**Comment by ORESoftware** [comment] 2018-03-13 16:05
I am on `tsc -v 2.7.2`

**Comment by andy-ms** [comment] 2018-03-13 16:27
Try installing `typescript@next`.  The new version should have a better error message.

**Closed** 2018-03-30 20:06 UTC
Labels: Duplicate
