### ISSUE TITLE
spread operator: Tuple types are erroneously taken as 0 length mimimum

### ISSUE THREAD

**Issue by nahuel** [Microsoft/TypeScript#18183] opened 2017-08-31 17:07 UTC
when using the spread operator, Tuple types are always taken as having 0 length minimum:

```ts
const f1 : () => [any,any] = () => [1,2]
const f2 = (x,y) => ''

// compiles OK:
let [a,b]   = f1()

// compiler error, good:
// TS2493: Tuple type '[any, any]' with length '2' cannot be assigned to tuple with length '3'
let [c,d,e] = f1()   

// compiler error, BAD:
// TS2556: Expected 2 arguments, but got a minimum of 0.
f2(...f1())          
```

**TypeScript Version:**  2.5.2

**Comment by mhegazy** [comment] 2017-08-31 18:22
duplicate of https://github.com/Microsoft/TypeScript/issues/4130

**Comment by mhegazy** [comment] 2017-09-18 18:07
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-18 18:07 UTC
Labels: Duplicate
