### ISSUE TITLE
const used in closure before initialization is not marked as an error

### ISSUE THREAD

**Issue by thelastnode** [Microsoft/TypeScript#30607] opened 2019-03-27 05:58 UTC
**TypeScript Version:**  3.4.0-dev.20190326

**Search Terms:** typescript hoisting const arrow function no error

**Code**

```ts
function useX(): number {
    // expect error for use of x before definition
    return x + 2;
}

alert(useX());

const x = 3;
```

**Expected behavior:** error for using `x` before definition

**Actual behavior:** no error, `useX` returns `NaN`

**Playground Link:** https://www.typescriptlang.org/play/#src=function%20useX()%3A%20number%20%7B%0D%0A%20%20%20%20return%20x%20%2B%202%3B%0D%0A%7D%0D%0A%0D%0Aalert(useX())%3B%0D%0A%0D%0Aconst%20x%20%3D%203%3B%0D%0A

**Related Issues:**
Seems similar to: https://github.com/Microsoft/TypeScript/issues/29125

**Comment by DanielRosenwasser** [comment] 2019-03-27 15:07
Duplicate of #13638.

**Closed** 2019-03-29 18:00 UTC
Labels: Duplicate
