### ISSUE TITLE
Assignment "resets" already narrowed type

### ISSUE THREAD

**Issue by hanwenguo** [microsoft/TypeScript#60521] opened 2024-11-16 23:09 UTC
### 🔎 Search Terms

"assignment operator" "type narrowing"

### 🕗 Version & Regression Information

- This is the behavior in every version in the Playground that I tried, and I reviewed the FAQ for entries about assignment operators and narrowing (there isn't any, though)

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.8.0-dev.20241116#code/GYVwdgxgLglg9mABAdzgJwNYGcAUAPALkXAzDmTAEoiso0YwBzRAbwChFEZhEcoBPAA4BTODzyIAvNMQAiWvSazKrDp0QSA1JLkLZAbjWc0wqCDRI8+xAHobiAIIQIwwVGEATIgHI83rliIYACGaGjknohQcIjeCgyM3moAvojCADZYwqrqiCZmFnIGKWzJbGygkLAIiFgAFnAg6R4OmXAA6ugYAEIgUAAicMJYAHJwUPhEJGQU1LV0CTlcPHxCouJSMvILSirsuRI6WnJ1GelwBrb2vv4MeXWBMIFxO4kANLF+XEjpDwGx03IYCSuXy5ks1jsiAAKmtEABRMLoHxfJ6IAD6JiyUHRURi3kBFBBiFSGSyS2MpnBRUMnDKySAA

### 💻 Code

```ts
function works(x: unknown): string {
  if (typeof x === "string") {
    x += "str";
    return x; // Accepted: 'x' is narrowed to 'string'
  } else {
    return "";
  }
}

function shouldAlsoWorkButDoesNot(x: unknown): string {
  if (typeof x === "string") {
    x = x + "hello"; // 'x' in rhs is 'string', 'x' in lhs is 'unknown'
    return x; // Type Error: 'x' is _reset_ to 'unknown'
  } else {
    return "";
  }
}
```

### 🙁 Actual behavior

There is two problems:
- as in `shouldAlsoWorkButDoesNot`, after the type of `x` is already narrowed to `string`, evaluating `x = x + "hello"` somehow "resets" the type of `x` to `unknown`.
- the behavior of `+=` and `x = x + ...` is inconsistent here.

### 🙂 Expected behavior

`x = x + ...` follow the behave of `+=`, which is correct, in the above code example.

### Additional information about the issue

Concerning inconsistency between `+=` and `x = x + ...`, also see #60520.

**Comment by jcalz** [comment] 2024-11-16 23:32
Duplicate of #27706

**Closed** 2024-11-19 21:40 UTC
