### ISSUE TITLE
Possible type inference bug.

### ISSUE THREAD

**Issue by MelvinWM** [microsoft/TypeScript#38746] opened 2020-05-23 18:59 UTC
**TypeScript Version:**  3.9.2

**Search Terms:**

2339 never label:Bug

**Expected behavior:**

The code should compile and run and print out " 'maybeA.myField' is: true ".

**Actual behavior:**

The code does not compile, and gives an error with:

"Property 'myField' does not exist on type 'never'.(2339)"

. It still runs, and when running, it prints out " 'maybeA.myField' is: true ", despite the type checking of the compiler indicating that will never happen.

**Related Issues:**

Might be a duplicate of or related to #37383 , though it might also be unrelated.

**Code**
```ts

class A {
    public myField: boolean = true;
}

let maybeA: undefined | A = undefined;

// Same issue if using Map.forEach.
[new A()].forEach(value => {
    maybeA = value;
});

// Commenting this in makes it correctly compile.
/*(() => {
    maybeA = new A();
})();*/

if (maybeA !== undefined) {
    console.log("'maybeA.myField' is: " + maybeA.myField);
}
else {
    console.log("'maybeA' was undefined.");
}

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
class A {
    constructor() {
        this.myField = true;
    }
}
let maybeA = undefined;
// Same issue if using Map.forEach.
[new A()].forEach(value => {
    maybeA = value;
});
// Commenting this in makes it correctly compile.
/*(() => {
    maybeA = new A();
})();*/
if (maybeA !== undefined) {
    console.log("'maybeA.myField' is: " + maybeA.myField);
}
else {
    console.log("'maybeA' was undefined.");
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/FAYwNghgzlAECCsDexZtgBwK4CMwEsRYBbATwDF8BTMAEwC5YcB7ZsKiAO1gF5YAXAE5YqAbmABfYMHb8SEUjirxGWTrSoAzfJyq1YAHwS9Yajdt21xwAPQ3YAZQjEqsfDBFvNpqDoDmsACyEBgAdJrMggCiECAAFqHAANq6AO4IABQAlAC64ZEx8RkAbhBgnjwAfMio6MQKSoh8peViklnWdrAAwszELpz8-gJx7m7c9QDWVHD4ciCRglQg-GCksAvEGPjsiTYAVBnZvNUo6PKKyiZpmR3t2aL7NtL43hn1l4gAhDx8Zlo6PRZGrnBacKBsKihMDMPwZABEAHIPo1QmRKDRaIi3FBGPDYABqC6o9HUOh3KQ0KCuM7oMEQ3YwuFIlHKbGpaCmdQAyyheEU4BAA)

**Comment by jcalz** [comment] 2020-05-23 21:08
Duplicate of #9998

**Closed** 2020-05-24 06:24 UTC
