### ISSUE TITLE
`const` equivalent for immutable instance variables

### ISSUE THREAD

**Issue by kimamula** [Microsoft/TypeScript#4683] opened 2015-09-07 16:14 UTC
`const` cannot be applied to instance variables, but it would be nice if we can declare immutable instance variables (with `final` keyword, for example).

Will there be support for this functionality?

```typescript
class Foo {
    private final str = 'str';
    private final num: number;
    constructor(private final bool: boolean) {
        this.num = 0;
    }

    doSomething() {
        // The below codes raise compilation errors
        this.str = '';
        this.num = 0;
        this.bool = false;
    }
}
```

**Comment by dsebastien** [comment] 2015-09-07 19:35
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/12

**Comment by kimamula** [comment] 2015-09-08 02:28
Well, this is not exactly a duplicate, as #12 is mainly about declaring properties as immutable externally, while I'm concerned with the immutability of the internal state.

However, I agree that this is at least similar. I will consider to join the discussion in #12.
Thanks.

**Closed** 2015-09-08 02:29 UTC
