### ISSUE TITLE
Flag --emitDeclarationOnly not working with tsc --build

### ISSUE THREAD

**Issue by frags51** [microsoft/TypeScript#47406] opened 2022-01-12 16:29 UTC
# Bug Report
We have a project with references (composite = true). I want to watch over the project and just emit declarations files and no JS. --emitDeclarationOnly is mentioned as compiler options in the TS CLI doc, but it does not seem to be working with --build:

error TS5072: Unknown build option '--emitDeclarationOnly'. Since it is mentioned as compiler options, I am assuming this is unexpected behavior. VS Code is able to provide us with type checks - does it generate JS for all files?

### 🔎 Search Terms

tsc build noemit

### 🕗 Version & Regression Information

TS version 3.9

### Actual behavior
tsc --build --watch --emitDeclarationOnly does not work.

### 🙂 Expected behavior

tsc --build --watch --emitDeclarationOnly just emits declaration files.

**Comment by MartinJohns** [comment] 2022-01-12 16:35
Duplicate of #25613.

**Comment by redhillking** [comment] 2022-01-12 20:19
@

**Closed** 2022-01-15 18:00 UTC
Labels: Duplicate
