### ISSUE TITLE
Need to restart to get auto-acquisition of typing files

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/TypeScript#11742] opened 2016-10-20 04:46 UTC
**OS Version:** macOS
**TypeScript Version:**  typescript@^2.0.6-insiders.20161014 using vscode 1.7 insiders

Note:   ` "typescript.experimentalAutomaticTypeAcquisition": true` must be in your vscode user settings.

**Steps to Reproduce**
- 1. clear `~/Library/Application Support/Microsoft/TypeScript/node_modules/@types`
- 2. start vscode on an workspace with the following two files:
`package.json`
```json
{
    "name": "test",
    "version": "0.0.1",
    "engines" : {
        "node" : "6.7.0",
        "npm" : "3.10.x"
    }
}
```
`test.js`
```js
var fs = require('fs');
fs.
```
- 3. open `package.json` in the editor
- 4. add the following property
```json
    "dependencies": {
        "express" : "4.14.0"
    }
```
- 5. open `test.js` in editor
- 6. place caret behind `fs.` and invoke intellisense using <kdb>Cmd+Space</kbd>

**Expected behavior:**
Intellisense proposals for the node `fs` module are presented

**Actual behavior:** 
No `fs` specific proposals are shown. `~/Library/Application Support/Microsoft/TypeScript/node_modules/@types` remains empty.

- 7. restart vscode
- 8. repeat steps 5. and 6.

-> Intellisense proposals for the node `fs` module are presented

**Comment by mhegazy** [comment] 2016-10-20 05:36
This looks like another duplicate of https://github.com/Microsoft/TypeScript/issues/11256

**Closed** 2016-10-25 22:23 UTC
Labels: Duplicate
