### ISSUE TITLE
Debug Failure. Did not expect JsxSelfClosingElement to have an Identifier in its trivia

### ISSUE THREAD

**Issue by amcasey** [Microsoft/TypeScript#27877] opened 2018-10-12 23:40 UTC
From 3.1.3

```
Error processing request. Debug Failure. Did not expect JsxSelfClosingElement to have an Identifier in its trivia
Error: Debug Failure. Did not expect JsxSelfClosingElement to have an Identifier in its trivia
    at addSyntheticNodes (tsserver.js:113841:30)
    at createChildren (tsserver.js:113830:9)
    at NodeObject.getChildren (tsserver.js:113774:56)
    at getTokenAtPositionWorker (tsserver.js:91057:43)
    at Object.getTokenAtPosition (tsserver.js:91049:16)
    at Object.getRangeOfEnclosingComment (tsserver.js:104660:68)
    at isInComment (tsserver.js:91368:30)
    at isInReferenceCommentWorker (tsserver.js:91485:21)
    at Object.isInReferenceComment (tsserver.js:91477:16)
    at Object.getCompletionsAtPosition (tsserver.js:93544:20)
    at Object.getCompletionsAtPosition (tsserver.js:114818:35)
    at IOSession.Session.getCompletions (tsserver.js:122608:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:121665:61)
    at tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (tsserver.js:123077:28)
    at IOSession.Session.executeCommand (tsserver.js:123086:33)
    at IOSession.Session.onMessage (tsserver.js:123106:35)
    at Interface.<anonymous> (tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by amcasey** [comment] 2018-10-12 23:49
Command was `completionInfo`.

**Comment by amcasey** [comment] 2018-10-13 00:35
Looks like @andy-ms may have fixed this? https://github.com/Microsoft/TypeScript/issues/25487

**Comment by andy-ms** [comment] 2018-11-09 17:20
All I did was add better error reporting so it would show us the file contents on error. Though it shouldn't show up in telemetry.

**Comment by sheetalkamat** [comment] 2018-12-13 21:19
Duplicate of #25487

**Closed by sheetalkamat** 2018-12-13 21:19 UTC
Labels: Bug, Source: Telemetry
