### ISSUE TITLE
Problem finding modules for starter project

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#10346] opened 2016-08-15 18:24 UTC
From @jankalfus [August 10th](https://github.com/Microsoft/vscode/issues/10391#issue-170407318)

Sometimes when I open my project, VS Code is unable to find imported external modules. I've got typings for the modules installed, all files in the project compiles fine using `tsc`, but I get red squiggly lines in the editor. The weird thing is that I get the squiggly lines only for some .tsx files, while it works for others.

The file src/web/App.tsx is fine:
![web](https://cloud.githubusercontent.com/assets/12714276/17553706/9f148050-5f07-11e6-8721-fd1e3a99cac2.png)

While I get squiggly lines for the file src/native/App.tsx:
![native](https://cloud.githubusercontent.com/assets/12714276/17553710/a3c8f266-5f07-11e6-9ab0-69ce23c46a0c.png)

My tsconfig.json content is the following:

```
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": false,
        "jsx": "react",
        "noImplicitAny": true,
        "experimentalDecorators": true,
        "module": "commonjs",
        "target": "es5",
        "rootDir": "src"
    },
    "exclude": [
        "node_modules",
        "src/native",
        "app",
        "app-native",
        "tools",
        "test"
    ]
}
```

Both `react` and `react-native` are installed as global typings.

Unfortunately, I cannot post the source code right now, but basically, the structure of the source files is as following:

```
src
 |-- common
 |-- native
       |-- index.ts
       |-- App.tsx
 |-- web
       |-- App.tsx
 |-- index.ts (this one is for web)
```
- VSCode Version: 1.4.0
- OS Version: Windows 10

Any ideas?

**Comment by waderyan** [comment] 2016-08-15 18:24
From @jankalfus [August 10th](https://github.com/Microsoft/vscode/issues/10391#issue-170407318)

I have noticed that if I use `File -> Close folder` and then `File -> Open Folder...` and open the project folder again, the errors are gone. If I just restart VS Code instead, I keep getting the errors. I presume that some internal cache gets cleared?

**Comment by waderyan** [comment] 2016-08-15 18:24
From @jankalfus [August 10th](https://github.com/Microsoft/vscode/issues/10391#issue-170407318)

More to this issue: I get the errors every time I create a new folder and ts/tsx file inside. Unfortunately, the workaround I've suggested in the previous comment doesn't work.

**Comment by waderyan** [comment] 2016-08-15 18:25
From @jankalfus [August 10th](https://github.com/Microsoft/vscode/issues/10391#issue-170407318)

I've published the source code. To reproduce this issue:
1. Go to [https://github.com/gina-system/react-starter](https://github.com/gina-system/react-starter)
2. Use the steps in the quick start section of the readme
3. Open the src/native/App.tsx file.

**Comment by waderyan** [comment] 2016-08-15 18:25
From @waderyan_ [August 10th](https://github.com/Microsoft/vscode/issues/10391#issue-170407318)

I have reproduced this per @jankalfus's instructions. 

I'm seeing a "Cannot Find Module" when I hover over `react-native`

![image](https://cloud.githubusercontent.com/assets/2449568/17606916/068dccbc-5fd7-11e6-8096-6c8660be24ae.png)

Developer shows a seemingly unrelated error. 

![image](https://cloud.githubusercontent.com/assets/2449568/17606936/2b45a28c-5fd7-11e6-8238-3e6b2e4c6a91.png)

It seems like typings directory is configured correctly. 

![image](https://cloud.githubusercontent.com/assets/2449568/17607005/a209100c-5fd7-11e6-8c8a-5f8822d32573.png)

**Comment by waderyan** [comment] 2016-08-15 18:26
From @waderyan on August 10th

Ok this is strange... I reopened the project to grab another screen shot and this is what I saw. 

![image](https://cloud.githubusercontent.com/assets/2449568/17607226/5336f65e-5fd9-11e6-9229-45b990156143.png)

Everything looks good now. 

I retraced my steps. 
1. re-cloned  https://github.com/gina-system/react-starter in a separate dir. 
2. followed the README steps (`npm install`, `typings install`)

Looks good again.

**Comment by michaeljota** [comment] 2016-09-24 22:05
I have this same issue. Not with React, but with any new module that I make. 

![captura de pantalla](https://cloud.githubusercontent.com/assets/10507776/18811544/5e777410-8281-11e6-9928-d70e4fc59832.png)

**Comment by fabiom** [comment] 2016-09-26 12:42
I had experienced the same issue. Perhaps this can provide additional clues:

- Adding <reference path=""> in a **completely separate** .ts file worked for a while. I have 1 file with all references I needed and that worked until recently.
- Adding a <reference path=""> in the file that is having issues always solves the problem. This has been my workaround.
- There is no pattern I can see when it happens. Files in the same folder may work or not. No apparent "order" seems to trigger it (alphabetical order, folder order, etc). No specific particular module seems to cause it although I had more issues with 'react'.
- tsc does not report issues. Just VS Code.

**Comment by briantobo** [comment] 2016-10-06 18:13
I'm having a similar problem, see the attached screenshot showing two files in the same folder of the same project, one of which shows the problem while the other is working correctly. I had no such problem until today, so it's hard to tell what triggers the bug.

![image](https://cloud.githubusercontent.com/assets/20914668/19164703/16ac0540-8bcf-11e6-8c26-73a4ec6d895b.png)

**Comment by roblom** [comment] 2016-10-26 09:41
I have the same issue for "react" when following the steps in https://www.typescriptlang.org/docs/handbook/react-&-webpack.html 
Adding this to the .tsx files "solves" the issue..: /// `<reference path="../../typings/tsd.d.ts" />`

**Comment by harshil93** [comment] 2016-11-23 04:53
Any plans to fix this ?

**Comment by michaeljota** [comment] 2016-11-23 12:54
f2 -> reload windows = workaround. :P

**Comment by harshil93** [comment] 2016-11-28 05:04
@michaeljota Not working for my typescript react files.

**Comment by 928PJY** [comment] 2017-01-22 07:28
So this is still an unsolved problem?

**Comment by michaeljota** [comment] 2017-01-22 19:54
I don't know if this still as unsolved problem, but the main workaround here it's to restart the resolver serve. There is one extension that can do it automatically, and manually. `typescript-hero`. This will only works with VSCode, and it has to be seen as is, a workaround. So this issue should remain open.

/cc @harshil93 @roblom Hope you find this useful.

**Comment by zhengbli** [comment] 2017-02-02 22:43
I tried all the repro instructions listed, none reproed for me. Do people still have this issue?

**Comment by hysaq** [comment] 2017-02-05 03:38
I was having a similar issue, but could resolve it by adding "types" field to package.json of the imported package to specify corresponding *.d.ts file explicitly. (See http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)
Looks it happens when
- trying to import a library compiled with old version of TypeScript without "types" field in package.json
- noImplicitAny=true

**Comment by mschnee** [comment] 2017-03-14 00:17
This happens to me frequently if I have a pre-existing project that I later want to add typescript to.  My assumption would be that VSCode, or the language services, are caching things somewhere and don't get updated.

In my most recent case, this happened when trying to create a redux reducer. `import { Record } from 'immutable';` was the problem import, even though `tsc  --traceResolution path/to/file.ts` found it eventually:
```
======== Module name 'immutable' was successfully resolved to '$HOME/my-project/node_modules/immutable/dist/immutable-nonambient.d.ts'. ========
```

When this happens, I push my changes to git, delete the directory complete, clone it again into a slightly different path, `vscode new/path/`, and it's no longer a problem.  Granted, this is not an actual solution, but is the most complete information I can provide.

**Comment by farfromrefug** [comment] 2017-03-14 17:57
same thing happening to me right now with module ```electron-updater```

**Comment by zhengbli** [comment] 2017-03-27 18:40
@hysaq @mschnee @farfromrefug do you mind sending a small repro project to help investigate? Thanks

**Comment by dhruvdutt** [comment] 2017-06-02 11:12
Edit your "tsconfig.json" with `"noImplicitAny": false`

**Comment by aozgaa** [comment] 2017-06-06 19:46
@waderyan, @jankalfus, @michaeljota, @roblom,@hysaq @mschnee @farfromrefug, @dhruvdutt, can you link to a minimal repro in a github repo that showcases the issue? Please create the repo with the exact code one would need to see the issue upon opening the directory in vscode (ie: all node_modules are already installed, as it seems there may be a module versioning issue at play).

Without an explicit repro, we can't make progress on getting a fix in.

**Comment by bkbonner** [comment] 2017-07-07 03:34
I'm seeing something similar.   It may not be exactly the same, but it seems like the error codes don't refresh in a predictable manner.    do we always have to close the entire folder and re-open it to trigger a refresh?    I recorded a video to show the behavior:  https://youtu.be/rBnS45DDe3c

i.e. if I add

import * as path from "path";

but I don't have @types/node in my package.json, I get a module not found error.

If I do a npm install --save @types/node.   And I go back to the file where I added the import, it still has the squiggle, unless I close the file and re-open it -- or if I make a change to the file -- or do F1-> reload window as previously suggested.    It seems like something else ought to trigger the validation -- maybe focus change?

**Comment by dhruvdutt** [comment] 2017-07-07 06:03
@bkbonner It would definitely take some initially for TypeScript to understand the definitions file and linking it with the project. Not a bummer!

**Comment by bkbonner** [comment] 2017-07-07 10:49
@dhruvdutt. I don't understand what you mean in your email.

**Comment by dhruvdutt** [comment] 2017-07-07 11:12
@bkbonner Try waiting for some time after installing npm modules. The compiler may be slow.
When you import a module, what happens behind the scenes is the TypeScript compiler goes to node_modules folder, finds the library and checks for "typings" attribute inside package.json.

**Comment by farfromrefug** [comment] 2017-07-25 08:45
@aozgaa I still this with one of my projects which has a 2 package.json structure
[this](https://github.com/iRath96/electron-react-typescript-boilerplate) should show the issue.
If in ```app/package.json``` i include a package which comes with typings then typescript wont find it  (```tsconfig.json``` being in ```./```)
I tried playing around with ```tsconfig.json``` with no success

**Comment by leocaseiro** [comment] 2017-08-17 02:08
I'm having this same issue and I think the problem is with tslint and/or the vscode plugin for tslint.

In my case, I'm coding with VSCode and the plugin [tslint](https://marketplace.visualstudio.com/items?itemName=eg2.tslint).

I'm not sure if all cases posted here have `no-unused-variable` enabled with tslint.

Has anybody noticed that this issue only happens if we enable `no-unused-variable` on the `tslint.json`.

The repo [gina-system/react-starter](https://github.com/gina-system/react-starter) has it enabled.

Anybody else could confirm if removing the `no-unused-variable` the warnings are gone?

Also, the warning happens for any npm library, which is any module without the `.` for local files, for example, react and angular:

<img width="648" alt="screen shot 2017-08-17 at 12 01 18 pm" src="https://user-images.githubusercontent.com/940070/29392880-d945e208-8343-11e7-8e6e-fcf677635387.png">

### My Solution:
If you enable [tslint-language-service](https://github.com/angelozerr/tslint-language-service) with the new plugin [TSLint (vnext)](https://marketplace.visualstudio.com/items?itemName=eg2.ts-tslint) it seems that fixes the issue.

PS: Be aware both the tslint-language-service and the plugin TSLint (vsnext) are in beta, but they seem working fine to me.

**Comment by mhegazy** [comment] 2017-08-31 22:19
> If in app/package.json i include a package which comes with typings then typescript wont find it (tsconfig.json being in ./)

@farfromrefug the module resolution logic in the compiler follows that of node. for a tsconfig.json at the root, it will not be able to see node_modules under `app\node_modules`. consider using path mapping.

**Comment by mhegazy** [comment] 2017-08-31 22:20
This issue has diverged into different directions. does not seem we have any repros for the original issue. closing for now. please file new issue, provide a sample repor or a tsserver log for investigations.

**Closed by mhegazy** 2017-08-31 22:20 UTC
Labels: Bug, Needs More Info, VS Code Tracked

**Comment by farfromrefug** [comment] 2017-09-05 11:33
@mhegazy that makes sense, i will look at path mapping. Thanks

**Comment by ChrisDillinger** [comment] 2017-12-15 11:10
Had this same issue this morning. f1 > reload window got rid of the errors for me. Not sure for how long though. (thanks @michaeljota )

**Comment by kitsonk** [comment] 2017-12-15 14:34
@ChrisDillinger Mohamed said:

> This issue has diverged into different directions. does not seem we have any repros for the original issue. closing for now. please file new issue, provide a sample repor or a tsserver log for investigations.

Adding to this issue is not productive (especially considering you didn't provide the requested information).

**Comment by chookie** [comment] 2018-02-06 19:00
Moving the module to dependencies instead of devDependencies fixed the issue for me. Not really where I want it but works.

**Comment by Giwayume** [comment] 2018-02-16 23:53
I am still experiencing this issue. Every time I create a new file vscode has difficulty recognizing the existence of modules.

**Comment by mhegazy** [comment] 2018-02-16 23:57
@Giwayume please file a new issue and give us some context to be able to reproduce the problem locally.

**Comment by manigandham** [comment] 2018-03-16 21:12
The `tsconfig.json` settings are usually the source of problems: https://www.typescriptlang.org/docs/handbook/compiler-options.html

- `module` sets the output type for your code 
- `moduleResolution` sets the way Typescript tries to look for your modules

These days I use 'esnext' and babel for transpiling for the `module` setting, `moduleResolution` should be set to `'node'` so that it resolves all the node modules properly. It will use that setting depending on what `module` is set to, but you should it explicitly to ensure it's correct.

More info on module resolution here: https://www.typescriptlang.org/docs/handbook/module-resolution.html

**Comment by jankalfus** [comment] 2018-03-17 11:51
I don't even understand why the config is necessary for input files. TypeScript should figure everything out on its own.

**Comment by michaeljota** [comment] 2018-03-17 11:57
If you are starting a new application and you just need a couple of files, sure, the compiler wouldn't need a config. But I really don't see a real scenario where the compiler wouldn't need a config file.

The compiler does not know how your project is designed, is it a simple browser js file with types? Is it a node module? Is it another kind of module?

And there is no way for the compiler to know what you want to do with that.

Do you want to target es5? es3? esNext?

I don't know how the compiler should figure everything out.

**Comment by jankalfus** [comment] 2018-03-17 12:57
I'm not saying it should figure _everything_ out. I'm just saying it could figure out everything regarding module structure the input files are using.

Being not very programmer friendly and buggy is one of the reasons I stopped using TypeScript. Babel could be used by a 5 year old, but the same is not true for TypeScript, unfortunately :/

**Comment by michaeljota** [comment] 2018-03-19 13:35
I wasn't going to respond, but somehow I fell that if I don't you will get the felling that you are right, and you are not. A comparison between Babel and Typescript is not only about what is the easier to used, because at the end, Babel is only a transpiler, and Typescript is a complete language. But is not only about that I think. 

Babel no longer have presets includes, so no batteries, no fun. You need to include the presets you want to use, and then configure them. While is true that this allow you more control about what you want to use, your point is exactly the opposite. 

Babel does not have a type checking system. This is just something that Babel is not. You could, however, use Flow. For sure. But, then you have to configure Flow. And Flow 3rd party libraries. And the Babel-Flow integration. 

And what do you mean with buggy anyway? I do have encounter some really edgy bugs, but they all have been reported, and most of them need some underwork first, like conditional typing, that 2.8 have. 

So, I'm sorry if you fell Typescript can't be used for a 5 years old, but I don't fell like a 5 years old should program with type checkers, maybe with blocks, but not type checkers.

**Comment by jankalfus** [comment] 2018-03-19 13:48
@michaeljota You totally missed my point, again. My point was I don't see a reason why TypeScript couldn't figure out what module structure I'm using automatically.

**Comment by manigandham** [comment] 2018-03-19 14:35
@jankalfus 

Did you read the documentation regarding resolution?

The default now *is* `'node'` and which should automatically resolve modules as expected for anyone using npm, however the older setting (and the reasons when it is enabled) is for backwards compatibility. So if you're starting today with a new project, then everything will work fine - but in case you have a different setting for `module` or have an older project setup, there will be some extra config needed. 

Perhaps Typescript defaulting to `'classic'` resolution mode when set to output `ES6` modules was unfortunate but it's all clearly described in the docs. I don't think reading documentation for the compiler settings to be very onerous considering the complexity of Typescript in general and the features it provides.

**Comment by jankalfus** [comment] 2018-03-19 14:43
@manigandham Thanks for this explanation.

I still don't see a reason TypeScript couldn't look at first few lines of some file in a project and try to guess what is the module structure being used.

**Comment by RyanCavanaugh** [comment] 2018-03-19 15:01
My experience is been that systems that "guess" are far more confusing than those that don't. You shuffle a few trivial lines around, the "guess" becomes wrong and the behavior changes, wat? We're not trying to be Clippy here - *It looks like you're using ES6 modules, should I change the module resolution algorithm for you?*

**Comment by jankalfus** [comment] 2018-03-19 16:31
If TypeScript had an "auto" module resolution option as default, informed about what type it selected, and the user had the ability to override it manually, what would be confusing about that?

**Comment by RyanCavanaugh** [comment] 2018-03-19 17:04
"Auto" is already basically the default - the "classic" resolution algorithm is specifically designed to have the best chance of finding a module in the right place without incorrectly finding modules it shouldn't.
