### ISSUE TITLE
strictNullCheck: flow analysis doesn't mix well inside lambdas

### ISSUE THREAD

**Issue by cyrilgandon** [Microsoft/TypeScript#11090] opened 2016-09-23 14:10 UTC
**TypeScript Version:** 2.0.3 compiled with the flag `strictNullCheck` to true

**Code**

```ts
class Fruit { color: Color | null; }
class Color { name: string; }

function filterNotCompiling(colors: Color[], fruit: Fruit | null) {
    if (fruit && fruit.color) {
        return colors.filter(color => color.name === fruit.color.name);
        //                                                   ^ Object is possibly 'null'
        //                                                   fruit.color detected as 'Color | null'
    }
}

function filterCompiling(colors: Color[], fruit: Fruit | null) {
    if (fruit && fruit.color) {
        const colorPredicate = fruit.color;
        return colors.filter(color => color.name === colorPredicate.name);
    }
}
```

**Expected behavior:**
After the guard `if (fruit && fruit.color)`, the type of `fruit.color` should be `Color`.
Both function should compile fine.

**Actual behavior:** 
After the guard `if (fruit && fruit.color)`, the type of `fruit.color` is `Color | null`.
The function `filterNotCompiling` doesn't compile

Edit: after some more migration of code, the problem appears in all code embedded in a lambda, this happens especially in my project for code inside a `Promise.then()`. I guess this issue is certainly a duplicate but I can't find one issue approaching this problem.

**Comment by ahejlsberg** [comment] 2016-09-28 01:18
This is working as intended. In this function

```ts
function filterNotCompiling(colors: Color[], fruit: Fruit | null) {
    if (fruit && fruit.color) {
        return colors.filter(color => color.name === fruit.color.name);
    }
}
```

we do indeed detect that there are no assignments to `fruit` anywhere and we therefore consider the *first* truthy check (`fruit`) to be in effect in the lambda. For example, this works:

```ts
function filterNotCompiling(colors: Color[], fruit: Fruit | null) {
    if (fruit) {
        return colors.filter(color => fruit.color && color.name === fruit.color.name);
    }
}
```

However, in the original example we can't safely assume that the *second* truthy check (`fruit.color`) is in effect in the lambda since properties can be freely mutated in a number of different ways. The only way to do that is to use a `const` intermediary, as in the `filterCompiling` function in the OP.

@mhegazy Did you have something else in mind when you marked this as a bug?

**Closed** 2016-09-28 01:35 UTC
Labels: Working as Intended

**Comment by cyrilgandon** [comment] 2016-09-28 10:07
Thank you @ahejlsberg , I've make an example to illustrate why the type cannot be infer to not undefined in this example, which uses a lambda into an asynchornous call. 
The design of this feature is much more clear now.

```csharp
class foo {
    bar?: string;

    makeSomeNoiseUnsafe(promise: ng.IPromise<any>) {
        if (this.bar) {
            // can't infer this.bar is defined, it could have be changed
            promise.then(_ => console.log(this.bar.length)); 
        }
    }

    makeSomeNoiseSafe(promise: ng.IPromise<any>) {
        if (this.bar) {
            // save the current state
            const bar = this.bar;
            // work with the saved state
            promise.then(_ => console.log(bar.length));
        }
    }
}
```

What tricks me is that `.filter()` is a synchronous call, but that's ok, I understand that the compiler has no way to distinguish between synchronous/asynchronous call.
