### ISSUE TITLE
Generic not inferred from contextual types

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#25293] opened 2018-06-28 13:20 UTC
**TypeScript Version:**  2.9.2

**Search Terms:** generic infer contextual type

**Code**

```ts
const baz: (n: number) => number = (
    // param `n` is correctly inferred to be `number` :-)
    n => n
);

const identity = <T>(t: T) => t;

const bar: (n: number) => number = identity(
    // param `n` is inferred as `any`, expected `number` :-(
    x => x
);
```

**Expected behavior:** TypeScript should infer the generic `T` in `identity` from the contextual type.

**Actual behavior:** TypeScript infers the generic `T` in `identity` as `any`!

**Playground Link:**  

**Related Issues:**

**Comment by Hotell** [comment] 2018-06-28 15:39
hmm I don't think this is valid.

What you are after is following:

```ts
// inferred bar 👉 (x: number) => number
const bar = identity((x: number) => x)
```

by doing

```ts
const bar: (n: number) => number = identity(
    x => x
);
```

you're telling compiler that `bar` should be type of `(n: number) => number`, but your are assigning to it `identity<any>((x:any): any => x)`

**Comment by OliverJAsh** [comment] 2018-06-28 15:47
I thought TypeScript would use `bar`s type annotation as a "contextual type" and use it to infer the generic to `identity` as `(n: number) => number`. 🤔

**Comment by Hotell** [comment] 2018-06-28 15:59
I might be wrong but I don't think so, that would mean that Generics can flow deeply to function calls

**Comment by ahejlsberg** [comment] 2018-06-28 17:35
This is working as intended. Function and arrow expression parameters without type annotations are assigned contextual types only when the contextual type is known (before instantiation) to be a function type. In your example the contextual type is simply `T`, so we infer from the argument `(x: any) => any` to `T`. Had the contextual type been something like `(x: T) => T`, we would _fix_ the inferences we've made so far for `T` (which would include inferences from the return type) and then assign that type to the `x` parameter.

**Comment by Hotell** [comment] 2018-06-28 17:40
yup what @ahejlsberg  and (myself partially) said :)

**Comment by OliverJAsh** [comment] 2018-06-28 17:55
Thanks for the explanation @ahejlsberg and @Hotell.

To justify why I would like this with a real world use case:

``` ts
const numberPromise = Promise.resolve(1);

numberPromise.then(
  // x is inferred as number, no type annotation required
  x => x + 1
);

// Later, when I need to expand on this function, if I use `pipe` I'm
// forced to add a type annotation to the parameter when it wasn't
// needed before.

numberPromise.then(pipe(
  // x is inferred as any, requiring me to add a type
  // annotation to the param that wasn't needed before
  x => x + 1,
  x => x * 2,
));

numberPromise.then(pipe(
  (x: number) => x + 1,
  x => x * 2,
));
```

**Comment by ahejlsberg** [comment] 2018-06-28 18:23
@OliverJAsh How is `pipe` defined?

**Comment by OliverJAsh** [comment] 2018-06-28 19:17
@ahejlsberg I'm using `flow` from Lodash, which is the same idea as `pipe`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/64104e9760065bd498a3d62d98bb05ea26500dc2/types/lodash/common/util.d.ts#L209

**Comment by Hotell** [comment] 2018-06-28 20:51
Hmm interesting, those definitions might be wrong ? this works 

```ts
declare const pipe: <A, R1, R2>(a: (arg: A) => R1, b: (args: R1) => R2) => (resolved: A) => R2

// $Expect number
const numberPromise = Promise.resolve(1)

numberPromise.then(
  // $Expect (x:number)=>number
  (x) => x + 1
)

// $Expect Promise<number>
numberPromise.then(
  pipe(
    // $Expect (x:number)=>number
    (x) => x + 1,
    // $Expect (x:number)=>number
    (x) => x * 2
  )
)
```

**Comment by ahejlsberg** [comment] 2018-06-29 02:30
The issue appears to be that the `flow` **wall** of overloads starts with a series of declarations that have zero parameters for the first function. In the process of matching against those, we assign type `any` to the `x` parameter of the lambda (because there is no matching contextual parameter). However, once we've made that assignment it sticks and for reasons of consistency we can't undo it. It all works if you eliminate all but the one-parameter-first-function declarations of `flow`. Not sure there is much we can do to change this.

**Comment by OliverJAsh** [comment] 2018-06-29 08:52
Ahh, that's good to know, so we can at least workaround it by patching the `flow` types to remove that overload (which we don't use).

I realised my original example was off the mark. Here is a correct example which does work:

``` ts
const identityFn = <T>(fn: (t: T) => T) => fn;

const bar: (n: number) => number = identityFn(
  // param `n` is correctly inferred to be `number` :-)
  x => x
);
```

**Comment by OliverJAsh** [comment] 2018-07-03 14:01
I guess this can be labelled as "won't fix"?

**Closed** 2018-07-13 10:04 UTC
Labels: Working as Intended
