### ISSUE TITLE
Type guard narrows type disregarding the value update in a lambda

### ISSUE THREAD

**Issue by zhuravlikjb** [microsoft/TypeScript#35960] opened 2020-01-02 15:41 UTC
**TypeScript Version:**  3.7.2, 3.8.x nightly

**Search Terms:** type guard arrow lambda

**Expected behavior:**
Write usages in a nested function should defeat the assignment type guard, and restore the original type of the variable.

**Actual behavior:**
Type of the variable is incorrectly narrowed to 'false'

**Related Issues:**

**Code**
```ts
class Z {
    test2() {
        let b = false;
        [0, 1].forEach(i => {
            if (i === 1) b = true;
        });
        console.log(b); // narrowed to 'false', but the value is actually 'true'
    }
}

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
class Z {
    test2() {
        let b = false;
        [0, 1].forEach(i => {
            if (i === 1)
                b = true;
        });
        console.log(b);
    }
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Comment by jcalz** [comment] 2020-01-02 15:49
Duplicate of #9998

**Closed** 2020-01-06 23:38 UTC
Labels: Duplicate
