### ISSUE TITLE
Constructor assignment makes it possible to erroneously get undefined in properties

### ISSUE THREAD

**Issue by mrakgr** [microsoft/TypeScript#38205] opened 2020-04-27 06:49 UTC
```typescript
class T {
	i : number;
	t : number = this.i;
	constructor(_i : number) {
		this.i = _i;
	}
}

console.log(new T(10).t); // undefined
```

I got bit by this in a more complex example yesterday. It should be a type error.

```typescript
class T {
	t : number = this.i;
	constructor(private i : number) {
	}
}

console.log(new T(10).t); // 10
```

Unexpectedly, if you do it like this it works.

**Comment by jcalz** [comment] 2020-04-27 15:34
Duplicate of #37979?  When you file a new issue there's a template to fill out; where did that go?  Issues that don't follow the template properly can't be triaged as easily.

**Comment by x87** [comment] 2020-04-27 15:46
This is a duplicate of #11006.

> the order is just deterministic: Parameter properties, then field initializers, then constructor code.

If you transpile the code into JavaScript you will see the difference between two examples:

```
"use strict";
class T {
    constructor(_i) {
        this.t = this.i; // initialize the field t
        this.i = _i; // execute the constructor code
    }
}
console.log(new T(10).t); // undefined
```

```
"use strict";
class T {
    constructor(i) {
        this.i = i; // initialize the parameter i
        this.t = this.i; // initialize the field t
    }
}
console.log(new T(10).t); // 10
```

**Closed** 2020-04-30 18:00 UTC
Labels: Duplicate
