### ISSUE TITLE
Inconsistency: type-predicate-guard is not treated as a guard with tagged template

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#3554] opened 2015-06-18 14:58 UTC
Tagged template is a kind of invocation, so it's valid to suppose that it will function the same way as an ordinary invocation at the same place.

But it's not so for type-predicate-guards:

```
var n: any;

declare function q(templateStringsArray: TemplateStringsArray, a: A): a is V;

if (q(n, m)) { // works
    m.m;
}
if (q `${m}`) { // doesn't work
    m.m;
}
```

**Comment by tinganho** [comment] 2015-06-18 15:45
I can try to fix this later.

**Comment by tinganho** [comment] 2015-06-21 05:00
I think this is maybe by design. Main purpose of template strings is to return an another string. Though it can also be used to validate strings. Still it is for validating strings and not types.

Though maybe we can add an error check when used with tagged template?

**Comment by DanielRosenwasser** [comment] 2015-06-21 05:43
Oh yeah, it's absurd, kind of dumb, and I can't see a single use case out of it, but it's a matter of consistency.

> Though maybe we can add an error check when used with tagged template?

I'm okay with this; better to disallow it at first and see if there are any legitimate needs for it than to get headaches over it in the future.

Maybe just "A tagged template's tag cannot return a type predicate."

**Comment by DanielRosenwasser** [comment] 2015-06-21 05:51
See #3584.

**Comment by danquirk** [comment] 2015-06-22 18:19
So do we need both bugs or can we close this one?

**Comment by DanielRosenwasser** [comment] 2015-06-22 18:20
It really depends on the direction we'd like to take; if we want consistency, close the other one. If we want to take the conservative route, close this one.

**Comment by mhegazy** [comment] 2015-06-23 16:43
looking at this again, i would say this is a won't fix. Type guards already support a small subset of code patterns, e.g. "===" but not "==" and the use of parenthesized expressions..

**Closed by mhegazy** 2015-06-23 16:43 UTC
Labels: Accepting PRs, Bug
