### ISSUE TITLE
this.constructor.staticMethod() is ok in JS, but is an error in TS

### ISSUE THREAD

**Issue by vadzim** [microsoft/TypeScript#59052] opened 2024-06-27 08:05 UTC
### 🔎 Search Terms

constructor class type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ 

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYGwhgzhAEDC5WgbwFAEgIBcyYJbGgGVs9gBZAU0wAsB7AEwAoBKZdNYWgOwlpAoB0IWgHNGAIiw580XDABmuLhXHN0AX3SUaDFmzRoA9Ieg050AO60ATgGsYS6AAdwjgFKEANNABGAV0xZGE4eXHoKawp6aEgYrmgI6xtZeIAVQnYzCAEQrGs-YEwbAWJpcio6JjU0TU0UZQs4BAgWAW1KliA

### 💻 Code

```ts
class Class {
	static StaticMethod() {
		console.log("static is fine")
	}
	Method() {
		// this works in plain JS, but is considered as an error in TS
		this.constructor.StaticMethod()
	}
}

new Class().Method()
```

### 🙁 Actual behavior

TS emits an error `Property 'StaticMethod' does not exist on type 'Function'. ts(2339)`

### 🙂 Expected behavior

no error in TS

### Additional information about the issue

this also works well in JS:

```ts
class Class {
	static StaticMethod() {
		console.log("Class static")
	}
	Method() {
		// this works in plain JS, but is considered as an error in TS
        // prints "Derived static"
		this.constructor.StaticMethod()
	}
}

class Derived extends Class {
    static StaticMethod() {
        console.log("Derived static")
    }
}

new Derived().Method()
```

https://www.typescriptlang.org/play/?#code/MYGwhgzhAEDC5WgbwFAEgIBcyYJbGgGVs9gBZAU0wAsB7AEwAoBKZdNYWgOwlpAoB0IWgHNGAIniQYWHPnHN0AX3SUaDFmzRoA9Dug1cMAO60ATgGsYuLtAAO4G9ABShADTQARgFdM0I9CcPLj0FGYU9NCQUbZhZub+tgAqhCjQ6RnpevZmNpgw4gAiYbgAbhHQsqTi7IYQAkFYZt7AmOYCxHLkVHRMimgqKiig0tDFueWRFAAemBRc9DBSiKiZVfhEJPhqvZqrmRmNfILCYkUlk5VbwAppGYMoKFwUxmMXESwCOxrMQA

**Comment by MartinJohns** [comment] 2024-06-27 08:19
Duplicate of #3841 / #32452.

**Closed** 2024-06-27 08:25 UTC
