### ISSUE TITLE
Enum / Type shorter dot syntax

### ISSUE THREAD

**Issue by theo-lubert** [microsoft/TypeScript#40343] opened 2020-09-01 14:43 UTC
## Search Terms

enum type short dot syntax inference swift

## Suggestion

Typescript could use a shorter dot syntax (`Enum.value` -> `.value`)
TS type inference seems perfectly fit to handle this kind of syntax

## Use Cases

Thanks to TS, we can write a lot a code based on types, enums, or even trees of constants without worrying too much about making types mistakes.
But the full type/namespace is written/duplicated everywhere. And most of the time, it feels way too dense without a real reason to be, as the language is capable of inferring the type correctly without it
 
**The short dot syntax is making the code lighter, and greatly easier to read**. And I have to say that it also looks and feel a lot more modern

## Examples

> A good example is the Swift short dot syntax. See here for enumerations: https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html

This code:
```ts
const config: MainConfig = {
    theme: {
        primaryColor: ApiTypes.Theme.Colors.blue,
    },
}

const red: ApiTypes.Theme.Colors = ApiTypes.Theme.Colors.red
const orange = mixColors(red, ApiTypes.Theme.Colors.yellow)

switch (config.theme.primaryColor) {
    case ApiTypes.Theme.Colors.red:
        return 'red'
    case ApiTypes.Theme.Colors.blue:
        return 'blue'
    case ApiTypes.Theme.Colors.orange:
        return 'orange'
    [...]
}
```

could be replaced by:
```ts
const config: MainConfig = {
    theme: {
        primaryColor: .blue, // MainConfig.theme.primaryColor: ApiTypes.Theme.Colors
    },
}

const red: ApiTypes.Theme.Colors = .red
const orange = mixColors(red, .yellow) // based on parameters types

switch (config.theme.primaryColor) {
    case .red:
        return 'red'
    case .blue:
        return 'blue'
    case .orange:
        return 'orange'
    [...]
}
```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-09-01 16:53
Duplicate of #1713.

**Comment by theo-lubert** [comment] 2020-09-01 17:19
Oh sorry, I did not find that one.

It has been 4 years since #1713 was closed though. Is it still the current policy to avoid this kind of features ? as it feels like Typescript is actually a good place to do exactly that (as it would be not impact runtime, or JS).
Also I don't know of any ES standard that could collide with this at this time (so, for years ahead).

I would argue that the positive effect of this feature could outweigh the (I believe unlikely) risk of collision. But that is mainly a subjective point of view.

Is it at least enough to consider letting this issue live for a while. Maybe it could be introduced as an experimental flag ?

**Comment by DanielRosenwasser** [comment] 2020-09-01 19:02
Yeah, we can't do this sort of thing - it's very close in spirit to why we can't implicitly resolve `foo` to `this.foo` in some cases. The stance of not using type-based resolution to determine runtime behavior is actually stronger than it was 4 years ago.

**Comment by theo-lubert** [comment] 2020-09-02 09:49
I might be fighting for a lost cause here 😄, but I don't see how this particular feature would determine runtime behaviour.

The `this.foo / foo` example is clear in the sense that both would represent a different statement/variable in JS. So Typescript would carry a different meaning than JS for the exact same code.
It also means implicitly accessing a property of an object (at runtime), even though it might not be obvious to a first reading.
Many languages allow that, and it actually makes some sense in a strongly OOP language, but probably not in TS.

Yet I can't think of any of those issues with the short dot syntax, as the syntax itself simply does not exists in JS (and I would argue, cannot exist). And it does not seem like it is actually determining any runtime behaviour, as it would only be using the **already known** type of a parameter/variable to **statically** access the right JS constant, effectively filling the gaps in behalf of the developper at compilation level. It could likely do so without ever making any assumptions about the type (and could abort the compilation if there is a case where it would need to).

Based on your comment @DanielRosenwasser, I imagine there are other issues with this that I do not see (and I would actually be curious to learn a bit about that).
But are we sure that the rationale actually applies to this specific feature ?

**Comment by RyanCavanaugh** [comment] 2020-09-02 16:18
> only be using the already known type of a parameter/variable to statically access the right JS constant

The template forbids this:

> This could be implemented without emitting different JS based on the types of the expressions

An alternate way to think of this is:

> Can a developer, seeing a type error they don't like, always add `as any` to silence it without downstream problems?

The answer is "no":
```ts
switch (config.theme.primaryColor as any) {
    case .red: <-- .red of what?
        return 'red'
    case .blue:
        return 'blue'
    case .orange:
        return 'orange'
    [...]
}
```

There are a bunch of reasons not to do type-based emit:
 * Other tools like Babel would be unable to correctly transpile TS files
 * TS tweaks type inference over time, which could lead to your program failing to *run correctly* due to an inference change
 * Type inference can be a very nonlocal process, so type-only changes in one file might lead to *runtime correctness* problems in another file
 * Resolving types before being able to do emit slows performance in `--watch` scenarios
 * Type errors can be silenced by things like `// @ts-ignore`, making the runtime characteristics of programs using that directive unknownable
 * None of this works with generics, since TS uses erasure instead of template instantiation

**Comment by theo-lubert** [comment] 2020-09-03 09:12
Thanks @RyanCavanaugh, these are really good points.

I would still hope to argue that the short dot syntax is optional in TS, and non-existant in JS.
 - In this case, being able to silence the type error with `any` or `ts-ignore` feels less relevant, as you would usually do that in a situation where you are transitioning from JS (so the syntax is not present unless you want it to be, and actually do your part to make it work).
 - If dealing with a TS code, a type error here would mean that the code is actually wrong, or incomplete, so ignoring it should not be permitted in the first place in my opinion. TS can only go so far, we still except the developer to use the full syntax if the type isn't known, and I think that's OK.

It also wouldn't work with generics, or maybe it could work but a very limited set of cases. Yet that would just be a known limitation that makes a lot of sense, one that we could live with.

And there is this:
> TS tweaks type inference over time, which could lead to your program failing to run correctly due to an inference change

That's probably the biggest problem, and even though I'd like to say that only working with fully known types could mitigate this in almost any case, that's just theory, I have no evidence to back this up 😔.

Type-based emits would make the language a lot more strict when using its related features. And I can't argue with the Babel point (a babel plugin maybe ?), or the fact that it would slow down performance. But I still believe it could be worth the cost.

As unlikely as it is, I can only hope that this kind of features can be considered in the future, as type-based emits could introduce very interesting features, that could greatly help developers.

**Comment by RyanCavanaugh** [comment] 2020-09-03 15:01
If you add something to a language, people expect it to *work*. Like, *really work*. The idea of a "known limitation" just doesn't have a lot of traction because how do you "know" the limitation exists? No one reads the docs past the first few pages; they're just out there trying to get stuff done, as they should be.

It's extremely frustrating to write some code using some new language feature, then try to apply very standard programming techniques like refactoring common code into a generic function, only to find that you can't anymore because the feature you relied on is broken inside generics. The experience is always that it's *broken*, not a "known limitation" - we get frequent feedback here on some features that were less thought-through that they should be removed from the language because people ran into the "known limitations" around them and were frustrated that they were allowed to go 90% of the way without the ability go to the last 10% toward their optimal solution.

**Closed by RyanCavanaugh** 2020-09-03 15:01 UTC
Labels: Duplicate
