### ISSUE TITLE
TS Duplicate Identifier bug

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#10128] opened 2016-08-04 09:56 UTC
_From @mboris96 on July 29, 2016 14:56_

If you have typescript files opened up in your editor and make a new file and import something that was imported into any of the opened files into that new file, then save it as <anything>.ts, it will show a duplicate identifier error. You would expect it to not show anything since it's a new file without a duplicate identifier. This bug is only when other files are open.

- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:31:10.994Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Add a typescript file and import anything into it and save.
2. Keep that file open in your editor
3. Create a new file and import that same thing you imported in Step 1 then save it as a typescript file
4. Note the error on the import that vscode shows

_Copied from original issue: Microsoft/vscode#9954_

**Comment by dbaeumer** [comment] 2016-08-04 09:56
@mboris96 can you share the example. Interesting would be the tsconfig.json file if any present since this influences how the TS compiler resolves files.

**Comment by dbaeumer** [comment] 2016-08-04 09:56
_From @mboris96 on August 3, 2016 15:12_

I can recreate this bug without a tsconfig.json file present.

If I just create a random file, say I call it `testorig.ts`

![screen shot 2016-08-03 at 11 04 00 am 3](https://cloud.githubusercontent.com/assets/9067370/17370439/0c746032-596a-11e6-83ce-d339ee8d03ee.png)

and then I add a new file

![screen shot 2016-08-03 at 11 05 43 am 3](https://cloud.githubusercontent.com/assets/9067370/17370505/43faf2e6-596a-11e6-8bb5-7a4af4320444.png)

and import the exact same thing as the first file, `import { it } from '@angular/core';` and save it as a new file, I get this

![screen shot 2016-08-03 at 11 08 32 am 3](https://cloud.githubusercontent.com/assets/9067370/17370594/a43d9d84-596a-11e6-823b-01436d8310a5.png)

And `it` is underlined in red saying, `Duplicate identifier 'it'.`

**Comment by dbaeumer** [comment] 2016-08-04 09:56
@mboris96 moving to the TS team since the problem comes from the tsserver.

**Comment by basarat** [comment] 2016-08-05 07:07
> Duplicate identifier 'it'.

FWIW I heard they made `it` global in recent version of Angular. However it should still not conflict in the presence of an `import` :rose:

**Comment by mboris96** [comment] 2016-08-05 12:34
Yeah, I know. I just figured I'd make a simple example. This happens with anything else too, not just angular imports.

**Comment by mhegazy** [comment] 2016-09-29 23:54
looks like this issue is fixed in the upcoming release. i can not get it to reproduce on the latest drop.

**Closed by mhegazy** 2016-09-29 23:54 UTC
Labels: Fixed
