### ISSUE TITLE
Assigning to `Partial<this>` inside the child class leads to error

### ISSUE THREAD

**Issue by nieltg** [Microsoft/TypeScript#24946] opened 2018-06-14 06:51 UTC
**TypeScript Version:**  3.0.0-dev.20180609

**Search Terms:**  polymorphic `this`, `Partial`

**Code**

```ts
class A {
  prop1: number
  method1(attr1: Partial<this>) {
  }
}

class B extends A {
  constructor() {
    super()
    this.method1({prop1: 5})  // <-- Not assignable
  }
}
```

**Expected behavior:**
No error should occur here. ~~As there is no error in this code below. (append this to the previous snippet)~~

```ts
let a = new A()
a.method1({prop1: 5})   // <-- No error here
let b = new B()
b.method1({prop1: 5})   // <-- Also no error here
```

A better opinion is available at the next comment.

**Actual behavior:**
```
a.ts:10:18 - error TS2345: Argument of type '{ prop1: 5; }' is not assignable to parameter of type 'Partial<this>'.
```

**Playground Link:**  [Playground &middot; TypeScript](https://goo.gl/bgHst2)  

**Related Issues:** 
I'm not sure, but this looks similar to me: #22934

Thank you very much.

**Comment by nieltg** [comment] 2018-06-15 03:39
Well, I think this one is tricky. This is what I have learned from polymorphic `this`. Correct me if I wrong.

### Working case

The first use-case of polymorphic `this` type I encountered on the [TypeScript documentation here](https://www.typescriptlang.org/docs/handbook/advanced-types.html#polymorphic-this-types) is used to build [fluent interfaces](https://en.wikipedia.org/wiki/Fluent_interface). Here is the simplified snippet.

```ts
class A {
  method1(): this {
    return this      // <-- Assignable
  }

  method2(): this {
    return new A();  // <-- Not assignable
  }
}
```

`this` is assignable with `this` but not with `A` instance because there will be a problem when `A` become a parent class of another class.

```ts
class B extends A {
  prop1: number

  // method1(): this {  <-- 'this' type becomes B
  //   return this      <-- 'this' instance is B, B is assignable to B
  // }

  // method2(): this {
  //   return new A();  <-- 'this' instance is B, A isn't assignable to B
  //                        (A doesn't have prop1, but B has)
  // }
}
```

### `Partial<this>` case

Things become a little different with `Partial<this>` since it makes every single property of `this` becomes optional.

```ts
class C {
  prop1: number

  method1(): Partial<this> {
    return { prop1: 5 };       // <-- Should be assignable
  }
}
```

In my opinion, assigning to `Partial<this>` should be allowed because of even subclasses of the base class define properties, all of them will be optional.

```ts
class D extends C {
  prop2: number

  // method1(): Partial<this> {   <-- 'this' type becomes C
  //   return { prop1: 5 };       <-- Specified object should be assignable to Partial<C>
  //                                  (as prop2 is now optional)
  // }
}
```

Thank you very much.

**Comment by mhegazy** [comment] 2018-06-21 20:46
Duplicate of https://github.com/Microsoft/TypeScript/issues/13442. `this` is a generic type that represents the type of the most derived class type only known at instantiation time.

**Closed** 2018-06-26 14:32 UTC
Labels: Duplicate
