### ISSUE TITLE
String template literals as object keys don't get validated correctly

### ISSUE THREAD

**Issue by wbolduc** [microsoft/TypeScript#58673] opened 2024-05-27 21:30 UTC
### 🔎 Search Terms

String template literal object keys return type function

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and there is nothing in the FAQ about it

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.4.5#code/MYewdgzgLgBBCGBbADgGwKYEYYF4YAoAPALjAFdEAjdAJwEpiYAldUGgEwB4ADBFDAPoASAN7kqtAL7cANNBoBLMAHMAfLnX4RAKBh6YAbV5I06YSMLSAuowBEACXSpUIWzO2S627aEiw+pgBMuAQk4tT0jCxsXMb8ZqLhUrLySmoaBDr6MAD0OTBKbDSsUKgAnjAAbvCoCuwwANboZbr6RgBC8PW1ULQ1MKKW3DYwtpRdMOPsbh5ePuDQcCYYAMwhRKQUEQzMrCAcPAGCiVvJclCKKuo4mln6eTBFJeUF7OhgUAoAZgro9VONZqtPS2ZTwGjjZToWx2YoxWyzIA

### 💻 Code

```ts
const sample1 = (x:number): Record<`sample_${number}`,string> => ({
    [`sample_${x}`]: "Hello",
})

const sample2 = (x:number): Record<`sample_${number}`,string> => ({
    // incorrectly valid key
    [`Bad literal ${x}`]: "bad bad",
})

const sample3 = (x:number): Record<`sample_${number}`,string> => ({
    // correctly identified bad key
    "garbage": "record"
})
```

### 🙁 Actual behavior

Typescript does not error on incorrect string template literals

### 🙂 Expected behavior

Typescript should show sample2 as having a bad object key like it does in sample3

### Additional information about the issue

Bonus feature request/question: Is this the only way to get this sort of return type from a function. Putting "as const" in the key or after the object doesn't seem to correctly infer the type. It stays wide {[x:string]: string}

**Comment by jcalz** [comment] 2024-05-27 23:10
Duplicate of #13948.

**Comment by fatcerberus** [comment] 2024-05-28 00:25
Note that `` Record<`sample_${number}`, string>` `` doesn’t restrict the type to *only* those keys, it just guarantees that any keys matching the pattern are typed as `string`.

**Comment by wbolduc** [comment] 2024-05-28 15:49
I mean I guess strictly from the perspective of something receiving the type but TS still checks that you're putting in the correct things when you're initially creating the object

```ts
const aa: Record<number, boolean> = {
	[2]: true,
	salami: "sandwich",
};
```
https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAhnAXDASgU1AJwCYB4wCuAtgEZqYA0MJIIANmnGAHwwC8MA3gFACQA2gCYAusiiYCaCnwhw6cIgEtkAIllhsAd0XAAFiukBfANzcgA

**Comment by fatcerberus** [comment] 2024-05-28 16:14
Only when assigning the object literal to the type directly:
```ts
const bb = {
	[2]: true,
	salami: "sandwich",
};
const aa: Record<number, boolean> = bb;  // ok, no error
```

The excess property check isn't comprehensive, you shouldn't rely on it to constrain the allowed values of a type.  That's why issue #12936 exists.

**Closed** 2024-06-16 01:31 UTC
Labels: Duplicate
