### ISSUE TITLE
"null" satisfies "void" but not "void | Promise<void>" return type

### ISSUE THREAD

**Issue by Lioness100** [microsoft/TypeScript#52608] opened 2023-02-04 05:06 UTC
# Bug Report

### 🔎 Search Terms

`void` return type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed [this](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void) relevant FAQ entry.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBFCm0CMAuGAKAlDAvAPhgDcQBLAE1w23xjAFcAbBgbgChRJYFoAmNLXAWLkYAHxgAFAE4gAtiQjwAPMLIEcVQbUYsgA)

### 💻 Code

```ts
const test1: () => void = () => null; // no error
const test2: () => void | Promise<void> = () => null; // error
```

### 🙁 Actual behavior

`test1`'s function return type satisfies the return type of `null`, expected as per the FAQ entry and explanation. However, `test2` generates the response:

```
Type 'null' is not assignable to type 'void | Promise<void>'.
```

### 🙂 Expected behavior

I would expect that if `null` satisfied `void` in this context, that would remain unchanged regardless of added unions. By definition, if `a` satisfies `b`, then `a` should satisfy `b | SomeArbitraryValue` too, right? Why does adding `| Promise<void>` change the behavior?

**Comment by MartinJohns** [comment] 2023-02-04 06:52
Duplicate of #43921. Used search terms: `void union in:title`

**Comment by Lioness100** [comment] 2023-02-04 13:33
Oh, thanks.

**Closed** 2023-02-05 03:12 UTC
