### ISSUE TITLE
Shorter syntax for default generic parameters in TypeScript, aka T?

### ISSUE THREAD

**Issue by vzakharov** [microsoft/TypeScript#55826] opened 2023-09-22 07:45 UTC
### 🔍 Search Terms

default generic parameters

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Introduce a shorter syntax for defining default generic parameters in TypeScript. Instead of `T extends Something = Something`, we could use `T? extends Something`.

### 📃 Motivating Example

Let's say you're building a data processing pipeline in TypeScript, and you have a `Processor` class that takes two generic parameters: `InputType` and `OutputType`. The `OutputType` extends `InputType` and defaults to `InputType` if not explicitly specified. 

With the current syntax, you would write it like this:

```typescript
class Processor<InputType, OutputType extends InputType = InputType> {
  // ...
}
```

This syntax is a bit verbose as it requires you to repeat `InputType` twice. With the proposed syntax, you could write the same thing more concisely:

```typescript
class Processor<InputType, OutputType? extends InputType> {
  // ...
}
```

This proposed syntax makes the code cleaner and easier to read, especially in complex codebases with many generic classes.

---

A potential criticism of this proposal could be the use of the `?` symbol, which in JavaScript and TypeScript is often used to denote optional properties in an interface or type, which default to `undefined` if not provided. This might lead to confusion as in this proposal, `?` is used to denote a default type for a generic parameter, which does not default to `undefined`.

However, it's crucial to note that in the context of generics, a type parameter cannot default to `undefined` unless it explicitly extends `undefined`. Therefore, the semantics of `?` in this context are inherently different and should not cause confusion.

Moreover, TypeScript already has instances where the same symbol is used in different contexts with different meanings. For example, the `&` symbol is used for both intersection types and bitwise AND operations. The meaning of the symbol is inferred from the context in which it's used. Similarly, the meaning of the `?` symbol in the context of generic parameters could be inferred from its context.

To alleviate potential confusion, we would ensure clear and comprehensive documentation explaining the use and meaning of the `?` symbol in the context of generic parameters. This would help developers understand the difference and use the feature effectively.

### 💻 Use Cases

**1. What do you want to use this for?**

I want to use this for creating classes with generic parameters that have default types.

**2. What shortcomings exist with current approaches?**

The current approach is verbose and repetitive, requiring the type to be written twice.

**3. What workarounds are you using in the meantime?**

Currently, there's no workaround for this. We have to use the existing syntax.

**Comment by MartinJohns** [comment] 2023-09-22 08:31
Duplicate of #30919.

**Closed** 2023-09-22 10:17 UTC
