### ISSUE TITLE
Cannot invoke an expression whose type lacks a call signature (on function union)

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#19480] opened 2017-10-25 21:40 UTC
tsc@2.5.3

```ts
// from lodash
declare function isFunction(func): func is ((...args: any[]) => any) | Function

if (isFunction(x)) {
  x('a') // TS2349
}
```

If I remove the union, it works:
```ts
declare function isFunction(func): func is ((...args: any[]) => any)

if (isFunction(x)) {
  x('a') // TS2349
}
```

**Comment by mhegazy** [comment] 2017-10-25 22:35
Duplicate of https://github.com/Microsoft/TypeScript/issues/7294

**Comment by thorn0** [comment] 2017-10-26 17:21
Even though, it's indeed a duplicate, I've been always wondering why `Function` and `(...args: any[]) => any` are two distinct types. Aren't they supposed to mean the same thing?

**Comment by mhegazy** [comment] 2017-11-09 21:23
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-11-09 21:23 UTC
Labels: Duplicate
