### ISSUE TITLE
Duplicate outline entries for JS top-level functions

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#7725] opened 2016-03-29 14:29 UTC
_From @joaomoreno on March 29, 2016 13:31_

![image](https://cloud.githubusercontent.com/assets/22350/14109628/2eb381c4-f5c3-11e5-940e-a99f173f245e.png)

JS outline always shows duplicate entries for top level functions.

_Copied from original issue: Microsoft/vscode#4741_

**Comment by egamma** [comment] 2016-03-29 14:29
Moving to TypeScript for investigation

**Comment by billti** [comment] 2016-03-29 16:02
Duplicate of #6566

**Closed by billti** 2016-03-29 16:02 UTC
Labels: Duplicate
