### ISSUE TITLE
Import types via docblock

### ISSUE THREAD

**Issue by garygreen** [microsoft/TypeScript#36321] opened 2020-01-21 01:50 UTC
## Suggestion

TypeScript currently allows for basic type checking via docblocks. The current problem is that you cannot "import" types such as those provided by https://github.com/DefinitelyTyped/DefinitelyTyped

Importing via docblock would allow developers to easily try out Typescript by sprinkling docblocks into their code to see type definitions without committing to changing everything to Typescript.

## Examples

```js
//@ts-check
//@ts-import * as WebpackTypes from '@types/webpack/index.d.ts' */

function GenerateManifest() {

        GenerateManifest.prototype.apply = function(compiler) {

        /* @typedef WebpackTypes.Compiler compilation */
        compiler.hooks.emit.tapAsync('generate-manifest-plugin', function(compilation, callback) {
            // compilation will now show suggestions in IDE such as vscode
        });
    }
}
```

This is using the webpack type definitions to provide IDE completions for the `compilation` type.

## Checklist

My suggestion meets these guidelines:

* [*] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [*] This wouldn't change the runtime behavior of existing JavaScript code
* [*] This could be implemented without emitting different JS based on the types of the expressions
* [*] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [*] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by IllusionMH** [comment] 2020-01-21 09:00
TS already supports type imports in JSDoc comments
with `import('module').ExportedType` inline
```ts
function GenerateManifest() {

    GenerateManifest.prototype.apply = function (compiler) {


        compiler.hooks.emit.tapAsync('generate-manifest-plugin',
            /**
             * @param {import('webpack').Compiler} compilation
             * @param {() => string} callback
             */
            function (compilation, callback) {

                // compilation will now show suggestions in IDE such as vscode
            });
    }
}
```
or you can move it to `@typedef` at the top

![image](https://user-images.githubusercontent.com/1312662/72789869-29317480-3c3d-11ea-9703-c7a0d31d1542.png)

**Comment by DanielRosenwasser** [comment] 2020-01-21 09:32
This is potentially a duplicate of #22160.

**Comment by rjgotten** [comment] 2020-01-23 15:24
> TS already supports type imports in JSDoc comments
> with `import('module').ExportedType` inline

That 'support' is quite frankly a half-baked afterthought and breaks down nearly immediately if you have to import more than a single type. E.g. Have fun writing an inline import definition for a generic type that has to inline-import two generic arguments.

You can work around that to some degree by using a local `@typedef`, but you need to do so for each individual type you need. It doesn't work seem to work with e.g. namespaces:

```js
/**
 * @typedef {import("./other").OtherType} OtherType
 */
// WORKS

/**
 * @typedef {import("./other").Namespace.OtherType} OtherType
 */
// WORKS

/**
 * @typedef {import("./other").Namespace} Namespace
 */

/**
 * @param {Namespace.OtherType}
 */
// DOESN'T WORK
```

Something else, which is fully compatible with TypeScript-isms to pull in types is _desperately_ needed for a more workable developer experience.

**Comment by DanielRosenwasser** [comment] 2020-01-23 17:54
Not working with namespaces is probably something we could fix if you did want to file another issue, though my preference is the issue linked to above.

**Closed** 2020-01-26 18:00 UTC
Labels: Duplicate
