### ISSUE TITLE
tsc 2.7.1 noUnusedLocals debug failure

### ISSUE THREAD

**Issue by jmlopez-rod** [Microsoft/TypeScript#21901] opened 2018-02-12 21:08 UTC
I found a bug in the latest release which is no longer present in your nightly builds. The only reason I convinced myself to post the bug is because the nightly build is for 2.8.0 and given that 2.7 was just released 12 days ago I do not think the nightly build will make it out any time soon.

This bug seems more fit for a patch.

**TypeScript Version:**  2.7.1

**Search Terms:** noUnusedLocals, debug failure 

**Code**

```ts
// test.ts

export class SomeClass {
  private notInitialized: boolean;
  private initialized: any[] = [];

  doesNothing(): void {
  };
}

```

**Expected behavior:**

The behavior seen in the nightly build seems ok:

```
jmlopez in ~/typescript-debug$ npm install typescript@next
npm WARN typescript-debug@1.0.0 No description
npm WARN typescript-debug@1.0.0 No repository field.

+ typescript@2.8.0-dev.20180211
updated 1 package in 1.394s
jmlopez in ~/typescript-debug$ tsc test.ts --noUnusedLocals --noEmit
test.ts(4,11): error TS6133: 'notInitialized' is declared but its value is never read.
test.ts(5,11): error TS6133: 'initialized' is declared but its value is never read.
```

**Actual behavior:**

```
jmlopez in ~/typescript-debug$ npm install typescript@latest
npm WARN typescript-debug@1.0.0 No description
npm WARN typescript-debug@1.0.0 No repository field.

+ typescript@2.7.1
updated 1 package in 1.519s
jmlopez in ~/typescript-debug$ tsc test.ts --noUnusedLocals --noEmit
/Users/jmlopez/typescript-debug/node_modules/typescript/lib/tsc.js:59841
                throw e;
                ^

Error: Debug Failure.
    at checkUnusedClassMembers (/Users/jmlopez/typescript-debug/node_modules/typescript/lib/tsc.js:35757:38)
    at checkUnusedIdentifiers (/Users/jmlopez/typescript-debug/node_modules/typescript/lib/tsc.js:35643:29)
    at checkSourceFileWorker (/Users/jmlopez/typescript-debug/node_modules/typescript/lib/tsc.js:37913:21)
    at checkSourceFile (/Users/jmlopez/typescript-debug/node_modules/typescript/lib/tsc.js:37891:13)
    at getDiagnosticsWorker (/Users/jmlopez/typescript-debug/node_modules/typescript/lib/tsc.js:37945:17)
    at Object.getDiagnostics (/Users/jmlopez/typescript-debug/node_modules/typescript/lib/tsc.js:37934:24)
    at /Users/jmlopez/typescript-debug/node_modules/typescript/lib/tsc.js:59858:85
    at runWithCancellationToken (/Users/jmlopez/typescript-debug/node_modules/typescript/lib/tsc.js:59834:24)
    at getSemanticDiagnosticsForFileNoCache (/Users/jmlopez/typescript-debug/node_modules/typescript/lib/tsc.js:59848:20)
    at getAndCacheDiagnostics (/Users/jmlopez/typescript-debug/node_modules/typescript/lib/tsc.js:60059:26)

```

**Related Issues:** ... (not sure)

**Comment by mhegazy** [comment] 2018-02-12 21:13
Duplicate of https://github.com/Microsoft/TypeScript/issues/21491, #21829, #21701, #21697 and #21533.

Fix should be in `typescript@next` today and in the upcoming `typescript@2.7.2` expected in a week or so.

**Closed by mhegazy** 2018-02-12 21:13 UTC

**Comment by jmlopez-rod** [comment] 2018-02-12 21:16
My searching skills are very bad, sorry about that. Good to know that the fix is coming up soon.
