### ISSUE TITLE
Suggestion:  Add compile time check for computed method names, and automatically assigned string constant

### ISSUE THREAD

**Issue by bahrus** [Microsoft/TypeScript#9579] opened 2016-07-08 22:06 UTC
Typescriipt allows you to define computed names for methods, which is very useful:

```ts
const country_change_handler = 'country_change_handler';
export class FlagIcon extends HTMLElement {
     [country_change_handler](newVal: string, oldVal: string){
        //country change handler
    }
}


```

However, using this "dynamic" method is less convenient than using a standard method -- no intellisense / compile time checks when invoking the method on an instance object.
```ts
     const fi = new FlagIcon();
     fi.country_change_handler(); //doesn't compile.  Typing fi. gives no dropdown / autocomplete.
```

Proposal:

1)  Define a special type that echos the name of the constant.

i.e.:

```ts
    const country_change_handler : StringConstant; // say
```

Typescript would emit:

```js
    const country_change_handler = 'country_change_handler'
```

References to this constant, within Typescript, would be treated as a non null string.

Of course, this has the benefit of making the constant match the actual string, even after refactoring.

2)  For such types, Typescript would give intellisense / compile time checks to computed properties:

```ts
const country_change_handler: StringConstant;
export class FlagIcon extends HTMLElement {
     [country_change_handler](newVal: string, oldVal: string){
        //country change handler
    }
}

const fi = new FlagIcon();
fi.country_change_handler(); //compiles
```

**Comment by mhegazy** [comment] 2016-07-08 22:08
duplicate of https://github.com/Microsoft/TypeScript/issues/5579?

**Comment by bahrus** [comment] 2016-07-08 23:18
I can sort of see how they are related, trying to accomplish similar goal.  With 5579, it's not clear to me whether you would be able to get autocomplete support when you type instanceObject followed by a dot , or if you have to use brackets and refer to a symbol that may not match the symbol in the class.  Perhaps I'm not grokking where that's spelled out.

**Comment by mhegazy** [comment] 2016-07-09 00:09
> With 5579, it's not clear to me whether you would be able to get autocomplete support when you type instanceObject followed by a dot , or if you have to use brackets and refer to a symbol that may not match the symbol in the class.

once the type system can tell what this property is, completion, find all refs, quick info, etc.. all should work normally.

**Comment by bahrus** [comment] 2016-07-09 01:58
I guess I would like to see the final suggestion explicitly for how 5579 would work, for me to agree that what I'm proposing is a duplicate.  As it stands 5579 looks like a jumble of different suggestions, with no accepted proposal fully fleshed out, in a way that appears to me to be a duplicate of this suggestion.

**Comment by mhegazy** [comment] 2016-07-10 04:12
I guess you can trust me on this one :) 5579 tracks making the compiler understand the computed properties in types if their expression is a constant expression. Once the type system knew about that, things just fall in place and they behave like normal properties. Unless there is a different request, I would close this in favor of 5579.

**Comment by bahrus** [comment] 2016-07-10 11:45
Okay, if you say so, feel free to close ;-).

**Comment by mhegazy** [comment] 2016-07-11 21:42
thanks.

**Closed by mhegazy** 2016-07-11 21:42 UTC
Labels: Duplicate
