### ISSUE TITLE
property access on unioned objects and string indices

### ISSUE THREAD

**Issue by tycho01** [Microsoft/TypeScript#17361] opened 2017-07-23 06:26 UTC
Although not originally mentioned in the laws of union types (#805), I would generally expect a union of types undergoing a transformation to be equivalent to the result of its constituents undergoing the same transformation (distributive law?).

**TypeScript Version:** `2.5.0-dev.20170626`, presumably any version from the introduction of union types

**Code**

```ts
type x = ({ a: 1 } | { a: 2 })['a'];
// 1 | 2
type y = { [k: string]: 3 }['a'];
// 3
type z = ({ a: 1 } | { a: 2 } | { [k: string]: 3 })['a'];
// ^ Property 'a' does not exist on type ...
```

**Expected behavior:**
`z`: `1 | 2 | 3`

**Actual behavior:**
`Property 'a' does not exist on type ...`

**Comment by tycho01** [comment] 2017-08-03 07:16
I've since found that distributivity is not generally guaranteed with unions. This would fail, for one, for operations such as checking whether a given union contains a certain key.

Nevertheless, I believe the above snippet to intuitively indicate a bug.

**Comment by mhegazy** [comment] 2018-07-02 23:15
Duplicate of https://github.com/Microsoft/TypeScript/issues/21141, should be fixed bu https://github.com/Microsoft/TypeScript/pull/25307

**Closed by mhegazy** 2018-07-02 23:15 UTC
Labels: Bug
