### ISSUE TITLE
inference strangeness - 5: tuples 

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#6343] opened 2016-01-04 15:25 UTC
```typescript
function f0(): [number, number] {
	return [1, 2]; // works
}

interface Some<a> { some: a; }
interface None { none: void; }
type Optional<a> = Some<a> | None;

function f1(): Optional<[number, number]> {
	return { some: [1, 2] }; // works
}

function some<a>(value: a) : Some<a> {
	return { some: value };
}

function f2() : Optional<[number, number]> {
	return some([1, 2]); // doesn't work
}
```

**Comment by ahejlsberg** [comment] 2016-01-04 15:44
Duplicate of #6310.

**Closed** 2016-01-04 15:45 UTC
Labels: Duplicate
