### ISSUE TITLE
Generic with extends and return will fail compilation

### ISSUE THREAD

**Issue by jsgoupil** [Microsoft/TypeScript#17794] opened 2017-08-15 03:07 UTC
**TypeScript Version:**  2.4.2

    class A {

    }

    export class B {
        public method<T extends A>(val: T): Promise<T> {
            return new Promise(resolver => {
                resolver(new A());
            });
        }
    }

It fails with this  
Argument of type 'A' is not assignable to parameter of type 'T | PromiseLike<T>'.
  Type 'A' is not assignable to type 'PromiseLike<T>'.
    Property 'then' is missing in type 'A'.

This code compiled just fine in 2.3

It looks similar to this old bug which compiled fine with 2.3, but fails with 2.4
https://github.com/Microsoft/TypeScript/issues/13993

**Comment by kitsonk** [comment] 2017-08-15 06:42
Not reproducible in the [playground](http://www.typescriptlang.org/play/#src=class%20A%20%7B%0A%0A%7D%0A%0Aexport%20class%20B%20%7B%0A%20%20%20%20public%20method%3CT%20extends%20A%3E(val%3A%20T)%3A%20Promise%3CT%3E%20%7B%0A%20%20%20%20%20%20%20%20return%20new%20Promise(resolver%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20resolver(new%20A())%3B%0A%20%20%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%7D%0A%7D%0A).

**Comment by ahejlsberg** [comment] 2017-08-15 07:10
This is working as intended and is an effect of #15104. Type `A` is not assignable to type `T` because `T` represents some type that *derives* from `A`.

We also now handle #13993 correctly (by reporting an error), but for a different reason. It was fixed by #16368.

**Comment by jsgoupil** [comment] 2017-08-15 15:13
@ahejlsberg then maybe I am looking at this `where T : A` C# thing but in TypeScript?

The documentation does not make any other mention of this? https://www.typescriptlang.org/docs/handbook/generics.html

Is it possible in 2.4?

**Comment by mhegazy** [comment] 2017-08-29 16:42
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-08-29 16:42 UTC
Labels: Working as Intended

**Comment by jsgoupil** [comment] 2017-08-29 16:57
@mhegazy could you kindly let me know if there is such a thing as I asked in the previous comment?
I am staying on 2.3 until I figure this out...

**Comment by mhegazy** [comment] 2017-08-29 22:43
> Is it possible in 2.4?

no. this is flagged as error in 2.4 +
