### ISSUE TITLE
Type '[...GnericParam]["length"]' does not satisfy the constraint 'number'.(2344)

### ISSUE THREAD

**Issue by timongh** [microsoft/TypeScript#53621] opened 2023-04-01 12:29 UTC
# Bug Report

### 🔎 Search Terms

genericity array destructure distributive-conditional-types

### 🕗 Version & Regression Information

- This changed between versions 3.9.7 and 4.0.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.2#code/C4TwDgpgBAggxnCZgDkCuBbAPCqEAewEAdgCYDOUxmARhAE4B8UAvFCgLABQ3A9L1ACi9egHt6fAQBVw0AOQBtAHQqYIgLoKARABsSAc2AALLerlRSoiJWKjgUcgENgAS3IAzEFGPQ4o4uTA9I4uxPZy1Bh09HJKABQATADMACwpAJTc7mjEcK7+UO4AjFhq9HiEJBRQOQDWtgDuxArqjHHcUFSYAFywCEiomFgdnVDKqhoKcnrEhkZy6iOM3Om9AG6iLqRQAN4AvtyS7KJCIuJHUkZuUBiOXnTeRtAQ7u4QeVCi7lAABgAibiCLhoaFca2gAGF-KQXPliI4dFAZJByLEjgBlCAQXpGYDAMDkbr8BokpSgFFweguZA6RyzJTifS8Sxwci8Ix00g0USiWq8BK8PxkWEufwIgC05OsSlxGB0AGIYYEqSCwRBxUKYXCJVLyEcAJLfYzXa4+KBwRzkCAAGkeJDteDO5TAYhojhoOi8fgw1kKYgwDp+4yUWDpUEcIjuNWIouIjHUPyyOTyscKCVKIgqRDIlDqjWarXaXE6kV68EQyHQ2BGnTKWaqlDpXgA-GMVEoypppgZjAsoL1iBBwRJi1BllxVlANltdgceFx+MdTmIR4uAEKgqCwuQ2OyPZwOFwYMB6JRJ3JwwpJIslnp9CuDaujzrBuIKIrqKAAHzGCVtCXUdIuxmOYFiWFZ1k2bZ9m4IA)

### 💻 Code

```ts
type AcceptNum<N extends number> = N

// Error
// Type '[...Arr]["length"]' does not satisfy the constraint 'number'.(2344)
function f1<Arr extends unknown[]>(
  num: AcceptNum<
    [...Arr]['length']
  >
): void {}

// No Error
// This may be the effect of `Distributive Conditional Types'.
// If this is the case, then the error probably comes from the `[...<an array union>]`
function f2<Arr extends unknown[]>(
  num: AcceptNum<
    Arr extends any ? [...Arr]['length'] : never
  >
): void {}

// No Error
// But it's not that simple.
function f3(
  num: AcceptNum<
    [...([1] | [2, 2])]['length']
  >
): void {}
```

### 🙁 Actual behavior

See code comments

### 🙂 Expected behavior

No error

**Comment by fatcerberus** [comment] 2023-04-01 13:18
Duplicate of #53563?

**Comment by timongh** [comment] 2023-04-01 13:38
It looks like this.

**Comment by ahejlsberg** [comment] 2023-04-03 13:45
This is indeed a duplicate of #53563.

**Closed** 2023-04-05 18:00 UTC
Labels: Duplicate
