### ISSUE TITLE
TypeScript errors in tsconfig.json with `noLib` option

### ISSUE THREAD

**Issue by osyrisrblx** [Microsoft/TypeScript#28224] opened 2018-10-30 03:18 UTC
**TypeScript Version:**  3.1.3

**Search Terms:**
tsconfig.json nolib "\[ts\] Cannot find global type 'Array'."

**Expected behavior:**
No error should occur

**Actual behavior:**
`tsconfig.json` contains the error `[ts] Cannot find global type 'Array'.`

![image](https://user-images.githubusercontent.com/9200592/47693579-95573100-dbd0-11e8-8fd8-1422c6479bea.png)

Repro steps:
- Create a new folder
- Create a `tsconfig.json` file that uses `"noLib": true,` (as shown above)
- Create a `src/main.ts` file to start the TS type checker and save it

VSCode will now give you the following error:
`[ts] Cannot find global type 'Array'.`

**Comment by kitsonk** [comment] 2018-10-30 04:04
Why did you ignore the issue template?

That is the intended behaviour.  When you specify `noLib` you need to ensure that any library files you do wish to use are included within the scope of your project, either by `lib` in `compilerOptions` or `files` or `includes`.

**Comment by osyrisrblx** [comment] 2018-10-30 04:37
Updated the original issue to fit the template, sorry. I wasn't sure how to work in some of the fields.

And I don't think this is actually intended behavior. I'm not using `Array` or any sort of array anywhere in `main.ts`. The file `main.ts` is completely empty.

But this was just a minimal repro to trigger the bug. Even if I create an interface for `Array` and populate it with some members the bug still occurs.

Finally, the error is created inside of `tsconfig.json` which doesn't make sense?

**Comment by sheetalkamat** [comment] 2018-10-30 14:52
This is duplicate of #3930

**Closed by sheetalkamat** 2018-10-30 14:52 UTC
Labels: Duplicate
