### ISSUE TITLE
make a new type *.tson

### ISSUE THREAD

**Issue by takegine** [microsoft/TypeScript#54233] opened 2023-05-13 01:28 UTC
# Suggestion
When using a JSON file, we want to limit the parameter content we fill in using the `$schema` field, and write a complex JSON to restrict it. I want to develop a completely new file that uses an interface instead of the schema's restrictive features. Its extension can be `tson`. This also makes it easier to convert from interface to and from JSON.In my opinion everyone will think that declare an interface is much simpler than the schema

// Same as above, in my native language
在使用json文件时，我们要限制填写的参数内容使用了“$schema”字段，并写了一个复杂的json去限制。我希望能开发一种全新的文件，使用一个 interface 来代替 schema的限制功能。它的拓展名可以是 tson 。这样也更容易从 interface 和json之间相互转化。我想，大家应该都会觉得 interface 的申明比schema要简单很多

**Comment by xiBread** [comment] 2023-05-13 04:01
Seems like a duplicate of #2064

**Closed** 2023-06-21 01:31 UTC
Labels: Suggestion, Out of Scope
