### ISSUE TITLE
Type conditional does not narrow down a union type in index signature

### ISSUE THREAD

**Issue by hlysine** [microsoft/TypeScript#48893] opened 2022-04-30 07:44 UTC
# Bug Report

### 🔎 Search Terms

conditional in type with index signature

### 🕗 Version & Regression Information

Tested versions:
- 4.6.2
- 4.3.5
- Nightly (4.7.0-dev.20220429)

This is the behavior in every version I tried, and I reviewed the FAQ for entries about index signatures and conditional types

### ⏯ Playground Link

[Playground link with relevant code](https://www.staging-typescript.org/play?ts=4.6.2#code/C4TwDgpgBAkgdgEwgDwgg8gIwFZQLxQDeAUFFANoDWEIAXFAM7ABOAlnAOYC69cArgFtMEZlAA+jFuw4BuYgF9ixUJCgBlABYB7PgBsEAIQhqpnADwAVKCmAREDSW04A+fFAtzl4aAGENEAGNqZktrZFt7WEQUNCxsVwISMnIAaSh2KGoQLQAzdx53VK4wiIQHfiERKAB+QpTi+k0dfSMTJw5LIuc5eSA)

### 💻 Code

```ts
type IndexedObj = {
  [key: string]: number | string;
}

type ShouldBeString<T extends string> = T;

type Checker<T extends IndexedObj> = {
  [K in keyof T]: T[K] extends number ? T[K] : ShouldBeString<T[K]>;
}
```

### 🙁 Actual behavior

Error: `Type 'T[K]' does not satisfy the constraint 'string'.`

### 🙂 Expected behavior

I don't expect there to be any errors. Since `IndexedObj` defines an index signature with values of type `number | string`, and `T[K] extends number` eliminates the `number` option, `T[K]` should be of type `string`, passing the `ShouldBeString` check.

**Comment by harry0000** [comment] 2022-04-30 08:51
This is a duplicate of  #26240.

**Comment by jcalz** [comment] 2022-04-30 19:53
Also note that, in general, if `T` is assignable to `A | B` but not to `A`, it does *not* imply that it's assignable to `B`.  For example, consider `Checker<{a: 0 | ""}>`.  `0 | ""` is assignable to `number | string` but it is assignable neither to `number` nor to `string`.  Oops.  So the behavior shown here is definitely working as intended.  

There are undoubtedly situations where it *is* safe to conclude `T extends B`, but you need extra information about `T`, `A`, and `B` and whether or not the check is [distributive](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types).

**Closed** 2022-05-05 18:00 UTC
Labels: Duplicate
