### ISSUE TITLE
Union type does not work as expected when recursive types and array is used

### ISSUE THREAD

**Issue by pleerock** [Microsoft/TypeScript#24403] opened 2018-05-25 06:47 UTC
Having following definition:

```ts
interface Post {
    id: number;
    title: string;
    tags: {
        id: number;
        name: string;
    };
}

type WhereOptions<E> = {
    [P in keyof E]?: E[P] extends object ? WhereOptions<E[P]> : E[P]
};

type Options<E> = {
    where?: WhereOptions<E> | WhereOptions<E>[];
};

const options: Options<Post> = {
  where: {
      id: 1,
      tags: {
          id: 1,
          blabla: 1, // compiles fine, but I expect it say missing property blabla
      }
  }
};
```

I don't have compiler errors as I expect.

If I change Options interface to:

```ts
type Options<E> = {
    where?: WhereOptions<E>; // | WhereOptions<E>[];
};
```

Then I see the error I expect. Is it a bug?

(sorry as usual don't know how to title issue).

**Comment by mhegazy** [comment] 2018-05-25 15:50
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/20863

**Closed** 2018-06-08 15:57 UTC
Labels: Duplicate
