### ISSUE TITLE
Type Guarding breaks with functions that return never

### ISSUE THREAD

**Issue by kwasimensah** [microsoft/TypeScript#39578] opened 2020-07-13 06:05 UTC
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

never type guard

**Code**

```ts
function fooWorking(x: number | undefined) : number {
  if (x === undefined) {
    throw new Error("Is undefined");
  }
  return x;
}


function fooBroken(x: number | undefined): number {
  const isAnError = () => {
    throw new Error("Is undefined");
  }
  if (x === undefined) {
    isAnError();
  }
  return x; // errors because it can't tell that x can only be a number
}
```

**Expected behavior:**

fooBroken compiles without issue. Typescript can tell that x must be a number because the if branch calls a function that never returns.

**Actual behavior:**

Typescript complains on the return statement in fooBroken because it doesn't realize x can only be a number.

**Playground Link:** 

https://www.typescriptlang.org/play/?ssl=17&ssc=2&pln=1&pc=1#code/GYVwdgxgLglg9mABMOcDqcBOBrGYDmAFAB4BciYIAtgEYCmmiAPouACZ3B51sCUi5SrQaIA3gChEiGMEQlEAXiWswHLmB78JUqVAAWmOAHcKdEwFFMhzIQBEASQDOKtdza3eAbkmIAvj8w6KBBMJGJvf3FxUEhYBGRUACFDbDowEkFqekYWdk43XkzhRm1ECARHKGlHAEEwS2tFOX4FAD4xH10DY1MLKyw7Jxd8jXcvH38pGTliRWU89U0OnWq6hoHxqUnEQODQxHDEAHojxAZrZ3oIAEMQRzppKpuwAHIqqDoAG0-EfWuq2bPRAIT4AT0Q9EQ1woWQY4l8QA

**Related Issues:**

**Comment by MartinJohns** [comment] 2020-07-13 10:50
Duplicate of #12825.

**Closed** 2020-07-15 18:00 UTC
Labels: Duplicate
