### ISSUE TITLE
Go To Definition not working if import path has cache busting (javascript)

### ISSUE THREAD

**Issue by webappslove** [Microsoft/TypeScript#29232] opened 2019-01-02 01:49 UTC
VSCode Version: 1.28 - 1.31
OS Version: Windows 10
Steps to Reproduce:
import a class with a suffix after `.js`:
`import Rooms from './components/Rooms.js?2019.01.01'`
Go to definition then just brings you to the import.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ajafff** [comment] 2019-01-02 19:53
Duplicate of #22689

**Comment by webappslove** [comment] 2019-01-04 23:16
OK, I just want to leave a kind of workaround here in case someones find this specific issue : use a search and replace in files...

Easy to do when you only need to update the app version – and this is what I was doing before – but now we need to remove it for development, and re-add a version before deploy, and only for the wanted file extensions, excluding specific words *(limit the scope of files searched with the dedicated include / exclude fields)*. The only limitation I found is that this will only match one file path per line, and only if the line doesn't include a forbidden word, so just use paths on their own lines.

**Toggle the regex button and enter in the search field:** (change your forbidden words and/or file extensions)
`^(?!.*(?:firebase|http))(.*?\.(?:js|css))(?:(?![\w.-])(\?[\d\.]+\w)?)`

**Then in the replace field, enter either:**
- `$1?YOUR_VERSION` before deploying, or
- `$1` to remove the version for development with intellisense working!

Test modifications here: https://regexr.com/45s36

Now I would **love** to have search snippets! (for this one and also for search excluding comments) No idea how or what it would look like though...  :)

**Closed** 2019-01-07 18:00 UTC
Labels: Duplicate
