### ISSUE TITLE
Omit<IntersectionType, 'common_prop'> removes unrelated properties

### ISSUE THREAD

**Issue by VanTanev** [microsoft/TypeScript#46888] opened 2021-11-21 15:27 UTC
# Bug Report

### 🔎 Search Terms

omit, intersection, extra, more

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Omit on intersections

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-beta#code/JYWwDg9gTgLgBAbzgeRMeBfOAzKERwDkArjMADboCeAtDFWAKYDOhA3AFAf1NwCiANzgBeRBzhwejAFxEAgoQA04uMWaMosgHbEQAIw0csAH0RwVU2YQBChFWo3bdBqMonMYmuB6jAtAcyM4UyQLBhkiAGElcwkHLx19DUVYuESnJKgjLik4SOgoRgBjGAB9AAsAQ2ZSn1LEkX4AD09KkoAeQRSkSyJbYKjCOAwAPg4AenGJAD0Afm5wuAB1PADS4Bq0ZmY-f1rPet1G1HR2-KhCkorq-ahDkBSSdShCMcmZ2aA)

### 💻 Code

```ts
import { Omit } from 'utility-types';

type Ev = {
  type: 'A',
  user: number
} | { 
  type: 'B'
  user: number,
  str: string
} | { 
  type: 'C', 
  user: number, 
  num: number
}

// missing extra properties
type Wrong_is_missing_str_num2 = Omit<Ev, 'user'>
//  ^? { type: 'A' | 'B' | 'C' } 

type Extracted= Extract<Ev, { type: 'B' | 'C' }>
//  ^? { type: 'B', user: number, str: string } | { type: 'C', user: number,  }

type Wrong_is_missing_str_num2 = Omit<Extracted, 'user'>
//  ^? { type: 'B' } | { type: 'C' } 
```

### 🙂 Expected behavior

```ts
type Expected_correct1 = Omit<Extracted, 'user'>
//  ^? {type: 'A' } | { type: 'B', str: string } | { type: 'C', num: number } 

type Expected_correct2 = Omit<Extracted, 'user'>
//  ^? { type: 'B', str: string } | { type: 'C', num: number } 
```

**Comment by MartinJohns** [comment] 2021-11-21 15:37
Duplicate of #46361. You expect the omit type to operate distributive, but it doesn't.

**Comment by VanTanev** [comment] 2021-11-21 15:40
Sorry that I didn't manage to catch the duplicate.
Do you think it might be worth adding this limitation of Omit to the docs, and including (or at least linking to) the distributive version?

**Closed** 2021-11-21 16:23 UTC
