### ISSUE TITLE
Be able to configure what quick info IntelliSense shows on hover (e.g. whether to expand)

### ISSUE THREAD

**Issue by brillout** [microsoft/TypeScript#56010] opened 2023-10-06 09:28 UTC
### 🔍 Search Terms

quick info, hover, IntelliSense, type hint, tsserver, VSCode

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

As a library author, I want to control what the user sees when he hovers over a type.

Most notably, I want to control whether the type should be expanded.

Tell TypeScript to show `{ n: number }` when the user hovers over `B`:
```ts
type A = { n: number }
// @ts-quickinfo-expand true
type B = A
```

Tell TypeScript to show `A` when the user hovers over `B`:
```ts
type A = { n: number }
// @ts-quickinfo-expand false
type B = A
```

### 📃 Motivating Example

Library authors increasingly use TypeScript to document their library. It's a powerful way to add documentation right inside the user's source code. Being able to control TypeScript's quickinfo IntelliSense is a boon for library authors.

This is helpful not only for library authors, but also for large scale projects.

### 💻 Use Cases

**1. What do you want to use this for?**

For [Vike](https://vike.dev/) (a next-generation frontend framework).

**2. What shortcomings exist with current approaches?**

See above.

**3. What workarounds are you using in the meantime?**

None that I'm aware of.

**Comment by MartinJohns** [comment] 2023-10-06 10:04
Essentially a duplicate of #34556.

**Comment by RyanCavanaugh** [comment] 2023-10-06 22:22
I think of it more like #38040 - we clearly need a way for QuickInfo to show a structural view rather than nominal view

**Comment by brillout** [comment] 2023-10-07 09:26
While these tickets are related, none of them suggest adding the capability of configuring TypeScript's QuickInfo. That's why I was under the impression that creating this ticket wouldn't be a duplicate.

> we clearly need a way for QuickInfo to show a structural view rather than nominal view

It's nice to hear that improving QuickInfo is being considered 👌

**Comment by MartinJohns** [comment] 2023-10-07 10:53
> While these tickets are related, none of them suggest adding the capability of configuring TypeScript's QuickInfo.

That's an implementation detail. A different suggestion on how to solve a problem usually does not warrant a new issue, when the problem it tries to solve is still the same. You can add that as a comment to the existing issues.

**Closed** 2023-10-10 01:25 UTC
Labels: Duplicate
