### ISSUE TITLE
no error when getting a property with no getter

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#49288] opened 2022-05-28 06:03 UTC
# Bug Report

### 🔎 Search Terms
setter without getter

### 🕗 Version & Regression Information
4.8.0-dev.20220527
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220527#code/MYGwhgzhAEBiD29oG8CwAoaXoQKYBdoAzRACgDcwQBXXALh3wCcBLAOwHMBKFAXw37oMweGwiESSALzQ2uAO5wyXDMNER4IXADoQ8DqUnaj+eAFUADhdxMAwpFykuPAPQvoTam3wsAtrmgbJngmIA)

### 💻 Code

```ts
class Foo {
    set foo(value: string) {}
}

const foo = new Foo()

console.log(foo.foo.toUpperCase()) // runtime error
```

### 🙁 Actual behavior
no error

### 🙂 Expected behavior
either an error when defining the setter if it shouldn't be allowed, or an error when accessing the `foo` property (as its type is `undefined`)

**Comment by MartinJohns** [comment] 2022-05-28 06:13
Duplicate of #30852. Check out the ESLint rule [accessor-pairs](https://eslint.org/docs/rules/accessor-pairs).

**Comment by DetachHead** [comment] 2022-05-28 06:46
thanks. btw the open issue is #21759

**Closed** 2022-05-28 06:46 UTC
