### ISSUE TITLE
Improve type inference for nullish coalescing (??) after null checks on multiple variables

### ISSUE THREAD

**Issue by hkfi** [microsoft/TypeScript#59973] opened 2024-09-15 19:08 UTC
### 🔍 Search Terms

"narrowing multiple conditions", "control flow analysis", "nullish coalescing", "type narrowing after null check"

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Currently, TypeScript doesn’t correctly infer types when using the nullish coalescing operator (??) after null checks involving multiple nullable variables. This requires additional code to handle permutations of nullable values, making the code less concise.

Consider the following example:
```typescript
function test(a: string | null, b: string | null): string {
  if (!a && !b) {
    throw Error("Need either a or b");
  }

  return a ?? b;  // TypeScript error: Type 'string | null' is not assignable to type 'string'
}
```

After the if (!a && !b) check, it’s guaranteed that at least one of a or b is a string, yet TypeScript still raises an error for the a ?? b expression, assuming that both values could still be null.

Expected Behavior:
I expect TypeScript to infer that at least one of a or b is a non-null string after the if (!a && !b) check. Therefore, a ?? b should not throw a type error since it’s guaranteed to return a non-null string.

Actual Behavior:
TypeScript throws the following error:
```
Type 'string | null' is not assignable to type 'string'.
```
Despite the null check ensuring that at least one of a or b is non-null, TypeScript doesn’t infer that a ?? b will always return a string.

### 📃 Motivating Example

In TypeScript, handling nullable values often requires extra checks or verbose code. With this improvement, TypeScript’s type inference is now smarter when using the nullish coalescing operator (??) after null checks.

For example, in this code:
```typescript
function test(a: string | null, b: string | null): string {
  if (!a && !b) {
    throw Error("Need either a or b");
  }

  return a ?? b;  // Now correctly inferred as 'string'
}
```

TypeScript now understands that after checking both a and b are not null, a ?? b will always return a non-null string. This makes the code more concise and eliminates the need for redundant if blocks or temporary variables.
As the number of nullable variables increases, this becomes more useful. Without it, handling multiple nullable variables would require increasingly verbose checks.

### 💻 Use Cases

1. What do you want to use this for?
General TypeScript usage.

2. What shortcomings exist with current approaches?
Non-null assertion is needed, when it shouldn't be.

3. What workarounds are you using in the meantime?
Using non-null assertion. Eg.

```typescript
function test(a: string | null, b: string | null): string {
  if (!a && !b) {
    throw Error("Need either a or b")
  } 

  return (a ?? b )!
}
```

**Comment by MartinJohns** [comment] 2024-09-15 19:25
Duplicate of #49452.

**Closed** 2024-09-19 01:32 UTC
Labels: Duplicate
