### ISSUE TITLE
Convert to named function refactoring should preserve `async` modifier

### ISSUE THREAD

**Issue by WickyNilliams** [microsoft/TypeScript#41680] opened 2020-11-24 13:34 UTC
The "convert to named function" refactoring should preserve the `async` modifier.

Starting with this code:

```ts
const foo = async () => {
  await Promise.resolve()
}
````

The current behaviour, after converting to a named function, produces:

```ts
function foo() {
  await Promise.resolve()
}
```

The `async` modifier has been lost during the refactoring, resulting in invalid code. There is another refactoring to "add async modifier", but it's an unnecessary second step.

Ideally it should instead produce this result in one pass:

```ts
async function foo() {
  await Promise.resolve()
}
```

**Comment by a-tarasyuk** [comment] 2020-11-25 07:49
Duplicate of https://github.com/microsoft/TypeScript/issues/40366

**Comment by jessetrinity** [comment] 2020-11-25 20:04
Closing as duplicate - fix available.

**Closed by jessetrinity** 2020-11-25 20:04 UTC
Labels: Bug, Domain: Refactorings, good first issue, help wanted

**Comment by WickyNilliams** [comment] 2020-11-25 21:34
Sorry! I did try to find if it had already been reported by search but came up short. Thanks anyway

**Comment by Nicolerobinn** [comment] 2020-12-08 07:53
I'm a little confused about this, but what's the point of converting like this? Is the arrow function bad

**Comment by WickyNilliams** [comment] 2020-12-08 09:07
There is nothing bad about arrow functions, but there are slight differences in behaviour between an arrow function and a named function - arrow functions have lexical scope, no access to `arguments`. 

Sometimes you want/need this, sometimes you don't, so it is useful to be able to quickly convert between the two.

**Comment by Nicolerobinn** [comment] 2020-12-08 09:17
I know slight differences in behaviour between an arrow function and a named function ,I thought the hint there was to force me to change the arrow function to a named function

**Comment by WickyNilliams** [comment] 2020-12-08 09:50
no, the refactoring works both ways :)

**Comment by Nicolerobinn** [comment] 2020-12-08 10:04
Ok, thank you
