### ISSUE TITLE
Generate declarations for toplevel external modules

### ISSUE THREAD

**Issue by spion** [Microsoft/TypeScript#1694] opened 2015-01-16 11:18 UTC
It would be great if TypeScript had support for wrapping generated AMD/commonjs module declarations inside a toplevel "external" module, e.g.

```
tsc -d -m commonjs -mname test src/test.ts --outDir out
```

would result with `out/test.d.ts` containing

```typescript
declare module "test" {
  // entire .d.ts file goes here
  export ...
}
```
Currently I do this manually with a [quick and hacky tool I wrote](https://github.com/spion/tsc-wrap-definition) which seems to work correctly so far for my [limited needs](https://github.com/doxout/promise-observer)

**Comment by csnover** [comment] 2015-01-20 18:07
Duplicate of #17

**Comment by danquirk** [comment] 2015-01-20 18:43
Yeah without a real way to write multi-file external modules this will be pretty hacky.

**Closed by danquirk** 2015-01-20 18:43 UTC

**Comment by fdecampredon** [comment] 2015-01-21 21:22
For the purpose of generating a configuration file I created a (little script)[https://github.com/fdecampredon/typescript-project-services/blob/master/scripts/concat-declaration.js] that does the job
