### ISSUE TITLE
Union discrimination breaks when destructuring parameters

### ISSUE THREAD

**Issue by tomchambers2** [microsoft/TypeScript#38020] opened 2020-04-17 10:54 UTC
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:** discriminated discrimination union destructured parameters

**Code**

```ts
type Action = | {type: 'add', payload: {toAdd: number}}  | {type: 'remove', payload: {toRemove: number}}

const reducerBroken = (state: number, {type, payload}: Action) => {
    switch (type) {
        case 'add':
            return state + payload.toAdd
        case 'remove':
            return state - payload.toRemove
    }
}


const reducerWorking = (state: number, action: Action) => {
    switch (action.type) {
        case 'add':
            return state + action.payload.toAdd
        case 'remove':
            return state - action.payload.toRemove
    }
}
```

**Expected behavior:**
Typescript recognises that the `type` of the action has been checked and that the action has been refined to a specific one where the `payload` properties can be safely accessed.

**Actual behavior:**
Typescript does not refine the type and it errors saying that the `action` could be any of the `payload`s specified in the union type.

**Playground Link:** 
https://www.typescriptlang.org/play/?ssl=21&ssc=2&pln=1&pc=1#code/FAFwngDgpgBAggYxASwPYDsYF4YB8YDe40AXDAOQCGAJteQDQwSVgA2qNZRqctZ6AVwC2AIygAnAL6SYeQsShly4qENQA3KAyYt2neagBKqjYpiDRE6cGAIMAZxAwV1AQgkAhcagDWUTDgAFI6UIGYWYuKMRJBQjMxsHNSSZIgoGACU2AB8hMCysvYA7sggCAAWMIEKWQT5BQ0IlPawVLTkJPUN3c5QIALimCFhMADUOok0AHQgPLRd3U0tFCpqmh0LPbIq-YMww7AAtBN61DNGJpoLksA3Nnbojr2u7uIA6qjiPsjoAObYVQO-GEkUYlCQaHQqQhmRyeQaxVKFSq4PS6BmsVqmwKS1aNDonS23R2AyGIFCsHGqMhUwSp3OvGo2NkuJWly0hKJBRJewOMGO1IwtN0SXOxjWUGutyAA

**Related Issues:**

**Comment by MartinJohns** [comment] 2020-04-17 11:33
Duplicate of #12184.

**Closed** 2020-04-17 12:54 UTC
