### ISSUE TITLE
TypeScript 2.0.3 narrows enum type and causes compile error

### ISSUE THREAD

**Issue by dsehnal** [Microsoft/TypeScript#11067] opened 2016-09-22 19:21 UTC
**TypeScript Version:**  2.0.3

**Code**

```ts
enum Enum { A, B }
function modify(x: { a: Enum }) { x.a = Enum.B; }
function doStuff() {
    let x = { a: Enum.A };
    if (x.a === Enum.A) {
        modify(x);
        if (x.a === Enum.B) {
            // ...
        }
    }
}
```

**Expected behavior:**

Expected to compile, code was working in version 1.8.4.

**Actual behavior:** 

Error at line ``if (x.a === Enum.B)``: Operator '===' cannot  be applied to types 'Enum.A'  and 'Enum.B'.

**Comment by mhegazy** [comment] 2016-09-22 19:25
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/10665.  please see https://github.com/Microsoft/TypeScript/issues/10665#issuecomment-247059194 for more details.

**Closed by mhegazy** 2016-09-22 19:25 UTC
