### ISSUE TITLE
transpileModule fails when declarationMap is specified  

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#59641] opened 2024-08-15 13:16 UTC
### 🔎 Search Terms

transpileModule declarationMap

### 🕗 Version & Regression Information

- This changed between versions 5.4 and 5.5

### 🙁 Actual behavior

When calling transpileModule with options that specify both `declaration` and `declarationMap`, `transpileModule` will force to false `declaration` but will leave `declarationMap` as is resulting in the error: `error TS5069: Option 'declarationMap' cannot be specified without specifying option 'declaration' or option 'composite'.`

### 🙂 Expected behavior

`transpileModule` should set both `declaration` and `declarationMap` to false (or neither)

**Comment by jakebailey** [comment] 2024-08-15 14:48
Technically a dupe of https://github.com/microsoft/TypeScript/issues/31991 but it's been a while

**Comment by dragomirtitian** [comment] 2024-08-15 14:49
I honestly searched for an existing bug but did not find it :(

**Comment by jakebailey** [comment] 2024-08-15 14:55
I only found that issue last night because I sorted all issues by least recently modified to find closable/interesting issues 😅

**Comment by jakebailey** [comment] 2024-08-15 14:58
> It's strange that this is newly impacting us. We did not have an issue before 5.5 RTM.

I'd suspect it was #58261

**Comment by dragomirtitian** [comment] 2024-08-15 15:52
> > It's strange that this is newly impacting us. We did not have an issue before 5.5 RTM.
> 
> I'd suspect it was #58261

Yeah probably. I also though so, that's why I searched for newest issues instead of going back to 2019. I was convinced it's a recent regression.

**Comment by jakebailey** [comment] 2024-08-15 22:03
My guess would be that it was actually "fixed" a while ago, then re-broken again.

**Closed** 2024-08-15 23:57 UTC
Labels: Duplicate
