### ISSUE TITLE
Less verbose transform of nullish coalescing and optional chaining

### ISSUE THREAD

**Issue by dfahlander** [microsoft/TypeScript#42047] opened 2020-12-18 23:10 UTC
## Search Terms

Nullish !=

## Suggestion

I love nullish coalescing and optional chaining and I love Typescript! But TS could transpile nullish coalescing a bit less verbose since:

    (expr !== null && expr !== void 0)

...is equivalent to:

    (expr != null)

See http://adripofjavascript.com/blog/drips/equals-equals-null-in-javascript.html.

I've created a PR #42044 that would make this change. This is my first PR in this repo so I'm not sure what the test requirements are. Seems it got cought in something.

## Use Cases

As a library vendor, I want to use nullish coalescing and optional chaining without sacrificing the final size of my library.

## Examples

Source:
```ts
return {
  from: range.lower ?? -Infinity,
  to: range.upper ?? Infinity
}
```

Transpiled:

```ts
var _c, _d;
return {
  from: (_c = range.lower) != null ? _c : -Infinity,
  to: (_d = range.upper) != null ? _d : Infinity
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-12-18 23:47
Duplicate of #34670.

**Comment by dfahlander** [comment] 2020-12-19 06:37
I also note that there was an explanation of this browser-specific exception https://github.com/microsoft/TypeScript/issues/34670#issuecomment-581196685 including a conclusion to be using `!= null` as the better alternative, given the use case for document.all and it's reason.

**Closed** 2020-12-21 18:00 UTC
Labels: Duplicate

**Comment by ajafff** [comment] 2021-01-08 21:06
For those who still want this to happen: I wrote a little transformer that hooks into the compilation and changes the output to the compact version using loose equality comparison: https://www.npmjs.com/package/ts-transform-compact-nullish-compare
