### ISSUE TITLE
Return type of 'super()' should be 'this', not 'void'

### ISSUE THREAD

**Issue by rbuckton** [microsoft/TypeScript#42298] opened 2021-01-12 19:21 UTC
Found when reviewing #29374. We currently treat the return type of `super()` as `void`, but it really should be `this`.

https://github.com/microsoft/TypeScript/blob/eb7388a5b9ed19ebc916f92976448993b7d39b09/tests/baselines/reference/derivedClassSuperProperties.errors.txt#L534-L536

> This error is interesting because the result of `super()` is certainly not `void`. This isn't something you need to address, however.

_Originally posted by @rbuckton in https://github.com/microsoft/TypeScript/pull/29374#discussion_r554206652_

**Comment by craigphicks** [comment] 2021-01-12 19:28
Why **should/must** it be 'this'?  I am not questioning that it **could** be this, as a matter of design choice.  Does the current return type `void` cause any problems?

**Comment by rbuckton** [comment] 2021-01-12 19:31
Because that's the behavior of `super()` in a constructor in ES2015. When you call `super()`, it sets the `this` value:

```ts
class Base {}
class Derived extends Base {
  constructor() {
    let x = super();
    console.log(x === this);
  }
}
new Derived(); // logs: true
```

**Comment by MartinJohns** [comment] 2021-01-12 19:40
Related: #38519

**Comment by MartinJohns** [comment] 2021-01-12 19:44
Duplicate of #37847.

**Comment by craigphicks** [comment] 2021-01-12 20:13
> Because that's the behavior of `super()` in a constructor in ES2015. When you call `super()`, it sets the `this` value:
> 
> ```ts
> class Base {}
> class Derived extends Base {
>   constructor() {
>     let x = super();
>     console.log(x === this);
>   }
> }
> new Derived(); // logs: true
> ```

So the reason 'for it' would be so that JS code could pass the TS compiler.
Are there are examples where JS doesn't pass the compiler?  I seem to remember so. 

I can see reasons 'against it': `x` would be a duplicate of `this` and the compiler has to track that semantically.  It's more confusing for a human reader to see two symbols referencing the same object.

**Comment by ExE-Boss** [comment] 2021-01-14 00:37
> `x` would be a duplicate of `this` and the compiler has to track that semantically.

That’s already supported:
```ts
let x: this;
```

**Comment by LongTengDao** [comment] 2021-01-15 11:12
> Why **should/must** it be 'this'? I am not questioning that it **could** be this, as a matter of design choice. Does the current return type `void` cause any problems?

```ts
class A {
    constructor () { return super(); }
}
```

It's faster than default `constructor`.

**Comment by ExE-Boss** [comment] 2021-01-15 17:32
For `Array`, you might want to do:
```js
class MyArray extends Array {
	constructor(length = 0) { return super(+length) }
}
```

to correctly support <code>[ArraySpeciesCreate](https://tc39.es/ecma262/#sec-arrayspeciescreate)</code> with non‑0 <var>length</var>.

**Closed** 2021-01-17 18:00 UTC
Labels: Duplicate
