### ISSUE TITLE
strictNullChecks works unexpectedly with async-await

### ISSUE THREAD

**Issue by heycalmdown** [Microsoft/TypeScript#13858] opened 2017-02-03 06:15 UTC
**TypeScript Version:**  2.1.5

**Code**

```ts
async function compileSuccess() {
    let id: string;
    Promise.resolve().then(() => {
        id = 'good luck!';
    }).then(() => {
        console.log(id);
    });
}

async function compileFailure() {
    let id: string;
    await Promise.resolve().then(() => {
        id = 'bad luck!';
    });
    console.log(id); // error TS2454: Variable 'id' is used before being assigned.
}
```

It might be related with https://github.com/Microsoft/TypeScript/issues/11498

**Comment by HerringtonDarkholme** [comment] 2017-02-03 06:32
Technically we can inline the function in `then` call since they are known to be executed before following statement (or throw an exception so following statement never reaches). But it might be very hard to tell whether a function is in `then`. 

Yet, why not just stripping the function? Removing extraneous `then` function is supposed to be one feature of async/await.

```ts
async function compileFailure() {
    let id: string;
    await Promise.resolve()
    id = 'bad luck!';
    console.log(id);
}
```

**Comment by heycalmdown** [comment] 2017-02-03 06:42
😄 
Because it was a try to make the real code simple.

```ts
async function scope(fn) {
  // doing something with bluebird disposer
  return await Bluebird.using(getSomeResource(), fn);
}

async function compileFailure() {
    let id: string;
    await scope(() => {
      id = 'bad luck!'; 
    });
    console.log(id);
}
```

I thought it would be hard to determine whether the inner code would be called or not. But bugs are bugs.

**Comment by mhegazy** [comment] 2018-02-12 21:28
Duplicate of #11498

**Closed** 2018-02-27 20:54 UTC
Labels: Duplicate
