### ISSUE TITLE
Auto import not providing suggestions (typescript)

### ISSUE THREAD

**Issue by ms747** [microsoft/TypeScript#36203] opened 2020-01-14 18:00 UTC
Code Insiders also has the same issue.

- VSCode Version:
1.41.1
26076a4de974ead31f97692a0d32f90d735645c0
x64
- OS Version:
Linux Mint 19.2
Steps to Reproduce:
1. Write "testModule" (third party npm module) and press Ctrl + Space or Ctrl + .  ( Previously it used to show options now I've to manually import it and shows no suggestions)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-01-15 17:07
Are there any other files in your project that reference `typeorm`? (also, is it listed in the package.json?)

**Comment by ms747** [comment] 2020-01-15 17:21
1. I have various files which reference typeorm to create models. ( Nestjs project )
2. Typeorm is listed within my package.json

**Comment by DanielRosenwasser** [comment] 2020-01-15 21:37
I think this is a duplicate of #36042.

A good way to test this is to see whether you can extend a class declared in an `@types` package?

**Comment by ms747** [comment] 2020-01-16 07:52
Typeorm in itself is a typescript library so there is no @types package for it.

![alt text](https://i.ibb.co/Xtn8jTG/error.png)

Also, I have two models in the same folder yet typescript is unable to import external module properly for one of them. I get typescript errors but compiles perfectly.

**Closed** 2020-01-18 05:09 UTC
