### ISSUE TITLE
Contextual typing failure with discriminated type and partially overlapping type.

### ISSUE THREAD

**Issue by yannack** [Microsoft/TypeScript#16513] opened 2017-06-14 03:37 UTC
**TypeScript Version:**  2.3 + 

**Code**

```ts
type MyType = 'meep'|'bidi';
type ThatType = 'moop'|'meep';

interface Foo {  
  isfoo: 'true';
  foo: MyType;
}
interface Bar {
  isfoo: 'false';
  foo: string;
}

let arr: Array<Foo|Bar>;

arr = [{foo: 'meep', isfoo: 'true'}, 
       {foo: 'moop', isfoo: 'false'}];
```

**Expected behavior:** This should compile. The discriminant `isfoo` should be enough to figure out that the first element of the array can only be a Foo and the second is a Bar.

**Actual behavior:**
ERROR(15,1): : Type '({ foo: string; isfoo: "true"; } | { foo: string; isfoo: "false"; })[]' is not assignable to type '(Foo | Bar)[]'.
  Type '{ foo: string; isfoo: "true"; } | { foo: string; isfoo: "false"; }' is not assignable to type 'Foo | Bar'.
    Type '{ foo: string; isfoo: "true"; }' is not assignable to type 'Foo | Bar'.
      Type '{ foo: string; isfoo: "true"; }' is not assignable to type 'Foo'.
        Types of property 'foo' are incompatible.
          Type 'string' is not assignable to type 'MyType'.

However, if Foo's `foo` is declared as a `string`, then it compiles fine. If Bar's `foo` is declared as a `ThatType`, then it also compiles fine.

**Comment by devdoomari** [comment] 2017-06-14 07:15
just a small question, but how is 'ThatType' being used for?

**Comment by yannack** [comment] 2017-06-14 13:21
Hi,
It's part of the description of the bug. If interface Bar is declared with
its property 'foo' of type 'ThatType', then the compiler has no issues. So
this works fine:

type MyType = 'meep'|'bidi';
type ThatType = 'moop'|'meep';

interface Foo {
  isfoo: 'true';
  foo: MyType;
}
interface Bar {
  isfoo: 'false';
  foo: ThatType;
}

let arr: Array<Foo|Bar>;

arr = [{foo: 'meep', isfoo: 'true'},
       {foo: 'moop', isfoo: 'false'}];


But if ThatType = string; then the compile error comes back.

**Comment by DanielRosenwasser** [comment] 2017-06-19 19:41
The first symptom we're seeing is that `{foo: 'meep', isfoo: 'true'}` is not assignable to `Foo`.

What we think is happening is that when looking at the type of the `foo` property, we get the contextual type to decide whether to widen. We see that the contextual type is `string | MyType` which subtype-reduces to `string`. So the type of the `foo` property is widened to `string`, but at that point it's no longer compatible with `Foo`.

**Comment by chmln** [comment] 2017-08-22 18:56
Similarly ran into this issue when typing responses from a database.

I'm aware that the current solution is to employ [discriminated](https://basarat.gitbooks.io/typescript/docs/types/discriminated-unions.html) type unions with varying string values.
But it doesn't feel right to pollute my schemas and data with unnecessary fields.

```ts
interface T {
    _id: string
    revision: number
}

interface Error {
    _id: undefined
    error: string  
}

const getDoc = (s: string): T | Error => {
    if (Math.random() < 0.5) {
        const r: T = {
            _id: "123",
            revision: 1
        }
        return r
    }

    else {
        const e: Error = {
            error: "Not found"
        }
       // Error: property 'name' is missing in type { error: string }
        return e
    }    
}

const doc = (id: string) => {
    const d = getDoc(id)
    if (d._id === undefined) {
        console.log(d.error)
         // 'error' doesnt exist on type 'T'
    }

    else {
        console.log(d.revision)
        // Error: 'revision' doesnt exist on type 'Error'
    }
}
```

**Comment by sandersn** [comment] 2017-10-03 22:13
Duplicate of #16457

**Closed** 2017-10-03 22:13 UTC
Labels: Bug, Duplicate
