### ISSUE TITLE
Class expressions don't support constructors that return any

### ISSUE THREAD

**Issue by spion** [Microsoft/TypeScript#5914] opened 2015-12-03 19:22 UTC
Example:

```typescript
function f(T:{new (...args:any[]):any}) {
	return class extends T {}
}
```

Error:

```
src/test.ts(2,23): error TS2509: Base constructor return type 'any' is not a class or interface type.
```

Seemingly arbitrary fix:

```typescript
interface I {}
function f(T:{new (...args:any[]):I}) {
	return class extends T {}
}
```

Afaik `any` should be an acceptable type here?

**Comment by mhegazy** [comment] 2015-12-03 19:36
Extend clause only supports object types, no type arguments, no intersection, no union, and since any can be any of these, it is not supported. a target of an extend clause must be something that has a "known shape", so that the extend checks can run when checking the class body, and give meaningful errors about what a class did or did not extend incorrectly.

i think this issue is a duplicate of  #4890

**Closed** 2015-12-03 19:36 UTC
Labels: Duplicate

**Comment by spion** [comment] 2015-12-04 01:25
There is a meaningful way to check whether it extends `{}`. That doesn't work either though:

```typescript
function f(T:{new (...args:any[]):{}}) {
    return class extends T {}
}
```

Yields the same error.

If however you use a named interface, it doesn't.
