### ISSUE TITLE
Only In Js files the require call should be used for string literal completion of modules

### ISSUE THREAD

**Issue by sheetalkamat** [microsoft/TypeScript#11371] opened 2016-10-04 22:46 UTC
There are multiple tests already in `tests/cases/fourslash` but lets just look at `tests/cases/fourslash/completionForStringLiteralNonrelativeImport1.ts`

``` typescript
// @Filename: tests/test0.ts
 import * as foo1 from "f/*import_as0*/
 import * as foo2 from "fake-module//*import_as1*/
 import * as foo3 from "fake-module/*import_as2*/

 import foo4 = require("f/*import_equals0*/
 import foo5 = require("fake-module//*import_equals1*/
 import foo6 = require("fake-module/*import_equals2*/

 var foo7 = require("f/*require0*/
 var foo8 = require("fake-module//*require1*/
 var foo9 = require("fake-module/*require2*/
```

**Expected behavior:**
No completion list in require calls in `test0.ts` and completion list if there was `test1.js`

**Actual behavior:** 
Completion list in `test0.ts`

**Comment by Andarist** [comment] 2023-08-27 12:47
Those completions are still available, at least with certain tsconfig settings. Perhaps @andrewbranch could chime in here to specify the exact rule that should be used here - or to confirm that this should just always be disallowed.

**Comment by andrewbranch** [comment] 2023-08-28 16:33
I think best-effort completions are good even if module resolution will not kick in.

**Comment by Andarist** [comment] 2023-08-28 16:41
Should this issue get closed as "working as intended" then? :)

**Comment by andrewbranch** [comment] 2023-08-28 16:47
Sure.

**Closed by andrewbranch** 2023-08-28 16:47 UTC
Labels: Working as Intended
