### ISSUE TITLE
Unexpected type inference from Array.reduce

### ISSUE THREAD

**Issue by InventingWithMonster** [Microsoft/TypeScript#20407] opened 2017-12-02 09:59 UTC
**Code**

```ts
type Foo = {};

const arrayOfFoo: Foo[] = [];

const a: any[] = arrayOfFoo.reduce((p, c) => p, []);
const b: any[] = [0, 1, 2].reduce((p, c) => p, []);
```

**Expected behavior:**
Both `a` and `b` should work typed as `any[]`.

**Actual behavior:**
`a` errors:
```
Type 'Foo' is not assignable to type 'any[]'.
  Type 'string' is not assignable to type 'any[]'.
const a: any[]
```

Even if I pass a typed array (as `Foo[]`) in as the initial value to `arrayOfFoo.reduce`, it still insists that it's returning `Foo`. Whereas `[0, 1, 2].reduce` seems to understand it's returning the array.

**Comment by j-oliveras** [comment] 2017-12-02 12:02
I think this works as intended. You can assign `[]` to type `{}`:
```ts
type Bar = {};
const f: Bar = []; // This is valid
```
With your const `a` typescript use a overload of reduce that the initial value has the same type as an item (because  `[]` is assignable to type `{}`). With `b` uses the reduce overload that the initial type can has a different type.

You example works is type `Foo` is declared different to `{}` and `any`. For example:
```ts
type Foo = { a: number };

const arrayOfFoo: Foo[] = [{ a: 1 }, { a: 2 }, { a: 3 }];

const a: any[] = arrayOfFoo.reduce((p, c) => p, []);
const b: any[] = [0, 1, 2].reduce((p, c) => p, []);
```

**Comment by bjnsn** [comment] 2017-12-08 22:01
I have an issue that seems related. Hopefully it can help guide the resolution.

The following (contrived example) works properly. It will infer that sum has type `{x: number; z: number;}`.

     const points = [{ x: 1, y: 1 }, { x: 2, y: 2 }];

     const sum = points.reduce((acc, point) => {
      	return acc;
     }, {x:0, z: 0})

However, if I pass an accumulator that extends the shape of a point, we run into issues. Specifically, in Typescript 2.6 I get this error: `"Parameter of type '{x: number; y: number; z: number;}' is not assignable to parameter of type '{x: number; y: number;}'."`

     const points = [{ x: 1, y: 1 }, { x: 2, y: 2 }];

     const sum = points.reduce((acc, point) => {
      	return acc;
     }, {x:0, y: 0, z: 0})`

I'm guessing this is somehow tied to the fact that `Arrray.reduce()` uses the first value in the array as the initial value if no accumulator value is provided.

**Comment by RyanCavanaugh** [comment] 2017-12-11 18:09
Possible duplicate of  #18986?

**Comment by mhegazy** [comment] 2018-01-10 20:13
this is actually caused by the change in #18986. Seems that this also reported in https://github.com/Microsoft/TypeScript/issues/20753. 

Seems that this is an intentional break then.

**Closed** 2018-01-10 20:13 UTC
Labels: Breaking Change
