### ISSUE TITLE
Generic type inference does not appear to fill in type of `this` parameter

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#10072] opened 2016-08-01 19:08 UTC
**TypeScript Version:**  nightly

**Code**

```ts
function f<T>(x: T, f: (x: T) => string): void {}
f("", x => x);

function g<T>(x: T, f: (this: T) => string): void {}
g<string>("", function() { return this; });
g("", function() { return this; });
```

**Expected behavior:**

No error. `this` is always of type `string`.

**Actual behavior:** 

In the last line, the type of `this` is still `T`; it hasn't been 'filled in'.

    src/a.ts(6,7): error TS2345: Argument of type '() => T' is not assignable to parameter of type '(this: string) => string'.
      Type 'T' is not assignable to type 'string'.

**Comment by sandersn** [comment] 2016-08-02 14:52
Duplicate of #9673 with a proposed fix at #9746.

**Closed** 2016-08-02 14:53 UTC
Labels: Bug, Duplicate
