### ISSUE TITLE
`lodash.merge` can Bypass Type Check in Typescript

### ISSUE THREAD

**Issue by dsdashun** [microsoft/TypeScript#48950] opened 2022-05-04 11:40 UTC
# Bug Report

### 🔎 Search Terms
lodash+merge

### 🕗 Version & Regression Information
4.x ( haven't tried any older versions )

- I was unable to test this on prior versions because it failed to compile my `node_modules` folder

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wPpwGZQiOAIgBsIATNAC0IG4BYAKEeADsYBTKbZAY3bgCyATwDCEFtmABzOAG9GcOCGSsAXIJUsxE6fQaKIYGAH51AeSPBxyYtslS9AX0bM2nbnw2s70uQrikUgAy7ABu7MTqqDBQrA6MzkwMrBxcvPwWMFYsNj4y8vpwAEYQEMQA0uxC6iVl7MgseooplUIAjKZwLACuIEWcTi4MxOzwIKLi9mZFAFbqwnlwALx+hcpqq4qKgSHhkUSs2BCEADT+jmcMjnqMI2OcUuxkedNzghM68UkA9AiMIA8ni9ZstMAA6AFQR4AClkFyUHymswAlP9Ac9JtJXmDDPAVgAmADMABYaFs4N9vnAYJRgOgAO7AYjEOBQdiQWBwTh4KBwcRwHj4MBM5BZcQnOD02k8ShwOlcgAeYHYPA4ZEYCG+Q0hjwxn1eoIwEMBsPh42BMwlBQMRnUbSJl0cyLJlOptPQ8pYEHg7CVKrV6mA9waDP4PAacG6qH4pAoqEoxqh-BgEBQqFQ0hYKCzEFm-slQdl9LwLBkMCEyoAhIxBSxUHUwYFoTqgZipK9nYwgA)

### 💻 Code

```ts
import * as _ from "lodash";

interface MyConfig {
  main: MainConfig;
  opt?: OptionalConfig;
}

interface MainConfig {
  logLevel: string;
}

interface OptionalConfig {
  boolKey: boolean;
  intKey1?: number;
}

let myConfigObj: MyConfig = {
  main: {
    logLevel: "info",
  },
};

let mergedConfigObj: MyConfig;

/*
mergedConfigObj = _.merge({}, myConfigObj)
mergedConfigObj.opt = 234;    // this will report error on compilation, which is expected
*/

mergedConfigObj = _.merge({}, myConfigObj, {
  opt: 123,
}); // this is not expected: it means we can use lodash.merge to assign an object with wrong type!
console.log(mergedConfigObj);    // result: { main: { logLevel: 'info' }, opt: 123 }

```

### 🙁 Actual behavior
Surprisingly, this code can compile without errors.  This means we can use `lodash.merge` to assign some optional fields with the wrong type, thus bypassing the type check in typescript

### 🙂 Expected behavior
I expect the code will compile error, indicating that the `opt` field cannot assign with a number type

**Comment by jcalz** [comment] 2022-05-04 14:41
I'm not sure why this is being filed against TS instead of against lodash, whose typings are (I think) in [DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/lodash).

Still, this is similar enough in spirit to the various issues that have been filed against `Object.assign()` that we could probably say this is a duplicate of those, e.g., #31982.  Intersections are a "best available compromise" for the results of this sort of merge; you could write something quite complicated to _try_ dealing with conflicting properties, but there will always be edge cases.

**Closed** 2022-05-07 10:00 UTC
Labels: External
