### ISSUE TITLE
Decorator metadata should tolerate nullable union types

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#9924] opened 2016-07-25 08:34 UTC
For example, the following code would get metadata of the first parameter type as `Object` instead of `Path`, and thus make strict null checks incapable of coexisting with type metadata.

``` ts
@command()
export default class extends Command {
    async execute(
        @param({
            name: 'config',
            default: 'dist.config.js'
        })
        configFilePath: Path | undefined,
        options: DistributeOptions
    ) {
        // ...
    }
}
```

**Comment by mhegazy** [comment] 2017-04-27 16:18
Duplicate of #13449

**Closed by mhegazy** 2017-04-27 16:18 UTC
