### ISSUE TITLE
Mapped type error inside but not outside generic function

### ISSUE THREAD

**Issue by RafaelSalguero** [Microsoft/TypeScript#16158] opened 2017-05-30 22:50 UTC
**TypeScript Version:**  2.3.4

**Code**

```ts
type MT<Keys extends string> = {
    [key in Keys]: number
}

type keys = "x" | "y";
interface Vector { x: number, y: number };

const vectorA: Vector = { x: 10, y: 20 };
const vectorB: MT<keyof Vector> = vectorA; //Correctly works
const vectorC: MT<string> = vectorB; //Correctly works
const vectorD: MT<keys> = vectorA; //Correctly works  

function MyFunc<TData extends MT<keyof TData>>(data: TData) {
    const a : TData = data;
    const b: MT<keyof TData> = a; //Correctly works
    //error!
    const c: MT<string> = b; //MT<keyof TData> is not assignable to MT<string>
}
```

**Expected behavior:**
Variable `b` should be assignable to `c` since `keyof TData` its a `string` union
**Actual behavior:**
Type MT&lt;keyof TData&gt; is not assignable to MT&lt;string&gt;

**Comment by ahejlsberg** [comment] 2017-05-31 16:04
Duplicate of #14548 (since, in the example above, `MT<string>` is effectively the same as `{ [key: string]: number }`).

**Comment by mhegazy** [comment] 2017-06-14 22:38
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-06-14 22:38 UTC
Labels: Duplicate
