### ISSUE TITLE
FR: More brilliant Type inference

### ISSUE THREAD

**Issue by Jack-Works** [Microsoft/TypeScript#20249] opened 2017-11-24 08:01 UTC
**TypeScript Version:**  2.6.1

**Code**

```ts
type Response200 = { url: string } & { response: Response & { status: 200 } }
type Response201 = { data: any[] } & { response: Response & { status: 201 } }
declare function request(): Response200 | Response201
const result = request()
switch (result.response.status) {
    case 200:
	result.response.status // <- (property) status: number & 200
	// Expected status: 200

	result // type = Response200 | Response201, Expected Response200
    break
}
```

**Comment by ORESoftware** [comment] 2017-11-26 21:38
Can you add more of a description of the problem?

**Comment by DanielRosenwasser** [comment] 2017-11-26 23:59
Partial duplicate of #18758 (also see #20127), though I am surprised we don't collapse `number & 200` to `200`.

**Closed** 2017-12-12 18:21 UTC
Labels: Duplicate
