### ISSUE TITLE
TypeScript Map<T, U>  type check bug `Object is possibly 'undefined'.ts(2532) `

### ISSUE THREAD

**Issue by xgqfrms** [microsoft/TypeScript#52929] opened 2023-02-23 07:43 UTC
# Bug Report

### 🔎 Search Terms

`Object is possibly 'undefined'.ts(2532) `

### 🕗 Version & Regression Information

- test versions `^4.7.4` and `4.9.4`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5IBQAZgK4B2MALgJZwWgC2AhgFZz63WQCiANkiZIK1AEwAKCmSaYAXKGlMARgQDaAXQCUCpavybQAbyKhYDTNVDKWmFAF5QAPydSZmAHSCKqajlBgAMxaANym5hSWzCwADqCOFEgA7hCxADx6BAA0ijL6AHwSoeHwkVZ2VgnJoADKSNQZeQSFxWYknBKlUUqgcCS5slrG4Wa0JBIAhKwxHji2bkxaQyZmq9EzFQs5AIytqwC+oEj8dsNrZtMem0o5l6j1C0MA1KC7YWv7I6BjEncPSkN8tZbEhll8zBUPCwEAhHu8DuFPmZCNQyPhGGoPFiKhowvswkA)

### 💻 Code

```ts
function majorityElement2(nums: number[]): number[] {
  const base = ~~(nums.length / 3);
  const map = new Map<number, number>();
  const set = new Set<number>();
  for(const num of nums) {
    if(!map.has(num)) {
      map.set(num, 1);
    } else {
      map.set(num, map.get(num) + 1);
    }
    if(map.get(num) > base) {
      set.add(num);
    }
  }
  return [...set];
};

```

### 🙁 Actual behavior

TypeScript can not understand the `if...else` condition, and shows an error.

![image](https://user-images.githubusercontent.com/7291672/220845808-d49da73b-bf97-424b-afdb-bef086894339.png)

### 🙂 Expected behavior

TypeScript can understand the `if...else` condition, without showing an error.

It should work like below with optional chaining `??`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

```ts
function majorityElement2(nums: number[]): number[] {
  const base = ~~(nums.length / 3);
  const map = new Map<number, number>();
  const set = new Set<number>();
  for(const num of nums) {
    if(!map.has(num)) {
      map.set(num, 1);
    } else {
      map.set(num, (map.get(num) ?? 0) + 1);
    }
    if((map.get(num) ?? 0) > base) {
      set.add(num);
    }
  }
  return [...set];
};
```

**Comment by MartinJohns** [comment] 2023-02-23 07:53
Duplicate of #30268 / #9619.

**Closed** 2023-02-23 08:03 UTC

**Comment by fatcerberus** [comment] 2023-02-23 14:57
> `~~(nums.length / 3)`

I know this isn't related to the issue but you might want to think twice about using `~~` in place of `Math.floor` - it coerces to 32-bit:

```
> ~~3000000000
-1294967296
```

Ouch.

**Comment by xgqfrms** [comment] 2023-02-24 01:21
> 

Yeah, you are right. Thanks for your time.

But in my scenario, using it is not only suitable but also improves performance, nothing more.

**Comment by MartinJohns** [comment] 2023-02-24 12:45
> but also improves performance

Did you actually **measure** if it has a positive performance impact in your application? Otherwise you should prefer clean and easy to understand code. I wouldn't have a clue what `~~number` does and would first have to look it up. Probably every time I see it, given the obscurity of it.

**Comment by xgqfrms** [comment] 2023-02-25 15:08
@MartinJohns 

## Your question is beyond the topic of this issue.

If you don't know something new, maybe you should take the initiative to learn it first.


## this article might help you

https://medium.com/@s.kutyepov/how-a-k-a-double-bitwise-not-operator-in-javascript-can-help-boost-performance-of-your-app-3d973078ff42

**Comment by MartinJohns** [comment] 2023-02-25 17:36
Oh wow, what astonishing ignorance.

**Comment by MartinJohns** [comment] 2023-02-25 17:38
You completely missed the point of my comment.

**Comment by RyanCavanaugh** [comment] 2024-06-26 20:17
Because it's a duplicate of another issue
