### ISSUE TITLE
`NonNullable<T>` type does not have a corresponding `Nullable<T>` type

### ISSUE THREAD

**Issue by ctjlewis** [microsoft/TypeScript#51255] opened 2022-10-21 06:09 UTC
*Pro forma* bug report for https://github.com/microsoft/TypeScript/pull/51254.

**Comment by MartinJohns** [comment] 2022-10-21 08:28
This is intentional. Duplicate of #39522.

**Comment by DanielRosenwasser** [comment] 2022-10-21 20:12
Explained at https://github.com/microsoft/TypeScript/pull/51254#issuecomment-1287390320

**Closed by DanielRosenwasser** 2022-10-21 20:12 UTC
Labels: Duplicate, Declined
