### ISSUE TITLE
Missing interface definition for Highlight API 

### ISSUE THREAD

**Issue by Momomash** [microsoft/TypeScript#58051] opened 2024-04-03 08:16 UTC
### 🔎 Search Terms

Highlight
Highlight API
CSS custom highlight api

### 🕗 Version & Regression Information

Version 4.9.5

This happen in the 'Nightly' version as well.

Please keep and fill in the line that best applies:

This is a crash
This changed between versions ______ and _______
X This is the behavior in every version I tried, and I reviewed the FAQ for entries about: Could not find anything relevant.
I was unable to test this on prior versions because _______

### ⏯ Playground Link

A link to a TypeScript Playground "Share" link which shows this behavior: http://www.typescriptlang.org/play/?ts=Nightly

### 💻 Code

```ts
const hl = new Highlight()
```

### 🙁 Actual behavior

Cannot find name 'Highlight'.(2304)

### 🙂 Expected behavior

Should return a newly created Highlight object.

[Constructor](https://developer.mozilla.org/en-US/docs/Web/API/Highlight#constructor)
[Highlight()](https://developer.mozilla.org/en-US/docs/Web/API/Highlight/Highlight)

```ts
let hl = new Highlight();
console.log(hl) // Highlight {priority: 0, type: 'highlight', size: 0}
```

### Additional information about the issue

There was been a similar issue before — https://github.com/microsoft/TypeScript/issues/53003. The issue was closed because the Highlighter API was experimental — https://github.com/microsoft/TypeScript/issues/53003#issuecomment-1447000779. 

But now the **Highlighter API** is no longer experimental and is supported by many browsers: 
https://developer.mozilla.org/en-US/docs/Web/API/CSS_Custom_Highlight_API#browser_compatibility
![Снимок экрана 2024-04-03 в 11 16 19](https://github.com/microsoft/TypeScript/assets/50700388/fcb69d46-0ad9-4309-a0be-fc7af3a65bc0)

**Comment by MartinJohns** [comment] 2024-04-03 08:34
Duplicate of https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1698.

**Closed** 2024-04-03 10:59 UTC
