### ISSUE TITLE
Decorated anonymous classes

### ISSUE THREAD

**Issue by errorx666** [Microsoft/TypeScript#21145] opened 2018-01-11 20:05 UTC
**TypeScript Version:**  2.6.0

**Code**

```ts
import { bindAll } from 'lodash-decorators';

class Base {}

const foo = new @bindAll() class extends Base {

}
```

**Expected behavior:**
No error.  foo is an instance of a class derived from Base and decorated with bindAll.

**Actual behavior:**
Expression expected.

Emit is:
```js
    var Base = /** @class */ (function () {
        function Base() {
        }
        return Base;
    }());
    var foo = new ;
    var default_1 = /** @class */ (function (_super) {
        __extends(default_1, _super);
        function default_1() {
            return _super !== null && _super.apply(this, arguments) || this;
        }
        default_1 = __decorate([
            lodash_decorators_1.bindAll()
        ], default_1);
        return default_1;
    }(Base));
    ;
```

**Related:**
I'm actually transpiling with babel, not TypeScript.  Babel accepts this syntax and it works as expected, but Visual Studio keeps showing expression expected warnings (via Salsa).

**Comment by mhegazy** [comment] 2018-01-11 20:36
Duplicate of https://github.com/Microsoft/TypeScript/issues/7342

**Closed** 2018-01-25 23:25 UTC
Labels: Duplicate
