### ISSUE TITLE
Incorrect assignability between type `{}` and `object`

### ISSUE THREAD

**Issue by whzx5byb** [microsoft/TypeScript#50502] opened 2022-08-29 03:35 UTC
# Bug Report

### 🔎 Search Terms

{}, empty object type, subtype

### 🕗 Version & Regression Information

- This is the behavior in every version I tried.
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/C4TwDgpgBMCMUF4oHsBGArCBjYUIA9gIA7AEwGcoBvAXygH4YAnAV2gC4oAzAQwBtyEANwAoAPRioUgHqNgrCABooPSgUg4IpEaEgwATImp0CRMpTSYcDZmyideA4eMky5C5aha5yAC2QsfKRQqNCOgjrg0MAAzEbk8gCWxADmeIQkFMY28nYO-IKiElJQsrZKKmr4GkTautEALEa06WZZCUzJae553AXOxW59Tsqq6TVaIiJcLMQ4icjEUGBMyKQsWBAASrPAiQC2EACiTKtMADwAKq2ZlLQAfAAUiZyXAJTUIiVQWIsJUPsjMQIAB3KAAdQgPAA1gBZHhgc6WbDAZTEFj7UJMe6ib77AB0gmAz2UAAY3qIaFMVmsNttdgdjqdkExHuSoMVfvswIk+BByJ5vFAQby+DBfKswQByACSxAAbvxEsFFXw7CxBMExiCodCAQioNCICApUA)

### 💻 Code

```ts
type t1 = object extends {} ? true : false;
//   ^? true, as expected
type t2 = {} extends object ? true : false;
//   ^? true, but should be false
type t3 = string extends {} ? true : false;
//   ^? true, as expected
type t4 = {} extends string ? true : false;
//   ^? false, as expected

function produceRuntimeError<T extends {}>(i: T) {
    const m = new WeakMap<object, number>;
    m.set(i, 0);
}

produceRuntimeError(0) // compiles, but will throw 'Invalid value used as weak map key'

```

### 🙁 Actual behavior

See above.

### 🙂 Expected behavior

> {}, the empty object type literal, is a supertype of all types except null and undefined. 

From https://github.com/microsoft/TypeScript/pull/49119 I'm aware that non-nullable primitive types like `string`, `number`, `object` are subtypes of `{}`. It is obviously incorrect to allow `{}` to be assignable to `object`.

**Comment by fatcerberus** [comment] 2022-08-29 04:42
Hmm, this is tricky.  A type like `{ toString(): string }` is also assignable to `object` (as would be expected), but could likewise be a primitive.  I think this is just an unfortunate bit of fallout from structural typing and probably won't be fixed.

**Comment by RyanCavanaugh** [comment] 2022-08-29 17:17
This is the intended behavior, at least for now. If records and tuples end up creating new kinds of things-with-properties-that-aren't-objects we'll probably reconsider.

**Closed** 2022-08-30 03:16 UTC
Labels: Working as Intended

**Comment by Zzzen** [comment] 2024-01-22 11:54
I believe it's more of a "design limitation" rather than functioning as intended.

```ts
const someObj: object = 1;  // errors, good

const nonNull: {} = 1;
const obj: object = nonNull;    // no error, why?
```
