### ISSUE TITLE
Path completions for Node.js subpath imports

### ISSUE THREAD

**Issue by thetutlage** [microsoft/TypeScript#52460] opened 2023-01-27 13:47 UTC
# Suggestion

Node.js for a while has a way to define [import aliases (known as subpath imports)](url) in `package.json` file. The subpath imports also work fine when I compile my code using `tsc` and inside my code editor (VSCode).

However, as I type the import path in my code editor, no suggestions related to subpath imports are shown.

Given, I have the following subpath import alias inside `package.json`.

```json
{
  "imports": {
    "#controllers/*": "./app/controllers/*.js"
  }
}
```

I should be able to type `#controllers` and get suggestions. Infact, using an export symbol from one of the controller files should write the auto-import using the alias.

### `tsconfig.json`

Following is a trimmed down version of my `tsconfig.json` file.

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "NodeNext",
    "lib": ["ESNext"],
    "rootDir": "./",
    "outDir": "./build",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "types": ["@types/node"]
  },
  "include": ["./**/*"],
  "exclude": ["./node_modules", "./build"]
}
```

## 🔍 Search Terms

- Node subpath imports
- Auto complete subpath imports
- Redirected by https://github.com/microsoft/vscode/issues/128064

## ✅ Viability Checklist

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
Since, TypeScript can understand and compile subpath imports, it will be great, if they are also suggested during import autocomplete

## 📃 Motivating Example

Have nice experience of auto-importing files with aliases.

## 💻 Use Cases

Right now, I have to either manually type the complete import statement by hand. Or type the export symbol name and update the import path to use the subpath alias.

Attaching a small screen recording of the same

https://user-images.githubusercontent.com/1706381/215099932-cf274151-6882-4a14-ba49-3b127a9231e3.mov

**Comment by xobotyi** [comment] 2023-12-20 22:03
Same here, except the IDE used.

Problem is somehow fixable with `paths` cofiguration wthin `tsconfig.json`, but it becomes a problem for cases when some of used packages uses same import alias.

**Comment by mbrevda** [comment] 2024-02-14 13:45
Looks like this was fixed in https://github.com/microsoft/TypeScript/pull/55015

**Comment by RomainLanz** [comment] 2024-02-14 14:18
Is there a version we can try to ensure it works as expected?

In the meantime, we are duplicating it inside the `paths` key of our `tsconfig`.

**Comment by mbrevda** [comment] 2024-02-14 14:30
`npm i typescript@next`

**Comment by DanielRosenwasser** [comment] 2024-08-21 03:21
I believe #55015 adds auto-imports, but not path completions within the string literals.

**Comment by tonivj5** [comment] 2024-08-31 09:42
I can confirm in `5.6.1-rc` helps with auto-imports when there's **already** an import.

1. With supath import already in file:
![image](https://github.com/user-attachments/assets/c5283158-44e1-408f-99b1-fbf12f1b4daf)
2. Without any reference in file:
![image](https://github.com/user-attachments/assets/b7852afe-23a7-420c-800c-80b7e496727f)


And, as @DanielRosenwasser has mentioned, there isn't any completions in import string path
![image](https://github.com/user-attachments/assets/06075f16-8506-4832-8b74-bfd5f73661d8)

**Comment by custardcream98** [comment] 2024-09-03 09:29
For now, it seems that adding the following to your tsconfig.json file does the trick:

```
{
  "compilerOptions": {
    "paths": {
      "#*":["./src/*"],
    }
  }
}
```

**Comment by DanielRosenwasser** [comment] 2024-09-03 22:26
@tonivj5 what `compilerOptions` do you have?

**Comment by tonivj5** [comment] 2024-09-06 09:47
@DanielRosenwasser here it's
```json
  "compilerOptions": {
    "baseUrl": ".",
    "rootDir": ".",

    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,

    "target": "es2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "moduleDetection": "force",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "verbatimModuleSyntax": true,
    "allowJs": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "lib": ["es2022", "ESNext.Disposable", "dom", "es2023.array"],

    "strict": true,
    "noUncheckedIndexedAccess": true,
    "noImplicitOverride": true,

    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "importHelpers": true,
    "pretty": true,

    "sourceMap": true,
    "composite": true,
    "declaration": true,
    "declarationMap": true,
    "incremental": true,

    "emitDeclarationOnly": false,
    "noEmit": false,
    "noEmitOnError": true,

    "tsBuildInfoFile": "./dist/tsconfig.app.tsbuildinfo"
  },
```

**Closed** 2024-10-31 20:33 UTC
Labels: Suggestion, Help Wanted, Domain: Completion Lists

**Comment by anthonyma94** [comment] 2025-03-10 19:22
Sorry to necro this, but I'm still having the issue with no completions in import string path. I'm running VSCode 1.98.0 and TS 5.7.3.

`package.json`
```json
"imports": {
    "#ui/*": {
      "types": [
        "./src/*.tsx",
        "./src/*.ts",
        "./src/*"
      ],
      "default": [
        "./src/*"
      ]
    }
}
```
Autosuggest works for symbols
![Image](https://github.com/user-attachments/assets/5a6474ce-3c3e-4b20-9085-727ff744b5fd)

But not the path itself

![Image](https://github.com/user-attachments/assets/bdf3fbbb-c19a-416a-af36-245d14417ac2)

**Comment by Andarist** [comment] 2025-03-11 07:23
You could create a repro case and open a new issue about this. It's hard to investigate this given the incomplete provided information.

**Comment by anthonyma94** [comment] 2025-03-29 19:22
@Andarist @mbrevda sorry for the late response, created a new issue #61504.
