### ISSUE TITLE
Trying to infer a substring in a template literal leads to the type not matching the template

### ISSUE THREAD

**Issue by JesusTheHun** [microsoft/TypeScript#55855] opened 2023-09-25 10:16 UTC
### 🔎 Search Terms

`template literal infer`, `literal infer`, `infer match`

### 🕗 Version & Regression Information

This changed between versions `4.6.4` and `4.7.4`. Doesn't no work in `5.2.2` nor `nightly`.

### ⏯ Playground Link

https://tsplay.dev/WzDbrN

### 💻 Code

```ts
type InferDelimiter<
  T extends string,
  Delimiter extends string,
> = T extends `${infer Head}${infer Mark extends Delimiter}${string}` ? true : false;

type T1 = InferDelimiter<'foo.bar', '.'>;
```

### 🙁 Actual behavior

`T1` is evaluated to `false`.

### 🙂 Expected behavior

`T1` is evaluated to `true`.

**Comment by MartinJohns** [comment] 2023-09-25 10:22
Your playground link does not match the code from your issue.

Your inferred type `${infer Mark extends Delimiter}${string}` will first infer the `string`, **then** check if it extends `Delimiter`. That's not going to work well.

Any reason why you're inferring the delimiter when you get it provided? When you write `${infer Head}${Delimiter}${string}` it will work.

**Comment by JesusTheHun** [comment] 2023-09-25 10:35
> Your playground link does not match the code from your issue.

The code in the issue only illustrate the issue itself.
The code in the playground include variant of the code when it behaves as expected.

> Your inferred type `${infer Mark extends Delimiter}${string}` will first infer the string, then check if it extends Delimiter. That's not going to work well.

I'm not sure what you mean by that. Are you saying it will try to match the string starting by the end up until it finds `Delimiter` ?

> Any reason why you're inferring the delimiter when you get it provided? When you write ${infer Head}${Delimiter}${string} it will work.

I was writing a type with `Delimiter` being a union, I didn't get what I wanted to I tried to break it down to figure out the issue. So yeah, in my use case `Delimiter` will be a union.

**Comment by JesusTheHun** [comment] 2023-09-25 11:28
Oh ok, thanks for the explanation, I understand now.
This behaviour is indeed confusing.

As for the performance of taking the constraints into account while inferring, because it is inside a template literal, several dramatic optimisations can be made to turn this into a O(1).

**Comment by fatcerberus** [comment] 2023-09-25 13:25
@Andarist If I recall from past discussions, it works this way intentionally for performance reasons, so the template matching algorithm doesn’t ever have to backtrack (any given placeholder either matches on the first try, or it doesn’t match at all).  Two directly adjacent placeholders will only ever match a single character at the first one, so you can do stuff like `${T}${string}` recursively to extract characters from the string one at a time.  This also, however, means that `${number}${string}` doesn’t work intuitively either, and I believe there are issues about that that have been closed as by design/design limitation.  People who want anything more complex tend to get redirected to https://github.com/microsoft/TypeScript/issues/6579.

**Comment by JesusTheHun** [comment] 2023-09-25 14:21
> since the added constraint might be a union (or a generic, or a non-literal...) it definitely makes the whole thing quite tricky

Out of curiosity, what makes it more tricky ? Union means combinatory so it's the same process repeated for each member, for each union, right ? What about generics ?

**Closed** 2023-09-28 01:25 UTC
Labels: Duplicate
