### ISSUE TITLE
Removing 'optional' attributes from a type's properties disallow adding undefined as it's type

### ISSUE THREAD

**Issue by KuSh** [microsoft/TypeScript#46850] opened 2021-11-18 10:19 UTC
# Bug Report

### 🔎 Search Terms

type generic remove optional attribute 

### 🕗 Version & Regression Information

I did test this on 4.4.4 and 4.5.0-beta using playground

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-beta#code/C4TwDgpgBA4g9nAJgOQK4Bt0EMBG6IAq4EAPAQHxQC8UA3gFBRNQDaA0lAJYB2UA1hBBwAZlAIBdAFxRU3RBGE8IiKBAAewCHIDOY9uMbMA-HrbioAHyjcM6SzLkKliQ02kF99AL716oSFAAQlgotrj4RJBklDQMzKwcPPyCImLiALRG0rLyitzKqhpaiLoeZq5QJmXmVjaY9jlO+S7x7p4+fsRiENrA1HQV2tK9AE48AOYNjnnKFdzSNgC2OBAjFTjSOAj4WNwVwO49wBVw2llQoxMn3OdLK2vxcDjnW3A7e4-A5wRHFahDF2AY24kysjRmLWYsgWqGWqymuWcfw2UFe7wRTVm8VQB26vQxEO8vn80HgSDQmHChCO-TJoUpeEIxDIR3InQCwXp2EZP3xNE5FO5EWZvOA5CAA)

### 💻 Code

```ts
type NullableType<T> = {
    [K in keyof T]-?: undefined extends T[K]
    ? T[K] | null | undefined
    : T[K]
}
```

### 🙁 Actual behavior

Removing optional attribute from type also remove undefined from final type
(when not removing optional attribute, final type is x?: typeof x | null | undefined) 

### 🙂 Expected behavior

Removing optional attribute just removes the optional attribute and doesn't modify final type

**Comment by MartinJohns** [comment] 2021-11-18 11:38
Sounds like a duplicate of #31025.

**Comment by RyanCavanaugh** [comment] 2021-11-18 16:47
I don't see any repro here that demonstrates what you're talking about. Please provide an actionable sample that clearly demonstrates what you consider to be the bug

**Comment by KuSh** [comment] 2021-11-19 09:11
Hi @RyanCavanaugh,

Hover over BadNullableTest in the playground, you'll see that previously optional attributes are defined as `string | null` instead of `string | null | undefined`

Regards,
Nicolas

**Comment by RyanCavanaugh** [comment] 2021-11-19 16:35
Please provide an minimal/actionable sample that clearly demonstrates what you consider to be the bug, not a textual description of where to look in a long sample

**Comment by tadhgmister** [comment] 2021-11-19 22:13
@KuSh does the relatively new compiler option `exactOptionalPropertyTypes` make it behave the way you are expecting? [playground][1]

```ts
type NullableType<T> = {
    [K in keyof T]-?: undefined extends T[K]
    ? T[K] | null | undefined
    : T[K]
}

type Test = {
    req: string
    opt?: string
    canBeNull: string | undefined
}

type EQ = NullableType<Test>
//   ^?
const shouldPass: EQ = {req: "", opt: undefined, canBeNull: undefined}
```

[1]: https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true&ts=4.5.0-beta#code/FAFwngDgpgBAcgVwDZIIYCMlQCqSgHmwD4YBeGAb2BhpgG0BpGASwDsYBrKMAewDMY2ALoBaAPwAuGAlYATKHzZRZMKAA8QUOQGdBjIdVpi9DITAA+MVsiQXpchUtmGaU7PuABfYKDyCo2iBklC4wAE5QAI5SgWFsAOahPBAgkjCxCaEAxqisAEJQiCgxIHGs8XYy8oqsyl4+4NAwAKIAisFFaJg4eIQBIETAAPRDtAB6YsBZPKyB6QAWPMiyAAqo2tpSbcEUEdEwAEQHADQwySBSVY61sqc5+YU2lw41yt5AA

**Comment by KuSh** [comment] 2021-11-22 08:58
> @KuSh does the relatively new compiler option `exactOptionalPropertyTypes` make it behave the way you are expecting? It seems so. But is effectively too recent for my current project (which use TS 4.3) and also has other consequencies as we're used to set optional props as undefined. Thanks for tip I'll keep that in mind 👍

**Closed** 2023-06-08 03:40 UTC
Labels: Unactionable
