### ISSUE TITLE
Rush's node_modules structure is not resolved in vscode correctly

### ISSUE THREAD

**Issue by nfour** [microsoft/TypeScript#28689] opened 2018-11-22 06:59 UTC
- VSCode Version: 1.28.2 (or insiders)
- OS Version: Arch linux

When trying to auto-import node modules within a `rush` project, intellisense will not locate dependencies. This also results in the editor crashing or re-initializing the TS server somewhat often.

This is likely due to rush's unique node module structure, and it's unclear if this ever worked as I have only adopted rush somewhat recently.

Steps to Reproduce:

You can replicate this issue within the `web-build-tools` repo itself.

1. Open https://github.com/Microsoft/web-build-tools/blob/master/libraries/ts-command-line/src/index.ts
2. type `Colors` in the top level (from the colors module). You shouldn't be able to resolve the symbol.

eg.

```ts
const foo: Colors = {};

export {
  CommandLineAction,
  ICommandLineActionOptions
} from './CommandLineAction';
```

This also seems to correlate with the editor's TS server crashing intermittently, but its not clear how to reproduce.

Does this issue occur when all extensions are disabled?: Yes

Versions tested:
- rush v5.5.2 / v5.3.0
- node 6 / node 10
- vscode v1.28.2 / insiders
- with either of: npm, yarn or pnpm (all latest)
- has been tested on multiple linux systems

## Workaround

If you execute the below script to replace symlinks with real files:

```
mv node_modules node_modules_old
rsync node_modules_old/ node_modules/ -a --copy-links -v
```

Everything should work as expected.

There seems to be an issue with symlinks.

Related: https://github.com/Microsoft/web-build-tools/issues/955

**Comment by sheetalkamat** [comment] 2018-11-29 17:59
Do I need to do anything special apart from cloning repo, opening file and typing the statement mentioned? I followed those steps (with typescript nightly build) but that seem to work as intended. Do not see any process shutdown or crash. Let me know if I need to do something else. If possible please  share full tsserver log so we can see where things might be going south. Thanks. 

You can enable log level verbose in settigns and open and log and share tsserver and ti log or upload them using
 1. With "typescript.tsserver.log": "verbose" enabled
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. Run ```code --upload-logs``` on the command line (or ```code-insiders --upload-logs``` if using vscode insiders) and follow instructions
5. Share the log file ID

**Comment by nfour** [comment] 2018-12-03 01:15
@sheetalkamat 

To replicate, by following those steps you *should* have not have gotten the auto-import suggestion and no auto-fix bubble. Is this the case for you?

The TS Server crashing is intermittent and harder to replicate. 

I'll be sure to use that command when it happens again, as `verbose` is enabled.

**Comment by sheetalkamat** [comment] 2018-12-03 17:43
> To replicate, by following those steps you should have not have gotten the auto-import suggestion and no auto-fix bubble. Is this the case for you?
Yes that's exactly what I saw. (Used typescript@next)

**Comment by nfour** [comment] 2018-12-06 04:52
@sheetalkamat 	

Uploaded the logs when I noticed that the TS Server was hanging while trying to initialize:

`Upload successful! Log file ID: 134282124`

**Comment by sheetalkamat** [comment] 2018-12-06 16:49
@nfour Looking at the log it seems like there are lot of DirectoryWatchers being invoked. Many of them are through failed lookup locations of the sources in project. Is it possible to share the repro project? We can sign nda if needed. (send it to me in email) I would also like to discuss with you about the different directoryWatcher locations that I see and reason about them but I am not sure if your code is private so let me know if we can continue the discussion here on email thread. If email, please contact me at shkamat at microsoft dot com. Thanks.

**Comment by nfour** [comment] 2018-12-10 01:47
@sheetalkamat 	

We're looking into whether we can provide the source code.

As an alternative, do you think the `web-build-tools` monorepo is capable of reproducing these issues?

**Comment by sheetalkamat** [comment] 2018-12-12 18:15
@nfour it would be hard to figure out what might be going wrong just from logs. In past we have used source code and figured out if there is something user can do or something we can do to enhance the experience. But that comes from looking at the source code, what kind of things module resolution is looking at etc. So just source structure is not enough (since from the log it seemed module resolution played role in the directory watchers being set). Please let me know once you are ready with the repro code. Thanks.

**Comment by nfour** [comment] 2018-12-14 00:20
@sheetalkamat I think we'll be able to get you access to the source, will email!

**Comment by nfour** [comment] 2018-12-18 05:11
@sheetalkamat sent you an email requesting info to provide the NDA.

**Comment by sheetalkamat** [comment] 2018-12-18 20:32
@nfour Thanks for email. I am working on getting you the information.

**Comment by nfour** [comment] 2019-01-15 00:17
@sheetalkamat we seem to be having issues getting this NDA underway for various reasons.

Ignoring that, has anyone made progress with this issue in other rush repos at Microsoft?

We are considering a workflow which attempts to use rush for its useful tools and to use something else for linking & installing dependencies.

**Comment by nfour** [comment] 2019-01-16 01:38
@sheetalkamat 	working on that now - going to try converting our codebase to use `yarn` workspaces alongside rush, and to use rush with yarn in another scenario (some node engine incompatibilies when switching over).

That may prove that rush's `commons` dependency management strategy is where to look.

**Comment by nfour** [comment] 2019-03-28 01:23
I want to give an update:
- VSCode@1.33+ no longer spins noticeable CPU cycles with rush `5.5` and `pnpm` 
- Auto-import of arbitrary dependencies still does not work - however - those that are rush linked do indeed show up in import suggestions

**Comment by sheetalkamat** [comment] 2019-07-15 21:16
Assigning this bug till we have concrete repro steps to be able to look into this.

**Comment by norman784** [comment] 2019-07-26 22:50
I'm having the same issue, you can check my [project](https://github.com/norman784/enjin-ts) and check it out, it's under `enjin/src/log.ts` the `chalk` dependency is present and the project works when running but still vscode shows as missing module, it was working fine before converting splitting the project into multiple projects with rush.js

**Comment by sheetalkamat** [comment] 2019-07-30 18:04
@norman784 The repro you said is your configuration error. With the tsconfig in your project, the module resolution kind is `classic` and not `node` (because your target is esnext) Changing the resolution, fixes the errors. You should be able to see details on resolution step with `--traceResolution`

**Comment by norman784** [comment] 2019-08-01 12:33
thanks! feels a bit confusig all the different configurations about how to load modules.

**Comment by totomakers** [comment] 2019-09-09 08:22
Any update ?

**Comment by RDeluxe** [comment] 2019-09-11 08:53
I'm sorry, but we have a concrete repo to replicate the issue with, have we not ? 

The issue is reproductible on Microsoft own web tools :

https://github.com/Microsoft/web-build-tools

We are trying to switch to Rush + VsCode (both MS products) and we encountered this issue, which is pretty much a showstopper.

Anyway, here is a really small repo to reproduce the issue : https://github.com/RDeluxe/rush-repro-955

Simply go to libraries/dtos/src/dtos/user.ts

You will have a compiler error. Normally vscode should be able to auto import the missing decorators from class-validator

`import { IsEmail, IsString, } from 'class-validator'`

Or to autocomplete and autoimport while typing `IsE`.

**Comment by RDeluxe** [comment] 2019-09-18 12:04
Hello, any news ? Could you reproduce on your end ? Thanks !

**Comment by RDeluxe** [comment] 2019-10-09 08:12
I'm sorry to bump this again, is there anything I could do ? 

I'm not 100% confident jumping in Typescript's codebase, but if somebody could point me in the right direction I may be able to help.

**Comment by csuich2** [comment] 2020-02-10 23:09
Anyone have any workarounds here? I'm still unable to get autocomplete working with a project using Rush.

**Comment by totomakers** [comment] 2020-03-09 22:08
Hi @sheetalkamat  

Any news about this issue ?

A small repro is here: https://github.com/RDeluxe/rush-repro-955

Any project with rush + ts look like having the issue

**Comment by sheetalkamat** [comment] 2020-03-10 19:39
The repro provided has nothing to do with rush.. 
Your tsconfig.json only includes two files and hence there is not auto import suggestion. Duplicate of #28773 where in completion dont have knowledge of symbols that are not part of program
 
```
Info 86   [12:31:0.605] Project 'c:/temp/rush-repro-955/libraries/dtos/tsconfig.json' (Configured) 
Info 87   [12:31:0.605] 	Files (40)
	c:/Typescript/built/local/lib.es5.d.ts
	c:/Typescript/built/local/lib.es2015.d.ts
	c:/Typescript/built/local/lib.es2016.d.ts
	c:/Typescript/built/local/lib.es2017.d.ts
	c:/Typescript/built/local/lib.es2018.d.ts
	c:/Typescript/built/local/lib.es2019.d.ts
	c:/Typescript/built/local/lib.es2020.d.ts
	c:/Typescript/built/local/lib.esnext.d.ts
	c:/Typescript/built/local/lib.es2015.core.d.ts
	c:/Typescript/built/local/lib.es2015.collection.d.ts
	c:/Typescript/built/local/lib.es2015.generator.d.ts
	c:/Typescript/built/local/lib.es2015.iterable.d.ts
	c:/Typescript/built/local/lib.es2015.promise.d.ts
	c:/Typescript/built/local/lib.es2015.proxy.d.ts
	c:/Typescript/built/local/lib.es2015.reflect.d.ts
	c:/Typescript/built/local/lib.es2015.symbol.d.ts
	c:/Typescript/built/local/lib.es2015.symbol.wellknown.d.ts
	c:/Typescript/built/local/lib.es2016.array.include.d.ts
	c:/Typescript/built/local/lib.es2017.object.d.ts
	c:/Typescript/built/local/lib.es2017.sharedmemory.d.ts
	c:/Typescript/built/local/lib.es2017.string.d.ts
	c:/Typescript/built/local/lib.es2017.intl.d.ts
	c:/Typescript/built/local/lib.es2017.typedarrays.d.ts
	c:/Typescript/built/local/lib.es2018.asyncgenerator.d.ts
	c:/Typescript/built/local/lib.es2018.asynciterable.d.ts
	c:/Typescript/built/local/lib.es2018.intl.d.ts
	c:/Typescript/built/local/lib.es2018.promise.d.ts
	c:/Typescript/built/local/lib.es2018.regexp.d.ts
	c:/Typescript/built/local/lib.es2019.array.d.ts
	c:/Typescript/built/local/lib.es2019.object.d.ts
	c:/Typescript/built/local/lib.es2019.string.d.ts
	c:/Typescript/built/local/lib.es2019.symbol.d.ts
	c:/Typescript/built/local/lib.es2020.bigint.d.ts
	c:/Typescript/built/local/lib.es2020.promise.d.ts
	c:/Typescript/built/local/lib.es2020.string.d.ts
	c:/Typescript/built/local/lib.es2020.symbol.wellknown.d.ts
	c:/Typescript/built/local/lib.esnext.intl.d.ts
	c:/Typescript/built/local/lib.esnext.string.d.ts
	c:/temp/rush-repro-955/libraries/dtos/src/dtos/user.ts
	c:/temp/rush-repro-955/libraries/dtos/src/index.ts
```

**Comment by totomakers** [comment] 2020-03-10 20:54
Hey ! sorry for bothering you @sheetalkamat  :( 

I made a better repro here: https://github.com/totomakers/rush-example

Maybe i can give you better information for helping you.

+ sample-app is a NestJS project, fresh install. 

Normally, VScode provide me help for finding import, like the decorator `@Controller`

![ app controller ts - sample-app - Visual Studio Code](https://user-images.githubusercontent.com/284379/76358024-11ab6980-6319-11ea-88d8-b37ea3800497.jpg)

But with rush nothing happen, i (hope) is because of the `node_modules` folder is not the same as a classic node install.

Issue was provide in [Rush](https://github.com/microsoft/rushstack/issues/955), [VSCode](https://github.com/microsoft/vscode/issues/80743) and Typescript

Maybe i miss the point :'( sorry and thanks for help

**Comment by RDeluxe** [comment] 2020-03-10 21:32
Hello @sheetalkamat ! Thanks for your time.

To be thorough I updated my repo https://github.com/RDeluxe/rush-repro-955

The README should explain everything. There are 3 projects there:

* A vanille one (auto imports work)
* Rush + yarn (not working)
* Rush + pnpm (not working)

**Comment by sheetalkamat** [comment] 2020-03-10 22:18
@RDeluxe  Thank you for repro. we will investigate this.

**Comment by octogonz** [comment] 2020-03-11 04:06
Very excited for this to get some attention @sheetalkamat!  This issue has been open for a lonnnng time.

**Comment by sheetalkamat** [comment] 2020-03-13 01:07
Good news.. i have fix prototype available.. need to polish it and write some tests.. But i will get PR up soon.

**Closed** 2020-03-16 18:15 UTC
Labels: Fix Available, Scenario: Monorepos & Cross-Project References

**Comment by huntye1** [comment] 2021-08-06 02:33
still have this problem...  

> Good news.. i have fix prototype available.. need to polish it and write some tests.. But i will get PR up soon.

**Comment by dermicus-miclip** [comment] 2022-11-04 09:45
For those still searching, make sure that you have vscode installed with the WSL plugin. You must be sure that the WSL backend is used!
