### ISSUE TITLE
Writeonly<S> as a solution for the problem with React's setState() and strictNullChecks

### ISSUE THREAD

**Issue by JannesMeyer** [Microsoft/TypeScript#27521] opened 2018-10-03 09:15 UTC
## Search Terms

- setState

I found these similar issues:
#12793 (closed without a proper solution)
#13359 (quite a different use case/problem + no solution offered)

## Suggestion

My suggestion would be a new special generic `Writeonly<S>` (the opposite of `Readonly<S>`).

Like that you could write code like this:

```typescript
interface S {
    foo: number;
}

class Test extends React.Component<{}, S> {

    handleClick = () => {
        let s: Writeonly<S> = {}; // Works! With Pick<S, 'foo'> this would not be allowed

        // Protects against the following bug:
        //console.log(s.foo + 1);

        s.foo = 1;

        // Protects against the following bug. With Partial<S> this would be allowed:
        //s.foo = undefined;

        this.setState(s); // Works! With Partial<S> this would not work, because it can't assign undefined to number
    };

}
```

## Use Cases

Using React's setState() in conjunction with strictNullChecks, which still doesn't have a proper solution. Neither `Pick<S, T>` nor `Partial<S>` are very useful when strictNullChecks is enabled. Especially when you need to update properties in an if-branch.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by MartinJohns** [comment] 2018-10-03 09:51
But how would this work without emitting diffferent JS? Your property `s.foo` has the value `undefined` now, so `setState` will take that value and assign it to your state (which is not legal according to the types).

In order for this to work as you imagine it you would need to actually remove the property from the object again, so instead of just type information you need additional JavaScript that would change

```
s.foo = undefined;
s.bar = methodMayReturnUndefined();
```

to

```
delete s.foo;
s.bar = methodMayReturnUndefined();
if (s.bar === undefined)
    delete s.bar;
```

**Comment by JannesMeyer** [comment] 2018-10-03 09:56
Sorry, that line of code was only an illustration of why `Partial<S>` doesn't work for this use case.

I would never try to assign undefined.

I have edited the post above and converted that line into a comment

**Comment by JannesMeyer** [comment] 2018-10-03 10:41
I would like to add that today the code above can be achieved by lying about the type with `as`:

```ts
handleClick = () => {
   let s = {} as S;

   console.log(s.foo); // Problem: s.foo has the type number in TypeScript, but it is undefined.
   // That's why reading from Writeonly<S> should not be allowed

   s.foo = 1;
   this.setState(s);
};
```

But this is much less safe, because you could read foo and receive undefined (even though TypeScript thinks you got a number). That's why reading values should be disallowed on these objects.

**Comment by andy-ms** [comment] 2018-10-03 16:02
I think most people would prefer just `this.setState({ foo: 1 })` over creating an empty object and writing to its properties one-by-one.
#13195 is a better solution if the problem is that you want all defined properties to  be non-`undefined`.

**Comment by JannesMeyer** [comment] 2018-10-03 16:45
Yes, that's better for simple cases indeed. But it doesn't allow you to make an assignment based on a condition.

Let's say you want to update foo and bar when a condition is true, but you always want to update a and b regardless:

```ts
if (condition) {
    this.setState({ foo: 1, bar: 2 });
}
this.setState({ a: 1, b: 2 });
```

However, the problem with multiple setState() calls is that these are not guaranteed to be batched by React. (Especially in async code they are never batched)

So if you want to do it in a single setState() you need to create an object and assign them one by one:

```ts
let state = {} as S;
if (condition) {
    state.foo = 1;
    state.bar = 2;
}
state.a = 1;
state.b = 2;
this.setState(state);
```

This is the only way to do it with a single setState() call to avoid duplicate renders.

And now imagine that you are doing this in a larger application with more complex state objects/logic.

**Comment by RyanCavanaugh** [comment] 2018-10-03 18:14
Duplicate #21759 ? `Readonly` is not a special type; it's just a mapped type applying the `readonly` property

**Comment by Kovensky** [comment] 2018-10-04 01:39
@andy-ms this is usually a problem when writing `setState` in its callback form.

The following example cannot compile at all with the current type definitions:

```ts
this.setState((state, props) => {
  if (props.foo) {
    return { bar: state.bar + 1 }
  }
  return { baz: state.baz - 1 }
})
```

A workaround is to copy the value you want to preserve; adding `baz: state.baz` to the first object and `bar: state.bar` to the second object.

**Comment by JannesMeyer** [comment] 2018-10-05 11:39
@RyanCavanaugh Thanks for pointing me to the other issue. I haven't read the entire discussion yet, so I'm not sure if that would allow the creation of an empty object like this:
```ts
let s: Writeonly<S> = {}; // S has many required keys
```
I will read through that issue when I have some more time.

@Kovensky Thanks, that is another great example of why something like this is needed! That situation is exactly why I created this feature request.

**Closed** 2018-12-13 18:00 UTC
Labels: Duplicate
