### ISSUE TITLE
Infer type guard from predicate for functions accepting type guards.

### ISSUE THREAD

**Issue by Martaver** [Microsoft/TypeScript#19468] opened 2017-10-25 12:01 UTC
It would be great to avoid the ceremony of having to declare separate type guards for functions accepting a type guard as an argument.

Consider functions like `Array.filter` or `Observable.filter` being used to filter a union type with discriminant:

    type FooBar = { type: 'foo' } | { type: 'bar' };
    const isFoo = <(fb: FooBar) => fb is { type: 'foo'}>(fb => fb.type == "foo");
    const fooBar$: Observable<FooBar> = { /* ... */ };
    const foo$ = fooBar$.filter(isFoo); //We can use the type guard 'isFoo' to narrow the type to Foo.

However this is quite a lot of wiring for something that anywhere else is quite straight forward. In an if/else or switch block, a type guard isn't necessary... Typescript infers the type from the predicate:

    if(fb.type === 'foo') {
        //'fb' is { type: 'foo' }
    }

Having to declare the type guard also requires us to 'repeat' out the shape of the type which can be quite painful if it isn't a type alias or class... i.e. we have to explicitly write `fb is { type: 'foo' }. 

Typescript should be able to infer that the correct type is `{ type: 'foo' }` from the supplied predicate.

In such an ideal world, we should be able to simply write:

    const foo$ = fooBar$.filter(fb => fb.type === 'foo');

If Typescript requires us to explicitly opt-in the function as a type-guard, then it should be possible to do so without explicitly repeating the type in the declaration. Maybe something like:

    const foo$ = fooBar$.filter(<fb is>(fb => fb.type === 'foo'));

**Comment by jcalz** [comment] 2017-10-25 13:49
Duplicate of #10734 and #14891 and #5101 (with a [relevant comment](https://github.com/Microsoft/TypeScript/issues/5101#issuecomment-145693151))

**Comment by DanielRosenwasser** [comment] 2017-10-25 14:24
Thanks for finding that @jcalz

**Comment by Martaver** [comment] 2017-10-25 18:14
To clarify, I'm looking for a general solution that doesn't require explicit definition of the narrowed guard type, not just an overload to `Array.filter`...

**Closed** 2017-11-22 23:11 UTC
Labels: Duplicate
