### ISSUE TITLE
Can't use generics in class decorator

### ISSUE THREAD

**Issue by zheeeng** [Microsoft/TypeScript#19245] opened 2017-10-17 13:30 UTC
**TypeScript Version:**  2.5.3

**Code**

```ts
interface Klass {
    new (): any
}

function decorator<P>(klass: Klass) {
    return class extends klass {
        test(p: P) {
            return p
        }
    }
}

class Test {
}

const Decorated = decorator<string>(Test)

const t1 = new Decorated()

// Argument of type '123' is not assignable to parameter of type 'string'.
t1.test(123)

@decorator
class Test2 {
}

const t2 = new Test2()

// Property 'test' does not exist on type 'Test2'.
t2.test(234)

@decorator<string>
class Test3 {
}

const t3 = new Test3()

// Declaration expected.
t3.test(345)
```

**Expected behavior:**

`t1` throws the warning as expected. (The generic works fine.)
`t2` at least knows it has a `test` method, and it accepts any type param be passed to `test`.
`t2` know it has a `test` method, and it accepts only the string type as the param to `test`

**Actual behavior:**

`t2` ignores the decorator adding test method.
`t3` throws a syntax error.

**Comment by mhegazy** [comment] 2017-10-17 17:24
Duplicate of https://github.com/Microsoft/TypeScript/issues/6173

**Comment by mhegazy** [comment] 2017-10-31 17:55
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-31 17:55 UTC
Labels: Duplicate
