### ISSUE TITLE
Suggestion: partial interface inheritance, 'except' keyword 

### ISSUE THREAD

**Issue by stepancar** [Microsoft/TypeScript#8309] opened 2016-04-26 16:52 UTC
For example, we have interface
``` typescript
interface A {
   a: string;
   b: number;
   c: string;
   d: number;
   //etc
}
```
and we want interface which contains all members except ```{c: string}``` and includes
``` typescript
{
    f: number;
}
```

Ofcource we can split interface A, but, for example, this interface stored in another npm package.

Another example

``` javascript

interface BemProps {
    modifications?: Array<{
        [index: string]: boolean;
    } | string>;
    prefix?: string;
    additionalClasses?: string;
}

// we want to pass all HTMLButtonElement valid props except className
// for set className we use bem.
function UiButton(props: BemProps & React.HTMLProps<HTMLButtonElement>) {
    return (
        <button disabled className={GetBEMClassNames(props) } {...props}>
            {props.children}
        </button>
    );
}
```

I suggest new keyword 'except' or '!'

Usage

``` typescript 
type Props =  BemProps & React.HTMLProps<HTMLButtonElement> except { className: string }
```
or "!"
``` typescript
type Props =  BemProps & React.HTMLProps<HTMLButtonElement> ! { className: string }
```

**Comment by aleksey-bykov** [comment] 2016-04-26 17:10
looks like closely related https://github.com/Microsoft/TypeScript/issues/4183

**Comment by mhegazy** [comment] 2016-04-26 17:17
seems like a duplicate of #4183

**Closed** 2016-05-20 05:51 UTC
Labels: Duplicate, Suggestion
