### ISSUE TITLE
Import suggestion behaviour differs between `export =` (CommonJS/AMD) and default exports

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#25402] opened 2018-07-03 14:08 UTC
**TypeScript Version:**  2.9.2

**Search Terms:** import suggestion export default

**Code**

```ts
declare module 'foo/bar' {
    const bar = 1;
    export = bar;
}

declare module 'foo/baz' {
    const baz = 1;
    export default baz;
}

// Doesn't have import suggestions
bar;

// Does have Import suggestions
baz;
```

I think these should behave the same. The behaviour for default exports is useful and should also apply to `export =` (CommonJS/AMD)?

**Comment by andy-ms** [comment] 2018-07-03 15:09
Duplicate of #25135

**Closed** 2018-07-03 15:17 UTC
Labels: Duplicate
