### ISSUE TITLE
Array.forEach incorrectly narrows the inferred type when elements are annotated with union type

### ISSUE THREAD

**Issue by shogunsea** [microsoft/TypeScript#55201] opened 2023-07-29 22:42 UTC
# Bug Report

### 🔎 Search Terms
Array.forEach
union type 

### 🕗 Version & Regression Information
all versions

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about array and foreach

### ⏯ Playground Link

[Playground link with relevant **code](https://www.typescriptlang.org/play?ts=5.2.0-beta#code/JYOwLgpgTgZghgYwgAgGIHt0DU4BsCuKA3gFDLIBuehAXMgM5hSgDmA3CQL4kmiSyIUAIThQcBYmUrUIdRsxDspIOAFtZDJqw7de4aPCTIAClHQAHeslLkqE+nRFiZAbQC6yAD5pM4wu50eCAAPc3QoMGQYfBAEMGB0ECjMAAoiaXtkTjpTC3oASmspKAgwfCgku0J6ADoYcIBRRAALFJSqiEKAXgA+DMJ8jnIAemHkGIR0VXVwZDBmlHrcXHQAd1Y59AYIFHmUACMIZrgKBKhkdBhkGtU4c2QpUeQSsor+iFrb8zaO7r7fnRAA)**

### 💻 Code

```ts
interface FooValue {
  value: string;
}

interface BarValue {
  value: string;
  name: string;
}

interface Props {
  values: BarValue[] | FooValue[];
}

export function foo({ values }: Props) {
  return values.forEach((value) => value);
}
```

### 🙁 Actual behavior
The inferred type of `value` is simply `FooValue`:
<img width="582" alt="image" src="https://github.com/microsoft/TypeScript/assets/2238944/d400d767-6bfc-4443-a82c-9057c15c8d44">

### 🙂 Expected behavior
But really it should be `FooValue | BarValue`, which is correct when using `.map`:
<img width="645" alt="image" src="https://github.com/microsoft/TypeScript/assets/2238944/dbf985f5-4f02-441b-84ff-36d65d6564f3">

I suspect this issue happens because `forEach` isn't annotated with generic return type `U` while `map` is:
https://github.com/microsoft/TypeScript/blob/250065e55b8f2bb212cb9d19b191cfeb15184ee0/src/lib/es5.d.ts#L1235-L1246

In fact after changing `forEach` to `forEach<U>` fixes this problem locally:
<img width="569" alt="image" src="https://github.com/microsoft/TypeScript/assets/2238944/e65a57ad-7cb2-486b-ab77-207473ee8446">

**Comment by MartinJohns** [comment] 2023-07-29 22:58
Subtype reduction, working as intended.

**Comment by jcalz** [comment] 2023-07-30 00:26
Essentially a duplicate of #46449 and many others: in a perfectly sound type system, if `A extends B` then TS will sometimes reduce `A | B` to `B`. This is working as intended.  In a perfectly sound type system such types `A | B` and `B` would be identical and the reduction from the former to the latter would have no observable effect.  Unfortunately TS doesn't have a perfectly sound type system, so the operation is indeed observable and sometimes results in surprising or undesired results for users.  But it's not considered a bug.

**Comment by fatcerberus** [comment] 2023-07-30 02:13
> In a perfectly sound type system such types `A | B` and `B` would be identical and the reduction from the former to the latter would have no observable effect.

Essentially a restatement of https://github.com/microsoft/TypeScript/issues/53425#issuecomment-1479705680, fwiw
(and in case *that* isn't clear: objects are allowed to have extra properties, so writing `FooValue | BarValue` doesn't add any additional constraints compared to just `FooValue` by itself).

**Comment by shogunsea** [comment] 2023-07-31 18:17
@jcalz @fatcerberus thanks for the explanation, but why this is not an issue with `.map`? I'd expect `.map` and `.forEach` behave identically except the return value (per the language spec). 

>But it's not considered a bug

I agree in general based on typescript not being "a perfectly sound system", however this did feel like a bug in our use case: we were using https://typescript-eslint.io/ to lint the data usage based on the type information, and when a piece of data was transformed with Array#forEach it produced wrong result due to this sub type reduction behavior.

**Closed** 2023-08-03 01:31 UTC
Labels: Not a Defect
