### ISSUE TITLE
object + string

### ISSUE THREAD

**Issue by beauxq** [microsoft/TypeScript#48530] opened 2022-04-02 18:58 UTC
# Suggestion

Warn about adding an object to a string.

`{} + "a"`

I understand that it's valid JavaScript, but I think it's rare that anyone actually intends to add an object to a string.
It could be an option that's not on by default.

## 🔍 Search Terms

object plus string
object add string
object + string
promise plus string
promise add string
promise + string

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* * (can be optional)
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).
* * (Goal 1. "Statically identify constructs that are likely to be errors.")

## 📃 Motivating Example

```ts
async function get_f() {
    return "f";
}

(async function main() {
    const f = get_f();

    const oo = "oo";

    const foo = f + oo;

    console.log(foo);
})();
```

It's obvious that it's a type error where someone just forgot to `await` the promise.

## 💻 Use Cases

  What shortcomings exist with current approaches?
    The only way I can see to have typescript find this error is to explicitly specify the type of everything.
      `const f: string = get_f();`

**Comment by fatcerberus** [comment] 2022-04-02 20:24
This unfortunately seems to be by design - see https://github.com/microsoft/TypeScript/issues/2093

**Comment by Josh-Cena** [comment] 2022-04-03 00:55
FYI, there's the TS-ESLint rule: https://typescript-eslint.io/rules/no-base-to-string

**Comment by RyanCavanaugh** [comment] 2022-04-04 02:59
Effectively a duplicate of #30239 (we would presumably always align the `+` and template string literal rules).

**Closed** 2022-04-06 18:00 UTC
Labels: Duplicate
