### ISSUE TITLE
Assertion functions don't work when defined as methods

### ISSUE THREAD

**Issue by mlhaufe** [microsoft/TypeScript#36931] opened 2020-02-21 13:30 UTC
**TypeScript Version:**  

3.9.0-dev.20200220

**Search Terms:**

assertion signature

**Code**

```ts
type Constructor<T> = new (...args: any[]) => T

let str: any = 'foo'

str.toUpperCase() // str is any

function assert(condition: unknown, message: string = 'Assertion failure', ErrorConstructor: Constructor<Error> = AssertionError): asserts condition {
    if(!condition) {
        throw new ErrorConstructor(message);
    }
}

assert(typeof str == 'string')

str.toUpperCase() // str is string

class AssertionError extends Error { }

class Assertion {
    assert(condition: unknown, message: string = 'Assertion failure', ErrorConstructor: Constructor<Error> = AssertionError): asserts condition {
        if(condition) {
            throw new ErrorConstructor(message);
        }
    }
}

let azzert = new Assertion().assert

let str2: any = 'bar'

azzert(typeof str2 == 'string')  //error 2775

str2.toUpperCase() // str2 is any
```

**Expected behavior:**

Assertion functions are usable as methods of a class

**Actual behavior:**

Assertions require every name in the call target to be declared with an explicit type annotation.(2775)
'azzert' needs an explicit type annotation.

**Playground Link:**

https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200220&ssl=1&ssc=1&pln=33&pc=34#code/C4TwDgpgBAwg9gOwM7AE4FcDGw6oDwAqAfFALxQIQDuUAFAHSMCGqA5kgFxRMIgDaAXQCUZEgQCwAKCkAbCMCgpUXHiDJQA5ADM4cDVKlL6OAKphIqGEyQRaIgPT3FaKAEsk3Xgclb0CbK6I3Eg2qMC0mIgAJq7AgQhcfgDWCHBUCAA0UAC2ECFMrBBcSq4IrOoaAIIhEGHxUFpMrjLoqBAaWQCiqKi48MhoWDjKsIhKQ7h43b2oJOTVoXGI07hCKjVhHpEIMUsIUADeUlAnblq0AITbu-EiR5Knj1DAABa9NJQ0K5Zjg9i4tFy+UKQgA3MdTgBfKTQ6SSayLWigSBwLTOVBkcgaEplDRCbxGUzmWpWGx2KCOdFuDw41jeTAyBFQBa1PbfKAQAAewAgOw87IOUFhUgZTJZdSC90eCNZEWisXiiQQKTSmRyeSQBSK6NK5Sx4r2DSaLTaHSg33643+I0tf2GUx6uDmzI2bMdqDWwUWW3lhqlTxOrnO1wViDuEIDj1e7wo1HN7ttGGtgI1WrBEaesMesOFkjkCiYAC9C6z1J8XYt4nZ6DKwt58+iAEwqXgVABGLH0cKLJbCSPAEFRTcxmlpeIp9lqMygjYA7LOAKwEtCN4xwMwWUm2BxOJSN6meEBAA

**Related Issues:**

Perhaps this a design limitation per the following PR?

https://github.com/microsoft/TypeScript/pull/33622
https://github.com/microsoft/TypeScript/pull/33622#issuecomment-575301357

**Comment by RyanCavanaugh** [comment] 2020-02-21 17:28
Assertion functions always need explicit annotations. You can write this:
```
let azzert: Assertion['assert'] = new Assertion().assert;
```

**Comment by justinmchase** [comment] 2020-04-28 14:33
@RyanCavanaugh Can you explain in a little more detail? I don't understand how to resolve the issue. 

This also is failing with the same error:
```ts
import * as assert from "assert";
export function exists(value: unknown): asserts value {
  assert(value);
}

export default {
  exists
};
```

Using:
```ts
import assert from "./assert";

assert.exists(true); // error ts(2775)
```

How does the exists function not have an explicit annotation? Or what can I do to resolve it in this case.

If I just export the function as non-default and do the import as `import { exists } from "./assert"` then it works but I'd like to have them grouped on the object `assert.xyz`.

**Comment by amber-pli** [comment] 2020-05-06 06:23
I am also seeing error `ts(2775)` when using `require` instead of `import`

Following has error:
```
const assert = require('assert')
```

Following has no error
```
import assert from 'assert'
```

**Comment by mlhaufe** [comment] 2020-05-06 06:44
@justinmchase , @amber-pli 

Create a let/const/var and assign it the assert function you imported. Give that variable an explicit type like in the example provided by @RyanCavanaugh .

**Comment by justinmchase** [comment] 2020-05-06 13:48
I guess whats confusing me is that he said:

> Assertion functions always need explicit annotations

But I believe in my code the function does have an explicit type annotation, yet its not working. Are we saying there is a bug and that the variable assigned to the function needs the explicit variable?

**Comment by borisyordanov** [comment] 2020-05-06 14:42
@justinmchase The type needs to be explicit, it's not a bug
https://github.com/microsoft/TypeScript/issues/34523
https://github.com/microsoft/TypeScript/issues/34596

**Comment by justinmchase** [comment] 2020-05-07 16:42
Ok, one last time, I swear I'm not being intentionally obtuse but I think I'm homing in.

I think my confusion is because, to my understanding, this function has an explicit type:
```ts
export function exists(value: unknown): asserts value {
  assert(value);
}
```

So when you say the type needs to be explicit its boggling my mind because I don't get how it couldn't be explicit.

But now, I'm wondering if you don't mean the function's type but the type of the _argument_ needs to be explicit? As in the `value: unknown` is the issue? It needs to be non-generic and not something such as `any` or `unknown`? Is that what you mean?

**Comment by mlhaufe** [comment] 2020-05-07 18:48
@justinmchase explicitly give it a type where you imported it.

**Comment by jasonk** [comment] 2020-05-25 17:23
@justinmchase I think the part that is boggling your mind is that the message isn't clear about *what* exactly doesn't have an explicit type.  You quoted this code, which clearly does have an explicit type:
```
export function exists(value: unknown): asserts value {
  assert(value);
}
```

But when you used it, you imported it like this:
```
import assert from "./assert";

assert.exists(true); // error ts(2775)
```
The 2775 error you are getting on that line is not about `exists` needing an explicit type, it's about `assert` needing one.  You can verify this by importing exists directly:
```
import { exists } from "./assert";
exists( true ); // works without the error.
```

So the error isn't telling you about problems with exists, it's telling you that your *default export* needs to be explicitly typed:
```
const defaults: {
  exists( value: unknown ): asserts value;
} = {
  exists,
};

export default defaults;
```

It isn't entirely clear to me why that is the case, and it seems that making the error message clearer about where exactly the problem lies was [discussed and rejected](https://github.com/microsoft/TypeScript/pull/33622#pullrequestreview-294589608).

What I have found can work to avoid having to repeat the typings twice is to move the actual assertion functions into a separate file and then re-export them:
```
export * from './real-assertions';
import * as assertions from './real-assertions';
export default assertions;
```
I'm also not entirely clear on *why* this works, but it seems like it does..

**Comment by justinmchase** [comment] 2020-05-26 22:26
Ok thanks, I'll try it out!

It does seem like there is a bug in here but I'll settle for work arounds for now.

**Comment by chriskrycho** [comment] 2020-05-29 22:36
As a prime example where you would *expect* this to work, but it doesn't—in a way that seems to me at least to pretty clearly be a bug—is *namespaces*.

For backwards compatibility, Ember's types have both modern module imports and re-exports from the `Ember` namespace. So we have:

```ts
export function assert(desc: string): never;
export function assert(desc: string, test: unknown): asserts test;
```

```ts
import { assert } from '@ember/debug';
assert('this works', typeof 'hello' === 'string');
```

And we *also* re-export that on the `Ember` namespace, with a re-export like this:

```ts
import * as EmberDebugNs from '@ember/debug';

export namespace Ember {
    // ...
    const assert: typeof EmberDebugNs.assert;
    // ...
}
```
```ts
const { assert } = Ember;
assert('this FAILS', typeof 'hello' === 'string');
```

> 'assert' needs an explicit type annotation.

I understand the constraints as specified, and I'm afraid I must disagree with [the team's conclusion about this error message](https://github.com/microsoft/TypeScript/pull/33622#discussion_r330195892)—

> We discussed in the team room and agreed that the existing message is fine, so I didn't change it.

—seeing as it took me about half an hour to finally find my way to this thread and understand the problem, and another half an hour to figure out how to rewrite our DefinitelyTyped tests to continue handling this! 😅 

For the record, if anyone else is curious, this is how I'm ending up working around it for the types PR I'll be pushing up shortly:

```ts
const assertDescOnly: (desc: string) => never = Ember.assert;
const assertFull: (desc: string, test: unknown) => asserts test = Ember.assert;
```

(I'm also going to have to document that or be ready to explain it, though gladly basically none of our TS users are likely to be doing this.)

**Comment by kael-shipman** [comment] 2020-09-09 20:57
I tried to include an assertion function as part of the exports for an inner module in one of my libraries and was heartbroken to find that, while I could use it perfectly within the module, I could not use it when referencing it from outside via the module namespace. @RyanCavanaugh's answer was a godsend!! Thank you so much!

Here's what I was doing:

**Project1::src/Http.ts**
```ts
export function assertThing(thing: any): asserts thing is string {
  // ...
}
```

**Project1::src/index.ts**
```ts
import * as Http from "./Http";
// ....
export { Http, /* .... and other things .... */ }
```

**Project2::src/Functions.ts**
```ts
import { Http } from "project1";

export const handler = (thing: any) => {
  Http.assertThing(thing);
  // ....
}
```

I was getting the error in the original post because of this, and I couldn't get past it. I successfully utilized Ryan's solution by doing this:


**Project2::src/Functions.ts**
```ts
import { Http } from "project1";

const assertThing: (typeof Http)["assertThing"] = Http.assertThing;

export const handler = (thing: any) => {
  assertThing(thing);
  // ....
}
```

While a little awkward, this is a total life-saver and has allowed me to successfully use this wonderful assertion functionality without limitation. (Note that it was necessary to use the `(typeof Http)` notation because typescript complained that namespaces can't be used as types.)

Anyway, just wanted to add this for anyone who may be struggling with something similar. Thanks again for the tip, @RyanCavanaugh!

**Comment by dschnare** [comment] 2020-11-25 16:47
For what it's worth this has made the Assert library usable again when checking JavaScript with Typescript.

```
const Assert = /** @type {typeof import('assert')} */(require('assert'))
```

All the type errors reported about non-explicit types are gone (thankfully).

**Comment by leandro-manifesto** [comment] 2021-02-22 19:59
I'm using Typescript `4.1.5` and it baffles me that this error even exists and that the message is so cryptic you have no idea what's going on.

Here is a sample code:
```typescript
class StringEnum<T extends string> {
	public constructor(
		private readonly values: readonly T[],
	) { }

	public is(value: string): value is T {
		return (this.values as readonly string[]).includes(value);
	}

	public assert(value: string): asserts value is T {
		if (!this.is(value)) {
			throw new Error('invalid string enum variant');
		}
	}
}

const MyEnum = new StringEnum([
	'sample1',
]);

const value = 'sample1';

if (MyEnum.is(value)) { } // works

MyEnum.assert(value); // error
```

[TS Playground](https://www.typescriptlang.org/play?ts=4.1.5#code/MYGwhgzhAEDKAuAnAlgOwOYFFUFcC2APACrQCmAHvKagCYwRJroB80A3gLABQAkAA44ARiGTBowAPaoGiHMHgTEACm49+KAG5gq0RKTA0pIAJ7QtIHKQgAuXfsOoT0IgG0AugBpVASnbQAvtyqAsKi0MgQSuaWtjJM3rbRpOEwJJy8PHrwOIio0ErwABYRAHRJMJB2BkamcRju3iVooDg0VlFgFqTeANyqgVzBQiJikBCkiPAdXbGMGAnQYxPwMEkpzuyqPMgAZvkAhEWlEdOW3r7pajxFiBIA7tCopA+YiLfKAORo5sg00HXoMi4PBmMAoMCoeAfXpbAY8AYDbiSaTwaAAWWM2Hw0AAvI9nnA5lhgUoXKoPhAwHg+CBSABGD5eLhuGGDLjIhigrq46AUqk0+kfPps3b5DFYvBNSJJc5+fzQAD0Cugd0UAGsIEEuOLgSUlpNTt0eorlRN3kA)

From my understanding, the signature of `MyEnum.assert` should be `(this: StringEnum<'sample1'>, value: string) => asserts value is 'sample1'` and that should be enough for the control flow analysis to know that after its call `value` should be a valid variant.

Also, the fact that `.is(value)` works and `.assert(value)` doesn't adds to the confusion.

Since this is a design limitation, it should be forbidden to use `asserts` in methods in the first place.

**Comment by mlhaufe** [comment] 2021-02-22 20:03
The error goes away if you're explicit:

```ts
const MyEnum: StringEnum<string> = new StringEnum([
	'sample1',
]);
```

**Comment by leandro-manifesto** [comment] 2021-02-22 20:04
Unfortunately that defeats the purpose of the generic argument, which is to keep the valid variant types around.

**Comment by leandro-manifesto** [comment] 2021-02-22 23:47
Now I'm pretty sure #34596 is about this exact problem too.

**Comment by tyler1205** [comment] 2021-03-03 16:43
Not only will they not work as methods, but having a (your) custom function defined as an expression/assignment instead of a function declaration seems to be a big no-no. Not sure why the difference but I did spend a couple hours pulling my hair out wondering why my code/types suddenly stopped working all of the sudden. 

For example this works:
`function addHighLevelCommands<
    A, //extends { [key: string]: { cmd: any } },
    B
>(attach: A, attachTo: B): asserts attachTo is typeof attachTo & typeof attach {
    //{ [k in keyof A]: A[k]["cmd"] } {
    Object.assign(attachTo, attach);
}`

but this doesn't (and throws the "must declare explicit type annotations" error when called):
`const addHighLevelCommands = function<
    A, //extends { [key: string]: { cmd: any } },
    B
>(attach: A, attachTo: B): asserts attachTo is typeof attachTo & typeof attach {
    //{ [k in keyof A]: A[k]["cmd"] } {
    Object.assign(attachTo, attach);
}`

You can see where I commented out part of the ts code in my attempts at debugging and trying to get it to work. Just thought I'd share my experience but I apologize if this is due to any ignorance on my part. As you can tell I'm having some fun with morphing? types but I'm wondering if these changing/changed/resultant types would ultimately show up in a .d.ts file that I could print out and utilized for self-documenting an API?

**Comment by eram** [comment] 2021-03-07 14:10
this is working for me:

```
import assertMod, { fail, ok, strictEqual, deepStrictEqual, notDeepStrictEqual, throws, doesNotThrow, ifError, rejects, doesNotReject, strict } from "assert";

type AssertT = {
  fail: typeof fail,
  ok: typeof ok,
  strictEqual: typeof strictEqual,
  deepStrictEqual: typeof deepStrictEqual,
  notDeepStrictEqual: typeof notDeepStrictEqual,
  throws: typeof throws,
  doesNotThrow: typeof doesNotThrow,
  ifError: typeof ifError,
  rejects: typeof rejects,
  doesNotReject: typeof doesNotReject,
  strict: typeof strict,
} & ((value: boolean, message?: string) => void);

const assert: AssertT = assertMod;
```

now you can call without having ts(2775):

```
assert(false, "always throws");
assert.fail("always throws");
```

**Comment by georeith** [comment] 2021-03-15 16:48
```ts
type AssertsIsOneOfType = <T extends ItemClass[]>(
  item: Item,
  types: T,
  prop: string
) => void;

const assertIsOneOfType: AssertsIsOneOfType = <T extends ItemClass[]>(
  item: Item,
  types: T,
  prop: string
): asserts item is Item & { className: T[number] } => {
  if (!types.some((type) => isOfType(item, type))) {
    throw new Error(`Cannot apply ${prop} to ${item.className}`);
  }
};
```

Do I really have to define all the types of this function twice just because I want to use a generic in my assertion?

If you don't `const assertIsOneOfType: AssertsIsOneOfType` like this then I get the:
> Assertions require every name in the call target to be declared with an explicit type annotation.ts(2775)
issue. So I have to define the call signature twice?

**Comment by davidgilbertson** [comment] 2021-03-18 07:06
With the goal of being able to write `assert.exists(condition)` - after much faffing about - I've found the following combinations of named exports, default exports, consts and functions to work. Maybe useful to future travellers...

```ts
// assert1.ts
export const exists1: (condition: any, message?: string) => asserts condition = (condition, message) => {
  if (!condition) throw new Error(message || 'An error occurred');
};

export function exists2(condition: any, message?: string): asserts condition {
  if (!condition) throw new Error(message || 'An error occurred');
}
```

```ts
// elsewhere
import * as assert1 from './assert1';

assert1.exists1(something);
assert1.exists2(something);
```

Or if you don't want to `import *`, this affront to humanity:

```ts
// assert2.ts
const exists1: (condition: any, message?: string) => asserts condition = (condition, message) => {
  if (!condition) throw new Error(message || 'An error occurred');
};

function exists2(condition: any, message?: string): asserts condition {
  if (!condition) throw new Error(message || 'An error occurred');
}

const myDefault: {exists1: typeof exists1; exists2: typeof exists2} = {exists1, exists2};

export default myDefault;
```

```ts
// elsewhere
import assert2 from './assert2';

assert2.exists1(something);
assert2.exists2(something);
```

With the default export approach, IntelliJ will do auto-imports properly.

**Comment by MatthiasKunnen** [comment] 2021-03-31 17:37
What about instance functions that assert something about `this`? Are they also meant to result into errors?

```TypeScript
class Device {
    id: string;
    settingsId?: string | null;

    assertHasSettings(): asserts this is {settingsId: string} & this {
        if (this.settingsId == null) {
            throw new Error(`Device with ID ${this.id}`
                + ` does not have individual settings`);
        }
    }
}

const device = new Device();
device.id = 'hello';
device.assertHasSettings();
```

TypeScript playground: https://www.typescriptlang.org/play?strictPropertyInitialization=false&ssl=15&ssc=28&pln=1&pc=1#code/MYGwhgzhAEAiCmA3Alse0DeAoavrIBMAuaCAFwCdkA7AcwG4c8J4yybaIBJAgfhPJU60AD7RqAVxAhGTXJBYUyACUgBlVuzoQAFAEoSC+EphkAFshiXMLNh27FSlDgF9oAMmjnr2PH-wAZtA63hAAdLZanDzQALyx4lIgephy-n7mFAD2AO7i8HkAohTZFDoABggoaNA5yObQXLDQACQYoWGELuVp6ekA1NDl0ARZ8DDUWWTQZmCI6DQEyCgEEmAgpJr25XqMfdAuaYeHWMBZ1OQjSKjoCdQFcNdo+owET-CdBHHQAORm8NIsj9Xu8wkYlKoIBo7NoXkA

**Comment by btmorex** [comment] 2021-05-21 17:47
Without being too repetitive, the following works for me:

```typescript
type Assert = (condition: unknown, message?: string) => asserts condition;

const assert: Assert = (condition, message) => {
  if (!condition) {
    throw new Error(message);
  }
};

export default assert;
```

**Comment by pie6k** [comment] 2022-01-31 11:03
My use case when it breaks is with creating scoped 'logging' utility that adds prefix to save me keystrokes.

```ts
const scope = createScope("Foo");

scope.assert(false, "Nope"); // <— throws error `[Foo] Nope`
scope.log("hello"); // <— logs "[Foo] hello"
// etc.
```

Thus my asset in a way is a method and has to be. 

But I cannot use that due to mentioned TS error:

```ts
scope.assert(false, "Foo"); // TS: Assertions require every name in the call target to be declared with an explicit type annotation.
// Same for
const { assert } = scope
assert(false, "Foo");
// or
const assert = scope;
assert(false, "Foo");
```

The only way to make it work is:
```ts
const assert: (input: unknown, message: string) => asserts input = scope.assert
assert(false, "Foo"); // TS does not complain and works
```

but doing it this way (explicitly having to assign type to assert totally misses the point which is my case was - make DX of writing debugging / assert messages easier)

**Comment by atulgpt** [comment] 2022-02-06 21:52
I am also facing this issue any update when this bug will be resolved?

**Comment by WORMSS** [comment] 2022-03-17 20:36
Just throwing in my two-cents because I got struck by this annoying and very unhelpful bug wording today..

My 'branding' string code.
```ts
export type DodiAttributeCodeType = string & { _type: 'DodiAttributeCode' };

/* Delcare type to get around TS Bug */
type DodiAttributeCode = {
  guard(str: string): str is DodiAttributeCodeType;
  parse(str: string): DodiAttributeCodeType;
  assert(str: string): asserts str is DodiAttributeCodeType;
};

export const DodiAttributeCode: DodiAttributeCode = {
  guard(str: string): str is DodiAttributeCodeType {
    return !!str; /* some complex test */
  },
  assert(str: string): asserts str is DodiAttributeCodeType {
    if (!DodiAttributeCode.guard(str)) {
      throw new Error();
    }
  },
  parse(str: string): DodiAttributeCodeType {
    DodiAttributeCode.assert(str);
    return str;
  },
};
```

```ts
import { DodiAttributeCode, DodiAttributeCodeType } from '@core/types/DodiAttributeCode';

const a = 'hello';
const b: DodiAttributeCode = a; // TS error 2322, string not valid
DodiAttributeCode.assert(a);
const c: DodiAttributeCode = a; // TS loves it.. Time to do real work now.
```

**Comment by jeremy-rifkin** [comment] 2022-04-06 05:30
> Assertion functions always need explicit annotations. You can write this:
> 
> ```
> let azzert: Assertion['assert'] = new Assertion().assert;
> ```

Thanks for the clear explanation, this is a strange behavior from typescript. Got stumped by this error today.

**Comment by DeepDoge** [comment] 2023-02-01 23:26
Really strange behavior

```ts
const value: unknown = 0

const foo = (value: unknown): asserts value is number => { }
foo(value) // error
value // unknown

const foo_: typeof foo = foo
foo_(value) // ok
value // number
```

```ts
const value: unknown = 0

const foo = {
    bar(value: unknown): asserts value is number { }
}
foo.bar(value) // error
value // unknown

const foo_: typeof foo = foo
foo_.bar(value) // ok
value // number
```

**Comment by cmdruid** [comment] 2023-07-12 00:05
Also chiming in that I ran into this bug in 4.9.4. I am saddened to hear that the typescript devs believe that this behavior is somehow working as intended.

**Comment by nicolo-ribaudo** [comment] 2023-08-16 10:28
Fwiw, if `t.assertSomething(val)` reports that error, you can solve it by doing
```ts
const assertSomething: typeof t.assertSomething = t.assertSomething;

assertSomething(val);
```

so that `assertSomething` is explicitly annotated as having its own type.

**Comment by pckilgore** [comment] 2023-09-20 17:50
While I can at least understand the decision to consider this working as intended, the error message you get only makes sense after you discover the solution to the problem, which is not an ideal trait in an error message.

**Comment by incerta** [comment] 2024-02-16 19:02
I think everybody would prefer that `asserts` and `is` behave the same in the context of they definition. The current situation:

```typescript
declare function makeStruct(): {
   assert(subj: unknown): asserts subj is string
   guard(subj: unknown): subj is string
}

const struct = makeStruct()

declare const subj: unknown

// ts-error:
// "Assertions require every name in the call target to be
//  declared with an explicit type annotation. 10:1:416 typescript2775"
struct.assert(subj)

// No such problem with `guard`
if (struct.guard(subj)) {
  subj // `string` as expected
}
```

The current restriction is highly unintuitive and reduces `ts` community ability to create nice `assert` method for schema dependent parsers/validators.

For example we could have `assert` method in `zod` library structs and typeguard `unknown` data like this: 

```typescript
import z from 'zod`

declare const subject: unknown

z.string().assert(subject)

subject // `string`
```

**Closed** 2024-02-24 00:23 UTC
Labels: Design Limitation

**Comment by WORMSS** [comment] 2024-02-24 00:52
@RyanCavanaugh is there somewhere to view the 'completed' work?

**Comment by RyanCavanaugh** [comment] 2024-02-24 00:55
The bulk "Close" action doesn't let you pick which "Close" you're doing.

Design Limitations aren't supposed to be left open - it means we're not aware of any plausible way to address them.
