### ISSUE TITLE
Property definition alignment with es6 in class constructor

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/TypeScript#6549] opened 2016-01-20 16:24 UTC
Hello,

I didn't find a previous discussion about this subject.
Here is the code:
```
Class Test {
    private _test:string;
    public test:number;
    
    constructor() {
         this._test="";
         this.test=1;
         this.test2="";  // error: must be declared, but it should guess the typing is string and public
         this._test3 : string[]; // invalid for now: could be private string[]
         this.test4 : string[];  // invalid for now: could be public string[]
        private this.test5 : string[];  // invalid for now: could be public string[], but modified to private
     }
}
```

Do you plan to  support such a feature ? I mean this._test3,this.test4 and this.test5
Are you working on this.test2 to add better intellisense for both ts and js (this.test2 shows any in vscode) ?

Thanks in advance for your answers.

**Comment by vladima** [comment] 2016-01-20 18:08
duplicate of #766

**Comment by DanielRosenwasser** [comment] 2016-01-20 18:09
See also #4955.

**Closed by vladima** 2016-01-20 18:08 UTC
Labels: Duplicate

**Comment by Alphapage** [comment] 2016-01-20 18:31
Ok you learn me something every time :-)

When I try this code from #4955:
```
class Alpha {
  constructor() {
    this.size = 42; //error
  }
}
var x = new Alpha();
var y = x.size; // y: number //error
```

I get the error: property 'size' does not exist on type 'Alpha'. Am I missing a tsconfig option ?
And when using js with tsserver (vscode), then size is of type any. But in the post, it seems to be supported. Do you have the same problem in vscode for js ?

**Comment by DanielRosenwasser** [comment] 2016-01-20 19:27
We haven't released that functionality just yet. I'm not sure if there's an easy way to enable it right now to experiment. @zhengbli might have a better idea.

**Comment by zhengbli** [comment] 2016-01-20 20:13
@Alphapage are you using the latest version of typescript compiler? I tested using `typescript@next` on npm, and I didn't get the errors, even in vscode. To be specific, the version I'm using is `Version 1.8.0-dev.20160120`

**Comment by Alphapage** [comment] 2016-01-21 09:14
@zhengbli I only get one error now and the typing is applied. +1
```
class Alpha {
  constructor() {
    this.size = 42; //error : property 'size' does not exist on type 'Alpha'
  }
}
var x = new Alpha();
var y = x.size; // y: number 
```

Is it a limitation for now or can tsserver guess that this.size is public without declaration ?

**Comment by Alphapage** [comment] 2016-01-21 09:17
Sorry, nothing changes in js and in ts too, I get same errors. No typings and property declaration is needed!

**Comment by Alphapage** [comment] 2016-01-22 08:54
I tried with Version 1.8.0-dev.20160122 without success. I will open a clean issue to report the problem:#6565
