### ISSUE TITLE
TouchEvent Typing in lib.dom.d.ts

### ISSUE THREAD

**Issue by olmobrutall** [microsoft/TypeScript#23204] opened 2018-04-06 09:36 UTC
Hi TS team, 

This is how lib.dom.d.ts used to look in 2.7:

```TS
interface DocumentEventMap extends GlobalEventHandlersEventMap {
   ...
     "suspend": Event;
    "timeupdate": Event;
    "touchcancel": TouchEvent;
    "touchend": TouchEvent;
    "touchmove": TouchEvent;
    "touchstart": TouchEvent;
    "volumechange": Event;
   ...
}  
```

But in the latest lib.dom.d.ts for ts 2.8

```TS
interface DocumentEventMap extends GlobalEventHandlersEventMap {
   ...
   "suspend": Event;
    "timeupdate": Event;
    "touchcancel": Event;
    "touchend": Event;
    "touchmove": Event;
    "touchstart": Event;
    "unload": Event;
   ...
}  
```

Why TouchEvent is gone? 

Thanks in advance.

**Comment by mhegazy** [comment] 2018-04-06 16:48
Duplicate of https://github.com/Microsoft/TypeScript/issues/22565. Fixed by https://github.com/Microsoft/TSJS-lib-generator/pull/394, should be in TS 2.8.2

**Comment by sandersn** [comment] 2019-05-20 17:22
This is fixed now.

**Closed by sandersn** 2019-05-20 17:22 UTC
Labels: Bug
