### ISSUE TITLE
Type guard fails to determine non null tuple property

### ISSUE THREAD

**Issue by irdkwmnsb** [microsoft/TypeScript#59784] opened 2024-08-28 10:30 UTC
### 🔎 Search Terms

"ts2322" "tuples" "null type guard"

### 🕗 Version & Regression Information

Typescript version 5.5.4

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.0-dev.20240828#code/C4TwDgpgBAIghsCAlOA7A5hAKuaBeKAbXkSgB8pUBXAGxoBpYFoLq6BdAKE4GMB7VAGdgUAE5pMALiaIUGbLigFCqCAHcZEABQBKRqo0ltO9gG5u-ISMTClUXUoB8UAN6coHqAEsAZvfHyhAAM7Ep4BGw05BQBmIQAjKHhEbQ0Oq7unlmiEMBUoqjmWQC+mR6WtgBG0sTMjEZJYhIQplAA9G1QWADKUABMAMx9fZzFQA

### 💻 Code

```ts
type DateRangeType = [Date | null, Date | null]

const range: DateRangeType = [new Date(), new Date()];

const test = () => {
    if (range[0] === null || range[1] === null) {
        return;
    }
    const b: [Date, Date] = range; // TS 2322
}
```

### 🙁 Actual behavior

Error on line `const b: [Date, Date] = range; // TS 2322`

### 🙂 Expected behavior

Type of range would be narrowed down to `[Date, Date]`

**Comment by jcalz** [comment] 2024-08-28 11:50
Duplicate of #42384

**Closed** 2024-08-28 21:13 UTC
