### ISSUE TITLE
Reducing output for NullOrUndefined-Comparison

### ISSUE THREAD

**Issue by LeopoldLerch** [microsoft/TypeScript#40340] opened 2020-09-01 06:50 UTC
## Search Terms

void 0 null

## Suggestion

The Null-Checks in Typescript like

node?.value

produce the following JS:

`node === null || node === void 0 ? void 0 : node.value`

Wouldn´t it be more efficient in to convert it to a comparision with "`== null`" like

`node == null ? undefined : node.value`

(undefined in my suggestion can be replaced with "void 0" also)

I know, "null" can be assigned a different value in some browsers, but it is also used in the current implementation for comparison, so it should not make a difference in that case. However, using the "`== null`" comparison would result in less javascript output and therefore smaller file sizes, whereas currently, altought the typescript code is less and cleaner to read, the js-output is now bigger. Also, as there are 2 type-safe-comparisons instead of 1 non-type-safe, it might have also some impact on performance of runtime-execution (altough i don´t expect it to be noticeable in any way).

Same applies of course also to eg the "??" operator.

## Checklist

My suggestion meets these guidelines:

* [ X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ X] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by j-oliveras** [comment] 2020-09-01 11:24
This will be invalid for `document.all`:
```ts
document.all == null // true
document.all === null || document.all === undefined // false
```

You can try it in a browser console.

**Comment by LeopoldLerch** [comment] 2020-09-01 12:23
well, maybe "document.all" is an exception, but it is also deprecated. Maybe the transpiler can do an exception for that case. 

> document.all is the only falsy object accessible to JavaScript

as stated in https://developer.mozilla.org/en-US/docs/Web/API/Document/all

not even listed in w3schools anymore. In my opinion thats quite an overhead for the overall for just a single and deprecated guess

**Comment by MartinJohns** [comment] 2020-09-01 13:07
Duplicate of #34670, which was tagged "Working as Intended".

**Comment by LeopoldLerch** [comment] 2020-09-01 13:15
Okay, but even in the refered thread there is also the last comment stating, that this is a wanted behaviour of browsers to avoid using old legacy code, that is designed for REALLY old browsers. 

Maybe there is a possibility to add eg a tsconfig-setting, to switch the Null-Checks?

**Comment by MartinJohns** [comment] 2020-09-01 13:19
> Maybe there is a possibility to add eg a tsconfig-setting, to switch the Null-Checks?

Please don't litter the config with even more flags. :-(

Besides this goes against the non-goal 1.  For minification support there's #8.

**Comment by LeopoldLerch** [comment] 2020-09-01 13:23
well, okay
but is less minification in the usual sense, this is more targeting producing less code (which then gets minified)

maybe "Minifying" is the wrong description for the suggestion mentioned here, "Reducing" might be better

**Closed** 2020-09-04 18:00 UTC
Labels: Duplicate

**Comment by ajafff** [comment] 2021-01-08 21:06
For those who still want this to happen: I wrote a little transformer that hooks into the compilation and changes the output to the compact version using loose equality comparison: https://www.npmjs.com/package/ts-transform-compact-nullish-compare
