### ISSUE TITLE
`T` incorrectly inferred as `T | undefined` after guard check while inside an arrow function.

### ISSUE THREAD

**Issue by Cristy94** [microsoft/TypeScript#32618] opened 2019-07-30 08:49 UTC
**TypeScript Version:**  3.5.1

**Search Terms:** undefined inference, strict check wrong, variable undefined when has value 

**Code**
```ts
interface IGroup {
    x: number;
}

const list = [{x: 1}, {x:2}];

for(let i = 0; i <= 1; ++i) {    

    let host: IGroup | undefined = undefined;

    for(const a of list) {
        if(!host) {
            host = a;
        }
    }

    if(!host) {
        continue;
    }

    console.log(host.x); // Host correctly infered as IGroup
    [0].map(() => console.log(host.x)); // Host is now IGroup | undefined, how can it be undefined?
}
```

**Expected behavior:**
`host` type is `IGroup`  inside the arrow function.

**Actual behavior:**
`host` type is  `IGroup | undefined`

**Playground Link:** https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgJIHEoHsCuAHZAbwChkzkAPALmRBwFsAjaAbmIF9jiEsQBnMMgA2wAcgC8yANqFqyAIzsANEWoAmdgF02xGFigAKIREHAJyAAwtkZgDyT51gNRPgASiLJS5Y4IAWWAI0GNj4yAA+yDggACYQMKAQMebRcQkgSdZk3mR6hjz8gnDIWDDComAeJOQ1NjAGAIQBAlU5tTXNgpJwbO1knDWcbcD1TYGVRG01BWCgOBC95EPTvHxYxgB0QlgA5gadGxRu1gD0J8gAEuPIPFBQEAhgQgCeNiAw0EnIcHxomLh4NpSCyaDb0OB4AwGDziAB8N1W6wgW12+3Ghzcx2QZ0u1wQcBAtCwAHciaS1vQIAFScworF4okYgB+DhAA

**Comment by j-oliveras** [comment] 2019-07-30 09:04
Related to #9998 (and duplicate of a lot of issues). Typescript don't known when the lambda will be called or it will be synchronous or not.

As a workaround, save the value of `host.x` to a `const` variable before calling the map method:
```ts
interface IGroup {
    x: number;
}

const list = [{x: 1}, {x:2}];

for(let i = 0; i <= 1; ++i) { 
    let host: IGroup | undefined = undefined;   
    for(const a of list) {
        if(!host) {
            host = a;
        }
    }

    if(!host) {
        continue;
    }

    console.log(host.x); // Host correctly infered as IGroup
    const hx = host.x;
    [0].map(() => console.log(hx)); // Host can now now somehow be undefined?
}
```
[Playground](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgJIHEoHsCuAHZAbwChkzkAPALmRBwFsAjaAbmIF9jiEsQBnMMgA2wAcgC8yANqFqyAIzsANEWoAmdgF02xGFigAKIREHAJyAAwtkZgDyT51gNRPgASiLJS5Y4IAWWAI0GNj4yAA+yDggACYQMKAQMebRcQkgSdZk3mR6hjz8gnDIWDDComAeJOQ1NjAGAIQBAlU5tTXNgpJwbO1knDWcbcD1TYGVRG01BWCgOBC95EPTvHxYxgB0QlgA5gadGxRu1gD0J8gAEuPIPFBQEAhgQgCeNiAw0EnIcHxomLh4NoFMR+CjmA4URZkKQWTQbehwPAGAwecQAPhuq3WEC2u32R2OyDOl2uCDgIFoWAA7pSaWt6BAAjTmFFYvFEjEAPwcIA).

**Comment by Cristy94** [comment] 2019-07-30 09:35
But it shouldn't matter when the `lamda` is called, right? `host` will never ever be undefined when the lambda is called, even if it's called synchronously now or async 5 seconds later. 

But I assume detecting that would be a bit expensive, as you have to detect all references to host within the closure and make sure the only assignments done are done before the guard check, and all the assignments that could be done after guard check (or async) only assign variable to `T`.

**Comment by RyanCavanaugh** [comment] 2019-07-30 17:04
See #11498

**Comment by Cristy94** [comment] 2019-07-31 08:07
But in the example I given, and your "converse problem", it doesn't matter when the arrow function is called, as the variable is checked before the arrow function, and it's **never** changed after.

So, already making this not throw an error would already catch most of the uses cases:

```
let x: string | undefined = 'ok';
if (x !== undefined) {
   [1].map(() => x.toLowerCase());
}
```

I understand that this is harder to check against, even though `x` will never be undefined:
```
let x: string | undefined = 'ok';
const t = setTimeout(() => x.toLowerCase(), 100);
if (x === undefined) {
    clearTimeout(t);
}
```

My point is not necessarily about `async` or `sync` functions, but maybe `TS` could know that a variable won't be modified after a certain point (see that all references to that variable are local, and no expression using that reference changes the variable), thus knowing that "from this point on, `x` will never be undefined" ?

Is this case too trivial/limited ("X will never be changed after this point") instead of the `sync` / `async', more generic one?

**Closed** 2019-08-02 18:00 UTC
Labels: Duplicate
