### ISSUE TITLE
Support async in template methods to indicate promise return value

### ISSUE THREAD

**Issue by scottschafer** [microsoft/TypeScript#50345] opened 2022-08-17 21:59 UTC
# Suggestion

## 🔍 Search Terms

template async method

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I would like to be able to use `async` in template definitions to indicate methods that return promises.

## 📃 Motivating Example

The following code is legal:
```
interface ITest {
  myAsyncFunction(): Promise<boolean>;
}

class Test implements ITest {
    async myAsyncFunction() {
        return true;
    }
}
```
But if the language supported it, it would be more consistent and convenient to write:
```
interface ITest {
  async myAsyncFunction(): boolean;
}

```

## 💻 Use Cases

There's a clear workaround here, but I think allowing async in templates to indicate Promise return values would be more intuitive than disallowing it.

**Comment by MartinJohns** [comment] 2022-08-17 22:43
Essentially a duplicate of #47630.

**Comment by RyanCavanaugh** [comment] 2022-08-19 20:58
Our view of this is that `async` is an implementation modifier, the same way that parameter destructuring is -- from the outside, a caller has no legitimate reason to care if you wrote an async function or a regular function returning a `Promise<T>`. Type declarations in all places reflect that [non-]distinction

**Closed** 2023-06-21 01:32 UTC
Labels: Suggestion, Declined
