### ISSUE TITLE
Support explicit tsconfig.json parameter

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#4831] opened 2015-09-17 04:37 UTC
```
tsc -config tsconfig-debug.json
```

This will help when user need several build settings without separate build system.

For example:

```json
{
    "version": "0.1.0",
    "command": "tsc",
    "tasks": [
        {
            "taskName": "release",
            "args": ["-p", "."]
        },
        {
            "taskName": "tester",
            "args": ["-config", "tsconfig-debug.json"]
        }
    ]
}
```

**Comment by mhegazy** [comment] 2015-09-17 18:59
looks like a dupe of https://github.com/Microsoft/TypeScript/issues/2869

**Closed** 2015-09-17 18:59 UTC
Labels: Duplicate
