### ISSUE TITLE
Inferred type of method is wrong even though type is set explicitly by the return expression

### ISSUE THREAD

**Issue by RevealedFrom** [microsoft/TypeScript#42373] opened 2021-01-16 15:19 UTC
# Bug Report

### 🔎 Search Terms 

type inferred wrongly

### 🕗 Version & Regression Information

4.1.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBFCm0YF4YEMIE8zBgCgEoUA+GAbwFgAoGGAG3lgCdEBXOqALjFYFsAjeEwA+rMABN4AMwCWYeOJQwxk2fPEBuarTQB3NDNgQG8AA6FttGADooAC3hg8hEuUtWYMqfgCyae9ZMaBIgvITEAAzWAKxELBDssKgALABMWjRWAL4EGbQsUKxMYDDxiRlZ1NSgkEYmpkoY2LguyKSUmRCMACoyvPAgrFDORG3kWQA0MACMEXO51JVU1AjQhLYOTkyuNRAgDNZ0IADmeEwEuTAA9FcwAEpiEDBq8NYwAMqhjH2IMGkwe36UB+TxU0jkCiqVBuMAAYvsjro5McYLpwAByWCgXimGQMTgwTEgd5QJjI9EwcQgX5gECweAADxkSHAcEwpnghPkADchOjqDdbqthgQNo4zjtwHsDkdTkwAPy2Ymk5GEC4aIA)

### 💻 Code

```ts
const test = async () => {
  let result:number|undefined = undefined;
  await sleep()
    .then(() => {
      if (Math.random()>0.5) result = 42;
    });
  return result;
}

const sleep = async () => {
  setTimeout(() => {}, 1000);
}

test().then(r => console.log(r)); //runs fine, sometimes undefined, sometimes 42

// Following won't compile: 'toString' does not exist on type 'never'
/// test().then(r => console.log(r?.toString()));
```

### 🙁 Actual behavior

Return type of `test` is `Promise<undefined>`.

### 🙂 Expected behavior

Return type of `test` should be `Promise<number|undefined>`.

**Comment by arciisine** [comment] 2021-01-16 15:52
For some reason the assignment of `= undefined` seems to be what is triggering the undesired behavior.  Removing that produces the appropriate typings.

**Comment by MartinJohns** [comment] 2021-01-16 16:07
And another duplicate of #9998.

**Comment by MartinJohns** [comment] 2021-01-16 18:00
> For some reason the assignment of `= undefined` seems to be what is triggering the undesired behavior.

It's a combination of intended behavior ([reasoning explained here](https://github.com/microsoft/TypeScript/issues/8513#issuecomment-217678711)) and a design limitation (#9998). Due to #9998 TypeScript is simply not aware of the re-assignment in the closure, so according to the compiler only the `undefined` value is ever assigned to the variable.

**Closed** 2021-01-18 07:51 UTC
