### ISSUE TITLE
Destructuring never type allowed when dot notation is disallowed

### ISSUE THREAD

**Issue by richardsimko** [microsoft/TypeScript#50769] opened 2022-09-14 09:39 UTC
# Bug Report

### 🔎 Search Terms

destructuring, never

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `never`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.3.3#code/MYewdgzgLgBAZgVzMGBeGAKAlALhmAUwDcCAnNAPhgG8BYAKBiZigAtSQB3fA7gUVIdS2ANwMAvmPoNQkWHBAg81GEQCGAGwQFlMEGzJ5CJcuJhn0K9Vp009B0nkTJs581NnQ7UAl4vxFADprbUD9VjIPcC8faAAmNACQYM1Q8LJA2KgpIA)

### 💻 Code

```ts
const func = (): never => {
    throw new Error();
};

const foo: { value: { other: never } } = { value: { other: func() } };
const { test } = foo.value.other;
const test2 = foo.value.other.test;

```

### 🙁 Actual behavior

No typing error for destructuring `{test}` even though `other` has type `never`.

### 🙂 Expected behavior

Getting the same error for destructuring as dot notation.

```ts
const { test } = foo.value.other;
```

and

```ts
const test = foo.value.other.test;
```

should be equivalent statements.

**Comment by MartinJohns** [comment] 2022-09-14 09:51
Duplicate of #42999. Used search terms: `destructure never in:title`

**Closed** 2022-09-14 10:31 UTC
