### ISSUE TITLE
Crashes on module.exports.Class.prototype pattern

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#35228] opened 2019-11-20 14:39 UTC
**TypeScript Version:**  3.8.0-dev-20191119

**Search Terms:**

**Code**

```js
module.exports.MyClass = function() {
    this.x = 1
}
module.exports.MyClass.prototype = {
    a: function() {
        this.b = 2
    }
}
```

```json
{
    "compilerOptions": {
        "allowJs": true,
        "declaration": true,
        "emitDeclarationOnly": true,
        "composite": true
    }
}
```

tsc -p tsconfig.json

**Expected behavior:**
Generate the declaration

**Actual behavior:**
Crash

```
Error: Debug Failure.
    at serializeAsAlias (C:\Users\Jack\Workspace\TypeScript\lib\tsc.js:31202:41)
    at serializeSymbolWorker (C:\Users\Jack\Workspace\TypeScript\lib\tsc.js:30980:29)
    at serializeSymbol (C:\Users\Jack\Workspace\TypeScript\lib\tsc.js:30940:38)
    at C:\Users\Jack\Workspace\TypeScript\lib\tsc.js:30921:25
    at Map.forEach (<anonymous>)
    at visitSymbolTable (C:\Users\Jack\Workspace\TypeScript\lib\tsc.js:30920:33)
    at symbolTableToDeclarationStatements (C:\Users\Jack\Workspace\TypeScript\lib\tsc.js:30812:17)
    at C:\Users\Jack\Workspace\TypeScript\lib\tsc.js:29673:106
    at withContext (C:\Users\Jack\Workspace\TypeScript\lib\tsc.js:29693:37)
    at Object.symbolTableToDeclarationStatements (C:\Users\Jack\Workspace\TypeScript\lib\tsc.js:29673:28)
```

**Playground Link:** 

**Related Issues:**

**Comment by sandersn** [comment] 2020-01-09 22:37
Here is a smaller repro:

```js
module.exports.MyClass = function() {
    this.x = 1
}
module.exports.MyClass.prototype = {}
```

The problem is that isAliasableExpression only recognises classes, not constructor functions. I'll have a fix up shortly.

**Comment by sandersn** [comment] 2020-01-29 00:32
I'm going to merge #36108, which fixes the crash, but the emit is still wrong and gives incorrect compile errors.

**Comment by Jack-Works** [comment] 2020-01-30 02:16
Should it get closed? 🤔

**Comment by sandersn** [comment] 2020-01-30 17:02
Nope, we'd like to keep it open until the bad emit is fixed. The commit message auto-closed it.

**Closed** 2020-03-31 21:59 UTC
Labels: Bug
