### ISSUE TITLE
bug with never type

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#32176] opened 2019-06-29 00:30 UTC
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
function assertString (value :any) :string {
    if ( typeof value==='string' ) { return value; }
    throwError();
}

function throwError () :never {
    throw Error();
}
```

**Expected behavior:**

no warning

**Actual behavior:**

warn except do like this:

```ts
function assertString (value :string) :string {
    if ( typeof value==='string' ) { return value; }
    throw throwError();
}
```

or:

```ts
function assertString (value :string) :string {
    if ( typeof value==='string' ) { return value; }
    return throwError();
}
```

**Playground Link:** 

**Related Issues:**

**Comment by nattthebear** [comment] 2019-06-29 01:04
Duplicate of https://github.com/microsoft/TypeScript/issues/28859

**Closed** 2019-06-29 14:45 UTC
