### ISSUE TITLE
 The order of union types obtained by keyof will change

### ISSUE THREAD

**Issue by xxf1996** [microsoft/TypeScript#42102] opened 2020-12-24 10:37 UTC
# Bug Report

### 🔎 Search Terms

order of `keyof` return union type

### 🕗 Version & Regression Information

- `version`: 4.0.3

### ⏯ Playground Link

[link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgJWG0wBsSBlGKTVAcwE8AxaAWzgG8BYAKDjhkxRawGAEYAXHADOVZLQDcPPgKEiATAH5JMqHMW84wmABV6YYNtlIFSxEjABXGAEkAJpd3X9y4CzAkaYGNMWg89WxIEFgQYSS4DPgBHBwgBMK9bPikEWiR0mwS4JAcWSWKWACM0bzgAXxqoIlISAHVgHIALWKKSqqgGprIAeShXNHyB4jIAIUxsqTLe6ttGqZIAWUwQRcrlg1dA-ExrCx7dqABtAF0ahCkAYQg-EhEECDy4CogIF+Oa7Ce-le7wAciUdn19LUeDxQJBYHZUBgcHhCGtKNQ6PRghUXhxbAh3NIrAVlIIjBMVg4XpSDBU5ndaXwAO7tWhdJlwaBjKCclhbMGlM6QgkPQEvGBvD46cL7Q7HYS06HcWHgaDwZBIrC4AiDChUQIMAAiIkwCBI+IMhM5SAgEL2fBivjcnKdLBBmBYpxlGQMMFSpE2AGtTuURQYAOQAdmDwAj9v6tgjAGZY-HhQ64DhJQA3YBGzD0BP-CB53nEzyk-i+fyBUzmJUw7gwMx4dCsADSwHocAAvHAQ-QIOhdeiDVjmFAWDwW+Z+JhccAuz3+4Ph6PmhjDdiFy8Z624GMBObl32B9312jN+PgMbTeaeEA)

### 💻 Code

```ts
export interface RecallStrategyForm {
  target1: string;
  target2?: string;
  getType: string;
  inputId: string;
  templateTag: string;
  limit: {
    quota: string;
    sign: string;
    num: number;
  };
  recallWeight: number;
  recallOrder: string;
  recallBasis: number;
  recallMax: number;
  dateRange: number[];
  isCompletion: boolean;
  completionNum: number;
}

export interface RecallStrategyTable {
  id: string;
  target: string;
  rule: string;
  basis: string;
  weight: string;
  order: string;
  maxNum: number;
  isCompletion: string;
  dateRange: string;
}

export interface RecallStrategyDetail {
  id: string;
  no: number;
  itemId: string;
  itemName: string;
  totalMake: number;
  '7Make': number;
  '3Make': number;
  activeDay: number;
  cover: string;
  templateType: string;
}

type formKey = keyof RecallStrategyForm
type tableKey = keyof RecallStrategyTable
type detailKey = keyof RecallStrategyDetail
```

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/17797002/103082557-55a3fc80-4615-11eb-9b0a-07317849059f.png)
![image](https://user-images.githubusercontent.com/17797002/103082623-7c623300-4615-11eb-9d41-c66d42b2456e.png)
![image](https://user-images.githubusercontent.com/17797002/103082646-8a17b880-4615-11eb-9214-473f3d596b67.png)

We can see that the result order of one is different from the order of the other two, the other two are arranged in the order of declaration, but the middle one is not;

### 🙂 Expected behavior

I hope the order of return is in accordance with the order of declaration or a fixed way;

**Comment by andrewbranch** [comment] 2020-12-28 18:36
Duplicate of #17944

**Closed** 2020-12-31 18:00 UTC
Labels: Duplicate
