### ISSUE TITLE
TSServer holds file locks on build output, preventing 'clean'

### ISSUE THREAD

**Issue by MLoughry** [Microsoft/TypeScript#29064] opened 2018-12-17 19:21 UTC
**TypeScript Version:**  3.2.1

**Search Terms:**
tsserver, file lock, delete, clean, rimraf

**Code**

No code.

When running TSServer (as part of VSCode) with project references and an `outDir` specified (such that downstream project references reference the `.d.ts` files in the `outDir`), TSServer will sometimes hold locks on files, preventing build processes from "cleaning" the `outDir`, such as by using `rimraf`

**Expected behavior:**
Cleaning happens without error

**Actual behavior:**
`Error: EPERM: operation not permitted, unlink 'D:\vso\client-web\obj\datetime\packages'`, for example, though any of various `EPREM` errors can occur. Closing VSCode or instructing it to restart the TSServer always resolves the issue.

**Comment by MLoughry** [comment] 2018-12-17 20:18
It's not a 100% repro, so of course it's being difficult now. 😔 I'll try to get you a log.

**Comment by MLoughry** [comment] 2019-01-08 18:59
@sheetalkamat, I managed to catch a repro, and posted the logs to https://github.com/MLoughry/typescript-29064

From `tsserver.log`, the lines surrounding the time repo in `build.log`:
```
Info 35900[10:37:50.875] Starting updateGraphWorker: Project: d:/vso/client-web/obj/common/controls/tsconfig.json
Info 35901[10:38:12.762] DirectoryWatcher:: Added:: WatchInfo: d:/vso/client-web/obj/common/controls/packages 1 Project: d:/vso/client-web/obj/common/controls/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
```

`build.log`
```
[10:38:08] Using gulpfile D:\vso\client-web\gulpfile.js
[10:38:08] Starting 'build'...
[10:38:08] Starting 'determineEntrypoints'...
[10:38:08] Finished 'determineEntrypoints' after 7.55 ms
[10:38:08] Starting 'build:setup'...
[10:38:08] Starting 'build:clean'...
[10:38:08] Starting 'cop:tsconfig'...
[10:38:09] Finished 'cop:tsconfig' after 582 ms
[10:38:40] 'build:clean' errored after 32 s
[10:38:40] Error in plugin "clean"
Message:
  "errno": -4048,
  "code": "EPERM",
  "syscall": "unlink",
  "path": "D:\\vso\\client-web\\obj\\datetime",
  "stack": "Error: EPERM: operation not permitted, unlink 'D:\\vso\\client-web\\obj\\datetime'",
  "message": "EPERM: operation not permitted, unlink 'D:\\vso\\client-web\\obj\\datetime'",
  "name": "Error"
}
Details:
    domain: [object Object]
    domainThrown: true
```

**Comment by MLoughry** [comment] 2019-01-29 21:09
Pinging @sheetalkamat 

Even if this is not currently prioritized, can the `Needs more info` tag be removed, since info has been provided?

**Comment by apantea01** [comment] 2019-02-21 23:12
Experiencing the same issue

**Comment by apantea01** [comment] 2019-02-21 23:16
Is there another workaround besides restarting VS Code?

**Comment by MLoughry** [comment] 2019-02-21 23:35
Restarting just the TS Server usually fixes the issue as well.

![image](https://user-images.githubusercontent.com/20823465/53209133-5a00c800-35ee-11e9-92da-2de1ea2cf429.png)

**Comment by ljcrapo** [comment] 2019-02-22 18:18
Same issue when trying to run `npm ci` while vscode is running.

```
npm WARN prepare removing existing node_modules/ before installation
npm ERR! path <project dir>\node_modules\@types
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink '<project dir>\node_modules\@types'
npm ERR!  { Error: EPERM: operation not permitted, unlink '<project dir>\node_modules\@types'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink '<project dir>\node_modules\@types'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path: '<project dir>\\node_modules\\@types' },
npm ERR!   isOperational: true,
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'<project dir>\\node_modules\\@types\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: '<project dir>\\node_modules\\@types' }
```
it seems the TSService has a lock on the `@types` folder
**OS**
Windows

**tsc -v** 
3.2.1

**npm -v**
6.7.0

**Comment by sheetalkamat** [comment] 2019-02-27 20:30
This is duplicate of #29407 and marking as such

**Closed by sheetalkamat** 2019-02-27 20:30 UTC
Labels: Needs Investigation
