### ISSUE TITLE
Type "unknown" for the reason in Promise.catch callback in lib.es5.d.ts

### ISSUE THREAD

**Issue by etonee123x** [microsoft/TypeScript#57270] opened 2024-02-02 10:47 UTC
### ⚙ Compilation target

esnext

### ⚙ Library

lib.es5

### Missing / Incorrect Definition

[Promise.catch](https://github.com/microsoft/TypeScript/blob/main/src/lib/es5.d.ts#L1539)

### Important:
[strict mode](https://www.typescriptlang.org/tsconfig#strict) is enabled. "[useUnknownInCatchVariables](https://www.typescriptlang.org/tsconfig#useUnknownInCatchVariables)" is not disabled.

### Description
Check the sample code. It represents some fetch-request (0) and transformation of its results (1). For some reasons (inattention) I return error in Promise.catch (3).

### What do I expect?
I expect that error (4.0) type (and then data (4.1) type) will be of type "unknown" and IDE will underline spreading data at transformation (1), typechecks will fail, etc --> I will notice the error --> I will prevent the error in runtime.

### What do I get?
Error (4.0) type (and then data (4.1) type) are "any" and IDE didn't underline the error, typechecks didn't fail, etc --> I didn't notice the error --> I got TypeError in runtime, cos the error value (5) is not iterable.

### Investigation
In [other issue, where author was requesting for generic for rejected promise values](https://github.com/Microsoft/TypeScript/issues/6283), [rbuckton](https://github.com/rbuckton) [agreed](https://github.com/Microsoft/TypeScript/issues/6283#issuecomment-240804072) that type "any" is the most accurate type for rejected promises values. It was ~2-3 years before type "unknown" was introduced, though 🤔!..

### Potential solution
Of course, I can add type annotation `"error: unknown"` in catch callback on my own, but I think it should be automatically inferred with flags I mentioned before. Or maybe create a new flag for this case. Or maybe change [Promise.catch](https://github.com/microsoft/TypeScript/blob/main/src/lib/es5.d.ts#L1539) definition. Or maybe I don't understand something, please explain me!

### Sample Code

```TypeScript
// (0)
const getData = () => new Promise<Array<number>>(
  (resolve, reject) => Math.random()
    ? resolve([1, 2, 3])
    : reject(new Error('error!')), // (5)
);

(async () => {
  const data = await getData() // (4.1)
    .catch((error) => { // (4.0)
      console.log(error);
      return error; // (3)
    });

  return [0, ...data]; // (1)
})();
```

**Comment by MartinJohns** [comment] 2024-02-02 11:01
Duplicate of #45602. Used search terms: `promise catch in:title`

**Closed** 2024-02-05 01:26 UTC
Labels: Duplicate
