### ISSUE TITLE
TS can't detect correct signature from union types

### ISSUE THREAD

**Issue by marcomura** [Microsoft/TypeScript#20936] opened 2017-12-29 12:05 UTC
**TypeScript Version:**  2.6.2

**Code**

```ts
// from lib.ts
interface DateConstructor {
    new(): Date;
    new(value: number): Date;
    new(value: string): Date;
    //...
}

function toDate(dateStringOrNumber: number | string): Date {
   return dateStringOrNumber ? new Date(dateStringOrNumber) : null;
}
```

**Expected behavior:**
No errors.

**Actual behavior:**
Error	 Build: Argument of type 'string | number' is not assignable to parameter of type 'string'.

**Comment by kitsonk** [comment] 2017-12-29 12:14
Duplicate of #20900

**Comment by marcomura** [comment] 2017-12-29 12:21
I believe, in this case, that it's not just a missing new(value: number | string): Date constructor declaration (also because people can't define all possible permutations).
TS should be able to detect that there are two constructors for both number and string, therefore number | string is legit.

**Comment by kitsonk** [comment] 2017-12-29 12:39
No, I am afraid that is not how it works currently.  Your suggestion though is already covered by #7294.

**Closed** 2018-01-12 19:50 UTC
Labels: Duplicate
