### ISSUE TITLE
`useDefineForClassFields` breaks subclasses if super() has any statements before it

### ISSUE THREAD

**Issue by fregante** [microsoft/TypeScript#35426] opened 2019-11-30 08:19 UTC
The following code generates broken JavaScript code, which causes a runtime error in all browsers:

```js
new Test();
// ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
```

Notice how removing the `1;` statement before `super()` produces the expected output.

**TypeScript Version:**  3.7.2 (the dev playground fails loading for me)

**Search Terms:**

useDefinedForClassFields object defineProperty class field initializers

**Code**

```ts
class Test extends Array {
    prop: number;
    constructor() {
        1; // Any statements here break it
        super();
        this.prop = 1;
    }
}
```

**Expected behavior:**

```ts
"use strict";
class Test extends Array {
    constructor() {
        1; // Any statements here break it
        super();
        Object.defineProperty(this, "prop", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: void 0
        });
        this.prop = 1;
    }
}
```

**Actual behavior:**

```ts
"use strict";
class Test extends Array {
    constructor() {
        Object.defineProperty(this, "prop", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: void 0
        });
        1; // Any statements here break it
        super();
        this.prop = 1;
    }
}
```

**Playground Link:** 
https://www.typescriptlang.org/play/?useDefineForClassFields=true&ssl=6&ssc=43&pln=5&pc=20#code/PQKgBArgzgpgIjAZgSwHYwGIHsBOBhAGwEMooNkYCATKALjABccIYwRgAoDgY2NLAAqMKAzAwAHgxioaYAII4cRAJ5gA3hzBawABxxYd9VBAC2AIxg4A3Ju3csqEc24NcACgCU629u0BGKzBgYHlUVREiKRNpBigwAAtLVjMcGCIAazBkBh9fMCgIHUtPGzztBnjkKAA6PQMwAF4wANyAXw5WoA

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/33895 maybe

**Comment by ajafff** [comment] 2019-11-30 15:33
This is indeed a duplicate of #33895. In that other issue the property had an initializer, which caused a compiler error (that indicates the compiler cannot handle this case properly). In your example there is no such error but still the same bad code is emitted.

**Comment by sandersn** [comment] 2020-01-24 00:09
Seems like the emit should put all initialisers after `super`. As @DanielRosenwasser points out in #33895, the current emit is likely to be slightly different, so it may be easier to keep it the same when `super` is the first statement, though perhaps worth making uniform for the long run.

**Closed** 2020-01-24 22:52 UTC
Labels: Bug, Fix Available
