### ISSUE TITLE
Value declared with interface not assignable to `Record<string, unknown>`

### ISSUE THREAD

**Issue by MarkDuckworth** [microsoft/TypeScript#60677] opened 2024-12-04 18:02 UTC
### 🔎 Search Terms

"T extends Record<string, unknown>", "interface extends Record<string, unknown>", "interface not assignable to `Record<string, unknown>`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (^3.x, ^4.x, ^5.x), and I reviewed the FAQ for entries about types vs interfaces, conditional types, and unknown type

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.2&ssl=8&ssc=38&pln=8&pc=1#code/PTAEBUFMGcBcEsB2BzUsDuB7U8AmlEEBjAQwBtRoALEgBxgC5QBZAT3FftBMVxdYCShSACcAZiSKQAULE6R+HLgF5QAb1BjMmJgCNtZSD1ABfaUliiJU-kMvjJCjVp2h9mQ8bPSQEGLG5oaHhkRCRUWGwAJUgiTBFcAB44EXCAGlAAV0QAa0RMdEQAPmk4xDhuJjY7K0dQVWdtJlgRTIUTAG4fMAAxEngyaCYlBQByauEHKVGcaFB8gJIgkMQSXUM0bDkuUZi4hOSW9Kzc-MKi0dLMcoDdJj34pJTj7LyC4vruLqub0CIq9jyT6NVwtNqmLplCq4e6xR6HVIoDKvM4fVREb6+KBwcIQUCQAAell4cweB2eSJOb3OsiBAmgZNwAGUjigAKqnd6JcBFT7gfFEgi4Ulw8ms5DIznnUAAflAo1YMBmTFG+VGkOuFUgTHpjJZiOQHOpiESbBGvNUCqVXV8AEE5iRQCIYJkyLAMhN7NYFLhMDB5pgAoTiXxGQiXlLij8KmIdQzRczxUbUabBJNvRb5WrvtJc7nfMpC4XQLbcLh4AhruQ0P45rpIGQCvUi8powFkHoDEZEAKQ3MUe9ZfLFdBlVnMDNLSP1W3QFQATUppAANqjFyjAC6vaF-cjQ6to9AKrVnwPM+6fhxKDxwZ3oDDFIl3EQrBK2wUuoT+vCtpf3Mz-K3iS94JuGlI8K++7Tke44zlCATwHGerir+rCpuap7ThqvwAFZIV+KF-p6tRSJmZ4dEAA

### 💻 Code

```ts
// Testing two identical shapes: MyType and MyInterface
type MyType = { foo: boolean }
interface MyInterface { foo: boolean }

// Test assigning to Record<string, unknown>
const a: MyInterface = { foo: true };
// Fails: Type 'MyInterface' is not assignable to type 'Record<string, unknown>'
const b: Record<string, unknown> = a;

// This is fine when the declaration uses MyType
const c: MyType = { foo: true };
const d: Record<string, unknown> = c;

// Testing T extends Record<string, unknown>
type IsRecordStringUnknown<T> = T extends Record<string, unknown> ? 'yes' : 'no';
const e: IsRecordStringUnknown<MyType> = 'yes';
// Similarly, MyInterface does not extend Record<string, unknown>
const f: IsRecordStringUnknown<MyInterface> = 'no';
```

### 🙁 Actual behavior

- Type `MyInterface` is not assignable to type `Record<string, unknown>`
-  `MyInterface` does not extend `Record<string, unknown>`.

### 🙂 Expected behavior

`MyInterface` is assignable to `Record<string, unknown>`, so the following code should compile:

const a: MyInterface = { foo: true };
const b: Record<string, unknown> = a;

`MyInterface` extends `Record<string, unknown>`, so the following code should compile:

`const d: IsRecordStringUnknown<MyInterface> = 'yes';`

### Additional information about the issue

The most relevant documentation I could find related to this:

```
// Anything but primitive assignable to { [x: string]: unknown }
function f24(x: { [x: string]: unknown }) {
  x = {};
  x = { a: 5 };
  x = [1, 2, 3];
  x = 123; // Error
}
```

[source](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html)

**Comment by MartinJohns** [comment] 2024-12-04 18:10
This is working as intended. `interface` and `type` are not interchangeably.

Duplicate of #42825. See also: https://github.com/microsoft/TypeScript/issues/15300#issuecomment-332366024

**Closed** 2024-12-07 01:32 UTC
Labels: Duplicate
