### ISSUE TITLE
Type guards in nested function scope

### ISSUE THREAD

**Issue by ysulyma** [Microsoft/TypeScript#19439] opened 2017-10-24 08:25 UTC
I have some code which adds drag functionality to elements; both HTML and SVG elements are supported. Most of the dragging logic is the same for either possibility, but exactly how we mutate the node differs slightly for HTMLElements vs SVGElements. TypeScript is getting upset about the union type inside nested functions.

**TypeScript Version:**  2.5.3

**Code**

```ts
type Draggable = HTMLElement | SVGElement;

function addDragBehavior(node: Draggable) {
    // some state that will be shared no matter what type node is
    let lastX = 0,
        lastY = 0;

    // some type discrimination
    if (node instanceof HTMLElement)
        handleHtml();
    else if (node instanceof SVGElement)
        handleSvg();

    function handleHtml() {
        // do HTML-specific stuff here
        // typescript doesn't like this line
        HTMLOnlyCode(node, lastX, lastY);
    }

    function handleSvg() {
        // do SVG-specific stuff here
        // typescript doesn't like this line
        SVGOnlyCode(node, lastX, lastY);
    }
}

function HTMLOnlyCode(elt: HTMLElement, x: number, y: number) {}

function SVGOnlyCode(elt: SVGElement, x: number, y: number) {}
```

**Expected behavior:**
Since `handleHtml()` is only ever called when `node` is an instance of `HTMLElement`, the type should be narrowed from `Draggable` to `HTMLElement` within that block, and similarly for `handleSvg()`.

**Actual behavior:**
I receive the following error message:
```
example.ts(17,24): error TS2345: Argument of type 'Draggable' is not assignable to parameter of type 'HTMLElement'.
  Type 'SVGElement' is not assignable to type 'HTMLElement'.
    Property 'accessKey' is missing in type 'SVGElement'.

example.ts(23,23): error TS2345: Argument of type 'Draggable' is not assignable to parameter of type 'SVGElement'.
  Type 'HTMLElement' is not assignable to type 'SVGElement'.
    Types of property 'onclick' are incompatible.
      Type '(this: HTMLElement, ev: MouseEvent) => any' is not assignable to type '(this: SVGElement, ev: MouseEvent) => any'.
        The 'this' types of each signature are incompatible.
          Type 'SVGElement' is not assignable to type 'HTMLElement'.
```

**Comments**
I can of course get around this by writing `<SVGElement>node` over and over in the `handleSvg()` function, but that's annoying. I tried writing an inline type guard
```ts
// ...
    function handleHtml() {
        node is HTMLElement;
        HTMLOnlyCode(node);
    }

    function handleSvg() {
        node is SVGElement;
        SVGOnlyCode(node);
    }
```
but it doesn't seem like this syntax is supported. I can also do
```ts
// ...
    function handleHtml() {
        if (!assertHTML(node)) return;
        HTMLOnlyCode(node);
    }

    function handleSvg() {
        if (!assertSVG(node)) return;
        SVGOnlyCode(node);
    }
}

function assertHTML(node: Draggable): node is HTMLElement {
    return true;
}

function assertSVG(node: Draggable): node is SVGElement {
    return true;
}
```
but that's a bit kludgy, as it's now generating actual useless code.

**Comment by samao** [comment] 2017-10-24 10:49
```
type Draggable = HTMLElement | SVGAElement;

function addDragBehavior(node: Draggable) {
    if (node instanceof HTMLElement) {
         handleHtml(node)
    }else {
         handleSvg(node);
    }

    function handleHtml(node:HTMLElement) { 
        HTMLOnlyCode(node)
    }

    function handleSvg(node:SVGAElement) { 
        SVGOnlyCode(node)
    }
}

function HTMLOnlyCode(elt: HTMLElement) { }
function SVGOnlyCode(elt: SVGAElement) {}
```

**Comment by kitsonk** [comment] 2017-10-24 12:23
Duplicate of #11498

**Comment by mhegazy** [comment] 2017-11-07 17:29
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-11-07 17:29 UTC
Labels: Duplicate
