### ISSUE TITLE
Always emit comments in declaration files

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/TypeScript#21719] opened 2018-02-07 13:59 UTC
With compiler options `"declaration": true` and `"removeComments": true`, the emitted `.d.ts` is currently stripped of comments.

I'd like to propose `.d.ts` files always be emitted with comments.

Since `.d.ts` files are important for documentation purposes only, and since file-size is of no concern, I believe there is no meaningful use-case for stripping the documentation from the emitted file.

Alternatively, a new compiler option `"removeDeclarationComments"` could be introduced, and should default to `true` - in the marginal case where somebody does want an uncommented `.d.ts`, this would still be possible, although, personally, I can't think of any use-case.

Note that the current behavior leads to production build scripts, in which we need to run the compiler twice - first with `"declaration": false, "removeComments": true` for the actual code, and then again with `"declaration": true, "removeComments": false` for the `.d.ts` file.

**Comment by j-oliveras** [comment] 2018-02-07 14:01
Duplicate of #14619.

**Closed** 2018-02-22 20:41 UTC
Labels: Duplicate
