### ISSUE TITLE
downlevel emit for spread does not match ES6 spec

### ISSUE THREAD

**Issue by vladima** [Microsoft/TypeScript#4810] opened 2015-09-15 22:31 UTC
```ts
var x: number[] = undefined;
console.log([1, ...x]);
```

is compiled to
```js
var x = undefined;
console.log([1].concat(x)); // prints [1, undefined]
```

per spec it should be TypeError: [GetIterator](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-getiterator) -> [GetMethod](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-getmethod)->[GetV](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-getv) -> [ToObject](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-toobject) -> raise TypeError.

**Comment by mhegazy** [comment] 2015-09-15 22:38
looks like a dupe of #1679

**Closed** 2016-08-02 03:38 UTC
Labels: Duplicate
