### ISSUE TITLE
"Type instantiation is excessively deep and possibly infinite" even for generated non-recursive type

### ISSUE THREAD

**Issue by KSXGitHub** [microsoft/TypeScript#31619] opened 2019-05-28 16:54 UTC
**TypeScript Version:**  3.4.5

**Search Terms:**

**Code**

<pre><code>git clone <a href='https://gist.github.com/b1ddd0b8c68889622794804931c222cd.git'>https://gist.github.com/b1ddd0b8c68889622794804931c222cd.git</a> tmpdir</code>
cd tmpdir
sh test.sh</pre>

**Expected behavior:**

It should work without error

**Actual behavior:**

```
ERROR: Type instantiation is excessively deep and possibly infinite
```

**Playground Link:** 

**Related Issues:** https://github.com/microsoft/TypeScript/issues/30188#issuecomment-484499108

**Comment by fatcerberus** [comment] 2019-05-28 17:09
Yes, this is known - a conditional type that requires more than 50 steps to instantiate into a concrete type will short out to `any`, producing the exact error you’ve encountered in the process.

**Comment by KSXGitHub** [comment] 2019-05-28 17:19
> a conditional type that requires more than 50 steps to instantiate into a concrete type will short out to `any`

The problem wouldn't exist if that "50" number was configurable.

**Comment by fatcerberus** [comment] 2019-05-28 17:41
Basically a duplicate of #28663, I think?

**Comment by AnyhowStep** [comment] 2019-05-28 19:10
I had a PR to make it configurable but there's a good reason it isn't configurable. It's an implementation detail, it could change at some point so that the number doesn't make sense, or the meaning of the number becomes different

https://github.com/microsoft/TypeScript/issues/29511#issuecomment-458620791

**Comment by nattthebear** [comment] 2019-05-28 22:09
Even the GitHub syntax highlighting gave up after `N extends 222`

**Closed** 2019-05-31 20:00 UTC
Labels: Working as Intended

**Comment by taxilian** [comment] 2020-02-23 05:24
I'm seeing this error message in VSCode on lines when running "tsc" from the console (from node_modules/.bin, so same version) is succeeding; I have a case where I legitimately need the depth, though it's definitely less than 50, and I've been trying without success to get rid of the stupid message so I can work again

**Comment by taxilian** [comment] 2020-02-23 05:30
Ahh; in my case it turns out that having too many types in a file can produce the error message in VSCode on random lines elsewhere. I commented out a large block of test types and it magically solved my issue
