### ISSUE TITLE
Allow the readonly Keyword in Constructor Parameters

### ISSUE THREAD

**Issue by shockone** [Microsoft/TypeScript#9290] opened 2016-06-21 08:59 UTC
Having a class

```typescript
class Person {
    private firstName: string;
    
    constructor(firstName: string) {
        this.firstName = firstName;
    }
}
```

TypeScript allows a shorthand notation for assigning the property

```typescript
class Person {
    constructor(private firstName: string) {
    }
}
```

However, if a property has the `readonly` modifier, we cannot use this notation anymore.

```typescript
class Person {
    constructor(private readonly firstName: string) { // an error.
    }
}
```

Would it be possible to allow the syntax from the last snippet?

**Comment by aluanhaddad** [comment] 2016-06-21 12:05
This is already supported in the current dev releases and is a very nice feature.
_test.ts_
```TypeScript
class ReadonlyPropertyParameter {
    constructor(readonly parameters) {
    }
}
```
transpiled _test.js_
```JavaScript
var ReadonlyPropertyParameter = (function () {
    function ReadonlyPropertyParameter(parameters) {
        this.parameters = parameters;
    }
    return ReadonlyPropertyParameter;
}());
```

**Comment by RyanCavanaugh** [comment] 2016-06-21 17:36
Duplicate of #7590; please search before logging new issues

![image](https://cloud.githubusercontent.com/assets/6685088/16239905/f358ee50-379b-11e6-99ca-a68cc3ded331.png)

**Closed by RyanCavanaugh** 2016-06-21 17:36 UTC
