### ISSUE TITLE
Allow return type of static methods to be 'this'

### ISSUE THREAD

**Issue by irakliy81** [Microsoft/TypeScript#10361] opened 2016-08-16 01:17 UTC
Currently, as far as I know, static class methods cannot have a return type `this`. However, there are scenarios where this could be useful. Consider the example below:

```TypeScript
// setup 
// ----------------------------------------------------------------------------
interface Factory<T> {
    create(attributes: any): T;
}

class Model {
    id: string;

    constructor(row: any) {
        this.id = row.id;
    }

    static create(row: any): any {  // cannot set return type to be 'this'
        return new this(row);
    }
}

class UserModel extends Model {
    username: string;

    constructor(row: any) {
        super(row);
        this.username = row.username;
    }
}

async function fetchOne<T>(factory: Factory<T>, query: string): Promise<T> {
    const rows = await db.execute(query);
    return factory.create(rows[0]);
}

// usage
// ----------------------------------------------------------------------------
fetchOne(UserModel, 'SELECT * FROM users WHERE id = 1')
    .then((model) => {
        // would like the model to have type UserModel
        // but currently it woudl be typed as 'any'
    });
```
This is a very simplistic example - but I think it illustrates the point. Apologies if this has been discussed previously.

**Comment by yortus** [comment] 2016-08-16 05:10
Duplicate of #5863?

**Comment by irakliy81** [comment] 2016-08-16 05:31
Seems like it. Sorry didn't find it myself!

**Closed** 2016-08-16 15:53 UTC
Labels: Duplicate
