### ISSUE TITLE
ts 2.3 -> 2.4 type predicate regression

### ISSUE THREAD

**Issue by MarenkovIgor** [Microsoft/TypeScript#19676] opened 2017-11-02 06:08 UTC
**TypeScript Version:**  2.4.1

**testFindTypeGuard.ts:**

```
let el: Element;

const nodes: Node[] = [];

const result = nodes.find((n): n is HTMLFontElement => n.nodeName === "FONT");

el = result;
```
**my.d.ts:**

```
interface Array<T> {
    find<U extends T>(predicate: (value: T, index: number, obj: Array<T>) => value is U): U | undefined;
}
```

**Expected behavior:**
Compiles fine (true for ts 2.1, 2.3)

**Actual behavior:** error TS2322: Build:Type 'Node' is not assignable to type 'Element'. 
(tested with ts 2.4.1 and 2.7.0-dev.20171101)

**Comment by fictitious** [comment] 2017-11-02 13:48
[This appears to be the commit](https://github.com/Microsoft/TypeScript/commit/872e916019a1a6cd33e03c1837569d4845c54576) that changed inferred type for `find`  from `HTMLFontElement` to `Node`

**Comment by MarenkovIgor** [comment] 2017-11-02 16:35
fictitious, commit diff is too complex for me. Any suggestion, how fix the code?

**Comment by ahejlsberg** [comment] 2017-11-02 17:09
Looks like a duplicate of #17451. @andy-ms can you verify?

**Closed** 2017-11-17 17:35 UTC
Labels: Duplicate
