### ISSUE TITLE
npm link forces two imports of the same type to be compared structurally

### ISSUE THREAD

**Issue by hiroshi-cl** [Microsoft/TypeScript#14746] opened 2017-03-20 14:44 UTC
**TypeScript Version:**  2.1.4, 2.1.6, 2.2.1
 
(my environment: node 7.7.3, OS X El Capitan)

**Code**

See > https://github.com/hiroshi-cl/bug-sample-tsc-crash

**Expected behavior:**

Some compiled code / user-friendly error message

**Actual behavior:**

crash (memory leak?)

> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by sandersn** [comment] 2017-04-05 22:29
Still repros on master.

**Comment by sandersn** [comment] 2017-04-07 16:07
This appears to be two bugs. 

1. `npm link` forces the type `Either` from `import { Either } from 'monet'` to be different in `def/src/index.ts` vs `use/src/index.ts`. Normally the compiler is able to recognise that these are the same type and only create one type object. With a linked package, however, it doesn't know the types are identical so it creates two and is forced to compare them structurally.
2. monet is a monad library and the compiler can't compare these types structurally in a reasonable amount of time or space.

(1) is supposed to be fixed by #8486, I think. I will investigate why this is not the case.
(2) is a known limitation of Typescript's current semantics and architecture. See #9052 for an example.

**Comment by sandersn** [comment] 2017-04-07 16:33
Actually, this is a duplicate of #6496. The issue is actually that `npm link` causes there to be *two* definitions of monet loaded. You can see this if you pass `--traceResolution` to the compiler:

```
======== Resolving module 'monet' from '/media/nathansa/src2/src/bug-sample-tsc-crash/use/src/index.ts'. ========
...
...
======== Module name 'monet' was successfully resolved to '/media/nathansa/src2/src/bug-sample-tsc-crash/use/node_modules/monet/index.d.ts'. ========
...
...
======== Resolving module 'monet' from '/home/nathansa/.nvm/versions/node/v7.4.0/lib/node_modules/@local/def/dist/index.d.ts'. ========
...
...
======== Module name 'monet' was successfully resolved to '/home/nathansa/.nvm/versions/node/v7.4.0/lib/node_modules/monet/index.d.ts'. ========

```

The first monet is the one that `use` got from running `npm install`. The second monet is the one that `def` get from running `npm install` followed by `npm install g . monet`. So the two `Either`s are coming from two different monets. The workaround is to explicitly specify the path to use for monet when compiling def via `baseUrl` and `paths`:

```json
{
  "compilerOptions": {
      "outDir": "dist",
      "baseUrl": ".",
      "paths": {
          "monet": ["node_modules/monet"]
      }
  },
  "include": [
    "./src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

This will force both `use/index.ts` and the linked `node_modules/@local/def/index.d.ts` to resolve to `node_modules/monet` instead of the linked reference resolving to the global installation of monet.

**Closed** 2017-04-07 16:34 UTC
Labels: Bug, Duplicate

**Comment by hiroshi-cl** [comment] 2017-04-07 16:39
thanks for your investigation
