### ISSUE TITLE
Pick type can't use common key types such as string, like Omit type

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#36074] opened 2020-01-08 10:06 UTC
I'm not sure why the Pick type has the `keyof T` constraint although the Omit type doesn't have.

**TypeScript Version:**  3.7.x-dev.20200107

**Search Terms:**

**Code**

```ts
const sym = Symbol();
class C {
    p = 0;
    [sym]: '';
}
type a = Pick<C, symbol>;
type b = Omit<C, string>;
type Structural<T> = Pick<T, string | number>;
```

**Expected behavior:**
pass
```ts
type Pick<T, K extends string | number | symbol> = { [P in Extract<keyof T, K>]: T[P]; };
type Omit<T, K extends string | number | symbol> = { [P in Exclude<keyof T, K>]: T[P]; }
```
**Actual behavior:**
Type 'symbol' does not satisfy the constraint 'unique symbol | "p"'.(2344)
Type 'string | number' does not satisfy the constraint 'keyof T'.
  Type 'string' is not assignable to type 'keyof T'.(2344)
```ts
type Pick<T, K extends keyof T> = { [P in K]: T[P]; }
type Omit<T, K extends string | number | symbol> = { [P in Exclude<keyof T, K>]: T[P]; };
```
**Playground Link:** http://www.typescriptlang.org/play/index.html?ts=3.8.0-dev.20200107#code/MYewdgzgLgBBCeBbGBeGBlJAjEAbAFAJQDcAUMLgIYQQwDCMA3qTKzAA6owAMZbMAbQSIAugC4YAcklkAvqSjx2AUxiUuABQCWwANYAeOgBo42PAD4yilTCxcA8oi1RDJ6ACctYAOaWFS1XQodwBXYCgQ90pcfQAVc00dA1i3YK9vGAAfGDAQxCxld0sgA

**Related Issues:**

**Comment by IllusionMH** [comment] 2020-01-08 16:52
Duplicate of #30825 and may other?

**Comment by falsandtru** [comment] 2020-01-08 17:17
No. That issue suggested the stricter Omit type but conversely this issue suggests the looser Pick type.

**Comment by RyanCavanaugh** [comment] 2020-01-08 23:48
We can't really change either of them after they've shipped. You're free to use your own definitions if you'd like.

**Comment by falsandtru** [comment] 2020-01-09 00:09
@RyanCavanaugh However, this change seems to make no breaking changes because this change just looses the constraint, right? I want you to answer this point.

**Comment by falsandtru** [comment] 2020-01-09 01:14
I can't find the actual problem this improvement makes.

**Comment by falsandtru** [comment] 2020-01-09 08:37
...Do you complain the same thing as that people? Eventually, the current definitions of the `Exclude` and the `Extract` have been symmetry. Asymmetric features are a basic anti-pattern. Such features are hard to use. I can't find any relevant reason to hold the `Pick` type and the `Omit` type asymmetry.

**Closed** 2020-01-13 12:00 UTC
Labels: Question
