### ISSUE TITLE
Possible issue with Array.prototype.map or disjoint unions of array types

### ISSUE THREAD

**Issue by NicholasBoll** [Microsoft/TypeScript#16339] opened 2017-06-07 21:10 UTC
`Array.prototype.map` seems to fail if given a disjoint union of different array types

**TypeScript Version:**  2.2.2 (also tried 2.3.4. Reproducible on the Playground as well)

**Code**

```ts
function map<T>(items: T[] | string[]) {
    items.map(x => x)
}
```
Also fails:
```ts
function map<T>(items: Array<T> | Array<string>) {
    items.map(x => x)
}
```

**Expected behavior:**
Maybe this should work?

**Actual behavior:**
Type Error:
```
Cannot invoke an expression whose type lacks a call signature. Type '{ <U>(this: [string, string, string, string, string], callbackfn: (value: string, index: number, ...' has no compatible call signatures.
```

**Workaround**
The following does work:
```ts
function map<T extends object | string>(items: T[]) {
  items.map(x => x)
}
```

Perhaps not a bug since a workaround exists - I don't know if the workaround would be a preferred method?

**Comment by mhegazy** [comment] 2017-06-07 22:14
Duplicate of https://github.com/Microsoft/TypeScript/issues/7294

**Comment by mhegazy** [comment] 2017-08-17 18:07
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-08-17 18:07 UTC
Labels: Duplicate
