### ISSUE TITLE
Type variable incorrect inferred as "{}

### ISSUE THREAD

**Issue by Yona-Appletree** [Microsoft/TypeScript#19381] opened 2017-10-20 19:33 UTC
**TypeScript Version:**  2.6.0-dev.201xxxxx

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

**Actual behavior:**

**Comment by andy-ms** [comment] 2017-10-20 20:11
Closing as duplicate of #19382.

**Closed by andy-ms** 2017-10-20 20:11 UTC
