### ISSUE TITLE
How should empty arrays and union types work together in 1.6?

### ISSUE THREAD

**Issue by osdm** [Microsoft/TypeScript#4499] opened 2015-08-27 19:30 UTC
```ts
var p = new Array<string>();
var q = true ? p : [];
q[0]
```

My reasoning follows, please correct me if I'm wrong.
According to 1.5 spec, type of q[0] was calculated in the following way:
1. Take union type of `Array<string>` and empty array (`Array<Undefined>`).
2. Reduce that union type, which gives us `Array<string>`, because string is a supertype of undefined.
3. Widen that type (changes nothing).
4. Type of q[0] is string.

According to 1.6 spec, type of q[0] should be calculated in the following way:
1. Take union type of `Array<string>` and empty array (`Array<Undefined>`).
2. No reduce is happening.
3. Widen that type, resulting in `(Array<string> | Array<any>)`.
4. Type of q[0] is `(string | any)`.

But that would break "no implicit any". Where did I make a mistake?

**Comment by DanielRosenwasser** [comment] 2015-08-27 20:44
@ahejlsberg, can you check into this?

**Comment by ahejlsberg** [comment] 2015-08-27 21:05
@osdm You're right, we no longer do subtype reduction in union types, however we still do deduplication as discussed in #4115. This has yet to make it into the spec. In the example above, `Array<Undefined>` is considered a duplicate of `Array<string>` so the type of the `?:` operation simply becomes `Array<string>`.

**Closed** 2015-08-27 21:05 UTC
Labels: Question
