### ISSUE TITLE
Error: Debug Failure. False expression. in 'findPrecedingToken' during 'quickinfo'

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#21799] opened 2018-02-09 01:19 UTC
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.1
**VSCode Version** 1.19.1
**command requested**: quickinfo
**hitting sessions**: 1327
**proportion of all sessions**: 0.004953840066001426
**stack**
```
Error: Debug Failure. False expression.
    at findPrecedingToken (tsserver.js:64624:18)
    at getTokenAtPositionWorker (tsserver.js:64586:41)
    at getTouchingToken (tsserver.js:64558:16)
    at Object.getTouchingPropertyName (tsserver.js:64554:16)
    at getQuickInfoAtPosition (tsserver.js:82852:27)
    at Object.getQuickInfoAtPosition (template-language-service-decorator.js:56:24)
    at IOSession.Session.getQuickInfoWorker (tsserver.js:89781:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:88934:61)
    at unknown (tsserver.js:90355:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90346:28)
    at IOSession.Session.executeCommand (tsserver.js:90355:33)
    at IOSession.Session.onMessage (tsserver.js:90375:35)
    at Interface.<anonymous> (tsserver.js:91576:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by andy-ms** [comment] 2018-02-09 18:17
@aozgaa The line numbers don't seem to match `2.7.1`, is this possibly an older or newer version?

**Comment by aozgaa** [comment] 2018-02-09 19:02
It could be an insiders build whose version starts with 2.7.1. I could try to get the exact version in the future, but requires some work. How useful would that be, on a scale from 1-10?

**Comment by mhegazy** [comment] 2018-02-09 21:33
Insider builds have different version anyways. this could either be 2.7.1 or a local build. We have changed the version in master, so moving forward we should not have this confusion.

**Comment by andy-ms** [comment] 2018-02-12 21:23
Looks like a duplicate of #20788.

**Closed by andy-ms** 2018-02-12 21:23 UTC
Labels: Bug, Source: Telemetry

**Comment by aozgaa** [comment] 2018-03-05 05:00
This issue reproduced in the following context:
**TypeScript Version Prefix**: 2.7.2
**VSCode Version** 1.21.0-insider
**command requested**: quickinfo
**hitting sessions**: 435
**proportion of all sessions**: 0.008930587776386294
**stack**
```
Error: Debug Failure. False expression.
    at findPrecedingToken (tsserver.js:64794:18)
    at getTokenAtPositionWorker (tsserver.js:64756:41)
    at getTouchingToken (tsserver.js:64728:16)
    at Object.getTouchingPropertyName (tsserver.js:64724:16)
    at getQuickInfoAtPosition (tsserver.js:83050:27)
    at Object.getQuickInfoAtPosition (template-language-service-decorator.js:59:24)
    at IOSession.Session.getQuickInfoWorker (tsserver.js:89979:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89132:61)
    at unknown (tsserver.js:90553:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90544:28)
    at IOSession.Session.executeCommand (tsserver.js:90553:33)
    at IOSession.Session.onMessage (tsserver.js:90573:35)
    at Interface.<anonymous> (tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```
