### ISSUE TITLE
Allow third-party plug-ins resolve the resolution of types.

### ISSUE THREAD

**Issue by ejmarino** [Microsoft/TypeScript#11995] opened 2016-11-02 16:11 UTC
Currently v2 of typescript is implementing npm's @types for resolution of types. Additionaly, if a npm's project have 'types' defined in its package.json, the compiler will see it too.

I think a problem (not really a problem) occurs when a project use jspm or another package manager that isn't npm. If the required project include it's typings, tsc will not find it unless I specify it manually in the tsconfig.json. Missing all the magic that is implemented for npm modules.

Allowing to jspm (or another package manager) development team (or anybody else) to build a type-resolver plugin for jspm and letting tsc use that type-resolver, every resolver can have access to the specific configuration (jspm.config.json for example) to resolve module names to files.

I hope you like the idea. Thanks!

**Comment by aluanhaddad** [comment] 2016-11-04 10:22
This is largely a duplicate of several issues.
Irregardless, I want this functionality. I think a pluggable `type-resolver`, as you have aptly called it is a very strong option.

TypeScript + jspm is my toolchain of choice by miles.

**Comment by ejmarino** [comment] 2016-11-04 12:57
I think the problem is that next year will come superpm and gets so popular that typescript start following the needs of that package manager and like this ad infinitum.

I have inconsistencies right now in the way that tsc looks for modules and systemjs do.
if I do `import * as utils from './utils'` and `utils` is a directory with an `index.ts` inside, tsc find the file without problem. But systemjs dont. and it seem logical: systemjs it's on the browser side and can not (can not?) try for every combination (./utils.js, ./utils/index.js, ./utils/package.json['main`]) ' until it hits the right one.

Ok, now I can make a types configuration with BaseUrl and Types inside of tsconfig.json, buy I'm kind of repeating the jspm/systemjs setup forced to manually update the file every time I update a package version.

I think it would be a good idea externalize resolution of types, and provide some default type-resolvers like the ones we have today.

**Comment by mhegazy** [comment] 2017-04-27 20:34
The compiler API makes the resolution process configurable.  we do not have plans to publish compiler extension/resolvers at the time being. 

JSPM module resolution is tracked by https://github.com/Microsoft/TypeScript/issues/6012

**Closed by mhegazy** 2017-04-27 20:34 UTC
