### ISSUE TITLE
Record<string, unknown> extends type but not interface

### ISSUE THREAD

**Issue by brianconnoly** [microsoft/TypeScript#45237] opened 2021-07-29 14:49 UTC
# Bug Report

### 🔎 Search Terms

Record with unknown extending type works but interface doesnt

### 🕗 Version & Regression Information

- This changed between versions 3.3 and 3.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.5#code/JYOwLgpgTgZghgYwgAgIIAdjIN4ChkHJQQCOArhAM5gBcyAShAgPZQAmAPNVKAOYA0yMiADWIZgHcQAPmQAfZADdmwNgG58hYpXTMQlCHUYt2XMDxACho8VNkLlqjQF9cuUJFiIUAcQghoYAQOVGQIAA9IEDZKNExZPEJkSGo6VBc3D2h4JGQASQAVKjBGcmKcTQI4AH46bj4NJIAjWuQQMgBbJugM3DAAT3QUAqLqUopqZABeCqSauvMGyuQWunauntxnDXdwbO9kUbA8va9cxK1SCdp8o-HixsudPQM6R3Ut3c8c4eKCwZQFwIxDKqUOdyuD2W2l0+kMShUH1cfQByD8AWIbAAjNM0f5AsEjidvt5pDsBkM8RiIGwAEy49EEjhHf5DMlAA)

### 💻 Code

```ts
interface Api {
    request: Record<string, unknown> | void;
    response: Record<string, unknown> | void;
}

interface Generic<A extends Api> {
    test: A;
}

interface ITestRequest {
    a?: string;
    b?: number;
}

type TTestRequest = {
    a?: string;
    b?: number;
};

interface TestInterface {
    request: ITestRequest;
    response: void;
}
interface TestType {
    request: TTestRequest;
    response: void;
}

// This doesnt work
type Genered1 = Generic<TestInterface>;

// But this does
type Genered2 = Generic<TestType>;
```

### 🙁 Actual behavior

ITestRequest fails to extend Record<string, unknown>

### 🙂 Expected behavior

ITestRequest works as TTestRequest and can be passed under signature Record<string, unknown>

**Comment by MartinJohns** [comment] 2021-07-29 15:00
Duplicate of #42825. Used search terms: `interface extends record unknown`

**Closed** 2021-08-07 18:00 UTC
Labels: Duplicate
