### ISSUE TITLE
Double emit of synthetic comments on class fields of decorated classes

### ISSUE THREAD

**Issue by mprobst** [microsoft/TypeScript#45817] opened 2021-09-10 15:03 UTC
# Bug Report

### 🔎 Search Terms

decorator transformer syntheticcomment emit field static

### 🕗 Version & Regression Information

- This changed between versions 4.3 and 4.4

### ⏯ Playground Link

no playground link, as this only occurs with synthetic comments (so needs a transformer)

### 💻 Code

As a unit test, in src/testRunner/unittests/transform.ts:

```ts
        testBaseline("transformSyntheticCommentOnStaticField", () => {
            return transpileModule(`
declare const Decorator: any;
@Decorator
class MyClass {
}
`, {
                transformers: {
                    before: [addStaticFieldWithComment],
                },
                compilerOptions: {
                    target: ScriptTarget.ES2015,
                    newLine: NewLineKind.CarriageReturnLineFeed,
                }
            }).outputText;

            function addStaticFieldWithComment(context: TransformationContext) {
                    return (sourceFile: SourceFile): SourceFile => {
                        return visitNode(sourceFile, rootTransform, isSourceFile);
                    };
                    function rootTransform<T extends Node>(node: T): Node {
                        if (isClassDeclaration(node)) {
                            const newMembers = [factory.createPropertyDeclaration(/* decorators */ undefined, [factory.createModifier(SyntaxKind.StaticKeyword)], "newField", /* questionOrExclamationToken */ undefined, /* type */ undefined, factory.createStringLiteral("x"))];
                            setSyntheticLeadingComments(newMembers[0], [{ kind: SyntaxKind.MultiLineCommentTrivia, text: "comment", pos: -1, end: -1, hasTrailingNewLine: true }]);
                            return factory.updateClassDeclaration(node, node.decorators, /* modifierFlags */ undefined, node.name, node.typeParameters, node.heritageClauses, newMembers);
                        }
                        return visitEachChild(node, rootTransform, context);
                    }
            }
        });

```

### 🙁 Actual behavior

```
  var MyClass = class MyClass {}
  /*comment*/
  /*comment*/
  MyClass.newField = "x";
  __decorate(MyClass, Decorator, ...)
```

### 🙂 Expected behavior

```
  var MyClass = class MyClass {}
  /*comment*/
  MyClass.newField = "x";
  __decorate(MyClass, Decorator, ...)
```

**Comment by MartinJohns** [comment] 2021-09-10 15:12
Looks like a duplicate of #45696.

**Comment by mprobst** [comment] 2021-09-10 16:30
Yes, that's right! I have to admit I didn't even search, I always assume we're the only odd people who care about the comment emit that much...

**Closed** 2021-09-10 16:30 UTC

**Comment by MartinJohns** [comment] 2021-09-10 18:23
> I have to admit I didn't even search

Yet you filled out the template section about search terms you used to try find existing bug reports. :-P

**Comment by mprobst** [comment] 2021-09-10 18:31
I filled the section with search terms I thought others might use to find
this!
