### ISSUE TITLE
Suggestion: Support type assertion on destructuring syntax

### ISSUE THREAD

**Issue by zheeeng** [Microsoft/TypeScript#18229] opened 2017-09-03 13:35 UTC
**Code**

Maybe we need a convenient way to add assertions on variables which are destructured out.

```ts
    type StringOrNumber = string | number
    
    const obj = {
      foo: 42 as StringOrNumber
    }
    
    const { foo } = obj
```

Nowadays, the workarounds are:

```ts
    // A:
    const { foo } = obj as { foo: number }

    // B:
    const { foo: foo2 } = obj

    const foo = <number>foo2
```

The first is a burden to rewrite the `obj`'s type when its type is nested and complicated. The second seems weird.

I'm assuming such a syntax like:

```ts
    const { <number>foo } = obj
```

can absolutely help us asserting the type no matter how big the `obj`'s type is.

**Comment by rozzzly** [comment] 2017-09-03 22:38
Not sure how I feel about this proposal... But I would suggest using the `as` keyword instead of the angle brackets for the type assertions.

It could look like:
```typescript
const { age as number, name as string } = person;
```
Where the type of `person` is `any`.

**Comment by zheeeng** [comment] 2017-09-04 02:15
@rozzzly Generally using `any` is better than mine, the problem is that `import` syntax has employed this keyword and has the exact same usage.

**Comment by kitsonk** [comment] 2017-09-04 09:33
This is essentially a duplicate of #1912.

**Comment by zheeeng** [comment] 2017-09-04 10:04
@kitsonk Didn't find a solution to relieve the pain point on casting type on value nested in object. May a simple workaround or a new sound syntax cloud be discussed.

**Comment by mhegazy** [comment] 2017-09-05 22:22
Please see https://github.com/Microsoft/TypeScript/issues/13471 and https://github.com/Microsoft/TypeScript/issues/7576

**Comment by andrewrothman** [comment] 2017-09-11 17:13
I understand (from this and the previous issues) that there is still room for discussion on the syntax of this operation, but I think it would be really great to have this feature, as something that a lot of developers have become accustom to.

**Comment by kitsonk** [comment] 2017-09-11 20:27
> ```
> const { name: string, age: number } = person;
> ```

That conflicts with [ES spec of assigning to new variable names when destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Assigning_to_new_variable_names).  Breaking that for everyone would result in lots of tears.  Because there is no straight forward syntax is the main reasons why the current methods are likely here to stay.

**Comment by mhegazy** [comment] 2017-09-26 16:11
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-26 16:11 UTC
Labels: Duplicate
