### ISSUE TITLE
Index signature parameter does not accept redefined valid types

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#10130] opened 2016-08-04 10:10 UTC
_From @danibishop on July 26, 2016 8:31_

- VSCode Version: 1.3.0
- OS Version: Windows 10 Pro - 64 bits

Steps to Reproduce:

1. Create an alias type for string
2. Create an index signature parameter using the new type

This makes the spellcheck fail in the parameter name for the index because "An index signature parameter type must be 'string' or 'number'"

`
var d1: { [id: string]: {}; } = {} // Spellcheck Ok

type otherString = string;

var d2: { [id: otherString]: {}; } = {} // Spellcheck complains about 'id'
`

_Copied from original issue: Microsoft/vscode#9745_

**Comment by arusakov** [comment] 2016-09-28 16:49
Same exception with enums:

```
enum X { }

type Obj = {
    [ind: X]: any // An index signature parameter type must be 'string' or 'number'.
}
```

**Comment by RyanCavanaugh** [comment] 2016-09-28 17:16
Duplicate of #1778, #7374, #8336, #5683, #2491, or #7656 depending on what you want to do.

**Closed by RyanCavanaugh** 2016-09-28 17:16 UTC
Labels: Duplicate
