### ISSUE TITLE
TS does not automatically understand object with accessor type if not extracted to a variable

### ISSUE THREAD

**Issue by aghArdeshir** [microsoft/TypeScript#46111] opened 2021-09-28 11:04 UTC
# Bug Report

### 🔎 Search Terms
extract to variable accessor, accessor automatically infer

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I searched the FAQ page for `].`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.3#code/C4TwDgpgBAKg+geQEYCsIGNhQLxQN4BQUxUwAFhANIQgBcUAzsAE4CWAdgOYDcBAvrwKhIsOAFkQMcNFzxkaTFAA+jFhx4ECAMwCu7TKwD27KKwYBJYPIzAAFERIcwO4PXgSpkAgEp6Tl6YMotaKhCRQzBDAOswmAIRxtv5YAIZBcqg23gB05FQ0vHya6MZMUAC2IABqKWwpSAA2EPR4UADaANY09ExsXAC6buKS0lB8OA7EAPRTAALADAC0rJzshpGTjIblEGSGAO4A4lEAyttRZOq23oK6+sBGJpUAYnoGxgDqrOQAoszM602ti6dFUfU43nwm1YWigSQsVkymFslRqdUaEE6NH63khYXCJBK7AYhia2Qahk4tgA5N9AlBDEjgNSbptwpForEKtVaqx6k0sSB+rkKNQQLxwkVNhyYk8eeiBSD+oVNHd3nKag1WAATV73R5AkE9NRcPGbIllCAADxYKUwEG1aL5GJw3Kd-MxSoljlh8MsITs1tt9sdvI9uKhBMJpVJEHJlJpdLMDKZLO9UZlXKDzDtwAd7oxIvy4s2UvZUVlbrDGMFyv4QA)

### 💻 Code

```ts
type T_Object = {
    theKey: string;
};

type T_MyType = T_Object | string;

function isItObject(
    input: T_MyType
): input is T_Object {
    return !!(input as T_Object).theKey;
}

const myVariable: { [key: string]: T_MyType } =
    //@ts-ignore
    somehowGetSomething();

function myFunctionWithError
    (key: string) {
    if (isItObject(myVariable[key])) {
        console.log('it is object');
        return myVariable[key].theKey;
    }

    return myVariable[key];
}

function myValidFunction
    (key: string) {
    const extractedVariable = myVariable[key];
    if (isItObject(extractedVariable)) {
        console.log('it is object');
        return extractedVariable.theKey;
    }

    return myVariable[key];
}
```

### 🙁 Actual behavior
There are two functions at the bottom of the code. The only difference is that in second case, I extracted `myVariable[key]` to a variable and used that in if condition and return value. In first function it gives me error, but in the second one (extracted variable) it doesn't.

### 🙂 Expected behavior

I expected TypeScript to automatically infer `myVariable[key]` is an object inside the `if` condition with `isItObject(myVariable[key])`

**Comment by IllusionMH** [comment] 2021-09-28 12:20
Looks like duplicate of #44899 which considered duplicate of #10530 (that accumulated a lot of different cases in comments)

**Comment by a-tarasyuk** [comment] 2021-09-28 16:12
I think this PR https://github.com/microsoft/TypeScript/pull/45974 will handle this case. [Playground](https://www.staging-typescript.org/play?ts=4.5.0-pr-45974-3#code/C4TwDgpgBAKg+geQEYCsIGNhQLxQN4BQUxUwAFhANIQgBcUAzsAE4CWAdgOYDcBAvrwKhIsOAFkQMcNFzxkaTFAA+jFhx4ECAMwCu7TKwD27KKwYBJYPIzAAFERIcwO4PXgSpkAgEp6Tl6YMotaKhCRQzBDAOswmAIRxtv5YAIZBcqg23gB05FQ0vHya6MZMUAC2IABqKWwpSAA2EPR4UADaANY09ExsXAC6buKS0lB8OA7EAPRTAALADAC0rJzshpGTjIblEGSGAO4A4lEAyttRZOq23oK6+sBGJpUAYnoGxgDqrOQAoszM602ti6dFUfU43nwm1YWigSQsVkymFslRqdUaEE6NH63khYXCJBK7AYhia2Qahk4tgA5N9AlBDEjgNSbptwpForEKtVaqx6k0sSB+rkKNQQNwoDMwepNkVNhyYk8eeiBSD+oVNHd3kqag1WAATV73R5AkE9NRcPGbIllCAADxYKUwEH1aL5GJw3Ld-Mxat44RhcLMlhCdntjudrt5PtxUIJhNKpIg5MpNLpZgZTJZ-vjESiiqg4eYTuALu9GJF+XFkqm0q4ss07PzXNR0YxgvV-CAA)

**Comment by aghArdeshir** [comment] 2021-09-28 17:50
Yes @a-tarasyuk . That would cover this case. Nice 👍

**Comment by aghArdeshir** [comment] 2021-09-28 18:01
Yes @IllusionMH those two iseues seem like to be a better way of expressing what I wanted. Thanks. 👍

I think this issue can/should be closed.

**Comment by IllusionMH** [comment] 2021-09-28 19:32
@a-tarasyuk great work as always!

However is it safe to do this case if `myVariable[key]` might not return same value between calls?
With intermediate constant you can be sure that constant isn't changed between `if` and usage but not with property access.

**Closed** 2021-10-01 18:00 UTC
Labels: Duplicate
