### ISSUE TITLE
Typescript is incorrect inferring the type.

### ISSUE THREAD

**Issue by hitrop** [microsoft/TypeScript#46083] opened 2021-09-27 09:15 UTC
# Bug Report

### 🔎 Search Terms

type narrowing inference incorrect bug

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

https://www.typescriptlang.org/dev/bug-workbench/?#code/JYOwLgpgTgZghgYwgAgFrIN4Chm+SOAWwgC5kBnMKUAc2QB98BXQgI2gG4sBfLLBAPYhKyGMgC8yABQAvMqgCUEgHyYceGQDoCxCcgBMABkNduXLABsIYZHLR7sefEVIGAND3NadKSQHJ9P3MYWQVzQWEbABM9bxdwoXIBK00LARopKM0wAQBVAAd86ABhOHIIKQUwoA

### 💻 Code
```ts
interface Z {
    name: string | number;
}

const f = (z: Z) => {
    z.name = 200;
};

let z: Z = {
    name: 2,
};

z.name = '2';

f(z);

const d = z.name;

console.log(d.toUpperCase());
```

### 🙁 Actual behavior

Here typescript incorrectly infers the type of variable d to be `string`. The above code shows no compile error, however results in a runtime error, since variable d is actually a `number`. 

### 🙂 Expected behavior

The type narrowing due to assignments should be more accurate and bullet proof (Or there should be tsconfig variable to opt out of type narrowing due to assignments of properties).

**Comment by IllusionMH** [comment] 2021-09-27 09:53
Duplicate of #9998

**Closed** 2021-10-03 18:00 UTC
Labels: Duplicate
