### ISSUE TITLE
Typescript 4.8.4: Different type inference on two `if` branches with (fundamentally) identical input

### ISSUE THREAD

**Issue by HynekS** [microsoft/TypeScript#52917] opened 2023-02-22 17:59 UTC
# Bug Report

### 🕗 Version & Regression Information

- This changed between versions 4.7.4 and 4.8.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4#code/JYWwDg9gTgLgBAbwFBzgYQBbADYBMoCmAdgDQpwDG2ERBAotgSMTGagEoECGFMDTLNnGABnAGpdswXP2ZFWSAL5wAZlAgg4AIkI8YWgNxIkMAJ5gCcACoERMAArqwIuAF5E5KlxEiAcl2YAfgAuODsoYCIAcyNlADI4ACkAZQANADoASXkIohFgClkWEQBtLVxgADctAF0jJAIAD0hYSho7a1t4dwAKZFQKLDxCUiVQmztHCGcASjcAPg9UQhgAVygiOB7yVAAeCsr5ndRETBx8YnSQLjAewfORki2CRjkYOddF-pOf4BUt0QSKQyV4sHovATyOZxBIAWS4MAw6SgXCIuA0PTmiwADOkAKxzb4-H4UdrwMBOFzuCFvdIU6YuAA+jMQiiMxOJK3WmyoNHooPk4IF8G8cE4eiK8ieRI5J3S8vpziEspOXh8-mYoQABiINAQ0NhvH4ApYACQIRUidJq43MRRa5WyxQzdlO46-f49QGSaSSmBCyHvOAwuDwxHI1HokCYuC7OC4glLFVtPLkyluOA0lh09PM1mulVcjaUai0P0Bt5wUXi3h+6Xu2XynMMx0qm0agja3XMA1Gjtwc2W62G9Um+2t4nOguThvLAhrYtZ+TT1DOxTHXYAegOR1QLqUBiAA)

### 💻 Code

```ts
import {
  Children,
  cloneElement,
  ReactElement,
  isValidElement,
} from "react";

type TestProps = {
  className?: string;
} & JSX.IntrinsicElements["div"];

export const Test = ({
  children,
}: TestProps) => {
  return (
    <div>
      {Children.map(children, (element) => {
        if (isValidElement(element) && Math.random() > 0.5) {
          const props = element.props || {};
          return cloneElement(element as ReactElement, {
            ...props,
            className: `someClassName ${props.className}`,
          });
        }
        if (isValidElement(element) && Math.random() < 0.5) {
          const props = element.props || {};
          return cloneElement(element as ReactElement, {
            ...props,
            className: `someClassName ${props.className}`,
          });
        }
        return element;
      })}
    </div>
  );
};
```

### 🙁 Actual behavior

The two `if` branches give different TS output (type inference & errors) with the same input (*fundamentally* same input; if identical input was used, the branching would not make sense. Demonstrating with `Math.random()`).

This behavior first appears in the TS playground in version 4.8.4. My project, where I ran into this issue, is also on v4.8.4. It seems to work as expected in earlier version 4.7.4.

![ts-error](https://user-images.githubusercontent.com/24924967/220706524-56e25c6a-7f57-4436-b60d-dd9a421c7ed9.png)

### 🙂 Expected behavior

The inferred types and errors will be identical in both branches with (fundamentally) identical input.

**Comment by RyanCavanaugh** [comment] 2023-02-22 19:00
Duplicate of #52232

**Closed** 2023-02-25 18:00 UTC
Labels: Duplicate
