### ISSUE TITLE
Incorrect function parameters accepted for interface with overloads

### ISSUE THREAD

**Issue by jtbandes** [microsoft/TypeScript#44441] opened 2021-06-04 18:24 UTC
# Bug Report

A function which does not satisfy an interface (its parameter types are too restrictive) is still accepted as conforming to the interface.

### 🔎 Search Terms

interface overload satisfied by function with parameter intersection where union is expected

### 🕗 Version & Regression Information
- This changed between versions 3.5.1 and 3.6.2 — In 3.5.1 the strange `data` parameter type was not accepted, but the `x: "a" & "b"` parameter was still accepted.

### 💻 Code
[Playground link](https://www.typescriptlang.org/play?strict=true#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIyYAUcAXMgERyUA0yAJnGOcsQPoUgCuAtgEbQAlMgC8APmQA3dMAZCKMuQG58hEvwqV+dRs1YcKAZzBRQAcxETps+YtuqAvrlwxuIBGGDoQycxDAMdGIFNEwcNSgA7ihfPAICInQKYgAPLRpkADIqHXomFgp+YHNQMGzkEzMQSzFJeISCAHom5AB3ZgB+NQJnXtxnIA)

```ts
interface Foo {
  foo(a: "a", data: (_: number) => void): void;
  foo(b: "b", data: (_: string) => void): void;
}

function getFoo(): Foo {
  return {
    foo: (x: "a" & "b", data: bigint & string) => { // no error
      // wat? we conjured a `never` out of nowhere
    }
  }
}
```

Another example with a runtime error: [Playground link](https://www.typescriptlang.org/play?target=8&strict=true#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIyYAUcAXMgERyUA0yAJnGOcsQPoUgCuAtgEbQAlMgC8APmQA3dMAZCKMuQG58hEvwqV+dRs1YcKAZzBRQAcxETps+YtuqAvrlwxuIBGGDoQycxDAMdGIFNEwcNSgA7ihfPAICInQKYgAPLRpkADIqHXomFhTDZH5gc1AwK0kleWy2YpMzEHNkAB9kHgFhMWrbISqIhISCuGIARhAhVSHnAmdnXH9AkiEAOiTial00rj5BKAH45AQfI3QAGwhV8-RzNOQAamQAJincRyEgA)

```ts
interface Foo {
  foo(a: "a", data: (_: number) => void): void;
  foo(b: "b", data: (_: string) => void): void;
}

function getFoo(): Foo {
  return {
    foo: (x: "a" & "b", data: ((_: bigint) => void) & ((_: string | number) => void)) => { // no error
      data(1n);
    }
  }
}

getFoo().foo("a", (x: number) => {
  console.log(x + 2);  // runtime error, x is actually a bigint
})
```

### 🙁 Actual behavior

`foo: (x: "a" & "b", data: bigint & string)` is accepted by the compiler, but would not satisfy the interface requirements

### 🙂 Expected behavior

I'd expect to need to write `foo: (x: "a" | "b", data: ((_: number) => void) | ((_: string) => void))`

**Comment by MartinJohns** [comment] 2021-06-04 18:36
> // wat? we conjured a `never` out of nowhere

It's not out of nowhere. It's from your type: `"a" & "b"`. This type can't possibly exist, so as a result you get `never`. A string can't be `"a"` **and** `"b"` at the same time.

**Comment by MartinJohns** [comment] 2021-06-04 18:37
This is essentially a duplicate of #32588. The object literal syntax does not support overloads.

**Comment by MartinJohns** [comment] 2021-06-04 18:38
> I'd expect to need to write `foo: (x: "a" | "b", data: ((_: number) => void) | ((_: string) => void))`

But this would be invalid. This would allow the function to be called with `"b"` and `(_: number)`, which is invalid according to the `Foo` interface.

**Comment by jtbandes** [comment] 2021-06-04 18:48
> This would allow the function to be called with `"b"` and `(_: number)`, which is invalid according to the Foo interface.

So the function would be more permissive with its arguments than the interface requires, but that doesn't make it invalid.

> The object literal syntax does not support overloads.

It's true that if I switch to regular overload syntax, I get the expected error:

```ts
function foo(a: "a", data: (_: number) => void): void; // This overload signature is not compatible with its implementation signature.
function foo(b: "b", data: (_: string) => void): void;
function foo(x: "a" & "b", data: bigint & string) {
}
```

But I wasn't trying to use overload syntax directly with my object literal (there's no such syntax)... I was just trying to return a value that conforms to an existing interface.

**Comment by jtbandes** [comment] 2021-06-04 18:49
https://github.com/microsoft/TypeScript/issues/32588#issuecomment-517431702 says

> This is already reasonable achievable today by annotating ProductManager with a type annotation.

In this case, I do have a type annotation on the object, but I still get a surprising lack of type-checking on the arguments my function accepts.

**Comment by jtbandes** [comment] 2021-06-04 18:52
> > // wat? we conjured a `never` out of nowhere
> 
> It's not out of nowhere. It's from your type: `"a" & "b"`. This type can't possibly exist, so as a result you get `never`. A string can't be `"a"` **and** `"b"` at the same time.

Sure, but _I was able to call the function_ without holding a `never` value...

**Comment by RyanCavanaugh** [comment] 2021-06-08 22:48
The code you'd need to write is
```ts
function getFoo(): Foo {
  return {
    foo: (x: string, data: ((ns: number) => void) | ((ns: string) => void)) => {
    }
  }
}
```
OP is working as intended - `never` is a bottom type and the method parameter types are bivariant, so the declaration is accepted.

**Closed** 2021-06-11 20:00 UTC
Labels: Working as Intended
