### ISSUE TITLE
Distinguishing types between `int` and `double`

### ISSUE THREAD

**Issue by orkhan-huseyn** [Microsoft/TypeScript#30543] opened 2019-03-22 11:15 UTC
## Search Terms

int double, integer, float, double

## Suggestion

This proposal introduces new number types `int` and `double` or `float`.  Goal is to make a difference between integers and floating point numbers since some JavaScript engines does such kind of difference in the back-end.

## Use Cases

As we know about V8 engine, it uses [pointer tagging](https://en.wikipedia.org/wiki/Tagged_pointer) to distinguish between different types such as `Smi` (small integer), `HeapObject`, `WeakHeapObject` etc.  

Consider this example: 

```
const o1 = {};
o1.x = 3;
o1.y = 4;

const o2 = {};
o2.x = 5;
o2.y = 6;
```

For both `o1` and `o2` object the engine will create same [shapes](https://mathiasbynens.be/notes/shapes-ics#shapes). See image below:

![](https://images.ponyfoo.com/uploads/7-86e5543b40894a178742aaa94ca0d7a2.svg)

However, after changing `o2.x` to some double value, say that `o2.x = 5.5;` then V8 will use create new subtree from that shape and the old subtree in this shape will be marked as deprecated and will be garbage-collected. Reason for this is because there is a difference how V8 stores `Smi` and `Double` values in the memory.

Here is second image after changing `x` to `5.5`:

![](https://images.ponyfoo.com/uploads/8-b321185c82e8443a919ebc598a320f69.svg)

Read more here: https://ponyfoo.com/articles/javascript-performance-pitfalls-v8#smi-to-double-migrations

## Examples

Some code examples from the proposal: 

```
class Point {
   constructor(private x: int, private y: int) {}
   
   getX(): int { this.x = x; }
   getY(): int { this.y = y; }
 }

let point = new Point(12, 5);
point.x = 1.5; // Error: double is not assignable to integer
```

This proposal does not require a breaking change, since `number` types are also okay, if one considers some possible performance pitfalls.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment] 2019-03-22 16:40
Duplicate of #195.

**Closed** 2019-03-22 21:39 UTC
Labels: Duplicate

**Comment by orkhan-huseyn** [comment] 2021-09-14 16:37
> Duplicate of #195.

If you have red both PRs carefully they have different reasons. I was not proposing it as a syntactic sugar.
