### ISSUE TITLE
Type-safe const assertions

### ISSUE THREAD

**Issue by btoo** [microsoft/TypeScript#42234] opened 2021-01-06 22:20 UTC
# Suggestion

## 🔍 Search Terms

type-safe const assertions

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

By allowing `const` assertions to accept a `type`, they can statically validate the type of the value _during_ construction, thereby providing the benefit of both standard and `const` assertions at the same time:
- `literalExpression as const Type`
- `<const Type>literalExpression`

where `literalExpression` is the literal expression whose type is being derived and `Type` is the type against which the derived type is going to be checked for `extends`

## 📃 Motivating Example

```typescript
type WeekDay = 'm' | 'tu' | 'w' | 'th' | 'f';
const mondayAndTuesday = ['m', 'tu'] as const WeekDay[]; // needs to not error
type ConstAssertion1 = typeof mondayAndTuesday extends WeekDay[] ? true : false; // true
type ConstAssertion2 = typeof mondayAndTuesday extends readonly ['m', 'tu'] ? true : false; // true
const mondayTuesdayAndSaturday = ['m', 'tu', 'sa'] as const WeekDay[]; // needs to error
```
This should also make it possible to allow autocomplete suggestions when `literalExpression as const WeekDay[]` is being written

## 💻 Use Cases

I often find myself having to choose between using [a standard type assertion][standard docs] and using [a `const` assertion][const docs]. Both offer important capabilities for static analysis:
- Standard: Assert that the `type` of the value being constructed `extends` _`SomePreexistingType`_
  - [e.g.][standard]
    ```typescript
    type WeekDay = 'm' | 'tu' | 'w' | 'th' | 'f';
    'sa' as WeekDay; // correctly errors
    ```
- `const`: Prevent type-widening of the value being constructed
  - [e.g.][const]
    ```typescript
    const weekDays = ['m', 'tu', 'w', 'th', 'f'] as const;
    weekDays.filter(weekDay => weekDay === 'sa'); // correctly errors
    ```

However, there isn't a way to have them _both_ (at least not without [a runtime assertion function](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions), [it seems][assertion function])

[standard docs]: https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions
[const docs]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions
[standard]: https://www.typescriptlang.org/play?ts=4.2.0-dev.20210106#code/C4TwDgpgBA6hEGsAiBDEUC8UDkBbbUAPjsAK4HHYDuFJAFrdgGbYDcAUNgM4oEpex4yNKygB6MVADGAewBOciFOAAbdBAXyuQA
[const]: https://www.typescriptlang.org/play?ts=4.2.0-dev.20210106#code/MYewdgzgLgBA7gUwQawCIEMCeEYF4YDaA5ALZEA0MRUArhVXPdQBZMBmRAujOjqJFADcAKEQoM2AHRsAlgBsoCAE4AKMWix4AfPCQbMeXPiIR0RAJSCYAemsxQSpQmBQ5B5UpBKIQA
[assertion function]: https://www.typescriptlang.org/play?ts=4.2.0-dev.20210106#code/C4TwDgpgBAogNhAthAdsAKuCAedA+KAXinSggA9hUATAZygCUIBDagexThAEEAnX5iGwBLFADMIvKAFUCAflgJkaTJGyyoALhIBuAFB6Axh1rAo1QfWIBtAOSJbAGii3gAVycuA7p9cALXzFfWmZgjwBdKGZ6YxRTfVBIKAARQSJFJFQMLGxEiDYxc0s8Az0xNxRDYGEOKNpaSWAASVpUkAAKADdmOG1mFBAASj76xvpuuChhejaoAG89KCnC9oBCCxBaADpRagoAeTEunsHBqGA-XjYvKBQIG5h+Nl59AF8DWNMoWjZkADkOBRplQ0LNiLYfv9AeRgVk2rY9NEGrxmq1BO1IRAAXcYaY4YJBno8lAAMLPXgQKpcP4QTqSdJ5ArfX5Y6Gw0GCPRAA

**Comment by RyanCavanaugh** [comment] 2021-01-06 22:24
Possible duplicate of #7481? I'm not sure what inferred type you want `mondayAndTuesday` to have

**Comment by btoo** [comment] 2021-01-06 22:46
> I'm not sure what inferred type you want mondayAndTuesday to have

```typescript
const mondayAndTuesday = ['m', 'tu'] as const WeekDay[];
type MondayAndTuesday = typeof mondayAndTuesday // readonly ['m', 'tu']
```

Another example would be 
```typescript
import { CSSProperties } from 'react';
const ReusableStyle = { width: '100%' } as const CSSProperties
```
where type-checking/autocomplete would be possible _while_ the value is being written, as long as `as const CSSProperties` has already been appended.

> Possible duplicate of #7481?

[This](https://github.com/microsoft/TypeScript/issues/7481#issuecomment-736103803) looks pretty synonymous with my proposal! Though I think dropping the `is` would be more ergonomic and idiomatic

**Comment by RyanCavanaugh** [comment] 2021-01-06 22:47
Yeah I think with 7481 it'd be `["m", "tu"] as const (syntax???) readonly Weekday[]` which composes pretty well.

**Closed by RyanCavanaugh** 2021-01-06 22:47 UTC

**Comment by btoo** [comment] 2021-01-06 22:50
Why would `readonly` need to be included in `["m", "tu"] as const (syntax???) readonly Weekday[]`? Shouldn't `const` take care of that transformation?

**Comment by RyanCavanaugh** [comment] 2021-01-06 22:55
You're right, it'd work either way there

**Comment by btoo** [comment] 2021-01-06 23:13
I'd like to rescind my comment that
> [dropping the `is` would be more ergonomic and idiomatic](https://github.com/microsoft/TypeScript/issues/42234#issuecomment-755763011)

since an `is` operator, as you say, would be better for composability and could be used _without_ `as const` entirely:

```typescript
import type { CSSProperties } from 'react';
const reusableStyle = { width: '100%' } is CSSProperties;
type ReusableStyle = typeof reusableStyle; // { width: string }
```
