### ISSUE TITLE
Type of object spread properties is incorrectly inferred with strictNullChecks

### ISSUE THREAD

**Issue by MartinJohns** [Microsoft/TypeScript#21698] opened 2018-02-06 21:02 UTC
**TypeScript Version:**  2.7.1

**Search Terms:** 
- partial
- strictNullChecks
- undefined

**Code**

```ts
interface User {
    name: string;
}

const user: User = { name: 'Bob' };
const partial: Partial<User> = { name: undefined };
const result = { ...user, ...partial };

type ResultName = (typeof result)['name'];
```

**Expected behavior:**
Type `ResultName` is `string | undefined`.

**Actual behavior:**
Type `ResultName` is `string`.

**Playground Link:**  
https://www.typescriptlang.org/play/#src=%0D%0Ainterface%20User%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aconst%20user%3A%20User%20%3D%20%7B%20name%3A%20'Bob'%20%7D%3B%0D%0Aconst%20partial%3A%20Partial<User>%20%3D%20%7B%20name%3A%20undefined%20%7D%3B%0D%0Aconst%20result%20%3D%20%7B%20...user%2C%20...partial%20%7D%3B%0D%0A%0D%0Atype%20ResultName%20%3D%20(typeof%20result)%5B'name'%5D%3B%0D%0A

**Related Issues:**
#14799

**Comment by mhegazy** [comment] 2018-02-06 21:32
Seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/13195

**Closed** 2018-02-22 20:41 UTC
Labels: Duplicate
