### ISSUE TITLE
Doesn't remember the class inside a Array.map

### ISSUE THREAD

**Issue by ulrikaugustsson** [Microsoft/TypeScript#9491] opened 2016-07-02 15:04 UTC
**TypeScript Version:** nightly (2.0.0-dev.201xxxxx)

**Code**

```ts
class SomeClass {
  constructor(public id: number){}
}

class SomeOtherClass {
  constructor(public name: string){}
}

type SomeUnionType = SomeClass | SomeOtherClass;

function buggyFunction(aArray: string[], bug: SomeUnionType): void {
  if (bug instanceof SomeClass) {
    console.log(bug.id);
    return;
  }

  if (bug instanceof SomeOtherClass) {
    aArray.map((a) => a = bug.name());
    return;
  }

  return;
}
```

**Expected behavior:**
Typescript should know that `bug` is of the type SomeOtherClass inside of the map function.

**Actual behavior:** 
Property 'name' does not exist on type SomeClass | SomeOtherClass.

**Comment by kitsonk** [comment] 2016-07-02 17:55
Duplicate of #9263 and #7662 and #9345 as narrowing is currently reset across function boundaries as explained in [#7718 (comment)](https://github.com/Microsoft/TypeScript/issues/7719#issuecomment-202684512).

Though this keeps coming up and it seems logical that anonymous functions, this could be potentially preserved? (or at least arrow functions used as callbacks?) @mhegazy @ahejlsberg @RyanCavanaugh

**Comment by ahejlsberg** [comment] 2016-07-03 02:51
The solution here is to guard on a `const` variable. Type guards are in effect across function expression and arrow function boundaries for `const` variables. We are considering allowing `const` as a parameter modifier so you don't have to copy parameters into `const` locals.

**Comment by ulrikaugustsson** [comment] 2016-07-03 07:43
Yeah, I solved my real issue by assigning the value to a const but it seems wrong to have to that. The behaviour is the same when using interfaces with a .kind property as guard.

**Closed** 2016-07-04 04:09 UTC
Labels: Question

**Comment by mquandalle** [comment] 2016-07-19 08:44
@ahejlsberg 

> We are considering allowing `const` as a parameter modifier so you don't have to copy parameters into `const` locals.

I’m interested in that, is there an issue to track this solution?
