### ISSUE TITLE
`any` inferred as type parameter even with `--noImplicitAny`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#11311] opened 2016-10-02 23:41 UTC
**TypeScript Version:**  nightly (2.1.0-dev.20161002)

**Code**

``` ts
function second<T>(tuple: [any, T]): T
function second<T>(tuple: [any, T, any]): T
function second(tuple: any[]): any {
    return tuple[1]
}

function segundo<T>(tuple: [any, T] | [any, T, any]): T {
    return tuple[1]
}

const pairs: [number, string][] = [[1, "two"]]
const x: number[] = pairs.map(second)
const y: number[] = pairs.map(segundo)
```

**Expected behavior:**

Both `x` and `y` are compile errors.

**Actual behavior:** 

`y` fails with:

```
a.ts(13,7): error TS2322: Type 'string[]' is not assignable to type 'number[]'.
  Type 'string' is not assignable to type 'number'.
```

but `x` does not fail, because the generic parameter of `map` is inferred as `any` rather than `string`, even with `--noImplicitAny` turned on.

On another note, I'm not sure what's happening below: either the type parameter of `identity` is inferred as `any` or it's inferred as `string & number` and function bivariance wreaks its magic:

``` ts
function useStringToNumber(f: (s: string) => number): void {}
function identity<T>(t: T): T {
    return t
}
useStringToNumber(identity)
```

**Comment by sergey-shandar** [comment] 2016-10-11 18:00
Related issue #3038

**Comment by mhegazy** [comment] 2017-05-17 23:56
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/11152

**Comment by andy-ms** [comment] 2017-05-18 00:04
Here's a simpler example:

```ts
declare function f<T>(x: T): T;
declare function f<T>(x: T, y: number): T;

const a: string[] = ["a", "b"];
const b = a.map(f);
```

Even in the absence of a type annotation on `b`, I would still expect to get either a compile error or a type other than `any[]`.

**Comment by mhegazy** [comment] 2017-05-18 20:05
looks like the same issue as https://github.com/Microsoft/TypeScript/issues/9366

**Comment by mhegazy** [comment] 2017-05-24 21:35
The [last example](https://github.com/Microsoft/TypeScript/issues/11311#issuecomment-302264138) is technically as spec'ed.  see [4.15.2 Type Argument Inference](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#4152-type-argument-inference):

> If e is an expression of a function type that contains exactly one generic call signature and no other members, and T is a function type **with exactly one non-generic call signature** and no other members, then any inferences made for type parameters referenced by the parameters of T's call signature are fixed, and e's type is changed to a function type with e's call signature instantiated in the context of T's call signature (section 3.11.6).

**Comment by mhegazy** [comment] 2017-06-08 16:14
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-06-08 16:14 UTC
Labels: Duplicate
