### ISSUE TITLE
Module resolution failure, non-documented "typings" priority and better mainFields

### ISSUE THREAD

**Issue by StanEgo** [microsoft/TypeScript#33305] opened 2019-09-08 15:25 UTC
Documentation  (https://www.typescriptlang.org/docs/handbook/module-resolution.html#how-typescript-resolves-modules) states that: "TypeScript will also use a field in package.json named "types". But it fails if "typings" is also there.

**TypeScript Version:**  3.6.2, next

**Code**
package.json file that contains this settings:
```json
"types": "src/index.ts",
"typings": "types/index.d.ts"
```

**Expected behavior:**
When package with settings above is resolved it should act as defined in documentation and look for "src/index.ts" defined by "types" property.

Of course there are additional notes in https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html, that "typings" and "types" are equal for publishing. But firstly, this is for publishing and not documented for resolving.

And secondly, it is very good that there are already two fields and possibility to separate declarations from sources like in code sample above. Because sometimes it's nice to have access to full sources (not only declarations), like bundling. For example, mainFields setting for webpack can point to ["types", "module", "main"].

We can just swap two lines in https://github.com/microsoft/TypeScript/blob/01e1b1bb276f48eaa0612a34dd8f1eec5d86bd49/src/compiler/moduleNameResolver.ts#L160-L162.
Firstly it will check for "types", then for "typings". And probably slightly enhance documentation to mention in node resolving that "typings" is also employed.

**Actual behavior:**
It fails to resolve any module in "src/index.ts" provided by the "types" property. The reason is that It firstly looks into "typings" folder and if doesn't exists (declaration not build in this sample), "types" setting is completely ignored.

**Comment by sheetalkamat** [comment] 2019-09-23 21:53
Marking this as intended since this was done for compatibility reasons.

**Closed by sheetalkamat** 2019-09-23 21:53 UTC
Labels: Working as Intended

**Comment by StanEgo** [comment] 2019-11-08 18:32
@sheetalkamat, looks like you didn't realize that if this behavior is expected, then there is a problem in documentation. So something should be fixed - code should reflect documentation or documentation should follow the actual code.

**Comment by yavulan** [comment] 2019-11-08 19:00
How changing this detection order will remove backward compatibility?
Moreover, in case "types" is newer than "typings", shouldn't "types" be prioritized over "typings"?

And take a deep look into potential usefulness with bundling, as described in the initial message.
