### ISSUE TITLE
Type inference for exact strings

### ISSUE THREAD

**Issue by ajcrites** [Microsoft/TypeScript#16276] opened 2017-06-05 22:41 UTC
**TypeScript Version:**  2.2.2

**Code**

```ts
interface Css {
  position: 'absolute' | 'relative';
}
function style(rules: Css) { }

const rules = { position: 'absolute' };
style(rules);
style({ position: 'absolute' });
```

**Expected behavior:**
There should be no type issues.

**Actual behavior:**
`style(rules)` yields

> `Argument of type '{ position: string; }' is not assignable to parameter of type 'Css'`
> `Types of property 'position' are incompatible`

Using `style({position: 'absolute'})` works fine.

**Comment by tycho01** [comment] 2017-06-09 15:54
#16360 just now seemed a bit similar (about tuples instead of objects).

**Comment by mhegazy** [comment] 2017-08-26 00:14
duplicate of https://github.com/Microsoft/TypeScript/issues/16523 and https://github.com/Microsoft/TypeScript/issues/12955

**Comment by mhegazy** [comment] 2017-09-11 16:00
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-11 16:00 UTC
Labels: Duplicate
