### ISSUE TITLE
awaited operator doesn't work with type guards

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#37512] opened 2020-03-21 08:46 UTC
@rbuckton 

**TypeScript Version:**  master

**Search Terms:**

**Code**

```ts
declare function isAwaited(value: any): value is awaited unknown;
function f<a>(a: a): void {
  isAwaited(a) && a;
}
```

**Expected behavior:**
The narrowed type of a is awaited a.
**Actual behavior:**
The narrowed type of a is a.

**Playground Link:** 

**Related Issues:**

**Comment by falsandtru** [comment] 2020-03-23 11:04
Probably we have to replace isPromiseLike with isAwaited.

```ts
          if (isPromiseLike(value)) {
            internal.status = {
              state: State.resolved,
              result: value,
            };
            value.then(
              value => {
                assert(internal.status.state === State.resolved);
                internal.status = {
                  state: State.fulfilled,
                  result: value,
                };
                resume(internal);
              },
              reason => {
                assert(internal.status.state === State.resolved);
                internal.status = {
                  state: State.rejected,
                  result: reason,
                };
                resume(internal);
              });
          }
          else {
            internal.status = {
              state: State.fulfilled,
              result: value!, // error
            };
            resume(internal);
          }
```

```
Type 'NonNullable<T>' is not assignable to type 'awaited T'.
  Type 'T' is not assignable to type 'awaited T'.ts(2322)
```

https://github.com/falsandtru/spica/blob/v0.0.343/src/promise.ts

**Comment by rbuckton** [comment] 2020-03-24 01:26
The problem is that `awaited unknown` is just reduced to `unknown`, so you are asserting that `value` is `unknown`. The `awaited` type *does* work in type guards:

![image](https://user-images.githubusercontent.com/3902892/77378607-ab204580-6d33-11ea-8687-f2786c5a7721.png)

Playground link: https://www.typescriptlang.org/play/index.html?ts=3.9.0-dev.20200322#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXywGcBBAdyiwxGAB4AVAPgAoA3KCZEALnjvgB94UcpWq8AlDzYcERISKrBeAbgBQKdNjxJ6zAB48+g4RUUT4Ab1XwbBRPCZEyp6kz3jxl67Z961PgF9VAKA

**Comment by rbuckton** [comment] 2020-03-24 01:27
Let me know if that addresses your concerns so that I can close this issue.

**Comment by falsandtru** [comment] 2020-03-24 04:44
Basically type arguments are not used in type guards. Can you remove type arguments to accept all types? Actually, your function doesn't accept `T | awaited T | PromiseLike<T>`.

Ideally, since `T` is considered as thenable when `T` is not `awaited T`, isAwaited function should work as follows.

```ts
declare function isAwaited(value: any): value is awaited any; // or awaited typeof value
function f<T>(x: T | awaited T | PromiseLike<T>) {
    if (isAwaited(x)) {
        x; // awaited T
    }
    else {
        x; // PromiseLike<T>
    }
}
```

**Comment by nmain** [comment] 2020-03-24 19:24
Just to make sure I'm understanding this right, would this be a reasonable implementation of `isAwaited`?  No matter what `T` is, `awaited T` is never PromiseLike ("thennable"), so `value is awaited unknown` just means that value is not PromiseLike.

```ts
function isAwaited(value: any): value is awaited unknown {
    return !value || typeof value.then !== "function";
}
```

**Comment by rbuckton** [comment] 2020-03-24 19:31
`awaited` is only preserved when the type argument is generic, so `awaited unknown` is just `unknown`.  Similar to `awaited any` is just `any`. It's only preserved at higher order.

**Closed** 2020-03-26 01:39 UTC
Labels: In Discussion, Suggestion
