### ISSUE TITLE
Generics, keyof, typeguard error

### ISSUE THREAD

**Issue by Bobdina** [Microsoft/TypeScript#17812] opened 2017-08-15 17:37 UTC
**TypeScript Version:**  2.4.2

I noticed a problem similar to #17808 when playing with generics:

```typescript
function GetPropertyWorks<T, P extends keyof T>(obj:T, prop:P):number{
    let value = obj[prop];
    if(typeof value == 'number'){
        return value;
    }
    return 0;
}

function GetPropertyDoesnt<T, P extends keyof T>(obj:T, prop:P):number{
    if(typeof obj[prop] == 'number'){
        return obj[prop];
    }
    return 0;
}
```
So apparently assigning to an intermediary solves the problem.

**Expected behavior:**

I expect that if I typecheck the obj[prop] value, that I can use it as a value of the type of the typecheck.

**Actual behavior:**
error TS2322: Type 'T[P]' is not assignable to type 'number'.
  Type 'T[string]' is not assignable to type 'number'.

**Comment by RyanCavanaugh** [comment] 2017-08-15 21:52
Duplicate of #17567 - type guards on property currently don't work

**Comment by mhegazy** [comment] 2017-08-29 23:51
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-08-29 23:51 UTC
Labels: Duplicate
