### ISSUE TITLE
Destructing arrays in function invocation doesn't work as expected

### ISSUE THREAD

**Issue by ivanpadavan** [Microsoft/TypeScript#22061] opened 2018-02-20 19:38 UTC
It's doesn't seem to be possible to invoke function with destructured array of arguments 
**Current behavior**
```ts
const func = (x: number, y: number) => x + y;
const payload = [1, 2];
func(...payload);
```
Throws an error.

**Possible workarounds**
```ts
// 0
const func = (x = 0, y = 0) => x + y;
// 1
const func = (x?: number, y?: number) => x + y;
```

**Playground link** https://www.typescriptlang.org/play/index.html#src=const%20func%20%3D%20(x%3A%20number%2C%20y%3A%20number)%20%3D%3E%20x%20%2B%20y%3B%0D%0Aconst%20payload%20%3D%20%5B1%2C%202%5D%3B%0D%0Afunc(...payload)%3B

**Comment by DanielRosenwasser** [comment] 2018-02-20 20:23
Happens even if you have a 2-tuple: 

```ts
const func = (x: number, y: number) => x + y;
const payload: [number, number] = [1, 2];
func(...payload);
```

**Comment by mhegazy** [comment] 2018-02-23 00:00
Duplicate of https://github.com/Microsoft/TypeScript/issues/4130

**Closed** 2018-03-09 16:33 UTC
Labels: Duplicate
