### ISSUE TITLE
Bug with union types

### ISSUE THREAD

**Issue by johnfn** [Microsoft/TypeScript#25958] opened 2018-07-26 07:20 UTC
**TypeScript Version:**  3.1.0-dev.20180714

**Search Terms:**

union

**Code**

```ts
function g(x: "a" | "b") {
    const f: { type: "a" } | { type: "b" } = {
        type: x
    };
}
```

**Expected behavior:**

No error.

**Actual behavior:**

Type '"a"' is not assignable to type '"b"'.

**Playground Link:** 

http://www.typescriptlang.org/play/index.html#src=function%20g(x%3A%20%22a%22%20%7C%20%22b%22)%20%7B%0A%20%20%20%20const%20f%3A%20%7B%20type%3A%20%22a%22%20%7D%20%7C%20%7B%20type%3A%20%22b%22%20%7D%20%3D%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20x%0A%20%20%20%20%7D%3B%0A%7D%0A

**Related Issues:** 

I'm pretty sure this already exists, but I have no clue what to search for. :(

**Comment by AlCalzone** [comment] 2018-07-26 12:06
Does this work for you?
```ts
function g<T extends "a" | "b">(x: T) {
    const f: { type: T } = {
        type: x
    };
    return f;
}

const a = g("a"); // { type: "a" }
const b = g("b"); // { type: "b" }
const c = g("c"); // error
```

**Comment by jcalz** [comment] 2018-07-26 13:45
Duplicate of #12052

**Closed** 2018-08-03 21:09 UTC
Labels: Duplicate
