### ISSUE TITLE
When the compile target is set to ES2022, an error will be reported at runtime

### ISSUE THREAD

**Issue by Yuuki-Sakura** [microsoft/TypeScript#53218] opened 2023-03-12 12:55 UTC
# Bug Report

### 🔎 Search Terms

ES2022 static member 

### 🕗 Version & Regression Information

This is a crash

When a class has a static property and uses the class name when initializing and uses a decorator, an error will be reported at runtime

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=9&module=1&pretty=false&allowSyntheticDefaultImports=true&isolatedModules=true#code/KYDwDg9gTgLgBAYwgOwM7wCLAXAvHACgEoAuOAYQBsBDVVLJKamaOPAPkJmqgHNgYRDnADeAKDEBfCQAEGxMaEixENOnAAqwdKLFt0zAJY5qeTdpgA6ZNQC2wKRKRoIlYJcoReBLekvUiIA)

### 💻 Code

```ts
export const Dec = (): ClassDecorator  => (target) => {

}

@Dec()
export class Test {
  // Using this.name and turning off useDefineForClassFields can eliminate runtime errors but need to use @ts-ignore
  static a = Test.name
}

console.log(Test.a)
```

### 🙁 Actual behavior

When run compiled javascript file will throw error:
`Cannot read properties of undefined (reading 'name') `

### 🙂 Expected behavior
```
console.log(Test.a) // should output 'Test'
```

### possible solution
Remove the following compiled Test_1 variables will become normal
```js
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Test = exports.Dec = void 0;
const Dec = () => (target) => {
};
exports.Dec = Dec;
let Test = class Test {
    static a = Test.name;
};
Test = __decorate([
    (0, exports.Dec)()
], Test);
exports.Test = Test;
console.log(Test.a); // output 'Test'
```

**Comment by fatcerberus** [comment] 2023-03-12 14:05
Looks like a duplicate of https://github.com/microsoft/TypeScript/issues/52004

**Closed** 2023-03-16 18:00 UTC
Labels: Duplicate
