### ISSUE TITLE
Bad emit for constructor parameter properties when using --useDefineForClassFields

### ISSUE THREAD

**Issue by Jessidhia** [microsoft/TypeScript#34971] opened 2019-11-07 10:36 UTC
**TypeScript 3.7.2**
[Playground link](https://www.typescriptlang.org/play/index.html?useDefineForClassFields=true#code/MYGwhgzhAEBiD29oG8BQ0PQE4FMwBN4A7EAT2gCMwtoBeaAFwAsBLCAOgDNF2qtV0mYMQgMsAV2AN4WABS4CxMtG7wAXCkrUNorCyIBzaAF8AlCmOpLQA)

Compiler Options:
```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

**Input:**
```typescript
class Foo {
    readonly bar = this.foo.bar

    constructor(readonly foo: { bar: string }) {}
}

```

**Output:**
```javascript
"use strict";
class Foo {
    constructor(foo) {
        this.foo = foo;
        Object.defineProperty(this, "foo", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: void 0
        });
        Object.defineProperty(this, "bar", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: this.foo.bar
        });
    }
}
```

Note how `this.foo` is initialized with `[[Set]]` (going against the option) and _then_ immediately clobbered with `undefined` by the `[[Define]]`.

**Expected behavior:**

This depends on how the parameter property is going to be interpreted. If it's still going to be interpreted as the same as writing an assignment in the constructor's body, then it needs to be reordered to happen _after_ all of the `Object.defineProperty` initializers (as they technically run before `super()` returns, or before the constructor block begins evaluating for non-subclassing classes), and `bar`'s initializer should detect `this.foo` as used before initialization.

If they're going to be "as powerful as" actual class fields, then constructor parameter properties must be hoisted higher than any actual class field initializers. Even with this latter interpretation, which is _almost_ what happened, the `this.foo = foo` assignment is incorrect and should be done either immediately after the `Object.defineProperty` for `foo` runs, or the `Object.defineProperty` should use the constructor parameter as `value` initializer.

**Comment by ajafff** [comment] 2019-11-07 10:45
Duplicate of #34942?

**Comment by Jessidhia** [comment] 2019-11-07 10:48
Looks like it, with the added suggestion of making this actually a use-before-initialize error due to the javascript runtime semantics of class properties.

**Closed** 2019-11-10 18:00 UTC
Labels: Duplicate
