### ISSUE TITLE
Unexpected compile / type error when using Promise.all

### ISSUE THREAD

**Issue by jeremywen3** [microsoft/TypeScript#35136] opened 2019-11-16 04:27 UTC
**TypeScript Version:**  3.7.2

**Search Terms:**
- Promise.all typing

**Code**

`index.ts`
```ts
type RandomType = {};

const getRandomValue = async (): Promise<RandomType> => {
    return {};
};

const getResults = async (): Promise<{ data: string[] }> => {
    return { data: ['a', 'b', 'c'] };
};

const run = async () => {
    const [random, { data }] = await Promise.all([getRandomValue(), getResults()]);
    console.log(random, data);
};

run();
```

`tsconfig.json`
```json
{
    "compilerOptions": {
        "target": "esnext",
        "lib": ["esnext", "dom"]
    },
    "exclude": ["node_modules"],
    "include": ["./**/*.ts"]
}

```

**Expected behavior:**
Compiles successfully.

**Actual behavior:**
Compile error: "Property 'data' does not exist on type 'RandomType'."

Seems to still compile the js file even though it shows a compile error.

Does not run with `ts-node` though.

**Playground Link:**
http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=13&pc=31#

**Related Issues:**

**Comment by MartinJohns** [comment] 2019-11-16 09:57
Duplicate of #34925.

**Closed** 2019-12-13 18:00 UTC
Labels: Duplicate
