### ISSUE TITLE
enum auto init number that already defined

### ISSUE THREAD

**Issue by xsetion** [Microsoft/TypeScript#8391] opened 2016-04-30 00:18 UTC
**TypeScript Version:** 
type-script playground

**Code**
*TS*
```ts
enum Color {Red = 6, Green=5, Blue};
let colorName: string = Color[2];

alert(colorName);
```
**
*JS*
```js
var Color;
(function (Color) {
    Color[Color["Red"] = 6] = "Red";
    Color[Color["Green"] = 5] = "Green";
    Color[Color["Blue"] = 6] = "Blue";
})(Color || (Color = {}));
;
var colorName = Color[2];
alert(colorName);
```
**

**Expected behavior:**
Since 'Red' is number 6, and 'Blue' defined automatically to follow 'Green's 5, 'Blue' should be getting any number that not listed yet,
The alert should not call 'Blue'.

**Actual behavior:** 
The 'Blue' element in the enum get 6 because it follows 'Green' 5 and did not get a pre-set.

**Comment by mhegazy** [comment] 2016-04-30 00:32
duplicate of https://github.com/Microsoft/TypeScript/issues/6864

**Closed by mhegazy** 2016-04-30 00:32 UTC
