### ISSUE TITLE
Private check can be bypassed by ElementAccessExpression

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#42360] opened 2021-01-15 13:51 UTC
# Bug Report

### 🔎 Search Terms

bypass private element access

### 🕗 Version & Regression Information

- I tested it on the master branch

### 💻 Code

```ts
class X { private x: number }
new X()['x']
```

### 🙁 Actual behavior

No error

### 🙂 Expected behavior

Type Error

**Comment by MartinJohns** [comment] 2021-01-15 15:32
It's intentional: https://github.com/microsoft/TypeScript/issues/12821#issuecomment-266249583

**Comment by ajafff** [comment] 2021-01-15 15:34
Duplicate of #19335

Some use it as a feature, e.g. to test private state. Some abuse it.

I have written a lint rule that applies the same rules of property access to element access: https://github.com/fimbullinter/wotan/blob/master/packages/mimir/docs/no-restricted-property-access.md

**Closed** 2021-01-15 17:07 UTC
Labels: Duplicate
