### ISSUE TITLE
Missing "Type ... has no properties in common with type ..." error

### ISSUE THREAD

**Issue by PavelPZ** [microsoft/TypeScript#25664] opened 2018-07-14 16:27 UTC
Typescript 2.9.2 and 3.0 RC

I think that following code is self explanatory

```
type RootKeys = 'name'
type Root = { [P in RootKeys]?: number } & { subRoot?: Root }

const root: Root = {
  subRoot: {
    name: 2,
    x3: 2, // ===> SHOULD BE ERROR BUT NO ERROR
  }
}

const root2: Root = {
  subRoot: {
    x3: 2,  // ==> ERROR AS EXPECTED (Type ... has no properties in common with type ...)
  }
}
```

**Comment by mhegazy** [comment] 2018-07-16 18:35
Duplicate of https://github.com/Microsoft/TypeScript/issues/18075

**Closed as completed** 2018-07-26 19:23 UTC
Labels: Duplicate
