### ISSUE TITLE
Infer more specific type from a union of tuple types when using string literals

### ISSUE THREAD

**Issue by fongandrew** [Microsoft/TypeScript#14339] opened 2017-02-27 19:53 UTC
**TypeScript Version:**  2.2.1

**Code**

```ts
declare var x: { type: "A", value: number; } | { type: "B", value: string; };
if (x.type === "A") {
    x.value; // Correctly inferred to be number
}

declare var y: ["A", number] | ["B", string];
if (y[0] === "A") {
    y[1]; // Not inferred as number but as string | number
}
```

**Expected behavior:** `y[1]` should be inferred as a number based on the value of `y[0]`

**Actual behavior:** `y[1]` is inferred to be `string|number`.

**Comment by mhegazy** [comment] 2017-02-28 00:55
Duplicate of https://github.com/Microsoft/TypeScript/issues/10530

**Closed by mhegazy** 2017-02-28 00:55 UTC
Labels: Duplicate
