### ISSUE TITLE
console.log(...[1,2,3]); Parameter does not support spread operator.

### ISSUE THREAD

**Issue by mishengqiang** [microsoft/TypeScript#15387] opened 2017-04-26 03:36 UTC
**TypeScript Version:**  2.2.2

**Code**

```ts
console.log(...[1,2,3]);
```

**Expected behavior:**
I can use the spread operator and can compile it. As in the image below in Chrome DevTools.

![image](https://cloud.githubusercontent.com/assets/9413032/25416833/975c5e46-2a72-11e7-8559-a115c32decbc.png)

**Actual behavior:**
Error Message: Supplied parameters do not match any signature of call target.

![image](https://cloud.githubusercontent.com/assets/9413032/25416800/632c94e2-2a72-11e7-9989-7ce4df2b7333.png)

**Comment by SaschaNaz** [comment] 2017-04-26 10:08
Function definition is strange, it should be as following on lib.d.ts:

```ts
interface Console {
  log(...data: any[]): void;
}
```

**Comment by mhegazy** [comment] 2017-04-26 17:07
The general case is a duplicate of https://github.com/Microsoft/TypeScript/issues/15375 and https://github.com/Microsoft/TypeScript/issues/5296.

For this specific one, as noted by @SaschaNaz, a fix to lib.d.ts should do the trick. PRs welcomed.  You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by alex3165** [comment] 2017-04-26 21:11
Seems like https://github.com/Microsoft/TSJS-lib-generator/pull/227/files#diff-7f5b3c2d91a2f2c707b4024507a6c1edR13453 should fix it

**Comment by jakebailey** [comment] 2023-06-28 16:53
`console.log` has been typed properly (as previously defined in this thread) for a super long time.

**Closed by jakebailey** 2023-06-28 16:53 UTC
Labels: Bug, Help Wanted, Domain: lib.d.ts

**Comment by saschanaz** [comment] 2023-06-28 18:25
🎉 for myself. 🙂
