### ISSUE TITLE
Different behavior for {} and unknown narrowed to {}

### ISSUE THREAD

**Issue by guillaumebrunerie** [microsoft/TypeScript#50531] opened 2022-08-30 10:26 UTC
# Bug Report

I found a curious situation in Typescript 4.8 where a variable of type `unknown` narrowed down to `{}` behaves differently than a variable of type `{}` from the beginning.

### 🔎 Search Terms

4.8, narrow, in
Not sure if it is related to #50527.

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because it relies on a new 4.8 feature.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-beta&ssl=18&ssc=2&pln=1&pc=1#code/MYewdgzgLgBAZjAvDAFADwFwwN4F8A0MAnlgK5gDWYIA7mAJRIB8OAUAJACWCKAhCgCIAhgJicwMNPUbYO7AE4BTKKXlgA3B1wdQkEABtFAOn0gA5unqb2AehuSY0IUQg5cqTq+qwwQ+fNpFABN6Qm8YEAAHKE4AWyF9GAAjUlghWEMhaBhwmgCwM1YOblReIhk5JRU1a21beyIxLz8AmmCYKBA3Iq4efmFRcWJpNnYFZVUNLR1wCANjUwty6ztiJpyWwKCOrrBFADdFeUIaAAtOYFP14Ez5fUbxUH9FYChCITBtyKqoRuh5D5mRTJF5CUgQYGcWCnITbKCnYEQISxYG-SLArIOJKKOAgJQwD7bNoweTkDoIxzI4FmUh+IKsXBAA)

### 💻 Code

```typescript
const f = (x: {}, y: unknown) => {
  if (!("a" in x)) {
    return;
  }
  console.log(x);
  // x stays {} (is not narrowed), not optimal but at least not wrong

  if (!y) {
    return;
  }
  // y is narrowed to {}

  if (!("a" in y)) {
    return;
  }
  console.log(y);
  // y is narrowed to never, which is clearly incorrect, and pretty strange because
  // it had the same type as x before and we run the same guard
}
```

### 🙁 Actual behavior

Narrowing `unknown` to `{}` and then using the `in` operator results in an incorrect type, whereas it doesn’t happen when starting with a variable of type `{}`.

### 🙂 Expected behavior

Narrowing should behave the same way whether we start with the type `{}` or narrow `unknown` down to `{}`.

**Comment by fatcerberus** [comment] 2022-08-31 21:30
I'm guessing what happens is that once `y` gets narrowed to `{}`, TS decides that `"a" in y` is impossible since `in` normally narrows unions via property existence and `{}` is an empty object type and thus gets eliminated, leaving `never`.  That doesn't explain why `x` isn't also narrowed to `never`, though.  Quite odd indeed.

**Comment by fatcerberus** [comment] 2022-08-31 21:32
For the record, the narrowing of `y` to `{}` is new - 4.7.4 leaves `y` as `unknown` and subsequently errors on `"a" in y`: [Playground](https://www.typescriptlang.org/play?ts=4.7.4#code/MYewdgzgLgBAZjAvDAFADwFwwN4F8A0MAnlgK5gDWYIA7mAJRIB8OAUAJACWCKAhCgCIAhgJicwMNPUbYO7AE4BTKKXlgA3B1wdQkEABtFAOn0gA5unqb2AehuSY0IUQg5cqTq+qwwQ+fNpFABN6Qm8YEAAHKE4AWyF9GAAjUlghWEMhaBhwmgCwM1YOblReIhk5JRU1a21beyIxLz8AmmCYKBA3Iq4efmFRcWJpNnYFZVUNLR1wCANjUwty6ztiJpyWwKCOrrBFADdFeUIaAAtOYFP14Ez5fUbxUH9FYChCITBtyKqoRuh5D5mRTJF5CUgQYGcWCnITbKCnYEQISxYG-SLArIOJKKOAgJQwD7bNoweTkDoIxzI4FmUh+IKsXBAA)

**Comment by guillaumebrunerie** [comment] 2022-09-01 05:27
`{}` isn't the empty object type, it's the "anything not null or undefined" type. So `"a" in y` should ideally narrow `{}` to `{a: unknown}` (feature request #21732), but there is in any case no reason to narrow it to `never`.

**Comment by fatcerberus** [comment] 2022-09-01 05:41
`{}` is the empty object type in the same sense that `{ a: string }` is the “object with a single property called `a` which is a string” type.  Structural typing may let you assign other things to it (like primitives) but it’s still really an object type.  It’s even assignable to `object`.

Case in point: Primitives can also be assigned to `{ toString(): string }`, so `{}` isn’t really special in that regard.

For the narrowing to `never`, like I said above I think it happens for the same reason that `{ b: string } | { c: string }` is narrowed to `never` by the same check.  What I don’t understand is why the first case doesn’t *also* narrow to `never`.

**Comment by guillaumebrunerie** [comment] 2022-09-01 06:09
Oh, I see what you mean. I didn’t realize that `"a" in x` narrows `{ b: string } | { c: string }` to `never`, it's unsound but I guess also a very common pattern in JS.

**Comment by fatcerberus** [comment] 2022-09-01 06:12
Yeah, every once in a while someone opens an issue about `in`-based narrowing being unsound, but it's by design because it's such a common JS pattern.  I'm pretty sure *this* is a bug though, because `in` isn't supposed to narrow non-union types IIRC.

**Comment by guillaumebrunerie** [comment] 2022-09-01 06:48
Oh, maybe the narrowing of `unknown` to `{}` actually narrows it internally to a union type with only one component (`| {}` if you see what I mean). That could explain it I guess.

**Comment by fatcerberus** [comment] 2022-09-01 23:25
> Oh, maybe the narrowing of unknown to {} actually narrows it internally to a union type with only one component (| {} if you see what I mean). That could explain it I guess.

This was my hypothesis as well.

**Closed** 2022-09-02 16:30 UTC
Labels: Bug, Fix Available
