### ISSUE TITLE
Autocompletion broken for generic function parameter with optional properties

### ISSUE THREAD

**Issue by timsuchanek** [microsoft/TypeScript#30507] opened 2019-03-20 12:48 UTC
As #30212 has been closed incorrectly (it's not a duplicate) and the comments there are not reacted on anymore, I reopen the issue here.

- VSCode Version: Version 1.31.1 (1.31.1)
- OS Version: macOS High Sierra 10.13.6

Steps to Reproduce:

![typescript autocompletion](https://user-images.githubusercontent.com/1094804/53742843-de2e3780-3e99-11e9-8cec-d85a28736f91.gif)

Open a TypeScript file with this content:

```ts
type Params = {
  foo?: string
  bar?: number
  visible?: boolean
}

export const obj = {
  paramsIdentityInline<T extends Params>(params: T): T {
    return params
  },
}

obj.paramsIdentityInline({
  
})

function direct(params: Params) {}

direct({

})
```

When you have a type which only consists of optional properties and use it in a generic context as a type parameter, the autocompletion doesn't work, while it works when you use that type directly without being generic in the function signature.
However, as soon as at least one of the properties on that type is non-optional, the autocompletion works, even for the optional properties.

Does this issue occur when all extensions are disabled?: Yes

As @hediet correctly notes, the referenced fix doesn't work for this bug.
Please see #30212 for more infos.

Ping @mjbvz

**Comment by RyanCavanaugh** [comment] 2019-03-26 16:42
The problem here is that `{}` is a valid `Params`, so we think this is just a call to `obj.paramsIdentityInline<{}>` and the **correct** suggestion list is therefore empty. From a type system perspective, that's justifiable.

This doesn't happen when there's a required property because the inference fails to produce a successful call, so we defer to the constraint for error reporting purposes and the constraint does have the properties. Notice that once the required property is present, we go back to showing the completions from the inferred type:
![image](https://user-images.githubusercontent.com/6685088/55016025-2cbb8700-4fab-11e9-9819-2532625c63e8.png)

The "fix" is probably just a bunch more special-casing in the services layer.

**Comment by RyanCavanaugh** [comment] 2019-04-12 21:10
Not soon, no.

**Comment by schickling** [comment] 2019-04-13 10:32
Does TypeScript have a bounty program in case someone wants to pick it up? Any thoughts on how much effort a fix for this would be?

**Comment by leonardodino** [comment] 2019-05-16 22:13
This kind of issue also degrades a a bit the development experience for me.

created a reproduction at [TypeScript Playground](https://www.typescriptlang.org/play/#src=type%20Params%20%3D%20%7B%20foo%3F%3A%20string%3B%20bar%3F%3A%20number%3B%20visible%3F%3A%20boolean%20%7D%0D%0A%0D%0Aexport%20const%20obj%20%3D%20%7B%0D%0A%20%20paramsIdentityInline%3CT%20extends%20Params%3E(params%3A%20T)%3A%20T%20%7B%0D%0A%20%20%20%20return%20params%0D%0A%20%20%7D%2C%0D%0A%7D%0D%0A%0D%0Afunction%20direct(params%3A%20Params)%20%7B%20%7D%0D%0Aconst%20indirect%20%3D%20%3CT%20extends%20Params%20%3D%20Params%3E(params%3A%20T)%3A%20T%20%3D%3E%20params%0D%0A%0D%0A%2F%2F%20working%20auto-completion%20(mac%3A%20ctrl%2Bspace%2C%20inside%20curly-brackets)%0D%0Adirect(%7B%20%C2%A0%20%7D)%0D%0A%0D%0A%2F%2F%20not%20working%0D%0Aobj.paramsIdentityInline(%7B%20%20%7D)%0D%0A%0D%0A%2F%2F%20also%20not%20working%0D%0Aindirect(%7B%20%20%7D)%0D%0A) and added another case.
The function being a property on an object doesn't change the auto-complete outcome at all.

---

Assuming I'm to fix this issue, is there any pointers where this kind of functionality is to be implemented?

Considering it provides autocomplete on error, even on the generic ones, there should be a way to reuse that code path, or am I missing something here?

**Comment by timsuchanek** [comment] 2019-06-26 08:00
Opened a PR to fix this https://github.com/microsoft/TypeScript/pull/32100

**Closed** 2019-10-17 17:45 UTC
Labels: Experience Enhancement, Suggestion
