### ISSUE TITLE
Error class to support native error cause

### ISSUE THREAD

**Issue by MahmoudEzzatAbdul-Rahman** [microsoft/TypeScript#47506] opened 2022-01-19 09:10 UTC
# Suggestion

## 🔍 Search Terms

Error Native Cause Stacktrace

## ✅ Viability Checklist

My suggestion meets these guidelines:

* ✅ This wouldn't be a breaking change in existing TypeScript/JavaScript code
* ✅ This wouldn't change the runtime behavior of existing JavaScript code
* ✅ This could be implemented without emitting different JS based on the types of the expressions
* ✅ This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* ✅ This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Error class constructor should support native error cause as per new ECMAScript standards

## 📃 Motivating Example
https://v8.dev/features/error-cause

## 💻 Use Cases
Implementing custom business errors which extend the base Error class while supporting error cause as another error natively, while capturing the stacktrace correctly for both errors.

**Comment by MartinJohns** [comment] 2022-01-19 09:13
Duplicate of #47019. Used search terms: `error cause in:title`

**Closed** 2022-01-19 10:42 UTC
