### ISSUE TITLE
Signature help shouldn't activate in a comment

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#20828] opened 2017-12-20 22:17 UTC
**TypeScript Version:**  typescript@2.7.0-dev.20171220

**Code**

```ts
const mySet = new Set([
    {
        x: [
            1,
            // A comment
        ],
    },
]);
```

Go to the end of the line after `// A comment` and type ` (`

**Expected behavior:**

Lets me continue typing a comment.

**Actual behavior:**

I get signature help for the `new Set`. This probably isn't relevant as I'm not writing a new argument to the constructor, just commenting something deeply nested inside it. We could try to detect the current position and only provide signature help when the cursor is at a new argument.

**Comment by DanielRosenwasser** [comment] 2017-12-22 08:52
Seems effectively like a duplicate of #1150.

**Closed** 2018-01-02 19:59 UTC
Labels: Duplicate
