### ISSUE TITLE
Static property is possibly undefined but error is not caught

### ISSUE THREAD

**Issue by millsp** [microsoft/TypeScript#42148] opened 2020-12-29 21:08 UTC
# Bug Report

### 🔎 Search Terms

static property error undefined

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about static properties

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8BQ1XQBYFMQgPYAoBKRAXyTKVEhgCFEU0IAXMJgS2GjAC45ykkNAHRghWHAUJIgA)

### 💻 Code

```ts
class A {
    hello() {}
}

class B {
    static a: A
}

B.a.hello() // crash
```

### 🙁 Actual behavior

Crash because ts assumed that the static property was not undefined

### 🙂 Expected behavior

Either require a definite assignment assertion or an inline assignment

**Comment by MartinJohns** [comment] 2020-12-29 21:10
Duplicate of #27899. Search terms: `static undefined`

**Closed** 2020-12-29 21:14 UTC
