### ISSUE TITLE
Add Regex String Types

### ISSUE THREAD

**Issue by NightshadeX9X** [microsoft/TypeScript#43048] opened 2021-03-02 18:36 UTC
# Add Regex String Types
## ⭐ Suggestion
I'd like to see Regex types be added into typescript. This would allow us to create types for specific necessary strings. I feel like  adding template literal types was a step in the right direction, but this would be even better.

## 📃 Example
```js
type AllUppercase = /^[A-Z]+$/;

let myLowercaseVariable: AllUppercase = "test"; // error
let myUppercaseVariable: AllUppercase = "TEST"; // works
```

**Comment by MartinJohns** [comment] 2021-03-02 18:52
Duplicate of #41160. Used search terms: `regex in:title`

You forgot to fill out the issue template.

**Closed** 2021-03-03 19:38 UTC
Labels: Duplicate
