### ISSUE TITLE
low memory detected, full analysis disabled for this solution

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#8152] opened 2016-04-18 19:47 UTC
nightly build, vs2015 + update 2

![image](https://cloud.githubusercontent.com/assets/937933/14617590/c62b5d10-057c-11e6-8c59-bb7bd89cf7b0.png)

**Comment by mhegazy** [comment] 2016-04-18 19:49
any more details you can share?

**Comment by aleksey-bykov** [comment] 2016-04-18 19:54
willing to run any test you give me

**Comment by mhegazy** [comment] 2016-04-18 19:56
do you have other C#/VB files in the solution? or just TS? any other extensions like resharper?

**Comment by aleksey-bykov** [comment] 2016-04-18 20:00
no C#, VB or Resharper, clean VS2015 no nothing


here are the project files:


[Intelsat.APS.Web.AB.zip](https://github.com/Microsoft/TypeScript/files/224688/Intelsat.APS.Web.AB.zip)

**Comment by rbmanian75** [comment] 2016-05-12 11:27
We are also getting this issue. We have 687 typescript files in out project and when we start editing type script file the memory usage of visual studio is constantly increasing and finally we get low memory detected error and visual studio crashes. before installing the update KB3151378 https://msdn.microsoft.com/en-us/library/mt695655.aspx we were not having this issue. But after installing working with typescript file is impossible. it always crashes visual studio. If you could tell us what kind of more information you need we could be able to provide with that info.

Thanks

**Comment by aleksey-bykov** [comment] 2016-05-12 11:31
a nasty workaround: as soon as you see the message you need to close the VS and open it to get it reset, this way you can save the set of open tabs you are working on, if you don't do this it will crash and your set of tabs going to get lost

also consider trying VS Code (new editor from MS) which looks more stable and has almost all features that VS has

**Comment by rbmanian75** [comment] 2016-05-12 13:05
We gave up on using typescript with vs 2015 update 2 because of the crashing issue. as suggested we are using vs code for editing typescript files with our projects. 

thanks

**Comment by mhegazy** [comment] 2016-05-20 06:01
> We gave up on using typescript with vs 2015 update 2 because of the crashing issue. as suggested we are using vs code for editing typescript files with our projects.

@rbmanian75 we would love to identify and fix these issues. can you share more details about the issues you are running into? can you share crash dumps? do you have any error stacks in your event viewer?

**Comment by rbmanian75** [comment] 2016-05-20 09:19
Thank you for the reply.

Here is the crash log collected using debugdiag
[devenv__PID__24472__Date__05_20_2016__Time_10_10_19AM__670__Log.zip](https://github.com/Microsoft/TypeScript/files/274241/devenv__PID__24472__Date__05_20_2016__Time_10_10_19AM__670__Log.zip)

If you need any other info please let us know.

**Comment by mhegazy** [comment] 2016-05-20 23:07
Most of these exceptions are handled, and the interesting ones do not have a stack. if VS crashed you should see an event in the event viewer, ideally with a CLR stack, can you share that?

also if you can consistently get this to reproduce we would love to take a look at your project sources. we would be happy to sign any NDA required to get access to the code.

**Comment by rbmanian75** [comment] 2016-05-23 08:43
This is what logged in the event viewer.

Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass14_0.<ContinueWithAfterDelay>b__0(Task t)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass6_0`1.<SafeContinueWith>b__0(Task t)
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass6_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SafeContinueWith>b__0(System.Threading.Tasks.Task)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass14_0.<ContinueWithAfterDelay>b__0(System.Threading.Tasks.Task)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass6_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SafeContinueWith>b__0(System.Threading.Tasks.Task)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticEventTaskScheduler.Start()
   at Roslyn.Utilities.TaskFactoryExtensions+<>c__DisplayClass1_0.<SafeStartNew>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.LongRunningThreadWork(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)


The crash is consistent. It always happens when we opne a typescript file.We can send you the source code. could you please share the email id. so that we can send you the source. We cant share it public.

Thanks

**Comment by mhegazy** [comment] 2016-05-23 17:08
We would love to take a look. email, `mhegazy` at `microsoft` dot `com`

**Comment by rbmanian75** [comment] 2016-05-24 08:33
We have noticed one thing. the 687 type script files are part of a very big asp.net VS solution. When we open the typsescript files folder only as open web site in visual studio and working on that everything is fine. When the typescript files are part of our solution only causing the issue. We wont be able to send the complete solution is to you. We can only send the typescript files. Will that be helpful. We are asking this only having typescript files in an empty asp.net project does not seems to be causing the issue.

**Comment by mhegazy** [comment] 2016-05-24 16:34
Thanks, a few follow up questions:
- do you have other extensions loaded? resharper? 
- in the empty project with only TS files, what is the memory consumption of VS after you open a file and the CPU spike to get diagnostics is over? 
- if the full solution, what is the memory consumption if you do not open any .ts files, just C# files?
- are all the ts files in one project? or multiple?
- do you have any tsconfig.json files?
- can you share the output of `tsc --diagnostics` on your project?

**Comment by rbmanian75** [comment] 2016-05-24 16:50
do you have other extensions loaded? resharper?
----------- No we dont have any extensions loaded

in the empty project with only TS files, what is the memory consumption of VS after you open a file and the CPU spike to get diagnostics is over?
--------- 360 MB CPU spikes up to 10% and goes to 0%

if the full solution, what is the memory consumption if you do not open any .ts files, just C# files?
--------700MB

If we open the  typescript file the cup spikes above 25% and the memory goes upto 3gb and then VS is crashing

are all the ts files in one project? or multiple?
-------all the ts files in one projects.

do you have any tsconfig.json files?
-------No we dont have tsconfig.json

can you share the output of tsc --diagnostics on your project?
-------------------------------------------------------------------------------
Files:               1
Lines:           17309
Nodes:           77357
Identifiers:     29805
Symbols:         22229
Types:            4339
I/O read:        0.00s
I/O write:       0.00s
Parse time:      0.14s
Bind time:       0.08s
Check time:      0.28s
Emit time:       0.01s
Total time:      0.51s
----------------------------------------------

**Comment by mhegazy** [comment] 2016-05-24 16:59
>If we open the typescript file the cup spikes above 25% and the memory goes up to 3gb and then VS is crashing

this is concerning, the ts project size is reasonable, and the 300 MB is what i would have expected. so seeing the memory spike is definitely a bug that we need to address. 
can you take a heapdump when memory starts to go above the 2 GB mark, using procdump (https://technet.microsoft.com/en-us/sysinternals/dd996900.aspx)

**Comment by rbmanian75** [comment] 2016-05-24 17:19
Here goes the dump [Dump File](https://onedrive.live.com/redir?resid=505EC563B182FA09!1210&authkey=!AOmvSnpiIf9z0QU&ithint=file%2czip)

**Comment by aleksey-bykov** [comment] 2016-05-24 17:23
i am coming back to the party

> do you have other extensions loaded? resharper?

no, no

> if the full solution, what is the memory consumption if you do not open any .ts files, just C# files?

- before opening a project: 77 MB
- after opening the project: 137 MB
- after opening a first TS file: 590 MB

> are all the ts files in one project? or multiple?

one project

> do you have any tsconfig.json files?

yes, one single one

> can you share the output of tsc --diagnostics on your project?
```
  Files:            1225
  Lines:          217892
  Nodes:         1025018
  Identifiers:    383113
  Symbols:        438286
  Types:          145642
  Memory used:   907597K
  I/O read:        0.14s
  I/O write:       0.69s
  Parse time:      3.42s
  Bind time:       1.33s
  Check time:     10.36s
  Emit time:       3.10s
  Total time:     18.21s
```

**Comment by vladima** [comment] 2016-05-24 17:36
@rbmanian75 can you please make a full process dump (`-ma` in procdump)?

**Comment by rbmanian75** [comment] 2016-05-25 09:07
Here goes the full process dump [Full Process Dump](https://drive.google.com/file/d/0BwzcfBk7y2XoQnNOam9EU0cyS3M/view?usp=sharing)

**Comment by vladima** [comment] 2016-05-25 17:19
@rbmanian75 can you please make one more full dump - last one was made in the middle of GC and not suitable for analysis?

**Comment by rbmanian75** [comment] 2016-05-30 09:44
@vladima  Here goes the second dump [Full Process Dump](https://onedrive.live.com/redir?resid=505EC563B182FA09!1211&authkey=!APa79felM5lSqWc&ithint=file%2czip). Sorry for the delay. I was on holidays last week.

**Comment by vladima** [comment] 2016-05-31 18:58
@rbmanian75 no worries. Also can you please make one more full dump when memory usage will be around 1.5GB?

**Comment by rbmanian75** [comment] 2016-06-01 09:29
@vladima Here it goes [Process Dump at 1.5GB](https://onedrive.live.com/redir?resid=505EC563B182FA09!1213&authkey=!AJqpHP5M1J56oY8&ithint=file%2czip)

**Comment by vladima** [comment] 2016-06-01 20:00
It looks like a [known issue](https://github.com/dotnet/roslyn/issues/7082 ) that should be fixed in the next VS update. As a workaround you can disable solution wide analysis by unchecking `Tools` -> `Options` -> `Text Editor` -> `C#` -> `Advanced` -> `Enable full solution analysis`.

**Comment by rbmanian75** [comment] 2016-06-02 08:43
We have already tried disabling full solution analysis. It does not help. This happens for typescript files only. Does roslyn code analsysis kicked for typescript files also? We dont get it.

**Comment by mhegazy** [comment] 2016-06-07 22:22
@CyrusNajmabadi and @heejaechang any ideas what is going on here and why disabling full solution analysis does not help?

**Comment by heejaechang** [comment] 2016-06-07 22:36
can they try https://www.visualstudio.com/en-us/news/2014-jul-2-vs.aspx this? to see whether update 3 has addressed the issue?

...

a lot of pending task issue should have been addressed in update 3.

**Comment by SwintDC** [comment] 2016-06-08 08:16
I have the same issue. Is there any progress with this issue ? Are there any other known workarounds ?
**solution wide analysis** was already disabled for C# in my options, so this was no workaround for me.

**Comment by SwintDC** [comment] 2016-06-08 09:05
Hopefully i can help with another memory dump:

I made the procdump (used command: procdump -ma 6588) after the CPU spike, see screenshot
![image](https://cloud.githubusercontent.com/assets/18047780/15887563/399ef758-2d63-11e6-8688-ded71a1f0fa2.png)

The dump: [link](https://drive.google.com/file/d/0B3Ag90Cc-LchRzhIa1d1dUd4ckk/view?usp=sharing)

**Comment by heejaechang** [comment] 2016-06-08 09:05
@SwintDC can you try the RC released yesterday to see whether the problem still exist?

**Comment by SwintDC** [comment] 2016-06-08 09:11
@heejaechang Yes, i will install it and report back. Because you first linked VS 2013 Update 3 RC, i wrongly thought you meant the update for 2013. But i found the Update 3 RC for VS 2015 and installed this one.

**Comment by heejaechang** [comment] 2016-06-08 09:18
@SwintDC oops, sorry. I updated url.

**Comment by heejaechang** [comment] 2016-06-08 09:19
for managed memory, I see these as biggest memory consumer.

1efa0b0c      183      1235908 Roslyn.Utilities.BKTree+Edge[]
2e4a22d4    53615      1286760 System.Collections.Concurrent.ConcurrentDictionary`2+Node[[System.Reflection.Metadata.TypeDefinitionHandle, System.Reflection.Metadata],[Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp]]
72e3ed0c    27679      1357504 System.Object[]
1e23d6fc    41680      2000640 System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[System.Collections.Immutable.ImmutableArray`1[[Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.CSharp]], System.Collections.Immutable]]
1efa09f0      183      2236572 Microsoft.CodeAnalysis.FindSymbols.SymbolTreeInfo+Node[]
1efa168c      183      2472532 Roslyn.Utilities.BKTree+Node[]
1e6a2b64    50002      4200168 Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol+PENamedTypeSymbolNonGeneric
1e6a5cc8    82845      4307940 Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEParameterSymbol
1e6a4ad8    63781      4337108 Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEFieldSymbol
1e6a568c    68975      4690300 Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEPropertySymbol
72e40764    80354      5409340 System.Int32[]
72e28a40    12015      5544014 System.UInt16[]
72e435fc    16905      6320086 System.Byte[]
72e3f320      967      7772752 System.Char[]
2fc181f4    37982      7808616 System.Collections.Generic.Dictionary`2+Entry[[System.String, mscorlib],[System.Collections.Immutable.ImmutableArray`1[[Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.CSharp]], System.Collections.Immutable]][]
1e6a0f8c   423365      8630704 Microsoft.CodeAnalysis.CSharp.Symbol[]
1e6a5270   273416     14217632 Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEMethodSymbol
02a6bc00   199109    133881098      Free

72e3e918   408731    268986188 System.String

some of them should have been addressed in update 3. for string, I think typescript team has done something I believe? @vladima for update 3?

**Comment by heejaechang** [comment] 2016-06-08 09:48
@vladima I don't see any big memory consumption related to diagnostics, and those BKTree related memory should have been addressed in update 3. but that is still quite small memory compared to 2.5GB of unknown memory usage. among those 2.5GB only 500MB is managed. other 2GB seems due to something else. I remember something about those related to typescript on other thread. do you remember what that was?

**Comment by SwintDC** [comment] 2016-06-08 12:06
It's not solved with the update.
As soon as i open a typescript file in the solution my CPU starts peeking to 50% and Visual Studio gradually uses more memory until it reaches around 2.5GB.
It hasn't crashed though yet.

**Comment by heejaechang** [comment] 2016-06-08 18:30
@SwintDC can I have dump again?

**Comment by SwintDC** [comment] 2016-06-09 12:36
Another dump (after CPU peek, when memory usage was high >2GB):
[link](https://drive.google.com/open?id=0B3Ag90Cc-LchX2pWY3VZSmkwQVE)

**Comment by ihsw** [comment] 2016-06-28 19:13
Just want to chime in that I am also experiencing the same issue.

* full code analysis is disabled
* running VS 2015 in safe mode works but obviously no Node/TypeScript projects compile
* VS 2015 memory usage continues climbing and it becomes so unstable (flashing Not Responding) until it crashes
* using VS 2015 Update 3

**Comment by mhegazy** [comment] 2016-06-28 19:18
@heejaechang any ideas?

**Comment by heejaechang** [comment] 2016-06-28 19:58
we found a leak where we are leaking preview window and preview workspace in certain cases. we are planning to release the fix on next micro-update. meanwhile, let me see whether we can share that nightly fix with you to see whether that address the issue you are seeing.

**Comment by SwintDC** [comment] 2016-06-29 07:57
Since we changed our tsconfig.json (see below) Visual Studio doesn't crash as often anymore, and it also doesn't use as much memory anymore.

**tsconfig.json: before**
{
  "compilerOptions": {
    "declaration": true,
    "noImplicitAny": true,
    "noEmitOnError": false,
    "module": "amd",
    "target": "es5"
  },
  "exclude": [
    "**/src/defs",
    "**/*.d.ts"
  ]
}

**tsconfig.json: after**
{
  "compilerOptions": {
    "declaration": true,
    "noImplicitAny": true,
    "noEmitOnError": false,
    "module": "amd",
    "target": "es5"
  },
  "files": [
      "ProjectA/lib/**/*.ts",
      "ProjectA/ts/**/*.ts"
  ]
}

**Comment by mhegazy** [comment] 2016-09-20 23:16
@aleksey-bykov and @SwintDC, is this still an issue?

**Comment by aleksey-bykov** [comment] 2016-09-20 23:55
no

**Comment by SwintDC** [comment] 2016-09-29 12:17
No, it doesn't crash anymore. Thanks !

**Closed** 2016-09-29 17:25 UTC
Labels: External
