### ISSUE TITLE
Add support for structuredClone

### ISSUE THREAD

**Issue by BenRacicot** [microsoft/TypeScript#47312] opened 2022-01-04 16:54 UTC
A very needed deep-cloning tool [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) has made it to Chrome's nightly builds. However usage gives an error 

`Cannot find name 'structuredClone'.ts(2304)`

Can we support it in 4.6?

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2022-01-04 17:11
Duplicate of https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1237.

**Comment by BenRacicot** [comment] 2022-01-04 18:40
Thanks @MartinJohns, I had searched for dups within this project. Thanks for linking.

**Closed** 2022-01-04 22:46 UTC
Labels: Duplicate
