### ISSUE TITLE
Type narrowed too much

### ISSUE THREAD

**Issue by fjolliton** [microsoft/TypeScript#57880] opened 2024-03-21 11:46 UTC
### 🔎 Search Terms

type narrowing local variable

### 🕗 Version & Regression Information

I don't see anything related in the FAQ. But I acknowledge that this seem too common to be unknown. Every version seem affected however.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.2#code/MYewdgzgLgBMCGAbRMC8MAUAzAXJglGgHwwBuIAlgCaGolYb4DcAUC6JLFAKbRoHEYAbxYwxMRN1jw8AVzBVuWCmG5UYAHxhhZAWwBG3AE795i5aqqtxMAPS2YAFQCeAB17AjFV7AjduuhAwUCAwhnAguq6SPIjOMPLwAO7wRtzBABbwXBnppEiy3KLi9jAgWDAABvCVcPBgcFlgAObpKpnpWCDIIEkqzXXIAHTFYgjIGIyCQjDw-ACMTDAAvsyjdg4AggodaQA0MBS+UBTImSoA1pnZVTV1DeBx66WuIBAQFPpxYemVZkoqNSVEY2CgVDBzACEqHQ-wsakIIhsNlKUAyFCCiEBMFasDSACtuMAeFR1jZ4EMQgBlKBeFqMaziZYsZasIA

### 💻 Code

```ts
const call = (f: () => void) => f();

const test = () => {
    let a: undefined | number = undefined;
    // Typescript seems to be completely unaware that the value
    // of `a` can change in the following call.
    call(() => { a = 1; });
    // And there, it still think that `a` can only
    // possibly be `undefined`.
    if (a !== undefined) {
        // this line get rejected
        a.toString();
    }
};
```

### 🙁 Actual behavior

It seems that Typescript is not considering a function call to affect local variable. It proceed to narrow the type from this limitation, and thus reject valid code.

Not assigning `undefined` to `a` causes the error to disappear *BUT* this is still a problem, because I might want a default value here (could be a number initially, that later get changed to undefined for example).

For example, and this is worse:

```ts
const call = (f: () => void) => f();

const test = () => {
    let a: undefined | number = 42;
    call(() => {
        a = undefined;
    });
    a.toString();
};
```
This will compile fine, but it will fail at runtime! 

### 🙂 Expected behavior

The type should not be narrowed in this case.

Typescript should detect that a closure is referencing a local variable, and thus, should avoid narrowing its type.

**Comment by MartinJohns** [comment] 2024-03-21 11:51
Another duplicate of #9998.

**Comment by fjolliton** [comment] 2024-03-21 12:03
Is there anything to prevent to narrow such types? (a configuration option or a directive to put somewhere)

**Comment by MartinJohns** [comment] 2024-03-21 12:10
No. It's all written in that issue. You can use a type assertion to prevent the initial narrowing: `42 as undefined | number`.

**Comment by craigphicks** [comment] 2024-03-23 00:27
Note: Typescript is aware that the value of `a` can change in a synchronous IIFE 
```
const test = () => {
    let a: undefined | number = undefined;
    // Typescript is aware that the value of `a` can change in a synchronous IIFE
    (() => { a = 1; })();
    let b = a; // number
    console.log(b);
};
test();
```

**Comment by fatcerberus** [comment] 2024-03-23 23:18
@craigphicks Yes, IIFEs are special-cased: since the compiler can readily see from the syntax that the function will always be called immediately, it's treated the same as if the code was written inline.

**Closed** 2024-03-26 01:24 UTC
Labels: Duplicate
