### ISSUE TITLE
add codefix for stub method/function

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#13094] opened 2016-12-21 14:54 UTC
offer a codefix as an option (among others, for example importing) that would create a stub of a function or method, when undeclared identifier is used in a call expression

**Comment by mhegazy** [comment] 2017-05-06 00:38
duplicate of https://github.com/Microsoft/TypeScript/issues/10140

**Comment by mhegazy** [comment] 2017-05-22 22:35
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-05-22 22:35 UTC
Labels: Duplicate
