### ISSUE TITLE
Using a setter causes type inference failure

### ISSUE THREAD

**Issue by csnover** [Microsoft/TypeScript#6000] opened 2015-12-08 20:24 UTC
Code:

```ts
const a = {
	b: {
		get foo(): string {
			return a.foo;
		},
		set foo(value: string) {
			a.foo = value;
		}
	},
	foo: ''
};
```

Expected: Type of 'a' is correctly inferred to be `{ b: { foo: string; }; foo: string; }`
Actual: error TS7022: 'a' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer"

Version: 1.7.3

Using a regular member function instead of a setter allows type inference to succeed:

```ts
const a = {
	b: {
		foo(value: string) {
			a.foo = value;
		}
	},
	foo: ''
};
```

**Comment by sandersn** [comment] 2015-12-09 21:35
@ahejlsberg, you said you know the cause of the problem and the fix, so I'm assigning to you.

The problem is that we delay body checking for functions until after the object literal has been checked, but not for the bodies of getters and setters.

**Closed** 2015-12-12 23:45 UTC
Labels: Bug
