### ISSUE TITLE
[Feature request] keep comment in declaration when removeComments = true

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#30307] opened 2019-03-10 12:45 UTC
## Suggestion

keep comment in declaration when `removeComments` = `true`

## Use Cases

because comment in declaration is for api desc

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by j-oliveras** [comment] 2019-03-10 14:24
Duplicate of #26987, #21719 and #14619.

**Closed** 2019-03-12 16:35 UTC
Labels: Duplicate
