### ISSUE TITLE
type narrowing not working in block where the narrowed variable gets reassigned

### ISSUE THREAD

**Issue by fieteboerner** [microsoft/TypeScript#49538] opened 2022-06-14 10:47 UTC
# Bug Report

### 🔎 Search Terms

`while loop`, `narrowing`, `assign`, `reassignment`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?ssl=19&ssc=2&pln=1&pc=1#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgBUwHM8BvAWACg4bEATALjiQFcBbAIzStrhagA2TAM4woyIj1phMUYCgD6CRs3ZcoVAL5Uq2CElFwZJYQ0IkA2gF04AXjjWdlXfsM4YCAG7AAcpk8IRJge+ubAAKqCwnZwABQAlEwAysAwADyi4khEAHx2eRTUtAKpcO5ewGExxsDCAHToyHSxNflGxMB1-AJ2tvYA5AD0MjAAFv3xANxSNHoG8N3R9kjAAO5wKemZEjmx1lMzcKujCCVx5d5h8XCFvLyLdZh0zReVHV2CB0V3Zdgelx1qh16o0kM1WrY8jU6spevZXmE6jI5IplF9eNpnN84HIYPwkHwotNKJogA)

![Screenshot from 2022-06-14 10-43-51](https://user-images.githubusercontent.com/8209685/173559251-2a1cd82e-0380-4119-a6eb-079bc63ffbc8.png)

### 💻 Code

```ts
export interface Page {
    id: number
    url: string
    parent_id: number
}

const pages:Page[] = []


const activeNavigationPageUrls = (): Set<string> => {
    let activePage = pages.find(page => page.url === '/path');
    const urls = new Set<string>([]);
    while (activePage) {
        urls.add(activePage.url);
        activePage = pages.find(page => page.id === activePage.parent_id); // the issue is in the arrow function of this line 
    }

    return urls;
}
```

### 🙁 Actual behavior

the type of the variable is narrowed by the while loop (to type `Page`). But in the line of finding and reassignment the type in the find-method is not narrowed down anymore even though the access in the find method is called before the reassignment has passed.

### 🙂 Expected behavior

the code should not throw a ts warning at all. I would expect the `actualPage` variable is of type `Page` in the find arrow function and after assignment of type `Page | undefined`

**Comment by MartinJohns** [comment] 2022-06-14 10:50
Duplicate of #9998.

See also: 
![image](https://user-images.githubusercontent.com/5269069/173560758-0d057c71-6977-4688-96c8-a22708e14328.png)
https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/types-not-correct-in-with-callback.md

**Closed** 2022-06-16 18:00 UTC
Labels: Duplicate
