### ISSUE TITLE
No Autocompletion for the Empty Object Type

### ISSUE THREAD

**Issue by mariusschulz** [Microsoft/TypeScript#14291] opened 2017-02-24 13:39 UTC
**TypeScript version:** 2.2.1

Currently, the language service doesn't offer any autocompletion when accessing members of objects that are typed as `{}`:

```ts
const obj = {};
obj.  // No autocompletion here :(
```

If `obj` is explicitly typed as `Object`, however, we **do** get autocompletion:

```ts
const obj: Object = {};
obj.  // constructor, hasOwnProperty(), isPrototypeOf(), ...
```

Is that difference in behavior intentional, and if yes, why?

**Comment by mhegazy** [comment] 2017-02-24 19:34
Duplicate of https://github.com/Microsoft/TypeScript/issues/9596

**Closed** 2017-04-19 18:54 UTC
Labels: Duplicate
