### ISSUE TITLE
Symbol type stripped on deferred import

### ISSUE THREAD

**Issue by raijinsetsu** [microsoft/TypeScript#37937] opened 2020-04-13 20:03 UTC
**TypeScript Version:**  3.8.3 and 3.5.3

**Search Terms:**
symbol type
symbol import
symbol deferred

**Code**

impl.ts
```ts
export const MySymbol = Symbol('MySymbol');
export type MySymbol = typeof MySymbol;

export class MyMap extends Map<string | MySymbol, string> {

}
```

working example with normal imports:
```ts
import { MyMap, MySymbol } from './impl';

const map = new MyMap();
map.set(MySymbol,'abc');
```

Non-working example with deferred imports:
```ts
async function main() {

    const {MyMap, MySymbol} = await import('./impl');
    const map = new MyMap();
    map.set(MySymbol,'abc');    
}
```

Alternative impl.ts attempt which also fails:
```ts
export const MySymbol = Symbol('MySymbol');

export class MyMap extends Map<string | typeof MySymbol,string> {

}
```

**Expected behavior:**
I should be able to use the symbol as a key in the map.

**Actual behavior:**
Typescript gives the following error:
`Argument of type 'symbol' is not assignable to parameter of type 'string | unique symbol'.ts(2345)`

I did also attempt to use a type-only import at the top of the file. Typescript, correctly, does not elide the type and the local variable and the type error. Deferred imports are being used for performance reasons. The only work around is to move the symbol to it's own file so it can be imported at the file scope without incurring the performance penalty of importing other files in the same module.

**Comment by rbuckton** [comment] 2020-12-16 23:47
This is related to #32408 and likely requires improvements in `unique symbol` freshness and widening.

**Comment by RyanCavanaugh** [comment] 2022-02-04 19:37
Marking as duplicate of https://github.com/microsoft/TypeScript/issues/32408 until proven otherwise

**Closed** 2022-02-04 19:37 UTC
Labels: Duplicate
