### ISSUE TITLE
Inconsistent behaviour in (trying) to make function arguments optional via generics

### ISSUE THREAD

**Issue by JelleRoets-Work** [microsoft/TypeScript#60482] opened 2024-11-12 10:03 UTC
### 🔎 Search Terms

"function argument optional via generic"

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about "optional function arguments via generics"

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAZgRhgXhgCgIYCcDmAuGANxAEsATAShQD4YBvAXwG4AoUSWLJVRNCpmAHpBMMCBgBTLFhBYWbcNHgAmFDAA8AFTXFy1TLgKaqyWo1bslWVT2V8BwmAFEAHgAcJwKBLIwk2HABXAFsJMCgIABoYACNA2BwQWAAGaIBBMBgAkLDYOFkYAHIAwpgAdwwIUSSYNxlCch8AOnkoAE8PGAAxLR1SMlpUA3wYYxoifotFPIBmAi61APHzBQ4YLBm1OBn7IRExSWlZeUs8gBY1XtRAsDIJOBIwH30Ao0kXb1uqm7uHp98APwTcgwIwmMzMVZWC48M7qH73R7PXaOVweLw+PxZXA5cJRWLxGCJFLpTLZULheAFYq4UoVKpiWB1EANO5kFpsAA2lSqAGluRAIFdgQN6CwYDBTlhAl5ZMMwfQGOL4PLRlQ6MqJVgJFBAlgwKwJUqlacYABrNRPMowfk8lEiNGeby+fw4ikRaJxBI1VIwDLYoLuqlYIolcqVapM+qNdlQzgAVjUZqacHt1UOMjkQA)

### 💻 Code

```ts
const f1 = (arg: void) => {};
const r1 = f1(); // no error

const f2 = <T = void>(arg: T) => {};
const r2 = f2(); // Expected 1 arguments, but got 0, An argument for 'arg' was not provided.

type F<T = void> = (arg: T) => void;
const f3: F = arg => {};
const r3 = f3(); // no error

const f4 = <T = undefined>(arg: T extends undefined ? void : T) => {};
const r4 = f4<undefined>(); // Expected 1 arguments, but got 0, An argument for 'arg' was not provided.

class Klass<T = void> {
  constructor(arg: T) {}
  f(arg: T) {
    return;
  }
}
const k = new Klass(); // Expected 1 arguments, but got 0, An argument for 'arg' was not provided.
const r5 = k.f(); // no error

```

### 🙁 Actual behavior

I would like to have / need some tools to control whether or not a function argument is optional based on context given via generics.

In most cases I still get the TS error `Expected 1 arguments, but got 0`, where I wouldn't expect an error. 
But I could find some (edge) cases where it's working tho, so at least the behaviour is inconsistent (see the example above)

### 🙂 Expected behavior

So in case the type of a function argument resolves into `void` (via a generic type or via conditional resolution), it should be possible to call that function without arguments without getting a TS error.

### Additional information about the issue

Partially related https://github.com/microsoft/TypeScript/issues/29131

**Comment by MartinJohns** [comment] 2024-11-12 10:46
Duplicate of #29131.

**Closed** 2024-11-16 01:32 UTC
Labels: Duplicate
