### ISSUE TITLE
keyof of open interface thinks keys may be numbers

### ISSUE THREAD

**Issue by inad9300** [microsoft/TypeScript#50701] opened 2022-09-09 10:40 UTC
The following code reports that the keys of `I` might be numbers, while in truth they can only be strings:

```ts
interface I {
  b: boolean;
  [more: string]: boolean;
}

function f(s: string) {}

f(null! as keyof I) // Argument of type 'keyof I' is not assignable to parameter of type 'string'. Type 'number' is not assignable to type 'string'.
```

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=8&ssc=20&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgJLIN4ChnIEYBc+A9sQDYRwgDcOyA2gLbFQREDOYUoA5gLpE8pClVoBfLFhgBXEAjDBiIZDAAU7Dl14BKTBKmqQ0smQCEyOO2QBrCAE9iMNNqA)

**Comment by MartinJohns** [comment] 2022-09-09 10:48
You forgot to fill out the issue template.

The behavior is correct. `number` is a valid key for an indexed type.

```typescript
declare const value: I
value[1] = true
```

You can use `Exclude<keyof I, number>` or enable the compiler flag `keyofStringsOnly` if you want the old behavior of `keyof` (which used to be only `string`, see #23592 for details).

**Comment by inad9300** [comment] 2022-09-09 14:12
Does this make sense to you? It seems pretty obvious to me that what the interface is expressing is that _only_ string keys should be allowed. I don't think anybody writing or reading code like that would expect otherwise, unless of course they have already been bitten by this before. Otherwise, what's the point of specifying the type of the key? `interface I { [key: string]: any }` and `interface I { [key: string | number]: any }` would have exactly the same meaning, which is rather awkward.

Though already pointed out in the pull request you linked, notice that the same doesn't happen with numbers, meaning `keyof` correctly restricts the key to be numbers when your interface so indicates it:

```ts
interface NumberMap {
  [key: number]: any;
}

let n1: keyof NumberMap = 42
let n2: keyof NumberMap = '42' // Correctly errors.

interface StringMap {
  [key: string]: any;
}

let s1: keyof StringMap = 42 // Misses what seems to me like an obvious bug.
let s2: keyof StringMap = '42'
```

[Playground link with relevant code](https://www.typescriptlang.org/play?keyofStringsOnly=false#code/JYOwLgpgTgZghgYwgAgHIFcC2AjaBZOAB2QG8AoZZAbQGsIBPALmRC1ygF1m4R6BuMgF8yZADYQwLAIzM69APYw0bfEWQBeZABYATGIksdshouU5VxTQHJdV5AHp7yAMLyoUCAjCj6yaFDcAZwA6EVBIWEQUAGUwKFAAcwJickpaBmZAuMSuZB5+IRFxSUCZZDlTWPiQJLVNXQcnPGBAwIhAvJBkeWwAN2B5dA7sdATQ4uRAo3KTJSrE5I1kGx0rMiA)

It's good to know about the compiler flag, at least, so thanks for that.

**Comment by MartinJohns** [comment] 2022-09-09 14:22
> Does this make sense to you? It seems pretty obvious to me that what the interface is expressing is that only string keys should be allowed.

Yes, it makes sense, because there are no "number" keys in JavaScript. It's always string (or symbol). The keys `2` and `"2"` are the same. Treating them different at type level would be confusing.

**Comment by MartinJohns** [comment] 2022-09-09 14:28
See also: [StackOverflow: What does a TypeScript index signature actually mean?](https://stackoverflow.com/a/58458309)

**Comment by inad9300** [comment] 2022-09-09 16:32
I don't quite see how that reasoning holds. TypeScript is as much a superset of JavaScript as it is a subset. It's point is precisely to forbid error-prone JavaScript patterns. The fact that `'3' > 2` is allowed and `true` in JavaScript doesn't prevent TypeScript from emitting an error when it encounters that likely-buggy expression.

It's a terrible idea to let people type their indexed type keys as `string`, then silently make them behave as `string | number`. If you want to let this awful JavaScript reality surface, then at least enforce consistency in people's programs and make them type `string | number` or something, no? Like, who's going to read "string" and think "ah, yeah, that means string or number"? Nobody shouldn't, or at least that's what I think at the moment.

**Comment by fatcerberus** [comment] 2022-09-09 18:20
This is working as intended and a duplicate of #48269 (and likely others).  Per the TS 2.9 release notes as well as the description of the feature as originally implemented in #23592:

> Given an object type `X`, `keyof X` is resolved as follows:
>
> * If X contains a string index signature, **`keyof X` is a union of `string`, `number`, and the literal types representing symbol-like properties**, otherwise
> * [snip]

We could argue soundness and consistency all day long, but at the end of the day the feature was implemented this way deliberately and it seems unlikely such a large breaking change would be made to the behavior now.

**Comment by inad9300** [comment] 2022-09-11 04:51
I understand you have a massive number of tickets to churn thorough, and a very complex project to take care of. I apologize for the duplicate. I understand it even if the final decision, all trade-offs considered, is to not introduce a breaking change (even though you do this all the time). What gets me, though, is how easy it seems for you to close off into a “it is the way it is” position. The fact that there are duplicate tickets alone should be an indication that people are not expecting this behavior. It would be nice to see at least a modest recognition that the current state of affairs isn’t the most fortunate.

Once you open up to solutions, there might be others besides a broad breaking change. For example, turning on `keyofStringsOnly` by default when in strict mode. Or something as simple as improving the documentation to more clearly cover this specific unexpected behavior. But for that one needs to be genuinely interested in listening to people and in improving things.

**Comment by MartinJohns** [comment] 2022-09-11 05:25
> For example, turning on `keyofStringsOnly` by default when in strict mode.

`strict` mode is for stricter type checking. Enabling `keyofStringsOnly` would be the opposite.

**Closed** 2022-09-13 18:00 UTC
Labels: Duplicate
