### ISSUE TITLE
Decorated classes should implement the decorator return type.

### ISSUE THREAD

**Issue by pietschy** [Microsoft/TypeScript#5627] opened 2015-11-12 00:12 UTC
This is strongly related to #4881 but I'm not sure if it's feature request or if it's really a bug. Given that the Decorators spec states the decorator can return a new constructor function, it sort of seems like it should work.

The following example uses constructor function types and very nearly works. 

[View this in playground](http://www.typescriptlang.org/Playground#src=interface%20ConstructorFunction%3CT%3E%20%7B%0D%0A%20%20%20%20new%20(...args%3Aany%5B%5D)%3AT%3B%0D%0A%20%20%20%20prototype%3AT%0D%0A%7D%0D%0A%0D%0Ainterface%20Disappearing%20%7B%0D%0A%20%20%20%20isVisible()%3Aboolean%3B%0D%0A%20%20%20%20vanish()%3Avoid%3B%0D%0A%7D%0D%0A%0D%0Afunction%20Disappearing%3CT%3E(ctor%3AConstructorFunction%3CT%3E)%3AConstructorFunction%3CT%20%26%20Disappearing%3E%20%7B%0D%0A%20%20%20%20let%20result%20%3D%20%3CConstructorFunction%3CT%20%26%20Disappearing%3E%3Ector%3B%0D%0A%20%20%20%20result.prototype.isVisible%20%3D%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20!this%5B'_hasDisappeared'%5D%3B%0D%0A%20%20%20%20%7D%3B%0D%0A%20%20%20%20result.prototype.vanish%20%3D%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20this%5B'_hasDisappeared'%5D%20%3D%20true%3B%0D%0A%20%20%20%20%7D%3B%0D%0A%20%20%20%20return%20result%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20This%20seems%20like%20it%20should%20work%0D%0A%2F%2F%20%40Disappearing%0D%0A%2F%2F%20class%20Cat%20%7B%0D%0A%2F%2F%20%20%20%20%20constructor(private%20name%3Astring)%20%7B%7D%0D%0A%2F%2F%20%7D%0D%0A%0D%0A%2F%2F%20but%20I%20have%20to%20do%20this%0D%0A%40Disappearing%0D%0Aclass%20Cat%20implements%20Disappearing%20%7B%0D%0A%20%20%20%20constructor(private%20name%3Astring)%20%7B%7D%0D%0A%20%20%20%20isVisible()%20%7Breturn%20false%7D%0D%0A%20%20%20%20vanish()%7B%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20let%20ctor%20%3D%20wrappedBlah(Cat)%3B%0D%0Alet%20buster%20%3D%20new%20Cat('Buster')%3B%0D%0Aalert(%60Is%20Buster%20visible%3F%20-%3E%20%24%7Bbuster.isVisible()%7D%60)%3B%0D%0Abuster.vanish()%3B%0D%0Aalert(%60Is%20Buster%20visible%3F%20-%3E%20%24%7Bbuster.isVisible()%7D%60)%3B%0D%0A%0D%0A)

```typescript
interface ConstructorFunction<T> {
    new (...args:any[]):T;
    prototype:T
}

interface Disappearing {
    isVisible():boolean;
    vanish():void;
}

function Disappearing<T>(ctor:ConstructorFunction<T>):ConstructorFunction<T & Disappearing> {
    let result = <ConstructorFunction<T & Disappearing>>ctor;
    result.prototype.isVisible = () => {
        return !this['_hasDisappeared'];
    };
    result.prototype.vanish = () => {
        this['_hasDisappeared'] = true;
    };
    return result;
}

// This seems like it should work
// @Disappearing
// class Cat {
//     constructor(private name:string) {}
// }

// but I have to do this
@Disappearing
class Cat implements Disappearing {
    constructor(private name:string) {}
    isVisible() {return false}
    vanish(){}
}

// let ctor = wrappedBlah(Cat);
let buster = new Cat('Buster');
alert(`Is Buster visible? -> ${buster.isVisible()}`);
buster.vanish();
alert(`Is Buster visible? -> ${buster.isVisible()}`);
```

**Comment by mhegazy** [comment] 2015-11-12 00:18
The issue here is that the tyep system is not aware of any type mutations the decoarator does to the original type. #4881 tracks supporting this. This issue is a duplicate of #4881.

for your scenario.  you use interface/class merging to get what you want:

```ts
@Disappearing
class Cat {
    constructor(private name:string) {}
}

interface Cat extends Disappearing {}

let buster = new Cat('Buster');
buster.vanish();
```

**Closed by mhegazy** 2015-11-12 00:19 UTC

**Comment by pietschy** [comment] 2015-11-12 00:41
Thanks @mhegazy,

I guess I was hoping this  scenario was different since the decorator return types were explicitly defined by the function parameters and return types.

**Comment by mhegazy** [comment] 2015-11-12 01:39
i agree that this is helpful, but that is #4881.
