### ISSUE TITLE
VS navigation from output window to error source is faulty when there are identically named files

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#7174] opened 2016-02-21 11:25 UTC
Hi,

**Version:**  TS 1.8.0-beta/ VS 2015
**Attachment**:  [test.zip](https://github.com/Microsoft/TypeScript/files/139579/test.zip)
**Related:**  Microsoft/nodejstools#700

To reproduce:

* Open up `test.sln` in the attached folder.
* Rebuild the solution.
* Switch to the output window and observe the error "Cannot find name 'bar'".
  (there are two lines printed, but that is issue #7093 and not the subject of this issue)
* Click on the error

This navigates to `app.ts` in the first project, while the error is actually in `app.ts` in the second project.

This appears to only affect NTVS projects. I am reporting this here because the problem only started appearing after 1.8 (i.e. it was not due to a relase on the NTVS side).

**Comment by mhegazy** [comment] 2016-02-23 22:46
The problem is that the compiler will shorten the names of the files in the error list based on the current directory. before it used to be whatever the name the user specified (MSBuild targets always use full path). so now VS is confused which file to open.

The fix should be in the tasks to concatenate the current directory to file names before extracting the errors.

**Comment by paulvanbrenk** [comment] 2016-04-08 23:45
I have a fix for this checked in.

**Closed** 2016-04-08 23:45 UTC
Labels: Bug, Fixed, Visual Studio
