### ISSUE TITLE
Create a Typescript Mimetype

### ISSUE THREAD

**Issue by btd1337** [microsoft/TypeScript#25426] opened 2018-07-04 01:57 UTC
Please add a typescript mimetype on FreeDesktop. Currently **.ts** files are recognize like _text/vnd.trolltech.linguist_ type and VSCode isn't set as default editor for this.

` https://freedesktop.org/wiki/Specifications/AddingMIMETutor/`

**Comment by RyanCavanaugh** [comment] 2018-07-05 20:17
Seems like anyone could do this?

**Comment by weswigham** [comment] 2018-07-05 20:40
The issue is that the `.ts` extension is already associated with the `"video/mp2t"` MIME.

**Comment by btd1337** [comment] 2018-07-07 19:29
shared-mime-info issues should be filed in the freedesktop.org bugzilla.

https://www.freedesktop.org/wiki/Software/shared-mime-info/
https://bugs.freedesktop.org/enter_bug.cgi?product=shared-mime-info

But better than reporting a shared-mime-info issue, the right thing to do for typescript is to submit it to the official IANA registry. From there it propagates to many places, including shared-mime-info. https://www.iana.org/assignments/media-types/

**Comment by kisaragi-hiu** [comment] 2024-08-06 18:07
Right now there is [an open MR in shared-mime-info](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/merge_requests/301) for this.

**Comment by RyanCavanaugh** [comment] 2024-08-06 21:58
Cool! Closing this since this is an external work item

**Closed by RyanCavanaugh** 2024-08-06 21:58 UTC
Labels: Suggestion, Help Wanted, Experience Enhancement
