### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined in 'unescapeLeadingUnderscores' during 'occurrences'

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#22559] opened 2018-03-14 02:54 UTC
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.2
**VSCode Version** 1.20.1
**command requested**: occurrences
**hitting sessions**: 113
**proportion of all sessions**: 0.00805416963649323
**five line hash**: 670421f129664a31d0a365662fd10725
**stack**
```
TypeError: Cannot read property 'length' of undefined
    at unescapeLeadingUnderscores (tsserver.js:9434:18)
    at Object.idText (tsserver.js:9438:16)
    at IdentifierObject.get [as text] (tsserver.js:82347:27)
    at isValidReferencePosition (tsserver.js:70145:36)
    at getReferencesAtLocation (tsserver.js:70191:22)
    at getReferencesInContainer (tsserver.js:70186:21)
    at getReferencesInSourceFile (tsserver.js:70178:24)
    at searchForImportedSymbol (tsserver.js:70038:21)
    at getImportOrExportReferences (tsserver.js:70289:25)
    at getReferencesAtLocation (tsserver.js:70231:17)
    at getReferencesInContainer (tsserver.js:70186:21)
    at getReferencedSymbolsForSymbol (tsserver.js:69904:25)
    at Object.getReferencedSymbolsForNode (tsserver.js:69820:24)
    at Object.getReferenceEntriesForNode (tsserver.js:69660:58)
    at getSemanticDocumentHighlights (tsserver.js:68595:57)
    at Object.getDocumentHighlights (tsserver.js:68584:20)
    at getDocumentHighlights (tsserver.js:83133:42)
    at getOccurrencesAtPositionCore (tsserver.js:83136:46)
    at Object.getOccurrencesAtPosition (tsserver.js:83122:27)
    at IOSession.Session.getOccurrences (tsserver.js:89656:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89272:61)
    at unknown (tsserver.js:90553:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90544:28)
    at IOSession.Session.executeCommand (tsserver.js:90553:33)
    at IOSession.Session.onMessage (tsserver.js:90573:35)
    at Interface.<anonymous> (tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by andy-ms** [comment] 2018-03-14 14:49
Duplicate of #20792
@aozgaa These have the same error, it should be possible to disambiguate them?

**Closed by andy-ms** 2018-03-14 14:50 UTC
Labels: Source: Telemetry
