### ISSUE TITLE
No "Block-scoped variable '...' used before its declaration." error for earlier function call

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#17653] opened 2017-08-07 11:15 UTC
**TypeScript Version:** Playground (2.3.4?)

**Code**

```ts
class Bar {
    constructor() {
        console.log(foo); // BUG: no error
    }
}
const bar = new Bar();

function Bar2() {
    console.log(foo); // BUG: no error
}
const bar2 = new Bar2();

function bar3() {
    console.log(foo); // BUG: no error
}
bar3();

console.log(foo); // error is thrown

const foo = 2;
```

**Expected behavior:**

`"Block-scoped variable 'foo' used before its declaration."` error for the three cases mentioned in the code example.

I don't know if this is out of scope for TypeScript, but maybe flow analysis could catch very simple cases like this:

```ts
function bar() {
    console.log(foo);
}
bar();

const foo = 2;
```

**Actual behavior:**

*No* `"Block-scoped variable 'foo' used before its declaration."` error for the three cases mentioned in the code example.

**Comment by RyanCavanaugh** [comment] 2017-08-07 19:25
Duplicate of #13320

**Comment by donaldpipowitch** [comment] 2017-08-08 06:04
I see, thanks. Well https://github.com/Microsoft/TypeScript/issues/13320 was closed because

> Correctly detecting this in all cases would require all function calls to trace out their call graphs, which would be pretty expensive relative to the number of bugs we'd actually detect.

I don't know how expensive it would be to detect _some_ cases for _some_ function calls? I actually stumbled over this when I re-ordered functions inside one file with no complex code.

**Comment by mhegazy** [comment] 2017-08-22 16:58
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-08-22 16:58 UTC
Labels: Duplicate
