### ISSUE TITLE
Provide Basic Syntax Check for Regular Expression Literals

### ISSUE THREAD

**Issue by graphemecluster** [microsoft/TypeScript#54744] opened 2023-06-22 15:27 UTC
**Edit:** Since someone is complaining about the failure to follow issue templates, I copied the content to https://github.com/microsoft/TypeScript/issues/3432#issuecomment-1604431899. Please continue the discussion in that issue.

<details><summary>Original content</summary>

Previously worked on #51837, I found that TypeScript gives almost no syntax errors for regular expressions. I would like to file a PR about it, thus I am opening this issue for easier tracking.

But before I work on the issue, I would like to hear some opinions from the Team. I am not sure, but I suppose the job of providing syntax check should not be shirked to linters right?

Something I would like to do are:
- Check for duplicated or unknown flags
- Check for unbalanced parentheses, which is the most common mistake people make
- Check for invalid escapes
  But this should be done only for RegExps with `u` or `v` flag, i.e. in `UnicodeMode`, that means if we encounter a `u` or `v` flag we will need to rescan the whole RegExp again (!!) (i.e. redoing what is done in the current `reScanSlashToken` method)
  And to check for invalid [`DecimalEscape`s and k`<GroupName>`s](https://tc39.es/ecma262/#prod-AtomEscape) we will also need to count the number of capture groups and record the names of all named capture groups along the way.

Am I doing too much or too less? I know doing too much may cause serious performace regressions (well, luckily regular expression literals are not that common compared with string literals). It should be better than doing nothing after all though.

</details>

**Comment by MartinJohns** [comment] 2023-06-22 15:59
You forgot to fill out the issue template. Duplicate of #3432.

**Comment by graphemecluster** [comment] 2023-06-22 17:05
It does look like a duplicate, but this issue does cover something more than #3432.
I just want some feedback from the members before I work on a PR. It’s better than working in vain.
And of course I am not forgetting the issue templates, but none of the templates seem appropriate in this case. I don’t think this kind of things should be made mandatory as long as the cause and effect is clearly conveyed. Team members sometimes don’t use them either.

**Comment by fatcerberus** [comment] 2023-06-22 17:13
> I don’t think [the issue template] should be made mandatory as long as the cause and effect is clearly conveyed.

Nonetheless, [they are](https://github.com/microsoft/TypeScript/issues/54703#issuecomment-1597452310) (note the canned response followed by issue closure).  Maintainers will almost invariably ignore issues that don't follow the template.

**Comment by graphemecluster** [comment] 2023-06-23 15:28
I don’t mean to start a dispute, but this is called _Quod licet Iovi, non licet bovi._
Anyway, since _comments to issues_ do not need to follow any templates, I’ve just moved the whole thing to #3432.

**Comment by RyanCavanaugh** [comment] 2023-06-23 16:25
@graphemecluster the reason we ask people to fill out the template is to ensure that people have done their due diligence working through necessary background research. Generally if someone is not willing to do this minimum amount of legwork, they are filing a very low-quality issue, or a duplicate of an existing issue, as occurred here.

**Closed** 2023-06-23 16:25 UTC
Labels: Duplicate

**Comment by graphemecluster** [comment] 2023-06-23 16:54
@RyanCavanaugh I apologize for my faults. I did search for existing things beforehand. To be specific, I firstly searched if there are any PRs related to RegExp. Since no significant PRs exist, I looked over the source code and started to work on it while encountering something to inquiry. So I quickly wrote the issue without other checks. This is the reason why I made the duplication. Please pardon me and comment on #3432.

**Comment by RyanCavanaugh** [comment] 2023-06-23 16:56
No worries, I file dupes sometimes too 😅
