### ISSUE TITLE
Infer callback parameters that has default values

### ISSUE THREAD

**Issue by wesley-at-hl** [microsoft/TypeScript#48934] opened 2022-05-03 15:21 UTC
# Bug Report

### 🔎 Search Terms
`callback`, `default parameter`, `default values` `infer`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `infer`, `callback`, `default param`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220503#code/PTAEAEBcE8AcFMDOwBO8CGBjSoAW7FQBXReAYXQBtKAjLAa1BgVANAFgAoED7sAMyIA7bAEsA9kOKkK1OpnoAeACqh4AD0jwhAE0IAKAHTH0KAOaIAXKyHQA2gF0AlKAC8APhvR3+zFVoM1soANKA68LBWoAAiEdrhItAAMqKIkE5BANxcIDlgkLipoEXooIiiALawlKL8ovA6oABu8CjlkqDi-MU4Beg4aaLUZbjiAO6EBfDFiIhE8HlcgiKQElIk5P7ySiGgAKo+fnKBoPpNVEEuHvsZp+eUl26ee6AA3lygn6BokEQoUkcAgouABfbKcPLFIT8VpoRpsAAGmEkaVA-CE1jOVAA-NYaOJxJQMEIrp58YTiQiuMihKj0W47lQGZAUPNbuSiegpNd7pleJDRNDYQ1WIQEcsxB0NrIgUoOcTQAAfYi6eB1IQNULyrmHLYnLEPUDaqTK4ThdUNUlGgmckmY+54m0K02qi06K3GqmcaV6hT6dFOPmgHgFIpjcQoeiEGjwPwbNFSIqCmEoOGgZGp2OQSjQMoRUz9eA5rgCoWZ+FiiWrKUyX1KYT0ITjIRap063x1+0XFWN5sett2xmGhtNsYkp7Wilcr0+45+g3M1nwdkDif3QPBsCwiNG2PoeP3GY90dCIA)

### 💻 Code
```ts
// a simplified version of useCallback from react
function useCallback<T, U>(callback: (val: T) => U): (val: T) => U {
    return callback
};

// inferred as `const fn: (val?: boolean) => boolean`
const fn = (val = true): boolean => val; // no error

// inferred as `function useCallback<boolean | undefined, boolean>(callback: (val: boolean | undefined) => boolean): (val: boolean | undefined) => boolean`
useCallback(fn);  // no error since fn is inferred separately

// inferred as `function useCallback<unknown, boolean>(callback: (val: unknown) => boolean): (val: unknown) => boolean`
useCallback((val = true): boolean => val); // error because val is unknown
```

### 🙁 Actual behavior

in `useCallback((val = true): boolean => val)`, val is inferred as unknown

### 🙂 Expected behavior

in `useCallback((val = true): boolean => val)`, val is inferred as boolean because it has a default value

**Comment by andrewbranch** [comment] 2022-05-03 19:27
> This changed between versions 3.3 and nightly

> This is the behavior in every version I tried

Which is it?

**Comment by wesley-at-hl** [comment] 2022-05-03 19:29
> > This changed between versions 3.3 and nightly
> 
> > This is the behavior in every version I tried
> 
> Which is it?

I tried every version between 3.3 and nightly and this is the behavior in every version I tried.

**Comment by fatcerberus** [comment] 2022-05-03 19:35
Which means the behavior didn't change between 3.3 and nightly.

**Comment by wesley-at-hl** [comment] 2022-05-03 19:36
> Which means the behavior didn't change between 3.3 and nightly.

Yes, which is why I spent a lot of time searching for existing issues and texts to see if this is due to some limitations, but I can't find any. Looking at the result, I'd say this is definitely a bug.

**Comment by andrewbranch** [comment] 2022-05-03 21:57
I think this is a (much simpler) duplicate of https://github.com/microsoft/TypeScript/issues/41668. I’m honestly not quite sure why that was called a design limitation, but I think this behavior might actually be desirable. Your callback function, lacking parameter type annotations, is _context sensitive_, which means the types flow in from `useCallback`. If there was any other inference source for `T`, it seems it would likely be stronger and you would want `= true` to be checked against it, not a contributor to that inference. It just happens that in this case, that’s the only inference source, so it wouldn’t have hurt to use it. Perhaps parameter defaults could be added as a low priority inference source, but there are a lot of complex interactions going on when inferring type arguments, and adding this could muddy the waters.

**Comment by fatcerberus** [comment] 2022-05-03 22:45
> If there was any other inference source for T, it seems it would likely be stronger and you would want = true to be checked against it, not a contributor to that inference.

In other words...
```ts
function now<T>(callback: (value: T) => void, value: T) {}
now((x = true) => {}, 42);
```
...should be an error because of `= true`, *not* because of `42` (`T` should infer to `number`).

**Comment by fatcerberus** [comment] 2022-05-04 17:19
> It just seem very inconsistent to me that switching the syntax around would have an impact on type inference.

Just as a warning about this line of thinking: in general you can’t really rely on equational reasoning in TS.  For example, distributive conditional types:

```ts
type SN = string | number;
type T = SN extends any ? Array<SN> : never;  // (string | number)[]
type Arrayify<T> = T extends any ? Array<T> : never;
type U = Arrayify<SN>;  // string[] | number[]
```

**Comment by andrewbranch** [comment] 2022-05-04 17:21
👍 Different code be different

**Comment by fatcerberus** [comment] 2022-05-04 17:23
> 👍 Different code be different

Indeed, though I’m still bitter about distributive conditionals because the “naked type parameter” rule is analogous to a function that behaves completely differently depending on whether you pass it a local variable or a parameter.

**Comment by fatcerberus** [comment] 2022-05-04 17:33
I assume the difference in that case is something to do with contextual typing?  That is, it’s trying to contextually type `(x = true) => {}` because it’s being passed to a function but can’t because it’s generic, thus ultimately inferring `unknown`?  Whereas if you assign the callback to a variable first, contextual typing doesn’t apply and it just uses the default value to type `x`.

**Comment by andrewbranch** [comment] 2022-05-04 17:46
Correct. You can observe that by making the callback non-context-sensitive by giving it a type parameter:

```ts
useCallback((val = true): boolean => val);    // val: unknown
useCallback(<_>(val = true): boolean => val); // val: boolean
```

**Comment by fatcerberus** [comment] 2022-05-05 05:24
Hmm, so based on the above, it looks like TS is instantiating `useCallback` first, then using the result of *that* “inference” to contextually type the callback.  If so, that’s a bit unfortunate, because it suggests that `useCallback(x => {})` would just silently default to its `unknown` constraint instead of throwing an implicit-any error as would normally be the case when no context is available for a function expression.

**Comment by wesley-at-hl** [comment] 2022-05-05 13:48
> useCallback(x => {}) would just silently default to its unknown constraint instead of throwing an implicit-any error 

Practically though, `useCallback(x => {})` would still throw errors if you try to use `x` in a non-unknown way.

I'm okay with the `useCallback(<_>(val = true): boolean => val);` approach as that gives me control over how I want ts to infer the values, though personally I think that, since js code evaluates inner expressions first, it would make more sense for ts to infer using the inner expression first,

**Comment by andrewbranch** [comment] 2022-05-05 15:59
I wasn’t suggesting adding a useless type parameter as a workaround; it just provides an interesting lens into the implementation details of the compiler. I would suggest giving `val` a type annotation, as you would any other time a function parameter cannot be inferred from context.

**Comment by fatcerberus** [comment] 2022-05-05 16:06
> I would suggest giving val a type annotation, as you would any other time a function parameter cannot be inferred from context.

To be fair: Giving a default value to a parameter is *usually* enough to infer the parameter's type in cases where contextual typing doesn't apply (e.g. `const foo = /* arrow function */`.  The issue here is that contextual typing *does* apply, which isn't immediately obvious.

**Comment by wesley-at-hl** [comment] 2022-05-05 16:06
`eslint` has a [no-inferrable-types](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-inferrable-types.md) rule which usually makes sense, but would complain in this case. I know this is something `eslint` is supposed to (try to) fix, but for now the useless type parameter seems to be the cleanest way to make both `ts` and `eslint` ~shut up~ happy.

**Closed** 2022-05-07 18:00 UTC
Labels: Duplicate
