### ISSUE TITLE
Intersection types are not valid index signature types

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#5599] opened 2015-11-10 23:12 UTC
For example, a variable of type
```ts
type Path = string & { __pathBrand: any };
```
cannot be used as an indexer type, and cannot be used to index an object with a `string` type indexer (despite being safely usable as a `string` in all other locations).

If an intersection type contains types which are valid for use in an index signature, then the intersection type itself should probably be valid as an index signature.

**Comment by ivogabe** [comment] 2015-11-11 06:24
Looks like a duplicate of #4372

**Closed** 2016-02-09 14:15 UTC
Labels: In Discussion, Suggestion
