### ISSUE TITLE
Class field does not apply control statement correctly when using it inside a function

### ISSUE THREAD

**Issue by zhiyan114** [microsoft/TypeScript#58465] opened 2024-05-08 03:45 UTC
### ⚙ Compilation target

ESNext

### ⚙ Library

v5.1.3

### Missing / Incorrect Definition

When a class field method contains 2 or more types, using if statement can help confirm and expose the object types. But when that same field is used inside a wrapped function, the check no longer works, exposing the default type as if the control statement doesn't exist at all.

Workaround: Set the field as a separate independent variable and the check will pass through.

### Sample Code

```TypeScript
class A {
  test = 1;
  testCall() {
    return 1;
  }
}

class B {
  tester = 2;
  testCaller() {
    return 2;
  }
}

class C {
  testee: A | B;
  testCaller() {
    return 33;
  }
}

function test() {
  let D: C = SomeFunctionThatSpawnsC();
  let E = D.testee;
  if(!(D.testee instanceof B)) 
    return;
  if(!(E instanceof B))
    return;
  D.testee.tester; // works
  E.tester; // works
  const F = () => {
    D.testee.tester // Type Error
    E.tester // Works
  }
}
```

**Comment by MartinJohns** [comment] 2024-05-08 03:55
Another duplicate of #9998.

**Closed** 2024-05-08 03:59 UTC
