### ISSUE TITLE
Suggestion: Allow named functions to use predefined types

### ISSUE THREAD

**Issue by matthew-gerstman** [Microsoft/TypeScript#19106] opened 2017-10-11 18:55 UTC
Currently there is no way to use a predefined type with a named function in typescript. I find this regularly causes issues with functional stateless components in React.

```
function NamedComponent() {
  return <div />;
}
// [ts] Property 'propTypes' does not exist on type '() => Element'.
NamedComponent.propTypes = {};

const ConstComponent: React.SFC<{}> = () => {
  return <div />;
};
ConstComponent.propTypes = {};
```
I'm propose a method to type traditionally named functions.

### Option 1
```
function: React.SFC<{}>  NamedComponent() {
  return <div />;
}
```
### Option 2
```
function NamedComponent: React.SFC<{}> () {
  return <div />;
}
```

**Comment by andy-ms** [comment] 2017-10-11 19:54
You can do this:
```ts
function NamedComponent() {
}
namespace NamedComponent {
    export const propTypes = {};
}
```
Unfortunately, we won't do any excess property checking in this case. Although if you could write `function: React.SFC` and `React.SFC` had some required properties, I'm not sure how we could enforce them to be assigned.

**Comment by mhegazy** [comment] 2017-10-11 19:56
Duplicate of https://github.com/Microsoft/TypeScript/issues/15868

**Comment by Kovensky** [comment] 2017-10-12 02:05
More accurately this is a duplicate of #16918

**Comment by matthew-gerstman** [comment] 2017-10-12 11:00
Thanks guys! I searched for previous issues but apparently my skills failed me 😅 . I think @Kovensky is right, #16918 is what I'm looking for.

**Comment by mhegazy** [comment] 2017-10-26 18:46
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-26 18:46 UTC
Labels: Duplicate
