### ISSUE TITLE
enum type checking issue

### ISSUE THREAD

**Issue by gamesover** [Microsoft/TypeScript#11772] opened 2016-10-21 01:25 UTC
Consider the below code
**Code**

```ts
enum Test {
    a = 1,
    b,
    c
}

function hello(abc: Test) {
    return 'abc';
}

hello(4); // Test enum does not have 4

```

**Expected behavior:**
since hello argument `abc` is `Test` type, it will allow only 1,2 and 3. Otherwise, I think it is better to throw out error immediately.
**Actual behavior:** 
you can pass abc to any number, as long as it is a `number` type

**Comment by wallverb** [comment] 2016-10-21 02:34
I wish TS team would address that:

https://github.com/Microsoft/TypeScript/issues/11559
https://github.com/Microsoft/TypeScript/issues/8020#issuecomment-208717449

**Comment by mhegazy** [comment] 2016-10-21 06:03
Duplicate of #11559

**Closed** 2016-10-21 06:03 UTC
Labels: Duplicate
