### ISSUE TITLE
`Element#scroll` may be incorrect

### ISSUE THREAD

**Issue by 43081j** [Microsoft/TypeScript#23008] opened 2018-03-29 23:17 UTC
**TypeScript Version:**  2.8.1
**Search Terms:** scroll is:issue

`Element#scroll` seems to be defined as follows (for quite some time now):

```ts
scroll(options?: ScrollToOptions): void;
```

By MDN there is no such method, only on `window`. However, inspecting a random element in Chrome results in there being a `scroll` method.

Could someone clarify this? Is there documentation for this method? Is it standard, non-standard, etc?

We're having problems over at [Polymer](https://github.com/polymer/polymer) producing type declarations because some of our elements implement a `scroll` method.

**Comment by mhegazy** [comment] 2018-03-30 01:49
Spec reference: https://drafts.csswg.org/cssom-view/#extension-to-the-element-interface

**Comment by mhegazy** [comment] 2018-03-30 01:49
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mhegazy** [comment] 2018-03-30 16:15
Thanks. I assumed it was not in the library. thanks for checking. looks like it is not a bug then. closing.

**Closed** 2018-03-30 16:16 UTC

**Comment by 43081j** [comment] 2018-03-30 16:27
The problem was that we have an element or two which implement a `scroll` method, but our generated type declarations fail to compile because it doesn't match that of `Element#scroll`. 

For example:

```ts
interface Foo extends Element {
  scroll(foo: string): void;
}
```

Won't work because `Element` has its own, differently typed `scroll`.

So this was pretty much a question of if the one on `Element` is valid/correct as i couldn't find it in the spec.
