### ISSUE TITLE
RHS expression type in assignment incorrectly inferred

### ISSUE THREAD

**Issue by yjbanov** [Microsoft/TypeScript#3123] opened 2015-05-12 01:01 UTC
To completely fix #1587 TypeScript should also support:

```typescript
function repro(message: Object | Object[]) {
    if (message instanceof Array) {
        message = message.filter;  // error
    }
}
```

Currently it results in `Property 'entries' does not exist on type 'Object | Object[]'`. It seems `message` on the RHS switches from `Array` back to `Object | Object[]` prematurely.

Workaround:

```typescript
function workaround(message: Object | Object[]) {
	var theMessage = message;
    if (theMessage instanceof Array) {
        message = theMessage.filter;
    }
}
```

**Comment by danquirk** [comment] 2015-05-12 01:49
The current design is that type guards narrow down the known constituent types of a union type, but they don't narrow to anything just based on the instanceof operator. Otherwise there'd be no need to use a union type here at all, you could just type ```message``` as ```any``` and let type guards do the rest.

**Comment by yjbanov** [comment] 2015-05-12 06:15
I thought that was what my example did, narrow down the constituents of the union type. Here's another example:

```typescript
class Uri {
	uriString: String;
 }

function repro(uri: String | Uri) {
    if (uri instanceof Uri) {
        uri = uri.uriString;
    }
}

function workaround(uri: String | Uri) {
	var theUri = uri;
    if (theUri instanceof Uri) {
        uri = theUri.uriString;
    }
}
```

I certainly wouldn't want to type `uri` as `any`.

**Comment by DanielRosenwasser** [comment] 2015-05-12 06:50
I believe the reason you're getting issues in both examples is because type-guards don't narrow variables in scopes where you assign to those variables.

**Comment by yjbanov** [comment] 2015-05-12 16:43
@DanielRosenwasser, that's what it feels like to me too. It seems to assign one type to the entire code block, in this case the `if` block. It doesn't recognize that before the assignment the type guard is in effect, and after the assignment acquires a different type.

**Comment by danquirk** [comment] 2015-05-12 19:52
Sorry, I misread the original example. @DanielRosenwasser is right, the issue is related to the assignment rule we have for type guards.

**Comment by RyanCavanaugh** [comment] 2015-05-13 15:48
Basically duplicate of #2388, then?

**Comment by yjbanov** [comment] 2015-05-13 16:26
@RyanCavanaugh, pretty close. Could be used as another test case.

**Closed** 2015-05-21 23:01 UTC
Labels: Duplicate
