### ISSUE TITLE
TS@2.9.1 is emitting failing code

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#24783] opened 2018-06-08 02:46 UTC
This issue is fixed in 3.0.0-dev.20180607
But I think it is significant enough that should be mentioned and consider backporting.

I have created a PR on one of my libraries to showcase this: https://github.com/unional/komondor/pull/177

You can see that the base, using 2.8.4 is passing as well as 3.0.0-dev.20180607

The error shown in the travis log:

```sh
FAIL src/spec.spec.ts
  ● subject not specable will throw (with spec/notSpecable): live
    UnexpectedError: Unexpected error. Expecting 'NotSpecable' but received ReferenceError: { message: 'tersify_1 is not defined' }
      
      at validateError (node_modules/assertron/src/assertron.ts:102:15)
      at node_modules/assertron/src/assertron.ts:42:11
```

The code is pretty normal:

```ts
import { BaseError } from 'make-error'
import { tersify } from 'tersify'

export class NotSpecable extends BaseError {
  // istanbul ignore next
  constructor(public subject) {
    super(`The ${typeof subject === 'string' ? subject : `subject ${tersify(subject, { maxLength: 50 })}`} is not supported by any loaded plugins`)

    Object.setPrototypeOf(this, new.target.prototype)
  }
}
```
as well as the transpiled code:
```js
Object.defineProperty(exports, "__esModule", { value: true });
var make_error_1 = require("make-error");
var tersify_1 = require("tersify");
var NotSpecable = /** @class */ (function (_super) {
    __extends(NotSpecable, _super);
    // istanbul ignore next
    function NotSpecable(subject) {
        var _newTarget = this.constructor;
        var _this = _super.call(this, "The " + (typeof subject === 'string' ? subject : "subject " + tersify_1.tersify(subject, { maxLength: 50 })) + " is not supported by any loaded plugins") || this;
        _this.subject = subject;
        Object.setPrototypeOf(_this, _newTarget.prototype);
        return _this;
    }
    return NotSpecable;
}(make_error_1.BaseError));
```

**Expected behavior:**
Expect the test to pass.

**Actual behavior:**
It fails.

Since I'm running `jest` with `ts-jest`, the code is not transpiled.
You can run `node ./node_modules/.bin/tsc` to transpile the code.
They will be under `dist-es5` folder.

**Comment by unional** [comment] 2018-06-08 02:48
One reason this is significant is that 2.8.4 -> 2.9.1 is not minor version upgrade, most user will get 2.9.1 automatically and encounter this.

**Comment by mhegazy** [comment] 2018-06-08 16:38
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/24551, and https://github.com/Microsoft/TypeScript/issues/24729.

**Closed** 2018-06-25 18:56 UTC
Labels: Duplicate
