### ISSUE TITLE
`locale` option

### ISSUE THREAD

**Issue by Bit0r** [microsoft/TypeScript#34873] opened 2019-11-02 02:58 UTC
The `--locale` option is available in the `tsc` compile option, but the `tsconfig.json` in `visual studio code` does not have the `locale` option. I hope to use the `locale` option in `tsconfig.json`.

**Comment by fatcerberus** [comment] 2019-11-02 05:32
Duplicate of #34644.  Please follow the template for feature requests.

**Closed** 2019-11-04 20:51 UTC
Labels: Duplicate
