### ISSUE TITLE
BUG/SUGGESTION: Missing support for destructuring in `import … = <namespace>` statements

### ISSUE THREAD

**Issue by smotaal** [Microsoft/TypeScript#20010] opened 2017-11-14 14:40 UTC
**TypeScript Version:**  2.6.1

**Intent**

To be able to export imports (using allowSyntheticDefaultImports) and not run into the dreaded *voldemort* cannot be named when importing those exports and consuming them in other modules inside or outside the scope of the project.

**Code**

Currently, the most intuitive approach exposes the entity but leaves out the type information, resulting in the cannot be named:

```ts
import fs from 'fs';
export const { existsSync, readFileSync, writeFileSync } = fs;
```

The TypeScript way of going about this disconnect is to use the `export import readFileSync = fs;` and do this for each and every member that needs to be exposed both as entity and type:

```ts
import fs from 'fs';
export import existsSync = fs.existsSync;
export import readSync = fs.readSync;
export import writeFileSync = fs.writeFileSync;
```

Which is crude when compared to the simplicity of `export const {…} = fs;` to say the least.

So, here is where it is not clear if this is intentional, a bug, or a future TODO from the past, but as a TypeScript developer one would expect this to be a given valid and supported syntax:

```ts
import fs from 'fs';
export import { existsSync, readFileSync, writeFileSync } = fs;
```

**Expected behavior:**

The `export const …` is behaving (though not ideal) but on par with TypeScript's conventions since it explicitly exports the entity.

The `export import <name> = <namespace>.<name>` gladly resolves this disconnect.

But one would expect `export import {… <names> } = <namespace>` to be valid TypeScript syntax, which behaves like `export const {… <names> } = <namespace>` but also expose the types.

**Actual behavior:**

Sadly, while TypeScript can properly handle destructuring in consts, and even transpile those flawlessly to legacy individual var statements, it does not like destructuring in the import counterparts.

***edit:** simplified code for readability*

**Comment by smotaal** [comment] 2017-11-14 15:20
Just as a side note, but this does not resolve the actual issue with the lagging destructuring support for `import =` statements…

There are various ways to accomplish this specific intent that are potentially problem free aside from some gagging when looking at the code:

```jsx
// helpers.ts — alternative 1
import fs from 'fs';
export const { existsSync, readFileSync, writeFileSync }: /*gag*/ typeof fs = fs;

// helpers.ts — alternative 2
import fs from 'fs';
export const { existsSync, readFileSync, writeFileSync } = fs as /*gag*/ typeof fs;

// helpers.ts — alternative 3
import fs from 'fs';
/*gag*//** @type {typeof fs} */
export const { existsSync, readFileSync, writeFileSync } = fs;

// helpers.js — tsc-generated for all alternatives
import fs from 'fs';
export const { existsSync, readFileSync, writeFileSync } = fs;

// helpers.d.ts — tsc-generated for all alternatives
/*gag but who's even looking without gravol on hand*/
export declare const existsSync: typeof fs.existsSync, readFileSync: typeof fs.readFileSync, writeFileSync: typeof fs.writeFileSync, renameSync: typeof fs.renameSync;

// helpers.d.ts — tsc-generated magically when it is executed OCD people
export type fs = typeof fs; /*no gag here — it belongs*/
export declare const { existsSync, readFileSync, writeFileSync } = fs;
```

To reiterate, this is a workaround, but let's hold off the cheering until `export import {…} = <namespace>` either behaves identical to those awful workarounds or even better result in this:

```ts
// helpers.ts
import fs from 'fs';
export import { existsSync, readFileSync, writeFileSync } = fs;

// helpers.js
import fs from 'fs';
export const { existsSync, readFileSync, writeFileSync } = fs;

// helpers.d.ts — most ideal
import fs from 'fs';
export import { existsSync, readFileSync, writeFileSync } = fs;

// helpers.d.ts — less ideal
import fs from 'fs';
export declare const { existsSync, readFileSync, writeFileSync }: typeof fs = fs;

```

**Comment by smotaal** [comment] 2017-11-14 15:34
Some issues to keep in mind:
- [ ] should `import =` compile into `const =` (instead of current `var =`)
- [ ] should `export import =` produce the definition `export import =` (instead of current)
- [ ] any possible regressions from introducing destructuring in `import =`
- [ ] …

**Comment by mhegazy** [comment] 2017-11-14 18:11
Duplicate of https://github.com/Microsoft/TypeScript/issues/18307

**Comment by mhegazy** [comment] 2017-11-14 18:16
> Currently, the most intuitive approach exposes the entity but leaves out the type information, resulting in the cannot be named:

not sure i understand the issue here.. 
```ts
import fs from 'fs';
export const { existsSync, readFileSync, writeFileSync } = fs;
```

generates the following declaration file:

```ts
/// <reference types="node" />
import fs from 'fs';
export declare const existsSync: typeof fs.existsSync, readFileSync: typeof fs.readFileSync, writeFileSync: typeof fs.writeFileSync;
```

**Comment by mhegazy** [comment] 2017-11-14 18:17
> To be able to export imports (using allowSyntheticDefaultImports) and not run into the dreaded voldemort cannot be named when importing those exports and consuming them in other modules inside or outside the scope of the project.

can you elaborate? seems like this is what we need to fix instead of building a new behavior to work around it.. are you looking for https://github.com/Microsoft/TypeScript/issues/9944?

**Comment by mhegazy** [comment] 2017-11-14 18:19
As i noted in https://github.com/Microsoft/TypeScript/issues/18307#issuecomment-328242493, we would rather not invest into non-standard syntax at this point, and instead help users move to the ES6 module syntax all the way. For instance https://github.com/Microsoft/TypeScript/pull/19675. if there is something that is blocking using the ES6 module syntax we should fix that instead.

**Comment by smotaal** [comment] 2017-11-14 18:53
Okay… So I went over your refs and here is an ES6-centric rehash:

My intended compiled output (.mjs compliant) is:

```js
import path from 'path';
export const { resolve } = path;
```

So with `{ target: "ESNEXT" module: "ES2015" }` my src/helpers.ts looks like this:

```ts
import path from 'path';
export const { resolve } = path;
```

And in another file I also do this:

```ts
import {resolve} from './helpers.ts';

class Package {
  resolve = resolve;
}
```

Now TSC throws for that second file *resolve … could not be named.*.

Of course one can argue that the second file is the culprit, and that quick fix is to change the line to `resolve: typeof resolve = resolve`. Absolutely, this is one way to go about it (meh).

Then, after testing a million things it turns out that if instead of `export const {resolve …} = path` in the helpers.ts I did a `export import resolve = path.resolve` then the original line in the other file `resolve = resolve` does not end up throwing.

So it seems that when using `import x from 'x'` the way TypeScript propagates types when using `export const {…} = x` is inferior when using `export import y = x.y`, since the latter does not throw about `y … could not be named`.

In ES6 spirit, I would recommend isolating what causes the difference and making it so that `export const {…} = x` propagates types in the same way as it if it was written using the more explicit but harder to maintain counterpart `export import y = x.y`. This would eliminate the need for `import = ` altogether and make this issue mute, because yes, everything can finally be named :)

**Comment by mhegazy** [comment] 2017-11-14 19:05
> Now TSC throws for that second file resolve … could not be named..

I think this is  #9944. and we have talked about this in the past, and decided to change the behavior. i.e. add an import to `"fs"` in the declaration file for `src/package.ts`, even if you do not have one in your source.

**Comment by mhegazy** [comment] 2017-11-14 19:06
I think this seems to all stem from #9944. i think fixing it is more ergonomic to users, and avoids adding new syntax to an already syntactically crowded area of the language.

**Comment by smotaal** [comment] 2017-11-14 19:15
That would solve it… The one thing I would be curious about though is if fixing it would be more appropriate in the exporting file instead of the consumers. I'm just thinking out loud, but since `export import y = x.y;` seems to fix it once and for all regardless of how many subsequent consumers files like the *src/package.ts*, the potential for problems would shrink exponentially.

**Comment by mhegazy** [comment] 2017-11-14 19:45
> I would be curious about though is if fixing it would be more appropriate in the exporting file instead of the consumers.

You do not have control over the exporting file all the time, it might be just a .d.ts. moreover, changing the exporting file only is not sufficient. you need to change both.

**Closed** 2017-11-29 00:08 UTC
Labels: Needs More Info
