### ISSUE TITLE
Suggestion: a --noEmitJS compiler option

### ISSUE THREAD

**Issue by mcmath** [Microsoft/TypeScript#15158] opened 2017-04-12 18:29 UTC
## The problem

It is sometimes useful to set different compiler options for `.js` files and `.d.ts` files. For example, I often want to set `--removeComments` for JavaScript outputs but not for declaration files. This can currently be achieved by building a project with `--declaration` and `--removeComments` enabled, removing emitted `.js` files, and then building the project without those options:

```sh
tsc --declaration --removeComments && rimraf "dest/**/*.js" && tsc
```

This is convoluted and wasteful. Of course, there are always tools like Gulp, but it would be nice to have a solution using just the `tsc` command.

## A solution: a --noEmitJS compiler option

I would like to see a `--noEmitJS` compiler option. Like `--noEmit`, it would suppress emitted JavaScript files, but unlike `--noEmit`, it would still emit sourcemaps and declaration files if the relevant compiler options are enabled. The above could be achieved like so:

```sh
tsc && tsc --declaration --removeComents --noEmitJS
```

This is nicer. It would also cover any other scenarios where different options are required for either declarations or sourcemaps.

**Comment by mhegazy** [comment] 2017-05-11 20:19
Duplicate of https://github.com/Microsoft/TypeScript/issues/13318

**Closed by mhegazy** 2017-05-11 20:19 UTC

**Comment by nojvek** [comment] 2017-12-16 18:37
@mhegazy I understand you've marked this as duplicate of `--removeComments` option but it doesn't seem like a duplicate. Generating only .d.ts files is a very legit use-case. `noEmitJs` becomes even more useful when you want to generate typings for pure js project with checkJs, declarations and allowJs enabled.

I understand allowJs + declarations is not supported but I understand it will soon be supported.
