### ISSUE TITLE
SUGGESTION: Allow specifying file extension in module import

### ISSUE THREAD

**Issue by ShinDarth** [Microsoft/TypeScript#26845] opened 2018-09-02 18:19 UTC
## Search Terms

- Allow specifying file extension in module import
- File extension 

## Suggestion

It would be nice to be able to specify the file extension when [importing a module](https://www.typescriptlang.org/docs/handbook/module-resolution.html#classic).

## Use Cases

- It would solve ambiguity between `.ts`/`.d.ts`/`.js` etc...
- It might help preventing issues like [this](https://github.com/angular/angular-cli/issues/10106) pr [this](https://github.com/angular/angular-cli/issues/4874)
- It would be compatible with [deno](https://github.com/denoland/deno)
- ... it doesn't harm anyway

## Examples

Use:

`import { b } from "./moduleB.ts"`

instead of:

`import { b } from "./moduleB"`

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by kitsonk** [comment] 2018-09-02 18:28
Related to/duplicate of #18442 and #16577

**Closed** 2018-09-02 18:51 UTC
