### ISSUE TITLE
Rename Symbol is messing up object literal shorthand

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#27189] opened 2018-09-18 17:14 UTC
_From @lordnox on August 30, 2018 15:37_

Example Code:
```
interface ITest {
  x: number
}
const createTest = (): ITest => {
  const x = Math.random()
  return {
    x,
  }
}
```
When trying to rename `const x` to `const rnd` the code will become:
```
interface ITest {
  x: number
}
const createTest = (): ITest => {
  const rnd = Math.random()
  return {
    rnd,
  }
}
```
This does kind of do the right thing, but changes the return type of the function and should actually become:
```
interface ITest {
  x: number
}
const createTest = (): ITest => {
  const rnd = Math.random()
  return {
    x: rnd,
  }
}
```

_Copied from original issue: Microsoft/TypeScript-Sublime-Plugin#673_

**Comment by andy-ms** [comment] 2018-09-18 17:31
Duplicate of #12007

**Closed** 2018-12-14 18:00 UTC
Labels: Duplicate
