### ISSUE TITLE
After destructuring an object with a function that returns 'never', the 'never' isn't then enforced when calling it

### ISSUE THREAD

**Issue by eranhirsch** [microsoft/TypeScript#48965] opened 2022-05-05 07:11 UTC
# Bug Report

When destructuring an object which contains a function that returns 'never', then calling that method should return never, making any code following that call unreachable. Instead, the "never"-ness of that function is somehow lost (although the type-hint shows it) and the code following that function call is shown as reachable.

When accessing the function directly instead of destructuring it everything works as expected.

In run-time the code following the method call is in-fact never reached as expected.

### 🔎 Search Terms

destructuring, never

### 🕗 Version & Regression Information

From the playground it seems that this problem exists since 3.7.5, and that versions prior to that ignore the never return value even when accessing the function directly.

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.7.5#code/JYOwLgpgTgZghgYwgAgPIAczAPYgM7IDeAUMstFNlAMJQRxhUAUAHgFzJ5hSgDmAlBxAQAbtADcxAL7FiAegBUC0guQAVABbAC25GA0p0lAEYAbCAFsGwBMmAX0pgDR6DyACYQuUAK4IwPjwgvMjYMK4o2Jg4+KHGAFYQ-sjGdHAA1gT6KDA+IP4xAOQEAETCYlAlALTCeHgqcsS5+Vi4elBw+KYMEABi2NisHN58LoTkUJQ0aYxQyFIcGK34gpzcfESkduGsyAC8B8glMAMl-JtkZHQBUCBHxnCVkmQyWxRUtPSzrPySW3JydSoAAiqA4ACUAKIAWQAaqhIeoABIASQAyhwAOoaACediyWgIADlUGpkHk0ggNHAzCgENhPAB+ZDYvHubBeZB0CzYEQbfS6VL0dIRZDNAq4f6A+yOZBwUz6bA+XgaOxgYrkkCU6m05lbfSUADuyGExshk2YJQAqlr6FSaeYzpJXoplMhVJoUHg4BYUBAWIgwMh6Z4XIaDHcQNggz48BtPN4-DcNoaqJk5QR-egkpB3A0mnkJXduJ08N1IAAhR5DNZBXguKLLPCLaK4PCrEbBC7bZC7A57e6PM7dq4QG53Y6nZ7zWRkRsxPAAOne0y+zBYv2ksgBO93e-3B8PR938h36khaLUKKJAHFkMeH4+Aaen6+3yfT8gidGbCh9AwTVwSJwmyPAUEeQwgiDa1bUQHVHVkel8CDec2xbJt9m7FdPgYddhnWYJzhIS5XCNE0IDNC0oCYAADAASQgWCkfFAKDPAfHQdAqFzGjNxeJxpD+bg8WI4M2yDa5MJLLoen6QZJ2wEoG1bFZpyQvBsHMRdTGwXhaJRINUygdIIHcDgGOuKReOdYMGCpXsKA4TocSIrZ1M0iBtN0pgKEXX06jgXgIE3GRhO7dSJLHKSOhkyA5KYEoHkqZSmz4sT8A8ry9JogzkCMkyzOQCyxyskLbLAeyfMmJyQBc8K20ynS9N8-zvSCkLiDC0SIq5KKB2ksseiraiFKU0IVPbNSGq0pr9MMtNTPMwhLOs6Rysqxy5Vq1yyHcmbvJarw2uC51OqgES3PE3qg36mLBsratEqHFKFzSvbPNmnL5uMxaiuWkrVuYhA7NVKqoBquruumj6DsmPyjsCk6tyAA)

### 💻 Code

```ts
interface Options {
  errorCreator(x: string): never;
}

/**
 * This is the problematic impl, the destructuring of the options object breaks the function's "never"-ness
 */
function translateFoo(x: string, { errorCreator }: Options): string {
  if (x === "foo") {
    return "bar";
  }

  errorCreator(x);

  // TODO: REMVOE THIS: Why is this NOT unreachable code? Why does removing this break the function
  // impl although it's unreachable? 
  throw new Error("Unreachable");
}

/**
 * The same exact code, when not using destructuring works as expected
 */
function translateBar(x: string, options: Options): string {
  if (x === "bar") {
    return "foo";
  }

  options.errorCreator(x);
}

////////////////////////////////////////////////
//// TESTING ///////////////////////////////////
////////////////////////////////////////////////

// Notice that none of these are print "Unreachable"

const options: Options = {
  errorCreator(x: string) {
    throw new Error(`${x} is not supported`);
  },
};

try {
  const ret = translateFoo("foo", options);
  console.log(`It worked: ${ret}`);
} catch (err: any) {
  console.log(err.message);
}
try {
  const ret = translateFoo("bar", options);
  console.log(`It worked: ${ret}`);
} catch (err: any) {
  console.log(err.message);
}
try {
  const ret = translateBar("foo", options);
  console.log(`It worked: ${ret}`);
} catch (err: any) {
  console.log(err.message);
}
try {
  const ret = translateBar("bar", options);
  console.log(`It worked: ${ret}`);
} catch (err: any) {
  console.log(err.message);
}
```

### 🙁 Actual behavior

Destructuring causes ts to ignore "never" as a return value. 

### 🙂 Expected behavior

Should work just like regular object access.

**Comment by MartinJohns** [comment] 2022-05-05 07:19
Duplicate of #37818.

**Closed** 2022-05-07 18:00 UTC
Labels: Duplicate
