### ISSUE TITLE
Add option to disable TS using inline import types in quick fixes

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#35078] opened 2019-11-13 06:22 UTC
**TypeScript Version:**  3.8.0-dev.20191112

**Search Terms:**
- Implement interface
- quick fix
- code action
- add missing imports

**Code**
For a small project:

`iface.ts`
```ts
export interface IValue {
    value: number;
}

export interface IFace {
    do(value: IValue): void;
}
```

`index.ts`
```ts
import { IFace } from "./iface";

export class Foo implements IFace {}
```

1. Run `implement interface` on `Foo `

**Current Behavior:**
The generated code is:

```ts
import { IFace } from "./iface";

export class Foo implements IFace {
    do(value: import("./iface").IValue): void {
        throw new Error("Method not implemented.");
    }
}
```

**Request**
We would like an option to tell TypeScript to not use inline imports and instead always add normal imports at the top of the file.

```ts
import { IFace, IValue } from "./iface";

export class Foo implements IFace {
    do(value: IValue): void {
        throw new Error("Method not implemented.");
    }
}
```

/cc @bpasero Since I know you were passionate about this issue

**Comment by bpasero** [comment] 2019-11-13 06:26
Duplicate of https://github.com/microsoft/TypeScript/issues/34995

**Comment by andrewbranch** [comment] 2019-12-10 20:36
In #32910, @DanielRosenwasser said

> We should always prefer an `import` statement at the top of the file.

In that fix, we didn’t discuss adding an option, we just made it always do an import declaration. @mjbvz do people really want an option, or does it seem like most people just want the import declaration?

It should also be noted that #35200 could have an impact on this discussion, so we may want to wait and see where it lands, particularly on whether the default behavior of the compiler’s elision of imports used only in type positions is going to change.

**Comment by mjbvz** [comment] 2019-12-10 22:13
@andrewbranch Yes I think VS Code would prefer that imports always be added at the top of the file. I'm not sure if other users prefer inline imports however, which is why I proposed having a setting to control this. We should try getting actual user feedback on this

Also 👍 for #35200

**Comment by andrewbranch** [comment] 2020-01-24 22:14
@mjbvz @DanielRosenwasser: with type-only imports in master, the discussion at #36038, and #36412 looking likely to be merged, what’s the latest feeling on the right thing to do here?

On one hand, auto-imports will not use `import type`, so maybe we should match that here and use a regular import at the top of the file. On the other hand, that has unwanted effects if `importsNotUsedAsValues` is `preserve` or `error`. Could that be used as a heuristic to write a type-only import? (And actually, should that same heuristic be used for auto-imports?)

**Comment by mjbvz** [comment] 2020-01-25 01:19
For VS Code, we would prefer adding regular imports. I agree though that this should not introduce an error, so observing `importsNotUsedAsValues` and using  `import type` instead makes sense to me

**Closed** 2020-02-11 01:13 UTC
Labels: Domain: Quick Fixes, Fix Available, In Discussion, Suggestion
