### ISSUE TITLE
Array.includes() should accept any arg that extends the array's type

### ISSUE THREAD

**Issue by erikdstock** [microsoft/TypeScript#60073] opened 2024-09-26 15:32 UTC
### 🔎 Search Terms

array.includes, types

### 🕗 Version & Regression Information

- This is the behavior in every version I tried - the type definition is 7 years old.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAtgTwIICcUEMEC4bRQSzAHMBtAXRgF4YSAidWgGhloCNayBYAKB6gQAOAUxgBZTKyEA5AK4AbOVVxQCxGAB8YYeXJ6hIsASiEQhYKADV0cmUOr1aMdBDETpOveGjx8ECISIrGxF7YEcnF3EESVkFTwMtHSDbJW0FCNdo9zjebn1vEgQTZjAQZmh8BSkQCmoSHhhG+GQ0TAA6QmAbABMTAAojEzNLa1sASkYGpsRUDAQOsC6ZXog+uF9-YmShCanGmdb5zp7+tLltsZ4yIA

### 🙁 Actual behavior

I should not receive type errors because an argument of type `string | null` might be included in an array of type `string[]`. It is the job of the method to make the final determination.

### 🙂 Expected behavior

I get type errors because `Array<string>.includes()` will only accept a string value. I have to cast my argument to a string in order to perform the check.

### Additional information about the issue

[Relevant code](https://github.com/microsoft/TypeScript/blob/3ad0f752482f5e846dc35a69572ccb43311826c0/src/lib/es2016.array.include.d.ts#L1-L18).

Basic suggested change:
```diff
interface Array<T> {
    /**
     * Determines whether an array includes a certain element, returning true or false as appropriate.
     * @param searchElement The element to search for.
     * @param fromIndex The position in this array at which to begin searching for searchElement.
     */
-    includes(searchElement: T, fromIndex?: number): boolean;
+    includes<U extends T>(searchElement: U, fromIndex?: number): boolean;}

interface ReadonlyArray<T> {
    /**
     * Determines whether an array includes a certain element, returning true or false as appropriate.
     * @param searchElement The element to search for.
     * @param fromIndex The position in this array at which to begin searching for searchElement.
     */
-    includes(searchElement: T, fromIndex?: number): boolean;
+    includes<U extends T>(searchElement: U, fromIndex?: number): boolean;}
// ...
}
```

**Comment by jcalz** [comment] 2024-09-26 15:59
That change wouldn’t help; it already accepts subtypes of the array element. What you want is the opposite (since `string extends (string | null)` and not vice versa). This is a duplicate of #26255 . Ultimately you’re looking for #14520

**Comment by erikdstock** [comment] 2024-09-26 16:11
> That change wouldn’t help; it already accepts subtypes of the array element. What you want is the opposite (since `string extends (string | null)` and not vice versa). This is a duplicate of #26255 . Ultimately you’re looking for #14520

Thanks for the link. I see there is a lot of discussion here - I searched but apparently missed it. In use case it seemed wrong to have to cast in this relatively straightforward`["a", "b"].includes(stringOrNull as string)`. If this has been decided years ago and I'm not contributing anything new feel free to close.

WIP PR was [here](https://github.com/microsoft/TypeScript/compare/main...erikdstock:TypeScript:fix-relax-array-includes-signature?expand=1) (first time contributing so I may have been doing it wrong).

**Comment by RyanCavanaugh** [comment] 2024-09-26 17:30
https://github.com/microsoft/TypeScript/issues/26255#issuecomment-736680802

**Closed by RyanCavanaugh** 2024-09-26 17:30 UTC
Labels: Duplicate
