### ISSUE TITLE
JSPM support

### ISSUE THREAD

**Issue by robertsundstrom** [Microsoft/TypeScript#2233] opened 2015-03-06 19:56 UTC
The JavaScript Package Manager, JSPM, is a frictionless package manager for JavaScript that is able to pull packages from various sources ("endpoints", as they are called), such as Node Package Manager (NPM) and Bower. Unifying all in one interface. 

It also has the ability to load EcmaScript 6 modules through the System.js library that implements a loader.

One notable feature is its support for transpilers, traceur (with AtScript) and Babel (formerly e6to5), that brings the new ES6 syntax and features and makes it easy to get started with building modern JavaScript applications.

JSPM brings a dynamic developer experience that pulls dependencies on the the fly. When an app is ready to be deployed it can then be compiled and dependencies can be bundled.

The JSPM configuration-file is based on the NPM package.json format.

TypeScript should support this new ecosystem too.

**Comment by red010b37** [comment] 2015-03-09 00:19
Yes please!

**Comment by robcleghorn** [comment] 2015-03-09 00:33
+1

**Comment by RichiCoder1** [comment] 2015-03-10 19:18
Aurelia makes extensive use of JSPM, and having worked with both I'd :+1: this.

**Comment by atrauzzi** [comment] 2015-03-13 17:00
:+1:

**Comment by ejsmith** [comment] 2015-03-17 05:46
Yes please!

**Comment by RyanCavanaugh** [comment] 2015-03-17 15:19
@mhegazy Accepting PRs?

**Comment by mhegazy** [comment] 2015-03-17 19:25
I actually like the JSPM work flow, and we should do that :) a couple of thoughts:
- we need a `transpile(input: string): string` interface on the TS side, to make the interaction with the API clean and simple
- we need to emit into the system.js module structure, possibly a new --module system
- finally plugin typescript support to JSPM

PRs are definitely welcomed

**Comment by basarat** [comment] 2015-03-17 22:26
> we need a transpile(input: string): string interface on the TS side, to make the interaction with the API clean and simple

I am sure you already know : https://github.com/teppeis/typescript-simple , it now does inline sourcemaps : https://github.com/teppeis/typescript-simple/pull/7 (I used it for https://github.com/atom/atom/pull/5898)

**Comment by atrauzzi** [comment] 2015-03-17 23:46
We have to make sure this comes out requiring zero configuration beyond any steps needed to get typescript initially installed.  Zero wiring requirements beyond maybe installing a package.

**Comment by basarat** [comment] 2015-03-18 01:46
@atrauzzi I was about to start work on this but noticed from : https://github.com/jspm/registry/blob/master/registry.json#L13 that there is `jspm install ts` from (https://github.com/frankwallis/plugin-typescript) by @frankwallis already. 

Is there something more required?

**Comment by robertsundstrom** [comment] 2015-03-18 06:36
I have not evaluted the extension yet. I don't know what level of support there is.

Can you debug the TS in the browser?

**Comment by frankwallis** [comment] 2015-03-18 17:44
I am the author of plugin-typescript and I'm currently converting a large multi-repository project over to using it.

It does provide source-maps so you can debug TypeScript in the browser.

I am very interested in any feedback people have, so if you find any issues or have suggestions for improvements you would like to see then please raise issues on that repository. I will be making some minor improvements to it over the coming week.

**Comment by ejsmith** [comment] 2015-03-18 17:59
I would still love to see a very simplified transpile method that has the option to embed the sourcemap content.

**Comment by atrauzzi** [comment] 2015-03-18 19:10
Yes, and I think there has to be full clarity on how `d.ts` files are used.  I'm not sure if there's a convention yet for that, but I'm thinking we probably need to map them to modules as they're imported.

**Comment by robertsundstrom** [comment] 2015-03-18 20:40
@frankwallis I could not view the source code when debugging my test project in Chrome. I just got the resulting JavaScript. I ran my test site in live-server. What am I doing wrong?

Some features worth having when supporting SystemJS:

* Errors and warnings highlighted in source code. Showing up in the console. Preferably colored text.
* Supporting backend-projects, not just front-end websites.

**Comment by frankwallis** [comment] 2015-03-18 22:49
@atrauzzi - plugin-typescript resolves .d.ts files like SystemJS/commonJS, ie. 'common/angular.d.ts' will resolve differently to './common/angular.d.ts'. I have updated the [readme](https://github.com/frankwallis/plugin-typescript) to reflect this. I think this is really important. plugin-typescript is the 4th typescript plugin I have written and I am painfully aware of the issues with managing declaration files across multiple projects. I think that using commonJS resolution for them is a neat solution which avoids having to update versions in multiple places when things change. I think that tsc & tsify as nodeJs compilers ought to use nodeJs resolution, while plugin-typescript as the SystemJS compiler uses SystemJS resolution. It also doesn't lose you anything - if you don't want to opt in or it causes problems in your IDE then just use relative paths.

@robertsundstrom - please check you have the latest version of jspm installed (0.14 I think?), I have had no problems. If you still have trouble then raise an issue on that repo. 
I am not sure what I need to do to better support back-end projects? 

@robertsundstrom, @basarat - I really would love to see some IDE integration - I have this dream sometimes where I'm compiling apps in SystemJS and running them in a browser tab of Atom while stepping through my code inside the Atom editor!

**Comment by robertsundstrom** [comment] 2015-03-19 17:58
@frankwallis 
All I get when I view "index.ts", served by live-server, in either Chrome or IE is:

    var f = function () {
        console.log("Test");
    };
    f();
    //# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJpbmRleC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQSxJQUFJLENBQUMsR0FBRztJQUNQLE9BQU8sQ0FBQyxHQUFHLENBQUMsTUFBTSxDQUFDLENBQUM7QUFDckIsQ0FBQyxDQUFDO0FBQ0YsQ0FBQyxFQUFFLENBQUMifQ==
    //# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJpbmRleC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQSxJQUFJLENBQUMsR0FBRztJQUNQLE9BQU8sQ0FBQyxHQUFHLENBQUMsTUFBTSxDQUFDLENBQUM7QUFDckIsQ0FBQyxDQUFDO0FBQ0YsQ0FBQyxFQUFFLENBQUMifQ==

Plugin version:

plugin-typescript@^0.5.10

**Comment by frankwallis** [comment] 2015-03-19 23:23
@robertsundstrom - I have reproduced this now, will issue a fix shortly.

**Comment by danielearwicker** [comment] 2015-03-21 10:21
@frankwallis :+1: for looking for a .d.ts in the package directory when referenced without `./` at the start.

How automatic is it? I'd like a way to write an npm package in .ts, such that my index.ts is compiled to index.js so that non-TS consumers are happy, but *also* TS users can just say:

    import x = require("x");

And neither I nor they have to do anything else to make it work. At the moment if I understand it correctly, I (the package author) must extract type declarations from my code and wrap them in a separate `x.d.ts`:

    declare module "x" {
        // exports copied from my index.ts file
    }

The `-d` flag to tsc doesn't seem to have a way to do this for me. It just makes top-level declarations.

And the consumer has to bring this `x.d.ts` to the attention of the TS compiler e.g. by using `/// <reference... ` comments. 

Ideally it should be enough for the consumer to import the package, and the type information is found. I guess `package.json` would need to contain something like:

    "typescriptMain": "index.ts"

But then index.ts might depend on interfaces declared in other files that are passed to `tsc`. This could be resolved by looking for a `tsconfig.json` file, so that `index.ts` can be fully understood.

**Comment by frankwallis** [comment] 2015-03-21 14:01
@danielearwicker if you want to deliver typescript in systemjs and javascript in nodejs you can override "main" in the "jspm" section of package.json - set it to "./index.ts!" and everything will work. 

Currently you do need an external declaration file for the consumer - if you want these generated automatically then I would look at dts-bundle. This external declaration file should be delivered with its own package and then referenced form the consumer using /// references *without* the "./"

Next week I am going to be seeing if I can get plugin-typescript to resolve ambient imports and if it finds another typescript file then it will trigger that compilation, autogenerate the correct .d.ts file (using dts-bundle) and inject that into the consumers compilation. This will mean it is doing a depth first compilation which is important. I think it is possible to do this, but I will find out more next week.

**Comment by basarat** [comment] 2015-03-28 02:11
Worth mentioning here : https://docs.google.com/document/d/139ImayzFfHwYDzPIfwOHgf4BsAsr4HIC0vaudF98Rog/mobilebasic

**Comment by markrendle** [comment] 2015-04-13 19:54
For those using TypeScript with Aurelia and wanting to use JSPM, I've managed to get it working by piping the output from TypeScript (with `--target es6`) through Babel. It's a bit hairy, because I also wanted to use decorators and TS1.5-alpha and Babel 5.0 disagree on how to do that.

Of course, if TS 1.5 adds support for `--module system` (using the [System.js](https://github.com/systemjs/systemjs) loader/polyfill as Babel does) then Babel wouldn't be necessary at all.

You can checkout out [my fork of `skeleton-navigation` here](https://github.com/KoanInk/skeleton-navigation)

Main issues:

* had to explicitly reference `lib.es6.d.ts` for `gulp-typescript`
* Babel did something odd with the `this.__decorate` produced by TS and it ended up as `undefined.__decorate`, so there's a `gulp-replace` regex hack to workaround that
* TS also attempt outputs an `Object.defineProperty(Class, "name", { ... });" which, at runtime, caused an error "cannot redefine property", so there's a regex hack for that, too

**Comment by ejsmith** [comment] 2015-04-15 03:44
I really hope that the TypeScript team are planning to support system.js. The JSPM and System.js workflow makes doing dev in a transpiled language feel first class.

**Comment by csaloio1** [comment] 2015-04-20 16:08
I too am using JSPM/Aurelia and would like to use TypeScript if it could plug in easily.

**Comment by frankwallis** [comment] 2015-04-20 16:42
@csaloio1 - have you tried [plugin-typescript](https://github.com/frankwallis/plugin-typescript)? I currently use it to build a large multi-repo angular project so it does work.

If you do find any issues I would appreciate it if you could raise them on the repo.

**Comment by csaloio1** [comment] 2015-04-20 18:30
Once it supports TS 1.5 I'll be very interested to try it.

**Comment by frankwallis** [comment] 2015-04-20 19:05
@csaloio1 - I have 1.5-alpha working in a branch, so you can try that if you like. It's not doing the single-file compilation yet, it's just an update of the 1.4 version. I need to do a bit more testing and then I'll tag a release.

**Comment by csaloio1** [comment] 2015-04-20 19:42
@frankwallis Sounds great. I'll check it out.

**Comment by frankwallis** [comment] 2015-04-21 12:09
@csaloio1 - FYI I've tagged a new version (1.0.0) which uses TS 1.5

**Comment by csaloio1** [comment] 2015-04-21 12:17
@frankwallis Awesome, thank you. I'm looking forward to trying it out later today :)

**Comment by ejsmith** [comment] 2015-04-21 12:56
@frankwallis does the 1.5 version perform better? We were seeing very slow loads using the old one.

**Comment by frankwallis** [comment] 2015-04-21 16:39
I think the performance is about the same as 1.4.1, but the plugin may well be faster for you now, as I actually fixed a fairly major performance issue in the plugin in version 0.6.7. 

My bundle currently takes between 6 - 10 seconds (depending on the machine) to create a bundle of 54k lines. Of that about 20k lines is typescript and during compilation it also loads about about 20k lines of declaration files (mainly lib.d.ts which is about 14k lines)

Now that the compiler supports single-file compilation it is possible to do the live browser loading without type-checking the program or loading the declaration files which will help. Then you could have  a separate watch task which bundles and does the type-checking, and that could cache files which would make it very fast. The plugin does not support single-file compilation yet, but I am keen to speed up the development turnaround.

**Comment by ejsmith** [comment] 2015-04-21 18:56
@frankwallis that sounds awesome! Hopefully we will get a more official build of TypeScript 1.5 with the BUILD conference next week. I would love to see this plugin working just like the Babel one does. It just makes the entire workflow so much nicer.

**Comment by markrendle** [comment] 2015-04-21 19:02
If it's any use as a stopgap, check out [this Gulp build task](https://github.com/KoanInk/koan/blob/master/src/Koan/build/tasks/build.js) for an example of using System.js with Aurelia and TypeScript 1.5-alpha by targeting ES6 and piping through Babel. Convoluted, and a couple of hacks required, but it works.

**Comment by mhegazy** [comment] 2015-04-27 20:00
Looks like we have all the pieces in place now for this to work:
- systemJS module output #2840
- Single file transpilation API #2499
- inlining source maps in emitted js code #2484

all what we need is a PR to add typescript as a transpiler option in JSPM.

**Comment by ejsmith** [comment] 2015-04-28 03:41
Awesome!!

**Comment by frankwallis** [comment] 2015-04-29 13:48
I have created https://github.com/frankwallis/plugin-typescript/issues/16, and I'm planning to implement this over the next week or two.

**Comment by hourliert** [comment] 2015-05-02 20:22
Amazing. Thanks !!!

**Comment by robertsundstrom** [comment] 2015-05-20 14:07
I have been watching this one: systemjs/systemjs#432

As soon as these conflicts get resolved, SystemJS will finally support TypeScript.

**Comment by mhegazy** [comment] 2015-05-25 19:04
TypeScript support is not in JSPM: https://github.com/jspm/jspm-cli/pull/735#issuecomment-105272821

**Closed by mhegazy** 2015-05-25 19:04 UTC
Labels: Accepting PRs, Suggestion

**Comment by atrauzzi** [comment] 2015-05-25 19:18
*"not"* or *"now"*?

Where would people find docs on making use of this?

**Comment by mhegazy** [comment] 2015-05-25 19:20
thanks @atrauzzi, corrected above. @vladima is working on a JSPM sample to share. We would be happy to take PRs for additional documentation as well.

**Comment by johnjelinek** [comment] 2015-06-07 04:12
Any updates on a JSPM sample?

**Comment by vladima** [comment] 2015-06-07 06:48
@johnjelinek JSPM 0.16 with TypeScript support is not officially released yet so our work over samples is still in progress. If you want to take a peek on intermediate results and ok with using the beta version of JSPM you can use https://github.com/Microsoft/TypeScriptSamples/tree/jspm/jspm

**Comment by OliverJAsh** [comment] 2015-06-12 18:00
Where can I track support for bundling in jspm?

**Comment by OliverJAsh** [comment] 2015-06-14 15:25
Testing https://github.com/Microsoft/TypeScriptSamples/tree/jspm/jspm with the latest jspm beta (0.16).

I don't seem to get compile errors in the browser, e.g. this succeeds:

``` js
function greeter(person: string) {
    return "Hello, " + person;
}

var user = [0, 1, 2];

greeter(user);
```

/cc @mhegazy

**Comment by vladima** [comment] 2015-06-14 16:44
@OliverJAsh  complete typechecking in transpile scenarios is not possible: TypeScript compiler deliberately works within given file without attempting to resolve any references to external files (including standard library). In this circumstances it cannot build the full set of types that will be available in the program and will report lots of errors which are in fact false positives. If you want to have full-fledged editing experience with correct errors - you should use editor with TypeScript support i.e. VSCode, Sublime, Visual Studio, Atom etc. Support to compile isolated modules can be seen as merely a shortcut to avoid explicit compilation step but not the replacement for full program analysis which can be done i.e. in the editor or the compiling the whole program.

**Comment by OliverJAsh** [comment] 2015-06-15 10:58
@vladima Thanks for the explanation.

I'm looking at VSCode and the IDE plugins now. Is it possible to hook these up to SystemJS so they read the config and can parse third party dependencies, e.g. `import jquery from 'jquery`;`?

**Comment by atrauzzi** [comment] 2015-06-15 12:09
@OliverJAsh That would be simply amazing.  Would almost offer a first-class client side dev experience.

I'm fairly curious about this realm, because I feel like there are numerous undiscovered challenges:

 - If it's a pure JavaScript package, how far can the hinting really expect to go?
 - If it's a TypeScript package, does it read built JS, or does it look somewhere for TS code?
 - If it's built JavaScript that includes the `.r.js` files, where should it expect to find those?
 - What if it's a package that needs to be supplemented with an `r.js`? Any way to match the two?

Probably more questions.  But I feel like package development in JS is just insanely complex and difficult to reason about with or without TypeScript.

**Comment by OliverJAsh** [comment] 2015-06-19 00:34
I don't seem to get compile errors when bundling (now supported in `jspm@0.16-beta.2`.

**Comment by vladima** [comment] 2015-06-19 04:46
Technically bundling as it is done in jspm now is not a whole program analysis as it processes modules one by one. I already have a workitem in my list to add support for reporting syntax errors during `transpile` part in es6-module-loader and in systemjs/builder.

Also we already have plenty of requests to add support for bunding in TypeScript compiler - is already in the roadmap (I think it is currently scheduled for 2.0).

**Comment by SonofNun15** [comment] 2016-02-20 13:41
Currently JSPM understands typescript but the typescript compiler does not know how to resolve typings using jspm as it does with npm. This is significant for two reasons:
1. Running `tsc`results in false errors because it can't load library typings. This may be able to be resolved via `typings` (https://github.com/typings/typings), but only via an additional typings install.
2. VSCode shows a bunch of false errors in files, presumably because it relies on `tsc` to generate errors.

**Comment by daslicht** [comment] 2016-03-02 23:22
Is there meanwhile an example ?

**Comment by frankwallis** [comment] 2016-03-02 23:30
@daslicht  - you can see some jspm/typescript examples [here](https://github.com/frankwallis/plugin-typescript/blob/master/examples)

**Comment by oising** [comment] 2016-03-26 02:57
@SonofNun15 Is there an issue tracking this?

**Comment by SonofNun15** [comment] 2016-03-28 12:42
@oising: yes, this one

**Comment by Bretto** [comment] 2016-04-27 03:43
Why is this closed ? Where can we follow the progress on this ?

**Comment by kitsonk** [comment] 2016-04-27 06:18
It is closed because as mentioned above it is supported.

There are the (Microsoft/TypeScriptSamples)[https://github.com/Microsoft/TypeScriptSamples/tree/master/jspm] which maybe a better place to focus your questions/look for answers.
