### ISSUE TITLE
Value remains undefined after if check when accessed by key of an object

### ISSUE THREAD

**Issue by Bloemendaal** [microsoft/TypeScript#48035] opened 2022-02-25 09:02 UTC
# Bug Report

### 🔎 Search Terms
Value remains undefined after if check when accessed by key of an object

### 🕗 Version & Regression Information
TypeScript v4.5.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/PTAEGUFMBcFcAcBQBLAdtSAnAZgQwMaSgBiA9qaAN6Ki2gBGumA-AFygDO0maA5gNw06jAF5tO3PoIC+iRPlKouobOXZkKAXipDajTOwDk+wwBpE0wfMXKA1pACe7ew9LYS5UNuNNDVhUrQoADuuOgc4JKovF6gABRcBhI80QCUXgB8oAEcpAA2kAB0eaS8CdypVoggoADqABZYRNCNoFiYpJigpPj4sJgciKqkANouALqgAGRTIWHQEVFlw2OO45VyyO5xKxPplKC6c+GRKcvkqw7r-IeyKNvQDvCQbioXE16a3ol8hvuHdGOC1OfB27zWlVucmqYAA8qg8g45kjoBQALa4eygZBBYKdWzWQKgABuuDysEgsOwGliuzWglJ5Mp1M8MyBizOcUZFKpGkqQA)

### 💻 Code
```ts
// Setup
interface Foo {
    bar?: string;
    baz?: string;
}

const foo: Foo = {
    bar: 'bar',
};

const key: keyof Foo = 'bar';

const wantsString = (str: string) => console.log(str);


// Where the error occurs
foo[key] && wantsString(foo[key]);

if (foo[key]) { 
    wantsString(foo[key]); 
}

if (typeof foo[key] === 'string') { 
    wantsString(foo[key]); 
}


// Only way to make it work
const valueOfFoo = foo[key];
valueOfFoo && wantsString(valueOfFoo);
```

### 🙁 Actual behavior
You receive this error:

```
foo[key] && wantsString(foo[key]);
                        ^
Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.ts(2345)
```

### 🙂 Expected behavior
The check before validates that `foo[key]` is truthy and knows that it must be a string.

**Comment by MartinJohns** [comment] 2022-02-25 09:16
Duplicate of #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.

**Closed** 2022-02-28 18:00 UTC
Labels: Duplicate
