### ISSUE TITLE
Proposal: Passing Arguments by Name

### ISSUE THREAD

**Issue by bryanerayner** [Microsoft/TypeScript#5857] opened 2015-12-01 15:12 UTC
When a function has multiple optional arguments, callers of the function must use `undefined` to get the default, optional value.

## Proposal

Add a syntax allowing function arguments to be passed by name. Unless there is a better suggestion, I propose the use of `:=`. This would be sugar, and rewrite the call site to invoke the function properly. A syntax error would be thrown if the argument name was not a specified parameter.

`argumentName := value`

Example syntax:

````javascript

function func(a, b=2, c=3)
{
// Do work
}

// Proposed syntax
func(c:=4, a:=1);
// Results in the following javascript being output:
func(1, void 0, 4);

// Syntax error - Multiple specifications for argument 'a'
func(1, a:=1);

// Syntax error - 'd' is not a function parameter
func(1, d:=4);

// Valid syntax
func(a:=1);
// Rewrites to
func(1);
````

**Comment by kitsonk** [comment] 2015-12-01 15:17
Personal opinion... it is anti-TypeScript design goals:

> 8. Avoid adding expression-level syntax.

Non-goal:

> 1. Exactly mimic the design of existing languages. Instead, use the behavior of JavaScript and the intentions of program authors as a guide for what makes the most sense in the language.

Object destructuring in ES6 with the combination of the terse object literal declarations in ES6 (both downward emittable) are more than sufficient to cover this type of functionality.  TypeScript isn't trying to be a new language, it is trying to be a superset of JavaScript.  This sounds a lot like a new language.

**Comment by mhegazy** [comment] 2015-12-01 17:04
looks like a duplicate of #467

**Closed by mhegazy** 2015-12-01 17:04 UTC
