### ISSUE TITLE
Compile on save not reading settings from external props file in VS2015

### ISSUE THREAD

**Issue by cjwainwright** [Microsoft/TypeScript#5222] opened 2015-10-12 12:28 UTC
If I create a TypeScript project with, say, the following properties directly in the .csproj file
```xml
<PropertyGroup>
  <TypeScriptOutFile>..\Output\combined.js</TypeScriptOutFile>
  <TypeScriptOutDir></TypeScriptOutDir>
</PropertyGroup>
```
Then both msbuild and the compilation triggered by saving a ts file both correctly update the output in the combined.js file in the output folder.

However if I extract those properties into an external SharedTypeScript.props file, and instead import the props file in the .csproj file, i.e.
```xml
<Import Project="SharedTypeScript.props" /> 
```
Then only msbuild will correctly build to the combined.js file in the output folder. Compilation on saving a ts file behaves as if no properties were specified and does not combine the output, instead putting individual js files next to the source ts files.

This is using the latest release (https://github.com/Microsoft/TypeScript/releases/tag/v1.6.2) and VS2015. This is a regression from VS2013 and typescript 1.4 where this was not a problem.

**Comment by mhegazy** [comment] 2015-10-12 18:22
looks like a duplicate of #4131

**Closed** 2016-01-08 23:50 UTC
Labels: Duplicate
