### ISSUE TITLE
Check keys in code flow analysis

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#10515] opened 2016-08-24 06:13 UTC
**TypeScript Version:**  playground / 2.1.0-dev

**Code**

```ts
interface Foo {
  bar: string;
}

interface CoolFoo extends Foo {
  baz: string;
}

interface OtherFoo extends Foo {
  zip: string;
}

type SomeFoo = CoolFoo | OtherFoo;

function run(foo: SomeFoo): number {
  if ('baz' in foo) {
    return foo.baz.length;  // error
  } else if ('zip' in foo) {
    return foo.zip.length;  // error
  }
  throw 'Wrong foo!';
}
```

**Expected behavior:**

Checking keys should be sufficient to check if `foo` is either `CoolFoo` or `OtherFoo`.

In contrast checking by value works (at least in 2.1.0-dev, not playground):

```ts
interface Foo {
  bar: string;
}

interface CoolFoo extends Foo {
  type: 'cool';
  baz: string;
}

interface OtherFoo extends Foo {
  type: 'other';
  zip: string;
}

type SomeFoo = CoolFoo | OtherFoo;

function run(foo: SomeFoo): number {
  if (foo.type === 'cool') {
    return foo.baz.length;  // error
  } else if (foo.type === 'other') {
    return foo.zip.length;  // error
  }
  throw 'Wrong foo!';
}
```

But even with 2.1.0-dev I cannot check for existence by value. This does **not** work:

```ts
function run(foo: SomeFoo): number {
  if (foo.baz !== undefined) {  // error
    return foo.baz.length;  // error
  } else if (foo.zip !== undefined) {  // error
    return foo.zip.length;  // error
  }
  throw 'Wrong foo!';
}
```

**Not** even that:

```ts
function run(foo: SomeFoo): number {
  if (typeof foo.baz === 'string') {  // error
    return foo.baz.length;  // error
  } else if (typeof foo.zip === 'string') {  // error
    return foo.zip.length;  // error
  }
  throw 'Wrong foo!';
}
```

**Actual behavior:** 

Checking keys is not enough to check if `foo` is either `CoolFoo` or `OtherFoo`. It doesn't compile, because TypeScripts treats `foo` as `CoolFoo | OtherFoo` even after checking keys.

**Comment by DanielRosenwasser** [comment] 2016-08-24 06:20
Looks like a duplicate of the recently-filed #10515.

**Closed by DanielRosenwasser** 2016-08-24 06:20 UTC

**Comment by jesseschalken** [comment] 2016-08-24 06:22
@DanielRosenwasser #10515 is this issue.

**Comment by kitsonk** [comment] 2016-08-24 06:26
There are a few things here.

First, playground is 1.8.0 at the moment, therefore does not have any code flow analysis, nor will 1.8.0 ever.

Second, checking the keys is not a sufficient guard usually:

```typescript
const foo = { baz: undefined };

if ('baz' in foo) {
    foo.baz.length; // Ooops!
}
```

Second, when narrowing types, there are limits to the abilities for TypeScript to figure things out.  Given you have two types, you should use a [custom type guard](http://www.typescriptlang.org/play/#src=interface%20Foo%20%7B%0D%0A%20%20bar%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20CoolFoo%20extends%20Foo%20%7B%0D%0A%20%20type%3A%20'cool'%3B%0D%0A%20%20baz%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20OtherFoo%20extends%20Foo%20%7B%0D%0A%20%20type%3A%20'other'%3B%0D%0A%20%20zip%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20SomeFoo%20%3D%20CoolFoo%20%7C%20OtherFoo%3B%0D%0A%0D%0Afunction%20isCoolFoo(value%3A%20any)%3A%20value%20is%20CoolFoo%20%7B%0D%0A%20%20%20%20return%20value%20%26%26%20value.type%20%3D%3D%3D%20'cool'%3B%0D%0A%7D%0D%0A%0D%0Afunction%20run(foo%3A%20SomeFoo)%3A%20number%20%7B%0D%0A%20%20if%20(isCoolFoo(foo))%20%7B%0D%0A%20%20%20%20return%20foo.baz.length%3B%0D%0A%20%20%7D%20else%20%7B%0D%0A%20%20%20%20return%20foo.zip.length%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A) to narrow it, versus relying upon other aspects.  That way your type guard is attesting to the shape, instead of TypeScript having to try to track all the potential differences that would make it work:

```typescript
interface Foo {
  bar: string;
}

interface CoolFoo extends Foo {
  type: 'cool';
  baz: string;
}

interface OtherFoo extends Foo {
  type: 'other';
  zip: string;
}

type SomeFoo = CoolFoo | OtherFoo;

function isCoolFoo(value: any): value is CoolFoo {
    return value && value.type === 'cool';
}

function run(foo: SomeFoo): number {
  if (isCoolFoo(foo)) {
    return foo.baz.length;
  } else {
    return foo.zip.length;
  }
}
```

@DanielRosenwasser you made this a duplicate of itself! 😢

**Comment by DanielRosenwasser** [comment] 2016-08-24 06:29
Sorry, too busy trying to track down the root duplicate.

P.S. I meant it's a duplicate of #10485. :smile:
