### ISSUE TITLE
Cannot use type assertion to `Partial<T>` where T is generic

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#19470] opened 2017-10-25 14:40 UTC
In #19467, @GregorioBR filed an issue about assigning a `Foo` to a `Partial<T>` where `T extends Foo`.

However, in trying to solve the issue with a type assertion, I got an error:

```ts
interface State {
    data?: string;
}

class View<S extends State> {

    public processState(): Partial<S> {
      return { data: "test" } as Partial<S>;
    }
}
```

This is surprising because I believe `Partial<S>` should be comparable to `{ data: "test" }`.

**Comment by mhegazy** [comment] 2017-10-25 15:59
Same issue referenced in 
* https://github.com/Microsoft/TypeScript/issues/19388
* https://github.com/Microsoft/TypeScript/issues/16356
* https://github.com/Microsoft/TypeScript/issues/17682
* https://github.com/Microsoft/TypeScript/issues/12799
* https://github.com/Microsoft/TypeScript/issues/18072
* https://github.com/Microsoft/TypeScript/issues/18201
* https://github.com/Microsoft/TypeScript/issues/18839

**Comment by mhegazy** [comment] 2017-10-25 16:01
@ahejlsberg we chatted about this issue earlier in the week. looking through the issues, there are multiple scenarios where this comes up, and our current behavior is not desired.

**Comment by DanielRosenwasser** [comment] 2017-10-26 00:47
I don't think it's the same issue, but it's definitely related. This is about making it more difficult to say "I know what I'm doing".

**Comment by ahejlsberg** [comment] 2017-12-04 17:41
@DanielRosenwasser Looking at this, the original example compiles with no errors with the current master (and, it appears, has since 2.5) because the comparable relation is more permissive that the assignable relation.

@mhegazy The issues you reference above all have to do with assignability. Are you suggesting we change the rules there? If so, what would the new rules be?

**Comment by mhegazy** [comment] 2017-12-04 18:08
I originally wanted to discuss the all as a group, and we did. I have since closed all assignebilty issues as working as intended. 
It should be fine to close this one as fixed now.

**Closed** 2017-12-04 18:32 UTC
Labels: Bug, Fixed
