### ISSUE TITLE
[nightly][regression] Wrong generic parameter inferred for constructed class instance

### ISSUE THREAD

**Issue by MichaelMitchell-at** [microsoft/TypeScript#58158] opened 2024-04-12 08:55 UTC
### 🔎 Search Terms

generic, class, infer

### 🕗 Version & Regression Information

- Bisects to https://github.com/Microsoft/TypeScript/pull/57403 by @weswigham 

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.5.0-dev.20240411#code/KYDwDg9gTgLgBDAnmYcCCBnDBLA5gOwB4AVAGjgFUA+OAXjgHkBbbGE8ga2EQgDNKaAMkoBuAFBiAxgBsAhljgAxCBBI0A3mLja4kiPgwwoAV0kxoACjDGARtOySEALjjEAlHHUBfCTvRY8fAtjF3UQFwBGLzcXZVVMHAJ2T3C4KKoNLT8dPQN4ADcXBMDksMivGnoGGwArYDMAOnlEoO9yGAALbAwGmHJjN3FsnShgGGMofDh8YAB3JRULfMGs4YB6NbgAPQB+VeyN12RUAHI4wmKky6IyTzhUiJE4CvJ1e8iniqoTuG7piHgzUCsjsqHMCGOcDOKguASStzeD0+GRODX2fkOs1kMH2Ph8QA

### 💻 Code

```ts
export type Assign<T, U> = Omit<T, keyof U> & U;

class Foo<T> {
    constructor(public t: T) {}

    assign(u: {x: 1}): Foo<Assign<T, {x: 1}>> {
        const v: Assign<T, {x: 1}> = Object.assign({}, this.t, u);
        return new Foo(v);
        // ^?
        // Type 'Foo<Assign<Assign<T, { x: 1; }>, { x: 1; }>>' is not assignable to type 'Foo<Assign<T, { x: 1; }>>'.
        // wat
    }
}
```

### 🙁 Actual behavior

Type error

### 🙂 Expected behavior

No type error

**Comment by weswigham** [comment] 2024-04-12 16:46
Duplicate of #58074 :)

**Closed** 2024-04-12 17:58 UTC
Labels: Duplicate
