### ISSUE TITLE
compile error message => This condition will always return 'true' since the types '2' and '1' have no overlap.

### ISSUE THREAD

**Issue by ysmoradi** [Microsoft/TypeScript#29965] opened 2019-02-19 11:11 UTC
**TypeScript Version:**  3.3.0

**Code**

```ts
let value = 2;

if (value != 2)
    throw new Error("some error");

function test() {
    value = 1;
}

test();

if (value != 1)
    throw new Error("some error");
```

**Expected behavior:** It should gets compiled correctly.

**Actual behavior:** Compile error =>  // **This condition will always return 'true' since the types '2' and '1' have no overlap.**

**Playground Link:** [Here it is.](https://www.typescriptlang.org/play/index.html#src=let%20value%20%3D%202%3B%0D%0A%0D%0Aif%20(value%20!%3D%202)%0D%0A%20%20%20%20throw%20new%20Error(%22some%20error%22)%3B%0D%0A%0D%0Afunction%20test()%20%7B%0D%0A%20%20%20%20value%20%3D%201%3B%0D%0A%7D%0D%0A%0D%0Atest()%3B%0D%0A%0D%0Aif%20(value%20!%3D%201)%0D%0A%20%20%20%20throw%20new%20Error(%22some%20error%22)%3B)

**Comment by jack-williams** [comment] 2019-02-19 11:40
Duplicate of #16262

**Comment by ysmoradi** [comment] 2019-02-19 11:47
@jack-williams So, they're going add a "Design limitation" label to this?
TypeScript team, I ask you kindly, please add a config for this to make this optional. Typescript already has tons of configurations. A little knowledge is dangerous, and you're making a compile time error based on a little knowledge in this scenario. By making this configurable and optional, you can improve typescript's performance in large projects too. Thanks in advance.

**Closed** 2019-02-19 18:23 UTC
Labels: Duplicate
