### ISSUE TITLE
Spread object type checking

### ISSUE THREAD

**Issue by PavelPZ** [Microsoft/TypeScript#12753] opened 2016-12-08 09:46 UTC
**TypeScript Version**: 2.1.4

**Code**
```
interface IPerson {
  name: string;
}

let person: IPerson = { name: 'John' };
let person2: IPerson;

person2 = { name: 'John', age:34 }; //error!!!!
person2 = { ...person, age: 34 }; //no error!!!!
```
**Question**
Is ```person2 = { ...person, age: 34 }; //no error!!!!```  expected behavior?

**Comment by aluanhaddad** [comment] 2016-12-08 10:10
I am also seeing this. I think this is expected behavior. These are not object literals but rather expressions that produce a value that is a subtype of their constituents.

**Comment by PavelPZ** [comment] 2016-12-08 10:36
OK, thanks, but is there any other solution how to avoid typing errors, e.g.: 
```
person2 = { ...person, xname: 'Charles' };
```

**Comment by mhegazy** [comment] 2016-12-08 18:04
Duplicate of https://github.com/Microsoft/TypeScript/issues/12717

**Closed** 2016-12-30 07:43 UTC
Labels: Duplicate
