### ISSUE TITLE
Emitting code with declaration compiler option undesirably reduces keyof into string literal type instead of preserving origin type

### ISSUE THREAD

**Issue by rostislav-simonik** [microsoft/TypeScript#44889] opened 2021-07-04 11:33 UTC
# Bug Report

Emitting code with declaration compiler option undesirably reduces keyof into string literal type instead of preserving original type

### 🔎 Search Terms

typescript, compiler options, declaration, minify, string literal type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type minifications in type declarations files. 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.4#code/KYDwDg9gTgLgBDAnmYcDKEC2wCCBjGASwgDs4BeOAbwCg45CATALjgGcYpCSBzAGhoBfGjVCRYDEjGBQAZgEM8qHABsV+IqTbU66LMFYZsG4iQHDR4aPCQo4AFWSpKAa2CIIsuKvUFTbETFrODwteFkICAo4AB57AE0ABQBROFBpEkZtRxQAPgAKWwMHJOSASlYANwgmClydYSA)

### 💻 Code

```
export type SomeAction = {
  id: string,
}

export interface AllActions {
  Some: SomeAction,
}

export type Type = keyof AllActions

export const foo = <TYPE extends Type>(type: TYPE): void => {
}
```

### 🙁 Actual behavior

produces declaration file (*.d.ts). See extends part, where "Some" is instead of Type. 
```
export declare type SomeAction = {
    id: string;
};
export interface AllActions {
    Some: SomeAction;
}
export declare type Type = keyof AllActions;
export declare const foo: <TYPE extends "Some">(type: TYPE) => void;

````

### 🙂 Expected behavior

```
export declare type SomeAction = {
    id: string;
};
export interface AllActions {
    Some: SomeAction;
}
export declare type Type = keyof AllActions;
export declare const foo: <TYPE extends Type>(type: TYPE) => void;

```
what causes problems if we are extending the `AllActions` interface later in the application by module augmentation.

**Comment by MartinJohns** [comment] 2021-07-04 13:00
Duplicate of #27171. Used search terms: `emit keyof string in:title`

**Comment by rostislav-simonik** [comment] 2021-07-05 05:00
@MartinJohns thx a lot, according to the discussion I was able to workaround the issue with function notation 

```
export function foo <TYPE extends Type>(type: TYPE): void {
}
```

**Closed** 2021-07-09 18:00 UTC
Labels: Duplicate
