### ISSUE TITLE
Overloads should consider optional parameters and a type union including undefined as identical

### ISSUE THREAD

**Issue by bterlson** [Microsoft/TypeScript#17644] opened 2017-08-07 01:42 UTC
**TypeScript Version:**  2.4.2

**Code**

```ts
class A {
  constructor(); // Error: overload signature not compatible with impl
  constructor(a: number | undefined) {}
}

class A {
  constructor();
  constructor(a?: number) {} // this one works
}
```

**Expected behavior:**
I expected the first example to work especially since the type of parameter `a` is identical in either constructor implementation. I think it is helpful when writing overloads to not use optional parameters in the implementation signature and be explicit about the types that might exist in each position.

**Actual behavior:**
The first results in the noted error.

**Commentary:**
The following error may a moral equivalent of the error I am objecting to:

```ts
function foo(a: number | undefined) { }
foo(); // error, even though it's "implicitly" passing undefined
```
but I think this case is different as on the call side the error is justifiable on the grounds that we think it's likely the caller forgot a parameter (even if undefined is an allowable type, you should be explicit).

**Comment by mhegazy** [comment] 2017-10-20 21:17
Duplicate of https://github.com/Microsoft/TypeScript/issues/12400

**Comment by mhegazy** [comment] 2017-11-06 16:51
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-11-06 16:51 UTC
Labels: Duplicate
