### ISSUE TITLE
Additional export from statements from ES7

### ISSUE THREAD

**Issue by Strate** [Microsoft/TypeScript#6245] opened 2015-12-25 08:30 UTC
There is already exists es7 proposal https://github.com/leebyron/ecmascript-more-export-from
and it accepted to stage-1.

It sould be nice to have same in typescript. Without it, it is annoying to write something like:

```typescript
// module1.ts
module Module1 { // I should explicit wrap to module for export
    // ... module declaration
}
export default Module1

// module2.ts
module Module2 {
    // ... module declaration
}
export default Module2

// index.ts
export {default as Module1} from "./module1"
export {default as Module2} from "./module2"

// usage.ts
import * as Modules from "./index"

// can be used Modules.Module1.
```

This can be done better with proposal:

```typescript
// module1.ts
// just a module declaration, without wrapping to explicit module

// module2.ts
// just a module declaration, without wrapping to explicit module

// index.ts
export * as Module1 from "./module1"
export * as Module2 from "./module2"

// usage.ts
import * as Modules from "./index"

// can be used Modules.Module1.
```

**Comment by plantain-00** [comment] 2015-12-25 13:19
+1

**Comment by DanielRosenwasser** [comment] 2015-12-25 17:01
Thanks for filing @Strate, but this is a duplicate of #4813.

**Closed by DanielRosenwasser** 2015-12-25 17:01 UTC
