### ISSUE TITLE
Webpack powered build process worked on TS 3.1.6 but fails on TS 3.2.2

### ISSUE THREAD

**Issue by gsbelarus** [Microsoft/TypeScript#28897] opened 2018-12-07 09:25 UTC
The error message and stack:

```
i ｢wdm｣: Failed to compile.
× ｢atl｣: Child process failed to process the request: Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isJsonSourceFile'.
    at Object.cast (C:\Golden\NS\gdmn\node_modules\typescript\lib\typescript.js:1325:22)
    at getTypeOfVariableOrParameterOrPropertyWorker (C:\Golden\NS\gdmn\node_modules\typescript\lib\typescript.js:35591:41)
    at getTypeOfVariableOrParameterOrProperty (C:\Golden\NS\gdmn\node_modules\typescript\lib\typescript.js:35567:48)
    at getTypeOfSymbol (C:\Golden\NS\gdmn\node_modules\typescript\lib\typescript.js:35856:24)
    at resolveESModuleSymbol (C:\Golden\NS\gdmn\node_modules\typescript\lib\typescript.js:32928:36)
    at getTargetOfNamespaceImport (C:\Golden\NS\gdmn\node_modules\typescript\lib\typescript.js:32431:20)
    at getTargetOfAliasDeclaration (C:\Golden\NS\gdmn\node_modules\typescript\lib\typescript.js:32560:28)
    at resolveAlias (C:\Golden\NS\gdmn\node_modules\typescript\lib\typescript.js:32595:30)
    at checkAliasSymbol (C:\Golden\NS\gdmn\node_modules\typescript\lib\typescript.js:55749:26)
    at checkImportBinding (C:\Golden\NS\gdmn\node_modules\typescript\lib\typescript.js:55778:13)
```

**Comment by weswigham** [comment] 2018-12-07 21:16
Duplicate of #28762, I believe?

**Closed** 2018-12-12 10:00 UTC
Labels: Duplicate
