### ISSUE TITLE
Enum Object Keys

### ISSUE THREAD

**Issue by Gaelan** [Microsoft/TypeScript#3627] opened 2015-06-25 06:25 UTC
```typescript
enum Foo { }

var fooMap: { [foo: Foo]: string } // => error TS1023: An index signature parameter type must be 'string' or 'number'.
```
[play][]
* * *
Enums are internally numbers, so this should be able to compile fine.

[play]: http://www.typescriptlang.org/Playground#src=enum%20Foo%20%7B%20%7D%0D%0A%0D%0Avar%20fooMap%3A%20%7B%20%5Bfoo%3A%20Foo%5D%3A%20string%20%7D

**Comment by DanielRosenwasser** [comment] 2015-06-25 15:54
Duplicate of #2491.

**Closed** 2015-06-25 15:54 UTC
Labels: Duplicate
