### ISSUE TITLE
TypeScript 1.7 standalone installation fails

### ISSUE THREAD

**Issue by bschapendonk** [Microsoft/TypeScript#5886] opened 2015-12-02 11:39 UTC
When I try to install TypeScript 1.7 on our build server I get the following error

![2015-12-02_123545](https://cloud.githubusercontent.com/assets/886018/11530005/52cc462e-98f1-11e5-931a-206db85fef2d.png)

We don't have Visual Studio installed on our build server (only the .net sdk and msbuild), this worked with the previous version (1.6)

**Comment by IngbertPalm** [comment] 2015-12-02 13:51
Same problem when installing on a machine with Visual Studio Prof.

Installer is searching for a key 'SOFTWARE\Microsoft\DevDiv\vs\Servicing\14.0\enterprise' which doesn't exists when the Prof. version is installed. No problem with an Enterprise edition.

As workaround I've added the key to the registry. After this I was able to install TS. But now I'm unable to edit ts-files in the VS2015 Update1 Prof IDE. So be careful to use the workaround.

**Comment by bschapendonk** [comment] 2015-12-02 14:25
Afaik the Visual Studio 2015 Update 1 includes TypeScript 1.7, so you shouldn't need to install it

**Comment by IngbertPalm** [comment] 2015-12-02 14:41
Yes it's included. Updating RTM to Update 1 resulted in the same error as in your post.
I assume the same package is used when updating the RTM version of VS or when installing TS as standalone.

**Comment by mhegazy** [comment] 2015-12-02 16:43
> As workaround I've added the key to the registry. After this I was able to install TS. But now I'm unable to edit ts-files in the VS2015 Update1 Prof IDE. So be careful to use the workaround.

@IngbertPalm  TS 1.7 have a dependency on Update 1 binaries. if you bypass the check it is going to fail at runtime. the only way to get 1.7 is to install Update1 first. please uninstall TS 1.7, install update1 and then try again.

**Comment by mhegazy** [comment] 2015-12-02 16:44
@bschapendonk for your build machine, i am assuming it does not have VS installed. if this is the case, use the installer from https://www.microsoft.com/en-us/download/details.aspx?id=48739

**Comment by IngbertPalm** [comment] 2015-12-02 17:17
@mhegazy The problem is that Update 1 failed with the above exception. When I try to reinstall Update 1, the installer tells me that it's already installed. The problem occurred on two different machines with VS 2015 Pro. No problem when applying to an enterprise edition.

**Comment by mhegazy** [comment] 2015-12-02 17:55
can you share the install logs, you can collect them by running the following tool http://aka.ms/vscollect

**Comment by yuit** [comment] 2015-12-02 18:10
@IngbertPalm just to clarify on collecting the logs
- download the tool from the link:  http://aka.ms/vscollect
- put the exe in your temp folder (%temp%)
- run the exe. It will produce the logs folder called vslogs.zip.

I will try to find more information in the mean time but the logs will let us know the installation steps in details

**Comment by bschapendonk** [comment] 2015-12-02 20:24
@mhegazy thanks, using the installer for Visual Studio 2013 worked.

**Comment by yuit** [comment] 2015-12-03 01:07
@IngbertPalm so just to clarify the issue a bit : the installer looks at the following registry hive for Professional sku `SOFTWARE\Microsoft\DevDiv\vs\Servicing\14.0\professional\`  for the registry key: `UpdateVersion`. Do you see the key in your regedit.exe?

From your explanation, I think there is a failure in installing Update1 so the VSUpdate1 installed but not successfully. So TypeScript 1.7 refused to install in your machine. I couldn't repo the issue. However, to get you unblocked, I would suggest you to uninstall the broken installer of VSUpdate1 by : in `Control Panel\Programs\Programs and Features` on the left-hand side panel you will see `View installed updates` and there is an entry call "Visual Studio 2015 Update 1 (KB3022398)". Uninstall the exe and try reinstall the VSUpdate1 again.

Let me know if this works out for you.

**Comment by IngbertPalm** [comment] 2015-12-03 10:00
@yuit Thank you for the information. We have reinstalled Visual Studio on both machines and it seems to be OK. Due to this, I think it's needless to provide the logs? 

But let me explain the situation which resulted in the issue.
We have two machines with VS 2015 Pro installed and one additional with VS 2015 Enterprise.
I've downloaded the vs2015.1.vsu.iso image from http://www.microsoft.com/en-us/download/details.aspx?id=49989. Updating the Enterprise-Edition with this ISO image was no problem. The update of both VS Pro machines failed with the message that the installer was unable to find Visual Studio 2015 Update 1. In the log-file we found a trace that the TS installer searches for a key SOFTWARE\Microsoft\DevDiv\vs\Servicing\14.0\enterprise. The key doesn't exists when the Pro-Edition is installed. So we have created the key in the registry an used the stand alone installer to install TS. After this, TS was installed on both machines but we were not able to edit TS-files in the IDE.
Finally we have decide to completely uninstall VS 2015 an to reinstall it with the VS 2015 Pro With Update 1 from the MSDN ISO image.

**Comment by yuit** [comment] 2015-12-03 17:20
@IngbertPalm I am glad that you are unblock. Thanks for sharing details. Though could you still share your logs? I would like to take a look into what is the root cause of the original issue and see if there is a possible fix for it.

**Comment by soerennielsen** [comment] 2016-01-04 19:17
How can this issue be closed? I don't see any solution in the thread. @mhegazy ?

The problem is that the standalone typescript installer for the 2015 toolchain cannot install if there is no Visual Studio 2015 with update 1 installed. 

Since it is a build server it makes very good sense that no version of visual studio is actually installed (it used to be best practice). So the issue is not really update 1 or not, the issue is that the installer no longer can install on a machine without visual studio 2015 - not the sidetracked disccusion about failed installations of update 1. 

The 2013 package can and the previous versions for 2015 could also without visual studio. 

Installing the 2013 package fixes the issue for the builds using toolsversion 12 (aka 2013), but not 14 (aka 2015).
Anyone have a workaround?

**Comment by mhegazy** [comment] 2016-01-04 19:32
reopening. the 2015 targets will not be installed. we will need to publish a standalone version or augment the check to check from both VS 2015, and VS2015 update1.

**Comment by mhegazy** [comment] 2016-01-04 19:33
Another possible workaround, is to use the the nuget package: https://github.com/Microsoft/TypeScript/issues/3940#issuecomment-164605498 this one does not require any installation

**Comment by soerennielsen** [comment] 2016-01-04 20:00
I've been battling that for a while, but as soon as had written the bits above I found a possible workaround:
1. Install the 2013 version (which installs the actual compiler and the msbuild target files for 2013)
2. Copy the content from "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0" from a a dev machine (with everything installed) to the same location on the build server. 

Seems to work.

**Comment by MoonStorm** [comment] 2016-01-06 02:27
Just installed MS Build Tools 2015 and the Windows SDK on our build server, which should have been enough for the standalone installer to work. It doesn't. It stops with the error mentioned in the first post. 

I couldn't find the "2015 Update 1" equivalent for the build tools. What am I missing here?

**Comment by mhegazy** [comment] 2016-01-27 00:09
Should be fixed in the next release.

**Closed by mhegazy** 2016-01-27 00:09 UTC
Labels: Bug, Fixed
