### ISSUE TITLE
Have non-null assertion operator (!) compile to an assertion in Javascript

### ISSUE THREAD

**Issue by ikinsey** [microsoft/TypeScript#50304] opened 2022-08-15 02:00 UTC
# Suggestion

If I put a non-null assertion in my Typescript, I would expect the compiled Javascript to have a non-null assertion there so that I get an error exactly where my exclamation point was placed.

Even if not default, a compilation option for this would be great.

```
const someVal = someMap.get("blah")!

someVal.someFunc()
```

## 🔍 Search Terms

bang exclamation non-null assertion operator

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Non-null assertion (!) should add an assertion to the compiled Javascript, throwing an immediate error if that assertion fails.

## 📃 Motivating Example

Non-null assertion is used when you want to indicate that due to the business logic, a given value should not be null (and if it is, that constitutes an error that needs to be immediately observed). No longer is the exclamation mark just a way to shut up the compiler, now it carries full syntax weight from Typescript through Javascript.

## 💻 Use Cases

Non-null assertion via an exclamation mark is the most succinct way to indicate the exact point at which a value being null constitutes an error. The alternative would be to add that assertion yourself, but it's much more verbose and can't be done inline with a chained statement.

**Comment by fatcerberus** [comment] 2022-08-15 03:28
> This isn't a runtime feature (e.g. library functionality, **non-ECMAScript syntax with JavaScript output**, new syntax sugar for JS, etc.)

This is out of scope.  TypeScript won't emit code for type-level assertions.

**Comment by MartinJohns** [comment] 2022-08-15 05:30
Duplicate of #20217.

**Closed** 2022-08-17 18:00 UTC
Labels: Duplicate
