### ISSUE TITLE
Enum lookup for map type [P in Enum] gives "implicit any index" error

### ISSUE THREAD

**Issue by aaronbeall** [Microsoft/TypeScript#19546] opened 2017-10-28 04:24 UTC
**TypeScript Version:**  2.5.3

It could be I stumbled on something I simply don't understand, but it seems like this should work:

**Code**

```ts
enum Color {
  RED = "RED",
  BLUE = "BLUE",
  GREEN = "GREEN"
}

type ColorMap = {
  [P in Color]: number; // type ColorMap = { RED: number; BLUE: number; GREEN: number; }
}

declare const color: Color;
map[color] // Error: Element implicitly has an 'any' type because type 'ColorMap' has no index signature.
```

All of the following work:

```ts
declare const map: ColorMap;
map[Color.RED] // OK

const red: Color = Color.RED;
map[red] // OK

declare const color: keyof typeof Color;
map[color] // OK -- I don't know why this works
```

**Expected behavior:**

`map[color]` to work and give return type of `number`

**Actual behavior:**

`map[color] // Error: Element implicitly has an 'any' type because type 'ColorMap' has no index `

**Comment by aaronbeall** [comment] 2017-10-28 04:27
More stuff I don't understand:

```
declare const color: Color.RED | Color.BLUE | Color.GREEN;
map[color] // Error: Element implicitly has an 'any' type because type 'ColorMap' has no index signature.

declare const color: Color.RED | Color.BLUE | "GREEN";
map[color] // OK
```

**Comment by aaronbeall** [comment] 2017-10-28 06:04
I think my confusion lies with how the compiler actually "sees" the `enum` type... I *thought* that string enum was equivalent to the old string literal `type` + `namespace` workaround:
```ts
type Color = "RED" | "BLUE" | "GREEN"
namespace Color { export const RED = "RED"; export const BLUE = "BLUE"; export const GREEN = "GREEN"; }

type ColorMap = {
  [P in Color]: number;
}

declare const map: ColorMap;
map[Color.RED] // OK

const red: Color = Color.RED;
map[red] // OK

declare const color: Color;
map[color] // Ok
```

**Comment by aluanhaddad** [comment] 2017-10-28 08:49
I've also found this very counterintuitive. The workaround was more verbose but was expressive and allowed for very convenient consumption.

**Comment by mhegazy** [comment] 2017-10-30 16:31
Duplicate of  #16760. Should be fixed by https://github.com/Microsoft/TypeScript/pull/18029

**Closed** 2017-11-13 18:06 UTC
Labels: Duplicate
