### ISSUE TITLE
add new feature/type for JSON

### ISSUE THREAD

**Issue by rubenyeghikyan-highway** [microsoft/TypeScript#47616] opened 2022-01-26 16:40 UTC
# Suggestion

Add a new feature type on typescript for JSON objects. As we all know JSON has limited possible types and would be nice to have separate type for JSON objects so we could validate it, also it could be easily used as result of `JSON.parse()`.

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.
JSON type

## 📃 Motivating Example

This feature would help us to make code / type-check shorter and life easier.

## 💻 Use Cases

`const data: jsonType = JSON.parse(jsonString)`
so data here is either `{}` or `[]` which has following type def 
```TS
interface jsonType {
 [key: number | string]: number | string | boolean | null | jsonType
}
```

**Comment by xiBread** [comment] 2022-01-26 16:57
Duplicate of #1897

**Closed** 2022-01-29 18:00 UTC
Labels: Duplicate
