### ISSUE TITLE
Const enums should be considered compile-time constants for computed property names

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#10770] opened 2016-09-08 06:21 UTC
**TypeScript Version:**  1.8.0

**Code**

```ts
const enum Color {
    Blue,
    Red = 1
}

interface IColors {
    // Error: A computed property name in an interface must be a compile-time constant
    [Color.Blue]: any;
    [Color.Red]: any;

    // No errors thrown
    [2]: any;
}
```

**Expected behavior:**
No red squigglies

**Actual behavior:** 
Red squigglies, because a const enum's value isn't considered a compile-time constant (isn't it?).

**Comment by mhegazy** [comment] 2016-09-08 18:06
this is a duplicate of https://github.com/Microsoft/TypeScript/issues/5579.

The issue here is not that they are constants or not. the issue is that the way the compiler is layered, it does not necessary know what they are when a it forms the shape of the internal data structure representing the interface or class (symbol). see #5579 for more details.

**Closed by mhegazy** 2016-09-08 18:06 UTC
Labels: In Discussion, Suggestion
