### ISSUE TITLE
default value of generic argument is not assignable to the extended type

### ISSUE THREAD

**Issue by barak007** [microsoft/TypeScript#28154] opened 2018-10-26 10:50 UTC
**TypeScript Version:**  3.2.0-dev.20181026

**Search Terms:**
default argument
default parameters
default value
default generic value
not assignable to 
**Code**

```ts
type Z = "a" | "b"

// works fine
const x: Z = 'a'

function y<T extends Z>(a: T) { }

// works fine
y('a')  

// When you add default value the autocomplete is working fine, suggesting 'a' and 'b' but type error is present.
// Error: Type '"a"' is not assignable to type 'T'.
function y1<T extends Z>(a: T = 'a') { }

// This also working
function y2(a: "a" | "b" = 'a') { }

```

**Expected behavior:**
'a' should be assignable to T
**Actual behavior:**
Type Error

**Playground Link:** 
http://www.typescriptlang.org/play/#src=type%20Z%20%3D%20%22a%22%20%7C%20%22b%22%0D%0A%0D%0Aconst%20x%3A%20Z%20%3D%20'a'%0D%0A%0D%0Afunction%20y%3CT%20extends%20Z%3E(a%3A%20T)%20%7B%20%7D%0D%0A%0D%0Ay('a')%20%20%0D%0A%0D%0Afunction%20y1%3CT%20extends%20Z%3E(a%3A%20T%20%3D%20'a')%20%7B%20%7D%0D%0A

**Related Issues:** 
Nope.

**Comment by jack-williams** [comment] 2018-10-26 13:49
I think this is related, but not identical to, this issue here #21521.

I would wait on the opinion from someone in the team...but my initial reading of the problem is that the choice to use default arguments is purely syntactic to keep things nice.

Just from the syntax `y1()` we know to drop in the default argument, and this is completely independent from the instantiation of the type parameters. However you can then run into unsound things like:

```ts
y1<"b">(); // argument will be 'a', says it has type 'b'.
```

To make your suggestion sound would require checking the default argument per instantiation, which is extra complexity that the TS team might not be in favour of. Instead, the current solution is to just pick a default argument that will always be consistent with the type parameter, even if this is limiting.

**Comment by weswigham** [comment] 2018-10-26 17:39
```ts
function y1<T extends Z>(a: T = 'a') { }
```
is correctly an error - you can write
```ts
y1<"a" & { __brand: void }>();
```
to which `"a"` would not be assignable. Sadly, `extends` of a union is not quite a "one of" constraint.

**Comment by barak007** [comment] 2018-10-27 11:47
it's a wider problem not only for unions. in all cases these examples should report error on call site

```ts
/* The a argument is optional*/
function y2<T extends { name: string }>(a?: T) { }

y2()
y2<{ name: string, age: number }>()
```

**Comment by weswigham** [comment] 2018-11-27 17:31
`false` isn't assignable to `T` - `T` can be jnstantiated as either `true` or a subtype of `false` - so the assignment is not allowed. You must produce a `T` to assign to a `T`.

**Comment by DeTeam** [comment] 2018-11-28 08:58
@weswigham does it mean that it's practically impossible to just provide a value here, the only way would be using another generic function which can produce `T`?

**Comment by aleclarson** [comment] 2019-01-14 02:50
I tried coming up with a workaround for @DeTeam's example, but then I hit #29400.

```diff
- function f<T extends boolean>(some: T = false) {}
+ function f<T extends boolean>(some: T | false = false) {}
```

**Comment by aleclarson** [comment] 2019-01-14 02:56
> false isn't assignable to T - T can be jnstantiated as either true or a subtype of false - so the assignment is not allowed. You must produce a T to assign to a T.

@weswigham Is there a compelling use case for allowing a subtype of `false` to be possible?

As of now, I'd rather see the following be supported:

```ts
function f<T extends boolean = false>(a: T = false, b: T extends true ? 1 : 0) {}
```

But I might just be in the weeds here. 🤷‍♂️

**Comment by jack-williams** [comment] 2019-02-28 19:18
@aleclarson 

>  Is there a compelling use case for allowing a subtype of false to be possible?

Yes, in the future you might have name subtyping similar to flow.

In Flow:
```
opaque type invalid: false = false;
// invalid is assignable to false, but false is not assignable to invalid
```

**Closed** 2019-07-13 00:02 UTC
Labels: Question

**Comment by kripod** [comment] 2020-04-10 10:06
I just found a way to avoid this issue using function overloads: https://twitter.com/kripod97/status/1248551695065456641

> JavaScript vs TypeScript implementation of the same function. The latter infers its return type when a second parameter is given.
>
> Applying `keyof` on the resulting object returns the union of concrete numeric values in `steps`. This makes code autocomplete work wonderfully.
>
> ![](https://user-images.githubusercontent.com/14854048/78982873-55b1aa00-7b23-11ea-82d4-3e5c27840a53.png)

Please refer to the [implementation above](https://github.com/kripod/glaze/blob/26d21e4a3f2a5c8f512f579d9e56fe89139bbaf3/packages/glaze/src/scales.ts#L1-L24) and [usage](https://github.com/kripod/glaze/blob/26d21e4a3f2a5c8f512f579d9e56fe89139bbaf3/packages/glaze/src/theme.ts#L95) for further details.

**Comment by xialvjun** [comment] 2020-12-30 19:20
> I tried coming up with a workaround for @DeTeam's example, but then I hit #29400.
> 
> ```diff
> - function f<T extends boolean>(some: T = false) {}
> + function f<T extends boolean>(some: T | false = false) {}
> ```

` function f<T extends boolean>(some: T | false = false) {}` indeed makes ts not to complain, but it doesn't help on our type:
```ts
function f<T extends boolean>(some: T | false = false) { return some }
const a = f();  // here I expect "a"'s type is "false", but it's "boolean"
```

**Comment by lexigren** [comment] 2021-07-21 19:32
Why can't I use default value for parameter of generic type? 
This is outrageous. It's unfair.
