### ISSUE TITLE
TSX. Type of props created by using the spread operator is ignored.

### ISSUE THREAD

**Issue by undefeat** [Microsoft/TypeScript#22144] opened 2018-02-23 11:27 UTC
**Environment:**
Typescript: 2.7.2,
react-scripts-ts: 2.13.0,
Visual Studio Code: 1.20.1,
Node: 7.9.0

`{
    "compilerOptions": {
        "outDir": "build/dist",
        "module": "esnext",
        "target": "es5",
        "lib": ["es2017", "dom"],
        "sourceMap": true,
        "allowJs": true,
        "jsx": "react",
        "moduleResolution": "node",
        "rootDir": "src",
        "forceConsistentCasingInFileNames": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noImplicitAny": true,
        "strictNullChecks": true,
        "suppressImplicitAnyIndexErrors": true,
        "noUnusedLocals": true,
        "downlevelIteration": true,
        "experimentalDecorators": true
    },
    "exclude": [
        "node_modules",
        "build",
        "scripts",
        "acceptance-tests",
        "webpack",
        "jest",
        "src/setupTests.ts"
    ]
}
`

**Expected behavior:**
When using the spread operator to add props to a React element, the type of the props should be taken into account.

**Actual behavior:**
The type of the props is ignored.

![selection_043](https://user-images.githubusercontent.com/6769991/36592013-af6761c0-189c-11e8-94c0-7081b6a41c89.png)
![selection_044](https://user-images.githubusercontent.com/6769991/36592018-b21b4a08-189c-11e8-8d34-997127216d71.png)

**Comment by DanielRosenwasser** [comment] 2018-02-23 20:52
Duplicate of #18801

**Comment by DanielRosenwasser** [comment] 2018-02-23 20:53
See #12936 for exact object types.

**Closed** 2018-03-09 23:41 UTC
Labels: Duplicate
