### ISSUE TITLE
Issue in inferring types in Switch Case for object methods having union mapped types.

### ISSUE THREAD

**Issue by kansalanmol0609** [microsoft/TypeScript#51563] opened 2022-11-16 17:09 UTC
# Bug Report

### 🔎 Search Terms

Issue in inferring types in Switch Case for object methods having union mapped types.

### 🕗 Version & Regression Information
Version - All versions upto v5.0.0-dev.20221116

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about mapped types, union types and switch cases.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221116#code/KYOwrgtgBAggxgFwJYHsQGcDeBYAUDAYQBUBJAeQDkYAaPQ0ygITwF8BuPPBATwAdhYiVCBhQAvFBy4oUHvygAuQcjToAdPXJVa0qLwCG3ADYp9AEyVSZMgEYoz3JegQAnJCADmHXTIjB06PoewEooNgBWwIjeMiysnLhyAvAqIIzikngySYrKwuqaTDoyBsamFpk+UH4BQSFQYZHRWVBxuG1cfMlCaERdGSnCogA+eWiM3nhwqghQ+j0gABL6IGZGwC7oli0A2gDWwNxQ7jKDqhrEWiNjGBcMFIwAukoAFKUm5koAogAervMIAA8ZxAfX41Eksi6SgORxYAD4dgByd7lJGPACU4nhUAAbigkGZWBkrFAdiCCpdKDBnlAXpg7A4ITVAsEWFixDjphgUOs1CYPC9Gdxmf5WcAMcUyRS7lonq9MCy6uzsVBuehecB+ShBdUxXVJfFcFMZnoNgAzFAuCAgjIvAHCJQgsESpT4wmq0noADuSAQcAAFvaFmokhjSTI4Pp0N1UpT7jAFC1I9HY-lZUwk1UZC5gAgwC4QHMFstVutNjsHWhQ11HsHUmpUeYMWwoC02iwgA)

### 💻 Code

```ts
enum Actions{
ACTIONA,
ACTIONB
};

type ActionA = {
  type : Actions.ACTIONA,
  payload: {
    body: string;
    message: object;
  }
}

type ActionB = {
  type : Actions.ACTIONB,
  payload: {
    message: object;
  }
}

type ActionType = ActionA | ActionB;

const actionHandlers: {
  [key in  Actions.ACTIONA | Actions.ACTIONB]: (payload: Extract<ActionType, { type: key }>['payload']) => void
} = {
  [Actions.ACTIONA]: ({body, message}) => console.log(body, message),
  [Actions.ACTIONB]: ({message}) => console.log( message),
}

const performAction = (action: ActionType): void => {
  switch(action.type){
    case Actions.ACTIONA:
    case Actions.ACTIONB:
      return actionHandlers[action.type](action.payload);  //Error here
  }
}
```

### 🙁 Actual behavior

Getting this error - 
```
Argument of type '{ body: string; message: object; } | { message: object; }' is not assignable to parameter of type '{ body: string; message: object; }'.
  Property 'body' is missing in type '{ message: object; }' but required in type '{ body: string; message: object; }'.

```

### 🙂 Expected behavior

TypeScript compiler should have been able to infer that `action.type` and `action.payload` are connected. It looks like it is treating them as independent variables.

**Comment by fatcerberus** [comment] 2022-11-16 17:17
Duplicate of #30581, but see https://github.com/microsoft/TypeScript/issues/30581#issuecomment-1205946813

**Closed** 2022-11-18 17:44 UTC
Labels: Duplicate
