### ISSUE TITLE
Typeguards on this

### ISSUE THREAD

**Issue by elicym** [Microsoft/TypeScript#16547] opened 2017-06-15 07:07 UTC
**TypeScript Version:**  2.3.0

**Code**

```ts
function isImg(el: HTMLElement): el is HTMLImageElement {
    return el.tagName == 'IMG';
}

document.getElementById('id').addEventListener('click', function () {
    //this works
    let _this = this;
    if (isImg(_this))
        console.log(_this.src);
    //this doesn't work
    if (isImg(this))
        console.log(this.src);
});

```

**Expected behavior:**
Typeguards should be allowed for *this*.

**Actual behavior:**
Typeguards don't work for *this*.

**Comment by andy-ms** [comment] 2017-06-15 15:29
Looks like a duplicate of #14817

**Comment by mhegazy** [comment] 2017-08-17 18:07
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-08-17 18:07 UTC
Labels: Duplicate
