### ISSUE TITLE
Template string aren't recognized by classifier

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#1884] opened 2015-02-02 11:07 UTC
https://github.com/Microsoft/TypeScript/blob/ab9ce1e9e6636ec6a2aa4f01458525f249c4edf5/src/services/services.ts#L1172

I would expect them to get a special treatment. For instance 

```
`Hello ${name}`
``` 
could have tokens like: ```string(`Hello), punct(${), identifier(name), punct(}), string(`)```

**Comment by DanielRosenwasser** [comment] 2015-02-02 18:27
Duplicate of #1698, #1716, and #1477. In #1477 I give an explanation of the technical difficulties associated with highlighting a context free construct template strings, however, I decided that it was an inappropriate experience so now we just do our best to propagate template state across lines. #1744 has a fix.

**Closed** 2015-02-02 18:30 UTC
Labels: Duplicate

**Comment by DanielRosenwasser** [comment] 2015-02-13 22:10
A fix is now in `master`.
