### ISSUE TITLE
Generic parameter defaults in arrow functions confused as jsx elements in tsx files

### ISSUE THREAD

**Issue by matt-erhart** [microsoft/TypeScript#45939] opened 2021-09-17 16:47 UTC
```ts
const OkInTsx = function <A = string>() {
  return 'ok in ts file';
};

export const BrokeInTsx = <A = string>() => {
  return 'ok in ts file';
};
```

To replicate, copy that code in a ts file (v3.3+ tested, updated vscode). It should be ok. Rename ts to tsx and the generic parameter default will be considered a jsx element and therefore a syntax error. I discovered this doing some codegen into a tsx file. If we are writing our own code, we can work around, but it seems jsx and generic parameter defaults on arrow functions aren't working together at the moment.

**Comment by MartinJohns** [comment] 2021-09-17 17:44
You forgot to fill out the issue template. It asks for search terms you used to find existing issues. Duplicate of #15713.

**Closed** 2021-09-17 18:55 UTC
Labels: Duplicate

**Comment by matt-erhart** [comment] 2021-09-18 00:20
Whoops, don't know why I didn't get a template that time. This is a slightly different issue which I show [in the ts playground here](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210910&ssl=23&ssc=3&pln=1&pc=1#code/PTAEGkDsHsHdNAZwJYFtkBsCGAnUzFEBXAU1FmQBcALUAcxMhJ2QGNFRrLKAHRALhB0q1IgCMAdK2ipg6VjmiJoAM0rAAKgE8eJAMoLkPdQWIlEwAIwBWAOyWAzACgnIAOrQcAa1C5FRSAATRCcSAA8eT0pQaUhEaIBhGVQsD28AQRx-IIAxTwBxRmY2DgBeUAAedIAaAD4ACgBKUFLa0ABvJ1BQHBJKIhwEAHJoH2QESg4VTBIhgG4nAF8F0IiomOg46IBRMMpGYLSvTOzAvJxCphZ2Fsr00HD9oI4Arxh4BubWjq6evoHhqN8BMpjN5ksVuFIjhorF4qAACKbSgAVUQJBOcByAVYlGQm0QR0xAUCtxUOLxm0qGlu8RYkDoDTC-A0zU63V6-UGoDCEJcIFAAElQGISBhkCQAG5kLCgJiwfCEUjkETQIjRWCeHx+NXPUAqTz0IrXUA8XBYVB9ZigQIkFRYIgYSbA3xZOD6in4uKraGwgnRABCii8JEstwqgoAGrTKPS6HV6szBWEvm12qABTANqgUuQtTqSb9OQDQCMxiD9WCFssXFD1nDA8GSAAmcNRmNxh57A4vSBvOCQJn8ZOpjoZsBZx49vPeAtBIv-blll3O6YYWbVuZAA). Basically, there are workarounds for generics on arrow functions, but not for generic parameter defaults with the ```=``` in there. I can repost   with template if it's actually new. I searched for typescript generic aliases, typescript generic renaming, typescript generics, advanced typescript generics, generic parameter defaults.

```ts
// Known similar issue with generics https://github.com/microsoft/TypeScript/issues/15713

//Work arrounds
export const CommaWorkArroundForGenerics = <A,>() => {
  return 'ok in ts file';
};

export const ExtendsWorkArroundForGenerics = <A extends unknown>() => {
  return 'ok in ts file';
};

export const DontUseArrowFunctionsWorkArround = function <T = string>(x:T) {
  return x
};

// I believe a new issue without work arrounds for generic parameter defaults in arrow functions
export const Broke1 = <IX = string,>(x:Ix) => { // no comma workarround
  return 'ok in ts file';
};

export const Broke2 = <IX = string extends unknown>(x:Ix) => { // no extends workarround
  return 'ok in ts file';
};
```

**Comment by andrewbranch** [comment] 2021-09-23 19:17
Your last example gets the syntax wrong in general—the constraint needs to come before the default. It works if you fix that, except that the second-to-last example breaks parsing for everything after it. So the one thing that doesn’t work is an arrow function with a default but no constraint (as in `Broke1`), but for all intents and purposes you can always add `extends unknown`, so there’s still at least one workaround for everything you could need to do.

**Comment by matt-erhart** [comment] 2021-09-24 16:08
Aha, got it, thanks. 
```export const WorkArroundExtendsCorrectSyntax = <Ix extends unknown = String >(x:Ix) => { 
  return 'ok in ts file';
};```
