### ISSUE TITLE
Function Decorator 

### ISSUE THREAD

**Issue by CofeeWithRose** [microsoft/TypeScript#41158] opened 2020-10-19 03:35 UTC
## Suggestion

support function no in class  Decorator.
In react app, I hope to use decorator to define the  route information of function components.

## Use Cases

Page.tsx
```

@Reflect.metadata('Route', { path: '/home' })
export function Page(){
  return <div> Home Page </div>
}


console.log(Reflect.getMetadata('Route', Page).path ) //   "/home"


```

## Checklist

My suggestion meets these guidelines:

* [yes ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ yes] This wouldn't change the runtime behavior of existing JavaScript code
* [yes ] This could be implemented without emitting different JS based on the types of the expressions
* [ yes] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [yes ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-10-19 06:41
Duplicate of #7318. And this would first require JavaScript to support function decorators.

**Comment by RyanCavanaugh** [comment] 2020-10-19 15:13
Please follow the "search terms" part of the template. Thanks!

**Closed by RyanCavanaugh** 2020-10-19 15:13 UTC
Labels: Duplicate
