### ISSUE TITLE
variance checks don't take into account whether a property is `readonly`

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#48623] opened 2022-04-09 11:19 UTC
# Bug Report

### 🔎 Search Terms
variance readonly

### 🕗 Version & Regression Information

4.7.0-dev.20220408

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220408#code/C4TwDgpgBAkgdgNwIYCcCWS7ADxrlAewFdgoAVAPigF4oBvAWACgpWpkAbIiALnOYC+zZgBMIAYw6po4gnADOpAGYECfeMnSYcdFBCQi5HEOyRdeUOEQC2AIwgoBFYUxUEAdJ26ez3GlABGKAB6YIcUAhQXWQVSW1R1RFQMLGw6U3M+KzsHKCd-Nxd4lB9zUr9aACYQ4LgCKHDIoA)

### 💻 Code

```ts
type Invariant<in out T> = {
    value: T
}

declare const foo: Invariant<{readonly value: number}>

foo.value.value = 1 //error

const bar: Invariant<{ value: number }> = foo

bar.value.value = 2 //no error
```

### 🙁 Actual behavior
the value of type `Invariant<{readonly value: number}>` is allowed to be assigned to the variable of type `Invariant<{value: number}>`

### 🙂 Expected behavior
the types should not be compatible because `{value: number}` is narrower than `{readonly value: number}` and the `Invariant` type has an `in` annotation

**Comment by MartinJohns** [comment] 2022-04-09 11:24
Duplicate of #13347. Types with mutable properties and types with readonly properties are treated the same. The optional variance annotations don't change anything about this, because the issue is not about variance.

> `{value: number}` is narrower than `{readonly value: number}`

It's not. They're the same.

**Closed** 2022-04-09 11:40 UTC
