### ISSUE TITLE
[Feature Request] Add a "throws" keyword to the signature of functions to identify functions that can possibly throw

### ISSUE THREAD

**Issue by flowstate247** [microsoft/TypeScript#49582] opened 2022-06-16 22:22 UTC
## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add a "throws" keyword to the signature of functions to identify functions that can possibly throw.

## 📃 Motivating Example

Java has a throws keyword to help the developer who reads code determine whether a function or method can possibly throw or not:
```
static void testMethod() throws Exception {
    String test = null;
    test.toString();
}
```

## 💻 Use Cases

Practically speaking the value of this feature request for the DX is that by reading the code of a function we can be sure simply by reading the signature type whether or not that function can possibly throw, even if it doesn't have the throw keyword explicitly written in the function body.

## Related to

https://github.com/microsoft/TypeScript/issues/49549
https://github.com/typescript-eslint/typescript-eslint/issues/5196

**Comment by MartinJohns** [comment] 2022-06-16 22:44
Duplicate of #13219. Used search terms: `throws in:title`

**Comment by flowstate247** [comment] 2022-06-17 13:27
To be honest I'm not that much of a fan of the whole 'throws' Java-esque mechanic. It feels a bit heavy and long-winded for a language such as TypeScript.

It's just that the way TypeScript interprets the type theory is too lax. So it leaves this proposal as the only option to be able to solve the underlying issue I exposed in https://github.com/microsoft/TypeScript/issues/49549

**Closed** 2022-06-19 18:00 UTC
Labels: Duplicate
