### ISSUE TITLE
Applying a constrained generic with type parameters as the argument type doesn't properly catch constrained fields

### ISSUE THREAD

**Issue by shapirone** [microsoft/TypeScript#52309] opened 2023-01-19 20:07 UTC
# Bug Report
### 🔎 Search Terms
generic constraints, generic types, multiple generics, generic type variable, type parameters

### 🕗 Version & Regression Information
This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics.

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBACgTge0nYBLCBnAKuaBeKAbwG0BrCEALg2DlQDsBzAXUqgEN6QBfAbgChQkKACUIARwCuqOBAAm8JBBTpsuADyKwGKBAAewCPTk6tytJhyQAfFAIAKAKJ6AxgBtJciOvIgEAM1hEbQAaKAwQAFsAIwQ3awBKYmYBfgZDOH92F2gAeWiAKwgXYCtvLR19Q2NTYPNVMrCxKRl5Ct0DIxNRCWlZBTqVSw0K61tCfigoMEGLDDYKgSnZFv6AfjZmvrbgjCWOOTlUNAR6djczIYwNqFi4iE4Bbn5+AHpXqCwAC2h-OLcEAB3BiMKAAEQg-gYEHyRRK03YGAwmCgwB+UEYRmUqBcOnSCFR6KE0AChOg7DgoKOshKbhAbw+31QOnOAMBOkkOmABMi7HI4UkskJ7GAZKgK22cg4cDg7BAUFOdKgLlOwHYDC56N8OlJaJJhWKwAA5DoZkori8VfQaODIdDYYa7FBNLsOtVupc5o0eqsdkhKp0aj7JZ6GiNdmN7F4ofRjqhTmwHSUyi7-U1eq0Bv7EnZxpMoO8oPQEEh+M9+BCYzCDSV7PnCGbkHM2BMplNDDQ2AAiL6oLv57ghfMSzNsYhdjvALthLvRRDkehhNyofmRCBd5gFj7qAC0O90MoQcAwYRAcoAhGWEi9C99fv8gSDbVWk8AAOrHL4AQUOcdO51DFEwERZFNWgTF6GxXEoHxDhiz1OAEVkehRQgqCi3YNcpUrBlPl7Fk3DZDkuQJYCkSgOQgXoMVKzgqVkD+OBImVU4jhOM43FRcAn1OKBAR+BCFUQ+Dn3Hdhf3YgDZlUDcYJ0DBIBcVAoXkMJokkUUXHYTkUSwABlVECQBZExWJHcMHYfwIFABVAj1cUM36aVZXlaIIB4yDbLFaNoSlbUFWo+yEBrY1TWkzBLVOG1K3tEKPzRH82PjDjAJ0AhU20N0ulqc0vVwdNfSzTKqmy4NM1SlNRjCWiSqDV9Kt2AqQwjawoztWN2LYSsElzIh80LYtS3LGLINfeLvwk5KpNy1Q6ymBtwvmPq21RTBgG7Xt+ymQdh0c+QxwnNbpygWd5yMKBl1XddN0LXd92LA9EGPMJJC+BUvkvbgEiAA)

### 💻 Code

```ts
type PropertiesType = {[key:string]: any};
type RequiredPropertiesType<Props extends PropertiesType> = (Exclude<keyof Props, symbol>)[];

interface JSONSchemaObjectType<
  Props extends PropertiesType,
  RequiredProps extends RequiredPropertiesType<Props>
> {
  properties: Props;
  required?: RequiredProps;
  additionalProperties?: boolean;
}

const DefineObject = <
  Props extends PropertiesType,
  RequiredProps extends RequiredPropertiesType<Props>,
  Def extends JSONSchemaObjectType<Props, RequiredProps>
>(definition: Def) => {
  // noop
}

DefineObject({
  properties: {
    test: "hi"
  },
  required: ["test", "broken like me"] // <-- no static type error
})
```

### 🙁 Actual behavior

The `required` array accepts values that are not keys used in it's sibling `properties`

### 🙂 Expected behavior

The `required` array is constrained to the keys used in it's sibling `properties`

**Comment by whzx5byb** [comment] 2023-01-20 17:45
You should explicitly provide the constraint as a context to help infer the correct type of `Props`:

```diff
const DefineObject = <
  Props extends PropertiesType,
  RequiredProps extends RequiredPropertiesType<Props>,
  Def extends JSONSchemaObjectType<Props, RequiredProps>
- >(definition: Def) => {
+ >(definition: Def & JSONSchemaObjectType<Props, RequiredProps>) => {
}

```

**Comment by shapirone** [comment] 2023-01-20 18:18
@whzx5byb this constrains the argument but causes any conditional typing that relies on `definition` being a generic to fail

**Comment by RyanCavanaugh** [comment] 2023-01-26 00:50
> this constrains the argument but causes any conditional typing that relies on definition being a generic to fail

Can you go into more detail? The above solution is effectively correct; there's not a way to exclude candidates from inference like you would need in order to make this to work.

**Comment by RyanCavanaugh** [comment] 2023-02-02 00:20
Treating as duplicate of #14829

**Comment by shapirone** [comment] 2023-02-02 01:15
Sorry for the silence here, I've been looking into the resulting conditional typing failure and haven't been able to reproduce what we're seeing in a simplified TS Playground. Applying the recommended solution appropriately applied the constraint on the `required` field, but caused static type test failures that I assumed were related to inference from our conditional typing.

I've since realized that the test failures we're seeing are resolved if we assign the result of `DefineObject` to a variable and reference that variable in the surrounding function call, rather than using `DefineObject` directly as the object value. Code sample below to illustrate

```ts
// This causes test failures in our inferred runtime typing
DefineFunction({
  input_parameters: {
    properties: {
      myObject: DefineObject({
        type: Schema.types.object,
        properties: { req: { type: "string" }, opt: { type: "string" } },
        required: ["req"],
      });
    },
    required: ["myObject"],
  },
});


// This does not
const MyObject = DefineObject({
  type: Schema.types.object,
  properties: { req: { type: "string" }, opt: { type: "string" } },
  required: ["req"],
});
  
DefineFunction({
  input_parameters: {
    properties: {
      myObject: MyObject
    },
    required: ["anObject"],
  },
});
```

I'm still working on providing a Playground example, but please let me know if this behavior is familiar to you, if I should close this issue and open a new issue when I have more details, or if a pointer to where this creates problems in our actual code base would be helpful 🙇

**Closed** 2023-02-04 18:00 UTC
Labels: Duplicate
