### ISSUE TITLE
🚨 Array .map() type too wide

### ISSUE THREAD

**Issue by regnaio** [microsoft/TypeScript#60542] opened 2024-11-20 04:02 UTC
### 🔎 Search Terms

[TypeScript Playground Link](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBACgQQJICUDKMC8MDaAoGQ3AcgENiAaGABgF0KCidiAjSmARnscOeHYBM3WjFIQYoSFADcePJOgwAwgHkAckoQAVAKJrtOgCJZ4ydADoAtqQAOACgBupADYBXAKZYAfDAAGAEgBvJzd3HDoAXwBaIJCPHC4I31FxBSgASlk8KABPG08lcGBSKHcwEvcAExM7XPyQADNldU1dfV1DdJwwV0sWdwAnWlkgA)

### 🕗 Version & Regression Information

Unknown

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYewdgzgLgBACgQQJICUDKMC8MDaAoGQ3AcgENiAaGABgF0KCidiAjSmARnscOeHYBM3WjFIQYoSFADcePJOgwAwgHkAckoQAVAKJrtOgCJZ4ydADoAtqQAOACgBupADYBXAKZYAfDAAGAEgBvJzd3HDoAXwBaIJCPHC4I31FxBSgASlk8KABPG08lcGBSKHcwEvcAExM7XPyQADNldU1dfV1DdJwwV0sWdwAnWlkgA

### 💻 Code

```ts
const PAIRS = [
    ['a', 0],
    ['b', 1],
    ['c', 2],
] as const;

const CONCATENATED = PAIRS.map(value => `${value[0]}-${value[1]}` as const);

type Concatenated = (typeof CONCATENATED)[number];
```

### 🙁 Actual behavior

If you hover over `Concatenated`, you can see that its type is `type Concatenated = "a-0" | "a-2" | "a-1" | "b-0" | "b-2" | "b-1" | "c-0" | "c-2" | "c-1"`.

### 🙂 Expected behavior

The expected type should instead be `type Concatenated = "a-0" | "b-1" | "c-2"`.

**Comment by jcalz** [comment] 2024-11-20 04:46
TS doesn't have direct support for *correlated unions* as described in #30581. The only support is for generics of the form described at #47109, which is kind of yucky for a case like this:

```ts
type PairFor = { [T in typeof PAIRS[number] as T[0]]: T[1] }
type MapRet<K extends keyof PairFor> =
    { [P in K]: `${P}-${PairFor[P]}` }[K]

const CONCATENATED =
    PAIRS.map(<K extends keyof PairFor>(
        value: readonly [K, PairFor[K]]
    ): MapRet<K> => `${value[0]}-${value[1]}` as const);

type Concatenated = (typeof CONCATENATED)[number];
// type Concatenated = "a-0" | "b-1" | "c-2"
```
[Playground link](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBACgQQJICUDKMC8MDaAoGQ3AcgENiAaGABgF0KCidiAjSmARnscOeHYBM3WjFIQYoSFADceKAE8ADgFN4pAJYAnAGIhNWGAG9cAFRjqwMBSpAAzeMnQ4wAVwC2LZZpFiYJnHS0AFx+OFwwAL5ySqoAsqSKKMpQADwA0jDKAB5QymAAJuIA1srydmpaupoAfFg8Rrhw5pZpwTAABgAkhnARALTdcBo6ejhwtBHtkTiteHiS0DAAwgDyAHJLCCYAomtb2wAidUQOqGgAdG4JABTpmTl5hTAlZfZDlXrV1-UnAG6kABsXMoQpplKR8uAAfJcGkqO8RpoZrRaPUAJQheKJZLpWqYWpdQz-IHKAITAZEwHAsITKa+BZQNGyaIqZbgYCkXJgTnKfIGa7WZTlVYbfZ7HYHNHOdyebyyAD08qsMTZYA5XJ5fOwACJSH1qNqYAAfGDalh9DiGk3a4B9ATaoA)

I don't know if this is considered a duplicate of #30581 or a design limitation.

**Closed** 2024-11-29 01:33 UTC
Labels: Design Limitation
