### ISSUE TITLE
Comments on PropertyDeclaration nodes not honored by the TS transform.

### ISSUE THREAD

**Issue by alxhub** [Microsoft/TypeScript#22497] opened 2018-03-12 21:28 UTC
**TypeScript Version:**  2.7.2

**Search Terms:** PropertyDeclaration

**Code**
```
function addComment(property: ts.PropertyDeclaration): void {
  ts.addSyntheticLeadingComment(property, ts.SyntaxKind.MultiLevelCommentTrivia, 'this comment will never show up');
}
```
**Expected behavior:**

The comment appears in the generated JS file.

**Actual behavior:**

The comment is missing from the generated JS file.

**Playground Link:** n/a

**Related Issues:**

**More Info:**

The comment is dropped in the `ts.ts` transform function `addInitializedPropertyStatements`. As part of transforming the `PropertyDeclaration` nodes into `Statement`s, their comments are forgotten:

https://github.com/Microsoft/TypeScript/blob/master/src/compiler/transformers/ts.ts#L1219

**Comment by j-oliveras** [comment] 2018-03-13 11:04
Duplicate of #17689 and #22377.

Probably solved by #22141. You can try it with a [nightly build](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md).

**Closed** 2018-03-28 21:11 UTC
Labels: Duplicate
