### ISSUE TITLE
DocumentOrShadowRoot.adoptedStyleSheets is missing in lib.dom.d.ts (constructible style sheets spec)

### ISSUE THREAD

**Issue by felixfbecker** [microsoft/TypeScript#30022] opened 2019-02-21 13:49 UTC
**TypeScript Version:**  3.4.0-dev.20190220

**Search Terms:**
CSS constructable stylesheets adoptedStyleSheets shadow root

Shipped in Chrome and polyfillable.

Spec: https://wicg.github.io/construct-stylesheets/
Blog post: https://developers.google.com/web/updates/2019/02/constructable-stylesheets

**Comment by RyanCavanaugh** [comment] 2019-02-27 17:34
Draft/experimental APIs should be provided as out-of-band lib files, not in the shipping DOM. We'll revisit when this leaves experimental phase

**Comment by jogibear9988** [comment] 2019-10-21 16:44
Also shipped in FireFox

**Comment by meyfa** [comment] 2022-07-03 11:57
I'm pretty sure this is a standard thing by now, see the [Compatibility Table on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/adoptedStyleSheets#browser_compatibility) and the [Specification by CSSWG](https://drafts.csswg.org/cssom/#dom-documentorshadowroot-adoptedstylesheets). May we revisit?

**Comment by RyanCavanaugh** [comment] 2022-07-05 21:39
Sure

**Comment by meyfa** [comment] 2022-08-26 11:41
Seems to be fixed in TS 4.8! 🎉

**Comment by cedx** [comment] 2022-08-26 17:29
Confirmed on my side: with TS 4.8.2, it's OK.

**Comment by jakebailey** [comment] 2023-07-09 21:22
This was fixed in #49596.

**Closed by jakebailey** 2023-07-09 21:22 UTC
Labels: Suggestion, Help Wanted, Domain: lib.d.ts
