### ISSUE TITLE
VScode Occurrences Highlight has issues with Template strings and strings

### ISSUE THREAD

**Issue by thepont** [microsoft/TypeScript#45134] opened 2021-07-21 03:15 UTC
I'm not certain if this is an issue with TmLanguage or VSCode, but this issue only seems to happen when viewing Typescript or JavaScript files.

With `editor.occurrencesHighlight` set to `true` VSCode seems to incorrectly highlight entire strings as word occurrences unless another token is found in the string such as an escape char or template substitution element. 

The `editor.occurrencesHighlight` feature "controls whether the editor should highlight semantic symbol occurrences" and generally when working will highlight occurrences of the current selected symbol.

**Code**

```ts
const test1 = "Test String"; // Highlights the entire string when the cursor is within the string definition 
const test2 = "Test String \t"; // Does not highlight the entire string when the cursor is within the string definition (Expected Behavior)
const test3 = `
    Test
    Template
`; // Highlights the entire string when the cursor is is within the string definition
const test4 = `
    Test
    Template
    \t
`; // Does not highlight the entire string when the cursor is is within the string definition (Expected Behavior)
const test5 = `
    Test
    Template
    ${test1}
`; // Does not highlight the entire string when the cursor is within the string definition  (Expected Behavior)
```

**How it's designed to work**

```ts
const TEN = 10;
const test = 10; // putting your cursor on 10 does not highlight anything
console.log(test); // putting your cursor on test highlights both test and the definition of test 
```

**Comment by IllusionMH** [comment] 2021-07-21 10:11
Looks like duplicate of #43292

**Comment by thepont** [comment] 2021-07-21 23:11
Thanks @orta @IllusionMH, it certainly is a dupe.

**Closed** 2021-07-24 18:00 UTC
Labels: Duplicate
