### ISSUE TITLE
A computed property name in an interface must directly refer to a built-in symbol

### ISSUE THREAD

**Issue by nbransby** [Microsoft/TypeScript#13190] opened 2016-12-28 01:17 UTC
**TypeScript Version:**  2.1

When will TypeScript be able to type check this:

```ts
const location = Symbol("Quick reply location")
const onText = Symbol("Text message responder")
const onLocation = Symbol("Location message responder")
const onImage = Symbol("Image message responder")

interface ResponseHandler {
    [quickReply: string]: () => void
    [location](lat: number, long: number): void
    [onText](text: string): void;
    [onLocation](lat: number, long: number): void;
    [onImage](url: string): void;
}
```
What I would like it to do is verify the methods defined on an object conforming to this interface have the right parameters based on the property symbol / type (in case of string)

**Comment by aluanhaddad** [comment] 2016-12-28 05:22
How would an implementation acquire the symbol for say, `Location`?

**Comment by nbransby** [comment] 2016-12-28 12:31
```typescript
let handler: ResponseHandler = {
        [location](lat: number, long: number) {
            console.log(`User located at ${lat}, ${long}`);            
        }
    }
```

**Comment by aluanhaddad** [comment] 2016-12-28 14:58
And where does that symbol come from? Is it something exported by the module that exports the interface?

**Comment by nbransby** [comment] 2016-12-28 18:29
Yes it is defined above the interface in the example

**Comment by mhegazy** [comment] 2016-12-28 18:32
Duplicate of https://github.com/Microsoft/TypeScript/issues/5579

**Comment by aluanhaddad** [comment] 2016-12-28 23:41
@nbransby right, of course! for some reason I thought you were using modules. I don't know why, as you do not in your example. 
Regardless, since each instantiation of a non-well-known symbol is unique, it would make it impossible for consumers to implement the interface without acquiring the original instantiation. Perhaps that is desirable in your use case though.

**Comment by nbransby** [comment] 2016-12-29 01:32
Yes thats exactly the use case im after. My example is non-module based for simplicity but the symbols would be exported with the interface

**Closed** 2016-12-30 18:08 UTC
Labels: Duplicate
