### ISSUE TITLE
tsconfig.json inheritance needs an "off" switch?

### ISSUE THREAD

**Issue by Kaelum** [Microsoft/TypeScript#16838] opened 2017-06-29 20:47 UTC
It would be nice if there was a way to override/remove a setting in a tsconfig.json that "extends" a base configuration file.  Here is an example:

**tsconfig.base.json**:
```
{
	"compilerOptions": {
		"outDir": "./Scripts/.tsbuild/",
		"declaration": true,
		"declarationDir": "./Scripts/types/"
	}
}
```

**tsconfig.json**:
```
{
	"extends": "tsconfig.base",
	"compilerOptions": {
		"outFile": "../../dashboard.js",
		"declarationDir": null
	}
}
```

We've setup tsconfig.base.json file for transpiling each TypeScript file into individual JavaScript files for modular objects, but we also need to be able to build single file libraries.  If I can't turn off the "declarationDir" setting, I get build errors.  Setting this to null appears to turn off the build errors, but I get a warning that this setting can only be a string.  This is only an issue with conflicting settings.

However, I'm not entirely sure how the TypeScript team has envisioned this.  Should we have multiple base configurations, some base configurations extending others, and then have the application (library) tsconfig.json extend from one of those?  If not, then we need to be able to turn "off" a setting that was defined in a base configuration.

**Comment by yahiko00** [comment] 2017-06-29 20:51
Instead of null, an empty string won't do?

**Comment by Kaelum** [comment] 2017-06-29 21:53
@yahiko00 I tried an empty string (""), and it results in the same build error.

**Comment by mhegazy** [comment] 2017-08-23 18:28
Duplicate of https://github.com/Microsoft/TypeScript/issues/14184

**Comment by mhegazy** [comment] 2017-09-06 19:01
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-06 19:01 UTC
Labels: Duplicate
