### ISSUE TITLE
Output line and column as `:line:column` instead of `(line,column)`

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#18838] opened 2017-09-29 09:25 UTC
I use iterm2 as my terminal. When I run `tsc -w` I want errors to be clickable along with their filenames, lines and columns. Right now, only the filename is clickable.

I think if we just output in the following syntax
```ts
filename:line:column
```
it will recognize lines and columns as clickable as well. As you can se here:

![screen shot 2017-09-29 at 11 21 30](https://user-images.githubusercontent.com/1324476/31009613-6215c022-a508-11e7-8ca5-9dff49e0048e.png)

Whereas in the `tsc` case:

![screen shot 2017-09-29 at 11 22 12](https://user-images.githubusercontent.com/1324476/31009651-8d4cc04c-a508-11e7-966f-4c40ec85b68b.png)

**Comment by kitsonk** [comment] 2017-09-29 11:04
There is a lot of downstream tooling that depends on the current behaviour. Changing it would cause lots of other regressions in already existing tooling.  Why not raise an issue with iterm2 to allow extension of pattern matching to make it more flexible?

**Comment by tinganho** [comment] 2017-10-02 15:11
FWIW, I checked Safari, Chrome, Firefox and Node.js. They all use `filename:line:column` syntax. Preferably, I think TypeScript should output whatever Node.js output to be consistent.

And I tried to get info about whether using parens`(line, column)` was a valid URI syntax compared to using colon syntax. But couldn't find any.

**Comment by mhegazy** [comment] 2017-10-03 01:01
seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/16978

**Comment by mhegazy** [comment] 2017-10-17 16:28
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-17 16:28 UTC
Labels: Duplicate
