### ISSUE TITLE
Provide more detailed metadata for decorators

### ISSUE THREAD

**Issue by joesonw** [Microsoft/TypeScript#12577] opened 2016-11-30 08:06 UTC
#Proposal
Current emitted decorator metadata, only contains minimal typing information. My suggestion is to provide detailed information. Such as, nested type (generic type).

# Example

## 1.  resolve nested typing.

```
class A {
    @Foo
    propA: Map<string, Promise<number>>;
    @Bar
    propA: Map<string, Map<List<number>, boolean>>;
    @Baz
    methodA(): Map<Promise<number>, string>;
}
```

both `@Foo`'s `deisng:type` and `@Foo`'s `design:returntype` and each `design:paramtypes` should be the same.

resulting metadata:
```
@Foo: [Map, [string, [Promise, [number] ] ] ];
@Bar: [Map, [string, [Map, [ [List, [number] ] , boolean] ] ];
@Baz: [Map, [ [Promise, [number] ] , string] ];
```

logic:
for any generic type.
`Type<...Arguments>` -> `[Type, [...Arguments]]`, recursively.

## 2. Retrieve parameter names
new metadata `design:paramnames`, in the same order of `design:paramtypes`.

## 3. ParamTypes and ParamNames for class decorators

```
@Foo
class A {
	propA: string;
	methodA(): number;
}
```

similar to `deisng:paramtypes` and `design:paramnames` of a method decorator. It retrieves paramter types and paramnames of each property and function even props were not assigned with a initial value. param type for a method should be `Function` in this case.

**Comment by joesonw** [comment] 2017-01-03 08:46
Would this be accepted as a feature? If so, I can submit a PR for this.

**Comment by mhegazy** [comment] 2017-04-27 16:37
Duplicate of  https://github.com/Microsoft/TypeScript/issues/11362

As noted in https://github.com/Microsoft/TypeScript/issues/14971#issuecomment-297580549, reflection and runtime type serialization is outside the scope of the TypeScript project in the time being.

Relevant discussion in https://github.com/Microsoft/TypeScript/issues/3628.

**Closed by mhegazy** 2017-04-27 16:37 UTC
