### ISSUE TITLE
Type guard does not work for object

### ISSUE THREAD

**Issue by kkmuffme** [microsoft/TypeScript#54238] opened 2023-05-13 16:18 UTC
# Bug Report

### 🔎 Search Terms

typeof object type guard

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I searched all issues

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/FAMwrgdgxgLglgewgAgEYEMBOAKZWDmAXHhAJ7ICUyA3sMvcnCMrjKQA4CmCzByAvIOQByBKgBWnWMMo06DBVCQBnGMhAIEAvJnwBuefQC+wQ42asO3XroFDhqzHAj4ZVWgsUq1Grfx36ZiYmoJCwiCi+uATEjs74sh4MShCqjDCcALbaAFIAygDyAHIAdOxYypzRthQGZkwsyGxcPOlZdv6iElIwbnKeyd7qmtpwGZkGCsGmwEA

### 💻 Code

```ts
function bar( arg: any ) {
    if ( typeof arg === 'object' ) {
        const foo = arg;
    }

    if ( typeof arg === 'string' ) {
        const foo = arg;
    }
}

function foo( arg: string ) {
    const item = JSON.parse( arg );

    if ( typeof item === 'object' ) {
        const foo = item;
    }
}
```

### 🙁 Actual behavior

Type guard for "object" did not work (still any), while it works fine for string.

### 🙂 Expected behavior

foo should be object in line 4 and 16.
There is no mention that type guard of object does not work: https://www.typescriptlang.org/docs/handbook/2/typeof-types.html#limitations
In fact, it even states that it DOES work:
https://www.typescriptlang.org/docs/handbook/advanced-types.html
>These typeof type guards are recognized in two different forms: typeof v === "typename" and typeof v !== "typename", where "typename" can be one of [typeof operator’s return values](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#Description) ("undefined", "number", "string", "boolean", "bigint", "symbol", **"object"**, or "function").

**Comment by MartinJohns** [comment] 2023-05-13 16:47
Probably a duplicate of https://github.com/microsoft/TypeScript/issues/6301#issuecomment-168136962.

**Comment by MartinJohns** [comment] 2023-05-13 18:43
The question is: Would it really be helpful to narrow it to `object | null`? You still can't access any properties, and it'll force the user to add a type assertion to continue to use it.

**Comment by RyanCavanaugh** [comment] 2023-05-15 18:41
This doesn't seem like a great trade-off in general. Downcasting to `string` or `number` is useful because those types are known to have particular characteristics, but downcasting to `object` just leaves you worse off than you were before in the vast majority of cases without providing any additional type safety.

**Closed** 2023-06-08 03:40 UTC
Labels: Not a Defect
