### ISSUE TITLE
"Maximum call stack size exceeded" Involving Mapped Types and Generic Type Inference

### ISSUE THREAD

**Issue by tomb-pss** [Microsoft/TypeScript#20064] opened 2017-11-16 07:05 UTC
**TypeScript Version:**  2.6.1

**Code**

```ts
type Foo<T> = {
    [K in keyof T]: Foo<T[K]>;
};

interface Bar<T> {
    bar: Foo<T> | Bar<T>;
}

function a<T>(fooBar: Foo<T> | Bar<T>) {
    return b(fooBar); //Doesn't work
//    return b<T>(fooBar); //Works
}

function b<T>(fooBar: Foo<T> | Bar<T>) {
}
```

**tsconfig.json**
```json
{
    "compilerOptions":
    {
        "target": "ES2015",
        "strict": true
    }
}
```

**Expected behavior:**
Should compile successfully.

**Actual behavior:**
Compiler crashes with the following output:
```
tsc.js:58005
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at instantiateType (C:\Users\blind\projects\pss\acorn\node_modules\typescript\lib\tsc.js:25752:33)
    at instantiateType (C:\Users\blind\projects\pss\acorn\node_modules\typescript\lib\tsc.js:25779:49)
    at C:\Users\blind\projects\pss\acorn\node_modules\typescript\lib\tsc.js:25603:42
    at Object.map (C:\Users\blind\projects\pss\acorn\node_modules\typescript\lib\tsc.js:469:29)
    at getAnonymousTypeInstantiation (C:\Users\blind\projects\pss\acorn\node_modules\typescript\lib\tsc.js:25688:40)
    at instantiateType (C:\Users\blind\projects\pss\acorn\node_modules\typescript\lib\tsc.js:25763:32)
    at getTemplateTypeFromMappedType (C:\Users\blind\projects\pss\acorn\node_modules\typescript\lib\tsc.js:23662:21)
    at inferTypeForHomomorphicMappedType (C:\Users\blind\projects\pss\acorn\node_modules\typescript\lib\tsc.js:27543:32)
    at inferFromObjectTypes (C:\Users\blind\projects\pss\acorn\node_modules\typescript\lib\tsc.js:27757:48)
    at inferFromTypes (C:\Users\blind\projects\pss\acorn\node_modules\typescript\lib\tsc.js:27717:29)
```

The issue seems to be a problem with inferring the generic parameter when calling b() inside of a(). Explicitly supplying the parameter fixes the issue.

**Comment by sandersn** [comment] 2017-11-30 17:54
Looks like a duplicate of #19951

**Closed by sandersn** 2017-11-30 17:54 UTC
Labels: Bug
