### ISSUE TITLE
Auto import suggests from umd instead of module in ionic 3

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#25204] opened 2018-06-25 21:40 UTC
_From @surajrao on June 25, 2018 9:19_

- VSCode Version: 1.24.1
- OS Version:Mac OS High Sierra (10.13.5)

Steps to Reproduce:

1. Start a new ionic project.

`ionic start myApp tabs`

2. Try to import a component from ionic-angular.

The auto import seems to import from `ionic-angular/umd` which has `ionic-angular/umd/index.d.ts`
instead of `ionic-angular` which also includes `ionic-angular/index.d.ts`.

![screen shot 2018-06-25 at 2 32 55 pm](https://user-images.githubusercontent.com/5566582/41841534-2fe22972-7886-11e8-8fe4-dafae634a31c.png)

This results in the below error on running.

```
    Uncaught Error: Cannot find module "."
        at webpackMissingModule (index.js:3)
        at e.code (index.js:3)
        at Object.<anonymous> (index.js:9)
        at __webpack_require__ (bootstrap 62d6a5897825ac327001:54)
        at Object.690 (slide.transition.ts:67)
        at __webpack_require__ (bootstrap 62d6a5897825ac327001:54)
        at Object.495 (main.js:1885)
        at __webpack_require__ (bootstrap 62d6a5897825ac327001:54)
        at Object.487 (notification-api.ts:6)
        at __webpack_require__ (bootstrap 62d6a5897825ac327001:54)

```

Related StackOverflow post: [ionic-uncaught-error-cannot-find-module](https://stackoverflow.com/questions/51015815/ionic-uncaught-error-cannot-find-module-when-importing-a-service-provider)
Does this issue occur when all extensions are disabled?: Yes

Is this because of the ionic project structure or an issue with vscode import?

"ionic-angular": "3.9.2"    
typescript version in workspace - 2.9.1

_Copied from original issue: Microsoft/vscode#52786_

**Comment by mjbvz** [comment] 2018-06-25 21:45
Using 3.0.0-dev-20180623, we get these suggestions:

![screen shot 2018-06-25 at 2 44 15 pm](https://user-images.githubusercontent.com/12821956/41877487-49a7bea8-7886-11e8-915f-acdebee6c2c6.png)

With TS 2.6.x, we get the proper suggestion

**Comment by aparkertg** [comment] 2018-06-26 21:59
Same issue here with IonicModule. 

Auto import recommends "import { IonicModule } from 'ionic-angular/umd';" which generated the same exact errors. 

I resolved it by manually adjusting to "import { IonicModule } from 'ionic-angular';"

**Comment by andy-ms** [comment] 2018-06-26 23:54
In `main.ts`, I'm not getting any suggestions from `../../../node_modules` in `typescript@next`:

![image](https://user-images.githubusercontent.com/19274678/41945323-4d52569a-7961-11e8-9f1a-7895b778636c.png)

There's an option to import from the original declaration, which is in `node_modules/ionic-angular/umd/toast/toast.d.ts`, but it's the second suggestion, and doesn't affect completions, so that seems to be working as intended.

@aparkertg What file are you in when you try the import? Also, what operating system are you on?

**Comment by andy-ms** [comment] 2018-07-03 23:34
May be a duplicate of #25279. Could you test again with tomorrow's `typescript@next` release.

**Comment by redwolf2** [comment] 2018-07-06 17:07
This error messages will result in `Cannot import module '.'` error messages. In order to avoid this, one has to remove the umd sub directory from the import.

**Comment by eduardoRoth** [comment] 2018-07-15 17:10
I'm having the same issue 😢

**Comment by Maraket** [comment] 2018-07-16 04:53
Just started using VSCode, and enjoying it, though finding my app all of a sudden stopped working, I realize it's polluted every instance of ionic-angular with ionic-angular/umd (I did save them, but I made the dangerous assumption that VSCode knew better), and sure enough ran into the issue everyone else is

**Comment by us-concrete-sdiwan** [comment] 2018-07-16 15:56
I too face this issue, how to remove /umd  from import statement

**Comment by Maevus** [comment] 2018-07-18 15:50
I had a similar problem with ionic-angular  when I update VSCode today (1.25.1). Had to revert to a previous commit and do a code compare to figure it out. It also tidied all imports to barrels etc - which is could be cool but I've found ionic-angular to produce errors on occasion when using barrels, and have sometimes had to explicitly import a desired class, so in this case import tidying while a neat idea is problematic.  Love VSCode and TS generally though!

**Comment by ffMathy** [comment] 2018-07-19 12:33
I've been having this issue too.

**Comment by Voricles** [comment] 2018-07-19 12:51
I have been debugging this for 2 days now, thinking that I somehow messed up my code. Feeling frustrated.

**Comment by surajrao** [comment] 2018-07-20 05:25
@andy-ms I just checked by starting a new project with ionic. Seems like it is happening for `typescript@2.9.2` (The one installed with the stable vscode). I am not getting the issue in `typescript@3.1.0-dev.20180717` for the same new project.

Screenshots:

**2.9.2**
![screen shot 2018-07-20 at 10 50 05 am](https://user-images.githubusercontent.com/5566582/42984614-10c925e8-8c0b-11e8-8204-213148a720fe.png)

**3.1.0-dev.20180717**
![screen shot 2018-07-20 at 10 49 40 am](https://user-images.githubusercontent.com/5566582/42984625-239ecf38-8c0b-11e8-9b62-65baa66612bb.png)

**Comment by mhegazy** [comment] 2018-07-23 17:31
thanks @surajrao for confirming the issue is fixed in `typescript@next`. closing.

**Closed by mhegazy** 2018-07-23 17:31 UTC
Labels: Bug, Needs More Info

**Comment by moleisking** [comment] 2018-07-31 09:30
Wow. I had the same issue with "/umd" on type script ~2.6.2. I am sure the core issue is related to how typescript translates and how webpack handles this translation. I see the latest version of typescript is 3.0 so maybe a ^2.6.2 would make a difference.

**Comment by mhegazy** [comment] 2018-07-31 17:30
@moleisking please file a new ticket, and giving us enough context to enable us diagnose the issue.
