### ISSUE TITLE
Singleton types under the form of string literal types

### ISSUE THREAD

**Issue by Nevor** [Microsoft/TypeScript#1003] opened 2014-10-30 16:21 UTC
This proposal is based on a working prototype located at https://github.com/Nevor/TypeScript/tree/SingletonTypes

## String literal types extended to the whole language

This change would bring singleton types created from literal string to complete recent addition of type aliases and union types.  This would hopefully satisfy those that mentioned string enum and tagged union in previous PRs (#805, #186).

This addition would be short thanks to a concept that was already implemented internally for ".d.ts" files.

## Use cases 

Often operational distinction of function and values are done with an companion finite set of string that are used as tags. For instance events handler types rely on strings like "mouseover" or "mouseenter". 

Sometimes string are often themselves operating on a finite definite set of values that we want to convey this through specifications and have something to enforce it. 

And for more advanced typing, we sometimes use types themselves as informations to guide function usages, constraining a little further the base types.

## Current workarounds
There is no way to create string enum for now, the workaround is to manipulate variables assigned once and for all. This does not protect from typos that will gladly propagate everywhere a string is used.

When we want to implement tagged union types for symbolic computation, we must use some number enum coupled with subtyping and casting machinery, losing all type safety.

In general, advanced type constraint are done through classes and this put us further away from simple records that would have been used in javascript.

## Overview examples
```typescript
type result = "ok" | "fail" | "abort";

// "string enum"
function compute(n : number) : result {
  if(...) {
    return "ok";
  } else if (...) {
    return "fail";
 } else {
    return "crash"; // Error, not accepted
 }
}

function checkSuccess(o : result) : void { ... }

var res : result = compute(42);

checkSuccess(res); // OK
checkSuccess("crash"); // Error

res = "crash"; // Error

var message = res; // OK, message infered as string
var verbose = "Current status : " + res; // OK


// Specifications constrains
interface operationAction {
  name : string;
  id : number;
  status : result;
}

// Usable as and with regular types
var results : result[] = [compute(3), compute(27), "ok"]; // Ok
results = ["crash", "unknown"]; // Error

type error_level = "warning" | "fatal";

interface Foo<T> {
  foo : T;
}
interface Toto<U> {
  value : Foo<result> | { unknown : string; value : U };
}

var foo : Toto<error_level> = { foo : "ok" }; // OK
var foo : Toto<error_level> = { foo : "crash" }; // Error
var foo : Toto<error_level> = { unknown : "Unknown error", value : "warning" }; // OK
var foo : Toto<error_level> = { unknown : "Unknown error", value : "trace" }; // Error


// Disjoint union
type obj = { kind : "name"; name : string } | { kind : "id"; id : number } | { kind : "internal" ; id : number }

var o : obj = { kind : "name", name : "foo", id : 3 } 
var o : obj = { kind : "id", name : "foo", id : 3 } 
// Both object are strictly distinguished by their kind

var o : obj = { kind : "unknown", name : "something" }; // Error

type classical_obj : { name : string } | { id : number };

var c_o : classical_obj = { name : "foo", id : 3 }; // A supertype of both is assignable, we lose infos 

```
## Typing specifications
- any string literal as type "s" (StringLiteralType) where s is the content of the literal.
- every StringLiteralTypes are subtypes of string, the reverse is not true.
- two StringLiteralTypes are compatible if and only if they represent the same string literal.

```typescript
type ok = "ok"


var a : ok = "ok";
var b : "ok" = a; // OK

var a  : ok = "no"; // Error
var c : string = a; // OK 
var a : ok = c; // Error 
```

### Backward compatibility
This prototype is backward compatible (accepts programs that were accepted before) but in one case : 
```typescript
function ... {
  if (...) { 
    return "foo";
 } else {
    return "bar";
 }
}
```
The compiler will raise an Error saying that there is no common type between "foo" and "bar". This is because the compiler only accept one of the return type to be supertype and does not widen before.
We might add a special case for StringLiteralTypes and keep other types as is, or, do some widening and therefore accept empty records for conflicting records for instance.

### Error messages
It might confuse users that their literal strings are mentioned as types when they are expecting to see "string" even though this difference as no incidence on normally rejected string.
The compiler might display StringLiteralTypes as "string" whenever the conflict is not involved between two StringLiteralTypes.

## Extending type guards 
To be fully usable to distinguish records by type tags, type guards should be extended to take into account this kind singleton types. One would expect the following to work : 

```typescript
type obj = { kind : "name"; name : string } | { kind : "id" ; id : number };
var o : obj = ...;
if (o.kind == "name") {
  /* o considered as left type */
} else if(o.kind == "id")  {
  /* o considered as right type */
}
```

**Comment by fdecampredon** [comment] 2015-02-03 17:39
:+1: 
having this feature would be invaluable, I'm sorry to ask that but is it scheduled for a typescript version ?

**Comment by danquirk** [comment] 2015-02-03 21:46
We still need to talk about it a bit further but the idea was well liked. At the moment our near term schedule is fairly full with ES6 related features though.

**Comment by knuton** [comment] 2015-03-06 17:00
Thanks for working this out @Nevor, another big thumbs up for this suggestion! Our codebase could really benefit from this feature.

Most people coming from functional languages may first think of an addition closer to #186 (crazy thoughts of a TypeScript pre-processor were thought). But this *tagged union* (literally) approach seems much more idiomatic and a perfectly natural extension of TypeScript.

Are there any steps we could take to help with this? Any open questions to explore? What is missing?

**Comment by jrsnyder** [comment] 2015-04-22 17:09
:+1:

**Comment by RyanCavanaugh** [comment] 2015-04-27 23:40
Accepting PRs. With something like this, please include *lots* of tests with your PR :smile:

**Comment by knuton** [comment] 2015-04-28 12:42
Yay! :grinning: 

Can we clarify the intended scope? As far as I can tell, this issue brought up the following main ideas:

  1. Singleton types in the form of string literal types
  2. [Singleton types in the form of const-enum members](https://github.com/Microsoft/TypeScript/issues/1003#issuecomment-61130784)
  3. Allow type refinement by tag inspection (`foo.kind === "name"`)
  4. Allow for `switch` statements to serve as type guards

Which of these are within the scope for a suggested implementation? Does it make sense to tackle 1. and 2. together? Should 3. be treated as part of #1007?

**Comment by RyanCavanaugh** [comment] 2015-04-28 16:05
1 and 3 only, I think. 2 is probably separable; 4 is covered by #2388

**Comment by JsonFreeman** [comment] 2015-05-01 01:02
We may consider this for boolean literal types as well. They could be very useful for generators, as per issue https://github.com/Microsoft/TypeScript/issues/2983

**Comment by danielearwicker** [comment] 2015-05-01 11:50
I'm wondering whether this would allow forwarding to string literal overloads such as `document.createElement`. treating such overload sets like a *reusable* way to map runtime strings to compile-time interfaces, so for example, the caller can specify the type once (as a string literal) and have it checked both at compile and runtime:

    function safeQuerySelector<TTagName /* constraint? */>(sel: string, tagName: TTagName) {
  
        // To discover what createElement would return, given string type tagName
        var elem = ((x?: void) => x ? document.createElement(tagName) : null)();

        // actually do the query
        elem = <typeof elem>document.querySelector(sel);

        // validate that the found element is of the desired type
        if (!elem || elem.nodeName !== tagName.toUpperCase()) {
            throw new Error(`Selector ${sel} does not identify a ${tagName} element`);
        }
        return elem;
    }

    var a = safeQuerySelector(".crazyLink", "a");
    a.href = "blah"; // fine, as safeQuerySelector returned HTMLAnchorElement

But `TTagName` needs a constraint to ensure that it is a string. `TTagName extends string` is presumably wrong because it allows anything structurally compatible with `string`, which is not strict enough for DOM methods that want a real string.

Wouldn't be ideal to have to manually write down the union of all parameters acceptable to `createElement`:

    function safeQuerySelector(
        sel: string,
        tagName: string|"a"|"abbr"|"acronym"|"address"|"applet" 
                        //... and so on for ~100 cases

**Comment by JsonFreeman** [comment] 2015-05-04 17:50
@danielearwicker Actually, `extends string` would mean that it is really a string. Something structurally compatible with a string does not satisfy `extends string`. The one you are thinking of is `extends String` (note the capitalization). That is the structural one.

**Comment by tinganho** [comment] 2015-06-05 08:34
I'm just wondering how it should be dealt with if we want to extend the type with more string literals. 

Use case:
```typescript
type Event = "click" | "drag" | "touch";
declare function addEventListener(event: Event); 
addEventListener("click");
createEvent("dbclick");
addEventListener("dblick"); // error
```

**Comment by jbondc** [comment] 2015-06-05 19:26
@tinganho You'd be able to use:
```
type SomeEvents = "click" | "drag" | "touch";
type MoreEvents = SomeEvents | "dbclick";
declare function addEventListener(event: MoreEvents);
addEventListener("click");
addEventListener("dblick");
declare function addEventListener2(event: SomeEvents | "dbclick");
addEventListener2("click");
addEventListener2("dblick");
```

**Comment by JsonFreeman** [comment] 2015-06-05 22:19
We don't have a way to augment a type declared by a type alias, whether or not it's a union type. You'd have to do what @jbondc suggested.

**Comment by JsonFreeman** [comment] 2015-06-05 22:45
I'd like to clarify something about my interpretation of the proposal. Somebody please correct me if I'm wrong:

1. A string literal in type position denotes the string literal type associated with the given text
2. A string literal in a value position that is *not* contextually typed has type `string`
3. A contextually typed string literal has the string literal type associated with the text
4. Unlike the relation between enums and `number`, `string` is neither assignable to nor a subtype of a string literal type.

**Comment by JsonFreeman** [comment] 2015-06-05 22:47
5. The apparent type of a string literal type is the `String` interface type.

**Comment by jbondc** [comment] 2015-06-06 17:13
@JsonFreeman Not sure about (2), (3), currently working out details. Should have a patch you can review in a couple of days. Would help if you have test cases in mind. 

My expectation is:
```
var varStringA = "a"; // string type
let letStringA = "a"; // string type
const constStringA = "a"; // 'string set type' that allows only the value "a"
let letStringAB: "a" | "b" = "a"; // 'string set type' that allows only the values "a" | "b"
let letStringABC: "a" | "b" | "c" = "a"; // 'string set type' that allows only the values "a" | "b" | "c"

function foo(values: "a" | "b") {}

foo(varStringA); // error string not assignable to "a" | "b"
foo(letStringA); // error string not assignable to "a" | "b"
foo(constStringA); // ok
foo(letStringAB); // ok
foo(letStringABC);  // error  "a" | "b" | "c" not assignable to "a" | "b"

function fooInferReturn() { // infers string
   if(Math.random() > 0.5)   
       return "a";
   
   return "b";
}

function fooInferReturn() { // infers "a" | "b"
   const a = "a";
   const b = "b";
   if(Math.random() > 0.5)   
     return a;
   
   return b;
}
function fooInferReturnMixed() { // infers string (if any return value not const)
   const a = "a";
   if(Math.random() > 0.5)   
     return a;
   
   return "b";
}
```

**Comment by JsonFreeman** [comment] 2015-06-06 22:34
No, you are talking about constant propagation, which is based on how a certain entity is declared (whether it has the `const` keyword or not determines whether it is a string literal type or not). I am talking about flowing this information via types, and doing the discrimination based on contextual typing info. This is what we have done for tuples vs arrays. Namely, an array literal contextually typed by a tuple type has a tuple type. In a similar way, a string literal contextually typed by a string literal type has a string literal type (the thing you are calling a set type). This is in order to maintain backward compatibility.

**Comment by JsonFreeman** [comment] 2015-06-06 22:35
I will add that unless I misunderstood your proposal, the difficulty is that it does not maintain the same overload selection rules when you pass a string literal as an argument to a call.

**Comment by DanielRosenwasser** [comment] 2015-06-07 03:47
Yes, while it doesn't seem like typing `const`-declared strings as string literal types would be a problem, it unfortunately is:

```TypeScript
function foo() {
    const a = "hello";
    return a;
}

var x = foo();
x = "world";
```

Here, `a` would be typed as `"hello"`. `foo`'s return type is now `"hello"`. In turn, `x` is typed as `"hello"`, but now `x` cannot be reassigned any other string.

**Comment by JsonFreeman** [comment] 2015-06-07 06:04
@DanielRosenwasser With the contextual typing approach, you could still run into a similar thing. I'm modifying your example a bit to add a type annotation:
```ts
function foo(): "hello" {
    return "hello";
}

var x = foo(); // Inferred as "hello"
x = "world"; // Still an error
```

**Comment by DanielRosenwasser** [comment] 2015-06-07 07:53
> With the contextual typing approach, you could still run into a similar thing. 

But at that point you've opted into an explicit string literal type, whereas having `const` declarations implicitly do so is a breaking change, so I'm not seeing the issue.

**Comment by JsonFreeman** [comment] 2015-06-07 08:05
Yes, I agree. Just wanted to make sure.

**Comment by jbondc** [comment] 2015-06-07 12:33
@DanielRosenwasser @JsonFreeman I think it still works:
```
function foo() { // infer type "hello"
    const a = "hello";
    return a;
}

var x = foo(); // widens to string because x is *not* const
x = "world"; //ok

const y = foo(); // y has type "hello"
y = "world"; // hello
```

**Comment by DanielRosenwasser** [comment] 2015-06-07 18:37
I don't think that would be intuitive for users (it is inconsistent between types of declarations), but I can see some merits to that approach.

**Comment by JsonFreeman** [comment] 2015-06-07 20:55
Neither the contextual type approach nor the widening approach results in different treatment for const declarations versus variable declarations. Unless somebody voices a clear advantage for the widening approach, I favor contextual typing.

**Comment by jbondc** [comment] 2015-06-09 13:11
@JsonFreeman The thing I call a 'set type' is not a string literal type:
https://github.com/Microsoft/TypeScript/blob/2fafd71763143446c2a6bfe2eab1736aa1f1e23d/src/compiler/sets.ts

It's a set type, what I'm doing is mapping string literals to 'BitSets' which are super easy to compare. The following test cases work:
https://github.com/Microsoft/TypeScript/blob/2fafd71763143446c2a6bfe2eab1736aa1f1e23d/tests/cases/labs/sets/string.ts
https://github.com/Microsoft/TypeScript/blob/2fafd71763143446c2a6bfe2eab1736aa1f1e23d/tests/cases/labs/sets/number.ts
https://github.com/Microsoft/TypeScript/blob/2fafd71763143446c2a6bfe2eab1736aa1f1e23d/tests/cases/labs/sets/boolean.ts

https://github.com/Microsoft/TypeScript/tree/2fafd71763143446c2a6bfe2eab1736aa1f1e23d/tests/cases/labs

For contextual typing, I added this test:
https://github.com/Microsoft/TypeScript/blob/2fafd71763143446c2a6bfe2eab1736aa1f1e23d/tests/cases/labs/sets/stringSetInferred.ts

Think we can create a special type parameter '<string extends "a" | "b">' that is inferred from string|number|boolean literals.

I'm fine with any approach that performs well :wink: and gives a lot of flexibility.

**Comment by JsonFreeman** [comment] 2015-06-13 23:27
One interesting question is whether a string literal type should be nullable (allow null / undefined as a value). Right now, our type system has types for null and undefined, but these types are assignable to all types. Should string literals be an exception because they denote one particular value? The motivation is this:
```ts
interface StringWrapper {
     kind: "string";
     value: string;
}
interface ArrayWrapper {
     kind: "array";
     value: string[]
}
var v: StringWrapper | ArrayWrapper = { kind: undefined, value: ["hello"] }; // Suppose this assignment is allowed
if (v.kind === "array") {
    // Clearly, v has type ArrayWrapper here
}
else {
    // Process of elimination suggests that v is of type StringWrapper, but that is not true.
    v.value; // string[]
}
```
There are 3 options:

1. Null and undefined are not assignable / subtype of a string literal type or a union of string literal types. This would be intuitive, but somewhat against the grain in terms of the existing rules in the type system.
2. Null and undefined are assignable, and we don't allow a string literal check to narrow a type in the false branch of a type guard construct. This is safe, but we give up some usability.
3. Null and undefined are assignable, and string literal checks can narrow in both branches. This means string literal type guards are kind of fuzzy, and can be misleading at times, but they are usable, and we get to keep our type system fully nullable.

Thoughts??

**Comment by nycdotnet** [comment] 2015-06-14 07:23
Interesting dilemma!  I've been thinking about this for an hour or so, and have typed up three different responses to how there was an obvious choice and the rest were evil.

I must say that the most vexing part of this code sample is `// Suppose this assignment is allowed`.

My selections in order of decreasing preference:
  * Implement non-nullable types holistically and get choice 1 for free, choice 2 for non-nullable types.
  * Go with choice 3 for now, make it an error when non-nullable types come out (this is an example of a good breaking change).
  * Implement choice 3 and create a new switch `--strictTypeGuardNarrowing` which lets people opt-in to choice 2 :bike: :house:

I don't think choice 1 fits with today's TypeScript.

**Comment by jbondc** [comment] 2015-06-14 12:50
```
var v: StringWrapper | ArrayWrapper = { kind: undefined, value: ["hello"] }; // error (on node kind): The value 'undefined' is not in the set "string" | "array"
if (v.kind === "array") {
    // Clearly, v has type ArrayWrapper here
}
else {
    // Process of elimination suggests that v is of type StringWrapper
    v.value; // string[]
}
```
If you create a union of string literals, numeric literals or boolean literals, this does not include the value 'null' or 'undefined'.

So yes you get an easy way to declare strict non-nullable types.

You can however add them:
```
type someStringsWithNull = "a" | "b" | null;
type someStringsWithNullUndefined = "a" | "b" | null | undefined;

function foo(){ // infers string set type  "a" | "b" | null
   return "a";
   return "b";
   return null;
}

function foo(){ // infers string set type  "a" | "b" | null | undefined;
   return "a";
   return "b";
   return null;
   return undefined;
}

function foo(){ // infers string set type  "a" | "b" | null | undefined;
   return "a";
   return "b";
   return null;
   throw "something"; // infers undefined
}
case Base {}
class A extens Base {}
class B extends Base {}
function narrowMe(something: Base){ // infers string set type  "a" | null
   return "a" is A;
   return null is B;
}
```
Type narrowing by constant value:
```
if(narrowMe(something) === null) {
   something; // B
} else {
     something; // A
}
```
Similarly, a 'number set' does not include Infinity | NaN:
```
type numbers = 1 | 2 | 3 | 4 | 5;
let n: numbers = null; // error the value 'null' is not in set 1...5
n = NaN; // error the value 'NaN' is not in set 1...5
n = 5;
n = 10; // error the value '10' is not in set 1...5
```
You can however add them:
```
type numbersAndFriends = 1 | 2 | 3 | 4 | 5 | NaN | Infinity | null | undefined;
let nf: numbers = null;
nf = undefined;
nf = NaN;
nf = Inifinity;
```

**Comment by yortus** [comment] 2015-06-15 03:11
I think option 1 is correct and preferrable for the kind of type-level reasoning that singleton types are able to bring to the language.

I think of a singleton type as a subset of a broader type where the subset is a single value from the broader set, ie a singleton set. `null` and `undefined` are always members of the broader set, but a singleton type is a subset and can therefore exclude these two values.

If singleton types implicitly always also include `null` and `undefined` as allowed values, they are not really singletons at all, they are 'tripletons' or something, with the weaker powers of type-level reasoning that go with that.

eg `var abc: 'abc'` is stating explicitly that `abc` can only have the value `'abc'`. `null` and `undefined` are explicitly not members of this type's value set.

Is there some scenario using singleton types where assigning `null` and/or `undefined` would be useful? Or is this perhaps more an issue with the way the compiler currently works? (Or both?)

**Comment by nycdotnet** [comment] 2015-06-15 14:45
@yortus A very straightforward example that I can think of is setting the value of a variable programmatically, e.g.:

```typescript
function numberRangeName(num: number)
    var x: "positive"|"negative"|"zero";  // x is undefined here.
    if (num > 0) {
        x = "positive";
    }
    ///etc...
    return x;
}
```
Of course you could always have a `"NotSure"` in there, but then that's basically the same thing as allowing undefined, just more explicit.  I know you could write this simple example slightly differently to eliminate the temporary variable, but more complex examples might require it.

**Comment by JsonFreeman** [comment] 2015-06-15 17:40
@jbondc, you cannot denote the null type and undefined types explicitly today. I'm not sure there is value in adding those words in the type syntax, rather than some sort of nullability marker.

To @yortus's comment, I was going to say that null and undefined are not really in the spirit of singleton types, and having the types be nullable is just a type system limitation. But I am actually convinced by @nycdotnet's example, where the value is set after the declaration point. If we made these types non-nullable, then you would have to modify the code in that example to take advantage of var scoping:
```ts
function numberRangeName(num: number)
    if (num > 0) {
        var x: "positive"|"negative"|"zero" = "positive";
    }
    ///etc...
    return x;
}
```
But while this is a pattern we support, it's not a pattern we want to encourage.

**Comment by jbondc** [comment] 2015-06-15 17:52
@JsonFreeman Have you looked at my patch?

A set type:
```
type something = "a" | "b" | "c";
```
Is the creation of a type from literal values, not other types.
```
function numberRangeName(num: number)
    var x: "positive"|"negative"|"zero"|undefined;  // x is allowed to be undefined here.
    if (num > 0) {
        x = "positive";
    }
    ///etc...
    return x;
}
```
I haven't encoded those values into 'bits' yet but plan to add them:
```
	const valUndefined: BitSet = [2, 1];
	const valNull: BitSet = [2, 2];
	const valTrue: BitSet = [2, 4];
	const valFalse: BitSet = [2, 8];
	const valInfinity: BitSet = [2, 16];
	const valNaN: BitSet = [2, 32];
```
I'm kind of concerned you want to implement this differently.

**Comment by yortus** [comment] 2015-06-16 00:22
> `var x: "positive"|"negative"|"zero";  // x is undefined here.`

That's just an uninitialised variable. The compiler can already flag an error for this - eg:

`const a;  // Error: 'const' declarations must be initialized`

Its also trivially easy to avoid:

```typescript
function numberRangeName(num: number)
    var x: "positive"|"negative"|"zero" = "zero";
    if (num > 0) {
        x = "positive";
    }
    ///etc...
    return x;
}
```

I guess there's a trade-off for the user of singletons: either they must pay the cost of initialising singleton variables to a valid value, or they must pay the cost of having to have extra type guards and checks everywhere the values are used.

I guess I was wondering if there is a *useful* example of allowing `null`/`undefined` in a singleton? ie where it helps express or solve a problem at hand.

**Comment by JsonFreeman** [comment] 2015-06-18 21:43
Talked with @mhegazy. We think that this issue really doesn't have much to do with string literal types. Instead it has more to do with type guards that involve property accesses. To this end, our inclination is that if you have a type guard based on a property access, we will only narrow the type in the true branch. The false branch could trick us into doing a faulty process of elimination.

**Comment by yortus** [comment] 2015-06-19 01:09
@JsonFreeman can you clarify what this means for whether or not the type system would consider `null`/`undefined` as valid values for singleton types?

**Comment by JsonFreeman** [comment] 2015-06-19 05:36
Sure, it means that singleton types are just like any other type, in that they implicitly allow null and undefined. This minimizes friction with the rest of the type system.

I do see the merit in making singleton types not allow null or undefined. However, doing that would mean that we need to provide a way to denote a nullable singleton type. We have thought about nullability in general from time to time, but so far have not come to any promising conclusions about how it would be accomplished. For better or worse, our type system today is nullable at its very core.

**Comment by yortus** [comment] 2015-06-19 05:52
Got it. Still curious to see an example illustrating why someone might want to constrain a type to a singleton value and also *want* it to be nullable. Bearing in mind this is all purely about compile time type checking since singleton types obviously have no runtime support.

**Comment by yortus** [comment] 2015-06-19 06:02
Clarifying my last comment... I would like to know the justification for this statement:

> we need to provide a way to denote a nullable singleton type

What need does a nullable singleton satisfy?

**Comment by yortus** [comment] 2015-06-19 06:07
Also isn't `undefined` itself (as in the value of the expression `void 0`) an instance of both:
a) a singleton type
b) a non-nullable type

So its not like they are unprecedented.

**Comment by alainfrisch** [comment] 2015-06-19 07:49
> Instead it has more to do with type guards that involve property accesses.
>...
> we will only narrow the type in the true branch. The false branch could trick us into doing a faulty process of elimination

I don't follow the reasoning.

First, for a variable whose type is an union of singletons and a guard testing one of the values (which does not involve any property access):  the fact that the value can be `null` or `undefined` should not change the fact than in the false branch, there is one less possibility.  Now if you test all possibilities (with a cascade of if-then-else or a switch), you're left with an empty union, which could still denote either `null` or `undefined` (if you decide so).  This can be tested with further branches, or asserted by calling a function taking precisely this empty type (a soft version of "exhaustivity modulo non-nullness" checking).

Now, if the guard in on a property access (with an initial type being typically a union of objects with a discriminator field), the same approach would still work:  when testing if the property has a specific value, the false branch should have the knowledge that the corresponding case(s) in the union are no longer possible.  I don't see why allowing null/undefined would affect that.

**Comment by jbondc** [comment] 2015-06-19 12:22
Should have a patch in a couple of days, it's looking pretty awesome :smile: 

@JsonFreeman The conclusion I came to is that constants deserve special treatment, they can 'bypass' the type check. So the compiler has a notion of two things:
- Type checking
- Constant checking
```
function foo(something: "a" | "b") {}
foo("a") // "a" here is a constant, we check if "a" is in the set "a" | "b"
// we don't really care about the type but for theory's sake, it has type string 
```
My thinking aligns more closely with:
http://blog.golang.org/constants

These ideas are my own, go is the closest thing I've seen to the approach I'm taking. 
Type narrowing leverages that we know about constants:
```
// property access
type obj = /*1*/ { kind : "name"; name : string } |  /*2*/ { kind : "id" ; id : number };
// compiler: infer from the union that kind is a set type of "name" | "id"
// compiler: add the constant identity mapping to the union of
 //  {"kind": {"Sname": ObjectOf1, "Sid": ObjectOf2 }}

var o : obj;
if (o.kind === "name") {
  // LHS is a set type
  // RHS is a *constant*
  // LHS parent type has an identity mapping  {"kind": {"name": ObjectOf1, "id": ObjectOf2 }}
  // boom ["kind"]["name"] --> narrows
  o.name;
} else if(o.kind === "id")  {
  // LHS is a set type
  // RHS is a *constant*
  // LHS parent type has an identity mapping  {"kind": {"name": ObjectOf1, "id": ObjectOf2 }}
  // boom ["kind"]["id"] --> narrows
   o.id;
}
```
It's all going to work out nicely. Like I said before null is *not* included by default. But it could be:
```
type obj = /*1*/ { kind : "name"; name : string } |  /*2*/ { kind : "id" ; id : number }
 |  /*3*/ { kind : null ; nullDude : number };
// compiler: infer from the union that kind is a set type of "name" | "id" | null
// compiler: add the constant identity mapping to the union of
 //  {"kind": {"Sname": ObjectOf1, "Sid": ObjectOf2, "n": ObjectOf3 }}
```
Note that each constant actually gets a special "identity key" for the identity mapping part.

**Comment by jbondc** [comment] 2015-06-19 13:24
I'll add this will work with const enums or any const binding that resolves to literal:
```
let something: {kind: "a", a: true} |  {kind: null, null: true}  | {kind: 0, integer: true}
// identity mapping becomes {"kind": {"Sa" : ObjectOf0, "n" : ObjectOf1, "I0": ObjectOf2} }
const Null = null;
const A = "a";
const enum Things {
   a, b, c
}
if (something.kind === Things.a) {
  // mapping of "I0" (integer) constant key in 'something'
} else  {
  // whatever is left in our identity mapping
  something; // {kind: null, null: true} | {kind: 0, null: true}
}
if (something.kind === Null) {
  // mapping of "n" constant key in 'something'
} else  {
  // whatever is left in our identity mapping
   something; // {kind: "a", a: true}   | {kind: 0, null: true}
}
if (something.kind === A) {
  // mapping of "Sa" constant key in 'something'
} else  {
  // whatever is left in our identity mapping
  something; // {kind: null, null: true}  | {kind: 0, null: true}
}
```
We just have to know the RHS resolves to a constant value then we're good to go.

**Comment by JsonFreeman** [comment] 2015-06-29 17:42
@yortus The reason it is valuable to denote a nullable singleton type is the example @nycdotnet gave: https://github.com/Microsoft/TypeScript/issues/1003#issuecomment-112094477. Like you said, in order to get around this, you have to have a sentinel value ("zero" in the example you gave), which seems kind of unnatural.

Your point about undefined being a non-nullable singleton type: That is true, but the type system treats undefined specially in two important ways, which make it not function as a precedent for non-nullable types:

1. It is a bottom type.
2. It gets widened when it is assigned to something.

**Comment by JsonFreeman** [comment] 2015-06-29 17:44
@jbondc Your suggestion to fold in constant propagation seems to mix too many features together, and it seems to have much wider scope than the feature calls for.

**Comment by jbondc** [comment] 2015-07-02 15:29
Well sometimes you need building blocks to create new things, I added two fundamental concepts 'set types' + constants. The 'set types' is very similar to ```4. Variant types``` here:
http://lucacardelli.name/papers/inheritance.pdf

Anyways not sure if I'm headed in the same direction as TS so may fork it into something else.

**Comment by JsonFreeman** [comment] 2015-07-02 16:26
The tagged union usage is the most similar thing to variant types that Typescript can have. The problem is that there are no first class "labels" in Javascript, so we use type guards instead. And then to make a label at compile time, there is a choice between using const entities (what you suggested), or types that represent constant values (what this proposal was about).

**Comment by teppeis** [comment] 2015-07-13 14:01
Flowtype implemented similar feature: http://flowtype.org/blog/2015/07/03/Disjoint-Unions.html

**Comment by yortus** [comment] 2015-07-13 14:16
@teppeis looks nice, and demonstrates the simplicity of coding with truly disjoint unions. According to the discussion above it appears TypeScript may not allow type narrowing in the `else` case due to `null` and `undefined` being implicitly allowed values of every singleton type.

**Comment by Nevor** [comment] 2015-07-13 14:26
@teppeis , @yortus Actually, it's the same feature, the examples are very familiar since it's actually this issue that was cross posted on flow's github (https://github.com/facebook/flow/issues/135) completing an other proposal (https://github.com/facebook/flow/issues/20). 

Concerning the type narrowing, the softer handling of `null` and `undefined` of TypeScript do not prevent us from doing it in the `else` case. Actually all examples given in this blog post should work in my proposal prototype.

**Comment by yortus** [comment] 2015-07-13 14:38
@Nevor regarding type narrowing that's great if it can be done in the presence of `null`/`undefined`. Are you talking along the lines of option 3 in [this comment](https://github.com/Microsoft/TypeScript/issues/1003#issuecomment-111760092)?

**Comment by Nevor** [comment] 2015-07-13 14:55
Yep, in the case of Typescript, we are already in a world where everything can be `null/undefined`, I don't see the need to treat this case differently. Moreover, it's very easy to transform an "unsafe" `if-then-else` into a safe `switch` or `if-then-else-if-then`.

**Comment by JsonFreeman** [comment] 2015-07-13 17:46
Yes, there are certainly no technical limitations to narrowing a nullable in the else clause, I was just wondering whether people wanted this looseness. Sounds like the answer is yes.

Btw, @RyanCavanaugh made a good point that by this philosophy, we should also narrow in the else clause of an instanceOf guard.

**Comment by jbondc** [comment] 2015-07-14 12:09
Just working out the test cases and agreeing on those seems like a better first step.

Set types + constant checking works fine, in fact it simplifies & speeds up checking. Any solution here I imagine would also work with number & boolean:
https://github.com/facebook/flow/issues/524

Removed my comments since I won't be submitting a PR.

**Comment by impinball** [comment] 2015-09-21 14:47
Would this work with [my proposal](https://github.com/impinball/typescript-enum-proposal), particularly with the `const enum` feature? To take the first few lines of the initial overview as an example:

```ts
const enum Result : string {
  ok,
  fail,
  abort,
}

function compute(n : number) : Result {
  if(...) {
    return Result.ok;
  } else if (...) {
    return Result.fail;
 } else {
    // This couldn't be any more clear what the problem is.
    return Result.crash;
 }
}
```

**Comment by impinball** [comment] 2015-09-30 06:32
Although now that I come to think about it, this could complement enum types, as enums are effectively a type union of constants. Enums should be typed like classes, and type unions would be the duck-typing equivalent.

Also, shouldn't this be expanded for other primitive constants as well? I know of a few use cases for numeric constants, and a few cases where false is treated specially, while true is ignored or not used.

**Comment by knuton** [comment] 2015-10-29 15:03
I see that @DanielRosenwasser is now working on this. Any way we can help with community contributions?

**Comment by mhegazy** [comment] 2015-12-01 07:19
The original issue is addressed by #5185. the remaining part is extending the type guards to support the string literal types. but this should be tracked by a different issue.

**Closed by mhegazy** 2015-12-01 07:19 UTC
Labels: Suggestion

**Comment by Elephant-Vessel** [comment] 2016-04-05 13:13
Hey, shouldn't this result in a warning about either unreachable code or type incompatibility?

```typescript
type Animal = "dog" | "cat";

function DoStuff(animal:Animal) {
	if(animal === "fish")
		return;
}
```

**Comment by Elephant-Vessel** [comment] 2016-04-05 13:14
Hey, shouldn't this result in a warning about either unreachable code or type incompatibility?

```typescript
type Animal = "dog" | "cat";

function DoStuff(animal:Animal) {
	if(animal === "fish")
		return;
}
```

**Comment by DanielRosenwasser** [comment] 2016-04-05 17:35
@Elephant-Vessel we're working on it. See #6196, though I don't know if we'll see it in 2.0.
