### ISSUE TITLE
IteratorResult should be a discriminated union

### ISSUE THREAD

**Issue by KSXGitHub** [Microsoft/TypeScript#28670] opened 2018-11-26 04:17 UTC
## Suggestion

Current definition of `IteratorResult` demands `value` to be provided regardless of whether `done` is `true` or `false`.

**Suggestion:** Change `IteratorResult` to something like this

```typescript
type IteratorResult<T> =
  { readonly done: true } |
  { readonly done: false, readonly value: T }
```

## Use Cases

I am currently trying to build a custom async iterator that cannot be done with async generator, it is absurd that I had to provide some value when iteration is done.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AnyhowStep** [comment] 2018-11-26 05:39
I think I just force cast to as any or sth

**Comment by KSXGitHub** [comment] 2018-11-26 05:43
@AnyhowStep Yeah, that was my workaround too. But I think it shouldn't be, hence the request.

**Comment by cpplearner** [comment] 2018-11-26 06:42
duplicate of #11375?

**Comment by hwanders** [comment] 2018-11-26 19:16
According to the [spec](https://tc39.github.io/ecma262/#sec-iteratorresult-interface) and [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#The_iterator_protocol) the `value` property may (but is not required to) be present when `done` is `true`.
I think the proper typing should be
```ts
type IteratorResult<T> =
  { readonly done: true, readonly value?: T } |
  { readonly done: false, readonly value: T }
```
or even:
```ts
type IteratorResult<T> =
  { readonly done: true, readonly value?: any } |
  { readonly done: false, readonly value: T }
```

**Comment by weswigham** [comment] 2018-11-26 20:15
@rbuckton think we've got enough infrastructure in place to be able to try this lib change yet?

**Comment by rbuckton** [comment] 2018-11-27 03:47
For reference, @KSXGitHub is talking about this: https://tc39.github.io/ecma262/#sec-iteratorresult-interface (emphasis added):

> If the end of the iterator was reached `done` is **true**. If the end was not reached `done` is **false** and a value is available. _If a `done` property (either own or inherited) does not exist, it is consider to have the value **false**._

**Comment by rbuckton** [comment] 2018-11-27 03:50
There is, however, nothing that indicates `done` or `value` are read-only.

**Comment by KSXGitHub** [comment] 2018-11-27 03:55
@rbuckton Although the spec does not _demands_ the properties to be either writable or read-only, making them not read-only makes it impossible to use a read-only (e.g. frozen) object as an `IteratorResult`.

**Closed** 2018-12-12 10:00 UTC
Labels: Duplicate
