### ISSUE TITLE
Incorrect code transpiling for generator function when downlevel iteration is set

### ISSUE THREAD

**Issue by pomadin** [Microsoft/TypeScript#24824] opened 2018-06-09 09:07 UTC
**TypeScript Version:**  2.9.1

**Search Terms:**
- generator
- iterator (**for..of**)
- downlevelIteration

**Code / Issue**
```ts
// ES5 target and downlevelIteration should be set
function* saga(patterns, { pathname: path }) {
    for (const pattern of patterns) {
        yield [pattern, path];
    }
}
```
If I use `tsc -t es5 --downlevelIteration --noEmitHelpers` to transpile the sample I will get incorrect location for `path` variable declaration. It should be declared at the beginning of `saga` function to be closured as it's done by v2.8.4. But in case of v2.9.1 it's declared under `case 0` that is incorrect as the variable would be `undefined` for other entry states.

**Expected behavior:**
The proper location of `path` variable declaration to get it defined for all states.
```js
function saga(patterns, _a) {
    var path, patterns_1, patterns_1_1, pattern, e_1_1, e_1, _b;  // correct place
    return __generator(this, function (_c) {
        switch (_c.label) {
            case 0:
                path = _a.pathname;
                _c.trys.push([0, 5, 6, 7]);
                patterns_1 = __values(patterns), patterns_1_1 = patterns_1.next();
                _c.label = 1;
            case 1:
                if (!!patterns_1_1.done) return [3 /*break*/, 4];
                pattern = patterns_1_1.value;
                return [4 /*yield*/, [pattern, path]];
            case 2:
                _c.sent();
                _c.label = 3;
            case 3:
                patterns_1_1 = patterns_1.next();
                return [3 /*break*/, 1];
            case 4: return [3 /*break*/, 7];
            case 5:
                e_1_1 = _c.sent();
                e_1 = { error: e_1_1 };
                return [3 /*break*/, 7];
            case 6:
                try {
                    if (patterns_1_1 && !patterns_1_1.done && (_b = patterns_1.return)) _b.call(patterns_1);
                }
                finally { if (e_1) throw e_1.error; }
                return [7 /*endfinally*/];
            case 7: return [2 /*return*/];
        }
    });
}
```

**Actual behavior:**
The `path` variable is declared and initialized only for the `0` state.
```js
function saga(patterns, _a) {
    var e_1, _b, patterns_1, patterns_1_1, pattern, e_1_1;
    return __generator(this, function (_c) {
        switch (_c.label) {
            case 0:
                var path = _a.pathname; // incorrect place
                _c.label = 1;
            case 1:
                _c.trys.push([1, 6, 7, 8]);
                patterns_1 = __values(patterns), patterns_1_1 = patterns_1.next();
                _c.label = 2;
            case 2:
                if (!!patterns_1_1.done) return [3 /*break*/, 5];
                pattern = patterns_1_1.value;
                return [4 /*yield*/, [pattern, path]];
            case 3:
                _c.sent();
                _c.label = 4;
            case 4:
                patterns_1_1 = patterns_1.next();
                return [3 /*break*/, 2];
            case 5: return [3 /*break*/, 8];
            case 6:
                e_1_1 = _c.sent();
                e_1 = { error: e_1_1 };
                return [3 /*break*/, 8];
            case 7:
                try {
                    if (patterns_1_1 && !patterns_1_1.done && (_b = patterns_1.return)) _b.call(patterns_1);
                }
                finally { if (e_1) throw e_1.error; }
                return [7 /*endfinally*/];
            case 8: return [2 /*return*/];
        }
    });
}
```

**Comment by mhegazy** [comment] 2018-06-11 17:49
Can you try `typescript@next`?

**Comment by mhegazy** [comment] 2018-06-11 17:52
Duplicate of https://github.com/Microsoft/TypeScript/issues/24564. should be fixed in `typescript@next` today, and in `typescript@2.9.2` in a few days.

**Comment by pomadin** [comment] 2018-06-12 03:15
I have checked `typescript@3.0.0-dev.20180609` and the issue has been fixed there. I will wait for 2.9.2 to get the fix. Thanks.

**Closed** 2018-06-28 23:04 UTC
Labels: Duplicate
