### ISSUE TITLE
Bug in destructuring assignment, losing type analysis information 

### ISSUE THREAD

**Issue by tomcumming** [Microsoft/TypeScript#12263] opened 2016-11-15 10:53 UTC
**TypeScript version: 2.0.8**
```typescript
export type State = {
    value: string,
    mode: Selecting | Selected,
}

type Selected = {
    type: 'selected',
    valid: boolean
}

type Selecting = {
    type: 'selecting',
    options: { type: 'loading', handle: number }
        | { type: 'loaded', selection: undefined | number, items: string[] }
}

function f(state: State) {
    if (state.mode.type === 'selecting' && state.mode.options.type === 'loaded') {
        const {options} = state.mode;
        const options2 = state.mode.options;
        options2.items;        
        options.items;
    }
}
```

**Expected**
inside `f`, `options` and `options2` should have the same type

**Actual**
`options` loses the narrowed type information

**Comment by ahejlsberg** [comment] 2016-11-15 21:50
Duplicate of #10065 and #10846.

**Closed** 2017-04-21 16:56 UTC
Labels: Duplicate
