### ISSUE TITLE
Optional chaining is emitting not recognizable JavaScript code in lower level than ES Next

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#33737] opened 2019-10-02 02:48 UTC
In the [TypeScript design goal](https://github.com/microsoft/TypeScript/wiki/TypeScript-Design-Goals#goals) it writes `Emit clean, idiomatic, recognizable JavaScript code`, but the optional chaining breaks this.

**TypeScript Version:**  3.7.0-beta

**Search Terms:** Optional chaining

**Code**

```ts
const a = globalThis?.browser?.runtime?.getBackgroundPage?.()?.location?.href ?? location.href
```

**Expected behavior:**

Generate a recognizable JavaScript code.

**Actual behavior:**

```js
var _a, _b, _c, _d, _e, _f, _g, _h;
const a = (_h = (_g = (_f = (_e = (_c = (_b = (_a = globalThis) === null || _a === void 0 ? void 0 : _a.browser) === null || _b === void 0 ? void 0 : _b.runtime) === null || _c === void 0 ? void 0 : (_d = _c).getBackgroundPage) === null || _e === void 0 ? void 0 : _e.call(_d)) === null || _f === void 0 ? void 0 : _f.location) === null || _g === void 0 ? void 0 : _g.href, (_h !== null && _h !== void 0 ? _h : location.href));
```

**Comment by septs** [comment] 2019-10-02 02:50
Add like lodash.get function to helper?

**Comment by AnyhowStep** [comment] 2019-10-02 03:04
What is your target version?

**Comment by Jack-Works** [comment] 2019-10-02 04:36
target ES2017

**Comment by ilogico** [comment] 2019-10-02 09:15
The idiomatic and recognizable form is not spec compliant:
```js
something && something.prop && something.prop.method && something.prop.method();
```

**Comment by j-oliveras** [comment] 2019-10-02 10:00
@ilogico as a example:
```ts
some[i++]?.large?.property?.paths
```

is not the same as:
```ts
some[i++] && some[i++].large && some[i++].large.property && some[i++].large.property.paths
```

The current output is always valid.

**Comment by Jack-Works** [comment] 2019-10-02 12:34
> The idiomatic and recognizable form is not spec compliant:
> 
> ```js
> something && something.prop && something.prop.method && something.prop.method();
> ```

That's not correct. If `something.prop` is a getter, you're invoking it multiple times. A more readable names is okay.

```ts
const something_ = !(sth === void 0 || sth === null) ? sth : void 0
const something_prop = !(something_ === void 0 || something_ === null) ? something_.prop : void 0
const something_prop_method = !(something_prop === void 0 || something_prop === null) ? something_prop.method : void 0
something_prop_method !== void 0 && something_prop_method !== null && Reflect.apply(something_prop_method, something_prop, [])
```

I think `_e.call(_d)` in the above result is not correct if the code is `binded`

**Comment by ilogico** [comment] 2019-10-03 08:23
I think you misread, I'm not suggesting the transpilation is done like that. I'm stating the idiomatic way is **not** spec compliant.
- computed properties are recomputed
- getters are called multiple times
- the value is not compared with null or undefined, but tested for truthiness instead

**Comment by AnyhowStep** [comment] 2019-10-03 08:43
Change your target to esnext

**Comment by Jack-Works** [comment] 2019-10-03 09:11
> Change your target to esnext.
> 
> Also, provide a playground next time. It helps poor mobile users like me test stuff more easily =(
> 
> If only the playground supported mobile users and use a regular textarea...

Does the playground supports typescript@beta?

And it has no meaning to change the target to ESNext. I'm talking about how to translate it to old ES versions.

**Comment by AnyhowStep** [comment] 2019-10-03 09:45
I'm on mobile, so typing getting a link was a pain in the butt.
[Playground TS 3.7, esnext](http://www.typescriptlang.org/play/?target=99&ts=3.7-Beta#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UA6AQzwHMz4BXAOwBMA6UHTBQDOoIRVQphoeqGjwaAWABQIWRQDWKMpw4UOTaf0IlyVGgVYArSLBp6xXFDIDukAEag3rZ0MhkeysqqAih0jCzs3KCI9Joi4qCQ9EJ4oABm8GSgeOxoGEL0aTCpkAAeRJTIHKhBYM7imKAUjslNHEZEpJTUnqkx6noGCaiUAG4U9NB5opj0ZJC1WJC+tFY2qEJ8IaAAqgBKADLpmVhSBPRMkiKQo354qIL6oIvzAI5sFPNc03L03w+hNa2Y5ZIRISDwDgoGC+AJKZQIDhCGjYaByUAAXlAACIABIwOTYwIqMAATVysHo7V8KEhS1AlCYmBoAIZyzY0Bo8DS9PwnVMPUWCEQBAo0D8AC5TvERKMqWKGKAAFL0OVdMygZyCWCNSntbTtOmLLzwHx+IQAGlEfluZBEJypeC1fi0STReDhCMhyM1mWg3yx2PAfq4RPhJNA5LYoD11pQmFNTRo-WWaD0qR1VMuInQ9IQjitblSQshttQg0M2MRyOx0xk2LlZGxW0EMtAkNpPNZMQ4eEWD0GIj5Jm6NC48FTuZTSdo8CEYjc4umBueEcdzvmytV9HVPQNm2J1fg4p4ciYAApUeiANQ4u+35whgCUyiYcjckwEwgA-DwTWayEWAA5RMcmjWZbmkdpmiSdseQTZx6TCZhWE4b5HzIdRLVkSBUAAchERY5HgdRpBRRNh13ZNYlTDCBieeoHi3NUBWTTIFgjNJOD4AARNhKCeAcRF8WwKDpVw8LRTwUBGPAK1zTRIAIaRCIjWA5BWXM5V0NEZBVFjRxU2d5woRcZPyBDQEssDV1UWN5gAWjYFYymEcsnnUDhTXFLhLjhf9fEAiMAGFoAoWBSLcGBE1zRF3LYSAJVqRYynoEVxQleA3GsWwhAcqkuHysgyEYIQgA)

[Playground TS 3.7, es2017](http://www.typescriptlang.org/play/?ts=3.7-Beta#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UA6AQzwHMz4BXAOwBMA6UHTBQDOoIRVQphoeqGjwaAWABQIWRQDWKMpw4UOTaf0IlyVGgVYArSLBp6xXFDIDukAEag3rZ0MhkeysqqAih0jCzs3KCI9Joi4qCQ9EJ4oABm8GSgeOxoGEL0aTCpkAAeRJTIHKhBYM7imKAUjslNHEZEpJTUnqkx6noGCaiUAG4U9NB5opj0ZJC1WJC+tFY2qEJ8IaAAqgBKADLpmVhSBPRMkiKQo354qIL6oIvzAI5sFPNc03L03w+hNa2Y5ZIRISDwDgoGC+AJKZQIDhCGjYaByUAAXlAACIABIwOTYwIqMAATVysHo7V8KEhS1AlCYmBoAIZyzY0Bo8DS9PwnVMPUWCEQBAo0D8AC5TvERKMqWKGKAAFL0OVdMygZyCWCNSntbTtOmLLzwHx+IQAGlEfluZBEJypeC1fi0STReDhCMhyM1mWg3yx2PAfq4RPhJNA5LYoD11pQmFNTRo-WWaD0qR1VMuInQ9IQjitblSQshttQg0M2MRyOx0xk2LlZGxW0EMtAkNpPNZMQ4eEWD0GIj5Jm6NC48FTuZTSdo8CEYjc4umBueEcdzvmytV9HVPQNm2J1fg4p4ciYAApUeiANQ4u+35whgCUyiYcjckwEwgA-DwTWayEWAA5RMcmjWZbmkdpmiSdseQTZx6TCZhWE4b5HzIdRLVkSBUAAchERY5HgdRpBRRNh13ZNYlTDCBieeoHi3NUBWTTIFgjNJOD4AARNhKCeAcRF8WwKDpVw8LRTwUBGPAK1zTRIAIaRCIjWA5BWXM5V0NEZBVFjRxU2d5woRcZPyBDQEssDV1UWN5gAWjYFYymEcsnnUDhTXFLhLjhf9fEAiMAGFoAoWBSLcGBE1zRF3LYSAJVqRYynoEVxQleA3GsWwhAcqkuHysgyEYIQgA)

When you highlighted this,
> Emit clean, idiomatic, recognizable JavaScript code

I thought you were complaining it wasn't emitting exactly what you typed, since it's technically clean, idiomatic and recognizable (Stage 3) JavaScript.

So, if that's what you were complaining about, changing your target to esnext would be the solution.

But your actual complaint is that it doesn't look like it's emitting clean, idiomatic and recognizable es2017 JavaScript, when trying to down level its emit

**Comment by septs** [comment] 2019-10-05 01:49
@rbuckton

**Comment by Jessidhia** [comment] 2019-10-05 03:09
That sure is a lot of `?.` in the example line; you only need `?.` on the properties you expect might be null/undefined, not on everything. It short-circuits.

There's no way to emit this in a way that "would be readable" while still preserving order of operations. Like, it is _possible_, but especially when embedded in any expression more complicated than an assignment expression, it would require also transforming a bunch of unrelated code and spilling even more things to local variables to preserve behavior.

Say, what if you have an optional chain in the argument to a method call.

```ts
foo.bar(foo.baz?.x)
```

Maybe typescript could spill the `foo.baz?.x` into a separate declaration, say, `_foo_baz_x = /* ... */`, but that would mean potentially invoking `baz` and `x`'s getter (or `get` `Proxy` trap) before `foo.bar`. To avoid that, `foo.bar` would also have to be spilled into a `_foo_bar` local, and `_foo_bar`'s call expression would have to be converted into a `.call` call expression.

```ts
var _foo_bar = foo.bar
var _foo_baz = foo.baz
var _foo_baz_x = _foo_baz !== null && _foo_baz !== undefined ? _foo_baz.x : undefined
_foo_bar.call(foo, _foo_baz_x)
```

This is probably the easy case; what do you do if it's already in the consequent/alternate of a ternary expression, say, `checkX ? foo.baz?.x : ''`; every single sub-expression could/should only be evaluated if `checkX` is truthy to begin with.

At best, TypeScript could try to derive the spilled locals from the identifiers in the subexpressions, kinda like I did in my code example, instead of just using `_a`, `_b`, etc. They'll all get crushed when the code is minified anyway, there's no need to emit short local identifiers.

**Comment by Jack-Works** [comment] 2019-10-05 03:16
The helper described in the https://github.com/microsoft/TypeScript/issues/33737#issuecomment-537312950 can resolve the order problem I think

**Comment by rbuckton** [comment] 2019-10-05 05:05
While I can understand that the output JavaScript is harder to read, this is no worse than our emit for destructuring or computed properties. This emit emulates the correct runtime behavior and is the most efficient representation. A helper like `_get` that you have above would not preserve the correct execution order for element access in `a?.b[c()]`, nor would it work for a chain involving an optional call without falling back to the current emit `a?.b().c.d`.

**Comment by rbuckton** [comment] 2019-10-05 05:11
I'm closing this as "Working as Intended". While it is always a goal to emit clean, idiomatic JavaScript when possible, this is not always feasible or recommended. This is a case where we have chosen to as closely match the semantics of the proposal as possible.

**Closed by rbuckton** 2019-10-05 05:11 UTC
Labels: Working as Intended

**Comment by KhraksMamtsov** [comment] 2019-10-08 08:37
Hi! 
I wrote a helper that makes the code more readable and using it produces less code.
You may see it here http://jsfiddle.net/sjmkz81b/4/
It works like maybe monad, but it is light version for ?. and ??. 
No need to generate temporary variables like _a, _b, _c
It works on demand - if ```null``` or ```undefined``` occurs in the chain, then further all calculations are stopped and the ```undefined``` is passed along the chain, so index access with index incrementation works fine.
Please check feedle for tests.
Of the minuses - the stack trace is bigger and the trace is probably slower. 
Although I did not take measurements.
What do you think about that?

```js
a?.[i++]?.c?.d?.(1, 2, 3) ?? 123
// becomes
// es6
__helper(a)(x => x[i++])(x => x.c)(x => x.d, [1, 2, 3])(() => 123)
// es5
__helper(a)(function(x) { return x[i++]; })(function(x) { return x.c; })(function(x) { return x.d; }, [1, 2, 3])(function() { return 123; })
// current version on playground
var _a, _b, _c, _d; _d = (_c = (_b = (_a = a) === null || _a === void 0 ? void 0 : _a[i++]) === null || _b === void 0 ? void 0 : _b.c) === null || _c === void 0 ? void 0 : _c.d, (_d !== null && _d !== void 0 ? _d : 123);
```
```js
a ?? 123
// becomes
// es6
__helper(a)(() => 123)
// es5
__helper(a)(function() { return 123 })
// current version on playground
(a !== null && a !== void 0 ? a : 123)
```
```js
a?.b
// es6
__helper(a)(x => x.b)()
// es5
__helper(a)(function(x) { return x.b })()
// current version on playground
var _a; (_a = a) === null || _a === void 0 ? void 0 : _a.b;
```
```js
// helper itself
function __helper(x) {
  return function(fn, args, _x = x) {
    if (_x !== void 0 && _x !== null) {
      if (fn === void 0) { // __h({ y: 1 })() => { y: 1 }
        return _x;
      }
      if (fn.length) { // get property __h({ y: 1 })(x => x.y) => __helper([[maybeValue]])
        if (args === void 0) {
          return __helper(fn(_x));
        } else {
          // get property and call __h({ y: 1 })(x => x.y, [1, 2, 3]) => __helper([[maybeValue]])
          return __helper(fn(_x).apply(_x, args));
        }
      } else { // get or default __h(1)(() => 2) => 1
        return _x;
      }
    }
    if (fn === void 0) { // __h(undefined | null)() => undefined
      return void 0;
    }
    if (fn.length) { // get property [[undefined]]?.y  __h(undefined | null)(x => x.y) => __helper(undefined | null)
      return __helper(_x);
    } else { // get or default __h(undefined | null)(() => 2) => 2
      return fn();
    }
}
```
```js
// minified version
function h(i) {return function(e, n, l) {return void 0 === l && (l = i), null != l ? void 0 === e ? l : e.length ? h(void 0 === n ? e(l) : e(l).apply(l, n)) : l : void 0 === e ? void 0 : e.length ? h(l) : e()}}
```
