### ISSUE TITLE
Prefer Top Level Export For Missing Import Quick Fix

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#16959] opened 2017-07-05 23:45 UTC
From https://github.com/Microsoft/vscode/issues/30001

**TypeScript Version:**  2.4.1

**Steps**
In a new workspace:

1. `npm install @angular/core`. Angular core ships with its own `d.ts` files

2. In a JS file:

```js
@Component({}) 
class Foo{}
```

3. Trigger `Fix Missing import` quick fix on `Component`

**Expected behavior:**
A quick fix that adds an `@angular/core` import is shown.

**Actual behavior:**
Quick fixes for importing from folders under `@angular/core` are shown

![screen shot 2017-07-05 at 4 38 40 pm](https://user-images.githubusercontent.com/12821956/27889324-720d546e-61a0-11e7-9504-94d93f322ce9.png)

In this case, it appears that the implicit javascript project is loading all `d.ts` files from `@angular/core`:

```
Open files: 
/Users/matb/projects/san/test.js
Info 97   Project '/dev/null/inferredProject1*' (Inferred) 0
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es6.d.ts
/Users/matb/projects/san/test.js
/Users/matb/Library/Caches/typescript/2.4/node_modules/@types/reflect-metadata/index.d.ts
/Users/matb/projects/san/node_modules/@angular/core/src/di/injection_token.d.ts
/Users/matb/projects/san/node_modules/@angular/core/src/type.d.ts
/Users/matb/projects/san/node_modules/@angular/core/src/metadata/di.d.ts
/Users/matb/projects/san/node_modules/@angular/core/src/change_detection/constants.d.ts
/Users/matb/projects/san/node_modules/@angular/core/src/di/metadata.d.ts
/Users/matb/projects/san/node_modules/@angular/core/src/di/forward_ref.d.ts
...
```

Shouldn't this be limited to loading the `d.ts` from just the `package.json` `typings` and any files it references?

**Comment by mhegazy** [comment] 2017-08-17 19:43
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/15223

**Closed by mhegazy** 2017-08-17 19:43 UTC
Labels: VS Code Tracked
