### ISSUE TITLE
Generic type constraint ignored when applied to interface expecting a different signature.

### ISSUE THREAD

**Issue by rjamesnw** [Microsoft/TypeScript#15458] opened 2017-04-29 01:55 UTC
Not sure if I found a bug or not, so just checking first.  The code below should not work, but it compiles fine:

```
interface IType<TInstance> {
    new (value: boolean, ...args: any[]): TInstance;
}

class Test<T extends string> {
    constructor(value: T) { }
}

function doSomething(_type: IType<any>) { }

doSomething(Test);

```
([here](https://www.typescriptlang.org/play/index.html#src=interface%20IType%3CTInstance%3E%20%7B%0D%0A%20%20%20%20new%20(value%3A%20boolean%2C%20...args%3A%20any%5B%5D)%3A%20TInstance%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Test%3CT%20extends%20string%3E%20%7B%0D%0A%20%20%20%20constructor(value%3A%20T)%20%7B%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20doSomething(_type%3A%20IType%3Cany%3E)%20%7B%20%7D%0D%0A%0D%0AdoSomething(Test)%3B%0D%0A))

If I change ` constructor(value: T) { }` to ` constructor(value: string) { }` it fails.  It should fail anyhow, since T could NEVER be of the expected type. :/

This also just seems wrong: 

```
interface IType<TInstance> {
    new (value: boolean, ...args: any[]): TInstance;
}

class Test<T extends Object> {
    constructor(value: T) { }
}

function doSomething(_type: IType<any>) { }

doSomething(Test);

class O extends Object { }

class TO extends Test<O> { }

doSomething(TO);
```
Compiles just fine. :/

**Comment by mhegazy** [comment] 2017-05-17 22:40
Duplicate of https://github.com/Microsoft/TypeScript/issues/8397

**Closed** 2017-05-17 22:40 UTC
Labels: Duplicate

**Comment by mhegazy** [comment] 2017-05-18 17:26
Tracked by https://github.com/Microsoft/TypeScript/issues/5616
