### ISSUE TITLE
Union type can allow required properties of a member type to be missing

### ISSUE THREAD

**Issue by AndrewFerr** [microsoft/TypeScript#55548] opened 2023-08-28 17:15 UTC
### 🔎 Search Terms

union member in partial

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about unions, interfaces, and type guards

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20230828#code/JYOwLgpgTgZghgYwgAgCoAU5TARmQbwChkTk4AuZEAVwFsAjaAbmNPspoecIF9DDQkWIhQYsYAEwFWJBBzqMoLUsgAm8rkt78EAexABnMMgAO4nAH04IVRbPZgcADZ3xUgLzSVFZDgA0MsjsyBIBKnLIAMwBfIQw1CAIYMD6yDAWYtg4APJQEgAUAB6UmbgAPqUSAJRepMAwyPkA5AhNyKDIhTVEKiqFAHSqyABUnhLKpHzh+ga6ThD9TroA5kVVLHzppTl5+fa4VjauDs7Hkuv8gtDwSGgAQrpgABbIEIWQNgZomFl+324EPhgACeJlEP1wuQez2Qnm2yDK90eTxY8USyVSWwhO2hTyKJWxUOR3UC9UaLTaHS6tV6nUGIzGExIU1IekMcwWS1WXQ2cQyhKguL25kOtn2jhc+2qLEIILB-yyuQAkuBoAYIEkUiBYQrcAjGvCAGS66VxBKazH88zK1VQdUWkD43U7FVCe0YkAklRk5qtdra6k9Wl0oajEJM5As2QzDmLFZrXlY61QV1qjUe4VZUVnCVnU2y0Hg8wAQRsAFk4MDGBCPM7kMb8pV9fgeBc0Q60lasqXVBWqxAa07tj2+9W3F66g1fZSAxPaQNQ4zAlHkGzZvM49yLpsu7gR5Wx9gCvtLNYxeJc1L1kA

### 💻 Code

```ts
interface TPart1 {
    a: number;
    b: number;
}

interface TPart2 {
    c: number;
    d: number;
}

const part1_and_partial_part2 = {
    a: 1,
    b: 2,
    c: 3,
}

function f_TPart1Or2(x: TPart1|TPart2) {
    if ('c' in x) {
        x.d *= 2;
    }
    console.log(x);
}
f_TPart1Or2(part1_and_partial_part2);

interface TBoth extends TPart1, TPart2 {}
type TPart1OrBoth = TPart1 | TBoth;
function f_TPart1OrBoth(x: TPart1OrBoth) {
    if ('c' in x) {
        x.d *= 2;
    }
    console.log(x);
}
f_TPart1OrBoth(part1_and_partial_part2);

type TPart1OrIntersection = TPart1 | (TPart1 & TPart2);
function f_TPart1OrIntersection(x: TPart1OrIntersection) {
    if ('c' in x) {
        x.d *= 2;
    }
    console.log(x);
}
f_TPart1OrIntersection(part1_and_partial_part2);

type TPart1AndMaybePart2 = TPart1 & (TPart2 | {});
function f_TPart1AndMaybePart2(x: TPart1AndMaybePart2) {
    if ('c' in x) {
        x.d *= 2;
    }
    console.log(x);
}
f_TPart1AndMaybePart2(part1_and_partial_part2);
```

### 🙁 Actual behavior

No error is caught by static analysis, and each function is allowed to access & modify `x.d` despite it not existing in the value of `x` that they are given.

### 🙂 Expected behavior

A "not assignable to type" error should be raised when trying to pass either function an object that partially implements `TPart2`, even if that object fully implements `TPart1`.

Alternatively, the presence of any property of `TPart2` on the object shouldn't assume the presence of all other properties of `TPart2` on that object.

### Additional information about the issue

When an object fully satisfies a particular interface/type and partially satisfies another, that object is considered to satisfy the union of the fully-satisfied type & the partially-satisfied one.

However, this breaks the assumption that if the object has any property of the partially-satisfied interface/type, it must have all of them.

A way around this is to distinguish types by adding tag properties to them à la discriminated unions, but this requires runtime-visible changes to objects that could perhaps be avoided by stricter static analysis.

**Comment by MartinJohns** [comment] 2023-08-28 17:46
The `in` operator is intentionally unsound.

**Comment by jcalz** [comment] 2023-08-28 18:42
See #34975

**Comment by andrewbranch** [comment] 2023-08-28 18:44
Duplicate of https://github.com/microsoft/TypeScript/issues/34975

**Comment by fatcerberus** [comment] 2023-08-29 10:28
> A "not assignable to type" error should be raised when trying to pass either function an object that partially implements `TPart2`, even if that object fully implements `TPart1`.

With respect to this bit specifically: #12936

**Closed** 2023-09-01 01:28 UTC
Labels: Duplicate
