### ISSUE TITLE
Types destructuring

### ISSUE THREAD

**Issue by wongchichong** [microsoft/TypeScript#54748] opened 2023-06-23 05:34 UTC
# Suggestion

Types destructuring

## 🔍 Types destructure

As we know, we can destructure object or module using the following syntax.

```ts
import React, { useEffect, useState } from 'react'
import type { FC, CSSProperties } from 'react'

or
import * as React from 'react'
const { useEffect, useState } = React
```

I would like to suggest that the following types destructuring should be valid too
```ts
type { FC, CSSProperties } = React 
```

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2023-06-23 06:33
Duplicate of #35396.

**Closed** 2023-06-23 16:29 UTC
Labels: Duplicate
