### ISSUE TITLE
Provide a empty object type for`{}` 

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/TypeScript#52128] opened 2023-01-06 11:32 UTC
# Bug Report

### 🔎 Search Terms

Object type

### 🕗 Version & Regression Information

4.9.4
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PQKhCgAIOyAEAOBDATkgtpZb0GdID2AdgDYCekSJJBA7oQEYBWApgMYAuktAlhwBaQOZBC0pEAJpABuVAK5iAZjxYkJAGkgt0CYY1adNSSZAAGiqrhamoIYOAnsSqJXKKcexSIoIEAFNgYuABcUJDhAD6QAN5CIizBkACMANwy8gmQRHLoDCwokAC+YZExcaKJAExpsiQKibgcKDxEAOZFJZBR0cXhpRYkVuAAlInSBDwSKeDgoDAgkACSitxiclZmTQqmmnyQuPwEcmqQeeVi+SgEBfz5LAB0tvY+-lsswylAA)

### 💻 Code

```ts
/**
 *
 * @param params only allow object with type and value field, empty object, and `false`
 */
declare function foo(params:
    | { type: 1; value: number }
    | { type: 2; value: string }
    | {}
    | false
): void;

/**
 * If we use `true`, it should be type error here.
 */
foo(true);
```

### 🙁 Actual behavior

`true` is subtype of `{}`, no error
### 🙂 Expected behavior

There should exist a type stand for empty object.

**Comment by MartinJohns** [comment] 2023-01-06 11:58
I guess a duplicate of #42426 and you likely want #12936.

TypeScript is structurally typed, `true` can be assigned to `{}` because it's a subtype of it. This is working as intended. You can't represent a type that says "has no properties" in TypeScript.

**Closed** 2023-01-08 18:00 UTC
Labels: Duplicate
