### ISSUE TITLE
this.constructor is defined as "Function" resulting in property (static method name) does not exist on type 'Function'

### ISSUE THREAD

**Issue by nhusby** [microsoft/TypeScript#39559] opened 2020-07-11 01:43 UTC
this.constructor is defined as "Function" resulting in property (static method name) does not exist on type 'Function'.  My understanding is that "this.constructor" is the proper way to call a static method from an instantiated method.  

**TypeScript Version:**  3.9.5

**Search Terms:**
"this.constructor" "property does not exist on type 'Function'"

**Code**

```ts
export ClassNameInterface {
  abstractMethod: ( classSpecificVariable: string ) => void;
}

export abstract class ClassName implements Partial< ClassNameInterface > {
  protected static method( classSpecificVariable ){
    this.abstractMethod();
  }
}

export class InheritedClassName implements ClassNameInterface {
  private classSpecificData = 'InheritedClassNameSpecificData'
  protected static abstractMethod( classSpecificVariable: string ){}
  public method(){
    return this.constructor.method( this.classSpecificData );
  }
}
```

**Expected behavior:**
this.constructor.method( this.classSpecificData ); is valid code

**Actual behavior:**
this.constructor.method( this.classSpecificData ); is highlighted as error.

**Comment by ExE-Boss** [comment] 2020-07-11 08:32
Duplicate of <https://github.com/microsoft/TypeScript/issues/3841>

**Closed** 2020-07-16 18:00 UTC
Labels: Duplicate
