### ISSUE TITLE
"Expected 1 arguments, but got 0", when expected argument is "undefined"

### ISSUE THREAD

**Issue by drewwyatt** [Microsoft/TypeScript#20776] opened 2017-12-19 04:26 UTC
**TypeScript Version:**  2.6.2

While trying to make redux a bit more typesafe than what you get with the out of the box typedefs, I ran into the following issue where a function that expects a generic type as its argument still expects an argument to be passed, even when that argument is undefined.

**Code**

```ts
// Action definiton from redux typedefs
interface Action {
  type: any;
}

// Action type using generics
// T is intended to be a string literal
// P is optional, so it defaults to undefined
interface TypedAction<T extends string, P = undefined> extends Action {
    readonly type: T;
    readonly payload: P;
}

// Function for generating the most common type of action creator
// Takes a TypedAction as its generic arg and uses that to infer
// what is required as the payload in the returned action creator
function makeActionCreator<T extends TypedAction<any, any>>(
    type: T['type'],
): (p: T['payload']) => T {
    return payload => ({ type, payload } as T);
}

//=================
// Example usage //
//=================

interface EmailPasswordCredential {
    readonly email: string;
    readonly password: string;
}

enum SignUpActionType {
    executeSignUp = 'SignUp/executeSignUp',
    reportSuccess = 'SignUp/reportSuccess',
    reportError = 'SignUp/reportError',
}

////
// Action Types
////

// Sign-up action
// requires an email and password to be specified
type ExecuteSignUpAction = TypedAction<
    SignUpActionType.executeSignUp,
    EmailPasswordCredential
>;

// Success action
// Doesn't need a payload
type ReportSignUpSuccessAction = TypedAction<SignUpActionType.reportSuccess>;

// Error action
// Fired when something didn't work (like a 400)
// Error is passed back as the payload
type ReportSignUpErrorAction = TypedAction<SignUpActionType.reportError, Error>;

////
// Action Creators
////

const signUp = makeActionCreator<ExecuteSignUpAction>(
    SignUpActionType.executeSignUp,
);

const reportSignUpSuccess = makeActionCreator<ReportSignUpSuccessAction>(
    SignUpActionType.reportSuccess,
);

const reportSignUpError = makeActionCreator<ReportSignUpErrorAction>(
    SignUpActionType.reportSuccess, // because of the generic - this correctly errors from the type mismatch
);

// the real problem:

// this correctly errors, an EmailPasswordCredential is required
signUp(); 

// this, however, should be allowed. 
//the missing argument is "undefined", which is what we are passing, by passing nothing.
reportSignUpSuccess();

// this fixes the type error, but feels unnecessary
reportSignUpSuccess(undefined);
```

**Expected behavior:**

`reportSignUpSuccess()` should be able to be called without any explicit arguments.

**Actual behavior:**

`reportSignUpSuccess()` throws a type error when called, unless `undefined` is passed explicitly.

**Comment by ajafff** [comment] 2017-12-19 09:51
Duplicate of #4260?

**Closed** 2018-01-02 18:40 UTC
Labels: Duplicate
