### ISSUE TITLE
Slow behavior in '--watch'

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#7376] opened 2016-03-03 20:15 UTC
There have been a few cases reported by customers that using `--watch` has been on the slow side. We should elicit feedback to understand what's going on.

Examples:

* https://www.reddit.com/r/typescript/comments/48rzzq/protip_what_to_do_to_solve_the_current_slowness/
* https://gitter.im/Microsoft/TypeScript?at=56d86d9906ba9a282a28ecf1

**Comment by mhegazy** [comment] 2016-03-03 20:22
//CC @zhengbli

**Comment by jeffreymorlan** [comment] 2016-03-03 20:45
I've noticed this on Ubuntu (node v0.10.25). TypeScript 1.6 used to always detect changes within a second. 1.7 and 1.8 take about 2 seconds for a one-file project, and anywhere between 2-10 seconds for a large project.

It seems this only affects older versions of node. If I use node 4.0.0 or later, it's down to less than a second again.

**Comment by jhades** [comment] 2016-03-03 20:56
this could be duplicate than #6178. I've noticed this in version 1.8.7

**Comment by zhengbli** [comment] 2016-03-03 20:57
As @jeffreymorlan noticed, the current implementation does different things for new node (> v4.0) and older node. For the newer ones, it uses the non-polling watchers, which is fast. For the older node version, it uses polling watchers with a large polling interval with concerns that a shorted polling interval might cause pains for HDD users on old machines.

@jhades, what is your environment when you notice this? What is your node version?

**Comment by vivainio** [comment] 2016-03-03 21:07
I noticed this with one of the 1.8 prerelease versions (when I was experimenting with migration from 1.7 series, and "-m systemjs --outfile test.js"). 10 sec delay on windows. Just tried with current stable release, and can't reproduce it anymore. So possibly dupe of #6178

**Comment by jhades** [comment] 2016-03-04 08:52
@zhengbli i'm on 4.2.1

**Comment by zhengbli** [comment] 2016-03-04 18:39
@jhades Are you on Windows/Linux/Mac? Do you have a sample project that I can use to repro the issue? As I just tested on my windows machine with node 4.2.1 and TypeScript 1.8.7, changes in a project with 100+ ts files can be detected instantly with `tsc --watch`.

**Comment by jhades** [comment] 2016-03-04 19:10
@zhengbli I'm on OSX 10.11.1

**Comment by DanielRosenwasser** [comment] 2016-03-07 03:15
I have been seeing more and more projects suggesting/utilizing [Watchman](https://facebook.github.io/watchman/). Perhaps we should consider looking into it.

**Comment by chapati23** [comment] 2016-03-08 22:18
`tsc -w` also got a LOT slower for me lately, tried all kinds of configs and debugging my code and external packages but it really seems this was introduced by typescript.

tried 1.7.3, 1.8.7 and 1.9.0-latest-dev on node 5.6 and node 5.7 (OSX 10.11.3), all take minimum 3-5sec to pick up file changes. unfortunately i can't really pinpoint which version exactly introduced the slow behavior but it definitely used to be a LOT faster.

**Comment by realyze** [comment] 2016-03-31 22:52
Yep, 1.6 picks up the changes much faster (Mac OS X 10.11.2).

**Comment by basarat** [comment] 2016-04-02 10:52
> I have been seeing more and more projects suggesting/utilizing Watchman. Perhaps we should consider looking into it.

Got excited, then saw poor windows support : https://facebook.github.io/watchman/docs/install.html `Windows x64 on Windows Server 2012 R2 and later is currently in alpha status.` :rose:

**Comment by jhades** [comment] 2016-04-02 11:25
For anyone running into the same issue with typescript or other tools: nodemon is a good way of watching a directory and triggering a task (its not only to restart the server). For example this npm script watches the folder src/app for *.scss  files and then runs an npm task: 

    "watch-css": "nodemon -V -w src/app --ext \".scss\" --exec \"npm run build-css\""

So in principle this should work:

    "watch-ts": "nodemon -V -w src/app --ext \".ts\" --exec \"tsc\""

**Comment by jimbocoder** [comment] 2016-04-11 23:19
Upgrading node from 0.12.4 to 5.10.1 fixed this for me.  `tsc -w` is now behaving exactly as expected, where previously delays between 5 and infinity seconds were present.

**Comment by vivainio** [comment] 2016-04-19 05:58
We still detected this problem on Node 0.10.x. Upgrading to Node 4.x immediately fixed it.

Maybe it would make sense to add a warning when using --watch on old Node versions?

**Comment by mhegazy** [comment] 2016-04-27 21:20
@zhengbli should this be fixed with https://github.com/Microsoft/TypeScript/pull/8196 ?

**Comment by zhengbli** [comment] 2016-04-27 21:25
Yep. Should have no problems with watch perf anymore.

**Comment by mhegazy** [comment] 2016-04-27 21:30
We believe this should be addressed by https://github.com/Microsoft/TypeScript/pull/8196. and should be available on `typescript@next`. if you are still experiencing issues, please let us know and we will reopen the issue.

**Closed** 2016-04-27 21:32 UTC
Labels: Fixed, Needs More Info
