### ISSUE TITLE
Type-asserted variable become unknown again at once change

### ISSUE THREAD

**Issue by fenying** [microsoft/TypeScript#50440] opened 2022-08-25 08:04 UTC
# Bug Report

A type-asserted variable from `unknown`, would become `unknown` again at once its value changed

### 🕗 Version & Regression Information

- This problem could be reproduced between versions _4.3.5_ (earlier versions not tested) and _latest nightly_

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABDAzgORAWwEYFMBOAFCgFyLgDWYcA7mAJRkrLNhZ76IDeAUD4gMT5cUEPiRQAngAdccYImYBeFYgDkbHATUBuHgF8+oSLASIouFFEIQylanUaIAbnBgATbn0HIFhAISoGFpEEPT0Xvw+glAAFvi0iGC4NIgAKjK4AKL4CURqNLEAhlAA-Gr0ej6GUQIQiEqI9QDUiACMerWIAPQAVL1diL2IAOqxkog0cCAANp5FSEUoKAQWnpociHgQcJi45GBUtIsA5kUwYKWDvd1dMH4t7Q2qAAwRvIOCwqLiVYI1Ph2YBQcBmuAAdDM4CcbJUDHwLFZCG0AEwAZjhQA)

### 💻 Code

```ts
function isNumber(s: unknown): s is number { // it's the same even changed to string or other types

    return typeof s === 'number';
}

let c: unknown = 123;

if (!isNumber(c)) {

    throw new TypeError('what?');
}

c = c + 1;

/**
 * Why would an asserted number become unknown again?
 */
if (c + 1 === 0) {

    console.log(c);
}
```

### 🙁 Actual behavior

the assert number-typed variable `c` became `unknown` again.

### 🙂 Expected behavior

It should keep being `number` type

**Comment by MartinJohns** [comment] 2022-08-25 09:21
Duplicate of #27706. Used search terms: `unknown narrow in:title`

**Closed** 2022-08-27 06:18 UTC
Labels: Duplicate
