### ISSUE TITLE
Enable constants as computed values for string enums

### ISSUE THREAD

**Issue by kataik** [microsoft/TypeScript#40793] opened 2020-09-27 04:57 UTC
# Search Terms

'TS18033', 'typescript define enum with constant string value', 'string enum computed constant'

## Suggestion

Please consider enabling to use constant variables as values for string enums. The following code snippet fails compilation with TS18033 ('Only numeric enums can have computed members, but this expression has type 'string'. If you do not need exhaustiveness checks, consider using an object literal instead.')

```ts
const VALUE: string = 'ENUM_VALUE';

enum MyEnum {
  KEY = VALUE, // <-- Fails with TS18033
}

console.log(MyEnum.KEY);
```

, whereas the following passes:

```ts
enum Values {
  VALUE = 'ENUM_VALUE',
}

enum MyEnum {
  KEY = Values.VALUE,
}

console.info(MyEnum.KEY);
```

## Use Cases

Use string interpolation (templated strings) when defining the value of a string enum to be able to reuse pre-defined constants as part of the value. (E.g. namespace prefixes, extension postfixes)

## Examples

```ts
const NAMESPACE: string = 'com.mycompany.myservice';

enum Errors {
  INVALID_INPUT_ERROR = `${NAMESPACE}.errors#InvalidInput`,
}
```

## Checklist

My suggestion meets these guidelines:

* [ X ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ X ] This wouldn't change the runtime behavior of existing JavaScript code
* [ X ] This could be implemented without emitting different JS based on the types of the expressions
* [ X ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ X ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by Inlesco** [comment] 2020-10-11 07:52
This would be a perfectly valid feature to implement since computed number values are already allowed.

Is there any reason why computed string values shouldn't be allowed for enums? Perhaps I'm not aware of something tied to the bigger picture?

**Comment by moneydance** [comment] 2020-11-12 20:29
I'm also curious about why computed enums are disabled for strings.

**Comment by fenduru** [comment] 2021-04-16 00:50
This would be handy when when writing a React component with a prop that controls a css class. Right now I'm doing the following

```tsx
enum ComponentVariant {
  Foo,
  Bar,
}

const classes = {
  [ComponentVariant.Foo]: styles.fooClassName,
  [ComponentVariant.Bar]: styles.barClassName,
}

export default function TheComponent({ variant }: {variant: ComponentVariant}) {
  return <div className={classes[variant]} />
}
```

But it would be both cleaner, and also safer (i.e. prevent accidentally indexing into a non-existing value in the classes object) to do this directly:

```tsx
enum ComponentVariant {
  Foo = styles.fooClassName,
  Bar = styles.barClassName,
}

export default function TheComponent({ variant }: {variant: ComponentVariant}) {
  return <div className={variant} />
}
```

**Comment by tomasdev** [comment] 2021-05-01 21:16
Following the namespace reasoning, highly useful for developing browser extensions or other scripts where we don't want to collision with pre-existing scripts, such as `postMessage(<this value>, '*')`

**Comment by ahnpnl** [comment] 2021-07-06 18:01
I also need this

**Comment by RebeccaStevens** [comment] 2021-11-19 07:07
Additionally symbols should be allowed to be used as enum values.

```ts
enum MyType {
    foo = Symbol("foo"), // Error: ts(18033) - Only numeric enums can have computed members, but this expression has type 'symbol'. If you do not need exhaustiveness checks, consider using an object literal instead.
}
```

**Comment by Thorugoh** [comment] 2021-11-19 17:05
I'm with the same problem :/

**Comment by webia1** [comment] 2021-11-29 10:11
please enable, thank you!

**Comment by daltonrussell** [comment] 2021-12-20 20:57
Facing the same issue. I would love to have computed values for strings so I can assign react components to enums.

**Comment by SheppardX** [comment] 2022-01-10 13:35
PUSH!! i am currently facing this issue too. 
have an ENUM with endpoints and want to reuse pre-defined parts of that 

```
export const customerEndpoint = '/customers';

export enum ENDPOINTS {
  INVOICES = `${customers}/invoices`,
  BASKET = `${customers}/basket`,
}
```

as an example

**Comment by zheoreh** [comment] 2022-01-19 21:51
+1

**Comment by estefafdez** [comment] 2022-02-14 13:18
I would love to have this on TS, thanks!

**Comment by JordanDC2** [comment] 2022-03-09 21:15
This would be a great feature, currently running into this same issue

**Comment by WilliamChazot** [comment] 2022-03-11 15:19
I'm currently working to build a enum and interfaces to organize my database fields, finally as a custom orm system, and all my database fields have a prefix `slot_`, that I wanted to specify in string literals in my enum:

```typescript
// current enum
enum MyTableFields {
  OBJECT_ID = 'slot_objectID',
  CODE = 'slot_code',
  LABEL = 'slot_label'
}

// wanted enum
const slot_ = 'slot_'
enum MyTableFields {
  OBJECT_ID = `${slot_}objectID`,
  CODE = `${slot_}code`,
  LABEL = `${slot_}label`
}

```

**Comment by MrEmanuel** [comment] 2022-04-06 14:42
I too want to compute two enums with slight variations, such as a prefix.

**Comment by stormBMO** [comment] 2022-04-14 08:38
+1 here, would be great innovation

**Comment by azad-derakhshani-GS** [comment] 2022-04-25 12:48
+1 from me as well, I would like to assign values to enum variables depending on the environment via the ternary operator.

**Comment by iulia-codes** [comment] 2022-04-26 17:14
I support this as well, any prospects for implementation horizon?

**Comment by Labernator** [comment] 2022-04-27 13:05
+1, this would be quite helpful

**Comment by nkappler** [comment] 2022-04-27 13:12
There's another error message you might get if you try this:
`Computed values are not permitted in an enum with string valued members. ts(2553)`

**Comment by aghArdeshir** [comment] 2022-05-19 07:56
I'm in favor if this change too. I would like to be able to do something like this:

![image](https://user-images.githubusercontent.com/5755214/169242562-ba0cb959-d4bf-4764-a331-93f9b67170e1.png)

**Comment by ZEAL-MATCH-LTD** [comment] 2022-05-19 10:45
This would be ideal! Especially when declaring API route constants. 
```ts
import { getExact } from "../../util/env";

enum ApiRoutes {
    users = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    blockUser = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    reverifyUser = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    resetPassword = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    preferences = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    pacemakers = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    matchPreferences = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    userLocation = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    tokens = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    messageThread = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    readMessage = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    suggestedSports = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    suggestedGenders = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    findMatch = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    likeUser = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    dislikeUser = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    createP2pReferralCode = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    p2pReferral = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    citiesAPI = 'https://wft-geo-db.p.rapidapi.com/v1/geo/cities',
    discover = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
    eventAttendance = `${getExact('REACT_NATIVE_BACKEND_URL')}/****`,
};

export default apiRoutes;
```

**Comment by GO-DIE** [comment] 2022-06-20 06:35
I also need this feature
The deletion of this feature causes my code to be difficult to maintain

**Comment by embedify** [comment] 2022-06-28 06:00
+1

**Comment by webia1** [comment] 2022-07-04 10:00
With all due respect for the work that has been done for TypeScript so far.  (Forgive me; English is not my mother tong)

I don't know if anyone gets the opposite impression somehow, but we TS lovers are not here for trolling. On the contrary, I personally would be willing to help for free.

Unfortunately, I personally have the impression that the ts-dev-team does what they want while ignoring the community's wishes and taking well-intentioned criticism and suggestions for improvement as an insult. Please be aware; that we are the community.

**For example, this issue has been waiting for a solution almost for two years, and this is not an isolated case.**

Although I want to help and I always try to be polite; (because I wish TS to continue and go in the right direction because I love using TS and I've put a lot of effort into it for years), I'm being terrorized and insulted by some core devs including dev-lead. I don't know how many I've had to block lately because of this. But that was not the case 2 years ago. 

I do not know if it is because of the corona, but we must establish respectful communication again. (If someone can't contribute anything positive, at least he shouldn't hinder.)

TS-Team has to take community wishes seriously. They do what they want to do, block new ideas as off-topics, close bugs without solving them, and they want us to do what they want instead of doing what we need to do. 

Sorry, I won't play this game for long. I convinced a giant company (German Railways) to use TS in the middleware, which was a three-digit million project. I probably wouldn't have done that if I had been a troll.

Dear TS team, please take this seriously.

Many thanks

**Comment by miguelci** [comment] 2022-07-13 10:00
+1

**Comment by a-tarasyuk** [comment] 2022-07-16 06:32
_Meeting Notes_ https://github.com/microsoft/TypeScript/issues/49927 about this issue.

**Comment by lyssareba** [comment] 2022-08-02 17:17
+1 also useful for enums utilizing i18n translations

```
export enum FooBarBas {
  FOO = i18next.t('Foo'),
  BAR = i18next.t('Bar'),
  BAS = i18next.t('Bas'),
}
```

**Comment by hieucd04** [comment] 2022-08-11 11:44
+1

**Comment by bfoong-equinix** [comment] 2022-08-29 07:56
+1

**Comment by harishgupta42** [comment] 2022-09-05 09:23
+1

**Comment by ashen780** [comment] 2022-09-07 07:40
It's been 2 years. still waiting for this feature.

**Comment by Nut41tank** [comment] 2022-09-08 12:25
+1

**Comment by XiaoSunXS** [comment] 2022-09-08 14:38
Still waiting too!

**Comment by TomasSestak** [comment] 2022-09-14 15:20
i also need this

**Comment by Am1rr3zA** [comment] 2022-09-15 04:30
+1 this is really useful, specially in case of AWS CDK (deploying on test account)

**Comment by BryanValeriano** [comment] 2022-09-28 19:10
+1

**Comment by BryanValeriano** [comment] 2022-09-28 19:28
What I would like to do:
`export enum SplashColor {
  Red = [1, 0, 0.14, 0.5],
  Yellow = [0.9, 0.84, 0.28, 1],
  Blue = [0.3, 0.1, 0.9, 1],
  Purple = [0.5, 0.1, 0.7, 1],
  Orange = [0.8, 0.4, 0, 1],
};`

What I'm doing: 
`export type tint = [number, number, number, number];

export interface SplashColor {
  Red: tint,
  Yellow: tint,
  Blue: tint,
  Purple: tint,
  Orange: tint,
};

export const SplashColorType: SplashColor = {
  Red: [1, 0, 0.14, 0.5],
  Yellow: [0.9, 0.84, 0.28, 1],
  Blue: [0.3, 0.1, 0.9, 1],
  Purple: [0.5, 0.1, 0.7, 1],
  Orange: [0.8, 0.4, 0, 1],
}`

**Comment by zendesk-olgaczarnecka** [comment] 2022-09-30 08:21
👋 Hi @ahejlsberg
Will [this PR](https://github.com/microsoft/TypeScript/pull/50528) be merged soon ?

**Comment by atanas-hristov-deltatre** [comment] 2022-10-12 17:57
I'd love to have that feature too.

**Comment by goonerify** [comment] 2022-10-17 02:37
Any update on this and the [associated PR](https://github.com/microsoft/TypeScript/pull/50528)?

**Comment by ahejlsberg** [comment] 2022-10-17 17:11
Stay tuned... 😉

**Comment by ahejlsberg** [comment] 2022-10-17 19:35
Now implemented in #50528.

**Comment by saharis9988** [comment] 2022-10-21 08:46
very important feature for declaring constants in more generic way!

**Comment by DZ8540** [comment] 2022-10-28 16:29
+1

**Closed** 2022-11-03 18:05 UTC
Labels: Suggestion, Awaiting More Feedback, Fix Available

**Comment by ann-aot** [comment] 2022-11-25 20:14
+1

**Comment by rutexd** [comment] 2022-11-28 23:55
+1

**Comment by vfa-locltb** [comment] 2022-12-01 07:40
+1

**Comment by jpaxtonrs** [comment] 2022-12-12 21:56
+1 as well

**Comment by RyanCavanaugh** [comment] 2022-12-13 21:10
Why are people +1ing an implemented feature?

**Comment by handletastic** [comment] 2022-12-13 21:13
Probably because people don't yet know of it? 🤷🏻‍♂️ I mean it's been implemented like a month ago only.

**Comment by handletastic** [comment] 2022-12-13 21:13
> Why are people +1ing an implemented feature?


Probably because people don't yet know of it? 🤷🏻‍♂️ I mean it's been implemented like a month ago only.

**Comment by youthug** [comment] 2023-03-14 06:45
Hey guys, how to fix this error?

got this in [playground](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230313#code/MYewdgzgLgBKYBMCWUnhgXhlATgVwFMBuAWAChz5oYAFHAgMyQA8AuGaHJMAc0znDJU6APwwARAHoEAQygzxMdlIggAtgQBqMgDaFxpCmSqwCYPGpgAlEHigEIMAN7kYb2jJxRHWAAYASJzpGFgBfSQAHT29fABp3BMlJCWk5GUjoiHFXdwBJMAA3ECRgB34AoPomZnDuIpKHXzcklNl5STri0qzyUPIgA) (TS version: the latest Nightly):
> const enum member initializers must be constant expressions.(2474)

<img width="1583" alt="image" src="https://user-images.githubusercontent.com/24794392/224915911-e2dc4d09-4c0d-4e12-953b-6d5534d75b2f.png">

and this in IntelliJ IDEA (TS version: 5.0.1-rc)
> TS18033: Type 'string' is not assignable to type 'number' as required for computed enum member values.

**Comment by dfl-zeke** [comment] 2023-03-16 23:57
> Why are people +1ing an implemented feature?

It's been a 4-5 months and still not included into latest release, wym.

**Comment by RyanCavanaugh** [comment] 2023-03-17 21:21
5.0 came out yesterday and includes this feature.

**Comment by afarah1** [comment] 2023-06-02 19:29
I have a use case like this which still yields TS18033 on 5.0.4:

```
const fooStr = 'foo';

export const myStrings = {
    foo: fooStr,
};

enum MyEnum {
  FOO = myStrings.foo,
};
```

**Comment by dburgos92** [comment] 2023-07-06 09:24
On 5.0.4 with angular this doesn't work:

`export enum Section{
    ASIGN = GlobalConstants.ASIGN
    DISTRIBUTION = "Distribucion"
}`

**Comment by nick4fake** [comment] 2023-07-26 18:41
@RyanCavanaugh this is still an issue even with TS 5.1.6:

![image](https://github.com/microsoft/TypeScript/assets/1065993/d4c635f7-42f6-4f25-a5d8-1d251fa3d475)

**Comment by hanzheliva** [comment] 2023-08-03 01:18
<img width="907" alt="Screenshot 2023-08-02 at 9 16 12 PM" src="https://github.com/microsoft/TypeScript/assets/140115653/0937b2f9-1781-4c07-9881-dba8b4458dd0">

@RyanCavanaugh Could you please check what the cause of this problem is?

**Comment by RyanCavanaugh** [comment] 2023-08-03 19:27
The error message means what it says.

**Comment by AlexKDawson** [comment] 2023-08-07 21:49
@RyanCavanaugh I think people (myself included) are still seeing this warning after installing TS >5.0 
I'd expect this error to not appear if the feature was implemented?

**Comment by AlexKDawson** [comment] 2023-08-08 00:18
Side Note: I've seen a couple examples of people trying to do the same with ternary expressions, but the key difference being that typescript still evaluates the following

```typescript
const foo = true ? 'x' : 'y';
```
as `foo: 'x'|'y'` despite that it could technically be evaluated as a const expression `foo: 'x'`

So for anyone curious, ternary expressions still won't work but at least it makes sense why.

**Comment by mgol** [comment] 2023-10-04 12:56
Issues with using one string enum in another seem like TS bugs; I reported a separate issue for this:
https://github.com/microsoft/TypeScript/issues/55978
Please upvote if you hit this, too.

Flagged code, for reference:
```ts
enum E1 {
  A = 'A',
}

const enums = {
  E1,
};

enum E2 {
  A = enums.E1.A,
}
```

**Comment by Friend-LGA** [comment] 2025-01-28 16:55
Hmm.... this should work, right?

```ts
const option2 = 'option2';
const option3 = 'option3' as const;

export enum TestEnum {
  Option1 = 'option1',
  Option2 = option2, // <<< no errors here
  Option3 = option3, // <<< ts(18033) error here
}
```

<img width="371" alt="Image" src="https://github.com/user-attachments/assets/01723843-5610-449d-9315-6a1c46cfc98a" />

---
TS version: `5.6.2`
