### ISSUE TITLE
no error

### ISSUE THREAD

**Issue by qq645381995** [microsoft/TypeScript#36320] opened 2020-01-21 01:35 UTC
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts

export interface Demo {
    type: 'input';
    items?: () => { demo?: string };
}

export interface Demo2 {
    children?: Demo[];
}

export const d: Demo2 = {
    children: [
        {
            type: 'input',
            items: () => ({ demo: '1', str: 'no error' }),
        },
    ],
};


```
**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

https://www.typescriptlang.org/play/index.html#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgEWAFsI4BvAKDmrhgE8xgAuOAcmTAFcZWBuKmglREAzgH4WACgCUcALwA+cnAAmxCBLgiYUZAHM4AX36GKFUJFiIUaLLgLqATOQHVsACwQAbFVGBJNQhIAbQBdEzMLaHhsCCRtVRYgiGc5Fxo4D29ffxZg1wz0wuL6RhZ2JC4eABoC4uohYhEpWUU4STJVdXKARlZqrR1ypFI0KGhWI2la+qMZmlDa4wogA
**Related Issues:**

**Comment by DanielRosenwasser** [comment] 2020-01-21 09:38
You'll need to explain what you expect to happen for future issues. Otherwise, my assumption is that this is a duplicate of #241 because you're expecting an excess property error.

**Closed** 2020-01-21 10:09 UTC
Labels: Duplicate
