### ISSUE TITLE
Index signature assignable to type with incompatable optional properties

### ISSUE THREAD

**Issue by webstrand** [microsoft/TypeScript#46025] opened 2021-09-23 16:44 UTC
# Bug Report

### 🔎 Search Terms

index signature assignable compatable optional partial 

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about index signatures

### ⏯ Playground Link

[playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPAN7wDaA1iAJ6GYwCWKA5gLq0YPPwC+A3AFD8A9EJx549NPCho09JiigAjCAgxJ4S2PADu9DAAt4KDSBgwkMKXAAOljCGD9k6LFpiESaJAFsQABQsbAH5CFABXHyUzUhYeeABeMSQBIA)

### 💻 Code
```ts
declare const foo: { [key: string]: string };
const bar: { someProp?: number[] } = foo;
```
### 🙁 Actual behavior

`foo` is assignable to `bar` without errors.

### 🙂 Expected behavior

`foo` is not assignable to `bar` because the index signature is incompatable with `someProp`; `string` is not assignable to `number[]`.

The issue is that if `foo.someProp` exists with the type `string`, that assignment will cause runtime errors.

### Additional Examples
Computed properties add another level of confusion due to this error being unreported:
```ts
declare function foo(x: { a?: string[], b?: string[] }): void;

declare const prop: "a" | "b";
foo({
  [prop]: () => {} // should be an error
})
```
[playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwAoAPALngG94oB+CgZwxi1QHMBtAXQBp4AjevCYt23eAF8AlBQBuOLMADcAKBWhIsBGDxN4ABxg59FAERRT8AD7xT-U6sSEilFfHgdDxrhSJT4ALwAfFQS8AD04cIAFjjIEMACCFD4IDBGMCrSQA)

Excess properties are normally permitted, but index signatures are supposed to provide type information for all unexpected properties on an object.
```ts
const foo: { 
  a: string; 
  [key: string]: string 
} = { a: "", b: "" };

const bar: { 
  a: string; 
  b?: number[] 
} = foo;

// at runtime bar.b has the type `string` not `Array<number>`
```
[Playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZiEAuGBvGAoGMCGLoBOAlmAOYDcm2A2gNYCmAnvlMWQLotumYC+MAXjS4UAIlEAaGACMxomL3IYMoSLGk4CKdFhExCJClRkB+FGACuAW2n0C1dn0HxESjAHp3uWAQtgoRFb0MpoAdNIwABY4EDBQkcFQjAAOwQAGBmRpMGAgsGkAggQEOIwAPJY2dgB8aUA)

**Comment by MartinJohns** [comment] 2021-09-23 17:12
Duplicate of #42719. Used search terms: `index optional in:title`

**Comment by webstrand** [comment] 2021-09-23 18:41
I'm not reall sure I'd call this a _Suggestion_, given the issue with computed properties?

**Closed** 2021-09-26 18:00 UTC
Labels: Duplicate
