### ISSUE TITLE
Emit for `as` operator drops nested module prefix

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#5524] opened 2015-11-04 12:56 UTC
Hi,

**Version:** TS 1.6

```
module foo.bar {
	export function baz(){}
};

module foo {
  const a1 = bar['baz']; // foo.bar['baz']
  const a2 = (<any>bar)['baz']; // foo.bar['baz']
  const a3 = (bar as any)['baz'];  // bar['baz']
}
```

The emit for `a3` appears to be wrong.

**Comment by mhegazy** [comment] 2015-11-04 17:14
looks like a duplicate of #4832. This should be fixed in `typescript@next`.

**Closed by mhegazy** 2015-11-04 17:14 UTC
