### ISSUE TITLE
import with JSX preserve rewrites the opening tag but not the closing tag

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#5962] opened 2015-12-06 23:17 UTC
Code : 

```ts
import {Provider} from "react-redux"

ReactDOM.render(
        <Provider>
          <App />
        </Provider> , document.getElementById('app')
      );
```

Emits: 

```js
"use strict";
var react_redux_1 = require("react-redux");
ReactDOM.render(<react_redux_1.Provider>
          <App />
        </Provider>, document.getElementById('app'));
```

Expected: 

```js
"use strict";
var react_redux_1 = require("react-redux");
ReactDOM.render(<react_redux_1.Provider>
          <App />
        </react_redux_1.Provider>, document.getElementById('app'));
```

Reported on SO http://stackoverflow.com/questions/34107590/tsx-to-jsx-transformation-doesnt-match-closing-tag-correctly and verified locally personally :rose:

**Comment by mhegazy** [comment] 2015-12-07 06:31
looks like a dupe of #5955

**Closed by mhegazy** 2015-12-07 06:31 UTC
Labels: Bug
