### ISSUE TITLE
Higher order type inference from generic functions lost when result type is wrapped

### ISSUE THREAD

**Issue by maclockard** [microsoft/TypeScript#51850] opened 2022-12-10 21:29 UTC
# Bug Report

### 🔎 Search Terms

Higher order type, Higher kinded type, Inference generic lost, Wrapped

### 🕗 Version & Regression Information
and fill in the line that best applies:

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about higher order type inference

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwHcYoAHAMTTACUQBnZCDAHgEF4QAPDEVYW+KKgCeAbQC6AGnhUAfAAoU6AFzw5AOg2wA5rRUsAlPAC8M6fpXrNMHXsMn4Ab0LESJEMBVV4AXwDcAKH9QSFgERUxcfCJSCnQaekYAJlZ2Lh4+AWFxKVkFSgsNNW1deANjUypzR2dSN2BYsAKrG1K7UycsVFQQGE8fHwCg8Gg4eDA8Wgx4SZhOrQAVHAA5ZABbCxKZubb4VDWAIx6A8dRJ6YxZ1AXltYB1FzrjGvJKeIYMOS2rxZXV-V94AB6QGqTYXbblarRVzuFR7VaHGA+fwnM5fa6-e61dyJJ7QhpvJKfcHfG5-AHAqEPdwNDYqdE7JzQupwg49freQLBEYIVFTDA4FgwYhCFRMebyDAqeY7ebiY4TfmC4VQIRYmHAPEuAl0d5yAVCkX-eBAkHiyXSxnPFnwOViZF8+AGlVq6nAXFGZ46hIYRL65VGikgplu2mqKWZIRW5mwyPiDnwAC08CUciAA)

### 💻 Code

```ts
declare function wrapFuncResult<A extends any[], R>(func: (...args: A) => R): (...args: A) => { wrapped: R };

declare function wrapFuncResult2<A extends any[], R>(func: (...args: A) => R): { wrappedFunc: (...args: A) => { inner: R } };

declare const stringToNum: (s: string) => number;
const stringToNumWrapped = wrapFuncResult(stringToNum); // (s: string) => { wrapped: number }
const stringToNumWrapped2 = wrapFuncResult2(stringToNum); // { wrappedFunc: (s: string) => { wrapped: number } }

declare const toArray: <T>(t: T) => T[];
const toArrayWrapped = wrapFuncResult(toArray);  // <T>(t: T) => { wrapped: T[] }
const toArrayWrapped2 = wrapFuncResult2(toArray); // { wrappedFunc: (t: any) => { wrapped: any[] } } - :(
```

### 🙁 Actual behavior
The function `toArrayWrapped2` is of type `{ wrappedFunc: (t: any) => { wrapped: any[] } }`. The inference of the type parameter `T` from `toArray` was lost when the return type was wrapped.

### 🙂 Expected behavior

The function `toArrayWrapped2` is of type `{ wrappedFunc: <T>(t: T) => { wrapped: T[] } }`. This would preserve the type parameter `T` from `toArray` just like the unwrapped result type of `toArrayWrapped`.

**Comment by jcalz** [comment] 2022-12-11 13:41
Duplicate of #49505

**Closed** 2022-12-15 18:00 UTC
Labels: Duplicate
