### ISSUE TITLE
Making nav-bar elements more intuitive

### ISSUE THREAD

**Issue by Hrshk15** [microsoft/TypeScript#41175] opened 2020-10-20 12:10 UTC
## Search Terms

Nav-bar , hover

## Suggestion

Nav-bar **elements** can have a very basic highlighting effect on **hover**  which incline with the simple design of the website.  When user moves his/her cursor over it . It should feel more intuitive. I'll be more than happy to help.

## Use Cases

This will make it more intuitive that it is a clickable element . 
## Examples

A very basic text-highlighting effect on hover.
## Checklist

My suggestion meets these guidelines:
* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-10-20 21:58
Might want to check out: https://github.com/microsoft/TypeScript-Website

**Comment by RyanCavanaugh** [comment] 2020-10-26 18:31
@orta your call

**Comment by orta** [comment] 2020-10-27 14:11
Thanks, this is a dupe of https://github.com/microsoft/TypeScript-Website/issues/1266

**Closed by orta** 2020-10-27 14:11 UTC
Labels: In Discussion, Suggestion
