### ISSUE TITLE
Add support for ES2016 Object Spread Initializer

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#6525] opened 2016-01-18 09:03 UTC
_From @onybo on January 13, 2016 8:57_

Object Spread Initializers is a proposed feature of ES2016 and is very useful when writing Redux reducers. The syntax is supported in babel, but when using the feature in Visual Studio Code it will mark the spread operator as a syntax error.

See: https://github.com/sebmarkbage/ecmascript-rest-spread/blob/master/Spread.md
for more information of the feature.

It would be very nice if Visual Studio Code did not mark the use of this feature as an error with a red squiggly.

The current behavior in Visual Studio Code is also described in Issue #1640 

_Copied from original issue: Microsoft/vscode#1974_

**Comment by jrieken** [comment] 2016-01-18 09:03
_From @jpierson on January 17, 2016 3:1_

+1 I've been pretty much ignoring my errors and warnings in VSCode in hopes that this would be addressed soon but it's been a few months now. I've also noticed some discussion in the ESLint project about this and their suggestion was to make use of babel-eslint. I wonder if that is possible to use in VSCode...

**Comment by DanielRosenwasser** [comment] 2016-01-18 20:15
Duplicate of #2103.

**Closed by DanielRosenwasser** 2016-01-18 20:15 UTC
