### ISSUE TITLE
Completion interferes with typeing a "type alias".

### ISSUE THREAD

**Issue by CyrusNajmabadi** [Microsoft/TypeScript#2882] opened 2015-04-23 00:12 UTC
Completion shouldn't appear after "type" when typing a type alias.

**Comment by DanielRosenwasser** [comment] 2015-04-23 01:14
Sounds like a duplicate of #2520, though as @CyrusNajmabadi pointed out offline, there shouldn't even be a builder since this is a declaration position.

**Comment by paulvanbrenk** [comment] 2015-05-13 22:54
Fixed with PR #2979

**Closed by paulvanbrenk** 2015-05-13 22:54 UTC
Labels: Bug, Fixed
