### ISSUE TITLE
Show Proper Suggestions within Class Body

### ISSUE THREAD

**Issue by audinue** [Microsoft/TypeScript#15340] opened 2017-04-24 11:10 UTC
**TypeScript Version:**  2.2.2

**Code**

```ts
class Component {

    /**
     * Called when this component is updated.
     */
    componentUpdated () {
    }
}

class MyComponent extends Component {

    // CTRL+SPACE here...
}
```

**Expected behavior:**
TypeScript [language service] shows proper sugestions **including the documentation** for the class members.

For example:
```ts
constructor
toString
componentUpdated
```

**Actual behavior:**
![screenshot_1](https://cloud.githubusercontent.com/assets/1407800/25334445/d6b57cf4-2918-11e7-903a-bce0ad4112e4.jpg)

TypeScript showed irrelevant suggestions.

**Comment by mhegazy** [comment] 2017-04-24 17:11
Duplicate of https://github.com/Microsoft/TypeScript/issues/7158

**Closed by mhegazy** 2017-04-24 17:11 UTC
