### ISSUE TITLE
Extracting return types from functions while mapping types?

### ISSUE THREAD

**Issue by JasonKleban** [Microsoft/TypeScript#15763] opened 2017-05-11 13:43 UTC
I don't recognize any examples of this in the docs.  Can we map to a type that holds the return types of key-indexed functions?  Is there a syntax for that?

```
var ex = {
    One<S>(x : S) { return x; }
    
    Two<T>(y : T) { return "foo"; }
    
    Three() { return false; }
}

 // Bad because all return types would have to be the same `T`
type BadMappedOutputs<T, O extends { [k : string] : () => T }> = {
    [K in keyof O] : T
}

// Something like this?
type MappedOutputs<O> = {
    <T>[K in keyof O where O[K] extends () => T] : T
}

var baz = MappedOutputs<typeof ex>;

baz.One; // any
baz.Two; // string
baz.Three; // boolean
```

**Comment by aluanhaddad** [comment] 2017-05-17 19:32
I believe this is a duplicate of #6606.

**Comment by mhegazy** [comment] 2018-02-08 18:30
You should be able to get this working today with [Conditional Types](https://github.com/Microsoft/TypeScript/pull/21496)
```ts
type ReturnType<T> = T extends (...args: any[]) => infer R ? R : never;

type MappedOutputs<T> = {
    [P in keyof T]: ReturnType<T[P]>
}
```

**Closed by mhegazy** 2018-02-08 18:30 UTC
Labels: Needs Investigation
