### ISSUE TITLE
tsconfig.json is not loaded properly when definitions in 'typescript' package is imported explicitly

### ISSUE THREAD

**Issue by Mongkii** [microsoft/TypeScript#42112] opened 2020-12-25 13:42 UTC
# Bug Report

### 🔎 Search Terms

tsconfig doesn't work

### 🕗 Version & Regression Information

4.1.2

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 4.0 ~ 4.1.2

### ⏯ Playground Link

[bug-demo.zip](https://github.com/microsoft/TypeScript/files/5742783/bug-demo.zip)

#### tsconfig.json
```json
{
  "compilerOptions": {
    "target": "ES2020"
  }
}
```

#### scene A
```ts
// Some third-party packages would install @types/node with it.
// if @types/node is installed,the primary definition of setTimeout would be the one in @types/node,
// which returns NodeJS.Timeout and therefore can't be assigned to a number type

let timerId: number | undefined;
timerId = setTimeout(() => {}, 0); // ❌  Type 'Timeout' is not assignable to type 'number'.ts(2322)

// At the time, the tsconfig is loaded, so flatMap (ES 2019 feature) works perfectly.
[].flatMap((item) => item); // ✅
```

##### scene B
```ts
import { setTimeout as WindowSetTimeout } from "typescript/lib/lib.dom";

let timerId: number | undefined;

//  So I'd import the window.setTimeout definition directly from typescript package, to avoid the error in assignment.
timerId = (setTimeout as WindowSetTimeout)(() => {}, 0); // ✅

//  However flatMap then reports an Error, seems tsconfig is not loaded properly.
[].flatMap((item) => item); // ❌ Property 'flatMap' does not exist on type 'never[]'. Do you need to change your target library? Try changing the `lib` compiler option to 'es2019' or later.ts(2550)
```

### 🙁 Actual behavior

tsconfig.json is not loaded properly, because flatMap is not enabled.

### 🙂 Expected behavior

tsconfig loaded successfully

**Comment by andrewbranch** [comment] 2020-12-28 19:31
You don’t import lib files, you add them to the `"lib"` array in your tsconfig.

**Comment by Mongkii** [comment] 2020-12-29 00:57
I know I could use `lib` to import definitions and `types` to include only what I need.

However my situation, it is:

- `@types/node` would add an overload to `setTimeout`
- the import-from-node `setTimeont` is always the default choice of overload
- `@types/node` is necessary so I can't use `types` to omit it
- I don't feel like to change my code from `setTimeout` to `window.setTimeout`

Therefore I can only import the browser version `setTimeout` definition from lib file and force assign it, which makes the tsconfig not working properly.

**Comment by AviVahl** [comment] 2020-12-29 02:32
I use `ReturnType<typeof setTimeout>`. Works well with dom types, node types, or the two together.

**Comment by Mongkii** [comment] 2020-12-29 03:12
> I use `ReturnType<typeof setTimeout>`. Works well with dom types, node types, or the two together.

It's a good idea, but it doesn't work in `React.useRef`, which needs a initial value. I usually write something like `const refTimerId = useRef(0);`

**Comment by andrewbranch** [comment] 2020-12-29 18:00
If you have `"dom"` in your `"lib"`, the DOM `setTimeout` should be the first (and therefore default, with no context) overload. If you are referencing lib.dom.d.ts some other way (which you shouldn’t), the order might be reversed.

**Comment by Mongkii** [comment] 2020-12-30 01:37
Whether I add `dom` in `lib` or not, import lib.dom.d.ts or not, default `setTimeout` is always the node one.

By the way, if this problem is cause by misuse, it'll not be given a solution?

**Comment by andrewbranch** [comment] 2020-12-30 19:35
Ok, so the `flatMap` thing looks weird but it’s caused by improperly referencing `lib.dom.d.ts`. The only way you’re supposed to reference it is via `lib` in your tsconfig or `/// <reference lib="dom" />`. Anything else will cause problems.

You’re right though, that the NodeJS `setTimeout` is the first overload once you actually add a second argument. The DOM one’s second argument is defined as optional while Node’s is required, so if you leave it off, you get the DOM definition. This seems slightly unfortunate to me, but it seems like people have just been working around it—see #842.

This would be fixed by the [Strict Environments proposal](https://gist.github.com/RyanCavanaugh/702ebd1ca2fc060e58e634b4e30c1c1c).

**Closed** 2021-01-04 00:00 UTC
Labels: Question

**Comment by andrewbranch** [comment] 2021-01-04 18:25
I would add that the best solution is to get @types/node out of your browser compilation if at all possible. You shouldn’t need it for anything actually running in the browser, so maybe you could split your project into multiple configs, one for browser code that has `"types": []` and one for Node code. The feasibility of doing that varies case by case.
