### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#3436] opened 2015-06-09 06:06 UTC
Reported by @kuon in:https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/220

When I use autoformat, the following block get the following indentation:

    toolsElement = h.div({ className: "row-tools" },
        h.button({
            className: "add-node",
            onClick: () => DataController.createNode(this.props.parentId)
        }, "Create new node")
        );

While I expect (Last line should be to the left):

    toolsElement = h.div({ className: "row-tools" },
        h.button({
            className: "add-node",
            onClick: () => DataController.createNode(this.props.parentId)
        }, "Create new node")
    );

Another example:

    return (
        h.div({
            className: "view-node-row",
            style: {
                width: width,
                height: rowHeight
            }
        },
            backgroundElement,
            centerElement,
            toolsElement,
            h.div({ className: "nodes" }, items)
            )
        );

While I expect:

    return (
        h.div({
            className: "view-node-row",
            style: {
                width: width,
                height: rowHeight
            }
        },
        backgroundElement,
        centerElement,
        toolsElement,
        h.div({ className: "nodes" }, items)
        )
    );

PS: I'm doing react without JSX because TypeScript > JSX, but proper indentation is really crucial to readability.

**Comment by wgebczyk** [comment] 2015-06-09 10:40
+1

**Comment by aleksey-bykov** [comment] 2015-06-09 12:55
+1 
https://github.com/Microsoft/TypeScript/issues/871

**Comment by mhegazy** [comment] 2015-07-02 00:17
@SaschaNaz wanna take a look at this one?

**Comment by SaschaNaz** [comment] 2015-07-02 03:29
@mhegazy Sure, interested. I will take a look.

**Comment by SaschaNaz** [comment] 2015-07-04 16:38
I'm not sure about the second example. #3738 currently makes it into:

```typescript
return (
    h.div({
        className: "view-node-row",
        style: {
            width: width,
            height: rowHeight
        }
    },
        backgroundElement,
        centerElement,
        toolsElement,
        h.div({ className: "nodes" }, items)
    )
);
```

and this is in fact what I expect. Is your indentation example generally preferred?

**Comment by kuon** [comment] 2015-07-04 17:47
I think the first argument should be aligned with the other arguments.

Ii could also be something like this:

```javascript
return (
    h.div({
            className: "view-node-row",
            style: {
                width: width,
                height: rowHeight
            }
        },
        backgroundElement,
        centerElement,
        toolsElement,
        h.div({ className: "nodes" }, items)
    )
);
```

Which is even better. And I think it's what JSBeautifier produces.

**Comment by mhegazy** [comment] 2015-07-05 01:39
Yup. I believe backgrondElement should be pushed back one step.

**Comment by SaschaNaz** [comment] 2015-07-05 05:13
The JSBeautifier way looks a bit more complicated. Okay, I'll follow the general preference.

**Comment by kuon** [comment] 2015-07-05 10:56
Perhaps you may introduce some form of configuration, style is quite personal.

**Comment by SaschaNaz** [comment] 2015-07-09 06:17
One question: What do we want in this case?

```typescript
{
    foo(`foo
foo
foo
`, {
            }); // <- this is current indentation that should be fixed, but what do we want?
}
```

**Comment by kuon** [comment] 2015-07-09 08:11
Seems that https://github.com/Microsoft/TypeScript/issues/3673 is a duplicate of this one

**Comment by SaschaNaz** [comment] 2015-07-11 16:59
Two PRs #3738 and #3827 fix this.

**Comment by SaschaNaz** [comment] 2015-07-14 15:58
One more question: Which do we want for variable declaration list?

```typescript
// This is current behavior
var foo = {
    a: 3
},
    bar = 3;
```

```typescript
// Pushed back
var foo = {
    a: 3
},
bar = 3;
```

**Comment by kuon** [comment] 2015-07-14 16:40
I'd say:

```javascript
var foo = {
        a: 3
    },
    bar = 3;
```

**Comment by SaschaNaz** [comment] 2015-07-14 17:00
@kuon JSBeautifier also does so but we have to choose a default behavior. I personally like your push-forward way, if you ask.

**Comment by kuon** [comment] 2015-07-14 17:10
I think the most important thing is to keep the `},` aligned with the next thing.

So either of those:

```javascript
var foo = {
    a: 3
},
bar = 3;

var foo = {
        a: 3
    },
    bar = 3;
```

Just not the current behavior.

Then it's really a matter of style. I like the push-forward better and as JSBeautifier is the closest thing we have to a reference I'd say do the same if possible.

Personally I stopped using variable declaration list for readability, mostly because different formatters have different behaviors and this ensure a "push forward", I simply do:

```javascript
var foo = {
    a: 3
};
var bar = 3;
```

**Comment by SaschaNaz** [comment] 2015-08-09 07:03
#3827 is waiting feedback, if anyone asks ;)

**Comment by vladima** [comment] 2015-11-30 17:38
closing this issue since it was marked as fixed few months ago

**Closed by vladima** 2015-11-30 17:38 UTC
Labels: Bug, Fixed

**Comment by SaschaNaz** [comment] 2015-11-30 17:41
Not completely fixed, but I think the remaining problem should be posted as a separate issue.

**Comment by vladima** [comment] 2015-11-30 17:51
@SaschaNaz can you please file it it so we can understand what part of work is not finished yet?

**Comment by SaschaNaz** [comment] 2015-11-30 18:42
Okay, I just opened #5834.
