### ISSUE TITLE
TSC remove comments even when removeComments to false

### ISSUE THREAD

**Issue by AlgusDark** [Microsoft/TypeScript#16727] opened 2017-06-24 03:51 UTC
**TypeScript Version:**  2.4.0

**Code**

```ts
var a = /*#__PURE__*/(function () { })()
```

**Expected behavior:**
```javascript
var a = /*#__PURE__*/(function () { })();
```

**Actual behavior:**
```javascript
var a = (function () { })();
```

If I wrote the comment above the declaration, it works, but I need that comment because is going to help me with Uglify to know that this is a pure function with no side-effects.

**Comment by kitsonk** [comment] 2017-06-24 05:50
You mean _does_ remove comments, correct?

The compiler does seem to [erase comments in some surprising ways](http://www.typescriptlang.org/play/#src=var%20%2F*%20foo%20*%2Fa%20%3D%20%2F*%20bar%20*%2F(%2F*%20baz%20*%2Ffunction%20(%2F*%20qat%20*%2F)%20%7B%20%2F*%20qux%20*%2F%20%7D)(%2F*%20quux%20*%2F)%3B).

**Comment by kitsonk** [comment] 2017-06-24 05:54
This sort of seem related to #1665 in that the compiler will erase comments where it thinks the comment is related to some code it is not emitting, but obviously it is getting a but over active in some positions.

**Comment by AlgusDark** [comment] 2017-06-24 06:00
You're right, I edited my question. It's erasing the comments as you mention.

Ohh, I was afraid it was a bug, thanks for pointing that issue.

**Comment by nishantkagrawal** [comment] 2017-07-11 07:54
As per [#3844](https://github.com/Microsoft/TypeScript/issues/3844) using `/*!` should work. But it doesn't work either.

```javascript
this.form['additionalName'].customValidationMessage = /*! i18nextract */ 'Some message';
```
while if the comment is moved to another line, it works.
```javascript
this.form['additionalName'].customValidationMessage =
                /*! i18nextract */ 'Some message';
```

As per @yuit it was fixed, but it seems it is not fixed for all cases.

**Comment by mhegazy** [comment] 2017-08-24 00:21
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/17606

**Comment by mhegazy** [comment] 2017-09-07 17:44
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-07 17:44 UTC
Labels: Duplicate

**Comment by benjamin21st** [comment] 2018-04-16 02:12
I think I found one of the "mysterious ways" TSC would ignore the `removeComments: false`, see this example:
http://www.typescriptlang.org/play/#src=let%20stuff%20%3D%20%5B%0A%20%20%20%201%2C%0A%20%20%20%202%2C%0A%20%20%20%20%2F%2F%203%2C%0A%20%20%20%20%2F%2F%204%0A%5D

In case the link expires, here is the code:

```
let stuff = [
    1,
    2,
    // 3,
    // 4
]
``` 
The commented out lines `3` and `4` will be removed. But if one removes the trailing comma next to 2, the two lines will be preserved. 

Not sure if this is a feature or bug -__-

**Comment by hckrmoon** [comment] 2018-04-18 09:58
For React with typescript user, adding `'removeComments': false` to `ts-loader` options is working rather than adding `'removeComments': false` to `tsconfig.json`.
