### ISSUE TITLE
Deconstruct empty array.

### ISSUE THREAD

**Issue by somarlyonks** [Microsoft/TypeScript#27902] opened 2018-10-15 05:46 UTC
Maybe not `[...Array(n)]` should not be compiled to `Array(n).slice()` ?

The former is `[undefined * n]` yet the later is `[empty * n]`. The key difference is that the former is iterable.

`[...Array(5)].map(_ => 1)` produces `[1, 1, 1, 1, 1]` while `Array(5).slice().map(_ => 1)` produces `[empty * 5]` which remains uniterable.

I know I can fill it like `Array(5).fill(1)`, but I think the situation above is still a bug.

**Code**

```ts
[...Array(5)].map(_ => 1)
```

**Expected behavior:**
[1, 1, 1, 1, 1]

**Actual behavior:**
[empty * 5]

[@PG](https://www.typescriptlang.org/play/index.html#src=console.log(%5B...Array(5)%5D.map(_%20%3D%3E%201))%3B%0D%0A)

**Comment by DanielRosenwasser** [comment] 2018-10-15 07:48
Looks like a duplicate of #8856.

**Closed** 2018-10-15 08:03 UTC
Labels: Duplicate
