### ISSUE TITLE
Object is possibly 'undefined'. When a key of the interface is optional. 

### ISSUE THREAD

**Issue by ndr47** [microsoft/TypeScript#41443] opened 2020-11-08 17:09 UTC
Why the compiler complain in this case? 
The problem is that the `_id` is optional. If I remove the optional `?` it compiles with no issue.

But the object ` user_keys[k]` is not `undefined` because I am looping on arrays of a different object of type User.
Also if I use a type guard it still complain.

**TypeScript Version:**  4.0.5

**Search Terms:**
Object is possibly 'undefined'.
Error 2532

**Expected behavior:**
It should compile.

**Actual behavior:**
Error 2532 -> Object is possibly 'undefined'.

**Code**
```ts
interface User {
	_id?:string
	email:string;
}

type ModelKeys<T> = {
	[P in keyof T]: Array<'unique' | 'readonly'>;
}

const user_keys:ModelKeys<User> = {
	_id: ['unique'],
	email: ['unique', 'readonly'],
};

let k:keyof ModelKeys<User>;
for(k in user_keys){
	for(const type of user_keys[k]){
                                   // ~~ --> Object is possibly 'undefined'.
		console.log(type)
	}
}

for(k in user_keys){
	if(typeof user_keys[k] !== typeof undefined)
		for(const type of user_keys[k]){
                                           // ~~ --> Object is possibly 'undefined'.
			console.log(type)
		}
}

for(k in user_keys){
	if(Array.isArray(user_keys[k]))
		for(const type of user_keys[k]){
                                           // ~~ --> Object is possibly 'undefined'.
			console.log(type)
		}
}

for(const [k,v] of Object.entries(user_keys)){
	console.log(k);
	for(const type of v){
                                   // ~~ --> Object is possibly 'undefined'.
		console.log(type);
	}
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const user_keys = {
    _id: ['unique'],
    email: ['unique', 'readonly'],
};
let k;
for (k in user_keys) {
    for (const type of user_keys[k]) {
        console.log(type);
    }
}
for (k in user_keys) {
    if (typeof user_keys[k] !== typeof undefined)
        for (const type of user_keys[k]) {
            console.log(type);
        }
}
for (k in user_keys) {
    if (Array.isArray(user_keys[k]))
        for (const type of user_keys[k]) {
            console.log(type);
        }
}
for (const [k, v] of Object.entries(user_keys)) {
    console.log(k);
    for (const type of v) {
        console.log(type);
    }
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgKoGdrIN4CgCQA+sACYD8AXOmFKAOYEQC2cwANlTfQNy4C+uXGACeABxQBZAPYkIbANIRh6ADwAVAHzIAvDgIBtAArJQyANZKpMZGoC6FZAEEoUOMJUByAK4hgARy8ID2QAH2QPKAg4EikQNmEPDV4BXARY6mQvTChCC2UKaVkFJVUMaC1dPCJSB31vXwCg2wAaRhZ2Wvr-QI9m8Mjo2PiPFv5eXDYIMHMKPKtkQrlFZRUyqCTcGCkoAAozExBM7NySgEoqrd20kAyRcWR5rOgT5X0zW3OCfGv0KUmAOjYUjoOzuEFOBAEKUuewOR2eeXQn3wwBgoLEEEex0Rb1syAAhNpdGDHiBZDBQBASBD8PgYT9pmCHtYnjkce9kbSfn8IIDgejxDT8FDBDD9qZWS8kVVUTtnK5hP9gOh5W4dpL2R8hfT0oyMcz4WySrjOd90jy+SCwUKRZttjsGcg3s0AG54+YAeQARgArCAIMD-CDgWgQdDq7FnZHcgFAkFmU68On2x1M+Yuzkx3lxgXgpNQoA)

**Comment by MartinJohns** [comment] 2020-11-08 17:11
Duplicate of #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.

**Comment by ndr47** [comment] 2020-11-08 17:12
What is the solution?

**Comment by MartinJohns** [comment] 2020-11-08 17:20
Store the value in a local variable, narrow the local variable.

**Closed** 2020-11-12 18:00 UTC
Labels: Duplicate
