### ISSUE TITLE
Methods of classes extended in others do not inherit the types of method arguments.

### ISSUE THREAD

**Issue by DMVMarcio** [microsoft/TypeScript#58611] opened 2024-05-22 03:11 UTC
### Acknowledgement

- [x] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

TypeScript Version: 5.3.3

When extending a class and overriding a method in the new class, it does not inherit the types of the original method, however, it forces you to maintain the same arguments, the same types, async and the same return, making it necessary to re-write the typing.

If something is required to be exactly the same thing, both arguments and return, shouldn't it automatically inherit the types?

**Example:**
```ts
interface Data {
	id: string;
	name: string;
}```

```ts
class Test1 {
	exec(data: Data) {
		console.log(data.id);
	}
}

class Test2 extends Test1 {
    exec(data) { // data: any
        console.log(data.name);
    }
}

class Test2 extends Test1 {
	constructor() {
        super();
    }

    exec = (data) => {} // data: any
}

class Test2 extends Test1 {
	exec(data: number) {} // Property 'exec' in type 'Test2' is not assignable to the same property in base type 'Test1'.
}
```

**Works:**
```ts
class Test2 extends Test1 {
	constructor() {
        super();

        this.exec = (data) => {} // data: Data
    }
}```

**Comment by fatcerberus** [comment] 2024-05-22 03:38
Duplicate of https://github.com/microsoft/TypeScript/issues/32082 and/or other issues linked therein.
See also: https://github.com/microsoft/TypeScript/issues/36165.

**Comment by DMVMarcio** [comment] 2024-05-22 11:51
This "solved" the problem, however, this still leaves the need to add some unnecessary typing.

**Comment by fatcerberus** [comment] 2024-05-22 14:48
> This "solved" the problem

I'm not sure what you're referring to; I was just pointing out other issues requesting the same or similar features.  This indeed isn't possible today.

**Closed** 2024-05-25 01:28 UTC
Labels: Duplicate
