### ISSUE TITLE
tuple type don't check number of elements

### ISSUE THREAD

**Issue by co-dh** [Microsoft/TypeScript#5259] opened 2015-10-14 22:03 UTC
The following compiles, 
```ts
    var foo:[string, string] = ['','', '', '']
```
while this one not:
```ts
    var foo:[string, string] = ['','', '', 1]
```
The first one should not compiles, since the initializer has 3 elements while the type says 2.

**Comment by sandersn** [comment] 2015-10-14 22:31
Tuples are basically objects with numeric properties. So `foo: [string, string]` is like saying `foo: {0: string, 1: string}`. The value you assign to `foo` has an extra property '2', but that's OK in Typescript.

The second doesn't compile for a different reason, which is just that the array `['', '', '', 1]` is typed as `(number | string)[]`, and `number` is not compatible with any of the types in `[string, string]` -- even though the number doesn't occur until the third element.

The first reason basically makes sense to me, although it would be nice if Typescript had better checking here.

The second reason is a side effect of using arrays to represent tuples, and is a bit unfortunate. For example, this doesn't compile either:

```ts
var bar: (number | string)[] = [1, 2, ''];
var foo: [number, number, string] = bar; // (number | string)[] is not assignable to [number, number, string]

var baz: [number, number, string] = [1, 2, '']; // OK!
```

**Comment by seanfreiburg** [comment] 2015-10-16 03:17
Second doesn't compile because 1 isn't a string. You gave it a type of [string,string].

**Comment by sandersn** [comment] 2015-10-16 15:19
According to the spec, the type [number, string] is equivalent to an interface that extends Array:

    interface NSPair extends Array<number | string> { 0: number, 1: string }

The unfortunate side effect of this is that extra elements in a tuple assignment are ignored, but only if they are of a type that is already present in the tuple. That's because `[1, "foo", 2]: (number | string)[]`, which `NSPair` extends, but `[1, "foo", false]: (number | string | boolean)[]`, which it does not. 

I think this is a bug in the spec, but I'm not at all sure how to fix it. Maybe an ad-hoc rule that says the lengths have to match, or maybe there's an existing way to fix it in the language.

**Comment by JsonFreeman** [comment] 2015-12-03 10:05
Tuples are already quite unsafe because you can do the following:
```ts
var tuple: [number, string] = [0, ""];
for (var i in tuple) {
    tuple[i] = ""; // Succeeds because string is assignable to number | string
}
tuple[0]; // type is number, but should be string
```
I think the goal of giving the user the right type needs to be relaxed for tuples, relative to other parts of the language. On the one hand, there are no restrictions on what users can do with tuples, but on the other hand, users may make strong assumptions about what the tuple will contain at each index (that's what makes it a tuple). This disconnect between expectation and reality should probably be addressed more broadly if any changes to the type checking rules for tuples are considered.

**Comment by ahejlsberg** [comment] 2015-12-08 23:32
This isn't a bug, it is working as designed. Our view is that tuple is an array for which we have static knowledge of the individual types of the first N elements and for which the element type is the union of the types of those N elements. We allow more than N elements to be present (since there's really not much we can do to prohibit it), but we do require those elements to have a compatible type.

**Closed** 2015-12-08 23:32 UTC
Labels: Bug, By Design

**Comment by mortb** [comment] 2016-06-28 08:33
Must say I feel a bit sad about this.

I felt a bit excited when I read about tuples in the typescript handbook:
https://www.typescriptlang.org/docs/handbook/basic-types.html#tuple
When realizing that there is no checking on the number of array elements the tuple feature doesn't seem as attractive as it did in my first impression. (This non existent length check is not mentioned in the typescript handbook)

I was expecting something to use like C# tuples: (https://github.com/dotnet/roslyn/issues/347)
Oh well...

**Comment by aboglioli** [comment] 2017-04-04 20:47
Tuples should have a fixed size or number of elements. That's a property:
[Properties of tuples](https://en.wikipedia.org/wiki/Tuple#Properties)

**Comment by RyanCavanaugh** [comment] 2017-04-04 20:48
Identical is not the same as subtype.

**Comment by whitecolor** [comment] 2017-04-07 22:08
So there is no way any way to fixate number of elements of the tuple or list in typing? To me this is a big con.

**Comment by RyanCavanaugh** [comment] 2017-04-07 22:35
```ts
type fixed = [number, number] & { 2: void };
// Error
var x: fixed = [3, 3, 3];
```

**Comment by whitecolor** [comment] 2017-04-07 22:43
but it doesn't work with 2 either:
```ts
type fixed = [number, number] & { 2: void };
// Error
var x: fixed = [3, 3];
```

> Type '[number, number]' is not assignable to type 'fixed'.
  Type '[number, number]' is not assignable to type '{ 2: void; }'.
    Property '2' is missing in type '[number, number]'.

**Comment by RyanCavanaugh** [comment] 2017-04-07 22:43
Sorry
```ts
type fixed = [number, number] & { 2?: void };
// Error
var x: fixed = [3, 3, 3];
// OK
var y: fixed = [3, 3];
```

**Comment by whitecolor** [comment] 2017-04-07 22:47
@RyanCavanaugh cool, thank you!

**Comment by RyanCavanaugh** [comment] 2017-04-07 23:00
That's worked for as long as intersection types (or tuples? whichever came first) have existed

**Comment by arnauorriols** [comment] 2017-11-16 01:18
> This isn't a bug, it is working as designed. Our view is that tuple is an array for which we have static knowledge of the individual types of the first N elements and for which the element type is the union of the types of those N elements. We allow more than N elements to be present (since there's really not much we can do to prohibit it), but we do require those elements to have a compatible type.

This is the boldest "it's not a bug, it's a feature" case I've seen in years. Respect. 

> We allow more than N elements to be present (since there's really not much we can do to prohibit it), but we do require those elements to have a compatible type.

Maybe it's not simple to prohibit the number of items a tuple contains, but what about reading the tuple? Could be prohibited using an index larger than the tuple size?

```typescript
const t: [number, number] = [1, 2, 3];  // Works, apparently not possible to prohibit consistently
t[1];  // works
t[2];  // Error, [number, number] only has 2 elements
`

**Comment by RyanCavanaugh** [comment] 2017-11-17 21:55
@arnauorriols see #17765
