### ISSUE TITLE
node_modules in parent directories are ignored

### ISSUE THREAD

**Issue by kenotron** [Microsoft/TypeScript#5381] opened 2015-10-23 17:16 UTC
For an example, given a Foo and Bar project laid out like this:

```
Foo/
  node_modules/
    Bar/...
  src/
    a.ts
  dist/
    a.js
    a.d.ts

Bar/
  node_modules/
  src/
    b.ts
  dist/
    b.js
    b.d.ts
```

Whereas Foo depends on Bar. and Bar is already npm linked as above, if I had a.ts referencing something from b.ts like this:

```js
import * as b from 'Bar/dist/b';
```

It would NOT find it. This works fine if b.ts and a.ts were one level up, so it's next to node_modules.

**Comment by vladima** [comment] 2015-10-23 17:30
I was able to repro it, this is dupe of #5102 and is fixed in #5275

**Closed by vladima** 2015-10-23 17:30 UTC
Labels: Bug, Duplicate
