### ISSUE TITLE
ES6 Promise initialiser scope should be treated like block scope

### ISSUE THREAD

**Issue by cefn** [microsoft/TypeScript#42910] opened 2021-02-21 22:38 UTC
# Suggestion

## 🔍 Search Terms

Promise closure undefined ignored resolve

## ✅ Viability Checklist

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I would like to see assignments made within the Promise 'constructor' to be known to be set, just like any block-scoped inlined code.

```
function doTidyUp(){}

let myfun;
const myPromise = new Promise((resolve) => {
    myfun = () => {
        doTidyUp();
        resolve;
    }
})

const storedMyFun:Function = myfun;
```

In the above example, of course if it were any other reference, we wouldn't know if the scope of the Promise initialiser had ever been executed. For this reason the assignment of `myFun` to `storedMyFun` is a compiler error. However, if it's the ES6 Promise reference, we can know that the function has been called, and myfun in the outer closure has been set before the attempted assignment to storedMyFun. 

## 📃 Motivating Example

I've had to work around this when negotiating access between two separate processes, e.g. for locks and queues. A routine strategy is to create a Promise and then hand the resolve function (or a wrapper of resolve) to the requester, so that they can fulfil the promise. For example a release() callback returned by lock.acquire() can call resolve on a 'release promise'. This requires a variable in the outer closure, set by the Promise initialiser (since Promise deferment is no longer a thing :).

## 💻 Use Cases

As a workaround I've relied on my knowledge of asynchronous code primitives to force the issue with a `!`, but this may not be attempted by others who are genuinely unsure when the initialisation function gets run, and may genuinely think it's an error. Having it treated as its own block scope executed immediately within the closure would eliminate this issue...

```
let myfun!:() => void;
const myPromise = new Promise((resolve) => {
    myfun = () => {
        doTidyUp();
        resolve;
    }
})
```

**Comment by MartinJohns** [comment] 2021-02-21 22:47
#9998

**Comment by ExE-Boss** [comment] 2021-02-22 14:33
Duplicate of <https://github.com/microsoft/TypeScript/issues/11498>

**Comment by cefn** [comment] 2021-02-24 00:14
Thanks, all. I needed the keywords 'immediately invoked' to find these.

**Closed** 2021-02-26 18:00 UTC
Labels: Duplicate
