### ISSUE TITLE
tsc tell me "This condition will always return 'false'", but that doesn't seem to be the case.

### ISSUE THREAD

**Issue by benishouga** [microsoft/TypeScript#43979] opened 2021-05-06 12:02 UTC
# Bug Report

### 🔎 Search Terms

This condition will always return 'false' since the types _ and _' have no overlap.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about this error.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3&ssl=1&ssc=1&pln=6&pc=1#code/DYUwLgBAxgrgTnEA7MAuCAiAghiAfTAIVwF5McBuAKCgHskBnSKACwEMkBzECMgCiQgAHmnK4CGYgEpeAPgh9YCZJDKCRU6gDNacBaEgBLXhAAMFCMYA8EAMwXDAakcyA3lQjR2XEIviIUXhIySVwAfjEIdFDNKgBfKiA)

### 💻 Code

```ts
let current: "A" | "B" = "A";
const change = (next: "A" | "B") => (current = next);
for (let i = 0; i < 3; i++) {
  change(current === "B" ? "A" : "B"); // This condition will always return 'false' since the types '"A"' and '"B"' have no overlap.ts(2367)

}
```

### 🙁 Actual behavior
The compilation fails and the following error is output.
```
TSError: ⨯ Unable to compile TypeScript:
src/hoge.ts:4:10 - error TS2367: This condition will always return 'false' since the types '"A"' and '"B"' have no overlap.
```

### 🙂 Expected behavior
I want to compile successfully.

**Comment by MartinJohns** [comment] 2021-05-06 12:39
Duplicate of #9998.

**Comment by nmain** [comment] 2021-05-06 12:49
Also see https://github.com/microsoft/TypeScript/issues/8513.

**Closed** 2021-05-08 18:00 UTC
Labels: Duplicate
