### ISSUE TITLE
Infrastructure: internal declarations added to tsserverlibrary.d.ts

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#25440] opened 2018-07-04 18:58 UTC
I noticed this in https://github.com/Microsoft/TypeScript/pull/25439#pullrequestreview-134455964 after adding a function to an `@internal` namespace. The baseline changed so that means these declarations are also published to npm.

**Comment by mhegazy** [comment] 2018-07-05 18:08
Duplicate of https://github.com/Microsoft/TypeScript/issues/24966

**Closed** 2018-07-05 18:36 UTC
Labels: Duplicate
