### ISSUE TITLE
Spread syntax ignores generic type constraints

### ISSUE THREAD

**Issue by toolness** [microsoft/TypeScript#46146] opened 2021-09-30 15:55 UTC
# Bug Report

### 🔎 Search Terms

`typescript extends spread`

Through this I found #26412, which may be related to this, but I can't quite tell, in part because a code example that it claims raises a compile error in TS 3.0 no longer raises a compile error in 4.4.3.  There appear to be a number of bugs related to that, but as far as I can tell, none of them match the particular problem I'm having.  I might have missed one, though, in which case I apologize.

### 🕗 Version & Regression Information

4.4.3. Also happens in 4.5.0-dev.20210930 (see playground link below).

This is the behavior in every version I tried, and I reviewed the FAQ for entries containing the word `extends` and `spread`.

### ⏯ Playground Link

[Here is a Playground link.](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210930#code/C4TwDgpgBAKgFgSwHYHMoF4oG8BQUpwQA2RA9gFxRICuAtgEYQBOA2gLoDcOAvjjgGbUkAY2AJSSKKUhMAhsAgB5JPGQoAaglkBBAM66EKJLQhJgAHhhQIADwVIAJrtiJUAPgAUwVykowAlH7YeFDCErrAVBAA7qqoGNhQAHQp3mpQ3Fz4APTZUAASzNDR0LJMpfqGSOmyUBFM6cgRELIOUvxUdIysbFDApH2EUABEhCSkw1BgTNLMoAA0IblQso6wAMpQcgi6EM61YbRgCETQzDNMK862kKIQDkkhSDFxKEljZAmjCMNZWxDAahMSTPWI+Li8ARCUTiSSzOQKZSvTSydbTFoOSzWOymJwuNSeNKoPyBWDBHJ5QrlKAlFbU2SVIw1OrABrxJoKVrtToMZjsPoDbzQUbEMiTabwhZLPL0aiRGCbBykPZIADkkUOYCIsmQj3w5UBwMSKSSRJQ8wIoooI0Qk0yPBwQA)

### 💻 Code

```ts
type Thing = {
  hello: number[];
}

function operateOnThingViaSpreadThenAssignment<T extends Thing>(thing: T): T {
  const newThing = { ...thing };
  // Here we are assigning a string instead of number[] to the "hello" property,
  // and TS raises a compile error as expected.
  newThing.hello = "hi";
  return newThing;
}

function operateOnThingViaSpreadOnly<T extends Thing>(thing: T): T {
  // Here we are assigning a string instead of number[] to the "hello" property,
  // but TS doesn't complain.
  return { ...thing, hello: "hi" };
}
```

### 🙁 Actual behavior

TypeScript appears to treat the two functions differently, correctly raising a compilation error for `operateOnThingViaSpreadThenAssignment()` while curiously being fine with `operateOnThingViaSpreadOnly()`.

The latter seems particularly bad because, as far as I can tell, it's effectively not reporting something that is actually a type error.

### 🙂 Expected behavior

I expect TypeScript to raise the same error--or at least, something very similar, along the lines of `Type 'string' is not assignable to type 'number[]'`--for both functions.

**Comment by jcalz** [comment] 2021-09-30 16:24
There’s a bug report template you’re supposed to fill out when you open an issue here. Could you edit your post and provide all the required information?  This includes search terms you presumably used when looking for existing issues on the same topic before opening a new one. Thanks!

**Comment by toolness** [comment] 2021-09-30 21:53
Oops, sorry about that!  Just updated the post.

**Comment by MartinJohns** [comment] 2021-10-01 04:28
Duplicate of #42690. Used search terms: `generic spread in:title`

**Closed** 2021-10-07 18:00 UTC
Labels: Duplicate
