### ISSUE TITLE
Refactoring does not work with Mapped Types

### ISSUE THREAD

**Issue by normalser** [Microsoft/TypeScript#13329] opened 2017-01-06 21:24 UTC
```ts
interface State {
    test: string
}

type PartialState = Partial<State>

const foo: State = {
    test: 'a'
}
const bar: PartialState = {
    test: 'a'
}
```

Renaming `test` of `State` interface will not rename the `test` member of `bar`.
It would be very useful when working with React

**Comment by sandersn** [comment] 2017-01-26 20:20
This is a duplicate of #13690 -- the mechanism for find-all-refs should be the same as rename. 

Note that @andy-ms already fixed renaming `test: string` inside `interface State`, but it still doesn't work to rename a reference, eg `foo.test/*rename-here*/`

**Closed by sandersn** 2017-01-26 20:20 UTC
Labels: Bug
