### ISSUE TITLE
Intersection with type parameter doesn't subtract properties

### ISSUE THREAD

**Issue by smoogly** [Microsoft/TypeScript#20536] opened 2017-12-07 14:25 UTC
**TypeScript Version:**  2.6.1 && 2.7.0-dev.20171207

**Code**

```ts
interface InternalProps {
    a: number;
}
interface ExternalProps {
    b: string;
}

function make<T = {}>(arg: T & InternalProps): T & ExternalProps {
    return 1 as any;
}

const x = make<{}>({a: 1});
console.log(x.a); // Correct: type error

const y = make({a: 1});
console.log(y.a); // Incorrect: no type error
```

**Expected behavior:**
Property `a` should not be expected to exist on `y`.
Both examples should fail.

**Actual behavior:**
Only first example is considered a type error.

**Comment by andy-ms** [comment] 2017-12-07 15:10
Looks like a duplicate of #20505.

**Comment by smoogly** [comment] 2017-12-07 15:18
I'm not sure, but I don't think it's a duplicate.
In this case looks like `T` is inferred to be `InternalProps`, which is unexpected:

```ts
interface InternalProps {
    a: number;
}
interface ExternalProps {
    b: string;
}

function make<T = {}>(arg: T & InternalProps): T & ExternalProps {
    return 1 as any as T & ExternalProps;
}

const x = make<{}>({a: 1});
console.log(x.a); // Correct: type error
console.log(x.blah); // Correct: type error

const y = make({a: 1});
console.log(y.a); // Incorrect: no type error
console.log(y.blah); // Correct: type error
```

```
./node_modules/.bin/tsc test.ts                                                                            
test.ts(13,15): error TS2339: Property 'a' does not exist on type 'ExternalProps'.
test.ts(14,15): error TS2339: Property 'blah' does not exist on type 'ExternalProps'.
test.ts(18,15): error TS2339: Property 'blah' does not exist on type '{ a: number; } & ExternalProps'.
```

**Comment by andy-ms** [comment] 2017-12-07 15:33
The thing they have in common is that adding a default to a function's type parameter doesn't turn off type inference. So if a type can be inferred, that type will be used instead of the default.

But in this case I see that `T` could be inferred as `{}` since the input is `T & InternalProps` and `InternalProps` can handle the `a` property. One alternative to subtraction types (#4183) that I've heard discussed in the past I think looked something like this:
```ts
declare function removeA<T>(arg: T & { a: any }): T;
const o = removeA({a: 1});
o.a; // Should be an error?
```

**Comment by smoogly** [comment] 2017-12-07 15:50
@andy-ms, yes if the example you show was implemented,
my scenario would produce the results I expect as well.

**Comment by mhegazy** [comment] 2018-01-31 19:20
The compiler can not make these assumptions that the property exclusively exists in one constituent of the intersection.. i.e.  `T & { a: number }` does not guarantee that `T` itself does not have a property `"a"` with the same type or a different one. I think what you need is `Diff` (https://github.com/Microsoft/TypeScript/issues/19569).

**Closed** 2018-02-15 17:55 UTC
Labels: Working as Intended
