### ISSUE TITLE
Bug: `a instanceof b === false` doesn't influence type flow

### ISSUE THREAD

**Issue by jeengbe** [microsoft/TypeScript#53093] opened 2023-03-04 12:53 UTC
# Bug Report

### 🔎 Search Terms

instanceof explicit false if type narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about **Common bugs that aren't bugs**
- I was able to reproduce this on versions `5.1.0-dev.20230304`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230304#code/CYUwxgNghgTiAEYD2A7AzgF3gDwFzwFcUBrFJAdxQG4BYAKFElgWXSwE98oV3a76AFAEp4AXgB88AN714c+AEsAZgIHZFbbmBBIl8AKIwYSGGNGj4SqBDQghIuBgIxq9WfPnY+HgPQ-4AHoA-O5yfvAAygAWSAQQwPAARggA5IbGMCn0AL5udMJikjJ0HsoCAIRqGphaOnrpJvbwjs6u-CUecl6h8OHBOXkFEtI9ZezVGLW6BkYmZhZWNnbNIE4ufD3yvD19IR1h-tGx8UmpDZkD7UNFoyqV4wqaKNrT500t63mdctv7vf79OjZIA)

### 💻 Code

```ts
declare const x: unknown;

() => {
    if(x instanceof Error === false) return;

       x;
    // ^?
    // Should be 'Error', is 'unknown'
}

() => {
    if(!(x instanceof Error)) return;

       x;
    // ^?
    // Is correctly 'Error'
}
```

### 🙁 Actual behavior

The semantically equivalent expressions `(x instanceof Error === false)` and `!(x instanceof Error)` influence type flow (correct term?) differently.

### 🙂 Expected behavior

`(x instanceof Error === false)` should function the same way `!(x instanceof Error)` does.

**Comment by jcalz** [comment] 2023-03-04 13:07
Duplicate of #31105  and #9508 (is this a bug or a won’t fix?)

**Comment by jeengbe** [comment] 2023-03-04 13:10
a won't fix

**Closed** 2023-03-04 13:09 UTC
