### ISSUE TITLE
Extra generic parameters incorrectly make generic types compatible

### ISSUE THREAD

**Issue by cutthroat** [microsoft/TypeScript#41553] opened 2020-11-16 15:50 UTC
**TypeScript Version:**  4.0.5

**Search Terms:**
generic, incorrect, assignable, multiple, multi, two, parameter, compatible, unsound, unsafe

**Expected behavior:**
The type `NotOk<number, number>` below should not be assignable to `NotOk<string, string>`

**Actual behavior:**
It is.

**Code**
```ts
// Ok

interface I1<X> {
  m1: Ok<X>;
}

class Ok<X> {
  constructor(public x: X) {}

  fOk(i1: I1<X>) { i1 = i1; }
}

// !!! Fails to type-check as expected
const ok: Ok<string> = new Ok(0);


// Not ok

interface I2<X, Y> {
  m2: NotOk<X, Y>;
}

class NotOk<X, Y> {
  constructor(public x: X) {}

  fNotOk(i2: I2<X, Y>) { i2 = i2; }
}

// !!! Type-checks but should not
const notOk: NotOk<string, string> = new NotOk(0);
```

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/PTAEHkGsChoSwHYBcCmAnAZgQwMYtAJICMAPABoB8oA3tKKALZEBcEk5FA3NAL6w4AbLAGdhbDjTqgcAewTCkaAK44kMtAAoADkoBGAuDlAAPVmQCUNPlIxQNcFoVKVL1UA9ABed0U6g+1iCgAIShoABiWHACYmqgSACeWigAtDgAFig4kKAioCjGyaooACbQsvJIoDKQrFAkCmiIAOZU3ggoAO5sGgAM5tywQQByMlU1sIiomLj4BABM5AA0oACaVLT0DPOso0j1ZCvr3NaCImJ7B0cbUhWNKmqaOvqGJmau1vQYl5D2O4SLQ5rCiudzzLxgvwBIZgULBUAAFSSqQyWUgYl0SiqwnSMiUAhKoAQY3KcgURLGUF2lPYjRaKzpCFaEI63R+fQGQA)

**Related Issues:**
Somewhat related: #30634,  #31006

**Extra:**
The interface `I2` is needed for when inlined the type-checker [fails correctly](https://www.typescriptlang.org/play?#code/MYGwhgzhAEByD2B3A8gawDwA0A00CaAfNAN4BQ00w8AdhAC4BOArsHfAwBQAOTARiAEtg0AB4AuaJgCUJAL6ly0AGYIUqDgIBME4tAC22uEjRZchANzRZM3VugBeaFsvz5pAPTvoAMTACQMGzQdACeXACmALTAABbhwKjQkNDhIhGs4QAmpFS0dNDUxqgSqib0DALUAOa45ZVVRI7U4YhGahwADFLmQA):
```ts
class NowOk<X, Y> {
  constructor(public x: X) {}

  fNowOk(i2: { m2: NowOk<X, Y>; }) { i2 = i2; }
}

// Fails to type-check as expected
const nowOk: NowOk<string, string> = new NowOk(0);
```
However, this behavior could simply be due to a limitation of the unification mechanism used by the type checker.

**Comment by MartinJohns** [comment] 2020-11-16 16:46
Working as intended. You're not using `Y` anywhere.

[What is structural typing?](https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-structural-typing)  
[Why is `A<string>` assignable to `A<number>` for `interface A<T> { }`?](https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-structural-typing)

**Comment by cutthroat** [comment] 2020-11-16 17:14
I believe Y is not needed to cause a structural difference since the class `NotOk` already contains the field `x: X`, and instantiating it with say `X = number` and `X = string` should be a structural difference.  Isn't this the reason why the `ok` assignment above fails to type-check?

In any case, adding a field of type Y to `NotOk` (which I believe qualifies as an use) [still type-checks](https://www.typescriptlang.org/play?ssl=14&ssc=57&pln=1&pc=1#code/PTAEDkHsBdUhrAUIglgO2gUwE4DMCGAxpqAJIBMAPABoA0oAmgHygDeiooAtuQFwQwA8vCp1GTANyIAvskIAbfAGclA6MNH1mbDqEKQ0S6NgCuhaJGwAKAA4mARvJSFQAD35i7j56ACe-BgBKNlldXCh1ESsUPjJNcWDWUBjQAF5k8glQWVCQUABCQtAAFV8bTABaQgALTEJ4VXsTWCVqyBN5ABNQNBhEfUNYXsjYiI1KI2x0AHN6SZmWdLRMAHc1DSsABnpNwIkgA):

```ts
// Not ok

interface I2<X, Y> {
  m2: NotOk2<X, Y>;
}

class NotOk2<X, Y> {
  constructor(public x: X, public y: Y) {}

  fNotOk2(i2: I2<X, Y>) { i2 = i2; }
}

// !!! Type-checks but should not
const notOk2: NotOk2<string, string> = new NotOk2(0, 0);
```

Because `NotOk` and `NotOk2` type-check, I can cast, e.g., a number to a string:

```ts
// !!! Type-checks but should not
const notOk: NotOk<string, string> = new NotOk(0);

// !!! undefined
console.log(notOk.x.length);
```

**Comment by MartinJohns** [comment] 2020-11-16 17:30
You're right, I misread the code. This really seems strange.

    const val1 = new NotOk<number, string>(0);
    const val2: NotOk<string, string> = val1;
    val1.x // number
    val2.x // string

Interestingly the error shows up when you remove the `fNotOk2` method.

**Comment by cutthroat** [comment] 2020-11-16 17:49
Yes, `fNotOk2` seems to be essential, as well as the interface `I2`.  `NotOk` is the simplest example I could get.

**Comment by RyanCavanaugh** [comment] 2020-11-16 18:53
See https://github.com/microsoft/TypeScript/issues/39947 - this is fixed in the nightly build

**Closed** 2020-11-16 19:18 UTC
Labels: Duplicate
