### ISSUE TITLE
Enum literals assignments are inferred differently than what is emitted in .d.ts.

### ISSUE THREAD

**Issue by rkirov** [Microsoft/TypeScript#25990] opened 2018-07-26 22:33 UTC
**TypeScript Version:**  3.1.0-dev.20180726

**Search Terms:**

enum literals declarations 

**Code**

```ts
enum E {
  A = 'a',
  B = 'b'
}

class C {
  readonly type = E.A;
}

let x: E.A = new C().type; // no error, type is inferred to E.A, not E.
```

**Expected behavior:**
I expect similarly the .d.ts emitted to have a narrowed declaration for 'type'

```typescript
declare class C {
    readonly type: E.A;
}
```

**Actual behavior:**
Emitted .d.ts contains:
```typescript
declare class C {
    readonly type: E;
}
```

Note this is critical for creating tagged unions for type narrowing, and this behavior makes type narrowing only work when one is not crossing a '.d.ts' boundary. Bazel compliations usually look like 2-3 .ts files and hundreds to thousands .d.ts files from downstream compilations.

**Related Issues:**

**Comment by mhegazy** [comment] 2018-07-26 23:17
Duplicate of https://github.com/Microsoft/TypeScript/issues/15881

**Comment by rkirov** [comment] 2018-08-10 01:57
Thanks for picking the up. We are seeing a lot of code using this pattern because it is what ngrx (redux for angular) is recommending - https://github.com/ngrx/platform/blob/master/docs/store/actions.md#typed-actions

**Closed** 2018-09-07 19:09 UTC
Labels: Bug, Domain: Declaration Emit
