### ISSUE TITLE
No completion builder present before any word

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6327] opened 2016-01-02 23:31 UTC
```ts
// 1. input `w,`
w
window,
// 2. input `window`, move caret to line head by using arrow key, input `!`
window
window!window
```

**Comment by DanielRosenwasser** [comment] 2016-01-04 05:38
I think this might be a duplicate of #3700.

**Comment by DanielRosenwasser** [comment] 2016-01-04 05:40
Actually, I realized that only part of this issue is a duplicate of #3700. The fact that there's no builder there is by design, since in all practically, what could be declaring in those positions? The only thing you could be writing as a declaration would be a lambda.

**Closed** 2016-01-04 05:40 UTC
Labels: By Design
