### ISSUE TITLE
Broken output of --module system

### ISSUE THREAD

**Issue by chuntaro** [Microsoft/TypeScript#6996] opened 2016-02-10 11:41 UTC
Can not be run properly because when broken output of --module system.
Version of tsc problems occur 1.7.5 and 1.8.0.

```typescript
// bug.ts
export var test = false;

if (!test) {
  test = false;
}
```

tsc --module system bug.ts

```javascript
// bug.js
System.register([], function(exports_1) {
    var test;
    return {
        setters:[],
        execute: function() {
            exports_1("test", test = false);
            if (exports_1("test", !test)) { // <- broken output
                exports_1("test", test = false); // <- broken output
            }
        }
    }
});
```

**Comment by vladima** [comment] 2016-02-10 15:22
looks like duplicate of #6156.
this is what I see using 1.8 from npm
```
vladima@vladima-W520:~/sources/playground/6996$ ./node_modules/.bin/tsc -version
Version 1.8.0
vladima@vladima-W520:~/sources/playground/6996$ cat t.ts
// bug.ts
export var test = false;

if (!test) {
  test = false;
}
vladima@vladima-W520:~/sources/playground/6996$ ./node_modules/.bin/tsc -m system t.ts
vladima@vladima-W520:~/sources/playground/6996$ cat t.js
System.register([], function(exports_1) {
    "use strict";
    var test;
    return {
        setters:[],
        execute: function() {
            // bug.ts
            exports_1("test", test = false);
            if (!test) {
                exports_1("test", test = false);
            }
        }
    }
});
vladima@vladima-W520:~/sources/playground/6996$ 
``` 

Do I understand you correctly that you still can repro this in 1.8?

**Comment by chuntaro** [comment] 2016-02-10 16:56
Sorry, in 1.8 the bug has been fixed.
However, the following problems even 1.8 will still occur.

```typescript
// bug.ts

export var test = false;

export function print() {
  console.log(test);
}
```

```typescript
// main.ts

import * as bug from './bug';

bug.test = true;

bug.print();
```

$ tsc --module amd main.ts

```html
<!-- bug_module_amd.html -->

<!DOCTYPE html>
<html>
  <head>
    <script data-main="main.js" src="require.js"></script>
  </head>
</html>
```
browser console puts => true

$ tsc --module system main.ts

```html
<!-- bug_module_system.html -->

<!DOCTYPE html>
<html>
  <head>
    <script src="system.js"></script>
    <script>
     System.config({
       defaultJSExtensions: true
     });
     System.import('main.js');
    </script>
  </head>
</html>
```
browser console puts => false ???
Only changed the module format, the result is changed.

**Comment by vladima** [comment] 2016-02-10 18:44
the problem is that `main.ts` is illegal ES6 code: module namespace exotic objects [don't support](https://tc39.github.io/ecma262/#sec-module-namespace-exotic-objects-set-p-v-receiver) `[[Set]]` operation so attempts to set the value on it (`bug.test = true;`) will fail in runtime.
Note: `readonly` support that is currently available in `master` tracks such write operations - this code will error as an attempt to set the value of readonly property

**Closed by vladima** 2016-02-10 18:44 UTC
Labels: Duplicate

**Comment by chuntaro** [comment] 2016-02-11 01:55
Thank you for detailed explanation!
I understand.
In 1.9.0-dev.20160210 now compile error.

$ tsc --module amd main.ts
main.ts (5,1): error TS2450: Left-hand side of assignment expression can not be a constant or a read-only property.
