### ISSUE TITLE
Conditional types with class generics not narrowing properly

### ISSUE THREAD

**Issue by deviprsd** [microsoft/TypeScript#45053] opened 2021-07-15 21:19 UTC
# Bug Report

### 🔎 Search Terms

+ Conditional types not narrowing with class generics

### 🕗 Version & Regression Information
- v4.3.5
- I was unable to test this on prior versions because never needed such a situation

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?strictPropertyInitialization=false#code/PQKhAIBUE8AcFMDO4CGA7AJuAloxBXJcAJ3gBsUAXeLSge3ACN8BzcEYAKErnil7oAzAILFiKaAB5IAPnABeKOHgAPapmSjxU-GgDWaOgHc0cgPxQA2mnwBbRvGIBdcAC4oAbk7de4AOLwaADK1LDSADTgAKoKqGjQkQBqymqBGMgAwvhigZQZdGjUarFZOYX5haqUcooA3pzg4AAUevDQ7q3QQlAAlO4AsiiwCMQR0UkyXo0tbR1t3ZCRpIgA0rPgnd2JfeCDw45jURNT4JIA6inq6RvzguCJMk0NjTft4Gfhz43La28ASkhfockklLGcnDJPi9wAUAMbwMzuSjEQhQ8A7PYjYH3SbPc6XNLITZ3B5PaGddwfL4kQHrAGrNrYxKRGAIIRaCSSRJgiGQ6lw+DuQQoMiIeBoxpDBCYJEo8XPDFSg6LcY4rwAXy8nFhFDw4AAGhkACJMgkacBBOi2eAVIqUWKW622qpyeqNWD4RhkbCw8AsQIheCwdwBYKhJk1ZrUimvLbgAA+sbui2pPzaiKT9wT4HpQJVRxxEvAsGIYoA8rBKIgM7nGfmJtnGHQ6GR4Ogi0rMBmmy222g0Yr9qN6ziFK7qaAIHRKAALRzgWF0DB8Dip+CUbJocC1V5zaCoZCIZHYNBsTXPc-PD1en0LuewvQDIYAMQAchHYk0emPt2uN8Qt1nXAADp-TDIMmgAcgAGX1SDIi-H83WhGl-y3ZCUItAAtdwMJQoIsIABgARncSD4OpaECMIgAmMjIMo8B1XVal1UiYVRXFcBkUIHoL04FjOEnC1sFsWBW34BBkEgBggnwYY6GIe1Zz4XACBXLgeAQcAAAUUFLeBRBYRBJGeSBYnQBJnmSRRLLRGIqkJcBSlIcoCjtEpslcvJ3KqThI2Q4hjHcSATgIRg-mMRB3G5JwTlhLzcncKINS1LS+D0gyKyrWJkM7DBu2bVt0BOAVCt7EqBLS3xMQOMyLPiNEbLiKzGgc1JzRc3JnWKRQurcyo1H83LnhjI9iBPFgTjTaAM3GyaTlgfSxQzJo6EraLdOWwziGMsZmWiGRv3kOQjSoFAy3wSgPUoDVwAAMi2rKNuq7SzsoC6rpurlYl0AxjFMWJ5tPbMbHsedExsMgyGzRJXr4fqfMG+1FABRdiAwSRgZYSJ3s+66rtxHxtNrKQzPshrWqzRzOsSgaPL6umkbtNELkUP7DBMYbFDWjb3EysUjJMkcHmO07zsugnKHOIn0t2F933J54YlsxrrLNa5EZ6lHnKZ7XueaMX5aHCN4agR11xnSaRsaAAve2yPt22KMEuWLe1m3wFg3DqQIn3MOo0jwGxk4qKIujg+PU9Q6Yi9LCcATOCAA)

[Playground link with relevant code nightly](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210715#code/PQKhAIBUE8AcFMDO4CGA7AJuAloxBXJcAJ3gBsUAXeLSge3ACN8BzcEYAKErnil7oAzAILFiKaAB5IAPnABeKOHgAPapmSjxU-GgDWaOgHc0cgPxQA2mnwBbRvGIBdcAC4oAbk7de4AOLwaADK1LDSADTgAKoKqGjQkQBqymqBGMgAwvhigZQZdGjUarFZOYX5haqUcooA3pzg4AAUevDQ7q3QQlAAlO4AsiiwCMQR0UkyXo0tbR1t3ZCRpIgA0rPgnd2JfeCDw45jURNT4JIA6inq6RvzguCJMk0NjTft4Gfhz43La28ASkhfockklLGcnDJPi9wAUAMbwMzuSjEQhQ8A7PYjYH3SbPc6XNLITZ3B5PaGddwfL4kQHrAGrNrYxKRGAIIRaCSSRJgiGQ6lw+DuQQoMiIeBoxpDBCYJEo8XPDFSg6LcY4rwAXy8nFhFDw4AAGhkACJMgkacBBOi2eAVIqUWKW622qpyeqNWD4RhkbCw8AsQIheCwdwBYKhJk1ZrUimvLbgAA+sbui2pPzaiKT9wT4HpQJVRxxEvAsGIYoA8rBKIgM7nGfmJtnGHQ6GR4Ogi0rMBmmy222g0Yr9qN6ziFK7qaAIHRKAALRzgWF0DB8Dip+CUbJocC1V5zaCoZCIZHYNBsTXPc-PD1en0LuewvQDIYAMQAchHYk0emPt2uN8Qt1nXAADp-TDIMmgAcgAGX1SDIi-H83WhGl-y3ZCUItAAtdwMJQoIsIABgARncSD4OpaECMIgAmMjIMo8B1XVal1UiYVRXFcBkUIHoL04FjOEnC1sFsWBW34BBkEgBggnwYY6GIe1Zz4XACBXLgeAQcAAAUUFLeBRBYRBJGeSBYnQBJnmSRRLLRGIqkJcBSlIcoCjtEpslcvJ3KqThI2Q4hjHcSATgIRg-mMRB3G5JwTlhLzcncKINS1LS+D0gyKyrWJkM7DBu2bVt0BOAVCt7EqBLS3xMQOMyLPiNEbLiKzGgc1JzRc3JnWKRQurcyo1H83LnhjI9iBPFgTjTaAM3GyaTlgfSxQzJo6EraLdOWwziGMsZmWiGRv3kOQjSoFAy3wSgPUoDVwAAMi2rKNuq7SzsoC6rpurlYl0AxjFMWJ5tPbMbHsedExsMgyGzRJXr4fqfMG+1FABRdiAwSRgZYSJ3s+66rtxHxtNrKQzPshrWqzRzOsSgaPL6umkbtNELkUP7DBMYbFDWjb3EysUjJMkcHmO07zsugnKHOIn0t2F933J54YlsxrrLNa5EZ6lHnKZ7XueaMX5aHCN4agR11xnSaRsaAAve2yPt22KMEuWLe1m3wFg3DqQIn3MOo0jwGxk4qKIujg+PU9Q6Yi9LCcATOCAA)

### 🙁 Actual behavior
This code doesn't conform to the type expected by the generic even though intellisense is able to understand the return type.
```typescript
return {
        SZ:     {
           SZ01: '',
           SZ02: ''
    }
}
```

![Screen Shot 2021-07-15 at 4 27 11 PM](https://user-images.githubusercontent.com/3809354/125860065-f025359e-bd49-4901-8128-abe363090723.png)
![Screen Shot 2021-07-15 at 4 24 27 PM](https://user-images.githubusercontent.com/3809354/125860173-25231a00-967a-4159-8020-60a69dafcce5.png)

### 🙂 Expected behavior

Shouldn't error out, unless I'm doing something wrong here

**Comment by gabrielurbina** [comment] 2021-07-17 20:43
Not an expert here, but it might have something to do with the order types are eveluated
```typescript 
() => {
    return this.genStep('LX', () => {
      return {
        SZ: {
        SZ01: '',
        SZ02: ''
      }}
    }, false, true)
  }
```
Is parsed and analyzed before it gets to `public check: MapFN<T, U, V>`, so it can't use that type, for that at least

**Comment by gabrielurbina** [comment] 2021-07-17 20:48
try using regular methods instead of arrow functions
```
class XCD<T, U, V extends SomeContext = SomeContext> {
  public genStep(
    key: keyof V | keyof T,
    resKey?: keyof V | ResKey<T, U, V>,
    prseOpts?: ResKey<T, U, V> | boolean,
    append?: boolean,
  ){
    /** other code */
    return { key: key as string };
  };

  public check: MapFN<T, U, V> = () => {
    return this.genStep('LX', () => {
      return {
        SZ: {
        SZ01: '',
        SZ02: ''
      }}
    }, false, true)
  }
}
```

**Comment by andrewbranch** [comment] 2021-07-19 23:08
More complicated duplicate of https://github.com/microsoft/TypeScript/issues/43638

**Closed** 2021-07-22 18:00 UTC
Labels: Duplicate
