### ISSUE TITLE
TypeScript does not like hidden mutation of the values returned by getters

### ISSUE THREAD

**Issue by kaleidawave** [microsoft/TypeScript#38167] opened 2020-04-24 19:05 UTC
**TypeScript Version:**  3.7.3

**Search Terms:**: getter

**Code**: 

```ts
class MyClass {
    private _x = 0;

    addOne() {
        this._x++;
    }

    get x() {
        return this._x;
    }
}

const class1 = new MyClass();
if (class1.x === 4) {
    class1.addOne();
    if (class1.x === 5) {

    }
}
```

**Expected behavior:**

To allow it as the new value of `x` will be 5 after `.addOne` has been called

**Actual behavior:**

TypeScript throws error: `This condition will always return 'false' since the types '4' and '5' have no overlap.`

[**Playground Link:**](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200423#code/MYGwhgzhAECyCeBhcVoG8CwAoavoAcAnASwDcwAXAU2gH0APaAXmgAYBubbPaMAEz4B5AHZUAFAEp03HngoALYhAB0DANRrOOPAF8u23AHMqFAoQD2+SdIOzCJgK6Fh0BUtX0tPPVh-Zg5sIQpqCQEACMzNCiAO5wSCgQklrEAGbQYqFQ4cpElsxMLAAsUpi2WRHK-EKiyTK4aRkVOXn4BSwArKX63tg6QA)

**Related Issues:**

**Comment by jcalz** [comment] 2020-04-26 18:33
This is a duplicate of #9998; state-changing functions are not easy to represent in TS.

Note that getters are not the issue here.  The same thing happens with regular properties, e.g.,:

```ts
class MyClass {
    prop = 0;

    addOne() {
        this.prop++;
    }

}
```

[Playground link](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200423#code/MYGwhgzhAECyCeBhcVoG8CwAoavoAcAnAe32gF5oAGAbm2z2jABNmB5AOwFMAKASnQNGeAC4ALAJYQAdEVIBqeXRx4Avg2zqs2YMQ4QR0UJAgBGCtG4B3OEhQR+yiQDNoPY1FOySZcn+gALAKYKrgeZtIs7NyOQrgubuFecr7+AKzB9KHQWqpAA)

**Closed** 2020-05-13 18:00 UTC
Labels: Duplicate
