### ISSUE TITLE
Wrong type inference on boolean that changes in array.map

### ISSUE THREAD

**Issue by dennis-c** [microsoft/TypeScript#40769] opened 2020-09-25 15:23 UTC
**TypeScript Version:**  4.0.2

**Search Terms:** "have no overlap"

**Code**

```ts
let foo: boolean = false;

[ "a" ].map(() => {
	foo = true;
});

if (foo === true) {
        //do something
}
```

**Expected behavior:**
No errors

**Actual behavior:**
This condition will always return 'false' since the types 'false' and 'true' have no overlap.(2367)

**Playground Link:** 
https://www.typescriptlang.org/play?ts=4.1.0-dev.20200925#code/JAGwpgLgBAZg9nAXFARg8BDAdlAvLDEAZzAG4Aoc4AbSgCIM6oBdAOgFsMAHACh4Eo8APigBvKsHhw8UCACcArmSoBffhSoBLGFB5S8ufPKWDxUcxfMB6KwBNpROO0gALTVgDmqoA

**Related Issues:**

**Comment by j-oliveras** [comment] 2020-09-25 16:18
Duplicate of #9998 (last duplicate is #40745).

**Closed** 2020-09-28 18:00 UTC
Labels: Duplicate
