### ISSUE TITLE
Assignability checks in API

### ISSUE THREAD

**Issue by andy-hanson** [Microsoft/TypeScript#13502] opened 2017-01-15 19:16 UTC
Could `isTypeAssignableTo` be exposed on the type-checker for use by API consumers? This would be helpful for analyzing code using type information. I would like to check `instanceof` expressions for assignability in a lint rule (palantir/tslint#2046).
`getBaseConstraintOfType` would also be useful for doing checks inside generic functions.
`isTypeAssignableTo` would also be useful for a `no-unnecessary-cast` rule.

**Comment by andy-hanson** [comment] 2017-01-16 16:52
On that note, it would be useful to have some way of accessing control flow information too. https://github.com/palantir/tslint/pull/2038#discussion_r96126767

**Comment by danvk** [comment] 2017-01-22 19:09
Related to #11728

I'd also like have this exposed for https://github.com/danvk/typings-checker/issues/15

**Comment by andy-hanson** [comment] 2017-02-27 00:20
Would be resolved by #9943.

**Comment by mhegazy** [comment] 2017-11-01 16:53
Duplicate of https://github.com/Microsoft/TypeScript/issues/9879

**Closed** 2017-11-16 16:57 UTC
Labels: Duplicate
