### ISSUE TITLE
Two generic functions and composition

### ISSUE THREAD

**Issue by polemius** [microsoft/TypeScript#39644] opened 2020-07-17 20:43 UTC
**TypeScript Version:**  3.9.2

**Search Terms:** two generic functions composition

**Code**

```ts
function id<T>(x: T): T {
  return x
}

function composition<A, B, C>(
  f: (p1: A) => B,
  g: (p2: B) => C,
): (p: A) => C {
  return (x: A) => g(f(x))
}

const a = (x: number) => x + 1
const comp = composition(a, id)
// Error
// Argument of type '<T>(x: T) => T' is not assignable to parameter of type '(p1: unknown) => number'
const comp2 = composition(id, a)
```

**Expected behavior:**

No errors shows.
The type of function `comp2` should be `(p: number) => number`.

**Actual behavior:**

Type of function `comp` is `(p: number) => number` which is correct.
But type of function `comp2` is `(p: never) => number` which is not correct.
Also TypeScript shows the error: `Argument of type '<T>(x: T) => T' is not assignable to parameter of type '(p1: unknown) => number'`

**Playground Link:** [Link](https://www.typescriptlang.org/play/index.html?ssl=15&ssc=33&pln=1&pc=1#code/GYVwdgxgLglg9mABDAJgHgCoD4AUAPALkQwEoiNEBvAWAChFEAnAUyhEaTzoF867RIsBIghwAtgAc4AZxhCwaAIIAaRACFVAYVx0GwIjgkBGIopKIAvFnXLdiAOYGJAJiJrzVxJtu0yiQ6Ye1ppUdixsHP6EiGaW1vY4wPgkJDx8tKJg0lCIAIaWUURgIGIARsyMQYh4iADUiEZ0mdki4hIFopIycvBgOLmqqKm0APQjxACeEsyIAESYuKRxxLPI0siQbbmwpQA2MwDucgAWiFBTM-PYOEuexWUVs00ILZ0uHW3d8jioqrnDQA)

**Comment by ahejlsberg** [comment] 2020-07-21 19:13
This is effectively a duplicate of #30727. As I comment [here](https://github.com/microsoft/TypeScript/issues/30727#issuecomment-479657502), it's not immediately clear how we could do better given the left-to-right nature of our type inference algorithm. It's one of those examples that require full unification to make the correct inferences.

**Closed** 2020-07-24 18:00 UTC
Labels: Duplicate
