### ISSUE TITLE
IntelliSense for String literal types

### ISSUE THREAD

**Issue by PavelPZ** [Microsoft/TypeScript#7021] opened 2016-02-11 10:20 UTC
I have this String literal type example
```javascript
type TStyles = 'x' | 'y' | 'z';
```
Using IntelliSense for completion this code will be awesome:

```javascript
var style:TStyles = '>>> I want to use [CTRL+J] here to offer only valid TStyles values <<<';
```

**Comment by mhegazy** [comment] 2016-02-11 17:57
duplicate of https://github.com/Microsoft/TypeScript/issues/606

**Closed by mhegazy** 2016-02-11 17:57 UTC
