### ISSUE TITLE
return type of exported function with inner class

### ISSUE THREAD

**Issue by seonglae** [microsoft/TypeScript#48041] opened 2022-02-25 18:20 UTC
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried
![image](https://user-images.githubusercontent.com/27716524/155767167-c91fed0e-5519-4540-a85a-5e5080bbacab.png)
All version has same error

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAcwKZlQJxhAYuaeMACgEMAuRMEAWwCMsBKRAbwFgAoRRCAG1IDOAxAEkwGTAGF+Q1p27cADpjiKsUAJ6IAvIlLzEAXwOZUUEJiRiJ0wQM7GOnVAA9FcTFFYp0WHPkhYBCMgA)

### 💻 Code

```ts
function genericFunction(a: number) {
  class InnerClass {
    property = a
  }
  return InnerClass
}

export { genericFunction }
```

### 🙁 Actual behavior

this error occurs with `declaration` option
![image](https://user-images.githubusercontent.com/27716524/155765513-4dcc1a29-caba-41ef-8698-795271a0abf5.png)

Minimal [reproduction ](https://gist.github.com/seonglae/f786b5c995ae0242e1c1693551b560a6)of this issue

### 🙂 Expected behavior

export function without error
Can't I export class maker function with tsconfig `declaration` option?

**Comment by MartinJohns** [comment] 2022-02-25 18:43
Duplicate of #42645.

**Comment by RyanCavanaugh** [comment] 2022-02-26 00:52
There's not anything we could emit here that would be correct; that's why there's an error.

**Closed** 2022-02-28 20:00 UTC
Labels: Working as Intended
