### ISSUE TITLE
Incorrect return type for Array.prototype.reduce()

### ISSUE THREAD

**Issue by kwpeters** [Microsoft/TypeScript#21061] opened 2018-01-07 23:49 UTC
The TypeScript compiler thinks the type of the instances.reduce() call below is `C1 | string`.  I believe the return type should be `string`.

**Code**

```ts
class C1
{
}

type ItemType = C1 | string;

const instances: Array<ItemType> = [new C1(), "foo", new C1(), "bar"];

// The following line produces
// error TS2322 Type 'ItemType' is not assignable to type 'string'.
// Type 'C1' is not assignable to type 'string'.
const result: string = instances.reduce(
    (acc: string, curItem: ItemType): string => {
        if (curItem instanceof C1) {
            return acc + "C1";
        } else {
            return acc +curItem;
        }
    },
    ""
);
```

**Expected behavior:**
I would expect the above code to compile without errors.  If I use the Lodash's version of `reduce()` (`_.reduce()`) it compiles successfully.

**Actual behavior:**
The assignment of the `result` variable results in "error TS2322 Type 'ItemType' is not assignable to type 'string'. Type 'C1' is not assignable to type 'string'."  When evaluating the type of the `instances.reduce()` expression, it is `C1 | string`.  I would expect it to be just `string`.

**Comment by MrAndersen1** [comment] 2018-01-08 08:02
Since acc (string) is assignable to curItem (C1 | string) typescript cannot tell which overload of reduce you want to use. You can specify this with:
`const result: string = instances.reduce<string>(
...
`
Hope that makes sense. Why curItem is "never" in the "else" is curious to me however...

**Comment by kwpeters** [comment] 2018-01-08 09:44
Thanks for your help.  Using `instances.reduce<string>(...)` does fix the problem.

I do, however, have some questions about your statements above:

1. I do not believe `acc` should be assignable to `curItem` (C1 | string) as your first statement suggests.  If I try to assign a C1 instance to a string variable, I get `TS2322: Type 'C1' is not assignable to type 'string'.`
2.  `curItem` should not have type `never` in the else block.  It should have type `string`, shouldn't it?
3.  Why must I specify the return type of `reduce()` (via the generic parameter) when it is plain to see that the function passed to it can only return a string?  I would expect the compiler to be able to infer this.  Even so,I have explicitly specified the function's return type, and I still get the same error.

**Comment by mhegazy** [comment] 2018-01-09 00:16
this is caused by the overload of `Array.prototype.reduce`:
```ts
   reduce(callbackfn: (previousValue: T, currentValue: T, currentIndex: number, array: T[]) => T, initialValue: T): T;
```
since `string` is a subtype of `ItemType` the inferences for `string` and `ItemType` are reduced to `ItemType`, and that overload is picked. i am not sure why we have this overload though. 

I need to remove it and see what breaks :)

**Comment by yortus** [comment] 2018-01-09 00:46
Duplicate of #7014?

**Comment by mhegazy** [comment] 2018-01-09 00:59
thanks @yortus

**Closed** 2018-01-24 18:02 UTC
Labels: Duplicate
