### ISSUE TITLE
Support `decodeURIComponent` in import url

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#55220] opened 2023-07-31 20:27 UTC
# Suggestion

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Currently, ts treat import url as path, not url (remove search / hash and `decodeURIComponent` firstly).

Is it possible to support `decodeURIComponent` for import url, at least for `"moduleResolution": "NodeNext" / "bundler"`, or url in format with scheme like `http://example.com/%3F.js?version` or `file:./path%25`, because that's the standard behaviour of Node.js / browser?

## 📃 Motivating Example

```js
import './path%25.mjs';// actually expect './path%.mjs', not './path%25.mjs'
```

## 💻 Use Cases

import filename including `\` `%` `?` `#`.

**Comment by andrewbranch** [comment] 2023-07-31 23:48
Duplicate of #41730

**Closed** 2023-08-01 23:28 UTC
Labels: Duplicate
