### ISSUE TITLE
set.values().next() has wrong type

### ISSUE THREAD

**Issue by sdegutis** [microsoft/TypeScript#43750] opened 2021-04-20 14:33 UTC
# Bug Report

### 🕗 Version & Regression Information

Happens in both versions 4.2.3 and 4.3.0-beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBBMF4ZgKYHcYGUVQDzQCcBLMAcwD4AKASgG4AoeiAOgDcBDAGwFcUIbmqAB5QBHHigZA)

### 💻 Code

```ts
const s = new Set<string>();
s.values().next().value;
```

### 🙁 Actual behavior

Type of `value` is `any`.

### 🙂 Expected behavior

Type of `value` should probably be `string | undefined` or something.

**Comment by MartinJohns** [comment] 2021-04-20 15:41
@nmain Or `never`.

**Comment by RyanCavanaugh** [comment] 2021-04-20 16:03
@rbuckton I believe we have a duplicate of this?

**Comment by nmain** [comment] 2021-04-20 16:44
Ahh yes, this seems to be https://github.com/microsoft/TypeScript/issues/33353
Search terms:  iteratorresult return

**Closed** 2024-07-19 17:14 UTC
Labels: Needs Investigation
