### ISSUE TITLE
Enum error: Index signature parameter type must be string or number

### ISSUE THREAD

**Issue by vfonic** [Microsoft/TypeScript#3750] opened 2015-07-06 14:46 UTC
Hi,

I have an object that has an Enum as key. The Enum values get eventualy compiled to number in JS.

I'd like to be able to specify this:
`var mapping: { [mappingKey: MappingKey]: string; }`
(MappingKey is Enum)

This doesn't work and throws compile errors.

Specifying `mappingKey: number` is not the correct behavior, as I would be able to do this in TS code then:
`mapping[5] // this should throw compile error`

This is a bit related to this issue:
https://github.com/Microsoft/TypeScript/issues/1415

**Comment by RyanCavanaugh** [comment] 2015-07-06 16:42
Duplicate of #2491

**Closed by RyanCavanaugh** 2015-07-06 16:42 UTC
Labels: Duplicate
