### ISSUE TITLE
Type guards for type variables

### ISSUE THREAD

**Issue by marsiancba** [microsoft/TypeScript#31133] opened 2019-04-27 11:12 UTC
Currently (3.4) type guards do not work when variable is declared using type variable. Ideally type guard should be applied not only to variable, but also to type variable. More details in sample code below:

```ts
interface RecordTypes {
    cat: { name: string };
    dog: { name: string };
    person: { firstname: string, lastname: string };
}
type Kind = keyof RecordTypes; // "cat" | "dog" | "person" 

function logAnimal(kind: "cat" | "dog") { /* */ }

function logAny(kind: Kind) {
    if (kind == "cat" || kind == "dog") {
        // type guard is applied here, so typescript knows
        // that typeof kind == "cat" | "dog" in this block
        // and we can call logAnimal function without error

        logAnimal(kind); // OK
    }
    /* */
}

// But type guards do not work if we use type variables

function getName<K extends Kind>(kind: K, record: RecordTypes[K]) {
    if (kind == "cat" || kind == "dog") {
        // type guard is not applied here, so typescript does not know
        // that typeof kind == "cat" | "dog" in this block
        // and we get error when calling logAnimal function

        logAnimal(kind); // ERROR!!!

        // Correct behaviour should be to apply type guard not only
        // to variable kind, but also to type variable K, so in this block:
        // K extends "cat" | "dog"
        // and then typescript will also know that
        // typeof record == RecordTypes["cat" | "dog"]
        // and next line will compile withot error

        return record.name; // ERROR!!!
    }
    if (kind == "person") {
        return record.firstname + ' ' + record.lastname; // ERROR!!!

        // ^^^ This is actual problem we often ecounter in our project that
        // for this kind of code we have to add typecasts or create typecasted 
        // variables like:
        // const person = record as RecordTypes["person"];
    }
}
```

## Search Terms

type guards type variables

**Comment by jack-williams** [comment] 2019-04-27 17:30
Duplicate of #13995

**Closed** 2019-05-10 18:00 UTC
Labels: Duplicate
