### ISSUE TITLE
Function arg type inference (incorrectly) unions with null but excludes others

### ISSUE THREAD

**Issue by mikestopcontinues** [microsoft/TypeScript#49850] opened 2022-07-10 12:17 UTC
# Bug Report

### 🔎 Search Terms

function arg generic inconsistent type inference
infer func arguments breaks on null

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about functions and generics

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0&pretty=true#code/GYVwdgxgLglg9mABAWwIZQgCwMpQE4zQA8AKgHwAUUApgM5QBciFAHk+ANZhwDuYAlIgC8ZRC0QxaiEoIDeAKESI81KCDxIKAOh1wADrAS0mAQTx5UAT1KIAPonAATasBhhqjsoJGJ9hsLRarmCOFBRw3qI09OH8-ADc8gC+8qmgkP4o6FgAMnBwtNSklNGMzGwOYFy8AsKi4pLSADSIOlp+8AGm5lY29k4ubh5eiApKKmoavgadgcGhsXWIpbEJyWng0J0StLh4rOxV3Hz8TA1S9ARgAOajisqq6khQlnrUcMBiwkJCiADklzc1z+iRS8jQGBw+EIUAokj2-AoYBAABsUS0-qg-glEAB6XGIMzXEDIahgKC+T4vN7-ZFov47RDcCmoWi0GDXMCoABGKOobVSENy+UKcN2+BaAEYAEwAZgxWJx+MQAEkKRBUEhCtRlph0IhUEySdzqHhEDwYGimXAKULMIgAAbw-AO8HZTB5ArUMV7Fp09H-RXxPEEgDqJAAYgBCLKQz2FIiAm52I1oshuuMiopJ66UZ14P2olFKgkmRDXMmmwjmuB4Di0FrckAUmAU2iYOCoxxgP4Uk1M6geDzyIA)

[Discord thread, no solutions](https://discord.com/channels/508357248330760243/995412238724767966)

### 💻 Code

```ts
const matchStrict = <T>(test: (x: unknown) => x is T) => {
  return (...options: Array<T | undefined>): T | undefined => {
    return options.find((o) => test(o));
  };
};

const matchLoose = <T>(
  test: (x: unknown) => x is T,
  ...options: Array<T | undefined>
): T | undefined => {
  return options.find((o) => test(o));
};

const isStr = (x: unknown): x is string => {
  return typeof x === 'string';
};

// Works as expected
matchStrict(isStr)(123, 'a'); // ✅ 'number' is not assignable
matchStrict(isStr)(null, 'a'); // ✅ 'null' is not assignable

// Inconsistent behavior
matchLoose(isStr, 123, 'a'); // ✅ 'number' is not assignable
matchLoose(isStr, null, 'a'); // ⛔️ WTF! matchLoose<string | null>

matchLoose<string>(isStr, null, 'a'); // ✅ 'null' is not assignable
```

### 🙁 Actual behavior

`matchLoose(isStr, 123)` correctly excludes `number`, but `matchLoose(isStr, null)` incorrectly becomes `matchLoose<string | null>`.

### 🙂 Expected behavior

I expect `matchLoose(isStr, null)` and `matchLoose(isStr, 123)` to both throw errors, because `isStr` narrows `<T>` strictly. (I expect the intersection to work regardless of argument order too.)

**Comment by whzx5byb** [comment] 2022-07-10 19:01
A workaround could be using the type of type guard function as generic:
```ts
function matchLoose<T extends Function>(test: T, ...options: T extends (x: unknown) => x is infer R ? Array<R> : never) {
  return options.find((o) => test(o));
}

function isStr(x: unknown): x is string {
  return typeof x === 'string';
}

matchLoose(isStr, 123, 'a'); // Error as expected
matchLoose(isStr, null, 'a'); // Error as expected
```

**Comment by jcalz** [comment] 2022-07-11 14:15
Seems like a duplicate of #14829.  You don't want the `options` parameter to be used as an inference site for `T`.  

TypeScript has some heuristics for accepting/rejecting/combining inference candidates; `string` from one and `number` from another tends to be rejected, but `string` from one and `null` from another tends to be accepted and combined via union.  (See [SO question](https://stackoverflow.com/q/39905523/2887218), #19596, #44312,  and probably a zillion other places I can't find right now).  

Workarounds here usually involve lowering the priority of the `options` inference site, or otherwise blocking the inference.  Your curried function is one way to do it, since `T` is already specified by the time the returned function is called.  You can also define a `NoInfer<T>` utility and write the type of `options` as `Array<NoInfer<T> | undefined>`.  Possibilities are listed in #14829.  You can try `type NoInfer<T> = T & {}` or `type NoInfer<T> = [T][T extends unknown ? 0 : 1]` and see if that works for your use cases.

**Comment by mikestopcontinues** [comment] 2022-07-11 14:54
Thanks @jcalz, good tips!

**Comment by mikestopcontinues** [comment] 2022-07-11 15:00
For other who arrive here, I found this to be an excellent solution:

```ts
function match<T, U extends T>(test: T, ...options: Array<U | undefined>): T | undefined;
```

**Closed** 2022-07-13 18:00 UTC
Labels: Duplicate
