### ISSUE TITLE
Unable to compare numbers if they are literally typed

### ISSUE THREAD

**Issue by johnsoft** [Microsoft/TypeScript#12443] opened 2016-11-22 19:33 UTC
**TypeScript Version:**  2.1.1

**Code**

```ts
function compare(flag: boolean) {
    const offset = flag ? 1 : -1;
    return offset > 0;
}
```

**Expected behavior:**
Successfully compiles.

**Actual behavior:**
`error TS2365: Operator '>' cannot be applied to types '1 | -1' and '0'.`

Possibly helpful note: replacing `>` with `+` results in successful compilation.

**Comment by mhegazy** [comment] 2016-11-22 19:40
Duplicate of https://github.com/Microsoft/TypeScript/issues/10120. fixed by https://github.com/Microsoft/TypeScript/pull/12158, should be in next TS release.

**Closed** 2016-11-22 19:41 UTC
Labels: Duplicate
