### ISSUE TITLE
Array.prototype.filter misses undefined in returning value

### ISSUE THREAD

**Issue by ezubarev** [Microsoft/TypeScript#18760] opened 2017-09-26 07:15 UTC
**TypeScript Version:**  2.4.0

**Code**

```ts
const values = [1, 2];
values.filter((value) => value === 3)[0];
```

**Expected behavior:**
Object is possibly 'undefined'.

**Actual behavior:**
No errors.

**Comment by aluanhaddad** [comment] 2017-09-26 07:27
The type of `values` is `number[]` not `[number, number]` or `[1, 2]`. Even if tuple types were used however, this still would not be an error. 

See #6229

**Comment by ezubarev** [comment] 2017-09-26 07:57
`values.filter((value) => value === 3)` is undefined in this case. It doesn't link with provided issue.

**Comment by kitsonk** [comment] 2017-09-26 09:33
Duplicate of #13778

It is a conscious decision to favour usability over correctness, though the linked issue indicates it is open for further discussion.

**Comment by RyanCavanaugh** [comment] 2017-09-26 15:10
We assume that you are bounds-checking yourself correctly since the alternative is quite a bit worse. See linked issues above.

**Closed by RyanCavanaugh** 2017-09-26 15:10 UTC
Labels: Duplicate
