### ISSUE TITLE
problems recompiling application after installation of 1.8 beta

### ISSUE THREAD

**Issue by lucamorelli** [Microsoft/TypeScript#6841] opened 2016-02-02 18:24 UTC
Hi all, I have vs 2015 update 1 with ts 1.8. I just tried to reopen an asp.net 5 application with angular 1 and the usual angular.d.ts files.
After the installation of the installation of 1.8 beta I cannot compile it anymore:

with 1.8 beta installed I received a lot of errors: **Build: cannot find namespace 'ng'**:
uninstalling it (I have both 1.8 beta and 1.7.6 installed I have a single error: **Unable to get property 'compilerOptions' of undefined or null reference**.
repairing the ts 1.7 installation I obtain this error message: **Option 'project' cannot be mixed with source files on a command line**.

I worked with another asp.net 4 project and angular without problems.
this is my tsconfig.json

```json
{
    "compilerOptions": {
        "noImplicitAny": false,
        "noEmitOnError": true,
        "removeComments": false,
        "target": "es5",
        "outFile": "wwwroot/js/application.js",
        "inlineSourceMap": true,
        "inlineSources": true
    },
    "exclude": [
        "node_modules",
        "wwwroot"
    ]
}
```

Am I misiing something about the changes in ts 1.8?

**Comment by mhegazy** [comment] 2016-02-02 18:33
the error message `Unable to get property 'compilerOptions' of undefined or null reference.` is a bug in TS 1.7 that was fixed in https://github.com/Microsoft/TypeScript/pull/5589.

` Build: cannot find namespace 'ng':` is a different issue, can you share your project?

**Comment by lucamorelli** [comment] 2016-02-02 18:48
Since is the project of a customer I just sent the link to you via email.
about the #5589, there is any workaround to make it work again? the project was working with 1.7 before.

**Comment by mhegazy** [comment] 2016-02-02 23:09
The 1.7 issue was caused by a missing tsconfig.json file or one with unknown properties. yours look fine to me, so i am guessing it is something with the file location. i will need to see the build logs.

**Comment by lucamorelli** [comment] 2016-02-03 08:58
where can I find the logs? If I look in the output windows I see just this:
2>------ Build started: Project: Trace, Configuration: Debug Any CPU ------
2>VSTSC : tsc.js(31087, 13) JavaScript runtime error : Unable to get property 'compilerOptions' of undefined or null reference
========== Build: 1 succeeded or up-to-date, 1 failed, 0 skipped ==========

anyway checking out the same project in my laptop where I have ts 1.7.6 installed the project compiles without problems.

**Comment by mhegazy** [comment] 2016-02-03 20:00
OK. i see the issue now. it should be fixed in the next release, or in the nightly NuGet package.

**Comment by mhegazy** [comment] 2016-02-03 20:00
To clarify, the issue is specific to tsc.exe, enumerating directories looking for .d.ts files.

**Comment by mhegazy** [comment] 2016-02-03 20:01
node tsc.js should work.

**Comment by lucamorelli** [comment] 2016-02-03 20:08
thank you very much, how can I find more infos on using nuget packages in my asp.net 5 project? I had similar problems just opening a few angular 2 and aurelia projects, so I would like to check if this fix them too.

**Comment by mhegazy** [comment] 2016-02-03 20:18
here is the info: https://github.com/Microsoft/TypeScript/wiki/Nightly-drops

**Comment by lucamorelli** [comment] 2016-02-04 18:48
I'm trying to foolow the indications: since the xproj files doesn't contain the import of the task I left it untouched, Yesterday I added the nuget source in nuget configuration and the **1.8.20160203.1-beta **version of both the packages, but same problem. 
Now I see that the 1.8.20160204.1-beta is available: updated the project.json rebuilt the solution but I have this message

![untitled](https://cloud.githubusercontent.com/assets/127777/12825797/470c0c3e-cb78-11e5-9fcc-00236e7d88b4.png)

What am I missing?

**Comment by mhegazy** [comment] 2016-02-04 23:35
i just tried locally and i do not see this error, i actually used the UI. so righ-click, manage my Nuget Packages, removed exiting TS package, Added myget to package source, reloaded VS, and it seems to work on your project.

**Closed by mhegazy** 2016-02-04 23:35 UTC
Labels: Bug, Fixed

**Comment by lucamorelli** [comment] 2016-02-05 04:38
Thanks, I updated but I have the problem. _ have checked better and I looks like that at least now the problem is now.

declare var angular: angular.IAngularStatic;

// Support for painless dependency injection
interface Function {
    $inject?: string[];
}

**from angular.d.ts**

> // Collapse angular into ng
> import ng = angular;
> // Support AMD require
> declare module 'angular' {
>     export = angular;
> }

the problem is the import ng that is not working
If in my code I replace ng.IHttpService with angular.IHttpService and so on the error disappear, but I don't know if this is not working.
