### ISSUE TITLE
The LHS and RHS are swapped incorrectly when assign a subtype to a generic type

### ISSUE THREAD

**Issue by roneyrao** [microsoft/TypeScript#55665] opened 2023-09-07 12:29 UTC
### 🔎 Search Terms

failed to assign a subtype to a base type
The LHS and RHS are swapped incorrectly

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

```ts
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'

const mySlice = createApi({
  reducerPath: 'myReducer',
  baseQuery: fetchBaseQuery({
    baseUrl: 'bbb',
  }),
  endpoints: (builder) => ({}),
})
const newSlice: ReturnType<typeof createApi> = mySlice
```

### 🙁 Actual behavior

```
test.ts:31:7 - error TS2322: Type 'Api<BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}, FetchBaseQueryMeta>, {}, "myReducer", never, unique symbol | unique symbol>' is not assignable to type 'Api<BaseQueryFn<any, unknown, unknown, {}, {}>, EndpointDefinitions, string, string, unique symbol | unique symbol>'.
  Type 'Api<BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}, FetchBaseQueryMeta>, {}, "myReducer", never, unique symbol | unique symbol>' is not assignable to type '{ reducerPath: string; internalActions: InternalActions; reducer: Reducer<CombinedState<EndpointDefinitions, string, string>, AnyAction>; middleware: Middleware<...>; util: { ...; }; endpoints: { ...; }; }'.
    Types of property 'reducer' are incompatible.
      Type 'Reducer<CombinedState<{}, never, "myReducer">, AnyAction>' is not assignable to type 'Reducer<CombinedState<EndpointDefinitions, string, string>, AnyAction>'.
        Types of parameters 'state' and 'state' are incompatible.
          Type 'CombinedState<EndpointDefinitions, string, string> | undefined' is not assignable to type 'CombinedState<{}, never, "myReducer"> | undefined'.
            Type 'CombinedState<EndpointDefinitions, string, string>' is not assignable to type 'CombinedState<{}, never, "myReducer">'.
              Types of property 'config' are incompatible.
                Type 'ConfigState<string>' is not assignable to type 'ConfigState<"myReducer">'.
                  Type 'ConfigState<string>' is not assignable to type '{ reducerPath: "myReducer"; online: boolean; focused: boolean; middlewareRegistered: boolean | "conflict"; }'.

31 const newSlice: ReturnType<typeof createApi> = mySlice
         ~~~~~~~~


Found 1 error.
````
This line shows that "myReducer" is not assignable to "string":
`Type 'Reducer<CombinedState<{}, never, "myReducer">, AnyAction>' is not assignable to type 'Reducer<CombinedState<EndpointDefinitions, string, string>, AnyAction>'.`
But the error inside swapped their positions which cause the problem:
`Type 'ConfigState<string>' is not assignable to type 'ConfigState<"myReducer">'.`

### 🙂 Expected behavior

Literal string type should be assignable to string type.

**Comment by jcalz** [comment] 2023-09-07 13:08
Caveat - I'm not a member of the TS team, just trying to help triage:

This isn't really a properly submitted bug report (no playground link, depends on external libraries, etc) so it's hard to know for sure, but I assume this is just contravariance of function parameters and therefore working as intended.  See [the docs for `--strictFunctionTypes`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#strict-function-types) and the definition of contravariance.  If you still think there's a bug, then please edit this report so it provides the information as requested.  Otherwise, it would be helpful for you to close the issue yourself so that the TS team doesn't need to spend their time on it.

**Closed** 2023-09-08 02:53 UTC
