### ISSUE TITLE
TS4058 Return type of exported but cannot be named

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#24200] opened 2018-05-17 15:15 UTC
**TypeScript Version:**  2.9.0-dev.201xxxxx

**Search Terms:** 

**Code**

> i know this is a easy problem, but idk why it can't handle by default
> and fixed way is not good, when it need do multi import from many files
> and `// @ts-ignore` can't do this

a1.ts
```ts
import { SpawnOptions, SpawnSyncReturns } from 'child_process';
import * as crossSpawn from 'cross-spawn';

export function crossSpawnAsync(bin: string, argv?: string[], optiobs?: SpawnOptions): Promise<ReturnType<typeof crossSpawn.sync> & {
	errorCrossSpawn?: Error,
}>
{
	return new Promise(function (resolve, reject)
	{
		try
		{
			let cp = crossSpawn.sync(bin, argv, optiobs);

			resolve(cp);
		}
		catch (e)
		{
			reject({
				errorCrossSpawn: e,
			});
		}
	})
		.catch(function (ret)
		{
			return ret;
		})
		;
}

export function crossSpawnSync(bin: string, argv?: string[], optiobs?: SpawnOptions): ReturnType<typeof crossSpawn.sync> & {
	errorCrossSpawn?: Error,
}
{
	try
	{
		let cp = crossSpawn.sync(bin, argv, optiobs);

		return cp;
	}
	catch (e)
	{
		// @ts-ignore
		return {
			errorCrossSpawn: e as Error
		}
	}
}

```

a2.ts
```ts
import { crossSpawnAsync, crossSpawnSync } from './a1';

/**
 * Created by user on 2018/5/17/017.
 */

export function pushGit()
{
	let cp = crossSpawnSync('node', [
		'-v',
	]);

	return cp;
}
```

**Expected behavior:**

> no warn and right return

a2
```ts
import { SpawnSyncReturns } from 'child_process';
export declare function pushGit(): SpawnSyncReturns<Buffer> & {
    errorCrossSpawn?: Error;
};
```

**Actual behavior:**

```ts
Error:(7, 17) TS4058: Return type of exported function has or is using name 'SpawnSyncReturns' from external module "child_process" but cannot be named.
```

a2
```ts
export declare function pushGit(): any;
```

### add import at `a2.ts` 

a2.ts
```ts
import { SpawnOptions, SpawnSyncReturns } from 'child_process';
```

### export at `a1` and import at `a2`

a1.ts
```ts
export { SpawnOptions, SpawnSyncReturns }
```

a2.ts
```ts
import { SpawnOptions, SpawnSyncReturns } from './a1';
```

**Playground Link:**  

**Related Issues:**

**Comment by andy-ms** [comment] 2018-05-17 15:37
Duplicate of #9944

**Comment by bluelovers** [comment] 2018-06-02 05:41
> A has error
> B without error, but don't know why A has error

----------

**A**
```ts
import { registerGlobal, IGlobal } from './mocha_benchmark';

//let g: ReturnType<typeof registerGlobal>;
//g = registerGlobal();

let g = registerGlobal();

export = g;
```

```ts
Error:(11, 5) TS4023: Exported variable 'g' has or is using name 'MochaBenchmark' from external module "mocha-benchmark/mocha_benchmark" but cannot be named.
Error:(11, 5) TS4023: Exported variable 'g' has or is using name 'Benchmark' from external module "mocha-benchmark/node_modules/@types/benchmark/index" but cannot be named.
```

------------

**B**
```ts
import { registerGlobal, IGlobal } from './mocha_benchmark';

let g: ReturnType<typeof registerGlobal>;
g = registerGlobal();

export = g;
```

**Closed** 2018-06-18 18:34 UTC
Labels: Duplicate

**Comment by andy-ms** [comment] 2018-06-18 18:54
@bluelovers See #9944 -- `let g` has an inferred type that was declared in a different module. In `b` you gave it a different type. so nothing had to be inferred.
