### ISSUE TITLE
"Object literal may only specify known properties" error sometimes does not occur

### ISSUE THREAD

**Issue by mui-x** [Microsoft/TypeScript#21032] opened 2018-01-05 19:55 UTC
**TypeScript Version:**  2.6

**Code**

```ts
// Example 1
type Sheet = { web: { a: number } } & { b?: number }
const sheet: Sheet = {
  web: {
    a: 1,
    x: 1, //==> no error
  },
}

// Example 2
type Sheet2 = { web: { a: number } } 
const sheet2: Sheet2 = {
  web: {
    a: 1,
    x: 1, //==> error: "Object literal may only specify known properties"
  },
}

```

**Expected behavior:**

Both examples show the error *Object literal may only specify known properties, and 'x' does not exist in type '{ a?: number; }'* on line with ```x: 1,```

**Actual behavior:**

Only Example 2 shows mentioned error

**Comment by mhegazy** [comment] 2018-01-09 19:20
Duplicate of https://github.com/Microsoft/TypeScript/issues/19296

**Closed by mhegazy** 2018-01-09 19:20 UTC
Labels: Bug
