### ISSUE TITLE
Incorrect type inference when passing union type to a method or indexer

### ISSUE THREAD

**Issue by DavidKDeutsch** [Microsoft/TypeScript#7274] opened 2016-02-27 15:26 UTC
Not sure if this is a bug or just a feature that has not been implemented (yet), but given the following:

```ts
interface Foo {
    member1: number;
    member2: boolean;
}

function bar(foo: Foo, member: "member1" | "member2") {
    return foo[member]; // return type is inferred as any, whereas it should be number | boolean
}
```

I would expect the return type of `Foo` to be `number | boolean` instead of `any`. I see the same issue with function overloads:

```ts
declare function bar2(field: "field1"): string;
declare function bar2(field: "field2"): number;
declare function bar2(field: string): any;

var field: "field1" | "field2" = "field1";
var result = bar2(field); // inferred type of result is any, whereas it should be string | number
```

Note that his behavior is not limited to string literals; it also happens when overloading on type:

```ts
declare function bar3(field: Date): string;
declare function bar3(field: number): number;
declare function bar3(field: any): any;

var field2: Date | number = 6;
var result2 = bar3(field2); // inferred type of result2 is any, whereas it should be string | number
```

This is with typescript 1.8.2

**Comment by mhegazy** [comment] 2016-04-26 00:33
The first sample is a duplicate of https://github.com/Microsoft/TypeScript/issues/7730

The last two samples are by design. It becomes easier to see why this is not possible for the general case once you have more than one parameter. 

```ts
declare function bar2(field: "field1", a: number): string;
declare function bar2(field: "field2", b: string): number;

var result = bar2(field, "some string"); // number, or string, or number|string, or error?
```

This is already suggested in https://github.com/Microsoft/TypeScript/issues/1805, and you can find more discussions about these at https://github.com/Microsoft/TypeScript/issues/6735

**Closed by mhegazy** 2016-04-26 00:33 UTC
Labels: Bug, Domain: Literal Types
