### ISSUE TITLE
indexing optional attributes fails when indexing with a key that is keyof interface

### ISSUE THREAD

**Issue by sezanzeb** [microsoft/TypeScript#52895] opened 2023-02-21 12:39 UTC
# Bug Report

### 🔎 Search Terms

- TS2532
- keyof
- undefined
- interface
- optional
- Object is possibly 'undefined'

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `keyof`

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.0.0-dev.20230221#code/JYOwLgpgTgZghgYwgAhgezcg3gWAFDKHIBGcUA-AFzIgCuAtsdPgL774y0gJjBogk4ALwAU+IsgCOtAB7V0aADTiiMYBAA2AE2oBrCAE80MVBnwBKagDc0wLdhWFgJkdJkBtNZq0BdZAEIAXkDkLi0INRAILXMHAgkiBH4AZzQNCAA6DTQAc1dZT3VtPwBqZABGc0dkNjxaoA

### 💻 Code

```ts
interface foo {
    bar?: number
}

function baz(
    qux: foo,
    field: keyof foo
): void {
    if (qux[field] !== undefined) {
        console.log(qux[field] + 1)
    }
}
```

### 🙁 Actual behavior

`Object is possibly 'undefined'` error

### 🙂 Expected behavior

To work just like if `field` is set to `'bar'` instead of `keyof foo`

```ts
interface foo {
    bar?: number
}

function baz(
    qux: foo
): void {
    const field = 'bar';
    if (qux[field] !== undefined) {
        console.log(qux[field] + 1)
    }
}
```

**Comment by MartinJohns** [comment] 2023-02-21 13:05
Duplicate of #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal. Just store it in a local `const` variable.

**Comment by sezanzeb** [comment] 2023-02-22 09:33
That works, thanks!

```ts
interface foo {
    bar?: number
}

function baz(
    qux: foo,
    field_: keyof foo
): void {
    const field = field_;

    if (qux[field] !== undefined) {
        console.log(qux[field] + 1)
    }
}
```

**Comment by sezanzeb** [comment] 2023-02-22 10:17
This does not work if there are multiple optional fields:

https://www.typescriptlang.org/play?ts=5.0.0-dev.20230221#code/JYOwLgpgTgZghgYwgAhgezcg3gWAFDKHIBGcUAjAPwBcyIArgLbHT5ElkBMNdTLU+AL758MeiARhgaEBwBeACjZEAjvQAetdGgA0ywjGAQANgBMA+rQDWEAJ5oYqDPgCUtAG5pgp7PuQIZAGcwVCMzZABeUJMLAG4RAiJgRwU1dQBtQxiAXWQAQgio8VMIQxAIUxdfRPZCAJBAtGMIADpjNABzVI1MsNNcgGpkchc-YTxBIA

```ts
interface foo {
    bar1?: number
    bar2?: number
}

function baz(
    qux: foo,
    field_: keyof foo
): void {
    const field = field_;

    if (qux[field] !== undefined) {
        console.log(qux[field] + 1)
    }
}
```

**Comment by sezanzeb** [comment] 2023-02-22 10:20
Oh, you were probably talking about storing `qux[field]` in a const. That works for the second case as well:

```ts
interface foo {
    bar1?: number
    bar2?: number
}

function baz(
    qux: foo,
    field_: keyof foo
): void {
    const field = field_;

    const blub = qux[field];
    if (blub !== undefined) {
        console.log(blub + 1)
    }
}
```

**Closed** 2023-02-24 18:00 UTC
Labels: Duplicate
