### ISSUE TITLE
JS/TS semantic highlighting for keywords (readonly global vars)

### ISSUE THREAD

**Issue by a-ejs** [microsoft/TypeScript#42022] opened 2020-12-17 04:25 UTC
*TS Template added by @mjbvz*

**TypeScript Version**: 4.1.2

**Search Terms**
- semantic highlighting
- constant
- readonly

---

vscode 1.52.0

Code:

```js
undefined;
Infinity;
NaN;
```

Result:

Semantic highlighting recolors `Infinity` and `NaN` from `constant.language` to `variable`.

Expected:

All three identifiers should be colored identically.

**Comment by mjbvz** [comment] 2020-12-17 22:15
Moving this upstream since the TS team is taking ownership of semantic highlighting

**Comment by 9at8** [comment] 2021-01-20 04:30
I did some digging and my initial thought was that it's there's either an issue on the [vscode side](https://github.com/microsoft/vscode/blob/3d500ebd8b4a919e8631e916f417e5c68eb90d3f/extensions/typescript-language-features/src/languageFeatures/semanticTokens.ts#L70), or the [typescript server](https://github.com/microsoft/typescript/blob/8bbef818edfa7298fd25af94cddcbc36902667f3/src/server/session.ts#L1116) is not returning the correct token. ([Probably these lines?](https://github.com/microsoft/typescript/blob/f1dca6a61f577bfb83dbc91d2e064057880df209/src/services/services.ts#L1871-L1876))

I debugged the vscode typescript-language-features extension:

![Screenshot_20210119_232201](https://user-images.githubusercontent.com/8235156/105126705-55c8d800-5aad-11eb-8024-e18b252d09c7.png)

Looking at the `tokenSpan` (coming from the typescript server) seems to look ok (the first 3 classifications are all 2064 so the first three lines are the same type) and the return value also seems to match this expectation.

Now I think that the problem is somewhere in the typescript-language-features extension, but I am stuck :see_no_evil: Am I headed in the right direction? Any tips on what I should be looking at?

**Comment by 9at8** [comment] 2021-02-06 12:44
Just wanted to follow up on this :)

cc @orta

**Comment by orta** [comment] 2021-02-06 14:02
You'll want to look into `classifier2020.ts` in TypeScript, notably in this function: 

https://github.com/microsoft/TypeScript/blob/4a10aee1f8d6f1140f769b43756f84154cf62aa5/src/services/classifier2020.ts#L54

Where you can check if the identifier is one of the known globals 👍🏻

**Comment by inidaname** [comment] 2021-05-23 06:51
@orta
I will love to take on this, could there be a guide on what expected

**Closed** 2021-08-04 09:00 UTC
Labels: Fix Available, Rescheduled, good first issue, help wanted
