### ISSUE TITLE
Feature Request: "Extract to new local variable" refactoring

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#17098] opened 2017-07-11 18:18 UTC
_From @MartinHaeusler on July 9, 2017 13:18_

In Eclipse JDT, there's this really handy shortcut, mapped to `CTRL+2 L` by default, which works when an expression is selected. What it does is to create a new local variable to hold the result of the expression. For example...

`this.doSomeCalculation();`

If the mouse cursor is positioned over the line above, `CTRL+2 L` will turn the line into...

`double someCalculation = this.doSomeCalculation()`

I find myself using this shortcut a lot when coding Java. It assigns the correct typebound and proposes a sensible default name for the variable, based on the name of the called method. Having something similar for Typescript in VSCode would be very handy. With all the typing information that the Typescript environment has, this should be possible, right?

_Copied from original issue: Microsoft/vscode#30308_

**Comment by mhegazy** [comment] 2017-08-22 23:34
technically duplicate of https://github.com/Microsoft/TypeScript/issues/16565, but i like this one more.

**Comment by amorenew** [comment] 2017-09-12 11:39
@mjbvz  my issue gets closed but you didn't mention if it's working or no intention to make it?

**Comment by amcasey** [comment] 2017-09-12 17:08
@amorenew I believe @mjbvz meant to convey that we expect your scenario to start working when this issue is fixed.

**Comment by amorenew** [comment] 2017-09-12 17:46
sorry for misunderstanding I am not a native English speaker

**Comment by amcasey** [comment] 2017-10-03 23:22
There are still bugs and we make no attempt to extract multiple occurrences of the same expression but, arguably, this is now available in `master`.

**Closed by amcasey** 2017-10-03 23:22 UTC
Labels: Domain: Refactorings, Suggestion

**Comment by MartinHaeusler** [comment] 2017-10-28 19:32
@amcasey Nice! What is this feature called in VSCode? Is there any documentation? I'm currently on 1.17.2, is this feature in there, or is it scheduled for the next release?

**Comment by mhegazy** [comment] 2017-10-30 17:02
Should be working correctly in latest drop of TypeSript (TS 2.6.0 or later). VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.

**Comment by amcasey** [comment] 2017-10-30 17:11
@MartinHaeusler It should appear in the refactoring menu (i.e. lightbulb) alongside Extract Function.  We're still working on documenting all of our refactorings and code fixes.  As @mhegazy mentioned, you should be able to use it if you upgrade to the latest version of TypeScript.
