### ISSUE TITLE
In playground: variable use before declaration causes crash

### ISSUE THREAD

**Issue by aldendaniels** [Microsoft/TypeScript#26740] opened 2018-08-29 18:31 UTC
**TypeScript Version:**  3.0.1

The following code snippet:

```typescript
const x = y;
const y = 1;
``` 

Crashes the playground with the error:
```
workerMain.js:8 Uncaught Error: Converting circular structure to JSON

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at e._send (workerMain.js:10)
    at workerMain.js:10
    at n.Class.define.cancel.then (workerMain.js:9)
    at e._handleMessage (workerMain.js:10)
    at e.handleMessage (workerMain.js:10)
    at t.onmessage (workerMain.js:10)
    at self.onmessage (workerMain.js:11)
    at JSON.stringify (<anonymous>)
    at e._send (workerMain.js:10)
    at workerMain.js:10
    at n.Class.define.cancel.then (workerMain.js:9)
    at e._handleMessage (workerMain.js:10)
    at e.handleMessage (workerMain.js:10)
    at t.onmessage (workerMain.js:10)
    at self.onmessage (workerMain.js:11)
    at workerMain.js:8
```

See [this example](https://www.typescriptlang.org/play/index.html#src=const%20x%20%3D%20y%3B%0D%0Aconst%20y%20%3D%202%3B%0D%0A)

**Comment by mattmccutchen** [comment] 2018-08-30 00:29
Probably a duplicate of #26068.

**Closed** 2018-12-14 18:00 UTC
Labels: Duplicate
