### ISSUE TITLE
resolveJsonModule doesn't work with composite projects and import from node_modules

### ISSUE THREAD

**Issue by mikea** [microsoft/TypeScript#30785] opened 2019-04-05 22:50 UTC
This is a regression in 3.4

**Code**

```ts
import metadataFullJson from "libphonenumber-js/metadata.full.json";
```

tsconfig:
```
    "composite": true,
    "module": "commonjs",
    "resolveJsonModule": true,
```

**Expected behavior:**

file compiles

**Actual behavior:**

error TS6307: File '_redacted_/node_modules/libphonenumber-js/examples.mobile.json' is not in project file list. Projects must list all files or use an 'include' pattern.

**Related Issues:**

https://github.com/Microsoft/TypeScript/issues/25636

**Comment by RyanCavanaugh** [comment] 2019-04-17 23:59
@sheetalkamat what's the intended behavior here?

**Comment by sheetalkamat** [comment] 2019-04-18 19:35
We do have explicit check for json file from project reference so those should work correctly.
@mikea Please provide repro steps to be able to investigate this further and determine if its a configuration error or something we need to fix in compiler

**Comment by thovden** [comment] 2019-04-19 09:35
I'm also experiencing this problem - using a monorepo with `npm link`'ed packages. `tsc -b` from the top level causes this problem. Compiling the individual packages succeed without errors. Can be an error in my setup of the composite project of course.

**Comment by sheetalkamat** [comment] 2019-04-19 13:26
@thovden please share minimal repro steps so we can take further action thanks

**Comment by thovden** [comment] 2019-04-20 20:20
@sheetalkamat seems like I'm not able to reproduce using `tsc` only but it does occur when using `ts-loader` with webpack in a composite project. So this may be a `ts-loader` problem.

**Comment by thovden** [comment] 2019-04-22 11:22
https://github.com/TypeStrong/ts-loader/issues/905 - so for now `typescript` is not the prime suspect from my side :)

**Comment by sheetalkamat** [comment] 2019-06-06 21:29
Closing this since its not an issue.

**Closed by sheetalkamat** 2019-06-06 21:29 UTC
Labels: Needs More Info
