### ISSUE TITLE
Array indices are possibly 'undefined'

### ISSUE THREAD

**Issue by aminpaks** [Microsoft/TypeScript#18718] opened 2017-09-23 17:51 UTC
**TypeScript Version:**  2.5.2

**Code**

```ts
function test(statement: string): string {
  const parts = statement.split('-'); // <- parts will have at least one element
  let firstElement = parts.shift(); // <- firstElement cannot be undefined at this point

  if (parts.length > 1) {
    let secondElement = parts.shift(); // <- Still says that secondElement may be undefined!
  }
}
test('first-second');
```

**Expected behavior:**
- String prototype `split` method always creates an array with at least one elements and therefore `shift` method cannot produce an undefined type.
- Once we check the length of an array `shift`, `pop` cannot produce undefined type.

**Actual behavior:**
`shift`, `pop`  methods or accessing arrays indices return `undefined` even though the array has elements.

**Comment by DanielRosenwasser** [comment] 2017-09-23 20:20
There's not an easy way to communicate the behavior between this functionality in the type system today. You can convince the type system you know what you're doing with the non-null assertion operator (i.e. the `!` operator):

```ts
let secondElement = parts.shift()!;
```

**Comment by kitsonk** [comment] 2017-09-24 07:09
Duplicate of #11117

**Comment by mhegazy** [comment] 2017-10-09 16:49
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-09 16:49 UTC
Labels: Design Limitation
