### ISSUE TITLE
Error: [js] property type declarations can only be used in a 'ts' file.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9121] opened 2016-06-13 06:54 UTC
_From @jaqmol on June 12, 2016 14:25_

- VSCode Version: 1.2.0
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. Create a React component as a class, like:
`
class CommentList extends React.Component {
  render() {
    ...
  }
}
`
2. Add a static propType property, like:
`
class CommentList extends React.Component {
  static propTypes = {
    data: PropTypes.array.isRequired
  };
  render() {
    ...
  }
}
`
3. VSC underlines the static propTypes declaration as being an error with `[js] property type declarations can only be used in a 'ts' file.`. Despite there being no problem at all compiling the code with Babel.

_Copied from original issue: Microsoft/vscode#7584_

**Comment by dbaeumer** [comment] 2016-06-13 06:54
JS language server is maintained by the TS team. Moving...

**Comment by mhegazy** [comment] 2016-06-13 20:23
duplicate of https://github.com/Microsoft/TypeScript/issues/6997

**Closed by mhegazy** 2016-06-13 20:23 UTC
