### ISSUE TITLE
Constructor code broken since npm version `4.3.0-dev.20210408` with `--target ESNext`

### ISSUE THREAD

**Issue by scharf** [microsoft/TypeScript#45298] opened 2021-08-02 22:25 UTC
# Bug Report

Compiling the code below compiled with the `--target ESNext` option, an error is thrown.

### 🕗 Version & Regression Information

- No problem up to `npm` version  `4.3.0-dev.20210407`
- The problem first appears in `npm` version `4.3.0-dev.20210408`

### ⏯ Playground Link

Cannot be reproduced in the playground (see #45297)

### 💻 Code

```ts
function writeVal(a: number, b: any): number {
    console.log(‘writeVal’, a, b);
    return a;
}
class TestClass {
    a: number;
    public b = writeVal(2, this.z);    
    constructor(public z: number) {
        this.a = writeVal(1, this.z);
    }
    public c = writeVal(3, this.z);
}
```

### 🙁 Actual behavior

throws

```
x.ts:7:33 - error TS2729: Property ‘z’ is used before its initialization.

7     public b = writeVal(2, this.z);
                                  ~

  x.ts:8:17
    8     constructor(public z: number) {
                      ~~~~~~~~~~~~~~~~
    ‘z’ is declared here.

x.ts:11:33 - error TS2729: Property ‘z’ is used before its initialization.

11     public c = writeVal(3, this.z);
                                   ~

  x.ts:8:17
    8     constructor(public z: number) {
                      ~~~~~~~~~~~~~~~~
    ‘z’ is declared here.


Found 2 errors.
```

### 🙂 Expected behavior

The created javascript file should be

```js
function writeVal(a, b) {
    console.log('writeVal', a, b);
    return a;
}
class TestClass {
    constructor(z) {
        this.z = z;
        this.b = writeVal(2, this.z);
        this.c = writeVal(3, this.z);
        this.a = writeVal(1, this.z);
    }
}
```

**Comment by IllusionMH** [comment] 2021-08-02 22:55
Most likely related to https://github.com/microsoft/TypeScript/issues/45076 which is intended change although undocumented.

It can be reproduced in playground if you [enable `useDefineForClassFields` explicitly](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99&ts=4.3.5#code/GYVwdgxgLglg9mABAdwE4ygUwGoEMA2AFLgFyJggC2ARpqgDSLVm5gCeAlGRTXYgN4AoRCMQQEAZzj5MAOnxwA5oQDkaDDgIrGuRtQ4BuYaNSYoIVElxGAvoIj5cEiYgAqmCVADCj5wOMipORUtKhGoogADiDU+DAQTIgAvCjoWHhEAEyMUAAWMBKyAF6GEQFiklCoINBwqITRsfGIRdwhdBz+ERF5BbK4yakaGYQAjDn5hSXhonYRjXEJCSnq6QSEAMwTfdOCNkA) (I guess that playground defaults don't take into account ESNext specific defaults.

**Comment by IllusionMH** [comment] 2021-08-02 23:18
Most likely related to #45076 which is intended change to align with ES behavior related to class fields, although change in defaults for ESNext is not documented.

Looks like playground uses its own defaults which override new default value of `useDefineForClassFields` which is specific for ESNext target. You can see this error in playground if you [explicitly enable `useDefineForClassFields`](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99&ts=4.3.5#code/GYVwdgxgLglg9mABAdwE4ygUwGoEMA2AFLgFyJggC2ARpqgDSLVm5gCeAlGRTXYgN4AoRCMQQEAZzj5MAOnxwA5oQDkaDDgIrGuRtQ4BuYaNSYoIVElxGAvoMER8uCRMQAVTBKgBhJy4HGIqTkVLSoRqKIAA4g1PgwEEyIALwo6Fh4RABMjFAAFjASsgBehpGBYpJQqCDQcKiEMXEJiMXcoXQcAZGR+YWyuClpGpmEAIy5BUWlEaJ2kU3xiYmp6hkEhADMk-0zgnaCYJjI7p4+fhLjWZsc9kA)

And if you execute compiled code in any supported browser, you will see that it logs `undefined` in both places that are marked as error because these fields are added before constructor body runs.

**Comment by scharf** [comment] 2021-08-04 10:54
> You can see this error in playground if you explicitly enable useDefineForClassFields

Well I think, if the user does not change any settings, the version should user the default behavior and not requiring doing some research to figure out what flags to change to properly mimic the default behavior...

**Comment by IllusionMH** [comment] 2021-08-04 11:23
Yes, it's unfortunately that this flag has different default depending on TS version and target which is hard to implement for playground, however I think it make sense to keep Playground defaults vs TS default in separate discussion - e.g. linked #45297 or Playground repo.

And it doesn't change explanation in paragraphs 1 and 3.

**Comment by RyanCavanaugh** [comment] 2021-08-05 17:42
Where are y'all in every other issue where someone complains that the TS defaults aren't aligned with their personal preferences? 😅 Anyway see #34787; `ESNext` is intentionally a "moving target" that generally opts you in to the most-spec-like behavior and unspecified properties can go to different defaults depending on that. The Playground just has checkboxes so there we have to do whatever the checkbox says.

**Closed** 2021-08-10 00:00 UTC
Labels: Question
