### ISSUE TITLE
Introduce compact callback declaration

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#14173] opened 2017-02-19 04:44 UTC
tsc: 2.1.6

Originally from: http://stackoverflow.com/posts/42322317

I can see that needing to declare the argument name in the callback function type could be redundant, and MAY BE make even less sense in higher order function.

So maybe it is beneficial to support this shorten form `arrayCompare(f: (Ord) => (Ord) => boolean)`?

Do you see other application?

One drawback it that the compiler need to add arbitrary names to make completion consistent:
![image](https://cloud.githubusercontent.com/assets/3254987/23099377/d877bed0-f619-11e6-8667-60d8d956ba28.png)

**Comment by HerringtonDarkholme** [comment] 2017-02-20 06:25
The problem is we already have loosely typed function declaration like `var eq: (a, b) => boolean` where `a`/`b` only stands for arity but not type. 😞

**Comment by unional** [comment] 2017-02-20 06:44
Yes, but on the other hand we can have this rule kicks in only if the `a / b` can be resolved as types.

I think that is still doable.

**Comment by HerringtonDarkholme** [comment] 2017-02-20 06:50
> only if the a / b can be resolved as types.

This rule is too sloppy, consider: 

```typescript
(str, number) => string
```
The first one is not a type, but the second one is. How to resolve this signature?

Also, this requires resolving new parser conflict

```typescript
(Gen<A, B>) => string
```
Cannot be determined to be a syntax error or not.

Another confusion:

```ts
type A = ({a: string, b: number}) => string
var A = ({a: string, b: number}) => string
```
has totally different meaning.

**Comment by unional** [comment] 2017-02-20 07:40
> (str, number) => string

Would stay this won't apply. `number` is still name.

> type A = ({a: string, b: number}) => string

is a valid type, because you are doing a type declaration.

> var A = ({a: string, b: number}) => string

this would be an implementation.

One thing TypeScript good at is a clear separation of type definition and implementation, because the implementation side is just JavaScript.
So determining which is which is not too difficult (unless I make mistakes, which always happen more then I would like to. 🌷 ).

Of course, there could be still confusing cases.
It would be great to list them out and see if this proposal make sense or not. 🌷

**Comment by unional** [comment] 2017-02-20 07:47
> (Gen<A, B>) => string

Not sure what do you mean here. If this proposal is accepted and implement, would it be considered correct syntax? e.g. `foo<A,B>(fn: (Gen<A,B>) => string)`?

**Comment by HerringtonDarkholme** [comment] 2017-02-20 08:01
>  (Gen<A, B>) => string
is a syntax error now. If the proposal is accepted, this is no longer a syntax error. Error handling in parser requires rewriting (this impacts transpiling).

Another problem: we don't have types for spread arguments:

```ts
(a, ...b: any[]) => void
```

**Comment by unional** [comment] 2017-02-20 08:06
> Another problem: we don't have types for spread arguments:

`(string, ...string[]) => void` ?

**Comment by HerringtonDarkholme** [comment] 2017-02-20 08:14
Now consider: merging all rules mentioned above into one rule to parse and check function type (Especially, pay attention to how errors should be reported. For example, how generic argument type error is reported as I pointed above). The final rule will quickly explode when new syntax is introduced.

I found myself perplexed when writing it out. It probably means users will be confused too.

**Comment by unional** [comment] 2017-02-20 08:15
> Error handling in parser requires rewriting (this impacts transpiling).

Yes, that may need to change, but also may not. It depends on when the arbitrary argument is injected.

When `(Gen<A,B>) => string` is converted back to `(arg1: Gen<A, B>) => string`, then the error handling would be the same.

**Comment by unional** [comment] 2017-02-20 08:18
> merging all rules mentioned above into one rule to parse and check function type

Actually there is only a few:

1. If in type declaration, the code is in the format of `(Type1, Type2, ...TypeN) => TypeR` (or declaration without named argument), then
2. add the arbitrary argument so it becomes `(arg1: Type1, arg2: Type2, ...argn: TypeN) => TypeR`

Then parse as normal.

**Comment by HerringtonDarkholme** [comment] 2017-02-20 08:18
> When (Gen<A,B>) => string is converted back to (arg1: Gen<A, B>) => string

When? You have to know  `Gen` is a generic type at first because

> we can have this rule kicks in only if the a / b can be resolved as types.

If it isn't, should `Gen<A, B>` parsed as the old style function type? So it is a syntax error, not a type error.

**Comment by unional** [comment] 2017-02-20 08:19
> When? You have to know Gen is a generic type at first because

If `Gen / A / B / string` can be resolved as Type and generics, then yes, otherwise, no.

**Comment by HerringtonDarkholme** [comment] 2017-02-20 08:24
No, you cannot.

To resolve type information, you need to have AST because TSC is syntax driven. To have AST, you have to parse. To parse you have to know if `Gen` is resolved to type. 

The rule you listed is not sufficient, if without specifying how type information is integrated in parsing.

**Comment by unional** [comment] 2017-02-20 08:42
I see. I'm mentally handicap when talking about AST, so I trust your judgement. 😛 

In the SO post it mentioned Haskell.
So Haskell seems to support this syntax.

Can some idea be drawn from that? Or it is a radical change?

Would it be possible that when tsc parses `(Gen<A, B>) => string`, it recognizes the param name is missing and perform the injection there so it can continue parsing?

One key is this rule only applies during type declaration, i.e. `type A = ...`, `fn: ...`, `interface X { (...) => ...`, etc.

**Comment by HerringtonDarkholme** [comment] 2017-02-20 09:07
>  So Haskell seems to support this syntax.

Of course. And Haskell does not support untyped function type `(a, b) => void` so no conflict.

> Would it be possible that when tsc parses (Gen<A, B>) => string,

I don't know whether it is possible without parsing conflict before thorough mulling. It requires a proposer to bring out a viable algorithm.

**Comment by pelotom** [comment] 2017-02-20 19:44
The requirement to give names to symbols that you will never subsequently use is one of TypeScript's biggest syntactic warts. I think it's worth rectifying even at the expense of breaking changes.

**Comment by mhegazy** [comment] 2017-04-27 22:58
As noted by @HerringtonDarkholme, this would be a breaking change.

**Closed by mhegazy** 2017-04-27 22:58 UTC
