### ISSUE TITLE
Object destructuring named `exports` conflicts on targeting `commonjs`

### ISSUE THREAD

**Issue by JounQin** [microsoft/TypeScript#34693] opened 2019-10-24 02:33 UTC
**TypeScript Version:**  3.7.0-beta

**Search Terms:**

Object destructuring exports

**Code**

```ts
export interface CopyOptions {
    targets?: Array<{
      src: string | string[]
      dest: string | string[]
      rename?: string | ((name: string, extension: string) => string)
    }>
    verbose?: boolean
    hook?: string
    copyOnce?: string
}
  
export const COPY_OPTIONS_KEYS: Array<keyof CopyOptions> = [
  'targets',
  'verbose',
  'hook',
  'copyOnce',
]

export const isCopyOptions = (
  copies: Record<string, string> | CopyOptions['targets'] | CopyOptions,
): copies is CopyOptions =>
  !Array.isArray(copies) &&
  Object.keys(copies!).every(key =>
    COPY_OPTIONS_KEYS.includes(key as keyof CopyOptions),
  )

export const config = ({ exports = {}, copies: CopyOptions = [] }) => {
    return isCopyOptions(copies)
}
```

**Expected behavior:**

No conflict of `exports.isCopyOptions`

**Actual behavior:**
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.COPY_OPTIONS_KEYS = [
    'targets',
    'verbose',
    'hook',
    'copyOnce',
];
exports.isCopyOptions = (copies) => !Array.isArray(copies) &&
    Object.keys(copies).every(key => exports.COPY_OPTIONS_KEYS.includes(key));
exports.config = ({ exports = {}, copies: CopyOptions = [] }) => {
    return exports.isCopyOptions(copies);
};
```

**Playground Link:** 
[Playground](https://www.typescriptlang.org/play/index.html?module=1&ts=3.7-Beta&ssl=1&ssc=1&pln=30&pc=1#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgYQjAE8B5MGBCJAZzgG8AoOFuGTKAc2BhoH4AXHACCUKJmIAeJq1Y0o2ITRhRknOAB84y1Uk4BtALrNZcACbBlSlWs3abeoydlRgSTAFtgg+7vVaACgD3L2s-ABo4UFRaKiQwtQBKOABeAD5fJOc4AF807IA3NAAjCBpvIVKIABtgTCRsgAsICABrHx01bOwiMiRcDodORhyTRlBIWDge2nh8UgAFAE0AfUWAFQBJUgA5AGUVgGkAUSW9oVFxKVbgYgh0Al7ySmoaDJS4fRMAcnYuHho33CPyKUFK5SBP2abUhLG+PRIpH6wEhxnG4Gg8BmykQNEIiIocToHwCJgRCEsQgASsAelAzJJOnpIkzOBktPiyITXvpfhxuLxvoY7JznkTgYkhOTLLjHgSXrRUvkWABCS4SAB0CBo6uIAWlNGSADIjSZSMUAFa0mAam7EGj6ogUmgqxIa4CgvV2pXZebLNYLLa7A4nM5a-rVACuFgd3swdDt9zlXIVhuBLESjHRkyxr1zSHQCHUJPoUQxsGJDBykQNQlF3MVHyMuWS6QY2VcMEjUCQuPrqcdYGdmdGQA)

**Related Issues:**

**Comment by rbuckton** [comment] 2020-12-16 00:50
This is essentially a duplicate of #33043 due to the conflict between the local `exports` and the outer `exports` needed for CommonJS emit.

**Closed by rbuckton** 2020-12-16 00:50 UTC
Labels: Bug, Rescheduled
