### ISSUE TITLE
Formatting of lines starting from `;`

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#16082] opened 2017-05-25 17:24 UTC
Well, this is the special case for people developing without semicolons, sometimes we need to do such trick:

```ts
const x = obj
  // next line we start with semicolon, not to get the error
  //typescript formatter inserts indent spaces before it
  ;(something as Type).doThis(...)
```

So, currently, typescript formatter inserts indent spaces before it. Can it be handled/changed?

**Comment by mhegazy** [comment] 2017-05-25 18:47
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/10392

**Comment by whitecolor** [comment] 2017-05-25 19:26
So it seems to be `Wont fix` or what?

**Comment by mhegazy** [comment] 2017-05-25 19:31
> So it seems to be Wont fix or what?

correct.

**Comment by whitecolor** [comment] 2017-05-25 19:58
So it is not possible to work it around any how?

**Comment by mhegazy** [comment] 2017-05-25 20:10
Other than putting the semicolon on the previous line, no.

**Comment by mhegazy** [comment] 2017-06-09 17:14
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-06-09 17:14 UTC
Labels: Duplicate
