### ISSUE TITLE
Proposal: preserve parameterized types

### ISSUE THREAD

**Issue by snytkine** [Microsoft/TypeScript#13067] opened 2016-12-20 20:37 UTC
Would it be possible to preserve parameterized metadata?

For a code like this one

```
class UserService {

@service 
getUser(id:number):Promise<User>

}
```

It's currently possible to get the value of design:returntype using reflect-metadata but the value is limited to Promise prototype

It would be very helpful to also somehow preserve the type of Promise as well. This would be very helpful for writing a library that generates documentation from code, possibly a swagger file from inspecting signatures of controllers or generates schema from a class.

**Comment by DanielRosenwasser** [comment] 2016-12-20 23:53
Closing as a duplicate of #3015.

**Closed by DanielRosenwasser** 2016-12-20 23:53 UTC
