### ISSUE TITLE
Typescript 5.0.2 does not infer type correctly with React.isValidElement

### ISSUE THREAD

**Issue by changwoolab** [microsoft/TypeScript#53348] opened 2023-03-19 08:35 UTC
# Bug Report

```tsx
import React from "react";

type B = {
  b1: string;
  b2: number;
};

export function type(input: React.ReactElement | string | B) {
  if (typeof input === "string") {
    return input;
  }

  if (React.isValidElement(input)) {
    return input;
  }

  return input.b1;
}
```

After running `tsc` in the console, I got this error.

<img width="944" alt="Screenshot 2023-03-19 at 5 27 09 PM" src="https://user-images.githubusercontent.com/64240134/226162868-d63a10bd-2e58-4cb8-83c0-e76f2de9cced.png">

But there was no error in VScode and type inference was working well
<img width="471" alt="Screenshot 2023-03-19 at 5 29 43 PM" src="https://user-images.githubusercontent.com/64240134/226162987-0e9ddbf3-7b06-4dd3-ab22-02aca526baa4.png">

Also, there was no error with `4.9.4`.

### 🔎 Search Terms

typescript 5.0, React, ReactElement, isValidElement, inference, deduce

### 🕗 Version & Regression Information

After upgrading to typescript `5.0.2` and running `tsc` in the console.

- This is a crash
- This changed between versions 4.9.4 and 5.0.2
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
import React from "react";

type B = {
  b1: string;
  b2: number;
};

export function type(input: React.ReactElement | string | B) {
  if (typeof input === "string") {
    return input;
  }

  if (React.isValidElement(input)) {
    return input;
  }

  return input.b1;
}
```

### 🙁 Actual behavior

Type of input at the last line was `B | ReactElement`

### 🙂 Expected behavior

Type of input at the last line should be `B`

**Comment by MartinJohns** [comment] 2023-03-19 08:43
This seems to be a duplicate of #53178.

**Closed** 2023-04-02 18:00 UTC
Labels: Duplicate
