### ISSUE TITLE
Discriminated unions do not work when discriminating on a tuple type

### ISSUE THREAD

**Issue by AaronFriel** [microsoft/TypeScript#56920] opened 2024-01-02 03:51 UTC
### 🔎 Search Terms

tuplenarrowing
discriminated union tuple

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type narrowing, discriminated unions

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=5.4.0-dev.20240101#code/PTAEDECcFNtA3AhpAlogRgG2gZ1AMwHtJQAXACzlN1NAGNEc51pNCB3AGlHbgYDsykAJ4JkaUikL88hfGUpMyhUEzgp5ifqLkLccfskgd6xGHVKZhAOgBQpYQAc4ANUSYArnAC8q0qn4AcwBuWzC6aRxaAGVofkl+VlBffg9MTFCHZ1BY+JREzGSyJ2hdXITWYNAQUHccFX8UaAATAC4c4QBbdEJMAAoAciY8goGASjDoAA9HYlosuAApev4AEUI6D0642l8Ab1tQUHRkdrdPaABtAF1QgF9Q2xqAQWLsmEcYYYTA0EdkSTuKx-ZBMZpiC54fJ6Wo9eBLaIAeQAcqBmhstjtWvYSqAAAqg6AAUXh8WSh1AAB9QAcjnSQRR2pcBidIANuKlutBINxyvlWLcKfSkBczu4vKF6XcKdTafSGeQmSzkOycjt+ZhBfKIV4xRcbpK6Q9wpFaP9IEwSVj8YSrWT9hSANb5NqgAYRTqObDUdkU-6M0DM1mqvZ3Wp4TksHlqkYCzgUkW6t2UdKEX1hxg2i3E0mkR41ADChE93tYohwzjoGmE+V+FDg-vIBEQKEweFIKkMkGM7BhC1AunrOug3HQHloOA8dDosGaUMEXZ7tb7uMHlAV2LlGlAfQWunNltz1kblwAjNdkt5fANI9yBqAAGQPkHZu2kY+ICiXABMF6vvj5AoxhpIVqjAaIpxnFocDsekIhkM1P0VQNlTZDktijXl1QKP8X0PHYPwoR56RqABVRIZmgCwWlAbljEgdoABVcQGc4vCpUA2Kua57xQCNCFoRgcBQQJDCwKgGhYrj7yISAgU48VoFgul4KiYc9XY3wDxzAjE2gKoanAFs2yYqTFI4ribl4-jBJwYTRIwbBlDeOBWMUmTiHkrjlOlaUnnAytq2XRBQA8fgUAAR3Y81aDXBskObVt207IwTCHfs4uHAcSCHRtNwpbc+m0t9CPIH8-yvGMKkwYC5SOMiKMrahwTo4hTOyAZLgAIlZLr0K5aNUnSC9qW63r0OG6zQH4ATw3ssSnI7Fy3TG5A+umjDuQmzUBmUo5VMQgMgxVfrMKqjVcOKo9G2IukGumJqaNahjQGYjquIsxSrNAPjptmoSRIWiTlrci4PLk9IFIuPbTAQ9Soc0vCdPiaw9MNXywnwMKLCkQQAEkcGebtEGEAkKAAaWgYQioBdotGEMZ2hin6I02kg5RgUgPEgQR-AlWw-LI4SglqZbAg8ZBwSWxc0vXDL5FyhL8GM5LptS3t0tXBX1z07KYTy2wt3kPoCaJuTSaQynqaugiT3PYCnyRkqT1-S8AOw1hatAmpokQbZaO7Yhw1hQh4Rhg6NxQ4NTq286cKKG2UZusISPAv24Ge4OMFDpTQIjvSNJ8J2jzRikMf817yF+9hiEdHBuECFBST7HAAFp-WoHnQEwFB0DkkQWZ+hCgRaOxbBQT05hpUBOk-OhyG4PFQDDfBjE6N1SDbjvuX4AZQjlWfSHnmnX1zMZrHYFAKD6PZI+OtD8WsW9o0AgVl+4E-8PiYDvAAPhA1OoAADqtccAAEIAD8ZAt6fk7oIX6jlgYyw1uuRstR+Dgl1icMEA5eaoNgTvcOpo76oVVM-LCsZNQJ1tNdJCt19rEILgjIuid3ylyOHcCY0ogA)

### 💻 Code

```ts
// Free variables for the test case below, we can try variations of these to see if any of these narrow correctly.
type Value = string;


const Sentinel = null;
type Sentinel = typeof Sentinel; // also tried: Symbol('sentinel')

export type JsonDocument = {
  bar: Value[];
};

// A type representing partially parsed values in the above JSON document:
type ParseEvent =
  | {
      path: ['bar', number, Sentinel];
      value: Value;
    }
  | {
      path: ['bar', Sentinel];
      value: Value[];
    };

const parseEvent: ParseEvent = {
  kind: 'complete',
  path: ['bar', {} as number, Sentinel],
  value: 'hello',
} as ParseEvent;

// Completely specifying the path fails to narrow the type of the value, but succeeds in narrowing the type of the path:
{
  if (typeof parseEvent.path[1] === 'number' && parseEvent.path[2] === Sentinel) {
    // Succeeds.
    const path: ['bar', number, Sentinel] = parseEvent.path;

    // Unexpected error: Type 'Value | Value[]' is not assignable to type 'Value' forall Value.
    const value: Value = parseEvent.value; // Fails: Type 'Value | Value[]' is not assignable to type 'Value' forall Value.
  }
}

// Specifying a unique part of the path fails to narrow the type of the value or the path:
{
  if (parseEvent.path[2] === Sentinel) {
    // Unexpected error: Type '["bar", number, null] | ["bar", null]' is not assignable to type '["bar", number, null]'.
    const path: ['bar', number, Sentinel] = parseEvent.path;

    // Unexpected error: Type 'Value | Value[]' is not assignable to type 'Value' forall Value.
    const value: Value = parseEvent.value;
  }
}

function IsArrayPathKey(part: any): part is number {
  return true;
}

// Using a type guard to narrow the type of the path fails to narrow the type of the value or the path:
{
  if (IsArrayPathKey(parseEvent.path[1]) && parseEvent.path[2] === Sentinel) {
    // Same error as above.
    const path: ['bar', number, Sentinel] = parseEvent.path;

    // Same error as above.
    const value: Value = parseEvent.value;
  }
}

// This works, given the ts-pattern library is installed.

import { match, P } from 'ts-pattern';
{
  match(parseEvent).with({ path: ['bar', P.number, Sentinel] }, (parseEvent) => {
    // Works!? ts-pattern is able to narrow the path and value based on the pattern.
    const path: ['bar', number, Sentinel] = parseEvent.path;

    const value: Value = parseEvent.value;
  })
}
```

### 🙁 Actual behavior

Discriminating on the `parseEvent.path` value, a tuple type, in a conditional expression, the `if` conditions of the code above, does not work to narrow the type of the entire value. 

When discriminating on the entire tuple, the `parseEvent.path` type is narrowed, but `parseEvent.value` type is not.

When discriminating on a part of the tuple, e.g.: the 3rd element of the tuple which exists in one of the unioned types and not the other, neither the types of `parseEvent.path` nor `parseEvent.value` are narrowed.

### 🙂 Expected behavior

The code above should have no errors, and using a tuple as a discriminator should largely succeed.

**Comment by fatcerberus** [comment] 2024-01-02 04:05
Mostly a duplicate of https://github.com/microsoft/TypeScript/issues/48500#issuecomment-1085063454

> The current rule is (consistently, I guess?) that a potential discriminant property has to have at least one literal type in it to be a discriminant.

A tuple is not a literal type, even if it contains literal-typed elements.

**Comment by AaronFriel** [comment] 2024-01-02 05:34
> A tuple is not a literal type, even if it contains literal-typed elements.

Is this documented and/or considered not a bug?

**Comment by MartinJohns** [comment] 2024-01-02 10:36
> Is this documented

GitHub issues act as documentation as well.

**Comment by RyanCavanaugh** [comment] 2024-01-02 16:55
The documentation never claims that referenced-typed discriminants are supported. Not sure how we could document every negative statement about the language.

**Comment by AaronFriel** [comment] 2024-01-02 19:55
@RyanCavanaugh This is also the case if all of the entries in the tuple are literals. I don't think a referenced type is necessary:

```ts
type Union =
  | {
      discriminator: ['foo'];
      value: string;
    }
  | {
      discriminator: ['bar'];
      value: number;
    };

let foo: Union = {} as any;
if (foo.discriminator[0] === 'foo') {
  foo.discriminator; // ["foo"]
  foo.value; // string | number
}
```

**Comment by fatcerberus** [comment] 2024-01-02 19:58
@AaronFriel Thag case would be covered by https://github.com/microsoft/TypeScript/issues/18758

**Comment by AaronFriel** [comment] 2024-01-02 22:12
It does seem like #18758 is closer in spirit to this issue. I think this issue makes a slightly different, more specific ask. It's a bit of a blocker for a nice JavaScript/ES and TypeScript friendly API for the library I've just published, [`fn-stream`](https://github.com/AaronFriel/fn-stream).

**Closed** 2024-01-05 01:28 UTC
Labels: Not a Defect

**Comment by AaronFriel** [comment] 2024-01-05 22:45
Well that's unfortunate, is there a better label for this so that it remains an open issue?
