### ISSUE TITLE
Missing variance inversion in rest-parameters type inference (extends clause)

### ISSUE THREAD

**Issue by witemple-msft** [microsoft/TypeScript#47191] opened 2021-12-18 19:59 UTC
# Bug Report

This is a quirk that I first heard of in the TypeScript discord, and I've just been doing a little writing about variance in TypeScript and revisited and found that it's a real soundness issue in the compiler with rest-paramters, but moreover it's inconsistent with the way individual parameters are handled.

### 🔎 Search Terms

"inference", "contravariance", "variance inversion", "extends clause", "rest parameters"

I found some issues that seemed like they might be related, but didn't see anything that exactly matches this situation.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, including: **12/18 Nightly, 4.5.3, 4.0.5, and 3.3.3** (all TypeScript playground).

### ⏯ Playground Link

[Playground link with relevant code.][pg] This playground is heavily annotated and compares the buggy code with other code that doesn't exhibit the bug (but is logically the same).

### 💻 Code

The elemental code sample is this:

```ts
// All functions under the sun are assignable to this constraint.
type AnyFunction = (...params: never[]) => unknown;

function test<F extends AnyFunction>(...args: F extends (...params: infer P) => unknown ? P : never): number[] {
  // `args` should not be assignable to `number[]`, but it is!
  return args;
}
```

### 🙁 Actual behavior

I explain it more in detail in the playground link, but the basic problem is that the constraint of `P` in the above snippet is computed as `never[]`. It should be `unknown[]`. This leads to a soundness issue where the function could be instantiated with any function in the universe, but the variance is backwards and so they are treated as if they are nothing and therefore assignable to anything without an assertion.

In general, when rest-parameters of some function type `T` are inferred in an `extends` clause, the inferred parameters are erroneously constrained to the parameters of _constraint_ of `T` itself. That misses a variance inversion and results in the soundness issue. To show that the constraint of `P` comes directly from the constraint of `F`, another example:

```ts
function f<F extends (...params: string[]) => unknown>(
  ...args: F extends (...params: infer P) => unknown ? P : never
): (string | number)[] {
  // This is now an obvious error: type `string[]` is not assignable to `number[]`
  const n: number[] = args;
  // But this is not, even though it should be:
  return args;
}
```

This does not produce an error (though there should be one) because the constraint of `P` is computed to be `string[]`. However, that's not right. The constraint over `F` isn't that its parameters are assignable to `string[]`, _but that `string[]` is assignable to its parameters_. If I instantiate the type with rest parameters that are `(string | number)[]`, then I will end up assigning `(string | number)[]` to `string[]`, hence the soundness issue.

### 🙂 Expected behavior

When the following form of `extends` clause appears where `T` is a generic and `P` are rest-parameters that cannot be immediately distributed to named parameters, the constraint of `P` should be `unknown[]` regardless of the constraint of `T`.

```typescript
T extends (...params: infer P) => any
```

There are no constraints about what `T`'s parameters are assignable _to_, only that some _other_ type must be assignable _to them_). The only constraint of the rest-parameters is that they must be an array type, so logically they must have the widest possible array constraint: `unknown[]`.

[pg]: https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&allowUnusedLabels=true&noUnusedLocals=true&noUnusedParameters=true&esModuleInterop=false&declaration=false&target=99&noFallthroughCasesInSwitch=true&pretty=true&exactOptionalPropertyTypes=true&useUnknownInCatchVariables=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true&ts=4.6.0-dev.20211218#code/PQKhFgCgAIWhie0DqALAhgF2gSWgUQA8AHAUwGNNSATKWaOuAAyoGdMnoBLV6daAGYBXAHaUuAexHRMGbD2gBzUiNIAnLuWgSAbuuhMAYkwB0B4917kp7Nei6rqMiQYCCIgJ6HR4qUwA00ADuqJqolgYAFCYxxOh2ALasAFzQqnpqANoAugCU0AC8AHzQogDWIhJBIpyRsqTQCeiEXE0ANoyCPpiS0pgeZNAAtEN8bW1dYj02fGoN6KysXIoi6ABGbQ2YLrIK-WS5ZgAqqOqkAhJz5pwK1iK29o7O0GsNDuzoIj1YNMFcsnxPJNfH0Bm8+qdOqIuBlWKQTJ1OixSOwbiIBOpePUZGDtAJuJheHFEqQqGpeEwAAqcARqCQJa7QSJ4IIaKjaITYbEODFzMQNchtdBCOGBNacgnBS5lLGnaCsdAJBoihyKGRyqnxRWkzGcfakQ6dE4NJikQhUETUVicQXCuERSoiIYCdBtJYCLjrTbQahCLY7OUuyjqrDqhoAfTuDwcmHDeMZCgWSxWXv9YYMZotVptQpF8MRMDgAGUHOQTdSIjz1HMnLT6enlKoNFp9YFsdYEsQuJs1I0Rdg8+nIzZMHYY3GJPiqZwQipoB3iJzVemk8tVmtu-8PPHp4FWC5ZyJOquVsvp89+DpXX7Av8-uN56dyGUQ1y5cP7qPHrGdxXE4s11TZ5ZFDK82j9AByLEwQRQsGDggAJKpSAyNs5SjL8YwdCRsAXTlfmsNQ5koNoPGOdD6S7HsZDmLAKQrBZuHxO8FHDE9129bYDHSdQcgCF4JWxUc-RxMghnqS5SU0V1OgwscvgiEDsHDJgeKybIbl4digK46dwzMAAZCRFGk8YPDQho5lYIQ2nkWVQ3bEd5OwScDArVhUAkGynEqbBXm4lDeI0sUJSYcpKmqPjYPoI0KM7bt9HY+i9RcVShASV51NqbE5kwIQ1FBQZXORVF8iCf5PIlT5tx4az8zg2KzgifgElq5crw0T4y24ERYV6YJTmkfgrOwYltTJUS3l4KsiN+OsGX4Rt1E0aK4E6RBcDEGweAtcgPALegcHxIJwXYUh0CcOTHkZXTIjGhJUjU-JilKEQKiqGomS4Ex4UBbdhCmfrXKkeY1EUdKVEwfJPicUdty4mb031NzOFc8MpFI9MPXJTBOnunU1HDCz50ohLe3QSghFdTHqAkFEet5Axwo+zhGOxc4MXEPQSc-Zzf1MaATgUW5LmIzBAhh+V8tITGuHxdmBE5npuaumNOlc6rtFUaB8YmhQwreiKagsiEGg5ihlYFJzv3jEahl1-QZpUbqPK8tonH8g33sijTVvg+hjWgM1FWITZeFeNoqh9UgEmt9lPKCdNVYUkXO3wy7RYtzGLl7AGQR56Mvl4YHtficGlS+QJAukQ90wd8lZlIToekUVBMEx5OaD99akCQxOuI9QgCWSA64BwdFq2XfgQgkb0Rp1rUlQm5H5r4JQVGWrQjBta2HF+Lj-P4PPpmkV3vOgNi2iCdAPFYOMPC4GWnH4ZGlIic2uZl7cvaNvj-E6OYih4jUDDsXeWFFeY22KsYKCC8SRklYGYVwwIT6TVfHwcgZZiCEiZobD6fFBCXDgeNTElgxTbmoOcBw-xegSwAimDYaZqqdGPv1euBdMKV3lAGK2kCsLQKYLA+uvAEj9heCaZmPtTCMGAFAKAoAIBwQALLNFaK6FB-V9RIKBKwqQaD-zJg4mmJg7gvDdF6NIwssjIDI1Md4QGeiChMhiCYe6KQ0iBXUs9EokiRAAG45GQAUZ0AAQkIRQigPAAEJNq8g0CINU2IZ5zxRKNReBNoKDAUK1ACCS14dU9PyHqfUpBRNHtAAAml5ecnwg56D6GoeGLhyAYASVsOUuV8qFTTPuJeoQ8ky1FICZ+vBI55MYv8WBtT4h2HhricqsgvLYCPlwQgvx4hbiZL5NeeVQ4GlvNgcqD52KrWsbovoqSAA8hgg7mhUFaaAdjzFSCKNEGIZd3E3MzPc3gbzXGL3cYjSk3jXre2kAAfmgJSaAqRfG5EeulTKORoAAG86DQGAMAAwHzOBn3dmkHC4i+D0KMc8NKGUgr8XFPIOyZSYDQE6QVWYihWABMgAAX0CZi6AAApMRXFXb9zkOqBQtEzLNW4aIagqhFiWDqrBbleBqBcGlRBbAGBuZcSaGUeYQJkZJnUCfRBgs4pUX0EciYGBiBUW3JsbASpiWGIMJkWwqoNLATlMI+M2IlrNiZCEMIERCJi1yIEeRWLqVI1xKwW+VAGQKEoRiH4Th3gqvaQ0c5A05x3nILU2kpAv6OrXICIOisLYwhNC60cbqUrcURZS2CbBMCXMiIQVIrqEkgt8a8gARKccYEge25DZfIsAnQVEtHaGgnOGiZgl1BuXSG5EGhwjuE4Ep0g8xaSGmDCGClWDEFotQU5UBbGeHsSCAA8qoVwu6K7YCcXdRej1PFdrwdUNlZ6zEOJENe0gt7F1fAAEqpMKM42IALUiZDUnkQoPj33+MCaOxR9B4AAEZUiUjpL6Ms26g5ESIYxM0ZBKC-AWeEfgSwEnejLnuzAJ7ICZqbX+65tysy8CeT+v9AG6OvLLqkL5dzLS-PuqkIFb6wXQEhdC2FCH4VpHrb2NF9LGU7sUH4jFWL8AEbUDEo4uIf4s2wssklOlUoiEU5YzlkBkPrQAEypFcG6Fwh6JA4fprU6shHeDEYtr8FU4z5Sqho3eyGxKdlCD2T1dMds3E6wkEsVBrlHJ8K+AxpjqS-0gfYKx75wnHnnueb+m9oXgOpL42DATbGflMlEwzfQwK4OgqNlJqFMLmsfXkxZilSn0WqeZWy6ztm4LwAAMyOeczrbDQhcMlq8+THzJA-NOAC2qSjwWF10Y4XzN+wsJ6zRTabGQkXvTEASzQvRrl560fvYgmRUAMvsD-ePXk2Xm2CfYwV79V6SuAcwBVxQVW8sPL+XVzIQLYMvV8a1mTHXqhdcU6ivrpIukDagENoJY6RsABYJv7im25mbHnpDzfC750j1BAirZeDhCjx2ouxfSQg7bNtJa7f27KTb97osvxOw0M7iXejdzgkLKw9INwyoQHZ4ZCBRvpaKzITLqg3vuGoG9l76hctCYeZxn7-7SuYDewDoH2vfkuLBxDiTLXpPtbhQinrSOVMo6ZWXQbQA

**Comment by ahejlsberg** [comment] 2022-01-11 18:35
This is effectively a duplicate of #26945. It would be nice to do better here, but it would require complex changes. In an ideal world we'd reason about both upper and lower bounds of type variables and use the appropriate bound based on the variance of a location when creating constraint types. However, we only track upper bounds and we're not currently equipped to understand the variance of a location during type instantiation.

With respect to the examples in this PR, the reason some of them behave correctly is that when computing the constraint of a distributive conditional type, if the resulting type is `never`, we simply reject that constraint. However, we don't do that for other `never`-ish types such as `never[]`. You can observe this if you rewrite one of the examples to:

```ts
function test<F extends AnyFunction>(...args: (F extends (...params: (infer P)[]) => unknown ? P : unknown)[]): number[] {
  return args;  // Error
}
```

But this is obviously more of a band aid than a complete solution.

**Closed** 2022-01-15 18:00 UTC
Labels: Duplicate
