### ISSUE TITLE
HTML/C-like #include statements

### ISSUE THREAD

**Issue by zilqarneyn** [microsoft/TypeScript#57920] opened 2024-03-24 10:45 UTC
### 🔍 Search Terms

include

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

So far as I understand, both JavaScript and TypeScript lack any HTML-like (& C-like) #include statement, & that causes lots of inconviences. To check/translate a set of files (mixed set of related JavaScript-&-TypeScript or a few TypeScript files).
 
To emulate how HTML includes multiple JS files, all the includes may need to exist only at the top of that .ts file (may mix-along with import statements, but before any other emittable code, unless concatting all the includes as a single file in the output). 

 Alternatively, TypeScript may read .html files, & for every <script> statement, check whether there is any xy.ts for that src="xy.js", and if none, then accept it as purely JavaScript, while processing the others from the corresponding .ts files.                                                                                                                      

When I have to refer to functions/etc. from a library (tone.js, etc), I would have to write a declaration for every Tone.js function/etc. that is referred from that .ts file.                                                                                                   

Alternatively, perhaps you could write & publish your TypeScript, with module-based syntax. However, anywhere below "tsc --target es6 ...", it breaks the web browser, because tsc produces code with "require" statements (acceptable for Node.js, not for web browsers).                                                                                                  

Furthermore ironically, lacking such include facility, is inconvenient within TypeScript, too, because if I have to refer to functions/etc. that exist in other files, then I have to declare them each and every file where I use them, because there is no (C-like) capability to declare them in one place (some .h file) that would be includeable from any of the using files.

### 📃 Motivating Example

Lacking such #include statement capability, I splitted a Tone.js-&-Three.js project/demo into two files, Tone.js portion as (no modules) JavaScript while the Three.js portion as JavaScript-or-TypeScript module, & told in the latter (TypeScript), through                            declare function ToneDraw_scheduler(renderNext : (renderer : THREE.WebGLRenderer, scene : THREE.Scene, camera : THREE.Camera, cube_ : THREE.Object3D) => void, renderer : THREE.WebGLRenderer, scene : THREE.Scene, camera : THREE.Camera, cube_ : THREE.Object3D, div4writing : HTMLDivElement) : void;  
                                                                                                                                                   
 The other portion has to remain as JavaScript because it cannot include the "tone.js" (the library file that HTML includes).

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

1. JS for HTML pages
2. Cannot verify the portion necessarily remaining as JS.
3. I keep the JS portion opaque, & only HTML lists the "tone.js" & JS portion.

**Comment by jcalz** [comment] 2024-03-24 11:37
>  This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

It sure looks like most of your proposal is exactly a runtime feature. That’s essentially a non-starter here, and you’ll get a “go propose this as a JS feature and we’ll support it once it reaches Stage 3 of the TC39 Process”.

**Comment by MartinJohns** [comment] 2024-03-24 11:39
This is out of scope for TypeScript. Anything that requires additional code to be emitted (beyond down-leveling and legacy features) is a no-go.

I've definitely seen a duplicate of this, but I can't find it right now. `include` is a too generic search term.

> because tsc produces code with "require" statements (acceptable for Node.js, not for web browsers).

TypeScript does what it should do. If you're using modules, it needs to output module code. It doesn't have to be `require`, it can also be `import`s (which I think modern browsers understand now). It's up to your configuration.

**Comment by zilqarneyn** [comment] 2024-03-25 08:33
> > This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
> 
> It sure looks like most of your proposal is exactly a runtime feature. That’s essentially a non-starter here, and you’ll get a “go propose this as a JS feature and we’ll support it once it reaches Stage 3 of the TC39 Process”.

That confuses HTML/C includes (that are absolutely static, compile-time features), and JavaScript-style (AJAX/eval/etc., also known as "dynamic HTML" but such run-time code is not necessary nor any advantage here).

**Comment by zilqarneyn** [comment] 2024-03-25 08:42
> This is out of scope for TypeScript. Anything that requires additional code to be emitted (beyond down-leveling and legacy features) is a no-go.
> 
The term "C includes" may have suggested your comment, but there are no macro facilities (no macro expansion, thereoff) in TypeScript. Strictly for on-the-fly compile-time static analysis, informed by the included declaration files. That is, _including_ is not for concatting files nor emitting something extra. Simply for declarations, & thereby, knowing/including the pre-existing library (such as Tone.js) is for informing TypeScript what the .TS file is referring to. Just for referencing, not emitting/concatting.

**Comment by IllusionMH** [comment] 2024-03-25 10:38
Isn't that what `/// <reference... >` does?
https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-

Or approaches linked at the end of this section.

**Comment by zilqarneyn** [comment] 2024-03-26 07:47
> Isn't that what `/// <reference... >` does? https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-
> 
> Or approaches linked at the end of this section.

They may sound similar, but they work differently/bizarrely, although extendable/debuggable (1) to include/refer/know both .d.ts files & .js libraries (without transforming either to any runtime-loadable file, maybe except (as already tsc seems to do) transforming .d.ts files to .js files when the including .ts file is module-based), (2) referrable from not only module/import/export based .ts files but also from other .ts files (& not converting them to module-based by  emitting import/export statements into those non-module-based ones).                                                                                              

BTW, furthermore, <reference lib=.../> sounds like limited to only built-in (not user-defined) libxyz.d.ts files. The <reference path=.../> of TypeScript behaves bizarrely (when attempted to refer to a JS library, or in general). (1) I simply referred to Tone.js and then tsc told me that it is a .js file and I may use it with the --allowJS option, (2) when I did that then tsc told me that processing that file would overwrite the original file (& suggested hacking with tsconfig). Now, what is the sense of trying to compile/overwrite a referred file along with the referring file? If it were a .ts file, tsc would simply convert it to a .js file, but why? It should remain as is, & only included/referenced in compilation phase, for declarations/prototypes. Furthermore, when I simply rename Tone.js to Tone.ts, tsc trashes by dumping all of Tone.ts to the terminal/screen.                                                                                                                            

The way I suggest, seamlessly integrates all three of the types { (1) module-based .ts files, (2) global-scope .ts files that do not refer to any .js, (3) global-scope .ts files that refer to .js libraries }. Ironically, without this, a claim (or, two) that TypeScript loves to make, is/are actually (self-woundingly) very downgraded. One big claim is that, any JS is already TS, & that you may include TS extras little by little, at your own pace. However, until you convert your global-scope JS to module-based JS, that claim is irrelevant. (The other major claim is down-leveling things, despite refusing/disgracing the global-scope JS legacy almost completely. Where you cannot even set a foot, you cannot sell anything.)                                                                                              

One commenter suggested that "imports" has support from browsers, but the documentation at mozilla does not seem to list that ( https://developer.mozilla.org/en-US/search?q=Imports ), & therefore I do not know since when (if any) browser(s) started supporting it. Therefore, I prefer how I had factored a .js to two portions, to make one of them usable with modules/TypeScript.

**Comment by zilqarneyn** [comment] 2024-03-26 07:48
> It sounds like you're just talking about a module bundler, of which many exist already. TS isn't a tool for doing that; it's a typechecker

I do not use module-bundlers (at least, so far), & not asking TypeScript to "bundle" anything. Simply, while doing the type-checking of a .ts file, TS should know what declarations (functions/etc.) have been defined in other files.

**Comment by fatcerberus** [comment] 2024-03-27 02:03
> TS should know what declarations (functions/etc.) have been defined in other files.

It already does know that.  It sounds like you have global declarations in files that TS is incorrectly treating as modules, which just means your project is configured incorrectly.

As for module support in browsers:
https://caniuse.com/?search=modules

Supported in Chrome since 2017 and Firefox since 2018.

**Closed** 2024-03-30 01:23 UTC
Labels: Suggestion, Out of Scope
