### ISSUE TITLE
different path resolving behavior on unix and windows

### ISSUE THREAD

**Issue by stepancar** [Microsoft/TypeScript#5016] opened 2015-09-29 13:56 UTC
hello!
see screen
on windows i haven't any problems, but on unix atom, and ts loader emits errors. I think that its compiler mistake.
windows allow use not caseSensetive strings 
![screenshot_5](https://cloud.githubusercontent.com/assets/2854910/10166070/13f04c78-66cb-11e5-8400-d24ff7c8a97e.png)

**Comment by mhegazy** [comment] 2015-09-29 16:43
looks like a duplicate of  #4719, #3626 and #2011. the compiler is case-insensitive on windows, but case-sensitive on *nix systems. we can not make it case-insensitive all the time, but we can make it case-sensitive when you set a flag, this way you get the same errors on all systems.

**Closed by mhegazy** 2015-09-29 16:43 UTC
Labels: Duplicate
