### ISSUE TITLE
Private properties assigned in constructor disappear from object

### ISSUE THREAD

**Issue by Hitulya** [microsoft/TypeScript#60735] opened 2024-12-11 03:44 UTC
### 🔎 Search Terms

constructor properties assignment

### 🕗 Version & Regression Information

5.7.2

### 💻 Code

Issue.ts
```ts
export class Issue {
  string2 = this.string1 + "b";
  constructor(private readonly string1 = "d") {}
}
```
main.ts
```ts
import { Issue } from "./Issue";

const _1 = new Issue();
console.log(_1.string2);
```

### 🙁 Actual behavior

Output is "undefinedb"

### 🙂 Expected behavior

Output should be "db"

### Additional information about the issue

I used some class from my previous project, it didn't work correctly. After some investigation I came to this issue.

repo: https://github.com/Hitulya/ts-private-property-undefined-issue

**Comment by jcalz** [comment] 2024-12-11 04:29
Presumably a duplicate of #45995 and #55132, but the relevant config for the bug report seems to be hosted in your own repo instead of here in the bug report.

**Closed** 2024-12-14 01:32 UTC
Labels: Duplicate
