### ISSUE TITLE
Give autocompletion for union types

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#9389] opened 2016-06-28 11:07 UTC
**TypeScript Version:**  Master branch (fetched on June 25)

**Code**

```ts
interface ScrollOptions {
  behavior: string;
}
declare function scrollIntoView(arg?: boolean | ScrollOptions): void;

scrollIntoView({
  b // no autocompletion
})
```

**Comment by DanielRosenwasser** [comment] 2016-06-28 19:26
Is this a duplicate of #6405?

**Comment by mhegazy** [comment] 2016-06-28 21:42
thanks. i looked for this one and could not find it.

**Closed** 2016-06-28 21:42 UTC
Labels: Bug, Duplicate
