### ISSUE TITLE
When combining the same type, the specific type before combining is still provided

### ISSUE THREAD

**Issue by xushengfeng** [microsoft/TypeScript#59269] opened 2024-07-14 17:36 UTC
### 🔍 Search Terms

literals, union

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

when we use union types, editor can't provide any suggestions.
```ts
type a = "a" | "b" | string
// typeof a:string

let v:a
v = "a" // ✔ but without suggestion
v = "other" // ✔
```

If we remove `string` from the union type, we wouldn't be able to set `v` to any other value.

```ts
type a = "a" | "b"
// typeof a:"a"|"b"

let v:a
v = "a" // ✔ with suggestion
v = "other" // ❌
```
I hope editor can give suggestion about "a"or"b"

### 📃 Motivating Example

we can give optional value suggestion to user, but user can use other type without error

### 💻 Use Cases

1. What do you want to use this for?
	like `document.body.style.borderWidth='inherit'`，editor can give 'inherit'|'thin' and so on, but other string can be set.
2. What shortcomings exist with current approaches?
	editor can't give more suggestions
3. What workarounds are you using in the meantime?
	none

**Comment by MartinJohns** [comment] 2024-07-14 17:55
Duplicate of #29729. A workaround is to use `string & {}`.

**Closed** 2024-07-14 23:41 UTC
