### ISSUE TITLE
Methods in classes are anonymous function on es3/es5 target

### ISSUE THREAD

**Issue by TobiasSekan** [Microsoft/TypeScript#16141] opened 2017-05-30 09:37 UTC
When target is es3 or es5 method inside classes will reduced to anonymous function so it is impossible to get the name of the function, when it is used as parameter.

**TypeScript Version:**  2.2

**Code**
```ts
export class MyClass
{
  public MyFunction(myParam: string)
}
```

**Expected behavior:** (named function)
```ts
    var MyClass = (function () {
        function MyClass() {
        }
        MyClass.prototype.MyFunction = function MyFunction(myParam) {
            return myParam;
        };
        return MyClass;
    }());
    exports.default = MyClass;
```
**Actual behavior:** (anonymous function)
```ts
    var MyClass = (function () {
        function MyClass() {
        }
        MyClass.prototype.MyFunction = function (myParam) {
            return myParam;
        };
        return MyClass;
    }());
    exports.default = MyClass;
```

**Function to get the method name**
(parameter has type any, because the name attribute is missing in Function type)
```ts
    /**
     * Return the name of a given function
     * @param {Function} functionSource The function
     * @returns {string} The name of the function
     */
    public static GetFunctionName(functionSource: any): string
    {
        if(functionSource.name)
        {
            return functionSource.name;
        }

        let funcNameRegex = new RegExp(/function (.{1,})\(/);
        let results       = funcNameRegex.exec(functionSource.toString());
        let result        = results && results.length > 1 && results[1];

        if(!result)
        {
            funcNameRegex = new RegExp(/return .([^;]+)/);
            results       = funcNameRegex.exec(functionSource.toString());
            result        = results && results.length > 1 && results[1].split(".").pop();
        }

        return result || "";
    }
```

**Comment by mhegazy** [comment] 2017-05-30 18:57
Duplicate of https://github.com/Microsoft/TypeScript/issues/5611

**Closed** 2017-05-31 08:09 UTC
Labels: Duplicate
