### ISSUE TITLE
JSON.parse generic

### ISSUE THREAD

**Issue by PumpedSardines** [microsoft/TypeScript#44603] opened 2021-06-15 19:57 UTC
# Suggestion

The JSON.parse function should utilize a generic.

## 🔍 Search Terms

JSON parse generic

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [*] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [*] This wouldn't change the runtime behavior of existing JavaScript code
* [*] This could be implemented without emitting different JS based on the types of the expressions
* [*] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [*] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Adding generics to JSON.parse

## 📃 Motivating Example

```ts
interface MyInterface {
     test: string,
    example: number
}
const myArr = JSON.parse<MyInterface[]>(fetchResponseText);

```
Removing refrence
```ts
interface MyInterface {
     test: string,
    example: number
}
const myOtherArr = JSON.parse<MyInterface>(JSON.stringify(myArr));

```

## 💻 Use Cases

Make it easier and more convinient to parse JSON.

**Comment by nmain** [comment] 2021-06-15 20:08
I can't find a precise issue that this is a duplicate of, but similar requests have been rejected before:  https://github.com/microsoft/TypeScript/issues/44000.

Generic type parameters that only appear in the output position of functions are just assertions in disguise, so why not just write that?  It only costs two characters more.
```
JSON.parse(s) as T
JSON.parse<T>(s)
```

**Comment by MartinJohns** [comment] 2021-06-15 20:39
This would just give people the false impression of type safety.

Instead the type should be `unknown`, but that was deemed a good big of a breaking change.

**Comment by MartinJohns** [comment] 2021-06-15 20:41
Duplicate of #30220. Used search terms: `json.parse in:title`

**Closed** 2021-06-15 20:53 UTC
Labels: Duplicate
