### ISSUE TITLE
ATA: Only download typings for dependencies in top-level package.json

### ISSUE THREAD

**Issue by octref** [microsoft/TypeScript#12044] opened 2016-11-04 06:43 UTC
When I was verifying ATA in VSCode, I found it downloaded typings for non-top-level deps.

I only added ~20 packages to my package.json, but in my cache I found:

![image](https://cloud.githubusercontent.com/assets/4033249/19996556/a139b9d2-a21d-11e6-86e9-4d7e042bf43a.png)

IMO only typings for dependencies in package.json should be downloaded. This is also one of the factor that caused npm overload.

**Comment by aluanhaddad** [comment] 2016-11-04 10:26
This is arguably correct behavior. See related discussions like #11917

**Comment by mhegazy** [comment] 2016-11-04 18:40
> This is also one of the factor that caused npm overload.

I do not believe this accurate. The npm issue was not caused by valid package installation, but rather by checks for non existing packages. this is based on the information the npm team has shared with us.

We have added a fix for this in [TypeScript 2.0.7 release](https://github.com/Microsoft/TypeScript/releases/tag/v2.0.7) to address the non-existing package issue. 

> I only added ~20 packages to my package.json, but in my cache I found:

Please note that this is a machine-wide cache. so all projects will contribute to the cache and will use files from the cache if they exist.

**Comment by octref** [comment] 2016-11-04 18:44
> The npm issue was not caused by valid package installation, but rather by checks for non existing packages.

Say you have a project that has 10 deps, each of them depends on 10 other deps.
For the 100 indirect deps, wouldn't TS need to check which of them have typings?

**Comment by octref** [comment] 2016-11-04 18:52
@mhegazy I'll just follow #11917 and maybe you can close this as a duplicate. Thanks!

**Comment by mhegazy** [comment] 2016-11-04 19:46
I do not think this is covered by #11917. the automatic type acquisition happens before there are `@types` packages. it is what acquires these @types packages. so there is a relationship but they are not the same.

Let me ask why you feel this behavior is not correct? do you see typing lags? or it is just concern about disk space?

**Comment by octref** [comment] 2016-11-04 20:29
Because it downloads unnecessary typings, that might take very long to finish, depending on internet connection.

For example, for https://github.com/kriasoft/react-starter-kit

```
react-starter-kit > ls -la node_modules | wc -l
     927
```

As its package.json has only ~30 packages. Downloading 30 typings should be enough to drive intelliSense.

One concern I have is, although I don't know for sure, my guess is all typings are downloaded with same priority. I'd prefer if typings for deps in package.json can be downloaded first so we can light up intelliSense faster.

On the VSCode side, we are also interested in adding visual indication to the progress of ATA. Instead of showing progress for downloading ~900 typings, showing progress for the ~30 required typings makes more sense.

**Comment by RyanCavanaugh** [comment] 2019-09-18 23:34
This isn't desirable (typings with unresolved dependencies will have errors and other problems), let alone possible given how npm works (there isn't a way to install a package without its dependencies).

**Closed by RyanCavanaugh** 2019-09-18 23:34 UTC
Labels: Working as Intended
