### ISSUE TITLE
Use slice instead of for loop when initializing rest parameters

### ISSUE THREAD

**Issue by charlespierce** [Microsoft/TypeScript#20308] opened 2017-11-28 21:15 UTC
**TypeScript Version:**  Local build of `master` branch.

When transpiling Rest Parameters for ES5 and below, the generated initialization uses a `for` loop to read the `arguments` object. This can be made simpler by using `Array.prototype.slice` to generate a copy of the relevant section of the array.

**Code**

```
function foo(x: number, ...rest: any[]) {
    return x * rest.length;
}
```

**Expected behavior:**
```
function foo(x) {
    var rest = Array.prototype.slice.call(arguments, 1);
    return x * rest.length;
}
```

**Actual behavior:**
```
function foo(x) {
    var rest = [];
    for (var _i = 1; _i < arguments.length; _i++) {
        rest[_i - 1] = arguments[_i];
    }
    return x * rest.length;
}
```

**Comment by RyanCavanaugh** [comment] 2017-11-28 21:26
Please search before logging new issues. Duplicate of #3219

![image](https://user-images.githubusercontent.com/6685088/33344986-9b7cd16e-d43f-11e7-8bb9-da9ff4847cce.png)

**Closed by RyanCavanaugh** 2017-11-28 21:26 UTC
Labels: Duplicate
