### ISSUE TITLE
TS2339: Property 'tooltip' does not exist on type '{ label: string; } | { label: string; tooltip: string; }'.

### ISSUE THREAD

**Issue by retorquere** [Microsoft/TypeScript#19186] opened 2017-10-14 19:27 UTC
**TypeScript Version:**  typescript@2.6.0-dev.20171014

**Code**

```ts
const cells = [
  { label: '1' },
  { label: '2', tooltip: '2' },
  { label: '3', tooltip: '3' },
  { label: '4' },
  { label: '5' },
  { label: '6' },
]
for (const cell of cells) {
  if (cell.tooltip) console.log(cell.tooltip)
}
```

**Expected behavior:**
That this compiles without error; the error message seems to indicate TS sees a call to cell.tooltip as valid but then forbids it in the second part of the error message.

**Actual behavior:**
```
tt.ts(10,12): error TS2339: Property 'tooltip' does not exist on type '{ label: string; } | { label: string; tooltip: string; }'.
  Property 'tooltip' does not exist on type '{ label: string; }'.
tt.ts(10,38): error TS2339: Property 'tooltip' does not exist on type '{ label: string; } | { label: string; tooltip: string; }'.
  Property 'tooltip' does not exist on type '{ label: string; }'.
```

**Comment by DanielRosenwasser** [comment] 2017-10-14 21:20
Looks like a duplicate of #1260

**Comment by retorquere** [comment] 2017-10-14 21:53
I eyed that issue but couldn't make out whether it was the same problem; If it's a dup feel free to close. The suggestions in #1260 do allow compilation, but is this issue planned for a fix in a 2.x release? #1260 has been open for a while.

**Comment by ajafff** [comment] 2017-10-14 22:22
The easy fix for your problem is a type annotation:
```ts
const cells: {label: string, tooltip?: string} = [
  { label: '1' },
  { label: '2', tooltip: '2' },
  { label: '3', tooltip: '3' },
  { label: '4' },
  { label: '5' },
  { label: '6' },
]
```

**Comment by retorquere** [comment] 2017-10-14 22:27
Yeah, that's what I settled on in the end.

**Comment by mhegazy** [comment] 2017-10-30 18:31
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-30 18:31 UTC
Labels: Question
