### ISSUE TITLE
Infer super class generic type from `super()` call.

### ISSUE THREAD

**Issue by ruojianll** [microsoft/TypeScript#56334] opened 2023-11-07 08:09 UTC
### 🔍 Search Terms

"class generic type"

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Infer super class generic type from `super()` call.

### 📃 Motivating Example

```
class A<T>{
  constructor(arg:T)
}

class B extends A{
  constructor(){
    super('abc')// T is string
  }
}

```

### 💻 Use Cases

1. What do you want to use this for?
This is a common feature.

**Comment by whzx5byb** [comment] 2023-11-07 08:54
Duplicate of https://github.com/microsoft/TypeScript/issues/36456.

**Comment by fatcerberus** [comment] 2023-11-09 17:58
> This wouldn't be a breaking change in existing TypeScript/JavaScript code

This feels potentially breaky in the case of base classes with type parameter defaults - TS would start inferring type parameters where previously a default was used (intentionally).

**Closed** 2023-11-12 01:29 UTC
Labels: Duplicate
