### ISSUE TITLE
Auto Type narrowing for array union type when the first element type is determined

### ISSUE THREAD

**Issue by maple5233** [microsoft/TypeScript#49185] opened 2022-05-20 09:43 UTC
# Suggestion

## 🔍 Search Terms
is:issue union type array guard first element

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
If we have a union type array like `declare const array: string[] | number[]`, and the first element type is determined in a branch, we should be able to narrow the array type to `string[]` or `number[]`.
(Of course we can now use custom type guards for our purposes, but it would be exciting if this were all automated.)

## 📃 Motivating Example
[playground](https://www.typescriptlang.org/play?#code/PTAEBcGdQNwUwE6QJYHsB2AuUAWAdAGx44BQJIoAxgIaRygCMJAJnJQDbUL2UaTiguCagE9s-BMnQBzANoBdUAB9Q6AK4BbAEaIFJAGZr0lcGnShmqAMqoNccAAsp0gBQBKUAG8SoUMn2gLuAiAA5wqAFCorIADIoAvImgAOQSzske3r7ZVHwC+shI4ACi7HB26ALxggjCIrGKFADqDnDmjvQaqGp0oA6o8EigA4gQrbBcyNRaZQA0oCLdVNTmdPSO1AIdENBt0lI8qLVs4Owifuj6iNDbwWHzAO5OlA5+0KngkjLJPjkQofQCkVSuU2uAACoA0DVO7hSK1aJxUAUSD9NTsZigHQpNLfQKUNTHSpnPwCZDvXHSZSqTQ6BAZX45WE1OqQsLQ-5hCIs0TIsCo7oYrH0D5fOTyZL4wncYnnZBkimfZwKanqbS6CVuX4AXxIuvIYBovQATCQpOBEPpqJR6ABBLygfSoVDYNV00C682W630ABCDq0XFdtNGutYHC4h3Q-B5ImN2FtKpUvr0hmMpgwFmstnsThkxvcXl+-kCySdqElUljxoamUZuWj+UK-BBFSq1YafNALTaY063V6-UG0BGCD7E0k0zmCyWNFWcHWDk246goD2B1yxxMJKkVyGtwBj2er3JKVtPyZUKBLbKbbZ9BhAO5UTjnZRaKF2OS56lRNOcoVM9qV9BlL3ZF97w5WFnwROMuwFdFMS-RMJV-GV-1JN4zyTUAU01HU9TICgADlUFAdgMGkUZ0AXTFwDIh5JAtQQqB6eiNE5ehpDULhMVoFjWnYMIxzTEwzHI5AAGtF3JTADCMMTMy0I5nF9NRwGI2i4GYAAJOAhMQABxHiEGYFwX3EJUZBwt0NTcbAXywykVSyUBuHAQl2ifeE6k7RJqlFdJCJIIA)
```ts
// ts version: 4.6.4

// case 1
declare const array: string[] | number[]
function doSomething() {
  if (typeof array[0] === 'string') {
      const firstElement = array[0] // When the mouse hovers over the variable, you can see that the ts engine correctly infers the type, which is 'string'
      type firstElementType = typeof array[0] // should be 'string' (currently it is 'string | number')
      type arrayType = typeof array // should be 'string[]' (currently it is 'string[] | number[]')
  }
}

// case 2
interface A { foo: number }
interface B { bar: number }
declare const array2: A[] | B[]
function doSomething2() {
  if ('foo' in array2[0]) {
    const firstElement = array2[0] // When the mouse hovers over the variable, you can see that the ts engine correctly infers the type, which is 'A'
    type firstElementType = typeof array2[0] // should be 'A' (currently it is 'A | B')
    type arrayType = typeof array2 // should be 'A[]' (currently it is 'A[] | B[]')
  }
}

// No longer need to write a custom type guard as a helper function like this:
function boringButNeededHelperGuard(array: string[] | number[]): array is string[] {
  return typeof array[0] === 'string'
}


```

## 💻 Use Cases
Save time writing custom type guards, and code reading experience will be better

**Comment by MartinJohns** [comment] 2022-05-20 12:48
This sounds like a duplicate of #45301 to me, which was marked as a duplicate of #42384.

**Closed** 2022-05-22 18:00 UTC
Labels: Duplicate
