### ISSUE TITLE
Infer generic types based on properties

### ISSUE THREAD

**Issue by DavidKDeutsch** [Microsoft/TypeScript#7496] opened 2016-03-13 13:20 UTC
This may be a duplicate of #7234 and/or #3812, but I don't know enough about the internals of TypeScript to know for sure. Let's say I have the following:

```ts
interface MyInfo<T> {
   data: T;
}

class Foo {
   x: number;
} 

let fooInfos: MyInfo<Foo>[];
let objectInfos: MyInfo<Object>[];

for (let info of objectInfos) {
   if (info.data instanceof Foo) {
       fooInfos.push(info); // should infer that info is MyInfo<Foo>, but it doesn't
   }
} 
```

In this case, the compiler still thinks `info` is of type `MyInfo<Object>` instead of `MyInfo<Foo>`, whereas I would expect it to be able to properly infer the type.

**Comment by mhegazy** [comment] 2016-03-28 20:00
this is a duplicate of #3812.

**Closed by mhegazy** 2016-03-28 20:00 UTC
