### ISSUE TITLE
Branch that calls a 'never' class method is still expected to return.

### ISSUE THREAD

**Issue by 6XGate** [microsoft/TypeScript#42377] opened 2021-01-17 01:30 UTC
# Bug Report

### 🔎 Search Terms

- `TS2366 never`
- `TS2355 never`

### 🕗 Version & Regression Information

This is the first time trying to use this feature but it occurs with the following versions.

```
❯ npx tsc --version
Version 4.2.0-dev.20210115
```
and
```
❯ npx tsc --version
Version 4.1.3
```

This is the behavior in every version I tried, and I reviewed the FAQ for entries about never returning functions not working as class members.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/MYewdgzgLgBADgJxMAphCMC8MDeMCGCA5gG4BcMA2gEQCWYAJigB4B0UE1ANDNQLR8AFigA2cagF0YAXwBQs0JFgiQRIigRZcsmLpgAzfFHwiAFBqQIKAUQSWAlBTAoSG7Xo8xFEECJSsLEARzOyD7AG4dT10oQSQAdxhAhEiPOTlZfQBXMGAoWnADIxMQyxtQhEcYZ1dNHCjdb19-ZNKw1L1YhKSKyIzs3PzCgFt8egAGUyqwLOGAIzd6jxU1DVZDYzNnRNtLU2p4wRAQOE57CNl+nLyCsBhR+gBGKadZhbqGos3TbZhdoP2h2Op2o5z68gGNxGYzAACYXtU3otPrR9DBTIhkGgIKxCKRWH4wERYjAAISYbDjezuaIwBAoKBZBB3cYdXQZDwbEq-f7BA5HE5nC5XQa3e4wgDMCJm82RHlR6MxqHQuOIJAJKCJJPJlOpS1p9MZzJgrM+HL0K3UCHWxS2KB2FUBApBYMuEOuQzuUDQUGlSI+HgeYEmF0DMOeob0Qfhkd0QalF0+hqZLPBsm90CmkSAA)

### 💻 Code

```ts
const logger = {
    fatal(error: Error): never {
        console.error(error);
        process.exit(1);
    }
}

function fatal(error: Error): never {
    console.error(error);
    process.exit(1);
}

function main0(): number {
    logger.fatal(new Error("whoops"));
}

function main1(): number {
    fatal(new Error("whoops"));
}

function main2(): number {
    if (process.argv.length !== 0) {
        return 0;
    }

    fatal(new Error("whoops"));
}

function main3(): number {
    if (process.argv.length !== 0) {
        return 0;
    }

    logger.fatal(new Error("whoops"));
}

function test(): number {
    main0();
    main1();
    main2();
    main3();

    return 0;
}

process.exit(test());
```

### 🙁 Actual behavior

- The compiler reports a `TS2355` for `main0` even though it calls a `never` returning method. `main1` is fine but uses a standalone function.
- The compiler reports a `TS2366` for `main2` even though it calls a `never` returning method. `main3` is fine but uses a standalone function.

### 🙂 Expected behavior

No errors should have been reported.

**Comment by MartinJohns** [comment] 2021-01-17 02:27
Duplicate of #10470.

**Comment by 6XGate** [comment] 2021-01-17 02:39
@MartinJohns, that issue is almost four years old and appears to have been corrected or unrelated. All `never` stand-along functions in my example work just fine. Just not those on objects.

**Comment by MartinJohns** [comment] 2021-01-17 02:46
That's true, good point. I was a bit too eager posting that comment.

But this seems related and up to date: #36753

**Comment by noneta** [comment] 2021-01-17 02:58
i have to go to see the problem 
i need for a group chat with me on the phone for my work on the next time we can do help me on my phone with text messages arabic make sure we are working for a group chat please let me know if that works for me 🫂💬💋

**Comment by 6XGate** [comment] 2021-01-17 04:24
@MartinJohns, oh cool, yes, that looks like the same issue, since this was affecting type narrowing for me as well.

**Comment by ajafff** [comment] 2021-01-17 13:20
I have written a lint rule that tells you which calls to `never`-returning functions/methods are not recognized by TypeScript, so you don't need to know the exact rules. It suggests using `return` or `throw` in those cases to make the control flow effect explicit.
https://github.com/fimbullinter/wotan/blob/master/packages/mimir/docs/return-never-call.md

**Comment by 6XGate** [comment] 2021-01-17 16:30
I was able to make things work for my use case by just replace my logger object with a set of stand alone functions in one module that I did `import * as logger from "`. Not ideal but for that it was no problem. Would be great of `never` worked everywhere.

**Closed** 2021-01-21 18:00 UTC
Labels: Duplicate
