### ISSUE TITLE
Missing data type in requiring json file.

### ISSUE THREAD

**Issue by zheeeng** [Microsoft/TypeScript#18001] opened 2017-08-24 08:32 UTC
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```json
// data.json
{
    "age": 123,
    "username": "Tom",
}
```

```ts
declare const require: any;

// 'age' and 'username' are inffered as any
const { age, username } = require('./data.json')

// wrong syntax
const { age as number, username as string } = require('./data.json')

// can't use destruction, and we cant get warnings when we assert incorrect types
const age: number = require('./data.json').age
const username: string = require('./data.json').username
```

**Expected behavior:**

Get the correct types of 'age' and 'username'

**Actual behavior:**

Thus require syntax can't get the actual types when handling json file.

**Comment by kitsonk** [comment] 2017-08-24 10:13
You should really be asking these basic general questions in other forums, like StackOverflow or Gitter.

```ts
const { age, username } = require('./data.json') as { age: number, username: string };
// or
const { age, username }: { age: number, username: string } = require('./data.json');
```

**Comment by QuietWind** [comment] 2017-08-24 10:15
you must define require data types! like this.

```ts
// data.json data like

// {
//     "name": "your name",
//     "age": 23
// }

interface Info {
    name: string;
    age: number;
}

const data: Info = require("./data.json");

```

**Comment by zheeeng** [comment] 2017-08-24 12:05
@kitsonk Thx for your reply and sorry for asking syntax. I came up this issues bcoz that I thought that it's may be a defect on requiring non-ts/js file at first.
I think that it is not much difficult to infer the data types which come from JSON file. Why not do the enhancement?

**Comment by kitsonk** [comment] 2017-08-24 12:59
Then this is a duplicate of #9225.

Static analysis of JSON at design time has limited value and almost always needs some sort of assertion of what the real type/structure is for it to be handled as.  Also the mechanics of importing JSON at runtime very widely at runtime and in a lot of cases, it is a structure returned from a remote request, where again, typing would need to be asserted because it cannot be statically identified.

**Comment by zheeeng** [comment] 2017-08-24 14:25
@kitsonk Okay, maybe you are right, I'm just a little upset for the dev experience. The local JSON files have been imported into the compiling system, it should be well analyzed, manually assertion 
 on 'any' type may leads runtime errors.

**Comment by mhegazy** [comment] 2017-08-24 17:50
should be tracked by https://github.com/Microsoft/TypeScript/issues/7071

**Comment by mhegazy** [comment] 2017-09-08 16:56
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-08 16:56 UTC
Labels: Duplicate
