### ISSUE TITLE
Compilation bug if last block in file is multiline comment

### ISSUE THREAD

**Issue by Andreyika** [Microsoft/TypeScript#2035] opened 2015-02-14 06:08 UTC
tsc version 1.4.1.0 (1.3.0 work correctly)
tsc -w --out ../file.js file.ts

file.ts
~~~typescript
/// <reference path="./interfaces.ts"/>
alert('1');
~~~

interfaces.ts
~~~typescript
interface HashTable<T> {
	[key:string]: T;
}

/*interface Test {
}*/
~~~
( *multiline* comment closed on *last line of file*, no emtpy lines after it ). compiled to 
~~~javascript
/*interface Test {
interface HashTable<T> {
	[key:string]: T;
}

/*interface Test {
 
/// <reference path="./interfaces.ts"/>
alert('1');
~~~
last line of interfaces.ts dissapeared so comment block doesnt closed and result js file incorrect.

-------
without reference
typescript
~~~typescript
interface HashTable<T> {
	[key:string]: T;
}
/*interface Test { 
*/
~~~

js
~~~javascript
/*interface Test {
interface HashTable<T> {
	[key:string]: T;
}

/*interface Test {
 
~~~

**Comment by DanielRosenwasser** [comment] 2015-02-14 08:53
Looks like a duplicate of #1714 which should be fixed for TypeScript 1.4.2.

**Closed by DanielRosenwasser** 2015-02-14 08:53 UTC
