### ISSUE TITLE
Different type narrowing behaviour between !Array.isArray and === false

### ISSUE THREAD

**Issue by connorjburton** [microsoft/TypeScript#50712] opened 2022-09-11 10:27 UTC
# Bug Report

I have a variable of type `unknown` that I want to narrow to either a `string` or `any[]`.

If I use `Array.isArray(variable) === false` the type narrowing stays as unknown which I do not expect.

If I use `!Array.isArray(variable)` the type narrowing becomes `string | any[]` which I expected.

### 🔎 Search Terms

Array.isArray type narrowing unknown

### 🕗 Version & Regression Information
v4.8.2 - v3.3.3

- This is the behavior in every version I tried.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.2#code/MYewdgzgLgBBIFsCmBhcAzAlgcwGoEMAbAVyRgF4YAKASgC4ZiwBrMEAdzAoD4YBvAFAxhMAE5IoxUVwDaARgA0MAExKAzAF0A3AIC+AgQHpDMKAE8ADmUwRGLNpyVQAFjZhukADyvAoSACYCoJCw6CAgFHCIqBg4BCRItDoGxjDAzvhg2GQuZPiiovhmac5IwMymEQCEAIIFRQB0NnWFZlRhIDQwmf4wHTBg+aIctlAR0KKYWTAAPt1gZjIaYvi5oqYZXEysHGACmOjU5lYgh-1V5JQA5BNT2FcwAGSPMC2NzfVtHV2XlOhEECQXUEIg2w3YAyQEIAogUQKIqFcAHIgWD4OBQSbTeHzbqfK40HT6IwmfpuaCYQiEOw7RwbNxuNiwLw+PyBVIuBm2ABWxGgMFK4iiMDMIGIaUyMCQ+AglOKgLI7AysFyxWO1lsADdMOjclK4aJbLL-EgAEb5ILgeCEJANQggbDtcINZhIMwQWiEoA)

### 💻 Code

```
const someConfigValue = (): unknown => {
    return [1, 2, 3];
}

// type is unknown, this is expected
const foo = someConfigValue();


// change the array check to !Array.isArray(foo) and foo narrows to string | any[] rather than unknown
if (typeof foo !== 'string' && Array.isArray(foo) === false) {
    throw new Error('Not a string or an array');
}

// foo is still unknown, this is not expected
// this is just here so you can easily see what they type is via the errors sidebar
console.log(foo.keys());
```

### 🙁 Actual behavior

Type narrowing does not work correctly when using `Array.isArray(variable) === false` vs `!Array.isArray(variable)`

### 🙂 Expected behavior

Type narrowing should work the same between `Array.isArray(variable) === false` and `!Array.isArray(variable)`.

`Array#isArray` returns a boolean, it should not matter if I do a loose or strict check.

**Comment by yudai-nkt** [comment] 2022-09-11 11:55
IIUC, `typeof foo !== 'string'` is not required to reproduce this behavior. Below is a more minimal reproduction ([playground](https://www.typescriptlang.org/play?ts=4.8.2#code/MYewdgzgLgBAZiEMC8MAUBDATgcwFwwCuYA1mCAO5gCUKAfDAN4BQMMAlnOgIJZYYBPAHTsIvfgMy5ayWTChZCAU1os2bbDgDcMAPS6ipclVbr9APQD8pgL6nOPPoJFinkzdVWmNuHfpgYYAIA2gC63nq6VrbMNlrMQA)).

```ts
const foo = (arg: unknown) => {
  if (Array.isArray(arg) === true) {
    arg; // unknown
    //^?
  }
  if (Array.isArray(arg)) {
    arg; // any[]
    //^?
  }
};
```

**Comment by MartinJohns** [comment] 2022-09-11 12:00
Duplicate of #31105.

**Comment by MartinJohns** [comment] 2022-09-11 12:03
Also a duplicate of #9508 (much older), which was marked Won't fix.

**Comment by yudai-nkt** [comment] 2022-09-11 12:07
I believed that there must be a duplicate because this behavior seemed easy to encounter, but I didn't have the time to investigate at the moment. Thanks for pointing out.

**Comment by connorjburton** [comment] 2022-09-11 12:21
Interesting, thank you for the additional context. I wonder if the stance would be different now than it was in 2016, if this would be easier to implement or not.

I found the justification for the Won't Fix to be weak, in my opinion. I don't see how strictness is a code smell and should be a first class citizen when it comes to support.

However, I am not a contributor or maintainer of TypeScript so I am not privy to the complexity or design decisions around this. So happy with just knowing the context.

**Comment by MartinJohns** [comment] 2022-09-11 13:00
To me personally it's just more noise and adds no benefit. Makes the code harder to read as well.

You might be interested in the ESLint rule "strict-boolean-expressions": https://typescript-eslint.io/rules/strict-boolean-expressions/  
It ensures that logical expressions are booleans. So `if (myBool)` is valid, but `if (myString)` or `if (myNumber)` is not.

**Comment by connorjburton** [comment] 2022-09-11 16:32
Thanks, that might be a good substitute.

**Closed** 2022-09-15 18:00 UTC
Labels: Duplicate
