### ISSUE TITLE
Inferred type incomplete, when inferring parameters type on surcharged constructors.

### ISSUE THREAD

**Issue by denis-migdal** [microsoft/TypeScript#59812] opened 2024-08-31 11:29 UTC
### 🔎 Search Terms

None

### 🕗 Version & Regression Information

Tested on the nightly build.

### ⏯ Playground Link

```tsx function foo(a: boolean): void function foo(a: number): void function foo(a: boolean|number) {}  type InferArgs<T> = T extends (...args: infer U) => void ? U : never;  type Args = InferArgs<typeof foo... ```  [Playground Link](https://www.typescriptlang.org/play/?ts=5.7.0-dev.20240831#code/GYVwdgxgLglg9mABMOcAUBDAXIgRqgGwFMMwBKHANzhgBMAoUSWBZVTHMEAW1yICcKianUbho8JCnTY8hEmAA+XXgLKIA3gF969KAE8ADkUQBJMMAEBBfgHMAzgB4AKgD5EAXkTPERAB5QRGC09ohoAHSRGHb2ODAWAogAquoe7iK0iAD8yYicRJQCANy6BsaINg6eZgn8lU5lRHDAbHCuJfTEUIiy9dUA2lD8IEQAukVAA)

### 💻 Code

```ts
function foo(a: boolean): void
function foo(a: number): void
function foo(a: boolean|number) {}

type InferArgs<T> = T extends (...args: infer U) => void ? U : never;

type Args = InferArgs<typeof foo>;

let a: Args = [true];
```

### 🙁 Actual behavior

When inferring the function parameters, only one of the function signature is used.
Here, `Args` is `[number]`, which raises an error in the last line.

### 🙂 Expected behavior

When inferring the function parameters, the union of the different signatures should be returned.
Here, `Args` should be `[number]|[boolean]`.

**Comment by jcalz** [comment] 2024-08-31 12:45
You didn’t provide any search terms. Did you search for existing issues before filing this? Also, “surcharged” isn’t a term that makes much sense here but from context I gather you mean “overloaded”.

Duplicate #43731

**Comment by MartinJohns** [comment] 2024-08-31 13:20
This is also in the documentation: [Inferring Within Conditional Types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types)

> When inferring from a type with multiple call signatures (such as the type of an overloaded function), inferences are made from the _last_ signature (which, presumably, is the most permissive catch-all case). It is not possible to perform overload resolution based on a list of argument types.

**Comment by denis-migdal** [comment] 2024-08-31 15:14
> You didn’t provide any search terms.

Sorry for that, I was in a train with very slow/limited Internet access.

> Also, “surcharged” isn’t a term that makes much sense here but from context I gather you mean “overloaded”.

Indeed, bad translation (in French we say "surcharge").

> This is also in the documentation: [Inferring Within Conditional Types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types)

So according to the documentation :
> When inferring from a type with multiple call signatures (such as the type of an overloaded function), inferences are made from the last signature (which, presumably, is the most permissive catch-all case).

The last signature being :
```ts
function foo(a: boolean|number)
```

Shouldn't `Args` be at least `[boolean|number]` ?
It makes to sense for it to be sometimes the first signature, and sometimes the second signature.

**Comment by jcalz** [comment] 2024-08-31 15:18
"I was in a train" So, um, wait until you're off the train to file issues? Maybe? I don't know how to process this response.

"The last signature being" no, that's the implementation. It's not a call signature (try calling the function with `Math.random()<0.5 ? true: 123` as an argument) If you want that call signature you need to add it explicitly.

**Comment by denis-migdal** [comment] 2024-08-31 15:25
> If you want that call signature you need to add it explicitly.

Well, I don't want this to be a call signature, but the implementation signature to be used during inferences as it makes the most sense.

The documentation is also a little strange :
> the last signature (which, presumably, is the most permissive catch-all case).

It is the implementation signature that is the catch-all case, not the last call signature.

**Comment by MartinJohns** [comment] 2024-08-31 15:38
The documentation refers to _call signatures_. You can't call the implementation signature. But I guess the wording could be clearer.

> It is the implementation signature that is the catch-all case, not the last call signature.

That depends on your code. In your example there is no "catch-all" call signature. But you could add one:

```typescript
function foo(a: boolean): void
function foo(a: number): void
function foo(a: boolean | number): void
function foo(a: boolean|number) {}
```

Now you have a catch-all call signature, and your function could be called with a value typed `boolean | number`.

**Comment by denis-migdal** [comment] 2024-08-31 16:07
> That depends on your code. In your example there is no "catch-all" call signature. But you could add one:
> [...]
> Now you have a catch-all call signature, and your function could be called with a value typed `boolean | number`.

I think I see 3 issues for this.

The first one is that the third signature would be callable, so would enable to call e.g. `foo(true, 3)`. When we only want this signature for inferences.

The second one is the code duplication between the last call signature and the implementation signature (code duplication is never a great thing).

The third one is that if we wish to use it on existing functions, we'd have to declare it for every functions which can be really time-consuming, with the risk of forgetting one, or if one function is modified, to forget to update the declaration.



Knowing that, without overload, TS already generates a signature from the implementation signature.
Could it be possible, with overload, to also generate one from the implementation (but non-callable) ?

For example, if we assume that TS generates a signature list, could we assume that e.g. the first one is non-callable (if other signatures are available), and reserve it for the implementation signature ? If empty (e.g. no implementation signature known), could use the last signature from the list (current behavior), or could even be computed as the union of the other signatures ?

Technically I'd assume this would be possible ?

**Comment by jcalz** [comment] 2024-08-31 16:15
So is this now some kind of feature request? TS is behaving as designed and we’re talking about… implementation signature changes? What’s the status of this as a bug report?

**Comment by denis-migdal** [comment] 2024-08-31 16:18
> So is this now some kind of feature request? TS is behaving as designed and we’re talking about… implementation signature changes? What’s the status of this as a bug report?

Currently it seems the issue is a design issue. I think you consider them to be feature requests ?

**Comment by jcalz** [comment] 2024-08-31 18:24
I really don't know, and I'm not a member of the TS team, just a <strike>nosy</strike> <strike>annoying</strike> *interested*  bystander, so nothing I say is authoritative. You can feel free to ignore me and just wait for the TS team to get involved. But, I'd say if you don't want this to be closed as just a duplicate of #43731 or others, you should edit it so it uses the feature request template and be specific clear about what the feature request is, searching first for existing issues with similar requests, to help the TS team triage.

My guess is that they would just decline a suggestion to expose the implementation signature the way you're asking for. Function types don't encode *implementation* information, they encode *call signature* information. Declarations for overloads don't mention the implementation, and they shouldn't have to know anything about the implementation (or else TS's library files for JS would need to have all kinds of added information in them). And what good would it do to consult the implementation signature when the function is not callable that way? If you tell me `Parameters<typeof foo>` is `[boolean | number]` and I *can't* call `foo(Math.random()<0.5?true:123)` then I'm not going to be happy. Personally I'd expect someone who runs into this discrepancy with overloads to ask for #14107 with the hope that you'd get `[boolean] | [number]` or something like it.

Anyway I think I've said all I can say here so I will bow out and wait to hear what the TS team says. Good luck!

**Comment by denis-migdal** [comment] 2024-08-31 19:54
Thanks for your answer.

> Personally I'd expect someone who runs into this discrepancy with overloads to ask for #14107 with the hope that you'd get `[boolean] | [number]` or something like it.

I agree. I assumed it was not possible as the doc stated:
>  It is not possible to perform overload resolution based on a list of argument types.

And hard to fix, as the mentioned issues are 5 to 7 years old, without being addressed, while it the issue seems quite real (TS seems to have a lot of such issues, it is kind of frustrating).

Indeed, as you stated :

> If you tell me `Parameters<typeof foo>` is `[boolean | number]` and I _can't_ call `foo(Math.random()<0.5?true:123)` then I'm not going to be happy.

You are quite right. It is even more true if we have 2 arguments : `[boolean | number, boolean | number]`, while you can't call `foo(true, 0)` would indeed be incoherent.


However, I saw that the type has the different callable signatures :
```
type c = {
    (a: boolean): void;
    (a: number): void;
}
```
So TS seems to have all required information to perform a correct inference.

But I think I got the issue.

**Possible solution 1:**

For a simple inference, we could simply try it for each callable signature, and return an union of the inferred types.
But with more complex inference, we could have the same issue as you presented :

```ts
type Args<T> = T extends (a: infer A, b: infer B) => infer C ? [A,B, C] : never;
```
Could give `[number|boolean, number|boolean, void]`. But it'd be technically correct as we didn't returned the function signature, but a tuple of the possible types for its parameters and return value.

**Possible solution 2:**

Else, the union could be made latter, by making an union of the results, e.g. returning : `[number, number, void]|never|[boolean, boolean, void]`. But I assume it might pose some performances issues if there are lot of nested inference ?

**Possible solution 3:**

Adding to TS the types from the solution given inside the issue you just posted:

[Playground Link](https://www.typescriptlang.org/play/?ts=4.7.2&ssl=78&ssc=15&pln=78&pc=33#code/C4TwDgpgBA8gbhATgGwPYEMAmAFRqwDOAPACrxJpYB8UAvFNgJYDGA1qeShpgDRSsQQqAGZQyCLtQDcAWABQoSLAmVMAVQB2jVBoBKEZgFdEBRgg4rufEtnSJgjdMk6q6UQxtYbUAdw016cQpuKAgAD2AIDUwCKAAKeSgoADpUuwBzAgAuKEYNYSQxAEFETPkASjoaPILEMX1gYw1EqAB+KAB6DoZECAQNYFz8vMZIqF6jE20NKAAjECgCYHwwPPTxg2NTHSgfAAsosVt7R2dLLBakrqg99Fj0ZiMAW0NkdEjMKCdkKBEoYAOYhcIVM6Q072MEAIyUuRzsDicwKwoQiURiQPOmFh7Q0fSQsKysKSSQAPspglhNNN9JNTOYicTGTZ4ackZ8AGQYim8BmMpLMk6IzFQTlxOKpZIZbLFUoESq0GgkBpNSqctm4fDEIKSTBUXnEvVyPnEsliiVSnIkEqZeWK5WIDTlFo5XESWQKcDQNlUnQWbkoyLRWLitKynLoDQgADaAF1bV9IwEoABRMLMZCGTAQIgtb1aHQ0rZmbOw64kQEAIji8ddSAri0YYIhvSgLyWc2ge1QjCWEE+y3+leEeAG9b+AIgpe6eUiJgMDh0fGEqDqwB8qA2dx00vQlVmBnQhgI0AmRZ2S01uwOM1GuQIU9CGmYqA8s77fAjn1mlVvx4gT1iAcwF6fpBgnKBn2QN5CGgP4CEMWZjwAR0MKJgAfCtnyeMB3kYWZkAgetQXBRpemDCB0mSKAq3jOBu0wesZw3Kt0FaHIAEZaPoityh4B99hYPYoHSYt7igTBGAmQZnw0CRthmAd0HcfMNBhI1iTFGs8UQVUuR1FoqD49TtVccJA3RasqigWs6hxbSoBySyFWs7T5Cod15A6AAqeRy2gYBEBYVhAI3cD0FmVAEA2Wlpi+XoJXkeRdygABJfIkECjR1nAnDEHQJ4IFnBNPl6UiFM9WI-gjX5MT7KBhA8ZgFxmHxGCg9xj3kcC3nbSL-WI5sID4ATmCEnsvjAXK0OQBZqvCMBkBYW8s2IiCuxYCA1Pkb9UoGJBjyatYvgbLKCIbJtSOgVqAUHWDApE8Efhnfb52mPhmGq3oVyzRAusBZ650OnY4jAVACFMfDZpmDxMFQZ40Lq0ws1CYQCia1pyi2uRmEqNLZwO5rYg+mYdBmjsNgAWm+pB32s1BBnBRA8B8Oq4l6TBDGYPteKgABlVA+AneQAYJ2LbhC8nelmQw2sGPJbuogUETObl63SKIkBYQXr3kU8ph2YnyYvSa6v2Q5wIa9qRdenZxY7Q4pZl5BgDUmAJ0QVrj218b11eEqoVeOWZmqmoRjGPX5LUryOkSuRrmTSFWHQABCLrPTEKFgCKdi3DzaYiAAbxaascjoxhMHdJI4nQDjyg4yv4hrqAACY+FmHJm7rlv3QAX3c2P48wdWoAAYTuCAchoqybKIxsSMhVsj0Gfcbm7XtMDUxRoBITOimb3PMR9DRC+Lruy4r4um84+vL47tuO675uG5Lly3XkPuPLj7pkyH6Ax+PHIAARQwC0WDvGgANS69wWyoCeKMD4m9047yWEUAAzAfbkR8T7qRfufZ+V8u7sWfmfeiUhOjdA5qAj6kRb4t3vi3R++Da713IeJEBi1qGTjkB-Ae3QABy9N-K3DAoCamdQ-h9R1LEcaTx0AzjkbiT48twIeDeleQSrYIARnvF-Qc7xcjAAAOSxBAvtPCZ0jxHSUkfEgqA8YvSBuVJQZsWzgUkaoTy3QxGtnePjKifkURczAM1O81EnI0BnsNPYGi7YDhXutdenj-ihUBMOHQgxxz-T2oDZqVEAASvhtJ8FGMYhWTwwaDAIJAZgjBhAsHOvPXoRlrgjSEgVbRq8ewOCygYxYXY-ZG3QAUXIogVEqVCTJCQHw5gPFYMkhMSTraOKxtcNKtRMrrCUqonYfxcr5UKoURoC0oS-DqKVJo-wKqhO8D4KAoNwbmM2mnJQ6o7D7PxqQAMaJgzmjDAmaMcYrIRhAEmY47z9pEDzr6EgVB+4eheZie0GgSCek+WZb58RfmZHDJGWM8ZgVJiRSiyAkLD4qVILCz+W8M5LAAEI53oK8vKBUPlFxwSQ8uTCoDX25Vy1ucwH4d2IS6bSvc4XPO3pnWl+9GWIsKk0Yl2Y2VVw5RfHBrFmG8tofy9uDChWnxFW-bh4rdECLGOBCsM8NhlUuUoYmhjl7QDyOmTMtN9wfSPNAbZGhYjXSEjZJJsM6ZBxdcjUYakgA)

**Comment by RyanCavanaugh** [comment] 2024-09-05 17:03
I don't see anything here that isn't addressed in other issues.

> And hard to fix, as the mentioned issues are 5 to 7 years old, without being addressed, while it the issue seems quite real (TS seems to have a lot of such issues, it is kind of frustrating).

Every issue you encounter leads to an open issue rather than a closed one, interesting observation 🙂

![Image](https://github.com/user-attachments/assets/a44ff791-56cf-452b-a7c9-0169b82bee0a)

**Closed by RyanCavanaugh** 2024-09-05 17:03 UTC
Labels: Unactionable

**Comment by denis-migdal** [comment] 2024-09-05 21:31
> Every issue you encounter leads to an open issue rather than a closed one, interesting observation 🙂

The interesting observation is that lot of theses issues are rather old than new, with multiples instances, and often due to design choices... some issues never got any clear answer whether they'll be fixed one day, its priority level, what prevent/delay a fix, etc.

I have so much fun wasting time on "unsound" stuff, and trying to find dirty workarounds if any.
