### ISSUE TITLE
Type Narrowing Inside Looping Structure Conditions not Persisting

### ISSUE THREAD

**Issue by xXCrash2BomberXx** [microsoft/TypeScript#54660] opened 2023-06-15 20:50 UTC
# Bug Report

### 🔎 Search Terms
Looping, Condition, Inference, Chain, And, &&, Array

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Type Guards

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/DYUwLgBAhgTjBcECCcoE8A8KbowIwHsDQoA7APggB8JSBXAWzxBkoF4IBtTsGOkALoCA3AFgAUBIBmBGBAAUoSAEsIHAAzCIqjNDgA6UKQDmYABZblAaisBKCREfapC2DE7KB20gGcwZAGMQAhdsdAgAMgi9d09DEBNzCEp1W0cAenSIAAUYAgAHFjA0CAByI1MzUogAEwIQH1oCSBAAD2U-CAJSCGLCsvomFmoIQmIQMk4BUv0HJ3mA7p9xwwJjeTcPAXjEs1stCEycvMKYYrKK82q6hqaW9s7u3rR+0sHmORoxklIpmYkJMoXBs4Jx1F5lL5-KQgiFkKgSlEYmDtpczMkIKk5o5Fr4VsA1vJePx9kA)

### 💻 Code

```ts
let arr: Array<Array<boolean> | number> = [[true]];

for (let i = 0; i < arr.length; i++)
    if (arr[i] instanceof Array && arr[i].length > 0)  // Property 'length' does not exist on type 'number | boolean[]'.
        console.log(arr[i].length);  // Property 'length' does not exist on type 'number | boolean[]'.

if (arr[0] instanceof Array && arr[0].length > 0)
    console.log(true);
```

### 🙁 Actual behavior
When attempting to compile, the condition `arr[i] instanceof Array` infers that `arr[i]` is an `Array` and has the property `length` but this inference is not continued throughout the rest of the condition nor body within the condition due to the variable `i`. This behavior does not match the behavior with a fixed-index as is shown in the fixed-index block.

### 🙂 Expected behavior
Ideally, the inference from `arr[i] instanceof Array` would be continued into `arr[i].length > 0` due to it being an `&&` which makes the second condition never run unless `arr[i]` is an instance of  `Array`. This should also be the case for the body of the if statement. This behavior is shown with a fixed index but does not apply to a variable one.

**Comment by fatcerberus** [comment] 2023-06-15 20:56
It has nothing to do with the loop.  It's just that `obj[key]` isn't narrowed when `key` is not a literal.  Duplicate of https://github.com/microsoft/TypeScript/issues/51368 -> https://github.com/microsoft/TypeScript/issues/10530

**Comment by fatcerberus** [comment] 2023-06-15 20:57
Workaround: First assign the value `arr[i]` to a variable inside the loop and narrow that.

**Closed** 2023-06-22 01:33 UTC
Labels: Duplicate
