### ISSUE TITLE
Promise assignability checking is weak

### ISSUE THREAD

**Issue by jeffreymorlan** [Microsoft/TypeScript#8561] opened 2016-05-11 21:07 UTC
`Promise<Derived>` is assignable to `Promise<Base>` (good), but `Promise<Base>` is also assignable to `Promise<Derived>` (bad - should require a cast)

This weakens type checking, especially since it's so easy to accidentally create `Promise<{}>` which is assignable to any other `Promise`:

```ts
function f() {
    return new Promise(resolve => { resolve(1); });
    // oops, this has a return type of Promise<{}>
}
function g(p: Promise<string>) { /* ... */ }

g(f()); // Allowed due to contravariance!
```

It's possible to work around this by extending the Promise interface with a dummy property:
```ts
interface Promise<T> { _assignabilityHack: T }
```

**Comment by falsandtru** [comment] 2016-05-11 23:48
See #6407.

**Comment by chrisgavinme** [comment] 2016-05-18 15:56
If this is by design, would it be possible to have an option to fail compilation when a type cannot be inferred in a situation like this?

**Comment by mhegazy** [comment] 2016-05-20 01:09
Looks like a duplicate of #6407

**Closed** 2016-05-20 05:53 UTC
Labels: Duplicate
