### ISSUE TITLE
Error: No Project. in 'Object.ThrowNoProject' during 'signatureHelp'

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#21808] opened 2018-02-09 01:19 UTC
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.1
**VSCode Version** 1.20.0-insider
**command requested**: signatureHelp
**hitting sessions**: 652
**proportion of all sessions**: 0.002433989241170256
**stack**
```
Error: No Project.
    at Object.ThrowNoProject (tsserver.js:84217:23)
    at ProjectService.getDefaultProjectForFile (tsserver.js:87395:46)
    at IOSession.Session.getFileAndProjectWorker (tsserver.js:89772:87)
    at IOSession.Session.getFileAndProject (tsserver.js:89757:29)
    at IOSession.Session.getSignatureHelpItems (tsserver.js:89977:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89035:61)
    at unknown (tsserver.js:90393:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90384:28)
    at IOSession.Session.executeCommand (tsserver.js:90393:33)
    at IOSession.Session.onMessage (tsserver.js:90413:35)
    at Interface.<anonymous> (tsserver.js:91614:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mhegazy** [comment] 2018-02-09 18:06
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/20629

**Closed by mhegazy** 2018-02-09 18:06 UTC
Labels: Bug, Source: Telemetry
