### ISSUE TITLE
Type guard does not work when its value is set to a variable.

### ISSUE THREAD

**Issue by alexandretperez** [Microsoft/TypeScript#19943] opened 2017-11-11 10:31 UTC
**TypeScript Version:** 2.7.0-dev.20171111

**Code**

```ts
// -- Errors here:
test(value: number | undefined) : number {
    let isNumber = typeof value == "number";
    if (isNumber && value > 0) // < -- TS2532: Object is possibly 'undefined'.
        return value * 10;

    return 0;
}

// -- No errors here:
test(value: number | undefined) : number{
    if (typeof value == "number" && value > 0)
        return value * 10;

    return 0;
}
```

**Expected behavior:**
No errors

**Actual behavior:**

TS2532: Object is possibly 'undefined'.

**Comment by ahejlsberg** [comment] 2017-11-11 15:26
Duplicate of #12184.

**Closed** 2017-11-27 18:38 UTC
Labels: Duplicate
