### ISSUE TITLE
Hex Colors error with TS2590: Expression produces a union type that is too complex to represent

### ISSUE THREAD

**Issue by AtomicGamer9523** [microsoft/TypeScript#59015] opened 2024-06-25 16:57 UTC
### 🔎 Search Terms

`ts(2590)`, `Expression produces a union type that is too complex to represent.`, `HexTypes`

### 🕗 Version & Regression Information

This is an error that typescript throws when I try to build it, as well as the LSP complains. It raises the error `ts(2590)`, `Expression produces a union type that is too complex to represent`

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAEhAeBhAFgQwE5QLxQEQAZcoAfPARiNNwCZK8BmO3AFiYFYmA2JgdiYA4mATiYBBJgCEmiJgBEmAUSYAxXAG4AUKEiwE9RAHsANgcw4ABgGIAJAG84SNOgC+dhygyv7CDy-ObtaAdOQxMzKCs3Hycvdxiox08E31jopO9EvwDwIIR+UNNsCJsMlOT40oq49OqXcpq0usrPfw0NBDBTYChA3SRjQpwHfQHMUmCCsb780bUgA

### 💻 Code

```ts
type HexChar = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "A" | "B" | "C" | "D" | "E" | "F";
type Hex3Color = `#${HexChar}${HexChar}${HexChar}`;
type Hex6Color = `#${HexChar}${HexChar}${HexChar}${HexChar}${HexChar}${HexChar}`;
type Hex8Color = `#${HexChar}${HexChar}${HexChar}${HexChar}${HexChar}${HexChar}${HexChar}${HexChar}`;

export type HexColor = Hex3Color | Hex6Color | Hex8Color;
```

### 🙁 Actual behavior

The type of `HexColor` should be well defined and accessible. As well as there shouldn't be any errors.

### 🙂 Expected behavior

The type of `HexColor` is `any`, and there are errors.

### Additional information about the issue

It seems that also Deno is affected (I first discovered it using Deno). I tried switching to plain TS, still raises errors.

**Comment by AtomicGamer9523** [comment] 2024-06-25 17:11
It seems that the maximum states that union can represent is `2^32`, but `Hex6Color` and `Hex8Color` are more than that. The simple fix would be to change the max number of union states from a 32-bit integer to a 64-bit integer. I am just not quite sure where that error actually gets raised

**Comment by MartinJohns** [comment] 2024-06-25 17:39
Duplicate of #43388.

> It seems that the maximum states that union can represent is `2^32`

The limit is 25, and that's intentional.

**Comment by AtomicGamer9523** [comment] 2024-06-25 22:02
> > It seems that the maximum states that union can represent is `2^32`
> 
> The limit is 25, and that's intentional.

I [searched for 25](https://github.com/search?q=repo%3Amicrosoft%2FTypeScript++language%3ATypeScript+path%3A%2F%5Esrc%5C%2F%2F+25&type=code), and can't seem to find where this limitation actually is. Is it possible to submit a PR to increase that value ?

**Comment by jcalz** [comment] 2024-06-25 23:43
25 is from #30779 but that doesn't seem to be related to this. The limit here is on the order of 10^5, and if you are trying to write a union bigger than that then you're doing something TS doesn't want you to do. The limit is there for performance so I'm sure they're not going to increase it to some large number just because the *number* can be represented easily.

**Comment by RyanCavanaugh** [comment] 2024-06-26 20:28
The limit is in place to stop your typechecking from taking six hours, not because we don't have access to 32 bits worth of integer 😉

**Comment by AtomicGamer9523** [comment] 2024-06-26 22:09
I see, thank you. In my case the only thing I can really do then is to perform some analysis during compile time, and/or hope for #43335 to be accepted

**Closed** 2024-06-29 01:30 UTC
Labels: Duplicate
