### ISSUE TITLE
organizeImports will break prettier formatting

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#23931] opened 2018-05-07 15:50 UTC
_From @lordgreg on May 7, 2018 7:34_

For better readability, we are using Prettier to show our code like:
```
import { HttpParams } from '@angular/common/http';
import {
  Component,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  OnInit,
  Output,
  SimpleChanges,
  ViewChild
} from '@angular/core';
import {
  MatPaginator,
  MatSelectChange,
  MatTableDataSource
} from '@angular/material';
```
`organizeImports` breaks the formatting

Steps to Reproduce:

1. use prettier 
2. use `format document` function
3. save so organizeImports steps in.

## Result:
```
import { HttpParams } from '@angular/common/http';
import { Component, EventEmitter, Input, OnChanges, OnDestroy, OnInit, Output, SimpleChanges, ViewChild } from '@angular/core';
import { MatPaginator, MatSelectChange, MatTableDataSource } from '@angular/material';
```

## Should be:
```
import { HttpParams } from '@angular/common/http';
import {
  Component,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  OnInit,
  Output,
  SimpleChanges,
  ViewChild
} from '@angular/core';
import {
  MatPaginator,
  MatSelectChange,
  MatTableDataSource
} from '@angular/material';
```

_Copied from original issue: Microsoft/vscode#49339_

**Comment by mhegazy** [comment] 2018-05-07 19:26
Duplicate of https://github.com/Microsoft/TypeScript/issues/22991

**Closed** 2018-05-22 18:55 UTC
Labels: Duplicate
