### ISSUE TITLE
better type coercion : instead of cannot invoke an expression whose type lacks a call signature

### ISSUE THREAD

**Issue by SalathielGenese** [Microsoft/TypeScript#20877] opened 2017-12-23 15:07 UTC
**TypeScript Version:**  2.6.2

```json
{
    "compilerOptions": {
        "strict": true,
```

**Code**

```ts
export interface HopeLike<T, S = void>
{
    <U>(callabale: (value: T) => U, asHoped?: (value: U) => boolean): HopeLike<U, T>;
    or<U>(callable: (parent: S, value: T) => U): this | HopeLike<U, T>;
    get(): T | void;
}

let h: HopeLike<number> = <any>void 0;
h(() => 1).or(() => '').or(p => ({})); // here is the issue, from the `.or(...`
```
Note that this code works well if `.or` call is not called twice!

**A concrete usecase**
```ts
const EVENT: Event<typeof source> = new Event(event, source);
const HANDLERS = hope(EVENT_EMMITTERS.get(this)!)
    (container => container.get(event)!)
// Since it is not sure this key is mapped, let's ensure, just in case.
// This' achieved by calling `.or(callback)` which will run its callback only if the `event` key is mapped
    .or(container => container.set(event, []).get(event)!)
        .get(); // were finally fetch the real result, which may be `void` as well
if (HANDLERS) for (let handler of HANDLERS)
    if (void handler.call(EVENT, EVENT, ...data) || EVENT.isPropagationStopped)
        break;
```

Where :

1. `const EVENT_EMMITTERS: WeakMap<EventEmitter<any>, Map<string, EventHandlerLike<any>[]>> = new WeakMap();`
2. The `this` context is instance of `EventEmitter`

**Expected behavior:**
I had expected these to be inferred after the`.or` second call:

1. parameter `p` as `number | string`
2. the return value to be: `HopeLike<number, number> | HopeLike<U, number> | HopeLike<string, number> | HopeLike<U, string>`

**Actual behavior:**
The error says `cannot invoke an expression whose type lacks a call signature. Type '(<U>(callable: (parent: number, value: number) => U): HopeLike<number, number> | HopeLike<U, nu...'`

**Comment by DanielRosenwasser** [comment] 2017-12-23 21:41
This might be fixed by #17819; @weswigham?

**Comment by SalathielGenese** [comment] 2017-12-24 11:08
Thanks @DanielRosenwasser  for your interest. As far as I can tell of your example, the union type is for signatures with same return type and but differing parameter types.

In my case, the parameter is of one type only. The return type changes depending of what happen at rutime: the callback in the `.or(...)` call is executed only if the computed value from previous `HopeLike<T, S>(...)` call were not satisfied (according to the predicate `asHoped(...)`).

So, no sure this might be a fix.

-----

However, I was able to increase typing complexity, wrote a solution that worked, then striped off unnecessary code until I got a simple solution that works just as I expected (even the implementation is now tiny).

```ts
export interface HopeLike<T, S = void>
{
    <U>(map: (value: T) => U, asHoped?: (value: U) => boolean): HopeLike<U, T>;
    or(map: (parent: S) => T): HopeLike<T, S>;
    get(): T | void;
}
```

You may discover that the redesigned interface express something strongly different from the first version. I figured out that I wrongly implemented the solution to that my specific problem. Nonetheless, the question remains: **[W]hy TypeScript cannot (yet) infer that union type of two functions to be function, thus *call*able ?**

Therefore, I call for possible duplicates as I believe this isn't the first issue opened about...

**Comment by sylvanaar** [comment] 2017-12-26 21:44
I have reduced the problem down so it is easier to to see the issue:

```
type Func = (<T>() => T) | (() => void);

const callme = {} as Func;

callme(); // error
```

**Comment by SalathielGenese** [comment] 2017-12-27 01:55
You got it clear, @sylvanaar

**Comment by RyanCavanaugh** [comment] 2017-12-27 19:02
Duplicate of #7294

**Closed** 2018-01-24 18:03 UTC
Labels: Duplicate
