### ISSUE TITLE
v4.0.x -> v4.1.1-rc change in overload selection

### ISSUE THREAD

**Issue by tchetwin** [microsoft/TypeScript#41563] opened 2020-11-17 09:46 UTC
**TypeScript Version:**  4.1.0-dev.20201029, 4.1.1-rc

**Search Terms:** overload

**Code**

```ts
import { promisify } from "util";

// These are components of @types/xml2js@0.4.5
export interface convertableToString {
    toString(): string;
}
declare class Parser {
    parseString(str: convertableToString, cb?: Function): void;
}

const xmlParser = new Parser();
const parseString = xmlParser.parseString.bind(xmlParser);
const parseStringP = promisify(parseString); // <--- interested in overload selection from this line

parseStringP("abc");
//           ^--- error surfaces here
```

**Expected behavior:**

No error. This overload is selected from `promisify`:

```
(alias) promisify<convertableToString, unknown>(fn: (arg1: convertableToString, callback: (err: any, result: unknown) => void) => void): (arg1: convertableToString) => Promise<...> (+13 overloads)
```

**Actual behavior:**

`Expected 0 arguments, but got 1. (2554)` (on the argument to `parseStringP`). This overload is selected from `promisify`:

```
(alias) promisify<unknown>(fn: (callback: (err: any, result: unknown) => void) => void): () => Promise<unknown> (+13 overloads)
```

**Notes:**

Overloads from [unpkg](https://www.unpkg.com/@types/node@14.14.7/util.d.ts):

```ts
interface CustomPromisifyLegacy<TCustom extends Function> extends Function {
    __promisify__: TCustom;
}
interface CustomPromisifySymbol<TCustom extends Function> extends Function {
    [promisify.custom]: TCustom;
}
type CustomPromisify<TCustom extends Function> = CustomPromisifySymbol<TCustom> | CustomPromisifyLegacy<TCustom>;

function promisify<TCustom extends Function>(fn: CustomPromisify<TCustom>): TCustom;
function promisify<TResult>(fn: (callback: (err: any, result: TResult) => void) => void): () => Promise<TResult>;
function promisify(fn: (callback: (err?: any) => void) => void): () => Promise<void>;
function promisify<T1, TResult>(fn: (arg1: T1, callback: (err: any, result: TResult) => void) => void): (arg1: T1) => Promise<TResult>;
function promisify<T1>(fn: (arg1: T1, callback: (err?: any) => void) => void): (arg1: T1) => Promise<void>;
function promisify<T1, T2, TResult>(fn: (arg1: T1, arg2: T2, callback: (err: any, result: TResult) => void) => void): (arg1: T1, arg2: T2) => Promise<TResult>;
function promisify<T1, T2>(fn: (arg1: T1, arg2: T2, callback: (err?: any) => void) => void): (arg1: T1, arg2: T2) => Promise<void>;
// removed overloads with 3, 4 & 5 template parameters for brevity
function promisify(fn: Function): Function;
```

**Playground Links:**

[4.1.0-beta](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201028#code/JYWwDg9gTgLgBAbzmKETAM7AGYE84C+c2qIcARAK4zAA25A3AFBMD0rcAKgBYCmGvOAEMoggMZpIAO15SYGOBGxwAAjFxh+rAB4haAJgBWGFQAYAdABZzAVia9tkWHGBzeUbELHiIUgG7uMEIARrS8nBAAyjBQrgDmiExwyXAwUTHxABQAlABccBgZUnHMBEwAJrxitCLiNRgKAAoiAlCJKXDscAAGYsHdcCBC+FIQ8MGCMHxwE4WpGrxJKV3J0MBxrvncMDBgGLnsG1OUweYSIKwAIrzYrsAwvLS4nAvlVzd3D08vmm+hEMFWAAOADsIWCIIAnAA2coARjEQlMAGZoSC4UCbEIgdChDYgaYxEDglibHCbKZ9DCiax1JoMDo9EYGa5KtpzOVzPIAMQAGWRyKWyTALV40VixUyhSg+Qk-kCITCEXF8QANHA+gB+fIAMUoUjENF8eTgfggwHKpRYcrmulozSgrTgAF44DIAO5wB2tHLMG3wEWOsVFBKuu3e9zmQMCFXFczBVmZcOiqDZP2+ObR4MSuKNF3IUiYHC4TJZ2NxNMsMshxqZcghMTkStdAC0bfbHYAekwgA) ✔️ 
[4.1.0-dev.20201028](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201028#code/JYWwDg9gTgLgBAbzmKETAM7AGYE84C+c2qIcARAK4zAA25A3AFBMD0rcAKgBYCmGvOAEMoggMZpIAO15SYGOBGxwAAjFxh+rAB4haAJgBWGFQAYAdABZzAVia9tkWHGBzeUbELHiIUgG7uMEIARrS8nBAAyjBQrgDmiExwyXAwUTHxABQAlABccBgZUnHMBEwAJrxitCLiNRgKAAoiAlCJKXDscAAGYsHdcCBC+FIQ8MGCMHxwE4WpGrxJKV3J0MBxrvncMDBgGLnsG1OUweYSIKwAIrzYrsAwvLS4nAvlVzd3D08vmm+hEMFWAAOADsIWCIIAnAA2coARjEQlMAGZoSC4UCbEIgdChDYgaYxEDglibHCbKZ9DCiax1JoMDo9EYGa5KtpzOVzPIAMQAGWRyKWyTALV40VixUyhSg+Qk-kCITCEXF8QANHA+gB+fIAMUoUjENF8eTgfggwHKpRYcrmulozSgrTgAF44DIAO5wB2tHLMG3wEWOsVFBKuu3e9zmQMCFXFczBVmZcOiqDZP2+ObR4MSuKNF3IUiYHC4TJZ2NxNMsMshxqZcghMTkStdAC0bfbHYAekwgA) ✔️ 
[4.1.0-dev.20201029](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201029#code/JYWwDg9gTgLgBAbzmKETAM7AGYE84C+c2qIcARAK4zAA25A3AFBMD0rcAKgBYCmGvOAEMoggMZpIAO15SYGOBGxwAAjFxh+rAB4haAJgBWGFQAYAdABZzAVia9tkWHGBzeUbELHiIUgG7uMEIARrS8nBAAyjBQrgDmiExwyXAwUTHxABQAlABccBgZUnHMBEwAJrxitCLiNRgKAAoiAlCJKXDscAAGYsHdcCBC+FIQ8MGCMHxwE4WpGrxJKV3J0MBxrvncMDBgGLnsG1OUweYSIKwAIrzYrsAwvLS4nAvlVzd3D08vmm+hEMFWAAOADsIWCIIAnAA2coARjEQlMAGZoSC4UCbEIgdChDYgaYxEDglibHCbKZ9DCiax1JoMDo9EYGa5KtpzOVzPIAMQAGWRyKWyTALV40VixUyhSg+Qk-kCITCEXF8QANHA+gB+fIAMUoUjENF8eTgfggwHKpRYcrmulozSgrTgAF44DIAO5wB2tHLMG3wEWOsVFBKuu3e9zmQMCFXFczBVmZcOiqDZP2+ObR4MSuKNF3IUiYHC4TJZ2NxNMsMshxqZcghMTkStdAC0bfbHYAekwgA) ❌ 
[4.1.1-rc](https://www.typescriptlang.org/play?ts=4.1.1-rc#code/JYWwDg9gTgLgBAbzmKETAM7AGYE84C+c2qIcARAK4zAA25A3AFBMD0rcAKgBYCmGvOAEMoggMZpIAO15SYGOBGxwAAjFxh+rAB4haAJgBWGFQAYAdABZzAVia9tkWHGBzeUbELHiIUgG7uMEIARrS8nBAAyjBQrgDmiExwyXAwUTHxABQAlABccBgZUnHMBEwAJrxitCLiNRgKAAoiAlCJKXDscAAGYsHdcCBC+FIQ8MGCMHxwE4WpGrxJKV3J0MBxrvncMDBgGLnsG1OUweYSIKwAIrzYrsAwvLS4nAvlVzd3D08vmm+hEMFWAAOADsIWCIIAnAA2coARjEQlMAGZoSC4UCbEIgdChDYgaYxEDglibHCbKZ9DCiax1JoMDo9EYGa5KtpzOVzPIAMQAGWRyKWyTALV40VixUyhSg+Qk-kCITCEXF8QANHA+gB+fIAMUoUjENF8eTgfggwHKpRYcrmulozSgrTgAF44DIAO5wB2tHLMG3wEWOsVFBKuu3e9zmQMCFXFczBVmZcOiqDZP2+ObR4MSuKNF3IUiYHC4TJZ2NxNMsMshxqZcghMTkStdAC0bfbHYAekwgA) :x:
[4.2.0-dev.20201112](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201112#code/JYWwDg9gTgLgBAbzmKETAM7AGYE84C+c2qIcARAK4zAA25A3AFBMD0rcAKgBYCmGvOAEMoggMZpIAO15SYGOBGxwAAjFxh+rAB4haAJgBWGFQAYAdABZzAVia9tkWHGBzeUbELHiIUgG7uMEIARrS8nBAAyjBQrgDmiExwyXAwUTHxABQAlABccBgZUnHMBEwAJrxitCLiNRgKAAoiAlCJKXDscAAGYsHdcCBC+FIQ8MGCMHxwE4WpGrxJKV3J0MBxrvncMDBgGLnsG1OUweYSIKwAIrzYrsAwvLS4nAvlVzd3D08vmm+hEMFWAAOADsIWCIIAnAA2coARjEQlMAGZoSC4UCbEIgdChDYgaYxEDglibHCbKZ9DCiax1JoMDo9EYGa5KtpzOVzPIAMQAGWRyKWyTALV40VixUyhSg+Qk-kCITCEXF8QANHA+gB+fIAMUoUjENF8eTgfggwHKpRYcrmulozSgrTgAF44DIAO5wB2tHLMG3wEWOsVFBKuu3e9zmQMCFXFczBVmZcOiqDZP2+ObR4MSuKNF3IUiYHC4TJZ2NxNMsMshxqZcghMTkStdAC0bfbHYAekwgA) ❌ 

**Related Issues:**

https://github.com/microsoft/TypeScript/issues/41099 - Similar *looking* but the version introducing the regression doesn't align.
https://github.com/microsoft/TypeScript/issues/41359#issuecomment-721383363 - Previously reported in this Issue

**Comment by robpalme** [comment] 2020-11-17 10:42
@DanielRosenwasser This is the late-breaking 4.1 compatibility break I mentioned earlier.  It didn't really hamper the upgrade because it was easy to circumvent.

**Comment by DanielRosenwasser** [comment] 2020-11-17 10:51
@ryancavanaugh maybe let's discuss about this briefly before the release. It sounds like it's not a blocker, but I can't make sense of the change here and it affects the inference of Node.js's `promisify`.

**Comment by DanielRosenwasser** [comment] 2020-11-17 13:14
@ahejlsberg too - unclear if https://github.com/microsoft/TypeScript/issues/41099 is related.

**Comment by DanielRosenwasser** [comment] 2020-11-17 21:47
@ahejlsberg I believe this regression came from https://github.com/microsoft/TypeScript/pull/41308

**Comment by DanielRosenwasser** [comment] 2020-11-17 22:09
Okay, here is the minimal repro:

```ts
declare function promisify<TResult>(fn: (callback: (err: any, result: TResult) => void) => void): () => Promise<TResult>;
declare function promisify<T1, TResult>(fn: (arg1: T1, callback: (err: any, result: TResult) => void) => void): (arg1: T1) => Promise<TResult>;

declare function parseString(str: any, cb?: Function): void;

const parseStringP = promisify(parseString);

let x = parseStringP("abc");
```

This works in TypeScript 4.0, but not in 4.1 or after that PR. If you swap the overloads, then things work again.

**Comment by DanielRosenwasser** [comment] 2020-11-17 22:28
I tried swapping each of the corresponding `void`/non-void callback operators, let's see if it can just be a DefinitelyTyped fix: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49640

**Comment by ahejlsberg** [comment] 2020-11-17 22:48
I took a look. Short story, the current behavior is correct and the previous behavior wasn't. But it is incredibly subtle. It comes down to relating the types

* source `(str: convertableToString, cb?: Function | undefined) => void` and
* target `(cb: (err: any, result: unknown) => void) => void`

during overload resolution. First subtlety is that `convertableToString` is effectively equivalent to `{}` because every object has a `toString(): string` method. So, the `cb` and `str` parameters end up being compatible, and since target only supplies one parameter there is no need to relate the `cb?` parameter to anything. Overload resolution therefore succeeds and picks an overload that subsequently causes an error.

I didn't succeed before because we'd relate type `Function | undefined` to `any` for the second parameter instead not relating at all. The intent here was to have it always succeed (because anything is assignable to `any`). However, the first pass of overload resolution uses the subtype relation, and in that relation `any` is a top type and not assignable to `Function | undefined`. So, overload resolution would (erroneously) skip the overload.

Like I said, subtle!

The real issue is that the overloads aren't selective enough and/or listed in the wrong order.

**Comment by DanielRosenwasser** [comment] 2020-11-17 23:12
I don't think there's an obvious way to reorder `promisify` in a way that doesn't introduce a new break. Here's a few test cases included:

```ts
declare function parseString(str: any, cb?: (...args: any) => any): void;

const parseStringP = promisify(parseString);

let x = parseStringP("abc");

const arg1UnknownError: (arg: string) => Promise<number> = promisify((arg: string, cb: (err: unknown, result: number) => void): void => { });
const arg1AnyError: (arg: string) => Promise<number> = promisify((arg: string, cb: (err: any, result: number) => void): void => { });

const arg0: () => Promise<number> = promisify((cb: (err: Error | null, result: number) => void): void => { });
const arg0NoResult: () => Promise<any> = promisify((cb: (err: Error | null) => void): void => { });
const arg1: (arg: string) => Promise<number> = promisify((arg: string, cb: (err: Error | null, result: number) => void): void => { });
const arg1UnknownError2: (arg: string) => Promise<number> = promisify((arg: string, cb: (err: Error | null, result: number) => void): void => { });
const arg1NoResult: (arg: string) => Promise<any> = promisify((arg: string, cb: (err: Error | null) => void): void => { });
const cbOptionalError: () => Promise<void | {}> = promisify((cb: (err?: Error | null) => void): void => { cb(); }); // tslint:disable-line void-return

declare function promisify<TResult>(fn: (callback: (err: any, result: TResult) => void) => void): () => Promise<TResult>;
declare function promisify(fn: (callback: (err?: any) => void) => void): () => Promise<void>;
declare function promisify<T1, TResult>(fn: (arg1: T1, callback: (err: any, result: TResult) => void) => void): (arg1: T1) => Promise<TResult>;
declare function promisify<T1>(fn: (arg1: T1, callback: (err?: any) => void) => void): (arg1: T1) => Promise<void>;
declare function promisify<T1, T2, TResult>(fn: (arg1: T1, arg2: T2, callback: (err: any, result: TResult) => void) => void): (arg1: T1, arg2: T2) => Promise<TResult>;
declare function promisify<T1, T2>(fn: (arg1: T1, arg2: T2, callback: (err?: any) => void) => void): (arg1: T1, arg2: T2) => Promise<void>;
```

I could imagine trying a migration to rest parameter types, but I'd rather not do that for this change.

**Comment by DanielRosenwasser** [comment] 2020-11-17 23:13
@tchetwin @robpalme you mentioned that this was something you managed to get around - do you remember what you specifically did?

**Comment by tchetwin** [comment] 2020-11-18 09:33
> @tchetwin @robpalme you mentioned that this was something you managed to get around - do you remember what you specifically did?

By `as ...` casting the argument to `promisify` to force selection of the correct overload.

This occurred in precisely one place and it happened to be in the shared build tooling itself rather than the application population.

**Comment by AlCalzone** [comment] 2020-11-19 13:56
> I could imagine trying a migration to rest parameter types, but I'd rather not do that for this change.

How do you like [this](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201112#code/PQKhFgCgAIWglApgFwK4CcB2BnayAWi0ANgIbbLQCWyiAtgOS7ICeADkVZtKXqm8URRYwKIgAebAPbpKrDtAAy5ZAB4AKtAm1MAE1ypMAa0xSA7pgDaAXQB80ALzRN2xHtw2oASAD80TIgAbojo3gBczlriOvrQlgB0iVwAZiHQAPoANNSYqegI1tB+8OGRru5xifEpaVnQABQ1+fAAlD6FfvXw0AA+0Ia6iMlciLotpQHB6ADcUFCgcEhoWMyEeOxEUsl4a2QUPOgA5qh0bpRbPNDJhgDGyFRS3CCikBLSsusKyhQAgkcnZw0URiuHqVVIR2wEVImBYNhajnsMJY9ic3zUAAUIaRTrR0NgNLZbLNIPMwAgUBgcDsiAAidCUrC0z6bba8G6kYjEABGpBuRgAtBQWIJoD8MQBJERiSQyOQbaAAYU5PL5RnFEqWVPUG1U3hc0TcsTBiQhhyhPFh8MRlpYmX1iu5wKNoPBkOhVusCIcSNhjiUKj+x1OmDU6ls9sgXnUjqDuCcWPQOJQIQJAFFxDdiKhBhpHdkBkMRroiZGvKiHdy486KpZ6mn0OgZL1-KguS3C8MAmN2kVoIEpFRdNAwpXq+VYpYG038n1MG3iB29EXu9kmtAAKodTcjseQmuxZE2PsxquQywARkKo5g0DvkxC3hJZIgMEWjOpvDYTboVGwVGGUYrlue5Hmgf9DkwUhliIZJmwIIhDioYJuA5LleX5IVWFFa5MDuB5MHiYRnhld55QUDEfz-ACWCBCdXVNd1bWtH1bTLdQtSwf1lXQtUNU4zAdQ4Ql2PHQ0KiPQo0UQUhdFURNkzxAlwwjbxUQaN1zQidQ429exKKkX9sEQDQBOJOZIAWYiKWWT9225VA5F2FRqFoRhmAVLhLjQAREGACEkxYYiXjeOUWSUGS5INEF+mMUwLBsdTopdOJrG8PxPCjbSDw8Kp10UbJkV7PxFFKGxn0gQYswhWCQII6Bv0M6jklo5KKhNeIzQtSS9NtWx6mSTBtJaCIDKMmjCQq4BgEcBw5vmhaLKqsgGWAvDQO4NgIWMgBlZB0C4Q56godAPTtaAbm5HwIg6rqzpY30WBG-tB10CqbkefYtvxRA9oOzBDgxf1GvGlr6m+3b9sOloSUEShxGB7bfqhgGMXqWlSG5G5aRh+YZvwchwoaE6zt6sa-xM5FbAs6aog4O5Rhus0IhO6GbXJ4zVHnOhuRCanLJmvk0E5CI73qZnwJRw4yaoznud59B7EAFHIoA+nBKDNC8Nzi8xMGnZsnBB5qWHqcWjhZqXskum6QlO2KTF17IGWwNtkAieWQl6gch2e73h1YgBvaAAF9cYFunEAZ3QmfNyX-ul9nZZMj3Fbxng7lQEW7waCXWYBmWmrlk4FeV1XPo1o4Lx+WF9fyQ3ZZo03c8ti7uRtxszqdxAXeIN3Wx5z2bT933XptIPQ5JWm3kj2ho4aAujOT4u+bToXM+IUX58Twul4HxXoBVyA1f2M0AAZgYbsH6mthpbYiWuW3nLku57vuU6916R6HMeQ7DqfJBnozLerEOaU1hPzWma8s5iwXhTVQft7ACgFPYCUDBhxmlQEQAgf5qC4A+o2GeZd1YHEOKfAAclIJAr8L6F0btfNut8O7QAfnOBcH8fYRD9j-Ceadp5RxjocC28dYFFz3hAwWGdoE51jnnBOICk5c2XvvQ+x8K6HAvDQ0GJszaCLjodK2DD6h32YY2ZsrDn7QGdq7d2Sj2FjE4aPQOv9J4zT4bPARQi2byJ3oosRq9JEb2zjozx+dt6L18SXA+RCT6V21g7CwtcABMmjjZNxkS3G+RimEsNbBYqxvcbF7zsV-f29hx5-1cQA-h0jdGyJEWAlE-jhaBLFs3YRYS4EIOgEglBaCSGYJ2DgnB+CGR3GiWoi8FCqGuxSf+K+bT9Gt3bnbHJT9iDFIcd-JxPDw5uKAfUep8DR59ADsHcR6dmmbwOR0zmCDxmtwAPJsA2pyB+9daFX0ybba6JiZyPzYUPT+mzSnQCDpdA50xnHQFpsgbAxAuBu10H+TGggBTwoCC9IcAoGS2SgEAA)?

```ts
/**
 * Returns the last item's type in a tuple
 */
export type Last<T extends unknown[]> = T extends []
	? never
	: T extends [...infer _, infer R] ? R
	: T extends [...infer _, (infer R)?] ? (R | undefined)
	: never;

/** Returns the type of the last argument of a function */
export type LastArgument<T extends (...args: any[]) => any> = Last<Parameters<T>>;

/** Returns the "return" type of a callback-style API */
export type CallbackAPIReturnType<
	T extends (...args: any[]) => any,
	TCb extends (...args: any[]) => any = LastArgument<T>,
	TCbArgs = Parameters<Exclude<TCb, undefined>>,
	> =
	TCbArgs extends [(Error | null | undefined)?] ? void :
	TCbArgs extends [Error | null | undefined, infer U] ? U :
	TCbArgs extends any[] ? TCbArgs[1] :
	never;

/**
 * Returns a promisified function signature for the given callback-style function.
 */
export type Promisify<T extends (...args: any[]) => any,
	TReturn = CallbackAPIReturnType<T>,
	TArgs extends any[] = Lead<Parameters<T>>,
	> = (...args: TArgs) => Promise<TReturn>;

/**
 * Returns all but the last item's type in a tuple/array
 */
export type Lead<T extends unknown[]> = T extends []
	? []
	: T extends [...infer L, any?] ? L
	: [];

declare function promisify<T extends (...args: any[]) => any>(fn: T): Promisify<T>;
```

results for your test cases:
```ts
declare function parseString(str: any, cb?: (...args: any[]) => any): void;

const parseStringP = promisify(parseString);
let x = parseStringP("abc");
// has type  (str: any) => Promise<any>

// expected: (arg: string) => Promise<number>
// actual:   (arg: string) => Promise<number> ✔
const arg1UnknownError = promisify((arg: string, cb: (err: unknown, result: number) => void): void => { });

// expected: (arg: string) => Promise<number>
// actual:   (arg: string) => Promise<number> ✔
const arg1AnyError = promisify((arg: string, cb: (err: any, result: number) => void): void => { });

// expected: () => Promise<number>
// actual:   () => Promise<number> ✔
const arg0 = promisify((cb: (err: Error | null, result: number) => void): void => { });

// expected: () => Promise<any>
// actual:   () => Promise<void> --> I'd argue this is correct
const arg0NoResult = promisify((cb: (err: Error | null) => void): void => { });

// expected: (arg: string) => Promise<number>
// actual:   (arg: string) => Promise<number> ✔
const arg1 = promisify((arg: string, cb: (err: Error | null, result: number) => void): void => { });

// expected: (arg: string) => Promise<number>
// actual:   (arg: string) => Promise<number> ✔
const arg1UnknownError2 = promisify((arg: string, cb: (err: Error | null, result: number) => void): void => { });

// expected: (arg: string) => Promise<any>
// actual:   (arg: string) => Promise<void> --> I'd argue this is correct
const arg1NoResult = promisify((arg: string, cb: (err: Error | null) => void): void => { });

// expected: () => Promise<void | {}>
// actual:   () => Promise<void> --> where should the {} come from?
const cbOptionalError = promisify((cb: (err?: Error | null) => void): void => { cb(); }); // tslint:disable-line void-return
```

**Comment by DanielRosenwasser** [comment] 2020-11-19 19:50
Well those *seem* way better. I don't know how I feel about those helper types, but if you wanted to put up your own PR to `@types/node` that might be a worthwhile way to gauge any other breaks.

**Comment by clonardo** [comment] 2020-11-19 23:33
is there a way to switch back to the old behavior via a compilerOptions flag or something? TypeScript 4.1.2 is now shown on npm as a stable release, and this is a breaking change in my application.

**Comment by DanielRosenwasser** [comment] 2020-11-19 23:37
It is a stable release, and we make breaks across minor versions. 4.1.2 is the first stable minor version for 4.1.x.

I don't know whether we realistically can make a roll-back change. What kind of things did you hit in the upgrade?

**Comment by clonardo** [comment] 2020-11-20 00:33
> It is a stable release, and we make breaks across minor versions. 4.1.2 is the first stable minor version for 4.1.x.
> 
> I don't know whether we realistically can add a flag. What kind of things did you hit in the upgrade?

This app had a number of places where it was creating a `new Promise()` via the constructor and resolving it with `resolve()`. I had to change the promise constructors to `new Promise<void>`. The app was being built with noImplicitAny:false and noImplicitReturns:false . What made life a little more difficult is that VSCode's TypeScript language service (in the current stable release) wasn't letting me select 4.1.x for pre-build checking, so I had to go back to a find + replace + fix, transpile, wait and cross fingers-type workflow. After doing this work to update a pretty big monorepo, it's fine now, I think.

**Comment by DanielRosenwasser** [comment] 2020-11-20 00:37
Sorry to hear that - that's actually [a separate known break, relating to the issue of how `resolve` is typed](https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#resolves-parameters-are-no-longer-optional-in-promises).

> VSCode's TypeScript language service (in the current stable release) wasn't letting me select 4.1.x for pre-build checking

Hmm - [you should be able to select a workspace version of TypeScript](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-the-workspace-version-of-typescript). I suspect if that doesn't work, the issues there might relate to the monorepo setup.

Again, sorry that this hit you in a surprising way.

**Comment by clonardo** [comment] 2020-11-20 03:01
> s

Thanks, I didn't realize about the change to `resolve` typings.

To check the VSCode issue, I brought up another (non-mono) repo and installed `typescript@latest`. Still no good, even after closing + reopening VSCode, and restarting the TypeScript language service. I'm on VSCode 1.51.1 on Windows 10. Now that I know where the risks are, I'm not too worried about this.

![image](https://user-images.githubusercontent.com/7379800/99752701-cc982380-2ab2-11eb-82e0-774518d91de4.png)

**Comment by AlCalzone** [comment] 2020-11-20 10:47
>  if you wanted to put up your own PR to `@types/node` that might be a worthwhile way to gauge any other breaks

PR is up at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49699, but I'll need some help. The directory structure of @types/node is complicated to say the least :)

**Comment by yw662** [comment] 2020-11-29 00:06
Can confirm in 4.1.2 where I have to explicitly write like `new Promise<void>(res=>res())` instead of just `new Promise(res=>res())` where former version of typescript infers a `Promise<unknown>`.

**Comment by yw662** [comment] 2020-11-29 00:09
> VSCode's TypeScript language service (in the current stable release) wasn't letting me select 4.1.x for pre-build checking,

But you can change the typescript version VSCode use. Just click the ts version in bottom right corner and vscode will write your option in ./.vscode/sth.

**Comment by tchetwin** [comment] 2020-12-01 10:34
@yw662, as per Daniel above:

> that actually sounds more like [a separate known break, relating to the issue of how `resolve` is typed](https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#resolves-parameters-are-no-longer-optional-in-promises).

The need to introduce an explicit `void` type parameter for Promise constructors resolving with no arguments is unrelated to this Issue thread.

**Comment by AlCalzone** [comment] 2020-12-03 08:41
> Well those _seem_ way better. I don't know how I feel about those helper types, but if you wanted to put up your own PR to `@types/node` that might be a worthwhile way to gauge any other breaks.

PR is up at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49699 and seems to be working. What needs to be done to gauge the impact of this? @DanielRosenwasser

**Comment by ahejlsberg** [comment] 2020-12-03 21:08
See https://github.com/microsoft/TypeScript/issues/41607#issuecomment-736807393 for an explanation of what changed in overload resolution.

**Closed** 2022-06-21 08:21 UTC
Labels: Breaking Change, Rescheduled
