### ISSUE TITLE
Option to preserve original decorators (no transpiling)

### ISSUE THREAD

**Issue by nashwaan** [Microsoft/TypeScript#20569] opened 2017-12-08 07:29 UTC
**TypeScript Version:**  2.6.2

**Code**

I like Typescript for all its advertised advantages and specially, it is a **superset** for ESNext javascript.

But I am facing one issue in the transpiled code.
I would like you to add an option to preserve original decorators in the emitted code.

Say I have the following class `Greeter` in `greeter.ts`:

```ts
function clsDecorator(constructor: Function) {
  Object.seal(constructor);
}

function funDecorator(value: boolean) {
  return function (target: any, propertyKey: string, descriptor: PropertyDescriptor) {
      descriptor.enumerable = value;
  };
}

@clsDecorator
class Greeter {
  greeting: string;
  constructor(message: string) {
    this.greeting = message;
  }
  @funDecorator(false)
  greet() {
    return 'Hello, ' + this.greeting;
  }
}
```

But how to keep class and function decorators in the output and not introduce __decorate code?

**Expected behavior:**

I want to get this `greeter.js` output (which is correct ESNext syntax when experimental decorator is enabled, and it can be consumed by babel):

```js
function clsDecorator(constructor) {
  Object.seal(constructor);
}

function funDecorator(value) {
  return function(targe, propertyKey, descriptor) {
    descriptor.enumerable = value;
  };
}

@clsDecorator
class Greeter {
  greeting;
  constructor(message) {
    this.greeting = message;
  }
  @funDecorator(false)
  greet() {
    return 'Hello, ' + this.greeting;
  }
}
```

**Actual behavior:**

But currently I get this output using `tsc greeter.ts --target ESNext` (which is good for the general case):

```js
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
function clsDecorator(constructor) {
  Object.seal(constructor);
}
function funDecorator(value) {
  return function (target, propertyKey, descriptor) {
    descriptor.enumerable = value;
  };
}
let Greeter = class Greeter {
  constructor(message) {
    this.greeting = message;
  }
  greet() {
    return 'Hello, ' + this.greeting;
  }
};
__decorate([
  funDecorator(false)
], Greeter.prototype, "greet", null);
Greeter = __decorate([
  clsDecorator
], Greeter);
```

**Comment by j-oliveras** [comment] 2017-12-08 15:57
Duplicate of #16882 and #18713.

**Closed** 2018-01-25 23:25 UTC
Labels: Duplicate
