### ISSUE TITLE
esModuleInterop:true breaks intellisense

### ISSUE THREAD

**Issue by gc** [microsoft/TypeScript#40991] opened 2020-10-04 13:52 UTC
Issue Type: <b>Bug</b>

These tsconfig.json values are completely breaking intellisense for my project:
```ts
		"module": "commonjs",
		"moduleResolution": "node",
```

When I take these out, and restart ts server, it works fine, if i put them back in and restart ts server, it stops working.

**Observed result:**
When typing in something in code, such as `Time`, which vscode should be suggesting me to import from somewhere, no dropdown appears at all, and if I do `ctrl+space`, it says no suggestions. Again, I remove those 2 config options, restart ts server, and it works fine.

**Expected result:**
Should show a dropdown pretty much in 99% of cases when im typing, doesnt show a dropdown AT ALL.

**Reproduction:**
You could try use my repo to reproduce: https://github.com/oldschoolgg/oldschoolbot

Note that, these 2 config options come from the `eslint-config-bamboo` that im extending in the tsconfig.json there, **however** I am using these 2 tsconfigs locally for debugging this: https://gist.github.com/gc/fa1110fa28e7a66ac0b1ee42a73435a6

to test that its working, go to `index.ts` and type in the word `roll` and/or `Time` - both should definitely be giving suggestions.

removing these 2 options however breaks other stuff, and isnt a viable solution for me to use. hopefully someone canhelp me find the root cause.

**note:** I have tried completely, entirely nuking vscode (including all my settings) from my PC, clearing all node_modules and caches, and reinstalling - and that didnt fix it.

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600X Six-Core Processor            (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.45GB free)|
|Process Argv|--crash-reporter-id 693da592-757d-488c-9730-a967bac12a33|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|3.2.0
vscode-eslint|dba|2.1.8
prettier-vscode|esb|5.7.1
vscode-styled-components|jpo|0.0.32
material-icon-theme|PKi|4.3.0
ayu|tea|0.20.1
material-theme|zhu|3.9.1

(1 theme extensions excluded)

</details>

**Comment by andrewbranch** [comment] 2020-10-08 18:12
It’s working for me, though I didn’t run `npm install`, so maybe there’s a dependency that’s totally crashing things? Can you try these steps?

1. `npm install typescript@next`, then select that TypeScript version as the one VS Code uses. Does that fix it?
2. If not, `rm -rf node_modules` and restart TS Server. Does that fix it?
3. Regardless of whether or not it does, restart TS Server, run “TypeScript: Open TS Server log” from the command palette, try again, and send me the logs.

**Comment by gc** [comment] 2020-10-29 10:08
@andrewbranch Thank you for taking the time to look into this

1. Nope.
2. No, definitely not - I tried this a million times, I even further nuked all my caches, completely uninstalled TS, VSCode, etc, and it didnt fix.
3. Log: https://pastebin.com/raw/B8kNW1y2


**Steps taken:**
1. `git clone https://github.com/oldschoolgg/oldschoolbot.git`
At this point in time, it should work fine. e.g. type `roll` in `src/index.ts` and youll see lots of suggestions.
2. Now, `yarn add typescript` (or npm), and it will install a 4.0 version of Typescript. and **restart TS server** in VSCode so its definitely using the new version.
3. Now try again to type in src/index.ts, and it doesnt work..
4. This is the point I saved the TS Server log linked above.


I noticed `Error: Debug Failure. Symbol parent was undefined. Flags: ` appears in the logs, which based on my looking, seems like it might be the error causing this.

**Comment by gc** [comment] 2020-10-29 10:51
I *think* I may have tracked further what the issue is, I pretty much went through and deleted a tonne of files to manually bisect the cause, since obviously its an import causing it, and I think I've deduced its the `oldschooljs` package (which is my package, by the way).

Heres the code for the package, is something off or wrong with it to be causing this? https://github.com/oldschoolgg/oldschooljs

**Comment by andrewbranch** [comment] 2020-10-29 18:05
Ah. I think this is a duplicate of #40684, which was literally just fixed yesterday by #41282. _Now_ I bet `typescript@next` solves your problem.

**Comment by gc** [comment] 2020-10-30 03:54
Doesn't seem to fix it. I installed the next version, ensured that it was the selected ts version, and it still happens.

Logs: https://pastebin.com/raw/MWT4Eea6
```
Info 0    [14:51:47.334] Starting TS Server
Info 1    [14:51:47.335] Version: 4.1.0-dev.20201029
[snip]
    Debug Failure. Symbol parent was undefined. Flags: ExportDoesNotSupportDefaultModifier|Property|GetAccessorExcludes|SetAccessorExcludes|PropertyOrAccessor|MethodExcludes|ClassMember|ValueModuleExcludes|FunctionExcludes|FunctionScopedVariableExcludes|Value|BlockScopedVariableExcludes|ParameterExcludes|RegularEnumExcludes|ClassExcludes|ConstEnumExcludes|EnumMemberExcludes|Transient. Declarations: PropertyDeclaration, PropertySignature.
```

**Comment by gc** [comment] 2020-10-30 04:26
OK - I think I have found the cause... in my package, I had a class that I copied (& licensed) from someone elses code, and they were doing this weird export:
```ts
export = Collection as typeof Collection & {
	default: typeof Collection;
};
```

after changing it to just a normal `export default class`, seems all fixed.

**Closed** 2021-02-04 18:22 UTC
Labels: Bug, Crash, Domain: Completion Lists, Fix Available
