### ISSUE TITLE
Inconsistent Errors on conditional assignment with optional object properties

### ISSUE THREAD

**Issue by mkaraula** [microsoft/TypeScript#46276] opened 2021-10-08 14:57 UTC
# Bug Report

### 🔎 Search Terms

- object
- optional properties
- undefined
- conditional assignment 

### 🕗 Version & Regression Information

- This is the behavior in every version I have tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-beta#code/C4TwDgpgBAYg9nKBeKBvKcB2EBcUBGCANhAIaZQA+UArpgCYQBmAltvVAL4BQokUAIVIAnZGiy4CxMph7cAxlgDOwKEwR54iFKgl46jVu04BubucWYVBEQHlseIaJTq4AOglQAhEhQHmbBAcAPxqCFB46HpQwMI00KYWyqr4IgAqAO5wjiJirh7Y3r60DAHsUKG6DmHuEpwRaBjVsfFcQA)

### 💻 Code

```ts
type Foo = { one: boolean | undefined }
type Bar = {one: boolean}

const foo: Foo = {one: undefined};


const barOne: Bar = foo.one !== undefined ? foo : { one: true };

const barTwo: Bar = foo.one !== undefined ? {one: foo.one} : { one: true }
```

### 🙁 Actual behavior

The assignment for `barOne` throws an error but the assignment for `barTwo` does not.

### 🙂 Expected behavior

I was expecting that either both of them fail or that none of them is failing. 

### 👋

Apologies if this is not a Bug but I dont get it and I could not find any explanation for this online. 

I got stuck for quite a while with this Issue. My problem is that I dont understand why an conditional assignmnet like the one for `barOne` is failing. Then I discovered that when I do the assignment like I did for `barTwo`, Typescript isnt complaining. 

I would expect that eiter both of them throw an error or both of them dont throw one.

**Comment by andrewbranch** [comment] 2021-10-11 19:07
I think basically a duplicate of https://github.com/microsoft/TypeScript/issues/18758; see #38839

**Closed as completed** 2021-10-14 18:00 UTC
Labels: Duplicate
