### ISSUE TITLE
Omit is broken / Modifiers not inferred

### ISSUE THREAD

**Issue by pirix-gh** [Microsoft/TypeScript#31232] opened 2019-05-03 15:20 UTC
@DanielRosenwasser 

The new version of `Omit` discards the field modifiers. The solution is to avoid using a type directly in a `keyof` statement as TS loses the inference of the field modifiers (optional, readonly). 

I am not sure if it should behave this way, as you looked confident writing the `Omit` type, it's probably part of another problem. In short, **TS discards the inference of field modifiers on mapped types that map with another type (instead of keyof).**

**TypeScript Version:**  3.5.0-dev.20190501

**Search Terms:**
mapped type readonly lose modifiers

**Code**

```ts
type Omit<T, K extends keyof any> = {
    [P in Exclude<keyof T, K>]: T[P]
} //     ^^^^^^^^^^^^^^^^^^^^ optional & readonly not inferred

// Mapping with a type like Exclude<keyof T, K> caused TS to forget modifiers

type O = {
    readonly a: string
    b?: number
    c?: any
}

type test00 = Omit<O, 'b'>

type WhatWeGet = {
    a: string;
    c: any;
} // === test00

type WhatItShouldBe = {
    readonly a: string;
    c?: any;
} // !== test00
```

**Expected behavior:**
Should preserve the modifiers

**Actual behavior:**
Loses the modifiers on the fields

**Playground Link:** 

**Related Issues:**

**Comment by jcalz** [comment] 2019-05-03 15:45
Duplicate of #31190

**Closed** 2019-05-03 15:52 UTC
