### ISSUE TITLE
TS2531: Object is possibly 'null' but it is certain not null. switch(true) pattern. 

### ISSUE THREAD

**Issue by Artuar** [microsoft/TypeScript#41097] opened 2020-10-14 08:03 UTC
I tried to use switch(true) pattern in my code and found a bug.
There is a similar piece of code that shows the same bug.
Try it on the playground.

**Playground Link:** 
[TS Playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBBDuBLKwAWAVATgVwKYAUBDKKXTMGAXhgAoA3QgGzwEYAuGMbAWwCMyYAH07ZGjADQwGzXACYOXPgOFcxASioA+GAG8AUDENwkKVLSg5cG-UdsxghCLilNWMAISVqqxjABkfi4ysh5eImJsBnbRmLhQ2ORBbgDUSXIA3FHRDk5pLKHeooyR0TFxCRTSrJmlMAAmuABmhKJQJbVGsfGJVRlZMAC+egOZQA)

**Code**
```
const switchTruePattern = (value1: number | null, value2: number | null) => {
    switch (true) {
        case value1 !== null && value2 !== null:
            return value1 + value2;
        case value1 !== null:
            return value1;
        default:
            return value2;
    }
};
```

**TypeScript Version:**  4.0.2

**Expected behavior:**
TS should correctly assume that next cannot be null after the conditional statement.

**Actual behavior:**
It throws TS2531: Object is possibly 'null'.

**Related Issues:** 
[#35964](https://github.com/microsoft/TypeScript/issues/35964)

**Comment by MartinJohns** [comment] 2020-10-14 08:31
Essentially a duplicate of #37178. Just the details vary slightly.

**Comment by RyanCavanaugh** [comment] 2020-10-15 15:55
Please search a bit more diligently before logging new issues. Thanks!

**Closed by RyanCavanaugh** 2020-10-15 15:55 UTC
Labels: Duplicate
