### ISSUE TITLE
Allow the use of a module JSX namespace

### ISSUE THREAD

**Issue by ceymard** [Microsoft/TypeScript#8757] opened 2016-05-23 14:05 UTC
Since JSX is a global namespace, it is not possible to use typings declared in a module for its Element or ElementClass.

When writing a module, it would then be convenient to write something like ;

```typescript
import {MyEltType, JSX}  from 'my-custom-jsx-lib'

var myelt = <div> ...</div>
```

and have typescript check Element, ElementClass and so on on its local JSX instance.

Also, when not providing any JSX namespace but having a factory that has a return type, the compiler crashes nastily with a 

```
/usr/lib/node_modules/typescript/lib/tsc.js:33078
                throw e;
                ^

TypeError: Cannot read property 'flags' of undefined
    at isRelatedTo (/usr/lib/node_modules/typescript/lib/tsc.js:16013:32)
    at checkTypeRelatedTo (/usr/lib/node_modules/typescript/lib/tsc.js:15941:26)
    at checkTypeAssignableTo (/usr/lib/node_modules/typescript/lib/tsc.js:15819:20)
    at isTypeAssignableTo (/usr/lib/node_modules/typescript/lib/tsc.js:15813:20)
    at getJsxElementAttributesType (/usr/lib/node_modules/typescript/lib/tsc.js:18463:47)
    at checkJsxOpeningLikeElement (/usr/lib/node_modules/typescript/lib/tsc.js:18564:40)
    at checkJsxSelfClosingElement (/usr/lib/node_modules/typescript/lib/tsc.js:18265:13)
    at checkExpressionWorker (/usr/lib/node_modules/typescript/lib/tsc.js:20439:28)
    at checkExpression (/usr/lib/node_modules/typescript/lib/tsc.js:20349:42)
    at checkExpressionCached (/usr/lib/node_modules/typescript/lib/tsc.js:20310:38)
```

**Comment by RyanCavanaugh** [comment] 2016-05-23 17:48
Regarding the first point, you can now do this using the `declare global {` syntax.

I'll take a look at the crash

**Comment by ceymard** [comment] 2016-05-24 10:08
By doing 

```typescript
declare global {

  namespace JSX {

  }

}

```

I get an `error TS2665: Module augmentation cannot introduce new names in the top level scope.`

Is there something I'm not seeing ?

**Comment by ceymard** [comment] 2016-05-24 12:21
Does this mean I **have** to have a `.d.ts` file declaring the namespace to be able to augment it ?

If so, would that mean that I would be limited to *extending* the JSX.Element, rather than define it altogether ?

**Comment by RyanCavanaugh** [comment] 2016-05-24 17:01
That error and restriction has been removed

**Comment by ceymard** [comment] 2016-05-24 22:31
Should I use a nightly build then ?

By the way I have tried to make a simple reproduction for the mentioned bug, but couldn't. The library that explodes as such is on github and I'd be delighted to show you how to reproduce if you wish.

**Comment by RyanCavanaugh** [comment] 2016-05-24 22:39
Yea, the nightly build should make that error go away.

A github repo for the bug would be great, always happy to look at those.

**Comment by ceymard** [comment] 2016-05-25 08:49
I just tested with typescript@1.9.0-dev.20160525-1.0 and the crash is no longer present.

There is a way of reproducing with 1.8.10 (I started a branch for this), are you still interested or do you consider this as resolved ?

**Comment by RyanCavanaugh** [comment] 2016-05-25 16:54
If it's fixed in the nightly then it's probably a duplicate of #7286

**Comment by ceymard** [comment] 2016-06-01 13:19
Since everything is working fine for me, shouldn't we mark this as closed ?

**Closed** 2016-06-01 23:23 UTC
Labels: Duplicate

**Comment by ellisonbg** [comment] 2017-06-07 22:36
We have a large extensible application where different extension authors might use different virtual dom libraries underneath TSX. Right now because `JSX` is expected to be global that is difficult. Allowing the `JSX` namespace to be resolved locally in a module would help a ton.

**Comment by mhegazy** [comment] 2017-06-08 00:54
@ellisonbg please see https://github.com/Microsoft/TypeScript/issues/15386
