### ISSUE TITLE
support interface key can be type string union type

### ISSUE THREAD

**Issue by Hental** [Microsoft/TypeScript#19208] opened 2017-10-16 11:48 UTC
**TypeScript Version:**  2.5.3
**Code**
```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
  interface StatesType {
    password: string;
    username: string;
    isLoad: boolean;
  }
  type typeNames = 'password' | 'username';
  
  class SignIn extends React.Component<object, StatesType> {
    render() {
      const inputEvent = (type: typeNames) => (e: any) => this.setState({ [type]: e.target.value });
      return <input onChange={inputEvent('username')} />
    }
  }
```
if i give a interface to react component, react setState function only accept state with one more key in given state, like this
```ts
  { password: '' }
  // or
  { username: '' }
```
i hope new state`s key is dynamic, but typescript inference it is
```ts
  interface {
    [x: string]: string;
  }
```
and not match the signature of setState and report an error.
**Expected behavior:**
  no error;
**Actual behavior:**
  Argument of type '{ [x: string]: string; }' is not assignable to parameter of type 'Pick<StatesType, "username" | "password" | "isLoad">'. Property 'username' is missing in type '{ [x: string]: string; }'.

**Comment by mhegazy** [comment] 2017-10-16 17:38
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/13948

**Comment by mhegazy** [comment] 2017-10-30 18:31
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-30 18:31 UTC
Labels: Duplicate
