### ISSUE TITLE
Discriminated Unions In Switch Statements Don't Respect Destructuring

### ISSUE THREAD

**Issue by agentilela** [Microsoft/TypeScript#15889] opened 2017-05-16 21:24 UTC
**TypeScript Version:**  2.3.2

**Code**

```ts
interface Square {
    kind: "square";
    size: number;
}
interface Circle {
    kind: "circle";
    radius: number;
}

type Shape = Square | Circle

const area = (s: Shape) => { //Works
    switch (s.kind) {
        case "square": return s.size * s.size;
        case "circle": return Math.PI * s.radius ** 2;
    }
}

const area = (s: Shape) => {
    const {kind} = s
    switch (kind) {
        case "square": return s.size * s.size; // size doesn't exist on Circle
        case "circle": return Math.PI * s.radius ** 2;  // radius doesn't exist on Square
    }
}


```

**Comment by mhegazy** [comment] 2017-05-16 21:37
Duplicate of https://github.com/Microsoft/TypeScript/issues/10976

**Comment by mhegazy** [comment] 2017-06-02 01:36
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-06-02 01:36 UTC
Labels: Duplicate
