### ISSUE TITLE
[Feature request] allow set type when use `let { a } = argv`

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#31049] opened 2019-04-20 20:39 UTC
## Suggestion

allow set type when use 

- `let { a } = argv` => `let { a as string } = argv`
- `({ a } = argv);` => `({ a as string } = argv);`

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by Mcfloy** [comment] 2019-04-21 18:52
You can already do this with `let { a } = argv as { a: string }`

**Comment by bluelovers** [comment] 2019-04-22 00:50
@Mcfloy i don't wanna do that waym when i use `let { a, b, c } = argv` and only `a` type is incorrect

**Comment by DanielRosenwasser** [comment] 2019-04-22 20:19
Duplicate of #7576.
Duplicate of #29526.

**Closed by DanielRosenwasser** 2019-04-22 20:19 UTC
