### ISSUE TITLE
Error on forget to use await on Promise in if condition

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#41511] opened 2020-11-12 14:24 UTC
PR: #39175 

<img src="https://user-images.githubusercontent.com/5390719/85197492-d6ef9f00-b313-11ea-83b4-52285b4f4ac3.png" />

**Comment by MartinJohns** [comment] 2020-11-12 14:33
Duplicate of #25330.

**Closed** 2020-11-16 18:00 UTC
Labels: Duplicate
