### ISSUE TITLE
Issue with systemjs and decorators

### ISSUE THREAD

**Issue by subesokun** [Microsoft/TypeScript#3441] opened 2015-06-09 12:46 UTC
Hi, I'm using TSC 1.5.3 (latest head) and I'm trying to compile following piece of code
```typescript
@SomeDecorator()
export class App {
  constructor() {
  }
}
```
```json
{"compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "system",
    "target": "es5"
}}
```
which will then produce following code
```javascript
var __decorate = ...;
var __metadata = ...;
System.register([], function(exports_1) { ... };
```

Now this doesn't really play nice together with systemjs and it works for me only when manually moving the `var __decorate` and `var __metadata` declarations into the anonymous function `function(exports_1) { ..here... }`.  Not sure if it's really valid to have these variable declarations outside of the `System.register`.

**Comment by subesokun** [comment] 2015-06-09 13:29
It seems like these declarations outside of `System.register` are crashing the format detection of systemjs. When adding manually a meta override as workaround like the following it's working again.

```javascript
System.config({
  "meta": {
    "app.js": {
      "format": "register"
    }
  }
});
```
(please note that these metadata overrides are first available starting from SystemJS 0.17.0)

**Comment by mhegazy** [comment] 2015-06-09 19:20
looks like a duplicate of #3364

**Closed** 2015-06-09 19:20 UTC

**Comment by subesokun** [comment] 2015-06-09 19:47
Thanks for the pointer, yes looks like a duplicate of  #3364
