### ISSUE TITLE
Primitive type narrowing doesn't respect re-assignment in function body

### ISSUE THREAD

**Issue by zachkirsch** [microsoft/TypeScript#50237] opened 2022-08-09 17:49 UTC
# Bug Report

### 🔎 Search Terms

narrowing inside function 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type narrowing

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220809&ssl=1&ssc=1&pln=2&pc=1#code/DYUwLgBAtgngQgewcCBeCAzAhsAziAbggHpiIEA7CACwQDcQAnAGmniRQEtcIwYAHEABMIWHgCMOILBQCwAKFIQIAPQD8ChbETISZSjXpNW2jhG4QKCAO68Bw0T2x4QCpes2KyAY2oyA5iBsOigYjAhQmDj4vAi8jACurvKJFADCCEIgABTZAJRoAHwQAN4KysqmuuhgiYQKAL55nlUoSga0DCzBZha4YJzAKHyCImJRLm5kHvIK3pS4yCAAdMAI-tmtBUrzjIwg3mDAMBD8jJwUYDy1SZ4YCRSHnAapGVnZqQBcEPlFEHQIThCApleQVCCpfIERpAA)

### 💻 Code

```ts
let myBool = false; // on hover, myBool is typed as boolean

myBool // on hover, myBool is now typed as false

// change myBool from false to true
runCode(() => {
    myBool = true;
})

myBool // on hover, myBool is still typed as false

console.log(myBool) // correctly prints true

function runCode(run: () => void) {
    run();
}
```

### 🙁 Actual behavior

`myBool` is a boolean and declared with `let`. It is allowed to be changed to from `false` to `true`, and indeed I do! But TypeScript doesn't realize that I've changed it, so it narrows the type (on hover) to `false` even after I've changed it.

### 🙂 Expected behavior

Either: (1) TS shouldn't narrow the type to `false` at all, or (2) TS should realize that the value may have changed on the `runCode(...)` line, and therefore not restrict the type to `false` after that function call.

**Comment by MartinJohns** [comment] 2022-08-09 17:52
Duplicate of #9998.

**Closed** 2022-08-12 18:00 UTC
Labels: Duplicate
