### ISSUE TITLE
computed property name in an interface error when using `[]` already

### ISSUE THREAD

**Issue by eyebrowkang** [microsoft/TypeScript#58179] opened 2024-04-13 05:45 UTC
### 🔎 Search Terms

A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.ts(1169)

### 🕗 Version & Regression Information

- This changed between versions 3.3 and 5.4.5

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/KYOwrgtgBAouEwB4EMIAcA2woG8BQUhUA1sAJ4CMUAvFAOSmV0A0BRD5AtAM7ADGAexAATOjXqMe-IaNYBfPHgCWIAC7AATgDNkfbAEk1mnXqSpM2fESgBtOJDPosAOkYUAugC4o3VRpUA5gDcbIR28I4WNhxkUoIidO5eUPAARpohCoRAA

### 💻 Code

```ts
enum EnumExample {
    key1 = 'key1',
    'key-second' = 'key-second',
}

interface InterfaceExample {
    [EnumExample.key1]: string;
    [EnumExample['key-second']]: number;
}
```

### 🙁 Actual behavior

Has Error: `A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.ts(1169)`

### 🙂 Expected behavior

No Error

**Comment by MartinJohns** [comment] 2024-04-13 06:55
Duplicate of #25083.

**Comment by jcalz** [comment] 2024-04-13 11:44
Regression information is incorrect; this didn’t change between TS3.3 and current (it didn’t work in TS3.3 either).

**Closed** 2024-04-18 01:25 UTC
Labels: Duplicate
