### ISSUE TITLE
TypeScript Language Server False Positive Error Reporting

### ISSUE THREAD

**Issue by DScheglov** [microsoft/TypeScript#57585] opened 2024-02-28 22:41 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Clone the project `git clone https://github.com/DScheglov/res-test.git`
2. Open the VS Code: `code res-test`
3. Install dependencies (in terminal): `npm i`
4. Open file `./src/index.ts`

The following errors are shown:
![image](https://github.com/microsoft/vscode/assets/9888941/aca72243-17aa-4cff-956d-e029bc5d4c38)

These errors are false positive:
1. project is configured to use the same typescript compiler as a project. See `.vscode/settings.json`
2. project is compiled successfully via terminal: `npx tsc` (no errors)
3. errors are gone after TS Language Server is restared (`Ctrl + Shift + P` , TypeScript: Restart TS Server)
4. errors go back after any touch of the file (just add a space).

There is not such problem in WebStorm
![image](https://github.com/microsoft/vscode/assets/9888941/f679d7dc-a661-4937-b2a6-235c419c8056)
(Sorry, I have to check)

Errors are not displayed in the TS Playground as well:
[Playground](https://www.typescriptlang.org/play?jsx=0&module=1#code/JYWwDg9gTgLgBAbzgJQKYGcCuAbGAaOCAawNSigIBEI4BfOAMyghDgHIABAYwEMoATVNmzAAdsAD0MdAFooGHDDYBuAFCqYATzCo4ABTLoIouAF5EquHFE8QqAFxx0MKGIDmaqzzcPrmEABGZGq0ahraugBSRqIA8gEAVqhc8OZoXND8ADzOrqJuBJiiRKIQAO6iAHxhGaLOhEQAkgzxSSlmcAAUAG482Ji+RSXlogCUjmhYuFnRxq3J+OwAosjIAPoAcrEAKmsAghtrsQBCkUsAwttslWaVlnBaOhAMcL39uqaf7BCJC2xwADIAa8+gM4ABCL6iHDYe5WAD8DR6oN0PHQcFmcV+KVGcLgjjIUE6bBW6y2uwOR1OFyuoxqxnqxGajVEqS6bwGjiGpQq4xQCmm0MCZAIJNWmx2+0OjQ2VxupjuVg2-iCUAAdMB0CyYKgfESOahcVYEUiDXA0X5hVAjcaCeRiaSJRTpbK2HT1LVGU0GHoIOhgDBgN0PuyUY4haq+ZNFFkIyLluLyWs9LEAMqNbaNABqS2ut3uZpuAAY4IjiMj3qN8XBCQ7E5KU+nMzm3fS6vAmQwNhAYEtwFpUy4OhXOXBuSMowKYFl7rl3Hh7mKyZK9mtU9tkDKAOL-AA+CfWSwAsnptgBNNcb7dsVTyxUPCLPEHvCFfNhz-L-RG1pdO-aXzcNh3Kt7ALFE1WwVB8hgAALMwvhLb97V-Y9TwvddAOA-F7nLA13XCHQ4CzPpgH4HhA2MJZyGgLIlhrAAPHVRH4dEPzceVEDgMByJgxw2IAbQAXWUOAMkERwlhE0IPQZeA3lI8jgEo6ioA6WiGKYlinBcdxKk6e5uNgvidPyISCDE3wllUPliJEMiKNEKjmCgWi7y6JBDJg8yIEEOh8MeXQDCgGJbIUhynOgDpQvspTHJUmcrH3X8k0pE4zkuG9EoPP9KRlK57iSx0k0bDNs1zArspSgDrwqlCT3PaqgJvap1FQejIFgUTZIaZogpiABGYcDS5YoeTGfMrGoToGCKFJYoAKk6KsEDxT0O2xNlNGAIR+HmnqWg2kdDTVEAeDAJz9ONY1CUihVnzC2KIqJMyaxUm0rHwq61usWwQy2na9s7bte37TRByJH42hgNUbDsUYTrOi68SsG7VLu+SYuU5zOn4thYdQNhBNIN68U+41vu8P7tuwXb9u1TpIYWNVKfhrgYJ4MQGe9X1-UDYN4dO877WR17nNue7Mbi7Hccpwniec964DJqx5BgTAoBMJB8YISm6E8Pywjajr4G+zs+uMAAmYcwPeEbhgqBcrE84y8jcISOlxnRguMOXrImuAppm0Q5uMQHucMYxIh+JaLC+7rIY6f6abD5p5hSI7FasBGhaJVHxYxxSsegTpPPl6BRmVrr2x+uxE+p2mgZ7PswAHFwGcSGHfszuBs4uvP0ZIyWnpxtVR9L9h8bl0Xy8rimfDrgG6dZduEmZnxWfZzmzb9AMg0NEXe-tfubgL8KVJHseeNFWWien61K9V9XNZr1Adfn6SrFofDTfD72THMM2EdRAWzbEYSCEEIBuC5r1IBnQta-UcGwKOMFRBsDfr4AALFbL+7oJASDgLEIgnFhqcXxog5BqD0GOCwXQOgMk6gQHAdgSB0CfSwPgXYchEAUFoPND4RwMgaE4LUHguATlOKo0cB5Hijh+LsFlnAW+FlEFFQbGmUqLZaG0HoWA1AECoGAL-nAl+iDeGU2odgiuIj8HiKQJIzizs4ByLxr9f4SifK+DqmhRqO4tE6MYXo5hBjf4xGMWQuAWCqERMsbgmx5AJEqSkVxGRTiJ6uMUd5cSlUVw+P+PQbRqhPQBP0aw82ogwkIPYBQvJVjVCiNsXfJJjjnEKPcVk5KK4XRXD8YUhkxSgmlPYXwzBMTrFiPiXYxJDiUnOMnhkrq7TVEUlyT0opTCWGGNCWwN0sTxmqUmc5JpMy2meKWVKKk6Vun5P8es4JMCjHQmELU+pEzGnTKMk4k5Kj6zOguTSPJdDekMNuYMoxRRBAMDEKgfgzy4n7LedIj5L1lHZN+Wlf5PTVBAA)

**Comment by RyanCavanaugh** [comment] 2024-02-29 23:26
Minimized repro
```ts
export interface Result<T, E> {
  mapErr<F>(fn: (error: E) => F): Result<T, F>;
  [Symbol.iterator](): Generator<E, T>;
}

declare const okIfObject: (value: unknown) => Result<Record<string, unknown>, 'ERR_NOT_AN_OBJECT'>;
declare const okIfInt: (value: unknown) => Result<number, 'ERR_NOT_AN_INT'>;
export declare function Do2<T, E>(job: () => Generator<E, T>): void;

declare let value: unknown;
Do2(function* () {
  const object = yield* okIfObject(value).mapErr(
    error => 0
  );

  const age = yield* okIfInt(object.age).mapErr(
    error => 0
  );

  return { age };
});
```

**Comment by DScheglov** [comment] 2024-03-01 09:53
@RyanCavanaugh 

I've met similar error from eslint:
![image](https://github.com/microsoft/TypeScript/assets/9888941/53eca2c4-4f42-4749-a13d-5d04dcb1aa55)

Shoud I register the bug in `@typescript-eslint`? Or there  it will be fixed after this one?

**Comment by RyanCavanaugh** [comment] 2024-03-01 17:24
I'm not sure how their rule works. If it depends on type information (looks like it does) then that error should go away after we fix this one.

**Comment by Andarist** [comment] 2024-03-03 14:32
Analyzing Ryan's simplified repro the problem comes from `encodedSemanticClassifications-full` that is called before semantic diagnostics. It breaks the regular order of type checking since while collecting tokens it calls `reclassifyByType` on `object`'s declaration. That reads its type and to do that it has to resolve the type of the yield expression. That is a function call that has to be inferred (speaking about `.mapErr` here) and that depends on the contextual type of the yield operand, that in turn requires the return type of the containing function to be computed which leads to computing type of the return expression and that depends on... `object`'s type. That's how the circularity arises.

Failing test case for this situation:
```ts
// @strict: true
// @target: esnext
// @lib: esnext

//// export interface Result<T, E> {
////   mapErr<F>(fn: (error: E) => F): Result<T, F>;
////   [Symbol.iterator](): Generator<E, T>;
//// }
////
//// declare const okIfObject: (
////   value: unknown,
//// ) => Result<Record<string, unknown>, "ERR_NOT_AN_OBJECT">;
////
//// declare const okIfInt: (value: unknown) => Result<number, "ERR_NOT_AN_INT">;
////
//// export declare function Do2<T, E>(job: () => Generator<E, T>): void;
////
//// declare let value: unknown;
////
//// Do2(function* () {
////   const object = yield* okIfObject(value).mapErr((error) => 0);
////   const age = yield* okIfInt(object.age).mapErr((error) => 0);
////   return { age };
//// });

verify.encodedSemanticClassificationsLength('2020', 132);
verify.getSemanticDiagnostics([]);
```

**Comment by Andarist** [comment] 2024-03-03 20:57
I spent some time on this to learn what the proper fix could be. I concluded that the only proper fix for this has to be about making the cycle resolution logic smarter - or for the "out of order" type resolution to alter its behavior somehow. 

No extra flags passed down by the caller can fix this because the compiler doesn't always control the caller. For instance, I managed to somewhat improve the situation locally for the test case above but that didn't fix quick info problem at the very same location:
```ts
/// <reference path="fourslash.ts" />

// @strict: true
// @target: esnext
// @lib: esnext

//// export interface Result<T, E> {
////   mapErr<F>(fn: (error: E) => F): Result<T, F>;
////   [Symbol.iterator](): Generator<E, T>;
//// }
////
//// declare const okIfObject: (
////   value: unknown,
//// ) => Result<Record<string, unknown>, "ERR_NOT_AN_OBJECT">;
////
//// declare const okIfInt: (value: unknown) => Result<number, "ERR_NOT_AN_INT">;
////
//// export declare function Do2<T, E>(job: () => Generator<E, T>): void;
////
//// declare let value: unknown;
////
//// Do2(function* () {
////   const object/*1*/ = yield* okIfObject(value).mapErr((error) => 0);
////   const age = yield* okIfInt(object.age).mapErr((error) => 0);
////   return { age };
//// });

verify.quickInfoAt("1", "const object: Record<string, unknown>");
```

One of those calls `checker.getTypeAtLocation` while the other one calls `checker.getTypeOfSymbolAtLocation`. The problem with any attempt to fix this by passing extra information through callers/links/whatever is that it won't fix raw API calls like this: `checker.getTypeOfSymbol(checker.getSymbolAtLocation(node))`.

**Comment by RyanCavanaugh** [comment] 2024-03-06 22:27
Additional repro noted at https://github.com/microsoft/TypeScript/issues/57429#issuecomment-1981202521

**Comment by DScheglov** [comment] 2024-03-22 12:32
@RyanCavanaugh 
I've found one more bug in TypeScript, but I'm not sure if it is related to this one. Could you please check:
https://github.com/microsoft/TypeScript/issues/57903

**Comment by mikearnaldi** [comment] 2024-04-25 02:36
Tracking as https://github.com/Effect-TS/effect is also hit by this

**Comment by DScheglov** [comment] 2024-04-25 08:48
@mikearnaldi 

Yep, I was surprised that I found the bug before the Effect team did.
Could you please check if https://github.com/microsoft/TypeScript/issues/57903 is also relevant for Effect-TS?

**Comment by mikearnaldi** [comment] 2024-04-25 09:05
> @mikearnaldi
> 
> Yep, I was surprised that I found the bug before the Effect team did. Could you please check if #57903 is also relevant for Effect-TS?

the reason we didn't find the bug before is that we were using an adapter function so instead of `yield* x` it would have been `yield* $(x)` for some obscure reason the adapter variant doesn't raise the issue

**Comment by mikearnaldi** [comment] 2024-04-25 09:06
https://github.com/microsoft/TypeScript/issues/57903 doesn't affect Effect as we don't use async generators (provided I've understood the issue correctly)

**Comment by jakebailey** [comment] 2024-04-26 03:09
I tried an absolutely terrible idea; in `getTypeOfNode`, I checked to see if the node is a child of a generator function, then do `getReturnTypeOfSignature(getSignatureFromDeclaration(containingFunction))`. This fixed the test case in https://github.com/microsoft/TypeScript/issues/57585#issuecomment-1975182526 without breaking any other tests, and is likely not slower because that info is cached (we're just forcing it to resolve early). But that doesn't work for the test case from https://github.com/microsoft/TypeScript/issues/57429#issuecomment-1981202521, and I'm sure there are other paths that could hit that.

**Comment by mikearnaldi** [comment] 2024-04-26 05:15
> I tried an absolutely terrible idea; in `getTypeOfNode`, I checked to see if the node is a child of a generator function, then do `getReturnTypeOfSignature(getSignatureFromDeclaration(containingFunction))`. This fixed the test case in [#57585 (comment)](https://github.com/microsoft/TypeScript/issues/57585#issuecomment-1975182526) without breaking any other tests, and is likely not slower because that info is cached (we're just forcing it to resolve early). But that doesn't work for the test case from [#57429 (comment)](https://github.com/microsoft/TypeScript/issues/57429#issuecomment-1981202521), and I'm sure there are other paths that could hit that.

Would it be possible to get a snapshot with this idea to test in the effect codebase if it solves all the instances of this issue?

**Comment by jakebailey** [comment] 2024-04-26 05:52
Sure; watch https://github.com/microsoft/TypeScript/pull/58323 for a build once the pipeline completes.

**Comment by mikearnaldi** [comment] 2024-04-26 07:06
Unfortunately it seems like it doesn't fix the issue, rather it does but it makes it appear in a different place, the return of the generator

<img width="659" alt="Screenshot 2024-04-26 at 09 05 36" src="https://github.com/microsoft/TypeScript/assets/24249610/43a5b426-584c-4338-a0cc-8f78dff1bc9f">

**Comment by Andarist** [comment] 2024-04-26 07:55
IIRC I had an idea to utilize the existing `resolutionStart` to ignore some leading elements in `findResolutionCycleStartIndex`. While that was nice and has proven to be somewhat promising, I failed to generalize the idea and handle properly nested calls etc

**Comment by jakebailey** [comment] 2024-04-26 17:22
Interestingly, a modified https://github.com/microsoft/TypeScript/issues/57585#issuecomment-1975182526 to omit the return like the above is also fixed by my hack, which implies that the error being produced above is a cycle caused by some other query than semantic tokens. tsserver trace logs (`"typescript.tsserver.log": "verbose"`) would be interesting here to figure out what path happened to be turned into a test case.

**Comment by mikearnaldi** [comment] 2024-04-26 17:28
the full code to repro this is:

```ts
import { Effect } from "effect"

Effect.gen(function* () {
  const a = yield* Effect.succeed(0)
  const b = yield* Effect.succeed(1)
})
```

the bug presents while you edit, like adding a new line, making changes in general

**Comment by mikearnaldi** [comment] 2024-04-26 17:41
Not sure if helpful but you can find the log from tsserver here: https://gist.github.com/mikearnaldi/fc2c4f15135b034d62f0625de82557f4

**Comment by jakebailey** [comment] 2024-04-26 18:10
Yeah, that log's really long (the error doesn't happen until message 1020), so would need something shorter. That and you're using a language service plugin, which we generally treat as "voiding all warranties" when it comes to us trying to figure out what's wrong. But I don't think it matters in this case (but do try without it).

I can't get that example to reproduce myself, though, only with the return present...

**Comment by mikearnaldi** [comment] 2024-04-26 18:20
Much shorter log without the plugin: https://gist.github.com/mikearnaldi/70037e879777f1f3243d0496559c2a99 

To reproduce delete the second line:

```ts
const b = yield* Effect.succeed(1)
```

and re-type it manually, error should appear.

I wonder if I can use replay.io to record a session here cc @Andarist

**Comment by jakebailey** [comment] 2024-04-26 18:43
That log looks truncated; the main reason for the log is to find the steps to get to the bad error, so we need steps from the first message all the way to the error to be able to write an equivalent test which touches everything in the right way. (Hence why a full log and a short one is helpful.)

I still wasn't able to make it reproduce when typing it out by hand, though... It's possible my editor did not make the same sequence of calls, of course.

**Comment by mikearnaldi** [comment] 2024-04-26 18:50
Try a few times to delete and retype, it's sporadic, doesn't happen always. Will provide a full log tomorrow

**Comment by Andarist** [comment] 2024-04-26 19:04
Is there a strong need to provide an extra repro for this if we already have 3 compiler tests written for this here? ;p

**Comment by jakebailey** [comment] 2024-04-26 19:14
I figured that would be helpful given I fixed the cases that looked `effect`-y, but it didn't help in the real world? That to me implied that there are still more cases missing, but sorry for the noise.

**Comment by ahejlsberg** [comment] 2024-04-26 21:02
I working on a fix for this, I'll put something up later this afternoon.

**Closed** 2024-04-29 21:27 UTC
Labels: Bug, Fix Available
