### ISSUE TITLE
Type query for a result of a function call

### ISSUE THREAD

**Issue by Strate** [Microsoft/TypeScript#6239] opened 2015-12-24 14:40 UTC
Is it possible to use `typeof` type query operator to get function's return type?

**Comment by Strate** [comment] 2015-12-24 19:27
Seems that no. It would be great to do something like:

```
declare var do: (arg: string) => number

let a: typeof do // a now has (arg: string) => number type
let b: typeof do() // b now has number type
```

**Comment by DanielRosenwasser** [comment] 2015-12-25 00:57
This comment is related: https://github.com/Microsoft/TypeScript/issues/2710#issuecomment-131243298https://github.com/Microsoft/TypeScript/issues/2710#issuecomment-131243298

**Comment by yortus** [comment] 2015-12-25 01:09
Duplicate of #4233?

**Comment by tinganho** [comment] 2015-12-25 04:16
I have also encountered this problem many times.

**Comment by aleksey-bykov** [comment] 2015-12-25 08:54
What would be the inferred type in the following situation?

```typescript
function fn<a>(value: a) : { value: a; } { return { value: value }; }
let a: typeof fn;
```

If the answer is `{value: {}}` (assuming the current state of affairs) then such feature is useless.

@DanielRosenwasser, how feasible is it to allow variables to hold unresolved type parameters? 

Might be related #5959

**Comment by Strate** [comment] 2015-12-25 09:00
I think answer should be an error about required type argument, and developer should write
```typescript
let a: typeof fn<number>()
```
to get `{value: number}`

**Comment by aleksey-bykov** [comment] 2015-12-25 09:04
@Strate 
this is pure syntax sugar over
```typescript
let b = fn<number>();
let a = typeof b;
```
if this is what you are looking for then it might be better phrased as "Type query for a result of a function call"

**Comment by Strate** [comment] 2015-12-25 10:01
You are right, I'm gonna to change the caption :)

**Comment by tinganho** [comment] 2015-12-25 11:53
I'm wondering how this would handle overloaded functions? I guess one must pass in the type of the arguments to let it overload correctly the return type.
```typescript
function f(a: string): string;
function f(a: string, b: number): boolean;
function f(a: string, b?: string | number, c?: string): boolean | string {
	return true;
}

typeof f(string, number) // boolean
```
Isn't ellipses `...` a better syntax for not overloaded functions? Because only `f()` (no arguments) doesn't corresponds to the function signature `f(a: string)` (with one arguments).
```typescript
function f(a: string): boolean;
typeof f(...) // boolean
```

**Comment by yortus** [comment] 2015-12-25 13:40
@tinganho #4233 takes care of that - just use any valid expression - like `typeof f("", 0)`

**Comment by yortus** [comment] 2016-01-25 08:39
Proposal + implementation that covers this: #6606

**Closed** 2016-01-25 17:07 UTC
Labels: Duplicate
