### ISSUE TITLE
"Inline temporary variable" quickfix

### ISSUE THREAD

**Issue by srmagura** [microsoft/TypeScript#46440] opened 2021-10-20 03:18 UTC
# Suggestion

## 🔍 Search Terms

- Quickfix, quick fix
- Inline temporary variable, inline variable, temporary variable

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ✔️ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ✔️ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ✔️ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ✔️ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ✔️ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

C# has a nice quickfix called "inline temporary variable":

![image](https://user-images.githubusercontent.com/801549/138020816-9a4d10de-1fc3-40ca-8a21-cf7c155bc386.png)

I propose adding an equivalent quickfix to TypeScript.

## 📃 Motivating Example

Developers frequently define variables and then only use them in one place. Inlining such variables can make the code more succinct and readable. As with all quickfixes, this quickfix would simply be a convenient shortcut for what you can already do by hand.

For example, the quickfix would transform this code:

```ts
const message = 'Failed to activate foobars.'
throw new Error(message)
```

into

```ts
throw new Error('Failed to activate foobars.')
```

## 💻 Use Cases

- Automate the process of inlining temporary variables that are only used once (in both JavaScript and TypeScript code)
- (???) Automate the process of inlining temporary variables that are used more than once. The C# quickfix does support this but I'm not sure if it's a useful feature, since inlining a variable that is used multiple times results in duplication.

We would need to define exactly which variable declarations are eligible for this quickfix. I'm not sure since I'm not a compiler person.

**Comment by DanielRosenwasser** [comment] 2021-11-04 01:02
Duplicate of #18459

**Closed** 2021-11-04 01:02 UTC
Labels: Duplicate
