### ISSUE TITLE
[Bug] Generic type extending an Array can not be used as rest params

### ISSUE THREAD

**Issue by bogdan** [microsoft/TypeScript#38767] opened 2020-05-25 14:20 UTC
**TypeScript Version:**  3.9.3

**Search Terms:**

* Rest element type
* Generics

**Code**

```ts
type E<T extends any[]> = [...T]
```

**Expected behavior:**

No compilation error.

**Actual behavior:**

```
2574: A rest element type must be an array type.
```

**Playground Link:** 

https://www.typescriptlang.org/play?#code/C4TwDgpgBAogPAFShAHsCA7AJgZygQwxAG0BdAPigF4piA6BhUgbgChWg

**Comment by ahejlsberg** [comment] 2020-05-25 18:51
Duplicate of #26113.

**Closed** 2020-05-26 05:38 UTC
Labels: Duplicate
