### ISSUE TITLE
No Project errors in TS Server

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20357] opened 2017-11-30 01:46 UTC
Copied over from https://github.com/Microsoft/vscode/issues/30948

@otake  reports:

Steps to Reproduce:

1. Add allowJs: true to compilerOptions in tsconfig.json
2. Reload Window
3. Try to "Find All References" on anything in a .ts file
4. Always returns no results
5. Remove allowJs option from tsconfig.json
6. Reload Window
7. Try to "Find All References" again and it works!

**Comment by mjbvz** [comment] 2017-11-30 01:47
Reported TS server log with 2.6:

```
{"seq":0,"type":"response","command":"quickinfo","request_seq":28,"success":true,"body":{"kind":"function","kindModifiers":"","start":{"line":352,"offset":10},"end":{"line":352,"offset":22},"displayString":"function getShapeIcon(icon: IShapeIcon): JSX.IntrinsicElements","documentation":"","tags":[]}}
Info 1755 [15:28:26.34] request:
    {"seq":29,"type":"request","command":"quickinfo","arguments":{"file":"/mypath/app/xv/diagram/Shape.tsx","line":352,"offset":16}}
Info 1756 [15:28:26.34] Starting updateGraphWorker: Project: /mypath/tsconfig.json
Info 1757 [15:28:26.34] Finishing updateGraphWorker: Project: /mypath/tsconfig.json structureChanged: false Elapsed: 0ms
Perf 1758 [15:28:26.35] 29::quickinfo: elapsed time (in milliseconds) 1.0181
Info 1759 [15:28:26.35] response:
    {"seq":0,"type":"response","command":"quickinfo","request_seq":29,"success":true,"body":{"kind":"function","kindModifiers":"","start":{"line":352,"offset":10},"end":{"line":352,"offset":22},"displayString":"function getShapeIcon(icon: IShapeIcon): JSX.IntrinsicElements","documentation":"","tags":[]}}
Info 1760 [15:28:29.198] request:
    {"seq":30,"type":"request","command":"references","arguments":{"file":"/mypath/app/xv/diagram/Shape.tsx","line":352,"offset":16}}
Err 1761  [15:28:29.208] Exception on executing command {"seq":30,"type":"request","command":"references","arguments":{"file":"/mypath/app/xv/diagram/Shape.tsx","line":352,"offset":16}}:

    No Project.

    Error: No Project.
    at Object.ThrowNoProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:81131:23)
    at IOSession.Session.getProjects (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85879:42)
    at IOSession.Session.getReferences (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85977:37)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85247:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86660:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86669:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86689:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:87881:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
Info 1762 [15:28:29.208] response:
    {"seq":0,"type":"response","command":"references","request_seq":30,"success":false,"message":"Error processing request. No Project.\nError: No Project.\n    at Object.ThrowNoProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:81131:23)\n    at IOSession.Session.getProjects (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85879:42)\n    at IOSession.Session.getReferences (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85977:37)\n    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85247:61)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86669:88\n    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86660:28)\n    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86669:33)\n    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86689:35)\n    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:87881:27)\n    at emitOne (events.js:96:13)\n    at Interface.emit (events.js:191:7)\n    at Interface._onLine (readline.js:241:10)\n    at Interface._normalWrite (readline.js:384:12)\n    at Socket.ondata (readline.js:101:10)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:191:7)\n    at readableAddChunk (_stream_readable.js:178:18)\n    at Socket.Readable.push (_stream_readable.js:136:10)\n    at Pipe.onread (net.js:560:20)"}
Info 1763 [15:28:29.221] request:
    {"seq":31,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/mypath/app/xv/diagram/Shape.tsx","startLine":352,"startOffset":16,"endLine":352,"endOffset":16}}
Info 1764 [15:28:29.221] Starting updateGraphWorker: Project: /mypath/tsconfig.json
Info 1765 [15:28:29.221] Finishing updateGraphWorker: Project: /mypath/tsconfig.json structureChanged: false Elapsed: 0ms
Perf 1766 [15:28:29.221] 31::getApplicableRefactors: elapsed time (in milliseconds) 0.5031
Info 1767 [15:28:29.221] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":31,"success":true,"body":[]}
Info 1768 [15:28:30.713] request:
    {"seq":32,"type":"request","command":"occurrences","arguments":{"file":"/mypath/app/xv/diagram/Shape.tsx","line":352,"offset":18}}
Info 1769 [15:28:30.714] Starting updateGraphWorker: Project: /mypath/tsconfig.json
Info 1770 [15:28:30.714] Finishing updateGraphWorker: Project: /mypath/tsconfig.json structureChanged: false Elapsed: 0ms
Perf 1771 [15:28:30.720] 32::occurrences: elapsed time (in milliseconds) 6.7359
Info 1772 [15:28:30.720] response:
    {"seq":0,"type":"response","command":"occurrences","request_seq":32,"success":true,"body":[{"start":{"line":288,"offset":26},"end":{"line":288,"offset":38},"file":"/mypath/app/xv/diagram/Shape.tsx","isWriteAccess":false},{"start":{"line":352,"offset":10},"end":{"line":352,"offset":22},"file":"/mypath/app/xv/diagram/Shape.tsx","isWriteAccess":true}]}
Info 1773 [15:28:31.91] request:
    {"seq":33,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/mypath/app/xv/diagram/Shape.tsx","startLine":352,"startOffset":10,"endLine":352,"endOffset":22}}
Info 1774 [15:28:31.91] Starting updateGraphWorker: Project: /mypath/tsconfig.json
Info 1775 [15:28:31.91] Finishing updateGraphWorker: Project: /mypath/tsconfig.json structureChanged: false Elapsed: 0ms
Perf 1776 [15:28:31.92] 33::getApplicableRefactors: elapsed time (in milliseconds) 1.0031
Info 1777 [15:28:31.92] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":33,"success":true,"body":[]}
Info 1778 [15:28:32.140] request:
    {"seq":34,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/mypath/app/xv/diagram/Shape.tsx","startLine":288,"startOffset":26,"endLine":288,"endOffset":38}}
Info 1779 [15:28:32.140] Starting updateGraphWorker: Project: /mypath/tsconfig.json
Info 1780 [15:28:32.140] Finishing updateGraphWorker: Project: /mypath/tsconfig.json structureChanged: false Elapsed: 0ms
Perf 1781 [15:28:32.141] 34::getApplicableRefactors: elapsed time (in milliseconds) 1.1401
Info 1782 [15:28:32.141] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":34,"success":true,"body":[]}
Info 1783 [15:28:50.306] request:
    {"seq":35,"type":"request","command":"quickinfo","arguments":{"file":"/mypath/app/xv/workflowBuilder/components/TaskStepSettings.tsx","line":117,"offset":3}}
Info 1784 [15:28:50.307] Starting updateGraphWorker: Project: /mypath/tsconfig.json
Info 1785 [15:28:50.307] Finishing updateGraphWorker: Project: /mypath/tsconfig.json structureChanged: false Elapsed: 0ms
Perf 1786 [15:28:50.307] 35::quickinfo: elapsed time (in milliseconds) 1.0803
Info 1787 [15:28:50.308] response:
    {"seq":0,"type":"response","command":"quickinfo","request_seq":35,"success":false,"message":"No content available."}
```

**Comment by otake** [comment] 2017-12-05 03:53
Oh wow, setting `disableSizeLimit` to true in the compiler options worked! Thanks so much. Our project does have a ton of files.

I see this in the log :
`Info 1671 [20:50:24.162] 	Files (1579)`
I suppose that is the file count?

**Comment by sheetalkamat** [comment] 2017-12-05 18:56
@otake Yes thats the file count in the project. Is it same with or without allowJs set to true? If not what's the diff.

**Comment by otake** [comment] 2017-12-05 22:32
No definitely not the same, we are slowly transitioning over to TS.
```
allowJs: true  -> Files (1579)
allowJs: false -> Files (432)
```

diff = 1,147 files

**Comment by sheetalkamat** [comment] 2017-12-06 19:13
You can diff the files reported in tsserver and see if you can edit your tsconfig file to exclude the files that you don't want. Note that the tsconfig specifies the root files to include but your included files are importing modules/referencing files from the excluded set, they will still be included.

**Comment by sheetalkamat** [comment] 2017-12-06 19:14
Since this is really not a bug but by design I am closing this bug, but feel free to report if anything seems out of normal. Thanks.

**Closed by sheetalkamat** 2017-12-06 19:14 UTC
Labels: Bug, VS Code Tracked
