### ISSUE TITLE
Type and interface have different behavior in index signature extends checking.

### ISSUE THREAD

**Issue by ruojianll** [microsoft/TypeScript#57810] opened 2024-03-17 06:30 UTC
### 🔎 Search Terms

"extends", "type and interface"

### 🕗 Version & Regression Information

version all

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.2#code/C4TwDgpgBAKu0F4oG8BQUNQIYC4oDsBXAWwCMIAnVAX1VQEt9hKAzLAY2gEknWPo0mbHiJlKNOqEhQAglCRxpEAB7N8AEwDOUAEoR2AewrqAPJuAVGAcwA0BEuQoA+KAH4oFwtDxsANpugAekDPCFQpaAAheSgeZgo2TigVNS1dfSNTc0t8W3sxZzcPCi8oHyx-IMC-ANQgA

### 💻 Code

```ts
type Type = {
    a: number
}

interface Interface {
    a: number
}

type A = Type extends Record<string, number> ? true : false //true
type B = Interface extends Record<string, number> ? true : false //false
```

### 🙁 Actual behavior

type A is true
type B is false

### 🙂 Expected behavior

both true or false

**Comment by ruojianll** [comment] 2024-03-17 06:31
I can't find any document about the difference about this.

**Comment by MartinJohns** [comment] 2024-03-17 07:55
Duplicate of #42825. See also https://github.com/microsoft/TypeScript/issues/15300#issuecomment-332366024.

Used search terms: `interface type record in:title`

**Closed** 2024-03-17 14:00 UTC
