### ISSUE TITLE
Add abstract support to new

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#41197] opened 2020-10-22 09:50 UTC
## Search Terms

abstract new

## Suggestion

```
type X = { abstract new () :object };
```

## Use Cases

To ensure an fn arg is an constructor but can't directly construct.

## Examples

```
declare function fn (constructor :{ abstract new () :object }) :void;

fn(               {                             }); // error, must be class
fn(         class {                             }); // error, must be class and can't as new.target
fn(         class { protected constructor () {} }); // error, must be class and can't as new.target even in it self
fn(abstract class {                             }); // right
fn(abstract class { protected constructor () {} }); // right
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment] 2020-10-23 00:11
Seems like @rbuckton's #36392 fixes this. I don't know if I can technically mark this as a duplicate of #26829 or #35576 because it's not clear that either of them have suggested the specific feature.

**Closed** 2020-10-23 03:37 UTC
