### ISSUE TITLE
ts不支持jsx plus特性，希望能尽快支持

### ISSUE THREAD

**Issue by Le-seul** [microsoft/TypeScript#49534] opened 2022-06-14 02:24 UTC
![image](https://user-images.githubusercontent.com/43976075/173480180-ed3ac859-6c62-4549-94cb-935cf0b95f30.png)

**Comment by fatcerberus** [comment] 2022-06-14 02:32
duplicate of https://github.com/microsoft/TypeScript/issues/49513 😕

**Closed** 2022-06-16 18:00 UTC
Labels: Duplicate
