### ISSUE TITLE
Union type with option field and expressions order in if statement

### ISSUE THREAD

**Issue by arusakov** [Microsoft/TypeScript#20533] opened 2017-12-07 11:59 UTC
**TypeScript Version:**  2.7.0-dev.20171207

**Code**
```ts
// test via "tsc --noEmit --strict test.ts"

type Type1 = {
  type: 1,
  val?: string,
}

type Type2 = {
  type: 2,
  val: string,
}

type Type = Type1 | Type2

function test1(x: Type) {
  if (!x.val || x.type !== 1) {
    return
  }
  const y: string = x.val // Error: Type 'string | undefined' is not assignable to type 'string'.
}

function test2(x: Type) {
  if (x.type !== 1 || !x.val) { // check x.val after x.type
    return
  }
  const y: string = x.val // OK here
}
```
**Expected behavior:**
No error in `test1` function.

**Actual behavior:**
Wrong type inference of `x.val` in `test1`.

**Comment by mhegazy** [comment] 2018-01-30 23:52
This is a design limitation of how type narrowing works. `!x.val` here only narrows the type of `x.val` and not that of `x` to `Type2`. the issue here is that narrowing only limits the set of possible types a symbol can have, but does not introduce a new type.. doing so, we fear will result in a big performance degradation to the entire system.

In the first case, the compiler processes `!x.val`, narrowing the type of `x.val` to `string` from `string | undefined`. it then processes `x.type !== 1`, since `type` here is a discriminant property, it narrows the type of `x` to `Type1`. this change to the type of `x` causes a reset to any narrowing assumptions that happened earlier, leaving `x.val` `string | undefined`. In the second case, the compiler narrows `x` to `Type1` first, then narrows the type of `x.val` to `string`.

**Comment by mhegazy** [comment] 2018-01-30 23:53
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/18840

**Closed** 2018-02-15 17:55 UTC
Labels: Duplicate
