### ISSUE TITLE
No IntelliSense for "export from" syntax

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9115] opened 2016-06-13 06:38 UTC
_From @ChenMachluf on June 9, 2016 14:56_

Hi,
I'm using the "export from" syntax and it seems that it doesn't working well with the intellisense.
For now I'm using a workaround by importing and then exporting in two separate lines.

![animation4](https://cloud.githubusercontent.com/assets/6990608/15934122/feaaa8b4-2e6a-11e6-8026-dfe90e51de03.gif)

tnx 

- VSCode Version: 1.2.0
- OS Version: Windows 10

_Copied from original issue: Microsoft/vscode#7482_

**Comment by mhegazy** [comment] 2016-06-13 19:58
I do not think goto def on "Person2" here should take you to the other file. this would be the issue we need to fix.

`Person1` and `Person2` are local names, and goto def should not work on them. it should work on the both instances of `Person` though.

**Comment by andy-ms** [comment] 2016-08-24 19:47
The `export Person from "./person"` syntax isn't currently supported.
You can re-export non-default exports (`export {Person} from './person'` where './person' is `export class Person ...`) and services will work just fine.
Marking as duplicate of #4813 (see "reexporting default").

@mhegazy: Goto def on Person2 currently takes you directly to its target. We could make a separate issue for that if you consider it a problem.

**Closed by andy-ms** 2016-08-24 19:47 UTC
Labels: Bug

**Comment by mhegazy** [comment] 2016-08-24 20:42
> @mhegazy: Goto def on Person2 currently takes you directly to its target. We could make a separate issue for that if you consider it a problem.

this is the desired behavior.
