### ISSUE TITLE
Emitter: Static class property "name" causes TypeError due to Function.name being readonly

### ISSUE THREAD

**Issue by about-code** [Microsoft/TypeScript#9778] opened 2016-07-17 17:39 UTC
**TypeScript Version:**  1.8.10

Consider the following class definition with a static property *name*:
```ts
class Foo {
     static name() {
         return "Hello World";
     }
     constructor() {}
}
```
The TS emitter output for this is:
```javascript
var Foo = (function () {
    function Foo() {
    }
    Foo.name = function () {
        return "Hello World";
    };
    return Foo;
}());
```
However, at least in Chrome and Firefox a function's name property is **readonly** for ordinary functions causing the assignment of the static function *name* to be ignored / causing a TypeError in strict mode.

The TS example above is also valid ES 2015 so I've tested it without transpilation in a current version of Chromium (v51.0.2704.79). Interestingly, while we can not change the *name* property of ordinary functions in Chromium we can still do the following for the constructor function once a static *name* property is present:
```javascript
class Foo {
   static name() {
        return "Hello World";
   }
   constructor {}
}
Foo.name = "Hello World"
console.log(Foo.name); // logs "Hello World"
```
So the name property of the constructor function is no longer read-only. Based on this I assume Chromium internally does something like

**Expected behavior:**
```javascript
var Foo = (function () {
    function Foo() {
    }
    Object.defineProperty(Foo, "name", { writable: true; });  // <= required for static class property *name*
    Foo.name = function () {
        return "Hello World";
    };
    return Foo;
}());
```
So a static class property *name* requires the *name* property to be made `writable: true` first. Unfortunately, `Object.defineProperty` is only available since ES 5 so static properties could become problematic for a compiler target of `es3`.

Therefore you might also want to note, that section 9.11.2 of ES2015 spec states that the ES interpreter must not set the *name* property, if a function does have an OwnProperty *name*. So the spec does seem to take custom values for *Function.name* into account which is why I consider a default configuration of `writable: false` for Function.name being problematic. It would certainly be better if browser vendors could agree here on making Function.name `writable: true` by default.

**Comment by about-code** [comment] 2016-07-17 19:10
Note: it seems there have been some issues with
```javascript
Object.defineProperty(Foo, "name", { writable: true; });
```
in the past with older versions of Chrome, due to older Chromes having set configurability of `Function.name` to *false*. See [comment](https://github.com/Microsoft/TypeScript/issues/2836#issuecomment-94558916) of @alexeagle regarding issue #2836.

**Comment by mhegazy** [comment] 2016-07-17 19:51
Duplicate of https://github.com/Microsoft/TypeScript/issues/442

**Closed** 2016-09-20 23:09 UTC
Labels: Duplicate
