### ISSUE TITLE
TS6133: 'svgs' is declared but never used

### ISSUE THREAD

**Issue by zhongsz** [Microsoft/TypeScript#15171] opened 2017-04-13 09:08 UTC
**TypeScript Version:**  2.3.0

**Code**

> import * as React from 'react'
> import SvgIcon from 'react-native-svg-icon'
> import svgs from './svgs**'
> export default (props: any) => <SvgIcon {...props} svgs={svgs} />

**Actual behavior:**
the error information occured : **TS6133: 'svgs' is declared but never used**

But when i change the code to

> `export default (props: any) => <SvgIcon svgs={svgs}  {...props} />` 

i found the issue is fixed.so i think it's a bug for TypeScript. i hope the team could fixed it .

**Comment by huhuanming** [comment] 2017-04-13 13:31
I found myself in the same situation yesterday

**Comment by deryost** [comment] 2017-05-01 15:16
Same situation for me, but I can't change the order everywhere, waiting for 2.4 to fix this.

**Comment by mhegazy** [comment] 2017-05-23 17:18
Duplicate of https://github.com/Microsoft/TypeScript/issues/15478. should be fixed in `typescript@2.3.3`

**Closed by mhegazy** 2017-05-23 17:18 UTC
Labels: Bug, Duplicate
