### ISSUE TITLE
Should getters still infer the same type from setters over their return expressions?

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#43414] opened 2021-03-29 10:39 UTC
```ts
class C {
    #x = Promise.resolve("")

    set myValue(x: Promise<string> | string) {
        this.#x = Promise.resolve(x);
    }
    get myValue() {
        return this.#x;
    }
}
```

Should the `get` type of `myValue` be `Promise<string>` or just `string | Promise<string>`? Right now it is the latter; but technically, the former provides a more specific type.

Changing this technically would be a breaking change.

**Comment by MartinJohns** [comment] 2021-03-29 10:53
Duplicate of #2521.

**Comment by ahejlsberg** [comment] 2021-03-29 13:25
I agree, I don't think there is a compelling case for us to *infer* divergent getter and setter types.

**Comment by RyanCavanaugh** [comment] 2021-03-29 16:52
I also would prefer to keep the current behavior

**Comment by DanielRosenwasser** [comment] 2021-03-30 01:39
Consensus'd

**Closed** 2021-03-30 02:35 UTC
Labels: Declined, Suggestion
