### ISSUE TITLE
HTMLTableElement Functions return wrong types (insertRow, insertCell)

### ISSUE THREAD

**Issue by EricLambrecht** [Microsoft/TypeScript#1274] opened 2014-11-26 01:17 UTC
~~insertRow(index?: number): HTMLElement;~~
insertRow(index?: number): **HTMLTableRowElement** ;
~~insertCell(index?: number): HTMLElement;~~
insertCell(index?: number): **HTMLTableCellElement**;

also HTMLTableElement.rows is not a collection of HTMLTableRowElements!?

Am I mistaken here?

**Comment by mhegazy** [comment] 2015-12-01 07:09
duplicate of #3583, and should be fixed in https://github.com/Microsoft/TypeScript/pull/5836

**Closed by mhegazy** 2015-12-01 07:09 UTC
Labels: Bug, lib.d.ts, Revisit
