### ISSUE TITLE
when decorators emit type information class ordering becomes important

### ISSUE THREAD

**Issue by marechal-p** [microsoft/TypeScript#43981] opened 2021-05-06 17:33 UTC
# Bug Report

When using decorators along with design type info, decorating a class that depends on another one implicitly adds a class definition ordering constraint. Not properly ordering those class definitions will result in a runtime crash, and the only way to know this is to know this issue before hand.

### 🔎 Search Terms

decorator initialization

### 🕗 Version & Regression Information

typescript 3.9.9 and 4.2.3

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Decorators

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAZzgWwKYBEMTgJwEMoCAeAFQD4AKKQ-AcwygC5FyBKN8xAbwChEQxPmYh8SOo2b8Avv34ABVJhx4iJfPwgAbQsmSIAgn0HC8YZFHwhoBavQYB+NgCEOp4V8QXUOjAB0OnAM1ADkvta2UBgAJsYAhGEANIiOHGZC8vLaegaIrnw5kWmIALyIYBgA7sbUGUA)

### 💻 Code

```ts
function someDecorator<T>(target: T): T {
    return target
}

@someDecorator
class A {
    constructor(arg?: B) {
        console.log('constructed A!', arg)
    }
}

class B {}

const a = new A()
```

Relevant generated JavaScript:

```js
// [...]
let A = class A {
    constructor(arg) {
        console.log('constructed A!', arg);
    }
};
A = __decorate([
    someDecorator,
    // EARLY REFERENCE ISSUE: B is defined below, so the JS runtime will complain about not-initialized refs!
    __metadata("design:paramtypes", [B])
], A);
// LATE DEFINITION OF B:
class B {
}
// [...]
```

### 🙁 Actual behavior

> [ERR]: can't access lexical declaration 'B' before initialization 

### 🙂 Expected behavior

TypeScript to either emit code in the right way, or complain at build time to prevent the runtime issue.

**Comment by MartinJohns** [comment] 2021-05-06 18:04
Duplicate of #27519.

**Closed** 2021-05-09 18:00 UTC
Labels: Duplicate
