### ISSUE TITLE
Allow type import from .d.ts using subpath import alias

### ISSUE THREAD

**Issue by nlwillia** [microsoft/TypeScript#57731] opened 2024-03-12 00:39 UTC
### 🔍 Search Terms

.d.ts subpath imports

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Assume an esm project using TypeScript 5.4.2.  (`"type": "modules"` in package.json and `"compilerOptions": {"module": "nodenext"}}` in tsconfig.json)

Given `export interface Foo {}` in `internal/api.d.ts`, I can `import type {Foo} from './internal/api.js'` in index.ts.

But if I use [subpath imports](https://www.typescriptlang.org/docs/handbook/modules/reference.html#packagejson-imports-and-self-name-imports) to map the internal directory in package.json (`"imports": {"#internal/*.js": "./internal/*.js"}`), then I cannot write the same import using the aliased module specifier: `import type {Foo} from '#internal/api.js'`

> TS2307: Cannot find module '#internal/api.js' or its corresponding type declarations.

A workaround is to rename the `.d.ts` to `.ts`.  Then, it can be used with the `#internal` import alias.

### 📃 Motivating Example

While there is a difference in output behavior for a `.d.ts` vs. a `.ts` containing the same type declarations, it's currently fairly opaque why one wouldn't work here and the other would.  This is especially true for type imports which while using a `.js` extension only exist at compile time.  If a type-only import works for a `.d.ts` which will never produce compiled output, then it's unintuitive why a subpath alias would not also (abstractly) work for it.

### 💻 Use Cases

The current workaround is to rename the `.d.ts` to `.ts` or to use a relative import style.

This is confusing at the source level because it's not clear just reading the import why one works with the subpath alias and the other requires a relative path.

```
import type {Foo} from '#internal/a.js' // in ./internal/a.ts
import type {Bar} from './internal/b.js' // in ./internal/b.d.ts
```

The error messaging also doesn't help.  Even if there's no desire to change the subpath resolution behavior, it would be helpful if the error informed why trying to map to a `.d.ts` type did not work.

**Comment by ljharb** [comment] 2024-03-22 16:46
Is this perhaps the cause of https://github.com/webpro/knip/issues/567, or should i file a separate issue?

**Comment by nlwillia** [comment] 2024-03-22 17:47
@ljharb This is just about resolving types through import aliased `.d.ts` module specifiers.

**Comment by ljharb** [comment] 2024-03-22 17:48
right - https://unpkg.com/browse/knip@5.2.2/dist/plugins/vite/index.d.ts is the file that's giving me trouble (and that TS seems unable to exclude/ignore)

**Comment by nlwillia** [comment] 2024-03-22 18:25
Ignores or `skipLibCheck` are not honored if the file is referenced.  It sounds from the other issue like you're trying to use something as a library that isn't packaged for that which isn't likely a TypeScript issue.

**Comment by ljharb** [comment] 2024-03-22 19:22
the file isn't referenced by me, though - altho i'm sure it's referenced by one of the package's files I'm importing.

indeed it's not packaged for use as a library, but i'm not sure why that'd mean TS should be permanently broken just because i'm using it thus?

**Comment by nlwillia** [comment] 2024-03-22 19:33
What you're asking about is not related to this issue.

**Comment by andrewbranch** [comment] 2024-03-28 17:23
@nlwillia can you provide a reproduction or at least a tsconfig? I think `rootDir` and `outDir` may be a factor here.

**Comment by nlwillia** [comment] 2024-03-28 18:33
@andrewbranch you're correct.  The `outDir` seems to be the factor.  Here's [a repro](https://stackblitz.com/edit/stackblitz-starters-baigj5?file=index.ts).  The index imports an interface from two files, but only the .ts import compiles, not the .d.ts.  The import mapping references the outDir (which is necessary for the mapped import to work at all).

**Comment by RyanCavanaugh** [comment] 2024-03-28 18:59
This setup is pretty hard to reason about. There's not going to be an `api.js` file at runtime, so module resolution correctly doesn't consider it a lookup target. Right now there isn't a distinction during module resolution as to whether you're resolving for the purposes of `import type` or regular `import` and it's not really apparent how one could be made either.

In fact, it's totally legal for module resolution to find a *different* module under this name if that file exists, e.g. `internal/api.tsx`
![image](https://github.com/microsoft/TypeScript/assets/6685088/f1de1fd7-28e5-4b53-8b9a-0cfd58257f24)

If you're naming `api.d.ts` because "This file just contains types so I'll name it .d.ts", this is an anti-pattern and should be avoided - `.ts` is the correct file extension even if you don't intend to have values in it. If it's trying to declare an external module that actually exists, it should probably use a form like
```ts
declare module "#internal/api.js" {
    export interface Foo { a: string }
}
```

**Comment by andrewbranch** [comment] 2024-03-28 19:16
Yeah, I can’t decide whether this should work or not. I agree with Ryan that the correct move here is to name the file `.ts`. An alternative that does work, as long as you’re only importing types, is to add an entry to `imports` like

```json
"imports": {
  "#internal/*.d.ts": "./internal/*.d.ts",
  "#internal/*.js": "./dist/internal/*.js"
},
```

and reference the module as a type-only import with the `.d.ts` extension. That’s dangerous if you’re going to publish this package to npm, as you’d need to preserve the `internal/api.d.ts` file in the published package, when your first instinct might be to publish only the `dist` folder. It could be alright if this is in a private app, though.

**Comment by nlwillia** [comment] 2024-03-28 19:21
I don't disagree that it's unintuitive.  Things have gotten kind of weird in general (though I understand [why](https://www.typescriptlang.org/docs/handbook/modules/theory.html)) with all the references to `.js` paths that might not exist due to noEmit or just not having built yet.  But from a type perspective, this is a difference in behavior that's hard to understand under the new model, and it's very strange to have your editor rejecting an import construction that works just fine elsewhere.

I ran across this in the context of porting a legacy project to ESM, and renaming the files is fine as a workaround.  I just thought it was important to at least document the discrepancy.  I was on the verge of ripping out subpath imports project-wide because I couldn't immediately discern why this one part of the code base was being flaky.

**Comment by andrewbranch** [comment] 2024-03-28 20:53
> it's very strange to have your editor rejecting an import construction that works just fine elsewhere

It doesn’t though, in your example—there is no `dist/internal/api.js`. If you add one by hand, you’ll see the error change from

> Cannot find module '#internal/api.js' or its corresponding type declarations.

to

> Could not find a declaration file for module '#internal/api.js'. '/home/projects/stackblitz-starters-lfm265/dist/internal/api.js' implicitly has an 'any' type.

This seems correct to me. When we see that you’re resolving to something in the build output directory, we look for the corresponding build input for the `.js` file, which had to be a `.ts` file. A `.d.ts` file in the input directory could not have produced the target `.js` file, or even have been produced by the same compilation. So once we fail to find an input file, we try resolving in the output directory. There, we find nothing, so resolution fails. Or, in my edit, we find a `.js` file without type information.

**Comment by nlwillia** [comment] 2024-03-29 13:14
It looks like another workaround would be to add [paths](https://www.typescriptlang.org/tsconfig#paths), which is telling the compiler that this root is externally aliased, though it's unfortunate that information can't be wholly inferred from the package config.
```
    "paths": {
      "#internal/*": ["./internal/*"]
    }
```

**Closed** 2024-04-01 01:29 UTC
Labels: Working as Intended, Needs Investigation
