### ISSUE TITLE
export default class compile error

### ISSUE THREAD

**Issue by welefen** [Microsoft/TypeScript#6450] opened 2016-01-12 08:32 UTC
```ts
export default class {
  
}
```

compiled code is:

```js
class {
}
exports. = default_1;

```

compile command is `tsc --module commonjs --target ES6 default.ts`, TypeScript version is 1.7.5

**Comment by welefen** [comment] 2016-01-12 08:45
when set --target ES5, it's correct

**Comment by vladima** [comment] 2016-01-12 17:12
duplicate of #5844, should be fixed in master. Can you give a try to `typescript@next` on npm to see if it resolves the problem?

**Comment by mhegazy** [comment] 2016-01-12 17:12
should be fixed in latest.

**Closed** 2016-01-12 17:12 UTC
Labels: Duplicate
