### ISSUE TITLE
Unexpect Object is possibly 'undefined' Error when checked before.

### ISSUE THREAD

**Issue by SyMind** [microsoft/TypeScript#40341] opened 2020-09-01 07:05 UTC
**Steps**

use TS 3.3 (latest)
enable all strict checks
have code such as this:

```ts
interface Props {
    foo?: {
        bar: string;
        baz: string;
    }
}

function hello({foo}: Props) {
    const isFooPresent = foo !== undefined;
    let bar = isFooPresent ? foo.bar : ''; // Object is possibly 'undefined'.
    let baz = isFooPresent ? foo.baz : ''; // Object is possibly 'undefined'.

    // but follow code is safe.
    //  let bar = foo !== undefined ? foo.bar : '';
    //  let baz = foo !== undefined ? foo.baz : '';
}
```

Using a const variable to store check result, an error when occur.

**Comment by MartinJohns** [comment] 2020-09-01 07:26
And another duplicate of #12184.

> use TS 3.3 (latest)

Uhh... The latest version is 4.0.2, not 3.3.

**Closed** 2020-09-01 22:56 UTC
Labels: Duplicate
