### ISSUE TITLE
let tsserver watch paths for changes

### ISSUE THREAD

**Issue by leemhenson** [microsoft/TypeScript#32896] opened 2019-08-14 19:39 UTC
## Search Terms

tsserver watch node_modules project references

## Suggestion

Would it be possible to teach tsserver to watch a set of paths for changes, and feed back data to clients on the basis of any changes it detected? 

## Use Cases

My particular use case is that we have a monorepo with multiple packages that depend on a shared package. We use pnpm, which basically symlinks the packages together:

```
/sharedPackage
  /package.json 
  /src
    /someFile.ts
  /.emitted
    /someFile.js

/consumerPackage
  /package.json  <-- has dependency on "sharedPackage": "*"
  /node_modules
    /sharedPackage    <!-- symlink to ../../../sharedPackage
  /src
    /consumerFile.ts
```

Then, in the `consumerFile.ts` we do:

```typescript
import { thing } from "sharedPackage/.emitted/someFile";
```

This all works great, and we use project references to watch and compile both projects at the same time. The problem comes when you have the monorepo open in your editor, and you make changes in the shared package while also editing files in the consumer package. The `tsc --build --watch` we are running doesn't have any way to signal to the `tsserver.js` process that it has changed the files that it has parsed, and that it should maybe now display or remove some squiggles for errors, warnings etc. The only solution is to trigger the `Restart Typescript` mechanism, or kill and restart `tsserver.js`. I can write a script to watch files and to kill `tsserver.js` when they change, but that doesn't play nice with things like `tide` in Emacs. 

A solution I can conceive of is having a file watcher as part of `tsserver.js` that watches `node_modules` for changes, and rereads those files when they change. Ideally, having some way to limit the set of watched files would be good for perf reasons.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by sheetalkamat** [comment] 2019-08-14 19:50
This should be working correctly today. Since the generated .d.ts files are what tsserver watches. You can look at the tsserver and notice the file being watched. If you are not using `preserveSymLinks` option, the symlink should follow to your sharedPackage/.emitted/somFile.js

**Comment by leemhenson** [comment] 2019-08-15 09:47
Hi Sheetal, here's a repro of our current setup: https://github.com/leemhenson/tsserver-refresh-issue

We shall do some more experimentation on other approaches but I'd be interested to know why this repro doesn't work, if you think it should.

**Comment by leemhenson** [comment] 2019-08-15 11:10
🤔  so `preserveSymlinks` is the secret sauce here....

**Comment by sheetalkamat** [comment] 2019-08-15 15:07
Yes preserveSymLinks is meant to tell compiler that use link instead of resolving it.. so this is working as intended

**Closed by sheetalkamat** 2019-08-15 15:07 UTC
Labels: Needs More Info
