### ISSUE TITLE
Stronger `this` typing?

### ISSUE THREAD

**Issue by m93a** [microsoft/TypeScript#49025] opened 2022-05-09 11:35 UTC
# Suggestion
The behavior of `this` in methods is one of the last features of JavaScript that is both unintuitive and **not** checked for by TypeScript. It is commonplace for both novice and experienced TypeScript programmers to accidentaly create a method (instead of an [instance function](https://github.com/Microsoft/TypeScript/wiki/'this'-in-TypeScript#use-instance-functions)) and then pass it as a callback. Currently, the only way to find out that one has made such a mistake is at runtime (yikes!).

I propose two small changes in the typechecking system which could be introduced as a strict rule (eg. `strictThisArgument`). Those changes would eliminate most of the mistakes that lead to unexpected values of `this` at runtime.

## 🔍 Search Terms
better `this` and `bind`, `this.method` is not a function, strict `this`, unbound method passed to `map`, `filter`, `addEventListener` compiles but fails at runtime, method as callback checking

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code — **not if it's introduced as a strictness rule**
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
Introduce a strict rule that will:
 1. Automatically add the correct `this` signature to methods in a class
 2. Make `this` in function signatures `unknown` by default – ie. `() => void` would be equivalent to `(this: unknown) => void`

## 📃 Motivating Example

Consider the following example:
```typescript
class ConstantShift {
    additiveConstant = 42;

    addToNum(n: number) {
        return n + this.additiveConstant;
    }
}

function addToNumStrong(this: ConstantShift, n: number) {
    return n + this.additiveConstant;
}

const nums = [0, 1, 5, 27];
const shift = new ConstantShift();

nums.map(shift.addToNum); // compiles, doesn't work
nums.map(addToNumStrong); // compiles, doesn't work

nums.map(shift.addToNum.bind(shift)); // compiles and works
nums.map(addToNumStrong.bind(shift)); // compiles and works
```
[Link to playground.](https://www.typescriptlang.org/play?#code/MYGwhgzhAEDCD2A7CAXMiUGUAWBLAZitAN4BQ0F0YAJtbirgG4CmCyaG0AvNACwBMAblLlKNagBV4AOQCuAWwAUiAFzRECgEbMATgEoSoypR3MUsnYnXQA1NBR4IAOnH0mrJKnQphxgL6kAaT4sojADEhUtFJy8pgoOkgA5ooOuBBqbF4YOAQoADTqahry2vqGxqbmltZ2ac6uDCxZHD6BIsCeRCUwPADaAAyFAIyFAKyF-ADsALrCnezQEHiE3OrMAO5wXd65hIp6wqQ9TvJgAA6Ky3ku0TIKh9AA9E-QnfLnuCDMEIXU8D9EAByIgbeA6ADWxwUzjOl3EMQU8USiCSjxeb3gHy+Pz+AIgwNB4Kh0PksIuVxWKFuknu8icmlwiGolLyenRr3en2+MHQ1GgYMhEFJ5Phd1iyOSDKZLOuhHZgmenKx3J+VGZAuJwqAA)

This example might look artificial, but in essence it's what every React developer does when they want their component to listen to some event. Passing methods as callbacks is a thing that happens quite often in the JS world.

How would this suggestion change this behavior? The first step would change the signature of the `addToNum` method to:
```typescript
addToNum(this: ConstantShift, n: number): number
```
and the second step would make `map` accept `(this: unknown, x: number) => number` as the callback.

This would be enough to make TypeScript correctly recognize whether the code will work correctly at runtime, as can be seen in [this playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAWwIYAcA8AVANIgJQD4AKVAJ3IC5FsBtAXX2DBpKgAsYBnG8AazBwA7mHwAPGtgCUiALxFC0mgUaIA3gChEOxOQCmUEOSQVyAOjToSLaQG5NAX02aIAG1TduiAMIJuUKhgUADKXMBQGtq6qAAmsTCwAG76fmABQZFyiAAsAEwO0TpxsdhwAHIgyOxcvL7+gcFhMBH4rIhgVQBG+uSyWrqDeobGSEgA1IicPOYliTApaRnBDoPOzpqgkLAIiCVllcghUOQIAOY1PDRLjaHhUG00ncg9fVGDBkYmHYiT09yzeLzRYNTIODYQBodKrebJ0AAM+AAjPgAKz4PIAdgYDkh6Ui3Hu8g6+mE9XxmWaERI9hcVhIz24+EJLSggNKFSq9kQAHoeYhYnB9NwwABySKQ5DoGBufSaemM-D7TlHE7nbl8gVCkXixCS6WyukYBkw5n3dkHKrmLowMCxEgsiLSDX8-Uy4V7O2IYRwcj8bjy42KvbxS2q05gM7W232x1QZ12XmuuBS93eIKxb2+-2aIA).

## 💻 Use Cases

Eliminates mistakes when working with methods and callbacks, and ultimately increases productivity.

**Comment by whzx5byb** [comment] 2022-05-09 13:16
Duplicate of https://github.com/microsoft/TypeScript/issues/7968.
See https://github.com/microsoft/TypeScript/pull/6739 also for the explanation for removing `--strictThisChecks` flags.

**Closed** 2022-05-10 09:01 UTC
Labels: Duplicate
