### ISSUE TITLE
Add visibility modifier to allow access only within a module

### ISSUE THREAD

**Issue by asfernandes** [Microsoft/TypeScript#19907] opened 2017-11-10 10:39 UTC
Sometimes you want a property/method to be visible outside of a class in the same module but do not want it to be on the public interface outside their module.

For example:

```ts
export class PublicClass {
    public myPublicProperty = 1;
    internal myInternalProperty: number;  // do not expose outside this module

    constructor() {
        setValue(this);
    }
}

function setValue(o: PublicClass) {
    o.myInternalProperty = o.myPublicProperty;  // allow access to myInternalProperty outside PublicClass
}
```

**Comment by andy-ms** [comment] 2017-11-10 14:20
Duplicate of #5228 and #7692.

**Closed** 2017-11-27 18:38 UTC
Labels: Duplicate
