### ISSUE TITLE
Object unexpectedly undefined

### ISSUE THREAD

**Issue by mqualizz** [microsoft/TypeScript#52104] opened 2023-01-04 19:53 UTC
# Bug Report

### 🔎 Search Terms

undefined object, callback, closure, hoisting, arrow function

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (every version available in the playground, from 3.3.3 to Nightly 5.0.0), and I reviewed the FAQ for entries about `undefined`, `closure`, `hoisting`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230104&ssl=18&ssc=59&pln=18&pc=1#code/MYewdgzgLgBAZiEBZAhgBwFyrQHmgJwEswBzAGgEF98UBPHMAVwFsAjAU3wD4uYBeGGHYB3GNgAUASgBQ0uIzDAohcDAghm7AGIKlKsOJT4SGKjXpM2nLpJgBvaTCcwA9C4B0n6QF9ZoSLAAbigANozsEPwwANoAjGQwAEwJAMwJACwJAKwAugDcsiHssAggUaXY7iTF4gBEKLWSBdKEcDDipfwCTCEhtg7O8IhR0fk+sm4wACoAFuwwhBAQ4QuRUDOLMCHE7AnCc-jzUwDKanRrMyiwAAal1zDMdDAcMAoAJuxwO2-SwWER7gQ+AAoihgDNxOJArY+LxSu40IwIBDoU0Ji4YABJMAwdabbZCBInGCHUAkMCEABeEVxlxud1WghAsHen2+0nUmh0imU4A6iDRQA)

### 💻 Code

```ts
const fooMap:Map<string,Array<number>> = new Map()

function someFunction(arg:Array<number>) {
    //...
}

const values = [1, 2, 3, 4, 5];

let foo = fooMap.get("a");

if (foo == null) {
    foo = [];
}

// The issue is this line, where TS says that `foo` may be undefined
values.forEach((v) => foo.push(v));

// In this line, TS recognizes that `foo` is not undefined
someFunction(foo);
```

### 🙁 Actual behavior

A variable (in this case, `foo`) is being marked as possibly undefined when used inside of a closure, although it will never be null at that point.

### 🙂 Expected behavior

I expect `foo` to be not-null.

I apologize if the observed behaviour is expected -- but, if it is, can someone explain why?

**Comment by MartinJohns** [comment] 2023-01-04 19:56
Duplicate of #9998.

**Comment by mqualizz** [comment] 2023-01-04 20:33
Is this a duplicate?  I've read the bug, and am still reading through all of the comments, but I don't believe this is a situation where control flow analysis is having to contend with a function call.

The problem isn't `someFunction(foo)` (which happens after the `values.forEach()` function call).  Even if it were to be argued that we can't determine whether `values.forEach()` modifies `foo`, and thus `foo` could be `undefined` at the `someFunction()` line, that's not what's happening -- `foo` is being marked as possibly `undefined` in the callback.

What am I missing?

**Comment by MartinJohns** [comment] 2023-01-04 20:44
Narrowing is reset in closures. It is a duplicate.

**Comment by mqualizz** [comment] 2023-01-04 20:45
> Narrowing is reset in closures. It is a duplicate.

Ok, thank you.

**Closed** 2023-01-04 20:45 UTC
Labels: Duplicate
