### ISSUE TITLE
IntelliSense for type's nested keys

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#20944] opened 2017-12-30 13:07 UTC
This doesn't work in latest insiders VSCode:

![image](https://user-images.githubusercontent.com/736697/34454376-fd845836-ed8b-11e7-939c-81bd42236529.png)

Should propose `prop`.

Usually, this refers to TS, not VSCode.

**Comment by mhegazy** [comment] 2018-01-04 20:09
Actually duplicate of https://github.com/Microsoft/TypeScript/issues/20938

**Comment by whitecolor** [comment] 2018-01-05 13:35
Sometimes it is not easy to find out if the issue already exists =)

**Closed** 2018-01-20 20:10 UTC
Labels: Duplicate
