### ISSUE TITLE
Emit does not preserve empty lines

### ISSUE THREAD

**Issue by NoelAbrahams** [microsoft/TypeScript#843] opened 2014-10-07 10:51 UTC
Hi,

**TS Version**: 1.1

Given

``` TypeScript
function foo() {

    var x = 10;

    var y = 11;
}
```

 We used to get

``` JavaScript
function foo() {
    var x = 10;

    var y = 11;
}
```

In the new compiler the line break is missing

``` JavaScript
function foo() {
    var x = 10;
    var y = 11;
}
```

(Both compilers removed the first empty line, but the new compiler has gone a step further.)

This can affect the experience when debugging JavaScript in the browser.

**Comment by mtraynham** [comment] 2015-03-03 22:01
@NoelAbrahams There is one issue that exists with debugging in the browser that is slightly related to this conversation.  When using setter/getter chains (like with jquery), the new line feeds are lost during translation.  That being said, it is a huge pain point when doing this with Arrow functions.

As an example:
```
(<any> x).a('#test')
    .b('test')
	.c(() => 'foo')
	.d(() => 'bar')
	.e(() => 5)
	.f(() => 6);
```
Becomes:
```
x.a('#test').b('test').c(function () { return 'foo'; }).d(function () { return 'bar'; }).e(function () { return 5; }).f(function () { return 6; });
```

http://www.typescriptlang.org/Playground#src=(%3Cany%3E%20x).a('%23test')%0A%20%20%20%20.b('test')%0A%09.c(()%20%3D%3E%20'foo')%0A%09.d(()%20%3D%3E%20'bar')%0A%09.e(()%20%3D%3E%205)%0A%09.f(()%20%3D%3E%206)%3B

**Comment by NoelAbrahams** [comment] 2015-03-04 15:00
@mtraynham, actually I think the problem you highlight is a slightly different one.

In previous versions the body of an inline function was always emitted on new lines:

```typescript
// TS
var x = () => 'foo';

// JS - old
var x = function () { 
             return 'foo'; 
       };

// JS - new
var x = function () { return 'foo'; };
```

I too have found this to be a problem - having to occasionally go back and create a `function` so that I can set a breakpoint when debugging in the browser.

**Comment by mtraynham** [comment] 2015-03-05 02:55
@NoelAbrahams Ahh yes, I have been using this exact same temp solution...  I wasn't sure if this was an appropriate bug to contribute this problem to (erasure of line feeds), or should I open another?

**Comment by timjmartel** [comment] 2016-02-24 16:56
As an engineering director exploring moving our javascript  development community to typescript the new line capability would really help.  One of the primary appeal of typescript was  maintaining the readability and structure of the code created in typescript generatedJavascript.  

Great to see comments are kept in the recent update and addition of the “--removeComments" command line directive.

**Comment by shawnExplore** [comment] 2016-04-15 02:15
I would also like this for a similar reason as @timjmartel  - when developers see the emitted JS looks *nice* they are less resistant to adopt.  Preserving (at least vertical) whitespace makes the code look less like it was generated by a machine and more like idomatic JS code written by a human.

If our team ever decided to abandon TS and instead continue with the transpiled JS it would be much easier to adopt the emitted JS sources if they had human-friendly whitespace.

**Comment by egarrulo** [comment] 2016-07-20 18:09
In regard to empty lines, would it be possible - for now - to have them emitted, even if they are hit or miss?  Such experimental feature could be asked with a “--keepEmptyLines" option.  It would be not so much for having nice JS, but for having more readable JS.

In regard to chained function calls, would it be possible to have one call for line, to let users set breakpoints?  Again, this feature could be asked with a "--oneCallForLine" option, if it is another "hit or miss" thing.

Thanks for your attention.

**Comment by egarrulo** [comment] 2016-07-21 12:38
Actually, chained function calls could be split by a source code beautifier, therefore it doesn't make sense to embed such feature in TypeScript.

**Comment by ORESoftware** [comment] 2017-02-19 00:39
This shouldn't be that hard, shouldn't there just be an option in tsconfig.json

`preserveWhitespace: true/false`

?

**Comment by ORESoftware** [comment] 2017-02-19 00:41
But I am not seeing this as a compiler option: https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by ORESoftware** [comment] 2017-02-20 01:18
I just realized. One good reason to not keep whitespace is that it will really help prevent you from accidentally editing the .js instead of the .ts. I guess one thing to do would be to write out the .js files as readonly. So maybe this is a non-issue.

**Comment by DanielRosenwasser** [comment] 2017-02-21 05:47
No, not at the moment. Feel free to open up a separate issue for that though.

**Comment by ORESoftware** [comment] 2017-02-21 06:48
@DanielRosenwasser you're saying if we want to preserve whitespace that we should open a separate issue? Is this issue not enough?

**Comment by byelims** [comment] 2017-04-03 11:36
It would be nice to have this.

**Comment by cwallsfdc** [comment] 2017-04-20 16:14
+1

**Comment by angeloocana** [comment] 2017-04-26 23:59
+1

**Comment by jaguar7021** [comment] 2017-07-25 15:12
+1

**Comment by ppsimatikas** [comment] 2017-09-14 19:50
The crowd wants `preserveWhitespace: true/false`
@ORESoftware ++

**Comment by Ciantic** [comment] 2017-09-27 21:30
Reason this is important is that TypeScript is supposed to "degrade gracefully" to JS. Right now it can't preserve new lines making the JS a bit dense to read, especially if you write TypeScript, but you are supposed to deliver JS to some place else.

**Comment by bril-andrew** [comment] 2017-12-04 14:40
+1 `preserveWhitespace: true/false`

### Temporary hack
Use [esformatter](https://github.com/millermedeiros/esformatter) to add linebreaks.

With the following configuration file:

```JSON
{
  "lineBreak": {
    "before": {
      "FunctionDeclaration": ">=2",
      "FunctionDeclarationOpeningBrace": 0,
      "FunctionDeclarationClosingBrace": 1,
      "MethodDefinition": ">=2",
      "ClassDeclaration": ">=2"
    },
    "after": {
      "FunctionDeclaration": ">=2",
      "FunctionDeclarationOpeningBrace": 1,
      "MethodDefinitionClosingBrace": ">=2",
      "ClassClosingBrace": ">=2"
    }
  }
}
```

**Comment by valera-rozuvan** [comment] 2018-01-02 15:24
@mtraynham Your example:

```
(<any> x).a('#test')
    .b('test')
    .c(() => 'foo')
    .d(() => 'bar')
    .e(() => 5)
    .f(() => 6);
```

with the latest compiler produces this JS:

```
x.a('#test')
    .b('test')
    .c(function () { return 'foo'; })
    .d(function () { return 'bar'; })
    .e(function () { return 5; })
    .f(function () { return 6; });
```

(see TS PlayGround https://goo.gl/JViurr )

A lot has changed since TS Version 1.1 (the version of TypeScript for which this issue was created). Maybe this issue can be closed? @ahejlsberg ?

**Comment by mtraynham** [comment] 2018-01-02 18:50
@valera-rozuvan I had opened #2259 instead.  My issue was related to line feeds, but not the exact same issue described by this bug.  #2259 was closed a while back (May 2015).

**Comment by fermmm** [comment] 2018-02-06 09:30
This is the **bril-andrew** esformatter configuration but with a bug fixed, (when the class declaration has an import there was no line break):
`{
    "lineBreak": {
        "before": {
            "FunctionDeclaration": ">=2",
            "FunctionDeclarationOpeningBrace": 0,
            "FunctionDeclarationClosingBrace": 1,
            "MethodDefinition": ">=2",
            "ClassDeclaration": ">=2",
            "ExportNamedDeclaration": 2
        },
        "after": {
            "FunctionDeclaration": ">=2",
            "FunctionDeclarationOpeningBrace": 1,
            "MethodDefinitionClosingBrace": ">=2",
            "ClassClosingBrace": ">=2"
        }
    }
}`

**Comment by DanielSWolf** [comment] 2018-03-07 12:49
I don't think using esformatter solves the whole problem. Sure, it can automatically insert blank lines around functions etc. But for me, blank lines *within functions* are even more crucial. We use blank lines like paragraphs in prose: to group individual thoughts.

Those blank lines within functions help to communicate the structure of the function. Without them, I find that readability suffers.

**Comment by JimTheMan** [comment] 2019-09-10 17:43
@ahejlsberg I seeing incorrect line numbers in my unit testing output when using ts-jest, and this issue seems to be caused by the empty lines being removed in the js output. I am curious why it is so difficult to leaves these lines in the final js. Is there any more information out there on this? Can we help somehow to make this happen? :)

**Comment by dragomirtitian** [comment] 2019-09-19 12:10
@JimTheMan  If you use source maps then maybe the `source-map-support` [package](https://www.npmjs.com/package/source-map-support) can help you get the correct stack traces in the output.

**Comment by zeroliu** [comment] 2019-11-20 10:05
I also run into this issue. I came up with a workaround by creating a diff patch and revert whitespace changes in the patch. [jsdiff](https://github.com/kpdecker/jsdiff) allows you to create a structured patch object and manipulate it as you wish. 

```
import * as diff from 'diff';

const patch = diff.parsePatch(diff.createPatch('file', oldText, newText));
const hunks = patch[0].hunks;
let lineOffset = 0;
for (const hunk of hunks) {
  hunk.lines = hunk.lines.map(line => {
    // Revert whitespace changes
    if (line === '-') {
      lineOffset++;
      return ' ';
    }
    return line;
  });
  hunk.newLines = hunk.newLines + lineOffset;
}
return diff.applyPatch(oldText, patch);
```

With this workaround, you can preserve all the line breaks from the original file.

**Comment by valera-rozuvan** [comment] 2019-11-20 10:16
@zeroliu Does it introduce a noticeable delay in compile step?

**Comment by valera-rozuvan** [comment] 2019-11-20 10:17
@ahejlsberg Do you think it's worth fixing this issue?

**Comment by zeroliu** [comment] 2019-11-20 12:56
@valera-rozuvan depending on the size of your project. For my use cases where I transpile 10-ish files of 100-1000 LOC, it doesn't introduce any noticeable delay.

**Comment by BiosBoy** [comment] 2020-04-06 06:17
Any solutions here yet? I run in this trouble too...

**Comment by mbroadst** [comment] 2020-05-07 22:32
I was part way into trying to fix this in the compiler itself when my teammate @emadum reminded me that tsc can preserve comments. Here's a little gulp pipeline that seems to do a fairly decent job of preserving newlines:

```
const gulp = require('gulp');
const ts = require('gulp-typescript');
const through = require('through2');

function preserveNewlines() {
  return through.obj(function(file, encoding, callback) {
    const data = file.contents.toString('utf8');
    const fixedUp = data.replace(/\n\n/g, '\n/** THIS_IS_A_NEWLINE **/');
    file.contents = Buffer.from(fixedUp, 'utf8');
    callback(null, file);
  });
}

function restoreNewlines() {
  return through.obj(function(file, encoding, callback) {
    const data = file.contents.toString('utf8');
    const fixedUp = data.replace(/\/\*\* THIS_IS_A_NEWLINE \*\*\//g, '\n');
    file.contents = Buffer.from(fixedUp, 'utf8');
    callback(null, file);
  });
}

gulp.task('default', function () {
  return gulp.src('src/**/*.ts')
    .pipe(preserveNewlines())
    .pipe(ts({}))
    .pipe(restoreNewlines())
    .pipe(gulp.dest('lib'));
});
```
I think a more clever comment would prevent some false positives, but it seems to work well for us today. I've only tested this on a relatively small file, but the performance overhead there was minimal. 

hth

**Comment by m9xiuz** [comment] 2020-05-26 09:00
I don't get it why it's so hard. You can, for example, before compilation, replace every empty line with some placeholder, e.g.:
`1234567887654321;`
and then after complication replace them back to empty lines.
Example: [https://www.typescriptlang.org/play](https://www.typescriptlang.org/play#code/MYewdgzgLgBAhmAogDzgWwA4BsCmA1OAJwEs4AjXGAXhgCIAJHLLEGAdREKwBNaAoAIwAmAMwAWAKwA2AOwAOOTKkSxIoQIDcfUJBC4AdCwDmACgQp02fEVIUcASkGjJshUpVrN2rHAgQYAIIQ3ABmMADefDDRMMLi0vKKyqrqWjEwyABcMADKUCRgRmkxcS6J7ile6TrQhACuwFCcJlm5+cSF9hFR6SXOCW7JnsW9MFAAFsQQ+sjUGSO9pQNJHqk90QC+67H9riuVWltLexXDfCF1YI3E4DAhICAmXZHpx+VDa9Xg0BlzcQtvQarLxHXbvYFae6PexaQH7YZAA)

**Comment by eneko89** [comment] 2021-03-11 21:21
Is this still being considered? I see this experiment: https://github.com/microsoft/TypeScript/pull/37814 and https://github.com/microsoft/TypeScript/pull/42303, but don't know if there is any plan to deliver it some day.

**Comment by edsrzf** [comment] 2021-04-29 19:45
Is there a way I could contribute to fixing this? If I could get some guidance around what an acceptable fix might look like, I'd be willing to take a stab at it.

**Comment by sdwvit** [comment] 2021-06-25 03:54
@CarabusX I took slightly minimalistic approach, but very similar to yours:
```
        function preserveWhitespace(content) {
          return content.replace(/(\s)/g, (m) => {
            return `/**_P${m.charCodeAt(0)}**/`;
          });
        }
        function restoreWhitespace(content) {
          return content.replace(/\/\*\*_P(\d+)\*\*\//g, (_, m) => {
            return String.fromCharCode(m);
          });
        }
        content = preserveWhitespace(content);
        const output = ts.transpileModule(content, {
          reportDiagnostics: false,
          compilerOptions: {
            target: ts.ScriptTarget.ESNext,
            importsNotUsedAsValues: ts.ImportsNotUsedAsValues.Preserve,
            sourceMap: true,
            removeComments: false,
          },
        });
        output.outputText = restoreWhitespace(output.outputText.replace(/\s+/g, ''));
```

**Comment by favna** [comment] 2021-11-26 00:36
I tried many suggestions from this thread but none worked for me. After a while, however, I managed to come up with my own solution.

Before I share the code, I should note that this code relies on Prettier for formatting to get the JS code consistent with the TS code. I already use Prettier in all my projects, so I just copied the config I am using anyway.

One final note, as my use case for this, was the Docusaurus website for https://github.com/sapphiredev, I have also decided to publish this conversion and formatting as an NPM package: https://www.npmjs.com/package/@sapphire/docusaurus-plugin-ts2esm2cjs

Now on to the code. This transpiles TS into ESM and then further converts that ESM into CJS.
```js
const { runTransform } = require('esm-to-cjs');
const ts = require('typescript');
const prettier = require('prettier');
const sapphirePrettierConfig = require('@sapphire/prettier-config');

const documentationPrettierConfig = {
	...sapphirePrettierConfig,
	tabWidth: 2,
	useTabs: false,
	printWidth: 120,
	parser: 'babel'
};

/** @type {import('ts').CompilerOptions} */
const tsCompilerOptions = {
	module: ts.ModuleKind.ESNext,
	newLine: ts.NewLineKind.LineFeed,
	moduleResolution: ts.ModuleResolutionKind.NodeJs,
	target: ts.ScriptTarget.ESNext,
	removeComments: false,
	esModuleInterop: true,
	pretty: true
};

/**
 * Transpiles input TypeScript code to ESM code.
 * @param {string} code The code to transpile
 * @returns {{ outputText: string; diagnostics: unknown[]; sourceMapText?: string }} Input code transpiled to ESM
 */
const tsToEsm = (code) => ts.transpileModule(code, { reportDiagnostics: false, compilerOptions: tsCompilerOptions });

/**
 * Transforms input ESM code to CJS code.
 * @param {string} code The code to transform
 * @returns Input code transformed to CommonJS
 */
const esmToCjs = (code) => runTransform(code, { quote: 'single' });

/**
 * Escaped new lines in code with block comments so they can be restored by {@link restoreNewLines}
 * @param {string} code The code to escape new lines in
 * @returns The same code but with new lines escaped using block comments
 */
const escapeNewLines = (code) => code.replace(/\n\n/g, '\n/* :newline: */');

/**
 * Reverses {@link escapeNewLines} and restores new lines
 * @param {string} code The code with escaped new lines
 * @returns The same code with new lines restored
 */
const restoreNewLines = (code) => code.replace(/\/\* :newline: \*\//g, '\n');

/**
 * Formats the code using Prettier
 * @param {string} code The code to prettier format
 * @returns Prettier formatted code
 */
const prettierFormatCode = (code) => prettier.format(code, documentationPrettierConfig).slice(0, -1);

/**
 * The example code that we'll be transpiling and formatting.
 * Of note here is that it also has a type only import that will be removed during transpilation,
 * and it needs to be accounted for with the restoration of new lines.
 */
const codeStr = `import { Command, Args } from '@sapphire/framework';
import type { Message } from 'discord.js';

export class EchoCommand extends Command {
  public constructor(context: Command.Context, options: Command.Options) {
    super(context, {
      ...options,
      aliases: ['parrot', 'copy'],
      description: 'Replies with the text you provide'
    });
  }

  public async messageRun(message: Message, args: Args) {
    // ...
  }
}`;

const emptyLineEscapedTsCode = escapeNewLines(codeStr);

const esmCode = tsToEsm(emptyLineEscapedTsCode).outputText;
const cjsCode = esmToCjs(esmCode);
```

**Comment by wbt** [comment] 2022-02-16 21:24
I would also like to see this implemented, with a few specific reasons in mind:
- Consistency with general design philosophy per NoelAbrahams' [comment above](https://github.com/Microsoft/TypeScript/issues/843#issuecomment-58568441)
- Ciantic's [comment](https://github.com/Microsoft/TypeScript/issues/843#issuecomment-332661356) about needing to deliver JS elsewhere
- Being able to cleanly compare JS generated through TS and JS that existed before, where demonstrating a close match is important to adoption
- Not having long lines requiring horizontal scrolling in the emitted code, where the source included line breaks to make things neat and beautiful and meeting linter/style specs (also [commented on above](https://github.com/Microsoft/TypeScript/issues/843#issuecomment-77045982))
- Being able to [continue working with transpiled JS](https://github.com/Microsoft/TypeScript/issues/843#issuecomment-210254059) if all these overhead costs of TypeScript become too much; anticipating difficulty here creates lock-in costs that raise barriers to adoption in the first place.

[This PR](https://github.com/microsoft/TypeScript/pull/36688), discussed in the [3.9 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#code-actions-preserve-newlines), show code actions preserving newlines; why can't the emitted code do something similar?

**Comment by devope** [comment] 2024-01-03 07:34
Are there any updates for almost 10 years?
I would like to be able to configure preserving new lines

**Comment by RyanCavanaugh** [comment] 2024-01-03 20:52
I'm changing this to Won't Fix. Reasons:
 * This has obviously not been a key blocker for anyone
 * Of all the "keep trivia" problems we have, this is surely the lowest-priority among them
 * At this point, *many* alternative transpilers with different behaviors around comments/whitespace exist; if you need truly need newline preservation, you can use one of those
 * Performance remains top-of-mind for us and anything that makes emit slower needs to be carrying a lot more value than newline preservation.

**Closed by RyanCavanaugh** 2024-01-03 20:52 UTC
Labels: Won't Fix

**Comment by rattrayalex** [comment] 2024-01-04 01:15
> At this point, many alternative transpilers with different configurable behaviors around comments/whitespace exist

Does anyone know of a good option for this?

**Comment by favna** [comment] 2024-01-04 09:16
> > At this point, many alternative transpilers with different configurable behaviors around comments/whitespace exist
> 
> Does anyone know of a good option for this?

It depends on your exact needs. There are several suggestions in this issue and a list of other transpilers is as follows. Note that this list hasn't been sanitized for the specific requirement:

- [tsup](https://tsup.egoist.dev) (uses esbuild or swc depending on config)
- [esbuild](https://esbuild.github.io)
- [swc](https://swc.rs)
- [babel](https://babeljs.io/) (with [@babel/plugin-typescript](https://babeljs.io/docs/babel-preset-typescript))
- [rollu]() (with [@rollup/plugin-typescript](https://github.com/rollup/plugins/tree/master/packages/typescript) or [rollup-plugin-typescript2](https://github.com/ezolenko/rollup-plugin-typescript2))
- [turbopack](https://turbo.build/pack)
