### ISSUE TITLE
Should prefer relative path first before index when it comes to suggestions

### ISSUE THREAD

**Issue by mmahalwy** [microsoft/TypeScript#47040] opened 2021-12-02 05:54 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.3
- OS Version: Darwin arm64 20.6.0

Steps to Reproduce:

1. Have a function that is exported from a file, call it './baseSchemas.ts'
2. Have an index file that exports the contents of that file, `export * as baseSchemas from './baseSchemas'`
3. Try to import that function in a file, see something like this:
![image](https://user-images.githubusercontent.com/3749095/144365724-85a50088-db25-485e-822e-13613f4f5fec.png)

Expectation is the relative should be preferred over the index. When importing or default to index, it can cause a circular dependency if index is imported, which then index imports the same file.

**Comment by RyanCavanaugh** [comment] 2021-12-07 18:52
This is the intended behavior; shorter paths (those with fewer directory separators) are always preferred over longer ones. The motivation is that packages which re-export their contents are typically doing so to provide a unified API surface (meaning they don't want you to index into their subdirectories as shown here).

**Comment by mmahalwy** [comment] 2021-12-07 19:41
@RyanCavanaugh makes sense. Is there a way to switch the order? I had seen an `TypeScript › Preferences: Import Module Specifier` but not sure if that influences this

**Comment by RyanCavanaugh** [comment] 2021-12-07 20:29
Not sure. @andrewbranch ?

**Comment by andrewbranch** [comment] 2021-12-07 20:52
Duplicate of #45953. We’ll probably drop paths that resolve to nothing but dots and slashes as that often creates an import cycle between a barrel re-export and the file that’s importing it (which may not be a problem at runtime, but can be if the modules have side effects, and I’ve just never seen anyone use import paths like that on purpose).

**Closed** 2021-12-10 18:00 UTC
Labels: Duplicate
