### ISSUE TITLE
Suggestion: add config excludeTypes

### ISSUE THREAD

**Issue by k8w** [Microsoft/TypeScript#17242] opened 2017-07-17 11:32 UTC
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)
2.4.0

**Code**

This is a frontend project.

```ts
let timer: number = setTimeout(()=>{}, 1000);
```

```
npm i @types/protobufjs
```

**Expected behavior:**
Compile success

**Actual behavior:**
Compile error for type of timer not match that in `@types/node`

`@types/node` is a dependency that `@types/protobufjs` need.
But in frontend project, it always be brought by  some lib (maybe can run both at browser and server)

Need some way to exclude @types/node for frontend project.

So suggest this:

```
{
  ..
  excludeTypes: ['@types/node']
}
```

**Comment by ikatyang** [comment] 2017-07-17 12:52
It seems duplicate of #17042?

**Closed** 2017-09-07 17:44 UTC
Labels: Duplicate
