### ISSUE TITLE
Associativity fails for intersections of unions

### ISSUE THREAD

**Issue by tenedor** [Microsoft/TypeScript#19055] opened 2017-10-09 22:38 UTC
**TypeScript Version:**  2.5.1-insiders.20170825

**Code**

```ts
interface A {
    identity: 'a';
    a: number;
}
interface B {
    identity: 'b';
    b: number;
}
interface C {}

// This function errors as written. It does not error if changed to `value: C & (A | B)`.
function f(value: ((A | B) & C) & (A | B)): number {
    switch (value.identity) {
        case 'a':
            return value.a; // Error: Property 'a' does not exist on 'B & C'.
        case 'b':
            return value.b; // Error: Property 'b' does not exist on 'A & C'.
    }
}
```

**Expected behavior:**
No error. This is a discriminated union and the switch statement should infer property `a`.

Furthermore, I expect that the following types are equivalent:
1. `((A | B) & C) & (A | B)`
2. `(A | B) & C & (A | B)`
3. `C & (A | B)`

However, 1 behaves differently from 2 and 3.

**Actual behavior:**

TS errors because it fails to infer that the type cannot be `B & C` in the first case.

**Comment by tenedor** [comment] 2017-10-09 22:43
Here is a practical example where this causes problems in a codebase. This is analogous to the issue I ran into at my company. If I have a union type (Animal) and a mixin (Domestic) and I define their composite type (Domestic Animal), I am unable to restrict this type to a subset of the union (Domestic Dog) by using an intersection. Instead I need to expose the mixin - `Domestic & Dog` instead of `DomesticAnimal & Dog`. I do not want to do this because I want to keep the mixin private.

```
interface Laborador {
    breed: 'laborador';
    bark: () => void;
}
interface Chihuahua {
    breed: 'chihuahua';
    yip: () => void;
}
interface Cat {
    breed: 'cat';
}
type Animal = Laborador | Chihuahua | Cat;
interface Domestic {
    wearsLeash: boolean;
}
type DomesticAnimal = Animal & Domestic;

function makeDogNoise(domesticDog: DomesticAnimal & (Laborador | Chihuahua)): void {
    switch (domesticDog.breed) {
        case 'laborador':
            domesticDog.bark(); // Error: Property 'bark' does not exist on `Chihuahua & Domestic`
        case 'chihuahua':
            domesticDog.yip(); // Error: Property 'bark' does not exist on `Laborador & Domestic`
    }
}
```

**Comment by jcalz** [comment] 2017-10-10 18:07
You could think of this as a failure of associativity (the type system must not be collapsing nested intersections to a flat intersection before processing futher) or as a failure of absorption (see #16386) since `X & Y` is a subtype of `X`, and therefore the intersection should collapse to `X & Y` (where `X` is `A|B` and `Y` is `C` in your case). 

If I inspect what happens to `((A | B) & C) & (A | B)` in the compiler, it gets distributed to `(A & C) | (B & C) | (A & C & B) | (B & C & A)`, whereas `(A | B) & C & (A | B)` gets distributed to `(A & C) | (B & C)`.  The former could be further reduced by absorption to the latter.  The former confuses the control flow analysis, as you see.

Obviously there's a workaround:
```ts
function f(value: ((A | B) & C) & (A | B)): number {
  const v: (A & C) | (B & C) = value;
  switch (v.identity) {
    case 'a':
      return v.a; // okay
    case 'b':
      return v.b; // okay
    default:
      const exhaustivenessCheck: never = v;
      return exhaustivenessCheck;
  }
}
```

Or in your animal example,
```ts
function makeDogNoise(
  domesticDog: (DomesticAnimal & Labrador) & (DomesticAnimal & Chihuahua)
): void {}
```
No need to expose the `Domestic` mixin.

**Comment by tenedor** [comment] 2017-10-11 15:44
Thanks @jcalz, agreed on every point.

The reason this one matters to my team is that in our real code there are 31 "dogs" and 51 total "animals", and these combine with either of two modifying types like "domestic". We're using this fine-grained typing because we need to write N x N interleaving rules for every animal pairing and very much want discriminated unions with `never` checks to ensure we don't miss an interleaving. The set of animals occasionally changes, too, and we need to update all the interleavings:

```ts
type Dog = Laborador | Chihuahua | GreatDane | Poodle /* | ... x 31 */;
type Cat = Siamese | Tawny | Calico /* | ... x 12 */;
type OtherAnimal = Elephant | Giraffe /* | ... x 8 */;
type Animal = Dog | Cat | OtherAnimal;
```
interface Domestic { wearsLeash: boolean; };
export type DomesticAnimal = Animal & Domestic;

function getsAlong(animal1: DomesticAnimal, animal2: UndomesticAnimal) {
  switch (animal1.type) {
    case 'poodle':
    case 'chihuahua':
      return getsAlongWithSmallDomesticAnimal(animal2);
    // ...
    default:
      return assertNever(animal1);
  }
}
```

For now we've decided to expose `Domestic` and `Undomestic` as well as `DomesticAnimal` and `UndomesticAnimal`, but it's confusing for unfamiliar developers to track the difference. Our actual name for `Domestic` ends up more like `DomesticAnimalMixin` so it all ends up more esoteric than the metaphor suggests.

**Comment by mhegazy** [comment] 2017-10-11 20:14
The examples in this thread should be addressed by https://github.com/Microsoft/TypeScript/pull/18438. most of the cases with unit types (the discriminant) that were in the past an intersection (e.g. `poodle` & `chiuahua`), now reduce to `never`, which removes them from the union.

**Comment by mhegazy** [comment] 2017-10-11 20:15
Marking this issue as a duplicate of #16386 and #18210.

**Comment by tenedor** [comment] 2017-10-12 08:02
@mhegazy great, this seems correct. Thanks.

**Closed** 2017-10-12 18:33 UTC
Labels: Duplicate
