### ISSUE TITLE
TypeScript ignores type of JSX spread props if the JSX tag is non-empty

### ISSUE THREAD

**Issue by bluenote10** [microsoft/TypeScript#44782] opened 2021-06-28 07:50 UTC
# Bug Report

### 🔎 Search Terms

jsx empty

Possibly related issues:
- https://github.com/microsoft/TypeScript/issues/43760

Related SO question: [Why does TypeScript ignore the type of JSX spread props if the JSX tag is not empty?](https://stackoverflow.com/questions/67764224/why-does-typescript-ignore-the-type-of-jsx-spread-props-if-the-jsx-tag-is-not-em)

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about JSX.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4BYAKCrQgDsBneAIxQBMAFHMBuAXjgBvKnDitO3AFwFMECPgA0VAL5UqmAK50MwenAAqSJgEYAFAEohIuERgaodOAB42wAG5CAdN-FcIPZQB6AD4VNUpNbRhdR0MmACYLK0pRW3tHF3cvH3Y-AODnQNc3UMplIA)

### 💻 Code

This assumes JSX: React

```ts
const badProps = {
  badProp: "foo",
};

// This doesn't compile; as expected.
function Test1() {
  return <div {...badProps} />;
}

// This does compile; not expected.
function Test2() {
  return <div {...badProps}> </div>;
}
```

### 🙁 Actual behavior

The expression in `Test2` compiles without error.

### 🙂 Expected behavior

Type checks should apply to both empty and non-empty usages, and result in the same compilation error.

**Comment by andrewbranch** [comment] 2021-06-28 18:10
Duplicate of https://github.com/microsoft/TypeScript/issues/29883

The one that has an error has an error for a separate reason; the real behavior you’re talking about is the fact that excess properties are generally allowed on JSX elements if they come from spread. The former example just happens to error because it has _no_ good properties (whereas the latter has a matching `children` property), so it triggers our separate “this really looks like you have no idea what function/element you’re calling/creating” logic.

**Comment by bluenote10** [comment] 2021-06-29 07:10
Indeed #29883 would solve it. On the other hand #29883 is a feature request, while this particular behavior feels more like a bug.

**Comment by andrewbranch** [comment] 2021-06-29 14:14
#29883 is framed in an odd way, but just [a few comments down](https://github.com/microsoft/TypeScript/issues/29883#issuecomment-495779613) it’s argued and broadly 👍’d that it feels like a bug. Either way, this is behavior that we do know about and at one point did on purpose I guess, so changing it is “suggestion,” not a “bug fix” 🤷

**Comment by bluenote10** [comment] 2021-06-29 15:30
The bug aspect could be fixed independently by allowing excess properties in general. Technically this can't break any existing code. From a user perspective it would be clearer to allow excess properties entirely or not at all. That the language treats `<div {...badProps}> </div>` differently from `<div {...badProps}></div>` is highly unexpected.

Of course the cleaner / desired solution is to disallow them (via an option).

**Comment by andrewbranch** [comment] 2021-06-29 15:44
That’s not an excess-property thing; that’s a common-property thing, and the example you found just looks extra strange because of the way JSX obscures what’s going on under the hood. You can suppress the error not only by making the element non-empty, but by adding any other recognized prop:

```tsx
<div {...badProps}></div>                       // error: no properties in common
<div {...badProps} className="whatever"> </div> // no error, because source and target have overlap with `children`
<div {...badProps} className="whatever"></div>  // no error, because source and target have overlap with `className`
```

The “no properties in common logic” exists to catch likely mistakes where there would otherwise be no error: [playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFAhgawKYFUDOGBOAFCHvgFyIDeiYKAthgPwU5T4xgDmANIhnShgAbZolbsuvGABNRYEHQBGBRAF8AlFQCwAKESIA9AcQA6M7tW7dEBK0QCAnsoCCuAgHUYUABYBRAB5sKAAK+HAADgSwGDiIALzaejT0GBQARM5g0vgYAO5p3Lr6AG4YQnAQXg4UAMyFScAoxXDsUBgAwnDl5IhpikIgGGkWANxWOqiYbkSOLtOePgFBoRFRMDHqYzrWtlD2cKwAMjCYQg4AcnBQrqTxifr+FAAMJgBMAKw1rwCc9frViAAjCZ3gAWGrvJ5-RAALwoAFoaiZQa9QQA2b6jcaTbCkQh0A5QY6nC5XG4ETa6IA). There’s no type-theoretical reason to treat these two objects differently, since excess properties are allowed and all the target properties are optional. But when there’s _zero_ overlap, it looks quite likely to be a mistake, so we flag it.

So yes, you can often find strange examples that look highly inconsistent with each other when you put them side-by-side, but in this case that inconsistency is an unrelated feature, not a bug.

**Closed** 2021-07-01 18:00 UTC
Labels: Duplicate
