### ISSUE TITLE
Type narrowing with unreachable code error

### ISSUE THREAD

**Issue by Diverclaim** [microsoft/TypeScript#35239] opened 2019-11-20 18:52 UTC
**Playground link**
[playground](http://www.typescriptlang.org/play/?strictPropertyInitialization=false&strictBindCallApply=false&alwaysStrict=false&allowUnreachableCode=true&esModuleInterop=false&target=3&module=0#code/GYVwdgxgLglg9mABAdwKYwE4BMAUBKRAbwChFFRJYFEBzVMVDAQylQGUoMYwaB5DAHIgAtgCNG+AFyIAzp241EAH0RgR4jEVJlEMYIhwBZFgAsAdMzBY4w-IgB8iAAxmArARI6dGVFBAYkABYAJgBubTIAX0RUABsZVC0vMh8-AMQAIlFYpmymDPCvSO1i7VT-MHDtCAQ5RAA3JliQRIBeWnpGFnZ5Hn4hMQk8Qt19HCgATwAHVDh9RubEgEJW9oy5Lh4MjwjEGrA6tUGMADUmlukjjUR2hZaR4sigA)

**Code**
```
function weird() {
  function generateStringOrNumber(): string | number {
    if (Math.random() > 0.5) {
      return 42;
    } else {
      return "blabla";
    }
  }

  return; // this causes problems

  const value = generateStringOrNumber();
  if (typeof value !== "string") {
    const numberValue: number = value;
  }
}
```

**Actual behaviour**
Compiler error 
```
Type 'string | number' is not assignable to type 'number'.
  Type 'string' is not assignable to type 'number'.(2322)
```

**Expected behaviour**
Should compile fine

**Notes**
Remove return in function, and it actually compiles fine.

**Comment by j-oliveras** [comment] 2019-11-20 20:01
Duplicate of #33674 and #26914?

I only searched `narrowing unreachable`.

**Closed** 2019-11-22 21:13 UTC
Labels: Duplicate
