### ISSUE TITLE
TS Server fatal error:  path.replace is not a function

### ISSUE THREAD

**Issue by dipti-code** [microsoft/TypeScript#38164] opened 2020-04-24 10:46 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
TypeError: path.replace is not a function
    at normalizeSlashes (tsserver.js:6191:21)
    at Object.combinePaths (tsserver.js:6252:28)
    at getWildcardDirectories (tsserver.js:28441:48)
    at matchFileNames (tsserver.js:28299:35)
    at getFileNames (tsserver.js:27850:26)
    at parseJsonConfigFileContentWorker (tsserver.js:27782:18)
    at Object.parseJsonSourceFileConfigFileContent (tsserver.js:27740:16)
    at ProjectService.loadConfiguredProject (tsserver.js:142263:44)
    at ProjectService.createAndLoadConfiguredProject (tsserver.js:142240:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (tsserver.js:142245:36)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:143101:44)
    at tsserver.js:143396:107
    at Object.mapDefined (tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144260:46)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment] 2020-04-24 18:25
@dipti-code Does your project contain a jsconfig or tsconfig file? Can you share these?

**Comment by dipti-code** [comment] 2020-04-27 06:06
@mjbvz my tsconf.json is like 
{
  "compilerOptions": {
     "target": "es5",
     "module": "commonjs",
     "baseUrl": ".",
     "paths": {
        "*": [
           "./*"
        ],
        "src/*": [
           "./src/*"
        ],
        "test/*": [
           "./test/*"
        ]
     },
     "types": [
         "node",
         "@wdio/sync",
         "@wdio/jasmine-framework"
      ],
      "allowSyntheticDefaultImports": true,
       "esModuleInterop": true
  },
  "include": [
   ["./**/*.ts"]
  ]
}



and also , my Vs code behaved abruptly, no intellisence or function hover not working

**Comment by dipti-code** [comment] 2020-04-28 10:42
@mjbvz Any update on this.
and why its happening to my typescript project only that is created recently, not with other typescripts projects.

I converted the.js files to TS.

**Comment by mjbvz** [comment] 2020-05-28 17:02
@RyanCavanaugh Marking this as a VS Code priority since we've seen a few user reports of the problem

**Comment by sheetalkamat** [comment] 2020-05-28 18:56
Please share the logs to be able to investigate this
You can upload logs by following these steps:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. In vscode or vscode insiders, run the `TypeScript: Open TS Server log` command
5. This should open a large file called `tsserver.log`. Please share this file. Additionally you can also share file `ti.log` created next to it.

**Comment by darkl1ght** [comment] 2020-08-13 06:19
@RyanCavanaugh I have provided all the info you need in my issue([https://github.com/microsoft/TypeScript/issues/39856](https://github.com/microsoft/TypeScript/issues/39856)). Let me know if you need more details.

@sheetalkamat FYI..

**Closed** 2020-08-14 00:08 UTC
Labels: Bug, Fix Available, VS Code Priority
