### ISSUE TITLE
refactor convert params to de-struct obj: TypeScript Server Error (3.7.3) Debug Failure. False expression.

### ISSUE THREAD

**Issue by thelazydogsback** [microsoft/TypeScript#36277] opened 2020-01-18 01:28 UTC
Trying to refactor a fn in a tsx file with the shape below, I got the following error:

```
export function DropdownEditor<TData extends object, TOpt>(
                        a:string, b: boolean,
                        c:(row:TData)=> TOpt[], 
                        d? : (opt:TOpt, row:TData) => boolean, 
                        e?:(opt:TOpt)=>string,
                        f?:(opt:TOpt,state:RenderOptionState)=>any,
                        g?:(opt:TOpt)=>string )   {  

```

```
<semantic> TypeScript Server Error (3.7.3)
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at getPos (tsserver.js:119224:22)
    at assignPositionsToNode (tsserver.js:119965:27)
    at visitNode (tsserver.js:70797:23)
    at Object.visitEachChild (tsserver.js:71014:117)
    at assignPositionsToNode (tsserver.js:119962:30)
    at visitNode (tsserver.js:70797:23)
    at visitFunctionBody (tsserver.js:70901:23)
    at Object.visitEachChild (tsserver.js:71038:358)
    at assignPositionsToNode (tsserver.js:119962:30)
    at visitNode (tsserver.js:70797:23)
    at Object.visitEachChild (tsserver.js:71184:108)
    at assignPositionsToNode (tsserver.js:119962:30)
    at Object.visitNodes (tsserver.js:70848:48)
    at assignPositionsToNodeArray (tsserver.js:119970:30)
    at Object.visitEachChild (tsserver.js:71011:53)
    at assignPositionsToNode (tsserver.js:119962:30)
    at getNonformattedText (tsserver.js:119946:56)
    at getFormattedTextOfNode (tsserver.js:119927:26)
    at format (tsserver.js:119910:52)
    at computeNewText (tsserver.js:119913:23)
    at tsserver.js:119883:89
    at Array.map (<anonymous>)
    at tsserver.js:119882:50
    at Array.map (<anonymous>)
    at Object.getTextChangesFromChanges (tsserver.js:119868:86)
    at ChangeTracker.getChanges (tsserver.js:119838:45)
    at Function.ChangeTracker.with (tsserver.js:119360:32)
    at Object.getEditsForAction (tsserver.js:129156:66)
    at Object.getEditsForRefactor (tsserver.js:120455:41)
    at Object.getEditsForRefactor (tsserver.js:131324:32)
    at IOSession.Session.getEditsForRefactor (tsserver.js:140691:59)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139542:61)
    at tsserver.js:140929:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140920:28)
    at IOSession.Session.executeCommand (tsserver.js:140929:33)
    at IOSession.Session.onMessage (tsserver.js:140952:35)
    at Interface.<anonymous> (tsserver.js:142267:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment] 2020-01-18 02:00
Can you please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). Do you still see this issue after installing that extension and restarting VS Code?

**Comment by thelazydogsback** [comment] 2020-01-19 01:51
I installed the latest nightly (extension info pasted below), restarted and made sure that "use vscode version" was selected -- however, the 3.8.2 was not listed (only 3.8.0) and the error remains the same.


```Name: JavaScript and TypeScript Nightly
Id: ms-vscode.vscode-typescript-next
Description: Enables typescript@next to power VS Code's built-in JavaScript and TypeScript support
Version: 3.8.20200118
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next```

**Comment by thelazydogsback** [comment] 2020-01-22 20:34
Any other ideas to try?

**Comment by elibarzilay** [comment] 2020-05-07 20:48
@thelazydogsback, @mjbvz: Perhaps I'm doing something wrong, but I can't reproduce this.  Below shows what I did, and the log doesn't show any problems either.  (I remember some fix I did that was related to `getPos` not too long ago, so maybe that's why it works now.)

![Refactor](https://user-images.githubusercontent.com/185905/81343153-6f8ed000-9082-11ea-9324-6d04fb346087.gif)

**Comment by mjbvz** [comment] 2020-05-08 18:58
@elibarzilay Try testing when you have a caller too

@thelazydogsback Can you share the full code that originally caused this?

**Comment by elibarzilay** [comment] 2020-05-11 17:00
@mjbvz, I added:
```
DropdownEditor("", true);
```
and
```
DropdownEditor("", true, _x => [{}], (_x,_y) => true, _x => "",
               (_x,_y) => {}, _x => "");
```
and it worked fine in both cases.

**Comment by thelazydogsback** [comment] 2020-05-11 17:50
As of the latest version this re-factor now completes without error for me.
However, it produces code that fails to compile at some of the call-sites.
I need to look into it more when I have tie, but this looks like it's because the refactor unfortunately does *not* keep type information -- e.g., it will convert:

`foo(x:int)` to `foo({x})`, not to `foo({x:int})`.

And the compiler doesn't quite match def-site and call-site type-inferences. 
Keeping types (perhaps as an option) would also make the code much more self-documenting -- would like to make this a feature request...

Should I put the details here, or would this be a new bug??
Also I'm not sure if it is indeed a bug -- it depends whether this re-factor is guaranteed to work, or it if considered a "starting point" for complex cases.

thanks

**Comment by RyanCavanaugh** [comment] 2020-05-12 15:41
Refactors aren't (can't) be guaranteed to always produce error-free code on the other side - there are simply too many ways to call or indirect a function in JS for us to handle all of them.

**Comment by RyanCavanaugh** [comment] 2020-05-21 17:14
Closing due to lack of repro. Please log a new issue if you see a crash again. Thanks!

**Closed by RyanCavanaugh** 2020-05-21 17:14 UTC
Labels: Bug, Needs More Info, Rescheduled
