### ISSUE TITLE
`Move to new file` does not carry over global 'use strict'

### ISSUE THREAD

**Issue by spazmodius** [microsoft/TypeScript#40292] opened 2020-08-27 21:05 UTC
Given a javascript source file that sets strict mode (`'use strict'`),
When using the **Move to a new file** refactoring to extract a function declaration, 
Then the resulting function ends up in a non-strict file.

It is possible for this to change the program's behavior.

- VSCode Version: **1.48.1**
- OS Version: **Windows 10**

Steps to Reproduce:

1. Given `main.js`:
```js
'use strict'
const fs = require('fs')
function foo() { return this }
console.log(foo())
```

2. Running `node main` produces the output:
```console
undefined
```

3. Extract `foo` using the **Move to a new file** refactoring.

This modifies `main.js`:
```js
'use strict'
const fs = require('fs')
const { foo } = require("./foo")
console.log(foo())
```
and generates `foo.js`:
```js
function foo() { return this; }
exports.foo = foo;
```
4. Now running `node main` produces the output:
```console
Object [global] {
  global: [Circular],
  ....
```

Manually adding `'use strict'` to `foo.js` restores the original behavior.

**Comment by a-tarasyuk** [comment] 2020-08-28 17:57
Do we need to suggest _"Move to a new file"_ for directives?

```ts
[|"use strict";|] ?
```

```ts
function foo() {
    [|"use strict";|] ?
} 
```

cc @DanielRosenwasser @RyanCavanaugh

**Comment by DanielRosenwasser** [comment] 2020-08-28 17:59
No, the intent is that when declarations are moved to a new file, every prologue should be moved over as well.

**Comment by DanielRosenwasser** [comment] 2020-08-28 17:59
Actually, I'm going to close this as a duplicate of #30478 because I already filed this issue.

**Closed** 2020-08-28 18:00 UTC
Labels: Duplicate

**Comment by a-tarasyuk** [comment] 2020-08-28 18:03
Ouch, I can do PR to resolve the issue with the prologue directives, if, of course, this is acceptable.

**Comment by DanielRosenwasser** [comment] 2020-08-28 18:22
Absolutely, that would be great!
