### ISSUE TITLE
Intellisense suggestions for string literal type.

### ISSUE THREAD

**Issue by Tharaxis** [Microsoft/TypeScript#7572] opened 2016-03-17 23:00 UTC
Would be great if CTRL+Space (or whatever your hotkey is for show suggestions) would show all the literal string options available for string literals.

In my case I have an `<Icon>` React component which takes an icon key as one of its props, and I want to limit the options that can be chosen. The string literals work great. Unfortunately because of the number of icons it's somewhat difficult to know _what_ your options are and the intellisense is next to useless in this case because you get basically the first 3 or 4 options in the description, but nothing more. Being able to invoke suggestions and get the list would be a huge help.

**Comment by DanielRosenwasser** [comment] 2016-03-17 23:09
Thanks for filing, but this is a duplicate of #606.

**Closed by DanielRosenwasser** 2016-03-17 23:09 UTC
