### ISSUE TITLE
Refinement of object works and it doesn't

### ISSUE THREAD

**Issue by lll000111** [microsoft/TypeScript#32301] opened 2019-07-08 20:00 UTC
I created a few tiny examples, one per demo function:

[**Playground link**](https://www.typescriptlang.org/play/index.html?target=6#code/GYVwdgxgLglg9mABAEwKYFs4DUCMAKKACxjAHMAuRcAazDgHcwBKSgNzhmUQG8AoRAYhjBEBYmUQBeaYjAgANvMQAfZYigBPAA6o4IoiVKIAhDIDkcAEYArVNDNMe-QS6IAnBrNT1EAUTcebnhmdFCIAIZIVrb2TADczgIAvryJiBAIAM5h0ZTRdmGS6uKkCSm8oJCwCCgY2ABMYoaUNHSMLIjsnE4uwqKaOnrFhibm+bE9LoLunmDefgFwQSFwYZGI41AOCS7lvSJNEtJFcoqOfFPThB4+cz7+gcGhEVE2Bdtpe4IZYNkbNnk3tApMMyGVUpVoPAkGhMFgAMyHChUMC0BjMNgcLgXQR9JGjE4KJQAMmJ6m0un0JSkYyBW3OaRcPz+uX+MUKoNKn145Uh1RhdSwABYkS1UW0MZ0sZMBHzoUJMgB5OmilFo9qUAwSGCZNkFGVTNyoKAgNxIYz446yIkqNQDSmcgmICx0j67VL7UQ65XspFMBmXATMnIAvXAoparnu3ngKE1WHYACsqta6I6XWxaTlNW9KsjYvVksjCrDYRxlyNJrNjtMhMUiFJ5MGVJGVpd7LMO0EXwEeNzvsj-oNTKyIesgPZIMjXeSPN4QA)

In particular, these two:

```js
function demoV1(thing: unknown): void {
    if (thing === null || typeof thing !== 'object') {
        throw new Error('not an object');
    }

    // ERROR: thing is object || null
    const obj: object = thing;
}

function demoV2(thing: unknown): void {
    if (typeof thing !== 'object') {
        throw new Error('not an object');
    }

    if (thing === null) {
        throw new Error('not an object');
    }

    // WORKS
    const obj: object = thing;
}
```

So... TypeScript does not understand an or operator "||" to test twp things in the same `if()`?

**Comment by lll000111** [comment] 2019-07-08 20:04
Okay... so I found that the _order_ of the individual tests matters, which is just as strange so I see no reason to close the issue.

```js
function demoV1(thing: unknown): void {
    if (typeof thing !== 'object' || thing === null) {
        throw new Error('not an object');
    }

    // WORKS
    const obj: object = thing;
}

function demoV2(thing: unknown): void {
    if (thing === null) {
        throw new Error('not an object');
    }

    if (typeof thing !== 'object') {
        throw new Error('not an object');
    }

     // ERROR: thing is object || null
    const obj: object = thing;
}

```

**Comment by jack-williams** [comment] 2019-07-08 20:22
Duplicate of #28131

**Closed** 2019-07-08 20:33 UTC
Labels: Duplicate
