### ISSUE TITLE
It's possible for the language service in VS 2015 to not work with two tsconfig.json files in the same project

### ISSUE THREAD

**Issue by Tragetaschen** [Microsoft/TypeScript#11882] opened 2016-10-27 07:36 UTC
**TypeScript Version:**  2.0.\* (tested with both 2.0.3 and 2.0.6)

**Code**

I've got the following folder structure in my project

```
Client\tsconfig.json
Client\main.ts
Client\angular2\
Client\application\
phantomcss\file.ts
phantomcss\package.json
phantomcss\tsconfig.json
Server\asp.net Core Application*
package.json (for angular2)
node_modules (for this package.json)
project.json
app.xproj
```

Note that the `phantomcss` folder doesn't have the `node_modules` folder for its `package.json`.

**Expected behavior:**

For the `Client` subfolder, the language service in VS (the three drop-downs above `.ts` files, folding controls for classes etc.) works normally.

**Actual behavior:** 
There is no language service beyond basic syntax highlighting.

Once I `npm install` in the `phantomcss` folder, things light up in VS and everything works as expected.
Also, if I rename / remove `phantomcss/tsconfig.json`, everything works.

**Comment by Tragetaschen** [comment] 2016-10-27 07:39
The `phantomcss\tsconfig.json` references `@types` that are only ever installed by the sibling `phantomcss\package.json`, other than that it's an entirely standard config:

```
{
  "compilerOptions": {
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "target": "es5",
    "types": [
      "casperjs",
      "phantomcss"
    ]
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false
}
```

**Comment by arusakov** [comment] 2016-10-27 13:44
VSCode also doesn't work right for project with more than one tsconfig.json after upgrading to TypeScript 2.0.6

**Comment by mhegazy** [comment] 2016-10-27 18:58
@Tragetaschen  can you share a sample project we can look at. i can not get this to repro on a simple project.

**Comment by mhegazy** [comment] 2016-10-27 18:58
@arusakov can you share more information.

**Comment by Tragetaschen** [comment] 2016-10-28 07:58
I have reduced my application to [Tragetaschen/typescript-issue-11882](https://github.com/Tragetaschen/typescript-issue-11882)

Visual Studio should settle with no TS language service:

![image](https://cloud.githubusercontent.com/assets/1947968/19799065/dc5214a2-9cf4-11e6-93cb-4b741219c00c.png)

Once I run `npm install` in `phantomcss` or remove the `types` option from `phantomcss\tsconfig.json, everything lights up:

![image](https://cloud.githubusercontent.com/assets/1947968/19799096/0e5afe82-9cf5-11e6-86d3-a2709659ac76.png)

**Comment by Tragetaschen** [comment] 2016-11-07 20:27
Hmm: `Has More Info`

**Comment by mhegazy** [comment] 2016-11-07 21:12
thanks @Tragetaschen for the repro. we see the issue now. should have a fix soon. the issue is triggered by the missing @types packages for `"casperjs"` and `"phantomcss"`.

**Comment by vladima** [comment] 2016-11-08 22:06
fixed in internal bits

**Closed by vladima** 2016-11-08 22:06 UTC
Labels: Bug, Fixed, Visual Studio
