### ISSUE TITLE
Some code became broken in 4.7

### ISSUE THREAD

**Issue by HanabishiRecca** [microsoft/TypeScript#49338] opened 2022-06-01 11:54 UTC
# Bug Report

### 🔎 Search Terms

4.7

### 🕗 Version & Regression Information

Such code became broken in 4.7. It works as expected in 4.6.

### ⏯ Playground Link

[4.6 example](https://www.typescriptlang.org/play?ts=4.6.4#code/C4TwDgpgBAKuEGcCyBDMUC8UDeAoKBUA2gAwC6AXDlAGYD2dVA5AEYoBOTA3FAL5f5CRAIyVqKZi258B-XLlCQoABQA8MKBAAewCADsAJgigBrCCDo1Y8ZGgB8masCowevKADJrkW2CIwyAXlFaDhIAAkUQwAbCHZjLDxCYg0ASz1Tc0tvRFQwMgB+KgAKMCo1GDsASkwHADc6VINZIIBjOj0EYCgQyJi4hBd4PoNY+MckoXISsBqMB3bOuliAOmi6AHNSlfo6KoAaQQIRMVK5hY6EZYg1ze2UA9w5XEWuqA6AZToAWwgAUTq+m6WHUmh0+iMmQsVjCuXspXK6mqtSOPWGUVGAyIYBWwEKKzOAiAA)

[4.7 example](https://www.typescriptlang.org/play?ts=4.7.0-beta#code/C4TwDgpgBAKuEGcCyBDMUC8UDeAoKBUA2gAwC6AXDlAGYD2dVA5AEYoBOTA3FAL5f5CRAIyVqKZi258B-XLlCQoABQA8MKBAAewCADsAJgigBrCCDo1Y8ZGgB8masCowevKADJrkW2CIwyAXlFaDhIAAkUQwAbCHZjLDxCYg0ASz1Tc0tvRFQwMgB+KgAKMCo1GDsASkwHADc6VINZIIBjOj0EYCgQyJi4hBd4PoNY+MckoXISsBqMB3bOuliAOmi6AHNSlfo6KoAaQQIRMVK5hY6EZYg1ze2UA9w5XEWuqA6AZToAWwgAUTq+m6WHUmh0+iMmQsVjCuXspXK6mqtSOPWGUVGAyIYBWwEKKzOAiAA)

### 💻 Code

```ts
type TypesMap = {
    [0]: { foo: 'bar'; };
    [1]: { a: 'b'; };
};

type P<T extends keyof TypesMap> = { t: T; } & TypesMap[T];

type TypeHandlers = {
    [T in keyof TypesMap]?: (p: P<T>) => void;
};

const typeHandlers: TypeHandlers = {
    [0]: (p) => console.log(p.foo),
    [1]: (p) => console.log(p.a),
};

const onSomeEvent = <T extends keyof TypesMap>(p: P<T>) =>
    typeHandlers[p.t]?.(p);
```

Also it works in 4.7 with optional (`?`) removed from `TypeHandlers` index.

### 🙁 Actual behavior

The code won't compile.

### 🙂 Expected behavior

The code should compile.

**Comment by fatcerberus** [comment] 2022-06-01 12:59
> ```ts
> type Packet<T extends keyof PacketTypes> = { op: T; } & PacketTypes[T];
> ```
>
> `op: T` is not narrowed by generic for some reason.

Not sure what you mean by "narrowed by generic"?  You're going to have to give more details about what's going wrong.  "The code won't compile" isn't very helpful.

**Comment by HanabishiRecca** [comment] 2022-06-01 14:13
Ok, I figured out something.
Such example works fine for both 4.6 and 4.7 as expected:

```ts
type TypesMap = {
    [0]: { foo: 'bar'; };
    [1]: { a: 'b'; };
};

type P<T extends keyof TypesMap> = { t: T; } & TypesMap[T];

type TypeHandlers = {
    [T in keyof TypesMap]: (p: P<T>) => void;
};

const typeHandlers: TypeHandlers = {
    [0]: (p) => console.log(p.foo),
    [1]: (p) => console.log(p.a),
};

const onSomeEvent = <T extends keyof TypesMap>(p: P<T>) =>
    typeHandlers[p.t]?.(p);
```

But when I add optional (`?`) to `TypeHandlers`
```ts
type TypesMap = {
    [0]: { foo: 'bar'; };
    [1]: { a: 'b'; };
};

type P<T extends keyof TypesMap> = { t: T; } & TypesMap[T];


type TypeHandlers = {
    [T in keyof TypesMap]?: (p: P<T>) => void;
};

const typeHandlers: TypeHandlers = {
    [0]: (p) => console.log(p.foo),
    [1]: (p) => console.log(p.a),
};

const onSomeEvent = <T extends keyof TypesMap>(p: P<T>) =>
    typeHandlers[p.t]?.(p);
```
it works as expected at 4.6 ([example](https://www.typescriptlang.org/play?ts=4.6.4#code/C4TwDgpgBAKuEGcCyBDMUC8UDeAoKBUA2gAwC6AXDlAGYD2dVA5AEYoBOTA3FAL5f5CRAIyVqKZi258B-XLlCQoABQA8MKBAAewCADsAJgigBrCCDo1Y8ZGgB8masCowevKADJrkW2CIwyAXlFaDhIAAkUQwAbCHZjLDxCYg0ASz1Tc0tvRFQwMgB+KgAKMCo1GDsASkwHADc6VINZIIBjOj0EYCgQyJi4hBd4PoNY+MckoXISsBqMB3bOuliAOmi6AHNSlfo6KoAaQQIRMVK5hY6EZYg1ze2UA9w5XEWuqA6AZToAWwgAUTq+m6WHUmh0+iMmQsVjCuXspXK6mqtSOPWGUVGAyIYBWwEKKzOAiAA)), but broken at 4.7 ([example](https://www.typescriptlang.org/play?ts=4.7.0-beta#code/C4TwDgpgBAKuEGcCyBDMUC8UDeAoKBUA2gAwC6AXDlAGYD2dVA5AEYoBOTA3FAL5f5CRAIyVqKZi258B-XLlCQoABQA8MKBAAewCADsAJgigBrCCDo1Y8ZGgB8masCowevKADJrkW2CIwyAXlFaDhIAAkUQwAbCHZjLDxCYg0ASz1Tc0tvRFQwMgB+KgAKMCo1GDsASkwHADc6VINZIIBjOj0EYCgQyJi4hBd4PoNY+MckoXISsBqMB3bOuliAOmi6AHNSlfo6KoAaQQIRMVK5hY6EZYg1ze2UA9w5XEWuqA6AZToAWwgAUTq+m6WHUmh0+iMmQsVjCuXspXK6mqtSOPWGUVGAyIYBWwEKKzOAiAA)).

I don't know why `?` breaks the code in 4.7.

**Comment by jcalz** [comment] 2022-06-01 14:18
Could be the same as #49242

**Comment by HanabishiRecca** [comment] 2022-06-01 14:27
> Could be the same as #49242

Yeah. Too bad the error is very obscure and I wasn't even able to properly explain it.

**Comment by ahejlsberg** [comment] 2022-06-01 16:29
This is indeed a duplicate of #49242.

**Closed** 2022-06-01 16:30 UTC
Labels: Duplicate
