### ISSUE TITLE
Runtime error when mixing into Object with es5 target

### ISSUE THREAD

**Issue by JustASquid** [Microsoft/TypeScript#18564] opened 2017-09-19 02:29 UTC
**TypeScript Version:**  2.5.2

**Code**

```ts
type Constructor<T = {}> = new (...args: any[]) => T;

function Mixin<T extends Constructor>(Base: T) {
	return class extends Base {
		NonArrowFunction() {
			console.log("Non Arrow Function");
		}
		
		ArrowFunction = () => {
			console.log("Arrow Function");
		}
	}
}

class A extends Mixin(Object) {
	constructor() {
		super()
		// No runtime errors
		this.ArrowFunction();
		
		// Runtime error in es5 export
		this.NonArrowFunction();
	}
}

new A();
```

**Expected behavior:**
No runtime error when compiled with `--target es5` and run with latest node version.

**Actual behavior:**
```
TypeError: _this.NonArrowFunction is not a function
    at new A (C:\Users\Daniel\Desktop\mixines5.js:31:15)
    at Object.<anonymous> (C:\Users\Daniel\Desktop\mixines5.js:36:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

The runtime error does not happen when mixing into an empty class as opposed to `Object`.

**Comment by DanielRosenwasser** [comment] 2017-09-19 03:09
Unfortunately this is a duplicate of #10762 and ES5-compliant emit can't properly model subclassing certain built-ins.

Check out the FAQ here: https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work

If it's available to you, you can call `Object.setPrototypeOf` at the end of your constructor.

**Comment by JustASquid** [comment] 2017-09-19 03:59
@DanielRosenwasser Thank you! What would you say would be the best way to describe mixing into an 'empty class' like this? Using
```
class Empty {}
class A extends Mixin(A) {}
```
is a bit verbose.

**Comment by aluanhaddad** [comment] 2017-09-19 12:34
@JustASquid what about
```ts
class A extends Mixin(class {}) {}
```

**Comment by mhegazy** [comment] 2017-10-03 16:55
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-03 16:55 UTC
Labels: Duplicate
