### ISSUE TITLE
Inferring type from a class private property doesn't working if hash (#) is used

### ISSUE THREAD

**Issue by n-gist** [microsoft/TypeScript#55764] opened 2023-09-16 20:18 UTC
### 🔎 Search Terms

using #
private #
typeof #

### 🕗 Version & Regression Information

Just found, TS 5.2.2

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYGwhgzhAEAqCmEAu0DeBYAUNH0u+gAcAnASwDcwl5oA7Ae2IFswQAuOgVyYCN5j8uAMQALSCI61ufAdlyCcpWgDN+AOUYt2cREgDaAcgbNWBgLoLoS1cQAS4jgmSHR485ctIAnoXj1lGiba3r7+0EgipBAAdMZanj5+yvYQEuGJYRFR0a6pHnI4lsD0tMjEnMBIjAAUAJRolgRZMXGs0AC80AAMjbjNOWKpHd29OP3W6pptnT0FBOGRMRN24sOz832L0SFJgVprowvZO-4pIgdzAL5Y15hAA

### 💻 Code

```
class Test {
    
    private normal: number
    #hash: number
    
    inferNormal: Test['normal']
    inferHash: Test['#hash']
    
    typeofNormal: typeof this.normal
    typeofHash: typeof this.#hash
    
    
    constructor() {
        this.normal = 0
        this.#hash = 0
        this.inferNormal = 0
        this.inferHash = 0
        this.typeofNormal = 0
        this.typeofHash = 0
    }
}
```

### 🙁 Actual behavior

Seems like TS doesn't see hash variables when they are used for type linking

### 🙂 Expected behavior

Perhaps they should behave the same?

### Additional information about the issue

It also gives variables different scopes when declared
`private variable` - `variable.other.property.ts`
`#variable` - `variable.object.property.ts`

Which is actually nice, it gives possibility to assign private variables separate color. I like how #variable is dimmed out. But inside methods they both get `variable.other.property.ts` scope, and therefore same color.

**Comment by MartinJohns** [comment] 2023-09-16 20:36
Duplicate of #47595.

**Comment by RyanCavanaugh** [comment] 2023-09-18 19:04
`Test['#hash']` isn't the type of `this.#hash`, it's the type of `this["#hash"]`, a separate property

**Closed** 2023-09-21 01:24 UTC
Labels: Duplicate
