### ISSUE TITLE
Circularities Only Blocked Sometimes

### ISSUE THREAD

**Issue by harrysolovay** [microsoft/TypeScript#37426] opened 2020-03-17 02:42 UTC
**TypeScript Version:**  3.8.2

**Search Terms:** circular, type, mapping, tuple, corresponding, signature

This builds off of [the issue I just submitted](https://github.com/microsoft/TypeScript/issues/37420) (tagged as a bug).

In summary, I'm trying to create a virtual type system.

I define the available types:

```ts
enum Type {
  Boolean = "Boolean",
  Int = "Int",
  List = "List",
}
```

I create a `Codec` type:

```ts
type Codec<
  T extends Type,
  C extends Codec<Type> | undefined = undefined
> = C extends undefined ? [T] : [T, C];
```

And I create a utility type, which can be used to unwrap / gather the corresponding type.

```ts
type AnyCodec = Codec<Type, Codec<Type> | undefined>;

type Decode<C extends AnyCodec> = C extends Codec<Type.Boolean>
  ? boolean
  : C extends Codec<Type.Int>
  ? number
  : C extends Codec<Type.List, Codec<Type>>
  ? C extends Codec<Type.List, infer I>
    ? I extends Codec<Type>
      ? Decode<I>[]
      : never
    : never
  : never;
```

Surely enough, it works for `Codec<Type.Int>`:

```ts
const intCodec: Codec<Type.Int> = [Type.Int];
type IntCodec = typeof intCodec;
type IntCodecDecoded = Decode<IntCodec>; // `string`
```

It works for `Codec<Type.Boolean>`:

```ts
const booleanCodec: Codec<Type.Boolean> = [Type.Boolean];
type BooleanCodec = typeof booleanCodec;
type BooleanCodecDecoded = Decode<BooleanCodec>; // `boolean`
```

And it works for `Codec<Type.List>`:

```ts
const listOfIntCodec: Codec<Type.List, Codec<Type.Int>> = [
  Type.List,
  [Type.Int],
];
type ListOfIntCodec = typeof listOfIntCodec;
type ListOfIntCodecDecoded = Decode<ListOfIntCodec>; // `number`
```

[TypeScript Playground of the example up to this point](http://www.typescriptlang.org/play?#code/KYOwrgtgBAKgngB2FA3gKClAQgexwG2AEMQoBeKAIlwOJEoBoMoBJEAF3KrfceYBkAlgGdOFSkNF8AvmjTtEyAMI4AJsADGAHmYwowAB7tQq4bEVNMS-UZNmV67fCQA+KAB8oYEOoBmgkGBVLm8-AKC0NwprQ2MfM1Dgf0DggH4oAG0YAF0oAC5MmAYoJWyAbjkFJCgAQRA4B00uRqcLErVNLWdgN09E5KCXCvlFKAARTQ6tGNt42vqWqJKbONN2xy7FADoaQhIXZnSAIzw9kGYCmdX7DtakLZ4DzHTwCCPgACcL5di7dc7ultJOxii1Nq4nlB0lc-mDAcDigFfJ9WJDnqwVrDbuCesxMOiJhopiwXBlsnj8QVAgA3T4UqnAWlfTAMpnDIkgURQALsFqXbGAx5cLLbHjlEbVHgtLhVYA4XzcjgtCqy1hK26EjrBCia9RaKW3IZQAD0xqgAANRB8AgBzc1yDlck60Eh8-53YA7U50JYi+67Oji1UB123GWKeVQZ1nZUS5AhkAtXVBLjJrQJxZlE1m83Ruj2tCOzj4ETsADyvgNjn5G3hpdBAtFHBcvt02wRzD9nrFTCDo2BFarTQossjJdEg-VjhV-dLk95Gsm6m14yXwC0A8rU80RtNFte7w+9qAA)

We see `Decode` works, even though it's self-referencing. There's no cycle-related error––presumably because of the use of tuples, which seem somewhat cycle-friendly since 3.7. Now let's add another type:

```diff
enum Type {
  Boolean = "Boolean",
  Int = "Int",
  List = "List",
+ Union = "Union",
}
```

We modify the `Codec` type to support multiple array of type `Codec` (the types to unite):

```ts
type Codec<
  T extends Type,
  // added `Codec<Type>[]`
  C extends Codec<Type> | Codec<Type>[] | undefined = undefined
> = C extends undefined ? [T] : [T, C];
```

And we update the definition of `AnyCodec`:

```ts
type AnyCodec = Codec<Type, Codec<Type> | Codec<Type>[] | undefined>;
```

Let's instantiate this type:

```ts
const unionOfIntAndBoolean: Codec<
  Type.Union,
  [Codec<Type.Boolean>, Codec<Type.Int>]
> = [Type.Union, [[Type.Boolean], [Type.Int]]];
type UnionOfIntAndBoolean = typeof unionOfIntAndBoolean;
```

And let's create and use the corresponding `DecodeUnion` utility:

```ts
type DecodeUnion<C extends Codec<Type.Union, [Type][]>> = C extends Codec<
  Type.Union,
  infer T
>
  ? T extends AnyCodec[]
    ? T[number] extends AnyCodec
      ? Decode<T[number]>
      : never
    : never
  : never;

type UnionOfIntAndBooleanDecoded = DecodeUnion<UnionOfIntAndBoolean>; // `number` | `boolean`
```

[TypeScript Playground of this example, continued up to this point](http://www.typescriptlang.org/play?#code/KYOwrgtgBAKgngB2FA3gKClAQgexwG2AEMQoBeKAIlwOJEoBoMoBJEAF3KrfceYBkAlgGdOFSkNF9MAVRCCcpcXIX0mAXzRp2iZAGEcAE2ABjADzMYUYAA92oQ8Ni6mmPdbsOnB4+fhIAPigAHygfUzN-YACAbQBdEKgwEGMAM0EQYEMuZLSMrLQgindbexSnXOB0zOyAfigYmASALgaYBjC4gG4tHSQoAEEQOHCTLlHIlzCjCKig0Im5+MTK6qyAnu1dKAARUxmzEs9yweHRorCPMsdp30mkADoaQhIA5nqAIzwXkGZWo+u3hmfl0Dx4b0w9XAEA+wAATn9LqUvLdZqDJOwOotdAEIVB6gCUdjHhiOhlUvDWHjIawrkTgfdosxMDS9iYDixYnFmSzWpkAG7wnl84CChGYEVizZ9ZBsmYqRSHOknYnAB4KkAdRq6OLxXHjZU3CaWUEa1xQcmUmCFd6wQ1OIYjYHxHn1GAxaGwuEJZEnR2jHms-bGSIeyBeuLU3lQAVCllQSVxhMx0XwzbskCiC0cUb-BlRMEcC7ax48bpbfo8UZcGU4VLZ9ijHoy1g54Fy4zZCgd4BmKvAjZQAD0Q6gAANRHCMgBzMdaDNZr60Ei51Egx7POjFgubkjllu7kDVii1+tLn5NivIQ+jHtd3bB3s3gddYejsfnuhztALzj4ETsAA8qk-a+HmdwFqSa6MoW7D6hQMQmiSAHmiWaplkw+7bBiwGgaYNa6HWUD-qIuFtr4zbYQBZGNu2j73j2Zg4SB5GmIOI7jp68Lfr+STyIoNFDIYh7gRESFqmazAxKqTzfFuWL5qC4Lctupr8ZqDRobJy4gHEWoFmWcRYf0GqCSkh4EUgRHJKoZnCXJJCUSZ6l2Yed5cD2GpmKZLHsEJh7se+XFwmOiQfg5IBjkAA)

The utility works! `UnionOfIntAndBooleanDecoded` is inferred as being of type `number | boolean`. Last but not least, let's integrate `DecodeUnion` into the more general `Decode` utility type.

This is where we run into trouble:

```diff
type Decode<C extends AnyCodec> = C extends Codec<Type.Boolean>
  ? boolean
  : C extends Codec<Type.Int>
  ? number
+ : C extends Codec<Type.Union, [Type][]>
+ ? DecodeUnion<C>
  : C extends Codec<Type.List, Codec<Type>>
  ? C extends Codec<Type.List, infer I>
    ? I extends Codec<Type>
      ? Decode<I>[]
      : never
    : never
  : never;
```

[TypeScript Playground, with the error-producing code](http://www.typescriptlang.org/play?#code/KYOwrgtgBAKgngB2FA3gKClAQgexwG2AEMQoBeKAIlwOJEoBoMoBJEAF3KrfceYBkAlgGdOFSkNF9MAVRCCcpcXIX0mAXzRp2iZAGEcAE2ABjADzMYUYAA92oQ8Ni6mmPdbsOnB4+fhIAPigAHygfUzN-YACAbQBdEKgwEGMAM0EQYEMuZLSMrLQgindbexSnXOB0zOyAfigYmASALgaYBjC4gG4tHSQoAEEQOHCTLlHIlzCjCKig0Im5+MTK6qyAnu1dKAARUxmzEs9yweHRorCPMsdp30mkADoaQhIA5nqAIzwXkGZWo+u3hmfl0Dx4b0w9XAEA+wAATn9LqUvLdZqDJOwOotdAEIVB6gCUdjHhiOhlUvDWHjIawrkTgfdosxMDS9iYDixYnFmSzWpkAG7wnl84CChGYf50k7E4APFSKDqNXRxeJ4+psmbykCHPEisWbPrIDXGLWHKU3GVy+QKtrK1UXQnShmWUFa1xQcmUmCFd6wc1OIYjYHxHn1GAxaGwuEJZEnQOjHms-bGSIRyBRuLU3lQAVCllQPV5gs50XwzbskCiD0cUb-BlRMEcC5Kx48bpbfo8UZcQ04VLV9ijHqG1g14HGrJcCdmLvAjZQAD0C6gAANRHCMgBzFdaCtVr60Ei11Egx7POjNhvnkjtkfXkDdii9-sHn5DjvIe+jCfZCjTr9zl0i7Liur50DuaB7pw+AiOwADyqSzr4dZ3A2pInoyjbsLiXAxC6JKwe6Laym2TC3tsGIIUhpg9rofZQDBohUWOvjDhRsHMYO47JpOf48WYlGISxpjzkuq6RvCEFQUk1ogJxQyGPeKERPhspuswMSWveARYvWoLgtyl6urJirEU83x0HEioNm2cTkf0WrySk960Ug9HJKoTmKRZJBsQ5slefeP5TjxpqOUJ7AKdpQFiSuElwiuiSgT5IArkAA)

While the prior self-reference did not result in a circularity error, this one does: `Type alias 'Decode' circularly references itself`.

Is there a workaround? Could this be related to [the aforementioned issue](https://github.com/microsoft/TypeScript/issues/37420)?

I know I've said it many times, but I truly mean it every time when I say: your help is greatly appreciated & thank you!!!

**Comment by soul-codes** [comment] 2020-03-17 03:08
Sorry if I hijack this issue, but I truly am not sure whether what I'm also experiencing somehow has a similar root cause to the OP (similar issue search took me here). @harrysolovay perhaps you could see if the behavior described below contributes to/is related to your issue in any way?

The issue that I've come across is that if a generic interface (`GenericBox`) is _directly_ part of a type alias (`Foo`), that type alias can use itself as generic argument to the generic interface. However, if the generic interface is then used as a part of a _generic_ type alias (`Bar`), another type alias (`UnionOfBar`) sending itself as generic argument into this generic type will result in a circular reference error. ([live](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgOIRNYCBCB7ADwB4AVAPmQG8AoZZANzgBsBXCALmRIG5qBfatTABPAA4oAYnjzIAvGgxZchIlLwUAPsgDOYKKADm3ZAHoTyAPIBpQSPHIccKKQrz0mfcuLledlAFUQYDwQCxhHKDkHJyJA4NDwp00dPUNjM2QAYWAoBBYmJ2QoCBhoDCRkaCg8KCA))

```ts
interface GenericBox<T> {
  value: T;
}

type Foo = GenericBox<Foo> | string; // OK

type Bar<T> = GenericBox<T>;
type UnionOfBar = Bar<UnionOfBar> | string; // Circular reference error
```

**Comment by harrysolovay** [comment] 2020-03-17 17:17
@soul-codes circularities are allowed in tuples, of which `UnionOfBar` is not. In tuples, it's possible to resolve the signature of the tuple to type-check its child elements, which might share their parent's signature. In the situation you describe, `UnionOfBar`'s signature is unclear––it describes itself. Might I ask what is your use case? There's likely a better way to describe your data.

**Comment by RyanCavanaugh** [comment] 2020-03-17 21:53
This might be fixed by https://github.com/microsoft/TypeScript/pull/37423 ; it's worth checking.

If not, this is kind of like how the police only *sometimes* pull you over for speeding. "Fixing" this probably won't be in the direction you want 😉

If you can narrow this down to a super simple example we could advise further

**Comment by soul-codes** [comment] 2020-03-18 04:31
@harrysolovay understood. I just wondered if our issues were in fact the same and perhaps, as Ryan has requested, yours could simplify to mine. It seems like it is rather a misunderstanding of how circularity is supposed to work on my side which led me to mistake it as a bug/issue. I will proceed to SO accordingly. Sorry to pollute this issue folks!

**Comment by harrysolovay** [comment] 2020-03-22 05:56
I was definitely speeding 😂

I managed to implement the desired type-mapping thanks to [a StackOverflow answer](https://stackoverflow.com/questions/60698306/mapping-between-circular-types-in-typescript) provided by the creator of [Punchcard](https://github.com/punchcard/punchcard), a serverless DX, which I encourage all to check out!

One of the monorepo's packages, "Shapes" (like "Codecs"), is used to map between the representations of different services while enforcing type-safety. Really, really cool. Anyone who's trying to achieve recursive mapping between types should check it out.

**Closed** 2020-03-22 18:43 UTC
Labels: Needs Investigation
