### ISSUE TITLE
Conditional member access

### ISSUE THREAD

**Issue by schungx** [Microsoft/TypeScript#5037] opened 2015-09-30 14:45 UTC
Just out of curiosity, is TypeScript going to have a conditional member access operator similar to C#'s `?.`?

Instead of writing

    foo && foo.bar && foo.bar.baz();

We can write:

    foo?.bar?.baz();

Or is something like this already possible?

**Comment by mhegazy** [comment] 2015-09-30 16:26
duplicate of #16

**Closed by mhegazy** 2015-09-30 16:26 UTC
