### ISSUE TITLE
make tslib imports shakable

### ISSUE THREAD

**Issue by tommytroylin** [microsoft/TypeScript#16999] opened 2017-07-07 09:19 UTC
**TypeScript Version:**  2.4.1
when I use ts with config like:
```json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "importHelpers": true,
    "module": "esnext",
    "noEmitHelpers": true,
    "target": "esnext"
  }
}
```
I notice that it come out with code like this
```ts
import * as tslib_1 from "tslib";
```
It is not good enough for tree-shaking by webpack.
Webpack actually bundle with the entire `tslib.es6.js`

And it's a bit heavy in my bundle 
![image](https://user-images.githubusercontent.com/3364271/27951571-ff7ec22c-6337-11e7-9fe6-1aafb032f678.png)

**Expected behavior:**

```ts
import { __decorate } from "tslib"; 
// depends on funcitons that actually used with in this file
```

**Comment by bfricka** [comment] 2017-07-12 18:10
It should be shakable, as the package.json defines `"module": "tslib.es6.js"`, and uses es6 exports rather than exporting an object. From this perspective, it seems more like a Webpack issue. Have you tried reproducing with Rollup?

**Comment by RichiCoder1** [comment] 2017-07-12 18:56
@bfricka I think the issue is that `import * as tslib_1 from "tslib";` is what is being generated by `tsc`. Webpack (currently) doesn't know how to shake this. Typescript should emit an import that only includes what that module is actually using.

**Comment by bfricka** [comment] 2017-07-12 20:13
Totally. I should have read the ticket closer.

**Comment by TheLarkInn** [comment] 2017-09-25 17:12
That is correct!!! `import *` is very hard for webpack to try and analyze. 

However something like `import foo from "tslib/lib/foo"` would be far easier to analyze.

**Comment by RikkiGibson** [comment] 2018-06-06 19:11
Is there anything that would make this unfeasible? It would really be ideal to have only the actually used helpers get bundled by tools like webpack.

**Comment by DanielRosenwasser** [comment] 2018-06-06 19:44
@TheLarkInn, just curious, where can users track better tree-shaking for namespace exports in Webpack?

**Comment by fazouane-marouane** [comment] 2018-12-12 22:31
Hi there 👋

We faced this issue this week after using generators with typescript while trying not to blow our size budget.
Below is the workaround I tried. I'll definitely go to hell for this 🔥 

## Configuration
```json5
{
  "compilerOptions": {
    // ...

    // We will need typescript not to inline implementation for __generator
    "noEmitHelpers": true
    // We will need typescript not to import 'tslib' either
    "importHelpers": false,
  }
}
```

## Module using GeneratorFunctions 
```ts
// import __generator manually
import { __generator as tslib__generator } from 'tslib'
// This is necessary so the above import won't get remove on the compiled version
export const __generator = tslib__generator

export function* helloWorld() {
  yield* "Hello, World!";
}

```

## Output

### esm + es2015

```js
import { __generator as tslib__generator } from 'tslib';
export const __generator = tslib__generator;
export function* helloWorld() {
    yield* Array.from('Hello, World!');
}
//# sourceMappingURL=hello_world.js.map
```

✅ Using any bundler that does support dead code elimination (a.k.a TreeShaking™), it will ignore `__generator` and **tslib** since it has not been imported/used.

### esm + es5
```js
import { __generator as tslib__generator } from 'tslib';
export var __generator = tslib__generator;
export function helloWorld() {
    return __generator(this, function (_a) {
        switch (_a.label) {
            case 0: return [5, __values(Array.from('Hello, World!'))];
            case 1:
                _a.sent();
                return [2];
        }
    });
}
//# sourceMappingURL=hello_world.js.map
```

✅ Any bundler will see that `__generator` is in use and will keep it while ignoring the rest of **tslib**.

I hope that this will help some of you until we have proper support for tree shaking of importHelpers.

**Comment by theKashey** [comment] 2019-06-13 00:14
Not sure how `tslib` could be tree shackable, as long as it does not marked as a `sideEffect:false`, thus should not be a subject for optimization.

**Comment by theKashey** [comment] 2019-06-13 00:37
There is a less hacky(in comparison to @fazouane-marouane solution) way to solve the problem 
1. __disable__ importHelpers, let ts inline everything
2. add [runtime-compress-loader](https://github.com/theKashey/runtime-compress-loader/) loader to your webpack configuration.
3. it will scan files for ts-helpers [signatures](https://github.com/theKashey/runtime-compress-loader/blob/master/src/signatures.js#L221), and replace them with corresponding `import {helper} from 'tslib'`, making import _tree shakable_.

**Comment by rbuckton** [comment] 2019-08-06 19:20
I'd like to clarify some of the requirements for tree-shakable imports:
- Which output module kinds should be tree shakable? WebPack seems to only support tree shaking via ES module syntax (`import`/`export`), so it seems like this should only be `--module es2015` and `--module esnext`.
- Is `import { __helper } from "tslib";` enough to be tree shakable, or do there need to be changes made to `tslib` as well?
- The `tslib` package main export introduces global declarations for each helper to be able to leverage `tslib` via `<script>` tags as well as via import. Is that a problem for tree-shakability?

**Comment by RikkiGibson** [comment] 2019-08-06 20:40
1. Agreed.
2. Yes, because tslib has an esm distribution that the bundler will find and use https://unpkg.com/tslib@1.10.0/tslib.es6.js
3. No, because the esm distribution doesn't include the global declarations (as far as I can see).

It actually looks like it should be enough to change to the `import { __helper } from 'tslib'` syntax to start tree shaking the tslib usages. You might have to add a `"sideEffects": false` but that can be good to do anyway if your esm distribution doesn't cause observable side effects when it is evaluated.

**Comment by RichiCoder1** [comment] 2019-08-08 15:27
Ditto the above. An tslib build using `ESM` style imports and exports + `"sideEffects": false` should be enough for both Webpack 4+ and Rollup.

Webpack:
https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

Rollup:
https://rollupjs.org/guide/en/#tree-shaking

^ The difference between the two being Rollup will try and determine sideEffects itself while Webpack needs a signal to trigger it's tree-shaking.

**Closed** 2019-08-09 21:02 UTC
Labels: Committed, Suggestion
