### ISSUE TITLE
Too strict type checking of function overloading.

### ISSUE THREAD

**Issue by karak** [Microsoft/TypeScript#21023] opened 2018-01-05 04:51 UTC
**TypeScript Version:**  2.6.2
**Code**

```ts
declare function f(x: string): string;
declare function f(x: string[]): string[];
// These lines do mean `f`` accepts string | string[].

let x: string;
let xs: string[] | undefined;

const ys = f(xs || x);
// Compile error:
// Argument of type 'string | string[]' is not assignable to parameter of type 'string[]'.
// Type 'string' is not assignable to type 'string[]'.
```
**Expected behavior:**
Compiled successfully.

**Actual behavior:**
Compile error.

**Comment by j-oliveras** [comment] 2018-01-05 07:42
Duplicate of #20936, #20900, #7294.

**Comment by andy-ms** [comment] 2018-01-05 15:59
@SalathielGenese That's because `xs! || x` is of type `string[]` since the left-hand side is considered always truthy.

**Closed** 2018-01-20 20:10 UTC
Labels: Duplicate
