### ISSUE TITLE
Inheritance of getter

### ISSUE THREAD

**Issue by wehrstedt** [Microsoft/TypeScript#25927] opened 2018-07-25 13:09 UTC
**TypeScript Version:**  2.7.1

**Search Terms:**
getter inheritance
getter derived
accessor inheritance

**Code**

```ts
class A {
	protected _oId: string;

	constructor(){
		this._oId = "";
	}

	public get oId(): string {
		return this._oId;
	}
}

class B extends A {
	constructor() {
		super();
	}

	public set oId(val: string) {
		this._oId = val;
	}
}
```

**Expected behavior:**
```ts
const b = new B();
b.oId = "123";
console.log(b.oId); // 123
```

If I understand https://github.com/Microsoft/TypeScript/issues/13432 right, it's a correct behaviour. But then it's not correct that getters and setters are inherited in general. I have to overwrite the getter function in my derived class to make the code work as expected. But then the benefit of inheritance is lost in that case, more concretely the inheritence makes no sense at this point because the logic of the parent class is lost. The main problem is that no exception occurres and it's hard to find the cause of this error.

**Actual behavior:**
```ts
const b = new B();
b.oId = "123";
console.log(b.oId); // undefined
```

**Playground Link:** 
[Click](https://www.typescriptlang.org/play/#src=class%20A%20%7B%0D%0A%09protected%20_oId%3A%20string%3B%0D%0A%0D%0A%09constructor()%7B%0D%0A%09%09this._oId%20%3D%20%22%22%3B%0D%0A%09%7D%0D%0A%0D%0A%09public%20get%20oId()%3A%20string%20%7B%0D%0A%09%09return%20this._oId%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aclass%20B%20extends%20A%20%7B%0D%0A%09constructor()%20%7B%0D%0A%09%09super()%3B%0D%0A%09%7D%0D%0A%0D%0A%09public%20set%20oId(val%3A%20string)%20%7B%0D%0A%09%09this._oId%20%3D%20val%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aconst%20b%20%3D%20new%20B()%3B%0D%0Ab.oId%20%3D%20%22123%22%3B%0D%0Aconsole.log(b.oId)%3B%0D%0A)

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/13432

**Comment by andy-ms** [comment] 2018-07-25 16:01
Duplicate of #11596

**Closed** 2018-08-02 21:55 UTC
Labels: Duplicate
