### ISSUE TITLE
Typescript does not follow the type signature of custom @jsx pragma. So transpiled jsx type-checks differently to non-transpiled jsx.

### ISSUE THREAD

**Issue by bluepnume** [Microsoft/TypeScript#29143] opened 2018-12-24 15:35 UTC
**TypeScript Version:**  3.2

**Search Terms:** typescript custom jsx

**Code**

The following code type-checks perfectly:

```ts
function renderElement(element : string) : HTMLElement;
function renderElement(element : () => HTMLElement) : HTMLElement;
function renderElement(element : () => string) : string;
function renderElement(element : string | (() => HTMLElement) | (() => string)) : HTMLElement | string {
    if (typeof element === 'string') {
        return document.createElement(element);
    }

    if (typeof element === 'function') {
        return element();
    }

    throw new Error(`Unsupported jsx element: ${ typeof element }`);
}
function Button() : HTMLElement {
    return renderElement('button');
}

function Message() : string {
    return 'hello world';
}

const myDiv = renderElement('div');       // Correctly type-checks as HTMLElement
const myButton = renderElement(Button);   // Correctly type-checks as HTMLElement
const myMessage = renderElement(Message); // Correctly type-checks as string
```

When I convert it to JSX, using `@jsx renderElement` as a custom jsx pragma, I start having problems. The code does not type-check the same way as it does without jsx.

```ts
/* @jsx renderElement */

function renderElement(element : string) : HTMLElement;
function renderElement(element : () => HTMLElement) : HTMLElement;
function renderElement(element : () => string) : string;
function renderElement(element : string | (() => HTMLElement) | (() => string)) : HTMLElement | string {
    if (typeof element === 'string') {
        return document.createElement(element);
    }

    if (typeof element === 'function') {
        return element();
    }

    throw new Error(`Unsupported jsx element: ${ typeof element }`);
}

function Button() : HTMLElement {
    return <button />;
}

function Message() : string {
    return 'hello world';
}

// All of these now type-check as 'any'

const myDiv = <div />;
const myButton = <Button />;
const myMessage = <Message />;
```

**Actual behavior:**

`myDiv`, `myButton`, and `myMessage` are all typed as `any`

**Expected behavior:**

`myDiv`, `myButton`, and `myMessage` should be typed as `HTMLElement`, `HTMLElement` and `string`.

If the `@jsx` factory comment is set, typescript should use that factory to determine the types of any `<intrinsic />` or `<NonInstrinsic />` jsx elements.

In this example:

- `<div />` would be transpiled to `renderElement('div')`. `renderElement(string)` is typed to always return an `HTMLElement`. As such `<div />` should always be typed as `HTMLElement`.
- `<Button />` would be transpiled to `renderElement(Button)`. `renderJSX(() => HTMLElement)` is typed to return `HTMLElement`. As such - `<Button />` should always be typed as `HTMLElement`.
- `<Message />` would be transpiled to `renderElement(Message)`. `renderJSX(() => string)` is typed to return `string`. As such - `<Message />` should always be typed as `string`.

I maintain the [jsx-pragmatic](https://github.com/krakenjs/jsx-pragmatic) module which we built and use at PayPal to render jsx directly to html and dom nodes for our Checkout experience. I'm exploring converting our entire stack from Flow to TypeScript, but this is currently blocking me from proceeding.

Note: I did try declaring the `JSX` namespace:

```
declare namespace JSX {
    export type Element = HTMLElement | string;
    export interface IntrinsicElements {
        [whatever : string] : HTMLElement
    }
}
```

But there are two problems with this:

1. It shouldn't be necessary -- the type of the `@jsx` renderer function (in this case `renderElement`) should give typescript all the information it needs to correctly type these jsx elements. This is demonstrated by the first example -- where the hand-rolled code is type-checked perfectly.
2. It forces me to type every `Element` as `HTMLElement | string` -- but that's not sound in this case. `renderElement` is an overloaded function -- the return type depends on whether it's an intrinsic element, passed a string (which can only ever return an `HTMLElement`) or a function (which could return either an `HTMLElement` or a `string`). So I lose type safety and correctness that way.

Correct me if I'm wrong -- but it seems like it would be better in this case if TypeScript type-checked the jsx in the same way Flow does; namely:

1. Transpiled the JSX down to regular javascript (or typescript) using whatever `@jsx` pragma is passed
2. **Then** type check the transpiled code

That way, the same code should type-check the same way, no matter whether it's written using JSX/TSX or JS/TS. And there should be no differences in type checking between the original two code examples I posted.

This is even more important when you bear in mind: `renderElement` (or whatever `@jsx` pragma is set) could be implemented and typed to return **any** type based on any criteria or heuristic. It's only React which specifically limits this to "null", "Fragment", "Element" and "string" return types. So in order for JSX to be truly usable outside the bounds of React, TypeScript would really need to not treat jsx as a special case, and instead just type-check the transpiled code once the jsx has been stripped out and replaced with regular function calls.

**Playground Link:** (wasn't able to figure out how to enable JSX in the playground)

**Related Issues:** n/a

**Comment by bluepnume** [comment] 2018-12-24 15:42
OK apparently just needed `export type Element = HTMLElement;`. Whoops! Closing this for now.

**Comment by bluepnume** [comment] 2018-12-24 16:37
Reopening this with some better examples. Originally I thought `export type Element = HTMLElement | string;` would solve my problem, but it doesn't seem to account for the fact that `renderElement` can be overloaded to return different types based on the input type.

**Comment by weswigham** [comment] 2018-12-25 04:37
> It shouldn't be necessary

We agree.

> It forces me to type every Element as HTMLElement | string -- but that's not sound in this case. 

Yah. Our original JSX implementation was too coupled to how react used to do things and we've been dealing with the ramifications of those choice for awhile. But in some ways, those tradeoffs are the only reasons why it _can_ work, because, for example, we don't have a typesystem operator for resolving an overloaded function.

In any case, we already actually have an issue tracking this:

Duplicate of #21699.

**Comment by bluepnume** [comment] 2018-12-25 04:41
Awesome! Thanks for linking me to the original issue. Love the work on TS btw, I'm trying out a bunch of stuff and thoroughly impressed so far. This 👌 close to being a convert!

**Closed** 2018-12-27 18:00 UTC
Labels: Duplicate
