### ISSUE TITLE
Problem with case sensitive filesystem on osX

### ISSUE THREAD

**Issue by amossam** [Microsoft/TypeScript#9109] opened 2016-06-12 20:09 UTC
**TypeScript Version:** 
```
`- > tsc -v
Version 1.8.10

`- > node -v
v5.11.0

`- > npm -v
3.8.8
```
Not shure does this belongs here.
I'm using tsc on simple node.js(angular2 quickstart) project, which uses tsc -w 
Problem is, my path to project contains uppercase letters (/opt/Development/node.js/mqtt_fe),
but when I run tsc -w I get following error:
```
Error: watch /opt/development/node.js/mqtt_fe ENOENT
```

My temporary fix is to create link from /opt/Development to /opt/development
/opt is case sensitive filesystem. I'm using osX 10.11.4

Thx

**Comment by Arnavion** [comment] 2016-06-12 23:19
Duplicate of #7154

**Closed** 2016-06-13 20:12 UTC
Labels: Duplicate
