### ISSUE TITLE
Can't pass the return value of a callback with known type to another function that should accept that kind of type.

### ISSUE THREAD

**Issue by paoloricciuti** [microsoft/TypeScript#49603] opened 2022-06-19 14:14 UTC
Given [this situation in the Playground](https://www.typescriptlang.org/play?target=7&jsx=0#code/KYDwDg9gTgLgBDAnmYcAiB5AsgVTAEwEMZgAeAFTlBIDt8BnOACXKwBkBRAG2AFtga8ALzNWnHv0EA+OCIDecANoBrYIjgBLGnFWIIAMzjkAugH4AXHAAKhWBsJcKKtcZkAfOBl4aYpG3YcnXVcAGjhCGkQZAF8AbgAoeNBIWARkVABhAGUcpB56CioQWgZRdm4+AWEy8UrpWWtbGHtHckUAIno84HbXOA8vHz8mlqdO7t6pMIiohKTwaHgkFDgASQAxAFcaAGNmiBoKACVgGE2oGjDKagFSlnKJKpkRAApgCQsjfrgaTa4uACUshk5BOZwucx2By6cHwEF4W12+20IkKNzojHutUk1SxFRxUheWjAmxglnIYX0NEsG22ew0B1ImFwBGIZHIUyMUgBQikcnicEFcAA9MLCPR6BoAObaGAAC1QYCgEBQdmAjCgp3ONGA+Dg+mVvAQCv1dOR+tlEGNqDxj0Emm0xNJAqFGAARgArYB7AB04slMqJNBJMEpNBeAIBCWiiShNBhOwliPpBwaaOKt0xYnxVQatrqMEJTrJRjDNOTyNI2VyiHyFE5HJ5fJdgtF-ulspNXVrqE14J1eoN8OtpqRDO0VIQVvlNuzdvgWgdIZbsPhFfHQZDYQjvJecm7PEsVM3pIB0Uj8Rj8TjMPeBYacJ2mxxPp2mrZOcEL3a+A0ADd2ijRJRXlDRGHoU4R3wKBCClKVCDdHhwhgGAoA0N1SVQAwoP-KcECgTZgHiOEETNDc7xxbcmz3FdoNg+DEOASxUMIkJL0jOYQLlMC4AgpYTTdQgdmUKVlW2PUoS4aA4GwmcqHnPDNXwa8kzIg43nnKjd35IU4EE4TRIgcSMggKSoEsdolPaNjzwBRIgA)  i should be able to pass the return value of the callback in cssFunction as the style value for the call to domFunction but typescript yells at me that is not assignable.

Is this a valid bug or is this expected behavior?

**Comment by jcalz** [comment] 2022-06-19 18:17
Issues like this tend to be closed as "unactionable" with the [comment](https://github.com/microsoft/TypeScript/issues/49278#issuecomment-1142372932):

> To expedite the triage process, we need everyone to follow the issue template and instructions.
> 
> When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions _completely_, follow them, and then fill in _all_ the fields in that template.
> 
> We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

If you want to avoid this fate you should probably edit the issue now with the requisite information.  And maybe remove the "Duplicate" label too.

**Comment by fatcerberus** [comment] 2022-06-19 18:19
@jcalz Looks like they used the bug template for #9998 dupes, which leaves out the usual issue template and only includes comments that the behavior is by design.  This doesn’t seem to be related to 9998, though.

**Comment by RyanCavanaugh** [comment] 2022-06-20 16:50
I checked the code anyway and this is a correct error; it's not possible to construct a valid `DOMUpdate<T>` from an object expression inside a function generic on `T` - the code has a potential bug.

**Comment by paoloricciuti** [comment] 2022-06-20 16:53
Can I ask you why it's not possible? I'm trying to understand.

**Comment by paoloricciuti** [comment] 2022-06-21 04:17
Also if I try to just pass values it correctly give me intellisense and it doesn't errors out. It also does not errors out if I don't add the second generic to IFunction.

**Closed** 2022-06-23 18:00 UTC
Labels: Duplicate
