### ISSUE TITLE
index types of strings have wrong type.

### ISSUE THREAD

**Issue by lifeiscontent** [microsoft/TypeScript#36284] opened 2020-01-18 09:48 UTC
**TypeScript Version:**  3.7.3

**Search Terms:**

**Expected behavior:**  Typescript should tell me that I need to check against possible undefined values when accessing methods on characters of strings.

**Actual behavior:**  I get runtime exceptions in my code.

**Related Issues:**

**Code**
```ts
const str = 'hello';


const char = str[5]; // char should be string | undefined

char.includes('bar'); // cannot read property `includes` of undefined
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const str = 'hello';
const char = str[5]; // char should be string | undefined
char.includes('bar'); // cannot read property `includes` of undefined

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/v2/en/play#code/MYewdgzgLgBNBOMC8MDkALApgG2yVA3AFAmiSzDoCGiKCA2gKwC6BMA9OzJTXOiAFdsAExgAjTHCjwAlmADmMAD4wBYYZgBmczMNLV4AOjnBsAjRAAUqMTVQBKNp25UwYELHiYqogA7wQX0x4KABPGAADEzMLCJgQTVV1LR1hIA)

**Comment by MartinJohns** [comment] 2020-01-18 11:59
Duplicate of #13778.

**Closed** 2020-01-20 00:31 UTC
