### ISSUE TITLE
[VS2015] JSX in extends clauses is auto-formatted oddly

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#4576] opened 2015-09-01 00:03 UTC
![jsxextendsspacing](https://cloud.githubusercontent.com/assets/2932786/9593341/00224c30-5002-11e5-8029-75e170f09aac.gif)

Generally speaking, the opening and closing tags should line up vertically, but the autoformatter seems to disagree in this case.

**Comment by vladima** [comment] 2015-09-01 02:32
looks like a dupe of #4568

**Closed** 2015-09-01 17:36 UTC
Labels: Bug
