### ISSUE TITLE
Option for strictPropertyInitialization to check even potentially undefined properties

### ISSUE THREAD

**Issue by marcomura** [Microsoft/TypeScript#26015] opened 2018-07-27 18:35 UTC
Opening new bug since the previous got closed without any explanation.

Why strictPropertyInitialization should require strictNullChecks?
```ts
class C {
    foo: number;
    bar = "hello";
    baz: boolean;
    //  ~~~
    //  Error! Property 'baz' has no initializer and is not assigned directly in the constructor.
    constructor() {
        this.foo = 42;
    }
}
```
Without stringNullChecks, I can solve the error explicitly assigning undefined to baz.

**Comment by ajafff** [comment] 2018-07-27 19:18
IIRC control flow analysis only happens when `strictNullChecks` is enabled.

In addition `strictPropertyInitialization` only checks properties that cannot contain `undefined`. As you already noted, without `strictNullChecks` everything can contain `undefined.`

**Comment by j-oliveras** [comment] 2018-07-27 19:19
Duplicate of #24716 and #23659.

**Comment by marcomura** [comment] 2018-07-27 23:53
"This PR implements a new --strictPropertyInitialization compiler option to guard against uninitialized properties in class instances".
I would prefer this to mean "if you want your field to be undefined, you have to explicitely assign undefined".

E.g., with --strictPropertyInitialization but without --strictNullChecks:

Given:
```ts
class C {
x: number | undefined;
y: number;
}
```
there should be an error in both.

Given:
```ts
class C {
x: number | undefined = undefined;
y: number = undefined;
}
```
no errors.

This is the compiler option I'm looking for, and this is the behavior I thought --strictPropertyInitialization had.

**Comment by marcomura** [comment] 2018-07-27 23:55
Should I open a proposal for a new compiler option?

**Comment by andy-ms** [comment] 2018-07-27 23:56
Let's just make that this issue.

**Comment by RyanCavanaugh** [comment] 2018-08-23 04:49
Would prefer not to add another commandline flag or induce a big breaking change.

**Closed by RyanCavanaugh** 2018-08-23 04:49 UTC
Labels: Add a Flag, Suggestion, Too Complex
