### ISSUE TITLE
Undefined not narrowed out of array pop/shift return type despite check

### ISSUE THREAD

**Issue by wbt** [microsoft/TypeScript#47846] opened 2022-02-11 14:16 UTC
# Bug Report

### 🔎 Search Terms

array pop shift undefined length

### 🕗 Version & Regression Information

Observed in 3.7.5 - 4.5.5 (latest) + nightly as of issue filing. 
Prior versions claim an error but aren't as specific; there's no reason to believe this is a regression.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwDYEMDOa4FkCeBhVDOAbzjICgyyYcxg0EoBLMGPCMHAURBQFswSYAAoAlAC44AQShQUOADxoYzAHYBzAHwlKVPQgirlcZWvVoAKhHac4AXjgBtAOQpnAGjjOARh68JnAF0Abl09MiF4KHoAVyQYSRk5RVMmDW0HRxCw8IB3AAsmIWFUjUtrDhwAOiENGHzNAAZRHXC2uGi0OJgqsBi0fJKVNPMrG2rIMDFRYLIAejm4LlloSWdS9TgAHzgY1QATYAAzNOB95zgmTFUIeHQ0JnVVFG8hOBgIODAUOT5gGGAUDgECO71owC8G2cOT0AF8YVRojAYlBVB1YvFQnCqORYUA)

### 💻 Code

```ts
export class MyClass {   
    typescriptCopyExample(): Array<string> {
        const stringsToCopy = ['a', 'b', 'c'];
        let result: Array<string> = [];
        while(stringsToCopy.length>0) {
            result.push(stringsToCopy.pop()); // Error: 'string | undefined' is not assignable to parameter of type 'string'
        }
        return result;
    }   
}
```

### 🙁 Actual behavior

An error on the flagged line that the result of `pop()` could be undefined, which is what happens when the array is empty, even inside a conditional check that this is not the case.

### 🙂 Expected behavior

Inside the conditional check, `stringsToCopy` is narrowed to an array of length > 0. The return type of `pop()` and `shift()` operations are not flagged as possibly `undefined`.

**Comment by MartinJohns** [comment] 2022-02-11 14:32
Duplicate of #30406.

**Closed** 2022-02-13 18:00 UTC
Labels: Duplicate
