### ISSUE TITLE
Feature request : use of namespaces and module togeher

### ISSUE THREAD

**Issue by xmehaut** [Microsoft/TypeScript#5312] opened 2015-10-18 08:15 UTC
I would suggest to be able to use namespaces with modules.

dummy1.ts file :
```
namespace MyLib {
   export class Dummy1{
       constructor(public name:string, public surname:string) {};
   }
}
```
dummy2.ts file :
```
namespace MyLib {
   export class Dummy2{
       constructor(public name:string, public surname:string) {};
   }
}
```

main.ts file :
```
import {Dummy1, Dummy2} from 'mylib'
function main() {
   let dum1= new Dummy1("sds", "sdsq");
   let dum2= new Dummy2("sf", "sdsfd");
}
```
By doing this, we could directly call exported data from common namespace by just calling the namespace in the import statement.

Furthermore, the code generator could generate only one mylib.js file containing the Dummy1 and Dummy2 classes with system.js convention.

**Comment by DanielRosenwasser** [comment] 2015-10-18 23:18
I believe this is a duplicate of #2956.

**Closed by DanielRosenwasser** 2015-10-18 23:18 UTC

**Comment by xmehaut** [comment] 2015-10-19 05:51
Thx for the answer 
If currying or partial définition is not planned, maybe the following syntactic ability could be easily implemented, ie if the last argument of a function is a closure , be able to extra ct it from the arguments to be able to write such a thing 
´´´
aList.map (a)=>{ somethingtodo}
´´´
Or even 
´´´
div(className=´toto') {
    Somethingtodo
}
´´´
  

Envoyé de mon iPhone
