### ISSUE TITLE
TypeError: Cannot read property 'charCount' of undefined in `charOffsetToLineInfo` during `decorateSpan`

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#20799] opened 2017-12-19 22:52 UTC
tsserver version: 2.6.1
hitting sessions: 2083
stack:
```
TypeError: Cannot read property 'charCount' of undefined
    at LineNode.charOffsetToLineInfo (tsserver.js:87329:79)
    at LineIndex.positionToLineOffset (tsserver.js:87078:36)
    at ScriptVersionCache.positionToLineOffset (tsserver.js:87001:50)
    at TextStorage.positionToLineOffset (tsserver.js:81573:33)
    at ScriptInfo.positionToLineOffset (tsserver.js:81787:41)
    at IOSession.Session.decorateSpan (tsserver.js:86370:39)
    at tsserver.js:86364:74
    at Array.map (native)
    at IOSession.Session.decorateNavigationTree (tsserver.js:86364:39)
    at IOSession.Session.getNavigationTree (tsserver.js:86380:32)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:85397:61)
    at tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId (tsserver.js:86660:28)
    at IOSession.Session.executeCommand (tsserver.js:86669:33)
    at IOSession.Session.onMessage (tsserver.js:86689:35)
    at Interface.<anonymous> (tsserver.js:87881:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mhegazy** [comment] 2018-01-20 20:39
The `Source: Telemetry` have limited information. we only have the call stack from the crash report. We need to either mitigate the crash, or add additional asserts to get more information in future crash reports.

**Comment by andy-ms** [comment] 2018-03-12 20:58
Duplicate of #21818

**Closed by andy-ms** 2018-03-12 20:58 UTC
Labels: Bug, Source: Telemetry
