### ISSUE TITLE
tsconfig.json extending from base tsconfig.json cannot override "declaration" to false

### ISSUE THREAD

**Issue by benny-medflyt** [Microsoft/TypeScript#17357] opened 2017-07-22 10:17 UTC
**TypeScript Version:**  2.4.1

If we have a "base" tsconfig.json file:

```json
{
    "compilerOptions": {
        "declaration": true,
        "declarationDir": "./dist/types"
    }
}
```

And we try to create another tsconfig.json that extends it:

```json
{
    "extends": "../base/tsconfig.json",
    "compilerOptions": {
        "declaration": false
    }
}
```

Then it doesn't work. We get error:

    error TS5052: Option 'declarationDir' cannot be specified without specifying option 'declaration'.

There doesn't appear to be a way to "unset" the "declarationDir" setting. (Tried null, empty string, undefined)

**Comment by mhegazy** [comment] 2017-08-23 18:27
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/16838

**Comment by mhegazy** [comment] 2017-09-06 19:01
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-06 19:01 UTC
Labels: Duplicate
