### ISSUE TITLE
Function that returns never doesn't work when placed inside an object

### ISSUE THREAD

**Issue by LeoAso** [microsoft/TypeScript#55154] opened 2023-07-25 22:02 UTC
# Bug Report

### 🔎 Search Terms

never, throw, error, unreachable

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about functions returning never

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.6#code/GYVwdgxgLglg9mABABwIZhhAFASgFyJgCmAbkQE6IDeAUIolABblwDuhR7AouS+VgHIA8o0JwAhAJwBuGgF8aNIgA9kcclEQQEAZ00U+OxAF5qdFOky4CxMpSoNmbDt17rBIsZJmI5AGnMAekDEVAAbHTgGchgiABNHIh0iIJC0DAgCaw47EwA+akcWdmJXPg9RMAkpaV8A+mCLDICFRvDI6NiEpiSU4LlQo20wPVl+xB1UWB1gWKMAJSJtcjiAHj0YsABzP0QsXHycihw82RpQSFgERABbVABPACMiAHEiKABlKE2t7I2YbaIAA+hBAYTCZno5HeIHISAARABJAQ3UITb4ArbieGyBTncDQeBIKBJKAHWj0YZ6NGmO5PV7vL4-XCyegwYB7cSoHCIAzqHQAOnSVhkqUQ7M53KaItqjR6vLclC2cCSoVYD3FHPucBAiBAyUcMCMAL0RFQcUUlN0mkeBH+gNMqFZWl0cDCRAFYTgv0eooUQA)

### 💻 Code

```ts
function panic(): never {
  throw new Error('Oh no!');
}

export const errors = {
  panic(): never { throw new Error('Oh no!'); },
  // also tried these
  // panic: (): never => { throw new Error('Oh no!'); },
  // panic,
}
// also tried these
//} as const;
//} satisfies Record<string, (() => never)>;

function maybeGetString(): string | null {
  return "I'm a string!";
}

function test() {
  const a = maybeGetString();
  if (!a) errors.panic();
  // if (!a) panic(); // the error goes away if you use this instead

  const b: string = a;
  console.log(b);
}
```

### 🙁 Actual behavior

A function returning never is being treated differently when it is called from inside an object i.e. `panic` vs `errors.panic`. This is despite the fact that they both resolve to the same type `() => never`.

### 🙂 Expected behavior

The function should work the same way regardless of how it is called. It should work the same as a `throw` statement, so that in the code snippet above, the type of `a` is narrowed from `string | never` to `string`, and there should be no error on the statement `const b: string = a`

**Comment by MartinJohns** [comment] 2023-07-25 22:06
Duplicate of #36753 and many many others.

**Comment by nmain** [comment] 2023-07-26 11:38
As detailed above, you'd have to remove the inference on `errors` to fix this.

```typescript
export const errors: { panic: () => never } = {
  panic(): never { throw new Error('Oh no!'); },
}
```

**Closed** 2023-07-28 12:27 UTC
Labels: Duplicate
