### ISSUE TITLE
Error: Debug Failure. Expected 2684 <= 2533 in `createFileDiagnostic` during `getApplicableRefactors`

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#20796] opened 2017-12-19 22:44 UTC
Might be a duplicate, but can't find the other "off-by-many" issue, so reporting here nonetheless

tsserver version: 2.6.1
hitting sessions: 2788
stack:
```
Error: Debug Failure. Expected 2684 <= 2533
    at Object.assertLessThanOrEqual (tsserver.js:3185:17)
    at Object.createFileDiagnostic (tsserver.js:2293:19)
    at getRangeToExtract (tsserver.js:77623:42)
    at Object.getAvailableActions (tsserver.js:77509:38)
    at tsserver.js:75017:128
    at Object.flatMapIter (tsserver.js:1570:23)
    at Object.getApplicableRefactors (tsserver.js:75016:23)
    at Object.getApplicableRefactors (tsserver.js:80232:32)
    at IOSession.Session.getApplicableRefactors (tsserver.js:86474:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:85436:61)
    at tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId (tsserver.js:86660:28)
    at IOSession.Session.executeCommand (tsserver.js:86669:33)
    at IOSession.Session.onMessage (tsserver.js:86689:35)
    at Interface.<anonymous> (tsserver.js:87881:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mhegazy** [comment] 2018-01-20 20:37
The `Source: Telemetry` have limited information. we only have the call stack from the crash report. We need to either mitigate the crash, or add additional asserts to get more information in future crash reports.

**Comment by amcasey** [comment] 2018-01-23 02:28
Trying to report inability to extract an empty range but specifying a position beyond EOF.

**Comment by amcasey** [comment] 2018-01-23 21:47
The position is determined many stack frames earlier, so we may have no better option than adding upstream asserts.

**Comment by amcasey** [comment] 2018-01-23 21:50
@aozgaa do we know which editor(s) this is from?

**Comment by aozgaa** [comment] 2018-01-25 05:00
All the source: Telemetry bugs are from vscode (as of today).

**Comment by amcasey** [comment] 2018-01-26 01:40
This seems very similar to https://github.com/Microsoft/TypeScript/issues/20798 - it looks like a refactoring is being requested at an invalid position.  FYI @andy-ms

**Comment by DanielRosenwasser** [comment] 2018-01-30 00:17
Repro: The following anonymous `.js` buffer in VS Code:

```js
import * as frorb from "gorb";
frorb./*CURSOR HERE*/
```

```
[Error  - 4:15:11 PM] 'getApplicableRefactors' request failed with error.
Error processing request. Debug Failure. Expected 38 <= 35
Error: Debug Failure. Expected 38 <= 35
    at Object.assertLessThanOrEqual (C:\Users\Daniel\TypeScript2\built\local\tsserver.js:4070:17)
    at Object.createFileDiagnostic (C:\Users\Daniel\TypeScript2\built\local\tsserver.js:2905:19)
    at getRangeToExtract (C:\Users\Daniel\TypeScript2\built\local\tsserver.js:97469:42)
    at Object.getAvailableActions (C:\Users\Daniel\TypeScript2\built\local\tsserver.js:97332:38)
    at C:\Users\Daniel\TypeScript2\built\local\tsserver.js:93628:128
    at getIterator (C:\Users\Daniel\TypeScript2\built\local\tsserver.js:1972:23)
    at Object.next (C:\Users\Daniel\TypeScript2\built\local\tsserver.js:1967:35)
    at Object.arrayFrom (C:\Users\Daniel\TypeScript2\built\local\tsserver.js:2623:32)
    at Object.getApplicableRefactors (C:\Users\Daniel\TypeScript2\built\local\tsserver.js:93627:23)
    at Object.getApplicableRefactors (C:\Users\Daniel\TypeScript2\built\local\tsserver.js:100752:32)
    at IOSession.Session.getApplicableRefactors (C:\Users\Daniel\TypeScript2\built\local\tsserver.js:108109:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Users\Daniel\TypeScript2\built\local\tsserver.js:107044:61)
    at C:\Users\Daniel\TypeScript2\built\local\tsserver.js:108313:88
    at IOSession.Session.executeWithRequestId (C:\Users\Daniel\TypeScript2\built\local\tsserver.js:108304:28)
    at IOSession.Session.executeCommand (C:\Users\Daniel\TypeScript2\built\local\tsserver.js:108313:33)
    at IOSession.Session.onMessage (C:\Users\Daniel\TypeScript2\built\local\tsserver.js:108333:35)
    at Interface.<anonymous> (C:\Users\Daniel\TypeScript2\built\local\tsserver.js:109594:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by amcasey** [comment] 2018-01-30 22:28
@DanielRosenwasser, do you have a consistent repro?  I haven't been able to trigger it yet.

**Comment by amcasey** [comment] 2018-01-30 22:39
Up to and including the last `.`, that file appears to be 38 characters long so it's `file.text.length === 35` that seems suspicious.

**Comment by mhegazy** [comment] 2018-03-10 00:38
We believe this is fixed now, since we can not reproduce the issue any longer. but this is not definitive. closing for now, and waiting for more telemetry data.

**Closed by mhegazy** 2018-03-10 00:38 UTC
Labels: Bug, Source: Telemetry
