### ISSUE TITLE
Array.IsArray incorrect type guard

### ISSUE THREAD

**Issue by JakeCoxon** [microsoft/TypeScript#44745] opened 2021-06-25 17:16 UTC
# Bug Report

### 🔎 Search Terms

Array isArray unknown any type guard

### 🕗 Version & Regression Information

3.3.3 - 4.3.4
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type guard

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.9.7#code/MYewdgzgLgBAHgLhgVzAazCA7mGBeGAbQHIBDCAE3IuIF0AoegSwDMYAKAQQCdvSBPAHRMIPPv3ZwAlFJgBvRjCXxCABlowAtDACMAJgDM+g-QC+9IA)

### 💻 Code

```
const x: unknown = ['asdasd']

if (Array.isArray(x)) {
    x[0] - 123123
}
```

### 🙁 Actual behavior

It passes type checking

### 🙂 Expected behavior

I would expect it to fail because although x is an array, x[0] should still be unknown. I'd expect to be forced to check the type of the items

**Comment by MartinJohns** [comment] 2021-06-25 17:21
Duplicate of #44703 / #41808. Search terms: `Array.isArray in:title`

**Comment by JakeCoxon** [comment] 2021-06-25 17:25
^ I saw that issue but it is very vague and I couldn't work out if it is the same problem

**Closed** 2021-06-27 18:00 UTC
Labels: Duplicate
