### ISSUE TITLE
optional property in type union leads to incorrect type inference

### ISSUE THREAD

**Issue by maifeeulasad** [microsoft/TypeScript#55615] opened 2023-09-03 10:31 UTC
### 🔎 Search Terms

"optional union", "union optional"

### 🕗 Version & Regression Information

- This changed between versions n/a and n/a
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `optional union` and `union optional`
- I was unable to test this on prior versions because i'm pretty lazy, (but I tested on `5.2.2`, `5.1.6`, `5.0.4`, `4.9.5`, `4.8.4`, `4.7.4`, `4.6.4`, `4.5.5`, `4.4.4`, `4.3.5`, `4.2.3`, `4.1.5`, `4.0.5`, `3.9.7`, `3.8.3`, `3.7.5`, `3.6.3`, `3.5.1`, `3.3.3`, `Nightly=v5.3.0-dev.20230903`)

### 💻 Code

```ts
interface I{
    a?: object[]
    b?: object[]
}

const test = ({a,b}: I) => {
    console.log(a)
    console.log(b)
    console.log(a || b)
    console.log((a || b).map((c)=>c)) // <-- this is wrong as expected
}

interface I1{
    a: object[]
    b?: object[]
}

interface I2{
    a?: object[]
    b: object[]
}

const testAnother = ({a,b}: I1 | I2) => {
    console.log(a)
    console.log(b)
    console.log(a || b)
    console.log((a || b).map((c)=>c)) // this should be correct, but it's giving me error
}

const testSimple = ({a,b}: I1) => {
    console.log(a)
    console.log(b)
    console.log(a || b)
    console.log((a || b).map((c)=>c)) // this is correct, and understand-able
}
```

### 🙁 Actual behavior

TypeScript infers that both `a` and `b` can be undefined, and hence throws an error on the `(a || b).map()` invocation.

### 🙂 Expected behavior

Logically `a || b` is can never be undefined. 

Since the union type `I1 | I2` guarantees that at least one of the properties (`a` or `b`) will always be present, TypeScript should infer that `a || b` always returns an array of objects, and thus should allow `(a || b).map()` without any error.

### Additional information about the issue

**Feel free to assign it to me**

**Comment by MartinJohns** [comment] 2023-09-03 10:41
Duplicate of #30869. See also this comment: https://github.com/microsoft/TypeScript/issues/54252#issuecomment-1547984904

**Comment by fatcerberus** [comment] 2023-09-03 11:22
> I was unable to test this on prior versions because i'm pretty lazy, (but I tested on 5.2.2, 5.1.6, 5.0.4, 4.9.5, 4.8.4, 4.7.4, 4.6.4, 4.5.5, 4.4.4, 4.3.5, 4.2.3, 4.1.5, 4.0.5, 3.9.7, 3.8.3, 3.7.5, 3.6.3, 3.5.1, 3.3.3, Nightly=v5.3.0-dev.20230903)

That… doesn’t sound very lazy at all. :smile:
[And I don’t think anyone will fault you for not testing further back than 3.3.3.](https://github.com/microsoft/TypeScript/issues/49186#issuecomment-1133055891)

**Closed** 2023-09-08 01:24 UTC
Labels: Duplicate
