### ISSUE TITLE
No compiler error when type is defined inside a function

### ISSUE THREAD

**Issue by temurih** [microsoft/TypeScript#47556] opened 2022-01-22 05:34 UTC
# Bug Report

### 🔎 Search Terms

I don't know how to search for it, these are a few things I tried. I apologize if its a duplicate, or if I am misunderstanding how the types work.

- No compiler error when type is defined inside a function
- No compiler error when function type is defined

### 🕗 Version & Regression Information

`v4.5.4` possibly others too

### ⏯ Playground Link

[Playground Link - Check Line 10](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&allowUnreachableCode=true&allowUnusedLabels=true&noStrictGenericChecks=true&noUnusedLocals=true&noUnusedParameters=true&removeComments=true&useUnknownInCatchVariables=true&exactOptionalPropertyTypes=true&noFallthroughCasesInSwitch=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true&noImplicitUseStrict=true&suppressExcessPropertyErrors=true&suppressImplicitAnyIndexErrors=true&keyofStringsOnly=true#code/C4TwDgpgBAyg9gWwgFXNAvFARAGwJYDOwEAdllAD7ZwBOAcnMFgNwCwAUBwMZwlFQAzOHCiYAFADcAhjgCuEAFyxEKNAEpRAPigBvKDz5wcEAHQ44Ac0kz5GgL5tO7PCWI0BUrtACCJRgAsIGlRIXQ4oKCk-YECaADUbCAB+JXgkEIgOOw5uXn5zGggEJWs5RShfAKCMjXRtCTg8ABNRKDEdcMjo2ISy1qwmqQQsABooAHpxqBjCKAJ-OFkcFoAjaCl9RDA8YxooIJpaaeEkgEJOyen-QgBJAm8AYS2doIBRGkOaJSIaFwss2raDrsCJRKrxRL9KIgGYWMiOCIGAhGUzmKxgmJBXq2C5TIRwMQYnqQihUADk+CIpDJakc2Scl2Q1wIUAA7rQANYEc7sJHAKAFIoAdU5BBK0jKSkqmOC6i0UAazVa7U6RKxkMwAyGoyyUu61TldTCIK64OxGGw0Nh8M6SJRZkshP1ELKalxgmETrNJPJlOIJBpdI4QA)

### 💻 Code

```ts
type SomeType = "listen" | "orNot";

const foo = (value: SomeType) => { console.log(value) };

interface AnotherType {
  anotherValue?: SomeType
}

const lorem: (value: AnotherType) => void = ({
  anotherValue = "dam", // this should be a compiler error too?!
  // thisIsACompilerError: string
}) => {
  anotherValue = "anythign";
  console.log(anotherValue)
  // foo(anotherValue || 'listen');
}
```

### 🙁 Actual behavior

It is not a compiler error.

### 🙂 Expected behavior

It should be a compiler error, as the following works fine,

```ts
const lorem: (value: AnotherType) => void = ({
  anotherValue = "dam",
  // thisIsACompilerError: string
}: AnotherType) => {
  anotherValue = "anythign";
  console.log(anotherValue);
}
```

**Comment by fatcerberus** [comment] 2022-01-22 09:07
From the point of view of a user of `lorem`, there’s nothing wrong with the function you’ve assigned to it.  The *implementation* has to deal with the fact that `value.anotherValue` might be `"dam"`, but that doesn’t affect the *caller* of the function and so the assignment is legal.  Function parameters are contravariant: You can give me a function that accepts a wider type than I asked for.

Adding the required string property `thisIsACompilerError` *does* produce an error because nothing the caller provides is going to have that property.

**Comment by Josh-Cena** [comment] 2022-01-22 13:39
Took me a while to understand what @fatcerberus is saying 😄 Your signature of `: (value: AnotherType) => void` is only visible to the caller, but not to the implementation. TypeScript is fine with your implementation being something wider than `AnotherType`, so even if you widen it to `(value: {anotherValue: string}) => void` in the implementation, there won't be an error.

You can see your code as this:

```ts
declare function foo(value: {anotherValue: string}): void;
const lorem: (value: AnotherType) => void = foo;
```

Which apparently is fine.

**Comment by fatcerberus** [comment] 2022-01-22 15:56
@Josh-Cena In this particular case it's actually a bit closer to writing this:
```ts
const lorem: (value: AnotherType) => void = (value: AnotherType) => {
  let anotherValue = value.anotherValue ?? "dam";
  anotherValue = "anythign";
  console.log(anotherValue)
  // foo(anotherValue || 'listen');
}
```
which TypeScript has no reason to reject.

**Comment by temurih** [comment] 2022-01-24 21:30
@Josh-Cena @fatcerberus Wait, what? I don't understand, what is the difference between the two? In both cases, we are saying that I will take `AnotherType` as a parameter. Whether you write one way or the other, I thought that both are saying the same thing.

```
const lorem: (value: AnotherType) => void = ({ anotherValue = "dam" }) => {};
```
OR
```
const lorem = ({ anotherValue = "dam" }: AnotherType) => {};
```

And what would be the case where you want the implementation to be wider than the caller signature? If it is wider, then why not define it in the signature? I mean why would you implement for wider cases, but you will only allow a subset? Then why not just say the subset is allowed, it does not make sense :(

**Comment by fatcerberus** [comment] 2022-01-24 22:46
Without getting into technical details: `lorem` itself is typed as a function which accepts an `AnotherType` value.  The actual function you’ve assigned to it can be passed an `AnotherType` without violating the type system; the *implementation* will see `"dam"` instead of `undefined` in case the property doesn’t exist, but the caller has no reason to care about that.

See my comment above:
https://github.com/microsoft/TypeScript/issues/47556#issuecomment-1019297185

**Closed** 2022-01-27 00:00 UTC
Labels: Question

**Comment by temurih** [comment] 2022-01-27 07:14
@fatcerberus I think you missed the bullet there, I don't want the developers that are using my interface `AnotherType` to assign `dam`. I know I can do `alue.anotherValue ?? "dam"` or `alue.anotherValue || "dam"`, but this is exactly what I am trying to avoid. Do you understand the question now?

**Comment by fatcerberus** [comment] 2022-01-27 07:35
I understand what you want, what I'm trying to tell you is that the reason you don't get an error is the same reason you don't get an error here:

```ts
// why is this legal?
let fooey: (x: "foo" | "bar") => void = (x: string) => console.log(x);

// because both "foo" and "bar" are valid inputs for (x: string):
fooey("foo");  // no problem
fooey("bar");  // ditto
```

By omitting the type annotation on your destructured parameter, TS *infers* `(value: { anotherValue: string }) => void` for the type of the arrow function expression, which is assignable to `(value: AnotherType) => void` for the same reason the above example is legal.  To prevent this inference, you have to annotate the destructure like in your example under Expected Behavior.

Function assignability is based on what the *caller* can do with the function.  Since you seem to also want to restrict the *implementation*, you need to be explicit.

> I don't want the developers that are using my interface AnotherType to assign "dam".

This is already the case even in your "broken" code - you'll find that it's not legal to call `lorem({ anotherValue: "dam" })` (or any other string for that matter).  The destructuring and defaulting you've done is an implementation detail from the caller's PoV.  That's why I posted the example using `?? "dam"` - because the semantics are *exactly the same*.

**Comment by fatcerberus** [comment] 2022-01-27 07:51
Splitting up the construction of the arrow function and its subsequent assignment to `lorem` might help clarify what's going on:
```ts
type SomeType = "listen" | "orNot";

const foo = (value: SomeType) => { console.log(value) };

interface AnotherType {
  anotherValue?: SomeType
}

const loremFun = ({
//     ^? const loremFun: ({ anotherValue }: { anotherValue?: string | undefined }) => void
  anotherValue = "dam",
  // thisIsACompilerError: string
}) => {
  anotherValue = "anythign";
  console.log(anotherValue)
  // foo(anotherValue || 'listen');
};

const lorem: (value: AnotherType) => void = loremFun;
```

Notice that the default string `"dam"` is completely invisible from outside the function and the result is a function type that takes `string | undefined`, which in turn is compatible with the type of `lorem` for the aforementioned reasons.

**Comment by Josh-Cena** [comment] 2022-01-27 07:54
If you truly want your downstream developers to have a strict type, you should make them put the type on their parameters, not on the function. i.e. `const lorem = ({ anotherValue = "dam" }: AnotherType) => {};`. There's actually a semantic difference in this.
