### ISSUE TITLE
Inconsistent type inference when changing the order of type declarations (5.0 regression)

### ISSUE THREAD

**Issue by SimpleCreations** [microsoft/TypeScript#55666] opened 2023-09-07 13:30 UTC
### 🔎 Search Terms

N/A — not sure which part of the playground code causes the issue

### 🕗 Version & Regression Information

* No bug on 4.9.5
* The bug can be observed starting from 5.0.4

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBA4gTgQzACwIoBkByB7AdgZQFcAjfCAGwgGNgFjKoBeAKCigB8oBnYOAS1wBzVhygBBOIhAAeHvyGjchcuVGFcAEwgAzARA0A+EZyUrjUdVt259AbmahIsRCgxFSFarXrQWbTvBIaOgA8sQAVl7mElLSga6hEV6Kyqqcljp6hvaO0PHBAGoI5IS+zkEYOAQkZJQ0dAwBLsHutV4NEPYA9F1QEFzkAsAAtBp8XB3DNgAeI4M2UAACuVxU-GAj-fPAXVR4XOPAELgjAlrT+sPYSTTDPCCUADTL4P1rfBvDW0O7+4fHI1yo0yuD4wD4+wcr3KCTCkRoTCgAG8oABtADWEBAAC5uLwBIIALq4-IYIolaAAX3szD2uB4UAAKgAlMSYfAAMRCzIAsgBRZmI-AgAC2xGw5AAFAByFlsznc-nM6UAShpQwgcG0CCo0FannqPg5fAoGi4bRoENwIQ2Vq4yJEqLl7K5vIFhIA-LjGYh6dpsHARZrmTpNcdddJrvDgI8YcE4V4DPZKcwoU5jabzQbwXgbTn6dJGQZEYy+rNjma424atmOiIPVB9XVvJQM+QzRb83m7SJcVVMKkOtJ1OjcNgAO64JOprRUcgIODQOkM50Kt3MgD6zL5HIFfMwAGE+RvGQBNAAKfNx6j4AEdStxReLyPZZ-PF1Bl8AmayXYqBVuO57oex6rq6SrXqC97QFwT4SvYGpajq0A+ggfoBkGcAhtoYa4BGIiMqh6GBpqZZHJo9pRl4jwEYy0IQOWFFVok0Y0cWSKOmB-6btuu7biBJ4XnyxJMnRkD2GwTq-muSqAXx+5Hie0nge63pEVw-okXAyaprkUAAKq4OOLhNu0PiFmRFb2qS6CmYalDFowTKWUxMQIDIIgCDhcBQAUzBGGwDb9oO5kFAFUDeuqJyatqupQAmNAAOpgsg6maZh3Z4NItG+hpGGkQx5GVlRNA0WwhH0YxlY2QlMb+Q6klceuIlpflWGhoueEQIWrVabGFWQNOKZptAbYaOeCDAMgtUWYVVnMbVjkNWiADSUACFAmIgNg2hMp63qoithIuZWXmkX5bCBb5J3Wc01YeM2daXZdDZjRNU0zYZxlIHZLbdWF4XPX2eADioQ4jmOk6AxFUA2AAbpqyZQAAZFAY1Zs2VqZQWRY0npY3uO9yDkqU0gFP1hOTcgS0FDdzFVL9T1QA2F0w7Tc1MTZjM+PWTKU1NdNvVTn1GSZNaPaFBjQyzdM1TcwAiM9r0mu2RMk91X1iw9ZmUGTBgUyQRPQ2w3r88gdO1clU29RltpZYrz2XWdPmEbl6WamVjvPZrP3izr-3G5dgcNq7aF5VpDsmxYuCjhOuAO7i8Oar2sMQAj2m6dCQtTer2XlbLd0sdRBFE4LKvjcL8uFvr9VORxklrRtW07UyRMiWtHOVs3u2Mg7yummbueModhL9UTI-Q4naeI8wlIYliLeMm3UVHEhcUctg2CrzbpH11AuimpBseTjpI1QHyJxwCAiJ77BXDA7goPzuZENx0NePQqgpRXzfIj+lvmoDwSkxngL0aNN6ryASoLwVpkwfycHycscBcDFHQAIdEiIL68GvqjPe8xMQaA5HAbAIowEbwAXAKBIDcBwMzumCBpEnJYJ-rgv+DC4BoJjlweA2BCBgCoTA0BuJyGr04eibhxC+ECMtHgWhZ8RGAOAYI3Av82BgggCKe+4CKGokJHI-G7CxESN4WATBl8cHLUEJIsAYiwGINXig8gYjRDBTBi-GOkMpz6KzoY9BxipFKJkSouunkjgimEb4rhPC+HeKcKXEJbB-6QMCfmXEe81FhK0eky6Ul5QqWZC1N2bVsK4QjAouAO84CxnKdOZ61IRD1PqWfAAkmExE2dibFFJl-TUIBYxGxpG+BcS59jfmmLiVpGj7BfigDibR28ilaTUJoEE+hETTHsEAA

### 💻 Code

Apologies if the example is too long. I did my best to reduce it as much as possible, having encountered this bug in production.

```ts repro
type GraphQLNonSubSelectable =
  | string
  | Array<string | null | undefined>
  | null
  | undefined;
type GraphQLSubSelectable =
  | GraphQLObject
  | Array<GraphQLObject | null | undefined>;
type GraphQLValue = GraphQLNonSubSelectable | GraphQLSubSelectable;
type GraphQLObject = { [key: string]: GraphQLValue };

const TRANSFORMER = Symbol('TRANSFORMER');

interface SubSelectableFieldsSelectionOptions {
  [TRANSFORMER]?: TransformerReference<object, GraphQLObject>;
}

type FieldsSelectionOptions<T> = T extends GraphQLSubSelectable
  ? SubSelectableFieldsSelectionOptions
  : NonNullable<unknown>;

declare const TRANSFORMER_REFERENCE_TYPE: unique symbol;
declare const TRANSFORMER_REFERENCE_TRANSFORMER: unique symbol;
interface TransformerReference<
  TTransformer extends object,
  TType extends GraphQLObject,
> {
  [TRANSFORMER_REFERENCE_TYPE]: TType;
  [TRANSFORMER_REFERENCE_TRANSFORMER]: TTransformer;
}

type UnwrapSubSelectable<T extends GraphQLSubSelectable> = T extends Array<
  infer V
>
  ? NonNullable<V>
  : T;

interface ObjectWithTransformerOption<
  TTransformer extends object,
  TType extends GraphQLObject,
> {
  [TRANSFORMER]: TransformerReference<TTransformer, TType>;
}

type FieldPathObject<T extends GraphQLObject> = {
  [K in keyof T]?: T[K] extends infer V
    ? V extends GraphQLSubSelectable
      ? FieldPathObject<UnwrapSubSelectable<V>>
      : NonNullable<unknown>
    : never;
} & FieldsSelectionOptions<T>;

type FieldSubPathValue<V, TSubPath> = V extends GraphQLNonSubSelectable
  ? V
  : V extends GraphQLSubSelectable
  ? TSubPath extends FieldPathObject<UnwrapSubSelectable<V>>
    ? V extends GraphQLObject
      ? FieldPathValue<UnwrapSubSelectable<V>, TSubPath>
      : TSubPath extends ObjectWithTransformerOption<
          infer TTransformer,
          UnwrapSubSelectable<V>
        >
      ? TTransformer
      : unknown
    : never
  : never;

type FieldPathValue<
  T extends GraphQLObject,
  TPath extends FieldPathObject<T>,
> = {
  [K in keyof TPath]: K extends keyof T
    ? FieldSubPathValue<T[K], TPath[K]>
    : never;
}[keyof TPath];

interface FooterTransformer {
  field: unknown;
}

type Entry = {
  sys: NonNullable<unknown>;
};

type Query = {
  footerCollection?: FooterCollection;
};

type ExternalLink = Entry & {
  linkedFrom?: FooterCollection;
};

type Footer = Entry & {
  footerLinksGroupCollection?: FooterLinksGroupCollection;
};

type FooterCollection = {
  items: Footer[];
};

type FooterLinksGroup = Entry & {
  groupLink?: ExternalLink | NonNullable<unknown>;
};

type FooterLinksGroupCollection = {
  item: FooterLinksGroup;
};

type Path = {
  footerCollection: {
    items: {
      [TRANSFORMER]: TransformerReference<FooterTransformer, Footer>;
    };
  };
};

type Item = FieldPathValue<Query, Path>;

declare const x: Item;
const y: FooterTransformer | undefined = x;
```

### 🙁 Actual behavior

1. Observe that the example gives the following error:
```
TS2322: Type 'Footer[] | undefined' is not assignable to type 'FooterTransformer | undefined'.
  Property 'field' is missing in type 'Footer[]' but required in type 'FooterTransformer'.

121 const y: FooterTransformer | undefined = x;
          ~
```

2. Put `type Footer` between `type Query` and `type ExternalLink`. [Updated example](https://www.typescriptlang.org/play?#code/C4TwDgpgBA4gTgQzACwIoBkByB7AdgZQFcAjfCAGwgGNgFjKoBeAKCigB8oBnYOAS1wBzVhygBBOIhAAeHvyGjchcuVGFcAEwgAzARA0A+EZyUrjUdVt259AbmahIsRCgxFSFarXrQWbTvBIaOgA8sQAVl7mElLSga6hEV6Kyqqcljp6hvaO0PHBAGoI5IS+zkEYOAQkZJQ0dAwBLsHutV4NEDngec0YYZE0TFAA3lAA2gDWECAAXNy8AoIAunP5GEUl0AC+9sxUeDxQACoASmKY+ABiIScAsgCiJ0P4IAC2xNjkABQA5KfnVxuDxOPwAlLsBMAIHBtAgqNBWp56j5LnwKBouG0aHw8CEwMAcbguCMRGN-hdrndHksAPxzI6IInabBwV7Qk46aEQXDw6TYJI0AA05QS-S8BnsW2YDm6UFR6MxSIJuPxhK40iOBiGRygEAAHlDNMS1uhEXVvJQRDSoGb2ii0eQMVjlbg8S6uCI5lVMKkOtJ1BNcNgAO64CXSrRUcgIODQfZE4DHM4UoGPAD6J3ul0e90wAGF7mmjgBNAAK9zm6j4AEdStw3h9yPZI9HY1B44dyYCqScM1mc-nC13KcDK7ga3WuA3PvZIdDYfDjoyuMzWezObGeRBpCIjgyEEyWWy4LqDdyMVB+QNgILd0dZfrDReTWKhcwtcNScPU73M9nM4ORZlvcKzHPekD2GwZLJt2wJ9v+uYFkWMEjtS9L7oea5wJK0q5FAACquDBi4trIpQGqnk+xq9KaNRKh0WqMMclHnsSMQIDIIgCNo0JQAU75WlA3q+j40gFEYbD0hCuBQjCcLQK+wAAOp8MAyAYSuR7Qm6hI7mwe7Lqux4sUal4Cjed4PmepkvuZt4fl+KE-qBGlGeuPGbryBkHppWHCnu3ThlKMpOPKjqlggamKRRj6sSKwSKYxJJQQA0lAAhQFMIDYNoxy0vSYwpUsJkXtxvH8WwbDWgUJXURUtEeOaHQiJVUDWmFGgRVF5nSIRxFIKRFrbuJEmtVAXp4D6Kh+gGQahqNklQDYABu0KSlAABkcoOk6SqEjpBwauGIXQB17hdcgGylGJ-nnZFyBJTVsU2TRVSDc1VV8Z6fG1fFbh0U1PiCUcd1qb9HUXdFfUkQDdrkSNLVtT9z3PjRimI59EP3Vd27QwNsNkcNBi3SQF0LZV9Kg8gv2KSpamuVpcAHbgelja1ZUnt5mHHrebOtXjYDvaJ4kY5V5OfVzvnHqLY6BiGuCI3MK3Qt9yvYbhspY2pOOszqKN1aKdm7hd4M7ZDPWavZQyfql6W4Jl0w5ccF2gWl+sO9luVHIj7U7VTOtHIVSz+RdQfk0rECrerWyTI7Xsu9JskLqd2DYLJDNYclUC6OistzbgOEnVA9wyXAIDWyIU5cBNuBTdGomzfLQW7HhqClGXFdsMyafQnmnzmoSdJyqnsl9yoXiEpKLeayPvFMSXvDl1tNvZ7PcDoAIExcPA2CEGAY8D3gQ+XGvG+4FvO97wfE94FPGtOPcZ5wLgxRnxMQwLx3y8iOQm-6JccBsCvGPmva+2Jb7MB2PfFOPc4BgJdJ3dKUJXjV2HrAsYSw75FxPrAt+29AF7w-qXJeWdBAELAG-Iej9ZIv3IG-UQwlpoN3PvnZu0C0GyTwZffe-cb72yYivVSEBXhzBwZwze+Dd5gCwXhE2AiRDd1Hrw8BuA5grzYEIlBajRbQQBKhE4LlDKMw5B5bkvIxHQgzjzDh0JwytSgWwKBUCi4AElkFDC1pdYo1027QhAMKMmuwWwxjjAcRMeo5huOEfYDsiZZg2LgFY3i6RNCZBsBoIYep7BAA)

3. Watch the error disappear.

### 🙂 Expected behavior

Versions 4.9.5 an below correctly infer the types (produce no error). Changes to the order of `type` declarations do not affect the result.

**Comment by andrewbranch** [comment] 2023-09-11 18:02
Caused by https://github.com/microsoft/TypeScript/pull/52392

**Comment by ahejlsberg** [comment] 2024-05-29 22:18
The issue here is similar to that in #56291. The example requires resolving nested `FieldPathValue` instantiations more than three levels deep, and which point the type checker stops evaluating to avoid what appears to be infinite recursion. As I mention in #56291, we simply don't have a good way to determine that the instantiations eventually terminate. The reason the example works when types are reordered is that type IDs end up ordering differently and don't exhibit the same increasing ID pattern that causes termination.

We're continuing to think about better ways to handle these scenarios.

**Closed** 2024-06-01 01:31 UTC
Labels: Design Limitation
