### ISSUE TITLE
transpiled optional chaining and nullish coalescing calls global getter twice

### ISSUE THREAD

**Issue by j4k0xb** [microsoft/TypeScript#56863] opened 2023-12-24 05:22 UTC
### 🔎 Search Terms

"optional chaining", "nullish coalescing", "getter", "global", "temporary variable"

### 🕗 Version & Regression Information

- This changed in commit or PR https://github.com/microsoft/TypeScript/pull/34951

### ⏯ Playground Link

https://www.typescriptlang.org/play?module=0&ts=3.8.3#code/PIIwVgpgxgLgdAEwgMwJYDsIAUBOB7ABwhxgE8AKAdwwT0oBoACAIgENmmBvAKEcYHMIMcgEpGPPnyh50AZzwAbCHAV5+5ZoJjMRAbl6MAvvW6G93VgH44Ifa0aXLjAIy6gA

### 💻 Code

```ts
Object.defineProperty(window, "a", {
  get() {
    console.log("get");
  },
});
a?.b;
a ?? 1;
```

### 🙁 Actual behavior

It logs `get` 4x because the getter is accessed multiple times:
```js
a === null || a === void 0 ? void 0 : a.b;
a !== null && a !== void 0 ? a : 1;
```

### 🙂 Expected behavior

Log `get` 2x (same as running the untranspiled source code)
It should use temporary variables like Babel and SWC:
```js
var _a, _a2;
(_a = a) === null || _a === void 0 || _a.b;
(_a2 = a) !== null && _a2 !== void 0 ? _a2 : 1;
```

**Comment by MartinJohns** [comment] 2023-12-24 06:17
IMO this is intentional and a duplicate of https://github.com/microsoft/TypeScript/issues/50426#issuecomment-1226054446.

**Closed** 2023-12-31 01:49 UTC
