### ISSUE TITLE
New Feature Requesting for `RegExp` literal type

### ISSUE THREAD

**Issue by ngolin** [Microsoft/TypeScript#18521] opened 2017-09-16 06:51 UTC
Since there is `string literal type`, it is natural to come to the idea of **RegExp literal type**. But more importantly, it's not just natural thinking, it's also based on reality using.

There have been some famous patterns, such as:
event listener: **on***
Angular directive: **ng-***
Vue directive: **v-***

When these string passing around, sometimes the pattern information is important too, so this is a point to keep it along by using **RegExp literal type**.

There is a function `function query(word: string)` in my recent project, the `word` parameter must have a prefix such as 'en' to indicate whether the word is in English or Chinese or not. So it also follows a particular pattern, better to be defined as something like this: `function query(word: /en[a-z]+/ | /zh.+/)`.

RegExp has been widely in JS Apps to describe string patterns. I mean, if we code something like this:
```ts
function doSomething(text: string) {
    if (!text.match(/^on[a-z]+$/)) throw new SyntaxError();
    // do something carefully otherwise
}
```

**that is, if there is every need to check the correctness at runtime, why not do so at compile-time earlier on?**
```ts
function doSomething1(text: /^on[a-z]+$/) {
    // do something happily anyway
}
```

The gap between `'string'` and `string` is very big, there must be something can fill in, I suppose. And RegExp is just the good choice to do so. Anyway, it must be a really interesting feature. But it seems very difficult to implement though.

**Comment by isiahmeadows** [comment] 2017-09-16 10:06
Clarification: you're probably thinking of string pattern constraints, which have more in common with numeric constraint types than regular expressions. In that light, I'd advise recasting your proposal to *not* seem like it's confusing that with RegExp instances.

**Comment by ngolin** [comment] 2017-09-16 10:56
@isiahmeadows I have no idea what numeric constraint types are all about. I'll do some search later. But when I rethink about it, there is something confusing.

**Comment by isiahmeadows** [comment] 2017-09-16 11:24
@ngolin By "numeric constraint types", I was referring to this kind of thing:

https://en.m.wikipedia.org/wiki/Constraint_satisfaction

(Apologies for the slightly incorrect terminology.)

**Comment by isiahmeadows** [comment] 2017-09-16 11:36
Also, another note: assignability for such patterns is pretty difficult to compute for all but the most contrived of cases.

- JS regular expressions technically are context-free due to allowing infinitely nested parentheses, so equivalence may likely be undecidable. (Basically, this means checking it could result in an infinite loop.)
- Mathematical regular expressions' equivalence is already not easy to compute in the general case. Keep in mind, this prohibits grouping of any kind as well as backreferences.

**Comment by ngolin** [comment] 2017-09-16 13:16
@isiahmeadows It seems this issue is beyond my understanding, but I quite understand your point. But I have another problem. Do you think `(str: string) => void` is assignable to `(str: string | undefined) => void`. I don't think so. And I've just made my confusion [here](https://github.com/Microsoft/TypeScript/issues/18466#issuecomment-329965558).

**Comment by gcnew** [comment] 2017-09-16 17:08
This issue seems to be a dupe of https://github.com/Microsoft/TypeScript/issues/6579.

**Comment by DanielRosenwasser** [comment] 2017-09-16 19:30
Hey, thanks for filing, but this seems to be a duplicate of #6579.

In the future using the issue tracker's search functionality can make it easier for us to triage issues. Thanks!

**Closed** 2017-09-17 02:45 UTC
Labels: Duplicate
