### ISSUE TITLE
Type predicate using generic not working implicitly - Signature must be a type predicate

### ISSUE THREAD

**Issue by jroru** [microsoft/TypeScript#55641] opened 2023-09-05 21:30 UTC
### 🔎 Search Terms

* type predicate
* generic
* must be a type predicate

### 🕗 Version & Regression Information

- TS 5.2.2
- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/MYewdgzgLgBAbgQwDYEsAmCogE4DEHBbYCeMAvDADwAqANAHwAUAUDPMupjgFwyPAIwaTlACmvAK5gA1mBAB3MAEpy9GAKEjRMFBBjVmKsmoDeAXwDczZgHobMUQA8ADqMKi0MALQxsoqBLYYDBQxK4wIABm7KgYRA4uqMAoUEikztggcOgezIixXHgERMSUYBIAtgBGothMrHwawnGiSrxNWjp65dW1qiFholHqgs2Y2mSTMABEPTXY04ZWtvZysE6u7p4+fgFBA+HD+SI4MBAAFiASSJ6gFdqRmRUh59oA5qJgtSjAMM4I2AQz0YogAdG9QTA5rUVBksjlPOAYKgvjAAIxovIcOI4fCEHClaF1FhsfijLRGNShVzDDotchTWaVeaLJQWIA

### 💻 Code

```ts
const validatorFactory = <T,>(
  validator: (candidate: unknown) => candidate is T
) => {};

// expected - return type of validator explicitly provided
validatorFactory<number>(
  (candidate): candidate is number => typeof candidate === "number"
);

// not expected - return type of validator should come from the generic param (e.g. number)
validatorFactory<number>(
  (candidate) => typeof candidate === "number"
);
```

### 🙁 Actual behavior

```
Argument of type '(candidate: unknown) => boolean' is not assignable to parameter of type '(candidate: unknown) => candidate is number'.
  Signature '(candidate: unknown): boolean' must be a type predicate.(2345)

```

### 🙂 Expected behavior

The return type of the type predicate should be based on the generic parameter implicitly.

**Comment by MartinJohns** [comment] 2023-09-05 21:54
Related / duplicate of #38390.

Arrow functions are never inferred as type guards.

**Comment by jroru** [comment] 2023-09-06 21:14
Is this achievable somehow without using arrow functions?

**Closed** 2023-09-10 12:21 UTC
Labels: Duplicate
