### ISSUE TITLE
`forceConsistentCasingInFileNames` does not always work with `paths` compiler option

### ISSUE THREAD

**Issue by stephenbrady** [Microsoft/TypeScript#17617] opened 2017-08-04 18:44 UTC
**TypeScript Version:**  2.4.2

**Code**

```ts
// Base tsconfig at /Users/a_user/a_repo/core.json
{
  "compilerOptions": {
    "forceConsistentCasingInFileNames": true,
    "baseUrl": "",
    "paths": {
      "*": [ "*", "src/*" ]
    }
  }
}

// tsconfig at /Users/a_user/a_repo/tsconfig.json
{
  "extends": "./core"
}

// Source file in /Users/a_user/a_repo/src/foo.ts
const v = 1;
export default v;

// Source file in /Users/a_user/a_repo/src/bar.ts
import v from "foo";

```

**Expected behavior:**
No compiler errors/warnings

**Actual behavior:**
```
error TS1149: File name '/Users/a_user/a_repo/src/foo.ts' differs from already included file name '/users/a_user/a_repo/src/foo.ts' only in casing.
```
---

This is running on OS X 10.9.5 (default case-insensitive HFS file system).

I am only able to reproduce the issue when using configuration inheritance. Using an absolute path with the expected casing for `baseUrl` resolves the issue.

This issue is filed off of these remarks: https://github.com/Microsoft/TypeScript/issues/17542#issuecomment-319296988

**Comment by aluanhaddad** [comment] 2017-08-05 05:44
Thank you for filing this. I see the exact same behavior. Interestingly, if I set `baseUrl` in the _extending_ tsconfig, it also resolves the error.

**Comment by afshinm** [comment] 2017-09-03 16:10
I have the same problem on mac OS, node 7.6.0.

**Comment by arackaf** [comment] 2017-09-06 20:21
Reproduced on Windows 10 as well.  Interestingly, we don't even have paths set.  Full tsconfig:

```
{
    "compilerOptions": {
        "target": "esnext",
        "baseUrl": "./src",
        "jsx": "react",
        "allowSyntheticDefaultImports": true,
        "allowUnreachableCode": true,
        "allowJs": true,
        "moduleResolution": "node",
        "module": "es2015",
        "experimentalDecorators": true,
        "forceConsistentCasingInFileNames": true,
        "lib": ["es2015", "dom"],
        "typeRoots" : ["./typings/modules", "./node_modules/@types"]
    },
    "include": [
        "./src/**/*.ts",
        "./src/**/*.tsx",
        "./src/**/*.js",
        "./src/**/*.jsx",
        "./test/**/*.ts*"
    ],
    "exclude": [
        "./node_modules/**/*",
        "./dist/**/*",
        "./src/assets/**/*",
        "./src/build/**/*"
    ]
}
```

**Comment by aluanhaddad** [comment] 2017-09-06 20:38
@arackaf it is `--baseUrl` that causes the issue. When it is inherited, it seems to get resolved in such a way that the _resulting_ paths begin with it's lowercase variant. the simplest work around currently is to specify the base URL a second time in the inheriting configuration.

**Comment by arackaf** [comment] 2017-09-07 02:56
What do you mean "inherited" ?  I only have one tsconfig file - what's being inherited where?

**Comment by aluanhaddad** [comment] 2017-09-07 03:12
Sorry, it's not in the issue title but the op states that the issue can only be reproduced when using configuration inheritance. This has been my experience as well.

I'm also running Windows 10, professional x64

**Comment by arackaf** [comment] 2017-09-07 06:27
Oh interesting.  Well I may have stumbled onto a different repro of the same bug.  I only have one tsconfig.json in my project, but this still fails for me.  I ran a search on my file system, and the only other tsconfig file anywhere is in node_modules, which I've explicitly excluded.

**Comment by mhegazy** [comment] 2017-09-07 17:54
OP should be addressed by https://github.com/Microsoft/TypeScript/pull/18058.

@arackaf can you share more context about your issue, preferably in a new ticket.

**Closed by mhegazy** 2017-09-07 17:54 UTC
Labels: Bug, Fixed

**Comment by arackaf** [comment] 2017-09-07 18:18
@mhegazy  When is the fix in 18058 going to show up in a new version?  If that doesn't fix my issue, then sure, I'll open a new ticket, hopefully with a minimal repro

**Comment by mhegazy** [comment] 2017-09-07 18:48
> When is the fix in 18058 going to show up in a new version?

it should be in today's `typescript@next`.

**Comment by arackaf** [comment] 2017-09-07 20:06
Cool, but when do you expect the next regular release on npm?  Want to try _that_ on my work repo.  We definitely can't be running typescript@next in prod :)

**Comment by mhegazy** [comment] 2017-09-07 20:46
should be in 2.6, [scheduled for October](https://github.com/Microsoft/TypeScript/wiki/Roadmap)

**Comment by arackaf** [comment] 2017-09-08 02:06
Oh my - seems I missed 2.5!  :D

**Comment by jamietre** [comment] 2018-02-16 00:13
This is still happening to me in 2.7.1 on MaOS. I'm using inherited tsconfigs, it doesn't matter where `baseUrl` is specified, tried all permutations.

**Comment by weswigham** [comment] 2018-02-16 00:24
A similarish bugfix related to consistent casing shipped in 2.7.2, which as it happens released today. Does it fix your issues?

**Comment by aluanhaddad** [comment] 2018-02-16 00:31
@weswigham yes! It fixes the issue. Thank you very much.

**Comment by jamietre** [comment] 2018-02-16 01:01
Works for me too! Talk about instant gratification..
