### ISSUE TITLE
"Type  is not assignable to type 'Readonly<any>'.(2322)"

### ISSUE THREAD

**Issue by MarcelWaldvogel** [microsoft/TypeScript#50026] opened 2022-07-24 14:37 UTC
# Bug Report

### 🔎 Search Terms
readonly, any, literal, assignment, initializer

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `readonly`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=15&ssc=14&pln=15&pc=76#code/PTAEEkDsEsBdoIYBtoC9qQOagaAzrAE4aYBcoA7gPaEDWeAULAJ4AOApqAMqgC8+REgG4GSdrHwBGcj34AiBAjkixEvACZyAJXYIAJlUhJmAHi4A+PqAVKRDPJKtyARsvvqnruyAgx4yNBIcSGZyajo8ABpQdgAPAGN2VgkAMxpQHX1DYyY2TgBBKwQQlXEcaVBC+UU3VRxNDN0DI1N8y2rbUB8AFTzQAHICYix+0Gg8UEgqCQQ8PGhMSARnMVBYKjW+-szm4xNi5nN+gDoACnUAZnV1AEoGBgRHeS8Hj2flLrBejgGhklHxpNpjg5gslitOOtNj9tk1sqYDkczpdrncgA)

[More realistic playground example](https://www.typescriptlang.org/play?ts=4.7.4#code/KYDwDg9gTgLgBDAnmYcAixhgErAIYAmEAdgDaIA8AKgHxwC8cVcoMwxBAznAN4C+cAD5wA2gF0AsACg4cAPxxchEuQo9RABTgBLYnADWwRBABmTMQC50mHPiJlKVERrF0+NabKtL7q2gG5pJBRrLB8VRAAmajpGZlZ2Ll4BYXFPeUU7CLVNHT1DYzMqS1DbZQcAZmpnVzh3dO8shxjAqWDUDDCm8iraBiYWEDYObn4hUUkZDPDm9Wc8gyNTcytOst9EXpq3DymrKlag5FQADX71PCtOGChdAHN-OAAjK2IAVwBbJ+AoR4BjKx4YiIR4ERp-aAECjXW7EO4AGjgQMQblaEOI1zgIAAjFYzowLlYAER4PBExEvOCRSKIgFwIkgEDkuBg3hIqzYilWSJ1OpokiYkCRRrlVQnWJsy700nMynU2nExnM1mEuCc57c3l8fkY+AgCqrGwzMUS1Ukslcqk0uB0hlMxEq9lqy08gTauAAeg9cBMeG0pG4EDeME42gIqCBBDyofD0nRgoALIauqKohRxecnebZdzrbalQ6rKr1XKtYc2sc4ABNTNSmH3R6U95fH7-QHA0HgyHQm73RHN75QVFxgXwRC46u14kyl15xX2llFp0lzVunWYqIijYUKumrMzjVWhX0guLyUcl1lke6uCbZPrbK7qfSi2H+U2+fKpdSldUsue71fX9QNgxjYBrw3JNSmNNMnwJfdXzlOcTwXR0f0vNdpCAA)

### 💻 Code

```ts
// Initializing a string: works
type S = string;
let s1: S = "aa";
let s2: Readonly<S> = "aa";

s1 = "b";
s2 = "b";

// Initializing any: works, except for Readonly
type A = any;
let a1: A = "aa";
let a2: Readonly<A> = "aa"; // Type 'string' is not assignable to type 'Readonly<any>'.(2322)
let a3: Readonly<A> = "aa" as any; // OK

a1 = "b";
a2 = "b"; // Type 'string' is not assignable to type 'Readonly<any>'.(2322)
```

### 🙁 Actual behavior

`Readonly<any>` loses the assignability properties of `any`.

### 🙂 Expected behavior

`Readonly<any>` should maintain the assignability of `any`. `Readonly<>` for other types (e.g., number, string, object) maintains the assignability.

There seems to be no obvious reason for this difference.

**Comment by MartinJohns** [comment] 2022-07-24 15:45
Sounds like a duplicate of #19624.

**Comment by MarcelWaldvogel** [comment] 2022-07-25 09:22
I took a closer look, and, indeed, they seem to have the same root cause. Sorry!

To summarize my current understanding of `Readonly<>`: It tries to coerce the type into something key/value-ish (object, array), for which it succeeds with `any`, but silently fails with primitive types and turns into a no-op.

If so, then:
1. can this behavior be documented in the `Readonly<>` TS reference section, by appending "It is a no-op on primitive types. For arrays, `ReadonlyArray<>` is preferred." to the introduction? This would make it more explicit that `object` is not just a example usecase, but in fact the only reasonable use (with `ReadonlyArray<>` better suited for arrays. Or,
2. can `Readonly<>` be made to issue a warning when applied to primitive types?

BTW: #19624 has the *working as intended" label. Apparently, the intention changed between 2.5.3 (the version reported for) and 3.3.3 (the oldest in the playground), because the error is no more (Playground 3.3.3 and 4.7.4 are happy with the code 2.5.3 reportedly was unhappy with).

**Comment by RyanCavanaugh** [comment] 2022-07-28 03:18
This isn't something we've seen frequent enough user feedback on to warrant inclusion in an introductory text.

**Closed** 2022-07-30 20:00 UTC
Labels: Working as Intended

**Comment by web3jt** [comment] 2022-11-18 08:49
Thanks all above.

I think I have work it out just like this https://github.com/web3jt/dApp-tour/commit/902e1f2d3f291dfc173c0404f3b36c813ae61512

After change

```typescript
const MONARCH_MIXER_CONTRACT_CONFIG = {
    addressOrName: '0x...',
    contractInterface: CONTRACT_ABI,
};
```

to

```typescript
const MONARCH_MIXER_CONTRACT_CONFIG = {
    address: '0x...',
    abi: CONTRACT_ABI,
};
```

I'd got the right alert about `readonly` type

then I updated

```typescript
interface MintCodeJSON {
    tokenId: number,
    proofId: number,
    proof: string[],
}
```

to

```typescript
interface MintCodeJSON {
    tokenId: number,
    proofId: number,
    proof: readonly `0x${string}`[],
}
```

Now, solved.

Thanks again and wishes.

**Comment by web3jt** [comment] 2022-11-18 08:52
> This isn't something we've seen frequent enough user feedback on to warrant inclusion in an introductory text.

I think that's because not so many people use typescript after imported `wagmi` by themselfs,

there are lot of bootstrap or cases using js but not ts,

so they just fork/copy, edit, deliver...
