### ISSUE TITLE
Increment expression of `for` loops don't invalid the type of variables typed as literal number values

### ISSUE THREAD

**Issue by MichaelMitchell-at** [microsoft/TypeScript#50176] opened 2022-08-04 04:47 UTC
# Bug Report

### 🔎 Search Terms

increment decrement for loop variable mutate const literal number invalidate invalidation stale

### 🕗 Version & Regression Information

This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220803&ssl=16&ssc=2&pln=1&pc=1#code/GYewTgBAFANgpgFwgSwgXggBggQwM4QDGIAdnggNwoQA8EAjJhQJQQDeAsAFARGnkQAHgC4s6FAGoJFbgF9u3UJFiJqGbPj5lK1OoxbtuvZFJk8tAkWIzIz8rovDR4SVOtwFi2qiYm0GTKyc5l6Wotg2dgpcSs6qbmKaoTqoekySEkFGFkhWEShRXEA)

### 💻 Code

```ts
for (let i = 0 as const; i < 10;) {
  // error - expected
  const x: 0 = i++;
}

for (let i = 0 as const; i < 10;) {
  i++;
  // error - expected
  const x: 0 = i;
}

for (let i = 0 as const; i++ < 10;) {
  // error - expected
  const x: 0 = i;
}

for (let i = 0 as const; i < 10; i++) {
  // no error - unexpected!
  const x: 0 = i;
}

```

### 🙁 Actual behavior

No type error

### 🙂 Expected behavior

Type error, since this is obviously unsound.

**Comment by MartinJohns** [comment] 2022-08-04 05:08
Duplicate of #14745.

**Comment by MichaelMitchell-at** [comment] 2022-08-04 06:05
I'd contend that this isn't a duplicate on the grounds that even though https://github.com/microsoft/TypeScript/issues/14745 was closed as "Won't fix", the example that it referenced was actually fixed at some point in the last five years, but the example I provided doesn't work.

**Comment by MartinJohns** [comment] 2022-08-04 07:28
There's also #47027, which is essentially about the same issue and is still open.

**Comment by fatcerberus** [comment] 2022-08-04 14:32
The increment and subsequent assignment being allowed is #47027, but there seems to be a second bug here: removing `i++` from the loop header makes `i` be treated as `number` inside the loop (thus all the other assignments being errors), while having it there preserves the literal type.  That is… quite bizarre and if anything I’d expect it to be the other way around.

**Closed** 2022-08-06 18:00 UTC
Labels: Duplicate
