### ISSUE TITLE
Type is not assignable to itself in `else` branch of conditional when using conditional type with `: T`

### ISSUE THREAD

**Issue by jtbandes** [microsoft/TypeScript#47901] opened 2022-02-15 02:56 UTC
# Bug Report

### 🔎 Search Terms

not assignable conditional else

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about the above search terms

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD28A8AVAfNA3gKGtA5gKYAu0AbmCAK6EAUAlAFzQpbTEAWATvAO7QA7QvwCiXHlwYBuaAF9s87ADMqA4MQCW8AdC6rUaWksTMUTFtEIAPYoQEATGAmQaBSwl2gBVDAH5v0KZ4OHgaStBGiNCuEMRgaoTw4c70WLh4uiRUXDrG8AB0FNSEUumyliAQhGkZmcTZuYilePKyQA)

### 💻 Code

```ts
class Foo<T> {
  get value(): T { throw new Error(); }
}

function run<T>(foo: T): T extends Foo<infer U> ? U : T  {
  if (foo instanceof Foo) {
    return foo.value;
  } else {
    return foo;  // Type 'T' is not assignable to type 'T extends Foo<infer U> ? U : T'.
  }
}
```

### 🙁 Actual behavior

`foo.value` is assignable to `U` in the `if` branch, but `foo` is not assignable to `T` in the `else` branch.

### 🙂 Expected behavior

Given that `foo instanceof Foo` is false, I would expect the `:` branch of the conditional type to be used, meaning that the function's return type should be `T`, to which `foo` should be assignable (because its type is `T`).

**Comment by fatcerberus** [comment] 2022-02-15 03:05
Duplicate of https://github.com/microsoft/TypeScript/issues/33912

**Comment by jtbandes** [comment] 2022-02-15 03:09
Thanks, that looks right, however based on reading the issue I'm surprised that `return foo.value` works in the `if` branch at all; have some changes been made since the original issue was created?

**Comment by fatcerberus** [comment] 2022-02-15 03:12
The only thing I can think of is that because `T` has no constraint it's prematurely inferring `infer U` as `unknown` or `any`.

**Comment by RyanCavanaugh** [comment] 2022-02-15 20:42
> ...  known to be assignable to both sides of a conditional, 

This logic has been removed

**Comment by fatcerberus** [comment] 2022-02-15 20:56
@RyanCavanaugh If that logic has indeed been removed, then why is `return foo.value` not an error in the example?

**Comment by RyanCavanaugh** [comment] 2022-02-16 18:29
`foo.value` is `any` there (TBH I haven't looked into why, seems a little odd)

It's a safe rule but was causing enormous performance problems in material-ui

**Closed** 2022-02-19 18:00 UTC
Labels: Duplicate
