### ISSUE TITLE
Expose isTypeAssignableTo in TypeChecker?

### ISSUE THREAD

**Issue by MeirionHughes** [Microsoft/TypeScript#11728] opened 2016-10-19 07:30 UTC
I would like to determine if one Type is assignable to another Type. So far I've only found the type comparison and checking functions in checker.ts, but that entire file is marked internal. 

Is there a way to determine if one type is assignable to another using the exposed typescript library? A question to this effect on StackOverflow has not been answered. If not, could such functionality be added, say to `TypeChecker`?

**Comment by MeirionHughes** [comment] 2016-10-28 00:50
this seems to be a rather basic change: 

**types.ts**
```ts
export interface TypeChecker {
  ...
  isTypeAssignableTo(source: Type, target: Type):boolean;
  ...
```

**checker.ts**
```ts
const checker: TypeChecker = {
  ...
  isOptionalParameter,
  isTypeAssignableTo
};
```

basic usage check: 

```ts
let source: ts.SourceFile = file["source"];
let decl = <ts.ClassDeclaration>source.statements.find(x => x.kind == ts.SyntaxKind.ClassDeclaration);

let checker = ref.typeChecker;
let type = checker.getTypeAtLocation(decl);

expect(checker.isTypeAssignableTo(type, type)).toBe(true);
```

@RyanCavanaugh any chance of a quick look to see if this is acceptable?

**Comment by RyanCavanaugh** [comment] 2016-10-28 20:43
We also had a request from a partner team to expose this and some other functions. This list looks fairly reasonable and shouldn't create any problems -- we'll be following up
```ts
isTypeAssignableTo
getAnyType
getUndefinedType
getBooleanType
getNullType
getNumberType
getStringType
createArrayType
getUnionType
```

**Comment by MeirionHughes** [comment] 2016-11-17 09:26
@RyanCavanaugh would you allow me to PR a quick change to expose `isTypeAssignableTo` in TypeChecker, at least, or are you looking to make breaking changes before exposing this?

**Comment by weswigham** [comment] 2016-11-17 10:11
@RyanCavanaugh Also note, This specific issue is encompassed in #9879, which still has #9943 open.

**Comment by MeirionHughes** [comment] 2017-04-10 14:30
@RyanCavanaugh any progress? This all seems to have stalled. All I really need is for the exiting implementation of `isTypeAssignableTo` to be exposed - I'm happy to make a PR to that effect.

**Comment by raveclassic** [comment] 2017-11-01 07:50
@RyanCavanaugh Same here (https://github.com/Microsoft/TypeScript/issues/19602), all we need is one function which lands with two lines of changes. Maybe you could add a `Community` label to this?

**Comment by mhegazy** [comment] 2017-11-01 16:53
Marking as duplicate of https://github.com/Microsoft/TypeScript/issues/9879

**Closed** 2017-11-16 16:57 UTC
Labels: Duplicate
