### ISSUE TITLE
error TS2564: Property 'client' has no initializer and is not definitely assigned in the constructor.

### ISSUE THREAD

**Issue by wpconsulate** [microsoft/TypeScript#56250] opened 2023-10-29 19:07 UTC
### 🔎 Search Terms

I have a class in typescript 

```
class Redis {
  private static instance: Redis
  private readonly redisUri: string
  public client: RedisClientType

  constructor(redisUri: string) {
    this.redisUri = redisUri
    this.createClient()
  }

  private createClient() {
    try {
      this.client = createClient({
        url: this.redisUri
      })
    } catch (error: any) {
      winston.error(error)
    }
  }
}
```

in this class I'm getting typescript compile error
`error TS2564: Property 'client' has no initializer and is not definitely assigned in the constructor.`

now if I move the code from `createClient` function to `constructor` then there's no error.
But compiler gives me error even though, I'm calling that function in the contructor itself. 

this seems lke a bug to me.

### 🕗 Version & Regression Information

- this doesn't let me to build and crash

### 💻 Code

```ts
class Redis {
  private static instance: Redis
  private readonly redisUri: string
  public client: RedisClientType

  constructor(redisUri: string) {
    this.redisUri = redisUri
    this.createClient()
  }

  private createClient() {
    try {
      this.client = createClient({
        url: this.redisUri
      })
    } catch (error: any) {
      winston.error(error)
    }
  }
}
```

### 🙁 Actual behavior

in this class I'm getting typescript compile error
`error TS2564: Property 'client' has no initializer and is not definitely assigned in the constructor.`

### 🙂 Expected behavior

compiler should also check if the member variable is assigned a value with the function that is being called within contructor

**Comment by MartinJohns** [comment] 2023-10-29 19:17
Duplicate of #21132.

**Closed** 2023-11-02 01:26 UTC
Labels: Working as Intended
