### ISSUE TITLE
private mode

### ISSUE THREAD

**Issue by fsocietyCodeMaster** [microsoft/TypeScript#56171] opened 2023-10-22 08:24 UTC
### 🔎 Search Terms

private property in a class

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

class Person {
        private Name : string;
        constructure(name : string){
        this.Name = name
} }

### 🙁 Actual behavior

the problem is when we compile into javascript code in ES2022 we have # to make a property private and we cant get access to it 
here in typescript even when we configure target to ES2022 , when we compile the above code in javascript file the privacy didnt applied and we can get access to the property and log it ,even the # doesnt appear

### 🙂 Expected behavior

in javascript we need to have the same result

### Additional information about the issue

thanks you

**Comment by MartinJohns** [comment] 2023-10-22 08:27
This is working as intended. If you want ES2022 private properties you must use `#`. Properties marked as `private` **will not** be transformed to `#` properties.

**Comment by fsocietyCodeMaster** [comment] 2023-10-22 08:39
use # in type script so what is the point of using private key bro... nahh,

**Comment by MartinJohns** [comment] 2023-10-22 08:48
`private` has existed long long before `#`-properties. `private` is not going to be removed or transformed to `#`-properties (both would be **massive** breaking changes).

**Comment by fsocietyCodeMaster** [comment] 2023-10-22 09:23
so writing jacascript in typescript is better , its worthless to use private key waste of typing...
at least not in c++

**Comment by jcalz** [comment] 2023-10-22 13:37
Duplicates #31670

**Comment by fsocietyCodeMaster** [comment] 2023-10-22 17:00
Thanks bro

**Closed** 2023-10-23 15:51 UTC
Labels: Duplicate
