### ISSUE TITLE
Question: keys of a type which have a certain type

### ISSUE THREAD

**Issue by Peter-Juhasz** [Microsoft/TypeScript#18211] opened 2017-09-01 18:42 UTC
The type system is awesome, but I am struggling with this problem.

```ts
class View<TMode> {
    public sortBy(source: TModel[], property: keyof TModel): void {
    }
}
```

Is it possible to restrict the second parameter to those keys of `TModel` which type is `string`?

For example, if I have an object like this:
```ts
{
    "id": 1,
    "name": "hello",
}
```

Then the only allowed key is `"name"`.

If not supported now,
 - does any workaround exists with advanced type arithmetic?
 - is it planned?

Thanks.

**Comment by kitsonk** [comment] 2017-09-01 20:09
This is not a support forum.

Questions should be asked at [StackOverflow](http://stackoverflow.com/questions/ask?tags=typescript) or on [Gitter.im](https://gitter.im/Microsoft/TypeScript).

Also, it seems to [work](http://www.typescriptlang.org/play/#src=class%20View%3CT%3E%20%7B%0A%20%20%20%20public%20sortBy(source%3A%20T%5B%5D%2C%20property%3A%20keyof%20T)%3A%20void%20%7B%0A%20%20%20%20%7D%0A%7D%0A%0Aconst%20v%20%3D%20new%20View%3C%7B%20id%3A%20number%3B%20name%3A%20string%3B%20%7D%3E()%3B%0A%0Av.sortBy(%5B%5D%2C%20'name')%3B%0A) as you would expect, unless I am missing something:

```ts
class View<T> {
    public sortBy(source: T[], property: keyof T): void {
    }
}

const v = new View<{ id: number; name: string; }>();

v.sortBy([], 'name');
```

**Comment by Peter-Juhasz** [comment] 2017-09-01 20:58
Thank you for your reply. It's my bad, I used the type `string` which makes the question ambiguous. My question is more of a feature-related question, this is why I chose this channel. If you still see this is not the place for this question then feel free to close it.

It should work with `"name"`, but `"id"` should not be allowed, because its type is `number`. So, if I have a type like `{ id: number, name: string, description: string }`, is there any way to reference only `"name"` and `"description"` (based on their types, excluding `"id"`) as a literal type?

As far as I know, it is not possible now, but a workaround might exists like in #18133 or it might be a proposal for future versions. It is also very similar to #13214.

**Comment by kitsonk** [comment] 2017-09-01 21:04
Actually, as you point out by linking to #13214 that this is actually a duplicate of #12424 which is a feature being considered for the future.  Of course researching these things _before_ you open an issue would be great.

**Closed** 2017-09-01 21:08 UTC

**Comment by gcnew** [comment] 2017-09-01 21:55
There is a workaround but keep in mind that these workarounds are quite fragile. E.g. try to make `description` optional, or `string | undefined`.

```ts
type Bool = 'true' | 'false'

type HasKey<T, Key extends string> = (
  { [K in keyof T]: 'true' } &
  { [key: string]: 'false' }
)[Key]

// if the type has a `charCodeAt` property we deem it a `string`
// obviously, this might not always be the case
type IsString<T> = HasKey<T, 'charCodeAt'>

type StringProps<T> = {
    [K in keyof T]: {
        'true': K,
        'false': never
    }[IsString<T[K]>]
}[keyof T]

class View<T> {
    public sortBy<K extends StringProps<T>>(_source: T[], _property: K): void {
    }
}

const v = new View<{
    id: number;
    name: string;
    description: string;
}>();

v.sortBy([], 'description');
```

**Comment by VinceOPS** [comment] 2018-04-12 16:18
TS 2.8

```typescript
export type StringProps<T> = ({ [P in keyof T]: T[P] extends string ? never : P })[keyof T];
```

**Comment by jdforsythe** [comment] 2018-07-05 20:55
Nice @VinceOPS 

Any way to make it work on private methods?

```ts
class SomeClass {
  public prop;
  constructor() {}

  public someMethod() {}

  private somePrivateMethod() {}

  private other() {
    this.callWithThis('prop'); // proper warning, since it's not a Function
    this.callWithThis('someMethod'); // properly no warning, since it's a Function
    this.callWithThis('somePrivateMethod'); // warning since it's private
  }

  private callWithThis(classFnName: MethodProp) {
    const self = this;
    return () => { return self[classFnName].call(self); };
  }
}

type MethodProp = ({
  [T in keyof SomeClass]: SomeClass[T] extends Function ? T : never
})[keyof SomeClass]
```
