### ISSUE TITLE
ParseInt and ParseFloat should accept numbers and BigInt as Input

### ISSUE THREAD

**Issue by rafikalid** [microsoft/TypeScript#50828] opened 2022-09-18 14:21 UTC
# Bug Report

`parseInt` and `parseFloat` only accept string. therefore it should accept `number`, `Number` and `bigInt` too

### 🔎 Search Terms

- parseInt
- parseFloat

### 🕗 Version & Regression Information

all versions

Please keep and fill in the line that best applies:
-->
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about parseInt and parseFloat

### ⏯ Playground Link

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/A4QwTgzgpgkgdgFwBQA4CsAWOBKA3AAgHpD8BlACwHsBXAGwBN8B3SsAa2YEsFz8AjTgHN4CAFChIsREkwoAdACY0eIiQo0GzVhwSVKXHvjjUAtnyiRR48NABitSiGTosK4mSp1GLdgd4DhRGtJe0dkWUVlAnd1Ly1fXX0mbl5jMwsIK3cAVQhOOEFmMBBgYAzRAGNKOAgEI3wAXiMoJnwAOVNzMBko4OgRJBxotU9NHzYrKpq6gLamuBb8ACEhAYBGDDReiX7pWbcRjW9tfESgA)

### 💻 Code

```ts repro
parseInt(854n); // Should work with bigInt
parseInt(548.25); // Should work too with numbers

parseFloat(854n); // Should work with bigInt
parseFloat(548.25); // Should work too with numbers

// Using wrappers
const n = new Number(55);
parseInt(n); // Should work

```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/A4QwTgzgpgkgdgFwBQA4CsAWOBKA3AAgHpD8BlACwHsBXAGwBN8B3SsAa2YEsFz8AjTgHN4CAFChIsREkwoAdACY0eIiQo0GzVhwSVKXHvjjUAtnyiRR48NABitSiGTosK4mSp1GLdgd4DhRGtJe0dkWUVlAnd1Ly1fXX0mbl5jMwsIK3cAVQhOOEFmMBBgYAzRAGNKOAgEI3wAXiMoJnwAOVNzMBko4OgRJBxotU9NHzYrKpq6gLamuBb8ACEhAYBGDDReiX7pWbcRjW9tfESgA)

### 🙁 Actual behavior

Those functions accept only string to parse

### 🙂 Expected behavior

Should accept `number`, `Number` and `bigInt` too

### Solution
I send a PR for this. please review and merge :heart:

**Comment by fatcerberus** [comment] 2022-09-18 14:24
Duplicate of #17203/#38471

**Comment by rafikalid** [comment] 2022-09-18 14:31
fix: https://github.com/microsoft/TypeScript/pull/50829

**Comment by rafikalid** [comment] 2022-09-18 14:40
When I need to convert a number into an integer, I use this :
const myInteger= parseInt(542.33)
the same If I want to convert a big Integer into int.
I don't have a good reason why limit this to string when the real API allows any type of data?

**Comment by fatcerberus** [comment] 2022-09-18 14:47
That's what `Math.trunc` is for. `parseInt` will do the wrong thing if your numbers are too large, e.g. `parseInt(3e21)` returns `3` (Have you actually read through the linked issues? This was discussed to death.) So while it does allow any type of data (by converting it to a string first), it's not guaranteed to do what you intended. The purpose of the type checker is to detect bugs like that.

I don't have a reason why limit this to string when to real API allows any type of data?

You could say this about most built-ins because automatic type coercion runs rampant in JS (i.e. half of the reason TS even exists). See https://stackoverflow.com/questions/41750390/what-does-all-legal-javascript-is-legal-typescript-mean

**Comment by MartinJohns** [comment] 2022-09-18 15:09
Besides what fatcerberus said, you should really not be using the types `String` and `Number` in place for `string` and `number`.

**Comment by jakebailey** [comment] 2022-09-19 18:13
Passing non-strings through `parseInt` and `parseFloat` almost assuredly will behave in an unexpected way. If you want to drop the non-integer portion of a number, use `Math.trunc`. If you want to convert a bigint to a number, use `Number(myBigInt)`.

**Comment by fatcerberus** [comment] 2022-09-19 19:20
Indeed.  The key isn't that it *accepts* some type of data, but that it's well-behaved when passed that type.  `parseInt` is well-behaved when passed a string; it tries to convert the string to an integer (it might not always succeed, but you know that upfront).  It's *not* well-behaved when passed a number--it might give you back the integer portion of the number, or it might just totally mangle it, and you have no way of knowing which will happen unless you examine the number's string representation before you pass it in.

**Closed** 2022-09-21 20:00 UTC
Labels: Working as Intended
