### ISSUE TITLE
Argument of type 'number' | 'string' is not assignable to overloaded function accepting 'number' or 'string

### ISSUE THREAD

**Issue by osi-oswald** [Microsoft/TypeScript#8350] opened 2016-04-28 11:17 UTC
**TypeScript Version:** 

1.8.10

**Code**

```ts
declare function overload(param: number);
declare function overload(param: string);

let bar: number | string;
overload(bar); // Argument of type 'number' | 'string' is not assignable to parameter of type 'string'
```

**Expected behavior:**
Since the function 'overload' either accepts a 'number' or a 'string', the compiler should not complain.

**Actual behavior:** 
The compiler complains with: "Argument of type 'number' | 'string' is not assignable to parameter of type 'string'".

**Workaround:**
Of course I could always rewrite the declaration of 'overload' as:
```ts
declare function overload(param: number | string);
```

But usually these declarations are from external *.d.ts files which I do not want to touch if I don't have to.

**Comment by yortus** [comment] 2016-04-28 14:00
Looks like a duplicate of #1805

**Comment by osi-oswald** [comment] 2016-04-28 14:48
You are absolutely right regarding the duplicate

**Closed** 2016-04-28 16:30 UTC
