### ISSUE TITLE
importHelpers is not work at some code

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#45971] opened 2021-09-20 16:16 UTC
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?importHelpers=true&module=1&allowSyntheticDefaultImports=true#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVysARyU3wCVgBnCAGwDdgBhaYACgEoAuOCmKTFAOYBYAFABvUQEh8MJFFwok1anACGFNSgCeogL6jRoSLESoM2XJgC2xmAFEQvVQB4AKnFAxgKACYbV2gB8LCiqVsBcPHyCnHAAClAQVpgUwG6BohIi0sCy8nDWtiz4RCTA5FR0jMzsbHqiQA

### 💻 Code

```ts
export function requireResolveCore(): string
{
	return null as any
}

export function importExtra<T extends any>(name: string): Promise<T>
{
	return import(requireResolveCore())
}

```

### 🙁 Actual behavior

```ts
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.importExtra = exports.requireResolveCore = void 0;
function requireResolveCore() {
    return null;
}
exports.requireResolveCore = requireResolveCore;
function importExtra(name) {
    return Promise.resolve().then(() => __importStar(require(requireResolveCore())));
}
exports.importExtra = importExtra;
```

### 🙂 Expected behavior

```ts
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.importExtra = exports.requireResolveCore = void 0;
const tslib_1 = require("tslib");
function requireResolveCore() {
    return null;
}
exports.requireResolveCore = requireResolveCore;
function importExtra(name) {
    return Promise.resolve().then(() => (0, tslib_1.__importStar)(require(requireResolveCore())));
}
exports.importExtra = importExtra;
```

**Comment by MartinJohns** [comment] 2021-09-20 16:37
Simplified:

    const f = import("" as string)

**Comment by MartinJohns** [comment] 2021-09-20 16:38
Sounds like a duplicate of #27415.

**Closed** 2021-09-20 18:35 UTC
