### ISSUE TITLE
TS 1.8.4: tsconfig.json subfolders and files not excluded

### ISSUE THREAD

**Issue by birick** [Microsoft/TypeScript#7217] opened 2016-02-24 13:57 UTC
In VS 2015 Pro, using the Asp.Net 5 Web Application template, I have installed via npm the typings js module, which in concert with a typings.json file will install Typescript definition files to a typings folder as so... 

- Project
 - wwwroot
 - Controllers
 - scripts
 - typings
    - browser
    - main
    - browser.d.ts
    - main.d.ts
 - Views
 - tsconfig.json
 - typings.json

The browser folder and browser.d.ts is intended for clientside while the main folder and main.d.ts file are intended for serverside, and one should pick which they want to use, and exclude the other.

With TS 1.7.3 installed, one excluded the main files in the tsconfig.json as so (this worked - last two entries in exclude array):

```JSON
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "outDir": "wwwroot/js",
    "rootDir": "scripts",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "system"
  },
  "exclude": [
    "node_modules",
    "wwwroot",
    "typings/main",
    "typings/main.d.ts"
  ]
}
```

After installing TS 1.8.4, I now get Duplicate identifier errors between files in the typings/main and typings/browser folder.  In other words, the subfolder exclude for "typings/main" is not being respected.

Experimenting a bit, the "node_modules" and "wwwroot" is being excluded correctly.  If I exclude the root folder "typings" then the error goes away, but no typings load from any files either.  Also trying to exclude a file in a subfolder, say "typings/main/ambient/bootstrap/bootstrap.d.ts" doesn't work.  So there appears to be a bug excluding subfolders/subfiles.

The expected behavior is for subfiles or subfolders in the exclude array to be ignored during compile.  The actual behavior is that they are not excluded.

**Comment by BigDataSamuli** [comment] 2016-02-24 14:47
That's the same issue I reported [here](https://github.com/Microsoft/TypeScript/issues/7198). The Windows version of the compiler has problems with exclude items that are file paths. The duplicate definition errors are a result of typings/main.d.ts not being excluded properly. A cleanish workaround is to exclude the whole typings directory, and reference the main.d.ts or browser.d.ts file in another file committed to source control. E.g:

typings.d.ts:
`/// <reference path="typings\main.d.ts" />`

**Comment by birick** [comment] 2016-02-24 16:44
Ok - wasn't sure if the issue you had applied to subfolder references as well.  I see there was a patch put out last night - if I get some time after work I may give it a shot and see if it resolves it.  Another workaround would be writing a gulp task to delete the unneeded file and subfolder - not sure which I would choose atm.

**Comment by mhegazy** [comment] 2016-02-24 18:15
thanks @BigDataSamuli. this indeed is a duplicate of #7198. @birick give the [nightly nuget package](https://github.com/Microsoft/TypeScript/wiki/Nightly-drops#using-nuget-with-msbuild) a try and let us know if it still reproduces.

**Closed by mhegazy** 2016-02-24 18:15 UTC

**Comment by birick** [comment] 2016-02-25 05:05
I tried the nightly package - no luck.  Most of the instructions I could find were for non-vNext projects, so I couldn't find any Import statements relevant in the xproj file.  After downloading and building the NuGet package, nothing changed.

**Comment by mhegazy** [comment] 2016-02-25 17:31
can you share your project?

**Comment by birick** [comment] 2016-02-26 02:52
Sure.  I am attaching the project called AngularBase.  It is a stock vNext Asp Net Website based on the current templates with the following changes (it's an experiment in setting up Angular2+Typescript+vNext and the project hasn't been heavily modified)

1. Removed readme.html
2. Added a collection of npm packages focusing around Angular2
3. Added a scripts folder where I would plan to put typescript files
4. Added a number of tasks to gulpfile.js
5. Added Personal Notes.txt just to keep some notes on this
6. Added tsconfig.json
7. Added typings.json

[AngularBase.zip](https://github.com/Microsoft/TypeScript/files/147602/AngularBase.zip)
