### ISSUE TITLE
No differentiation between `ArrayBuffer` and `Uint8Array`

### ISSUE THREAD

**Issue by lucacasonato** [microsoft/TypeScript#55032] opened 2023-07-15 20:50 UTC
# Bug Report

TypeScript can not differentiate between `ArrayBuffer` and `Uint8Array` (or other typed array types).

```ts
const t: ArrayBuffer = new Uint8Array();
```

### 🔎 Search Terms

- Structural typing
- Brand checking

Related #50714, #42534, #202

### 🙁 Actual behavior

TypeScript checks the program above, and reports no errors.

### 🙂 Expected behavior

An error should be thrown, because in many APIs, passing a `Uint8Array` rather than an `ArrayBuffer` will throw or result in runtime errors.

### Cause and proposed fix

The cause for this issue is TypeScript's structural typing. Within the type structure, `ArrayBuffer` is a subset of structure of `Uint8Array`. Because of this, TypeScript considers `Uint8Array` a valid `ArrayBuffer` type.

To fix this, we should consider adding a brand to the `Uint8Array` and `ArrayBuffer` interfaces, such as the following:

```ts
interface ArrayBuffer {
  readonly [Symbol.toStringTag]: "ArrayBuffer";
}
```

This _may_ be an issue when subclassing `ArrayBuffer`, because the subclass may have a different `Symbol.toStringTag`

**Comment by MartinJohns** [comment] 2023-07-15 20:55
Duplicate of https://github.com/microsoft/TypeScript/issues/42534, https://github.com/microsoft/TypeScript/issues/31311, and ultimately https://github.com/microsoft/TypeScript/issues/202.

See also this comment: https://github.com/microsoft/TypeScript/issues/31311#issuecomment-490690695

**Comment by lucacasonato** [comment] 2023-07-15 20:57
Oh I missed that comment. How unfortunate. I wonder if the breakage actually uncovers real user error...

**Closed** 2023-07-20 01:31 UTC
Labels: Duplicate
