### ISSUE TITLE
JSDoc syntax for optional parameter causes description to disappear from intellisense

### ISSUE THREAD

**Issue by wrummler** [Microsoft/TypeScript#9971] opened 2016-07-26 22:04 UTC
**TypeScript Version:**  within VS Code 1.3.1

JSDoc syntax for optional parameters (e.g. `{number} [parameterName] Description`) seems to cause the parameter description to not get picked up for intellisense.

Closure Compiler syntax (e.g. `{number=} parameterName Description`) does not cause the same problem.

**Code**

```js
/**
 * @param {number} [x] Description
 */
function foo (x) { }
```

**Expected behavior:**

Hovering over `x` in the function declaration shows "Description", like this:

![description-for-required-parameter](https://cloud.githubusercontent.com/assets/3069355/17156398/44d21238-534f-11e6-9ee8-299da1c2bee5.png)

**Actual behavior:** 

![no-description-for-optional-parameter](https://cloud.githubusercontent.com/assets/3069355/17156406/4dda960c-534f-11e6-90c1-d7ff9e5af3de.png)

**Comment by sandersn** [comment] 2016-07-26 22:39
Never mind, it repros for both javascript and typescript.

**Comment by sandersn** [comment] 2016-08-30 20:53
Duplicate of #6810

**Closed by sandersn** 2016-08-30 20:53 UTC
Labels: Bug
