### ISSUE TITLE
Inferred type in a foreach on a tuple can't be assigned to an overloaded function

### ISSUE THREAD

**Issue by wnadurski** [microsoft/TypeScript#42575] opened 2021-02-01 08:01 UTC
# Bug Report
### 🔎 Search Terms
overloaded function union foreach 

### 🕗 Version & Regression Information
4.1.3
- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.3#code/MYewdgzgLgBBIFsCmUAWBLMBzCMC8MA2gFAxkwBEAZugE7QUA0p5FESoYAJhcQLowAhrk7Rio2PGRpMWAFyUa9KBRgAfSu0498mjuB7EjVAK5hgUdOBimwACiXQF1OgwCUC6LVkBuYrYsrMBszB1coZy0DCg84KG9sPwDLa1sw5WcZWh5Yr19-M0DU0McIoTAAT1z42RgAbxYyWhQTWmDS4gBfY1CXZRiC+ykUDGw3YmGZbAgAOioQWgBRQWBUOzsprDd8AD56xpgAekOYAElJQQrcNEFYAHJNu5h0XBAqGCgKgAckRXDVDRsfTcJgwABGJlg6FgzS+CyguEEwSQtFoC3KFQA7pcDmlNuNOuMJogRrJZvMlis1htRltdvtyEcTqcYMAkUIIBB0FhgndJrSnlAQDAHt8kG8PgKDhIhApPj8JZtdH0GNLwNBwXKxYracqoiC1ZBYMAtQr3kqCPzZAdjjAAHLClFo+i40LAImM20AIUhz3eLOEXJ5IseH2FaF+orNktkd0Yz1gmPQABtkzBYfDyjAnQsZnnDRquKbxebdQRNjaTotUQtXfYuAS3EA)

### 💻 Code

```ts
const somethings = [
    "first",
    "second"
] as const
const something: "first" | "second" = "second"


function fun(first: "first"): string;
function fun(first: "second"): string;
function fun(first: "third"): string;
function fun(first: any): string {
    return first
}

fun("first")
fun(something)
somethings.forEach((thing) => {
    // It says that 'thing' is of type "first" | "second", but it reports an error anyway
    fun(thing)
})

somethings.forEach((thing) => {
    // I can assign 'something' to 'typeof thing'
    const a: typeof thing = "first"
    const b: typeof thing = "second"
    const c: typeof thing = something
    // No errors
    fun(c)

    // But if I assign 'thing' to the 'typeof thing', it will report an error...
    const d: typeof thing = thing
    // Error
    fun(d)
})
```

### 🙁 Actual behavior

The IDE says that the type of a value inside a foreach is a union and this union is the same exact one as defined somewhere else, and this union type is applicable to an overloaded function, but the function invocation with this argument reports an error.
The interesting fact is that the error actually doesn't depend on the type, but an actual value (lines 28 and 33)

### 🙂 Expected behavior

There should be no error

**Comment by MartinJohns** [comment] 2021-02-01 08:21
Duplicate of #39885 / #1805.

**Closed** 2021-02-04 18:00 UTC
Labels: Duplicate
