### ISSUE TITLE
Bug: Mapped type does not satisfy the constraint it just matched in conditional type

### ISSUE THREAD

**Issue by krryan** [Microsoft/TypeScript#21729] opened 2018-02-07 17:55 UTC
Further testing has demonstrated that generics and type inference are not relevant here; have the same problem without using those.

Updated simplified example:
```ts
interface Foo { foo: string; }
interface Bar { bar: string; }
type FooBar = Foo | Bar;
declare interface ExtractFooBar<FB extends FooBar> {}

type Extracted<Struct> = {
    [K in keyof Struct]: Struct[K] extends FooBar ? ExtractFooBar<Struct[K]> : Struct[K];
/*                                                                ^^^^^^^^^
Type 'Struct[K]' does not satisfy the constraint 'FooBar'.
  Type 'Struct[K]' is not assignable to type 'Bar'. */
}
```

Note that in a non-map situation, this works fine: `T extends FooBar ? ExtractFooBar<T> : T` compiles without a problem. So my guess is that this is related to the type-indexing, whatever stores the constraint on `T` here does not store the same constraint for `Struct[K]`, or the re-use of `Struct[K]` retrieves a "new" type through the indexing, and TS doesn't see the relation between the first `Struct[K]` and the second even though `K` has not changed.

For more on my use-case and the original problem I had, the original post:

> Our project uses a concept we call "fields," which are places where data can go from user input, and fields can be set or unset, valid or invalid, etc. And we have a big union of field types representing every combination of those things for different types of fields, and that's called `Field<T>`. The different types of fields encode a lot of behavior, but one of the things we have in there is that, for example, if a field is required, and we have no value for it, then we have an invalid field—period, there is no type in the union that allows required, unset, and valid to exist simultaneously in the same field. That gives us a lot of type-safety.
> 
> When it comes time to save a form full of these fields, we want to make sure all fields match the types that are valid. I attempted to use conditional types for this, first to determine what the appropriate type for a given field should be (e.g. given a union of required fields, the savable version is the one that's required, set, and valid), calling that `SavableField<F, T>`. That works fine. Then came the next step: a `SavableForm<Form>` type that maps all properties, and if a property is a field, replacing it with its `SavableField` variant, and otherwise just leaves it as-is. That does not work.
> 
> A simplified example:
> 
> ```ts
> declare type Field<T>; // Field is a big union of generic types
> declare type SavableField<F extends Field<T>, T>; // big series of type conditions to select "savable" types from the union
> 
> export type SavableForm<Form> = {
>     [K in keyof Form]: Form[K] extends Field<infer T> ? SavableField<Form[K], T> : Form[K];
> /*                                                                   ^^^^^^^
> Type 'Form[K]' does not satisfy the constraint 'Field<T>'.
>   Type 'Form[K]' is not assignable to type 'ReadOnlyAlwaysSetInvalidForged<T>'. */
> }
> ```
> 
> `Form[K]` here has literally just passed the `extends Field<infer T>` condition, so it failing to be assignable to `Field<T>` is very confusing/surprising here. (For the record, `ReadOnlyAlwaysSetInvalidForged<T>` is the member of the `Field<T>` union that happens to be considered "last" by TS, as seen by hovering over the definition of `Field<T>`.)

Noting that the bug happens only with mapped types allowed a workaround for the above issue, as well:

```ts
type SavableIfFieldBounceIfNot<P> = P extends Field<infer T> ? SavableField<P, T> : P;

export type SavableForm<Form> = {
    [K in keyof Form]: SavableIfFieldBounceIfNot<Form[K]>;
}
```

**Comment by mhegazy** [comment] 2018-02-07 18:00
Looks like a duplicate of #21631 and should be fixed by https://github.com/Microsoft/TypeScript/pull/21709

**Comment by krryan** [comment] 2018-02-07 18:09
Looks related, but I'm not certain it's fixed by #21709. That talks about constraints on the inferred parameter, but my issue seems more closely related to constraints _on the type we're asking conditions of_ which is subtly different (maybe?). By the I mean, in the example there you see `T` getting passed, `T`'s constraints being updated by the fix. But I am worried about `Form[K]`. In my actual use-case, `T` _doesn't_ have any constraints on it; our fields can be a field of any type.

**Comment by mhegazy** [comment] 2018-02-07 18:22
you are right.. sorry did not read the example carefully.. we still need to do something similar for index access types.

**Comment by krryan** [comment] 2018-02-07 18:25
I updated my initial example to be simpler, and removed the mention of generics and type inference since you get the bug even without those confounding factors. I am still interested in those cases, though, obviously.

**Comment by mhegazy** [comment] 2018-02-07 19:28
You can do this today using an indirection. the checking done in #21709 works on type parameters and not indexed access types. and that is why your `SavableIfFieldBounceIfNot` works. 

I agree with you that this looks like a bug, and i think we should fix it.

**Comment by krryan** [comment] 2018-02-07 19:31
Right, that's what I meant by including the `SavableIfFieldBounceIfNot` bit on the end there. With a workaround, much lower priority, but yeah, definitely a bug—I wouldn't have realized the workaround existed without you pointing out #21709.

**Closed** 2018-03-21 22:18 UTC
Labels: Bug, Fixed
