### ISSUE TITLE
An argument without a type confuses automatic type inference for a generic function

### ISSUE THREAD

**Issue by oleg-slapdash** [microsoft/TypeScript#47242] opened 2021-12-24 17:14 UTC
# Bug Report

I am sorry for a dry bug report, I am not sure why it happens and what area of TS this is concerned but I have a repro in hopes this would be fixed. 

### 🔎 Search Terms

No idea, really.

### 🕗 Version & Regression Information
- This is the behavior in every version I tried.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=3&ts=4.6.0-dev.20211224#code/KYDwDg9gTgLgBAYwgOwM7wCYEMZbgXjgG8BYAKDjgDMsBLAG1QC5Et0AVATzGAApSKlOAHphcAHIB5dgFEWASXg0GqOLSpwYAC1qqqAV2QIYtFHC1s4WZFagBzfQFtgyGOSFxU+gEaoEUWm9gFl4AfSoICABKAgA+OH5qSJYAIm8sKBS4AF8rVSQ0GCiAGnchKGBUCHoAN2CE7FwY-HjGrAA6CIhSwWySsoB3aABrZlYObj4BD1EJaTk4RTghqFG1DQyHZ1c1VWQITGAqWmRgDDLKL19-QPreZvjErtT0zJy8xBR0fsFKCqranc2g84G1OpEepQ+j1sgBucjkUCQWDUQzGUw2BBsGBcHgAHnYAAUsJx6BAsBhYrx-tU6lAWNNPD4-AEgiFnnBvJF6MBrCCiSSyRT4YIaYCAPwhMAZFwwFgC0nkjAg6ycEV9YhlCowfRQGxiunq8hAA)

### 💻 Code

```ts
export const data = {
  fails: castType({
    // NOTE: It fails if this function has an argument
    subscribe: (_foo) => ({ foo: "bar" } as const),
    resolve: (data) => data.foo,
  }),
  works: castType({
    // NOTE: It works if argument is not defined
    subscribe: () => ({ foo: "bar" } as const),
    resolve: (data) => data.foo,
  }),
};

export function castType<TPayload>(resolver: {
  subscribe: (foo: boolean) => TPayload;
  resolve?: (parent: TPayload) => any;
}) {
  return resolver;
}

```

### 🙁 Actual behavior

It fails to determine the correct type in a generic if an argument is specified.

### 🙂 Expected behavior

It should determine the correct types for a generic.

**Comment by MartinJohns** [comment] 2021-12-24 17:23
Duplicate of #43371.

**Closed** 2022-01-03 16:39 UTC
Labels: Duplicate
