### ISSUE TITLE
getTypeAliasInstantiation crashes with TypeError: Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by AWare** [microsoft/TypeScript#49458] opened 2022-06-09 16:34 UTC
# Bug Report

### 🔎 Search Terms
getTypeAliasInstantiation

### 🕗 Version & Regression Information
between 4.7.0-dev.20220322 and 4.7.0-dev.20220323

- This is a crash
- This changed between versions 4.7.0-dev.20220322 and 4.7.0-dev.20220323

### ⏯ Playground Link

I haven't been able to extract a minimal test case, as it crashed, without emitting any errors. If you have any advice for how to instrument tsc to help find the location, I'd be happy to run through it and attempt to find a minimal test case.

Unfortunately, I am not able to share the repo.

### 🙁 Actual behaviour

```/Users/alex/code/application-v3/node_modules/.pnpm/typescript@4.7.0-dev.20220325/node_modules/typescript/lib/tsc.js:96258
                throw e;
                ^

TypeError: Cannot read properties of undefined (reading 'get')
    at getTypeAliasInstantiation (/Users/alex/code/application-v3/node_modules/.pnpm/typescript@4.7.0-dev.20220325/node_modules/typescript/lib/tsc.js:49357:54)
    at createMarkerType (/Users/alex/code/application-v3/node_modules/.pnpm/typescript@4.7.0-dev.20220325/node_modules/typescript/lib/tsc.js:55238:17)
    at _loop_22 (/Users/alex/code/application-v3/node_modules/.pnpm/typescript@4.7.0-dev.20220325/node_modules/typescript/lib/tsc.js:55206:45)
    at getVariancesWorker (/Users/alex/code/application-v3/node_modules/.pnpm/typescript@4.7.0-dev.20220325/node_modules/typescript/lib/tsc.js:55227:21)
    at getVariances (/Users/alex/code/application-v3/node_modules/.pnpm/typescript@4.7.0-dev.20220325/node_modules/typescript/lib/tsc.js:55184:17)
    at structuredTypeRelatedTo (/Users/alex/code/application-v3/node_modules/.pnpm/typescript@4.7.0-dev.20220325/node_modules/typescript/lib/tsc.js:54392:41)
    at recursiveTypeRelatedTo (/Users/alex/code/application-v3/node_modules/.pnpm/typescript@4.7.0-dev.20220325/node_modules/typescript/lib/tsc.js:53996:30)
    at isRelatedTo (/Users/alex/code/application-v3/node_modules/.pnpm/typescript@4.7.0-dev.20220325/node_modules/typescript/lib/tsc.js:53580:25)
    at isPropertySymbolTypeRelated (/Users/alex/code/application-v3/node_modules/.pnpm/typescript@4.7.0-dev.20220325/node_modules/typescript/lib/tsc.js:54595:24)
    at propertyRelatedTo (/Users/alex/code/application-v3/node_modules/.pnpm/typescript@4.7.0-dev.20220325/node_modules/typescript/lib/tsc.js:54631:31)```

### 🙂 Expected behaviour

for typescript not to crash

**Comment by AWare** [comment] 2022-06-13 13:11
I haven't quite found the offending code yet, but it seems to be related to the optional variance stuff going on in fastify. I'll make a corresponding second issue there if I can pin it down.

**Comment by unicornware** [comment] 2022-11-27 21:37
@RyanCavanaugh i'm experiencing a similar issue with `typescript@4.9.3`. it seems to be somewhat related to using `skipLibCheck` (i'm using the option in another `tsconfig` file, but not getting an error):

```sh
4:28:40 lex@FLEXBOOK :: ~/Projects/FLDV/FLDV-P026 ‹main*› » tsc -p tsconfig.typecheck.json                                                                                                   2 ↵
/Users/lex/Projects/FLDV/FLDV-P026/node_modules/typescript/lib/tsc.js:99606
                throw e;
                ^

TypeError: Cannot read properties of undefined (reading 'get')
    at getTypeAliasInstantiation (/Users/lex/Projects/FLDV/FLDV-P026/node_modules/typescript/lib/tsc.js:51153:54)
    at createMarkerType (/Users/lex/Projects/FLDV/FLDV-P026/node_modules/typescript/lib/tsc.js:57171:17)
    at _loop_23 (/Users/lex/Projects/FLDV/FLDV-P026/node_modules/typescript/lib/tsc.js:57136:45)
    at getVariancesWorker (/Users/lex/Projects/FLDV/FLDV-P026/node_modules/typescript/lib/tsc.js:57157:21)
    at getVariances (/Users/lex/Projects/FLDV/FLDV-P026/node_modules/typescript/lib/tsc.js:57114:17)
    at structuredTypeRelatedToWorker (/Users/lex/Projects/FLDV/FLDV-P026/node_modules/typescript/lib/tsc.js:56334:41)
    at structuredTypeRelatedTo (/Users/lex/Projects/FLDV/FLDV-P026/node_modules/typescript/lib/tsc.js:55955:30)
    at recursiveTypeRelatedTo (/Users/lex/Projects/FLDV/FLDV-P026/node_modules/typescript/lib/tsc.js:55924:30)
    at isRelatedTo (/Users/lex/Projects/FLDV/FLDV-P026/node_modules/typescript/lib/tsc.js:55506:25)
    at checkTypeRelatedTo (/Users/lex/Projects/FLDV/FLDV-P026/node_modules/typescript/lib/tsc.js:55166:26)
```

would i take the same steps you outlined above to narrow down the issue further?

**Comment by powerpete** [comment] 2022-12-08 10:07
I've the same issue. I reproduce it with the attached project. [buggy.zip](https://github.com/microsoft/TypeScript/files/10184314/buggy.zip)

The line 
```
var chart: Chart<"scatter"> = undefined;
chart = new Chart(ctx, { type: 'scatter', data: { datasets: [] } });
```
will force typescript to throw the "TypeError: Cannot read ..." exception.

[buggy.zip](https://github.com/microsoft/TypeScript/files/10184314/buggy.zip)

**Comment by luixo** [comment] 2023-02-16 14:23
I stumbled upon this error as well and decided to dig a little to the core of the problem.
I found out there is a clash of some sort in case of an import of an augmented type.

I made a repo with a not really minimal reproduction, but as good as possible: https://github.com/luixo/ts-bug-example
The base of the repo is a `create-next-app` initial commit.
I added a `next-i18next` package that uses type `AppProps` from `next` package.
`AppProps` relies on `AppPropsType` which relies on `AppInitialProps` type which I augment in `pages/_app.tsx` file.

Running `npm i && npx tsc` in the repo outputs given error.
Any of those actions will remove the error:
- Removing `AppInitialProps` augmentation
- Removing `appWithTranslation` from usage (say, moving it to `console.log(appWithTranslation)`) effectively factoring it out from calculations
- Changing `Props extends NextJsAppProps<any>` to `Props extends any` in `next-i18next/dist/types/appWithTranslation.d.ts` to `Props extends any` effectively factoring out the problem type from calculations

Unfortunately, I was not able to create a smaller reproducible case.

I believe this it not the expected behaviour of the `tsc` and I hope this issue will get addressed.

**Possible temporary workaround:**
Discover the exact type that gives you an error:
```diff
function getTypeAliasInstantiation(symbol, typeArguments, aliasSymbol, aliasTypeArguments) {
  var type = getDeclaredTypeOfSymbol(symbol);
  if (type === intrinsicMarkerType && intrinsicTypeKinds.has(symbol.escapedName) && typeArguments && typeArguments.length === 1) {
  return getStringMappingType(symbol, typeArguments[0]);
  }
  var links = getSymbolLinks(symbol);
+   if (!links.instantiations) {
+     console.log('Links', links.escapedName, links);
+   }
  var typeParameters = links.typeParameters;
  var id = getTypeListId(typeArguments) + getAliasId(aliasSymbol, aliasTypeArguments);
```
..and remove the augmentation.

**Comment by huw** [comment] 2023-05-07 20:05
@luixo Thank you! [In my case](https://github.com/vasturiano/react-force-graph/pull/435#issuecomment-1537525268), an upstream dependency updated a type I was importing to add a type parameter, meaning that I was attempting to augment a generic type without supplying the parameters correctly. Easy to solve once I knew what was going on!

**Comment by RyanCavanaugh** [comment] 2024-03-20 21:10
We don't have a solid/minimal repro yet; one would be greatly appreciated

**Comment by luixo** [comment] 2024-03-20 23:03
> We don't have a solid/minimal repro yet; one would be greatly appreciated

Can you please specify what [my reproduction](https://github.com/luixo/ts-bug-example) (mentioned above) lacks?

**Comment by RyanCavanaugh** [comment] 2024-03-20 23:16
16 files plus whatever `npm` brings in is not minimal

**Comment by LelouBil** [comment] 2024-04-10 19:54
Here is a repro with only typescript as a dependency, and the smallest file content I could find https://github.com/LelouBil/typescript-bug-repro

**Comment by LelouBil** [comment] 2024-04-10 19:54
I didn't manage to simplify the example further

**Closed** 2024-04-14 01:33 UTC
Labels: Duplicate
