### ISSUE TITLE
Type inference in Array<T>.filter()

### ISSUE THREAD

**Issue by LouisBoucquet** [microsoft/TypeScript#46987] opened 2021-12-02 09:36 UTC
# Bug Report

### 🔎 Search Terms

Type inferance

### 🕗 Version & Regression Information

This bug occurs in version 4.5.2;

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAIglgY2gXigRigHygJi1AZnwBZ8BWfANgG4AoWgMwFcA7BYOAexajgGd4SABQsAXFBZMAtgCMIAJwCU4nv1iJoAb1pRdUeRGBN5PANpoANLisErxK2SuUAugDo4bADZMAJhD4iinQAvvQI3HzAUACG8vLRICrScvKmzlCo5lY4NnYOTlYA7FYAHFYAnFYADM50tLHxIDp6rgxwnsAKIhkAfLwCGoGKzbqtnPIAotEIABbdyH3aestQAPSrEv1QnGBQoJBQAAaSsgqHIyvrUAAqM2pqwDPQrBAAHpDsED5QcjPRAG5ceQXZZXW7QTzRWQ+aK8HhtDoKKB8GacJieb4eBhIuDAPh7cDQBjyThSI78QQQc7LYJBegNBIXVrtTryISBFRbSm9fqUoZMhjjKazeaLEF6K6qfE7AkHQ6U6l6Wl1BlNZbMxFsikaYbqwWTaZzHgLKBLFa6SVbGX7aDyjSK3TKoA)

### 💻 Code

```ts
function tIsOfTypeP(t: T): t is P {
	// Logic
}

const array: T[] = [...];

// newArray is still of type T[]
const newArray = array
	.filter(t => tIsOfTypeP(t));
```

### 🙁 Actual behavior

The variable `newArray` is of type `Array<T>`.

### 🙂 Expected behavior

The variable `newArray` is of type `Array<P>`. You know that only elements will remain of type `P`.

**Comment by MartinJohns** [comment] 2021-12-02 09:52
Duplicate of #20218. You're not passing a type guard function to `filter`.

**Comment by LouisBoucquet** [comment] 2021-12-02 09:57
Shouldn't the type of the lambda become a typeguard?

**Comment by MartinJohns** [comment] 2021-12-02 10:07
No.

**Closed** 2021-12-05 18:00 UTC
Labels: Duplicate
