### ISSUE TITLE
Javascript tsconfig file (tsconfig.js)

### ISSUE THREAD

**Issue by DanielHoffmann** [microsoft/TypeScript#39441] opened 2020-07-06 13:23 UTC
## Search Terms

config
tsconfig.json

## Suggestion

It would be very helpful if typescript followed the conventions of pretty much every other JS-stack tool and allowed the configuration to be done as a javascript file so they can more easily be manipulated.
For example all these tools (and many more) already accept configuration files to be javascript:

Prettier -> .prettierrc.js
Jest -> jest.config.js
Webpack -> webpack.config.js
eslint -> .eslintrc.js
styleling -> .stylelintrc.js
lint-staged -> lint-staged.config.js

My suggestion is for typescript tsconfig resolver to look for a `tsconfig.js` file if available, if so `require()` it and use the exported values as configuration. If that file is not available then follow the current resolver rules for tsconfig.json.

## Use Cases

- Filesystem introspection
- Better environment variable toggling of options
- Easier extensibility of configurations
- Easier building of tools that include typescript

## Examples

```js
module.exports = {
  "includes": [path.resolve(__dirname, process.env.SOURCE_DIR)],
  ...
}
```

```js
const config = { ... }
if (NODE_ENV === 'development') config.compilerOptions.noUnusedLocals = false
module.exports = config
```

Right now it is impossible to merge arrays when using the "extends" option of tsconfig.json. If the configuration were javascript files this would be feasible:

```js
const originalConfig = require('some-dep/config/tsconfig.json')
const path = require('path')
module.exports = {
  ...originalConfig,
  includes: [...originalConfig.includes,  path.resolve(__dirname, './mytypes/')]
} 
```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-07-06 13:40
Duplicate of #30400. Used search terms: `tsconfig.js`

**Closed** 2020-07-06 19:24 UTC
Labels: Duplicate

**Comment by StJohn3D** [comment] 2022-02-11 02:26
#30400 should have been marked a duplicate of this one. This issue does a much better job of explaining why we need this feature. one tsconfig.json simply doesn't cut it for more complicated projects.

**Comment by SrBrahma** [comment] 2022-05-09 21:21
Up. Having all the setup json as js files is the future already happening.

**Comment by faeb187** [comment] 2023-03-24 02:53
@qodesmith actually it's not impossible, it's very easy:

1. Just read the file using `fs.readfile` or `fs.readfileSync` with option `{ encoding: "utf8" }`
2. JSON.parse the string you get
3. update your JSON however you like dynamically
4. JSON.stringify before...
5. write the file back where it belongs using `fs.writeFile` or `fs.writeFileSync`

I was looking if `.js` is allowed but it's easy to just generate your config files (all of them) then add a CLI or whatever and configure or set some default templates, etc.

**Comment by Tofandel** [comment] 2023-06-20 15:44
@faeb187 That would not work if your config includes non encodable content, like functions, which would be the use case for a `.js`  file

**Comment by qodesmith** [comment] 2023-06-24 11:06
@Tofandel What @faeb187 is suggesting is manipulating JSON data by reading, updating, and re-writing the data back to disk. Since the source of truth would be a JSON file, there wouldn't be any non-encodable content. It's essentially the same [solution](https://github.com/qodesmith/cna-vite-setup/blob/main/createAliasMap.ts#L66) I came up with a while ago, but it's still a hack.
