### ISSUE TITLE
A signature using union type does not produce the same invalid usages than a signature using union types

### ISSUE THREAD

**Issue by stof** [microsoft/TypeScript#46873] opened 2021-11-19 20:30 UTC
# Bug Report

The handbook recomments using overloads rather than a union when only the argument type changes. But this does not produce the same behavior regarding catching extra object literal properties.

### 🔎 Search Terms

overload, argument, union

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type system

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEoHMBGBhA9gG1ymQG8AoZZKCAEwC5kQBXAW02gG4Ll1qIQGzNp26Z8TCINbsoXSnHwAHABZwA-FOGyyAXzJlQkWIhQAJAM748hYuUrKJmmXOTm4YJlHfBcAxtJFKfGB0ZTAQCHNzJ0DkBRV1GO09A3BoeCRkUwB3HAIiUm4HSX8tF2zlYEgIqKSXMUQAaxro0udueNUNNpE9CAAPRSIwZAR8OCjkAGUJ82siAHkAN2hCOBpCygRfczAoJgQwIgAKbZsGDDybAEoXbZBd-cOTs6IGCyt8qFvue8eDo5QU5fd65ebfO47PYAl4gtBYcHIAA+WUsiJROSuRGum0oyAA9PjkAAVBYAEQW3D0fUGw1G40mMyi4IAqiAfCBcX9oc8ga8oBcEV9kajPjYRZjwTi7HjCSTyZTKNSyBFstNZuDlqtcOtjjLqPRkAAmACsJoANNxeBB+AxTRbROISvbLfZHMgAAyu1zuTzeXwML3cYKhcKRVoARg9QZ01xVEDVTLmXzZHL13ANdrN3uttuN2cd7pdRXdQcobg8XjAHMD3pDYRaDCjMeuQA)

### 💻 Code

```ts
interface RgbColor {
  red: number;
  green: number;
  blue: number;
  alpha?: number;
}

interface HslColor {
  hue: number;
  saturation: number;
  lightness: number;
  alpha?: number;
}

interface HwbColor {
  hue: number;
  whiteness: number;
  blackness: number;
  alpha?: number;
}
export class SassColorOverload {
  constructor(color: RgbColor);
  constructor(color: HslColor);
  constructor(color: HwbColor);
  constructor(color: RgbColor | HslColor | HwbColor) {
    // TODO
  }
}
export class SassColorUnion {
  constructor(color: RgbColor | HslColor | HwbColor) {
    // TODO
  }
}
new SassColorOverload({
  red: 255,
  green: 255,
  blue: 255,
  hue: 0,
  saturation: 0,
  lightness: 100,
})
new SassColorUnion({
  red: 255,
  green: 255,
  blue: 255,
  hue: 0,
  saturation: 0,
  lightness: 100,
})
```

### 🙁 Actual behavior

SassColorOverload reports an invalid object literal, but SassColorUnion does not.

### 🙂 Expected behavior

Same behavior regarding catching extra properties in object literals when using the union type, especially given that this is the recommended implementation in https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#use-union-types

**Comment by MartinJohns** [comment] 2021-11-19 20:39
Duplicate of #20863.

**Closed** 2021-11-25 18:00 UTC
Labels: Duplicate
