### ISSUE TITLE
Interface allow to call method with mandatory argument

### ISSUE THREAD

**Issue by sosoba** [microsoft/TypeScript#41929] opened 2020-12-11 13:12 UTC
**TypeScript Version:**  4.1.2

**Search Terms:** interface optional parameters

**Code**

```ts
interface I {
    m(p?:string):string;
}

class C implements I {
    m(p:string){
        return p;
    }
}

const i : I = new C();
i.m();
```

**Expected behavior:** 
`Class 'C' incorrectly implements interface 'I'.`

**Actual behavior:**

No errors

**Comment by MartinJohns** [comment] 2020-12-11 13:29
That wouldn't be type-safe.

    const i: I = new C();
    i.m();

**Comment by MartinJohns** [comment] 2020-12-11 16:06
Duplicate of #38019.

**Closed** 2020-12-13 18:00 UTC
Labels: Duplicate
