### ISSUE TITLE
Can't assign to conditional generic within generic

### ISSUE THREAD

**Issue by ayroblu** [microsoft/TypeScript#41837] opened 2020-12-06 08:24 UTC
Hi I was trying to do something much more complicated than this with conditionals without success, I was reducing the issue down and down and I found this, which I find a bit weird, I was hoping someone might be able to enlighten me of a work around?

**TypeScript Version:**  v4.1.2

**Search Terms:**
assign to conditional generic

**Code**

```ts
type Param<T> = T extends undefined ? {
    first: string,
} : {
    first: string,
}
function run<T>(param: T) {
    const p: Param<T> = {
        first: 'hi'
    }
    return p;
}
```

**Expected behavior:**
No type error

**Actual behavior:**
type error

**Playground Link:** 
[link here](https://www.typescriptlang.org/play?#code/C4TwDgpgBACghgJzgWwDwBUB8UC8V1QQAewEAdgCYDOUArpRAGYCWZEFUA-FAN4BQUQVBYIqwAFxQxCVgHMANHwC+USfyHDmoiVOAyyC5X0b0AxsGYB7MlAT0MmABRhEKSegCUvAUNPWxUGCS8EhoWLjeGhoiYpIA5AAWzHE+gkqpthDAtAg2YADcykA)

**Related Issues:** 
I couldn't find any, sorry if this is a well known problem / duplicate!

**Comment by MartinJohns** [comment] 2020-12-06 09:21
Duplicate of #26933. Search terms used: `assign conditional`

**Closed** 2020-12-06 09:25 UTC
