### ISSUE TITLE
Visual Studio 2015 Update 3 crashes when debugging Typescript

### ISSUE THREAD

**Issue by mwchan** [Microsoft/TypeScript#9544] opened 2016-07-07 02:31 UTC
**TypeScript Version:**  1.8.10

**VS 2015**
Update 3

**Expected behavior:**
I was able to debug Typescript in VS 2015 Update 2. Since updating to Update 3, my solution keeps crashing.

**Actual behavior:** 
VS 2015 crashes as soon as I insert one or more breakpoints.

```ts
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at TypeScriptDebugEngine.SymbolProvider.DecodedSourceMapDataItem.MapJsSourcePosition(Microsoft.VisualStudio.Debugger.Symbols.DkmTextSpan, Microsoft.VisualStudio.Debugger.Script.DkmScriptDocument)
   at TypeScriptDebugEngine.SymbolProvider.DocumentResolver.Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmSymbolDocumentSpanQuery.FindSymbols(Microsoft.VisualStudio.Debugger.Symbols.DkmResolvedDocument, Microsoft.VisualStudio.Debugger.Symbols.DkmTextSpan, System.String, Microsoft.VisualStudio.Debugger.Symbols.DkmSourcePosition[] ByRef)
   at Microsoft.VisualStudio.Debugger.EntryPoint.IDkmSymbolDocumentSpanQuery_FindSymbols(IntPtr, IntPtr, IntPtr, IntPtr, NativeXapiArray ByRef, NativeXapiArray ByRef)


```

**Comment by mhegazy** [comment] 2016-07-07 02:40
Duplicate of https://github.com/Microsoft/TypeScript/issues/9524

**Closed by mhegazy** 2016-07-07 02:40 UTC

**Comment by stefan505** [comment] 2016-07-14 19:31
Don't this is a dup, refer to my issue as well: #9544
