### ISSUE TITLE
TypeScript can't parse optional object when assigned to a variable 

### ISSUE THREAD

**Issue by bnbarak** [microsoft/TypeScript#36510] opened 2020-01-29 19:41 UTC
**TypeScript Version:**  3.7.5

**Code**
```ts
type A = { b?:  { c?: number } }
const a: A = { b: {c: 123} };
const isSafe = a && a.b && a.b.c
// if (a && a.b && a.b.c) { // <= works
if (isSafe) { // <= breaks
    console.log(a.b.c); // (TS 2532) Object is possibly 'undefined'.
}
```
**Expected behavior:**
TS should check if `isSafe` protects against `undefined`
**Actual behavior:**
TS doesn't check `isSafe` 

<details><summary><b>Output</b></summary>

```ts
"use strict";
const a = { b: { c: 123 } };
const isSafe = a && a.b && a.b.c;
// if (a && a.b && a.b.c) { // <= works
if (isSafe) { // <= breaks
    console.log(a.b.c); // (TS 2532) Object is possibly 'undefined'.
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=2&pc=22#)

**Comment by nmain100** [comment] 2020-01-29 20:18
Duplicate of https://github.com/microsoft/TypeScript/issues/12184

**Closed** 2020-02-06 18:00 UTC
Labels: Duplicate
