### ISSUE TITLE
Suggestion/feature request - enforce static properties/fields 

### ISSUE THREAD

**Issue by ORESoftware** [microsoft/TypeScript#21976] opened 2018-02-15 20:15 UTC
I added this question on SO:

is there a way to enforce static class properties? https://stackoverflow.com/questions/48813814/enforce-static-member-in-class-using-enum

It doesn't look like there is a way to do what I want to do, hence the feature request.

**Code**

```ts

declare enum Foods {
  CHERRY = 'CHERRY',
  LETTUCE = 'LETTUCE',
  JERKY = 'JERKY'
}

declare abstract class ForceFoods {
  static food : Foods
}

export class MyFoods implements ForceFoods {
  static food = Foods.CHERRY;  // if I omit this line, tsc will not complain
}

```

**Expected behavior:**
I was hoping tsc could enforce static properties to be defined

**Actual behavior:**
I don't currently believe tsc can enforce static properties

**Comment by mhegazy** [comment] 2018-02-15 20:31
Now that we have `--strictPropertyInitialization` and `!` operator for asserting definite assignment, we should consider making an uninitialized static property an error.

That does not solve your problem thought.. it will give you an error on `ForceFoods` as well as on `MyFoods`.  I think you are looking for  https://github.com/Microsoft/TypeScript/issues/14600 for abstract static properties/methods.

**Comment by RyanCavanaugh** [comment] 2021-06-24 18:31
This is a little jumbled up with `abstract` but it seems like this is a duplicate of #27899

**Closed by RyanCavanaugh** 2021-06-24 18:31 UTC
Labels: In Discussion, Suggestion
