### ISSUE TITLE
Suggestion: allow set accessor to accept null as a way to set default value.

### ISSUE THREAD

**Issue by luz-alphacode** [Microsoft/TypeScript#28834] opened 2018-12-04 04:55 UTC
I know this may sound duplicate with previous suggestion about get/set accessors to have have different type. BUT, the following case is really common in many js library and is widely use by many js developers:

```
class Foo {

  private _key;

  get key(): number {
    return this._key;
  }
  
  set items(value: number | null) {
    this._key = value !== null ? value : 3
  }
}
```

Use different types for get/set accessors may not be a good practice, but allow a simple way to set to default value is not bad; without null, you have to strictly expose the default value to use, I don't think this is a friendly for large project.
Many exists library use null to set to default value, without the support, the declaration file become somehow not accurate.
if the declaration of property is non-null, you must read the code to find the default value.
If the declaration of property is T | null, then you have to use ! assertion every time you use this property, because the getter always return a non null value.
Will you please consider this as a feature？

**Comment by MartinJohns** [comment] 2018-12-04 05:55
Duplicate of the rejected #2521.

**Comment by AnyhowStep** [comment] 2018-12-04 07:36
Seems like a code smell.

```ts
x.foo = null;
console.log(x.foo); //Expect `null`, received "qwerty"
```

If you want to make it so you can make a field goes back to its "default" value, why not a more descriptive method?

```ts
x.reinitFoo();
x.resetFoo();
x.clearFoo();
x.setDefaultFoo();
```

**Comment by luz-alphacode** [comment] 2018-12-04 07:56
Well, I could do that when I write my own code.
But the question is there are some exist JavaScript libraries use this strategy, and the declaration cannot describe such condition, then I have to figure out the default value myself and assign it by setter.
Yes, I could write some wrapper function to reset the value, but it's doesn't feel good.

Null check and same-typed a getter/setter is a strong feature that protect the code from bugs, but as a enhanced language of JavaScript, I really think that preserve some JavaScript style is nice. And I don't think the nullable setter is bad practice. The interface is clear and non-nullable getter ensure type safety.

I don't agree the original discussion about different types, and it doesn't give enough reason for this particular suggestion. That's why I opened this new discussion. Actually I think this is a discussion about the practice of 'null', if the team have a strong reason, I think I could live with that. Thank you for your apply.

**Closed** 2018-12-04 19:22 UTC
Labels: Duplicate
