### ISSUE TITLE
ts.NodeArray<T> no longer mixes well with Array.isArray()

### ISSUE THREAD

**Issue by SlurpTheo** [Microsoft/TypeScript#19886] opened 2017-11-09 22:02 UTC
**TypeScript Version:**  2.6.1

**Code**

```ts
const arr: ts.NodeArray<ts.VariableDeclaration> = node as ts.NodeArray<ts.VariableDeclaration>;
if (Array.isArray(arr)) {
	const x = arr;
	const y = x[0].getText;	// getText() no longer in IntelliSense
}
```

**Expected behavior:**
Control-flow analysis used to know that `x` was an array of `ts.VariableDeclaration`.

**Actual behavior:**
Now it's all mixed-up (intersectioned with `any[]`).

![image](https://user-images.githubusercontent.com/5269716/32632248-823a654e-c568-11e7-934d-342013b7f155.png)

**Comment by andy-ms** [comment] 2017-11-10 01:17
Looks like a duplicate of #17002. (`NodeArray` inherits from `ReadonlyArray`)

**Comment by SlurpTheo** [comment] 2017-11-10 04:02
@andy-ms It does look very similar only my code was not an issue in 2.4.2 (#17002 says it was happening in 2.4.1).

**Comment by andy-ms** [comment] 2017-11-10 14:35
Oh, that's because `ts.NodeArray` was mutable back then.

**Closed** 2017-11-27 18:38 UTC
Labels: Duplicate
