### ISSUE TITLE
element.style[key] = value throws implicit any error

### ISSUE THREAD

**Issue by appsforartists** [Microsoft/TypeScript#11914] opened 2016-10-28 01:25 UTC
**TypeScript Version:**  2.0.3

**Code**

```ts
const propName: string = 'position';

const div = document.getElementsByTagName('div')[0];
div.style[propName] = 'absolute';
```

**Expected behavior:**
Styles are dynamically settable with dictionary access; the above snippet should set `position: absolute` on `div`

**Actual behavior:** 
Throws 
```
ERROR(4,1): : Element implicitly has an 'any' type because index expression is not of type 'number'.
```
Must use format `style.setProperty(key, value);`

**Comment by aluanhaddad** [comment] 2016-10-29 05:21
This behavior is correct. Specifically, `element.style` is typed as a `CSSStyleDeclaration` which is declared in `lib.dom.d.ts` as
```typescript
interface CSSStyleDeclaration {
    [index: number]: string;
}
```

**Comment by akarzazi** [comment] 2016-10-30 00:17
From W3C : https://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-CSSStyleDeclaration
```

// Introduced in DOM Level 2:
interface CSSStyleDeclaration {
           attribute DOMString        cssText;
                                        // raises(DOMException) on setting

  DOMString          getPropertyValue(in DOMString propertyName);
  CSSValue           getPropertyCSSValue(in DOMString propertyName);
  DOMString          removeProperty(in DOMString propertyName)
                                        raises(DOMException);
  DOMString          getPropertyPriority(in DOMString propertyName);
  void               setProperty(in DOMString propertyName, 
                                 in DOMString value, 
                                 in DOMString priority)
                                        raises(DOMException);
  readonly attribute unsigned long    length;
  DOMString          item(in unsigned long index);
  readonly attribute CSSRule          parentRule;
};
```
There is no string indexer on CSSStyleDeclaration.
The statement : `div.style["position"]` is a JavaScript alternative way to access the property `div.style.position`,  which is not possible in TypeScript.

**Comment by mhegazy** [comment] 2016-10-30 02:27
> The statement : div.style["position"] is a JavaScript alternative way to access the property div.style.position, which is not possible in TypeScript.

This is not accurate. both `div.style["position"]` and `div.style.position` work as intended. both resolve to the same property and both have the type `string`.

This is another manifestation of https://github.com/Microsoft/TypeScript/issues/7730 which is basically that:

```ts
const position = "position";
div.style[position] // should behave the same way as div.style["position"]
```

**Comment by mhegazy** [comment] 2016-10-30 02:28
this should be handled correctelly when https://github.com/Microsoft/TypeScript/pull/11929 is merged in.

**Comment by mhegazy** [comment] 2016-10-30 02:29
closing in favor of #7730.

**Closed by mhegazy** 2016-10-30 02:29 UTC
Labels: Duplicate

**Comment by akarzazi** [comment] 2016-10-30 13:36
My bad, TypeScript seems to handle index notation fine as long as the parameter is a string literal  !

```
const div = document.getElementsByTagName('div')[0];
var a = div.style['position']; // a is string|null;
```
