### ISSUE TITLE
Aliased Promise types behave differently than the original Promise with target es5

### ISSUE THREAD

**Issue by theRobinator** [microsoft/TypeScript#39282] opened 2020-06-26 20:59 UTC
**Search Terms:** promise type, not a valid async function return type in es5/es3, alias type

**Code**

On the latest TS (3.9.2 as of this posting) target set to `es5`, these two code snippets behave differently:

Everything works fine here:

```
async function foo(): Promise<string> {
    return 'hello';
}
```

Adding this type alias breaks it:

```ts
type StringPromise = Promise<string>;

async function foo(): StringPromise {
    return 'hello';
}
```

**Expected behavior:** Adding a type declaration should not affect the behavior of the example. An error should be thrown in both cases or neither.

**Actual behavior:** Adding a type declaration causes the error `Type 'StringPromise' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.`

[Playground Link](https://www.typescriptlang.org/play/?target=1&ssl=5&ssc=6&pln=5&pc=19#code/PTAEFkHsGMGtQIagA4CdIFsCWBnApqNJAHY4AuqArtGZKqDpKGQBYHIA2CAngObqViAEwZ48ORKABEySB24AzLBw5SAdACgQoAHJNiYkbVBCmrXKCwLQ3SJUIJiDZHmhXuoALSeOWAEYa0Fw4EgAK6Nj4oADeAL4aGmTcLqAAyhRYxLzhmLgEALygOZF4ADzkqJm8AHwA3AkIONzE0KAKgjRYJG2QkAAUAJQAXGkZWcV5MRqgM6CoeGSUqE4A5GwqkCv18UA). I added a dummy Promise constructor in there to "polyfill" the lib, but this also reproduces on disk.

**Comment by MartinJohns** [comment] 2020-06-26 22:05
Duplicate of #32574.

**Comment by yortus** [comment] 2020-06-27 03:51
The reason this seems surprising is that for async functions in ES3/ES5, TypeScript takes the identifier in the return type annotation and emits it into the runtime code. It's probably the only case where TS does that.

You can see it in this [playground link](https://www.typescriptlang.org/play/?target=1&ssl=6&ssc=2&pln=1&pc=1#code/C4TwDgpgBAysBOBLAdgcwArwPYFtEGdoBeKTXAiAHnwRVQD4BuAKABMIBjAGwEN5oOWZDVi00ZPIQBcUAN7IIAdyiUAKvQAUAShkSKa+gF9mzHvhDIOUAGYBXS8ERCbWLNplwk47JOizmUIFQ-MC28MhQAOQAFhBcXFiRLIZAA). `StringPromise` appears in a value position in the emitted code, and changing or removing the type annotation will change the emitted code.

**Closed** 2020-07-03 18:00 UTC
Labels: Duplicate
