### ISSUE TITLE
Type checker works on union types but it's buggy.

### ISSUE THREAD

**Issue by Arian94** [microsoft/TypeScript#41069] opened 2020-10-12 20:40 UTC
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```
type Row =
    | { [iAmNumber: number]: number; }
    | { iAmString: number; b: number; }

let obj: Row = {
    iAmString: 45 // The bug is here. The 'obj' has ONE property and it's iAmString which is a string itself. 
                  // The Row type has an iAmNumber key with the type number.
                  // That is where the issue is. The type checker should either tell us to change the key (iAmString) to a number (eg 58) 
                  // or ask us to add the property 'b'.
    // b: 457,
};

console.log(obj);
```

**Expected behavior:**
Scenario 1: ERROR: Type '{ iAmString: number; }' is not assignable to type '{ [iAmNumber: number]: number; }'.
Correction: { 58: 45; }
Scenario 2: ERROR: Type '{ iAmString: number; }' is missing the following properties from type '{ iAmString: number; b: number; c: number; d: number; }': b, c, d.
Correction: { iAmString: 45; b: 34; }
**Actual behavior:**
 No error is published. [LOG]: { "iAmString": 45 }
**Playground Link:** 
https://www.typescriptlang.org/play?#code/C4TwDgpgBASg9gdygXgFBQ1APlA3lAbQEsBBAWwDkBXMgIwgCcAuKAOxvoYF0X27GA3FAC+6TDnykyAZWAMirAOa8OgqLRX8GQ0Zmx4oU2fKWbOQjW1XaoAYzNrd4g0bkLlVrRYc37n81AAJj4iAqioADYQwFBwtABWLPBIyHhiGK4mHgAsAKxQAPQFUAAqABbQtFSKhgDOUBUMEAB0pRVQAORx8R0NAIb1APIUAKJQYAxwkAygUH2sgYbAHfWZ7lAIZUS2ZXVzULVuSku1EBEAZq3l0MlQoJD99fOG5NRaUADWECAbRMC7-2g92gfE4zXSekhUIwRTafRiRHqm0YQPaiNqVGgiKu7WBdgqti+DAOZTgVAiiwgf0adzOESgVHqwDgUCarD6ZCx5GM62ZL0o1lixIGHwZTJZfUCi0B40m01mHVoHXBelhljyAHYADSoYRhVC2OCsWpwKLNCJwRQACm6AEoBEA
**Related Issues:**

**Comment by MartinJohns** [comment] 2020-10-12 20:54
Duplicate of #41043.

**Comment by RyanCavanaugh** [comment] 2020-10-12 20:54
This is the intended behavior. Excess property checking is a rule that is only enforced on fresh objects; it is not part of the type system *per se*.

`{ iAmString: 45 }` *is* a valid `{ [iAmNumber: number]: number; }`: All of its numeric-named properties are numbers. "Extra" properties are allowed during this validity check.

Separately, we do check for "extra" properties on this object literal, and we do see that there is a corresponding property, so it isn't "extra" according to this check.

**Closed** 2020-10-15 20:00 UTC
Labels: Working as Intended
