### ISSUE TITLE
JavaScript: types allowed when decorator is added to a JavaScript file

### ISSUE THREAD

**Issue by sberan** [Microsoft/TypeScript#11800] opened 2016-10-23 13:58 UTC
**TypeScript Version:** nightly (2.1.0-dev.201xxxxx)

When I add a decorator to a .js file, I no longer get the `'types' can only be used in a .ts file` error. Is this expected behavior?

**Code**

``` js

@SomeDecorator
class SomeClass {
    foo(x:number) { 

    }
}

```

**Expected behavior:**
`'types' can only be used in a .ts file`

**Actual behavior:** 
no errors

**Comment by mhegazy** [comment] 2016-10-23 16:49
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/11719. @jramsay should have a fix for this in soon.

**Comment by mhegazy** [comment] 2016-10-23 19:14
looking at this again, do not think this is a duplicate.

**Comment by sberan** [comment] 2016-10-23 19:21
No errors are being produced by tsc at all, so I don't think it's a dupe. To be clear, I actually like this behavior, but I'm not sure if I should rely on it working this way.

**Comment by mhegazy** [comment] 2016-10-23 20:44
It is a bug. So I would not rely on this behavior.

**Closed** 2016-11-10 18:37 UTC
Labels: Bug, Fixed
