### ISSUE TITLE
Generic function argument lost when passed to a generic identity function

### ISSUE THREAD

**Issue by invliD** [microsoft/TypeScript#38007] opened 2020-04-16 15:31 UTC
**TypeScript Version:**  3.8.3

**Search Terms:**
* generic function
* "instantiated with a different subtype of constraint"

**Expected behavior:**
In TypeScript 3.7.5, the function returned by `define` is of type `<E>(argument: E, somethingElse: { key: E; }) => (a: string) => number`.

**Actual behavior:**
In TypeScript 3.8.3, the function returned by `define` is of type `(argument: E, somethingElse: { key: E; }) => (a: string) => number`.

I believe this behavior is a regression, since a function with generic argument types without itself being generic doesn't really make sense, and the coded did work with TS 3.7. My assumption here is that TS doesn't understand the two `E`s actually _must_ be the same type.

**Code**
```ts
// In reality there are more arguments of an Action and they have complex types
type Action<R> = (a: string) => R;

// The purpose of this method is to allow definitions of action creators without explicitly typing an
// Action's argument types every time
function define<C extends (...args: any[]) => Action<any>>(creator: C): C {
    return creator;
}

// Type inferred in TS 3.7.5: <E>(argument: E, somethingElse: { key: E; }) => (a: string) => number
// Type inferred in TS 3.8.3: (argument: E, somethingElse: { key: E; }) => (a: string) => number
const definedAction = define(
    <E>(
        argument: E,
        somethingElse: { key: E }
    ) => (a /* a has a properly inferred type */) => 5,
);

const extra = { test: "" };

definedAction(extra, { key: extra });
/*
Error only in TS 3.8.3:
Argument of type '{ test: string; }' is not assignable to parameter of type 'E'.
  '{ test: string; }' is assignable to the constraint of type 'E', but 'E' could be instantiated with a different subtype of constraint '{}'.(2345)
*/

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
// The purpose of this method is to allow definitions of action creators without explicitly typing an
// Action's argument types every time
function define(creator) {
    return creator;
}
// Type inferred in TS 3.7.5: <E>(argument: E, somethingElse: { key: E; }) => (a: string) => number
// Type inferred in TS 3.8.3: (argument: E, somethingElse: { key: E; }) => (a: string) => number
const definedAction = define((argument, somethingElse) => (a /* a has a properly inferred type */) => 5);
const extra = { test: "" };
definedAction(extra, { key: extra });
/*
Error only in TS 3.8.3:
Argument of type '{ test: string; }' is not assignable to parameter of type 'E'.
  '{ test: string; }' is assignable to the constraint of type 'E', but 'E' could be instantiated with a different subtype of constraint '{}'.(2345)
*/

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=27&pc=1#code/PTAEEkDtQJwUwIYBsCWAXAnqNALO9QECBbAewKIHMBXYuSNAZ1FIDNDoBBAYzRVOgJIAE2x4sOBADc4obqWIAHJHAAe2DIriMAUJi2gefAQB4ASgD5QAXlAAKBAC5QjNDBSRKAShtWzAbh0dEFAAFTxQRWoYRVJGWTYxFGY6XFJRZOxSQiQkUgB3UGE4Vg90fkhmRIReCrl4BDRyZnz0HFJqNFA1ZRRudCQsfQ9KDmCwIwqAcmYqWnou-W1umRghlDodVmpIWoEiko84EwBhbtU0emFmOwA6e6pGZyEMAG0AXR9rK0nTF4sLHZuA0mjBnCcvODQABvHSgeGwOBoaLQYGIUGBAC+QRCoU0sg8rHw8Ay0FCAGVQABmW4AdluAFZnCYAKKAuZ0BjOFkAGhcCiROBGLKQ8Wc0NAAGs4Bhuf5QJivlYHM5XO5PErQJBaAAjfDjML40CE4lwUlhSk0gActypzgcMBonLQ3L5jAFuGForg4qlMrlCs1KpcbhGmu1xD1MB08kqXWKpUgZt+0FsCaOdjhCNZgKzCIRHIWrrz+f5qSFnhFYphftloBZCpLQYQoGAACpCKBJLNIjBSFoYINjZAiTASRoDG3gJqGTydF5AjGBK5zm4W7YJZdXM4AEQ7hWL9NJ4QpuxqNd8iXSuvnmAtxWBds6Flj8gsSBDjwW6m3G12nScI68wMCw7BLKAUybtoLohuqlDypiUzGswkCkF0CCMIwKCUJACA6ioWSREQCCpPgoETrIUwslMtxZpB2DQaqoaeAhSGZBhWE4XhBFNGIsixmqCAeF0iTgVRUx8jqnQQdRcgdEgoh6sOrhCHwjRmqArS4J2wgoKwo4LC41A6uBiQCWuwkQdCiG3HYABMVIACwMl4OhTjoQA)

**Related issues:**
* #30134

**Comment by ahejlsberg** [comment] 2020-04-17 17:21
Duplicate of #37110. Fixed in #37811. No longer repros in nightly build.

**Closed** 2020-04-17 17:21 UTC
Labels: Duplicate
