### ISSUE TITLE
`[...(T[] & { length: N; })]` be instantiated as `[T, T, T, ..., T]`(N T's in total)

### ISSUE THREAD

**Issue by KingMario** [microsoft/TypeScript#55772] opened 2023-09-18 12:13 UTC
### 🔍 Search Terms

`Array` `Type` `At Least` `Elements` `Generic`

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Declare an array with at least limited N elements (N = 3) is easy like:

```typescript
type ArrayWith3PlusElements<T> = T[] & {
  0: T;
  1: T;
  2: T;
}
```

But when `N` is arbitury, generic support is required.

Please add feature that can declare an array with at least N elements using generic like this:

```typescript
type ArrayWithNElements<T, N extends number> = T[] & {
  length: N;
};

type MyArray3 = ArrayWithNElements<number, 3>; // Array with 3 elements of type number

const arr01: MyArray3 = [1, 2, 3]; // Valid
const arr02: MyArray3 = [1, 2, 3, 4]; // Error: Array does not have 3 elements
const arr03: MyArray3 = [1, 2]; // Error: Array does not have 3 elements

type ArrayWithNPlusElements<T, N extends number> = [...ArrayWithNElements<T, N>, ...T[]];

type MyArray3Plus = ArrayWithNPlusElements<number, 3>; // Array with at least 3 elements of type number

const arr11: MyArray3Plus = [1, 2, 3]; // Valid
const arr12: MyArray3Plus = [1, 2, 3, 4]; // Valid
const arr13: MyArray3Plus = [1, 2]; // Expected to be error but actually valid: Array does not have at least 3 elements
```

**That is, rest elements(...) operation of `ArrayWithNElements<T, N>` in `ArrayWithNPlusElements<T, N>` should effect in the type instantiation. For simplicity, instantiation is converted for ArrayWithNElements<T, N> only when the ... operation acts on it.**

### 📃 Motivating Example

1. Validation: By enforcing a minimum number of elements in an array, you can ensure that the array meets certain requirements or constraints. For example, you might want to validate that an array has at least N elements before performing certain operations on it.

2. API Contracts: When designing APIs, you may want to specify that an array parameter should have a minimum length. This can help prevent errors or unexpected behavior when the array is used within the API.

3. Performance Optimization: In some cases, having a minimum number of elements in an array can improve performance. For example, if you know that an algorithm requires at least N elements to work efficiently, you can enforce this constraint in the type system to ensure that the algorithm is only used with arrays of sufficient length.

4. Code Clarity: By explicitly stating the minimum number of elements in an array type, you can make the code more self-documenting and easier to understand for other developers. It provides a clear indication of the expected array length and can help prevent mistakes or misunderstandings.

Overall, declaring a generic array type with at least N elements can help improve code correctness, maintainability, and performance in certain scenarios.

### 💻 Use Cases

1. What do you want to use this for?

The ability to define a generic array type with a minimum number of elements would be useful in scenarios where you want to ensure that an array meets certain requirements or constraints. For example, you might want to enforce that an array has at least N elements before performing certain operations on it.

2. What shortcomings exist with current approaches?

The current approach in TypeScript does not support defining a type with a specific number of elements in an array. This limitation makes it challenging to enforce a minimum number of elements in an array type directly.

3. What workarounds are you using in the meantime?

In the absence of native TypeScript support, you can consider using runtime checks or custom validation functions to ensure that an array has a minimum number of elements. These checks can be performed at runtime using conditional statements or utility functions. While this approach does not provide compile-time type safety, it can help validate the array length during runtime execution.

**Comment by MartinJohns** [comment] 2023-09-18 12:17
Duplicate of #54740.

**Comment by KingMario** [comment] 2023-09-18 12:20
> Duplicate of #54740.

I'm sorry but this is for **at least** N elements, not **exactly** N elements.

**Comment by MartinJohns** [comment] 2023-09-18 12:23
True, but that's more or less the same. 🤷‍♂️ Just `[T, T, T, ...T[]]` instead of `[T, T, T]`.

**Comment by KingMario** [comment] 2023-09-18 12:25
> True, but that's more or less the same. 🤷‍♂️ Just `[T, T, T, ...T[]]` instead of `[T, T, T]`.
> 
> Also relevant: #55746

But this requires N to be generic.

**Comment by MartinJohns** [comment] 2023-09-18 12:31
I have no idea what you mean with that comment.

Regardless, you can still just adapt the solution from the linked issue:

```typescript
type TupleAtLeastMap<T> = {
  0: [...T[]],
  1: [T, ...T[]],
  2: [T, T, ...T[]],
  3: [T, T, T, ...T[]]
  // go as far as you need to
}
type TupleAtLeastN<N extends keyof TupleAtLeastMap<unknown>, T> = TupleAtLeastMap<T>[N];

type MyArray3 = TupleAtLeastN<3, number>;

const arr01: MyArray3 = [1, 2, 3]; // Valid
const arr02: MyArray3 = [1, 2, 3, 4]; // Error: Array does not have 3 elements
const arr03: MyArray3 = [1, 2]; // Error: Array does not have 3 elements
```

The team is not going to add extra functionality or a utility type for this (as per the issues I linked).

**Comment by KingMario** [comment] 2023-09-18 12:34
What I want is a declaration with two parameter T and N, where N extends number, and If you want declare an array with at least N elements. If N is 10,000, you don't have to write a TupleAtLeastMap for over 10,000 lines first.

**Comment by MartinJohns** [comment] 2023-09-18 12:40
I understand that. And I linked you an issue where someone requests **almost** the same, and the team explicitly declines the feature request. What makes you think your "Tuple at least N" issue is any different than the "Tuple exact N" issue?

Anyhow, I provided you the next best solution, and now I'm outta here. ✌️

**Comment by KingMario** [comment] 2023-09-18 13:14
@MartinJohns Thanks.

Tuple exact N can be declared generically with parameter T and N like this and TypeScript can validate any variable declared as such type:

```typescript
type ArrayWithNElements<T, N extends number> = T[] & {
  length: N;
};
```

**Comment by KingMario** [comment] 2023-09-18 13:27
Giving this buggy behavior codes could express what I required more clearly:

```typescript
type ArrayWithNElements<T, N extends number> = readonly T[] & {
  length: N;
};

type NewArrayWithNElements<T, N extends number> = readonly [...ArrayWithNElements<T, N>];

type MyNumberArray = NewArrayWithNElements<number, 3>;

const arr11: MyNumberArray = [1, 2, 3]; // Valid
const arr12: MyNumberArray = [1, 2, 3, 4]; // Expected to be error but actually valid: Array does not have 3 elements
const arr13: MyNumberArray = [1, 3]; // Expected to be error but actually valid: Array does not have 3 elements
```

vs:

```typescript
type ArrayWithNElements<T, N extends number> = readonly T[] & {
  length: N;
};

type MyArray3 = ArrayWithNElements<number, 3>; // Array with 3 elements of type number

const arr01: MyArray3 = [1, 2, 3]; // Valid
const arr02: MyArray3 = [1, 2, 3, 4]; // Error: Array does not have 3 elements
const arr03: MyArray3 = [1, 2]; // Error: Array does not have 3 elements
```

**Closed** 2023-09-21 01:24 UTC
Labels: Suggestion, Declined
