### ISSUE TITLE
Narrowing does not apply to array member / object element but should

### ISSUE THREAD

**Issue by wbt** [microsoft/TypeScript#48227] opened 2022-03-11 20:30 UTC
# Bug Report
### 🔎 Search Terms
narrowing array member object element

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about "Common "Bugs" That Aren't Bugs" and "Common Feature Requests"

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBFCeAHApgZQIYDNkClUDF0BLAGwgEkwAVVGAXhkwFcxgojwAKIsRJqAIIAnIengAuGJwDk0mAB8YAEXRRkASgDaAXQA0MUCOQRE4ACY8A5gDl0AW2OToQqzvUwA3gCgAkCWSwQsZMJLCSHpo8ZsgAHk5QLmCW2pIqagC+9J7pANy+mCBCnP6wUbEwPBW8-MKi8O7ePj5EmNzVgiJikWDRMdowAIR0DLINvk1BECFQmoaTpj1Wtg4Q3b3a-Qw8fB11a7HaeU3pvic+QVBMQmAwk9N5J6CQsADuhQDW6EIgLGZZzKx2FxtjVOhIpLIFMpVBodPo5sYFhYkstHDBnK5tGM-AFbsFQjBwvs4uiElYUtCMlkPLl8oViriyjEqlUdrUxNifE9oHBkHZTKIhPAAGroEhMZBZEG7LpMw7jFqcNT8wpfEViiWDYYwUaecbnfEzBEmcxLezGYkbLLKgVq0Xi5BHHxnM4XK43O6hB5AA)

### 💻 Code
```ts
const typeSafeJSFailsInTS = function(inputArray: ('' | Date)[], correspondingNames: string[]) {
	let result : {[index: string]: Date} = {};
	for(let index in inputArray) {
		if(inputArray[index] !== '') {
			result[correspondingNames[index]] = inputArray[index];
		}
	}
	return result;
}
const workaround = function(inputArray: ('' | Date)[], correspondingNames: string[]) {
	let result : {[index: string]: Date} = {};
	for(let index in inputArray) {
		const temporaryValue = inputArray[index];
		if(temporaryValue !== '') {
			result[correspondingNames[index]] = temporaryValue;
		}
	}
	return result;
}
```

### 🙁 Actual behavior

Error on line 5 (the most indented line): 
> Type '"" | Date' is not assignable to type 'Date'.  Type 'string' is not assignable to type 'Date'. ts(2322)

This is wrong because it's inside a conditional block that narrows out the empty-string type from `inputArray[index]`. 

### 🙂 Expected behavior

The first example works just fine, with narrowing of the type working just as it does in the second. 

### Related issues
I don’t think this is a duplicate of #9998, despite [how common duplicates are](https://github.com/microsoft/TypeScript/issues/48183). This isn’t about other functions modifying the state or possibly expanding the type of a variable beyond a narrowing; there aren’t even multiple function calls involved.  It’s not asynchronous, which was [recently held](https://github.com/microsoft/TypeScript/issues/48148#issuecomment-1061025652) to be a distinguishing feature of #9998. 

I don’t think this is a duplicate of #18758 which is about narrowing the type of the parent based on the type/presence of deeper members, which is more complicated than what’s sought here, which is narrowing a specific member of an array rather than its parent.

**Comment by MartinJohns** [comment] 2022-03-11 20:33
Duplicate of #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.

**Closed** 2022-03-11 20:34 UTC
