### ISSUE TITLE
Template strings and keyword colorization

### ISSUE THREAD

**Issue by DickvdBrink** [Microsoft/TypeScript#1716] opened 2015-01-18 15:44 UTC
See screenshot, only happens after the `${num}` stuff
Running VS 2013

Because I didn't have an ending `*/` the whole file is now shown as a comment

![capture](https://cloud.githubusercontent.com/assets/765657/5792975/b93ef542-9f31-11e4-9c87-d4cf4ee69f67.PNG)

**Comment by DanielRosenwasser** [comment] 2015-01-18 19:53
Known issue and duplicate of #1477 and #1698. Unfortunately this won't work in VS2013 but it does for VS2015.

**Closed** 2015-01-18 19:53 UTC
Labels: Duplicate

**Comment by DanielRosenwasser** [comment] 2015-01-20 02:22
@DickvdBrink if you're still interested, there's a partial fix here: https://github.com/Microsoft/TypeScript/issues/1698#issuecomment-70594428

**Comment by DanielRosenwasser** [comment] 2015-02-13 22:09
A fix is now in `master`.

**Comment by DickvdBrink** [comment] 2015-04-03 12:53
Wow, I didn't saw this until today xD Thanks @DanielRosenwasser

**Comment by DanielRosenwasser** [comment] 2015-04-03 18:22
You're very welcome! Did you just see the change with 1.5-alpha?

**Comment by DickvdBrink** [comment] 2015-04-07 19:38
Yes, I made a build myself and the above one was fixed! Thanks!
