### ISSUE TITLE
instanceof-guard-based narrowing of sum types produces the type "never"

### ISSUE THREAD

**Issue by pbazant** [Microsoft/TypeScript#17789] opened 2017-08-14 22:23 UTC
**TypeScript Version:**  TS 2.4
**Code**

```ts
class C1 {
    foo: number;
}

class C2 {
    foo: number;
    bar: number;
}

function f_not_C2(a: C1 | C2) {
    if (!(a instanceof C2)) {
        a.foo; // a has type C1, so only foo is available
    }
}

function f_not_C1(a: C1 | C2) {
    if (!(a instanceof C1)) {
        a; // a should have type C2, but has type never!
    }
}
```
**Expected behavior:**
The variable "a" in f_not_C1(...) should have type C2.
**Actual behavior:**
The variable "a" in f_not_C1(...) has type never, making all properties unavailable.

**Comment by jcalz** [comment] 2017-08-15 02:06
Duplicate of #10934 and many others.  TypeScript's lack of nominal typing (#202) causes `instanceof` to behave oddly.  Workarounds include adding some optional property to the classes to help TypeScript distinguish them:

```ts
class C1 {
    __brand?: 'C1'
    foo: number;
}

class C2 {
    __brand?: 'C2'
    foo: number;
    bar: number;
}
```
function f_not_C1(a: C1 | C2) {
    if (!(a instanceof C1)) {
        a; // a is C2 now
    }
}
```

**Comment by mhegazy** [comment] 2017-08-30 20:08
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-08-30 20:08 UTC
Labels: Duplicate
