### ISSUE TITLE
Compiler crash on some functions with self-referential types

### ISSUE THREAD

**Issue by garybernhardt** [microsoft/TypeScript#52757] opened 2023-02-14 20:11 UTC
# Bug Report

### 🔎 Search Terms

"Maximum call stack size exceeded". There are many issues referencing this, but most seem like different bugs from this, and I don't see any that have a simple repro like I provide here.

### 🕗 Version & Regression Information

I tested in these versions:

* Untestable in 4.6.4 and earlier (the repro code causes a syntax error)
* Fails in 4.7.4.
* Fails in 4.8.4.
* **Fails in 4.9.5 (current release as of this report)**
* **Fails in 5.0.0-dev.20230214 (current "next" as of this report)**

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4#code/GYVwdgxgLglg9mABMAPAFQHwAoCGAnAcwGcAuRKATwAcBTOYZdDAShLUQG9E8aoQ8k+YgG5EAXyA) Load it up, hit "Run", then look at your browser's dev console to see that the compiler blew the stack.

### 💻 Code

```ts
function f<T>(args: typeof f<T>):T { return args; }
```

### 🙁 Actual behavior

The compiler itself throws `RangeError: Maximum call stack size exceeded`. E.g.:

```text
$ cat temp.ts
function f<T>(args: typeof f<T>):T { return args; }
$ npx tsc temp.ts
/Users/grb/proj/execprog/node_modules/typescript/lib/tsc.js:99612
                throw e;
                ^

RangeError: Maximum call stack size exceeded
```

### 🙂 Expected behavior

The code either compiles or gives a type error.

**Comment by jakebailey** [comment] 2023-02-16 04:04
It's been noted that this is partially a dupe of #51202, which has its own PR on #51214 (but needs more tests to cover this issue).

**Closed** 2023-02-17 19:31 UTC
Labels: Bug, Fix Available

**Comment by garybernhardt** [comment] 2023-02-17 21:36
Thanks for the quick resolution @jakebailey!
