### ISSUE TITLE
Named exports missing from CommonJS module compiled with TS 4.4 and importHelpers: true

### ISSUE THREAD

**Issue by maxholman** [microsoft/TypeScript#45813] opened 2021-09-10 09:36 UTC
# Bug Report

### 🔎 Search Terms

SyntaxError: Named export not found. The requested module is a CommonJS module, which may not support all module.exports as named exports,  esm, exports, __exportStar, tslib

### 🕗 Version & Regression Information

- This changed between versions 4.4 and 4.3

### ⏯ Playground Link

Playground links demonstrate the difference in compiled output between versions

[Playground link with relevant code (4.4)](https://www.typescriptlang.org/play?importHelpers=true&module=1&ts=4.4.2#code/KYDwDg9gTgLgBAKjgMyhAtnA5MgzlgbiA)

[Playground link with relevant code (4.3)](https://www.typescriptlang.org/play?importHelpers=true&module=1&ts=4.3.5#code/KYDwDg9gTgLgBAKjgMyhAtnA5MgzlgbiA)

[Full reproduction repo and instructions](https://github.com/maxholman/ts-4.4-exports)

### 💻 Code

From the above Playground link, 4.4 produces:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
(0, tslib_1.__exportStar)(require("fs"), exports);
```
4.3 produces:
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
tslib_1.__exportStar(require("fs"), exports);
```

Note the use of the comma operator to unbind  `__exportStar`.  This seems to be new in 4.4 via [more indirect calls for imported functions](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#more-compliant-indirect-calls-for-imported-functions) and https://github.com/microsoft/TypeScript/pull/44624

### 🙁 Actual behavior

Named exports are missing when importing a CommonJS module compiled with Typescript 4.4 when `importHelpers` is `true`.

Setting `importHelpers` to false fixes this problem, but may result in a lot of duplicated code via `tslib`

### 🙂 Expected behavior

Named exports should either exist, whether I have `importHelpers` turned on or off.... or would be good this this was specifically documented as a breaking change. 

(possibly) related: https://github.com/microsoft/TypeScript/issues/45189

**Comment by StanislavKharchenko** [comment] 2021-09-20 14:32
I second concerned about this.
What is the reason of such breaking changes in 4.4 version?

**Comment by guybedford** [comment] 2021-10-18 21:19
@andrewbranch thanks for the analysis here. We can add a fix, but the project there was always supposed to be stabilized and frozen due to the risk of Node.js versions giving different exports being a highly undebuggable experience for users. I'm still tending towards not pushing a fix for this reason but happy to discuss further in that issue.

**Comment by andrewbranch** [comment] 2021-10-20 23:41
@guybedford that’s totally reasonable, and I wouldn’t mean to imply that I think cjs-module-lexer has a particular obligation to recognize our output even if it wasn’t frozen. It seems like the expectation is that sometimes you’ll just have to use the default import and access properties off of it. My earlier comment was only meant to convey that on the TS side, we also can’t change, as our old emit was just plain wrong and the new emit fixes bugs. Thanks!

**Comment by paulmillr** [comment] 2021-11-07 20:46
Hey folks, I don't understand. How is changing the imports from `tslib_1.__exportStar()`to `(0, tslib_1.__exportStar)()` useful? It definitely hurts readability. Isn't it a bug to add `0, `?

**Comment by andrewbranch** [comment] 2021-11-08 20:44
No, it is a bug not to add the indirect call. See https://github.com/microsoft/TypeScript/issues/35420.

**Comment by StanislavKharchenko** [comment] 2021-11-19 13:15
@andrewbranch 
Do you have some documentation and changelog regarding this?
There was not clear why this was added.

**Comment by andrewbranch** [comment] 2021-11-19 16:46
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#more-compliant-indirect-calls-for-imported-functions

**Comment by BenSjoberg** [comment] 2021-12-02 22:51
> No, it is a bug not to add the indirect call. See #35420.

Would it be possible to add an exception so that this doesn't occur with functions from tslib? None of the functions in tslib use `this`, so there should be no functional issues.

I know how hacky it sounds, but the maintainer of cjs-module-lexer [is opposed](https://github.com/nodejs/cjs-module-lexer/issues/63#issuecomment-946195973) to updating the exportStar parsing logic in that package. 

The status quo is causing CommonJS packages written in TypeScript to be somewhat fragile when used from ESM. Unless you eschew named imports entirely when using a CommonJS library (which is frustrating since TS still suggests them as auto-imports), you run the risk of your code breaking on a minor or patch update if the developer turns on  turns on importHelpers or just rewrites `export { Foo, Bar } from './baz'` to `export * from './baz'`. IMO, the fact that doing either of those could lead to breaking changes for some users is very unexpected behavior.

**Comment by andrewbranch** [comment] 2021-12-03 18:38
We’ll investigate that 👍

**Closed** 2021-12-08 23:42 UTC
Labels: Needs Investigation

**Comment by BenSjoberg** [comment] 2021-12-09 14:42
Thank you so much! :)

**Comment by trivikr** [comment] 2022-01-21 02:55
Is this issue (and fix) going to be added to the [TypeScript milestones for 4.6.x](https://github.com/microsoft/TypeScript/milestones)?
