### ISSUE TITLE
Getter not functioning properly when overriding the setter

### ISSUE THREAD

**Issue by andrewl913** [microsoft/TypeScript#56336] opened 2023-11-07 20:14 UTC
### 🔎 Search Terms

setter without getter abstract class

overriding a setter on a base class causes the subclass getter to return undefined

The getter not functioning properly when overriding the setter.

### 🕗 Version & Regression Information

Tested on v3, v4, and v5.

The getter not functioning properly when overriding the setter.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/FASwdgLgpgTgZgQwMZQAQAUYHsAmBXJCAZQgWlQG9hVUQcAuVAZwhnAHMBua1MBAWyiMWbMFx4syeJsNYduAX2DAEAIxHIIqJABsETJhmz5CAHiKooAD2hgchzLgLFS5ALxGnhEmSgA+Sh4kLDARZywYAAoAB2xoQigcVAASSWhGIgBKQJolHnYoLTpI7KoaGhhCvBgwVAgACxAmADpU1yhmuh4lGgKtNOkSnPLKiGrahqbWtI6Bpm5c5RomQuZXQYA3BB08ITXRdlKeGkmWtt9mudQPLZ2oBdQlPPBoeGQ0ACEsLABrH3JrLZ7J4TC5fMM+IJZAcHk1VGBofJgHldPpDF9fpYbFA7A5jM5TBi-u0AmVmKs5pFbrtEWIjuVtCEmFgdB0dFh2JEAERELCCZh0KAAWigcDgUEIqHqsA6XMyDxOjTOM0u60MN22uweT2UwVCWlU3x+114UAA7qgiZEKLwBHsuQAVKAsLkAGjWUhkqC5AEFCCANlA3bQGN6AIzBuEI8MAJgAzFzHvLgHrmazmuzOYbfqrPfKgA

### 💻 Code

```ts

interface ProductState {
  id: string;
  name: string;
  status: string;
}

abstract class Product<S extends ProductState = ProductState> {
  constructor(protected $state: S) {
  }

  get id() {
    return this.$state.id
  }
  get status() {
    return this.$state.status;
  }

  set status(value: string) {
    this.$state.status = value;
  }
}

interface BookState extends ProductState {
  name: string;
  isbn: string;
}

class Book extends Product<BookState> {
  set status(value: string) {
    console.log("Some side-effect here.");
    this.$state.status = value;
  }
}

const book = new Book({ name: "Test", status: "Active", id: "1", isbn: "123" });
// Returns undefined
console.log(book.status);
```

### 🙁 Actual behavior

the field `status` returns undefined.

### 🙂 Expected behavior

the field `status` returns "Active".

**Comment by MartinJohns** [comment] 2023-11-07 20:22
Duplicate of #47581.

**Closed** 2023-11-10 01:26 UTC
Labels: Duplicate
