### ISSUE TITLE
Template Literals in Record

### ISSUE THREAD

**Issue by Sharcoux** [microsoft/TypeScript#43618] opened 2021-04-09 17:55 UTC
# Bug Report

### 🔎 Search Terms

Template literals index Record

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Template Literals
- I was unable to test this on prior versions because template literal didn't exist

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210409#code/C4TwDgpgBAkgJgFXNAvFABgEgN4DsCuAtgEYQBOAvgLQ4EnnW1GmU17MPoCwAUAMYB7XAGdgUAJZwAXLETIoaAOQAGVcqpr1mjaoCMigNy9eoSFACCCqACUIgsnAA88JJAA0UUWXG4A5gD5jfiFRKABDGUs0bF4oOKgAbUkAXRlFYAhRRV4KXjCkuGSoAHpiqABRABsIQghcMXFCMErxPnFgSpAoAAsw4XDcKEUw3BBFKFNoUj4w-GFoCAAPMDJM4XEhKAEAMwn5RSx2elYmY8YjlnO6S-Rxmdx0qFIoOYg4CYEJXDglvbNFcyKAB0AAoAOzKACsAGYAJS8IA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.

type IdType = `${number}-${number}-${number}-${number}`
const id: IdType = '0000-0000-0000-0001';

type A = Record<IdType, string>

const a: A = {
    [id]: 'test'
}
a[id] // Element implicitly has an 'any' type because expression of type '`${number}-${number}-${number}-${number}`' can't be used to index type 'A'.(7053)


```

### 🙁 Actual behavior

```
Element implicitly has an 'any' type because expression of type '`${number}-${number}-${number}-${number}`' can't be used to index type 'A'.(7053)
```

### 🙂 Expected behavior

ts be happy, cause I love my ts happy.

**Comment by jcalz** [comment] 2021-04-09 20:43
Duplicate of #42192

**Closed** 2021-04-12 18:00 UTC
Labels: Duplicate
