### ISSUE TITLE
[2.6.0] Crash in tsservice `getCodeFixes` command

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#19462] opened 2017-10-25 03:03 UTC
**TypeScript Version:**  2.6.0-dev.20171019

**Code**

(unknown)

**Expected behavior:**

Compilation/typing errors to show up in the Problems view of VS Code.

**Actual behavior:**

```
[Error  - 1:04:30 PM] 'getCodeFixes' request failed with error.
Error processing request. Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.unescapeLeadingUnderscores (.../node_modules/typescript/lib/tsserver.js:8560:18)
    at Object.getSuggestionForNonexistentSymbol (.../node_modules/typescript/lib/tsserver.js:19551:95)
    at Object.getActionsForCorrectSpelling [as getCodeActions] (.../node_modules/typescript/lib/tsserver.js:73149:38)
    at .../node_modules/typescript/lib/tsserver.js:72873:33
    at Object.forEach (.../node_modules/typescript/lib/tsserver.js:1294:30)
    at Object.getFixes (.../node_modules/typescript/lib/tsserver.js:72872:16)
    at .../node_modules/typescript/lib/tsserver.js:76664:35
    at Object.flatMap (.../node_modules/typescript/lib/tsserver.js:1526:25)
    at Object.getCodeFixesAtPosition (.../node_modules/typescript/lib/tsserver.js:76662:23)
    at IOSession.Session.getCodeFixes (.../node_modules/typescript/lib/tsserver.js:82655:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (.../node_modules/typescript/lib/tsserver.js:81577:61)
    at .../node_modules/typescript/lib/tsserver.js:82799:88
    at IOSession.Session.executeWithRequestId (.../node_modules/typescript/lib/tsserver.js:82790:28)
    at IOSession.Session.executeCommand (.../node_modules/typescript/lib/tsserver.js:82799:33)
    at IOSession.Session.onMessage (.../node_modules/typescript/lib/tsserver.js:82819:35)
    at Interface.<anonymous> (.../node_modules/typescript/lib/tsserver.js:83945:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

I am unsure what caused this to happen, but the `Problems` panel / compilation error highlights became non-functional, typescript-wise, after this crash happened (tslint, etc still worked). Manually restarting the TS Service fixed it; but I did not do it immediately, so it is possible that I did further changes to the code or environment that avoided the crash.

**Comment by DanielRosenwasser** [comment] 2017-10-25 14:58
Looks like a duplicate of #19002

**Comment by mhegazy** [comment] 2017-10-25 16:11
Can you share the tsserver log after this error? have you seen the similar stack before? a repro or any log would be appreciated.

**Comment by mhegazy** [comment] 2017-11-09 21:23
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-11-09 21:23 UTC
Labels: Needs More Info
