### ISSUE TITLE
template literals fail to type check as string literals

### ISSUE THREAD

**Issue by spoonscen** [Microsoft/TypeScript#17595] opened 2017-08-03 20:56 UTC
**TypeScript Version:**  2.4.0

**Code**
```ts
type Foo = 'lol'

const barr: Foo = `lol`
// Type 'string' is not assignable to type '"lol"'.
```

https://www.typescriptlang.org/play/#src=type%20Foo%20%3D%20'lol'%0A%0Aconst%20barr%3A%20Foo%20%3D%20%60lol%60

**Expected behavior:**
```ts
type Foo = 'lol'

const barr: Foo = `lol`
// No error
```

**Actual behavior:**
```ts
type Foo = 'lol'

const barr: Foo = `lol`
// Type 'string' is not assignable to type '"lol"'.
```

**Comment by ikatyang** [comment] 2017-08-04 03:03
Duplicate of #16592.

**Comment by DanielRosenwasser** [comment] 2017-08-04 03:08
Thanks for finding that @ikatyang!

**Closed** 2017-08-10 13:53 UTC
Labels: Duplicate
