### ISSUE TITLE
Parameters of overridden methods are made implicit any when using JSDoc `@override` 

### ISSUE THREAD

**Issue by markcellus** [microsoft/TypeScript#59320] opened 2024-07-17 11:37 UTC
### 🔎 Search Terms

`"jsdoc @override"`
`"@override"`

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about JSDoc comments
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYGwhgzhAEBCkFMDC4rQN4ChPWgegCoCdcDoABABzACcwBbDCAFxoEsA7AcwF9pmAnpQTQS0MuRoJmAVxocY6Fu248xBPCQBmAex0AKQcICUGMdCmz5-IQhJq1mUJBhIAFmxAATFC+gIAD2YEDi8YeAhkVEVRXEJiXHEKHQA3BBp2LztEjW09Q1tTLESLaTkOG2F7TB4gA

### 💻 Code

```ts
class BaseClass {

  /**
   * @param {string} type 
   * @returns {string}
   */
  foo(type) {
    return type
  }
}

class ChildClass extends BaseClass { 
  /**
   * @override
   */
  foo(type) {
    return type
  }
}
```

### 🙁 Actual behavior

The `type` param passed to `ChildClass.foo` does not inherit the `string` type used in the same method of the `BaseClass` and evaluates as implicit `any`

### 🙂 Expected behavior

The `type` param passed to `ChildClass.foo` should inherit the `string` type used in the same method of the `BaseClass`

### Additional information about the issue

This bug is also present when using `@inheritdoc`, which should not be the case.

**Comment by markcellus** [comment] 2024-07-17 11:38
Here's a GIF showing what happens when hovering over the `ChildClass.foo`
![override-not-showing-params-vscode](https://github.com/user-attachments/assets/35717c9e-4622-42ed-bcd5-2780fa8752bd)

**Comment by MartinJohns** [comment] 2024-07-17 11:42
> This is a crash

It isn't. You probably forgot to fill out this section of the issue template.

---

This aligns with the behaviour of TypeScript code. Derived classes don't automatically infer the types based on the base class. This is a duplicate of #23911.

**Comment by markcellus** [comment] 2024-07-17 12:25
> This aligns with the behaviour of TypeScript code. Derived classes don't automatically infer the types based on the base class. This is a duplicate of https://github.com/microsoft/TypeScript/issues/23911.

Yes, TS doesn't _automatically_ infer the types based on the base class. But you probably missed the part when I'm explicitly declaring that it does using `@override`. It's not a duplicate of that issue.

**Comment by MartinJohns** [comment] 2024-07-17 12:37
> But you probably missed the part when I'm explicitly declaring that it does using `@override`.

I did not miss it, I just don't see the significance. You expect the overridden method to automatically infer the argument types as the base, but that's currently not supported, as per the linked issue. That you specify the type with JSDoc instead of TypeScript makes no difference.

> See the [documentation of `@override`](https://jsdoc.app/tags-override) for what it does.

I don't see anything of relevance here either. It doesn't even say that the JSDoc of the parent should be inherited.

**Comment by markcellus** [comment] 2024-07-17 13:20
> You expect the overridden method to automatically infer the argument types as the base, but that's currently not supported

This statement is false as well, because I'm not asking TS to "infer" the arguments. I'm declaring them explicitly. It's no different than if I were to use `BaseClass['foo']` on the `@type` tag. The following apparently works... but it doesn't make much sense that it works, but `@override` or `@inheritdoc` doesn't. 

```js
class BaseClass {
  /**
   * @param {string} type 
   * @returns {string}
   */
  foo(type) {
    return type
  }
}

class ChildClass extends BaseClass { 
  /**
   * @type {BaseClass['foo']}
   */
  foo(type) {
    return type
  }
}
```


So if it's supported there, that's no different than what `@override` should do.

**Comment by snarbies** [comment] 2024-07-17 14:35
Unfortunately, even if this deviates from JSDoc documentation, this is "working as intended". This behavior aligns with the behavior of the `override` keyword. It does go against intuition, hence the linked issue. If the behavior for `override` changes, I would hope and expect `@override` to change with it. As it stands, manual type annotations are required for overrides, and potentially deducing them from the overridden method is what is being referred to as "inferring" the types.

**Comment by markcellus** [comment] 2024-07-17 14:56
Yeah I'm aware of what currently stands, and I agree that "manual type annotations are required for overrides", which is why this ask isn't related to that issue you all keep pointing me to. 

The fact that the `@override` tag isn't being considered as a "manual type annotation" is the problem. Would you also say that declaring `@inheritdoc` on a method is also not a "manual type annotation"? I'm manually declaring to TypeScript what the method is that it should be using for the type, so what is there to "infer" here?

**Comment by markcellus** [comment] 2024-07-17 15:06
> manual type annotations are required for overrides

This keeps coming up as a point. The other commenter was mentioning that TypeScript doesn't support inferred types on methods.  But that's not the case. 

For instance, when I use a different argument type in a method of a parent class, TypeScript tells me that the types don't match.

![inferred-types-typescript](https://github.com/user-attachments/assets/74e5d295-523e-4c37-b3c3-7c9f9dd26e25)

 It's already "inferring" that the argument in the overridden method is clashing with the argument in the base class, so TypeScript does already "infer" the association with inherited methods.

**Comment by jcalz** [comment] 2024-07-17 15:23
NB: Also not a TS team member, so I have no authority here.

----

Some notes on terminology:

A [type annotation](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#parameter-type-annotations) is when you use a colon followed by the type.  `override` and `@override` are not type annotations.

[Inference](https://www.typescriptlang.org/docs/handbook/type-inference.html) is also not the same as type checking also.  TS can and will *check* the override for compatibility, but it won't *infer* the parameter type for you.  The `override` keyword just adds a bit more type *checking*, but none of the *inference* you're looking for.  

I think you might not be happy with this terminology but that's the way these terms are used in TypeScript.

----

Everyone finds the current behavior around `extends` and `implements` clauses on classes annoying... but it's not a bug, it's a feature request that essentially already exists at the previously mentioned location. 

Maybe you're asking that specifically `override` and `@override` should enable such inference, but that inference should really be happening *anyway*, even if you don't specify `override` that way. If #23911 or the like were implemented, you'd get your desired behavior automatically.  I don't know if restricting the inference to the use of `override` would make the feature more or less likely to be implemented.

**Comment by markcellus** [comment] 2024-07-17 16:37
Guess we disagree on what a "type annotation" is. I consider using JSDoc tag annotating a type. TS has [a whole document](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html) on supporting JSDoc tags. So I'm confused on why we're getting caught up in terminology here, which doesn't really matter imo. The issue I brought up originally is still an issue and it appears to be a bug.

If TypeScript doesn't want to infer anything I'm doing on a method i'm overriding, and implicitly assumes them as `any` (like in my original OP). It confuses me that somehow the parameters are no longer `any` when I use `@param` tag. Please see the last gif that I posted. That error shouldn't be there if TS is supposed to be not "inferring" anything about the arguments in the overriding method.

**Comment by MartinJohns** [comment] 2024-07-17 16:48
> It confuses me that somehow the parameters are magically no longer implicitly `any` when I use the `@param` tag. Please see the last gif that I posted. That error shouldn't be there if TS is supposed to be not "inferring" anything about the arguments in the overriding method.

When you don't have a type annotation it falls back to `any` due to the missing type inference (linked issue). When you provide a type annotation it does not. The error you posted has nothing to do with type inference and is just a compatibility check. `any` is compatible (hence no error), but `number` is not.

**Comment by markcellus** [comment] 2024-07-17 17:03
> When you don't have a type annotation it falls back to any due to the missing type inference (linked issue). 

Sure and I have no problems with that. But it also does this if `@override` is used, which is the point I'm trying to make. 

> When you provide a type annotation it does not. 

Another commenter just said that using `@override` or JSDocs is not a type annotation, so since I'm not using a type annotation, I'm unsure on how this statement applies.

> The error you posted has nothing to do with type inference and is just a compatibility check.

Again, we're getting hung up on terminology. I don't maintain TypeScript so I don't know what the definitions created all mean or why certain things were defined that way.  All I'm saying is that whether it's a compatibility check or type inference, when I specify a JSDoc `@override` or `@inheritdoc`, it seems like a bug for TS not to recognize that my intention is to use the exact same typed arguments as the base class.

**Comment by RyanCavanaugh** [comment] 2024-07-22 19:46
A type annotation is an annotation that provides a type. `override`, as designed today, isn't one of those -- it's a keyword that validates that you have some corresponding thing in the base type. That was its sole design. It doesn't have any type effects.

I can get why the other behavior is desirable but it's just factually not a *bug*. The code is working the way we wanted it to work when we wrote it. You can disagree with what was wanted! But that doesn't make it a bug.

**Comment by markcellus** [comment] 2024-07-22 20:23
Bug or not, it's still unexpected behavior. 

If TS is going to support JSDoc, it should behave the way JSDoc would behave. Or you're not supporting JSDoc. If the intention is not to support JSDoc, it's better to just say that instead of pretending to. :) 

Specifying `@override`  or `@inheritdoc` in JSDoc does fail if the parameters are not the same as those in the child class. So I'd expect for TS to behave the same way.

**Closed** 2024-07-25 01:31 UTC
Labels: Duplicate
