### ISSUE TITLE
Argument of type 'string[]' is not assignable to parameter of type '"value" | "value"[]'.

### ISSUE THREAD

**Issue by ahagelstein** [Microsoft/TypeScript#20068] opened 2017-11-16 13:42 UTC
**TypeScript Version:**  2.7.0-dev.20171116
**Code**

```ts

const func1 = <T extends (string | number)>(key: string, data: T | T[]): void => {};
const func2 = <T extends (string | number | boolean)>(key: string, data: T | T[]): void => {};

func1("data", ["value"]);
// OK

func2("data", [123, 345]);
// OK

func2("data", [false, true]);
// OK

func2("data", ["123", true]);
// OK

func2("data", ["123"]);
// Argument of type 'string[]' is not assignable to parameter of type '"value" | "value"[]'.
//   Type 'string[]' is not assignable to type '"value"[]'.
//     Type 'string' is not assignable to type '"value"'.
```

**Expected behavior:**

Code compiles without errors.

**Actual behavior:**

Code compiles with error.

BUT: with typescript@2.6.1 there is no error.

**Comment by andy-ms** [comment] 2017-11-16 14:59
Duplicate of #19837

**Closed** 2017-12-01 07:26 UTC
Labels: Duplicate
