### ISSUE TITLE
TS2536 when deep remapping

### ISSUE THREAD

**Issue by klarezz** [microsoft/TypeScript#52896] opened 2023-02-21 17:49 UTC
# Bug Report

### 🔎 Search Terms

TS2536: Type cannot be used to index

### 🕗 Version & Regression Information

v4.9.5

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gRgKygXigbwFBSgQwFzpbZRwGbHEDGBArgHYDWdA9gO51HYC+RPXA3BgyhIUAEoQAsjjApC2ANoAFKAEs6UBhBDMAZrEQBdMpygLJajVp374CZYeMH7Sw+bcAiSh8O8MAoA)

### 💻 Code

```tsx
type Obj = {
  a: {
    b: {
      c: unknown
    }
  }
};

type ReMap = {
  [P in keyof Obj]: {
    [M in keyof Obj[P]]: Obj[P][M]["c"]
  }
};
```

### 🙁 Actual behavior

Code below throws TS2536: Type "c" cannot be used to index type 'Obj[P][M]'

### 🙂 Expected behavior

No error?

### Related?

Could be related to #21760

**Comment by klarezz** [comment] 2023-02-21 18:10
@MartinJohns, I updated the issue, could you please explain what I'm doing wrong?

**Comment by RyanCavanaugh** [comment] 2023-02-21 18:22
I think this is just a duplicate of the one you linked.

Anyway this code is equivalent and works well:
```ts
type Obj = {
  a: {
    b: {
      c: string
    }
  }
};

type GetC<T> = T extends { c: infer O } ? O : never;

type ReMap = {
  [P in keyof Obj]: {
    [M in keyof Obj[P]]: GetC<Obj[P][M]>;
  }
};
```

**Closed** 2023-02-24 18:00 UTC
Labels: Duplicate
