### ISSUE TITLE
Unable to narrow union to Record in TS 4.8

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#50671] opened 2022-09-07 14:09 UTC
# Bug Report

### 🔎 Search Terms

union record narrow type guard 

### 🕗 Version & Regression Information

- This changed between versions 4.7.4 and 4.8.2

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.8.2#code/GYVwdgxgLglg9mABDAzgeQEYCsCm0A8AKgHwAUMUAXIoQJTUXIo2IBkiASnnAE4Am+FFB4wwAcwA0icAGswcAO5hiiAN4AoRFsQ8cUEDySZc0AHQAHHnCjWAnuZymbAZWGixpiAEMANj-JQtIgAvKGIAEQA2nDYeFCIxnEAuuEA3OoAvurqfHg+XrqIoJCwCIhQOEKkBWLUXBC8AkIi4lJeYLbE9IgAbnAwfNm5EPmFDWBCiDXUpM3uiAA+iGAgALYYODyLalPU4RjhiBm06eowwIjk6LHQ1TxitEEa2ogA9K9T90yUmtrviABaGjORAAFlMAHZqKovHsDlkXv8gYQQeCABwzObibYrdabbaqXYRA5HILseqNQRuVrSMByRTKX5aCpVQmmdk1UmZdRAA)

### 💻 Code

```ts
function isObject<T>(it: T): it is T & Record<string, unknown> {
    return Object.prototype.toString.call(it) === "[object Object]";
}

declare function test(arg: Record<string, any>): void

declare const arg: (string | number | { a: "b" });

if (isObject(arg)) {
    // arg is:
    // - TS 4.7: {a: "b"}
    // - TS 4.8: (string | number | { a: "b" }) & Record<string, unknown>
    test({ ...arg }) // ERROR: Spread types may only be created from object types.(2698)
}
```

### 🙁 Actual behavior

`arg` stays as some intersection type, which TS does not recognize as an object type.

### 🙂 Expected behavior

`arg` gets narrowed to `{a: "b"}`

**Comment by AlCalzone** [comment] 2022-09-07 14:12
Bonus attempt using conditional types, not much better though:
```ts
type ExtractObject<T> =
	T extends readonly unknown[] ? never
	: {} extends T ? Record<string | number | symbol, unknown>
	: T extends Record<string | number | symbol, unknown> ? T
	: never;

function isObject<T>(it: T): it is T & ExtractObject<T> {
	return Object.prototype.toString.call(it) === "[object Object]";
}

declare function test(arg: Record<string, any>): void

declare const arg: (string | number | { a: "b" });

if (isObject(arg)) {
    // arg is:
    // - TS 4.7: {a: "b"}
    // - TS 4.8: (string | number | { a: "b" }) & { a: "b" }
    test({ ...arg }) 
}
```

[Playground Link](https://www.typescriptlang.org/play?ts=4.8.2#code/C4TwDgpgBAogHsATgQwMbAPICMBWF0A8AKgHxQC8AUAJBFQQIQB2AJgM5SITIsD2TAGxBQArkwDWTXgHcmAbQC6UAPxQmEAG4RENAFxQA3gF96jVhzqqASvl6IWBNkgCWTAOZQAPmpEBbLNpeUGwg-rwCADSiElKyJHpQdAzAzOxQNqh2Dk6Irh7eTH4BiEEhYZHRkjJMZKpECepaiADclJQAZmLozvxQzmzYeISkABTOwPpEAJT6430WUABksAgo6IP4wMRkBjRcwCKITFAb6AB0YIi8wNfgEGc3AMou7meoyAICY8BTFOTkUAARHJeLhNicwegFIDWkY2ix8AJkFwoJ0mN1eiknCNkW59Bkso4Xm4osgmCASDMoBpeM4WPDEcjoJkmE4oLj9CMcnkgoV-IFvAZ2fpAVhAVAjFNWpRnO0oGMBpDgDjEG4pr9dlAtVAAPQ69mq+a6Sja3X6gC0iUeUAALGcAOz6AzIEViuGmvVQS1Ea12gAcnO57l5RQFhmFQLFEt+yyFLsj4vd2qxyqFZ3TuOjUEocKAA)

**Comment by AlCalzone** [comment] 2022-09-07 14:15
Note that narrowing arrays broke in a similar fashion, but here I was able to work around it with a conditional type.

Works in 4.8:
```ts
type ExtractArray<T> =
	T extends readonly unknown[] ? T
	: {} extends T ? (T & unknown[])
	: never;

export function isArray<T>(it: T): it is T & ExtractArray<T> {
	if (Array.isArray != null) return Array.isArray(it);
	return Object.prototype.toString.call(it) === "[object Array]";
}
```

Used to work until 4.7:
```ts
export function isArray<T>(it: T): it is T & unknown[] {
	if (Array.isArray != null) return Array.isArray(it);
	return Object.prototype.toString.call(it) === "[object Array]";
}
```

**Comment by whzx5byb** [comment] 2022-09-07 14:45
`function isObject<T>(it: T): it is T & object & Record<string, unknown>`

Does this work for you?

**Comment by AlCalzone** [comment] 2022-09-07 14:51
Looks like a step in the right direction. Still need to find a way to remove arrays from the type though.

**Comment by lll000111** [comment] 2022-09-09 08:53
Not just unions are affected:

Not only unions. Here is a simpler example:

https://www.typescriptlang.org/play?ts=4.8.2#code/GYVwdgxgLglg9mABAZQKZgCYCEA2cBGAFBgIZQkBci4A1mHAO5gA0i6EcGMYA5lbfSYBKRAG8AsAChEMxDGCJC7Ttx6IAhAF5N1TKmDdUGRADITbSCt4btiAOQgowABx2RE6bK9QAFgCdGRDBUBkQAUT8Av0I7ZS5eNwBuKS8AXykU2QB6LMQAWTgQAGdURB84ADdUP0QoOEQS0oxUKFRoI1qATwAHUsyZHMQAdR90aiLVRAAVZEQKgBYAOmdFgCY5KDkisVTEAB9dZoNgjH7EQZGx4smZuaWAdkX5ja3EACJHFzf9w-1DU88MjiqmSklSoKAA

```javascript
function SendBlob(data: unknown, encoding: unknown) {
    if (encoding !== undefined && encoding !== 'utf8') {
        throw new Error('encoding');
    }

    // Mouse hover to see detected type 
    // When using TS v4.8.2 it is {} | undefined
    // When using TS v4.7.4 it is "utf8" | undefined
    encoding;
};
```

**Comment by andrewbranch** [comment] 2022-09-09 17:04
@AlCalzone can you provide some test cases that show why @whzx5byb’s solution of `T & object` isn’t sufficient? It works fine for the only case in your repro.

**Comment by AlCalzone** [comment] 2022-09-09 17:41
@andrewbranch Sure thing:

[Playground Link](https://www.typescriptlang.org/play?ts=4.8.2#code/GYVwdgxgLglg9mABDAzgeQEYCsCm0A8AKgHwAUMUAXIoQJTUXIo2IBkic2eUbiASnjgAnACb4UUITDABzADSJwAazBwA7mGKIA3gChEBxEJxQQQpJlzQAdAAchcKI4CetnNacBlSdJnWIAIYANkHkULSIALzRiABEANqcVjyW3AC6sQDcugC+uroieEEBxoigkLAIiFA4EqQlMtQCEMJiElKyCgFgzsT0iABucDAi+YUQxaUtYBKIDQCM1KRgIAC2GDhCiAA+cz3xaTs6c9SxGLGIObTZ45M4iNOzDQBMSyvrm0fdzgdH2idxc6Xa75GDARDkdBcaD1IQyea0CJ6QyIAD0qMQKHsOACIl8iDUwiUKEo+kMNTq-2s1IWwOyKPR1QAFqgmIhVDxuohNg4hKSAJCPHg8SJzOHzfwIQJQbL8xmGAB6AH5dHKMTxWcpVBpcrpGYBEwkQGAcShwYD1qOiVutNttdvtDvtFsQgGTCAlElD5crQeBIVCpaAAMRgAA8cGISGFqHQGBrmNoctyQzUwCJmIRVUq0RiAHIlBxqZn3AAGCeL1Vc9yce0UMzcEDBMHDHGhUFVBkIvGarXEPlkR3eGy2uxQznWcCCCi16k0quo040SZTaZomez1WMAR4C6QQRgpsQpZyxfbLHY3dEvY6MgHayHR1H48ntZUM+Ic5YOGTZpXSW46+9SowC6IQhACZwOC2AJoBAYIW2SNdOy-ZdmE3EQECCCCdwOVV+SzMAcAGT5GQ5Gt83A3DoyXH9mFIalrAaEk9h+NIIkiLRvlw-DCOIjFSICMpwB9BBKJYEi4C6JBoNMOC-2gD8CKIrY9FVRlCBZZhWQIiBahQEoII2QIQBQHABUZKBKzgcEVhCKIYgAcjkqB7NU9VLPBX4rUQRzWxctVEF+aQJG6HSrMQAMRRiSQQBwVVjFMcxwtbOwHCcCy3A8OBvGvfxglCCg2JiBInKS5IMmyPJdDBCF-VbYMwxEWEZGeREdDJAxGSxND8UJIRiVJFEKSgUgqRpOFnjpdr1ygDS2W1GseWEKaXklSAt0yddpmlRB0NqdlHCTVAeCqdL7m0AJTnOPI8iAA)

```ts
function isObject<T>(it: T): it is T & object & Record<string, unknown> {
    return Object.prototype.toString.call(it) === "[object Object]";
}

declare function test(arg: Record<string, any>): void

declare const arg1: (number | any[] | { a: "b" });
declare const arg2: (number | any[] | { a: "b" });

if (isObject(arg1)) {
    // spreading works:
    test({ ...arg1 });
    // this is not an error:
	const t = arg1.concat;
	//    ^?
	// t is unknown
}
// ↑ broken
//====================================================
// ↓ works

function isObjectFixed<T>(it: T): it is {} extends T
	? // Narrow the `{}` type to an unspecified object
	  T & Record<string | number | symbol, unknown>
	: unknown extends T
	? // treat unknown like `{}`
	  T & Record<string | number | symbol, unknown>
	: T extends object // function, array or actual object
	? T extends readonly unknown[]
		? never // not an array
		: T extends (...args: any[]) => any
		? never // not a function
		: T // no, an actual object
	: never {

	// This is necessary because:
	// typeof null === 'object'
	// typeof [] === 'object'
	// [] instanceof Object === true
	return Object.prototype.toString.call(it) === "[object Object]";
}

if (isObjectFixed(arg2)) {
    // spreading works:
    test({ ...arg2 });
    // this is now an error
    arg2.concat; // concat does not exist on type {a: "b"}
}
```

**Comment by AlCalzone** [comment] 2022-09-09 17:51
Sorry, had to edit this a few times, I messed up in between.

**Comment by andrewbranch** [comment] 2022-09-09 18:26
Ah. Yeah, since functions and arrays are assignable to our `object`, I’m inclined to say this is working as intended, and what you’re checking for is indeed more complex, hence the several conditions you need in the predicate. Perhaps `object`’s name is a bit unfortunate. What it really is is the non-primitive type. (In fact that’s what we name it in the checker.) But for what it is, not what it’s named, I think the behavior is expected.

**Comment by AlCalzone** [comment] 2022-09-09 18:35
Strangely `T & Record<...>` did work just fine in 4.7 and narrowed T to its Record-compatible subset.
Just like `T & unknown[]` narrowed T to its array subset and no longer does now.

Is it really supposed to be this complex to make sure one is dealing with an actual Record (or an actual array)?

**Comment by andrewbranch** [comment] 2022-09-09 18:42
What’s an “actual Record”? Lots of things that are not made out of object literals have named properties that can be accessed, which is what the `{}` and `interface` syntaxes mean in TypeScript. `() => {}`, `[]`, and `"hello"` are all examples of a `Record<"length", number>`. Such is the nature of a structural type system.

**Comment by andrewbranch** [comment] 2022-09-09 21:03
I’m honestly shocked that the definition of `isObject` worked before. It’s totally inconsistent. Even in 4.7:

```ts
type T1 = (string | number | { a: "b" }) & Record<string, unknown>; // (string | number | { a: "b" }) & Record<string, unknown>
declare let arg2: T1;
test({ ...arg2 }); // error
```

I just inlined the intersection you’re performing in the type predicate. If you expect to get `{ a: "b" }` out of that intersection, it means you think `string & Record<string, unknown>` is `never`, which has never been true. I’m actually totally baffled that the type guard acted like it was.

> distinguish those from other (structurally compatible) things

Philosophically, this is just going to be a heavy lift, if not impossible, in a structural type system. TypeScript reasons much more about what you can _do_ with a value than what it _is_. What’s returned by a value’s `toString()` is very nearly outside the scope of the language.

**Comment by AlCalzone** [comment] 2022-09-09 22:30
> If you expect to get `{ a: "b" }` out of that intersection, it means you think `string & Record<string, unknown>` is `never`, which has never been true. I’m actually totally baffled that the type guard acted like it was.

Heh, I guess I just went along with what TS gave me when I wrote this function that way. That behavior was pretty stable since 3.3 (or earlier, dunno).

**Comment by fatcerberus** [comment] 2022-09-10 00:22
@andrewbranch Technically I guess it’s not accurate to call `object` the non-primitive type either since I recently realized primitives can be assigned to `{ toString(): string }` which in turn is assignable to `object`.  I don’t really know what to call this odd duck of a type anymore, heh.  Maybe just “`{}` with extra steps” 😆

**Closed** 2022-09-14 20:00 UTC
Labels: Working as Intended

**Comment by alebrozzo** [comment] 2022-09-22 09:52
Regardless of if this expected behaviour, it is a breaking change. Perhaps it should be rolled back and re introduced in a v5?

in our case we are comparing primitives and getting this same error:

```
type ValueType = (string | number | bigint | Date) | undefined | null;

const isEmpty = <T extends ValueType>(val: T) => {
    return val === undefined || val === null || val === '';
};

export const customComparer = <T extends ValueType>(a: T, b: T, locale: string) => {
    if (isEmpty(a) || isEmpty(b)) {
        return compareWithEmptyValues(a, b);
    }

    if (typeof a === 'string' && typeof b === 'string') {
        return a.localeCompare(b, locale, { sensitivity: 'base' });
    }

    return a < b ? -1 : a > b ? 1 : 0;
};

```

on v4.7 it worked fine but on v4.8.2 TS complains that a and b could be null on the last line.

**Comment by Apollon77** [comment] 2022-09-22 11:30
@alebrozzo The TypeScript project here do not use semantic versioning, so you need to consider each minor version as most likely "breaking" and not just major ...
