### ISSUE TITLE
Type guard not working for checking an optional property whose type should be Function and using `typeof` with it.

### ISSUE THREAD

**Issue by LvChengbin** [microsoft/TypeScript#42241] opened 2021-01-07 15:48 UTC
# Bug Report

### 🔎 Search Terms

type guard, type assertions, typeof

### 🕗 Version & Regression Information

I just tried this on playground with v4.1.3 and the issue still occurs in v4.2.0-dev.20210107

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210107#code/JYOwLgpgTgZghgYwgAgBrIN4Chm+QNzgBsBXCAfgC5kAKZAOkbigHMBnagbWTbClBYAaZCBIBbAEbRkAXWQBKZAF4AfAQD2wACYBuHHhBwxFar34gWegL5YsCdSF7IAHtXRLMNuw6cYCxMmQrZRc9LGAYOkJSFEVsPGR7RzBkGBAQukZ6ZnZqAAVmIwhIKDYAHjAATwAHCHUYfxi1RVVPLC8Iumd6aMC4-VwkpzSMhiZWDmQCqCKS8qra+pcegIhm5TUMGwShlJhqLtM+AWFK6lFJaRa1fE0tEO7eiGtbcMjlw2MFTAHEnxTJmYBA96J9nu0gA)

### 💻 Code

```ts
interface X {
    value?: ( ...args: [ string, number ] ) => void;
    name?: string;
}

const x: X = {}

const { value } = x;

if( value ) {
    const fn = ( ...args: Parameters<typeof value> ) => {} // ✅
}

if( x.value ) {
    // Type '((args_0: string, args_1: number) => void) | undefined' does not satisfy the constraint '(...args: any) => any'.
    //     Type 'undefined' is not assignable to type '(...args: any) => any'.(2344)
    const fn = ( ...args: Parameters<typeof x.value> ) => {} // ❌
    const f: ( x: string, y: number ) => void = x.value; // ✅
}

if( x.name ) {
    const s: string = x.name; // ✅
}
```

**Comment by MartinJohns** [comment] 2021-01-07 15:50
Duplicate of #9998.

**Comment by phamquangquy92vd** [comment] 2021-01-07 16:34
> # Bug Report
> 
> ### 🔎 Search Terms
> 
> type guard, type assertions, typeof
> 
> ### 🕗 Version & Regression Information
> 
> I just tried this on playground with v4.1.3 and the issue still occurs in v4.2.0-dev.20210107
> 
> ### ⏯ Playground Link
> 
> [Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210107#code/JYOwLgpgTgZghgYwgAgBrIN4Chm+QNzgBsBXCAfgC5kAKZAOkbigHMBnagbWTbClBYAaZCBIBbAEbRkAXWQBKZAF4AfAQD2wACYBuHHhBwxFar34gWegL5YsCdSF7IAHtXRLMNuw6cYCxMmQrZRc9LGAYOkJSFEVsPGR7RzBkGBAQukZ6ZnZqAAVmIwhIKDYAHjAATwAHCHUYfxi1RVVPLC8Iumd6aMC4-VwkpzSMhiZWDmQCqCKS8qra+pcegIhm5TUMGwShlJhqLtM+AWFK6lFJaRa1fE0tEO7eiGtbcMjlw2MFTAHEnxTJmYBA96J9nu0gA)
> 
> ### 💻 Code
> 
> ```ts
> interface X {
>     value?: ( ...args: [ string, number ] ) => void;
>     name?: string;
> }
> 
> const x: X = {}
> 
> const { value } = x;
> 
> if( value ) {
>     const fn = ( ...args: Parameters<typeof value> ) => {} // ✅
> }
> 
> if( x.value ) {
>     // Type '((args_0: string, args_1: number) => void) | undefined' does not satisfy the constraint '(...args: any) => any'.
>     //     Type 'undefined' is not assignable to type '(...args: any) => any'.(2344)
>     const fn = ( ...args: Parameters<typeof x.value> ) => {} // ❌
>     const f: ( x: string, y: number ) => void = x.value; // ✅
> }
> 
> if( x.name ) {
>     const s: string = x.name; // ✅
> }
> ```

**Comment by RyanCavanaugh** [comment] 2021-01-07 17:25
The expression space of function arguments is evaluated in the control flow context of the function body, not the enclosing scope. So `x.value` is `... | undefined` here the same way it would be in a statement position:
```ts
if (x.value) {
    const fn = (...args: Parameters<typeof x.value>) => {
        x.value; // (...) | undefined
    }
}
```
This is broadly more desirable than the alternative, since otherwise code like
```ts
const f = (arg: typeof x = x) => { }
```
could fail, which would make even less sense.

**Closed** 2021-01-09 20:00 UTC
Labels: Working as Intended
