### ISSUE TITLE
Set.has should accept any type

### ISSUE THREAD

**Issue by ktmud** [microsoft/TypeScript#44542] opened 2021-06-10 22:20 UTC
# Suggestion

Currently if you do

```ts
const mySet = new Set(['foo'] as const])
mySet.has('bar')
```

Line 2 throws an `Argument of type '"bar"' is not assignable to parameter of type '"foo"'` error.

However, `set.has(...)` is meant to detect whether an element is in the set, therefore by definition it should be able to accept arguments that are not in the set---in which case, it just returns `false`.

It seems the fix is simply replace https://github.com/microsoft/TypeScript/blob/69cc9ba5e458349168832293510046aa1248cef9/lib/lib.es2015.collection.d.ts#L63  with

```ts
    has(value: any): boolean;
```

## 🔍 Search Terms

set, has, dom, lib, any, type, const

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow `set.has(...)` to accept any arguments that are not in the set.

## 📃 Motivating Example

N/A

## 💻 Use Cases

N/A

**Comment by IllusionMH** [comment] 2021-06-10 22:28
Looks like a duplicate of #42641

**Closed** 2021-06-13 18:00 UTC
Labels: Duplicate
