### ISSUE TITLE
An array with objects is formatted incorrectly.

### ISSUE THREAD

**Issue by TrevorKarjanis** [microsoft/TypeScript#40989] opened 2020-10-07 16:11 UTC
An array with objects is formatted incorrectly. This is similar to [#50284](https://github.com/microsoft/vscode/issues/50284)

- VSCode Version: 1.50.0-insider
- OS Version: macOS Catalina 10.15.6

Steps to Reproduce:

1. Create a JavaScript array that starts with a string and ends with two objects on new lines.
```javascript
let test = ['test', {
    test: 'test'
}, {
    test: 'test'
}];

test = [{
    test: 'test'
}, {
    test: 'test'
}];
```
2. Format the document

Result:
```javascript
let test = ['test', {
    test: 'test'
}, {
        test: 'test'
    }];

test = [{
    test: 'test'
}, {
    test: 'test'
}];
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-10-08 05:46
Duplicate of https://github.com/microsoft/TypeScript/issues/8644 (which  #50284 links to)

**Closed by mjbvz** 2020-10-08 05:46 UTC

**Comment by TrevorKarjanis** [comment] 2020-10-08 13:38
@mjbvz There are two different cases, multiline arrays and multiline function calls. TypeScript formats multiline arrays differently than VSCode but then formats function calls equivalently. TypeScript formats each differently, like the following.
[TS Playground Example](https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBdw0BSCGgAXlAAG0AOQ01DM-gAb0UJRKbPyoFZ+nZigAvlyebz+YK2cyxQBdADcwQQnFpaGFADEvAyABTJCi-VAC2mUTjMOyQVXcAWc8UCMg20B2gCUoDpAD5naBRcq2drdULaRznZK+cKBUGRfbubyNbTI7KxS7lcUcA0PGQvIh4AMGCD2NT7oxzewGMxIPxYNB1Il8-A9CIvAAiACiqwYiBq+mbSRxzfADnZwgAcpAJM2gioAPLfMi7QSVrSQY6oRwKVzSPCgJw5nSjLD6FAIRAw4RXb6SXPREQGDg47osNhcbhBEpAA)
```typescript
let test = ['test', {
        test: 'test'
    }, {
        test: 'test'
    }];

const testFn = (first, second, third) => { };
testFn('test', {
    test: 'test'
}, {
    test: 'test'
});
```
I personally don't like the extra indentation for arrays.
