### ISSUE TITLE
JSX tags don't provide completions for imported names

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#6030] opened 2015-12-10 08:27 UTC
Adapting from #6029 as an example:.

Assuming `tsd` is installed (`npm install -g tsd`)

Run

```shell
`tsd install react-global react-bootstrap --save`
```

* `tsconfig.json`:

    ```json
    {
        "compilerOptions": {
        "target": "es5",
        "module": "amd",
        "jsx": "react"
        },
      "compileOnSave": false,
      "files": [
        "./main.tsx",
        "./typings/tsd.d.ts"
       ]
     }
````

* `main.tsx`:
    ```tsx
    import * as React from 'react';
    import { render } from 'react-dom';
    import { Button } from 'react-bootstrap';

    class App extends React.Component<{}, {}> {
      render() {
        return < /*1*/
      }
    }

    render(</*2*/ />, document.getElementsByTagName("entrypoint")[0] );
    ```

Notice that at `/*1*/` and `/*2*/`, you'll get `App`, but not `Button`.

**Comment by mhegazy** [comment] 2016-01-07 19:29
duplicate of #4577

**Closed by mhegazy** 2016-01-07 19:29 UTC
Labels: Bug
