### ISSUE TITLE
Compiler not erroring for generic in Promise.resolve

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#10785] opened 2016-09-08 18:36 UTC
Latest 2 beta

``` ts
type Foo = Promise<string>;
const baz = Promise.resolve(1); // inferred as Promise<number>, correct
const cmd: Foo = baz // should error! number should be string
```

**Comment by yortus** [comment] 2016-09-09 13:02
It is an annoying problem, but I think the team is looking into it. See #9953 and #10524. (This is really a duplicate of those).

**Comment by OliverJAsh** [comment] 2016-09-22 16:06
Closed by https://github.com/Microsoft/TypeScript/commit/9d4219acf17e6b1e20279a331db12e13e94d4b58

**Comment by OliverJAsh** [comment] 2016-09-23 16:13
Actually I believe this is still an issue:

``` ts
const commits: Promise<number> = Promise.resolve('foo') // no error!
```

**Comment by mhegazy** [comment] 2016-12-14 06:58
> Actually I believe this is still an issue:

should be working now.

```sh
c:\test>tsc --v
Version 2.1.4

c:\test>type C:\test\sandbox8\a.ts
const commits: Promise<number> = Promise.resolve('foo') // no error!

c:\test>tsc C:\test\sandbox8\a.ts --lib es6
sandbox8/a.ts(1,7): error TS2322: Type 'Promise<string>' is not assignable to type 'Promise<number>'.
  Type 'string' is not assignable to type 'number'.
```

**Closed by mhegazy** 2016-12-14 06:58 UTC
