### ISSUE TITLE
Autocomplete on JSX

### ISSUE THREAD

**Issue by olmobrutall** [Microsoft/TypeScript#6931] opened 2016-02-05 20:49 UTC
After token `<` auto-complete doesn't really work on .tsx files. 

Two examples: 

Here I would like to have `boolean` in the auto-complete list, but only functions are showed, so It only shows `Boolean`. 

![image](https://cloud.githubusercontent.com/assets/720953/12858663/c5b60aa6-cc51-11e5-9715-4b967149d497.png)

Here however I want a React element:
* intrinsic types like `div` work properly :+1: 
* components defined in this module as well :+1: 
* but components imported are not shown in the list :-1:  

![image](https://cloud.githubusercontent.com/assets/720953/12858727/30b1da1a-cc52-11e5-80ce-5186c09a0fb3.png)

Still, thanks for 1.8, is much better!

**Comment by mhegazy** [comment] 2016-02-05 22:18
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/4577

**Closed** 2016-02-20 05:25 UTC
Labels: Duplicate
