### ISSUE TITLE
`valid: (value: string) => void` but  `{valid(value) {} }` error "Parameter 'value' implicitly has an 'any' type."

### ISSUE THREAD

**Issue by yamiwamiyu** [microsoft/TypeScript#60058] opened 2024-09-25 09:54 UTC
### 🔎 Search Terms

function inference any

### 🕗 Version & Regression Information

- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play/?noUncheckedIndexedAccess=true&useDefineForClassFields=true&allowUnreachableCode=true&allowUnusedLabels=true&downlevelIteration=true&noEmitHelpers=true&noStrictGenericChecks=true&noUnusedLocals=true&noUnusedParameters=true&preserveConstEnums=true&removeComments=true&importHelpers=true&experimentalDecorators=true&emitDecoratorMetadata=true&isolatedModules=true&isolatedDeclarations=false&allowUmdGlobalAccess=true&exactOptionalPropertyTypes=true&noFallthroughCasesInSwitch=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true&useUnknownInCatchVariables=true&strictBuiltinIteratorReturn=true&noImplicitUseStrict=true&suppressImplicitAnyIndexErrors=true&preserveValueImports=true&keyofStringsOnly=true&suppressExcessPropertyErrors=true&noCheck=false&noErrorTruncation=true&preserveWatchOutput=true&verbatimModuleSyntax=true&allowSyntheticDefaultImports=true&allowArbitraryExtensions=true&noUncheckedSideEffectImports=true&resolvePackageJsonImports=true&resolvePackageJsonExports=true&allowImportingTsExtensions=true&disableSourceOfProjectReferenceRedirect=true&inlineSourceMap=true&inlineSources=true&stripInternal=true&pretty=true&ts=5.6.0-dev.20240818&ssl=140&ssc=43&pln=140&pc=61&noLib=true&filetype=ts#

### 💻 Code

```ts
// detail please see Playground Link
g<{
    ID?: number;
    Name?: string;
    Face?: string;
    Time?: Date;
}>().build({
    ID: {default: 10, },
    other: {init: '', default: 0, rules: [{valid(value) {} }]},
})
```

### 🙁 Actual behavior

Mouse over the `valid` to display `valid: (value: string) => void`
Mouse over the `value` to display `Parameter 'value' implicitly has an 'any' type.`

### 🙂 Expected behavior

value type is string not any

**Comment by MartinJohns** [comment] 2024-09-25 10:52
Duplicate of #47599.

**Closed** 2024-09-28 01:32 UTC
Labels: Duplicate
