### ISSUE TITLE
strictPropertyInitialization don't works right with delegate initialization

### ISSUE THREAD

**Issue by spat-ne-hochu** [Microsoft/TypeScript#22259] opened 2018-03-01 09:45 UTC
**TypeScript Version:**  2.7.2

**Code**
```ts
class A {
    private b: number;
    private c: string;

    constructor(b: number) {
        this.b = b;
        this.initC();
        
    }

    private initC() {
        this.c = 'string';
    }
}
```
--strictNullChecks
--strictPropertyInitialization

**Expected behavior:**
no errors

**Actual behavior:**
Property 'c' has no initializer and is not definitely assigned in the constructor.

**Playground Link:** 
https://goo.gl/uP2yKq

**Comment by Kingwl** [comment] 2018-03-01 09:51
> There are certain scenarios where properties can be initialized indirectly (perhaps by a helper method or dependency injection library), in which case you can use the new definite assignment assertion modifiers for your properties (discussed below).

**Comment by spat-ne-hochu** [comment] 2018-03-01 10:01
@Kingwl Definite 
"Assignment Assertions" is a very bad practice, and I will not use it with serious projects, because it can very easily break the code.

it can check the constructor function.
why can not it test other methods for initialization?

**Comment by s-ve** [comment] 2018-03-01 11:59
Looks like a duplicate of #21132

**Closed** 2018-03-01 12:53 UTC
