### ISSUE TITLE
Return types of arrow functions allow additional properties.

### ISSUE THREAD

**Issue by ChristophGr** [microsoft/TypeScript#41850] opened 2020-12-07 13:28 UTC
Returned objects of arrow functions can have more properties than the type specified in the variable declaration .

**TypeScript Version:**  4.1.2 / 4.2.0-dev.20201207

**Search Terms:**
arrow function return type covariant additional properties

**Code**

```
type MyResult = { foo: string };

const arrowProvider: () => MyResult = () => ({ foo: 'bar', bar: 'foo' });
// no error


function funcProvider(): MyResult {
  return { foo: 'bar', bar: 'foo' }; // error
}
```

**Expected behavior:**
Both `funcProvider` and `arrowProvider` should not compile because of the superfluous property `bar` in there.

**Actual behavior:**
Only `funcProvider` triggers a compile-error

**Playground Link:** 
https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiBKEDOBXANsKBeKBvKAZgPZEBcUSwATgJYB2A5lAL4DcAUOwMZF2VQBDKlSIB3AAoiAbjQAmEKuQAUASmwA+WAmTpMOVRqhL8xMlADkAIyHmANFGuKLp8yxUd2BFHS7AavQm8uSSIZeSpVcjhEVAw8digoKghgFCo6PEIScisbe0cclxYOZiA

**Related Issues:**

**Comment by MartinJohns** [comment] 2020-12-07 13:48
Duplicate of #41834 and many others I can't find right now.

You don't specify a return-type for your function, so the return type is inferred. Then, when assigning your function to the variable, the compiler checks if the return-types are compatible, which they are.

**Closed** 2020-12-09 18:00 UTC
Labels: Duplicate
