### ISSUE TITLE
Support tooltip for @yields JSDoc

### ISSUE THREAD

**Issue by nvmnghia** [microsoft/TypeScript#50080] opened 2022-07-28 04:47 UTC
My sample JSDoc

```js
/**
 * @typedef {('foo'|'bar')} TokenType
 */

/**
 * @typedef {Object} Token
 * @property {TokenType} type - Token type
 */

/**
 * @generator
 * @yields {Token} - Token
 */
const gen = function* () {
  yield { type: "foo" };
};

const use_gen = () => {
  const it = gen();
  console.log(it.next().value.type);
};

/**
 * @returns {Token} - Token
 */
const func = () => {
  return { type: "foo" };
};

const use_func = () => {
  const val = func();
  console.log(val.type);
};
```

When hover `Token` in `@returns {Token}`, we can see the object structure.

When hover `Token` in `@yields {Token}`, we can not see the object structure.

IntelliSense currently works fine (`type` is shown while typing the 2 `console.log()`).

Tested version: 

```bash
$ code-insiders --version

1.70.0-insider
9cf2fabdd600c7d8e3230803acb246405321e8dd
x64
```

**Comment by MartinJohns** [comment] 2022-07-30 00:12
Duplicate of #23857.

**Comment by nvmnghia** [comment] 2022-07-30 01:20
> Duplicate of #23857.

No I don't think so. This is just about the tooltip while hovering `@yield`.

**Comment by fatcerberus** [comment] 2022-07-31 22:06
> could you please explain why the issue is moved here? This is just an UI problem.

The UI in question is handled by the TypeScript language server.  That's why you can see the structure of the type, because TypeScript is synthesizing type info from your JSDoc comments.

**Closed as completed** 2022-08-08 18:00 UTC
Labels: Duplicate
