### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by Kinrany** [microsoft/TypeScript#38365] opened 2020-05-06 17:23 UTC
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationOfResolution (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101865:22)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101901:25)
    at Map.forEach (<anonymous>)
    at Object.clearPerDirectoryResolutions [as startCachingPerDirectoryResolution] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101661:50)
    at ConfiguredProject.Project.updateGraphWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:139785:38)
    at ConfiguredProject.Project.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:139729:42)
    at ConfiguredProject.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140654:63)
    at updateProjectIfDirty (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141076:45)
    at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143114:29)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143396:107
    at Object.mapDefined (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:144260:46)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:145994:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:146003:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:146027:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.45.0-insider (d4b8ec9da3bf1061a948fbb1b0d9d3db750cc79f, 2020-05-05T07:13:27.726Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv|-psn_0_1216809|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
prettier-vscode|esb|4.5.0
gitlab-workflow|fat|2.2.0
file-icons|fil|1.0.23
vscode-mocha-test-adapter|hbe|2.3.0
vscode-test-explorer|hbe|2.18.0
vscode-edit-csv|jan|0.2.7
nbpreviewer|jit|1.2.2
rust-analyzer|mat|0.2.159
vscode-http-client|mkl|0.34.0
sqltools|mtx|0.21.7
tabnine-vscode|Tab|2.8.2
vscodeintellicode|Vis|1.2.6
markdown-all-in-one|yzh|2.8.0

</details>

**Comment by mjbvz** [comment] 2020-05-06 17:58
Same error stack as #37759

@Kinrany Can you reliably reproduce this error?

**Comment by Kinrany** [comment] 2020-05-06 18:22
No, it only happened once.

Could be related to me deleting typescript compiler output directory and node_modules a few times. I was debugging a problem with the combination of pnpm and TS.

**Comment by RyanCavanaugh** [comment] 2020-05-11 18:21
We'd definitely need some hint at repro steps for this one

**Comment by sheetalkamat** [comment] 2020-05-11 18:44
Also tsserver log is useful: 
You can upload logs by following these steps:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. In vscode or vscode insiders, run the `TypeScript: Open TS Server log` command
5. This should open a large file called `tsserver.log`. Please share this file. Additionally you can also share file `ti.log` created next to it.

**Comment by Kinrany** [comment] 2020-05-13 03:58
Had a similar crash: https://github.com/microsoft/vscode/issues/97667

Also happened when I was fiddling with npm and pnpm, trying to fix a compilation error that only shows up with pnpm.

Can't reproduce reliably yet.

**Comment by mjbvz** [comment] 2021-02-17 22:14
Closing as not actionable without more information

If you see this again with VS Code 1.53+ and TypeScript 4.15+, please let us know

**Closed by mjbvz** 2021-02-17 22:14 UTC
Labels: Needs More Info

**Comment by ksnyde** [comment] 2021-09-08 22:36
Can we re-open? I can give you clear instructions to recreate.

**Comment by andrewbranch** [comment] 2021-09-08 22:40
@ksnyde that would be great! I will reopen, given repro instructions.

**Comment by ksnyde** [comment] 2021-09-08 22:51
Ok, coming right up ...

**Comment by ksnyde** [comment] 2021-09-08 23:11
I have noticed this same behavior in a CLI repo that I use internally (but it's open source). I was working on some image optimization features and the build times were getting long enough that I realized I really needed to get back to running the build in a watcher.

First off, let's get the repo setup:

```sh
# clone
git clone https://github.com/inocan-group/do-devops.git
# switch to right commit
git checkout ebef9a5bd946f1073cac669663581247857ac09c
# install deps
yarn
# show build process is working
yarn build
# get help page from CLI (this step isn't really necessary)
yarn dd
# now for the big fail
yarn watch:build
```

<img width="506" alt="2021-09-08_16-06-11 (4)" src="https://user-images.githubusercontent.com/980757/132597114-46e371d2-b546-445d-9104-8cde2dc31973.png">

- the commit I've posted above is currently the latest commit in the `feature/images` branch
- I'm using node 14 in my tests (although I believe I also tried with Node 15 too at one point)

If you've followed these steps you'll likely have a watcher running and all is looking good but make any change to a TS file under `/src` and it should crash with an error resembling the following (you do need to change some part of the code ... I am just changing a log statement in `useImageApi.ts`):

> /Volumes/Coding/inocan/open-source/do-devops/node_modules/typescript/lib/typescript.js:2546
            throw e;
            ^

> Error: Debug Failure. False expression: File extension for signature expected to be dts
Verbose Debug Information: Found: .map for /Volumes/Coding/inocan/open-source/do-devops/bin/shared/images/useImageApi.d.ts.map:: All output files: ["/Volumes/Coding/inocan/open-source/do-devops/bin/shared/images/useImageApi.d.ts.map","/Volumes/Coding/inocan/open-source/do-devops/bin/shared/images/useImageApi.d.ts"]
    at updateShapeSignature (/Volumes/Coding/inocan/open-source/do-devops/node_modules/typescript/lib/typescript.js:114815:30)
    at Object.getFilesAffectedBy (/Volumes/Coding/inocan/open-source/do-devops/node_modules/typescript/lib/typescript.js:114768:18)
    at getNextAffectedFile (/Volumes/Coding/inocan/open-source/do-devops/node_modules/typescript/lib/typescript.js:115259:51)
    at getSemanticDiagnosticsOfNextAffectedFile (/Volumes/Coding/inocan/open-source/do-devops/node_modules/typescript/lib/typescript.js:115889:32)
    at Object.getSemanticDiagnostics (/Volumes/Coding/inocan/open-source/do-devops/node_modules/typescript/lib/typescript.js:115934:20)
    at emitFilesAndReportErrors (/Volumes/Coding/inocan/open-source/do-devops/node_modules/typescript/lib/typescript.js:117772:57)
    at result.afterProgramCreate (/Volumes/Coding/inocan/open-source/do-devops/node_modules/typescript/lib/typescript.js:117961:13)
    at Object.watchCompilerHost.afterProgramCreate (/Volumes/Coding/inocan/open-source/do-devops/node_modules/typescript/lib/tsc.js:686:13)
    at synchronizeProgram (/Volumes/Coding/inocan/open-source/do-devops/node_modules/typescript/lib/typescript.js:118254:22)
    at updateProgram (/Volumes/Coding/inocan/open-source/do-devops/node_modules/typescript/lib/typescript.js:118466:21)

**Comment by ksnyde** [comment] 2021-09-08 23:12
Note: i will add one caveat, and that is that I'm using **ttsc** instead of **tsc** because **ttsc** opens up using TS plugin API's and I have a path alias which need resolving.

**Comment by andrewbranch** [comment] 2021-09-08 23:35
That’s a completely different error stack, and I fully expect it to be caused by ttypescript or typescript-transform-paths. If you can reproduce it without using an unsupported patch of our compiler, feel free to open a new issue.

**Comment by ksnyde** [comment] 2021-09-08 23:50
Well the error message is precisely the same, I didn't dig into the prior posters stack.

**Comment by ksnyde** [comment] 2021-09-08 23:58
in fact on further observation ... I think @andrewbranch I think you kicked the can down the road too soon. There is zero reference to anything but **Typescript** in the stack!

**Comment by ksnyde** [comment] 2021-09-09 00:03
I was just being transparent ... but nothing suggests this to be an externality!

**Comment by andrewbranch** [comment] 2021-09-09 00:13
It very well may be a TypeScript issue, but we would ask for a reproduction that minimizes the chances of 3rd-party interference no matter what. The fact that I can’t find a single other issue mentioning the message “File extension for signature expected to be dts” makes me quite suspicious of the plugin (more than the plugin infrastructure). If people were reporting that error en masse, it would be a different story. But as it is I’m willing to impose a little extra burden of proof on the sole issue reporter. And it’s clear it’s a separate issue from the one originally reported here.

**Comment by ksnyde** [comment] 2021-09-09 00:14
Ok well this used to work in this repo and ALL of my repos use this configuration. I won't be able to reproduce I guess.

**Comment by ksnyde** [comment] 2021-09-09 00:21
this issue does show up a lot on a google search .... not the **dts** part but I'm not sure a consistent part of the message.

**Comment by andrewbranch** [comment] 2021-09-09 00:32
`Debug failure. False expression` comes before _all_ our `Debug.assert(...)` messages—it could be literally any crash 😄

**Comment by jasonkuhrt** [comment] 2021-09-17 01:48
I am facing this or similar issue in https://github.com/prisma-labs/kont.

It seems that when I stop using `ttsc` things are working.

**Comment by ksnyde** [comment] 2021-09-17 15:31
I have done further research and it is definitely down to `ttypescript`.
The good news is that it's shockingly easy to move over to `ts-patch` if
you're using `typescript-transform-paths` you'll find the author is the
same and he's both very qualified and very much active. He's working on a
rearchitected v2 to `ts-patch` but there's no need for people who just want
to do path alias remapping.

**Comment by justinbhopper** [comment] 2021-12-15 00:58
I ran into the same issue and also confirmed it was due to the usage of ttypescript.  However, unlike @ksnyde, I was using `@zerollup/ts-transform-paths`, not `typescript-transform-paths`.

Switching from ttsc to `ts-patch` fixed this issue for me.  I was able to use ts-patch with `@zerollup/ts-transform-paths`.

**Comment by arunsingh28** [comment] 2021-12-22 01:01
```
<semantic> TypeScript Server Error (4.5.4) Debug Failure. False expression. Error: Debug Failure. False expression. at NodeTypingsInstaller.installPackage (c:\Users\aruns\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174568:30) at TypingsCache.installPackage (c:\Users\aruns\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164107:39) at ConfiguredProject.Project.installPackage (c:\Users\aruns\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164361:42) at applySingleCodeActionCommand (c:\Users\aruns\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:160425:24) at Object.applyCodeActionCommand (c:\Users\aruns\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:160419:125) at IOSession.Se...  
```

idk why its coming every time .
