### ISSUE TITLE
JSDoc Error with 2 function param

### ISSUE THREAD

**Issue by Thaina** [Microsoft/TypeScript#7254] opened 2016-02-26 08:17 UTC
define function with JSDoc which contain callback function as parameter get error about duplicate

![image](https://cloud.githubusercontent.com/assets/1042507/13346825/bb473dba-dc9b-11e5-8d3f-58618be8c815.png)

**Comment by RyanCavanaugh** [comment] 2016-02-26 16:20
Duplicate of #6993

**Closed by RyanCavanaugh** 2016-02-26 16:20 UTC
Labels: Duplicate
