### ISSUE TITLE
Cannot use class before definition

### ISSUE THREAD

**Issue by letmaik** [Microsoft/TypeScript#10675] opened 2016-09-01 23:21 UTC
**TypeScript Version:**  2.0

**Code**

```ts
new A()
class A {}
```

**Expected behavior:**
The code should run without error.

**Actual behavior:** 
The first line throws a "TypeError: A is not a constructor".
This is because `class A {}` is transpiled to `var A = ...` and kept in the same code order. If A was transpiled as `function A () {...}` then it would work as function statements are hoisted but function expressions are not.

Babel and traceur do the same thing, so maybe this is just a hard issue and not worth solving as eventually there will be native class support anyway in engines.

The problem becomes more obscure when doing things like:
```ts
class B extends A {}
class A {}
```
Same issue but the error changes to a weird `TypeError: b is undefined`.

I think either this should be solved or alternatively a compile-time error thrown if the target is <ES2015.

**Comment by kitsonk** [comment] 2016-09-01 23:29
Duplicate of #5207

**Closed** 2016-09-01 23:54 UTC
Labels: Duplicate

**Comment by letmaik** [comment] 2016-09-02 07:12
Thanks, I didn't see that. I edited the issue text as I was clearly wrong in assuming that class declarations are hoistable where in fact they are not.

**Comment by kitsonk** [comment] 2016-09-02 12:38
Yeah, it was a hard one to find, but I remembered it being brought up before (and I thought I had remembered about them not being hoistable too)
