### ISSUE TITLE
Autoimport not suggesting imports from exports/imports references in package.json

### ISSUE THREAD

**Issue by IgnusG** [microsoft/TypeScript#51599] opened 2022-11-19 21:30 UTC
# Bug Report

### 🔎 Search Terms

autoimport, imports, exports, package.json

### 🕗 Version & Regression Information

- This changed between versions 4.6 and 4.7

> As it only applies to a new feature introduced in 4.7 - https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing

### 💻 Code

```json
// package.json
{
  "type": "module",
  "imports": {
    "#self/*": "./*"
  }
}
```

```json
// tsconfig.json
{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",

    "strict": true,
    "isolatedModules": true
  }
}
```

```typescript
// a.ts
export const greeting = "Hello World!";
```

```typescript
// b.ts
console.log(greeting) // Use quick-fix to trigger autoimporter for greeting- observe missing suggestion for the imports alias
```

You can work around this by adding a tsconfig paths configuration option (which is respected by the autoimporter):

```json
// tsconfig.json
{
  "compilerOptions": {
    ...,
    "paths": {
      "#self/*": ["./*"]
    }
  }
}
```

### 🙁 Actual behavior

- Imports are correctly resolved by typescript according to the rules introduced in 4.7 as described in the blog ✅ 
- Autoimport does not seem to however check these and suggests relative imports instead 🔴 
- It does however respect tsconfig paths so adding an additional redundant paths config option makes the auto import suggest the aliased paths ✅ 

### 🙂 Expected behavior

- The autoimport should take package.json `imports` aliases into account when resolving paths/suggestions

**Comment by andrewbranch** [comment] 2022-12-02 17:01
Duplicate of https://github.com/microsoft/TypeScript/issues/49492, I think

**Closed** 2022-12-02 22:54 UTC
Labels: Needs Investigation, Domain: Auto-import
