### ISSUE TITLE
Tagged union types aren't preserved during key remapping

### ISSUE THREAD

**Issue by Zip753** [microsoft/TypeScript#48922] opened 2022-05-02 21:10 UTC
# Bug Report

### 🔎 Search Terms

`union remap`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the ~FAQ~ documentation for entries about "Mapped Types", "Unions and Intersection Types", "Control Flow Analysis for Destructured Discriminated Unions" from TS 4.6 announcement.

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220502#code/KYOwrgtgBAou0G8BQVVQIJQLxQEQENcAaFNAIWzwCNckBfJJAFwE8AHYWeAWXzbYCWIAOaVkaKAG04kAHToAugC4o8KsABOAblKpp8WWWVQAzkw1DhOujubtOMiAGlgLAGr4ANmE45xaaSghKABrVwB7ADMuSF5+S2N-CVQwlhUYHWS0ADcvH3SePkERaQVMtBt6fUgyxgB6OtN8CE58Eyh8KnDs4CIoKjAmKAB3ASYACygAEwFIyM1QIdSTOw4YiAB5EGAAFWHwsV0pGCCQUIjoxzji4USjiXDt9PKspn2C2KLLUpeoSrpqhBakhImAQABjJgCR6hbI7cJbXb7AAUAA8Ps5XB5vMAAJQYxF7A5JILRNGyVLYLA4RzyXFQEkScGPMyqSAqNSaSio2S5HFaKANKCsNYCdpsDThDgaTwsVT4DSS4bAKb3NDMkAmcKeYCyTzhYTI+C4350KDATwmTizKDkynUmkGMj0xnqllDMwaFSeyzc3l5YACoUi63iyXS2XyxXhZWqrKoDVanV6g3Iz0mo4MCRCjTjdpiqCJgRTBZTfpynYAZQ67QQUEewAxAre4W95l9AB82RB1No-n0hGZgPgy1EoBBwhpOCYOODZgJwetCfsjomhg2iQTtkTDvH608oDzUiQ9y2VDy+T5M78p0wwBozhv9tYkEA)

### 💻 Code

```ts
enum Enum {
    A = "a",
    B = "b"
}

type EnumMapping = {
    [Enum.A]: number;
    [Enum.B]: string;
};

type EnumKeyValue = {
    [E in keyof EnumMapping]: {
        key: E;
        value: EnumMapping[E];
    };
}[Enum];

// same as above, but with different keys
type EnumOneTwo = {
    [E in keyof EnumMapping]: {
        one: E;
        two: EnumMapping[E];
    };
}[Enum];

function kvToOneTwo(x: EnumKeyValue): EnumOneTwo {
    if (x.key === Enum.A) {
        const num: number = x.value; // type is properly narrowed
        console.log(num);
    } else if (x.key === Enum.B) {
        const str: string = x.value; // type is properly narrowed
        console.log(str);
    }
    // rhs is considered by TS as { one: Enum; two: string | number; }, instead of more specific EnumOneTwo
    const oneTwo: EnumOneTwo = {
        one: x.key,
        two: x.value
    };
    return oneTwo;
}
```

### 🙁 Actual behavior

```
Type '{ one: Enum; two: string | number; }' is not assignable to type 'EnumOneTwo'.
  Type '{ one: Enum; two: string | number; }' is not assignable to type '{ one: Enum.B; two: string; }'.
    Types of property 'one' are incompatible.
      Type 'Enum' is not assignable to type 'Enum.B'.
        Type 'Enum.A' is not assignable to type 'Enum.B'.(2322)
```

### 🙂 Expected behavior

Type info from `EnumKeyValue` is preserved when mapped to `EnumOneTwo` and code compiles without issues.

**Comment by jcalz** [comment] 2022-05-03 16:10
Looks like a duplicate of #30581.  
The fix for that issue is #47109, where you refactor things to be generic:

```ts
type EnumKeyValue<K extends Enum = Enum> = {
    [E in K]: {
        key: E;
        value: EnumMapping[E];
    };
}[K];

type EnumOneTwo<K extends Enum = Enum> = {
    [E in K]: {
        one: E;
        two: EnumMapping[E];
    };
}[K];

function kvToOneTwo<K extends Enum>(x: EnumKeyValue<K>): EnumOneTwo<K> {
    return {
        one: x.key,
        two: x.value
    };
}
```
[Playground link](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220502#code/KYOwrgtgBAou0G8BQVVQIJQLxQEQENcAaFNAIWzwCNckBfJJAFwE8AHYWeAWXzbYCWIAOaVkaKAG04kAHToAugC4o8KsABOAblKpp8WWWVQAzkw1DhOujubtOMiAGlgLAGr4ANmGAAeJ1DAAB5MoAAmJlyQlI4AfGK6UjBQQlBOxuISaADWriowOlloAG5ePvk8fIIi0gqFaDb0kum2rBxREADyIMAAKgDuAPb+gSHhkY4x8PE4mXrJqekqc1mDPfn1RUxDFZC8-Ja1m1CNdM11jABmYCAAxkwCa1DZxb2D3X1DI8GhIBEdsQAFEFds5XB5vH4nLEAJSgj4DYbQqArDTAJhgDQgFGJCRrYAqIKyXIsEhFVDbQaE2SlSGJU6MW5rMxQQZMTA4F5vBFDQEIZ55DryIhQWnlKAARgATABmE4w2xAA)

**Closed** 2022-05-07 18:00 UTC
Labels: Duplicate
