### ISSUE TITLE
noUncheckedIndexedAccess does not compile on incorrect possible undefined

### ISSUE THREAD

**Issue by Magnuti** [microsoft/TypeScript#51988] opened 2022-12-21 14:20 UTC
# Bug Report

### 🔎 Search Terms

- `noUncheckedIndexedAccess`

### 🕗 Version & Regression Information

- v4.9.4
- `noUncheckedIndexedAccess: true`
- This is the behavior in every version I tried, and I reviewed the FAQ for entries since v4.1.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=4.9.4#code/MYewdgzgLgBGCuBbARgUwE4RgXhgbQEYAaGAJhIGYBdAbgCg6BLAMxgAoEUMIA6AG1RgA5lAAWMAHwwADAEoYAbzowYoSLGaNMsXJzSY802stXhoMACYh4yAQDEt53Ju0wAVGXoBfOkA)

### 💻 Code

```ts
const numbers = [1, 2, 3];

if (numbers.length > 0) {
  const first = numbers[0];
  const doubleFirst = first * 2;
}
```

### 🙁 Actual behavior

The code does not compile since the compiler thinks `first` can be `undefined`.

![image](https://user-images.githubusercontent.com/43852515/208924949-ca8683cf-4afc-4336-b892-13b40393d858.png)

### 🙂 Expected behavior

The compiler should notice that `first` must be of type `number` and not `number | undefined` since the if statement ensures that.

Of course the code compiles if we disable `noUncheckedIndexedAccess`, but I would like to keep it enabled.

**Comment by MartinJohns** [comment] 2022-12-21 14:22
Essentially a duplicate of #38000. `noUncheckedIndexedAccess` does not change anything about this.

You can access the first element and check that one for `undefined`.

**Comment by Magnuti** [comment] 2022-12-21 15:26
@MartinJohns it seems redundant having check the first element for `undefined`. The array cannot contain `undefined` elements and the array contains elements by the `if(numbers.length > +)` statement, therefore the first element `first` cannot be `undefined`.

**Comment by WesleyYue** [comment] 2022-12-22 04:13
> @MartinJohns it seems redundant having check the first element for undefined. The array cannot contain undefined elements and the array contains elements by the if(numbers.length > +) statement, therefore the first element first cannot be undefined.

`if (numbers.length > x)` doesn't check if the var is undefined, only the length, you can have `[undefined, undefined, undefined]`.

Regardless, I would agree the error should not throw here since `numbers` is clearly defined. I'm running into a bunch of variations of this where the var is clearly defined by typescript appends undefined liberally.

**Comment by Magnuti** [comment] 2022-12-22 08:31
@WesleyYue are you sure that the array can contain `undefined` values? If I explicitly specify the type on the array the code below won't compile.
```ts
const numbers: number[] = [1, 2, 3, undefined];
```
![image](https://user-images.githubusercontent.com/43852515/209091512-361b741d-04ed-4b0a-b9a9-032008b86a5f.png)

Even if I do not specify the type on the array the result is the same.
```ts
const numbers = [1, 2, 3];
numbers.push(undefined)
```

![image](https://user-images.githubusercontent.com/43852515/209091362-60287f2b-28f5-4050-95fa-85be6fef4d2e.png)

**Comment by Magnuti** [comment] 2022-12-22 08:36
> if (numbers.length > x) doesn't check if the var is undefined, only the length, you can have `[undefined, undefined, undefined]`.

@WesleyYue I mean yes if the array was not clearly defined, but as you say the array is clearly defined. The error should not be thrown so we agree on that

**Comment by MartinJohns** [comment] 2022-12-22 09:13
Checking the `length` property does not narrow the type, that's what the issues I linked are about. I suggest checking the indexed value **instead** of the `length` property, or simply use a type assertion.

**Closed** 2022-12-22 09:51 UTC
Labels: Duplicate

**Comment by fatcerberus** [comment] 2022-12-22 15:20
For the record, it's entirely possible for this to happen at runtime:
```ts
let arr: number[] = [];
arr[1] = 42;
console.log(arr.length);  // 2 (i.e. arr.length > 0)
console.log(arr[0]);  // undefined!
```

It's debatable whether most code needs to be hardened against that (sparse arrays are evil), but seems worth considering, at least.
