### ISSUE TITLE
Operation of "instanceof" is illegal when "target:es5"

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/TypeScript#13123] opened 2016-12-22 13:05 UTC
typescript2.1.4

    class MyError extends Error {}
    let e=new MyError();
    console.log(e instanceof MyError);

target:es5
>false

target:es6
>true

**Comment by mhegazy** [comment] 2016-12-22 18:29
duplicate of https://github.com/Microsoft/TypeScript/issues/12790

Please see https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work

**Closed by mhegazy** 2016-12-22 18:29 UTC
