### ISSUE TITLE
Typescript never fails on the wrong field of a partial type object with predefined keys.

### ISSUE THREAD

**Issue by arthurgubaidullin** [microsoft/TypeScript#52371] opened 2023-01-23 16:04 UTC
# Bug Report

### 🔎 Search Terms

- not fail
- partial type
- wrong field type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/C4TwDgpgBAglC8UDkMkCg2klA0hEAzgsgIZJQA+yARuVUgMbqbjQDCA9gLZgcCuAOwAmxAN5ooUANoAFKAEsBufAQC6AfgBcsSlAF8ANgYDcaAL4YhEBgZIAnaAw4CCwKAGtteQhicu3DgSGwNqiUABmHBxaUJw8-MJQZmISUAD0aVAAAsAEALQQAB6QDMAFdnYcdqmRHKGpklLuqtoAjABMAMypFmZAA)

### 💻 Code

```ts
type A = 'A'

type Keys = 'a' | 'b' | 'c'

type Compound = {
  [P in Keys]?: A | null;
}

declare const k: Keys

const result: { foo?: Compound } = {
  // @ts-expect-error
  foo: {
    [k]: 123
  }
}
```

### 🙁 Actual behavior

Not fail.

### 🙂 Expected behavior

Must fail.

**Comment by jcalz** [comment] 2023-01-23 18:40
Duplicate of #50859

**Closed** 2023-01-26 18:00 UTC
Labels: Duplicate
