### ISSUE TITLE
RxJS type inference fails in 3.6.2

### ISSUE THREAD

**Issue by felixfbecker** [microsoft/TypeScript#33131] opened 2019-08-29 09:01 UTC
**TypeScript Version:**  3.6.2

**Search Terms:** type inference 3.6

**Code**
```ts
function asObservable(input: string | ObservableInput<string>): Observable<string> {
    return typeof input === 'string' ? of(input) : from(input)
}
```

**Expected behavior:**
This function managed to compile correctly in 3.5 with RxJS 6.5.2

**Actual behavior:**
In 3.6, it fails with 
```
Type 'Observable<unknown>' is not assignable to type 'Observable<string>'.
  Type 'unknown' is not assignable to type 'string'.ts(2322)
```
the type of `from()` does not get inferred anymore.
It is declared as
```ts
function from<O extends ObservableInput<any>>(input: O): Observable<ObservedValueOf<O>>
```
Specifically, the `ObservedValueOf<T>` type fails now with `ObservableInput<T>`:
```ts
type ObservedValueOf<O> = O extends ObservableInput<infer T> ? T : never;

type ObservableInput<T> = SubscribableOrPromise<T> | ArrayLike<T> | Iterable<T>;
```
which worked before.

**Related Issues:** Filed at https://github.com/ReactiveX/rxjs/issues/4992

**Comment by j-oliveras** [comment] 2019-08-29 10:17
Related to #33125?

**Comment by benlesh** [comment] 2019-08-29 14:38
Yeah, this one is really not good for RxJS and will break a lot of people. [This comment is a solid illustration of why](https://github.com/ReactiveX/rxjs/issues/4992#issuecomment-526105205)

**Comment by maxdeviant** [comment] 2019-08-29 19:40
Not using RxJS, but I can confirm that a number of spots in our codebase where type inference was working before (in 3.4.1) broke after upgrading to 3.6.2.

**Comment by weswigham** [comment] 2019-08-29 22:43
So, this is my minimal repro:
```ts
declare function of<T>(a: T): Observable<T>;
declare function from<O extends ObservableInput<any>>(input: O): Observable<ObservedValueOf<O>>;

type ObservedValueOf<O> = O extends ObservableInput<infer T> ? T : never;

interface Subscribable<T> {
    subscribe(next?: (value: T) => void, error?: (error: any) => void, complete?: () => void): void;
}
type ObservableInput<T> = Subscribable<never>;


export declare class Observable<T> implements Subscribable<T> {
    subscribe(next?: (value: T) => void, error?: (error: any) => void, complete?: () => void): void;
}

function asObservable(input: string | ObservableInput<string>): Observable<string> {
    return typeof input === 'string' ? of(input) : from(input)
}
```

The `Subscribable<never>` is ultimately what produces the `unknown` inference result, looks like. If `ObservableInput` only contains a `Subscribable<T>`, there's no problem. I'll look into why our inference is `unknown` now~

**Comment by weswigham** [comment] 2019-08-29 22:56
Haaaaaaaaaaaaaaaaaaaaaah the issue is with our new inference matching code. We try to infer from `Subscribable<never>` to `Subscribable<T> | Subscribable<never>` - we match `Subscribable<never>` up to itself, strip it, then say "welp, nothing left in the source, must be done", and do not produce an inference for `T`. Now, since there's no inference for `T`, we assign it `unknown`, which then is union'ed with the inference from the other input type options once that flows out of the conditional and effectively erases 'em.

**Comment by fatcerberus** [comment] 2019-08-30 05:11
> We try to infer from Subscribable<never> to Subscribable<T> | Subscribable<never> - we match Subscribable<never> up to itself, strip it, then say "welp, nothing left in the source, must be done"

This actually makes perfect sense to me.  Since `Subscribable<never>` matches itself, `T` is effectively a phantom type in that context.  Like if you have `type Maybe<T> = [ 'nil' ] | [ 'just', T ]`, then in the case of `nil` you can use it for any `Maybe<T>` you want because `T` isn't used.

I guess it's not too nice if it breaks real-world code though. :wink:

**Comment by fatcerberus** [comment] 2019-08-30 15:40
> Since `Subscribable<never>` matches itself, `T` is effectively a phantom type in that context.

While the above is true, I did subsequently realize it probably makes the internal union order observable in unexpected ways, which isn't too nice from a theoretical basis either*.  So :+1: to #33154 from me.

<sup>* Always remember to put down the hood when done working on the car lest people hotwire stuff after you walk away. :car: :stuck_out_tongue:</sup>

**Comment by benlesh** [comment] 2019-09-01 02:00
Here's another one that is broken:

```ts
import { defer, of } from 'rxjs';

const a$ = defer(() => of(1)); // $ExpectType<number>
```
// In 3.6, this is now `Observable<never>`

**Closed** 2019-09-05 13:27 UTC
Labels: Bug, High Priority

**Comment by DanielRosenwasser** [comment] 2019-09-09 21:03
Can you all try out `typescript@3.6.3-insiders.20190909` on npm?

**Comment by simeyla** [comment] 2019-12-27 02:04
I've seen some cases where VSCode has chosen to put something like :

    import { combineLatestMap } from 'src/app/shared/util/rxjs';

instead of 

    import { combineLatestMap } from '../../../../shared/util/rxjs';

I've seen this cause similar problems with inference - that sometimes work and sometimes don't. 

So check your imports aren't absolute. (And yes this is a custom operator)
