### ISSUE TITLE
Uninitialized field with non-nullable type is undefined with strict null checks

### ISSUE THREAD

**Issue by lunaryorn** [Microsoft/TypeScript#15170] opened 2017-04-13 08:46 UTC
**TypeScript Version:**  2.2.2

**Code**

```ts
class Foo {
  public foo: number;
}

const assertIsDefined = (n: number) => {
  if (n === undefined) {
    throw new Error('n was undefined!');
  }
};

assertIsDefined((new Foo()).foo);
```

**Expected behavior:**

With `--strictNullChecks` the compiler should reject this code, because the value of the uninitialized field `foo` is `undefined` which is not assignable to the parameter type of `assertIsDefined`.

Perhaps it should even reject this code because the field is not initialized and thus has the value `undefined` even though `undefined` is not assignable to the field type. 

**Actual behavior:**

The code compiles with `--strictNullChecks`, and throws an error because `foo` is undefined **at runtime** even though the types to not allow `undefined` anywhere.

**Comment by aluanhaddad** [comment] 2017-04-14 09:12
TypeScript could require marking the property as optional or require it to have an initializer expression. Unfortunately, that would be a major breaking change.

**Comment by lunaryorn** [comment] 2017-04-14 09:31
But isn't the current behaviour unsound and very risky? 

I found this issue when I forgot to initialise a variable, and had an undefined error at runtime at a totally different place where all types involved did not allow `undefined`.

I thought `strictNullChecks` would protect against uninitialised variables; to discover that it does not and even leaks `undefined` into types that prohibit `undefined` is quite a nasty surprise to be honest.

**Comment by mhegazy** [comment] 2017-04-21 20:59
Duplicate of https://github.com/Microsoft/TypeScript/issues/8476

**Closed by mhegazy** 2017-04-21 20:59 UTC
