### ISSUE TITLE
Dynamic import with Promise.all not working correctly.

### ISSUE THREAD

**Issue by vajahath** [microsoft/TypeScript#45631] opened 2021-08-30 08:20 UTC
When I put more than 10 dynamic imports on `Promise.all` typing breaks.

# Bug Report
### 🔎 Search Terms
`promise.all`, `dynamic import`

### 🕗 Version & Regression Information
Spotted on `^4.4.2`
Not sure about older versions.

### ⏯ Playground Link
Since this depends on importing modules, I'm attaching here the zip (manly 3 files, `index.js`, `package.json`, `tsconfig.json`) instead of playground link.

### 💻 Code
`tsconfig.json`
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2020"
  },
  "compileOnSave": true,
  "include": ["src"]
}
```
When I put more than 10 entries on `Promise.all`, typing breaks.
```ts
// 10 entries - no problem
async function importTest() {
  const k = await Promise.all([
    import("lru-cache"),
    import("lru-cache"),
    import("lru-cache"),
    import("lru-cache"),
    import("lru-cache"),
    import("lru-cache"),
    import("lru-cache"),
    import("lru-cache"),
    import("lru-cache"),
    import("dayjs"),
    // import("lru-cache"),
    // import("lru-cache"),
  ] as const);
}
```
Now uncommenting 11th entry
```ts
async function importTest() {
  const k = await Promise.all([
    import("lru-cache"),
    import("lru-cache"),
    import("lru-cache"),
    import("lru-cache"),
    import("lru-cache"),
    import("lru-cache"),
    import("lru-cache"),
    import("lru-cache"),
    import("lru-cache"),
    import("dayjs"),
    import("lru-cache"), // <- 11th entry
    // import("lru-cache"),
  ] as const);
}
```
resulting in
(attaching the zip here 💼 [test-ts.zip](https://github.com/microsoft/TypeScript/files/7075259/test-ts.zip))
```
src/issue-1.ts(2,9): error TS6133: 'k' is declared but its value is never read.
src/issue-1.ts(2,31): error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'readonly [Promise<typeof LRUCache>, Promise<typeof LRUCache>, Promise<typeof LRUCache>, Promise<typeof LRUCache>, Promise<typeof LRUCache>, ... 5 more ..., Promise<...>]' is not assignable to parameter of type 'Iterable<typeof LRUCache | PromiseLike<typeof LRUCache>>'.
      The types returned by '[Symbol.iterator]().next(...)' are incompatible between these types.
        Type 'IteratorResult<Promise<typeof LRUCache> | Promise<typeof dayjs>, any>' is not assignable to type 'IteratorResult<typeof LRUCache | PromiseLike<typeof LRUCache>, any>'.
          Type 'IteratorYieldResult<Promise<typeof LRUCache> | Promise<typeof dayjs>>' is not assignable to type 'IteratorResult<typeof LRUCache | PromiseLike<typeof LRUCache>, any>'.
            Type 'IteratorYieldResult<Promise<typeof LRUCache> | Promise<typeof dayjs>>' is not assignable to type 'IteratorYieldResult<typeof LRUCache | PromiseLike<typeof LRUCache>>'.
              Type 'Promise<typeof LRUCache> | Promise<typeof dayjs>' is not assignable to type 'typeof LRUCache | PromiseLike<typeof LRUCache>'.
                Type 'Promise<typeof dayjs>' is not assignable to type 'typeof LRUCache | PromiseLike<typeof LRUCache>'.
                  Type 'Promise<typeof dayjs>' is not assignable to type 'PromiseLike<typeof LRUCache>'.
                    Types of property 'then' are incompatible.
                      Type '<TResult1 = typeof dayjs, TResult2 = never>(onfulfilled?: ((value: typeof dayjs) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<...>) | null | undefined) => Promise<...>' is not assignable to type '<TResult1 = typeof LRUCache, TResult2 = never>(onfulfilled?: ((value: typeof LRUCache) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<...>) | null | undefined) => PromiseLike<...>'.
                        Types of parameters 'onfulfilled' and 'onfulfilled' are incompatible.
                          Types of parameters 'value' and 'value' are incompatible.
                            Type 'typeof dayjs' is not assignable to type 'typeof LRUCache'.
                              Type 'typeof dayjs' provides no match for the signature 'new <K, V>(options?: Options<K, V> | undefined): LRUCache<K, V>'.
```
![Animation](https://user-images.githubusercontent.com/12165822/131308159-4dcb3c52-4f60-4358-81d1-4e2dbbfc6ed1.gif)

### 🙁 Actual behavior
The compiler throws erros.
### 🙂 Expected behavior
There shouldn't be any errors.

**Comment by andrewbranch** [comment] 2021-09-01 00:05
Duplicate of https://github.com/microsoft/TypeScript/issues/22469, should be fixable with or after https://github.com/microsoft/TypeScript/pull/45350

**Closed** 2021-09-03 18:00 UTC
Labels: Duplicate
