### ISSUE TITLE
Wrong type inference when type should be union typed

### ISSUE THREAD

**Issue by ffMathy** [microsoft/TypeScript#46641] opened 2021-11-02 14:48 UTC
# Bug Report

### 🔎 Search Terms
- "Ternary if type inference"

### 🕗 Version & Regression Information
This seems to appear on all versions, so unsure if it's a bug actually. I just find the behavior "weird".

### ⏯ Playground Link
Example 1: https://www.typescriptlang.org/play?ts=4.4.4#code/C4TwDgpgBAKuECEoF4oG8BQVtQGYHt8AuKAZ2ACcBLAOwHMBuLHAIwEMKSaBXAWxYgUmAXwwZQkWPACCKdM2wFiZSrUYZRY3NxoBjYFXw0odCMACSNcmz0QAFBzokWhADYQbASkw4oVXA4UdN4KvlAUZtwUxj5hcUokAEQA1gCOAO4AJmmZ6cmJADShcdjsnFAAjADMVQDsxTjCUGykUpAITL5NEK6k0GhQDdgRwFExQ2EJUIlKiRNNLW0Q0p2NGmLuwFAAHnKmFlbANrr2lNwQngxAA

Example 2: https://www.typescriptlang.org/play?ts=4.4.4#code/GYVwdgxgLglg9mABAcwKZQJJgM5QIaSoAUeATsgFyIBGccANqgQJQDeAUIl4jMCeW07dhpdCFJIOw6d2B0qAIgDWARwDuAE1Ua1ShQBohM4dTJUAjAGZLAdiPSAvgG57DxKnrZUiVonsixCR9-Yzk4RTCFEK5nV3YHdnZGKEQAD0QAXhR0LFwCCGIoUhBUZicgA

### 💻 Code
N/A

### 🙁 Actual behavior
In the second Playground example, the inferred type of `x` is correctly:
```typescript
{
    foo: string;
    bar: number;
} | {
    foo: string;
    bar?: undefined;
}
```

However, in the first example, the inferred type is `TypeA` instead of `TypeA|TypeB`, which I think is odd.

### 🙂 Expected behavior
As in the second Playground example, I want the inferred type of the first example to be `TypeA|TypeB`, but it infers it as `TypeA`.

**Comment by MartinJohns** [comment] 2021-11-02 15:06
[Issue template for bug reports.](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md)

**Comment by MartinJohns** [comment] 2021-11-02 15:10
> Then the inferred type of `x` is incorrectly `TypeA`. The inferred type should have been `TypeA|TypeB`.

Subtype reduction kicks in here. **Every** `TypeB` is **also** a `TypeA`, because the properties match. It's the same as #46449.

You can avoid this behaviour by adding a type annotation for the return type.

**Comment by jcalz** [comment] 2021-11-02 15:11
Yeah, this is just subtype reduction and has been part of TypeScript for... *(checks notes)* ...ever?  Or close to it.

**Comment by jcalz** [comment] 2021-11-02 15:21
> @jcalz just because it has been part of TypeScript forever, doesn't mean it can't be improved and shouldn't be discussed.

It's a feature, not a bug.  Are you filing a bug report or a feature suggestion?  There's an issue template you should be filling out either way.  Right now the onus is on you to do the things the TS team expects for someone filing an issue, before you can expect too much engagement here, unfortunately.

**Comment by ffMathy** [comment] 2021-11-02 15:29
@jcalz I filled out the issue template now. Sorry about that. The reason I chose to omit it, was because I wasn't sure how to fill out the individual fields in the template. I think it is less readable and understandable now, but I get that you want consistency.

**Comment by jcalz** [comment] 2021-11-02 15:37
You're not sure how to do this?

> 🔎 Search Terms <\!-- What search terms did you use when trying to find an existing bug report?  List them here so people in the future can find this one more easily.

When you file a bug here you should first be searching for existing issues that report the same thing so that you don't create a duplicate.  Then, when you fail to find an existing issue that is the same, you list those search terms here, so that people in the future can find *your* issue when they are looking.  If you leave required fields blank, the TS team will be less likely to do much more than close it as unactionable.  

> 💻 Code <\!-- Please post the relevant code sample here as well-->

You wrote N/A there because you weren't sure how to put the code sample in plaintext?  

> I think it is less readable and understandable now, but I get that you want consistency

Note that I'm just a nosy bystander and not a member of the TS team so you don't have to take anything I say as authoritative.  I do like me some consistency, though.

**Comment by ffMathy** [comment] 2021-11-02 15:54
> You're not sure how to do this?
> 
> > 🔎 Search Terms <\!-- What search terms did you use when trying to find an existing bug report?  List them here so people in the future can find this one more easily.
> 
> When you file a bug here you should first be searching for existing issues that report the same thing so that you don't create a duplicate.  Then, when you fail to find an existing issue that is the same, you list those search terms here, so that people in the future can find *your* issue when they are looking.  If you leave required fields blank, the TS team will be less likely to do much more than close it as unactionable.  
> 
> > 💻 Code <\!-- Please post the relevant code sample here as well-->
> 
> You wrote N/A there because you weren't sure how to put the code sample in plaintext?  
> 
> > I think it is less readable and understandable now, but I get that you want consistency
> 
> Note that I'm just a nosy bystander and not a member of the TS team so you don't have to take anything I say as authoritative.  I do like me some consistency, though.  

I filled in the search terms now. Missed it when going through the template.

I wrote N/A because the two playground links have more than enough sufficient code to show what the point is. In fact, more than should be necessary.

And I wouldn't call it being "nosy". I'd call it being plain arrogant. I get that you're - probably a good help to the TypeScript team by catching naughty people who do not comply with the templates and what not (and I changed my report too to comply), but you don't have to do it in a hostile way.

**Comment by jcalz** [comment] 2021-11-02 16:14
I think hostility/arrogance  must be in the eye of the beholder, but it’s probably more productive at this point for me to bow out of this conversation and leave the issue in the hands of those whose behavior I hope you’ll find more palatable. Good luck to you!

**Closed** 2021-11-05 18:00 UTC
Labels: Duplicate
