### ISSUE TITLE
Generics derived from inheritance do not work properly!

### ISSUE THREAD

**Issue by dangaogit** [microsoft/TypeScript#42896] opened 2021-02-20 03:57 UTC
# Bug Report

### 🔎 Search Terms

`extends`
`generic`

### 🕗 Version & Regression Information

v4.1.5
- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.5&ssl=15&ssc=2&pln=1&pc=1#code/C4TwDgpgBAIhFgAoEMBOwCWyA2AeAKgHxQC8UA3gLABQUdUA2olBgHZQDWEIA9gGZR8AXQD8ALkFMhUCAA9gEVgBMAzlAAUbPhFRQAqgEoG0kfuNQJ+KQG4aAX1vUayAEYrgqZAGNgUL9mQVNQAhQOgqWnpgcSh3VDYAc0c7Gho+AFdWHwwedgB3HlQORPUeFwArCTgEFHQsPFCVCEIDChp6KDLygDpfMgAifuTU6gyszFyoVh5gAHVC4tYEghl5RVUoRubSiqr4JDRMHAIWtsi6Lt7SKEHkoA)

### 💻 Code

```ts
type DeepPartial<T> = {
    [P in keyof T]?: T[P] extends (infer U)[] ? U[] : T[P];
};

abstract class Base {
    t?: string;
}

function working(obj: DeepPartial<Base>) {
    obj.t = "";
}

function notWorking<T extends Base>(obj: DeepPartial<T>) {
    obj.t = "";
}
```

### 🙁 Actual behavior
Compile time error in 'notWorking()': `Type '""' is not assignable to type '(T["t"] extends (infer U)[] ? U[] : T["t"]) | undefined'.`
### 🙂 Expected behavior
No compile time error in 'notWorking()'.

**Comment by dangaogit** [comment] 2021-02-20 04:00
If "DeepPartial" is changed to "DeepPartial1", it can work normally, but this is obviously not good!

```ts
type DeepPartial1<T> = {
    [P in keyof T]?: DeepPartial1<T[P]> | T[P];
};
```

**Comment by dangaogit** [comment] 2021-02-20 07:46
This version of DeepPartial dose NOT work too:
```ts
type DeepPartial<T> = {
    [P in keyof T]?: T[P] extends [] ? T[P] : T[P];
};
```

**Comment by jcalz** [comment] 2021-02-20 21:44
It's going to turn out that the compiler can't really verify assignability to conditional types which depend on unspecified/unresolved generic type parameters.  Assuming this isn't a duplicate of something, I'd expect to see it closed as "Design Limitation".

For the particular code here, though, is there a reason you're not using

```ts
type DeepPartial<T> = {
    [P in keyof T]?: DeepPartial<T[P]>;
};
```

Your special-casing of arrays doesn't seem to be necessary since [mapped types on tuples and arrays produce tuples and arrays](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#mapped-types-on-tuples-and-arrays):

```ts
type Foo = DeepPartial<{
    a: number[],
    b: Array<{ c: string }>,
    d: [string, number, { e: boolean }]
}>
/* type Foo = {
    a?: (number | undefined)[] | undefined;
    b?: (DeepPartial<{
        c: string;
    }> | undefined)[] | undefined;
    d?: [(string | undefined)?, (number | undefined)?, (DeepPartial<{
        e: boolean;
    }> | undefined)?] | undefined;
} */
```

[Playground link](https://www.typescriptlang.org/play?ts=4.1.5#code/C4TwDgpgBAIhFgAoEMBOwCWyA2AeAKgHxQC8UA3gLABQUdUA2olBgHZQDWEIA9gGZR8AXQD8ALljwkaTDgJMhhANw0Aviuo1QkKADEePUpIQp0WPFVr1kE1gFcAtgCMIqBkIA0NelCcSAgqioyCC45FAAxhIAzsCobADmUKqEXlZ0ACYSDLHxrAkeUPbOroXhEBJOBtgQyOyqQmqENAD0AFRQ2tD6hmSWPsjiUAAUxS6oUAA+UHasGRB8bBAZAJTuUzNzC0sZGj5OQ8NwJjLmYd4+9FFQuYl79Ckbs-OLrMtrQk9br8v3mUMMYa3fJfF47FYiQqjRzjUHbN6rSEjY7SMxyfqXOgVXzVWqsP7JYjTZ7w94iT7E747DSqKBtFo0GjIJy5ZARYCRbDIaLRKAAIW50AxdGAQ2BCRpjOofFm7IwPHYAHceKgOIlhjwnAArCQo0yyPAC6IQQgrCgXOiarUAOg5ZAARPbJZppbLMAqijxgAB1FVq-IEKAQAAewAgc15RpNGu1uqk+rORDNwqgVttRkdzpoQA)

**Comment by dangaogit** [comment] 2021-02-21 02:26
> It's going to turn out that the compiler can't really verify assignability to conditional types which depend on unspecified/unresolved generic type parameters. Assuming this isn't a duplicate of something, I'd expect to see it closed as "Design Limitation".
> 
> For the particular code here, though, is there a reason you're not using the following definition?
> 
> ```ts
> type DeepPartial<T> = {
>     [P in keyof T]?: DeepPartial<T[P]>;
> };
> ```
> 
> Your special-casing of arrays doesn't seem to be necessary since [mapped types on tuples and arrays produce tuples and arrays](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#mapped-types-on-tuples-and-arrays):
> 
> ```ts
> type Foo = DeepPartial<{
>     a: number[],
>     b: Array<{ c: string }>,
>     d: [string, number, { e: boolean }]
> }>
> /* type Foo = {
>     a?: (number | undefined)[] | undefined;
>     b?: (DeepPartial<{
>         c: string;
>     }> | undefined)[] | undefined;
>     d?: [(string | undefined)?, (number | undefined)?, (DeepPartial<{
>         e: boolean;
>     }> | undefined)?] | undefined;
> } */
> ```
> 
> [Playground link](https://www.typescriptlang.org/play?ts=4.1.5#code/C4TwDgpgBAIhFgAoEMBOwCWyA2AeAKgHxQC8UA3gLABQUdUA2olBgHZQDWEIA9gGZR8AXQD8ALljwkaTDgJMhhANw0Aviuo1QkKADEePUpIQp0WPFVr1kE1gFcAtgCMIqBkIA0NelCcSAgqioyCC45FAAxhIAzsCobADmUKqEXlZ0ACYSDLHxrAkeUPbOroXhEBJOBtgQyOyqQmqENAD0AFRQ2tD6hmSWPsjiUAAUxS6oUAA+UHasGRB8bBAZAJTuUzNzC0sZGj5OQ8NwJjLmYd4+9FFQuYl79Ckbs-OLrMtrQk9br8v3mUMMYa3fJfF47FYiQqjRzjUHbN6rSEjY7SMxyfqXOgVXzVWqsP7JYjTZ7w94iT7E747DSqKBtFo0GjIJy5ZARYCRbDIaLRKAAIW50AxdGAQ2BCRpjOofFm7IwPHYAHceKgOIlhjwnAArCQo0yyPAC6IQQgrCgXOiarUAOg5ZAARPbJZppbLMAqijxgAB1FVq-IEKAQAAewAgc15RpNGu1uqk+rORDNwqgVttRkdzpoQA)

# I think the problem here should be this:
[Playground link](https://www.typescriptlang.org/play?ts=4.1.5#code/LAKAhgRgzgLgTmAxjABIgNmKUUCEsCmKA3qCuSjAPwBcKscAlgHYDmA3KAL6igwCeAByIARAgUEAFMHBiMw6ADwAVAHwoAvCTIUA2pJQsUAawL8A9gDMUygLq0bKAgA8YBZgBMc+KESo39WxQ6ZUDOEC5w0EsAV2ZkRnNmFAB3czhjFlYACnMIACs6MQlpWXklHwJVAEptEAoUPPyAOlQtACJ28J4QaLiEpJRmcxgAdXTMthUnV3cvPEJVXIKi8SkZOQUVGrqGptbNFE7u3hAgA)
```ts
type DeepPartial<T> = {
    [P in keyof T]?: T extends Base ? T[P] : T[P];
};
```
Even if there are no tuples, 'not working' still doesn't work properly. Semantically, 'not working' should work properly

**Comment by dangaogit** [comment] 2021-02-22 03:26
Here is the complete definition code for 'typeorm'
```ts
export declare type DeepPartial<T> = {
    [P in keyof T]?: T[P] extends Array<infer U> ? Array<DeepPartial<U>> : T[P] extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>> : DeepPartial<T[P]> | T[P];
};
```

**Comment by RyanCavanaugh** [comment] 2021-02-22 19:30
In general this sort of counterfactual analysis isn't possible - given an arbitrary `T[K]` and a nonlinear transformation like `DeepPartial`, there's no way to know what type *could* come out the other side in an instantiated form.

**Comment by dangaogit** [comment] 2021-02-23 00:50
> In general this sort of counterfactual analysis isn't possible - given an arbitrary `T[K]` and a nonlinear transformation like `DeepPartial`, there's no way to know what type _could_ come out the other side in an instantiated form.

## First of all, I can't infer a type even if I make it the same on both sides
```ts
type DeepPartial<T> = {
    [P in keyof T]?: T extends Base ? T[P] : T[P];
};

abstract class Base {
    t?: string;
}

function notWorking<T extends Base>(obj: DeepPartial<T>) {
    obj.t = "";
}
```
## Secondly, from the business point of view, judging the type of T [k] to get different branches is the right business, semantically speaking

**Closed** 2021-06-01 22:36 UTC
Labels: Design Limitation
