### ISSUE TITLE
JSX element is not transformed to `React.createElement` when inside a spread

### ISSUE THREAD

**Issue by EgoziE** [microsoft/TypeScript#54984] opened 2023-07-12 12:01 UTC
# Bug Report

### 🔎 Search Terms

JSX, spread, React.createElement

### 🕗 Version & Regression Information

5.1

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.6#code/DwYQ9gtgDgBATgSwOYAsAuBeA3sAJggNwD4APYAen2IF8YsA6RrGAdzjADskAuGPQ0hSpFq1ckSA)

### 💻 Code

```ts
<Comp right={<div>x</div>} {...{ wrong: <div>x</div>}}/>
```

### 🙁 Actual behavior

```
React.createElement(Comp, { right: React.createElement("div", null, "x"), wrong: <div>x</div> });
```

### 🙂 Expected behavior
Works with version 5.0.4

```
React.createElement(Comp, Object.assign({ right: React.createElement("div", null, "x") }, { wrong: React.createElement("div", null, "x") }));
```

**Comment by fatcerberus** [comment] 2023-07-12 13:03
Probably a duplicate of https://github.com/microsoft/TypeScript/issues/54411 (see last comment)

**Comment by marsiancba** [comment] 2023-07-13 14:08
Just hit this bug when upgrading to 5.1.
Also in 5.2.0 beta

**Closed** 2023-07-13 16:46 UTC
Labels: Bug
