### ISSUE TITLE
Type inference fails for generic React props with JSX syntax, works with regular syntax

### ISSUE THREAD

**Issue by alshain** [Microsoft/TypeScript#16499] opened 2017-06-13 19:23 UTC
**TypeScript Version:**  2.3.4

**Code**

With the react TS starter pack: `create-react-app.cmd generics-fail --scripts-version=react-scripts-ts`, modify index.tsx as follows:

```ts
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import registerServiceWorker from './registerServiceWorker';
import './index.css';

interface Problematic<T> {
    key: T;
}

interface Props<T, R> {
    data: T;
    renderer: (props: Problematic<T>) => React.ReactElement<R>;
}

class InferenceFail<T, R> extends React.Component<Props<T, R>, {}> {

}

class Data {
  key: string;
}

let works = new InferenceFail({data: new Data(), renderer: ({key}) => <div>{key.key}</div>});

let fails = <InferenceFail data={new Data()} renderer={({key}) => <div>{key.key}</div>} />;
//                                                                          ^^^

ReactDOM.render(
  (
    <div>
    {works}
    {fails}
  </div>),
  document.getElementById('root') as HTMLElement
);
registerServiceWorker();

```

**Expected behavior:**

No compiler error. The `InferenceFail` instance should be correctly inferred to have actual type parameter `Data` for `T`.

**Actual behavior:**

Compiler error: 

> (25,77): error TS2339: Property 'key' does not exist on type '{}'.

`T` is inferred to be `{}`.

**Comment by mhegazy** [comment] 2017-06-13 20:21
duplicate of https://github.com/Microsoft/TypeScript/issues/14729

**Comment by mhegazy** [comment] 2017-08-17 18:07
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-08-17 18:07 UTC
Labels: Duplicate
