### ISSUE TITLE
Using a keyword in an argument expression should return a better error message than 'Argument expression expected'

### ISSUE THREAD

**Issue by eonarheim** [Microsoft/TypeScript#29579] opened 2019-01-25 13:55 UTC
**TypeScript Version:**  3.3.0-dev.201xxxxx

[typescript@next repro](https://github.com/eonarheim/typescript-confusingerror)

**Search Terms:**
[Argument Expression Expected](https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Argument+expression+expected)
[Argument Expression](https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Argument+expression)
[Keyword Argument Expression](https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+keyword+argument+expression)
[Keyword Argument](https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+keyword+argument)
[Keyword](https://github.com/Microsoft/TypeScript/issues?q=is%3Aissue+keyword+is%3Aopen)

**Code**

See in [TypeScript Playground](https://www.typescriptlang.org/play/index.html#src=%0D%0Alet%20array%20%3D%20%5B1%2C%202%2C%203%5D%3B%0D%0A%0D%0A%2F%2F%20Works%0D%0Aarray.map(d%20%3D%3E%20console.log(d))%3B%0D%0A%0D%0A%2F%2F%20Doesn't%20work%20as%20expected%2C%20but%20with%20confusing%20error%20message.%0D%0A%2F%2F%20Perhaps%20%22Cannot%20use%20'default'%20keyword%20in%20argument%20expression%22%3F%0D%0Aarray.map(default%20%3D%3E%20console.log(default))%3B%0D%0A%2F%2F%20Error%20message%3A%0D%0A%2F%2F%20Argument%20expression%20expected%0D%0A%2F%2F%20Argument%20of%20type%20'void'%20is%20not%20assignable%20to%20parameter%20of%20type%20'(value%3A%20number%2C%20index%3A%20number%2C%20array%3A%20number%5B%5D)%20%3D%3E%20%7B%7D'%0D%0A%0D%0A)

```ts

let array = [1, 2, 3];

// Works
array.map(d => console.log(d));

// Doesn't work as expected, but with confusing error message.
// Perhaps "Cannot use 'default' keyword in argument expression"?
array.map(default => console.log(default));
// Error message:
// Argument expression expected
// Argument of type 'void' is not assignable to parameter of type '(value: number, index: number, array: number[]) => {}'
```

**Expected behavior:**

The typescript compiler should complain with a better error message to steer developers who may not be familliar with all the JS keywords given a poor choice of variable name that is a keyword, like `default`. 

`array.map(default => console.log(default));`

We spent a few moments scratching our heads before we remembered that `default` is a keyword used in the default case in a switch statement.

**Actual behavior:**

These error messages, are fairly cryptic to what is wrong:
`Argument expression expected`
`Argument of type 'void' is not assignable to parameter of type '(value: number, index: number, array:  number[]) => {}'` 

Something to the effect of "Cannot use the 'default' keyword' as an argument" or "Cannot use 'default' keyword in argument expression" would quickly clear up the developer (my) mistake.

Thanks!

**Playground Link:** 
See in [TypeScript Playground](https://www.typescriptlang.org/play/index.html#src=%0D%0Alet%20array%20%3D%20%5B1%2C%202%2C%203%5D%3B%0D%0A%0D%0A%2F%2F%20Works%0D%0Aarray.map(d%20%3D%3E%20console.log(d))%3B%0D%0A%0D%0A%2F%2F%20Doesn't%20work%20as%20expected%2C%20but%20with%20confusing%20error%20message.%0D%0A%2F%2F%20Perhaps%20%22Cannot%20use%20'default'%20keyword%20in%20argument%20expression%22%3F%0D%0Aarray.map(default%20%3D%3E%20console.log(default))%3B%0D%0A%2F%2F%20Error%20message%3A%0D%0A%2F%2F%20Argument%20expression%20expected%0D%0A%2F%2F%20Argument%20of%20type%20'void'%20is%20not%20assignable%20to%20parameter%20of%20type%20'(value%3A%20number%2C%20index%3A%20number%2C%20array%3A%20number%5B%5D)%20%3D%3E%20%7B%7D'%0D%0A%0D%0A)

**Related Issues:** 
N/A

**Comment by DanielRosenwasser** [comment] 2019-01-27 00:18
Duplicate of #16934. Surprised I remembered well enough to dig it up.

**Closed** 2019-01-29 18:00 UTC
Labels: Duplicate
