### ISSUE TITLE
Use external modules within internal module

### ISSUE THREAD

**Issue by linvi** [Microsoft/TypeScript#909] opened 2014-10-17 11:40 UTC
I am trying to use external module within an internal module but Visual Studio won't let me do that.
As soon as I add an import x = require('xxx'); the internal module no longer consider the file to be part of the module and all exports are not referenced by the module anymore.

I have read the [Module Documentation](https://github.com/Microsoft/TypeScript/wiki/Modules) but I could not find the scenario of using external modules within an internal module.

As described in my [post](http://stackoverflow.com/questions/26410913/typescript-import-external-module-in-internal-module/26413700#26413700), I want to create a ViewModel module that will contain all the ViewModels of my application. 

The application will use Knockout in order to insure the communication between the Views and the ViewModel and I therefore need to import the knockout module.

```
// HomePageViewModel.ts
import ko = require('knockout'); // When adding this line I can no longer access HomePageViewModel from the internal ViewModels module
module ViewModels {
    export class HomePageViewModel {
        constructor() {
            console.log('Creating HomePageViewModel');
        }
    }
}
```

```
// ViewModelFactories.ts
module OtherModule {
    export class ViewModelFactories {
        public static CreateHomePageViewModel(): ViewModels.HomePageViewModel {
            return new ViewModels.HomePageViewModel();
        }
    }
}
```

**When importing the external module knockout, the internal module no longer exports the HomePageViewModel class.**

Thank you for your help.

**Comment by csnover** [comment] 2015-03-08 07:20
@RyanCavanaugh For instantiated modules, this is true. But the compiler complains in non-instantiated modules, too, which means it is impossible to describe global types in an ambient declaration if those global types refer to a type that comes from some other external module:

```ts
/// <reference path="../external/external.d.ts" />

declare module foo {
	// TS Error: Import declarations in an internal module cannot reference an external module.
	import request = require('external/request');

	interface RequestError extends Error {
		// …

		/**
		 * The response object for the request.
		 */
		response: request.IResponse;
	}

	// …
}

declare module 'foo/Bar' {
	// …
	class Bar {
		error: foo.RequestError;
		// …
	}
	export = Bar;
}

// …
```

The internal module `foo` could be written as an external module, but given the way other declaration files are authored, I think that would be considered an anti-pattern at this point.

**Comment by mhegazy** [comment] 2015-03-08 18:31
@csnover is it expected that the JavaScript molded by these definitions be accessed as both an internal module (e.g. include the js in a script tag) or required (either using an AMD loader or commonjs)? 

one pattern that i have seen is to define all your typeings in an internal module, and then have an external module to expose them as well:
```ts
declare module foo {
     function f ();
     var x;
]
declare module "foo" {
    export = foo;
}
```
The main problem is that external modules and internal modules are really different, the shared syntax does not help here obviously. The compiler can understand external modules consuming internal modules, as they just represent global objects, but it can not understand what the opposite means in absence of a loader system.

Since your code is accessible both as a module, or addition to the global namespace, i assume your dependencies are as well (e.g. 'external/request'), if your dependencies expose an internal module (something along the lines i mentioned above) then that should solve the problem.

We have the same problem with typescript definitions, and the way we worked around it is by using two files one internal and one external, though we have no dependencies that we expose in the .d.ts.

**Comment by csnover** [comment] 2015-03-08 19:42
> @csnover is it expected that the JavaScript molded by these definitions be accessed as both an internal module (e.g. include the js in a script tag) or required (either using an AMD loader or commonjs)? 

No, always required. The internal type `foo` is just for the type system, it’s never related to any real code. See https://github.com/theintern/intern/blob/typings/typings/leadfoot/leadfoot.d.ts#L5-L51 for a concrete example.

> if your dependencies expose an internal module (something along the lines i mentioned above) then that should solve the problem.

Unfortunately I don’t think it’s safe to presume that the way the external dependencies are structured could be changed, as they are, well, external.

In this concrete example above, the dependencies come from well-structured modular code, and it would be wrong for that upstream project to move all these interfaces out of external modules.

**Comment by marcinporebski** [comment] 2015-03-11 13:24
What I understand is there no option to create standalone node.js application consisting of internal modules? As using node.js requires importing external dependencies (like streams, events etc.) hence every module using these becomes external module. It's even more restrictive, extending this policy on non-module TS files, so that any file containing require can't be used as `<reference>`.
Correct me if I'm wrong, but this makes internal modules completely useless, and the only hope is in [Suggestion: multi-file external modules #17](https://github.com/Microsoft/TypeScript/issues/17).

**Comment by mhegazy** [comment] 2015-03-11 16:43
@csnover sorry for the late reply. I am a bit confused. so why do you need the internal module for your typings?

**Comment by csnover** [comment] 2015-03-11 18:40
As a convenience for generic interfaces that are used in multiple places across an entire package but don’t emit code. The alternative is to create some a separate interfaces/typedefs module, which could be OK (and would improve portability), but just runs against how these things are typically modelled right now in DefinitelyTyped. I’m mostly OK moving to that model if that’s what everyone thinks is best, but I’m sure some people will complain about all the extra typing they have to do whenever they want to use one of these generic interfaces (most developers are incredibly lazy).

**Comment by mhegazy** [comment] 2015-03-11 19:12
i see. thanks for the explanation. The problem is internal modules should have been called namespaces :). i do not think the two really mesh well just because of dependencies in external modules, and the open-ended nature of internal modules.

**Comment by mhegazy** [comment] 2015-06-12 23:50
I do not think there is more actions here that are not already captured in other issues. please reopen a new issue if this is not the case.

**Closed by mhegazy** 2015-06-12 23:50 UTC
Labels: Question
