### ISSUE TITLE
"typescript.preferences.importModuleSpecifier": "project-relative" is not as intended

### ISSUE THREAD

**Issue by jeemercado** [microsoft/TypeScript#58114] opened 2024-04-07 09:40 UTC
"typescript.preferences.importModuleSpecifier": "project-relative" is not working properly anymore after the new update. I tested this for Nx projects.

- VS Code Version: 1.88.0
- OS Version: macOS M1 Ventura 13.6

Steps to Reproduce:

1. Set typescript.preferences.importModuleSpecifier to project-relative

**Comment by andrewbranch** [comment] 2024-04-08 18:04
Can someone please provide an example repo with reproduction steps that show this happening?

**Comment by ivan-palatov** [comment] 2024-04-09 03:50
@andrewbranch created an example here https://github.com/ivan-palatov/vscode-typescript-imports-bug

Its worth mentioning that while I was recreating it, I managed to discover that on typescript 5.4.x everything works as intended, but on 5.3.3 it is happening. So, as a simple (for most) workaround, I would suggest updating typescript vertion to 5.4.x. Not sure if its happening on earlier, harder to migrate from, versions.

**Comment by andrewbranch** [comment] 2024-04-09 15:45
Thanks @ivan-palatov! I’m going to close this as fixed, but if anyone can reproduce on 5.4/nightly TS, please comment with repro steps and I’ll reopen and investigate more. I’m guessing this bug was accidentally fixed by code shuffling around in https://github.com/microsoft/TypeScript/pull/55015.

**Closed by andrewbranch** 2024-04-09 15:45 UTC
Labels: Needs More Info
