### ISSUE TITLE
add ts-ignore label Block 

### ISSUE THREAD

**Issue by L-Hknu** [microsoft/TypeScript#38739] opened 2020-05-23 02:20 UTC
invalid: ![image](https://user-images.githubusercontent.com/37376096/82719555-68043380-9cde-11ea-9219-4583af49072c.png)   
Effective: 
![image](https://user-images.githubusercontent.com/37376096/82719577-91bd5a80-9cde-11ea-84cb-26c55c541972.png)

Add block level  ignore
![image](https://user-images.githubusercontent.com/37376096/82719643-0beddf00-9cdf-11ea-9d62-7e17de96a8d6.png)

**Comment by DanielRosenwasser** [comment] 2020-05-26 20:10
Duplicate of #19573

**Closed by DanielRosenwasser** 2020-05-26 20:10 UTC
