### ISSUE TITLE
Type alias is not possible when defining abstract method.

### ISSUE THREAD

**Issue by fphh** [Microsoft/TypeScript#6832] opened 2016-02-02 10:26 UTC
This gives an compile error:
```

type t = () => void;

abstract class A {
   abstract f : t
}

```
This compiles:
```

abstract class A {
  abstract f () : void; 
}

```
Shouldn't both be possible if we support type aliases?

I used Typescript 1.7.5.

**Comment by mhegazy** [comment] 2016-02-02 18:03
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/4669

**Closed by mhegazy** 2016-02-02 18:03 UTC

**Comment by fphh** [comment] 2016-02-03 09:20
I don't see that #4669 has to do with type aliases. Actually, I think that, if my first example does not compile, this means type aliasing is not fully implemented or broken.

**Comment by cvsguimaraes** [comment] 2016-02-03 17:23
Please reopen this one.

**Comment by mhegazy** [comment] 2016-02-03 17:59
abstract properties are not  legal in TS today. #4669 tracks enabling it. This has nothing to do with type aliases..  `abstract class  C { abstract c: number; }` still does not compiler.

**Comment by fphh** [comment] 2016-02-04 09:48
If we had abstract properties, then my first example would compile? Note, that by type _f_ is still a method, not an property (even if it looks syntactically like a property).

**Comment by mhegazy** [comment] 2016-02-04 18:45
> If we had abstract properties, then my first example would compile?

yes. this is #4669
