### ISSUE TITLE
Playground is completely broken

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/TypeScript#26125] opened 2018-08-01 19:26 UTC
**Expected behavior:**

Code should be type-checked and show errors/warnings.

**Actual behavior:**

Nothing happens. There are also errors in the Chrome console (see below).

**Playground Link:**
https://www.typescriptlang.org/play/index.html#src=interface%20Woof%20%7B%0D%0A%20%20%20%20rules%3A%20object%3B%0D%0A%20%20%20%20sing%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aconst%20d%3A%20Woof%20%3D%20%7B%0D%0A%20%20%20%20sing%3A%2099%2C%0D%0A%20%20%20%20rules%3A%20'rut%20roh!'%0D%0A%7D%0D%0A

Errors in console:
```
WARNING: Promise with no error callback:2
workerMain.js:9 {exception: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at e._send …, error: null, promise: n.C…s.d…e.supportedForProcessing, handler: undefined, id: 2, …}
workerMain.js:9 TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at e._send (workerMain.js:10)
    at workerMain.js:10
    at n.Class.define.cancel.then (workerMain.js:9)
    at e._handleMessage (workerMain.js:10)
    at e.handleMessage (workerMain.js:10)
    at t.onmessage (workerMain.js:10)
    at self.onmessage (workerMain.js:11)
workerMain.js:8 Uncaught Error: Converting circular structure to JSON

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at e._send (workerMain.js:10)
    at workerMain.js:10
    at n.Class.define.cancel.then (workerMain.js:9)
    at e._handleMessage (workerMain.js:10)
    at e.handleMessage (workerMain.js:10)
    at t.onmessage (workerMain.js:10)
    at self.onmessage (workerMain.js:11)
    at JSON.stringify (<anonymous>)
    at e._send (workerMain.js:10)
    at workerMain.js:10
    at n.Class.define.cancel.then (workerMain.js:9)
    at e._handleMessage (workerMain.js:10)
    at e.handleMessage (workerMain.js:10)
    at t.onmessage (workerMain.js:10)
    at self.onmessage (workerMain.js:11)
    at workerMain.js:8
(anonymous) @ workerMain.js:8
setTimeout (async)
unexpectedErrorHandler @ workerMain.js:8
e.onUnexpectedError @ workerMain.js:8
o @ workerMain.js:8
(anonymous) @ workerMain.js:9
(anonymous) @ workerMain.js:9
setTimeout (async)
n @ workerMain.js:9
dispatchEvent @ workerMain.js:9
g @ workerMain.js:9
n.Class.derive.supportedForProcessing @ workerMain.js:9
then @ workerMain.js:9
e._handleMessage @ workerMain.js:10
e.handleMessage @ workerMain.js:10
t.onmessage @ workerMain.js:10
self.onmessage @ workerMain.js:11
```

**Comment by mattmccutchen** [comment] 2018-08-01 21:35
Hi again ffxsam!  Duplicate of #26068.

**Closed** 2018-08-01 21:38 UTC
