### ISSUE TITLE
[Ember] Intellisense dont work for this.[methodName]

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#8133] opened 2016-04-17 16:44 UTC
_From @atcq1 on March 25, 2016 13:11_

- VSCode Version:0.10.11
- OS Version:ubuntu 14.04 x64

Intellisense\autocomplete not work to call methods and property through this.methodName () / this.propertyName.

Steps to Reproduce:
1. Create route:
```
import Ember from 'ember';

export default Ember.Route.extend({
    property1: 'text',
    model(params) {
        return {};
    },
    firstMethod()
    {
        //test1
    },
    secondMethod()
    {
        //test2        
    },
    thirdMethod()
    {
        //Intellisense
        secondMethod(); //work
        this.secondMethod(); //do not work
        //Autocomplete
        property1; //work
        this.property1; //do not work
    }
});
````
2 Enter `this.second` or `this.prop` in `thirdMethod(){}`:

_Copied from original issue: Microsoft/vscode#4671_

**Comment by egamma** [comment] 2016-04-17 16:44
I don't think that Salsa supports this pattern, moving to TypeScript for comment.

**Comment by DanielRosenwasser** [comment] 2016-04-17 18:31
@sandersn you work now covers this correctly, right?

**Comment by DanielRosenwasser** [comment] 2016-04-17 22:27
Or is this a duplicate of #8110?

**Comment by sandersn** [comment] 2016-04-18 15:40
Yes, this works in Salsa (as well as TypeScript) if, in settings.json, you set "typescript.tsdk" to a directory that contains the bits from `typescript@next`.

**Closed** 2016-04-18 15:40 UTC
