### ISSUE TITLE
Is there any way to configure TypeScript differently for specific files?

### ISSUE THREAD

**Issue by jsmiith** [microsoft/TypeScript#32284] opened 2019-07-07 10:05 UTC
Is there any way I can set my class file, `Client.ts`, to compile to ES6 whilst the rest compiles to ES5?

I was getting the error `Class constructor Client cannot be invoked without 'new'`, so I set out to find an answer. According to this answer, I need to set my target to es6, so I did. That meant that Node could not run my code due to the fact that it was in ES6. Apparently, Node supports ES6 classes though, so how would I go about making only that file compile to ES6?

**Comment by MartinJohns** [comment] 2019-07-07 10:11
Kind of a duplicate of #8405 (or at least related).

**Comment by RyanCavanaugh** [comment] 2019-07-08 21:39
Short answer is "no". Long answer is also "no" 😉

**Closed** 2019-07-09 05:35 UTC
Labels: Question

**Comment by MartinJohns** [comment] 2019-07-09 06:07
@RyanCavanaugh Is there an answer between the short and the long one?
