### ISSUE TITLE
Inconsistent treatment of shorthand methods with generic Partial

### ISSUE THREAD

**Issue by russelldavis** [microsoft/TypeScript#32416] opened 2019-07-16 05:06 UTC
**TypeScript Version:** 3.5.1

**Search Terms:** inconsistent shorthand methods

**Code**

```ts
function assignPartial<T>(target: T, partial: Partial<T>): T {
  return Object.assign(target, partial)
}

let obj = {
  foo(bar: string) {}
}

assignPartial(obj, {foo: (...args) => {}})
assignPartial(obj, {foo(...args) {}})
```

**Expected behavior:**
Both calls to assignPartial are typechecked the same, with no `any` types or errors.

**Actual behavior:**
In the second call, `args` is given the type `any[]`, causing `noImplicitAny` to fail.

**Additional notes:**
- If you change `Partial<T>` to just `T`, the error goes away ([playground link](https://www.typescriptlang.org/play/#code/ATBmFcDsGMBcEsD2lgEMDO74HNIAVUAnBVAGwB4AVAPgApEAjAKwC5hKAaYAByJNLaUAlIOABvAFAgQhAKaxwhFAHlmsuADoMWXPWZdexeGSFTgAXzNnS84IybAAvOLMhQiRLQZE26WIXhIbCFxSxBLM20cfD5jUj0mLjF3RDZaDQyibHQQx2pQ81MQKNwCIzIEpJT0zMJskLFzQokgA)).
- If you keep `Partial` but hardcode the type instead of using generics, the error also goes away ([playground link](https://www.typescriptlang.org/play/#code/ATBmFcDsGMBcEsD2lgEMDO74HNIAVUAnBVAGwApYjsBTWALmFgE8AHGxUYRAIwCsANMFZESpRgWLwyAHhbtO3fgD4AlI3kcuvPsADeAKBAhCdcIRQB5fjTgA6DFlyVqdISKllVR4AF8fPqR0SroAvPo+IKCIiOQ8RIzosITwkNiq+v4g-j6OOPii0hQ6QnrRiIzkdtXU6Bmhypm+3iB5uJJi5CX65VU1hNh1Td5AA)).

**Playground Link:** 
https://www.typescriptlang.org/play/#code/ATBmFcDsGMBcEsD2lgEMDO74HNIAVUAnBVAGwB4AVAPgApYjsBTWALmEoBpgAHIk0uwLF4ZKtQCU7SsADeAKBAhCLcIRQB5AEYArJnAB0GLLnqMW3PiLITFwAL527pFsES7gAXjl2QoRIi0WkTs6LCE8JDYEnKOII52xjj4-KKktO463LL+iOy0BoWM6DGe1LH2tiBJuMICGbrZuQVFhNglFbZAA

**Related Issues:** https://github.com/microsoft/TypeScript/issues/11062, but it's a different inconsistency (and has been fixed).

**Comment by minajevs** [comment] 2019-07-16 09:04
I think this one is duplicate of https://github.com/microsoft/TypeScript/issues/32230 and is fixed with https://github.com/microsoft/TypeScript/pull/32362

**Comment by russelldavis** [comment] 2019-07-16 14:54
#32230 is related, however the fix for that bug does not fix this one (this bug persists in the latest nightly build, 3.6.0-dev.20190716).

**Comment by russelldavis** [comment] 2019-07-26 15:50
@RyanCavanaugh @ahejlsberg mind taking a quick look (at least to triage)? This is basically the same issue as #32230 (which was put in the 3.6 milestone and partially fixed, but this variant of the issue remains).

**Closed** 2019-07-29 17:08 UTC
Labels: Bug, Fix Available
