### ISSUE TITLE
`strictNullChecks` and the compiler's code

### ISSUE THREAD

**Issue by nikeee** [Microsoft/TypeScript#23404] opened 2018-04-13 23:33 UTC
Currently, the compiler seems to be compiled without the `strictNullChecks` flag. Is there any plan to update (parts of) the code base to compile with this flag?

I know there are some parts that require a large amount of rewirting just to satisfy this flag. However, some APIs could easily be changed. Are small, partial strictNullCheck-enhancements something that would be accepted for merges?

I'm currently looking at something like [`pasers#visitNode(s)`](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/parser.ts#L34-L50) and [`scanner.setText()`](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/scanner.ts#L2050-L2054)

**Comment by RyanCavanaugh** [comment] 2018-04-13 23:40
![image](https://user-images.githubusercontent.com/6685088/38761658-6f25d2a4-3f39-11e8-868e-4ac3ca500e18.png)

**Comment by RyanCavanaugh** [comment] 2018-04-13 23:41
We're hoping to merge that PR quite soon

**Comment by DanielRosenwasser** [comment] 2018-04-13 23:42
Duplicate of #9432.

**Closed by DanielRosenwasser** 2018-04-13 23:42 UTC
Labels: Duplicate

**Comment by nikeee** [comment] 2018-04-13 23:50
Thanks!
