### ISSUE TITLE
typescript version 2.8.1 bug

### ISSUE THREAD

**Issue by tomoat** [Microsoft/TypeScript#22973] opened 2018-03-29 02:45 UTC
```sh
/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:27263
                    if (namespace.valueDeclaration &&
                                  ^
TypeError: Cannot read property 'valueDeclaration' of undefined
    at resolveEntityName (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:27263:35)
    at resolveTypeReferenceName (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:32085:20)
    at getTypeFromTypeReference (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:32232:30)
    at checkTypeReferenceNode (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:44202:24)
    at checkSourceElement (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:47664:28)
    at checkSourceElement (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:47706:28)
    at checkJSDocParameterTag (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:45056:13)
    at checkSourceElement (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:47691:28)
    at Object.forEach (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:1762:30)
    at checkSourceElement (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:47625:24)
```

There is no problem using typescript 2.7.2 for the project, but upgrade to 2.8.1 to run the error

**Comment by 0v3rst33r** [comment] 2018-03-29 05:55
Same issue for me.

**Comment by sandersn** [comment] 2018-03-29 16:59
@tomoat @0v3rst33r any idea what code makes this happen? Added a check for undefined is easy but I'd like to add a test for the fix.

**Comment by sandersn** [comment] 2018-03-29 17:15
Specifically, it's code that looks like this in a javascript file that's breaking:

```js
// Javascript containers
var a = {}
var b = function () {
  this.property = null
}
var c = class {
  constructor() { }
}
// nested Javascript containers
a.n = {}
a.m = function () {
  return 1
}
```

But presumably the initializer causing the crash is a little different or it wouldn't be causing a crash.

**Comment by kellycampbell** [comment] 2018-04-04 16:43
I'm seeing this as well, but the stack is slightly different:

```
TypeError: Cannot read property 'valueDeclaration' of undefined
    at resolveEntityName (/home/kellyc/Projects/stratis/stratis3/lib/js/kvstore/node_modules/typescript/lib/tsc.js:21909:35)
    at resolveEntityName (/home/kellyc/Projects/stratis/stratis3/lib/js/kvstore/node_modules/typescript/lib/tsc.js:21897:33)
    at resolveTypeReferenceName (/home/kellyc/Projects/stratis/stratis3/lib/js/kvstore/node_modules/typescript/lib/tsc.js:26133:20)
    at getTypeFromTypeReference (/home/kellyc/Projects/stratis/stratis3/lib/js/kvstore/node_modules/typescript/lib/tsc.js:26275:30)
    at getTypeFromTypeNode (/home/kellyc/Projects/stratis/stratis3/lib/js/kvstore/node_modules/typescript/lib/tsc.js:27281:28)
    at getTypeFromTypeNode (/home/kellyc/Projects/stratis/stratis3/lib/js/kvstore/node_modules/typescript/lib/tsc.js:27299:43)
    at tryGetTypeFromEffectiveTypeNode (/home/kellyc/Projects/stratis/stratis3/lib/js/kvstore/node_modules/typescript/lib/tsc.js:23826:24)
    at getTypeForVariableLikeDeclaration (/home/kellyc/Projects/stratis/stratis3/lib/js/kvstore/node_modules/typescript/lib/tsc.js:23643:32)
    at getWidenedTypeForVariableLikeDeclaration (/home/kellyc/Projects/stratis/stratis3/lib/js/kvstore/node_modules/typescript/lib/tsc.js:23800:24)
    at getTypeOfVariableOrParameterOrProperty (/home/kellyc/Projects/stratis/stratis3/lib/js/kvstore/node_modules/typescript/lib/tsc.js:23880:28)
```

I attached a debugger and the file it's trying to compile is a Protobuf.js generated .js file. 

In `getSymbolOfNode(node)`, the `node.symbol` is undefined.

I can try to work up a simpler example that reproduces this later today.

**Comment by sandersn** [comment] 2018-04-04 17:00
@kellycampbell A couple of notes that might help narrow things down:

1. I suspect this happens when there are conflicting names in JS vs TS files. The compiler may merge the symbols.
2. You can look at `node, node.parent, node.parent.parent` etc for a node that has a `name` or `escapedName` property. That will help you search for the name of the offending node, or its parent.

**Comment by kellycampbell** [comment] 2018-04-04 17:57
I'm attaching a minimal example which demonstrates the issue.

To reproduce, run:

```
npm install
npm run build
```
[typescript_bug_22973.zip](https://github.com/Microsoft/TypeScript/files/1876954/typescript_bug_22973.zip)

**Comment by kellycampbell** [comment] 2018-04-04 18:00
Also, I just tested and found that if you make the package declaration in the example.proto just `package hello;`, the compile step works. Adding a second level to the proto package causes the issue.

**Comment by sandersn** [comment] 2018-04-04 22:54
Here's a smaller standalone repro:

```js
var ns = {};
ns.same = (function() {
    var same = {};
    same.test = (function() {
        /** @type {ns.same.Whatever} */
        var crash;
    })();
    return same;
})();
```

I haven't tracked down the cause completely, but it's probably because `ns` has a property named `same`, but the IIFE also has a local called `same` (which is of course assigned to `ns.same` later). The binder ends up not putting a symbol on the `{}` of `var same`, but I haven't determined why yet.

**Comment by sandersn** [comment] 2018-04-05 16:01
Ah. The problem is that IIFEs don't get a symbol assigned to them. Here's an even smaller repro:

```ts
var ns = (function() {})();
/** @type {ns.Whatever} */
var crash;

var os = {};
/** @type {os.Whatever} */
var ok;
```

The `{}` that initializes `os` gets a symbol, but the `(function() {})()` that initializes `ns` does not.

**Comment by sandersn** [comment] 2018-04-05 16:25
Our IIFE story isn't complete right now, so I'm going to let IIFEs continue to not have a symbol, and instead just fix the check in `resolveEntityName` so that type names will fail to resolve.

Right now IIFEs never get any bindings from their contents, so the type names would never resolve anyway. The correct fix is for IIFEs to understand their return value, then track the return's bindings and make those available. I'm not sure how to do that given the current architecture of the binder, though. It looks like it will have to be after the binding pass, and it might be difficult (or just ugly) to do it in the checker.

**Closed** 2018-04-05 16:57 UTC
Labels: Bug, Fixed
