### ISSUE TITLE
preProcessFile doesn't find other imports after template strings

### ISSUE THREAD

**Issue by diagramatics** [microsoft/TypeScript#30878] opened 2019-04-12 03:18 UTC
**TypeScript Version:**  3.5.0-dev.20190411

**Search Terms:**
preProcessFile import

**Code**

```ts
const ts = require('typescript');
const output = ts.preProcessFile("`${foo}`; import './test';", true, true);
console.log(output.importedFiles);
```

**Expected behavior:**

`./test` should be listed in `importedFiles` as an entry to the array.

**Actual behavior:**

It doesn't. The array is empty.

Reversing the order works though.

```ts
const ts = require('typescript');
const output = ts.preProcessFile("import './test'; `${foo}`;", true, true);
console.log(output.importedFiles);
```

Note this also happens on dynamic imports too.

```ts
const ts = require("typescript");
const output = ts.preProcessFile("`${foo}`; import('./test');", true, true);
console.log(output.importedFiles);
```

Note that these repros are short for reproducability reasons. Yes, not doing static importing at the top is silly, but I found that from my use case of something similar to this:

```ts
const foo = `${someVariable}.${someOtherVariable}`;
import('./foo').then(m => m.callFunction());
```

You can drill down to having the issue also reproducible with static imports and dynamic imports with promise chaining or `async`, so anything import statement related?

**Playground Link:** 

Replicated in CodeSandbox: https://codesandbox.io/embed/5zqln3nn5n.

**Related Issues:**  None (?)

**Comment by kitsonk** [comment] 2019-10-10 17:50
Well, I just discovered that the reverse is also true.  Once you have a string literal with a variable in it, `preProcessFile()` then identifies import like statements in string literals. 🤷‍♂️

```ts
import * as ts from "typescript";

const src = '`${}`;\n`import * as doh from "ooops";\n`;';

const info = ts.preProcessFile(src, true, true);

console.log(JSON.stringify(info, undefined, "  "));
```

This will generate somethings like this:

```ts
{
  "referencedFiles": [],
  "typeReferenceDirectives": [],
  "libReferenceDirectives": [],
  "importedFiles": [
    {
      "fileName": "ooops",
      "pos": 29,
      "end": 34
    }
  ],
  "isLibFile": false
}
```

**Comment by sandersn** [comment] 2020-01-31 00:03
Probably related to #33680

**Comment by kitsonk** [comment] 2020-01-31 03:32
I would say #33680 is a duplicate of this! :-) We were here long before that one! :-)

**Comment by joscha** [comment] 2020-01-31 12:15
I think #33680 is slightly different in the sense that it doesn't seem to detect imports when the file is specified in a template string. This issue here discusses relates to missed imports *after* a template string and an incorrect import inside a template literal. I will try and produce some tests for this.

**Comment by lenkan** [comment] 2020-01-31 13:33
I added some tests and a fix for this in #36143. It does handle the simple cases. But I do think there is a lot more to it, I just haven't had the time to dive into it more. I added some more test cases locally and could force incorrect results that way.

**Comment by joscha** [comment] 2020-01-31 13:41
ah @lenkan, this complements #36546 brilliantly I think. I actually expect both of my skipped tests in #36546 to pass with your change.

**Comment by kitsonk** [comment] 2020-04-23 20:49
This is getting to be a real pain for those that rely in `preProcessFile()` like Deno.  The one PR in this area has been closed, but the problems haven't been fixed.

**Closed** 2022-03-15 22:28 UTC
Labels: Bug, API, Fix Available
