### ISSUE TITLE
A string literal type should not permit duplicate values

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#7498] opened 2016-03-13 17:30 UTC
Hi,

**Version**: 1.8.5

I would like to see an error when duplicate values are found in a string literal declaration:

```ts

type alphabet = 'a' | ... | 'x' | 'y' | 'a';  // Error: Duplicate value 'a'

```

This is most likely an unintentional inclusion.

**Comment by kitsonk** [comment] 2016-03-13 18:40
I think this actually would be a significant change in behaviour that would have unintentional impacts in a lot of ways.  Types have always collapsed duplicates as long as they don't conflict.

[For example,](http://www.typescriptlang.org/Playground#src=type%20Foo%20%3D%20%7B%20foo%3A%20string%20%7D%20%7C%20%7B%20foo%3A%20string%20%7D%20%7C%20%7B%20foo%3A%20string%20%7D%20%7C%20%7B%20foo%3A%20string%20%7D%3B%0A%20) this has always been valid in TypeScript:

```typescript
type Foo = { foo: string } | { foo: string } | { foo: string } | { foo: string };
```

**Comment by xLama** [comment] 2016-03-13 19:16
Union types permit duplicate values so I think it is by design. 

#805

Basics

Some simple rules:
**Identity: A|A is equivalent to A**

**Comment by NoelAbrahams** [comment] 2016-03-14 09:36
Yes, I see that now.

I wonder whether a distinction can be made between constructing a union type vs. initialising one with duplicates.

```ts
type a1 = 'a'; 
type a2 = 'a';

type a = a1 | a2; // Okay

type a3 = 'a' | 'a';  // Error
```

I don't see why anyone would want to do the latter.

The use-case we have is with regard to a string literal type that has a growing number of values over time. We do not want a new software engineer to add a duplicate value to the list and go away thinking they can use the new value when it is already in the list.

**Comment by mhegazy** [comment] 2016-03-14 19:41
This looks like a TSlint rule candidate. but it would be out of scope for the compiler.

**Closed by mhegazy** 2016-03-14 19:41 UTC
