### ISSUE TITLE
given x : T, bool should be a subtype of x is T

### ISSUE THREAD

**Issue by fread2281** [Microsoft/TypeScript#19557] opened 2017-10-29 02:16 UTC
If `x : T` is already known, any `bool` implies/is evidence for `x is T`.

This should help type inference for e.g.

```
function f<T, R extends T>(x: T[], p: (x: T) => x is R): R | undefined {
  for (const v of x) {
    if(p(v)){return v}
  }
}

// doesn't work
f([2,3,4], (x) => x > 3)
// works
f([2,3,4], (x): x is number => x > 3)
```
(filter, etc)

**Comment by aluanhaddad** [comment] 2017-10-30 02:18
This looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/10734

**Comment by andy-ms** [comment] 2017-10-30 14:47
There's no type guard for us to infer in the not-working case.
`x > 3` isn't correctly of type `x is number`, because `2` is a number but it would return false. When you explicitly annotate a type predicate we trust you and allow it, but inferring one in this case would be wrong.

**Closed** 2017-11-14 21:35 UTC
Labels: Working as Intended
