### ISSUE TITLE
TSC Watch crashes when class is exported as module.exports.default in JS file - cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by myfatemi04** [microsoft/TypeScript#41101] opened 2020-10-14 16:23 UTC
I get this error:
```
[12:18:51 PM] Starting compilation in watch mode...

C:\Users\legoc\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:84774
                throw e;
                ^

TypeError: Cannot read property 'kind' of undefined
    at Object.isEntityNameExpression (C:\Users\legoc\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:13169:21)
    at serializeMaybeAliasAssignment (C:\Users\legoc\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:39495:42)
    at serializeSymbolWorker (C:\Users\legoc\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:39161:49)
    at serializeSymbol (C:\Users\legoc\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:39126:38)
    at C:\Users\legoc\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:39107:25
    at Map.forEach (<anonymous>)
    at visitSymbolTable (C:\Users\legoc\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:39106:33)
    at serializeAsNamespaceDeclaration (C:\Users\legoc\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:39370:25)
    at serializeAsFunctionNamespaceMerge (C:\Users\legoc\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:39348:25)
    at serializeMaybeAliasAssignment (C:\Users\legoc\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:39525:29)
```

This happens when I create a file called "index.js" and try to compile it with `tsc -w`.

Here is my `tsconfig.json`:

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "outDir": "dist",
    "sourceMap": true,
    "strict": true,
    "target": "es2017",
    "noImplicitAny": false,
    "allowJs": true
  },
  "compileOnSave": true,
  "include": [ "src" ]
}
```

TSC breaks and doesn't offer a helpful error message.
The following is the code that can be used to reproduce this exact error.
I spent over an hour to isolate the error; it didn't mention which file produced the error or etc.
Strangely enough, running just `tsc` by itself compiles the code successfully.

```js
class TestClass {}

module.exports = {
    default: TestClass
}
```

**Comment by a-tarasyuk** [comment] 2020-10-15 09:56
It seems duplicate of https://github.com/microsoft/TypeScript/issues/41101.

**Comment by weswigham** [comment] 2020-10-19 20:45
If you mean dupe of https://github.com/microsoft/TypeScript/issues/40554 then, probably. This is definitely fixed in `master`, though.

**Closed by weswigham** 2020-10-19 20:45 UTC
Labels: Bug, Domain: Declaration Emit
