### ISSUE TITLE
infer type of tuple from single elements

### ISSUE THREAD

**Issue by phra** [Microsoft/TypeScript#15484] opened 2017-04-30 23:35 UTC
hi,

while working on [await-to-ts](https://github.com/phra/await-to-ts) i discovered that i cannot publish the [to function](https://github.com/phra/await-to-ts/blob/master/index.ts#L6) with the return type of Promise<[Error, null] | [null, T]> but only with Promise<[Error, T]> because it cannot infer correctly the tuple type on partial informations on elements. you can find a live example of this in [this branch](https://github.com/phra/await-to-ts/blob/infer-null/index.ts#L8)
![schermata da 2017-05-01 00-35-42](https://cloud.githubusercontent.com/assets/984628/25569021/47741738-2e06-11e7-81e7-f3f4089ac6f2.png)

**TypeScript Version:**  2.3.1

**Code**
[playground link](https://www.typescriptlang.org/play/index.html#src=function%20f(flag%3A%20boolean)%3A%20%5Bnumber%5D%20%7C%20%5Bstring%5D%20%7B%0A%09if%20(flag)%20%7B%0A%09%09return%20%5B0%5D%0A%09%7D%0A%0A%09return%20%5B'0'%5D%0A%7D%0A%0Aconst%20res%20%3D%20f(true)%5B0%5D%0Aif%20(typeof%20res%20%3D%3D%3D%20'number')%20%7B%0A%09res%20%2F%2F%20is%20a%20number%2C%20it%20works%20correctly%0A%7D%20else%20%7B%0A%09res%20%2F%2F%20is%20a%20string%2C%20it%20works%20correctly%0A%7D%0A%0Aconst%20res2%20%3D%20f(true)%0Aif%20(typeof%20res2%5B0%5D%20%3D%3D%3D%20'number')%20%7B%0A%09const%20tmp1%20%3D%20res%5B0%5D%20%2F%2F%20is%20string%20%7C%20number%2C%20it%20should%20be%20number%0A%7D%20else%20%7B%0A%09res%20%2F%2F%20is%20a%20string%2C%20it%20works%20correctly%0A%7D%0A%0A%0Afunction%20g(flag%3A%20boolean)%3A%20%5Bnumber%2C%20string%5D%20%7C%20%5Bstring%2C%20number%5D%20%7B%0A%09if%20(flag)%20%7B%0A%09%09return%20%5B0%2C%20'0'%5D%0A%09%7D%0A%0A%09return%20%5B'0'%2C%200%5D%0A%7D%0A%0Aconst%20res1%20%3D%20g(true)%0Aif%20(typeof%20res1%5B0%5D%20%3D%3D%3D%20'number')%20%7B%0A%09const%20tmp1%20%3D%20res1%5B0%5D%20%2F%2F%20is%20string%20%7C%20number%2C%20it%20should%20be%20number%0A%09const%20tmp2%20%3D%20res1%5B1%5D%20%2F%2F%20is%20string%20%7C%20number%2C%20it%20should%20be%20string%0A%7D%20else%20%7B%0A%09const%20tmp1%20%3D%20res1%5B0%5D%20%2F%2F%20is%20string%20%7C%20number%2C%20it%20shuold%20be%20string%0A%09const%20tmp2%20%3D%20res1%5B1%5D%20%2F%2F%20is%20string%20%7C%20number%2C%20it%20should%20be%20number%0A%7D)
```ts
function f(flag: boolean): [number] | [string] {
	if (flag) {
		return [0]
	}

	return ['0']
}

const res = f(true)[0]
if (typeof res === 'number') {
	res // is a number, it works correctly
} else {
	res // is a string, it works correctly
}

const res2 = f(true)
if (typeof res2[0] === 'number') {
	const tmp1 = res[0] // is string | number, it should be number
} else {
	res // is a string, it works correctly
}


function g(flag: boolean): [number, string] | [string, number] {
	if (flag) {
		return [0, '0']
	}

	return ['0', 0]
}

const res1 = g(true)
if (typeof res1[0] === 'number') {
	const tmp1 = res1[0] // is string | number, it should be number
	const tmp2 = res1[1] // is string | number, it should be string
} else {
	const tmp1 = res1[0] // is string | number, it shuold be string
	const tmp2 = res1[1] // is string | number, it should be number
}
```

**Expected behavior:**
based on partial informations, the type system should be able to infer tuple type correctly.
**Actual behavior:**
the type system fails to infer tuple types with partial informations about elements.

**Comment by jurajkocan** [comment] 2017-05-01 09:18
suggestion workaround with objects instead tuples: [15482](https://github.com/Microsoft/TypeScript/issues/15482)

**Comment by kitsonk** [comment] 2017-05-01 09:38
Yeah, I still think fixing this or #15482.  TypeScript _could_ narrow these types.  Certainly related though.

**Comment by phra** [comment] 2017-05-01 09:51
i think that it should be a killing feature because in my case i can use the type system to signal to the user that is trying to access the resolved value of the promise without checking before the error, because if you don't check the err variable the resolved value will have a null | T type, after checking the error the type will be correctly T.
@jurajkocan i was thinking about that, maybe i can give it a try and see, but the tuple syntax is for sure more elegant in this case.

**Comment by phra** [comment] 2017-05-04 12:42
no plan to see this FR approved soon?

**Comment by mhegazy** [comment] 2017-05-05 23:54
Duplicate of https://github.com/Microsoft/TypeScript/issues/12849

**Comment by mhegazy** [comment] 2017-05-22 22:34
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-05-22 22:34 UTC
Labels: Duplicate
