### ISSUE TITLE
Type of pointer to object is treated differently from type of object

### ISSUE THREAD

**Issue by nvlang** [microsoft/TypeScript#59104] opened 2024-07-02 04:10 UTC
### 🔎 Search Terms

inconsistent inference of type of pointer / alias in generic function

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about bugs

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240701#code/KYDwDg9gTgLgBAMwK4DsDGMCWEV1AQwFswAbYAHgDUA+ACgCg4nFUNsUB5KAQSinwCeALkbMxAHzi1aASjgBeanFQATYAkwpgKmaLFNJtSnhAxgKFQGc4lmFE0BzOAH44lANoBdOEOUX1mtoyADT0cgDeenCYCFK8-AIAdJiW8YK0yOhYOFxpAjIRcFFiaDi2cJCaZlAKLFnsuXyCANxF+sxk8ABu+CS+tDACYMAQsZlsOTxN+e4oSIQARsBQnq0A9GtwEADWgsUdwPAOSPhQKgCM-V2+qNsoEADuKHKKcF3R1gNDI2Os2ZxTBIyWbzJYrdabZZQaD7JidODHU4qABMVxuKDuj2eCiU7xSUkGw1GFQgVWWwLmi2WqzgGy2uwEUQAvkx6EygA

### 💻 Code

```ts
export function example<V>(
    functionOrArray:
        | (() => undefined)
        | (V extends string ? V[] : undefined),
) {
    if (Array.isArray(functionOrArray)) { 
        const pointer = functionOrArray; 
        let val: (typeof functionOrArray)[number]; // okay
        let guard1: (v: unknown) => v is (typeof functionOrArray)[number]; // error
        let guard2: (v: unknown) => v is (typeof pointer)[number]; // okay
    }  
}
```

### 🙁 Actual behavior

`(v: unknown) => v is (typeof alias)[number]` works, but `(v: unknown) => v is (typeof functionOrArray)[number]` doesn't.

### 🙂 Expected behavior

Expected `alias` and `functionOrArray` to either both work or both not work.

**Comment by MartinJohns** [comment] 2024-07-02 05:17
Duplicate of #9998.

**Comment by RyanCavanaugh** [comment] 2024-07-09 22:51
`typeof` in that position is going to use the non-control-flowed (i.e. declared, not narrowed) type of the variable, and `pointer` and `functionOrArray` have different declared types

**Closed** 2024-07-12 01:31 UTC
Labels: Working as Intended
