### ISSUE TITLE
Define literal type during object declaration

### ISSUE THREAD

**Issue by kube** [Microsoft/TypeScript#14194] opened 2017-02-20 22:10 UTC
# Problem

During object declaration, there is no way to explicitly define a property literal type:

```ts
const obj = {
  hello: 'world'
}
```

Here `typeof obj` is `{ hello: string }`

# Example of Use Case

In the case of a Redux Action, which will be constant, I expect `type` property to be a literal type:

```ts
const increment = {
  type: 'INCREMENT'
}

const decrement = {
  type: 'DECREMENT'
}

export type Action =
  & typeof increment
  & typeof decrement
```

# Current Workaround

It's possible to explicitly define the literal type after the value:

```ts
const increment = {
  type: 'INCREMENT' as 'INCREMENT'
}
```

Which causes two problems:
- redundancy
- misspelling won't be analysed (`'foo' as 'bar'` will work)

****

`readonly` would be a solution, but does not seem to be compatible with object declaration syntax.

**Comment by mhegazy** [comment] 2018-02-08 21:17
Duplicate of  #17363 and https://github.com/Microsoft/TypeScript/issues/20271 and others. please see https://github.com/Microsoft/TypeScript/issues/20271#issuecomment-347020203 and  #10676 for more context.

**Closed** 2018-02-26 20:43 UTC
Labels: Duplicate
