### ISSUE TITLE
Better handlng of hyphenated properties

### ISSUE THREAD

**Issue by chocolatechipui** [microsoft/TypeScript#4032] opened 2015-07-26 22:48 UTC
It is common in JavaScript to have hyphenated property names. For example:

```
var obj = {
   "foo-bar" : "Foo Bar"
};
```

The property "foo-bar" can be accessed like so:

```
obj["foo-bar"] \\ returns "Foo Bar"
```

From my use of TypeScript I've noticed that when using these in code or interfaces, TypeScript does not seem to reveal them as possible values. I'm talking about Intellisense, code completion, etc. I've noticed that when examining these types of properties in the Safari Web inspector, that it is aware these properties exist on the object. When you type `obj[` it will pop up all the possible object properties including the hypenated ones. 

I would hope it would be possible to reveal hyphenated object properties to the end user so that they can get completion for these types of hyphenated properties.

Here is an example of a recent ambient declaration I wrote:

```
interface fetch {
    (input: string, init?: {
      method?: {
        delete?: string, 
        get?: string, 
        head?: string, 
        options?: string, 
        post?: string, 
        put?: string
      },
      headers?: {
        Accept?: string;
        "Accept-Language"?: string;
        "Content-Language"?: string;
        "Content-Type"?: {
          "text/plain"?: string;
          "application/x-www-form-urlencoded"?: string;
          "multipart/form-data"?: string;
        }
      },
      body?: any;
    }): Promise<any>;
}
```

When the user types:

```
fetch('a/b/c/d', {
   headers: {
   }
});
```

Only the value `Accept` gets revealed, the other hyphenated values are ignored. Trying to use bracket notation does not work.

**Comment by mhegazy** [comment] 2015-07-26 23:25
That is a missing feature in the language service API. The assumption is that you will call getCompletions after a dot, something that is hyphenated is not valid after a dot; what we need to do is for get completions to return a substitution string, i.e. `a.|` => `a["accept-language"]`.

**Comment by mhegazy** [comment] 2015-07-26 23:26
We would be open to take a PR for this if you are interested.

**Comment by chocolatechipui** [comment] 2015-07-27 03:46
I'm assuming that's in ```tsserver.js```. From looking at that method, it appears that the real one of interest is ```getCompletionsAtPosition```, which is ```server/client.ts```.  I don't see any documentation regarding the internal workings, not even comments. At least some types are there. Is there any documentation for tsserver.js?

**Comment by danquirk** [comment] 2015-07-27 20:20
There's some amount of documentation in the wiki in the same section as this page: https://github.com/Microsoft/TypeScript/wiki/Architectural-Overview

**Comment by mhegazy** [comment] 2015-07-27 21:18
one thing to note here, is we need to do this in a way that is backward compatible, i.e. editor using the services today would not need ot make changes (or just minimum if at all).

**Comment by bawr** [comment] 2015-07-30 11:50
This issue is of particular interest to me as well. I wouldn't mind working on it over the weekend, but I have one question first, since my Google-fu failed, and I don't want to break my TSC setup just yet. ;)

When I make my changes and I want to test them in Visual Studio, is it enough to overwrite the `typescriptServices.ts` file in the `..\CommonExtensions\Microsoft\TypeScript` directory with the generated (new) version, or is the process more involved?

**Comment by DanielRosenwasser** [comment] 2015-07-30 14:54
@bawr I would use Dev mode and have your language service file point to the one in your `built/local` folder instead, though, if you build with errors, your language service might crash. We need to modify our Jakefile to avoid this.

See https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio

**Comment by bawr** [comment] 2015-07-30 15:12
Sweet!

I actually browsed through the wiki, but I neglected to look at the page listing *after* scrolling down, heh.

**Comment by DanielRosenwasser** [comment] 2015-09-29 06:28
Is this a duplicate of #606?

**Comment by mhegazy** [comment] 2015-09-29 16:21
it is related, #606 is mainly about specialized signatures.

**Comment by DanielRosenwasser** [comment] 2016-04-20 20:31
Okay, now that specialized signatures are just a weird special case of using string literal types, is this a duplicate of #606?

**Comment by mhegazy** [comment] 2016-04-20 21:03
it is related but not a duplicate.

**Comment by matt-subroot** [comment] 2019-07-27 21:02
How are hyphenated properties handled now? Stuck on this today. Thanks!

**Comment by fuafa** [comment] 2019-07-31 04:45
Seems this is fixed already

**Comment by matt-subroot** [comment] 2019-07-31 04:54
Can you please provide an example of syntax or a link to such syntax?

**Comment by fuafa** [comment] 2019-07-31 05:13
![image](https://user-images.githubusercontent.com/20750310/62185271-58ed7700-b394-11e9-80bc-e4296d0c1cde.png)

Trigger suggestion inside headers.

**Comment by RyanCavanaugh** [comment] 2024-03-22 23:48
Works now, though note that this requires a compliant language service host that can handle non-insertive completions

**Closed by RyanCavanaugh** 2024-03-22 23:48 UTC
Labels: Suggestion, Help Wanted, API
