### ISSUE TITLE
`that !== null && typeof that === "object"` still claims that `that` can be `null`

### ISSUE THREAD

**Issue by derolf** [microsoft/TypeScript#40363] opened 2020-09-03 09:24 UTC
**TypeScript Version:**  4.0.2

**Search Terms:**

typeof, object, narrow, if, null

**Code**

```ts
function broken(that: unknown): object {
  if (that !== null && typeof that === "object") {
    return that;  // <--- ts(2322)
  }
  return {};
}

function works(that: unknown): object {
  if (typeof that === "object" && that !== null) {
    return that;
  }
  return {};
}
```

**Expected behavior:**

Compile.

**Actual behavior:**

Fails with error

```
Type 'object | null' is not assignable to type 'object'.
  Type 'null' is not assignable to type 'object'.ts(2322)
```

**Playground Link:** 

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAIwE5wNYFMwAooAWAhlAFyLgZhwDuYAlOXMgFZbSIDeAUIojMET5iURAEIAvBMRgQAGzmIAZEsRQAngAcscQYRKIp0gETM20Y-S68+iVFighUSfVADcNgL437j5108Pb25QSFgERBo4VAwAZ2ESckpqOkZEM3ZRHj4BIQ1tXTURQylEU1ZM42VVV3FS2QUrbNtfJxcRDz5vPlb-TkDuTyA

**Comment by MartinJohns** [comment] 2020-09-03 10:17
Duplicate of #28131. Search terms used: `null object`

**Comment by RyanCavanaugh** [comment] 2020-09-09 16:59
Thanks @MartinJohns!

**Closed** 2020-09-11 18:00 UTC
Labels: Duplicate
