### ISSUE TITLE
Add Constructor<T> to lib.es5.d.ts

### ISSUE THREAD

**Issue by mlhaufe** [microsoft/TypeScript#41656] opened 2020-11-23 18:28 UTC
## Search Terms

Constructor, utility type, lib.es5.d.ts 

## Suggestion

The following type should be added to lib.es5.d.ts:

```ts
type Constructor<T> = new (...args: any[]) => T
```

## Use Cases

This is a common pattern used in mixins and other class oriented declarations:

This also complements the existing utility types:

![image](https://user-images.githubusercontent.com/826584/100000161-cfcb3200-2d86-11eb-81c4-9cde7657ab98.png)

## Examples

```ts
type Constructor<T> = new(...args: any[]) => T;

function Tagged<T extends Constructor<{}>>(Base: T) {
    return class extends Base {
        _tag: string;
        constructor(...args: any[]) {
            super(...args);
            this._tag = "";
        }
    }
}

const TaggedPoint = Tagged(Point);
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-11-23 19:40
Duplicate of #20256.

**Closed** 2020-11-26 18:00 UTC
Labels: Duplicate
