### ISSUE TITLE
Re-export type from another module

### ISSUE THREAD

**Issue by magic-akari** [microsoft/TypeScript#50122] opened 2022-08-01 06:20 UTC
# Suggestion

## 🔍 Search Terms

- TS1383
- re-export type

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow re-export type.

We can use `export from` statement in JavaScript..

```JavaScript
export { foo } from "mod"
```

and in TypeScript, we can export type from another module.

```TypeScript
export type { foo } "mod";
// or
export { type foo } from "mod";
```

Note: They are different when transforming to JavaScript.
The first statement will be removed and the second will be `export {} from "mod"` or `import "mod"`.

When it comes to re-export, for example,

```JavaScript
export * from "mod";
```

If we try to write 

```TypeScript
export type * from "mod";
```
We will get a TS1383 error. 

```
Only named exports may use 'export type'.
```

## 📃 Motivating Example

To be added.

I have no strong need for it, just as a record.

## 💻 Use Cases

`export * from "mod"` will generate runtime export statement. To avoid this, one has to list all the type.

```TypeScript
export type { foo, bar, baz, ...and more } from "mod";
```

**Comment by whzx5byb** [comment] 2022-08-01 06:35
Duplicate of https://github.com/microsoft/TypeScript/issues/37238

**Closed** 2022-08-07 18:00 UTC
Labels: Duplicate
