### ISSUE TITLE
Type guard narrowing doesn't work on index lookup

### ISSUE THREAD

**Issue by aaronbeall** [Microsoft/TypeScript#19346] opened 2017-10-19 17:54 UTC
**TypeScript Version:**  2.5

**Code**

```ts
interface Stuff { [key: string]: string | number | boolean; }

const stuff: Stuff = {};
const key = "foo";
typeof stuff[key] == "string" && handleString(stuff[key])

function handleString(s: string) { }
```

**Expected behavior:**
No errors

**Actual behavior:**
Compile error on `handleString(stuff[key])` call:
```
Argument of type 'string | number | boolean' is not assignable to parameter of type 'string'.
```

(Searched and didn't find an issue...)

**Workaround:**
Extract `stuff[key]` into variable before-hand. Not too painful a workaround...

**Comment by nahuel** [comment] 2017-10-19 18:01
reported this issue on #19341 minutes ago.

**Comment by jcalz** [comment] 2017-10-19 18:22
Duplicate of #17567?

**Comment by mhegazy** [comment] 2017-10-19 18:37
Actually both issues need to be fixed for this to work, https://github.com/Microsoft/TypeScript/issues/10530 and #17567.

**Comment by mhegazy** [comment] 2017-11-02 20:04
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-11-02 20:04 UTC
Labels: Duplicate
