### ISSUE TITLE
Discriminated union not narrowing when discriminator is itself a union

### ISSUE THREAD

**Issue by Peeja** [microsoft/TypeScript#54370] opened 2023-05-24 15:17 UTC
# Bug Report

### 🔎 Search Terms

discriminated union, discriminator, narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _discriminated unions_

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play#code/C4TwDgpgBAIglgZwMYCc4Fs4DsCGwIAmAqlnAPZZQC8UAglAD5QBCjUAwmSjANwBQfbPhQAzHEmj0A3nyhRQkAFxQARDhX8AvgKERR46KxlyFEZSoBGGvtsFZhYiRy4wox+eDOqkKtioLWtgQQSAA2OCjQSBQIwPIAFtgA5srwyGiYuPjEpBT8fMCJWEkAdKb8APQVUAB6APwFRaXlfFVycvU6IlAAFIXJZZ7UVDRqKgCUCShkAO6qAHJkUElkZAQAhNaNAy1tnf3Fg5CV1e2dgt19TUfQI6M+jEwHzUN3qgGThdNzKovLqxsts8bidag1gbtTh0GkA)

### 💻 Code

```ts
type DiscriminatedUnion = A | B | CorD;

interface A {
  type: "a";
}

interface B {
  type: "b";
}

interface CorD {
  type: "c" | "d";
}

declare const thing: DiscriminatedUnion;

thing.type;
// ^? const thing: DiscriminatedUnion
thing.type;
//    ^? (property) type: "a" | "b" | "c" | "d"

if (thing.type === "a") throw "No good!";

thing.type;
// ^? const thing: B | CorD
thing.type;
//    ^? (property) type: "b" | "c" | "d"

if (thing.type === "c" || thing.type === "d") throw "No good!";

thing.type;
// ^? const thing: B | CorD
thing.type;
//    ^? (property) type: "b"
```

### 🙁 Actual behavior

`thing.type` at the end has type `B | CorD`.

### 🙂 Expected behavior

`thing.type` at the end should have type `B`, because it can never be `CorD`.

---

This may well be considered a feature that hasn't been implemented yet.

For context, here's [the type I'm trying to remove](https://github.com/oguimbal/pgsql-ast-parser/blob/6df49a58f05b6ae48c8b006d44a4b86302b2f4a4/src/syntax/ast.ts#L641-L645). This is an AST for SQL expressions. I've parsed an expression using this library, which gives me an `Expr`, but I'm only expecting to handle simpler kinds of SQL expressions, and I'd like to throw on more complex ones and narrow the type. Currently, it's harder than I'd like to kick `SelectFromUnion` out of the [large `Expr` union](https://github.com/oguimbal/pgsql-ast-parser/blob/6df49a58f05b6ae48c8b006d44a4b86302b2f4a4/src/syntax/ast.ts#L737-L761), because its `type` is `'union' | 'union all'`. Probably my best bet at this point would be a custom type guard, but it sure would be nice if TS could figure out the narrowing for me.

**Comment by MartinJohns** [comment] 2023-05-24 19:00
Duplicate of #31404.

**Closed** 2023-05-28 18:00 UTC
Labels: Duplicate
