### ISSUE TITLE
JavaScript: casting with `"checkJs": true`

### ISSUE THREAD

**Issue by bruce965** [Microsoft/TypeScript#16881] opened 2017-07-01 11:25 UTC
I opened a question on [StackOverflow](https://stackoverflow.com/q/44817856/1135019) and got no answers, so I guess this is still a missing feature.

I'm looking for a way to do a cast with JavaScript Language Service code-checker enabled.

**TypeScript Version:**  2.4.1 / 2.5.0-dev.20170629

```js
// JavaScript

const something = window.something;
```

```ts
// TypeScript equivalent

const something: SomethingConstructor = (window as any).something;
```

```js
// JavaScript with checkJs

const anyWindow = (/** @type {any} */(window));  // Property 'something' does not exist on type 'Window'.
const something = (/** @type {SomethingConstructor} */(anyWindow.something));
```

```js
// Workaround for this specific situation

/** @type {any} */
const anyWindow = window;
/** @type {SomethingConstructor} */
const something = anyWindow.something;
```
---

References:

https://github.com/Microsoft/TypeScript/issues/9694

**Comment by rbuckton** [comment] 2017-08-05 05:39
This is a duplicate of #5158.

**Closed by rbuckton** 2017-08-05 05:39 UTC
Labels: Duplicate
