### ISSUE TITLE
Parser error with bigint literal object keys and class properties

### ISSUE THREAD

**Issue by almeidx** [microsoft/TypeScript#50863] opened 2022-09-20 19:22 UTC
# Bug Report

The TypeScript compiler does not support BigInt literal properties on objects/classes (without square brackets)

### 🔎 Search Terms

bigint literal object key class property

### 🕗 Version & Regression Information

- This is a crash
- This is the behavior in every version I tried (all the versions available in the TypeScript playground)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.2#code/MYewdgzgLgBCBGArGBeGBvGBGMAubATAMwwC+A3AFCXAA2AhhBDAIIaUyfZiqFFWlKQA)

### 💻 Code

```ts
const obj = { 1n: 123 };

class A {
    1n = 123;
}
```

### 🙁 Actual behavior

Various parser errors:
- The left-hand side of an assignment expression must be a variable or a property access.
- Property assignment expected.
- ';' expected.
- Declaration or statement expected.
- Unexpected token. A constructor, method, accessor, or property was expected.
- Declaration or statement expected.

### 🙂 Expected behavior

Anything but a parser error

**Comment by MartinJohns** [comment] 2022-09-20 21:19
Is there any legit reason why you would write code like this?

**Comment by MartinJohns** [comment] 2022-09-20 21:30
Duplicate of #35982.

**Closed** 2022-09-20 21:33 UTC

**Comment by fatcerberus** [comment] 2022-09-21 06:15
It’s interesting that #35982 says this wasn’t implemented on purpose, since it’s legal JS syntax.
