### ISSUE TITLE
JSDocTag#comment has CRLF newlines as CR

### ISSUE THREAD

**Issue by dsherret** [microsoft/TypeScript#35511] opened 2019-12-05 00:27 UTC
**TypeScript Version:**  3.8.0-dev.20191128

**Search Terms:** JSDocTag newlines comment

**Code**

```ts
import * as ts from "typescript";

console.log(ts.version); // 3.8.0-dev.20191128

const testFilePath = "/file.ts";
const testFileText = `
/**
 * @example
 * Some\n * text\r\n * with newlines.
 */
function test() {}`;

const testSourceFile = ts.createSourceFile(testFilePath, testFileText, ts.ScriptTarget.Latest, true);
const funcDec = testSourceFile.statements.find(ts.isFunctionDeclaration)!;
const tags = ts.getJSDocTags(funcDec);

console.log(JSON.stringify(tags[0].comment)); // "Some\ntext\rwith newlines."
```

**Expected behavior:**

Either:

* `"Some\ntext\r\nwith newlines."` <-- probably as-is?
* `"Some\ntext\nwith newlines."`

**Actual behavior:**

Outputs: `"Some\ntext\rwith newlines."`

**Comment by sandersn** [comment] 2020-04-17 17:36
I don't think I'll have time to fix this for 3.9, so I'm moving to 4.0. 

Reminder: It's still `help wanted` in case anybody else wants to look at it.

**Comment by sandersn** [comment] 2020-06-30 19:01
The problem is in the interaction between the scanner and the jsdoc comment parser; the scanner treats `\r` and `\n` as two newlines in a row. The parser only includes the first newline in a sequence of multiple empty newlines.

Either of those rules could be incorrect. The scanner one feels wrong to me &mdash; `\r\n` should really be one newline &mdash; but there may be compatibility concerns with changing it.

Squashing completely empty newlines makes sense, although it's kind of a corner case. I suspect there are additional reasons for the rule though.

**Comment by sandersn** [comment] 2020-06-30 20:58
Turns out it was the jsdoc scanner at fault, so I'm pretty confident in changing it; I think only API users will already depend on its current newline treatment.

**Closed** 2020-06-30 22:16 UTC
Labels: Bug, Domain: JSDoc, Fix Available
