### ISSUE TITLE
"The given path's format is not supported" errors for compiled TypeScript files in Azure package since upgrading to Visual Studio 2015 Update 1

### ISSUE THREAD

**Issue by berendengelbrecht** [Microsoft/TypeScript#6215] opened 2015-12-23 06:53 UTC
We can no longer package Azure web roles containing TypeScript since upgrading to Visual Studio 2015 Update 1. One of my colleagues managed to restore the functionality by uninstalling the latest TypeScript and repairing TypeScript Tools for Visual Studio 1.5.3.0. For others (like me): no such luck.

**Blocking symptom:**
- When packaging a web role for a web application containing TypeScript, there will be multiple errors: "The given path's format is not supported.", In the build output it is seen that the target path where msbuild tries to copy the output javascript file is incorrect. For example:

`2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.7\Microsoft.WindowsAzure.targets(2787,5): error MSB3021: Unable to copy file "D:\Users\b.engelbrecht\Documents\Visual Studio 2015\Projects\TestTs\TestTs\Eform\config.js" to "D:\Users\b.engelbrecht\Documents\Visual Studio 2015\Projects\TestTs\TestTsCloud\obj\Release\TestTs\D:\Users\b.engelbrecht\Documents\Visual Studio 2015\Projects\TestTs\TestTs\Eform\config.js". The given path's format is not supported.`

Note that the target path looks like two paths concatenated, with the drive letter D:\ appearing twice in the path (which indeed is an illegal path format).

I tried installing TypeScript 1.7.4.0 for Visual Studio 2015 Update 1 (release date December 17, 2015) in the hope that the bug would be fixed, but unfortunately that did not resolve the problem..

**Steps to reproduce, from scratch:**
- Install Visual Studio 2015 RTM
- Install Azure Tools 2.7
- Install Visual Studio 2015 Update 1
- Install TypeScript 1.7.4.0 for Visual Studio 2015 Update 1
- Create a new solution with an empty MVC web application
- Add a new directory to the web application and add a simple .ts file to that directory. Check that the application builds
- Add an Azure Cloud Service project to the solution, associate the cloud service with the MVC web application
- Try to package the cloud service. This fails with two errors as shown above (one for the .js output and one for the .js.map output file of the .ts file).

**Steps to reproduce, using prepared sample solution:**
- Download the sample solution http://support.decos.nl/Berend/TestTs-20151223.zip
- Open solution in Visual Studio 2015 Update 1 with Azure tools 2.7 and latest TypeScript installed
- Go to menu Tools > NuGet Package Manager > Manage NuGet Packages for Solution ...
- The package manager shows a warning "Some NuGet packages are missing ...". Click the [Restore] button to the right of the warning (packages were not included in the sample zip to reduce download size).
- Close package manager after restoring packages, try to build the web application TestTs. This should now proceed warning-free.
- Right-click the web role project TestTsCloud, select "Package...". For me, this fails with two "The given path's format is not supported." errors.

I sincerely hope this can be resolved soon. In our team, developers having installed Visual Studio 2015 Update 1 can no longer create Azure packages for roles containing TypeScript. Since we heavily use Azure, the problem is severe.

**Comment by erenes** [comment] 2015-12-23 14:00
Just tried to follow the steps above, but with the latest Azure SDK (2.8) installed, it appears the problem is not dependent on Azure SDK version. 

After opening the project, I chose to upgrade it to 2.8. Then following the steps to reproduce still gave me the following error: 
`2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.8\Microsoft.WindowsAzure.targets(2787,5): error MSB3021: Unable to copy file "C:\temp\6215\TestTs\Eform\config.js" to "C:\temp\6215\TestTsCloud\obj\Release\TestTs\C:\temp\6215\TestTs\Eform\config.js". The given path's format is not supported.`
`2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Windows Azure Tools\2.8\Microsoft.WindowsAzure.targets(2787,5): error MSB3021: Unable to copy file "C:\temp\6215\TestTs\Eform\config.js.map" to "C:\temp\6215\TestTsCloud\obj\Release\TestTs\C:\temp\6215\TestTs\Eform\config.js.map". The given path's format is not supported.`

I have attached the full build output to this comment. 
[build-output.txt](https://github.com/Microsoft/TypeScript/files/70836/build-output.txt)

**Comment by paulvanbrenk** [comment] 2015-12-23 17:42
This is a duplicate of #5894, which is fixed in TS 1.7.6 which you can download, here for [VS 2015 TS 1.7.6 Update](http://www.microsoft.com/en-us/download/details.aspx?id=48593).

**Closed by paulvanbrenk** 2015-12-23 17:42 UTC
Labels: Needs More Info

**Comment by berendengelbrecht** [comment] 2015-12-24 05:42
That works, thanks a lot! Shame that this version is not (yet?) available in Visual Studio notifications, would have saved us much time.

**Comment by mleyb** [comment] 2016-01-06 09:56
Can't this be pushed out on a VS notification? This has caused our team no end of headaches
