### ISSUE TITLE
Assert failure tryReuseStructureFromOldProgram

### ISSUE THREAD

**Issue by amcasey** [Microsoft/TypeScript#27873] opened 2018-10-12 23:31 UTC
From 3.1.3:

```
Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at tryReuseStructureFromOldProgram (tsserver.js:84813:22)
    at Object.createProgram (tsserver.js:84506:34)
    at synchronizeHostData (tsserver.js:114685:26)
    at Object.getProgram (tsserver.js:114768:13)
    at InferredProject.Project.updateGraphWorker (tsserver.js:118814:53)
    at InferredProject.Project.updateGraph (tsserver.js:118762:42)
    at Object.updateProjectIfDirty (tsserver.js:119449:45)
    at InferredProject.Project.getLanguageService (tsserver.js:118459:28)
    at IOSession.Session.getCompletions (tsserver.js:122608:43)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:121665:61)
    at tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (tsserver.js:123077:28)
    at IOSession.Session.executeCommand (tsserver.js:123086:33)
    at IOSession.Session.onMessage (tsserver.js:123106:35)
    at Interface.<anonymous> (tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by amcasey** [comment] 2018-10-12 23:49
Command was `completionInfo`.

**Comment by amcasey** [comment] 2018-10-13 00:43
Probably https://github.com/Microsoft/TypeScript/issues/27471

**Comment by sheetalkamat** [comment] 2018-10-15 20:04
This is duplicate of #20795 as in confirmed that this is possible only if there was exception in the invocation of previous createProgram which resulted in us not creating new program and old program was partially used and still present as newProgram

**Closed by sheetalkamat** 2018-10-15 20:04 UTC
Labels: Bug, Source: Telemetry
