### ISSUE TITLE
Ability to create definition files with no xml reference definitions

### ISSUE THREAD

**Issue by niemyjski** [Microsoft/TypeScript#2932] opened 2015-04-27 17:21 UTC
I'm using multiple tsconfig files because I want targeted builds and since the tooling won't support this/isn't there I'm using a single references file to link them all.. I'd like to generate a definition file that doesn't have any xml references so I can just distribute my definition file...

![image](https://cloud.githubusercontent.com/assets/1020579/7353273/ed2e477e-ecd7-11e4-9941-46a8eaa4ba1d.png)

**Comment by danquirk** [comment] 2015-04-27 18:21
I'm not entirely sure what the request here is. It sounds like you want the /// reference removed when this file is generated? But presumably it's in this file because it's needed by types in here (like ILastReferenceIdManager).

**Comment by niemyjski** [comment] 2015-04-27 18:23
Yes, that is exactly what I want. I don't need it and I'm just going to have to remove it every time I build or or write something to do it. It doesn't need any of the types as everything is in the same module. I just have the references.ts file to link all the files because the tsconfig.json file won't work for my setup and editors don't yet support it..

**Comment by mhegazy** [comment] 2015-04-27 19:37
you can use `--noResolve` and that will stop resolving /// references and will not propagate them to output.

**Comment by mhegazy** [comment] 2015-04-27 19:38
the issue is, you give that to some one, and they load it and it has errors. the ///reference is added because your .d.ts has types that it did not define. so your .d.ts is not usable by itself.

**Comment by niemyjski** [comment] 2015-04-27 19:46
I'm fine with that.

**Comment by mhegazy** [comment] 2015-06-12 22:51
looks like there is no information/action required by this issue. closing.

**Closed by mhegazy** 2015-06-12 22:51 UTC
Labels: Question
