### ISSUE TITLE
instanceof should not narrow in false branch; or structural assignment to class types should not be allowed

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#33481] opened 2019-09-18 03:26 UTC
**TypeScript Version:**  3.5.1

**Search Terms:**

instanceof, narrow, false branch

**Code**

```ts
class A {
  x! : number
}
class B {
  y! : number
}

//Neither A nor B, nominally
//Is A, structurally
const aOrB : A|B = { x : 32 };

if (aOrB instanceof A) {
  const a : A = aOrB; //OK
} else {
  const b : B = aOrB; //Expected to fail; is OK
}
```

**Expected behavior:**

`A|B` should not narrow to `B` in the `false` branch.

It is possible for `aOrB` to structurally match `A` but not nominally match `A`.
`instanceof` only checks for a nominal match; not structural match.

**Actual behavior:**

`A|B` is narrowed to `B` in the `false` branch and will cause run-time bugs.

**Playground Link:** [Playground](http://www.typescriptlang.org/play/#code/MYGwhgzhAECC0G8BQ1oA8CE0Bc0B2ArgLYBGApgE5IC+SokMAQoitAJ5a6GmU1JIB6AQDkyASwAuAC0px8AewrRGAGgVExeMCBBtBAgJIxYaiBIoFgEghW2668vGehgA8hWa5YAH2YBeRHQcaABmACZoagBufjEAM2gACjcPaE0zMDxgMnkE2ABKFlRgR2cwYPgAlMYo6CFXAGkaaDIQCDIi6BKnCWgSYP8Xdxq6gQBRNAAHMisyABNoCXloOLAxEFqxGEaaIA)

**Related Issues:** 

https://github.com/microsoft/TypeScript/pull/32774

I'm sure many people have known of this behaviour for a long time, and I never use classes or `instanceof` much. So, I never bothered to create an issue for it. However, the above PR finally motivated me to bring this up.

I tried to look for "instanceof narrow false branch" on the issues page but couldn't find anything related.

I'm sure this will get closed as "Working as Intended" or "Duplicate" but I feel like I needed to get this out of my system, anyway =x

**Comment by kitsonk** [comment] 2019-09-18 03:52
Essentially duplicate of #202

TypeScript is a structural type system.  That is because JavaScript is _mostly_ a structural system, but only becomes nominal with `instanceof`.  The change of behaviour you are suggesting would be a breaking change, and it was an intentional decision to have a situation that wasn't 100% correct, but where usability outweighed.

It has been a long roadmap item to experiment with nominal typing in TypeScript of which #33038 is one potential solution.  There are a couple others that the TypeScript team are actually working on.

**Comment by AnyhowStep** [comment] 2019-09-18 06:16
It's different from #202 and #33038 because they're trying to make stuff like `string` and other non-class types become nominally typed.

Applying structural typing to interfaces and non-classes works fine, in general, but starts leaking (like the example above) when applied to classes and `instanceof` or `constructor` checks.

So, either one of the following should have failed (if we didn't care about usability/backwards compat),

+ `const aOrB : A|B = { x : 32 };`
+ `const b : B = aOrB;`

But both are allowed at the moment and this introduces the unsoundness.

-----

How often do people try to assign an object literal to a `class` type?

**Comment by RyanCavanaugh** [comment] 2019-09-18 16:55
This is an intentional trade-off. Analysis of real code showed that people either use `instanceof`, or use structural-class matching, but not both.

**Comment by austincummings** [comment] 2019-09-18 17:11
@RyanCavanaugh This was however taken into account in PR #32774, granted that's not merged yet so there are no inconsistencies yet. But I did ask [here](https://github.com/microsoft/TypeScript/pull/32774#discussion_r314844270) about that and it was determined that there shouldn't be narrowing in the false case. Should that PR be changed to be consistent with `instanceof` or stay how it is?

**Comment by AnyhowStep** [comment] 2019-09-19 17:55
There's another reason to not want to narrow in the false branch.
```ts
//package-foo@1.1.0
export class A {}
export class B {}

//package-foo@1.2.0
export class A {}
export class B {}

//f.ts
//Let's say we're importing from 1.1.0
import {A, B} from "package-foo";

function f (aOrB : A|B) {
  if (aOrB instanceof A) {
    //Correctly narrow to A
  } else {
    //Incorrectly narrow to B
    console.log("I received B");
  }
}

//index.ts
//Let's say we're importing from 1.2.0
import {A, B} from "package-foo";
import {f} from "./f";

f(new A());
```

**Closed** 2019-09-21 20:00 UTC
Labels: Working as Intended
