### ISSUE TITLE
compileOptions.paths generated code resolves module path incorrectly

### ISSUE THREAD

**Issue by bgfist** [Microsoft/TypeScript#26146] opened 2018-08-02 08:34 UTC
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**
**Code**
tsconfig.json: 
```json
{
  "compilerOptions": {
    "target": "es5",
    "outDir": "dist",
    "declaration": true,
    "declarationDir": "d",
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "baseUrl": ".",
    "paths": {
      "*": ["src/*"]
    }
  }
}
```
src/lib.ts
```ts
export const num =  1;
```
src/index.ts
```
export { num } from 'lib';
```

**Expected behavior:**
I would like the generated js and .d.ts files to resolve module correctly.

**Actual behavior:**
But now it is like so:
dist/index.js
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var lib_1 = require("lib");
exports.num = lib_1.num;
```
so how can this code  run normally?

**Playground Link:** 

**Related Issues:**

**Comment by j-oliveras** [comment] 2018-08-02 09:25
Working as intended and duplicate of #9910.

Coping the answer made by @mhegazy at #9910:

> The compiler does not rewrite module names. module names are considered resource identifiers, and are mapped to the output as they appear in the source
> 
> The module names you write are not going to change in the output. the "paths" and "baseURL" are there to tell the compiler where they are going to be at runtime.

**Comment by bgfist** [comment] 2018-08-03 02:11
yeah,  but what about the generated .d.ts ? It does not rewrite module names either.

**Comment by joonhocho** [comment] 2018-10-08 10:47
I've created a solution that does not require any dependencies nor babel. It also fixes .d.ts files (if in the same directory as output for now. declarationDir support can be added ).
https://github.com/joonhocho/tscpaths

https://github.com/Microsoft/TypeScript/issues/15479#issuecomment-427539118

**Closed** 2018-12-15 18:00 UTC
Labels: Duplicate
