### ISSUE TITLE
Can't typecheck constructor in class generic parameter

### ISSUE THREAD

**Issue by albyrock87** [Microsoft/TypeScript#23264] opened 2018-04-09 10:57 UTC
**TypeScript Version:**  2.8.1

**Search Terms:** generics constructor type check constraint new

**Code**

```ts
export interface HasOneParameterConstructor<T> {
  new (p1: any): T;
}

class Foo {
  constructor(p1: string) {

  };
}

class Bar<T extends HasOneParameterConstructor<T>> {

}

class BarFooImpl extends Bar<Foo> { // error here under "Foo"

}
```

**Expected behavior:**
No errors: constructor type checking works

**Actual behavior:**
error TS2344: Type 'Foo' does not satisfy the constraint 'HasOneParameterConstructor<Foo>'.
Type 'Foo' provides no match for the signature 'new (p1: any): Foo'.

**Playground Link:** [Playground Test](http://www.typescriptlang.org/play/#src=export%20interface%20HasOneParameterConstructor%3CT%3E%20%7B%0D%0A%20%20new%20(p1%3A%20any)%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Foo%20%7B%0D%0A%20%20constructor(p1%3A%20string)%20%7B%0D%0A%0D%0A%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Bar%3CT%20extends%20HasOneParameterConstructor%3CT%3E%3E%20%7B%0D%0A%0D%0A%7D%0D%0A%0D%0Aclass%20BarFooImpl%20extends%20Bar%3CFoo%3E%20%7B%20%2F%2F%20%3C--%20ERROR%20here%20under%20%22Foo%22%0D%0A%0D%0A%7D)

**Related Issues:**
Maybe it's related to: [Can't extend mixin constructor that constructs a generic type](https://github.com/Microsoft/TypeScript/issues/13807)

**Comment by albyrock87** [comment] 2018-04-10 10:05
Hi @andy-ms , I tried your suggestion but the problem persists:
```ts
export interface HasOneParameterConstructor<T> {
  new (p1: any): T;
}

export abstract class ConstructorCheck<T, Class extends HasOneParameterConstructor<T>> {
  
}

export abstract class MyBase<TImplementor> extends ConstructorCheck<TImplementor, typeof TImplementor> {

}

class BaseImpl extends MyBase<BaseImpl> {

}
```

Your example does work but it's hackable:
```ts
class Hack { constructor(a: string) {} }
class BarFooImpl extends Bar<Foo, typeof Hack> {}
```

I'm trying to create a library with some usage restriction, and that's not good.

**Comment by andy-ms** [comment] 2018-04-10 15:17
Note that TypeScript does not have any abstract static methods (#14600). It might be more helpful to determine what you're trying to accomplish -- currently `Class` is unused there. Note that the type parameter is only available as a type, and not as a value, so you won't be able to write `new T` inside of your class body, and as you've noticed `typeof T` doesn't work.

**Comment by andy-ms** [comment] 2018-04-16 15:21
If I understand that right, you want something like this?
```ts
abstract class A {
	final constructor() {}
}

class B extends A {
	constructor() { super(); someBadThing(); } // Compile error, super constructor is final
}
```

It doesn't seem that useful to have an abstract class whose constructor can't be overridden -- sublcass constructors are forced to call the superclass constructor anyway. And one can of course do `new B(); b.someBadThing();` even if the constructor isn't overridden.

**Comment by albyrock87** [comment] 2018-04-16 15:38
A final constructor would do the trick.
I'm in the Angular world, and I'm trying to stop the developer to `@Inject` other things in the `B` class.

**Comment by andy-ms** [comment] 2018-04-16 15:43
This is a duplicate of #1534 then -- I don't think there's a good way to do what you want right now. (You can't just make the constructor private because then the class can't be overridden at all.) It's possible that you could add a run-time check in `A`'s constructor that `this.constructor` has no decorators? I don't really know how angular works though.

**Closed** 2018-04-30 16:56 UTC
Labels: Question
