### ISSUE TITLE
Deconstructive type assignation

### ISSUE THREAD

**Issue by owl-from-hogvarts** [microsoft/TypeScript#46519] opened 2021-10-25 17:12 UTC
# Suggestion
Add deconstructive assignation for types like it is done for variables (objects)

## 🔍 Search Terms

type, deconstructive. assign, variable, equals, namespaces

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

It would be cool to have ability to deconstruct type namespaces like we already able to do with regular variables or more specially with objects.

## 📃 Motivating Example

This feature will shorten code without loosing readability. When you have complicated modules structure, when you reexporting things to better group them, it rapidly become annoying to write something like `someModule.ohOneMoreModule.thatTypeINeed` which, here is a coincidence, is heavily used. Thus you'd like to write only the name of type you are using and not the whole path to it, while preserving other rarely used things under long cover.

As of now, you can alias type, but if the type contain complex logic, generics etc. it will be quite hard and increases the risk of error

## 💻 Use Cases

```typescript
// user.ts
import { UserSendable } from "userSendable.ts"
import { UserData } from "userData.ts"

type Sendable = UserSendable 
type Data = UserData 

export namespace User {
  export Sendable ,
  export Data,
}

// userService.ts
import { User } from "user.ts"

export User
export UserService

// db.ts

import { User } from "userService.ts"

// suppose that UserSendable is heavily used while UserData is not, but required in few places
// so each time i'd like to use UserSendable i should write
const foo: User.Sendable = ...

// looks uggly, is not it? note, every time... every
// now consider this

type { Sendable } = User

const bar: Sendable = ...
```
The above example is pretty simple and does not really show the problem. The PROBLEM bubbles up when generics come int game.

If instead of simple `Sendable` there were something like:
```typescript
// it is only declaration. Imagine this is inside namesapce and you need to alias it
type ConstructableSubclass<
  T extends abstract new (...args: any[]) => unknown,
  Constructor extends new (...args: any[]) => InstanceType<T> = new (
    raw: string,
    start: number
  ) => InstanceType<T>
> = Constructor & Omit<T, never>;
```
you will need to write again all defaults and restrictions for generics to manage the alias work.
But with Destructive Type Assignation you can simply do:
```typescript
type { ConstructableSubclass } = UtilityTypes
```
And boom! No place for mistackes left.

P.S. Thanks for reading this. Pleas, leave a comment so I can find out what i can improve in this suggestion.

**Comment by DanielRosenwasser** [comment] 2021-11-04 18:50
Duplicate of #13135.

**Comment by owl-from-hogvarts** [comment] 2021-11-05 12:40
> Duplicate of #13135.

yeah, i missed this already open issue due to miss-spelling in `deconstructive` word. Generally, this issue and #13135 already have solution as mentioned above. So they both can be closed

**Closed** 2021-11-07 18:00 UTC
Labels: Duplicate
