### ISSUE TITLE
Type checking is ignored with spread operator, especially with truthy expression.

### ISSUE THREAD

**Issue by dimak-dev** [microsoft/TypeScript#57248] opened 2024-01-31 14:43 UTC
### 🔎 Search Terms

spread operator with expression

### 🕗 Version & Regression Information

- Tested with www.typescriptlang.org with versions from 3.3.3 to nightly (v5.4.0-dev.20240131)

### 💻 Code

```ts
type Type = {
    property: string,
}

let typedVar1: Type = {
    property: 'string',
    anotherProperty: 'foo', // TS-2353: Object literal may only specify known properties, and 'anotherProperty' does not exist in type 'Type'.
}

let typedVar2: Type = {
    property: 'string',
    ...({anotherProperty: 'bar'}), // No error
}

let typedVar3: Type = {
    property: 'string',
    anotherProperty: 'foo', // TS-2783: 'anotherProperty' is specified more than once, so this usage will be overwritten.
    ...({anotherProperty: 'bar'}),
}

let typedVar4: Type = {
    property: 'string',
    anotherProperty: 'foo', // No error, total ingoring
    ...(1 == 1 && {anotherProperty: 'bar'}),
}

console.log(typedVar2); // {"property": "string", "anotherProperty": "bar"} 
console.log(typedVar2.anotherProperty); // TS-2339 : Property 'anotherProperty' does not exist on type 'Type'.
console.log(typedVar4); // {"property": "string", "anotherProperty": "bar"} 
console.log(typedVar4.anotherProperty); // TS-2339 : Property 'anotherProperty' does not exist on type 'Type'.
```

### 🙁 Actual behavior

1. TS-2353: Object literal may only specify known properties, and 'anotherProperty' does not exist in type 'Type'
2. No error
3. TS-2783: 'anotherProperty' is specified more than once, so this usage will be overwritten.
4. No error

### 🙂 Expected behavior

1. TS-2353: Object literal may only specify known properties, and 'anotherProperty' does not exist in type 'Type'
2. TS-2353: Object literal may only specify known properties, and 'anotherProperty' does not exist in type 'Type'
3. TS-2353 + TS-2783
4. TS-2353 + TS-2783

**Comment by MartinJohns** [comment] 2024-01-31 14:57
Duplicate of #39998.

**Comment by fatcerberus** [comment] 2024-01-31 16:36
le sigh... this error message really needs to be softened to make it more obvious EPC isn't a type check. 
 Count this as another vote for something like https://github.com/microsoft/TypeScript/pull/55152#issuecomment-1661005191

**Closed** 2024-02-04 01:28 UTC
Labels: Duplicate
