### ISSUE TITLE
Const enum values as array

### ISSUE THREAD

**Issue by Harpush** [microsoft/TypeScript#41122] opened 2020-10-15 19:01 UTC
## Search Terms
const enum

## Suggestion
So i looked for a way to get all values from const enum without hardcoding them and stumbled upon https://github.com/microsoft/TypeScript/issues/21391.
The idea is similar but with one important difference.
Right now when i declare a const enum and use it the compiler replaces the usage with the actual value. The suggestion is allowing the same for values.
So when i write:
```ts
const enum Test {
  A = 'A',
  B = 'B'
}
const test = Test.A;
const test2 = Test.values();
```

It will compile into:
```ts
const test = 'A';
const test2 = ['A', 'B'];
```

## Use Cases
Eliminates the need to either drop const enums or hardcode all the values in an array and remember to add any new enum member. 

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-10-15 19:14
Duplicate of #38960.

> [x] This feature would agree with the rest of TypeScript's Design Goals.

It wouldn't, tho.

> Non-goal 5. Add or rely on run-time type information in programs, or **emit different code based on the results of the type system**. Instead, encourage programming patterns that do not require run-time metadata.

---

Besides, you can just use `Object.values(..)` when not using a `const  enum`. Retrieving the values for a `const enum` kinda goes against the concept of it.

**Comment by Harpush** [comment] 2020-10-15 19:20
> Duplicate of #38960.
> 
> > [x] This feature would agree with the rest of TypeScript's Design Goals.
> 
> It wouldn't, tho.
> 
> > Non-goal 5. Add or rely on run-time type information in programs, or **emit different code based on the results of the type system**. Instead, encourage programming patterns that do not require run-time metadata.
> 
> Besides, you can just use `Object.values(..)` when not using a `const enum`. Retrieving the values for a `const enum` kinda goes against the concept of it.

Well the whole const enum concept is against the goals then...

Well its still const enum values... Same as replace usage - replace values. Its not a runtime way its a compilation replacement like regular usage.

**Comment by RyanCavanaugh** [comment] 2020-10-15 19:46
> Well the whole const enum concept is against the goals then...

We mostly agree and aren't inclined to dig that particular hole any deeper.

**Closed** 2023-06-21 01:32 UTC
Labels: Suggestion, Out of Scope

**Comment by theanurin** [comment] 2025-01-15 12:04
Workaround (if you really need `const enum`)

```typescript
const enum Test {
    A = 'A',
    B = 'B',
    // C = 'C', /* uncomment the line to see compilation error */
}
type TestMap<T> = { [key in Test]: T };
const testUtilityMap: TestMap<null> = { [Test.A]: null, [Test.B]: null };
const allTests: ReadonlyArray<Test> = Object.freeze(Object.keys(testUtilityMap) as Array<Test>);
console.log(allTests.join(", "));
```

[Playground Link](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBApmArgWxgFTtGBvAUDAmAQRgF4YByIigGn0ICEzKHb6CB6DmAYWYp60YHAFQxEYUMmQJYUABZwYAGwCWYJVBAwIcJVIAOq5QEMoq8PABOVkFZgiOuAL64oATwNKM0ALImDAB40AD5mbBgAbQBrOHcYdXRMKABdAC50GGcAblxQSDlkgFVzNQ9-AwyfKArApGVlMPIIyOqAOiJ0mHrlGij2hi6erNz8rBMG6ogMgCU4EwATcGV3IhsTd2DkppgAeQAjACs4YCg2gDMrPQAvOAAKA+PTttj3CDuoYtLVcoCAShgJggxHWm2qIT+o3AEBAyjgbWUIAA5ncJsopm1DiB1HcAER9XF-SG4IA)

When you add a new item into enum, compiler will provide `Property '[Test.C]' is missing in type '{ A: null; B: null; }' but required in type 'TestMap<null>'.ts(2741)` 
So you do not miss to add it in map (and as side effect into `allTests` array)
