### ISSUE TITLE
Rename Locations not found for Class Expression Var

### ISSUE THREAD

**Issue by JKillian** [Microsoft/TypeScript#5190] opened 2015-10-09 14:42 UTC
Rename locations aren't found correctly for `Parent` in the code below:

```typescript
let Parent = class {};
class Child extends Parent {}
```

Confirmed by testing in Sublime and also by the test below:

```typescript
/// <reference path='fourslash.ts' />

////class [|Parent|] = class { };
////class Child extends class [|Parent|] { }

let ranges = test.ranges()
for (let range of ranges) {
    goTo.position(range.start);

    verify.renameLocations(/*findInStrings*/ false, /*findInComments*/ false);
}
```

Related: https://github.com/palantir/tslint/issues/721

**Comment by DanielRosenwasser** [comment] 2015-10-09 18:24
Hey @JKillian, this seems to be fixed in `master` and I suspect it's a duplicate of #5028. If you'd like, you can get the fix on npm by installing `typescript@next`.

**Closed by DanielRosenwasser** 2015-10-09 18:24 UTC

**Comment by JKillian** [comment] 2015-10-09 18:51
@DanielRosenwasser  Shoot, for real? I pulled the latest code off master and ran `jake runtests tests=renameClassVar` which references a file with the test code I posted above. It gave me the following output:

```typescript
  1) fourslash tests tests/cases/fourslash/renameClassVar.ts fourslash test renameClassVar.ts runs correctly:
     Error: Marker:
Rename location count does not match result.

Expected: [{"fileName":"tests/cases/fourslash/renameClassVar.ts","start":6,"end":12},{"fileName":"tests/cases/fourslash/renameClassVar.ts","start":52,"end":58}]

Actual:[{"fileName":"tests/cases/fourslash/renameClassVar.ts","textSpan":{"start":6,"length":6},"isWriteAccess":true}]
```

Obviously I don't want to be reporting bugs for old versions because that wastes everyone's time. Do you see something I did wrong in the process?
