### ISSUE TITLE
`as` keyword is missing in completion lists within function bodies

### ISSUE THREAD

**Issue by busyscout** [microsoft/TypeScript#40432] opened 2020-09-08 14:01 UTC
Try to write
```
const s = 1 as number;
```
The "as" keyword is missing in VS2019 intellisense suggestion list. TS version is 3.9. If you press space after "as", then "async" keyword is inserted.
![TS AS](https://user-images.githubusercontent.com/23096209/92486342-a58cbe00-f1f4-11ea-8e66-f1c25cea67da.png)

**Comment by DanielRosenwasser** [comment] 2020-09-08 21:57
Looks like this should have been fixed in 3.8. See https://github.com/microsoft/TypeScript/issues/34814

Unable to reproduce the issue on my end. Is your project using the same version of TypeScript?

```
Microsoft Visual Studio Enterprise 2019
Version 16.5.2
VisualStudio.16.Release/16.5.2+29926.136
Microsoft .NET Framework
Version 4.8.03752

TypeScript Tools   16.0.20225.2001
TypeScript Tools for Microsoft Visual Studio
```

![image](https://user-images.githubusercontent.com/972891/92531571-66a23c80-f1e3-11ea-875e-893267fb8dbc.png)

**Comment by busyscout** [comment] 2020-09-10 08:18
Microsoft Visual Studio Professional 2019
Version 16.7.2
VisualStudio.16.Release/16.7.2+30413.136
TypeScript Tools   16.0.20702.2001

It depends on context.
To reproduce just create simple ts file with the following content
```
const x = 100 as number; //OK. as in suggestion list

function main() {
    const x = 100 as number; //WRONG. as is not in suggestion list
}
```

![TS-AS-Correct](https://user-images.githubusercontent.com/23096209/92699894-ce2cc900-f356-11ea-83bf-5a11af669287.png)
![TS-AS-Wrong](https://user-images.githubusercontent.com/23096209/92699903-d1c05000-f356-11ea-95e9-12c8ba23e99a.png)

**Comment by DanielRosenwasser** [comment] 2020-09-10 09:15
I think the logic for https://github.com/microsoft/TypeScript/blob/0a1f1c864b2c5aa1818d8e0fb619c1f4e3302eb4/src/services/completions.ts#L2651-L2654 is off.

**Comment by DanielRosenwasser** [comment] 2020-09-10 09:21
I think this should be a matter of adding a test and making an exception like with `async`/`await`

**Closed** 2020-09-17 09:15 UTC
Labels: Bug, Domain: Completion Lists, Fix Available, good first issue, help wanted
