### ISSUE TITLE
tsc watch with project references shouldn't stop compiling on certain errors

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/TypeScript#35223] opened 2019-11-20 11:36 UTC
Set up a project that use project references. You can take the eslint VS Code extension as an example from here: https://github.com/microsoft/vscode-eslint

- open the project
- start the watch compile by running the `npm: watch` task
- open the eslintServer.ts file
- paste the following code:

```ts
const x = 10;
export function foo(): number {
	return 10 + 10;
}
```
- save
- observe: the eslintServer.js file is not updated. The reason is the error on the `const x = 10`; that reports this as unused. 

I do see why some errors stop the builder especially when using project references. However a unused symbol shouldn't since it has no effect on the shape of the eslintServer.ts file.

**Comment by sheetalkamat** [comment] 2019-11-20 19:29
Duplicate of #28877 ?

**Comment by dbaeumer** [comment] 2019-11-21 10:00
Yes, but I think the solution to this problem can not be works as designed. This make the feature really hard to use. IMO the compiler should do its best to emit code. Consider you comment a piece of code which results in an unnecessary import. Now I have to organize my imports to be able to emit code. 

These are things that are really annoying since you have to very closely watch your errors counts before you debug :-)

To make things worse in the eslint example client and server don't actually depend on each other. I use project references to  have an elegant way to only start one compile job an therefore to therefore to save system resources.

What is the underlying reason that all errors always abort compilation?

**Comment by RyanCavanaugh** [comment] 2019-11-26 00:16
@dbaeumer the things we said last time are still true this time around 😉

If we emitted code anyway, the second time you ran `tsc -b` on the same project, we wouldn't realize that there were still errors in the dependent project.

**Closed** 2019-11-28 18:00 UTC
Labels: Duplicate

**Comment by dbaeumer** [comment] 2019-11-28 20:10
@RyanCavanaugh this actually makes the feature in many cases hard to use for me. 

Can you please explain to me why an unnecessary import has to fail the whole compile and emitting path. I am not arguing that the TS compiler should continue in all cases but things that are more linting errors and IMO have no affect on the shape generation should not make this fail.

The fact that you are not differentiating them does IMO not mean you can't address this. A first step of course would be to know when a error doesn't effect project dependency updates.

So can we PLEASE consider this.

One thing that adds to this is for sure the fact that in VS Code there diagnostics are rendered as warnings this users were very confused that they show up as errors.

**Comment by dbaeumer** [comment] 2020-01-23 09:15
@RyanCavanaugh can you please comment on this. I get tricked by this every day.
