### ISSUE TITLE
Is there an equivalent to babel/register?

### ISSUE THREAD

**Issue by datoml** [Microsoft/TypeScript#5734] opened 2015-11-20 20:06 UTC
Currently we testing server side rendering with react and typescript.
I created an express server in typescript and run it on node.js with ts-node.

Babel is using require(babel/register) for on the fly transpiling.
[Babel/register](https://babeljs.io/docs/usage/require/)
Coffee script seems like to achieve the same with register.coffee
[Register.coffee](http://coffeescript.org/documentation/docs/register.html)

Is there an official module for typescript with the same functionality?
Or does anyone know a well supported one?

**Comment by blakeembrey** [comment] 2015-11-20 21:37
There's no official one (correct me if that's wrong), but I what's the issue your having with `ts-node`? What do you mean by "a well supported one" that isn't `ts-node`?

**Comment by datoml** [comment] 2015-11-20 22:19
Not really an issue.

Babel-node for instance shouldn't be used in production. So I thought this will be the same with ts-node.

>babel-node not meant for production use
>You should not be using babel-node in production. It is unnecessarily heavy, with high memory usage >due to the cache being stored in memory. You will also always experience a startup performance >penalty as the entire app needs to be compiled on the fly.

**Comment by blakeembrey** [comment] 2015-11-20 22:40
It'll be the same for any system where you want to transpile in memory. However, it's possible to optimise the process a little bit (the current `ts-node` approach **is not** made for this, it keeps an entire language services instance in memory). 

I'd actually love any thoughts from the TypeScript team on this, but I was considering making a new flag to enable to current in-memory process which should only be used for node watch tasks (like `mocha --watch` and the CLI) and switching to use a single program emitting the contents into a file cache with subsequent single file transpilations from now on (very bad for `--watch` since you won't get subsequent type errors from requires that are asynchronous to program startup).

**Comment by datoml** [comment] 2015-11-21 08:18
Thank you for this additional explanation.
So the difference is that ts-node is keeping it in memory and babel/register is using a cache folder?

**Comment by blakeembrey** [comment] 2015-11-21 16:54
You might have to try Babel and check, but I looked at the README and it made an assertion of a cache existence. That cache may just be metadata though.

**Comment by datoml** [comment] 2015-11-21 17:42
I am not too experienced with node yet ;).
But under the there can't be that much difference.

Is this type also used in production I wonder?
Or do I use an compiled version?

**Comment by DanielRosenwasser** [comment] 2015-11-21 22:35
@rbuckton, @weswigham, and @mhegazy might know more about this.

Is there any reason you can't just compile your project/tests and run them like that?

**Comment by blakeembrey** [comment] 2015-11-21 23:05
@DanielRosenwasser Personally, I don't because it gets messy too quickly. I don't want specs in my compiled output since they'd end up in NPM with the way `tsc` currently works - unless I split it into two commands and two output directories. On top of that, I use fixture files that I'd have to copy from the `src` directory into the `tsc` output directory for tests to actually work and resolve properly. It's much easier just to maintain and use `ts-node` honestly. The final solution is to compile them inline, but then I get stuck with dead `.js` hanging around (I already have to `rm -rf dist/` before every publish/build for the same reason).

**Comment by vladima** [comment] 2015-11-22 04:17
looks like a dupe of #1823

**Closed** 2015-12-09 22:13 UTC
