### ISSUE TITLE
Maximum call stack size exceeded transpiling d3-brush

### ISSUE THREAD

**Issue by ahsquared** [Microsoft/TypeScript#13821] opened 2017-02-01 20:42 UTC
**TypeScript Version:**  2.1.5

**Code**

**_d3.js**
```js
import {select} from 'js/d3-selection/index.js';
import {brush} from 'js/d3-brush/index.js';

export default {
	select,
	brush
};
```

**_graph.js**
```js
import d3 from "./_d3";
let graph = () => {
	let svg = d3.select("svg");
	svg.append("circle")
		.attr("r", 20)
		.attr("cx", 20)
		.attr("cy", 20);
};

export default graph;
```

**main.js**
```js
import graph from "./_graph";
graph();
```

**Expected behavior:**
It should transpile and output a file that includes those pieces of d3 and draws a circle.

**Actual behavior:**
/usr/local/lib/node_modules/typescript/lib/tsc.js:50061
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at isMatchingReference (/usr/local/lib/node_modules/typescript/lib/tsc.js:26935:37)
    at getTypeAtFlowAssignment (/usr/local/lib/node_modules/typescript/lib/tsc.js:27454:21)
    at getTypeAtFlowNode (/usr/local/lib/node_modules/typescript/lib/tsc.js:27405:32)
    at getTypeAtFlowCondition (/usr/local/lib/node_modules/typescript/lib/tsc.js:27505:32)
    at getTypeAtFlowNode (/usr/local/lib/node_modules/typescript/lib/tsc.js:27412:32)
    at getTypeAtFlowBranchLabel (/usr/local/lib/node_modules/typescript/lib/tsc.js:27538:36)
    at getTypeAtFlowNode (/usr/local/lib/node_modules/typescript/lib/tsc.js:27423:29)
    at getTypeAtFlowBranchLabel (/usr/local/lib/node_modules/typescript/lib/tsc.js:27538:36)
    at getTypeAtFlowNode (/usr/local/lib/node_modules/typescript/lib/tsc.js:27423:29)
    at getFlowTypeOfReference (/usr/local/lib/node_modules/typescript/lib/tsc.js:27387:51)

**Test Case**
I have created a small repo that replicates this issue:
https://gitlab.com/ahsquared/system-typescript-d3-bug

**Comment by sandersn** [comment] 2017-02-08 16:47
Very likely a duplicate of #12946

**Closed** 2017-02-08 17:54 UTC
Labels: Bug, Duplicate

**Comment by sandersn** [comment] 2017-02-09 21:01
This should be fixed now.
