### ISSUE TITLE
Asserting changes type of original variable inline (the change reverts in subsequent lines)

### ISSUE THREAD

**Issue by paradoxloop** [microsoft/TypeScript#58055] opened 2024-04-03 12:43 UTC
### 🔎 Search Terms

asserting type
`as` changing underlying type

### 🕗 Version & Regression Information

- This changed between versions v4.2 and v4.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.3#code/MYewdgzgLgBAHjAvDA3gWAFAxgcgJ44BcuAFgKYA2FIOANJtjnETAIwAMmAvppgGYBXMMCgBLcDAggAtmQBiQkeLAAeACowycKGTAATCDADWZPCD4woeAA5lz8AHwAKawCcQ1wmoCUqBpIB3UShgEhgXd2tfdCxsGGAAQwgyXAJCfziYAHosmATYKBJRQ2sQUTBYNw8YYskxKhgAIjxGmAAfJrhWvQEUqBBLGzIIYFdRa1gwEFgAIzJygHM8mYo+gbAE13cAjLiczQgKcthXAVWmqYBaITJgYYhNvEurW0uk5NcxcFa3MgA3XRQQwbLYgIJgJYgASuZIUAEQXbYUCQE6sJAwKrWADciOyuUymQAegB+XHI6AwVwAJnRmLyhnwOBxsUy+wJcRJuJmrjICSMzOwPAw3EwQA

### 💻 Code

```ts
const x = {
  'y': 'hello',
  'x': 10
}

function someFunction<T extends keyof typeof x>(prop:T) {
  switch (prop) {
    case 'y':
      // at this point prop is still "y" | "x" due to typescript not being able to narrow
      // eslint rule "no-unecessary-type-assertion" prevents narrowing ourselves
      const r1 = prop;
      //         ^?
      const r2 = prop as 'y';
      //         ^?
      break;
  }

}

```

### 🙁 Actual behavior

If you [inspect the types of prop with and without the assertion](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAHjAvDA3gWAFAxgcgJ44BcuAFgKYA2FIOANJtjnETAIwAMmAvppgGYBXMMCgBLcDAggAtmQBiQkeLAAeACowycKGTAATCDADWZPCD4woeAA5lz8AHwAKawCcQ1wmoCUqBpIB3UShgEhgXd2tfdCxsGGAAQwgyXAJCfziYAHosmATYKBJRQ2sQUTBYNw8YYskxKhgAIjxGmAAfJrhWvQEUqBBLGzIIYFdRa1gwEFgAIzJygHM8mYo+gbAE13cAjLiczQgKcthXAVWmqYBaITJgYYhNvEurW0uk5NcxcFa3MgA3XRQQwbLYgIJgJYgASuZIUAEQXbYUCQE6sJAwKrWADciOyuUymQAegB+XHI6AwVwAJnRmLyhnwOBxsUy+wJcRJuJmrjICSMzOwPAw3EwQA) you can see that without the assertion TS reports the type of prop to be T  extends "y" | "x" but with the assertion TS reports the type of `prop` as `"y"`.
![image](https://github.com/microsoft/TypeScript/assets/709833/5d1ca967-b633-47c7-a3db-8ddfa11fab20)

This is a bug with TS itself - a behaviour changed in TS v4.3. In v4.2 TS correctly reports both locations as the generic - in v4.3+ it exhibits the above behaviour.

### 🙂 Expected behavior

The assertion should not be changing the type of the original variable.

### Additional information about the issue

Discovered while debugging a [eslint issue ](https://github.com/typescript-eslint/typescript-eslint/issues/8827).

**Comment by MartinJohns** [comment] 2024-04-03 12:59
Note that the type of `prop` is not actually changed. If you look at the type in the next line it's still correctly `T extends "y" | "x"`.

So it's at most an issue with the type shown in the tooltip.

**Comment by jcalz** [comment] 2024-04-03 15:10
Duplicate of #43873

**Comment by RyanCavanaugh** [comment] 2024-04-03 16:26
We need to retain basically both the `T` and the `"y"` aspects of the type here, otherwise code like this fails:
```ts
function someFunction<T extends keyof typeof x>(prop:T): T {
  switch (prop) {
    case 'y':
      return prop;
```

Note that
```ts
const r1: 'y' = prop;
```
also doesn't error.

The "correct" type is both `T` and `"y"` depending on what you need to use it for. If the contextual target is a union we treat it as `"y"`, otherwise it's `T`. So neither display is "wrong", but we can only show one at a time to the user obviously.

**Comment by bradzacher** [comment] 2024-04-03 20:10
The issue is that from typescript-eslint's perspective for the rule `no-unnecessary-type-assertion` we inspect the left and right side of the assertion and compare the types to make a guess if they are the same type. If they're the same type then we error and flag the assertion as unnecessary.

The way we do this is in the most basic form - "are the type objects the same?" Not even doing any fancy type assignability checks - it all just boils down to `if (left === right) report()`.

So in this particular case when we inspect the left we don't see the type `T` - we see the type `"y"`. Obviously this is the exact same type as the right so we report.

There's no flags set on the left type either so we can't even guess that the left might be the generic type. The contextual type too is the same. Is there another API we can use to get the type of the left without the assertion here (eg see that it is the generic type)?

**Comment by bradzacher** [comment] 2024-04-03 20:13
To clarify - it's not just what you show to the user - this is not a problem of intellisense has to display one so we pick the best one via some logic.

Instead it's what the type API itself reports for the expression. When there is no assertion it reports the type `T`. When there is an assertion it reports the type `"y"`.

**Comment by jcalz** [comment] 2024-04-03 21:01
I suppose there'd be some issue if it became `T & "y"`?  

```ts
function someFunction<T extends keyof typeof x>(prop: T) {
    if (prop === "y") {
        x[prop].toUpperCase(); // error
        const p: "y" = prop;
        x[p].toUpperCase(); // okay
        const q: T & "y" = prop; // error!
        x[q].toUpperCase(); // this would have been okay
    }
}
```

**Comment by paradoxloop** [comment] 2024-04-03 21:47
@jcalz my using of a `switch` in the example was probably a mistake. I don't think this is a duplicate of [#43873](https://github.com/microsoft/TypeScript/issues/43873) because the problem is not typescripts inability to narrow for `extend` but that it picks and choses in the same code block about whether it is narrowed (in a way that doesn't let us override without triggering reasonable eslint rules). 

@RyanCavanaugh needing to keep the return type broad to enable returing T makes sense

IF statement example:
[ES Lint Playground](https://typescript-eslint.io/play/#ts=5.4.3&fileType=.ts&code=GYVwdgxgLglg9mABFAhgawKYEEAUWBciA5CkQJSIDeiAvgFCiSwLLoYBCO7hRARuVVp06EBAGcoiMSgC2ABwA2GRAF4qdRIhQ8AFhgUK4RADSIA9GalQATjDABzZAE85GDYl6EAjAAZzlsBAZXgxrZ1c6Gi0xRFEwCWEGcGh4JDE4GQwAMWSAHgAVRAwADygMMAATGJIiRAAfYn4APhw5azg5QnyKSncYYERW9rlVFTUanvdNC0QKjGAUEAVJEJ0UADd4EDCAdxgoHTgQSTAUa3a9hyk4WZRURBgYsDhJKBcMCuQbiVsHKdjxJIKncUKopLJFBgANptDoAXX%2BwNQADolA4DsJNJpUJhcLC5BQZo9EGs5HInF9EKdznAdpSaohgHAwgdiYwIP8ZljEAA9AD8-3x-kQ4GpFxiKHsKDsnMs-MxWJmUBu9gwrz0Hgwa02RzCcAG0mA%2BgpKAgEAwYjEdkc0nkSkQAEkqRgPrLEDIUIEUAYTZbQq93h5johVZILQo7GGadZ-nEJO6wUKUNVSG7uen5dy40CQQBZMG2yFQmQI7lIlC51HlewY-447A4GRkNOaTO0IoKMTKXrc%2BucfHNzT0eh0JW2TbeorFCH2vYHI5h0rlT6mqAxUTnDDQBROJJMVLXTI5SAAJiGHR4pDqfAEPYeA3PIzG41IkyzgNu9zUhaUMOGpcVSxuTbbE2DxYZB0AjMBW5fE3TbKJ9C7dRezYfsIPcYdEjoIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWkOTJE0fJQ5N0UOdA7RI4MAF8QOoA&tsconfig=&tokens=false)


<img width="632" alt="Screenshot 2024-04-03 at 22 44 50" src="https://github.com/microsoft/TypeScript/assets/709833/e9bd8eda-af16-4469-9e46-f3bda36c35e1">

**Closed** 2024-04-06 01:24 UTC
Labels: Not a Defect
