### ISSUE TITLE
Invalid type after destructuring a Record

### ISSUE THREAD

**Issue by lcswillems** [microsoft/TypeScript#56456] opened 2023-11-18 18:51 UTC
### 🔎 Search Terms

record destructuring concat

### 🕗 Version & Regression Information

TypeScript 5.2

### ⏯ Playground Link

https://www.typescriptlang.org/play?ssl=5&ssc=1&pln=5&pc=57#code/MYewdgzgLgBAhgLhgJQKagE4BMA80MCWYA5gDTxgCeAfDALwwDe8SATOQEZIDMMAvgG4AUKEiwO9JjAB0suOQBebfsJHhoMSkjSZc+ImQo1JzRDHYwuMXoLViYCyQHkOAK3RRpcCBALEwABQu7sCe3r7+AYx85JQAlOTMSub8cQJAA

### 💻 Code

```ts
const a: Record<string, any> = { a: 2, b: 3 };
const b = { ...a, z: 2 };

const y: Record<string, any> = { a: 2, b: 3 };
const z = Object.assign(Object.assign({}, y), { z: 2 });
```

### 🙁 Actual behavior

`b` is of type `{ z: number}`

### 🙂 Expected behavior

`b` should be of type:

```
Record<string, any> & {
    z: number;
}
```

Same as the type of `z`

**Comment by fatcerberus** [comment] 2023-11-18 19:04
Duplicate of https://github.com/microsoft/TypeScript/issues/27273.  Also this is a spread, not a destructuring.

**Comment by fatcerberus** [comment] 2023-11-18 19:11
Note that it’s not actually an “invalid type” - `{ z: number }` is a valid description of what you get, just not the most convenient.

**Closed** 2023-11-23 01:28 UTC
Labels: Duplicate
