### ISSUE TITLE
Using rest destructing on class objects seems to include getters in the resulting type

### ISSUE THREAD

**Issue by divillysausages** [microsoft/TypeScript#46967] opened 2021-12-01 09:44 UTC
# Bug Report

If you have a class along the lines of:

````ts
class User {
    constructor(
        public uid: number,
        public password: string // sensitive info
    ) { }
	
    get score(): number {
        return 10; // example code - imagine having to fetch something a little more complex
    }
}
````

If we then want to destructure a `User` object (e.g. returning a client-friendly basic object from a server), we first declare a type:

````ts
type UserClient = Omit<User, 'password' | 'score'>;
````

We pass `score` to the `Omit` here because, as we're using destructing, only basic properties will be returned, not any getters. We can then create our method:

````ts
toClient(): UserClient {
    const { password, ...client } = this;
    return client;
}
````

However, `score` is something that we want to return, so we change our `UserClient` type to:

````ts
type UserClient = Omit<User, 'password' | 'score'> | { score: number };
````

and our `toClient()` method now becomes:

````ts
toClient(): UserClient {
    const { password, ...client } = this;
    return {
        score: this.score,
        ...client
    }
}
````

This, however, gives the error `'score' is specified more than once, so this usage will be overwritten`, even though when we destructure an object, it doesn't give us the getters - it seems like the inferred type from this line:

````ts
const { password, ...client } = this;
````

is wrong (specifically, it's `Omit<this, 'password'>` for `client`). In order to fix it, I need to change that line to 

````ts
const { password, score, ...client } = this;
````

This doesn't really have any effect on the underlying JavaScript code, so it's a minor bug (I think)

### 🔎 Search Terms

- `rest`
- `destructuring`

### 🕗 Version & Regression Information

I'm currently on `4.4.3` though running in TypeScript Playground, `3.9.7` is when it first seems to show up.

In that version, the inferred type is `Pick<this, Exclude<keyof this, "password">>`

In 3.8.3 the inferred type is the same, though the error isn't present, so there must have been a change to the underlying `Pick` code (perhaps to include getters?)

- This changed between versions 3.8.3 and 3.9.7

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.4.4#code/MYGwhgzhAECqEFMBO0DeAoAkMA9gOwgBckBXYQnJACi0wAcSAjEAS2GhJYBMAuaPEgFtGyADS0GzNtDqQIAd0q9oRJCzwBzaAHptKhARaEWANwTR1AMxxYAlGmgBfLFg0JCK3EgRVbfAcLIaLTehCRIeNAAjAAMANw6eggAHmCCdCDmuFzmALQWgmAa6uYAFmAm6loU0JbuwKUqOILupVXQYNCshISZ0IKUWc0ZKVjO6NCT0BQAwqwGhL588MhzLAvBU1vQuAQeqDJyikhcotAAdJeg63gejtAAvNNtEHET25Oh4ZEYHx8QXgQfEIL3OAMG4j+20u52uC3eH2cW2czkIAE86OYVkg1hsngB5QRGAA82LOAHJZFBjlxydAAD7Qcng7zkgB8DIcLKB-CEIhQjjiQA

### 💻 Code

```ts
class User {
    constructor(
        public uid: number,
        public password: string // sensitive info
    ) { }
	
    get score(): number {
        return 10; // example code - imagine having to fetch something a little more complex
    }

    toClient(): UserClient {
        const { password, ...client } = this;
        return {
            score: this.score, // ERROR: 'score' is specified more than once, so this usage will be overwritten
            ...client
        }
    }
}
type UserClient = Omit<User, 'password' | 'score'> | { score: number };
```

### 🙁 Actual behavior

The inferred type on `client` seems to include getters

### 🙂 Expected behavior

The inferred type on `client` to only include basic properties as it's created through destructuring

**Comment by MartinJohns** [comment] 2021-12-01 10:05
I think this is a duplicate of #36575, or at least very related. TypeScript does not distinguish between properties (getter/setter) and fields on the type level.

**Comment by whzx5byb** [comment] 2021-12-01 10:27
Workaround:  Use the specified class type instead of the polymorphic `this` type
```ts
toClient() {
    const { password, ...client } = this as User 
    return {
        score: this.score, // OK
        ...client
    }
}
```

**Comment by divillysausages** [comment] 2021-12-01 12:38
@whzx5byb Can you explain that a bit, please? Why is `this` not already considered a `User` inside it's own class method?

**Comment by fatcerberus** [comment] 2021-12-04 03:02
> Why is `this` not already considered a `User` inside it's own class method?

`this` is considered generic, i.e. `this extends User`, because your method may be called through a subclass.

**Comment by jakebailey** [comment] 2021-12-07 21:23
Thanks for giving a version range where this stopped working; I was able to bisect this to #37192.

**Comment by jakebailey** [comment] 2021-12-07 22:53
Hm, that PR is actually just what expanded out the error message; the core issue that rest destructuring `this` doesn't omit properties seems to have existed for much longer (potentially always).

Here's a modified example that shows this behavior:

https://www.typescriptlang.org/play?ts=4.5.2#code/MYGwhgzhAECqEFMBO0DeAoAkMA9gOwgBckBXYQnJACi0wAcSAjEAS2GhJYBMAuaPEgFtGyADS0GzNtDqQIAd0q9oRJCzwBzaAHptKhARaEWANwTR1AMxxYAlGmgBfLFg0JCK3EgRVbfAcLIaLTehCRIeNAAjAAMANw6eggAHmCCdCDmuFzmALQWgmAa6uYAFmAm6loU0JbuwKUqOILupVXQYNCshISZ0IKUWc0ZKVjO6NCT0BQAwqwGhL58qBzc-kIiSAkQXggA-P4IZiiOwVPn0LgEHiuyUIpIygD6otAAdB+gLAtO0AC80zaEDiEwuk1C4UiXwWIPO43Os3meEIACYlg5OMoApttrsDvwjkFThgwZMrkQHHcFEo+C93p8kR5TgDCECOjB4MhYaSIRFLozuZNnM4gA

With the desired behavior being that both `toClient` and `toClient2` have no errors, but `as User` is the only one that works consistently.

**Comment by jakebailey** [comment] 2021-12-09 01:12
I was able to "fix" the original case by not using `Omit` on `this` when destructuring, however one can also destructure a value of type `T extends SomeClassWithPropGetter` and get the same thing. The extended test case is:

```ts
class A {
    constructor(public foo: string) {}

    get bar(): number {
        return 1;
    }

    func() {
        const {           ...rest1 } = this;
        const {           ...rest2 } = this as A;
        const { foo: _f1, ...rest3 } = this;
        const { foo: _f2, ...rest4 } = this as A;

        // Rest destructuring drops properties provided by getters.
        // "bar" should not be present in any of these.
        rest1.bar;
        rest2.bar;
        rest3.bar;
        rest4.bar;
    }

    returnThis() {
        return this;
    }
}

function destructure<T extends A>(x: T) {
    const {           ...rest1 } = x;
    const {           ...rest2 } = x as A;
    const { foo: _f1, ...rest3 } = x;
    const { foo: _f2, ...rest4 } = x as A;

    // Rest destructuring drops properties provided by getters.
    // "bar" should not be present in any of these.
    rest1.bar;
    rest2.bar;
    rest3.bar;
    rest4.bar;
}
```

[Playground Link](https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8BQ1XWAewHYQC4CcBXYXDfACgAdCAjEAS2GgDMMMAuaPferAcwCUiAL5IUaPgFNc0GmAoDOWQgFsak-InFo0+aYXxZoARgDc26KIvNCWYOSHIdOzDhkJnngHQ+9eY5bQALzQuAAW9BDmnqiueIgxOj5efrgATIEh4ZHQkHDRMXHuLGycAPrMxgA00MmpAMyZoRFRFi7Y8R6sHNAVaTV1kngALE3ZMHmw5m1oAPSz0ABKQzIAJitEJAa8fNCr+BiUMJQHlBq49EPQJxgAbvTrq7IAntBSuLgaEF4zqPPQACI5PgAVwwhhCCAnlgMDJ1Nc-JIsDJeLksK8MMxmkNJD9EqljF5gQVPKk0kT5CTnA0KfgqTpUsNaVSrAz9IYACotBxafHsozjFlIKw2OwXbB7DbEXAGSQAHg50EkAA9PlhVjBYAA+cjKzgcxwWIoJRKoQb+JrKqnGjym2q+FYZYTBaDK3Ka60dYrdcqVAYOvCNZ0hK1Gr0JH29Zj9e0pFajYOu935MQ6f7LeLrbjS7b8PanY6nc6XQt3B6SJ40V7vT74b4Wf5A+SgiDgyHQ2GySQInHI6CosDo6CY7EQXEWAnMieOqdswOz3TxqfCIA)

Where all 8 accesses to `bar` should be errored.

**Comment by divillysausages** [comment] 2021-12-09 08:54
Hi @jakebailey ,

Thanks for looking at this, and getting a fix so quickly.

To be clear, in your last Playground link, it'll error on all 8 access to `bar` in a future TypeScript version? In `v4.5.2`, it only errors out on the 4 `as A` lines for me

**Comment by jakebailey** [comment] 2021-12-09 18:05
That's what my PR does, yes. You can try out my PR here: [Playground Link](https://www.staging-typescript.org/play?ts=4.6.0-pr-47078-3#code/MYGwhgzhAECC0G8BQ1XWAewHYQC4CcBXYXDfAChTWoAdCAjEAS2GjsZYAV8MaAuaHnxMsAcwA0VaqhrCAbmFwBTNvMVLuvAUJESp0AJSIAvkn2iluaBdzKKBgVkIBbekvyJ91fJcL4s0ACMANz6pvoQloKWduQA+nKOLm74Rgjh1M6WABYYACbkaV5omDhWCNKVlQB0tT54gdDG0AC80LjZTBChVdAA9H29Q70AegD8xaileIjDVbXV9bgATE2t7Z0wkHA9VQNzB6jjk+jYMxXszMCa-NBxgeLQC0sAzGttHV27lfuHc8e9ablNgMK43ARxZaPZ5KPAAFneGy60G2sG+0l+fyGxxOS0C1UuXB4NHR3lhKwJoKJvFJaFelI412JtNQSzhDLBzLMvTxBLUyhuLOgS2WfKYCgFXJ55JeYolGilVTZcvUgu5SvJ+JsdiFIuq2vcupl+pihtx5PZBvwoXNDWqkVsZuleFFDp1ttwsrdTo18Ptput6sqvKyHXyRpd1VDuTyEc9UZy4Y97OjSeopnCADNCFgSExsNA8uSiCQ-EoADwAFWgSgAHsosHkYLAAHzkWsCStFahA2ZYp51TWI2vozH9yoAkpnYH9mEu4co5ujwbjqqTqbT2aEplaO4PAeLGXD5ertcTHubi5Une3SHQwfwheok+n6Q4sl27dqj8Ur+K1nGn+NL6MqQEkkGwqaiqkrAT+oqyOKqr-pBeCygh8rfnSFrQQqwEgVBVronqhH4ahJqOoGP6WgGNo-vi3qUVhkYMURxosaRuDsuxHH4qmsYcaKfGsWRQkcSmib8cYQA)

There's unfortunately a little more nuance that my PR needs to handle better, namely, it should probably be legal to destructure non-public properties when it's `this` of the current class being unpacked; mine disallows this but probably only because I'm reusing the code that previously only ran on the non-generic case, where you're only considering the public interface of a type.

I'll make sure we discuss it beforehand.

**Comment by jakebailey** [comment] 2021-12-09 19:03
Per https://github.com/microsoft/TypeScript/pull/47078#issuecomment-990132945, dropping non-public seems correct, so the behavior I'm showing is the final one.

**Closed** 2021-12-09 19:45 UTC
Labels: Bug, Fix Available

**Comment by divillysausages** [comment] 2021-12-10 08:28
Thanks again, @jakebailey  and @RyanCavanaugh for the quick turnaround! 👍

**Comment by bergus** [comment] 2022-01-26 03:05
> as we're using destructing, only basic properties will be returned, not any getters.

This seems like an unsafe assumption. Whether a property is copied into a rest pattern depends on whether it is an *own* property, not on whether a property is a getter or a method. As far as I understand, TypeScript doesn't distinguish own from inherited properties?
