### ISSUE TITLE
Enable JSX.Element to be checked based on the element type

### ISSUE THREAD

**Issue by sdegutis** [microsoft/TypeScript#59671] opened 2024-08-17 21:42 UTC
### 🔍 Search Terms

JSX IntrinsicElements Element

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

The docs currently say:

> By default the result of a JSX expression is typed as any. You can customize the type by specifying the JSX.Element interface. However, it is not possible to retrieve type information about the element, attributes or children of the JSX from this interface. It is a black box.

This proposal is to somehow allow specifying types so that it can be decided by tsc:

```tsx
const status = <p class='status' />; // type = HTMLParagraphElement
```

### 📃 Motivating Example

The examples on https://vanillajsx.com/ all have assertions like `as HTMLParagraphElement`.

This change would enable custom JSX libraries easier to specify that `"p": HTMLParagraphElement` to avoid this.

### 💻 Use Cases

1. What do you want to use this for?

Iterate on experimental JSX implementations.

2. What shortcomings exist with current approaches?

Explicitly asserting JSX element types.

3. What workarounds are you using in the meantime?

Explicitly asserting JSX element types.

**Comment by MartinJohns** [comment] 2024-08-17 21:49
Duplicate of #21699.

**Comment by sdegutis** [comment] 2024-08-17 22:08
@MartinJohns I don't think so... I think I just got it working a few minutes ago with `JSX.ElementType` but I can't repro. But if I can, then this is already solved...

**Closed** 2024-08-22 01:31 UTC
Labels: Duplicate
