### ISSUE TITLE
Type remains narrowed when it could've changed

### ISSUE THREAD

**Issue by Jamesernator** [microsoft/TypeScript#50839] opened 2022-09-19 05:21 UTC
# Bug Report

### 🔎 Search Terms

"This condition will always return 'false' since the types"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about narrow

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/FAMwrgdgxgLglgewgAgIYGd0FMBOMAUUSAJgFzIBGCCANlqhAJTkbZ7rJETHIDewyQcjghk+AIRdijPgKHyYACxwIA7sghZ1AURwqc+AAatc8JMhCo4dYocYBuOYIC+wV8Cg1WyALIJiYHSy8gDExFgADuji5H4BdADaALqOoegwqDBg0eQARJA0cBAA1ljEucgAPsi5hSVFAOYV1bVFpeWOTsghdcUASlhQYDjocABuWPgy-PLyImJKcOgAdCHpmdnI4gC82zUFbWW5012zQjhYWTgQqWfIrnfIiytrGVkce631EE23ZyAIHBiLjpZDhCLIBCiZ6rcHoE6PeTg1a9AZDEbjSYOU5CB53GGvDYfGq9I5-e7ALo9NpTYJ3Ex4fAE9bvZC7T4HEpHbGPAmowbDUYTKbk+QMgjMt6bdkkw7lHm4tzAIA)

### 💻 Code

```ts
function assert(cond: boolean): asserts cond {
    if (!cond) {
        throw new Error(`assertion failed`);
    }
}

class Module {
    #deps!: Module[];
    #status!: "unlinked" | "linking" | "linked";

    #linkRecursive() {
        if (this.#status !== "unlinked") {
            return;
        }
        this.#status = "linking";
        for (const dep of this.#deps) {
            dep.#linkRecursive();
        }
        this.#status = "linked";
    }

    #link() {
        assert(this.#status === "unlinked");
        this.#linkRecursive();
        // This condition will always return 'false' since the types '"unlinked"' and '"linked"' have no overlap.(2367)
        assert(this.#status === "linked");
    }
}

```

### 🙁 Actual behavior

Currently this is a TS error:

```
This condition will always return 'false' since the types '"unlinked"' and '"linked"' have no overlap.(2367)
```

### 🙂 Expected behavior

I would expect there to be no reported error. Obviously full program analysis is not going to happen, but it would be good if function/method calls that directly operate on a value with mutable properties would invalidate those mutable property types.

i.e. It would be good if narrowing of non-readonly properties was invalidated by these patterns:

```ts
// fn call with narrowed value as arg
const v = { k: "a" | "b" };
assert(v.k === "a");
someFn(v); // should invalidate v.k === "a" as in general someFn might mutate v
v.someMethod(); // Also should invalidate v.k === "a" as in general someMethod might mutate v
assert(v.k === "b");
```

**Comment by fatcerberus** [comment] 2022-09-19 05:57
Duplicate of #9998.

**Comment by fatcerberus** [comment] 2022-09-19 06:07
Because you mentioned `readonly` properties, I feel compelled to point out, `{ readonly x: string }` is freely assignable to `{ x: string }`.  `readonly` is a pretty weak guarantee and only prevents you from modifying the property *through the `readonly` reference*.  It won't prevent a function you passed the object into from mutating it.

**Comment by Jamesernator** [comment] 2022-09-19 06:21
> Because you seem to be implying there could be a carve-out for `readonly` properties, I feel compelled to point out, `{ readonly x: string }` is freely assignable to `{ x: string }`

What I mean is the analysis is based on whether or not the function being passed into could write the properties. i.e. This would NOT disable narrowing because the function says it won't modify the reference:

```js
declare function someFn(v: { readonly k: "a" | "b" }): void;

const v: { k: "a" | "b" };
assert(v.k === "a");
someFn(v);
// Still an error because someFn doesn't indicate it might modify the reference
assert(v.k === "b");
```

Note that methods would have an implicit `readonly` for `readonly` class properties anyway:

```js
class Foo {
    readonly #state = "a" | "b";
    
    // has type (this: { readonly #state: "a" | "b" }) so it essentially states
    // this method doesn't modify `this.#state`
    method() {
        
    }
}
```

> Imagine if e.g. `arr.push(v)` reset narrowing on `v` just because you passed it to a function.

Yes, although really the type of `push` should reflect that it doesn't modify the argument in any way, in which case the above rules would just work:

```ts
interface Array<T> {
    // Push doesn't modify T so Readonly<T>
    push(v: Readonly<T>): number;
}
```

**Comment by Jamesernator** [comment] 2022-09-19 06:30
Also while I generalized the above to functions as well as methods, just the narrower case of invalidating other properties just based on methods would be fine. In general I think if people are declaring non-readonly properties in classes, having `.method()` invalidate all those properties shouldn't be that surprising.

**Comment by fatcerberus** [comment] 2022-09-19 06:37
It looks like your idea(s) aren't new and were also brought up in #9998.  See "Mitigating with `const` parameters" and "Mitigating with `readonly` fields" in particular.

**Comment by MartinJohns** [comment] 2022-09-19 06:57
> What I mean is the analysis is based on whether or not the function being passed into could write the properties. i.e. This would disable narrowing because the function says it won't modify the reference:

Read-only Interfaces are implicitly compatible with the writable ones. The object can easily be passed on and be modified (or using a type assertion).

**Comment by Jamesernator** [comment] 2022-09-19 08:23
> Read-only Interfaces are implicitly compatible with the writable ones. The object can easily be passed on and be modified (or using a type assertion).

If people are accepting something as readonly and then go on to try and modify it anyway, I really feel like that is their problem. Like if they wanted to modify it they shouldn't have bothered accepting a readonly value in the first place.

**Comment by fatcerberus** [comment] 2022-09-19 13:46
I suspect what @MartinJohns was getting at is that it's easy enough to do *by accident* because the type system sees nothing wrong with this code:

```ts
interface Foo { x: string }

function canMutateFoo(foo: Foo) {
    foo.x = "oops";
}

function cantMutateFoo(foo: Readonly<Foo>) {
    canMutateFoo(foo);
}

const foo: Foo = { x: "something" };
cantMutateFoo(foo);
```

Just substitute less on-the-nose names for the functions and you can see where this might go sideways. 😃

**Comment by RyanCavanaugh** [comment] 2022-09-19 18:28
> If people are accepting something as readonly and then go on to modify it anyway, I really feel like that is their problem. Like if they wanted to modify it they shouldn't have bothered specifying it as a readonly value in the first place.

The soundness hole around `readonly` is irrelevant because `readonly` doesn't mean immutable; the reverse situation is the problematic one. This program is legal *and sound*:
```ts
const obj = { x: 1 };
const view: { readonly x: number } = obj;
obj.x++;
```
Knowing that a property is `readonly` tells you nothing about whether or not its value might change between readings.

**Comment by Jamesernator** [comment] 2022-09-20 02:43
> Just substitute less on-the-nose names for the functions and you can see where this might go sideways.

Again:

> If people are accepting something as readonly and then go on to modify it anyway, I really feel like that is their problem

Really the fact that `{ readonly x: T }` is assignable to `{ x: T }` at all seems more of kindness due to the fact that SO MANY existing ts types are written as `{ x: T }` even if they don't modify the properties. Like it would be inconvenient if `{ readonly opt: boolean ]` couldn't be passed to `function doThing(opts: { opt: boolean })`, and because `readonly` is relatively new there's **a lot** of code written like `{ opt: boolean }` not `{ readonly pt: boolean }`.

> The soundness hole around `readonly` is irrelevant because `readonly` doesn't mean immutable; the reverse situation is the problematic one. This program is legal _and sound_:

This is irrelevant to the proposed solution, the point is through a `readonly` reference you shouldn't be able to mutate the value. What happens through the original reference doesn't matter because you're operating on the readonly reference.

i.e. In this situation:

```js
declare function withA(a: "a"): void;

declare function doThingReadonly(o: { readonly x: number }): void;
declare function doThing(o: { x: number }): void;

const obj: { x: "a" | "b" } = { x: "a" };
const view: { readonly x: number } = obj;

// CASE 1
assert(view.x === "a");
doThingReadonly(view);
// fine because doThing indicates it won't change .x
withA(view.x);

// CASE 2
assert(obj.x === "a");
doThingReadonly(obj);
// also fine because doThing indicates it won't change .x
withA(obj.x);

// CASE 3
assert(view.x === "a");
doThing(view);
// not fine, although this case is UNSOUND ANYWAY due to throwing away readonly-ness
// so it doesn't really matter what TS does here
withA(view.x);

// CASE 4
assert(obj.x === "a");
doThing(obj);
// also not fine, doThing may have mutated obj
viewA(obj.x);
```

Now the original issue here, CASE 4, is the fact that passing something through a non-readonly reference might mutate the value.

My proposed change doesn't change CASES 1-3 because it assumes `readonly` won't be written THROUGH A READONLY REFERENCE.

---

An alternative (weaker) fix for the original issue here would just be to disable `ts(2367)` for narrowed values if a method call has come between such calls, i.e.:

```js
assert(module.#state === "unlinked");
module.#linkRecursive();
// When reaching here TS knows a method has been called, so comparisons use the original
// module.#state : "unlinked" | "linking" | "linked" so this comparison is still legal
assert(module.#state === "linked");
```

**Closed** 2022-09-22 18:00 UTC
Labels: Duplicate
