### ISSUE TITLE
feat(): compile-ts-from-js-and-annotations-and-declarations

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/TypeScript#48937] opened 2022-05-03 16:41 UTC
# Suggestion

## 🔍 Search Terms

 
compile ts jsdoc d.ts declarations 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I am suggesting to support tsconfig settings that enable to define .js files with corrosponding .d.ts files or even only jsdoc annotations
to get compiled into a .ts file 

that flow is totally unsupported while it would solve a list of issues that are open and not really fast solve able with other strategies. 

## 📃 Motivating Example

1. Developer a creates a .d.ts file and developer b can use that d.ts file to author a .js file that picks up the types defined for that file from the .d.ts file after that he can compile that to a single .ts file compiling the ts file will result in the exact same 2 source files 

2. i got a project only as .js and .d.ts and want to work with it in typescript as single file to export only parts of it that i use i could for rebundling create again a .ts representation for internal needs 

## 💻 Use Cases

- Code Consumption ReUse 
- eliminate the need to use a bundler for that task 
- eliminate the need for manual reconstruction.
- eliminate the need to learn and understand maybe complex source build chains if you want to reuse existing tscode as you can take the bundle result + d.ts to recons

i am fine to let this only work with .js ESM code as probally CJS will spit out un analyzeable code but for ESM we could get that work!

Maybe get this working only with ESNext?

**Comment by andrewbranch** [comment] 2022-05-03 22:15
Duplicate of https://github.com/microsoft/TypeScript/issues/19285

**Closed** 2022-05-06 18:00 UTC
Labels: Duplicate
