### ISSUE TITLE
Generic function param's default value

### ISSUE THREAD

**Issue by woshiguabi** [microsoft/TypeScript#35353] opened 2019-11-26 07:32 UTC
**TypeScript Version:**  3.8.0-dev.20191125

**Search Terms:**
key of generic type, default param

**Code**

```ts
const obj = {
    foo: 1,
    bar: 'bar',
    zoo: false,
};

// Type '"foo"' is not assignable to type 'K'.
// '"foo"' is assignable to the constraint of type 'K', but 'K' could be instantiated with a different subtype of constraint 'string | number | symbol'.(2322)
function getValue<T extends { foo?: any }, K extends keyof T>(obj: T, key: K = 'foo') {
    return obj[key];
}

const result0 = getValue(obj); // expect number
const result1 = getValue(obj, 'foo'); // expect number
const result2 = getValue(obj, 'bar'); // expect string
const result3 = getValue(obj, 'zoo'); // expect boolean
```

**Expected behavior:**
Param `key` can be given a default value.
I've tried many way (such as override) to write a function what can match the expected result, but failed.
Is there a simple way to implement the function? 

**Actual behavior:**
Compile Error
Type '"foo"' is not assignable to type 'K'.
  '"foo"' is assignable to the constraint of type 'K', but 'K' could be instantiated with a different subtype of constraint 'string | number | symbol'.(2322)

**Playground Link:** 
[Background](https://www.typescriptlang.org/play/index.html?ts=3.8.0-dev.20191125&ssl=14&ssc=56&pln=1&pc=1#code/MYewdgzgLgBCBGArGBeGBvAUDHMBmIIAXDAIwA02u8AhgE4kDktdjluMAXoSXjQDYQAppQC+AbkyY8AVzDAoAS3AwA5kKgA1ATKEAeACowhADyhCwAEwgZ8hAPwkaYAJ4xR5GAGljZi9ZgAayEXEDwYAwA+AAoERBIDT2CXEh80RgIQRgBKDCocOg0ZOjA4JABtZIBdSVEpUEhYQogZfigABlQ1DW1+XVikbPEYAHoR32AhAAdYMBkAW3ghOkwG6Bhm1qhSLvUtHSEBxE8MwhzhsYnp2YWllbWmoRa2gCZdnoOjk5Zz0fHTSYzGDQOiKMCqVbgdabNoAZne+z6hziJ24WSGfyuQPghH4QmcmCAA)

**Related Issues:**

**Comment by MartinJohns** [comment] 2019-11-26 11:08
Duplicate of / same issue as #23718.

This short example shows why this is not possible:

    getValue<typeof obj, 'zoo'>(obj)

`K` is now the type `'zoo'`, but no value is provided, so the default value should be... `'foo'`? That value is not compatible with the type `'zoo'`.

**Comment by woshiguabi** [comment] 2019-11-28 02:30
@MartinJohns thanks, i got it.
But i still want to find a type definition that can match the expected result, or this is design limitation?

**Closed** 2019-12-15 00:00 UTC
Labels: Question

**Comment by xialvjun** [comment] 2020-12-31 03:54
> Duplicate of / same issue as #23718.
> 
> This short example shows why this is not possible:
> 
> ```
> getValue<typeof obj, 'zoo'>(obj)
> ```
> 
> `K` is now the type `'zoo'`, but no value is provided, so the default value should be... `'foo'`? That value is not compatible with the type `'zoo'`.

typescript should complain at `calling getValue` rather than `defining getValue`, so the caller must offer right type to `getValue`.

**Comment by xialvjun** [comment] 2020-12-31 06:48
There should be a `super constraint` https://github.com/microsoft/TypeScript/issues/29652#issuecomment-752858857
```ts
function foo<A super 4>(x?: A = 4): A {
    return x;
}

function getValue<T extends { foo?: any }, K super 'foo' extends keyof T>(obj: T, key: K = 'foo') {
    return obj[key];
}
```
