### ISSUE TITLE
ASI misinterprets assignment as function call when missing semicolon

### ISSUE THREAD

**Issue by muesli-dev** [microsoft/TypeScript#60774] opened 2024-12-16 15:19 UTC
### 🔎 Search Terms

TypeScript automatic semicolon insertion issue
missing semicolon function call
ASI issue in TypeScript
TypeScript parser bug

### 🕗 Version & Regression Information

latetest (5.7.2)

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAhgJwXAnjAvDA2gBgDQwCMBATAQMwC6AUKJLCAEYBWGMA3jFAKbQBcMHDAC+tcNBhNmJNpx78YAcjiNgikdU1SAdPNiZEyFLkowA9GfgATKwEswAc3gwI3ALa3QAG3AwAFtwI3DAAZrYAHooQXAEwthAQAK7BANzUABRSMnDRcGAoAJS6vPpKkZpikCBe3No+DumGqARSLSwkBUA

### 💻 Code

```ts
const array = [0, 1, 2, 3];

const obj = { test: 0 };
const obj2 = { test: 'abc' };

obj.test = array[0] // adding a semicolon fix's the issue ;
(obj2 as any).test = 'x'


console.log(array, obj, obj2)
```

### 🙁 Actual behavior

When I omit a semicolon between two statements, TypeScript misinterprets the code. It incorrectly assumes that the expression array[0] is a function call, rather than recognizing it as an array element. This happens when I assign a value to obj.test and later cast another object (obj2) using as any. Adding a semicolon fixes the issue, but the behavior is unexpected.

### 🙂 Expected behavior

Without a semicolon, TypeScript should treat obj.test = array[0] as a normal assignment, not as a function call. Adding a semicolon between the two lines fixes the issue, so TypeScript should properly interpret the code without needing a semicolon.

**Comment by MartinJohns** [comment] 2024-12-16 15:29
This is working as intended and unrelated to TypeScript. It's just how JavaScript works.

**Comment by nmain** [comment] 2024-12-16 16:40
Duplicate of https://github.com/microsoft/TypeScript/issues/15444.  My search terms were `semicolon type assertion parentheses`

**Comment by muesli-dev** [comment] 2024-12-17 13:59
> This is working as intended and unrelated to TypeScript. It's just how JavaScript works.
> 
> When you run this code it will try to call `array[0]` as a function. Here's an example, it will log `"foo"`:
> 
> const array = [(arg: any) => console.log(arg)]
> const test = array[0]
> ("foo")

But 

`(obj2 as any)`

should be read as a type cast not a funtion call. the typescript interpreter/compiler should treat obj.test = array[0] as a normal assignment

**Comment by nmain** [comment] 2024-12-17 15:42
Just open the Javascript console in any browser and paste this into it, and see what it does.

```javascript
const array = [0, 1, 2, 3];

const obj = { test: 0 };
const obj2 = { test: 'abc' };

obj.test = array[0]
(obj2).test = 'x'


console.log(array, obj, obj2)
```

![Image](https://github.com/user-attachments/assets/29a69e12-58e4-43af-bd48-fe9c7594a09c)

**Closed** 2024-12-17 20:39 UTC
Labels: Duplicate, Not a Defect
