### ISSUE TITLE
add a flag to disallow expression statements different than void

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#8615] opened 2016-05-16 09:19 UTC
Problem:
Funtional programming needs better support in TypeScript. Values are everything in FP and in TypeScript the expression statements just silently discard them. Not being able to track places where the values are discarded leads to severe bugs. Example:

```typescript
// before refactoring
function notify(message: string) : void {
    window.postMessage(message); // <-- assuming always works
}

// turns out that window.postMessage crashes when window gets closed
// need a check and a conditional result

// after refactoring
function notify(message: string) : Tried<void, 'cant-send-a-message'> {
    if (window.closed) {
        return failureFrom('cant-send-a-message');
    } else {
        return successFrom(window.postMessage(message));
    }
}

// after such change we need to make sure that all places that call `notify` are addressed
// it's easy to overlook those without a help from a compiler
```

Workaround:
use a linter rule

Solution:
add a flag to the compiler

**Comment by mhegazy** [comment] 2016-05-16 17:43
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/8240

**Comment by aleksey-bykov** [comment] 2016-05-16 17:45
so the linter is the way?

**Comment by mhegazy** [comment] 2016-05-16 17:50
I would want to bring it up for discussion again, since this is the third request in a few weeks for this feature.
I doubt anything will happen immediately as we do not have any precedence for the attribute/metadata syntax. ambient decorators (https://github.com/Microsoft/TypeScript/issues/2900) seems like a good candidate, but we do not have these yet.

**Comment by mhegazy** [comment] 2016-05-16 17:50
closing in favor of  #8240

**Closed by mhegazy** 2016-05-16 17:50 UTC
Labels: Duplicate
