### ISSUE TITLE
Same index export name and file name results in incorrect auto-import

### ISSUE THREAD

**Issue by Brqqq** [microsoft/TypeScript#40746] opened 2020-09-24 13:43 UTC
**TypeScript Version:**  4.1-dev.20200924 in VSCode 1.49.1 on Windows 10

**Search Terms:** auto import folder same name export

**Code**
Lets say you have the following folder structure:
```
/foo/index.ts
/entry.ts
/foo.ts
```

/foo/index.ts has the following contents:
```ts
export const Bar = 1;
```
and the other files are empty.

In `/entry.ts` you try typing "Bar" and use the auto-import feature.

**Expected behavior:**
After typing "Bar" and using the auto-import feature, the file should look like this:
```ts
import { Bar } from "./foo/";

Bar
```

**Actual behavior:**
```ts
import { Bar } from "./foo";

Bar
```

This import refers to `/foo.ts` , not `/foo/index.ts`

Note that if `/foo.ts` is not present, the actual behavior is correct.

**Playground Link:** 

**Related Issues:**

**Comment by andrewbranch** [comment] 2020-09-24 21:47
Duplicate of https://github.com/microsoft/TypeScript/issues/36730

**Closed** 2020-09-27 18:00 UTC
Labels: Duplicate
