### ISSUE TITLE
Literal types and their unions should not be mutable

### ISSUE THREAD

**Issue by KSXGitHub** [Microsoft/TypeScript#28077] opened 2018-10-23 14:07 UTC
This code should not be valid:

```typescript
let a: 'a' = 'a'
a += 'x' // 'typeof a' is still 'a' 

let b: 5 = 5
b += 7 // 'typeof b' is still 5
```

**Comment by jack-williams** [comment] 2018-10-23 14:14
This seems ok to me, though I might be missing something. At the point in the expression b _does_ have type 5, but after the expression the type of b is correctly widened.

```ts
let a: 'a' = 'a';
a += 'x';
const x: 'a' = a; // string not assignable to 'a'

let b: 5 = 5
b += 7;
const y: 5 = b; // number is not assignable to 5
```

**Comment by jack-williams** [comment] 2018-10-23 14:47
Here is a related issue: #18102

Which does point to inconsistent behaviour, for example:

```ts
let num1: 5 = 5;
num1 += 7; // ok
// num1 has type number;

let num2: 5 = 5;
num2 = num2 + 7; // error
```

I can't say if this is a bug, or by design to support certain JS idioms. Someone on the team will need to clarify that. I agree that the documentation is probably lacking on this either way though.

**Comment by jack-williams** [comment] 2018-10-23 15:31
Should the operator `++` be treated in the same way? That also widens the literal type.

**Comment by KSXGitHub** [comment] 2018-10-23 15:38
@ahejlsberg You set milestone to 3.2 but I think this might be a breaking change

**Comment by collin5** [comment] 2018-11-21 23:07
Opened a pull request (a few weeks back) to solve an issue related to this. #28344

**Comment by ahejlsberg** [comment] 2019-02-01 20:49
I'm going to close this as a duplicate of #14745 and move the conversation to here.

**Closed by ahejlsberg** 2019-02-01 20:49 UTC
Labels: Bug, help wanted
