### ISSUE TITLE
const function variable cannot reference itself

### ISSUE THREAD

**Issue by jamiewinder** [Microsoft/TypeScript#10912] opened 2016-09-14 12:02 UTC
**TypeScript Version:**  2.0.2

With this code:
```ts
const mouseUpListener = (upEvent: MouseEvent) => {
    // (do something)
    window.removeEventListener('mouseup', mouseUpListener); // *1
};
```
I get an error on line *1 saying: "Variable 'mouseUpListener' is used before being defined". I can change `const` to `let` and it works, but I'm not sure I see the difference (the function body won't ever run until the variable is set, so is `const`).

Is this expected / correct?

**Comment by yortus** [comment] 2016-09-14 12:22
Looks like a duplicate of #9382

**Closed** 2016-09-14 19:17 UTC
Labels: Duplicate
