### ISSUE TITLE
Valid ES6 allowJs `error TS8014: 'property declarations' can only be used in a .ts file.`

### ISSUE THREAD

**Issue by dave-hillier** [Microsoft/TypeScript#7216] opened 2016-02-24 13:28 UTC
**TypeScript Version:** 

1.8.2

**Code**

```ts
// A self-contained demonstration of the problem follows...
class Repro
{
    static property = {
	foo: "bar"
    };
}
```

`tsc --allowJs --out out.js repro.js`

**Expected behavior:**

Compiles without error 

**Actual behavior:** 

```
repro.js(3,5): error TS8014: 'property declarations' can only be used in a .ts file.
```

**Comment by RyanCavanaugh** [comment] 2016-02-24 17:43
Duplicate of #6997

**Comment by RyanCavanaugh** [comment] 2016-02-24 17:44
Just to confirm, are you also transpiling with Babel's Stage 0 preset?

**Closed by RyanCavanaugh** 2016-02-24 17:43 UTC
Labels: Duplicate

**Comment by dave-hillier** [comment] 2016-02-24 17:48
I haven't got that far yet. I wanted to try out the allowJs option on an existing code base. I simply ran tsc to reproduce this. I might just switch to using full typescript

**Comment by RyanCavanaugh** [comment] 2016-02-24 18:07
If you don't have an external transpiler in the toolchain, then that error message is definitely correct -- this code doesn't run on any current JS runtime.

**Comment by dave-hillier** [comment] 2016-02-25 10:22
so allowJs doesnt support ES6 in?

**Comment by RyanCavanaugh** [comment] 2016-02-25 17:41
This isn't ES6 syntax. ES6 does not have property initializers.
