### ISSUE TITLE
TS Server crashes once TS file is open

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15716] opened 2017-05-10 04:53 UTC
_From @aminpaks on May 9, 2017 11:21_

- VSCode Version: 1.12.1
- OS Version: macOS 10.12.4 (16E195)

The project is private so I can't share the code or steps to reproduce it though I'm going to provide some logs, hopefully will be enough. If you need something else please ask.
The file that I open is about 1100 lines and it's a pure typescript file that is importing some of `lodash`, `d3` and `angular v4`.
As soon as I open this file TS Server crashes and nothing will work anymore! TS Server restarts but it gets stuck at binding forever, and the only way to get Code to work is to restart.
This issue started right after updating to 1.12

[Here is the TS Server log file](https://pastebin.com/7PSLXsGC)
[Here is the ChromeDevTools console](http://i65.tinypic.com/1z4ki20.png)

_Copied from original issue: Microsoft/vscode#26299_

**Comment by mjbvz** [comment] 2017-05-10 04:53
_From @aminpaks on May 9, 2017 17:43_

So apparently the issue is with Typescript v2.3.x, it works with v2.2.x
Should I inform Typescript team, or you guys can move this?

**Comment by mjbvz** [comment] 2017-05-10 04:57
Moving over to TypeScript repo since it sounds like the issue only happens when TypeScript 2.3 is used. I don't see anything suspicious in the log file or the the developer tools screenshot

@aminpaks  Can you try setting `"typescript.tsserver.trace": "verbose"` in VSCode and reproducing the issue. Then open the output panel and share the output from the `TypeScript` section. This may provide some additional clues to what is going wrong

Also does this happen for all projects, or just the one project you are working in?

**Comment by aminpaks** [comment] 2017-05-10 10:36
Sure Matt,

[Here is the TS Server trace log](https://pastebin.com/P9R4gqzW)

**Comment by westonpace** [comment] 2017-05-11 03:34
This seems very similar to #15028 .  I've recorded my observations there but it's about the same, crashes as soon as I open (actually it won't crash until I try and resolve a particular symbol in my file), doesn't occur on 2.2 but does on 2.3, etc.

**Comment by andy-ms** [comment] 2017-05-12 22:18
This looks similar to #15688. In both cases:
* A request is sent.
* Semantic diagnostics are sent back.
* The original request is never answered.
* A bunch of other requests are immediately canceled.

**Comment by andy-ms** [comment] 2017-07-12 17:50
Hi @aminpaks, @westonpace, we're trying to confirm if this can still happen in `typescript@next`. We can't get much from the server logs, since all they show is that TypeScript is failing somewhere inside `quickInfo`, presumably somewhere inside the checker. Could either of you find a scenario that reproduces this that you're willing to share? If you know the symbol whose hover causes the problem, you should be able to extract out just the parts of your related to that symbol to reproduce the error.

**Comment by aminpaks** [comment] 2017-07-12 23:29
@andy-ms I'd really like to help, and I tried to reproduce it with `typescript@next` but no luck.
I'll keep you updated if I had a chance to catch it.

**Comment by mhegazy** [comment] 2017-08-16 21:37
closing for now. please reopen if you see the issue again.

**Closed by mhegazy** 2017-08-16 21:37 UTC
Labels: Bug, VS Code Tracked
