### ISSUE TITLE
Refactoring operations shouldn't reach external definitions such as lib.d.ts and node_modules

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#15776] opened 2017-05-11 19:59 UTC
**TypeScript Version:**  2.3

**Comment by mhegazy** [comment] 2017-05-11 20:03
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/7458

**Comment by falsandtru** [comment] 2017-05-11 20:22
#7458 treats a part of this issue. But I think #7458 is not enough. It is too much detail.

**Comment by mhegazy** [comment] 2017-05-11 20:25
it is the issue we are using to track this change. not sure having two issues helps any one.

**Comment by falsandtru** [comment] 2017-05-11 20:43
I feel if #8227 is not dup, this is not dup. If this is dup, #8227 is dup.

**Comment by mhegazy** [comment] 2017-05-25 23:35
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-05-25 23:35 UTC
Labels: Duplicate
