### ISSUE TITLE
Namespace exports and special properties don't get checked for use-before-declaration

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#26484] opened 2018-08-16 00:08 UTC
```ts
new N.C
N.x

function N() {}

namespace N { 
    export class C {
    }
    export let x = 10;
}
```

**Expected**:

```
Class 'C' used before its declaration.
Variable 'x' is used before being assigned.
```

or

```
Class 'C' used before its declaration.
Property 'x' is used before being assigned.
```

**Actual**

```
Class 'C' used before its declaration.
```

Similarly, for functionality in `master`, we should do the same checking

```ts
Foo.defaultProps

function Foo({ x, y, z }: { x: number, y: string, z: boolean }) {
}

Foo.defaultProps = {
    x: 0,
};
```

Currently doesn't error, but **should** produce the following message:

```
Property 'defaultProps' is used before being assigned.
```

**Comment by sandersn** [comment] 2018-08-16 15:48
Duplicate of #21327

**Closed by sandersn** 2018-08-16 15:48 UTC
Labels: Bug
