### ISSUE TITLE
Syntatic sugar for callable namespaces (functions as namespace)

### ISSUE THREAD

**Issue by KSXGitHub** [Microsoft/TypeScript#23735] opened 2018-04-27 09:06 UTC
I have a **suggestion**: I love to write callable namespaces but I don't want to write its name twice (one for function, one for namespace), so I propose a syntax sugar for this:

```typescript
export namespace myFunc {
  (x: number) => square(2 * x)
  export const square = (x: number) => x * x
}
```

This should be equivalent to:

```typescript
export function myFunc (x: number) {
  return myFunc.square(2 * x)
}

export namespace myFunc {
  export const square = (x: number) => x * x
} 
```

---

**Search Terms:** 
callable namespace syntax sugar

**Comment by AlCalzone** [comment] 2018-04-27 13:11
Related, but not sure if duplicate:
https://github.com/Microsoft/TypeScript/issues/21572
https://github.com/Microsoft/TypeScript/issues/15868

**Comment by mhegazy** [comment] 2018-04-27 15:52
I would consider this a dupe of https://github.com/Microsoft/TypeScript/issues/15868.

https://github.com/Microsoft/TypeScript/issues/15868 is JS syntax, and no need to create new constructs if one already exists.

**Closed** 2018-05-14 16:09 UTC
Labels: Duplicate

**Comment by bluelovers** [comment] 2018-05-31 03:03
@mhegazy where is that `syntax for function + namespace` ?

can u post a link?

**Comment by AlCalzone** [comment] 2018-05-31 13:03
https://www.typescriptlang.org/docs/handbook/declaration-merging.html scroll down to about 2/3.

```ts
function buildLabel(name: string): string {
    return buildLabel.prefix + name + buildLabel.suffix;
}

namespace buildLabel {
    export let suffix = "";
    export let prefix = "Hello, ";
}
```
