### ISSUE TITLE
Bring back unused variable highlight in JavaScript

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#10503] opened 2016-08-23 16:54 UTC
_From @saharso on August 21, 2016 8:16_

When I first started using vs code, There used to be a very useful green highlighting for variables that were declared, but not used throughout the code. This was very helpful with keeping my code clean and tidy. For some reason this feature was removed a few months ago. I can't see why. Please bring it back.

Sahar Soffer.

_Copied from original issue: Microsoft/vscode#10755_

**Comment by waderyan** [comment] 2016-08-23 16:54
_From @alexandrudima on August 22, 2016 7:55_

fyi @dbaeumer

**Comment by waderyan** [comment] 2016-08-23 16:54
_From @dbaeumer on August 22, 2016 8:35_

@waderyan this is something the tsserver has to implement.
@saharso you can use a linter plugin (like eslint) to get that feature.

**Comment by DanielRosenwasser** [comment] 2016-08-24 01:26
I'm going to close this as a duplicate of #10449.

**Closed** 2016-08-24 06:16 UTC
Labels: Duplicate
