### ISSUE TITLE
Formatting with multi-line if condition

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript#15895] opened 2017-05-17 00:45 UTC
**TypeScript Version:**  nightly (2.4.0-dev.20170516)

**Code**

Type:

```ts
if (a
    && b) {
```

Hit enter. Type `return true;`. Hit enter. Type `}`.

**Expected behavior:**

```ts
if (a
    && b) {
    return true;
}
```

**Actual behavior:**

```ts
if (a
    && b) {
        return true;
    }
```

**Comment by SaschaNaz** [comment] 2017-05-26 23:10
This is a regression from some point of 2.2-2.4.

**Comment by RyanCavanaugh** [comment] 2024-03-07 23:11
Closing due to lack of interest

**Closed by RyanCavanaugh** 2024-03-07 23:11 UTC
Labels: Bug, Help Wanted, Domain: Formatter
