### ISSUE TITLE
isArrayType declared internally returns `type is TypeReference` however the converse is not true

### ISSUE THREAD

**Issue by NilsIrl** [microsoft/TypeScript#55510] opened 2023-08-25 13:41 UTC
### ⚙ Compilation target

N/A

### ⚙ Library

N/A

### Missing / Incorrect Definition

From `src/compiler/checker.ts`:

```ts
isArrayType(type: Type): type is TypeReference;
```

This implies that if `isArrayType` returns false then `type` is not a `TypeReference` which may not be the case as pointed out by https://github.com/microsoft/TypeScript/issues/55010#issuecomment-1634776672.

If instead an interface ArrayType was added like so:

```ts
interface ArrayType extends TypeReference {}
```
and `isArrayType` updated like so:
```ts
isArrayType(type: Type): type is ArrayType;
```

Then the signature would be safe and correct. This will then allow the externally available compiler API to match the internal one. Currently because the internal signature of `isArrayType` is not safe the external signature instead is:

```ts
isArrayType(type: Type): boolean;
```

### Sample Code

```TypeScript
if (typeChecker.isArrayType(type)) {
    // complains that type is not TypeReference
    typeChecker.getTypeArguments(type);
}
```

### Documentation Link

Continuation of #55010

**Comment by jakebailey** [comment] 2023-08-25 13:49
I don't understand; is this not just #55010, which you filed and we closed as working as intended? Is there any new info here?

**Comment by NilsIrl** [comment] 2023-08-25 15:04
In #55010, because the proposed solution was not safe/strictly correct, the issue was marked as working as intended. The solution proposed here is safe.

Adding an empty interface helps because if `isArrayType` returns `false`. Then the assertion is that `type` is not an `ArrayType` but that doesn't imply that `type` isn't a `TypeReference`.

**Comment by MartinJohns** [comment] 2023-08-25 15:22
> Adding an empty interface helps because if `isArrayType` returns `false`. Then the assertion is that `type` is not an `ArrayType` but that doesn't imply that `type` isn't a `TypeReference`.

I don't see how this is true. According to your definition **every** `TypeArray` is also a `TypeReference`, because these types are structurally the same.

**Closed** 2023-08-28 01:25 UTC
Labels: Duplicate

**Comment by NilsIrl** [comment] 2023-08-28 08:18
Oops. I didn't realize typescript treats two types as the same if they have the same structure.

Adding a field to make `ArrayType` and `TypeReference` distinct would work. Using `__brand` is conventional according to https://www.typescriptlang.org/play/?q=30#example/nominal-typing

**Comment by jakebailey** [comment] 2023-08-28 10:15
We have many branded types internally; but I think it stands to be seen why this change really needs to be made and whether or not there's some bug this fixes or something.

**Comment by NilsIrl** [comment] 2023-08-28 12:08
The motivation for fixing this bug is shown in the following example:

```ts
if (typeChecker.isArrayType(type)) {
    // complains that type is not TypeReference
    typeChecker.getTypeArguments(type);
}
```

Currently, either a cast needs to be performed or an extra check needs to be performed.

Otherwise the internal declaration is not strictly correct but it hasn't caused any bugs that I know of.
