### ISSUE TITLE
Auto-Property support

### ISSUE THREAD

**Issue by emdadgar2** [Microsoft/TypeScript#8858] opened 2016-05-27 15:46 UTC
Hi,
Please make typescript auto-property support like C# to easier use.

Thanks.

**Comment by sandersn** [comment] 2016-05-27 16:37
Can you give more detail? What would you like to write in TypeScript, and how would you have to write it today?

**Comment by emdadgar2** [comment] 2016-05-28 16:53
Today, we must use this syntax:
```
class foo {
    private _bar:Boolean = false;
    get bar():Boolean {
        return this._bar;
    }
    set bar(value:Boolean) {
        this._bar = value;
    }
}
```

it's better use this like syntax:
```
class foo {
    get bar():Boolean;
    set bar(value:Boolean);
}
```
or
```
class foo {
    set get bar():Boolean;
}
```
or
```
class foo {
    property bar():Boolean {get;set;};
}
```

C# implements this option. Take a look at:
[https://msdn.microsoft.com/en-us/library/bb384054.aspx](url)

Thanks

**Comment by gneuvill** [comment] 2016-06-03 11:37
Or, as an alternative : 
```typescript
class foo {
  constructor(private bar: boolean) {}
}
```
should both initialize the `bar` field _and_ generate the accessors for it. (but what if I only want the getter ...?)

**Comment by kitsonk** [comment] 2016-06-03 14:47
Essentially a duplicate of #7628 (which was out of scope)

**Comment by RyanCavanaugh** [comment] 2016-06-03 18:11
I don't understand what the use case is. The motivations for using properties instead of fields in C# generally aren't applicable to JavaScript/TypeScript.

**Comment by gneuvill** [comment] 2016-06-03 18:33
> I don't understand what the use case is. The motivations for using properties instead of fields in C# generally aren't applicable to JavaScript/TypeScript.

Pedantically, this is called the 'uniform access principle' : inside the `foo` class, that the `bar` field is named 'bar' is an implementation detail ; I should be able to rename it without affecting the call sites (which would still access the data through a 'bar' identifier). Moreover, that the data is accessed though a field dereference or a method dereference is also an implementation detail : the syntax should be the same in both cases (and not be `bar()` or `getBar()` as in java).

But you surely already know that and the bore that it is to write those accessors by hand... So why not have the compiler do that dirty work for us ?

**Comment by mhegazy** [comment] 2016-06-04 19:05
> should both initialize the bar field and generate the accessors for it. (but what if I only want the getter ...?)

use `readonly`:

```ts
class foo {
  constructor(private readonly bar: boolean) {}
}
```

> So why not have the compiler do that dirty work for us ?

auto-implemented properties a la C# are identical to property declarations in TS. so the proposal of 
```ts
class foo {
    property bar():Boolean {get;set;};
}
```

is 
```ts
class foo {
    bar: boolean;
}
```

**Comment by mhegazy** [comment] 2016-06-04 19:08
As noted by @kitsonk this is a duplicate of  #7628. and as noted in #7628, JS already have an accessor declaration syntax, adding yet another form incurs a chance of conflicting syntax between TS and JS; and  moreover, it is not clear that it adds much value vs. the cognitive cost of yet a new declaration form.

**Closed by mhegazy** 2016-06-04 19:08 UTC
Labels: Needs Proposal

**Comment by anetegithub** [comment] 2017-03-13 04:51
What about decorators?
```typescript
class foo {
    @validate
    get set bar():Boolean;
}
```
