### ISSUE TITLE
Assignment not correctly inferred when checking string literal.  Variable X is used before being assigned 

### ISSUE THREAD

**Issue by KilianB** [microsoft/TypeScript#59356] opened 2024-07-19 11:43 UTC
### 🔎 Search Terms

Variable  is used before being assigned
2454

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Bugs

Old as well as nightly `v.5.6.0-dev.20240719`

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240719&ssl=11&ssc=1&pln=1&pc=1#code/MYewdgzgLgBAZiEMC8MAUIAOUCW4IBcMA5AILECUKAfDAN4BQMzMANgKawBOnArl2ABqAQ1a92RaFxxgA5gG4GTFjjjosufCmSoylespYseUfkNHiUJAMogAtuxgix7YoqMBfJUYD0PmADC9piswjIQMMIARiC83HwCMABuFo5gILBR7DKyMDI4uKI4AF7sACaGMCZmVQnmLooeikA

### 💻 Code

```ts
const foo = (options: 'A') => {
    let returnValue: string;

    if (options === 'A') {
        returnValue = 'Some Value';
    }

    // Complains about returnValue not being initialized
    return returnValue;
};
```

### 🙁 Actual behavior

Error message that the returnValue is used before assignment.

### 🙂 Expected behavior

If all possible code paths of options have been covered ts should know that the variable is initialized.

**Comment by Andarist** [comment] 2024-07-19 12:02
Duplicate of https://github.com/microsoft/TypeScript/issues/56527

**Closed** 2024-07-29 01:31 UTC
Labels: Duplicate
