### ISSUE TITLE
Include inferred usages in 'find references'

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#12685] opened 2016-12-06 11:29 UTC
``` ts
type Child = { name: string }
type Parent = { children: Child[] }
const createParent = (): Parent => (
  { children: ['foo', 'bar']
    .map((name) => ({ name }))
  }
)
```

TS is type-checking `Parent`, which involves type checking the `children` property and thus each `Child.

When I select `name` inside my Array mapper function and invoke TS to find references, VSCode/TypeScript server does not include the original type definition of `Child.name`:

![image](https://cloud.githubusercontent.com/assets/921609/20923969/eb3c6d5c-bba6-11e6-91f3-c8870b8d20e9.png)

(See `Child.name` is not highlighted).

However, if I add the type annotation for `Child`, it does include it in the list of references:

``` ts
type Child = { name: string }
type Parent = { children: Child[] }
const createParent = (): Parent => (
  { children: ['foo', 'bar']
    .map((name): Child => ({ name }))
  }
)
```

![image](https://cloud.githubusercontent.com/assets/921609/20923979/fb88be04-bba6-11e6-8a07-43ceebc496a9.png)

Would it be possible to make TypeScript include the references that are inferred instead of annotated, e.g. example 1 as well as example 2?

**Comment by andy-ms** [comment] 2017-05-11 19:07
The problem is that in `(name) => ({ name })`, the type of `{ name }` isn't inferred to be `Child`. It's inferred to be `{ name: string }`, a *different* type which happens to be assignable to `Child`. So it's not the case that `({ name })` *is* a `Child`, but it's assignable to one.

So find-all-references won't work because the `name` there is actually a different property, defined on a newly created type.

The real fix for this situation would be to provide contextual types even through generic calls, so that `({ name })` would be interpreted as a `Child` literal and not as its own type. See #15680.

**Closed by andy-ms** 2017-05-11 19:07 UTC
Labels: Design Limitation, Suggestion

**Comment by andy-ms** [comment] 2017-05-27 18:28
#15680 is closed now but that didn't fix this. See #11152 and #3423 now.
