### ISSUE TITLE
`tsc --build` and tsconfig project references treat paths ending in `.jsonc` as directories

### ISSUE THREAD

**Issue by zenekron** [microsoft/TypeScript#60261] opened 2024-10-17 20:00 UTC
### 🔎 Search Terms

"jsonc", "references", "build", "tsconfig"

### 🕗 Version & Regression Information

5.6.3

### 💻 Code

```jsonc
// tsconfig.json
{
  "references": [
    { "path": "./tsconfig.dev.jsonc" }
  ]
}
```

```jsonc
// tsconfig.dev.json
{
  "compilerOptions": {
    "composite": true
  }
}
```

### 🙁 Actual behavior

The paths are treated as directory paths, `tsc` appends `tsconfig.json` to them and tries to access a file that won't exist:

```sh
$ tsc --build ./tsconfig.json
error TS5083: Cannot read file '<...>/tsconfig.dev.jsonc/tsconfig.json'.


Found 1 error.
```

```sh
$ tsc --build ./tsconfig.dev.jsonc
error TS5083: Cannot read file '<...>/tsconfig.dev.jsonc/tsconfig.json'.


Found 1 error.
```

### 🙂 Expected behavior

I would expect `tsc --build` and `references` to behave the same as `tsc --project` and `extends`: load `.jsonc` files they are pointed at with no particular extra handling.

### Additional information about the issue

I submitted this issue as a bug instead of a feature request because other `tsc` commands already handle files with the `.jsonc` extension as expected (e.g. `--project` and tsconfig's `extends` field) and because the [documentation](https://www.typescriptlang.org/docs/handbook/project-references.html) explicitly states the following:

> The path property of each reference can point to a directory containing a tsconfig.json file, or to the config file itself (which may have any name)."

This leads me to believe that the current behavior expressed by `tsc --build` and tsconfig's `references` field is not intended and thus a bug.

**Comment by Luke080808** [comment] 2024-10-17 23:02
Lo

**Comment by MartinJohns** [comment] 2024-10-18 13:42
Duplicate of / related: #43121

**Comment by zenekron** [comment] 2024-10-18 20:37
> Duplicate of / related: [#43121](https://github.com/microsoft/TypeScript/issues/43121)

Some of the considerations made in #43121 and their proposed solution #43173 will likely still apply to this issue, especially what was said about extending the `Extension` enum:

> Dont think the addition of extensionless here is appropriate. There are so many places we handle extension we would need to go see to check and verify if they need update.
Eg. In general when JSON extension is converted to JSON target for parsing and determining what to do with it and something like that. If we return extension as JSON i am sure something will break somewhere in API usage as well. (getScriptSnapshot of LS etc)
I am not sure this is complete change.
So this is going to need more testing and detailed review that involves verifying those usages from different angles like running tsserver scenario, LS scenario, APIs etc rather than just parsing test>
>
> _Originally posted by @sheetalkamat in https://github.com/microsoft/TypeScript/pull/43173#discussion_r612693722_

---

After some investigation it looks like the cause of the issue is the `resolveConfigFileProjectName` function which appends `tsconfig.json` to the project path if it does not end in `.json`:

https://github.com/microsoft/TypeScript/blob/d48a5cf89a62a62d6c6ed53ffa18f070d9458b85/src/compiler/tsbuild.ts#L176-L183

Unlike #43173, my proposal would be to leave the `Extension` enum untouched and instead mimic what already happens with `tsc --project` which is to only append `tsconfig.json` if the path points to an existing directory:

https://github.com/microsoft/TypeScript/blob/d48a5cf89a62a62d6c6ed53ffa18f070d9458b85/src/compiler/executeCommandLine.ts#L606-L620

The `resolveConfigFileProjectName` would end up looking something like the following, and some effort would be needed to propagate the appropriate `System` down to this function, but it should be nowhere close to having to modify the `Extension` enum while ensuring that nothing breaks.

```ts
export function resolveConfigFileProjectName(system: Pick<System, directoryExists>, project: string): ResolvedConfigFileName { 
    if (system.directoryExists(project)) {
        return combinePaths(project, "tsconfig.json") as ResolvedConfigFileName;
    }

    return project as ResolvedConfigFileName;
}
```

**Comment by zenekron** [comment] 2024-10-18 20:44
@RyanCavanaugh apologies for the mention but could I ask you to reconsider the `Duplicate` status, especially in light of my last comment.

While the two issues are definitely related I do not believe there's overlap in either what problems they address nor their proposed solutions.

**Closed** 2024-10-21 01:33 UTC
Labels: Duplicate
