### ISSUE TITLE
Type guards in class method not working

### ISSUE THREAD

**Issue by csleead** [Microsoft/TypeScript#17359] opened 2017-07-22 17:49 UTC
TypeScript Version:  2.4.1

```
declare var caseInsensitiveCompare: (s1: string,s2: string) => boolean;
class AnswerChecker {
    possibleAnswers: string[];
    input: string | null;
    public isCorrect(): boolean {
        if (this.input === null) {
            return false;
        }
        
        return this.possibleAnswers.some(a => caseInsensitiveCompare(a, this.input)); // Compilation error
    }
}
```

**Expected behavior**:
Should compile because this.input is not null in the return statement

**Actual behavior**:
this.input is still treated as "string | null" and cause compilation error

**Remarks**:
This only happens when class member is used directly. If isCorrect is implemented like this
```
public isCorrect(): boolean {
        if (this.input === null) {
            return false;
        }

        let x = this.input
        return this.possibleAnswers.some(a => caseInsensitiveCompare(a, x));  
    }
```
The code compiles

**Comment by aluanhaddad** [comment] 2017-07-23 01:27
This is a duplicate of many many issues. The reason this happens is that there is no knowledge the compiler has as to when a callback will be executed. A callback passed to `Array.prototype.some` will indeed be executed immediately but this is not something which is generally true for all callbacks.

**Comment by RyanCavanaugh** [comment] 2017-07-24 16:45
Duplicate of #9998 / #11498

**Closed by RyanCavanaugh** 2017-07-24 16:45 UTC
Labels: Duplicate
