### ISSUE TITLE
Should allow 'symbol' as the type of an index signature

### ISSUE THREAD

**Issue by snytkine** [Microsoft/TypeScript#12932] opened 2016-12-15 00:15 UTC
**TypeScript Version:**  2.1.4 

**Code**

```ts
state:{[key:symbol]:any}
```

**Expected behavior:**
Should allow this
According to Mozilla: A symbol is a unique and immutable data type. It may be used as an identifier for object properties. 
**Actual behavior:**
Error: TS1023 an index signature parameter must be a string or number

**Comment by DanielRosenwasser** [comment] 2016-12-15 00:33
I'm not certain whether this should be considered a dupe of #1863.

**Comment by snytkine** [comment] 2016-12-15 00:38
@DanielRosenwasser  I think #1863 is different issue. The code mentioned in 1863 works fine in 2.1.4

**Comment by JsonFreeman** [comment] 2016-12-15 01:04
@snytkine is right about the original code in #1863, but then there's the [comment](https://github.com/Microsoft/TypeScript/issues/1863#issuecomment-73475036) further down.

**Comment by mhegazy** [comment] 2016-12-15 17:29
This is a duplicate of #1863. please see my comment in https://github.com/Microsoft/TypeScript/issues/1863#issuecomment-247679106.

**Closed** 2016-12-29 19:30 UTC
Labels: Duplicate
