### ISSUE TITLE
Simple Overload syntax

### ISSUE THREAD

**Issue by nilslindemann** [microsoft/TypeScript#39654] opened 2020-07-18 17:30 UTC
## Search Terms

"Typescript Github issue overloading" (via google, i see no search entry in the [page you linked](https://github.com/Microsoft/TypeScript/search?type=Issues))

I can not say that i understood about what these people talked (And i understand Haskell Monads...) So if this is a duplicate issue, forgive me.

## Suggestion

Implement an overload syntax, which is

* easy to use
* pretty to look at
* performant in the generated Javascript
* nice to read in the generated Javascript

## Example

I write in TypeScript:

```typescript
interface Apple { taste:string }
interface Banana { color:string }

// 'overloaded' is the new syntax
overloaded function eat ( apple:Apple ) {
    console.log(`eat ${apple.taste} apple`);
}

overloaded function eat ( banana:Banana ) {
    console.log(`eat ${banana.color} banana`);
}

let apple: Apple = { taste: 'tasty' };
let banana: Banana = { color: 'yellow' };

eat( apple );
eat( banana );
```

TypeScript generates this Javascript:

```javascript
function eat_Apple ( apple ) {
    console.log(`eat ${apple.taste} apple`);
}

function eat_Banana ( banana ) {
    console.log(`eat ${banana.color} banana`);
}

let apple = { taste: 'tasty' };
let banana = { color: 'yellow' };

eat_Apple( apple );
eat_Banana( banana );
```

i am aware of the following way to do it currently, checking for interface membership using the `is` trick:

```typescript
interface Apple { taste:string }
interface Banana { color:string }

function isApple(apple: any): apple is Apple { 
    if ('taste' in apple) { 
        return true;
    }
    return false;
}

function isBanana(banana: any): banana is Banana { 
    if ('color' in banana) { 
        return true;
    }
    return false;
}

function eat(which: Apple|Banana) {
    if (isBanana(which)) { 
        let banana = which as Banana
        console.log(`eat ${banana.color} banana`);
    } else if (isApple(which)) { 
        let apple = which as Apple
        console.log(`eat ${apple.taste} apple`);
    }
}

let apple: Apple = { taste: 'tasty' };
let banana: Banana = { color: 'yellow' };

eat( apple );
eat( banana );
```

* It sucks to write all this code.
* There is duplication.
* It is not easy to read – `isBanana(banana: any): banana is Banana` – Thats banana.
* The eat function signature is not pretty (`which` parameter is not expressive).
* The non performant membership tests go into the output.

## Checklist

*I guess* my suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-07-18 17:53
Duplicate of #3442.

> [x] This feature would agree with the rest of TypeScript's Design Goals.

I'd say this goes against goal 6, and non-goal 1 and 5.

**Comment by nilslindemann** [comment] 2020-07-18 18:29
#3442 That issue where principal @kitsonk is purposefully misunderstanding the purpose.

Goal and non-goal violations:

* I dont see how it goes against **goal 6**, please elaborate.
* **Non-goal 1**: well, TypeScript uses *types*, lets make use of them.
* **Non-goal 5**: yes thats a good argument. But there are cases where practicality beats purity. What i like about this is the **terse syntax** and that i pay **no performance price** for it – no runtime type checks and no OOP slowdown/brainfuck by creating classes where i dont want them. (In TypeScript) **no ugly long function names** repeating the information which is already contained in the parameter types. Just sweet interfaces, and sexy short function names. Also, a solution to the 'into which class do i put this method' problem (Answer: in no class).

**Comment by nilslindemann** [comment] 2020-07-18 20:13
@MartinJohns Ok, i see what you mean with goal 6, the fact that `overloaded` may be added to the javascript language. But that may also be the case with the other keywords TypeScript defines, eg. `interface`.

**Comment by nilslindemann** [comment] 2020-07-18 20:40
I think this issue is different from the other issue, because

* the syntaxes suggested there are different and
* my request is more narrow – i am just interested in some syntactical sugar without the implicit typing/OOP foobar.

This shall just be a small but useful syntactical addon to the already existing tools in the language.

**Comment by nilslindemann** [comment] 2020-07-18 20:57
`qualified` or `typed` may be alternatives to `overloaded`.

**Comment by kitsonk** [comment] 2020-07-18 21:08
> That issue where principal @kitsonk is purposefully misunderstanding the purpose.

I was not purposefully misunderstanding the purpose.

Your proposal is still a type directed emit, which is against the design goals of TypeScript.

**Comment by nilslindemann** [comment] 2020-07-18 23:00
Well, close it then.

**Comment by kitsonk** [comment] 2020-07-19 04:27
I have no power to close issues.

**Comment by RyanCavanaugh** [comment] 2020-07-20 17:16
This is a duplicate of #3442 and I don't understand why anyone would argue otherwise. Anyway it requires type-directed emit, which is a no-go.

**Closed by RyanCavanaugh** 2020-07-20 17:16 UTC
Labels: Duplicate
