### ISSUE TITLE
ES6 imports not emitted when referenced in JSX element (using import alias)

### ISSUE THREAD

**Issue by use-strict** [Microsoft/TypeScript#4854] opened 2015-09-18 11:04 UTC
Considering this example:

```typescript
import React = require("react");
import {Components} from "some-lib"; // <- this import is not emitted
import MyComponent = Components.MyComponent;

class Wrap extends __React.Component<{}, {}> {
    render() {
        return <MyComponent></MyComponent>;
    }
}
```

Assuming the following definition for "some-lib"
```typescript
declare module "some-lib" {
    namespace Components {
        class MyComponent extends __React.Component<{}, {}> {}
    }
}
```

The problem seems to occur only when using an alias import ("import MyComponent = Components.MyComponent"). If the component is exported as a top-level symbol the problem doesn't reproduce.

Replacing the JSX.Element with "React.createElement(MyComponent, null)" or simply adding a "console.log(MyComponent)" makes the issue not reproducible as well.

Could be related to https://github.com/Microsoft/TypeScript/issues/4688

Reproduces with latest (1.6.2) compiler.

**Comment by vladima** [comment] 2015-09-18 17:19
looks like a dupe of #4675

**Closed by vladima** 2015-09-18 17:19 UTC
Labels: Bug, Duplicate
