### ISSUE TITLE
Dotted access bypasses the read-only declaration of indexer

### ISSUE THREAD

**Issue by jonaskello** [Microsoft/TypeScript#18373] opened 2017-09-10 20:21 UTC
**TypeScript Version:**  2.5.2

**Code**

```ts
let foo: { readonly [key: string]: number } = { "a": 1, "b": 2 };
foo["a"] = 3; // Error: Index signature only permits reading
foo.a = 3; // No error
```

**Expected behavior:**
Objects declared read-only should be immutable.

**Actual behavior:**
Dotted access bypasses the read-only declaration.

This was not a problem before [dotted access](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#dotted-property-for-types-with-string-index-signatures) was added in 2.2.

Technically, the behaviour may be considered correct since only the indexer is declared read-only. However, practically, since 2.2 the consumer of the object is free to choose between index access or dotted access, and so can make unwanted mutations without even knowing it. So in practice, the provider that declares the indexer readonly can no longer make a strong assumption that the objects will not be mutated by consumers. So this basically renders the readonly declaration of indexers useless.

**Comment by sandersn** [comment] 2017-09-11 17:49
Duplicate of #14296, which is fixed in master and `typescript@next`

**Closed by sandersn** 2017-09-11 17:49 UTC
Labels: Bug
