### ISSUE TITLE
TypeScript bug in Proxy handler method

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#19899] opened 2017-11-10 06:21 UTC
I made a video on this bug:
https://www.useloom.com/share/5f89ee1de6f84abbbf9703af3b34c00c

**Code**

```ts
  t.$inject = new Proxy(self.__inject, {
       set(target, property, value, receiver){
          throw new Error('cannot set any properties on t.$inject (in test cases).');
       }
  });
```

**Expected behavior:**
Expect `throw` to supercede API requirements

**Actual behavior:**
Need to return a boolean even after a `throw` call.

Here is a screenshot of the error message:

![screenshot 2017-11-09 22 19 30](https://user-images.githubusercontent.com/11139560/32645478-4b2f9838-c59c-11e7-9045-695332fbf30d.png)

**Comment by andy-ms** [comment] 2017-11-10 14:25
Duplicate of #16874.

**Comment by ORESoftware** [comment] 2017-11-10 18:15
cool +1

**Closed** 2017-11-27 18:38 UTC
Labels: Duplicate
