### ISSUE TITLE
Incorrect Generics inference with keyof, conditional types

### ISSUE THREAD

**Issue by goloveychuk** [Microsoft/TypeScript#22765] opened 2018-03-21 17:59 UTC
**TypeScript Version:**  2.8.0-dev.20180321

**Code**

```ts

declare function setIn<T,
    K extends Keyof<T>,
    V extends Val<T, K>,
    K2 extends Keyof<V>>(
        val: T,
        [k, k2]: [K, K2],
        v: Val<V, K2>): T


class List<T> {
    __brand!: string
}



type Keyof<T> = T extends List<any> ? number : keyof T

type Val<T, K> = K extends keyof T ? T[K] : T extends List<infer LT> ? LT : never


class User {
    b!: List<number>

    c!: List<string>
}


let a!: User


setIn(a, ['b', 3], 32) // ok, should ok
setIn(a, ['b', 3], 'sd') // no error, should error
setIn(a, ['b', 3], true) // error, should error
```

**Expected behavior:**
`setIn(a, ['b', 3], 'sd')` expected to have compile error
**Actual behavior:**
No error.

Problem is that `K extends Keyof<T>,` is inferred as `'b' | 'c'`, but should be 'b'.
If we remove `c!: List<string>` from `User` - everything working ok.

Will defining explicit generics variance help with this?

**Comment by RyanCavanaugh** [comment] 2018-03-21 18:37
@ahejlsberg thoughts on how to address this? The root cause appears to be the undesirable distribution of `K` in `Val`, but the `[K]` trick doesn't work because the `keyof` constraint doesn't transfer over:
```ts
// As written
type Val<T, K> = K extends keyof T ? T[K] : T extends List<infer LT> ? LT : never
// Fix?
type Val<T, K> = [K] extends [keyof T] ? T[K] : T extends List<infer LT> ? LT : never
//                                       ~~~~
//                            Can't index T with type K
```

**Comment by ahejlsberg** [comment] 2018-03-21 20:50
#22707 already has a fix for the constraint transferring over in `[T] extends [xxx]` constructs.

**Comment by goloveychuk** [comment] 2018-03-22 11:52
Ok, so those will be fixed. 
Other question: any plans to write such a code better way?
So now we don't have variadics and should those long chains of `keyof`s to work with variable number of args. 
Ok. Let's say we have variadics implemented. They will help in `curry`, `assign` and many others cases, but not in setIn. Since we need somehow to add this `keyof` constraint for variadics.
The option could be to add another new syntax, smth like
`type Path<T> =  { infer ...K extends keyof T[K'] }`
But it's started to be very complicated.
So the question is - maybe it'd be good option to add api for computed types, to fill those very specific cases (like setIn).
smth like
```ts
type A<T> = function(type: ts.Type) { 
        ... some logic
        return type
}
```
Thanks

**Closed** 2018-03-26 10:48 UTC
