### ISSUE TITLE
Suggestion: Pick by type 

### ISSUE THREAD

**Issue by rokoroku** [Microsoft/TypeScript#16350] opened 2017-06-08 04:50 UTC
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
interface AnInterface {
  stringProperty: string;
  numberProperty: number;
  objectProperty: object;
  functionProperty1: () => number;
  functionProperty2: Function;
  functionProperty3(): number;
}
type PickByType<O extends object, T extends any> = {
  // suggestion here: we should be able to filter object property somehow.
  [K in keyof O && typeof O[K] is T]: O[K];
};
type StringOnly = PickByType<AnInterface, string>; // { stringProperty: string; }
type NumberOnly = PickByType<AnInterface, number>; // { numberProperty: number; }
type ObjectOnly = PickByType<AnInterface, object>; // { objectProperty: object; }
type WithoutFunction = StringOnly & NumberOnly & ObjectOnly; // { stringProperty: string; numberProperty: number; objectProperty: object; }  


```

**Expected behavior:**
In this scenario, we can pick object's properties by their type. 
It will be useful when extracting **properties** from **class** type. 
 
**Actual behavior:**
I couldn't find the way to achieve this scenario.
And also, complex index signature like `K in keyof O && typeof O[K] is T` is not supported yet.

**Comment by mhegazy** [comment] 2017-06-08 05:37
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/12424

**Closed by mhegazy** 2017-06-08 05:37 UTC

**Comment by zheeeng** [comment] 2018-06-14 08:06
@mhegazy Sorry for bothering you, I didn't find out a meet solution from #12424

I tried this:
```typescript
type OmitString<T> = {
    [P in keyof T]: T[P] extends string ? never : T[P];
};
type T = OmitString<{ foo: string, bar: number }>;

// T is expanded as:
type T = { foo: never; bar: number; }
```

We lost the 'in' operator type guard in this way. I expected `T` is:
```typescript
type T = { bar: number; }
```

**Comment by zheeeng** [comment] 2018-06-14 17:44
@mhegazy Thx very much! I learned from you.

**Comment by arnaudriegert** [comment] 2019-08-22 09:48
@mhegazy I get the following error when I try your bit of code:

```
    TS2344: Type 'Exclude<keyof T, { [P in keyof T]: T[P] extends string ? never : P; }[keyof T]>' does not satisfy the constraint '"data" | "length" | "normalize" | "assignedSlot" | "wholeText" | "splitText" | "appendData" | "deleteData" | "insertData" | "replaceData" | "substringData" | "baseURI" | "childNodes" | ... 53 more ... | "replaceWith"'.
  Type 'keyof T' is not assignable to type '"data" | "length" | "normalize" | "assignedSlot" | "wholeText" | "splitText" | "appendData" | "deleteData" | "insertData" | "replaceData" | "substringData" | "baseURI" | "childNodes" | ... 53 more ... | "replaceWith"'.
    Type 'string | number | symbol' is not assignable to type '"data" | "length" | "normalize" | "assignedSlot" | "wholeText" | "splitText" | "appendData" | "deleteData" | "insertData" | "replaceData" | "substringData" | "baseURI" | "childNodes" | ... 53 more ... | "replaceWith"'.
      Type 'string' is not assignable to type '"data" | "length" | "normalize" | "assignedSlot" | "wholeText" | "splitText" | "appendData" | "deleteData" | "insertData" | "replaceData" | "substringData" | "baseURI" | "childNodes" | ... 53 more ... | "replaceWith"'.
        Type 'keyof T' is not assignable to type '"replaceWith"'.
          Type 'Exclude<string, { [P in keyof T]: T[P] extends string ? never : P; }[keyof T]> | Exclude<number, { [P in keyof T]: T[P] extends string ? never : P; }[keyof T]> | Exclude<symbol, { [P in keyof T]: T[P] extends string ? never : P; }[keyof T]>' is not assignable to type '"data" | "length" | "normalize" | "assignedSlot" | "wholeText" | "splitText" | "appendData" | "deleteData" | "insertData" | "replaceData" | "substringData" | "baseURI" | "childNodes" | ... 53 more ... | "replaceWith"'.
            Type 'Exclude<string, { [P in keyof T]: T[P] extends string ? never : P; }[keyof T]>' is not assignable to type '"data" | "length" | "normalize" | "assignedSlot" | "wholeText" | "splitText" | "appendData" | "deleteData" | "insertData" | "replaceData" | "substringData" | "baseURI" | "childNodes" | ... 53 more ... | "replaceWith"'.
              Type 'string' is not assignable to type '"data" | "length" | "normalize" | "assignedSlot" | "wholeText" | "splitText" | "appendData" | "deleteData" | "insertData" | "replaceData" | "substringData" | "baseURI" | "childNodes" | ... 53 more ... | "replaceWith"'.
                Type 'Exclude<string, { [P in keyof T]: T[P] extends string ? never : P; }[keyof T]>' is not assignable to type '"replaceWith"'.
                  Type 'Exclude<keyof T, { [P in keyof T]: T[P] extends string ? never : P; }[keyof T]>' is not assignable to type '"replaceWith"'.
                    Type 'keyof T' is not assignable to type '"replaceWith"'.
                      Type 'string | number | symbol' is not assignable to type '"replaceWith"'.
                        Type 'string' is not assignable to type '"replaceWith"'.
                          Type 'Exclude<string, { [P in keyof T]: T[P] extends string ? never : P; }[keyof T]> | Exclude<number, { [P in keyof T]: T[P] extends string ? never : P; }[keyof T]> | Exclude<symbol, { [P in keyof T]: T[P] extends string ? never : P; }[keyof T]>' is not assignable to type '"replaceWith"'.
                            Type 'Exclude<string, { [P in keyof T]: T[P] extends string ? never : P; }[keyof T]>' is not assignable to type '"replaceWith"'.
                              Type 'string' is not assignable to type '"replaceWith"'.
```

I'm not very familiar with these intricacies of TS so I can't really make sense of it. I'm guessing it has to do with the version of TypeScript (I'm using v3.5.3). Any idea?
