### ISSUE TITLE
Type guard failures that become an intersection type

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#9859] opened 2016-07-21 06:47 UTC
**TypeScript Version:**  2.0.0

**Code**

``` ts
class A<T> {
  private _: T;
}
class B<T> {
  private _: T;
}
function f() {
  var o: A<void> | B<void> = new B<void>();
  if (o instanceof A) return o; // B<void> & A<any>, should be A<void>
}
```

**Expected behavior:**

A type of `o` narrowed by type guard is `A<void>`.

**Actual behavior:** 

A type of `o` narrowed by type guard is `B<void> & A<any>`.

**Comment by yortus** [comment] 2016-07-21 11:58
I'd say this follows from #8911/#9016.

`o` is narrowed to `B<void>` when you assign `new B<void>` to `o`. Then the compiler sees the `o instanceof A` as further narrowing and comes up with the intersection type.

I suspect the `A & B` type, which seems impossible in terms runtime behaviour, seems fine to the compiler which is just concerned about the structural intersection of the `A` and `B` types.

**Comment by yortus** [comment] 2016-07-21 12:00
Note this comment in particular: https://github.com/Microsoft/TypeScript/issues/8911#issuecomment-224672366

**Comment by mhegazy** [comment] 2016-07-21 23:04
then options here are either `never

**Comment by falsandtru** [comment] 2016-07-21 23:27
This problem caused by declared type internal overwriting. This behavior should be a bug because following code works correctly.

```ts
class A<T> {
  private _: T;
}
class B<T> {
  private _: T;
}
function f() {
  var o: A<void> | B<void>;
  if (o instanceof A) return o; // A<void>
}
```

**Comment by mhegazy** [comment] 2016-07-21 23:33
I am not sure i understand what you meant there. but the important difference between the two samples is the assignment...

```ts
var o: A<void> | B<void> = new B<void>();

// here o can only be `B<void>` and nothing else. no assignments has happened to o since it got `new B<void>()`

if (o instanceof A) return o;  /// now how can we narrow B into A?
```

**Comment by falsandtru** [comment] 2016-07-21 23:40
@mhegazy why do you think "working as intended" about that difference? The two samples should be a same narrowed type by type guard.

**Comment by yortus** [comment] 2016-07-21 23:53
@falsandtru assignments cause narrowing as per #8010. Then subsequent narrowing to an unrelated type   narrows to the intersection of the two narrowed types as per #9031. According to those two rules, your example is indeed working as intended.

Your sample is a bit like the following, which produces the same intersection narrowed type:

```ts
class A<T> {
  private _: T;
}
class B<T> {
  private _: T;
}
function f() {
  var o: A<void> | B<void>;
  if (o instanceof B) {
      if (o instanceof A) return o; // B<void> & A<any>, should be A<void>
  }
}

```

**Comment by falsandtru** [comment] 2016-07-22 00:04
I understood that behavior, but I'm not sure that which is a spec, or a bug.

**Comment by yortus** [comment] 2016-07-22 00:30
Why would it be a bug? Control flow analysis can infer:

1. That `o` is a `B` throughout the body of `f`, since a `B` is assigned to `o` and there are no subsequent assignments that could change it to something else.
2. That the only way we could reach the guarded `return o` statement is if `o` is an `A`. And since `o` is already known to be a `B`, then `o` must be an `A & B` in that guarded clause.

**Comment by falsandtru** [comment] 2016-07-22 00:32
Merging #9861.

```ts
class A<T> {
  private _: T;
}
class B<T> {
  private _: T;
}
function f() {
  var o: A<void> | B<void> = new B<void>();
  if (!(o instanceof B)) return o; // B<void>, should be A<void>
  o; // B<any>, should be B<boid>
}
```

Merging #9862.

```ts
class A<T> {
  private _: T;
}
class B<T> {
  private _: T;
}
function f() {
  var o: A<void> | B<void> = new A<void>();
  o instanceof A || o instanceof B;
  o; // A<any>, should be A<void> | B<void>
}
```

**Comment by mhegazy** [comment] 2016-07-22 00:37
the first case is again because of the initialization. there is no way for `o` to be any thing but `B`. so checking `!(o instanceof B)` is really not meaningful here. so you have `B`, you take out `B`, what are you left with..

**Comment by falsandtru** [comment] 2016-07-22 01:05
I see, I think we can close this issue. However, a compiler option for detection of this assignment type mismatch is helpful to avoid these confusing. A declared type shouldn't be wider than an assigned type in these CFA behaviors.

**Comment by yortus** [comment] 2016-07-22 01:12
> A declared type shouldn't be wider than an assigned type 

A wider declared type allows for re-assignment later on:

```ts
let a: string | number = 'foo';
a; // a is narrowed to string here
a = 42;
a; // a is narrowed to number here
```

**Comment by falsandtru** [comment] 2016-07-22 01:18
It case seems an anti-pattern.

**Comment by yortus** [comment] 2016-07-22 01:21
@falsandtru why an anti-pattern?

**Comment by falsandtru** [comment] 2016-07-22 02:19
It should be

```ts
const a: string = 'foo';
const b: number = 42;
```

Also see #9886.

**Comment by yortus** [comment] 2016-07-22 03:05
There's plenty of discussion about this in #8513. Note the realistic motivating example involves modelling an `Optional<T>` type as a union of `Some<T>` and `None`, and some control flow that initialises an `Optional` to `None` and then possibly reassigns it with a `Some` value.

I don't think you can simply say

> It should be
> 
> ```ts
> const a: string = 'foo';
> const b: number = 42;
> ```

in light of legitimate examples where people are trying to model runtime-valid code using TypeScript, where union variables with initializers occur naturally as a result.

**Comment by falsandtru** [comment] 2016-07-22 03:44
My example is based on immutable programing. So I suggested as optional in #9886.

**Comment by yortus** [comment] 2016-07-22 03:54
OK, then if you make the variable in your first example immutable:

```ts
function f() {
  const o: A<void> | B<void> = new B<void>();
  if (o instanceof A) return o; // B<void> & A<any>, should be A<void>
}
```

...then it seems an even stronger case for the current compiler behaviour being correct, doesn't it? Or have I misunderstood what you mean by immutable?

**Comment by falsandtru** [comment] 2016-07-22 04:03
It example is a bad case. So I said "But this operation is a mistake, should be removed." in #9886. My suggestion is useful for finding mistakes like this.

**Closed** 2017-04-19 18:55 UTC
Labels: Working as Intended
