### ISSUE TITLE
intelliSense for implements interface and extends

### ISSUE THREAD

**Issue by octref** [Microsoft/TypeScript#11971] opened 2016-11-01 07:41 UTC
**TypeScript Version:**  2.0.6

Using VSCode 1.7 Insider:

![image](https://cloud.githubusercontent.com/assets/4033249/19882526/89065842-9fcb-11e6-94d2-116e8a90a9c0.png)

**Expected behavior:**

intelliSense suggests `talk(): string`, which is a required method for the interface.

**Actual behavior:** 

No suggestion.

Also hope this can be implemented for `extends`, as it'll come handy when extending abstract class.

**Comment by mhegazy** [comment] 2016-11-01 16:19
Duplicate of https://github.com/Microsoft/TypeScript/issues/7158

**Closed by mhegazy** 2016-11-01 16:19 UTC
