### ISSUE TITLE
Terrible trouble with Map

### ISSUE THREAD

**Issue by isoftninja** [Microsoft/TypeScript#30807] opened 2019-04-08 10:34 UTC
```
class T {
    static map = new Map<string, object>();
    static getInstanceById(id:string): object {
        if ( !T.map.has( id ) ) {
            T.map.set( id, {} );
        }

        return T.map.get( id ); // >>>
    }
}

/** <<<
 * TS2322: Type 'object | undefined' is not assignable to type 'object'.
 * Type 'undefined' is not assignable to type 'object'.
 */
```

```
// very bad!
class T0 {
    static map = new Map<string, object>();
    static getInstanceById(id:string): object {
        let result = T0.map.get( id );

        if ( !result ) {
            result = {};

            T0.map.set( id, result );
        }

        return result;
    }
}
// Good!
class T1 {
    static map = new Map<string, object>();
    static getInstanceById(id:string): object {
        return T1.map.has( id ) ? T1.map.get( id ) : T1.map.set( id, {} ).get( id );
    }
}

```

**Comment by nmain** [comment] 2019-04-08 15:52
Duplicate of https://github.com/Microsoft/TypeScript/issues/9619

Either use the `T0` form or a `!` type assertion, or perhaps encapsulate the login from `T0` into some sort of `getValueOrDefault` helper function.

**Closed** 2019-04-11 18:00 UTC
Labels: Duplicate
