### ISSUE TITLE
Array(n) is spreaded incorrectly in arrays

### ISSUE THREAD

**Issue by zuzusik** [Microsoft/TypeScript#14088] opened 2017-02-15 13:38 UTC
**TypeScript Version:**  2.1.6

**Code**

```ts
[...Array(5)]
```

**Expected behavior:**
Array filled with `undefined` 5 times (this is how it should be by the spec and how Chrome/FF/Safari do it)

**Actual behavior:**
Empty array with length set to 5

**Comment by alex3165** [comment] 2017-02-15 14:13
Typescript compile it to `Array(5).slice();` https://www.typescriptlang.org/play/#src=%5B...Array(5)%5D%0D%0A

**Comment by zuzusik** [comment] 2017-02-15 14:16
@alex3165 yes, it does, and this is wrong because it gives non spec compliant result

**Comment by alex3165** [comment] 2017-02-15 14:29
@zuzusik Agreed, it is not really expected

**Comment by mhegazy** [comment] 2017-02-15 20:46
Duplicate of https://github.com/Microsoft/TypeScript/issues/8856

**Closed** 2017-04-19 18:54 UTC
Labels: Duplicate
