### ISSUE TITLE
Visual Studio doesn't honor imports and generates fields again

### ISSUE THREAD

**Issue by rvdn** [Microsoft/TypeScript#4151] opened 2015-08-04 16:30 UTC
If in the project file, one states:
```<Import Project="Imports.props" />```

and with import.props the following 
```<?xml version="1.0" encoding="utf-8"?>:Ld
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <UseIISExpress>false</UseIISExpress>
    <IISExpressSSLPort />
    <IISExpressAnonymousAuthentication />
    <IISExpressWindowsAuthentication />
    <IISExpressUseClassicPipelineMode />
    <UseGlobalApplicationHostFile />
 <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\WebApplications\Microsoft.WebApplication.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\WebApplications\Microsoft.WebApplication.targets')" />
  <ProjectExtensions>
    <VisualStudio>
      <FlavorProperties GUID="{349c5851-65df-11da-9384-00065b846f21}">
        <WebProjectProperties>
          <SaveServerSettingsInUserFile>True</SaveServerSettingsInUserFile>
        </WebProjectProperties>
      </FlavorProperties>
    </VisualStudio>
  </ProjectExtensions>
</Project>```

When the project is being compiled, the fields are generated again in the main project file. (This works with C# and C++ projects)

**Comment by woppa684** [comment] 2015-08-04 16:38
```xml
 <?xml version="1.0" encoding="utf-8"?>
 <Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
     <UseIISExpress>false</UseIISExpress>
     <IISExpressSSLPort />
     <IISExpressAnonymousAuthentication />
     <IISExpressWindowsAuthentication />
     <IISExpressUseClassicPipelineMode />
     <UseGlobalApplicationHostFile />
     <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\WebApplications\Microsoft.WebApplication.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\WebApplications\Microsoft.WebApplication.targets')" />
     <ProjectExtensions>
     <VisualStudio>
     <FlavorProperties GUID="{349c5851-65df-11da-9384-00065b846f21}">
     <WebProjectProperties>
     <SaveServerSettingsInUserFile>True</SaveServerSettingsInUserFile>
     </WebProjectProperties>
     </FlavorProperties>
     </VisualStudio>
     </ProjectExtensions>
 </Project> 
```

**Comment by mhegazy** [comment] 2015-08-04 17:13
looks like a dupe of #4131

**Closed by mhegazy** 2015-08-04 17:13 UTC

**Comment by rvdn** [comment] 2015-08-04 18:19
The additional issue here is that the properties are regenerated while that is not done with 4131

**Comment by mhegazy** [comment] 2015-08-04 18:39
what do you mean by "regenerated"? can you elaborate?

**Comment by mhegazy** [comment] 2015-08-04 18:39
what do you mean by "regenerated"? can you elaborate?

**Comment by rvdn** [comment] 2015-08-04 19:38
The fields are being placed back in the projectfile automatically by visual studio. The typescript specific fields not.

**Comment by mhegazy** [comment] 2015-08-04 19:43
I do not think this is the Typescript language service that is doing this. the only piece that writes to the project file in the Typescript plugin in, is the project property pages. did you change project properties through the project property pages? when does this write event happen?

**Comment by rvdn** [comment] 2015-08-04 19:48
It happens on the compile command from visual studio.

**Comment by mhegazy** [comment] 2015-08-04 19:54
that is interesting. this happens on a clean project, i.e. open project, build. with no changes to the project or any files. correct?

And it is only the IIS*/ProjectExtension properties? if so, i think this the C# webproject project system that is forcing these properties to be added and not the TypeScript VS plugin.

**Comment by rvdn** [comment] 2015-08-04 19:58
Indeed that is the case. Open project, build without changes. And indeed the iis/projectextension properties

**Comment by mhegazy** [comment] 2015-08-04 20:00
Looks like the project system expects these properties to be in the file, and will add them if they are missing on load. not sure who would know more about this. let me ask around and see if i can find the right owner.

**Comment by rvdn** [comment] 2015-08-07 18:29
Have you found the right owner and will it be solved?

**Comment by mhegazy** [comment] 2015-08-07 22:41
I emailed a couple of folks. have not heard back from any one yet.

**Comment by mhegazy** [comment] 2015-08-07 22:42
@madskristensen do you know who should we talk to about this issue?

**Comment by madskristensen** [comment] 2015-08-08 07:21
Perhaps @sayedihashimi knows?

**Comment by sayedihashimi** [comment] 2015-08-08 08:48
@billhiebert any ideas?

**Comment by rvdn** [comment] 2015-08-18 07:47
Any news?
