### ISSUE TITLE
Duplicate signature on overloading doesn't error

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#6247] opened 2015-12-25 14:52 UTC
Shouldn't below code give me red squiggles on the duplicate overloaded signature?
```typescript
function f(a: string, b: number): boolean;
function f(a: string, b: number): boolean;
function f(a: string, b?: string | number, c?: string): boolean {
	return true;
}
```

**Comment by DanielRosenwasser** [comment] 2015-12-25 17:28
I believe this is a duplicate of #802.

**Closed** 2015-12-25 17:28 UTC
Labels: Duplicate
