### ISSUE TITLE
ts(2531) Object is possibly 'null' error when using Boolean in expression

### ISSUE THREAD

**Issue by gamtiq** [microsoft/TypeScript#42466] opened 2021-01-23 21:13 UTC
# Bug Report

### 🔎 Search Terms

2531,
Object is possibly 'null' Boolean

### 🕗 Version & Regression Information

4.1.3

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Boolean, null

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.3#code/JYOwLgpgTgZghgYwgAgKoGdrIN4ChkHIhwC2EAXMumFKAOYDcuAvrrjAK4gJjAD2IZMHQZoACgBucADYcKyLgGsQfAO4gAlJSmyUwtJig58hAPSnkAFQAWKGH2nS19ZBAAeABygR06fiHRkBDgOTGQAIgB5ACMAKwgeIUCPPl9gaOkAT2QAchAORxyAOjEAJgBWAGYARg1w1ygoPigTAm8wDihBMEyPCD4YZB05ZABecdy+OISwHOQAMnnkACE+Bwg4EEkZOQ0FpbE80gg50CGdiA0mQmRzZHbOwVX1ze3dPcXkHr6B890xiY5KbxHhzT6HYhkU6CYaXa5mCwPLrIACEKNh+y+vX6gwx41Gk2moMxEOO0L+uyYrVuFhsdgcTlULncXh8fgEgTg3mQMFAEGpdyR3WxvzxgOBMzBSzRGPBRyhQhhFyuAsREA6yOe0g2W1lS2+OIpKHxhJBsxJ8pOiqNGhVrCAA)

### 💻 Code

```ts
interface User {
    name: string;
}

function isUser(value: unknown): value is User {
    return typeof value === 'object' && Boolean(value) && ('name' in value);
}
```
Also "Object is possibly 'null'.(2531)" error can be caused by using the following expressions:
```ts
return Boolean(value) && typeof value === 'object' && ('name' in value);
```
```ts
return !!value && typeof value === 'object' && ('name' in value);
```

### 🙁 Actual behavior

TypeScript complains that `value` is possibly `null` in `('name' in value)` check.
But the previous checks assure that value is object, not `null`.

### 🙂 Expected behavior

No error in the mentioned expressions.

By the way the following expressions are error-free:
```ts
return typeof value === 'object' && !!value && ('name' in value);
```
```ts
return Boolean(value && typeof value === 'object' && ('name' in value));
```

I'm not sure whether this issue is a duplicate of #16655 or not.

**Comment by MartinJohns** [comment] 2021-01-23 22:43
It's a duplicate of #16655.

**Closed** 2021-01-29 18:00 UTC
Labels: Duplicate
