### ISSUE TITLE
Add a tsconfig option to assume every .ts file is a module

### ISSUE THREAD

**Issue by osyrisrblx** [Microsoft/TypeScript#27535] opened 2018-10-03 22:45 UTC
Currently with TypeScript, if I create two files and put `const foo = "bar";` in each, I will get the following error:

![image](https://user-images.githubusercontent.com/9200592/46443600-4090d980-c73c-11e8-9a0a-1c5668ab3b30.png)

For the specific environment I'm using, this is not the case at runtime. I'd like to silence this error with a tsconfig.json option.

One current workaround is to put `export {};` in all my files to instruct TypeScript that the file is a module, but I'd like to avoid doing so.

**Comment by osyrisrblx** [comment] 2018-10-03 22:49
More info about workaround found here:
https://stackoverflow.com/questions/40900791/cannot-redeclare-block-scoped-variable-in-unrelated-files

**Comment by RyanCavanaugh** [comment] 2018-10-03 22:54
Duplicate of #18232

**Closed** 2018-10-08 11:01 UTC
Labels: Duplicate

**Comment by osyrisrblx** [comment] 2019-05-29 22:39
@RyanCavanaugh Any chance of a tsconfig.json option to force all files to be considered modules?
