### ISSUE TITLE
Incorrect function parameter type resolution

### ISSUE THREAD

**Issue by bolt-igor** [microsoft/TypeScript#46991] opened 2021-12-02 13:26 UTC
# Bug Report

### 🔎 Search Terms
- enum type resolution

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Type System Behaviour and Generics

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.2#code/KYOwrgtgBAYg9nKBvAUFKBBKBeKAiAQzwBo0oAhHfAIxJQF8UUBjOEAZwBcppdV0A2vDgA6DAF0AXFAAUBacLEBKHAD5k9UoMXkps6goQjyK7OqSaGAbiYAzMCGacAlmyi2EAHgAqUYAA9OUAATdlgEVRkANwIAG2lvJWkouGdg5DJWDm5bKggBGNjxKygAelL3KHZgYAgwzkQACwIo4ChORraAJ2cAc0buTgBPAAc2zq7gMnQZ2bnZ8qgsrndpfnmN+cWoeVldxQxTdRS0m03zme2DfUNREzUoE+Czi-PF+gFvcTJbaLilEqLDrOMLBODAdggADk3AA7nAugBrKDUYDMAhgaqVAJjJxhAggHZdXqQUDcOC5YZjKAgYCtLrTDaLZY5aRyYkABmktPpR0eqWCDBQQA)

### 💻 Code

```ts
enum Foo {
  A = "a",
  B = "b",
}

const m = {
  [Foo.A]: (a: Foo.A) => {},
  [Foo.B]: (b: Foo.B) => {},
};

function foo<T extends Foo>(val: T): void {
  const f = m[val]; // f seems to have the right type here
                    // const f: {
                    //  a: (a: Foo.A) => void;
                    //  b: (b: Foo.B) => void;
                    // }[T]
  f(val); // this doesn't work because f expects an argument of type never
          // const f: (arg0: never) => void
}

```

### 🙁 Actual behavior

`f(val)` fails to compile

### 🙂 Expected behavior

I would expect `f(val)` to compile since we know that `val` is of type `Foo` meaning it's either `Foo.A` or `Foo.B`. If it's `Foo.A` then `f` is of type `(a: Foo.A): void`, if it's `Foo.B` then `f` is of type `(b: Foo.B): void`. In both cases invoking `f(val)` seems like a proper invocation.

**Comment by MartinJohns** [comment] 2021-12-02 13:36
I think this is the same as #33014.

`f` will be a union of all cases, because the compiler doesn't know what type `T` actually is. When calling a union function you must provide arguments that match all possible cases, but an intersection `"a" & "b"` is impossible, so you end up with `never`.

**Comment by bolt-igor** [comment] 2021-12-02 13:46
@MartinJohns 
This is what happens now, yes. However I believe this could be improved.
If we  introduce an extra type hint for the `m` variable, like this
```
const m: {[key in Foo]: (a: key) => void} = {
  [Foo.A]: (a: Foo.A) => {},
  [Foo.B]: (b: Foo.B) => {},
};
```
then the line `const f = m[val];` should produce `f` of a type `(a: T) => void`. Thus making the invocation `f(val)` possible since `val` has type `T`.

**Comment by RyanCavanaugh** [comment] 2021-12-03 18:28
The problem is that this program is, from TypeScript's perspective, the same as this one which induces an unsoundness through a legal call to `foo`:
```ts
enum Foo {
  A = "a",
  B = "b",
}

const m = {
  [Foo.A]: (a: Foo.A) => { console.log(`a = ${a}`)},
  [Foo.B]: (b: Foo.B) => { console.log(`b = ${b}`)},
};

function foo<T extends Foo>(val1: T, val2: T): void {
  const f1 = m[val1];
  const f2 = m[val2];
  f1(val2);
}
// Prints 'a = b', a contradiction
foo<Foo>(Foo.A, Foo.B);
```
Even #33014 doesn't help in this case, since no operation "narrows" `T`. We'd need a separate and additional concept beyond that, where a given *value* of a generic type is tracked. But then even with that it's not clear how to proceed - it's easy from a human perspective to see that `m` has a neat 1:1 mapping of `[Foo.A]` to `(p: Foo.A) =>` but that's not a first-class concept either, so presumably the checker would have to combinatorially explode all legal inhabitants of the constraint(s) and ensure each of them checked.

**Comment by RyanCavanaugh** [comment] 2021-12-08 17:24
Mapped types are eagerly resolved into their object equivalents wherever possible; this is generally desirable because mapped types are usually just shorthand ways of expanding out a repetitive pattern. There's not really machinery in place to keep both formulations of them around and choose the best one depending on the situation -- that sort of thing tends to lead to weird consistency problems.

That said, it still wouldn't help without some sort of "same value" tracking to resolve the `val1`/`val2` problem. So this pattern is two fairly large type system leaps away from being possible to check as hoped for.

**Comment by bolt-igor** [comment] 2021-12-09 09:08
I see. Last question then:
> So this pattern is two fairly large type system leaps away from being possible to check as hoped for.

Are these leaps planned for any foreseeable future (any place to track them)?

Thanks again, and I believe this might be closed for now.

**Comment by RyanCavanaugh** [comment] 2021-12-09 17:53
You can start at #30581

**Closed by RyanCavanaugh** 2021-12-09 17:53 UTC
Labels: Design Limitation

**Comment by bolt-igor** [comment] 2021-12-27 14:46
Hi @RyanCavanaugh, I can see that the PR got merged and it's possible to make my initial code to compile which is great! However, I also noticed that your example [(Playground link)](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211227#code/KYOwrgtgBAYg9nKBvAsAKClAglAvFAIgEMCAadTAIT0ICMz0BfddAYzhAGcAXKCALmQBtANbAAnlACWIWAgC6ggBRFBY8QEo8APigA3OFIAmjGqgxQh8OADosiqCsHW7W3LqRR2XOABtgNr5wAOZKAAZENAAkSESMYRqM5BZWCDaUDkq0zmmUbh5eHJx+AUGhYbTRSLTxicmMANwsaABmYCCs3FIcUC0IADwAKlDAAB7coEaccnDaSnpEvgCMgoOk+osATKsaggbGyBSFXLwtSzQQQgvL8k0W3jy9mxdXW7dHZ-NbGnfMaAD0-ygAAUAE4ybjTADkkXwtCh60i3m4oKIRiknW6IHQfTg-WscxcWHWLjyDSAA) also compiles now while I believe it shouldn't, should it?

**Comment by RyanCavanaugh** [comment] 2022-01-03 18:44
After fielding this issue for many years we decided to give up and take the soundness hit. Cautious implementors of `foo` can write
```ts
function foo<T extends Foo, U extends Foo>(val1: T, val2: U): void {
  const f1 = m[val1];
  const f2 = m[val2];
  f1(val2); // error
}
```
