### ISSUE TITLE
Failed to access the interface behind it when intersecting an interface with the same key.

### ISSUE THREAD

**Issue by etch-cure** [microsoft/TypeScript#56777] opened 2023-12-14 02:20 UTC
### 🔎 Search Terms

interface intersection type

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEIFcxgPYgApxRwC2yA3gFDLLYBGAVgNIQCeAXMgM5hSgDmAbipcwLADYQO3XiEHCIANwjgpPfkIC+FCqEixEKAMoQwxiQjDBcBIqUrVOEc5dycOGLNcIkA2gF1NbV1oeCRkABUIAA9TEzMICysQcmFHZyS3cmQxOFonVRk+ZA1-QIpogAdsKDBkYP0wgDF0MTFjWPTcFOoK72IOdvjEr1tkADII6NiOhJcQCi0KBFda6JIKiWbWwadZpI4ttrjd4eSAXm7kXtsOe2ouE7nMn2F7y7fqOiZWDgByX4ANK8PtxxJJkL8ACYQeAtMAABkBwLeimUYD+SI+9xyeTEfwA8hU5sgAIy-ZHFIFYu5Yr7MdgQzFYkRgv7Q2FiBFMrGolSMqnMnH5CGE4lkilaLEAeilyEAN6OABjrAAujyEAKs3IQBznYABceQgAJBwC7C8hALargEqu5CAFNnAAA1yEtgFKm4F+YRaDRCcpRdabFpHGanAB01xIvrSe1cvpg1QAoogABYACgUcDE6BQZwAfMgE0mIL6hWIAJRAA

### 💻 Code

```ts
interface ButtonParam {
  objKey: string;
  style: string;
  event: string;
}

interface SetSelectionParam {
  selections: ButtonParam[];
}

interface TextSetSelection {
  selections: { label: string }[];
}

export interface FullSetSelection {
  param: SetSelectionParam & TextSetSelection
}

const exampleFullSetSelection: FullSetSelection = {
  param: {
    selections: [
      {
        objKey: '',
        style: 'default0',
        event: '',
        label: 'Option 1'
      },
      {
        objKey: '',
        style: 'default0',
        event: '',
        label: 'Option 1'
      }
    ]
  }
};

exampleFullSetSelection.param.selections.forEach(value => value.label)
```

### 🙁 Actual behavior

exampleFullSetSelection.param.selections.forEach(value => value.label)

in here, it can not access value.label.

### 🙂 Expected behavior

exampleFullSetSelection.param.selections.forEach(value => value.label)

in here, it can access value.label.

**Comment by jcalz** [comment] 2023-12-14 03:46
Duplicate of #41874

**Closed** 2023-12-17 01:31 UTC
Labels: Duplicate
