### ISSUE TITLE
Type guards fail in `switch (true)` constructs.

### ISSUE THREAD

**Issue by sccolbert** [Microsoft/TypeScript#16887] opened 2017-07-02 03:14 UTC
Sometimes it's nice to use `switch (true)` along with boolean expression `case` clauses to make code cleaner than a bunch of `if/else` statements. Unfortunately, type guards do not work here:

**TypeScript Version:**  2.3.1

**Code**

```ts
interface Square {
  type: 'square';
  size: number;
}

interface Rectangle {
  type: 'rectangle';
  width: number;
  height: number;
}

type Shape = Square | Rectangle;

function isSquare(shape: Shape): shape is Square {
  return shape.type === 'square';
}

function isRectangle(shape: Shape): shape is Rectangle {
  return shape.type === 'rectangle';
}


let shape: Shape;

switch (true) {
  case shape.type === 'square':
    shape.size;  // fail
    break;
  case shape.type === 'rectangle':
    shape.width; // fail
    break;
}


switch (true) {
  case isSquare(shape):
    shape.size;  // fail
    break;
  case isRectangle(shape):
    shape.width; // fail
    break;
}


switch (shape.type) {
  case 'square':
    shape.size;  // okay
    break;
  case 'rectangle':
    shape.width; // okay
    break;
}


if (isSquare(shape)) {
  shape.size;  // okay
}

if (isRectangle(shape)) {
  shape.width;  // okay
  shape.height; // okay
}

```

**Expected behavior:**

All forms should compile.

**Actual behavior:**

The `switch (true)` forms do not compile.

**Comment by yortus** [comment] 2017-07-02 10:02
Duplicate of #8934

**Closed** 2017-08-05 05:45 UTC
Labels: Duplicate
