### ISSUE TITLE
[Help wanted] Broken Typescript resolving(TS 2307) when import from 'node_modules' directly with PNPM

### ISSUE THREAD

**Issue by zheeeng** [microsoft/TypeScript#46423] opened 2021-10-19 01:46 UTC
# Bug Report

### 🔎 Search Terms

pnpm, node_modules

### 🕗 Version & Regression Information

It's something about module resolving. I tested in the local and remote sandbox with the latest typescript.

#### Video

https://user-images.githubusercontent.com/1303154/138014608-e9f1e289-3361-41d8-a132-fe52d31dd4c3.mov

#### Repro

Look at example project: https://aquamarine-ant-l2yzybvg.ws-us17.gitpod.io

It's a typescript project.

I'm importing { Menu } from 'node_modules' directly, and Menu imports dependency rc-menu.

Caused by the rc-menu can't be resolved, the onClick does not exist on type MenuProps.

I tried `yarn` and `npm`, they both work fine.

![image](https://user-images.githubusercontent.com/1303154/137830085-79a53807-613d-4c72-9664-fb7216a23f10.png)

Moreover, please note the comment // import 'antd', once I removed the comment slash, all types work correctly. Coz that It's maybe  something resolving problem-related to typescript

### Yet another repo for reproducing the issue:

**https://github.com/zheeeng/test-pkgs-baz**

Foo package:

```ts
export type Foo = {
    method: () => string,
    str: string,
    num: number,
}

export const foo: Foo = {
    method () { return 'foo' },
    str: 'foo',
    num: 42,
}
```

Bar package:

```ts
import type { Foo } from 'test-pkgs-foo'

export interface Bar extends Foo {
    nil: null
}

export const bar: Bar = {
    method: () => 'bar',
    str: 'bar',
    num: 41,
    nil: null,
}
```

Baz package:

```ts
// please toggle this comment:
// import 'test-pkgs-bar'

import { Bar } from './node_modules/test-pkgs-bar'

const bar: Bar = {
    nil: null,
}
````

### 💻 Code

```ts
import * as React from 'react'
// import 'antd'
import { Menu } from '../node_modules/antd'

const i = (
    <Menu onClick={console.log} />
)
```

toggle the comment the resolving has different resolving results.

### 🙁 Actual behavior

`Cannot find module 'rc-menu' or its corresponding type declarations.ts(2307)`

### 🙂 Expected behavior

type resolves correctly.

### Additional information:
node -v prints: v16.11.0

**Comment by andrewbranch** [comment] 2022-02-08 22:05
Duplicate of #46607

**Closed by andrewbranch** 2022-02-08 22:05 UTC
Labels: Needs Investigation
