### ISSUE TITLE
Changes to compileOnSave in tsconfig.json not honnerd untill VS is restarted

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#10511] opened 2016-08-23 20:41 UTC
Here are the steps:

- Create new project, verify Compile on Save works
- Add tsconfig, set `"compileOnSave": true` in tsconfig.json
- Compile on Save does not work
- Restart VS, it works.

**Comment by paulvanbrenk** [comment] 2016-08-23 20:43
Duplicate of #9593

**Closed by paulvanbrenk** 2016-08-23 20:43 UTC
Labels: Bug, Duplicate
