### ISSUE TITLE
Reference type related derivation problems

### ISSUE THREAD

**Issue by Topthinking** [microsoft/TypeScript#43685] opened 2021-04-15 07:45 UTC
![image](https://user-images.githubusercontent.com/13382821/114832299-ec810880-9e00-11eb-83a7-00c5533a8658.png)

## **`Why was the m field not derived when it was used`**

![image](https://user-images.githubusercontent.com/13382821/114832837-8779e280-9e01-11eb-9d96-f735a5d299c9.png)

**Comment by Topthinking** [comment] 2021-04-15 07:49
![image](https://user-images.githubusercontent.com/13382821/114833369-1555cd80-9e02-11eb-8afb-b746314721d5.png)

**Comment by MartinJohns** [comment] 2021-04-15 07:53
Duplicate of #42257 and many others.

You forgot to fill out the issue template.

**Closed** 2021-04-18 18:00 UTC
Labels: Duplicate
