### ISSUE TITLE
Function parameter default values must not refer their own local scope (es spec violation)

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#18378] opened 2017-09-11 07:09 UTC
Babel works correctly.

**TypeScript Version:**  master

**Code**

```ts
f();

function f(o = {g}) {
  return console.log(o.g());

  function g() {
    return 1;
  }
}

function g() {
  return 0;
}
```

**Expected behavior:**

```
$ node built/local/tsc.js index.ts && node index.js
0
$ node index.ts
0
```

**Actual behavior:**

```
$ node built/local/tsc.js index.ts && node index.js
1
$ node index.ts
0
```

**Comment by falsandtru** [comment] 2017-09-11 07:15
https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=GYCglA3AUFwK4DsDGAXAlgewQAlB7AvNgN4DmAvmCVNtgE4CmKcdOSWAzhgDYMB03DKRAY-wsJBi14ydFmzjqtWo2atsARmi1yUXbESpMORcRr0mLHAAZo5IA&debug=false&circleciRepo=&evaluate=true&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0

**Comment by mhegazy** [comment] 2017-09-11 16:26
Duplicate of https://github.com/Microsoft/TypeScript/issues/2584

**Closed** 2017-09-11 22:25 UTC
Labels: Duplicate
