### ISSUE TITLE
Too difficult to augment values which do not export their type

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#12074] opened 2016-11-06 23:41 UTC
Let's take this file (`react-router/lib/Route.d.ts`):

```ts
import * as React from 'react';
import Router from './Router';
import { Location } from 'history';

declare const self: self.Route;
type self = self.Route;

declare namespace self {
    interface RouteProps extends React.Props<Route> {
        path?: Router.RoutePattern;
        // ...
    }
    interface Route extends React.ComponentClass<RouteProps> {}
    interface RouteElement extends React.ReactElement<RouteProps> {}
}

export default self;
```

Let's say that [I wanted to write a module augmentation](http://stackoverflow.com/questions/40450283/creating-new-type-definitions-for-react-router-relay) for this.

There is no way (that I can think of) to reopen the namespace or any of the interfaces.

1. Local namespace/interface merging is not allowed with imports.
2. There is no way I can reopen a default export in a module augmentation.

As a result, I have to rewrite `react-router` so that I can make it augmentable because the original author did not think far ahead enough to support it.

**Comment by DanielRosenwasser** [comment] 2016-11-06 23:57
I should actually take back what I said in part - it is not so much that the author didn't think far enough ahead to support augmentations, but rather, that the module is available using a default export. The author wanted to export all of the types through the default export as well, but as mentioned above, there is no way to reopen default exports.

**Comment by mhegazy** [comment] 2017-03-09 19:49
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/14080

**Closed** 2017-04-19 18:55 UTC
Labels: Duplicate
