### ISSUE TITLE
Suppress only specified errors using '// @ts-ignore' comments.

### ISSUE THREAD

**Issue by Busyrev** [Microsoft/TypeScript#21197] opened 2018-01-16 13:14 UTC
In some special cases it's ok to ignore error using ['// @ts-ignore' comment](https://github.com/Microsoft/TypeScript/pull/18457#issuecomment-339097980). But, good practice is ignore only pecific error, not all possible errors. There is an issue with way, how to specify error, there is no public error codes, messages are localized. We have no way to point what diagnostic we want to ignore. But we have [diagnosticMessages.json](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/diagnosticMessages.json) that contains codes.
My proposal is: Include error code to diagnostic message, and then allow to specify what error compiler should ignore, may be like this 
`// @ts-ignore:1048`
May be it would be better to create human readable identifiers for all error and use them instead number codes.

**Comment by andy-ms** [comment] 2018-01-16 15:50
Duplicate of #19139

**Closed** 2018-01-30 19:54 UTC
Labels: Duplicate

**Comment by Busyrev** [comment] 2018-02-03 18:17
I think it is not a duplicate of #19139. My idea is specify error number in //@ts-ignore comment ingnore only errors you want to, not all possible
