### ISSUE TITLE
Format code doesn't work!

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#12178] opened 2016-11-11 17:12 UTC
_From @fbenvegna on November 9, 2016 15:32_

- VSCode Version: 1.7.1
- OS Version: Windows 7 Professional SP1

Steps to Reproduce:
I have a Node.js/Express/ExtJS large project with 19000 files and 3300 directory
1. create a new file on routes (or other) directory
2. insert few lines of unformatted code
3. format the code.... it's OK!
4. close and reopen VSCode
5. reopen the file
6. apply some change to the code
7. format the code.....  fails!!!!

No problem with vscode 1.6.
Now, it's impossible to format any existing file on project!

_Copied from original issue: Microsoft/vscode#15243_

**Comment by waderyan** [comment] 2016-11-11 17:12
_From @aeschli on November 9, 2016 19:7_

What's the language of the file that you format? Does it matter what's the content of the file?

Also, can you list the extensions that you are using and also maybe try to run code without extensions?
Use  `code --disable-extensions` for that

**Comment by waderyan** [comment] 2016-11-11 17:12
_From @fbenvegna on November 9, 2016 20:6_

The language is JavaScript. It's a Node.JS / Express project.

**Comment by waderyan** [comment] 2016-11-11 17:12
_From @fbenvegna on November 10, 2016 16:0_

I tried `code --disable-extensions` but nothing is changed!

**Comment by waderyan** [comment] 2016-11-11 17:12
_From @fbenvegna on November 10, 2016 16:5_

I downgraded VSCode from 1.7.1 to 1.6.1 and formatting is OK!!!!
The problem is only on 1.7.X.
Please, correct the bug!

**Comment by waderyan** [comment] 2016-11-11 17:12
_From @fbenvegna on November 11, 2016 10:21_

After many trials, I found a solution to the problem... **jsconfig.json**.
If you delete the file... code formatting it's ok!
But I need **jsconfig.json**! 
In my case, I have to add the ExtJS directory ('public' on my project) to "exclude" section
`	
"exclude": [
		"node_modules",
		"public"
	]
`
Now, code formatting on 1.7.1 is OK!
I think that problem is related to Intellisense because another solution is to delete the ExtJS sources subdirectory inside 'public' and all is working.

**Comment by vladima** [comment] 2016-11-11 19:43
looks like a dupe of https://github.com/Microsoft/TypeScript/issues/11888

**Closed** 2016-11-11 21:39 UTC
Labels: Duplicate, VS Code Tracked
