### ISSUE TITLE
Type predicate can sometimes result in different type than type discrimination

### ISSUE THREAD

**Issue by aslilac** [microsoft/TypeScript#46909] opened 2021-11-23 16:50 UTC
# Bug Report

### 🔎 Search Terms

predicate, discrimination

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 4.5.2. Test in 4.0 and nightly as well.

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.5.2#code/GYVwdgxgLglg9mABFApgZygCgB4C5HgDWYcA7mAJSIDeAUAJAzCKZQCeADinM9ogLyDEAIgwAnGGADmwxAB85iPoP6IADFTr162Bo2Y4BQ4QAsUAG3NxZCpUdUaaenXoC+DdwyYsIZiIQBGHApNPV1tb0xfFH8AJmDQ7Rdtd3p3T1BIWAREaP8gvAIwYjJKfD4YNBZxSSl5dUSxFCgQMSR2Lh47FREa6RtFZSE1AG5aDPBoeCQ8wnjCohJyCnLESpZTCysbBqd6Jpa27uMzS2t5Qft1MdcgA)

### 💻 Code

```ts
function test(x: unknown) {
	if (typeof x === "string" || x === 0) {
		x
		if (x === "hello" || x === 0) {
			x
		}
	}

	if (check1(x)) {
		x
		if (check2(x)) {
			x
		}
	}
}

function check1(x: unknown): x is (string | 0) {
	return typeof x === "string" || x === 0;
}

function check2(x: unknown): x is ("hello" | 0) {
	return x === "hello" || x === 0;
}
```

### 🙁 Actual behavior

In the first set of nested scopes, `typeof x` is narrowed to `string | 0` by the first `if`, and then `"hello" | 0` by the second if. This behavior is correct.
In the second set of nested scopes, `typeof x` is narrowed to `string | 0` by the first `if`, but is narrowed to `0` by the second if. 

### 🙂 Expected behavior

`"hello"` is a valid part of the subset of `string`, and should be included in the union type. The types derived from these two methods should be identical.

**Comment by MartinJohns** [comment] 2021-11-23 17:33
I believe this to be a duplicate of #31156.

**Comment by RyanCavanaugh** [comment] 2021-11-23 21:01
Behavior dates back to at least 3.3... I'm surprised this hasn't been noticed before (I suppose a union UDTG is weirdish).

**Closed** 2022-07-16 00:01 UTC
Labels: Bug, Help Wanted
