### ISSUE TITLE
Function typechecking doesn't work for methods.

### ISSUE THREAD

**Issue by kwasimensah** [microsoft/TypeScript#35930] opened 2019-12-31 04:35 UTC
**Search Terms:**
method typechecking

**Code**

```ts
interface DoSomething {
    (): number;
}

function doubleNumber(generator: DoSomething) {
    return generator() * 2;
}

function return42() {
    return 42;
}

console.log(doubleNumber(return42));

class ArbitraryNumber {
    constructor(private readonly _seed: number) { }

    seed(): number { return this._seed;}
}

const test = new ArbitraryNumber(5);
// this line will cause an error because *this* won't be defined inside of seed()
console.log(doubleNumber(test.seed));
```

**Expected behavior:**

The typechecker complains because the implicit this isn't supplied when calling test.seed/i.e. you're forced to bind with an actual object.

**Actual behavior:**

This is a runtime error.

**Playground Link:** ! A link to a  Playground "Share" link which demonstrates  behavior 

https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgCIHsDK6C2EwAWoA5sgN4CwAUMrcgBQCUAXMiAK44BG0A3NQF9q1GOxAIwwdCGQATdOy4AbCADlOPKPWIQQ0OGHRRWGbHkIlG5anWRR87KDJ16oBo02QAqZACZ+VEJUImISUjL2YI4gACy+npQ0dJHRyHEBQdQI0gDO6CoAdEroxPTyiirq3ND0KU5xjIwBWUpwOTnIAIJQXMBgblAAnlWa1km02SA5-ewSHgAOUMAAbgYo9nDyIEqDyAD6ORAQsqwc1VBWZMiZ48iHx0ynGtDkdg5OyBY5BQdHsrxBG6TaafCAggC8bAgAHcuj0+gNhs8tABWJpZXL5CBFEplBTKNTI+iQaYFe6yRrNYJUIA

**Related Issues:** ! Did  find other bugs that looked similar?

**Comment by DanielRosenwasser** [comment] 2019-12-31 21:07
Looks like a duplicate of #7968.

**Closed** 2020-01-09 18:00 UTC
Labels: Duplicate
