### ISSUE TITLE
Unexpected type narrowing for variable (outer scope) assignment in function

### ISSUE THREAD

**Issue by cschuller** [microsoft/TypeScript#36403] opened 2020-01-24 15:46 UTC
**TypeScript Version:**  3.8.0-dev20200122

**Search Terms:**
property does not exist on type never

**Code**

```ts
class Person {
    name: string;
    constructor(name: string) {
        this.name = name;
    }
}
 
let foo: Person | null = null;

function initialize() {
    foo = new Person('foo');
}

initialize();

if (foo) {
    console.log(foo.name); // Property 'name' does not exist on type 'never'.
}
```

**Expected behavior:**
No compile error.

**Actual behavior:**
Code throws a `Property 'name' does not exist on type 'never'.`

**Playground Link:** 
[playground example](https://www.typescriptlang.org/play/index.html?ts=3.8.0-dev.20200122&ssl=18&ssc=2&pln=1&pc=1#code/MYGwhgzhAEAKCmAnCB7AdtA3gKGn6aYAtvAFzQQAuiAlmgOYDcu+w6ViArsJSogBSES5DnXoBKLC3z5KACxoQAdEPjQAvAWLxmMgL7YD0bCHiVoAMxQpyCZOmgAfApxAgNLt82wXOaHjQOdDSUNGAgNABe8PySODJWKB5o8ADucEioaPwA5Ik54swG2MGh4VExhdglFtD8iXHS0GxoqKZKICj09dYq2oXQAPSDcIgoAA5IlACe0DmqOdAAJijwMGgo5vAAHormDjOTcykAbkg5SobYQA)

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/35644
Labelled as fix available for 3.8.1, but does not work for 3.8.0-dev20200122

**Comment by jcalz** [comment] 2020-01-24 15:50
duplicate of #9998; the compiler has no idea that `initialize()` has an implication for the type of `foo`.

**Comment by cschuller** [comment] 2020-01-24 16:17
@jcalz Thanks - Quite a long discussion, good arguments on both sides. I am more in favor of turning the optimistic prediction off (or make it configurable or warning level), but at least we could re-phrase the error message.

**Closed** 2020-01-24 17:08 UTC
Labels: Duplicate
