### ISSUE TITLE
infer type fail when type is ([k1, t1] | [k2, t2])[] like

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#36374] opened 2020-01-23 16:45 UTC
**TypeScript Version:**  Version 3.8.0-dev.20200123

**Search Terms:**

**Code**

```ts
export type IEntrie = (
	['a', string]
	| ['b', string]
	| ['c', string]
	| ['d', string]
	| ['e', number]
	)

export default (Object.entries({}) as IEntrie[])
.map(([siteID, table]) => {

	if (siteID === 'e')
	{

		console.dir(siteID) // infer should is 'e
		console.dir(table + 0) // infer should is number

		return {
			siteID,
			table,
		}
	}
	else
	{
		console.dir(siteID) // infer should is a b c d
		console.dir(table) // infer should is string

		return {
			siteID,
			table,
		}
	}
})
```

**Expected behavior:**

when siteID is `e`, `table` should is `number`, not `string | number`
when siteID is not `e`, `table` should is `string`, not `string | number`

```ts
export declare type IEntrie = (['a', string] | ['b', string] | ['c', string] | ['d', string] | ['e', number]);
declare const _default: ({
    siteID: "e";
    table: number;
} | {
    siteID: "a" | "b" | "c" | "d";
    table: string;
})[];
export default _default;
```

**Actual behavior:**

> Error:(20, 15) TS2365: Operator '+' cannot be applied to types 'string | number' and 'number'.

![image](https://user-images.githubusercontent.com/167966/73004503-63b82e80-3e42-11ea-86f4-b5b1c40cebe7.png)

```ts
export declare type IEntrie = (['a', string] | ['b', string] | ['c', string] | ['d', string] | ['e', number]);
declare const _default: ({
    siteID: "e";
    table: string | number;
} | {
    siteID: "a" | "b" | "c" | "d";
    table: string | number;
})[];
export default _default;
```

**Playground Link:** 

**Related Issues:**

**Comment by nmain100** [comment] 2020-01-23 17:01
Duplicate of https://github.com/microsoft/TypeScript/issues/32639 which is a duplicate of https://github.com/microsoft/TypeScript/issues/12184.  My search terms were "dependent narrowing".

Everything works as expected if you don't destructure into `[siteID, table]`, but once you do you have two separate variables and Typescript doesn't track the relation between narrowing one causing a narrowing of the other.

**Closed** 2020-01-23 17:27 UTC
