### ISSUE TITLE
ES6 Bare imports generates invalid Javascript

### ISSUE THREAD

**Issue by joaompneves** [Microsoft/TypeScript#2896] opened 2015-04-23 21:57 UTC
The following typescript (using the new module system syntax)

    import "foo";

generates the following invalid javascript:

    define(["require", "exports", "foo"], function (require, exports, )

**Comment by mhegazy** [comment] 2015-04-23 21:59
looks like a duplicate of #2801. should be fixed in the latest in master/release-1.5

**Closed** 2015-08-11 00:02 UTC
Labels: Duplicate
