### ISSUE TITLE
The SSL cert of typescriptlang.org is expired

### ISSUE THREAD

**Issue by tsekityam** [Microsoft/TypeScript#22680] opened 2018-03-18 10:58 UTC
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 
HTTPS, SSL

**Description**

I got the following error when I tried to open https://typescriptlang.org with Firefox
> www.typescriptlang.org uses an invalid security certificate. The certificate expired on March 17, 2018, 5:48 AM. The current time is March 18, 2018, 6:51 PM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Expected behavior:**
Can open https://typescriptlang.org with Firefox 58

**Actual behavior:**
Can't open https://typescriptlang.org with Firefox 58

**See also**
https://www.ssllabs.com/ssltest/analyze.html?d=www.typescriptlang.org&latest

**Comment by j-oliveras** [comment] 2018-03-18 13:18
Duplicate of #22663.

This is the fifth issue about this.

**Comment by Blair2004** [comment] 2018-03-18 18:10
I thought there was a problem with my browser :/

**Closed** 2018-03-18 23:06 UTC
Labels: Duplicate
