### ISSUE TITLE
No error for callback returned value wrong field

### ISSUE THREAD

**Issue by artaommahe** [Microsoft/TypeScript#21869] opened 2018-02-11 11:55 UTC
**TypeScript Version:**  2.7.1

**Code**
```ts
interface IState {
  smth: string;
}

let state: IState = { smth: '' };

function update(callback: (state: IState) => IState): void {
  state = callback(state);
}

// no error here for wrong field
update(state => ({ ...state, smth2: '' }));
// and here too
update(state => ({ smth: '', smth2: '' }));

// this will mark an error
update(state => {
  state = { ...state, smth2: '' };
  return state;
});
```

**Expected behavior:**
Mark an error for wrong field

**Actual behavior:**
No error for wrong field

**Playground Link:**
https://stackblitz.com/edit/typescript-callback-return-type-error?file=index.ts

**Comment by andy-ms** [comment] 2018-02-11 17:22
Duplicate of #12632.

**Closed** 2018-02-26 20:42 UTC
Labels: Duplicate
