### ISSUE TITLE
Conditional return types don't work

### ISSUE THREAD

**Issue by kwasimensah** [microsoft/TypeScript#46127] opened 2021-09-29 02:55 UTC
# Bug Report

### 🔎 Search Terms

conditional return type alias generics

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about conditional return types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210928#code/C4TwDgpgBAKhDOwA8MB8UC8soQB7AgDsATeKRAJwEtCBzKAfikIFcBbAIwgqgC4oOAe0EAbCAENCAbgBQMgGYtCAY2BVBhKPOEpUAClz8YASiMJkaAN4yoUKvL2hIg+VFyYMWAESUatL8bWtrYUEMAsFJoArLK2AL42UKHhkVDAFCwQsnFAA)

### 💻 Code

```ts
type Test<T> = T extends string ? number : boolean;

function foo<T>(x: T): Test<T>{
  if(typeof x === "string"){
    return 5;
  }
  return true;
}
```

### 🙁 Actual behavior

Both branches have different flavors of error 2322

### 🙂 Expected behavior

the typeof guard should have let Typescript know it was dealing with a string and should have now which branch of the conditional type it should be allowed to return. The same outside of the type guard since it returns and control flow analysis should have treated that like an implicit else.

**Comment by kwasimensah** [comment] 2021-09-29 03:05
What I'm really trying to do:

I'm trying to write a function that when giving a string returns Wrapped<string>

The closest I got this to working is with overloads but then I couldn't get it working with downstream functions even if they had overloads. https://www.typescriptlang.org/play?ts=4.4.3#code/JYOwLgpgTgZghgYwgAgOpTgB0xAJgHgBUA+ZAbwChlkoI5cB7EAGwE9kxWcAuZAIgDuGbHj4BuKjTqMW7AG5xmAVwi9CEgL4VtMJSARhgTZAiZzoYABQAPXgGcwUUAHMAlMl7osOAg6chnYgldfUNjUxBzKDAiYhtPYR9Y9wTvPFjgvQMjEBMzC3jkPQBrEAYBEBSikFLy3MpqamAYS04cBhhka2QAXj7+Pxc+VwbGsdowJSh6ttV+ITTcPgAaZAVlOesNCTGtcYhJ6a6KLR0ssNycKABbYDs7YHMAMXOc2MLBgOQAHzRE9JKZQqxCqXhEBEBdVIowmU1yESiVmsrk02jRQA

So I tried to be smart about doing the conditional in the return type and saw this bug.

**Comment by jcalz** [comment] 2021-09-29 03:08
duplicate of #33912

**Closed** 2021-10-04 18:00 UTC
Labels: Duplicate
