### ISSUE TITLE
Crash on import statement with empty file name 

### ISSUE THREAD

**Issue by Smesharikable** [microsoft/TypeScript#36899] opened 2020-02-20 16:30 UTC
**TypeScript Version:**  3.7.5, 3.8-Beta

**Search Terms:**
Crash, Cannot read property 'kind' of undefined

**Related Issues:**

**Code**
```ts
import {aaa} from ""
```

<details><summary><b>Output</b></summary>

```ts

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/#code/JYWwDg9gTgLgBAbwIYoL5wGZQiOAiPIA)

**Comment by a-tarasyuk** [comment] 2020-02-21 09:33
Based on the stack trace, the issue in https://github.com/microsoft/TypeScript/blob/cf24c4fdc064d1ba88eb939d601ffd824926ed52/src/services/textChanges.ts#L1281

It can be reproduced with the existing path too [Playground](https://www.typescriptlang.org/play/?ts=Nightly#code/JYWwDg9gTgLgBAbzgQ1XAvnAZlCI4BEAdAPRjIwAWBQA). _(put the cursor at the end of the path)_. I could reproduce this issue only in Monaco Editor, in the VSCode I could not reproduce. I tried to create the test to simulate the bug, however, steps that cause the issue in Monaco Editor works well in the test. Is there any way to simulate the behavior like in Monaco Editor?

cc @DanielRosenwasser @RyanCavanaugh  @elibarzilay

**Comment by elibarzilay** [comment] 2020-03-19 23:01
I couldn't come up with a test that triggers the bug, or debug on the playground webpage, so handing it over to @orta.

**Comment by orta** [comment] 2020-06-25 17:48
This is fixed in the new playgrounds, we'll see that in 4.0

**Closed by orta** 2020-06-25 17:48 UTC
Labels: Bug, Rescheduled
