### ISSUE TITLE
Type guards do not work on array access expressions

### ISSUE THREAD

**Issue by OleksandrNechai** [Microsoft/TypeScript#11483] opened 2016-10-10 09:09 UTC
**TypeScript Version:**  2.0.3

**Code**

``` ts
let list = [1, '2'];
for (let i = 0; i < list.length; i++) {
    const j = i;
    if (typeof list[j] === 'string') {
        console.log(list[j].charAt(0)); // Property 'charAt' does not exist on type 'string | number'
    }
}
```

**Expected behavior:**
Successful compilation, since the type of `list[j]` is made clear with type guard

**Actual behavior:** 
error TS2339: Property 'charAt' does not exist on type 'string | number'

**Comment by aluanhaddad** [comment] 2016-10-10 14:56
I'm not sure if this is intended to work, it would stand to reason since `j` is `const`. But in the meantime the following workaround will get the job done
```ts
for (let i of list) {
    if (typeof i === 'string') {
        console.log(i.charAt(0));
    }
}
```

**Comment by mhegazy** [comment] 2016-10-10 18:51
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/10530

**Comment by RyanCavanaugh** [comment] 2016-10-10 19:07
@mhegazy the sample doesn't compile under Nathan's PR

**Comment by mhegazy** [comment] 2016-10-10 20:15
well.. it did in a previous iteration. the result was all array indexes were narrowed adding high perf and memory pressure. the current iteration of the PR, only narrows strings, this seems to be less expensive. we can discuss a better implementation.

**Comment by RyanCavanaugh** [comment] 2016-10-31 22:15
Declined due to performance reasons. Since it should almost always be possible to write `const j = list[i]` instead, this shouldn't be too burdensome.

**Closed by RyanCavanaugh** 2016-10-31 22:15 UTC
Labels: Design Limitation
