### ISSUE TITLE
Insufficient type narrowing of object with a union property

### ISSUE THREAD

**Issue by KevinWuWon** [microsoft/TypeScript#33467] opened 2019-09-17 15:24 UTC
**TypeScript Version:**   typescript@3.7.0-dev.20190917 (typescript@next)

**Search Terms:** union property type narrowing

Note: this is two bugs in one but they look related.  "Issue 2" might actually be more damning.

## Issue 1

**Code**

```ts
// Compile with `tsc --strictNullChecks` maybe1.ts
type Base = { bar: number };
type MaybeFoo = Base & { foo: string | null };
type HasFoo = MaybeFoo & { foo: string };

export function useMaybeFoo(maybeFoo: MaybeFoo) {
  if (maybeFoo.foo !== null) {
    const hasFoo: HasFoo = maybeFoo;
  }
}
```

**Expected behavior:**
Should compile because the conditional should have narrowed the MaybeFoo to a HasFoo.

**Actual behavior:**
```
maybe1.ts:7:11 - error TS2322: Type 'MaybeFoo' is not assignable to type 'HasFoo'.
  Type 'MaybeFoo' is not assignable to type '{ foo: string; }'.
    Types of property 'foo' are incompatible.
      Type 'string | null' is not assignable to type 'string'.
        Type 'null' is not assignable to type 'string'.

7     const hasFoo: HasFoo = maybeFoo;
            ~~~~~~
```

**Playground Link:** [click](http://www.typescriptlang.org/play/#code/C4TwDgpgBAQghgZ2gXigbygIzgJwFxQB2ArgLaYQ5QC+A3AFCiRQCycIFAYgPbdSrwkUAGTooAM14EEwHAEtCAcygAfIsQA2GmgybQAEoh59UbDhGMixk7tNkLldevQgAPMNxzAJxQgGNgOW5CKGIkMy5eAApSdkjbVjiLXgBKdHooKDlxKBik4wA6GygAQmRUEi00tAzMqD9gmSgACyMpKEMES1RY82MGTOp6aiA)

**Related Issues:** had a quick search but couldn't anything

### Workaround

This code is exactly the same, but compiles
```ts
// Compile with `tsc --strictNullChecks` maybe2.ts
type Base = { bar: number };
type NoFoo = Base & { foo: null };
type HasFoo = Base & { foo: string };
type MaybeFoo = NoFoo | HasFoo;

export function useMaybeFoo(maybeFoo: MaybeFoo) {
  if (maybeFoo.foo !== null) {
    const hasFoo: HasFoo = maybeFoo;
  }
}
```

**Playground Link** [click](http://www.typescriptlang.org/play/#code/C4TwDgpgBAQghgZ2gXigbygIzgJwFxQB2ArgLaYQ5QC+A3AFCiRQByA9gGJttSrxJQAZOigAzbgRIAbKTQZNoACURcefRNGEZxbAgmA4AloQDmcxuGgBZOCAqrerTtygAfKMoSqG9CAA8wNhxgMWJCAGNgQzZCKGIkGzsIVQAKUlt7CShEzLYASnR6KChDUSg0jOTuADodKABCZFRpKQK0IuKocJj9KAALFSzPB1R0pO8O6nopoA)

## Issue 2

Now let's try using the same type definitions as maybe2.ts, but try creating a MaybeFoo:

```ts
// Compile with `tsc --strictNullChecks` maybe3.ts
type Base = { bar: number };
type NoFoo = Base & { foo: null };
type HasFoo = Base & { foo: string };
type MaybeFoo = NoFoo | HasFoo;

export function makeMaybeFoo(foo: string | null): void {
  const maybeFoo: MaybeFoo = {foo: foo, bar: 3};
}
```

**Expected behavior:**
Should compile.

**Actual behavior:**
```
maybe3.ts:7:9 - error TS2322: Type '{ foo: string | null; bar: number; }' is not assignable to type 'MaybeFoo'.
  Type '{ foo: string | null; bar: number; }' is not assignable to type 'HasFoo'.
    Type '{ foo: string | null; bar: number; }' is not assignable to type '{ foo: string; }'.
      Types of property 'foo' are incompatible.
        Type 'string | null' is not assignable to type 'string'.
          Type 'null' is not assignable to type 'string'.

7   const maybeFoo: MaybeFoo = {foo: foo, bar: 3};
```

**Playground Link** [click](http://www.typescriptlang.org/play/#code/C4TwDgpgBAQghgZ2gXigbygIzgJwFxQB2ArgLaYQ5QC+A3AFCiRQByA9gGJttSrxJQAZOigAzbgRIAbKTQZNoACURcefRNGEZxbAgmA4AloQDmcxuGgBZOCAqrerTtygAfKMoSqG9CAA8wNhxgMWJCAGNgQzZCKFI4AGsIGzsIVQAKHT0DYzN3aSkASgIANzZDABN0eigocJj9ONt7CSgUlrV0LLFuABosXAIAZjp6aiA)

### Issue 2 Workaround
Changing back to the original type definitions fixes it:
```ts
// Compile with `tsc --strictNullChecks` maybe4.ts
type Base = { bar: number };
type MaybeFoo = Base & { foo: string | null };
type HasFoo = MaybeFoo & { foo: string };

export function makeMaybeFoo(foo: string | null): void {
  const maybeFoo: MaybeFoo = {foo: foo, bar: 3};
}
```

**Playground Link:** [click](http://www.typescriptlang.org/play/#code/C4TwDgpgBAQghgZ2gXigbygIzgJwFxQB2ArgLaYQ5QC+A3AFCiRQCycIFAYgPbdSrwkUAGTooAM14EEwHAEtCAcygAfIsQA2GmgybQAEoh59UbDhGMixk7tNkLldevQgAPMNxzAJxQgGNgOW5CKFI4AGsIMy5eAAobO3klVXUtAEoCADduOQATdHooKD9gmVD2GNtWCotefnQEiV4AGixcAgBmJ2ogA)

**Comment by jack-williams** [comment] 2019-09-17 16:22
Issue 1 is a duplicate of #30506.
Issue 2 is a duplicate of #33243, I think.

**Comment by KevinWuWon** [comment] 2019-09-17 17:05
> Issue 1 is a duplicate of #30506

Yup.

> Issue 2 is a duplicate of #33243, I think.

Yeah, seems related or the same.  The workaround `Expand` workaround it describes works for my case.

Thanks!  Feel free to dedupe, although I think my explanation of Issue 2 is more minimal than #33243

**Comment by AnyhowStep** [comment] 2019-09-17 17:09
I will always be against having this narrowing implemented because of,

https://github.com/microsoft/TypeScript/issues/33205#issuecomment-527313227

**Comment by AnyhowStep** [comment] 2019-09-17 17:12
Your second example (alleged workaround) is saying a **very different** thing from the first example

**Comment by AnyhowStep** [comment] 2019-09-17 17:14
```ts
type MaybeFoo = NoFoo | HasFoo;
```

And

```ts
type MaybeFoo = Base & { foo: string | null };
```

**Are not** the same type and **should not** be treated the same

**Comment by KevinWuWon** [comment] 2019-09-17 19:20
Great point.  So you're saying they're not equivalent because you can reassign foo.

Would the types be equivalent if all the properties were readonly?  Sprinkling readonly everywhere doesn't make any of the errors go away.

**Comment by KevinWuWon** [comment] 2019-09-17 19:33
Ah, I just read the discussion on #33205 where you covered why readonly doesn't change anything (because it's not absolute).  I agree now that Issue 1 is working as intended.

What do you think about Issue 2 though?

**Comment by AnyhowStep** [comment] 2019-09-17 19:37
For issue 2, it makes sense that the assignment should be sound.

It's an object literal that is not referenced elsewhere.
I'm not sure if it'll be marked as a duplicate of something else or "design limitation", though.

**Comment by jack-williams** [comment] 2019-09-17 19:47
I’m pretty sure issue 2 is a bug as per my first comment. If you remove the intersections and just use a union of object literals it works

**Comment by AnyhowStep** [comment] 2019-09-17 19:57
Ah. It wasn't obvious to me the issues were indeed related because I was stuck on the fresh object literal part.

I didn't try to remove the intersection =x

**Closed** 2019-09-20 18:00 UTC
Labels: Duplicate
