### ISSUE TITLE
Default parameters create incorrect Function.length

### ISSUE THREAD

**Issue by planttheidea** [Microsoft/TypeScript#30672] opened 2019-03-31 13:57 UTC
**TypeScript Version:**  3.4.1

**Search Terms:** default parameters, function.length

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

function foo(bar: string, baz: string = 'default') {}

console.log(foo.length);
```

**Expected behavior:**

Length is `1`, which [aligns with spec behavior](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length#Examples).

**Actual behavior:**

Length is `2`. This is because the transformation produces this code:

```javascript
function foo(bar, baz) {
    if (baz === void 0) { baz = 'baz'; }
}
```

`baz` is an explicitly-defined argument with no default, therefore it counts to the total. The way `babel` handles it is to take the arguments starting from the first default parameter and assign variables based on that:

```javascript
function foo(bar) {
  const baz = arguments[1] !== void 0 ? arguments[1] : 'baz';
}
```

This maintains spec compliance.

**Playground Link:** 

[Simple playground example](https://www.typescriptlang.org/play/#src=function%20foo(bar%2C%20baz%20%3D%20'baz')%20%7B%20%7D%0D%0A%0D%0Aconsole.log(foo.length)%3B%20%2F%2F%202)

**Related Issues:**

**Comment by dragomirtitian** [comment] 2019-03-31 14:22
Isn't this a duplicate of https://github.com/Microsoft/TypeScript/issues/23251. Title is a bit misleading but the issue seems the same.

**Comment by planttheidea** [comment] 2019-03-31 14:28
Ah yes, it appears to be a duplicate of that issue. Closing as such.

**Closed** 2019-03-31 14:28 UTC
