### ISSUE TITLE
"use strict" and source map are emitted to json files that are imported as a module

### ISSUE THREAD

**Issue by marcelh-gh** [Microsoft/TypeScript#24733] opened 2018-06-06 22:07 UTC
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** json use strict

the "use strict" and the source map in the emitted json cause errors during runtime....

**Comment by mhegazy** [comment] 2018-06-06 22:11
Duplicate of https://github.com/Microsoft/TypeScript/issues/24514.

Fix should be in `typescript@next` today, and in `typescript@2.9.2` next week.

**Comment by marcelh-gh** [comment] 2018-06-13 18:50
sorry, I did not see it fixed in typescript@next then and after just updating to 2.9.2 now it also still persists.

**Comment by mhegazy** [comment] 2018-06-13 19:58
i am unable to reproduce this locally on `typescript@2.9.2`. can you please share repro steps?

**Comment by marcelh-gh** [comment] 2018-06-13 20:04
hmm...
I just have something like `import setup from "./setup.json";` in a .ts file and the new compiler option `resolveJsonModule `set to true.
The resulting copy of the imported json file is emitted with the use strict and sourcemap - just as before.

in case there is a conflict with some other compiler option, here is my config:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "strict": true,
        "strictPropertyInitialization": false,
        "noUnusedParameters": true,
        "removeComments": false,
        "preserveConstEnums": true,
        "sourceMap": true,
        "target": "ES2017",
        "outDir": "./compiledJS",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "pretty": true,
        "plugins": [
            {
                "name": "tslint-language-service",
                "alwaysShowRuleFailuresAsWarnings": false,
                "ignoreDefinitionFiles": true,
                "supressWhileTypeErrorsPresent": false,
                "mockTypeScriptVersion": false
            }
        ]
    },
    "exclude": [
        "node_modules",
        "compiledJS",
        "playground",
        "documentation",
        "unitTesting",
        "gulpfile.js",
        "lib",
        "bundle.js",
        "**/*/*.quokka.ts"
    ]
}
```

**Comment by mhegazy** [comment] 2018-06-13 20:17
```sh

c:\test\24733>type tsconfig.json
{
    "compilerOptions": {
        "module": "commonjs",
        "strict": true,
        "strictPropertyInitialization": false,
        "noUnusedParameters": true,
        "removeComments": false,
        "preserveConstEnums": true,
        "sourceMap": true,
        "target": "ES2017",
        "outDir": "./compiledJS",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "pretty": true,
        "plugins": [
            {
                "name": "tslint-language-service",
                "alwaysShowRuleFailuresAsWarnings": false,
                "ignoreDefinitionFiles": true,
                "supressWhileTypeErrorsPresent": false,
                "mockTypeScriptVersion": false
            }
        ]
    },
    "exclude": [
        "node_modules",
        "compiledJS",
        "playground",
        "documentation",
        "unitTesting",
        "gulpfile.js",
        "lib",
        "bundle.js",
        "**/*/*.quokka.ts"
    ]
}

c:\test\24733>type a.ts
import x = require("./a.json")
x.n;
x.a

c:\test\24733>type a.json
{
    "a": 0,
    "n": "s",
}

c:\test\24733>tsc --v
Version 2.9.2

c:\test\24733>tsc

c:\test\24733>type .\compiledJS\a.json
{
    "a": 0,
    "n": "s"
}
```

**Comment by marcelh-gh** [comment] 2018-06-13 20:21
the only difference I see: you wrote ` import x = require("./a.json") ` where I did `import x from "./a.json";`
Everything works fine in my case too - besides the mentioned problem...

**Comment by marcelh-gh** [comment] 2018-06-13 20:29
nope. if I use the import from syntax it does not work for me. only with the import x=require....
strange....

**Comment by mhegazy** [comment] 2018-06-13 20:30
can you provide a repro project we can look at?

**Comment by marcelh-gh** [comment] 2018-06-13 20:41
i literally just used the same files as you in an empty project just now....

**Comment by mhegazy** [comment] 2018-06-13 20:47
are u sure you are using 2.9.2?

**Comment by marcelh-gh** [comment] 2018-06-13 20:47
yeah sure.... tsc --v ;-)

ok.. I did uninstall and reinstall typescript. now it works _regardless_ of the syntax.
actually I had a similar case happen long time ago when updating from TS 2.1...

sorry to have wasted your time! cheers, marcel

**Comment by marcelh-gh** [comment] 2018-06-13 20:50
I guess the issue can be closed. Thank you for your help!

**Closed** 2018-06-28 23:04 UTC
Labels: Duplicate

**Comment by AhmedMKamal** [comment] 2019-04-06 18:52
Why I'm facing this issue with `"typescript": "^3.4.1"`?!

**Comment by amitdahan** [comment] 2019-08-31 10:01
This is happening for me on `3.6.2` :(

**Comment by ealtunyay** [comment] 2020-02-11 14:29
ran into this using `"typescript": "^3.7.5"`. confirmed removing `isolatedModules` works

**Comment by joshkel** [comment] 2020-03-08 02:20
The `isolatedModules` workaround is apparently no longer needed in TypeScript 3.8.1 and above.
