### ISSUE TITLE
tsc.ps1 cannot be loaded. The file ... is not digitally signed

### ISSUE THREAD

**Issue by Houuse** [microsoft/TypeScript#35606] opened 2019-12-10 10:22 UTC
**TypeScript Version:**  typescript@3.7.3

**Search Terms:**
tsc.ps1 , tsc not digitaly signed
**Code**

```ts
after fresh install 

PS C:\Users\xxx> npm install -g typescript
C:\Users\xxx\AppData\Roaming\npm\tsc -> C:\Users\xxx\AppData\Roaming\npm\node_modules\typescript\bin\tsc
C:\Users\xxx\AppData\Roaming\npm\tsserver -> C:\Users\xxx\AppData\Roaming\npm\node_modules\typescript\bin\tsserver
+ typescript@3.7.3
updated 1 package in 0.93s

PS C:\Users\xxx> npm ls -g typescript
C:\Users\xxx\AppData\Roaming\npm
`-- typescript@3.7.3

PS C:\Users\xxx> tsc
tsc : File C:\Users\xxx\AppData\Roaming\npm\tsc.ps1 cannot be loaded. The file
C:\Users\xxx\AppData\Roaming\npm\tsc.ps1 is not digitally signed. You cannot run this script on the current system.
For more information about running scripts and setting execution policy, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ tsc
+ ~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

**Expected behavior:**
the typescript command isn't running at all due that tsc.ps1 isn't digitally signed, my pc execution policy 
``` 
PS C:\Users\xxx> Get-ExecutionPolicy
AllSigned
``` 
**Actual behavior:**
```ts
PS C:\Users\xxx> tsc
tsc : File C:\Users\xxx\AppData\Roaming\npm\tsc.ps1 cannot be loaded. The file
C:\Users\xxx\AppData\Roaming\npm\tsc.ps1 is not digitally signed. You cannot run this script on the current system.
For more information about running scripts and setting execution policy, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ tsc
+ ~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```
not related directly to ts , it's powershell script not signed issue

Edit , I know this isuue could be worked around by running following command in powershell

```
PS> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
```
am not security expert but assuming that the user don't have to change their pc execution policy in order to run typescript

**Comment by j-oliveras** [comment] 2019-12-10 10:40
I think that `tsc.ps1` is created by npm.

**Comment by fatcerberus** [comment] 2019-12-10 14:59
Duplicate of #35031

**Comment by fatcerberus** [comment] 2019-12-10 15:02
Relevant npm issue is https://github.com/npm/cli/issues/470.

**Closed** 2019-12-13 10:00 UTC
Labels: External

**Comment by pacis-25** [comment] 2022-08-01 04:15
just type tsc.cmd the ts filename

**Comment by sinaAtabaki** [comment] 2024-03-28 17:58
or just delete 
C:\Users\%USERNAME%\AppData\Roaming\npm\tsc.ps1
Now it will automatically load tsc.cmd when you type tsc in the command prompt/ powershell
