### ISSUE TITLE
Auto import does not pick up shortest path despite correct setting (JavaScript project with jsconfig.json)

### ISSUE THREAD

**Issue by rwalle** [microsoft/TypeScript#54324] opened 2023-05-19 14:11 UTC
# Bug Report

### 🔎 Search Terms

* shortest path
* auto import relative path
* auto import parent folder

I found a few closely related issues, and a few of them are marked as fixed. But since I am using a very recent version of the TS server, I was not expecting the issue to appear in my setup.

* https://github.com/microsoft/TypeScript/issues/25739
* https://github.com/microsoft/TypeScript/issues/26348
* https://github.com/microsoft/TypeScript/issues/42235
* https://github.com/microsoft/TypeScript/issues/51269

### 🕗 Version & Regression Information

TS Server 5.0.4 in VSCode 1.78.2

### ⏯ Playground Link

N/A -- project setup

### 💻 Code

Please use the code in this repository:

https://github.com/rwalle/ts-path-issue

### 🙁 Actual behavior

We have a monorepo setup without `node_modules`, and for simplicity, assume all packages live under the same folder. A team only develops one or a few packages, and they may have dependencies between them. In the example repository, `package1` depends on `package2`. `jsconfig.json` has been correctly setup.

After opening `setup1/package1` as the only workspace folder in VSCode, open `file1.js` and type `bar`, the import path is `../package2/file1`. The value for VSCode extension setting `javascript.preferences.importModuleSpecifier` is the default "shortest". If this is changed to "non-relative" or "project-relative", it gets worse -- it becomes `package1/../package2/file1`.

Alternatively, under "shortest" setting, move `file1.js` to a subfolder and try to import `bar`, you always see `package1/../package2/file1`.

<img width="779" alt="Screenshot 2023-05-19 094604" src="https://github.com/microsoft/TypeScript/assets/3648011/d3819a4e-8926-41c6-a2ad-d332c5120490">

<img width="656" alt="Screenshot 2023-05-19 094732" src="https://github.com/microsoft/TypeScript/assets/3648011/4b103394-933a-4a85-94d5-f61b64196f66">

However, if I manually type `import { bar } from 'p'`, it can find `package2`. Also go to definition works properly if you uncomment the import at the beginning of that file.

After opening `setup2` as the workspace folder in VSCode, type `bar`, import path is `package2/file1`. However we don't want to do that -- root folder is huge and nobody wants to have all folders and files from irrelevant packages visible in the workspace tree and potentially watched.

### 🙂 Expected behavior

For `setup1/package1`, TS Service correctly provides the shortest path `package2/file1`.

**Comment by andrewbranch** [comment] 2023-05-19 20:45
Looks like a duplicate of https://github.com/microsoft/TypeScript/issues/53369, which means it was fixed in https://github.com/microsoft/TypeScript/pull/53957. Please make sure to try out the [nightly TypeScript version](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) before you go through all the trouble of making a repro! Let me know if the nightly doesn’t solve your problem, but I’m going to go ahead and close because it looks identical.

**Comment by rwalle** [comment] 2023-05-19 21:40
> Looks like a duplicate of #53369, which means it was fixed in #53957. Please make sure to try out the [nightly TypeScript version](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) before you go through all the trouble of making a repro! Let me know if the nightly doesn’t solve your problem, but I’m going to go ahead and close because it looks identical.

I just installed typescript@next extension and still seeing the same thing with 5.2.0-dev.20230517, and I think I am using the correct version by checking the command and the TS Server log

![Screenshot 2023-05-19 173819](https://github.com/microsoft/TypeScript/assets/3648011/7ccb73f5-8b15-43c5-a6ce-b215e541ed8f)

Would you mind validating this?

**Comment by andrewbranch** [comment] 2023-05-19 22:44
I can’t repro anything like `package1/../package2/file1`, which I kind of got tunnel vision on in your initial description. I get `../package2/file1`. But you want `package2/file1`.

**Comment by rwalle** [comment] 2023-05-19 23:00
> I can’t repro anything like `package1/../package2/file1`, which I kind of got tunnel vision on in your initial description. I get `../package2/file1`. But you want `package2/file1`.

Correct, the behavior has changed but is still not what a user would expect.

**Comment by andrewbranch** [comment] 2023-05-19 23:07
My bad, I was skimming for the most horrifying parts of the actual behavior 😄

**Closed** 2023-07-03 22:02 UTC
Labels: Bug, Fix Available, Domain: Auto-import
