### ISSUE TITLE
null checks not working with `&&false`

### ISSUE THREAD

**Issue by whizsid** [microsoft/TypeScript#52530] opened 2023-01-31 13:43 UTC
# Bug Report
I have a project that enabled `allowUnreachableCode` option. I wanted to bypass a large condition. So I appended `&&false` at the end of the condition. But now I can not compile the project due to null check errors.

### 🔎 Search Terms

- null check false
- null check boolean
- null guard boolean

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?allowUnreachableCode=true#code/DYUwLgBAhgdgogDygWwA6gGpQE4EsoBGoAXBAM5h4wDmAPjAK7DAQC8EARABIjMD2EAOp9swACYcAUJNwAzABSxEKdCCx5CoAIStGzAGT7ZUYGRABKCAG9JEOxFCRYfMAAsQ2dfiIhSFKtRs0PBIaJg43qAA3JIAvkA)

### 💻 Code

```ts
let anExampleVariable: string|null = "Hello World"

if(anExampleVariable!=null&&false) {
    let anotherVariable: string = anExampleVariable;
    //   ^^^^^^^^^^^^^^^ Type 'string | null' is not assignable to type 'string'. Type 'null' is not assignable to type 'string'.
}
```

### 🙁 Actual behavior

Getting `Type 'string | null' is not assignable to type 'string'. Type 'null' is not assignable to type 'string'.` error.

### 🙂 Expected behavior

null checks should work as before.

**Comment by MartinJohns** [comment] 2023-01-31 13:50
Duplicate of #26914.

**Closed** 2023-02-04 18:00 UTC
Labels: Duplicate
