### ISSUE TITLE
Iterators: Narrowing the key does not narrow the value's type

### ISSUE THREAD

**Issue by MarcelWaldvogel** [microsoft/TypeScript#46718] opened 2021-11-07 15:22 UTC
# Suggestion

Narrowing the key obtained by iterating through `Object.entries()` does not narrow the type of the value associated with that key. I.e., inside `for (const [key, value] of Object.entries(x)) {…}`, `x[key]` can have its type narrowed by narrowing `key`, but the type of `value` will not be narrowed, even though the two are equivalent.

Right now, it feels somehow like a surprise that `x[key]` is not the same as `value` and `x[key]` needs to be evaluated again, even though that was the original goal of using the iterator.

## 🔍 Search Terms

object type narrowing key value

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

Example ([Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAGlC8UDeBDAXFAdgVwLYCMIAnAGinwxwOLIGMMBnYIgS0wHMBfAbgFgAoAQDNsmWsBYB7TFBYMA0hBAAVSQDk8hIgAoGjZm3YBKRrIZQA5CgtQAPpfw2kAqFCIRg2IjPPw-l6zt7Bj9EC0c+fk4BAQgADzBJImAoETEJaSgAE0lsfAAbCA1qIgZtOIwYEygAN0kWLOQXVKSobVppJigAbQBrMhqAXShJISgAeXwAKwhxADoITAMIMrijIyb+V1cWMe05RRV1TWJtXvXN7e2OzC6QBFqoACooACZuK4B6T8e5LEkUr1MJIAO4yYCScjQFBYE5EKCAGXJmlcbl0AF4POJ9YYvd5Qb5QLG9YZ-IGg8GQwhQGFULRQQCg5MioNEtsyBCygA)):
```ts
type X = {a: number, b: number, c: string};

function isKeyToNumber(s: string): s is 'a' | 'b' {
  return s === 'a' || s=== 'b';
}

export function doubleNumbers(x: X): void {
  for (const [k, v] of Object.entries(x)) {
    if (isKeyToNumber(k)) {
      const y = v * 2;    // v is not known to be a number ❌
      const z = x[k] * 2; // x[k] is known to be a number ✅
    }
  }
}
```

I ran into this issue while writing a sort function for a [TypeScript-first vCard parser](https://github.com/MarcelWaldvogel/vcard4-ts/blob/4b7a115596ff60e6aa88eeeb318a7f187a66b66a/src/sort.ts#L9), which I mis-attributed first.

## 💻 Use Cases

Enumerating through objects which have different types for their values based on the key, e.g.

* for databases
* JSON inputs
* vCards
* …

Right now,
* `for…of` cannot be reasonably used there, as the value's type is not narrowed, unless re-fetched from the record; and
* the developer is confused why the same data has two different types, depending on how they try to get at it.

**Comment by MartinJohns** [comment] 2021-11-07 15:35
This sounds like a duplicate of #35873.

**Comment by MarcelWaldvogel** [comment] 2021-11-07 21:52
I do not think it is a duplicate, but they probably should be implemented together, even though the key/value case might be easier to implement.

**Comment by MartinJohns** [comment] 2021-11-08 06:21
I don't see how this could be implemented without a very specific implementation just for `Object.entries()`, and that would be silly and counterproductive. But I'd love to learn and be corrected.

**Comment by andrewbranch** [comment] 2021-11-08 20:47
It is a duplicate of #35873—this is just a specific example where it would be nice to have #35873.

**Closed** 2021-11-11 18:00 UTC
Labels: Duplicate
