### ISSUE TITLE
NonNullable type syntax sugar

### ISSUE THREAD

**Issue by tanishqkancharla** [microsoft/TypeScript#50914] opened 2022-09-23 01:52 UTC
# Suggestion

Exclamation mark on types to assert NonNullable

```tsx

type CreateFileState = { dirPath: string } | undefined

declare const state: CreateFileState!
// Same as
declare const state: NonNullable<CreateFileState>
```

## 🔍 Search Terms

* NonNullable
* Assertion
* Exclamation mark
* Type

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

It’s pretty frequent that you want to use optional (`X | undefined`) types, but want to submit a non nullable of that type to a function. 

For example, imagine a FormState type that optionally has some state

```tsx
type CreateFileState = { dirPath: string, name: string } | undefined

type FormState = {
   // …
  createFile: CreateFileState
}

function submitForm(state: FormState) {
  // …
  if(state.createFile) {
    createFile(state.createFile)
  }
}

function createFile(state: CreateFileState!) {
  // …
}
```

Some other options:
* Use NonNullable instead. You can, this is just syntax sugar that lines up with typescript’s operator for asserting non-nullable values. NonNullable is annoying to write and spell.
* Let `createFile` take the nullable `CreateFileState` and just don’t do return early if its undefined. Semantically, it just doesn’t line up since `createFile` sounds like it definitively does something. You could change it to `maybeCreateFile`, but that’s more convoluted and your function names will be littered with `maybeX`...

## 💻 Use Cases

Syntax sugar for `NonNullable`

**Comment by jcalz** [comment] 2022-09-23 02:46
Duplicate of #46629

**Closed** 2022-09-23 05:26 UTC
