### ISSUE TITLE
Type signature overload is ignored in a place where it makes better sense.

### ISSUE THREAD

**Issue by ackvf** [Microsoft/TypeScript#30343] opened 2019-03-12 19:16 UTC
**TypeScript Version:**  3.4.0-dev.20190312

**Search Terms:**
ambient declaration overload

**Preface:**
I've been using these inline `console.debug(val) || val` statements for ages, but since recently, `void` cannot be tested for truthiness. My workaround for typescript projects is to include this in my `src/index.tsx` file, which works great
```ts
declare global {
  interface Console {
    debug(message?: any, ...optionalParams: any[]): false;
  }
}
```
> Enough said, my problem is that this technique does not work in **javascript projects**.

**Code:**

```ts
// src/global.d.ts

interface Console {
  abc(message?: any, ...optionalParams: any[]): false;
  debug(message?: any, ...optionalParams: any[]): false;
}

// later in src/**/SomeComponent.jsx

[1,2].map((v, ix) => console.debug('v', ix, v) || v) // void cannot be tested for truthiness
[1,2].map((v, ix) => console.abc('v', ix, v) || v) // no error
```

**Expected behavior:**
Expected is that the overload that returns false when used in place that test for truthiness is used.
When tested with `console.abc`, as per the interface, it is correctly picked up as returning false.

**Actual behavior:**

**error:** `An expression of type 'void' cannot be tested for truthiness ts(1345)`

Interestingly, after I have switched to ts@next and thus restarted the TS server, it first picks up my ambient declaration, so the code passes, but then it loads the `@types\node\globals.d.ts`

![global-declaration](https://user-images.githubusercontent.com/2313018/54227908-42d43c80-4501-11e9-9a5e-da5d7cf078ad.gif)

**Comment by j-oliveras** [comment] 2019-03-12 19:52
Duplicate of #28248 and #26262.

As a workaround, use comma operator:
```ts
[1,2].map((v, ix) => (console.debug('v', ix, v), v))
[1,2].map((v, ix) => (console.abc('v', ix, v), v))
```

**Comment by ackvf** [comment] 2019-03-13 08:16
Actually no, I am not upset about `void` not being tested for truthiness. I am upset about my overload not being applied. If my understanding of overloads is wrong, then I am sorry and I'll be happy to close this issue, but in that case an explanation would be helpful. Thanks in advance

**Closed** 2019-03-15 18:00 UTC
Labels: Duplicate

**Comment by ackvf** [comment] 2019-03-16 08:45
Wait @typescript-bot why u do dis?!
This issue isn't a duplicate and I **have made** a recent activity to express that.

**Comment by ackvf** [comment] 2019-03-16 08:46
@DanielRosenwasser please

**Comment by ackvf** [comment] 2019-03-16 15:05
@RyanCavanaugh I believe your bot is malfunctioning, please help!

**Comment by RyanCavanaugh** [comment] 2019-03-17 03:17
@ackvf this is a question about how to get your JS file configured to see the global declaration file. I'd recommend StackOverflow as a good support point. Thanks!

**Comment by ackvf** [comment] 2019-03-17 09:19
@RyanCavanaugh It does see the global declaration file as demonstrated in the gif, but it chose a different overload even though that overload gives an error.

**Comment by RyanCavanaugh** [comment] 2019-03-17 16:39
Overload resolution doesn't work by iterating each overload to see which makes your entire program not-an-error. The first matching overload is chosen; the return type isn't even part of this process.

**Comment by ackvf** [comment] 2019-03-17 16:44
Call signature is already considered, but if two return types share one call signature, maybe it should also consider a return type and the surrounding?
Or do you have another advice to force a particular overload or something else to make the compiler not complain?
