### ISSUE TITLE
why Map<string,boolean> reuturn type boolean | undefined

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/TypeScript#43860] opened 2021-04-28 12:42 UTC
# Bug Report

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFApgZygChgEwFwYBOMYA5gDQC2AhgA54CydAPESRQEZxwA2K1YAHwBKPF178wAbwCwAKESLEMYJhq0AdAAtqabDmHDZCpacIooIQknUbSF-cPmmAvvJdA)

### 💻 Code

```ts
function test(id:string,map:Map<string,boolean>):boolean{
    if(map.has(id)){
        return map.get(id)  // why the type here is boolean | undefined? 
    }
}


```

### 🙁 Actual behavior
Type 'boolean | undefined' is not assignable to type 'boolean'.

### 🙂 Expected behavior

because I've set the type is `Map<string,boolean>`, so it is boolean, no way undefined

**Comment by nmain** [comment] 2021-04-28 12:58
Duplicate of https://github.com/microsoft/TypeScript/issues/13086
Search terms:  map has narrowing

**Comment by HomyeeKing** [comment] 2021-04-28 13:28
so in this case , we've done type guard by `if condition`,  so it does exist and won't be `delete`d in common use case

**Comment by nmain** [comment] 2021-04-28 13:47
I agree, the code is sound, but tsc has no way to make this kind of reasoning.

**Closed** 2021-05-03 00:00 UTC
Labels: Question
