### ISSUE TITLE
Nested series of assignments takes ~quadratic time to parse

### ISSUE THREAD

**Issue by tchetwin** [microsoft/TypeScript#30833] opened 2019-04-09 13:39 UTC
**TypeScript Version:** 3.5.0-dev.20190409 (also 3.4.2)

**Search Terms:** nested, `parsePossibleParenthesizedArrowFunctionExpressionHead`

**Code**

```ts
a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=a.a).a).a).a).a).a).a).a).a).a).a).a).a).a).a).a).a).a).a).a
```

Alternate test bench:

```javascript
const ts = require("typescript");
const source = `a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=(a=a.a).a).a).a).a).a).a).a).a).a).a).a).a).a).a).a).a).a).a).a`;

ts.transpileModule(source, {});
```

**Expected behavior:**

Parses in a timely manner.

**Actual behavior:**

`tsc` takes 5 seconds, and this time increases ~quadratically as the repetition is increased. In our case this quickly grew to hours.

**Playground Link:**

[Playground](https://www.typescriptlang.org/play/#src=a%3D(a%3D(a%3D(a%3D(a%3D(a%3D(a%3D(a%3D(a%3D(a%3D(a%3D(a%3D(a%3D(a%3D(a%3D(a%3D(a%3D(a%3D(a%3D(a%3Da.a).a).a).a).a).a).a).a).a).a).a).a).a).a).a).a).a).a).a).a%0D%0A) (Warning, this is a little intense and might hang the browser)

**Related Issues:**

Not that I could find

**Some investigation**:

Looking at profile output, it looks like the following might be happening:

* Arrive at first `(`
* Could be a parenthesized arrow function (based on `(a=`...)
* Pursue that theory, start consuming first default assigned property
* Arrive at second `(`
* Could be a parenthesized arrow function (based on `(a=`...)
* Repeat until we finally reach the middle, realise there was no arrow function, backtrack
* We now know the outermost set of parens wasn't an arrow, but an assignment
* Arrive at second `(` (again)
* Repeat the whole process

**But, why?**:

Received output of this style from terser (formerly uglify-es) from original code of the form:

```javascript
str = str.replace("a", "b");
str = str.replace("c", "b");
```

We happen to need to do some AST based post-processing.

**Comment by jakebailey** [comment] 2023-07-18 19:27
This was fixed by #32640; #31987 turned out to be a duplicate of this issue (and has effectively the same test case).

**Closed by jakebailey** 2023-07-18 19:27 UTC
Labels: Bug
