### ISSUE TITLE
Extending String issue

### ISSUE THREAD

**Issue by wallverb** [Microsoft/TypeScript#12328] opened 2016-11-17 17:00 UTC
If this is duplicate of https://github.com/Microsoft/TypeScript/issues/12123 then please close it

```ts
"use strict"
class Dupa extends String {
    constructor(data) {
        super(data)
        this['label'] = data.value
    }
}

const dupa = new Dupa({value: 'Test'})
console.log(dupa['label'])
```

Works in:
* Chrome
* Firefox
* Node: 6.7.0
* Babel: https://goo.gl/eo6QyN

TS compiled code causes runtime error:
`VM2008:11 Uncaught TypeError: Cannot create property 'label' on string '[object Object]'(…)`

**Comment by mhegazy** [comment] 2016-12-16 03:09
this indeed is a duplicate of #12123, please see the documentation in https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work

**Closed by mhegazy** 2016-12-16 03:09 UTC
