### ISSUE TITLE
Support ES7 Object rest/spread properties

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#4928] opened 2015-09-22 18:00 UTC
Here is the ES7 proposal:
https://github.com/sebmarkbage/ecmascript-rest-spread

Rest Properties

```ts
let { x, y, ...z } = { x: 1, y: 2, a: 3, b: 4 };
x; // 1
y; // 2
z; // { a: 3, b: 4 }
```

Spread Properties

```ts
let n = { x, y, ...z };
n; // { x: 1, y: 2, a: 3, b: 4 }
```

**Comment by DanielRosenwasser** [comment] 2015-09-22 20:02
Duplicate of #2103.

**Closed** 2015-09-22 20:03 UTC
Labels: Duplicate, ES7, In Discussion, Suggestion
