### ISSUE TITLE
Object#entries and Object#values doesn't consider optional properties as potentially undefined 

### ISSUE THREAD

**Issue by eliasm307** [microsoft/TypeScript#52045] opened 2022-12-29 13:04 UTC
# Bug Report

### 🔎 Search Terms

- Object entries optional properties 
- Object values optional properties 

### 🕗 Version & Regression Information

- This changed between versions 4.2.3 and 4.3.5

### ⏯ Playground Link

- [4.2.3 Playground link](https://www.typescriptlang.org/play?ts=4.2.3&exactOptionalPropertyTypes=false#code/PTAEHcEsBcAsHsCu1TQM4GN4DsBmkBzAOgCs0cBiAUwA8BDDaAeQAdpIc6AbABQCd4LKn2gBPACqihaUFWx0ARlyoATADShB7Tl1AsBQkZCoyMdbLJqQ0KKHFAADRNhVV82VQ4CwAKCzYbTQUSAC5QAG9ceHgAfjCbPkhsAg0FOj440ASkggBfUABeCKj4MOdXd1VU9LKXNyTVfN9fJmCqRiI5aESTAAp4YIBKIii+AFEGWF7egG0AaypRDQA3bkQqAF1BwoA+CN9QQ9B-QIT47pzC0FWudYBuUBBrtaoshEQuFVAFV752+AI2GsqlAdBkLHg0C6kG4XFEoHK9Q8Kl8uUGzR8rRI7WgRBu6zQ-SGI3g40mvXxrwKe3CByOJxQZyyF2SV0pDyelLeSE+31+-0BwK+YL0kOhsPhiMqKJ8aKAA) producing type error as expected
- [4.3.5 Playground link](https://www.typescriptlang.org/play?ts=4.3.5&exactOptionalPropertyTypes=false#code/PTAEHcEsBcAsHsCu1TQM4GN4DsBmkBzAOgCs0cBiAUwA8BDDaAeQAdpIc6AbABQCd4LKn2gBPACqihaUFWx0ARlyoATADShB7Tl1AsBQkZCoyMdbLJqQ0KKHFAADRNhVV82VQ4CwAKCzYbTQUSAC5QAG9ceHgAfjCbPkhsAg0FOj440ASkggBfUABeCKj4MOdXd1VU9LKXNyTVfN9fJmCqRiI5aESTAAp4YIBKIii+AFEGWF7egG0AaypRDQA3bkQqAF1BwoA+CN9QQ9B-QIT47pzC0FWudYBuUBBrtaoshEQuFVAFV752+AI2GsqlAdBkLHg0C6kG4XFEoHK9Q8Kl8uUGzR8rRI7WgRBu6zQ-SGI3g40mvXxrwKe3CByOJxQZyyF2SV0pDyelLeSE+31+-0BwK+YL0kOhsPhiMqKJ8aKAA) not producing type error anymore

### 💻 Code

```ts
// without tsconfig.json#exactOptionalPropertyTypes enabled, optional properties can exist with `undefined`
const obj: {foo?: string, bar?: string} = {foo: undefined, bar: undefined} 

Object.entries(obj).forEach(([key, value]) => {
    const str: string = value; // value should be recognised as potentially undefined
})

Object.values(obj).forEach(value => {
    const str: string = value; // value should be recognised as potentially undefined
})
```

### 🙁 Actual behavior

From v4.3 it doesnt consider optional object properties as potentially undefined (with exactOptionalPropertyTypes disabled) when using `Object#entries` or `Object#values`

### 🙂 Expected behavior

Optional properties should mean the value when using `Object#entries` or `Object#values` is potentially undefined when exactOptionalPropertyTypes is disabled, as `undefined` could be assigned to the optional properties.

This allows TS to compile code with potential runtime issues from using optional properties as if they were always defined.

**Comment by MartinJohns** [comment] 2022-12-29 13:23
Duplicate of #48587.

**Comment by eliasm307** [comment] 2022-12-29 23:48
Thanks @MartinJohns ! Unfortunately, enabling `exactOptionalPropertyTypes` in the code base im working on would require a lot of fixes so it's not an easy option and difficult to justify the work required.

I understand the concerns in the linked issue about the behaviour potentially causing issues to existing code, however I'm not clear if the change in behaviour in v4.3 was intentional or a regression?

Anyway, it would be nice if there was a way to atleast get a warning about things that might be undefined when iterating over object properties. An option could be to tie different behaviour depending on the value passed to the exactOptionalPropertyTypes option, similar to how different values change the behaviour of allowUnreachableCode. So:

- undefined value would be the existing default behaviour
- true would be where undefined can't be assigned to optional properties
- false would allow assigning undefined to optional properties and also show warnings for  potentially undefined property value usages

**Comment by RyanCavanaugh** [comment] 2023-01-10 18:26
This is the intended behavior as Martin explained.

I don't see much appetite from our side for bifurcation that flag's behavior. This is the first request I've seen where someone only wants *some* of its implications and it's been available for a pretty long time by now.

**Closed by RyanCavanaugh** 2023-01-10 18:26 UTC
Labels: Working as Intended
