### ISSUE TITLE
type guard doesn't work well with index access on an array of discriminated union types

### ISSUE THREAD

**Issue by CYBAI** [microsoft/TypeScript#49898] opened 2022-07-14 03:56 UTC
# Bug Report

I had a discriminated union type and also a type guard function. When I have an array of the type, I cannot use type guard to check with the value `arr[idx]` properly.

As a workaround, I need to declare it as a variable first and use it with type guard.

### 🔎 Search Terms

control flow analysis
type guard
discriminated union

### 🕗 Version & Regression Information

Tried on 4.7.4 and 4.8-beta on playground

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Common Buts That Aren't Bugs

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/KYDwDg9gTgLgBMAdgVwLZwNIEtEBM4DeAUHHAMICGMANCXACIQDmtAvkUaJLHDjMFABmFAMbA4AIQoBnYAEFEWVBQA2hOqUQVUwAFxxpMKDiZF2ncNHh8BwsQ2YIQ-PNMkz5i5WuKlSAaxxcfWw8ADpGU3MuK15EfiFRcUp4UBdcNylZBSVVdT84QLwQoLCUjTgtHTIACwpEJmBguAAjCAgVYHqzDhieGABPMHEc7zgAXgcmOAAfcioOQWREERgsCEReaVHVAAoQfWX-RAgAd0QASn0QLbgdnwqoYBhkKE2bgEJxyeXcYEEcE04AAyYFwT7fSrIFRqUFwQbDCCCcETSEAcggLQAVsBVmiQWDdvs4DI7l5VBcwkV8N9JqFcBFHDM5sTSfdKdTUXTSikLj0iEsVmsNlsUvtDohjmdLtdbil8n4ni83lt7vsLgTwVSglzMDyqABufmC1brTb8Qy7eq5FTSfT3ADaAF1qLxcAcoagWgINb4-FhkbssNIxdbvNIHVh3U6Lr6KgUw6oI1GQE6wlVgLV6o1cBVzAUA3AgyGqFbybaHQAGGNxgoJ8sR6vp7SZuoNJp5jgFEQbQwoyaJispp0VQvFsUgWMKutajNZ9u5grsdhAA)

### 💻 Code

```ts
export enum Kind {
  Cat,
  Dog,
}

export interface BaseAnimal {
    name: string
}

export interface Dog extends BaseAnimal {
    kind: Kind.Dog
}

export interface Cat extends BaseAnimal {
    kind: Kind.Cat
    nameChanged: boolean
}

export type Animal = Dog | Cat

function isAnimal(x: unknown): x is Animal {
    return x !== undefined && x !== null && typeof x === 'object' && ((x as Animal).kind === Kind.Dog || (x as Animal).kind === Kind.Cat)
}

function isCat(x: unknown): x is Cat {
    return isAnimal(x) && x.kind === Kind.Cat;
}

function test(animals: Animal[], idx: number) {
    if (isCat(animals[idx])) {
        animals[idx].nameChanged // compile fail
    }

    if (isCat(animals[0])) {
        animals[0].nameChanged // pass
    }

    const x = animals[idx]
    if (isCat(x)) {
        x.nameChanged // pass
    }
}
```

### 🙁 Actual behavior

while using `animals[idx]` with type guard, it cannot be inferred as Cat inside the if

### 🙂 Expected behavior

`animals[idx]` should be inferred as Cat

**Comment by MartinJohns** [comment] 2022-07-14 07:11
Duplicate of #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.

Just store `state[sku]` in a local variable.

**Closed** 2022-07-16 18:00 UTC
Labels: Duplicate
