### ISSUE TITLE
Unexpected type narrowing

### ISSUE THREAD

**Issue by awerlogus** [microsoft/TypeScript#39285] opened 2020-06-26 21:34 UTC
**TypeScript Version:**  typescript@4.0.0-dev.20200626

**Search Terms:** narrow, type narrowing

When constant has a type which is more wide than its value, assigning this constant to another constant or passing it as function argument will narrow the type to the type of the value

```ts
// string | number
const a: string | number = 5

// Got: number
// Expected: string | number
const b = a
```

**Comment by MartinJohns** [comment] 2020-06-26 22:03
Duplicate of #39028.

**Closed** 2020-06-29 18:00 UTC
Labels: Duplicate
