### ISSUE TITLE
The `typeof x === "number"` guard has stopped working

### ISSUE THREAD

**Issue by d180cf** [Microsoft/TypeScript#9923] opened 2016-07-24 22:09 UTC
After upgrading from `1.8.10` to `2.0.0` got this error:

```ts
        add(layer: matrix | number, rand = () => Math.random()) {
            const v = this.outputs[this.outputs.length - 1];

            if (typeof layer === 'number') {
                this.add(matrix.make(layer, v.length, () => rand() / layer * 2));
            } else {
                this.weights.push(layer);
                this.outputs.push(vector.zero(layer.length));
            }
        }
```

In the `rand() / layer * 2` expression `layer` has type `matrix | number` and thus tsc complains about the arithmetic operation. The `<any>` type cast works around the problem.

**Comment by mhegazy** [comment] 2016-07-24 23:01
Duplicate of https://github.com/Microsoft/TypeScript/issues/7662

**Closed** 2016-07-25 16:15 UTC
Labels: Duplicate
