### ISSUE TITLE
Typescript allows assigning anything to `Record<number, ...>`

### ISSUE THREAD

**Issue by rChaoz** [microsoft/TypeScript#60289] opened 2024-10-19 22:36 UTC
### 🔎 Search Terms

assigning to record number

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.0-beta#code/MYewdgzgLgBCBGArGBeGBvGEQFsCmUAFgJZgDmAXDAETQBO1MAvgLABQoksdewVASrxB0AJgB4wAVxzw8dADRYodUmQB8qOEiA

### 💻 Code

```ts
const obj = { something: "str" }
const rec: Record<number, string> = obj
```

### 🙁 Actual behavior

No error

### 🙂 Expected behavior

It should error as "something" is not of type `number`

**Comment by MartinJohns** [comment] 2024-10-19 23:08
This is working as intended. The type `Record<number, string>` means that all `number` keys are `string`, not that only `number` keys exists. You can't limit the existence of additional properties.

**Comment by MartinJohns** [comment] 2024-10-19 23:11
Duplicate of #45727.

**Closed** 2024-11-02 01:32 UTC
Labels: Duplicate
