### ISSUE TITLE
Function interface issue

### ISSUE THREAD

**Issue by ttony** [Microsoft/TypeScript#4100] opened 2015-07-31 08:43 UTC
Hi Team,

Please visit the link below:

http://www.typescriptlang.org/Playground#src=interface%20Callback%20%7B%0A%09(param%3A%20number)%3A%20void%3B%0A%7D%0A%0Aclass%20A%20%7B%0A%09%0A%09public%20doSome%20%3D%20(callback%3A%20Callback)%20%3D%3E%20%7B%0A%09%09callback(123)%3B%0A%09%7D%3B%0A%7D%0A%0A%0Alet%20a%20%3D%20new%20A()%3B%0Aa.doSome(%20()%20%3D%3E%20%7B%0A%09console.log(%22tony%22)%3B%0A%7D)%3B

a.doSome( () => {  } ); // should compiler not allow me to do this? since the param is not an optional field.

Cheers,

-Y

**Comment by Kinchkun** [comment] 2015-07-31 12:21
Did I understand you correctly that you think something like this should be illegal:

    var foo: (bar: number) => void = () => { }

IMHO this is not an issue, since the interface only guarantees me that I cannot use a function in a wrong way, i.e. a way which leads to defecting behavior.  Since the following does not altering the function outcome, it satisfy the interface constrain:

    foo(5) // function still behaves correctly

Cheers

**Comment by RyanCavanaugh** [comment] 2015-07-31 14:06
Duplicate of #3000

**Closed by RyanCavanaugh** 2015-07-31 14:06 UTC
Labels: Duplicate

**Comment by RyanCavanaugh** [comment] 2015-07-31 14:07
See also https://github.com/Microsoft/TypeScript/wiki/Type%20Compatibility#comparing-two-functions
