### ISSUE TITLE
Allow objects to be passed to BigIntConstructor.

### ISSUE THREAD

**Issue by 12wrigja** [microsoft/TypeScript#46636] opened 2021-11-02 05:00 UTC
# lib Update Request

## Missing / Incorrect Definition

[`BigIntConstructor`](https://github.com/microsoft/TypeScript/blob/663b19fe4a7c4d4ddaa61aedadd28da06acd27b6/src/lib/es2020.bigint.d.ts#L104) does not accept `object`, which it should as the [spec](https://tc39.es/ecma262/#sec-bigint-constructor-number-value) defines it as being able to convert any object to a primitive.

## Sample Code

```
globalThis.BigInt({
  valueOf: () => 20,
});
```

## Documentation Link

https://tc39.es/ecma262/#sec-bigint-constructor-number-value

**Comment by MartinJohns** [comment] 2021-11-02 08:16
Essentially a duplicate of #2361.

**Closed** 2021-11-06 18:00 UTC
Labels: Duplicate

**Comment by 12wrigja** [comment] 2021-11-08 22:30
I can see how that is related, but I don't think it is a duplicate.

That logic does make sense for JS operators, where the coercion is reasonably well defined. That doesn't apply to the types in the BigInt constructor though. In the more general case, I don't think it's correct to change TS to allow wrapped objects everywhere that the valueOf return type matches a given type. See [this playground](https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBZJcWD1RpiWAWaiCABy7EQ0m+AApVvl+iy2WR+KgGMxuYJUJROMwAJSgADeihKJScqHxXgA2vKFZrUO0iecNZqSpyxMIzHhpRlRWYLESAPLSABWkCpvH1BqNDBNnDNIk4lvMkCJzNZ3xdBoVACJw6AANSgPVhkrEMXDTmS0MJgAGABIZasAL4Z10AXQA3Io88EEL6aJwWY99FFUMIALy0+lNoN89kARgADPxw53vqBw5Ky1XRUkHfXBI2W23IAyh2R2TKdAxoOxIDbkuzpTLQEqVaA+yXQHm88axF6B3bHVSR2PQCocGphEJOAByGhfK4MZBBIoE7wO4ATQPAzDsoOvLfAAOqgd5Oqgo5lsk8DYuy7jpM2vZnhQAA8taIDOc5gSizCxHh0bRvurrAaB4GQdmMpESR0BNqqFBFnm8E5vA04NuxgicdxGZjuWwQvs0HhkF4iDoc4wLsD+dyMBK7BCpA-CwNA6iJAwwJ6D6I4AKKrP+Cz6FG6EjuADioJ+wiMpAEjhkEKg2l8ZDvIIWlaJARyCmQCiuNIeCHpA8k6MMWD6CgCCINCnoxHcEjodEIgGBw2ILEwrAcDwARAA) for some examples where this doesn't work.

I would hope that if this behavior was desirable for authors of a function they would be able to opt into it explicitly (strawman: `function example(x: number|HasValueOf<number>)` where `HasValueOf<T>` matches any object whose valueOf returns type `T`). If this were the case, I'd expect the `BigInt` typings to be updated to include it, but as it stands today that doesn't exist and `object` is the best that can be done.
