### ISSUE TITLE
Some ideas about the better version of function overloading in TypeScript (Similar to Java).

### ISSUE THREAD

**Issue by WRSP** [microsoft/TypeScript#52256] opened 2023-01-16 07:47 UTC
## ⭐ Suggestion

The ideas about function overloading in typescript.

------------ Current TypeScript -------------

```
class NetworkUtility {
	public upload(url: FtpUrl, file: File)
	public upload(url: SftpUrl, file: File)
	public upload(url: any, file: any) {
		... if else manually ...
	}
}
```
------------ The Expected TypeScript -------------
```
class NetworkUtility {
	public upload(url: FtpUrl, file: File) {
	    ...
	}
	public upload(url: SftpUrl, file: File) {
	    ...
	}
}
```
----------- Generated Native Javascript -----------
```
class NetworkUtility {
	upload(url, file) {
		if(url.constructor.name === "FtpUrl" && file.constructor.name === "File") {
			__upload_FtpUrl_File(url, file);
		} else if(url.constructor.name === "SftpUrl" && file.constructor.name === "File") {
			__upload_SftpUrl_File(url, file);
		}
	}
	
	__upload_FtpUrl_File(url, file) {
		...
	}
	
	__upload_SftpUrl_File(url, file) {
		...
	}
}
```

**Comment by MartinJohns** [comment] 2023-01-16 08:28
You forgot to fill out the issue template. It contains a viability checklist, where this kind of suggestion is mentioned. It goes against the [TypeScript Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

I'm also certain this has been suggested before already.

**Comment by xiBread** [comment] 2023-01-16 15:11
Duplicate of #3442

**Closed** 2023-01-17 22:53 UTC
Labels: Suggestion, Out of Scope
