### ISSUE TITLE
Cannot assign the object of rest properties into `Record<string, unknown>`.

### ISSUE THREAD

**Issue by mysticatea** [microsoft/TypeScript#44505] opened 2021-06-08 11:59 UTC
# Bug Report

### 🔎 Search Terms

```
rest properties record<string,unknown>
```

### 🕗 Version & Regression Information

This looks happening since TS 3.5. Related to https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#-k-string-unknown--is-no-longer-a-wildcard-assignment-target

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.2#code/N4KABBYPRWBKBTAxgSwQNxQOwOZgIZgAGiSA9gE4AmAPAM4AuF2OANGAK5YDWWZA7lgB8RMGQBGAK2QNwkAGZckDFGSxgGCRgAoJ05QC54ySrUbNc7LrwHCAlEfRkUVMKEgew5LHTIAbBAA6PzIcXSkZOwBuOQgAXxBYrzVGMWYcbHw-AHkI5TAAXjcwLHwAWwQjACIAQT8UJAQq9nwcSrAAJgAGMDiYj29U4BLyhHZAiYotBgAFCjIABzpewrSUDNKcvIYYpM0dSnXMrf0GaKSYSAA9G9u7u7BsgGkAQj3p7SnGOcW6c49LhB7g8AKJwODZOBGACSWCoCAAHmA6OtSgwOFMwChlmVsSjcFj1AwAJ4LBBgADkw1a7SwHDK4gQFCivQp7x0X1m8yWBGW1LaRjpDKZLLi-0ggLAwOlMpljye7HEHAYGgAFtivPhUiEyNxllRnAS+Ax1bhAiAEkA)

### 💻 Code

```ts
// Recieving a `Record<string, unknown>` object
function test(object: Record<string, unknown>): void {
    console.log(object);
}

const originalObject = { name: "Alice", age: 20 };
const { name, ...restProps } = originalObject;

test(originalObject);
//   ^^^^^^^^^^^^^^ OK!
test(restProps);
//   ^^^^^^^^^ ERROR: Index signature is missing in type '{ age: number; }'
test(restProps as { age: number; });
//   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ OK, but this cast looks doing nothing.
```

### 🙁 Actual behavior

That `test(restProps);` triggers a type error.

### 🙂 Expected behavior

That `test(restProps);` is OK as the same as `test(originalObject);` or `test(restProps as { age: number; });`.

**Comment by jcalz** [comment] 2021-06-08 20:13
duplicate of #42021, adding search terms "index signature" and "destructuring"

**Closed** 2021-06-11 18:00 UTC
Labels: Duplicate
