### ISSUE TITLE
[Legacy Support] tsc --watch should NOT clear my console

### ISSUE THREAD

**Issue by roblav96** [Microsoft/TypeScript#21824] opened 2018-02-09 08:35 UTC
> tldr;

Please merge this:
https://github.com/Microsoft/TypeScript/pull/21303 `Added --preserveWatchOutput flag`
🍰

----

After upgrading to `typescript@2.7.1` my terminal gets cleared whenever the watcher detects a change.

This is painfully annoying because I have a vertical widescreen monitor setup and my eyes naturally focus to the bottom.
![BPXIcZj](https://i.imgur.com/BPXIcZj.jpg)

----

https://github.com/Microsoft/TypeScript/pull/20389 `"tsc --watch should clear screen on new compilation" Two: Electric Boogaloo`
https://github.com/Microsoft/TypeScript/pull/20427 `Added console clearing with a message to --watch starts`
https://github.com/Microsoft/TypeScript/issues/21295 `Allow not clearing the console on recompiles in --pretty --watch mode`

**Comment by mhegazy** [comment] 2018-02-09 16:58
Duplicate of https://github.com/Microsoft/TypeScript/issues/21295

**Closed** 2018-02-26 20:42 UTC
Labels: Duplicate
