### ISSUE TITLE
Number.isFinite is missing type guard

### ISSUE THREAD

**Issue by Juraj-Masiar** [microsoft/TypeScript#43792] opened 2021-04-23 13:45 UTC
# Bug Report
The `Number.isFinite` accepts `unknown` parameter and returns `true` only if the parameter is `Number`.
So there should be a type guard saying it's a `Number`.
MDN:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite

### 🔎 Search Terms
Number.isFinite

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `Number.isFinite`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAEziARgGwKYAoAeAXImCALbrYBOiAPouMtsDGNsgJTGkXWIDeAKESIYwRLgBy5SlQB0MAM4AxVjCh58HDgOEjEVbFBBUk+RACpEAJgDcegL57Dx04gAM9p0A)

### 💻 Code

```ts
function double(x: number | undefined): number {
  if (Number.isFinite(x)) {
    return x * 2;  // ERROR: Object is possibly 'undefined'.
  }
  return 0;
}
```

### 🙁 Actual behavior

ERROR: Object is possibly 'undefined'.

### 🙂 Expected behavior

No error :)

**Comment by MartinJohns** [comment] 2021-04-23 14:20
Duplicate of #39090. Found using the search terms you provided in your issue.

**Closed** 2021-04-23 14:26 UTC
