### ISSUE TITLE
Make inference of index signatures more precise

### ISSUE THREAD

**Issue by aloifolia** [Microsoft/TypeScript#29377] opened 2019-01-11 16:47 UTC
## Search Terms

index signature, object, value, field

## Suggestion

Currently, it is not possible (or I missing some crucial knowledge here) to infer the concrete type of the value of an object field. So while in the following code the compiler correctly infers `bar` for `a`

````ts
const a = 'bar'
type b = (typeof a); // this yields "foo"
````

it fails to do the equivalent in the following example

````ts
const t = { foo: 'bar' };
type u = (typeof t)['foo']; // this yields string
````

The compiler should literal types for values in objects, as well. 

## Use Cases

I would like to be able to infer the types of configuration objects without having to explicitly annotate them. This would allow me to write such objects without much hassle and simultaneously use Typescripts inference mechanism to reason about the well-definedness of these values. 

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jack-williams** [comment] 2019-01-11 16:53
Essentially a duplicate of #10195 I think.

**Comment by aloifolia** [comment] 2019-01-13 11:11
@jack-williams Yes, I guess this is a specific case of the more general inference problem mentioned in #10195. I [summarized](https://github.com/Microsoft/TypeScript/issues/10195#issuecomment-453820606) my findings there, as well.

**Closed** 2019-01-15 18:00 UTC
Labels: Duplicate
