### ISSUE TITLE
Exclude<any,whatever> (another way of negated type #29317)

### ISSUE THREAD

**Issue by escKeyStroke** [microsoft/TypeScript#33318] opened 2019-09-09 04:41 UTC
Hi

## Search Terms

Exclude<any
type subtraction 
any but
all types except
Checked: https://github.com/microsoft/TypeScript/issues/31579 https://github.com/Microsoft/TypeScript/pull/29317

## Suggestion

``` typescript
type T00 = Exclude<any,whatever>
``` 
`T00` should be composed of `any` (all) types, except those types that are assignable to `whatever`
## Use Cases

I definded a bunch of functions according to the following interface: 
``` typescript
interface ecafretni { (x:any, y:Q): any }
```
`x` literally takes any type, there's no possible narrowing down.  Think of a general-purpose deep-copy function, for example.  `Q` is some other interface I defined somewhere.  **Here's the use case:** I had to change the order of the arguments of `ecafretni` to `(y:Q, x:any)` and I was wishing that TypeScript would point out all the (hundreds of)  points where I was calling functions abiding by that interface, so that I woulnd't miss any.  But it wouldn't because, of course, type `Q` is assignable to `any` and type `any` is assignable to `Q`.

So I came up with another type to use in the place of `any`: `R = Exclude<any,Q>`, and redefine `ecafretni` argument types as `f(y:Q, x:R)`.  But it's not working.  It seems that `R` behaves the same way as `any`.
## Examples

```typescript
const f = function( x : Exclude<any,Number> ){};
const x:Number = 4;
const v = f(x); // TYPE MISMATCH !!!! (not caught by TypeScript)
```
## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2019-09-09 06:23
Duplicate of #29317.

**Comment by jack-williams** [comment] 2019-09-09 07:58
Duplicate of #29188

**Closed** 2019-09-16 18:00 UTC
Labels: Duplicate
