### ISSUE TITLE
ts.transpileModule does not return diagnostics

### ISSUE THREAD

**Issue by alexlur** [Microsoft/TypeScript#17514] opened 2017-07-30 03:21 UTC
**TypeScript Version:**  2.4.2

**Code**

```ts
import * as ts from 'typescript';

const module = ts.transpileModule('const a: string = 2; a = 0;', {
  reportDiagnostics: true,
});
console.log(module.diagnostics);
```

**Expected behavior:**
Reports `[ts] Type '2' is not assignable to type 'string'`.

**Actual behavior:**
Diagnostics is an empty array `[]`.

**Comment by aluanhaddad** [comment] 2017-07-30 03:28
From what I understand, that is precisely the point of the transpile module API. It exposes TypeScripts ability to transform ESNext code intro various targets while remove TypeScript specific syntax _without_ typechecking. This is useful for many tool chains that wish to perform typechecking and transpilation separately.

**Comment by alexlur** [comment] 2017-07-30 04:15
Thanks for the quick response. How should I migrate this API call to include typechecking?

**Comment by alexlur** [comment] 2017-07-30 04:17
What does `reportDiagnostics` option do?

**Comment by kitsonk** [comment] 2017-07-30 07:08
Duplicate of #4864

**Closed** 2017-07-30 10:32 UTC
