### ISSUE TITLE
ts need path alias

### ISSUE THREAD

**Issue by jiankafei** [microsoft/TypeScript#45860] opened 2021-09-14 12:14 UTC
# Suggestion
## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

In the nodejs environment, you can not use rollup and other packaging tools, but only need the TSC compiler to output TS as ESM, so the "path alias" is necessary.

## 📃 Motivating Example

```json
/* tsconfig.json */
{
	"compilerOptions": {
		"rootDir": "src",
		"outDir": "dist",
		"paths": {
			"src/*": ["src/*"],
		},
		/* The default is false,This option determines whether to replace the path alias */
		replacePaths: false
	}
}
```

## 💻 Use Cases

```json
/* tsconfig.json */
{
	"compilerOptions": {
		"rootDir": "src",
		"outDir": "dist",
		"paths": {
			"src/*": ["src/*"],
		},
		/* The default is false,This option determines whether to replace the path alias */
		replacePaths: false
	}
}
```

```ts
import aaa from 'src/aaa'; // aaa.ts

// if "replacePaths" is true, The above import path will be replaced.

import aaa from '/project/dist/aaa.js'; // "/project" refers to the current project working directory. "dist" is the outDir.
```

**Comment by IllusionMH** [comment] 2021-09-14 12:57
Duplicate of #41782, #26722 and many other

**Comment by funkydev** [comment] 2021-09-14 15:09
I described the request more detailed in Issue #45862

**Closed** 2021-09-14 19:01 UTC
Labels: Duplicate
