### ISSUE TITLE
Mix of mix cause error

### ISSUE THREAD

**Issue by shrinktofit** [microsoft/TypeScript#34410] opened 2019-10-15 04:04 UTC
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
- Mixin composition
- Recursive mixin

**Code**

```ts
type Constructor<T = any, A extends any[] = any[]> = new (...a: A) => T;

function CallbackInvokable<T extends Constructor>(base: T) {
    return class extends base {
        protected invoke(...args: any[]) { }
    };
}

function EventTargeted<T extends Constructor>(base: T) {
    // A event target should be callback-invoke-able.
    // Error: Type "{ new (...a: any[]): CallbackInvokable<T>.(Anonymous class); prototype: CallbackInvokable<any>.(Anonymous class); } & T" is not a constructor type.
    return class extends CallbackInvokable(base) {
        public emit (...args: any[]) {
            this.invoke(...args); // "invoke" doesn't exist on type (Anonymous Class).
        }
    };
}

class Empty {};
class Test extends CallbackInvokable(Empty) {}; // OK
class Resource extends EventTargeted(Empty) {}; // OK
```

**Expected behavior:**
No error reported.

**Actual behavior:**
Error reported, as commented above.

**Playground Link:** 

**Related Issues:**

**Comment by raymondfeng** [comment] 2019-10-16 00:33
Is it a duplicate of https://github.com/microsoft/TypeScript/issues/33739?

**Comment by RyanCavanaugh** [comment] 2019-10-17 23:24
See #13807 and its related suggestions

**Closed** 2019-10-18 02:08 UTC
Labels: Duplicate

**Comment by boconnell** [comment] 2023-08-23 21:57
FWIW this seems more like a dupe of https://github.com/microsoft/TypeScript/issues/32080 than https://github.com/microsoft/TypeScript/issues/13807
