### ISSUE TITLE
Inferred return type of generic function with specialized arguments is unknown

### ISSUE THREAD

**Issue by kol-93** [microsoft/TypeScript#40111] opened 2020-08-18 12:17 UTC
**TypeScript Version:** from **3.5.1** to **4.0.0-beta**

**Search Terms:**
is:issue is:open return type generic unknown 

**Code**
```ts
declare function f<T>(x: T): T;
declare function g(x: number): number;

type F = typeof f; // type F = <T>(x: T) => T;
type G = typeof g; // type G = (x: number) => number;

type TypedReturn<Fn extends (...args: any[]) => any, Args extends any[]> = Fn extends <A extends Args>(...args: A) => infer R ? R : never;
type TypedReturn1<Fn extends (arg: any) => any, Arg> = Fn extends <A extends Arg>(arg: A) => infer R ? R : never;

type FR = TypedReturn<F, [number]>;
// expected: type FR = number;
// actual:   type FR = unknown;

type GR = TypedReturn<G, [number]>;
// expected: type GR = number;
// actual:   type GR = number;

type FR1 = TypedReturn1<F, number>;
// expected: type FR1 = number;
// actual:   type FR1 = unknown;

type GR1 = TypedReturn1<G, number>;
// expected: type GR1 = number;
// actual:   type GR1 = number;

// These types are proofs of a bug
type F_Infer_OK = F extends (...args: [number]) => number ? true : false;
// type F_Infer_OK = true;
type F_Infer1_OK = F extends (x: number) => number ? true : false;
// type F_Infer1_OK = true;

type F_Infer_FAIL_1 = F extends (...args: [number]) => string ? true : false;
// type F_Infer_FAIL_1 = false;
type F_Infer1_FAIL_1 = F extends (x: number) => string ? true : false;
// type F_Infer1_FAIL_1 = false;

type F_Infer_FAIL_2 = F extends (...args: [string]) => number ? true : false;
// type F_Infer_FAIL_2 = false;
type F_Infer1_FAIL_2 = F extends (x: string) => number ? true : false;
// type F_Infer1_FAIL_2 = false;
```

**Expected behavior:**
See comments in ***Code*** section

**Actual behavior:**
See comments in ***Code*** section

[Playground link](https://www.typescriptlang.org/play?ts=4.0.0-beta#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVIB4AVAPgAoAPALniIEoaiBuAKFElgRXWz3gHNKNVMgC2AIxAwG8ERKmsWGAJ4AHBADF4AXngr1OREibwA9Kb1rNO+MXLVadHSVqt9CAOI33hgSfOW6vBeukKyYpLSzuHyMIrutFbAAEogGMgwqAQa+CAUGCCowADO8GQAdJWw-MU0UKjKANoAuk7aLvXKADTwAIIwNfB5BUWlnS0uujlD+YUltr0zI-P9NeSV5dW1fW0uWKiIUvDJ8AD8x-DCIABuCkpWieopaRmoAIzZubOjZdV1Dbt4J0eqtJvBpsM5qUCItIT9QWQ-jtovtDjALucTldbnEWPcghoTroiElUulMtkeo05JFmiRWAE8upMCBgDQEoSbDS7gEoJhkFAIDR4IFNET4GgANaoHAAd1Q8QeHnFJKeZNeBA8VO5MDpDIsTPABTZouC4p1+qB-MFwtNyq5ETu+LFbxsqtZ6syHw0PR19JYjIozON7IehNdugtAYsfPSNpFpvDNilMvliqCyojjw9Ly9mt9jpg-sDwdZoYzySzUd51qFCYSmYdsUU0doAAsQMUEO4xnB4KoYDhDKVfFB4OJkPxneCAPoASQOUhnAHkANI2LRw+YVKoDbbUwutaI6s56GDIBA0RCCruWjnzxcwFfr3QYc8gNxhh9ot7PjdLKEygcHVARPc43wvS4kBvD9W3vBcfz-V933TTRvyXDRejnAAZGcs03b5tw2LYaAPWIj3aeBijffZ+FPCDL2giBbzgr8EIwrDcKza9mNg+DH1-TCcLw-8t1KMIQOiaiYFo+j3ygniWICfjEKEribEU2Dpw0dCnzUmcACZRMI8TiL3UjpNoiiXDAs9IKvGC7zYx8Z30ozdE0z8CV0wTOMM4zlnEhxLNQfhQMLOT7KYpSLBUqRfOE9zotgoA)

**Related Issues:**
No direct related issues found.

**Comment by ahejlsberg** [comment] 2020-10-21 23:56
This is effectively a duplicate of #22617. As I mention there, the fix would be to have type inference in conditional types perform instantiation of a source type in the context of a target type when the source type is a generic function type.

**Closed** 2020-10-24 18:00 UTC
Labels: Duplicate
