### ISSUE TITLE
Narrowing unions of interfaces with intradependent property types

### ISSUE THREAD

**Issue by david-mancuso** [microsoft/TypeScript#51341] opened 2022-10-28 15:20 UTC
# Bug Report

Type narrowing doesn't behave as I expect it would for a union of interfaces where one property type is mapped directly to another property type. If this is not a bug, I would love to understand how I can better type this use case because it appears valid to me.

### 🔎 Search Terms

enum, union, type, interface, property, never, error, validation, gating, narrowing, 4.7.4, strict

### 🕗 Version & Regression Information

Bug appears in v4.7.4 (used in my context) through latest `next` version today.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20221025#code/KYOwrgtgBAYg9nA0sAngZygbwLACgpQBCAggEpQC8UA5AEYCGATtQDR4EkBalNDAXtTwBfPHgCWIAC7BGAM3oBjYESZZ2UANaoAXLATJ0AOhKkA3OoBu9ADZhgutJMYSA5udwjc4qTPlKVfGr4mjp6SKhoxsSc7gRWtvZQ4BC0Mu6eeJIoAA7K8HA8hKoAPgHu3tJyinkIRYxBBAyMunUA2tTxdtQAumzB-C30fO2dwD19BHDZkmi6+a3dwqK4Ctb0aBj5dVBiENnWwBCgM2HbOP2qVNT0tArUsVD8PACMAEwAzA9TM3MICzytc4EAhaFC-cJGEwTYGjXTUAAmwFkgmCQmhQOBoPBBkiXGhcRsdl0ABYAKwANnUngI3XKwQUcBAjkYYAUkjgjAAFABKTBQIRQZYEWQIJo83QWOBieENYGSAAWYki30iIsYAFFFPLOZy+aCWFBRvzuZQAHyy4FQBVK1qg7o8UYPAhCbl053CIA)

### 💻 Code

```
enum FooKeys {
  BAR = 'bar',
  BAZ = 'baz'
}

interface Bar {
  key: FooKeys.BAR;
  value: string;
}

interface Baz {
  key: FooKeys.BAZ;
  value: number;
}

type Foo = Bar | Baz;

interface FooBar {
  bar: Bar['value'],
  baz: Baz['value'],
  opts: Foo[]
}

class FooBar implements FooBar {
  bar = 'abc';
  baz = 123;
  opts: Foo[] = [{
    key: FooKeys.BAR,
    value: 'def'
  },
  {
    key: FooKeys.BAZ,
    value: 456
  }
  ];

  constructor(){ } 

  foobar(): void {
    this.opts.forEach(({ key, value }) => {
      // Throws error:
      // Type 'string | number' is not assignable to type 'never'.
      // Type 'string' is not assignable to type 'never'.
      this[key] = value;
    });
  }
}
```

### 🙁 Actual behavior

The `Foo` properties of `value` and `key` are not narrowed relative to each other despite being constituents of discrete types where they are directly related.

### 🙂 Expected behavior

I would expect that typing an object as `Foo` would enforce the relationship between the `key` and `value` properties. This is because the `Foo` union is not an `any` to `any` relationship of its constituent interfaces' properties. Each interface has a type for the `key` which maps directly to a type for the `value`. These relationships are enforced at the time of initializing `opts: Foo[]` but that same reasoning seems to not apply when narrowing and gating the `Foo` objects.

**Comment by fatcerberus** [comment] 2022-10-28 15:38
Duplicate of #35873 and/or #30581.

**Comment by erabl-identos** [comment] 2022-10-30 15:54
I've a similar usecase where a boolean property directly determines whether or not another property is either a valid enum value or `null`:

[TS-Playground](https://www.typescriptlang.org/play?#code/PTAEAEGcBcCcEsDG0Bco4FcCmAoHWA7DAW1AEkCA3AQwBt4ATAJS2sgHsDQBvHUUAKJMmAeSYB9AIwAaPoOFjxAJlkBfPPALQssAGbVEWQTVoZq2hgBFqATwBCbI734NbaGAgIBzANxz4kABqdIxoAEbs7LSsBH78miaMLGycaBSJzKwcXAA+oES0tH7qOJraegZGwfQMAiZmFtY2oFgAHtoEDJDGdA1YVrYOkE7+QSEMaJhYcaAJ48nZaAVFOCVlOvqG5FTjdb3m-U0t7YRdPaYHA-aOPKPVoaD6tMMzczULqdsZH7GreNA2AAORj2F0atlAAF5QPdavVLkc8uldvDwTY-HhdBgCMh4JxQF4sNBQX0rgAKACUaBJCIhzlA0WgLVgsHYsDSO3eWXxeWWUPyGEKGP4IFAABUgVhuuxdKBAazgbAAaAAOQBWEq0DUWBGTSIdjEQHmeBhaIAOnFktVESiMU1AXy7CZbEg8C8BGopqM0HY6CtKqewxVZrJSgAzEolBS5KKAO7waAAC1mYxq-KmWs6s05SW5XGhy2k5FAsfYgoYx2ByEtwMgiAQgKZPtAw29iYdbFAAANYTS0V25DroBhYFx6S43KqlAAGSMAWkk07nYckKtk-HiqYeOlZsChkILgto643b1zKQIaB3bJPqgxMbAYSwtHYsdA+oYRlLsAA1t1O20VYWOgiZll4iYxgAVKAQ4jmOcgTjYaAqjO86Lsuq4nvwZo4WS157geh6FKAAD8PAprCkywNgRZnpkF5LEeoCqKAaDcBR4xoIGWC0Tm9GLMyu7MRSt4+KAkHAKsQA)

```typescript
enum InvalidReason {
  ERROR_1,
  ERROR_2,
}

interface EvaluatedDayBase {
  day: string;
  isValid: boolean;
  invalidReason: InvalidReason | null;
}

interface ValidEvaluatedDay extends EvaluatedDayBase {
  isValid: true;
  invalidReason: null;
}

interface InvalidEvaluatedDay extends EvaluatedDayBase {
  isValid: false;
  invalidReason: InvalidReason;
}

type EvaluatedDay = ValidEvaluatedDay | InvalidEvaluatedDay;


function getEvaluatedDay(): EvaluatedDay {
  let error: InvalidReason | null = null;

  // Types of property 'isValid' are incompatible. Type 'boolean' is not assignable to type 'false'.(2322)
  // with isValid = true and invalidReason = null, I would expect Typescript to see this as `ValidEvaluatedDay`
  return {
    day: '2022-10-31',
    isValid: error === null,
    invalidReason: error,
  };


  // below code works as expected though
  /* return {
    day: '2022-10-31',
    ...(error === null ? { isValid: true, invalidReason: null } : { isValid: false, invalidReason: error }),
  }; */
}
```

**Closed** 2022-11-01 18:00 UTC
Labels: Duplicate
