### ISSUE TITLE
Allow inferring generic function types "as const"

### ISSUE THREAD

**Issue by mmkal** [microsoft/TypeScript#38968] opened 2020-06-07 12:04 UTC
## Search Terms

const generic inference nested

## Suggestion

Let generic function signature specify that type parameters should be inferred `as const`

## Use Cases

Allow writing library functions that specify how they want their generic parameters to be inferred. Right now, this is only possible with generics like `<T extends string>(value: T) => ...`, which doesn't cover objects - only literals.

## Examples

Let's say you have a basic runtime type-matching function:

```typescript
const getMatcher = <T>(sample: T) => <U>(value: U): value is T & U => {
  // implementation details not important - just a very basic deep-equals
  if (sample && typeof sample === 'object') {
    return Object.entries(sample).every(([k, v]) => k in value && getMatcher(v)((value as any)[k]))
  }
  return sample === (value as any)
}
```

If I try to use this to make a string matcher, it doesn't keep track of literal types:

```typescript
const fooMatcher = getMatcher('foo') // T is inferred as `string`, not literal `"foo"`

const s = Math.random() < 0.5 ? 'foo' : 'bar'

if (fooMatcher(s)) {
  const foo: 'foo' = s // Error: Type '"foo" | "bar"' is not assignable to type '"foo"'.
}
```

This makes sense as default behaviour, since `'foo'` was passed in as a string. And it can be fixed at the call site with `getMatch('foo' as const)`. But this only works for typescript programs, and if we're writing a library, javascript users of that library won't get useful type inference. And it's not really intuitive. Even typescript users of the library will need to know somehow that this trick is available.

It could also be fixed by changing the function signature:

```typescript
const getMatcher = <T extends string>(sample: T) => ...
```

But `getMatcher` is now limited to only work with strings. This doesn't cover the case of deeply nested objects:

```typescript
const commentMatcher = getMatcher({
  type: 'comment',
  payload: {sender: 'abc'},
})
```

As far as I know, there's no way to tweak the `extends` constraint for `T` which makes this keep track of the literal `type: 'comment'` and `sender: 'abc'` values. So this feature request is to allow us to effectively ask the compiler to add `as const` to any inferred type parameters:

```typescript
const getMatcher = <T as const>(sample: T) => <U>(value: U): value is T & U => {
  ...
}
```

(syntax is just an idea which reuses the `as const` pattern in the generic typedef)

If we could do this, it'd make it easy to use the matcher to write useful type guards:

```typescript
type Request =
  | {type: 'comment'; payload: {sender: string; issueId: number; body: string}}
  | {type: 'issue'; payload: {sender: string; id: number; title: string; body: string}}

const commentMatcher = getMatcher({
  type: 'comment',
  payload: {sender: 'abc'},
})

const handleRequest = (request: Request) => {
  if (commentMatcher(request)) {
    console.log('parent: ' + request.payload.issueId) // request would be correctly inferred as a comment, because `type: 'comment'` was inferred as a literal
  }
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by robbiespeed** [comment] 2020-09-05 17:10
@mmkal using overloads you can make your `getMatcher` function infer strings/numbers as const and still work with objects like this:
```ts
function getMatcher <T extends string> (sample: T): <U> (value: U) => value is T & U
function getMatcher <T extends number> (sample: T): <U> (value: U) => value is T & U
function getMatcher <T> (sample: T): <U> (value: U) => value is T & U
function getMatcher <T> (sample: T) {
    return function <U> (value: U): value is T & U {
        if (sample && typeof sample === 'object' && typeof value === 'object') {
            return Object.entries(sample).every(([k, v]) => k in value && getMatcher(v)((value as any)[k]))
        }
        return (sample as any) === value;
    }
}
```
[playground](https://www.typescriptlang.org/play?ts=4.0.2#code/GYVwdgxgLglg9mABAcwKZQLIEMoQBaoBOiAPACqKoAeUqYAJgM6KNSExjIB8iAFI1gC2ABwA2qAFyIyASikkAqj14A3LKJCTECmYgC8PNRtSIYzCgDJtAKFCRYCFOmy4CxcpRp0miMCEEARkTKAiLiUrLySnxGmlI6+obqmqbmiFYKtuDQ8EhomDj4RKRkIUJiWpGk0arJWgkGiLEmZtLpNnY5jvkuRe6lfKEVEboA3taIk4iE6CCESJ0OSIrKzfFyTXWpbRmI41MHpsCD5eLpVlAAnsKocMdDZ3pPiADkcAEAVqjQL+eIVzc7ptjPpnm9Pt8oC8xhNDnCZlA5kgAPIQ6AAOjobBgqEY-FOqBkmJUREuvF4AG0ANYAGiaAF1dI0qaYkM0-j1Cm5VDJyeysMwsGBLjJqYyZLC4QBfSWHBFIk5hEwCxBCkWgvTAzQAbllMpl1ggCFYiGAcDgvTc+icBVcRF4LzNcGhuqNYBNYAATJbiprOXbCLxPTJdYbjVAWNaXHh0YQhfQ4IJeLoSIgAAzogCsiAA-K8nb8pC8AlhCC9QzBjrwnT7A4wZDDJm6TU6iwXrYxdQbmxGLVzfTba7xRqbzVI2CkpSHrGH3RGAlGcDG4wxE8nSOms7m9qO4OPCJPEEWS2WK1W+wHeAEG3tYT3EHud63EAFzeIhYgpdaAl3rEA)

**Comment by mmkal** [comment] 2020-09-08 17:13
@robbiespeed yes, but I'm interested in inferring objects with string/number _properties_ as literals, not just string/number values. This solution helps, but doesn't cover the example in the OP:

```typescript
getMatcher({ type: 'comment' })
```

Here, the generic will be inferred as `{ type: string }`, whereas I want `{ type: 'comment' }`

**Comment by robbiespeed** [comment] 2020-09-08 19:20
@mmkal my mistake I missed the part where it was about properties, doesn't help that I forgot `{ foo: 'bar' } as const` is valid syntax for recursively making a objects properties readonly and inferred as literal.

I did just stumble across how to make it work for properties, I thought it would only restrict the type going into `getMatcher` to a const, but it actually inferred all the properties as literal.

```ts
type ConstRecord <T> = {
  [P in keyof T]:
    T[P] extends string ?
      string extends T[P] ? never : T[P] :
    T[P] extends number ?
      number extends T[P] ? never : T[P] :
    T[P] extends boolean ?
      boolean extends T[P] ? never : T[P] :
      ConstRecord<T[P]>;
}

type ConstValue <B, T extends B> = B extends T ? never : T;

function getMatcher <T extends string> (sample: ConstValue<string, T>): <U> (value: U) => value is T & U
function getMatcher <T extends number> (sample: ConstValue<number, T>): <U> (value: U) => value is T & U
function getMatcher <T extends boolean> (sample: ConstValue<boolean, T>): <U> (value: U) => value is T & U
function getMatcher <T> (sample: ConstRecord<T>): <U> (value: U) => value is T & U
function getMatcher <T> (sample: ConstRecord<T>) {
    return function <U> (value: U): value is T & U {
        if (sample && typeof sample === 'object' && typeof value === 'object') {
            return Object.entries(sample).every(([k, v]) => k in value && getMatcher(v as any)((value as any)[k]))
        }
        return (sample as any) === value;
    }
}

const oMatcher = getMatcher({ foo: true } as const); // type infered as { foo: 'bar' }
const oMatcherB = getMatcher({ foo: true }); // type also infered as { foo: 'bar' }
const oMatcherC = getMatcher({ foo: { bar: true } }); // works on nested props too!

const b = Math.random() < 0.5 ? { foo: true } : 'bar';

const barMatcher = getMatcher('bar');

if (oMatcherB(b)) {
  b; // type guarded to { foo: true }, although it's not properly reducing the type and has a full type of:
    // ({
    //     foo: true;
    // } & string) | ({
    //     foo: true;
    // } & {
    //     foo: boolean;
    // })
    // It might be possible to fix this with some tweaking
}
else if (barMatcher(b)) {
  b; // type correctly guarded to 'bar'
}
```
[Playground](https://www.typescriptlang.org/play?ts=4.0.2#code/C4TwDgpgBAwg9gOwM7AEoQMZwE4BMoA8AKgHxQC8UA3gFBRQDaAClAJYJQDWEIcAZlCIBdAFx16g5kKgQAHsAgJcSKCmzsA5lAD84iauDqEWuQqUqiUnVAQQAbhGxQRkptLH7LbmfMXKbAK4AtgBGjjp6EgjBYU6mfhZW2jb24S5e7pEZPmb+IXBwADYQAIYcuvr0+UWlHPHmrtLJtg5O6VYelfDIaJg4uMRSJADcNAC+NDSgkLCIKABqJYUB0AQAQgA0gjkJUGtklGs7DUTWLWmCozR8AQgYwKyIUBoQwACyJcAYABbhxMf+NSaMgACiQJSCYGKLm6CyWKwIQOMW1IAEoXAQAKqguzwiAuTGoihkXHLaCsCxQABkUEx11u90eHBe70+Pz+p3q-mioUcoPBkOhsx6izJBB5sRRJHRhGxUBBpJWBKJ5BJeLYlJpdJudweTxZHy+vyc-y5KmqxTK-IhUPxwrhYottSlMqxOLxyuJUEV5M1tPpuqZz1ehvZJtI8oFtphc16WDwxGlGLlCo9tJVarJGu2WoDjP1IbZxsIEbBNqFsLj-UTRNo+mwrwC2A4OvzHDd8p9ypcPuzpy11Ei+lYAjLgugVJp0wg-FU5eg5EXUAA5HAQgArTDAZfUqfgGcCXuLyirjdb5e1oeVegN4BNjgAeTP9wAdIpDKwIEgx7bUW-WiAIIggwnBbHYQgZlwbAcL2k7BqyRqOAqUAlCoZQgKiQG9qhKEIBhIEQaiV70BM143o2zaRvOKFoXhKpLj6oz6BMEw0FgPRQHAobFpQBpFkhVBQHwBQuIYKxQGMNFQOxKCosMUAAPQKVA07QXwjgQPgOGCcJcAuMuIQlNgO4TDJwCcdxjhHLxhaIdgII6SJKnYOJYxyYpymqUsSBwGpGlaSojl6SuhnGRJbGxhZ-HYDAFDwZZ9lBS4gmhaJLnQJJbnyUpUAAO44JwKhPLYKCaVAYDYHAYAqMABQAISTGZUAhHFhrfC+2BlLgcBBCCRIEFAAAML4AKzWElzmuc4IVGcuVxNaFCVxXxdkggZs1yZMI7ylx0VrCCISopeVTZZ5+7PAERm4GVtXUEJTliRlWxLMA3xwAEGjfGw24qAgcDmRVVWOIUIBQA2uABBgmgqb8KnnV1UDfDhJRCQEhSFHDMz8J09A5Q5kQ5foulpSsTESDlkk0kiGhEgAPvKdbk8pRMPelZO48plODvohMSMTzUFJaCDsx5ElETzykAJLmUErCfeZYTlXASBIKwITFCpvl8KwsgwxSeWsK9qg9dAwC5aUnCaOMNAQIUSDkqOi3RQdR3c81p2Y9A8YNvcIMXVdN2+etxnW0AA)

It's not perfect, but I'm extremely surprised it inferred the properties as literal.

**Comment by jcalz** [comment] 2020-09-28 13:05
Duplicate of or strongly related to #30680

**Comment by midzdotdev** [comment] 2023-01-11 16:04
Yep, `const` generics have now been implemented. I believe this issue can safely be closed.

https://github.com/microsoft/TypeScript/pull/51865

**Comment by mmkal** [comment] 2023-01-12 11:37
Great news! Thank you for pointing that out @midzdotdev

**Closed** 2023-01-12 11:36 UTC
Labels: Suggestion, Awaiting More Feedback
