### ISSUE TITLE
Type narrowing with "in" operator and closure results in an "any" type 

### ISSUE THREAD

**Issue by jdufresne** [microsoft/TypeScript#53913] opened 2023-04-19 15:35 UTC
# Bug Report

Example code:

```ts
const keys = ["b"];

type A = {
  b?: boolean;
};

function f(a: A): void {
  keys.map((key) => {
    if (key in a) {
      const c: never = a[key];
    }
  });
}
```

### 🙁 Actual behavior

```
test.ts:10:13 - error TS2322: Type 'any' is not assignable to type 'never'.

10       const c: never = a[key];
               ~
```

### 🙂 Expected behavior

```
test.ts:10:13 - error TS2322: Type 'boolean' is not assignable to type 'never'.

10       const c: never = a[key];
               ~
```

We can deduce that because the key ("b") is in the variable "a", `a[key]` must be a boolean.

**Comment by jcalz** [comment] 2023-04-19 18:22
You didn't fill out the issue template completely; could you edit to do that?

This is behaving as designed and there's no bug; if we interpret this as a feature request then it's a duplicate of #43284 (awaiting more feedback) or #48149 (declined).

**Closed** 2023-04-19 19:09 UTC
