### ISSUE TITLE
The behavior of class Parameter Properties changes with the es target

### ISSUE THREAD

**Issue by magic-akari** [microsoft/TypeScript#59589] opened 2024-08-11 10:30 UTC
### 🔎 Search Terms

- class
- constructor parameter
- useDefineForClassFields
- initialization

### 📌 Related issues
- #45995
- #55132

### 🕗 Version & Regression Information

- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play/?useDefineForClassFields=true&target=7#code/PTAEAEBcEMCcHMCmkBcpEGcBMAGXAoECAVw0QBFEAzASwDtEAxAe1gGEAbaDDRmxDgBMMaSLGKJ8AYy49QAFQCeAB0QBlKbBrLIABTjQAtskSxdsZqtiR+GUAG98oZ6CJQMAWhrw6rSS9AqZmZQAF5QSAALGgwAOgAjOABuJxcpZjoMMWIpSFYACmVieI4aKVBE2DRoOkUASgdUgOd0zOYORFiOZnh8gCJaOmgODkU+gBoI6Lig5jqUgIBffGX8BgB3BRV1TW09A2NIU3NLUxtMfoA3YYk++aA

### 💻 Code

```ts
// @target: es2020
// @useDefineForClassFields: true
class TypeScriptParameterProperties {
    // @ts-ignore
    foo = this.bar;
    constructor(public bar: any) {
        console.log("finally", this.foo);
    }
}

new TypeScriptParameterProperties("value");
```

```ts
// @target: esnext
// @useDefineForClassFields: true
class TypeScriptParameterProperties {
    // @ts-ignore
    foo = this.bar;
    constructor(public bar: any) {
        console.log("finally", this.foo);
    }
}

new TypeScriptParameterProperties("value");
```

### 🙁 Actual behavior

Different compilation options will output different values.

es2020: "finally",  "value" 
esnext: "finally",  undefined 

### 🙂 Expected behavior

They should output the same value.

### Additional information about the issue

- https://github.com/swc-project/swc/issues/9418
- https://github.com/swc-project/swc/pull/7055#issuecomment-1464897834

**Comment by magic-akari** [comment] 2024-08-11 11:01
Here is another example, which does not use ts-ignore and ts does not report any errors.

```TypeScript
// @target: es2020
// @useDefineForClassFields: true
class TypeScriptParameterProperties {
    foo = console.log("foo");
    constructor(public bar: any = console.log("bar")) {
        console.log("finally");
    }
}

new TypeScriptParameterProperties();
```
[Playground](https://www.typescriptlang.org/play/?useDefineForClassFields=true&target=7#code/PTAEAEBcEMCcHMCmkBcpEGcBMAGXAoECAVw0QBFEAzASwDtEAxAe1gGEAbaDDRmxDgBMMaSLGKJ8AYy49QAFQCeAB0QBlKbBrLIABTjQAtskSxdsZqtiR+GUAG98oZ6CrNmoALygpzOhmYORAA6DmZ4AAoAIjdmKIBKAG4nF19-MWIpSFYI5WIAIw4aKVB8uDRoOkUvHz8AoNDw6LLYBPiHFJdUusCQsMiY+mgODkUE5K6AX3xp-AYAdwUVdU1tPQNjSFNzS1MbTAikoA)

```TypeScript
// @target: esnext
// @useDefineForClassFields: true
class TypeScriptParameterProperties {
    foo = console.log("foo");
    constructor(public bar: any = console.log("bar")) {
        console.log("finally");
    }
}

new TypeScriptParameterProperties();
```

[Playground](https://www.typescriptlang.org/play/?useDefineForClassFields=true&target=99#code/PTAEAEBcEMCcHMCmkBcpEGcB2iAekAoECAVw0QBFEAzASxwDEB7WAYQBtoMMHbF2AJhjSRYJRAQDGnbqAAqATwAOiAMqTYtJZAAKcaAFtkiWDthMVsSHwygA3gVBPQ1Jk1ABeUJKZYMTdkQAOnYmeAAKACJXJkiASgBuR2cfP1ESSUgWcKUSACN2WklQPLg0aCwFT29ff0CQsKjS2Hi4+2TnFNqA4NCI6PpodnYFeKTOgF8CKYIcAHd5ZTUNLV19I0gTMwsTa0xwxKA)

The order in which they print out `foo` and `bar` is different.

**Comment by whzx5byb** [comment] 2024-08-11 11:49
Duplicate of https://github.com/microsoft/TypeScript/issues/45995.

**Closed** 2024-08-15 01:30 UTC
Labels: Duplicate
