### ISSUE TITLE
Type narrowing not working properly for unions in let declarations

### ISSUE THREAD

**Issue by lgenzelis** [microsoft/TypeScript#48038] opened 2022-02-25 13:59 UTC
# Bug Report

When you type a variable with a union type, typescript is too aggressive while narrowing it down. Specifically, it only considers assignments in the "main" flow, and ignores any other possibility.

### 🔎 Search Terms

let, type guard, type narrowing, never

### 🕗 Version & Regression Information

I've tried with different TS versions starting in `3.`, and it happens in all of them. I also tried with nightly (v4.7.0-dev.20220215)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/DYUwLgBAZg9jBcEDOYBOBLAdgcwgHwkwFcBbAIxFQgF4IAWAJgG4BYAKCiMwGMx0ZMEMgENUACgCUEAN7sI0ODQgByRstZsAvu3YjxEjQHpDCmEtUN1EYxHRQIAdxAQu3GCRIhMkMAAt0SAA0jiDKqM5QWCDsdhBiYACeAA4gMPawZtRZKigYOMpSsmzyGQB0WNzARAAmIEhiygAeBUzWJgAKqDApqIkqFVW1SMoQ1TB1hDCQII0BkAIQiSkqmCAAbpTKpezabEA)

### 💻 Code

```typescript
let foo: string | number = 42;
function bar() {
  foo = '42';
}

bar();
// foo = '42'; // if we uncomment this, we're fine
if (typeof foo === 'string') {
  foo.includes('x'); // TS Error: property 'includes' does not exist on type 'never'
}
```

### 🙁 Actual behavior

TS shouldn't be so eager to narrow the type to `never`. 

### 🙂 Expected behavior

Don't narrow unions based on assignments. Or, if it's not too hard to implement, do it only when you can be absolutely certain. I.e., no function after the assignment that caused the type narrowing.

**Comment by MartinJohns** [comment] 2022-02-25 14:04
Duplicate of #9998.

Assignments within closures are not recognized, so according to TypeScript the only value ever assigned is `42`, a `number`. You can prevent the narrowing upon assignment (which is intended) using a type assertion:

```typescript
let foo: string | number = 42 as string | number;
```

**Closed** 2022-02-25 18:40 UTC

**Comment by MartinJohns** [comment] 2022-02-25 18:44
You're probably the first one to actually read the issue after being linked to it.

**Comment by danny-does-stuff** [comment] 2024-05-15 17:23
I am currently switching from Flow to TS, and FWIW once I understood that Flow was taking the pessimistic approach, it rarely bothered me, even though most of my functions were pure. I guess it's just part of the learning curve of switching!
