### ISSUE TITLE
Promise type resolution with overloaded functions.

### ISSUE THREAD

**Issue by thealjey** [microsoft/TypeScript#51874] opened 2022-12-13 11:01 UTC
# Bug Report

TypeScript is not able to choose the right overload for a function passed as a callback to a `then` method of a promise object.

### 🔎 Search Terms

Promise
overload
type resolution

### 🕗 Version & Regression Information

As far as I can tell this not a regression.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/PTAEBcE8AcFNQJYGdQGMD2AnTtXgDaSg5Lr4BusAJqAIYpLiYIB2A5gNoC6AULAB7Qs4NOhaNQbdOhoBeUAEFstSADoAZpnQBbABQAiddP0BKANw8eICDHjJisUhWp0UAVxYBrFugDuLbgAaUCpHaARweHAAC3t8VngAI1hWNlB1DzwEMVp8QkRQlnAEVFy+QWFRcRFE2jk6X1oI0AAFLW1kWFUSMkoDI3RTVRjYFl0lTBUNdvMgA) (see .D.TS)

### 💻 Code

```ts
// type is correctly resolved as string[]
export const good = Array.from("foo");

// type is resolved as unknown[], despite this line being functionally identical
export const bad = await Promise.resolve("foo").then(Array.from);
```

### 🙁 Actual behavior

The types of `good` (`string[]`) and `bad` (`unknown[]`) are different.

### 🙂 Expected behavior

The types of `good` (`string[]`) and `bad` (`string[]`) are the same.

### 🤩 Ideal behavior in my subjective opinion

The type of both `good` and `bad` is `["f", "o", "o"]`.

**Comment by andrewbranch** [comment] 2022-12-19 18:26
Inference doesn’t perform overload resolution. It’s attempting to infer from `ArrayConstructor.from<T>(arrayLike: ArrayLike<T>): T[]`, and `string` is not assignable to `ArrayLike` of anything, so it falls back to `unknown` for `T`. Roughly a duplicate of most of these 24 “Design Limitation” issues, where you can find more discussion and explanation: https://github.com/microsoft/TypeScript/issues?q=is%3Aissue+inference+overload+resolution+label%3A%22Design+Limitation%22+is%3Aclosed+

**Closed** 2022-12-22 18:00 UTC
Labels: Duplicate
