### ISSUE TITLE
Problem with /* */

### ISSUE THREAD

**Issue by edvinv** [Microsoft/TypeScript#1725] opened 2015-01-19 13:41 UTC
There is a bug (TypeScript 1.4.1) in js code generation when new line is missing after end comment.

To reproduce create new ts project add foo.ts:
```typescript
/*
class Foo {
    foo() {
    }
}	*/
```
The generated js is:
```typescript
/*
class Foo {
    foo() {
    }
/*
class Foo {
    foo() {
    }
 
//# sourceMappingURL=foo.js.map
```
If there is new line after */ it works ok.

**Comment by Arnavion** [comment] 2015-01-19 16:35
Duplicate of #1714

**Comment by RyanCavanaugh** [comment] 2015-01-19 18:24
Workaround is to not have the `/` be the last character in the file

**Closed** 2015-01-19 18:24 UTC
Labels: Duplicate
