### ISSUE TITLE
Upgrading compiler to 2.6.1 breaks angular 4.3.6+material 2 application 

### ISSUE THREAD

**Issue by DariuszOstolski** [Microsoft/TypeScript#19713] opened 2017-11-03 12:36 UTC
I'm not 100% sure if this is a bug but I've upgraded compiler to 2.6.1 from 2.5.3 (this is angular 4.3.6 and material 2 application) no other component was upgraded at that time and after upgrade I have this error when running application in development mode:

```ReferenceError: collections_1 is not defined```

**Code**

```ts
import {Component, Input, OnDestroy, OnInit} from '@angular/core';
import {DataSource} from '@angular/cdk/collections';

export type CellFunctionType = (userData: any) => any;

export interface DcnDataTableColumn {
    columnName: string;
    header: string;
    cell: CellFunctionType;
    toolTip?: string;
    sort: boolean;
}

@Component({
    selector: 'dcn-data-table',
    templateUrl: './dcn-data-table.component.html',
    styleUrls: ['./dcn-data-table.component.css'],

})
export class DcnDataTableComponent implements OnInit, OnDestroy  {

    @Input('title') tableTitle: string;
    @Input() dataSource: DataSource<any> | null;
    @Input() columns: DcnDataTableColumn[];

    displayedColumns: string[];

    constructor() {

    }

     ngOnInit() {
        this.displayedColumns = this.columns.map(function(column) {
            return column.columnName;
        });
    }

    ngOnDestroy() {
        if (this.dataSource) {
            this.dataSource = null;
        }
    }
}

```
This is transpiled source code from previous version 2.5.3:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var core_1 = require("@angular/core");
var DcnDataTableComponent = /** @class */ (function () {
    function DcnDataTableComponent() {
    }
    DcnDataTableComponent.prototype.ngOnInit = function () {
        this.displayedColumns = this.columns.map(function (column) {
            return column.columnName;
        });
    };
    DcnDataTableComponent.prototype.ngOnDestroy = function () {
        if (this.dataSource) {
            this.dataSource = null;
        }
    };
    tslib_1.__decorate([
        core_1.Input('title'),
        tslib_1.__metadata("design:type", String)
    ], DcnDataTableComponent.prototype, "tableTitle", void 0);
    tslib_1.__decorate([
        core_1.Input(),
        tslib_1.__metadata("design:type", Object)
    ], DcnDataTableComponent.prototype, "dataSource", void 0);
    tslib_1.__decorate([
        core_1.Input(),
        tslib_1.__metadata("design:type", Array)
    ], DcnDataTableComponent.prototype, "columns", void 0);
    DcnDataTableComponent = tslib_1.__decorate([
        core_1.Component({
            selector: 'dcn-data-table',
            templateUrl: './dcn-data-table.component.html',
            styleUrls: ['./dcn-data-table.component.css'],
        }),
        tslib_1.__metadata("design:paramtypes", [])
    ], DcnDataTableComponent);
    return DcnDataTableComponent;
}());
exports.DcnDataTableComponent = DcnDataTableComponent;
```

And this is transpiled version from 2.6.1:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var core_1 = require("@angular/core");
var DcnDataTableComponent = /** @class */ (function () {
    function DcnDataTableComponent() {
    }
    DcnDataTableComponent.prototype.ngOnInit = function () {
        this.displayedColumns = this.columns.map(function (column) {
            return column.columnName;
        });
    };
    DcnDataTableComponent.prototype.ngOnDestroy = function () {
        if (this.dataSource) {
            this.dataSource = null;
        }
    };
    tslib_1.__decorate([
        core_1.Input('title'),
        tslib_1.__metadata("design:type", String)
    ], DcnDataTableComponent.prototype, "tableTitle", void 0);
    tslib_1.__decorate([
        core_1.Input(),
        tslib_1.__metadata("design:type", collections_1.DataSource)
    ], DcnDataTableComponent.prototype, "dataSource", void 0);
    tslib_1.__decorate([
        core_1.Input(),
        tslib_1.__metadata("design:type", Array)
    ], DcnDataTableComponent.prototype, "columns", void 0);
    DcnDataTableComponent = tslib_1.__decorate([
        core_1.Component({
            selector: 'dcn-data-table',
            templateUrl: './dcn-data-table.component.html',
            styleUrls: ['./dcn-data-table.component.css'],
        }),
        tslib_1.__metadata("design:paramtypes", [])
    ], DcnDataTableComponent);
    return DcnDataTableComponent;
}());
exports.DcnDataTableComponent = DcnDataTableComponent;

```
**Expected behavior:**
Upgrading compiler does not break application.

**Actual behavior:**
Console errors collection_1 is not defined

**Comment by ericmartinezr** [comment] 2017-11-03 12:57
https://github.com/angular/angular/issues/19587#issuecomment-337713553

**Comment by mhegazy** [comment] 2017-11-03 18:44
Seems like a duplicate of https://github.com/angular/angular/issues/19587

**Comment by DariuszOstolski** [comment] 2017-11-16 13:27
I think this issue can be closed then.

**Closed** 2017-11-16 17:29 UTC
Labels: Duplicate
