### ISSUE TITLE
"export default interface" does not compile

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#10411] opened 2016-08-18 14:33 UTC
This works
```ts
interface A {
   a: string;
} 
export default A;
```
but this does not:
```ts
export default interface A {
   a: string;
} 
```
>error TS1005: ';' expected.

Tooltip over the keyword `interface`:
>The name 'interface' cannot be found.

**Comment by kitsonk** [comment] 2016-08-18 14:39
Dupe of #3194, #3095 and discussed in #3917.

You should really [search for issues](https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue%20export%20default%20interface%20) before opening a new one.

**Closed** 2016-08-18 14:48 UTC
