### ISSUE TITLE
Typescript can't compile success while using some Symbol attributes

### ISSUE THREAD

**Issue by MSDimos** [Microsoft/TypeScript#20572] opened 2017-12-08 11:15 UTC
**TypeScript Version:**  2.6.2

**Code**

```ts
class Ite {

    [Symbol.toPrimitive](hint): number | string {
        switch (hint) {
            case 'number':
                return 100;
            case 'string':
                return "100";
            case "default":
                return "default";
            default:
                return null;
        }
    }
}
let ite: Ite = new Ite();

/*The following code hints the errors */
console.log(ite == 100);
console.log(ite + 100);
console.log(ite * 2);

```

**Expected behavior:**
JavaScript can run normally, and display the following content at the console
```
false
default100
200
```
but typescript can't compile success. And many of the rest of the ``` Symbol ``` attributes are not normally identified. Such as ``` Symbol.species ```.

**Comment by kitsonk** [comment] 2017-12-08 16:33
As the form noted, you need to provide a fully reproducible example.

You need to provide more basic information.  What is your `tsconfig.json` or what arguments are you passing in `tsc`.  When you say _can't compile success_ what errors are you getting?

**Comment by MSDimos** [comment] 2017-12-09 01:42
@kitsonk Thanks for your reply
This is my ```tsconfig.json```
```json
{
    "compilerOptions": {
        "target": "es2015",
        "module": "amd",
        "jsx": "react",
        "outDir": "./dist",
        "moduleResolution": "node"
    },
    "compileOnSave": true,
    "include": [
        "./*"
    ]

}
```
This is my ```package.json```
```json
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "typescript": "^2.6.2"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "tsc index.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

```
I added a command script in ```package.json```, and using ```npm run build``` to run ```tsc index.ts```.
and this is what error says
```
index.ts(3,6): error TS2304: Cannot find name 'Symbol'.
index.ts(19,13): error TS2365: Operator '==' cannot be applied to types 'Ite' and 'number'.
index.ts(20,13): error TS2365: Operator '+' cannot be applied to types 'Ite' and '100'.
index.ts(21,13): error TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.
```
But the code is in accordance with the ES6 specification, and it is reasonable that it shouldn't be wrong.
Thank

**Comment by mhegazy** [comment] 2018-01-10 21:02
Duplicate of https://github.com/Microsoft/TypeScript/issues/4538

**Closed** 2018-01-25 23:25 UTC
Labels: Duplicate
