### ISSUE TITLE
Intl.ResolvedDateTimeFormatOptions is missing properties

### ISSUE THREAD

**Issue by BPScott** [microsoft/TypeScript#45420] opened 2021-08-11 23:57 UTC
# lib Update Request

## Configuration Check

My compilation *target* is `ES2020` and my *lib* is `the default`.

## Missing / Incorrect Definition

`Intl.ResolvedDateTimeFormatOptions` - the type returned by calling `DateTimeFormat`'s `resolvedOptions` method - appears to be missing the following properties:

- `dateStyle`
- `timeStyle`
- `dayPeriod`
- `hourCycle`
- `fractionalSecondDigits`

It looks like these items (along with `calendar` and `numberingSystem`) were added to  [`es2020.intl.d.ts`'s `DateTimeFormatOptions`](https://github.com/microsoft/TypeScript/blob/08358f3380a64553b59496a4f8ec14de1d33e852/src/lib/es2020.intl.d.ts#L280-L288) however they were never added to `ResolvedDateTimeFormatOptions`.

It seems that `calendar` and `numberingSystem` are both present in [`es5.d.ts`'s `ResolvedDateTimeFormatOptions`](https://github.com/microsoft/TypeScript/blob/663b19fe4a7c4d4ddaa61aedadd28da06acd27b6/src/lib/es5.d.ts#L4348-L4363). Because of this I am unsure if the absent options should be added to `ResolvedDateTimeFormatOptions` in es5.d.ts or es2020.d.ts.

https://tc39.es/ecma402/#table-datetimeformat-resolvedoptions-properties is the spec table of possible returned properties

## Sample Code

[Sample TS playground](https://www.typescriptlang.org/play?target=7#code/MYewdgziA2CmB00QHMAUZYHcAEBJMALtPACICGBsAKgJYC2sAYiAE50WoDksYAtAKoBlTgBpsAb2wATCrEEEAnnABc2ThAAWrAp2wBfAJTwWsKNABusKQHkADgRrgIqIzMrylsAwChQkGAhIaBg4+ESksrQMzGwc3HxCohLYDgweKmpIYMi6hsamMJY29o6QLvCpcopwPr5OAYgo6Fh4hMTklFFMrOwEXDwCwmKSMgoACrAsjlKqnGBkLCwgmLlGJmZFdg5O5aMTUyBSPn5mgU0hreEd1PTdsX3xg0mSlemws1k5YloAriwAwgpgCpOBoAEwAFlW+Q2Vi2pWcRl+AKBNW8dX8cEawRaYXakVuMV6-QSQ2SADMWGRgNt5tBBLA-FISDRkDQCBBVABGfRrAoWOElHZGSnU2lkemM8DM1nsiAGIA)

```js
console.log(new Intl.DateTimeFormat('en-US', { dateStyle: 'short' }).resolvedOptions().dateStyle)
console.log(new Intl.DateTimeFormat('en-US', { timeStyle: 'long' }).resolvedOptions().timeStyle)

console.log(new Intl.DateTimeFormat('en-US', { dayPeriod: 'narrow' }).resolvedOptions().dayPeriod)
console.log(new Intl.DateTimeFormat('en-US', { timeStyle: 'long', hourCycle:'h24' }).resolvedOptions().hourCycle)

console.log(new Intl.DateTimeFormat('en-US', { fractionalSecondDigits: 1 }).resolvedOptions().fractionalSecondDigits)
```

The above lines throw type errors saying the various properies on `resolvedOptions` do not exist

## Documentation Link

https://tc39.es/ecma402/#table-datetimeformat-resolvedoptions-properties

**Comment by IllusionMH** [comment] 2021-08-12 00:37
Duplicate of #42577 which itself is duplicate of other issues.

**Comment by BPScott** [comment] 2021-08-12 01:09
This issue looks to be more thorough than #42577 - which does not mention the `dayPeriod` or `fractionalSecondDigits`.


#42577 has been marked as a duplicate of #35865 / #34399. In both cases that appears to be an incorrect diagnosis, as both of those issues are about improvements to `DateTimeFormatOptions`, NOT `ResolvedDateTimeFormatOptions`. 

- #35865 talks about strictening the types on `DateTimeFormatOptions`, changing them from `string` to specific values. This issue has been fixed as of TS 4.2 as [that interface now uses unions of strings for those values](https://github.com/microsoft/TypeScript/blob/v4.3.5/src/lib/es5.d.ts#L4332-L4346).
- #34399 talks about an omission of `hourCycle` from `DateTimeFormatOptions`. This issue has been fixed as of TS 4.2 when targeting es2020 per [this interface](https://github.com/microsoft/TypeScript/blob/v4.3.5/src/lib/es2020.intl.d.ts#L280-L288)

**Comment by IllusionMH** [comment] 2021-08-12 08:59
Yes, you are correct. Read by diagonal and missed that `ResolvedDateTimeFormatOptions` were not updated to match other options added to options.

Also looks like it's tricky question in which file definitions should go as https://github.com/microsoft/TypeScript/pull/42945 tries to "move" (in that case just removing) some of this properties of `DateTimeFormatOptions` to further versions.

**Comment by orta** [comment] 2021-09-08 09:44
I'm reasonably sure I've got all these covered and merged into main with in https://github.com/microsoft/TypeScript/pull/45647 - should be available in 4.5

**Comment by BPScott** [comment] 2021-09-08 15:49
Heya @orta,

I'm not sure if I'm reading that PR correctly but it looks like `DateTimeFormatOptions` was updated but I can't see any adjustments to `ResolvedDateTimeFormatOptions`, or any places where the return interface of resolvedOptions() got changed to something else.

**Comment by BPScott** [comment] 2021-09-16 06:43
Ping @orta, I've just tried on the [nightly build playground](https://www.typescriptlang.org/play?target=7&ts=4.5.0-dev.20210910#code/MYewdgziA2CmB00QHMAUZYHcAEBJMALtPACICGBsAKgJYC2sAYiAE50WoDksYAtAKoBlTgBpsAb2wATCrEEEAnnABc2ThAAWrAp2wBfAJTwWsKNABusKQHkADgRrgIqIzMrylsAwChQkGAhIaBg4+ESksrQMzGwc3HxCohLYDgweKmpIYMi6hsamMJY29o6QLvCpcopwPr5OAYgo6Fh4hMTklFFMrOwEXDwCwmKSMgoACrAsjlKqnGBkLCwgmLlGJmZFdg5O5aMTUyBSPn5mgU0hreEd1PTdsX3xg0mSlemws1k5YloAriwAwgpgCpOBoAEwAFlW+Q2Vi2pWcRl+AKBNW8dX8cEawRaYXakVuMV6-QSQ2SADMWGRgNt5tBBLA-FISDRkDQCBBVABGfRrAoWOElHZGSnU2lkemM8DM1nsiAGIA) and it still raises type errors.

I don't think this issue has been resolved as the types of `ResolvedDateTimeFormatOptions` don't seem to have been updated

**Comment by orta** [comment] 2021-09-16 08:52
Yep, I agree 👍🏻

**Closed** 2021-09-23 20:33 UTC
Labels: Bug, Help Wanted, Domain: lib.d.ts

**Comment by BPScott** [comment] 2021-09-23 20:45
Thanks @orta <3
