### ISSUE TITLE
type checking after instainceOf condition is working incorrectly

### ISSUE THREAD

**Issue by stepancar** [Microsoft/TypeScript#5522] opened 2015-11-04 09:56 UTC
this example works great

```javascript
function test(value: string[]| string){
	var result: string;
	if (value instanceof Array){
		result = value.join('');
	}
}
```
but this 
``` javascript
interface IFoo {
	value: string[] | string;
}

function bar(options: IFoo) {
	var result: string;
	if (options.value instanceof Array) {
		result = options.value.join('')
	}
}
```
property join does not exists on type string[] | string

i think i'ts compiler mistake

**Comment by kitsonk** [comment] 2015-11-04 10:26
I maybe wrong, but I don't think the type narrowing will work on complex types like that, I would suspect because it would over complicate what the compiler would have to keep track of, duplicating the complex type and then narrowing the one element of the type...  In order to get it to work, you should try something like:

```typescript
interface Foo {
  value: string[] | string;
}

function bar(options: Foo) {
  let result: string;
  const value = options.value;
  if (value instanceof Array) {
    result = options.value.join('');
  }
}
```

**Comment by stepancar** [comment] 2015-11-04 12:07
@kitsonk , thank you for your answer!
I agree that, this checking is more harder, but i think it's more usefull for developers. 
In your solution you added const value only for force compiler to check. I think it's not good idea

**Comment by mhegazy** [comment] 2015-11-04 17:42
looks like a duplicate of #4297

**Closed by mhegazy** 2015-11-04 17:42 UTC
