### ISSUE TITLE
Generic inference to unknown after using function arguments

### ISSUE THREAD

**Issue by MikeYermolayev** [microsoft/TypeScript#43371] opened 2021-03-25 08:59 UTC
# Bug Report

Hello  👋🏻
I'm facing some strange issue with Generics. Until I specify input arguments in function all generics are inferred correctly. But as soon as I mention argument in function the inference is broken. 

Thanks in advance for any help 🙏🏻

### 🔎 Search Terms

- generic is lost after specifying input arguments 
- typescript generic unknown after specifying arguments ([found this stackoverflow](https://stackoverflow.com/a/60807317/4280642) but not sure if it's the same case)

### 🕗 Version & Regression Information

typescript: 4.2.3
Also tried nightly build but the issue remains

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about __Generics_______

### ⏯ Playground Link
[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/C4TwDgpgBAwg9gOwRAxsOAnKBeKAeAKCmKgEEUUIBnKgFTgGsIECA+ACjjGCoC4oA3kRIBzCMHKUa9JgnYBLBGACuwfgJRwAJhH5VgGRSIC+ASn4AFDHAC28qhDyTqdRs1YBuYcQBuAQwAbeS0-YAhSVQALBSVVdQAzeQgArT4yChcZZjNLazsHPAEEPxtdKH1DBBNPAjMcVig-BBAvAk0EfSh25DRMfngkVHQsXBiwU3qoZQQdROQtAjbEHuH2IRIoMQkM6TcEfj8qEAQUKHYJ7Aa19Fl+AHIb5juzABpvKH8gkLCI4EiDo4nM4CRLJVJ1S6CKAAemhoJSaQEj325QMRmM7w2sI2ONxJAAegB+TEkDDiZQYBCCYqle4ARwA7hBnu8MWZFt0hpg1u8ts5drdGoDTmMLlckXt7sjnqYXjDoVBSghgPJEFBFCpgI0MCJlEqtQAjMl+BhUdUIeIQMknCDvT7BULhKIA44ikFJBEQhoCeVQeGpfjTBgIOAMlh430RqNEknEMnAClUoolMp3RnMjEbNmmRZAA)

### 💻 Code

```ts repro
type Connector = &lt;
    AccessToken
>(opts: {
    getAccessToken(input: {code: string}): Promise&lt;AccessToken>;
    validateAuth(input: {fields: AccessToken}): Promise&lt;{name: string}>;
}) => any;

const connector: Connector = (inp) => undefined

connector({
    getAccessToken: async () => ({token: 'token'}),
    validateAuth: async ({fields}) => { //fields: {token: string}
        //                  ^?
        return {name: 'qwe'}
    }
})

connector({
    getAccessToken: async (inp) => ({token: 'token'}), // mention input argument breaks inference
    validateAuth: async ({fields}) => { // fields: unknown
        //                  ^?
        return {name: 'qwe'}
    }
})


```

### 🙁 Actual behavior

`fields` inside `validateAuth` infer to unknown after using function argument in `getAccessToken`. Until I use arguments everything works OK

### 🙂 Expected behavior

Usage of function arguments inside `getAccessToken` should not affect Generic inference since they are statically type

**Comment by MikeYermolayev** [comment] 2021-03-25 10:23
Looks like the problem occurs only for methods in one options object.

As a workaround splitting them into two objects works OK.

```ts repro
type Connector = &lt;
    AccessToken
>(optsA: {
    getAccessToken(input: {code: string}): Promise&lt;AccessToken>;
}, optsB: {
    validateAuth(input: {fields: AccessToken}): Promise&lt;{name: string}>;
}) => any;

const connector: Connector = (inp) => undefined

connector({
    getAccessToken: async () => ({token: 'token'}),
    
}, {
validateAuth: async ({fields}) => { //fields: {token: string}
        //                  ^?
        return {name: 'qwe'}
    }
})

connector({
    getAccessToken: async (inp) => ({token: 'token'}), // mention input argument breaks inference
    
}, {
    validateAuth: async ({fields}) => { // fields: unknown
        //                  ^?
        return {name: 'qwe'}
    }
})


```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/C4TwDgpgBAwg9gOwRAxsOAnKBeKAeAKCmKgEEUUIBnKgFTgGsIECA+ACjjGCoC4oA3kRIBzCMHKUa9JgnYBLBGACuwfgJRwAJhH5VgGRSIC+ASn4AFDHAC28qhDyTqdRs1YBuAsYA0ULjyk6sLEAG4AhgA28lrhwBCkqgAWCkqq6gBm8hCRWnxkFC4yzGaW1nYOeAII4Ta6UPqGCCae3qY4rFDhCCBeBJoI+lADyGiY-PBIqOhYuKlg7didygg6WchaBP2IozPsQiRQYhKF0m4I-OFUIAgoUOyLnfvosvwA5C-Mb2Y+IVDefiEEWisXiiWASUu11u9wEWRyeTMHUEUAA9Kj4bl8gJPhcGgYjMY-od0YcyeSSAA9AD8xJIGHEygwCEENTq7wAjgB3CDfP5EsxbEbTTD7P7HZxnV5daF3eaPWG496476mPykuoIYDyRBQRQqYBdDAiZSaw0AIwZ4QYVD1CAyEAZtwgfwBgj+wJicQSyShNzlcOyWKRSxRpMxeX4KwYCDgXJYFLRqMTKagNLpxAZwCZLOqtXqb25vKJhwFpi2QA)

**Comment by ilogico** [comment] 2021-03-25 12:36
This issue might be related: [38264](https://github.com/microsoft/TypeScript/issues/38264).

**Comment by RyanCavanaugh** [comment] 2021-03-25 17:41
Our inference algorithm is based on doing a fixed number of passes to collect inference candidates (see also #30134 which proposes that we use an unbounded number of passes). In this case, the parameterless function is *non-context-sensitive*, meaning that its return type can be known ahead-of-time to not depend on the ultimate result of inference, so we're able to use its return type to collect an inference candidate.

The parameterful version is context-sensitive, because it has an unannotated parameter. *From the outside* we can see that this ultimately won't matter, but the inference process is not far enough along at this point to use that information, and thus delays collecting the return type as an inference candidate until later on at which point `AccessCode` has already been fixed to `unknown` due to a lack of covariant candidates.

The workaround in this case is to write `(inp: { code: string }) =>`.

**Comment by MikeYermolayev** [comment] 2021-03-25 19:46
wow, thanks for the detailed answer and the workaround

**Comment by jkillian** [comment] 2021-07-16 18:35
Thanks for the great explanation @RyanCavanaugh, very helpful! Ran into this exact issue today ([playground link](https://www.typescriptlang.org/play?ts=4.3.5&strict=true#code/C4TwDgpgBAkgdmArsAIgQ2GqBeKBvKAZwHsBbCAOUVIC4o5qAjCAJwG4oBfAKG9EigB5MMACWxOIQA8AFQB8OfNyhEIAGwgBjYMRZ0AFABMMaOvCSoTAShwKZbZVAgBHRGjWjQAMTgB+A6ZQMgA0UIx0MjbYCozExBpocA483ABmiHDa4nBQiIQQAMrqWjossnL6xCLZhHTCYhLS8lYRSiosEMCILDlVDZIAdPka2rr6eCTkVLRQAEwADJxWybwA9KtQAOKCgih0AO66ANaEUPsAFhA5wJcdAOSniVCipGAe2lD80Km6UAAGxkwfygiUM9GI-xcbg83jgf2C3HW-x+xGBolOml0HW0ahAUGIqU+4GgfwYpGYLD+3ExkmA+CgKK4ijyhWKoxY40cwxKugMgLQUQU4wZcTo-KGZEo1C4VgRSwciI2212B2OpwuV0+twgDxBOQgAA8wKJNJ4iQIfix-vzgaC9ZDXO5PCAfFSkX8UbM0RisSVcfjCV9-mSKVSaYQ6QRPUzcCyiiNSpyVNz2XyTGYEMh0JhBVBhZ6xSYJVNpUsESooU7YQFgoxc1hsI2wnLlmsNgAhACCewZaFEalOhH7V2A-o1121uqeLzeJrNQct1pMtrgYKef0rMJdcMVIuIAGZnqc-okQGHGpG94fOMz8vGeRy8Fy2aU0znbHmo3F94XMMWpaQMrlk4jpbj4NZ1h+DZNowLZsEAA)), and it was especially insidious because it silently introduced `any`s into the codebase without causing any compiler errors. Leaving a slightly simplified example here just in case it's useful for discussions/example use cases that could be improved. It'd be much less of a priority for me if it just introduced `unknown`s instead of `any`s, because that would be caught easily in other places at compile time:

```ts
type InputData = { someNum: number; }

type Options<T> = {
  selector: (data: InputData) => T;
  equalityFn?: (a: T, b: T) => boolean;
}

function useSelector<T>(options: Options<T>): T {
  return options.selector({someNum: 20});
}

// GOOD: works when there's an implict type for `data` and no `equalityFn`,
// `foo` is correctly of type `number`
const { foo } = useSelector({
  selector: (data) => ({ foo: data.someNum }),
});

// GOOD: works when there's an expicit type for `data` and an `equalityFn`
// `foo2` is correctly of type `number`
const { foo2 } = useSelector({
  selector: (data: InputData) => ({ foo2: data.someNum }),
  equalityFn: (a,b) => a === b,
});

// BAD: fails silently when there's an implicit type for `data` and an `equalityFn`
// foo3 is `any`
const { foo3 } = useSelector({
  selector: (data) => ({ foo3: data.someNum }),
  equalityFn: (a,b) => a === b,
});
```

**Comment by RyanCavanaugh** [comment] 2021-07-16 19:33
@jkillian that's a bug caused by the binding pattern (aka destructuring). I think it's reported already but can't find it at the moment - can you log a new issue?

**Comment by jkillian** [comment] 2021-07-16 20:24
@RyanCavanaugh, thanks, agreed after looking at it again that the `any` vs. `unknown` part of my above post is a different issue than this ticket about function arguments and inference. I've made the new issue for that here: https://github.com/microsoft/TypeScript/issues/45074. Please feel free to edit anything as necessary if I used wrong terminology anywhere (as is highly likely 😆).

**Comment by tannerlinsley** [comment] 2021-12-01 22:32
Closed #46977 (duplicate) for this one. We're trying to do get around this in our React Query library and it's definitely been weirding us out 😂 .  I think it's worth dropping in a quick snippet of our use-case for posterity:

```tsx
function useQuery<TQueryKey, TData>(_options: {
  queryKey: TQueryKey;
  queryFn: (context?: { queryKey: TQueryKey }) => TData;
  onSuccess: (data: TData) => void;
}) {}

const queryKey = ["test", 1, 2, { 3: true }]

// no context no cry
useQuery({
  queryKey,
  queryFn: (): number => 1,
  onSuccess: (data) => data.toFixed(),
});

// as soon as I use ctx, data is no longer of type number for onSuccess
useQuery({
  queryKey,
  queryFn: (ctx): number => 1,
  // Why is `data` of type `any`?
  onSuccess: (data) => data.toFixed(),
});
```

For now, we've dropped the proposal to adopt this syntax as the primary syntax in our API, but we would *really* love to make it happen in the future. Where should we go from here to help that happen?

**Comment by jkillian** [comment] 2022-04-25 17:57
I believe this is related to #47599 and is now fixed by #48538?

**Comment by Andarist** [comment] 2022-09-22 22:26
@RyanCavanaugh it seems that this got fixed by intra-inference improvements in 4.7, all reported playgrounds work:
- [@MikeYermolayev's case](https://www.typescriptlang.org/play?ts=4.7.4#code/C4TwDgpgBAwg9gOwRAxsOAnKBeKAeAKCmKgEEUUIBnKgFTgGsIECA+ACjjGCoC4oA3kRIBzCMHKUa9JgnYBLBGACuwfgJRwAJhH5VgGRSIC+ASn4AFDHAC28qhDyTqdRs1YBuYcQBuAQwAbeS0-YAhSVQALBSVVdQAzeQgArT4yChcZZjNLazsHPAEEPxtdKH1DBBNPAjMcVig-BBAvAk0EfSh25DRMfngkVHQsXBiwU3qoZQQdROQtAjbEHuH2IRIoMQkM6TcEfj8qEAQUKHYJ7Aa19Fl+AHIb5juzABpvKH8gkLCI4EiDo4nM4CRLJVJ1S6CKAAemhoJSaQEj325QMRmM7w2sI2ONxJAAegB+TEkDDiZQYBCCYqle4ARwA7hBnu8MWZFt0hpg1u8ts5drdGoDTmMLlckXt7sjnqYXjDoVBSghgPJEFBFCpgI0MCJlEqtQAjMl+BhUdUIeIQMknCDvT7BULhKIA44ikFJBEQhoCeVQeGpfjTBgIOAMlh430RqNEknEMnAClUoolMp3RnMjEbNmmRZAA) 
- [@jkillian's case](https://www.typescriptlang.org/play?ts=4.7.4#code/C4TwDgpgBAkgdmArsAIgQ2GqBeKBvKAZwHsBbCAOUVIC4o5qAjCAJwG4oBfAKG9EigB5MMACWxOIQA8AFQB8OfNyhEIAGwgBjYMRZ0AFABMMaOvCSoTAShwKZbZVAgBHRGjWjQAMTgB+A6ZQMgA0UIx0MjbYCozExBpocA483ABmiHDa4nBQiIQQAMrqWjossnL6xCLZhHTCYhLS8lYRSiosEMCILDlVDZIAdPka2rr6eCTkVLRQAEwADJxWybwA9KtQAOKCgih0AO66ANaEUPsAFhA5wJcdAOSniVCipGAe2lD80Km6UAAGxkwfygiUM9GI-xcbg83jgf2C3HW-x+xGBolOml0HW0ahAUGIqU+4GgfwYpGYLD+3ExkmA+CgKK4ijyhWKoxY40cwxKugMgLQUQU4wZcTo-KGZEo1C4VgRSwciI2212B2OpwuV0+twgDxBOQgAA8wKJNJ4iQIfix-vzgaC9ZDXO5PCAfFSkX8UbM0RisSVcfjCV9-mSKVSaYQ6QRPUzcCyiiNSpyVNz2XyTGYEMh0JhBVBhZ6xSYJVNpUsESooU7YQFgoxc1hsI2wnLlmsNgAhACCewZaFEalOhH7V2A-o1121uqeLzeJrNQct1pMtrgYKef0rMJdcMVIuIAGZnqc-okQGHGpG94fOMz8vGeRy8Fy2aU0znbHmo3F94XMMWpaQMrlk4jpbj4NZ1h+DZNowLZsEAA)
- [@tannerlinsley's case](https://www.typescriptlang.org/play?ts=4.7.4#code/GYVwdgxgLglg9mABCAzgUwIojQJwJ4A8AKlrngNJp4A0iRAIgIZSMB8AFAPpwAOsCKAFyIA3gChEiAI7Z8lPMJKyKVANwTpygGJhh7CAihoAHlAD8wkZrLzFpOVUQBfAJSIAvKzpMW6yQgBlEAgINBQhRHYAE2ZGRR9GN09EADc4GCj1V1EnMTEDMBQoawc8D0QAbQAiIyKq2gBGWgAmWisAZmEoHGxnAF08gHpBxDA4RAKjU1HxiHwxVExldnFJGRsqag11-B09F2EwEABbACNcDy8mjUDg0PC9GJYkryfGADooOC0YYzQo9guLaudRiYaIRgoRAoOAICFQgCSyHQEygxlob0QMChY0QABsEABzC5wYCIKB4HhoUYnc44RDAOD024hMIoBboex4FbbZTyLZrbS6SLQYwHGlnC7Ja6ScEAdQAFmVsYgAAZvVWIUnkynU1WMMB4VVmG5gIKsh6RN4vRBvT7fX7-QHAlyqIA)

The issue can be closed.

**Closed** 2022-09-26 22:11 UTC
Labels: Design Limitation

**Comment by layerok** [comment] 2024-09-26 07:16
So the order of properties is important when inferring

For example this works
```typescript
function createModule<RequestData, FormValues>(o: {
  values: FormValues;
  mapValues: (values: FormValues) => RequestData;
  onCreate: (data: RequestData) => void;
}) {}

createModule({
  values: {
     name: 2
  },
  mapValues: (values) => ({
    title: values.name
  }),
   onCreate: (data) => data.title.toFixed(), 
});
```
But this doesn't
```typescript
function createModule<RequestData, FormValues>(o: {
  values: FormValues;
  mapValues: (values: FormValues) => RequestData;
  onCreate: (data: RequestData) => void;
}) {}

createModule({
  onCreate: (data) => data.title.toFixed(), 
  values: {
     name: 2
  },
  mapValues: (values) => ({
    title: values.name
  }),
});
```

**Comment by Andarist** [comment] 2024-09-26 08:35
Yes, this is an existing limitation. Note that it isn't about properties but certainly, it's easier to run into this with object properties. Let's take a look at this example with positional arguments ([TS playground](https://www.typescriptlang.org/play/?ts=5.6.2#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXzDigxAFkdhkIQBGAHgCUQBHZEAZwwBFioAaeADEcMALYA1KBDbsAfAAoAUPHgA3KTIBcQkRI0c+y+KKgAHSdI7b56y+23CxFmQEp4AXlnwmrDt16GKngAwkQk1sC82j4y-hhQbp5qOFjAhi7aqinAANyKioQgxGQUVLRKKgDeRiqoUKIg2gBMgfAAvq02+uyJXvLVKirYGNSZ3QB0dQ2tbS6dkfG98AtQ48PUaziCWAAeIMDyc4oueYqgkLAIKOjYeARhJZTUTYwssTzxAo56dgpGtlodE5uq0Qg8IlFvG8-B8Eh4vFlUq0TOZutYAVYgT9XPCob5OLD0plsqdCsVyE8QE0KvABoMpo14C0jB0jPIVksVmssCMQJttnsDkcVF07Et+jV4OtGRj2JN6iAZkcToogA)):

```ts
declare function createModule1<RequestData, FormValues>(
  values: FormValues,
  mapValues: (values: FormValues) => RequestData,
  onCreate: (data: RequestData) => void,
): void;

// this works
createModule1(
  {
    name: 2,
  },
  (values) => ({
    title: values.name,
  }),
  (data) => data.title.toFixed(),
);

declare function createModule2<RequestData, FormValues>(
  values: FormValues,
  onCreate: (data: RequestData) => void,
  mapValues: (values: FormValues) => RequestData,
): void;

// this doesn't
createModule2(
  {
    name: 2,
  },
  (data) => data.title.toFixed(), // 'data' is of type 'unknown'.(18046)
  (values) => ({
    title: values.name,
  }),
);
```

As we can see, when context-sensitive functions are involved it always has been important to have the "producer" before the "consumer".
