### ISSUE TITLE
ESNext Set methods

### ISSUE THREAD

**Issue by Renegade334** [microsoft/TypeScript#58329] opened 2024-04-26 15:21 UTC
### ⚙ Compilation target

esnext

### ⚙ Library

esnext

### Missing / Incorrect Definition

The [ES2025 Set.prototype methods](https://github.com/tc39/proposal-set-methods) proposal has [now reached Stage 4](https://github.com/tc39/proposals/blob/main/finished-proposals.md), and has been rolled out in V8 and javascriptcore.

### Sample Code

```TypeScript
const a = new Set([1,2,3]), b = new Set([2,3,4]);

a.union(b);
a.intersection(b);
a.difference(b);
a.symmetricDifference(b);
a.isSubsetOf(b);
a.isSupersetOf(b);
a.isDisjointFrom(b);
```

### Documentation Link

https://tc39.es/proposal-set-methods/

**Comment by IllusionMH** [comment] 2024-04-26 15:24
Duplicate of #57228

**Closed** 2024-04-26 15:26 UTC
Labels: Duplicate
