### ISSUE TITLE
Add a Readonly factory type/wrapper that supports Maps/Sets

### ISSUE THREAD

**Issue by qc00** [microsoft/TypeScript#25230] opened 2018-06-26 17:25 UTC
## Search Terms

"readonly" type set

## Suggestion

Add something like below to the standard library

```typescript
type SmartRO<T> =
    T extends ReadonlyArray<any> | ReadonlyMap<any, any> | ReadonlySet<any> ? T :
    T extends Array<infer U> ? ReadonlyArray<U> :
    T extends Map<infer K, infer V> ? ReadonlyMap<K, V> :
    T extends Set<infer U> ? ReadonlySet<U> :
    Readonly<T>;
```

## Use Cases

Often people want to express in the type system that certain value is not to be modified by code accessing them. However, the `Readonly<T>` wrapper type [does not work](https://github.com/Microsoft/TypeScript/issues/16840) on Map and Set.

As a result, it's difficult to write a generic type that takes a mutable type argument and use a read-only version in the type body.

## Examples

```typescript
interface Validator<T> {
    isValid(x: SmartRO<T>);
}
```

## Checklist

My suggestion meets these guidelines:
* [✔] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [✔] This wouldn't change the runtime behavior of existing JavaScript code
* [✔] This could be implemented without emitting different JS based on the types of the expressions
* [✔] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment] 2018-06-26 17:50
This was one of the proposals we discussed when adding conditional type support. The general consensuses was that we need a new `readonly` type operator (tracked by https://github.com/Microsoft/TypeScript/issues/10725). the type duplication for every entity causes other problems in inference, overload resolution, and in type comparisons.

I am going to say this is a duplicate of https://github.com/Microsoft/TypeScript/issues/10725, since https://github.com/Microsoft/TypeScript/issues/10725 fulfills the underlying scenario.

**Comment by mhegazy** [comment] 2018-06-26 17:51
I should also add that you can always add this type in your project and use it as a wrapper for `Readonly`, but we do not have plans to add it to the standard library at the time being.

**Closed as completed** 2018-06-26 18:25 UTC
Labels: Duplicate
