### ISSUE TITLE
Object is possibly undefined within inner branches

### ISSUE THREAD

**Issue by aminpaks** [Microsoft/TypeScript#18639] opened 2017-09-21 09:38 UTC
I'm reporting a possible bug if hasn't been already reported.

**TypeScript Version:**  2.5.2
I tried with vscode latest version that ships with TS v2.5.2

**Code**

```ts
export type uniqueArrayPredicate<T> = (item: T, searchIn: T[]) => boolean;

export function uniqueArray<T>(first: T[], second: T[], predicate?: uniqueArrayPredicate<T>): T[] {
  if (predicate == undefined) {
    predicate = (item: T, searchIn: T[]) => searchIn.indexOf(item) === -1;
  }

  const unique = second.filter(item => predicate(item, first)); // <-- [ts] Object (predicate) is possibly 'undefined'.
  return first.concat(unique);
}
```

**Expected behavior:**
Once we check for truthy, the variable should remain valid/defined throughout all inner branches of the current scope.

**Actual behavior:**
Finds the variable as undefined within an inner branch of the scope!

**Comment by aminpaks** [comment] 2017-09-21 09:49
I bypassed it by this for now which is not great!:
```ts
const unique = second.filter(item => predicate && predicate(item, first));
```

**Comment by aluanhaddad** [comment] 2017-09-21 10:57
This appears to be a duplicate of #11498.

I would suggest that a more desirable workaround would be to create a local `const` or use a default parameter.
```ts
export function uniqueArray<T>(first: T[], second: T[], predicate?: uniqueArrayPredicate<T>): T[] {
  const p = predicate || (item: T, searchIn: T[]) => searchIn.includes(item);

  const unique = second.filter(item => p(item, first));
  return first.concat(unique);
}
```
or
```ts
export function uniqueArray<T>(first: T[], second: T[], predicate: uniqueArrayPredicate<T> = (item: T, searchIn: T[]) => searchIn.includes(item)): T[] {
  const unique = second.filter(item => predicate(item, first));

  return first.concat(unique);
}
```

**Comment by aminpaks** [comment] 2017-09-21 11:11
Would be great that it gets fixed :)

**Comment by aminpaks** [comment] 2017-09-21 11:15
Just a note, I think it's supposed to be negative to keep the unique ones `... => !searchIn.includes(item)...`

**Comment by mhegazy** [comment] 2017-10-05 18:18
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-05 18:18 UTC
Labels: Duplicate
