### ISSUE TITLE
Type guards ignored in closure

### ISSUE THREAD

**Issue by hgl** [microsoft/TypeScript#38755] opened 2020-05-24 09:59 UTC
**TypeScript Version:** 
v4.0.0-dev.20200523

**Search Terms:**
type guard closure
**Code**

```ts
let data: {[k: string]: string} = {}
function deleteOnClick() {
    let key = findKey()
    if (!key) {
        return;
    }
    let key2 = key
    window.addEventListener("click", () => {
        delete data[key2] // this is ok
        delete data[key] // type error, key can be null
    })
}

function findKey(): string | null {
    return null
}
```

**Expected behavior:**
`delete data[key]` contains no error
**Actual behavior:**
`delete data[key]` contains type error

**Playground Link:** 
https://www.typescriptlang.org/play/?#code/DYUwLgBAJghmMC4IG8DaBrJBnMAnAlgHYDmAutnkcQL4QC8K1AUAGYCuhAxmPgPaHQQoMCADyhAMLB8ndAAoAlCiYRVEYRHQgAnvQgsiUANI7FKtfhYQ5AQi3alyc2rW5wbXIQDcziMxca9gBMeva+AO6GvOEAdDBQUACiAG4ghGAAMvg4aSC4cgBEnNKyBQA01kp0AHzKLi5QQuAg0HAwGDpBpBAA9D0QYAAW2RAjvOi+DU0irfAd2t19A9oADi15uLy4FfYQnDACAEYthGzAwL7UCkzMrBzcfAIGhMamChQEJBAAPhCn53VXO5PH8zhdqEA
**Related Issues:**

**Comment by hgl** [comment] 2020-05-24 10:00
[Asked on SO](https://stackoverflow.com/questions/61983304/why-closure-makes-type-guard-be-ignored-in-typescript), doesn't get any response. Looks like a bug to me.

**Comment by MartinJohns** [comment] 2020-05-24 10:24
Duplicate of #9998.

**Comment by hgl** [comment] 2020-05-24 12:48
That issue

**Comment by hgl** [comment] 2020-05-24 16:12
On second thought this doesn’t seem to be a duplicate. key is locally defined, there is no way the addEventListener call can reset it back to null.

Not sure it’s flow control related.

**Comment by ahejlsberg** [comment] 2020-05-25 01:36
This is a design limitation. When a local variable is declared with `let` or `var` the control flow analyzer assumes that there could be subsequent assignments to the variable following the creation of a closure that references the variable, and therefore that narrowed types may no longer be correct. Your example works if you use `const` in the declaration of `key` because it is then known that there won't be any further assignments and that it is safe to carry the narrowed types into the closure.

We *could* theoretically do more work in the control flow analyzer to determine that there are no assignments to a particular variable following the creation of a function closure that references the variable, but it's not trivial.

**Closed** 2021-06-01 22:26 UTC
Labels: Design Limitation
