### ISSUE TITLE
Custom Typescript version for Yarn PNP Support - Visual Studio 2019

### ISSUE THREAD

**Issue by grbd** [microsoft/TypeScript#42121] opened 2020-12-27 00:13 UTC
# Suggestion

Hi,
So what I'm currently using at the moment is Visual Studio 2019.
I basically have an old webforms project and inside that a subdirectory of clientjs
this directory contains everything javascript related which inclues webpack, package.json, tsconfig.json
etc which all gets built via webpack (not the VStudio typescript compiler) to a javascript bundle in a subdir of wwwroot in the project.
So the javascript build is independent of MSBuild.

The problem I'm running into is getting the typescript intelisense to work.
This is due to the use of yarn's pnp system.
With yarn's pnp system it generates a .pnp.js file which acts sort of like a virtual node_modules directory
and maps back to zip files that can be located on a different or the same drive (a global cache on C: for example)

Normally the fix for this with "visual studio code" is to override the typescript bin setting "typescript.tsdk"
so that instead of the usual one it uses

  * .yarn\sdks\typescript\lib\
  * for the files tsc.js, tsserver.js, typescript.js

These act like a wrapper around the installed typescript installed via yarn's pnp system / package.json
to handle the virtual node_module directory via .pnp.js

What I've been trying to figure out is if there's an equivilent way of doing this with Visual Studio 2019
The closet I came was this thread

  * https://github.com/microsoft/TypeScript/issues/41355

which suggests a global setting via CustomTSServerLocation in the registry

But what I'd like to see is if there's a way to specify this in the csproj file instead (unless there's already a hidden setting for it)
i.e. could this be included into a future version of Studio 2019?
This includes both pre .Net Core (.Net WebForms) and .Net core (.Net 5) project types

## 🔍 Search Terms

yarn, 2019

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [y] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [y] This wouldn't change the runtime behavior of existing JavaScript code
* [y] This could be implemented without emitting different JS based on the types of the expressions
* [y] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [y] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

The ability to specify a custom typescript library at the .csproj level within Visual studio 2019

## 💻 Use Cases

The main motivation for this is that yarn's pnp package management system saves a lot of disk space vs the traditional npm node_modules approach due to it's way it handles the virtual node_modules directory via .pnp.js

**Comment by MartinJohns** [comment] 2020-12-27 08:35
Looks like a duplicate of #28289.

**Comment by grbd** [comment] 2020-12-27 09:58
In the case of 28289 that's looking into adding yarn2 support into the typescript compiler
For this I'm asking about something different in terms of specifying a wrapper for typescript within the Visual Studio 2019 IDE as a workaround instead. By specifying a different path for tsc.js, tsserver.js other than the normal one used.

**Closed** 2021-01-02 00:00 UTC
Labels: Question, Visual Studio
