### ISSUE TITLE
in 2.1.4, strictNullChecks make index types of nullable fields be never 

### ISSUE THREAD

**Issue by scottbessler** [microsoft/TypeScript#12747] opened 2016-12-08 07:42 UTC
**TypeScript Version:**  2.1.4

**Code**

```ts
function get<T, K extends keyof T, K2 extends keyof T[K]>(obj: T, propertyName: K, propertyName2: K2): T[K][K2] | undefined {
    const step1 = obj ? obj[propertyName] : undefined;
    return step1 ? step1[propertyName2] : undefined;
}

interface Org {
    admin?: User;
}
interface User {
    email?: string;
}

const o: Org = { admin: { email: 'foo' } };
const o2: Org = {};

console.log(get(o, 'admin', 'email'))
console.log(get(o2, 'admin', 'email'))
```

**Expected behavior:**

Expect to output:
```
foo
undefined
```

**Actual behavior:**
with strictNullChecks, fails to compile:
```
foo.ts(17,29): error TS2345: Argument of type '"email"' is not assignable to parameter of type 'never'.
foo.ts(18,30): error TS2345: Argument of type '"email"' is not assignable to parameter of type 'never'.
```

works without strictNullChecks:
```
foo
undefined
```

**Comment by mhegazy** [comment] 2016-12-08 17:44
Duplicate of #12651, #12723, and #12744.

fixed by https://github.com/Microsoft/TypeScript/pull/12770

**Comment by ahejlsberg** [comment] 2016-12-08 18:50
Actually, this isn't a duplicate, but more like a suggestion that we somehow permit indexed access types to work on types that include `undefined` and/or `null`. It would probably require a new type operator, e.g. `T!`, which removes `undefined` and `null` from the type of `T`. We could then say that when a truthy, undefined, or null check is applied to a type parameter `T`, we produce the type `T!` in order to record the knowledge that the type is not nullable.

Anyway, I'm going to reopen and change to a suggestion.

**Comment by scottbessler** [comment] 2016-12-08 19:31
Ah yeah i was wondering if this was expected behavior.

`T!` or somesuch would be great.

**Comment by RyanCavanaugh** [comment] 2020-07-21 22:35
Closing due to low feedback volume.

**Closed by RyanCavanaugh** 2020-07-21 22:35 UTC
Labels: In Discussion, Suggestion
