### ISSUE TITLE
Compiler output in parsable format e.g. JSON

### ISSUE THREAD

**Issue by robatwilliams** [microsoft/TypeScript#46340] opened 2021-10-13 08:54 UTC
# Suggestion

## 🔍 Search Terms

tsc, compiler, parsable, json, output

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Command line option for `tsc` that causes the log to be output in a parsable format such as JSON.

This could be as minimal as `--json` option, or as much as ESLint's [pluggable formatter](https://eslint.org/docs/user-guide/command-line-interface#-f---format) feature - although I don't have a need for that.

## 📃 Motivating Example

Allows writing scripts to act on compiler output, without needing to get into get into the complication of using the [compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API).

## 💻 Use Cases

I'm working on improving the type safety of a partially/weakly-typed codebase, by e.g. typing more files and strengthening existing types (replacing `any`/`$Object`, making properties required etc.). This causes a large amount of new errors across the codebase. Fixing many of these causes more errors to be identified. If I attempt to fix all these in one PR (that doesn't break the build) then I'll be at it forever and my branch will conflict with colleagues' changes.

Thus I need to add lots of ignores/expect-errors, so I have a script to do that. This would be cleaner/easier if I didn't have to parse the compiler's text output.

**Comment by MartinJohns** [comment] 2021-10-13 09:34
Duplicate of #31566.

**Comment by robatwilliams** [comment] 2021-10-13 21:28
Thanks. Even with that search operator, I'm not sure I'd have found it amongst the hundreds.

That issue was closed citing the availability of the compiler API which would allow someone else to write a tool for this. The same point as mine was then made - that the API is low-level.

I'm not sure anyone would have the motivation to write and maintain said tool, given it's much quicker and easier to parse the text output (it seems designed for easy parsing/matching) especially if (like me) you only need to use it once.

That said, I would understand if this is closed for the same reason - if you need it enough, write it yourself.

**Closed** 2021-10-16 18:00 UTC
Labels: Duplicate
