### ISSUE TITLE
Stop breaking code after every minor update

### ISSUE THREAD

**Issue by hmzlam** [microsoft/TypeScript#41300] opened 2020-10-28 09:15 UTC
We are tired from updating projects after every minor update, would you please make typescript compatible with old code, we are forced to downgrade versions to make things work, we think that typescript should add feautures without breaking existing files.
so would you please keep typescript stable until big version update

**Comment by ericmorand** [comment] 2020-10-28 09:24
Does TypeScript not adhere to Semantic Versioning?

**Comment by kitsonk** [comment] 2020-10-28 10:06
Duplicate of #14116

**Comment by MartinJohns** [comment] 2020-10-28 10:50
Just consider every "minor" update a major one.

The alternative would be that instead of minor-version updates they just always release major-version updates and nothing was won, except that we soon have TypeScript 35.0.0.

**Closed** 2020-10-28 15:42 UTC
Labels: Duplicate
