### ISSUE TITLE
problem publishing ts app using web deploy 

### ISSUE THREAD

**Issue by lucamorelli** [Microsoft/TypeScript#7322] opened 2016-03-01 17:05 UTC
Hi, I have a problem publishing an asp.net 4 app using angular, ts 1.8 from visual studio.
Since with ts 1.8 is possible to add a tsconfig file in asp.net 4 projects too, I added it and configured it to create a single output file this way

```
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "target": "es5",
    "inlineSourceMap": true,
    "inlineSources": true,
    "outFile": "Scripts/application.js"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}

```
All works fine until I try to deploy to an azure app service using web deploy: added it, configured, but when I try to deploy I have this error:

`Copying file App\Maintenance.js to obj\Debug\Package\PackageTmp\App\Maintenance.js failed. Could not find file 'App\Maintenance.js'. 
`

This is one the ts files that are compiled in the single file 'application.js'.
If my ts installation is not broken, looks like web deploy still continues to look inside the msbuild project settings for the deployment settings of ts files, but adding tsconfig.json file this changes, and when tsconfig file is present typescript project settings are disabled.

Proof of this is that if I rename the tsconfig file, reapply settings via project settings and try to deploy, everything works fine.

Is this normal?

**Comment by mhegazy** [comment] 2016-03-01 18:05
this is caused by the same issue as https://github.com/Microsoft/TypeScript/issues/7247

**Comment by paulvanbrenk** [comment] 2016-04-11 21:27
This is fixed in the [nightly NuGet packages](https://www.myget.org/feed/typescript-preview/package/nuget/Microsoft.TypeScript.MSBuild) in builds after 1.9.0-beta-20160411-1.

**Closed by paulvanbrenk** 2016-04-11 21:27 UTC
Labels: Bug
