### ISSUE TITLE
Array spread of tuple type yields error when used to call matching function.

### ISSUE THREAD

**Issue by rzvc** [Microsoft/TypeScript#24241] opened 2018-05-18 03:38 UTC
**TypeScript Version:**  2.9.0-dev.20180516

**Search Terms:**  tuple rest spread function

**Code**

```ts
function f(a: number, b: string) : void
{
}

let params : [number, string] = [10, 'test'];

f(...params);
```

**Expected behavior:**
I expect that to compile without any errors.

**Actual behavior:**
error TS2556: Expected 2 arguments, but got 0 or more.

**Comment by s-ve** [comment] 2018-05-18 06:47
duplicate of #4130 ?

**Comment by rzvc** [comment] 2018-05-18 07:14
Looks like it, yes.

This issue came up when thinking about #24240, which has applications in forwarding rest parameters.

**Closed** 2018-06-02 19:56 UTC
Labels: Duplicate
