### ISSUE TITLE
Error with `interface` but not with `type` for indexed property

### ISSUE THREAD

**Issue by rdeneau** [Microsoft/TypeScript#19865] opened 2017-11-09 09:37 UTC
**TypeScript Version:**  2.6.0

**Code**

```ts
interface I<K extends string, P> {
    [key in K]?: P; // Error: 1. A computed property name must directly refer to a built-in symbol.
                    //        2. A computed property name must be of type 'string', 'number', 'symbol' or 'any'.
}

type T<K extends string, P> = {
    [key in K]?: P; // No Errors !?
};
```

**Expected behavior:**
Same error for both definitions, `I` and `T`.

**Actual behavior:**
Error only with the `interface`.

**Comment by aluanhaddad** [comment] 2017-11-09 15:23
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/18299

**Comment by kreba** [comment] 2017-11-10 11:32
For other n00bs like me: Note that there is a difference between "indexed" and "mapped" types.
See http://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types

**Closed** 2017-11-27 18:38 UTC
Labels: Duplicate
