### ISSUE TITLE
Extend auto-generated constructor field initializers to support #private fields

### ISSUE THREAD

**Issue by blixt** [microsoft/TypeScript#42550] opened 2021-01-29 12:05 UTC
# Suggestion

Currently, TypeScript allows `contructor(private readonly text: string) {}` in a class to automatically assign `this.text` inside of the generated constructor.

It follows that `constructor(readonly #text: string) {}` would automatically assign `this.#text` inside of the generated constructor, with one notable change: the parameter name would need to change to `text` since parameter names cannot use the `#` character.

This also allows a more transparent path for a refactor function to change `private text` to `#text` with minimal TypeScript source changes in cases where existing field initializers exist in constructors.

## 🔍 Search Terms

class private field initializer constructor

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## Playground

As you'll see in the emitted JavaScript code below, it almost works already, but the constructor parameter name has to change to `text` instead of `#text` – the rest of the emitted JavaScript is correct.

https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99&module=1&ts=4.2.0-dev.20210129#code/MYGwhgzhAEAyD2BzRBTATtA3gWAFDWmHgDsIAXNAV2DPjQAo0UwATEkAT2gGIyUAPMgC5o5NAEtiiAJRYAvnjwEQSAJJl6snPgKESEeCBQA6FYnpkAFuIjHeAstKXQFuV3iKky0ENAC80MQoAO5wSKgMAESWKCAq0MF0ICwAhJFOuCCmahrSQA

**Comment by MartinJohns** [comment] 2021-01-29 12:42
Duplicate of #36282. Used search terms: `constructor private field`

**Closed** 2021-01-29 13:03 UTC
