### ISSUE TITLE
Leverage generic type identification

### ISSUE THREAD

**Issue by nugaon** [microsoft/TypeScript#48799] opened 2022-04-21 11:25 UTC
# Bug Report

### 🔎 Search Terms

inferring, infer, generic type, generic, user-defined type guard, conditional type

### 🕗 Version & Regression Information

- This is a bug in all versions of TypeScript

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220421#code/C4TwDgpgBAsghgSwHYBUoF4oHIBWB7ACySygB9sATPCLAKFEigDU4AbAVwhQB40IAPYBCQUAzrESoAfBih9BwsdnxESAfiijgAJ2QBzKAC45UAUJHisVGlA1J2AWwBGEbUahIIAN1f1w0ACUIYHZtVF5TBQsJZBQZTHlzJVxCYlsoAFVkYABmACYAQW1tOBB3RMVLa3VM7IAOIpKy408fbVpaADN2JABjYAQ8JCgEUXhYiLNKmOkACi82TmMegGskPAB3JAAaKAdJFH9jFABKYwWOaFGTAG9aKAeobWDQ4YvODHRMfdj-WgBfDrdPoDIZQIRaSZRJTjOYrCAgY67d4QYwsS48OJnKBBEJhTEyO6PEadWajWEoWbwkC7FKqE4nKBE4mPXpDLQeWQogB0ojArAQwFmWCwjIA9GLmIsuLwZNd1sARkhOq5nhQoBsCMITNc1pthk4ygADalG+4sh7PPHDTwbWpIXKFYqlWbiyW414EkbiBVKlXFCDqzXatC69Zbc0PQGAh5AA)

### 💻 Code

```ts
type MainT = 'john' | 'doe'
type ValueT<T extends MainT> = T extends 'john' ? string : T extends 'doe' ? number : never
type ReturnT<T extends MainT> = T extends 'john' ? Uint32Array : T extends 'doe' ? Uint8Array : never

function isMainT<T extends MainT>(value: unknown, mainType: T): value is T {
    return value === mainType
}

function test<T extends MainT>(key: T, value: ValueT<T>): ReturnT<T> {
    if(isMainT(key, 'john')) {
        const n = value.split('') // ValueT<T> is not inferred when T is known by using typeguard on `key`
        return new Uint32Array() // ReturnT<T> is not inferred when T is known
    }
}
```

### 🙁 Actual behavior

When the type of the main generic type (`MaintT`) is identified by a User-Defined Type Guard function, the other conditional types based on this main type are not identified and TS keeps it generic.  

### 🙂 Expected behavior

`ReturnT<T>` and  `ValueT<T>` became inferred after T has been identified

**Comment by andrewbranch** [comment] 2022-04-21 18:20
Duplicate of https://github.com/microsoft/TypeScript/issues/33912 and https://github.com/microsoft/TypeScript/issues/35873

**Closed** 2022-04-24 18:00 UTC
Labels: Duplicate
