### ISSUE TITLE
Static class fields can lead to runtime errors

### ISSUE THREAD

**Issue by millsp** [microsoft/TypeScript#42901] opened 2021-02-20 17:32 UTC
# Bug Report

It is permitted not to initialize a `static` field:

```ts
class Foo {
    static bar: string
}

const baz = Foo.bar // inferred string

console.log(typeof baz) // is undefined
```

### 🔎 Search Terms

static class field property undefined error assigned

### 🕗 Version & Regression Information

This bug has always been here, as far as I checked (3.3.3).

- This is a crash
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Class.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/MYGwhgzhAEBiD29oG8BQ0PQgFzNglsNAEZgBOAXFtmfgHYDmqAvqqsPHTiWAF7QBeOIgB0pMtAD0k6rUZsOXeCACmIkPAYAKbAE8ADivgAzHrwCUUmQFc6AExXH6Ku0A)

### 💻 Code

```ts
class Foo {
    static bar: string
}

const baz = Foo.bar // string

console.log(typeof baz) // undefined
```

### 🙁 Actual behavior

`undefined` values will certainly lead to a program crash.

### 🙂 Expected behavior

Either to be suggested to assign a default value or to mark the field as optional.

**Comment by MartinJohns** [comment] 2021-02-20 18:47
Duplicate of #27899. Search terms: `static undefined`

**Closed** 2021-02-25 18:00 UTC
Labels: Duplicate
