### ISSUE TITLE
TypeScript/JS primitive types don't appear in intellisense

### ISSUE THREAD

**Issue by atg** [microsoft/TypeScript#30184] opened 2019-03-01 21:05 UTC
If I type `function() { new Map<strin` inside a function I would expect to get `string` at the top of intellisense but instead I get `stringify` in node mode or `String` in browser mode, and `string` is not there.

As far as I can tell it is not configuration dependent, you can observe the same issue in the [typescript playground](https://www.typescriptlang.org/play/index.html).

If there is no `function() {` then `string` DOES appear. Here's a table of what works and doesn't work:

* Works: `type T = strin`
* Works: `new Map<strin`
* Works: `let foo: strin`
* Works: `function() { type T = strin`
* **Fails**: `function() { new Map<strin`
* **Fails**: `function() { new Array<strin`
* **Fails**: `function() { new Array<numbe`
* **Fails**: `function() { new Array<boolea`
* Works: `function() { let foo: strin`
* Works: `if (window) { new Map<stri`
* Works: `for (let x of []) { new Map<strin`
* **Fails**: `() => new Map<strin`
* Works: `function foo<T>() { } foo<strin`
* **Fails**: `function foo<T>() { foo<strin`
* Works: `class { x: Map<strin`
* Works: `class { x = new Map<strin`
* Works: `function() { 1 as Map<strin`
* Works: `{ foo() { new Map<strin`
* **Fails**: `{ foo: function() { new Map<strin`
* **Fails**: `class { foo() { new Map<strin`

- VSCode Version: 1.31.1 and monaco
- OS Version: ancient macos

Steps to Reproduce:

1. create new .ts or .js file
2. type `function() { new Map<strin`

Does this issue occur when all extensions are disabled?: Yes

**Comment by AlCalzone** [comment] 2019-03-02 14:46
I think this is #29769

**Comment by atg** [comment] 2019-03-02 14:56
As far as I can tell this is fully reproducible, I get exactly the same results in both vscode and the typescript playground. It's interesting that it works if you use the shorthand syntax `{ foo() { new Map<strin` but if you use the longhand syntax `{ foo: function() { new Map<strin` it fails. I have no idea what the significance of that is but maybe it means something to somebody.

**Comment by rbuckton** [comment] 2019-08-09 23:40
I'm currently having trouble reproducing this. Is this issue purely related to system performance (i.e. do the cases that fail above persist if you type something like `function () { new Map<`, then wait a few seconds before typing `str`? If the types show up, then this may be due to the copy of the editor buffer that the TypeScript service has may not be up to date with the actual editor buffer in vscode. 

@mjbvz: This may be due to something out-of-sync between vscode and the TypeScript language service, as I've seen similar hard-to-reproduce issues regarding incorrect completions for members in a system under heavy load.

**Comment by AlCalzone** [comment] 2019-08-10 07:36
@rbuckton are you sure this is not https://github.com/microsoft/TypeScript/issues/29769 (which has been closed in the meantime)?
In any case it does NOT seem related to performance as I first thought. The primitive types were missing from auto completion at certain locations.

**Comment by rbuckton** [comment] 2019-08-12 21:31
This does appear to be a duplicate of #29769.

**Closed by rbuckton** 2019-08-12 21:31 UTC
Labels: Bug, Duplicate
