### ISSUE TITLE
getApplicableRefactors returns "Install missing types package" quickfix

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19378] opened 2017-10-20 18:14 UTC
**TypeScript Version:**  2.6.1-insiders.20171019

**Code**

In a empty project with a `package.json` that includes `lodash` but not `@types/lodash`. Try writing an import:

```ts
import _ from 'lodash'
```

Request quickfixs on `'lodash'`

**Bug**

`getApplicableRefactors` is also returning a quick fix here for `Install missing types package`

```
Trace  - 11:13:01 AM] Sending request: getApplicableRefactors (51). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/src/test.ts",
    "startLine": 1,
    "startOffset": 15,
    "endLine": 1,
    "endOffset": 23
}
[Trace  - 11:13:01 AM] Response received: getApplicableRefactors (51). Request took 2 ms. Success: true 
Result: [
    {
        "name": "Install missing types package",
        "description": "Install missing types package",
        "actions": [
            {
                "description": "Install '@types/lodash'",
                "name": "install"
            }
        ]
    }
]
[Trace  - 11:13:01 AM] Sending request: getCodeFixes (52). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/src/test.ts",
    "startLine": 1,
    "startOffset": 15,
    "endLine": 1,
    "endOffset": 23,
    "errorCodes": [
        2307
    ]
}
[Trace  - 11:13:01 AM] Response received: getCodeFixes (52). Request took 2 ms. Success: true 
Result: [
    {
        "description": "Install '@types/lodash'",
        "changes": [],
        "commands": [
            {
                "type": "install package",
                "packageName": "@types/lodash"
            }
        ]
    }
]
```

**Comment by mjbvz** [comment] 2017-10-20 18:22
I've added a workaround for this on the VS Code side but believe this should be addressed for 2.6.1. @mhegazy and @andy-ms Do you agree?

**Comment by andy-ms** [comment] 2017-10-20 20:53
We intentionally exposed this both as a refactor and a quick fix. If a user has `--noImplicitAny` disabled they will see only the refactor because they will have no compile errors. (That might be a good reason to surface implicit-any problems as "info" even if `--noImplicitAny` is disabled.)
Is it a problem if they both appear? Should we add code to the refactor to do nothing if we think this will also show up as a quick fix?

**Comment by mjbvz** [comment] 2017-10-20 20:58
Yes, this causes us to show the same code action twice, once from the quickfix for the error and once from the refactoring.

I believe that this is a quickfix and should not be returned as a refactoring. We previously used to send compute quickFix requests to TS even if there were no errors in the currently selected code, but disabled this for performance reasons in TS 2.4. Should we look into enabling this again?

**Comment by andy-ms** [comment] 2017-10-20 21:04
The problem is that it is not a compile error to import from an untyped package unless the user has `--noImplicitAny` enabled. We want implicit-any users to still be able to take this action even if there aren't any errors to be fixed.

**Comment by mjbvz** [comment] 2017-10-20 21:08
Yes that's what I'm trying to say. We currently don't even call `getCodeFixes` if there are no errors in the selected code:

```ts
	public async provideCodeActions(
		document: TextDocument,
		range: Range,
		context: CodeActionContext,
		token: CancellationToken
	): Promise<Command[]> {
		const file = this.client.normalizePath(document.uri);

		// This part was added when we picked up TS 2.4		
		const supportedActions = await this.getSupportedActionsForContext(context);
		if (!supportedActions.size) {
			return [];
		}

		const args: Proto.CodeFixRequestArgs = {
			...vsRangeToTsFileRange(file, range),
			errorCodes: Array.from(supportedActions)
		};
		const response = await this.client.execute('getCodeFixes', args, token);
		return (response.body || []).map(action => this.getCommandForAction(action, file));
	}
```

We can remove the size check so that we still call `getCodeFixes` even if there are no error codes.

**Comment by andy-ms** [comment] 2017-10-20 21:17
If you ask for code fixes and there are no errors, we'll return an empty response, since there's nothing to fix. (The TS implementation of code fixes (`getCodeFixesAtPosition` in `services.ts` iterates over error codes.)

**Comment by mjbvz** [comment] 2017-10-20 21:22
If we want to support the no implicit any case, I propose we change the getCodeFix to support empty error code requests.  If that change would be too complex for 2.6, we can ship with the no implicit any case not being supported yet and look into handling it in a future release. However I feel that we need to remove this quick fix from the `getApplicableRefactors` response for 2.6

**Comment by mhegazy** [comment] 2017-10-20 21:36
@mjbvz do you happen to have `--strict` in your project? or did you get this config file from `tsc --init` (which adds `--strict`)? 

If so, i think i have a fix for this issue.

**Comment by mjbvz** [comment] 2017-10-20 21:59
No, my tsconfig was:

```
{
    "compilerOptions": {
        "target": "ES6",
        "allowJs": true
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

**Comment by andy-ms** [comment] 2017-10-20 22:28
Longer-term solution might be #19392.

**Comment by mhegazy** [comment] 2017-10-20 23:47
I am unable to reproduce this locally with the setup mentioned above with 1.18-insiders and latest TS.

@andy-ms , seems from your comments, you understand the issue here. can you elaborate on how i can reproduce this locally?

**Comment by andy-ms** [comment] 2017-10-21 00:19
I don't get the quickfix at all in insiders -- didn't think that feature was in yet? Also, @mjbvz mentioned having added a workaround.
But from what I can tell, he is getting an error at the import for "lodash" because his module resolution setup is wrong; we provide a quickfix since the module import failed, but we probably shouldn't. We also provide a refactor because he doesn't have `--noImplicitAny` enabled. So we are providing duplicate actions (except, he already added a workaround into vscode).

**Comment by mhegazy** [comment] 2017-10-21 00:44
aah.. now i see. why do we have the quick fix associated with `            Diagnostics.Cannot_find_module_0.code` ? it should only be associated with `Diagnostics.Could_not_find_a_declaration_file_for_module_0_1_implicitly_has_an_any_type.code`.. or am i missing something?

**Comment by andy-ms** [comment] 2017-10-21 00:54
That's exactly what #19394 does.

**Comment by mhegazy** [comment] 2017-10-23 04:35
Sorry, was stuck trying to understand the issue and did not look at the change.

**Comment by mhegazy** [comment] 2017-10-24 17:02
Fixed by  #19394.

**Comment by mjbvz** [comment] 2017-12-08 19:44
The original issue here was not addressed and the difference in semantics between quick fixes and refactorings is causing problems on our side (see https://github.com/Microsoft/vscode/issues/37288)

I still would like install @types to be returned only as a quick fix. See my comment on the PR for more info: https://github.com/Microsoft/TypeScript/pull/19394#issuecomment-338358455

**Comment by mhegazy** [comment] 2018-01-11 01:07
We are working on adding a new non-error diagnostic category, and moving all these refactoring to quick fix only. this should address the problem.

**Closed by mhegazy** 2018-01-11 01:08 UTC
Labels: Bug, Fixed
