### ISSUE TITLE
React.__spread has been removed in React 15.x

### ISSUE THREAD

**Issue by darthtrevino** [Microsoft/TypeScript#7964] opened 2016-04-08 17:15 UTC
**TypeScript Version:** 
1.8.9

React.__spread has been deprecated for a while, and has been removed in 15.0. 
(https://github.com/facebook/react/commit/a142fd257803a218b5b9b2e76c327f0421b9b8b6)

When upgrading a typescript project to React 0.15, an error is shown that `React.__spread is not defined` when using spread props.

It looks like it'll be turned into a warning instead soon(https://github.com/facebook/react/commit/fc1cfb6225f5c3af6843515363db63ed3dcbb824), but it's advisable to migrate tsx transformations from using `React.__spread` to using `Object.assign`

**Comment by RyanCavanaugh** [comment] 2016-04-08 17:23
Duplicate of #7270

**Closed by RyanCavanaugh** 2016-04-08 17:23 UTC
Labels: Duplicate
