### ISSUE TITLE
want a type operator that converts a function type to the type of one of its parameters

### ISSUE THREAD

**Issue by fc01** [Microsoft/TypeScript#19125] opened 2017-10-12 07:46 UTC
```ts

//Type A ----> Type B

type A = (state: string, action: any) => string
type B = string


//SyntaxError
type GetB<K extends (state: S, action: any) => S, S ???? > = S 
type xxx = GetB<A>  


//right
const getB = <S>(f: (state: S, action: any) => S) => ({} as S)
let b = getB({} as A) //string
```

**Comment by jcalz** [comment] 2017-10-12 18:07
I think a little prose would be helpful for people trying to understand what you're asking.  

If I read you correctly, you want a [type operator](https://github.com/Microsoft/TypeScript/issues/16392) that converts a function type to the type of one of its parameters.  That's not currently possible, although #6606 would presumably let you do this:

```ts
type Param1<T extends Function> =
  typeof (null! as <P=never>(f: (p1: P, ...rest: any[]) => any) => P)(null! as T);
type xxx = Param1<A>
```

So this is either a duplicate of #6606 or a new request that could be tracked in #16392, maybe?  Not sure.

**Comment by mhegazy** [comment] 2017-10-27 17:11
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-27 17:11 UTC
Labels: Needs More Info
