### ISSUE TITLE
Suggestion: Use npm dist-tag to install v1.4 stable by default instead of v1.5 alpha

### ISSUE THREAD

**Issue by teppeis** [Microsoft/TypeScript#2650] opened 2015-04-07 08:31 UTC
Now `npm install typescript` installs v1.5.0-alpha, but most users need stable v1.4.x.
Because v1.5 has breaking changes and is not stable yet.

npm provides dist-tag command for this purpose.

> [dist-tag | npm Documentation](https://docs.npmjs.com/cli/dist-tag)

`npm` itself uses dist-tag to [pre-release](https://github.com/npm/npm/releases) next version as `next` tag.
It would be nice for TypeScript to publish v1.5.0-alpha.x as `next` tag and keep v1.4.x in `latest` tag before v1.5 stable is published.

If TypeScript uses dist-tag, it's possible to pre-release every LKG as alpha version (#964). It helps meta-TypeScript library development.

**Comment by basarat** [comment] 2015-04-07 09:31
:+1:

**Comment by vvakame** [comment] 2015-04-07 09:46
:+1:

**Comment by DanielRosenwasser** [comment] 2015-04-07 15:18
I'd call it `stable` for 1.4.x and `next` or `canary` for 1.5.x-yyyy, but this seems like a good idea.

**Comment by mhegazy** [comment] 2015-04-07 17:12
@billti  can we update the 1.5-alpha with the tag

**Comment by billti** [comment] 2015-04-07 17:51
We can certainly do that.  I want to be sure we're aware of the consequences though. It does mean 1.5.0-alpha (indeed any prerelease if we make this the norm) will get much less usage.

I'd also note that any packages that have taken a dependency, unless they explicitly take a dependency on the prerelease tag, will **not** get a version that has a prerelease tag (such as -alpha).  See https://github.com/npm/node-semver/pull/99/files#diff-04c6e90faac2675aa89e2176d2eec7d8R76 

I do get the benefits, just making sure we're aware of the drawbacks too (and where this isn't an issue already)

**Comment by teppeis** [comment] 2015-04-09 03:57
@DanielRosenwasser

> I'd call it stable for 1.4.x

The default version is `latest` by npm spec.

> f) a <name> that has a "latest" tag satisfying (e)
> [install | npm Documentation](https://docs.npmjs.com/cli/install)

**Comment by DanielRosenwasser** [comment] 2015-04-09 04:21
@teppeis gotcha, thanks for pointing that out.

**Comment by billti** [comment] 2015-04-16 23:32
I didn't see any further arguments as to why choose one strategy over the other.  As outlined, if a package.json has a dependency on TypeScript, it will NOT install a version with a pre-release tag anyway (unless it specifies the pre-release version).

As for breaking changes - if these are by design, then they will also be in the "final" 1.5 when it ships, so the fact this is pre-release doesn't matter.  If they are bugs, then we'll fix them and push an update if impactful enough.

Closing for now.  Will reopen and reconsider if there is a stronger case for changing the tagging.

**Closed by billti** 2015-04-16 23:32 UTC
Labels: Bug

**Comment by teppeis** [comment] 2015-04-16 23:53
@billti I agree with you about v1.5-alpha, because it has bean released.
And then, I wish earlier v1.6-alpha (every LKG if possible) were pre-released as `next` tag...
It has benefits clearly: meta-TypeScript libraries can refer to it in their alpha package.json (instead of reference to this huge git repo) and users can try implemented features soon.

**Comment by watilde** [comment] 2015-04-17 00:22
+1
> And then, I wish earlier v1.6-alpha (every LKG if possible) were pre-released as next tag...

**Comment by jasonwilliams200OK** [comment] 2015-04-24 02:08
Please read the full post at: https://github.com/Microsoft/TypeScript/issues/2898.

@billti, as mentioned in my post at https://github.com/Microsoft/TypeScript/issues/2898, you can easily fix it by running the following two commands:

```bash
# optionally cd into/typescript-source-directory
npm dist-tag add typescript@1.4.1 latest
npm dist-tag add typescript@1.5.0-alpha alpha
```

takes about 23 seconds on an average ADSL connection :smile:
BTW, you can fix it just now, without waiting for next release.

**Comment by jasonwilliams200OK** [comment] 2015-05-22 05:52
Please reopen this issue. Semver seems to be ignored once again with 1.5.2-beta.

Can anyone please explain what is the hold up on running the commands from my previous comment? The current way is totally against the npm docs and semver principles:

* https://docs.npmjs.com/misc/semver
* https://docs.npmjs.com/cli/dist-tag
* https://docs.npmjs.com/cli/tag

The npm distribution tags are different than github pre-release tags and npm is GH-tag agnostic, unless you are installing the package from "GitHub slug" `npm install Microsoft/typescript` (which is super slow, requires git to be present in PATH, doesn't work behind various proxy servers).

There is only **one** absolute correct way of doing it, that is what every major package vendor is doing: the right way, as per the docs and conventions. 

Again, this issue needs to be reopened and requires a serious revisit. 

@othiym23, do you have any better (magical) way to convince people on following the laws of semver? :)

**Comment by othiym23** [comment] 2015-05-22 07:02
> As outlined, if a package.json has a dependency on TypeScript, it will NOT install a version with a pre-release tag anyway (unless it specifies the pre-release version).

While this is true, running either `npm install typescript` or `npm install --save[-dev] typescript` will get `latest`, which means that people setting up new packages can end up depending on prerelease versions without explicitly opting into them.

@jasonwilliams200OK
What the TypeScript team is doing here isn't an abuse of semver: they're assigning versions to TypeScript that conform to whether changes are breaking, feature, or patch, and they're using prerelease versions (which semver makes somewhat unwieldy on purpose) as a way to test out new releases. I don't think there's anything wrong with that.

I'm not the semver police :rotating_light: (well, OK, maybe I am, a little), but I can talk about the npm CLI team's experiences with using prerelease versions, which is that we found them unwieldy. Prereleases are more or less orthogonal to release lines (like `latest` and `next`), and rather than being complementary, I've found it very confusing to try to combine the two. Lots of practical questions pop up: if you're testing a release candidate as a prerelease, how do you sign off on it as the final release? Do you deal with `alpha`, `beta`, etc, or do you just use "pure" semver prelease versions like `1.3.5-0.1`? How many dist-tags / release lines do you need? How does all this interact with branches in your DVCS? Should you even try? How do you keep everything correlated? The complexity starts compounding pretty fast, and I'm not sure it brings much in the way of benefits.

Ultimately, what turned out to be simplest for npm was to just have a `latest`, a `next`, and then create other dist-tags for other major versions as we work on releasing them, and give up on caring about having new major or minor versions get released as 16.0.0 or 52.4.0. Version numbers are cheap, and what's most important is that when somebody runs `npm install mypackage`, by default they get the version of your package that you, as maintainers, think is most appropriate for use by the package's consumers.

To give an example, we've been steadily working towards the release of `npm@3`. As soon as we have all of npm's tests passing on the `multi-stage` branch, we're going to consider that version of npm ready for wider testing. What version will we be publishing it as? `npm@3.0.0`, even though we fully expect that the version of `npm@3` that will eventually become npm's `latest` in a month or two will be more like `3.0.7` (or even `3.2.3`). Keeping things restricted to the basic semver triplets makes for a much simpler release story when you try to figure out what was going on with your project sometime down the road.

But that's all my opinion, and the TypeScript team should do what makes the most sense for them and their maintenance and release process. Ultimately, semver is a pretty flexible framework, and while it's by definition prescriptive, treating it primarily as a means of describing what's in a particular package version (instead of trying to use it to control how that package is received) will help keep things simple.

:police_car:

**Comment by billti** [comment] 2015-05-22 17:04
> Can anyone please explain what is the hold up on running the commands from my previous comment?

Because we haven't decided that we want to do this.

> ..what's most important is that when somebody runs `npm install mypackage`, by default they get the version of your package that you, as maintainers, think is most appropriate for use by the package's consumers.

Agreed.

For existing features, these aren't really 'pre-releases'.  We run thousands of baseline tests, and millions of lines of real project code through our compiler before we push out __any__ release in order to catch issues and avoid breaking existing code as much as we can.  Any issues that get through are either 'design-tweaks' (i.e. will be in the final release unless we get heavy feedback against it), or something that slipped through all our testing and we want to catch ASAP (and will push a point release for if warranted).  For both of these reasons we want as much adoption as possible, and as other projects have observed, any version which is not the `npm install mypackage` default gets very little adoption.

Pre-releases also often contain new language features we are iterating on.  Again, this shouldn't break existing projects (that wouldn't have been able to use them already), but are an opportunity for developers to experiment with our new developments - hence the pre-release version.  (Note: We do recognize this workflow may be less than ideal, and are considering an 'experimental' flag to enable features in progress, rather than using 'prerelease' versions, going forward.  No final plans yet though).

I get the desire for purity of process, but pragmatically, getting the feedback from broad adoption of a pre-release (which __has__ been heavily tested for breaking changes, which new projects can opt out of by __not__ commiting a package.json with the pre-release tag, and existing projects with a TypeScript dependency __won't__ get with 'npm install' by default), is preferable to shipping the final release with issues that could have been found earlier with broader community usage and feedback.

**Comment by teppeis** [comment] 2015-07-28 14:55
Finally, nightly build is published. Thanks!
http://blogs.msdn.com/b/typescript/archive/2015/07/27/introducing-typescript-nightlies.aspx

**Comment by jasonwilliams200OK** [comment] 2015-07-29 02:21
Thanks for the headsup @teppeis!
Now we can see the available distribution tags by running:

```cmd
npm dist-tag list typescript
```

which is currently outputting:

```powershell
latest: 1.5.3
next: 1.6.0-dev.20150728
```

which means you have:

```powershell
# for v1.5.3 (exact), these options:
npm install typescript

npm install typescript@latest

npm install typescript@1.5.3  # semver major.minor.patch

npm install typescript@1.5    # semver major.minor, take the latest patch

npm install typescript@1      # semver major, note that in npm semver, anything after hyphen
                              # marks the version as pre-release, such as; 1.6.0-dev... 
                              # specifying only major version ignores the pre-release and
                              # considers highest non-hyphened as latest stable version (v1.5.3).

# for v1.6
npm install typescript@next

npm install typescript@1.6.0-dev.20150728    # need to enter the exact version because
                                             # typescript@1.6.. branch is not stabled yet,
                                             # hence considered non-existent.
```
