### ISSUE TITLE
Suggestion: tsconfig.json support multiple configurations.

### ISSUE THREAD

**Issue by zengfenfei** [Microsoft/TypeScript#11172] opened 2016-09-27 07:59 UTC
I want to generate both **es5** and **es6** versions of my TS project into different directories. But current **tsconfig.json** seems  to support only one configuration. I suggest that **tsconfig.json** supports configuration like this(similar to _webpack.config.js_):
```json
[
    {
        "compilerOptions": {
            "outDir": "./build/es5",
            "target": "es5"
        }
    },
    {
        "compilerOptions": {
            "outDir": "./build/es6",
            "target": "es6"
        }
    }
]
```

**Comment by kitsonk** [comment] 2016-09-27 08:48
Essentially a dupe of #9876 which is the solution for complex configuration setting in a complex project.

**Comment by mhegazy** [comment] 2016-09-28 01:00
As noted by @kitsonk, configuration inheritance (i.e. using `extends` in a tsconfig.json file to inherit configurations) would be the solution here. you can use it if you are using `typescript@next`.

With that, you would have a master `tsconfig.json` file, and a set of overrides, `tsconfig.es6.json` and `tsconfig.es5.json`, etc.. you call the compiler on the override files, so `tsc --p tsconfig.es6.json`.

hope that helps.

**Closed by mhegazy** 2016-09-28 01:00 UTC

**Comment by zengfenfei** [comment] 2016-09-28 02:09
@mhegazy Thanks, it works for me.
