### ISSUE TITLE
Array.isArray type guard does not match arrays with readonly modifiers

### ISSUE THREAD

**Issue by crizzis** [microsoft/TypeScript#55238] opened 2023-08-02 10:16 UTC
# Bug Report

`Array.isArray`, when used on a type union, does not result in a positive type guard match on array types that are declared `readonly`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about  'array', 'readonly'

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBBCcQQ0MwAUVWDEQC0gADVHBQGNJ3KAALygABEAAkYNAMOB4GRonzFBTBPB3AERcwABS0+mM9ysygc9wASmCKhwzQ8ZC8iHFzmB7BoXzcZmY7AYzEg-Fg0HUiQ58D0Ii8fLpDKZgj5SWxfPADlQAHJhAA5SASPlBFQAeS+ZHegmdWkgR1QjgUrmkeFATjNOmGWH0KAQiGhwkuNok4uiIgMHGxCyYrA4PCCJUUJVQ7UqZDITGTZGT0gAVpBYDReZNuI1oMWqZROMwANoAXVAAB9QABvUA6BjQdiQfJXVAbkYAXwA3KAVKWvRWlyvi4gpvpK2juGrdFMSUAc3BzU9z0va8KlHcdJxnOcF1ALdI2TeJGEwJAGEjHdH3JRoqVAZBYngVxeSVDICCtGC4LwCcp1necdR5AA+Y8wJlOVIAVeBlQAQlgsc8ACIQhKYJUzwvSAWIAMlkyDpICKTLx1fD7yAA)

### 🙁 Actual behavior

After testing a `readonly T[] | V`-typed variable with `Array.isArray()`, acessing `V`-exclusive properties without a cast still yields an error, as the LHS of the union type is not ruled out.  ('Property does not exist on type readonly T[]')

In contrast, `T[] | V` - typed variables don't have this problem. 

### 🙂 Expected behavior

The behaviour should be consistent for both `readonly` and non-`readonly` variants

**Comment by crizzis** [comment] 2023-08-02 10:25
Suggested solution: 

`interface ArrayConstructor {
    new(arrayLength?: number): any[];
    new <T>(arrayLength: number): T[];
    new <T>(...items: T[]): T[];
    (arrayLength?: number): any[];
    <T>(arrayLength: number): T[];
    <T>(...items: T[]): T[];
    isArray(arg: any): arg is any[] | readonly any[];
    readonly prototype: any[];
}`

**Comment by fatcerberus** [comment] 2023-08-02 12:19
Duplicate of https://github.com/microsoft/TypeScript/issues/53395, in which this is considered to be working as intended and I disagree 😄

**Comment by RyanCavanaugh** [comment] 2023-08-02 17:59
Filing this under the "People generally say TypeScript should be more strict but specifically want possibly-wrong but convenient answers" folder 😉

**Comment by fatcerberus** [comment] 2023-08-02 20:33
@RyanCavanaugh FWIW this issue is actually a good example of when it's more or less impossible for TypeScript to be sound - given how TypeScript works, `x is T` is fundamentally making an assertion about a type's *structure*, whereas `Array.isArray()` is a *nominal* check.  There's an impedance mismatch there that can't really be reconciled[^1], [hence your observation here](https://github.com/microsoft/TypeScript/issues/53395#issuecomment-1480364068).

[^1]: ...without introducing real nominal types anyway, but that's an entire can of worms unto itself.

**Closed** 2023-08-05 01:30 UTC
Labels: Duplicate
