### ISSUE TITLE
VS 2015 Update 1 RC crash 

### ISSUE THREAD

**Issue by videege** [Microsoft/TypeScript#5718] opened 2015-11-19 19:07 UTC
After installing Update 1 RC, I now cannot open any project that contains TypeScript files.  I thought my TypeScript extension might be out of date, but I still experience the crash after updating to the latest extension version.  My activity log has the following entries:

```
  <entry>
    <record>893</record>
    <time>2015/11/19 18:56:21.855</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part &quot;Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.SemanticClassificationTaggerProvider&quot;. ---&gt; System.MissingMethodException: Method not found: &apos;Void Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject..ctor(Boolean)&apos;.&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.AbstractAsyncClassificationTaggerProvider..ctor(TaskHandler taskHandler, IForegroundNotificationService notificationService, FormatMappingChangedWatcher formatMappingChangedWatcher, IEnumerable`1 asyncListeners)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.SemanticClassificationTaggerProvider..ctor(TaskHandler taskHandler, IForegroundNotificationService notificationService, FormatMappingChangedWatcher formatMappingChangedWatcher, ISemanticChangeNotificationService semanticChangeNotificationService, TypeScriptSemanticClassificationMap classificationMap, IEnumerable`1 asyncListeners)&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.DelegateServices.&lt;&gt;c__DisplayClass2_0`1.&lt;As&gt;b__0()&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;   at System.Lazy`1.LazyInitValue()&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)</description>
  </entry>
  <entry>
    <record>894</record>
    <time>2015/11/19 18:56:21.858</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part &quot;Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.SyntacticClassificationTaggerProvider&quot;. ---&gt; System.MissingMethodException: Method not found: &apos;Void Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject..ctor(Boolean)&apos;.&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.AbstractAsyncClassificationTaggerProvider..ctor(TaskHandler taskHandler, IForegroundNotificationService notificationService, FormatMappingChangedWatcher formatMappingChangedWatcher, IEnumerable`1 asyncListeners)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.SyntacticClassificationTaggerProvider..ctor(TaskHandler taskHandler, IForegroundNotificationService notificationService, FormatMappingChangedWatcher formatMappingChangedWatcher, TypeScriptSyntacticClassificationMap classificationMap, IEnumerable`1 asyncListeners)&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.DelegateServices.&lt;&gt;c__DisplayClass2_0`1.&lt;As&gt;b__0()&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;   at System.Lazy`1.LazyInitValue()&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)</description>
  </entry>
  <entry>
    <record>895</record>
    <time>2015/11/19 18:56:21.859</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part &quot;Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider&quot;. ---&gt; System.MissingMethodException: Method not found: &apos;Void Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject..ctor(Boolean)&apos;.&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider..ctor()&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.DelegateServices.&lt;&gt;c__DisplayClass2_0`1.&lt;As&gt;b__0()&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;   at System.Lazy`1.LazyInitValue()&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)</description>
  </entry>
  <entry>
    <record>896</record>
    <time>2015/11/19 18:56:26.890</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part &quot;Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.SemanticClassificationTaggerProvider&quot;. ---&gt; System.MissingMethodException: Method not found: &apos;Void Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject..ctor(Boolean)&apos;.&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.AbstractAsyncClassificationTaggerProvider..ctor(TaskHandler taskHandler, IForegroundNotificationService notificationService, FormatMappingChangedWatcher formatMappingChangedWatcher, IEnumerable`1 asyncListeners)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.SemanticClassificationTaggerProvider..ctor(TaskHandler taskHandler, IForegroundNotificationService notificationService, FormatMappingChangedWatcher formatMappingChangedWatcher, ISemanticChangeNotificationService semanticChangeNotificationService, TypeScriptSemanticClassificationMap classificationMap, IEnumerable`1 asyncListeners)&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.DelegateServices.&lt;&gt;c__DisplayClass2_0`1.&lt;As&gt;b__0()&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)</description>
  </entry>
  <entry>
    <record>897</record>
    <time>2015/11/19 18:56:26.890</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part &quot;Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.SyntacticClassificationTaggerProvider&quot;. ---&gt; System.MissingMethodException: Method not found: &apos;Void Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject..ctor(Boolean)&apos;.&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.AbstractAsyncClassificationTaggerProvider..ctor(TaskHandler taskHandler, IForegroundNotificationService notificationService, FormatMappingChangedWatcher formatMappingChangedWatcher, IEnumerable`1 asyncListeners)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.SyntacticClassificationTaggerProvider..ctor(TaskHandler taskHandler, IForegroundNotificationService notificationService, FormatMappingChangedWatcher formatMappingChangedWatcher, TypeScriptSyntacticClassificationMap classificationMap, IEnumerable`1 asyncListeners)&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.DelegateServices.&lt;&gt;c__DisplayClass2_0`1.&lt;As&gt;b__0()&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)</description>
  </entry>
  <entry>
    <record>898</record>
    <time>2015/11/19 18:56:26.890</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part &quot;Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider&quot;. ---&gt; System.MissingMethodException: Method not found: &apos;Void Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject..ctor(Boolean)&apos;.&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider..ctor()&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.DelegateServices.&lt;&gt;c__DisplayClass2_0`1.&lt;As&gt;b__0()&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)</description>
  </entry>
```

**Comment by mhegazy** [comment] 2015-11-19 19:26
in Add/Remove programs, what version of TypeScript do you have installed?

**Comment by mhegazy** [comment] 2015-11-19 19:27
the error indicates that the latest version of TS was not installed. can you share your setup logs?

**Comment by mhegazy** [comment] 2015-11-19 19:27
//cc: @yuit

**Comment by videege** [comment] 2015-11-19 20:00
In Add/Remove programs I have TypeScript Tools for Microsoft Visual Studio 2015 1.5.3.0 and 1.6.3.0 installed.

**Comment by mhegazy** [comment] 2015-11-19 20:34
OK, so this means that you installed Update 1 but not the TS that matches it (1.7.*), the error you are getting is because some platform APIs changed in Update 1, and your old TS extension did not know about them.

Now the question is how you system ended up in this situation. can you share your install logs from VS Update1? these should be under %temp% and will have the prefix "dd_",  if you sort by date modified you should see a cluster around the time you installed the update, and these are the ones we would be interested in. feel free to email us directly (mhegazy at Microsoft dot com).

**Comment by yuit** [comment] 2015-11-19 23:08
@videege also it will be great if you can run the following tool http://aka.ms/vscollect

The link will download an exe called Collect.exe. Put Collect.exe into %temp% and run it there. After it finishes, you will see vslog.zip and if you could share it with us that will be great !

**Comment by videege** [comment] 2015-11-19 23:34
@yuit I will try to get my installation logs to you tomorrow (already left work for the day).  From what I recall I had no option pre-setup to select anything about Web Tools (I just downloaded the updater from http://go.microsoft.com/fwlink/?LinkId=626599 and hit "Install").

**Comment by yuit** [comment] 2015-11-20 01:46
@videege thanks. I will wait for you log and I will let you know more what I find out

**Comment by mhegazy** [comment] 2015-11-26 00:24
@videege any news about the logs?

**Comment by yuit** [comment] 2015-11-30 17:09
@videege I will am going to close this bug for now. If you still run into an issue again, please feel free to reopen the bug.And feel free to send us the log. Thanks!

**Comment by gwicksted** [comment] 2015-12-02 16:37
I ran into the same issue (cannot resolve):
* The web tools were checked.
* Tried manually changing the project file TypeScript version to 1.7 (from 1.6) = no luck.
* Tried installing the 1.7.4 package and hit repair = no luck.
* Using "Programs and Features" to remove "Typescript Tools for Microsoft Visual Studio 2015 1.5.4.0" as well as 1.6.3.0 and 1.7.4.0.
* Re-installed 1.7.4.0 using "TypeScript_Full.exe" = no luck
* Noticed an update in VS to TypeScript tools (Extensions and Updates) - says my current version is 1.5.4.0 and the new version is 1.7.4.0 so I attempted to installed this.
* Installer will not continue - says Visual Studio 2015 Update 1 was already found on this computer (disabled with an info icon next to it) and has TypeScript 1.7.4.0 checked off (still interactive).  I can uncheck TypeScript 1.7.4.0 and it allows me to press Next but if it's checked off, it just has a disabled Update button (with UAC symbol to the left).
* So I unchecked TypeScript 1.7.4.0 and pressed Next -- which says it will uninstall.
* Still gets error when loading a project.
* Tried the install again (via Extensions and Updates) - this time it proceeds.
* Still gets the error and still says there is an update and my current version is 1.5.4.0.
* Ran a repair from the TypeScript_Full.exe = no luck.
* Installed Web Essentials 2015 (only difference I could see between this PC and my other one which works) = no luck.
* I'll see if I can fix this somehow.  Possibly full uninstall of VS or replacing tsc with a newer one.

Scenario 2 (works out of the box):
* On a similarly configured second PC, noticed it's installing "TypeScript 1.7.4.0 for Visual Studio 2015 Update 1".  Requires a reboot at the end.
* Once it opens the same project (still at 1.6), it warns that the project uses a version of TypeScript older than the version currently installed with Visual Studio and asks if I would like to upgrade = pressed Yes.
* This PC works just fine.

**Comment by gwicksted** [comment] 2015-12-02 17:20
Ok so noticed there were two TypeScript directories here:

`D:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft`

One was TypeScript and the other was TypeScript1.5

Removed TypeScript1.5 and VS got errors starting up so I ran a repair install using the TypeScript_Full.exe (for 1.7)

No more error!

So it's likely only those that used TS 1.5 (possibly the beta?)

**Comment by mhegazy** [comment] 2015-12-02 17:52
The installer never appended a version in a directory name in this location. if i am to guess, some one has manually created this directory.

glad the issue is resolved.

**Closed by mhegazy** 2015-12-02 17:52 UTC
Labels: Bug, Needs More Info

**Comment by gwicksted** [comment] 2015-12-02 18:08
@mhegazy you're probably right!  I may have been testing out TS from the repo during 1.5.

Thank you!
