### ISSUE TITLE
generic type is not equal to expression type

### ISSUE THREAD

**Issue by HeavenSky** [microsoft/TypeScript#43843] opened 2021-04-27 02:57 UTC
# Bug Report
detail see below code, it's very confused. "generic type is not equal to expression type"
```ts
type xx<T, U> = T extends void ? U : T & U;
type x1 = xx<never, number>
// x1 => never
type x2 = never extends void ? number : never & number;
// x2 => number
```

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
type xx<T, U> = T extends void ? U : T & U;
type x1 = xx<never, number>
// x1 => never
type x2 = never extends void ? number : never & number;
// x2 => number

// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

**Comment by nmain** [comment] 2021-04-27 11:57
Duplicate of https://github.com/microsoft/TypeScript/issues/41911
My search terms were distributive conditional type never

**Closed** 2021-04-29 18:00 UTC
Labels: Duplicate
