### ISSUE TITLE
execution flow analysis disregards narrowing for primitives constants

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#7768] opened 2016-04-01 17:00 UTC
nightly build

```
const x = Math.random() > 0.5 ? 'hey' : 1;
if (typeof x === 'number') {
	[].map(() => x + 2); // expected should typecheck, actual no-no-no
}
```

numbers can't mutate, `x` holds a number, also it is a constant, constant can't change its value, so ...

**Comment by DanielRosenwasser** [comment] 2016-04-01 17:06
My guess is that we stop trying to track the way this was narrowed because you're in an arrow function. Being able to track this would be pretty difficult, but maybe we could say that we still narrow in function expressions/arrow functions.

**Comment by RyanCavanaugh** [comment] 2016-04-01 17:12
If we see a `const` narrowed by `typeof`, that should be "sticky" even in function bodies.

This isn't true for `let`, e.g.
```ts
let x = Math.random() > 0.5 ? 'hey' : 1;
if (typeof x === 'number') {
  // Unsafe
  window.setImmediate(() => x.toFixed());
  // Safe but not distinguishable from above
  [0].map(() => x.toFixed());
}
x = 'oops';
```
but we can be sure the `typeof` a `const` cannot change.

**Comment by mhegazy** [comment] 2016-04-28 22:15
duplicate of https://github.com/Microsoft/TypeScript/issues/7662.

**Closed by mhegazy** 2016-04-28 22:15 UTC
Labels: Needs Proposal
