### ISSUE TITLE
in operator does not narrow string type to index object

### ISSUE THREAD

**Issue by deser** [microsoft/TypeScript#48972] opened 2022-05-05 15:01 UTC
Example:
```ts
const meow: string = 'domain1'

const hosts = {
    "domain1": {color: 'red'},
    "domain2": {color: 'blue'},
}

if(meow in hosts) {
   hosts[meow]
}
``` 

Playground: 
https://www.typescriptlang.org/play?#code/MYewdgzgLgBAtgUxAdwFw2gJwJZgOYwC8MA5ACYhwCGuAjCQFAOiSwAWI0ERMA3gzEEwARBWp1h6XqAA2ITOhKYEZEgF8ANAKGjKNMACZJfWfMUAjGQFcE6rWqbYAZgApEKGLhgcuASj7a3pxQEADa7sgAugwOQA

Expected behavior:
`meow` can be used to index `hosts` if verification with `in` operator is done.

**Comment by torcoste** [comment] 2022-05-05 17:41
This will work as you would expect if you do not forcibly set the type for `meow`

``` ts
const meow = 'domain1'

const hosts = {
    "domain1": {color: 'red'},
    "domain2": {color: 'blue'},
};

if(meow in hosts) {
   hosts[meow]
}
```

[Playground](https://www.typescriptlang.org/play?ts=4.6.2#code/MYewdgzgLgBAtgUxAdxgXhgcgCYjgQwEswBGTAWACgrRJYALEaCdGAbypi5gCJcDiJHgC52oADYgATqMxSE2TAF8ANJ2588RMACYRYkJJlYARuICuCZWspKA3FSqEAZgApEKGMRiNmASnZ1HyYoCABtD2QAXSolIA)

**Comment by jcalz** [comment] 2022-05-05 18:13
You forgot to completely fill out the issue template.  

This is working as intended.  Non-union types are not narrowed upon assignment.  Duplicate of or strongly related to #16976

**Comment by fatcerberus** [comment] 2022-05-05 18:58
Assuming this worked (allowing arbitrary strings as indexers after an `in` check), objects can legally have extra properties thanks to structural subtyping—so what is the type of `hosts[meow]` then?

**Closed** 2022-05-08 18:00 UTC
Labels: Duplicate
