### ISSUE TITLE
Bug in async awaits in es5

### ISSUE THREAD

**Issue by JustynaBroniszewska** [microsoft/TypeScript#40614] opened 2020-09-17 14:12 UTC
**TypeScript Version:** 4.1.0-dev.20200917

**Search Terms:** is:issue is:open async label:bug change

**Code**

```ts
async function bar () {
  return {
    a: await Promise.resolve(1),
    b: await Promise.resolve(2),
    c: await Promise.resolve(3),
    d: await Promise.resolve(4),
    e: await Promise.resolve(5),
    f: await Promise.resolve(6),
    g: await Promise.resolve(7),
    h: await Promise.resolve(8),
    // works correctly if you comment the next line
    i: await Promise.resolve(9),
  }
}

bar().then(console.log)
```
tsconfig.json
```json
{
  "compilerOptions": {
    "lib": ["DOM", "ES2015"]
  }
}
```

**Expected behavior:**
```js
{ a: 1, b: 2, c: 3, d: 4, e: 5, f: 6, g: 7, h: 8, i: 9 }
```

**Actual behavior:**

```js
{ a: 9, b: 9, c: 9, d: 9, e: 9, f: 9, g: 9, h: 9, i: 9 }
```

**Playground Link:** 
https://www.typescriptlang.org/play?target=1#code/IYZwngdgxgBAZgV2gFwJYHsIwEbAE4wAUAlDAN4BQMMeApsgnlpddcAFwzADuwqyMAAp50AW1QhaAOjoh0AGwButQgEZiAGiqtsnHnwHCxE6bIXLCAJk3bqUPb35CR4yTNpylKgMw3WMABMHA2djNzMvQgAWP1ZaYKcjV1MPcxUAVljqOATDFxN3TwsANiyYAHNc0OTCtMIAdjKACyqkgoiLAA4y1Fb88NTIgE5YgF8KcYpcPBIpZCbaCEIoTE9peXRy4iA

**Related Issues:** 
#40047

**Comment by j-oliveras** [comment] 2020-09-17 15:47
The cause seems to be that the generated code use the same value to init all properties (case 9):
```ts
// Excluded __awaiter and __generator functions
function bar() {
    return __awaiter(this, void 0, void 0, function () {
        var _a;
        return __generator(this, function (_b) {
            switch (_b.label) {
                case 0: return [4 /*yield*/, Promise.resolve(1)];
                case 1: return [4 /*yield*/, Promise.resolve(2)];
                case 2: return [4 /*yield*/, Promise.resolve(3)];
                case 3: return [4 /*yield*/, Promise.resolve(4)];
                case 4: return [4 /*yield*/, Promise.resolve(5)];
                case 5: return [4 /*yield*/, Promise.resolve(6)];
                case 6: return [4 /*yield*/, Promise.resolve(7)];
                case 7: return [4 /*yield*/, Promise.resolve(8)];
                case 8: return [4 /*yield*/, Promise.resolve(9)];
                case 9: return [2 /*return*/, (_a = {},
                        _a.a = _b.sent(),
                        _a.b = _b.sent(),
                        _a.c = _b.sent(),
                        _a.d = _b.sent(),
                        _a.e = _b.sent(),
                        _a.f = _b.sent(),
                        _a.g = _b.sent(),
                        _a.h = _b.sent(),
                        _a.i = _b.sent(),
                        _a)];
            }
        });
    });
}
bar().then(console.log);
```

**Comment by IllusionMH** [comment] 2020-09-17 15:55
At first I thought that this is problem with generator transformations, but looks like version where `async` changes to generator and `await` changed to `yield` provides correct assignments in each case.

Also original problem is not reproducible in 3.9.7.

**Comment by j-oliveras** [comment] 2020-09-17 16:06
The nightly have the same problem.

As a reference for the typescript team, in version 3.9.7 it generates:
```ts
// Excluded __awaiter and __generator functions
function bar() {
    return __awaiter(this, void 0, void 0, function () {
        var _a;
        return __generator(this, function (_b) {
            switch (_b.label) {
                case 0:
                    _a = {};
                    return [4 /*yield*/, Promise.resolve(1)];
                case 1:
                    _a.a = _b.sent();
                    return [4 /*yield*/, Promise.resolve(2)];
                case 2:
                    _a.b = _b.sent();
                    return [4 /*yield*/, Promise.resolve(3)];
                case 3:
                    _a.c = _b.sent();
                    return [4 /*yield*/, Promise.resolve(4)];
                case 4:
                    _a.d = _b.sent();
                    return [4 /*yield*/, Promise.resolve(5)];
                case 5:
                    _a.e = _b.sent();
                    return [4 /*yield*/, Promise.resolve(6)];
                case 6:
                    _a.f = _b.sent();
                    return [4 /*yield*/, Promise.resolve(7)];
                case 7:
                    _a.g = _b.sent();
                    return [4 /*yield*/, Promise.resolve(8)];
                case 8:
                    _a.h = _b.sent();
                    return [4 /*yield*/, Promise.resolve(9)];
                case 9: return [2 /*return*/, (_a.i = _b.sent(),
                        _a)];
            }
        });
    });
}
bar().then(console.log);
```

**Comment by IllusionMH** [comment] 2020-09-17 16:12
Interesting enough @andrewpg found that it doesn't depend on number of `await`'s
but on number of object keys after first `await`.

[Example](https://www.typescriptlang.org/play?target=1&ts=4.0.2&ssl=40&ssc=13&pln=39&pc=10#code/IYZwngdgxgBAZgV2gFwJYHsIwEbACYAUAlDAN4BQMMATgKbILVYVVXABcMwA7sKsjAAK1dAFtUIWgDo6IdABsAbrQIBGIgBpKrbJx58BwsROmyFyggCZN2qlE4BmLaxh5OAFmetanAKxeqOE4ANgCYAHNOAHYwgAtOAA4w1E4ATi8AX3Is8lBIWEQUDCxw9HQ8VWIybToGJmqXDhhVMN0YSzD7GCdbVw8wnxh-XqCYUN7ImBje+K5efiERcUkZWjklFQSbFxS5g0XjFbMNglTtmCysvOh4JCg0TAiyvEsqlhp6RmZe4AAGTl+YWAqgBQL080MSxMq3WFnUrXB+yMy1Ma3MKmsnUcYTcME8vUGwxco3GLkm0xcsySvQA9DSYLt0tpLuQgA)

**Comment by IllusionMH** [comment] 2020-09-18 09:07
Caused by 8231519b853b0fe594cb70b8b89fb8e5c15c2918 in #38880

/cc @elibarzilay @rbuckton

**Comment by andrewbranch** [comment] 2020-09-18 19:46
Thanks for the investigation, everyone! 🌟

**Comment by styu** [comment] 2020-09-18 22:22
Would it be possible to backport a fix for this to 4.0.x? We unfortunately had to revert our 4.0.x upgrade because this issue was causing our apps to crash, and we'd love to upgrade to 4.0.x before November :)

**Comment by DanielRosenwasser** [comment] 2020-09-18 22:45
Yes, I think we can packport the eventual fix to TypeScript 4.0.4. @elibarzilay do you think you'd be able to prioritize this issue?

**Comment by DanielRosenwasser** [comment] 2020-09-30 20:17
Seems like @elibarzilay is having hardware issues. @rbuckton can you take a look at this?

**Comment by elibarzilay** [comment] 2020-09-30 20:21
I'm back, kind of.  Trying to find it now.

**Closed** 2020-10-14 19:58 UTC
Labels: Bug, Fix Available

**Comment by DanielRosenwasser** [comment] 2020-10-14 23:50
If folks can try out the next nightly version of TypeScript to validate that the fix works for them, we'd appreciate that a toN!

**Comment by styu** [comment] 2020-10-16 14:38
@DanielRosenwasser I tried the nightly out in our repo and it seems to have fixed the issue!

**Comment by styu** [comment] 2020-10-19 15:01
@DanielRosenwasser sorry to bother, but what's the timeline for 4.0.4? We're super eager to upgrade to 4.0.x :)
