### ISSUE TITLE
Subtracting Date objects shows a TypeScript error, but actually works.

### ISSUE THREAD

**Issue by ScottHenshaw86** [microsoft/TypeScript#58400] opened 2024-05-02 07:16 UTC
### 🔎 Search Terms

"Date arithmetic"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Dates

### 💻 Code

```ts
const a = new Date();
const b = new Date();
const c = a - b;
```

### 🙁 Actual behavior

TypeScript shows error: The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.ts(2362)

### 🙂 Expected behavior

No error because the operation works.

**Comment by pavanputhra** [comment] 2024-05-02 07:17
+1

**Comment by Andarist** [comment] 2024-05-02 07:31
https://stackoverflow.com/questions/41750390/what-does-all-legal-javascript-is-legal-typescript-mean/41750391#41750391

**Comment by MartinJohns** [comment] 2024-05-02 08:31
Duplicate of #5710.

**Comment by RyanCavanaugh** [comment] 2024-05-02 15:44
See also https://github.com/microsoft/TypeScript/issues/2361#issuecomment-82509802

**Closed** 2024-05-05 01:30 UTC
Labels: Duplicate
