### ISSUE TITLE
Organize Import creates whitespace that needs to be deleted manually

### ISSUE THREAD

**Issue by jsgoupil** [microsoft/TypeScript#40736] opened 2020-09-22 19:53 UTC
*TS Template added by @mjbvz*

**TypeScript Version**: 4.1.0-dev.20200918

**Search Terms**
- organize imports

---

- VSCode Version: 1.49.1 (user setup)
- OS Version: Windows_NT x64 10.0.19041

I am not 100% sure what is the exact scenario how to reproduce this, but it happens 90% of the time. When I press ALT+SHIFT+O (Organize Imports), I get plenty of spacing in my imports.
The rules for organizing these imports seem to be all over the place, which one ends up on their own line? etc.
I always have to clean up manually.

These imports:
```
import {
    ChangeDetectionStrategy,
    Component,
    ContentChild,
    EventEmitter,
    Input,
    Output,
    TemplateRef,
    AfterViewInit,
    ChangeDetectorRef,
    HostBinding,
    ElementRef,
    ViewChild
} from '@angular/core';
import { Resource, ClickableResource } from '@models/resource';
import { newGuid } from '@utility/string';
import { DragulaService } from 'ng2-dragula';
```

Become:
```
import {
    AfterViewInit, ChangeDetectionStrategy,







    ChangeDetectorRef, Component,
    ContentChild,







    ElementRef, EventEmitter,





    HostBinding, Input,
    Output,
    TemplateRef,




    ViewChild
} from '@angular/core';
import { ClickableResource, Resource } from '@models/resource';
import { newGuid } from '@utility/string';
import { DragulaService } from 'ng2-dragula';
```

Video of what is happeining.
[spacing-incorrect.zip](https://github.com/microsoft/vscode/files/5263672/spacing-incorrect.zip)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-09-24 01:49
Thanks @jsgoupil!

@DanielRosenwasser Can we make sure this is scheduled for TS 4.1? (I have not see other reports so far, so I don't think we want to try fixing it in a 4.0 recovery build)

**Comment by jsgoupil** [comment] 2020-09-24 15:35
Maybe there should be something a little more predictable when it comes to either putting them all the imports on one line or putting them all on different lines? It seems quite random. Also, make sure to check how many lines end up **under the last import** and in order to stay consistent.

It had been happening forever, but I thought it would just get fixed one day :) Now that I'm doing major refactoring, this is happening a lot.

**Comment by a-tarasyuk** [comment] 2020-10-01 15:55
I suppose the organized import should look like so

```ts
import {
    AfterViewInit,
    ChangeDetectionStrategy,
    ChangeDetectorRef,
    Component,
    ContentChild,
    ElementRef,
    EventEmitter,
    HostBinding,
    Input,
    Output,
    TemplateRef,
    ViewChild
} from "@angular/core";
```

It seems the issue in sorting specifiers because import specifiers have original ranges after the sort 
https://github.com/microsoft/TypeScript/blob/35111231f7ee48ce0ca08e4c1076d94b7125865b/src/services/organizeImports.ts#L228
One of the possible fix to make a map after a sort to fix ranges. I think @andrewbranch is more familiar with this functionality., @andrewbranch what do you think?

**Comment by andrewbranch** [comment] 2020-10-02 16:47
This bug is almost definitely caused by https://github.com/microsoft/TypeScript/pull/36688. I’m not sure off the top of my head what the best fix is, but that’s the first place to look. @elibarzilay, I can take this one if you want. /cc also @a-tarasyuk.

**Comment by elibarzilay** [comment] 2021-02-13 10:04
@andrewbranch: I looked at this, and at the closed #40895, and I'm confused.  It looks like #36688 is about preserving trivia(?) (comments & newlines, and maybe whitespace?) but I don't see how this would make sense when reordering things:

* Wouldn't this get very messed up when there's an `import` line that looks like

    Foo, // blah blah

  since the comment will get dragged along with the next import (so will appear on whatever happens to be before it, "doubly shuffled")?

* If the source has empty lines to separate parts of the imports, then those would also move in unexpected ways; even worse with comment lines to separate such parts.

Given this, I'd expect the reasonable option to be dropping all the extras, and maybe at most do the minor thing of putting newlines in the new text if the original had any newlines, but nothing else.

Clearly there's some brokenness in these cases with the extra empty lines, and I'm guessing that the #36688 doesn't account for lines being shuffled which leads to it, but even if this didn't happen, I don't see how the fixed thing would make sense given the above.

**Comment by andrewbranch** [comment] 2021-02-16 18:21
This should be fixed by https://github.com/microsoft/TypeScript/pull/42630.

**Comment by andrewbranch** [comment] 2021-02-16 21:32
Looks like #41417 should have been marked as an exact duplicate of this, in fact.

**Comment by elibarzilay** [comment] 2021-02-23 20:04
Closing this, since as @andrewbranch notes, it's the same as #41417, and I also verified that #42630 resolves this one.

**Closed by elibarzilay** 2021-02-23 20:04 UTC
Labels: Bug, Domain: Formatter, Domain: Organize Imports, Effort: Moderate, Fix Available, Rescheduled, help wanted
