### ISSUE TITLE
Incorrect string property suggestion for private field returned outside of class

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#36082] opened 2020-01-08 19:45 UTC
**TypeScript Version:**  3.8.0-dev.20200108

**Search Terms:**
- private fields
- javascript
- string property accessor
- bracket accessor
- suggestions

**Code**
For the JavaScript:

```js
//@ts-check

class Prv {
    #value = 1;
}

new Prv()[''];
```

Trigger suggestions inside the string

**Expected behavior:**
No suggestions returned

**Actual behavior:**
A suggestion for `#value` is returned. This changes the code to:

```js
//@ts-check

class Prv {
    #value = 1;
}

new Prv()['#value'];
```

**Comment by j-oliveras** [comment] 2020-01-08 20:28
Related/duplicate of #35954? PR on #36079.

**Closed** 2020-01-31 03:42 UTC
Labels: Bug, Fix Available
