### ISSUE TITLE
Class with getter satisfies interface with mutable property

### ISSUE THREAD

**Issue by SrTobi** [Microsoft/TypeScript#16171] opened 2017-05-31 14:24 UTC
Consider the following code:

~~~~ts
interface Base {
    prop: number;
}


class Impl implements Base {
    get prop(): number {
        return 3;
    }
}

let base = <Base>new Impl();
base.prop = 9;

~~~~

This gives no error while compiling and even runs without any error/exception.
It should only work though, if `prop` was declared readonly in the `Base`.
Otherwise it should report that a setter is missing for `prop`.

**Comment by andy-ms** [comment] 2017-05-31 15:25
May be a duplicate of #13347.

**Comment by mhegazy** [comment] 2017-06-14 22:38
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-06-14 22:38 UTC
Labels: Duplicate
