### ISSUE TITLE
Typescript does not narrow down type inside Array.prototype.find in strictMode

### ISSUE THREAD

**Issue by zetti-caletti** [microsoft/TypeScript#53333] opened 2023-03-18 00:37 UTC
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://stackblitz.com/edit/typescript-2ghahn?file=index.ts)

### 💻 Code

```ts
interface Post {
  id: string;
  replyPost?: {
    id: string;
  };
}

export class PostService {
  private posts: Post[] = [];

  getPostsForLeave(leavePostId: string) {
    const leavePost = this.posts.find((post) => post.id == leavePostId);
    const postPath: Post[] = [];

    if (!leavePost) {
      return postPath;
    }
    postPath.push(leavePost);
    let currentPost: Post | undefined = leavePost;

    while (currentPost && currentPost.replyPost) {
      // here currentPost is correctly narrowed down as not undefined, but not inside Array.prototype.find
      if (currentPost.replyPost.id) {
      }

      this.posts.find((post) => {
        // this does not work
        if (currentPost.replyPost) {
        }
      });

      currentPost = this.posts.find((post) => {
        // this does not work
        if (currentPost.replyPost) {
        }

        // this also does not work
        return post.id == currentPost.replyPost.id;
      });

      if (currentPost) {
        postPath.push(currentPost);
      }
    }
    return postPath.reverse();
  }
}
```

### 🙁 Actual behavior

Inside Array.prototype.find it says:
'currentPost' is possibly 'undefined'

### 🙂 Expected behavior

Should be detected as not undefined, because of the condition in the while loop.

**Comment by fatcerberus** [comment] 2023-03-18 01:17
Duplicate of #9998 and there’s an issue template that explains this

**Comment by zetti-caletti** [comment] 2023-03-18 16:16
Regarding to #9998 
But Typescript should know, that Array.prototype.find does not change the value of an array, because it's a built in function.

**Comment by fatcerberus** [comment] 2023-03-18 16:27
To the compiler it's just another method call.  There's no meaningful distinction between JS built-ins and user-defined functions; in fact all the built-ins are defined in userland in `.d.ts` files that come with the compiler.

**Closed** 2023-03-25 18:00 UTC
Labels: Duplicate
