### ISSUE TITLE
Navigation bar in .d.ts file ignores interfaces when cursor is outside the interface

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#3026] opened 2015-05-04 21:26 UTC
For the following code:
```ts
declare namespace M {
    // cursor here
    interface I {

        prop;
    }

    var v;
}
```
One would expect the middle nav bar to show M, and the right nav bar to show I. But the right nav bar shows v. Effectively, it skips interfaces and shows the upcoming var instead.

The middle nav bar does show I when the cursor is inside I, as expected.
![navbarskipsinterfaces](https://cloud.githubusercontent.com/assets/8052525/7462855/91765c40-f269-11e4-9dcc-6b7e76b38bda.gif)

**Comment by paulvanbrenk** [comment] 2015-05-04 22:00
I don't think that's a bug... the problem is that `I` is not shown in the nav bar at all, when the cursor is above the declaration.

**Comment by JsonFreeman** [comment] 2015-05-04 23:07
But a *var* is shown when the cursor is above the declaration. So why not an interface?

**Comment by paulvanbrenk** [comment] 2015-05-05 01:20
@JsonFreeman that's what I said..

**Comment by DanielRosenwasser** [comment] 2015-05-05 06:00
Now, now, everybody can be right. :trophy:

**Comment by JsonFreeman** [comment] 2015-05-05 08:40
Oh I think I got confused when you said "I don't think that's *a* bug", instead of "*the* bug" (using the indefinite article).

**Comment by mhegazy** [comment] 2016-05-17 22:48
this looks fixed now.

**Closed by mhegazy** 2016-05-17 22:48 UTC
Labels: Accepting PRs, Bug
