### ISSUE TITLE
Missing decorators functionallity on plain objects

### ISSUE THREAD

**Issue by Durisvk** [Microsoft/TypeScript#20442] opened 2017-12-04 14:52 UTC
**TypeScript Version:**
 - 2.7.0-dev.20171203 (locally)
 - 2.6.1 (globally)

tested also on `typescript@next`

**Code**

```ts
// Define a simple decorator
const decorator : PropertyDecorator = (target : any, key : string | symbol) : void => {
    console.log(key, target[key]);
}

// I will create a plain object
const obj = {
    some: {
        nestedObj: {
            // Here comes the point of error
            @decorator
            value: 10,
        },
    },
};

```

**Expected behavior:**

I would expect it to be transpiled like this:

```js
var obj = {
    some: {
        nestedObj: decorator({
            value: 10,
        }, 'value'),
    },
};
```

Babel already comes with this feature, and when I saw it I was thinking: "of course, Typescript will support it".

So I've build a feature in my library based on that. Now I have to do this workaround:

function applyDecorators(parent : any, key : string | symbol, ...decorators : PropertyDecorator[]) {
    _.forEach(decorator, (d) => {
        d(parent, key);
    });
}

applyDecorators(obj.some.nestedObj, 'value', decorator1, decorator2);

**Actual behavior:**

The Visual Studio Code shows error right away. The tsc compiler also shows an error

- VSCode Error:

```ts

// << Line 148 is here >>
const obj = {
    some: {
        nestedObj: {
            @decorator // // [ts] Declaration expected. any         [[line 152]]
            value: 10, // value <= [ts] Unused label. ||| 10 <= [ts] Left side of comma operator is unused and has no side effects.          [[line 153]]
        }, // [ts] Expression expected         [[line 154]]
    }, // Argument expression expected          [[line 155]]
}; // Argument expression expected          [[line 156]]
// << Line 158 is here >>
```

- tsc@next Error:

```
tests/integration.ts(152,21): error TS1136: Property assignment expected.
tests/integration.ts(152,31): error TS1146: Declaration expected.
tests/integration.ts(154,17): error TS1109: Expression expected.
tests/integration.ts(155,13): error TS1135: Argument expression expected.
tests/integration.ts(156,9): error TS1135: Argument expression expected.
tests/integration.ts(156,10): error TS1005: ')' expected.
tests/integration.ts(188,5): error TS1128: Declaration or statement expected.
tests/integration.ts(188,6): error TS1128: Declaration or statement expected.
tests/integration.ts(190,1): error TS1128: Declaration or statement expected.
tests/integration.ts(190,2): error TS1128: Declaration or statement expected.
```

**Comment by aluanhaddad** [comment] 2017-12-04 20:19
The reason that is not supported is because https://github.com/tc39/proposal-decorators does not provide for it. Decorators are unfortunately limited to classes.

Whatever Babel extension you have that supports this (I'd be curious to know which) is providing functionality that is not even proposed for standardization.

**Comment by mhegazy** [comment] 2017-12-04 20:35
Duplicate of https://github.com/Microsoft/TypeScript/issues/5770

**Closed** 2018-01-02 18:40 UTC
Labels: Duplicate
