### ISSUE TITLE
Constant overload doesn't complain about incorrect call

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#2021] opened 2015-02-12 16:09 UTC
Test Case:

interface Overload {
	
	foo(id:"special", value:number):void;
	foo(id:string, value:any):void;

}

class Bug {

	private overload:Overload;

	public call():void {
		this.overload.foo("special", "");
	}
}

Compile with tsc. Observe that there is no error message. Shouldn't the compiler complain about the fact that this.overload.foo("special", "") is an incompatible call. E.g. "" is not assignment compatible to number.

**Comment by NoelAbrahams** [comment] 2015-02-12 17:40
Possible duplicate of #191. It'll be nice to have an error here, but there are complications.

**Closed** 2015-02-12 18:00 UTC
Labels: Duplicate
