### ISSUE TITLE
Union type is not determined with deep destructuring

### ISSUE THREAD

**Issue by anvish** [Microsoft/TypeScript#12465] opened 2016-11-23 10:22 UTC
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)
2.1.1
**Code**

```ts
type Option = 'a' | { result: number }

type Value = { option: Option }

function do1(value: Value) {
    if (value.option != 'a') {
        const { result } = value.option
    }
}

function do2(value: Value) {
    if (value.option != 'a') {
        const { option: { result } } = value // [ts] Type 'Option' has no property 'result' and no string index signature.
    }
}
```

**Expected behavior:**
`do2` works as `do1`, type of `value.option` is determined
**Actual behavior:**
`do2` works differently from `do1`, type of `value.option` is not determined

**Comment by ahejlsberg** [comment] 2016-11-23 17:40
Duplicate of #10065 and #10846.

**Closed** 2017-04-21 16:56 UTC
Labels: Duplicate
