### ISSUE TITLE
isNaN expecting a number argument

### ISSUE THREAD

**Issue by shaharkazaz** [Microsoft/TypeScript#21065] opened 2018-01-08 15:04 UTC
**TypeScript Version:**  2.6.2

**Code from lib.es6.d.ts**

```ts
/**
  * Returns a Boolean value that indicates whether a value is the reserved value NaN (not a number).
  * @param number A numeric value.
  */
declare function isNaN(number: number): boolean;
```

**Expected behavior:**
The function should get any type and not only numbers.

**Actual behavior:**
I get an error when passing a string.

**Comment by jcalz** [comment] 2018-01-08 15:18
Duplicate of #19153 among many, many others.   Did you [read the contributing guidelines](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#2-search-for-duplicates) as requested before you opened this issue?

**Comment by shaharkazaz** [comment] 2018-01-08 15:36
Searched for: "is:issue is:open isNaN" but didn't see any matches, sorry for the duplicate, next time I'll search without filters 👍

**Comment by jcalz** [comment] 2018-01-08 15:39
Yeah, I think "make sure to search closed issues also" should be made explicit in those instructions.

**Comment by RyanCavanaugh** [comment] 2018-01-08 16:06
Didn't realize we were linking people to the terrible Issues Tab search. Sorry about that

**Closed** 2018-01-08 19:19 UTC
Labels: Duplicate

**Comment by aleksey-bykov** [comment] 2018-01-18 11:26
the instructions to search before posting need to be in the template of the issue
