### ISSUE TITLE
Raise tsconfig default to ES2015 or later

### ISSUE THREAD

**Issue by NagayamaToshiaki** [microsoft/TypeScript#59986] opened 2024-09-17 06:37 UTC
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

According to [CanIUse](https://caniuse.com/es6), more than 96% of the current brousers used have ES2015 support.
As of ES2022, [nine out of ten](https://caniuse.com/?feats=mdn-javascript_builtins_array_at,mdn-javascript_builtins_regexp_hasindices,mdn-javascript_builtins_object_hasown,mdn-javascript_builtins_error_cause,mdn-javascript_operators_await_top_level,mdn-javascript_classes_private_class_fields,mdn-javascript_classes_private_class_methods,mdn-javascript_classes_static_class_fields,mdn-javascript_classes_static_initialization_blocks) browsers are ready to use the feature.
Why do you stick to 15-year-old ES5 as default?

**Comment by MartinJohns** [comment] 2024-09-17 07:16
Duplicate of #49206.

**Comment by MartinJohns** [comment] 2024-09-17 07:20
Related: #10117 / #47572.

**Closed** 2024-09-17 16:53 UTC
