### ISSUE TITLE
array spread into an object is incorrectly assignable to array types

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#48692] opened 2022-04-14 07:55 UTC
# Bug Report

### 🔎 Search Terms
spread object assignable to array 
### 🕗 Version & Regression Information

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220408#code/MYewdgzgLgBAZiEAuG0BOBLMBzA2gXRgF4YCBYAKEoHpqBTNNENFAFQE8AHOmAcgG8AvrxgYIMALZiIWbDCgALHggA2KkAHdZMTk25ooGOuLhMJ8rj17pZBXihV0cigDQ6QnN5wCuEBW9AwYABDKDdgsAATGAAmADZJZjoAOkpA6BgAI2CWVChMHAJiGCFKGmowEBgGJjQ08AzsgC8UG0LCEn5k7oQQQTKKWjRvMEMJHhrmLLoQ3x4MKHFK2AiYHLRg9kpstGSfPwAKACIjgEogA)

### 💻 Code

```ts
const foo: string[] = []

//error: Type '{}' is missing the following properties from type 'string[]': length, pop, push, concat, and 26 more.
const bar: string[] = {}

//no error
const baz: string[] = {...foo}

//runtime error because its not an array
bar.push("")
```

### 🙁 Actual behavior
object is assignable to an array type

### 🙂 Expected behavior
error because the object does not have all the members of `Array`

**Comment by MartinJohns** [comment] 2022-04-14 08:07
Duplicate of #43977. Used search terms: `object spread array in:title`

**Closed** 2022-04-14 08:10 UTC
