### ISSUE TITLE
Tagged unions discriminated over number-like or symbol-like properties

### ISSUE THREAD

**Issue by mcheshkov** [Microsoft/TypeScript#24624] opened 2018-06-02 16:13 UTC
## Search Terms

Tagged union
Number-like properties
Symbol-like properties

## Suggestion

Discriminate union variants on number-like or symbol-like property value.
It brings such properties on-par with string-like in one more area.

## Use Cases

Some languages/serialization frameworks represent enum values as tuple/array with discriminator as head, and nested values as tail. Typing that can be useful in interop with such languages.

## Examples

```
type C = {
    0: 'a',
    1: number
};

type D = {
    0: 'b',
    1: string
};

type CD = C | D;

let cd: CD;
if (Math.random() < 0.5) {
    cd = ['a', 1];
} else {
    cd = ['b', 'asd'];
}

switch (cd[0]) {
    case 'a':
        let n : number = cd[1]; // not allowed on 2.9.1
        break;
    case 'b':
        break;
}

//////////

const sym1 = Symbol();
const sym2 = Symbol();

type G = {
    [sym1]: 0,
    [sym2]: number
};

type H = {
    [sym1]: 1,
    [sym2]: string
};

type GH = G | H;

let gh: GH;
if (Math.random() < 0.5) {
    gh = { [sym1]: 0, [sym2]: 1 };
} else {
    gh = { [sym1]: 1, [sym2]: 's' };
}

switch (gh[sym1]) {
    case 0:
        let n: number = gh[sym2]; // not allowed on 2.9.1
        break;
    case 1:
        break;
}
```

On TS 2.9.1 this code generates `Type 'string | number' is not assignable to type 'number'.` on marked lines.

## Checklist

My suggestion meets these guidelines:
* [X] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment] 2018-06-02 19:47
Duplicate of https://github.com/Microsoft/TypeScript/issues/10530

**Closed** 2018-06-03 00:15 UTC
Labels: Duplicate
