### ISSUE TITLE
property undefined check

### ISSUE THREAD

**Issue by dolphinlin** [microsoft/TypeScript#35692] opened 2019-12-16 02:07 UTC
**TypeScript Version:**  3.7.2

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
type StreamerList = {
  notSignIn?: string[];
};

function run(s: StreamerList) {
  if (!s.notSignIn) return;

  const notSignInList = s.notSignIn;

  const agg = ['a', 'b', 'c'];
  agg.filter(member => s.notSignIn.indexOf(member)); // Object is possibly 'undefined'.
  agg.filter(member => notSignInList.indexOf(member)); // work well.
}

```

**Expected behavior:**
Line 11 shouldn't be undefined, if i re-assign `s.notSignIn` to new var, the `undefined check` will be fine.

**Actual behavior:**

**Playground Link:** 
https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=14&pc=1#code/C4TwDgpgBAysBOECGBbC8AyBLAzsKAvFAN4BQUUAdgPbAxYDmlAkpQPwBcUe8WlDAbQC6AblIBfMaQBmAV0oBjYFmqUo8eQAocXOIlTpseAJQlyULNKiaAhDgB0NOoxaVTiYLPiUpFBarwqWnomViN8IgcnENdfKH9KQKQGBkIoAQByJAyAGigMgCNc-IUM0XNkhntpLAAbYHRNNBQC9EIAPm5HYJdWez4AEwgADwB5aSaIFvRjYzEKSuq6hvhJ6fgOoOdQynD+yiGxiebW+FmxcVIgA

**Related Issues:**

**Comment by jcalz** [comment] 2019-12-16 03:21
duplicate of #11498 and #9998

**Closed** 2019-12-20 18:00 UTC
Labels: Duplicate
