### ISSUE TITLE
Extend typeof / type query to work on general expressions

### ISSUE THREAD

**Issue by chadaustin** [Microsoft/TypeScript#7425] opened 2016-03-07 21:14 UTC
This is in the context of a jasmine unit test.  I'd love to write:

```
describe(..., () => {
  // note: not initialized yet.  gets initialized in beforeEach.
  let mock_objects: typeof(get_mock_objects());
  beforeEach(() => {
    mock_objects = get_mock_objects();
  });
});
```

I don't want to manually spell out the type, because get_mock_objects returns an object with a bunch of ad hoc properties.  I also don't want to call get_mock_objects() outside of beforeEach because it depends on other setup and it's somewhat expensive.  (I also don't want to risk forgetting to call it in beforeEach.)

Right now, typeof is limited to specific types of expressions, but it seems it should be able to work on any expression.

**Comment by DanielRosenwasser** [comment] 2016-03-07 21:26
Hi @chadaustin, thanks for filing the issue. This looks like a duplicate of #6606. In the future, it'd be helpful for us to double-check if there's an existing issue.

**Closed by DanielRosenwasser** 2016-03-07 21:26 UTC

**Comment by chadaustin** [comment] 2016-03-07 22:00
Sorry for the noise!  I promise I searched for "typeof" three times but just didn't see that one.  :)

**Comment by DanielRosenwasser** [comment] 2016-03-08 17:45
No worries! Admittedly it's a lot easier for us to find those issues so I can't blame you.
