### ISSUE TITLE
"not in keyof T" - exclude keyof T from string

### ISSUE THREAD

**Issue by yinso** [microsoft/TypeScript#42315] opened 2021-01-13 10:57 UTC
# Suggestion

## 🔍 Search Terms

* "not in keyof T"
* Exclude keyof T
* opposite, outside keyof
* reverse, inverse keyof

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ x ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ x ] This wouldn't change the runtime behavior of existing JavaScript code
* [ x ] This could be implemented without emitting different JS based on the types of the expressions
* [ x ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ x ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I am trying to define a type that matches all strings except for `keyof T`, which seems to be definable as:

```typescript
type NotInKeyof<T> = Exclude<string, keyof T> // expect to match all string except 'bar' and 'baz'

interface Foo { // keyof Foo = 'bar' | 'baz'
    bar: string
    baz: number
}

const notInKeyofFoo: NotInKeyof<Foo> = 'bar' // expect to error but passes.
```

However, this doesn't work the way I thought it would. TypeScript currently seems to treat `string` and the keys of an object as distinct types, so the exclusion doesn't do anything.

This could just be my search skill failing me - if this is already doable in some form, please let me know thanks.

## 📃 Motivating Example

This reason I am looking for such a type is to write code that allows for incrementally building up an object type, so as I add new keys, the type checker can help catch whether I accidentally used old keys.

I am seeing the need for this pattern in the following scenarios where there is a need to deal with version management and incremental changes - I am sure there are more elsewhere as well:

* database schema construction
* form construction
* API construction

## 💻 Use Cases

My current usage is to model database schema changes. The following snippet shows what I am thinking of:

```typescript
const Accounts = createTable('Account') // type is {} at this point.
  .column('accountId', Number) // this widens the type to { accountId: number }
  .column('name', String) // this further widens the type to { acccountId: number, name: string }
```
By allowing the type to be incrementally build up, we can model multiple versions of the database in a single code base.

This is already doable today with most of TypeScript's facilities. The gap right now is that when I add a new column, it would be great for TS to help check whether the key was already used, hence the "not in keyof" test:

```typescript
// time to upgrade to Accounts V2
const AccountsV2 = Accounts
  .column('description', String) // no issues
  .column('accountId', Number) // would be great if TS can flag this.
```

If this is not yet doable in TS, it seems to me this should be a safe addition to existing code, but certainly would love to know more either way on how this can be considered. Please let me know if there are any questions, thanks.

**Comment by MartinJohns** [comment] 2021-01-13 10:59
Duplicate of #38254.

**Comment by yinso** [comment] 2021-01-13 11:13
I see - thanks for the quick response ;)

**Comment by MartinJohns** [comment] 2021-01-13 11:23
> TypeScript currently seems to treat `string` and the keys of an object as distinct types

To expand a bit on this. `keyof T` is a [union type](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#union-types) of several [literal types](https://www.typescriptlang.org/docs/handbook/literal-types.html) matching the property names of the type `T`, for example `keyof { propA: number; propB: string }` results in the union type `"propA" | "propB"`. These literal types `"propA"` and `"propB"` are still a `string` type, just more specific / narrow.

The [`Exclude<T, E>` utility type](https://www.typescriptlang.org/docs/handbook/utility-types.html#excludetype-excludedunion) removes all union members from `T` that are assignable to `E`. In your example `Exclude<string, ..>` it won't do anything, because `string` is not a union type to begin with.

**Comment by yinso** [comment] 2021-01-13 23:53
Awesome thanks for the additional elaborations. Sounds like the right solution would be based on negated types #29317 when it's available - something like:

```typescript
type NotKeyof<T> = string & not keyof T
```

**Closed** 2021-01-16 18:00 UTC
Labels: Duplicate

**Comment by justindbaur** [comment] 2022-08-12 00:09
@yinso You mention being able to do your incremental object creation just without the safety of adding a property multiple times. Do you mind sharing how you were able to achieve that? I'm in a similar boat right now.

**Comment by yinso** [comment] 2022-09-10 03:12
@justindbaur this [TS Playground fiddle](https://www.typescriptlang.org/play?#code/C4TwDgpgBAkgzgQwAoCcD2BjAPAFQHxQC8UAFAG4BcUCAdiAJREFlQCWcUOAUFxgDYI4HAMJo+AVwC2NXAQDeXKFBQQEAEzQ0+IKDQSSIVOMBSsaAc0XLVGrTvYIq8ZOmz4rGTcZTiMwNCgkegZGJmbmADRsiE6IqJiyjApKSsAAFuwAdMHQxDlWqRlwmQ5E0QhWAL5c1VygkFCiEtIAsghgWACqUBAAHsAQNGocaABGAFYQfgTEyVAA2khsNFAA1hAgaABmUJ0AulRNUjKdi3t4NTz8ghw4CKN8EF09-YPDUGOT01BzKuqa2ignmaNDghzExzaHU6FyUnlBJl8-kCwOOYMaENa7S6eCSBSg6SyqOkHGIxNBVQ8mJkAGkAIwvAZDDjecJRHB0vBBfSGKD0qIOWIuBIc3FUO4PJ7dABkUAASlMAmosPzOJz5PiVMBxCgVjQIAB3Tj3R7PWUKzwoZWq0VcuRQTKOwnFclwKLzHIHXSGjEg3Cc7kGAWIRiVagialQs3yxVWlV09nq+iU2rw4wEk25b1GiWPEhySrJ3heYAZyUM4jATOZckkADkrDUdai5CotAYVBY7F0UlGEBQTAJ4Ag23IjEIE6gdZovf7deTadLVclACYysvHnSa9T6zlm6RKNQ6PRO9EoKyLIP6iOtmOiJO6xfzPPiwiy48AMzrzMr7cg+sYH8AxNi2h7tieUBdhwAAiCADIOXYIrQGA3lAsEDEWQA) shows a simple sketch of the incremental idea. let me know if there are any questions.
