### ISSUE TITLE
Support json output formatter

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/TypeScript#50631] opened 2022-09-04 11:27 UTC
# Suggestion

## 🔍 Search Terms

tsc

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

https://eslint.org/docs/latest/user-guide/formatters/

We can see eslint support json formatter, can tsc also support this?

## 💻 Use Cases

parse tsc output

**Comment by MartinJohns** [comment] 2022-09-04 12:59
Duplicate of #46340 / #31566.

> Search Terms  
> tsc

Those are some very poor search terms. I used: `json output in:title`

**Closed** 2022-09-10 18:00 UTC
Labels: Duplicate
