### ISSUE TITLE
Support of local variable for `MyClass.prototype`

### ISSUE THREAD

**Issue by SmallAiTT** [Microsoft/TypeScript#26033] opened 2018-07-28 03:35 UTC
## Suggestion
Source:

```ts
namespace G{
    export class MyClass{
        f1(): void{}
        f2(){}
        f3(){}
        f4(){}
    }
    export class MyClass2 extends MyClass{
        f1(): void{super.f1()}
        f2(): void{super.f2()}
        f3(): void{super.f3()}
    }
}
```

After compile, the code would be `code1`:
```js
var G;
(function (G) {
    var MyClass = (function () {
        function MyClass() {
        }
        MyClass.prototype.f1 = function () { };
        MyClass.prototype.f2 = function () { };
        MyClass.prototype.f3 = function () { };
        MyClass.prototype.f4 = function () { };
        return MyClass;
    }());
    G.MyClass = MyClass;
    var MyClass2 = (function (_super) {
        __extends(MyClass2, _super);
        function MyClass2() {
            return _super !== null && _super.apply(this, arguments) || this;
        }
        MyClass2.prototype.f1 = function () { _super.prototype.f1.call(this); };
        MyClass2.prototype.f2 = function () { _super.prototype.f2.call(this); };
        MyClass2.prototype.f3 = function () { _super.prototype.f3.call(this); };
        return MyClass2;
    }(MyClass));
    G.MyClass2 = MyClass2;
})(G || (G = {}));
```
But I expect it to be `code2`:
```js
var G;
(function (G) {
    var MyClass = (function () {
        function MyClass() {
        }
        var __p = MyClass.prototype;
        __p.f1 = function () { };
        __p.f2 = function () { };
        __p.f3 = function () { };
        __p.f4 = function () { };
        return MyClass;
    }());
    G.MyClass = MyClass;
    var MyClass2 = (function (_super) {
        __extends(MyClass2, _super);
        function MyClass2() {
            return _super !== null && _super.apply(this, arguments) || this;
        }
        var __p = MyClass2.prototype;
        var __sp = _super.prototype;
        __p.f1 = function () { __sp.f1.call(this); };
        __p.f2 = function () { __sp.f2.call(this); };
        __p.f3 = function () { __sp.f3.call(this); };
        return MyClass2;
    }(MyClass));
    G.MyClass2 = MyClass2;
})(G || (G = {}));
```

It is because  `code2` would be smaller than `code1` after compile of uglifyjs.
`MyClass.prototype` would still be `MyClass.prototype` after compile of uglifyjs.
I am working in a H5-Game team, and I'm hoping so eagerly that you can support this feature.
Thx!
## Checklist

My suggestion meets these guidelines:
* [ ] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by DanielRosenwasser** [comment] 2018-07-28 03:51
Duplicate of #3929.

**Comment by DanielRosenwasser** [comment] 2018-07-28 03:57
Just because it's been brought up in that original thread, using [this gzip utility](https://dafrok.github.io/gzip-size-online/) shows the current code is actually smaller after compression than when introducing the variable.

**Comment by SmallAiTT** [comment] 2018-07-28 05:59
But my test result used `GZip Size Online (LEVEL:6)` is:
* `code1`: `original size: 679232 / gzipped size: 163199`.
* `code2`: `original size: 659411 / gzipped size: 157842`.

**Comment by SmallAiTT** [comment] 2018-07-28 06:07
My test code is compiled by uglifyjs.

**Closed** 2018-12-15 18:00 UTC
Labels: Duplicate
