### ISSUE TITLE
ts ignores type annotation and generate wrong type inference 

### ISSUE THREAD

**Issue by chenxinhang12345** [microsoft/TypeScript#57765] opened 2024-03-13 18:44 UTC
### 🔎 Search Terms

wrong type inference

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ?

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.5.0-dev.20240313#code/DYUwLgBAhgXBDOYBOBLAdgcwgHwmgrsMBALx6HADcAUAMYD2aiEARqRANoCMANAEw8AzAF0aLAHQAzekgCiUWgAsAFMtoBKUgD4IAb2oRo7AMrJ0GNepoBfK9RSTlUCAEISZAkXX7DhgPR+RijweCAAbiBIEOgQYIrBrMD0tADWBr4MTPSg4kkWUHbW1EA

### 💻 Code

```ts
let a: string | null = null;
const b = [1,2,3];
b.forEach((c) => {
  a = String(c);
});
if(a !== null){
    // a is never in this block
    console.log(a);
}
```

### 🙁 Actual behavior

variable `a` is inferred as `null` in the if block, causing the variable `a` in the if block to be type `never`.

### 🙂 Expected behavior

`a` should be inferred as `string`

### Additional information about the issue

```ts
let a: string | null = null as (string | null);
const b = [1,2,3];
b.forEach((c) => {
  a = String(c);
});
if(a !== null){
    // a is never in this block
    console.log(a);
}
```
This workaround magically works.

**Comment by MartinJohns** [comment] 2024-03-13 18:46
The lost narrowing in the callback is a duplicate of #9998.

That your type annotation is not used is working as intended. Assigning a value narrows the variable.

**Closed** 2024-03-16 01:23 UTC
Labels: Duplicate
