### ISSUE TITLE
Setting a property that has a getter but no setter fails silently at runtime

### ISSUE THREAD

**Issue by IceCreamYou** [Microsoft/TypeScript#10099] opened 2016-08-02 20:17 UTC
**TypeScript Version:**  1.8.10

**Code**

```ts
class Parent {
    private _x: number;
	get x() {
		return this._x;
	}
}

const p = new Parent();
p.x = 3;
console.log(p.x); // undefined
```

**Expected behavior:** TypeScript fails to compile because `x` is not settable. (The emitted JavaScript uses `Object.defineProperty()` which defaults the `writeable` config to `false`.)

**Actual behavior:** TypeScript compiles, and setting the property fails silently at runtime.

This can be worked around by just calling the accessor `getX()` instead of `get x()`, but it's still unexpected behavior for TypeScript to not complain at all here.

Also note that this is different than a `readonly x` property because getters are computed.

**Comment by RyanCavanaugh** [comment] 2016-08-02 20:33
Duplicate of #12.

Please search for issues before logging new ones. #9928 would be easily found by searching with key words from the title.
![image](https://cloud.githubusercontent.com/assets/6685088/17344039/7db0d074-58b5-11e6-81e1-e2d5d285f55f.png)

**Closed by RyanCavanaugh** 2016-08-02 20:33 UTC
Labels: Duplicate

**Comment by IceCreamYou** [comment] 2016-08-02 20:53
Thanks. I searched, but neglected to remove the default search parameter that restricts the results to open issues, so I missed #9928.
