### ISSUE TITLE
TS2345: Fails when both branches of a conditional generic are valid

### ISSUE THREAD

**Issue by ArnaudBarre** [microsoft/TypeScript#41590] opened 2020-11-19 02:19 UTC
**TypeScript Version:**  4.0.5, 4.1-beta, 4.2.0-dev

**Search Terms:**  TS2345 conditional generic

**Code**: ([Playground Link](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201112#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4BYAKCqQA9JY40IA7AZ3gBEUYkAFYGgDWSKHAC8cADwBJNgGEANqigoARsrh1eLACZs4aiBGUoWAPgAUAbypw4ANxSKArkgA0cVvIAWZgOYecMAKpqoaSFQAvgBccLaU9k6uSHEcUMAs-nAAPnAuekiYmUi6dl4svgGpcJblSc5ucXJKKuqa2kh6BjBQbnAA-HDpmdl5BbpFJbpwab2j7uUAlBLmjhDAuhSJwaFtEQPNeyjhyttRK+JrdTtS5vXSusAO5tbJ-QND+L7GbEj4USkAHoni8HkCgXAZCw4GZgpNnHAAO7QRQzGA+EIVJDIiAuNG4qBCNieNQueAYngAcgMLAgFJ8OLUwH8gQ4uzYbgeb0aOIAZHzdq0Tu1+YKpGSYDBWBUlIIhOJrJZLmtvH4skhLBMpixSgBCJZRczCqDAyXSixRcGQgAqmIMrBxfyQIAMIGgOMUwBEsMMLn8DykmTA5LgMAAnmAkOJ8LoeP9ZerAoqcVdE9VLEgAHQwE6BGBZ95IQ1wIH3W5lqhLbZUIA))

```ts
export const DatePicker = <IsClearable extends boolean>({
  value, onChange, isClearable
}: {
  value: string | undefined
  onChange: (
    value: IsClearable extends true ? string | undefined : string,
  ) => void;
  isClearable?: IsClearable;
}) => (
  <>
    <div>{value ?? "Choose"}</div>
    // In an ideal world this one would works, but that's not the biggest issue
    {value && isClearable && <button onClick={() => onChange(undefined!)}>Clear</button>}
    // This one seems more like a bug
    <input type="date" onChange={e => onChange(e.target.value)} />
  </>
);
```

**Expected behavior:** No error

**Actual behavior:** Argument of type 'string' is not assignable to parameter of type 'IsClearable extends true ? string | undefined : string'

**Comment by andrewbranch** [comment] 2020-11-24 22:19
Duplicate of #26933

**Closed** 2020-11-24 22:38 UTC
Labels: Duplicate
