### ISSUE TITLE
Understand Node's `assert()` as a type guard

### ISSUE THREAD

**Issue by jinwoo** [Microsoft/TypeScript#19622] opened 2017-10-31 21:46 UTC
**TypeScript Version:**  2.5.3

**Code**

For code like below:
```ts
function getFoo(): Foo {
  const a: Foo|null = null;
  // ...
  // some code that conditionally sets a to a Foo instance.
  // ...
  if (!a) throw new Error('a is not a Foo!');
  return a;
}
```
, typescript understand that `a` is non-null when returned from `getFoo()`.

But Node.js has its own [`assert` module](https://nodejs.org/dist/latest-v9.x/docs/api/assert.html), and it is not understood by typescript and we need a type-cast like below:

```ts
import * as assert from 'assert';

function getFoo(): Foo {
  const a: Foo|null = null;
  // ...
  // some code that conditionally sets a to a Foo instance.
  // ...
  assert(a);
  return a as Foo;
}
```

It'd be really great if typescript understands that the non-nullness has been already checked by the `assert()` call and `a` is non-null in this case.

**Comment by mhegazy** [comment] 2017-10-31 23:38
Duplicate of https://github.com/Microsoft/TypeScript/issues/10470 and https://github.com/Microsoft/TypeScript/issues/8655

this is a design limitation at the time being. the reachable code analysis happens at an earlier phase, before types are known, and that builds the control flow graph that is used later on. narrowing will use that graph.

**Closed** 2017-11-16 16:57 UTC
Labels: Duplicate
