### ISSUE TITLE
Debug failure in `startCachingPerDirectoryResolution`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#19077] opened 2017-10-10 20:49 UTC
I can't seem to reproduce this again, but I had opened `code-insiders` in the TypeScript repository as a whole and was in `Gulpfile.ts`. I've emailed the full logs to @sheetalkamat.
```
Error: Debug Failure. False expression.
    at Object.startCachingPerDirectoryResolution (/home/andy/.nvm/versions/node/v8.6.0/lib/node_modules/typescript/lib/tsserver.js:80528:22)
    at InferredProject.Project.updateGraphWorker (/home/andy/.nvm/versions/node/v8.6.0/lib/node_modules/typescript/lib/tsserver.js:81524:38)
    at InferredProject.Project.updateGraph (/home/andy/.nvm/versions/node/v8.6.0/lib/node_modules/typescript/lib/tsserver.js:81477:39)
    at InferredProject.Project.getLanguageService (/home/andy/.nvm/versions/node/v8.6.0/lib/node_modules/typescript/lib/tsserver.js:81207:26)
    at IOSession.Session.getApplicableRefactors (/home/andy/.nvm/versions/node/v8.6.0/lib/node_modules/typescript/lib/tsserver.js:84946:32)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/home/andy/.nvm/versions/node/v8.6.0/lib/node_modules/typescript/lib/tsserver.js:83920:61)
    at /home/andy/.nvm/versions/node/v8.6.0/lib/node_modules/typescript/lib/tsserver.js:85130:88
    at IOSession.Session.executeWithRequestId (/home/andy/.nvm/versions/node/v8.6.0/lib/node_modules/typescript/lib/tsserver.js:85121:28)
    at IOSession.Session.executeCommand (/home/andy/.nvm/versions/node/v8.6.0/lib/node_modules/typescript/lib/tsserver.js:85130:33)
    at IOSession.Session.onMessage (/home/andy/.nvm/versions/node/v8.6.0/lib/node_modules/typescript/lib/tsserver.js:85150:35)
    at Interface.<anonymous> (/home/andy/.nvm/versions/node/v8.6.0/lib/node_modules/typescript/lib/tsserver.js:86285:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mhegazy** [comment] 2017-10-10 23:02
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/18928

**Closed by mhegazy** 2017-10-10 23:02 UTC
Labels: Bug, Domain: TSServer, Duplicate
