### ISSUE TITLE
Salsa not working with require('path') with src folder

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#7001] opened 2016-02-10 15:47 UTC
_From @SteveALee on February 10, 2016 13:7_

I can't reopen #2850 but the original problem still stands and I can reproduce it

* Enable Salsa
* create a new npm module project (npm init -y)
* Install node typings
* Create a `src` sub folder and add the basic `src\jsconfig.json`
* Add the following to `src\test.js` - `var p = require('path').`

Intellisense does not work correctly on the `.`

Everything works with the files in the project root.

_Copied from original issue: Microsoft/vscode#2887_

**Comment by egamma** [comment] 2016-02-10 15:47
Moving to salsa for investigation

**Comment by SteveALee** [comment] 2016-02-10 16:43
Note moving `jsconfig.json` to project root seems to resolve the problem. 
Note the docs for the old javascript intellisense explicitly suggest having this file in src, client, server etc. folders if they exist

**Comment by SteveALee** [comment] 2016-02-10 16:54
Another observation: with a js file that is 2 folders below the root then when I enter `.` the menu does eventually appear. **After 17 seconds!!** I have Surface Pro 4 i7 with nothing else going on

**Comment by billti** [comment] 2016-02-10 17:09
For the first problem, this is by design. If you have your `jsconfig.json` file *below* where you installed the Node typings, then the typings are not part of the project (unless you explicitly reference them somehow by climbing above the root, e.g. `/// <reference path="../typings/node.d.ts/>`.

For the second issue, I've not seen any performance issues unless you have a lot of Node modules installed and are scanning all the JavaScript under here. Do you have `node_modules` listed in the `excludes` property (e.g. [this value](https://github.com/billti/ASPNET5-with-Angular2/blob/master/src/WebApplication2/scripts/tsconfig.json#L12))? Else Salsa is trying to read and analyze all the JavaScript for every node module installed (and all their dependencies, etc...).

**Comment by SteveALee** [comment] 2016-02-10 17:16
> For the first problem, this is by design

So the docs will need updating when Salsa becomes the default

> For the second issue, [snip] Do you have node_modules listed in the excludes property (e.g. this value)

Doah! Of course. Having moved the jsconfig up node_modules becomes relevant.

I'll move typings down to %projroot%\src along with jsconfig. That's should solve both issues.

Thank you!

**Comment by SteveALee** [comment] 2016-02-10 17:22
Interesting that this issue is closed but there is no audit entry say who closed it. Is this a git bug?

**Comment by billti** [comment] 2016-02-10 17:31
This issue we're typing in right now?? It's still open as far as I can see. I was waiting to here back before closing. (Note this issue was originally logged under the VSCode project, and that was closed/moved to this new TypeScript issue).

We have an issue active somewhere to exclude `node_modules` by default if no `excludes` or `files` is provided, so that should alleviate the need to add this manually for every project.

Thanks! (Will close now).

**Closed by billti** 2016-02-10 17:31 UTC

**Comment by egamma** [comment] 2016-02-11 09:24
@SteveALee regarding the docs

>Note the docs for the old javascript intellisense explicitly suggest having this file in src, client, server etc. folders if they exist

This is still correct also the jsconfig.json semantics hasn't changed between the old JS infrastructure and Salse. Having said this. I now see that we should add a hint in the docs that the typings folder needs to be inside the folder with the jsconfig.json.

This is tracked in issue microsoft/vscode-docs#152.

**Comment by SteveALee** [comment] 2016-02-11 09:56
Yes, adding a note on typings folder location will fix the confusion I experienced.
