### ISSUE TITLE
Smarter control flow analysis for null check 

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#10134] opened 2016-08-04 13:02 UTC
**TypeScript Version:**  2.0.0

**Code**

``` ts
class Test {
  foo: string | null;

  get hasFoo() {
    return this.foo !== null;
  }

  hasFoo2() {
    return this.foo !== null;
  }
}

function isNotNull(value) {
  return value !== null;
}

const test = new Test();

// works
if (test.foo !== null) {
  test.foo.toLowerCase();
}

// doesn't work
if (test.hasFoo) {
  test.foo.toLowerCase();
       // ^~~~ Object is possibly null.
}

// doesn't work
if (test.hasFoo2()) {
  test.foo.toLowerCase();
       // ^~~~ Object is possibly null.
}

// doesn't work
if (isNotNull(test.foo)) {
  test.foo.toLowerCase();
       // ^~~~ Object is possibly null.
}
```

It would be really nice, if the control flow analysis would check functions, methods and getters. This is really helpful for `strictNullChecks: true`.

**Comment by AdamWillden** [comment] 2016-09-09 18:53
I think I'm hitting the same issue, is this not the same as https://github.com/Microsoft/TypeScript/issues/8437 (which was 'fixed')?

**Comment by kitsonk** [comment] 2016-09-09 20:10
What you are really asking for is some sort of guard that you can describe, otherwise how would TypeScript understand what is going without deep introspection of methods.  To even have this in the realms of possibility, the return value needs to denote the guard.

Also, you are also implying you are asking for a negation guard as well.

Potentially, something like this:

```typescript
class Test {
  foo: string | null;

  get hasFoo(): this.foo is string {
    return this.foo !== null;
  }

  hasFoo2(): this.foo is string {
    return this.foo !== null;
  }
}

function isNotNull(value): value is not null {
  return value !== null;
}
```

Related, #5101 suggests inferred type guards, which could potentially solve some if these use cases.

#4183 discusses negation/subtraction types.

**Comment by DanielRosenwasser** [comment] 2016-09-09 20:16
Note that with `this`-type guards you could write something like

```ts
hasFoo(): this is this & { foo: string } {
    return this.foo !== null;
}
```

But this has to be on a method, not a get-accessor.

**Comment by donaldpipowitch** [comment] 2016-09-16 06:30
@DanielRosenwasser Is it by design that get-accessor can't use `this`-type guards or is there an open issue I can follow?

I really want do to more complex stuff like that:

```typescript
class FormValue<T> {
  @observable value: T;
  @observable error: FormError | null;

  @observable isPristine: boolean = true;
  @computed get isDirty(): boolean {
    return !this.isPristine;
  }

  @computed get isValid(): boolean {
    return this.error === null;
  }
  @computed get isInvalid(): boolean {
    return !this.isValid;
  }

  @computed get shouldShowErrors(): boolean {
    return this.isInvalid && this.isDirty;
  }
}

// and later somewhere
const Input = observer((props) => 
  <div>
    <input type="text" value={props.formValue.value}/>
    {props.formValue.shouldShowErrors ?
      <p>{props.formValue.error}</p> {/* error is possibly null here */}
    :
      null
    }
  </div>
)
```

It would be great if I could tell TypeScript:
- When `shouldShowErrors` is `true` this means...
- `isInvalid` is `true` which means...
- `isValid` is `false` which means...
- `error` must be a `FormError` and not `null`

**Comment by mhegazy** [comment] 2016-12-14 06:17
Duplicate of https://github.com/Microsoft/TypeScript/issues/11796 and https://github.com/Microsoft/TypeScript/issues/11117?

**Closed** 2016-12-29 19:34 UTC
Labels: Duplicate
