### ISSUE TITLE
Visual Studio Community 2013, Typescrip 1.4: When saving file, const enum doesn't resolve to constant when enum is defined in other file.

### ISSUE THREAD

**Issue by mpawelski** [Microsoft/TypeScript#1742] opened 2015-01-20 17:35 UTC
Hi,
I installed Visual Studio Community 2013 and Typescript 1.4. When I changed all my enums to const enum (btw, very nice feature, thanks!) I noticed that compile-on-save feature doesn't  handle this feature well.

When I use those const enums in other file than the one it was defined in then when I save file, they are not resolved to constant numbers.

For example I have file firstFile.ts:
```
const enum TestEnum {
    Foo, Bar
}

var testFirstFile = TestEnum.Bar;
```
and when I save file (by pressing Ctrl+S) i get file firstFile.js:
```
var testFirstFile = 1 /* Bar */;
//# sourceMappingURL=firstFile.js.map
```

but When i have secondFile.ts file:
```
/// <reference path="firstfile.ts" />

var testInOtherFile = TestEnum.Bar;
```
and save file I get secondFile.js:
```
/// <reference path="firstfile.ts" />
var testInOtherFile = TestEnum.Bar;
//# sourceMappingURL=secondFile.js.map
```

only when I build project in Visual Studio I get proper secondFile.js file:
```
/// <reference path="firstfile.ts" />
var testInOtherFile = 1 /* Bar */;
//# sourceMappingURL=secondFile.js.map
```

**Comment by mhegazy** [comment] 2015-01-20 18:32
this looks like a duplicate of #1599

**Comment by mhegazy** [comment] 2015-01-20 18:42
looking at it again, this does not look the same. issue #1599, would cause this scenario:
change firstfile.ts to update values of the enum
save it, the values are updated correctly in firstfile.ts but not in secondfile.ts. is that what you are seeing, i am not seeing the same behavior you mention above locally?

**Comment by mpawelski** [comment] 2015-01-20 22:04
I got this problem at work. I installed the newest Visual Studio Community 2013 and Typescript 1.4.

I have the same problem at home. Here I recorder video that demonstrate it (a little too long, sorry).
https://www.dropbox.com/s/4jbt41d1h1td0f0/typescript_const_enum_problem.mp4

**Comment by mhegazy** [comment] 2015-01-20 22:09
yup that is diffrent from #1599. looking more into it.

**Closed** 2015-01-23 23:19 UTC
Labels: Bug

**Comment by vytautas-pranskunas-** [comment] 2015-04-24 08:16
I have same problem. I see it is fixed already. Do you know when this will be available publicly and with what version. It is very important bug.

**Comment by DanielRosenwasser** [comment] 2015-04-24 08:23
@vytautas-pranskunas- it should be in for 1.5.

Also, 1.5 alpha is out now if you're interested.

**Comment by vytautas-pranskunas-** [comment] 2015-04-24 08:27
Should i replace only typescriptServices.js? 
When oficial 1.5 release is planned?

**Comment by vytautas-pranskunas-** [comment] 2015-04-24 08:36
btw: i have replaced typescriptServices.js file and now on save it does not generate any file and console sys: "Input file contained syntax errors. Output generation skipped."

I do not have any errors and on build everything works fine.
