### ISSUE TITLE
[...new Map()] and [...new Set()]

### ISSUE THREAD

**Issue by rabbitooops** [microsoft/TypeScript#32547] opened 2019-07-25 09:06 UTC
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
[...new Map()]
```

**Expected behavior:**
```ts
Array.from(new Map())
```

**Actual behavior:**
```ts
new Map().slice()
```

**Playground Link:** 

**Related Issues:**

**Comment by MartinJohns** [comment] 2019-07-25 15:37
Duplicate of #8856?

**Comment by RyanCavanaugh** [comment] 2019-07-25 17:31
Downlevel ES6 spread syntax into a call to an ES6 Array API... 🤔

**Closed by RyanCavanaugh** 2019-07-25 17:31 UTC
Labels: Duplicate
