### ISSUE TITLE
Type guard do not narrow array element accessed inline

### ISSUE THREAD

**Issue by caesarsol** [Microsoft/TypeScript#15492] opened 2017-05-01 14:33 UTC
**TypeScript Version:**  2.2.1

A type guard in a loop does not narrow an array element to its type inside the conditional.

On the opposite, the same works by accessing the array element using a variable in between.

This could be by design, but it's quite strange to me...

**Code**

```ts
declare function isNum(a: any): a is number
declare function acceptNum(c: number): void

let children: Array<string | number> = [3, 4, 5]

for (let i = 0; i < children.length; ++i) {
    if (isNum(children[i])) {
        acceptNum(children[i]); // error: Type string is not assignatable to type number 
    }
}

for (let i = 0; i < children.length; ++i) {
    const child = children[i];
    if (isNum(child)) {
        acceptNum(child); // no error
    }
}
```

[TS play demo here](https://www.typescriptlang.org/play/#src=declare%20function%20isNum(a%3A%20any)%3A%20a%20is%20number%0D%0Adeclare%20function%20acceptNum(c%3A%20number)%3A%20void%0D%0A%0D%0Alet%20children%3A%20Array%3Cstring%20%7C%20number%3E%20%3D%20%5B3%2C%204%2C%205%5D%0D%0A%0D%0Afor%20(let%20i%20%3D%200%3B%20i%20%3C%20children.length%3B%20%2B%2Bi)%20%7B%0D%0A%20%20%20%20if%20(isNum(children%5Bi%5D))%20%7B%0D%0A%20%20%20%20%20%20%20%20acceptNum(children%5Bi%5D)%3B%20%2F%2F%20error%3A%20Type%20string%20is%20not%20assignatable%20to%20type%20number%20%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afor%20(let%20i%20%3D%200%3B%20i%20%3C%20children.length%3B%20%2B%2Bi)%20%7B%0D%0A%20%20%20%20const%20child%20%3D%20children%5Bi%5D%3B%0D%0A%20%20%20%20if%20(isNum(child))%20%7B%0D%0A%20%20%20%20%20%20%20%20acceptNum(child)%3B%20%2F%2F%20no%20error%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A)

**Expected behavior:**
`children[i]` type narrowed to `number` inside the `if` body.

**Actual behavior:**
`children[i]` type is still `string | number` inside the `if` body.

**Comment by mhegazy** [comment] 2017-05-01 17:18
Duplicate of https://github.com/Microsoft/TypeScript/issues/10530

**Closed** 2017-05-01 17:22 UTC
Labels: Duplicate

**Comment by caesarsol** [comment] 2017-05-01 17:30
Sorry about that, I searched with various keywords and nothing popped out. Very few of the phrasing in common!
