### ISSUE TITLE
Allow emitting .js extension in module paths in compiled output

### ISSUE THREAD

**Issue by b-strauss** [Microsoft/TypeScript#6265] opened 2015-12-27 14:05 UTC
Module loaders like [systemjs](https://github.com/systemjs/systemjs) expect module paths to point to a valid file path, including the .js extension. Although [exploringjs](http://exploringjs.com/es6/ch_modules.html#_modules-in-javascript) says the extension might not be needed, the module loader spec's default behaviour has not yet been decided upon. So for code to have the widest possible support it would be good to have an option to tell the compiler to add the extension.

**Comment by vladima** [comment] 2015-12-28 18:21
looks like  a duplicate of #4595 ([this](https://github.com/Microsoft/TypeScript/issues/4595#issuecomment-137602265) comment)

**Closed by vladima** 2015-12-28 18:21 UTC
Labels: Duplicate
