### ISSUE TITLE
Nullable types can't be reconciled when they are parameterized keys

### ISSUE THREAD

**Issue by johnfn** [Microsoft/TypeScript#21182] opened 2018-01-14 20:25 UTC
**TypeScript Version:** 2.6.2

**Code**

```ts
type Rect = {
  width: number | undefined;
}

class HasARect<T extends Rect> {
  rect: T;

  get<K extends keyof T>(prop: K): T[K] {
    return this.rect[prop];
  }

  getWidth(r: T): number {
    return this.get("width") || 0; // Type 'undefined' is not assignable to type 'number'.
  }
}
```

**Expected behavior:**

This is not a type error.

**Actual behavior:**

```
Type 'T["width"]' is not assignable to type 'number'.
  Type 'number | undefined' is not assignable to type 'number'.
    Type 'undefined' is not assignable to type 'number'.
```

**Comment by mhegazy** [comment] 2018-01-17 01:08
narrowing does not occur on generic types, we need a higher order type operator to be applied here instead. see https://github.com/Microsoft/TypeScript/issues/15376#issuecomment-297160989 for more info.

duplicate of https://github.com/Microsoft/TypeScript/issues/14366

**Closed** 2018-01-31 17:39 UTC
Labels: Duplicate
