### ISSUE TITLE
tsc.exe doesn't work on Windows Server 2012

### ISSUE THREAD

**Issue by ahmelsayed** [Microsoft/TypeScript#11339] opened 2016-10-04 00:54 UTC
**TypeScript Version:**  2.0.3 

**Repro:**

1) Get a Windows 2012 Server instance.

2) use the following code 

`Test.ts`
```ts
class Test {
    test() {
        console.debug("Hey there!");
    }
}
```

`Test2.ts`
```ts
class Test2 {
    test() {
        console.debug("Hey there!");
    }
}
```

`tsconfig.json`
```json
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": true,
    "sourceMap": true,
    "target": "es6",
    "module": "amd",
    "outFile": "wwwroot/app/app.js",
    "strictNullChecks": true
  },
  "compileOnSave": true
}
```

3) copy `C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.0\` to the VM (or install `TypeScript_Dev14Full.exe`)

3) run `C:\temp\TypeScript\2.0\tsc.exe`

**Expected behavior:**
To Work. It works fine on 2012 R2 and Windows 10 Client

**Actual behavior:** 

```
Script failed with error: 'JsErrorScriptException (0x30001)'.
Unable to get property 'length' of undefined or null reference
TypeError: Unable to get property 'length' of undefined or null reference
   at compareStrings (Unknown script code:672:17)
   at compareStringsCaseInsensitive (Unknown script code:684:9)
   at Array.prototype.sort (native code)
   at matchFileNames (Unknown script code:39261:9)
   at getFileNames (Unknown script code:39139:13)
   at parseJsonConfigFileContent (Unknown script code:39089:9)
   at parseConfigFile (Unknown script code:39654:13)
   at performCompilation (Unknown script code:39676:21)
   at executeCommandLine (Unknown script code:39627:9)
   at Global code (Unknown script code:39945:1)
```

**Some observations:**
This only happens if you have more than 1 `.ts` file.

**Comment by davidebbo** [comment] 2016-10-04 00:56
To add to this, Windows Server 2012 is what's used throughout Azure App Service today, so this bug is effectively making the new TypeScript unusable on that platform.

**Comment by vladima** [comment] 2016-10-04 03:40
this looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/11110 that was already fixed in master (fix was also [ported](https://github.com/Microsoft/TypeScript/pull/11268) into release 2.0.5). Can you try nightly build to check if you still see the error?

**Comment by ahmelsayed** [comment] 2016-10-04 05:47
@vladima would you mind pointing me to where I can get that build to try? I only picked up released versions of TypeScript from typescriptlang.org before and have no idea where to get a nightly build from

**Comment by davidebbo** [comment] 2016-10-10 21:45
@vladima any idea where we can pick up a build to test this? Or when do you expect it to make it into a real release? Thanks!

**Comment by vladima** [comment] 2016-10-10 22:43
the fix was already checked in into release-2.0.5 and thus will go into the next release. Also it was [cherry-picked](https://github.com/Microsoft/TypeScript/pull/11496) into `master`  and should be available in should today's nightly builds on `npm` (check `typescript@next`) or [myget](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#using-nuget-with-msbuild)

**Comment by ahmelsayed** [comment] 2016-10-11 17:35
When is the next release scheduled? To iterate David's comment, we can't support TypeScript on Azure App Service until we have a build of tsc that works with msbuild on Windows Server 2012.

**Comment by mhegazy** [comment] 2016-10-11 18:14
Looking at this more, this is not the same issue as #11110. It looks related though. so we need to get a different fix in.

**Comment by mhegazy** [comment] 2016-10-25 19:53
@ahmelsayed, [TypeScript 2.0.6](https://github.com/Microsoft/TypeScript/releases/tag/v2.0.6) should be available now; please give it a try and let us know if there are other issues.

**Closed by mhegazy** 2016-10-25 19:53 UTC
Labels: Bug, Fixed, High Priority

**Comment by watashiSHUN** [comment] 2017-01-10 23:40
@mhegazy Did this by any chance not make it into 2.1? We see the same error again running 2.1.4 on Windows Server 2012

**Comment by mhegazy** [comment] 2017-01-11 02:15
That is a new issue then. Please create a new issue and share some context for us to be able to reproduce and diagnose.
