### ISSUE TITLE
Infering by nested kind

### ISSUE THREAD

**Issue by jozefchutka** [microsoft/TypeScript#48383] opened 2022-03-23 11:27 UTC
# Bug Report

### 🔎 Search Terms

infer, kind, nested

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiDyAjAVhAxsKBeKUDeAsAFACQAThAIYAmA9gHYA2IUA1gJb3UBceHX3AESVBAbgC+o4rgo0GzKJW4BnYGU4BzKUXFQAPvmLkqdJi348+nHoMRjJxccWJoGqqGlnBoOABQBKbjgkVAxsAD4oXzwlQUEAGjZrXgshEXFxf21XencAWwhqdkpsDy8IAO0CosoAOgt662wsHGFBKAAyDqhq4trKUSA)

### 💻 Code

```ts
type MyObject =  {
	readonly kind:{kind:"a";};
  readonly a:string;
} | {
	readonly kind:{kind:"b";};
}

const create = ():MyObject => ({a:"", kind:{kind:"a"}});
const media = create();
media.kind.kind === "a" && media.a; // Property 'a' does not exist on type 'MyObject'.
```

### 🙁 Actual behavior

Compiler throws error on the last

```
Property 'a' does not exist on type 'MyObject'.
  Property 'a' does not exist on type '{ readonly kind: { kind: "b"; }; }'.
```

### 🙂 Expected behavior

By type definition, compiler has enough information to resolve that property `a` does exist on my object b/c there is no other option for `media.kind.kind === "a"`

**Comment by fatcerberus** [comment] 2022-03-23 12:15
Duplicate of https://github.com/microsoft/TypeScript/issues/18758

**Closed** 2022-03-26 18:00 UTC
Labels: Duplicate
