### ISSUE TITLE
High CPU usage from Visual studio process

### ISSUE THREAD

**Issue by KamyarNazeri** [Microsoft/TypeScript#250] opened 2014-07-25 18:25 UTC
Migrated issue from codeplex:
https://typescript.codeplex.com/discussions/472439
https://typescript.codeplex.com/workitem/2386
https://typescript.codeplex.com/workitem/779

I'm yet experiencing very high cpu usage from *VS2013 update 3 RC* and I'm just wondering if there is any update on this?
The cpu usage is higher with refactoring large .ts files!

For the record:
- I'm using *VS2013 update 3 RC* on an i7 machine with 8G ram, Win7
- I'm having *Compile on save* disabled
- No resharper/web essentials installed!
- Auto-sync javascript references is disabled
- I'm having separate .ts file for each class

**Comment by rcollette** [comment] 2015-02-14 21:45
I'm seeing a constant CPU utilization of 13% on an i7.   I ran a profiler session and it appears to show that the hot path is TypeScriptLanguageService.ScriptContext.OpenProjectOnItemAdded\IsTypeScriptFileOrFolderThatContainsTypeScriptFiles\IsFolderThatContainsTypeScriptFiles\System.Linq.Enumerable.Any(class System.Collections.Generic.IEnumerable`1<!!0>)

This project contains node_modules and bower_components (renamed to components) folders that are relatively large and deep.  So much so that the VS GIT source control provider no longer works.  I suppose this could be part of the issue but it still seems odd that it would bog down the machine to the point that the UI doesn't respond well (cursor hesitation, scroll hesitation) and the laptop fan is going pretty strong.

The project is here but you'll have to run npm install and bower install from the project director after getting it from github.
https://github.com/rcollette/RequireAngularTS

See attached profiler report
[TypeScriptCPUUtilization.vsps | uploaded via ZenHub](https://files.zenhub.io/54dfc182ca68774f4199d414)

**Comment by rcollette** [comment] 2015-02-15 04:50
Turning off "show all files" in solution explorer seems to be a work around.   This removes my bower modules directory and node_modules directory from solution explorer and it seems to drop back to normal cpu utilization.   Since I am building with gulp watch, my project does not include nested js files in the solution, so getting to the built files is cumbersome without show all files enabled.

**Comment by rcollette** [comment] 2015-02-15 04:52
Another impact of this is that I am unable to rename files while it is in this high cpu utilization mode.   I use the rename context menu, the name briefly appears editable but at best I can enter one character and then the file name switches back to being uneditable.

**Comment by mhegazy** [comment] 2015-02-16 06:43
@rCollette which version are you using? @vladima had a couple of fixes related to thus in the last release (1.4).

**Comment by rcollette** [comment] 2015-02-16 16:25
I am using 1.4 in VS 2013.

**Comment by vladima** [comment] 2015-02-16 21:53
Interestingly enough everything works like charm on my machine

-  do you have any 3rd party VS extension installed for this version of VS?
- can you make a heap dump using Process Explorer or ProcDump at the moment when CPU usage spikes and upload it somewhere?

**Comment by rcollette** [comment] 2015-02-19 17:54
I will try to get to this by at least this weekend.   Sorry for the delay.   I will use procexp to create a full dump and upload it.     In the mean time, if you know of an easy way to disable all extensions except one such that I can then put them back, that would help.  I've been searching around for how to do this but haven't found anything.    I am using several different extensions.

**Comment by vladima** [comment] 2015-02-19 18:32
ProcDump can monitor the application for CPU spikes and create a dump when CPU usage reaches the threshold.

**Comment by NoelAbrahams** [comment] 2015-02-20 10:56
VS 2015 CTP 5 also has problems.

Opened up the solution this morning (contains in excess of 600 TypeScript files) and editing was extremely slow.

Here's what task manager had:

![bbb](https://cloud.githubusercontent.com/assets/1106823/6284977/79461a2a-b8ee-11e4-9cb0-31993d79ed7e.gif)

This has been going on for about 8-10 minutes in spite of no edits being made.

I'm using TS 1.4

**Comment by vladima** [comment] 2015-02-20 19:00
@NoelAbrahams to clarify whether it is a TypeScript issue can you make a heap dump (using Process Explorer\ProcDump ) when CPU spikes and share it?

**Comment by mhegazy** [comment] 2015-02-20 23:01
@NoelAbrahams your stack trace points to the HTML editor, I have communicated that to the HTML Editor team, and they are aware of the issue and working on a fix. thanks for reporting it!

**Comment by rcollette** [comment] 2015-02-22 22:33
I've uploaded my dump file but would prefer to private message the link to it.  Would someone mind sending an email address to richard dot collette chat gmale dot com (replace the dot, chat and gmale words appropriately please).

**Comment by rcollette** [comment] 2015-02-23 02:04
Link to dump file has been shared with @vladima

**Comment by rcollette** [comment] 2015-02-28 23:23
@mhegazy - My issue is likely an extension.  I've shut every extension I could off and I can now toggle between hide/show all and it's almost instantaneous.   I'll update when I figure out which one it is.  Sorry if this is a wild goose chase.   Curious if this turns out to be Web Essentials.

**Comment by rcollette** [comment] 2015-03-01 03:36
@vladima - It appears to be the Tangible T4 Editor extension that is causing the problem.  I turned off all extensions, that could be turned off, except the T4 editor and the problem remained.  It could be exacerbated by other extensions because eventually the high CPU usage did settle down whereas with other extensions enabled, it seemingly runs at high CPU forever while all files are shown.   I'm not sure why the profiler hotpath was pointing at TypeScript but I suppose it's not impossible that the T4 editor is doing something which in turn makes TypeScript look like it is slow.   In any case, if the T4 editor is turned off, there are no issues so I know this is the root of at least my problem.   Sorry if this was a sidetrack.

**Comment by vladima** [comment] 2015-03-01 19:27
@rcollette got it, thanks for sharing this information. I took a look into the dump file and it does not seem that CPU is doing anything TypeScript related (which confirms your observations). Since the root cause of the problem is not TypeScript related I'm going to close this issue - feel free to create a new one if you think that the problem still exists and we can do something on the TypeScript side to fix it..

**Closed by vladima** 2015-03-01 19:27 UTC
Labels: Visual Studio
