### ISSUE TITLE
Is it possible to use Enum without knowing it's definition inside function calls

### ISSUE THREAD

**Issue by pietrasiak** [Microsoft/TypeScript#15979] opened 2017-05-21 11:24 UTC
Lets say we have enum like:
```
enum SportType {
  Football, Basketball, Hockey,
};
```

and then we have function that is using it

```
export function doSomethingWithSport(sport: SportType) {
  // doing something
}
```

Later on, when we use this function (possibly in totally different file), we use it like:

```
doSomethingWithSport(SportType.Football)
```
note it requires `SportType` to be imported inside local scope.

**But hey, as long as we know exactly what matching type is here, why not make it possible to use it like:**

```
doSomethingWithSport(.Football)
```

Since it's known that by `.Football` in this context we mean `SportType` enum, it'd be quite convinient to do it this way (you don't need to import enums alongside with function itself)

Is there such option in Typescript or is it planned?

It'd also be handy with `switch` etc like in Swift lang: https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Enumerations.html

**Comment by mhegazy** [comment] 2017-05-22 17:06
Duplicate of https://github.com/Microsoft/TypeScript/issues/1713 and https://github.com/Microsoft/TypeScript/issues/8964

**Comment by mhegazy** [comment] 2017-06-06 16:42
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-06-06 16:42 UTC
Labels: Duplicate
