### ISSUE TITLE
Decorators, allow @D and @D() to be the same

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#3830] opened 2015-07-12 17:01 UTC
If there's a decorator that takes all optional parameters it's easy to mistake and write
```
@decorator class A {}
```
instead of
```
@decorator() class A {}
```
The problem is that there's no warning and the decorator function does not get called at all. 

I suggest to make the parameterless version `@decorator` to be the same thing of `@decorator()`, thus avoiding confusion.

**Comment by DanielRosenwasser** [comment] 2015-07-12 18:46
What is the type returned by `@decorator()` in your example?

This has been brought up on https://github.com/Microsoft/TypeScript/issues/2249#issuecomment-104235451, and I think @JsonFreeman sufficiently explained why this wouldn't be an acceptable change:

https://github.com/Microsoft/TypeScript/issues/2249#issuecomment-104849392
https://github.com/Microsoft/TypeScript/issues/2249#issuecomment-104955635
https://github.com/Microsoft/TypeScript/issues/2249#issuecomment-104978543

Specifically:
> It seems like this request hinges on the idea that decorator factories are the canonical way to use decorators, but I don't see how this allows the user to define and use raw decorators. If I define a decorator `F`, and the application `@F` gets treated as `@F()`, then the result of calling F is used as the decorator, instead of F itself. Are you suggesting we give an error somewhere if someone tries to apply a raw decorator instead of a decorator factory?

**Comment by DanielRosenwasser** [comment] 2015-07-12 18:48
The reason I ask about the type returned by `@decorator()` is that I realize that this may be caused by a bug we had: #3246

**Comment by nippur72** [comment] 2015-07-13 07:21
Sorry for the duplicate, it gets harder and harder to search among all issues...

@DanielRosenwasser yes it's the bug #3246, my code is like this:
```TypeScript
// @computed decorator
function computed(ob?: polymer.Property) {   
   return (target: polymer.Element, computedFuncName: string) => {
      // ...
   }
}
```

but using it as 
```
@computed myprop: string;
```
does not produce any error.

**Comment by DanielRosenwasser** [comment] 2015-07-13 08:02
No worries! Just wanted to make sure that was the problem before closing.

**Closed by DanielRosenwasser** 2015-07-13 08:02 UTC
Labels: Declined, Duplicate, Needs More Info, Suggestion
