### ISSUE TITLE
Nested class's private field has inconsistent name in declaration file under watch mode

### ISSUE THREAD

**Issue by alvinleung1996** [microsoft/TypeScript#47490] opened 2022-01-18 16:18 UTC
# Bug Report

### 🔎 Search Terms

private field declaration

### 🕗 Version & Regression Information

v3.8.3, v4.5.4, v4.6.0-dev.20220116

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAMwK4DsDGMCWEWNWgCgEo4BvAWACg4a4pgYkpc0AbAQwGdO4BBMqrSFwAxAkzBWAEzgBeOAHIFg2gF8q6ykA)

### 💻 Code

```ts
export function func() {
    return class A {
        #field = ''
    }
}
```

### 🙁 Actual behavior

In watch mode, the name of the private field in the declaration file is not consistent after rebuild.

The initial build emits the following declaration: 

```ts
export declare function func(): {
    new (): {
        "__#1@#field": string;
    };
};
```

Do some changes in the source file, for example:

```ts
export function func() {
    return class A {
        #field = 'a'
    }
}
```

The output becomes:

```ts
export declare function func(): {
    new (): {
        "__#12@#field": string;
    };
};
```

Undo the change. The output becomes:

```ts
export declare function func(): {
    new (): {
        "__#16@#field": string;
    };
};
```

The number in the emitted private field name seems to increase after each rebuild.

### 🙂 Expected behavior

The emitted private field name is consistent across rebuild and should be named `#private`.

```ts
export declare function func(): {
    new (): {
        #private;
    };
};
```

**Comment by MartinJohns** [comment] 2022-01-18 16:33
Duplicate of #36548. Used search terms: `private emit in:title`

**Closed** 2022-01-21 18:00 UTC
Labels: Duplicate
