### ISSUE TITLE
Pipeline Operator but for Generic Types

### ISSUE THREAD

**Issue by hazae41** [microsoft/TypeScript#35712] opened 2019-12-16 22:12 UTC
## Search Terms

pipeline operator
generic types

## Suggestion

A pipeline operator but for generic types

## Use Cases

This would be less ugly and more readable

## Examples

The following

    Promise<Signed<Message<String>>>

would become

    Promise of Signed of Message of String

On an interface

    interface Duck {
        quack(): Promise of String;
    }

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jcalz** [comment] 2019-12-18 14:53
Near-duplicate of #34165

**Comment by dragomirtitian** [comment] 2019-12-18 15:02
Similarly to #34165 I find the readability claim debatable.

Also what happens with generics with multiple type parameters ? would you use `G of T1 and T2` ? How would you disambiguate something like `G1 of G2 and T1 and T2` is that `G1<G2<T1, T2>>` or `G1<G2<T1>, T2>`.  While the angle brackets are not the prettiest bit of syntax they do make it clear where one type ends and the other continues.

**Comment by hazae41** [comment] 2019-12-18 15:31
Promise of String
Promise of (String and number)

**Comment by jcalz** [comment] 2019-12-18 15:47
Parentheses are too close to angle brackets for my taste; no human being uses parentheses or angle brackets to communicate.  Instead of punctuation we should use a keyword to signify where a generic parameter list ends.  Since reusing existing keywords is preferable to coining new ones (and helps the environment), a good one to use for this would be `finally`, which does a good job of signaling the end of something.   And instead of `and`, a new keyword, we could re-use `with`, which is just sitting around gathering dust anyway.  Anyway, that means we can turn the completely incomprehensible

```ts
Pick<Map<string, Promise<number>>, "get">
```

into the human-friendly

```ts
Pick of Map of string with Promise of number finally finally "get" finally
```

:trollface:

**Comment by RyanCavanaugh** [comment] 2019-12-20 00:29
@jcalz 😬

We're extremely conservative around adding syntax to the type space; new syntax needs to have very concrete upsides

**Closed by RyanCavanaugh** 2019-12-20 00:29 UTC
Labels: Declined, Suggestion
