### ISSUE TITLE
Type narrowing with instanceof and or-check does not seem to work

### ISSUE THREAD

**Issue by eugenio-bolt** [microsoft/TypeScript#45726] opened 2021-09-04 21:11 UTC
# Bug Report

Using `instanceof` inside an if-check with an `||` condition does not seem to narrow down types. A detailed
example is provided in the Playground link below.

### 🔎 Search Terms

narrowing

### 🕗 Version & Regression Information

I have verified this occurs on all version of TS available in the playground, including the Nightly build.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type narrowing

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210904#code/C4TwDgpgBAShDOBXANsKBeKBvAsAKCimQHsBDAEwEsA7AcwC4pgAnRCAGnwF8oAfbfIRIUaDKADNSyeB0FRypYKUbwWovlACizZsWac8XANz584xNQDGwSsWpRaEYHCSoAFAEpGLlGlwEoZidEZnssIjIqOkZJaQ55RWUoaggAdy0dPTcAIgAJCGQSAEJsjygublM8GmAIZklLaABJABlI0QB5Zm1dZgEAoNdgRn9CIXboplZZAJ5+UbHhKLFYmQMxhKVGHr118sq8MwtrW3sQNzBSZlIAW0ZWidouneYvKAA3YkpyfsJKcQuV1uADpBr5gUtRGUFoRLHZ4MRkBAIcRaDlIXRSiZZlACjJfmM4dQEUiUWjLtcbqCEOCFEpgTcEPBSI4PNjCBVDFVzFYbHYoAAPTwEomqQIYBxOHzuNlyAD0cqgABUABaUeDJK66VLqcjEBDJYhoVJ6ADWcn+UDczBRIjoGHQmBYbD4-BtdNIUBoqlIVggxHEGV60LkhAVyvA0AA5NLgFGvRrqEaoKR4PBKLRqKQAEZIpjEJiRqBR8IYsTOiBGcoaUuPGJSGRVj3bTLMKtcKPA0NQcNKosliJ2lYNyubJKqZjqfgvdvx9WGtCp9OZnN54AF0CQYu1oeMCvtmuD5b1uJNxIt3qzrsBMOKwh9rcDssnxtjlRqe3T1uzhMLlNpjMs1zaB10LR8d2PCQRzPLYgz0K9u3DDYHwNAMoDAXRIGYUBiw9eMrmgGg4RuS4bGA68NiQjYI0fCcpzg5g50TZMl0A1cQI3fsXk7RC72o+9+zougmL-ViV2A-MwOjbjgTcAAmABmOS5I8btziwMFUEYZguFlWYqlvZU1UTLViB1e0TWYU14AtQNrVtZYHSdaYQxvKB1M04ZAl09l9i5Q48CFNkgA)

### 💻 Code

```ts
type Result = {
  loading: true,
} | {
  loading: false,
  data: string | Error,
};

function getResult(): Result {
  return { loading: false, data: new Error("Hello!") }
}

interface ILoadingOrError {
  result: {
    loading: true,
  } | {
    loading: false,
    data: Error,
  }
}

function y(param: ILoadingOrError): void {
  if(param.result.loading) {
    console.log("loading");
  } else {
    console.log(param.result.data.message);
  }
}

function x() {
  const r = getResult();
  // This narrowing does not work
  if (r.loading === true || r.data instanceof Error) {
    // Type 'Result' is not assignable to type '{ loading: true; } | { loading: false; data: Error; }'.
    // Type '{ loading: false; data: string | Error; }' is not assignable to type '{ loading: true; } | { loading: false; data: Error; }'.
    //   Type '{ loading: false; data: string | Error; }' is not assignable to type '{ loading: false; data: Error; }'.
    //     Types of property 'data' are incompatible.
    //       Type 'string | Error' is not assignable to type 'Error'.
    //         Type 'string' is not assignable to type 'Error'.(2322)
    y({result: r});
  }

  // This narrowing works
  if (r.loading === true) {
    y({result: r});
  }
}

x();
```

### 🙁 Actual behavior

The `result` variable is not being narrowed such that it can match `ILoadingOrError`.

### 🙂 Expected behavior

I would expect to be able to pass `{result: r}` to function `y`:
* In the case where `r.loading === true`, `r` is guaranteed to be of the form `{loading: true}`.
* In the case where `r.data instanceof Error`, `r` is guaranteed to be of the form `{loading: false, data: Error}`

**Comment by MartinJohns** [comment] 2021-09-04 22:50
Duplicate of #32595.

**Closed** 2021-09-10 18:00 UTC
Labels: Duplicate
