### ISSUE TITLE
Large composite project crashes tsserver.js with "Debug Failure. False expression."

### ISSUE THREAD

**Issue by leemhenson** [microsoft/TypeScript#26546] opened 2018-08-20 12:02 UTC
**TypeScript Version:**  3.1.0-dev.20180818

**Search Terms:** Debug Failure False Expression

**Code**

My project contains a single package which is built from:

```
/src
  /directoryA
  /... 29 other directories
/tests
  /tsconfig.json 
  /directoryA
  /... 29 other directories
/tsconfig.json
```

Each directory under `src` has it's own composite tsconfig.json, and they form a DAG. There is also a tsconfig under `tests` that references each and every directory under `src`. The root directory contains a tsconfig that references every tsconfig under `src` and `tests`.

**Expected behavior:**

`tsc --build` should succeed and I should be able to browse the code in vscode without issue.

**Actual behavior:**

`tsc --build` succeeds, and I can browse code under `src` in vscode without issue. However, when I open up a file inside `tests`, the following error is emitted in the tsserver.log:

```
Debug Failure. False expression.

    Error: Debug Failure. False expression.
    at mergeSymbol (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29937:26)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30033:49
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30032:20)
    at mergeSymbol (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29957:21)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30033:49
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30032:20)
    at mergeSymbol (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29962:21)
    at mergeModuleAugmentation (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30061:34)
    at initializeTypeChecker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:54898:25)
    at Object.createTypeChecker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29781:9)
    at Object.getTypeChecker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83198:79)
    at synchronizeHostData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:111305:21)
    at Object.getProgram (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:111378:13)
    at ConfiguredProject.Project.updateGraphWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115433:53)
    at ConfiguredProject.Project.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115381:42)
    at ConfiguredProject.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115751:61)
    at ProjectService.addFilesToNonInferredProjectAndUpdateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:116821:25)
    at ProjectService.createConfiguredProject (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:116837:22)
    at ProjectService.openClientFileWithNormalizedPath (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:117243:44)
    at IOSession.Session.openClientFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118832:37)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118037:31)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119496:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119487:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119496:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119516:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120770:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
Info 1390 [12:54:10.751] response:
    {"seq":0,"type":"response","command":"open","request_seq":2,"success":false,"message":"Error processing request. Debug Failure. False expression.\nError: Debug Failure. False expression.\n    at mergeSymbol (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29937:26)\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30033:49\n    at Map.forEach (<anonymous>)\n    at mergeSymbolTable (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30032:20)\n    at mergeSymbol (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29957:21)\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30033:49\n    at Map.forEach (<anonymous>)\n    at mergeSymbolTable (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30032:20)\n    at mergeSymbol (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29962:21)\n    at mergeModuleAugmentation (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30061:34)\n    at initializeTypeChecker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:54898:25)\n    at Object.createTypeChecker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29781:9)\n    at Object.getTypeChecker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83198:79)\n    at synchronizeHostData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:111305:21)\n    at Object.getProgram (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:111378:13)\n    at ConfiguredProject.Project.updateGraphWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115433:53)\n    at ConfiguredProject.Project.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115381:42)\n    at ConfiguredProject.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:115751:61)\n    at ProjectService.addFilesToNonInferredProjectAndUpdateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:116821:25)\n    at ProjectService.createConfiguredProject (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:116837:22)\n    at ProjectService.openClientFileWithNormalizedPath (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:117243:44)\n    at IOSession.Session.openClientFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118832:37)\n    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118037:31)\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119496:88\n    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119487:28)\n    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119496:33)\n    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119516:35)\n    at Interface.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120770:27)\n    at emitOne (events.js:116:13)\n    at Interface.emit (events.js:211:7)\n    at Interface._onLine (readline.js:282:10)\n    at Interface._normalWrite (readline.js:424:12)\n    at Socket.ondata (readline.js:141:10)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at Pipe.onread (net.js:594:20)"}
```

The typescript process is then dead on that file, not even a `Loading...` hover. The following process in process explorer seems to be stuck:

```
electron_node electronForkStart.js tsserver.js
  electron_node typingsInstaller.js tsserver.js typesMap.js
```

**Comment by sheetalkamat** [comment] 2018-08-20 21:43
Also apart from that you should submit tsserver log to be able to understand the issue.
You can also upload logs using 
1. With "typescript.tsserver.log": "verbose" enabled
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. Run ```code --upload-logs``` on the command line (or ```code-insiders --upload-logs``` if using vscode insiders) and follow instructions
5. Share the log file ID

**Comment by leemhenson** [comment] 2018-08-21 08:52
A smidge more data:

```
$ tsc --diagnostics
Files:           934
Lines:        114371
Nodes:        597497
Identifiers:  222348
Symbols:      357365
Types:        126168
Memory used: 457463K
I/O read:      0.12s
I/O write:     1.01s
Parse time:    3.00s
Bind time:     0.97s
Check time:    6.17s
Emit time:    13.48s
Total time:   23.63s
```

@sheetalkamat `Upload successful! Log file ID: 2797946071`

@RyanCavanaugh This project is private so I can't share it, and as you can see from the diagnostics it's pretty big! If the data in the uploaded log files isn't enough to figure out the issue I'll try to recreate it on a smaller scale.

**Comment by sheetalkamat** [comment] 2018-08-21 20:04
@leemhenson From the shared log, nothing stood out. From the log it seems project has 1343 files being added to it (compared to tsc 934 as per your shared data) That's the only thing standing out as such. We would need repro to investigate this and tsserver log is not enough.

**Comment by sandersn** [comment] 2018-08-23 16:44
@leemhenson One option would be for us to sign an NDA, if that would allow us to look at your original code.

**Comment by leemhenson** [comment] 2018-08-24 15:51
I'm a bit snowed under at the moment but I'll try to work up a repro. If not I'll see about the NDA route.

**Comment by drew-y** [comment] 2018-10-08 16:55
I am also having this problem on a similar project. It's private as well but I'd be more than willing to provide access to the project.

**Comment by sandersn** [comment] 2018-10-08 17:46
@drew-y Thanks! I'll contact you over e-mail to talk about how to get access.

**Comment by gavinpc-mindgrub** [comment] 2019-02-15 18:02
I have also run into this on a large composite project.  The build will work fine one minute then it will get into this state, and reverting my most recent change doesn't restore the build.  I will put together a repro case as soon as possible.

In the meantime, I have been able to work around it by doing a clean (removing existing build artifacts) and building again.  If that is the case for the OP, it may be a clue.  In any case, it may help others hitting this.

**Comment by wolcotts** [comment] 2019-05-04 08:57
Here's a 100% repro w/two .ts and three tsconfig files running tsc version 3.4.5. Cmdline: "tsc --build src"

[ts_throw_e.zip](https://github.com/Microsoft/TypeScript/files/3144166/ts_throw_e.zip)

**Comment by sandersn** [comment] 2019-05-17 17:21
@wolcotts your error is fixed in typescript@next. It's a duplicate of https://github.com/microsoft/TypeScript/issues/30591. However, that code didn't exist when this issue was filed, so I don't think it's the same cause.

**Comment by sandersn** [comment] 2019-05-17 17:27
Looking back at my e-mail, @drew-y's problem was fixed in 3.1.4. It's just @leemhenson's bug that is outstanding. I could be wrong, though, and maybe the code did exist already, so it could in fact be the same issue that @wolcotts saw.

@leemhenson can you test with typescript@next or typescript@rc?

**Comment by leemhenson** [comment] 2019-05-18 20:28
Hey @sandersn, I no longer work at that company so don't have access to that project to test. I'm 99% certain it's the same problem I reported here:

https://github.com/microsoft/TypeScript/issues/30429

I just updated the repro project listed there to `typescript@next`, but that has not helped:

https://github.com/leemhenson/project-refs-oom-repro/commit/97c54910acb08d622f40198035a2570c0e89901b

**Comment by sandersn** [comment] 2019-05-20 16:40
Thanks. You've done a lot of work on this one. I'll close this as a duplicate of #30429 since it looks like the oomemory is the blocker now, not the mergeSymbol assertion.

**Closed by sandersn** 2019-05-20 16:40 UTC
Labels: Bug, Crash

**Comment by zpdDG4gta8XKpMCd** [comment] 2019-05-21 03:36
we just got bitten by this very issue when we tried to switch to composite builds

**Comment by sandersn** [comment] 2019-05-21 18:07
@zpdDG4gta8XKpMCd Which issue? An assert with a stack ending in mergeSymbol? Or does the build run out of memory?

**Comment by zpdDG4gta8XKpMCd** [comment] 2019-05-21 22:01
build runs out of memory, no matter how much we give it via `--node --max_old_space_size=XXXXX`
