### ISSUE TITLE
Proposal: template string types and regex string types

### ISSUE THREAD

**Issue by streamich** [Microsoft/TypeScript#19114] opened 2017-10-11 21:46 UTC
Allow string types to be regular expressions `/#[0-9]{6}/` and allow nesting types into regular expressions `${TColor}`:

```ts
type TColor = 'red' | 'blue' | /#[0-9]{6}/;
type TBorderValue = /[0-9]+px (solid|dashed) ${TColor}/
```

Result:

```ts
let border1: TBorderValue = '1px solid red'; // OK
let border2: TBorderValue = '1px solid yellow'; // TSError: .....
```

Use case: there is a library dedicated to writing "type-safe" CSS styles in TypeScript [`typestyle`](https://github.com/typestyle/typestyle). The above proposed functionality would help greatly.

**Comment by mhegazy** [comment] 2017-10-11 22:58
Duplicate of https://github.com/Microsoft/TypeScript/issues/6579

**Closed** 2017-10-11 23:34 UTC
Labels: Duplicate
