### ISSUE TITLE
Inconsistencies within types for ObjectConstructor methods, appeal to revisit the Object.keys discussion

### ISSUE THREAD

**Issue by dpchamps** [microsoft/TypeScript#45835] opened 2021-09-11 23:54 UTC
# lib Update Request

@jcalz has enumerated a non-exhaustive list [here](https://github.com/microsoft/TypeScript/issues/45390#issuecomment-895661910), the issue template links to the [SO Answer](https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript). I'm aware of these resources, I know that this comes up quite frequently, but it would be greatly appreciated if you would hear me out :pray: 

It's instructive to go way back to 2016 with [this comment](https://github.com/microsoft/TypeScript/pull/12253#issuecomment-263132208) in a follow-up PR to #12207 -- which will be relevant in a few seconds.

>  Once you move to the instantiated type world it degenerates because an object can (and often does) have more properties at run-time than are statically known at compile time.

@RyanCavanaugh sort of codifies these hesitations in the SO answer. The crux of this argument is that a more-precisely typed `Object.keys` is potentially unsound. We get a first hand demonstration of this by observing some well-typed program that would produce runtime errors.

**But TS is already in this state** where very similar code, is A) well-typed, but B) will produce runtime errors. This comes down to how `Object.values` and `Object.entries` are typed. 

See two examples here, using `Object.values`:

* [Case Number 1](https://www.typescriptlang.org/play?#code/C4TwDgpgBACg9gSwHbCgXigbwFBT1ADwC4okBXAWwCMIAnAbl3xBPOrsYF9ttRIoAcgEMKEACbxkqDJJRQAZFiQiIJAM7BayAOadGvcNABqQgDZkIa9LEQoA2gGsIIOADMbUgLr6AxnCQaUK5I1gAUDiQm5pYAlOgAfFhMeAiuoXwQblAO6GgYAERsNLT5MTj4FVC0EMBktCEOAHTAcADKmjqhMYwV3MlQwAAWtHAA7qQQ4wCitCO0ofkAkhRgcGpqCFSm0ADCQmoQpdh9fgGoPhAodCTCohK20koqJPkXVyUANIQkAAxfLFAfnoeKdAmI2nBREMdAB1BBDWSPUKrKQkRFxNCJcr4Vxweag1AEKBZADyVAAVhAfMBGgA3MwWNTIh4xMr9CrBUIEGL9bh9cGtSE1Qaw+GDRGhN7AOjdIA)
* [Case Number 2](https://www.typescriptlang.org/play?#code/C4TwDgpgBAyg9gWwgJQJYGMAWB5ARgKwnWCgF4oBvAKClqgEMAuKAZ2ACdUA7AcwG4adXMy4BXBLgjsBdKOwj0AJnC4AbEFHTMARG068oq1MCn1V2wbUXMAFAEoyAPijaAEhFWq4UAOpx2qooWAL5UVOgqbFC49CwQzPBIaFh4hMRklJYMOpioUAj02gA0WcJQAIwADJUlslouetw8hsam5rV0ilC2DqTObh5evv6BIWERXFH06OgQYMAs2GogAIIwHE0AMq3sZhk2AB46jQZGJrvmvc7UsqgAZodQAISk5Lobpztm2nY3snTATDsOAAdygXAgYIAouxgewbNpRJgoHBkSxIDxMBBgMBUHAfllQqFwpESMoICxEhB1qI7nd9kdKPV3vpmmc2tpgldMrI7v4bBMogA3PZwempIjAAB0ItUogphzsvyysmms3mi2Waw+PG25zMNlldhkdCJYXJlMQ1OAtIeMTixqAA)

Note: this was known way back in 2016, where @ahejlsberg called this out in the same comment:

> BTW, I have the same reservations about `Object.entries` which I notice is now typed this way.

___

Within a structural type-system and in the absence of [Exact Types](https://github.com/Microsoft/TypeScript/issues/12936), it would appear that _most_ Object reflection methods must be typed imprecisely wide, including `Object.entries` and `Object.values`.

But this kind of feels like it violates [Typescripts third non-goal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals): Precise types for object methods are incredibly useful, which is clear by the number of requests, questions and PRs around `Object.keys` type signature.

Given the state of things it feels like one of two things should happen:

1. Remove [these](https://github.com/microsoft/TypeScript/blob/main/lib/lib.es2017.object.d.ts#L26) [two](https://github.com/microsoft/TypeScript/blob/main/lib/lib.es2017.object.d.ts#L38) type signatures, and revisit when Exact Types land.
1. Add a more precise `Object.keys` type definition override, and  maintain at least the same level of unsoundness that already exists.

## Sample Code

Something like this maintains parity with the status-quo:

```typescript
interface ObjectConstructor {
    keys<T extends Record<string, unknown>>(o: T): (keyof T)[];
}
```

Which [is not a valid program in the SO example](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgPICMBWEFgMID2IAzmFAK64FTIDeAUMk8gNYQCexAPACrIQAPSCAAmxZACUc1EV1JRQAcwA0yciBYgCAdxAA+PQAoCALmQ8AlGcNt2BGOYsBtALoBuegF969UJFiIKAAKBH50jMwCZiDkALbo0B7MyOzRcQlQHt70YOwADigAGsgAvMghfk629uWh4C4+MOq4wETIMCA2ZtUOFeAW4cnADjalJWUARAITAwzJyQhExAQANhAAdCsEioYTxXACwMQzScye-CvEKMPIo+OT7DOD80yLJKsbWzsTAJrIB0cThEmOcIJcUHMXsgwAALKA6ZAgCDaZAAUSg8Kgux4MKOyDxwFieQIxGIwHQayByW82T80HgSGQADk4LEICI+mB+EIIKJxJznkwQKyIGZ5Eosj43qRkEhwNAzCy2Ry6lyyrRESKzBM5f4JqoosgAAyqVLG5CeDz0JogFptEQEADKBDZsKUhjyYDMnNmwPa1Fu0q5LGQNQw2Fw61sxA9YAsvqhyAA9EnkABBZAANzgK2AIllOZW+JgDnDODAUY4Mc9AygEDA5CgJFuPVqfmcDUTHRsFlOIK89BT5jhOnEcBA3KQntaIHoDudrtxIB2uugvaAA), but [demonstrates the same level of unsoundness that already exists](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgPICMBWEFgMID2IAzmFAK64FTIDeAUMk8gNYQCexAPACrIQAPSCAAmxZACUc1EV1JRQAcwA0yciBYgCAdxAA+PQAoCALmQ8AlGcNt2BGOYsBtALoBuegF969MOwAOKAAKBKBgyAC8dIzMAmYg5AC26NAezMjs8UkpUB7evgEoAHJwiRAiIWGRyJXgyABkdCClEGbySp4eBYHIAGpwADbkEOJRtWBOtvY1oeDuPjDquMBEyDAgNmZTDuMW0enADjaREVEARAJnewzp6QhExAQDEAB0AwSKhmcAGshwAsBiFc0sxPPwBsQUIdkMdTud2Fd9rcmPcSE9Xu9PmcAJp-AFAiwgphgiAQlA3ZHIMAACygOmQIAg2mQAFEoHSoF8eNTAchecBEv4CMRiMB0M9gTFiV4fKjSMgkOBoGYSmUKrNwlFaM0ymYzorIFAzqo4sgAAyqTLmzqyh7hEQEADKBDKNKUAHVgDTxtVDEKwmZdpE9EimDBqIY5eEBMhphhsLgXrZiH6NRYLBTketDAILFLkN58g7na6eSBFJ7vRrIxAlVBCUA)

Thanks for listening, appreciate y'all :smile: . I realize the team is full of experts and this is likely to have been discussed. Happy to close if thats the case, but am interested to read more about it!

**Comment by MartinJohns** [comment] 2021-09-12 06:13
Duplicate of #38520.

**Closed** 2021-09-15 18:00 UTC
Labels: Duplicate
