### ISSUE TITLE
Backslash escaping in template strings are handled incorrectly?

### ISSUE THREAD

**Issue by jthg** [Microsoft/TypeScript#2803] opened 2015-04-16 21:08 UTC
Example: (TypeScript)
```typescript
var a = `hello\world`;
var b = `hello\\world`;
var c = `hello\\\world`;
var d = `hello\\\\world`;
```
Is compiled to: (JavaScript)
```javascript
var a = "helloworld";
var b = "hello\world";
var c = "hello\world";
var d = "hello\\world";
```

[TypeScript Playground](http://www.typescriptlang.org/Playground#src=var%20a%20%3D%20%60hello%5Cworld%60%3B%0D%0Avar%20b%20%3D%20%60hello%5C%5Cworld%60%3B%0D%0Avar%20c%20%3D%20%60hello%5C%5C%5Cworld%60%3B%0D%0Avar%20d%20%3D%20%60hello%5C%5C%5C%5Cworld%60%3B%0D%0Aalert(a)%3B%0D%0Aalert(b)%3B%0D%0Aalert(c)%3B%0D%0Aalert(d)%3B)

Note that we need four backslashes in order to have a single backslash in the string value.

I tried the ES6 implementations in Chrome, Firefox and es6fiddle.net and they all treat backslashes in template strings the same way as in regular strings (i.e., two backslashes in the template results in a single backslash in the string value.).

**Comment by DanielRosenwasser** [comment] 2015-04-16 21:41
What do you think the expected output is?

**Comment by DanielRosenwasser** [comment] 2015-04-16 21:52
Wait, I'm seeing what you mean. I thought you were referring to something similar to #1984.

This is actually fixed in 1.5 alpha.

**Comment by DanielRosenwasser** [comment] 2015-04-16 23:13
Confirmed that this is fixed in 1.5 alpha. Emit is now:

```JavaScript
var a = `hello\world`;
var b = `hello\\world`;
var c = `hello\\world`;
var d = `hello\\\\world`;
```

**Closed by DanielRosenwasser** 2015-04-16 23:13 UTC
Labels: Bug

**Comment by alanouri** [comment] 2015-12-15 07:53
@DanielRosenwasser can you please reopen this issue as it has either regressed or it was never fixed: [TypeScript Playground](http://www.typescriptlang.org/Playground#src=var%20a%20%3D%20%60hello%5Cworld%60%3B%0D%0Avar%20b%20%3D%20%60hello%5C%5Cworld%60%3B%0D%0Avar%20c%20%3D%20%60hello%5C%5C%5Cworld%60%3B%0D%0Avar%20d%20%3D%20%60hello%5C%5C%5C%5Cworld%60%3B%0D%0Aalert(a)%3B%0D%0Aalert(b)%3B%0D%0Aalert(c)%3B%0D%0Aalert(d)%3B)

**Comment by DanielRosenwasser** [comment] 2015-12-15 08:22
Why do you say there's a regression? The emit is as I've listed above, which is semantically the same.

**Comment by DanielRosenwasser** [comment] 2015-12-15 08:26
Sorry, my comment above is incorrect. The current emit is

```ts
var a = "helloworld";
var b = "hello\\world";
var c = "hello\\world";
var d = "hello\\\\world";
```

Which is correct. Here's why:

1. `a` should have `"helloworld"` because `\w` just maps to `w`.
2. `b` should have `"hello\\world"` because `\\` needs to keep its escape
3. `c` should have `"hello\\world"` because of the reasons for (1) and (2) combined; namely, `\\` continues to need to be escaped, and since `\w` just maps to `w`, that doesn't.
4. `d` just has rule (2) repeated twice; both escaped backslashes are maintained.

**Comment by alanouri** [comment] 2015-12-15 08:27
Oh, right, yes, that is correct.  Sorry, I didn't verify the earlier comment and just assumed the behavior was wrong, the the comment.  Please feel free to leave it closed :)

**Comment by DanielRosenwasser** [comment] 2015-12-15 08:32
No worries, every time I look at this issue (or a related one), I find myself saying "That's right - wait, that's wrong - wait, no it's fine." Counting backslashes is annoying. :smile:
