### ISSUE TITLE
Architectural error

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [Microsoft/TypeScript#9344] opened 2016-06-24 03:14 UTC
Cant call static owerriden methods,  if i write `Animal.run()` this is code not use `Cat.run` owerriden method. i need write `this.constructor.run()` but it get compilation error.

```typescript
class Animal {
	
	static run (){
		alert('Animal run')
	}
	
	run(){
		this.constructor.run() // compile error
		// if i write Animal.run() this code not use Cat.run owerriden method
	}
	
}


class Cat extends Animal {
	
	static run (){
		super.run()
		alert('Cat jump')
	}

}

let cat = new Cat()
cat.run()
```

solution
---
add keyword `static` for access to current static props, `static` will be alias for `this.constructor` in self methods, and alias for `this` in static methods

and code will be:
```typescript
class Animal {
	
	static run (){
		alert('Animal run')
	}
	
	run(){
		static.run() // compile to this.constructor.run()
	}
	
}


class Cat extends Animal {
	
	static run (){
		super.run()
		alert('Cat jump')
	}

}

let cat = new Cat()
cat.run() // alert('Animal run') alert('Cat jump')
```

dangers
---
Static keyword to be used in the following standards and ES have  different semantics

**Comment by mhegazy** [comment] 2016-06-24 03:24
Duplicate of https://github.com/Microsoft/TypeScript/issues/3841

**Comment by uMaxmaxmaximus** [comment] 2016-06-24 03:26
@mhegazy omg "commented on 13 Jul 2015" man

**Closed** 2016-06-24 03:29 UTC
Labels: Duplicate
