### ISSUE TITLE
No suggestions given after the `as` keyword.

### ISSUE THREAD

**Issue by d180cf** [Microsoft/TypeScript#5562] opened 2015-11-08 02:37 UTC
The language service doesn't give any suggestions here:

```ts
const wrapper = document.querySelector('.wrapper') as H
```

At `H` I expected to see HTMLElement. The suggestion is shown if I type `;` and then `H`.

**Comment by DanielRosenwasser** [comment] 2015-11-09 05:03
Duplicate of #4731. This should be fixed in the next release.

**Closed by DanielRosenwasser** 2015-11-09 05:03 UTC
Labels: Bug
