### ISSUE TITLE
support sub-projects within a single tsconfig.json

### ISSUE THREAD

**Issue by JeroMiya** [Microsoft/TypeScript#1928] opened 2015-02-04 18:41 UTC
Extension to https://github.com/Microsoft/TypeScript/pull/1692.

Motivation:
A common file layout for some projects is to organize code by feature, rather by the kind of the file. This means that the implementation of a feature, along with its unit tests and end to end tests are all grouped into a single directory structure. I use this convention in my own projects.

Currently, however, tsconfig.json assumes that sub-projects are split by directories. With the feature grouped files convention, however, we have multiple 'projects' interleaved in the same directories. For example, end to end tests have different project settings than unit tests, which may have different project settings from the application code itself.

Proposal:
Support sub-projects within a single tsconfig.json. This allows for more flexibility in how files are laid out in an application.

Example:
```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "removeComments": false,
    "sourceMap": true
  },
  "files": [
     "common-files/commonFiles.ts",
  ],
  "projects": {
     "app": {
         "compilerOptions": {
             "module": "amd",
             "removeComments": true,
             "out": "app/app.js"
         },
         "files": [
             "app/feature1/feature1.ts"
         ]
     },
     "unit": {
         "compilerOptions": {
             "out": "tmp/unit/"
         },
         "files": [
           "app/feature1/feature1_test.ts",
         ]
    },
    "e2e": {
        "compilerOptions": {
            "module": "commonjs",
            "out": "tmp/e2e/"
        },
        "files": [
            "app/feature1/feature1PageObject_e2e.ts",
            "app/feature1/feature1_e2e.ts"
         ]
    }       
}
```

Building with tsc:
```
tsc -p tsconfig.json
-> builds root and all sub-projects, including those in sub-directories, recursively.

tsc -p tsconfig.json:app
-> builds root and app sub-project.
```
Notes:
* Projects are recursive. You can have sub-projects of projects. Building the root builds all sub-projects and their sub-projects.
* To build a specific sub-project, use ':', for example tsc -p jsconfig.json:app:feature1 if "feature1" were a subproject of "app" (not shown in the example above).
* Child projects inherit options and files from their parent projects, unless options are overwritten. Files are additive.
* tsconfig.json files in sub-directories are evaluated independently. That is, they do not inherit anything from tsconfig.json files in a parent directory.
* IDE and editor extensions may decide to support switching the current "context" of a file, i.e. the project or sub-project, or the tsconfig.json file if more than one reference the same file in one of the parent directories.

The default context is determined as follows:
* Find the tsconfig.json in the same directory as the file, or recursively search parent directories.
* If the root project has a reference to the file, use the root settings as the default context.
* Recursively look in each sub-project, finding the first project with a reference to the file.

**Comment by a3chic9** [comment] 2015-04-10 14:32
I'm looking for some way to more easily manage this too. I like the idea of having unit tests along side the source file because it makes the /// file references easier (rather than ../../../src/feature/file.ts). I might be interested in just creating different tsconfig files (e.g. tsconfig-app.json, tsconfig-unit.json) which should work with the -p project spec.

**Comment by Zorgatone** [comment] 2015-09-23 16:37
I need a feature like this, to possibly bundle some files and compile the rest alone

**Comment by aciccarello** [comment] 2015-09-23 16:49
@Zorgatone I'm using [browserify](https://github.com/substack/node-browserify) with the [tsify](https://github.com/smrq/tsify) plugin to bundle my files. Then I've started using ES6 imports to pull in all the files that I need for that bundle.

**Comment by adidahiya** [comment] 2015-09-23 16:59
+1 it would be great if tsconfig.json supported multiple subprojects, and I like the syntax / semantics that @JeroMiya is proposing

**Comment by Zorgatone** [comment] 2015-09-23 17:29
I totally think that this suggestion needs more attention though.
It's definitely something that will help a lot of people save some precious time. Instead of having to rely on external tools (grunt/gulp/browserify/...)

**Comment by mhegazy** [comment] 2015-09-28 21:02
Duplicate of https://github.com/Microsoft/TypeScript/issues/3469?

**Closed** 2015-12-09 22:10 UTC
Labels: Suggestion
