### ISSUE TITLE
Overload resolution: Choosing the wrong overload when arguments involve generic wrappers

### ISSUE THREAD

**Issue by krryan** [microsoft/TypeScript#13570] opened 2017-01-18 22:15 UTC
**TypeScript Version:**  2.2.0-dev.20161221

**Code**

```ts
function filter<P extends Q[], Q, R extends Q>(values: P, isR: (value: Q) => value is R): R[];
function filter<R>(values: R[], isValid: (value: R) => boolean): R[];
function filter<P extends Q[], Q, R extends Q>(values: P, isR: (value: Q) => value is R): R[] {
    const result: R[] = [];
    values.forEach(q => {
        if (isR(q)) {
            result.push(q);
        }
    });
    return result;
}

interface Foo<T> {
    foo: T;
}
interface Bar<T> {
    bar: T;
}
type FooBar<T> = Foo<T> | Bar<T>;

const foobars: FooBar<{}>[] = [];

function isFoo<T>(foobar: FooBar<T>): foobar is Foo<T> {
    return 'foo' in foobar;
}
filter(foobars, isFoo).map(foo => foo.foo);

filter<FooBar<{}>[], FooBar<{}>, Foo<{}>>(foobars, isFoo).map(foo => foo.foo);

function isFooObject(foobar: FooBar<{}>): foobar is Foo<{}> {
    return isFoo(foobar);
}
filter(foobars, isFooObject).map(foo => foo.foo);
```
(also on the [Playground](http://www.typescriptlang.org/play/index.html#src=function%20filter%3CP%20extends%20Q%5B%5D%2C%20Q%2C%20R%20extends%20Q%3E(values%3A%20P%2C%20isR%3A%20(value%3A%20Q)%20%3D%3E%20value%20is%20R)%3A%20R%5B%5D%3B%0D%0Afunction%20filter%3CR%3E(values%3A%20R%5B%5D%2C%20isValid%3A%20(value%3A%20R)%20%3D%3E%20boolean)%3A%20R%5B%5D%3B%0D%0Afunction%20filter%3CP%20extends%20Q%5B%5D%2C%20Q%2C%20R%20extends%20Q%3E(values%3A%20P%2C%20isR%3A%20(value%3A%20Q)%20%3D%3E%20value%20is%20R)%3A%20R%5B%5D%20%7B%0D%0A%20%20%20%20const%20result%3A%20R%5B%5D%20%3D%20%5B%5D%3B%0D%0A%20%20%20%20values.forEach(q%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(isR(q))%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20result.push(q)%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D)%3B%0D%0A%20%20%20%20return%20result%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Foo%3CT%3E%20%7B%0D%0A%20%20%20%20foo%3A%20T%3B%0D%0A%7D%0D%0Ainterface%20Bar%3CT%3E%20%7B%0D%0A%20%20%20%20bar%3A%20T%3B%0D%0A%7D%0D%0Atype%20FooBar%3CT%3E%20%3D%20Foo%3CT%3E%20%7C%20Bar%3CT%3E%3B%0D%0A%0D%0Aconst%20foobars%3A%20FooBar%3C%7B%7D%3E%5B%5D%20%3D%20%5B%5D%3B%0D%0A%0D%0Afunction%20isFoo%3CT%3E(foobar%3A%20FooBar%3CT%3E)%3A%20foobar%20is%20Foo%3CT%3E%20%7B%0D%0A%20%20%20%20return%20'foo'%20in%20foobar%3B%0D%0A%7D%0D%0Afilter(foobars%2C%20isFoo).map(foo%20%3D%3E%20foo.foo)%3B%0D%0A%0D%0Afilter%3CFooBar%3C%7B%7D%3E%5B%5D%2C%20FooBar%3C%7B%7D%3E%2C%20Foo%3C%7B%7D%3E%3E(foobars%2C%20isFoo).map(foo%20%3D%3E%20foo.foo)%3B%0D%0A%0D%0Afunction%20isFooObject(foobar%3A%20FooBar%3C%7B%7D%3E)%3A%20foobar%20is%20Foo%3C%7B%7D%3E%20%7B%0D%0A%20%20%20%20return%20isFoo(foobar)%3B%0D%0A%7D%0D%0Afilter(foobars%2C%20isFooObject).map(foo%20%3D%3E%20foo.foo)%3B))

**Expected behavior:**
Compiles without error.

**Actual behavior:**
The first invocation of `filter`, `filter(foobars, isFoo).map(foo => foo.foo);`, has an error `Property 'foo' does not exist on type 'FooBar<{}>'`. The second/less-specific overload of `filter` is being selected, even though (as the second invocation shows) the first/more-specific overload is valid, and also despite the fact (as shown by the third invocation) the correct overload is chosen when the inferred type does not involve a generic.

**Comment by lucasray** [comment] 2017-01-24 18:41
I believe this example also gets to the crux of the issue:

```typescript
interface A<T> {
    _a: T;
}
interface B<T> {
    _b: T;
}
type AorB<T> = A<T> | B<T>;

declare function isA1<T>(input: AorB<T>): input is A<T>;
declare function isA2(input: AorB<{}>): input is A<{}>;

declare function overload<T>(fn: (input: AorB<T>) => input is A<T>);
declare function overload<T>(fn: (input: AorB<T>) => boolean);

overload(isA1); // uses 2nd overload
overload(isA2); // uses 1st
```

If only one `overload` is declared, both calls still typecheck correctly (so, both declarations are valid for both `isA*` functions). If both are present, they use the overloads as commented. I'm not sure what causes them to choose different overloads when both are valid.

**Comment by krryan** [comment] 2017-01-25 00:40
Yes, exactly that. There should be some way to control which overload is "preferred" when both are valid, and I had thought that was order (first matching overload is chosen), but it seems like TypeScript is... I dunno, shortcutting and/or getting lazy too early on these evaluations when you don't hint them.

**Comment by mhegazy** [comment] 2017-05-18 20:09
related to https://github.com/Microsoft/TypeScript/issues/9366

**Comment by Erikvv** [comment] 2018-06-18 10:57
I have a similar issue while writing definitions for ohanhi/hyperscript-helpers

After passing a function through a generic wrapper it either choses the last overload or it loses type safety completely, depending on how I write the overloads. 

Minimal example:

```ts
declare function overload(a: number);
declare function overload(b: string);

interface MyFunction<T> {
    (t: T): any
}

declare function wrap<T>(f: MyFunction<T>): MyFunction<T>

const myFunction = wrap(overload);

myFunction('qwerty'); // OK
myFunction(9000); // error TS2345: Argument of type '9000' is not assignable to parameter of type 'string'
```

This can be fixed by changing the `wrap` function to below but I haven't gotten this to work in more generic code.

```ts
declare function wrap<F extends MyFunction<T>, T>(f: F): F
```

**Comment by krryan** [comment] 2018-06-18 13:06
Actually, that looks more like a question of higher-kinded types, which is the long-standing issue #1213.

**Comment by Erikvv** [comment] 2018-06-18 13:35
@krryan I'm no expert but it seems to me the problem is in the overloads being ignored.

**Comment by krryan** [comment] 2018-06-18 13:53
They are, but more fundamentally, TS has no way of passing around something that can go multiple ways like that. When you pass `overload` to `wrap`, TS needs to pick one of the overloads—in this case, it seems, the first. Higher-kinded types might help that situation. And my question, ultimately, doesn't have to do with trying to get TS to maintain that flexibility, it's just about choosing the right one in a situation where I *want* TS to choose one.

**Comment by benneq** [comment] 2018-08-13 20:15
Is this the same issue?

```
interface Foo {

}

interface Bar extends Foo {
    someFn: (arg: string) => void
}
function myFn(obj: Foo);
function myFn(obj: Bar, arg: string);
function myFn(obj: Foo | Bar, arg?: string) {
    if (arg) {
        obj.someFn(arg);  // ERROR
                          // Property 'someFn' does not exist on type 'Foo'
    }
}
```

Playground Link: https://www.typescriptlang.org/play/#src=interface%20Foo%20%7B%0D%0A%0D%0A%7D%0D%0A%0D%0Ainterface%20Bar%20extends%20Foo%20%7B%0D%0A%20%20%20%20someFn%3A%20(arg%3A%20string)%20%3D%3E%20void%0D%0A%7D%0D%0A%0D%0Afunction%20myFn(obj%3A%20Foo)%3B%0D%0Afunction%20myFn(obj%3A%20Bar%2C%20arg%3A%20string)%3B%0D%0Afunction%20myFn(obj%3A%20Foo%20%7C%20Bar%2C%20arg%3F%3A%20string)%20%7B%0D%0A%20%20%20%20if%20(arg)%20%7B%0D%0A%20%20%20%20%20%20%20%20obj.someFn(arg)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D

**Comment by krryan** [comment] 2018-08-14 11:27
@Erikvv I don't think typeguards are going to help benneq. Note that he's testing `arg` but wants TS to infer something about `obj`. A typeguard is there answer to the second question regarding a workaround, though.

Anyway, @benneq, your first sniper doesn't work for a few reasons, but none of them are directly related to this. First, TS doesn't support the notion of “entangled” variables, so a test against one is not going to lead to inferences about another. Second, function overloads do very minimal type checking—the overloads have to be at least theoretically compatible with the primary signature, but they are never checked against the function body to see if that is hope they are being used.

**Comment by RyanCavanaugh** [comment] 2019-07-23 03:32
Appears to be due to generic inference not using all overloads, which is a known limitation

**Closed by RyanCavanaugh** 2019-07-23 03:32 UTC
Labels: Design Limitation
