### ISSUE TITLE
VS2015 Update 1 - Web Site Project - TSX Editor breaks with use of "module": "es6" setting in tsconfig.json

### ISSUE THREAD

**Issue by snerks** [Microsoft/TypeScript#6492] opened 2016-01-14 23:57 UTC
Use of the `"compilerOptions": {"module": "es6"}` setting in tsconfig.json in a VS2015 "Web Site" project appears to break the editor for TSX files. 

Use of the `"compilerOptions": {"module": "es2015"}` setting also causes the issue. 

With this setting in place, entered keystrokes are not rendered into the TSX file.

## Environment ##
1. Visual Studio 2015 (Community) - Update 1
1. Typescript 1.7 Extension
1. Windows 7 SP1 (64-bit)

## Steps to Reproduce ##
Minimal repro available here:
[https://github.com/snerks/Min1](https://github.com/snerks/Min1)

### "Normal" behaviour with "target": "es6" ###
1. Clone or copy this repo to disk
1. `npm install`
1. Launch VS2015 Community - Update 1
1. Select File/Open/Web Site...
1. Select the root folder containing this repo.
1. From Solution Explorer, open the file ~/src/views/Badge.tsx
2. Observe that syntax highlighting works for `React.Component` etc.
3. Make trivial (non-destructive) edit to source code (e.g. add a comment)
4. Observe that entered keystrokes are rendered
5. Close ~/src/views/Badge.tsx

### Unexpected behaviour with "module": "es6" ###
6. Using Solution Explorer, open the file ~/tsconfig.json
7. Change the setting: `"compilerOptions": {"target": "es6"}` to `"compilerOptions": {"module": "es6"}`
8. Save the file ~/tsconfig.json
9. Close the file ~/tsconfig.json
10. From Solution Explorer, re-open the file ~/src/views/Badge.tsx
2. Observe that syntax highlighting does not work for `React.Component` etc.
3. Attempt to make trivial (non-destructive) edit to source code (e.g. add a comment)
4. Observe that entered keystrokes (other than "ENTER", "BACKSPACE", "Paste") are not rendered.

**Comment by vladima** [comment] 2016-01-15 00:01
looks like a dupe of #6392, pinging @paulvanbrenk for resolution

**Closed** 2016-01-15 00:02 UTC
Labels: Duplicate
