### ISSUE TITLE
"Find All References" returns no results for JS files with 'require' import

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#16263] opened 2017-06-05 12:36 UTC
**TypeScript Version:**  2.3.4

**Code**

``` js
// app/helpers/index.js
export const foo = () => {}
```

``` js
// app/main.js
import { foo } from './helpers';

foo();
```

``` js
// app/entry.js
export const foo = () => {
    require('./main')
}
```

tsconfig.json:

``` json
{
    "compilerOptions": {
        "allowJs": true,
        "checkJs": true
    },
    "files": [
        "./app/entry.js"
    ]
}
```

package.json:

``` json
{
  "private": true,
  "devDependencies": {
    "@types/node": "7.0.27",
    "typescript": "2.3.4"
  }
}
```

**Expected behavior:**
If I go to `app/helpers/index.js` in VSCode and select "Find All References", I should see the reference in `app/main.js`.

**Actual behavior:**
It doesn't find any references, returning "No Results".

![image](https://cloud.githubusercontent.com/assets/921609/26784159/f4dee804-49f3-11e7-9cf5-08bd8b802d7f.png)

If I change `app/main.js` to the following (removing `export`), then it does find references:

``` js
// removed `export`
const foo = () => {
    require('./main')
}
```

![image](https://cloud.githubusercontent.com/assets/921609/26784168/027201f4-49f4-11e7-95e4-7ffcd1adc159.png)

**Comment by Kovensky** [comment] 2017-06-05 15:15
It seems typescript ignores `require` in modules.

**Comment by DanielRosenwasser** [comment] 2017-06-05 16:48
@Kovensky yes but not in .js files.

**Comment by andy-ms** [comment] 2017-06-05 18:19
I reproduced the error in `typescript@2.3.4`. This seems to be fixed in `typescript@next`.

**Comment by OliverJAsh** [comment] 2017-06-05 21:18
Thanks!

**Closed** 2017-06-05 21:18 UTC
Labels: Bug, Fixed
