### ISSUE TITLE
Wrong type inference on a mutated array

### ISSUE THREAD

**Issue by nukata** [microsoft/TypeScript#33443] opened 2019-09-16 09:21 UTC
**TypeScript Version:**  3.6.3

**Code**

```ts
function foo(a: string[]): boolean {
    if (a[0] === 'A') {
        a.shift();
        if (a[0] !== 'B') return true;
    }
    return false;
}

console.log(foo(['A', 'A']));   // => true
console.log(foo(['A', 'B']));   // => false
```

**Expected behavior:**

```
$ tsc foo.ts
$ node foo.js
true
false
$ 
```

**Actual behavior:**

```
$ tsc foo.ts
foo.ts:4:13 - error TS2367: This condition will always return 'true' since the types '"A"' and '"B"' have no overlap.

4         if (a[0] !== 'B') return true;
              ~~~~~~~~~~~~


Found 1 error.
```

`a.shift()` mutates `a[0]`.
TypeScript seems to have ignored it in type inference.

**Comment by jack-williams** [comment] 2019-09-16 09:35
This is a duplicate of #9998 if you alpha rename: `a[0]` to `token`, `A` and `B` to syntax kinds, and `a.shift()` to `nextToken()`.

**Comment by nukata** [comment] 2019-09-16 10:51
Thank you.
Now I see this is rather a duplicate of [#31334](https://github.com/microsoft/TypeScript/issues/31334), which is stated as _a design limitation_ and closed.

I am afraid my [Little Scheme in TypeScript](https://github.com/nukata/little-scheme-in-typescript) will never be sound in TypeScript 3.6 and later.
For [scm.ts L591-L594](https://github.com/nukata/little-scheme-in-typescript/blob/v1.0.1/scm.ts#L591-L594):

```
$ tsc --version
Version 3.6.3
$ cd little-scheme-in-typescript-1.0.1
$ tsc -strict -t ESNext --outFile scm.js scm.ts
scm.ts:594:21 - error TS2367: This condition will always return 'true' since the types '"."' and '")"' have no overlap.

594                 if (tokens[0] !== ')')
                        ~~~~~~~~~~~~~~~~~


Found 1 error.
```

**Closed** 2021-06-01 22:25 UTC
Labels: Design Limitation
