### ISSUE TITLE
Incorrect type narrowing with callback

### ISSUE THREAD

**Issue by danvk** [microsoft/TypeScript#35593] opened 2019-12-09 21:45 UTC
I'd expect this code to type check:

**Code**
```ts
function processArray(xs: string[]) {
  let bar: string[] | null = null;
  xs.forEach(() => {
    bar = ['a', 'b'];
  });
  if (bar) {
    bar.forEach(str => console.log(str));
  }
}

processArray([]);
processArray(['x']);
```

Despite the explicit type annotation on `bar`, TypeScript narrows the type based on the initial assignment and doesn't see the reassignment in the callback. Replacing `xs.forEach` with `for-of` makes this example work but is harder in more complex situations.

**TypeScript Version:**  3.7.2

**Search Terms:**

- 2339
- 2339 callback

**Expected behavior:**

No error

**Actual behavior:**

```Property 'forEach' does not exist on type 'never'.(2339)```

**Related Issues:**

https://github.com/microsoft/TypeScript/issues/8353
https://github.com/microsoft/TypeScript/issues/35132

<details><summary><b>Output</b></summary>

```ts
"use strict";
function processArray(xs) {
    let bar = null;
    xs.forEach(() => {
        bar = ['a', 'b'];
    });
    if (bar) {
        bar.forEach(str => console.log(str));
    }
}
processArray([]);
processArray(['x']);

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABABwE5wgUwM7YIKqoCGAngBQAe2AXItlKjGAOYDaAugJSIDeAsAChEiADaYoiAEZFUteoxYdEAH0RgQIkYgC8ajSIDcg4VQB0wOKgCiRCAAsyZbtoB8vY8KkydiVgHIiPwAaRD9JP3YjIUQAX04o4RhgRDJpVG5+aOE080sbezJ5HTcIBGw4MVMROGZChk54jxjBZoFBNAwcfEJSMg5GgQ6sXAJicn8KCIGgA)

**Comment by MartinJohns** [comment] 2019-12-09 21:51
Duplicate of #9998. Would be fixed by #11498.

**Comment by fatcerberus** [comment] 2019-12-09 23:34
`forEach` is an interesting case, because to get the correct semantics, the callback would have to be analyzed like a *loop body*, not just an IIFE.

**Comment by fan-tom** [comment] 2019-12-10 10:02
Is it the same issue?
```typescript
export interface Foo {
  bar?: string;
} 

function daz(foo ?: Foo) {
    if (foo?.bar) {
        const bar: string = foo.bar;
        [].map(item => {
            const bar: string = foo.bar; // <- cannot assing string | undefined to string
        });
    }
}
```

**Comment by fatcerberus** [comment] 2019-12-10 14:45
@fan-tom Yes.  The compiler doesn’t know in general that a function you provided is going to be called immediately (or, for that matter, how many times it will be called), so it can’t safely keep the narrowings as the variable might be reassigned in the meantime.

**Comment by danvk** [comment] 2019-12-10 14:54
@fan-tom same root cause, but opposite symptoms in the sense that you want a narrowing whereas I want to avoid an incorrect narrowing.

What surprised me about this is that the type of `bar` in my initial example gets narrowed to `null` despite the explicit type annotation of `string[] | null`.

**Comment by fan-tom** [comment] 2019-12-10 14:54
@fatcerberus, then why there is no error there?
```typescript
export interface Foo {
  bar?: string;
}

async function evil(foo: Foo): Promise<void> {
    foo.bar = undefined;
}

async function daz(foo ?: Foo) {
    if (foo?.bar) {
        await evil(foo); // <- after that foo.bar gets undefined
        const bar: string = foo.bar; // but type is still string
        [].map(item => {
            const bar: string = foo.bar; // <- but here compiler conservatively thinks it is string|undefined
        });
    }
}
```

**Comment by fatcerberus** [comment] 2019-12-10 14:57
See #9998.  The analyzer doesn't look into function calls.

**Closed** 2019-12-12 18:00 UTC
Labels: Duplicate
