### ISSUE TITLE
Creating an interface with a symbol?

### ISSUE THREAD

**Issue by blesh** [Microsoft/TypeScript#8099] opened 2016-04-14 20:06 UTC
**TypeScript Version:** 

1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

**Code**

```ts
// try augmenting the SymbolContructor to have some expected symbol on it.
// in RxJS5's case, it'll be the Symbol.observable symbol from the es-observable spec.
interface SymbolConstructor {
  observable: symbol;
}

interface Observablesque<T> {
  [Symbol.observable]: () => Subscribable<T>
}
```

or 

```ts
// try importing some symbol reference (I get why this might not work)
import {$$observable} from './symbol/observable';

interface Observablesque<T> {
  [$$observable]: () => Subscribable<T>
}
```

**Expected behavior:**

I should be able to enforce types that have symbols on them, custom or otherwise.

**Actual behavior:** 

I get really confused and go get myself a coffee.

**Comment by blesh** [comment] 2016-04-14 20:09
Also, depending on the environment, that interface could be `Symbol.observable` or it could be `@@observable`.

**Comment by blesh** [comment] 2016-04-14 20:12
What I"m looking at here are specifically two future built-ins: `Symbol.observable` and `Symbol.asyncIterator`.

**Comment by mhegazy** [comment] 2016-04-14 20:14
The first one should work as if you have the Symbol definition.

The second one is a bit more involved. the issue is we do not know what the import points to at the time when we are building types, there is more discussion in: https://github.com/Microsoft/TypeScript/issues/2012
the issue is tracked by https://github.com/Microsoft/TypeScript/issues/5579

**Comment by david-driscoll** [comment] 2016-04-14 20:24
Keep in mind, when imported through node definitions, the TypeScript compiler raises an error, because you cannot have ambient references as part of your source (`/// <reference path=".../symbol.d.ts" />`).  Is there a way to augment ambient interfaces?

We had this at one point but it was causing errors so we backed it out.
https://github.com/ReactiveX/rxjs/commit/d185ff849ec9540c14d95496bbee9f0fcda2a90c

**Comment by mhegazy** [comment] 2016-04-14 20:28
why not `declare global`?
```ts
declare global {
   SymbolConstructor {
     observable: symbol;
   }
}
```

**Comment by blesh** [comment] 2016-04-14 20:52
> why not declare global?

Because I'm a better JavaScript developer than I am a TypeScript expert?

**Comment by DanielRosenwasser** [comment] 2016-04-14 21:15
> Because I'm a better JavaScript developer than I am a TypeScript expert?

Good point @blesh - I just filed [this issue](https://github.com/Microsoft/TypeScript-Handbook/issues/250).

**Comment by david-driscoll** [comment] 2016-04-14 21:23
because I didn't know that existed... I'll have to mess with that in a day or two.  Thanks!

**Comment by blesh** [comment] 2016-04-14 21:28
No dice with `declare global`.

**Comment by DanielRosenwasser** [comment] 2016-04-14 21:40
@blesh can you elaborate what issues you're running into? This works for me.

### `foo.ts`

```ts
export {};

declare global {
    interface SymbolConstructor {
        observable: symbol;
        asyncIterator: symbol;
    }
}

Symbol.observable;
```

### `tsconfig.json`

```ts
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "noImplicitAny": false,
        "sourceMap": false
    },
    "files": [
        "foo.ts"
    ]
}
```

**Comment by blesh** [comment] 2016-04-14 21:48
@DanielRosenwasser 

It complains at me:

```
TS2665: Module augmentation cannot introduce new names in the top level scope.
```

**Comment by DanielRosenwasser** [comment] 2016-04-14 21:52
`SymbolConstructor` will need to have been declared somewhere, so if you'll need to target ES6 or have a `.d.ts` file that declares it. 

I believe if you're using nightlies, you could avoid targeting ES6 and use `--lib es6`.

**Comment by mhegazy** [comment] 2016-04-14 21:52
logged https://github.com/Microsoft/TypeScript/issues/8102 for the error.

**Comment by blesh** [comment] 2016-04-14 22:19
> I believe if you're using nightlies, you could avoid targeting ES6 and use --lib es6.

What is this and how does it benefit us?

**Comment by robwormald** [comment] 2016-04-19 04:18
@blesh the nightly versions of TS let you do:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false,
        "outDir": "dist",
        "lib": ["es5", "es2015.promise", "dom"]
    },
    "files": [
		"src/main.ts"
   ]
}

```
rather than providing say, es6-shim external defs (the above config is what's needed to use rxjs, currently)

@DanielRosenwasser while Observable isn't part of the es6/es7 scope, its currently a stage1 proposal... does the `lib` option (amaaazing) provide a facility to add external lib.whatever files, or might y'all be open to having a `lib.stage1.d.ts` etc option as part of TS?

**Comment by mhegazy** [comment] 2016-04-19 18:26
closing in favor of #5579

**Closed by mhegazy** 2016-04-19 18:26 UTC
Labels: Duplicate
