### ISSUE TITLE
Supporting 'this' type

### ISSUE THREAD

**Issue by jonathandturner** [Microsoft/TypeScript#3694] opened 2015-07-01 18:29 UTC
# Background

We've had a few requests to support this typing (like #229).  This proposal addresses the use cases for a function 'this' type, a class 'this' type, and a corresponding feature for interfaces.

# Motivating Examples

## Extension (lightweight mixin)
```TypeScript
interface Model {
  extend<T>(t: T): <type of containing interface> & T;
}

interface NamedModel extends Model {
  name: string;
}

declare function createNameModel(): NamedModel;

var modelWithNameAndAge = createNamedModel().extend({
  age: 30
});
modelWithNameAndAge.name; //valid
modelWithNameAndAge.age; // valid
```

## Safe instantiation
```TypeScript
function f() {
  this.x = 3;
}
var g = new f(); // gives type an easy way to check f's body or specify instantiated type
```

## Safe method invocation
```TypeScript
function f() {
  this.x = 3;
}
var obj = {y: "bar", f: f};
obj.f(); // can’t easily error
```

## Well-typed fluent APIs (also useful for cloning)
```TypeScript
class Parent {
  setBase(property, value): <whatever the child class is> {
    this._secretSet(property, value);
    return this;
  }
}

class Child extends Parent { 
  name:string;
}

var c = new Child();
console.log(c.setBase("foo", 1).setBase("bar", 2").name);  //valid
```
# Design

To support the motivating examples, we introduce a 'this' type.  The 'this' type should follow the intuition of the developer.  When used with classes, 'this' type refers to the type of the class it finds itself in.  With functions, 'this' allows you to further document how the function will be used as a constructor and in what context it can be invoked while in an object.  

## Classes and 'this'

A class that uses a 'this' is referring to the containing named class.  In the simplest example:

```TypeScript
class C {
  myThis(): this { return this; }
}
var c = new C();
var d = c.myThis();
```
We trivially map the 'this' type in the invocation of myThis() to the C type, giving 'd' type C.

The type of 'this' will follow with subclasses.  A subclass sees any 'this' in the type of its base class as its own type.  This allows more a fluent API, as in this example:

```TypeScript
class C {
  myThis(): this { return this; }
}
class D extends C {
  name: string;
}
var D = new D();
d.myThis().name = "Joe"; //valid
```

For this to work correctly, only 'this' or something that resolves to 'this' can be used.  Something which looks like it should work correctly, but can't work safely is this example:

```TypeScript
class C {
  newInstance(): this {
    return new C(); // error, 'this' only works with this expressions
  }
}
```
## Functions and 'this'

Functions gain the ability to talk about the shape of the 'this' pointer that is visible in the function body.  The design here leverages the type variables of the function to describe what the shape of 'this' has:

```TypeScript
function f<this extends {x:number}>() {
  this.x = 3;
}
```

This is fairly readable, and we could use syntax coloring/tooling to help signify that the 'this' here is a special type variable that is implied by all functions.

Once the type of 'this' is described for functions, we can check the inside of the function body, where this is used:

```TypeScript
function f<this extends {x:number}>() {
  this.x = 3;
  this.y = 6; //error: y is not available on this
}
```

We can also check invocation sites:

```TypeScript
var o = {myMethod: f, y: "bob"};
o.myMethod(); //error: o does not match the shape of 'this' for 'myMethod'
```
We may even want to error on the assignment when object is first created instead of the invocation site.

## Interfaces and 'this'

Similarly to classes, interfaces currently lack the the ability for a type to refer to itself.  While an interfaces can refer to itself by name, this limits the ability of interfaces that extend the original interface.  Here, we introduce 'this' as a way for interfaces to do this:

```TypeScript
interface Model {
  clone(): this;
}

interface NamedModel extends Model {
  name: string;
}

var t:NamedModel;
t.clone().name; // valid
```

For this to work, 'this' refers to the containing named type.  This helps eliminate ambiguities like this:

```TypeScript
interface I {
  obj: { myself: this; name: string };
}
```

In this example, 'this' refers to I rather than the object literal type.  It's trivial to refactor the object literal type out of the class so that you can describe a 'this' that instead binds to the object literal itself.

# Motivating examples (Redux)

In this section, we re-write the motivating examples using the proposed functionality.

## Extension (lightweight mixin)
```TypeScript
interface Model {
  extend<T>(t: T): this & T;
}

interface NamedModel extends Model {
  name: string;
}

declare function createNameModel(): NamedModel;

var modelWithNameAndAge = createNamedModel().extend({
  age: 30
});
modelWithNameAndAge.name; //valid
modelWithNameAndAge.age; // valid
```

## Safe instantiation
```TypeScript
function f<this extends {x:number}>() {
  this.x = 3;
}
var g = new f(); // gives type an easy way to check f's body or specify instantiated type
```

## Safe method invocation
```TypeScript
function f<this extends {x: number}>() {
  this.x = 3;
}
var obj = {y: "bar", f: f};
obj.f(); // error: f can not be invoked on obj, missing {x: number}
```

## Well-typed fluent APIs (also useful for cloning)
```TypeScript
class Parent {
  setBase(property, value): this {
    this._secretSet(property, value);
    return this;
  }
}

class Child { 
  name:string;
}

var c = new Child();
console.log(c.setBase("foo", 1).setBase("bar", 2").name);  //valid
```

**Comment by DanielRosenwasser** [comment] 2015-07-01 18:45
Should methods now all implicitly gain a `this` type variable? This would prevent users from shooting themselves in the foot. For example:

```TypeScript
class C {
    prop: number;
    method() {
        return this.x;
    }
}

let c = new C();
let removedMethodHandle = c.method;
console.log(removedMethodHandle());
```

**Comment by jonathandturner** [comment] 2015-07-01 18:55
@DanielRosenwasser possibly?  Though I suspect that won't give you what you need.  If the 'this' type shows up in the type of c.method, if you pass it to a callback that forgets the 'this' piece of the type, you won't catch the error.

**Comment by prabhjots** [comment] 2015-07-01 21:19
'this' is a good idea. Also it could be applied to the 'call', 'bind' and 'apply' scenarios.

For Example: 
```typescript
class A {
    name: string;

    setName<this extends { name: string;}>(val:string) {
        this.name = val;
    }
}


class B {
    somethingElse: string;
 }

class C { name: string; }

var setName = new A().setName;
var b = new b();
var c = new C();
setName.apply(b, ["hello"]); //error
setName.call(b, "hello"); //error
setName.bind(b)("hello"); //error


setName.apply(c, ["hello"]); //ok
setName.call(c, "hello"); //ok
setName.bind(c)("hello"); //ok

```

**Comment by HerringtonDarkholme** [comment] 2015-07-03 07:02
:+1:  for the proposal

For the interface and class part, it seems `this type` overlaps a lot with F-bounded polymorphism. Can `this type` cover the latter?

**Comment by ahejlsberg** [comment] 2015-07-04 02:42
Some questions that come to mind...

(1) Your proposal doesn't specifically say, but I assume within a class `this` would denote a type that behaves like a subtype of the containing class (effectively like a type parameter with the current class as a constraint). That means we'd break the following code:

```typescript
class C {
    foo() {
        var x = this;
        x = new C();
    }
}
```

(2) The proposal doesn't specify what the type of a method in a class is. For example:

```typescript
class C {
    f() { }
}
var c = new C();
var f = c.f;  // Ideally of type <this extends C>() => void
f();          // Should be an error
```

the type of `f` currently is `() => void`, but I assume it would now be `<this extends C>() => void`. That would ensure `f` can't accidentally be called without a proper `this`.

(3) What are the type compatibility rules for function types with `this` type arguments? For example:

```typescript
var c = new C();
var f: () => void = c.f;  // Is this allowed?
```

If we treat `this` as a type parameter, the above assignment would be allowed because we erase type parameters when checking assignment compatibility of signatures. That might in fact be the right thing to do because anything stricter would break a lot of existing code. But it is something we need to consider.

**Comment by DanielRosenwasser** [comment] 2015-07-04 19:49
@ahejlsberg, my comment brings up (2). From what I understand, @jonathandturner responded that because of your point in (3), we lose the benefit resulting from (2) because of the callback case.

We could instead always take `this` constraints into account, and say that if an instance method never accesses `this`, it does not receive a `this` constraint. This way, we'd only break code in cases where a `this` handle was actually used, though, I could see it as slightly awkward to enforce this consistency.

**Comment by impinball** [comment] 2015-07-07 03:47
Couldn't the above use case be covered by this?

```ts
interface Foo {
  bar(this: Foo & Bar): void;
}

interface Bar {
  bar(this: Foo | Bar): void
}
```

That, I believe, fits closer to the emerging syntax consensus in #229.

**Comment by DanielRosenwasser** [comment] 2015-07-07 05:02
@impinball could you clarify which use case you're referring to?

**Comment by impinball** [comment] 2015-07-07 09:10
Sorry...I meant the `this` in function types in the main proposal. It wasn't specifically about your comment...probably should have mentioned @jonathandturner.

Also, as for that mixin model, there's already half a dozen mixin proposals out there, but this specific version proposed in the main bug is probably not the best way to go (feels incomplete).

**Comment by jonathandturner** [comment] 2015-07-07 15:36
@ahejlsberg - yeah, good to call out (1).  Though I allude to it in the proposal by talking about assignment compat with 'this', I think the way you spell it out works better and gives a better intuition.

@DanielRosenwasser - We should explore implied 'this' constraint more, and try it out on some real world code to see what impact it might have.

@impinball - agreed. This isn't intended to be used as a complete mixin solution, rather a way of modeling extension like how some libraries (like Ember) do extensibility.  For a full mixin story, you'd want the type-checking part (including something like intersection types) combined with a code generation piece.

**Comment by jbondc** [comment] 2015-07-17 15:10
:+1: though concerned about what 'this' refers to for the mixin/composition story. Are the mixed in methods included or only the single inheritance?

**Comment by jonathandturner** [comment] 2015-07-17 17:22
@jbondc - do you have an example you think would cause problems?

**Comment by jbondc** [comment] 2015-07-17 17:40
With a trait model, composition is where declared:
```
enum D {
  d
}
class B { b() {} }
class C { c() {} }
class A {
   import B, C, D; // composed here at compile time
   me(): this { return this } // includes me(), b(), c(), d
}
enum D {
  e
}
```
With a ~mixin model, it's unclear:
```
enum D {
  d
}
class A mixin(B, C, D) {
   me(): this { return this } // includes me(), b(), c(), d, e?
}
// any declaration merging, is this part of A?
enum D {
  e
}
```
Do later declarations get included?

**Comment by jbondc** [comment] 2015-07-17 18:16
To verbalize my concern, if people start using the 'mixin model' and expect 'this' to include later declarations, that conflicts with the trait model which to my understanding would be how things get merged in ES${x}.

**Comment by jonathandturner** [comment] 2015-07-17 18:17
I'm not sure exactly what your semantics are here, since this isn't valid JS/TS.

A related example in valid JS should show it a bit better:

```TypeScript
class A extends mixin(B, C, D) {
   me(): this { return this } // includes me(), b(), c(), d, e?
}
```

So yeah, from the original example in the writeup a subclass would have a 'this' type that reflects the shape of the class.  Unfortunately, I don't think there's enough descriptive power in the type system to cover the mixin forms.

**Comment by jonathandturner** [comment] 2015-07-17 18:17
(not to say there couldn't be in the future)

**Comment by jbondc** [comment] 2015-07-17 18:19
Yep forgot the 'ClassHeritage' thing, meant the ```extends mixin(B, C, D)```

**Comment by jbondc** [comment] 2015-07-17 18:38
For the previous 'trait syntax', I meant something like this:
http://wiki.ecmascript.org/doku.php?id=strawman:trait_composition_for_classes

**Comment by impinball** [comment] 2015-07-18 08:36
## This also allows classical inheritance to be modeled<br>:star::star::star:&nbsp;*correctly*&nbsp;:star::star::star:.

It's not just a mixin problem.

*<sub>(Yes, that amount of emphasis is necessary. I know of no other type system that fails at this, not even Java, C++, or C#. To me, the current behavior exposes a broken OO type system, and [really is a bug in of itself](https://github.com/Microsoft/TypeScript/issues/275).)</sub>*

It's required to type libraries with deep object hierarchies. One such example, [Lazy.js](http://danieltao.com/lazy.js/), cannot be typed without full type inheritance of delegated methods. It uses inheritance very frequently, with a very deep inheritance hierarchy. Its API uses a relatively deep hierarchy (although I also still need a way to override the return type of an inherited method for a couple specific cases in its API, namely the async equivalents of `each`). Lodash has a similar problem. Another example is the following code:

```ts
class A {
  foo(): this { return this }
}

class B extends A {
  bar(): this { return this }
}

new B().foo().bar()
```

If you change the above to this, [it will fail to compile](http://www.typescriptlang.org/Playground#src=class%20A%20%7B%0A%20%20foo()%3A%20A%20%7B%20return%20this%20%7D%0A%7D%0A%0Aclass%20B%20extends%20A%20%7B%0A%20%20bar()%3A%20B%20%7B%20return%20this%20%7D%0A%7D%0A%0Anew%20B().foo().bar()). That is *surprising* behavior for anyone used to most other static OO type systems.

```ts
class A {
  foo(): A { return this }
}

class B extends A {
  bar(): B { return this }
}

new B().foo().bar() // Property 'bar' does not exist on type 'A'.
```

This is kinda required for a few too many things.

**Comment by DanielRosenwasser** [comment] 2015-07-18 18:27
>  I know of no other type system that fails at this, not even Java, C++, or C#
> ...
>  That is surprising behavior for anyone used to most other static OO type systems.

I'm not sure what you're talking about, as far as I understand, none of those languages has self-typing.

> If you change the above to this, it will fail to compile.

Yes, because this is currently under proposal.

**Comment by impinball** [comment] 2015-07-18 20:25
The equivalent doesn't fail with Java 6 or later, correct? It's more about
the B still being a B, after being returned from an A.

**Comment by DanielRosenwasser** [comment] 2015-07-19 01:30
> The equivalent doesn't fail with Java 6 or later, correct?

No, it fails, and [it even fails in Java 8.](http://ideone.com/T7mGiX)

**Comment by MgSam** [comment] 2015-07-19 05:47
``` TypeScript
class A {
  foo(): this { return this }
}

class B extends A {
  bar(): this { return this }
}

new B().foo().bar()
```

It seems to me that this should always fail to compile. Foo returns `this`, which is A. Why should parent class A know anything about B's method `bar`?

**Comment by kitsonk** [comment] 2015-07-19 06:21
> It seems to me that this should always fail to compile. Foo returns this, which is A. Why should parent class A know anything about B's method bar?

While it is difficult to figure out at compile time, it is what is actually happening at runtime.  Because `this` is simply a reference to the instance, means at runtime, the last statement is valid.  So the argument is why couldn't TypeScript support this.  This is valid ES6:

```js
class A {
    foo() { return this }
}

class B extends A {
    bar() { return this }
}

new B().foo().bar();
```

**Comment by impinball** [comment] 2015-07-19 06:56
Okay. I'll take back most of my claims about other languages. I didn't realize that they also had the same problem. I'll take another approach: could TypeScript finally get this right? It's runtime behavior that should also be possible to infer statically, without a lot of trouble.

**Comment by jonathandturner** [comment] 2015-07-20 18:10
@MgSam yup, it's what @kitsonk says.  There's a difference here between 'this' type and returning the class type.  Your example without the 'this' type would throw the error:

```TypeScript
class A {
  foo(): A { return this }
}

class B extends A {
  bar(): B { return this }
}

new B().foo().bar()  // error Property 'bar' does not exist on type 'A'.
```

The 'this' typing is closer to what's happening at runtime, which is that B's instance is what is available after the new call.

**Comment by shovon** [comment] 2015-08-27 18:38
I might point out that supporting the "`this`" type will be super helpful when using the [bind operator](https://github.com/zenparsing/es-function-bind).

It even looks like there are plans to support the bind operator in TypeScript, judging by the looks of 8521632d1c2ee34939de8dbde6915c6d259e0c1d.

**Comment by eggers** [comment] 2015-09-03 06:30
+1 +1 +1 I just came across this issue working with decorators, and was trying to do stuff like this to solve the problem:

```typescript
function bar(): void {
  declare this: Foo;
}
```

But after reading the proposals, now I like this:

```typescript
function bar<this: Foo>(): void {}
```

over this:

```typescript
function bar(this: Foo): void;
```

or this:
```typescript
function bar<this extends Foo>(): void {}
```

----


@MgSam Why should that example fail to compile? It's a perfectly valid use of chaining. Here's something more concrete:

```typescript
/// <reference path="../typings/angularjs/angular.d.ts" />

interface CachingModule extends angular.IModule {
  cache(object: Object): CachingModule;
}

var m:CachingModule;

m.cache({}).constant("foo", "bar"); //valid, but
m.constant("foo", "bar").cache({}); //error

```

**Comment by rotemdan** [comment] 2015-09-17 05:06
```ts
class Example {
  func(): this;
  static func(): this;
}
```
* Should the static function return type be the constructor type `typeof Example`? or the instance type?
* If the static `this` is alternatively supported say, through, `typeof this` wouldn't that be confusing?
* If the `this` type is supported, how will a natural extension like `this.func` handle this ambiguity?
* If the class or function is merged with a namespace, or an ambient class is merged with an interface, what will `this` mean on those scenarios?
* Will the `this` type of a class instance and interface be also accessible from the outside? what syntax is planned for that?

**Comment by impinball** [comment] 2015-09-17 06:56
Here's my current solution for this problem, although I don't like it (I needed this for a lot of interface definitions):

```ts
interface Foo<T extends Foo<any>> {
  // ...
}
```

This idiom is very common in other languages with generics/templates, which also suffer from this same problem.

```java
// Java
class Foo<T extends Foo> {
  // ...
}
```

**Comment by impinball** [comment] 2015-09-17 07:11
@rotemdan 

1. It returns the type of the actual instance, much like ES6's `new.target`, but statically determined. It's resolved on the caller's side, not the callee's side.
2. That would refer to the `this` instance the function is called with, usually the class itself. It's still resolved on the callee's side.
3. Types and values are parsed in different contexts, and are kept in independent namespaces. For this reason, you can still have a variable named `string`.
4. See 1.
5. Highly doubt it. The function itself has no clue what `this` represents in it unless it's constrained (methods' `this` types are already implicitly constrained to their containing class) or explicitly typed.

**Comment by rotemdan** [comment] 2015-09-17 07:59
@impinball 

My questions are mostly related to ambiguities in the **semantics**, not necessarily the syntax. This includes ambiguities between references to run-time entities like namespaces and pure types like interfaces, static and instance member types, etc. Even if the syntax may not be ambiguous (at least from the point of view the compiler), the semantics could be, from the perspective of the developer.

Now:
1. The feature is for type positions, E.g. `let x: this`, which in TypeScript is purely a compile-time construct, there is no concept or "callee" or "caller", any piece of metadata that is available within any scope, including the `this` type can be unambiguously made available in outside the declaration class/interface declaration.
2. The question was about the **semantics** of `this` when referenced from a static position in the declaration. However, there is also a purely syntactic problem here in the case of a generic class:
```ts
class Example<T> {
  x: this;
  static y: this; // This is impossible
}
```
It is impossible to resolve the type of the expression `Example.y` because the type parameter is only valid for instances, E.g.. `Example<number>.y` is not valid.
3. The question was about semantics from the point of view of a human, not a mechanical difficulty of the compiler to disambiguate between different statements.
4. The question was about semantics.
5. Like 1. This is just compile time metadata, it can unambiguously be made available at any point and position of the code.

**Comment by impinball** [comment] 2015-09-18 09:35
Okay, to revisit your initial questions:

1. Yes. The type should be `typeof Example`.
2. I see no reason why it shouldn't be identical to `typeof Example`.
That's the least surprising outcome.
3. For one, I don't think it should be supported in the first place. Two,
even if it is, that's not a straightforward thing for even a human to
figure out. There's also the problem that the implementation could provide
a more permissive type than the interface itself. That would bring
nightmares for bug catching, as the type can't be determined by merely
looking at it. In some cases, you would have to look across files to figure
out all the pieces (they would be pieces).
4. It would represent the context it's defined in. If it's in a class, it
refers to the type of the instance. If it's in an interface, it refers to
an instance of that interface. If it's the return type of a function, it
deals with the `this` inside the function.
5. Probably not. It's defined per-function. And I doubt there's much of a
use case for getting that context outside the function.

Sorry for not quite understanding your question. Is this better?

**Comment by rotemdan** [comment] 2015-09-18 10:08
@impinball 

One reason I'm mentioning this is because this proposal is relatively short sighted when it comes to allowing future extensions, like referencing the types of properties:
```ts
class Example {
  member: number;
  getMember(): this.member {
  ..
  };

  static member: string;
  static getMember(): this.member {
  ..
  }
}
```
If using different semantics at static and instance contexts, the problem then would be `this.member` at an instance position would mean the instance member (typed `number`) and `typeof this.member` at the same position would be static member (typed `string`). This would be very confusing. It also has the problem that it doesn't naturally extend to a way of referencing those types from the outside (this also includes function `this` type, which can be useful, especially if that function is used as a constructor).

In any case, having `this` mean the class type and `typeof this` mean the constructor type is also not great syntax in general.

**Comment by rotemdan** [comment] 2015-09-18 10:29
@impinball 

This problem also surfaces in the current proposal, regardless of any extensions, and even when `this` is entirely disallowed at static positions:

```ts
class Example {
  member: number;

  // Technically this should reference the static member's type. But other than the compiler 
  // and those deeply familiar with the language spec, no one would guess this would be the case:
  func(): typeof this.member; 

  static member: string;
}
```

**Comment by impinball** [comment] 2015-09-19 06:34
@rotemdan 

You're talking to someone who really doesn't like the idea of a `this.prop` type or similar. All I see is a ***gigantic*** footgun with no decent use case. Could you come up with a compelling, real-world example where the very idea itself could be useful?

```ts
// This should fail to compile. Happy hunting, even in this contrived example.
interface Foo {
  foo: string;
  member: this.foo;
  func(): this.member;
}

interface Bar extends Foo {
  bar: number;
  member: this.bar;
}
```

Do we ***really*** need to have strong implicit coupling between types?

**Comment by rotemdan** [comment] 2015-09-19 07:29
@impinball 

There is already a way to achieve strong implicit coupling between property types (although I wouldn't say it is very 'implicit'):
```ts
class Example {
  static a: string[];
  static b: typeof Example.a;
}
```
or more indirectly in interfaces (same approach can be use to reference class instance members):
```ts
interface A {
  a: number;
  b: typeof x.a; // Note this wouldn't work if A.a is a generic type.
}

let x: A;
```
More generally, any type alias is a essentially a strong coupling between types:
```ts
type A = number;
type B = A;
type C = B;
...
// Generic aliases (introduced in 1.6):
type A<T> = Array<T>;
type B<T> = { a: A<T> }
type C<T> = B<T>;
...
```

You don't have to use any of this if you think it is a bad practice. As for better syntax for property type references, see my proposal at #4640, which also includes a more constrained approach to a `this` type, that tries to address some of the issues I mentioned here.

----

In any case, this isn't really related to the issue of `typeof this.member` pointing to a static member type:
 * Modifying it to point to an instance member instead would change the semantics of `this` to reference the 'isolated' class instance type - a type that doesn't exist in typescript at the moment, and if this approach is taken, wouldn't be directly referenceable from the outside, though that would be possible with a simple trick:
```ts
class Example {
  a: this;
  static b: number;
}

let x: Example;

// The type of 'instance' is the isolated instance type of 'Example', which doesn't have a name
// or a way to describe it e.g. the closest way would be instance: { a: ??? }
let instance: typeof x.a; 
``` 
* Disallowing it completely (and also assuming it's disallowed at static positions) would weaken the class `this` type to the point it can only be used in very trivial cases, and wouldn't be loyal to the semantics of the containing class type.

**Comment by impinball** [comment] 2015-09-19 08:25
@rotemdan 

1. Do take into account that other than a standard `this` type to refer to the instance's type, the implementation will be hard.
2. I'm going to re-ask my question: could you demonstrate a real-world example of where this would be useful?

**Comment by rotemdan** [comment] 2015-09-19 09:18
1. Not sure what is referenced as 'hard' to implement.
2. I'm not exactly sure what you are referring to, anyway, I was never mentioning that 'trick' for useful applications. The reason I mentioned that was because of semantic correctness: 
```ts
class Example {
  func(): this {
    ...
  }

  a: number;
  static a: string;
}

let instance = new Example();
let x = instance.func();
``` 
Assuming `this` points to the isolated instance type of the class (i.e. `typeof this.a` refers to the instance member type) . What should the type of `x` be inferred here? would it be semantically correct resolve it to class type `Example` (where `typeof Example.a` would refer to a static member type)?

Also, if it is will be possible to declare:
```ts
class Example {
  static a: string; 
  a: number;
  b: typeof this.a;
}
```
and have `b` reference to the instance property type, why not also allow to do this from the outside? (this includes references from anonymous interfaces within the class itself), but then any syntax that would be proposed would not be consistent with the `typeof this` syntax because `typeof Example.a` would point to the static property type. This is a part of the complex chain of reasoning that lead to formulating the [`typeon` operator](https://github.com/Microsoft/TypeScript/issues/4640), as a more 'complete' package, that is consistent both for internal and external references.

**Comment by impinball** [comment] 2015-09-20 03:55
@rotemdan Are you wanting this feature yourself?

**Comment by errorx666** [comment] 2015-09-21 15:29
@impinball I find myself using the [Curiously recurring template pattern](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern) in most OO languages to represent this, which, in my opinion, is a hack workaround. Full fledged support for a `this` type would be immensely welcome.
:+1:

**Comment by ahejlsberg** [comment] 2015-09-22 13:56
An implementation of polymorphic 'this' typing is now available in #4910.

**Comment by eggers** [comment] 2015-09-22 20:41
@ahejlsberg Thanks, that's great. That request doesn't address the specification of a this type in functions yet? Does it?

e.g.

```TypeScript
function f<this: {a: string}>() {
  return this.a;
}
```

**Comment by Zorgatone** [comment] 2015-09-28 07:42
+1

**Comment by falsandtru** [comment] 2015-10-29 08:17
:+1: some browser apis define the custom `this` object.

**Comment by irakliy81** [comment] 2015-11-09 17:07
+1

**Comment by tkqubo** [comment] 2015-11-09 22:26
+1

**Comment by toadzky** [comment] 2015-11-17 01:43
:+1:  It's been a couple months since the last real discussion on this. Is there any updates?

**Comment by basarat** [comment] 2015-11-17 01:51
@toadzky its been merged : https://github.com/Microsoft/TypeScript/pull/4910 :rose: And a few APIs in `lib.d.ts` have also been udpated

**Comment by eggers** [comment] 2015-11-17 03:57
@basarat @toadzky I think that pull request just handles polymorphic types, but not the ability to set the the type of `this` as an argument for functions, for example:

```
function f<this extends {x:number}>() {
  this.x = 3;
  this.y = 6; //error: y is not available on this
}
```

**Comment by impinball** [comment] 2015-11-17 04:10
@eggers That's what I've gotten as well. It's mostly for TypeScript's solution to the [CRTP](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern) (example from Wikipedia):

```java
// Java
public interface Comparable<T extends Comparable> {
    int compareTo(final T other);
}

public class Item implements Comparable<Item> {
    private String name;
    constructor(String name) {
        this.name = name;
    }

    @Override
    public int compareTo(final Item other) {
        return name.compareTo(other.name);
    }
}
```

```scala
// Scala
trait Comparable[T <: Comparable[_]] {
  def compareTo(other: T): Int
}

class Item(private val name: String) extends Comparable[Item] {
  def compareTo(other: Item): Int = name compareTo other.name
}
```

```ts
// TypeScript
interface Comparable {
    compareTo(other: this): number;
}

class Item extends Comparable {
    constructor(private name: string) {}

    compareTo(other: Item): number {
        return name.compareTo(other.name);
    }
}
```

**Comment by impinball** [comment] 2015-11-17 04:10
The rest of it is still yet to be done.

**Comment by mhegazy** [comment] 2015-11-17 04:34
As @impinball and @eggers noted #4901 only handles the class and interface case but not the function one. This is why the issue is still open. The next step is the ability to declare a constraint on the type of this argument in a function and check against that at call sites.

**Comment by toadzky** [comment] 2015-11-17 07:32
ok. I could really use that feature. i'm using koa, which binds everything to `this` when it invokes the handler function.

**Comment by kobezzza** [comment] 2015-11-19 09:57
+1

**Comment by Zorgatone** [comment] 2015-11-19 10:46
+2

**Comment by falsandtru** [comment] 2015-12-03 09:01
Hi, please merge following syntax into this discussion.

```ts
var o = {
  method() {
    this; // `this` is `o` object
  },
  anon: function () {
    this; // `this` is `o` object
  }
};
```

#5817

**Comment by sandersn** [comment] 2015-12-09 18:23
I put up a proposal for this-function types at #6018 (with a link to a prototype as well).

**Comment by LPGhatguy** [comment] 2016-01-06 00:15
It appears #4910 did not address the possibility of `typeof this` though it did allow `this` in plenty of type expressions.

What was the resolution on that idea? It would allow for resolution of #3841 with syntax like:

```ts
class A {
	"constructor": typeof this;
}

let a = new A();
let b = new a.constructor();
```

**Comment by DanielRosenwasser** [comment] 2016-01-06 00:39
@LPGhatguy see #1554 and #2542.

**Comment by isiahmeadows** [comment] 2016-01-06 00:46
@LPGhatguy Also, as @ahejlsberg rightly mentioned [here](https://github.com/Microsoft/TypeScript/issues/3841#issuecomment-163350868), not all JS constructors are well-behaved in this area. Too many people unintelligently do this (I admit I have a few times in small scripts and pages, out of laziness, but not in anything big):

```js
function Foo() {
  // ...
}

Foo.prototype = {
  bar: function () {
    // ...
  },
}
```

In this case, `new Foo().constructor === Object`, because the object literal's constructor is `Object`. It was never actually set in the prototype object itself. That's the other problem.

**Comment by KamilSzot** [comment] 2016-01-29 01:15
We have:

```typescript
class C {
  a: any
}
function fn(cb: (a:C) => void) {}
fn((c) => { c./code completion kicks in here/ })
```

Could we also have...?

```typescript
function fn(cb: (this:C) => void) {}
fn(() => { this./code completion should kick in here/ })
```

**Comment by isiahmeadows** [comment] 2016-01-29 01:46
@KamilSzot 

Arrow functions don't have their own `this`, but inherit from the parent scope. I'm guessing you meant this?

```ts
function fn(cb: (this:C) => void) {}
fn(function () { this./* code completion should kick in here */ })
```

**Comment by sandersn** [comment] 2016-01-29 02:07
@KamilSzot @isiahmeadows I just wrote a test for what you want in my ongoing work to implement `this` for functions: 41d133f9fab6a58e6e2d303584f40c82b2446d9e
As Isiah points out, it only works with `function`, not `=>`.

**Comment by mhegazy** [comment] 2016-04-07 23:39
with https://github.com/Microsoft/TypeScript/pull/6739, `this` types can be specified for functions. a new compiler flag, `--noImplicitThis` makes it an error if `this` is used without being defined in the containing function.

**Closed by mhegazy** 2016-04-07 23:39 UTC
Labels: In Discussion, Suggestion

**Comment by isiahmeadows** [comment] 2016-04-08 21:55
@mhegazy I have a couple clarification questions:

1. I'm guessing you're just referring to literal ES5 functions?
2. Does `func(function (x: string) { ... })` trigger `noImplicitThis` if the callee *doesn't* define a `this` type for the argument, such as in `func(f: (x: string) => any): any)`?

**Comment by sandersn** [comment] 2016-04-08 22:02
1. Methods can also declare a this parameter:

```ts
class C {
  totalCallback(this: void, e: Event); // assign to me!
}
```

2. `noImplicitThis` is triggered by this *expressions* in the body of a function. It is independent of assignability checks, which default to `any` if no this type is declared.

In other this is an implicit this error:

```ts
function f(n: number) {
  return this.m + n; // error -- this: any
}
```

But this is a normal old assignability error:

```ts
function f(this: void) { ... }
class C {
    m(this: this) { ... }
}
let c: C;
c.m = f; // error!
````

**Comment by isiahmeadows** [comment] 2016-04-08 22:48
@sandersn Thanks! :smile:

**Comment by vitaly-t** [comment] 2016-05-09 14:07
@sandersn Thanks! I think the approach to declare the first parameter as `this: myType` is the best one:

**Comment by nippur72** [comment] 2016-06-21 07:39
IMO the syntax is a bit verbose, instead of
```ts
function f<this extends {x:number}>() {
  this.x = 3;
}
```
why not simply:
```ts
function f() {
  let this: {x:number};
  this.x = 3;
}
```

**Comment by Zorgatone** [comment] 2016-06-21 07:59
@nippur72 no, that's not good. You're actually declaring a variable named this and not initializing it (undefined). The compiled code would have: `var this;` in it and have a runtime error

**Comment by nippur72** [comment] 2016-07-15 11:03
has this landed in 2.0 ? I just copied this in a 2.0 project:
```ts
function f<this extends {x:number}>() {
  this.x = 3; 
}
```
but it tells me: 
>index.ts(1,12): error TS1139: Type parameter declaration expected.
index.ts(1,17): error TS1005: ';' expected.
index.ts(1,35): error TS1109: Expression expected.
index.ts(1,37): error TS1109: Expression expected.
index.ts(1,39): error TS1005: ';' expected.

**Comment by shelby3** [comment] 2016-09-10 07:37
@jonathandturner [wrote](https://github.com/Microsoft/TypeScript/issues/3694#issue-92455507):
> ```ts
> function f<this extends {x:number}>() {
>   this.x = 3;
>   this.y = 6; //error: y is not available on this
> }
> ```

Don't you mean `implements` instead of `extends`, since f is not allowed to add new member properties?

> ```ts
> var o = {myMethod: f, y: "bob"};
> o.myMethod(); //error: o does not match the shape of 'this' for 'myMethod'
> ```

Is `new o.myMethod()` legal?

**Comment by yhaskell** [comment] 2016-10-05 10:10
Can we also propagate this to work with static functions? 

Suppose, we have following code:
```typescript


class C {
    constructor() { console.log("C"); }
    static foo() { return new this(); }
}

class D extends C { 
    constructor() {
        super();
        console.log("D");
    }
    bar() { return 42; }
}

var d = D.foo(); // valid and works. Will output C and then D

console.log(d instanceof D);

console.log((<D>d).bar());
```

Can we add a possibility to type it correctly?

**Comment by HerringtonDarkholme** [comment] 2016-10-05 10:31
Of course you can. TypeScript has very advanced type system now.

```typescript
class C {
  static foo = function <D extends C>(this: {new(): D}) {return new this()}
}

class D extends C {
  bar() { return 42}
}

var d = D.foo()
d.bar()
```

**Comment by yhaskell** [comment] 2016-10-05 10:35
That looks like very dirty hack, although it works.

**Comment by marcusjwhelan** [comment] 2017-04-18 03:34
Is it possible to get the Type of my class I am currently working in? for example

```javascript
export class A{
    // constructor + methods
    // can use `A` as a return Type
}
export class B extends A{
    public b:any = this;
    // here in my methods if I use a return type of `B` it implies class `A`type
    // how do I use `B` as a type?
    fun():B {
        const self = this.b;
        return self;  // Error: Type 'A' is not assignable to type 'B' , property 'some class var' is not in type 'A.
    }
}
```

**Comment by basarat** [comment] 2017-04-18 03:47
@marcusjwhelan I think you want: 

```ts
export class A {
}
export class B extends A {
    fun(): this {
        return this;
    }
}
```
https://egghead.io/lessons/typescript-create-a-fluent-api-using-typescript-classes :rose:

**Comment by marcusjwhelan** [comment] 2017-04-18 03:52
@basarat ah thank you for the quick reply. Although I actually figured out that it was fault code on my part. The reason I could not use the class as a type was an issue with me assigning the variable that was to be returned as the parent type, copy paste error.
