### ISSUE TITLE
Unable to load a submodule from a npm package with TS 2.5.3

### ISSUE THREAD

**Issue by dieseldjango** [Microsoft/TypeScript#19129] opened 2017-10-12 15:35 UTC
**TypeScript Version:**  2.5.3 (also not fixed in typescript@next)

**Code**
See [this github repo](https://github.com/dieseldjango/load-submodule-from-package).

**Expected behavior:**
I am using some NPM packages that provide submodules that can be independently loaded. With TS 2.5.2 I can import these and compile. See the github repo mentioned above for an example.

**Actual behavior:**
With 2.5.3 or typescript@next I get a `Cannot find module` error.

**Comment by andy-ms** [comment] 2017-10-12 16:18
We look for a `package.json` when loading from `node_modules`, not when loading an arbitrary directory. In previous versions I think we would look in every directory, but that would cause problems in loading from `foo/bar` and the package.json is actually in `foo/package.json` and not `foo/bar/package.json`.
Looks like a duplicate of #18988. Now I'm wondering how many people are adding `package.json` in unusal locations and if we should now search for it in two locations, both `foo/bar/package.json` *and* `foo/package.json`.

**Comment by dieseldjango** [comment] 2017-10-12 16:56
I could be wrong, but I believe the correct behavior would be to search for package.json in the path indicated by the import: `foo/package.json` if importing from `"foo"`, and `foo/bar/package.json` if importing from `"foo/bar"`. Why would it be valid to import from `"foo/bar"` but actually use a package.json from another directory?

**Comment by dieseldjango** [comment] 2017-10-12 17:35
I've looked into this some more with some packages from which I import submodules.

In `react-icons` I import from `react-icons/fa/plus`. That path references a `fa/plus.d.ts` file in the `@types/react-icons` package, and a `fa/plus.js` file in the `redux-saga` package. TS is able to load the types correctly and webpack loads the JS correctly.

In redux-saga I import from `redux-saga/effects`. That path references an `effects.d.ts` file in the package, while there is also an `effects` directory that contains a `package.json`, which specifies via the `main` property where the module code file is located. TS loads the type def correctly, and node loads the module correctly via the package file.

The one that isn't working is a private package where I'm importing something like, 'my-package/foo'. The package has a `foo` directory that contains a package.json, which has a `types` property that specifies where the type definition is located, and a `main` property that specifies where the code is located. Prior to TS 2.5.3 this worked fine.

Given that node is able to find that package file and load the module, I would expect TS to do the same. It might be worth taking a closer look at node's module resolution code.

**Closed** 2017-10-16 20:07 UTC
Labels: Bug, Fixed
