### ISSUE TITLE
excluded type narrowing

### ISSUE THREAD

**Issue by jonnytest1** [microsoft/TypeScript#47919] opened 2022-02-16 15:05 UTC
# Bug Report

### 🔎 Search Terms
type narrowing

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
class A {
    a() { }
}

let el: A | string
let el2: A | string

if (el instanceof A || el2 instanceof A) {
    if (el instanceof A && el2 instanceof A) {


    } else if (el instanceof A) {
        el2 // string | A
    }
}
```

### 🙁 Actual behavior

if el or el2 are instance of A 
AND
! (el and el2) instance of A
AND
el isntance of A
then el2 can only be string  - but is shown as string|A

### 🙂 Expected behavior

(😅 i know its over the top )
but if possible i would like el2 to be narrowed down to string

**Comment by MartinJohns** [comment] 2022-02-16 16:09
This sounds like a duplicate of #37258.

**Comment by fatcerberus** [comment] 2022-02-16 16:16
Yeah so the problem here is that narrowing is done for each expression individually and `el instanceof A || el2 instanceof A` doesn't give the compiler enough information to narrow either one (one of them is an `A`, but which one?).  When it gets the `&&` check it can narrow *that* (it now knows both are `A`s), but it can't do anything in the `else` clause because at that point the compiler would have to look *backwards* at past type checks to actually narrow something.

**Closed** 2022-02-16 17:13 UTC
Labels: Duplicate
