### ISSUE TITLE
Casting `U|T` to `U` is newly an error in nightly (4.8.0-dev.20220609)

### ISSUE THREAD

**Issue by frigus02** [microsoft/TypeScript#49457] opened 2022-06-09 15:25 UTC
# Bug Report

### 🔎 Search Terms

TS2352, sufficiently overlaps

### 🕗 Version & Regression Information

- This changed between versions 4.7.2 and v4.8.0-dev.20220609

### ⏯ Playground Link

[Playground link (4.7.2) with relevant code (no error)](https://www.typescriptlang.org/play?ts=4.7.2#code/GYVwdgxgLglg9mABMAPAVQDSICpYBqICmAHlIWACYDOiaAPtgHwAUxAXIngJSIDeAUIiGIICKlEQB9DmkQBeRMUQBDGmgDc-AL5A)

[Playground link (nightly) with relevant code showing the error](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220609#code/GYVwdgxgLglg9mABMAPAVQDSICpYBqICmAHlIWACYDOiaAPtgHwAUxAXIngJSIDeAUIiGIICKlEQB9DmkQBeRMUQBDGmgDc-AL5A)

### 💻 Code

```ts
function f<U, T, X extends U|T>(x: X) {
    const _: U = x as U;
//               ^^^^^^
// Conversion of type 'X' to type 'U' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
//   'U' could be instantiated with an arbitrary type which could be unrelated to 'X'.(2352)
}
```

### 🙁 Actual behavior

This is an error in nightly (4.8.0) but was fine in 4.7.2.

### 🙂 Expected behavior

The new error doesn't feel helpful to me. I expect assigning `U|T` to `U` to be an error. But the explicit cast feels enough to me because `U|T` seem related to `U`. I don't feel like casting through `unknown` should be necessary.

**Comment by RyanCavanaugh** [comment] 2022-06-09 16:26
This wasn't an intentional change AFAIK

**Comment by MartinJohns** [comment] 2022-06-09 21:05
@fatcerberus Using type assertions was always allowed to ignore type-unsafety as long as there's somewhat of an overlap. `X` may extend `U`, so there's some overlap.

**Comment by ahejlsberg** [comment] 2022-06-09 21:09
@typescript-bot bisect good v4.7.2 bad main

**Comment by ahejlsberg** [comment] 2022-06-09 21:14
We'll see what the bisect says, but I'm pretty sure this is caused by #48861.

@weswigham Thoughts?

**Comment by ahejlsberg** [comment] 2022-06-09 21:55
It is indeed caused by #48861. The code in that PR disallows relating type parameters unless one extends the other *in a direct chain*. In other words, it doesn't make provisions for union type constraints.

**Comment by weswigham** [comment] 2022-06-09 22:09
Yup. We could expand it, but as noted by the poster above, it's definitely not a particularly safe cast; it's neither a downcast nor an upcast.

**Comment by frigus02** [comment] 2022-06-10 07:29
My argument is that `U|T` is enough of a relation to `U` that an explicit cast is enough.

> it's definitely not a particularly safe cast

That is true, though. I could understand a decision either way.

**Comment by fatcerberus** [comment] 2022-06-10 13:38
> My argument is that U|T is enough of a relation to U that an explicit cast is enough.

See my post above.  imo, whether `U | T` is related to `U` is the wrong question, because `X` is generic.

**Comment by ahejlsberg** [comment] 2022-12-08 15:30
I'm going to close this as working as intended.

**Closed** 2022-12-08 15:31 UTC
Labels: Working as Intended
