### ISSUE TITLE
keyof object is number instead of string 

### ISSUE THREAD

**Issue by eek** [microsoft/TypeScript#41669] opened 2020-11-24 11:50 UTC
**TypeScript Version:**  4.1.2 (actually all versions 3.3.3 - 4.1.2)

**Search Terms:**
keyof declared object is not only string, keyof object type, keyof declared key, keyof

**Code**

```ts
type GenericObject = { [key: string]: any };
type GenericKeyType = keyof GenericObject;
```

**Expected behavior:**
`GenericKeyType` should be of type `string`

**Actual behavior:**
`GenericKeyType` is `number | string` 

**Playground Link:** 
https://www.typescriptlang.org/play?#code/C4TwDgpgBA4hB2EBOBLAxgeQEYCsJuCgF4oBvKAbQGsIQAuKAZ2FXgHMBdBgQ3hCgC+AbgBQI0JFgJk6ANK0AKuGgkaIAPYAzKYlSZc+YEKA

**Related Issues:** 
Didn't find anything.

**Comment by MartinJohns** [comment] 2020-11-24 12:22
Duplicate of #39543. Used search terms: `keyof index number`

**Comment by ExE-Boss** [comment] 2020-11-24 14:18
Arguably, now that we have <https://github.com/microsoft/TypeScript/pull/40336> and <https://github.com/microsoft/TypeScript/pull/40598>, `keyof` should report <code>\`${number}\`</code> for numeric index signatures.

**Comment by eek** [comment] 2020-11-24 14:40
Thanks for the link to #39543 @MartinJohns, but I still think this is a bug.

I'm saying it's a bug because I'm explicitly saying that `GenericObject` must have only `string` keys, and I've seen the reply saying it's by design decisions of `keyof` to be able to allow `string | number | symbol` from [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#support-number-and-symbol-named-properties-with-keyof-and-mapped-types).

But I think explicit types should be respected. Not to mention there's also an inconsistency between:

```ts
type GenericObject = { [key: string]: any };
type GenericKeyType = keyof GenericObject; // number | string
```

![image](https://user-images.githubusercontent.com/2953026/100108369-607f3c00-2e73-11eb-98be-fe033da0bc2c.png)


and

```ts
type GenericObject = { [key in string]: any };
type GenericKeyType = keyof GenericObject; // string
```

![image](https://user-images.githubusercontent.com/2953026/100108530-899fcc80-2e73-11eb-89f3-f8ad60745f7f.png)

And I don't think there's any difference between:
`[key: string]` and `[key in string]` // sure, the `in` is meant for other usages but should still be the same.

**Comment by MartinJohns** [comment] 2020-11-24 14:42
@eek But it's not a bug, it's a design decision. One you probably disagree with, but nonetheless not a bug.

**Comment by eek** [comment] 2020-11-24 15:25
> Different syntaxes are for different features. Consistency is not a desirable goal for something like this.


But both the variants report the exact same type for `GenericObject`:

![image](https://user-images.githubusercontent.com/2953026/100113160-b3a7bd80-2e78-11eb-954b-42381aa7eea5.png)

How can then one `keyof` report only `string` and one report `string | number` ?

Also, why is `number` as a key enforced only upon the string key

![image](https://user-images.githubusercontent.com/2953026/100113325-df2aa800-2e78-11eb-9a8a-d43900d79411.png)

but `string` isn't enforcing anyone?

![image](https://user-images.githubusercontent.com/2953026/100113824-6b3ccf80-2e79-11eb-8b5e-1f1f7613457e.png)

I would expect Symbol to not be allowed in any of them, and string only in string / number only in number.

Playground can be found [here](https://www.typescriptlang.org/play?ts=4.1.2#code/MYewdgzgLgBAHgLhgCgN4G0JLAVwLYBGApgE4C62+xJAvgJQwC8MqAUDBzAEQCGXSARgA07TgMEjOMdAGUAnoRAAbZAHI4quhRgDWNVkA)

**Comment by RyanCavanaugh** [comment] 2020-12-01 22:39
This is the intended behavior in all cases.

**Closed** 2020-12-02 10:59 UTC
Labels: Working as Intended
