### ISSUE TITLE
Unexpected type argument inference

### ISSUE THREAD

**Issue by ltblue** [microsoft/TypeScript#46623] opened 2021-11-01 17:17 UTC
# Bug Report

### 🔎 Search Terms

generic type argument inference

### 🕗 Version & Regression Information

4.4.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.4#code/C4TwDgpgBAKuEB4ZQgD2BAdgEwM5QEYAfAJgD4oBeKAKClhXSz0KgH4pMBXAWwCMIAJygAuWvWRoMOfCXZRcwQQEtMAc1F1OEAG5CA3DRqhIUAGIB7C0kbSWxclSgAKVGIDeAQzEwANFD4feCQyAF8ASioKHQtlbEMaADMuTABjYGULTChEqwJXD29Cf0DOXgFBUKgiKC8xEhKxRRV1CNrQpJT0zOzcixIC2qKGgKalVTUqmrri0bL+ITb3Ds60jKyAz0EbKWZ8BwpnIr85y2sYMkjloz4t5wJ-PoJw-SgAejeoCwBrGlvBZwjJ4vd6fISCCyCMQAQUEal4WGAX0SUBM0AA5CR0VBlPhMBYkZ5cLhlGpMJ4+AAbaDACxQMBbTw8CAYYQWFFoqDogjogB0gIAzAAWACs4RudweOSsJBBHxQgghUKgsPhzMwSPZqPgXJ5OLxBKgRJJZIp1NRdIZgiZLKEyO1pkxfMFovF-0Bjxlcs+PxoQA)

### 💻 Code

```ts
type Type<T extends 1|2> = 
  T extends 1 ? number : 
  T extends 2 ? string :
  never;

type Foo<T extends 1|2> = (x: {a: T, b: Type<T>}) => void;

function foo1(x: {a: 1, b: number} | {a: 2, b: string}) {}
function foo2(x: {a: 2, b: string} | {a: 1, b: number}) {}

function bar<T extends 1|2> (a: T, b: Foo<T>) {}

bar(1, foo1); // ok
bar(2, foo1); // error: Argument of type '2' is not assignable to parameter of type '1'.(2345)

bar(1, foo2); // error: Argument of type '1' is not assignable to parameter of type '2'.(2345)
bar(2, foo2); // ok
```

### 🙁 Actual behavior

In `bar`, `foo1` is always inferred to be `Foo<1>` and `foo2` is always inferred to be `Foo<2>`

### 🙂 Expected behavior

It is supposed to be no error there because `foo1` and `foo2` have the same type, which can satisfy all the four calls.

**Comment by andrewbranch** [comment] 2021-11-01 18:13
Duplicate of https://github.com/microsoft/TypeScript/issues/45603, already fixed in nightly

**Closed by andrewbranch** 2021-11-01 18:13 UTC

**Comment by ltblue** [comment] 2021-11-02 02:41
> Duplicate of #45603, already fixed in nightly

Thanks. But I found it doesn't work if I use function overload instead of union type in nightly. Here is the code.
```ts
type Type<T extends 1|2> = 
  T extends 1 ? number : 
  T extends 2 ? string :
  never;

type Foo<T extends 1|2> = (x: {a: T, b: Type<T>}) => void;

function foo1(x: {a: 1, b: number}): void;
function foo1(x: {a: 2, b: string}): void;
function foo1(x: any) {}

function bar<T extends 1|2> (a: T, b: Foo<T>) {}

bar(1, foo1); // error: Argument of type '1' is not assignable to parameter of type '2'.(2345)
bar(2, foo1); // ok
```
[Playground v4.5.0-dev.20211101](https://www.typescriptlang.org/play?ts=4.5.0-dev.20211101#code/C4TwDgpgBAKuEB4ZQgD2BAdgEwM5QEYAfAJgD4oBeKAKClhXSz0KgH4pMBXAWwCMIAJygAuWvWRoMOfCXZRcwQQEtMAc1F1OEAG5CA3DRqhIUAGIB7C0kbSWxclSgAKVGIDeAQzEwANFD4feCQyAF8ASioKHQtlbEMaADMuTABjYGULTChEqwJXD29Cf0DOXgFBCLEYuMNktIysnLyCqC8xEhKxRRV1Kqga+KSU9Mzs3It8tyhPTBBI91CjetGmvk9BGylmfAcKZyK-ALFLaxgyBaWadcFnAn8JgnD9KAB6V5RBQQtBMQBBQRqXhYYBQCyJKAmaAAcgI0KgynwmAsoM8uFwyjUmE8fAANtBgBYoGANp4eBAMMJwZD4FBoSRoQA6ZwkADMABYAKzha4bFkPPLPN4fCwAaxoQA)

**Comment by andrewbranch** [comment] 2021-11-02 20:03
That's expected; inference doesn't pick overloads; it just uses the last one.
