### ISSUE TITLE
switch case unreachable code checking when use string literals

### ISSUE THREAD

**Issue by stepancar** [Microsoft/TypeScript#7745] opened 2016-03-31 11:32 UTC
Hello! See example
``` javascript
type lang = "en" | "ru";
function getDict(lng: lang): any {
    switch (lng) {
        case 'ru':
            return ru;
        case 'stringNotInLangType':
            return en;
    }
}
```
compiler should throw error, cause 
``` javascript
 case 'stringNotInLangType':
            return en;
```
is unreachable

**Comment by mhegazy** [comment] 2016-03-31 16:27
duplicate of https://github.com/Microsoft/TypeScript/issues/6149

**Closed by mhegazy** 2016-03-31 16:27 UTC
