### ISSUE TITLE
Suggestion: Copy doc comments for Partial<T>

### ISSUE THREAD

**Issue by xuld** [Microsoft/TypeScript#13251] opened 2017-01-02 10:14 UTC
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
interface A {
    /** I'm a doc comment. */
    prop: string;
}

type B = Partial<A>;

var a: A;
var b: B;
```

**Expected behavior:**
The doc comment of `A.prop` should be copied to `B.prop`.
Since there is no other method to add doc comments for type B.

**Actual behavior:**
`a.prop` has a description while `b.prop` dose not.

**Comment by sandersn** [comment] 2017-01-03 18:01
Doc comments are attached to a node. I can't remember if synthetic symbols like those created by `Partial<T>` have their original nodes. If not I'll have modify the jsdoc lookup code to get the doc comments from the original symbol's node.

**Comment by sandersn** [comment] 2017-01-26 17:25
This is likely a duplicate of #13690 and will be fixed when that is. I'll leave this issue open in case there is additional work to do after the fix for that is done.

**Comment by sandersn** [comment] 2017-01-26 20:18
Actually, this is a duplicate of the earlier bug #12966. I'll close this one in favour of that one.

**Closed by sandersn** 2017-01-26 20:18 UTC
Labels: Bug
