### ISSUE TITLE
Safe guard for elements of fixed array yields error when trying to use whole array

### ISSUE THREAD

**Issue by G07cha** [microsoft/TypeScript#32632] opened 2019-07-31 09:09 UTC
**TypeScript Version:**  3.6.0-dev.20190730

**Search Terms:**

- Type guard for items of fixed array
- Validating items of fixed array

**Code**

```ts
const foo: [Date | undefined, Date | undefined] = [undefined, new Date()]

const strictDatePair = (dates: [Date, Date]) => console.log(dates)

if (foo[0] instanceof Date && foo[1] instanceof Date) {
    strictDatePair([foo[0], foo[1]]) // ok
}

if (foo[0] instanceof Date && foo[1] instanceof Date) {
    strictDatePair(foo) // error TS2345: Argument of type '[Date | undefined, Date | undefined]' is not assignable to parameter of type '[Date, Date]'.
}
```

**Expected behavior:**

If item is narrowed to a specific type it should be reflected in array

**Actual behavior:**

It's only related to individual item

**Playground Link:** https://www.typescriptlang.org/play/index.html#code/MYewdgzgLgBAZiEAuGBtAIgQygUxgHxgFcwATHOASzB1IBoYtcDiyLraBdGAXjRPJUa9GDQDujbDgAUASk4AoBaEixoAJ0rAoTHAAVMldbxjTSUiCgxSGuzrN4A+GCoggANjgB07kAHMzC1klSjhpBBBUAAZuamhMMGAcEDhJZgAydPhEVABGWNUEpJS0nAcAbwUYapgNLR0pAyNpVAjozgY2-PsFAF8QsLaYmDioIuTU3RhM7Mj8kcLEidKKqpq67V0m9XDEYN6gA

**Related Issues:** No

**Comment by nmain** [comment] 2019-07-31 12:29
This is a duplicate of https://github.com/microsoft/TypeScript/issues/31755, even though the tuple type makes it look a bit different.

**Closed** 2019-07-31 12:38 UTC
