### ISSUE TITLE
TypeScript does not recognize getters with union types

### ISSUE THREAD

**Issue by wesleycho** [Microsoft/TypeScript#5776] opened 2015-11-24 17:01 UTC
I have a particular setup

```js
class Foo {
  get bar() {
    return 'foobar';
  }
}

class Bar {
  get foo() {
    return 'foobar';
  }
}

class Foobar {
  data: Foo | Bar;

  baz() {
    if (isFooInstance(this.data) {
      return this.data.bar;
    }
  }
}
```

TypeScript throws an error in this situation saying `bar` does not exist on `Foo | Bar` - this is incorrect behavior IMO, especially if I have already screened out what type it is via other mechanisms.

**Comment by RyanCavanaugh** [comment] 2015-11-24 17:35
Duplicate of #3812

**Closed by RyanCavanaugh** 2015-11-24 17:35 UTC

**Comment by wesleycho** [comment] 2015-11-24 18:16
Ah sorry, couldn't find anything mentioning union types in particular when searching for issues.
