### ISSUE TITLE
Type parameter appears in function parameter should be optional.

### ISSUE THREAD

**Issue by caikan** [microsoft/TypeScript#45963] opened 2021-09-20 03:29 UTC
# Bug Report

### 🔎 Search Terms

`omit` `type` `arguments` `2558`

### 🕗 Version & Regression Information

v4.4.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/FAMwrgdgxgLglgewgAgCYFMQB4CyAaZAFWXQA8Z0JUBnZAb2QG0AFZOFAa3QE8ERkcAXQBcyajABO7AObIAvgD4AFADcAhgBtRhAJT1gyQ8gnoYYCSnUbgc4MChJxyNcgC8aTFgZrRARgIARqIATPLKdAZGIAgIogDkAWoScTY6ANx24NDwSMhQJmoUACKeOMp6EUbIMNwADujIAMpu9Eys7MhcvPxCouJSELK2VSZmFshZsIgoWMRkFFS0jcpW2hWRVYaj5paaG-I2dg4QTgEt+eiF6CXY3n6BIWFKOkqVRj7IcQAW6BoaCHE8Psgp8AO4ICQaVCA-bRWKfRLJVJAA)

### 💻 Code

```ts
function def<M, T extends { [P in keyof M]: string }>(val: T) {
    return val
}

// 👇Expected 2 type arguments, but got 1.(2558)
const a = def<{ a: 1, b: 2 }>({
    foo: 'bar'
});

function createDef<M>() {
    type S = { [P in keyof M]: string }
    return function <T extends S>(val: T) {
        return val
    }
}

const b = createDef<{ a: 1, b: 2 }>()({
    a: 'hello',
    b: 'world',
    foo: 'bar'
})
```

### 🙁 Actual behavior

I created a function with 2 type parameters. The 2nd is referenced by the function's parameter.
When I use the function, I am asked to provide all the 2 type arguments.
But I think the 2nd is unnecessary, because it can be Inferred by the function's argument.
If there is only 1 type parameter in the function's definition, there is no problem.
So I have to wrap the function in another one as a walkaround.

### 🙂 Expected behavior

Make the type parameters which appear in function parameters optional.

**Comment by MartinJohns** [comment] 2021-09-20 06:55
Duplicate of #26242 / #26349.

**Closed** 2021-09-26 18:00 UTC
Labels: Duplicate
