### ISSUE TITLE
Duplicate error messages with Visual Studio 2015 and TS2.0

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#9633] opened 2016-07-12 08:54 UTC
VS2015 with TS2.0 shows duplicate error messages when typescript is installed in global by npm (`npm i -g typescript@beta`). These duplicate errors are shown after type checks for unopened files.

**TypeScript Version:**  2.0

**Comment by mhegazy** [comment] 2016-07-13 01:25
Can you share more details on how to reproduce this?

**Comment by falsandtru** [comment] 2016-07-13 01:50
How to:

0. Add invalid code such as `var a;` in TypeScript project.
0. Unload the project.
0. Run `$ npm i -g typescript@2.0.0`.
0. Reload the project.
0. Wait a few minutes (don't open any files).
0. Duplicate errors are shown in the error list automatically.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	TS6133	'a' is declared but never used.	localsocket	
Error	TS7005	Variable 'a' implicitly has an 'any' type.	localsocket	
Error	TS6133	'a' is declared but never used.	localsocket	
Error	TS7005	Variable 'a' implicitly has an 'any' type.	localsocket	
```

Can you repro?

**Comment by falsandtru** [comment] 2016-07-13 02:11
Changed "reload project" to "restart vs".

**Comment by mhegazy** [comment] 2016-07-13 02:57
i see it now. thanks.

**Comment by paulvanbrenk** [comment] 2016-07-13 21:34
I can repro this without installing TypeScript from npm, or reloading the project... however this seems to be an issue with some VS infrastructure, and not TypeScript specific. Looking for the right team to take a look here.

**Comment by RyanCavanaugh** [comment] 2020-07-21 21:51
Assuming this has been fixed by now...

**Closed by RyanCavanaugh** 2020-07-21 21:51 UTC
Labels: Bug
