### ISSUE TITLE
Const strings don't narrow their `length` property

### ISSUE THREAD

**Issue by bbrk24** [microsoft/TypeScript#55338] opened 2023-08-11 18:39 UTC
### 🔎 Search Terms

const string length

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about const strings

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgJwTAvDA2gcjpgNDTAIzwOEwF14IZRIoBuAKFuhmmTW0LKpvGibN+sRAgAyAUzCp4SAHQAbKQHMoACyYB6TTF0wAegH4hdNlHFSZ7RSvVadeo4yA

### 💻 Code

```ts
const arr = ['a', 'b', 'c'] as const;
const str = 'abc' as const;

const arrLen = arr.length;
//    ^? const arrLen: 3
const strLen = str.length;
//    ^? const strLen: number
```

### 🙁 Actual behavior

The `length` property of the constant string is of type `number`

### 🙂 Expected behavior

The `length` property of the constant string should be `3`, like it is for the constant array.

**Comment by fatcerberus** [comment] 2023-08-11 18:55
Looks like a duplicate of https://github.com/microsoft/TypeScript/issues/34692.  Related issue: https://github.com/microsoft/TypeScript/issues/41037

**Closed** 2023-08-14 01:24 UTC
Labels: Duplicate
