### ISSUE TITLE
Narrowing down the type of a parameter isn't recognized in closure

### ISSUE THREAD

**Issue by jmankopf** [microsoft/TypeScript#34669] opened 2019-10-23 10:47 UTC
**TypeScript Version:**  v3.7-Beta 

**Search terms :** narrow narrowing down type parameter closure

**Code**
```ts
function foo(arg: string | undefined) {
    arg = arg ?? "default";

    arg.length // no error
    const bar = () => {
        arg.length; // error 
    }
}

```

**Expected behavior:**
arg should be of type string within the body of the closure.

**Actual behavior:**
arg is possibly 'undefined' within the body of the closure.

**Playground Link:** [Playground link](http://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=1&ssc=28&pln=1&pc=37#code/GYVwdgxgLglg9mABMOcAUBDATgcwFyIDOUWMYOiAPouACYCmwZ9tAlIgN4CwAUIv4mwUAvINxVqAIgbAMIADZRJAbl68BYnADp59clAAWiAPTHEYOInpYscLOoEQExRACNsiUWnbCAfJwcNfiEdPRxDZRMza1ssREDEAF9eZJ4gA)

**Comment by MartinJohns** [comment] 2019-10-23 12:30
Duplicate of #9998.

**Comment by fatcerberus** [comment] 2019-10-24 02:49
*Is* this actually a duplicate of #9998?  That's a design limitation wherein narrowings are optimistically *not* reset when calling a function because it would be impractical to follow the control flow into the call.  Here, the narrowing *is* being reset at a closure boundary, which is normal (i.e. not just a design limitation - it's deliberate).

**Closed** 2019-10-24 16:56 UTC

**Comment by Buntelrus** [comment] 2020-11-20 09:01
What's the conclusion of this?

**Comment by MartinJohns** [comment] 2020-11-20 09:03
The conclusion is that it's a duplicate of #9998.

**Comment by Buntelrus** [comment] 2020-11-20 09:23
I don't get it. What can I do to solve this problem?
