### ISSUE TITLE
language service response documentation file path (QuickInfo、CompletionEntryDetails、SignatureHelp)

### ISSUE THREAD

**Issue by DingWeizhe** [microsoft/TypeScript#50665] opened 2022-09-07 00:43 UTC
# Suggestion

in vscode IntelliSense will rendered markdown documents, but now the base URI is file being editing.
but should be relative to defining file.

So we need to add a file field to any response with documentation to render the markdown link / image correctly

vscode issues https://github.com/microsoft/vscode/issues/160018

## 🔍 Search Terms
QuickInfo、CompletionEntryDetails、SignatureHelp

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

response documentation file path. when commands QuickInfo、CompletionEntryDetails、SignatureHelp.

## 💻 Use Cases

Improve vscode typescript documentation rendering correctness

**Comment by andrewbranch** [comment] 2022-09-09 23:22
Duplicate of #47718

**Closed** 2022-09-12 18:00 UTC
Labels: Duplicate
