### ISSUE TITLE
Folding does not return all ranges in file with large chained method

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#25782] opened 2018-07-18 22:59 UTC
From https://github.com/Microsoft/vscode/issues/53766

**TypeScript Version:**  3.1.0-dev.20180713

**Search Terms:**
- Folding
- Outliningspans

**Code**

open [this file](https://github.com/Microsoft/vscode/files/2194553/test.zip) and request folding rabge

**Bug:**
Folding ranges are only returned after line 3800 or so

**Comment by mhegazy** [comment] 2018-07-18 23:02
@uniqueiniquity can you take a look

**Comment by Davilink** [comment] 2018-07-19 14:13
I have the same issues with a huge gulpfile (699 lines). Some code cannot be unfold, closing/re-opening the file doesn't correct the problem, i have to restart VSCode.

missing the "+" action to unfold
![image](https://user-images.githubusercontent.com/1498932/42947887-5731543a-8b3c-11e8-8286-643944a1b5f9.png)

**Comment by uniqueiniquity** [comment] 2018-07-19 20:49
@mjbvz, the original issue is explained by https://github.com/Microsoft/TypeScript/issues/25596#issuecomment-404577953; we stop looking for folding ranges at a certain AST depth due to perf reasons.

@Davilink, could you share your gulpfile or a similar repro? From the picture, it doesn't look like the same issue, since the original issue is caused by repeatedly chaining method calls.

**Comment by Davilink** [comment] 2018-07-19 23:20
Because the problem is solved when a restart VSCode, it's might be due to larger workspace + the larger gulpfile. I will open an separate issue to track that problem.

**Comment by uniqueiniquity** [comment] 2018-12-31 22:49
Closing due to addressing the original issue with https://github.com/Microsoft/TypeScript/issues/25596#issuecomment-404577953

**Closed by uniqueiniquity** 2018-12-31 22:49 UTC
Labels: Bug, Domain: Outlining
