### ISSUE TITLE
Wrong typecheck in for..in for dictionary|array with strict true

### ISSUE THREAD

**Issue by saithis** [microsoft/TypeScript#32552] opened 2019-07-25 14:23 UTC
**TypeScript Version:**  3.4.3

**Search Terms:** wrong typecheck indexer for..in dictionary array strict implicitly any

**Code**

```ts
class Arr {
  public data: string[] = [];
}

class Dict {
  public data: {[key: string]: string } = {}
}

function test(obj: Arr | Dict){
  // Works
  if(obj instanceof Arr){
    for (const controlName in obj.data) {
      if (obj.data[controlName]) {
      }
    }
  }
  // Works
  if(obj instanceof Dict){
    for (const controlName in obj.data) {
      if (obj.data[controlName]) {
      }
    }
  }
  // Error
  if(obj instanceof Dict || obj instanceof Arr){
    for (const controlName in obj.data) {
      if (obj.data[controlName]) { // <-- here
        // Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'string[] | { [key: string]: string; }'.
        // No index signature with a parameter of type 'string' was found on type 'string[] | { [key: string]: string; }'
      }
    }
  }
  // Error
  for (const controlName in obj.data) {
    if (obj.data[controlName]) { // <-- here
      // Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'string[] | { [key: string]: string; }'.
      // No index signature with a parameter of type 'string' was found on type 'string[] | { [key: string]: string; }'
    }
  }
}
```

**Expected behavior:**
No error

**Actual behavior:**
Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'string[] | { [key: string]: string; }'.
No index signature with a parameter of type 'string' was found on type 'string[] | { [key: string]: string; }'

**Playground Link:** https://www.typescriptlang.org/play/#code/FAYwNghgzlAECCAnRsDexawA4FcBGYAliLACYQAuEAXLFBYoQHYDmA2gLqwC8snA3MAC+wUJBiwAIsQpoM2fERLkqtVGwDWAUwCeteo1Yd9DZi1hCeaESOAAzHExAVCAeyawKW+gApXeACtaJBQAHykZAEp0TAB6WNgAdVdEDSh5Qjs-QNhmeggnLVc7BGRo+Uw7FNgfEHd6WDqmBlcwADkIAFstXI9-AIA6FQhIuUxx3JLsweG2Jpb2rq0OUZiJiwqNzBE4hOTU9MxM6d78wuKI53KJqpRa+tl5xFaO7t7YfqHKEbH1zJrPrMni8litfhMduNIZD4rAAKLIFIZLL9U5Uc4laTOWChcKovLokBFEoha7jW41JoNYGLN7MD6BL5UVabI5TQHfObuBavZarWCwgA8AFphbAABZaRBaVnjWFwsBabrNXKdLBKQgUMA6CXQWAFWAAcgKOkNnh0WB6eC0IAgOCgPS0AA8sNKYG4+iUKBaeoaDGYzbamIbZNbYPatKRPK5eqRnebLUb-axODi0HxtHo6KYjCZDCx+BZDQNZbtYG0Y8w4066IQWExKDhpbAAO6a8X67AQRBLLwoC7exN+nMsM0tvVVRxR9wJ33J9hccKoDO6PNmYzZ-OFoSG2WQ7byGEJBHPRDyCn3JjU7nPWk9ekc5ngyYAxlAm8g7pg5dC0USqUyusArHoqyqyIQaoalqOrinqBrGkwpqzrA1q2hGsDOq63hQB6Hxej6SYjoGBQhihPQRlGFCVkw1bIcO+apkuK5ZvOG7ztuxayrCFaxvGOH1o2zZthQHYQF2PbdH2eF0fOY4Tq4U4fB4g5ziOjHppoq6buua6sBxmzQsIQA

**Related Issues:** didn't find any

**Comment by jcalz** [comment] 2019-07-25 15:46
Duplicate of #6346 and perhaps related to #12314

**Comment by saithis** [comment] 2019-07-26 10:10
What confused me is, that indexer signature on its own is ok and array on its own is ok, but if the type is either of the two, then it isn't. After reading #6346 it would als be ok for me if for..in wouldn't work with arrays, but it should be consistent. Also maybe a better error message explaining why array with for..in is not ok.

**Closed** 2019-07-28 18:00 UTC
Labels: Duplicate
