### ISSUE TITLE
Non-void class decorators don't replace type of reference

### ISSUE THREAD

**Issue by Sheeo** [Microsoft/TypeScript#13988] opened 2017-02-09 23:48 UTC
Using the newly unrestricted `extends` clause in combination with decorators allows for "proper" mixins alà what #4881 wants, but currently the return value of class decorators does not replace the definition, even though this is the runtime behavior.

**TypeScript Version:**  2.2.0 (RC)

**Code**

```ts
type Constructable = new (...args: any[]) => Object;

function snafucate<T extends Constructable>(Base: T) {
    return class Foo extends Base {
        foo() {
            return "bar";
        }
    }
}

@snafucate
class Bar {
}

let x = new Bar();
x.foo();

// Example code mirroring what actually happens at runtime gets typed correctly:
const Baz = snafucate(class {
    bazz() {
        return "bazz";
    }
});

let y = new Baz();
y.bazz();
y.foo();
```

**Expected behavior:**

No compile time errors

**Actual behavior:**

```
tsc --experimentalDecorators test.ts
test.ts(16,3): error TS2339: Property 'foo' does not exist on type 'Bar'.
```

**Comment by mhegazy** [comment] 2017-02-10 00:13
Duplicate of https://github.com/Microsoft/TypeScript/issues/4881

**Closed** 2017-04-21 16:55 UTC
Labels: Duplicate
