### ISSUE TITLE
type inference after typeof expected

### ISSUE THREAD

**Issue by FalkNisius** [microsoft/TypeScript#47437] opened 2022-01-14 08:10 UTC
# Bug Report

Conditions with typeof operator for object properties works only for direct access, not for indexed access, even the index can't be changed. 

```ts
a.b
a['b']
index = 'b'
a[index]
```

The lines 1, 2 and 4 should be handled in the same way.

### 🔎 Search Terms

infer types

### 🕗 Version & Regression Information

Typescript 4.5.4
TypeScript 4.6.0 nighlty

- This is the behavior in some version I tried, and I reviewed the FAQ for entries about typeof

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.5.4#code/FASwdgLgpgTgZgQwMZQAQAUEwM5QCYCK2qA3qgNoDWUAngFyrYQzgDmAugwK5h5Rzh8qAD6NmbEWJZhW5dpMw58RBVlyFsc1AF9gwADZQIqAI5dY9RepUBeUgP3QYDAOQIARkhcAaVEgD2PMz0qC5QYC66wHA8SBAg-mCoUAAezMgQAGoI+uaoABRmFgxWyti+AlD6eAxM0qwAlLXiMqTAqB2oIHAFEDQADlD+PUUwNOSV1fI2M6F1bC4NbZ0rqDBGXDBJo+OTeOwAdOv9+shQ+QD0+QB6ADrYANTC9w8AJA0XrL4ui+2d2sl9LhlqsOusIJskj8-h1dFEYmA4gkkql0nEAGIgRywAo7EpqMpNKQSEgwro9fJ9QbDUzmMYHBxOVAzOwueYyRYg0HgyG0iwMrFOI5QE5nS43F7PR7vT7fX6g2GA4GkhWrHlbUIuMkrOF6BFIxLJNIwDKY7EwABMuLpIVKGiJ7NYXPJvQGQxGNvILkZsBc01mbJarE5KoV6u2nu9gt9h2OpxQ4rujylbw+X01DW1-yVaFDqrBGw10NVur+QA

### 💻 Code

```ts

interface ParsedQs { [key: string]: undefined | string | string[] | ParsedQs | ParsedQs[] }

let query:ParsedQs = {filter: 'abc', country: 'en'}

function extractValue (query: ParsedQs, field: string): string {
    if (typeof query[field] === 'string') {
        return query[field].replace(/(^\s+|\s+$)/g, '')
    } else {
        return ''
    }
}

function extractFilter (query: ParsedQs): string {
    if (typeof query.filter === 'string') {
        return query.filter.replace(/(^\s+|\s+$)/g, '')
        } else {
            return ''
        }
}

function extractFilter2 (query: ParsedQs): string {
    if (typeof query['filter'] === 'string') {
        return query['filter'].replace(/(^\s+|\s+$)/g, '')
        } else {
            return ''
        }
}

  
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
let query = { filter: 'abc', country: 'en' };
function extractValue(query, field) {
    if (typeof query[field] === 'string') {
        return query[field].replace(/(^\s+|\s+$)/g, '');
    }
    else {
        return '';
    }
}
function extractFilter(query) {
    if (typeof query.filter === 'string') {
        return query.filter.replace(/(^\s+|\s+$)/g, '');
    }
    else {
        return '';
    }
}
function extractFilter2(query) {
    if (typeof query['filter'] === 'string') {
        return query['filter'].replace(/(^\s+|\s+$)/g, '');
    }
    else {
        return '';
    }
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

      

### 🙁 Actual behavior

The evaluated type of an expression is forgot in the first then statement. 
There is a different between ```typeof a[b]```ans ```typeof a.b``` independend of the value of b 

### 🙂 Expected behavior

The evaluated type of an expression should be recognized in the then part.
There should not be a different between directly accessed properties or  indexed properties.

**Comment by MartinJohns** [comment] 2022-01-14 08:12
Duplicate of #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.

Simple workaround: Store it in a local variable.

**Comment by fatcerberus** [comment] 2022-01-14 09:16
Duplicate of #46560, which in turn is a duplicate of #10530.

**Closed** 2022-01-16 18:00 UTC
Labels: Duplicate
