### ISSUE TITLE
Some JavaScript syntax error only shown in TypeScript files

### ISSUE THREAD

**Issue by billti** [Microsoft/TypeScript#23835] opened 2018-05-02 20:59 UTC
Given the below code

```js
function foo(){
    var x = "test";
    break;
}
```

TypeScript files will return an error on the "break" statement, but JavaScript files will not.

According to the ES5 spec (http://es5.github.io/#x12.8)

> A program is considered syntactically incorrect if either of the following is true...
>  - The program contains a break statement without the optional Identifier, which is not nested, directly or indirectly (but not crossing function boundaries), within an IterationStatement or a SwitchStatement

Looks like this was fixed for TypeScript in https://github.com/Microsoft/TypeScript/issues/57 . We should give the same syntax errors in JavaScript files.

**Comment by mhegazy** [comment] 2018-05-03 17:34
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/6107.

The issue here is we report these errors are part of the grammar check, which is done during checking and not during binding. so you get the errors only if you ran a check on the file (either .ts or a ,js with `// @ts-check`). 

To enable this we will need an extra walk over the tree to check the nodes. one option is to this in the binder.

**Closed** 2018-05-18 19:46 UTC
Labels: Duplicate
