### ISSUE TITLE
error TS2688: Cannot find type definition file for...random paths.

### ISSUE THREAD

**Issue by atrauzzi** [microsoft/TypeScript#27956] opened 2018-10-18 00:05 UTC
Using https://github.com/atrauzzi/gerty on the branch `hashi-gerty`.  

Basically anything that tries to do typescript gets a bunch of errors about not finding type definitions I never reference in any of my source files.

(For the simplest example, I do a `yarn install` and then `./node_modules/.bin/ts-node`.)

```
PS C:\Users\atrauzzi\Development\atrauzzi\gerty> .\node_modules\.bin\ts-node
> console.log('hi');
error TS2688: Cannot find type definition file for '.github'.
error TS2688: Cannot find type definition file for 'build'.
error TS2688: Cannot find type definition file for 'examples'.
error TS2688: Cannot find type definition file for 'scripts'.
error TS2688: Cannot find type definition file for 'src'.
error TS2688: Cannot find type definition file for 'website'.

undefined
>
```

Apologies, I have searched for this, but wasn't able to find anything relevant or within the last few months.

What is happening and why am I getting these weird errors?  Is there any way they can be improved if it is in fact something that I've done wrong?

**Comment by mattmccutchen** [comment] 2018-10-18 02:00
These errors occur when you have subdirectories of a `typeRoots` directory (in this case `node_modules/@types`) that do not contain `index.d.ts` files.  I agree the error message is mysterious and should be improved.

In your case, the errors occur because your `package.json` [specifies a package named `@types/`](https://github.com/atrauzzi/gerty/blob/06204a3c1748cbde9527de9f3d03d89619bdfe27/package.json#L18), which is a silly thing to do.

**Comment by atrauzzi** [comment] 2018-10-18 11:21
Aha!  Doh!

My apologies, clearly that's a yarn add gone wrong. Yes, very silly indeed.

Feel free to use my blunder-ticket to track improving any feedback 😉

**Comment by atrauzzi** [comment] 2018-10-18 16:49
In my situation, how was the directory `@types` being inferred?  Does TS read `package.json` for hints?

**Comment by mattmccutchen** [comment] 2018-10-18 16:54
TypeScript looks in `node_modules/@types` by default since this is where types packages from DefinitelyTyped containing global declarations (such as [`@types/node`](https://www.npmjs.com/package/@types/node), to give one popular example) are normally installed.  See [the documentation](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types).

**Comment by atrauzzi** [comment] 2018-10-18 17:42
So how does that connect back to there being a bad `@types/` entry in my `package.json`?

**Comment by mattmccutchen** [comment] 2018-10-18 19:19
The entry `"@types/": "reach/router"` caused https://github.com/reach/router to be downloaded directly into the `node_modules/@types` folder, creating new files and subdirectories unrecognized by the TypeScript compiler alongside the existing valid subdirectories.  I'm guessing you ran `yarn add @types/@reach/router`, trying to install the `@types` package for the scoped package `@reach/router`, but that command is actually parsed as installing a package named `@types/` at version `reach/router`.  You probably meant [`@types/reach__router`](https://www.npmjs.com/package/@types/reach__router): that's the naming convention for `@types` packages for scoped packages.  Consider filing a bug against Yarn for letting you install a package with the invalid name `@types/`.  (I notice that NPM correctly catches this.)

**Comment by atrauzzi** [comment] 2018-10-18 19:36
Aha!  Gotcha.  After reading your error messages, I wasn't so sure they'd have helped me figure out what was going on either.  So, I was trying to think if there's any way to highlight not necessarily the source of my error, but better information about the symptom.

**Comment by Finesse** [comment] 2019-07-08 10:59
I got this problem too and my case is different. My project has the following file structure:

```
├ frontend
│  ├ node_modules/
│  ├ tsconfig.json
│  └ index.ts
└ backend
```

The frontend working directory is `frontend`, it has the `node_modules` directory inside and all the commands are run from this directory. I accidentally ran `npm install something` while being in the root directory so an excess `node_modules` directory appeared:

```
├ frontend
│  ├ node_modules/
│  ├ tsconfig.json
│  └ index.ts
├ node_modules/
└ backend
```

And then when I ran `cd frontend && tsc --noEmit` I got the `TS2688` error.

I fixed the error by deleting the `node_modules` directory from the project root.

**Comment by jasperkuperus** [comment] 2019-09-21 18:54
Exact same thing happened to me as @mattmccutchen describes. Also ran `yarn add @types/@scoped/package`, and suddenly you have `@types/` as dependency and these weird errors. Would be nice if we get a more descriptive error.

**Comment by Sesna** [comment] 2019-09-29 04:11
this helps me alot, thx. 

> These errors occur when you have subdirectories of a `typeRoots` directory (in this case `node_modules/@types`) that do not contain `index.d.ts` files. I agree the error message is mysterious and should be improved.
> 
> In your case, the errors occur because your `package.json` [specifies a package named `@types/`](https://github.com/atrauzzi/gerty/blob/06204a3c1748cbde9527de9f3d03d89619bdfe27/package.json#L18), which is a silly thing to do.

it help me a lot, thank you.

**Comment by loopmode** [comment] 2019-09-30 12:29
> These errors occur when you have subdirectories of a `typeRoots` directory (in this case `node_modules/@types`) that do not contain `index.d.ts` files. I agree the error message is mysterious and should be improved.
> 
> In your case, the errors occur because your `package.json` [specifies a package named `@types/`](https://github.com/atrauzzi/gerty/blob/06204a3c1748cbde9527de9f3d03d89619bdfe27/package.json#L18), which is a silly thing to do.

So.. what's the best strategy to tackle the need for `index.d.ts`? I currently keep an empty `index.d.ts`, with just a link to this issue as a comment. Next to it, I keep a bunch of smaller d.ts files.

I am not really happy with the empty index file strategy, but it seems to help - otherwise I simply can't have a bunch of smaller d.ts files in my project's `types/` folder and TS2688 bites me..

**Comment by Texas-Analyst** [comment] 2019-12-04 21:06
Within the Typescript documentation with the section on compiler options 'types', it worked for me
to create the types: ["anymatch". "lodash", ......] compiler option in tsconfig.json to eliminate this error. I am using Visual Studio code. As you know this may or may not work for you.
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by Texas-Analyst** [comment] 2019-12-04 21:10
This is what I used that appears to remedy this type of error for me.
If types is specified, only packages listed will be included. For instance:
{
   "compilerOptions": {
       "types" : ["node", "lodash", "express"]
   }
}
This tsconfig.json file will only include ./node_modules/@types/node, ./node_modules/@types/lodash and ./node_modules/@types/express. Other packages under node_modules/@types/* will not be included.
A types package is a folder with a file called index.d.ts or a folder with a package.json that has a types field.

**Comment by Gfast2** [comment] 2020-01-08 11:18
Sorry for having time read through all comments here.
I think this error just indicated you: 
> "if you config tsc to do the job in this way, you need to install the missing type definitions for the modules that tsc indicate. For Example, in my scenario, tsc told me I'm missing type definition for "node", then I solve it by yarn add -D @types/node`. :cheese:

**Comment by Texas-Analyst** [comment] 2020-03-12 01:57
Ok. Thanks for your feedback. If you solved your problem, then why are you
telling me?
Why not just published it as a check that developers need to ascertain and
forget it?

**Comment by thorsent** [comment] 2020-07-15 19:27
This should probably be a warning rather than an error. A missing typedef is equivalent to an empty typedef, which isn't an error condition.

**Comment by makuzaverite** [comment] 2020-09-30 08:58
I have fixed this by adding ` "baseUrl": "." ` in my `tsconfig.json` file

**Comment by neokamikai** [comment] 2020-10-10 15:18
i have the same error but on jsconfig.json file, for no aparent reason, i don't use babel or any other transpiler on my project, because its a very simple static website, and this is what i have on my jsconfig file, and it's reporting an "unexpected" error, i don't use babel, or any other transpiler, how can i get rid of this error? or is this a bug?

![image](https://user-images.githubusercontent.com/4462017/95658601-0825f200-0af2-11eb-9a1b-0777e58ff35f.png)

**Comment by iloseall** [comment] 2020-10-12 07:47
when I use tsc --project ./
I got 
```
error TS2688: Cannot find type definition file for 'cacheable-request'.

error TS2688: Cannot find type definition file for 'eslint'.

error TS2688: Cannot find type definition file for 'eslint-scope'.

```

**Comment by stoplion** [comment] 2020-10-21 03:28
Same error, I have a tsconfig in a Cypress folder and one in root.

**Comment by blurk** [comment] 2020-10-24 14:08
I have this error today! But the code still got compiled to js 😶[error image](https://i.imgur.com/m26YsNi.png)

**Comment by thebiltheory** [comment] 2020-12-07 10:57
> 
> 
> This is what I used that appears to remedy this type of error for me.
> If types is specified, only packages listed will be included. For instance:
> {
> "compilerOptions": {
> "types" : ["node", "lodash", "express"]
> }
> }
> This tsconfig.json file will only include ./node_modules/@types/node, ./node_modules/@types/lodash and ./node_modules/@types/express. Other packages under node_modules/@types/* will not be included.
> A types package is a folder with a file called index.d.ts or a folder with a package.json that has a types field.

Does that mean you have to add each `@types/<package>` manually to your `tsconfig` ?

**Comment by dagatsoin** [comment] 2020-12-08 09:19
I reached the same situation, where I need to add a root to look into for declaration file (typing a cordova plugin and need global access)

![image](https://user-images.githubusercontent.com/3670794/101464376-d76e0780-393e-11eb-855f-25b3a24776bd.png)

**Comment by linonetwo** [comment] 2021-02-23 08:39
This is still a problem, I get `Cannot find type definition file for 'node_modules'.`

I have 

1. `"typeRoots": [  "./node_modules/@types",`
2. `"baseUrl": ".",`
3. `"moduleResolution": "node",`
4. and my node_modules is just located at project root, no additional node_modules added.

So basically I tried all methods above, nothing works. And this error message is still a cypher in 2021.

**Comment by amelieykw** [comment] 2021-03-02 01:10
I met the same problem ('cannot find the definition file for "babel__core"') as you guys, but I googled it and I found the solution which works for me. [编译typescript出现 Cannot find type definition file for ‘babel__core‘](https://blog.csdn.net/weixin_43342105/article/details/107952323)

For those who cannot read Chinese, the solution is :

1. **option 1**: add `"skipLibCheck": true, ` in `"compilerOptions"` in your tsconfig.json
```json
{
  "compilerOptions": {
     "skipLibCheck": true,                     /* Skip type checking of declaration files. */
  }
}
```
2. **option 2**: add `typeRoots ` in `"compilerOptions"` in your tsconfig.json
```json
{
  "compilerOptions": {
    "typeRoots": [
      "node_modules/@types",
      "src/typings"
    ]
  }
}
```
In my case, originally I had `"skipLibCheck": true,` when I met this problem, so this time, I add `"typeRoots"`  which solved my problem.

**Comment by linonetwo** [comment] 2021-03-02 08:51
@amelieykw Hi I solve this by an upgrade to the latest ts-node.

**Comment by amelieykw** [comment] 2021-03-02 09:01
> @amelieykw Hi I solve this by an upgrade to the latest ts-node.

Congratulations! However, I don't think that the problems that we met were same. In my case, the problem was 'cannot find the definition file for "babel__core"' in app created by create-react-app.

**Comment by yugakiran** [comment] 2021-04-09 23:26
I had the simillar issue and I was able to reslove by adding package.json "@types/systemjs": "~version" in devDependencies

**Comment by oneal1801** [comment] 2021-04-26 14:06
> I met the same problem ('cannot find the definition file for "babel__core"') as you guys, but I googled it and I found the solution which works for me. [编译typescript出现 Cannot find type definition file for ‘babel__core‘](https://blog.csdn.net/weixin_43342105/article/details/107952323)
> 
> For those who cannot read Chinese, the solution is :
> 
> 1. **option 1**: add `"skipLibCheck": true, ` in `"compilerOptions"` in your tsconfig.json
> 
> ```json
> {
>   "compilerOptions": {
>      "skipLibCheck": true,                     /* Skip type checking of declaration files. */
>   }
> }
> ```
> 
> 1. **option 2**: add `typeRoots ` in `"compilerOptions"` in your tsconfig.json
> 
> ```json
> {
>   "compilerOptions": {
>     "typeRoots": [
>       "node_modules/@types",
>       "src/typings"
>     ]
>   }
> }
> ```
> 
> In my case, originally I had `"skipLibCheck": true,` when I met this problem, so this time, I add `"typeRoots"` which solved my problem.

it worked for me thank you!

**Comment by ImAbhishekTomar** [comment] 2021-06-19 20:26
### Anyone find solution for this?

> ERROR : Cannot find type definition file for 'android'. The file is in the program because: Entry point for implicit type library 'android'

```
{
	"resource": "/Users/jack/Desktop/root/projects/svg-editor/tsconfig.json",
	"owner": "typescript",
	"severity": 8,
	"message": "Cannot find type definition file for 'android'.\n  The file is in the program because:\n    Entry point for implicit type library 'android'",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}
```

![Screenshot 2021-06-20 at 1 54 02 AM](https://user-images.githubusercontent.com/6933841/122654630-6f5c7180-d16a-11eb-8e8d-b8ffb23e4f8d.png)

**Comment by nicktaras** [comment] 2021-09-28 03:11
I'm working on an open source project where I knew that the project could be installed and used (many people working on the same source). However I came across the following error when running the project on my machine:

This being a package that this project does not use.

 ERROR
      TS2688: Cannot find type definition file for 'express-serve-static-core'.
  The file is in the program because:
      Entry point for implicit type library 'express-serve-static-core'

After trying a few solutions - It was possible fix the problem by updating the ts config as explained above. 
However the actual fix applied was to delete my system node_modules folder which within this folder was the root cause. I hope this helps if you are in a similar situation.

**Comment by TaimoorMalik-Sunny** [comment] 2021-10-06 06:22
![solution](https://user-images.githubusercontent.com/66994297/136150702-21de82ba-3279-4810-9286-a019baff852a.jpeg)

Run this : npm install @types/node --save-dev

and in tsconfig file add :    
  {
      "compilerOptions": {
        "types": ["node"]
      }
    }

**Comment by THammami01** [comment] 2022-02-01 03:09
This is probably because it is installed using this syntax: `@types/@chec/commerce.js`
The correct one is: `@types/chec__commerce.js`

**Comment by gpspelle** [comment] 2022-04-30 17:17
In my case the problem was due to the fact that I moved the directory containing the npm project.

A `npm i` solved it.

**Comment by CaliforniaMountainSnake** [comment] 2022-05-12 20:19
For 2022 readers:
Configure TypeScript for handling webpack's [asset/source](https://webpack.js.org/guides/asset-modules/#source-assets):

By default you will get error: `Cannot find module 'your_module?raw' or its corresponding type declarations.`
To avoid it, create the file `asset_source_loader.d.ts` (Not required to add anything into the `tsconfig.json`)
```typescript
declare module "*?raw" {
    const content: string;
    export default content;
}
```

Example of the webpack configuration:
```webpack
{
    resourceQuery: /raw/,
    type: "asset/source",
}
```
(Don't forget to add `resourceQuery: {not: [/raw/]}` to every loader if you'd like to exclude raw assets from being processed by other loaders. Read the [documentation](https://webpack.js.org/guides/asset-modules/#source-assets))

And then you can load modules into the variables:
```typescript
import txt from "some_style.min.css?raw";
console.log("LOADED TXT:", txt);
```

**Comment by mosesoak** [comment] 2022-08-18 19:50
I had a similar problem in a project where a library added native types, fixed by removing its @types/ lib.

In my case the library was yup, so removing @types/yup fixed the error.

Typescript authors: the error message is not helpful. It would be nice to detect overlapping types and give an error about a conflict, perhaps like "Try removing the @types library if one is installed". 👍

**Comment by JamesBarrettDev** [comment] 2022-09-13 14:08
> I had a similar problem in a project where a library added native types, fixed by removing its @types/ lib.
> 
> 
> 
> In my case the library was yup, so removing @types/yup fixed the error.
> 
> 
> 
> Typescript authors: the error message is not helpful. It would be nice to detect overlapping types and give an error about a conflict, perhaps like "Try removing the @types library if one is installed". 👍 

Thanks! Had the same problem with `@types/yup` this worked. 😃

**Comment by timmeade** [comment] 2022-09-18 15:26
JUST FYI for Everyone:

I found this thread reading having this same issues.  But in mine i had removed the library and @type file as no longer needed.  I was still getting this error.

Restarting VSCODE and it went away

**Comment by AliRadmanesh** [comment] 2022-10-13 07:29
> I had a similar problem in a project where a library added native types, fixed by removing its @types/ lib.
> 
> In my case the library was yup, so removing @types/yup fixed the error.
> 
> Typescript authors: the error message is not helpful. It would be nice to detect overlapping types and give an error about a conflict, perhaps like "Try removing the @types library if one is installed". 👍

As @mosesoak said, it's because you have types for packages that you don't even use in `@types` folder.

So first of all try to remove those packages or try removing `node_modules` and `yarn.lock` and reinstall your packages.

If that doesn't help, go for other options like `typeRoots` in `tsconfig.json`.

**Comment by JRasmusBm** [comment] 2022-10-27 13:33
This is what worked for me: https://github.com/microsoft/TypeScript/issues/27956#issuecomment-509179806

The rogue node_modules folder was in the great-grandparent directory. Took me just about 2 hours to figure out :cry: :rofl:

**Comment by thorsent** [comment] 2022-11-03 21:01
Missing index.d.ts unnecessarily broke a chunk of the internet:
https://github.com/jaredwray/keyv/issues/528

"This should be a _warning_", he says again 2 years later.

**Comment by AijazAsif** [comment] 2022-12-31 07:59
> This is what I used that appears to remedy this type of error for me. If types is specified, only packages listed will be included. For instance: { "compilerOptions": { "types" : ["node", "lodash", "express"] } } This tsconfig.json file will only include ./node_modules/@types/node, ./node_modules/@types/lodash and ./node_modules/@types/express. Other packages under node_modules/@types/* will not be included. A types package is a folder with a file called index.d.ts or a folder with a package.json that has a types field.

Thank you

**Comment by TechStudent10** [comment] 2023-01-15 20:39
> I met the same problem ('cannot find the definition file for "babel__core"') as you guys, but I googled it and I found the solution which works for me. [编译typescript出现 Cannot find type definition file for ‘babel__core‘](https://blog.csdn.net/weixin_43342105/article/details/107952323)
> 
> For those who cannot read Chinese, the solution is :
> 
> 1. **option 1**: add `"skipLibCheck": true, ` in `"compilerOptions"` in your tsconfig.json
> 
> ```json
> {
>   "compilerOptions": {
>      "skipLibCheck": true,                     /* Skip type checking of declaration files. */
>   }
> }
> ```
> 
> 2. **option 2**: add `typeRoots ` in `"compilerOptions"` in your tsconfig.json
> 
> ```json
> {
>   "compilerOptions": {
>     "typeRoots": [
>       "node_modules/@types",
>       "src/typings"
>     ]
>   }
> }
> ```
> 
> In my case, originally I had `"skipLibCheck": true,` when I met this problem, so this time, I add `"typeRoots"` which solved my problem.

This worked for me. Thank you!

**Comment by dayknlang** [comment] 2023-01-17 20:10
O mesmo erro aconteceu comigo, nisso ao ler esse fórum inclui a opção 2 do nosso amigo acima e deu super certo, obrigada!

Opção 2: adicionar typeRoots  em "compilerOptions" em seu tsconfig.json

{
  "compilerOptions": {
    "typeRoots": [
      "node_modules/@types",
      "src/typings"
    ]
  }
}

**Comment by cangSDARM** [comment] 2023-02-15 06:39
I don't know why this error comes up, can't there be no need for node_modules to be any by default? Does it have to have @types??why

**Comment by Sazzels** [comment] 2023-02-24 09:13
Initially I ran into the same problem. My `tsconfig.json` always showed me that "Cannot find type definition file for 'node'.".

![grafik](https://user-images.githubusercontent.com/20369031/221138633-9b7708cb-3ac2-400e-b3ac-cccb3d481fca.png)

However, if I thoroughly follow the instructions for "Nuxt 3 getting-started", the error clears up. 

I think the important part is `...enable Take Over Mode (recommended)`.

Found in here in [https://nuxt.com/docs/getting-started/installation#prerequisites](https://nuxt.com/docs/getting-started/installation#prerequisites)  which leads to [https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode)

After enabling `Take Over Mode` which requires also to restart the current worspace the error is resolved. 

![grafik](https://user-images.githubusercontent.com/20369031/221138875-914867ff-d229-4766-9556-a8270925de67.png)

**Comment by generalMashuka** [comment] 2023-04-17 09:12
```
rm -rf node_modules
rm package-lock.json
npm i
```


fixed my strapi `error TS2688`

**Comment by MalekSmida** [comment] 2023-04-19 09:38
This worked for me
https://stackoverflow.com/a/72759322/13987596

**Comment by lufercampos** [comment] 2023-06-15 13:18
> JUST FYI for Everyone:
> 
> I found this thread reading having this same issues. But in mine i had removed the library and @type file as no longer needed. I was still getting this error.
> 
> Restarting VSCODE and it went away

a VSCODE restarting fixed the errors...thank you.

**Comment by amandesai01** [comment] 2023-07-06 08:58
@houh60 damn. it worked for me too LOL! Sometimes modern problems required not-so-modern solutions.

**Comment by robinelvin** [comment] 2023-09-15 09:12
I get the following error which makes no sense to me:

```
error TS2688: Cannot find type definition file for 'testing-library__jest-dom'.
  The file is in the program because:
    Entry point for implicit type library 'testing-library__jest-dom'


Found 1 error.
```

I have a monorepo and this error is coming from compiling my "common" workspace which has no references to `@testing-library/jest-dom` although one of my other workspaces does. I cannot see any references in any TS or config files which would point to this library being required. Nor can I see any option in `tsc` which will tell me why it needs this definition.

**Closed** 2023-09-15 16:43 UTC
Labels: Bug, Domain: Error Messages
