### ISSUE TITLE
Runtime error for two classes in one ts file.

### ISSUE THREAD

**Issue by vlechenko** [Microsoft/TypeScript#8572] opened 2016-05-12 12:30 UTC
**TypeScript Version:** 

1.8.10

**Code**

```ts
export class BaseLayoutModel extends BaseModel {
    constructor(attributes?: any, options?: any) {
        super(attributes, options);
    }
}

export class BaseModel extends Backbone.Model {
    constructor(attributes?: any, options?: any) {
        super(attributes, options);
    }

    destroy(options?: Backbone.ModelDestroyOptions): any {
        const opts = _.extend({
            contentType: "application/json",
            dataType: "text"
        }, options || {});
        super.destroy(opts);
    }
}
```

**Expected behavior:**

**Actual behavior:** 
Runtime error. BaseModel  is undefined

**Comment by aleksey-bykov** [comment] 2016-05-12 12:42
in your code `BaseModel` is declared lexically after `BaseLayoutModel`

in the compiled code it means that `BaseModel` is used before being initialized

try swapping the declarations (`BaseModel` class should come first)

**Comment by vlechenko** [comment] 2016-05-12 12:46
I know about “why it failed”. But this code translated to JS without any errors.

**Comment by Arnavion** [comment] 2016-05-12 23:33
Duplicate of #4341 and #5207 which should be fixed by #4343

**Closed** 2016-05-12 23:43 UTC
