### ISSUE TITLE
Refactoring: Extract Type

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#24017] opened 2018-05-10 07:37 UTC
# Background

I hate offhandedly writing a type out in one location that I'll need to cut/paste later.

# Proposal

Given a selected type segment, provide the ability to extract that type into

* an interface if given a type literal or
* a type alias otherwise

in any scope where each captured type is available.

Optionally, a parameterized type alias can be made available in scopes where captured types are not available.

![extracttypealias](https://user-images.githubusercontent.com/972891/39857951-f2f1dc58-53e9-11e8-9762-1a6dc579de29.gif)

**Comment by Kingwl** [comment] 2018-05-10 07:42
👍 a useful feature

**Comment by mhegazy** [comment] 2018-05-10 16:16
Duplicate of https://github.com/Microsoft/TypeScript/issues/23869

**Comment by DanielRosenwasser** [comment] 2018-05-10 19:30
Mine is better.

**Comment by mhegazy** [comment] 2018-05-10 19:33
mine now has the GIF 😛

**Comment by DanielRosenwasser** [comment] 2018-05-11 00:01
Thief!

**Closed** 2018-05-11 00:01 UTC
Labels: Duplicate
