### ISSUE TITLE
tsconfig.json does not work with VS 2015

### ISSUE THREAD

**Issue by ReverseBlade** [Microsoft/TypeScript#3124] opened 2015-05-12 04:12 UTC
I am trying to give options to typescript namely trying tell how to load modules from VS. For new ASP.NET 5 templates this option simply not available, worse typescript 1.5 does not honor tsconfig.json either so what should I do ?

**Comment by CyrusNajmabadi** [comment] 2015-05-12 05:49
tsconfig.json files are not currently working in VS2015.  It's something @paulvanbrenk is working on.

**Comment by ReverseBlade** [comment] 2015-05-12 05:59
any work around for the time being. I need to specify modules to amd

**Comment by paulvanbrenk** [comment] 2015-05-12 19:02
No guaranteed workaround, you can try adding a TypeScriptModuleKind element to a propertygroup, with amd or commonjs specified.. not sure if that gets correctly communicated to the compiler.

**Comment by ReverseBlade** [comment] 2015-05-12 19:36
Thanks that seems to work.

**Comment by boxofnotgoodery** [comment] 2015-05-17 02:20
+1 for this to work in VS2015 RC

**Comment by paulvanbrenk** [comment] 2015-05-18 18:15
This will work in the final release of VS 2015.

**Comment by mhegazy** [comment] 2015-05-19 00:39
Updating the label to suggestion as this is not a bug level change; this does not change the plan of shipping this in the next public VS release.

**Comment by paulvanbrenk** [comment] 2015-05-20 21:10
Checked in the code to enable this scenario in VS 2015

**Closed by paulvanbrenk** 2015-05-20 21:10 UTC
Labels: Committed, Suggestion, Visual Studio

**Comment by afaayerhan** [comment] 2015-07-20 23:23
just got VS 2015 RTM now but the tsconfig is not working. and when you change module system it just does not work. it defaults to commonjs. and if you remove TypeScriptModuleKind it cannot compile without --module flag

**Comment by paulvanbrenk** [comment] 2015-07-20 23:27
What kind of project are you using? For VS 2015 RTM only ASP.NET v5 and Cordova Projects are supported.

**Comment by afaayerhan** [comment] 2015-07-20 23:32
njsproj

**Comment by paulvanbrenk** [comment] 2015-07-20 23:35
Yes, that's a currently unsupported project type. The behavior you're seeing is expected. We are planning support for additional project types, but nothing concrete at the moment.

**Comment by afaayerhan** [comment] 2015-07-20 23:46
thanks. it would be great if njsproj would be supported and also for tsconfig files sync with ItemGroup typescriptCompile includes.

**Comment by paulvanbrenk** [comment] 2015-07-20 23:57
That's exactly one of the problems we run into.. we don't want to have to keep the 2 files in sync. As long as the files are edited in Visual Studio we would be ok, but the moment one of the files is edited outside of Visual Studio the files would be out of sync and we would have a problem getting them back in agreement.

**Comment by Jak3b0** [comment] 2015-07-24 00:50
I'm trying to use the tsconfig.json inside an empty ASP.NET vNext project and it is not being used. I have to set the properties inside a PropertyGroup in the .xproj file... Is there any steps I need to do in order to make it work? @paulvanbrenk, as you mentionned in a previous reply, this should work right?

**Comment by paulvanbrenk** [comment] 2015-07-24 17:23
What does your project look like? 
The following setup should work:
````
/project root
    /wwwroot
    /scripts
        -tsconfig.json
        -*.ts
````

**Comment by jannavarro** [comment] 2015-08-06 02:17
@paulvanbrenk you mentioned "For VS 2015 RTM tsconfig.json based configuration is only supported for ASP.NET v5 and Cordova Projects."

In VS 2015 there is a project for Html Application with TypeScript. Will this be supported?

**Comment by paulvanbrenk** [comment] 2015-08-06 17:57
We are looking at making the experience better for all projects, including the Html App with TypeScript.. not sure about the time line though.

**Comment by dazinator** [comment] 2015-09-15 20:41
tsconfig.json is not being honored for me (new ASP.NET v5 project.)
I have had to add the ms build properties to the xproj.
Does the tsconfig.json file have to be placed under a /scripts directory as suggested?

**Comment by mhegazy** [comment] 2015-09-15 21:03
@dazinator, for now it needs to be under the scripts folder. but  we have a fix for this in the next release. so bear with us for a little bit longer.

**Comment by dazinator** [comment] 2015-09-15 22:05
@mhegazy ok thats fine - will give that a try. Thanks :)

**Comment by davismj** [comment] 2015-10-19 12:55
1. New HTML Application with TypeScript project.
2. tsconfig.json not supported in this project type.
3. Uninstall Visual Studio.

**Comment by oryol** [comment] 2015-11-04 20:25
I use latest (1.6.3 TypeScript language services), VS 2015 and ASP .Net Betta8. I have FrontendApp folder in the root of web project with tsconfig.json. It contains compiler options and links to files with TS definitions. I also use WebPack + ts-loader to build frontend application and it builds successfully.

But Visual Studio code analyzer shows errors in the TypeScript files for imports of modules which are declared in the definition files. If I add references like
```
/// <reference path="typings/tsd.d.ts" />
```
then errors are disappearing. But all these files are already declared in the tsconfig.json so I don't want to have two sources of these files. What is even more interesting that I have several modules (external) and I added reference comments only to one of them (the main one). If I reopen project and open some other TypeScript file (not main) - Visual Studio shows errors. If I open main TS file after that and wait a few seconds then errors disappear (in all TS files). And after each project reopen I need to open main TS file and wait few seconds.

Is it possible just to use files list with definitions from tsconfig.json without including reference comments.

**Comment by paulvanbrenk** [comment] 2015-11-04 20:44
@oryol Please see this wikipage about using `tsconfig.json` and ASP.NET 5. https://github.com/Microsoft/TypeScript/wiki/Using-TypeScript-With-ASP.NET-5

I think the reason you're seeing what you're seeing is that we only check for tsconfig.json files in the scripts folder.

**Comment by oryol** [comment] 2015-11-04 20:48
So, is it possible to use tsconfig.json in other folders (not in "Scripts")? If not - are you going to support such scenarios and when can we expect such feature?

**Comment by paulvanbrenk** [comment] 2015-11-04 20:50
@oryol No, not in TypeScript 1.7 (or earlier), However I'm actually right now working on making the `tsconfig.json` support a lot better in VS 2015, you should see that in the 1.8 release.

**Comment by oryol** [comment] 2015-11-04 20:52
Thank you for reply!

**Comment by defyjoy** [comment] 2016-03-06 08:17
Does this still work for *.csproj files ? I opened a new blank asp.net application and tried to make it work with tsconfig.json .The project I chose in 2015 was 

![image](https://cloud.githubusercontent.com/assets/1047068/13553080/c0d164a6-e3a1-11e5-9cba-3f60fd0c4354.png)


But it seems the VS completely ignores the tsconfig.json. 

![image](https://cloud.githubusercontent.com/assets/1047068/13553086/e11d4932-e3a1-11e5-8750-2dec8ff678b3.png)


My project structure somewhat looks like this 

![image](https://cloud.githubusercontent.com/assets/1047068/13553090/f86c3620-e3a1-11e5-9425-86504d2c6d83.png)

**Comment by mhegazy** [comment] 2016-03-07 18:01
@defyjoy can you try the latest (https://github.com/Microsoft/TypeScript/releases/tag/v1.8.7), and if you run into issues, please file a new issue and provide a project we can look at.

**Comment by paulvanbrenk** [comment] 2016-03-07 20:37
@defyjoy Can you make sure TypeScript shows in Help > About

**Comment by dehghani-mehdi** [comment] 2017-01-18 11:55
Doesn't work here, I'm using `VS 2015.3` and latest version of `TypeScript`

**Comment by dazinator** [comment] 2017-01-18 12:22
When using VS2015, put the tsconfig file in a "Scripts" folder. Otherwise I don't think VS will find it or honour it.

**Comment by dehghani-mehdi** [comment] 2017-01-18 14:10
@dazinator that isn't really good way to deal with config file, I always rename `Script` folder to `js`, personally prefer to use `commad-line` to deal with this issue.

**Comment by dazinator** [comment] 2017-01-18 14:27
@dehghani-mehdi - yep I know. I also think it's a poor, but that is how the VS project system supports typescript projects as far as I know. This should help @defyjoy. If you want to handle typescript project compilation outside VS using `tsc` that will of course work.

**Comment by dazinator** [comment] 2017-01-18 15:54
Also - if you do decide to use command line `tsc` to handle typescript project compilation, then you will want to disable VS from automatically transpiling ts files to js files (as it will to do that depending on your VS configuration settings for typescript language). To prevent VS from doing this in VS2015, add the following to your .csproj file:

```xml
<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
```

**Comment by dehghani-mehdi** [comment] 2017-01-19 05:18
@dazinator Thanks for the note, for now I just add `tsconfig.json` to the project for disabling auto generate JS file by VS :), of course the correct solution is what you mentioned.
