### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined  at getAssignmentTargetKind

### ISSUE THREAD

**Issue by therawk** [Microsoft/TypeScript#29365] opened 2019-01-11 08:56 UTC
**TypeScript Version:**  3.2.2

**Search Terms:**
Cannot read property 'kind' of undefined

I have found some results about this error but I haven't found anything about the problem where my project throws the error: "at getAssignmentTargetKind"

**Code**
I'm using angular 7.2.0 - the error first occured when I updated from 6.x to 7.x.
Also I tried creating a new project and just migrate everything file by file but since the error happens so randomly it's almost impossible to track down the file causing the problem :/

Here's the full error message:
```js

ERROR in : TypeError: Cannot read property 'kind' of undefined
    at getAssignmentTargetKind (E:\dev\client7\node_modules\typescript\lib\typescript.js:10234:28)
    at Object.isAssignmentTarget (E:\dev\client7\node_modules\typescript\lib\typescript.js:10277:16)
    at checkObjectLiteral (E:\dev\client7\node_modules\typescript\lib\typescript.js:47309:45)
    at checkExpressionWorker (E:\dev\client7\node_modules\typescript\lib\typescript.js:51806:28)
    at checkExpression (E:\dev\client7\node_modules\typescript\lib\typescript.js:51751:42)
    at checkExpressionWithContextualType (E:\dev\client7\node_modules\typescript\lib\typescript.js:51581:26)
    at checkApplicableSignature (E:\dev\client7\node_modules\typescript\lib\typescript.js:48900:35)
    at chooseOverload (E:\dev\client7\node_modules\typescript\lib\typescript.js:49219:26)
    at resolveCall (E:\dev\client7\node_modules\typescript\lib\typescript.js:49171:26)
    at resolveCallExpression (E:\dev\client7\node_modules\typescript\lib\typescript.js:49478:20)
    at resolveSignature (E:\dev\client7\node_modules\typescript\lib\typescript.js:49766:28)
    at getResolvedSignature (E:\dev\client7\node_modules\typescript\lib\typescript.js:49798:26)
    at checkCallExpression (E:\dev\client7\node_modules\typescript\lib\typescript.js:49890:29)
    at checkExpressionWorker (E:\dev\client7\node_modules\typescript\lib\typescript.js:51817:28)
    at checkExpression (E:\dev\client7\node_modules\typescript\lib\typescript.js:51751:42)
    at resolveDecorator (E:\dev\client7\node_modules\typescript\lib\typescript.js:49685:28)

```

I added this to typescript.js:
```js
function getAssignmentTargetKind(node) {
        var parent = node.parent;

        if(!parent) {
          console.log(node)
        }
```

Here's the console.log
```js

NodeObject {
  pos: 493,
  end: 596,
  flags: 8,
  transformFlags: 536870912,
  parent: undefined,
  kind: 188,
  properties:
   [ NodeObject {
       pos: 494,
       end: 516,
       flags: 0,
       transformFlags: 536870912,
       parent: [NodeObject],
       kind: 275,
       decorators: undefined,
       modifiers: undefined,
       name: [IdentifierObject],
       questionToken: undefined,
       exclamationToken: undefined,
       initializer: [TokenObject],
       modifierFlagsCache: 536870912,
       symbol: [SymbolObject] },
     NodeObject {
       pos: 517,
       end: 555,
       flags: 8,
       transformFlags: 536870912,
       parent: undefined,
       kind: 275,
       name: [IdentifierObject],
       questionToken: undefined,
       initializer: [NodeObject],
       original: [NodeObject],
       modifierFlagsCache: 536870912 },
     NodeObject {
       pos: -1,
       end: -1,
       flags: 8,
       transformFlags: 536870912,
       parent: undefined,
       kind: 275,
       name: [IdentifierObject],
       questionToken: undefined,
       initializer: [NodeObject],
       modifierFlagsCache: 536870912 },
     pos: -1,
     end: -1,
     hasTrailingComma: undefined,
     transformFlags: 536870912 ],
  multiLine: true,
  original:
   NodeObject {
     pos: 493,
     end: 596,
     flags: 0,
     transformFlags: 536870912,
     parent:
      NodeObject {
        pos: 483,
        end: 597,
        flags: 8192,
        transformFlags: 536870912,
        parent: [NodeObject],
        kind: 191,
        expression: [IdentifierObject],
        arguments: [Array],
        id: 136557 },
     kind: 188,
     multiLine: true,
     properties:
      [ [NodeObject],
        [NodeObject],
        [NodeObject],
        pos: 494,
        end: 594,
        transformFlags: 536870912 ],
     symbol:
      SymbolObject {
        flags: 4096,
        escapedName: '__object',
        declarations: [Array],
        members: [Map],
        valueDeclaration: [Circular] },
     nextContainer:
      NodeObject {
        pos: 666,
        end: 879,
        flags: 128,
        transformFlags: 536875010,
        parent: [NodeObject],
        kind: 157,
        decorators: undefined,
        modifiers: undefined,
        typeParameters: undefined,
        parameters: [Array],
        body: [NodeObject],
        modifierFlagsCache: 536870912,
        symbol: [SymbolObject],
        locals: [Map],
        returnFlowNode: [Object],
        nextContainer: [NodeObject],
        id: 136559 },
     contextualType: undefined,
     contextualMapper: undefined,
     jsDocCache: [] },
  modifierFlagsCache: 536870912,
  contextualType:
   TypeObject {
     checker:
      { getNodeCount: [Function: getNodeCount],
        getIdentifierCount: [Function: getIdentifierCount],
        getSymbolCount: [Function: getSymbolCount],
        getTypeCount: [Function: getTypeCount],
        isUndefinedSymbol: [Function: isUndefinedSymbol],
        isArgumentsSymbol: [Function: isArgumentsSymbol],
        isUnknownSymbol: [Function: isUnknownSymbol],
        getMergedSymbol: [Function: getMergedSymbol],
        getDiagnostics: [Function: getDiagnostics],
        getGlobalDiagnostics: [Function: getGlobalDiagnostics],
        getTypeOfSymbolAtLocation: [Function: getTypeOfSymbolAtLocation],
        getSymbolsOfParameterPropertyDeclaration: [Function: getSymbolsOfParameterPropertyDeclaration],
        getDeclaredTypeOfSymbol: [Function: getDeclaredTypeOfSymbol],
        getPropertiesOfType: [Function: getPropertiesOfType],
        getPropertyOfType: [Function: getPropertyOfType],
        getTypeOfPropertyOfType: [Function: getTypeOfPropertyOfType],
        getIndexInfoOfType: [Function: getIndexInfoOfType],
        getSignaturesOfType: [Function: getSignaturesOfType],
        getIndexTypeOfType: [Function: getIndexTypeOfType],
        getBaseTypes: [Function: getBaseTypes],
        getBaseTypeOfLiteralType: [Function: getBaseTypeOfLiteralType],
        getWidenedType: [Function: getWidenedType],
        getTypeFromTypeNode: [Function: getTypeFromTypeNode],
        getParameterType: [Function: getTypeAtPosition],
        getPromisedTypeOfPromise: [Function: getPromisedTypeOfPromise],
        getReturnTypeOfSignature: [Function: getReturnTypeOfSignature],
        getNullableType: [Function: getNullableType],
        getNonNullableType: [Function: getNonNullableType],
        typeToTypeNode: [Function: typeToTypeNode],
        indexInfoToIndexSignatureDeclaration: [Function: indexInfoToIndexSignatureDeclaration],
        signatureToSignatureDeclaration: [Function: signatureToSignatureDeclaration],
        symbolToEntityName: [Function: symbolToEntityName],
        symbolToExpression: [Function: symbolToExpression],
        symbolToTypeParameterDeclarations: [Function: symbolToTypeParameterDeclarations],
        symbolToParameterDeclaration: [Function: symbolToParameterDeclaration],
        typeParameterToDeclaration: [Function: typeParameterToDeclaration],
        getSymbolsInScope: [Function: getSymbolsInScope],
        getSymbolAtLocation: [Function: getSymbolAtLocation],
        getShorthandAssignmentValueSymbol: [Function: getShorthandAssignmentValueSymbol],
        getExportSpecifierLocalTargetSymbol: [Function: getExportSpecifierLocalTargetSymbol],
        getExportSymbolOfSymbol: [Function: getExportSymbolOfSymbol],
        getTypeAtLocation: [Function: getTypeAtLocation],
        getPropertySymbolOfDestructuringAssignment: [Function: getPropertySymbolOfDestructuringAssignment],
        signatureToString: [Function: signatureToString],
        typeToString: [Function: typeToString],
        symbolToString: [Function: symbolToString],
        typePredicateToString: [Function: typePredicateToString],
        writeSignature: [Function: writeSignature],
        writeType: [Function: writeType],
        writeSymbol: [Function: writeSymbol],
        writeTypePredicate: [Function: writeTypePredicate],
        getAugmentedPropertiesOfType: [Function: getAugmentedPropertiesOfType],
        getRootSymbols: [Function: getRootSymbols],
        getContextualType: [Function: getContextualType],
        getContextualTypeForObjectLiteralElement: [Function: getContextualTypeForObjectLiteralElement],
        getContextualTypeForArgumentAtIndex: [Function: getContextualTypeForArgumentAtIndex],
        getContextualTypeForJsxAttribute: [Function: getContextualTypeForJsxAttribute],
        isContextSensitive: [Function: isContextSensitive],
        getFullyQualifiedName: [Function: getFullyQualifiedName],
        getResolvedSignature: [Function: getResolvedSignature],
        getResolvedSignatureForSignatureHelp: [Function: getResolvedSignatureForSignatureHelp],
        getConstantValue: [Function: getConstantValue],
        isValidPropertyAccess: [Function: isValidPropertyAccess],
        isValidPropertyAccessForCompletions: [Function: isValidPropertyAccessForCompletions],
        getSignatureFromDeclaration: [Function: getSignatureFromDeclaration],
        isImplementationOfOverload: [Function: isImplementationOfOverload],
        getImmediateAliasedSymbol: [Function: getImmediateAliasedSymbol],
        getAliasedSymbol: [Function: resolveAlias],
        getEmitResolver: [Function: getEmitResolver],
        getExportsOfModule: [Function: getExportsOfModuleAsArray],
        getExportsAndPropertiesOfModule: [Function: getExportsAndPropertiesOfModule],
        getSymbolWalker: [Function: getSymbolWalker],
        getAmbientModules: [Function: getAmbientModules],
        getJsxIntrinsicTagNamesAt: [Function: getJsxIntrinsicTagNamesAt],
        isOptionalParameter: [Function: isOptionalParameter],
        tryGetMemberInModuleExports: [Function: tryGetMemberInModuleExports],
        tryGetMemberInModuleExportsAndProperties: [Function: tryGetMemberInModuleExportsAndProperties],
        tryFindAmbientModuleWithoutAugmentations: [Function: tryFindAmbientModuleWithoutAugmentations],
        getApparentType: [Function: getApparentType],
        getUnionType: [Function: getUnionType],
        createAnonymousType: [Function: createAnonymousType],
        createSignature: [Function: createSignature],
        createSymbol: [Function: createSymbol],
        createIndexInfo: [Function: createIndexInfo],
        getAnyType: [Function: getAnyType],
        getStringType: [Function: getStringType],
        getNumberType: [Function: getNumberType],
        createPromiseType: [Function: createPromiseType],
        createArrayType: [Function: createArrayType],
        getElementTypeOfArrayType: [Function: getElementTypeOfArrayType],
        getBooleanType: [Function: getBooleanType],
        getFalseType: [Function: getFalseType],
        getTrueType: [Function: getTrueType],
        getVoidType: [Function: getVoidType],
        getUndefinedType: [Function: getUndefinedType],
        getNullType: [Function: getNullType],
        getESSymbolType: [Function: getESSymbolType],
        getNeverType: [Function: getNeverType],
        isSymbolAccessible: [Function: isSymbolAccessible],
        getObjectFlags: [Function: getObjectFlags],
        isArrayLikeType: [Function: isArrayLikeType],
        isTypeInvalidDueToUnionDiscriminant: [Function: isTypeInvalidDueToUnionDiscriminant],
        getAllPossiblePropertiesOfTypes: [Function: getAllPossiblePropertiesOfTypes],
        getSuggestionForNonexistentProperty: [Function: getSuggestionForNonexistentProperty],
        getSuggestionForNonexistentSymbol: [Function: getSuggestionForNonexistentSymbol],
        getSuggestionForNonexistentExport: [Function: getSuggestionForNonexistentExport],
        getBaseConstraintOfType: [Function: getBaseConstraintOfType],
        getDefaultFromTypeParameter: [Function: getDefaultFromTypeParameter],
        resolveName: [Function: resolveName],
        getJsxNamespace: [Function: getJsxNamespace],
        getAccessibleSymbolChain: [Function: getAccessibleSymbolChain],
        getTypePredicateOfSignature: [Function: getTypePredicateOfSignature],
        resolveExternalModuleSymbol: [Function: resolveExternalModuleSymbol],
        tryGetThisTypeAt: [Function: tryGetThisTypeAt],
        getTypeArgumentConstraint: [Function: getTypeArgumentConstraint],
        getSuggestionDiagnostics: [Function: getSuggestionDiagnostics],
        runWithCancellationToken: [Function: runWithCancellationToken],
        getLocalTypeParametersOfClassOrInterfaceOrTypeAlias:
         [Function: getLocalTypeParametersOfClassOrInterfaceOrTypeAlias] },
     flags: 524288,
     id: 14277,
     objectFlags: 2,
     symbol:
      SymbolObject {
        flags: 66,
        escapedName: 'Component',
        declarations: [Array],
        members: [Map],
        parent: [SymbolObject],
        exports: Map {},
        valueDeclaration: [NodeObject],
        id: 118624,
        isReferenced: 67897832 },
     members:
      Map {
        'changeDetection' => [SymbolObject],
        'viewProviders' => [SymbolObject],
        'moduleId' => [SymbolObject],
        'templateUrl' => [SymbolObject],
        'template' => [SymbolObject],
        'styleUrls' => [SymbolObject],
        'styles' => [SymbolObject],
        'animations' => [SymbolObject],
        'encapsulation' => [SymbolObject],
        'interpolation' => [SymbolObject],
        'entryComponents' => [SymbolObject],
        'preserveWhitespaces' => [SymbolObject],
        'selector' => [SymbolObject],
        'inputs' => [SymbolObject],
        'outputs' => [SymbolObject],
        'providers' => [SymbolObject],
        'exportAs' => [SymbolObject],
        'queries' => [SymbolObject],
        'host' => [SymbolObject],
        'jit' => [SymbolObject] },
     properties:
      [ [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject] ],
     callSignatures: [],
     constructSignatures: [],
     stringIndexInfo: undefined,
     numberIndexInfo: undefined,
     resolvedBaseTypes: [ [TypeObject] ],
     declaredProperties:
      [ [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject],
        [SymbolObject] ],
     declaredCallSignatures: [],
     declaredConstructSignatures: [],
     declaredStringIndexInfo: undefined,
     declaredNumberIndexInfo: undefined },
  contextualMapper: undefined }
```

**Expected behavior:**
No errors

**Actual behavior:**
See above

Is there anything I can do to finally track down the file/code causing the error?

**Comment by Provson** [comment] 2019-01-24 10:31
Same issue for me. I use angular 7.2.2, typescript 3.2.4

**Comment by AngularTx** [comment] 2019-01-29 17:02
i have the same issue with 7.2.2 and 3.2.4 and with 3.1.6 .

**Comment by Kevinci** [comment] 2019-01-30 06:39
Same issue with angular 7.2.0, typescript 3.1.6

**Comment by StarpTech** [comment] 2019-02-13 08:45
Same issue for me as well. Angular: 7.2.4 Typescript: 3.2.4

**Comment by Provson** [comment] 2019-02-14 09:13
Any idea ? How can we help you ?

**Comment by dialeggio** [comment] 2019-02-26 23:16
Same issue with angular 7.2.6 and typescript 3.1.6

**Comment by cancerberoSgx** [comment] 2019-02-27 01:53
Don't know if is the same cause, but I'm having the same error with the following code that, although is weird, tsc is not emitting any diagnostics and it crash without stacktrace (was able to get a stacktrace with ts-node). 

```

class C<S> {
  a={}
  m(s: S) {
    const b = { ...this.a, ...s } = {   }
  }
}
```

```


/home/sg/git/jsx-alone/jsx-alone-dom-extra/node_modules/typescript/lib/tsc.js:71491
                throw e;
                ^

TypeError: Cannot read property 'kind' of undefined
    at Object.isIdentifier (/home/sg/git/jsx-alone/jsx-alone-dom-extra/node_modules/typescript/lib/tsc.js:10382:21)
    at getLiteralTypeFromPropertyName (/home/sg/git/jsx-alone/jsx-alone-dom-extra/node_modules/typescript/lib/tsc.js:32924:23)
    at Object.map (/home/sg/git/jsx-alone/jsx-alone-dom-extra/node_modules/typescript/lib/tsc.js:378:29)
    at getRestType (/home/sg/git/jsx-alone/jsx-alone-dom-extra/node_modules/typescript/lib/tsc.js:29004:47)
    at checkObjectLiteralDestructuringPropertyAssignment (/home/sg/git/jsx-alone/jsx-alone-dom-extra/node_modules/typescript/lib/tsc.js:43034:28)
    at checkObjectLiteralAssignment (/home/sg/git/jsx-alone/jsx-alone-dom-extra/node_modules/typescript/lib/tsc.js:43003:17)
    at checkDestructuringAssignment (/home/sg/git/jsx-alone/jsx-alone-dom-extra/node_modules/typescript/lib/tsc.js:43106:24)
    at checkBinaryLikeExpression (/home/sg/git/jsx-alone/jsx-alone-dom-extra/node_modules/typescript/lib/tsc.js:43186:24)
    at checkBinaryExpression (/home/sg/git/jsx-alone/jsx-alone-dom-extra/node_modules/typescript/lib/tsc.js:43181:20)
    at checkExpressionWorker (/home/sg/git/jsx-alone/jsx-alone-dom-extra/node_modules/typescript/lib/tsc.js:43743:28)


```

My two cents, keep it up

**Comment by MoGray** [comment] 2019-03-04 23:00
Just to add onto these issues with Angular.

This has been happening periodically to me and a few people on my team, but only when running through a VM of Windows.  When running this with the same setup on our Mac side or on a Windows machine not in a VM we have yet to experience this issue with many of the same versions of Angular others have mentioned in here.

This could certainly be an overall bug that we have yet to experience on non-VM's, but as others have mentioned it's so periodic it's hard to track down what's causing it or why.

**Comment by volser** [comment] 2019-03-07 07:56
same issue angular 7.2.7, ts 3.2.4

**Comment by StarpTech** [comment] 2019-03-07 08:00
@volser when does it happen? Could you make a repro or describe your setup in detail?

**Comment by volser** [comment] 2019-03-07 08:10
when I first time run `ng serve` all ok, but when I change something and hot reload compiles changes, I'm getting such error, BUT not each time, happens randomly. may be 1 of 10 reloads

**Comment by volser** [comment] 2019-03-07 08:11
and only on Windows

**Comment by volser** [comment] 2019-03-07 08:12
looks like it happens, when I'm making changes during compiling

**Comment by Provson** [comment] 2019-03-07 08:17
I tried to reinstall NodeJs, visual studio code (why not). I tried ng serve on Windows cmd and Powershell.
Nothing worked

**Comment by therawk** [comment] 2019-03-07 11:30
As recommended [here](https://stackoverflow.com/questions/53827570/typeerror-cannot-read-property-kind-of-undefined-at-getassignmenttargetkind/54900384#54900384) , ```Installing '@types/history' package``` seems to have fixed it.

Still I'm interested in what's causing it

**Comment by Provson** [comment] 2019-03-07 15:51
@therawk Hi, I installed '@type/history' and it dosn't works.
Personnaly, I don't understand how could it have worked.

**Comment by therawk** [comment] 2019-03-07 16:04
@Provson Hmmm I just checked what the package does and as you said - it's not supposed to work/solve this problem 🤔
Really strange. I never had this error after installing it though

**Comment by MoGray** [comment] 2019-03-11 19:31
I know this might not help too much, but seeing as it's an Angular specific bug with an object literal might narrow down what's breaking somewhere.

The code for SyntaxKind:  or the kind in the original post being 188 is "ObjectLiteralExpression".

From this code piece.

https://github.com/Microsoft/TypeScript/blob/master/lib/typescriptServices.d.ts

**Comment by Provson** [comment] 2019-04-01 07:55
Any update ?

**Comment by yevgeni-eosos** [comment] 2019-04-02 15:42
have the exact issue with angular 7.2.10 and typescript 3.1.1 (had ts 3.2.4 before, and downgraded to 3.1.1 to see if it fixes the issue).
it happens mostly when saving something in the project and it sometimes throws this error when trying to re-compile. then i need to stop it and re-run ng serve.
it's just annoying, not a big issue (but still an issue).

**Comment by andrewbranch** [comment] 2019-04-02 19:18
Hey @volser and @yevgeni-eosos, thanks for the info! Unfortunately I'm still unable to repro 😕 

Here's what I tried:

1. Boot Windows 10 in Parallels
2. I have node 8.12.0 on that OS
3. `npm i -g @angular/cli@7.2` (resolved to 7.2.4)
4. `ng new angular-test`, no routing, plain CSS: installed typescript 3.2.4
5. `ng serve`
6. Open `src/app/app.component.ts` and make small edits. Tried maybe 50–100 times, especially changing stuff in and around the `@Component` decorator since the stack trace shared started with `resolveDecorator`.

But no crashes. If anyone can share a repo or a zip file of a codebase that exhibits the issue, that would be 🌟 

Thanks!

**Comment by RyanCavanaugh** [comment] 2019-04-02 22:21
I'm resolving this as an Angular bug (see https://github.com/angular/angular-cli/issues/13861 ) - the call stack + debug print indicate that TS was given a `SourceFile` where an `ObjectLiteralExpression` didn't have a `parent`, which is an impossible state for TS to put itself into. The root cause here is some other code inserting synthesized nodes into the source tree and then trying to perform top-level checker operations on the resulting object - this isn't legal to do (SourceFiles are immutable) and the checker is not equipped to handle this.

With actual repro steps we could potentially investigate further on our side to help out, but as-is this is effectively a corrupted source tree and there's no issue on the TS side.

**Closed** 2019-04-02 22:21 UTC
Labels: External

**Comment by osnoser1** [comment] 2019-05-19 03:40
This problem happens to me when I am working on some feature in an angular project, and I must change the branch in the repository where all the files that the other branch does not have are deleted.

**Comment by Gaetan-LeGac** [comment] 2019-08-30 08:34
Same error when I try to add add an new element via a custom transformer:
```
getCustomTransformers: () => ({
    before: [transformateurRepoGraphql()]
}),
```
```
if (node.arguments[1] === undefined)
    node.arguments[1] = ts.createObjectLiteral([]);
```
I get this error:
```
TypeError: Cannot read property 'kind' of undefined
    at getAssignmentTargetKind (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:10688:28)
    at Object.isAssignmentTarget (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:10731:16)
    at checkArrayLiteral (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:49045:45)
    at checkExpressionWorker (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:53941:28)
    at checkExpression (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:53878:38)
    at checkExpressionWithContextualType (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:53596:24)
    at checkApplicableSignature (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:50853:35)
    at chooseOverload (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:51238:26)
    at resolveCall (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:51157:26)
    at resolveCallExpression (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:51468:20)
    at resolveSignature (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:51759:28)
    at getResolvedSignature (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:51790:26)
    at checkCallExpression (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:51877:29)
    at checkExpressionWorker (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:53956:28)
    at checkExpression (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:53878:38)
    at checkAwaitExpression (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:52855:31)
```
Same with `createArrayLiteral`. When I use `createStringLiteral`, I get this one:
```
TypeError: Cannot read property 'text' of undefined
    at getErrorSpanForNode (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:9363:40)
    at Object.createDiagnosticForNodeFromMessageChain (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:9290:20)
    at checkTypeRelatedTo (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:42751:31)
    at checkTypeRelatedToAndOptionallyElaborate (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:42030:24)
    at checkApplicableSignature (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:50858:26)
    at resolveCall (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:51168:21)
    at resolveCallExpression (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:51468:20)
    at resolveSignature (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:51759:28)
    at getResolvedSignature (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:51790:26)
    at checkCallExpression (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:51877:29)
    at checkExpressionWorker (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:53956:28)
    at checkExpression (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:53878:38)
    at checkAwaitExpression (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:52855:31)
    at checkExpressionWorker (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:53980:28)
    at checkExpression (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:53878:38)
    at checkExpressionCached (/home/gaetan/www/Professionnel/Node/laboiteabitcoin.fr/node_modules/typescript/lib/typescript.js:53617:38)
```

**Comment by carbler** [comment] 2020-02-09 04:43
I'm having the same problem. If you find a solution, I will be attentive!

**Comment by bmeritter** [comment] 2020-03-10 01:28
I'm also having the same problem. If you find a solution, I will be attentive!

**Comment by BekAndriy** [comment] 2020-06-17 08:41
I had the same issue, but it was in my tsconfig.json. 
I added the "files" key and it helps.
Below is my config file.
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "module": "commonjs",
    "outDir": "dist",
    "target": "es2017",
    "isolatedModules": false,
    "noEmit": false,
    "sourceMap": true
  },
  "files": [
    "./node_modules/@types/node/index.d.ts"
  ],
  "include": ["server/**/*.ts"],
  "exclude": [
    "node_modules"
  ]
}
