### ISSUE TITLE
Name conflict between JS keywords and generated function names when transpiling classes to ES5

### ISSUE THREAD

**Issue by robinWongM** [microsoft/TypeScript#34831] opened 2019-10-30 18:46 UTC
**TypeScript 3.6.3**
[Playground link](https://www.typescriptlang.org/play/?target=1#code/DYUwLgBCAeAOD2AnMBnAXBAhgOwJ4G4BYAKBgWRQDoATEAM0wFdhIBeCAY2ExRQgG8SEYZ3jYUYRIw5gkACgCUAoSNUB6NRGrwI2eGAAWAS2wBzFcIC+JS0A)

Compiler Options:
```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES5",
    "module": "ESNext"
  }
}
```

**Input:**
```typescript
let exports: any;
exports.default = class {
    constructor() {
        // do nothing
    }
}
```

**Output:**
```javascript
"use strict";
var exports;
exports.default = /** @class */ (function () {
    function default() {
        // do nothing
    }
    return default;
}());

```

**Expected behavior:**
The function name should be replaced when it might be invalid. In the above example, `default` is not a valid function name and `function default()` will throw an error in the browser.

**Comment by a-tarasyuk** [comment] 2020-07-19 09:08
Duplicate of https://github.com/microsoft/TypeScript/issues/26325

**Comment by RyanCavanaugh** [comment] 2020-07-20 18:16
Thanks @a-tarasyuk

**Closed by RyanCavanaugh** 2020-07-20 18:16 UTC
Labels: Duplicate
