### ISSUE TITLE
Enhancement: Playground replaces ")" with "%29" for easily pasting "Share" links into Reddit

### ISSUE THREAD

**Issue by cspotcode** [Microsoft/TypeScript#10154] opened 2016-08-04 21:20 UTC
This is a minor usability improvement to the TypeScript Playground, not a bug or design proposal.

When posting code samples on Reddit, I include a link to the TypeScript Playground.  Reddit uses markdown formatting, but unlike Github, it terminates the link early if the URL contains a ")".  Here is an example: https://www.reddit.com/r/FormatPractice/comments/4w6rj0/testing_123/

If the "Share" button on the TypeScript Playground replaces closing parentheses with "%29" in the URL hash, it will be more convenient to paste Playground links into Reddit posts.

Here is a relevant Reddit help post: https://www.reddit.com/r/help/comments/lyz35/problem_using_links_with_parentheses_in_a_comment/

**Comment by mhegazy** [comment] 2017-05-12 00:20
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/14943

**Closed by mhegazy** 2017-05-12 00:20 UTC
Labels: Docs, Suggestion
