### ISSUE TITLE
[BUG](?) Strict null check not warning about possibly undefined class members

### ISSUE THREAD

**Issue by Bnaya** [Microsoft/TypeScript#14926] opened 2017-03-30 08:41 UTC
**TypeScript Version:**  2.2.1

**Code**

```ts
class MyClass {
    public request: {} | null;
}
const c = new MyClass();
 // with strict null check the type here is {} | null, but its actually undefined! 
c.request

```

**Expected behavior:**
The type-checker should warn that request is undefined if no value was set in the member declaration or in the constructor  
**Actual behavior:**
TS treating the member as the declared type, even its not initialize

**Comment by cevek** [comment] 2017-03-30 13:10
Heh, another one issue https://github.com/Microsoft/TypeScript/issues/14929

**Comment by DanielRosenwasser** [comment] 2017-03-30 14:36
Duplicate of #8476 which is very difficult to solve.

**Closed by DanielRosenwasser** 2017-03-30 14:36 UTC

**Comment by gdelmas** [comment] 2017-03-31 14:04
> Duplicate of #8476 which is very difficult to solve.

"Very difficult to solve" should not have been the reason to close #8476

**Comment by Bnaya** [comment] 2017-03-31 14:16
any comments should go to #8476
