### ISSUE TITLE
error TS1206: on anonymous class

### ISSUE THREAD

**Issue by devpaul** [Microsoft/TypeScript#8176] opened 2016-04-19 15:25 UTC
I am trying to use a decorator with an anonymous class (class expression) on TypeScript 1.8.9 and am receiving the error: "error TS1206: Decorators are not valid here."

```typescript
const decorator: MethodDecorator = function (target: Object, propertyKey: string,
	descriptor: TypedPropertyDescriptor<any>): TypedPropertyDescriptor<any> {
	return descriptor;
};
const C = class { 
	@decorator method() {} 
};
```

I didn't see anything addressing decorating anonymous classes in the roadmap, so I am filing this issue to either provide clarification to other people in my situation or to mark a bug.

**Comment by mhegazy** [comment] 2016-04-19 18:07
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/7342

**Closed by mhegazy** 2016-04-19 18:07 UTC
