### ISSUE TITLE
Does typeguard work with expressions, i.e. ev.target?

### ISSUE THREAD

**Issue by TimKelly2** [Microsoft/TypeScript#2184] opened 2015-03-02 20:40 UTC
A cast appears to work with the expression, ev.target.
```ts
         if(ev.target instanceof Node) {
             var n : Node = <Node>ev.target;
             n.appendChild(document.getElementById(data));
         }
```
A typeguard appears to work with the simple variable, t.
```ts
         var t = ev.target;
         if(t instanceof Node) {
             var n : Node = t;
             n.appendChild(document.getElementById(data));
         }
```
A typeguard appears to fail with an expression, ev.target or (ev.target).
```ts
         if(ev.target instanceof Node) {
             ev.target.appendChild(document.getElementById(data));
         }
```

**Comment by danquirk** [comment] 2015-03-02 20:50
This is by design currently (the spec section on type guards only mentions narrowing variables and properties, not dotted names). We can consider augmenting the narrowing functionality but there are concerns about side effecting function calls.

**Comment by zspitz** [comment] 2015-04-15 13:34
+1

**Comment by mhegazy** [comment] 2016-02-22 18:17
closing in favor of https://github.com/Microsoft/TypeScript/issues/3812

**Closed by mhegazy** 2016-02-22 18:17 UTC
Labels: Needs Proposal, Suggestion
