### ISSUE TITLE
Parse error with an 'override' variable

### ISSUE THREAD

**Issue by sarimarton** [microsoft/TypeScript#44996] opened 2021-07-13 01:02 UTC
# Bug Report

### 🔎 Search Terms

override

### 🕗 Version & Regression Information

- This changed between versions <4.2.3 and 4.3.*

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBCBuBTATsglgE0TAvDALANwBQoksAhrjABQIrpYwUTNgCeAlCaeNHElSZEAD2pFe5GGLx1BjUc1YUO3YkA)

### 💻 Code

const override = 4;
const a = (override as any); // <-- error; typescript thinks it's an unfinished arrow function

const overridex = 4;
const x = (overridex as any);

### 🙁 Actual behavior

TypeScript thinks it's an unfinished arrow function

### 🙂 Expected behavior

The code should not produce any error.

**Comment by DanielRosenwasser** [comment] 2021-07-13 02:47
Ugh - the same is true of (at least) `readonly`, `declare`, and `abstract`.

**Comment by a-tarasyuk** [comment] 2021-07-13 06:40
Duplicate of https://github.com/microsoft/TypeScript/issues/44466.

**Closed** 2021-07-16 18:00 UTC
Labels: Duplicate
