### ISSUE TITLE
Non-nullable type is not narrowed when inside function

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#20105] opened 2017-11-17 18:20 UTC
**TypeScript Version:**  2.6.1

**Code**

```ts
declare const obj: {
    myFn: (() => number) | undefined;
};

// No errors
if (obj.myFn !== undefined) obj.myFn();

if (obj.myFn !== undefined) {
    const a = () =>
        // Unexpected error: Object is possibly 'undefined'
        obj.myFn();
    a();
}
```

**Comment by andy-ms** [comment] 2017-11-17 18:57
Duplicate of #9998

**Closed** 2017-12-02 00:37 UTC
Labels: Duplicate
