### ISSUE TITLE
Null assertion operator blocking control flow anlysis

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#23662] opened 2018-04-24 18:49 UTC
**TypeScript Version:**  2.9.0-dev.20180422

**Search Terms:** 

**Code**

```ts
class Base { b!: number }
class Derived extends Base { d!: number; }    

declare var x: Base | undefined;

declare function isDerived(x: any): x is Derived;


if (x) { 
    if (isDerived(x!)) { 
        x // Base;
    }
    if (isDerived(x)) {
        x // Derived;
    }
}
```

**Expected behavior:**

`x` in both instances should have the same type.

**Actual behavior:**

`x` has two different types based on whether null assertion operator was used or not.

**Comment by mhegazy** [comment] 2018-04-25 16:47
> Eh not quite. But I think there is a dupe of this somewhere

yeah.. i remember seeing this before, but could not find it. my search skills are not what they used to be..

**Comment by andy-ms** [comment] 2018-07-24 15:57
Duplicate of #15655

**Closed** 2018-08-02 21:55 UTC
Labels: Duplicate
