### ISSUE TITLE
jsdoc template no check

### ISSUE THREAD

**Issue by awerlogus** [microsoft/TypeScript#43697] opened 2021-04-15 22:03 UTC
# Bug Report

### 💻 Code

in ts code everything is ok

```ts
// Argument of type 'number' is not assignable to parameter of type 'T'
const a: <T>(func: (x: T, y: T) => T, x: T) => T = (func, x) => func(x, 2)
```

in js code no error
```js
/** @type {<T>(func: (x: T, y: T) => T, x: T) => T} */
const a = (func, x) => func(x, 2)
```

### 🙁 Actual behavior

no error in js code

### 🙂 Expected behavior

the same error as in ts code

**Comment by sandersn** [comment] 2021-04-16 14:06
Duplicate of https://github.com/microsoft/TypeScript/issues/42060

**Closed by sandersn** 2021-04-16 14:06 UTC
Labels: Bug, checkJs
