### ISSUE TITLE
`AbortSignal` incorrectly type-narrowed during `async` function

### ISSUE THREAD

**Issue by neil-morrison44** [microsoft/TypeScript#55982] opened 2023-10-04 15:32 UTC
### 🔎 Search Terms

"abortSignal", "async type narrowing", "await type narrowing", "AbortSignal.aborted: false"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about bugs(?)

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBATgQzAExAWwIIQJ5mAFQAsBLMAcxgF4YEc8YAKASgC4YAFOdYiAUwB4wAVzQAjXnAB8VaQG8AUDCU0A7gmKwGYXio5c0PAQDcQxZJIYM4vCCAA2R3kxkw+UfMTS8QQqJeeU0ta2DrzMADQwAKxMsYrK1lBCcGAwAMwADPIAvvLyoJCwCABiQnhQxOBUjAFy8UoF0DSiIHBQAMLgUFx2dhLV2roYLW2dYN32fXDM9TCNRWBYuMCl5ZWp1LTLNS4Kyvtz4E1GCHZCvBjVCGoa8EiomHQEJOQzB8rEAGaMCCMdXT0pgA6CDEMhgU5A36tKC8ZDORLJMCzfbzGAnM68ABCVxusEQKHQSzwRFIZDe7xgXx+fzGE16EhBYIhdihfzhzj2lNRR3svCBdhA5IARNDRgDJozQeDIWLYcgYGoIDBuudhUwUZTESlNUpctzGnyBUKGLIMecMJFzdjshr9vrlEhiSsysAKuBmPs8vs3B4vD4-J7AjAue9qQwALIIKCEIEEh6e6QZIExZowumAxlyil6yIANg1uRKrvdYBm8iAA

### 💻 Code

```ts
const randomAsyncThing = async (): Promise<number> => {
    await (new Promise<void>((resolve) => setTimeout(() => resolve(), 5)))
    return 30
}

const aFunction = () => {
    const abortController = new AbortController()
    const anAsyncFunction = async () => {
        const valueA = await randomAsyncThing()
        if (abortController.signal.aborted) return
        const valueB = await randomAsyncThing()
        if (abortController.signal.aborted) {
            console.log("abortController.signal.aborted was true")
            return
        }
        console.log({valueA, valueB})
    }
    anAsyncFunction()    

    setTimeout(() => {
        if (Math.random() > 0.5) abortController.abort()
    }, 6)
}
aFunction()
```

### 🙁 Actual behavior

Typescript narrows the `abortController.signal.aborted` on line 12 to `false`

### 🙂 Expected behavior

It should know not to narrow the type since it doesn't have enough information to infer its new type after the `await`.

Either:
- It sees that it's an async function, with an `await` between the two checks and that the origin of `abortController.signal.aborted` is outside the scope of the function and resets the type narrowing on `await`
- it knows that AbortSignals are externally set & there's special behaviour to avoid narrowing them (though any other boolean property in an object outside the current scope would have the same issue)

Might need to go as far as always resetting narrowed types upon `await` for everything that isn't a primitive value with a scope local to the closure, but there's probably something smarter I've not thought of.

### Additional information about the issue

Probably wouldn't have noticed it if it wasn't for this https://typescript-eslint.io/rules/no-unnecessary-condition/ eslint rule flagging it

**Comment by MartinJohns** [comment] 2023-10-04 15:37
Another duplicate of #9998.

**Comment by fatcerberus** [comment] 2023-10-04 15:42
FWIW the `await` is irrelevant - *any* function call, async or not, might mutate an object.

**Closed** 2023-10-07 01:24 UTC
Labels: Duplicate
