### ISSUE TITLE
Exclude specific files from auto import suggestions

### ISSUE THREAD

**Issue by thorn0** [microsoft/TypeScript#35395] opened 2019-11-27 21:48 UTC
## Search Terms

autoimport, exclude, ignore, isolation, encapsulation 

## Suggestion

We need a way to exclude files from auto import. Not from the project, only from the auto import suggestions.

## Use Cases

My project includes a .d.ts file (generated from the previous version of the project) with legacy data structures (interfaces), many of which have the same names as their counterparts, newer data structures. As that file uses `declare module "..." { ... }` syntax, imports from it are non-relative, which is why auto import gives them a higher priority whereas modules with the newer structures have relative paths. The result is that the 'Add all missing imports' command constantly creates lots of wrong imports. If only there were a way to suppress suggestions for that specific module. I want to import from it only in rare cases.

I feel like this problem kind of defeats one of the important points of modules: I wanted to **isolate** those legacy definitions inside their module and forget about them, but because of this auto import issue they constantly get in the way.

---

Another example. Type definitions for libraries are in no hurry to use the new `asserts` feature of TS 3.7 for compatibility reasons. When I defined my own `assert` function to benefit from this feature, VS Code started to insist on importing `assert` form Node's `console` module instead, so, for lack of a better solution, I ended up renaming the function.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by raijinsetsu** [comment] 2020-08-07 13:27
We have a similar issue in a large project: a legacy set of code that no new code should reference but which must stay where it is for compatibility. Being able to instruct VSCode to ignore the files in that folder for the purposes of auto-import would be VERY beneficial.

Currently, we're looking into whether or not ESLint can at least cause an error but I'm not sure it supports restricting relative modules like that.

**Comment by SimpleCookie** [comment] 2020-08-10 12:25
I would also love to be able to exclude certain files. In my case I need a certain CSS file included AFTER another, however the organizeImports config automatically sorts them in the wrong order.

**Comment by yuval-gilboa** [comment] 2020-08-28 17:00
An additional use case we have is to enable splitting implementation of a large namespace to multiple module files but still expose it under a single namespace. This would allow us to have better control over shape of exposed apis without being tied to the internal module structure we use.

For example, assuming we have three module files:

`module1`
`module2`
`module3`

We then define a re-exports module like this:

```
import * as module1 from './module1';
import * as module2 from './module2';
import * as module3 from './module3';

export const lib = { ...module1, ...module2, ...module3};
```

We then use the `lib` namespace to access all members of module1...3. But the members of these internal modules are also exposed on the global 'namespace' which pollutes the api surface. This cannot be avoided due to the way the module system works, but if we were able to exclude these files from intellisense auto-import it would make them practically hidden and thus partially solve our problem.

**Comment by uhyo** [comment] 2020-08-28 17:13
I also would love to see this feature.
I recently created a library named [rocon](https://github.com/uhyo/rocon) and it has `react.d.ts` at the root directory so that users can import stuff from `"rocon/react"`. The `react.d.ts` reexports everything from `./lib/react`.

The problem is that TypeScript's auto-import suggestion prioritizes importing from `rocon/lib/react` rather than `rocon/react`. So it would be nice to exclude files inslide `rocon/lib` from the suggestion.

**Comment by IanEdington** [comment] 2021-01-25 17:32
@RyanCavanaugh It looks like this ticket generated quite a bit of feedback since you added that label. Is there any other specific feedback you're looking for?

**Comment by RyanCavanaugh** [comment] 2021-01-26 18:53
I liked the prior comment's example of a real-life file layout that caused problems.

**Comment by richardbarrell-calvium** [comment] 2021-02-17 13:40
I have a different use-case for asking for the same (or perhaps a different, but very similar) feature.

I have a codebase which uses a couple of libraries which have thousands of types defined in them (e.g. the "aws-sdk" library has, by my count, 28MB of ".d.ts" files). These libraries are only used in a couple of places in this codebase. It appears that their entire contents get considered for auto-suggestion everywhere. I believe this makes IDEs misbehave (I see VS Code spends >500ms in `JSON.parse()`, I'm told that IntelliJ exhibits weird behaviour) when typescript sends the IDE a big auto-complete candidate list.

Since I only use those libraries directly in a handful of files, it would be very useful to be able to omit them from typescript's auto suggestions. It would be even more useful to be able to turn auto suggest for them back on in just the specific files where I do want to use them.

As a workaround, I'm considering splitting my project into multiple packages (in one repo) so that the main top-level package doesn't have a direct dependency on the big libraries & their types aren't visible in it.

**Comment by richardbarrell-calvium** [comment] 2021-02-17 13:48
> I have a different use-case for asking for the same (or perhaps a different, but very similar) feature.
> ...snip

Issue #32826 looks like it's describing the same performance problem that I'm having & I'm looking for a way to work around.

**Comment by richardbarrell-calvium** [comment] 2021-02-17 13:49
> I have a different use-case for asking for the same (or perhaps a different, but very similar) feature.
> ...snip

Issue #32174 looks like it's describing the same performance problem that I'm having & I'm looking for a way to work around.

**Comment by not-rusty** [comment] 2021-03-13 18:25
Disabling autoimports with "typescript.suggest.autoImports" does fine for me, as the `Quick fix` functionality does the auto importing well enough, even though it would be nice to be able to exclude some folder paths to improve perfomance.

**Comment by Glandos** [comment] 2021-06-28 08:04
I have a Vue application with a `main.ts`:
```ts
import Vue from 'vue'

import './plugins/logger'
import './plugins/axios'

import App from './App.vue'
import router from './router'
import store from './store'
import i18n from './i18n'

// Auth needs axios and vuex (in store) defined
import './plugins/auth'
import vuetify from './plugins/vuetify'

// Make sure to register before importing any components
import './class-component-hooks'

import './plugins/caches'

Vue.config.productionTip = false

new Vue({
  router,
  store,
  vuetify,
  i18n,
  render: h => h(App)
}).$mount('#app')
```

I am using a code action on save to organize imports automatically. On this very file, I have:
```ts
import Vue from 'vue'
import App from './App.vue'
// Make sure to register before importing any components
import './class-component-hooks'
import i18n from './i18n'
// Auth needs axios and vuex (in store) defined
import './plugins/auth'
import './plugins/axios'
import './plugins/caches'
import './plugins/logger'
import vuetify from './plugins/vuetify'
import router from './router'
import store from './store'






Vue.config.productionTip = false

new Vue({
  router,
  store,
  vuetify,
  i18n,
  render: h => h(App)
}).$mount('#app')
```

As you can see, the import order is now wrong, since `auth` is imported before `axios`.

Organize Imports is a very good features, especially on save, but I need to exclude this specific file from it. Even an inline comment could do the trick.

**Comment by posva** [comment] 2021-08-11 11:06
This would be really useful for Vue as some libraries use an intermediate package in order to support Vue 2 and Vue 3 at the same time. The package is named `vue-demi` and is used by the libraries, but never in the application. So when people are using libraries using `vue-demi` (which points to either Vue 3 or Vue 2 depending on the installed dependencies), the auto-import features automatically adds `import { ref } from 'vue-demi'` instead of the corresponding `import { ref } from 'vue'` or `import { ref } from '@vue/composition-api'`. This is very easy to overlook and can cause very subtle and hard to debug issues.

Given the existing options of `typescript.preferences.import...` and some others, maybe there could be an option `typescript.preferences.excludeAutoImports: string[]` that exclude paths and package names. Maybe even a glob if that even makes sense but I think ignoring a whole folder would be enough.

**Comment by fgarcia** [comment] 2021-08-16 06:07
Maybe the `exports` keyword from `packages.json` is not a propper standard yet despite being widely supported, but it could be used as guideline of the preferred import path.

Whenever I want to import `{Logger}` from my `@app/core/logs` package within `{repo}/packages/core` and I am suggested imports from

- '../../core/src/logs'
- '../../core/build/logs'
- '../../core/dist/logs'
- '../node_modules/@app/core/logs'

Would it be so strange looking into `/packages/core/package.json` and guess I just want this?

- `@app/core/logs'

Currently it is not even suggested. Sure I can configure my editor to ignore the build/dist/node_modules paths, but still there is the problem that package exports are not even suggested

**Comment by vincaslt** [comment] 2021-09-10 08:31
`@chakra-ui/react` is facing the same issue, it's reexporting everything, but autocomplete prefers direct imports from `@chakra-ui/button` etc.

**Comment by Dids** [comment] 2021-09-22 09:30
Vue 3 project here and the problem in my case is [https://github.com/jquense/yup/blob/master/docs/typescript.md](yup).

It exports types that clash with practically all primitive types, so if I want to define `string` as a type, VSCode will auto-import/suggest `string` from `yup`, not the default `string` type.

Been Googling this issue for hours, but so far haven't found a solution outside of getting completely rid of `yup`.

**Comment by HaveSpacesuit** [comment] 2021-09-22 13:53
This has become an issue in the last few weeks that did not use to occur. If I try to auto import standard React functions or types, the default suggestion is coming from a different folder in node_modules. This consistently breaks my build and always takes me a minute to figure out. I would love to be able to add 'react-transition-group' to a blocked auto import list.

![image](https://user-images.githubusercontent.com/15036346/134356677-a9164f04-de7a-420b-9229-8296c15a8dbb.png)

**Comment by andrewbranch** [comment] 2021-09-22 23:40
@HaveSpacesuit that's #45784, fixed by #45792

**Comment by andrewbranch** [comment] 2021-09-22 23:46
@Dids can you open a new issue for your problem? I believe globals are supposed to prevent auto-imports of the same name from showing up at all, but the rules around this have changed a couple times. It’s worth looking into though.

As a general rule, if auto-imports is doing something that objectively makes no sense, please file a new issue instead of commenting on this one for better visibility. This thread is about excluding things that we really have no way of knowing to exclude without the user telling us explicitly, like https://github.com/microsoft/TypeScript/issues/35395#issuecomment-682898798. Thanks!

**Comment by kkirby** [comment] 2022-02-25 17:13
Yeah, anytime I write ": string", vscode auto imports "string" from fp-ts. Pretty annoying.

**Comment by andrewbranch** [comment] 2022-02-25 17:19
@kkirby that’s not related to this issue—please open a new one.

**Comment by andrewbranch** [comment] 2022-02-25 17:19
> As a general rule, if auto-imports is doing something that objectively makes no sense, please file a new issue instead of commenting on this one for better visibility. This thread is about excluding things that we really have no way of knowing to exclude without the user telling us explicitly, like https://github.com/microsoft/TypeScript/issues/35395#issuecomment-682898798. Thanks!

**Comment by kkirby** [comment] 2022-02-27 00:56
@andrewbranch I wouldn't say it doesn't make any sense. fp-ts does have a string export. And it might be useful for some people. I'd rather the import be opt-out rather than opt-in. If you insist I make a new issue for this one, then I will.

**Comment by andrewbranch** [comment] 2022-03-01 16:16
@kkirby `string` from fp-ts 7.5.2 is a namespace that doesn’t export any types, so it’s never going to be valid in a type position like `const s: string`. Even if it did export types, globals are supposed to shadow auto-imports with identical names. For both of these reasons, I can’t reproduce the issue you’re having, so a small repro would be super helpful when you open a new issue.

**Comment by aleclarson** [comment] 2022-04-07 19:02
I think a good rule of thumb would be: "If there's an empty line between two groups of `import` statements, avoid joining those groups together."

Comments would not count as empty lines.

**Comment by andrewbranch** [comment] 2022-04-07 22:34
@aleclarson did you mean to comment on https://github.com/microsoft/TypeScript/issues/41494 instead? 🤔

**Comment by eyedean** [comment] 2022-05-05 22:39
I am eagerly looking forward to this.  `aws-sdk` is killing me.  It both makes it hard for me to find out the real import that I am looking for and makes even typing on this project in VS-Code extremely slow. 😢😢😢

<img width="271" alt="image" src="https://user-images.githubusercontent.com/5694695/167036027-e39e47a7-e335-478e-93a8-940a9f5447ad.png">

PS. I really hope a solution better than "turn it off" comes into play  [after 3 years](https://github.com/microsoft/TypeScript/issues/32174#issuecomment-510146150).

**Comment by andrewbranch** [comment] 2022-05-05 22:59
> hard for me to find out the real import that I am looking for

Isn’t it the first one in the list?

I’m open to trying this, but I have to warn everyone who thinks this is going to be a big perf improvement that they’re probably going to be disappointed. Filtering stuff out of auto-imports is not going to filter it out of your program. All those files in aws-sdk are still going to be there, instantiating types, taking up slots in the global symbol table, etc. The only place it’s going to save any time is the work done actually generating these auto-imports lists, and much of the hard work there is already heavily cached.

**Comment by andrewbranch** [comment] 2022-05-05 23:07
@eyedean also, if you want the best auto-imports and perf experience, try to use the latest version of TypeScript. I can tell you’re not because I changed those fix descriptions in 4.6.

**Comment by eyedean** [comment] 2022-05-05 23:54
@andrewbranch Thanks for your prompt response, Andrew!

Yes, we are on 4.2.4 and I take that.  We have a plan to upgrade to 4.6 (or 4.7 [after 5/24](https://github.com/microsoft/TypeScript/issues/48027)) across the board later this month.  Catching up with TypeScript requires us to 1) make sure we utilize new features (going through [Daniel Rosenwasser](https://devblogs.microsoft.com/typescript/author/danielrosenwasser/)'s thorough changelog posts one by one), 2) make sure there is no breaking change, 3) make sure there is no breaking change with the libraries we use (e.g. we are still on Vue 2.)  It's a good problem to have though, I am always excited for new features and great improvements that make life easier! 🙌

About this specific problem, I googled for a way to limit this list as a cmd+dot hotkey (autocomplete) on VSCode can take up to 5 seconds for me right now.  And I vaguely remember that the intended import is not always the first one and there have been cases that I needed to go through the list to catch what I am after.  Anyhow, I don't have this problem on similar projects that don't have `aws-sdk` imported.  That's why I was looking for a way to fight that problem specifically.

I'll update here after we upgraded to 4.6 or 4.7.  In the meantime, I will be looking forward to seeing if "excludeAutoImports: string[]" (as suggested [in this comment](https://github.com/microsoft/TypeScript/issues/35395#issuecomment-896734327)) will be added. :)

Cheers!

**Comment by andrewbranch** [comment] 2022-05-06 00:14
Hmm, the `⌘ .` functionality actually doesn’t use the export cache like completions does; I should look into that separately. Although even completions in 4.2 lacks some major caching and performance improvements made since then.

**Comment by eyedean** [comment] 2022-05-08 03:05
@andrewbranch I am on TS `4.6.3`, VS-Code `1.67.0` and aws-sdk: `2.1130.0` and the desired import is the one at the bottom of the suggestion list:
<img width="232" alt="image" src="https://user-images.githubusercontent.com/5694695/167279919-24be5abb-2e53-4fa9-827f-e80390b6827f.png">

I am literally uninstalling (`npm un aws-sdk`) if I am planning to do more than 10 lines of code on this project.  Without `aws-sdk` everything is amazing. :)  I reaaaaaaallly wish TS would have a way to exclude one giant npm package from its suggestions.

**Comment by RyanCavanaugh** [comment] 2022-05-09 19:04
Just to reiterate, auto-import quickly (in relative terms) does a scan of all the files which are already being analyzed (causing the slowness) for general typechecking purposes. This suggestion is about excluding things from auto-import, not excluding them from analysis in general.

Excluding `aws-sdk` from auto-import *only* will make the auto-import completion list show up a small amount faster, but everything else is still going to be bogged down an equivalent amount.

**Closed** 2022-06-17 21:39 UTC
Labels: Suggestion, Needs Investigation, Fix Available

**Comment by andrewbranch** [comment] 2022-06-20 15:55
This still needs a corresponding change on the VS Code side—I’ll update here when that’s done.

**Comment by oBusk** [comment] 2022-08-02 15:44
@andrewbranch looks like it was done in https://github.com/microsoft/vscode/pull/153160 correct?

**Comment by andrewbranch** [comment] 2022-08-02 15:59
Yes, my apologies; I forgot to message here as promised. This is available in typescript@next and VS Code now. https://github.com/microsoft/TypeScript/pull/49578 explains how to use it. We’ll probably put something in the TypeScript release notes or the next VS Code release notes.

**Comment by fo-fo** [comment] 2022-09-04 15:16
This is all very cool, but now I find myself wanting to disable specific imports from libraries, while allowing others 🥴

First thing that comes to mind would be to make the `autoImportFileExcludePatterns` accept an object such as the following (a similar "set" pattern is already used in `files.exclude` in VSCode):

```
"autoImportFileExcludePatterns": {
  "someLib": {
    "default": true,
    "someExportedSymbol": true
  }
}
```

Any plans for something like this?

**Comment by acarroll-trend** [comment] 2022-09-07 20:34
@fo-fo I 2nd that request. I would like it to stop suggesting
```typescript
import { isEqual } from 'lodash-es';
```
and only allow
```typescript
import isEqual from 'lodash-es/isEqual';
```
The former is very easy to accidentally select, and miss on review. The problem is that on our project, we lose tree shaking, and then the final bundle balloons. Sure, we could mitigate that in other ways, but this is the most elegant solution, IMO.

**Comment by drpicox** [comment] 2022-10-08 17:10
I am with a project that each time that I write test, it autocompletes:

```js
const { default: test } = require("node:test");
```

I am tired of deleting that line. How can I avoid that without renouncing to auto import?

**Comment by zardoy** [comment] 2022-12-22 14:37
> This is all very cool, but now I find myself wanting to disable specific imports from libraries, while allowing others 🥴

Hi, @fo-fo, @acarroll-trend and others, I made [VS Code extension](https://github.com/zardoy/typescript-vscode-plugins#auto-imports) that should satisfy your requests:

<details>
<summary>Configuration examples</summary>

To disable (ignore) specific imports from any module:

```jsonc
"tsEssentialPlugins.suggestions.ignoreAutoImports": [
    "path/*#resolve,join", // ignore resolve and join from `path` module and any subpaths of it
    "path/win32" // ignore all imports from this module specifically
],
```

https://github.com/microsoft/TypeScript/issues/35395#issuecomment-1239843287, It ensures these two imports will appear on top. For example when running Fix all missing imports quick fix, `lodash-es/isEqual` will be selected.

```jsonc
"tsEssentialPlugins.autoImport.changeSorting": {
    "isEqual": [
        // ensures these two will always be on top even if other libs are installed
        "lodash-es/isEqual",
        "lodash-es"
    ]
}
```

While it should work from quick fix, it doesn't work from autocomplete, because AFAIK reexports takes precedence in autocomplete, I can add a setting for that, but I'm not sure of format that would cover all cases.

</details>

**Comment by GabenGar** [comment] 2023-02-15 05:38
@andrewbranch 
How to use this feature in context of [issue](https://github.com/i18next/next-i18next/issues/1917#issuecomment-1366958378)?
The situation is this:
1. `next-i18next` [imports `useTranslation()` from `react-i18next`](https://github.com/i18next/next-i18next/blob/6a692ae688d4cb5c95bc8ff0a378f12a6a2fe61c/src/types.ts#L4) in its type definitions.
2. Creates a [type alias off it](https://github.com/i18next/next-i18next/blob/6a692ae688d4cb5c95bc8ff0a378f12a6a2fe61c/src/types.ts#L60).
3. Then reexports [`useTranslation()`](https://github.com/i18next/next-i18next/blob/6a692ae688d4cb5c95bc8ff0a378f12a6a2fe61c/src/types.ts#L85).
4. The [index file reexports `useTranslation()` from `react-i18next`](https://github.com/i18next/next-i18next/blob/6a692ae688d4cb5c95bc8ff0a378f12a6a2fe61c/src/index.tsx#L5).
The result of all of this is `next-i18next` doesn't even appear in suggestions for `useTranslation()`. 

Let's say I have this project structure:
```
/project
  - frontend
```
Where `frontend` is the folder with nextjs project (and therefore `next-i18next`).
`project` is where the vscode workspace file is stored, which also defines `project` and `/project/frontend` as multi-roots of the workspace.
I've tried to put this snippet:
```json
{
  "typescript.preferences.autoImportFileExcludePatterns": [
    "/**/node_modules/react-i18next"
  ]
}
```
In `.vscode/settings.json` in either/both of these folders and `react-i18next` is still in the autoimport suggestions. Am I right to assume this feature is not applicable because it's technically the same symbol spread across several files/packages? If so, how to make `next-i18next`  at least appear in suggestions?

**Comment by andrewbranch** [comment] 2023-02-15 16:47
> Am I right to assume this feature is not applicable because it's technically the same symbol spread across several files/packages?

That wasn’t the intention—it’s really just supposed to be individual files that are ignored. It sounds like that could be a bug.

Are `react-i18next` and `next-i18next` both listed as dependencies in your package.json in this case? Re-exports do tend to “shadow” their sources in completions, but I think that behavior should be disabled for cross-package re-exports.

**Comment by GabenGar** [comment] 2023-02-16 10:29
Yes, [the instructions](https://github.com/i18next/next-i18next#1-installation) say to install both of them.

**Comment by andrewbranch** [comment] 2023-02-16 16:31
@GabenGar would you mind opening a new bug to track this? I’ll take a look at both issues you mentioned.

**Comment by GabenGar** [comment] 2023-02-17 09:29
@andrewbranch a bug? Isn't it like at least 3 (potential) bugs?
- Cross-package re-exports of symbols.
  I also noticed it does sometimes show `next-i18next` or `react-i18next` in the autocompletion (but never both), so there might be a race condition involved.
- that new feature of ignoring files/symbols/modules and it might or might not working due to issue above.
- that new feature of ignoring files/symbols/modules and multi-root workspaces.
I think for a start the first issue has to be resolved first, since others are dependent on it.

**Comment by andrewbranch** [comment] 2023-02-17 17:30
I don’t understand what your third bullet point means, but yes, there are two potential bugs. Feel free to open two separate ones if you prefer.

**Comment by andrewbranch** [comment] 2023-02-17 18:32
It resolves relative to the “workspace folder” of the file being edited (`vscode.workspace.getWorkspaceFolder`). I’m not sure what that returns in a multi-root workspace, but it sounds like it would be the directory where the workspace file lives, not the root within the workspace. Which would make the relative paths specified inside individual roots unintuitive.

**Comment by 0x80** [comment] 2023-03-06 09:40
The current implementation doesn't cover nodejs built-in modules, right? The two that are bothering me the most are "assert" and "console", but adding them to the config doesn't seem to have any effect.

I will give the VSCode plugin from @zardoy a try...

**Comment by andrewbranch** [comment] 2023-03-07 16:56
> The current implementation doesn't cover nodejs built-in modules, right?

It does. You just have to specify filenames or globs that cover the file(s) where those ambient modules are declared (whatever shows up in Go To Definition on the module specifier).

Every time someone proposes a very reasonable sounding change to auto-import heuristics, we find that implementing it makes the experience worse for ~50% of people. When “local” modules are given priority, people in really large codebases get mad that `Component` gets auto-imported from `"../../../../../apps/email-templating/external/__mocks/types/flux-capacitor"` when they _obviously_ meant to import from `"react"`. It can definitely be worth revisiting these things from time to time, but my preference is to come up with solutions that don’t make zero-sum trades in sorting/priority.

**Comment by 0x80** [comment] 2023-03-08 05:30
@andrewbranch Awesome. For me, adding `@types/node` fixed my problem 👍

**Comment by 0x80** [comment] 2023-03-18 03:07
... but somehow it doesn't work for "log" coming from the debug module. Vscode points to `"@types/node/debug/index.d.ts"` but including it in the list of exclude patterns has no effect for me.

**Comment by andrewbranch** [comment] 2023-03-20 16:00
That file doesn’t exist in @types/node, so I’m not sure what you’re seeing.

**Comment by 0x80** [comment] 2023-04-02 04:14
@andrewbranch I got confused. It pointed to @types/debug, an external dependency. Everything seems to work fine after all 🎉

**Comment by oviniciusfeitosa** [comment] 2023-09-20 20:43
- Update your `settings.json` file:

```json
"javascript.preferences.autoImportFileExcludePatterns": ["**/node_modules/@types/node/**", "**/node_modules/@types/node/console", "**/node_modules/@types/node/console.d.ts"],
"typescript.preferences.autoImportFileExcludePatterns": ["**/node_modules/@types/node/**", "**/node_modules/@types/node/console", "**/node_modules/@types/node/console.d.ts"],
```

- Then reload your VSCode

**Comment by NazmusSayad** [comment] 2024-01-16 16:29
I wanna exclude all the import suggestions from "data-fns".

```json
{
  "typescript.preferences.autoImportFileExcludePatterns": [
    "date-fns",
    "**/date-fns",
    "**/date-fns/**",
    "**/date-fns/**/*",
    "node_modules/date-fns",
    "**/node_modules/date-fns",
    "**/node_modules/date-fns/**",
    "**/node_modules/date-fns/**/*"
  ],
  "javascript.preferences.autoImportFileExcludePatterns": [
    "date-fns",
    "**/date-fns",
    "**/date-fns/**",
    "**/date-fns/**/*",
    "node_modules/date-fns",
    "**/node_modules/date-fns",
    "**/node_modules/date-fns/**",
    "**/node_modules/date-fns/**/*"
  ]
}
``` 
I have tried these but still not working.

Typescript version: 5.3.2
VSCode version: 1.85.1
OS: Windows

**Comment by andrewbranch** [comment] 2024-01-16 17:18
Currently only workspace-relative paths (starting with `./` or `../`) work on Windows. A fix is in progress.

**Comment by NazmusSayad** [comment] 2024-01-16 17:49
Got it....

After using:

`./**/node_modules/date-fns`

It's working

**Comment by andrewbranch** [comment] 2024-02-06 22:28
`./**/node_modules/@types/node` should do it. Also, leading with `./` shouldn’t be necessary by now if you’re using TypeScript nightly or VS Code Insiders.

**Comment by 188599** [comment] 2024-09-24 11:34
I'm working on an Ionic using Angular's standalone components and they give you the following settings on a newly generated project: 

```json
  "typescript.preferences.autoImportFileExcludePatterns": ["@ionic/angular/common", "@ionic/angular"]
```

But it doesn't seem like it does what is intended, because firstly, the first entry `@ionic/angular/common` is completely useless, since every single import under `@ionic/angular` is excluded, including the imports from `@ionic/angular/standalone` which you'd expect to be allowed, since it's where all the imports you need from their package reside. 

I also found the option `typescript.preferences.autoImportSpecifierExcludeRegexes`, which as per it's description: 
```
Specify regular expressions to exclude auto imports with matching import specifiers. Examples:

^node:
lib/internal (slashes don't need to be escaped...)
/lib\/internal/i (...unless including surrounding slashes for i or u flags)
^lodash$ (only allow subpath imports from lodash)
```
should allow me to exclude the other imports while maintaining `@ionic/angular/standalone` that I need, but it does not seem to work, at all.

**Comment by andrewbranch** [comment] 2024-09-24 16:41
Can you open a new issue following the template with repro steps?

**Comment by 188599** [comment] 2024-09-24 19:10
> Can you open a new issue following the template with repro steps?

As soon as I said that here I saw that there was a new VS Code update, turns out that fixed the issue immediately for `typescript.preferences.autoImportSpecifierExcludeRegexes`. I was gonna say that here but I couldn't find where I posted anymore 😅

**Comment by applemate** [comment] 2025-05-17 06:53
I also have a  suggestion entry I like to be gone forever. Is there way to remove it ?

![Image](https://github.com/user-attachments/assets/b6836dd3-0793-47f9-90c5-b71cd7051128)
