### ISSUE TITLE
Typescript compiler hangs and starts eating memory

### ISSUE THREAD

**Issue by davyvanlaere** [Microsoft/TypeScript#7344] opened 2016-03-02 19:23 UTC
**TypeScript Version:** 
1.8.0-beta

**Code**

        return this.http.request(url, request)
            .catch(initialError => {
                if (initialError && initialError.status === 401 && isSecureCall === true) {
                    // token might be expired, try to refresh token
                    return me.authService.refreshAuthentication().flatMap((authenticationResult:AuthenticationResult) => {
                        if (authenticationResult.IsAuthenticated == true) {
                            // retry with new token
                            me.authService.setAuthorizationHeader(request.headers);
                            return this.http.request(url, request);
                        }
                        return Observable.throw(initialError);
                    });
                }
                else {
                    return Observable.throw(initialError);
                }
            });

**Expected behavior:**

This code has compiled and worked before. (this is a snippet from an angular2 application: if an authenticated request fails because the token has expired, the code tries to use a refresh token to get a new token and retry the request).

**Actual behavior:** 

The compiler starts to hang 

I have stripped down my project to the bare minimum to illustrate the problem. 
To reproduce; clone this repo: 

https://github.com/davyvanlaere/TypescriptCompilerIssue

Then run "npm install", followed by "tsc": the compiler will hang, and the process "Evented I/O for V8 Javascript" will start to eat memory (i let it run for a while and killed it at 1.3gb).

It has something to do with the types of the return statements. If you the replace 2nd "return this.http.request(url, request);" line with "return Observable.throw(initialError);", the compiuler will not hang.

**Comment by vladima** [comment] 2016-03-02 19:48
what version of node do you use?

**Comment by davyvanlaere** [comment] 2016-03-02 19:51
v0.12.0

**Comment by vladima** [comment] 2016-03-02 19:52
can you try to upgrade to node 5 and see if you still see this issue?

**Comment by davyvanlaere** [comment] 2016-03-02 20:03
Just checked with version 4.3.1 (LTS) and 5.7.0 (stable), problem is gone. I apparently had an ancient node version ...

While running tsc, the process still peaks to 800Mb though (seems alot for such a small workload?)

**Comment by vladima** [comment] 2016-03-02 20:06
recent version of `rxjs` have added more complex type definitions so analyzing them takes lots of time - we already have an issue that tracks it.

**Comment by davyvanlaere** [comment] 2016-03-02 20:08
Darn ... the repo builds, but the project it was distilled from still explodes. I'll see if i can isolate the problem again.

**Comment by vladima** [comment] 2016-03-02 20:10
Can you share the actual code so we can be sure that root problem is addressed? We can sign an NDA if necessary.

**Comment by davyvanlaere** [comment] 2016-03-02 20:15
NDA is not necessary, but i prefer not to share it publicly.

**Comment by vladima** [comment] 2016-03-02 20:16
Can you send it to `vladima` @ `microsoft.com`?

**Comment by davyvanlaere** [comment] 2016-03-02 20:46
Sent!

**Comment by msklvsk** [comment] 2016-03-17 20:52
Same here, importing and using `{Observable} from 'rxjs/Observable'` hangs compilation of an angular2 app since rxjs 5.0.0-beta.2

**Comment by msklvsk** [comment] 2016-03-17 20:58
(present in TS 1.8.9, node 5.9.0)

**Comment by vladima** [comment] 2016-03-17 22:40
this is one of a few similar issues that were reported recently (i.e. #7460 and #7344) that originate from the fact that type declarations in rxjs-5.0.0-beta.2 got more complicated and compiler spends lots of time exploring them. This is one of downsides of structural type system - in order to prove that two types are related their whole structure must be examined. We can short-circuit in a few places (https://github.com/Microsoft/TypeScript/pull/7474)  but in general this problem is pretty hard to solve. Luckily it can be addressed on the consumer side - we are following up with RxJS folks to add a fix that should improve the situation (https://github.com/ReactiveX/RxJS/pull/1475)

**Comment by msklvsk** [comment] 2016-03-18 14:02
I forgot to mention that the hang happens on watch-triggered recompile. Initial build succeeds though (~2 sec slower than usual but still succeeds). Is it a known issue or should I post new one concerning successful initial but failed incremental?

**Comment by vladima** [comment] 2016-03-18 14:45
we've seen the similar issue before due to significant increase of memory during type relation check - it  was resolved after I switched to RxJS version that included https://github.com/ReactiveX/RxJS/pull/1475. Given that this PR is already merged in master ( :clap: ) you can try to build RxJS from master and see if it will help in your case. If issue still exist I'd be very curious if I can somehow get your project for repro to make sure that problem is addressed.

**Comment by brian428** [comment] 2016-03-21 18:04
I think part of the issue is that the watch triggers build.dev, which includes clean.dev. So I think the output folder is getting blown away after each change. I'm not sure if it's possible, but ideally the clean would only delete the files (or folders) affected by the change? Or, it might be worth considering whether a clean is actually needed during watch changes? I can see it being desired during startup, but I'm wondering if doing it for each change has more drawbacks than benefits?

**Comment by mhegazy** [comment] 2016-03-29 22:14
Updating to latest RxJS beta should address the issue. please reopen if the issue persists on newer versions of the framework.

**Closed by mhegazy** 2016-03-29 22:14 UTC
Labels: External
