### ISSUE TITLE
Template literal autocomplete not working for parameter objects

### ISSUE THREAD

**Issue by kadiryazici** [microsoft/TypeScript#46605] opened 2021-10-30 21:58 UTC
# Bug Report

### 🔎 Search Terms
typescript cannot get parameter object type when using template literal types

### 🕗 Version & Regression Information

- This is a bug
- I saw this bug when trying to create an object using template literal  as keys by first parameter which is object.

### ⏯ Playground Link
[Link](https://www.typescriptlang.org/pt/play?#code/MYewdgzgLgBCBGArGBeGBvAUDHMwEMBbAUwC4YByAaXwBMBLAJwoBptd8BzMmAJgAZMAX0yYAZgFcwwKPXAwANvWjEwAHgAqMYgA8oq2hAwBtANbEAnuWiN6YTgF1y+MBaEA+ABQJE5DS20AN1UoCHIsXBhjKksYOxgAA3AAEnQbO04YADIYcwsQMRgNIQSHAH5yGIthAEoMURFMAHommAAREBgAYQ0AJQAZGABqGABlAAd8YGI4yHpaGYhiUDBaGEnGImJ9RjgkZdgXNfyJGAB3egUFGCXiZtb8CSgQUEJxhW25MEwlFTBvJABCK4WqiFrtTo9AbDMaTaazCDzRbLcBrDZbHb3GAnc6Xa5gECwbiHVwwR7PGCvd6fcA-ZT6f7oMnccgCGBCIHsHC1IA)

### 💻 Code

```ts
const obj = {
    name: 'Kadir',
    age: 20
}

function listen<T extends {[key: string]: any}>(obj: T, events: {
    [Key in `on${string & keyof T}`]?: Key
}) {

}

// Do CTRL + Space inside second parameter object and you will see
// autocompletion
listen(obj, {
    
})

// Do CTRL + Space inside second parameter
// you will not get any auto completion
listen({ age: 20 }, {
    
})
```

### 🙁 Actual behavior
If object is created in first parameter it won't give autocompletion but will give type errors.

### 🙂 Expected behavior
It should give autocompletion in second parameter object.

**Comment by andrewbranch** [comment] 2021-11-01 17:06
Duplicate of #41620

**Comment by kadiryazici** [comment] 2021-11-01 17:08
@andrewbranch 
![image](https://user-images.githubusercontent.com/47540799/139711314-d65b76de-6bdf-490c-93a3-4a2b0ba10c4e.png)

@andrewbranch 
![image](https://user-images.githubusercontent.com/47540799/139711330-11a885bf-14c4-4833-9cea-2d90f3b59c5f.png)

**Comment by andrewbranch** [comment] 2021-11-01 17:22
@kadiryazici you’re right, thanks for clarifying. This is pretty weird.

**Closed** 2021-11-09 22:50 UTC
Labels: Bug, Help Wanted, Effort: Moderate, Domain: Completion Lists
