### ISSUE TITLE
Object is possibly 'undefined' error when using typed map value in closure

### ISSUE THREAD

**Issue by borisovg** [microsoft/TypeScript#41045] opened 2020-10-11 14:56 UTC
**TypeScript Version:**  4.0.3

**Search Terms:** "Object is possibly 'undefined' map"

**Code**

```ts
type Thing = { data: any };

const things: Map<string, Thing> = new Map();

function add_thing (id: string, data: any) {
    let thing = things.get(id);

    if (typeof thing === 'undefined') {
        thing = { data };
        things.set(id, thing);
    }

    return () => thing.data;
}
```

**Expected behavior:**
No errors - it is not possible for "thing" to be undefined based on the above code.

**Actual behavior:**
Object is possibly 'undefined' error.

If `things` is instead defined as `const things = new Map();` then there is no error.

If it is assigned to another constant like this `const thing2 = thing;` and that is used in the closure then there is also no error.

**Playground Link:** https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgFgSwHYHMoF4oG8oBMCGw+AXFPkiFAL4DcAUHQMYD2SAzsFMIqm6QLL4wAHg4AnZCgA0sHigB8GKEggB3KILAAKAJT06AMwCuSRsASsyuXAH1ukqFoS5S4yTIJFS5EDux0oQKgAGwhOe1QlCJQ2ADoUMKdcPQYgqAQDR1BIZkzojHRMAHITXAgDZAhcIr8sALSg-MwcT3xqegbGuTi2ROcZaJS0qlSgsTCjMSRHP3RFaNjW+iogA

**Related Issues:** #7719

**Comment by MartinJohns** [comment] 2020-10-11 15:00
Duplicate of #9998.

Quick workaround: Store it in a new const variable:

    const cthing = thing;
    return () => cthing.data;

**Comment by borisovg** [comment] 2020-10-11 15:04
@MartinJohns thanks I am aware of this workaround - edited the description.

**Comment by MartinJohns** [comment] 2020-10-11 15:07
It's still a duplicate of #9998. :-)

> If `things` is instead defined as `const things = new Map();` then there is no error.

If you declare it like this, then the type is inferred to be `Map<any, any>`. As a result the type of `thing` is `any`, and you opted out of all type-safety checks. That's why you don't get an error in this case.

**Comment by MartinJohns** [comment] 2020-10-11 15:14
Another **nasty** workaround:

    const thing = things.get(id) ?? (things.set(id, { data }), things.get(id)!);

    return () => thing.data;

(Please don't use this.)

**Comment by borisovg** [comment] 2020-10-11 15:19
I guess my objection to 9998 is the "discussion" label there when this is clearly a bug IMHO. That and my example looks way more RWC to me than the code in that ticket, although I did simplify it a bit for brevity. ;-)

**Comment by borisovg** [comment] 2020-10-11 15:34
The least ugly workaround seems to be this: `return () => thing!.data;`

**Comment by whzx5byb** [comment] 2020-10-11 17:03
That's why we need [Map.prototype.emplace](https://github.com/tc39/proposal-upsert). You might consider using a polyfill of it.

```
function add_thing (id: string, data: any) {
    return things.emplace(id, {insert: () => ({ data })});
}
```

**Closed** 2020-10-14 18:00 UTC
Labels: Duplicate

**Comment by jerome022** [comment] 2022-04-09 15:33
This should work without the need of a new const
`return () => thing!.data;`

**Comment by shamil8** [comment] 2022-04-29 06:21
I would do like this:
`
interface IMap<K, V> extends Map<K, V> {
  get(key: K): V;
}

type Thing = { data: any };

const things: IMap<string, Thing> = new Map();
`
