### ISSUE TITLE
Add support for defining: string - 'a' (string minus string literal type)

### ISSUE THREAD

**Issue by wallverb** [Microsoft/TypeScript#12182] opened 2016-11-11 20:47 UTC
https://github.com/Microsoft/TypeScript/pull/11587 allows us to do this:

```ts
function test(a: 'a' | string) {
    if (a == 'a') { 
        a // <- type: 'a'
    }
}
```

It would be great if the following could also work:

```ts
type Z = {type:'a',a:string}|{type:string,b:string}
function test(a: Z) {
    if (a.type == 'a') { 
        a // <- type: Z but ideally if it could be {type:'a',a:string}
    }
}
```

**Comment by ahejlsberg** [comment] 2016-11-11 21:52
The proposed narrowing of `Z` wouldn't be correct because a `{ type: string, b: string }` could very well have `type` property with the value `'a'`. The only way it would be correct is if you could somehow express a type `string - 'a'` (i.e. a string with any value but `'a'`), but we don't have that capability.

BTW, #11587 is about narrowing `string` to a literal type, not about narrowing something like `'a' | string`. In general it is not meaningful to have types like `'a' | string` because it is really the same as just `string` and the compiler will reduce it to that the minute it performs subtype reduction.

**Comment by wallverb** [comment] 2016-11-12 00:42
@ahejlsberg Thanks for the response.

I wonder if we could say that `'a'` should take precedence over `string` in case of `Z`, but if not then

`string - 'a'` would solve our use case - so I renamed that title to reflect this feature - but if you feel it's Out of scope - feel free to close it.

We are trying to migrate Redux actions/reducers to `TS` and such a `catch-all` action would be very useful, for example:

```ts
interface AddToDo {
  type: 'addToDo'
  data: {
     name: string
     completed: boolean
  }
}
// ... - other actions

interface CatchAll {
  type: string  // `string - 'addToDo'` would help here
  data: any
}

type Actions = AddToDo | CatchAll

function reduce(action: Actions) {
  switch (action.type) {
     case 'addToDo': 
          action // type: Actions -> ideally: AddToDo
     break; 

    /// any other actions
    case 'someOtherAction':
       action // type: Actions -> ideally: CatchAll
    break;
  }
}
```

Thanks

**Comment by aluanhaddad** [comment] 2016-11-12 05:28
@wallverb That is somewhat strange because the "any other actions" case doesn't do what it says. It only handles values that are tagged with `'someOtherAction'`. If all other values are always so tagged, then using that tag as the literal type of `CatchAll.type` correctly describes the behavior of `reduce`.

**Comment by wallverb** [comment] 2016-11-12 13:57
@aluanhaddad Sorry if my example was not clear enough - I updated. The thing is that there are hundreds of such redux actions that don't have any type defined for them and only handful of actions (like AddToDo) that do have them.
Having something like this:

```ts
type DefinedActionTypes = 'addToDo' | 'removeToDo' // | .....
type UndefinedActionTypes = string - DefinedActions

interface CatchAll {
  type: UndefiendActionTypes
  data: any
}
```

would allow to achieve that (to narrow to `CatchAll`), but I understand if that would be Out of Scope / no interest by anyone else

**Comment by aluanhaddad** [comment] 2016-11-12 15:45
@wallverb What I mean is that you need to handle that in the `default` clause. If they actually have no union tag at runtime, you can write
```ts
interface CatchAll {
  type: undefined
  data: any
}
```
and type narrowing will actually work with `case` (if you are using `--strictNullChecks` then `undefined` is incompatible with `string`).

**Comment by mhegazy** [comment] 2016-11-14 19:33
seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/7993

**Closed by mhegazy** 2016-11-14 19:33 UTC
