### ISSUE TITLE
RecursiveReadonly and RecursivePartial

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#18591] opened 2017-09-20 08:45 UTC
Suggestion to add types to lib.d.ts:

```ts
type RecursiveReadonly<T> = {
	readonly [P in keyof T]: RecursiveReadonly<T[P]>;
};

type RecursivePartial<T> = {
    [P in keyof T]?: RecursivePartial<T[P]>;
};
```

Difference from Readonly and Partial
```ts
type ComplexType = { a: { b: { c: { d: number; } } } };

const x:Readonly<ComplexType> = {
    a: { b: { c: { d: 1 } } }
};
const xx: RecursiveReadonly<ComplexType> = {
    a: { b: { c: { d: 1 } } }
};
x.a.b.c.d = 3;
//xx.a.b.c.d = 3; // Error

const y:Partial<ComplexType> = {};
const yy: RecursivePartial<ComplexType> = {};

//y.a = {};// Error
yy.a = {}; // OK
```

[Playground](http://www.typescriptlang.org/play/#src=%0D%0Atype%20RecursiveReadonly%3CT%3E%20%3D%20{%0D%0A%09readonly%20[P%20in%20keyof%20T]%3A%20RecursiveReadonly%3CT[P]%3E%3B%0D%0A}%3B%0D%0A%0D%0Atype%20ComplexType%20%3D%20{%20a%3A%20{%20b%3A%20{%20c%3A%20{%20d%3A%20number%3B%20}%20}%20}%20}%3B%0D%0A%0D%0Aconst%20x%3AReadonly%3CComplexType%3E%20%3D%20{%0D%0A%20a%3A%20{%20b%3A%20{%20c%3A%20{%20d%3A%201%20}%20}%20}%0D%0A}%3B%0D%0Aconst%20xx%3A%20RecursiveReadonly%3CComplexType%3E%20%3D%20{%0D%0A%20a%3A%20{%20b%3A%20{%20c%3A%20{%20d%3A%201%20}%20}%20}%0D%0A}%3B%0D%0Ax.a.b.c.d%20%3D%203%3B%0D%0A%2F%2Fxx.a.b.c.d%20%3D%203%3B%20%2F%2F%20Error%0D%0A%0D%0A%0D%0Atype%20RecursivePartial%3CT%3E%20%3D%20{%0D%0A%20[P%20in%20keyof%20T]%3F%3A%20RecursivePartial%3CT[P]%3E%3B%0D%0A}%3B%0D%0A%0D%0Aconst%20y%3APartial%3CComplexType%3E%20%3D%20{}%3B%0D%0Aconst%20yy%3A%20RecursivePartial%3CComplexType%3E%20%3D%20{}%3B%0D%0A%0D%0A%2F%2Fy.a%20%3D%20{}%3B%2F%2F%20Error%0D%0Ayy.a%20%3D%20{}%3B%20%2F%2F%20OK)

**Comment by kitsonk** [comment] 2017-09-20 10:14
Duplicate of #13923

**Closed** 2017-09-20 10:19 UTC
