### ISSUE TITLE
Default type parameters are required

### ISSUE THREAD

**Issue by leonard-thieu** [Microsoft/TypeScript#16601] opened 2017-06-17 16:38 UTC
**TypeScript Version:**  2.3.4

**Code**

From https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17239:

```
Error - typescript - node_modules@types\jquery\index.d.ts(4306,101): error TS2304: Cannot find name 'any'.
Error - typescript - node_modules@types\jquery\index.d.ts(4455,36): error TS2314: Generic type 'Deferred<TResolve, TReject, any, TNotify>' requires 4 type argument(s).
Error - typescript - node_modules@types\jquery\index.d.ts(4456,36): error TS2314: Generic type 'Event<TTarget, EventTarget, TData>' requires 3 type argument(s).
Error - typescript - node_modules@types\jquery\index.d.ts(4457,41): error TS2314: Generic type 'Event<TTarget, EventTarget, TData>' requires 3 type argument(s).
Error - typescript - node_modules@types\jquery\index.d.ts(4458,36): error TS2314: Generic type 'Deferred<TResolve, TReject, any, TNotify>' requires 4 type argument(s).
Error - typescript - node_modules@types\jquery\index.d.ts(4459,37): error TS2314: Generic type 'AjaxSettings<TContext, any>' requires 2 type argument(s).
Error - typescript - node_modules@types\jquery\index.d.ts(4461,43): error TS2694: Namespace 'JQuery' has no exported member 'Coordinates'.
Error - typescript - node_modules@types\jquery\index.d.ts(4463,28): error TS2314: Generic type 'jqXHR<TResolve, any>' requires 2 type argument(s).
Error - typescript - node_modules@types\jquery\index.d.ts(4464,35): error TS2314: Generic type 'Promise<TResolve, TReject, any, TNotify>' requires 4 type argument(s).
Error - typescript - node_modules@types\jquery\index.d.ts(4465,53): error TS2694: Namespace 'JQuery' has no exported member 'NameValuePair'.
```

Line [4306](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/32a5f7521a07b28fa92e64ea0b6d4342e97a9e30/types/jquery/index.d.ts#L4306):
```typescript
interface EventHandler<TContext, TData = null> {
```
Lines [4455-4466](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/32a5f7521a07b28fa92e64ea0b6d4342e97a9e30/types/jquery/index.d.ts#L4455):
```typescript
interface JQueryCallback extends JQuery.Callbacks { }
interface JQueryDeferred<T> extends JQuery.Deferred<T> { }
interface JQueryEventObject extends JQuery.Event<HTMLElement> { }
interface JQueryEventConstructor extends JQuery.Event<EventTarget> { }
interface JQueryDeferred<T> extends JQuery.Deferred<T> { }
interface JQueryAjaxSettings extends JQuery.AjaxSettings { }
interface JQueryAnimationOptions extends JQuery.EffectsOptions<Element> { }
interface JQueryCoordinates extends JQuery.Coordinates { }
interface JQueryGenericPromise<T> extends JQuery.Thenable<T> { }
interface JQueryXHR extends JQuery.jqXHR { }
interface JQueryPromise<T> extends JQuery.Promise<T> { }
interface JQuerySerializeArrayElement extends JQuery.NameValuePair { }
```
All of the generic types mentioned in the error log have at least 1 default type parameter (and 1 less parameter than indicated).

`Deferred`'s declaration for example:
```typescript
interface Deferred<TResolve, TReject = any, TNotify = any> {
```

I haven't been able to reproduce this myself. 

**Expected behavior:**
No error when omitting arguments for type parameters with defaults.

**Actual behavior:**
Error requiring arguments for all parameters plus one.

**Comment by rbuckton** [comment] 2017-06-21 22:34
@leonard-thieu Is this still an issue? https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17239#issuecomment-309479776 seems to indicate that the issue was due to the jQuery declaration taking a dependency on Iterable. 

The steps provided do not form an adequate repro for this issue, and I am unable to reproduce this locally. I'm closing this for now.

**Closed by rbuckton** 2017-06-21 22:34 UTC
Labels: Bug

**Comment by leonard-thieu** [comment] 2017-06-21 22:43
I believe Iterable is a different issue than this one.

No one that reported the generic parameter issue responded with more info. I'm leaning towards it being a version mismatch despite people reporting that they're using TypeScript 2.3.4.
