### ISSUE TITLE
Failure to narrow conditional type after guard

### ISSUE THREAD

**Issue by schuelermine** [microsoft/TypeScript#47168] opened 2021-12-16 10:59 UTC
# Bug Report

### 🔎 Search Terms

conditional type guard

### 🕗 Version & Regression Information

This seems to not be a regression at all.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211216#code/C4TwDgpgBAGgPAFQHxQLxQIKJQHygIWwChRJNs0oBvUiALigCIBDRgGigDdmAbAV3pQEAXxLhohZJRriGjAEbsuvAQxFiyAJURsAmlAgAPYBAB2AEwDOsbCnT6jJi9ckoA-EKgNOAewCW5kQAZnymAMbAfj6mUEE6DsZmVjbISAAUIAy6AJQM2gh6KFREUKVQfkFQGQB0tGio6AqM2dQlZe0AThDAfB0xINXc-BBtpcIGPJbQXT19RKJAA)

### 💻 Code

```ts
type X<T> = A<T> | B<T>
type A<T> = {type: "a", value: T}
type B<T> = {type: "b", value: T}
type R<T,Y extends X<T>> = Y extends B<T> ? T : void
function f<T,Y extends X<T>>(y: Y): R<T,Y> {
    if (y.type === "b") {
        return y.value
    } else return
}
```

### 🙁 Actual behavior

TS complains about `y.value` and `else return`.

### 🙂 Expected behavior

They should be accepted.

**Comment by jcalz** [comment] 2021-12-16 18:04
Duplicate of #33912

**Closed** 2022-01-06 18:00 UTC
Labels: Duplicate
