### ISSUE TITLE
allowJs duplicate identifier error

### ISSUE THREAD

**Issue by erikcharlebois** [Microsoft/TypeScript#6792] opened 2016-02-01 19:32 UTC
Tried using allowJs with a minified version of google analytics and ran into some duplicate identifier errors. Cut down testcase:

```js
function bar(a) {                                                                
  if (a)                                                                         
    this.x = 1;                                                                  
  else                                                                           
    this.x = 1;                                                                  
                                                                                 
  // This also fails and is closer to the actual minified GA version.                                                      
  // a ? (this.x = 1) : (this.x = 1);                                            
} 
```

```cmd
tsc --allowJs pretty.js --out foo.js
pretty.js(3,5): error TS2300: Duplicate identifier 'x'.
pretty.js(5,5): error TS2300: Duplicate identifier 'x'.
```

**Comment by vladima** [comment] 2016-02-01 19:49
looks like a dupe of #6645

**Comment by mhegazy** [comment] 2016-02-01 19:49
#6645

**Comment by mhegazy** [comment] 2016-02-01 19:49
:). thanks @vladima

**Closed by mhegazy** 2016-02-01 19:49 UTC
Labels: Bug, Duplicate
