### ISSUE TITLE
Switch multiple conditions type error

### ISSUE THREAD

**Issue by Fi1osof** [microsoft/TypeScript#50386] opened 2022-08-21 04:20 UTC
# Bug Report

### 🔎 Search Terms
switch undefined 

### 🕗 Version & Regression Information

6.4 ~ 4.7.4 (latest)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAysCGxoF4oG8BQVtQGYHt8AuKAZ2ACcBLAOwHMMBfDDAGwmDISRLkWgA+UAK40AJhFy0IYgNwt2nChFLDWwEgCNC7eDSipc8VqQjyMVXFAAU5fgEp0LHF34A6AvgPJUAIlJiuGKkuL5YOKQA7lTAAMYAFjaUwhCOmOEu2LHwpq5IHoTeqADkSOTFRBmZ2bl2+Z5FUKUqwBVVmTjKquoGUMlm7R1QmsrwANbmQ1A10HUQBV4+JWWtlVMzefMNS00rbVMuXWqcqP3yBzgjEOOTQxtzUABkj5sLjc3la3c5s9xbhTsPqtBh0jj1ThQUucLsNRhNnN9an8oAB+V7bHy7FrFKAkIwmCBfDr3P5vQF7IkHMEnPqQgYw2HXeFVZhMDBAA)

### 💻 Code

```ts
type State = {
    foo: string
}

let state: State | undefined;

let result: boolean = false;

if (state) {

    state.foo === "sdfdsf"
    switch (true) {

        case state.foo === 'test':
        case state.foo === 'test':
            result = true;
            break;

        // Object is possibly 'undefined'.ts(2532)
        case state.foo === 'test':
        case state.foo === 'test':
            result = true;
            break;

        // Object is possibly 'undefined'.ts(2532)
        case state && state.foo === 'test':
        case state.foo === 'test':
            result = true;
            break;

        // Object is possibly 'undefined'.ts(2532)
        case state ? state.foo === 'test' : false:
        case state.foo === 'test':
            result = true;
            break;

    }

}

```

### 🙁 Actual behavior

Error Object is possibly 'undefined'.ts(2532)

### 🙂 Expected behavior

No error

**Comment by MartinJohns** [comment] 2022-08-21 06:45
Duplicate of #37178.

**Closed** 2022-08-28 18:00 UTC
Labels: Duplicate
