### ISSUE TITLE
The `: never` function, does not recognize another `: never` function it its body

### ISSUE THREAD

**Issue by parzh** [Microsoft/TypeScript#17408] opened 2017-07-25 19:38 UTC
**TypeScript Version:**  2.4.1

**Code**

```ts
function foo(): never {
  throw new Error();
}


function bar(): never {
  foo(); // there's no reachable end point here
}
```

**Expected behavior:**
No compiler errors / warnings, since type annotation is present on function `foo`

**Actual behavior:**
Compiler: `[ts] A function returning 'never' cannot have a reachable end point.`

**Comment by RyanCavanaugh** [comment] 2017-07-25 20:02
Duplicate of #14735 and its related issues

**Closed** 2017-07-25 20:10 UTC
