### ISSUE TITLE
Incorrect quick info when variable and exported interface have the same name

### ISSUE THREAD

**Issue by robpalme** [microsoft/TypeScript#41897] opened 2020-12-09 13:04 UTC
**TypeScript Version:**  4.2.0-dev.20201209 (but this bug is not a regression)

**Search Terms:** export interface any

**Code**

```ts
const X = 1;   // X is any 😞
export interface X {}

// uncomment this line and X becomes type 1 🙂
// export type { X }
```

**Expected behavior:**

Type information should be retained.  The atomic declaration `export interface` should behave the same as declaring an interface and then exporting it on another line.

**Actual behavior:**

Type information is lost - `X` becomes `any`.  `export interface` has an unwanted side-effect on the typing.  `export interface` does not behave the same as splitting the type declaration and the export out into two operations.

**Playground Link:** [Bug repro](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201209#code/FAehAIEYDpwCQPYDcCmAncz3gC4AsBLAZ3AA1wBacIlFXATwAc7jwBDAO3oEJgBjBByI4y4ALxQA3MGAoAHowRoRBDjnQAzNnzrkA3gF8ZYcACZYAVQ4CAtjZRrchEgBtVdTgBNweLBj+ibADmbKqU1LQMzOCskKAQ8orKUXR6ogZAA)

**Related Issues:** None found - but it is really hard to search for this bug.

The workaround for this issue is simple:  declare the interface without exporting it, and then export it on a separate line.  But this is unintuitive dark magic.  It would be better to just fix this.

**Comment by RyanCavanaugh** [comment] 2020-12-09 18:28
This is just a quickinfo bug; it's not actually `any`

![image](https://user-images.githubusercontent.com/6685088/101671423-5465b380-3a09-11eb-8133-18248f239be4.png)

**Comment by a-tarasyuk** [comment] 2020-12-10 15:17
@DanielRosenwasser I think this issue is a duplicate of https://github.com/microsoft/TypeScript/issues/32839. It is still not clear how to properly solve this problem. Should TS throw an error?https://github.com/microsoft/TypeScript/issues/32839#issuecomment-584342224? Or https://github.com/microsoft/TypeScript/issues/32839#issuecomment-584307160?

/cc @DanielRosenwasser @weswigham

**Comment by robpalme** [comment] 2020-12-10 18:57
Given the type-only export (`export type { X }`) works today, it would be mildly sad to make `export interface` error, given that it too can be inherently viewed as another form of type-only export.

Part of the sadness is that it would break our codebase.

**Closed** 2023-02-01 00:42 UTC
Labels: Bug, Domain: Quick Info
