### ISSUE TITLE
checkJs: "implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer." on class property that is reassigned (with noImplicitAny, checkJs, and jsdoc annotations)

### ISSUE THREAD

**Issue by henrahmagix** [microsoft/TypeScript#37893] opened 2020-04-10 16:59 UTC
**TypeScript Version:**  3.9.0-dev.20200408

**Search Terms:**
- implicitly has type 'any' because it does not have a type annotation
- referenced directly or indirectly in its own initializer
- noImplicitAny
- checkJs

**Code**

Note: this problem only occurs when `this.filepath` is assigned to itself (with or without modification). The problem only goes away when not reassigning to `this.filepath` anywhere in the class.

```js
export class ShowTheBug {
  /**
   * @param {object} opts
   * @param {function} opts.someFunc
   * @param {string} opts.filepath
   */
  constructor({
    someFunc,
    filepath,
  }) {
    this.someFunc = someFunc;
    this.filepath = filepath; // error on this line
  }

  reassign() {
    this.filepath = this.filepath.replace('whatever', window.location.href);
  }
}
```

**Expected behavior:**
- destructured `filepath` is annotated as `string`
- `this.filepath` is annotated as `string`

**Actual behavior:**
- destructured `filepath` is annotated as `string` (🥰)
- `this.filepath` is annotated as `any` (😫) even though it's being assigned a `string`, and causes a `noImplicitAny` problem.

`.replace()` is a known method of `string`, so I think `this.filepath` should be typed as `string`.

This problem also continues through an intermediary variable.

**Playground Link:** [reproduced with language set to JavaScript](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200408&ssl=1&ssc=1&pln=19&pc=1&useJavaScript=true#code/KYDwDg9gTgLgBAYwDYEMDOa4GUAWEDuAKjsAEICuA5nAN4BQccA9AFQsOMtwACYKUKALa0IAIwBWwBDAC+cCGBhoOcLr35DaAM3IA7aQEsIuuQqUA6NBEHAAYnoQq1fAcJpoYUA7sqnFacy0DJGA+GBwnJg4EYw8ocmloAAp6RkYrG3t9ABoVOCCQsJxcxhkASlo88IMAjLsHOABeODqshABuKpwawODQlHCm-L6i9uYmOGAoKGh5XThqzCRvYA4ZOg4oYHQ0A0pdJIrUtMXewoGcIdOC-vDzLbBUBGAkgHJ8HAHgADcp1+y4PhvAATAjmJAQBADIy6cw4LZaMqdUp0GRAA).

**Related Issues:** https://github.com/microsoft/TypeScript/issues/23284

### Reported types
<img width="606" alt="Screenshot 2020-04-10 at 17 39 11" src="https://user-images.githubusercontent.com/1429026/79007067-4eee5b80-7b52-11ea-8b15-66bfd11ffb86.png">

![image](https://user-images.githubusercontent.com/1429026/79007244-aab8e480-7b52-11ea-8650-d61deca6b55a.png)

### Intermediary variable example
![image](https://user-images.githubusercontent.com/1429026/79008082-82ca8080-7b54-11ea-90c4-158c411d9a72.png)
![image](https://user-images.githubusercontent.com/1429026/79008136-a097e580-7b54-11ea-8b97-bd3153be2f18.png)

**Comment by DanielRosenwasser** [comment] 2020-04-10 23:23
Duplicate of #35099

**Comment by DanielRosenwasser** [comment] 2020-04-10 23:47
Should be fixed in tomorrow's nightly - you can try it out in VS Code with https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next

**Comment by DanielRosenwasser** [comment] 2020-04-10 23:47
or `npm install typescript@next`

**Comment by henrahmagix** [comment] 2020-04-11 14:13
Thanks @DanielRosenwasser! Sorry about not finding that duplicate issue, thanks for getting it fixed so quickly =)

**Comment by henrahmagix** [comment] 2020-04-12 12:41
@DanielRosenwasser yup, I can confirm it's working correctly in the latest nightly `v3.9.0-dev.20200411` – thanks! 

I look forward to it being released, no rush =)

**Comment by DanielRosenwasser** [comment] 2020-04-12 21:59
No prob, have a great weekend!

**Closed** 2020-04-15 18:00 UTC
Labels: Duplicate
