### ISSUE TITLE
Semantic types

### ISSUE THREAD

**Issue by mixtur** [microsoft/TypeScript#49806] opened 2022-07-06 11:28 UTC
# Suggestion

Support semantic types.

Semantic types are type aliases that are not assignment-compatible with another semantic types even if their definitions are the same.

## 🔍 Search Terms

Semantic, validated.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

```typescript
semantic type USD = number;
semantic type EUR = number;

let a: USD = 1;
let b: EUR = 2;
a = b; // type error

//or 

semantic type Inches = number;
semantic type Meters = number;
let c: Inches = 1;
let d: Meters = 2;
a = b; // type error
```

## 💻 Use Cases

Currency, measurement units, normalized/general vectors or quaternions.

There is a userland library called validated-types ([github](https://github.com/pksilen/validated-types), [blog post](https://betterprogramming.pub/understanding-semantic-and-validated-types-in-typescript-4-54ce43d7d90f)) made with similar intentions, but from the looks of it, it adds runtime overhead, which could be avoided if the feature was in the language.

**Comment by MartinJohns** [comment] 2022-07-06 11:52
Duplicate of #202.

**Closed** 2022-07-09 18:00 UTC
Labels: Duplicate
