### ISSUE TITLE
Function overloading - obscure logic

### ISSUE THREAD

**Issue by evil-shrike** [Microsoft/TypeScript#22231] opened 2018-02-28 16:25 UTC
I have a variable of a union type (A or B). I have a function with overloads for A and for B.
It seems definitely sensible to allow passing this variable to the function. But TS fails on compilation.

```ts
interface A { foo: string };
interface B { bar: string };
let value: A | B;

function test(obj: A): boolean;
function test(obj: B): boolean;
function test(obj) { return true; }

test(value);
```

See [Playground](https://www.typescriptlang.org/play/index.html#src=interface%20A%20%7B%20foo%3A%20string%20%7D%3B%0D%0Ainterface%20B%20%7B%20bar%3A%20string%20%7D%3B%0D%0Alet%20value%3A%20A%20%7C%20B%3B%0D%0A%0D%0Afunction%20test(obj%3A%20A)%3A%20boolean%3B%0D%0Afunction%20test(obj%3A%20B)%3A%20boolean%3B%0D%0Afunction%20test(obj)%20%7B%20return%20true%3B%20%7D%0D%0A%0D%0Atest(value)%3B%0D%0A)

**Expected behavior**:
No compile errors.

**Actual behavior**:
```
lib.ts(28,6): error TS2345: Argument of type 'A | B' is not assignable to parameter of type 'B'.
  Type 'A' is not assignable to type 'B'.
    Property 'bar' is missing in type 'A'.
```

I didn't test on all versions but I guess it doesn't depend on particular version as it's failing in the Playground.

I understand that instead of using overloads I can create a function with union type for argument:
```
function test(obj: A | B): boolean;
```
but in my case it's not acceptable. Actually the provided code is a simplified example of bigger problem.
I have a component with an option which type is `string[] | Map<string>` where Map is 
```
export interface Map<T> {
	[key: string]: T;
}
```
I need to pass this option to a function from Undescore like these ones:
```
contains<T>(list: _.List<T>, value: T): boolean;
contains<T>(object: _.Dictionary<T>, value: T): boolean;
```

**Comment by s-ve** [comment] 2018-02-28 16:30
Duplicate of #14107 ?

**Comment by evil-shrike** [comment] 2018-02-28 16:47
@s-ve yes, I guess so

**Closed** 2018-02-28 17:00 UTC
Labels: Duplicate
