### ISSUE TITLE
File extensions in import autocomplete suggestions

### ISSUE THREAD

**Issue by a-ejs** [microsoft/TypeScript#42157] opened 2020-12-30 13:52 UTC
vscode 1.52.1

With `javascript.preferences.importModuleSpecifierEnding` set to `"js"`:

Given a file `./foo.js` that exports `foo`, typing

```js
import foo from "./
```

brings up a suggestion for `./foo`, without the extension.

In contrast, simply typing `foo` and letting auto import do the work correctly adds

```js
import foo from "./foo.js";
```

at the top of the file, respecting the setting value.

This seems odd, especially considering that in most cases with ES modules specifying the extension isn't optional.

---

Also: if `foo` has `mjs` extension, it's not suggested at all (#27957). However its exports still appear as auto import suggestions, and selecting them does nothing (besides producing an 'unknown extension' error).

**Comment by andrewbranch** [comment] 2020-12-30 21:21
This seems reasonable to me, looks like we’d want to pass the `preferences` in stringCompletions.ts all the way down into `getCompletionEntriesForRelativeModules` and use that preference in the `getExtensionOptions()` call.

**Comment by andrewbranch** [comment] 2021-01-04 18:41
Duplicate of #39155

**Closed** 2021-01-07 18:00 UTC
Labels: Duplicate
