### ISSUE TITLE
nested generic function inference causes unbound type parameter leak

### ISSUE THREAD

**Issue by tjjfvi** [microsoft/TypeScript#55467] opened 2023-08-22 18:05 UTC
### 🔎 Search Terms

unbound generic, unbound type parameter

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ.

### ⏯ Playground Link

https://www.typescriptlang.org/play?jsx=0#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwHcYoAHAHgA0A+ACgA8AueCgSiYG95Hn4BfAKFCRYCFOmx54YKBAhkAgvBB0MIVMADO8KKgCeAbQC6AGngAVWt07caAOnuwA5hqbyW8ALxVzfU-dtOLvBuTGb8-GB4GhjwECBQANaeUjIQNESkNGQW9KHuXlwspgCMLPwA9OXw1fAAegD8-EA

### 💻 Code

```ts
declare function wrap<X>(x: X): { x: X }
declare function call<A extends any[], T>(x: { x: (...args: A) => T }, ...args: A): T

const leak = call(wrap(<T>(x: T) => x), 1)
//    ^? - const leak: A[0]
```

### 🙁 Actual behavior

The type of `leak` involves an unbound type parameter.

### 🙂 Expected behavior

The type of `leak` should be `number`.

**Comment by fatcerberus** [comment] 2023-08-22 21:51
This is like the third or fourth bug I’ve seen recently involving an unbound type parameter escaping from a generic.  I wonder if they all have the same root cause…

**Comment by rotu** [comment] 2024-01-26 01:05
> This is like the third or fourth bug I’ve seen recently involving an unbound type parameter escaping from a generic. I wonder if they all have the same root cause…

I found it to happen from how TypeScript treats `for-of` syntax. https://github.com/microsoft/TypeScript/issues/38388#issuecomment-1911247065

**Comment by weswigham** [comment] 2024-02-13 23:48
@Andarist is right, there's a lot going wrong here to make this leak happen, though the particulars of how a specific inference is chosen don't matter *too* much.

1. We should outright discard inferences of the form `[T[0]]` for `T` - all that means is "T's first element is T's first element" which is a tautological inference.
2. Even with that in place, thanks to the inference from the unbound type parameter we carry through, we have a type parameter inference result that references a previously inferred type parameter. That's fine for defaults - we just instantiate at time of inference, but not currently for actual inference results. This is pretty trivially fixable - just move the backreference mapper instantiation we do for type parameter defaults down a few lines so we always do it.
3. But even once we start doing *that*, we reveal *another* problem - the instantiation makes the call return type resolve as expected, but now the argument type is still something referencing `A[0]` instead of `number` - so signature argument assignability fails - easy enough to fix, just instantiate the expression type with the signature mapper (since the signature's type parameters can appear in the expression thanks to unbound type parameter inference nowadays).
4. And then once you start making *that* instantiation, you notice _it does nothing_ because of a bug in `couldContainTypeVariables` (or rather, in type construction that affects it) - the isolated signature type _has no symbol after being instantiated to `(x: A[0]) => A[0]`_, and so is considered as "not possibly containing type parameters", which is patently false. This is because `getOrCreateTypeFromSignature` currently makes its types without a symbol, which is a bug. Easy to fix on the surface, and fixing it probably fixes a handful of other leaks elsewhere.
5. Unfortunately, fixing that actually turns out to be pretty complicated - adding a symbol and a declaration to the type is easy enough, but making it so anonymous type instantiation machinery can find the right type parameters to instantiate - that's another story entirely! Since we're trying to instantiate a signature type we constructed from basically nothing (an arrow expression and some context), the list of what outer type parameters it can refer to is _also_ constructed, and needs to be the context signature's type argument list (as any of them may be referenced by the expression via inference). Believe it or not, we do *not* have machinery to allow this yet!

I'm working on something that hits up all those points at #57403, but it'll take a bit to find a place for the fix to land that doesn't break anything, particularly with regards to instantiation changes.

**Comment by Andarist** [comment] 2024-02-14 00:00
@weswigham funny enough i was also looking at https://github.com/microsoft/TypeScript/issues/43961 over the weekend and discovered exactly what u mention here from the point 3 to 5, I had to pause the investigation before I managed to work around the point 5 😅 it’s worth adding a test case based on that extra issue into ur PR unless it turns out to add another layer of complexity to this that should be fixed later

**Closed** 2024-03-27 16:57 UTC
Labels: Bug, Fix Available
