### ISSUE TITLE
private modifier for constructor

### ISSUE THREAD

**Issue by dipacs** [Microsoft/TypeScript#5539] opened 2015-11-05 08:06 UTC
Sometimes the private modifier on the constructor can be useful, especially if you want to implement some kind of singletons.

**Comment by kitsonk** [comment] 2015-11-05 08:15
What would the emit look like for this?  Sounds like it would clearly break/not be compatible with ES6 classes.  What would  be the proposed behaviour on `new`?  If you were creating a singleton, why not just an object literal using the ES6 notation?

```typescript
const mySingleton = {
  foo() { console.log() }
};
```

**Comment by DanielRosenwasser** [comment] 2015-11-05 08:29
Duplicate of #2341.

**Closed by DanielRosenwasser** 2015-11-05 08:29 UTC
Labels: Duplicate
