### ISSUE TITLE
Error: No Project. in 'Object.ThrowNoProject' during 'navtree'

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#21794] opened 2018-02-09 01:19 UTC
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.1
**VSCode Version** 1.19.3
**command requested**: navtree
**hitting sessions**: 1400
**proportion of all sessions**: 0.005226357266316501
**stack**
```
Error: No Project.
    at Object.ThrowNoProject (tsserver.js:84217:23)
    at ScriptInfo.getDefaultProject (tsserver.js:84825:46)
    at ProjectService.getDefaultProjectForFile (tsserver.js:87397:39)
    at IOSession.Session.getFileAndLanguageServiceForSyntacticOperation (tsserver.js:89761:92)
    at IOSession.Session.getNavigationTree (tsserver.js:90089:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89106:61)
    at unknown (tsserver.js:90393:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90384:28)
    at IOSession.Session.executeCommand (tsserver.js:90393:33)
    at IOSession.Session.onMessage (tsserver.js:90413:35)
    at Interface.<anonymous> (tsserver.js:91614:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mhegazy** [comment] 2018-02-09 18:04
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/20629

**Closed by mhegazy** 2018-02-09 18:04 UTC
Labels: Bug, Source: Telemetry

**Comment by aozgaa** [comment] 2018-03-05 05:00
This issue reproduced in the following context:
**TypeScript Version Prefix**: 2.7.2
**VSCode Version** 1.21.0-insider
**command requested**: navtree
**hitting sessions**: 314
**proportion of all sessions**: 0.006446447268471945
**stack**
```
Error: No Project.
    at Object.ThrowNoProject (tsserver.js:84377:23)
    at ScriptInfo.getDefaultProject (tsserver.js:84985:46)
    at ProjectService.getDefaultProjectForFile (tsserver.js:87557:39)
    at IOSession.Session.getFileAndLanguageServiceForSyntacticOperation (tsserver.js:89921:92)
    at IOSession.Session.getNavigationTree (tsserver.js:90249:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89266:61)
    at unknown (tsserver.js:90553:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90544:28)
    at IOSession.Session.executeCommand (tsserver.js:90553:33)
    at IOSession.Session.onMessage (tsserver.js:90573:35)
    at Interface.<anonymous> (tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```
