### ISSUE TITLE
Method `concat` has wrong typization

### ISSUE THREAD

**Issue by phpcoder2022** [microsoft/TypeScript#58631] opened 2024-05-23 09:57 UTC
### 🔎 Search Terms

typescript, concat, bug

### 🕗 Version & Regression Information

I tested this behavior on version 5.4.5. Local and playground results are equal.
I attached link to playground for demo.
You can see problem in output array. It isn't contains only arrays, but contains just numbers too.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?jsx=0#code/C4TwDgpgBAcgrgWwEYQE4GUIEc4QHYDG0AvFHoiqgNoC6A3AFAMED2eAzsFMAIYDWEeMjTsopABQA6ae2y5CEdgC5YFNJhz4itAJRiAfFADeDKFFYcWAGwiSrLAObiABgEE8IKDwLAAlm1EAd19gAAsvVFQeEHZnABooWU0Fdh1GAF9GZgCuHgATPKFKdkxgUQlpSXJhDAgylQAFHiiEOpEAHlBIFgAzbn5BNVR2fV0DY1MyIdL2SR6WVABRb1DxWS5iQ14BIpEpGTqdNIZMpnzCoZK69nEqKgBGBIAmBIBmGhpJCwIeYFuAFgSAFYEgA2GhHOhAA

### 💻 Code

```ts
type NumberSequence = number[];

const takeNumbers = (...sequences: NumberSequence[]) => {
  console.log(`Any actions with arrays`, sequences);
};

const addNumbersSets = (...numberSets: Parameters<typeof takeNumbers>[]) => {
  numberSets.forEach(set => takeNumbers(...set));
};

addNumbersSets([[1, 2, 3]].concat([4, 5, 6]));

```

### 🙁 Actual behavior

Output array contains numbers

### 🙂 Expected behavior

Output array contains only arrays of numbers

**Comment by whzx5byb** [comment] 2024-05-23 10:52
Duplicate of https://github.com/microsoft/TypeScript/issues/19535.

**Comment by phpcoder2022** [comment] 2024-05-23 11:42
How for need generic type `ConcatArray<T>`? I wrote this type locally:

```ts
type ConcatArg<RawType> = RawType extends unknown[] ? RawType[] : (RawType | RawType[]);

interface Array<T> {
  concat(...items: ConcatArg<T>[]): T[];
}
```

Is it a acceptable solution?

**Comment by nmain** [comment] 2024-05-23 13:29
> Is it a acceptable solution?

If it works for you, use it!  My interpretation of https://github.com/microsoft/TypeScript/issues/36554 is that the TypeScript team probably not interested in adopting such a change unless it's part of a holistic revamp of array typing issues, with consideration given to all users and possible breaking changes.

**Closed** 2024-06-09 01:31 UTC
Labels: Duplicate
