### ISSUE TITLE
Overload selection differs for mapped types vs interfaces

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#25378] opened 2018-07-02 20:08 UTC
**TypeScript Version:**  2.9.1

**Search Terms:** overload mapped types interface

**Code**

```ts
interface LoDashStatic {
  mapValues<T, TResult>(
      obj: { [index: string]: T },
      callback: (t: T) => TResult,
  ): { [index: string]: TResult };
  mapValues<T extends object, TResult>(
      obj: T,
      callback: (t: T) => TResult,
  ): { [P in keyof T]: TResult };
}

declare const _: LoDashStatic;

interface AbcObjectInterface {
  a: number;
  b: string;
  c: boolean;
}
type AbcObjectRecord = Record<"a" | "b" | "c", string>;

declare const abcObjectRecord: AbcObjectRecord;
declare const abcObjectInterface: AbcObjectInterface;

// Expected return type to be `{ a: number; b: number; c: string }` and got :-)
// The second overload is used, as expected.
_.mapValues(abcObjectInterface, (v) => 1);

// Expected return type to be `Record<"a" | "b" | "c", number>` but got `{ [index: string]: number }` :-(
// The first overload is used, unexpectedly.
_.mapValues(abcObjectRecord, (v) => 1);
```

**Related Issues:** https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26983#issuecomment-401897916

**Comment by mhegazy** [comment] 2018-07-02 20:16
Duplicate of https://github.com/Microsoft/TypeScript/issues/15300

**Comment by OliverJAsh** [comment] 2018-07-02 20:19
Ta!

**Closed** 2018-07-03 08:13 UTC
Labels: Duplicate
