### ISSUE TITLE
"paths" of tsconfig.json doesn't work inside the symlinked directory

### ISSUE THREAD

**Issue by jhaemin** [microsoft/TypeScript#37630] opened 2020-03-13 04:35 UTC
- VSCode Version: `1.43.0`
- OS Version: macOS Catalina `10.15.3`

Steps to Reproduce:

1. Initialize a project with the TypeScript.

```zsh
tsc --init
```

2. Create a simple directory structure and two TypeScript modules.

```
root
├─ original-module2
│  └─ module2.ts
├─ src
│  └─ module1.ts
└─ tsconfig.json
```

`module1.ts`
```ts
export const module1 = 'module1'
```

`module2.ts`
```ts
import { module1 } from '@/module1'
```

3. Configure `tsconfig.json` with `baseUrl` and `paths`.

```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

4. Symbolic link `original-module2` to `src`.

```zsh
ln -s path/to/original-module2 path/to/src
```

![Screen Shot 2020-03-13 at 1 52 49 PM](https://user-images.githubusercontent.com/19797697/76590896-fe271b00-6531-11ea-987c-dc013b08693e.png)

5. "paths" intellisense works perfectly inside the original directory. But it cannot be resolved inside the symlinked directory.

**Original Directory**

![Screen Shot 2020-03-13 at 1 25 32 PM](https://user-images.githubusercontent.com/19797697/76589795-90c5bb00-652e-11ea-84a1-2feb0dd0b5d6.png)
![Screen Shot 2020-03-13 at 1 26 03 PM](https://user-images.githubusercontent.com/19797697/76589807-9ae7b980-652e-11ea-903a-03720b0287ff.png)

**Symlinked Directory**

![Screen Shot 2020-03-13 at 1 26 25 PM](https://user-images.githubusercontent.com/19797697/76589817-a5a24e80-652e-11ea-9e69-0d59602e36d6.png)
![Screen Shot 2020-03-13 at 1 26 48 PM](https://user-images.githubusercontent.com/19797697/76589821-aaff9900-652e-11ea-898e-7083b6507eeb.png)
![Screen Shot 2020-03-13 at 1 29 45 PM](https://user-images.githubusercontent.com/19797697/76589835-b9e64b80-652e-11ea-8b8d-9f7ce2adc40d.png)
![Screen Shot 2020-03-13 at 1 53 55 PM](https://user-images.githubusercontent.com/19797697/76590944-2151ca80-6532-11ea-876c-e9a4ca0181d7.png)

Sometimes the issue occurs reversely, which means the intellisense doesn't work inside the original directory but works inside the symlinked directory.

Tested on both Visual Studio Code(`1.43.0`) and Visual Studio Code Insiders(`1.44.0-insider`, with `--disable-extensions`).

Sadly but fortunately it works on JetBrains WebStorm without any problem.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sheetalkamat** [comment] 2020-07-23 19:16
I am not sure how to repro this.  I am using vscode 1.47.2 and i dont see symlinked folder in the explorer.
![image](https://user-images.githubusercontent.com/8052792/88329088-4aebe100-ccde-11ea-8b27-9e7fa2136c7e.png)


Here is the folder structure:
```
c:\temp\test>dir /s
 Volume in drive C is OSDisk
 Volume Serial Number is F41A-DBC9

 Directory of c:\temp\test

07/23/2020  12:04 PM    <DIR>          .
07/23/2020  12:04 PM    <DIR>          ..
07/23/2020  12:03 PM    <DIR>          original-module2
07/23/2020  12:07 PM    <DIR>          src
07/23/2020  12:08 PM               122 tsconfig.json
               1 File(s)            122 bytes

 Directory of c:\temp\test\original-module2

07/23/2020  12:03 PM    <DIR>          .
07/23/2020  12:03 PM    <DIR>          ..
07/23/2020  12:08 PM                26 module2.ts
               1 File(s)             26 bytes

 Directory of c:\temp\test\src

07/23/2020  12:07 PM    <DIR>          .
07/23/2020  12:07 PM    <DIR>          ..
07/23/2020  12:13 PM                59 module1.ts
07/23/2020  12:07 PM    <SYMLINKD>     original-module2 [original-module2]
               1 File(s)             59 bytes
```

**Comment by sheetalkamat** [comment] 2020-07-23 19:17
Please share your tsserver log if this repros with latest vscode build and typescript nightly.
You can upload logs by following these steps:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. In vscode or vscode insiders, run the `TypeScript: Open TS Server log` command
5. This should open a large file called `tsserver.log`. Please share this file. Additionally you can also share file `ti.log` created next to it.

**Comment by jhaemin** [comment] 2020-08-06 07:47
@sheetalkamat 

I tested with nightly TypeScript `4.1.0-dev.20200805` and Visual Studio Code Insiders `1.48.0-insider`.

Here is a gif reproducing the issue.

![Aug-06-2020 16-17-10](https://user-images.githubusercontent.com/19797697/89502665-5243dc00-d800-11ea-84a1-608684cad034.gif)

When I symlink the directory, it appears inside the VSCode's file tree.

I'm currently using macOS and didn't test it on Windows, but I assume Windows VSCode does not render **symlinked** directories.

Also I attach [`tsserver.log`](https://github.com/microsoft/TypeScript/files/5033303/tsserver.log), but I don't see any logs related to the issue.

**Comment by sheetalkamat** [comment] 2020-08-10 18:16
can you please share tsserver.log after you enable `traceResolution` in compiler options so we can see whats going on with resolution. Thanks

**Comment by sheetalkamat** [comment] 2020-08-10 18:36
This needs handling projects little better for symlinks (not just in find all refs but to get completions etc which involves getting default project and updating the state of the project using resolved path)

**Comment by walkerburgin** [comment] 2020-12-15 02:39
I hit what I think is this same error today in the context of a project which uses PNPM as its package manager. With the way that PNPM uses symlinks, I think this issue makes the `"paths"` compiler option surprisingly error prone.  If it's helpful I set up a small repro here: https://github.com/walkerburgin/ts-paths-symlink-repro (the README includes traceResolution output as well)

**Comment by sheetalkamat** [comment] 2021-02-09 22:43
I have looked into this and there seems like no feasible way to fix this. editors send tsserver with information of file location and content when opened and having same files open in editor through different paths makes keeping what happens between them in sync not feasible. 
Option of combining results from multiple projects is not ideal either since we dont want to keep the configured project open or add cost of getting result from multiple ones.
So this issue wont be fixed.

**Closed** 2021-02-09 22:43 UTC
Labels: Needs Investigation, Rescheduled
