### ISSUE TITLE
private class members cannot be inherited when using class as interface

### ISSUE THREAD

**Issue by npenin** [microsoft/TypeScript#37924] opened 2020-04-13 08:34 UTC
**TypeScript Version:**  3.8.3

**Search Terms:** class private member implement

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
class A
{
    private p:string='';
}

class B implements A
{
    private p:string;
}
```

**Expected behavior:** either of those:
- private members are not required when implementing a class as an interface (preferred)
- private members can be defined on the class implementing without a compiling issue

**Actual behavior:** 
- when not defining the member on B, compiler complains it is missing
- when defining the member, compiler complains it is not matching with definition on A

**Playground Link:** https://www.typescriptlang.org/en/play?ts=3.8.3#code/MYGwhgzhAECCBQBve1XQA4CcCWA3MALgKYYBcEBOAdgOYC8A5AwNzwC+88okMAQtNgC26EEUFEqBGAmRoMOfMTIVqNVmyA

**Related Issues:**  #20581

**Comment by MartinJohns** [comment] 2020-04-13 08:47
Duplicate of #37447.

**Comment by npenin** [comment] 2020-04-13 18:09
I agree this is a duplicate. Sorry for missing this one.

But I don't get how it can work as intended since there is no way to implement the class A

**Closed** 2020-04-16 18:00 UTC
Labels: Duplicate

**Comment by npenin** [comment] 2020-04-16 21:30
@RyanCavanaugh, can you please explain me how to implement class A ?

**Comment by npenin** [comment] 2020-05-09 14:42
@RyanCavanaugh up ?

**Comment by RyanCavanaugh** [comment] 2020-05-12 16:03
@npenin You can't. That is a desired property of `private`.
