### ISSUE TITLE
Ability autocomplete for the Omit utility keys

### ISSUE THREAD

**Issue by arimariojesus** [microsoft/TypeScript#50854] opened 2022-09-20 03:07 UTC
# Allow Omit to auto-infer object keys

## 🔍 Search Terms
`auto-infer`, `omit`, `autocomplete`.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I would like to propose the ability to autocomplete for the [Omit](https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys) utility on object keys just as it does for the [Pick](https://www.typescriptlang.org/pt/docs/handbook/utility-types.html#picktype-keys) utility.

Something like this:
```ts
interface Todo {
  title: string;
  description: string;
  completed: boolean;
  createdAt: number;
}

type CustomOmit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
 
type TodoPreview = CustomOmit<Todo, "description">;
 
const todo: TodoPreview = {
  title: "Clean room",
  completed: false,
  createdAt: 1615544252770,
};
```

## 📃 Motivating Example

```ts
interface LargeObject {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  author: string;
  createdAt: number;
  updatedAt: number;
  etc: string;
}

// "autor" key was supposed to be "author" but it's hard to notice on objects with multiple properties
type ReducedObject = Omit<LargeObject, "description" | "title" | "completed" | "autor">;

const todo: ReducedObject = {
  id: "id",
  subtitle: "Cool subtitle",
  author: "What!",
  createdAt: 123,
  updatedAt: 456,
  etc: "bla bla"
};
```

### What do you want to use this for?
- [x] To make it easier to search for properties on objects
- [x] Avoid duplicate keys passed to Omit
- [x] Avoid syntactic errors when passing keys to Omit

### What shortcomings exist with current approaches?
Currently Omit does not check or autocomplete the keys passed, so it is possible to pass any value, even if it is not part of the type in question

**Comment by jcalz** [comment] 2022-09-20 11:56
Not an exact duplicate of #30825 but very strongly related.  

They’re not going to change the definition of `Omit`, but you can write your own version that acts however you want.  There’s even a comment in there about an IDE that adds your desired autocomplete feature for the existing `Omit`.

**Comment by Andarist** [comment] 2022-09-20 11:57
You can write a version that auto-completes like this:
```ts
type Omit2<
  T,
  K extends keyof T | (string & {}) | (number & {}) | (symbol | {})
> = { [P in Exclude<keyof T, K>]: T[P] };
```

Surprisingly though, this version doesn't work as expected:
```ts
type Omit3<T, K extends keyof T | ((string | number | symbol) & {})> = {
  [P in Exclude<keyof T, K>]: T[P];
};
```

See it in action [here](https://www.typescriptlang.org/play?ssl=15&ssc=3&pln=13&pc=1#code/C4TwDgpgBAKhDOwoF4oG8oDMD22BcUiATgJYB2A5lAL4DcAUPaJFAPIC2JwATADz1RYAGgFQA0lAgAPYBDIATeFADWEENkywoAHygAKYuSoAydNQCUO-WQCu7AEYQiUU2gtWDIB9gA2Vt+b0AHwo6FAA2gAKUORQAKJSAMY+NvIQvKrqmjBC4kEAugQwUfk0DPQA9BVQAIY+PtgA7hDyTODQAEoIAIyhHFx8cIi5AET2NUQjQQxVtfVNLbUKtTbA2InY7GA+ELKtzJ0I3H2cPLxDwKM42FPlB2ynAMznuRLSsgpKmRpaunoGwFIlCstgcTis8C89l8llcFhCqDQoiiMTI8SSKTSGTUPxyeUKsBKDDojFm8BsRDApHgRh8IFywAAFiQlPJsAgyAByJA1VbrTbbXYQNosLrwR4nLjPC6jW70IA)

**Comment by RyanCavanaugh** [comment] 2022-09-20 21:46
Agree this is basically a duplicate of #30825 (the idiomatic `OmitStrict` does get completions as expected). There's no information present that TS can use to tell it's supposed to be presenting the keys of `T` here, and arguably it'd be incorrect to do so as those aren't the only legal values for the second type argument.

**Closed by RyanCavanaugh** 2022-09-20 21:46 UTC
Labels: Suggestion, Declined

**Comment by arimariojesus** [comment] 2022-09-21 00:58
@jcalz I still haven't found anything related. I really appreciate the contribution. The issue already presents a very rich discussion and corrects the suggestion presented.

**Comment by arimariojesus** [comment] 2022-09-21 01:06
@Andarist The `Omit2` example is really useful for my use case. Thank you for the contribution.
