### ISSUE TITLE
'Infer type from usage' suggestion always shown even when no quick fix is available 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#28826] opened 2018-12-03 20:52 UTC
**TypeScript Version:**  3.3.0-dev.20181130

**Search Terms:**
- suggestions
- quick fix

**Code**
For the TS:
```ts
const a = (x) => x   
```

**Bug:**
A suggestion diagnostic for `Parameter 'x' implicitly has an 'any' type, but a better type may be inferred from usage` is returned and rendered in the editor. However, no quick fix is returned in this case

We should only show suggestions for problems that are fixable

**Playground Link:** 

**Related Issues:**

**Comment by sandersn** [comment] 2018-12-03 22:31
There should be a codefix available, but it looks like it fails to apply. I'll see why.

**Comment by mjbvz** [comment] 2018-12-03 23:08
@DanielRosenwasser This issue is causes some confusion in VS Code. The `...` suggestion combined with the `add/remove braces` refactoring in the editor makes it look like we are suggesting that you can add or remove braces:

![dec-03-2018 11-54-26](https://user-images.githubusercontent.com/12821956/49407208-ada8f700-f70c-11e8-88a8-30b7f3c98ce2.gif)

This only happens in TS 3.2. I think we may need to disable this suggestion on the VS Code side

**Comment by sandersn** [comment] 2018-12-03 23:35
At one point, we didn't infer from function expressions, including arrow expressions, but as of 3.2 we do trivial alias analysis for function expressions. Arrow expressions should behave the same.

I can just enable arrow functions, but I need to change the code to add parentheses to single-parameter functions that don't have them. Shouldn't take too long.

**Comment by AlCalzone** [comment] 2018-12-04 12:56
Duplicate of #28702?

**Closed** 2018-12-04 17:03 UTC

**Comment by sandersn** [comment] 2018-12-04 17:22
@AlCalzone almost, I think #28750 and #28702 are the same bug. I couldn't repro that one with master, so maybe you can try the release version of 3.2 or `typescript@next`?
