### ISSUE TITLE
Type restriction not working when playing with conditions

### ISSUE THREAD

**Issue by Brack0** [microsoft/TypeScript#33003] opened 2019-08-21 09:49 UTC
**TypeScript Version:**  3.5.1

**Search Terms:** Union types, type restriction

**Code**

```ts
enum ENUM_VALUE {
  VALUE_1 = "1",
  VALUE_2 = "2",
  VALUE_3 = "3"
}

function getValue(): ENUM_VALUE | ENUM_VALUE[] {
  return Math.random() > 0.5
    ? ENUM_VALUE.VALUE_1
    : [ENUM_VALUE.VALUE_2, ENUM_VALUE.VALUE_3];
}

const value: ENUM_VALUE | ENUM_VALUE[] = getValue();

if (Array.isArray(value)) {
  const valueArr: ENUM_VALUE[] = value; // Works here
}

if (Array.isArray(value) === true) {
  const valueArr: ENUM_VALUE[] = value; // Error
}
```

**Expected behavior:** `if (Array.isArray(value) === true)` is not very fancy but it should restrict the type of 'value'.

**Actual behavior:** The type isn't changed.

**Playground Link:** https://www.typescriptlang.org/play/#code/KYOwrgtgBAogcgVQLIH0BqBBAMgmUDeAsAFBRSY4woCMUAvFAETWMA0JZFuKATPUzzYdy2bgGZ+jMYxIBfEiQBmYEAGMALgEsA9iCgBzYOrQBDADZhgACgCUALliJUXPAB9HydKJgBtALoEwgBORmBBekgm6gAWAHRBJiAAJtoQtlAAfFAADLEArMJkAPwezt6xLjSFUA4+8J4uFd68rKVelE2UKGJ+ANxyCsSqugDO6lAAbuaWDvVllFDuc+24-vyGxtPWNv3EJJqKUFYYQQkAnrGaIyfnVlMWwDY2gaRQwyBjk1s3s04rvgEGPdLL0oAB6MFQADq2iCAGsRlBosAQgM9sQDkcbiYLldsWc7ltnnQSVB1EFLM8iK93p9gcAfm0XGsgVtQRDYKdYWigA

**Related Issues:** #32819

**Comment by jack-williams** [comment] 2019-08-21 09:57
Duplicate of #32819.

**Closed** 2019-08-21 17:02 UTC
Labels: Duplicate
