### ISSUE TITLE
Spread attribute syntax makes compilation and type checking ignore errors and module imports

### ISSUE THREAD

**Issue by lith-light-g** [Microsoft/TypeScript#15625] opened 2017-05-06 00:55 UTC
**TypeScript Version:**  2.3.2 (VSCode / Windows)

**Code**

```ts
import * as React from "react";
import { style } from "./classNames";

export class Component extends React.Component<React.HTMLProps<HTMLDivElement>, {}> {
    constructor(props?: React.HTMLProps<HTMLDivElement>) {
        super(props);
    }
    render(): JSX.Element {
        const props: any = this.props;
        return <div
            {...props}
            className={style}
        >
            <p>Content</p>
        </div>;
    }
}
```

**Expected behavior:**
Compiled code should have `require("./classNames");`.
**Actual behavior:**
`require("./classNames");` is not present.

I'm in a weird situation where TypeScript stops caring about whatever that is after a spread attributes syntax.

In the sample code I can't put `{...this.props}` because I would get this error: `'children' are specified twice. The attribute named 'children' will be overwritten.` So I worked around it with the `any` variable.

But now the crazy thing is that everything after the spread syntax is "ignored" by TypeScript.

The compiler doesn't notify any further syntax errors and doesn't include the imported module that I use after the spread syntax. But it *will* successfully compile.

[This is the compiled file of the above code](https://github.com/lith-light-g/typescript-spread-bug/blob/master/index.js). I believe I should get a `require("./classNames")` somewhere which I do get if I don't use the spread syntax.

#### Using an undeclared variable before the spread syntax
![Before spread](http://i.imgur.com/v5vU056.png)
VSCode shows the error and I also get the following error when compiling: `index.tsx(12,24): error TS2304: Cannot find name 'notDeclared'.`

#### Using an undeclared variable after the spread syntax
![After spread](http://i.imgur.com/ZDY7LQO.png)
VSCode ignores the error and I get no errors when compiling.

**Comment by mhegazy** [comment] 2017-05-06 00:58
Duplicate of https://github.com/Microsoft/TypeScript/issues/15469. should be fixed in `typescript@next`, and will be part of the upcoming `typescript@2.3.3`.

**Comment by yuit** [comment] 2017-05-08 18:52
Close for now @lith-light-g  let us know if you still run into issue after update to `typescript@next`

**Closed by yuit** 2017-05-08 18:52 UTC
Labels: Duplicate
