### ISSUE TITLE
Throw "TypeError: Attempted to assign to readonly property." at compile

### ISSUE THREAD

**Issue by DaSchTour** [Microsoft/TypeScript#10286] opened 2016-08-11 15:33 UTC
**TypeScript Version:**  1.8.10

**Code**

```ts
"use strict";
class Foo {
  private _readonlyProp: any;
  constructor() {
    this._readonlyProp = "bar";
  }
  get readonlyProp() {
    return this._readonlyProp;
  }
}

const foo = new Foo();
foo.readonlyProp = "not bar";
```

**Expected behavior:**
Compiler complains about setting a readonly property.

**Actual behavior:** 
Compile works, but browser throws "TypeError: Attempted to assign to readonly property." error.

**Comment by RyanCavanaugh** [comment] 2016-08-11 16:05
Duplicate of #12. This now produces an error

>  error TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property

You could also try the FAQ: https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-getters-without-setters-not-considered-read-only

**Closed by RyanCavanaugh** 2016-08-11 16:05 UTC
Labels: Duplicate
