### ISSUE TITLE
Preserve Named Properties when Merging Tuple Types

### ISSUE THREAD

**Issue by BribeFromTheHive** [microsoft/TypeScript#53930] opened 2023-04-20 15:28 UTC
# Suggestion

## 🔍 Search Terms

- Named properties in merged tuple types
- Rest parameters with named tuple properties
- Merge tuple types while preserving named properties

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add the ability to merge tuple types while preserving the named properties of their elements.

## 📃 Motivating Example

Currently, when tuple types with named properties are merged using the spread operator `...`, TypeScript loses the named properties of the tuple elements. This makes it difficult to maintain named parameter hints in function signatures when using rest parameters with merged tuple types.

## 💻 Use Cases

Consider the following example:

```typescript
type SimpleArgs = [a: number, b: string];

type MergedArgs = [...SimpleArgs, c: boolean];

function exampleFunction(...args: MergedArgs) {
  const [a, b, c] = args;
  // Do stuff with a,b,c
}

exampleFunction(1, 'hello', true);
```

In this scenario, the named properties a, b, and c are lost when the tuple types are merged into MergedArgs. As a result, the parameter hints for exampleFunction do not show the named properties when mousing over the function signature.

It would be beneficial to have a way to merge tuple types that preserves the named properties of their elements, improving the developer experience when working with rest parameters in function signatures.

**Comment by RyanCavanaugh** [comment] 2023-04-20 15:52
> Currently, when calling the blah function, the editor hints display the args rest parameter, but they do not display the named parameter hints from the tuple type (e.g., a: someType, b: anotherType, etc.).

That's not what I'm seeing?

![image](https://user-images.githubusercontent.com/6685088/233420281-413162c2-fafb-41f2-90d3-81bb39a12644.png)

**Comment by BribeFromTheHive** [comment] 2023-04-20 17:11
Hi @RyanCavanaugh,

Thanks for getting back to me on this so quickly.

I'd like to apologize that my initial feature request was a bit unclear. After seeing your reply, I realized that what I was trying to achieve was a bit more nuanced than I initially explained. So, I've gone ahead and updated the request with a clearer description/title and some practical use cases.

Thanks for your patience!

- Luke

**Comment by fatcerberus** [comment] 2023-04-20 17:17
With the updated example in the OP, this looks like a duplicate of https://github.com/microsoft/TypeScript/issues/52853

**Comment by BribeFromTheHive** [comment] 2023-04-20 17:29
Correct! They are one and the same issue. Thanks for that!

**Closed** 2023-04-20 17:29 UTC
Labels: Duplicate
