### ISSUE TITLE
Bug with assertion on String literal types

### ISSUE THREAD

**Issue by MrMamen** [Microsoft/TypeScript#20750] opened 2017-12-18 14:11 UTC
**TypeScript Version:**  2.7.0-dev.20171216

**Code**
This is part of a react component (thus setState), but the only relevant part is this:

```ts
interface MyState {
  a: boolean;
  b: boolean;
}
class MyComponent extends React.Component<undefined, MyState> {
  private toggle = (event: ChangeEvent<HTMLInputElement>): void => {
    const checked = event.target.checked;
    const name: "a" | "b" = (event.target.name as "a" | "b");
    this.setState({ [name]: checked });
  }
}
```

I know it can be dangerous to state what the the target.name is of these types, but regardless it should work. Also the statement works if I change it into:
```ts
 const name: "a" | "b" = "a";
```

**Expected behavior:**
To accept name as either "a" or "b"

**Actual behavior:**
``
error TS2345: Argument of type '{ [x: string]: boolean; }' is not assignable to parameter of type 'Pick<MyState, "a" | "b">'.
  Property 'a' is missing in type '{ [x: string]: boolean; }'.
``

**Comment by andy-ms** [comment] 2017-12-18 15:52
`{ [name]: checked }` is an object with only one property, but `MyState` has two properties.
If you write `interface MyState { a?: boolean; b?: boolean; }`, then this will work.

**Comment by MrMamen** [comment] 2017-12-19 07:57
Likewise I am puzzled that this works:
```ts
    if (name === "a") {
      this.setState({ [name]: checked });
    } else if (name === "b") {
      this.setState({ [name]: checked });
    }
```
while this does not:
```ts
    if (name === "a" || name === "b") {
      this.setState({ [name]: checked });
    }
```
The latter gives the same error message as described in the original description.

**Comment by andy-ms** [comment] 2017-12-19 15:30
Filling in type arguments:
```ts
if (name === "a") {
    this.setState<"a">({ [name]: checked });
} else if (name === "b") {
    this.setState<"b">({ [name]: checked });
}

if (name === "a" || name === "b") {
    this.setState<"a" | "b">({ [name]: checked });
}
```
The problem is that `setState` takes a key type `K` and expects an object that has *all* of those keys -- but the inferred key type would be `"a" | "b"` and the object will only have *one* of those keys.

**Comment by mhegazy** [comment] 2018-01-10 19:32
Duplicate of https://github.com/Microsoft/TypeScript/issues/13948

**Closed** 2018-01-25 23:25 UTC
Labels: Duplicate
