### ISSUE TITLE
Deconstructing a discriminated union with shared secondary property of different types

### ISSUE THREAD

**Issue by louiebert** [microsoft/TypeScript#39026] opened 2020-06-11 17:39 UTC
**TypeScript Version:**  3.9.2

**Search Terms:**
discriminated union, discriminated
**Code**

```ts
interface OptionOne {
    kind: "one";
    ambiguousProperty: number; // This property name is shared, but has a different type in each unioned interface
    isThisABug: boolean;
}

interface OptionTwo {
    kind: "two";
    ambiguousProperty: string; // This property name is shared, but has a different type in each unioned interface
    prettySureThisIsABug: boolean;
}

type OptionUnion = OptionOne | OptionTwo;

// This function is riddled with errors
const myDeconstructedFunc = ({kind, ambiguousProperty, ...otherParams}: OptionUnion) => {
    if (kind === "one") {
        const myLocalNum: number = ambiguousProperty;
        otherParams.isThisABug = true;

        console.log(myLocalNum); // So this thing is used
    } else if (kind === "two") {
        const myLocalString: string = ambiguousProperty;
        otherParams.prettySureThisIsABug = true;

        console.log(myLocalString); // So this thing is used
    }
};

// This function is error-free
const myNotDeconstructedFunc = (option: OptionUnion) => {
    if (option.kind === "one") {
        const myLocalNum: number = option.ambiguousProperty;
        option.isThisABug = true;

        console.log(myLocalNum); // So this thing is used
    } else if (option.kind === "two") {
        const myLocalString: string = option.ambiguousProperty;
        option.prettySureThisIsABug = true;

        console.log(myLocalString); // So this thing is used
    }
};

```

**Expected behavior:**
Both of these functions have the same behavior (ideally both compiling without errors)
**Actual behavior:**
`myDeconstructedFunc` has compile errors and can't discern the correct type inside a union isolating condition. `myNotDeconstructedFunc` handles this case just fine.
**Playground Link:** 
[Link here](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200610&ssl=42&ssc=1&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgPIAczAPYlSFAbwChkzkBrUAEwC5kAiXCBgblPLgFsAjYAcwCu2QQGcAClGzpoYAJ70Qg3tFbIA9OuQAVABbBRydFJlR5yENxQHko3XCgRqAGmQ9BYZPcNxk1YDAw0BDgyPIyyKDIEIi6yIIgOATUkeDQ8EgcZAZ6BgCCAEKC-PQ82NgANjEg7AC+xMSgkLCIKBhYuNoA7tjIJOSUNPQMYD1sWcjcfEIiEiayCrZgUKD8apo6+obG0gsWVpGGdg5Oru6e3pN+AUGOoeHWINGx8YnMKU3prRPGEGDyAGVBI5cqIAJKiQrFUrlKpwGrEerEB5oTBJACqbyeAF5UR08ARkAAfPFJbrYdjEBC4USeLhyAAiEGpIFpUEECEg1AAYgkEMhcQAKQhUEAuSa8ATCMSSXZmOSuAB0yuwYF00HEDm4olq9HaGKxAEoBQA+PoTALIQWilLYu2MZgMY39AbkFm05D0gAy2AQcAqADllIplDxoAKJdNpXM5fJ2K7yKr1VBNVBtYqclsofwI8tBBBKQmyO7KhBFRVsPxBd7ff6g1xDestADemqbG2QDmbGInBNatEKqJrDArTaBfaRmNnRMBu66XIfX6KgDlqt6GzVhGplLZrLTHGZ4m1RqtVxRIrfv85ECQVsIdnc+yCw0i8gS1Vy5Xqwva8vV53Gw0ZtWy2MJ9E7Q54iHag+0RSk509OQA1VJk53ZTknF5EB+SFaR8T1NFcExJJjWxM0XWyEdBTwpJFTHO1cSYAgnXNV8EJrJd6xDFQoAjGjcEVbcZhleZ5XjIt+JADNRFBB9cTzZ9D2LGlS0-KsOLrZRAI2FswPbcCu0MHsYIGfsIEHYcrUkuiaHHRjRmwFiKNddifyXFcVk7dd-xzXFrKE6M9wWcSE2sy9AWBCBQXvIpfLCJ9CyLd8ywrdS3P9DzVm04C9MMDtDKg3tTLg4ggA)

**Related Issues:** 
I didn't find any that were specifically for deconstructing a shared property that was typed differently per unioned interface.

**Comment by MartinJohns** [comment] 2020-06-11 19:13
Essentially a duplicate of #12184.

**Comment by louiebert** [comment] 2020-06-11 19:16
Upon further investigation, this doesn't need the condition of "shared property with different types". This repros as soon as the discriminant is deconstructed. If the discriminant is `readonly`, I feel like TS should be smart enough to retain its intellisense in the deconstructed discriminant.

```typescript
interface OptionOne {
    readonly kind: "one";
    foo: number;
    isThisABug: boolean;
}

interface OptionTwo {
    readonly kind: "two";
    bar: string;
    prettySureThisIsABug: boolean;
}

type OptionUnion = OptionOne | OptionTwo;

// riddled with errors
const myDeconstructedFunc = ({kind, ...otherParams}: OptionUnion) => {
    if (kind === "one") {
        const myLocalNum: number = otherParams.foo;
        otherParams.isThisABug = true;

        console.log(myLocalNum); // So this thing is used
    } else if (kind === "two") {
        const myLocalString: string = otherParams.bar;
        otherParams.prettySureThisIsABug = true;

        console.log(myLocalString); // So this thing is used
    }
};

// no errors
const myNotDeconstructedFunc = (option: OptionUnion) => {
    if (option.kind === "one") {
        const myLocalNum: number = option.foo;
        option.isThisABug = true;

        console.log(myLocalNum); // So this thing is used
    } else if (option.kind === "two") {
        const myLocalString: string = option.bar;
        option.prettySureThisIsABug = true;

        console.log(myLocalString); // So this thing is used
    }
};
```

**Closed** 2020-06-14 18:00 UTC
Labels: Duplicate
