### ISSUE TITLE
CodeFix import for items that exist globally

### ISSUE THREAD

**Issue by normalser** [Microsoft/TypeScript#13378] opened 2017-01-10 02:03 UTC
I'm not sure if this feature request is valid so just wanted to see what you think.

Let's say I have a react component called `History`.
As it happens there also exists global `declare var History` in `lib.dom.d.ts`

It would be nice that when using `History` in my module I could use CodeFix import action (`Cmd+.`) to be able to import my own component if there is no such local import. CodeFix bulb / shortcut keyboard is very discreet so there wouldn't be any worry of noise.

And I'm not sure how many other such cases could exist

**Comment by aluanhaddad** [comment] 2017-01-10 04:19
So is the idea here that it would always be an available "refactoring" or is this for the scenario you have in mind one where you actually meant to import your History component and simply forgot?

**Comment by wallverb** [comment] 2017-01-10 14:05
@aluanhaddad what I meant was this.

Imagine user has React component:
```tsx
// File: history1.tsx
export const History = ()=> <div>...</div>
```

and he wants to reuse it in his other react components

```ts
// File: test.tsx
export const Test = ()=> <History/>
```

But because there happens to exist 'History' global variable - he is not able to use the most awesome recent feature of TS/Vscode called "CodeFix import" - no bulb and clicking Cmd+"." does nothing

Now the only way to make it work is to manually go to the top of the file and add `import { History } from './history1'` or to rename the component to something else (so it does not collide with some global type/item)

I was just wondering if it was make sense to have this logic:

If there is no import like `import { History } from '....'` in current file then still allow to use `Cmd+.` on `History` (in this example)  to import "local component" into current file

List of global types/items is pretty big but still not sure if it's gonna be common scenario of defining own things that happen to have the same name as some globals

![zbikq8ga78](https://cloud.githubusercontent.com/assets/1723815/21808995/c72c3838-d713-11e6-8027-7f07a4abca42.gif)

**Comment by aluanhaddad** [comment] 2017-01-14 04:34
Thanks for clarifying. I like this idea.

**Comment by mhegazy** [comment] 2017-04-21 00:10
Duplicate of #7849. Fixed by https://github.com/Microsoft/TypeScript/pull/13921

**Closed by mhegazy** 2017-04-21 00:10 UTC
