### ISSUE TITLE
Better assignability check for IteratorResult<T,U>

### ISSUE THREAD

**Issue by skishore** [Microsoft/TypeScript#17285] opened 2017-07-19 05:04 UTC
I'm opening this bug to discuss a blocker for https://github.com/Microsoft/TypeScript/issues/2983 that seems significant enough to merit discussion on its own. In the course of trying to fix that issue, I found that Typescript cannot assign the type:

```
{done: boolean, value: number}
```

to the type:

```
{done: false, value: number} | {done: true, value: any}
```

What's going on here is that assignment from a non-union type T to a union type A | B is currently only allowed if T can be assigned to A or to B. However, in this particular case, casework on the type T shows that is indeed a subtype of A | B.

I don't propose to fix this problem in full generality. In fact, that seems pretty much infeasible to me, as I think we can express arbitrary SAT instances as instances of this problem. However, would people be okay with an improvement to the assignment relation specific to this IteratorResult case?

**Comment by mhegazy** [comment] 2017-08-23 20:01
Duplicate of #2983 and #11375

**Comment by mhegazy** [comment] 2017-09-07 17:44
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-07 17:44 UTC
Labels: Duplicate
