### ISSUE TITLE
Type narrows to `never` after using `in` operator on `HTMLElement` type

### ISSUE THREAD

**Issue by craigkovatch** [microsoft/TypeScript#46911] opened 2021-11-23 23:41 UTC
# Bug Report

In the code sample/playground below, TS 4.2 and below narrows the type of `elem` to `never` inside the conditional first branch here (hence the use of `any`). I would expect it to /augment/ the type, i.e. the type of `elem` should be `HTMLElement & { scrollIntoViewIfNeeded: unknown }` or maybe `HTMLElement & { scrollIntoViewIfNeeded: any }`. It seems like the compiler should infer this from the use of the `in` operator in the conditional.

In TS 4.3 and above, the type of `elem` remains `HTMLElement`; to me that is still unexpected.

### 🔎 Search Terms

Turns out "in", "never", and "operator" are pretty common search terms 😬 Sorry in advance if I lack the vocabulary to search/describe this issue properly.

### 🕗 Version & Regression Information

TS 4.5.2, but repros at least back to 3.7.5

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `never` and "distributive conditional types" (seems like a different issue).

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.5#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5IBQJSAHgA5z4AuoAZgK4B2MNAlnM6JjPnABsBASWY04ANXZIA7sPoA5JEmQIAFEgFIAtgC5QACQAq4ADIBRLdqRiAlPoBucdglABvIqFDt6oNQHJefiFRcSlZeSUVFX9vbk0dW3dPL1AE7QA6IMERMUlpOUVlVTV6AEMBTCRbAG4UgF80ypQPVKadLL4c0PzZNTdQACMkHDKHTnx9fzLGcX8AGiGBOBgAaynmJDLCTBoFuIF2TY2tnb3QetqGonqgA)

### 💻 Code

```ts
export function scrollIntoViewIfNeeded(elem: HTMLElement): void {
  if ('scrollIntoViewIfNeeded' in elem) {
    (elem as any).scrollIntoViewIfNeeded(false);
  } else {
    elem.scrollIntoView({ behavior: 'auto', block: 'nearest', inline: 'nearest' });
  }
}
```

### 🙁 Actual behavior

Type of `elem` is `never` or `HTMLElement`, depending on TSC version.

### 🙂 Expected behavior

Type of `elem` should be inferred to include a field named `scrollIntoViewIfNeeded`

**Comment by fatcerberus** [comment] 2021-11-24 00:47
Duplicate of #21732.  Search terms: `in type guard property`

`in` only narrows unions, it doesn’t add properties to a type.

**Comment by RyanCavanaugh** [comment] 2021-11-24 17:54
Thanks @fatcerberus

**Closed** 2021-11-26 18:00 UTC
Labels: Duplicate
