### ISSUE TITLE
Duplicate identifier in buffer and send packages

### ISSUE THREAD

**Issue by magnushiie** [Microsoft/TypeScript#7063] opened 2016-02-12 23:12 UTC
Using the allowJs compiler option, if [buffer](https://github.com/feross/buffer) or [send](https://github.com/pillarjs/send) are dependencies, Duplicate identifier errors are reported:
```log
node_modules/buffer/index.js(94,5): error TS2300: Duplicate identifier 'length'.
node_modules/buffer/index.js(95,5): error TS2300: Duplicate identifier 'parent'.
node_modules/buffer/index.js(229,20): error TS2300: Duplicate identifier 'length'.
node_modules/buffer/index.js(230,20): error TS2300: Duplicate identifier 'parent'.
node_modules/send/index.js(203,22): error TS2300: Duplicate identifier 'root'.
node_modules/send/index.js(212,22): error TS2300: Duplicate identifier 'root'.
```

It seems similar to #6645, but here in addition to this member assignment, prototypes are in play.

**Comment by mhegazy** [comment] 2016-02-13 00:29
if i understand correctly you are calling `tsc --allowjs node_modules/buffer/index.js node_modules/send/index.js` correct? if so, why? what if not then how are you getting these errors?

**Comment by magnushiie** [comment] 2016-02-13 20:15
We are not directly pointing tsc to buffer/send, but we have configuration in tsconfig.json pointing to  node_modules. Here's a simplified example:
```json
{
  "compilerOptions": {
    "allowJs": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "lib",
    "target": "es5",
    "baseUrl": ".",
    "paths": {
      "*": [
        "*", 
        "node_modules/*"
      ]
    } 
  },
  "files": [
    "test.ts"
  ]
}
```

test.ts:
```typescript
import { Buffer } from "buffer";

console.log(Buffer);
```

And execute as:
```sh
npm install buffer
tsc
```

We have the node_modules/* entry in tsconfig because we would like tsc to transpile our modules in there. I know we could list only these specific modules in tsconfig, or pre-transpile the dependencies, but it would be nice if TS compiler could handle this.

**Comment by mhegazy** [comment] 2016-02-13 21:09
I see. Thanks for the clarification, the path mapping part is what I missed. The issue is the compiler does not think these are modules.

**Comment by billti** [comment] 2016-02-24 23:07
Issue is in one place it's assigned to this.length, in another Buffer.prototype.length. See also #6645.

**Comment by RyanCavanaugh** [comment] 2016-02-26 23:00
PR pending

**Closed** 2016-03-01 21:57 UTC
Labels: Bug, Fixed, Salsa

**Comment by billti** [comment] 2016-03-03 19:09
I see the release-1.8 merge. Is this fixed in master also?
