### ISSUE TITLE
Infinite unions

### ISSUE THREAD

**Issue by EnderShadow8** [microsoft/TypeScript#45275] opened 2021-08-02 12:04 UTC
# Suggestion

## 🔍 Search Terms

infinite union unions distributive conditional

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Types such as `string` and `number` which distribute over conditionals or act like unions.

A new `union` operator or similar could convert these types to a union-like structure. This prevents breaking existing code.

```ts
type StringUnion = union string
```

## 📃 Motivating Example

Say I want a type which is any string which is not a valid key of an object type:

```ts
type NotValidKey = Exclude<string, keyof MyObjectType> // Doesn't work because string is not a union

type NotValidKeyHelper<T> = T extends keyof MyObjectType ? never : T
type NotValidKey = NotValidKeyHelper<string> // Doesn't work because string is not a union
```

Using the suggested feature:
```ts
type NotValidKey = Exclude<union string, keyof MyObjectType>
```

## 💻 Use Cases

This is useful for functions which use the `asserts` feature to add properties to objects, to prevent preexisting properties from being overwritten.

```ts
function addProp<O extends object, P extends Exclude<union string | union number, keyof O>, V>(obj: O, prop: P, value: V): asserts obj is obj & {P: V} { ... }
```

This is also useful for excluding certain numbers such as 0 from being valid values for a variable or argument.

```ts
function divide(a: number, b: Exclude<union number, 0>): number { ... }
```

Currently I'm asserting the object to `never`, which acts as a sort of fake error message the next time any property on the object is accessed. This doesn't always work and may be hard to trace back to the culprit function.

**Comment by MartinJohns** [comment] 2021-08-02 12:07
This is essentially a duplicate of #29317.

**Closed** 2021-08-02 13:28 UTC
