### ISSUE TITLE
Code Navigation broken in VS Code 1.6 

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11221] opened 2016-09-28 20:49 UTC
VS Code Insiders 1.6

![image](https://cloud.githubusercontent.com/assets/2449568/18931572/9d041014-8581-11e6-8c71-574f452b837b.png)

![image](https://cloud.githubusercontent.com/assets/2449568/18931598/b14215a8-8581-11e6-8e2f-2e852dd27391.png)

Code to copy and paste

jsconfig.json

```javascript
{
	// See https://go.microsoft.com/fwlink/?LinkId=759670
	// for the documentation about the jsconfig.json format
	"compilerOptions": {
		"target": "es6",
		"module": "commonjs",
		"allowSyntheticDefaultImports": true
	},
	"exclude": [
		"node_modules",
		"bower_components",
		"jspm_packages",
		"tmp",
		"temp"
	]
}
```

foo.js

```javascript
var bar = require('./bar');

function foo() {
    this.x = 0;
    this.y = 'hello';
}
```

bar.js

```javascript
var _ = require('lodash');

function testFun() {
    console.log('bar');

    this.w = 0;
    this.z = 'hello';
}


module.exports.testFun = testFun;
```

I've also installed lodash typings

![image](https://cloud.githubusercontent.com/assets/2449568/18931694/1f3fa4da-8582-11e6-834e-3bd1d474a0bf.png)

Note that Go to definition and peek will work for methods

![image](https://cloud.githubusercontent.com/assets/2449568/18931723/3a6aa340-8582-11e6-96f5-fb77f3bf7494.png)

![image](https://cloud.githubusercontent.com/assets/2449568/18931744/4c3be8c2-8582-11e6-936f-b5a97823f944.png)

**Comment by mhegazy** [comment] 2016-09-29 04:53
duplicate of https://github.com/Microsoft/TypeScript/issues/9251

**Closed by mhegazy** 2016-09-29 04:53 UTC
Labels: Bug, VS Code Tracked
