### ISSUE TITLE
Casing of output js and js.map files is not consistent.

### ISSUE THREAD

**Issue by Vossekop** [Microsoft/TypeScript#2011] opened 2015-02-11 20:41 UTC
It seems my initial assessment was incorrect (see a bit below what I originally thought happened). It turns out the output filename of a typescript file is not cased the same as the typescript file, but the same as the casing in the reference path another typescript. So if I have one file name CamelCased.ts and one called pascalCased.ts. And I put a reference to camelCased.ts in that last one, this will compile but the output js file will be named camelCased.js and not CamelCased.js as I would have expected.

I don't know if I would call this a bug, but it sure is inconvenient.

[Original]
In a visual studio project containing multiple ts files some start with a capital, and some are all lower case. After the TypeScriptCompile action is called for a file using only lower case, all subsequent file outputs are lower cased, even for ts files that start with a capital.

Files that start with a capital who are compiled before the first lower cased file all have outputs that start with a capital letter.

I know I should be more consistent in my naming, but if you ask me, it's a rather subtle way of forcing me....
[/Original]

**Comment by mhegazy** [comment] 2015-03-24 17:13
The compiler currently issues an error of a file name is uses with inconsistent cases only on case sensitive systems. see [getSourceFileFromCache](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/program.ts#L362).

A good change is to make this controlled by a flag, so that you get errors for inconsistent casing for file references, ensuring that the files are always generated in a consistent manner.

**Comment by jkristia** [comment] 2015-05-21 02:41
I would consider this a bug. The compiler (in my opinion) should not be default change the file name casing. Even if I happened to name my file in a non standard way, the compiler should maintain the naming for the js file.
I just moved my project to Linux and was surprised of the many errors I got. It was only then I looked at the generated js files, and noticed the inconsistency in the generated file names

**Comment by mhegazy** [comment] 2015-05-21 19:51
@jkristia the problem is getting the actual file name from disk can be expensive, and most of the users do not care about it. this is why the compiler uses the first name of the file it encounters to identify it, be it on the command line, ///reference or import. I would assume that you have some inconsistent casing for file references in your project (either build script or /// reference); would me earlier suggestion of adding a flag to ensure you really reference all files consistently not work for you?

**Comment by bleiddyn** [comment] 2015-06-25 21:12
This issue caused me a few hours of confusion as well. If the file system check is expensive, perhaps we could add a fallback to case-insensitive when the compiler has trouble finding the file?

As an aid for people who have the same issue, the compiler error I was getting said, rather unhelpfully, "Module cannot be aliased to a non-module type."

**Comment by rscholey** [comment] 2015-07-04 05:49
+1 million - One of our team members is having exactly the same problem and has been trying to fix this for the last hour with no luck.

**Comment by benliddicott** [comment] 2015-09-08 14:17
Is a filesystem check actually that expensive? This has been profiled?
See also #3626

**Comment by vladima** [comment] 2015-10-27 20:19
#5275 introduces a flag `forceConsistentCasingInFileNames` - when it is set compiler will report an error if some file has multiple references with inconsistent casing inside the program

**Comment by vladima** [comment] 2015-10-27 21:06
fixed in e811fecda645cd7905821d48fcf5f757dbedfa50

**Closed by vladima** 2015-10-27 21:06 UTC
Labels: Accepting PRs, Suggestion

**Comment by mhegazy** [comment] 2015-10-27 23:54
The fix should be in `typescippt@next` tonight. Use the new `--forceConsistentCasingInFileNames` command line argument to make sure you are catching casing issues consistently.
