### ISSUE TITLE
error casting interface union field

### ISSUE THREAD

**Issue by codemau5** [Microsoft/TypeScript#20889] opened 2017-12-25 09:04 UTC
**TypeScript Version:**  2.6.2

**Code**

```ts
interface A1 {
    type: "A1";
}
interface A2 {
    type: "A2";
}
type AU = A1 | A2;

function foo(obj1: AU) {
    const obj2: AU = {
        type: obj1.type
        /*
        Error TS2322:
        Type '{ type: "A1" | "A2"; }' is not assignable to type 'AU'.
            Type '{ type: "A1" | "A2"; }' is not assignable to type 'A2'.
            Types of property 'type' are incompatible.
            Type '"A1" | "A2"' is not assignable to type '"A2"'.
            Type '"A1"' is not assignable to type '"A2"'.
        */

    };
}
```

**Expected behavior:**
create a new object with the same value of the first object.

**Actual behavior:**
typescript error TS2322:
Type '{ type: "A1" | "A2"; }' is not assignable to type 'AU'.
    Type '{ type: "A1" | "A2"; }' is not assignable to type 'A2'.
    Types of property 'type' are incompatible.
    Type '"A1" | "A2"' is not assignable to type '"A2"'.
    Type '"A1"' is not assignable to type '"A2"'.

**exampe in TypesSript Playground:**
https://www.typescriptlang.org/play/index.html#src=interface%20A1%20%7B%0D%0A%20%20%20%20type%3A%20%22A1%22%3B%0D%0A%7D%0D%0Ainterface%20A2%20%7B%0D%0A%20%20%20%20type%3A%20%22A2%22%3B%0D%0A%7D%0D%0A%0D%0Atype%20AU%20%3D%20A1%20%7C%20A2%3B%0D%0A%0D%0Afunction%20foo(obj1%3A%20AU)%20%7B%0D%0A%20%20%20%20const%20obj2%3A%20AU%20%3D%20%7B%0D%0A%20%20%20%20%20%20%20%20type%3A%20obj1.type%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A

**Comment by jcalz** [comment] 2017-12-26 01:12
Duplicate of #12052 ?

**Comment by DanielRosenwasser** [comment] 2017-12-26 07:26
Using a type assertion syntax actually does work here.

```ts
interface A1 {
    type: "A1";
}
interface A2 {
    type: "A2";
}

type AU = A1 | A2;

function foo(obj1: AU) {
    const obj2 = {
        type: obj1.type
    } as AU;
}
```

**Comment by codemau5** [comment] 2017-12-26 14:58
@DanielRosenwasser the issue you labeled this as a duplicate of, is labeled as "intended behavior",
because { type: "A1" | "A2"; } !== { type: "A1"; } | { type: "A1" ; },
otherwise if we had more fields, we can get an unstable behaviour.

looking into it, I found that you **do get unstable behavior** using the fix you commented!!

```ts
interface A1 {
    typeA: "A1";
    typeB: "B1";
}
interface A2 {
    typeA: "A2";
    typeB: "B2";
}
type AU = A1 | A2;

function foo(obj1: AU, obj2: AU): AU {
    const obj3: AU = <AU>{
        typeA: obj1.typeA,
        typeB: obj2.typeB
    };
    return obj3;
}

const a1: A1 = {
    "typeA": "A1",
    "typeB": "B1"
}
const a2: A2 = {
    "typeA": "A2",
    "typeB": "B2"
}

const a3: AU = foo(a1, a2);

console.log(a3.typeA, a3.typeB);
// A1 B2

```

a3 is of type AU, but is in an **invalid state!!**

if you would try to create such an object, you would normally get this error:
```ts
const au: AU = {
    typeA: "A1",
    typeB: "B2"
};
/*
Type '{ typeA: "A1"; typeB: "B2"; }' is not assignable to type 'AU'.
  Type '{ typeA: "A1"; typeB: "B2"; }' is not assignable to type 'A2'.
    Types of property 'typeA' are incompatible.
      Type '"A1"' is not assignable to type '"A2"'.
*/
```

**Closed** 2018-01-09 20:36 UTC
Labels: Duplicate
