### ISSUE TITLE
String.split() does not return correct type

### ISSUE THREAD

**Issue by mulholio** [microsoft/TypeScript#36547] opened 2020-01-31 15:27 UTC
**TypeScript Version:**  3.7.5

When calling `String.prototype.split`, the return type of this function is listed as 'string[]`, even though values may be undefined. The return type should therefore be `Array<string | undefined>`.

**Search Terms:** String.split, split, split-type

**Code**

```
const s: string = 'one/two';
const split = s.split('/');
const [one, two, three] = split;

console.log(two);   // 'two'     -> correct
console.log(three); // undefined -> incorrect type!
```

[Playground Link](https://www.typescriptlang.org/play/index.html?ssl=6&ssc=52&pln=1&pc=1#code/MYewdgzgLgBBBccoCcCWYDmMC8MDk4ApgPRQDuIeA3AFCiSwQAOANqrLhAHTNtQAUeYngCUtetBgBtIgBoY5EPKgALZIUIBdHHFbtadcBBAtCXFiAz9FYmHeLF8ivHdcBaAHwxQydcCiGkCZmFlaq6oS2DjAArmAAJoQAZuiE8TCeMOg+frBQAJ5MhACEQA)

**Expected behavior:** Return type is an array of strings or undefined

**Actual behavior:** All elements of array are typed as strings.

**Comment by jcalz** [comment] 2020-01-31 15:48
Essentially a duplicate of #13778.  All arrays would have to include `| undefined` in order to prevent this situation.

**Closed** 2020-01-31 17:42 UTC
Labels: Duplicate
