### ISSUE TITLE
Destructing arrays

### ISSUE THREAD

**Issue by wallverb** [Microsoft/TypeScript#9816] opened 2016-07-19 13:27 UTC
**TypeScript Version:**  2.0.0-beta

`noImplicitAny` enabled

**Code**

```ts
        const k = [5] 
        const [test] = k // ok
        const [test2] = [5]  // error
```

**Expected behavior:**
Should compile fine

**Actual behavior:** 
Throws error on line 3 `Binding element 'test2' implicitly has 'any' type`

Sorry if duplicated, couldn't find one

**Comment by mhegazy** [comment] 2016-07-19 17:05
Duplicate of https://github.com/Microsoft/TypeScript/issues/8229

**Closed by mhegazy** 2016-07-19 17:05 UTC
