### ISSUE TITLE
VS2015 Intellisense not working with HTML in TSX file

### ISSUE THREAD

**Issue by pealmeid** [Microsoft/TypeScript#5201] opened 2015-10-10 10:55 UTC
I'm beginning to use TypeScript to replace JS in my VS2015 projects, but I can't seem to figure out what is happening in a React project. I converted the JSX to TSX without any problems, but when I try to edit the 'render' method it seems as if Intellisense is not able to parse the HTML:

![tsx1](https://cloud.githubusercontent.com/assets/6384219/10410764/dd2d7df0-6f21-11e5-8475-887b6b689741.png)
(VS correctly identifies the beginning `'<div>'`)

But when I try to type the closing `'<div>'`, Intellisense does not show the correct option:
![tsx2](https://cloud.githubusercontent.com/assets/6384219/10410791/a4c78a7c-6f22-11e5-93ad-8676ce32a8b4.png)

Am I missing something? If I "force" the editor to produce the correct HTML it compiles without errors, but during the editing I keep getting autocomplete errors.

Thanks in advance.

**Comment by pealmeid** [comment] 2015-10-10 11:07
Added note: Intellisense works without any problems on JSX files. This is only happening with TSX files. Also, I have added the reference to `react.d.ts` on my TSX file. Thanks again.

**Comment by SaschaNaz** [comment] 2015-10-10 12:35
#5088 also says this problem.

**Comment by mhegazy** [comment] 2015-10-10 18:48
Looks like a duplicate of #5088 as @SaschaNaz mentioned. Should have a fix out soon. Sorry for the trouble. Please let us know if you run into other issues during the conversion.

**Closed** 2015-11-22 14:35 UTC
Labels: Duplicate
