### ISSUE TITLE
Breakpoints in ASP.NET 5 Web Application

### ISSUE THREAD

**Issue by Sharpiro** [Microsoft/TypeScript#4021] opened 2015-07-24 19:07 UTC
I have been experimenting with Visual Studio 2015 RTM and Typescript 1.5.3.  After setting up gulp-tsc to generate sourcemaps in an ASP.NET 5 Web Application, i have been able to get breakpoints to be hit in the project, and even go to the correct line.

However, as soon as the breakpoint is hit, it goes to the Javascript file rather than the Typescript file, which is not acceptable.

Am I missing anything, and/or is there plans in the future to support debugging in ASP.NET 5 projects?

**Comment by NoelAbrahams** [comment] 2015-07-27 19:18
I've logged a similar set of issues with debugging NTVS projects: Microsoft/nodejstools#324.

To quote:

> I also notice that VS is not letting me set breakpoints in certain valid places. The breakpoint keeps slipping. And VS keeps breaking in the JavaScript file instead of the TypeScript file, where the breakpoint was set.

> The combination of these problems makes it rather difficult. We can improve the reliability of the debugging experience by:

>* Ensuring breakpoints are settable where required in TypeScript file (i.e. solve the slipping problem)
* Ensuring the debugger only every hits breakpoints in TypeScript files, instead of the JavaScript.
* Solve the problem of the occasional hang.

**Comment by sheetalkamat** [comment] 2015-08-17 17:52
@Sharpiro , could you please share your sample project that you are having issues with breakpoint. It would be easier to investigate it futher. Thanks.

**Comment by Sharpiro** [comment] 2015-08-19 00:53
@sheetalkamat 
Here is the link: https://github.com/Sharpiro/Asp5Testing

it's pretty much a default MVC app in ASP.NET 5 VS 2015 at this point.

my test TS files are under "wwwroot/app" and are currently being combined into "testOutput.js" via GULP with the associated MAP file in that same directory.

Putting a breakpoint in any of the 3 .ts files while the project is running and refreshing Internet Explorer will result in the breakpoint dissapearing from the .ts files and being hit on the corresponding line of the .js output file.

When you stop debugging, the breakpoint will reappear in the .ts files.

**Comment by sheetalkamat** [comment] 2015-08-19 23:05
@Sharpiro: It seems like the sourcemap generated is wrong. This is my folder structure
![folderstructure](https://cloud.githubusercontent.com/assets/8052792/9370618/7edf2104-4686-11e5-8778-27b4fed9af72.JPG)

The map has:
![sourcemap](https://cloud.githubusercontent.com/assets/8052792/9371226/e0a87be2-468b-11e5-82f9-f78aab289747.JPG)

So it is expecting file at:
file:///E:/GitHub/Asp5Testing/src/Asp5Testing_Web/wwwroot/wwwroot/app/testOne.ts

Which seems incorrect. You need to use sourceRoot option to set the place where to look for sources

**Comment by Sharpiro** [comment] 2015-08-19 23:56
@sheetalkamat 

After following your advice I was able to get it working by specifying the sourceRoot option in Gulp.

Thanks for your help.

**Comment by mhegazy** [comment] 2015-08-20 00:00
looks like the issue is resolved. closing.

**Closed by mhegazy** 2015-08-20 00:00 UTC
Labels: Bug, Needs More Info, Visual Studio
