### ISSUE TITLE
Strict null: missing a case for arrays

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#34595] opened 2019-10-19 15:24 UTC
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
strict null array

**Code**

```ts
const someStringArray: string[] = [];
const someString = someStringArray.filter(_ => false)[0];

console.log(someString.length);
```

**Expected behavior:**
`someString` is `string | undefined`

**Actual behavior:**
`someString` is `string`

**Comment by bpasero** [comment] 2019-10-19 15:26
Simpler repro:

```ts
const someStringArray: string[] = [];
const someString = someStringArray[100];

console.log(someString.length);
```

**Comment by MartinJohns** [comment] 2019-10-19 15:48
This is a duplicate of #15661 (and #13778). This behavior is by design.

**Comment by bpasero** [comment] 2019-10-19 16:01
This means TS is loosing type information:

IS
```ts
function something(index: number): boolean {
    const item = foo[index];

    return item && item.pinned;
}
```

MUST BE
```ts
function something(index: number): boolean | undefined {
    const item = foo[index];

    return item && item.pinned;
}
```

**Comment by MartinJohns** [comment] 2019-10-19 16:06
Yes, that is true. But again: this is intentional, it's by design. Otherwise nearly every array-access needs to be checked for `undefined`, and the TypeScript team did not consider this acceptable. Also TypeScript does not aim to provide a sound type-system (non-goal 3).

There's the open issue #13778 to introduce a compiler-option to change this behavior.

**Closed** 2019-10-19 16:10 UTC
