### ISSUE TITLE
parseInt and parseFloat should accept any and not just strings

### ISSUE THREAD

**Issue by MoritzKn** [microsoft/TypeScript#38471] opened 2020-05-11 16:23 UTC
**TypeScript Version:**  3.8.3 (playground)

**Search Terms:**
- "parseInt any"
- "parseInit type"
- "parseInit string"
- "parseFloat any"
- "parseFloat type"
- "parseFloat string"

**Code**

```ts
const maybeNumber: number | string = 1;

// The issue: parseInt only accepts strings so this fails,
// even though the runtime happily accepts any value...
const asNumber1 = parseInt(maybeNumber, 10)

// So the solution would be:
// Convert the number toString() and the string toString() so we can be sure that we never 
// pass numbers into the parseInt function...
const asNumber2 = parseInt(maybeNumber.toString(), 10)

// Or, better do a type check. But we are still duplicating a type check that already exits in the runtime... :/
const asNumber3 = typeof maybeNumber === 'string' ? parseInt(maybeNumber, 10) : maybeNumber

// Or simply accept defeat and out out
const asNumber4 = parseInt(maybeNumber as string, 10)
```

**Expected behavior:**

`parseInt` and `parseFloat` accepts `any`. 

The [spec](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-parseint-string-radix) gives the function the signature `parseInt ( string, radix )` but also states that the argument will be converted to string internally (`Let inputString be ? ToString(string).`).

In my opinion, the type system should allow relaying on the behavior:

1. It improves usability
2. Adding runtime checks creates bigger bundles and slower code (even if only by a tiny margin)

IMHO duplicate type checks should not be encouraged.

**Actual behavior:**

The first `parseInt` call returns the type error:
```
Argument of type 'string | number' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'.(2345)
```

**Playground Link:** [here](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAcwKZQLIEMCeAjVAORAFsCAnACgEoAuRMUixAHwAKBnKcmMZRAN4BYAFCJEMYIkrYoACwB05LGAAmcEjUQA+RAoCs1QaPHjy6EOSQAWAEwnEAX0SoANh1TGxp81EtIAcgA2EICHR1EIkVEIBC5EElwCYjJUcnpGVPJWTm5efgBeFHRsfCImNJoAblFRAHo6xAAVOU8YDg4QVHoAByxyDwBJMChEBFccRCwICFQeqA5ELh4+RY44RHl2xGAsGHcAGnrG1AA3VCR5OBBkOU3WxHJwWBJPOSwenv3J6dn5xZUk1OWFcXQU4JicVGWA4KQoAEZEEU+gNUMMoJREmU4WkDoh4QAGai1EQNRAAZQ28k861BsAQiAA7tdXKpEARaMdEABhBDncijakMCrZKBwcl5PhaFRsoXLfKbcWS5BadZMzwQFTsmmWTzyLCjRmeMBnNKILl9DrCrKLXhi+6eFFDEY7cDQeBgcEKSFgeIwnHkWxIxBOtEjTFJcpZBRiiUrFXUPGE4nRUmNADy5DxBCgUDN6immxwPQ1rQgAGsFIgAEIgQ2efo02CuVyIVQgHquGCa2B8QtQYul1AV+4GqaucxYVSTVAADxgCwklweTxGMFeXsQtDqPr9sJFAGZgwOS3ApFjkiKkQUigF5XwAogAPwh-rOjEXqMUJNErcJSMBiSZKZks66dj8MxzKMqioMAqAGru0L7lk1jBqG6IRtiV4wksyo-imohAA)

**Comment by MartinJohns** [comment] 2020-05-11 16:29
Duplicate of #17203. Search terms: `parseFloat`.

**Comment by MoritzKn** [comment] 2020-05-11 22:02
Sorry, I missed that one. If the desition was made that this behavior is intended, I accept it and don't want to repeat the argument. But if you are willing to revisit this, IMHO it would be an improvement. 

I already made my argument above but I have one small addition:
In my experience types like `string | number` (or `any` but it's probably a number) are common when taking input from outside TS where you are not 100% sure what the types are. In these cases adding a runtime conversion seems more appropriate to me than a type assertion (`as number`) and a type check using `typeof` seems overly verbose.

**Comment by RyanCavanaugh** [comment] 2020-05-11 23:20
`parseInt(3e20)` is `3e20` but `parseInt(3e21)` is `3`. This is *not* a process you should put arbitrary data through. If you really want to, add a type assertion, because this is a very dangerous process.

**Comment by MoritzKn** [comment] 2020-05-12 07:56
Fair point. Though I'd like to point out that `parseFloat(Number.MAX_VALUE) === Number.MAX_VALUE` works and `parseInt(Number.MAX_SAFE_INTEGER) === Number.MAX_SAFE_INTEGER` also works. It's just that when you get out of the integer range that you start getting unexpected behavior.

But perhaps is going to be enough for me to actually start writing `typeof foo === 'number' ? foo :  parseInt(foo, 10)`.

**Closed** 2020-05-14 18:00 UTC
Labels: Duplicate
