### ISSUE TITLE
Stricter type aliases

### ISSUE THREAD

**Issue by d180cf** [Microsoft/TypeScript#5952] opened 2015-12-06 05:33 UTC
Let's say we have an alias for `number`:

```ts
/** bits 0..3 = x, bits 4..7 = y, bit 31 = always 1*/
type coords = number;
/** x = 0, y = 0 */
const zero: coords = 0;
```

The `zero` variable, despite being of type `coords`, will act everywhere as though it's a plain number: the language service will say that it's a number, the compiler will treat it as a plain number and so on. However the `coords` type is not just a number because it has some internal structure and because not every value of type `number` is a value of type `coords` (in other words, the set of values in `coords` is smaller than the set of values in `number`).

It would be nice if the language service displayed the proper type name in such cases and if the compiler put some constraints on operations with such custom types, e.g. `const zero: coords = 0` should error because `0` is of type `number` which may be (the compiler doesn't know) wider than `coords`.

**Comment by DanielRosenwasser** [comment] 2015-12-06 06:22
#364 is definitely related. So is #202 to some extent.

**Comment by DanielRosenwasser** [comment] 2015-12-06 06:25
As for the language service displaying the declared name, it's probably better not to do that so that users understand what they're actually dealing with. It would be inappropriate to give users the impression that the language is doing what this proposal asks for with respect to the `type` keyword.

**Comment by GoToLoop** [comment] 2015-12-08 03:04
As a very poor workaround I'm using empty enums. For example:
```ts
declare const enum coord {}
declare const enum size {}

type xy  = [coord, coord]
type wh  = [size, size]

mouseX:  coord
mouseY:  coord

width:  size
height: size

ellipse(x: coord, y: coord, w: size, h: size): this
```

**Comment by mhegazy** [comment] 2015-12-08 04:01
also related https://github.com/Microsoft/TypeScript/issues/4895

**Comment by mhegazy** [comment] 2015-12-09 00:58
looks like a dupe of #2477

**Closed by mhegazy** 2015-12-09 00:58 UTC
Labels: Needs Proposal, Suggestion

**Comment by d180cf** [comment] 2015-12-09 04:36
@GoToLoop, that's actually a decent workaround. Thanks!
