### ISSUE TITLE
potential JavaScript error ignored with in operator and type {}

### ISSUE THREAD

**Issue by killmag10** [microsoft/TypeScript#56364] opened 2023-11-10 15:21 UTC
### 🔎 Search Terms

"in","operator","{}","type","ignored"

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2&ssl=16&ssc=16&pln=1&pc=1#code/GYVwdgxgLglg9mABAGzgcwDIFMxqgCwAoA3AQ2RCwC5EBvAXwEo6BYAKEU8QHpvEB3OACcA1gGdEMJAClSZAMoQhMAA5REAIxDqAKgE8VWRcrWICQuPwmkkWIRaHsuk4IkJQDWOK7IUsAOmQcPHxEAF4IxAByMBAAWw07KOZaJ2cuCAQxOCDA9EIooNwCSTEaKMQAakRfSkDggkYAbjTOenZWnj4wOEQ7B0kkfUNjVXUtdSlEWQUlMc6YVwKikIqp2qwUzudMsGzc1DRCACJgOHAAExQG-GPmzvoWtna2dl2xdTgNACtwuhWCDQAKyPDpsQ7YYpEY6kRAfZS4O5PCE3Qhfb7NIA

### 💻 Code

Short example:
```ts
let v : {} = "a string";

if ('length' in v) {
    console.log("can't work");
};
```
Full example:
```ts
function logLength(value: {}) {
    // works in JavaScript but TypeScript throws an error
    if (typeof value.length === 'number') {
        console.log('length is: ' + value.length);
    }

    // no error in TypeScript but in JavaScript
    if ('length' in value) {
        console.log("found length");
    };
}

const obj = {length: 5};

logLength("a string");
logLength(obj);
```

### 🙁 Actual behavior

No Typescript Error but a JavaScript Error.
Error: `cannot use 'in' operator to search for "length" in "a string"`

### 🙂 Expected behavior

Typescript should throw an Error.

**Comment by MartinJohns** [comment] 2023-11-10 16:10
These are both design limitations. In general the `in` operator is fairly unsound.

**Comment by jcalz** [comment] 2023-11-10 17:09
essentially duplicate of #43210

**Closed** 2023-11-13 01:28 UTC
Labels: Duplicate
