### ISSUE TITLE
Regression with 'out' in `(out as number)`

### ISSUE THREAD

**Issue by DavidSouther** [microsoft/TypeScript#49021] opened 2022-05-09 03:38 UTC
# Bug Report

### 🔎 Search Terms

regression 4.6 4.7 4.8 out as

### 🕗 Version & Regression Information

This bug is present in "Nightly 4.8.0-dev20220508", it is not in 4.6.2

- This changed between versions 4.6.2 and 4.7.0-dev.20220415 (including 4.8.0-dev.20200508)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220508#code/DYUwLgBA9grpC8ECsBuAsAKAMZQHYGdIBDCRAClmPwlxgFsAjEAJwEp0NNRIooFkOOApAakIFPhCLVajFuyA)

### 💻 Code

```ts
let out = 5;
const a = (out as number);
```

This is reduced from a larger expression, where the parens are necessary to nest the cast inside a ternary operation.

```
class Foo {
  constructor(
    outs: (string | { id: string; start: number })[],
  ) {
    for (const out of outs) {
      const { id, start = 1 } =
        (out as {id: string}).id !== undefined
        ? (out as { id: string; start: number })
        : parse(out as string);
      console.log(id, start);
    }
  }
}
```

### 🙁 Actual behavior

Compiles to
```
let out = 5;
const a = (as, number) => ;
```

This looks like the new [Optional Variance](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#optional-variance-annotations-for-type-parameters) rules are identifying these parentheses as an arrow function, when they are just nesting the cast.

### 🙂 Expected behavior

```
let out = 5;
const a = out;
```

This is a paren-wrapped cast, not a function declaration.

**Comment by DanielRosenwasser** [comment] 2022-05-09 04:16
Ugh, this is a duplicate of https://github.com/microsoft/TypeScript/issues/44466, but it's now a regression in more code due to TS 4.7's addition of `out` as a contextual modifier.

```ts
// @declaration: true

let readonly: any;
let override: any;
let out: any;
let declare: any;

const a = (readonly as number);
const b = (override as number);
const c = (out as number);
const d = (declare as number);
```

**Closed** 2022-05-10 23:37 UTC
Labels: Bug, Fix Available
