### ISSUE TITLE
TS 3.9 Breaks generator method type inference

### ISSUE THREAD

**Issue by NullVoxPopuli** [microsoft/TypeScript#38534] opened 2020-05-13 10:51 UTC
**TypeScript Version:**  3.9.2

**Search Terms:**
generator

**Code**
![image](https://user-images.githubusercontent.com/199018/81803033-150fcc80-94e5-11ea-8193-dbd84d0758ce.png)

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```
```ts
class Foo {
    *search(term: string) {
        let [a, b] = yield Promise.all([getA(), getB()]);

        console.log(a, b);
    }
}

function getA() {
    return Promise.resolve(1);
}

function getB() {
    return Promise.resolve({ b: 2 });
}
```
**Expected behavior:**
Same inference as 3.7? I don't see a resolution here, as it seems _any_ yielded type wants to be a part of the "return value", and that could be _incredibly_ verbose for some generator functions.

**Actual behavior:**
![image](https://user-images.githubusercontent.com/199018/81803212-57d1a480-94e5-11ea-9061-2a742b7ef84b.png)

**Playground Link:** 
https://www.typescriptlang.org/play/#code/FDDGBsEMGdoAgGIHslwN7DluAqaBTSAJ1AAsAKAF3yIFsAuOaSogSwDsBzASnU2wHh8lOAG1IAGjgAjALpwAvHACerfOAAmcAApEktVgQB0kcOHKjOwgILluUq5QBCd2dwDcIAQNBJ20JCEjcCROckkZD34sAF9gOOAAMwBXdlBKVj84R1teDAEiYWSidh09A2NCgPAAN3xyAEYohJS0jKzHFzzouELKYtLdfUN8IyrAuvI0GUYAJjgY5qA

Here is the same code on 3.7:
https://www.typescriptlang.org/play/?ts=3.7.5#code/FDDGBsEMGdoAgGIHslwN7DluAqaBTSAJ1AAsAKAF3yIFsAuOaSogSwDsBzASnU2wHh8lOAG1IAGjgAjALpwAvHACerfOAAmcAApEktVgQB0kcOHKjOwgILluUq5QBCd2dwDcIAQNBJ20JCEjcCROckkZD34sAF9gOOAAMwBXdlBKVj84R1teDAEiYWSidh09A2NCgPAAN3xyAEYohJS0jKzHFzzouELKYtLdfUN8IyrAuvI0GUYAJjgY5qA

**Related Issues:**

**Comment by rbuckton** [comment] 2020-06-27 01:05
The problem is that `a` and `b` are untyped, and there is no way for the generator to know what `yield` returns without the return type annotation. The error you are seeing is due to the implicit `any` for `a` and `b`. Prior to 3.9, `a` and `b` would still have been `any`, but we didn't issue an implicit-any error (and we should have).

There are two ways to resolve the error:
- Add an explicit return type annotation to `search`
- Add an explicit type annotation to the variable declaration: [example](https://www.typescriptlang.org/play/#code/FDDGBsEMGdoAgGIHslwN7DluAqaBTSAJ1AAsAKAF3yIFsAuOaSogSwDsBzASnU2wHh8lOAG1IAGjgAjALqNR7AK61pNKWhmNlqmnAC+suAF44AT1b5wAEzgAFIklqsCAOkjhw5UZ2EBBcm4pX0oAIUDZbgBuEAEBUCR2aCQhV3AkTnJJGWj+LH1gAuAAMyV2UEpWRLgQgN4MASJhJSJ2e0dnNybk8AA3fHIARlyi0vLK6pDw+ry4JsoWtocnF3xXbpT+8k1pRgAmAxGgA)

There is currently no way in the type system to craft a return type that determines how a type should flow from the output (right-hand) side of a `yield` and the input (left-hand) side of a `yield`.

**Comment by rbuckton** [comment] 2020-06-27 01:11
I'm closing this for now, as the error you are seeing is intended. I am still considering ways to approach how to connect the input and output types of a `yield` to be used in conjunction with some form of evaluator (similar to `co`), but even that case would require an explicit return type annotation since `yield` on its own does not inform how or if the input and output types are connected.

**Closed by rbuckton** 2020-06-27 01:11 UTC
Labels: Working as Intended
