### ISSUE TITLE
Optimization tools or guidelines

### ISSUE THREAD

**Issue by jbondc** [microsoft/TypeScript#3594] opened 2015-06-22 12:42 UTC
a) Which tools or guidelines are recommended for optimizing TypeScript?

V8/node has some pretty good tools:

```
node --prof bench/parse.js
node --trace_opt --trace_deopt bench/parse.js
```

http://mrale.ph/irhydra/2/

There's NodeJS tools in Visual Studio, wondering if there's anything specific for Chakra that I can use today.  

https://github.com/Microsoft/node

b) Which non v8 specific tools exist today?

**Comment by DanielRosenwasser** [comment] 2015-06-22 13:22
@vladima, @CyrusNajmabadi, and @mhegazy might be well-suited to answering this.

You can use the F12 tools in Edge (Project Spartan) and IE to do some profiling (and the same goes for Chrome as well).

I believe you can accomplish this by running the tests in the browser:

```Shell
jake runtests-browser
```

**Comment by mhegazy** [comment] 2015-06-23 17:11
We have a perf test script that we run against node, and tsc.exe (which is a Chakra wrapper). the script it self can be posted, the issue is we run it on snapshots from some user code bases that we do not have permissions to open them. we can open the script if this helps.

**Comment by vladima** [comment] 2015-06-23 18:30
also there is a set of helpers that allows to host language service on the web page and perform a targeted profiling of different aspects of LS functionality using built-in browser tools

**Comment by jbondc** [comment] 2015-06-24 15:35
@mhegazy That would be great, is there a plan to allow building the wrapper or that will be integrated in windows 10? I'm looking more for command line tools so I have an alternative to 'v8 optimization' and its specific type guessing.

**Comment by mhegazy** [comment] 2015-08-10 23:15
@yui can we put a version of the perf script in scripts\

**Comment by jbondc** [comment] 2015-09-21 21:30
Is the script a wrapper around this api?
https://msdn.microsoft.com/en-us/library/dn249552(v=vs.94).aspx

Don't mind writing it but would rather align around a common tool.

**Comment by DanielRosenwasser** [comment] 2024-03-04 22:22
For optimizing compilation of TypeScript and profiling the compiler/language service, I've written up https://github.com/microsoft/TypeScript/wiki/Performance

Otherwise, this sort of documentation is a bit out of scope for us.

**Closed** 2024-03-04 22:46 UTC
Labels: Docs
