### ISSUE TITLE
Compiler options into the TS code

### ISSUE THREAD

**Issue by jpolo** [Microsoft/TypeScript#1886] opened 2015-02-02 13:13 UTC
It would be really nice to have a way to get the compiler options into the code (like precompilation ifdef or something like that).
The main reason would be to make conditional code (=shim) conditionnally to the target ES version.

In term of code scalability, this would also help smooth transition to ES6.

**Comment by DanielRosenwasser** [comment] 2015-02-02 18:30
This may be a duplicate of #449.

**Closed** 2015-02-02 18:59 UTC
Labels: Duplicate, Suggestion
