### ISSUE TITLE
Improve Omit field type check

### ISSUE THREAD

**Issue by Joliwood** [microsoft/TypeScript#58164] opened 2024-04-12 12:45 UTC
### ⚙ Compilation target

ES2015

### ⚙ Library

Typescript

### Missing / Incorrect Definition

The Omit built-in generic type doesn't lock the field we provide to omit. 

### Sample Code

```TypeScript
/**
 * Construct a type with the properties of T except for those in type K.
 */
type Omit<T, K extends keyof any> = Pick<T, Exclude<keyof T, K>>;

With this code, we can ask typescript to omit a field that doesn't exist in T generic argument, instead of K extends keyof any, we could use Kextends keyof T.
```

**Comment by nmain** [comment] 2024-04-12 12:51
Duplicate of https://github.com/microsoft/TypeScript/issues/30825.

**Closed** 2024-04-12 15:08 UTC
