### ISSUE TITLE
Refactor Feature: String Concatenation to Interpolation

### ISSUE THREAD

**Issue by MgSam** [Microsoft/TypeScript#24910] opened 2018-06-12 19:52 UTC
## Search Terms

refactor, string, concatenation, interpolation

## Suggestion

A small but useful refactoring that could be offered is to turn one or more string concatenations into an interpolated string. The inverse operation is also potentially useful (turning an interpolated string into concatentations)

## Examples

``` TypeScript
let the = "the";
let foo = the + " quick" + " brown" + " fox" + " jumps" + " over " + the + " lazy" + " dog";

//Having cursor to left or right of + sign allows refactoring to convert to interpolated string ->

let foo = `${the} quick brown fox jumps over ${the} lazy dog`;

//Running the inverse operation on the result (converting an interpolated string into concatenation), would result in this -->

let foo = the + " quick brown fox jumps over " + the + " lazy dog";
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment] 2018-06-12 20:06
Duplicate of https://github.com/Microsoft/TypeScript/issues/18267

**Closed** 2018-06-13 17:29 UTC
Labels: Duplicate
