### ISSUE TITLE
Optional Chaining and Type Narrowing

### ISSUE THREAD

**Issue by arciisine** [microsoft/TypeScript#33736] opened 2019-10-02 02:37 UTC
## Search Terms
Optional Chaining

## Suggestion
Currently I use a pattern of an `in` check with a ternary to narrow type on optional fields. With the new optional chaining, it would be great if the type narrowing could occur as the optional chain is progressed.

## Use Cases
The primary use here is for type narrowing on union types without the need for extra boilerplate.

## Examples

Current method of using the `in` operator for type narrowing.
```typescript
type Header = { headers: Record<string, any> };
type Options = { config : any };

function getHeader(input: Header | Options, key: string, def?: any) {
   return ('headers' in input ? input.headers[key] : undefined) || def;
}
```

Improved syntax given optional chaining
```typescript
type Header = { headers: Record<string, any> };
type Options = { config : any };

function getHeader(input: Header | Options, key: string, def?: any) {
   return input.headers?.[key] ?? def;
}
```

## Checklist

My suggestion meets these guidelines:
* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by zhongliangwang** [comment] 2019-10-03 03:51
Thumb up to this issue. Type narrowing is not working with `if` blocks as well.

```ts
const 
```

Playground Link: https://www.typescriptlang.org/play/?ts=3.7-Beta#code/CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPAN7wBGshmMAligOYA08AtiBgBZLCEAUAlPAC8APngA3JNWDwAvvAA+8AK4pQ2WiGABuAFA7q2eD1xIA-ADpyMIYMHwA5AGUAqgGFXAUUeP7AojvhAnDxzVg4ufl0ZIA

**Comment by kingdaro** [comment] 2019-10-06 00:38
Maybe this is also related. I ran into an issue with narrowing discriminated unions:
```ts
type Shape =
    | { type: 'rectangle', width: number, height: number }
    | { type: 'circle', radius: number }

declare const shape: Shape | undefined

const radius = shape?.type === 'circle' && shape?.radius
```
This errors on `radius` in `shape?.radius`:
```
Property 'radius' does not exist on type 'Shape'.
  Property 'radius' does not exist on type '{ type: "rectangle"; width: number; height: number; }'.(2339)
```
[Playground](https://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=8&ssc=1&pln=1&pc=1#code/C4TwDgpgBAygFgQ0lAvAWAFBW1APlAbylEgC4oByAJwgGNgEA7AcwBsIKAaKAdwEsAJsDjlGAVwC2AIwhVucCH2ZxgoyTKpQAvphx5CxcBHIVafKrXZcoVBAL5iAzmumztmTALqsENKLQB7RkdgKEdEMlgI6HwxRi8AMz5GCAEPDEDg0Nt7J1Qw6IB+ADoSaBQKyjMLKygAMjqCpAgSnIdHTCA)

**Comment by Kingwl** [comment] 2019-10-07 08:18
Seems fixed in https://github.com/microsoft/TypeScript/pull/33821

**Comment by kingdaro** [comment] 2019-10-09 00:21
Found another similar problem: narrowing doesn't happen properly with `switch`
```ts
type Shape =
    | { type: 'rectangle', width: number, height: number }
    | { type: 'circle', radius: number }

function getArea(shape?: Shape) {
    switch (shape?.type) {
        case 'circle':
            return Math.PI * shape.radius ** 2
        case 'rectangle':
            return shape.width * shape.height
        default:
            return 0
    }
}
```
[Playground](https://www.typescriptlang.org/play/?ts=Nightly&ssl=14&ssc=2&pln=1&pc=1#code/C4TwDgpgBAygFgQ0lAvAWAFBW1APlAbylEgC4oByAJwgGNgEA7AcwBsIKAaKAdwEsAJsDjlGAVwC2AIwhVucCH2ZxgoyTKpQAvphx5CxcBHIVafKrXZcoVBAL5iAzmumztmTADMxjenwD2jFDMEMAAgjQIABSOiJAA-OTwSBAAlIS6OI78wLRwUDFxEPEAdCRpGVh6OLQIjtCm5pYcpJnV1TTAYlRBALIIwiUACgCSUABUULEpJbb2ThOTAExt1bX1lDT0TGwtq+3Ynd1B05Al-EL5k6cQJQpKKvs4AhCeCGKsqk-tRz1QAAyrHQYLRAA)

In the latest nightly as of this comment, this _does_ typecheck if I refactor this to if statements

**Comment by HoldYourWaffle** [comment] 2019-10-09 09:23
I think I'm encountering a similar issue when using the new assertion statements:

```ts
declare function assertNonNull<T>(x: T | null): asserts x is T;
declare const x: { y: T | null } | null;

assertNonNull(x?.y); // Assert y, implicitly assert x
doSomething(x.y); // Error: x is possibly 'null'; the implicit assert for x didn't work

assertNonNull(x); // Explicitly assert x
doSomething(x.y); // No error anymore, both x and y have been narrowed down correctly
```

I'm using the latest nightly as of 9 october.

**Comment by ryanquinn3** [comment] 2019-10-16 15:35
I've stumbled across what appears to be a similar issue to this one. 

Heres a link to the [playground](https://www.typescriptlang.org/play/?ts=Nightly&ssl=10&ssc=40&pln=10&pc=47#code/C4TwDgpgBAYhCGwCuAnCBnKBeKBvAsAFBRQCWAJgFxTrAqkB2A5gNxEklMQD2AthHRAB+agWIcSoSNVr1mbcRIDG3binKNEGagyS8ARhBQBtALoKJAXwXWidwgDMkDJcFLcGUCAA868VwDCquqawBgAFA7UcIioGACUOnqGJqZ47BykDlCRAHRcfAIowrlS0ACEWDgA5GG01fHpihJQAPStUMAAFqSYSvDo0Ohd3EgANuRQhlA9wGTZDvk8-IJkmM7kEA6MEJMZLVBoyCieZhYclvuHAqieiwUrxbkqahoMWug2QA).


The snippet:
```ts
type Feature = {
  id: string;
  geometry?: {
    type: string;
    coordinates: number[];
  };
};


function extractCoordinates(f: Feature): number[] {
    if (f.geometry?.type !== 'test') {
        // this case should be hit if f.geometry is undefined 
        return [];
    }
   // doesn't narrow f.geometry to the defined value
    return f.geometry.coordinates;
}
```

**Comment by Kingwl** [comment] 2019-10-17 10:40
@ryanquinn3 
```
// doesn't narrow f.geometry to the defined value
 return f.geometry.coordinates;
```
That seems expected behavior

**Comment by ahejlsberg** [comment] 2019-10-18 20:37
We have previously discussed and rejected the notion that

```ts
input.headers && input.headers[key]
```

should be permitted, since that only establishes that `input.headers` is truthy, but not what its exact type is (there is no declaration of a `headers` property in `Options` which is effectively the same has having a `headers` of type `unknown`).

The exact same argument holds for `input.headers?.[key]` and for that reason we won't implement this suggestion.

You could argue this is also true for the `in` operator--and you would be right. See discussion in #10485. But this doesn't change the fact that we don't want this behavior for the very common operation of property access using `.` or `?.`.

**Comment by ahejlsberg** [comment] 2019-10-18 20:38
Meanwhile, several comments on this suggestion have pointed out valid issues relating to control flow analysis of optional chaining constructs. We'll track those in #34570.

**Closed** 2019-11-19 00:08 UTC
Labels: Declined, Suggestion
