### ISSUE TITLE
function arguments pass by name

### ISSUE THREAD

**Issue by tangjfn** [microsoft/TypeScript#35724] opened 2019-12-17 10:29 UTC
## Use Cases

function test(a: string, b: number):void {
}

test(b:100,a:"100"); // js: test("100", 100)

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by dragomirtitian** [comment] 2019-12-17 11:04
This proposal does not statify this guideline:

> This isn't a runtime feature (e.g. library functionality, **non-ECMAScript syntax with JavaScript output**, etc.)

**Comment by MartinJohns** [comment] 2019-12-17 14:16
Duplicate of #467.

**Comment by RyanCavanaugh** [comment] 2019-12-17 19:30
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Closed** 2019-12-17 19:30 UTC
Labels: Duplicate
