### ISSUE TITLE
Proposal: Enchance typeguards to infer type based on the returned type

### ISSUE THREAD

**Issue by Akindin** [microsoft/TypeScript#60522] opened 2024-11-17 01:08 UTC
### 🔍 Search Terms

else typeguard, typeguard properties

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Allow explicitly specify the type of tested value based on the type of result.

### 📃 Motivating Example

This allows to break existing types into a user defined subtypes, for example for valid | invalid strings

``` typescript
function isValidEmail(value: string): value is ValidEmail otherwise InvalidEmail {
    return /^\S+@\S+\.\S+$/.test(value)
}

function updateEmail(email: ValidEmail) {
    // ...
}

function showEmailFormatError(email: InvalidEmail){
    // ...
}

let email = document.querySelector("#email").value;

if (isValidEmail(email)) {
    updateEmail(email);
} else { // infers the type from otherwise
    showEmailFormatError(email)
}

```

Getting a response type based on a status

```typescript
interface InProcessResponse {
  abort: () => void;
}

interface SuccessResponse {
  data: unknown;
}

interface ErrorResponse {
  errorCode: number;
  errorMessage: string;
}

function getStatus(response: unknown): 
    "success" means SuccessResponse |
    "pending" means InProcessResponse | 
    "error" means ErrorResponse | 
    "unknown" means unknown {
    //...
    return true
}

const response = getSomething();

switch(getStatus(response)) {
    case "success":
        // infers SuccessResponse
        break;
    case "pending":
        // infers InProcessResponse
        break;
    case "error":
        // infers ErrorResponse
        break;
    case "unknown":
        // infers unknown
        break;
}
```

### 💻 Use Cases

1. What do you want to use this for?
To ensure handling of special cases and validation.
2. What shortcomings exist with current approaches?
Need of typecasting and boilerplate
3. What workarounds are you using in the meantime?Either you make multiple typeguards [Playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAaghgGwJYBMCiBbOSFQLxQDOwATkgHYDmUAZFAN4BQULUSh8y6WOAXFKQCuERgF9GjUJCgBJcgDdEqTNlwFiZKrQbNW7Tsp4J+AM0SER4xicHkAxsCQB7cmw5LuqgBSKEw-hoUlACU-L7CbrAeKjg6rFAkEMCCJK4A9AB6ADoAygDUAAK5eVkAdMUAJGmlwBDEPojCwWISNvaOLm5yvobe4RABpEGhUP2R3dFGcayJyalQAISZxUX5ZZXVtfX9zVZtDs6ugmAocLUxCF4QRvwGnjjB0yxpaVCl7y3WtgedhAAWTgA7hcAGJOEhYYBoEgkcFXG6yBSTVTBJjxF5vD5WOwuYhQa6qfBQLwoJx2QQYCDkYClACOwhIIByEAQEAccIARABiAk4DmPOCEKAACQAKgBZAAycjAgihrMp1OCpX6AG4JEgTMT9MicPCUY80axjqdzkZ9Q91aJ8QgLGwtV52BMuBcLQhgobdCx-kDQeDIdDYSQ3bsbXajc9XqS6uQAOTAKAAa3IQIEfzOafYkXIEHkEBILSAA) or you cast types before using typeguard [Playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAaghgGwJYBMCiBbOSFQLxQDOwATkgHYDmUAZFAN4BQULUSh8y6WOAXFKQCuERgF9GjUJCgBJcgDdEqTNlwFiZKrQbNW7Tsp4J+AM0SER4xicHkAxsCQB7cmw5LuqgBSKEw-gaeOFAAPrIKHio4AJT8vsJusJFGOqxQJBDAgiSuAPQAegA6AMoA1AACJaWFAHRVACS5NcAQxD6IwtFiEjb2ji5QgmAocC1RCF4QRgHJqtGprLm5UDWr3da2Ds6uhAAWTgDu4wBiTiRYwGgkJGeT0+G+hnNMaUsra1Z2LsRQU6r4UC8KCcdkEGAg5GANQAjsISCBihAEBAHLcAEQAYj+ODR8zghCgAAkACoAWQAMnIwIJLsjwZDojV4tB8UkuONQg9ZjgANwSJAmQH6bkTbEIaLzF6sIYjMZGO5zPmiX4ICwLFh7Q4nM4XK43EgKmLdIA)

**Comment by jcalz** [comment] 2024-11-17 01:29
Why does `getStatus` return `true` and not `"success"` etc? 

`otherwise`: duplicate of `else` type guard suggessted at #15048,
`means`: duplicate of #31376 and/or #46650

**Comment by Akindin** [comment] 2024-11-17 15:12
Thanks for mentioning the related issues, they seem reasonably close to what I propose

> Why does `getStatus` return `true` and not `"success"` etc?
Oh sorry that was a stub

**Closed** 2024-11-29 01:33 UTC
Labels: Duplicate
