### ISSUE TITLE
Proposal: throw type

### ISSUE THREAD

**Issue by Jack-Works** [Microsoft/TypeScript#30289] opened 2019-03-09 05:47 UTC
## Search Terms
`throw` `type` `proposal` `expression` `language service`

## Summary
![image](https://user-images.githubusercontent.com/5390719/54066813-ba8c3800-4271-11e9-9732-e9e2d02f80e7.png)

Provide custom error message on type level. By `throw 'error message'` (which evals to `never`)

## Detail
Now we have type `never` to represent a type that has 0 value in it. But it does not provide enough information for it.

For example:
```ts
function divide10by<T extends number>(n: T): T extends 0 ? never : number
function divide10by(n: number): number {
    return 10 / n
}

divide10by(1) // number
divide10by(0) // never
const result = divide10by(0).toString()
// Property 'toString' does not exist on type 'never'.
```

This prevents we accidentally provide the wrong parameters. But it's not clear enough.

Let's imagine we get a new type of Type expression like this: `throw 'Any string'` that equals never but show error details in the language service.

```typescript
function divide10by<T extends number>(n: T): T extends 0 ? throw 'You cannot divided by zero' : number
function divide10by(n: number): number {
    return 10 / n
}

divide10by(1) // number
divide10by(0) // never, You cannot divided by zero
const result = divide10by(0).toString()
// Property 'toString' does not exist on type 'never'.
// You cannot divided by zero.
```

This is useful in complex types.

```typescript
class ElementOrTextArray<T> {
    map<NextType>(fn: (current: T) => NextType): ElementOrTextArray<NextType> { return {} as any }
    eachParentElement: T extends HTMLElement ? (() => ElementOrTextArray<HTMLElement>) : throw `Cannot invoke eachParentElement on type ${T}. ${T} is not a subtype of HTMLElement` = (() => {}) as any
}

const x = new ElementOrTextArray<string>().eachParentElement()
// ^ Cannot invoke an expression whose type lacks a call signature. Type 'never' has no compatible call signatures.
// Cannot invoke eachParentElement on type string. string is not a subtype of HTMLElement
const y = new ElementOrTextArray<HTMLDivElement>().eachParentElement()
// This is Okay
```
----------------------------------------------------------
## Grammar
```
// throw 'message'
<throw_type> ::= throw <string>
// throw `message, T = ${typeof t}`
<throw_type> ::= throw <string_literal>
```
## Evaluate:
Any throw expression in type context evaluates to `never`.
## Additional information to language service
- `throw 'string'` evaluates to 'string'
- throw \`Before ${Type} After\` evaluates to 'Before ' + Type + ' After'

## Hacks
1. A named interface
```ts
interface CannotInvokeEachParentElementForTWhereTIsNotSubTypeOfHTMLElement {}
class ElementOrTextArray<T> {
    map<NextType>(fn: (current: T) => NextType): ElementOrTextArray<NextType> { return {} as any }
    eachParentElement: T extends HTMLElement ? (() => ElementOrTextArray<HTMLElement>) : CannotInvokeEachParentElementForTWhereTIsNotSubTypeOfHTMLElement = (() => {

    }) as any
}

const x = new ElementOrTextArray<string>().eachParentElement()
// Cannot invoke an expression whose type lacks a call signature. Type 'CannotInvokeEachParentElementForTWhereTIsNotSubTypeOfHTMLElement' has no compatible call signatures.
const y = new ElementOrTextArray<HTMLDivElement>().eachParentElement()
// OK
```

## Problem of this way to strict caller's generic
I cannot specify one thing to be `T extends Q ? A : never`, in the same time assign it as A.
```typescript
class A<T> {
    x: T extends Q ? (() => void): never = () => {}
    // NO, I can't do this.
}
```
## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment] 2019-03-09 15:00
Duplicate #23689 ?

**Comment by Jack-Works** [comment] 2019-03-10 10:36
Yes. Does that under considering?

**Comment by jack-williams** [comment] 2019-03-10 13:31
I don't think this is a duplicate of #23689. That proposal is for a new type that represents an exception during type-checking and should not be related to any other type: the dual of `any`.

I believe this proposal is for something that is essentially a labelled `never` that has no distinct type checking behaviour, but gives better error messages.

One potential issue with this proposal is that if the `throws` type evaluates to `never` it will get swallowed by subtype reduction. Basically, the same problem where people want
```ts
type Colour = "blue" | "green" | string
```
to give autocompletion suggestions, but TypeScript removes the literals because they are semantically meaningless.

**Comment by RyanCavanaugh** [comment] 2019-03-18 23:26
I think the broad use case of "Use the type system to indicate error states" is what's being discussed in both issues, with the particulars of topness/bottomness of those flagging types being an design detail to hammer out later - certainly we wouldn't do *both*, so figuring which is preferable is something we can track at #23689

**Closed by RyanCavanaugh** 2019-03-18 23:26 UTC
Labels: Duplicate
