### ISSUE TITLE
JSdoc 'import type' syntax wrongly transformed when generate declaration from js file

### ISSUE THREAD

**Issue by xlfsummer** [microsoft/TypeScript#46575] opened 2021-10-29 09:18 UTC
# Bug Report

### 🔎 Search Terms
Import type syntax error after generate .d.ts from js
Import type error after generate .d.ts using JSdoc

### 💻 Code

```js
// index.js
/** @type {import('./type').Foo} */
export const foo;
```
```ts
// type.ts
export type Foo = string;
```
- [jsdoc syntax: import-types](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#import-types)
- [doc: Creating .d.ts Files from .js files](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html)

[demo repo](https://github.com/xlfsummer/typescript-jsdoc-template-defaults-demo/tree/import-types) (using  'import-types' branch, not 'master')

### 🙁 Actual behavior

output index.d.ts
```ts
/** @type {import('./type').Foo} */
export const foo: import('./type').Foo;
```

`import` is a method for loading async resource in js/ts, not import a type. it should be transformed to `import .. from ..` .

### 🙂 Expected behavior

output index.d.ts
```ts
import {Foo} from './type';
/** @type {import('./type').Foo} */
export const foo: Foo;
```

**Comment by fatcerberus** [comment] 2021-10-30 02:28
> `import` is a method for loading async resource in js/ts, not import a type.

`import("foo")` doesn’t mean that when used in a type position—in that case it means the type of `import * as … from "foo"`, as resolved by TypeScript.

**Comment by xlfsummer** [comment] 2021-10-30 04:02
> > `import` is a method for loading async resource in js/ts, not import a type.
> 
> `import("foo")` doesn’t mean that when used in a type position—in that case it means the type of `import * as … from "foo"`, as resolved by TypeScript.

Yes. In a type position, we use `import(...)` to import all exports in another file. When we generate type declaration files, we should not directly copy that from source to dist. We should replace the `import(...)` by `import ... from ...` and place it to the top of the output file.

**Comment by orta** [comment] 2021-10-30 12:09
JSDoc is used to only give type-hints in TypeScript and JavaScript files, not to direct how the syntax should change. I'm afraid any changes here would be massively breaking to the ecosystem, and break the TypeScript design guides which were mentioned in the issue template.

**Comment by xlfsummer** [comment] 2021-11-01 05:56
But I think it's weird to have each single feature works fine but break when use them both. (because `import()` returns `Promise` value in ts)

I think maybe we could handle this by replace `import()` to `any`? (at least it won't break types)

**Comment by andrewbranch** [comment] 2021-11-01 15:52
Working as intended for now, but there’s an issue tracking an investigation into whether we can do this: https://github.com/microsoft/TypeScript/issues/44044

(As an aside, it feels slightly weird to me that the JSDoc `type` tag gets preserved in declaration emit.)

**Closed** 2021-11-03 20:00 UTC
Labels: Working as Intended
