### ISSUE TITLE
Type inference too narrow in Array.reduce with strictFunctionTypes on

### ISSUE THREAD

**Issue by jakeboone02** [Microsoft/TypeScript#30821] opened 2019-04-08 22:30 UTC
**TypeScript Version:**  3.4.1

**Search terms:** reduce strictFunctionTypes

**Code**

When the type of `passing` is explicitly set to `boolean`, this fails:

```ts
const passing: boolean = [1].reduce(pv => true, true);
```

**Expected behavior:**

Type inferred from `true` as the `initialValue` argument should be `boolean`.

**Actual behavior:**

`Type 'boolean' is not assignable to type 'true'.` <-- error on the return value of the reducer function.  It's as if I wrote this:

```ts
const passing = [1].reduce(pv => true, true as true);
```

The workaround I'm using is this:

```ts
const passing: boolean = [1].reduce(pv => true, !!true);
```

This also works:

```ts
const passing: boolean = [1].reduce(pv => true, true as boolean);
```

**Playground link:**

Turn on **strictFunctionTypes** to see the error:

https://www.typescriptlang.org/play/#src=const%20passing%3A%20boolean%20%3D%20%5B1%5D.reduce(pv%20%3D%3E%20true%2C%20true)%3B

**Related issues:** none found

**Comment by ahejlsberg** [comment] 2019-04-09 03:26
This issue has the same root cause as #30390, so I'm marking it as a duplicate.

**Comment by jakeboone02** [comment] 2019-04-09 04:01
Thanks, @ahejlsberg. Should we just close this ticket, then?

**Comment by ahejlsberg** [comment] 2019-04-09 04:28
Yes, I'll close it.

**Closed by ahejlsberg** 2019-04-09 04:28 UTC
Labels: Duplicate
