### ISSUE TITLE
Unions of types with optional members don't check member types when assigning an object literal

### ISSUE THREAD

**Issue by zakmagnus** [Microsoft/TypeScript#13283] opened 2017-01-04 17:48 UTC
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**
```ts
type unionType = { stringValue: string } | { numberValue: number } | { arrayValue?: string[] };
let unionVariable: unionType;
unionVariable = { stringValue: 0 };
// Why does this compile? stringValue's type is wrong!
```

**Expected behavior:**
The code does not compile. The union may have a ``stringValue`` member, but its type must be ``string``, not ``number``.

**Actual behavior:**
The code compiles. Type safety is lost.

**More code samples for contrast:**
If none of the members of the types being unioned are optional, then it fails to compile, as expected:
```ts
type unionType = { stringValue: string } | { numberValue: number } | { arrayValue: string[] };
let unionVariable: unionType;
unionVariable = { stringValue: 0 };
/* The previous line does not compile. That makes sense! Here's an error message:
Type '{ stringValue: number; }' is not assignable to type 'unionType'.
  Type '{ stringValue: number; }' is not assignable to type '{ arrayValue: string[]; }'.
    Property 'arrayValue' is missing in type '{ stringValue: number; }'.
*/
```

Members which don't exist at all are not allowed, even if the union has optional members:
```ts
type unionType = { stringValue: string } | { numberValue?: number } | { arrayValue: string[] };
let unionVariable: unionType;
unionVariable = { noSuchThing: 0 };
/* The previous line does not compile. That makes sense! Here's an error message:
Type '{ noSuchThing: number; }' is not assignable to type 'unionType'.
  Object literal may only specify known properties, and 'noSuchThing' does not exist in type 'unionType'.
*/
```

**Motivation:**
I did not dig up a weird corner case just to be annoying! I actually need this. I'm trying to use ``keyof`` to add much more precise types to the immutability helper library (current typings: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/immutability-helper/index.d.ts), which naturally involves unioning interfaces which contain optional members. The whole point of what I'm trying to do is to get the compiler to enforce very strict types, but right now the types of members end up completely ignored.

**Comment by mhegazy** [comment] 2017-01-04 22:15
Duplicate of https://github.com/Microsoft/TypeScript/issues/12745

**Comment by zakmagnus** [comment] 2017-01-04 23:40
@mhegazy Is that really a duplicate? In the issue you've linked, there are discriminants, but my issue doesn't have those. Meanwhile, my issue involves optional members (I don't get any bad behavior if I don't have optionals!) whereas the issue you linked doesn't have any optionals.

I don't know how this stuff is implemented, so maybe these two different things are somehow the same on the inside; but it doesn't look very much like a duplicate based on surface-level appearances.

**Comment by mhegazy** [comment] 2017-01-04 23:48
the check is disabled for Union/intersection types. #12745 tracks enabling the check.

**Closed** 2017-04-21 16:56 UTC
Labels: Duplicate
