### ISSUE TITLE
object is possibly undefined even though check is done

### ISSUE THREAD

**Issue by barroudjo** [microsoft/TypeScript#34535] opened 2019-10-17 09:28 UTC
**TypeScript Version:**  3.6.3

**Search Terms:** object is possibly undefined

**Code**

```ts
const foo = (bar: { baz?: { name: string } }) => {
    const isBarBazDefined = !!bar.baz;
    if(isBarBazDefined) console.log(bar.baz.name);
}
```

**Expected behavior:**
Typescript should not give an 'object is possibly undefined' error.

**Actual behavior:**
Typescript does give an 'object is possibly undefined' error.

**Playground Link:** 
http://www.typescriptlang.org/play/?ssl=4&ssc=2&pln=1&pc=1#code/MYewdgzgLgBAZiEMC8MAUAjAhgJwFwwDeM2AXgPwHFhYC2ApgdDgJZgDmMAvtwJQoA+IgCgYYmKEiwWEAEK55pACL04begBMUMAIQ7sOAHRkA3KPEs4aGfJyKVasJv6SIIADb1D7kO0y5jLFJDGgZeMy4gA

**Related Issues:**
Couldn't find any. 

I realise this is very simple case, but I haven't been able to find an existing issue or FAQ entry on the subject...

**Comment by jack-williams** [comment] 2019-10-17 10:10
This is a duplicate of #12184 - narrowing results cannot be assigned to an identifier and reused.

**Comment by barroudjo** [comment] 2019-10-17 14:23
Thanks. Is there any recommended workaround, besides again doing the check ?

**Comment by jack-williams** [comment] 2019-10-17 20:49
@barroudjo The quick and easy way is a `!` assertion:
```ts
const foo = (bar: { baz?: { name: string } }) => {
    const isBarBazDefined = !!bar.baz;
    if(isBarBazDefined) console.log(bar.baz!.name);
}
```

**Closed** 2019-10-20 18:00 UTC
Labels: Duplicate
