### ISSUE TITLE
Inconsistent keyof array behavior

### ISSUE THREAD

**Issue by jackhe16** [microsoft/TypeScript#45330] opened 2021-08-05 03:12 UTC
### Typescript version: 4.3.5

Is this expected behavior ?

Just do paradigm extraction, shouldn't it have the same result ?

### 💻 Code

```ts
type ArrayString = string[];

type Keys1 = {
  [K in keyof ArrayString]: K;
}[keyof ArrayString];

// number |
//   typeof Symbol.iterator |
//   typeof Symbol.unscopables |
//   "length" |
//   "toString" |
//   "toLocaleString" |
//   "pop" |
//   "push" |
//   "concat" |
//   "join" |
//   "reverse" |
//   "shift" |
//   "slice" |
//   "sort" |
//   "splice" |
//   "unshift" |
//   "indexOf" |
//   "lastIndexOf" |
//   "every" |
//   "some" |
//   "forEach" |
//   "map" |
//   "filter" |
//   "reduce" |
//   "reduceRight" |
//   "find" |
//   "findIndex" |
//   "fill" |
//   "copyWithin" |
//   "entries" |
//   "keys" |
//   "values" |
//   "includes";

type ArrayKeys<T> = {
  [K in keyof T]: K;
}[keyof T];

type Keys2 = ArrayKeys<ArrayString>;

// number | (() => IterableIterator<number>) | (() => {
//     copyWithin: boolean;
//     entries: boolean;
//     fill: boolean;
//     find: boolean;
//     findIndex: boolean;
//     keys: boolean;
//     values: boolean;
// }) | (() => string) | (() => string) | (() => number) | ((...items: number[]) => number) | {
//     (...items: ConcatArray<number>[]): number[];
//     (...items: (number | ConcatArray<number>)[]): number[];
// } | ((separator?: string) => string) | (() => number[]) | (() => number) | ((start?: number, end?: number) => number[]) | ((compareFn?: (a: number, b: number) => number) => number[]) | {
//     (start: number, deleteCount?: number): number[];
//     (start: number, deleteCount: number, ...items: number[]): number[];
// } | ((...items: number[]) => number) | ((searchElement: number, fromIndex?: number) => number) | ((searchElement: number, fromIndex?: number) => number) | {
//     <S extends number>(predicate: (value: number, index: number, array: number[]) => value is S, thisArg?: any): this is S[];
//     (predicate: (value: number, index: number, array: number[]) => unknown, thisArg?: any): boolean;
// } | ((predicate: (value: number, index: number, array: number[]) => unknown, thisArg?: any) => boolean) | ((callbackfn: (value: number, index: number, array: number[]) => void, thisArg?: any) => void) | (<U>(callbackfn: (value: number, index: number, array: number[]) => U, thisArg?: any) => U[]) | {
//     <S extends number>(predicate: (value: number, index: number, array: number[]) => value is S, thisArg?: any): S[];
//     (predicate: (value: number, index: number, array: number[]) => unknown, thisArg ...

```

**Comment by jcalz** [comment] 2021-08-05 03:39
This seems to be a duplicate of #35464, and therefore working as intended.  Note: this issue does not follow the [bug report template](https://github.com/microsoft/TypeScript/raw/b9e952be1d1ccae16218a712e6daca9c8f39c415/.github/ISSUE_TEMPLATE/Bug_report.md).

**Closed** 2021-08-07 18:00 UTC
Labels: Duplicate
