### ISSUE TITLE
Spread operator fails for object type generics

### ISSUE THREAD

**Issue by opiation** [microsoft/TypeScript#26412] opened 2018-08-13 15:52 UTC
**TypeScript Version:**  3.0

**Search Terms:**
generic, spread, object types, spread types, spread operator

**Code**

```ts
function shallowCopy<T extends object>(state: T): T {
  return {
    ...state
  }
}
```

**Expected behavior:**
Should compile as only `state`'s properties are being shallow-copied to the returned result and thus meets the `T` type.

**Actual behavior:**
Does not compile with the following error message:
```shell
> Spread types may only be created from object types.
```

If `T extends object`, is it not then an `object type`?  If not, what `type` or `interface` can be defined that **is** an `object type` and is not exactly `{}` or `object`?

**Possible ways forward:**
- If the compiler does not properly recognize `T extends object` as an object type, perhaps this should be implemented to better support spread/rest operators in modern ecmascript syntax.
- If `T extends object` is a recognized object type, the compiler error should be amended to something like _"Spread types may only be created from the `object` type in generics"_
- Silently lock and close this issue adding documentation that states _"The spread operator does not support generics extending `object`"_

**Playground Link:** [Contrived example][playground]

**Related Issues:**
https://github.com/Microsoft/TypeScript/pull/13288 - While this seems like the use case was addressed by @RyanCavanaugh , the resulting workaround suggests far more explicit typing than should be required by the compiler to infer the types in the example provided.  While closing that PR might have been the protocol, it seemed more effectively to silence the community request for spread operator support with generics extending from `object`.

[playground]: https://www.typescriptlang.org/play/#src=const%20state%20%3D%20%7B%0D%0A%20%20answer%3A%2042%0D%0A%7D%0D%0A%0D%0Afunction%20shallowCopy%3CT%20extends%20object%3E(state%3A%20T)%3A%20T%20%7B%0D%0A%20%20return%20%7B%0D%0A%20%20%20%20...state%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20alternateCopy%3CT%20extends%20object%3E(state%3A%20T)%3A%20T%20%7B%0D%0A%20%20return%20Object.assign(%0D%0A%20%20%20%20%7B%7D%2C%0D%0A%20%20%20%20state%2C%0D%0A%20%20%20%20%7B%20answer%3A%20%22123%22%20%7D%0D%0A%20%20)%0D%0A%7D%0D%0A%0D%0Aconst%20copy%20%3D%20shallowCopy(state)%0D%0A%0D%0Aconst%20alt%20%3D%20alternateCopy(state)

**Comment by andy-ms** [comment] 2018-08-13 16:31
Duplicate of #24060, #24630, #22687, #20510, #20013.
I'll mark this as an error message bug since we should be providing a message that this doesn't and likely never will work for a type parameter without a cast.

**Comment by simonbuchan** [comment] 2018-08-16 06:02
Just digging through those links, https://github.com/Microsoft/TypeScript/issues/10727#issuecomment-306562488 suggests that there wasn't a specific reason for this to not work originally, but by https://github.com/Microsoft/TypeScript/issues/20013 it was decided that this was correct to reject this.

On the one hand, the reasoning there, essentially that own/enumerable requirement for spread isn't modeled by TS, is also an issue even without generics so allowing this usage isn't introducing a *new* type-safety problem; on the other, the problem is much larger with generics, as the heuristic TS uses for non-generic spreads (which is just strip methods, right?) doesn't work. Is this why #10727 was recently tagged as Revisit?

**Comment by alamothe** [comment] 2018-08-17 00:50
Came here because of:
```typescript
type A = {
	a: string
	b: number
}

function f<B extends object>(x: A & B) {
	const {a, b, ...other} = x // does not work
}
```

**Comment by RyanCavanaugh** [comment] 2018-10-09 22:28
> Silently lock and close this issue 

:extremely long sigh:

**Comment by Cryrivers** [comment] 2018-10-16 04:34
Reading through previous issue I understand that `...T` is not assignable `T`. But may I know the challenge for getting a correctish inference?

For example:

```ts
type MyObj = {
  a: string,
  b: number,
  c: boolean,
}

function foo<T extends MyObj>(value: T) {
  const { a, ...otherValues } = value;
}
```

is it possible to infer `otherValues` as `Omit<MyObj, 'a'> & AnyObject`, so we can at least make it type-safe if we access properties in `otherValues` that belongs to `MyObj`?

**Comment by xiaodeaux** [comment] 2018-12-07 00:56
This bug is probably related to #8856 somehow.

**Comment by mnpenner** [comment] 2021-03-09 04:28
@JoshuaKGoldberg Isn't that the problem? It *should* give a compile-time error ideally.

`shallowClone(new C())` doesn't have the method `m()`.

**Closed** 2023-10-06 04:08 UTC
Labels: Bug, Help Wanted, Domain: Error Messages
