### ISSUE TITLE
Quick info for property name in a destructuring binding element is wrong

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2405] opened 2015-03-18 01:21 UTC
```ts
var { person: { name, id } } = { person: { name: "hi", id: 100 } };
```
Get quick info on the word `person` on the right side of the assignment. You get the correct type `{ name: string; id: number }`. You also get the kind 'property' and the name 'person'.

However, the `person` on the left just gives you `any`. I would expect it to show exactly the same kind, name and type as the one on the right.

![bindingelementpropertynamequickinfo](https://cloud.githubusercontent.com/assets/8052525/6700901/52798bb4-ccd2-11e4-96c4-371cd8926347.gif)

**Comment by mhegazy** [comment] 2015-03-18 16:41
dupe of #2024

**Closed** 2015-03-18 16:42 UTC
Labels: Bug, Duplicate
