### ISSUE TITLE
Type assertions aren't merge right

### ISSUE THREAD

**Issue by leonovalex** [microsoft/TypeScript#45561] opened 2021-08-24 07:00 UTC
# Bug Report

### 🔎 Search Terms

type assertions order

### 🕗 Version & Regression Information

Started at least from 3.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210823#code/MYewdgzgLgBATgU2AglgNwXGBeGAKADwC4YBvAXwEocA+GAgbgCgnRJYAzHfYmAVzABrMCADuYatjqkmMGCi54oATwAOCEFwIwAhNlwByEACMAVkigGYAH2v0cuMHwA2z6jLlzEUPnDD8wABMEDhQwBEDZGHIo719-RGR0TEJKJhjWcGgYDgBGbkISAWExCVoyKIUeBxgnVxs7FXVNez1DE3NgS3corwQfPwDg0PDIuRi+gYSkVAw4VPSgA)

### 💻 Code

```ts
const receiver = (x: {}) => x;

const f = (x: unknown) => {
  if (typeof x !== 'object' || x == null) {
    return undefined
  }
  return receiver(x)
}

const f1 = (x: unknown) => {
  if (x == null || typeof x !== 'object') {
    return undefined
  }
  return receiver(x)
}
```

### 🙁 Actual behavior

Has error: Argument of type 'object | null' is not assignable to parameter of type '{}'. Type 'null' is not assignable to type '{}'.

### 🙂 Expected behavior

Shouldn't have any error. Checks are equivalent.

**Comment by MartinJohns** [comment] 2021-08-24 07:20
Duplicate of #28131. Used search terms: `null typeof object`

**Closed** 2021-08-24 14:38 UTC
