### ISSUE TITLE
Visual Studio not immediately recognizing d.ts files added via NuGet

### ISSUE THREAD

**Issue by nycdotnet** [Microsoft/TypeScript#1759] opened 2015-01-21 18:07 UTC
Visual Studio does not immediately recognize d.ts files that are added via NuGet.  It seems that the first time a definition is added in this way, the file needs to be manually referenced or the project needs to be unloaded/reloaded.
 
Repro:
  * Brand new Windows 8.1 fully patched with VS 2013 Community Edition (Update 4).
  * Create a new HTML Application with TypeScript.
  * Change the app.ts to show this code:
```typescript
window.onload = () => {
  console.log($('#content').length);
}
```
  * Go to Manage... NuGet Packages...
  * Download the `jquery.TypeScript.DefinitelyTyped` package.
  * The error "could not find symbol $" will remain.  **Expected:** The error should go away.
  * Create a reference manually in `app.ts` : `/// <reference path="scripts/typings/jquery/jquery.d.ts" />`
  * Now the error will go away because Visual Studio includes the definition in the compilation.
  * Remove the reference and save the file, the error will come back.  **Expected:** The error should not come back.
  * Right-click "Unload Project", Right-click "Reload Project".  Now the error will go away and VS will properly include the jquery.d.ts in the compilation.  **Expected:** It should not have been necessary to reload the project.

This is also a problem if you have the new TypeScript 1.4 VS extension installed.  In addition to the project unload/reload, closing and re-opening Visual Studio will also work around the issue.  This happens in VS 2013 Pro also - I just wanted to see if it would repro on a completely clean machine.

**Comment by vladima** [comment] 2015-02-03 01:11
Core reason of the problem is fixed in VS2014. Fixing it in VS 2013 will require significant and potentially risky changes so don't think we can afford it

**Closed by vladima** 2015-02-03 01:11 UTC
Labels: Bug

**Comment by nycdotnet** [comment] 2015-02-03 20:19
Thank you for looking into this, @vladima.  I'm rather disappointed to hear that this won't be fixed in VS 2013.  When you say that the core reason is fixed in VS 2015, does that mean that NuGet d.ts imports should work immediately in that version?

**Comment by vladima** [comment] 2015-02-03 20:59
It is fixed in our internal bits and I believe they are not available to public yet.

**Comment by nycdotnet** [comment] 2015-02-04 01:04
OK thanks.
