### ISSUE TITLE
Incorrect emit order in exporting

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6187] opened 2015-12-21 17:03 UTC
ts:

```ts
let f: any;
(() => f = () => 0)();
export {f} // f is defined
```

emit:

```js
"use strict";
var f;
exports.f = f; // f is undefined
(function () { return f = function () { return 0; }; })();
```

**Comment by vladima** [comment] 2015-12-21 17:29
duplicate of #4101

**Closed by vladima** 2015-12-21 17:29 UTC
Labels: Duplicate

**Comment by falsandtru** [comment] 2015-12-21 17:31
thanks!
