### ISSUE TITLE
Exported variable 'X' has or is using name 'Y' from external module "Z" but cannot be named.

### ISSUE THREAD

**Issue by alan-agius4** [Microsoft/TypeScript#20842] opened 2017-12-21 12:14 UTC
**TypeScript Version:**  2.7.0-dev.20171221

**Code**

```ts
// foo.ts
import { WatchOptions } from "cpx";
export let x: WatchOptions;

// bar.ts
import { x } from "./foo";
export const x2 = x;
```

Just for the sake of the above you can install only `@types/cpx`

**Expected behavior:**
No error and the external module interface is named.

**Actual behavior:**
```
Exported variable 'x2' has or is using name 'WatchOptions' from external module "C:/git/xxxx/node_modules/@types/cpx/index" but cannot be named.
```

Related to https://github.com/Microsoft/TypeScript/issues/20657 but it seems this only solved local non `node_modules` imports

**Comment by ajafff** [comment] 2017-12-21 12:18
Duplicate of #9944

**Closed** 2017-12-21 12:29 UTC
