### ISSUE TITLE
[feat] document on best practice of package.json for dual package (CJS+ESM)

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#53948] opened 2023-04-21 13:00 UTC
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

- dual package CJS + ESM
- package.json best practice

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I fork a typescript CJS repo to add ESM support.

---

https://github.com/sinclairzx81/typebox/pull/400#issuecomment-1517754812

> Do you have any reference links on best practice to support both ESM and CJS? I assume the cjs and esm submodule pathing is a common, but curious on best practice configuration of package.json. I had been meaning to support ESM, however probably as a minor semver, as internal directories have been changed.

---

I use below config, seems working, but not sure if it is best practice.

Therefore, request for a official document.

https://github.com/loynoir/typebox/blob/feat-esm/package.json#L13-L56

```txt
==> cjs/package.json <==
{"type":"commonjs"}

==> esm/package.json <==
{"type":"module"}
```

**Comment by MartinJohns** [comment] 2023-04-21 13:35
Duplicate of #52593. You should mention your use case there, if it wasn't mentioned already (likely was).

**Comment by loynoir** [comment] 2023-04-21 14:31
The issue behind this feat is https://github.com/microsoft/TypeScript/issues/53949

dts resolve to CJS entry dts instead of ESM entry dts

**Closed** 2023-04-23 18:00 UTC
Labels: Duplicate
