### ISSUE TITLE
`Omit` behaves poorly with unions

### ISSUE THREAD

**Issue by bakkot** [microsoft/TypeScript#39556] opened 2020-07-10 19:51 UTC
**TypeScript Version:**  3.9.2 (also v4.0.0-beta)

**Search Terms:** omit, pick, union

**Code**

```ts
type StringTok = { name: 'string', location: number, contents: string }
type NumberTok = { name: 'number', location: number, value: number }

type Tok = StringTok | NumberTok

type UnlocatedTok = Omit<Tok, 'location'>

let a: UnlocatedTok = { name: 'number', value: 1 }

let b: UnlocatedTok = { name: 'number' }
```

**Expected behavior:**
No type error on the `let a`, type error on the `let b`.

**Actual behavior:**

Type error on the `let a`:
> Type '{ name: "number"; value: number; }' is not assignable to type 'Pick<Tok, "name">'.
>  Object literal may only specify known properties, and 'value' does not exist in type 'Pick<Tok, "name">'.(2322)

No type error on the `let b`.

Specifically, it is surprising to me that, [contrary to its description](https://www.typescriptlang.org/docs/handbook/utility-types.html#omittk), the result of `Omit<T, K>` is not the type which contains the members of `T` except without the properties in `K`, but instead some other type.

**Playground Link:** [Link](https://www.typescriptlang.org/play/?ssl=8&ssc=1&pln=11&pc=1#code/C4TwDgpgBAysBOBLAdgcwCoHsDWUC8UA3lMgIYC2EAXFAOQDOCKqtANFADaYDGpwimZDWQBXcgCMI8dt0HAIyYPRqMkaKAF8AUKEhQAcmMnwsuAsTKUatURKltOPPgKEkjU9gDdSHEdTd28JpaOuDQpviwTGgRAD4G7iY4IbrQAKrIXLzyACYRBADy5IjAADym7LRZzoK0AHwhHBDAUKQ0GdW5+UQkFP42iQ7evv4AjMFaTS3i7ZlOXTiRFn3Wtsa0wUA)

**Related Issues:** None that I could find.

**Comment by IllusionMH** [comment] 2020-07-10 22:40
Duplicate of #31501 search terms: `Omit union`

It's working as intended.
`Omit` isn't distributive over unions and if you check implementation its `Pick<T, Exclude<keyof T, K>`
`keyof` for union will return only properties that are available in all union members so it will be `'name' | 'location'` and with `'location'` excluded only one key is left for `Pick`

You need to use conditional types to process each union member separately `type SimpleUnionOmit<T, K extends string | number | symbol> = T extends unknown ? Omit<T, K> : never;` of find more complete constrained approach.

[Example](https://www.typescriptlang.org/play/?ssl=15&ssc=102&pln=15&pc=1#code/C4TwDgpgBAysBOBLAdgcwCoHsDWUC8UA3lMgIYC2EAXFAOQDOCKqtANFADaYDGpwimZDWQBXcgCMI8dt0HAIyYPRqMkaKAF8AUKEhQAcmMnwsuAsTKUatURKltOPPgKEkjU9gDdSHEdTd28JpaOuDQpviwTGgRAD4G7iY4IbrQAKrIXLzyACYRBADy5IjAADym7LRZzoK0AHwhHBDAUKQ0GdW5+UQkFP42iQ7evv4AjMFaTS3i7ZlOXTiRFn3Wtsa0E1oA9FtQALQHh0cHKWGwiORgTRkuRSXl7ADSUBAAHvLIOfRQqsxQ8WspP8fiAJJgOHVIugXu8FF8oCJkNhkJgAO7IKAAfigdzK6CekOEEE8UgA3Kc9B15hA8jgAEyRGAXK4QG6CXHlHCVTouerkybNVp02adGmmBnmXpWOiA+BDHx+GjjbQC6bCqBU7Ji+lLKX9WUbDRAA)

**Comment by bakkot** [comment] 2020-07-10 22:57
Hm, ok. Thanks for the workaround. Is it perhaps worth updating the documentation to explain that `Omit` doesn't do the thing one might expect and to link the workaround which does the thing one would actually want? I would _not_ have been able to come up with that solution on my own.

**Closed** 2020-07-15 20:00 UTC
Labels: Working as Intended

**Comment by everdimension** [comment] 2021-04-30 08:24
Uhm, how is this "working as intended"?

**Comment by HunterKohler** [comment] 2022-04-26 01:42
@everdimension 

The `Omit` type intentionally does not [distribute](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types) unions. When a type parameter is evaluated against an `extends` clause, this changes the evaluation from being an operation on one type, to the union of the operation on each element within the original union. This would be a distinctly different helper.

See the following for example of distribution:

```ts
type ToArrayDistributive<T> = T extends any ? T[] : never;
type ToArrayNonDistributive<T> = T[];

type ExampleDistributive = ToArrayDistributive<string | number>; //  string[] | number[]
type ExampleNonDistributive = ToArrayNonDistributive<string | number>; // (string | number)[]
```

To distribute `Omit`, you could do the following:

```ts
type OmitDistributive<T, K extends keyof any> = T extends any ? Omit<T, K> : never;
```
