### ISSUE TITLE
typescript organize imports conflicts with ts-lint rule ordered-imports

### ISSUE THREAD

**Issue by marcelh-gh** [Microsoft/TypeScript#23888] opened 2018-05-04 10:36 UTC
**TypeScript Version:**  2.9.0-dev.201xxxxx

**Search Terms:** organize imports, code action

The typescript feature alphabetizes imports in a way that all imports starting with a capital letter come first.
The ts-lint rule expects everything to be alphabetized just based on the letter - irrespective of capitalization.

This gets annoying when you use the ts-lint rule and also configure the TS code action to organize imports when the file gets saved.
After you use the quick-fix in VS Code to fix issues, they just get recreated as soon as you save the file.

**Comment by j-oliveras** [comment] 2018-05-04 11:29
You can disable auto organize imports in VS Code: https://code.visualstudio.com/updates/v1_23#_run-code-actions-on-save

**Comment by marcelh-gh** [comment] 2018-05-04 11:33
@j-oliveras you misunderstood my point. I know that and turned it on on purpose. The point is, it would be nice if ts-lint and TS organize imports would use the same method to alphabetize. ;-)

**Comment by mhegazy** [comment] 2018-05-04 19:54
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/23366. we should use case-insensitive comparison when ordering imports..

**Closed** 2018-05-04 19:58 UTC
Labels: Duplicate
