### ISSUE TITLE
Libs are not modules

### ISSUE THREAD

**Issue by DellCliff** [microsoft/TypeScript#53430] opened 2023-03-21 22:48 UTC
# lib Update Request

Make the lib.x.d.ts files into proper modules.

## Missing / Incorrect Definition

Example: `export interface Document ..................`

## Sample Code

Being able to import the lib files:

`import { Document } from "typescript/lib/lib.dom`;

instead of having to use a triple-dash statement.

Once included, types handled through triple-dash statements become available globally. With proper modules you would be able to import types locally into a single file without leaking into the whole code base.

This could help modeling mixed code bases, where parts only run on node, other parts only in the browser, and third parts on either.

**Comment by MartinJohns** [comment] 2023-03-21 23:07
Duplicate of #46754.

**Closed** 2023-03-24 18:00 UTC
Labels: Duplicate
