### ISSUE TITLE
Suggestion: polymorphic object and tuple member type references through literal types

### ISSUE THREAD

**Issue by malibuzios** [Microsoft/TypeScript#7730] opened 2016-03-29 18:34 UTC
_(This seems to have some things in common with #6080 and is strongly related to #1295 as [it can be used to provide an alternative solution to it](https://github.com/Microsoft/TypeScript/issues/1295#issuecomment-202388214) but l opened this separately since I did not feel it was appropriate to continue discussing it there and wanted to approach it in a more generalized way)_

This would provide improved type safety for cases where an interface property is referenced through a string having a value that's known at compile time:

``` ts
type MyType = { "ABC": number };
let x: MyType = { ABC: 42 };

const propName = "ABC"; // 'propName' received the literal type "ABC" (not string)
let y = x[propName]; // 'y' received the type MyType["ABC"] which resolved to 'number'
```

And with support for generic types added, this could work similarly, but resolve to an intermediate type of the form `T[S]` where `T` is an object type and `S` is a string literal type:

``` ts
function func<T extends object>() {
    let x: T;
    const propName = "ABC"; // 'propName' received the literal type "ABC"
    let y = x[propName]; // 'y' would receive the type T["ABC"]
}
```

This could combine with `readonly` function parameters to provide an alternative solution for #1295 (which was actually [where the idea was initially proposed](https://github.com/Microsoft/TypeScript/issues/1295#issuecomment-202388214)):

``` ts
function getProperty<T extends object, S extends string>(obj: T, readonly propName: S): T[S] {
    return obj[propName];
}

// Here T resolves to { ABC: number }, S resolves to the literal type "ABC", 
// and T[S] resolves to number
let x = getProperty({ABC: 42}, "ABC"); // Type of 'x' is number

// Here T resolves to { ABC: number }, S resolves to the literal type "CBA" 
// and T[S] resolves to any
let x = getProperty({ABC: 42}, "CBA"); // Type of 'x' is any

// Here T resolves to { ABC: number }, S resolves to string
// and T[S] resolves to any
let x = getProperty({ABC: 42}, getRandomString()); // Type of 'x' is any
```

This may similarly extend to [numeric literal types](https://github.com/Microsoft/TypeScript/pull/7480), for tuples:

``` ts
type MyTupleType = [number, string, boolean];
let x: MyTupleType;
const index = 1; // 'index' received the literal type 1;

let y = x[index]; // 'y' received the type MyTupleType[1] which resolved to 'string'
```

And work with generic tuples as well:

``` ts
function getTupleElement<T extends Array<any>, N extends number>(tuple: T, readonly index: N): T[N] {
    return tuple[index];
}
```

Same can be done with symbol literal types (haven't thought about that much though):

``` ts
function getSymbolProperty<T extends object, S extends symbol>(obj: T, readonly sym: S): T[S] {
    return obj[sym];
}
```

**Comment by mhegazy** [comment] 2016-03-29 21:55
duplicate of https://github.com/Microsoft/TypeScript/issues/6678

**Comment by malibuzios** [comment] 2016-03-29 22:04
@mhegazy 

#6678 does seem to cover some of the tuple aspect (which is only a small part of this), but this one also covers generic tuples as well:
```ts
function func<T extends Array<any>>(tuple: T) {
  const index = 1;
  return tuple[index]; // return type inferred as the polymorphic reference type T[1]
}

type MyTuple = [number, string, boolean];
let x: MyTuple = [12, "abcd", true];
let result = func(x); // type of 'result' is the type MyTuple[1] which resolves to string
```

**Comment by mhegazy** [comment] 2016-03-29 22:40
this part would be https://github.com/Microsoft/TypeScript/issues/1295.

we have no way today of getting element type of an array.

**Comment by malibuzios** [comment] 2016-03-30 07:50
@mhegazy 

Please read [this comment](https://github.com/Microsoft/TypeScript/issues/1295#issuecomment-202388214) in #1295. This is an alternative solution the one originally proposed there and is different from it. The property specifier here is a **type** rather than a run-time entity.

The idea of a literal type is that it represents a value that is known at compile time. Since
```ts
const x = "ABC"
```
Receives the literal **type** `"ABC", I have reformulated the proposed solution to #1295 to reference a **literal type** instead of a parameter, i.e. instead of 
```ts
function getProperty<T extends object>(obj: T, propName: string): T[propName] {
    return obj[propName];
}
```
I changed `T[propName]` to `T[S]` where `S` is a **type** that extends `string`:
```ts
function getProperty<T extends object, S extends string>(obj: T, readonly propName: S): T[S] {
    return obj[propName];
}
```
I'm using the fact that in case the parameter `propName` would receive a value that is known at compile time. The type `S` would be a literal string type and can be referenced in the expression `T[S]`.

I have also generalized this to any position in the code (not just return types) and for numeric literals as well. Numeric referenced are not covered by #1295.

This issue is not a duplicate. It is about understanding the wider implications of this type of polymorphic references through literal types. I did not feel it was appropriate to continue posting about it there.

**Comment by malibuzios** [comment] 2016-03-30 14:10
Seems like the whole discussion has been diverted to arguing whether this is a duplicate or not, and the actual content ignored. I'm sorry but this seems like a complete waste of time. I'll close it myself.

**Comment by mhegazy** [comment] 2016-03-30 20:53
I did not intend to wast any one's time. sorry if i did. i believe i understand the proposal, and it seems to be there are two parts, 1. using the values of const initializes to get better type information, which seems to be tracked by #6678, and 2. the ability to talk about type of a property of a type. the proposal here seems to be a slight variation from #1295. as mentioned in https://github.com/Microsoft/TypeScript/issues/1295#issuecomment-96852169, we are open to accepting PRs for the general proposal, and we would be open to consider your proposed implementation approach as well.
one thing to note, there are no literal types for numbers, or symbols at the moment. so your proposal only works for string literal types.

**Comment by malibuzios** [comment] 2016-03-30 21:43
@mhegazy 

That's OK, I did not mean you were wasting my time, more like "it turned out it wasn't that much of a great idea to open a new issue and wasn't positively received, never mind". Sometimes in online conversations there could be some misunderstandings, so it could be one.

Anyway, the modification I proposed for #1295 could be seen as "minor" in the sense that it is still the same syntax and the general approach in relation to the problem presented is very similar (though it does require type parameter inference to be truly effective), but is different (perhaps not "fundamentally" different - that was probably an exaggeration) in the sense that the two cannot work together - either run-time entities are used as specifiers (e.g. `T[propName]`) or types (e.g. `T[S]`), having them both would create problems with name collisions etc. and would have somewhat ambiguous semantics.

The features this approach relies on weren't available or even proposed when #1295 was conceived. Things like string literal types and how they are applied to immutable run-time entities and the possibility of read-only function parameters (though I'm not sure if that has been decided on at this point).

There are also some interesting extensions that can be done with this, seemingly without significant effort as it relies on conventional inference mechanisms of the language. For example, as a complement to #6080 (or maybe as an application for #7722) it could support more complex scenarios like:
```ts
function getAnyOneOfTwoStrings() "a" | "b" {
    if (Math.random()) > 0.5
      return "a";
    else
      return "b";
}

function f<T extends object, S extends string>(obj: T, readonly str: S) {
  return obj[str];
}

let MyType = { a: number, b: string, c: boolean }
let x: MyType;

// T resolves to MyType, S resolves to "a" | "b"
// MyType["a" | "b"] resolves to number | string
let result = f(x, getAnyOneOfTwoStrings()); // type of result is number | string
```
This may be very difficult or even impossible to implement with the original proposal, but may come essentially "for free" with this slight modification.

**Comment by malibuzios** [comment] 2016-04-01 16:43
I don't think the examples I gave so far were convincing enough to truly demonstrate the strength of this approach.

The previous example could still somehow (though not very elegantly) _use_ type inference to "pull out" the possible list of literals even with the previous approach: 
```ts
function func<T>(obj: T, propName: string): T[propName] {
	...
}

let x: "a" | "b;

func<T>({a: 123, b: "ABC"}, x);
```
I mean, even if this looks like a real 'stretch' or somewhat semantically inaccurate.

However there are some cases where there is **no possible way** to get any type information, as there isn't even a particular parameter to reference!

```ts
function func<T>(obj: T, getPropName: () => string): T[???]; // What would T reference here?
```
But when using the type as a specifier, this isn't really a problem, the existing machinery of type argument inference would easily infer it:
```ts
// No problem here:
function func<T extends object, S extends string>(obj: T, getPropName: () => S): T[S]

// T resolves to {a: number, b: string}, S resolves to "a" | "b"
// return type is {a: number, b: string}["a" | "b"] which resolves to  number | string
func({a: 123, b: "ABC"}, () => Math.random() > 0.5 ? "a" : "b");
```

This can be extended to arbitrarily complex expressions, as complex as type argument inference could support:
```ts
// No problem here as well:
function func<T extends object, S extends string>(obj: T, complexObject: { num: number, getPropName: () => S}): T[S]

// T resolves to {a: number, b: string}, S resolves to "a" | "b"
// return type is {a: number, b: string}["a" | "b"] which resolves to  number | string
func({a: 123, b: "ABC"}, { num: 123, nameCallback: () => Math.random() > 0.5 ? "a" : "b"});
```

**Comment by DanielRosenwasser** [comment] 2016-04-01 17:01
Is this related to #6080?

**Comment by malibuzios** [comment] 2016-04-01 17:09
@DanielRosenwasser 

Yes, I have mentioned it may provide a solution to it but it goes much further than that. It also includes intermediate polymorphic expressions like `T["a" | "b"]`, or even `T[S]` where both `T` and `S` are generic parameters, and `T` must extend `object`  and `S` must extend `string`. Also it describes similar functionality of for tuples, i.e. `T[N]` where `T` must extend `Array<any>` and `N` must extend `number`.

**Comment by mhegazy** [comment] 2016-11-02 23:37
The request in the OP should be handled by the new `keyof` and `T[K]` operators introduced by https://github.com/Microsoft/TypeScript/pull/11929

**Closed by mhegazy** 2016-11-02 23:37 UTC
Labels: Fixed, Suggestion
