### ISSUE TITLE
generics that extend conditional types that use another generic don't work

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#41743] opened 2020-12-01 03:45 UTC
**TypeScript Version:**  4.2.0-dev.20201201

**Search Terms:**
Conditional types generics
**Code**

```ts
interface Foo<T, U extends T extends number? any: any> {}
function foo<T>(bar: Foo<T, number>) {}
```

**Expected behavior:**
No error, `U` is `any`
**Actual behavior:**
Error 2344: `Type 'number' does not satisfy the constraint 'T extends number? any: any'`
**Playground Link:** 
https://www.typescriptlang.org/play?ts=4.2.0-dev.20201201#code/JYOwLgpgTgZghgYwgAgGIHt0B4AqAaZAVWQgA9IQATAZ2RxPIitpAFcBbAI2gH5k4QATwBc-IQD5kAbwC+AWABQMViARhg6EMhiZc4gBSc4UURmz5kbLtHEBKaTKA
**Related Issues:** 
Maybe #41040 ?

**Comment by RyanCavanaugh** [comment] 2020-12-01 21:41
Looks like a duplicate of #30639

**Closed** 2020-12-01 21:51 UTC
Labels: Duplicate
