### ISSUE TITLE
Regression: intersection of a generic type bound to a discriminated union with one of the union constituencies reduces to never

### ISSUE THREAD

**Issue by Igorbek** [microsoft/TypeScript#38549] opened 2020-05-13 16:32 UTC
**TypeScript Version:**  3.9.2

**Search Terms:** Generic union intersection

**Code**

```ts
interface A {
  kind: "A";
  a: number;
}

interface B {
  kind: "B";
  b: number;
}

declare const shouldBeB: (A | B) & B;
const b: B = shouldBeB; // works

function inGeneric<T extends A | B>(alsoShouldBeB: T & B) {
  const b: B = alsoShouldBeB;
  //    ~ TS2739: Type 'T & B' is missing the following properties from type 'B': kind, b
}
```

**Expected behavior:**

No errors (were no errors on 3.8)

**Actual behavior:**

```
TS2739: Type 'T & B' is missing the following properties from type 'B': kind, b
```

**Playground Link:** [link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=18&pc=1#code/JYOwLgpgTgZghgYwgAgILIN4FgBQzkDWoAJgFzIBEqFA3LvnOSAK4C2ARtHTgL666hIsRCgBCmeoRLkKo2pPZM2nKNz45cxCAgA2cKCgQB7EAGcwyUwAsjzHcVERR5ABToAPslEBKZADIvbmMzC0UvZABeSxs7BycaZAB6ROQAdyMoAlN+HBhmEAQwYBNkUABxCBBoYAQAHgAVZAgAD0gQYlM0ZE9RAD4XOB1TIwBlGPtHZ2RGgJ8JPGRg82Qw8SjB4bHbCfjJZPx8AD9pkYAmAHYAZgBOcnqATwAHFAByGa8X0s7WYFNTUAA5sgwFYUDAjDodEZUoDkI8oEZnlAihBOjAEaxgU9XqIXuQiO0ADQrXDqIA)

**Related Issues:**

It seems to be related to #36696

**Comment by ahejlsberg** [comment] 2020-05-13 23:42
This is basically a duplicate of #38542, but the repro is simpler here.

**Comment by Igorbek** [comment] 2020-05-13 23:58
> This is basically a duplicate of #38542, but the repro is simpler here.

I saw it and couldn't recognize whether it was the same issue or not.

**Closed** 2020-05-14 03:57 UTC
Labels: Bug, Fix Available

**Comment by HitalloExiled** [comment] 2020-05-20 22:34
I had some similar problems at the intersection of properties with different values:

```ts
type T01 = { a: "a" } & { a: "b" }; // never, expects { a: "a"|"b" }
type T02 = { a: "a" } & { a: null }; // never, expects { a: "a"|null }
type T04 = { a: "a" } & { a: undefined }; // never, expects { a: "a"|undefined }
type T03 = { a: string } & { a: null }; // never, expects { a: string|null }
type T05 = { a: string } & { a: undefined }; // never, expects { a: string|undefined }
type T06 = { a?: string } & { a: undefined }; // { a: undefined }, { a?: string|undefined }
```

Does this issue cover that too?
