### ISSUE TITLE
Dart style Mixins

### ISSUE THREAD

**Issue by pdeveltere** [microsoft/TypeScript#56586] opened 2023-11-29 08:36 UTC
### 🔍 Search Terms

dart, mixins

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

I am working with both TypeScript and Dart extensively. And I must say that the Mixin concept Dart has introduced is extremely usefull and well thought out: https://dart.dev/language/mixins.

Since both TypeScript and Dart compile to JavaScript, it thought it must be possible for TypeScript to implement Mixins in a similar way?

### 📃 Motivating Example

```
mixin Wings {
  void fly() {
    console.log('flap')
  }
}

class Bird extends Animal with Wings {
   // ...
}

class Airplane extends Vehicle with Wings {
   // ...
}

const bird = new Bird();
bird.fly();

const  airplane = new Airplane();
airplane.fly();
```

### 💻 Use Cases

1. What do you want to use this for?
easy to add implementations to objects.

2. What shortcomings exist with current approaches?
in my oppinion, the current mixin approach is not very readable.

3. What workarounds are you using in the meantime?
https://www.typescriptlang.org/docs/handbook/mixins.html

**Comment by whzx5byb** [comment] 2023-11-29 08:40
Duplicate of https://github.com/microsoft/TypeScript/issues/54576

**Comment by pdeveltere** [comment] 2023-11-29 08:43
thanks @whzx5byb closing since there already is a proposal https://github.com/justinfagnani/proposal-mixins

**Closed** 2023-11-29 08:46 UTC
