### ISSUE TITLE
latest release version is `3.3.3333`?

### ISSUE THREAD

**Issue by Kosta-Github** [Microsoft/TypeScript#30043] opened 2019-02-22 09:05 UTC
is that intentional? see: https://github.com/Microsoft/TypeScript/releases/tag/v3.3.3333

**Comment by trotyl** [comment] 2019-02-22 09:09
Duplicate of https://github.com/Microsoft/TypeScript/issues/30032

**Closed** 2019-02-22 09:13 UTC
Labels: Question
