### ISSUE TITLE
Omit makes works in an unexpected way for intersection+union type

### ISSUE THREAD

**Issue by semanticist21** [microsoft/TypeScript#60530] opened 2024-11-18 05:03 UTC
### 🔎 Search Terms

I defined my type as below.

```ts
type ErrorPostProcess = {
  status: number;
  code: number;
  desc: string;
  msg: string;
} & (
  | {
      process: 'redirectToast' | 'redirect';
      url: string;
    }
  | {
      process?: 'none' | 'toast' | 'gotoLogin' | 'gotoLoginWithToast' | undefined;
    }
);
```

When I use `Omit` operator on `ErrorPostProcess`, this works in a way not as I expected.

```ts
export const codeApiErrors: Omit<ErrorPostProcess, 'status'>[] = [
// OK
  {
    code: 113,
    desc: 'Not found your social account.',
    msg: 'Not found your social account.',
  },
// Object literal may only specify known properties, and 'url' does not exist in type 'Omit<ErrorPostProcess, "status">'.
  {
    code: 113,
    desc: 'Not found your social account.',
    msg: 'Not found your social account.',
    process: 'redirectToast',
    url: '/login',
  },
...
]
```

### 🕗 Version & Regression Information

I never changed version, just have been using typescript in my proj.

`"typescript": "~5.5.4",`

This is my typescript version.

### 🙁 Actual behavior

```ts
export const codeApiErrors: Omit<ErrorPostProcess, 'status'>[] = [
// OK
  {
    code: 113,
    desc: 'Not found your social account.',
    msg: 'Not found your social account.',
  },
// Object literal may only specify known properties, and 'url' does not exist in type 'Omit<ErrorPostProcess, "status">'.
  {
    code: 113,
    desc: 'Not found your social account.',
    msg: 'Not found your social account.',
    process: 'redirectToast',
    url: '/login',
  },
...
]
```

This is incurring an Error.
In the other hand, without `Omit`, the type works fines.

```ts
// this does not makes type error!
export const test: ErrorPostProcess[] = [
  {
    status: 113,
    code: 113,
    desc: 'Not found your social account.',
    msg: 'Not found your social account.',
    process: 'redirectToast',
    url: 'asdasd',
  },
];
```

### 🙂 Expected behavior

```ts
export const codeApiErrors: Omit<ErrorPostProcess, 'status'>[] = [
// OK
  {
    code: 113,
    desc: 'Not found your social account.',
    msg: 'Not found your social account.',
  },
// It should also pass type check.
  {
    code: 113,
    desc: 'Not found your social account.',
    msg: 'Not found your social account.',
    process: 'redirectToast',
    url: '/login',
  },
...
]
```

### Additional information about the issue

  System:
    OS: macOS 14.4
    CPU: (12) arm64 Apple M3 Pro
    Memory: 85.72 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.8.0 - /opt/homebrew/bin/node
    npm: 10.8.2 - /opt/homebrew/bin/npm
    pnpm: 9.12.3 - /opt/homebrew/bin/pnpm
    bun: 1.1.33 - ~/.bun/bin/bun
  npmPackages:
    @babel/core: ^7.26.0 => 7.26.0 
    @babel/preset-react: ^7.25.9 => 7.25.9 
    @commitlint/config-conventional: ^19.5.0 => 19.5.0 
    @eslint/compat: ^1.2.2 => 1.2.2 
    @eslint/js: ^9.14.0 => 9.14.0 
    @hookform/resolvers: ^3.9.1 => 3.9.1 
    @mdx-js/loader: ^3.1.0 => 3.1.0 
    @mdx-js/react: ^3.1.0 => 3.1.0 
    @next/mdx: ^15.0.3 => 15.0.3 
    @nx/devkit: 20.0.5 => 20.0.5 
    @nx/eslint: 20.0.5 => 20.0.5 
    @nx/eslint-plugin: 20.0.5 => 20.0.5 
    @nx/jest: 20.0.5 => 20.0.5 
    @nx/js: 20.0.5 => 20.0.5 
    @nx/next: 20.0.5 => 20.0.5 
    @nx/playwright: 20.0.5 => 20.0.5 
    @nx/react: 20.0.5 => 20.0.5 
    @nx/rollup: 20.0.5 => 20.0.5 
    @nx/vite: 20.0.5 => 20.0.5 
    @nx/web: 20.0.5 => 20.0.5 
    @nx/workspace: 20.0.5 => 20.0.5 
    @playwright/test: ^1.48.2 => 1.48.2 
    @radix-ui/react-accordion: ^1.2.1 => 1.2.1 
    @radix-ui/react-alert-dialog: ^1.1.2 => 1.1.2 
    @radix-ui/react-aspect-ratio: ^1.1.0 => 1.1.0 
    @radix-ui/react-avatar: ^1.1.1 => 1.1.1 
    @radix-ui/react-checkbox: ^1.1.2 => 1.1.2 
    @radix-ui/react-collapsible: ^1.1.1 => 1.1.1 
    @radix-ui/react-dialog: ^1.1.2 => 1.1.2 
    @radix-ui/react-dropdown-menu: ^2.1.2 => 2.1.2 
    @radix-ui/react-hover-card: ^1.1.2 => 1.1.2 
    @radix-ui/react-label: ^2.1.0 => 2.1.0 
    @radix-ui/react-menubar: ^1.1.2 => 1.1.2 
    @radix-ui/react-navigation-menu: ^1.2.1 => 1.2.1 
    @radix-ui/react-popover: ^1.1.2 => 1.1.2 
    @radix-ui/react-progress: ^1.1.0 => 1.1.0 
    @radix-ui/react-radio-group: ^1.2.1 => 1.2.1 
    @radix-ui/react-scroll-area: ^1.2.0 => 1.2.0 
    @radix-ui/react-select: ^2.1.2 => 2.1.2 
    @radix-ui/react-separator: ^1.1.0 => 1.1.0 
    @radix-ui/react-slider: ^1.2.1 => 1.2.1 
    @radix-ui/react-slot: ^1.1.0 => 1.1.0 
    @radix-ui/react-switch: ^1.1.1 => 1.1.1 
    @radix-ui/react-tabs: ^1.1.1 => 1.1.1 
    @radix-ui/react-toast: ^1.2.2 => 1.2.2 
    @radix-ui/react-toggle: ^1.1.0 => 1.1.0 
    @radix-ui/react-toggle-group: ^1.1.0 => 1.1.0 
    @radix-ui/react-tooltip: ^1.1.3 => 1.1.3 
    @rollup/plugin-url: ^8.0.2 => 8.0.2 
    @svgr/rollup: ^8.1.0 => 8.1.0 
    @swc-node/register: ~1.9.2 => 1.9.2 
    @swc/cli: ~0.3.14 => 0.3.14 
    @swc/core: ~1.5.29 => 1.5.29 
    @swc/helpers: ~0.5.13 => 0.5.13 
    @tanstack/react-query: ^5.59.19 => 5.59.19 
    @tanstack/react-query-devtools: ^5.59.19 => 5.59.19 
    @testing-library/react: 15.0.6 => 15.0.6 
    @trivago/prettier-plugin-sort-imports: ^4.3.0 => 4.3.0 
    @types/jest: ^29.5.14 => 29.5.14 
    @types/mdx: ^2.0.13 => 2.0.13 
    @types/node: 18.16.9 => 18.16.9 
    @types/react: 18.3.1 => 18.3.1 
    @types/react-dom: 18.3.0 => 18.3.0 
    @vitejs/plugin-react: ^4.3.3 => 4.3.3 
    @vitejs/plugin-react-swc: ^3.7.1 => 3.7.1 
    @vitest/coverage-v8: ^1.6.0 => 1.6.0 
    @vitest/ui: ^1.6.0 => 1.6.0 
    autoprefixer: 10.4.13 => 10.4.13 
    axios: ^1.7.7 => 1.7.7 
    babel-jest: ^29.7.0 => 29.7.0 
    class-variance-authority: ^0.7.0 => 0.7.0 
    clsx: ^2.1.1 => 2.1.1 
    cmdk: ^1.0.4 => 1.0.4 
    contentlayer: ^0.3.4 => 0.3.4 
    core-js: ^3.36.1 => 3.39.0 
    date-fns: ^4.1.0 => 4.1.0 
    dotenv-cli: ^7.4.2 => 7.4.2 
    embla-carousel-react: ^8.3.1 => 8.3.1 
    env-cmd: ^10.1.0 => 10.1.0 
    eslint: ^9.14.0 => 9.14.0 
    eslint-config-next: 14.2.3 => 14.2.3 
    eslint-config-prettier: ^9.1.0 => 9.1.0 
    eslint-plugin-import: 2.31.0 => 2.31.0 
    eslint-plugin-jsx-a11y: 6.7.1 => 6.7.1 
    eslint-plugin-playwright: ^1.8.3 => 1.8.3 
    eslint-plugin-react: 7.35.0 => 7.35.0 
    eslint-plugin-react-hooks: 4.6.0 => 4.6.0 
    husky: ^9.1.6 => 9.1.6 
    input-otp: ^1.4.1 => 1.4.1 
    jest: ^29.7.0 => 29.7.0 
    jest-environment-jsdom: ^29.7.0 => 29.7.0 
    jotai: ^2.10.2 => 2.10.2 
    jsdom: ~22.1.0 => 22.1.0 
    ky: ^1.7.2 => 1.7.2 
    lint-staged: ^15.2.10 => 15.2.10 
    lucide-react: ^0.454.0 => 0.454.0 
    next: 14.2.17 => 14.2.17 
    next-contentlayer: ^0.3.4 => 0.3.4 
    next-themes: ^0.4.3 => 0.4.3 
    nx: 20.0.5 => 20.0.5 
    postcss: 8.4.38 => 8.4.38 
    pretendard: ^1.3.9 => 1.3.9 
    prettier: ^3.3.3 => 3.3.3 
    prettier-plugin-tailwindcss: ^0.6.8 => 0.6.8 
    query-string: ^9.1.1 => 9.1.1 
    react: 18.3.1 => 18.3.1 
    react-day-picker: 9.2.1 => 9.2.1 
    react-dom: 18.3.1 => 18.3.1 
    react-error-boundary: ^4.1.2 => 4.1.2 
    react-hook-form: ^7.53.1 => 7.53.1 
    react-hot-toast: ^2.4.1 => 2.4.1 
    react-resizable-panels: ^2.1.6 => 2.1.6 
    react-use: ^17.5.1 => 17.5.1 
    recharts: ^2.13.3 => 2.13.3 
    rehype-pretty-code: ^0.14.0 => 0.14.0 
    rehype-stringify: ^10.0.1 => 10.0.1 
    remark-parse: ^11.0.0 => 11.0.0 
    remark-rehype: ^11.1.1 => 11.1.1 
    rollup: ^4.14.0 => 4.24.4 
    sass: ^1.55.0 => 1.80.6 
    shiki: ^1.22.2 => 1.22.2 
    sonner: ^1.7.0 => 1.7.0 
    tailwind-merge: ^2.5.4 => 2.5.4 
    tailwindcss: 3.4.3 => 3.4.3 
    tailwindcss-animate: ^1.0.7 => 1.0.7 
    ts-jest: ^29.2.5 => 29.2.5 
    ts-node: 10.9.1 => 10.9.1 
    tslib: ^2.8.1 => 2.8.1 
    typescript: ~5.5.4 => 5.5.4 
    typescript-eslint: ^8.13.0 => 8.13.0 
    unified: ^11.0.5 => 11.0.5 
    vaul: ^1.1.1 => 1.1.1 
    vite: ^5.4.10 => 5.4.10 
    vite-plugin-dts: ~3.8.3 => 3.8.3 
    vitest: ^1.6.0 => 1.6.0 
    zod: ^3.23.8 => 3.23.8 
    zod-validation-error: ^3.4.0 => 3.4.0 
    zustand: ^5.0.1 => 5.0.1 
  npmGlobalPackages:
    @changesets/cli: 2.27.9
    @playwright/test: 1.48.2
    envinfo: 7.14.0
    npm: 10.8.2
    prettier: 3.3.3
    shadcn-ui: 0.9.2
    shadcn: 2.1.6

**Comment by semanticist21** [comment] 2024-11-18 05:04
Delete unused section

**Comment by MartinJohns** [comment] 2024-11-18 05:12
Duplicate of #54904.

**Closed** 2024-11-18 05:52 UTC
