### ISSUE TITLE
User-defined type guards cannot narrow discriminated union types

### ISSUE THREAD

**Issue by yenshih** [microsoft/TypeScript#49782] opened 2022-07-05 09:57 UTC
# Bug Report

### 🔎 Search Terms

- user-defined type guards

- narrowing

- discriminated union

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [narrowing](https://www.typescriptlang.org/docs/handbook/2/narrowing.html)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nAQgQwE4B4AqUC8UDkAZgvlAD4EBGa+AfLlNhAB7AQB2AJgM5TfCoAluwDmUAPxQA3lFCQAXIwDcUAG7IANgFcIigMLIwg4JsEAvCFnoBfKIvYRVEVEoBQrzhADGGtNC9w7PxQxEhoivBhLu4BQcBQgtyRDAAUcroEoaQU+NSo+ACUiukJvEQkuPQlODWZJG6ugoRQKaEoqAB01bXlcIXSrlBDUAD0IwSR+IPDbWgd6toQrtbuTS2Jka0I7V3gEAUFA8Oj4-iT5ATtpOI300OznQs6y65AA)

### 💻 Code

```ts
type FooBar<T = 'foo' | 'bar'> = T extends string ? { type: T; value: Capitalize<T> } : never;

declare const fooBar: FooBar;

const isFoo = (type: 'foo' | 'bar'): type is 'foo' => type === 'foo';

if (fooBar.type === 'foo') {
    // 'Foo'
    fooBar.value
}

if (isFoo(fooBar.type)) {
    // 'Foo' | 'Bar' ???
    fooBar.value
}
```

### 🙁 Actual behavior

typeof `fooBar.value` in the second `if` block is `'Foo' | 'Bar'`

### 🙂 Expected behavior

typeof `fooBar.value` in the second `if` block should be `'Foo'` instead of `'Foo' | 'Bar'`

**Comment by MartinJohns** [comment] 2022-07-05 10:58
Duplicate of #42384.

**Closed** 2022-07-08 18:00 UTC
Labels: Duplicate
