### ISSUE TITLE
@ char mishandled inside jsdoc code

### ISSUE THREAD

**Issue by Tyriar** [microsoft/TypeScript#55463] opened 2023-08-22 12:31 UTC
I couldn't figure out how to use `@` inside a jsdoc codeblock. If it's inside inline code or a code block I would think it would not need escaping at all.

```ts
/**
 * `before @param after`
 */
```

![Image](https://github.com/microsoft/vscode/assets/2193314/bc634a6f-3439-4795-8d3f-9bdb21f92de0)

```ts
/**
 * `before &#xFF20;param after`
 */
```

![Image](https://github.com/microsoft/vscode/assets/2193314/620f2b87-aa44-4430-b875-08397032108f)

```ts
/**
 * ```
 * before @param after
 * ```
 */
```

![Image](https://github.com/microsoft/vscode/assets/2193314/fbaf3f5b-b665-45ef-ad0d-aa5d0aacf819)

```ts
/**
 * ```
 * before &#xFF20;param after
 * ```
 */
```

![Image](https://github.com/microsoft/vscode/assets/2193314/794b7ed1-3d68-46d0-a64b-59d530362c68)

**Comment by MartinJohns** [comment] 2023-08-22 15:06
IMO a duplicate of #49273.

**Closed** 2023-08-22 15:23 UTC
