### ISSUE TITLE
Type guards don't work with interface members

### ISSUE THREAD

**Issue by notenoughneon** [Microsoft/TypeScript#7593] opened 2016-03-19 19:04 UTC
**TypeScript Version:** 

1.8.9

**Code**

```ts
interface I {
    m: string | {a: string};
}
var x: I;
var y: string;
if (typeof x.m === 'string') {
    y = x.m;
} else {
    y = x.m.a;
}

```

**Expected behavior:**
no compile errors

**Actual behavior:** 
test.ts(7,5): error TS2322: Type 'string | { a: string; }' is not assignable to type 'string'.
Type '{ a: string; }' is not assignable to type 'string'.
test.ts(9,13): error TS2339: Property 'a' does not exist on type 'string | { a: string; }'.

Pulling x.m out into a separate variable causes the type guard to work as expected.

**Comment by yortus** [comment] 2016-03-19 23:59
Duplicate of #3812?

**Comment by notenoughneon** [comment] 2016-03-20 07:35
Yes, I think it may be a duplicate. Sorry!

**Comment by RyanCavanaugh** [comment] 2016-03-21 03:34
Yep, this should work once #3812 is fixed

**Closed by RyanCavanaugh** 2016-03-21 03:34 UTC
Labels: Duplicate
