### ISSUE TITLE
After installing typescript for visual studio 2015 the paths to typescript still point at older versions from visual studio 2015 dev prompt.

### ISSUE THREAD

**Issue by MikeCheel** [Microsoft/TypeScript#8386] opened 2016-04-29 20:19 UTC
**TypeScript Version:** 

1.8 (From the site)

**Code**

```ts
// A self-contained demonstration of the problem follows...

```

**Expected behavior:**
when I open a vs 2015 command prompt and type tsc.exe -v it should say the latest version. 
**Actual behavior:** 
It shows an older version.

**Comment by mhegazy** [comment] 2016-05-02 23:52
duplicate of https://github.com/Microsoft/TypeScript/issues/4971

Please see the comment in https://github.com/Microsoft/TypeScript/issues/4971#issuecomment-144184935 for workarounds.

**Closed by mhegazy** 2016-05-02 23:52 UTC
