### ISSUE TITLE
Request: mixing private and public constructors

### ISSUE THREAD

**Issue by 00ff0000red** [microsoft/TypeScript#42183] opened 2021-01-03 01:54 UTC
# Suggestion

## 🔍 Search Terms

private constructor, public constructor, overloaded class signatures

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I suggest that private and public constructor annotations are both allowed to be used at once for a class, the public constructor's signature should only be available for use outside of the class, and the private constructor's signature should only be usable from within the class, whether it's a static method, instance method, nested classes, etc.

## 📃 Motivating Example

This would allow greater encapsulation and leak less information about a class's implementation.

## 💻 Use Cases

A core part of an API that I was making was a class, as classes can only have one constructor, I had just made a signature overload for the constructor, one that I had only called from within the class, whereas the other was intended to be called by the consumer of the API. Yet, it made no sense that both were public, as this did not semantically reflect how the code was intended to be used, and the code could only throw errors if the consumer were to use the other overload, so it would only make sense to have made one private, but TS doesn't allow mixing public/private constructor signatures.

The only potential workarounds are using casting from within the class to "wide" types like `any`, or "casting off" the overload before exporting the type of the code.

[Example playground link](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210102#code/MYGwhgzhAEAq0G8C+AoFpIwBLQKYA8AXXAOwBMZ4EUBIABwCcBLANzGOmAHsSJCGArsEJcGACnwAuaBACeAWwBGXEAEoA3LW69+QkeKkz+TEgHMNaGtr6DhoiasQpoL1y6YAzaGMKy6uLi98aABeMOgAIhsTUwjHajdE1wB6ZOg6AUUQJmBOHhs9UWck6CQ8EAhcaE9vX39A6GCwkMi5JRU4pxLE1PTmNg5rXTsGYqTUMcSIAX9xCxpUJE0gA).

**Comment by MartinJohns** [comment] 2021-01-03 07:30
Duplicate of #9592.

**Closed** 2021-01-03 15:28 UTC
