### ISSUE TITLE
Unexpected behavior of conditional types on generics

### ISSUE THREAD

**Issue by nscarcella** [microsoft/TypeScript#33296] opened 2019-09-07 03:03 UTC
I stumbled upon a rather odd behavior while trying to combine conditional types with generics. It looks like, even when the produced types are structurally different, it's still possible to assign a values between them.

```ts
class T1 { t1_tag = 't1' }
class T2 extends T1 { t2_tag = 't2' }

type X<T> = {
  x: T extends T2 ? 'yes' : 'no'
}

let a1: X<T1> = { x: 'no' } // {x: 'yes'} is not valid
let a2: X<T2> = { x: 'yes' } // {x: 'no'} is not valid

// These assignations should not type, but they do
a1 = a2
a2 = a1
```

At first I thought this might be caused by generics being intentionally ignored but that seemed weird, since the types end up being structurally different and checks seem to work for literals, so I though I would report it, just in case.

**TypeScript Version:**  3.6.2

**Search Terms:** generics, conditional type, type inheritance

**Expected behavior:** exclusive structural conditional types derived from generic should not be assignable to each other.

**Actual behavior:** assignation seems to pass type check even when types are structurally incompatible.

**Playground Link:** [here](https://www.typescriptlang.org/play/index.html#code/MYGwhgzhAEAqCM0De0Au8D6qwHNoF5oBydI6AXwChRIZYAmaAUwA9UmA7AEzsRVXpZcBYgLJVKqAJ4AHJtAAaAHlgA+EUkrRoLAFxxmbTjziMA-MSlMIZfUQ4B7IpQkgmqaGHj7lCdYRQ9YkdxaAB6MOQgoisbcmgASxhHDwA3MBAErko3DzB6HxV6f2QdO1jQiKi7EPik6BTodMzsyirYAAtreVoEnA4wVASHDhgIDocAVxAuBocPaTkAGmgAI0mFrqloLgdKLxF8-cZCLyA)

**Comment by AnyhowStep** [comment] 2019-09-07 03:50
https://www.typescriptlang.org/play/index.html#code/MYGwhgzhAEAqCM0De0Au8D6qwHNoF5oBydI6AXwChRIZYAmaAUwA9UmA7AEzsRVXpZcBYgLJVKqAJ4AHJtAAaAHlgA+EQG0klaNBYAuOMzacecRgH5iUphDKGiHAPZFK5ALoaADO8qUuTDQATvIgTKjQYPCGygjqAPTxhCgGxM7iukipRDZ25NAAljDOEQBuYCAFXP6B4CHQYRFg9DEq9AlJyHoOuWTQ8cjZ6flF0CXQ5ZXVlIlwABa28rQFOBxgqAVOHDAQc04AriBcY04R0nIANNAARvtnC1LQXE6UUSLNr4yEUUA

**Comment by jack-williams** [comment] 2019-09-07 09:05
Duplicate of #31295

**Comment by fatcerberus** [comment] 2019-09-07 16:04
> Duplicate of #31295

But... there's no `any` involved here... I don't think...

**Comment by jack-williams** [comment] 2019-09-07 20:38
The `any` is independent of the root issue. Check types in conditionals cause type parameters to be incorrectly measured as bivariant.

**Closed** 2019-09-15 18:00 UTC
Labels: Duplicate
