### ISSUE TITLE
python like imports for better suggestions for better auto complete

### ISSUE THREAD

**Issue by aaayushsingh** [Microsoft/TypeScript#27390] opened 2018-09-27 14:19 UTC
## Search Terms

1. import
2. python import
3. import python

## Suggestion

python like imports so that we have better suggestions for autocomplete in editors
eg: `from lib import module`

#### current implementation
`import { OnInit } from "@angular/core";`

this way has poor autocomplete support in editors. Editors can only show suggestions after it knows that I'm importing from `"@angular/code"`

#### suggested implementation

`from "@angular/core" import { OnInit }`

when this compiles to js, it stays the same

## Use Cases

better autocomplete suggestions in most editors. Currently to use better autocomplete, I have to first write the name of the library and then come back to the name of the module I want to import to get autocomplete suggestions which I can select by pressing just `tab`

## Examples
`from "@angular/core" import { OnInit }`
`from "../myCustomLib" import { SomeItem}`

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

Also, if you guys decide to implement this, can I get to work on this?

**Comment by andy-ms** [comment] 2018-09-27 16:09
This is out of scope of the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) since it would add new expression-level syntax.

**Comment by AlCalzone** [comment] 2018-09-27 16:45
If you use the VSCode snippet for import, the module is filled out first and then the imports so you get autocomplete.

**Comment by DanielRosenwasser** [comment] 2018-09-28 04:50
Duplicate of

- https://github.com/Microsoft/TypeScript/issues/7793
- https://github.com/Microsoft/TypeScript/issues/5821
- https://github.com/Microsoft/TypeScript/issues/5029
- https://github.com/Microsoft/TypeScript/issues/2371
- https://github.com/Microsoft/TypeScript/issues/4880

**Closed** 2018-12-14 18:00 UTC
Labels: Duplicate

**Comment by Alireza-Ghavabesh** [comment] 2023-11-08 09:09
please add python like import for better suggestion
