### ISSUE TITLE
Remaining properties of a generic type can't be accessed after using spread on it

### ISSUE THREAD

**Issue by que-etc** [Microsoft/TypeScript#28821] opened 2018-12-03 17:48 UTC
**TypeScript Version:** 3.3.0-dev.20181201

**Search Terms:**
- generic
- pick
- exclude
- spread

**Code**

```ts
type TargetProps = {
    foo: string,
    bar: string
};

const modifier = <T extends TargetProps>(targetProps: T) => {
    let {bar, ...rest} = targetProps;

    let result: typeof rest & {bar: string}

    // 'foo' doesn't exist 
    rest.foo;

    // Type 'Pick<T, Exclude<keyof T, "bar">> & { bar: string; }' is not assignable to type 'T'.
    let combined: T = result;
};
```

**Expected behavior:**
Rest properties of an object, which has a generic type, should be accessible after the spread operator was applied.

**Actual behavior:**
None of the properties described in the base `TargetProps` type can be accessed.

**Playground Link:** [link](https://www.typescriptlang.org/play/index.html#src=type%20TargetProps%20%3D%20%7B%0D%0A%20%20%20%20foo%3A%20string%2C%0D%0A%20%20%20%20bar%3A%20string%0D%0A%7D%3B%0D%0A%0D%0Aconst%20modifier%20%3D%20%3CT%20extends%20TargetProps%3E(targetProps%3A%20T)%20%3D%3E%20%7B%0D%0A%20%20%20%20let%20%7Bbar%2C%20...rest%7D%20%3D%20targetProps%3B%0D%0A%0D%0A%20%20%20%20let%20result%3A%20typeof%20rest%20%26%20%7Bbar%3A%20string%7D%0D%0A%0D%0A%20%20%20%20%2F%2F%20'foo'%20doesn't%20exist%20%0D%0A%20%20%20%20rest.foo%3B%0D%0A%0D%0A%20%20%20%20%2F%2F%20'foo'%20doesn't%20exist.%0D%0A%20%20%20%20result.foo%3B%0D%0A%0D%0A%20%20%20%20%2F%2F%20Type%20'Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20%22bar%22%3E%3E%20%26%20%7B%20bar%3A%20string%3B%20%7D'%20is%20not%20assignable%20to%20type%20'T'.%0D%0A%20%20%20%20let%20combined%3A%20T%20%3D%20result%3B%0D%0A%7D%3B)

**Related Issues:**
- https://github.com/Microsoft/TypeScript/issues/28720
- https://github.com/Microsoft/TypeScript/issues/28748
- https://github.com/Microsoft/TypeScript/issues/28791#issuecomment-443757708

**Comment by weswigham** [comment] 2018-12-04 19:30
The core of this is that a generic exclude disallows property access, even if said access is known to be "safe".

**Comment by que-etc** [comment] 2018-12-04 20:02
@weswigham I'm just curious, why the `Pick/Exclude` combination, when used in a conditional type, yields different result?

```typescript
type TargetProps = {
    foo: string,
    bar: string
};

type Omit<T, K extends keyof T> = T extends T ? Pick<T, Exclude<keyof T, K>> : never;

const fn = <T extends TargetProps>(obj: T): void=> {
    let rest: Omit<T, 'bar'>;

    // 'foo' exists.
    rest.foo;
};
```

**Comment by DanielRosenwasser** [comment] 2018-12-08 01:12
The second error is reasonable; you don't know if `T` is instantiated with a `bar` that's more derived than `string` (e.g. a literal type).

The first error feels more questionable.

**Comment by que-etc** [comment] 2018-12-11 23:35
@DanielRosenwasser I just realized, that if some properties of the instantiated value may have a literal type, then we shouldn't be able reassign any of them. 

That is, following example should probably raise an error: https://github.com/Microsoft/TypeScript/issues/28952#issuecomment-446400763

P.S. sorry for linking to my own comment. Didn't really know where to ask this.

**Comment by ahejlsberg** [comment] 2018-12-21 20:54
I have a fix for the first error in the original example that I will be putting up shortly. The second error in the original example in a duplicate of #28884.

**Closed** 2018-12-31 03:44 UTC
Labels: Bug, Domain: Conditional Types
