### ISSUE TITLE
TypeScript '@deprecated' warning shown for wrong overload

### ISSUE THREAD

**Issue by rsivan** [microsoft/TypeScript#40007] opened 2020-08-11 18:03 UTC
*TS Template added by @mjbvz*

**TypeScript Version**: 4.1.0-dev.20200811

**Search Terms**
- deprecated 
- jsdoc

**Repo code**
from @IllusionMH

```ts
import { of, SchedulerLike } from 'rxjs';

declare const arr: number[];
declare const scheduler: SchedulerLike;

of(arr); // has @deprecated but only in comment

of(arr, scheduler); // marked as deprecated, has @deprecated in comment
```

---

Issue Type: <b>Bug</b>

In a Typescript source file, import 'of' from 'rxjs';
type a statement that includes 'of(someArray);
Hover near 'of', it shows a deprecation notice, however the actual deprecation is for a different overload of 'of'.
The same happens on any @deprecated annotations with multiple overloads 

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|16, 11, 8|
|Memory (System)|16.00GB (7.20GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

![d ts](https://user-images.githubusercontent.com/5142205/89932186-14f59a80-dbc2-11ea-95e0-01e50e6bd9de.png)
![deprecated](https://user-images.githubusercontent.com/5142205/89932201-1757f480-dbc2-11ea-8cdc-8fc7ea145d68.png)

**Comment by DanielRosenwasser** [comment] 2020-08-11 22:50
I think we have a heuristic where if a signature has no JSDoc comments, we'll pick out the first one. This is often useful to avoid duplication. You can try it out here, where quick info on the call picks up `@badda`:

```ts
/**
 * @badda
 */
declare function foo(): string;
/**
 * @bing
 */
declare function foo(a: string): string;
declare function foo(a: number): number;


foo(123)
```

It's unclear what we should do in some of these situations. 

Maybe the right behavior is that if only the first signature has a comment, then we pick that up; otherwise, if more than one signature has a comment, we only try to pick the comment for the current signature's declaration.

**Comment by DanielRosenwasser** [comment] 2020-08-11 22:51
The feature is working correctly in terms of warnings though - that overload should not be highlighted as a deprecated use, so we don't need a prioritized fix for 4.0.

Marking as `Moderate` because we'll probably have to workshop the implementation or this.

**Comment by IllusionMH** [comment] 2020-08-11 22:54
Maybe make sense not to bring comments that has `@deprecated` JSDoc tag if signature itself isn't deprecated.

**Comment by rsivan** [comment] 2020-08-11 23:30
Agree with @IllusionMH 

> Maybe make sense not to bring comments that has `@deprecated` JSDoc tag if signature itself isn't deprecated.

**Comment by Kingwl** [comment] 2020-08-12 01:28
In my memory, It's caused the quick info, completions, etc who used getNodeModifiers only take the jsdoc by first declaration for the signature
CC: @sandersn

**Comment by sandersn** [comment] 2020-08-12 15:00
This is a complex problem. It is a duplicate of #407, in particular [my last comment](https://github.com/microsoft/TypeScript/issues/407#issuecomment-650266584) on the issue.

**Closed by sandersn** 2020-08-12 15:00 UTC
Labels: Bug, Domain: Quick Info, Needs Proposal, help wanted
