### ISSUE TITLE
Support exact matching array types from JSON files

### ISSUE THREAD

**Issue by PythonCoderAS** [microsoft/TypeScript#49194] opened 2022-05-20 20:42 UTC
# Suggestion

The ability to support using explicit types for exact array lengths with JSON data.

## 🔍 Search Terms

json exact matching array types

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

The ability to treat JSON arrays as exact arrays.

## 📃 Motivating Example

```json
{"example": [1, 2, "three", 4]}
```

```ts
import thing from 'test.json';

interface Test {
    example: [number, number, string, number];
}

export const example: Test = thing;
```

## 💻 Use Cases

This allows making more-specific rather than less-specific types. In the above example, the compiler will flag the declaration because a `(number|string)[]` does not match the specific type I provided.

**Comment by MartinJohns** [comment] 2022-05-20 22:14
Duplicate of #32063.

**Comment by PythonCoderAS** [comment] 2022-05-20 23:33
> Duplicate of #32063.

This is similar but not the exact same thing. The linked issue is talking about taking an array and getting a single compound literal type from the values (like `[1, 2]` -> `1 | 2`). I want something like `[1, 2]` to match `number[]` and `[number, number]`.

**Comment by MartinJohns** [comment] 2022-05-21 05:21
The type can't be `number[]` and `[1, 2]` at the same time. The one is a mutable array with an arbitrary amount of elements, the other is a readonly array with exactly two elements. These types contradict each other.

**Comment by frank-dspeed** [comment] 2022-05-21 06:06
the solution is simple we got casting to const since typescript 4.5 or 4.7 not sure 
typescript
```ts
const literalArray = [1,2] as const
```


js
```js
const literalArray = /** @type {const} */ [1,2] 
```

it got implemented in a way so that you need to indicate that on assignment hope that helps

**Comment by MartinJohns** [comment] 2022-05-21 07:33
> the solution is simple we got casting to const since typescript 4.5 or 4.7 not sure

This feature is called "const context" and was introduced in TypeScript 3.4 (March 2019, #29510), and support for JSDoc was added in TypeScript 4.5 (November 2021, #45464).

But this only works for literals, not for imported values. Having imported values from JSON behave as with `const` is exactly what #32063 is about.

**Comment by frank-dspeed** [comment] 2022-05-21 08:02
@MartinJohns as far as i understood your referencing to a proposal to import json as const i want to drive all values even json as const see my example https://github.com/frank-dspeed/frank-dspeed/issues/10

**Comment by MartinJohns** [comment] 2022-05-21 08:44
That is not supported, and not really feasible. At the point where you want to use `as const` the compiler already lost the information what type it is. It can't deduce `readonly [1, 2]` from a value typed `number[]`. Only the other way is possible and could be achieved using a conditional type.

**Comment by frank-dspeed** [comment] 2022-05-21 13:41
@MartinJohns thats why i wrote it in the proposal the direction does not matter but we need some more scope in future typescript versions to address a lot of small issues.

or maybe we can let it lookup types the ide does that for imports all the time.

**Closed** 2022-06-03 18:00 UTC
Labels: Duplicate
