### ISSUE TITLE
Find all references of constructor

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#9936] opened 2016-07-25 21:02 UTC
When we find all references for `constructor()`, we should get `new X()` and `X.prototype.constructor`.

    class X {
        constructor() {}
    }
    new X();
    X.prototype.constructor;

**Comment by DanielRosenwasser** [comment] 2016-07-25 21:47
Duplicate of #2114.

**Closed by DanielRosenwasser** 2016-07-25 21:47 UTC
