### ISSUE TITLE
Allow setter type to be incompatible with the getter type

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript#43662] opened 2021-04-13 21:47 UTC
# Suggestion

## 🔍 Search Terms

differing accessor types

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

#42425 forces the getter type to be assignable to the setter type. This makes the feature limited on the following DOM typing case, and thus it could be great if the limitation can be lifted.

## 📃 Motivating Example

```webidl
[Exposed=Window]
interface CSSStyleRule : CSSRule {
  attribute CSSOMString selectorText;
  [SameObject, PutForwards=cssText] readonly attribute CSSStyleDeclaration style;
};
```

```ts
interface CSSStyleRule extends CSSRule {
    selectorText: string;
    get style(): CSSStyleDeclaration;
    set style(cssText: string); // currently an error
}
```

```ts
document.body.style = "display: none" // thus still an error while the actual behavior allows it 🤔
```

## 💻 Use Cases

Allows Web IDL readonly attributes to be assignable, and thus the DOM typing better matches the actual behavior.

Transferred from https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/996.

**Comment by andrewbranch** [comment] 2021-04-13 22:57
I don’t know if #2521 was intended to be closed, or if it remains open to track feedback like this. Also related is #43066, but this case is one where you can’t just make the set type `string | CSSStyleDeclaration` because assigning a `CSSStyleDeclaration` back to the accessor _doesn’t work_ 😬

**Comment by thw0rted** [comment] 2021-04-16 08:03
In the "Restrictions" section near the top of #42425, Ryan said that "`obj.x = obj.x;` must be legal assuming obj.x is writable at all" in order to "prevent novel unsoundness from occurring".  Smarter people than I will have to tell you exactly why that's so but it also seems to align with the [Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals):

* Goal: Statically identify constructs that are likely to be errors. -- designing an API that does not allow `x=x` sure seems "likely to be an error"
* Non-goal: Introduce behaviour that is likely to surprise users -- the DOM violated the POLS here, and it should feel bad.

Also, in case it matters, `el.style = el.style` might not do what you want, but it does not cause a runtime error.

**Comment by Pentadome** [comment] 2021-04-16 15:51
Why not just make a Get..() and Set...() function? Getters and setters are supposed to be so simple that they are similar in use as fields.

**Comment by saschanaz** [comment] 2021-04-16 15:54
> Also, in case it matters, `el.style = el.style` might not do what you want, but it does not cause a runtime error.

That should still be an error because it's virtually `el.style = el.style.toString()` where the string becomes `[object CSS2Properties]`.

**Comment by andrewbranch** [comment] 2021-04-16 15:55
> Also, in case it matters, `el.style = el.style` might not do what you want, but it does not cause a runtime error.

I mean, it will literally never do what you want or expect, unless you just want to watch the ~~world~~ DOM burn. Preventing runtime errors is kind of priority one, but preventing blatantly obvious behavioral errors is also a goal.

**Comment by shellscape** [comment] 2021-08-19 14:04
Lending my support to this proposal. Thankfully language ability trumps subjective opinion. If we wanted to write a bunch of `getThing` and `setThing` methods, we'd probably be in Java.

**Comment by valerii15298** [comment] 2022-01-16 20:07
+1 to this proposal. Using apollo + graphql on front end. And such functionality would be really VERY helpful.
Using Apollo type policies I am creating smal library helper to better usability with help of Javascript proxy api. So basically when i need to get value with some parameters it will be a function(when invoked(with arguments or not, will return value) and set to set value.
I am using this Generic: 
```
type RecursiveFunc<T> = {
  [P in keyof T]: T[P] extends (infer U)[]
    ? RecursiveFunc<U>[]
    : T[P] extends object
    ? (() => RecursiveFunc<T[P]>) | T[P]
    : (() => T[P]) | T[P];
};

const conn: RecursiveFunc<Connection> = someval

// get all ports that connected to node 1
conn.ports({args: {node: 1}})

// set ports
conn.ports = [ {node: 1}, {node: 2} ]

// TS2349: This expression is not callable.
// Not all constituents of type 'Ports | (() => RecursiveFunc<Ports>)' are callable.
// Type 'Port' has no call signatures.
```
 Though I am using Javascript Proxy API and it will work in both cases(with get and set) with corresponding types.

**Comment by jlalmes** [comment] 2022-01-20 17:35
+1 for this feature. Flagging this issue that contains lots of great use cases for incompatible getter/setter types: https://github.com/microsoft/TypeScript/issues/2521

**Comment by josh-** [comment] 2022-10-04 01:53
Just wanted to flag another Web API that isn't able to be used without this feature:

The [URL.search](https://url.spec.whatwg.org/#dom-url-search) getter returns `string`, but the `setter` also accepts a `URLSearchParams` object, so the following fails to compile:

```ts
const url = new URL("https://example.com");
url.search = new URLSearchParams({ test: "test" });
```

with `error TS2322: Type 'URLSearchParams' is not assignable to type 'string'.`, despite it being valid.

**Comment by saschanaz** [comment] 2022-10-04 02:54
>Just wanted to flag another Web API that isn't able to be used without this feature

Your code is equivalent to this:

```js
const url = new URL("https://example.com");
url.search = new URLSearchParams({ test: "test" }).toString();
```

... as URLSearchParams has special stringification behavior. So no, it can be used without this feature.

**Comment by nopeless** [comment] 2022-10-07 04:50
I feel like the pot holes generated by having different get/set types can also be overcome by TypeScript. 

I believe most people are going to support same types and over load them to be different as well for example

```ts
get id(): string {}
set id(): string | number {}
```

`string | number` extends `string`, so even JavaScript developers who are expecting `get` and `set` to be the same type shouldn't have any issues

**Comment by mrflip** [comment] 2023-01-17 20:33
What are the blockers for making this happen? The error when this rule is violated seems like a nice-to-have, but when the narrowing is intentional it is paralyzing.

If the feeling is that this loosening deserves some positive indication from the developer, one could have the set declaration take a generic:

```
get id(): string {}
set id<string>(val: string | number) { ... }
```

this works even if you don't want to define a getter: 

```
set id<string>(val: string | number) { Object.defineProperty(this, 'id', String(val), { configurable: false, writable: false, enumerable: true }) }
```

**Comment by MaximSagan** [comment] 2023-01-20 08:38
Just spent an hour debugging an error caused by a junior dev that never would have existed if TypeScript could getters could recognize getter-less properties as such. Would be great if this issue were prioritized.

**Comment by thw0rted** [comment] 2023-01-20 14:39
Maxim, I think you're having a slightly different issue.  You want [this linter rule](https://eslint.org/docs/latest/rules/accessor-pairs) which prevents the creation of setter-only properties.  I think there might actually be an issue on this tracker about it, but under the hood this is basically a problem of bad JS/ES design, and TS is kind of stuck with it.

**Comment by nopeless** [comment] 2023-01-20 19:32
> Just spent an hour debugging an error caused by a junior dev that never would have existed if TypeScript could recognize getter-less properties as such. Would be great if this issue were prioritized.

@MaximSagan 
If there is no getter, then the type would be `never` meaning that it will always extend the setter type. If this issue gets "fixed", then it will actually hide your problem even further. As @thw0rted commented, you want a linter rule. 

Or you can just scream at the junior def for not making it an idiomatic `setProperty()` function

**Comment by thw0rted** [comment] 2023-01-20 20:48
> If there is no getter, then the type would be never meaning that it will always extend the setter type

I think Maxim's point was that if getters and setters were allowed to be incompatible, then the missing getter could be typed, whether explicitly or implicitly, as `void` (instead of `never`), and `f(foo.writeOnlyProperty)` would be an error.  This isn't how ES actually behaves, of course, but it would do a better job of observing the Principle Of Least Surprise.

For now, we have that linter rule.

**Comment by shellscape** [comment] 2023-02-27 16:38
A periodic reminder to the TS staff that the community has been asking for this since 2015 (#2521).

**Comment by andrewbranch** [comment] 2023-02-27 23:08
I actually brought this up a few weeks ago and we agreed it’s worth some experimenting during 5.1. I just forgot to update the issue afterwards; thanks for the reminder.

To be fair though, #2521 is closed because #42425 was thought to address it. This issue was raised afterwards to present use cases that #42425 did not address.

**Comment by travislwatson** [comment] 2023-03-06 23:15
Perhaps a unique use case, but I'll log mine here. I wanted to allow providing an update function to pass to Immer in addition to just setting the new value. This works fine in JS, but I can't get the Type definitions to comply

```ts
console.log(someObj.profile) // { name: 'John Doe' }
someObj.profile = { name: 'This works' }
someObj.profile = (draft) => {
  draft.name = 'This does not'
}
```

**Comment by Morglod** [comment] 2023-03-17 18:15
use case:

getter/setter in mapped type for proxy value with different types for reactive (rxjs like) api

I have Proxy object, that simplifies api for rxjs like values  
When I get value from this Proxy, I just read last memoized value  
When I assign to this value, I should be able to assign both 'updater' or value type

Example code:

```ts
values: MyProxy<{ x: number, y: number }>;

values.x = 10;
values.y = () => values.x + 10;

const finalY = values.y;
```

Type of Proxy here should be:
```ts
{
    get [K in keyof T](): T[K];
    set [K in keyof T](value: T[K] | (() => T[K]));
}
```

**Closed** 2023-03-30 15:51 UTC
Labels: Suggestion, Needs Investigation, Experience Enhancement, Fix Available

**Comment by shellscape** [comment] 2023-03-30 16:27
Thank you!
