### ISSUE TITLE
Implicit member resolution for namespaces through a 'using' keyword

### ISSUE THREAD

**Issue by d180cf** [Microsoft/TypeScript#4816] opened 2015-09-16 02:54 UTC
Are there plans to support the `using` keyword? In large projects there are usually set of modules called "utils" and it's pretty annoying to write `import foo = utils.foo;` for every used entity.

**Comment by DanielRosenwasser** [comment] 2015-09-16 03:36
Related to (but not quite quite a duplicate of) #2819.

**Comment by NoelAbrahams** [comment] 2015-09-16 08:26
Also related to #2956.

**Comment by DanielRosenwasser** [comment] 2015-09-16 17:02
Thanks @NoelAbrahams! Looks like we should be tracking that there.

**Closed by DanielRosenwasser** 2015-09-16 17:02 UTC
