### ISSUE TITLE
strip debugger statements 2.0

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#25442] opened 2018-07-04 20:19 UTC
I opened this ticket a year ago or so:
https://github.com/Microsoft/TypeScript/issues/15093

I was just reading this article:
https://medium.com/the-node-js-collection/get-ready-a-new-v8-is-coming-node-js-performance-is-changing-46a63d6da4de

looks like `debugger;` statements **really** hit performance of node.js processes/servers.

It would be great if `tsc` could do things like strip `debugger;` statements.

We don't need linting tools if we use `tsc`.  tsc *could* serve as a tool that can do amazing things, in transforming code. In being a code transform tool, it could do things beyond transpiling ts to js. 

If this is truly out of scope (which I could understand), is there some plugin system or what not that could plugin to a tsc workflow?

_because this functionality doesn't exist:_

`$ find . | strip-debugger | tsc`

nor does this exist

`$ find . | tsc | strip-debugger`

without such a pipeline, it's difficult to incorporate other tools with tsc. An alternative to a pipeline like that, would be plugins I think.  Babel-style plugins?

If it were incorporate into tsc, you would have the same tsconfig.json, you would just use

```bash
$ tsc --strip-debugger-statements
```

**Comment by kitsonk** [comment] 2018-07-04 20:29
Duplicate of #15093

That issue wasn't locked and the discussion should have continued there.

**Comment by ORESoftware** [comment] 2018-07-04 20:53
The issue is locked for me tho lol, it looked locked, so that's why I filed a new ticket

**Comment by MartinJohns** [comment] 2018-07-05 06:34
@kitsonk "Microsoft locked and limited conversation to collaborators 13 days ago"

@ORESoftware You could do this already using custom transformers using #13764. But beyond that I'd see it as out of scope for the TypeScript compiler.

**Comment by RyanCavanaugh** [comment] 2018-07-05 17:00
Our scope hasn't changed since a year ago 🙃

**Closed by RyanCavanaugh** 2018-07-05 17:00 UTC
Labels: Out of Scope, Suggestion

**Comment by ORESoftware** [comment] 2018-07-05 18:51
"Sometimes scopes change" - DJT
