### ISSUE TITLE
Nested comma triggers signature help

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#12045] opened 2016-11-04 06:43 UTC
**TypeScript Version:**  2.0.3

**Code**

```ts
function foo(x) { }
foo([0 ]) // Type a comma after the 0
```

**Expected behavior:**
In VS code, typing the comma should not trigger signature help
**Actual behavior:** 
Comma triggers signature help

**Comment by RyanCavanaugh** [comment] 2016-11-04 16:11
I don't think it *should* trigger signature help -- it would make it look like you were outside the array. Thoughts?

**Comment by JsonFreeman** [comment] 2016-11-04 17:16
It also happens in object literals and in nested functions.

**Comment by DanielRosenwasser** [comment] 2016-11-04 17:56
Come on Jason, you don't remember this issue from ~2 years ago? #1150.

**Comment by JsonFreeman** [comment] 2016-11-06 17:25
Ah, it's all coming back to me now. I like the TriggerReason idea. Could that be implemented for VSCode too?

**Comment by mhegazy** [comment] 2016-11-07 19:54
indeed a duplicate of #1150.

**Closed by mhegazy** 2016-11-07 19:54 UTC
Labels: Bug, Duplicate
