### ISSUE TITLE
Simplify `[never]` to `never`

### ISSUE THREAD

**Issue by domoritz** [microsoft/TypeScript#44003] opened 2021-05-07 21:18 UTC
# Suggestion

## 🔍 Search Terms

never, simplify, [never]

## ✅ Viability Checklist

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I believe `[never]` means nothing can be assigned so it should be the same as `never`. I think the same could be done for `never[]`. 

## 📃 Motivating Example

https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDaA7CA3CAnAugKCA

## 💻 Use Cases

This would simply make types nice to read.

**Comment by domoritz** [comment] 2021-05-07 21:58
> never[] could represent an empty array.

Right. Then we should leave that alone.

**Comment by jcalz** [comment] 2021-05-08 01:10
Duplicate of or strongly related to #42324

**Closed** 2021-05-08 03:57 UTC
