### ISSUE TITLE
This-function parameter inference fails in object with other typing features

### ISSUE THREAD

**Issue by HerringtonDarkholme** [Microsoft/TypeScript#10461] opened 2016-08-21 08:46 UTC
This may relate to https://github.com/Microsoft/TypeScript/issues/10288

**TypeScript Version:**  2.0.0, installed via typescript@beta

**Code**
All code under `--noImplicitThis` flag.

```ts
function plainThisBound(m: {[k:string]: (this: string) => string}) {}

plainThisBound({
  method() {
    return this.substr(0) // no error
  }
})

function polymorphicThisBound(m: {[k:string]: <V>(this: string) => V}) {}
polymorphicThisBound({
  method() {
    return this.substr(0) // error in noImplicitThis
  }
})

function unionThisBound(m: {[k:string]: (this: string) => string} & {method(): string}) {}
unionThisBound({
  method() {
    return this.substr(0) // error in noImplicitThis
  }
})
```

**Expected behavior:**
All three example should compile, if `this` parameter is inferred on call site
Or no example should compile, if `this` must be explicitly annotated

**Actual behavior:** 
Only the first example compiles.

**Comment by HerringtonDarkholme** [comment] 2016-08-21 08:57
I think some background story will be helpful.
I come up with this when trying to write a more type-safe API for [vue.js](https://rc.vuejs.org)

[Annotating](https://github.com/Microsoft/TypeScript/issues/10427) `this` in vue's API is [difficult](https://github.com/vuejs/vue/issues/478#issuecomment-115278119), so I tried this:

```typescript
declare class VueTyped<T> {
  data<D>(d: D): VueTyped<T & D>;
  method<M>(m: M & { [k:string]: (this: T) => any }): VueTyped<T & typeof m>
  static new(): VueTyped<{}>
  get(): T
}


var b = VueTyped.new()
  .data({msg: '123'})
  .method({
    method() {
      return this.msgs // expected to have an error for typo
    }
  })
  .get()

```
on the line `this.msgs` I expect to have an error. But it does not.

**Comment by DanielRosenwasser** [comment] 2016-08-21 17:30
For your `polymorphicThisBound`, your signature really reads to me as "each of the methods in this object is generic" (see #5737 for something related) whereas I think you really meant to just return `{}` or `any`.

In `unionThisBound`, I believe the issue is that we don't look to the index signature if we have a member of a certain name in the originating type.

Maybe @ahejlsberg has some insights.

**Comment by HerringtonDarkholme** [comment] 2016-08-22 01:33
Thanks for pointing out the spec. 

I understand `polymorphicThisBound` is quite contrived and not inferred according to the spec.

It seems `unionThisBound` should be inferred as it has an[ apparent member of index signature](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3111-apparent-members)?

**Comment by ahejlsberg** [comment] 2016-08-22 14:43
The issue here is fixed by #9746. Your example works in that branch, using either a union type for the `m` parameter or a type constraint for the `M` type parameter.

This is a pretty neat trick. It is kind of magic how the correct type just pops out at the end.

One thing I noticed is that you get errors if you add additional parameters to the methods you define with `method` because they aren't assignable to the indexer type. But you can fix that like so:

```ts
declare class VueTyped<T> {
  data<D>(d: D): VueTyped<T & D>;
  method<M>(m: M & { [k:string]: (this: T, ...args: any[]) => any }): VueTyped<T & M>
  static new(): VueTyped<{}>
  get(): T
}
```

One problem that remains is that when you add explicit parameter type annotations to methods in the `method` argument, the contextual type disappears. We've discussed having contextual types survive in those cases and continue to affect those parameters that don't have type annotations. We should probably look at that again.

Adding @sandersn.

**Comment by sandersn** [comment] 2016-08-23 00:17
Should be fixed now that #9746 is merged.

**Closed by sandersn** 2016-08-23 00:17 UTC

**Comment by DanielRosenwasser** [comment] 2016-09-07 22:32
@HerringtonDarkholme have you ported this into to the Vue declaration file at all?

**Comment by HerringtonDarkholme** [comment] 2016-09-08 01:26
@DanielRosenwasser @kaorun343 has already updated declaration file for Vue 2.0 and that declaration file has used a lot of TS2.0 features to give a description for Vue.

My approach needs many API changes which are unsuitable for official Vue to adopt.
