### ISSUE TITLE
It should infer implemented method parameter type from extends parent class

### ISSUE THREAD

**Issue by zyf0330** [microsoft/TypeScript#44642] opened 2021-06-18 07:03 UTC
# Bug Report

### 🔎 Search Terms

when extends abstract class,
method parameter type cannot be inferred.

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYOwrgtgBAKgngB2FA3gKClAglAvFAIgEYCAaDKAIT0ICYy0BfNNASxABdgAnAMwEMAxsgCSIXgHscKAG5YAXFCLM2nHgOFQxk6rMqLaKjomQARfh34AeGFGAAPLiAAmAZ1gmAfDXSZjSRRhyTHZJQLtHUDcPJAA6LApMAH4tcSlEqHCHJ2j4OMoM5NSdQsyoEGAZHiYAbhZ+ACNXDm4hDihBABt+V3cYCQlOhol7Gwicvq9UCmcLfkVzSxtPOopBCRBm7jBBDgluAApZywW55YBKacw-AAtWV1jj-honuswVTEattqgIYA4bhJnEc5qcljBPOd5DIJKxnHUVF0eu4sP1BsN7OMon0BkMRjYTPFvL5fv9AcCnpcSZgAPQ02ASKCsCAITrAP6cUkAoFQbjAACOYFYfPcAIsUAQ-Fafy43FFJigEl4UAABk8VRk6Uz3K5+H8oD1VWi8fZYjLySrYpr6VgXFB-MgVYtrBCVYrlWq5rFQhI3TceMhXICwJ1nFAGshQjw+WHDc6CXEsJ4rdcoFrKGB2qxlSIoM4JMBXCAAOTtfjOMMOvPAXjsVgcVgbKCSbiq9VQf184LXLVVpVtr0+t2CfggEASdoRpniaPAZwp67rTaDYCxToSADmIMs3rSsRklHOFGYiI2zXtilRuIxNAqAHdsMaMQcUPaTIFCVhSNOwqgoHJFCIKBGGA846g4M0ySBF83wCGJVy-H8JEUV8AKUYDQKAA)

### 🙁 Actual behavior

compile without error

### 🙂 Expected behavior

compile fail caused by line 36
line 30: `data` shoule be inferred as `Data<Type.A>`

**Comment by MartinJohns** [comment] 2021-06-18 09:16
Duplicate of #31470 / #1373. Used search terms: `parameter type override infer`

**Closed** 2021-06-18 09:32 UTC
