### ISSUE TITLE
RE Debug Failure - how do I find the bad code?

### ISSUE THREAD

**Issue by the8thavatar** [Microsoft/TypeScript#17565] opened 2017-08-02 12:45 UTC
I am using Typescript 2.4.1.0. with VS2017 
I have, in Tools\Extensions and updates, the TypeScript for Microsoft Visual Studio installed along with the Typescript HTML Application template which is what I used to set up the project.

When I build the project it reports that tsc failed with code 1.
Enabling detailed build reports I get the following:
1>  Unknown output: Script failed with error: 'JsErrorScriptException (0x30001)'.
1>  Unknown output: Debug Failure. 
1>  Unknown output: Error: Debug Failure. 
1>  Unknown output:    at fail (Unknown script code:2018:13)
1>  Unknown output:    at assert (Unknown script code:2008:17)
1>  Unknown output:    at typeToString (Unknown script code:23526:13)
1>  Unknown output:    at reportRelationError (Unknown script code:28855:17)
1>  Unknown output:    at isRelatedTo (Unknown script code:28972:21)
1>  Unknown output:    at propertiesRelatedTo (Unknown script code:29382:29)
1>  Unknown output:    at structuredTypeRelatedTo (Unknown script code:29275:29)
1>  Unknown output:    at recursiveTypeRelatedTo (Unknown script code:29172:17)
1>  Unknown output:    at isRelatedTo (Unknown script code:28959:25)
1>  Unknown output:    at checkTypeRelatedTo (Unknown script code:28838:13)

Other posts I have seen here have reported a file location reference pointing to a js file. I don't see a working file that the above could be line numbers within.
I also tried the nuget typescript msbuild package and got the same thing with that.

**Comment by the8thavatar** [comment] 2017-08-02 13:31
Found it by excluding files and rebuilding

**Comment by DanielRosenwasser** [comment] 2017-08-02 17:13
Could you share an example file that demonstrates the bug?

**Comment by the8thavatar** [comment] 2017-08-03 08:18
I was trying to be clever and thought I could do the following...
"use strict";

class t {
    public previousPens: { // type..
        keys: [],
        values: [],
    } =
    { // value..
        keys: [],
        values: [],
    };
}

 This block was originally in an object variable declaration so it used to be
var t = {
    previousPens =
    {
        keys: [],
        values: [],
    }
};

**Comment by DanielRosenwasser** [comment] 2017-08-04 07:38
Looks like a duplicate of #17266, problem is you're using empty arrays for types. Should be fixed in 2.5.

**Closed by DanielRosenwasser** 2017-08-04 07:38 UTC
Labels: Needs More Info
