### ISSUE TITLE
TypeScript should respect "instanceof" in logical expressions

### ISSUE THREAD

**Issue by slavafomin** [microsoft/TypeScript#31291] opened 2019-05-07 14:19 UTC
Hello!

Thank you for your hard work.

Please, consider this code:

```typescript
class Foo { 
    foo: string;
}
class Bar {
    bar: string;
}

function foo(value: Foo | Bar) {
    const isFoo = value instanceof Foo;
    const isBar = !isFoo && value.bar; // <-- causes error
}
```

The line above throws an error:
```
Property 'bar' does not exist on type 'Foo | Bar'.
Property 'bar' does not exist on type 'Foo'.
```

However, if I replace the logical variable with the expression directly, it works:

```
const isBar = !(value instanceof Foo) && value.bar;
```

The `isFoo` variable in my example is a boolean constant, it's value can't change, so I believe it should be statically analyzable.

**Comment by JakeTunaley** [comment] 2019-05-08 22:48
Duplicate of https://github.com/microsoft/TypeScript/issues/12184

**Closed** 2019-05-11 18:00 UTC
Labels: Duplicate
