### ISSUE TITLE
Syntax errors caused by JS file

### ISSUE THREAD

**Issue by Aqours** [Microsoft/TypeScript#18306] opened 2017-09-07 10:23 UTC
**TypeScript Version:**  2.5.2

![qq 2](https://user-images.githubusercontent.com/8586286/30158816-04f21f1e-93f9-11e7-9d09-bbcd44be2f6f.png)

** example code **

> Sorry, I cannot provide more code

```js
// a.min.js file
... // compress code
export default n;

// b.js file
import * as N from './a.min';
...
export default {
  // ...
};

// c.ts file
import Re from './b';
...
```

tsconfig.json
```json
{
  "compilerOptions": {
    "allowJs": true,
    "sourceMap": true,
    "declaration": false,
    "skipLibCheck": true,
    "noImplicitAny": false,
    "strictNullChecks": false,
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "dom",
      "es5",
      "scripthost",
      "es2015"
    ]
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

There 34 Syntax errors caused by JS file when compile TS file(use `tsc` command) without module bundler. Actually, those errors should not be hinted by TS.

**Comment by Aqours** [comment] 2017-09-07 10:38
Those errors would be disappeared if I refomat compressed code in a.min.js.

**Comment by mhegazy** [comment] 2017-09-07 18:36
your tsconfig.json has ` "allowJs": true`, and i am guessing you have an import to `a.min`, and does not seem to be `a.min.d.ts` or `a.min.ts` available.

so either 1. do not use `allowJs`,  2. create a new file for `a.min.d.ts`

**Comment by mhegazy** [comment] 2017-09-07 18:37
Also can you share the section of the .js file that is causing the errrors? looks like we have a parser error we need to fix.

**Comment by Aqours** [comment] 2017-09-08 03:56
@mhegazy https://github.com/Aqours/Issues-TypeScript I create a min repo which can reproduce this issue,

**Comment by mhegazy** [comment] 2017-09-08 23:04
@sandersn looks like another lambda/ternary parsing issue.

**Comment by sandersn** [comment] 2017-09-11 16:02
Still repros on master/2.5.3. I'll take a look.

**Comment by sandersn** [comment] 2017-09-11 16:51
#18294 fixes this. Interestingly, this is *not* a dupe of #18158. Bisecting tracked down d796bf1e0a30e899e52d3355b219d22c4875256f as the buggy commit, a couple of weeks after the commits that caused #18158.

@Aqours did you try this code on older versions of Typescript to see if it also fails? I am very suspicious that two people hit 3-year-old bugs within two weeks right after I made parsing changes in the last version.

**Comment by sandersn** [comment] 2017-09-11 17:18
Here's a small repro that I believe still has the essential parse failure:

```ts
{L:function(a){ return true ? (a/8) : true },ka:function(
 ){},
};
```

**Comment by Aqours** [comment] 2017-09-12 02:29
@sandersn 
version tested:
- 2.4.2 failed
- 2.3.4 failed
- 2.1.6 failed
- 1.8.10 failed

**Comment by sandersn** [comment] 2017-09-12 21:51
#18417 is a better fix than this that works by requiring speculatively parsed arrow functions to have an `=` for their parameter's initalisers. Currently `(x y) { }` is parsed as if the user intended to write `(x = y) => { }`. This is true sometimes, but often it is not, especially when we parse `y` incorrectly, as is the case with this bug. (Reminder: here `y = /8) : true },ka:function(`)

**Closed** 2017-09-14 20:01 UTC
Labels: Bug, Fixed
