### ISSUE TITLE
readonly has no effect for string index signiture

### ISSUE THREAD

**Issue by michael8090** [Microsoft/TypeScript#14454] opened 2017-03-04 15:53 UTC
**TypeScript Version:**  2.2

**Code**

```ts
interface ROObject {
    readonly [index: string]: number;
}

const o: ROObject = { x: 1 };

// unexpected: here reasign is allowed
o.x = 2;

interface ROArray {
    readonly [index: number]: number;
}

const a: ROArray = [1];
// it respects the readonly modifier correctly
a[0] = 2;


```

**Expected behavior:**
The `readonly` mdifier should work consistantly for both string indexer and number indexer
**Actual behavior:**
Only the `readonly` for number indexer is respected. The one for string indexer has no effect.

**Comment by andy-ms** [comment] 2017-04-11 22:34
Ping @ahejlsberg @sandersn
Wanted to test for #15036 that the `readonly` would be removed if spreading an object with an index signature, but it's still not added in the first place. Is this a known design limitation?

**Comment by DanielRosenwasser** [comment] 2017-08-04 21:33
Looks like a dupe of #14296.

**Closed by DanielRosenwasser** 2017-08-04 21:33 UTC
Labels: Bug
