### ISSUE TITLE
TS2.3, VS 2017, Preview 2,  CompileOnSave specified in external tsconfig.json seems not to be working

### ISSUE THREAD

**Issue by fis-cz** [Microsoft/TypeScript#15831] opened 2017-05-14 13:57 UTC
**TypeScript Version:**  2.3
**VisualStudio 2017, Preview 2**

**Expected behavior:**

CompileOnSave tsconfig.json option works in the same way as VS2015 Update 3, TS extension 2.2.1

**Actual behavior:**

CompileOnSave specified in external tsconfig.json seems not to be taken into account at all.

Build / rebuild the project / solution works correctly and generates updated output.

**Comment by mhegazy** [comment] 2017-05-15 21:19
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/15083, should be fixed in TS 2.3.3

**Comment by mhegazy** [comment] 2017-05-30 18:59
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-05-30 18:59 UTC
Labels: Duplicate
