### ISSUE TITLE
Typescript experimentalDecorators compiler flag not honored in VSCode

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9178] opened 2016-06-15 06:57 UTC
_From @arciisine on June 14, 2016 11:30_

- VSCode Version: 1.3.0-insiders
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. Configure typescript to use decorators
2. Create a simple decorator usage
3. See VSCode indicate that experimentalDecorators are not enabled

My `tsconfig.json` is as follows:
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators" : true
  },
  "files": [
    "test.ts"
  ]
}
```

And `test.ts` is
```typescript
function Verbose() {
  return (t:any) => t;
}

@Verbose()
export class Test {}
```

Typescript compiles the files fine, without error, but vs code seems to think that the experimentalDecorators flag is not enabled, and marks every usage site as a warning.

![image](https://cloud.githubusercontent.com/assets/1264175/16041112/5b0c2a56-31f9-11e6-8f13-2a8c033b41ec.png)

_Copied from original issue: Microsoft/vscode#7654_

**Comment by dbaeumer** [comment] 2016-06-15 06:57
Moving to TS. TS team please note that the current insider build is still using 1.8.10. So the behavior should be the same with 1.2.x

**Comment by mhegazy** [comment] 2016-06-15 17:16
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/8905..

it does not reproduce with latest tsserver. please try with latest `typescript@next` (see https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code) and reopen if you are still running into the issue.

**Closed by mhegazy** 2016-06-15 17:16 UTC
Labels: typescript
