### ISSUE TITLE
Typing of `Array.every` and `Array.some` is too strict

### ISSUE THREAD

**Issue by MichaelTamm** [Microsoft/TypeScript#30767] opened 2019-04-05 10:27 UTC
**TypeScript Version:**  3.4.1

**Search Terms:**
Array, typing, some, every

**Code**

```ts
const a = [0, 1, 2];
console.log(a.every(x => x));  // ... false
console.log(a.some(x => x));  // ... true
```

**Expected behavior:**
Should compile without an error.

**Actual behavior:**
`tsc` complains with 2 errors TS2322: Type 'number' is not assignable to type 'boolean'.

**Playground Link:**
[A link to a TypeScript Playground "Share" link which demonstrates this behavior](https://www.typescriptlang.org/play/#src=const%20a%20%3D%20%5B0%2C%201%2C%202%5D%3B%0D%0Aconsole.log(a.every(x%20%3D%3E%20x))%3B%20%20%2F%2F%20...%20false%0D%0Aconsole.log(a.some(x%20%3D%3E%20x))%3B%20%20%2F%2F%20...%20true)

**Related Issues:**
none

In the spirit of "any valid JavaScript is also valid TypeScript" the code above should compile without errors.

The errors occur because of the type definitions of the `Array` methods `every` and `some`: The current decalration in `lib.es5.d.ts` states, that the first parameter `callbackfn` must return a `boolean`. This is (in my opinion) too strict, because the [JavaScript spec](https://tc39.github.io/ecma262/#sec-array.prototype.every) says:

> _callbackfn_ should be a function that ... returns a value that is coercible to the Boolean value **true** or **false**.

Therefore the correct declaration should state, that `callbackfn` returns `any`:

```ts
interface Array<T> {
        ...
        every(callbackfn: (value: T, index: number, array: T[]) => any, thisArg?: any): boolean;
        ...
        some(callbackfn: (value: T, index: number, array: T[]) => any, thisArg?: any): boolean;
        ...
}
```

BTW, the `Array` method `filter` in `lib.es5.d.ts` is already declared like this:
```ts
        filter(callbackfn: (value: T, index: number, array: T[]) => any, thisArg?: any): T[];
```

**Comment by MartinJohns** [comment] 2019-04-05 13:46
Duplicate of #27496. Search terms used: `is:issue array every some boolean `

**Comment by MichaelTamm** [comment] 2019-04-05 16:29
> Changing the return type to any also means that this is legal: `.same(() => {})`. The inner function returns undefined and is compatible to any.

Yes, indeed! `.some(() => {})` **is** legal JavaScript (according to the spec) and should therefore not lead to an error.

I am aware, that the current typing of `every` and `some` _might_ catch some bugs, but in practice it never did for me. But to work around the too strict typing I always have to use `... => !!(...)` which is cumbersome.

Furthermore there is this asymmetry between the declaration of `Array.filter` and `Array.every`/`Array.some` in the current declarations.

**Closed** 2019-04-07 18:00 UTC
Labels: Duplicate
