### ISSUE TITLE
Polymorphic `this` behavior after method extraction

### ISSUE THREAD

**Issue by Guerric-P** [microsoft/TypeScript#45781] opened 2021-09-08 09:09 UTC
# Bug Report

After extracting a method from a class prototype (which becomes a plain function), the polymorphic `this` still behaves like the function is attached to the class prototype.

### 🔎 Search Terms

polymorphic this

### 🕗 Version & Regression Information

I saw this happening in the latest current version (4.4.2) and I don't know since when the bug exists.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=24&ssc=104&pln=1&pc=1#code/MYGwhgzhAEBiD29oG8BQ1pgB4EsIGF4A7AFwCd4QAuaCcnIgc2gF5oAiOshx9gbnTQAJjjIBTYCRzFCpCtVr0mrDlx79UggGY4QJMeKEBBXBBpqmAbQC6Ky5yW9rAjDr0GxQgCKiJU4uaONnYO3EzszpoY+nQAFG76hgByYAC2YjQABgkeQgAkyBaMAL6Z0ABk0ADWYgCe8FrQJAAWeACUKIIY4iQArmRETa0QljnJaWKRGMWoM6jAxHTQWogqRGIA7nCIAgtES+IQvXoqK-AAdDEksexjniZ47G180AD0r9AAKrUADmLQh0oADcxDBmh5AmFGDZNHsllcVAgLj8KCR4CRfmJLqCSLtFiRoBsKMo2FcbndjKYni93tAAJIEsAgCBIQEgEFgjxNJBFGHzfHQABG8F6RCEKiu50FDCEsVFQjEOnWQme-P2BKJxEYACYVML5eTdIl7lTnm8PgzMMzWaDgaDoODxNzFFC+XCNcTGABmRGIc4o9HozHYujnMA-H4gWpysWKhieAA00HsFIeEAiZtplqZLIBtvZ9sd-zRLp4boFmqYABZfcjUUG-iGSOdgEyQDGFUrExxU6aaRbGda8yyC5ynSXedYgA)

### 💻 Code

```ts
class Foo {
  axisControl: string = "string";
  directionControl: string = "string";

  filteredAxis: string[] = ["string"];
  filteredDirection: string[] = ["string"];

  test(filteredName: `filtered${string}` & keyof this) {
    return this[filteredName];
  }
}

const foo = new Foo;
const result = foo.test("filteredAxis"); // Type resolves here: string[]

const test = Foo.prototype.test;
const wrong = test("filteredAxis"); // It also resolves here to string[]

const bound = test.bind(undefined);
const wrong2 = bound("filteredAxis"); // It also resolves here to string[]

const wrong3 = Foo.prototype.test.apply(undefined, ["filteredAxis"]); // It also resolves here to string[]

const wrong4 = Foo.prototype.test.call(undefined, "filteredAxis"); // It also resolves here to string[]
```

### 🙁 Actual behavior

The `wrong`, `wrong2`, `wrong3`, `wrong4` variables types resolves to `string[]`

### 🙂 Expected behavior

Compilation errors to prevent the `TypeError: Cannot read properties of undefined` runtime errors

**Comment by andrewbranch** [comment] 2021-09-08 16:48
Note that you can opt into enforcing this by [explicitly annotating a `this` type for the method](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ1pgB4EsIGF4A7AFwCd4QAuaCcnIgc2gF5oAiOshx9gbnTQAJjjIBTYCRzFCpCtVr0mrDlx79UggGY4QJMeKEBBXBBpqmAbQC6Ky5yW9rAjDr0GxQgCKiJU4uaONnYO3EzszpoY+nQAFCQAFng0iXgANNBu+oYAcmAAtmI0AAZZHkIAJMgWjAC+xdAAZNAA1mIAnvBa0KkQAJQoghjiJACuZEQ9SRCWZbkFYpEYtagrqMDEdJmIKkRiAO5wiAIbRFviEKN6KlqIAHQxJLHsc54meOx9fNAA9D-QABV2gAHMTQC6UABuYhgCQ8gTCjBsmlOW0eKgQ8DuwIoJHgJBBYgeMJIJ02JGg+woyjYj2er2Mpk+3z+0AAkhSwCAIEgISBobCPD0kDVketydAAEbwUZEIQqR53SUMISxWVCMQ6PZCL7is4UqnERgAJhU0vV9N02TeTK+v3+HMw3N5MKhMOgcPEwsUiLFqIN1MYAGYMfccfj8YTiXQ7mBgcCQO01XLNQxPBl7Az3hAInbWY6uTzwa7+e7PWC8T6eH6JYamAAWUNY8N4gmg6MkO7ALkgZMarXpjhZ20sh2c53FnmlwVeyui6xAA). I know I’ve heard some team members express that they wish we did this automatically for class methods, but by now it would probably be too big a breaking change. I feel confident there must be an issue discussing this as a suggestion, but I’m having trouble finding it.

**Comment by andrewbranch** [comment] 2021-09-08 16:52
Just had to be extra clever with GitHub search. Duplicate of https://github.com/microsoft/TypeScript/issues/7968.

**Closed** 2021-09-10 18:00 UTC
Labels: Duplicate
