### ISSUE TITLE
JSX bug: TS2605 on stateless component

### ISSUE THREAD

**Issue by polkovnikov-ph** [Microsoft/TypeScript#6531] opened 2016-01-18 23:09 UTC
// test.tsx
	/// <reference path="react/react.d.ts" />
	/// <reference path="react/react-dom.d.ts" />
	import React = require('react');
	import ReactDOM = require('react-dom');
	let Test = (state: any) => <div />;
	ReactDOM.render(<Test />, document.getElementById('react'));

compiled with

	$ tsc test.tsx --jsx react --module commonjs

results in

	error TS2605: JSX element type 'Element' is not a constructor function for JSX elements.

In case we translate JSX by hand and use

	let Test = state => React.createElement("div", null);
	ReactDOM.render(React.createElement(Test, null), document.getElementById('react'));

everything works as expected.

**Comment by polkovnikov-ph** [comment] 2016-01-18 23:16
@RyanCavanaugh @sheetalkamat, please :)

**Comment by polkovnikov-ph** [comment] 2016-01-18 23:27
Now's time for some surprises. In case we translate JSX by hand and use

	let Test = state => React.createElement("div", null);
	ReactDOM.render(React.createElement(Test, null), document.getElementById('react'));

everything works as expected.

**Comment by thorn0** [comment] 2016-01-19 00:32
Duplicate of #6353

**Comment by polkovnikov-ph** [comment] 2016-01-19 00:47
Confirmed.

**Comment by polkovnikov-ph** [comment] 2016-01-19 00:59
Nope, this still doesn't work.

	function test<T>(x: T): T {
		return x;
	}
	let Test = test((state: any) => <div />);
	ReactDOM.render(<Test />, document.getElementById('react'));

emits

	error TS2605: JSX element type 'Element' is not a constructor function for JSX elements.
	  Property 'render' is missing in type 'Element'.

**Comment by polkovnikov-ph** [comment] 2016-01-19 01:03
Nope, still doesn't work.

	function test<T>(x: T): T {
		return x;
	}
	let Test = test((state: any) => <div />);
	ReactDOM.render(<Test />, document.getElementById('react'));

emits

	error TS2605: JSX element type 'Element' is not a constructor function for JSX elements.
	  Property 'render' is missing in type 'Element'.

**Comment by thorn0** [comment] 2016-01-19 01:54
It hasn't been released yet. Use `typescript@next` if you need it now.

**Comment by RyanCavanaugh** [comment] 2016-01-19 06:55
What @thorn0 said (thanks!)

**Closed by RyanCavanaugh** 2016-01-19 06:55 UTC
Labels: Duplicate

**Comment by polkovnikov-ph** [comment] 2016-01-19 08:19
@RyanCavanaugh But that's what I've seen in typescript@next and master!
