### ISSUE TITLE
Bad formatting for 'implement interface'

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#28507] opened 2018-11-13 20:09 UTC
```ts
interface Doggable {
    bark(): string;
    woof(): string;
}

class Dog implements Doggable {
    
}
```

**Expected**

```ts
class Dog implements Doggable {
    bark(): string {
        throw new Error("Method not implemented.");
    }

    woof(): string {
        throw new Error("Method not implemented.");
    }
}
```

**Actual**

```ts
class Dog implements Doggable {
    bark(): string {
        throw new Error("Method not implemented.");
    }    woof(): string {
        throw new Error("Method not implemented.");
    }

    
}
```

**Comment by AlCalzone** [comment] 2018-11-14 07:42
Duplicate of #26550 ?

**Closed** 2019-01-02 21:11 UTC
Labels: Duplicate
