### ISSUE TITLE
Enhance const assertions to narrow based on a known type

### ISSUE THREAD

**Issue by Harpush** [microsoft/TypeScript#34734] opened 2019-10-25 09:29 UTC
Lets assume i have a type
```ts
type Test = {a: 'one'} | {a: 'two'} | {a: 'three'};
````

If i create a literal array of this type and access the first element i get the union type (as expected)
```ts
const a: Test[] = [
  {
    a: 'one'
  },
  {
    a: 'two'
  }
];
const first = a[0].a; // type is 'one' | 'two' | 'three'
```

But if i use a const assertion i still get the union type
```ts
const a: Readonly<Test[]> = [
  {
    a: 'one'
  },
  {
    a: 'two'
  }
] as const;
const first = a[0].a; // type is still 'one' | 'two' | 'three' and i wish to have 'one'
```

Whats more i lose auto complete
```ts
const a: Test[] = [
  {
    a: 'one'
  },
  {
    a: 'two'
  },
  {
    // I have auto complete for property a and its type as 'one' | 'two' | 'three'
  }
];

const b: Readonly<Test[]> = [
  {
    a: 'one'
  },
  {
    a: 'two'
  },
  {
    // No auto complete at all
  }
] as const;
```

What i suggest is to somehow narrow the const assertion... maybe something like
```ts
const a = [
  {
    a: 'one'
  },
  {
    a: 'two'
  },
  {
    // Will have auto complete for property a and its type as 'one' | 'two' | 'three'
    // Will also error if i write b for example
  }
] as const<Test[]>;
const first = a[0].a; // type will be 'one'
```

While having auto completion to the Test type on one hand and on the other hand getting a const literal type.

**Comment by MartinJohns** [comment] 2019-10-25 10:35
This is happening because you explicitly widen the type again with your explicit type declaration. If you either let the compiler infer the const type or use a more restrictive type it will be a tuple instead of an array and it will work as you expect:

    const a = [{ a: 'one' }, { a: 'two' }] as const;
    const first = a[0].a; // Type is "one"

    const b: Readonly<[{a: 'one'}, {a: 'two'}]> = [{ a: 'one' }, { a: 'two' }];
    const second = a[1].a; // Type is "two"

Keeping it an array instead of a tuple will conflict with #9998 (and probably others).

**Comment by Harpush** [comment] 2019-10-25 11:02
@MartinJohns In example `a` i don't have the type safety for the `Test` model i mentioned and in example `b` i can't use the union... i need to explicitly define the tuple type. What i meant is saying the array is of the union type but the const assertion makes it actually a tuple (but a type safe one based on the `Test` model).
In the second example if i want to add a third item i need to add it in the tuple type declaration too which makes the whole union usage not relevant.
An even more simplified example can be
```ts
type Simple = 'a' | 'b' | 'c';
const b = ['a', 'b'] as const<Simple> // Now the language should allow me to add only a | b | c and it should become a tuple
```
With your solution i need to write
````ts
const b: Readonly<['a', 'b']> = ['a', 'b']
// ... later in time
const b: Readonly<['a', 'b', 'c']> = ['a', 'b', 'c']
```

**Comment by nmain** [comment] 2019-10-25 15:16
I'm not 100% on your use case, but this feels like a duplicate of https://github.com/microsoft/TypeScript/issues/31062

**Comment by Harpush** [comment] 2019-10-25 21:41
@nmain Seems like the same problem... probably a duplicate then

**Closed** 2019-10-30 00:00 UTC
Labels: Question
