### ISSUE TITLE
[Feature Request] Allow reference to declaration files with import and export keywords

### ISSUE THREAD

**Issue by kaysonwu** [microsoft/TypeScript#37294] opened 2020-03-09 14:18 UTC
## Search Terms

`d.ts` `reference` `declaration` `import export`

## Suggestion

Allow reference to declaration files (`.d.ts`) with `import` and `export` keywords

## Use Cases

I want to use it for type extends and reuse，Currently, it can only be import as a module.

## Examples

**example.d.ts**

```
import { Action, AnyAction, Reducer } from "redux";

interface Model<S = any, A extends Action = AnyAction> {
    namespace: string;
    state: S,
    reducers: Record<string, Reducer<S, A>>
}
```

**example.ts**

```
/// <reference path="./example.d.ts" />

const User : Model = {
  namespace: 'user',
  state: {},
  reducers: {
    
  }
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment] 2020-03-09 19:23
Duplicate of #36812.

**Closed by DanielRosenwasser** 2020-03-09 19:23 UTC
