### ISSUE TITLE
Allow symbol as object keys

### ISSUE THREAD

**Issue by sebilasse** [Microsoft/TypeScript#8611] opened 2016-05-15 20:14 UTC
**TypeScript Version:** 
1.8.10 - editing with github's Atom / TS

**Code**

```ts
// A self-contained demonstration of the problem follows...
export interface Container {
  stores: { [s: symbol]: string };
}
```

**Expected behavior:**
It should be fine ...

**Actual behavior:** 
err: `An index signature parameter type must be 'string' or 'number'`

**Comment by malibuzios** [comment] 2016-05-15 21:34
#1863 seems to include both indexing with symbols, and using them in index signatures. I'm not sure how much of the first part has already been implemented but the issue is currently labeled as 'Accepting PRs'.

**Comment by mhegazy** [comment] 2016-05-16 17:33
closing in favor of #1863

**Closed** 2016-05-16 17:33 UTC
Labels: Duplicate
