### ISSUE TITLE
Set.has() and Array.includes() should narrow the type of their argument to the type of this when they return true

### ISSUE THREAD

**Issue by jyasskin** [microsoft/TypeScript#51678] opened 2022-11-29 05:59 UTC
# lib Update Request

## Configuration Check

My compilation *target* is `ES2022` and my *lib* is `the default`.

## Missing / Incorrect Definition

`Set.has()` and `Array.includes()` should narrow the type of their argument to the type of `this` when they return true (which implies they should accept wider types as arguments).

This is probably impossible until https://github.com/microsoft/TypeScript/issues/14520 is solved, but I wanted to add a more concrete use case than just making it convenient to pass wide arguments.

## Sample Code

```ts
type Ingredient = {
  amount?: string;
  unit?: string;
  name?: string;
}
const ingredientKeys = new Set(["amount", "unit", "name"] as const);

let key: string = "...";
let value: string = "...";
let result: Ingredient = {};
// Doesn't work but should:
if (ingredientKeys.has(key)) {
  result[key] = value;
}

// Works, but can't do it as a member function:
function has<T extends U, U>(set: ReadonlySet<T>, elem: U): elem is T {
  const wider: ReadonlySet<U> = set;
  return wider.has(elem);
}
if (has(ingredientKeys, key)) {
  result[key] = value;
}
```

[Playground Link](https://www.typescriptlang.org/play?target=9&jsx=0#code/C4TwDgpgBAkgdgcwE4QCYEsJ2FAvFAbwFgAoKKAQwFsB7AV2wH4AuKAZ2CXUQG5TyG6YC3aduCPmShxqEERy69SAX1KkAxjTgco4lBizAA0hBBs80iAHcoAZQjAAFAG0ARNXrZXAGiivBwD5+MlQQrgC6lOaa2sAAlJKkAGYM6sDoWlAAFhRsADwAKlAQAB7AWKjmAKq+VQB8jmwOrABKEBSoWgA2IPbAhXW+EF0QVKxVcazDo7rmRcRSMTpW6KgQSK3tnXA9fXn1Fk3AkuQowHRIcFAra0gAdDlsjtNUCSpqJClwaRlXKB3wZBoTDYRyoCjACisABiNCQVAAIhCKJNYIh9CCcAtyEscCg2HQusBmICMYYLARlCcoEk4VBHLioM4ANamXwANwoXToEEiNCSUHBkLihH45F0AscoEg-KgnO50AAhLh8K4FOJXCKYuk4DzElJyOhJY9HHpgYYTGZfKyQHERdjxacIASiSzTJF8PK9WLyKoDVAfVAAPRBuxZehdVDXOHM5iBo30s0GbCWtgPXKOG120X+p0u4BukAeuVc73+v2+sVnC5-Z2E47vEgfRnlDiw+FIyEWODWKDtxHIxxvEit4D9zsUO5HRzuWgMQK+VwARigS6DACZNZJR+PkVOHDOAkFXOo6GAt6Qd3CB5D905XCEwouCQgKEgLyPnWPrxO74e4CgmgIHA6AAF5oMer5IAARhQCBhMOGhaGwNAjHcXQ0AgjgAFK2AA8gAclOYiIEaICOP8qCkuaoJXh2yJ2gkQA)

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/has

**Comment by jyasskin** [comment] 2022-11-29 06:14
Yikes, this also requires https://github.com/microsoft/TypeScript/issues/15048 even though that behavior isn't documented in https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates.

**Comment by fatcerberus** [comment] 2022-11-29 06:29
If you mean the requirement that type predicates be exhaustive, that *is* documented, albeit admittedly somewhat offhandedly:

> Notice that TypeScript not only knows that pet is a Fish in the if branch; it also knows that in the else branch, you don’t have a Fish, so you must have a Bird.

which implies the type predicate must be exhaustive.

**Comment by jcalz** [comment] 2022-11-29 14:47
Essentially a duplicate of #36275

**Comment by MoritzKn** [comment] 2022-11-29 14:50
Is this that complicated? This seems to fulfill the requirement already:

```ts
/** Shouldn't this be the type signature of Array.prototype.includes?
function arrayIncludes<T>(arr: T[], v: unknown): v is T {
  return arr.includes(v as T);
}
```

I assume I am missing something but couldn't the type signature simply be changed to this?

**Comment by jcalz** [comment] 2022-11-29 14:52
^ https://github.com/microsoft/TypeScript/issues/36275#issuecomment-702233949

**Comment by fatcerberus** [comment] 2022-11-29 15:03
I think this [Playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAQwE6uQTwJKQDYgAmApgM4A8AKgHwAUaqAXIpQNoC6ANIgG7PgBrMHADuYAJTMeiGKRaIA3gChEiVMSghUSBgDoY+ImVrTkcyuIDcSgL5KlEBKSgp0zZ6gMBzDogC8iKyIAETAcHDB3MEARmjBiOzWjmDOiFBkUO5QnmBe-iEADuHAwdYwwIj06Fi4EAQkpFWo3OnO4uKKKqppGdYA9H2qAHoA-LaIxHikxJ3dPc79g4ijtkpAA) illustrates the issue with that signature nicely.

**Comment by fatcerberus** [comment] 2022-11-29 15:31
To be clear, #15048 is required for the reasons explained by @jcalz.  #14520 is optional (the alternative is to type the search term as `unknown`), but most people still want it to be error to check for an unrelated type in an array, so `strArray.includes(num)` should be an error, but `strArray.includes(strOrNum)` shouldn't.  Without #14520 you only have the choice of both being an error, or neither.

**Closed** 2022-12-04 18:00 UTC
Labels: Duplicate
