### ISSUE TITLE
Accessing private properties from an external function with `this` parameter

### ISSUE THREAD

**Issue by roddolf** [Microsoft/TypeScript#18281] opened 2017-09-06 18:14 UTC
If I have a class with a private property: 
```typescript
class MyClass {
  private privateProperty;
}
```

I would expect that having a function with the `this` parameter as the class I could access to the private property of the class:
```typescript
function myFunction( this:MyClass ) {
  this.privateProperty; // Gives an error
}
```

Since I'm specifying where the function is running, shouldn't it be treated as if it's "inside" the class?

**Comment by aluanhaddad** [comment] 2017-09-06 18:22
This is a duplicate of #17694

**Comment by mhegazy** [comment] 2017-09-21 22:42
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-21 22:42 UTC
Labels: Duplicate
