### ISSUE TITLE
{ tag: 'foo' | 'bar' } should be assignable to { tag: 'foo' } | { tag: 'bar' }

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#19813] opened 2017-11-07 17:28 UTC
Logically it seems like this should work:

```ts
declare const x: { tag: 'foo' | 'bar' };

const foobar: { tag: 'foo' } | { tag: 'bar' } = x
//    ^^^^^^ Type '{ tag: "foo" | "bar"; }' is not assignable to type '{ tag: "foo"; } | { tag: "bar"; }'.
//             Type '{ tag: "foo" | "bar"; }' is not assignable to type '{ tag: "bar"; }'.
//               Types of property 'tag' are incompatible.
//                 Type '"foo" | "bar"' is not assignable to type '"bar"'.
//                   Type '"foo"' is not assignable to type '"bar"'.
```

Of course this is only the case if there aren't additional fields with differing types for `tag` to discriminate, so this is admittedly perhaps a niche use case.

**Comment by mhegazy** [comment] 2017-11-07 17:41
Duplicate of https://github.com/Microsoft/TypeScript/issues/14865

**Closed** 2017-11-07 19:54 UTC
Labels: Duplicate
