### ISSUE TITLE
[Transforms] Missing module name in ES6 module when emit short-hand property assignment in object literal

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#8204] opened 2016-04-20 00:14 UTC
**Original**
```ts
module m {
    var z = x;
    var y = {
        a: x,
        x
    };
}
```
**Expect**
```js
(function (m) {
    var z = m.x;
    var y = {
        a: m.x,
        x: m.x
    };
})(m || (m = {}));
```
**Actual**
```js
(function (m) {
    var z = m.x;
    var y = {
        a: m.x,
        x
    };
})(m || (m = {}));
```

- objectLiteralShorthandPropertiesWithModuleES6.js
- giant.js

**Comment by sandersn** [comment] 2016-04-20 18:19
Duplicate of #7682 -- I'll copy these test cases over to that bug so that we'll remember to check them.

**Closed by sandersn** 2016-04-20 18:19 UTC
Labels: Bug, Domain: Transforms
