### ISSUE TITLE
Wrong boolean type after callback

### ISSUE THREAD

**Issue by jens-duttke** [microsoft/TypeScript#36544] opened 2020-01-31 12:16 UTC
**TypeScript Version:**  3.8.0-dev.20200130
**Search Terms:** wrong boolean type callback

**Code**

```ts
let b: boolean = false;

[0].forEach(() => {
    b = true;
});

if (b === true) {
    console.log(b);
}
```

**Expected behavior:**
In line `if (b === true) {`, `b` should be either of type `true` or of type `boolean`.

**Actual behavior:**
TypeScript throws an error in line `if (b === true) {`:
> This condition will always return 'false' since the types 'false' and 'true' have no overlap.(2367)

**Playground Link:** [Playground Link](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20200130#code/DYUwLgBARgXND29QEMB2EC8EBmzgGcQBuAWAChyBtABgF0A6beAJwFFkBjACwAoeBKTAD4IAb3IRJ0TBDDMArsXIBffqQpkAltgg8omDFjmLB4slIgd4qfEhD1g8AOZ61K8kA)

**Comment by jcalz** [comment] 2020-01-31 12:32
Duplicate of #9998.  The compiler can’t easily realize that the `forEach` callback mutates `b`.

The solution here is probably to disable control flow narrowing on the original assignment, since it’s not helping you:

```ts
let b = false as boolean;
```

**Closed** 2020-02-02 18:00 UTC
Labels: Duplicate
