### ISSUE TITLE
tsserver.js 100% CPU on Code Insiders 

### ISSUE THREAD

**Issue by dusty** [microsoft/TypeScript#31196] opened 2019-04-16 14:47 UTC
- VSCode Version: Version 1.34.0-insider (1.34.0-insider)
- OS Version: macOs 10.14.4 (18E226)

Steps to Reproduce:

1. Open any javascript file in vscode
2. CPU spikes to 100% in Code Helper

Does this issue occur when all extensions are disabled?: Yes

Whenever I open a javascript file in vscode the CPU spikes to 100% and it vscode is slow.  It will stay between 98%-150% while the file is open.  I've tried installing the insider edition and disabling all extensions and that didn't change anything.

I have node v11.13.0 installed on my computer.  I don't have typescript installed, nor am I using it in this project that I'm working with.

This happens even if I open a single javascript file, I don't need to have a folder opened.

What additional steps can I take to help find the cause of this?

Thanks

<img width="1440" alt="Screen Shot 2019-04-16 at 7 40 07 AM" src="https://user-images.githubusercontent.com/792/56219423-93b4e480-601b-11e9-8897-e8f6b8fefa70.png">

**Comment by mjbvz** [comment] 2019-05-01 18:14
Thanks for the logs. Moving this issue upstream as I don't see anything suspicious in the logs from @dusty. These were collected when the high cpu usage was happening, correct?

@awwong1 From your logs, I see that you have `@types/styled-components` installed in your workspace. Can you please make sure you have the latest version of this. There was a perf issue with a few versions: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34391

**Comment by dusty** [comment] 2019-05-01 19:29
Yes, this was during high CPU.

**Comment by masaltzman** [comment] 2019-05-02 14:30
Sorry all, I didn't realize that this thread was about the insiders build. Well, I downloaded the insiders build and I haven't been able to duplicate this problem, seems to be fixed on insiders. Here's my current version:

Version: 1.33.0-insider (user setup)
Commit: 9b849d9de7168eb4f685823bf9b9e27a0a8dae74
Date: 2019-03-08T06:59:35.464Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by dusty** [comment] 2019-05-02 16:55
I'm still having issues with code insider.  On 1.34.0.

Could it be the size of the project?  I'm working on a relatively large project, we have about 1600 src .js files.

<img width="1440" alt="Screen Shot 2019-05-02 at 9 53 34 AM" src="https://user-images.githubusercontent.com/792/57092421-43e34800-6cc0-11e9-8ff6-340d1a865c0a.png">

**Comment by masaltzman** [comment] 2019-05-03 00:48
> Sorry all, I didn't realize that this thread was about the insiders build. Well, I downloaded the insiders build and I haven't been able to duplicate this problem, seems to be fixed on insiders. Here's my current version:
> 
> Version: 1.33.0-insider (user setup)
> Commit: 9b849d9de7168eb4f685823bf9b9e27a0a8dae74
> Date: 2019-03-08T06:59:35.464Z
> Electron: 3.1.3
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.17763

Haha, I spoke too soon. It's happening again right now. Oddly tsserver is not the culprit, at least according to the process explorer. I didn't get a chance to turn on the tsserver verbose log, but will do that now and post the log when this happens again. Or, is there another log you need since process explorer does not show tsserver to be consuming cpu?

![image](https://user-images.githubusercontent.com/11338843/57115205-838b4d80-6d1b-11e9-9a14-f25d03100420.png)

**Comment by awwong1** [comment] 2019-05-14 17:55
@mjbvz I have the latest version of `@types/styled-components` (`4.1.15`).
I still experience issues using VSCode 1.33.1.

Is this issue related to [VScode shipping with TypeScript 3.4](https://code.visualstudio.com/updates/v1_33#_typescript-34)?
I downgraded my editor to VSCode 1.32.3 and I do not experience any performance issues, even with `typescript@3.4.5` in my `package.json` file.

**Comment by mjbvz** [comment] 2019-05-17 20:26
@awwong1 You also need to switch your workspace to use your local typescript version by by following [these instructions](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions)

Please try this again, but using the latest typescript@next

**Comment by akontaroudis** [comment] 2019-06-02 11:41
I have tried typescript 3.3.1, 3.4 and @next. Cleared typescript caches and tsserver is still using 100% of the cpu when typing. Every keystroke takes around 2-3 seconds.

**Comment by RyanCavanaugh** [comment] 2019-08-22 22:26
There are a lot of different versions being reported here and a lot of different possible root causes. 3.3 had some issues that were fixed in 3.4; if anyone's on 3.5 and still seeing this, please log a new issue with server logs as suggested by @mjbvz above. Thanks!

**Closed by RyanCavanaugh** 2019-08-22 22:26 UTC
Labels: Domain: Performance, Unactionable
