### ISSUE TITLE
Discriminated unions and object literals

### ISSUE THREAD

**Issue by thorn0** [Microsoft/TypeScript#18629] opened 2017-09-21 01:28 UTC
I'm not sure if it's a bug.

**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

playground, 2.5.1-insiders.20170825

**Code**

```ts
interface Square {
    kind: "square";
    size: number;
}

interface Rectangle {
    kind: "rectangle";
    width: number;
    height: number;
}
type Shape = Square | Rectangle;

var a: Square = { kind: 'square', size: 100, width: 50 }; // error
var b: Shape = { kind: 'square', size: 100, width: 50 };  // oops
```

**Expected behavior:**

Same error. From the `kind` property, TypeScript should understand that the second object literal is of type `Square` and prevent us from attaching the `width` property to it.

**Actual behavior:**

no error

**Comment by mhegazy** [comment] 2017-09-21 16:48
Duplicate of https://github.com/Microsoft/TypeScript/issues/12745

**Comment by mhegazy** [comment] 2017-10-05 18:18
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-05 18:18 UTC
Labels: Duplicate
