### ISSUE TITLE
Inconsistent generic type inference between record type and object literal type

### ISSUE THREAD

**Issue by hkleungai** [microsoft/TypeScript#56821] opened 2023-12-18 06:50 UTC
### 🔎 Search Terms

record, generics, object literal

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [Generics](https://github.com/Microsoft/TypeScript/wiki/FAQ#generics)

### ⏯ Playground Link

https://tsplay.dev/mq0kQN

### 💻 Code

```ts
declare function forEach<T extends string | number | symbol>(
    data: { [a in T]: unknown },
    cb: (x: T) => unknown
): void;

declare let record: Record<string, unknown>;
forEach(record, key => {})
//              ^?

declare let obj: { [a: string]: unknown };
forEach(obj,    key => {})
//              ^?
```

### 🙁 Actual behavior

- `key` for `record: Record<string, unknown>` is inferred as `string` type
- `key` for `{ [a: string]: unknown }` is inferred as `string | number` type

### 🙂 Expected behavior

both `key` should be inferred as the same type, i.e. `string` type.

**Comment by fatcerberus** [comment] 2023-12-18 07:14
This is intentional, if surprising.  Normally `keyof` a string index signature is `string | number`, because the type is indexable by either.  `Record`, however, is defined as a mapped type which produces a `keyof` of just `string`.  Duplicate of https://github.com/microsoft/TypeScript/issues/55706.

**Comment by fatcerberus** [comment] 2023-12-18 07:19
Duplicate of https://github.com/microsoft/TypeScript/issues/49540.

**Comment by hkleungai** [comment] 2023-12-18 07:48
Thanks @fatcerberus for the quick response. I have read through the issues you mentioned, and I want to further something.

I find that by changing the obj type from index signature to mapped type, it gives the desired type.

Playground link: https://tsplay.dev/mb1nBN

Code:
```typescript
declare function forEach<T extends string | number | symbol>(
    data: { [a in T]: unknown },
    cb: (x: T) => unknown
): void;

declare let               obj_index_sig: { [s: string]: unknown };
//                        ^?
forEach(obj_index_sig,    key => {})
//                        ^?

declare let               obj_mapped_type: { [s in string]: unknown } 
//                        ^?
forEach(obj_mapped_type,  key => {})
//                        ^?
```

But then, what is the actual difference between `{ [s: string]: unknown }` and `{ [s in string]: unknown }`?

On one hand, it seems the mapped type does not just devolved into an index signature, based on how the tsc successfully interpreted the `string` type from `key` for `obj_mapped_type`.

But on the other hand, the ts playground inlay seems indicate they have the same "shape" (with the only difference in the LHS key, `s` vs `x`.

```typescript
let obj_index_sig: { [s: string]: unknown; }
let obj_mapped_type: { [x: string]: unknown; }
```

How should I understand the difference between `{ [s: string]: unknown }` and `{ [s in string]: unknown }`?

**Closed** 2023-12-22 01:27 UTC
Labels: Duplicate
