### ISSUE TITLE
Mapped Types and Generics

### ISSUE THREAD

**Issue by gamli** [Microsoft/TypeScript#13848] opened 2017-02-02 20:08 UTC
First of all: thank you for TypeScript and the really awesome speed it is developed!!!

I am having problems using Mapped Types in Generic (sub)classes that constrain their type parameters. I think the best description is the code below. I'll follow it up with some explanation.

**TypeScript Version:**  2.1.5

**Code**

```ts
class GenericBase<TValue> {

    takePartial(partial: Partial<TValue>) {
        // ...
    }
}

class GenericSub<TValueSub extends GenericSubValue> extends GenericBase<TValueSub> {

    subTakePartial(subPartial: Partial<TValueSub>) {
        super.takePartial(subPartial); // ok
        super.takePartial({}); // should be ok - but gives error
        super.takePartial({ GenericFoo: "GenericFooValue" }); // should be ok - but gives error
    }
}

class GenericSubValue {
    GenericFoo: string;
}
```

**Expected behavior:**
The calls ```super.takePartial({})``` and ```super.takePartial({ GenericFoo: "GenericFooValue" })``` in class ```GenericSub``` should compile since ```{}``` and  ```{ GenericFoo: string }``` are partial types of any type that extends ```GenericSubValue``` (what is what the type constraint of GenericSub demands).

**Actual behavior:**
The calls ```super.takePartial({})``` and ```super.takePartial({ GenericFoo: "GenericFooValue" })``` in class ```GenericSub``` result in a compilation error.

However, it does work on a non-generic sub type of ```GenericBase```:
```ts

class ConcreteSub extends GenericBase<ConcreteSubValue> {

    subTakePartial(subPartial: Partial<ConcreteSubValue>) {
        super.takePartial(subPartial); // ok
        super.takePartial({}); // ok
        super.takePartial({ GenericFoo: "GenericFooValue" }); // ok
        super.takePartial({ ConcreteFoo: "ConcreteFooValue" }); // ok
    }
}

class ConcreteSubValue extends GenericSubValue {
    ConcreteFoo: string;
}
```

**Comment by ahejlsberg** [comment] 2017-02-02 21:41
The first error (passing an empty object literal) was fixed by #13772.

The second error is by design because for a type parameter `T extends C`, `T` is assignable to `C`, but `C` is not assignable to `T`. In this specific case, a `GenericSubValue` is not assignable to a `Partial<TValueSub>` because the actual type substituted for `TValueSub` might have properties that are further derived than those in `GenericSubValue`.

**Comment by gamli** [comment] 2017-02-02 22:14
What do you mean by "the actual type substituted for ```TValueSub``` might have properties that are further derived than those in ```GenericSubValue```"?
Does that mean that a sub type of ```GenericSubValue``` could have a property ```ConcreteFoo``` of  a derived type of e.g. ```string``` or rather some class?

Is there even a way within the type system to make ```GenericBase``` and ```GenericSub``` work as intended in the comments/expected behaviour?

**Comment by ahejlsberg** [comment] 2017-02-02 22:30
> Does that mean that a sub type of GenericSubValue could have a property ConcreteFoo that is derived of e.g. string or rather some class?

Yes, for example:

```ts
class ConcreteSubValue extends GenericSubValue {
    ConcreteFoo: "yes" | "no";
}

**Comment by gamli** [comment] 2017-02-02 22:32
Sorry I edited my comment after you answered :(

**Comment by gamli** [comment] 2017-02-02 22:38
In your example, do you mean ```GenericFoo: "yes" | "no"``` (so narrowing the superclasse´s type down)?

**Comment by ahejlsberg** [comment] 2017-02-02 22:40
Sorry, yes I meant `GenericFoo`. Now fixed.

**Comment by gamli** [comment] 2017-02-02 22:41
Something about the ```RecursivePartial<T>```?

**Comment by ahejlsberg** [comment] 2017-02-02 22:43
It doesn't change in the recursive case. As I said above, a for `T extends C`, `C` is not assignable to `T`, nor is it assignable to `Partial<T>`, because the actual type argument for `T` could be further derived than `C`.

**Comment by gamli** [comment] 2017-02-02 23:00
Not trying to be a nuisance here - just for understanding: 
* Should "...nor is it assignable to ```Partial<T>```..." say "...nor is it assignable to ```RecursivePartial<T>```..." (because that was the example)?
* Isn't "...the actual type argument for ```T``` could be further derived than ```C```..." always true because of thethe constraint ```T extends C```?
What I am actually trying to do is to provide a typesafe implementation of something similar to React's ```setState(...)``` that works when inheriting from base components that apply constraints to the sub component's state type and update part of the state by themselfs.
(Is that still a valid discussion for github or should I turn to stackoverflow with something like that?)

**Closed** 2017-02-04 08:29 UTC
Labels: Working as Intended
