### ISSUE TITLE
Generated declaration file missing reference path for custom types.

### ISSUE THREAD

**Issue by mastermatt** [Microsoft/TypeScript#20367] opened 2017-11-30 15:35 UTC
I've tried to provide a simple version that reproduces the issue I'm seeing. It doesn't seem possible to include custom types in a package when attempting to publish because the custom types are never referenced in the generated `.d.ts` files. 

In this trivial example, the community provided `@types/request` is being augmented with declaration merging from files in the project's `./typings` dir.

**Code**
#### index.ts
```ts
import * as request from "request";
import {RequestBody, Request} from "request";

export function doPost(uri: string, body: RequestBody): Request {
  return request.post(uri, {body});
}
```
#### typings/request/index.d.ts
```ts
import {ReadStream} from "fs";

declare module "request" {
  type RequestBody = Buffer | object | ReadStream | string | undefined;
}
```
#### package.json
```json
{
  "name": "test",
  "version": "0.0.1",
  "main": "index.js",
  "types": "./index.d.ts",
  "files": [
    "index.js",
    "index.d.ts",
    "typings/**/*.d.ts"
  ],
  "dependencies": {
    "@types/request": "^2.0.8",
    "request": "^2.83.0"
  },
  "devDependencies": {
    "@types/node": "^8.0.53",
    "typescript": "^2.7.0-dev.20171130"
  }
}
```
#### tsconfig.json
```json
{
  "compilerOptions": {
    "target": "ES2016",
    "module": "commonjs",
    "declaration": true,
    "rootDir": "./",
    "strict": true,
    "moduleResolution": "node",
    "baseUrl": "./"
  },
  "include": [
    "index.ts",
    "typings/**/*"
  ]
}
```
**Expected behavior:**
I should be able to publish the files listed in `package.json#files` to an NPM registry and have all the typings, including the custom types, available when imported by another package.

**Actual behavior:**
#### index.d.ts
auto generated via `tsc -p .`
```ts
/// <reference types="request" />
import { RequestBody, Request } from "request";
export declare function doPost(uri: string, body: RequestBody): Request;
```
Produces the error
> Error:(2, 10) TS2305: Module "~/src/test/node_modules/@&#8203;types/request/index" has no exported member 'RequestBody'.

Manually adding
```ts
/// <reference path="typings/request/index.d.ts" />
```
Seems to be the current work around.

Up-to-date documentation on how to write/use custom types (not added to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)) is lacking so I'm honestly not sure if this is a bug or if I'm doing something wrong, but scouring the internet has lead me to believe that this is not the intended behavior.

**Comment by mhegazy** [comment] 2017-11-30 17:38
`/// <reference types="request" />` has a specific meaning today. it knows it needs to look in `@types` packages.
 
if you have some overrides, treat these like you treat your own code. i.e. you need to publish them all along with your code; the compiler does not know that this .d.ts file is an override for some library. `/// <reference path="..." />` are maintained in the input, so you can add one in your input and it should be transformed with the file.

That said, I highly recommend against shipping a package with an override to an already available declaration in the global scope. If your declaration file conflicts with an already available `@types` package, you are setting your users for a long road of pain. better of make the update to Definitely Typed. If this is merely an augmentation (i.e. definition an addition your package does on top of the original), then it should be fine.

**Comment by mastermatt** [comment] 2017-11-30 20:13
Keep in mind I used the `request` lib here as an example.
All the `.d.ts` files in my `typings` directory are being published, just not referenced. 

Are you saying I should remove `"typings/**/*"` from `tsconfig.json#include` and add a bunch of  `/// <reference path=***.d.ts" />` where needed? The StackOverflow community seems to think that reference paths shouldn't be used regularly anymore (`tslint` complains about it too, even [MS rec](https://github.com/Microsoft/tslint-microsoft-contrib/blob/npm-5.0.1/recommended_ruleset.js#L224)). 

I have quite a large set of custom types from closed-sourced vanilla js packages that I'm importing. It seems odd that I can't tell TS "here is the directory where I have my custom types, it looks just like `node_modules/@types`, use it too". Feature request? I was hoping `compilerOptions#paths` would fit this bill, but it stops scanning options once it finds it's first match so doesn't work for augmentations. 

>If your declaration file conflicts with an already available `@types` package, you are setting your users for a long road of pain. better of make the update to Definitely Typed.

That's nice in theory, but it takes days/weeks/months for bugs to get merged into Definitely Typed. For non-open source work that doesn't cut the mustard so we're forced to loosen how strict the type-checking is or include augmentations in our project.

**Comment by mhegazy** [comment] 2017-11-30 21:52
> Are you saying I should remove "typings/**/*" from tsconfig.json#include and add a bunch of /// <reference path=***.d.ts" /> where needed?

Ideally you should not put any types in the global scope directly. these do not version well.. 
if you have all your declarations in modules, then you do not need `/// <reference path=".." />` since you are using `import` statements.
If however these types are meant to be used as globals, then `/// <reference path=".." />` is your best bet.

> I have quite a large set of custom types from closed-sourced vanilla js packages that I'm importing. It seems odd that I can't tell TS "here is the directory where I have my custom types, 

you can, just use `--typeRoots`. but this is not the issue, the issue is that your code will now have references to type packages that your users have no access to them.. and not sure what the compiler can do to help you out here..

>  it looks just like node_modules/@types, use it too

not sure i understand what you mean

>  I was hoping compilerOptions#paths would fit this bill, but it stops scanning options once it finds it's first match so doesn't work for augmentations.

`paths` only works for modules, and not globals. use `--typeRoots` for globals.

> That's nice in theory, but it takes days/weeks/months for bugs to get merged into Definitely Typed.

feel free to ping me and i can take a look and get it merged faster.

Also note if everyone published their own definition files for dependencies you are left with a huge dependency conflict hell that your customers have to deal with. by you doing the right thing, you save your package users hours later.

**Closed** 2017-12-01 21:23 UTC
Labels: Question
