### ISSUE TITLE
Have `never` implicitly return from its location.

### ISSUE THREAD

**Issue by isiahmeadows** [Microsoft/TypeScript#12883] opened 2016-12-13 15:29 UTC
This would fix #12825, and pave the way for another suggestion to fix #8655. I'll link the proposed fix's issue here after I submit it.

**Comment by isiahmeadows** [comment] 2016-12-13 16:02
The corresponding issue to fix #8655 given this is #12885 (which is far broader in scope).

**Comment by mhegazy** [comment] 2016-12-13 17:48
this is a duplicate of https://github.com/Microsoft/TypeScript/issues/12825. the issue is that the compiler does things in phases. when it knows about the control flow, it does not know about types. so it is an implementation limitation, both issues have the same limitation. it is not an issue of how to handle `never` when found.

**Comment by isiahmeadows** [comment] 2016-12-15 18:01
Oh. So it would be much more difficult to accomplish than I initially
anticipated. I didn't realize that.

On Tue, Dec 13, 2016, 12:48 Mohamed Hegazy <notifications@github.com> wrote:

this is a duplicate of #12825
<https://github.com/Microsoft/TypeScript/issues/12825>. the issue is that
the compiler does things in phases.

So I'm guessing past phases have no way of communicating to future phases
any node-specific data? How difficult would that be?

when it knows about the control flow, it does not know about types. so it
is an implementation limitation, both issues have the same limitation. it
is not an issue of how to handle never when found.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/TypeScript/issues/12883#issuecomment-266809801>,
or mute the thread

**Closed** 2016-12-19 18:03 UTC
Labels: Duplicate
