### ISSUE TITLE
Auto imports using import <module> = require() instead of import <module> from 

### ISSUE THREAD

**Issue by tx-steven** [microsoft/TypeScript#36809] opened 2020-02-14 22:12 UTC
*TS Template added by @mjbvz*

**TypeScript Version**: 3.7.5

**Search Terms**
- auto imports
- javascript 

---

Hey guys. Recently I noticed my auto imports options as well as my quick fix options are not using import from syntax with modules that don't have a default export.  Did something change recently settings or configuration to cause this? 

*tsconfig*: 
![Screen Shot 2020-02-14 at 2 08 29 PM](https://user-images.githubusercontent.com/50590506/74572133-7e5a6080-4f33-11ea-83e0-e8f16610fe6f.png)

- VSCode Version: 1.42.1
- OS Version: macOS Mojave 10.14.3

Steps to Reproduce:

1. type out a function
2. use auto imports or select from quick fix options
3. import default option no longer available

![Screen Shot 2020-02-14 at 2 11 19 PM](https://user-images.githubusercontent.com/50590506/74572401-ead55f80-4f33-11ea-81ee-b57932dd646e.png)

![Screen Shot 2020-02-14 at 2 11 58 PM](https://user-images.githubusercontent.com/50590506/74572512-16584a00-4f34-11ea-846b-77398d7df43d.png)

**Comment by andrewbranch** [comment] 2020-02-21 20:09
@tx-steven this should be fixed by https://github.com/microsoft/TypeScript/pull/36475. Can you try with TypeScript 3.8?

**Comment by tx-steven** [comment] 2020-02-22 00:24
Hey @andrewbranch, it works now after upgrading! thank you for the help

**Comment by andrewbranch** [comment] 2020-02-22 00:26
No problem!

Marking as duplicate of #29038 for record-keeping

**Closed by andrewbranch** 2020-02-22 00:26 UTC
Labels: Duplicate
