### ISSUE TITLE
Sometimes when using JSX Tag completion, the trailing tag termination character disappears

### ISSUE THREAD

**Issue by yamachu** [microsoft/TypeScript#46704] opened 2021-11-01 04:53 UTC
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.62.0-insider (Universal) Commit: ff1e16eebb93af79fd6d7af1356c4003a120c563
- OS Version: macOS 10.15.7
- Extension: JavaScript and TypeScript Nightly v4.5.20211031

Steps to Reproduce:

1. Open React JSX file
2. Write a JSX tag and select the hovered completion content (with return key)

![remove-trailing-tag](https://user-images.githubusercontent.com/1955233/139623250-aaa6e363-42a0-409a-89be-926782e3a051.gif)

related issue
https://github.com/microsoft/vscode/issues/82324

**Comment by mjbvz** [comment] 2021-11-05 21:39
Possibly a similar root cause to https://github.com/microsoft/vscode/issues/136377

Minimal example:

```ts
import * as React from 'react';

const a = (
    <span >

    </span>;
)
```

The replacement span returned is:

```
 "replacementSpan": {
                "start": {
                    "line": 4,
                    "offset": 11
                },
                "end": {
                    "line": 4,
                    "offset": 12
                }
            },
```

Which ends up replacing the closing `>`

**Comment by andrewbranch** [comment] 2021-11-08 22:47
I think we probably don’t need a replacement span at all for JSX attribute completions. The identifier that the user started to type should already automatically be set as the `optionalReplacementSpan` on the top-level response. Otherwise, I don’t think there’s anything to replace.

**Closed** 2021-11-11 02:18 UTC
Labels: Bug, Fix Available
