### ISSUE TITLE
Error: Type T cannot be used to index intersection with Record<T, any>

### ISSUE THREAD

**Issue by NaridaL** [Microsoft/TypeScript#22317] opened 2018-03-04 16:41 UTC
**TypeScript Version:**  2.8.0-dev.20180302

**Search Terms:** `Type cannot be used to index intersection` `Type cannot be used to index`

**Code**

```ts
interface I {a: 1}
function foo<T extends string>(o: I & Record<T, number>, k: T) {
    o[k] // Type 'T' cannot be used to index type 'I & Record<T, number>'.
}
// the following work:
function foo2<T extends string>(o: Record<T, number>, k: T) {
    o[k]
}
// same result, but T different:
function bar<T extends Record<string, number>>(o: I & T, k: keyof T) {
    o[k]
}
```

**Expected behavior:**
No errors.
**Actual behavior:**
Error.

**Playground Link:**  [playground](https://www.typescriptlang.org/play/#src=interface%20I%20%7Ba%3A%201%7D%0D%0Afunction%20foo%3CT%20extends%20string%3E(o%3A%20I%20%26%20Record%3CT%2C%20number%3E%2C%20k%3A%20T)%20%7B%0D%0A%20%20%20%20o%5Bk%5D%20%2F%2F%20Type%20'T'%20cannot%20be%20used%20to%20index%20type%20'I%20%26%20Record%3CT%2C%20number%3E'.%0D%0A%7D%0D%0Afunction%20foo2%3CT%20extends%20string%3E(o%3A%20Record%3CT%2C%20number%3E%2C%20k%3A%20T)%20%7B%0D%0A%20%20%20%20o%5Bk%5D%0D%0A%7D%0D%0Afunction%20bar%3CT%20extends%20Record%3Cstring%2C%20number%3E%3E(o%3A%20I%20%26%20T%2C%20k%3A%20keyof%20T)%20%7B%0D%0A%20%20%20%20o%5Bk%5D%0D%0A%7D%0D%0A%0D%0A) 

**Related Issues:**
There's https://github.com/Microsoft/TypeScript/issues/18538, but that seems to be an issue with `keyof`, which isn't an used here.

**Comment by ahejlsberg** [comment] 2018-03-04 17:17
Duplicate of #22286. Already fixed in currently nightly build.

**Closed** 2018-03-22 15:41 UTC
Labels: Duplicate
