### ISSUE TITLE
export a class with new (ts-5.0) decorator cause error when creating an instance at the same file.

### ISSUE THREAD

**Issue by wenxiao** [microsoft/TypeScript#54194] opened 2023-05-09 09:09 UTC
# Bug Report

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because it use the new decorator feature.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=7&module=1#code/LAKApgHgDg9gTgFwAQDMCuA7AxggljDJAFTAGcEARMLeAQwXgAoFa4BzMBALiUYDoBrNqR60MATwDaAXQCUSALwA+JGPEAaJDQwJI3VRPkBvAL6hQWADa1SpJAFkypWhwASYgCaWwcJEdBIgUgAAiTkVDRw9PABQbrkjLQ85HC4GGyaAEbJCKnpxrFBQdqkMN58ljBsjADkALa0uJaZMBBI8Qg1mjW0XardmX2ZsgDchUhmIJOQsIhaBORIdYpIGGAA7g5OLmDuGF4+jKMWC2VgFVW1AOrwANY1subg0PDIVjZ2jrY7ewdwAEx+cahMiUah0BhwcYdRI5PIZJDZJApNJsAogIpFEpnC7VeqNZqtdqgvo9Pq0AZDY4YoKTaYvOYlZB1QEKVYbLbfNyebwAo5jEDY8o+OBMGoAYTEGBgyDgYFoWAAFkhFT4wA8gA)

### 💻 Code

this works fine:
```ts
export function TestDecorator(target: (...args: any[]) => any, context: any) {}
class MessageHandler {
    @TestDecorator
    test(a: string, b: string) {
        console.log('mailbox test', 'a', a, 'b', b);
    }
}
export const m = new MessageHandler();
```

Adding a "export" before class MessageHandler will cause error: 
```ts
export function TestDecorator(target: (...args: any[]) => any, context: any) {}
export class MessageHandler{
    @TestDecorator
    test(a: string, b: string) {
        console.log('mailbox test', 'a', a, 'b', b);
    }
}
export const m2 = new MessageHandler();
```

### 🙁 Actual behavior

An error occur: "MessageHandler is not defined"

### 🙂 Expected behavior

No error should occur.

### More detail:
If we choose not to use the decorator or not to export, it works fine.

The error is because Typescript translate the code into:

```js
......

exports.MessageHandler = (() => {
    var _a;
    let _instanceExtraInitializers_1 = [];
    let _test_decorators;
    return _a = class MessageHandler2 {
            test(a, b) {
                console.log('mailbox test', 'a', a, 'b', b);
            }
            constructor() {
                __runInitializers(this, _instanceExtraInitializers_1);
            }
        },
        (() => {
            _test_decorators = [TestDecorator];
            __esDecorate(_a, null, _test_decorators, { kind: "method", name: "test", static: false, private: false, access: { has: obj => "test" in obj, get: obj => obj.test } }, null, _instanceExtraInitializers_1);
        })(),
        _a;
})();
exports.m2 = new MessageHandler();
```

At code `exports.m2 = new MessageHandler();`, `MessageHandler` is `undefined`. It should be `new exports.MessageHandler()`, or the class defined as `MessageHandler` and then assign to `exports.MessageHandler`

**Comment by IllusionMH** [comment] 2023-05-09 15:52
Looks like duplicate of #53332

**Closed** 2023-05-11 18:00 UTC
Labels: Duplicate
