### ISSUE TITLE
[javascript] No intellisense for javascript objects created with new?

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#9519] opened 2016-07-05 13:15 UTC
_From @raghur on July 4, 2016 16:31_

- VSCode Version:1.2.1
- OS Version:Windows 8.1 x64

Steps to Reproduce:

1. I have a nodejs library generated with AutoRest which also generates `d.ts` files.
2. It's `package.json` has `"typings": "path to d.ts file"` generated by autorest.
3. In a project where I have the npm package above referenced, there is intellisense only for the main class constructor. Once an instance is created, intellisense doesn't work on the created object to suggest completions.

gif below to explain

![animation](https://cloud.githubusercontent.com/assets/516267/16566468/5e7c3f8e-4232-11e6-9de8-7368b237bd4c.gif)

_Copied from original issue: Microsoft/vscode#8738_

**Comment by mhegazy** [comment] 2016-07-05 19:53
@raghur the information provided is not enough to understand what is going on. please share more context. ideally a repro project that we can use to identify the problem.

**Comment by raghur** [comment] 2016-07-06 00:58
The issue is that I see vs code reading in type definitions for the api object. Hovering over it shows class and parameter into. However over an instance is newed, there is no intellisence available on the object (methods or properties).

I will try to get an example using open source code

**Comment by mhegazy** [comment] 2016-09-21 04:43
Without information about the declaration this issue is unactionable. closing for now. please reopen if you have more information.

**Closed by mhegazy** 2016-09-21 04:43 UTC
Labels: Needs More Info

**Comment by raghur** [comment] 2016-09-22 04:01
[vscode-bug-9519.zip](https://github.com/Microsoft/TypeScript/files/486473/vscode-bug-9519.zip)

Ok - here's a sample project illustrating the issue. It's generated from swagger pet store spec json here - https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/json/petstore.json

Here's a gif as well showing
>The issue is that I see vs code reading in type definitions for the api object. Hovering over it shows class and parameter into. However over an instance is newed, there is no intellisence available on the object (methods or properties).

![vscode-bugreport-9519](https://cloud.githubusercontent.com/assets/516267/18736700/44a1fd52-80a7-11e6-84c5-5e5b154f881c.gif)

**Comment by mhegazy** [comment] 2016-09-22 04:20
I see. the issue here is that `petstore` definition has "required" arguments, and the type system can not figure out a call signature that matches the target.. here is a simpler repro:

```ts
function foo(a, b) { return "";}
foo(). // expect length, actual non.
```

**Comment by mhegazy** [comment] 2016-09-22 04:23
I should add, in a js file, we should allow omitting arguments in a call site.
