### ISSUE TITLE
Partial does not solve React.setState

### ISSUE THREAD

**Issue by AlexGalays** [Microsoft/TypeScript#12793] opened 2016-12-09 12:00 UTC
Traditionally in TS, the absence of value or an explicit undefined value was exactly the same thing.
Perhaps it still even makes sense for Partial, but I thought Partial was meant to solve the React setState problem; and I believe it's still not solved today.

**TypeScript Version:**  2.1.4

**Code**

```ts
type State = { veryImportant: number }

// This compiles fine with all the mandatory flags (strictNullChecks, etc)
// if setState uses Partial<State>
// This is a huge invariant violation and can happen very easily for instance
// by setting `veryImportant` to a nullable variable.
this.setState({ veryImportant: undefined })
```

**Expected behavior:**
A non nullable property should not be updatable with null/undefined with strictNullChecks.

We need to be able to say "give me an object that
1) Either do not declare a property I have
2) Or if it does, must have the same exact type (not nullable)

By the way, I don't even use React, but this is a fairly common and useful behavior to have.

**Comment by ahejlsberg** [comment] 2016-12-09 16:24
I believe this is what you're looking for:

```ts
function setState<T, K extends keyof T>(obj: T, state: Pick<T, K>) {
    for (let k in state) {
        obj[k] = state[k];
    }
}

interface Foo {
    a: string;
    b: number;
}

let foo: Foo = { a: "hello", b: 42 };
setState(foo, { a: "test", b: 43 })
setState(foo, { a: "hi" });
setState(foo, { b: 27 });
setState(foo, { });
setState(foo, { a: undefined });  // Error
setState(foo, { c: true });  // Error
```

**Comment by AlexGalays** [comment] 2016-12-09 16:32
Looks good! Thanks.

**Comment by ericanderson** [comment] 2016-12-09 17:33
@ahejlsberg Thanks for the post. However, the following situation then creates an issue:

```ts
interface FooState {
  bar: string;
  foo?: string;
}

const defaultFooState: FooState = {
  bar: "Hi",
  foo: undefined,
};

class Foo extends React.Component<{}, FooState> {
  public doStuff() {
    this.setState(defaultFooState);
  }
}
```

And updating setState as follows:
```ts
        setState<K extends keyof S>(f: (prevState: S, props: P) => Pick<S, K>, callback?: () => any): void;
        setState<K extends keyof S>(state: Pick<S, K>, callback?: () => any): void;
```

You get the error:
```
severity: 'Error'
message: 'Argument of type 'FooState' is not assignable to parameter of type 'Pick<FooState, "bar" | "foo">'.
  Property 'foo' is optional in type 'FooState' but required in type 'Pick<FooState, "bar" | "foo">'.'
at: '37,19'
source: 'ts'
```

Updating the state to explicitly allow the optional to be undefined also produces the same error.
```
interface FooState {
  bar: string;
  foo?: string | undefined;
}
```

**Comment by RyanCavanaugh** [comment] 2016-12-09 18:02
@ericanderson question: in your opinion, should `setState({ foo: undefined })` be an error, or not?

**Comment by ericanderson** [comment] 2016-12-09 18:07
Ive been kicking it around in my head. If foo is allowed to be undefined (either because its optional or explicitly allowed), then that should not be an error for setState(), ignoring how TS is implemented.

If you implement setState with Partial, it works as intended for this case but breaks because it allows you to set undefined where its not allowed.

**Comment by masonk** [comment] 2016-12-09 18:41
interface TState = {  foo?: string; }
let state = { foo: "initial" };

Now I want state to become `{ foo: undefined }`, how am I to do that if I can't call `setState({ foo: undefined })`?

I prefer the Partial to the Pick in this case. Partial allows some invalid behavior, but Pick prohibits some valid expressions.

If indexed types had the concept of optionality, then `keyof FooState` would return `"foo?" | "bar"`, and Pick would become a perfect expression of the actual type of `setState`.

(Then I think for full completeness, if indexed types gain the concept of optionality they should also gain the concept of requiredness, so that we could undo optionality.

type Required<T> = {
    [K in keyof T]!: T[K]
})

**Comment by ericanderson** [comment] 2016-12-09 18:46
@masonk if you define your state as `type TState = { foo: string | undefined}` you can still use it as you wish with Pick.

But if we use Partial, and you have `type State = { foo: string}`, then it will not be an error to have `setState({foo: undefined})`.

**Comment by ericanderson** [comment] 2016-12-09 18:49
@RyanCavanaugh If there is a bug here, I would suggest that any parameter who is an optional type is also an implicit "T | undefined" so that when you convert it in something like `Pick`, the ability to assign `undefined` does not get lost.

**Comment by masonk** [comment] 2016-12-09 18:49
Sure, but the idiomatic way to say `{ foo: string | undefined }` is `{ foo?: string }`. As I understand the TypeScript, those two declarations ought to behave identically throughout TypeScript.

**Comment by ericanderson** [comment] 2016-12-09 18:50
@masonk Correct. I think we could say that there is currently a bug in TypeScript that the undefined get lost in the case of `Pick`

**Comment by ericanderson** [comment] 2016-12-09 18:53
@masonk Also do note that they arent always assignable.

```ts
type A = { foo?: string };
type B = { foo: string | undefined};

let a: A = { foo: "bar" }
let b: B = { foo: "bar" }

a = b; // okay
b = a; // not okay
```

**Comment by RyanCavanaugh** [comment] 2016-12-09 18:57
I think the problem is that the symmetry between `{ foo: string | undefined }` and `{ foo?: string }` is a lie -- spreading in `{}` to an object has different effects than spreading in `{ foo: undefined }`.

In an ideal world there would be a difference
```ts
interface A {
  foo?: string;
}
interface B {
  foo: string | undefined;
}
interface C {
  foo?: string | undefined;
}
let a: A = { }; // OK
let b: B = { }; // Error, missing 'foo'
let c: C = { }; // OK
a.foo = undefined; // Error, undefined is not string
b.foo = undefined; // OK
c.foo = undefined; // OK

setState(a, { }); // OK
setState(a, { foo: undefined }); // Error
setState(b, { }); // Error, foo missing
setState(b, { foo: undefined}); // OK
setState(c, { }); // OK
setState(c, { foo: undefined}); // OK
```
We've sort of swept this under the rug, but with Object spread and `Object.keys`, there really is a difference between "missing" and "present with value `undefined`". It ought to be possible to express this difference to indicate your intent.

**Comment by ericanderson** [comment] 2016-12-09 19:06
@RyanCavanaugh I agree with you, however the example for `setState(c, { foo: undefined});` was not working for me on my other laptop (while it does work on the playground right now). If I was imaging the issue for `C`, then I agree that everything is working as it should be.

**Comment by AlexGalays** [comment] 2016-12-09 19:07
@ericanderson  I think the playground uses strictNullChecks: false

**Comment by masonk** [comment] 2016-12-09 19:09
Ok, those examples from @ericanderson  and @RyanCavanaugh  are helpful. I now see that there are clear differences between "no key" and "key: undefined".

Damnit, you know what this means?

It means almost all of the interfaces in all of the code I've ever written are maltyped.

Pretty much wherever I have said, `{ foo?: T }`, I meant to say `{ foo?: T | undefined }`.  Because {} is assignable to `{ foo?: T }`, I have to treat `foo` as `T | undefined` at runtime. With strictNullChecks I'm actually required to. Since I'm already doing that, I usually - read almost always - want to allow myself to assign undefined to foo.

I can't think of a single place in my code where I've made an optional property but wish for my compiler to insist that if the property _exists_ then it must not be `undefined`, but allow non-existence. But that's my problem, not TS's problem. TS is just following JS here, and JS clearly makes a distinction.

```t

**Comment by ericanderson** [comment] 2016-12-09 19:23
Okay, I found my repro, it fails with `strictNullChecks` true or false., this feels like it should work @RyanCavanaugh:

```ts
interface C {
  foo?: string | undefined;
}
let c: C = {}; // OK
let c2: C = {
    foo: undefined,
} // OK

function setState<T, K extends keyof T>(obj: T, state: Pick<T, K>) {
    for (let k in state) {
        obj[k] = state[k];
    }
}

setState(c, c2); // !OK =  ERR Argument of type 'C' is not assignable to parameter of type 'Pick<C, "foo">'.
```

**Comment by ericanderson** [comment] 2016-12-09 19:36
Nevermind. I withdraw my complaint. In my above example, there is no way for TS to know that c2.foo, in general, was given a value or was left off. Thus if it promises that it returned a Pick<C, "foo">, then foo MUST be defined, which we can't guarantee. While this isn't my ideal, it seems to be correct, and to go back to the source of this (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13155), `Pick` is the right choice and the side effect of State objects having no optionals is the most rational thing.

Thanks again @ahejlsberg & @RyanCavanaugh

**Comment by masonk** [comment] 2016-12-09 19:41
I'm confused again. How could that possibly be right?

It shouldn't matter to TS whether "c2.foo, in general, was given a value or was left off", because we've said that both are allowed.  C is a supertype of Pick<C>. Anything of type C should be assignable to something of type Pick<C>.

**Comment by ericanderson** [comment] 2016-12-09 19:44
C cannot be assigned to Pick<C, "foo"> because later when you use the Pick version it MUST have a param of foo that is on the object. C isn't guaranteed to have that

**Comment by masonk** [comment] 2016-12-09 19:45
Yes, but how could that possibly be the correct behavior?

`keyof C` isn't `"foo"`, it's `"foo"?`, only the type system doesn't know about that yet.

**Comment by AlexGalays** [comment] 2016-12-09 19:57
Yeah, that can't be right. You need to be able to reset some state, for instance the id of a timeout when it's over/cancelled should be put back to undefined.

Since a React State is encapsulated, it's not overly helpful to make some of its keys optional, but just removing the `?` still doesn't make your example compile.

```ts
  interface C {
    foo: string | undefined;
  }
  let c: C = {}; // OK
  let c2: C = {
      foo: undefined,
  } // OK

  function setState<T, K extends keyof T>(obj: T, state: Pick<T, K>) {
      for (let k in state) {
          obj[k] = state[k];
      }
  }

  setState(c, c2);
// error TS2322: Type '{}' is not assignable to type 'C'.
 // Property 'foo' is missing in type '{}'.
```

**Comment by masonk** [comment] 2016-12-09 20:00
@AlexGalays 

```typescript
  let c: C = {}; // OK
```

Does that actually work? @RyanCavanaugh's example above that didn't work.

**Comment by RyanCavanaugh** [comment] 2016-12-09 20:02
Just to be clear, my comment above was *normative* not *descriptive*. Today we considered `{ x?: number }` to be the same as `{ x: number | undefined }` for the purposes of reading `x`. But we are thinking of changing this to more explicitly model "present but undefined" and "missing"

**Comment by ericanderson** [comment] 2016-12-09 20:03
If we are considering {x?: number} to be the same as {x: number | undefined} currently, then currently there is a bug, given the example I pasted above, no?

**Comment by AlexGalays** [comment] 2016-12-09 20:05
@masonk  Hugh, you're right, the error is at this line rather than the last.

**Comment by masonk** [comment] 2016-12-09 20:25
In the playground right now, here is what actually happens. Unexpected* things happens when I pick optional keys.

```typescript
interface A {
    foo?: string;
}
interface B {
    foo: string | undefined;
}
interface C {
    foo?: string | undefined;
}

let a: A = {};
let a2: A = { foo: "ok" }
let a3: A = { foo: undefined };

let b: B = { }; // (As expected) Error: Property "foo" is missing
let b2: B = { foo: "ok" };
let b3: B = { foo: undefined };

let c: C = {}; 
let c2: C = { foo: "ok" }
let c3: C = { foo: undefined }

function setState<T, K extends keyof T>(obj: T, state: Pick<T, K>) {
    for (let k in state) {
        obj[k] = state[k];
    }
}
setState(a, {}); // Ok (As expected)
setState(a, a2); // (Unexpected) Error: foo is optional in type 'A' but required in type Pick<A, "foo">
setState(a, a3); // (Unexpected) Error: Argument of type 'A' is not assignable to parameter of type Pick<A, "foo">

setState(b, {}); // Ok (As expected; I have picked 0 keys from B)
setState(b, b2); // Ok (As expected)
setState(b, b3); // Ok (As expected) 

setState(c, {}); // Ok
setState(c, c2); // (Unexpected) Error: foo is optional in type 'C' but required in type Pick<C, "foo">
setState(c, c3); // (Unexpected) Error: Argument of type 'C' is not assignable to parameter of type Pick<C, "foo">
```


* To me.

**Comment by ahejlsberg** [comment] 2016-12-10 00:11
We've been discussing this and have come to the consensus that `Pick<T, K>` should copy the modifiers from `T` which it currently doesn't do. More specifically, for a mapped type `{ [P in keyof T]: X }` we currently copy the modifiers from `T`, and we want to do the same for a mapped type `{ [P in K]: X }` where `K` is a type parameter with the constraint `K extends keyof T`.

**Comment by ericanderson** [comment] 2016-12-10 00:16
Thanks @ahejlsbeeg

Will this be in 2.2 or the next 2.1

**Comment by masonk** [comment] 2016-12-10 00:57
You guys are the best. Thank you. (By the way, mapped types are an amazing feature; I love them. In fact, 2.1 is an amazing release over all and ya'll are killing it over there).

**Closed** 2016-12-10 23:16 UTC
Labels: Bug, Fixed

**Comment by aluanhaddad** [comment] 2016-12-11 00:08
I just want to remark that the rapidity of this feedback loop is awesome! An issue comes up, is discussed and gets resolved in less than 2 days, and this is a programming language we are talking about. Great work!

**Comment by aleksey-bykov** [comment] 2016-12-12 12:55
sure thing mapped types got some love, let's not skip the legs day tho

**Comment by kimamula** [comment] 2016-12-29 09:29
I found another problem with using `Pick` for typing `setState`, which happens when updating state conditionally.

```ts
declare class Component<P, S> {
    setState<K extends keyof S>(f: (prevState: S, props: P) => Pick<S, K>, callback?: () => any): void;
}

declare const component: Component<{}, { foo: number; bar: string; }>;
component.setState(() => 0 === 0 ? { foo: 0 } : { bar: '' });
```

The last line raise an error, which says

```
error TS2345: Argument of type '() => { foo: number; } | { bar: string; }' is not assignable to parameter of type '(prevState: { foo: number; bar: string; }, props: {}) => Pick<{ foo: number; bar: string; }, "foo...'.
  Type '{ foo: number; } | { bar: string; }' is not assignable to type 'Pick<{ foo: number; bar: string; }, "foo" | "bar">'.
    Type '{ foo: number; }' is not assignable to type 'Pick<{ foo: number; bar: string; }, "foo" | "bar">'.
      Property 'bar' is missing in type '{ foo: number; }'.
```

**Comment by kimamula** [comment] 2016-12-29 12:01
Is it possible to make `Pick<T, K1>` assignable to `Pick<T, K2>` if `K1` is assignable to `K2` to resolve the above problem?

**Comment by AlexGalays** [comment] 2016-12-29 12:25
Yeah, typescript has a lot of issues inferring from function returns. I don't think it's an issue with Pick especially.
It infers that your Pick must have the full set of keys.

**Comment by ericanderson** [comment] 2016-12-29 12:36
The compiler should probably infer the return value to be 'Pick<T, "foo"> | Pick<T, "bar">' instead. Then it could infer that both of those are assignable to 'Pick<T, K>' I believe.

**Comment by kimamula** [comment] 2016-12-29 13:18
@ericanderson 
Ah, yes, you are right.

I was misunderstanding `Pick` and this comment is incorrect.
> I think if K1 is assignable to K2, then Pick<T, K1> should be assignable to Pick<T, K2>.

**Comment by kimamula** [comment] 2017-01-04 12:56
Well, certainly the issue I described is not specific to `Pick`.

```ts
function f(s: string): void;
function f(n: number): void;
function f(args: string | number): void {}

f(''); // no error
f(0); // no error
f(0 === 0 ? '' : 0); // error: Argument of type '"" | 0' is not assignable to parameter of type 'number'. Type '""' is not assignable to type 'number'.
```

It is likely that although you can define an argument of a function as one of multiple types, it must have a single type per use.

**Comment by lukecwilliams** [comment] 2017-10-18 19:20
I don't totally understand the @ahejlsberg [solution](https://github.com/Microsoft/TypeScript/issues/12793#issuecomment-266055843) - we're supposed to redefine setState on every component to get TS to settle down about setState with a partial object?

**Comment by grantila** [comment] 2017-12-14 14:41
I agree with @lukecwilliams's not getting how this is solved, especially given the *title* of this issue. **`Partial` still won't work with `setState`**, since `setState` uses `Pick`. Please reopen @ahejlsberg or describe how `Partial< T >` is compatible with `Pick< T, ... >`, or conclude that `setState` should have another signature. Anything but leaving it closed when it's still an issue.

The following **does not** work, and is a not-so-uncommon way to partially build up a state somewhere, to then apply it with `setState`. Please consider `foo` to be a lot more complex and not as trivial as this example, where alternative logic would obviously suffice.

```ts
interface State
{
	a: string;
	b: number;
}

class Comp extends React.Component< { }, State >
{
	foo( )
	{
		const state: Partial< State > = { };
		if ( !0 ) // obviously apply some useful logic here
			state.a = "foo";
		this.setState( state );
	}
}
```

It fails with:
```
TS2345: Argument of type 'Partial<State>' is not assignable to parameter of type 'Pick<State, "a" | "b">'.
  Property 'a' is optional in type 'Partial<State>' but required in type 'Pick<State, "a" | "b">'.
```

Yes, one can Hawaii-cast things to make `tsc` happy, à la:

```ts
this.setState( state as State );
```

or, pick your poison:

```ts
const state = { } as State;
```

but this is not a solution. Or is it? I'm personally resentful to blatantly lie about types this way. It's a bad habit.

**Comment by coding2012** [comment] 2017-12-27 16:04
I have another example of some strangeness around the Pick infrastructure as used in React types specifically. Unfortunately I don't fully understand it but this is something I ran into:

typescript version is 2.6.2 and using "@types/react": "^16.0.31"

```javascript
export type ExportProperties = {
    hpid: boolean,
    gender: boolean,
    age: boolean,
    diagnosisCode: boolean,
    medicationCode: boolean,
    procedureCode: boolean
};

export class StudyExportComponent extends React.Component<{ study: Study }, ExportProperties> {

    constructor(props: { study: Study }) {
        super(props);
        this.state = {
            hpid: true,
            gender: false,
            age: false,
            diagnosisCode: false,
            medicationCode: false,
            procedureCode: false
        };
        this.handleCheck = this.handleCheck.bind(this);
        this.handleCheck2 = this.handleCheck2.bind(this);
        this.handleCheck3 = this.handleCheck3.bind(this);
    }

    handleCheck(name: keyof ExportProperties) {
        return (event: any) => {
            let state = {};
            state[name] = event.target.checked;
            this.setState(state);
        };
    }
    handleCheck2(name: 'hpid' | 'gender' | 'age' | 'diagnosisCode' | 'medicationCode' | 'procedureCode') {
        return (event: any) => {
            let boolValue: boolean = event.target.checked;
            this.setState({ [name]: boolValue });
        };
    }
    handleCheck3(name: keyof ExportProperties) {
        return (event: any) => {
            let boolValue: boolean = event.target.checked;
            this.setState({ [name]: boolValue });
        };
    }
// Clipped rendering stuff
```
With the following errors:
This first one is for handleCheck2
```
src/components/study/study-export.tsx(41,27): error TS2345: Argument of type '{ [x: string]: boolean; }' is not assignable to parameter of type 'ExportProperties | ((prevState: Readonly<ExportProperties>, props: { study: Study; }) => ExportPr...'.
  Type '{ [x: string]: boolean; }' is not assignable to type 'Pick<ExportProperties, "hpid" | "gender" | "age" | "diagnosisCode" | "medicationCode" | "procedur...'.
    Property 'hpid' is missing in type '{ [x: string]: boolean; }'.

41             this.setState({ [name]: boolValue });
                             ~~~~~~~~~~~~~~~~~~~~~
```
And this one for handleCheck3:
```
src/components/study/study-export.tsx(47,27): error TS2345: Argument of type '{ [x: string]: boolean; }' is not assignable to parameter of type 'ExportProperties | ((prevState: Readonly<ExportProperties>, props: { study: Study; }) => ExportPr...'.
  Type '{ [x: string]: boolean; }' is not assignable to type 'Pick<ExportProperties, "hpid" | "gender" | "age" | "diagnosisCode" | "medicationCode" | "procedur...'.
    Property 'hpid' is missing in type '{ [x: string]: boolean; }'.

47             this.setState({ [name]: boolValue });
                             ~~~~~~~~~~~~~~~~~~~~~
```
My work-around is clearly in handleCheck which does not have any TS errors but as you can see is clearly working around types in this case (at least I think it is).

I also just noticed that this compiles just fine:
```javascript
this.setState({ [name]: boolValue } as Pick<ExportProperties, keyof ExportProperties>);
```

Now that I look at this a little more maybe that's the appropriate thing to do...

Now just to be clear none of this is failing the most common use-case as shown below:

```javascript
this.setState({ hpid: true });
```

Hopefully this post is helpful to others even if not actionable to the Typescript language.

**Comment by ericanderson** [comment] 2017-12-27 16:09
I think you're types could be improved. Specifically to prevent the problem, change the type of `name` in your functions to `keyof ExportProperties`. I bet that solves your problem (and also means you dont have to update that function everytime you add something to `ExportProperties`).

Unrelated but tip, if you use => notation for your methods, you dont have to manually bind them, they are bound for you.
