### ISSUE TITLE
Required<T> optional properties type validation will not work

### ISSUE THREAD

**Issue by misuken-now** [Microsoft/TypeScript#29991] opened 2019-02-20 10:16 UTC
**TypeScript Version:**  3.2.0-rc <= 3.4.0-dev.20190220

**Search Terms:** Required

**Code**

```ts
const a: Required<{ a?: 1; x: 1 }> = { a: 1, x: 1 };
const b: Required<{ b?: 1; x: 1 }> = { b: 1, x: 1 };
export let A = a;
export let B = b;
A = b; // No Error
B = a; // No Error

a.b; // Property 'b' does not exist on type 'Required<{ a?: 1; x: 1; }>'.
b.a; // Property 'a' does not exist on type 'Required<{ b?: 1; x: 1; }>'.
```

**Expected behavior:**

```
Error:(5, 1) TS2322: Type 'Required<{ b?: 1 | undefined; x: 1; }>' is not assignable to type 'Required<{ a?: 1 | undefined; x: 1; }>'.
  Property 'a' is missing in type 'Required<{ b?: 1 | undefined; x: 1; }>'.
Error:(6, 1) TS2322: Type 'Required<{ a?: 1 | undefined; x: 1; }>' is not assignable to type 'Required<{ b?: 1 | undefined; x: 1; }>'.
  Property 'b' is missing in type 'Required<{ a?: 1 | undefined; x: 1; }>'.
```

When it is "3.1.6" it will be like that.

**Actual behavior:**

No Error

**Playground Link:** 

[link](https://www.typescriptlang.org/play/index.html#src=const%20a%3A%20Required%3C%7B%20a%3F%3A%201%3B%20x%3A%201%20%7D%3E%20%3D%20%7B%20a%3A%201%2C%20x%3A%201%20%7D%3B%0Aconst%20b%3A%20Required%3C%7B%20b%3F%3A%201%3B%20x%3A%201%20%7D%3E%20%3D%20%7B%20b%3A%201%2C%20x%3A%201%20%7D%3B%0Aexport%20let%20A%20%3D%20a%3B%0Aexport%20let%20B%20%3D%20b%3B%0AA%20%3D%20b%3B%20%2F%2F%20No%20Error%0AB%20%3D%20a%3B%20%2F%2F%20No%20Error%0A%0Aa.b%3B%20%2F%2F%20Property%20'b'%20does%20not%20exist%20on%20type%20'Required%3C%7B%20a%3F%3A%201%3B%20x%3A%201%3B%20%7D%3E'.%0Ab.a%3B%20%2F%2F%20Property%20'a'%20does%20not%20exist%20on%20type%20'Required%3C%7B%20b%3F%3A%201%3B%20x%3A%201%3B%20%7D%3E'.)

**Related Issues:**

**Comment by jack-williams** [comment] 2019-02-20 13:02
This looks to be related to variance markers used for generic mapped types---a very similar problem to #29698. When relating `a` and `b`, I believe it is just relating the type arguments in a covariant way, which holds for assigning `{ a?: 1; x: 1 }` to and from `{ b?: 1; x: 1 }`. The variance markers do not reflect how the keys of the type arguments are used.

You can see behaviour by replacing `Required` with a structurally equivalent, but different alias. Variance markers are not used in this instance, and type checking falls back to structural checking. The error correctly gets flagged in this case.
```ts
type Required2<T> = { [P in keyof T]-?: T[P]; };
const a: Required<{ a?: 1; x: 1 }> = { a: 1, x: 1 };
const b: Required2<{ b?: 1; x: 1 }> = { b: 1, x: 1 };
export let A = a;
export let B = b;
A = b; //  Error!
B = a; //  Error!
```

I've been wrong on this before though. You'll most likely need @ahejlsberg or @weswigham to give a definitive answer.

**Comment by misuken-now** [comment] 2019-02-21 05:29
Thanks for looking into this @jack-williams.

It was a difficult problem to understand for me.
I was saved because it provided information.

Once it is written as follows, it will be as intended, so it seems to be temporarily resolved.

```ts
type Required2<T> = Required<{ [P in keyof T]-?: T[P]; }>;

const a: Required2<{ a?: 1; x: 1 }> = { a: 1, x: 1 };
const b: Required2<{ b?: 1; x: 1 }> = { b: 1, x: 1 };
export let A = a;
export let B = b;
A = b; // Property 'a' is missing in type 'Required<{ b: 1; x: 1; }>' but required in type 'Required<{ a: 1; x: 1; }>'.
B = a; // Property 'b' is missing in type 'Required<{ a: 1; x: 1; }>' but required in type 'Required<{ b: 1; x: 1; }>'.

a.b; // Property 'b' does not exist on type 'Required<{ a?: 1; x: 1; }>'.
b.a; // Property 'a' does not exist on type 'Required<{ b?: 1; x: 1; }>'.
```

**Comment by weswigham** [comment] 2019-03-06 17:48
This is fixed in `master`.

**Comment by jack-williams** [comment] 2019-03-06 19:08
@weswigham I can't seem to reproduce: 5bd73f55320c43c362ef99d3ee183e428e2b974f. It should error on the first two assignments, right?


(P.S. excuse my spelling)

**Comment by weswigham** [comment] 2019-03-06 19:11
Your baselines are right - getting an error on those two accesses is intended, since the `Required` type is meant to strip them out, and the assignments should all be allowed, since they both evaluate to `{x: number}`.

**Comment by jack-williams** [comment] 2019-03-06 19:20
Is `Required` not meant to remove `?` modifiers, rather than strip out optional properties?

**Comment by weswigham** [comment] 2019-03-07 01:16
Ah, derp, you're right - I was confusing it with a `RequiredKeys` function I'd been looking at.hmmm yeah, those assignments shouldn't work. Hmm.

**Closed** 2019-05-03 21:42 UTC
Labels: Bug
