### ISSUE TITLE
Compiler error with redeclared exported variable 'default'

### ISSUE THREAD

**Issue by GiedriusGrabauskas** [Microsoft/TypeScript#11213] opened 2016-09-28 17:09 UTC
**TypeScript Version:**  2.0.3

When try to redeclare exported variable `default` with function call, typescript compiler throw a error.

**Code**

```ts
import * as React from 'react';
import * as ReactRouter from 'react-router';

export default class TestComponent extends React.Component<{}, {}> {
    render() {
        return <div>Test component</div>;
    }
}

export default ReactRouter.withRouter(TestComponent);
```

**Error**
```cmd
> tsc -p . --noEmit

D:\test\ts-error3\node_modules\typescript\lib\tsc.js:37701
                throw e;
                ^

TypeError: Cannot read property 'kind' of undefined
    at getTypeForVariableLikeDeclaration (D:\test\ts-error3\node_modules\typescript\lib\tsc.js:15537:42)
    at getWidenedTypeForVariableLikeDeclaration (D:\test\ts-error3\node_modules\typescript\lib\tsc.js:15642:24)
    at getTypeOfVariableOrParameterOrProperty (D:\test\ts-error3\node_modules\typescript\lib\tsc.js:15699:28)
    at getTypeOfSymbol (D:\test\ts-error3\node_modules\typescript\lib\tsc.js:15826:24)
    at checkClassLikeDeclaration (D:\test\ts-error3\node_modules\typescript\lib\tsc.js:25705:30)
    at checkClassDeclaration (D:\test\ts-error3\node_modules\typescript\lib\tsc.js:25687:13)
    at checkSourceElement (D:\test\ts-error3\node_modules\typescript\lib\tsc.js:26626:28)
    at Object.forEach (D:\test\ts-error3\node_modules\typescript\lib\tsc.js:185:30)
    at checkSourceFileWorker (D:\test\ts-error3\node_modules\typescript\lib\tsc.js:26694:20)
    at checkSourceFile (D:\test\ts-error3\node_modules\typescript\lib\tsc.js:26680:13)
```

**Sample**
[ts-error.zip](https://github.com/Microsoft/TypeScript/files/498808/ts-error.zip)

**Sample usage**
```cmd
npm install && npm test
```

**Expected behavior:**
Typescript error:
`Cannot redeclare exported variable 'default'.`

**Comment by mhegazy** [comment] 2016-09-29 05:41
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/10193

**Closed by mhegazy** 2016-09-29 05:41 UTC
Labels: Bug
