### ISSUE TITLE
Type narrowing does not work if you use bracket notation with a variable

### ISSUE THREAD

**Issue by katz12** [microsoft/TypeScript#39936] opened 2020-08-06 15:40 UTC
**TypeScript Version:**  3.9.2

**Search Terms:**
type 
narrow 
variable 
constant
bracket

I don't run into this often, but sometimes I have an object key that is worth extracting to a constant for ease of use. I found that doing this caused me to lose some type narrowing power.

**Code**

```ts
const PROP = 'some.prop-name:with_chars(that)need;to&be!escaped`with~quotes'

interface Bar {
    [PROP]?: [string]
}

const bar: Bar = {}

if (bar['some.prop-name:with_chars(that)need;to&be!escaped`with~quotes']) {
    const [test1] = bar['some.prop-name:with_chars(that)need;to&be!escaped`with~quotes']
}

if (bar[PROP]) {
    const [test2] = bar[PROP]
//        ^^^^^^ Type '[string] | undefined' must have a '[Symbol.iterator]()' method that returns an iterator.(2488)
}

if (bar['some.prop-name:with_chars(that)need;to&be!escaped`with~quotes']) {
    const [test3] = bar[PROP]
}
```

**Expected behavior:**
In each of the conditionals above the type of the property should be narrowed to exclude `undefined`.

**Actual behavior:**
It only narrows when you name the property with a string literal instead of a constant.

**Playground Link:** [link](https://www.typescriptlang.org/play?ts=3.9.2#code/MYewdgzgLgBACgJQPJxgXhgcgiAtgUwDoAHAJxGIFowBDAgLgHcBLKACwH1g2bSIAKdjSgBKMPnwATANxQQAMgBG+AIT4IwGsSkADFuwB+ARwCuIKOswAoK8zAXSAMxrB8MAEK8YAbysx-MADaiCgAugD89EHQpHYA5qFWAL42oJCwirxRnqToPim2jjD8maSB2HhEZBTUdPhMrJzcvAJCouJSsgrKahpauvpsxmYWEJihIj5+AWnQQaNQAIyheaXlOAQk5FS0DINcPHyCPO0SMnJKquqa2pJ6jcPmlokFzEUlvMHIcBNTATCzWCBBYAJhWGDWIR+yRsb2Kawqm2qOzqDXYBxax2EYjOXUuvRuAwepieY1+vn+gPm6igAGZwTBId8XkA)

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/10530
https://github.com/microsoft/TypeScript/issues/36463 (maybe?)
https://github.com/microsoft/TypeScript/issues/36230 (maybe?)

**Comment by MartinJohns** [comment] 2020-08-06 16:38
Duplicate of #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.

**Comment by katz12** [comment] 2020-08-06 16:44
Thanks @MartinJohns.

This comment specifically seems to point to my issue: https://github.com/microsoft/TypeScript/issues/10530#issuecomment-603915317

**Closed** 2020-09-05 18:00 UTC
Labels: Duplicate
