### ISSUE TITLE
Auto formatting is buggy for chained callbacks (promises).

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#2651] opened 2015-04-07 09:37 UTC
I think some times we need to write things like this, but obviously the auto formatting doesn't support this style well enough (actually it destroys manually formatted code):

```typescript
promise
    .then(() => returnAnotherPromise())
    .then(() => {
        // do something...
    })
    .then(() => {
        // do some other thing...
    });
```

Because the style below doesn't seem to be acceptable.

```typescript
promise.then(() => returnAnotherPromise()).then(() => returnAnotherPromise()).then(() => {
    //...
});
```

I find there's quite a lot bugs related to auto formatting, maybe a thorough test procedure should be designed?

**Comment by DanielRosenwasser** [comment] 2015-04-07 15:14
Sounds like this might be a duplicate of #1888. We have a test suite for these sorts of bugs, but usually we find more through exploratory methods anyway. Of course, any bug that comes in has a repro added to the test suite.

**Comment by mhegazy** [comment] 2015-04-07 17:19
@vilic contributing tests are always welcome, so are proposals for better engineering processes.

Formatting tests are all under [fourslash](https://github.com/Microsoft/TypeScript/tree/master/tests/cases/fourslash) directory. And more info can be found in [CONTRIBUTING.md](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#running-the-tests)

**Closed** 2015-04-07 17:27 UTC
Labels: Duplicate
