### ISSUE TITLE
No compatible call signatures, with keyof

### ISSUE THREAD

**Issue by kevupton** [Microsoft/TypeScript#23499] opened 2018-04-18 05:07 UTC
No compatible call signatures, when using a `keyof` defined variable. 

**TypeScript Version:**  2.7.1

**Search Terms:** 
no compatible call signatures 
no compatible call signatues keyof
**Code**

#### This does not work:
```ts
interface ITest {
  Test1?: string | null;
  Test2?: number | null;
  Test3?: object;
}

export type TestMap<T> = {
  [TKey in keyof ITest]: (testValue: ITest[TKey]) => boolean;
};

export type Keys = keyof ITest;

const test: ITest = {};

function testMethod(key: Keys) {
  const testValue = test[key];
  const map: TestMap<string> = {};

  if (map[key](testValue)) { // this throws the error

  }
}
```

#### This works:
```ts
interface ITest {
  Test1?: string | null;
  Test2?: number | null;
  Test3?: object;
}

export type TestMap<T> = {
  [TKey in keyof ITest]: (testValue: ITest[TKey]) => boolean;
};

export type Keys = keyof ITest;

const test: ITest = {};
const key: Keys = 'Test1';
const testValue = test[key];
const map: TestMap<string> = {};

if (map[key](testValue)) {

}
```

**Expected behavior:**
This should compile.

**Actual behavior:**
error
> ERROR in src/app/controls/filter-bar/filter-bar.service.ts(41,7): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type '((testValue: string) => boolean) | ((testValue: number) => boolean) | ((testValue: object) => boo...' has no compatible call signatures.

**Playground Link:**  
[Playground Link](https://www.typescriptlang.org/play/#src=%0D%0Ainterface%20ITest%20%7B%0D%0A%20%20Test1%3F%3A%20string%20%7C%20null%3B%0D%0A%20%20Test2%3F%3A%20number%20%7C%20null%3B%0D%0A%20%20Test3%3F%3A%20object%3B%0D%0A%7D%0D%0A%0D%0Aexport%20type%20TestMap%3CT%3E%20%3D%20%7B%0D%0A%20%20%5BTKey%20in%20keyof%20ITest%5D%3A%20(testValue%3A%20ITest%5BTKey%5D)%20%3D%3E%20boolean%3B%0D%0A%7D%3B%0D%0A%0D%0Aexport%20type%20Keys%20%3D%20keyof%20ITest%3B%0D%0A%0D%0Aconst%20test%3A%20ITest%20%3D%20%7B%7D%3B%0D%0A%0D%0Afunction%20testFailingMethod(key%3A%20Keys)%20%7B%0D%0A%20%20const%20testValue%20%3D%20test%5Bkey%5D%3B%0D%0A%20%20const%20map%3A%20TestMap%3Cstring%3E%20%3D%20%7B%7D%3B%0D%0A%0D%0A%20%20if%20(map%5Bkey%5D(testValue))%20%7B%20%2F%2F%20this%20throws%20the%20error%0D%0A%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20testPassingMethod()%20%7B%0D%0A%20%20const%20key%3A%20Keys%20%3D%20'Test1'%3B%0D%0A%20%20const%20testValue%20%3D%20test%5Bkey%5D%3B%0D%0A%20%20const%20map%3A%20TestMap%3Cstring%3E%20%3D%20%7B%7D%3B%0D%0A%0D%0A%20%20if%20(map%5Bkey%5D(testValue))%20%7B%20%2F%2F%20this%20works%0D%0A%0D%0A%20%20%7D%0D%0A%7D)

**Related Issues:**

**Comment by andy-ms** [comment] 2018-04-18 14:47
Duplicate of  #7294 -- it has a union type, so it can't be called.

**Closed** 2018-05-02 22:53 UTC
Labels: Duplicate
