### ISSUE TITLE
JSON.stringify() type does not include `this` type for replacer function

### ISSUE THREAD

**Issue by Haringat** [Microsoft/TypeScript#28632] opened 2018-11-21 10:40 UTC
The lib.d.ts does not contain a `this` type for the replacer callback, although this is explicitly set by the runtime to the value of holder according to "https://www.ecma-international.org/ecma-262/5.1/#sec-15.12.3". I would suggest an any type for this.

**TypeScript Version:**  3.2.0-dev.20181117

**Search Terms:** JSON serialize replacer this

**Code**

```ts
function serialize(key, value) {
    return value;
}

function test() {
    JSON.stringify({foo: "bar"}, function (key) {
        // !!! this should be legal !!!
        return serialize(key, this[key]);
    });
}
```

**Expected behavior:**
Compilation without error with "noImplicitThis" compilerOption being activated.

**Actual behavior:**
tsc reports an error saying "'this' implicitly has type 'any' because it does not have a type annotation." when noImplicitThis is activated.

**Playground Link:**
https://www.typescriptlang.org/play/index.html#src=function%20serialize(key%2C%20value)%20%7B%0D%0A%20%20%20%20return%20value%3B%0D%0A%7D%0D%0A%0D%0Afunction%20test()%20%7B%0D%0A%20%20%20%20JSON.stringify(%7Bfoo%3A%20%22bar%22%7D%2C%20function%20(key)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20!!!%20this%20should%20be%20legal%20!!!%0D%0A%20%20%20%20%20%20%20%20return%20serialize(key%2C%20this%5Bkey%5D)%3B%0D%0A%20%20%20%20%7D)%3B%0D%0A%7D

**Related Issues:** 
none found

**Comment by ikokostya** [comment] 2018-11-21 20:11
Duplicate of https://github.com/Microsoft/TypeScript/issues/6955
There is pull request https://github.com/Microsoft/TypeScript/pull/28270/files

**Closed** 2018-12-12 10:00 UTC
Labels: Duplicate
