### ISSUE TITLE
Error ts(1345) when using JavaScript logical operator as statement

### ISSUE THREAD

**Issue by JipingWang** [microsoft/TypeScript#31604] opened 2019-05-26 17:19 UTC
**TypeScript Version:**  3.4.5

**Search Terms:** operator

**Code**

```ts
<form className={classes.form} onSubmit={e => e.preventDefault() || false}>
```

**Expected behavior:**
  valid, no error throws.

**Actual behavior:**
Error ts(1345): An expression of type 'void' cannot be tested for truthiness.

**Comment by j-oliveras** [comment] 2019-05-26 17:43
This is working as intended: #26262, PR #26234. Duplicate of #28248.

**Closed** 2019-05-28 04:16 UTC
Labels: Duplicate
