### ISSUE TITLE
Default destructuring object not recognized properly.

### ISSUE THREAD

**Issue by fresheneesz** [microsoft/TypeScript#52049] opened 2022-12-30 03:14 UTC
# Bug Report

### 🔎 Search Terms

destrucruting, object, default, empty

### 🕗 Version & Regression Information

Version 4.9.4

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMAFAbwB6ILyIIwC+AXIpiWCALYBGApgE4E6kECUpAUIt4vbVCHpIMHAkA

### 💻 Code

```ts
function f({x = 1}: {x: number} = {}) {
    return x
}
```

### 🙁 Actual behavior

`Property 'x' is missing in type '{}' but required in type '{ x: number; }'`

This is wrong because calling, for example, `f()` will result in `x` being `1`, even tho the `= {}` default definition is empty (because the destructuring object has a default). 

### 🙂 Expected behavior

I would expect this to pass type linting.

**Comment by fresheneesz** [comment] 2022-12-30 03:15
Note that this is the best DRY way to define this in javascript. If you leave out the `= {}` then `f()` will result in an error (x not defined). If you instead define this as `function f({x} = {x: 1}` then calling `f({})` will result in `x not defined` as well. The above is the shortest way to defined it so that both `f()` and `f({})` can be called without issue.

**Comment by MartinJohns** [comment] 2022-12-30 03:20
Duplicate of #51179.

**Comment by fresheneesz** [comment] 2022-12-30 05:28
Ah I see, the correct way of writing this is:

```
function f({x = 1}: {x:? number} = {}) {
    return x
}
```

I assume this is because the type `{x:? number}` here is defining what argument type can be passed in rather than defining what parameter type is received. This is a rather awkward situation. It seems that typescript *does* recognize the fact that the parameter has a different type than the argument, and properly recognizes that the parameter is not in fact optional.

**Comment by fatcerberus** [comment] 2022-12-30 12:26
Yeah, for destructurings, the type annotation specifies what kind of values can be used to initialize it, not what types the bindings will ultimately have.  It usually happens to be that these are the exact same type, *except* for the case where one or more of the bindings has a default.

The way to think about it is that you’re annotating the imaginary temp variable used to destructure the object.  It’s a bit weird IMO, but that’s how they chose to design it.

**Comment by RyanCavanaugh** [comment] 2023-01-05 21:57
Yeah, among equal desugarings to choose from, TS treats this as
```ts
function f(_obj: {x: number} = {}) { // <- type violation
    let x = _obj.x ?? 1;
    return x;
}
```

**Closed** 2023-01-08 18:00 UTC
Labels: Duplicate
