### ISSUE TITLE
Fail to import `classPrivateFieldGet` from tslib when `"importHelpers": true`

### ISSUE THREAD

**Issue by millsp** [microsoft/TypeScript#36841] opened 2020-02-17 20:52 UTC
I am testing out the lastest ECMA private fields. I get an error when `importHelpers` enabled:
```
This syntax requires an imported helper named '__classPrivateFieldGet' which does not exist in 'tslib'. Consider upgrading your version of 'tslib'.ts(2343)
```

I'm not sure if there's pending work on the tslib, so I'm repoting this anyway.

**TypeScript Version:**  3.8.1-rc
**TS Lib Version:**  1.1.0

**Search Terms:**
tslib classPrivateFieldGet

**Code**

```ts
class A {
    #a: number

    constructor() {
        this.#a = 1
    }
}


```

**Expected behavior:**

This should compile

**Actual behavior:**

Shows an error on tslib

**Playground Link:** 

**Related Issues:**

**Comment by Haringat** [comment] 2020-02-21 12:33
I have a few additional observations:
1. When I only compile one file typescript seems to completely ignore the `importHelpers: true` option and emit all required helpers (including __classPrivateFieldGet and __classPrivateFieldSet) into the js file. When the compiled file references other files via imports the behaviour @pirix-gh described occurres.
2. When `module: "CommonJS"` is set, it imports all helpers just as you would expect. However, when `module: "ESNext"` or "module: "ES2015"` it does not import __classPrivateFieldGet and __classPrivateFieldSet (other helpers like __awaiter are imported though)

**Comment by motss** [comment] 2020-02-25 03:21
I believe that this is a bug as the helpers for setting and getting private fields will be imported only when `module` set to `CommonJS`.

**Comment by duxiaofeng-github** [comment] 2020-03-04 16:37
i have another question, ts transplie #property to weakmap(this) to store the property value.

when the class instance destroyed and recycled by the gc. at that time, the property value of this class instance still store in weakmap.

will it cause a memory leak?

**Comment by duxiaofeng-github** [comment] 2020-03-04 17:19
well, reply to myself, it seems chrome will clean up all values in weakmap after their key have been gc'ed

**Comment by Haringat** [comment] 2020-03-08 13:44
@duxiaofeng-github Not just chome, but v8 in general and all other javascript engines too. It is a part of the specification as you can read here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

**Comment by duxiaofeng-github** [comment] 2020-03-09 11:37
@Haringat thx, i read that doc before, i must miss something...

**Comment by cedx** [comment] 2020-03-23 11:11
Same issue here with `typescript` 3.8.3 and `tslib` 1.11.1.

**Comment by matrunchyk** [comment] 2020-05-23 10:08
Same issue with TS 3.9.3 and tslib 2.0.0

**Comment by thibaut-loftorbital** [comment] 2020-06-16 08:33
With Typescript 3.8.2 and tslib 2.0.0, I have got a runtime Error `ReferenceError: __classPrivateFieldGet is not defined`

**Comment by michaelaflores** [comment] 2020-07-21 14:57
Experiencing this issue with typescript 3.8.3 and tslib 1.11.1, where a runtime error occurs `Can't find variable: __classPrivateFieldSet`. 

Truncated tsconfig.json:
```json
{
  "compilerOptions": {
    "importHelpers": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "CommonJS",
    "resolveJsonModule": true,
    "lib": ["dom", "dom.iterable", "es2015", "es2016", "es2017"],
    "esModuleInterop": true,
    "allowJs": true,
    "strict": true,
    "downlevelIteration": true,
    "plugins": [
      {
        "transform": "typescript-is/lib/transform-inline/transformer",
        "shortCircuit": false,
        "ignoreClasses": true,
        "ignoreMethods": true,
        "ignoreFunctions": true,
        "disallowSuperfluousObjectProperties": false
      }
    ],
    "moduleResolution": "node",
    "isolatedModules": true
  }
}
```

**Comment by rbuckton** [comment] 2020-07-28 23:09
I cannot seem to repro this with typescript@next and tslib@2.0

**Comment by rbuckton** [comment] 2020-07-28 23:11
@Haringat: `--importHelpers` will not be used if the TypeScript thinks the file is a Script rather than a Module. Even with `--module commonjs`, if there are no imports or exports in the file it considers it to be a global script. If you want it to use `tslib`, you need to ensure there is at least one import or export to indicate it is a module, even if that is an empty export (i.e., `export {};`)

**Comment by rbuckton** [comment] 2020-07-28 23:23
I believe the type error in the original description was fixed at some point between when the issue was filed and now. Its possible the runtime issue may have been addressed by another PR in the meantime, as well, as there have been several recent PRs that could affect tslib import. If anyone is still experiencing an issue and can provide a consistent repro using `typescript@beta` and `tslib@2.0` please let me know and I will look into this again.

**Comment by toyobayashi** [comment] 2020-08-05 06:50
@rbuckton 
I experienced the same problem, both `typescript@beta` and `typescript@next`.

Repo: [https://github.com/toyobayashi/import-helpers-private-field-issue](https://github.com/toyobayashi/import-helpers-private-field-issue)

package.json
``` jsonc
{
  // ...
  "scripts": {
    "build": "tsc && tsc -p ./tsconfig.cjs.json"
  },
  "devDependencies": {
    "tslib": "^2.0.0",
    "typescript": "^4.0.0-beta"
  }
}
```

tsconfig.json & tsconfig.cjs.json
``` json
{
  "compilerOptions": {
    "outDir": "out-esm",
    "module": "ESNext",
    "target": "es2015",
    "importHelpers": true,
    "moduleResolution": "node",
  },
  "include": [
    "src/index.ts"
  ]
}
```
``` json
{
  "compilerOptions": {
    "outDir": "out-esm",
    "module": "commonjs",
    "target": "es2015",
    "importHelpers": true,
    "moduleResolution": "node",
  },
  "include": [
    "src/index.ts"
  ]
}
```

src/index.ts
``` ts
class A {}

class B extends A {
  #x: number = 1

  getX (): number {
    return this.#x
  }

  setX (v: number): void {
    this.#x = v
  }

  async asyncMethod (): Promise<number> {
    return 0
  }
}

export { B }
```

out-esm/index.js
``` js
var _x;
import { __awaiter } from "tslib"; // <-- missing __classPrivateFieldGet and __classPrivateFieldSet
class A {
}
class B extends A {
    constructor() {
        super(...arguments);
        _x.set(this, 1);
    }
    getX() {
        return __classPrivateFieldGet(this, _x); // <-- error
    }
    setX(v) {
        __classPrivateFieldSet(this, _x, v); // <-- error
    }
    asyncMethod() {
        return __awaiter(this, void 0, void 0, function* () {
            return 0;
        });
    }
}
_x = new WeakMap();
export { B };
```

But commonjs output correctly:

out-cjs/index.js
``` js
"use strict";
var _x;
Object.defineProperty(exports, "__esModule", { value: true });
exports.B = void 0;
const tslib_1 = require("tslib");
class A {
}
class B extends A {
    constructor() {
        super(...arguments);
        _x.set(this, 1);
    }
    getX() {
        return tslib_1.__classPrivateFieldGet(this, _x); // <-- ok
    }
    setX(v) {
        tslib_1.__classPrivateFieldSet(this, _x, v); // <-- ok
    }
    asyncMethod() {
        return tslib_1.__awaiter(this, void 0, void 0, function* () {
            return 0;
        });
    }
}
exports.B = B;
_x = new WeakMap();
```

**Comment by rbuckton** [comment] 2020-08-06 01:43
I'll take another look, thanks for the repro

**Closed** 2020-08-06 20:27 UTC
Labels: Fix Available, Needs Investigation, Rescheduled

**Comment by svallory** [comment] 2022-10-06 15:30
This is again a bug in `4.8.4`. Easy to reproduce:

```
mkdir test && cd test
npm init
tsc --init
npm i -D typescript
```

**tsconfig.json**
```
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "importHelpers": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": false
  }
}
```

**test.ts**
```
export class Test {
  #pvt: string;

  constructor(pvt: string) {
    this.#pvt = pvt;
  }
}
```

**Comment by boy51** [comment] 2022-10-28 11:04
I'm experiencing this on `4.8.4` but slightly different error, not sure if also caused by `importHelpers`

```
web: > node main
web: /var/app/current/node_modules/tslib/tslib.js:250
web: return privateMap.get(receiver);
web: ^
web: TypeError: privateMap.get is not a function
web: at Object.__classPrivateFieldGet (/var/app/current/node_modules/tslib/tslib.js:250:27)
```

**Comment by Banou26** [comment] 2022-12-16 00:14
@boy51 getting the same issue, i don't have `importHelpers` though, have you found a workaround?

**Comment by harvey-woo** [comment] 2023-01-03 10:13
> @boy51 getting the same issue, i don't have `importHelpers` though, it looks like it's coming from my `p-queue` package since it's using private class fields, have you found a workaround?
> 
> Edit: It seems installing `tslib^2.4.1` manually has fixed the issue for me.

Just add `tslib^2.4.1` to resolutions,
And run `npm install`,
the lock file will update, remove `tslib^2.4.1` on resolutions just added,
run `npm install`, again, the lock file will be updated again, and this problem will be fixed

**Comment by rbuckton** [comment] 2023-01-05 21:44
> @boy51 getting the same issue, i don't have `importHelpers` though, it looks like it's coming from my `p-queue` package since it's using private class fields, have you found a workaround?
> 
> Edit: It seems installing `tslib^2.4.1` manually has fixed the issue for me.

Is it possible you had an older `tslib` installed via a transitive dependency?

**Comment by svallory** [comment] 2023-01-07 01:52
> If I were to follow these steps I would also get this error since the npm init in your steps indicates this is in a completely empty folder

HAHAHAHA thank you! I thought `tslib` was a reference to the `lib.d.ts` files that are part of the typescript package!
