### ISSUE TITLE
Enum Literal Types  2.4.1

### ISSUE THREAD

**Issue by acopalipsis** [Microsoft/TypeScript#17068] opened 2017-07-10 19:20 UTC
```
enum E {
    A = 1,
    B = "b"
}

let valye: E.A | E.B = 123; // Ok?
```

**Comment by andy-ms** [comment] 2017-07-10 19:37
Duplicate of #6131

**Comment by acopalipsis** [comment] 2017-07-10 19:39
@andy-ms there on the enum in the role of type

**Comment by andy-ms** [comment] 2017-07-10 19:43
I can't tell what the question is -- besides the problem of an arbitrary number being assignable to an enum type, which is issue #6131.

**Closed** 2017-07-10 19:47 UTC
Labels: Duplicate
