### ISSUE TITLE
mapping over an array of tuple types does not give the correct type

### ISSUE THREAD

**Issue by mattyork** [Microsoft/TypeScript#11312] opened 2016-10-03 03:03 UTC
**TypeScript Version:**  2.0.3

**Code**

The `map` callback in the code below is the identity function.

``` ts
let arr: Array<[number, number]> = [[1, 2]]

let mappedArr: Array<[number, number]> = arr.map(([x, y]) => {
    return [x, y];
})
```

**Expected behavior:** `mappedArr` is of type `Array<[number, number]>`. Compilation works.

**Actual behavior:** Doesn't work. Error message:

```
Type 'number[][]' is not assignable to type '[number, number][]'.
  Type 'number[]' is not assignable to type '[number, number]'.
    Property '0' is missing in type 'number[]'.
```

 [TypeScript playground link](https://www.typescriptlang.org/play/#src=let%20arr%3A%20Array%3C%5Bnumber%2C%20number%5D%3E%20%3D%20%5B%5B1%2C%202%5D%5D%0D%0A%0D%0Alet%20mappedArr%3A%20Array%3C%5Bnumber%2C%20number%5D%3E%20%3D%20arr.map%28%28%5Bx%2C%20y%5D%29%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20%5Bx%2C%20y%5D%3B%0D%0A%7D%29%0D%0A)

**Comment by kitsonk** [comment] 2016-10-03 05:44
Tuples are never inferred.  On the return, you [have to be explicit](http://www.typescriptlang.org/play/#src=let%20arr%3A%20Array%3C%5Bnumber%2C%20number%5D%3E%20%3D%20%5B%5B1%2C%202%5D%5D%0D%0A%0D%0Alet%20mappedArr%3A%20Array%3C%5Bnumber%2C%20number%5D%3E%20%3D%20arr.map((%5Bx%2C%20y%5D)%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20%3C%5Bnumber%2C%20number%5D%3E%20%5Bx%2C%20y%5D%3B%0D%0A%7D)%3B%0D%0A):

```typescript
let arr: Array<[number, number]> = [[1, 2]]

let mappedArr: Array<[number, number]> = arr.map(([x, y]) => {
    return <[number, number]> [x, y];
});
```

... [or](http://www.typescriptlang.org/play/#src=let%20arr%3A%20Array%3C%5Bnumber%2C%20number%5D%3E%20%3D%20%5B%5B1%2C%202%5D%5D%0D%0A%0D%0Alet%20mappedArr%3A%20Array%3C%5Bnumber%2C%20number%5D%3E%20%3D%20arr.map((%5Bx%2C%20y%5D)%3A%20%5Bnumber%2C%20number%5D%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20%5Bx%2C%20y%5D%3B%0D%0A%7D)%3B%0D%0A) ...

```typescript
let arr: Array<[number, number]> = [[1, 2]]

let mappedArr: Array<[number, number]> = arr.map(([x, y]): [number, number] => {
    return [x, y];
});
```

But of course then you don't have to be explicit about the [left hand side then](http://www.typescriptlang.org/play/#src=let%20arr%3A%20Array%3C%5Bnumber%2C%20number%5D%3E%20%3D%20%5B%5B1%2C%202%5D%5D%0D%0A%0D%0Alet%20mappedArr%20%3D%20arr.map((%5Bx%2C%20y%5D)%3A%20%5Bnumber%2C%20number%5D%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20%5Bx%2C%20y%5D%3B%0D%0A%7D)%3B%0D%0A):

```typescript
let arr: Array<[number, number]> = [[1, 2]]

let mappedArr = arr.map(([x, y]): [number, number] => {
    return [x, y];
});
```

**Comment by gcnew** [comment] 2016-10-03 07:34
You can also manually augment `map` as proposed in https://github.com/Microsoft/TypeScript/pull/11252.

**Comment by kitsonk** [comment] 2016-10-03 08:46
Which means this is dupe of #6574, I had forgotten.

**Comment by calebegg** [comment] 2016-10-28 23:48
I don't think this is a dupe; that issue is about mapping tuples to tuples (and also, it's fixed). This is about mapping arrays of tuples to arrays of tuples.

The issue could be more succinctly stated as: "Tuple return types are not inferred". Here's a simple repro case:

http://www.typescriptlang.org/play/#src=function%20foo(x%3A%20number%2C%20y%3A%20string)%20%7B%0D%0A%20%20%20%20return%20%5Bx%2C%20y%5D%3B%0D%0A%7D

(note that the return type is (number | string)[] instead of [number, string])

The fact that arrow functions therefore can't map tuples to tuples is just a consequence of that.

**Comment by mhegazy** [comment] 2016-10-29 00:10
This is another manifestation of https://github.com/Microsoft/TypeScript/issues/11152.


`map` is declared as:

```ts
map<U>(callbackfn: (value: T, index: number, array: T[]) => U, thisArg?: any): U[];
```

so you see `U` is only inferred from the return type of the callback function. since tuple types are never inferred unless there is a contextual type (which in this case there is none), a regular array type is inferred for `U`, then the assignment check is done, and it fails.

The piece that is missed here, is we know that the `U[]` will be assigned to `mappedArr`, and we should use this as a contextual type. #11152 tracks propagating using the return type of the contextual signature if one exists as another location for inference.

**Closed** 2016-10-31 21:51 UTC
Labels: Duplicate
