### ISSUE TITLE
Docs in base interface overriding docs in object typed with extended version of the same interface

### ISSUE THREAD

**Issue by yashsway** [microsoft/TypeScript#55753] opened 2023-09-15 13:03 UTC
### 🔎 Search Terms

Closest issue I found: https://github.com/Microsoft/TypeScript/issues/12031

Also searched: "interface docs overriding", "interface", "extended interface", "extended interface docs", "interface shadowing", "interface shadowing implementor"

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because this bug appeared on the current version of Typescript I'm using. I didn't have the opportunity to test on other versions. Using `4.9.5`.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/PTAEDpNBnALBDATgUwCagC4E8AOzqgCWAdqAPbHKgBmhANspOAFAkbKLXwDGVAgqADezUKNDAAVBNDcU8DIQrlqoeKBTQyAV0S9QE4CLGzk85AC5QACkGhU8tQF9Lt+xniX4xLKEcBKUABeAD5QAAVEMgBbQmhkAB4ANzJCVGCAbiNRSWktHDcqMhUvUGQAD1iFYgBzdXxtXSoDLNA8gssbIlQAGjsHXxcuy2gMRBJq3rcPVW9fAJDwyJi4pJS0zMdmZhAIKBIZsgxYDhp6KiZWYnZOHn4wui0CcvZiVAIBYTFxKVUZMjI6DJHhhoqAosgjmR0M0vtxgdEALIQ2BQjrzUIRaKxBLJVIZZibZjcCgjVT2HDXSx8e6PIJCFo5IEjUEmMx2Mhw8FXeSKUgw4xydgdVz9fxBDFLbHgDQAxLIKx+boMn5w5lRVr5NmoDlaLnuBRKfmiNpmYVdSai9GLLFxaX1OhyhVK2HwqJIyGoNHi63LRgyh3yvwEzLbMCPcbkHRk+AUjjMeDk67gVnsTpTSwAIm1+GIAHIMKAAO5kRAAawzc0yCZjSZNqdsqUzAEYMxb3JmRvRAdnoHmC8WyxX-FXExxk673SjUAqQzsUXLEOQFzMfEVMMcwcioQR4AAjMhy0AAPRm6Cw2hgKK0dHQ5Tw3ALIJgyCoRyoqpB6u1nOQ3INxCYUBdy0AsKDoHw3yIK4OC4PRv11X99V5S8yELaAgA

### 💻 Code

```ts
// ... shared types in one file...
interface A {
    /** creation of a resource */
    create: ({ data }: { data: any }) => Promise<void>;
    /** update of an existing resource */
    update: ({ id, data }: { id: string, data: any }) => Promise<void>;
}

// ... in another file ...
interface APlus extends A {
    /** a cool custom method */
    customMethod: () => Promise<void>;
}

const adapter: APlus = {
    /** custom create documentation */
    create: ({ data }) => Promise.resolve(),
    /** custom update documentation */
    update: ({ id, data }) => Promise.resolve(),
    customMethod: () => Promise.resolve()
};

// using our adapter
adapter.create({ data: "doesn't work" });
adapter.update({ id: "1", data: "still doesn't work" });
adapter.customMethod();

// hover over any of the methods above ^ and you should expect to see the custom documentation in intellisense... but only the interface documentation shows
```

### 🙁 Actual behavior

Intellisense JSDoc shows:

| Method | Doc |
|--------|--------|
| create | creation of a resource |
| update | update of an existing resource |
| customMethod | a cool custom method | 

### 🙂 Expected behavior

Intellisense JSDoc should show:

| Method | Doc |
|--------|--------|
| create | custom create documentation |
| update | custom update documentation |
| customMethod | a cool custom method | 

1. Use the documentation in the closest type
2. Fallback up the extends chain for documentation if it does not exist in the current type

### Additional information about the issue

VSCode version dump:

Version: 1.82.1 (Universal)
Commit: 6509174151d557a81c9d0b5f8a5a1e9274db5585
Date: 2023-09-08T08:49:32.930Z (1 wk ago)
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 22.6.0

**Comment by fatcerberus** [comment] 2023-09-15 13:43
I think this is expected behavior because you've explicitly annotated `adapter` as `APlus`, so the custom docs in the object literal you assigned to that are lost.  It's just like writing `const x: number = 42` instead of `const x = 42` - only in the latter case can you hover over `x` in subsequent code to see the exact value you assigned to it; otherwise that information is lost.

This almost does what you want:
```ts
const adapter = {
    /** custom create documentation */
    create: ({ data }) => Promise.resolve(),
    /** custom update documentation */
    update: ({ id, data }) => Promise.resolve(),
    customMethod: () => Promise.resolve()
} satisfies APlus;
```

I say "almost" because you lose the documentation for `customMethod`.  Ultimately I don't think there's a way to inherit docs in an object literal like this.  You either get the docs from the type, or from the object literal, but not both at once.

**Comment by nmain** [comment] 2023-09-15 13:46
> Ultimately I don't think there's a way to inherit docs in an object literal like this. You can either get the docs from the type, or from the object literal, but not both at once.

```typescript
const _adapter = {
    /** custom create documentation */
    create: ({ data }) => Promise.resolve(),
    /** custom update documentation */
    update: ({ id, data }) => Promise.resolve(),
    customMethod: () => Promise.resolve()
} satisfies APlus;

const adapter: APlus & typeof _adapter = _adapter;
```

[Playground](https://www.typescriptlang.org/play?ssl=23&ssc=51&pln=15&pc=1#code/PTAEDpNBnALBDATgUwCagC4E8AOzqgCWAdqAPbHKgBmhANspOAFAkbKLXwDGVAgqADezUKNDAAVBNDcU8DIQrlqoeKBTQyAV0S9QE4CLGzk85AC5QACkGhU8tQF9Lt+xniX4xLKEcBKUABeAD5QAAVEMgBbQmhkAB4ANzJCVGCAbiNRSWktHDcqMhUvUGQAD1iFYgBzdXxtXSoDLNA8gssbIlQAGjsHXxcuy2gMRBJq3rcPVW9fAJDwyJi4pJS0zMdmZhAIKBIZsgxYDhp6KiZWYnZOHn4wui0CcvZiVAIBYTFxKVUZMjI6DJHhhoqAosgjmR0M0vtxgdEALIQ2BQjrzUIRaKxBLJVIZZibZjcCgjUAAfXg9hw1yCQhaOSBI1BJjMdjIcPBV3kilIMOMcnYHVc-X8QQxS2x4A0AMSyCsfm69J+cKZUVa+VZqHZWk57gUSj5ojaZiFXUmIvRiyxcSl9Tosvlith8KiSMhqDRYqty0Y0vtcr8BJg3OgtHwoD490emSJJIwqip10skYeBAAZJhcMgiuTKfBqSdArnExwYztHuNyDoE-nrsw8wXEOAWexOlNLAAiLX4YgAcnjAHcyIgANYduaZBvXcDG1u2VKdgCMHfN7k7I3ogO70D7g+HY4n9ZLTZVINdyKh8rLYBRssQ5DvMx8OaOVHB7oI8AARmRZaAAHozOgWDaDAKJaHQ6DlHg3DxiCMDIFQr6MmebIcsgXL6sQTCgF+WjxhQdA+MhbAcFwehauhmE8mBZADtAQA)

**Comment by fatcerberus** [comment] 2023-09-15 13:47
> 1. Use the documentation in the closest type
> 2. Fallback up the `extends` chain for documentation if it does not exist in the current type

For the record: The "closest type" in the original example is `APlus` because of the explicit type annotation, so this actually describes what TS already does.  The feature you're missing is the ability to have an object literal directly "inherit" documentation (at least without an ugly workaround like @nmain shows above).

**Comment by RyanCavanaugh** [comment] 2023-09-15 15:06
I agree with [this comment](https://github.com/microsoft/TypeScript/issues/55753#issuecomment-1721306661)

Not really sure what the action item is here; there are more requested doc behaviors than there are ways to write a program. The current implementation tries to do the right thing and something with a reasonable claim to being right is happening here.

**Comment by fatcerberus** [comment] 2023-09-15 15:26
@RyanCavanaugh Maybe an option could be to have JSDoc be inherited through contextual typing.  Then my `satisfies` example would work.  I was a bit surprised that didn’t *already* work, actually.

**Closed** 2023-09-18 01:25 UTC
Labels: Not a Defect
