### ISSUE TITLE
Typescript JSX with Generics - Parameter implicitly has an 'any' type

### ISSUE THREAD

**Issue by ayloncarrijo** [microsoft/TypeScript#46961] opened 2021-11-30 21:02 UTC
When using JSX syntax with Generics, Typescript is able to infer properties normally, except the type of function parameters.

Example code:

```typescript
interface Dictionary {
  a: JSX.IntrinsicElements['a'];
  button: JSX.IntrinsicElements['button'];
}

type Props<T extends 'a' | 'button'> = Dictionary[T] & {
  as: T;
};

function Test<T extends 'a' | 'button'>(args: Props<T>) {
  return null;
}

<Test as="a" href="#" onClick={(arg) => {}} />; // Parameter 'arg' implicitly has an 'any' type.

Test({
  as: 'a',
  href: '#',
  onClick: (arg) => {}, // No error
});
```

[TS Playground](https://www.typescriptlang.org/play?ts=4.5.2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4Aoc4AOxiSk3STgBFgNgJqUoBPOAN7k4cFAC44AKQDKADQB0ASVpQaAZ3YBRADZIQSWmoDa%20FPgC6FEQCMArjBhcJMhcpirqGtDr0GYx-DsHLgsKAF9KGF4wZgAFHDA1AB4AFTgkAA86agATNQIzOAAfAiDHanwAPjgAXlZ2GE5uPiMU8zgAMkFhUTUJFPCKckxbag4uOBSkNRhU9KyDPIL8YtL7cqqACh4Acz64eIhE1MqASm6RIhhbKGo4alttbXDKVOn4FDUagCIUb7gABZETA-ADE-y4AGFtOwANY1ATbKA7c41aoCMJhOAAekqQymM02QhEnwkpnwABoekCkJgyaDKT0oTC0LCJEiUbV0WEqWFThQgA)

If I place the mouse over the onClick property, it can tell the type of the onClick (React.MouseEventHandler<HTMLAnchorElement>), but still cannot infer the parameter's type.

**Comment by jcalz** [comment] 2021-11-30 21:15
Duplicate of #44596 I think.  Also there is a [template](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md) you're supposed to fill out completely when you create a bug report here; doing so helps the TS team triage and address the issue.

**Closed** 2021-12-03 18:00 UTC
Labels: Duplicate
