### ISSUE TITLE
Incorrect Generic Constraint with Union when Nested

### ISSUE THREAD

**Issue by wilwade** [microsoft/TypeScript#51969] opened 2022-12-19 22:50 UTC
# Bug Report

### 🔎 Search Terms

Generic 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics and unions

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/C4TwDgpgBAKhC2YCyB7AJhANlAvFA3gFBRQCWaAXFAHYCu8ARhAE4DcxUAHlQM7DOlqAc3YkQvfoJGEAvoUKhIUAMLMIAQ2AQ4iVBmx4ACqQDGAawA8O5OiwAaKAHJOjqAB8nIRwD52C8NAAYijM8IbMKGA8VlAQnFrUaDywCDb67ipqmtqpeljeuAQcPBDAeZhUABTwthWwAJS4BQBuKOSiUDX6VDAdpDwAomikwFJUDCgomBrU7HKEglrMAGbqJtCqGlrBoeGRyXEJSVA7YRFRFpvZ1uUFRCT9QyNjUKuYJXPyiyyr61BPwFOeyisXiEESySB52iN1qdw4j2Go2EVH4tAgn0IJhQ1D4JxC8EKl1BR2SV22BOByQ8AKh+28lXuUBKZVqdg4XXsCMGSKk7JkVGUjRw8I4JGxuOAUAAFupEtMAPLUZSy4TQPAWJAk8HHZQAbQARJzMAaALoOADS2ohUDMEBAKGWUCQDOa6kw6KoSD1FvNtvtVAtwvhJFDoYA9OHYNKICVmdKULRMGgaCgpbLmtA5bFmBFmFB1MkWeUoABlAASCoAqgAZAAiMvUmagimgAANqrUerlahlyTldLVg1BWu022Kw8zSuVO-p6h1J1PWfpGVAAHQb40OPV2kCmqhuj3QGTz+SLkiR6P9KDY3MQEzATAgMjUZYsHgbtdQBi0KXX4Axsy6jwNA2IYAAhBOYakE6lSIs8wiNEy55LjOxqnihJDFrUq6fluUA7va+4ju66JQCeC6TjIsTvNAyHnthK7oZRi6MVguGbmyBG7sRh5kRRUGhnIYYyJ8QA)

### 💻 Code

```ts
type FormProps<T extends TempModel | CreateTempModel> = {
  setModel: (model: T) => void;
  model: T;
}

type CreateFormProps = FormProps<CreateTempModel>;
type EditFormProps = FormProps<TempModel>;

const Form = <C extends CreateFormProps | EditFormProps>({
  setModel,
  model
}: C) => {
    const handleOnChange = <M extends C["model"], K extends keyof M>(value: M[K], key: K) => {
        setModel({ ...model, [key]: value });
    };
}
```

### 🙁 Actual behavior

The compiler resolves the type of setModel as `(model: TempModel) => void;`

### 🙂 Expected behavior

The compiler resolves the type of setModel as `(model: TempModel | CreateTempModel) => void;`

### Additional Complexity

The playground code DOES work in another case.

If we add an additional constraint of `isEditing` this will NOT throw the error:

```ts
interface CreateFormProps extends FormProps<CreateTempModel> {
  isEditing: false;
}

interface EditFormProps extends FormProps<TempModel> {
  isEditing: true;
}

const Form = <C extends CreateFormProps | EditFormProps>({
  setModel,
  model,
  isEditing,
}: C) => {

    const handleOnChange = <M extends C["model"], K extends keyof M>(value: M[K], key: K) => {
        // FAIL
        setModel({ ...model, [key]: value });

        // WORKS, but there is no code difference between the branches!
        if (isEditing) {
          setModel({ ...model, [key]: value });
        } else {
          setModel({ ...model, [key]: value });
        }
    };
}
```

**Comment by andrewbranch** [comment] 2022-12-22 22:33
Ah, this is a classic. Duplicate of #35873/#30581. The first thing to note is that the nested generic is a red herring. You can remove it completely and see the same puzzling behavior:

```ts
const Form = <C extends CreateFormProps | EditFormProps>({
  setModel,
  model,
  isEditing,
}: C) => {
  setModel(model); // error
  if (isEditing) {
    setModel(model) // works
  } else {
    setModel(model) // works
  }
}
```

The error stems from the fact that

> These should not have an error as setModel SHOULD have type `(model: TempModel | CreateTempModel) => void;`

is incorrect. `setModel` is a union of functions which is decidedly _not_ the same as a function whose parameter is a union of the constituent functions’ parameters. When you union functions, you _intersect_ their parameters:

```ts
setModel: ((model: TempModel) => void) | ((model: CreateTempModel) => void)
// reduces to
setModel: (model: TempModel & CreateTempModel) => void
```

Since the function could have either signature, you have to call it with an argument that would satisfy either signature—that is, a type that satisfies both `TempModel` and `CreateTempModel`. You don’t have that. What you have is a value that will _either_ satisfy `TempModel` or `CreateTempModel`, but never both at the same time.

What the compiler doesn’t understand, the way you’ve written it here, is that these two unions are correlated. I _think_ if you study #30581 and the PR that closed it, you can probably find a way to rewrite this that works.

**Comment by wilwade** [comment] 2022-12-22 23:30
@andrewbranch Interesting and thank you! I got two versions working (see the second one as it is very interesting)

The model of the union of functions resolving to the intersection makes sense.

I think the best resolution here is something along the lines of this [Playground Link](https://www.typescriptlang.org/play?ts=4.9.4#code/C4TwDgpgBAKhC2YCyB7AJhANlAvFA3gFBRQCWaAXFAHYCu8ARhAE4DcxUAHlQM7DOlqAc3YkQvfoJGEAvoUKhIUAMLMIAQ2AQ4iVBmx4ACqQDGAawA8O5OiwAaKAHJOjqAB8nIRwD52C8NAAqmA8LMBI6mC4BFAARCZqmhCxVKoaWtZ69nG0YGhJKbAINvpQMn6K0ABiKMzwhswoIRYA0lAQnFrUaDxQZhAgKABmUMGhzOGR0f2DI2NhEWDe0UQkoeG2mFQAFPCbVPMTiwDaLQC6AJS4ywBuKOSiUHv6ByELkadnj0O18DABVBa7DkhBMKGofCgNTq0W2qyg6yymDsHGe9g4Pzq-0gKJkVGh9UaISuOGW8MRm12mwuwMIQA)

```ts
type UpsertMap = { "create": CreateTempModel, "update": TempModel };

type FormProps<K extends keyof UpsertMap = keyof UpsertMap> = {
  setModel: (model: UpsertMap[K]) => void;
  model: UpsertMap[K];
  formType: K;
}
```

I still don't quite understand how the `if (isEditing)` is assists the compiler in working in the original version, but I think this works for my needs.

That said. This also works! [Playground Link](https://www.typescriptlang.org/play?ts=4.9.4#code/C4TwDgpgBAKhC2YCyB7AJhANlAvFA3gFBRQCWaAXFAHYCu8ARhAE4DcxUAHlQM7DOlqAc3YkQvfoJGEAvoUKhIUAMLMIAQ2AQ4iVBmx4ACqQDGAawA8O5OiwAaKAHJOjqAB8nIRwD52C8NAAYijM8IbMKGA8FgDSUBCcWtRoPCpqmtoINvrusFl6WLhpGlrWBdgeZbaY3kVEJDwQwOVUABTw1VQxAJS4tQBuKOSiUB36XSOkPACiaKTAUlQMKCiYGtTscoQmKNR8UMGhRa31UI3N1XYcY-YcU7PzUlcyVIdhEVG9OLWn5+Xt1W6myAA)

```ts
type FormProps<K extends CreateTempModel | TempModel = CreateTempModel | TempModel> = {
  setModel: (model: K) => void;
  model: K;
  isEditing: boolean;
}

const Form = ({
  setModel, model, isEditing,
}: FormProps) => {
  setModel(model);
}
```

That really doesn't make sense to me, but I guess somehow it is correctly constraining?

**Closed** 2022-12-25 18:00 UTC
Labels: Duplicate

**Comment by fatcerberus** [comment] 2023-01-10 16:14
@wilwade I know this issue is 3 weeks old, but I felt I should answer this:

> I still don't quite understand how the `if (isEditing)` is assists the compiler in working in the original version

From the compiler's point of view, you have a `((model: TempModel) => void) | ((model: CreateTempModel) => void)` and you're trying to call it with a `TempModel | CreateTempModel`.  These two unions are correlated (the values involved will always be compatible), but the compiler is only looking at the types in isolation so it doesn't know that.  By adding the `if (isEditing)` check, you narrow down the original discriminated union to a single constituent in each branch, in turn making it so that `model` and `setModel` are themselves no longer unions and the calls therefore succeed.
