### ISSUE TITLE
v2.3.2: spreading objects of type any seems to be removing imports

### ISSUE THREAD

**Issue by dzearing** [Microsoft/TypeScript#15546] opened 2017-05-03 01:23 UTC
**TypeScript Version:**  2.3.2 (also repros in 2.3.1, but not 2.2.1)

**Code**

We're seeing problems with spreading objects that aren't typed correctly.

This works, notice that `styles` has a type of empty object:

```tsx
import * as React from 'react';
import { animationClassNames } from '@uifabric/styling';

let styles: {} = {};

export function testMe() {
  return <div { ...styles }>{ animationClassNames } />;
}
```

The output generated successfully requires the `styling` package stored in the `styling_1` variable:

```js
var React = require("react");
var styling_1 = require("@uifabric/styling");
var styles = {};
function testMe() {
    return React.createElement("div", tslib_1.__assign({}, styles),
        styling_1.animationClassNames,
        " />; }");
}
```

However, if the `styles` object is of type any, the `styling_1` variable disappears, and causes nastiness downstream.
 
Typescript:

```tsx
import * as React from 'react';
import { animationClassNames } from '@uifabric/styling';

let styles: any = {};

export function testMe() {
  return <div { ...styles }>{ animationClassNames } />;
}
```

Generated JavaScript, where did `styling_1` go?

```js
var tslib_1 = require("tslib");
var React = require("react");
var styles = {};
function testMe() {
    return React.createElement("div", tslib_1.__assign({}, styles),
        styling_1.animationClassNames,
        " />; }");
}
exports.testMe = testMe;
````

**Expected behavior:**

Spreading objects without typings doesn't break things.

**Actual behavior:**

Unexpected breakage. 

Note that I'm using `any` here as an example; we've seen this happening in places where the object is of type `React.HTMLProps<HTMLDivElement>` and we don't understand. We've seen a number of errors from 2.3.2 where the compiler is complaining about spreading objects in JSX that are definitely objects of some interface shape but TypeScript isn't recognizing them.

**Comment by dzearing** [comment] 2017-05-03 01:52
Looks like a dupe of #15478, but in this case imports are being stripped. Feel free to close and track there, if this is the same. It's important to fix asap.

**Comment by mhegazy** [comment] 2017-05-03 23:12
This is caused by the same underlying issue as https://github.com/Microsoft/TypeScript/issues/15469. it should be fixed by https://github.com/Microsoft/TypeScript/pull/15548. The fix should be available in `typescript@next` tomorrow (5/4), please give it a try and let us know if you are still seeing issues.

**Closed by mhegazy** 2017-05-03 23:12 UTC
