### ISSUE TITLE
Missing Imports using TSX, ellipsis and transpileOnly (ts-loader)

### ISSUE THREAD

**Issue by olmobrutall** [Microsoft/TypeScript#15727] opened 2017-05-10 12:30 UTC
Hi Roslyn Team,

This is a follow-up of this issue: https://github.com/TypeStrong/ts-loader/issues/538

I'm responsible for a set of  [Framework](https://github.com/signumsoftware/framework) / [Applications](https://github.com/signumsoftware/southwind) that use TS and React intensively and trying to update to TS 2.3. 

We're using webpack, ts-loader and the option `transpileOnly` that makes the initial compilation much faster (40s -> 150s).  `transpileOnly` will call `transpileModule`.  

Using this `transpileOnly`, in combination with ellipsis in TSX elements makes TS to forget importing some references.  

## Github Repository that reproduces the problem in isolation

https://github.com/olmobrutall/tsxError

## TS Source

```TS
import * as React from 'react'
import { classes } from './Utils'

export interface Typeahead2Props {
    spanAttrs?: React.HTMLAttributes<HTMLSpanElement>;
}

export default class Typeahead2 extends React.Component<Typeahead2Props, {}>
{
    render() {

        return (
            <span {...this.props.spanAttrs} className={classes(this.props.spanAttrs && this.props.spanAttrs.className, "sf-typeahead")}>
              
            </span>
        );
    }
}
```

## JS Full compilation (Right)

```JS
Object.defineProperty(exports, "__esModule", { value: true });
var React = __webpack_require__(35);
var Utils_1 = __webpack_require__(36);
var Typeahead2 = (function (_super) {
    __extends(Typeahead2, _super);
    function Typeahead2() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Typeahead2.prototype.render = function () {
        return (React.createElement("span", __assign({}, this.props.spanAttrs, { className: Utils_1.classes(this.props.spanAttrs && this.props.spanAttrs.className, "sf-typeahead") })));
    };
    return Typeahead2;
}(React.Component));
exports.default = Typeahead2;
```

## JS Transpilation (Wrong)

```JS
Object.defineProperty(exports, "__esModule", { value: true });
var React = __webpack_require__(35);
var Typeahead2 = (function (_super) {
    __extends(Typeahead2, _super);
    function Typeahead2() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Typeahead2.prototype.render = function () {
        return (React.createElement("span", __assign({}, this.props.spanAttrs, { className: Utils_1.classes(this.props.spanAttrs && this.props.spanAttrs.className, "sf-typeahead") })));
    };
    return Typeahead2;
}(React.Component));
exports.default = Typeahead2;
```

> Note the missing `Utils_1` 

Thanks for the nice work :)

**Comment by jquintozamora** [comment] 2017-05-10 13:32
Hi @olmobrutall ,
Similar issue happened to me on #15721. 

Temporary I used this workaround:
Import with require and different variable name "cardType":

`const cardType = require("../ViewerItem/ViewerItemCardType");`

 Use it using this variable name:
`cardType.ViewerItemCardType.Big`

Isn't ideal, but worked temporary, let's see if we have a quick fix for that, which seems important.

Maybe in your scenario would be like:
Import:
`const utils = require("./Utils");`
Usage:
```tsx
<span {...this.props.spanAttrs} className={utils.classes(this.props.spanAttrs && this.props.spanAttrs.className, "sf-typeahead")}>
</span>
```

**Comment by olmobrutall** [comment] 2017-05-10 15:25
Hi @jquintozamora

Thanks for your detailed answer, indeed looks like the same problem. 

Are you also using TS-loader with transpileOnly? 

I've found workarounds but then i found another bug... 

The issue can also happen with imported symbols inside of the JSX element with ellipsis, not in properties.

It's a set of big applications and is failing at runtime so I'll prefer a proper solution. 

Let's see if the sun arrives to Seattle and we get some attention :)

**Comment by jquintozamora** [comment] 2017-05-10 17:59
Hi @olmobrutall , Actually I am using ts-loader, but not transpileOnly.

**Comment by olmobrutall** [comment] 2017-05-10 18:55
Strage, removing transpileOnly fixed the problem in my case...

**Comment by mhegazy** [comment] 2017-05-10 19:08
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/15469. should be fixed in `typescript@next` and in the next TS 2.3.3 release next week. 

can you give `typescript@next` a try and see if you are still running into issues?

**Comment by olmobrutall** [comment] 2017-05-11 08:22
Looks like works :+1:

**Closed** 2017-05-11 16:13 UTC
Labels: Duplicate
