### ISSUE TITLE
Enums behave unexpectedly, the workaround is verbose. There should be a less verbose way.

### ISSUE THREAD

**Issue by anurbol** [microsoft/TypeScript#32690] opened 2019-08-03 00:33 UTC
##  Search Terms

enums

## Suggestion
Because enums do not work as expected...

```ts
const enum MyEnum {
    Zero, 
    One
} 

const foo: MyEnum.Zero = 0 // Ok as expected (since MyEnum.Zero is zero)
const bar: MyEnum.Zero = 1 // OK, but expected Error!
```
...people start using this workaround (aka "namespace-as-enum"):

```ts
namespace MyEnum {
  export const Zero = 0;
  export type Zero = typeof Zero;

  export const One = 1;
  export type One = typeof One;
}
type MyEnum = typeof MyEnum[keyof typeof MyEnum];
const foo: MyEnum.Zero = 0 // okay as expected
const bar: MyEnum.Zero = 1 // error as expected

```

Maybe there should be a less verbose way to do this common stuff? 
For example it could be something like `enum MyEnum  {type Zero, type One}` 

## Use Cases

I use number values (i.e. enums) extensively instead of string values for performance reasons (a lot of JSON.stringify/parse).

## Examples

```ts
// Syntax A...
const enum MyEnum {
    type Zero,
    type One
} 
// ...or syntax B (C++ style) 
const enum class MyEnum {
    Zero, 
    One
} 

const foo: MyEnum.Zero = 0 // Ok 
const bar: MyEnum.Zero = 1 // Error!
```
[C++ had the same problem and they fixed it](https://stackoverflow.com/questions/18335861/why-is-enum-class-preferred-over-plain-enum/18338930)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AnyhowStep** [comment] 2019-08-03 01:10
Please don't close this issue as "working as intended" or "question". At the very least, leave it open so people can vote on it.

It's pretty annoying that enums are basically just `number` just to support bit masks/flags when that's not what an enum is really supposed to be

**Comment by anurbol** [comment] 2019-08-03 03:05
Yep, we only need a sugar syntax for namespace-as-enum workaround. The behavior of the workaround should remain..

**Comment by forivall** [comment] 2019-08-10 00:28
i *think* the `--preserveConstEnums` compiler flag can be used for that, although I haven't used it. It's worth investigating

**Comment by AnyhowStep** [comment] 2019-09-05 18:33
Anyway, one reason for wanting a new type of `enum` is because the current `enum` type does not reflect the actual run-time values.

```ts
enum Test {
    One = "one",
    Two = "two"
}

//Expected: "one"
//Actual  : never
type strExtractEnum = Extract<"one", Test.One>

//Expected: Test.One
//Actual  : Test.One
type enumExtractStr  = Extract<Test.One, "one">

//Expected: OK
//Actual  : Error
const e : Test.One = "one";
//Expected: OK
//Actual  : OK
const s : "one" = Test.One;

//"one"
console.log(Test.One);
//"one"
console.log("one");
//true
console.log("one" === Test.One);
```
[Playground](https://www.typescriptlang.org/play/#code/KYOwrgtgBAKsDOAXKBvAUFTUDyJhQF4oAiAez2IBoMsYB3UwkxB4tAXzTQHpuBRAB4AHYAGNEwACYAuEuWBteAQXFgAhgBtMsvADdgAJzSIAniKhIDgxAbXi+4aEWu3xAHjIVKsBIgB0uMAAfFy8giLiUrJwSAF4PNwqiOpaUNG+ccDGZvigkC52iADKNpjOAjaFbjH+gd6eCiEJ4WISMjgA0glJKdpQfAYGpEai5EhQ+OmxgUwNxADczcKtUZ3dqpp92F2jIOPwaXIUTDWZiwlzaLvwpBrAfhqkAOYAFKeBAJSLvJfXt-ePV5zL4JGxgLJ-O4PZ4vOaEAhEd54L5AA)

**Comment by mperktold** [comment] 2019-12-06 11:28
This behavior is really counter-intuitive.

The [TypeScript handbook ](https://www.typescriptlang.org/docs/handbook/enums.html#union-enums-and-enum-member-types) itself states that if all enum members are initialized to a static value, 

> ... enum types themselves effectively become a union of each enum member. While we haven’t discussed union types yet, all that you need to know is that with union enums, the type system is able to leverage the fact that it knows the exact set of values that exist in the enum itself.

This is simply not true, but I wish it was.

What concerns me the most is that this behavior is in conflict with certain type inference rules such as [exhaustiveness checking](https://www.typescriptlang.org/docs/handbook/advanced-types.html#exhaustiveness-checking) when using `strictNullChecks`.

For example, the following is considered exhaustive, but in reality isn't:

```ts
enum Direction { Left, Right }

function directionName(dir: Direction): string {
  switch (dir) {
    case Direction.Left:  return "left";
    case Direction.Right: return "right";
  }
}

// both calls return undefined, even if that shouldn't be possible
console.log(directionName(Direction.Left | Direction.Right));
console.log(directionName(42));
```

I was aware that you can use enums as bit flags and combine them using bitwise logic operators, but I assumed that the compiler somehow distinguished between the two cases based on some conventions.

For example, it could activate bit flag behavior only if all constants are initialized to a single bit or a combination of other constants, and otherwise fallback to a strict union type of all constants.

```ts
enum DirectionFlags {
  // single bits
  Up    = 1 << 0,
  Right = 1 << 1,
  Down  = 1 << 2,
  Left  = 1 << 3,
  // predefined combinations
  UpRight   = Up | Right,
  DownRight = Down | Right,
  DownLeft  = Down | Left,
  UpLeft    = Up | Left
}
```

It really think it would be much safer and more convenient to only allow bit flag usage if the enum definition meets certain conditions, to make sure it really was intended to be used in this way.
Also, I don't think flags are used very often.
And of course, a distinction on the syntax level would be even better.

I understand that changing the behavior of enums breaks backward compatibility.
On the other hand, perhaps a large number of developers have an incorrect intuition of how enums work, so maybe the change fixes more than it breaks.

**Comment by jhnns** [comment] 2019-12-21 14:03
Just stumbled upon this and I have to say that I'm really surprised about the current behavior. To me, the keyword `enum` clearly communicates that only the *enumerated* values are allowed, not just all numbers. And what's even more surprising is that enums *do work* as expected with strings. They're even super-strict with strings, treating enum members effectively as symbols:

```ts
enum State {
    Success = "SUCCESS",
    Error = "ERROR",
}

const state: State = "SUCCESS"; // Error, because it's not State.Success
                                // This is how symbols work
```

To me, this behavior is very unexpected and also inconsistent. And given the long list of issues (#17734, #21546, #11559, #15591, #8020, #18409, ...) I'm not the only one that finds that surprising.

I do understand that this is a massive breaking change, especially for the TypeScript project itself. But I think that this needs to be addressed somehow. I honestly never used bit masks in my projects, but I do use enums all the time and there are a lot of places where I relied on the exhaustiveness check (which clearly doesn't work as you can pass in any number).

What about a `symbol enum` or `enum symbol` keyword:

```ts
enum symbol State {
    Success,
    Error,
}

// Syntactic sugar for:

const State = {
    Success: Symbol("Success") as unique symbol, // as unique symbol is currently not
    Error: Symbol("Error") as unique symbol,     // allowed but you probably get the gist :)
};

type State = typeof State.Success | typeof State.Error;

let state: State;
state = State.Success; // Works
state = "Success"; // Error, because it must be the State.Success symbol
```

This would also be a good trade-off between easy to write enums that do not require you to re-spell the string literal (as string enums currently do) while maintaining debuggability because of symbol descriptions.

**Comment by nbabanov** [comment] 2020-06-22 15:21
I would also appreciate a proper fix for the enums. As they stand now, they seem a bit useless.

**Comment by forivall** [comment] 2020-06-22 21:59
For the case in https://github.com/microsoft/TypeScript/issues/32690#issuecomment-528516646 
```ts
//Expected: "one"
//Actual  : never
type strExtractEnum = Extract<"one", Test.One>
```
A workaround for this is in the following gist: https://gist.github.com/forivall/8968ec4ef450ceac9949b3a25583ca6d  It leverages the behaviour that an enum can be treated as a const value, and makes it work the other way around.

**Comment by hoclun-rigsep** [comment] 2021-07-08 20:49
I went with this:
```ts
const roles = {
  DSCO: 0x1 as 0x1,
  AIDE: 0x2 as 0x2,
  LT: 0x4 as 0x4,
  FF: 0x8 as 0x8,
  CHIEF: 0x12 as 0x12,
};
type Role = keyof typeof roles;
type RoleAsInt = typeof roles[keyof typeof roles];
```
It isn't completely DRY but it's close: the repetition is short and contained to each line. Would love some feedback.

**Comment by RyanCavanaugh** [comment] 2021-07-08 21:25
@hoclun-rigsep you can write `as const` on the outside instead of `as 0x1` on each line

**Comment by hoclun-rigsep** [comment] 2021-07-08 21:35
Amazing! Cuts down on the RY. Already glad I posted.

**Comment by Spongman** [comment] 2022-06-27 20:15
i'm surprised there isn't a simple way to create a typesafe enum distinct from `number`. isn't the whole point of typescript to add type-safety to javascript? allowing arbitrary values to be assigned to an enum-typed value seems contrary to this goal.

**Comment by hoangfnv** [comment] 2022-07-26 10:52
Current:
enum EnumTest {
    One = 1, // => typeof EnumTest.One in compile time: EnumTest.One (alias for number), runtime: number
    Two = "two",  // => typeof EnumTest.Two in compile time: EnumTest.Two (alias for some type be treated as Symbol('two')), runtime: string
}
=> It clearly leads to an unsafe type as in many cases above. 

Suggestion:
enum EnumTest {
    One = 1, // => typeof EnumTest.One in compile time: EnumTest.One (alias for 1), runtime: number
    Two = "two",  // => typeof EnumTest.Two in compile time: EnumTest.Two (alias for 'two'), runtime: string
}

Current solution:
- Never use "enum" with the initial value as a number (it is not a safe type). Use string initial instead of, the problem here just is we can't directly assign a string value to a variable had enum type

**Comment by nbabanov** [comment] 2022-08-25 10:54
@DanielRosenwasser Hey Dan, what do you think about this issue? A lot of people have to write more verbose code because of this.

**Comment by mkarajohn** [comment] 2022-09-01 15:12
Bumped into this today as well, just for the record.

**Comment by nbabanov** [comment] 2022-09-02 12:44
@RyanCavanaugh Any breakthrough here?

**Comment by nbabanov** [comment] 2023-04-06 08:10
> ```ts
> enum MyEnum {
> 	B = 3
> }
> 
> function foo(param: MyEnum) {    
> }
> 
> foo(MyEnum.B); // This should be the only working example.
> 
> foo('asdfasdf'); // This does not work, which is good.
> 
> foo(2); // This should also not work, but it does. :(
> ```

Seems like this is finally fixed in TypeScript v5!

Thanks a lot for the work! 🎊

**Closed** 2023-04-07 16:22 UTC
Labels: Suggestion, Awaiting More Feedback
