### ISSUE TITLE
class private methods shouldn't be "exported"

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/TypeScript#6748] opened 2016-01-30 03:33 UTC
Pretty much like the title says, private methods should stay private:

### input:
```
class NoRespect {
	private priv() {}
	pub() { return this.priv(); }
} 
```
### actual output:

```
var NoRespect = (function () {
    function NoRespect() {}
    NoRespect.prototype.priv = function () { };
    NoRespect.prototype.pub = function () { return this.priv(); };
    return NoRespect;
})();
```
### expected output:
```
var NoRespect = (function () {
    function NoRespect() {}
    var priv = function () { };
    NoRespect.prototype.pub = function () { priv.call(this); };
    return NoRespect;
})();
```

```
➜ tsc --version
message TS6029: Version 1.7.5
```

**Comment by yortus** [comment] 2016-01-30 05:43
Duplicate of #1537?

**Comment by DanielRosenwasser** [comment] 2016-01-30 08:31
Thanks @yortus.

**Closed by DanielRosenwasser** 2016-01-30 08:31 UTC
Labels: Canonical, Duplicate

**Comment by sant123** [comment] 2016-06-23 13:18
@yortus Either way is duplicated or not, the solution of private methods would be fine. As you can see, it really hiddes the method but it continues using the ```this``` keyword. Besides, private methods should stay as the name says 'only for the class' and Typescript compilation supports it! But that method can be consumed by normal Javascript because is inside the prototype of the class. 

Please take a look at this example:

```javascript
(function() {
    var Person = (function() {
        function secretMessage() {
            return "Hi " + this.name + " " + this.lastName;
        }

        function Person(name, lastName) {
            this.name = name;
            this.lastName = lastName;
        }

        Person.prototype.greet = function() {
            return secretMessage.call(this);
        };

        return Person;
    }());

    var c = new Person("Santiago", "Aguilar");
    console.log(c.greet()); //will greet :)
    console.log(c.secretMessage()); //ey ey this function is private, and can't be reached! Because it's private!
})();
```
