### ISSUE TITLE
Annoying NPM warnings from tsserver

### ISSUE THREAD

**Issue by chmln** [Microsoft/TypeScript#20908] opened 2017-12-27 17:44 UTC
Hello,

Context: I'm using tsserver wrapped in an LSP, and tsserver emits a useless npm warning every time on startup.

![screenshot from 2017-12-27 12-39-47](https://user-images.githubusercontent.com/11352152/34388720-4d54d16e-eb03-11e7-9670-5d6966ab088a.png)

While you may say the client should filter out and ignore this output, I believe this warning should not exist in the first place - it is cryptic and accomplishes nothing.

**Expected behavior:**
silence

**Actual behavior:**
npm warning about missing package description/etc even though project's package.json does contain these fields

**TS Version**: 2.6.1

**Comment by RyanCavanaugh** [comment] 2017-12-27 19:00
Duplicate of #19660

**Closed** 2018-01-11 20:05 UTC
Labels: Duplicate
