### ISSUE TITLE
Soundness problem in assigning properties on a union?

### ISSUE THREAD

**Issue by Nathan-Fenner** [Microsoft/TypeScript#18101] opened 2017-08-29 02:51 UTC
**TypeScript Version:**  2.4.2

**Code**

```ts
type Circle = {
    tag: "circle",
    size: number,
}

type Detail = {
    tag: "mesh",
    size: "small" | "medium" | "large",
}

function make(): Circle | Detail {
    return { tag: "circle", size: 5 };
}

const example: Circle | Detail = make();
example.size = "small";

// example is now {tag: "circle", size: "small"}, which is not Circle | Detail.
```

**Expected behavior:**

Assigning `example.size = "small"` should be rejected; the RHS must be convertible to `number & ("small" | "medium" | "large")` (which is uninhabited) rather than `number | ("small" | "medium" | "large")`.

In detail, if you want to write

```
o.f = x;
```

and `o: A | B | C | D` then `x` must be assignable to `A["f"] & B["f"] & C["f"] & D["f"]`.

**Questions:**

I assume this is a deliberate design decision to simplify type-checking and make it easier to mutate properties in unions, but it would be nice to get confirmation.
There are a few things that would be more difficult to write with this stricter check, like

```
example.size = "small";
// temporarily invalid
example.tag = "mesh";
// now a valid object again of type Circle|Mesh.
```

If this is important, then putting the stricter behavior behind a flag like `--strictUnionPropertyAssignment` would be nice.

**Comment by mhegazy** [comment] 2017-08-29 18:02
duplicate of https://github.com/Microsoft/TypeScript/issues/14150

**Comment by mhegazy** [comment] 2017-09-12 19:55
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-12 19:55 UTC
Labels: Duplicate
