### ISSUE TITLE
`satisfies` should work when an object is spread into another

### ISSUE THREAD

**Issue by arcticmatt** [microsoft/TypeScript#51569] opened 2022-11-17 00:58 UTC
# Suggestion

It looks like `satisfies` doesn't work when you spread an object into another

## TypeScript errors as expected

```
type Colors = "red" | "green" | "blue";

// Ensure that we have exactly the keys from 'Colors'.
const favoriteColors = {
    "red": "yes",
    "green": false,
    "blue": "kinda",
    "platypus": false
//  ~~~~~~~~~~ error - "platypus" was never listed in 'Colors'.
} satisfies Record<Colors, unknown>;
```

## TypeScript does not error, but I think it should

```
type Colors = "red" | "green" | "blue";

const foo = {
    "platypus": false
}

// Ensure that we have exactly the keys from 'Colors'.
const favoriteColors = {
    "red": "yes",
    "green": false,
    "blue": "kinda",
    ...foo
} satisfies Record<Colors, unknown>;
```

I would expect the latter to also have a TypeScript error, to prevent `favoriteColors` from having undesired extra properties.

Why? Well, because sometimes passing extra properties can break stuff.

## 🔍 Search Terms

satisfies, spread

**Comment by fatcerberus** [comment] 2022-11-17 02:09
Duplicate of https://github.com/microsoft/TypeScript/issues/50938; interestingly the examples are almost identical.

**Comment by fatcerberus** [comment] 2022-11-17 02:17
> Why? Well, because sometimes passing extra properties can break stuff.

Just FWIW, you probably shouldn't rely on this check to prevent runtime errors due to excess properties.  It's a linter-type feature primarily designed to catch typos in object literals; it's still very easy to end up with extra properties:

```ts
const faves = {
    "red": "yes",
    "green": false,
    "blue": "kinda",
    "platypus": false
};
const favoriteColors = faves satisfies Record<Colors, unknown>;  // no error
```

**Comment by RyanCavanaugh** [comment] 2022-11-17 17:47
Spreads aren't subject to excess property checks and it's not clear to me that they ever could be in an ergonomic way.

**Comment by fatcerberus** [comment] 2022-11-17 17:51
@RyanCavanaugh If this is Working As Intended, shouldn't #39998 be closed then? :wink:

**Comment by RyanCavanaugh** [comment] 2022-11-17 18:18
Awaiting More Feedback isn't the same as closed? 🙃

**Closed** 2022-11-19 20:00 UTC
Labels: Working as Intended
