### ISSUE TITLE
When infer K type from value type, occured an error in generic T[K] 

### ISSUE THREAD

**Issue by HealGaren** [microsoft/TypeScript#39972] opened 2020-08-10 10:33 UTC
**TypeScript Version:**  3.9.2

**Search Terms:** `ts type inference by value type`, `ts get property name from value type`

**Expected behavior:**
this is an example code of [typescriptlang.org : Distributive conditional types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#distributive-conditional-types)
I got `K` type that `T[K]` is `Function`. (following code:)

I expected TypeScript to be able to properly infer value type using this `K` type.
testForT1 and TestForGeneric should works fine.

**Actual behavior:**
I can't get V into the proper type using the K I got.
`testForT1` function worked, but `testForGeneric` function occured that error.
```
Type 'T[{ [K in keyof T]: T[K] extends Function ? K : never; }[keyof T]]' is not assignable to type 'Function'.
  Type 'T[T[keyof T] extends Function ? keyof T : never]' is not assignable to type 'Function'.
    Type 'T[keyof T]' is not assignable to type 'Function'.
      Type 'T[string] | T[number] | T[symbol]' is not assignable to type 'Function'.
        Type 'T[string]' is not assignable to type 'Function'.(2322)
```

**Related Issues:**

**Code**
```ts
type FunctionPropertyNames<T> = {
  [K in keyof T]: T[K] extends Function ? K : never;
}[keyof T];
type FunctionProperties<T> = Pick<T, FunctionPropertyNames<T>>;

interface T1 {
    method(): string;
    method2(): number;
}

function testForT1(data: T1, key: FunctionPropertyNames<T1>): Function {
    return data[key];
}


function testForGeneric<T>(data: T, key: FunctionPropertyNames<T>): Function {
    return data[key];
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function testForI1(data, key) {
    return data[key];
}
function testForGeneric(data, key) {
    return data[key];
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYgrgOwMbAJYHsEAUBO7I6gByAhgLYQDOAPACoB8UAvFAN4BQUUA2gNJSoEUANYQQ6AGZRaAXQBc0vjKgQAHsAgIAJpViIUGIQH4o-BQggA3CDgDc7AL7dR4qbPuhIe5Gky58NmhUdIwsWKhIwnQANN4GfngExOTBDPT27IIaOBIkSNAAkgCMbJxcUBTAABboWgAUAJQKlMA4ggDm9uUVENW1AEyN5nBkAEY29g7s7BL6vkIaLTDoOMV1WiTAJArFsS4K8D6G-kkgpBQ0xfRNcfOl3Ti9cDhCG1vOYjKT0zNzhlCLYDLHAAcU0NgiIXWm220j2YgOfwSAUIZxSNAYN0O8SEHAeTxeUDeJA+IC+jiAA)

**Comment by jack-williams** [comment] 2020-08-10 11:36
Duplicate of #32550, and in particular see Ryan's [comment](https://github.com/microsoft/TypeScript/issues/32550#issuecomment-515543721).

**Closed** 2020-08-10 23:07 UTC
Labels: Duplicate
