### ISSUE TITLE
Object.assing(this, {...}) not interpreted in constructors

### ISSUE THREAD

**Issue by dilyanpalauzov** [microsoft/TypeScript#38394] opened 2020-05-07 16:54 UTC
For this file:
```javascript
class T {
    a: string
    constructor (a:string) {
	Object.assign(this, {a})
    }
}

let t = new T('b')
```
tsc 3.8.3 reports

`error TS2564: Property 'a' has no initializer and is not definitely assigned in the constructor.`

I think property 'a'is definitely assigned in the constructor. `this.a = a` means the same.

**Comment by MartinJohns** [comment] 2020-05-07 17:02
Duplicate of #28883. Search terms: `object assign this constructor`.

**Closed** 2020-05-11 18:00 UTC
Labels: Duplicate
