### ISSUE TITLE
feature for enum methods

### ISSUE THREAD

**Issue by eczn** [microsoft/TypeScript#45164] opened 2021-07-23 09:48 UTC
# Suggestion

adding method for enum and make it more easier and powerful to use. current enum just a data enum map associating enum merber's name and value, but in fact, we need some calculations for enum, or else we have to declare another function to make such calculations:

``` ts
enum UserType {
    Admin: 1,
    Student: 2,
    Teacher: 3,
}

function getUserTypeText(userType: UserType) {
    // member name's translation in chinese
    const dictionary = ['', 'Admin 管理员', 'Student 学生', 'Teacher 老师'];
    return dictionary[userType]; // by mean of dictionary[1 | 2 | 3] to do translation
}

// in React render
declare const userType: UserType;
return <div>{ getUserTypeText(userType) }</div>
```

but if we have enum methods: 

``` ts
enum UserType {
    Admin: 1,
    Student: 2,
    Teacher: 3,
    toLocaleText() {
        const dictionary = ['', 'Admin 管理员', 'Student 学生', 'Teacher 老师'];
        return dictionary[this];
    }
}

// in React render
declare const userType: UserType;
return <div>{ userType.toLocaleText() }</div>
```

it improve code's readability and it's logic expressiveness

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2021-07-23 11:20
This would oppose the Viability Checklist.

**Comment by jcalz** [comment] 2021-07-23 13:15
Essentially a duplicate of #35039

**Comment by RyanCavanaugh** [comment] 2021-07-23 16:40
There's not even a way to emit this.

**Closed by RyanCavanaugh** 2021-07-23 16:40 UTC
Labels: Out of Scope, Suggestion
