### ISSUE TITLE
Immediately-executed callback function not considered when refining type.

### ISSUE THREAD

**Issue by bluepnume** [microsoft/TypeScript#52471] opened 2023-01-27 22:15 UTC
# Bug Report

```typescript
let foo = false;

[ 1, 2, 3 ].map(() => {
  foo = true;
});

type Foo = typeof foo;

// Foo resolves to `false`
```

Ideally `Foo` should resolve to `boolean` here

### 🔎 Search Terms

typescript immedately executed callback refine type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about immediately-executed callback functions
- 
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/FAGwpgLgBAZg9nKBeWBDEBnMBuYwDaUAjADRQBMZAzFALoB0AtqgA4AUbAlMgHxQDewKLATIoEAE4BXHMAC+nXMAgBPFmCgAxUSlXq4MEXCUB6E1tESwGOCABu18YgAGMdFmdA)

### 💻 Code

```typescript
let foo = false;

[ 1, 2, 3 ].map(() => {
  foo = true;
});

type Foo = typeof foo;

// Foo resolves to `false`
```
### 🙁 Actual behavior

`Foo` resolved to `false`, even though the runtime value is `true`

### 🙂 Expected behavior

`Foo` should resolve to `boolean` - since TypeScript does not intrinsically know if a callback will be called immediately or asynchronously.

**Comment by MartinJohns** [comment] 2023-01-27 22:33
Duplicate of #11498.

**Closed** 2023-01-30 18:00 UTC
Labels: Duplicate
