### ISSUE TITLE
5.1 regression: true is inferred as boolean and not assignable to true in complex types

### ISSUE THREAD

**Issue by ImRodry** [microsoft/TypeScript#54541] opened 2023-06-05 21:15 UTC
# Bug Report

### 🔎 Search Terms

- 5.1
- inference
- boolean

### 🕗 Version & Regression Information

- This changed between versions 5.0.4 and 5.1.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/JYWwDg9gTgLgBAbzgEQEZwL5wGZQiOAIhAgDsBzCAE1UIFgAoRqgUwGMAbAQyhbjbIBneDQBcKVI2aoAdAI4d2MYGQA8AQTgAfOACEAfAApCXVG0IBKGQFcwVLjBYB5Ui0NJsECOMKoehTAAaRDgAEmtSQRYYcQ8vcRgoaz4sDAspBmBSRyhsLjY+TQRGOFK4Lh8uegYyuFRxYSgs8kYMDKycvIK9RBKyiqJaPtK2BsTm1sYgA)

Sidenote about the snippet used: I noticed this bug while using the mongodb package and was not able to reproduce it with standalone types. This package uses very complicated types so I couldn't determine where the error was coming from, what I can tell is that it only starts happening when we use two or more interfaces in a union in the collection() call that have the same property with different string literals (in this case property "a" exists in interfaces A and B and has the value "a" in A and "b" in B). Although this template says not to use external libraries, I believe this is still a bug with TS as it is incorrectly inferring the type of the object passed to $unset. If anyone can reproduce this bug without using the package and explain why it happens I'd appreciate it a lot! This was also discussed on the TS Discord server: https://canary.discord.com/channels/508357248330760243/1114908480235651102

### 💻 Code

```ts
import { Db } from "mongodb"

declare const db: Db

db.collection<A | B>("abc").updateOne({ foo: "bar" }, { $unset: { foo: true } })

interface A {
    a: "a"
    b: string
}

interface B {
    a: "b"
    c: string
}
```

### 🙁 Actual behavior

The type of the values of the object is inferred as a generic `boolean`, which is not compatible with `true`

### 🙂 Expected behavior

Like in v5.0.4, an object of strings mapped to the constant value `true` should be assignable to the type required by the function which is `true | "" | 1`.

**Comment by nmain** [comment] 2023-06-07 12:40
The proposed fix in https://github.com/microsoft/TypeScript/issues/54498 fixes this as well.

**Comment by ImRodry** [comment] 2023-06-07 13:28
Thanks! That does seem to be way more detailed. I’ll await the PR

**Comment by gabritto** [comment] 2023-06-09 23:50
This seems to be a duplicate of #54498.

**Comment by ImRodry** [comment] 2023-06-10 00:28
yes I’m just waiting for the PR

**Closed** 2023-06-13 01:32 UTC
Labels: Duplicate
