### ISSUE TITLE
async iterator does not call return() for an abrupt completion at for await of loop

### ISSUE THREAD

**Issue by niceandneat** [microsoft/TypeScript#53106] opened 2023-03-06 03:00 UTC
# Bug Report

### 🔎 Search Terms

async iterator, for await loop

### 🕗 Version & Regression Information

- This changed after version [v4.9.3](https://github.com/microsoft/TypeScript/releases/tag/v4.9.3)

### ⏯ Playground Link

Target: ES2017 (with actual result)
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhhAnmYBJKBTATnARgGwxgF4YBvAKBhgG0BlRAW1xHwDoFk1McoQsAugAoAlOSrUYWDFACuWMOMmSwGAB5RRS5ZNCRWGNvhABzIQHJVG0eZEBuCTqkz5isjABucfLIwAuGHMAQnMAGhgAE3B-GAAzbwgiAF8HJyTQx0lpOQUhLx8Y6CwASzATMUonaj0IAyNTC2zXG3tM5SaFck9vX3Co1QCoLF8YFLbRjOUx6iSKMYoa2EY4UpJ4JBQYLWIAPm1Y-ngAdxXYIUWYNRgQWPWudGw8QgrMmrrjMzVW5VxpOABrVKjOYUCjLUqiOxAA)

Target: ES2018 (with expected result)
[Playground link with relevant code](https://www.typescriptlang.org/play?target=5#code/MYewdgzgLgBAhhAnmYBJKBTATnARgGwxgF4YBvAKBhgG0BlRAW1xHwDoFk1McoQsAugAoAlOSrUYWDFACuWMOMmSwGAB5RRS5ZNCRWGNvhABzIQHJVG0eZEBuCTqkz5isjABucfLIwAuGHMAQnMAGhgAE3B-GAAzbwgiAF8HJyTQx0lpOQUhLx8Y6CwASzATMUonaj0IAyNTC2zXG3tM5SaFck9vX3Co1QCoLF8YFLbRjOUx6iSKMYoa2EY4UpJ4JBQYLWIAPm1Y-ngAdxXYIUWYNRgQWPWudGw8QgrMmrrjMzVW5VxpOABrVKjOYUCjLUqiOxAA)

### 💻 Code

tsconfig.json

```json
{
  "compilerOptions": {
    "target": "ES2017",
  }
}
```

index.ts

```ts
const asyncIterable = {
  [Symbol.asyncIterator]() {
    return {
      next() {
        console.log('next()');
        return { value: '!', done: false };
      },
      return(value: string) {
        console.log('return()');
        return { value, done: true };
      },
    };
  }
};

const main = async () => {
  for await (const x of asyncIterable) {
    console.log(x);
    break;
  }
}

main();
```

Thanks to @kbridge for making [MCVE](https://stackoverflow.com/help/minimal-reproducible-example).

### 🙁 Actual behavior

```
next()
!
```

Should call `return()` for an abrupt completion at for await of loop (e.g. `break`, `throw`). This happens when `for-await-loop` code is transformed to target equal or lower than `ES2017`.

### 🙂 Expected behavior

```
next()
!
return()
```

If target for compilation is equal or higher than `ES2018`, It works as expected. This is also aligned with javascript specification.

**Comment by fatcerberus** [comment] 2023-03-06 03:11
Looks like a duplicate of https://github.com/microsoft/TypeScript/issues/52936

**Closed** 2023-03-09 18:00 UTC
Labels: Duplicate, Fix Available
