### ISSUE TITLE
Object.values not included in lib: es2017

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#28166] opened 2018-10-26 20:29 UTC
**TypeScript Version:**  3.2.0-dev.20181025

**Search Terms:**

**Code**
For a `tsconfig`:

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2017"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
} 
```

With code

```ts
Object.values({})  
```

**Expected behavior:**
No error on `Object.values`. This api was added in es2017

**Actual behavior:**
`Object.values` has error `Property 'values' does not exist on type 'ObjectConstructor'. [2339]`

**Comment by mister-walter** [comment] 2018-10-26 22:58
I've had issues in the past with specifying the `es2017` library not pulling in some of the new Object functions. I fixed it by adding `es2017.object` explicitly in libs in compilerOptions, like the following:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2017",
        "lib": ["es2017.object"]
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
} 
```

I'm not sure why this is necessary in either case (i.e. when `es2017` is in libs or when it's the target), since `es2017.object` is referenced inside lib.es2017.d.ts .

**Comment by lolleko** [comment] 2018-11-25 14:56
Probably related to #27874

**Comment by rbuckton** [comment] 2019-01-17 00:59
I cannot reproduce this in TypeScript 3.2.1 or later, this may have been resolved as part of a different fix. I'm closing this for now. @mjbvz: If this still seems to be an issue, please let me know and I will reopen.

**Closed by rbuckton** 2019-01-17 00:59 UTC
Labels: Domain: lib.d.ts, Needs Investigation
