### ISSUE TITLE
Nightly builds not getting update?

### ISSUE THREAD

**Issue by myitcv** [Microsoft/TypeScript#17401] opened 2017-07-25 16:13 UTC
```
$ date
Tue 25 Jul 17:09:08 BST 2017
$ cd `mktemp -d`
$ npm install typescript@next
$ ./node_modules/.bin/tsc --version
Version 2.5.0-dev.20170719
```

Or at least npm isn't getting updated:

```
$ npm show typescript | grep '2\.5'
     next: '2.5.0-dev.20170719',
     '1.6.0-dev.20150822': '2015-08-22T06:04:32.563Z',
     '1.9.0-dev.20160408': '2016-04-08T06:08:32.547Z',
     '1.9.0-dev.20160511': '2016-05-11T06:07:52.558Z',
     '2.1.0-dev.20161009': '2016-10-09T06:08:32.597Z',
     '2.1.0-dev.20161026': '2016-10-26T06:09:42.599Z',
     '2.2.0-dev.20170117': '2017-01-17T07:12:42.548Z',
     '2.3.0-dev.20170228': '2017-02-28T07:13:32.583Z',
     '2.4.0-dev.20170509': '2017-05-09T06:13:52.517Z',
     '2.5.0-dev.20170613': '2017-06-13T06:16:47.600Z',
     '2.5.0-dev.20170614': '2017-06-14T06:16:51.421Z',
     '2.5.0-dev.20170615': '2017-06-15T06:14:51.167Z',
     '2.5.0-dev.20170616': '2017-06-16T06:12:30.322Z',
     '2.5.0-dev.20170617': '2017-06-17T06:13:30.946Z',
     '2.5.0-dev.20170618': '2017-06-18T06:12:58.898Z',
     '2.5.0-dev.20170619': '2017-06-19T06:12:43.747Z',
     '2.5.0-dev.20170621': '2017-06-21T06:13:50.537Z',
     '2.5.0-dev.20170622': '2017-06-22T06:12:43.791Z',
     '2.5.0-dev.20170623': '2017-06-23T06:13:18.216Z',
     '2.5.0-dev.20170624': '2017-06-24T06:17:28.063Z',
     '2.5.0-dev.20170625': '2017-06-25T06:14:12.843Z',
     '2.5.0-dev.20170626': '2017-06-26T06:12:55.670Z',
     '2.5.0-dev.20170627': '2017-06-27T06:13:19.403Z',
     '2.5.0-dev.20170628': '2017-06-28T06:14:37.688Z',
     '2.5.0-dev.20170629': '2017-06-29T06:13:37.499Z',
     '2.5.0-dev.20170707': '2017-07-07T18:30:29.375Z',
     '2.5.0-dev.20170712': '2017-07-12T07:29:20.246Z',
     '2.5.0-dev.20170719': '2017-07-19T22:40:34.076Z' },
```

Same issue as before @yuit @DanielRosenwasser?

**Comment by DanielRosenwasser** [comment] 2017-07-25 16:51
Same issue. I'll publish now.

**Comment by DanielRosenwasser** [comment] 2017-07-26 00:54
Most up-to-date version should be published.

**Comment by DanielRosenwasser** [comment] 2017-07-26 00:55
Duplicate of #17012.

**Closed** 2017-07-26 00:56 UTC
Labels: Duplicate
