### ISSUE TITLE
--outDir + --watch + absolute path bug after file changes

### ISSUE THREAD

**Issue by soywiz** [Microsoft/TypeScript#1106] opened 2014-11-09 17:42 UTC
Version: 1.1.0.1
OS: MacOS

When I call tsc compiler with --watch switch and --outDir with an absolute entrypoint path, and change a file referenced in another folder, instead of outputing to the --outDir folder, it outputs .js files to where the .ts file is. It just happens after changing the file, the first compilation is right.

```
tsc --version
message TS6029: Version 1.1.0.1
```

Not reproducing the bug:
```
tsc -w --outDir out --target ES5 --module commonjs relative/path/test.ts
```

Reproducing the bug:
```
tsc -w --outDir out --target ES5 --module commonjs /absolute/path/to/file/test.ts

test.ts -> import a = require('anotherpath/otherfile');
anotherpath/otherfile.ts -> something;
```

**Comment by awerlang** [comment] 2015-03-19 11:37
I can reproduce an error related to watching absolute paths, even on Windows:

Command: 

```
dir features\\*.ts /B /S > tscfiles.txt
tsc --target ES6 --noEmitOnError --outDir ./tmp/features @tscfiles.txt
```

As soon as I change a file after running that command, I got an error.

```
message TS6042: Compilation complete. Watching for file changes.
message TS6032: File change detected. Compiling...
error TS5009: Cannot find the common subdirectory path for the input files.
message TS6042: Compilation complete. Watching for file changes.
```

File paths inside `tscfiles.txt` are absolute. If I change to relative, it works.

I have 2 suggestions here:

1) Make watch work with absolute paths
2) If watch mode should fail, fail fast

**Comment by DanielRosenwasser** [comment] 2015-03-25 07:19
Hey @soywiz, sorry to get back to this only now; I just tried out the original repro and it seems like this is actually no longer occurring on `master`. This is all probably a result of some of the work of refactoring our logic in `program.ts`.

@awerlang, if you'd like to take the time to try out `master` and confirm the issue is persisting then that would be greatly appreciated; however, if you can't, I can look into it further if you give me an appropriate repro for Windows.

However, since I believe this is fixed, I'm going to close the issue and mark it as so.

**Closed by DanielRosenwasser** 2015-03-25 07:19 UTC
Labels: Bug

**Comment by awerlang** [comment] 2015-03-25 16:35
@DanielRosenwasser I confirm the error I reported is gone. Thanks!

**Comment by materliu** [comment] 2016-05-17 07:53
encounter this again today!

**Comment by mhegazy** [comment] 2016-05-17 19:52
this is over a year old. do you mind filing a new issue and providing some details on what you see, what you expect and what version you are using.

**Comment by materliu** [comment] 2016-05-18 02:38
#8656 , thx @mhegazy
