### ISSUE TITLE
Maximum call stack size exceeded on long trivial method chain

### ISSUE THREAD

**Issue by jasonkuhrt** [microsoft/TypeScript#60626] opened 2024-11-27 15:07 UTC
### 🔎 Search Terms

"maximum call stack", "chaining api"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about maximum call stack

### 💻 Code

```ts
interface Context {}

interface Chain<$Context> {
  f: () => Chain<$Context>
}
declare const chain: Chain<{}>

// 488 chained calls to method "f"
chain
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f().f()
  .f().f().f().f().f().f().f().f()

/*

Uncomment the following line to hit tsc error during compilation.

It brings call chain to 489.

RangeError: Maximum call stack size exceeded ...
*/

// .f()
```

### 🙁 Actual behavior

```
RangeError: Maximum call stack size exceeded
    at getSymbolAtLocation (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/_tsc.js:85924:11)
    at getTypeFromTypeNodeWorker (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/_tsc.js:62046:24)
    at containsReference (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/_tsc.js:62289:101)
    at visitNode2 (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/_tsc.js:27895:18)
    at forEachChildInTypeReference (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/_tsc.js:28001:12)
    at forEachChild (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/_tsc.js:28416:35)
    at containsReference (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/_tsc.js:62313:16)
    at visitNodes (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/_tsc.js:27903:22)
    at forEachChildInTypeReference (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/_tsc.js:28001:49)
    at forEachChild (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/_tsc.js:28416:35)
```

### 🙂 Expected behavior

1. Able to compile regardless of chain depth
2. From a type checking point of view, if the code is not going to type check because of infinite depth issues then OK, but as a user I want to be informed about that to take corrective action. Imagine a complex project with dependencies and tens of thousands of lines of code etc. This failure gives no clue about what is "wrong" in the code. It relies on a developer having the precise context etc.

### Additional information about the issue

So far I have not been able to get TypeScript playground to choke on this: [link](https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgMIHtwQB5mQbwF8AoY0SWRFVACzlAB4ASDLXAPgOOWRgC5kACgCUyALyda9EM1aQOxEgBMICADZwoKBJgDOeBHVACpjIu1KHp3ZADoYI+44fCnrl288fvz3+79eAT7+IYEhNmGRwVFBsaHRCXExwhGJ8UlpyVmZOX6pGQXpRdmFJUX5xbmVpVVlyRV1tU01LeU8ja0d1d1lDc09-V1dfZ2DY6NxIwMT07PD7eNzi0NpUysz60sia8u7G1U7+0dbs4cnmxcHC8eXN1d2e+eP8w93b0+FZ7cfP2FfzwDjv93t9NsDfoCfuDQZCXjCQbCXNDEQjPtcIaiMeF0fCsbjkZjcfUcSi8Y8CWTCasSVTaacaZTGWCGUTSXC2RyZhTWXS3NzOUykSyBTzuvzeaTxYK6VLRaLZSLIQqJe9ldLGWq5UrhSr1X8dXrFXkDVrdXyTUbDdsLWaBZrLczXlbncSnaaXdS3Q7vdavbb-SkbR6ZUH3e77QH2ZGfYG-cH4xH41GkzHE2HFmmY70eHH0wHM9G0bms3bQyXVWXC1iCymi3na9ji1X5ZWG98a-Xs0225LW53td3+yHB+WNX3R46hw2OxPgjPm3PxwuuUueyuR8vqzntzuc0A).

**Comment by MartinJohns** [comment] 2024-11-27 15:14
Duplicate of #55100.

**Closed** 2024-11-27 18:32 UTC
