### ISSUE TITLE
Allow string literal types as index

### ISSUE THREAD

**Issue by scharf** [Microsoft/TypeScript#7205] opened 2016-02-24 00:40 UTC
**TypeScript Version:** 

1.8.2

**Code**

```ts
type FooBar = "foo" | "bar";

var map:{[foobBar:FooBar]: boolean};

```

**Expected behavior:**

I should be able to define a index type with a string literal type as key.

**Actual behavior:** 

The typescript compiler complains with
```
Error:(3, 11) TS1023: An index signature parameter type must be 'string' or 'number'.
```

**Comment by mhegazy** [comment] 2016-02-24 02:42
looks like a duplicate of #6246

**Closed by mhegazy** 2016-02-24 02:42 UTC

**Comment by mhegazy** [comment] 2016-02-24 02:44
actually https://github.com/Microsoft/TypeScript/issues/5683 is a better one to reference.
