### ISSUE TITLE
Invalid 'Object is possibly undefined' for variable definitely assigned via compound assignment

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#42412] opened 2021-01-19 20:39 UTC
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior since 4.0 where compound assignments were introduced

### ⏯ Playground Link

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210119#code/GYVwdgxgLglg9mABMOcAUBDAXIgTgUwwBMEAbAT0QGcpcYwBzAbQF1EAfRcI-Ye-IgBpEAIxwFiZSjTqNWHLmB58wAgJSIA3gFgAUIgOIMiAPwmAvKI6dWAbkQB6B4hL4qYAORREAdzi4Aaz1DI1MLKzNEO0dnV3cvX38g-UNjdnZLNBFrKJY1eycXODdPbz9A4NTrS2z03ILY4viypMqDQuMzGoBCBsTAqmEqOEQYbyp8fABbKkQoEYIARxAYAjmAC3xEACEMXF3cRH9EAEUQN1gEM4v4JDgAB3xcDHncNpjQyMxEGpzWfI+5QCVHeHRy31+dX+fSBIJS7WcMGAiDQ3QwGmMkJsLBhSThIQwADp6BBSCAeFQ0B4UHAPADCh4MB5RrN7nAqFQYCIKIgPNxePwiB49ABfIA)
      

### 💻 Code

```ts
function foo(a: string[] | undefined, b: string[] | undefined) {
    a ??= b || []; // doesn't work
    a ??= b ?? []; // doesn't work
    a ||= (b || []); // doesn't work
    a ||= b || []; // doesn't work
    // a ??= b!; // works, so it seems to require the BarBar or QuestionQuestion operator on the RHS
    // a ?? (a = b || []); // works
    // a || (a = b || []); // works
    // if (!a) a = b || []; // works
    a.includes('foo'); // 'a' is possibly 'undefined'
}
```

### 🙁 Actual behavior

Error `Object is possibly 'undefined'.` on the last statement.

### 🙂 Expected behavior

Each of the assignments should remove `undefined` from the type.

This might be caused by a faulty control flow graph for compound assingments because the same code written as its downlevel equivalent (see commented out lines) works as expected.

/cc @Kingwl

**Comment by MartinJohns** [comment] 2021-01-19 20:44
Looks like a duplicate of #40494.

**Closed** 2021-01-19 20:45 UTC
