### ISSUE TITLE
Suggestion: Operator overload

### ISSUE THREAD

**Issue by shrinktofit** [microsoft/TypeScript#31842] opened 2019-06-10 11:25 UTC
## Search Terms

Operator overload

## Suggestion

New operators(only in Typescript): 
- `#++` `#--`
- `#+` `#-` `#*` `#/` `#%`
- `#=`
- Any others...

```ts
class Vec3 {
    x: number;
    y: number;
    z: number;
    public #+ (other: Vec3) {
        return new Vec3(this.x + other.x, this.y + other.y, this.z + other.y);
    }
    public #* (scalar: number) {
        return new Vec3(this.x * scalar, this.y * scalar, this.z * scalar);
    }
    public #= (other: Vec3) {
        this.x = other.x;
        this.y = other.y;
        this.z = other.z;
        return this;
    }
}

// v1 + v2 * scalar
function multiplyAndAdd(v1: Vec3, v2: Vec3, scalar: number) {
    return v1 #= v1 #* scalar #+ v2;
}
```

is compiled as Javascript code:
```js

class Vec3 {
    x: number;
    y: number;
    z: number;
    public operator_add (other: Vec3) {
        return new Vec3(this.x + other.x, this.y + other.y, this.z + other.y);
    }
    public operator_scale (scalar: number) {
        return new Vec3(this.x * scalar, this.y * scalar, this.z * scalar);
    }
    public operator_assign (other: Vec3) {
        this.x = other.x;
        this.y = other.y;
        this.z = other.z;
        return this;
    }
}

function multiplyAddThenAssign(v, v1, v2, scalar) {
    return v.operator_assign(v1.operator_scale(scalar).operator_add(v2));
}
```

## Use Cases

A lot of math concepts such as complex numbers, vectors, matrix can benifit from it.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by j-oliveras** [comment] 2019-06-10 13:13
Duplicate of #19859 and #5407 and rejected.

**Comment by fatcerberus** [comment] 2019-06-10 14:00
TypeScript-specific operator overloading will basically never happen because it requires type-directed emit.  By design, if TypeScript sees `x + y`, it emits `x + y` in the output, regardless of what the types of `x` and `y` are.

The only way this could happen is if JavaScript itself got operator overloading.

**Closed** 2019-06-11 02:15 UTC
Labels: Duplicate

**Comment by shrinktofit** [comment] 2019-06-11 02:21
> TypeScript-specific operator overloading will basically never happen because it requires type-directed emit. 

Why does it must be type dependent? The `left #+ right`  can be treated simply as `left.operator_plus(right)` ignoring what left or right is.

**Comment by fatcerberus** [comment] 2019-06-11 02:26
Of course, but when the compiler sees `x + y` it has to know what the types of `x` and `y` are to know whether or not it has to change that to an `operator_plus()` call.  If they are, e.g. `number` then it can’t do that.

**Comment by fatcerberus** [comment] 2019-06-11 02:30
I’ll give you points for this: this is probably the cleanest syntax I’ve seen proposed for operator overloading in JS in a long time.  Would have been a better use for the `#` sigil than wasting it on private class members, but alas...
