### ISSUE TITLE
Document on programatically usage of typescript

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#53959] opened 2023-04-21 22:23 UTC
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Document on programatically usage of typescript.

## 📃 Motivating Example

In https://github.com/microsoft/TypeScript/issues/53958, I don't know how to use typescript programatically to test dts is resolved correctly.

https://github.com/loynoir/reproduce-typescript-53958/blob/85b8f7ca35d2e0856ff4e5ff2c4ab10a2361f3b4/test/test-runtime-resolve.mjs#L32

## 💻 Use Cases

```ts
type PathString = string;
type RequireAbleId = string;
type ImportAbleId = string;
type TypeAnnotationAst = {
  parent: TypeAnnotationAst | null;
  typeAnnotation: unknown;
};

async function dtsResolve(
  moduleId: PathString | RequireAbleId | ImportAbleId,
  kind: "require" | "import",
): Promise<PathString> {
  void { moduleId, kind };
  throw new Error();
}

async function typeResolve(
  moduleId: PathString | RequireAbleId | ImportAbleId,
  loc: {
    start: number;
    end: number;
  },
): Promise<TypeAnnotationAst> {
  void { moduleId, loc };
  throw new Error();
}
```

## Additional

In my other use case of using typescript programatically, find all source code ruled by same tsconfig, I think current typescript api is not very friendly to use.

Need to use `ts.` 6 times.

```ts
import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'

function tsNeighbor(importMetaUrl: string) {
  const tsconfigPath = ts.findConfigFile(fileURLToPath(importMetaUrl), ts.sys.fileExists, 'tsconfig.json')
  if (!tsconfigPath) throw new Error()

  const tsconfigFile = ts.readConfigFile(tsconfigPath, ts.sys.readFile)

  const parsedTsconfig = ts.parseJsonConfigFileContent(tsconfigFile.config, ts.sys, dirname(tsconfigPath))

  return parsedTsconfig.fileNames
}

console.log(tsNeighbor(import.meta.url))

```

**Comment by MartinJohns** [comment] 2023-04-21 22:29
Duplicate of #34890 / #17147. Used search terms: `document API in:title`. What search terms did you use?

**Comment by loynoir** [comment] 2023-04-21 22:33
I check https://www.typescriptlang.org/docs/handbook/

**Comment by loynoir** [comment] 2023-04-21 22:49
@MartinJohns 

I think document of resolving dts is outdated. 

https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#getting-the-dts-from-a-javascript-file

> file.replace(".js", ".d.ts")

**Closed** 2023-04-27 04:26 UTC
Labels: Duplicate
