### ISSUE TITLE
generics for "this" type

### ISSUE THREAD

**Issue by pleerock** [Microsoft/TypeScript#8740] opened 2016-05-22 17:53 UTC
Need to allow to use generics for "this" type, like this: `this<T>`

```typescript
class Collection<T> extends Array<T> {

    map<U>(callbackfn: (value: T, index: number, array: T[]) => U, thisArg?: any): this { 
        // this method will return this<T>, but I want to return this<U>
        return new (this.constructor as any)(...super.map(callbackfn, thisArg));
    }

}
```
example of usage:
```typescript
new Collection(
    new Model(1, "Mercedes"),
    new Model(2, "BMW"),
    new Model(3, "Ford")
)
    .map(model => model.engine)
    .forEach(engine => engine.serialNumber); // here compiler should see engine.serialNumber
```

**Comment by DanielRosenwasser** [comment] 2016-05-22 17:55
Looks like a duplicate of #6223. Let me know if not and we can reopen this.

**Closed** 2016-05-22 17:55 UTC
Labels: Duplicate
