### ISSUE TITLE
Contextually type object assignments to inherited member

### ISSUE THREAD

**Issue by omidkrad** [Microsoft/TypeScript#5181] opened 2015-10-08 19:15 UTC
I think the following should compile with no error:

```typescript
declare module Backbone {
	interface RoutesHash {
		[routePattern: string]: string | {(...urlParts: string[]): void};
    }
	class Events { }
	class Router extends Events {
		routes: RoutesHash;
	}
}

declare module Marionette {
	class AppRouter extends Backbone.Router {
	}
}

module Backbone.Tests {
	// Error, routes is not contextually typed
    class MyRouter extends Backbone.Router {
	    routes = {
	        "some/route": "someMethod",
			"some/otherRoute": () => {}
	    };
	}
}

module Marionette.Tests {
	// Error, routes is not contextually typed
    class MyRouter extends Marionette.AppRouter {
	    routes = {
	        "some/route": "someMethod",
			"some/otherRoute": () => {}
	    };
	}
}
```

**Comment by DanielRosenwasser** [comment] 2015-10-08 19:22
Duplicate of #3667?

**Comment by omidkrad** [comment] 2015-10-08 19:27
I guess it's a bug really.

**Closed** 2015-10-08 19:57 UTC
Labels: Duplicate
