### ISSUE TITLE
Types for global isNaN and Number.isNaN are swapped

### ISSUE THREAD

**Issue by ImRodry** [microsoft/TypeScript#52041] opened 2022-12-28 16:34 UTC
# Bug Report

### 🔎 Search Terms

isNaN

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 
This issue was mainly introduced by https://github.com/microsoft/TypeScript/pull/24436

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYZwcghmAUBECMsCUACA9GlAlApgFwFcAnAOxBQDMIAbEHFAIwLxVBIHIWIBjbnABzw4AJowCeKACoBlALAAoMAQC2DHEQB0oSDATJ0mAIK0A9iiL5iZSjTqNmrcjz6CR4qXPkLtUOBAbc+hjYlqTkeEQE9EwsbJwozgJCogwSMgpKqupa4L6w-oGowbiEYTa00Q6gCbxJbqkeQA)

### 💻 Code

```ts
isNaN("1") // Returns false but isn't accepted by TS
Number.isNaN("1") // Also returns false but is accepted by TS

isNaN("abc") // Returns true but isn't accepted by TS
Number.isNaN("abc") // Returns false but is accepted by TS
```

### 🙁 Actual behavior

global isNaN only takes a number as a parameter when it should take unknown because, as documented by MDN, "The isNaN() function answers the question "is the input functionally equivalent to [NaN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN) when used in a number context".", whereas Number.isNaN "provides a convenient way to check for equality with NaN" but "doesn't force-convert the parameter to a number". That being said I believe the global isNaN should accept an unknown parameter, whereas Number.isNaN should only accept a number.

### 🙂 Expected behavior

isNaN accepts a number and Number.isNaN accepts unknown

**Comment by fatcerberus** [comment] 2022-12-28 17:20
Duplicate of https://github.com/microsoft/TypeScript/issues/37449 and many, many others.

**Comment by ImRodry** [comment] 2022-12-28 17:26
This issue also focuses on the fact that Number.isNaN accepts unknown when that doesn’t really make any sense. If the global isNaN discussion is done then ignore that ig but I think that part should still be considered (see the linked pr)

**Comment by fatcerberus** [comment] 2022-12-28 17:29
I thought the discussion in https://github.com/microsoft/TypeScript/pull/24436 (which you linked in the OP) made it pretty clear why the `Number` functions accept any type.

**Comment by ImRodry** [comment] 2022-12-28 18:49
I know it does but I don't see a point in throwing anything that is not a number there because the result will be misleading. One might mistake that for the global one and then think that objects or strings are suddenly numbers

**Comment by RyanCavanaugh** [comment] 2023-01-04 16:57
The current design is intentional, not an oversight. I don't understand your logic here.

The problem with the global `isNaN` is that it provides "wrong" results, e.g. `isNaN([0, 1])` returns `true` even though `[0, 1]` *is not NaN*. That makes it "unsafe" to call because an unanticipated coercion might occur. `Number.isNaN` doesn't have this problem; it only returns `true` for the actual value `NaN`.

**Comment by ImRodry** [comment] 2023-01-04 17:29
@RyanCavanaugh my point here is that the fact that isNaN coerces the input to a number is known and completely intentional, and it has use cases. I also don't understand your example because [0, 1] is NaN, so the output is correct there and it will be for any value you put.

**Comment by RyanCavanaugh** [comment] 2023-01-04 17:43
> `[0, 1]` is `NaN`

But it isn't. That's the point. `[0, 1]` doesn't have the property that it isn't `===` to itself. It isn't `NaN`, it *coerces* to `NaN`, and the coercion rules are so weird that they're not plausibly invoked on purpose in well-formed code.

To put it another way, there are two functions:
 * One which, if given an actual number, tells you if that number is the `NaN` value, and returns kinda nonsense for everything else
 * One which, if given any value, tells you if that number is actually the `NaN` value

Clearly the first one should not be something that TypeScript lets you call with arbitrary values. The second one is something that *is* safe to call with any value. I think it's also obvious which one is global `isNaN` and which one is `Number.isNaN`.

**Comment by ImRodry** [comment] 2023-01-04 18:04
I don't understand why you call it nonsense. I got this idea initially because, in my code, I had a variable that came from user input which was a string. The user was supposed to type in a number and I simply wanted to check if what they typed was a valid number or not, so I should be able to do isNaN(input) to check that because that works and it makes perfect sense. Why isn't this a valid use case for you?

**Comment by ImRodry** [comment] 2023-01-04 18:34
The thing is I don’t need the number that the user put in, I simply needed a boolean to tell me whether it is a number or not and I can rule out `””` by simply checking its length or converting it to a boolean

**Closed** 2023-01-06 20:00 UTC
Labels: Working as Intended

**Comment by ImRodry** [comment] 2023-01-06 20:17
Bruh alright

**Comment by RyanCavanaugh** [comment] 2023-01-09 21:21
We clearly spelled out all of our reasoning on this. You're free to disagree with it but it's unrealistic for us to keep issues open forever under that condition.

**Comment by ImRodry** [comment] 2023-01-09 23:02
Yeah I know I just don’t think it makes sense but sure
