### ISSUE TITLE
hourCycle, dateStyle and timeStyle missing from interface Intl.ResolvedDateTimeFormatOptions

### ISSUE THREAD

**Issue by flip-it** [microsoft/TypeScript#42577] opened 2021-02-01 10:31 UTC
# Bug Report

### 🔎 Search Terms

Intl
DateTimeFormat
ResolvedDateTimeFormatOptions
hourCycle

### 🕗 Version & Regression Information

4.1.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.3#code/MYewdgzgLgBA3jAFiArgJwIwCYA0TVp7LoDCAnsADYCmeAJgIZTUDKUZNeUAlgLavsaMAL4wAvDDDUA7jACSYKJQB0AESbUAKn2oAxEGl5MAFAHJqYALQBVFqbxwAUDBf50ALhimwKfmm7A9o7CAJTKaNQQIJQAbtR0APIADjzgEMYhQA)

### 💻 Code

```ts
const { hour12, hour, hourCycle, dateStyle, timeStyle } = new Intl.DateTimeFormat('en-US', {
    hour: 'numeric',
}).resolvedOptions()
```

### 🙁 Actual behavior

Property 'hourCycle' does not exist on type 'ResolvedDateTimeFormatOptions'.
Property 'dateStyle' does not exist on type 'ResolvedDateTimeFormatOptions'.
Property 'timeStyle' does not exist on type 'ResolvedDateTimeFormatOptions'

### 🙂 Expected behavior

To be able to use all properties in Resolved Options of DateTimeFormat Instances defined in https://tc39.es/ecma402/#table-datetimeformat-resolvedoptions-properties

**Comment by MartinJohns** [comment] 2021-02-01 10:41
Duplicate of #35865 / #34399.

**Closed** 2021-02-04 18:00 UTC
Labels: Duplicate
