### ISSUE TITLE
No error on object literal containing property of wrong type for union

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#22129] opened 2018-02-22 22:36 UTC
**TypeScript Version:**  2.6.2, 2.7.2, 2.8.0-dev.20180222

**Search Terms:** 

**Code**

```ts
export interface A {
  x?: string;
}
export interface B extends A {
  y?: number;
}
export interface C extends A {
  z?: boolean;
}

const passes: B | C = { x: 'hello', z: 42 };
```

**Expected behavior:**

I would expect to get this type of error:

```
Types of property 'z' are incompatible.
  Type 'number' is not assignable to type 'boolean | undefined'.
```

**Actual behavior:**

No error. I would guess that the object literal is being inferred as a `B` with an extraneous `z` property instead of a `C`, however I would expect the rule about object literals not containing extraneous properties to apply. And what's odder is that if `x` isn't specified it  _does_ give the expected error:

```ts
const fails: B | C = { z: 42 };
```

[**Playground Link**](http://www.typescriptlang.org/play/#src=export%20interface%20A%20%7B%0D%0A%20%20x%3F%3A%20string%3B%0D%0A%7D%0D%0Aexport%20interface%20B%20extends%20A%20%7B%0D%0A%20%20y%3F%3A%20number%3B%0D%0A%7D%0D%0Aexport%20interface%20C%20extends%20A%20%7B%0D%0A%20%20z%3F%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Aconst%20passes%3A%20B%20%7C%20C%20%3D%20%7B%20x%3A%20'hello'%2C%20z%3A%2042%20%7D%3B%0D%0A%0D%0Aconst%20fails%3A%20B%20%7C%20C%20%3D%20%7B%20z%3A%2042%20%7D%3B%0D%0A)

**Comment by andy-ms** [comment] 2018-02-22 22:47
Looks like a duplicate of #20863

**Comment by pelotom** [comment] 2018-03-19 17:35
According to https://github.com/Microsoft/TypeScript/issues/20863#issuecomment-374267961, this is not a duplicate. Could it be reopened?

**Comment by andy-ms** [comment] 2018-03-19 19:26
Probably the error is that the object provided is assignable to `B` -- this should be considered an excess property and we should compare with `C` instead, which gives a better error.

**Comment by mhegazy** [comment] 2018-04-12 23:55
I believe the comment in https://github.com/Microsoft/TypeScript/issues/20863#issuecomment-374267961 is not right. this is a duplicate of #20863.

**Closed** 2018-04-26 15:07 UTC
Labels: Duplicate
