### ISSUE TITLE
Type guard using square bracket notation does not narrow type

### ISSUE THREAD

**Issue by mjdease** [microsoft/TypeScript#28081] opened 2018-10-23 16:02 UTC
**TypeScript Version:**  3.2.0-dev.20181023

**Search Terms:**
type guard square bracket notation narrowing

**Code**

```ts
interface ConfigType {
    [key: string]: boolean | { prop: string };
}

const config: ConfigType = {
    works: { prop: 'foo' },
    'works-not': { prop: 'bar' },
    bool: true,
};

if (typeof config.works !== 'boolean') {
    config.works.prop = 'test';
}

if (typeof config['works-not'] !== 'boolean') {
    config['works-not'].prop = 'test'; // [ts] Property 'prop' does not exist on type 'false'.
}
```

**Expected behavior:**
The type guard using square bracket notation narrows the type in the same way the type guard using dot notation does, resulting in no type errors in the above example.

**Actual behavior:**
The type guard specifically using square bracket notation does not narrow the type.

**Playground Link:** 
[Link](http://www.typescriptlang.org/play/#src=interface%20ConfigType%20%7B%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20boolean%20%7C%20%7B%20prop%3A%20string%20%7D%3B%0D%0A%7D%0D%0A%0D%0Aconst%20config%3A%20ConfigType%20%3D%20%7B%0D%0A%20%20%20%20works%3A%20%7B%20prop%3A%20'foo'%20%7D%2C%0D%0A%20%20%20%20'works-not'%3A%20%7B%20prop%3A%20'bar'%20%7D%2C%0D%0A%20%20%20%20bool%3A%20true%2C%0D%0A%7D%3B%0D%0A%0D%0Aif%20(typeof%20config.works%20!%3D%3D%20'boolean')%20%7B%0D%0A%20%20%20%20config.works.prop%20%3D%20'test'%3B%0D%0A%7D%0D%0A%0D%0Aif%20(typeof%20config%5B'works-not'%5D%20!%3D%3D%20'boolean')%20%7B%0D%0A%20%20%20%20config%5B'works-not'%5D.prop%20%3D%20'test'%3B%20%2F%2F%20%5Bts%5D%20Property%20'prop'%20does%20not%20exist%20on%20type%20'false'.%0D%0A%7D%0D%0A)

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/10530

**Comment by DanielRosenwasser** [comment] 2018-10-24 08:21
Is this not a duplicate of #10530?

**Comment by sandersn** [comment] 2018-10-24 15:39
No, this is not a duplicate. It's a missed interaction between indexed access and index signatures, where property access + index signatures works.
Here's a smaller repro, without the dashed-name red herring:

```ts
interface ConfigType {
    [key: string]: boolean | { prop: string };
}

const config: ConfigType = {
    works: { prop: 'foo' }
};

if (typeof config.works !== 'boolean') {
    config['works'].prop = 'test'; // error, config['works']: boolean | { 'prop': string }
    config.works.prop = 'test'; // ok
}
```

The behaviour is the same if the discriminator is `typeof config['works'] !== 'boolean'`, so I think it's just a failure of control flow from indexed access in this case.

Also note that if we have `interface ConfigType { works: boolean | { prop: string } }` then both statements work.

**Comment by rkirov** [comment] 2019-02-25 19:30
Just a drive by comment. We are working in Google internal TS to forbid using the prop access on index signature objects. The main reason is that to Closure prop access means safe to rename and index access means don't touch. This optimization pass is done without global knowledge (other than whats' coming externally) so its up to the developer to decide whether it is really "safe" to rename.

The transformation from `foo.bar` to `foo['bar']` is mostly noop TS-wise, except for this issue.

**Comment by sandersn** [comment] 2019-05-20 19:50
Turns out this was just missing. It is super simple to add since it's the same code as property access. I just need to make sure performance is OK.

**Comment by sandersn** [comment] 2019-06-14 15:33
Update: The PR is trivial and performance is, as expected, bad for probably-uncommon adversarial code. We need to discuss in the design meeting whether to take this change.

**Closed** 2019-07-16 17:10 UTC
Labels: Bug, Domain: Control Flow, Fix Available, Fixed
