### ISSUE TITLE
Local variable named `exports` interferes with global scope access in CommonJS mode

### ISSUE THREAD

**Issue by rix0rrr** [microsoft/TypeScript#46990] opened 2021-12-02 13:16 UTC
# Bug Report

### 🔎 Search Terms

exports

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ by Ctrl-F'ing for the word "exports". It does not appear anywhere.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?module=1&ts=4.5.2#code/KYDwDg9gTgLgBAYwgOwM7wEIEEByutwC8cA5AEYCGyVFJA3AFAMBmArsgjAJYpwAWwADaCIACgCUcAN4M4iFOjihIsVEVLsoQijGAATekzlI0EQcAB0IgOaiABgBUBcAG4VBrYHAjM42PHhwXGoAJFL++AC+duKMkQwCwmKxQA)

### 💻 Code

```ts
export const BANANA = 'banana';

function hello() {
  const exports = 'unrelated';

  console.log(`The value of BANANA is ${BANANA}`);  // <-- prints "The value of BANANA is undefined"
}
hello();
```

### 🙁 Actual behavior

Prints `the value if BANANA is undefined`.

As far as I can tell, I'm accessing a global (exported) variable. The JavaScript that is generated reads:

```js
    console.log(`The value of BANANA is ${exports.BANANA}`);
```

And so it's obvious what happens: the local variable named `exports` shadows the global export table. However, in my original TypeScript code there is no hint of  the export table, so I feel it is unreasonable for a TypeScript author to have to know about this.

### 🙂 Expected behavior

I expected one of the following two (both are reasonable to my mind):

* Do whatever renaming magic is necessary to make the lookup work. Whenever a local variable named `exports` is defined, copy the export table into a different variable and use that for subsequent lookups (`const _exports = exports;`).
* Reject variables named `exports` in local scopes as well, in addition to the rejection that already happens if I define this variable in the global scope: `Compiler reserves name 'exports' in top level scope of a module.`.

**Comment by MartinJohns** [comment] 2021-12-02 13:24
Duplicate of #33043.

**Closed** 2021-12-06 18:00 UTC
Labels: Duplicate
