### ISSUE TITLE
Control flow analysis for element access with variable index doesn't account for async race condition

### ISSUE THREAD

**Issue by rixtox** [microsoft/TypeScript#58822] opened 2024-06-10 16:10 UTC
### 🔎 Search Terms

Control flow analysis async race condition

### 🕗 Version & Regression Information

- This changed between versions 5.4.5 and 5.5.0
- This changed in https://github.com/microsoft/TypeScript/pull/57847

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.1-rc#code/IYZwngdgxgBAZgV2gFwJYHsIwOYFNkBywAtrgBQCUAXDAAoBO6xqIuAPCMvahNgHwwA3gCgYYmPXwJ6WAOQB3dPQA2AE1kBuYQF9hw0JFiIUGLHACMZdACMAVjQBKuKEtUcuPbABoYZMgA8aTm5eChgAXgEAN3RUVTCAHxgkVVw4HlxVPh8Aa1wwII9QoVFxVDhfZDAAB1x0CptbAG08sABdCPDwmAAiYyg0TB6wkXExmBcIThgIElwImGB5YFRkHHwiUkotcfFGlvy2slnSCh3xXTH91o7ulLSM1S1dYUnp1oXZbEl8T01XzDTRoLUbiA7tY5zQohbDUGAxOIlXZiN7oZS4AB0ynQ2DIAAMABK4ZTYnwAEkEJ1w2gAhHizqUxLoXgwmCxMcASWQmhYrHZcvkKD5eY0BWAKG0GUA

### 💻 Code

```ts
async function getName(): Promise<string> {
    return 'world';
}

async function f1(obj: Record<string, ((x: string) => void) | undefined>, key: string) {
    if (typeof obj[key] === "function") {
        const name = await getName();
        obj[key](name);
    }
    obj[key] = undefined;
}

const key = 'greeting';
const obj = {
    [key](name: string): void {
        console.log(`Hello, ${name}!`);
    }
}

Promise.all([f1(obj, key), f1(obj, key)]);
```

### 🙁 Actual behavior

No type error, but runtime failure:
```
Unhandled Promise Rejection: TypeError: obj[key] is not a function. (In 'obj[key](name)', 'obj[key]' is undefined)
```

### 🙂 Expected behavior

Type checker should account for potential race condition and do not persist the narrowed type after an `await` statement.

**Comment by nmain** [comment] 2024-06-10 16:17
This is a duplicate of #9998; see also the many other duplicates linked from that issue.

**Comment by rixtox** [comment] 2024-06-10 16:24
> This is a duplicate of #9998; see also the many other duplicates linked from that issue.

But this is a regression as 5.4.5 would not make the optimistic type narrowing on this path.

**Comment by Josh-Cena** [comment] 2024-06-10 17:46
How is this relevant to computed keys at all? Your code would have the same unsoundness if you substitute all `[key]` with `.greeting`.

**Comment by rixtox** [comment] 2024-06-10 19:39
> How is this relevant to computed keys at all? Your code would have the same unsoundness if you substitute all `[key]` with `.greeting`.

It's not about computed keys. I just took the [example from this blog](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-beta/#control-flow-narrowing-for-constant-indexed-accesses) and extended a bit.

**Comment by MartinJohns** [comment] 2024-06-10 19:59
> The main concern is that when there's an `await` in the control flow, you can no longer assume "neither `obj` nor `key` are ever mutated".

Which is exactly what #9998 is about. And it's unrelated to `await`, a sync function has the same issue.

**Comment by fatcerberus** [comment] 2024-06-10 21:43
The analogy for a synch function would be an intervening function call that causes the same mutation.

This issue is Exhibit A of "why TS team was so hesitant to add narrowing by indexed access for so long".  The bottom line is the compiler doesn't know whether any given `await` (or function call) is going to change types, so it's just a question of whether it should be optimistic or pessimistic when it encounters one.  Here TS chose to be optimistic.  If it was pessimistic, people would complain about unaffected variables being widened (leading to unsafe casts and/or redundant additional type checks), so neither option is really "better" than the other--it's a tradeoff.

**Comment by rixtox** [comment] 2024-06-11 00:47
> neither option is really "better" than the other--it's a tradeoff.

I think there are cases where a static analyzer can tell for sure a variable binding cannot be modified. For example if the variable is locally defined, not being modified synchronously, and not being captured by any closure. So if we rewrite the program like this:

```ts
async function f1(obj: Record<string, ((x: string) => void) | undefined>, key: string) {
    const method = obj[key];
    if (typeof method === "function") {
        const name = await getName();
        method(name);
    }
    obj[key] = undefined;
}
```

A static analyzer can tell that since `method` is locally defined, not captured by any closures, and not being modified locally, therefore, `method(name)` can be narrowed down safely according to the `typeof method === "function"` predicate.

This is less optimistic than the current analyzer but it still provides some good developer experience.

**Comment by rixtox** [comment] 2024-06-11 00:58
> neither option is really "better" than the other--it's a tradeoff.

Maybe worth mentioning the tradeoffs in the blog post. I read the blog post and felt it might not be as reliable as it seems. Which is why I wrote this issue. I don't think I would be the only one with this thought.

**Closed** 2024-06-17 01:31 UTC
Labels: Duplicate
