### ISSUE TITLE
Suggestion: document and enforce side effects of functions

### ISSUE THREAD

**Issue by AndrewMorsillo** [Microsoft/TypeScript#19520] opened 2017-10-27 02:49 UTC
Allow programmers to more descriptively document the side effects of functions and have Typescript check against these descriptions. [Google Closure seems to use this type of documentation for optimization](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler). It could result in better self documenting code, more helpful tooling, and more logic errors caught.

I am fairly new to TypeScript so I'm not sure if this would be really helpful in practice or not. What do you think?
 
No side effects
```ts
/** @nosideeffects */
function a(){
  let foo = "asdf";
  foo = "bar";
  return a
} //OK, only local variables are assigned to

/** @nosideeffects */
function b(){
  return SOME_GLOBAL;
} //OK, reads global state but does not modify it

/** @nosideeffects */
function b(){
  SOME_GLOBAL = "asdf";
} //ERROR, non local variable assigned to

/** @nosideeffects */
function c(bar: string){
  bar = "123"
  return bar
} //OK, non-reference type argument modified

/** @nosideeffects */
function d(bar: {a: string}){
  bar.a = "123"
} //ERROR, reference type argument modified

/** @nosideeffects */
function e(){
  const foo = a();
  return foo
} //OK, only @nosideeffects functions are called


function f(){
  return "foo"
}

/** @nosideeffects */
function g(){
  const foo = f();
  return foo
} //ERROR, cannot call a normal function from a @nosideeffects function
```

Modifies
```ts
function a(){
  let myObj = {foo: {bar: "bar"}}
  b(myObj)
  console.log(foo.bar) //WARN: myObj may have been clobbered by b(myObj)
}

/** @modifies {arg} */
function b(arg: any){
  delete arg.foo
}

```

**Comment by andy-ms** [comment] 2017-10-27 14:22
Looks like a duplicate of #17181

**Closed** 2017-11-10 23:17 UTC
Labels: Duplicate
