### ISSUE TITLE
type definitions bundler

### ISSUE THREAD

**Issue by Milo123459** [microsoft/TypeScript#40543] opened 2020-09-14 16:50 UTC
## Search Terms
type definitions, typescript typedefs, typescript definition bundler

## Suggestion
Add an option which will generate type definitions and bundle them into one "index.d.ts" (or whatever path)

## Use Cases
In tsconfig in compilerOptions you could add "bundleDefinitions": boolean | path/to/definition/file.d.ts

I want to use this for one of my projects which generates it's own definition files.
## Examples

This could be very helpful for developers who want's to have tsc generate a single type definition file.
## Checklist

My suggestion meets these guidelines:

* [ x ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ x ] This wouldn't change the runtime behavior of existing JavaScript code
* [ x ] This could be implemented without emitting different JS based on the types of the expressions
* [ x ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ x ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AlCalzone** [comment] 2020-09-14 19:35
https://github.com/TypeStrong/dts-bundle could be something for you

**Comment by kitsonk** [comment] 2020-09-14 20:08
Duplicate of #4433

**Comment by DanielRosenwasser** [comment] 2020-09-15 22:43
API Extractor's dts-rollup tool is the usual thing we forward people to these days.

https://api-extractor.com/pages/setup/configure_rollup/

**Closed** 2020-09-18 18:00 UTC
Labels: Duplicate
