### ISSUE TITLE
Output diagnostics in machine readable format (i.e. json)

### ISSUE THREAD

**Issue by Tallyb** [microsoft/TypeScript#57198] opened 2024-01-27 11:31 UTC
### 🔍 Search Terms

explainfiles, traceresolution

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Allow diagnostics options (explain files, trace resolution) etc. to generate machine readable format (i.e. json) that can be analyzed by tooling 

### 📃 Motivating Example

Explain files is now exported as json file, so you can display it with easy collapsing and expanding rows. 

### 💻 Use Cases

1. What do you want to use this for?
deeper and easier analysis of imported files
3. What shortcomings exist with current approaches?
Need to manuall (and prone to errors) parse text
5. What workarounds are you using in the meantime?
none

**Comment by MartinJohns** [comment] 2024-01-27 12:01
Duplicate of #46340 / #31566.

**Closed** 2024-02-01 01:27 UTC
Labels: Duplicate
