### ISSUE TITLE
Deducing return types from boolean arguments does not work with JSDoc and default argument values

### ISSUE THREAD

**Issue by Darker** [microsoft/TypeScript#59214] opened 2024-07-09 23:45 UTC
### 🔎 Search Terms

 - typescript template default argument
 - jsdoc infer template from default argument
      - I found this but it is closed so probably not the same issue: https://github.com/microsoft/TypeScript/issues/29401

### 🕗 Version & Regression Information

I don't know how to determine the exact version VSCode is using, but I just updated it...

### ⏯ Playground Link

https://www.typescriptlang.org/play/?jsx=0&filetype=js#code/C4TwDgpgBAKuEGEAWB7AlgYwgHhlCAHsBAHYAmAzlAEYooA2EAhiQDSwBiaAThcOzADKEDCnIA+KAF5Y+IqUpRg3AK7QA-Jx58oALljDR5ANwAoU6EhQAIiKYgAovPIVc7ABpziL2JJkwzUwB6ACoQ0ygQqAABYgBbMHomYigAb1oGZhIAXygANQAlCGAVbhIKADkVOOoIbgio6LAmbiY4tNsMeydvSmwMxhZ2QuLS8qqauvFc7lGyyura7igGmNmS+bS4SGR0LGwRjfHFuvYSE+52Pm40EgBzaYag0wAzFRIMYDQxKHWxgCEQLtMBAABR-eYTJbSJSqCAASjSESgKORKKCQRiwAoAFo0HcSChZmjfnMSFBzvR6GZsuYjDoKKgVPQyP8IFC6jCISRAcCsKDlGp4WZ6cAoIyUMzWRBBMpbncuWTeagQaCXkx6BQEWYMVAAIKfFQaqBIW7AfSi8VMll6zUoNkc7j6a7yqAAHwpF1MlolUttFHt7IuiqOyr2YOF5iAA

### 💻 Code

This problem occurs when trying to use JSDoc with TypeScript conditional types. The conditional type I created is the following:

```ts
type TypeChoice<T extends boolean, TFirst, TSecond> = T extends true ? TFirst : TSecond;
```

Application in plain javascript:
```javascript
/**
 * @template {boolean} VReturnsNumber
 * @param {VReturnsNumber} returnsNumber 
 * @returns {TypeChoice<VReturnsNumber, number, string>}
 */
// Error in the argument: 
// Type 'boolean' is not assignable to type 'VReturnsNumber'.
//   'boolean' is assignable to the constraint of type 'VReturnsNumber',
//   but 'VReturnsNumber' could be instantiated with a different subtype of constraint 'boolean'.ts(2322)
function returnByChoice(returnsNumber = true) {
    
    // @ts-ignore
    return null;
}

// These two work fine and show the desired type
const shouldBeNumber = returnByChoice(true);
const shouldBeString = returnByChoice(false);
// Actual hint: const shouldAlsoBeNumber: string | number
// default argument is not applied
const shouldAlsoBeNumber = returnByChoice();
```

### 🙁 Actual behavior

Error on the default argument:

```
Error in the argument: 
Type 'boolean' is not assignable to type 'VReturnsNumber'.
  'boolean' is assignable to the constraint of type 'VReturnsNumber',
  but 'VReturnsNumber' could be instantiated with a different subtype of constraint 'boolean'.ts(2322)
```

Additionally, the type is unknown if no argument is provided.

### 🙂 Expected behavior

 - The default argument should not cause an error. At the very least, it should not cause an error when the base type for the template is a primitive type
 - The default arguments should be used to infer the template if possible

### Additional information about the issue

I also tried to use this to suppress the error, but it kills the type inference in the process (the result type is always `number | string`):

```ts
type DecayExtends<T, X extends T> = T;
```

```javascript
/**
 * @template {boolean} VReturnsNumber
 * @param {DecayExtends<boolean, VReturnsNumber>} returnsNumber 
 * @returns {TypeChoice<VReturnsNumber, number, string>}
 */
function returnByChoice(returnsNumber = true) {
    
    // @ts-ignore
    return null;
}

```

**Comment by Darker** [comment] 2024-07-09 23:50
Looking more into the other issue I found, I can see that problem number 2 can be manually fixed by stating the default value. I also tried stricter template constraint, but the error still persists:
```javascript
/**
 * @template {true|false} [VReturnsNumber=true]
 * @param {VReturnsNumber} returnsNumber 
 * @returns {TypeChoice<VReturnsNumber, number, string>}
 */
function returnByChoice(returnsNumber = true) {
    // @ts-ignore
    return null;
}
```

The error still is:
```
Type 'boolean' is not assignable to type 'VReturnsNumber'.
  'boolean' is assignable to the constraint of type 'VReturnsNumber', but 'VReturnsNumber' could be instantiated with a different subtype of constraint 'boolean'.ts(2322)
```
In this case, it is clearly wrong, as there is no way `VReturnsNumber` could be instantiated to anything except `true` or `false`.

**Comment by MartinJohns** [comment] 2024-07-09 23:54
The error is correct, because generic arguments can be provided explicitly:

```typescript
returnByChoice<false>() // Why is returnsNumber true, when the type can only be false?
```

That is what is meant with
> but 'VReturnsNumber' could be instantiated with a different subtype of constraint 'boolean'

**Comment by RyanCavanaugh** [comment] 2024-07-09 23:56
Effectively a duplicate of #58977 

@MartinJohns you're my favorite "eager noobie" here btw 👍 (this is an inside joke, OP please disregard)

**Comment by Darker** [comment] 2024-07-09 23:58
If this is a duplicate would it make sense for me to create more specific issue regarding the workaround with `DecayExtends` not working? It seems that workaround should not lose the value type but it does. Or is that also known issue/has a reason for not working?

**Comment by RyanCavanaugh** [comment] 2024-07-10 00:02
`DecayExtends` isn't going to work either because, in the presence of zero candidates, the type parameter is resolved to its constraint (it's as if you had written `returnByChoice<true | false>`). It's more or less the same root cause.

**Closed** 2024-07-13 01:31 UTC
Labels: Duplicate
