### ISSUE TITLE
Output minified JavaScript?

### ISSUE THREAD

**Issue by tang-jason** [Microsoft/TypeScript#15197] opened 2017-04-14 18:34 UTC
Is there a road map to include minified JavaScript on save in compile option? It used to have in web essential which I thought it would be a very nice feature to bring it into TypeScript instead of using external tools like Grunt and Gulp.

**Comment by 304NotModified** [comment] 2017-04-14 18:43
duplicate of https://github.com/Microsoft/TypeScript/issues/8

**Closed** 2017-04-14 18:44 UTC
Labels: Duplicate
