### ISSUE TITLE
Dot notation for enum values

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#8964] opened 2016-06-04 08:57 UTC
Could we get Swift's dot notation for enum values?

It is very cumbersome to import an enum declaration and having to write them in function calls:
```ts
// ABC.ts
export const enum ABC {
  A, 
  B, 
  C,
}

export function testABC(abc: ABC) {
}

// test.ts
import { ABC } from './ABC';
import { testABC } from './ABC';

// it is very cumbersome to import ABC and type ABC.
testABC(ABC.A);
```

Swift introduced the most laziest way to write them. It would be good if TS could support it also. 
```ts
// test.ts
import { testABC } from './ABC';
testABC(.A);
```
Here is an another example with a switch statement, where you don't need to write `ABC` on every case:
```ts
import { ABC } from './ABC';
let abc: ABC;
switch (abc) {
   case .A:
        break;
   case .B:
        break;
   case .C:
        break;
}
```

**Comment by mhegazy** [comment] 2016-06-04 19:17
Duplicate of https://github.com/Microsoft/TypeScript/issues/1713

**Closed by mhegazy** 2016-06-04 19:17 UTC
