### ISSUE TITLE
Code won't compile due to invalid "always false" condition check

### ISSUE THREAD

**Issue by svallory** [microsoft/TypeScript#51350] opened 2022-10-29 13:45 UTC
# Bug Report

The code below won't compile because TS cannot detect that the variable is changed by the function called between asserts.

<img width="835" alt="image" src="https://user-images.githubusercontent.com/117560/198833973-9ea67ef2-ac1c-4a2e-bd64-981762a8577c.png">

### 🔎 Search Terms

tsc, compile, assert, error TS2367: This condition will always return

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about assert. I tested it on `3.8.3`, `4.8.4` and `typescript@next`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXygGdCQYMAKEADwAcYAueAIxxwhClQEpGiSzC8anQDcAKDHsM8MDjTSAvPAAM4sSnTY88ZDWBQMIAMJzUFLvADeY+DNMYA1A-EBfCX1IVZ8+Ar8qucV19QxN5ckCxDzJybzNffwBGQIB6FPgAWQBPO1B4AHMcEEEAC1IQIA)

### 💻 Code

```ts
declare function assert(expr: boolean): asserts expr;

let count = 0;

function updateCount() {
  count++;
}

assert(count === 0);
updateCount();
assert(count === 1);
```

### 🙁 Actual behavior

<img width="826" alt="image" src="https://user-images.githubusercontent.com/117560/198834061-d41d69bb-cdc0-4ad6-9217-a8c6d6218d2b.png">

### 🙂 Expected behavior

Code should compile

**Comment by MartinJohns** [comment] 2022-10-29 13:54
Duplicate of #9998.

**Closed** 2022-11-01 18:00 UTC
Labels: Duplicate
