### ISSUE TITLE
arguments length check is not smart enough

### ISSUE THREAD

**Issue by foisonocean** [Microsoft/TypeScript#24557] opened 2018-06-01 07:17 UTC
**TypeScript Version:**  2.9.0

**Search Terms:** 

**Code**

```ts
function foo(arg1: string): string;
function foo(arg1: string, arg2: string): string;
function foo(arg1: string, arg2: string, arg3: string): string;

function foo(str: string) {
    return str;
}

const arr = Array.from({ length: 2 }, (_, i) => `${i}`);

foo(...arr);

if (arr.length > 0 && arr.length <= 3) {
    foo(...arr);
}
```

**Expected behavior:**
call `foo` succeed.

**Actual behavior:**
got an error: `Expected 1-3 arguments, but got 0 or more.`

**Playground Link:**  
https://www.typescriptlang.org/play/index.html#src=function%20foo(arg1%3A%20string)%3A%20string%3B%0D%0Afunction%20foo(arg1%3A%20string%2C%20arg2%3A%20string)%3A%20string%3B%0D%0Afunction%20foo(arg1%3A%20string%2C%20arg2%3A%20string%2C%20arg3%3A%20string)%3A%20string%3B%0D%0A%0D%0Afunction%20foo(str%3A%20string)%20%7B%0D%0A%20%20%20%20return%20str%3B%0D%0A%7D%0D%0A%0D%0Aconst%20arr%20%3D%20Array.from(%7B%20length%3A%202%20%7D%2C%20(_%2C%20i)%20%3D%3E%20%60%24%7Bi%7D%60)%3B%0D%0A%0D%0Afoo(...arr)%3B%0D%0A%0D%0Aif%20(arr.length%20%3E%200%20%26%26%20arr.length%20%3C%3D%203)%20%7B%0D%0A%20%20%20%20foo(...arr)%3B%0D%0A%7D%0D%0A

**Related Issues:**

**Comment by andy-ms** [comment] 2018-06-01 14:49
Duplicate of #5331

**Closed** 2018-06-18 18:33 UTC
Labels: Duplicate
