### ISSUE TITLE
Either type not expanded for overload resolution

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#16412] opened 2017-06-09 19:33 UTC
From https://github.com/Microsoft/vscode/issues/28293

**TypeScript Version:**  2.4.0-20170609
**Code**

```ts
interface IFace {
	do(x: number): number
	do(x: string): string
}

function func(param: number | string, obj: IFace) {
	obj.do(param);
}
```

**Expected behavior:**
No compile errors. We have `do` overloads for both both types of params

**Actual behavior:**
Compile error. No overload found for `do` with argument of type `number | string`

// cc @roblourens

**Comment by mhegazy** [comment] 2017-06-09 20:00
duplicate of https://github.com/Microsoft/TypeScript/issues/14107

**Closed by mhegazy** 2017-06-09 20:00 UTC
Labels: VS Code Tracked
