### ISSUE TITLE
there are lot of import typescript errors with yarn2

### ISSUE THREAD

**Issue by budarin** [microsoft/TypeScript#36460] opened 2020-01-27 00:26 UTC
*TS Template added by @mjbvz*

**TypeScript Version**: 3.7.5

**Search Terms**
- yarn, yarn2
- pnp

---

- VSCode Version:  1.41.1
- OS Version: MacOs 10.15.2 (19C57)

Steps to Reproduce:

1. setup dependencies and their @types/ packages with yarn2 
2. open any typescript file with imports
3. some imports are marked as error as untyped while their @types are setup

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by orta** [comment] 2020-01-27 20:47
This can be considered a dupe of both https://github.com/microsoft/TypeScript/issues/28289 and https://github.com/microsoft/TypeScript/pull/35206

TS doesn't support the PnP style module resolution unless you go through the yarn pnpify tooling.

**Closed** 2020-01-28 11:35 UTC

**Comment by macabeus** [comment] 2020-02-19 18:37
@orta Thank you for reply, but is there some plan to TS support PnP?
