### ISSUE TITLE
Minor: type aliases not expanded in indexer parameter type checks

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#4964] opened 2015-09-25 09:56 UTC
Minor, but still:
```typescript
type nn = number;
class A {
    [s: nn]: number; // an error here, but it shouldn't be an error
}
```

**Comment by DanielRosenwasser** [comment] 2015-09-25 21:38
Is this a duplicate of #1778?

**Comment by danquirk** [comment] 2015-09-25 21:40
Yep, and I triaged each one differently, good job me

**Closed by danquirk** 2015-09-25 21:40 UTC
Labels: Bug
