### ISSUE TITLE
 Error TS2348: Value of type 'typeof App' is not callable.

### ISSUE THREAD

**Issue by shaikhspear16** [Microsoft/TypeScript#9023] opened 2016-06-08 13:04 UTC
Ionic 2 new project error.

I am creating a new project with Ionic 2 and Typescript on Windows 10 pc.

with the following command:

ionic start MyIonic2Project tutorial --v2 --ts

I get the following error when performing ionic serve

TypeScript error: app/app.ts(8,2): Error TS2348: Value of type 'typeof App' is not callable. Did you mean to include 'new'?

Shows a blank screen on ionic serve and android deployment. 

In chrome console I get the following error -

app.js:29 Uncaught TypeError: Cannot read property 'backButton' of undefined

**Comment by luisfurnas** [comment] 2016-06-08 15:28
A workaround for this issue is to use Component decorator instead of App, and use ionicBootstrap to bootstrap your Ionic app

**Comment by ayanthika** [comment] 2016-06-08 18:31
In your package.json file where it says  "ionic-angular": "^2.0.0-beta.7", if there is a caret in front of the version you are using take out the caret so it defaults to whatever version you are using. If not it tries to get the latest version

**Comment by joshgarwood** [comment] 2016-06-08 19:09
I am getting this as well, and have this in my package.json: "ionic-angular": "2.0.0-beta.8"

Am I missing something?

**Comment by sebagon** [comment] 2016-06-08 19:22
As @ayanthika suggested, make these changes to app.ts for a workaround:

- add this line at the beginning
`import {ionicBootstrap} from 'ionic-angular';`
- Change @App to @Component
- add this line at the end
`ionicBootstrap(MyApp);`

**Comment by joshgarwood** [comment] 2016-06-08 19:25
Thanks @sebagon !  Is this the proper way to code App components now, or is this just a workaround while the root cause is actually fixed?

Thanks!

**Comment by sebagon** [comment] 2016-06-08 19:26
@joshgarwood just a workaround while the root cause is fixed

**Comment by mhegazy** [comment] 2016-06-08 21:11
should this be reported on https://github.com/driftyco/ionic/issues instead?

**Comment by sebagon** [comment] 2016-06-09 12:59
@mhegazy I think so

**Comment by iignatov** [comment] 2016-06-15 22:14
@joshgarwood This is the proper way _(starting with Ionic 2 `beta.8`)_ - see the [changelog](https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#200-beta8-2016-06-06) for details.

### Here's the related issue in the Ionic repo: https://github.com/driftyco/ionic/issues/6917

@mhegazy I guess that this issue can be closed/locked so that the discussion continues over there.

**Comment by mhegazy** [comment] 2016-06-16 00:16
thanks! closing.

**Closed by mhegazy** 2016-06-16 00:16 UTC
Labels: External, Question
