### ISSUE TITLE
Type narrowing of union types by type predicate narrows to only first branch of union

### ISSUE THREAD

**Issue by Pajn** [microsoft/TypeScript#44754] opened 2021-06-26 09:04 UTC
# Bug Report

### 🔎 Search Terms

union type, type predicate

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "Common Bugs That Aren't Bugs"

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210626#code/C4TwDgpgBAYg9nKBeKBvA1gSwHYBMBcUA5AGYJEC+AUDsBAE4kCGAxtAEJP0A8AKslACC2EAD40WPISIAjLkQA0UAG5MANgFcIhXtVCQonAF4CMOAsTlHKVfdGEgB8RAB9DXKG+NUqJDdhZgTDhsKEwAZ2c5egAKVU1tKH90bDgAd2wASkJ4rTDw2ARPdx5ncVQqKCqoeghgDXpQuzgSFXU8pE7iOBkAKwhAoigAMmGoGLj26CYCphFMgH4AOklcZC7Sck83SYSoGf355dX1lFl5TKpqKjU6tr2UMylLJmsKfYKHH0xWmIiori7LSZTJoSrVW7AfYCXIQFbmU7EMhwIjgqoLe5aeF4NFQHJTJaw7G4K5AA)

### 💻 Code

```ts
type Foo = {kind: 'foo'}
interface Bar<T = Any> {kind: 'bar', value: T}
type Baz = {kind: 'baz'}
type Any = Foo | Bar | Baz

function isFoobar(value: unknown): value is Foo | Bar<Foo> {
    return typeof value === 'object' && ((value as any)?.kind === 'foo' || (value as any)?.kind === 'bar')
}

let value = {kind: 'baz'} as Any

if (isFoobar(value)) {
    let a = value.kind === 'foo'
    ? value.kind
    : value.value.kind
}
```

### 🙁 Actual behavior & 🙂 Expected behavior

`isFoobar` narrows the type to only `Foo` but should narrow it to the specified `Foo | Bar<Foo>`. It seems to be related to the combination of the generic parameter and the circularity because I can not find a way to simplify it further.

**Comment by andrewbranch** [comment] 2021-06-28 16:09
Duplicate of https://github.com/microsoft/TypeScript/issues/31156

**Closed** 2021-06-30 18:00 UTC
Labels: Duplicate
