### ISSUE TITLE
Duplicate identifiers

### ISSUE THREAD

**Issue by bartvanderwal** [Microsoft/TypeScript#6489] opened 2016-01-14 20:20 UTC
I'm experiencing a lot of `Duplicate identifiers` errors. I see around 80 similar issues, but I don't see a clear and workable solution anywhere. Not on [stackoverflow](http://stackoverflow.com/questions/31322525/typescript-confusing-duplicate-identifier-error-message) neither.

I'm using current Typescript, e.g. tsc v1.7.5. The `exclude` option in `tsconfig` does not seem to be respected, as I get around a 100 `Duplicate identifier` issues when compiling. All in the `typings` folders. See below. Before I had similar errors in `node_modules` files, but they seem to have disappeared after adding `node_modules` in my tsconfig's exclude. But similarly adding `typings` (and `client/typings`) does NOT fix this issue.

I'm currently using - only - this in a few of my own `.ts`. But most don't have any at all. At least NOwhere am I referencing int

     /// <reference path="typings/tsd.d.ts" />

Can you give advice how to solve this? Or is this a temporary bug to be fixed?

I already switched to Visual Studio Code and manual compiling instead of compile on save in Visual Studio with Node Tools for VS, because NTVS kept stalling the UI for dozens of seconds, killing any programmer flow :cry: . I find this typescript potentially very cool and powerful, but practically currently a bit unworkable :sob:.

**tsd.json**

```tsd.json
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": false,
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": true,
        "target": "es5"
    },
    "exclude": [
        "node_modules",
        "bower_components",
        "typings",
        "client/typings"
    ]
}
```

**Sample from error output**

```Errors
client/typings/underscore/underscore.d.ts(53,3): error TS2374: Duplicate string index signature.
client/typings/underscore/underscore.d.ts(1693,2): error TS2300: Duplicate identifier 'templateSettings'.
client/typings/underscore/underscore.d.ts(3628,2): error TS2300: Duplicate identifier 'export='.
typings/mocha/mocha.d.ts(8,5): error TS2300: Duplicate identifier 'slow'.
typings/mocha/mocha.d.ts(11,5): error TS2300: Duplicate identifier 'timeout'.
typings/mocha/mocha.d.ts(14,5): error TS2300: Duplicate identifier 'ui'.
typings/mocha/mocha.d.ts(17,5): error TS2300: Duplicate identifier 'globals'.
typings/mocha/mocha.d.ts(20,5): error TS2300: Duplicate identifier 'reporter'.
```

**Comment by mhegazy** [comment] 2016-01-14 20:35
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/6475 (no pun intended :))

**Comment by mhegazy** [comment] 2016-01-14 20:35
can you provide more details on your setup?

**Comment by bartvanderwal** [comment] 2016-01-15 00:10
Setup? What do you want to know, besides what I specified already?

It's a Node project with angular on the frontend. Angular 1.x, NOT 2, like #6475. But like that issue I'm also using project both on server and on client side. And the errors seem to come from  *mocha, node). I actually don't know why the `node.d.ts` is on the client side also, so I removed that for now. And Mocha also for now (only serverside tests so far). But there is still underscore that we're using on both ends. I even already tried to use lodash on client and underscore on server, but that actually gives the same nameclashes (logical in hindsight, they're API compatible).

It ran/runs fine in Visual Studio, but when I run it with NodeMon (via Grunt task) I get this sh@#load of 'duplicate'.

That seems to give these issues. I'm NOT using browserify, so to keep things simple for now, I have not deduplicated them. I just want one used with AMD. Or we're actually still on a completely flat structure, using no ES modules client side (only using Angular's modules).

Everything is in one project.

I could try to make a more minimal recreation and put it it . That'll take some time though. I was hoping I could be productive sooner :).

**Comment by mhegazy** [comment] 2016-01-15 00:14
duplicate declarations means you have two declarations for the same entity :). so you have two references to mocha.d.ts, removing one should stop the errors. 

If i can look at the project i might have a better answer.

**Comment by bartvanderwal** [comment] 2016-01-15 00:29
Okay. Well that's a clear statement. There ARE 2 `tsd.d.ts`files, one in `typings/` folder (for server-side) and one in `client/typings`.

As explained I already remove `node` and `mocha` projects from the client, and if I now also remove the included underscore typing:

    /// <reference path="underscore/underscore.d.ts" />

from the `client/typings/ts`, then the compile errors I mentioned are gone.

I then don't get `unknown type` or other similar compile errors in the client side ts as I expected. So I guess it then just uses the definitions from the root `typings` folder. Thought there are NO references to it (e.g /// like before).

I would expect that I would then have to use something like

    /// <reference path="../typings/tsd.d.ts" />
    /// <reference path="../../typings/tsd.d.ts" />

to reference both client and server side scripts.

**Comment by bartvanderwal** [comment] 2016-01-15 00:47
@mhegazy can I have two tsconfig files in one project? One for server and one for client? It's unclear to me from the documentation.

Because the server should have `CommonJS` target. The client side is just 'globals' for now, though target `AMD` seems the only option available for client side. But for now I'm reluctant to take on yet another dependency on requirejs, as the project feels so flakey.

**Comment by amb-it-ion** [comment] 2016-02-18 13:38
This error is so annoying, why can I not just turn it off? I can effectively no longer use the tsc error messages in my IDE directly, and instead have to rely on my gulp output.

**Comment by mhegazy** [comment] 2016-02-18 18:30
@bartvanderwal sorry for the delay, just saw this now. 

With TypeScript 1.8, you should be able to have multiple TSConfig files in your project, and it should split your files into islands. see https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#improved-support-for-tsconfigjson-in-visual-studio-2015 for more details.

**Closed** 2016-02-20 05:25 UTC
Labels: Duplicate

**Comment by LordDelacroix** [comment] 2017-04-04 14:23
I'm getting these same errors in a classic ASP.NET 4.6.1 solution that doesn't even USE  Typescript when compiling under VS2017!!
