### ISSUE TITLE
A problem with type checking in `if` statement.

### ISSUE THREAD

**Issue by Arfey** [Microsoft/TypeScript#31059] opened 2019-04-22 14:22 UTC
**TypeScript Version:**  3.4.2

**Search Terms:**
A problem with type checking in `if` statement.

**Code**

```ts
{({ loading, data, error }) => {
    const canShow =
      !loading &&
      !error &&
      data &&
      data.recommendedPrice &&
      data.recommendedPrice.price;
    if (canShow) {
      return (
        <RecommendedPrice
          price={data.recommendedPrice.price}
          isActive={isActive}
        />
      );
    }

    return null;
}}
```

**Expected behavior:**
all is fine

**Actual behavior:**
```
object is possibly 'null'
```

But when i write something like that all is fine

```ts

{({ loading, data, error }) => {
    if (
      !loading &&
      !error &&
      data &&
      data.recommendedPrice &&
      data.recommendedPrice.price
    ) {
      return (
        <RecommendedPrice
          price={data.recommendedPrice.price}
          isActive={isActive}
        />
      );
    }

    return null;
}}
```

**Comment by ahejlsberg** [comment] 2019-04-22 14:49
Duplicate of #12184.

**Closed** 2019-04-24 18:00 UTC
Labels: Duplicate
