### ISSUE TITLE
installer - add option to update system path to latest Typescript

### ISSUE THREAD

**Issue by voltcode** [Microsoft/TypeScript#4923] opened 2015-09-22 07:11 UTC
It would save a bit of hassle (especially when updating all PCs in a team) if Typescript VS installer asked about PATH update to the latest Typescript bin directory (ie. remove old Typescript from PATH , add new Typescript to PATH).

Managing all developers and asking them to update the PATH manually leads to problems - incoherent versions of command line tools can lead to erratic compilation errors between team members.

**Comment by DanielRosenwasser** [comment] 2015-09-22 08:09
Looks like a duplicate of #2068.

**Closed** 2015-09-22 18:24 UTC
