### ISSUE TITLE
Type narrowing should be able to make generics irrelevant

### ISSUE THREAD

**Issue by ShacharHarshuv** [microsoft/TypeScript#54601] opened 2023-06-10 21:09 UTC
# Bug Report

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAShBmAeAKgPigXigbwFBSgDcBDAGwFcIAuKZKAHygDtzTSBuXAX113nKYBjYAEsA9kyiCJhCACdgcJMgA0UAKqoAFHIQ0lKVGsFlSAI2KCA1jS3AayAJSZ06x-oSJNOfFBHwoHQQAOhIKaAxI5lZSZzwCAl1gcjlJXXhOAh5fJJTJeISwyhoTNgtrIPhQskpHFV8eLiA)

### 💻 Code

```ts
type Ref<T> = {
  value: T | null;
}

function convertRef<T, U>(ref: Ref<T>, callback: (t: T) => U): Ref<U> {
  if (ref.value === null) {
    return ref; // error: Type 'Ref<T>' is not assignable to type 'Ref<U>'
  }

  return {
    value: callback(ref.value),
  }
}
```

### 🙁 Actual behavior

There is an error on: Type 'Ref<T>' is not assignable to type 'Ref<U>'

### 🙂 Expected behavior

Because of the if condition, ref value should be narrowed to `{ value: null }`, which should be assignable to `Ref<U>`, so there shouldn't be any error. 

(The ticket name might not be the best, feel free to rename if needed)

**Comment by fatcerberus** [comment] 2023-06-10 21:19
You’re essentially asking for higher-order behavior whereby the compiler could recognize that a `.value` of `null` means *this particular value* is assignable to any instantiation of `Ref` regardless of the type argument, but that’s not how type narrowing works.  You have a `Ref<T>` when you start, you still have a `Ref<T>` afterwards, which is not typewise compatible with `Ref<U>`.

**Comment by ShacharHarshuv** [comment] 2023-06-10 21:22
Couldn't it be possible to narrow `Ref<T>` to `Ref<never>` so it's assignable to `Ref<U>`?

**Comment by xuld** [comment] 2023-06-11 10:45
` { value: null }` should not be assignable to Ref<U> because U can be instantiated with other types.
If your code compiles without error , then the type of result is confusing, for example:
```ts 
var result = convertRef<1, 2>({ value: null  }, t => 2)
```

**Comment by jcalz** [comment] 2023-06-11 11:44
Duplicate of (or variant of) #42384

**Comment by fatcerberus** [comment] 2023-06-11 14:15
Well, #42384 is probably a prerequisite, but this one is more “have TS recognize when a subset of `Foo`s are assignable to `Bar`” which is a whole different can of worms.

**Comment by ShacharHarshuv** [comment] 2023-06-11 15:26
> ` { value: null }` should not be assignable to Ref because U can be instantiated with other types. If your code compiles without error , then the type of result is confusing, for example:
> 
> ```ts
> var result = convertRef<1, 2>({ value: null  }, t => 2)
> ```

I'm not sure I understand. The inferred type of the result is correct. There would be no bug in your code. null is always a valid value based on the definition of `Ref`

**Comment by ShacharHarshuv** [comment] 2023-06-11 15:28
> Duplicate of (or variant of) #42384

I read the other issue but I don't understand enough about the TS compiler to say if fixing it would indeed also fix this issue.

**Comment by jcalz** [comment] 2023-06-11 15:41
Without #42384, `ref.value` being narrowed to `null` doesn’t cause `ref` to be narrowed to `{value: null}` automatically.  If that were changed, then you would presumably be able to return the narrowed `ref` as a value of type `Ref<T>`.

**Comment by rhazarian** [comment] 2023-06-11 21:30
Consider this code if the function worked as you wanted in your example.

```
const numberRef: Ref<number> = {
    value: null,
};
const numberRefConvertedToStringRef = convertRef(numberRef, () => "");
numberRefConvertedToStringRef.value = "hello world";
const x = numberRef.value; // inferred type of x is number, but actually it is a string
```

I don't think that this sort of narrowing should be possible, maybe except when the object is readonly.

**Comment by fatcerberus** [comment] 2023-06-11 22:10
@rhazarian TS generally doesn’t account for object mutability in assignability checks anyway; this wouldn’t be any different in that regard.  `{ foo: number }` is already assignable to `{ foo: unknown }`, for example.

**Comment by ShacharHarshuv** [comment] 2023-06-11 22:27
> I don't think that this sort of narrowing should be possible, maybe except when the object is readonly.

That's a very good point. However - it doesn't work even if the object IS readonly.

**Comment by RyanCavanaugh** [comment] 2023-06-12 17:21
The proposed behavior is, in general, not sound.
```ts
type Ref<T> = {
  value1: T | null;
  value2: T | null;
}

function convertRef<T, U>(ref: Ref<T>, callback: (t: T) => U): Ref<U> {
  if (ref.value1 === null) {
    return ref;
  }
}

const m = convertRef({value1: null, value2: ""}, () => 32);
m.value2; // number | null, is string
```

**Comment by ShacharHarshuv** [comment] 2023-06-12 19:44
@RyanCavanaugh As @fatcerberus said, according to what I propose, your example should still throw an error, because `{value1: null, value2: T | null}` is not assignable to `{value1: U | null, value2: U | null}`. While in my example `{value: null}` is actually assignable to `{value: U}`.

> detecting subsets of types that don't use the type parameter

I'm not sure I understand why it's that complicated. In my understanding, the if narrows the type to `{value: null}` and today, the following will not give an error:

```ts
type Ref<T> = {
  value: T | null;
}

function convertRef<T, U>(ref: Ref<T>, callback: (t: T) => U): Ref<U> {
  if (ref.value === null) {
    return { value: null }; // hard coded for the example, not giving an error
  }

  return {
    value: callback(ref.value),
  }
}
```

The problem is the type narrowing itself, not the assignability checks.  Actually, it turns out you don't need generic to reproduce the problem:

```
declare const ref: { value: unknown };

if (ref.value === null) {
  const x: { value: null} = ref; // gives error
}
```

However, with simple primitives, it works:

```ts
declare const value: unknown;

if (value === null) {
  const x: null = value;
}
```

**Comment by jcalz** [comment] 2023-06-12 19:47
*looks meaningfully at #42384*

**Comment by RyanCavanaugh** [comment] 2023-06-12 20:26
Right, for all cases *where this works* you're actually looking at something like #42384

**Comment by ShacharHarshuv** [comment] 2023-06-12 20:44
OK so yes, I think you're correct that #42384 will solve it. I think this ticket can be closed as duplicate.

**Closed** 2023-06-14 23:42 UTC
Labels: Duplicate
