### ISSUE TITLE
Type assertions of keyof types not guarded

### ISSUE THREAD

**Issue by miguel-leon** [microsoft/TypeScript#31389] opened 2019-05-14 08:24 UTC
Hi,

If type assertions of non assignable types is a compilation error, for example:
```typescript
const x = '99' as number; // error TS2352
```

shouldn't the following cause an error as well?
```typescript
interface I {
	att: any;
}
const y = 'typo' as keyof I;
```
The type inferred for `y` is as expected `keyof I` but its value is wrong.

Thanks, regards.

PS: please nobody say add `const y: keyof I`. That is not the point and can't be done in some cases such as a generic argument type.

**Comment by jack-williams** [comment] 2019-05-14 08:33
Duplicate of #14156

**Closed** 2019-05-20 18:00 UTC
Labels: Duplicate
