### ISSUE TITLE
Feature request: infer type predicates

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#17924] opened 2017-08-19 08:57 UTC
**TypeScript Version:**  2.4.2

It would be really nice if certain boolean-returning functions could be inferred to be type predicates. For example, in RxJS one of the signatures for the `filter` method is

```ts
function filter<T, S extends T>(
  this: Observable<T>,
  predicate: (value: T, index: number) => value is S,
  thisArg?: any
): Observable<S>;
```

It's very useful to filter on an observable and thereby have the resulting observable's type be refined:

```ts
type Action =
  | { type: 'FOO'; fooField: number }
  | { type: 'BAR'; barField: string }

action$
  .filter(action => action.type === 'FOO')
  .mergeMap(({ fooField }) => ...)
```

however this won't work because the lambda `action => action.type === 'FOO'` is not inferred to have the type `(action: Action) => action is { type: 'FOO'; fooField: number }`, even though the compiler should know this is true.

**Comment by aluanhaddad** [comment] 2017-08-19 16:45
See also https://github.com/Microsoft/TypeScript/issues/12798

**Comment by mhegazy** [comment] 2017-08-22 00:59
Duplicate of https://github.com/Microsoft/TypeScript/issues/5101, https://github.com/Microsoft/TypeScript/issues/14891. Please see https://github.com/Microsoft/TypeScript/issues/5101#issuecomment-145693151 for more details. if you do have a proposal in mind on how this can be accomplished for the general case feel free to post it to #5101.

**Comment by mhegazy** [comment] 2017-09-05 17:05
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-05 17:05 UTC
Labels: Duplicate
