### ISSUE TITLE
Is it possible to make EventTarget a generic interface?

### ISSUE THREAD

**Issue by masx200** [microsoft/TypeScript#49770] opened 2022-07-03 14:08 UTC
# lib Update Request
Is it possible to make EventTarget a generic interface?

## Configuration Check

My compilation *target* is `ESNEXT` and my *lib* is `the default`.

## Missing / Incorrect Definition
```ts
interface EventTarget<T extends Record<string, Event> = Record<string, Event>> {
    addEventListener<K extends keyof T>(type: K, listener: (this: EventTarget<T>, ev: T[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, callback: EventListenerOrEventListenerObject | null, options?: AddEventListenerOptions | boolean): void;
    dispatchEvent(event: T[keyof T]): boolean;
    dispatchEvent(event: Event): boolean;
    removeEventListener<K extends keyof T>(type: K, listener: (this: EventTarget<T>, ev: T[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, callback: EventListenerOrEventListenerObject | null, options?: EventListenerOptions | boolean): void;
}
declare const EventTarget: {
    new <T extends Record<string, Event> = Record<string, Event>>(): EventTarget<T>;
    prototype: EventTarget;
};
class TestTarget extends EventTarget<{
    complete: Event & {
        id: number;
    };
    message: MessageEvent;
}> {
constructor() {
        super()
    }
}
```

**Comment by MartinJohns** [comment] 2022-07-03 14:08
Duplicate of #43477.

**Closed** 2022-07-08 18:00 UTC
Labels: Duplicate
