### ISSUE TITLE
Static getters / setters can have incorrect `this` binding 

### ISSUE THREAD

**Issue by matthewjh** [Microsoft/TypeScript#4327] opened 2015-08-15 15:07 UTC
````typescript
class Base {
  static getCorrectFoo(): any {
     return this;
  }

   static get foo(): any {
      return this;
   }
}

class Inherited extends Base {}
````

```typescript
Base.foo === Base;
Base.getCorrectFoo() === Base;

Inherited.foo === Base; /// Should be `Inherited`
Inherited.getCorrectFoo() === Inherited;
````

I believe this is because the `foo` getter will be defined via `Object.defineProperty(Base, {..})`, which hard-wires `this` to `Base` within the getter, rather than binding as expected to `Inherited` in `Inherited.foo`.

**Comment by matthewjh** [comment] 2015-08-15 16:27
I have a fix in #4328, I just need some advice on testing it. Please take a look.

**Comment by DanielRosenwasser** [comment] 2015-08-16 04:07
This is actually a duplicate of #1520. See http://typescript.codeplex.com/workitem/2324 for the rationale/workaround, and as @danquirk mentions on https://github.com/Microsoft/TypeScript/issues/1868#issuecomment-72256645, I don't think we've changed our position on it.

**Comment by matthewjh** [comment] 2015-08-16 13:22
OK, so I'll (continue to) use my custom `__extends` so that my code functions as expected. Feels dirty as hell that I should have to do that, though.

Thanks Daniel!

**Closed** 2015-08-17 20:14 UTC
Labels: Duplicate
