### ISSUE TITLE
While recognizing server components using type script next (version 13) gives an error

### ISSUE THREAD

**Issue by bloodgroup-cplusplus** [microsoft/TypeScript#53431] opened 2023-03-22 04:03 UTC
While recognizing server components using type script next (version 13) gives an error But when i change my file type to jsx instead of tsx the components work fine for instance in the snippet below
![image](https://user-images.githubusercontent.com/81256027/226798886-8b9aecb2-faea-4178-9380-b1d13db6df62.png)

On renaming  layout.tsx to layout.jsx, the error is resolved.

![Screen Shot 2023-03-22 at 09 31 59](https://user-images.githubusercontent.com/81256027/226799327-c7c7ee48-255b-443d-a50d-b2c2ad82e863.png)

More details about the error on this youtube video (https://www.youtube.com/watch?v=4xduSsxa5Os) timestamp (34:56) . The video is a month old and don't know if this issue's been resolved yet.

**Comment by MartinJohns** [comment] 2023-03-22 06:40
You forgot to fill out the issue template for bug reports. In the end this is a duplicate of #21699.

**Closed** 2023-03-22 17:08 UTC
Labels: Unactionable
