### ISSUE TITLE
Upgrades to Object key correctness and type inference.

### ISSUE THREAD

**Issue by UselessMnemonic** [microsoft/TypeScript#52237] opened 2023-01-14 05:01 UTC
# Suggestion

Add new type syntax, including a `!` modifier for optional types and a concept for `closed` types, for more succinct type building and checking.

## 🔍 Search Terms

for-in, infer, exact, closed, type

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### Part 1: Strictly Optional types and the `!` modifier.
The `!` modifier can be affixed to properties instead of `?` indicating those keys are optional, but may not be set to `undefined`, only `delete`-ed. Take this sample:

```ts
type Person = {
  name: string,
  title!: string
}
```

No strictly optional property may specify `undefined` in its type, unlike an optional property which allows it. However, the final type is still a union of the property type and `undefined`.

Instances of `Person` can now be defined either with `title` omitted, or definitely some `string`.
```ts
const person: Person = { name: "Chris" }; // good
const person: Person = { name: "Chris", title: undefined }; //bad
```

Additionally, if authors wish to remove the `title` property from a `Person`, they must `delete` it, rather than setting it to `undefined`.

```ts
person.title = undefined; // bad
delete person.title; // good
```

In mapped types, `!` is expressed quite naturally as would a `?`:

```ts
type AltPerson = {
  [P in keyof Person]!: string
}

type AltPerson = {
  name!: string,
  title!: string
}
```

A type with strictly optional properties may freely be cast into one with plainly optional properties, but the opposite will not always be true. The author will have to iterate over the object's properties and ensure none are set to `undefined`.

For convenience, a `StrictlyOptional<T>`  type can be used to convert optional `?` properties to strictly optional `!` properties.

```ts
type AltPerson = StrictlyOptional<Partial<Person>>
```

`StrictlyOptional<T>` must not effect non-optional properties.  `Partial<T>` applied to a strictly optional type `T` should convert all its strictly optional properties to plainly optional.

If the author wishes to modify a strictly optional property arbitrarily, a cast to `any` will not suffice. The author must cast to `unknown` first, as to signal to the compiler a desire to evade `!` type checking.

A `readonly` property of type `T` should remain `readonly` in `StrictlyOptional<T>`. `satisfies` fails if attempting to satisfy a strictly optional property with a plainly optional one.

### Part 2: `closed` and `Closed<T>` types.
Often we create objects guaranteed not to deviate from an exact set of properties. To encourage strict adherence, a new `closed` modifier can be used to marks types for objects whose property set will never differ from the defined interface.

A `closed` type can be declared as follows:

```ts
closed type Preferences = {
  useSystemTheme: boolean,
  forceDarkTheme: boolean,
  language: string
}
```

Instances of `Preferences` must contain only those properties declared in `Preferences`.
Already when constructing a `Preferences`, the author must not declare more keys than strictly necessary.

```ts
const myPreferences: Preferences = {
  useSystemTheme: true,
  forceDarkTheme: true,
  language: "Esperanto",
  color: "green" // bad
}
```

But instances of closed types cannot be cast to other types that do not have the same properties. Casting `myPreferences as Record<string, any>` becomes invalid in `closed` contexts.

Objects can become closed either with the `closed` keyword or using the `Closed<T>` type, only if their properties can be inferred in advance:

```ts
const record = myPreferences as Record<string, any>; // bad
const record = { foo: "Foo", bar: "Bar" } as closed; // good
// typeof record = closed { foo: "Foo", bar: "Bar" }

const tuple = [1, 2, 3] as closed; // good
// type of record = closed [ 1, 2, 3 ]

const other: Closed<[string, number]> = ["<", 3];
```

A `readonly` property of `T` should remain `readonly` in `Closed<T>`. A frozen object of type `T` could be typed as `Readonly<Closed<T>>`  or in shorthand `Frozen<T>`.

## 💻 Use Cases

A combination of `Closed<T>` and `!` can help narrow down types in places such as for-in loops where iterating over a *known* key set is still treated as unsafe.

In one of my projects, I use a reducer inside of a react hook to update a set of user preferences from within the app. My reducer looks like this:

```ts
type Preferences = {
  readonly option1: string,
  ...
  readonly optionN: string
}

function tryWritePreference(key: keyof Preferences, value: Preferences[typeof key]);

function reducePreferences(state: Preferences, partial: Partial<Preferences>) {
  for (const k in partial) {
    // k is a string
    tryWritePreference(k as keyof Preferences, partial[k as keyof Preferences]!);
    // partial[k] is guaranteed from the rest of the project to be defined, as `partial` has really only strictly optional keys
  }
  return {...state, ...partial};
}
```

`Preferences` is not strictly a Record<string, string>, but casting state or partial to such would only move the problem of type assertions. A construct like `Closed<T>` in conjunction with `!` would not only provide needed hints to the compiler, but also help propagate certain guarantees as to ensure the correct use of `reducePreferences` in my app.

A better definition could be the following:
```ts
type Preferences = {
  readonly option1: string,
  ...
  readonly optionN: string
}

function tryWritePreference(key: keyof Preferences, value: Preferences[typeof key]);

function reducePreferences(state: Preferences, partial: StrictlyOptional<Partial<Preferences>>) {
  for (const k in partial) {
    // k is still string with the added bonus that partial[k] is always defined
    tryWritePreference(k as keyof Preferences, partial[k]);
  }
  return {...state, ...partial};
}
```

This definition also helps me ensure that only definitely not undefined properties end up in `partial`.
Additionally, the concept of `closed` types can further hint that it is unacceptable to give `partial` any more properties than expected. Thus, the final script becomes:

```ts
closed type Preferences = {
  readonly option1: string,
  ...
  readonly optionN: string
}

function tryWritePreference(key: keyof Preferences, value: Preferences[typeof key]);

function reducePreferences(state: Preferences, partial: StrictlyOptional<Partial<Preferences>>) {
  for (const k in partial) {
    // k is now definitely "option1" | ... | "optionN"
    tryWritePreference(k, partial[k]);
  }
  return {...state, ...partial};
}
```

**Comment by fatcerberus** [comment] 2023-01-14 05:08
Re: Strictly optional properties: you can already use `exactOptionalPropertyTypes` to prevent assigning `undefined` to optional properties.
Re: Closed types - This sounds like exact types, which is a duplicate of #12936.

**Closed** 2023-01-22 18:00 UTC
Labels: Duplicate
