### ISSUE TITLE
Unable to assign a boolean argument to a parameter that accepts both true and false

### ISSUE THREAD

**Issue by taxnuke** [microsoft/TypeScript#44392] opened 2021-06-02 17:37 UTC
# Bug Report

### 🔎 Search Terms

function overloads boolean not assignable to parameter of type true false

### 🕗 Version & Regression Information

v4.4.0-dev.20210601 

This is the behavior in every version I tried, and I reviewed the [FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ)

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABDMYCmAnAFMANgQwHMAuRKDENASlLBAFsAjTAbgChRJYFlVMcCJRMHy4AztVJjyKQu07R4SFOmx4ipRnDi40+MDUTSMsxAB9EdJpkQBvNokeIMaKCAxJ1hRAH5EARkRSAHIAQWD2AF82DnBFHjgQKH4vUnJKQytmDHk47iRE5LVBUhFxSSMZMDlYriVEQpSSxC0dPQMpKu8LLJt7J2dXd2U+YqIqKKA)

### 💻 Code

This will not compile

```ts
function inner(flag: true): number;
function inner(flag: false): string;
function inner(flag: boolean): string | number {
    return flag ? 1 : 'A';
}

function outer(flag: true): number;
function outer(flag: false): string;
function outer(flag: boolean): string | number {
    return inner(flag);
}
```

Unless I throw in a conditional statement that effectively _narrows_ the boolean `flag` into `true` and `false` inside respective branches.

```ts
function inner(flag: true): number;
function inner(flag: false): string;
function inner(flag: boolean): string | number {
    return flag ? 1 : 'A';
}

function outer(flag: true): number;
function outer(flag: false): string;
function outer(flag: boolean): string | number {
    if (flag) {
        return inner(flag);
    }

    return inner(flag);
}
```

### 🙁 Actual behavior

```
No overload matches this call.
  Overload 1 of 2, '(flag: true): number', gave the following error.
    Argument of type 'boolean' is not assignable to parameter of type 'true'.
  Overload 2 of 2, '(flag: false): string', gave the following error.
    Argument of type 'boolean' is not assignable to parameter of type 'false'.(2769)
```

### 🙂 Expected behavior

Compiles fine

**Comment by fatcerberus** [comment] 2021-06-02 17:43
The implementation signature doesn’t count for purposes of overload resolution.

**Comment by MartinJohns** [comment] 2021-06-02 17:43
Duplicate of #40827.

**Comment by DanielRosenwasser** [comment] 2021-06-03 21:33
You can rewrite as

```ts
function inner(flag: true): number;
function inner(flag: false): string;
function inner(flag: boolean): string | number
function inner(flag: boolean): string | number {
    return flag ? 1 : 'A';
}

```

**Closed by DanielRosenwasser** 2021-06-03 21:33 UTC
Labels: Duplicate

**Comment by Bezmehrabi** [comment] 2022-03-14 19:56
Hi Guyz,
I have the following problem:
```ts
function inner(flag: true): number;
function inner(flag: false): string;
function inner(flag: boolean): string | number
function inner(flag: boolean): string | number {
    return flag ? 1 : 'A';
}

// works fine.
let r = inner(true)


function func(b: boolean) {
    return inner(b)
}

// doesn't work as I want it, the return type is "string | number" but it should be "string"
let r2 = func(true)
```

how can I fix that?

**Comment by MartinJohns** [comment] 2022-03-14 20:17
@Bezmehrabi Repeat the overloads on your `func` function. Also, you better ask such questions on StackOverflow.
