### ISSUE TITLE
More concise way to specify an optional return type

### ISSUE THREAD

**Issue by angryziber** [microsoft/TypeScript#41902] opened 2020-12-09 19:40 UTC
## Suggestion

TypeScript already supports optional parameters and fields with a question mark.
Why not extend this feature to function/getter return types.

## Use Cases/Examples

```
function optional(): string? {
  return undefined // or allow just plain return
}
```

this would allow defining of optional getters as well:

```
class Hello {
  optional1?: string
  get optional2(): string? {
    return undefined
  }
}
```

Alternative syntax would be to specify question mark after the name, or even after the braces:

```
function optional?(): string
function optional()?: string
```

However, I find myself trying the first version of the syntax every time, which currently results in compile error.

This would compliment the usage of question mark `?` as nullablity/unefineability operator, similar to Kotlin.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-12-09 21:50
Duplicate of #35577.

**Comment by angryziber** [comment] 2020-12-10 17:28
The duplicate was closed, pointing to a discussion from 2016 that discusses everything about nulls. I was not able to follow/find the relevant parts in that discussion of why not to add nullable/undefineable return types.

By the end of 2020 more features have arrived to both JS and TS related to nullability handling, like optional chaining. It's time to reconsider and add the missing bits of nullability syntax to be able to make code more concise.

You can already get a nullable return type implicitly by e.g. returning the value from a nullable property (declared with ?), so why not allow to do that explicitly as well?

**Comment by MartinJohns** [comment] 2020-12-10 17:30
The point about optionality still stands. Optionality includes more than just "it can be undefined".

**Comment by RyanCavanaugh** [comment] 2020-12-10 17:32
Echoing my comments in the other suggestion; we don't intend to do this. The use of `T?` as a shortcut was debated [here](https://github.com/microsoft/TypeScript/issues/7426#issuecomment-193623924)

**Closed** 2020-12-10 17:33 UTC
Labels: Declined, Suggestion
