### ISSUE TITLE
Assign type alias to signature of function parameter list

### ISSUE THREAD

**Issue by nathantreid** [Microsoft/TypeScript#14719] opened 2017-03-18 13:38 UTC
Currently it appears there is no way to alias the parameter signature of a function separate from the entire signature. I think this feature should be added.
For now I'm going to represent this with the syntax `((<params>): TAlias)` where `<params>` is a standard parameter list, e.g. `(bar: string, baz: number)` and `TAlias` is the alias name. Together this looks like `((bar: string, baz: number): TAlias)`.

## Use Case
The reason for this is to allow the creation of a function that must have the exact same parameters as the passed in callback but with a different return type (it is currently possible to make it work with the exact same parameters and the same return type) via casting. 

```ts
class Foo<T, TResult, TAlias> {
  name: string;
  methodToRun: (bar?: T) => TResult;

  constructor(name: string, methodToRun: ((bar?: T): TAlias) => TResult) {
    this.methodToRun = methodToRun;
    this.name = name;
  }

  call((bar?: T): TAlias) : Promise<TResult> {
    return Promise.resolve(this.methodToRun(bar));
  };
}

// will pass TS validation (and does)
new Foo('', function (a: string) { return a.length; }).call('');
new Foo('', function () { return 1; }).call();

// will fail TS validation
new Foo('', function (a: string) { return a.length; }).call(2);  // Error: argument of type is not assignable to parameter of type
new Foo('', function (a: string) { return a.length; }).call(); // Error: supplied parameters do not match any signature of call target)
new Foo('', function () { return 2; }).call(2); // Error: supplied parameters do not match any signature of call target)
```

Note that in the example above, when `T` is not specified in the callback TypeScript doesn't care because it can infer that `T` is not being used anywhere in the class.

## How TS currently works

```ts
class Foo<T, TResult> {
  name: string;
  methodToRun: (bar?: T) => TResult;

  constructor(name: string, methodToRun: (bar?: T) => TResult) {
    this.methodToRun = methodToRun;
    this.name = name;
  }

  call(bar?: T): Promise<TResult> {
    return Promise.resolve(this.methodToRun(bar));
  };
}

// should pass TS validation (and does)
new Foo('', function (a: string) { return a.length; }).call('');
new Foo('', function () { return 1; }).call();

// should fail TS validation
new Foo('', function (a: string) { return a.length; }).call(2);  // Error: argument of type is not assignable to parameter of type
new Foo('', function (a: string) { return a.length; }).call(); // No TS error, causes runtime error (cannot read property length of undefined)
new Foo('', function () { return 2; }).call(2); // No TS error, but has no effect and doesn't match callback
```

**Desired behavior:**
TypeScript will enforce the argument type of `methodToRun` on `Foo#call`, but when `methodToRun` does not have an argument, TypeScript will enforce the lack of an argument on `Foo#call`. 

**Actual behavior:**
As shown at the bottom of the code snippet, when no argument is passed in, TS allows it because `bar` is specified as optional. If you change `bar` to be required, then you can still pass in the callback with no arguments, but you get an error when trying to call it:

```ts
class Foo<T, TResult> {
  name: string;
  methodToRun: (bar: T) => TResult;

  constructor(name: string, methodToRun: (bar: T) => TResult) {
    this.methodToRun = methodToRun;
    this.name = name;
  }

  call(bar: T): Promise<TResult> {
    return Promise.resolve(this.methodToRun(bar));
  };
}

// Now this one is OK
new Foo('', function (a: string) { return a.length; }).call(); // No error, which is good

// But as expected, this one fails
new Foo('', function () { return 1; }).call(); // Error: supplied parameters do not match any signature of call target
```

**Comment by ghetolay** [comment] 2017-04-19 11:03
I have the same need to build proxy function. What I want is take a function and create a proxy function around that function that keeps the same arguments signature but with a different return type.

I'm currently doing : 

```
function proxyFactory<R>(originFunc: () => R);
function proxyFactory<T1, R>(originFunc: (v1: T1) => R);
function proxyFactory<T1, T2, R>(originFunc: (v1: T1, v2: T2) => R);
function proxyFactory<T1, T2, T3, R>(originFunc: (v1: T1, v2: T2, v3: T3) => R);
function proxyFactory<T1, T2, T3, R>(originFunc: (v1?: T1, v2?: T2, v3?: T3) => R): (v1?: T1, v2?: T2, v3?: T3) => ProxyType<R> {
	return function(v1?: T1, v2?: T2, v3?: T3): ProxyType<R> {
		return { 
                  a: originFunc(v1, v2, v3)
               }
	}
}
```

But besides the static number of arguments, troubles also comes when `originFunc` has some optional parameter.
Would be nice if we could do : 

```
function proxyFactory<T, R>(originFunc: (arguments: T) => R): (...arguments: T) => ProxyType<R> {
	return function(...arguments: T): ProxyType<R> {
		return {
                  a: originFunc(...arguments)
                  //or
                  a: originFunc.apply(this, arguments)
                }
	}
}
```

**Comment by mhegazy** [comment] 2017-04-19 17:02
Duplicate of https://github.com/Microsoft/TypeScript/issues/5453?

**Comment by ghetolay** [comment] 2017-04-19 21:33
Yes I think this would cover my need and should also covers op needs I think.
But personally I would have never found it myself so it may be good to keep this issue open.

**Comment by mhegazy** [comment] 2017-05-08 19:24
This issue seems to have been already addressed or is unactionable at the moment. I am auto-closing it for now.

**Closed by mhegazy** 2017-05-08 19:24 UTC
Labels: Duplicate
