### ISSUE TITLE
(Suggestion) `filepath` built-in type

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#48892] opened 2022-04-30 06:59 UTC
# Suggestion

## 🔍 Search Terms

path filepath const type

## ⭐ Suggestion

Introduce the `filepath` type, it expects a const string that defines the path of an existing file. 
It is, in short, a const string analogue to the string in `import` declarations. 

```ts
const data_path: filepath = "../../static/data.json";
```

## 📃 Motivation

Writing scripts often consists of having hardcoded paths pointing to local files, 
e.g. unprocessed data inputs, bundler builds or test artefacts.

Typescript already has a variety of features for paths defined in import declarations, 
I suggest adding a type that would enable those features on const string variables.

### - IntelliSense 

Variables of type `filepath` get autocomplete features for existing files.

### - Refactoring

Variables of type `filepath` are automatically changed if the target file is moved or renamed

```ts
import { ... } from "./foo";
const target: filepath = "../foo.ts";
```

_Rename `foo.ts` to `bar.ts`..._

```ts
import { ... } from "../bar";
const target: filepath = "../bar.ts";
```

### - Type-checking

- `import` and `require` no longer need to declare paths inline to benefit from type-checking

```ts
const target: filepath = "../foo.ts";
const data = await import(target);
    // ^? const data: any                        [CURRENT]
    // ^? const data: typeof import("../foo.ts") [SUGGESTED]

```

- Paths to external files raise errors if missing

```ts
function read_file(target: filepath) {
  return fs.readFileSync(path.resolve(__dirname, target), "utf-8");
}
read_file("./input/client_table_2023.json");
// Cannot find file './input/client_table_2023.json' or its corresponding type declarations. ts(1234)
```

**Comment by MartinJohns** [comment] 2022-04-30 07:40
Duplicate of #42054.

**Comment by andrewbranch** [comment] 2022-05-03 00:14
This suggestion is unique in the type checking part, but I think that part is highly problematic. Would we resolve relative to the input file or output file? Are you supposed to `ts-ignore` if you need to reference a file that will only exist in CI? Nitpicking these questions isn’t worth the time—this is the job of a linter.

**Closed** 2022-05-03 00:14 UTC
Labels: Suggestion, Out of Scope
