### ISSUE TITLE
"Cannot redeclare block-scoped variable length"

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/TypeScript#43398] opened 2021-03-26 04:44 UTC
When I try to work on a JS file that has a "const length = 100" line at the top with `"js/ts.implicitProjectConfig.checkJs": true`, I get an ugly `"Cannot redeclare block-scoped variable length"` error because it conflicts with some lib.dom.ts file... but that's in fact not a concern at all:
![image](https://user-images.githubusercontent.com/8586769/112579751-43239580-8db3-11eb-8a09-aa79bc0b96b4.png)

I think something like this would probably pose a significant barrier to folks trying to get started with checkJS.

**Comment by mjbvz** [comment] 2021-03-26 20:24
This is a duplicate of https://github.com/microsoft/TypeScript/issues/31783

Moving upstream for more feedback. I don't think the code causes issues  when run in a browser

**Comment by JacksonKearl** [comment] 2021-03-26 21:26
Correct, I tried in node and browser contexts with no issues.

**Comment by RyanCavanaugh** [comment] 2021-03-26 21:39
The problem here is that if you downlevel this code to `var`, it starts misbehaving again, and we don't know whether or not you're doing that. Beside that, we *could* add some logic here to separate the "global scope that's actually global" and the "global scope that is shadowable with a block-scope `let`/`const`" but to be honest this really doesn't seem to come up much.

**Closed** 2024-02-24 00:23 UTC
Labels: Design Limitation
