### ISSUE TITLE
asume es module when using top level await

### ISSUE THREAD

**Issue by jimmywarting** [microsoft/TypeScript#54245] opened 2023-05-14 15:55 UTC
I'm faced with this error:
```
'await' expressions are only allowed at the top level of a file when that file is a module, but this file has no imports or exports. Consider adding an empty 'export {}' to make this file a module. ts(1375)
```

when i have code such as `await 1`

it's not always that i import or export something
And i don't really feel like doing and empty `export {}` or adding any tsconfig.json or jsconfig.json
i have checkJS + allowJs turned on in my vscode settings and the environment it guesses that it's in is sometimes often wrong. 

can you just don't assume that it's okey to use top level await.
I want to disable this lint/rule check completely completely... cuz this one is annoying.

**Comment by jcalz** [comment] 2023-05-14 23:07
There’s a template you’re supposed to fill out when you open a new issue.  

Looks like a duplicate of #37794.

**Comment by RyanCavanaugh** [comment] 2023-05-15 18:16
You can set `moduleDetection: force`

**Comment by jimmywarting** [comment] 2023-05-16 16:25
where in vscode? don't have a tsconfig or a jsconfig file

**Closed** 2023-05-19 00:00 UTC
Labels: Question

**Comment by jimmywarting** [comment] 2023-05-19 14:09
> no recent activity

Wow. it have only gone 3 days...

**Comment by jimmywarting** [comment] 2023-10-08 19:59
is there a vscode setting for this?
or do i really need a tsconfig?

**Comment by TomasHubelbauer** [comment] 2024-02-28 19:50
Since this is top Google hit for the error message, here is how you can get VS Code to chill about TLA when your runtime supports it (e.g.: Bun) and your IDE is holding you back - and all without the dreaded `export {}`:

`tsconfig.json`
```json
{
  "compilerOptions": {
    "module": "ESNext",
    "moduleDetection": "force",
    "target": "ESNext"
  }
}
```
