### ISSUE TITLE
dual parameter type

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#51836] opened 2022-12-09 10:46 UTC
# Suggestion

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

A parameter keyword to show certain type for outside call, and unknown type for inside use.

Useful for top level api of a lib, which also used in the lib inside (or as a better reading notice for that function scope).

And when dist .d.ts, the keyword can be removed.

## 📃 Motivating Example

```ts
function f (a :unknown number) :void {
    a.toString();// forgot to check type, error
    if ( typeof a!=='number' ) { throw new TypeError; }
    a.toString();// can safe use now
}
f(1);// correct
f(true);// error
```

```ts
function assertNumberExcept (len :unknown number, max :number) :asserts len is number {
    if ( typeof len==='number' ) { throw new TypeError; }
    if ( len>max ) { throw RangeError; }
}
function f (len :unknown number) :void {
    assertNumberExcept(len, 16);
    assertNumberExcept(len, '16');// error, so unknown keyword can not simply write on whole function level
    assertStringExceptLongerThan(len, 16);// error, wrong using assert util, overloading can not handle this
}
function assertStringExceptLongerThan (len :unknown string, maxLen :number) :asserts len is string {}
```

## 💻 Use Cases

For top level api of a lib, it often need to assert arguments type, sometimes we forget to do that.

But if write unknown instead, we could forget the type when call in the lib internal, for forget the type even in the function itself, and .d.ts it dist will have no meaning.

**Comment by whzx5byb** [comment] 2022-12-09 10:58
> to show certain type for outside call, and unknown type for inside use

I'd like to suggest using function overloading like this:
```ts
function f(a: number): void;
function f(a: unknown): void {
    a.toString();// forgot to check type, error
    if ( typeof a!=='number' ) { throw new TypeError; }
    a.toString();// can safe use now
}
```

**Comment by LongTengDao** [comment] 2022-12-09 11:11
@whzx5byb thank you! sorry I fotgot to write use case 2 a moment ago:

```ts
    assertStringExceptLongerThan(len, 16);// error, wrong using assert util, overloading can not handle this
```

And the new syntax help strong lib environment more easier.

**Comment by MartinJohns** [comment] 2022-12-09 12:00
This sounds like a duplicate of #49781 to me.

**Closed** 2022-12-10 00:48 UTC
Labels: Duplicate
