### ISSUE TITLE
Will imports be introduced as in Java?

### ISSUE THREAD

**Issue by splincode** [Microsoft/TypeScript#20009] opened 2017-11-14 11:53 UTC
There are a huge number of types of imports in JavaScript (I counted 3 of them), is it possible to support such imports as in Java? Java imports are developing and the specification is very good and time-tested.

In terms of convenience (absolute paths, not relative), you immediately write the import of the package you want, not the class that you need to import, but only then the path to the file, which is not convenient when typing in from the keyboard.

Due to the fact that developers encounter problems in the development, you have to write all sorts of resolving paths (webpack.config, tsconfig).

**Comment by andy-ms** [comment] 2017-11-14 15:54
We will stick to JavaScript's imports. See the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment] 2017-11-14 19:08
Duplicate of #17814

**Closed** 2017-11-14 22:47 UTC
Labels: Duplicate
