### ISSUE TITLE
Insufficient type narrowing of return type with Promise.all

### ISSUE THREAD

**Issue by sapphiredev** [microsoft/TypeScript#35258] opened 2019-11-21 06:39 UTC
**TypeScript Version:**  3.7.2

**Search Terms:**
generics readonly Promise.all

**Code**

```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "strictNullChecks": true,
    "esModuleInterop": true,
  }
}
```

```ts
declare function x1(): Promise<number>;
declare function x2(): Promise<number | null>;

(async () => {
	const [a, b] = await Promise.all([x1(), x2()]);
	if (a < 1) { }
})();
```

**Expected behavior:**
type of `a` should be `number`

**Actual behavior:**
type of `a` is `number | null`

**Playground Link:** 
https://www.typescriptlang.org/play/index.html?noImplicitAny=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&esModuleInterop=false&ssl=1&ssc=1&pln=8&pc=1#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwA8BGACgEoAueABRhwFssBnEAHlWXoCMQYA+ANwAoUJFgIU6bHkIAmclVoNmbDt17wAPvA4QIgoUJJQmAT3Txy8ALx94AbyEBIMHiYZ4AbSgAaeFwBdG3goAHcoLA8lRhYAOig9Ek9icj8CeTIAsmEnLERLKHhWeCIyB3gAXyEKsnJhIA

**Related Issues:**

**Comment by sapphiredev** [comment] 2019-11-21 06:50
another example:
```ts
declare class C<X> { }

declare function fn<T1, T2>(values: readonly [C<T1>, C<T2>]): [T1, T2];

declare function x1(): C<number>;
declare function x2(): C<number | null>;

(async () => {
	const [a, b] = fn([x1(), x2()]);
	if (a < 1) { }
})();
```

this code works if there is 
1. no readonly modifer
1. compiler option of strictNullChecks: false
1. no generic class

**Comment by MartinJohns** [comment] 2019-11-21 08:27
Duplicate of #35136, #34925, #33562. Found by searching for `Promise.all`.

**Comment by IllusionMH** [comment] 2019-11-21 17:49
#33707 might fix this one

**Closed** 2019-12-21 18:00 UTC
Labels: Duplicate
