### ISSUE TITLE
Class constructor type from instance

### ISSUE THREAD

**Issue by Mosho1** [Microsoft/TypeScript#8261] opened 2016-04-23 11:10 UTC
**TypeScript Version:** 

1.8.10

**Code**

```ts
    class ClassWithStaticProp {
        static prop = {};
    }

    const instance = new ClassWithStaticProp();

    // instance.constructor has no type information

```

**Expected behavior:**

`instance.constructor` should have the same type as the `ClassWithStaticProp` constructor function.

**Actual behavior:** 

`instance.constructor` has no type information

**Comment by Arnavion** [comment] 2016-04-23 14:33
Duplicate of #3841

**Closed** 2016-04-25 17:07 UTC
Labels: Duplicate
