### ISSUE TITLE
Error TS1206: Decorators are not valid here on a non-top level class

### ISSUE THREAD

**Issue by bcherny** [Microsoft/TypeScript#8361] opened 2016-04-28 19:48 UTC
```ts
function decorator(container, key) {}

class A {
	@decorator // OK
	fn(){}
}

let a = {
	b: class B {
		@decorator // Error TS1206: Decorators are not valid here
		fn(){}
	}
}
```

My use case is a controller class in an Angular 1.5 component:

```ts
const MyComponent = {
  bindings: {...},
  template: `...`,
  controller: class MyComponentController extends BaseComponent {
    @override
    foo() {...}
  }
}

abstract class BaseComponent {
  protected foo() {...}
}
```

**Comment by mhegazy** [comment] 2016-04-28 19:57
duplicate of #8257 and  #7342

**Closed by mhegazy** 2016-04-28 19:57 UTC

**Comment by bcherny** [comment] 2016-04-28 20:01
@mhegazy I saw both of those issues before filing this one - I think they are different than this.

#8257 is for an instantiated class
#7342 is for anonymous classes
This issue is for non-top level named classes.

**Comment by mhegazy** [comment] 2016-04-28 20:08
it is neither instantiated nor anonymous that matters. it is class declaration (top level), vs. class expression (everything else). (similar to function declaration, vs function expression.)

**Comment by bcherny** [comment] 2016-04-28 20:09
Got it - thanks.
