### ISSUE TITLE
HTMLSelectElement.options

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#1558] opened 2014-12-25 14:46 UTC
```
interface HTMLSelectElement {
    options: HTMLSelectElement; // should be HTMLCollection
```

**Comment by robfe** [comment] 2015-07-21 22:17
Is there any special reason why this one-line fix keeps getting pushed back? https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#L6078

If it's just a matter of priorities I'd love to help out. This one is annoying me since there's no clean way to replace the interface property

**Comment by mhegazy** [comment] 2015-07-21 22:55
@zhengbli can you take a look.

**Comment by RyanCavanaugh** [comment] 2015-07-22 04:59
@robfe it's a prioritization thing. FWIW we're always accepting PRs for lib.d.ts fixes (or anything else that's very low-risk, e.g. wiki edits, comments / formatting improvements, etc).

**Comment by robfe** [comment] 2015-07-23 20:51
I've just noticed that IE 11 itself considers `options` to be a reference to the select element

```
var s = document.createElement("select");
console.log(s.options === s); // true in IE 11, false in other browsers
```

In the older spec options is a `HTMLCollection`: http://www.w3.org/TR/REC-DOM-Level-1/level-one-html.html#ID-94282980

>  readonly attribute  HTMLCollection       options;


But as per http://www.w3.org/TR/html5/forms.html#dom-select-options it's an `HTMLOptionsCollection`

> The options IDL attribute must return an HTMLOptionsCollection rooted at the select node, whose filter matches the elements in the list of options.

where HTMLOptionsCollection is:

``` IDL
interface HTMLOptionsCollection : HTMLCollection {
  // inherits item()
           attribute unsigned long length; // shadows inherited length
  legacycaller HTMLOptionElement? (DOMString name);
  setter creator void (unsigned long index, HTMLOptionElement? option);
  void add((HTMLOptionElement or HTMLOptGroupElement) element, optional (HTMLElement or long)? before = null);
  void remove(long index);
           attribute long selectedIndex;
};
```

I'm keen to submit a fix for this, but what's your preference @mhegazy @RyanCavanaugh @zhengbli ?
1. leave it as is (with the interface matching IE11's implementation)?
2. a one line PR that changes it to HTMLCollection?
3. a slightly larger PR that adds the HTMLOptionsCollection interface?

**Comment by zhengbli** [comment] 2015-07-23 23:04
Confirmed that in Edge the ``HTMLSelectElement.options`` is still a reference of itself, the same with IE 11. I suggest to make the type of ``HTMLSelectElement.options`` ``HTMLSelectElement | HTMLCollection`` to avoid assignability problems.

**Comment by mhegazy** [comment] 2015-11-02 20:12
that does not help much. now the users who expect it to be `HTMLSelectElement` do not get that, nor the ones who want it to be `HTMLCollection`. both groups will have to cast.

**Comment by zhengbli** [comment] 2015-11-11 00:11
@mhegazy tested on the latest Edge that `HTMLSelectElement.options` became `HTMLCollection`, which is consistent with Chrome and Firefox. It should be OK to use it instead.

**Comment by mhegazy** [comment] 2015-11-11 06:14
:+1:

**Closed** 2015-12-01 18:47 UTC
Labels: Breaking Change, Bug, Fixed, lib.d.ts
