### ISSUE TITLE
If there is an optional property `prop1` for a react component, specifying `prop1-={value}` is not giving type error

### ISSUE THREAD

**Issue by pateltejas** [microsoft/TypeScript#46225] opened 2021-10-05 18:54 UTC
[Example](https://www.typescriptlang.org/play#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKCrQgDsBneAWQE8BhXSOpOmALkTEYAOgBi7ADwBvMDjABGAPyCmUYHQDmAGjhyIYAEyqY6rQF8AfHAC8cABSz5C3fqPmAlLevSqcf3BEMACuUHRwkgAmwABultIABgAkTgYK5nApbobmCeaSAPTRcVTmVFSSbJzg9LzwbgoAtDbS+AAWSAA2nRD4Gdkt7V09hn1wKIMoYwWWQA)

I have a prop named `prop1`, however I have a typo where I have a `-` after prop name, i.e `prop1-={value}`, but TS is not giving error. On other hand if I give in an unknown property, it does throw error. Wonder why is `-=` being considered valid assignment to the prop?

**Comment by MartinJohns** [comment] 2021-10-05 18:58
You forgot to fill out the issue template. Duplicate of #32447.

**Closed** 2021-10-10 00:00 UTC
Labels: Question
