### ISSUE TITLE
Move global const name into window interface

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#27703] opened 2018-10-11 09:07 UTC
The problem happens because the `name` is very popular variable/property name and there is global `name` with type like `any`

```ts
interface MyType {
   name: string;
   value: string;
}

 // somewhere in the code
 var {name} = getMyType();
 
 // some code 
 
 var bar = name + 'Bar';
 var newMyType:MyType = {name, value: 'bar'}
```

If I remove  this line `var {name} = getMyType();` within some refactoring, typescript no throws, because we have global `name` variable with type `never` which can be assigned to anything without any error

And absolutely no way to fix it locally
```ts
declare global {
   const name: void; // error: cannot reassign
}
```

In my practice I already fixed tens of bugs with this global `name`

I think this global `name` variable absolutely useless, but create a lot of bugs with his presence.

Solution is very simple - we just can move this variable into `Window` interface without any breaking changes

**Comment by kitsonk** [comment] 2018-10-11 09:29
Duplicate of #18433

**Closed** 2018-10-16 17:42 UTC
Labels: Duplicate
