### ISSUE TITLE
`this` type not work

### ISSUE THREAD

**Issue by gityoog** [microsoft/TypeScript#56227] opened 2023-10-27 02:40 UTC
### 🔎 Search Terms

keyof this

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/MYGwhgzhAECC0G8CwAoa0wEIBc0IBcAnASwDsBzVdAdzH2AAsAKAawFMBPXdjgewDNo+BsQgBKRKirQAvtNr0GAJladcAUQAeoAK4ATNgB4eAoSIgAaaAHIFjJdYB8E5Cmly0QtgSYvp6YVEAOjtmazBrMX8zYNCVcMjoAHok6FJefGhqXkIWd1QPVFI2ajhfELpGJgSolGLS2HK46oiJFKycliA

### 💻 Code

```ts
class A {
  a!: string
  watch(key: keyof this) {

  }
  watch2(key: Exclude<keyof this, 'watch2'>) {

  }
  test() {
    this.watch('a')
    this.watch2('a') // not work
  }
}

new A().watch('a')
new A().watch2('a') // work
```

### 🙁 Actual behavior

keyof `this` not work

### 🙂 Expected behavior

watch2 work

**Comment by MartinJohns** [comment] 2023-10-27 06:01
Duplicate of #31669.

**Closed** 2023-10-27 06:09 UTC
