### ISSUE TITLE
StrictNullChecks don't work well with higher-order functions

### ISSUE THREAD

**Issue by ccorcos** [Microsoft/TypeScript#19389] opened 2017-10-20 21:32 UTC
**TypeScript Version:**  2.6.0-dev.201xxxxx

**Code**

```ts
let x: string | undefined
let y: { value?: string } = {}

function f(arg: string) { }

function g(arg: () => void) {}

if (x && y.value) {
	g(() => {
		f(x)
		f(y.value)
	})
}
```

**Expected behavior:**

I would expect there to be no type errors.

**Actual behavior:**

x and y.value are both resolves as nullable inside the function even though I guarded them in the if statement.

**Comment by ahejlsberg** [comment] 2017-10-20 21:45
This is working as intended. `x` and `y` might have different values assigned to them before the callback passed to `g` is actually invoked. It works as expected if you switch from `let` to `const` in the declarations of `x` and `y`.

**Comment by ccorcos** [comment] 2017-10-20 22:29
Just realized this. Tricky... Thanks!

**Closed** 2017-10-20 22:28 UTC
Labels: Working as Intended
