### ISSUE TITLE
Add support for custom import handlers

### ISSUE THREAD

**Issue by Systemcluster** [Microsoft/TypeScript#11610] opened 2016-10-14 01:19 UTC
**Abstract**

Provide a mechanism to let developers define custom import handlers to allow typesafe imports of different file types.

**Problem**

`import` at this time exclusively handles ts/js module imports. Importing non-modules, e.g. css (for _css-modules_ usage) or json files, currently requires workarounds with potentially huge drawbacks: Statically creating a `.d.ts` for each file, or using a `require` declaration returning `any`.

``` ts
    // examples using webpack css-loader in module mode
    import * as styles from "./style.css" // requires static style.css.d.ts
    const styles = require<any>("./style.css") // not type-checked
```

**Proposition**

Provide a mechanism to define import handlers for specified file extensions. This handler will be supplied with the path of the file to be imported, and shall return a valid declaration - from the scripts perspective, a custom import should behave like a regular typescript module import. 

The handler could exist as a single script or a node module.

**Advantages**

The proposed addition opens up the possibility for developers to implement typesafe usage of loaders when using module bundlers like webpack. Additionally, it could enable the development of more flexible build pipelines that don't rely on preceding transpilation.

**Comment by aluanhaddad** [comment] 2016-10-14 03:39
This has already been resolved with ambient wildcard module declarations. Unfortunately this does not validate the existence of the target but it allows you to specify the types of the values produced by the loaders and bundlers that operate over them. 

Workarounds like creating individual `.d.ts` files were annoying and cumbersome to maintain, what are no longer necessary thanks to this new feature in 2.0.

```ts
declare module '*.html' {
  export default '';
}
```
What does does not do is intertwine TypeScript with a specific tool, environment, or protocol. It is an abstract declaration and can even contain exotic AMD style plug-in syntax or synthetic directory structures.

 I think this turned out really well.

**Comment by kitsonk** [comment] 2016-10-14 07:33
For reference the issue is #6615

**Comment by Systemcluster** [comment] 2016-10-14 09:25
Indeed wildcard module declarations are a good solution for many cases, but they do not provide a typesafe mechanism on a individual file basis. This would be an option separate to wildcard module declarations. Staying with the `css-modules` example, a pluggable import handler could enable the type checker to catch the following error:

```css
    .elem {/* css declaration */}
```
```ts
    import * as styles from "styles.css"
    let e = styles.elm // typo, styles.elm is not defined
```

**Comment by kitsonk** [comment] 2016-10-14 10:58
What you are asking for is non trivial.  These *import handlers* would have to parse non-TypeScript files into some sort of AST that is understood by TypeScript.  That would require a whole syntactic language to describe how to parse files in other languages.

What we have been doing in @dojo, wanting to use CSS Modules, is creating a [build step in our process](https://github.com/dojo/widgets/blob/37b6d6c4721de14559ffcadb4cb955c6688f5f87/Gruntfile.js#L57) to output a TypeScript module that contains the mapping of modular CSS classes into what is being generated when the CSS Module is transpiled.  We are also doing something similar with our internationalisation strings.

We are finding that dynamically generating TypeScript files is one of the easiest ways to have TypeScript understand "foreign" file formats.

**Comment by Systemcluster** [comment] 2016-10-14 13:47
>These import handlers would have to parse non-TypeScript files into some sort of AST that is understood by TypeScript. That would require a whole syntactic language to describe how to parse files in other languages.

They would return a simple module declaration in string form, the same format that a matching `.d.ts` file would contain. Typescript would then consume this string like any other module.

>We are finding that dynamically generating TypeScript files is one of the easiest ways to have TypeScript understand "foreign" file formats.

This is what the handler is supposed to do, merely avoiding the detour of writing the generated typescript to a file and instead passing the contents directly to the typescript service. It would have the advantage of providing the definition immediately to enable on-the-fly type checking and autocompletion.

**Comment by mhegazy** [comment] 2016-10-17 23:32
I would recommend creating a tool that would generate a .d.ts file from the original file. 

Building a whole set of custom module loading plugins, watching the source files, doing this on every edit would not be a salable solution.

**Comment by mhegazy** [comment] 2016-10-17 23:32
I should also note this is already covered by https://github.com/Microsoft/TypeScript/issues/3136

**Closed** 2017-04-21 16:56 UTC
Labels: Duplicate
