### ISSUE TITLE
Small change in 'import'

### ISSUE THREAD

**Issue by matheusml** [Microsoft/TypeScript#4880] opened 2015-09-20 02:19 UTC
We should change this:

```import { some-module } from 'some-lib'```

To this:
 
```from 'some-lib' import {some-module}```

If we change to the second, the IDE can help us out by auto-completing the modules which we can import. In the first case we still can do it, but it's unnatural, we have to type everything and then come back.

**Comment by Gaelan** [comment] 2015-09-20 04:54
TypeScript is based on ES6 syntax, which importing is a feature of. Generally, the TS project doesn't like to deviate from the spec, so the best way to go about this change might be to suggest it for the ES7 spec. However, I'm just a random lurker on this repository with no authority, so feel free to completely ignore this comment. :smile:

**Comment by DanielRosenwasser** [comment] 2015-09-21 07:01
This is a duplicate of #2371. While the import syntax doesn't lend well to intellisense/completion, I don't think it would be appropriate to deviate from ES6.

As @danquirk suggests in https://github.com/Microsoft/TypeScript/issues/2371#issuecomment-81905846, our IDE experience should compensate for this problem using something like snippets.

**Closed** 2015-09-21 07:01 UTC
Labels: Declined, Duplicate
