### ISSUE TITLE
Improve function argument type inference

### ISSUE THREAD

**Issue by Strate** [Microsoft/TypeScript#11440] opened 2016-10-07 09:51 UTC
Consider the example:

``` ts
// module1.ts
export function doOperation(
  options: string,
  callback: (argument: {
    prop1: number,
    prop2: string,
    prop3: SomeComplexInterface
  }) => any
) {
  // implementation is omitted
}

// module 2
import {doOperation} from "./module1"
doOperation("options", operationCallback);
function operationCallback(argument) {
  // argument has implicit type 'any' here
}
```

I suggest to improve type inference of `operationCallback`'s arguments in this way:
1. If function don't has defined arguments
2. Take first usage of that function
3. Infer argument types from that usage

What do you think about it?

**Comment by aluanhaddad** [comment] 2016-10-07 10:41
Personally, I think this would be confusing. 
I understand the desire, as I sometimes find it annoying that I have to add extra annotations when refactoring, but without those annotations the extracted callback function becomes less readable. And inferring on first use makes reuse difficult, for example if the extracted function were a generic error handler that ignored its argument.

I would suggest the following:
```TypeScript
// module1.ts
export function doOperation(
  options: string,
  callback: (argument: OperationCallbackArgument) => any
) { ... }

export interface OperationCallbackArgument {
    prop1: number,
    prop2: string,
    prop3: SomeComplexInterface
}

// module 2
import {doOperation, OperationCallbackArgument} from "./module1"

doOperation("options", operationCallback);

function operationCallback(argument: OperationCallbackArgument) {
    console.log(argument.prop1);
}
```

Long term, I think the language service will provide refactorings, such as "introduce local function".

**Comment by HerringtonDarkholme** [comment] 2016-10-07 12:01
Almost impossible in TypeScript, given current architecture.
Currently the compiler only infer local expression, the "bottom up" path, or contextually typing an expression, the "top down" path. Every expression is typed "locally".

What you ask for is global type inference: flow type information back to define site from use site. That's what TypeScript is designed to do. Try flowtype for similar feature (but that's not global inference either, flow just infers the argument type from function body)

**Comment by mhegazy** [comment] 2017-05-17 23:55
duplicate of https://github.com/Microsoft/TypeScript/issues/15114?

**Comment by mhegazy** [comment] 2017-06-02 01:36
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-06-02 01:36 UTC
Labels: Duplicate
