### ISSUE TITLE
Initializing JS/TS language features ignores files.watcherExclude

### ISSUE THREAD

**Issue by claritysolutionsteam** [Microsoft/TypeScript#29782] opened 2019-02-01 20:21 UTC
# details
Initially vs code respects files.watcherExclude upon opening a workspace if no js/ts files are open vs code correctly watches all files in the workspace except for those indicated by files.watcherExclude
However as soon as a JS/TS file is opened the message "initializing JS/TS language features" is shown on the status bar and vscode watches all files.

# reproducing

1. veryify that excludes some things in the work space
file > preferences > settings  > files.watcherExclude
2. close all open files and restart vs code
3. veryify that vs code is watching all files in the workspace that are not excluded
4. open (or create) a .js or .ts file
5. see initializing JS/TS language features on the bottom status bar
6. observe that vs code is watching all files in the workspace

exepected result: vs code should not watch files in the files.watcherExclude setting
actual result: vs code watches all files as soon as JS/TS language features are enabled 

# how to see what files vs code is watching 
There are a number of ways to do this on linux (none of them all that easy). 
Exact method may vary depending on version of linux
There are a number of methods discussed in https://unix.stackexchange.com/questions/15509/whos-consuming-my-inotify-resources/426001#426001
The method I used was to find the PID of code using ps EG: ps aux|grep code
this turns up multiple processes as code spawns subprocesses
then take those pids and 
grep /proc/<PID>/fdinfo/* inotify 
the text on these lines seems to vary depending on linux version so it may read something else other then inotify
at least on CentOS Linux 7 (Core) these lines contain ino:<inode number of file being watched in hex>
from there the number of files being watched can be compared to the number of files expected to be watched or
some method of stating the files in the workspace can be used to see exactly which files are being watched
for example ls -i will tell the inode number of the files listed (in decimal)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 3.10.0-862.3.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (8 x 2699)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|59.97GB (0.97GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by mjbvz** [comment] 2019-02-06 19:39
Moving over to TypeScript since it is the tsserver that is watching these files

**Comment by sheetalkamat** [comment] 2019-02-06 20:00
tsserver doesn't let you configure the watches you want to exclude. This is for best experience in vscode. I am not sure what action we can take here.
cc @RyanCavanaugh @DanielRosenwasser @amcasey

**Comment by kanerai** [comment] 2019-02-06 22:38
Is there anything we can do to stop it from watching the <projectRoot>/.git files? That directory doesn't have any files I would want typescript looking at.

**Comment by RyanCavanaugh** [comment] 2019-02-14 21:28
@sheetalkamat I don't think we should ever be watching `.git` - can you verify that this folder is always excluded from our watches?

**Comment by sheetalkamat** [comment] 2019-02-14 22:15
Currently we ignore anything thats dotted directory/file in node_modules. We can add `.git` to that list

**Comment by sheetalkamat** [comment] 2019-02-27 20:31
Duplicate of #29407 where in gulp deletes the directory we are watching and node doesn't send us notification of delete and then goes in bad state.

**Closed** 2019-03-07 19:24 UTC
Labels: Bug, Fixed
