### ISSUE TITLE
Type definition problem with Promise.all

### ISSUE THREAD

**Issue by twoeo** [Microsoft/TypeScript#9810] opened 2016-07-19 05:42 UTC
**TypeScript Version:**  1.8.10

**Code**

```ts
class XX{
	constructor(name:string){
		this.name = name;
	}
	name:string;
	showName(){
		console.log('ShowName: '+this.name)
	}
}

function getPromise(name):Promise<XX>{
	return new Promise<XX>((rs,rj)=>{
		rs(new XX(name))
	})
}
// just a promise array , TResult is XX
var promises: Promise<XX>[] = [getPromise('AA'), getPromise('BB')];

//type error with promise.all
var promiseAll:Promise<XX[]> = Promise.all(promises);
promiseAll.then(results=>{
	results.forEach(v=>{v.showName()})
})
```

**Expected behavior:**
Compile success, and run as below:
```
showName: AA
showName: BB
```

**Actual behavior:** 
Compile error with message:
```
test.ts(20,5): error TS2322: Type 'Promise<Promise<XX>[]>' is not assignable to
type 'Promise<XX[]>'.
  Type 'Promise<XX>[]' is not assignable to type 'XX[]'.
    Type 'Promise<XX>' is not assignable to type 'XX'.
      Property 'name' is missing in type 'Promise<XX>'.
```

**Suggestion:**
**Actually the problem seems like Promise<T> isn't recognized as PromiseLike<T>**
 In lib.es6.d.ts,
```ts
all<TAll>(values: Iterable<TAll | PromiseLike<TAll>>): Promise<TAll[]>;
```
maybe... should be:
```ts
all<TAll>(values: Iterable<TAll | PromiseLike<TAll> | Promise<TAll>>): Promise<TAll[]>;
```
It works well for this

**Comment by Arnavion** [comment] 2016-07-20 04:10
Duplicate of #7566

**Closed** 2016-07-20 04:58 UTC
Labels: Duplicate
