### ISSUE TITLE
"unknown" type testing doesn't work in unreachable code.

### ISSUE THREAD

**Issue by mpawelski** [microsoft/TypeScript#47343] opened 2022-01-07 13:51 UTC
# Bug Report

### 🔎 Search Terms
unknown allowUnreachableCode

### 🕗 Version & Regression Information
4.5.4 and 4.6.0-dev.20220107

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?allowUnreachableCode=true&ts=4.6.0-dev.20220107#code/FAMwrgdgxgLglgewgAgKYCd0PQCQIYQAmANhgIwAUGW6AXJANYQIDuEAlAN7DLJwhVM2PhADOMAlFQIQyAKJD0XHr2RQkohKQB0xBAHNBNbQFtUo0Xn2p2AbhUBfYE9CRYiFNWz4ipdACYjbHoIJlYObl50VBgwdAh7Xn4g9BFxSWlZBRplVTUNLVRdAxTTc0trO0dnYFdoeCQ0RR8SDABmFJCwtlzkGAALLBYmmhVkr1S4MQloTPlFXt51MULiwwmyiysbROQnFyA)

### 💻 Code

```ts
function errorHandler2(error:unknown){
  return;
  if(error instanceof Error){
    console.log(error.message); //Error: Object is of type 'unknown'.
  }
}

function errorHandler3(error:unknown){
  throw error
  if(error instanceof Error){
    console.log(error.message); //Error: Object is of type 'unknown'.
  }
}


```

### 🙁 Actual behavior

I've put `return` or `throw` statement just for debugging purpose to end function earlier. And I got compiler error in later code.

### 🙂 Expected behavior
No error because I have `allowUnreachableCode: true` in tsconfig (default) and the unreachable code is valid (but compiler says it is not).

Small bug IMO, nothing serious, but it's something I didn't expect.

**Comment by MartinJohns** [comment] 2022-01-07 14:14
Duplicate of #26914.

**Closed** 2022-01-13 18:00 UTC
Labels: Duplicate
