### ISSUE TITLE
Type guard not working

### ISSUE THREAD

**Issue by joeskeen** [Microsoft/TypeScript#6205] opened 2015-12-22 17:18 UTC
See [Playgound](http://www.typescriptlang.org/Playground#src=function%20test%20(myParam%3A%20string%20%7C%20string%5B%5D)%3A%20boolean%20%7B%0A%09if%20(typeof%20myParam%20%3D%3D%3D%20'string')%20%7B%0A%09%09if%20(myParam%20%3D%3D%3D%20'*')%20%2F%2F%20type%20here%20is%20%60string%20%7C%20string%5B%5D%60%2C%20but%20should%20be%20%60string%60%0A%09%09%09return%20true%3B%0A%09%09%09%0A%09%09myParam%20%3D%20%5BmyParam%5D%3B%20%2F%2Ferror%0A%09%7D%0A%09%0A%09return%20myParam.length%20%3E%200%3B%0A%7D):

I was sure I had the type guard syntax correct, but it doesn't seem to be working:

```js
function test (myParam: string | string[]): boolean {
	if (typeof myParam === 'string') {
		if (myParam === '*') // type here is `string | string[]`, but should be `string`
			return true;
			
		myParam = [myParam]; //error
	}
	
	return myParam.length > 0;
}
```

Is this a bug, or am I missing something here?

**Comment by vladima** [comment] 2015-12-22 17:22
duplicate of #1769

**Closed by vladima** 2015-12-22 17:22 UTC
Labels: Duplicate
