### ISSUE TITLE
object type can not be iterated with for...in

### ISSUE THREAD

**Issue by fpoppinga** [Microsoft/TypeScript#14792] opened 2017-03-22 09:44 UTC
**TypeScript Version:**  2.2.1 

**Code**

```ts
function f(param : object) {
    for (let key in param) {

    }
}

f({'a' : 2});
```

**Expected behavior:**
Code compiles, I expect `object` to be of "object type". 
**Actual behavior:**
TypeScript Error `error TS2407: The right-hand side of a 'for...in' statement must be of type 'any', an object type or a type parameter.`

**Comment by mhegazy** [comment] 2017-03-23 16:52
Duplicate of https://github.com/Microsoft/TypeScript/issues/14187 should be fixed by https://github.com/Microsoft/TypeScript/pull/14195

**Closed** 2017-03-23 16:53 UTC
Labels: Duplicate
