### ISSUE TITLE
Compiler crash: tuple type element list cannot be empty

### ISSUE THREAD

**Issue by anticrisis** [Microsoft/TypeScript#16636] opened 2017-06-20 08:07 UTC
**TypeScript Version:**  2.4.0 

**Code**

```ts
function foo(a: [], b: []): number {
    return a.length - b.length;
}

function callFoo() {
    foo([1], []);
}

```

**Expected behavior:**
Compiler should report the error in line 1: error TS1122: A tuple type element list cannot be empty.

**Actual behavior:**
Compiler crashes with the following stack trace:

```
Error: Debug Failure.
    at typeToString (D:\dev\proj\node_modules\typescript\lib\tsc.js:23452:22)
    at reportRelationError (D:\dev\proj\node_modules\typescript\lib\tsc.js:28778:34)
    at isRelatedTo (D:\dev\proj\node_modules\typescript\lib\tsc.js:28895:21)
    at checkTypeRelatedTo (D:\dev\proj\node_modules\typescript\lib\tsc.js:28761:26)
    at checkApplicableSignature (D:\dev\proj\node_modules\typescript\lib\tsc.js:33652:26)
    at resolveCall (D:\dev\proj\node_modules\typescript\lib\tsc.js:33884:17)
    at resolveCallExpression (D:\dev\proj\node_modules\typescript\lib\tsc.js:34043:20)
    at resolveSignature (D:\dev\proj\node_modules\typescript\lib\tsc.js:34221:28)
    at getResolvedSignature (D:\dev\proj\node_modules\typescript\lib\tsc.js:34241:26)
    at checkCallExpression (D:\dev\proj\node_modules\typescript\lib\tsc.js:34268:29)
```

**Comment by DanielRosenwasser** [comment] 2017-09-07 07:32
Duplicate of #17303.

**Closed** 2017-09-07 07:32 UTC
Labels: Duplicate
