### ISSUE TITLE
Show default arguments in signature help

### ISSUE THREAD

**Issue by Andy-QT** [Microsoft/TypeScript#29527] opened 2019-01-21 14:38 UTC
- VSCode Version: 1.30.2
- Language: JavaScript

Missing (=1) as parameter hint.

![grafik](https://user-images.githubusercontent.com/2870154/51480619-c0958a80-1d91-11e9-8688-7ffe33704464.png)

**Comment by mjbvz** [comment] 2019-01-22 17:19
Related to #27442

**Comment by mjbvz** [comment] 2019-01-24 23:35
Duplicate of #16665

**Closed by mjbvz** 2019-01-24 23:35 UTC
Labels: Domain: Signature Help, In Discussion, Suggestion
