### ISSUE TITLE
No props helper for indexed type function param

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#24825] opened 2018-06-09 09:13 UTC
Not sure how to formulate it in common terms, but here should be helper for X['A'] props:

![image](https://user-images.githubusercontent.com/736697/41189924-e2580a76-6bee-11e8-96f7-cbf64d8ac195.png)

```ts
  type X = {
    A: {
      a: number
    },
    B: {
      b: string
    }
  }

  const fn = <T extends keyof X> (type: T, param: X[T] ) => {}
  fn('A', {
    // here should be helper for X['A'] props
  })
```

TS 2.9.1

**Comment by DanielRosenwasser** [comment] 2018-06-09 18:44
Looks like a duplicate of #21022, but I really think we should try to solve this problem.

**Closed** 2018-06-28 23:04 UTC
Labels: Duplicate

**Comment by whitecolor** [comment] 2018-07-03 16:57
So, is it closed without resolution?
