### ISSUE TITLE
Give redeclaration errors on JSDoc @property declarations

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#18705] opened 2017-09-22 23:08 UTC
```js
/// @ts-check

/**
 * @typedef Props
 * @property x {number}
 * @property x {string}
 */
```

This should be an error assuming that we move forward with #15852.

**Comment by mhegazy** [comment] 2017-09-22 23:19
Duplicate of https://github.com/Microsoft/TypeScript/issues/15715

**Comment by mhegazy** [comment] 2017-10-09 16:49
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-09 16:49 UTC
Labels: Duplicate
