### ISSUE TITLE
Missing rule for not inserting spaces after/before braces

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11630] opened 2016-10-14 15:12 UTC
_From @shahata on October 9, 2016 17:55_
- VSCode Version: 1.5.3
- OS Version: macOS Sierra

Steps to Reproduce:
1. Add `"javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false` to the workspace settings
2. Type `const a = {b: 1};`
3. Format Code
4. Code is now formatted `const a = { b: 1 };`

I guess this is similar to https://github.com/Microsoft/TypeScript/issues/7540 and this rule considers only `[` and `]` as _brackets_ and actually a new rule `javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces` should be added to support _braces_: `{` and `}`

_Copied from original issue: Microsoft/vscode#13401_

**Comment by waderyan** [comment] 2016-10-14 15:12
_From @jrieken on October 10, 2016 14:47_

fyi - the pre-commit hooks goes with [`tsfmt.json`](https://github.com/Microsoft/vscode/blob/joh/fmtprio/tsfmt.json#L16), so if we change default we should keep them in sync

**Comment by waderyan** [comment] 2016-10-14 15:12
@shahata thank you for opening this issue. 

@dbaeumer this is confirmed on latest. Is this a feature request for TypeScript language service? Or something we need to implement on our end?

**Comment by waderyan** [comment] 2016-10-14 15:12
_From @dbaeumer on October 14, 2016 15:8_

@waderyan  Yes, I think so.

**Comment by mhegazy** [comment] 2016-12-16 01:09
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/9613

**Closed by mhegazy** 2016-12-16 01:09 UTC
Labels: Accepting PRs, Domain: Formatter, Suggestion, VS Code Tracked
