### ISSUE TITLE
Incomplete type narrowing when using type union with overloaded function

### ISSUE THREAD

**Issue by akatechis** [microsoft/TypeScript#57499] opened 2024-02-23 01:06 UTC
### 🔎 Search Terms

function overload union narrow 

### 🕗 Version & Regression Information

- I have tried this in `5.3.2`, and in playground `5.3.3` and `5.4.0-beta`.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.0-beta#code/C4TwDgpgBAYgdgRgDwEEA0UBCA+KBeKACgEMAuKFASn10wG4AoUSWOAJlQx3yLIowBG5AM7AATgEs4Ac2p5ajZtHgBmTllwES5dFCFRRkmRgDGI8VNk0sjJuGVx13AvGS7uAH1Yd3uL6qdsWwAzAFc4E2AJAHs4KAlhV0DCYPJ4QMpyYPjhVjcuXABvBihSqDEIYFCxOOCAOgAbCBlgAAt8PAIERgBfBgYwiKjYnPgfApS0x19MqGyE70CoYrLyyuraxubpNo6CNl7+wciYuISA30nWDKyc1jVfZZKyiqqaua2W9s6CFUOGAD0ACogSUgVAAJIAcgAJlAGhIANbQYDRPTQYgCJpQVFQEzEBoNHGtBYAdwkuxScAwUjAoWAlAwVJpcDpwEE1GiYiIwWp8VZ9NMlDBAIG4ROIxh0QAKiSZABxULEMQw5K8qb5DQstk6Wb0MVDU5QKWyyyK5Wqy7qxa+bX0nSCcxGWTkfXHYZxE1y6TmlVquBTB4FO3AB16J2WUwRmR6xjuo1es1Kv1WgPXW38nX8PQAfmj0lMeYMFhjrqeqwk2UI50QVMo1BWqxe63evOrAoZjFWfQrVZrbDrDeeTagAIBkKgpOioQacIgAA9IJE5lyoNKAMo4tFwZViaKk4ko+xQaLZAAGAjPW-RUAAVqFRFAz4ZLFfhFITA42FAALbEYAmK0EC5G00DCBAJixHC0QAG4QGIDTRMQMLDk2rwbHMcDtmyHJdmUPbNm8tRYbSgp6EK-zAqCUDggAEvB0ASFCP5QP+wAQD+YBRDIh4GMQP4ot6gj0lAD6WDi9inniQEmIiuRSKIEDISe2RKNIyZwsQwjgWIHrCCKBoSp6MregAwjJiL+hqgQhrqrpxuKHrGiZljmRBlmplM4xapm9rZvoL6ljYhlOYmMhubJVn3DZvmhv5+ZRsWzqxiFCYueFFlRekGakXFugCEWgUFnihUli6WDlmUlZEEoUkCHsUBQkVUJQAAZK1EmQFJJgNU1ZVQkOI6lOhrYkR2ggUahBGlNVhC1dk9U-I1zVtR1ACEJiDUNI3EdhZECJQeGlNNaxEZhe2dgwfRAA

### 💻 Code

```ts
/**
 * I create 3 different types, and then put them into a union.
 */
type Fn1<A, B> = (a: A) => B;
type Fn2<A, B> = (a: A, b: string) => B;
type Fn3<A, B> = (a: A, b: string, c: string) => B;
type Fn<A, B> = Fn1<A, B> | Fn2<A, B> | Fn3<A, B>;

/**
 * Now I create some type assertions so I can narrow down in the overloaded function.
 */
function isFn1<A, B>(f: Fn<A, B>): f is Fn1<A, B> {
    return f.length === 1;
}

function isFn2<A, B>(f: Fn<A, B>): f is Fn2<A, B> {
    return f.length === 2;
}

function isFn3<A, B>(f: Fn<A, B>): f is Fn3<A, B> {
    return f.length === 3;
}

/**
 * I'd like to be able to call this either
 * doThingGuard(fn, input) or
 * doThingGuard(fn, input, b) or
 * doThingGuard(fn, input, b, c)
 */
function doThingGuard<A, B>(fn: Fn1<A, B>, input: A): B;
function doThingGuard<A, B>(fn: Fn2<A, B>, input: A, b: string): B;
function doThingGuard<A, B>(fn: Fn3<A, B>, input: A, b: string, c: string): B;
function doThingGuard<A, B>(fn: Fn<A, B>, input: A, b?: string, c?: string): B {
    if (isFn1(fn)) {
        return fn(input);
    }
    if (isFn2(fn)) {
        // I would expect for TS to narrow the type of `b` to be just `string` since Fn2 matches the second overload
        // instead, it's inferred to be `string | undefined`
        return fn(input, b);
    }
    return fn(input, b, c);
}
```

### 🙁 Actual behavior

The compiler infers `b` and `c` to be string | undefined in all the if code blocks, even though I've narrowed the type of `fn` to be `Fn2` or `Fn3`.

### 🙂 Expected behavior

I expect the above code to properly narrow the types of `b` and `c` to be just `string` in the relevant `if` blocks, because I've properly narrowed the type of `fn` to the kind of `Fn` that is used in each individual overload signature.

### Additional information about the issue

In the playground, I tried doing something similar, but rather than using the `is` type guard functions, I checked whether `b` or `c` were not undefined (either through strict equality with `undefined` or with `typeof b === 'string'`) and none of these approaches seem to work.

I'm able to work around this by calling it with `!` but it would be nice to have the compiler know that what I'm doing is safe here, since the overload signatures should be restricting me from calling an Fn3 with fewer than 3 arguments.

```ts
fn(input, b!, c!);
```

**Comment by fatcerberus** [comment] 2024-02-23 01:21
Unfortunately it’s a known limitation that type narrowing in the implementation of an overloaded function doesn’t work based on the declared overloads - only the implementation signature matters.

**Comment by akatechis** [comment] 2024-02-23 01:23
> Unfortunately it’s a known limitation that type narrowing in the implementation of an overloaded function doesn’t work based on the declared overloads - only the implementation signature matters.

I see, so the overload signatures only matter when I'm calling the function, not when implementing it? That helps, thanks!

**Comment by fatcerberus** [comment] 2024-02-23 01:23
Roughly a duplicate of https://github.com/microsoft/TypeScript/issues/28167.

**Closed** 2024-02-26 01:25 UTC
Labels: Duplicate
