### ISSUE TITLE
IntelliSense Not working when using ramda 

### ISSUE THREAD

**Issue by BravenxX** [microsoft/TypeScript#39398] opened 2020-07-01 20:29 UTC
Issue Type: **Bug**

Sudenly VsCode IntelliSense stop working. It gets freeze in "Loading..." when hover a js function or class on my Js files with my mouse. I'm working with react native. Only js no Typescript

 **I did nothing but write code.**

I installed "JavaScript and TypeScript Nightly" extension but didn't work.

- VsCode: 
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

I repeat. **I did nothing but write code.**

**Comment by aecorredor** [comment] 2020-07-28 04:04
@BravenxX @mjbvz I had experienced the same exact problem with ramda's `curry` and had discussed it here: https://github.com/microsoft/TypeScript/issues/39398. It definitely seems to be the `@types/ramda` since @BravenxX is reporting the same thing I was experiencing.

CC: @amcasey

**Comment by sandersn** [comment] 2020-07-28 15:01
Sounds like we should add this usage to our test suite.

Also @pirix-gh, might you be able to take a look at ramda's types to see why this happens?

**Comment by imcotton** [comment] 2020-07-29 06:14
> Also @pirix-gh, might you be able to take a look at ramda's types to see why this happens?

I think he had changed user ID to @millsp

**Comment by millsp** [comment] 2020-07-29 11:31
Sure, I'll take a look

**Comment by millsp** [comment] 2020-07-30 09:28
It works well on my side, I could not reproduce the bug:

![Screenshot from 2020-07-30 11-25-15](https://user-images.githubusercontent.com/18401805/88906227-79763880-d257-11ea-9767-1bbd8ff28115.png)

Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T15:51:39.791Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-112-generic snap

**Comment by millsp** [comment] 2020-07-30 10:22
@aecorredor would you mind linking the issue you had? (you mistakenly linked this same issue)

**Comment by aecorredor** [comment] 2020-07-30 13:31
@millsp sorry about that, it's https://github.com/microsoft/TypeScript/issues/38339

**Comment by millsp** [comment] 2020-07-30 13:58
I'll be working during this year on more performant ways to write `curry` with overloads. In the meantime, if the actual `Curry` types cause problems, it should be reverted to what it used to be... But that will make some people scream! Or maybe typescript@4.0.0 will help fix these perf issues since it introduces variadic tuple types https://github.com/microsoft/TypeScript/pull/39094 (which are planned to be used in the upcoming [ts-toolbelt](https://github.com/millsp/ts-toolbelt)@7.0.0). For info,this PR cut the type instantiation count by 60%.

Another thing that I could do is to try to further optimize `Curry` types, not sure if it's possible, though. I would need a repro that fails, I'm not able to reproduce the error at the moment. This would give me ground to work on optimizations... Thanks if someone can do this :+1:

**Comment by millsp** [comment] 2020-07-30 20:50
@aecorredor @BravenxX @imcotton can you confirm that this is still happening? I recently pushed a series of lib-wide optimizations, maybe this could explain why I can't get the bug repro to work :thinking: Let me know.

**Comment by aecorredor** [comment] 2020-07-30 22:08
@millsp for what package? TS, ramda, or @types/ramda?

**Comment by millsp** [comment] 2020-07-30 23:11
@aecorredor for [ts-toolbelt](https://github.com/millsp/ts-toolbelt) which provides the `Curry` types for ramda. Would you be so kind to test if the repro still fails or not?

**Comment by aecorredor** [comment] 2020-07-31 05:20
@millsp I can confirm that the issue went away after upgrading `ts-toolbelt` to `6.13.36` 🎉. Hopefully it goes away for good. Merci beaucoup 🤘🏻. 

CC: @amcasey

**Comment by millsp** [comment] 2020-08-04 17:59
@sandersn, I think that we can close this issue with #38339

**Closed** 2020-08-05 22:31 UTC
Labels: Needs Investigation
