### ISSUE TITLE
Allow this typing and type parameters on static methods

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#7627] opened 2016-03-22 06:22 UTC
Since constructor visibility #2341 got merged. I haven't been able to utilise it fully because the classes I can benefit from requires type parameters and this typings on static methods.
```ts
abstract class Model<P> {
    static create(props: P): this {
        let model = window.store[this.name + props.id];
        if (model) {
            return model;
        }
        return window.store[this.name + props.id] = new this(props)
    }

    protected constructor(props: P) {
    }
}
```

The `Model` class is a base class.  A `this` typing would be very good to refer to the subclass instead of the base class. Since many classes has type arguments in their constructors, it makes sense to allow type arguments in static factory methods as well, otherwise you cannot create type safe factory methods.

**Comment by tinganho** [comment] 2016-03-22 06:33
Also since the original reason to allow visibility on constructors was to support static factory methods. So at least `this` typing on static methods needs to be supported to conform to the original reason.

**Comment by mhegazy** [comment] 2016-03-28 17:45
duplicate of https://github.com/Microsoft/TypeScript/issues/5863

**Closed** 2016-03-28 17:46 UTC
Labels: Duplicate, Suggestion
