### ISSUE TITLE
Passing bound callback to function taking unbound callback

### ISSUE THREAD

**Issue by danielrentz** [microsoft/TypeScript#35293] opened 2019-11-22 12:47 UTC
**TypeScript Version:**  3.7.2

**Search Terms:** bound unbound callback this parameter

**Code**

```ts
class C { public prop = 1; }
const c = new C();
 
function callUnbound(fn: () => void): void {
    fn();
}

function callBound(fn: (this: C) => void): void {
    //fn(); // compiler error as expected
    fn.call(c); // passes as expected
    callUnbound(fn); // passes unexpectedly (`callUnbound` does not call with context)
}

callBound(function () { console.log(this.prop); });
```

**Expected behavior:**
Last line in `callBound` causes a compiler error.

**Actual behavior:**
Last line in `callBound` passes the compiler, and `fn` will be called without `this` context.

**Playground Link:** 

**Related Issues:**

**Comment by jcalz** [comment] 2019-11-22 15:52
Duplicate of #7968

**Comment by fatcerberus** [comment] 2019-11-22 17:36
The `callBound()` call on the last line likely wouldn't be an error even with stricter `this` typing, because its argument function has no `this` annotation at all.   It's the same principle that you can pass a function with fewer parameters in place of one with more.  The `callUnbound()` call is where I would expect the compiler error, if one were to be produced.

**Comment by danielrentz** [comment] 2019-11-22 18:53
> The `callBound()` call on the last line likely wouldn't be an error even with stricter `this` typing, because its argument function has no `this` annotation at all. It's the same principle that you can pass a function with fewer parameters in place of one with more. The `callUnbound()` call is where I would expect the compiler error, if one were to be produced.

That's what I wanted to express with "Last line in (the function) callBound". :)

**Closed** 2019-11-22 18:55 UTC
Labels: Duplicate

**Comment by fatcerberus** [comment] 2019-11-22 19:01
Oops, you’re right, that was a brain fart.  I read it as “the last line, callBound, ...” 😬
