### ISSUE TITLE
Using Array.prototype.filter as a null-guard?

### ISSUE THREAD

**Issue by RonPenton** [Microsoft/TypeScript#18876] opened 2017-10-01 15:16 UTC
**TypeScript Version:**  2.4.0

**Code**

```ts
function noNulls(items: (string | null)[]): string[] {
    return items.filter(x => x !== null);   // return type is still (string | null)[]
}
```

**Expected behavior:**

Return type from filter should be string[]

**Actual behavior:**

Return type from filter is (string | null)[].

I know I can get around this by casting the end result, ala: 

```ts
function noNulls(items: (string | null)[]): string[] {
    return items.filter(x => x !== null) as string[];
}
```

But that just feels... bad. I'm guessing something like this is insanely complicated, but I figured I'd put this out there in case it isn't.

**Comment by jcalz** [comment] 2017-10-01 17:34
Duplicate of #16069?

**Comment by mhegazy** [comment] 2017-10-17 16:28
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-17 16:28 UTC
Labels: Duplicate
