### ISSUE TITLE
Feature Request / Proposal: Traits

### ISSUE THREAD

**Issue by yasselavila** [Microsoft/TypeScript#311] opened 2014-07-30 15:27 UTC
ORIGINALLY PROPOSED IN http://typescript.codeplex.com/workitem/838

Traits, as "compile-time" partial classes, would perfectly fit with TS ideology and resolve problems of multiple inheritance/mixins.

Traits in Scala: http://en.wikibooks.org/wiki/Scala/Traits
Traits in PHP: http://php.net/trait

I propose minimal traits similar to PHP implementation.

```typescript
trait FooTrait {
   // same as class definition, but no constructor allowed, e.g.:
   public foo() {
       return "foo";
   }
   private bar() {
       return "bar";
   }
}

class Foo {
    import FooTrait; //not insisting on exact keyword and syntax, just smth to start with

    // ...
}

class Bar {
    // rename methods:
    import FooTrait(foo => tfoo, bar => tbar);

    // and to include another trait, there is another import line:
    // import BarTrait;

    // ...
}
```

The code above could be compiled to JS below (can be optimized, just showing the main idea):

```javascript
var FooTrait = (function () {
    function FooTrait() {
        throw "Cannot instantiate trait FooTrait";
    }
    FooTrait.prototype.foo = function () {
        return "foo";
    };
    FooTrait.prototype.bar = function () {
        return "bar";
    };
    return FooTrait;
})();

var Foo = (function (_super, FooTrait) {
    function Foo() { }
    Foo.prototype.foo = FooTrait.prototype.foo;
    Foo.prototype.bar = FooTrait.prototype.bar;
    return Foo;
})(undefined, FooTrait);

var Bar = (function (_super, FooTrait) {
    function Bar() { }
    Bar.prototype.tfoo = FooTrait.prototype.foo;
    Bar.prototype.tbar = FooTrait.prototype.bar;
    return Bar;
})(undefined, FooTrait);
```

Unresolved name conflicts should raise a compile time error.

I think it would be a great advance for the language. But the proposal has more than one year made (in codeplex) ​​and has not yet been implemented.

**Comment by csnover** [comment] 2015-02-26 01:56
TypeScript team, are you guys open to receiving possible implementations of this feature?

**Comment by danquirk** [comment] 2015-02-27 01:28
We'd be open to implementations in the future but it's important that we first nail down a proposal we can all agree on. It'd be getting ahead of ourselves to start reviewing an implementation before we nail down what is and isn't the intended behavior here.

**Comment by csnover** [comment] 2015-02-27 02:10
No problem. SitePen is currently working on defining some package specifications for Dojo and this is one of the areas that we are looking to improve, so once we get a bit further along and actually begin the work of defining technical proposals those will be brought here. A prototype implementation would be useful to inform that decision-making and may form a suitable foundation for a final implementation, but these are early days, we have no code yet. I just didn’t want to have anyone on this side start going down the road and then find out that there is [no chance to accept this](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-features), or that after talking to @mhegazy about C3 linearization that you guys wanted to move in that direction instead.

**Comment by jbondc** [comment] 2015-02-27 15:03
@csnover I've been doing a couple of experiments, eventually settled on calling it an 'import class' (doesn't use any new keywords):
https://github.com/jbondc/ECMAScript/blob/master/lab/importClass/spec.ts

There's lots of details to work out, my philosophy is these declared 'composition things' should be immutable by default.

Would be interesting to know what happened to:
http://scg.unibe.ch/research/rotor?_s=YzoXCrbyJLJC8xxc&_k=LNQdzXB_&_n&27

Best guess is the ratio of benefit vs. complexity ratio in the compiler was quite low in C#.

**Comment by csnover** [comment] 2015-02-28 03:00
@jbondc Great! Looking over what you are proposing so far I would probably start by just focusing on the compiler side of things and not even thinking about any runtime enhancements in order to keep the initial feature very clear and focused (like the OP).

I understand not wanting to introduce new reserved words that weren’t future reserved words in the EcmaScript spec but `import class` is very unfortunate. The strawman introduced a “trait” adjective for class (trait class), which is better.

I/others will have additional feedback over the coming months on this.

**Comment by NoelAbrahams** [comment] 2015-03-01 10:47
@jbondc, there is a [similar proposal on the old codeplex site](https://typescript.codeplex.com/discussions/406449).  What do you think about it?

**Comment by jbondc** [comment] 2015-03-02 16:28
@NoelAbrahams Really like ~ extends() as a runtime version to augment an object 2(a). 

Typically traits are only intended to merged so they can't be used like regular objects:
```javascript
import class foo {
	world() {
		return super.hello() + ' world';
	}
}
```
Compiler doesn't complain that 'super' is missing. Check only happens when the 'trait/import class' is merged.

```javascript
class bar {
   import foo; // error: 'hello()' is missing, the compiler has to be able to infer what the 'super' structure looks like, be told somehow or just pretend its all good
}
```

@csnover Look foward to any feedback, agree that focus is important
 
1. Add support for compile time traits, some thoughts here:
  
  - Trait can't have a constructor method
  - Trait can extend another trait
  - Compiler error on import conflict

2. Try runtime extends() -- hardest

  extends() would behave:
  (a) more like mixin at runtime if passed a regular object (how do we know this at runtime?)
  (b) merges 'import class' by naming this and super

3. Experiment with Proxy
  - to get around Object.seal() but securely?

**Comment by csnover** [comment] 2015-03-13 03:00
Just a brief update for everyone watching: I should have a complete(ish) proposal to share in the next couple of days at the latest. Sorry for the delay.

**Comment by csnover** [comment] 2015-03-16 19:21
Our proposal is now available at https://docs.google.com/a/sitepen.com/document/d/112Xw-t8eh-eFIdKhn7LeDbGhO86XwlKv-Fwc6j9U-Oc/edit for discussion. (Please let me know if you prefer this to be in another format/location.) This proposal focuses purely on enhancing the compiler and doesn’t include any runtime enhancements.

Looking forward to your feedback and working with the rest of the team and community on refining these proposals into something that be implemented and added to TypeScript.

**Comment by yasselavila** [comment] 2015-03-16 20:03
@csnover +1... but ... what about use only 'trait' instead of 'traitclass'?

**Comment by RichiCoder1** [comment] 2015-03-16 20:04
@csnover agreed with @csnover. `trait class` seems very...peculiar to me. Especially since it, in the end, shares very little in common with `class`.

**Comment by csnover** [comment] 2015-03-16 21:04
The use of an adjective was taken from the ES strawman, I have no particular affinity for that grammar. This really is a first draft to get feedback so if people think the adjective is wrong then I’ll update the proposal until mostly everyone is happy :)

(I personally prefer multiple inheritance with C3 over traits since it covers more common use cases and is usually more intuitive for people that already know how single-inheritance works.)

**Comment by csnover** [comment] 2015-03-31 17:45
TypeScript team, do you have any feedback or can you let me know when you might have time to review this proposal? Is there information that is unclear that needs to be clarified before additional feedback can be solicited?

**Comment by RyanCavanaugh** [comment] 2015-03-31 20:38
I think the proposal is very clear. We're really busy wrapping up ES6 stuff at the moment so I can't give any hint of a timeline at this point.

**Comment by jbondc** [comment] 2015-04-01 11:23
@csnover Added some thoughts here:
https://github.com/jbondc/TypeScript/blob/traits/tests/labs/traits/feedback.ts

Added the 'constructor' option back.
Prefer to think of traits as things that are not JavaScript objects, the code gets flattened into the class (nothing is actually emitted unless import). So there's no need for __mixin(AB0.prototype, B.prototype);

I didn't understand the part 'They also enable automatic cross-cutting of concerns simply by inheriting multiple mixins, which is not possible with traits (in a traits model, the methods would conflict and could not chain together with super calls).'

Not sure if my emitted examples would work but think that the new ES6 symbols could be useful.

Note on syntax:
I'd also go with just 
a) trait nameA {}

b) import class nameB {}
 for the symmetry with 'class Foo { import nameB; }'

**Comment by billccn** [comment] 2015-04-07 12:25
This might qualify as a separated feature, but I am wondering can a runtime-only version of traits be implemented so that native objects can be augmented in a more OO fashion.

For example, say I define a "runtime trait" like

```
trait ChildList extends Element {
    get childList(): Element[] { /* iterate the HTMLCollection ... */ }
}
```

and then use it like `(someElement with ChildList).childList...`.

Emit for the trait could be the same as the current compile-time version (i.e. as prototype properties in a Function). For the call site, `Function.apply` can be used.

In the type system, such trait can be treated like an interface. (With the same `instanceof` problem that plagues the current mixins and the trait proposal above.)

**Comment by jbondc** [comment] 2015-04-07 13:28
@billccn It would be more like:
```javascript
trait ChildList {
    get childList(): Element[] { /* iterate the HTMLCollection ... */ }
}
extends(someElement, ChildList).childList... 
```
Or like you suggest 'with' , '+' as an operator may work too:
```javascript
(someElement with ChildList).childList... 
(someElement + ChildList).childList...
```
I'll point out traits aren't mixins:
https://github.com/reactjs/react-future/blob/master/01%20-%20Core/02%20-%20Mixins.js

That syntax is valid in the ES6 spec so we'll see how it evolves but find traits for web components & other use cases less fragile.

**Comment by jbondc** [comment] 2015-04-07 14:02
@csnover Here's an example of 'chaining' with traits:
https://gist.github.com/jbondc/b09d56dc4b8ed6c43af6

Much clearer then trying to follow super() calls everywhere.

**Comment by csnover** [comment] 2015-04-10 03:59
Thanks everyone for the feedback and sorry for the delay.

It would be nice to have a generic mechanism for combining types (like a `with` or `+`) but you would need to have a way to resolve conflicts which is isn’t possible with just a simple operator.

@jbondc

> Added the 'constructor' option back.

Agree on the constructors in traits, that was a mistake, can you put a comment on the proposal so I can remember to fix it there?

> I didn't understand the part 'They also enable automatic cross-cutting of concerns simply by inheriting multiple mixins, which is not possible with traits (in a traits model, the methods would conflict and could not chain together with super calls).'

OK, no worries, I will try to clarify in the proposal. To give a little more background here, one reason to prefer C3 over traits is to avoid having to do a lot of (keyboard) typing especially when you are composing things together. It also lets the consumer of a library avoid understanding the right method ordering for every conflict method in order for it to work.

So, as a concrete example, [dgrid](https://github.com/SitePen/dgrid/tree/master/doc), a responsive data grid widget, allows users to enhance its functionality by composing together classes adding in mixins/extensions. Users start with a base [Grid](https://github.com/SitePen/dgrid/blob/master/Grid.js), add keyboard navigation by mixing in [Keyboard](https://github.com/SitePen/dgrid/blob/master/Keyboard.js), and add column resizing by mixing in [ColumnResizer](https://github.com/SitePen/dgrid/blob/master/extensions/ColumnResizer.js), etc. Even though some of these mixins implement the same methods, everything almost always Just Works transparently and the user doesn’t have to think about sorting out how the super-calls should be ordered. So they can write:

```ts
class MyGrid extends Grid, Keyboard, ColumnResizer {}
```

and they are finished and everything just works.

In contrast using traits there would be numerous method conflicts, `buildRendering`, `destroy`, `postCreate`, `renderHeader` so it would end up needing to be more like this:

```ts
class MyGrid extends Grid {
  use Keyboard {
    destroy as destroyKeyboard,
    postCreate as pcKeyboard,
    // ... more here ...
  };
  use ColumnResizer {
    destroy as destroyColumnResizer,
    // ... more here ...
  };

  destroy() {
    super.destroy();
    this.destroyKeyboard();
    this.destroyColumnResizer();
  }

  postCreate() {
    super.postCreate();
    this.pcKeyboard();
    // ...
  }
}
```

And then if you ever change the way your grid is constructed you’d have to go through and find and fix all these methods explicitly too. Lots of work compared to letting C3 take care of it for you! (Replace the redirection with symbols and it’s still a similar problem.)

> https://gist.github.com/jbondc/b09d56dc4b8ed6c43af6

From what I see you are introducing a conflict since you have traits A and B used by class C and trait A also extends trait B, how would this be resolved? I don’t see any conflict resolution in this feedback gist. C3 automatically fixes this ambiguity by reordering dependencies of all inherited classes.

**Comment by csnover** [comment] 2015-04-10 04:03
Also, sorry, somehow I neglected to link to wikipedia on [C3 linearization](https://en.wikipedia.org/wiki/C3_linearization) for more background on how the algorithm works (it’s pretty straightforward!), I added the link in the proposal.

**Comment by jbondc** [comment] 2015-04-10 12:20
@csnover As long as the composing class implements all conflicting methods, there is no conflict reported by the compiler:
```javascript
class MyGrid extends Grid {
  import Keyboard;
  import ColumnResizer;

  buildRendering(){
    // what does this do? 
  }

  readerHeader(){
     // what does this do?
  }

  destroy() {
    super.destroy();
    this[Keyboard].destroy();
    this[ColumnResizer].destroy();
  }

  postCreate() {
    return this.pcKeyboard(super.postCreate());
  }
}
```

**Comment by jbondc** [comment] 2015-04-10 12:28
Good point on the operator (with or +), it woudn't be valid JavaScript too.

**Comment by jbondc** [comment] 2015-04-10 12:30
I can't remember now why 'constructor' (would or not) be allowed. I'll see if I can work out a patch at least to parse things in the upcoming weeks.

**Comment by anatoliyarkhipov** [comment] 2015-04-10 12:39
@jbondc 
> As long as the composing class implements all conflicting methods, there is no conflict reported by the compiler:
To be able to do this, programmer must know about all methods in all imported mixins and which of them are in conflict. Why he should if it is possible resolve this automatically like `dojo/declare` does (like in `dstore` example by @csnover)?

**Comment by jbondc** [comment] 2015-04-10 12:42
That's why traits are less fragile, see CLOS (3.3)
http://www.iam.unibe.ch/~scg/Archive/Papers/Duca06bTOPLASTraits.pdf

If you're using traits in a way that your traits have 5+ more conflicts, you have a design problem.

**Comment by RyanCavanaugh** [comment] 2015-04-28 00:02
There's a lot of overlap here with mix-ins; it would be bad (or at least treacherous) to do both. With mix-ins being a potential part of ES7/ES8+, we want to take the runtime side of this very conservatively and get TC39 to agree on a proposal in this area first.

Features specific to the type system to support these patterns are still on the table, but we'll track those in other issues.

**Closed by RyanCavanaugh** 2015-04-28 00:02 UTC
Labels: Declined, Suggestion

**Comment by xiphiaz** [comment] 2016-01-22 11:26
Is there an update on how/if mixins will become a first class capability of typescript rather than a bit of a hack with separated registration as it currently stands?

**Comment by kitsonk** [comment] 2016-01-22 11:35
> Is there an update on how/if mixins will become a first class capability of typescript rather than a bit of a hack with separated registration as it currently stands?

I am sure I will be corrected if I am wrong, but the TypeScript team have made it clear that because this is a domain that TC39 has indicated they will address, the team feel that this is something it doesn't feel it can introduce as it would likely cause incompatibilities with ES in the future.

The implications are, those of us who are passionate about it should be championing it within TC39.  The concepts of mixins/traits were part of the originally Harmony proposals, but didn't make it into the spec.  Also, as far as I am aware, there isn't any active advocacy on this specific area in TC39 at the moment.  Once there is a proposal sufficiently through the process in TC39, then I believe the TypeScript team would be more than glad to implement it.

**Comment by xiphiaz** [comment] 2016-01-22 11:39
@kitsonk thanks for the update, I guess we just have to hope for TC39, I'll see if I can find any discussion on the matter. I feel at this point that traits are the only major capability missing - I'm currently managing a site with ~50k sloc TS, and the mixin registrations are somewhat unwieldy.

**Comment by sanex3339** [comment] 2017-01-24 16:12
+1 for this feature

**Comment by ackimwilliams** [comment] 2017-02-21 07:45
What's the status on this feature?

**Comment by dylans** [comment] 2017-02-22 13:32
> What's the status on this feature?

See https://blogs.msdn.microsoft.com/typescript/2017/02/02/announcing-typescript-2-2-rc/ ... basically they're not adding new language grammar, but by making some changes to the way Classes work, it's possible/easier to achieve now.

**Comment by alexeygolev** [comment] 2017-03-07 07:37
One powerful pattern that is possible with traits is this (similar to what @jbman mentioned):
```ts
trait AccountService {
  debit: (account: Account, amount: number) => Account;
  credit: (account: Account, amount: number) => Account;
  transfer(from: Account, to: Account, amount: number): [Account, Account, number] {
    return [this.debit(from, amount), this.credit(to, amount), amount]  
  }
}
```
This is not something that TC39 can help us with as in this particular form it's only relevant to statically typed languages. It can be done with `abstract` classes but then we lose the benefit of the mixin pattern as we move the problem into the inheritance area. Trait composition also makes pattern such as "cake" pattern possible.

**Comment by samfrances** [comment] 2017-07-28 11:42
+1

**Comment by michaelolof** [comment] 2017-11-04 11:08
You can have a look at a simple library i wrote at [](https://github.com/michaelolof/typescript-mix) I think it fits nicely into how you would want to use traits/mixins
