### ISSUE TITLE
T wider in lazy branch of T | (() => T) for known T

### ISSUE THREAD

**Issue by pckilgore** [microsoft/TypeScript#55277] opened 2023-08-05 00:27 UTC
### 🔎 Search Terms

T | (() => T)
"T | (() => T)" inference
inference of lazy generic type
lazy generic inferred too wide

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about callbacks and functions and laziness and sum types.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBA8mwEsD2A7AhgGwyAMmgXiADwAqAfFALxQlQA+UAFIwJRUUksBQokUAsiBLho1AN5Q0ALigAjJEgwQ0KKAF8uAY1QBnYFABmq6o2Ay4iVJmx5CRQcMhk2lCmI1cjjCdKjAATgCuEAA0UDoAFkiBGAAmAGJoCBgyAIxqbAD0mVAAIhA6CP5oskqeKMwuFN6SMgHBYZHRcQZJKVAA5MARCDpQsUgFUChI+q3JYQDuPZoRUL1yaLEd6ixZOQBCS0A

### 💻 Code

```ts
type OptionallyLazy<T> = T | (() => T)
type MyType = { a: boolean }
const fn = (t: OptionallyLazy<MyType>) => {}

fn({ a: true, shouldFail: 'it does, good'})
fn(() => ({ a: true, shouldFail: 'this does not fail, which is bad' }))
```

### 🙁 Actual behavior

No type error for `shouldFail` on last line above.

### 🙂 Expected behavior

Type error for `shouldFail` on last line above, same as line above it.

**Comment by fatcerberus** [comment] 2023-08-05 01:05
`() => MyTypeWithExtraProps` is assignable to `() => MyType`, so this is working as intended.  The error you see in the first case is due to the excess property check (EPC), which only applies to object literals directly assigned to a type.  The error message for EPC is currently misleading; see https://github.com/microsoft/TypeScript/pull/55152.

**Comment by RobertSandiford** [comment] 2023-08-05 13:13
Discussed in some detail here #55113

Objects are allowed to have additional properties, however special checks are applied in some locations just to catch probable bugs. As said in other places, this is more of a warning than a type error.

[excess-property-checks](https://www.typescriptlang.org/docs/handbook/2/objects.html#excess-property-checks)

**Comment by pckilgore** [comment] 2023-08-05 15:47
Ahh, appreciate the notes. I wish the error message for those checks were more clear they are a lint, and not a type system property. I've been operating under this misunderstanding for years writing TS!

Any known good workarounds? I guess I can write a Lint rule to require annotation of a lazy value? This caused a very insidious misspelling bug.

Thanks again.

**Closed** 2023-08-05 15:47 UTC

**Comment by RobertSandiford** [comment] 2023-08-05 15:57
> Ahh, appreciate the notes. I wish the error message for those checks were more clear they are a lint, and not a type system property. I've been operating under this misunderstanding for years writing TS!
> 
> Any known good workarounds? I guess I can write a Lint rule to require annotation of a lazy value? This caused a very insidious misspelling bug.
> 
> Thanks again.

I don't see any option other than explicit typings. There is an open suggestion (#12936) for Exact types that are always checked this way, maybe one day that will happen.

**Comment by fatcerberus** [comment] 2023-08-05 15:57
> I wish the error message for those checks were more clear they are a lint, and not a type system property. I've been operating under this misunderstanding for years writing TS!

You’re certainly not alone.  Thats why I’m glad for #55152.
