### ISSUE TITLE
Import/Export TypeScript 1.5 modules from different npms

### ISSUE THREAD

**Issue by christyharagan** [Microsoft/TypeScript#3421] opened 2015-06-08 17:28 UTC
Hi all,

I'm wondering what the best approach is to this particular problem. I have a suggested approach, but hoped there might be a better more "out-of-the-box" solution.

Essentially I am trying to do the following:

Create two npm projects: A, and B with the following layouts:

A
 -> lib
  - -> foo.ts

B
  -> lib
   - -> bar.ts

foo.ts looks like:

```TypeScript
export function myFunc(){}
```

bar will import foo's default function.

What I would like is for the syntax to be such that when we compile this down to javascript commonjs, it "just works". E.g.: we should be able to do something like:

bar.ts:

```TypeScript
import {myFunc} from 'a/lib/foo'
```
(with corresponding js output of:
```JavaScript
var myFunc = require('a/lib/foo').myFunc
```
)

The problem is I don't really see a way of doing this easily. I certainly don't see a way of doing this "at scale", where we can imagine very large projects.

My "suggestion" is to create a d.ts file that looks something like this:

```TypeScript
declare module Foo {
  export function myFunc()
}

declare module "a/lib/foo" {
  export = Foo
}
```
This d.fs would then have similar declarations for each file.

In the short term, this could be automated with a build tool (grunt, gulp etc.), but ideally would be a compiler option.

As a final note, I know the ES6/TS1.5 module system vis-à-vis node.js is still baking (especially around the idea of default exports), and perhaps there are other approaches, or better ideas. But thought I'd ask the question and see what the community is thinking on this topic.

**Comment by christyharagan** [comment] 2015-06-08 17:36
There is a limitation in my approach. This would only work when the compiled javascript files are either all minified into one, or sit individually but in the same folder as the typescript files - which I personally think is messy.

All in all, there's not a clear answer in my mind... but I'm sure someone out there has a neat answer :)

**Comment by mhegazy** [comment] 2015-06-08 20:29
The problem is that the compiler does not follow node resolution logic to resolve, this is tracked by #2338; once this support is in, your import of "a", will resolve to "node_module\a\index.d.ts" for instance, and allows you, and your package users to get the correct typings.

**Comment by jasonswearingen** [comment] 2015-07-20 17:44
Not sure this is really a dupe of #2338, this seems more of a specific use-case scenario request.

FYI:  I also have this exact use-case need.  I have a lot of libraries that currently need to live in a single super-sized project because Typescript doesn't recognize .ts files in external (NPM) modules.

**Comment by mhegazy** [comment] 2016-02-20 05:23
this should now.

**Closed by mhegazy** 2016-02-20 05:23 UTC
Labels: Duplicate
