### ISSUE TITLE
incorrect compilation failure because tsc loads node_modules/@types/**/*.d.ts irrespective of their usage. 

### ISSUE THREAD

**Issue by reshadi** [Microsoft/TypeScript#11949] opened 2016-10-30 21:44 UTC
Hi,

**TypeScript Version:**  2.0.6 

**Code**

``` ts
a.ts contains:
console.log(1);

run these commands:
npm install supertest @types/supertest
tsc --module commonjs --target es5 --listFiles a.ts

```

**Expected behavior:**

```
a.ts
```

**Actual behavior:** 

```
node_modules/@types/superagent/index.d.ts(83,31): error TS2304: Cannot find name 'Promise'.
%AppData%/npm/node_modules/typescript/lib/lib.d.ts
a.ts
C:/types-bug/node_modules/@types/node/index.d.ts
C:/types-bug/node_modules/@types/superagent/index.d.ts
C:/types-bug/node_modules/@types/supertest/index.d.ts
```

*\* Problem **
It looks like the tsc compiler loads node_modules/@types/\* */ *.d.ts irrespective of their usage.

I thought that in the node module resolution mode, the behavior of the compiler should be to look for .ts or .d.ts files first in the "node_modules/X" then in the "node_modules/@types/X" only when it sees an "import 'X'" in the code. Instead it looks like tsc loads everything in node_modules/@types first.

One use case that this causes problem is when you have both server and client side code and want to compile the server side to es6 and client to es5.

Thanks.

**Comment by aluanhaddad** [comment] 2016-10-30 22:19
Possible duplicate of #11917

**Comment by mhegazy** [comment] 2016-12-16 03:27
use `--types ` or set `types: []` in your tsconfig.json. this will instruct the compiler to load nothing. Please see more documentation at www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

**Closed** 2017-04-21 16:41 UTC
Labels: Working as Intended
