### ISSUE TITLE
jsDoc use overloaded function documentations in intellisense.

### ISSUE THREAD

**Issue by aliemre1990** [microsoft/TypeScript#30940] opened 2019-04-15 18:23 UTC
Issue Type: <b>Feature Request</b>

It would be nice to see variations of functions documented like below code, when typing the function. I documented overloaded function according to this link https://github.com/jsdoc3/jsdoc/issues/1017 .
```
/**
 * Returns imported styles in 'dir/dir/style.scss' format.
 * @returns {string[]} Imported style's paths.
 *//**
* Returns imported styles in 'dir/dir/style.scss' format.
* @param {string} content File content to be used in operation.
* @returns {string[]} Imported style's paths.
*/
StyleFile.prototype.getImportedStylePaths = function (content) {
    if (!content)
        content = this.content;
....
}
```
Current behavior when typing.
![issue-overload-1](https://user-images.githubusercontent.com/12927303/56154863-48221c80-5fc2-11e9-9ddd-e8167693e612.jpg)
Expected to be like below. ( Would like to see '+ overload').
![issue-overload-2](https://user-images.githubusercontent.com/12927303/56155052-a949f000-5fc2-11e9-884d-30393636d194.png)
And current behavior after typing
![issue-overload-3](https://user-images.githubusercontent.com/12927303/56155288-43aa3380-5fc3-11e9-9ec8-0651c860d38f.jpg)
Expected. I would like to move with arrows between variations.
![overload-issue-4](https://user-images.githubusercontent.com/12927303/56155472-a56a9d80-5fc3-11e9-8fb5-c3d66878da67.jpg)

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment] 2019-04-15 18:30
Related #25590

**Comment by zavr-1** [comment] 2019-05-11 13:43
@aliemre1990 good luck waiting for a few years before this issue gets addressed. MS only wants people to use TS so I wouldn't count on your issue being resolved any time soon. If you reading this in 2021, what did I say?

**Comment by sandersn** [comment] 2019-07-25 22:40
Duplicate of #25590.

**Closed by sandersn** 2019-07-25 22:40 UTC
Labels: Awaiting More Feedback, Suggestion

**Comment by JoakimCh** [comment] 2020-12-05 21:04
> @aliemre1990 good luck waiting for a few years before this issue gets addressed. MS only wants people to use TS so I wouldn't count on your issue being resolved any time soon. If you reading this in 2021, what did I say?

You seem to have a point, almost 2021 now.

**Comment by kPepis** [comment] 2021-02-26 03:08
Welp, it is 2021 and I just landed here 🤷

**Comment by HunterKohler** [comment] 2021-06-26 21:01
I am not a big Typescript fan (probably because I'm a C++ fan) but I'm such a big IntelliSense fan.

+1 to this to support the bitter JSDoc clingers like myself.

**Comment by igorskyflyer** [comment] 2021-07-19 01:52
+1, just spent 2.5h trying to get overloads to appear properly in Intellisense in a TypeScript project; it was a JavaScript project but I converted it to TypeScript, hoping I could get overloads + JSDocs to work. It does work, I got my overloads with proper types, documentation about parameters and you can go through the overloads when auto-completing, but... Never going that road again.

**Comment by Darker** [comment] 2022-09-30 00:52
Another year behind us, we still one this. Just like @HunterKohler I'm a C++ programmer and a stickler for JSDoc+vanilla JS, mostly because I don't really want to be compiling a script language.
