### ISSUE TITLE
Suboptimal compilation for rest parameters

### ISSUE THREAD

**Issue by a-bronx** [microsoft/TypeScript#19182] opened 2017-10-14 07:01 UTC
There is an TS/ES.next idiom for the JS `arguments` array: `(...args: any[])`. But using it may produce suboptimal transpilation result, for example:

```ts
function debug(...args: any[]) {
    if (!settings.debug) return;
    console.log("DEBUG:", ...args);
}
```
produces following JavaScript (ES5) code:
```js
function debug() {
    var args = [];
    for (var _i = 0; _i < arguments.length; _i++) {
        args[_i] = arguments[_i];
    }
    if (!settings.debug)
        return;
    console.log.apply(console, ["DEBUG:"].concat(args));
}
```
Note that the `arguments` is copied to the `args` array immediately at the beginning of the function, before its real usage. This causes the code executed every time the `debug()` function is called, even if it is unnecessary.

Expected behavior would be something more intelligent: either moving the `arguments` unrolling code closer to the usage place (may be tricky if there are multiple usage points), or using `Array.prototype.slice.call(arguments)` in-place without copying it into the temporary `args`.

Compare with Babel's transpilation result:

```js
function debug() {
    var _console;

    if (!settings.debug) return;

    for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
        args[_key] = arguments[_key];
    }

    (_console = console).log.apply(_console, ["DEBUG"].concat(args));
}
```
Note that here the copying was moved past the conditional expression and happens only when needed.

**Comment by RyanCavanaugh** [comment] 2017-10-30 22:36
Accepting PRs for the following optimizations (doesn't need to have all of them):
 * Move the array copy emit to the first top-level statement which is before any statement which references it
 * Elide the array copy emit if it's never referenced
 * Elide the array copy emit if all accesses of the rest arg are of the form `x[k]` where `k` is a numeric literal, and replace `k` with `k + n` (where `n` is the correct offset)

**Comment by Kingwl** [comment] 2017-11-02 03:13
ping @RyanCavanaugh 
i need some help plz  
i have to find all reference when emit the array copy  
and are there any utils or field for that?  
or i must foreach all node?

**Comment by charlespierce** [comment] 2017-11-27 16:34
@kingwl Are you still working on this issue? I'd like to take a swing at implementing some of the optimizations but don't want to duplicate work.

**Comment by ORESoftware** [comment] 2017-11-27 22:52
+1

**Comment by Kingwl** [comment] 2017-11-28 02:42
@charlespierce No, I'm not on it, please feel free

**Comment by charlespierce** [comment] 2017-11-28 20:53
PR Opened with implementation of the first two bullet points: #20307

**Comment by ORESoftware** [comment] 2017-11-29 18:32
+1

**Comment by RyanCavanaugh** [comment] 2017-11-29 19:23
@ORESoftware please don't leave +1 comments; use the GitHub reactions feature (👍 on the issue). And there's certainly no point to multiple +1 comments on the same issue

**Comment by ORESoftware** [comment] 2017-11-29 19:31
oh sorry I didn't realize I had already done that! yeah I haven't figured out how to use the reactions but I will now

**Comment by charlespierce** [comment] 2018-01-20 06:14
@RyanCavanaugh The PR for this issue #20307 is still awaiting review. I recognize it's a big diff, touching so many existing baselines, so is there anything I can do to help make it more manageable?

**Comment by DanielRosenwasser** [comment] 2020-07-08 00:57
I think this is a duplicate of https://github.com/microsoft/TypeScript/issues/498

**Closed** 2020-07-10 18:00 UTC
Labels: Duplicate

**Comment by a-bronx** [comment] 2020-07-10 20:47
I think it is a different issue. The #498 is about TS generating code for unused rest parameter. This issue is about rest parameters that are used in some (possibly rare) code paths, but generated code is placed into all code paths, making it suboptimal.
