### ISSUE TITLE
add `in`, `out` modifiers to allow being specific of expected contrvariant/covariant type parameters

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#8137] opened 2016-04-17 18:01 UTC
Problem: in the current state of affairs although convenient to certain audiences the bivariance is a gaping hole in the type system

Solution: 
- allow optional but explicit `in` and `out` modifiers like in C# for those who wants to take advantage of stricter typechecking
- keep bivariant typechecking for anyone who doesn't care:

```typescript
Array<a> {
   map:  <b>(map: (value: a) => b) => b[];
)

declare var animals: Array<Animal>;
declare var copyCat: (cat: Cat) => Cat

animals.map(copyCat); // expected not to typecheck, currently allowed no problem

// but if we go

Array<in a> {
   map:  <b>(map: (value: a) => b) => b[];
)

// then

animals.map(copyCat); // doesn't typecheck anymore as expected

```

 #6102 spinoff

**Comment by RyanCavanaugh** [comment] 2016-04-18 16:39
Duplicate of #1394

**Closed** 2016-04-19 20:34 UTC
