### ISSUE TITLE
The problem with Omit utility type

### ISSUE THREAD

**Issue by Gautamvaishnav-git** [microsoft/TypeScript#56284] opened 2023-11-01 07:53 UTC
### 🔍 Search Terms

When we use **Omit utility type** we don't get auto-completion like we have in pick.

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

I just created my own utility type called **OmitKeys**

```ts

type OmitKeys<Type, K extends keyof Type> = Omit<Type, K>

```

### 📃 Motivating Example

```ts

type A = {
    name: string,
    age: number,
    class: string
}


type OmitKeys<Type, K extends keyof Type> = Omit<Type, K>

type a = OmitKeys<A, "age" | "name">
```

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

**Comment by MartinJohns** [comment] 2023-11-01 08:43
> ### 🔍 Search Terms
> When we use **Omit utility type** we don't get auto-completion like we have in pick.

Try using keywords as search terms, then you might have better luck finding the duplicates.

---

You didn't fill out the issue template, so it's unclear what you're actually suggesting. Under "Suggestion" you just wrote "I created my own type", nothing more.

If you're suggesting to change `Omit<>` to use `keyof T`, then it's a duplicate of #30825 (and many many others). If you're suggesting to add the `OmitKeys<>` type to the standard library, then it's out of scope as the team decided to not add further utility types unless they're needed for emit purposes.

**Comment by fatcerberus** [comment] 2023-11-01 14:36
Also see https://github.com/microsoft/TypeScript/issues/54451

**Comment by RyanCavanaugh** [comment] 2023-11-01 16:39
Duplicate #56135? But it's hard to tell what you want here without filling out the template more concretely.

**Closed by RyanCavanaugh** 2023-11-01 16:39 UTC
Labels: Unactionable
