### ISSUE TITLE
IntelliSense breaks with jsconfig / certain require statement

### ISSUE THREAD

**Issue by NickGrease** [Microsoft/TypeScript#7831] opened 2016-04-05 15:00 UTC
- VS Code 10.14
- Windows 10 (1511)
- Possibly related to #7824 from a users point of view.

Steps to Reproduce:
In a new empty project:

- Create a file called cfx.js with the following content

```js
'use strict';
exports.generateCanvas = function (fileOrUrl) {
    console.log(fileOrUrl);
};
```

 - Create a file index.js

```js
'use strict';
var cfx = require('./cfx.js');
```
Note the `.js` extention in the require statement.

- Using the green light bulb in lower right hand corner, add a `.jsconfig.json` file to the project, save it with default settings.
- In `index.js` type `cfx.` and note that intellisense is not working correctly (`generateCanvas` not showing)
- Delete file `.jsconfig.json` and **restart**
- In `index.js` type `cfx.` and note that intellisense **is** working correctly (`generateCanvas` is available)

##### Notes: 
*without* the presence of jsconfig; intellisense, at least superficially works regardless of file ext. being included in require statement.

*with* the presence of jsconfig; removing the the file extension in require statement results in proper intellisense behavior.

**Comment by mhegazy** [comment] 2016-04-05 18:22
The issue is we are using the `classic` module resolution strategy as a default if target is `ES6`. that does not seem to be correct.

As a work around, in your jsconfig.json, specify a moduleResoltion:

```JSON
    "moduleResolution": "node"
```

**Comment by basarat** [comment] 2016-04-06 03:17
> The issue is we are using the classic module resolution strategy as a default if target is ES6

I'd like to vote for `node` module resolution as default unless explicitly specified to be something else :rose:

**Comment by NickGrease** [comment] 2016-04-06 04:26
> As a work around, in your jsconfig.json, specify a moduleResoltion

I'm very glad to hear it's as simple as that for the user. Thanks for the info!

**Comment by mhegazy** [comment] 2016-04-20 23:49
this looks fixed in latest.

**Closed by mhegazy** 2016-04-20 23:49 UTC
Labels: Bug, Fixed, Salsa
