### ISSUE TITLE
Assignability type annotations

### ISSUE THREAD

**Issue by jscheiny** [microsoft/TypeScript#48475] opened 2022-03-29 21:35 UTC
# Suggestion

## 🔍 Search Terms

type annotation, match types, assignability, type inferrence

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
Add a way to declare a variable and have its type be inferred from its initial value but check that it is assignable to a given type annotation.

I don't have any great ideas for what the syntax of this would be but here are a few suggestions:

- Using a new `matches` type operator that is only allowed at the beginning of a type annotation:

    ``` ts
    const x: matches { [key: string]: string } = { ... };
    ```
- Using a new operator to replace the `:` type annotation operator. I don't have a great suggestion for what that operator should be, so I'm using `%` as a placeholder here:
    ```ts
    const x% { [key: string]: string } = { ... };
    ```

## 📃 Motivating Example
Suppose I'm declaring an object with arbitrary keys whose values are supposed to be of the form `${string}.v${number}`. For example:

```ts
const PageSections = {
    HEADER: "header.v1",
    BODY: "body.v1",
};
```

I want to be able to interact with the members of this easily by referencing `PageSections.HEADER`. However, there's nothing enforcing the contract on the values currently. If I tried to do this I would have to write this declaration as:

```ts
const PageSections: { [key: string]: `${string}.v${number}` } = {
    HEADER: "header.v1",
    BODY: "body.v1",
};
```

This works to check that I wrote each value correctly (e.g. if I wrote `HEADER: "header-v1"`, I would get a compile error as I would hope). However, this erases the information about the keys and lets me index into this arbitrarily, e.g. `PageSections.FOOTER` is not defined but compiles just fine.

There are a few workarounds that would work here but they're not ideal.

### Workaround 1

Add a separate keys type union or enum:

```ts
type PageSectionKeys = "HEADER" | "BODY";

const PageSections: Record<PageSectionKeys, `${string}.v${number}`> = {
    HEADER: "header.v1",
    BODY: "body.v1",
} as const;
```

This works but feels unnecessarily duplicative and if we wanted to maintain type information about the values (if we cast via `as const`) then that is still lost:

```ts
type PageSectionValues = typeof PageSections[PageSectionKeys];
// Resolves to `${string}.v${number}` instead of "header.v1" | "body.v1"
```

### Workaround 2

Add a separate variable which checks for the assignability:

```ts
const PageSections = {
    HEADER: "header.v1",
    BODY: "body.v1",
} as const;

const pageSectionsTest: { [key: string]: `${string}.v${number}` }  = PageSections;
```

This comes with a few downsides:
1. I have to create a separate variable which goes unused and TS will complain about if I'm using `noUnusedLocals`. I could export this but that's a hacky workaround and exposes and unnecessary variable in the API.
2. The error that I get from this isn't where the error actually occurred. In order to fix this issue, I need to decipher an error message and trace it back to a particular error

## 💻 Use Cases
If this feature were to be adopted, then we could write the example above as:

```ts
const PageSections: matches { [key: string]: `${string}.v${number}` } = {
    HEADER: "header.v1",
    BODY: "body.v1",
};
```

In this case if I make a mistake and type `"header.v1"` instead as `"header-v1"` I get an error at the place I expect. But I also will have the keys be strongly typed so typing `PageSections.HEADR` will read as an error. Additionally if I add `as const` to the end of this I can strongly type the values as:

```ts
type PageSections = typeof PageSections[keyof typeof PageSections];
```

**Comment by whzx5byb** [comment] 2022-03-29 22:04
You could write the example as:

[Playground](https://www.staging-typescript.org/play?ts=4.7.0-pr-46827-30#code/MYewdgzgLgBACgQwOYFMDKLhQJbgjAXhgG8AoGCmACQFEBBAERoCUAuGAIgAsUEATFACcAdADcAjBwA05SgCEA8gwCa7DgCMQfAJ5jJMgL4wICHBABm2FPmIwA2gGsU29tEHYwSALrsABgBJiNw8kAzFAsABXAFt1IQNfGCMAbiA)
```ts
const PageSections = {
    HEADER: "header.v1",
    BODY: "body.v1",
} satisfies { [key: string]: `${string}.v${number}` }
```
if https://github.com/microsoft/TypeScript/pull/46827 is merged.

**Comment by RyanCavanaugh** [comment] 2022-03-31 16:18
Treating as duplicate of #47920

**Closed** 2022-04-02 18:00 UTC
Labels: Duplicate
