### ISSUE TITLE
Uninitialized public fields don't conform to tc39 spec

### ISSUE THREAD

**Issue by Xapphire13** [microsoft/TypeScript#32671] opened 2019-08-01 23:00 UTC
**TypeScript Version:**  3.5.1

**Search Terms:** public field uninitialized initialized tc39

**Code**

```ts
class X {
    foo: number;
}
```

**outputs**
```js
"use strict";
var X = /** @class */ (function () {
    function X() {
    }
    return X;
}());
```
(Notice how the field `foo` doesn't exist`)

**Expected behavior:**
Output JS should match the tc39 spec (initialize the field to `undefined`) as specified [here](https://github.com/tc39/proposal-class-fields#fields-without-initializers-are-set-to-undefined). See [babel playground](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEBiD29oG8BQ1oDNEC5oDsBXAWwCMBTAJwG5UBfVIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.5.5&externalPlugins=%40babel%2Fplugin-proposal-class-properties%407.5.5%2C%40babel%2Fplugin-transform-typescript%407.5.5) for implementation that matches tc39 spec

**Actual behavior:**
Output JS simply ignores the field

**Playground Link:** https://www.typescriptlang.org/play/?target=1#code/MYGwhgzhAEAa0G8BQ1XQGYHtMC5oDsBXAWwCMBTAJwG4kBfIA

**Related Issues:** none

**Comment by IllusionMH** [comment] 2019-08-02 09:57
Duplicate of #27644?

**Comment by Xapphire13** [comment] 2019-08-02 16:23
@IllusionMH, very similar, I think #27644 addresses the broader spec, whereas this issue captures only the uninitialized fields.

Feel free to dupe (this issue can serve as improved search-ability =])

**Closed** 2019-08-05 18:00 UTC
Labels: Duplicate
