### ISSUE TITLE
Cannot find type definition file for 'vite/client'.

### ISSUE THREAD

**Issue by adoin** [microsoft/TypeScript#54629] opened 2023-06-13 01:28 UTC
# Bug Report

### 🔎 Search Terms
vite/client
typescript define vite type

### 🕗 Version & Regression Information

- This changed between versions 5.0.5  and 5.1.3.

### ⏯ Playground Link

[Load and run tscheck script](https://codesandbox.io/p/github/adoin/tsc-issue-repro/draft/stupefied-pare?file=/package.json:8,30&workspaceId=662eae0c-04e4-4597-b3d3-b0b731b74003)

### 💻 Code
It happens before code, can't read config only.
```json
{
    "compilerOptions": {
      "types": [ "vite/client","node"],
      "typeRoots": ["./node_modules/@types/", "./types"],
  }
}
```

### 🙁 Actual behavior
I want to use tsc, but it seems can not read vite/client.d.ts as vite type, which is need in project.

### 🙂 Expected behavior
vite/client in types can be successfully read.

**Comment by Blackfaded** [comment] 2023-06-13 05:48
Yan confirm this. 5.0.4 is working for me. 5.1.3 breaks with this error:

```json
    "types": ["vite/client", "vitest/globals", "node"],
```


```
error TS2688: Cannot find type definition file for 'vite/client'.
  The file is in the program because:
    Entry point of type library 'vite/client' specified in compilerOptions

  tsconfig.json:20:15
    20     "types": ["vite/client", "vitest/globals", "node"],
                     ~~~~~~~~~~~~~
    File is entry point of type library specified here.

error TS2688: Cannot find type definition file for 'vitest/globals'.
  The file is in the program because:
    Entry point of type library 'vitest/globals' specified in compilerOptions

  tsconfig.json:20:30
    20     "types": ["vite/client", "vitest/globals", "node"],
                                    ~~~~~~~~~~~~~~~~
    File is entry point of type library specified here.
```

**Comment by MartinJohns** [comment] 2023-06-13 08:44
Most likely an incompatibility with pnpm. Try running the setup without pnpm, or try to update your pnpm version.

**Comment by Blackfaded** [comment] 2023-06-13 09:17
I am using yarn

**Comment by adoin** [comment] 2023-06-13 09:47
> Most likely an incompatibility with pnpm. Try running the setup without pnpm, or try to update your pnpm version.

Nothing different, 
![image](https://github.com/microsoft/TypeScript/assets/20517172/6d49e6ab-263b-48e7-b494-e6fe1e7b3f00)

**Comment by RyanCavanaugh** [comment] 2023-06-13 15:18
I don't have access to the sandbox link, not that I'm going to run an arbitrary script if I did

This looks like a duplicate of #54390 and caused by https://devblogs.microsoft.com/typescript/announcing-typescript-5-1/#explicit-typeroots-disables-upward-walks-for-node_modules-types

**Comment by RyanCavanaugh** [comment] 2023-06-13 15:19
I will ask a second time for a concrete actionable repro. Please do not log a third bug without this information.

**Closed by RyanCavanaugh** 2023-06-13 15:19 UTC
Labels: Unactionable

**Comment by adoin** [comment] 2023-06-13 15:22
> I will ask a second time for a concrete actionable repro. Please do not log a third bug without this information.

https://github.com/adoin/tsc-issue-repro
This can reprod

**Comment by RyanCavanaugh** [comment] 2023-06-13 15:55
This is working as intended. Your tsconfig says
```
"typeRoots": ["./node_modules/@types/", "./types"],
```
The file you're expecting to find is in
```
node_modules/vite/
```
Note that `node_modules/vite/` is not a subdirectory of `node_modules/@types` nor `types`


You need to add `node_modules` to your typeRoots:
```
    "typeRoots": ["./node_modules/@types/", "./types", "./node_modules"],
```
and you will see the expected behavior

**Comment by adoin** [comment] 2023-06-14 01:13
> This is working as intended. Your tsconfig says
> 
> ```
> "typeRoots": ["./node_modules/@types/", "./types"],
> ```
> 
> ![](chrome-extension://annlhfjgbkfmbbejkbdpgbmpbcjnehbb/images/saveicon.png) Save
> The file you're expecting to find is in
> 
> ```
> node_modules/vite/
> ```
> 
> ![](chrome-extension://annlhfjgbkfmbbejkbdpgbmpbcjnehbb/images/saveicon.png) Save
> Note that `node_modules/vite/` is not a subdirectory of `node_modules/@types` nor `types`. TypeScript is behaving the way you told it to behave.
> 
> You need to add `node_modules` to your typeRoots:
> 
> ```
>     "typeRoots": ["./node_modules/@types/", "./types", "./node_modules"],
> ```
> 
> ![](chrome-extension://annlhfjgbkfmbbejkbdpgbmpbcjnehbb/images/saveicon.png) Save
> and you will see the expected behavior

It works, thank you.

**Comment by twentytwo777** [comment] 2023-08-14 19:13
> This is working as intended. Your tsconfig says
> 
> ```
> "typeRoots": ["./node_modules/@types/", "./types"],
> ```
> 
> The file you're expecting to find is in
> 
> ```
> node_modules/vite/
> ```
> 
> Note that `node_modules/vite/` is not a subdirectory of `node_modules/@types` nor `types`. TypeScript is behaving the way you told it to behave.
> 
> You need to add `node_modules` to your typeRoots:
> 
> ```
>     "typeRoots": ["./node_modules/@types/", "./types", "./node_modules"],
> ```
> 
> and you will see the expected behavior

best man

**Comment by gabrielbuii** [comment] 2023-09-05 13:52
@IanVS I am also curious, I would guess a slightly increased compilation time?

**Comment by IanVS** [comment] 2023-09-27 20:40
It sounds like there's probably not much of a performance issue: https://twitter.com/atcb/status/1707128537012981955.  It's just that in versions less than 5.1, there was no control over whether node_modules was included.

And here's a screenshot of my link above since I don't trust ~twitter~ x:
<img width="600" alt="image" src="https://github.com/microsoft/TypeScript/assets/4616705/99f97a27-a83c-41f0-8443-2310a88eae4d">

**Comment by RyanCavanaugh** [comment] 2023-10-06 23:17
The way to think about it is that we have a loop, psuedocode:
```ts
for each type in types {
  for each typeRoot in typeRoots {
    if (resolves(combine(typeRoot, type)) {
      addItToProgram()
      break
    }
  }
}
```
So adding another `typeRoot` has ~zero impact on perf when the list of `types` is manually-specified (i.e. is short)

**Comment by PieterjanDeClippel** [comment] 2024-07-31 13:20
Including the entire `node_modules` for type resolution? Sounds like a bad idea...
