### ISSUE TITLE
Parameters<T> can not get actual type on function overloads

### ISSUE THREAD

**Issue by zjtakato** [microsoft/TypeScript#56829] opened 2023-12-19 07:51 UTC
### 🔎 Search Terms

function overloads Parameters

### 🕗 Version & Regression Information

5.3.3

### 💻 Code
```typescript
class PDate {
  makeDate(timestamp: number);
  makeDate(m: number, d: number, y: number): Date;

  makeDate(mOrTimestamp: number, d?: number, y?: number): Date {
    if (d !== undefined && y !== undefined) {
      return new Date(y, mOrTimestamp, d);
    } else {
      return new Date(mOrTimestamp);
    }
  }
}
class CDate extends PDate {
  constructor() {
    super();
  }

  // Property 'makeDate' in type 'CDate' is not assignable to the same property in base type 'PDate'.
  // Type '(m: number, d: number, y: number) => Date' is not assignable to type '{ (timestamp: number): any; (m: number, d: number, y: number): Date; }'.ts(2416)
  override makeDate(...args: Parameters<PDate['makeDate']>) {
    return super.makeDate(...args);
  }
}
```

![image](https://github.com/microsoft/TypeScript/assets/124365086/3f30853a-94a3-41fe-9e59-185d7c05ac2c)

### 🙁 Actual behavior

When I want override parant class method, I need to get this method parameters type in child class, how can i get this method parameters type? 
I konw Parameters will be the parameters of the last signature, Can I get this type in another way?

### 🙂 Expected behavior

Parameters will be the parameters of actual function

**Comment by MartinJohns** [comment] 2023-12-19 07:54
This is a documented design limitation: https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types

And this is a duplicate of many.

**Comment by zjtakato** [comment] 2023-12-19 08:00
> design limitation

I konw this is a design limitation，can I get expected type in another way？

**Comment by craigphicks** [comment] 2023-12-19 16:42
@MartinJohns

To quote from [your reference](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types):

> When inferring from a type with multiple call signatures (such as the type of an overloaded function), inferences are made from the last signature (which, presumably, is the most permissive catch-all case). It is not possible to perform overload resolution based on a list of argument types.

There is some possible confusion in this description, as well as an often unmet presumption:

1. The description doesn't make clear whether *"the last signature"* is the *implementation signature* or the last *exposed signature* - if fact it means is the last *exposed* signature, which is logically what it must mean, because in a modules export file the *implementation signature* is not even included.
2. The often unmet presumption is that last *exposed signature* is *"the most permissive catch-all case"*.  It is not error for it not to be so, as can seen in this case.  So the user reading this presumption must be forgiven for thinking that the *implementation* signature is the *last signature* being described, because the *implementation signature* is actually required to be *"the most permissive catch-all case"*.

This same confusing and often unmet presumption appears verbatim in the [documentation for release 2.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#type-inference-in-conditional-types):

However, in this case  the error can be fixed by reversing the order of the signatures in `PDate`.
```
  makeDate(m: number, d: number, y: number): Date;
  makeDate(timestamp: number): Date; // why was the return type omitted? By default it is `any`.
```

**Comment by craigphicks** [comment] 2023-12-20 03:12
@RyanCavanaugh - Could you add the issue number(s) best matching?

**Comment by craigphicks** [comment] 2023-12-20 03:32
@RyanCavanaugh 

Could I bother you to be more specific?  Search through "function overloads" I could not find anything matching the OP's particular problem with getting the overloads union of signatures when the last one is not such a union.

**Comment by craigphicks** [comment] 2023-12-20 03:32
> And this is a duplicate of many.

Could I bother you to be more specific? Search through "function overloads" I could not find anything matching the OP's particular problem with getting the overloads union of signatures when the last one is not such a union.

**Closed** 2023-12-23 01:25 UTC
Labels: Duplicate

**Comment by craigphicks** [comment] 2024-01-14 02:13
@zjtakato

```
class PDate {
  makeDate(timestamp: number);
  makeDate(m: number, d: number, y: number): Date;
  makeDate(mOrTimestamp: number, d?: number, y?: number): Date;
  makeDate(mOrTimestamp: number, d?: number, y?: number): Date {
    if (d !== undefined && y !== undefined) {
      return new Date(y, mOrTimestamp, d);
    } else if (!d) {
      return new Date(mOrTimestamp);
    }
    throw "rangeError";
  }
}
class CDate extends PDate {
  constructor() {
    super();
  }
  override makeDate(...args: Parameters<PDate['makeDate']>) {
    return super.makeDate(...args);
  }
}

```
