### ISSUE TITLE
Add ES6 \u{...} support for identifiers

### ISSUE THREAD

**Issue by hydroper** [Microsoft/TypeScript#13144] opened 2016-12-23 10:26 UTC
**TypeScript Version:**  2.2.0

**Code**
```ts
\u{41}
```

**Expected behavior:**
`Cannot find name '\u0041'.`

**Actual behavior:**
Syntax warnings are shown.

**Advice**
It works in string literals, though. This input example is valid in ES6+, and works properly on browser (run in the browser console).

```ts
`\u{41}`
```

For know, only the basic *`UnicodeEscapeSequence`* with zeroes is supported.

```ts
\u0041
```

**Comment by DanielRosenwasser** [comment] 2016-12-24 08:22
Looks like a duplicate of #5291. We're accepting PRs.

**Closed** 2016-12-24 08:23 UTC
Labels: Duplicate
