### ISSUE TITLE
Partial<any> should be treated as any

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#20247] opened 2017-11-24 04:21 UTC
tsc@2.6.1

```ts
let x: Partial<any>
let y: number = x // Type 'Partial<any>' is not assignable to type 'number'.
let z: string = x // Type 'Partial<any>' is not assignable to type 'string'.
```

`Partial<any>` should be considered as `any` and can be assigned to other types.

[Playground](http://www.typescriptlang.org/play/index.html#src=let%20x%3A%20Partial%3Cany%3E%0D%0Alet%20y%3A%20number%20%3D%20x%0D%0Alet%20z%3A%20string%20%3D%20x)

**Comment by kitsonk** [comment] 2017-11-24 09:34
Do you have a real world use case for this?

It appears to be intentional because `Partial<any>` is the only one that actually generates a [general indexer](https://www.typescriptlang.org/play/#src=type%20PartialString%20%3D%20Partial%3Cstring%3E%3B%20%2F%2F%20string%0Atype%20PartialNumber%20%3D%20Partial%3Cnumber%3E%3B%20%2F%2F%20number%0Atype%20PartialObject%20%3D%20Partial%3Cobject%3E%3B%20%2F%2F%20object%0Atype%20PartialWeakObject%20%3D%20Partial%3C%7B%7D%3E%3B%20%2F%2F%20%7B%7D%0Atype%20PartialAny%20%3D%20Partial%3Cany%3E%3B%20%2F%2F%20%7B%20%5Bx%3A%20string%5D%3A%20any%3B%20%7D%0A):

```ts
type PartialString = Partial<string>; // string
type PartialNumber = Partial<number>; // number
type PartialObject = Partial<object>; // object
type PartialWeakObject = Partial<{}>; // {}
type PartialAny = Partial<any>; // { [x: string]: any; }
```

**Comment by unional** [comment] 2017-11-24 09:46
Yes I do, as in the linked PR:
https://github.com/unional/assertron/blob/master/src/satisfy.ts#L13

This issue is breaking this case:
https://github.com/unional/assertron/blob/master/src/satisfy.spec.ts#L118

**Comment by Jack-Works** [comment] 2017-11-24 14:07
By the way, type `number & 123` should be treated as `123`, `string & 'abc'` should be `'abc'`

**Comment by mhegazy** [comment] 2017-11-27 19:39
`Partial` and `Record` are mapped types, and these assume a transformation on the members of an object type.. there is a special treatment for primitives as noted by @kitsonk , since mapping primitive properties is rather meaningless.

Now, `any` can be thought of as an infinite union of all possible types, that include both primitive and object types.. a mapping operation on that infinite union would ignore primitives (`number`, `string`, etc..) and would only operate on the object types. the result of that transformation is guaranteed to always be an object type; the names of the properties is the infinite set of all possible property names (`string`) and their types are all possible types (`any`) hence the result is `{ [x: string]: any }.

I think there is something to be said on the use of `any`as an argument to `Partial`.. either you need a generic type parameter threaded through to be able to do the transformation correctly, or it should be explicitly specified as `any` and avoid the confusion.

Please see https://github.com/Microsoft/TypeScript/pull/19185 for more details about the change.

Duplicate of https://github.com/Microsoft/TypeScript/issues/19624

**Comment by unional** [comment] 2017-11-27 21:39
I think #19185 may be over solving the issue in #19152. 

I can understand that `{ [P in any]: T }` and `{ [P in keyof any]: T }` should yield `{ [x: string]: T}`

But that doesn't mean `Partial<any>` or `ReadOnly<any>` should resolve to `{ [x: string]: any }` and `{ readonly [x: string]: any }`

In #19152, the problem is the indexer, not the property type, that have the problem.

Also, `Partial<any>` and `ReadyOnly<any>` has a semantic meaning. In these circumstances, I think your statement "`any` can be thought of as an infinite union of all possible types, that include both primitive and object types" would be a more perceivable take.

I understand that `Partial` and `Record`are mapped types, but as they need special treatment for primitives, I think they also need special treatment for `any`. 🌷

**Comment by amir-arad** [comment] 2017-11-28 12:41
currently blocks wix/wix-react-tools#188

**Comment by kitsonk** [comment] 2017-11-28 14:53
@amir-arad any change here wouldn't solve the issue with your code.  It is unrelated.  For [example](https://www.typescriptlang.org/play/#src=function%20consumer(p%3A%7Bfoo%3Astring%7D)%7B%7D%0Aconst%20obj%3A%20Partial%3C%7B%20foo%3A%20string%20%7D%3E%20%3D%20%7Bfoo%3A'bar'%7D%3B%0Aconsumer(obj)%3B%0A) the following is an error:

```ts
function consumer(p:{foo:string}){}
const obj: Partial<{ foo: string }> = {foo:'bar'};
consumer(obj);
```

You have a situation where the key you require is optional on the source type.  That won't ever work.

**Comment by amir-arad** [comment] 2017-11-28 17:23
from the [Documentation site](https://www.typescriptlang.org/docs/handbook/basic-types.html#any) : 

> The any type is a powerful way to work with existing JavaScript, allowing you to gradually opt-in and opt-out of type-checking during compilation. 

I expect `Partial` to be consistent in that matter with other type expressions, such as unions and intersections, where `any` plays a special role:

```ts
function consumer(p:{foo:string}){}
const obj: (any & {foo:null}) | {foo:number} = {foo:'bar'};
consumer(obj); // this works fine
```

**Comment by unional** [comment] 2017-11-28 19:46
> I can understand that { [P in any]: T } and { [P in keyof any]: T } should yield { [x: string]: T}

To nail this a bit more, I can see the rational for #19185

```ts
interface X<T, R> {
  [P in keyof T]: R
}

let x: X<{ a: number, b: string }, { foo: number }> = { a: { foo: 1 }, b: { foo: 2 } }

// y: { [P: string]: { foo: number } }
let y: X<any, { foo: number }> = { c: { foo: number } }

// z: { a: any, b: any }
let z: X<{ a: number, b: string }, any> = { a: 'a', b: 1 }
```

But `Partial<T>`, `ReadOnly<T>`, or some others should behave more than mapped type, as they have special cases for primitives.

**Comment by mhegazy** [comment] 2017-11-28 20:36
> But Partial<T>, ReadOnly<T>, or some others should behave more than mapped type, as they have special cases for primitives.

all mapped types have the same behavior for primitives..

**Comment by kitsonk** [comment] 2017-11-28 20:43
> I expect `Partial` to be consistent in that matter with other type expressions, such as unions and intersections, where `any` plays that special role

Then why not use `any` instead of `Partial<any>`?

**Comment by unional** [comment] 2017-11-28 22:05
> all mapped types have the same behavior for primitives..

fair enough. As I said, I agree that the current behavior for mapped type is "likely" to be fine.
```ts
type X<T> = {
  [P in keyof T]: T[P]
}

X<any> => { [P in keyof any]: any[P] } => { [P: string]: any }
```

My question is: should `Partial` and `Readonly` be just mapped type? Or should they be something more than a mapped type?

"a partial set of an infinite set is an infinite set"
"ready only of an infinite set is read only of an infinite set"

**Comment by mhegazy** [comment] 2017-11-28 23:16
Mapped types in general are defined in terms of object types. in that context `Readonly` is an approximation of what a Readonly type operator would ideally mean. for instance `Readonly<Array<T>> !== ReadonlyArray<T>`, and so is `Map` and `Set`. so in that sense, i think `Readonly<any>` behaving as `any` in TS 2.5 was a bug, an unintentional behavior.

**Comment by unional** [comment] 2017-11-29 00:15
Yes, on that argument it does make sense for going against `Readonly<any> => any`

I'm almost convinced to drop `Readonly<>` from this discussion.

But on the other hand 😛 :

```ts
const x: Readonly<number> = 1
const y: Readonly<number & any> = 1 // error
```
`any` should be an inclusive of all types.

Maybe the special treatment needed for primitives is the root cause of this confusing behavior.

Maybe `type Readonly<T extends object> = { ... }` would avoid this problem altogether.

Need more time to think about `Partial<any>`

**Comment by mhegazy** [comment] 2017-11-29 00:23
> Maybe `type Readonly<T extends object> = { ... }` would avoid this problem altogether.

we wanted to do that originally. but then 1. `object` was not in back then, and 2. felt annoying that every time you would write `Partial<T>` you have to make sure `T extends object`. So instead we have added the special handling of primitives. back then we did not really think of `any` deeply, and the behavior was rather unspecified. last release we fixed that, but really it should have been like so all along.

**Comment by amir-arad** [comment] 2017-11-29 19:14
@kitsonk It's not always possible or convenient to define the type directly. sometimes you need to work with a third party tool, that returns `Partial<T>`. using `any` as the value of `<T>` should opt-out of type-checking during compilation.

**Comment by kitsonk** [comment] 2017-11-29 19:53
@amir-arad 

```ts
declare function foo<T>(bar: T): Partial<T>;
const baz: any = { qat: 1 };
const qat = foo(baz) as any;
// or
const qux: any = foo(baz);
```

It just requires you to be explicit about your `any` usage, which you should anyways.

**Comment by amir-arad** [comment] 2017-11-30 16:56
@kitsonk `as any` has a tendency to stick around long after it's usefulness. 
I don't think It's a good solution, to be explicit about a piece of data being of the `any` type again and again.

**Closed** 2018-01-02 18:42 UTC
Labels: Duplicate

**Comment by unional** [comment] 2018-01-02 19:15
`anti-bot`: this should be re-open for evaluation. 😛 
It would be a breaking change but may worth the cost.

**Comment by tycho01** [comment] 2018-02-22 19:33
https://github.com/gcanti/typelevel-ts/issues/19 suggested using conditional types to accomplish the desired behavior.
