### ISSUE TITLE
TypeScript build fails (tsc build of this project itself)

### ISSUE THREAD

**Issue by Bnaya** [Microsoft/TypeScript#14555] opened 2017-03-09 09:55 UTC
This a build of a plain fork on the same commit as this repo
https://travis-ci.org/brandtotal/TypeScript/jobs/209286829

The build fails on:
```
node built/local/tsc.js --noImplicitAny --noImplicitThis --noEmitOnError --types  --pretty --preserveConstEnums --outDir built/local/ --module commonjs -sourcemap -mapRoot file:////home/travis/build/brandtotal/TypeScript/built/local --target es5 --lib es5,scripthost --noUnusedLocals --noUnusedParameters src/server/cancellationToken/cancellationToken.ts
1841     export class URLSearchParams implements Iterable<string[]> {
                                                 ~~~~~~~~
node_modules/@types/node/index.d.ts(1841,45): error TS2304: Cannot find name 'Iterable'.
```

The `--lib es5,scripthost` is missing `es6` to have the iterator interface.

I don't know how your travis build is passing, i would assume its something on the cached dependencies.
try to clear your cache and run the build again

**Comment by sslgeorge** [comment] 2017-03-09 13:16
I am having the same exact issue now

**Comment by kitsonk** [comment] 2017-03-09 14:34
I have run into something similar.  It appears that @types/node of the 7.0.X versions assumes an ES6 environment.  I have noticed that if your force a `@types/node@^6.0.0` in a `package.json` you can eliminate the dependency on the build in ES6 features that are part of the 7.0.X release.

I assume recently the 7.0.X versions became the default, which means if there is a cache with an older version of `@types/node` it using the non ES6 specific typings and therefore builds continue to succeed without the `--lib es6` instead of `--lib es5`.

**Comment by mhegazy** [comment] 2017-03-09 17:48
As @kitsonk noted, this is caused by recent change to `@types/node`. Should be fixed by https://github.com/Microsoft/TypeScript/pull/14553

**Closed** 2017-03-09 17:48 UTC
Labels: Fixed, Infrastructure
