### ISSUE TITLE
Conditional types - Extract works incorrect 

### ISSUE THREAD

**Issue by sirian** [Microsoft/TypeScript#22899] opened 2018-03-27 10:29 UTC
**TypeScript Version:**  2.8.0-rc, 2.9.0-dev.20180327

```ts
declare function isFunction<T>(value: T): value is Extract<T, Function>;

declare function toString1(value: object | Function): string ;
declare function toString2(value: Function): string ;

function foo<T>(value: T) {
    if (isFunction(value)) {
        toString1(value); // ok

        toString2(value); // error TS2345: Argument of type 'Extract<T, Function>' is not assignable to parameter of type 'Function'.
                          // Type 'T' is not assignable to type 'Function'.
    }
}
```

**Comment by jcalz** [comment] 2018-03-27 18:18
Is this not a duplicate of #22347?

**Comment by ahejlsberg** [comment] 2018-03-27 19:32
Yes, it is pretty much a duplicate. And a workaround similar to the one mentioned in https://github.com/Microsoft/TypeScript/issues/22347#issuecomment-370905021 can be used:

```ts
declare function isFunction<T>(value: T): value is (Extract<T, Function> & Function);
```

That said, it would be nice if it actually worked, so I'm going to keep this one open as a bug.

**Comment by sirian** [comment] 2018-03-27 20:20
It's wrong

```
declare function isObject<T>(value: T): value is (Extract<T, object> & object);

declare const foo: {key: any} | Record<string, any>;

if (isObject(foo)) {
    console.log(foo.key);
}
```

```
error TS2339: Property 'key' does not exist on type '{ key: any; } | Record<string, any>'.
```

**Comment by sirian** [comment] 2018-03-27 20:21
moreover: 

![image](https://user-images.githubusercontent.com/897643/37992875-97994c10-3215-11e8-95c9-d4cfab5771c0.png)

**Comment by ahejlsberg** [comment] 2018-03-27 20:28
@sirian That's an unrelated issue. See #21141. In your example the `isObject` type guard doesn't actually do anything because both sides of the union are of type `object`.

**Comment by ahejlsberg** [comment] 2018-03-27 20:38
See #21732 regarding the example involving the `in` operator.

**Comment by sirian** [comment] 2018-03-28 06:36
@ahejlsberg `isObject` at https://github.com/Microsoft/TypeScript/issues/22899#issuecomment-376661428 is an example that your workaround is wrong at https://github.com/Microsoft/TypeScript/issues/22899#issuecomment-376647058

**Comment by sirian** [comment] 2018-03-28 07:15
@ahejlsberg 

```
declare function isString<T>(value: T): value is Extract<T, string> & string;

declare function foo(value: number): string ;

function test1<T>(value: T) {
    if (isString(value)) {
        foo(value);
    }
}

function test2<T extends number>(value: T) {
    if (isString(value)) {
        foo(value);
    }
}

function test3<T extends number | string>(value: T) {
    if (isString(value)) {
        foo(value);
    }
}

```

![image](https://user-images.githubusercontent.com/897643/38014305-ebbe6a86-3270-11e8-9933-a61d3089f56e.png)

**Comment by sirian** [comment] 2018-03-28 11:44
@ahejlsberg maybe it should be `Extract<T & Bit, Bit>`?

**Closed** 2018-03-31 18:56 UTC
Labels: Bug, Fixed
