### ISSUE TITLE
Shared external module causes compiler to lockup

### ISSUE THREAD

**Issue by david-driscoll** [Microsoft/TypeScript#5695] opened 2015-11-16 20:42 UTC
I have a very strange issue that I've finally figured out the cause of, as it's really very strange.

It appears that if there is a dependency, that exists in two locations, and it defines typings as `external`, then `tsc` gets confused and cannot reason about them both.

### Setup
* Using atom-typescript as my editor, though the issue shows up when trying to compile with `tsc` as well.
* I'm on a windows machine.

My folder structure looks like:
- `c:\Dev\Omnisharp\omnisharp-atom`
  - `\node_modules\omnisharp-client` symlink to `c:\Dev\Omnisharp\omnisharp-node-client`
  - `\node_modules\@reactive\rxjs` symlink to `c:\Dev\reactivex\RxJS`
- `c:\Dev\Omnisharp\omnisharp-node-client`
  - `\node_modules\@reactive\rxjs` symlink to `c:\Dev\reactivex\RxJS`
- `c:\Dev\reactivex\RxJS`

Everything is typically working great, I'm working on typings for RxJS 5.0, and updating `omnisharp-client` without issue.

When I got to `omnisharp-atom` an issue revealed itself, if I define `Observable<T>` as a return type  for a method, with the above setup, then `tsc` get's confused and fails to compile.  It gets into some sort of infinite loop.

### Working
If I update things so that they look like:
- `c:\Dev\Omnisharp\omnisharp-atom`
  - `\node_modules\omnisharp-client` (no symlink)
    - ~~`\node_modules\@reactive\rxjs`~~ (removed)
  - `\node_modules\@reactive\rxjs` symlink to `c:\Dev\reactivex\RxJS`

Then everything is happy and works as expected.

### Without symlinks
If I update things so that they look like:
- `c:\Dev\Omnisharp\omnisharp-atom`
  - `\node_modules\omnisharp-client` (no symlink)
    - `\node_modules\@reactive\rxjs` (symlink or non-symlink)
  - `\node_modules\@reactive\rxjs` symlink to `c:\Dev\reactivex\RxJS`

Then `tsc` fails to operate and will sit and consume CPU forever until it is killed.

**Comment by mhegazy** [comment] 2015-11-16 22:48
@vladima can you take a look

**Comment by vladima** [comment] 2015-11-17 00:02
@david-driscoll I've tried to repro it but with no luck however this sounds like a serious issue. Can you please share a self contained repro so we can address it properly?

**Comment by david-driscoll** [comment] 2015-11-17 00:28
Sure, I can recreate it on demand with my current solution, so I'll try zipping it up and double checking it still fails, then post a link.

**Comment by vladima** [comment] 2015-11-17 00:29
thanks!

**Comment by david-driscoll** [comment] 2015-11-17 01:43
So creating a zip failed to extract if you're on windows (like myself) because of long paths.

I've created a batch file that will setup the scenario, of course feel free to review it for an malicious code.  It's just pulling down a few git repos, running npm install for those repos and setting up the same symlinks.

https://onedrive.live.com/redir?resid=B65E6B05AE4EE402!237452&authkey=!AG6bNj8i96iBJJQ&ithint=file%2czip

**Comment by vladima** [comment] 2015-11-17 22:24
I can see what is going on. Good news is that is not not related to module resolution - all files are resolved without any issues. The issue is that from compiler perspective it sees two different set of typings for RxJS: one in `omnisharp-atom` folder and another in `omnisharp-node-client` and all the time pretty much spent trying to relate types from these typing sets

**Comment by david-driscoll** [comment] 2016-02-14 23:53
@vladima any traction on this issue, still seems to be a problem.  Any proposed work arounds perhaps?

**Comment by vladima** [comment] 2016-02-16 18:26
@david-driscoll TypeScript compiler currently does not follow symlinks so in your scenario it views RxJS in `omnisharp-node-client\node_modules` and `omnisharp-atom\node_modules` as different set of files and this leads to the worst possible option during type relationship check - comparing two identical structures. We have an issue to handle symlinks properly (#6365), once it is done - thinks should look better. As a workaround in your case can you push `RxJS` dependency higher in the directory hierarchy so compiler will use the same package for both `omnisharp-node-client` and `omnisharp-atom`?
```
├───node_modules
│   └───rx (symlink from rx-js)
├───omnisharp-atom
├───omnisharp-node-client
└───rx-js
```

**Comment by kruncher** [comment] 2016-03-08 21:30
I am having the exact same issue with `rxjs` and use of symlinks.

It doesn't like it when I symlink the core package into my plugin package because rxjs occurs in both paths standard-generator/node_modules/core-package/node_modules/rxjs and standard-generator/node_modules/rxjs.

To me it seems that TypeScript could just look in standard-generator/node_modules for rxjs first, before attempting to look inside the deeper node_modules folders.

**Comment by vladima** [comment] 2016-05-06 23:51
#8486 have added ability to follow symlinks during module resolution . Script this change should already be available in nightly builds, managed part and version of `tsc.exe` that support symlinks will be included in the next release

**Closed by vladima** 2016-05-06 23:51 UTC
Labels: Bug

**Comment by kruncher** [comment] 2016-05-23 12:00
I still seem to be experiencing issues when using symlinks via `npm link`.

For instance the following error occurs when my core package is symlinked into the `node_modules` directory of my plugin package. `MyInterface` is an interface that lives inside my core package; `MyInterfaceImplementation` is a class that lives inside my plugin package:
```
error TS2420: Class 'MyInterfaceImplementation' incorrectly implements interface 'MyInterface'.
```

However this issue does not occur when the core package is installed into the plugin package's `node_modules` directory:
```
my-plugin-package/node_modules/my-core-package
```

I setup the symlink using the following:
```
λ cd my-core-package
λ npm link
λ cd ../my-plugin-package
λ npm link my-core-package
λ npm run build-typescript
```

I think I am running the latest development build:
```
λ tsc --version
Version 1.9.0-dev.20160523-1.0
```
