### ISSUE TITLE
Type checking preservation at runtime

### ISSUE THREAD

**Issue by projektorius96** [microsoft/TypeScript#47380] opened 2022-01-11 09:16 UTC
Currently I don't use TypeScript (hereinafter – TS) , but I see it as a tooling in my future list if it could preserve things within boundaries of JavaScript specification at runtime . Let me show you simple example what do I mean .

Consider the following .ts code:
```javascript
function f(id: string) {
    return id;
}
```

Above would be transpiled to the following .js code:
```javascript
"use strict";
function f(id) {
    return id; // where the heck typecheking gone ? Oh I see it's only at "virtualized" compile stage 
}
```

Rather than someone's expected of so called "idiomatical **emmet**ization":
```javascript
"use strict";
function f(id) {
    return typeof id === 'string' ? id : false ; // preserve that is comprehended by specification, syntax
}
```

We can write boilerplaty type checking within JavaScript (_more precisely ECMAScript_) specification preserving it for runtime

**Cornerstone question**: why couldn't we suggest this as a future , at least optionally **.ts** source code be preserved for typechecking in final **.js** file rather than pretending be a (trans)compiler only at compiling , not runtime stage . Thank you .

**Comment by MartinJohns** [comment] 2022-01-11 09:20
- Duplicate of #1573.
- You forgot to fill out the issue template. It links to the language design goals, where this feature is explicitly excluded.

**Comment by projektorius96** [comment] 2022-01-11 11:21
Sorry for duplication & thanks for answering . Good luck !

**Closed** 2022-01-11 16:06 UTC
Labels: Duplicate
