### ISSUE TITLE
Access access should infer type union with undefined

### ISSUE THREAD

**Issue by stevenhankin** [microsoft/TypeScript#41229] opened 2020-10-25 09:34 UTC
**TypeScript Version:**  Up to and including 4.0.2

**Search Terms:** 
Array, accessor

**Code**
```ts
// Let's assume pets can be cats or dogs
type Pet = { name: string; species: "cat" | "dog" }
const pets: Pet[] = [{ name: "Muffin", species: "dog" }, { name: "Fidgit", species: "cat" }]

// Accessing it by index can return undefined if the array is empty or out of bounds
const maybePet = pets[100]

// Typescript infers maybePet as "Pet" (hover your cursor over maybePet), BUT should infer "Pet | undefined"
```

**Expected behavior:**
Typescript should infer maybePet as type `Pet | undefined`

**Actual behavior:**
Typescript infers maybePet as type `Pet`
This causes runtime bugs for out-of-bounds situations

**Playground Link:** [Pet Example](https://www.typescriptlang.org/play?ts=4.0.2#code/PTAEBkFMBcHIGdQEN7wK4FtKgA40QMZIB2oARtkdIgPYBOoAJjQObwBQ0AnnqAAoxQAXlABvUMSRYAXKHjQ6AS2IsA3HLwFFkeLIBEVPaAA+oPcxZGAvuwI1i83PlkDoAbQC6w0G-GSZZgCyaABmIcp6ADQakFo6+hbW0X5SkPoAYoqMLIrQUTFxumaGoFYe7OwgoACCBAQ68MosoLnkXC3EjJAAHqBEpHQwaHSkaJ2Q4cSQjC0hoNAAFthIdHRI7YqIkBg43KD0+2jQ+3NkNGOMHHYOxxjrFK7eeNRuAIwADO-llWAAKjw6AhKXYdEKQOiIO5cB6CFBmVxGAAUCxoADdwaAuOcGARhvADmiMVCYdAAJTRABCAFVfnIUWgADYzZRghh6R6mC4TZTTPTsIA)

**Related Issues:** Haven't found any

**Comment by MartinJohns** [comment] 2020-10-25 11:44
Duplicate of #13778. TypeScript 4.1 will provide a `noUncheckedIndexedAccess` flag for this purpose.

**Closed** 2020-10-25 11:53 UTC
