### ISSUE TITLE
Hovering `as const` returns `any`

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#43515] opened 2021-04-03 11:28 UTC
TS stable and nightly
[playground](https://www.typescriptlang.org/play?#code/ETAEEMGdQYwewHaQC5A)
```ts
"" as const
```
<img width="91" alt="chrome_2021-04-03_13-27-01" src="https://user-images.githubusercontent.com/30108880/113477157-505e1580-9480-11eb-977d-20950d9bc020.png">

**Comment by orta** [comment] 2021-04-03 12:23
Heh, yep

```ts repro
"" as const
//     ^?
```

**Comment by andrewbranch** [comment] 2021-04-05 17:17
I think it would be nice to display the type of the const assertion here (as opposed to displaying nothing, which would also be acceptable)

**Comment by andrewbranch** [comment] 2021-04-05 17:17
(This is probably just a `getTypeAtLocation` missing case.)

**Comment by davidli98** [comment] 2021-04-06 02:53
I would like to take a shot at this. However, I'm not familiar with how to debug changes to the services.

**Comment by SachiniAbeygunawardhana** [comment] 2021-04-06 06:44
Hi, If this is not assigned to anyone yet, I'm willing to work on this.

**Comment by andrewbranch** [comment] 2021-04-06 17:09
Have a look at

- https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#instructions-for-contributing-code
- https://blog.andrewbran.ch/debugging-the-type-script-codebase/
- https://github.com/orta/typescript-notes/tree/master/intro

We don’t actually assign community members, so if the issue still says “help wanted,” feel free to work on it. But be aware that someone else might work on it too. Once you’ve actively started and feel like you have a good chance of opening a PR, comment here so that others know not to start on it if they want a high chance of their code getting merged.

**Comment by z0gSh1u** [comment] 2021-04-07 13:12
![snapshot](https://user-images.githubusercontent.com/30524126/113871377-6b64b880-97e5-11eb-972e-08045d6235e8.png)

This looks like a bug with Scanner or Parser. Compiler reduces `const` into an `Identifier` instead of `ConstKeyword`.

**Comment by andrewbranch** [comment] 2021-04-07 16:59
That’s not a bug. A TypeReference needs an entity name (i.e., an identifier or dotted name). There’s nothing that says we can’t use an identifier node to store `const` in a type position, so const assertions were written that way to avoid changing the API for AsExpressions.

**Closed** 2021-04-12 10:43 UTC
Labels: Bug, Domain: Completion Lists, good first issue, help wanted
