### ISSUE TITLE
Export default abstract class not allowed in class declaration

### ISSUE THREAD

**Issue by xLama** [Microsoft/TypeScript#7375] opened 2016-03-03 19:50 UTC
**TypeScript Version:** 

1.8.2

**Code**

```ts

export default abstract class A  {} // Error
```

```ts

// Ok
abstract class A  {}
export default A;
````

I have not red anything about this in docs.

Thanks.

**Comment by mhegazy** [comment] 2016-03-03 19:56
duplicate of https://github.com/Microsoft/TypeScript/issues/3792

**Comment by RyanCavanaugh** [comment] 2016-03-03 19:57
Please search before logging new issues :cry:

![image](https://cloud.githubusercontent.com/assets/6685088/13507347/0ed6a6f6-e137-11e5-9601-6c56931dcf1e.png)

**Closed by mhegazy** 2016-03-03 19:56 UTC
