### ISSUE TITLE
Sudden lib.es6.d.ts errors in a solution that doesn't use TypeScript

### ISSUE THREAD

**Issue by stijnherreman** [Microsoft/TypeScript#14873] opened 2017-03-27 14:50 UTC
**TypeScript Version:** 2.1.5.0 (as reported by VS 2017 for the *TypeScript for Microsoft Visual Studio* extension)

**Code**
None whatsoever. The project does not use TypeScript.

**Expected behavior:**
No TypeScript errors listed in Visual Studio.

**Actual behavior:**
The following errors are listed in Visual Studio, since today. I've been using VS 2017 since its official release and haven't seen this problem before.

```
Error	TS2451	Cannot redeclare block-scoped variable 'JSON'.	Web	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TypeScript\lib.es6.d.ts	991	Active
Error	TS2451	Cannot redeclare block-scoped variable 'JSON'.	Web	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TypeScript\lib.es6.d.ts	1018	Active
Error	TS2451	Cannot redeclare block-scoped variable 'JSON'.	Web	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TypeScript\lib.es6.d.ts	5714	Active
```

**Comment by mhegazy** [comment] 2017-03-27 16:50
Seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/14565. Should be fixed in the next update of VS 2017.

**Closed** 2017-04-21 16:55 UTC
Labels: Duplicate
