### ISSUE TITLE
unknown: optional chaining support

### ISSUE THREAD

**Issue by mfulton26** [microsoft/TypeScript#46785] opened 2021-11-11 20:09 UTC
# Suggestion

## 🔍 Search Terms

chaining optional unknown

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Especially when catching an exception in try…catch but also in other places where the exact type may not matter it would be nice to be able to use some functions for a variable of type `unknown` with [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).

## 📃 Motivating Example

```ts
try {
  // some code here that may throw an exception
} catch (exception) { // could be anything so it is unknown
   // we might decide we don't care what type exception is only if it can be
  // transformed to a string and if the string includes some text
  if (exception?.toString().includes("HTTP 404")) {
    console.log("uh oh");
  }
}
```

instead of

```ts
try {
  // some code here that may throw an exception
} catch (exception) { // could be anything so it is unknown
  if (exception && typeof exception === "object" && exception.toString().includes("HTTP 404")) {
    console.log("uh oh");
  }
}
```

## 💻 Use Cases

I want to avoid writing extra type guards when not really needed so that I'm writing the same amount of code in TypeScript as I would if I were writing it directly in JavaScript.

**Comment by andrewbranch** [comment] 2021-11-11 20:17
Duplicate of #37700

**Comment by mfulton26** [comment] 2021-11-11 20:18
I forgot to search among closed issues; my apologies and thank you

**Closed** 2021-11-14 18:00 UTC
Labels: Duplicate
