### ISSUE TITLE
Wrong type narrowing to 'never' after 'in'

### ISSUE THREAD

**Issue by JanKoehnlein** [Microsoft/TypeScript#21714] opened 2018-02-07 09:07 UTC
**Search Terms:** 
Type narrowing, 'in' 

**Code**
```ts
interface Foo { 
    foo: boolean
}

interface Bar {
    bar: boolean
}

function isFooAndHasBar(foo: Foo): foo is Foo & Bar {
    return 'bar' in foo && foo.foo; 
}
```

**Expected behavior:**
No type error. Just because there is an additional property in a `Foo`, it should still have all props of `Foo`.

**Actual behavior:**
Error: Property 'foo' does not exist on type 'never'

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=interface%20Foo%20%7B%20%0D%0A%20%20%20%20foo%3A%20boolean%0D%0A%7D%0D%0A%0D%0Ainterface%20Bar%20%7B%0D%0A%20%20%20%20bar%3A%20boolean%0D%0A%7D%0D%0A%0D%0Afunction%20isFooAndHasBar(foo%3A%20Foo)%3A%20foo%20is%20Foo%20%26%20Bar%20%7B%0D%0A%20%20%20%20return%20'bar'%20in%20foo%20%26%26%20foo.foo%3B%0D%0A%7D

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/20583
Note that this is about the `true` branch (`&&`), and that `foo` itself is narrowed down to `never` (not `foo.foo`).
Current workaround: Switch operands. Had to do this in quite a few places in my codebase.

**Comment by niieani** [comment] 2018-02-07 10:12
You are expecting `foo` of type `Foo` as the parameter. You need to use a generic:

```ts
function isFooAndHasBar<T extends Foo>(foo: T): foo is Foo & Bar {
    return 'bar' in foo && foo.foo;
}
```

[Playground](https://www.typescriptlang.org/play/index.html#src=interface%20Foo%20%7B%20%0D%0A%20%20%20%20foo%3A%20boolean%0D%0A%7D%0D%0A%0D%0Ainterface%20Bar%20%7B%0D%0A%20%20%20%20bar%3A%20boolean%0D%0A%7D%0D%0A%0D%0Afunction%20isFooAndHasBar%3CT%20extends%20Foo%3E(foo%3A%20T)%3A%20foo%20is%20Foo%20%26%20Bar%20%7B%0D%0A%20%20%20%20return%20'bar'%20in%20foo%20%26%26%20foo.foo%3B%0D%0A%7D)

**Comment by mhegazy** [comment] 2018-02-07 17:25
duplicate of https://github.com/Microsoft/TypeScript/issues/21517.

**Closed** 2018-02-22 20:41 UTC
Labels: Duplicate
