### ISSUE TITLE
A way to define the opposite of Partial<T> type

### ISSUE THREAD

**Issue by Deilan** [Microsoft/TypeScript#18647] opened 2017-09-21 12:11 UTC
We already have `Partial<T>` and `Readonly<T>`, which are defined in the following way:
```ts
type Partial<T> = {
    [P in keyof T]?: T[P];
};

type Readonly<T> = {
    readonly [P in keyof T]: T[P];
};
```

It would be great to have a way to define the opposite of `Partial<T>`, let's say `Mandatory<T>` or `Strict<T>`, etc.:
```ts
type Mandatory<T> = {
    [P in keyof T]: T[P]!;
    //                  ^
    // note an exclamation mark, which is already used for
    // asserting a var is not undefined nor null
};
```

Example. Let's say we have `IPerson`:
```ts
interface IPerson {
    name: string;
    age?: number;
}
```
`Partial<IPerson>` would look like that:
```ts
interface Partial<IPerson> {
    name?: string;
    age?: number;
}
```
And the `Mandatory<IPerson>`:
```ts
interface Mandatory<IPerson> {
    name: string;
    age: number;
}
```

**Comment by goodmind** [comment] 2017-09-21 16:36
Looks like duplicate of https://github.com/Microsoft/TypeScript/issues/12936

**Comment by mhegazy** [comment] 2017-09-21 16:51
This is actually a duplicate of https://github.com/Microsoft/TypeScript/issues/15012

**Comment by mhegazy** [comment] 2017-10-05 18:18
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-05 18:18 UTC
Labels: Duplicate
