### ISSUE TITLE
Union with constrained type variable doesn't narrow in negative branch of type predicate

### ISSUE THREAD

**Issue by saschaB91** [microsoft/TypeScript#44814] opened 2021-06-29 19:23 UTC
### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/LAKAxgNghgzjAEAVApjALgYWnAPIgfPAN6jxnxoCeADsgOYCuUATgCYAUAblBAFzwMAdgGtBAewDuggJT9uEeAEsEiYqXIbmyNA2aCKzBsgDc6sgF8z8AGZd+ghgFsARsmaz4nMYtbFLIDQALOyQPLx8-K2shMC4eflUAH3gHFzcw718SAI1yRWt4djRA5QA6KlpGFg55aWk1HNzc4rLg2tNGpvItHT0Orvh-AZaYUtt2q39-UEhYFVRMbBgAJjx4ZAAPNGRBVgQAEShtwmyNCvomNji+ARFxKTCeJRUGgZ7dfTRDE0mokNTXO45JlIp02gkMhEiENyNFBLF5Al4MkAelgVCrBp8oURuUaBdqtc6q8BuRcW0eNJ+qSyO8+pjyDCmrjxpTqRZQOYgA

Issue Type: <b>Bug</b>

This error is only shown when using the TypeScript-Server not when compiling code.
When using an generic class with a method as type guard, it will only be validated correctly if you do not extend the generic type.
The first class is ok but the second shows an error on "this.f(val)" even though nothing changed

```
class TestClass<T> {
    typeguard(val: unknown): val is T {
        return true;
    }
    f(v: number): void {}
    h(v: T): void {}
    func(val: T | number): void {
        if (this.typeguard(val)) {
            this.h(val);
            return;
        }
        this.f(val);
    }
}
```

```
class TestClass2<T extends Date> {
    typeguard(val: unknown): val is T {
        return true;
    }
    f(v: number): void {}
    h(v: T): void {}
    func(val: T | number): void {
        if (this.typeguard(val)) {
            this.h(val);
            return;
        }
        this.f(val);
    }
}
```

**Comment by MartinJohns** [comment] 2021-06-29 20:12
> This error is only shown when using the TypeScript-Server not when compiling code.

This is not true. The error is shown when compiling just fine.

![image](https://user-images.githubusercontent.com/5269069/123860696-86e3e900-d926-11eb-8b88-e8c4ac9d58d2.png)

This is possibly a duplicate of #42185.

**Comment by andrewbranch** [comment] 2021-06-30 14:50
Looks like a regression between 4.2 and 4.3

**Closed** 2024-08-15 18:00 UTC
Labels: Bug, Fix Available, Rescheduled
