### ISSUE TITLE
Function throw type

### ISSUE THREAD

**Issue by RebeccaStevens** [microsoft/TypeScript#39846] opened 2020-07-31 06:04 UTC
## Search Terms

Throw Type

## Suggestion

Add ability to type functions with what they will/may throw. Catch statements can then use this information to type errors.

This proposal is about treating throw statements as a special kind of return statement and having function return types being able to reflect this.

In the case of not being able to tell what/if a function will throw, it will be implicit typed as `| throws any`.

If a function's return type is explicitly typed, but this type doesn't include a `throws`, it would be assumed that the it `throws any` - for backwards compatibility.

This would be a prerequisite form my [Promise rejection type](https://github.com/microsoft/TypeScript/issues/39680) proposal.

## Use Cases

Currently when catching errors, TypeScript doesn't know anything about the error's type (they are typed as `any`/`unknown`). Having access to this information would be very beneficial.

## Examples

```ts
// (Super) explicit return type for returning a number and never throwing.
function foo1(): number | throws never {
  return 1;
}

// (Super) explicit return type for always throwing a number.
function foo2(): never | throws number {
  throw 2;
}

// Explicit return type for returning a number or throwing a number.
function foo3(bar: number): number | throws string {
  if (bar < 0) {
    throw 'a';
  }
  return 3;
}

try {
  foo1();
} catch (error) {
  // error is of type `never`
}

try {
  foo2();
} catch (error) {
  // error is of type `number`
}

try {
  foo3(1);
  // foo3(-1);
}
catch (error) {
  // error is of type `string`
}

try {
  foo1();
  foo2();
  foo3(1);
}
catch (error) {
  // error is of type `number | string`
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-07-31 06:42
Duplicate of #13219.

**Comment by RebeccaStevens** [comment] 2020-07-31 09:49
Damn, I missed that issue.

Closing this one seems it's dup.

**Closed** 2020-07-31 09:49 UTC
