### ISSUE TITLE
Type not interpreted properly (possible bug)

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#22263] opened 2018-03-01 15:55 UTC
TypeScript 2.7.1:

Please try this in TS playground, you will see errors where my comments says bad/really bad.
`v` variable is properly typed before `foo2`, inside `foo2` not anymore.

```typescript
function foo(fn: () => { icon, text, small } | string) {
    let
        v = fn();
    if (typeof v === "string") {

    }
    else {
        if (v.icon) {

        }

        v.small;    // good
        v.text; // good

        foo2(() => {
            v.small // bad
            v.text  // really bad
        });
    }
}

function foo2(fn: () => void) {    
}
```

if you change to following all works as expected:
```ts
function foo(fn: () => { icon, text, small } | string) {
    let
        v = fn();
    if (typeof v === "string") {

    }
    else {
        if (v.icon) {

        }

        v.small;    // good
        v.text; // good

        let c = v;  // added intermediate var

        foo2(() => {
            c.small // ok
            c.text  // ok
        });
    }
}

function foo2(fn: () => void) {    
}
```

**Comment by andy-ms** [comment] 2018-03-01 15:57
Duplicate of 9998.
There is no error if you write `const v` instead of `let v`.

**Closed** 2018-03-15 18:41 UTC
Labels: Duplicate
