### ISSUE TITLE
'A type predicate's type must be assignable to its parameter's type' should not fire when in a generic predicate function

### ISSUE THREAD

**Issue by Nokel81** [microsoft/TypeScript#54116] opened 2023-05-03 18:07 UTC
# Bug Report

### 🔎 Search Terms

- 2677
- predicate
- user defined
- generic function

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about predicates

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230502#code/C4TwDgpgBAogHsATgQwMbAPKIDwBUA0UAqoQGLIA2FARmgNZQC8UAdhAG4SIB8TUuUCAggsAJgGdiUAPz8oALijkqtVHQDcAKE1CwAe0TAoAMwCuLdAEs9LKJfGlzVm3m4AKdpUW4AlIs8UdpLwSGiYOARKTsDWLIRuAHRJyIgA5uKK5nQsegDuLADaALo+TLxZOfm8AN6aUFCIEMCmiLagkHrGUAFMjMwARGYWMTb9WgC+QA)

### 💻 Code

```ts
type ExtractOr<T, U, Fallback = never> = T extends U ? T : Fallback;

export function isFunction<T>(val: T): val is ExtractOr<T, Function, (...args: unknown[]) => unknown> {
  return typeof val === "function";
}
```

### 🙁 Actual behavior

Should be a valid user defined predicate which can narrow union types to just those variants that are functions, otherwise (specifically if `val` is `unknown`) 

For example:

```ts

function foo(x: unknown) {
  if (isFunction(x)) {
    // x should be narrowed to `(...args: unknown[]) => unknown`;
  }
}

function foo(x: number | undefined | ((val: string) => boolean)) {
  if (isFunction(x)) {
    // x should be narrowed to `(val: string) => boolean`;
  }
}
```

### 🙂 Expected behavior

The TSC reports error 2677.

**Comment by fatcerberus** [comment] 2023-05-03 18:25
I don't think it's a dupe of #33912.  That one's about relating the `return` statement(s) in the function to the return type; this is just a type predicate return type being rejected outright, before CFA even comes into play.

**Comment by MartinJohns** [comment] 2023-05-04 07:58
@fatcerberus Maybe. My thought was that the type assignability error appears because the conditional type is not resolved.

**Comment by RyanCavanaugh** [comment] 2023-05-04 20:27
The error message accurately describes what's going on and I think the motivation for that error is pretty straightforward. the only thing you need to do to this code is add this intersection:
```ts
      val is T & ExtractOr
```
which shouldn't meaningfully change the behavior of the function at all

**Comment by Nokel81** [comment] 2023-05-04 20:35
@RyanCavanaugh Unfortunetly that does not work as intended and does meaningfully change the behvaviour. Here is a [playground link](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230502#code/C4TwDgpgBAogHsATgQwMbAPKIDwBUA0UAqoQGLIA2FARmgNZQC8UAdhAG4SIB8TUuUCAggsAJgGdiUAPz8oALijkqtVHQDcAKE1CwAe0TAoAMwCuLdAEs9LKJfGlzVm3m4AKdpUW4AlIs8UdpICAGSwCCjoWHhkTsDWLIRuAHSpyIgA5uKK5nQsegDuLADaALo+TLy5+UW8AN6aUFCIEMCmiLagkHrGUAFMjMwARGYW8TZDWgC+2qPOtsZ6egCMbnA5LHmFLBUNTZa9bvaOYwlrPruNTVBd0ACafLc9UHBa11AA9B8vUOIAFnpTBRRFBqNAWOlEIUICDgHooAADFJpTLZKDVbZlCqMKqbGosBFvKAzGaaObjBZLABMa0ULFMAFswYgoAAfdFiCDGSxsEHstweLy-JA8jLY3jUJYUCDIHaXfaHY5xM5wC5QPbXW5QB7MJ69V5XJqoGziIzURSSvTS2V8OBuIZDHxEppfH7-QHA0HgyHQ2HwpEBRSmxCi8WgqUyglEklAA)

```ts
type ExtractOr<T, U, Fallback = never> = T extends U ? T : Fallback;

export function isFunction<T>(val: T): val is T & ExtractOr<T, Function, (...args: unknown[]) => unknown> {
  return typeof val === "function";
}

function foo1(x: unknown) {
  if (isFunction(x)) {
    type Y = typeof x;
    // x should be narrowed to `(...args: unknown[]) => unknown`;
  }
}

function foo2(x: number | undefined | ((val: string) => boolean)) {
  if (isFunction(x)) {
    type Y = typeof x;
    const b: boolean = x(""); // <--- error here, x("") returns unknown
    // x should be narrowed to `(val: string) => boolean`;
  }
}
```

**Closed** 2023-05-07 00:03 UTC
Labels: Working as Intended

**Comment by Nokel81** [comment] 2023-05-07 23:31
@RyanCavanaugh why is this closed? I have shown why your "solution" doesn't work.

**Comment by solovevserg** [comment] 2023-12-07 16:02
Hello! 👋

Maybe it's too late, but here is the solution ([playground link](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230502#code/C4TwDgpgBAYgrgOwMYB4AqAFAhgJywWwGcoIAPYCBAE2JwiyoHsEAbEKLBEAbQF0oAvBy58ANFDQAlCMDg4EgqIgDWCRgHcEAPkUAKAHSHcAc0IAuCdjxEAlIJ1SZchAG4AUG9CQoAUXJ4kYAB5HHRxAFVxGCwWFgAjLCRlHSE-YADgMKhwnTIKamIECAA3CBwoAH4oXWjYhKSSckoaCUrYGPjE5SgLItKcOws0jKycjzIwRhxgKAAzRECAS2YoRcJ4ZGBlhHQtXWKYizQbCwOWVeJhxODQtCiF++QUFTVNPi0dAG83KCg6WXkUC8EEYsygZ0EAiEACJ5ptttD3ABfDxwpYrWaMRgARl0pAsLw0CDs31+izBujWG3RCDxNhJP1+QPA0AAmopgaCoKR3EyoAB6fncqCEAAWjDgLCoUDi0AQuBwGgg0uAjCgAAMDEYcKYCQhVES+HYBDpCZp1byoCiUW40VsMViAEx43pwfCy8oAHyU1Ags0WRWl3t0+0OIvSAeMxp0cSxLHoxIZZIpVIW9tppHpUFJTOBUHZQk5YJ5jN+SGYhBmcQsscY8c4ilIumh0Jslt+guFYolUplcoVSpVas1ZwslZwkejMrjCYtjOtqLT2zmWIAzC6oAg3R6oN7EFQ-QHlUnVin1kvmHST788wXmZAuSW+Z3SCLxZLpbLNyUyvO3CigA))

```typescript
type Func<TParams extends readonly any[] = any[], TReturn = unknown> = (...args: TParams) => TReturn;

type ExtractOr<T, U, Fallback> = Extract<T, U> extends never ? (Fallback extends T ? Fallback : never) : Extract<T, U>

export function isFunction<T>(val: T): val is ExtractOr<T, Func, Func<unknown[]>> {
  return typeof val === "function";
}
```

The original problem comes from the posible situation, when your `T` doesn't intersect with `Function` type completely (for example type `number` has no overlap with `Function`) which leads to the resulting type like `(val: number) => val is Function`, but it's incorrect due to TS compiler rule: "A type predicate's type must be assignable to its parameter's type".

So you need to handle this situation, ensure that `Fallback` type actually extends `T` before returning it. Otherwise you should return `never` as a Predicate type just like in the example above.

**Comment by Nokel81** [comment] 2023-12-07 16:28
ah thanks, will take a look
