### ISSUE TITLE
Weird interaction between default arguments and strict-null

### ISSUE THREAD

**Issue by evmar** [Microsoft/TypeScript#11424] opened 2016-10-06 17:16 UTC
**TypeScript Version:**  Version 2.0.5

**Code**

(with `--strictNullChecks` on)

``` ts
function x(y = 'a', z: number) {}
function x1(y: string, z: number) {}

// Construct error messages to reveal the type of these functions:
let test1: void = x;
let test2: void = x1;
// They have the same type:
// ERROR: Type '(y: string, z: number) => void' is not assignable to type 'void'.
// ERROR: Type '(y: string, z: number) => void' is not assignable to type 'void'.

// However, they have different observable behaviors:
x(undefined, 1);  // OK
x1(undefined, 1);  // ERROR
// ERROR: Argument of type 'undefined' is not assignable to parameter of type 'string'.
```

Note that the second parameter (`z`) is necessary to trigger this behavior; if you drop `z` from this example, then the first param `x` has a `?` as you'd expect.

(So it's even possible this is just a bug in how the function type is printed...?)

**Comment by RyanCavanaugh** [comment] 2016-10-06 17:31
We should be displaying the defaulted parameter as `x?` or `: string | undefined`

**Comment by sandersn** [comment] 2016-12-08 16:49
This is a duplicate of #11900 that points out a different symptom of the bug that needs to be fixed.

**Closed** 2017-02-13 21:30 UTC
Labels: Bug
