### ISSUE TITLE
A globally invoked `tsc` call should use the local `tsc` version if available

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#23072] opened 2018-04-02 17:49 UTC
When `tsc` is globally executed, it should shell out to a local version of `tsc` if there is one present in the node modules bin for the workspace it was invoked in, to respect project-local ts dependency versions.

**Comment by mhegazy** [comment] 2018-04-02 19:02
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/5157

**Comment by weswigham** [comment] 2018-04-02 20:14
We should reconsider. Like @alexeagle stated, we can just check the local `package.json` for a typescript dependency; and we have far more reliance on node now than two years ago when we made the determination that we didn't want to do that.

**Closed** 2018-04-17 15:50 UTC
Labels: Duplicate
