### ISSUE TITLE
useDefineForClassFields subclass field emits defineProperty (with undefined)

### ISSUE THREAD

**Issue by chriskrycho** [microsoft/TypeScript#35051] opened 2019-11-12 02:04 UTC
When using `declare` on a subclass, following the TS compiler suggestion when using `useDefineForClassFields`, the emitted output does a `defineProperty()` with `void 0` as its value. My expectation from reading the announcement post was that it would *not* do so, and would instead simply mark the type *without* triggering the emit. I'll freely admit this may be a misunderstanding on my part, but if so I expect it's tripping up other folks as well.

(May be a duplicate of #34972.)

**TypeScript Version:**  3.8.0-dev.20191105

**Search Terms:** useDefineForClassFields emit subclass

**TypeScript Nightly**
[Playground link](https://www.typescriptlang.org/play/index.html?useDefineForClassFields=true&ts=3.8.0-dev.20191105&ssl=11&ssc=23&pln=8&pc=1#code/MYGwhgzhAEBiD29oG8BQ1oCMwCcBc0EALjgJYB2A5tAD7TkCuAtpgKY7QC80ALAEwBuVAF9UqUJBgBFBgwAe0VnKKtyAExgIkaDGtYScrLLgLEyVIaKA)

Compiler Options:
```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

**Input:**
```typescript
class Foo {
  bar: string | number = 42;
}

class Quux extends Foo {
  declare bar: string;
}

```

**Output:**
```javascript
"use strict";
class Foo {
    constructor() {
        Object.defineProperty(this, "bar", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: 42
        });
    }
}
class Quux extends Foo {
    constructor() {
        super(...arguments);
        Object.defineProperty(this, "bar", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: void 0
        });
    }
}
```

**Expected behavior:**
```javascript
"use strict";
class Foo {
    constructor() {
        Object.defineProperty(this, "bar", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: 42
        });
    }
}
class Quux extends Foo {}
```

**Comment by sandersn** [comment] 2019-11-12 17:58
Yep, it's a duplicate of #34972. The output is exactly backward of the intended semantics.

**Closed by sandersn** 2019-11-12 17:58 UTC
