### ISSUE TITLE
VS Code file rename ignores importModuleSpecifier

### ISSUE THREAD

**Issue by krryan** [Microsoft/TypeScript#25739] opened 2018-07-17 20:17 UTC
**TypeScript Version:**  3.1.0-dev.20180626

**Visual Studio Code Version:** 1.26.0-insider

**Search Terms:** importModuleSpecifier

**Code**
`settings.json`
```json
    "typescript.preferences.importModuleSpecifier": "non-relative",
```

`foo/bar.ts`
```ts
export test = 1;
```

`some/path/file.ts`
```ts
import { test } from 'foo/bar';
```

Right-click on `foo/bar.ts` and choose Rename. Name it `foo/baz.ts`.

**Expected behavior:**
`some/path/file.ts`
```ts
import { test } from 'foo/baz';
```

**Actual behavior:**
`some/path/file.ts`
```ts
import { test } from '../../foo/baz';
```

(It's not clear to me if this should be a TS issue or VS Code issue, my apologies if I have misplaced this.)

**Comment by andy-ms** [comment] 2018-07-17 22:29
@krryan What's your `tsconfig.json`? Without some setting such as "baseUrl"`, we can't use a non-relative path because module resolution will fail.

**Comment by neilsoult** [comment] 2018-07-20 23:18
fwiw I started noticing today that even though my setting is `"typescript.preferences.importModuleSpecifier": "auto"`
my imports are being renamed to longer paths, using values in my tsconfig 'paths' settings, even when the file import is in the same folder.

**Comment by andy-ms** [comment] 2018-07-20 23:27
@neilsoult Could you test with `typescript@next` and try to come up with a repro? Does it only happen when renaming files, or do import fixes / import completions have the problem too? (Import fix is when you have an error and a light bulb pops up and offers to import it. Completions is when you type 'foo' and the completion list offers to import it.)

**Comment by neilsoult** [comment] 2018-07-23 17:38
It's hard to create a repro right now, but it seems to happen when moving/renaming files/folders, and may possibly be linked to problems ( like, errors because of import paths and the like ). I'll update if I'm able to create a fully reproducible scenario.

**Comment by neilsoult** [comment] 2018-07-25 18:29
As a small update, I think it is related to the option "typescript.updateImportsOnFileMove.enabled".
When either this is set to "always" or "prompt" and I choose yes at the prompt, it goes through my entire codebase and renames relative imports to longer paths.

**Comment by JacksonKearl** [comment] 2018-07-26 17:25
Experiencing same issue. Here's repro:
```
│   .gitignore
│   tsconfig.json
│
├───.vscode
│       settings.json
│
└───src
    ├───A
    │       a.ts
    │
    └───B
            b.ts
```

a.ts:
```export let a = () => { };```

b.ts:
```import { a } from "src/A/a";```


tsconfig.json:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "esModuleInterop": true,
        "target": "es6",
        "moduleResolution": "node",
        "outDir": "dist",
        "baseUrl": "."
    },
    "include": [
        "src/**/*"
    ]
}
```

settings.json:
```
{
    "typescript.preferences.importModuleSpecifier": "non-relative"
}
```


Steps:
 - move `a.ts` to `src/B/`
- accept "rename imports?" dialog
- the import staement in `b.ts` is now `./a` (should be `src/B/a`)
- move `a.ts` back to `src/A/`
- accept "rename imports?" dialog
- the import staement in `b.ts` is now `../A/a` (should be `src/A/a`)

Here's a repo:
https://github.com/JacksonKearl/ts-rename-bug-demo

**Comment by andy-ms** [comment] 2018-07-26 22:51
@mjbvz Before calling "getEditsForFileRename", vscode should call "configure" setting global preferences. Note that this can't be done per-file since getEditsForFileRename affects multiple files. It looks like currently there is no "configure" that would tell us the importModuleSpecifier preference.

**Comment by mjbvz** [comment] 2018-07-26 23:09
Ok, should we still call `configure` on the individual file too or is this not necessary?

**Comment by andy-ms** [comment] 2018-07-27 00:00
Not necessary.

**Comment by mjbvz** [comment] 2018-07-27 00:37
Pushed fixed on VS Code side for this

**Closed** 2018-07-27 00:41 UTC
Labels: Bug, Fixed

**Comment by digeomel** [comment] 2021-04-14 10:16
I'm having a similar (if not the same) issue in version 1.55.2 (just updated, but it was happening before).

This is (part of) my tsconfig.json:

```
"compilerOptions": {
        "baseUrl": "./",
        "outDir": "./dist",
        "sourceMap": true,
        "declaration": false,
        "downlevelIteration": true,
        "experimentalDecorators": true,
        "module": "es2020",
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "importHelpers": true,
        "allowSyntheticDefaultImports": true,
        "resolveJsonModule": true,
        "target": "es2015",
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2020.string",
            "es2019",
            "dom",
            "esnext.asynciterable"
        ],
        "paths": {
            "@models/*": [
                "projects/myproject/src/app/core/models/*"
            ],
            "@services/*": [
                "projects/myproject/src/app/shared/services/*"
            ],
            ...
```

I've tried with
`"typescript.preferences.importModuleSpecifier": "non-relative",`
and
`"typescript.preferences.importModuleSpecifier": "shortest",`

I always get the longest relative path, like `../../../../../path`

**Comment by digeomel** [comment] 2021-04-14 14:54
So, after reading this: https://stackoverflow.com/a/65583056/134120 it appears that the problem was caused by the TypeScript Importer extension. I disabled it, and now it works as expected.
