### ISSUE TITLE
Using generic parameters as type of default argument errors

### ISSUE THREAD

**Issue by Gregroam** [Microsoft/TypeScript#30949] opened 2019-04-16 02:39 UTC
**TypeScript Version:**  3.4.1

**Search Terms:**
generic parameter argument initialization default

**Code**

```ts
function Fn1<T extends boolean>(arg: T = false) {} //Type 'false' is not assignable to type 'T'.
function Fn2<T extends number>(arg: T = 42) {} //Type '42' is not assignable to type 'T'.

function Fn3<T extends boolean>(arg: T = false as boolean) {} //Type 'boolean' is not assignable to type 'T'.
function Fn4<T extends number>(arg: T = 42 as number) {} //Type 'number' is not assignable to type 'T'.

function Fn5<T extends boolean>(arg: T = false as any) {} //Fine
function Fn6<T extends number>(arg: T = 42 as any) {} //Fine
```

Should be able to use generic parameters as the type of an initialized (default) argument. Would think this should be possible but errors unless I cast as any

**Note:** Am wanting to use this for a conditional return type

**Playground Link:** https://www.typescriptlang.org/play/#src=function%20Fn1%3CT%20extends%20boolean%3E(arg%3A%20T%20%3D%20false)%20%7B%7D%20%2F%2FType%20'false'%20is%20not%20assignable%20to%20type%20'T'.%0D%0Afunction%20Fn2%3CT%20extends%20number%3E(arg%3A%20T%20%3D%2042)%20%7B%7D%20%2F%2FType%20'42'%20is%20not%20assignable%20to%20type%20'T'.%0D%0A%0D%0Afunction%20Fn3%3CT%20extends%20boolean%3E(arg%3A%20T%20%3D%20false%20as%20boolean)%20%7B%7D%20%2F%2FType%20'boolean'%20is%20not%20assignable%20to%20type%20'T'.%0D%0Afunction%20Fn4%3CT%20extends%20number%3E(arg%3A%20T%20%3D%2042%20as%20number)%20%7B%7D%20%2F%2FType%20'number'%20is%20not%20assignable%20to%20type%20'T'.%0D%0A%0D%0Afunction%20Fn5%3CT%20extends%20boolean%3E(arg%3A%20T%20%3D%20false%20as%20any)%20%7B%7D%20%2F%2FFine%0D%0Afunction%20Fn6%3CT%20extends%20number%3E(arg%3A%20T%20%3D%2042%20as%20any)%20%7B%7D%20%2F%2FFine

**Comment by jack-williams** [comment] 2019-04-16 09:06
Duplicate of #28154

**Closed** 2019-04-16 16:41 UTC
Labels: Duplicate
