### ISSUE TITLE
Star-imported module should conform to the type of a string-indexed object

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#17622] opened 2017-08-04 20:59 UTC
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

Suppose I have this module:

```ts
// foo.ts

export const x = 3
export const y = 5
```

Conceptually this module represents a map of strings to numbers, `{ [k: string]: number }`, however if I try to use it directly as such I get a type error:

```ts
// bar.ts

import * as foo from './foo'

function f(map: { [k: string]: number }) {
  // ...
}

f(foo)
//^^^ Argument of type 'typeof "/Users/tom/code/example/src/foo"' is not assignable to parameter of type '{ [k: string]: number; }'.
//      Index signature is missing in type 'typeof "/Users/tom/code/example/src/foo"'.
```

Fortunately there is a workaround: I can simply spread and recompose the module to make it conform to the expected type:

```ts
f({ ...foo }) // this type checks!
```

However it'd be nice if the more straightforward approach just worked!

**Comment by pelotom** [comment] 2017-08-04 21:08
Interestingly, there doesn't seem to be a problem when using a value type of `any` (`typeof map` =`{ [k: string]: any }`).

**Comment by aluanhaddad** [comment] 2017-08-06 02:33
Since imports are inherently static, why not use
```ts
import * as foo from './foo';
declare function bar(map: typeof foo): void;
```
on a side note, this allows for some erroneous coding patterns such as
```ts
// bar.ts
export let x = 1;
```
```ts
// foo.ts
import * as foo from './foo';
function bar(map: typeof foo) {
  map.x = 0; // WAT
}
```

**Comment by pelotom** [comment] 2017-08-06 05:45
> Since imports are inherently static, why not use
> ```ts
> import * as foo from './foo';
>
> declare function bar(map: typeof foo): void;
>```

This was just a minimal repro. In practice, the function I'm trying to pass `foo` to might be defined elsewhere that knows nothing about `foo`. It might even be in a 3rd party library which I have no control over.

> on a side note, this allows for some erroneous coding patterns such as
> ```ts
> // bar.ts
> import * as foo from './foo';
> 
> function bar(map: typeof foo) {
>  map.x = 0; // WAT
> }
> ```

Yeah, that's an oddity which should probably get its own bug report.

**Comment by pelotom** [comment] 2017-08-06 05:49
It seems like when treating `foo` as an object it should be no different than if instead of importing a module we had declared

```ts
type Foo = {
  readonly x: number
  readonly y: number
}

let foo: Foo = {
  x: 3,
  y: 5,
}
```

And in this case,

```ts
function bar(map: { [k: string]: number }) {
  // ...
}

bar(foo)
```

type checks just fine.

**Comment by aluanhaddad** [comment] 2017-08-06 06:44
Indeed. With respect to reporting a bug about the mutable binding via an indirect reference to a module namespace object, the closest approximation is the `readonly` modifier which currently doesn't do much. It still probably should be part of the type though.

**Comment by kitsonk** [comment] 2017-08-06 14:56
Duplicate of #16248
Duplicate of #10998

**Comment by thw0rted** [comment] 2017-08-17 08:51
I can't get the workaround from the OP to work with a JS library I'm using:

````ts
// foo.d.ts
declare module "foo" {
  class Bar { ... }
}

// app.ts
import * as Foo from "foo";
let f = {...Foo};
let bar = new f["Bar"];   // <-- Flagged with "no index signature" error
````

I just need a way to pass around class constructors to dynamically choose a subclass at runtime.  In my legacy (JS) code I did this with string-indexing into the module -- I'm not married to that solution in TS but it seems like it should work.

**Comment by aluanhaddad** [comment] 2017-08-17 12:32
@thw0rted just in case, did you forget to `export` `Bar`?

**Comment by thw0rted** [comment] 2017-08-17 12:55
I've got the wrong end of the stick here.  What I'm trying to do is select a class declared in a module using the class name as a string.  What I gave above as an example works without any workarounds, the problem is when I make the index parameter a variable instead of a literal. It's complaining that I can't index into the module with any old string, and I don't know how to constrain it such that the variable is forced to be a valid index key.  I thought that was `keyof` but I can't get that to work either.

A better example:

````ts
import * as Foo from "foo";
let b1 = new Foo["Bar"];  // I was wrong, no compiler error here
let k2: string = "Bar";
let b2 = new Foo[k2];    // compiler error, "has no index signature"
let k3: keyof Foo = "Bar";  // compiler error, "Cannot find name 'Foo'."
let b3 = new Foo[k3];    // I think this would work?
````

Of course I can avoid this by just casting Foo to `any` but that kind of defeats the point.

**Comment by aluanhaddad** [comment] 2017-08-17 13:34
I see what the issue is now.
```ts
import * as Foo from "foo";
let k3: keyof Foo = "Bar";  // compiler error, "Cannot find name 'Foo'."
```
needs to be written as
```ts
import * as Foo from "foo";
let k3: keyof typeof Foo = "Bar"; 
```
since `keyof` takes a _type_ but `Foo` is a value. In some situations, foo may also refer to a type but in the example you have shown, it is only a value.

**Comment by RyanCavanaugh** [comment] 2017-08-17 22:48
We should be able to apply the same treatment of inferred indexers to star-imports as we do for object literals, since (in theory) we know the entire set of members (because ES6 modules are immutable).

**Closed** 2017-10-11 22:13 UTC
Labels: Bug
