### ISSUE TITLE
async function return type must be global Promise<T>

### ISSUE THREAD

**Issue by jzhang1** [microsoft/TypeScript#36257] opened 2020-01-17 10:07 UTC
## Suggestion

Currently when we implement an async function, the type checked wants the return type to be exactly Promise<T>. Something like this:

async function foo(...): Promise<T>

It seems that this is overly strict. Sometimes it would be helpful to implement APIs that can do something like this:

async function foo(...): Promise<T> & { ... interface ...}

so that we can give the caller the option of either awaiting on the result of foo or calling some other API such as

await foo(...)
await foo(...).execute(...)

## Use Cases

An use case would be wrapping APIs such as IndexedDB. For example, when we call createObjectStore, we can optionally call objectStore.createIndex, but this has to be done within the same transaction as the call to createObjectStore. We need to give the caller an option to execute the createIndex code within the same transaction.

So the API would be something like:
await db.createObjectStore(...)
or
await db.createObjectStore(...).execute(objectStore => objectStore.createIndex(...))

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by ajafff** [comment] 2020-01-17 11:37
an `async` function always returns an instance of the native Promise implementation. Regardless of what you return from the function, the return value is awaited and a new standard Promise is fulfilled with that value.

**Comment by nmain100** [comment] 2020-01-17 17:18
Duplicate of https://github.com/microsoft/TypeScript/issues/35191.  If you want this change you'd have to start in TC39 and get them to change the fact that `async function` always returns the native `Promise` type at runtime, no matter what you do in the body.

**Comment by MartinJohns** [comment] 2020-01-17 17:18
Duplicate of #35191, #15292.

Search terms used: global async promise

**Closed** 2020-01-20 18:00 UTC
Labels: Duplicate
