### ISSUE TITLE
doesn't work return params for function

### ISSUE THREAD

**Issue by tema1411** [microsoft/TypeScript#46603] opened 2021-10-30 09:45 UTC
# Bug Report

### 🔎 Search Terms
doesn't work return params for function
function return parmas doesn't work 
return function params with generic type don't work 

### 🕗 Version & Regression Information

- This is a crash
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 'return type function type with  generic'
### ⏯ Playground Link

[Playground link with relevant code #1](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKuEGcoF4oOAJwJYDsDmUAPlDgK4C2ARhBgNwBQ9okUA8pQFYCMKUA3lAAeALihcADFAC+DZtHYcATLwEioiyTMZyoAcQjA4kADwwoEQcAg4AJkiOIAfLzMWrtpOmz4o9KP6gAfjZOLj8A0VdLazsSCmoMXwDkoJClJJT-URwIADcaRnoAYwB7HHQoADMcXlNzaI9YeARHAAoAQ0iASmF9Q3hTZ2RnPnD-LEqoVrkSyfaUZFQAci9cPCWu-jGUjANSDBq+NQkpKAB6M+AACxpoBCuS0gAbGyhqEhKocix0doBrCAAOigAGUHs9Xu8ru0kKUMLsisAoDpKCAoHhrDQsEVtlJGMkJlMZnMFssyFQaBstpl-LtgPtDmoNKcLtdbmhwS83tAcJ9vr8AcCwY8uVCYVA4QikSi0Rictgcck8dtrhgSgB3KAAUXhJQwrSWVnQG3oytK5SRgl41VaEi6QA)

[Playground link with relevant code #2](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gRgKwIxQLxQN5QB4C4kAMUAvgFCiSyIBMamOuU1RZF08CAzHVnlJy1KkAZgFcAdgGNgASwD24qMPEAKAIaMAzsABOM8QHMAlIw5IRE6fMXL1jcaIC2cCDpNUE1C1NkKlqjSg4OTkAGwg1cXcOTm8rP1tAiQBrcTkAdyjTRBQAHw9afJiofPEIADdXTFIoWqgZYSgVNjlGtTRUdABybT1DLqMoHQhgUR1FDD5CYgBuGrqGppa2ju6HZ1cBoZGxib5mMjr6xubwCFaods7u4LCI8S3h0fHMfYJiKAB6T4BZUW0gtBXHIdDooLgVEIjsAABY6DJQMrpKAAUVBIJUACJgBBtJijKQyKRJAoAdg6LZdKIIEYgA)

### 💻 Code

#1
```ts
type Types = string | number;

type Obj1 = { x: 10 };
type Obj2 = { x: 20 };

type GetType<T extends Types> = T extends string 
    ? Obj1
    : T extends number 
        ? Obj2 
        : never


const fn = <T extends Types>(a: T):GetType<T> => {
    if (typeof a === 'string') {
        return {x: 10} //there should be no mistake. Should be has correct type by generic
    }

    if (typeof a === 'number') {
        return {x: 20} //there should be no mistake. Should be has correct type by generic
    }

    throw Error('test')
}

const x = fn(10)
```
#2
```ts
type Obj1 = { x:10 }
type Obj2 = { x: 20 }
type Obj3 = { x: 30 }

function fn(a: string): Obj1
function fn(a: number): Obj2
function fn(a: boolean): Obj3
function fn(a: unknown): Obj1 | Obj2 | Obj3 | never {
    if (typeof a === 'string') return {x: 10};
    if (typeof a === 'number') return {x: 20}
    if (typeof a === 'boolean') return {x: 20} //Must be erorr :(

    throw new Error("test")
}

const x = fn(true)
```
### 🙁 Actual behavior

#1 has error Type '{ x: 10; }' is not assignable to type 'GetType<T>'.(2322);

#2 has not error with wrong return type 

### 🙂 Expected behavior

#1 there should be no mistake. Should be has correct type by generic
#2 has error with wrong return type

**Comment by MartinJohns** [comment] 2021-10-30 09:53
> This is a crash

This is not a crash.

---

Number 2 is working as intended. The implementation is not checked against the overloaded signatures. It's a duplicate of #13235.

**Comment by tema1411** [comment] 2021-10-30 10:16
> > This is a crash
> 
> This is not a crash.
> 
> Number 2 is working as intended. The implementation is not checked against the overloaded signatures. It's a duplicate of #13235.

Thanks. What about the first option?

**Comment by jcalz** [comment] 2021-10-30 11:48
That’s a duplicate of #33912 I think

**Comment by 4lessandrodev** [comment] 2021-10-31 20:53
I also have a similar error

```ts
const data = ["a", "b", "c", 1, 2, 3];

// Type '(string | number)[]' is not assignable to type 'number[]'
const result: number[] = data.filter((i) => typeof i === 'number');

console.log(result); // [1, 2, 3] 
```

**Comment by MartinJohns** [comment] 2021-10-31 21:54
@4lessandrodev That's completed unrelated, and is working as intended. Your inner function is **not** a type guard, it's just a function returning a `boolean`. As a result it's not used to narrow the type. You can add an explicit type annotation to make it a type guard.

**Closed** 2021-11-03 18:00 UTC
Labels: Duplicate
