### ISSUE TITLE
Conditional not narrowed + upchain information

### ISSUE THREAD

**Issue by icecream17** [microsoft/TypeScript#51193] opened 2022-10-16 20:45 UTC
# Bug Report

note: Probably a duplicate of some combination of issues

### 🔎 Search Terms

ts(2322)
ts2322
narrow
conditional
intersection

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about (all)
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20221016#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXy1VAA8B5RAHgBUAaeANQD4AKWGKATwC54qBtALp0QEEAFsQqDD3oBKGfBDEMk4AGde8APzxUyMQCMQMeDz0QIAKEsp02PPDhicANxDU6TVjHbdeg4VEJKRl5BkVlVQ0qbU0zEDcTAG9LeDSwPDUMAiIleABeHJJyb19A8UkMWVS0rER4ZkISAvzC8whZeBS0nvgMAAsYHAB3eAAlEERjSTAQAFEfHBhmACIV6p6AXxrHEAxkGHw2Tj4mpQFLbaA)

### 💻 Code

```ts
declare function indexOf<T, V>(array: T[], element: V): V extends T ? number : null

function remove<T, V>(array: T[], element: V): V extends T ? T : never {
   const index = indexOf(array, element)
   if (index === null) {
      throw ReferenceError("")
   }
   return array[index]
   // ^^^^^^^^^^^^^^^
   // Type 'T[][(V extends T ? number : null) & {}]' is not assignable to type 'V extends T ? T : never'.
   //     Type 'T' is not assignable to type 'V extends T ? T : never'.
}
```

### 🙁 Actual behavior

`index` is `(V extends T ? number : null) & {}`

### 🙂 Expected behavior

The if statement should narrow `index` to `number`, and simultaneously provide that `V extends T`, thus satisfying the return type conditional and collapsing `V extends T ? T : never` into `T`

`array[index]` is also `T`, the types match, no error 🎉

**Comment by MartinJohns** [comment] 2022-10-16 21:14
Duplicate of #33912.

**Closed** 2022-10-16 21:53 UTC
