### ISSUE TITLE
Primitives not colourised in generic position

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#3951] opened 2015-07-21 15:25 UTC
Hi,

**Version**: VS 2015 RTM/TS 1.5

In the image below the `string` and `number` should be coloured in the last two lines:

![image](https://cloud.githubusercontent.com/assets/1106823/8804611/01903e22-2fc5-11e5-947c-794c2d07b7e3.png)

**Comment by mhegazy** [comment] 2015-07-21 16:53
this is currently by design. we have disabled some of the colorization logic in this release as it was causing memory pressure. we are working on fixing this in the next release. sorry for the trouble.

**Comment by zhengbli** [comment] 2015-09-18 10:04
This should be fixed by 1.6 release.

**Comment by mhegazy** [comment] 2015-09-18 21:33
thanks @zhengbli

**Closed** 2015-09-18 21:33 UTC
Labels: Bug, Fixed
