### ISSUE TITLE
compile error in 2.7 for indexed types work with generics 

### ISSUE THREAD

**Issue by tommytroylin** [Microsoft/TypeScript#21529] opened 2018-02-01 06:59 UTC
**TypeScript Version:**  2.7.1

**Search Terms:** typer inference, indexed types, generics

**Code**
```ts
type Foo = {
  [name: string]: string[] | undefined;
};

const foo: Foo = {};
function bar<SomeName extends string>(name: SomeName): void {
  foo.any!.concat(); // ok
  foo[name]!.concat(); // Property 'concat' does not exist on type 'Foo[SomeName]'
  const newFoo = foo[name]; // ok
  newFoo!.concat(); // ok em....
}
```
with tsconfig (removed other configs)
```json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "strict": true,
    "strictPropertyInitialization": false
  }
}
```

**Expected behavior:**
No Error in `2.7` & `2.6`

**Actual behavior:**
No Error in `2.6` 
but in `2.7` it throws `Property 'concat' does not exist on type 'Foo[SomeName]'` 

FYI. I found some ways to make this error disappear. I think there must be something related but I can't tell.
* remove `undefined` type in `Foo` 's value
* use a temp var to avoid directly usage like `const newFoo = foo[name]`
* remove generics and define param `name` to be `string`

**Comment by tommytroylin** [comment] 2018-02-01 07:06
confirmed it exists on version `2.8.0-dev.20180201`

**Comment by ajafff** [comment] 2018-02-01 09:39
Maybe related to #21368

**Comment by mhegazy** [comment] 2018-02-01 17:47
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/21369

**Comment by tommytroylin** [comment] 2018-02-06 05:27
[playground](https://www.typescriptlang.org/play/#src=type%20Foo%20%3D%20%7B%0A%20%20%5Bname%3A%20string%5D%3A%20string%5B%5D%20%7C%20undefined%3B%0A%7D%3B%0A%0Aconst%20foo%3A%20Foo%20%3D%20%7B%7D%3B%0Afunction%20bar%3CSomeName%20extends%20string%3E(name%3A%20SomeName)%3A%20void%20%7B%0A%20%20foo.any!.concat()%3B%0A%20%20const%20a%20%3D%20foo%5Bname%5D%3B%20%2F%2F%20%20a%20is%20type%20Foo%5BSomeName%5D%0A%20%20a!.concat()%3B%20%2F%2F%20no%20problem%0A%20%20foo%5Bname%5D!.concat()%3B%20%0A%7D%0A) 
should turn on `strictNullCheck` as well

**Comment by tommytroylin** [comment] 2018-02-06 05:38
considering
* error still exists when replacing `undefined` with `null`
* error disappears when `strictNullChecks` turned off
* error disappears when using a temp var (maybe forcing to do a type inference?)

In my opinion, it's a bug in type system

@mhegazy 
any updates on this issue?

**Comment by Kovensky** [comment] 2018-02-13 05:15
This seems to be a problem with the non-null assertion operator when used on the result of a computed member expression.

```ts
import * as types from './types'

interface PreloadTypes {
  post: types.PreloadPostData
  user: types.PreloadUserData
}

interface GlobalPreload {
  post?: { [id: string]: PreloadTypes['post'] }
  user?: { [id: string]: PreloadTypes['user'] }
}
declare var preload: GlobalPreload

function getPreload<TKind extends keyof PreloadTypes> (kind: TKind, id: string): PreloadTypes[TKind]|undefined {
  if (kind in preload && id in preload[kind]) {
    return preload[kind]![id]
    // [id] access errors because it's indexing a possibly undefined object
  }
}
```

Changing the line to, for example, be `preload.user![id]` does not produce an undefined object access error.

Changing the access to be

```ts
const kindPreload = preload[kind]!
return kindPreload[id]
```

instead _still_ causes a build error on the second linke because `kindPreload` may be `undefined`, despite the `typeof` `kindPreload` correctly showing up as `GlobalPreload[TKind]` on hover type info. It's only when it is then indexed that the `| undefined` shows up.

Finally, adding the `!` on the `[id]` access _when_ it's split into multiple vars works -- `return kindPreload![id]` will compile.

Also note that removing the `!` from `preload[kind]!` does _not_ produce `| undefined` on the `typeof kindPreload`; in fact leaving it in there triggers tslint's `no-unnecessary-type-assertion` if you have it enabled.

**Closed** 2018-02-27 20:54 UTC
Labels: Duplicate
