### ISSUE TITLE
Transpiling an asynchronous generator causes an internal compiler exception

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#4144] opened 2015-08-04 08:06 UTC
Attempting to `ts.transpile` this [async generator](https://github.com/jhusain/asyncgenerator)
```ts
async function*(f) { yield f; }
```
throws
```
TypeError: Cannot read property 'members' of undefined
    at resolveDeclaredMembers (D:\repos\TypeScript\built\local\typescript.js:15456:65)
    at resolveTypeReferenceMembers (D:\repos\TypeScript\built\local\typescript.js:15486:26)
    at resolveStructuredTypeMembers (D:\repos\TypeScript\built\local\typescript.js:15705:21)
    at getPropertiesOfObjectType (D:\repos\TypeScript\built\local\typescript.js:15713:24)
    at propertiesRelatedTo (D:\repos\TypeScript\built\local\typescript.js:17272:34)
    at objectTypeRelatedTo (D:\repos\TypeScript\built\local\typescript.js:17238:30)
    at isRelatedTo (D:\repos\TypeScript\built\local\typescript.js:17062:34)
    at checkTypeRelatedTo (D:\repos\TypeScript\built\local\typescript.js:16929:26)
    at checkTypeAssignableTo (D:\repos\TypeScript\built\local\typescript.js:16902:20)
    at isTypeAssignableTo (D:\repos\TypeScript\built\local\typescript.js:16896:20)
```
annotating the generator return value in any way causes the exception to not be thrown. This also only happens when the async generator is anonymous. 

I know that async generators aren't technically valid JS, but attempting to transpile one probably shouldn't throw.

**Comment by DanielRosenwasser** [comment] 2015-08-04 14:25
Looks like a duplicate of #3978, I'll let @rbuckton close this since I think it'd be a worthwhile test.

**Comment by rbuckton** [comment] 2015-08-04 18:17
@weswigham: I'm unable to repro this against master, though async generators are not themselves supported in TypeScript. What version of the compiler are you using? Can you try this against our nightly builds? If you are using node, you can run `npm install typescript@next` to install the most recent nightly build locally in `node_modules/`.

**Comment by weswigham** [comment] 2015-08-04 20:24
This repo'd using the `jake build` version at  4c7b214a69c97eb1746b.

**Comment by rbuckton** [comment] 2015-08-28 22:23
This fails for the same reason as #3978, though asynchronous generators are still not supported.

**Closed** 2015-08-28 22:23 UTC
Labels: Bug, Duplicate
