### ISSUE TITLE
Typing a map over object and retain the keys

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/TypeScript#7698] opened 2016-03-26 15:41 UTC
When mapping a object, TS can't retain the keys accessor.

Following example uses [lodash _.mapValues](https://lodash.com/docs#mapValues), which maps a object.

```typescript
var newUsers = _.mapValues({
  'fred':    { 'user': 'fred',    'age': 40 },
  'pebbles': { 'user': 'pebbles', 'age': 1 }
}, function(o) { return o.age; }); // -> _.Dictionary<number>
let ageFred = newUsers['fred']; // is number
newUsers.fred // <-- invalid because TypeScript can't retain the keys.
```

I can't think a way to type _.mapValues so it would retain the keys. Retaining keys requires new kind of typing capabilities for the TypeScript.

I find myself needing to retain keys in surprising many places, e.g. when uncurrying a object full of functions.

**Comment by FayneAldan** [comment] 2016-03-26 16:38
You have to use [] to access properties in a dictionary. Dot notation does not work.

**Comment by Ciantic** [comment] 2016-03-26 17:17
@FayneAldan oh I know, that is why TS requires a new typing capablities to support *retaining* the keys.

**Comment by FayneAldan** [comment] 2016-03-26 21:30
Keys are still retained. Dot notation is the same as using []. In regular JS, you would use [] if you need to access a property dynamically.

**Comment by Ciantic** [comment] 2016-03-27 18:28
@FayneAldan it can't type check the keys afterwards, that is what I mean by retaining keys. 

I had a issue #3708 that was fixed also, about retaining keys. Right now it can already retain keys if the object is "fresh" and is typed with `<T extends { [k: string] : number }>`. 

But it can't retain the keys if I want to change the key values, it would be a good addition since it would allow to uncurry a object full of actions. E.g.

```typescript
interface IActionProps {
	value?: number;
}

const increaseValue = (s: IActionProps): IActionProps => () => ({
    value: s.value + 1,
});

const decreaseValue = (s: IActionProps): IActionProps => () => ({
    value: s.value - 1,
});

const defaultActions = {
	increaseValue,
	decreaseValue
}

function mapActions(o) {
	return _.mapValues(o, (v) => {
		// Do something
		return () => {
			// Do something
		}
	})
}

let actions = mapActions(defaultActions);

// Now the actions is object like this:
// actions = {
// 	increaseValue: () => { /* Does something */ },
// 	decreaseValue: () => { /* Does something */ },
// }

// And should autocomplete as increaseValue
actions.increaseValue === () => void
```

But it's not possible to write types for this in TypeScript because I can't retain the keys, best thing I get is `actions["increaseValue"]` and it does not type check, which is what I'm after.

**Comment by mhegazy** [comment] 2016-03-28 22:24
looks like a duplicate of #1295, or at least another aspect of it.

**Closed by mhegazy** 2016-03-28 22:24 UTC
