### ISSUE TITLE
Use another overload signature's documented info if exact one's info is missing

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#24414] opened 2018-05-25 16:21 UTC
**TypeScript Version:**  3.0.0-dev.20180522

**Search Terms:** 

**Code**

```ts
/**
 * A
 */
function f(a: 0): void;
function f(a: number): void;
function f(a: number) {
}
f(1);
```

**Expected behavior:**

`f(1)` has documented info `A`.

**Actual behavior:**

`f(1)` has no documented info.

**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment] 2018-05-25 16:24
PRs welcomed.

**Comment by ajafff** [comment] 2018-05-25 18:06
This needs a little more thought than the opening post describes:
Does it only use the description or tags as well? 
Should it only look at other signatures if the current signature has no jsdoc comment at all? 
How should `@param` tags of other signatures be handled?
This may be kind of a braking change if it also uses `@deprecated` tag of another signature.

**Comment by sandersn** [comment] 2019-07-25 22:42
Duplicate of #407

**Closed by sandersn** 2019-07-25 22:42 UTC
Labels: Suggestion, help wanted
