### ISSUE TITLE
Constrained generic class property has `any` type after `instanceof`

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#60810] opened 2024-12-18 13:24 UTC
### 🔎 Search Terms

- Type parameters
- Class
- `instanceof`
- `any`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYGwhgzhAECyCeBRATsg9sgPAFWgUwA8AXPAOwBMYIjkBLUgcwD5oBvAKGmgAcBXAIxC1g0IgC5o2ANydowNKWrJewIhgAU4yQEo2srkQAWtCADoi0ALyiZXAL7sH7cnlBhkeOQur5UGCQgo6FhK9MzQAD7QvKQA1qRoAO6kMuy0AGbQ6nh+yND01GCkwHhomYG5uhxcOcHmttAA9I1cXAB6APyyzfgE3K4k5BKhjN0tYKq8YCASRfDQgDLkjkA

### 💻 Code

```ts
class MyError<T extends string> {
  public t: T;
  constructor(t: T) {
    this.t = t;
  }
}

declare const error: MyError<string> | unknown;

if (error instanceof MyError) {
  error.t;
  //    ^?
  // expected: string
  // actual: any ❌
}
```

### 🙁 Actual behavior

See above.

### 🙂 Expected behavior

See above.

### Additional information about the issue

Potentially related?: https://github.com/microsoft/TypeScript/issues/17253. Although, this one seems to be for anonymous classes, which is not the case here.

**Comment by jcalz** [comment] 2024-12-18 13:46
Your `MyClass<string> | unknown` confused me for a minute into thinking you were asking for something else (i.e., that `MyClass<X> | unknown` should be narrowed to `MyClass<X>` if you use `instanceof`, but that's not possible because `unknown` absorbs everything). Maybe you can just change it to `unknown`, since that's the same thing and there's no implication of narrowing to a union member? 

Is the idea that since `MyClass<T>` is covariant in `T`, that the constraint should be used instead of `any` when narrowing via `instanceof`? And if it were contravariant you'd expect `never`, and if it were invariant or otherwise problematic then `any` would be fine?

**Comment by MartinJohns** [comment] 2024-12-18 13:49
Duplicate of #17473.

**Closed** 2024-12-18 13:58 UTC
