### ISSUE TITLE
TypeScript returns an unexpected value for `findConfigFile`

### ISSUE THREAD

**Issue by blakeembrey** [Microsoft/TypeScript#2965] opened 2015-04-30 03:10 UTC
I'm assuming this is unexpected, because I definitely did not expect it. `findConfigFile` will always return the string `tsconfig.json` and not use the search path when a `tsconfig.json` exists in the current working directory. Here's the offending lines: https://github.com/Microsoft/TypeScript/blob/f988a11cfcb5503d575260563ffb7ea66549d6ad/src/compiler/program.ts#L16-L18

**Comment by MartyIX** [comment] 2015-11-26 19:07
Shouldn't this issue be closed?

**Comment by mhegazy** [comment] 2015-12-02 00:54
thanks @MartyIX. this should be fixed now.

**Comment by blakeembrey** [comment] 2016-03-13 05:38
When did this get fixed? It's definitely still an issue.

![image](https://cloud.githubusercontent.com/assets/1088987/13727126/b74011a0-e89a-11e5-9c0e-cfefdde9dd3e.png)

**Comment by joelday** [comment] 2016-03-21 20:17
@mhegazy @blakeembrey I am also seeing this. Same repro steps and result. It looks like if "tsconfig.json" exists in the cwd(), it immediately returns without any evaluation based on the search path, which makes it impossible to search relative to a given file.

**Comment by joelday** [comment] 2016-03-21 20:22
I can see this being appropriate behavior for a cli fallback, but I wonder if it'd be better for searchPath to just use cwd as a fallback.

**Comment by mhegazy** [comment] 2016-03-21 20:23
reopening. @blakeembrey PRs are welcomed.

@joelday i am not sure i understand the request.

**Comment by joelday** [comment] 2016-03-21 20:25
@mhegazy I'm trying some additional repro conditions to be completely sure about the state of this.

**Comment by joelday** [comment] 2016-03-21 20:30
@mhegazy Okay, the issue is that if my cwd has a "tsconfig.json" in it, the search path is ignored. This is problematic when the cwd is not a parent of the search path. So, if my search path is "../../dir" or its resolved counterpart, it doesn't actually search that path.

**Comment by mhegazy** [comment] 2016-03-21 22:38
sure, we would be happy to take a PR for that too.

**Comment by blakeembrey** [comment] 2016-03-21 23:44
It's a symptom of the same issue, as mentioned in the OP. I'll look at doing a PR for it.

**Comment by mhegazy** [comment] 2016-03-28 21:10
thanks @blakeembrey. 
@joelday, can you give this change a try.

**Closed** 2016-03-28 21:09 UTC
Labels: Accepting PRs, API, Bug
