### ISSUE TITLE
Variable with advanced type with optional property can be assigned simple type value

### ISSUE THREAD

**Issue by hoegge** [Microsoft/TypeScript#17843] opened 2017-08-16 21:09 UTC
**TypeScript Version:**  TSLint 2.4.0 in VSCode and `www.typescriplang.org` playground today (2017-08-16)

**Code**

```ts
let a: { property?: string } = 1234; // why is this allowed?
```

**Expected behavior:**
It should not be possible to assign a number to a variable `a` of type `{ property?: string } ` or `... { property?: string | undefined; }` if strict-null-check is turned on.

**Actual behavior:**
`a` is assigned the value 1234
If the type's property is not optional, it behaves as expected, i.e. type `{ property: string }`.

**Comment by DanielRosenwasser** [comment] 2017-08-16 22:26
Duplicate of #16333. Should be fixed in TypeScript 2.4.2.

**Closed** 2017-08-16 22:26 UTC
Labels: Duplicate
