### ISSUE TITLE
Enum type inference

### ISSUE THREAD

**Issue by zolomatok** [microsoft/TypeScript#51933] opened 2022-12-17 15:40 UTC
# Suggestion

## 🔍 Search Terms

_enum type inference_
_enum inference_
_infer enum type from value_
_short form enum values_
_enum case inference_
_enum without type name_

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Swift allows for [omitting the type name](https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html) of the enum after the variable has already been declared as the enum's type.

For example...
```
enum Planet {
    case mercury, venus, earth, mars, jupiter, saturn, uranus, neptune
}
```
... _can_ be used as:
```
let planet = Planet.earth
planet = .mars
```
instead of
```
let planet = Planet.earth
planet = Planet.mars
```

## 📃 Motivating Example

We often have longer enum type names and omitting them leads to much cleaner looking and more legible code.
Consider that instead of:

```
enum CompassPoint { north, east, south, west }

let direction = CompassPoint.north

switch(direction as CompassPoint) { 
    case CompassPoint.north: 
        console.log("Lots of planets have a north")
        break;
    case CompassPoint.east:
        console.log("Watch out for penguins")
        break
    case CompassPoint.south:
        console.log("Where the sun rises")
        break
    case CompassPoint.west:
        console.log("Where the skies are blue")
        break
}
```

we can write:

```
enum CompassPoint { north, east, south, west }

let direction = CompassPoint.north

switch(direction as CompassPoint) { 
    case .north: 
        console.log("Lots of planets have a north")
        break;
    case .east:
        console.log("Watch out for penguins")
        break
    case .south:
        console.log("Where the sun rises")
        break
    case .west:
        console.log("Where the skies are blue")
        break
}
```

Even a simple assignment looks much nicer this way. Instead of
```
planet = isBlue ? Planet.earth : Planet.mars
```
we can have
```
planet = isBlue ? .earth : .mars

**Comment by MartinJohns** [comment] 2022-12-17 16:00
Duplicate of #45956.

> [x] This could be implemented without emitting different JS based on the types of the expressions

This was mistakenly checked. This requires to emit different JavaScript, otherwise your code wouldn't work anymore.

**Closed** 2023-06-21 01:32 UTC
Labels: Suggestion, Declined
