### ISSUE TITLE
Calling indexOf and includes in a readonly array results in a "not assignable" error message

### ISSUE THREAD

**Issue by ytxmobile98** [microsoft/TypeScript#54422] opened 2023-05-27 01:13 UTC
# Bug Report

I sometimes need to define a readonly array with a fixed set of values, and check if an unknown value matches one of those fixed values – for example, checking if an HTTP status code is one of the null body status codes (101, 103, 204, 205, 304) or redirect status codes (301, 302, 303, 307, 308).

But, after I put these status codes in a readonly array, and then call the `indexOf` method or the `includes` method on it, the compiler would generate an **error message** that the argument of the `indexOf` method or the `includes` method "_is not assignable to parameter of type …_" followed by the constants in the array.

### 🔎 Search Terms

* indexOf
* includes
* readonly
* array
* not assignable

### 🕗 Version & Regression Information

- `typescript` NPM package version: **5.0.4**

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAFlKAHAylAhlArhAwiAEwFMIYBeGAbwCgYYwsAbRgIUIE8AuGAbRgEYADPwA0AwQGYxAJkEAWGYICsYifJgBdEbRgAnIgQCW+4FG581omGumrJdgOx2AHJu0BfGOlKhIUANzU1ABmWGCmhuAwhhAASgbGRKYAFNCYOPjE3AwAtgBGRLoAlFQ6+ti6YPCIqBjYeIQkAHT6RiZQTYbhjFjEEKl1GY1Fge5AA

### 💻 Code

```ts
const httpStatusCodes = {
  nullBody: [ 101, 103, 204, 205, 304 ],
  redirect: [ 301, 302, 303, 307, 308 ],
} as const;

function isRedirect(statusCode: number) {
  return httpStatusCodes.redirect.includes(statusCode);
}
```

### 🙁 Actual behavior

An error is marked under the `statusCode` argument in the `includes` call.

The error message is

> Argument of type 'number' is not assignable to parameter of type '301 | 302 | 303 | 307 | 308'. ts(2345)

If I use `indexOf` instead, the error is the same.

### 🙂 Expected behavior

The code should compile normally without error, because `includes` and `indexOf` are both used to check if a user-supplied argument matches one of the values in the array. In pure JavaScript this operation is totally valid for variables of _any types_.

**Comment by jcalz** [comment] 2023-05-27 01:31
Duplicate of #14520 by way of #26255

**Comment by fatcerberus** [comment] 2023-05-27 02:27
To summarize past discussion around this: Ideally it should be an error to pass a string here, because that’s likely to be a mistake, so that’s why it doesn’t just take `any`.  However there’s currently no mechanism to allow “any type that overlaps with the type of the array” (that’s what #14520 is for); the best TS can do is thus “value must be assignable to the type of the array”

**Comment by fatcerberus** [comment] 2023-05-27 02:29
btw it’s not actually the `readonly` typing that’s the issue here but rather the fact that `as const` also infers literal types.

**Comment by guillaumebrunerie** [comment] 2023-05-27 07:15
Would it make sense to have overloads for the special case "`Array.includes` on an array of literal numbers should accept an arbitrary number" (and the same one with "string" instead of "number"). I feel like the vast majority of complaints about `Array.includes` is when the array contains only literal strings or only literal numbers.

**Comment by fatcerberus** [comment] 2023-05-27 08:39
TS doesn’t have anything resembling template specialization for generics so I don’t think that’s possible.

**Comment by whzx5byb** [comment] 2023-05-27 11:28
@guillaumebrunerie 

[Try this workaround](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIJSnAngHgCoB8yA3gFDIXKgIA2ArgCYQDOOA9AFTICqyzdAB2jI8yDmx4EAFGAAWwZgC4RyCAA9IIBsx7IA-MjkLkykBABu0ADR8IcKAlkBRGhAC2EcMu42YUAPZuAJJa6nqmdG4ARsIAPsh0oTCgEAwAlMpR-v6ucCAA3KQAvqSkoJCwiCgASnYM-iA0WOiYuIQk5JTU9EysnLr8QlAq4pIy8koq6praugZGOqYW1rb2ji7unmDevgHBoWrhyCCRMcPxiUzJZumZ2bkFxaUIDcxgyLJgYAIAymBwYDozAAwv5esgALwdCgnGg0ABCYKwygA2sgAIwABnRNixAGYbAAmTEAFiJmIArDY8aTkABdKydKCpYDMhDbZBomk45A0wnUzEE3mYgDsAoAHPTGUVkHAdC8QG9CqQYIl2cAGlRmLUGKyIOypG8AUDQUwItFoGlochmYCoCAPl9fv9ASCwSwAHTM3VssAe7qMFiGl0m91pQpFIA):
```ts
interface Array<T> {
    includes</* U super T */ U>(this: T extends U ? this : never, searchElement: U, fromIndex?: number | undefined): boolean;
}

interface ReadonlyArray<T> {
    includes</* U super T */ U>(this: T extends U ? this : never, searchElement: U, fromIndex?: number | undefined): boolean;
}
```

**Comment by ytxmobile98** [comment] 2023-05-27 12:18
> To summarize past discussion around this: Ideally it should be an error to pass e.g. a string here, because that’s likely to be a mistake, so that’s why it doesn’t just take `any`. However there’s currently no mechanism to allow “any type that overlaps with the type of the array” (that’s what #14520 is for); the best TS can do is thus “value must be assignable to the type of the array”

I don't think this is a real issue within a scope of _readonly_ array with a set of _compile-time fixed values_.

Consider the use case as you have mentioned: I have a _string_ variable `x` and passes it into an array `arr` with a fixed set of integers.

* If the outer logic is "if the `arr` contains `x`, then do something with `x`":
  * _**This is meaningless.**_ An array full of integers can never contain a string. The "do something" action will never be executed.
* If the outer logic is "if the `arr` does not contain the _number_ `x`, then do something with `x`":
  * _Now `x` is supposed to be a number, but is actually a string._ If you call methods of `x` that are only present on number variables, or if you pass `x` to a different function which expects a number, such mistakes will still be caught in the corresponding contexts.

So this type mismatch is not surely an issue that `Array.prototype.includes` or `Array.prototype.indexOf` should take a notice of. The mismatch itself could indicate a problem at a larger scope within the software project, which could mostly be caught in higher-level components in the codebase.

**Comment by fatcerberus** [comment] 2023-05-27 14:38
> So this type mismatch is not surely an issue that Array.prototype.includes or Array.prototype.indexOf should take a notice of. The mismatch itself could indicate a problem at a larger scope within the software project, which could mostly be caught in higher-level components in the codebase.

You’re right, and the “higher-level component” that’s taking notice of it is *TypeScript*—which is specifically designed to catch potential mistakes in your code at compile time based on the types used.  Unfortunately that sometimes means this particular method is too narrow, due to inherent constraints in the type system.

Anyway, I don’t make the rules, I’m only telling you how this discussion has gone in the past based on responses from team members.  Don’t shoot the messenger.

**Comment by fatcerberus** [comment] 2023-05-27 14:42
See for example https://github.com/microsoft/TypeScript/issues/53904#issuecomment-1513910169

**Comment by fatcerberus** [comment] 2023-05-27 14:52
> I don't think this is a real issue within a scope of readonly array with a set of compile-time fixed values.

Just wanted to address this - like I said above, TS doesn’t have template specialization, so this isn’t a distinction that can be made.  The fixed readonly arrays necessarily have to share the same `include` typing with the mutable ones.

**Closed** 2023-06-01 18:00 UTC
Labels: Duplicate
