### ISSUE TITLE
Destructuring parameters allows implicit any even with noImplicitAny: true

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#8667] opened 2016-05-18 16:08 UTC
With `noImplicitAny: true` set, the following should fail, but it doesn't:

``` ts
const x = ({ f }) => 1;
```

TS 1.8.7

**Comment by Arnavion** [comment] 2016-05-18 19:32
Duplicate of #6935

**Comment by mhegazy** [comment] 2016-05-19 05:00
In deed a duplicate. Should be fixed in typescript@next.

**Closed** 2016-05-19 05:00 UTC
Labels: Duplicate
