### ISSUE TITLE
Generic types considered private?

### ISSUE THREAD

**Issue by bluong** [Microsoft/TypeScript#1602] opened 2015-01-05 20:19 UTC
Hello Typescript!

In our typescript file, we have the following function implementation:
```ts
protected foo<A,B>(): {a: A; b: B;}[] {
  return null;
}
```

When the compiler runs, it throws the following errors
Return type of public method from exported class has or is using private name 'A'.
Return type of public method from exported class has or is using private name 'B'.

Is this expected or is this a bug?  My first instinct is that A/B are not private and thus should not have this error be thrown.

Note that if protected is changed to public, the error doesn't appear.

**Comment by danquirk** [comment] 2015-01-05 22:04
Are you using --declaration? Looks like a duplicate of #1445 if so.

**Comment by bluong** [comment] 2015-01-06 03:04
Yes it looks like we are using declaration.  Please note that this passed using the 1.3 compiler but is now broken through 1.4

**Comment by danquirk** [comment] 2015-01-06 03:05
Got it, thanks for the extra details, I'll close this as a duplicate.

**Closed by danquirk** 2015-01-06 03:05 UTC
