### ISSUE TITLE
Array functions taking predicates should not have to return boolean.

### ISSUE THREAD

**Issue by theSdev** [Microsoft/TypeScript#27496] opened 2018-10-02 11:34 UTC
## Search Terms

predicate find force boolean

## Suggestion

As per #5850 `array.prototype.filter` doesn't enforce `boolean` as a return type anymore. I want to propose the same behavior for wherever a predicate is needed. This means not only `filter`, but `find`, `some`, `every `and maybe others. These functions should not enforce boolean as return type of the predicate passed to them.

## Use Cases

This will be useful wherever the developer is looking for a result that is not missing some value(s).

## Examples

Say I want to find the first `parkSpace` that has `position`. This works in TypeScript 3.1.1:
`this.selectedParkSpace = this.parkSpaces.filter(o => o.position)[0] || null;`

but this doesn't:
`this.selectedParkSpace = this.parkSpaces.find(o => o.position) || null;`

For the latter, TypeScript complains:
> Type 'undefined' is not assignable to type 'boolean'.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by andy-ms** [comment] 2018-10-02 16:15
Duplicate of #19456?

**Comment by theSdev** [comment] 2018-10-02 17:02
@andy-ms definitely not. #19456 is about making this behavior optional for filter whereas I'm suggesting to expand this behavior to similar cases.

**Comment by RyanCavanaugh** [comment] 2019-04-23 19:28
Based on discussion, we'd like to see this with the return type being `unknown` and see if that breaks anything

**Closed** 2019-04-30 16:47 UTC
Labels: Bug, Domain: lib.d.ts, help wanted

**Comment by tuukkapuranen** [comment] 2019-08-23 19:04
I just updated to latest available TypeScript, and found out that the expression

`rows.findIndex(r => r.style === "selected");`

now results in

> Supplied parameters do not match any signature of call target: parameter type mismatch. Parameter 'predicate' should have type assignable to '{(value: ListRow, index: number, obj: ListRow[]): any; }', but it has type '{(d: ListRow): boolean; }'.

Is this expected and is the appropriate workaround to use

`rows.findIndex(r => r.style === "selected" as any);`

from now on?

The TS `compilerOptions` for the project exhibiting this behavior are the following:

        "allowJs": true,
        "skipLibCheck": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "noEmit": true,
        "jsx": "preserve",
        "strictNullChecks": false,
        "strictFunctionTypes": false
