### ISSUE TITLE
[VS2015]Imported class missing from completions in JSX body in extends expression

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#4577] opened 2015-09-01 00:35 UTC
![jsxcompletionsomitsimport](https://cloud.githubusercontent.com/assets/2932786/9593657/294e292c-5006-11e5-903d-ad9b659d2f47.gif)

It looks like it's also missing in any other JSX-expression context.

**Comment by mhegazy** [comment] 2015-09-01 00:38
i find the colorization of `if (true)` annoyingly wrong as well.

**Comment by weswigham** [comment] 2015-09-01 00:40
Isn't it colorized correctly?

**Comment by mhegazy** [comment] 2015-09-03 21:16
well.. lexically yes. but it should not have been.. we need to add a new context for being in a jsx element..

**Comment by danquirk** [comment] 2015-09-03 23:09
Why wouldn't you want your TypeScript code colorized just because it's in a JSX block?

**Comment by DanielRosenwasser** [comment] 2015-09-03 23:43
To clarify, it is **not** colorized correctly lexically, it is colorized as if the code is not JSX text. Visual Studio won't correctly classify this until we have the syntactic classifier back. This honestly might not be too bad to fix in the TextMate grammar though.

**Comment by olmobrutall** [comment] 2016-02-06 08:59
Hi guys, 

My issue (https://github.com/Microsoft/TypeScript/issues/6931) has been classified as a duplicate of this one, but this looks to me like and old corner case bug while in my experience the problem is quite massive. 

In tsx, when using generic types, autocomplete only lets you choose functions. In this case I want to select `boolean` but only `Boolean` is shown. 

![image](https://cloud.githubusercontent.com/assets/720953/12858663/c5b60aa6-cc51-11e5-9715-4b967149d497.png)

Also as noted here imported components don't work when creating JSX tags. You don't need esoteric inheritance with if statements to reproduce it like in the initial example, any JSX tag reproduces this bug.

![image](https://cloud.githubusercontent.com/assets/720953/12858727/30b1da1a-cc52-11e5-80ce-5186c09a0fb3.png)

This means the experience using libraries like react-bootstrap, react-widgets or writing any non-trivial app with imported components gets downgraded. 

Maybe this should be included in 1.8.2? 

Thanks for you work!

**Comment by RyanCavanaugh** [comment] 2016-03-01 21:48
Fix pending @ #7326

**Closed** 2016-03-01 22:27 UTC
Labels: Bug, Fixed
