### ISSUE TITLE
Improve Object.keys(object) and Object.values(object)

### ISSUE THREAD

**Issue by KSXGitHub** [Microsoft/TypeScript#26901] opened 2018-09-05 11:50 UTC
## Suggestion

When all keys and values of `object` is known
* `Object.keys(object)` should return array type of union of known properties
* `Object.values(object)` should return array type of union of known values

## How to implement?

I tried creating the 2 functions:

```typescript
declare function keys<
    Object extends { [_: string]: any },
    Key extends keyof Object
> (obj: Object): Key[]

declare function values<
    Object extends { [_: string]: any },
    Key extends keyof Object
> (obj: Object): Object[Key][]
```

I also tested them: [playground link](https://www.typescriptlang.org/play/#src=%2F%2F%20DEFINE%3A%20Object.keys()%0D%0Adeclare%20function%20keys%3C%0D%0A%20%20%20%20Object%20extends%20%7B%20%5B_%3A%20string%5D%3A%20any%20%7D%2C%0D%0A%20%20%20%20Key%20extends%20keyof%20Object%0D%0A%3E(obj%3A%20Object)%3A%20Key%5B%5D%0D%0A%0D%0A%2F%2F%20DEFINE%3A%20Object.values()%0D%0Adeclare%20function%20values%3C%0D%0A%20%20%20%20Object%20extends%20%7B%5B_%3A%20string%5D%3A%20any%7D%2C%0D%0A%20%20%20%20Key%20extends%20keyof%20Object%0D%0A%3E%20(obj%3A%20Object)%3A%20Object%5BKey%5D%5B%5D%0D%0A%0D%0A%2F%2F%20TEST%3A%20enum%0D%0Aenum%20Enum%20%7B%0D%0A%20%20%20%20abc%2C%0D%0A%20%20%20%20def%2C%0D%0A%20%20%20%20ghi%20%3D%20'ghi'%2C%0D%0A%20%20%20%20jkl%20%3D%208%0D%0A%7D%0D%0A%0D%0Aconst%20EnumKeys%20%3D%20keys(Enum)%20%2F%2F%20EnumKeys%3A%20Array%3C'abc'%7C'def'%7C'ghi'%7C'jkl'%3E%0D%0Aconst%20EnumVals%20%3D%20values(Enum)%20%2F%2F%20EnumVals%3A%20Enum%5B%5D%0D%0A%0D%0A%2F%2F%20TEST%3A%20interface%0D%0Ainterface%20Interface%20%7B%0D%0A%20%20%20%20abc%3A%20'abc'%0D%0A%20%20%20%20def%3A%20%5B'def'%5D%0D%0A%20%20%20%20ghi%3A%20'ghi'%5B%5D%0D%0A%7D%0D%0A%0D%0Adeclare%20const%20obj0%3A%20Interface%0D%0Aconst%20InterfaceKeys%20%3D%20keys(obj0)%20%2F%2F%20InterfaceKeys%3A%20Array%3C'abc'%7C'def'%7C'ghi'%3E%0D%0Aconst%20InterfaceVals%20%3D%20values(obj0)%20%2F%2F%20InterfaceVals%3A%20'abc'%7C%5B'def'%5D%7C'ghi'%5B%5D%0D%0A%0D%0A%2F%2F%20TEST%3A%20namespace%0D%0Anamespace%20Namespace%20%7B%0D%0A%20%20%20%20export%20const%20abc%20%3D%20'abc'%0D%0A%20%20%20%20export%20const%20def%20%3D%20%5B'def'%5D%0D%0A%20%20%20%20export%20declare%20const%20ghi%3A%20'ghi'%5B%5D%0D%0A%7D%0D%0A%0D%0Aconst%20NamespaceKeys%20%3D%20keys(Namespace)%20%2F%2F%20NamespaceKeys%3A%20Array%3C'abc'%7C'def'%7C'ghi'%3E%0D%0Aconst%20NamespaceVals%20%3D%20values(Namespace)%20%2F%2F%20NamespaceVals%3A%20'abc'%7C%5B'def'%5D%7C'ghi'%5B%5D%0D%0A)

### Use with objects

```typescript
const object = {
  abc: 123 as 123,
  def: 456 as 456
}

const objectKeys = Object.keys(object) // objectKeys: Array<'abc'|'def'>
const objectVals = Object.values(object) // objectVals: Array<123|456>
```

### Use with enums

```typescript
enum Foo {
  abc,
  def = 'def'
}

const FooKeys = Object.keys(Foo) // FooKeys: Array<'abc' | 'def'>
const FooVals = Object.values(Foo) // FooVals: Foo[]
```

### It is possible to ignore extra keys/values that don't exist in type definition

```typescript
interface Foo {
  abc: 'abc' // the only known key/value pair of Foo
}

const bar = {
  abc: 'abc' as 'abc', // exist in Foo
  ghi: 'ghi' as 'ghi' // doesn't exist in Foo
}

const foo: Foo = bar
const keys = Object.keys(foo) // TS emits `keys: 'abc'[]` but the correct value is `['abc', 'def']`
```

## Examples

See use cases and playground link above

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by jack-williams** [comment] 2018-09-05 12:06
Duplicate of this closed PR #25832.

As an example why:

```ts
const object = {
  abc: 123 as 123,
  def: 456 as 456
}

const objectKeys = Object.keys<{abc: 123}, 'abc'>(object) // objectKeys: Array<'abc'> whoops, array will contain 'def'
```

**Comment by Kingwl** [comment] 2018-09-05 12:08
> enum Foo {
  abc,
  def = 'def'
}

const FooKeys = Object.keys(Foo) // FooKeys: Array<'abc' | 'def'>
const FooVals = Object.values(Foo) // FooVals: Foo[]

keys of enum has not only "key"

**Comment by AlCalzone** [comment] 2018-09-05 14:09
While crawling through the issues I found this merged PR: https://github.com/Microsoft/TypeScript/pull/18175
Based on this precedence, would it make sense to type Object.keys as the union of all known properties and `string[]` for the unknown ones? Or is there simply no reasonable way to represent such a type?

**Comment by RyanCavanaugh** [comment] 2018-09-17 20:13
Dates back to at least #12253

**Closed by RyanCavanaugh** 2018-09-17 20:13 UTC
Labels: Duplicate
