### ISSUE TITLE
Show an error when `this` used before `super`

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#6197] opened 2015-12-22 04:06 UTC
I'm not 100% sure this is by ES6 spec but the following code errors on Edge and Firefox Nightly:

```typescript
new (class extends Promise {
  constructor() {
    let newThis = this; // Edge: Use before declaration, Firefox: |this| used uninitialized in anonymous class constructor
    super((resolve, reject) => resolve());
  }
})()
```

**Comment by vladima** [comment] 2015-12-22 04:53
duplicate of #4211

**Closed by vladima** 2015-12-22 04:53 UTC
Labels: Duplicate
