### ISSUE TITLE
Type recast

### ISSUE THREAD

**Issue by kratess** [microsoft/TypeScript#59503] opened 2024-08-01 17:39 UTC
### 🔎 Search Terms

"recast", "type recast", "2322"

### 🕗 Version & Regression Information

Version 5.5.4

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgILIN4Chm+QVwGdoQ4BbCALkxzzqJPKuULClAHMBuW3AX2QAfZCHwAbMTz5YsoSLEQoAQjXrEopCtWx01jLSzacedadKwx8IBGGAB7EMkisAFAEpVeBA9bI41dABeT10CdU1mHVDdBg0magAiZzAE3l1pUxk6YBhkFzgAOliI5ECykXExDygIMHwNHjSxWuQAI2oVYLgTLx87ZoKxOw4XVrcsaWT3LiA

### 💻 Code

```ts
interface A {
    username: {
        username: string;
    } | null;
}

interface B {
    username: {
        username: string;
    }
}

function test() {
    const a: A = {
        username: {
            username: "test"
        }
    }

    if (a.username === null) return;

    let b: B = a;
    console.log(b)
}
test();
```

### 🙁 Actual behavior

Type 'A' is not assignable to type 'B'.
  Types of property 'username' are incompatible.
    Type '{ username: string; } | null' is not assignable to type '{ username: string; }'.
      Type 'null' is not assignable to type '{ username: string; }'.

### 🙂 Expected behavior

I know why this error message is shown up but I wonder, wouldn't it be better that the type should be recasted after the if statement? Down the lines username object cannot be null. indeed the function stops if the object is null

**Comment by nmain** [comment] 2024-08-01 17:43
Duplicate of https://github.com/microsoft/TypeScript/issues/42384.  Search terms: "parent narrowing".

**Closed** 2024-08-04 01:31 UTC
Labels: Duplicate
