### ISSUE TITLE
Private variable in a class is treated as public in the transpiled code

### ISSUE THREAD

**Issue by smangalath** [Microsoft/TypeScript#9733] opened 2016-07-14 12:28 UTC
Correct me if I am wrong. There is something fundamentally wrong in the transpilation.

I created a class called Person with an intention to keep the name private to the class and expose it via a method. The transpiled code is making the field ( defined as private)  public, however , in typescript code - it prevents the direct access of private fields outside the constructor function and prototype

My get method is added to the prototype. This is wrong. It should be part of the function constructor itself. 

Is there a way to get this in transpiler ?

Please find the transpiled code and what it should have been ( ideally)

Transpiled code

'use strict';
var Person = (function () {
    function Person(name) {
        this._name = name;
    }
    ;
    Person.prototype.getName = function () {
        return 'Name : ' + this._name;
    };
    return Person;
}());
var p = new Person('John');
console.log(p.getName());

What it should have been ideally

'use strict';
var Person = (function () {

let _name;
    function Person(name) {
     _name  = name;

     this.getName = function () {
        return 'Name : ' + _name;
    };
    };

    return Person;
}());
var p = new Person('John');
console.log(p.getName());
console.log(p._name); //not accessible

**Comment by sgrtho** [comment] 2016-07-14 12:42
As noted in the FAQ this makes _name a shared variable between instances of Person. As with type safety, the **private** annotation is lost in JS output.

**Comment by smangalath** [comment] 2016-07-14 12:48
Thanks for the update but it is not very clear at this point. Can you share the FAQ section ?
Each instance to be holding a copy of _name. I understand that  explicit private annotation is gone in the output, however the transpiler to keep the _name in the closure and not to expose it. JS supports it.

**Comment by sgrtho** [comment] 2016-07-14 12:57
Sorry for my misleading comment. **Your** example shares **_name** between instances, as does the example in the [FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#you-should-emit-classes-like-this-so-they-have-real-private-members). Calling the constructor function will not yield a new closure, but it will refer to the one closure that created when the inner constructor function is returned and assigned to **var Person**.

What you want is not impossible. It just requires the private members to be scoped within the constructor function, which in turn leaves prototypal members our of context.

**Comment by smangalath** [comment] 2016-07-14 13:31
Actually  there is a slight correction in my example. Please see the corrected one. Private variable should be part of the constructor  function itself. This way , each instance will be keeping its copy of _name

var Person = (function(){
function Person(name) {
let _name = name;

 this.getName = function () {
    return 'Name : ' + _name;
};
};

return Person;
}())

var p = new Person('John');
console.log(p.getName());

var p1 = new Person('Mann');
console.log(p1.getName());

console.log(p._name); //not accessible

**Comment by RyanCavanaugh** [comment] 2016-07-14 17:32
Duplicate of #1537 and many others; please search before logging a new issue. Your proposed class gen suffers from side effects described in the very next FAQ entry.

**Closed by RyanCavanaugh** 2016-07-14 17:32 UTC
Labels: Duplicate

**Comment by smangalath** [comment] 2016-07-15 00:31
I am not sure what side effect are referred to. Also please see that we are trying to achieve the plain JS behavior of data hiding in a function constructor. How do we accomplish the same using typescript in the same pattern ? I am looking into the TS implementation and wondering if you are open for suggestions in this area.

**Comment by RyanCavanaugh** [comment] 2016-07-15 01:39
Your proposed codegen needs a closure allocation per method per instance, which doesn't scale properly.

You can write something like this if you're OK with a really bad perf profile:
```ts
function makeFoo(x: number) {
	function privateMethod() {
		x++;
	}
	return {
		bar() {
			return x;
		},
		increment() {
			privateMethod();
		}
	}
}

var j = makeFoo(12);
j.increment();
console.log(j.bar());
```

Regarding suggestions, respectfully, dozens of JS experts (literally the people who write the spec) have thought about this problem for years and not come up with a solution that meets the necessary constraints. There's nothing left to discuss; if you want to post proposed codegen I can explain which constraints would be violated, but the codegen is not changing.

**Comment by smangalath** [comment] 2016-07-15 19:26
Really appreciate for the details and your time

Let me stop by adding the following
Above example is also not free from scalability issues. What we are taking out is the age old practice of neat  data hiding in the constructor functions. My understanding is that if used appropriately, we can manage the copies per instance under control. In other words, how do we achieve the data hiding in the JS output for constructor functions once it moves out of the TS patronage ?

**Comment by kitsonk** [comment] 2016-07-15 20:00
> In other words, how do we achieve the data hiding in the JS output for constructor functions once it moves out of the TS patronage ?

Use a WeakMap (or a WeakMap polyfill).  This is a much better way of managing data that you truly want to keep private.

For example:

```typescript
interface PersonPrivateData {
    name?: string;
}

const personWeakMap = new WeakMap<Person, PersonPrivateData>();

export default class Person {
  constructor (name: string) {
    personWeakMap.set(this, { name });
  }
  getName() {
    return 'Name : ' + personWeakMap.get(this).name;
  }
}

const person = new Person('Joe');
console.log(person.getName());
```

Assuming you don't export the WeakMap from the module, there is no way for the private data to be exposed.  Native WeakMaps are designed to not interfere with GC (and most polyfills don't either) so once all references to a class instance are "lost" the private data will also be freed for GC (this is why there is no way to iterate over WeakMap/WeakSets).

**Comment by sgrtho** [comment] 2016-07-15 22:25
Okey, so we're already at it. For the records now: WeakMap polyfills targeting ES5 are either leaking memory or their contents are not truly hidden (because they rely on a generic "hiding" policy and a non-enumerable property on the key object, which can still be read through getOwnPropertyNames).

Anyways, in the great crowded ether, where all lines of code live, there is little room left for ugly ones - and I think the TypeScript compiler agrees. In the end no mean will suffice. Not in this target language, not in any practical setup or even this life.

**Comment by kitsonk** [comment] 2016-07-16 06:14
Eloquent.  Considering that most run-time engines support WeakMap, you are talking about a fairly narrow situation where someone could perform class abuse.  I do not believe WeakMaps are therefore impractical, especially considering there is no concise way of creating non-enumerable properties for private data.

I do agree though that until TC39 agree on a) [class properties](https://github.com/jeffmo/es-class-fields-and-static-properties) and b) visibility of those properties (not currently proposed) the target language (ES5) makes it hard.

I question if the neurotic fear of squirrelling away private data is a rational one, especially at the cost of performance for everyone using TypeScript?  Clearly it is not.
