### ISSUE TITLE
Differentiated type gets undifferentiated when used in a new closure

### ISSUE THREAD

**Issue by stefan-wullems** [microsoft/TypeScript#40493] opened 2020-09-11 09:53 UTC
**TypeScript Version:**  4.0.2

**Search Terms:**
 Differentiated types
**Code**

```tsx
type AccountMapping = { type: "account-key" };
type MetadataMapping = { type: "metadata"; fieldName: string };

type Mapping = AccountMapping | MetadataMapping;

export default function App(props: { mapping: Mapping }) {
  return (
    <>
      <div />

      {props.mapping.type === "metadata" && (
        <input
          // Here it works fine
          value={props.mapping.fieldName}
          
          onChange={(field) => {
            // Red squigglys
            console.log(props.mapping.fieldName)
          }
        />
      )}
    </>
  );
}
```

**Expected behavior:**

I expect that if I first differentiate the type of a variable, and then create a closure that references that variable, that I don't lose my differentiation.

**Actual behavior:**

The differentiation is lost.

I'm not sure if this is tied to tsx in some way but I couldn't reproduce it any other way.

Codesandbox: https://codesandbox.io/s/confident-gareth-s5kzx?file=/src/App.tsx

Note: the following sandbox does not have the latest version but I confirmed that this still is a problem locally

**Comment by MartinJohns** [comment] 2020-09-11 10:28
And another duplicate of #9998.

**Comment by RyanCavanaugh** [comment] 2020-09-11 15:16
👆

**Closed** 2020-09-11 18:26 UTC
Labels: Duplicate
