### ISSUE TITLE
Nested promise types (e.g., Promise<Promise<number>>) should not be allowed in TypeScript

### ISSUE THREAD

**Issue by noseratio** [microsoft/TypeScript#43522] opened 2021-04-03 23:00 UTC
# Bug Report

### 🔎 Search Terms

Nested promises, promise of promise

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about nested promises

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=7&jsx=0&module=6#code/GYVwdgxgLglg9mABMAjACgJQC5EAUBOcAtjAM4CmAPGCEQEbn4B8iA3ogFCLeL7lQh8SAsTLkAdH1JwANgDdyaACwAmDAG5OAXw4cAhqQCekZOGjwkwFZhwiSFarQbM2nHr36CkqzRx36jE1BIWARkAGYbPEJ7Khp6RhZ2Lh4+ASFo0QpJcml5RVUNbV0DYwhTEItkJSi7MUo6h3jnJiS3HggEUihEAAdEAF5M2Jy8hWU1dRTuNK9hsVHZcd6iv105OBgAE0RSoLNQpCI9GDBMNhTOsDyJGTgAczQ9AHcTntRMDUuu2VuHp9eMHe1gwX24Vxu4jujxebwinym4J+Mj+MMB7xqoKmWkQmHEED0UAgAAs0ORBiwIb9xIxCPgyViOEA)

### 💻 Code

```ts
function f1(): Promise<number> { 
    return Promise.resolve(42); 
}

async function f2(): Promise<number> { 
    return 42; 
}

async function f3(): Promise<number> { 
    return Promise.resolve(42); 
}

async function f4(): Promise<Promise<number>> { 
    const p = Promise.resolve(42);
    return Promise.resolve(p); 
}

void async function main() {
  console.log(await f1());
  console.log(await f2());
  console.log(await f3());
  console.log(await f4());
} ().catch(e => console.error(e));
```

### 🙁 Actual behavior

This code compiles without an error or warning.  Because JavaScript promises get automatically unwrapped, `f1`, `f2`, `f3` and `f4` have essentially the same behavior to the caller, they all return a promise that resolves to a number, which is inconsistent with the return type of `f4`, `Promise<Promise<number>>`.

### 🙂 Expected behavior

There should be an error or a warning for `f4`, suggesting the type should be `Promise<number>`. FWIW, it is impossible to have a promise that resolves to another promise in JavaScript, so nested `Promise<Promise<number>>` doesn't make sense and can be misleading.  

For example, a person coming from C# (where nested tasks like `Task<Task<int>>` is a legit concept), might be tempted to do this in TypeScript:

```ts
const outerPromise: Promise<Promise<number>> = f4();
const innerPromise = await outerPromise;
const result = await innerPromise; 
```

This code compiles, but doesn't behave as one may expect. The inferred type for `innerPromise` is actually `number`, not `Promise<number>`.

**Comment by MartinJohns** [comment] 2021-04-03 23:15
Duplicate of #27711.

**Closed** 2021-04-03 23:40 UTC

**Comment by noseratio** [comment] 2021-04-03 23:43
I overlooked the #27711, thanks for pointing out.
