### ISSUE TITLE
Too narrow typing for Array.prototype.includes

### ISSUE THREAD

**Issue by kulak-at** [microsoft/TypeScript#48247] opened 2022-03-14 10:31 UTC
# Bug Report

The type for `Array.prototype.includes` seems to be too narrow making it hard to use in many use cases. Currently `Array<T>` would use `T` as a parameter for searchElement which makes it impractical when used to check against optional types:
```ts
const arr = [
    "a",
    "b",
    "c",
];

const fn = (val: string | number): val is string => {
    return arr.includes(val);
}
```

The code above should work properly but instead val is too wide typing to be passed to it.

The issue is even more prevalent when used with `as const` keyword:
```ts
const arr = [
    "a",
    "b",
    "c"
] as const;

const isInConstArray = (val: string): boolean => {
    return arr.includes(val); // Error, Argument of type 'string' is not assignable to parameter of type '"a" | "b" | "c"'.
}
```

### 🕗 Version & Regression Information

Seems to be old bug, I could reproduce it in 3.9.7 which seems to be the first to understand `.includes` syntax on the Playground.
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Array / includes

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/MYewdgzgLgBAhgJwTAvDA2gKBjmAiOPAGm1zwCNjSc9g9MBdAbk01ElgEsIBJMAYXDQAgkjgBPVDAAUANzgAbAFwxoCTmADmMAD4wwAVwC25AKYIAlCvIgQC03DCoAfDADe1GAlNQDCJ4gIAHQawAoGACamEHKKFiwAvkA)

### 💻 Code

```ts
const arr = [
    "a",
    "b",
    "c"
];

const isInConstArray = (val: string | number): boolean => {
    return arr.includes(val);
}
```

### 🙁 Actual behavior

Error when passing `val` as parameter to `arr.includes`.

### 🙂 Expected behavior

`arr.includes` should accept wider type and behave like type guard instead.

**Comment by MartinJohns** [comment] 2022-03-14 10:40
Duplicate of #26255 / #14520.

**Closed** 2022-03-16 18:00 UTC
Labels: Duplicate

**Comment by whzx5byb** [comment] 2022-04-03 11:09
Workaround:

```ts
interface ReadonlyArray<T> {
    includes<U>(this: T extends U ? this : never, searchElement: U): boolean;
}

const arr = [
    "a",
    "b",
    "c"
] as const;

declare var v1: string;
declare var v2: number;

arr.includes(v1); // OK
arr.includes(v2); // Error as expected
```

**Comment by amerllica** [comment] 2022-04-23 15:21
Why has the @typescript-bot closed this issue? This issue is still being happend.

**Comment by MartinJohns** [comment] 2022-04-24 10:25
@amerllica The bot has closed the issue because it is a duplicate of https://github.com/microsoft/TypeScript/issues/26255 / https://github.com/microsoft/TypeScript/issues/14520. Feel free to subscribe to the open issue #14520.
