### ISSUE TITLE
(Supposedly) non-empty array causes "Source provides no match for required element at position 0 in target.(2345)"

### ISSUE THREAD

**Issue by twiddler** [microsoft/TypeScript#53698] opened 2023-04-07 22:26 UTC
# Bug Report

### 🔎 Search Terms

map source provides no match nonempty

### 🕗 Version & Regression Information

This happens in nightly, 5.0.3, 3.3.3 (similar error message) and many more versions available in the playground.

I reviewed the FAQ for entries about *Common "Bugs" That Aren't Bugs*.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230407#code/C4TwDgpgBAcg9gOwKIFsygIICcsEMQA8AKgHxQC8UA2kQDRQB0TRVAuqwFAcDGiAzsCi4K1AIz0ATPQDMrIXyi8EArgDMArgm7AAloiiqExEgApcALliJU6ENjyFSASigBvDlE9QsEYOqwIQhwAvmoIZgwouGAmJgBuLuRkCU5AA)

### 💻 Code

```ts
type NonEmptyArray<T> = [T, ...T[]]

const a = [1, 2, 3] as const

function fn<T>(a: NonEmptyArray<T>) {
    return a
}

fn(a.map((v) => v)) // Argument of type '(1 | 2 | 3)[]' is not assignable to parameter of type 'NonEmptyArray<1 | 2 | 3>'. Source provides no match for required element at position 0 in target.(2345)
```

### 🙁 Actual behavior

TypeScript complains that `a.map((v) => v))` is not a valid input for `fn` as it might be missing an element at position 0.

### 🙂 Expected behavior

I might be mistaken, but I understand that [map](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.map) guarantees an array of equal length, which in this case would guarantee an element at position 0.

Thanks for your help. :pray:

**Comment by jcalz** [comment] 2023-04-07 22:40
Essentially a duplicate of #29841

**Comment by twiddler** [comment] 2023-04-07 23:02
I think so, too. Thanks!

**Closed** 2023-04-07 23:03 UTC
