### ISSUE TITLE
Method class enumerable

### ISSUE THREAD

**Issue by sant123** [microsoft/TypeScript#15038] opened 2017-04-05 22:22 UTC
**TypeScript Version:**  2.2.2

**Code**

```ts
class Person {
    greet() { }
    bye() { }
}

function checkProperties(obj) {
    console.log("Keys found in (for-in):");
    for (let key in obj) {
        console.log(`Found key: ${key}`);
    }
}

let p = new Person();

checkProperties(p);
```

**Expected behavior:**
ES5 or ES6 target, the methods should be non-enumerable.

**Actual behavior:**
In ES5 the methods are enumerable.

**Comment by jwbay** [comment] 2017-04-05 22:43
Duplicate of #782? Also see #9769

**Comment by sant123** [comment] 2017-04-05 23:12
None of them @jwbay, properties should be enumerable according with ES6 Classes. Using Object.keys() or for-in loop shows the properties. However, this is not the case for methods.

**Comment by jwbay** [comment] 2017-04-05 23:14
When dealing with ES5 class constructs, methods are just prototype 'properties' that happen to be functions.

**Comment by sant123** [comment] 2017-04-05 23:17
Exactly but not in ES6, and the transpile from ES6 to ES5 should be equal right? I mean, if I change my target from ES5 to ES6 and in a part of my code I was using Object.keys() or for-in loop for getting name methods; the code will not work.

**Comment by MadaraUchiha** [comment] 2018-03-06 20:13
As mentioned in #22354, also applies to static methods.

**Comment by RyanCavanaugh** [comment] 2021-12-15 23:41
The impact of this is pretty small in practice and ES5 runtimes are getting pretty rare. We don't intend to address this given the other churn it would necessitate.

**Closed by RyanCavanaugh** 2021-12-15 23:41 UTC
Labels: Bug, Won't Fix, ES6
