### ISSUE TITLE
Instantiated namespace preceding ambient derived class ruins assignability 

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4485] opened 2015-08-27 00:30 UTC
```TypeScript
declare class Base {
    public blah;
}

namespace Derived {
    var x;
}

declare class Derived extends Base {
}

var b: Base = new Derived
```

Error:

```
foo.ts(12,5): error TS2322: Type 'Derived' is not assignable to type 'Base'.
  Property 'blah' is missing in type 'Derived'.
```

If you remove the `var x` from the namespace, or move the namespace last, everything works.

**Comment by ahejlsberg** [comment] 2015-08-27 16:28
This appears to be caused by an assumption that the `valueDeclaration` property of a symbol with `SymbolFlags.Class` references the class declaration. It basically always does, *except* in the rare case where a class is merged with a namespace declaration that precedes the class declaration.

I'm looking at the best way to fix it right now.

**Comment by sandersn** [comment] 2015-10-08 17:45
Note: You need to have a public member in `Base` for this to repro.

**Closed** 2015-11-13 16:50 UTC
Labels: Bug
