### ISSUE TITLE
navtree Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#41769] opened 2020-12-02 00:24 UTC
**TypeScript Version:**  4.2.0-dev.20201201

**Search Terms:**
- tsserver
- navtree

**Code**
For the file:
```ts
class Foo {}

const  = Foo;
```

Run a `navtree` command (you can trigger this in VS Code using the `go to symbol in editor` command)

**Bug:**
Exception:

```
[Trace  - 00:21:04.76] <syntax> Response received: navtree (23). Request took 34 ms. Success: false . Message: Error processing request. Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at getNodeSpan (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:125898:29)
    at getSpans (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:125866:26)
    at convertToTree (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:125836:24)
    at Object.map (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:449:29)
    at convertToTree (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:125838:32)
    at Object.map (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:449:29)
    at convertToTree (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:125838:32)
    at Object.map (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:449:29)
    at convertToTree (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:125838:32)
    at Object.map (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:449:29)
    at convertToTree (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:125838:32)
    at Object.map (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:449:29)
...
``` 

The example code is invalid but you can get into this state while editing a file (I was rename the variable when I hit this)

Potentially same issue as https://github.com/microsoft/TypeScript/issues/41534

**Comment by armanio123** [comment] 2020-12-02 02:28
This issue is a duplicate of #41534 as mentioned. It has been fixed already.

**Closed by armanio123** 2020-12-02 02:28 UTC
Labels: Bug, Duplicate
