### ISSUE TITLE
type false is not working in if condition unreachble code check

### ISSUE THREAD

**Issue by deepkolos** [microsoft/TypeScript#54705] opened 2023-06-19 13:15 UTC
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5IBQ8AdpgC6gCGAXKAGbUA2mKAvIy2wNxFEBLBqAAUTVkgCUoAN5FQC2HHJxmSAHTM4qEQHIArqULUYOJcl2S+AX35DR1aXMVKVazdr2Hjp80ks2QA)

### 💻 Code

```ts
const a: false = false;

if (false) {
    console.log('unreach code'); // unreach code error
}

if (a) {
    console.log('unreach code'); // no unreach code error
}
```

### 🙁 Actual behavior

if block not opacity darken

### 🙂 Expected behavior

just like 

```ts
if (false) {}
```

**Comment by MartinJohns** [comment] 2023-06-19 13:25
Duplicate of #39995.

**Closed** 2023-06-19 13:29 UTC
