### ISSUE TITLE
Suggestion: Member Type Guard

### ISSUE THREAD

**Issue by hillin** [Microsoft/TypeScript#14924] opened 2017-03-30 03:54 UTC
I would like to propose a new kind of type guard, which I call it a **Member Type Guard**: a property's type is guaranteed by another `boolean` property of its owner instance, or a `boolean`-returning method or function. This could be very helpful for situations one wants to consume a composite result, often a `boolean` or `enum` value indicating a state, and another value which might be `null`/`undefined` or not, depending on the state value.

Please allow me to put an example first so this idea could be well explained. The following code is from [lib.es6.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts):

```typescript
interface IteratorResult<T> {
    done: boolean;
    value: T;
}
```
An object implementing this interface will be returned by `Iterator<T>.next()`. If this iteration is done, the property `done` will be set to `true` and `value` will be left to `undefined`; otherwise `done` will be `false` and `value` will be the value produced by the iteration step.

However, with the `--strictNullChecks` compiler flag turned on, it is preferably to write like this:
```typescript
interface IteratorResult<T> {
    done: boolean;
    value: T | undefined;
}
```

A common pattern to consume this result:
```typescript
const result = iterator.next();
if(!result.done) {
    doSomethingWith(result.value!);  // a '!' is employed to enforce the un-null-ness of result.value
}
```

Since `!done` implies `value` is not `undefined` (in another word, `done` implies `value` is `undefined`), it would be great if the compiler understands this too. So we can define `IteratorResult<T>` like this:
```typescript
interface IteratorResult<T> {
    done: this.value is undefined;
    value: T | undefined;
}
```
therefore, `done` has become a type guard of `value`, in a `if(!result.done) {` block, `result.value` is thus inferred as of type `T`.

This kind of type guard could also be used in getters and methods:
```typescript
enum ResponseResult {
    Successful,
    FailedSilently,
    FailedWithError
}

class Response {
    result: ResponseResult;
    value: string | undefined;
    get isSuccessful() : this.value is string {
        return this.result === ResponseResult .Successful;
    }
}

function hasError(response:Response) : response.value is undefined {
    return response.result !== ResponseResult.Successful;
}

const response = getResponse(); // some function that returns a Response
if(response.isSuccessful) {
    // response.value is string rather than undefined here
}

/* or */ 

if(hasError(response)) {
    // response.value is undefined here
}
```

**Comment by vkurchatkin** [comment] 2017-03-30 12:29
This is already possible using union. Flow implements IteratorResult like [this](https://github.com/facebook/flow/blob/master/lib/core.js#L529-L531)

**Comment by hillin** [comment] 2017-03-31 02:23
@vkurchatkin thanks for inspiring me with the union approach.
So I've rewritten the last example in the main post, is this the best I can get? Because I feel it quite verbose.

```typescript
enum ResponseResult {
    Successful,
    FailedSilently,
    FailedWithError
}

type ResponseSuccessfulType = { result: ResponseResult.Successful, value: string };
type ResponseFailedType = 
{ 
    result: ResponseResult.FailedSilently | ResponseResult.FailedWithError, 
    value: undefined 
};
type ResponseType = ResponseSuccessfulType | ResponseFailedType;

function hasError(response:ResponseType) : response is ResponseFailedType {
    return response.result !== ResponseResult.Successful;
}

const response = getResponse(); // some function that returns an object of ResponseType
if(hasError(response)) {
    // response.value is undefined here
}
```

**Comment by mhegazy** [comment] 2017-05-12 00:26
i do agree that the union approach is better here. IterationReslult should be defined as:

```ts
IteratorResult<T> =  { done: true;  value: undefined; } | { done: false;  value: T; }; 
```

As for the OP, i think this is a duplicate of https://github.com/Microsoft/TypeScript/issues/7150

**Closed** 2017-05-17 19:35 UTC
Labels: Duplicate
