### ISSUE TITLE
Can't use type `this` in a static getter, but I can if its a method.. with a generic. But getters don't support generics. 

### ISSUE THREAD

**Issue by miguel-leon** [microsoft/TypeScript#54322] opened 2023-05-19 02:25 UTC
# Bug Report

In the following code
```ts
class Base {
	static get Class()/*: this*/ {
		return this;
	}
}
class A extends Base {}
class B extends Base {}

const x = A.Class; // typeof Base 👎 Should be typeof A
const y = B.Class; // typeof Base 👎 Should be typeof B
```
The type of `this` is not inferred correctly as it would do if it were an instance method.
But it works as expected if the static getter is changed to a method with generics workaround trickery.
```ts
class Base {
	static Class<T>(this: T) {
		return this;
	}
}
class A extends Base {}
class B extends Base {}

const x = A.Class(); // typeof A 🎉
const y = B.Class(); // typeof B 🎉
```
But then I'm forced to use a method call instead of a property access. I want a property 😥

### 🔎 Search Terms

static getter this type
There is a similar issue but it doesn't take into account statics.
https://github.com/microsoft/TypeScript/issues/35986

### ⏯ Playground Link

[Playground link A](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBCkFNoG8BQBICAXMWCWw0A5gltAMLhQAUAlAPQBUAXNFgBZ4SP0oboAnUgFcBAOzacIAbgwBfVAtCQYAQWgIAHlgRiAJjHgQkyJVUMbtug3EQoFqYAHsx2aJugBeaKoB0lFWloel4sAE8ABwQnADNbY2hqAGV2J2EQPWgAIyRwqNifWkcXNzCvOH9zIJC2SOi4oyRk1PTMnNr8hqKgA)
[Playground link B](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBCkFNoG8BQBICAXMWCWw0AwuFADwAqAfABRYAWeEAXNBQJQoboBOCWAVx4A7aAyYBuDAF9Us0JBgBBaAgAeWBMIAmMeBCTJ5pPao1bdcRClmpgAe2HZoa6AF5oSgHQlFNdhLQAPRBYgCeAA4I9gBmntCAPBuAkft2js5h7nA+Jv6BIeFRsXCJKUA)

### 💻 Code

In the description

### 🙁 Actual behavior

In the description

### 🙂 Expected behavior

In the description

**Comment by jcalz** [comment] 2023-05-19 02:36
Duplicate of #5863

**Closed** 2023-05-22 11:16 UTC
Labels: Duplicate
