### ISSUE TITLE
VS Code/language server doesn't properly detect `NodeNext` module kind based on `package.json`

### ISSUE THREAD

**Issue by shroudedcode** [microsoft/TypeScript#47806] opened 2022-02-08 17:29 UTC
# Bug Report

### 🔎 Search Terms

- `typescript nodenext errors only reported by tsc`
- `typescript nodenext errors not reported by vs code`

### 🕗 Version & Regression Information

I noticed this in `4.6.0-dev.20220208` and didn't try earlier versions because the `NodeNext` module kind hasn't been included in a stable release yet.

### ⏯ Playground Link

_Can't be reproduced in the Playground._

### 💻 Code

Reproducing the bug doesn't require specific code, but rather a specific TypeScript and VS Code setup, so I created a reproduction repo. Here's what's necessary to reproduce the issue:

- Clone [the repo](https://github.com/shroudedcode/ts-nodenext-issue-repro)
- Install the dependencies
- Open the project in VS Code
- Make VS Code use the workspace TypeScript version (`4.6.0-dev.20220208`)
- Compile the code with `yarn tsc` or `npx tsc`
- Open the `src/index.ts` file in VS Code

### 🙁 Actual behavior

`tsc` tells us about the ESM-specific `Relative import paths need explicit file extensions...` error in `src/index.ts` while VS Code doesn't. This is likely because `tsc` [correctly detects the file's module kind to be `NodeNext` based on the `package.json`](https://www.typescriptlang.org/tsconfig#node12nodenext-nightly-builds) while the language server doesn't for some reason.

### 🙂 Expected behavior

Both `tsc` and VS Code report the error because they both realize that the file is a `NodeNext` module.

**Comment by weswigham** [comment] 2022-02-09 19:19
Thanks for the succinct test case - I've added it to #47732, which contains the fix to the services resolution cache. (Technically this is probably a dupe of #47795, but this test case is much more contained!)

**Closed** 2022-02-15 21:53 UTC
Labels: Bug, Fix Available
