### ISSUE TITLE
Exported class with ES decorator throws ReferenceError

### ISSUE THREAD

**Issue by Seungwoo-Yu** [microsoft/TypeScript#54483] opened 2023-06-01 09:00 UTC
# Bug Report

### 🔎 Search Terms

- class
- export
- decorator
- es decorator
- class decorator

### 🕗 Version & Regression Information

- This doesn't happen in tsc and playground but in [test code](https://github.com/Seungwoo-Yu/TypeScript-ESDecorator-Issue/blob/main/src/testRunner/unittests/evaluation/esDecorators.ts#L2475) from [Typescript](https://github.com/microsoft/TypeScript), ts-node and ts-jest.
- This happens in main branch and release-5.0.
- I reviewed the FAQ for entries about export.

### ⏯ Playground Link

Due to that this doesn't happen in tsc and playground, there is no available link for playground but [the test code](https://github.com/Seungwoo-Yu/TypeScript-ESDecorator-Issue/blob/main/src/testRunner/unittests/evaluation/esDecorators.ts#L2475).

### 💻 Code

```ts
function TestDecorator() {
    return <T extends { new(...args: any[]): object }>(constructor: T, context: ClassDecoratorContext) => constructor;
}

@TestDecorator()
export class TestClass {
    test() {
        console.log('test function executed');
    }
}

(new TestClass()).test() // ReferenceError: TestClass is not defined
```

### 🙁 Actual behavior

ReferenceError: TestClass is not defined

### 🙂 Expected behavior

test function executed

**Comment by Seungwoo-Yu** [comment] 2023-06-01 09:21
It seems this doesn't happen as of 5.1.1-rc any longer.

**Comment by MartinJohns** [comment] 2023-06-01 09:28
Duplicate of #53332.

**Closed** 2023-06-23 01:33 UTC
Labels: Duplicate
