### ISSUE TITLE
Impossible to use type inference while redefining an inherited class field while reusing the inherited value.

### ISSUE THREAD

**Issue by b6i6o6** [microsoft/TypeScript#42372] opened 2021-01-16 14:19 UTC
# Bug Report

### 🔎 Search Terms

redefine class fields inference implicit any circular this

### 🕗 Version & Regression Information

This is the behavior in every version I tried including nightly and I assume it is a consequence of how Typescript currently handle class fields, which is different from the actual implementation of public class fields in current browser engines.

I assume this bug will disappear when Typescript handle class fields as is without transforming them into assignment on this.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&ts=4.1.3#code/MYGwhgzhAEBCkFNoG8BQ0PQA4CcD2W0AvCtGAFzQAsATNAL4Dcq9qqokMAygK4BGAdQCWAFwAWAYSE5gPcDgAqYoTAQAPEQgB2AExjwISNJmgB6U9CUro4-AHcIlAOS4CT6EIC2WEEOCiQAE9oMUgbQKwkJzAtQPc+BGAwHkMPEWgdPAQYLTx00IA3JDBwyPRMczItXJEwESE8LSqdDxgcBAAzBHatYAQWnWlEkSDoPBwPXSHgEeChJtEYPDsFrVEhMF8AL26AOgAKAHYABhoaAEpyjEqlJG78Cbs8ORaE6GBx9pnJsmgIWt0YBwLU4QgA5lpPNp0hA+logQ0ADTQPg8dKiP4IBCeGBgVEQIRFK5mCxibpID5aAk6brzME2MmlJB4DrQAAG4hUu1cWDZZHS4iQnjwUK06RZDKQEFwCDALQI3Tq41axMqYBmPE2o0FTOg+zs+C0YKC50mXRw7RaHWVbIgPEiOG5+F5yMMSASIGWyPEKWgNXe0lk8l2xJ5xBQxJMu2jnIgToIiMjmD4lCoAA5EyZWKx2OAoNBeIJRGJniIpDI5ECrBBYGjhOJYHgwSleA6FBE7hptHo4IgIyZKgAJcnsnl80IwHUfC3DM33fqlOkotFpVo-Drq9IGxr0sJ2h2qiztc3aPqTxmuER5DtjVkGYoC5QwLB4eYiZF2ZTAMQZLI5PIhGARSjs6fJ1IeZAgCAuwFlikrvI0EB4CACC7J69KllgK4essIYmGGJDGCYmDRrs+57DymbERgKbUBmxLZmwBRAiiTa+iQWgIHYBb8PWJZouWQZVk+tYiHxjbNhArbdO2kT7OczCUkhKFoU2+x8GxcY8rsYAKSSYxolhIiUDwuidPMC7zP8sryqytC7EAA)

### 💻 Code

```ts
class Base {
    prop = { a: 42 };
}

class SubWithCircularThis extends Base {
    // This throws: 'prop' implicitly has type 'any' because it does not have a type
    // annotation and is referenced directly or indirectly in its own initializer.(7022)
    // The error would be correct in a standard assignment scenario, but it seems abusive
    // here considering the type of `this.prop` at the moment of the spread operator is
    // actually the type (wrongly) inferred for `super.prop`, see below, thus not circular.
    prop = {
        ...this.prop,
        b: 48,
    }
}

class SubWithoutCircularThisButWithBogusSuperType extends Base {
    // Here `prop` has the correct inferred typing but it is in fact wrong as super
    // references the prototype of Base at this point, which does not have `prop` at
    // all. See the console.log output below.
    prop = {
        ...super.prop,
        b: 48,
    }
}

var bogus = new SubWithoutCircularThisButWithBogusSuperType();
console.log(bogus.prop.a); // output: undefined instead of 42.
```

### 🙁 Actual behavior

It is not possible to use type inference when redefining a class field in a sub class using the same name as the super class and reuse the value of the super class field without explicitely typing the proeprty.

It throws: 'prop' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.(7022).

The error would be correct in a standard assignment scenario, but it seems abusive in class fields considering the type of `this.prop` at the moment of the spread operator is actually the type (wrongly) inferred for `super.prop`, thus not circular.

However, the type of `super.prop`, while being the one I would have expected to get for `this.prop` in the context of class fields definition, is wrong for `super` in itself as `super` is the prototype of the Base class, not the instance itself.

So there are two bugs here but they are somewhat linked together because `this.prop` in the context of class field definition should be the type of `super.prop` and `super.prop` should not exist per se.

### 🙂 Expected behavior

`this.prop` in the context of class field definition should be the type currently used for `super.prop` and `super.prop` should not exist per se as this would more correctly match the behavior of public class fields.

As I mentionned earlier, I assume this would change when Typescript outputs actual public class fields, which is not the case for now, but the behavior seems wrong anyway. Especially the typing of `super.prop`. Anyway, the compiler should be able to distinguish between the "normal" context, where `this.prop` indeed means `this.prop` and the typing would indeed be circular, and the class field context, where `this.prop` means the prop previously defined in the super class, thus no circularity.

For anyone who would be facing the same issue as I was and who really wants to use type inference rather than manually type the property, I have found a rather hacky workaround to make `super.prop` return the value of `this.prop`:

[Playground link with hacky workaround](https://www.typescriptlang.org/play?target=99&ts=4.1.3#code/MYGwhgzhAEBCkFNoG8BQ0PQgFzNglsNMAK4BOZCAdtgFxyIDc6mAZvmTgDL5UIDyrAMIB7KjjIlg2EWWgBeaAAp4EBADpSFatgXRsAC3wQAlM0zQADmRGW9yaGHoAWAEzQAvsw+pUoSDAAyiQARgDq+IZCHKTgZAAqRjAIAB7Y1AAmMKpIaBYA9PnQicb6BjYA7hD0AOTWtjXQ+AC2liCEkSAAntAGkPpdlkg1YFRdjSEIwGAkak26GSIIMFQiun0AbkhgA0MsGIWOVKu4BGJHGU0wlKwIlFTACJcZHFPY3dCyTVQvlNIfvHmMBEFSo30i+DA7QAXnd1EoAOwABlcrhM+2gh0SSDuNjkFREJBAl0mxFkf10gJ2OFGGTAZEuAXwAHMqM0dFhHlR6fgRAAaaAhEiU3RqBDNGBgIUQfBbDGHAx3JDAMQyjJ3XjMspIbCDJAiVjQAAGhmM6nqliNjl0hiQzRE7Jon0Ntqw1gQYEutjueC+xnlRTA0hIUI+rt1Q2UFRsVGZ3RM31u2kurC+RogJCGZHNNktArFgoQIBBAsMs2gJ2IMSJ9PUGIt9gxFnULdNEBztj5TcwIRcAA4uxYfD4-OAoNBguFIgZCdhomRYvSShBYMKIoZYCJmbNgln4nroKl0j9sogUAHoAAJJXGi1WvowV0q7TSRO4p67TWC4XzK7faCsEGujRmIWr9BmWYXjcSoPMs2pWDYMgRvqho5NaZSlJYIi8NgAoVEYwAGNAixwZWmxIEad7WheobqBOCA6oqZLiCIIAaMWWqzpYP6TMWFR1hYDaKHkFiYC26gQXCFqDqJGC9tAzgDhiw6+Bs9KClu5aKHwFQTqE64zsK86LgkSSrtgBmbtuEC7nc+5DEoZh+KqrHsVuSghJp7YWuoYBmJiRRccK9AkD8CDsHwly8DgHpeoabh1qgWKKnMQaPFAsiSpQ0AEmQADW9KEieAFfNgBJYDOZDYCqzSajAgL2cswBkPgljYHW-AhAAVm86jqhFCAAAq5ncuoqIgHZIXqAp1LmNQCiJBxFMuf47LlBU2KFKZ+lAJBIG4ADMCKuAJmCHIEDH0AY2DYJY1SFMy06hJoDr5LVzUiBABrYPkjWBM1rU-cYGbLPkh3HRizIINgjnnrJS3FEk0DNGAeVwemmZSbmVqUNg5BgiaSQdpa+giI4GzYZcwDVnEuxILwSbUI8p2ybj+MMGomjkPc7UWuYmAeDJGBqNgAA88QAHxKBa9DxAmi2iYcACCwKGlsnC8mCzjqAAjOoB0Co1EAA21xFLCsayfMK3G6NxITtEQ-jjuwRZZN2COAgAUoEjiPoqPT0jqZCjBAqZkOyUU0GTQEhiAvsyqyjqUuI6SenRy7uwFWDQ+kcjYMH4hh808FMonHIhEGeWk8jeCEV+rqTJsvJyAameHHbDvEGOMAu8SECln0lIwNMIDtLGxqdT10h9eFvBDSNVUBzAIsELGbdFK6FqjT0vxvB8BJElTXSgEgkxlQxYJQzddySj82fX5w-5tsQE2Z5PvX9XPw3eov42c1oPMZoWnmnDeGFgVRUHYNuYO9sED0HzntIWYDDxUBIOyGBbF4GSAQEgsB0ZIhSkwfobBuD4ZqRAHteg0lM4eHREOVAtDVLqROFZWYSsxj2mytpBAulJwGVnMZGspljDmUsl5WyCQ9SOWYBAr6bF1AcSUCwry7CuicI0D5PyjAs5BToApVwAougeiIgAQiAA)

Please do not fix the type of `super.prop` without fixing the circular type inference of `this.prop` in the context of class fields, as this would break the workaround. Ideally, these two bugs should be fixed together.

I don't expect this to be fixed before Typescript actually starts outputing javascript code with public class fields but I thought you would like to know nonetheless.

**Comment by jcalz** [comment] 2021-01-16 15:55
Related to #10570

**Comment by MartinJohns** [comment] 2021-01-16 16:15
Looks like a duplicate of #33899.

**Comment by b6i6o6** [comment] 2021-01-16 16:33
Respectfully, I do not think this issue is a duplicate of those two. The first one does not seem to reuse the previous *value* of the property, thus only encompassing the "redefinition" part of this issue, while the second one uses `Object.assign` which does not "merge" the types (result of `Object.assign(A, B)` is `A & B`) like the spread operator does.

I am not *that* much into Typescript so I might be wrong and my issue might indeed be a duplicate of those but I don't think any of them include the typing issue of `super.prop`. This is quite confusing in my opinion because you can only spot the error at runtime when the object is not initialized with the correct value since `super.prop` is actually undefined in reality.

**Comment by whzx5byb** [comment] 2021-01-16 17:12
The issue of `super.prop` is a [bug](https://github.com/microsoft/TypeScript/issues/42214).

**Comment by MartinJohns** [comment] 2021-01-16 17:55
> Respectfully, I do not think this issue is a duplicate of those two. [...] while the second one uses Object.assign which does not "merge" the types (result of `Object.assign(A, B)` is `A & B`) like the spread operator does.

The behavior is the same when you use object spread: [Playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAKYCdoG8CwAoa0D2AjAVtALwoZZZgBc0A5AA6LR0LZ0CmCALgJ41nQBfDP05sAtnQDyBYqUzkqtURKaNmrDjz7yh6XRlCQYAZQCuuaGwAeogHYATGPCRp5AejfQAlreDYECGzAnNA87Px4hCSu5NC41DQQ5kws7Fy8ADT8WAB0eQAUnAAWXhA5kdCQcIgA2gBEkXUAugCU-PryAPrKUgTUYLbcssWlOT3S+MLunn4BQSFhbCLivVFysfFKK9BJFuppWlnyuQUjZd0rE5VOtXXjBM1tOhgdfrYQ2CBsOSDYAOb5WxsADu0DMuHyLRa0CAA)

But in the end it's in the discretion of the TypeScript team, of course.

> EDIT: Woops, sorry jcalz I did not realize you said "related to" and not "duplicate". Indeed the two issues are definitely related.

jcalz said related, I said duplicate. :-)

**Comment by RyanCavanaugh** [comment] 2021-01-20 18:49
I don't think there's anything here not covered by the existing linked issues.

**Closed** 2021-01-23 18:00 UTC
Labels: Duplicate
