### ISSUE TITLE
Quickfix to add missing attributes/properties

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#45163] opened 2021-07-23 08:53 UTC
# Suggestion

## 🔍 Search Terms

quickfix, properties, jsx, literal

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

We have:

```
{} is missing the following properties from type {} and {} more.
```

It's helpful to add all missing attributes/properties by quickfix. the default value could be null/undefined/zero-value/etc.

## 📃 Motivating Example

```ts
interface Foo {
  a: string
  b: number
}

const f: Foo = {}
--------------------------------
         ^ missing a, b
-------------------------------

```

To:

```ts

interface Foo {
  a: string
  b: number
}

const f: Foo = {
 a: undefined,
 b: undefined
}

```

**Comment by a-tarasyuk** [comment] 2021-07-23 09:41
It seems duplicate of https://github.com/microsoft/TypeScript/issues/28491 (https://github.com/microsoft/TypeScript/pull/44576), partially https://github.com/microsoft/TypeScript/issues/16755 (https://github.com/microsoft/TypeScript/pull/44781). The first PR was merged, however, I'm not sure if it was included in [typescript-4-4-beta](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-beta/). I think @DanielRosenwasser can clarify that ;).

**Comment by Kingwl** [comment] 2021-07-23 10:07
Looks cool! Don't forget jsx attributes too.

**Closed** 2021-07-26 18:00 UTC
Labels: Duplicate
