### ISSUE TITLE
api: compilerhost async fs

### ISSUE THREAD

**Issue by atanasster** [microsoft/TypeScript#47570] opened 2022-01-23 22:46 UTC
Hi, would you consider adding ability to create compiler host using async filesystem functions(or any other solution to the problem at hand). Possible support for either sync/async 

Use case is using the typescript api in a VSCode for the web extension, where the VSCode workspace.fs functions to acess the file system are all async: https://code.visualstudio.com/api/references/vscode-api#FileSystem
Tia

**Comment by RyanCavanaugh** [comment] 2022-01-24 17:03
The problem is that the checker, which is by far our performance bottleneck, can (in rare cases) need to read a file when resolving the type of an object. Because async is infectious, this would make the entire typecheck phase a very long and slow sequence of async calls -- I can't even speculate how slow this would be.

**Comment by atanasster** [comment] 2022-01-24 17:57
Thanks @RyanCavanaugh , i fully understand. However i do not see any workaround at this time to support VSCode for the web. Do you have any clues in which direction i should look? The VSCode team also seem pretty set on not providing blocking sync versions of their workspace.fs routines, as some remote file systems do need to be async.

**Comment by RyanCavanaugh** [comment] 2022-01-24 18:46
The general idea is the (somehow) know ahead of time which files will be needed and preload them so they can be synchronously returned. For any other files, you can record when they're probed, fetch them if they exist, then fire the file watcher so TS recomputes the program. This is how e.g. the TypeScript Playground works.

**Comment by atanasster** [comment] 2022-01-24 22:21
Thanks for the suggestion. I dont it works for my use case - running the checker on the selected file (i can pre-load this first file selected in VSCode), but then loading all required dependencies. Recomputing one by one on each file request also doesnt seem workable.

Can you point me to the code for ts playground - it seems a different use-case as it knows the files upfront and loads them in its virtual fs, but maybe i am missing something.

**Comment by RyanCavanaugh** [comment] 2022-01-25 18:26
https://github.com/microsoft/TypeScript-Website/tree/v2/packages/playground

**Closed** 2022-01-28 00:00 UTC
Labels: Question
