### ISSUE TITLE
Generics are inferred wrong in a union

### ISSUE THREAD

**Issue by awerlogus** [microsoft/TypeScript#56278] opened 2023-10-31 17:55 UTC
### 🔎 Search Terms

generic union inference 

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20231031#code/CYUwxgNghgTiAEYD2A7AzgF3lAXPAPAKIA08AKgHwAUIAlhgBYgx4DaAZlBGiKYQLrwAPvFYYYAV17l+ASngBeCvABuSWsACwAKB2hIsBMnRYARm07dpmGLRQBzQSLGTpKCQFtTzfjp1QqU1kdIA

### 💻 Code

```ts
declare const a: <E, T>(either: [false, E] | [true, T]) => void

declare const b: [false, string] | [true, number]

// now:      const a: <string, string>(either: [false, string] | [true, string]) => void
// expected: const a: <string, number>(either: [false, string] | [true, number]) => void
a(b)
```

### 🙁 Actual behavior

Both parameters: `E` and `T` are inferred as strings

### 🙂 Expected behavior

Parameter `E` is inferred as a string, parameter `T` is inferred as a number

**Comment by jcalz** [comment] 2023-10-31 18:30
Possibly related to #45809?

**Comment by RyanCavanaugh** [comment] 2023-10-31 21:06
Agree this is duplicate of #45809; tuple and object type discriminants work the same way

**Closed** 2023-10-31 23:07 UTC
Labels: Duplicate
