### ISSUE TITLE
Support for Mix-in classes: can not export mixing function from a module

### ISSUE THREAD

**Issue by BBGONE** [Microsoft/TypeScript#15313] opened 2017-04-22 04:36 UTC
**TypeScript Version:**  2.2

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
export interface ITagged {
    _tag: string;
}

export type TAnyConstructor<T> = new (...args: any[]) => T;

export function MixedTagged<T extends TAnyConstructor<{}>>(Base: T) {
    return class extends Base implements ITagged {
        _tag: string;
        constructor(...args: any[]) {
            super(...args);
            this._tag = "";
        }
    }
}
```

**Expected behavior:**
Should be no error. The function returns a class which implements interface. It should be treated by compiler as original Base class which supports ITagged interface. Otherwise this mixing is useless.

**Actual behavior:**
Error		Build:Return type of exported function has or is using private name '(Anonymous class)'

**Comment by ahejlsberg** [comment] 2017-04-23 15:05
Duplicate of #15066.

**Comment by mhegazy** [comment] 2017-05-08 19:23
This issue seems to have been already addressed or is unactionable at the moment. I am auto-closing it for now.

**Closed by mhegazy** 2017-05-08 19:23 UTC
Labels: Duplicate

**Comment by BBGONE** [comment] 2017-11-19 12:26
Thanks very much. I used it with typescript version 2.6.1. It works like a charm. Even allows to extend later the mixed classes.
That's how i used it in my project:
https://github.com/BBGONE/JRIApp/blob/master2/FRAMEWORK/CLIENT/shared/jriapp_shared/object.ts

**Comment by BBGONE** [comment] 2017-11-23 09:22
Yes, it works, but the problem that i need to have a constructor. This mixing works only on classes. EcmaScript6 now has a Proxy object, which can be used to add properties, methods to a given object, thus adding members to the interface. I can not use this mixing function in this case. Types union does not work either, because T | U type is not the same as T extends U.

**Comment by BBGONE** [comment] 2017-12-21 10:09
I've found that typescript has intersection types Type1 & Type2. I did not noticed it before. It is perfect for mixing.
