### ISSUE TITLE
can we point at the first bad argument (or lack of thereof) instead of saying: Supplied parameters do not match any signature of call target.

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#11688] opened 2016-10-17 21:09 UTC
i am spending lots of my time solving puzzles all day, one of may favorite one is: 
```
Supplied parameters do not match any signature of call target.
```

can i haz hints plezzzz?

**Comment by mhegazy** [comment] 2016-10-17 21:15
Duplicate of https://github.com/Microsoft/TypeScript/issues/6045

**Closed** 2016-10-18 00:50 UTC
Labels: Duplicate
