### ISSUE TITLE
Add rust like enums 

### ISSUE THREAD

**Issue by Haider-Ali-Dev** [microsoft/TypeScript#50460] opened 2022-08-26 00:30 UTC
# Suggestion
Converting raw data into enums would so useful.

## 🔍 Search Terms
"Rust like enums"

"Rust like enums", "rust enums", "enums"

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

TypeScript should have Rust like enums, right now it has C like enums which aren’t too useful but having rust like enums would be too helpful.

Enums variants can also store data inside them, they can act like tuple.

## 📃 Motivating Example

```typescript
enum Color {
    Red, 
    Green,
    Yellow(string)
};

function convertRawToColor(raw_color: string): Color {
    if (raw_color == "red") {
         return Color.Red
    } 
    // More checks 
}
```

## 💻 Use Cases
- Converting raw data into enums would so useful.
- Function can act differently using enum instructions.
- More robust and clean code.
- Wrapper around a data structure

**Comment by DanielRosenwasser** [comment] 2022-08-26 00:33
Duplicate of #36336.

**Closed** 2022-08-28 18:00 UTC
Labels: Duplicate
