### ISSUE TITLE
Unable to use imported symbol as class property when exported inside an object

### ISSUE THREAD

**Issue by kyeotic** [microsoft/TypeScript#42830] opened 2021-02-17 00:16 UTC
# Bug Report

imported symbols cannot be used as class properties. Symbols declared in the same file can.

### 🔎 Search Terms

* `Element implicitly has an 'any' type because type  has no index signature`
* `typescript symbol element no index signature`

### ⏯ Playground Link
This playground example cannot recreate the bug because it depends in _importing_ the symbol
[Playground link with similar but slightly different code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBA+gWwKYIEZIE4wLwwBQDKAnmiADZ4DkUS0lAlPTAIYQwQmrkBQ3SAHgAcQGWMDKs2AYWbAAFkhgBvbjDUxBAV1RkAlsBgBtRCnQYAugC52UDLrABzQ+dXrQkW5uBQReZGkxraDtHZyYVdUiYKDldCGN-M3McGETMVzUAX25MoA)

### 💻 Code

```ts
import {storeSymbols}  from './somewhere'

const _logger: symbol = storeSymbols._logger
const _dynamo: symbol = storeSymbols._dynamo

export class Cache {
  public [_dynamo]: ArcClient
  public [_logger]: Logger
  private metrics: CacheMetrics

  constructor({ dynamo, logger, metrics }: CacheConfig) {
    this[_logger] = wrapper(logger) // <--- errors
    this[_dynamo] = dynamo          // <--- errors
    this.metrics = metricsWrapper(metrics, this[_logger])
  }
}
```

### 🙁 Actual behavior

TS Error
```
Element implicitly has an 'any' type because type 'Cache' has no index signature. Did you mean to call 'set'?
````

### 🙂 Expected behavior

No errors

Here is the local error
 
![image](https://user-images.githubusercontent.com/1187432/108137469-c513f680-7070-11eb-869f-fd6996dba722.png)

Here is a screenshot with the error, next to the same code in the file that declared the symbol, where no error presents

![image](https://user-images.githubusercontent.com/1187432/108138009-ede8bb80-7071-11eb-9f99-61399668c19f.png)

**Comment by IllusionMH** [comment] 2021-02-17 16:12
Not sure about exports, but if you want to use symbol as key you need to use `unique symbol` . [Example](https://www.typescriptlang.org/play?#code/MYewdgzgLgBA+gWwKYIEZIE4C4YFcwCWAjrkjBAJ5ogA2MAvDAMpWq0AUA5FEtJwJQBuAFDCkADwAOIDLGA0AhhAgwAwguAALMgG9hMAzEm5UNAsBgBtRCnQYAujmgYCYAOaX7+w6EhQMuMBQMuzIaJhO-q4e9vwweoaJMFCaBBDWYXb2DDCZmN4GAL7ChUA)

**Comment by kyeotic** [comment] 2021-02-17 16:24
Interesting. Why does it work when the symbol is created in the same file then? The type `unique symbol` is new to me, and doesn't appear in the signature for the `Symbol()` function.

What is the difference between a `symbol` (which [mdn says is guaranteed to be unique](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol)) and a `unique symbol`? When is a `symbol` not a `unique symbol`?

**Comment by kyeotic** [comment] 2021-02-17 16:36
Ok, this is definitely a bug. I found [these docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#constant-named-properties) that describe doing exactly what I am doing:

```ts
// Lib
export const SERIALIZE = Symbol("serialize-method-key");

export interface Serializable {
  [SERIALIZE](obj: {}): string;
}
// consumer

import { SERIALIZE, Serializable } from "lib";

class JSONSerializableItem implements Serializable {
  [SERIALIZE](obj: {}) {
    return JSON.stringify(obj);
  }
}
```

The `consumer` is importing a symbol and using it as a class property. That code should be producing this error.

I even tried pulling these properties out into a shared interface, in case that somehow impacts the "uniqueness" requirement here. Paradoxically it now complains about both:

```
// error 1, at class declaration
Class 'Cache' incorrectly implements interface 'DynamoStore'.
  Property '[_dynamo]' is missing in type 'Cache' but required in type 'DynamoStore'.ts(2420)
dynamo.ts(117, 3): '[_dynamo]' is declared here.

// error 2, at constructor property assignment
Element implicitly has an 'any' type because type 'Cache' has no index signature. Did you mean to call 'set'?
```

**Comment by kyeotic** [comment] 2021-02-17 16:59
Nevermind, this is a duplicate of an apparently [longstanding lack of support for symbol indexers](https://github.com/microsoft/TypeScript/issues/1863).

Looks like I wont be using typescript for this library after all.

**Comment by IllusionMH** [comment] 2021-02-17 17:01
I don't think that issue is relevant in you case.

Not going into quirks of symbols support you can look at `symbol` vs. `unique symbol` as `string` vs. `'some string'`
any symbol assignable to `symbol`, but only one type is assignable to `unique symbol`. See  https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#unique-symbol

You need to preserve this uniqueness of symbols but as you declare them as just `symbol` 
```ts
const _dynamo: symbol = storeSymbols._dynamo`
```
it means any symbol.


[Same error if you use `string` instead of string literal](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&useDefineForClassFields=true#code/MYewdgzgLgBArmAlgRzgUwMpQE6LAcxgF4YByKNaUgbgCha0APABxG1mABsBDCCGAMJtsaYLADetGNJjM4AI06JgMANoIU6LLgIBdAFwxoO-Kt1SZoSDjhi2ACgC2aR-LTZDxvKd0BKGJIyQTBQABaIEOpIqJg43rrEMM6u7hbSAL60mbRW0DDY3GAAJiCO2t6JALLcYQB0BcWl9r61UCDlBPYAjABsvnQMLGwcPHwwAJJgoNgiYgFpsgpKKqoNJWVxep6bPgu5NnbYTi5uHkY7Zv6BwdJhEauF6x34CSTJpwuZ2UA)

**Comment by kyeotic** [comment] 2021-02-17 17:08
@IllusionMH I tried declaring them as unique symbols and it didn't change the error. That issue seems to be directly relevant: typescript does not support user defined symbols as indexable properties.

If you have a potential solution for this I'm happy to try it out.

**Comment by IllusionMH** [comment] 2021-02-17 17:18
As said before - you need to make sure that they are unique.
Ideally `./somewhere` should already have `storeSymbols` as `{_logger: unique symbol, _dynamo: unique symbol}` otherwise you need to use type assertion `const _logger: unique symbol = storeSymbols._logger as any;`

[Example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZxtApgZQJ4gEYQA2ycAvnAGZQQhwDkAdAPTI3oDuAFulOnQFCCAxhAB2qOAH1CEAOayeALjgBXUcACOK9ClwFCcALwo0vHPiLIG0uQqhwAhiQejsAbn4jx8SQBNsog4gEMpqmtq6FgbGqBjm+lZ+AUEQjs6uHvzoAB6QsHBChE4kAMIOQtyI-HA1cGAqeITAQnAA2kmBwQC6ygCCUEIlTeiiMNW19Y3NbTbyPD1wADK2POM1YFDAAG4OMDog6DCbQsjKZRXoALKHx8iCtQViqFAqQqYAFEj+nRAANHAyOZQf4HI7NEikM7lbglMQUYCyACUVQeDxgnGAyHagLsXSMcHYUAcYDAPHeOJ4yKYTDgAB4ALSMuA8ahQO6o2rozHtb4pPHGXnBDkPal0xn05lQVns4Vcqyg274hXggDqRJJZOVJ3+cuxKygXURazI-FIgn4ot4wS2OhZ0BIwFEzOyQTAhHQ-Bg2FJcH6g2Go3xCFIHi9PuWQKDIc93p05241zBJyjodjcHj6FhonhsnxLncgl86EKDl4j28BPVpKgyneDHrpdkp1UogA1qIIOxRK1DUYAHxLfUeIslsteCRa5Bq4nV2v1hiN5tqdud7u9wwDjOJ25uIA)

**Comment by kyeotic** [comment] 2021-02-17 17:20
I tried that. It doesn't work on the imported symbols. It works in the source file (the way the playground works) either way.

**Comment by IllusionMH** [comment] 2021-02-17 17:46
OK I see - symbols *in objects* are still widened to `symbol` even with `as const` :(

However option with assertion still works.

ATM you have two options:
1) perform assertions as in example
2) export/import/use symbols directly (`Cache2` on screenshot) as shown in docs you posted https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#constant-named-properties

![image](https://user-images.githubusercontent.com/1312662/108244786-409ca300-7158-11eb-95be-5e491e7b140f.png)

**Comment by kyeotic** [comment] 2021-02-17 17:49
Why does providing the `unique symbol` inside of an object cause it to lose its uniqueness? Aren't exports immutable bindings?

**Comment by IllusionMH** [comment] 2021-02-17 17:51
That's actually duplicate of #35562

**Comment by kyeotic** [comment] 2021-02-17 17:52
Yep, nice find.

**Closed** 2021-02-17 17:52 UTC
