### ISSUE TITLE
tsc v3.4RC: Incremental build fails when `--rootDir` passed on CLI

### ISSUE THREAD

**Issue by Coridyn** [microsoft/TypeScript#30457] opened 2019-03-18 05:50 UTC
**TypeScript Version:**  3.4.0-dev.20190316

**Search Terms:** incremental, False expression, both be relative

**Code**

```
//tsconfig.json
{
    "compilerOptions": {
        "incremental": true,
        "outDir": "dist"
    }
}

$ tsc -p tsconfig.json --rootDir src
```

**Expected behavior:**
Project is built successfully.

**Actual behavior:**
Build fails with `Error: Debug Failure. False expression: Paths must either both be absolute or both be relative`.

When a project has this setup:

 * "incremental": true
 * `outDir` has value (doesn't matter if the value is from tsconfig.json or CLI)
 * `--rootDir ...` set from CLI

**NOTE:** Build is successful when `rootDir` value is set in `tsconfig.json` (instead of passed on CLI).

So this will work:

```
//tsconfig.json
{
    "compilerOptions": {
        "incremental": true,
        "outDir": "dist",
        "rootDir": "src"
    }
}

$ tsc -p tsconfig.json
```

**Reproduction Link:** 
Project available here: https://github.com/Coridyn/ts34-incremental-issue

**Related Issues:** N/A

**Comment by sheetalkamat** [comment] 2019-03-18 22:29
The cause of this is that commandLine `rootDir` is not resolved to configFile or commandLine directory where as tsconfig options that are filePath are always resolved in directory path of config file

**Comment by a-tarasyuk** [comment] 2019-03-21 19:48
@sheetalkamat do you mean the following behavior?

```shell
node ../built/local/tsc.js --rootDir src
{ incremental: true,
  outDir: '/TypeScript/30457/dist',
  rootDir: 'src',
  configFilePath: '/TypeScript/30457/tsconfig.json' }
```


```shell
node ../built/local/tsc.js src
{ incremental: true,
  outDir: '/TypeScript/30457/dist',
  rootDir: '/TypeScript/30457/src', <- has absolute path
  configFilePath: '/TypeScript/30457/tsconfig.json' }
```

---
`getRelativePathFromDirectory(options.rootDir, configFileExtensionLess, /*ignoreCase*/ true)` cannot resolve path when `rootDir` passed in _cli_ and is not an absolute or relative path. 

```typescript
const configFileExtensionLess = removeFileExtension(configFile);
buildInfoExtensionLess = options.outDir ?
  options.rootDir ?
     ----> resolvePath(options.outDir, getRelativePathFromDirectory(options.rootDir, configFileExtensionLess, /*ignoreCase*/ true)) :
     combinePaths(options.outDir, getBaseFileName(configFileExtensionLess)) :
  configFileExtensionLess;
```
What do you think, what is the appropriate fix for this problem?

**Comment by nealeu** [comment] 2019-04-10 08:14
Hi,
I've just gone from 3.3.3333 to 3.4.2 and got the same problem via getOutputPathForBuildInfo().  We've got composite: true, so I guess this is what's bringing in the incremental build code path.

**Comment by MikeMitterer** [comment] 2019-04-10 12:04
I had the same problem when move to 3.4.3

Old cmd in package.json (fails with 3.4.3)
```bash
"build:ts": "tsc --rootDir src/main --project tsconfig.lib.json --declaration --outDir lib",
```
New version - works with 3.4.3
```bash
"build:ts": "tsc --rootDir $(pwd)/src/main --project tsconfig.lib.json --declaration --outDir $(pwd)/lib",
```

**Comment by ulrichb** [comment] 2019-07-02 09:35
.. I'm getting the same error ("Error: Debug Failure. False expression: Paths must either both be absolute or both be relative.") in my 3.6 nightly builds in a project where I use `--incremental`.

It started ~ with `3.6.0-dev.20190628`. In previous versions I got no errors; also TS 3.5 works fine.

**Closed** 2019-10-15 15:40 UTC
Labels: Bug, Fix Available
