### ISSUE TITLE
Support Recursive Conditional Types

### ISSUE THREAD

**Issue by Roaders** [microsoft/TypeScript#36142] opened 2020-01-11 08:06 UTC
## Search Terms

recursive conditional

## Suggestion

I want to be able to use recursive conditional types. 

## Use Cases

In this type:

```
type MapParams<T extends any[]> =
    ((...t: T) => any) extends ((first: string, ...tail: infer TRest) => any) ?
    Prepend<First<T>, MapParams<TRest>> :
    Partial<T>;
```
I am making all elements optional except for the ones at the start that are strings. This fails as `MapParams` references itself so I get a `Type alias 'MapParams' circularly references itself.(2456)` error.

## Examples

```
type Prepend<TFirst, TRest extends any[]> =
    ((head: TFirst, ...args: TRest) => any) extends ((...args: infer U) => any)
    ? U
    : TRest;

type First<T extends any[]> = T extends [infer TFirst, ...any[]] ? TFirst : never;

type MapParams<T extends any[]> =
    ((...t: T) => any) extends ((first: string, ...tail: infer TRest) => any) ?
    Prepend<First<T>, Partial<TRest>> : // should be Prepend<First<T>, MapParams<TRest>>
    Partial<T>;

function myFunction(one: string, two: string, three: number, four: boolean) { }
function mappedFunction(...args: MapParams<Parameters<typeof myFunction>>) { }

mappedFunction("") // should NOT work - string at index 1 should be required
mappedFunction("", "") // should work
mappedFunction(undefined) // should not work
mappedFunction() // should not work
```

[Playground](http://www.typescriptlang.org/play/?ssl=20&ssc=36&pln=2&pc=1#code/FAFwngDgpgBACgJytAdgEwDwBUBiBLBAZxABoYsAlKYmKADxCnUJgEMUwBtAXQD4YAvMBgiYACjEALKKzQAucviKkYAOnWsEAc0ILK1EAEpB-dmGP1GzcWPWrNOhXhQAzKAhgBVYwNMdDwqIA-F6BInpUxADcwKCQsErE2LQMTGgsZjz8AuQpVukwnM5uHrgExGR2mdzcMCFlyjAKKFAAbu4xcdAwALKsEHCarAC2hMmWaRkcWYJhNnYgej5+5nmTNi7lizDECM5aleogrHgANk6u7uSRRiZs-nVziMhpGIkg2LxkgwggeKynbA3Xj8BQAejBO0kAHsAK6nNAwABGsGeqEw70+ZD6AyGoyBBhBT00fwBn06LlhKAAxn9oSgYMMwDgqbS8PSxPSoApdvsyCAAO7QnkgPYoA4wECSJDcmAoWHDFEIMguOEIBRI6HQ04yFDGADeMAAvsBKTS6Qzhv1oGgWeb2ShbBptLpev0fiMxh7hlBGEQMOBoNCXIzmayLSCDcbYlaIDa7WyOQAiJPGCFQuEImAAOQA8lgYEKEABrGAAWh2ov2bBAMGcaHoMAAjBn4YiUTAkABHWEEKBoYCx+Phh1iFNkFNpyGEGFtwvQkuD639hMWsRUhubFpoKetrMoaG1ovFpdxlcjjm7meZxEHo8Lk-AIA)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by Roaders** [comment] 2020-01-11 09:52
I can up with this inelegant solution that works but only handles up to 10 params

```
type MapOne<T extends any[]> = ((...t: T) => any) extends ((f: string, ...t: infer TRest) => any) ? Prepend<First<T>, MapTwo<TRest>> : Partial<T>;
type MapTwo<T extends any[]> = ((...t: T) => any) extends ((f: string, ...t: infer TRest) => any) ? Prepend<First<T>, MapThree<TRest>> : Partial<T>;
type MapThree<T extends any[]> = ((...t: T) => any) extends ((f: string, ...t: infer TRest) => any) ? Prepend<First<T>, MapFour<TRest>> : Partial<T>;
type MapFour<T extends any[]> = ((...t: T) => any) extends ((f: string, ...t: infer TRest) => any) ? Prepend<First<T>, MapFive<TRest>> : Partial<T>;
type MapFive<T extends any[]> = ((...t: T) => any) extends ((f: string, ...t: infer TRest) => any) ? Prepend<First<T>, MapSix<TRest>> : Partial<T>;
type MapSix<T extends any[]> = ((...t: T) => any) extends ((f: string, ...t: infer TRest) => any) ? Prepend<First<T>, MapSeven<TRest>> : Partial<T>;
type MapSeven<T extends any[]> = ((...t: T) => any) extends ((f: string, ...t: infer TRest) => any) ? Prepend<First<T>, MapEight<TRest>> : Partial<T>;
type MapEight<T extends any[]> = ((...t: T) => any) extends ((f: string, ...t: infer TRest) => any) ? Prepend<First<T>, MapNine<TRest>> : Partial<T>;
type MapNine<T extends any[]> = ((...t: T) => any) extends ((f: string, ...t: infer TRest) => any) ? Prepend<First<T>, MapTen<TRest>> : Partial<T>;
type MapTen<T extends any[]> = ((...t: T) => any) extends ((f: string, ...t: infer TRest) => any) ? Prepend<First<T>, Partial<TRest>> : Partial<T>;
```

[Playground](http://www.typescriptlang.org/play/?ssl=15&ssc=148&pln=6&pc=1#code/FAFwngDgpgBACgJytAdgEwDwDEA0MBKMUAHiFOgM4wCGKYA2gLoB8MAvDABScTULUBbAFwxcMAHSTqI-AEp2rWmHkkylLp0niAgiICWKAGZQEMAKry2iurID85mDIDcwUJFhY9CCiAwAVIlJyNColJlYOANVgqnoDY1M-T28QPC0wxkYYeySvH0cYFCgANxMXN2gYAFlqCAB5Iv9AtRCaOnD2DS0QET9La2VmmI1DER8EAwBzNMkemHiTGD98KB9+tsH7RGRg7DzfP2Y8Gog-AHcAe38Vn2ZWETg+ED1qABt-ZhdwSpPzq6iguoMhEurNeuslCpAa1uKMYOMpjNxHMFokbiAITZsvAkKhMMkfB9jrU-AALJBQa6rEB3AqPBDPN4fL7uaok8lQSkAlqhdosTrcbrghQbKE8kZjEATFDTCRg+ZGRbLamYzY4nboPYpIlsiBYC4AVwQVNu93gTxe70OLJ+tX1Rqa0SBfJBgvlfRFkKG6lhkulsqFCoSS3RqvkW1xuwJByOus8pRNNLN9MZVs+FVgJ3jXO9rWBAs07rDuaovvhUsRcuR+kVaJVnqxEY1+P2OpOAGU9MRE7SHhamdaM7rO93ucN8xw3dWlsWnTDOHCETKkSjayH61ZRdjtnitYTDsSIO2SuQe8n+2mbZnasfSihHdDeQx+ZPC9OPZuvXPSwu-ZXA6i65rA2ao7lGrYHrqACieiTKSBzor25oMpazJDicMFwQcJYbB0r6Bh+AxisMZZLgG8qAcqwGfo26q7tGba1AAcgYXKIeeKEDum3zXhALGNGOzrPq6b5zIRW7fhK5b+iuNbBlRGIgeGdHgdqkG-KeClISmqGDjxup+JpOETqC76zo+UlkbJQZKqGSnbpGmoMZBOkDuxdIXmhwCGAaKAAMbPBcKAwAIYBYL5AV6EFnBBVAf7LjAICXPFsogBycWFAaAgAEYmHghiGggIjZRcFyvFAtDyAA3jAAC+3kRYFwUCLU0BoOF-lNW+fCTBQIgnA0lL0oIUBkN4GA8RchghWFjVRSgdzVXVrgtRAbUdZF0UAERbfIAD0e3wqShqvGgMBMXUASXAgADWMAALTSVMNAgAqaAkDAACMR0nWduUwEgACOBpeFAaDAKt61zdtW14Dt+2HRQx0GqdMDXTdEOtWDG1db572GKxaAIz9KNnSgFyvejmNrdj0MoJwxNI79hQU2jFy3a4QA)

**Comment by jcalz** [comment] 2020-01-11 20:11
Duplicate of #26980, but **yes, please.**

**Comment by AnyhowStep** [comment] 2020-01-12 02:45
@Roaders 
Sounds like you could use trampolines
https://github.com/microsoft/TypeScript/issues/26980#issuecomment-566214255

**Closed** 2020-01-15 02:17 UTC
Labels: Duplicate
