### ISSUE TITLE
Type updates don't propagate in monorepo across package boundaries

### ISSUE THREAD

**Issue by natew** [microsoft/TypeScript#30946] opened 2019-04-13 09:00 UTC
Steps to Reproduce:

1. In a yarn workspace monorepo, that uses references to build, update a package and it wont update the type definitions anywhere else besides that package.

I was looking for an open issue thinking this would be obvious, but don't see one. It's a huge annoyance working in a mono-repo, it means essentially youre hitting "restart TS server" many times a day.

Apologies if this is already opened.

**Comment by mjbvz** [comment] 2019-04-15 23:04
Can you share a small example project or describe your project structure in more detail

**Comment by natew** [comment] 2019-04-18 18:22
Yea, sorry for lack of detail here. I actually wonder if this isn't something weirdly specific to me, because I imagine a lot of people would have run into it.

I have a monorepo managed by yarn workspaces. All the packages share a parent `tsconfig.base.json` and use typescript, here's a typical config:

tsconfig.base.json:

```
{
  "compilerOptions": {
    "strict": true,
    "incremental": true,
    "declaration": true,
    "declarationMap": true,
    "module": "CommonJS",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2018",
    "noImplicitAny": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strictNullChecks": false,
    "strictFunctionTypes": true,
    "preserveConstEnums": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "jsx": "react",
    "allowJs": false,
    "sourceMap": true,
    "resolveJsonModule": true,
    "lib": ["es2017", "es2018", "dom"]
  },
  "typeAcquisition": {
    "enable": true
  }
}
```

tsconfig.json

```
{
  "extends": "../../tsconfig.base",
  "compilerOptions": {
    "composite": true,
    "outDir": "_",
    "rootDir": "src"
  },
  "include": ["src/**/*"],
  "references": [
    { "path": "../../packages/gloss" },
    { "path": "../../packages/use-store" },
    { "path": "../../packages/fast-compare" },
    { "path": "../../packages/ui" },
    { "path": "../models" },
    { "path": "../stores" },
    { "path": "../bridge" }
  ]
}
```

This is really more of a VSCode issue and I'm realizing I think I used the wrong tab to open this issue, but basically if I make a change to any package, the parents of it won't see the type update in VSCode. But if I go to `Restart TS Server` it will pick up.

[Here's a short video of it](https://v.usetapes.com/s8NwFTknL2).

**Comment by domoritz** [comment] 2019-04-25 02:47
This is a big issue for me as well. I use project references and changing code in one project does not update the types for that first project used in another project. I think this is a TS and VSCode issue so it seems okay to file it here.

**Comment by domoritz** [comment] 2019-04-25 02:49
Is this a duplicate of https://github.com/Microsoft/TypeScript/issues/26913?

**Comment by natew** [comment] 2019-06-05 21:45
Well it happens with or without references, any symlink module that updates won't get picked up until you restart the typescript server.

Given we use a monorepo and have pretty well-split-up packages, I actually hit `cmd+shift+p > restart ts` at least 50 times a day 😓

**Comment by natew** [comment] 2019-06-05 21:47
More information: I do have watch running inside typescript (Build > tsc: watch) from the root. It compiles everything fine, the types *do* change in the output directory. If I restart it picks up the changes properly. But it just doesn't look for updates until you do so.

**Comment by aleclarson** [comment] 2019-06-09 01:01
Related: The `extends` property of `tsconfig.json` is resolved relative to the symlink instead of its real path.

**Comment by aleclarson** [comment] 2019-06-09 02:28
Also related: The `tsconfig.json` of a linked dependency is not used when the `main` field of the dependency is a `*.ts` module.

**Comment by nilkanthjp** [comment] 2019-12-18 20:31
I've been experiencing this as well for a couple months. Thanks to @natew for the tip on restarting TS server, I've just been restarting VSCode entirely 😂

**Comment by chrillewoodz** [comment] 2020-06-10 08:51
Noticing this as well, you can also open the file which contain the updated types and VSC will pick them up. But that is annoying as hell as well.

**Comment by jpike88** [comment] 2020-07-29 04:18
This is a pain in the butt, having this issue as well

**Comment by steve-taylor** [comment] 2021-09-05 06:33
> Also related: The `tsconfig.json` of a linked dependency is not used when the `main` field of the dependency is a `*.ts` module.

Unfortunately, source-level dependencies don't really work in TypeScript. It's a shame, because I'd prefer that package consumers, not package authors, decide which environments (browsers, Node.js versions, or language features) are supported.

So with that in mind, you have to build your packages and point `main` to the _built_ `.js` entrypoint (e.g. `./dist/index.js`) and point `types` to the generated type definitions (e.g. `./dist/index.d.ts`). Similarly, if you're also building your packages as ES modules, you should also point `modules` to the built module entrypoint (e.g. `./dist/index.mjs`).

You end up with something like this in package.json:

```json
"main": "./dist/index.js",
"module": "./dist/index.mjs",
"types": "./dist/index.d.ts",
```

**Comment by alexburkowskypolysign** [comment] 2022-08-03 04:35
Any update on this? Seems to still be an issue

**Comment by DorianMazur** [comment] 2022-10-06 21:58
This is still the issue

**Comment by natew** [comment] 2023-06-07 21:56
@steve-taylor that doesn't fix it, but strangely a few days ago for no reason at all this started working for me, I wonder if VSCode did something?

**Comment by RyanCavanaugh** [comment] 2024-08-06 18:25
I think this has been resolved by some changes in watch strategy. Please open a new issue with complete repro steps if you're seeing this. Thanks!

**Closed by RyanCavanaugh** 2024-08-06 18:25 UTC
Labels: Needs More Info
