### ISSUE TITLE
Wrong comment indent in multiline expressions (TS, JS)

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#5772] opened 2015-11-24 09:52 UTC
_From @alexanderby on November 19, 2015 9:35_

When formatting JavaScript or TypeScript, comments placed between parts of multi-line expressions are placed wrong.
Expected to look like
```javascript
doStuff()
    .then()
    // Comment
    .then();
```
but actually is
```javascript
doStuff()
    .then()
// Comment
    .then();
```

_Copied from original issue: Microsoft/vscode#184_

**Comment by SaschaNaz** [comment] 2015-11-24 15:53
Duplicate of #4563?

**Comment by mhegazy** [comment] 2015-12-02 00:55
indeed. thanks @SaschaNaz!. it should be fixed in latest.

**Closed by mhegazy** 2015-12-02 00:55 UTC
