### ISSUE TITLE
Referencing the typeof mixin class or inside a mixin will compile to any in .d.ts files

### ISSUE THREAD

**Issue by Aylur** [microsoft/TypeScript#56977] opened 2024-01-08 01:29 UTC
### 🔎 Search Terms

mixin .d.ts

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Classes

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.0-dev.20240107&ssl=15&ssc=26&pln=12&pc=1#code/MYGwhgzhAEBCkFMDC4rQN7QL4CgcBcBPABwTkRUgiXwHsAnaAXmgDsEB3aACgDp+w9AOYQAXNDCtCAbQC6ASmYA+chGSoIeBAA9iDfNABmAV1bB8AS1qtoAWQvaLrADwAVaDvwJWAExjw1SigaBiVuAIRxV0V0HGh46HoEfGN6G1AqOwcnD20vX39EDDiE0ohaAFsEADFWbnlxe0cbWNK2hKSUtOh8AAsLTXb43FLcXBxgawgDABEEegsANwQfZizm8IoNeQmpgx95pZW19i45heWfepwDi5Xecqra+ofKmrr5IA

### 💻 Code

```ts
// main.ts
class BaseClass { }

type BaseClassCtor = new (...args: any[]) => BaseClass

export function Mixin<T extends BaseClassCtor>(Base: T) {
    return class Mixin extends Base {
        someFn(): Mixin {
            return this
        }
    }
}
```
the above code will compile to
```ts
// main.d.ts
declare class BaseClass {
}
type BaseClassCtor = new (...args: any[]) => BaseClass;
export declare function Mixin<T extends BaseClassCtor>(Base: T): {
    new (...args: any[]): {
        someFn(): any;
    };
} & T;
export {};
```

### 🙁 Actual behavior

in the `ts` codebase it works as expected
```ts
const Derived = Mixin(BaseClass)
const derived = new Derived()

// someFn() returns Derived
derived.someFn().someFn()
```

but in a `js` codebase using the `.d.ts` types it doesn't
```js
const Derived = Mixin(BaseClass)
const derived = new Derived()

// someFn() returns any
derived.someFn().someFn()
```

### 🙂 Expected behavior

using the type declaration to work correctly

**Comment by MartinJohns** [comment] 2024-01-08 02:47
Sounds like a duplicate of #51206. Used search terms: `mixin any in:title`

**Closed** 2024-01-11 01:29 UTC
Labels: Duplicate
