### ISSUE TITLE
Tuple behave different from documentation

### ISSUE THREAD

**Issue by xuniaoji** [microsoft/TypeScript#31252] opened 2019-05-04 08:23 UTC
**TypeScript Version:**  3.4.2

**Search Terms:** tuple outside

**Code**

```ts
let x: [string, number];
x = ['hello', 333]; // OK
x[2] = 'world'; // will give two errors
```

**Expected behavior:**
as the documentation mentioned: When accessing an element outside the set of known indices, a union type is used instead:

**Actual behavior:**
// Type '"world"' is not assignable to type 'undefined'.ts(2322)
// Tuple type '[string, number]' of length '2' has no element at index '2'.ts(2493)

**Playground Link:** [typescript-error](https://www.typescriptlang.org/play/index.html#src=let%20x%3A%20%5Bstring%2C%20number%5D%3B%0D%0Ax%20%3D%20%5B'hello'%2C%20333%5D%3B%20%2F%2F%20OK%0D%0Ax%5B2%5D%20%3D%20'world'%3B%20%2F%2F%20will%20give%20two%20errors%0D%0A%0D%0A)

**Related Issues:** no

**Comment by cpplearner** [comment] 2019-05-04 13:00
Duplicate of #28894

**Closed** 2019-05-11 18:00 UTC
Labels: Docs, Duplicate
