### ISSUE TITLE
Static properties are transpiled to enumerable properties on the resulting constructor

### ISSUE THREAD

**Issue by MadaraUchiha** [Microsoft/TypeScript#22354] opened 2018-03-06 14:46 UTC
**TypeScript Version:**  2.7.0

**Search Terms:** 
object.keys static
static class enumerable
class static defineProperty

**Code**

```ts
class A {
    static init() {
    	Object.assign(A, {t:2});
    }
    static another() {
        return 5;
    }
}

A.init();
console.log(Object.keys(A));
```

**Expected behavior:**
`["t"]` should be the output (which is what happens when you copy/paste that code into the browser console or to node.

**Actual behavior:**
`["init", "another", "t"]` is the output.

**Playground Link:** [Click me](https://www.typescriptlang.org/play/#src=class%20A%20%7B%0A%20%20%20%20static%20init()%20%7B%0A%20%20%20%20%09Object.assign(A%2C%20%7Bt%3A2%7D)%3B%0A%20%20%20%20%7D%0A%20%20%20%20static%20another()%20%7B%0A%20%20%20%20%20%20%20%20return%205%3B%0A%20%20%20%20%7D%0A%7D%0A%0AA.init()%3B%0Aconsole.log(Object.keys(A))%3B)

**Related Issues:**
- None I could find

**Extra:**
This happens because TypeScript emits static methods and variables as direct assignment on `A` (i.e. `A.init = function() {...}`, instead of the more correct `Object.defineProperty()` with `enumerable: false`.

Babel with the es2015-loose-preset exhibits the same behavior. Without the loose preset, the emitted code is correct there. TypeScript has no such option, though.

**Comment by elektronik2k5** [comment] 2018-03-06 16:56
Seems broken to me. [Link to Babel in strict mode](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYGwhgzhAECC0G8BQ1XQgFzBglsaOAdjhgBQCUiKaAkAPIBGAVgKbAYB0kEOA5oaVgAaRBgBcAJgC-5ANzVUUheiy58YQgHsMACxYAnClTQno-lhgCu-wtACs8k0qVJYHIiQrzgmwhE0gLBwgmrykjKzsHADWLACeEILkckA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=true&presets=es2015%2Ces2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&prettier=false&targets=&version=6.26.0&envVersion=), displaying correct behaviour.

**Comment by mhegazy** [comment] 2018-03-06 19:33
Duplicate of https://github.com/Microsoft/TypeScript/issues/15038

**Closed** 2018-03-06 20:13 UTC
Labels: Duplicate
