### ISSUE TITLE
 throw exception arrow function now working

### ISSUE THREAD

**Issue by cesarve77** [microsoft/TypeScript#52142] opened 2023-01-08 02:36 UTC
# Bug Report

### 🔎 Search Terms

 throw exception arrow function 

### 🕗 Version & Regression Information

4.9.4

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/FAehHUHsCcGsGcBcxgDMCuA7AxgFwJaSYAEAJpAKbwBykuUc8AFAJQDewxXx2R8uxXAAtokAO4BRAB7YKABwJFiAXmKtExTBQBuFaCoB8xDt0EjxmimOIToo6EwDke+45aduAXwDcHrr0x+YlRISA02fFIAfg1+aHxMAHNPFWNIxEcpKUdPP2J8VDUAQhDIADpI9jzTYVFJGXlFTFY83NMAoIAjAENocPTiOITk1IjSDVKK0hSwYiE9Cnz4M0WXGAAaYNCpwaFIdAAbUmIKKXx+POgKXHRoEh7oYFy0LDxCEgYEVhNuDBwmsx1aSyBTvdSWXT6Yx5WoWLTWWz2JxraBuVq+dp8ASlfrRWK4eJJFKqMYZLI5PIFYqTSo-UxcWH1EFNFqmNrcDoCB64-GEkYkgY06aXa63e69J7AIA

### 💻 Code
```
function doesNotWorks(){
    const throwException = (): never => {
    throw new Error('error')
    };
    const foo: {id?: string} = {id:'xx'}
    if (!foo.id){
        throwException()
    }
    const bar: {id: string} = {id: foo.id} // here is the error, foo.id should exist
    return bar
}

function Works(){
    function throwException(): never  {
    throw new Error('error')
    };
    const foo: {id?: string} = {id:'xx'}
    if (!foo.id){
        throwException()
    }
    const bar: {id: string} = {id: foo.id}
    return bar
}
```

### 🙁 Actual behaviour

throw and execption in arrow function foes not works

### 🙂 Expected behaviour

should works the same as named functions

**Comment by IllusionMH** [comment] 2023-01-08 03:35
Duplicate of #51075 and many other issues.

You need explicit type annotation for constant (see linked issue for more details)

**Comment by cesarve78** [comment] 2023-01-08 10:54
Thanks. Closing it

**Closed** 2023-01-12 18:00 UTC
Labels: Duplicate
