### ISSUE TITLE
Bug: `this` type not allowed in constructor

### ISSUE THREAD

**Issue by nin-jin** [Microsoft/TypeScript#8791] opened 2016-05-24 20:13 UTC
```ts
class X {
	foo = 1
	constructor( setup? : ( obj : this ) => void ) {
		if( setup ) setup( this )
	}
}

var x = new X( obj => {
	obj.foo = 2 // Ok, allowed
	// obj.bar = 3 // Ok, not allowed
} )
```

> A 'this' type is available only in a non-static member of a class or interface.

**Comment by jeffreymorlan** [comment] 2016-05-24 21:31
Exposing `this` to outside code from a constructor is an anti-pattern; subclasses haven't had the chance to do their own initialization yet:

```ts
class X {
	constructor(setup: (obj: any) => void) { setup(this); }
}
class Y extends X {
	a: string[] = [];
}
var y = new Y(obj => {
	obj.a.push('foo'); // fails because obj.a is not set yet
});
```

**Comment by mhegazy** [comment] 2016-05-24 23:06
Duplicate of https://github.com/Microsoft/TypeScript/issues/5863

**Closed by mhegazy** 2016-05-24 23:06 UTC

**Comment by nin-jin** [comment] 2016-05-25 07:32
@jeffreymorlan agree for this case :-) I am using this pattern now:

```
new X().setup( obj => {
    obj.foo = 2 // Ok, allowed
    // obj.bar = 3 // Ok, not allowed
} )
```

But it would be cool if we can use this:

```
new X().setup({
    foo : 2 , // Ok, allowed
    // foo : '3' , // Ok, not allowed
    // bar : 4 , // Ok, not allowed
})
```

But how to implement of strong intersection of type `this` and type of agrument?
