### ISSUE TITLE
'string | undefined' on known index of string[]

### ISSUE THREAD

**Issue by oyejorge** [microsoft/TypeScript#50149] opened 2022-08-02 21:42 UTC
# Bug Report

### 🔎 Search Terms

noUncheckedIndexedAccess array index

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about noUncheckedIndexedAccess

First noticed in 4.2.4, tested also in 4.7.4

### ⏯ Playground Link

https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true#code/JAMwrgdgxgLglgewgAgM4FMYCFMAooAWAhgE6oBcqMJcEA5gNoC6AlJdbXQN4BQPwwOCFzJCpVADoANunowCyALzLkARmQteA4CUxgSKMWQYAGJgG5+wAL58BumPpQByZ5Zs8gA

### 💻 Code

```ts
function setBet(chars:string[]):string{

	if( chars.length === 1 ){
		return chars[0];
	}
	return '';
}
```

### 🙁 Actual behavior

TS Error: "Type 'string | undefined' is not assignable to type 'string'."

### 🙂 Expected behavior

No error. Since the `chars` parameter is typed as `string[]`, if chars.length === 1, then chars[0] won't be `undefined`

**Comment by MartinJohns** [comment] 2022-08-02 21:43
Duplicate of #38000.

**Closed** 2022-08-05 18:00 UTC
Labels: Duplicate
