### ISSUE TITLE
Add `using namespace` statement

### ISSUE THREAD

**Issue by ruochenjia** [microsoft/TypeScript#53095] opened 2023-03-04 23:17 UTC
# Suggestion

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add a statement similar to `using namespace NS;` in C++, that allows to append members of an object/namespace/module to the global scope or function scope during compile time.

#### Using namespace in global scope
TypeScript:
```javascript
module NS {
  var a = 0;
  var b = "a";
}

using namespace NS;
b = "b";
a++;
```
Compiled JavaScript:
```javascript
NS.b = "b";
NS.a++;
```
#### Using namespace in function scope
TypeScript:
```javascript
module NS {
  var a = 0;
  var b = "a";
}

function c() {
  using namespace NS;
  a++;
  b = "";
}
```
Compiled JavaScript:
```javascript
function c() {
  NS.a++;
  NS.b = "";
}
```

#### Using namespace not allowed
```javascript
module NS {
  var a = 0;
  var window = null;
}

// error here as 'window' is already declared
using namespace NS;
```

#### Extending another module
```javascript
module A {
  var a = 0;
  var b = 1;
}

module B {
  using namespace A;
  var c = 10;
}

console.log(B.a); // 0
console.log(B.c); // 10
```

## 💻 Use Cases

Currently, I have to use `ModuleName.memberName` statement to access a member declared inside a module. This doesn't have many effects when you only have a few references, but I have far more than the acceptable amount just in one file. It makes your function lines longer, affects the readability of the code, and wastes a lot of time on just on typing out the module name.

**Comment by MartinJohns** [comment] 2023-03-05 01:24
Duplicate of #11775. You should also check the viability checklist again. Point 3 is definitely wrong.

**Comment by IllusionMH** [comment] 2023-03-05 01:24
Why this one is checked?
> This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

How it's different from `with`?

**Comment by Josh-Cena** [comment] 2023-03-05 03:30
Not to mention that `using` declarations are already taken by the [resource management](https://github.com/microsoft/TypeScript/issues/52955) feature ^^

**Comment by fatcerberus** [comment] 2023-03-05 05:06
> Not to mention that using declarations are already taken by the resource management feature ^^

To be fair, C# uses it for both purposes.  That said, yeah, this doesn't even come close to meeting the viability criteria.

**Closed** 2023-03-06 16:31 UTC
Labels: Suggestion, Out of Scope
