### ISSUE TITLE
Directory Compilation based on tsconfig.json to Properly Order Inherited Classes

### ISSUE THREAD

**Issue by bmingles** [Microsoft/TypeScript#3098] opened 2015-05-10 00:39 UTC
When a tsconfig.json file is used to target a directory instead of an explicit file list, inherited classes aren't guaranteed to be ordered correctly unless they contain /// <reference tags. It would be nice if directory based compilation could work out the order for inherited classes without the need for the extra tags.

eg.
If i have an empty tsconfig.json file:
```
{}
```
A base class:
```
/** Base class */
class ServiceBase {
}
```
And inheriting class:
```
/** Child class */
class MyService extends ServiceBase {
	constructor(){
		super();
	}
}
```
And a project structure like:
```
ProjectDir
--MyService.ts
--ServiceBase.ts
--tsconfig.json
```
The output .js will output the child class before the base class which gives runtime errors:
```
var __extends = this.__extends || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};
/** Child class */
var MyService = (function (_super) {
    __extends(MyService, _super);
    function MyService() {
        _super.call(this);
    }
    return MyService;
})(ServiceBase);
/** Base class */
var ServiceBase = (function () {
    function ServiceBase() {
    }
    return ServiceBase;
})();
```

If I add a reference comment to my child class, the ordering will be correct:
```
/// <reference path="ServiceBase.ts"/>
```
I'd like to not have to do this, since the reference tags no longer seem necessary for most other use cases:

**Comment by danquirk** [comment] 2015-05-11 19:29
We've generally avoided trying to automatically deduce file ordering. There're a variety of mechanisms to specify it yourself for cases like this where it is requires (_references.ts, tsconfig.json;s files property, normal /// references or imports).

**Comment by bmingles** [comment] 2015-05-13 12:24
That makes sense about not wanting to deduce file ordering, and adding a /// reference is easy enough. I would suggest that inheritance may be one place where a default deduced ordering makes sense, since it seems that a base class must always preceed an inheriting class in order for the code to even load. Just a suggestion though. Ya'll have done an amazing job on TypeScript. Thank you.

**Comment by danquirk** [comment] 2015-05-13 17:43
Yeah, I think we have another issue specifically for that simple case. Although the likely solution is that we would give an error asking you to fix the ordering rather than trying to figure out a valid ordering (of which there could be many with varying side effects).

**Comment by mhegazy** [comment] 2015-05-21 20:06
looks like a duplicate of #754

**Closed by mhegazy** 2015-05-21 20:06 UTC

**Comment by Jweber719** [comment] 2017-02-07 15:18
I'm using the "files" option and the compiler still uses alphabetical order....I don't think it is an "automatically deduction of file ordering" if you leave the order the way it is, in fact I think what the compiler is doing here is more deducing than if you just left it.  When I put my list of JS files in index.html, the browser doesn't automatically deduce file ordering, it uses what I declared, the compiler should too.  It gives the developer the power they need, or at least have a flag "keepFilesOrder" so we have some kind of power...this project has hundreds of TS files and referencing everything is redundant and a royal pain at this time.
