### ISSUE TITLE
type definition over async results

### ISSUE THREAD

**Issue by sebdoucet** [Microsoft/TypeScript#14169] opened 2017-02-18 18:53 UTC
TypeScript Version: 2.1.5

```ts
type VoidAsync = Promise<void>;

class Class1 {
    async func(): VoidAsync {

    }
}
```

**Expected behavior:**
No error.

**Actual behavior:**
error TS1055: Type 'VoidAsync' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.

**Comment by dylanpyle** [comment] 2017-10-05 23:35
Seems like this is a dupe of https://github.com/Microsoft/TypeScript/issues/12776 which is 'working as intended' albeit with a confusing error message.

**Comment by mhegazy** [comment] 2017-10-07 00:47
In ES5/ES3 the compiler uses the annotation to generate code, e.g. `async function f(): Bluebird.Promise<void> { ... }` this will call `new Bluebird.Promise` at runtime.

**Comment by mhegazy** [comment] 2017-10-07 00:47
https://github.com/Microsoft/TypeScript/issues/12776#issuecomment-265885846 should have a workaround here.

**Comment by mhegazy** [comment] 2017-10-23 18:38
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-23 18:38 UTC
Labels: Duplicate
