### ISSUE TITLE
texImage2D broken as of tsc 1.5

### ISSUE THREAD

**Issue by atebits** [Microsoft/TypeScript#3344] opened 2015-06-02 16:33 UTC
Calling the base version of the webgl function texImage2D (taking an ArrayBufferView of pixel data) results in:

`error TS2346: Supplied parameters do not match any signature of call target.`

Looks like the lib.d.ts only includes the definition for the version taking 'ImageData' for pixels.

**Comment by atebits** [comment] 2015-06-02 16:35
Added pull request: https://github.com/Microsoft/TypeScript/pull/3345

**Comment by zhengbli** [comment] 2015-06-02 17:51
This looks like a bug in the spec file.

**Comment by mhegazy** [comment] 2015-06-02 18:02
@zhengbli Can we add it to the script anyways

**Comment by zhengbli** [comment] 2015-06-02 18:07
Sure, I'll make the change to the script. Should be fixed for 1.6

**Comment by mhegazy** [comment] 2015-06-02 18:26
marking it as 1.5.2 since it is a regression.

**Closed** 2015-06-04 00:22 UTC
Labels: Bug
