### ISSUE TITLE
deeper type checks

### ISSUE THREAD

**Issue by gko** [Microsoft/TypeScript#13490] opened 2017-01-14 10:01 UTC
**TypeScript Version:**  2.1.1

**Code**

```ts
let test = (): boolean => {
  return fun(() => 1)()
}

let fun = (f: Function) => f
```

**Expected behavior:**
Error: Type '1' is not assignable to type 'boolean'.

**Actual behavior:**
No errors

**Comment by aluanhaddad** [comment] 2017-01-14 10:26
Because this is a common JavaScript idiom.
```ts
interface LineItem {
  name: string;
  price?: number;
}

const lineItems: LineItem[] = [{ name: 'A' }, { name: 'B', price: 9.99 }];

const totalCost = lineItems
  .filter(({ price }) => price)
  .reduce((sum, n) => sum + n.price, 0);
```

This used to be a type error back in the day but, I think the current behavior is better.

**Comment by gcnew** [comment] 2017-01-14 12:06
It's clearly wrong. Toss in a `===` check and everything blows up. Maybe a better solution would have been to introduce a type `coercible_bool` or `boollike`. While using coercions is a common JavaScript idiom, it should not be taken for granted that every `boolean` parameter is coerced. I'd rather expect the opposite (thats why `!!truthy` is a common idiom as well).

As a net result this is yet another type hole. I'm hoping a strict flag will fix it one day..

**Comment by ahejlsberg** [comment] 2017-01-14 17:09
This is working as intended. The `fun` function takes any function as an argument and returns it as a value of the general purpose type `Function`, effectively coercing a strongly typed function into a loosely typed one. Since the `Function` type permits calls with any argument list and returns values of type `any`, you end up converting the result from `number` to `any` and then from `any` to `boolean`.

The expected error is reported if you change `fun` to return the *same* type as it is given:

```ts
let fun = <T extends Function>(f: T) => f
```

**Comment by gko** [comment] 2017-01-14 19:10
@ahejlsberg thank you for your response.
In that case if I do:
```ts
let test = (): boolean => {
  return fun(() => () => {})()
}

let fun = <T extends Function>(f: T) => f
```

I also don't get an error

**Comment by gcnew** [comment] 2017-01-14 19:36
Apologies, I got confused because I was recently looking at [genericArgumentCallSigAssignmentCompat](https://github.com/Microsoft/TypeScript/blob/c320c884d6f8422dc0bebb0e80d276379e5d5b88/tests/cases/compiler/genericArgumentCallSigAssignmentCompat.ts#L16) which is currently passing, although it should not. For a second, I thought that maybe truthy/falsy assignments were actually allowed.

@gko If you turn `noImplicitAny` on, you see `() => () => {}` is marked as _implicit any_. It is then converted to `boolean` as @ahejlsberg explained.

**Comment by gko** [comment] 2017-01-14 19:42
@gcnew TIL. thank you

**Closed** 2017-01-14 19:43 UTC
Labels: Working as Intended

**Comment by aluanhaddad** [comment] 2017-01-15 01:15
>It's clearly wrong. Toss in a === check and everything blows up

@gcnew It is "correct" _if_ you want to coerce undefined to 0, since a seed is being passed to `reduce`, it will work.
That said, it is not a great practice.
