### ISSUE TITLE
DOM's Event is not extensible via class syntax

### ISSUE THREAD

**Issue by MadaraUchiha** [Microsoft/TypeScript#17156] opened 2017-07-13 09:13 UTC
**TypeScript Version:**  2.3.4

**Code**

```ts
class MyEvent extends Event {
    private foo: string;
    constructor() {
        super('hello');
        this.foo = 'bar';
    }
}

const ev = new MyEvent();
```

**Expected behavior:**
Code compiles and runs.

**Actual behavior:**
Code compiles, but Event has a runtime check that prevents calling it directly (without new). This means that TypeScript's compiled code: 
```js
// snip
var MyEvent = (function (_super) {
    __extends(MyEvent, _super);
    function MyEvent() {
        var _this = _super.call(this, 'hello') || this; // this throws
        _this.foo = 'bar';
        return _this;
    }
    return MyEvent;
}(Event));
```
Will throw at the marked line, because `_super` can't be `.call`ed directly.

With normal JS classes, the exact same code (sans the type annotations) work as expected.

---

P.S. I know that you're supposed to use `CustomEvent` with the `details` property, but that's not supported in IE or Safari, and we sadly need those browsers, and while it could be resolved with a polyfill for `CustomEvent`, this is still a piece of code that works with plain JS but does not run with TS compilation.

**Comment by MadaraUchiha** [comment] 2017-07-13 09:15
cc @linkgoron @benjamingr

**Comment by jcalz** [comment] 2017-07-13 14:04
Essentially a duplicate of the issue in #10853, right?  Are you trying to target ES5?

**Comment by kitsonk** [comment] 2017-07-13 14:06
Essentially yes.  Built-ins are not extensible in ES5.  It was not something that was introduced until ES2015.  There is no down-emit that would work.

**Comment by benjamingr** [comment] 2017-07-13 14:09
@kitsonk I'm not really sure what this has to do with ES2015 - this is not a built in - it's a host object. 

Whether or not it can be extended is up to the DOM and not JavaScript.

**Comment by jcalz** [comment] 2017-07-13 14:12
Also see #11304

**Comment by benjamingr** [comment] 2017-07-13 14:13
Yes, this issue looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/11304 - although that one is about an ES built in and this one is about the DOM.

**Comment by mhegazy** [comment] 2017-09-06 19:01
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-06 19:01 UTC
Labels: Duplicate
