### ISSUE TITLE
Type guard does not work with `Readonly` props

### ISSUE THREAD

**Issue by Lonli-Lokli** [microsoft/TypeScript#59865] opened 2024-09-05 09:43 UTC
### 🔎 Search Terms

type guard readonly

### 🕗 Version & Regression Information

- This changed between versions 4.9.5 and 5.0.4

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.0.4#code/KYDwDg9gTgLgBDAnmYcCyEDOBDAlgYwGlhE4BeOTGKXAOwHM4AfOWgVwFsAjYKAbgCwAKFCRYcOjF4AzbPlQYcBAArYowWjAA8AFTigptACaZ0WPERIA+OAG9hcONNxQqALjNL8AOQhHgulaCQo6YwPgQxh6KFr7+gcGhYAA2uDDKvPKa2PTAAPwe7Ny8wQC+wsKi0PBIKJ6xfgF6Bhom9QTEiDYUMSpqGto6Niw6wVXikjJyCuYEAELYYcpQEGCYuvoghm29ll12Do5w+MmLmN7YHPkeVDQMZZXg1RKaU-Lt+ADCkdQQycnAIzLVbrZpbVqmXadGwtYyQ2b4BZLFZrQIHEJwABu2GSbGA0QRcSaw1YbH+iTgkU+AAtsAx8XAABS0YAAdyJHjpiAAlOQbJiILgjA8RE8Jq8oLJ3rsAKq0CKaFb-QHA1Fg7bwrzQzYaj5I4Cq0E2ewYuhpXA4gBqOLxBK8RLRLHY5OE5SEjzENWQMy8ho2sJ2CO1PQR30VfwBQJRRuYHzlCt+yqjIISwmkbHlMFwkQkmHjPyVkf94LhH2hjLA0btFj9Q25HkrINzcflBYjKujaJNjnUMDYUFoTMbazgixbCcLHZTdYAdGas1abagAIQUZ3JEUe56TSXTD4AZRg2Ckxd1UOs6Mc+H76k0HI+DqGsfXm6EJzOHwA6mlqRA2DAABEoByIDVjDKQtlPCEyxIchKGoOh6BsS94OPBldkPNC0QobsjmvKBbxge910OUpgkOMA2C4VJ8DgXIYAAJQgCAYAAfTmABBACKyrOAGOAbAjEiZJEC0XZaysKx6wfRpHVJf4UMcXBpCZXA81bcMkx4kFuV5XCjjgXt+0HGBqTUmcqDQmd8MIokKUcUp9GSMJFKOAB6Ny4FVXgkDgABybFcWAPy4CE4BTFoFjNjU+Ac1qVA-P4wThNE8TOyGKw-JnQ4DI8o5vNgUgAqXEKwoiqLQBiykTO9fykqE2gRLEhF800yMJMymdGQAJgAZl6gBObkcqOIyBzgYdMBnQK8XsuA3QcioMUcSjqIIOjgEY5i2IAeUIbS1mrFR0qko6fFkp8nTJZJXOU1T1IndsjAOzBdNcntNuMhAzKmyypGsm8BjskbHOAZzUH00bPvGybpqXOaFvm11hCAA

### 💻 Code

```ts
export type MosaicKey = string | number;
export interface MosaicParent<T extends MosaicKey> {
  first: MosaicNode<T>;
  second: MosaicNode<T>;
  splitPercentage?: number;
}

export type MosaicNode<T extends MosaicKey> = MosaicParent<T> | T;
export interface MosaicBaseProps<T extends MosaicKey> {
    className?: string;
}
export interface MosaicControlledProps<T extends MosaicKey> extends MosaicBaseProps<T> {
  value: MosaicNode<T> | null;
  onChange: (newNode: any) => void;
}
export interface MosaicUncontrolledProps<T extends MosaicKey> extends MosaicBaseProps<T> {
  initialValue: MosaicNode<T> | null;
}

export type MosaicProps<T extends MosaicKey> = MosaicControlledProps<T> | MosaicUncontrolledProps<T>;
function isUncontrolled<T extends MosaicKey>(props: MosaicProps<T>): props is MosaicUncontrolledProps<T> {
  return (props as MosaicUncontrolledProps<T>).initialValue != null;
}

export interface MosaicState<T extends MosaicKey> {
  currentNode: MosaicNode<T> | null;
}

class MosaicWithoutDragDropContext<T extends MosaicKey = string>  {
  state: MosaicState<T> = {
    currentNode: null
  };

  public getRoot_BAD(props: Readonly<MosaicProps<T>>): MosaicNode<T> | null {
    if (isUncontrolled(props)) {
      return this.state.currentNode;
    } else {
      // Property 'value' does not exist on type 'Readonly<MosaicProps<T>>'.
      //   Property 'value' does not exist on type 'Readonly<MosaicUncontrolledProps<T>>'.(2339)
      return props.value;
    }
  }

    public getRoot_OK(props: MosaicProps<T>): MosaicNode<T> | null {
    if (isUncontrolled(props)) {
      return this.state.currentNode;
    } else {
      return props.value;
    }
  }
}

```

### 🙁 Actual behavior

      // Property 'value' does not exist on type 'Readonly<MosaicProps<T>>'.
      //   Property 'value' does not exist on type 'Readonly<MosaicUncontrolledProps<T>>'.(2339)

### 🙂 Expected behavior

no errors

**Comment by MartinJohns** [comment] 2024-09-05 10:42
Duplicate of #54385. Used search terms: `readonly narrow in:title`

**Closed** 2024-09-05 13:47 UTC
