### ISSUE TITLE
tsserver: one false entry in tsconfig.json makes whole project fail

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#4618] opened 2015-09-03 09:32 UTC
Example:

tsconfig.json:
```json
{
    "compilerOptions": {
        "target": "ES5",
        "noImplicitAny": false,
        "removeComments": false,
        "preserveConstEnums": false,
        "sourceMap": true,
        "experimentalDecorators": true
    },
    "files": [
        "lib/utils/A.ts",
        "lib/utils/B.ts",
        "example/abc"
    ]
}
```
note: the wrong entry example/abc

A.ts in lib/utils
```typescript
module abc.test {
	export interface I {
		foo(): void;
	}
}
``` 
B.ts in lib/utils
```typescript
module abc.test {
	class B implements I {
		public foo(): void {
		}
	}
}
```
Observe: you get a oompile error on I. The name is not known. Now remove the entry "example/abc" from tsconfig.json and everything is fine.

**Comment by DavidSouther** [comment] 2015-09-03 11:02
Is that not expected behavior? If you want to match arbitrary files, you can use `filesGlob`. Or is the error message not what you expect?

**Comment by weswigham** [comment] 2015-09-03 19:11
Dupe #4227 ?

**Comment by mhegazy** [comment] 2015-09-03 19:39
looks like a dupe of #4227

**Closed** 2016-02-20 05:23 UTC
Labels: Duplicate
