### ISSUE TITLE
unique symbol from the same source text position via multiple construction should be incompatible

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#48736] opened 2022-04-17 06:45 UTC
# Bug Report

### 🔎 Search Terms

`unique symbol`

### 🕗 Version & Regression Information

Tested on 4.7.0

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEEQBd5gPYDtgC54CN10kpMBYAKADMBXTMZASy3gC8AKASngG9L4BaLAGdUUeAF54AZQCeAW0IQu-QXGQ0YmXvCh5xAX13ChmUZQOUkqAB6S2Kitfiz7HTpUoB6L-ACiNgAO4MggwP4wMOgweAAqssHwAOTICSDoVLpJ8IwmmOhiwsKMAOaYUPhI8Mjo1WnJqcEZWQB08LEA7rXAjFRUIHCYqI0gJh2MyAAW1ZO58OXyCCA2ucgANAQ0w5MgrrAIdHDQocAtlL3w7BjY3HwUgvB2UrIW8CAQwgh3D65SNhaUZaBaKoHgGIA)

### 💻 Code

```ts
declare let cond: boolean
function z() {
    const a = Symbol()
    return { a: a } as const
}
let x = z()
let y = z()

// Expected Error: Type 'typeof a' is not assignable to type 'typeof a'. Two different types with this name exist, but they are unrelated.
if (cond) {
    x = y
} else {
    y = x
}
export {}
```

### 🙁 Actual behavior

No type error

### 🙂 Expected behavior

Type 'typeof a' is not assignable to type 'typeof a'. Two different types with this name exist, but they are unrelated.

**Comment by whzx5byb** [comment] 2022-04-17 07:16
Duplicate of https://github.com/microsoft/TypeScript/issues/40106

**Closed** 2022-04-17 07:21 UTC
