### ISSUE TITLE
Mixin function failed to compile when exported with --declaration

### ISSUE THREAD

**Issue by vietthang** [Microsoft/TypeScript#14317] opened 2017-02-26 13:19 UTC
**TypeScript Version:**  2.2.1

**Code**
Extract from official example:

```ts
// A *self-contained* demonstration of the problem follows...
export type Constructor<T> = new(...args: any[]) => T;

export function Tagged<T extends Constructor<{}>>(Base: T) {
  return class extends Base {
    _tag: string;
    constructor(...args: any[]) {
        super(...args);
        this._tag = "";
    }
  };
}
```

**Expected behavior:**
Code compiled fine.

**Actual behavior:**
This code fail to compile with `--declaration` options. The error is:

`Return type of exported function has or is using private name '(Anonymous class)'.`

It compiled fine without `--declaration`. Did I miss something?

**Comment by DanielRosenwasser** [comment] 2017-02-26 15:46
Duplicate of #14209 and therefore #14075.

**Closed** 2017-02-26 15:46 UTC
Labels: Duplicate
