### ISSUE TITLE
Type narrowing of an object property

### ISSUE THREAD

**Issue by JimmyRowland** [microsoft/TypeScript#50407] opened 2022-08-22 22:16 UTC
# Bug Report

Type narrowing does not work on a property of an object without assigning the property to an intermediate variable.

### 🔎 Search Terms

Record, type narrowing, object property

### 🕗 Version & Regression Information

- This changed between versions 4.7.4 and 4.9,0
- This is the behavior in every version I tried.

### ⏯ Playground Link

[Type narrowing bug](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220822#code/C4TwDgpgBAwghsCBzA9gJxFAvFARKSARlygB88CIAmXAbgFgAoS2OAGzYCM4BjAa2xQAFAEpsAPiicUKNhDgA7Bs3DR4iVBgDyaAGIBXBT2ABLFAsHrk6TOXgdu-ZSxgALE2wAmAFVWDcPO5exGR4gR6eNM5+WmCm5lqcAFYQxoIA3lBo8p7mbJgA2nwQmCYWbhG+kAC6APwAXKwaNjoGRvEWAL7RkFCxHZYI1tp6hsZmFuT9E4kpxso85gDOwFA8Q5og3ij2XLx8ALJwYBlMUFCUhI2iEhdo+hAANGcXqlTXYliSAGbsSxBMbpMRYKFZQFBxCaEDJrIKeK7CT6SYD3aBAxggsEQjpUQQ3L53B7KJjfMYDJAQYC7Rx8IThLyNCpeKpPcGQ8yNabmESM9h7fhQdIvEzfYSUFCi7ETbBYHC4FDJVLAXBiIWMc7nAD0mqgAHd0Hwli9zpjVutmiM2uNzIIpeYCvTPNVlBqoCKxaoJWsNi1Ru1pbK5Ss0GUkCrBcaNaaLhAVryLZgcObhiBWmSJi6NZ0XtnGMLRUJxZL2QoHXDqjKgyjQ+G1a7tVBcrGoAoUKt9WhDZHo4g400U7aS2WIs6c0wXtlgPo0BZ8cjUcpc0A)

### 💻 Code

```ts
type Category = "type1" | "type2";
type Callback = () => boolean;
type CategoryOrFunction = Category | Callback;
type ChildType = "child1" | "child2";
type OptionObject = { readonly [key in ChildType]?: CategoryOrFunction };
type Option = CategoryOrFunction | OptionObject;
const categoryToCallbackMap = {
  type1: () => true,
  type2: () => false
};
const option1 = { child1: () => true };
const option2 = () => true;

function getCallback(child: ChildType, option: Option): Callback {
  if (typeof option === "object") {
    // works
    const categoryOrFunction = option[child];
    if (typeof categoryOrFunction === "string") {
      const test: Category = categoryOrFunction;
    }
  }

  if (typeof option[child] === "string") {
    // does not works
    const test: Category = option[child];
  }

  return () => true;
}
```

### 🙁 Actual behavior

```ts
  if (typeof option[child] === "string") {
    // does not works
    const test: Category = option[child];
  }
```
`typeof option[child]` (implicit any) and `const test: Category = option[child];` (CategoryOrFunction is not assignable to Category) return error.

### 🙂 Expected behavior

There should be no error

**Comment by IllusionMH** [comment] 2022-08-22 22:37
Duplicate of #46560 and other.

As you've mentioned - assigning to const is safe and works as expected.

**Closed** 2022-08-28 18:00 UTC
Labels: Duplicate
