### ISSUE TITLE
Generic types on lib.dom window fetch

### ISSUE THREAD

**Issue by cenguidanos** [microsoft/TypeScript#44000] opened 2021-05-07 19:51 UTC
# Suggestion

Add generic types to `window.fetch`

## 🔍 Search Terms

- window.fetch
- Response types
- json() fetch types

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

```ts
// declare function fetch(input: RequestInfo, init?: RequestInit): Promise<Response>;
declare function fetch<T = any>(input: RequestInfo, init?: RequestInit): Promise<Response<T>>;

// interface Response extends Body {
interface Response<T = any> extends Body<T> {
    readonly headers: Headers;
    readonly ok: boolean;
    readonly redirected: boolean;
    readonly status: number;
    readonly statusText: string;
    readonly trailer: Promise<Headers>;
    readonly type: ResponseType;
    readonly url: string;
    clone(): Response;
}

interface Request extends Body { ... }

// interface Body {
interface Body<T = any> {
    readonly body: ReadableStream<Uint8Array> | null;
    readonly bodyUsed: boolean;
    arrayBuffer(): Promise<ArrayBuffer>;
    blob(): Promise<Blob>;
    formData(): Promise<FormData>;
    json(): Promise<T>;
    text(): Promise<string>;
}
```

## 📃 Motivating Example

```ts
type User = { user: string, password: string }

const response = await fetch<User>('https://...')

let user: User

if (response.ok) user = await response.json()

// Maybe better than ??
interface UserResponse extends Response {
  json(): Promise<User>
}

const response: UserResponse = await fetch('https://...')



```

**Comment by MartinJohns** [comment] 2021-05-07 20:47
This seems to be a duplicate of #33037.

**Closed** 2021-05-13 18:00 UTC
Labels: Duplicate
