### ISSUE TITLE
Type Prediction for union with typeguard seems wired

### ISSUE THREAD

**Issue by ryoppippi** [microsoft/TypeScript#55961] opened 2023-10-03 00:33 UTC
### 🔎 Search Terms

TypeGuard
Union

### 🕗 Version & Regression Information

Works After TS 4.6

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABDAzgORAG0wCgB4Bci4A1mHAO5gCUReyKiYWmA3gFCJeIBOAplBA8k9ALzimLANzsAvu3ZQAngAc+iAKI8ecHgFUw8MAB4AKgBpEexKM3bdAPhuIA2nsvgAJn2AwwfTwBdRAAfV2ZsS1NAhXZQSFgERCg+FCgcAEMeAHMiLR19QwRjNJ4-bKdqDm5ECAQ01z5tSwA3DMwQPmDbLOzObhhgHABCVAxsHCaeair+mq4oAAsdCkQpmRr5Gv5BYUQ2jvVEAHpjxFLy0OIwb19-TzkFeOgjZNSoACZMnLz7QqMSlAymAKohZjU6mAGi4pq12p1uohenNkEMpohhhIIphwfMFstKGttBtuFtuDshEgDp0TmcLiC5EA

### 💻 Code

```ts
function isNull(x: unknown): x is null{
    return x === null;
}

type ErrorUnion<T, U = Error> = [U, undefined] | [null, T]


function test(arg: ErrorUnion<string> ){
    const [err, value] = arg
    if(!isNull(err)){
        throw err;
    }
    return value  // string | undefined
}

function test2(arg: ErrorUnion<string> ){
    const [err, value] = arg
    if(err !== null){
        throw err;
    }
    return value // string
}
```

### 🙁 Actual behavior

The `value` variables in `test` and `test2` are predicted as different types

### 🙂 Expected behavior

Both `value` in `test` and `test2` should be predicted as `string`

**Comment by fatcerberus** [comment] 2023-10-03 00:43
Looks like a duplicate of https://github.com/microsoft/TypeScript/issues/55766#issuecomment-1723380802.

**Comment by ryoppippi** [comment] 2023-10-03 00:45
@fatcerberus 
Yeah looks like duplicated one
Thanks

**Comment by MartinJohns** [comment] 2023-10-03 12:36
What does it mean if it seems wired?

**Comment by fatcerberus** [comment] 2023-10-03 12:44
> What does it mean if it seems wired?

Probably that the programmer had too much coffee.

**Closed** 2023-10-06 01:25 UTC
Labels: Duplicate

**Comment by ryoppippi** [comment] 2023-10-06 14:27
Why you guys are so offensive.....
