### ISSUE TITLE
Why the recursive function's return type inferenced as any?

### ISSUE THREAD

**Issue by nnnnoel** [microsoft/TypeScript#53978] opened 2023-04-24 05:33 UTC
# Bug Report
when write recursive function via generator function or function,
return type inferenced as any.
the general purpose for recursive function, return type can be inferenced as correct return type.

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://tsplay.dev/mMzE1W)

### 💻 Code
<img width="294" alt="image" src="https://user-images.githubusercontent.com/67718949/233907817-f49ddc4f-3f2f-4722-853f-f477f37052ae.png">

```ts
function mock__fstat(name: string) {
    if (Math.random() > 0.5) {
        return {
            isDirectory: true,
            isFile: false,
        };
    }
    return {
        isDirectory: false,
        isFile: true,
    };
}
function* walk(dir: string) {
    if (mock__fstat(dir).isDirectory) {
        yield* walk(dir.split('/').slice(1).join('/'));
    }
    yield dir;
}
const a = walk('/a/b/c'); // will be AsyncGenerator<string>, but inferenced type is any
```

### 🙁 Actual behavior
walk function's return type is any

### 🙂 Expected behavior
walk function's return type is AsyncGenerator<string>

**Comment by MartinJohns** [comment] 2023-04-24 06:24
Your playground link does not work. Duplicate of #32523.

**Comment by nnnnoel** [comment] 2023-04-24 07:33
I thought #32523 is not focused on recursive function's type.

**Comment by RyanCavanaugh** [comment] 2023-04-24 15:47
The error message tells you why?

> because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.

**Comment by nnnnoel** [comment] 2023-04-25 03:59
@RyanCavanaugh but i cannot understand why this expression didn't inference type implicitly.
in this case, walk function returns `AsyncGenerator<string>` absolutely but recursive function call's return type inferenced as any.
why didn't skip the recursive function call in return type in inference flow?

**Comment by fatcerberus** [comment] 2023-04-25 05:32
> why didn't skip the recursive function call in return type inference flow?

https://github.com/microsoft/TypeScript/pull/53995 is probably relevant

**Comment by nnnnoel** [comment] 2023-04-25 06:58
@fatcerberus omg thanks a lot!

**Closed** 2023-04-27 09:20 UTC
Labels: Question
