### ISSUE TITLE
narrowing of property should also narrow its parent when optional chaining

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#49187] opened 2022-05-20 10:14 UTC
# Suggestion

## 🔍 Search Terms
narrowing optional chaining

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

when narrowing a property in an object, there are often other things it should be able to narrow as well. for example, when narrowing `foo?.bar` to a non-`undefined` type, it should also narrow `foo` to not be `undefined`

## 📃 Motivating Example

```ts
declare const foo: {
  bar: number[]
} | undefined

if (Array.isArray(foo?.bar)) {
  foo.bar //error: Object is possibly 'undefined'
}
```

## 💻 Use Cases

i'm trying to conditionally modify an array, but only if its parent property is present. currently, i have to use `!` to tell the compiler that it's not undefined, which isn't ideal:
```ts
if (
  itemDefinition.request === undefined ||
  typeof itemDefinition.request.url === 'string'
)
  return itemDefinition
const newItemDefinition = cloneDeep(itemDefinition)
if (Array.isArray(newItemDefinition.request!.url)) {
  newItemDefinition.request!.url.push({})
}
```

**Comment by MartinJohns** [comment] 2022-05-20 12:49
This sounds like a duplicate of #34974 to me.

**Closed** 2022-05-20 15:22 UTC
