### ISSUE TITLE
Support for new.target

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/TypeScript#8494] opened 2016-05-06 06:31 UTC
**TypeScript Version:** 

1.8.10

**Code**

```ts
function Foo() {
  console.log(new.target);
}

new Foo();
```

**Expected behavior:**

When targeting ES6, this should compile without an error.

`new.target` is an [obscure bit of ES6](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target), but it is there, for example running the code in an [ES6 browser returns what is expected](https://jsfiddle.net/kitsonk/2qa0n8m3/2/) in that `new.target === Foo`.  When it is just `Foo()` without `new` then `new.target === undefined`.

While it maybe challenging to come up with an emit that works for ES5, it should be at least supported when targeting ES6.

I suspect and emit for ES6 might be something like this:

```javascript
function Foo() {
  var _newTarget = this === window ? undefined : this && this.constructor;
  console.log(_newTarget);
}
```

**Actual behavior:** 

Compiles as:

```
$ tsc --target es6 test.ts
test.ts(2,18): error TS1109: Expression expected.
```

**Comment by basarat** [comment] 2016-05-06 06:37
I think it should just be supported *valid* compile without getting into *how to do a great emit*. 

That said `window` would be a bad idea (e.g. nodejs)

**Comment by kitsonk** [comment] 2016-05-06 06:46
> That said window would be a bad idea (e.g. nodejs) 

Revised:

```js
function Foo() {
  var _newTarget = this === (typeof window === 'undefined' ? global : window) ? undefined : this && this.constructor;
  console.log(_newTarget);
}

Foo();
```

When `'use strict';` is used, then `this` will be `undefined` anyways and the emit could simply be:

```js
'use strict';

function Foo() {
  var _newTarget = this && this.constructor;
  console.log(_newTarget);
}

Foo();
```

**Comment by mhegazy** [comment] 2016-05-06 16:35
duplicate of https://github.com/Microsoft/TypeScript/issues/2551

**Comment by kitsonk** [comment] 2016-05-06 16:37
Ooops... sorry...  I will move over to there...

**Closed** 2016-05-06 16:36 UTC
Labels: Duplicate
