### ISSUE TITLE
Typescript incorrectly infer the types for Readonly optional properties.

### ISSUE THREAD

**Issue by dryganets** [Microsoft/TypeScript#18902] opened 2017-10-03 00:38 UTC
**TypeScript Version:**  2.5.3) / 2.6.0-dev.20170930

**Code**

https://github.com/dryganets/typescript-bug/blob/master/index.ts
I expect this code to compile.
This example is
**Expected behavior:**
type guard
```
if (this.props.a) {
}
```

reduces the type from string|undefined to string.

**Actual behavior:**
type is still string|undefined after check.

The bug doesn't repro if I use the slightly different syntax:

```
export class Test extends ComponentBase<Props, {}> {

```

But we have some places in the app where the former syntax is required.

**Comment by mhegazy** [comment] 2017-10-03 00:59
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/15376. `this.prop.a` is a generic type, `P["a"]`, and there is no way currently to narrow a generic type. 

It is worth noting that the compiler does the right thing on property access/ index access/ call thanks to https://github.com/Microsoft/TypeScript/pull/15576. but the type of the symbol does not change.

**Comment by mhegazy** [comment] 2017-10-17 16:28
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-17 16:28 UTC
Labels: Design Limitation
