### ISSUE TITLE
 Incorrect information in the section "Type assertions" 

### ISSUE THREAD

**Issue by ravecat** [microsoft/TypeScript#37799] opened 2020-04-05 20:01 UTC
In section about [type assertions](https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions) didn't find angle-bracket example.

**Expected behavior:**

```typescript
let someValue: any = "this is a string";

let strLength = <string>(someValue.length);
```

**Actual behavior:**

```typescript
let someValue: any = "this is a string";

let strLength: number = (someValue).length;
```

**Comment by orta** [comment] 2020-04-05 21:00
Thanks! Closing as it's a dupe of https://github.com/microsoft/TypeScript-Website/issues/452

**Closed by orta** 2020-04-05 21:00 UTC
