### ISSUE TITLE
Allow typeof on arbitrary expression

### ISSUE THREAD

**Issue by mwisnicki** [Microsoft/TypeScript#2542] opened 2015-03-29 14:29 UTC
At the moment compiler insists on having valid identifier on right side of `typeof` so following code is not valid:

```ts
var x : typeof (1+ 2);
var y : typeof this;
```

even though it's possible to assign the expression to variable and then capture the type form that:

```ts
var x_ = 1+2;
var x = typeof x;
var y_ = this;
var y = typeof y_;
```

I propose to allow capturing type of any valid expression. The expression itself wouldn't be evaluated.

**Comment by mhegazy** [comment] 2015-03-30 18:20
How is that different from:
```ts
var x = typeof (1+2);
var y = typeof this;
```

**Comment by RyanCavanaugh** [comment] 2015-03-30 18:23
@mhegazy we're talking about type-position `typeof`, not value-position.

`typeof this` seems useful, but more allowing more complex expressions is trickier. It's not at all apparent to a casual observer that `typeof f(x)` *in type positions only* won't evaluate the function call; the restriction to dotted identifiers is a bit of a safeguard in this respect.

Other than `typeof this`, what kind of uses cases do you want this for?

**Comment by mhegazy** [comment] 2016-02-20 06:30
duplicate of #6606

**Closed by mhegazy** 2016-02-20 06:30 UTC
Labels: Needs More Info, Suggestion
