### ISSUE TITLE
Add support for a .tsconfig file 

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#1667] opened 2015-01-14 07:14 UTC
Typescript compiler lacks a native way of maintaining compilation options and source files for a given compilation unit like a project or a module. Using /// <references> can help ease the problem, but there is still a tax of adding and managing the references and it does not handle the compilation options issue. Moreover, different editors have different ways of representing project or module structure and compilation options which make cross-editor collaboration tricky.

The proposal is to introduce a new file `.tsconfig` that marks a compilation unit (aka project or module). The .tsconfig follows the footsteps of the .git* file family. Calling tsc in a directory with a .tsconfig will use the contents of the file and all .ts files in the directory as inputs without the need to specify them on the command line again.

### .tsconfig in detail
- .tsconfig is a json file
- The presence of a .tsconfig in a directory indicate that all .ts file in this directory and its sub directories recursively are part of the compilation unit
  - .d.ts files generated from the compilation but live within the directory are not included in the compilation unit identified by .tsconfig
- .tsconfig can specify additional compilation settings for the compilation
- Calling tsc in a folder containing .tsconfig will trigger compilation using the config file
- Since .tsconfig is a json file, it can be leveraged by other tools (linters, editors, build tools etc..) to store TS related project configuration
- Example .tsconfig
```JSON 
{
    "compilerOptions": ["-t ES5", "--out myoutput.js", "--noImplicitAny"],
    "linterOptions": {
        "suppressWarnnings": [234, 3363] 
    }
}
```

### Module example
Consider the following directory structure:
```
shared/
	node.d.ts
	tools.ts
foo/
	.tsconfig
	a.ts // adds a ///<reference> to node.d.ts 
	b.ts
bar/
	.tsconfig
	c,ts // adds a /// <references> to tools.ts
	d.ts
	baz/
		e.ts
```

Calling tsc in "foo" is equivalent to` tsc a.ts b.ts` 
Calling tsc in "bar" is equivalent to `tsc c.ts d.ts baz/e.ts`

### Using .tsconfig with tsc
- When calling tsc with no input files, the following steps are taken:
 1. Find the owning .tsconfig file by walking up the directory structure until a .tsconfig file is found, or the drive root is reached
 2. If a .tsconfig was found, compilation will be triggered with all .ts files in the directory containing the .tsconfig and all its sub directories
 3. The command line switch are compiled with the configuration options from the .tsconfig defining the compilation command line flags (e.g.: `tsc --watch` will cause a tsc to compile the contents of the current project in watch mode)

- When calling tsc with input a single directory name (e.g.: `tsc compiler`), If the directory contains a .tsconfig at the root, steps 2 and 3 from above are followed.

### Specifying output order with --out and .tsconfig
when using --out, the compiler relies on the order of the files passed on the command line to order the emitted JavaScript code. If using .tsconfig, the compiler will look for a special file `_references.ts` at the root (next to the .tsconfig file), and will ensure that this file is the first file in the list of input files. this implies that /// <reference> tags in _references.ts will specify order of the emitted files.

### Open issues:
1. Should the tsconfig file have a `.json` extension to indicate intended content, and allow editors to correctly colorize it, format it, etc..
2. In a VS project context (say .csproj), should .tsconfig be honored, or ignored in favor of the project.

**Comment by Arnavion** [comment] 2015-01-14 07:43
- It would be nice if "commandLineOptions" was an object like `{ "t": "ES5", "noImplicitAny": true }` instead of an array of strings (essentially the CompilerOptions interface but with strings instead of enums). This is similar to how the grunt plugin, etc. are configured. See [this](https://www.npmjs.com/package/grunt-typescript#documentation) and [this](https://www.npmjs.com/package/grunt-ts#support-for-tsc-switches).

- What options should not be honored in a .tsconfig ? For example, I don't know if anyone will ever want "watch" to be a default behavior of running tsc under their project directory, so even if .tsconfig contains "watch" it should be ignored?

**Comment by DanielRosenwasser** [comment] 2015-01-14 07:44
Great writeup @mhegazy. A few questions/concerns:

Are we not going to be able to specify TypeScript files in the config file? Perhaps this is something for down the road instead?

---------------------------------------------

> ```JSON
"compilerOptions": ["-t ES5", "--out myoutput.js", "--noImplicitAny"]
```

This seems a little silly - it's like we're getting closer to the *actual* structure of `ts.CompilerOptions`, but we're still expecting something we have to parse. Why not just permit the full command line string or a plain object? For instance, the following could be equivalent:

```JSON
"compilerOptions": { "target": "ES5", "out": "myoutput.js", "noImplicitAny": true }
```

and if we really don't want users to have to a type the whole word, the following could be allowed as well:

```JSON
"compilerOptions": { "t": "ES5", "out": "myoutput.js", "noImplicitAny": true }
```
---------------------------------------------

> Should the tsconfig file have a .json extension to indicate intended content, and allow editors to correctly colorize it, format it, etc.?

Yes. In fact, I don't think it should be a `.tsconfig` file, I think it should be something like `tsconfig.json`. Dot prefixes for filenames are an accident of history, and now an artifact from indicating hidden files on Unix systems when filesystems didn't support a 'hidden' attribute. Let's just be explicit.

---------------------------------------------

**Comment by Arnavion** [comment] 2015-01-14 07:52
>>Should the tsconfig file have a .json extension to indicate intended content, and allow editors to correctly colorize it, format it, etc.?

>Yes. In fact, I don't think it should be a .tsconfig file, I think it should be something like tsconfig.json.

Some tools like jake allow both `Jakefile` and `Jakefile.js` for the "default file". Perhaps both .tsconfig and tsconfig.json could be allowed here. 

>Dot prefixes for filenames are an accident of history, and now an artifact from indicating hidden files on Unix systems when filesystems didn't support a 'hidden' attribute.

Well they do have the nice property of automatically becoming hidden files, and of being a shell convention rather than a filesystem attribute. Filesystem attributes require support not just from every filesystem the code is going to live on, but also from tooling like version control. git doesn't support them, for example.

**Comment by mhegazy** [comment] 2015-01-14 07:56
>Are we not going to be able to specify TypeScript files in the config file? Perhaps this is something for down the road instead?

The idea that you do not need to specify anything. all files in your folder are part of the compilation. I can see an "exclude list", but not include.

>This seems a little silly - it's like we're getting closer to the actual structure of ts.CompilerOptions, but we're still expecting something we have to parse. Why not just permit the full command line string or a plain object? For instance, the following could be equivalent:

My preference would be to have the actual structure of ts.CompilerOptions. The problem with this is that there are enum values for module and target, and `{ "module" : 2 }` does not look helpful. so since we are doing a translation step anyways, sticking with something standard is simpler, like the accrual command line you would use to build on the command line without the tsconfig file. I would say, compilerOptions should just take a string which is the command line, that would be parsed.
```JSON 
"compilerOptions": "-t ES5 --out myoutput.js --noImplicitAny"
```

**Comment by NoelAbrahams** [comment] 2015-01-14 09:55
@mhegazy, thanks for raising this.

> Should the tsconfig file have a .json extension to indicate intended content, and allow editors to correctly colorize it, format it, etc..

My perference is for the file to be called `typescript.json`. Visual Studio now provides [syntax help and colourisation](http://blogs.msdn.com/b/webdev/archive/2014/02/28/new-json-editor-features-in-visual-studio-2013-update-2-ctp2.aspx) for these files. In addition [it's possible to schema-validate the content](http://blogs.msdn.com/b/webdev/archive/2014/04/11/intellisense-for-json-schema-in-the-json-editor.aspx).

> In a VS project context (say .csproj), should .tsconfig be honored, or ignored in favor of the project.

In VS people tend to use the TypeScript settings UI in order to change project settings. Since editing a JSON config file is even easier, I would suspect that the settings in .csproj will get out of date very soon. Something needs to be done about this. We shouldn't permit settings to be specified in two places, because that just introduces another source of potential confusion. In VS compiling a project with settings specified in both .csproj and the proposed `typescript.json` should result in a compilation error.

I also have an additional suggestion. We should deprecate the `_references.ts` file and permit references to be specified directly in `typescript.config`. That way we are not really introducing yet another config file into the mix, but rather replacing an existing one.

**Comment by dbaeumer** [comment] 2015-01-14 13:33
@mhegazy, thanks for starting working on this. I have a couple of comments and questions.

> Should the tsconfig file have a .json extension to indicate intended content, and allow editors to correctly colorize it, format it, etc

I am in favor of having a .json extension. Alternative names are ts.json or tsc.json

I agree with Arnavion to store the compiler options as a JSON object instead of a string. It eases readability and will ease to manipulate and read the config file from other tools.

I like the approach of finding a config file by walking up the directory structure and then using it. However from the writeup it is unclear to me what happens if the directory containing the picked config file has a subdirectory that has its own config file (e.g. like git where every directory can have its own .gitignore file). Will it first call tsc with the config file of the sub directory and when finished tsc with the config file of the parent directory excluding the files from the sub directory. And what do we do if the parent has two subdirectories with a config file? Do we need to specify a build order then?

And +1 to be able to specify an exclude list in the config file.

**Comment by mhegazy** [comment] 2015-01-14 17:25
@dbaeumer you raise a good point. Initially I thought about excluding the sub directories with the tsconfig file in them, but thinking about this seems confusing and not intuitive. building them as well seems to introduce other complications. i wonder if it should be an error to have this sort of nesting of these tsconfig files. would love to get your thoughts on how to handle this.

**Comment by mhegazy** [comment] 2015-01-14 17:34
@NoelAbrahams thanks for the feedback, a few comments:

> In VS people tend to use the TypeScript settings UI in order to change project settings. Since editing a JSON config file is even easier, I would suspect that the settings in .csproj will get out of date very soon. Something needs to be done about this. We shouldn't permit settings to be specified in two places, because that just introduces another potential source of confusion. In VS compiling a project with settings specified in both .csproj and the proposed typescript.json should result in a compilation error.

I do not have a good solution here either. i agree that it is a problem, but i am not sure if a compilation error is the best path. Consider cases where team members use VS as their main editor, where others use a different editor, making it an error means that the VS folks get to use their project file, and the others can not get tsconfig support. Maybe an MSBuild build-time warning would be more suited to this situation. thoughts?

> I also have an additional suggestion. We should deprecate the _references.ts file and permit references to be specified directly in typescript.config. That way we are not really introducing yet another config file into the mix, but rather replacing an existing one.

Two concerns here, we will need to continue supporting _references in VS and MSBuild, so deprecating it does not mean it will disappear. so what we are doing effectively is adding yet another way of doing the something. Though i am not a fan of _references.ts logic or its name, but it seems to solve the problem.
The other concern is that /// <references> are common enough that it is not a foreign concept so it makes it easier to explain to ts developers, instead of adding another pre-processor step along with /// references.

**Comment by danquirk** [comment] 2015-01-14 19:57
_Consider cases where team members use VS as their main editor, where others use a different editor, making it an error means that the VS folks get to use their project file, and the others can not get tsconfig support._

It seems to me that if you've gotten to the point where your team has a robust enough .tsconfig to serve other editors then VS should also just prefer it and obsolete your project file. You're guaranteed to experience pain if you have 2 distinct 'project files' but the only kind of 'project file' we could guarantee works everywhere is .tsconfig, so that would need to take precedence.

**Comment by Peter-Juhasz** [comment] 2015-01-14 19:58
+1 for **.json extension with schema**. Please do not introduce stupid linux-style namings for Visual Studio developers on Windows.

And yeah, we may need different configurations for different environments. And these configurations should be set/applied at one centralized place in the build process, like now I can manage TypeScript build configuration bound to MSBuild configuration and not separately.

**Comment by billti** [comment] 2015-01-14 20:33
+1 on using an object with properties for each switch rather than a string.  That way you can have a schema and intellisense to help you author the properties.

I also agree on dropping the "." from the start of the name. Why would you want this file to be hidden on some platforms if it's your project configuration file?  Make it a key file in the project root, similar to "package.json" for NPM.  I like Daniel's suggestion of "tsconfig.json".

**Comment by NoelAbrahams** [comment] 2015-01-15 10:33
@mhegazy 

> we will need to continue supporting _references in VS and MSBuild, so deprecating it does not mean it will disappear. so what we are doing effectively is adding yet another way of doing the same thing. Though i am not a fan of _references.ts logic or its name, but it seems to solve the problem.

Why would we need to support `_references.ts` in VS and MSBuild? If we are going to add compiler settings in the tsconfig that means VS and MSBuild would need to read them, right? The references could be read at the same time.

> The other concern is that /// are common enough that it is not a foreign concept so it makes it easier to explain to ts developers, instead of adding another pre-processor step along with /// references

The triple slash reference was never popular with users, e.g. #488. People just don't like to add directives within comments.

If we do the following:

```JavaScript
{
    "compilerOptions": { "target": "ES5", "out": "myoutput.js", "noImplicitAny": true },
    "linterOptions": {
        "suppressWarnnings": [234, 3363] 
    },
    "references": [
       "../typings/node.d.ts",
       "./bar.ts"
    ]
}
```

then tooling can be built to add/remove references.

**Comment by dbaeumer** [comment] 2015-01-15 14:11
@mhegazy: throwing an error in this scenario might be confusing and non intuitive as well. And I think there is a real use case. For example sub components are typically nested into its parent component.

I see the following possible solutions:

1. we compile the subdirectory by calling tsc with the corresponding config file. If we go down that path then we will need to support 'project dependencies' as well since a tsc call might trigger another tsc call. This might not be as bad as it sounds since through the _references.ts file the builder already has some ordering notation.

2. we ignore these subdirectories and maybe warn about it. If a developer wants to build such a structure then he needs to use another tool (jake, gulp, make, ...) to call tsc with the various config files in the right order.  

I am leaning more towards solution 2. Solution 1 might turn the config support into its own build/make system.

And I would like to pass the config file directly to the tsc compiler as well. Something like tsc @mydirectory\tsc.json

**Comment by fdecampredon** [comment] 2015-01-15 15:11
There has been work for specifying typescript configuration files, see: 
* https://github.com/TypeStrong/tsproj
* https://github.com/fdecampredon/brackets-typescript/#configuration

It would be great to have typescript directly support this kind of mechanism, but it would be a good idea in my point of view to be compatible with those files, or at least to achieve feature parity. 

Especially, I have not seen anything about multiple compilation target/project in a single file which have proved to be a great feature of those project.

**Comment by basarat** [comment] 2015-01-16 02:53
> Especially, I have not seen anything about multiple compilation target/project in a single file which have proved to be a great feature of those project.

I think it does solve this problem:

```ts
app/
    .tsconfig  // compile with amd, outDir : ../appOut
    a.ts
    b.ts
test/
    .tsconfig // compile with commonjs, outDir: ../testOut
    c,ts // adds a /// <references> to a.ts
    d.ts
```

I'd rather have this solution than to maintain my own monster : https://github.com/TypeStrong/tsproj#configuration-file-format. I like it :+1: Thanks guys! now users can just do `tsc --watch`!

**Comment by fdecampredon** [comment] 2015-01-16 07:01
@basarat  honestly it does not solves all the problem for example with [jest](https://facebook.github.io/jest/), projects look like that : 

```
app/
  foo
    __test__
       a-test.ts
       b-test.ts
    a.ts
    b.ts
  bar
    __test__
      c-test.ts
      d-test.ts
   c.ts
   d.ts
```
without a globing system and multiple compilation target described in the same file you won't be able to compile test separately, and there is a lot of other case that we could talk about.

Globing and multiple compilation target described in a same file is the way used by pretty much all the build tools, why would typescript go a different way with a file per folder system ?

**Comment by basarat** [comment] 2015-01-16 10:06
> honestly it does not solve all the problems 

I agree. 

> Globing and multiple compilation target described in a same file is the way used by pretty much all the build tools, why would typescript go a different way with a file per folder system

I agree that this is a bad idea and the team should reconsider

**Comment by Arnavion** [comment] 2015-01-16 10:25
@fdecampredon @basarat Are you suggesting to have something like a list of filenames / globs and then have a compiler options dictionary that applies only to that list? And then have multiple of these in the same file that you can put in the root of the project?

Can you give an example what it would like? I'm guessing something like

```javascript
{ "options": [
    ["foo/*.ts", "bar/*.ts", {
        /* options for source files */
        "compilerOptions": {
            /* ... */
        }
    }],
    ["foo/__test__/*.ts", "bar/__test__/*.ts", {
        /* options for test files */
        "compilerOptions": {
            /* ... */
        }
    }],
]}
```

**Comment by fdecampredon** [comment] 2015-01-16 10:44
Personaly in brackets-typescript I use something similar to grunt : 

For a single compilation target
```json
{
    "target": "ES5",
    "module": "AMD",
    "noImplicitAny": true,
    "sources" : [
        "src/declarations/**/*.ts",
        "src/main/**/*.ts"
    ]
}
```

For multiple one: 
```json
{
  "target": "ES5",
  "module": "AMD",
  "noImplicitAny": true,
  "projects" : {
      "project1": {
           "sources": [
                "project1/src/**/*.ts"
            ]
       },
       "project2": {
            "sources": [
                    "project2/src/**/*.ts"
             ],
             "target": "es3"
        }
   }
}
```
but any format is good for me if allows me to have a fine controls on what is a part of the project (glob), a way to describe multiple compilation target.

**Comment by dbaeumer** [comment] 2015-01-16 13:30
@fdecampredon: for me the question is whether tsconfig.json is a build system or a configuration for the tsc compiler. From what I read so far and from looking at the pull request https://github.com/Microsoft/TypeScript/pull/1692#issuecomment-70247472 it looks like the second. The advantage of this is that everyone can still use its preferred build system when building more than one TS component.

**Comment by fdecampredon** [comment] 2015-01-16 13:55
@dbaeumer The problem is that if a 'tsconfig.json' is adopted, it will become the de facto standard for typescript project build configuration, independently of the original purpose and scope of the feature.
It would kill the competition and I'm not sure it would benefit in anyway the tooling around typescript. 

I seriously would prefer that to never land in typescript than having a solution with limited/incomplete features set. I honestly hope that the team will reconsider.

**Comment by Arnavion** [comment] 2015-01-16 22:34
@fdecampredon So with your multiple targets example, if I run `tsc` from the root of the directory (where the project file is), what should happen? The current compiler can only use one set of compiler options per invocation (same as every other language compiler), so it'd have to spawn two tsc instances - one for project1 (default configuration) and one for project2 (default configuration plus override target to ES3).

I agree with @dbaeumer (and Ander's comment in his PR) that this requires changing tsc to be a compiler + build system instead of a compiler, and that it's better left to specialized build tools like grunt or brackets. I think it's fine for the project file to remain a shorthand for the compiler options within a particular directory, and for the compiler to remain a compiler.

**Comment by fdecampredon** [comment] 2015-01-17 10:40
@Arnavion since project are named we could simply invoke : 
```
tsc --project project1
```

**Comment by Arnavion** [comment] 2015-01-17 19:34
@fdecampredon You missed my question. What would happen if I ran just `tsc` at the root?

**Comment by fdecampredon** [comment] 2015-01-17 20:12
nothing without a '--project '  option it would simply display help.

**Comment by Arnavion** [comment] 2015-01-17 20:50
So it's the same as the current multiple files implementation, except that it's mashed together into one big file? I guess it allows inheritance of common compiler options, but otherwise it seems to have no benefit. If anything, it means large projects or group of projects belonging to more than one team will always require editing a single file even for the most nested project.

If inheritance of compiler options is the only reason for the single-file approach, I think we can add it to the current multiple-file approach as well using some kind of import feature. That is how other build systems (cmake, autotools, etc.) also work.

**Comment by basarat** [comment] 2015-01-20 03:57
> If inheritance of compiler options is the only reason for the single-file approach, 

No. This is also to have a way of specifying single file -> multiple compile targets.

**Comment by basarat** [comment] 2015-01-20 04:00
But I am honestly okay with this. I can see myself expanding on this to support the kind of things I want to support. I agree that a single instance of `tsc` only has a single instance of `program` and therefore can only handle a *single* project. So this is a nice thing to be implemented by native TypeScript.

**Comment by ahejlsberg** [comment] 2015-01-21 01:34
Closed in #1692.

**Closed by ahejlsberg** 2015-01-21 01:34 UTC
Labels: In Discussion, Suggestion

**Comment by johnnyreilly** [comment] 2015-02-27 12:06
Hey @mhegazy (or whoever else might know),

Somehow I managed to miss all the tsconfig excitement!  I've been reading through and I wondered what the implications ended up being for Visual Studio.  Based on my initial impressions it looks like tsconfig may deal with some of the implicit referencing issues discussed [here](https://github.com/Microsoft/TypeScript/issues/1066).  

My particular interest is leveling the playing field between using TypeScript inside VS and outside (in WebStorm / Atom etc).  My sincere hope is that the release of this feature will do just that! :fireworks: :tada: 

Would you be able to clarify what the likely impact will be for Visual Studio or is that not yet known?  My vote (it may be too late) would be to go with what @danquirk has to say:

> You're guaranteed to experience pain if you have 2 distinct 'project files' but the only kind of 'project file' we could guarantee works everywhere is .tsconfig, so that would need to take precedence.

**Comment by mhegazy** [comment] 2015-02-27 17:43
If you have a .csproj/.vbproj/.jsproj today that is managing your files and build options, then this is not going to affect you.

if however you are in the loose-file world, and you use /// references to pull in your files, and you manage your buid using a separate tool (e.g. grunt, gulp, make, jake ..etc..) then this should work nicely,

you will need to add tsconfig.json for every "project" you use, and the compiler and VS will understand that and load your files and your configuration options. then you would wire your build system to use the tsconfig and you have one place to host your build/editing configurations for the project.

**Comment by johnnyreilly** [comment] 2015-02-27 18:00
Great - so if you create a tsconfig.json in a project that currently uses csproj to drive compilation options then VS will switch to using the tsconfig and ignore the csproj?

**Comment by mhegazy** [comment] 2015-02-27 18:29
So this is all my expectations. we have not added the tsconfig support in VS yet (though we should be able to get it in by the next release); so more details would be available after this has been implemented :). The way i would envision it, is that if you have a project file already (.csproj for instance) tsconfig is ignored. The problem with two files is that there are duplication and maintenance overhead, so i would highly recommend not doing that.

My recommendation here would be to see how you are building, if you are using MSBuild, and you have your .*proj wired already, i would stay with that. if you are using other build tools, i would switch to tsconfig, and remove your project. if you still want to keep the project as a convenient way to load all files,  I would add something like  
```XML
<Compile Include="**\*.ts" />
``` 
to include all .ts files in your folder, and I would just use the 
```XML
<TypeScriptEnabled>false</TypeScriptEnabled>
```
to tell the language service that your project is not really a typescript project.

**Comment by johnnyreilly** [comment] 2015-02-28 07:12
Hey @mhegazy,

Thanks for your thoughts.  This is my ten cents: :pound: :smile:

I have to say that I'd really like for the `tsconfig.json` approach to be more of the default way to use TypeScript inside Visual Studio.  Obviously the project approach currently used will need to be supported in an ongoing fashion for backwards compatibility.  That said I think that `tsconfig.json` is a massive step in the right direction and its use should be encouraged as much as possible.  I've a couple of reasons:

1. I'm fairly passionate about having a unified coding experience when working with TypeScript across IDEs / text editors.  ie not one experience in Visual Studio and another elsewhere. `tsconfig.json` enables exactly that which is marvellous.
2. Given the changes coming with asp.net 5 to use `project.json` etc it seems a logical next step to move to using `tsconfig.json` as the standard.

I've just recently been trying out the [Atom TypeScript](https://github.com/TypeStrong/atom-typescript/) plugin (mostly the work of @basarat I believe) and it is fantastic.  This gave me an opportunity to use `tsconfig.json` in a project and I found it very simple, straightforward and powerful.  I think it would be a missed opportunity if Visual Studio doesn't encourage `tsconfig.json` to be the default.  

I might be reading what you're saying wrong but it sounds like you're suggesting `tsconfig.json` should be supported for those that want to use it but not pushed as the default way to use it in VS?  Did I understand you correctly?

Also I fear that 

```
<TypeScriptEnabled>false</TypeScriptEnabled>
```

is a little known option (with a name that unfortunately suggests that if you select it you're turning off TypeScript entirely :sob:). If this is what you will need to do to start using `tsconfig.json` in Visual Studio then people may not know about it or may be confused.  They may miss out on `tsconfig.json` as a result.

**Comment by mhegazy** [comment] 2015-02-28 13:01
I would be open to suggestions. to me tsconfig.json is an alternate way to express project structure, if you already have an msbuild project, then there is no need for another mean.

**Comment by basarat** [comment] 2015-03-01 06:19
> if you already have an msbuild project, then there is no need for another mean

agreed. But if a user has a tsconfig.json, it should be an indication of *maybe the team uses other editors as well* and perhaps VS should move to tsconfig as well?

**Comment by johnnyreilly** [comment] 2015-03-01 09:32
> to me tsconfig.json is an alternate way to express project structure

Agreed - however it's more powerful and may solve a number of edge cases that I (and I suspect others) currently experience.  For me the killer feature of `tsconfig.json` is that It allows fine grained control over building compilation context. I believe that having multiple compilation contexts within a project is actually a fairly common requirement and one reason why I'd really like Visual Studio to tend in the direction of favouring using `tsconfig.json` rather than the current approach.

Perhaps I could best illustrate this by talking about a pet project of my own and what I think using `tsconfig.json` could bring to the party.

The [project](https://github.com/johnnyreilly/proverb-offline) is an ASP.Net project built using AngularJS.  It uses the DefinitelyTyped AngularJS typings pulled in from [NuGet](http://www.nuget.org/packages/angularjs.TypeScript.DefinitelyTyped/).  

##### Excluding test libraries from the application compilation context

The AngularJS typings ship with [angular-mocks.d.ts](https://github.com/johnnyreilly/proverb-offline/blob/master/Proverb.Web/Scripts/typings/angularjs/angular-mocks.d.ts) which is for used for writing unit tests.  Due to implicit referencing `angular-mocks.d.ts` is part of the compilation context when I'm editing application TypeScript code. **Ideally it wouldn't be.**  When that code is run there is no angular-mocks to rely upon.  So ideally it shouldn't be part of the compilation context.  

`tsconfig.json` makes it possible to remedy the situation by allowing us to drop a `tsconfig.json` in the `app` folder which excludes `angular-mocks.d.ts` from the compilation context:

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "",
        "declaration": false,
        "noImplicitAny": true,
        "removeComments": false,
        "noLib": false
    },
    "filesGlob": [
        "./**/*.ts",
        "../scripts/typings/**/*.ts",
        "!../scripts/typings/angularjs/angular-mocks.d.ts"
    ],
    "files": [
        // generated from filesGlob
    ]
}
```

##### Having a test compilation context

If we wanted to have a separate `tests` folder to contain our unit tests we could have a separate `tsconfig.json` in the root of that folder would facilitate this.  It would also allow us separate our mocha / Jasmine etc typings from the application compilation context as well as allowing us to include `angular-mocks.d.ts` as part of our compilation context (as here, writing tests, it completely makes sense).

So when coding our unit tests we get the mocha / jasmine typings etc but when coding our application code we do not.

##### Preventing the implicit referencing / build task bust-up

Proverb has a Gulp task that, in debug mode, takes the TypeScript / JavaScript in the `app` folder and deploys it to a `build/debug` folder.

Presently this takes us into "workaround" territory because of implicit referencing.  Because Visual Studio takes all the TypeScript files in a project and uses them to build compilation context I have to have the following setting my [csproj](https://github.com/johnnyreilly/proverb-offline/blob/master/Proverb.Web/Proverb.Web.csproj#L510-L515):

```
  <Target Name="AfterBuild">
    <ItemGroup>
      <!-- what ever is in the build folder should be included in the project -->
      <Content Include="build\**\*.*" />
    </ItemGroup>
  </Target>
```

This only includes the content of the gulp task *after* the build has taken place.  This means that the implicit referencing issue does cause me a problem at build time.  It feels like a bit of a hack but it works pretty much.  As the screenshot below suggests the debug experience still has some `Cannot find name` reference issues of its own:

![screenshot 2015-03-01 08 09 45](https://cloud.githubusercontent.com/assets/1010525/6429932/6ad42aba-bfea-11e4-9e76-660cf3cd1853.png)

If we had `tsconfig.json` controlling compilation context then the `AfterBuild` hack hopefully shouldn't be necessary.  I'm not sure if the "cannot find name" issue might be solve-able by serving up a `tsconfig.json` or not - but maybe.

----------------

I'm uncertain what to suggest as the best way to add `tsconfig.json` to the Visual Studio tooling but I'd really like it to be "first class" support if possible.  I think catering for multiple compilation contexts within a project is a genuine requirement.  If I read it right I think your comment:

> Perhaps I would add something like
> 
> ```
> <Compile Include="**\*.ts" />
> ```
> 
> to include all .ts files in your folder, and I would just use the
> 
> ```
> <TypeScriptEnabled>false</TypeScriptEnabled>
> ```
> to tell the language service that your project is not really a typescript project.

would probably give the support required.  I understand from the conversation [here](https://github.com/Microsoft/TypeScript/issues/1066#issuecomment-63727612) that  `<TypeScriptEnabled>false</TypeScriptEnabled>` roughly speaking functions as a way to deactivate implicit referencing in a project.

But as I've mentioned the name `<TypeScriptEnabled>false</TypeScriptEnabled>` is a little confusing and it so, unless well documented, I can imagine this hurting adoption.

I know when you first add a TS file to a project in VS you get a prompt which asks you if you'd like to set up your project for TypeScript.  Ideally when you say "yes" to that I'd quite like Visual Studio to add a default `tsconfig.json` to the root folder of the project and perhaps make the changes to the project you were suggesting as well.  That way people are working with `tsconfig.json` right from the off.  Existing projects could be migrated by hand if people felt the need.

-----------------------

PS I've just spent a night tending a baby that will not sleep, that has a rash as well as a penchant for crying and so apologies if this doesn't make as much sense as it might.  I hope it makes sense but in the bleary dawn I can't be too sure. :sleepy: 

PPS If you haven't had a go already then I heartily recommend giving atom-typescript a whirl for a feel of how nice `tsconfig.json` can make life.

**Comment by NoelAbrahams** [comment] 2015-03-01 11:15
@mhegazy, 

> I would be open to suggestions. to me tsconfig.json is an alternate way to express project structure, if you already have an msbuild project, then there is no need for another.

This may not be entirely correct. I feel that `tsconfig` also solves `///reference` problem.

Some people may not see `///reference` as a problem, but the fact is it is a pernicious anti-pattern, especially in large projects. The problem arises because a `///reference` can create links between any individual source file to any other file (or group of files) across the entire solution. And once this link is established the whole idea of having projects in Visual Studio becomes unstable.

Of course there are best practices of have a `_reference.ts` file and so on, but there is no way to enforce that.

With `.tsconfig` one can eliminate `///reference` altogether and have much nicer project encapsulation.

My suggestion is that in Visual Studio instead of 

> The way i would envision it, is that if you have a project file already (.csproj for instance) tsconfig is ignored

We do it the other way round: If a `.tsconfig` file exists in the project root then the `.csproj` is ignored altogether.

**Comment by johnnyreilly** [comment] 2015-03-01 11:35
> If a .tsconfig file exists in the project root then the .csproj is ignored altogether.

+1 to that.

**Comment by DickvdBrink** [comment] 2015-03-02 08:01
In my opinion, if you want to use the csproj open that one and if you want the tsconfig solution, just open a .ts file and it will start using the .tsconfig file if it is in the same or parent directory (at least if I understood this correctly).

**Comment by basarat** [comment] 2015-03-02 08:21
My strongest opinion is "make it easier to use `tsconfig` from VS project properties". 

A checkbox like "use tsconfig.json to track TypeScript project properties" would be awesome.

**Comment by NoelAbrahams** [comment] 2015-03-02 09:22
@DickvdBrink,

I don't think we can do away with `.csproj`. When there are multiple projects how would we include them in a Visual Studio solution? We could have one project and simply list the rest as folders, but the project infrastructure provides a number of useful features like

* Right-click on a project and build that project.
* Context sensitive add/remove files.
* Add inter project dependencies.
* Run pre-build/post-build tasks.
* Functionality provided by NTVS project types (npm UI, right-click debug web service...) 

This kind of usability is indispensable within Visual Studio.

**Comment by NoelAbrahams** [comment] 2015-03-02 10:16
I've opened a couple of feature requests #2180 #2181.

If those features are implemented then we would not need to use `.tsconfig`.

**Comment by basarat** [comment] 2015-03-04 23:39
Just FYI (you might already know) I found that you can create a `.something` file on windows explorer by actually creating a `.something.` file : http://www.basarat.com/2015/03/create-gitignore-file-on-windows.html :heart:

**Comment by ToddThomson** [comment] 2015-03-27 00:27
It seems that this feature does not play well with typescript compiler gulp plugins. It looks like a vinyl adaptor for the tsconfig.json project file will be needed to provide the src stream.

**Comment by luboid** [comment] 2015-05-03 12:45
Can I use it with VS Web Site, if not is there any plans for implemtation

**Comment by mhegazy** [comment] 2015-05-03 23:21
@luboid this is already in the works; tsconfig in vs should be available in the next release.

**Comment by asgerhallas** [comment] 2015-06-05 07:14
@mhegazy is that 1.5.2? Or later? Can't seem to find any issue describing this change.

:)

**Comment by mhegazy** [comment] 2015-06-05 22:21
@asgerhallas this is in 1.5-alpha and 1.5-beta and should be in 1.5.2 as well.

**Comment by asgerhallas** [comment] 2015-06-06 06:26
@mhegazy I might have misunderstood the meaning of VS support then. When I include a tsconfig.json in my project, I thought it would take precedence over the VS-project settings. But compiling from within VS seems to ignore the tsconfig file (compiling from command line works fine). Is that the intent, or am I missing something?

**Comment by luboid** [comment] 2015-06-06 07:43
@mhegazy I have also problem with understand how it works, I have create repo with my try

https://github.com/luboid/vs-typescript-website

I am using VS 2015 with https://visualstudiogallery.msdn.microsoft.com/3e5ba71c-abea-4d00-b81b-a62de3ad3d53

https://github.com/luboid/vs-typescript-website/tree/master/TypeScript 

this is what contains 

C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript

when I save file changes nothing happen, I need to go to Tools -> Options -> Text Editor - TypeScript -> Project to enable "Automatically coompile ..." and JS file is generated but noting else, no map, no d.ts

I give it try with VS 2013 but with no success

**Comment by mhegazy** [comment] 2015-06-06 19:10
@asgerhallas and @luboid VS currently does not look at tsconfig.json. so weather you have the file in the directory or not, nothing changes. it still behaves as if you are calling builds passing all files on the commandline. the support should be added in the next public release of VS2015.

The reason is the TypeScript VS plugin in ships with VS releases, and VS has a ship scheduled that we, the TypeScript team, have no control over, and it has longer stabilization periods, which leads to some features shipping out of sync.

**Comment by asgerhallas** [comment] 2015-06-08 13:22
@mhegazy ah, I see. Thanks for the explanation, I'll await next VS release then :)

**Comment by matthew-dean** [comment] 2015-07-30 20:48
Is there any way to merge the efforts of various compilers, transpilers, and other command-line engines into adopting a single config.json format, somewhat like package.json?

Other libraries like Less have had a similar discussion. https://github.com/less/less.js/issues/1893  Why don't all of our communities collaborate and come up with one format? That way we don't litter the root directories of projects with a different config file for every type of transpiled / precompiled / pre- or post-processed language?

**Comment by andrewvarga** [comment] 2015-08-05 17:05
Now that there's a config file for the compiler, would it be possible to squeeze this feature in it somehow, which would be immensely useful:
https://github.com/Microsoft/TypeScript/issues/293

**Comment by mhegazy** [comment] 2015-08-05 17:40
@andrewvarga i believe this should be covered by #2338, we need a new mapping format to map an import name to a path.

**Comment by andrewvarga** [comment] 2015-08-05 22:18
@mhegazy Nice, I didn't catch that issue. Would that work for ///<reference path=""/> type of references too ?

**Comment by mhegazy** [comment] 2015-08-05 22:31
@andrewvarga this is only for modules as it follows the same runtime resolution process based on your module system (i.e. amd/commonjs). we could not come up with a meaningful /// reference resolution analogy.

**Comment by mikemorton** [comment] 2015-09-04 14:30
"the support should be added in the next public release of VS2015."

Is there any word on if this has been officially added?  If so, which version number should I be looking for?

**Comment by mhegazy** [comment] 2015-09-04 16:57
@mikemorton VS2015 has tsconfig support built in. here is how you get VS2015: https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx

**Comment by Bobris** [comment] 2015-09-17 08:26
I don't understand how to open tsconfig.json as solution in Visual Studio. Or what type of project I need to use for example if developing node.js application/module (and I don't want to duplicate list of ts files in csproj)...
In Atom-Typescript this not problem just open directory with tsconfig.json and everything magically works.

**Comment by mhegazy** [comment] 2015-09-17 16:53
@Bobris, tsconfig does not work in a project. the project file with its configuration (accessible through project properties) is considered the source of truth in a project context.
if you want to use tsconfig, just close your project, and open the file in VS, it will walk up and find the tsconfig that matches it, and will load all files referenced by your tsconfig, just like you would do with Atom, sublime, code, etc..

**Comment by Bobris** [comment] 2015-09-20 22:33
@mhegazy Yes, works, need to try for longer time. Now what is left to implement is support for "filesGlob".

**Comment by SetTrend** [comment] 2015-12-07 21:40
Does VS 2015 honour to have more than one single tsconfig file so we can have one config for a JS library project and another for the test files in the same .proj?

**Comment by mhegazy** [comment] 2015-12-07 23:05
@SetTrend, this is tracked by #4714

**Comment by SetTrend** [comment] 2015-12-07 23:09
@mhegazy : Excellent :+1:
