### ISSUE TITLE
Variable type is evaluated as never when it's not

### ISSUE THREAD

**Issue by alexey-pelykh** [microsoft/TypeScript#47241] opened 2021-12-24 13:11 UTC
# Bug Report

```
let data = [1,2,3];
let value : number | undefined = undefined;
data.forEach(x => value = x);
if (value !== undefined) {
    console.log(value);
}
```

results in `3` being printed out yet:
![image](https://user-images.githubusercontent.com/345102/147354986-f5152837-d0a3-443e-ad3d-7096eff54808.png)

At the same time if

```
let value : number | undefined = undefined;
```

is modified to

```
let value : number | undefined;
```

then `value` is resolved as `number` correctly:

![image](https://user-images.githubusercontent.com/345102/147355086-21d2df48-7351-423b-8cc8-f0d9a9ba5594.png)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.9.7#code/DYUwLgBAJghmMQLwQNoEYA0AmDBmAugNwBQokAbjMAK4gQBcEAdtQLYBGIAThAD4TUmUEADMAlkxBQkAoaIlSSseADoRAey4BRGAGMAFgAoAHkgB8ESjTrJjAShJiREQ1doQAhImSDh4yVB2EADexBDhELrqTADO6qAqwOoA5q5UtA4QAPRZlul0YACeAA50YjEQAESS5NyVxAC+QA)

### 🙂 Expected behavior

Variable type is resolved correctly

**Comment by MartinJohns** [comment] 2021-12-24 14:22
Another duplicate of #9998.

**Closed** 2022-01-03 16:39 UTC
Labels: Duplicate
