### ISSUE TITLE
Suggestion: Generic generics / Deferred generics

### ISSUE THREAD

**Issue by krryan** [Microsoft/TypeScript#21605] opened 2018-02-03 19:22 UTC
First, I have a suspicion this is a duplicate and I apologize for that. I have searched and found nothing, quite possibly because I don't really know what to call this (and "generic generic" doesn't search very well).

Anyway, I have a situation wherein I would like to take a generic function as a callback, but need to talk about its return value while it is still generic (not resolved with some particular type).

```ts
interface SomeGenericThingA<T> { foo: T; }
interface SomeGenericThingB<T> { bar: T; }
type SomeGenericThingUnion<T> = SomeGenericThingA<T> | SomeGenericThingB<T>;

interface SomeOtherThingA { baz: string; }
interface SomeOtherThingB { bat: string; }
type SomeOtherThingUnion = SomeOtherThingA | SomeOtherThingB;

function makeGenericThingUtility<
    WithValue extends <T>(value: T) => SomeGenericThingUnion<T>,
    Without extends SomeOtherThingUnion
>(
    callback: WithValue,
    fallback: Without
) {
    return {
        withValue: callback,
        withPossibleValue: <T>(possibleValue: T | undefined) => {
            return possibleValue !== undefined ? callback(possibleValue) : fallback;
        },
    };
}

declare const possibleString: string | undefined;

declare const callbackForA: <T>(value: T) => SomeGenericThingA<T>;
declare const fallbackForA: SomeOtherThingA;
const utilityForA = makeGenericThingUtility(callbackForA, fallbackForA);

declare function takesSomeA(value: SomeGenericThingA<string> | SomeOtherThingA): void;
takesSomeA(utilityForA.withPossibleValue(possibleString));
//         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
// Argument of type 'SomeOtherThingA | SomeGenericThingA<string> | SomeGenericThingB<string>' is not assignable to parameter of type 'SomeOtherThingA | SomeGenericThingA<string>'.
//   Type 'SomeGenericThingB<string>' is not assignable to type 'SomeOtherThingA | SomeGenericThingA<string>'.
//     Type 'SomeGenericThingB<string>' is not assignable to type 'SomeGenericThingA<string>'.
//       Property 'foo' is missing in type 'SomeGenericThingB<string>'.
```

I can't accept a generic parameter for the return type alone, because then it is not going to capture the `<T>` I need. Attempting to intersect the generic parameter with `<any>` with the union `<T>` doesn't work either:

```ts
function makeGenericThingUtilityExtraParameter<
    Value extends SomeGenericThingUnion<any>,
    WithValue extends <T>(value: T) => Value & SomeGenericThingUnion<T>,
    Without extends SomeOtherThingUnion
>(
    callback: WithValue,
    fallback: Without
) {
    return {
        withValue: callback,
        withPossibleValue: <T>(possibleValue: T | undefined) => {
            return possibleValue !== undefined ? callback(possibleValue) : fallback;
        },
    };
}

declare const callbackForB: <T>(value: T) => SomeGenericThingB<T>;
declare const fallbackForB: SomeOtherThingB;
const utilityForB = makeGenericThingUtilityExtraParameter(callbackForB, fallbackForB);

declare function takesSomeB(value: SomeGenericThingB<string> | SomeOtherThingB): void;
takesSomeB(utilityForB.withPossibleValue(possibleString));
//         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
// Argument of type 'SomeOtherThingB | (SomeGenericThingA<any> & SomeGenericThingA<string>) | (SomeGenericThingB<any> & SomeGenericThingA<string>) | (SomeGenericThingA<any> & SomeGenericThingB<string>) | (SomeGenericThingB<any> & SomeGenericThingB<string>)' is not assignable to parameter of type 'SomeOtherThingB | SomeGenericThingB<string>'.
//   Type 'SomeGenericThingA<any> & SomeGenericThingA<string>' is not assignable to type 'SomeOtherThingB | SomeGenericThingB<string>'.
//     Type 'SomeGenericThingA<any> & SomeGenericThingA<string>' is not assignable to type 'SomeGenericThingB<string>'.
//       Property 'bar' is missing in type 'SomeGenericThingA<any> & SomeGenericThingA<string>'.
```

What I really need here is some way to say something like

```ts
function makeGenericThingUtilityDeferredGeneric<
    Value<T> extends SomeGenericThingUnion<T>,
    Without extends SomeOtherThingUnion
>(
    callback: <T>(value: T) => Value<T>,
    fallback: Without
) {
    return {
        withValue: callback,
        withPossibleValue: <T>(possibleValue: T | undefined): Value<T> | Without => {
            return possibleValue !== undefined ? callback(possibleValue) : fallback;
        },
    };
}
```

but this doesn't exist. I can probably work around this problem soon with the conditional type inference that's being worked on (since it can extract return-type information from the callback function and then specify the return type of `withPossibleValue` better), but that seems an awkward way to express it while the above expresses what is going on quite naturally.

Syntax-wise, the biggest concern I see here is how to actually specify the parameter when calling the function with an explicit parameter. `makeGenericThingUtilityDeferredGeneric(callbackForA, fallbackForA)` would presumably be specified correctly, but if you needed to explicitly specify the generic parameters I'm not sure how you would want to write that. `makeGenericThingUtilityDeferredGeneric<SomeGenericThingA, SomeOtherThingA>(callbackForA, fallbackForA)` seems like the obvious approach on a first pass, but if `SomeGenericThingA` had more parameters than just `T`, and you want to specify the others (and, for reference, this is true of my situation) and leave out `T`, the writing of that gets more awkward. You can't just use `T` because it's not defined in that context, and it's not clear how to introduce it. You could imagine perhaps an initial paramter list, indicating which types are still to come, like `<T>SomeGenericThingC<T, string, number>` (kind of matching how the `T` is introduced in other context on the left of a `extends` or `=` or `(`), but then in the single-parameter case that certainly looks quite strange (`<T>SomeGenericThingA<T>`).

You could potentially try to enforce that explicit indication of generic-generic parameters must have the same number and order of parameters that is expected, and if that's not the case you just make a type for the purpose, e.g.

```ts
type SomeGenericThingCNumberString<T> = SomeGenericThingC<T, number, string>;
makeGenericThingUtilityDeferredGeneric<SomeGenericThingCNumberString, SomeOtherThingC>(callbackForC, fallbackForC);
```

Seems rather awkward though.

**Comment by jcalz** [comment] 2018-02-04 01:05
Looks like a duplicate of #1213.

**Comment by krryan** [comment] 2018-02-04 05:58
Yeah, looks like.

**Closed** 2018-02-20 19:07 UTC
Labels: Duplicate
