### ISSUE TITLE
Type narrowing not work

### ISSUE THREAD

**Issue by nuintun** [microsoft/TypeScript#58795] opened 2024-06-07 04:06 UTC
### 🔎 Search Terms

type narrowing

### 🕗 Version & Regression Information

- This version 5.4.5

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgCpQig3gKGcgawgE8AuZAZzClAHMBuPZYCgGQjhgH5yAjAe34AbDiEb4EAC2BCAJhhA80GCAG0AuowC+OHBAAeAB35QwyGAFcQCMMH4hktCGHZxZdANIkKACiiCwCnJ0TA1kAF5kDQBKcioaEFow3Al7KkJvOOo6MMiNRiYRMwQLKAUwYJUwgB9kK1kIGFAIWQjkf35AgvwAd2kRZB8SsohwZAAyceRh8oA6EUSwSWQAPmQABmjkFPxptLNVSQ5ZdTaZ0bBu3aJiClnDCwpJHyO3WZvoq4lS8rbX2VmUhk8lG4mQOiYGDApQcNwo2l0BmMpnMVhsdgcThcx083gATH4AkFlKFTnl1LFKNlEskmAh9hlblkEkkyVFNLp8EVpj8LpVSchavVGs1WpEOl1OcwYINzmNJjyRuB5qNaEtVhstjtUiB0odjmy5Zcpfg4fdHs9-u8SJ8TYrfpErUC5AowRDev0UENefKpkaVYtlmtNtsmDq9f9DT7jWHGXcHk8XsdrcRbbGjX9k86QWImO72s4YXHtEA

### 💻 Code

```ts
interface Tree {
  key: string;
  isLeaf?: boolean;
  children?: Tree[];
}

export function getLeadingKeys(roots: Tree[] = []): string[] {
  const keys: string[] = [];

  let current: Tree[] | undefined = roots;

  while (current && current.length > 0) {
    const [head] = current;

    keys.push(head.key);

    current = head.children;
  }

  return keys;
}
```

### 🙁 Actual behavior

Type narrowing not work

### 🙂 Expected behavior

Type narrowing working

### Additional information about the issue

![image](https://github.com/microsoft/TypeScript/assets/1730277/90ea6da3-b724-4a3a-a21c-fa348854b9b8)

![image](https://github.com/microsoft/TypeScript/assets/1730277/340f1abf-ef06-4e74-a7bb-f5951c2483df)

![image](https://github.com/microsoft/TypeScript/assets/1730277/ae7b60ca-f862-4567-8990-d15883d529a5)

**Comment by MartinJohns** [comment] 2024-06-07 05:40
This is working as intended / a design limitation. If you search for the error message you will find many duplicates.

**Comment by rotu** [comment] 2024-06-08 05:30
@MartinJohns I'm not sure that's the case and I think this deserves a closer look. If you still think it's a duplicate, can you mention the particular issue it duplicates?

The type of head *can be* inferred. In fact, *an identical loop* typechecks properly in the provided case `getLeadingKeys2`.

Also it typechecks properly if you merely *reassign* `head` in the loop instead of declaring it there.

[Playground Link](https://www.typescriptlang.org/play/?target=99&module=1#code/JYOwLgpgTgZghgYwgAgCpQig3gKGcgawgE8AuZAZzClAHMBuPZYCgGQjhgH5yAjAe34AbDiEb4EAC2BCAJhhA80GCAG0AuowC+OHBAAeAB35QwyGAFcQCMMH4hktCGHZxZdANIkKAZgAUUIJgFOTomBrIALzIGgCU5FQ0ILQRuBL2VITeCdR0EdEajEwiZggWUApgoSoRAD7IVrIQMKAQslHIgfzB4sglyJIcskX4AO7SIsh+ZRUQ4MgAZAvIM5UAdCLJYJLIAHzIAAyxyGn4U6qDbuodq3NgsSNnRMQUa4YWFJJ+l7Jrzw+6M4rcqVDo-NZSGTyOa9HRMDBgcoOZ4UbQ4IA)

```ts
interface Tree {
  key: string;
  isLeaf?: boolean;
  children?: Tree[];
}

export function getLeadingKeys(roots: Tree[] = []): string[] {
  const keys: string[] = [];

  let current: Tree[] | undefined = roots;
  let head;

  while (current && current.length > 0) {
    ([head] = current);

    keys.push(head.key);

    current = head.children;
  }

  return keys;
}
```

**Comment by MartinJohns** [comment] 2024-06-08 09:11
The inferred type of `head` depends on `current`. The inferred type of `current` (after assignment) depends on the type of `head`. So `head` indirectly references itself in it's initializer, as the error tells you.

Your new playground link works because `head` has no type annotation and is typed as `any`, so no implicit `any` is introduced by the initialization.

**Comment by rotu** [comment] 2024-06-08 16:09
> The inferred type of `current` (after assignment) depends on the type of `head`.

This is the part I don't grok. `current` *has* a type annotation - its type is never inferred.

If I add a straightforward statement like `current = 42;` in the loop, that causes a change in the type of `current` - instead the compiler complains about an invalid assignment.

> Your new playground link works because `head` has no type annotation and is typed as `any`, so no implicit `any` is introduced by the initialization.

You seem to suggest that an implicit `any` is introduced by `const [head] = current` *even though* `current` was declared with a type annotation.

But perhaps my example was more complicated than helpful. How, in the original second example, does manually unrolling the `while` loop by one *prevent* the issue?

```ts
export function getLeadingKeys2(roots: Tree[] = []): string[] {
  const keys: string[] = [];

  let current: Tree[] | undefined = roots;

  if (current && current.length > 0) {
    const [head] = current;

    keys.push(head.key);

    current = head.children;
  }

  while (current && current.length > 0) {
    const [head] = current;

    keys.push(head.key);

    current = head.children;
  }

  return keys;
}
```

**Comment by AlQubaiisi** [comment] 2024-06-08 16:16
> > يعتمد النوع المستنبط من (بعد التعيين) على نوع .`current``head`
> 
> هذا هو الجزء الذي لا أتحسبه. _يحتوي على_ تعليق توضيحي للنوع - لا يتم الاستدلال على نوعه أبدا.`current`
> 
> إذا أضفت عبارة مباشرة كما هو الحال في الحلقة ، فإن ذلك يتسبب في تغيير نوع - بدلا من ذلك ، يشكو المترجم من مهمة غير صالحة.`current = 42;``current`
> 
> > يعمل رابط الملعب الجديد الخاص بك لأنه لا يحتوي على تعليق توضيحي من النوع ويتم كتابته ك ، لذلك لا يتم تقديم أي ضمني بواسطة التهيئة.`head``any``any`
> 
> يبدو أنك تشير إلى أنه يتم تقديم ضمني بواسطة _على الرغم من_ الإعلان عنه بتعليق توضيحي من النوع.`any``const [head] = current``current`
> 
> ولكن ربما كان المثال الخاص بي أكثر تعقيدا من كونه مفيدا. كيف ، في المثال الثاني الأصلي ، هل يؤدي إلغاء الحلقة يدويا بواسطة واحد _إلى منع_ المشكلة؟`while`
> 
> ```ts
> export function getLeadingKeys2(roots: Tree[] = []): string[] {
>   const keys: string[] = [];
> 
>   let current: Tree[] | undefined = roots;
> 
>   if (current && current.length > 0) {
>     const [head] = current;
> 
>     keys.push(head.key);
> 
>     current = head.children;
>   }
> 
>   while (current && current.length > 0) {
>     const [head] = current;
> 
>     keys.push(head.key);
> 
>     current = head.children;
>   }
> 
>   return keys;
> }
> ```

interface Tree {
  key: string;
  isLeaf?: boolean;
  children?: Tree[];
}

export function getLeadingKeys(roots: Tree[] = []): string[] {
  const keys: string[] = [];

  let current: Tree[] | undefined = roots;
  let head;

  while (current && current.length > 0) {
    ([head] = current);

    keys.push(head.key);

    current = head.children;
  }

  return keys;
}

**Comment by MartinJohns** [comment] 2024-06-08 17:35
> This is the part I don't grok. `current` _has_ a type annotation - its type is never inferred.

Variables are narrowed upon assignment. The type depends on the expression. In your example the type depends on `head`.

**Comment by rotu** [comment] 2024-06-08 19:06
> Variables are narrowed upon assignment. The type depends on the expression. In your example the type depends on `head`.

Okay. I'm not 100% on what you're saying, but I *think* you're saying that *inside the loop body*, `current` has a different type. And this different type is circular. This seems supported by the fact that, replacing the annotation on `current` with one *not* narrowed by the loop condition (`Tree[]` instead of `Tree[] | undefined`) causes the code again to pass. [Playground Link](https://www.typescriptlang.org/play/?&q=5#code/JYOwLgpgTgZghgYwgAgCpQig3gKGcgawgE8AuZAZzClAHMBuPZYCgGQjhgH5yAjAe34AbDiEb4EAC2BCAJhhA80GCAG0AuowC+OHBAAeAB35QwyGAFcQCMMH4hktCGHZxZdANIkKAFgAUUIJgFOTomBrIALzIGgCU5FQ0ILQRuBL2VITeCdR0EdEajEwiZggWUApgoSr5yIH8wUX4AO7SIsh+ZRUQ4MgAZH3IXZUAdCLJYJLIAHzIAAyxyGn4QxlmqpIcsupRQ+WVTStExBQjhhYUkn6bbiPHsYcS+z1m0TeyI1Iy8j3IXFwxTRMHRMDBgcoOY4UbRAA).

This still doesn't explain why the declaration of `head` matters. When declared outside the loop, the post-assignment type of `head` is *just as circular* as when `head` is both declared and assigned inside the loop.

**Comment by MartinJohns** [comment] 2024-06-09 09:47
> I'm not 100% on what you're saying, but I _think_ you're saying that _inside the loop body_, `current` has a different type.

Consider this example:

```typescript
let v: number | undefined;
v = 123;
```

Right after the assignment, is the type of `v` `number | undefined` like the type annotation, or has it been narrowed to `number` based on the type of the assigned expression (`123`, aka `number`)?

When your type is not a union anymore this narrowing does not happen, as it's always the same type.

> This still doesn't explain why the declaration of `head` matters.

I'm not sure what you mean. Either you omit the type annotation, in which case the type of `head` is simply `any` (as mentioned before), or you have an explicit type annotation , in which case the error does not apply anymore (it mentions adding a type annotation).

**Comment by rotu** [comment] 2024-06-10 19:30
> Consider this example:
> 
> ```ts
> let v: number | undefined;
> v = 123;
> ```
> 
> Right after the assignment, is the type of `v` `number | undefined` like the type annotation, or has it been narrowed to `number` based on the type of the assigned expression (`123`, aka `number`)?

After the assignment, `v` has type `number`. But `v` still "remembers" its `number|undefined` annotation, as shown when you assign `any` to it.

```ts
let v: number | undefined;
v = 123;
void v
//   ^? let v: number
v = (null as any)
void v
//   ^? let v: number | undefined
```

> When your type is not a union anymore this narrowing does not happen, as it's always the same type.
> 
> > This still doesn't explain why the declaration of `head` matters.
> 
> I'm not sure what you mean.

What I mean is that `let head; ...; const [head] = ...` declares an identifier without declaring its type and yet the compiler infers the type (more specific than the implicit `any`) and provides contextual help. This is the same developer experience I'd expect with `const [head] = ...`.

![image](https://github.com/microsoft/TypeScript/assets/119948/551c20cb-f89a-471f-9db1-735d5a4b9a66)

> Either you omit the type annotation, in which case the type of `head` is simply `any` (as mentioned before), or you have an explicit type annotation 

That does not match my experience.

With no type annotation, (`let head;`), then after the assignment, intellisense shows `let head: Tree`. Is this considered something other than "type narrowing" (even though the type of `head` is *not* a union type?

With an "explicit `any`" (`let head: any;`), then after assignment, intellisense shows `let head: any`.

> in which case the error does not apply anymore (it mentions adding a type annotation).

Unfortunately, AFAICT, adding a type annotation to `const [head] = ...` is not straightforward (`const [head:Tree] = current`). I'm guessing there's some syntactic issue here, but `const head:Tree = current[0]` *does* work.

Narrowing *does* seem to happen if I declare `head` with the union type `let head: Tree | undefined;`. I *would* expect to see an error again, but I don't!

**Comment by fatcerberus** [comment] 2024-06-12 19:51
> Unfortunately, AFAICT, adding a type annotation to `const [head] = ...` is not straightforward (`const [head:Tree] = current`).

For future reference the way to add a type annotation to a destructuring assignment is

```ts
const [head]: [Tree] = current;
const { foo, bar }: { foo: string, bar: string } = whatever;
```

**Closed** 2024-06-15 01:30 UTC
Labels: Duplicate
