### ISSUE TITLE
problems of using await on async method of super class

### ISSUE THREAD

**Issue by JacobChang** [Microsoft/TypeScript#6169] opened 2015-12-19 03:54 UTC
await does not works on method of super class

    class Animal {
      constructor() {
      }

      async walk() {
        console.log('animal walk')
      }
    }

    class Dog extends Animal {
      constructor() {
        super();
      }

      async walk() {
        await super.walk();
        console.log('dog walk');
      }
    }

I suppose this piece of code should work, but It doesn't, as method walk of Dog will be transformed to

    class Dog extends Animal {
      ...

      walk() {
          return __awaiter(this, void 0, Promise, function* () {
              yield super.walk();
              console.log('dog walk');
          });
      }
    }

but the specification says keyword 'super' is only permitted in a constructor, method call and member accessor in derived class.

**Comment by vladima** [comment] 2015-12-19 05:14
duplicate of #5124

**Closed by vladima** 2015-12-19 05:14 UTC
Labels: Duplicate
