### ISSUE TITLE
JSDoc: support `@implements` tag on class

### ISSUE THREAD

**Issue by darky** [Microsoft/TypeScript#17498] opened 2017-07-28 22:23 UTC
**TypeScript Version:** nightly (2.5.0-dev.20170728)

**Code**

**index.d.ts**
```ts
class AClass {
    method(a: number): number
}
```

**some.js**
```javascript
/** @type {AClass} */
class A {
    method(a) {
        return false;
    }
}
```

**Expected behavior:**

`Type 'false' is not assignable to type 'number'.`

**Actual behavior:**

Not working. Impossible to set type on class.

**Comment by andy-ms** [comment] 2017-07-29 00:54
Maybe you want something like this? (won't work today):
```js
/** @import { I } from "foo.d.ts" */

/** @implements {I} */
class AClass { ... }
```

However, in TS code we don't allow you to omit the parameter types on an override, even if they should be inferrable due to already being declared in the parent; the best link I have on that is https://github.com/Microsoft/TypeScript/issues/2000#issuecomment-245964251.

**Comment by darky** [comment] 2017-07-29 16:45
Yeah, if it resolve problem, would be cool!

**Comment by que-etc** [comment] 2018-06-22 13:19
The Lighhouse team uses a neat [workaround](https://github.com/GoogleChrome/lighthouse/blob/6bf2f45607edce27319acac7e39fa02c705a061d/lighthouse-core/config/config.js#L362) to assert implementation of an interface.

Here is the gist:

``` typescript
// @file: interface.d.ts
export interface MyInterface {
    foo(): string
}

// @file: implementation.js

/** @typedef {import(./interface).MyInterface} MyInterface */

export class MyClass {
    constructor() {
        /**
         * Assert that MyClass correctly implements MyInterface.
         * @type {MyInterface}
         */
        const instance = this;
    }

    /**
     * @returns {number}
     */
    foo() {
        return 42;
    }
}
```

**Comment by sandersn** [comment] 2019-03-13 21:30
Duplicate of #30156, which has a real code example.

**Closed by sandersn** 2019-03-13 21:30 UTC
Labels: Committed, Domain: JSDoc, Domain: JavaScript, Suggestion
