### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by dulmandakh** [Microsoft/TypeScript#19527] opened 2017-10-27 10:24 UTC
**TypeScript Version:**  2.7.0-dev.20171027

**Code**
```ts
const HTTP_PORT = (process.env && process.env.HTTP_PORT) ? parseInt(process.env.HTTP_PORT) : 3000;
```
or

```ts
const HTTP_PORT = (process.env && typeof process.env.HTTP_PORT === 'string') ? parseInt(process.env.HTTP_PORT) : 3000;
```

**Expected behavior:**
There shouldn't be a compile error

**Actual behavior:**
error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

**Comment by aluanhaddad** [comment] 2017-10-27 11:33
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/17960

**Closed** 2017-11-10 23:17 UTC
Labels: Duplicate
