### ISSUE TITLE
enum index { 	[k: EnumA]: number } TS1023: An index signature parameter type must be 'string' or 'number'.

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#31624] opened 2019-05-28 18:05 UTC
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
enum EnumA { a = 1 }

interface Interface
{
	[k: EnumA]: number
	// should allow use enum, because enum only allow number and string
}

type T1 = {
	[k in EnumA]: number
}

let a: T1 = {
	[EnumA.a]: 0,
};

let b: T1 = {
	1: 0,
};
```

**Expected behavior:**

> no error, because enum only allow number and string

**Actual behavior:**

> Error: TS1023: An index signature parameter type must be 'string' or 'number'.

**Playground Link:** 

**Related Issues:**

**Comment by jcalz** [comment] 2019-05-28 18:17
Duplicate of #2491.  You can use [mapped types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types) like `Record<EnumA, number>` instead.  Also relevant work in #26797.  Please consider searching before filing bugs (or filling out "search terms" so we know what you tried).

**Comment by bluelovers** [comment] 2019-05-28 21:40
@jcalz 
`Record<T>` is a type, not `interface`

**Comment by jcalz** [comment] 2019-05-29 13:24
```ts
interface Interface extends Record<EnumA, number> {}
```

**Closed** 2019-05-31 18:00 UTC
Labels: Duplicate
