### ISSUE TITLE
the type error checking bug

### ISSUE THREAD

**Issue by KenFront** [microsoft/TypeScript#38619] opened 2020-05-17 05:23 UTC
**TypeScript Version:**  3.9.2

**Expected behavior: the two checked results to update properties of object should be same.

**Actual behavior: there is a type error in way 2, but not in way 1.

**Code**
```ts
interface xxx {
    id: string;
    name: string;
    description?: string;
}

const test = (propName: keyof xxx) => {
    const o: xxx = {
        id: '1',
        name: '1',
        description: '1'
    }
    const o2: xxx = {
        id: '1',
        name: '1',
        description: '1'
    }
    // change property way 1
    const o3 = {
        ...o,
        [propName]: o2[propName]
    }

    // change property way 2
    o[propName] = o2[propName]
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const test = (propName) => {
    const o = {
        id: '1',
        name: '1',
        description: '1'
    };
    const o2 = {
        id: '1',
        name: '1',
        description: '1'
    };
    // change property way 1
    const o3 = Object.assign(Object.assign({}, o), { [propName]: o2[propName] });
    // change property way 2
    o[propName] = o2[propName];
};

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=3.9.2#code/JYOwLgpgTgZghgYwgAgB7uQbwFDL84AEwC5kBnMKUAcwG5d8Q4BbCUiqkOhvQiMhFQAOYYAHsQAfnaUa9AL7ZsCCRWSQ1AXmQAKIVDFCAcizbIA1hACeYmGnQBKZJoB8WHshUg1Y0ulTO7vjBBCTIAOQAjOEANB7BTKykUbHx+HwCwqISydEeisFePgBMfhjaOCH4RLmpVXiJZilx9cgZgsAi4iC1+R4A9P2eABZwXCj6htBgVsgA7nCzkR5FYMhiAMyBlfUAdPtiLfUA2pPGpgC6pGLFpwbnrBd9A0MIo+PIZ9OzC7PFHmI7oYTI9AjcgQ8IE95EA)

**Description:** I am not sure the result for both of them should be correct or not. I just think they should be same.

**Comment by jcalz** [comment] 2020-05-17 20:22
Duplicate of #13948 and #27273

**Closed** 2020-05-20 18:00 UTC
Labels: Duplicate
