### ISSUE TITLE
Array of numbers wrong sort

### ISSUE THREAD

**Issue by demensdeum** [microsoft/TypeScript#58160] opened 2024-04-12 10:58 UTC
### 🔎 Search Terms

sort numbers array

### 🕗 Version & Regression Information

Write array of numbers const numbers: number[] = [16, 1, 0, 9, 100], then sort(), 
Result sort will be:
[16, 1, 0, 9, 100]

Expected:
[0, 1, 9, 16, 100]

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBGCuBbARgUwE4QFxyW9A2gLowC8MBAjAGwA0Ml9ADPQJz2VNNEBQokIADaoAdIJABzABQIUGCCIgh0UKQEo1QA

### 💻 Code

const numbers: number[] = [16, 1, 0, 9, 100]
console.log(numbers.sort())

### 🙁 Actual behavior

Result sort will be:
[16, 1, 0, 9, 100]

### 🙂 Expected behavior

Expected:
[0, 1, 9, 16, 100]

### Additional information about the issue

Suppose to convert to correct array type in JS

**Comment by MartinJohns** [comment] 2024-04-12 11:02
This is working as intended. First of all, this is just how JavaScript works, it's completely unrelated to TypeScript. Secondly, the [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) makes clear that the values are converted to strings and then sorted, when no comparer is provided:

> If omitted, the array elements are converted to strings, then sorted according to each character's Unicode code point value.

**Comment by demensdeum** [comment] 2024-04-12 11:05
@MartinJohns wanted to say that new Float64Array([16, 1, 0, 9, 100]).sort() works correctly

**Comment by MartinJohns** [comment] 2024-04-12 11:09
Yes, different types can behave differently. As [documented](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/sort), when omitting the comparer for `Float64Array`s sort method the values are sorted by their numeric value:

> If omitted, the typed array elements are sorted according to numeric value.

But again, that's just how JavaScript works and completely unrelated to TypeScript.

**Comment by demensdeum** [comment] 2024-04-12 11:16
@MartinJohns
Ok, thnx.
I think it's could be good to transpile to Float64Array or BigInt64Array, like C++ do it with auto deduction.

**Comment by MartinJohns** [comment] 2024-04-12 11:23
That's **explicitly** out of scope for TypeScript. The compiled TypeScript code should behave as-is, just with the types removed. See also: [TypeScript Design Goals](https://github.com/microsoft/TypeScript/wiki/TypeScript-Design-Goals)

**Comment by demensdeum** [comment] 2024-04-12 11:34
1. But isn't JS does not support generics, but TS does?
2. So I guess this is good field to improve in TS, because sorting numbers in lex order is frustrating.

**Comment by MartinJohns** [comment] 2024-04-12 11:42
> 1. But isn't JS does not support generics, but TS does?

Generics only exist at compile time, they're just type information. After compilation anything generic related is completely gone. There's no runtime behavior.

> So I guess this is good field to improve in TS, because sorting numbers in lex order is frustrating.

Again, this is explicitly out of scope. See the document I linked. Just provide a comparer if you want numerical sorting for arrays.

You might also want this ESlint rule: [require-array-sort-compare](https://typescript-eslint.io/rules/require-array-sort-compare/)

**Comment by demensdeum** [comment] 2024-04-12 11:51
> Generics only exist at compile time, they're just type information. After compilation anything generic related is completely gone. There's no runtime behavior.

Same for Float64Array or BigInt64Array auto deduction, it's type information.

> [require-array-sort-compare](https://typescript-eslint.io/rules/require-array-sort-compare/)

Good rule, but I want to be my code DRY as possible, which could be achieved with Float64Array/BigInt64Array types.
With "sort-compare" I would need to write custom comparators everytime with only-numbers array.

**Comment by MartinJohns** [comment] 2024-04-12 11:58
> Same for Float64Array or BigInt64Array auto deduction, it's type information.

Those are actual runtime types provided by JavaScript. A `Float64Array` is not an `Array`. That's also why they have different runtime behaviors. They're also limited in what they can do, e.g. a `BigInt64Array` can't store floating point `number`s.

> With "sort-compare" I would need to write custom comparators everytime with only-numbers array.

🤷‍♂️ You have to deal with the quirks of the runtime you're dealing with.

**Closed** 2024-04-12 15:29 UTC
Labels: Working as Intended
