### ISSUE TITLE
Error TS2322: Type 'string' is not assignable to type 'T extends number[] ? string[] : string'.

### ISSUE THREAD

**Issue by jiesia** [microsoft/TypeScript#52476] opened 2023-01-28 10:13 UTC
I have a code snippet like this:

```ts
function testFunc<T extends number[] | number>(arr: T): T extends number[] ? string[] : string {
  return !Array.isArray(arr) ? String(arr) : arr.map((a) => String(a));
}
```

But this gives me the following errors:

Type 'string | string[]' is not assignable to type 'T extends number[] ? string[] : string'. 
Type 'string' is not assignable to type 'T extends number[] ? string[] : string'.ts(2322)

**Comment by MartinJohns** [comment] 2023-01-28 10:36
You forgot to fill out the issue template for bug reports. Duplicate of #33912.

**Closed** 2023-01-31 18:00 UTC
Labels: Duplicate
