### ISSUE TITLE
Type predicates only work with shorthand syntax in if statements

### ISSUE THREAD

**Issue by ngregory-rbi** [microsoft/TypeScript#49573] opened 2022-06-16 12:55 UTC
# Bug Report

### 🔎 Search Terms

predicate
type predicate
predicate syntax

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type predicates.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.2#code/GYVwdgxgLglg9mABAQwBQEpEG8BQj+IQIDOUiAbsgDYwAmAYlcgObGIC8iA2gOQC0yHgBpE-AEbDRfCDwC6KNkTCkA3HgKhIsBIhjFGLAGrU6qYE2YAuRKQBOMMM3TXzLXWygBPAA4BTOMAUJgwWxFxgIAC2Yr628rgEiYi2vlAgtkiUNCEsxAB0DhBUILS+xGYWCohefgFB2Qas4VExcehqiQC+6vhKpIiuzByIALLIUAAWebbIYLRwkRh5UHAAylD2jhgdBDCBqHqNxtkVLJjsFwPUxL6YCUn4gyqIAPQvNhsOzD1JKWkZO3w3UST1e7zsXxwPz2iFQAEJDhZjqZBug7j8QRZnm8Pptvg98H90mBAYhgRosWDqj5-IEsnRGmEItFYrIcN0cJpoPAkGIMNgfn0yPScqxhrwBJJxFLpHIqkLSVztEhEUZgqcrLivs4BpU9NTanTgozmiy4gKCclUsT6gzQgVIMVSuVBlUarTbaKmS1We0fuTeiQyK7OGNJtNZvNFuhlmtPls-YkYQd9Ej1aiOJcNiBbhaCaCcRDHBiCESAf6fgXwfH8QRoftVcxkbQNWi8w8qwaPSKTczWmzLWWSRXMSxsdW8eygA)

### 💻 Code

```ts
function a() {
    const validFlags = ['-a', '-b', '-c'] as const;
    function isFlagValid(flag: string): flag is typeof validFlags[number] {
        return validFlags.includes(flag as typeof validFlags[number]);
    }
    const flag = Math.random().toString();
    if (isFlagValid(flag) === false) {
        flag; // string
        return;
    }
    flag; // string

    if (!isFlagValid(flag)) {
        flag; // string
        return;
    }
    flag; // typeof validFlags[number]
}

function b() {
    const validFlags = ['-a', '-b', '-c'] as const;
    function isFlagValid(flag: string): flag is typeof validFlags[number] {
        return validFlags.includes(flag as typeof validFlags[number]);
    }
    const flag = Math.random().toString();
    if (isFlagValid(flag) === true) {
        flag; // string
        return;
    }
    flag; // string
    
    if (isFlagValid(flag)) {
        flag; // typeof validFlags[number]
        return;
    }
    flag; // string
}
```

### 🙁 Actual behavior

The function with a type predicate only limits the type definition of `flag` if it's used in shorthand syntax `!isFlagValid(flag)` or `isFlagValid(flag)` and not the more explicit `isFlagValid(flag) === false` or `isFlagValid(flag) === true`.

### 🙂 Expected behavior

The function with a type predicate limits the type definition of `flag` regardless of the syntax uses and they both mean the same thing.

**Comment by MartinJohns** [comment] 2022-06-16 13:16
Duplicate of #44366.

**Closed** 2022-06-18 18:00 UTC
Labels: Duplicate
