### ISSUE TITLE
const enums in a declared namespace cause namespace to be instantiated

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4403] opened 2015-08-21 21:09 UTC
Consider a simplified version of [the .d.ts file for 'nouislider'](https://github.com/borisyankov/DefinitelyTyped/blob/8f081073e6cb416f901b272810d8b04d6e01c9e0/nouislider/nouislider.d.ts):

```TypeScript
declare namespace myFramework {
    interface Static {
        create(blahArray: any[]): Instance;
    } 

    interface Instance {
        /**
         * Returns 0, 1, or 2, depending on if the stars align.
         */
        doFoo(): number
    }
}

declare var myFramework: myFramework.Static;
```

`doFoo` currently returns one of 3 different values. `number` is a little more broad than one would prefer, so one might be tempted to say "I know, I'll use a const enum!":

```TypeScript
declare namespace myFramework {
    interface Static {
        create(blahArray: any[]): Instance;
    } 

    interface Instance {
        /**
         * Returns 0, 1, or 2, depending on if the stars align.
         */
        doFoo(): number
    }

    const enum FooReturnValue {
        StarsTotallyAlign,
        StarsTotallyDontAlign,
        EhCloseEnough
    }
}

declare var myFramework: myFramework.Static;
```

Now that person has two problems:

Severity | Code | Description | File | Line
-----------|--------|----------------|------|-------
Error | TS2300 | Duplicate identifier 'myFramework'. | myFramework.ts | 1
Error | TS2300 | Duplicate identifier 'myFramework'. | myFramework.ts | 20

Apparently, the `FooReturnValue` causes the namespace to be instantiated.

Note:One might say that the solution is to just absorb `Static` into the `myFramework` namespace and just instantiate it there, which seems reasonable, but it is still an odd quirk that there is no way to control that a const enum can instantiate a module

**Comment by mhegazy** [comment] 2015-08-21 21:26
that is currently by design. it is worth reconsidering though.  //CC: @vladima

**Comment by JsonFreeman** [comment] 2015-08-24 18:28
I think the problem is that it makes myFramework ambiguous. When you refer to myFramework in value position, how is the compiler supposed to know whether myFramework should have a method called `create` (the var interpretation) versus a const enum member called FooReturnValue?

**Comment by mhegazy** [comment] 2016-02-22 20:39
as noted, this is by design. we have not got any feedback about this issue. closing for now.

**Closed by mhegazy** 2016-02-22 20:39 UTC
Labels: Needs Proposal, Suggestion
