### ISSUE TITLE
`null & {}` should not simplify to `never` in a union

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#28421] opened 2018-11-08 23:34 UTC
While working on #28394 I was able to identify an issue with inference that was causing us to infer `{}` for a reverse mapped type's property types - the behavior of `{}` in an intersection was itself very strange and is what actually led to the problem (otherwise the bad inference would probably never have been observable unless someone was using a `this` type in their component!).

In short, if I have
```ts
interface ReactElement<T> {
    $type: string;
}
type ReactText = string | number;
type ReactChild = ReactElement<any> | ReactText;
interface ReactNodeArray extends Array<ReactNode> { }
type ReactFragment = {} | ReactNodeArray;
type ReactNode = ReactChild | ReactFragment | string | number | boolean | null | undefined;
```
and I write
```ts
declare var a: { children?: ReactNode; };
declare var b: { children?: ReactNode; } & { children?: {} };

a = b;
b = a;
//^^
//Type '{ children?: ReactNode; }' is not assignable to type '{ children?: ReactNode; } & { children?: {} | //undefined; }'.
//  Type '{ children?: ReactNode; }' is not assignable to type '{ children?: {} | undefined; }'.
//    Types of property 'children' are incompatible.
//      Type 'ReactNode' is not assignable to type '{} | undefined'.
//        Type 'null' is not assignable to type '{} | undefined'.
```

both assignments should work (under `strictNullChecks`), but they do not!

**Comment by weswigham** [comment] 2018-11-08 23:39
cc @ahejlsberg - I remember talking with you about this and weather intersections with `{}` and unit types can "count" as vacuous or not (since we waffle on weather `{}` implies an actual object or not) - I think this is a good practical example of why they cannot. Swapping the unconstrained type parameter base type to `unknown` might also help make this crop up less often, since `unknown` behaves like you'd expect it to in this case!

**Comment by ahejlsberg** [comment] 2018-12-09 17:08
@weswigham I see the issue in #26796, but I don't understand what the problem is here. The `ReactNode` type is effectively the same as `{} | null | undefined`. When you intersect `{} | null | undefined` with `{} | undefined` you get `{} | undefined` (which is correct), and the error is that `{} | null | undefined` is not assignable to `{} | undefined` (which is also correct). What am I missing?

**Comment by weswigham** [comment] 2018-12-09 23:09
The `{}` only appeared from an inference failure - so failed inference introduced a type which affected the assignability of the result. Had we selected `unknown` instead of `{}`, it would have actually been fine. The issue is phrased like this because we often still treat `{}` like a top type, but in this case we do not and the comparisons break down because of it.

**Comment by ahejlsberg** [comment] 2018-12-10 14:38
Hmm. I don't think we want to start treating `{}` as a top type any more than we already do since it really isn't in `--strictNullChecks` mode. As you're saying above, the correct thing to do would be to infer `unknown` when we have no inference candidates.

**Comment by ahejlsberg** [comment] 2019-01-30 17:23
I'm going assign this back to you. With #28940 there is at least a way to explicitly request an `unknown` inference when we have no candidates. Beyond that, you could run the experiment of changing the default to `unknown` for unconstrained type parameters--but I have a feeling is too big of a breaking change.

**Closed** 2019-05-23 22:30 UTC
Labels: Bug, Domain: Literal Types
