### ISSUE TITLE
isFinite(), isInteger(), ... as type predicates?

### ISSUE THREAD

**Issue by titouandk** [microsoft/TypeScript#58916] opened 2024-06-18 20:33 UTC
### 🔍 Search Terms

Use isNumber() isNan() isFinite() as type predicates

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

`Number` provides several functions that could be used as type predicates.

Currently, those functions provide no indication about the type of the value that passes the test:

```ts
let val: unknown;

if (Number.isInteger(val)) {
    val.toString() // error: val is of type unknown
}
```

### 📃 Motivating Example

The exemple is self-explanatory.

### 💻 Use Cases

What workarounds are you using in the meantime?

Manual casting to a related type.

**Comment by whzx5byb** [comment] 2024-06-18 20:38
Duplicate of https://github.com/microsoft/TypeScript/issues/15048

**Comment by fatcerberus** [comment] 2024-06-18 20:47
To be clear, these can't be type predicates *today* because `x is number` is an "if and only if" relation - if the predicate is false, TS assumes `x` is not a number.

**Closed** 2024-06-21 01:30 UTC
Labels: Working as Intended
