### ISSUE TITLE
lib.es2015.core.d.ts: Some parameters of functions of Number is not completely right

### ISSUE THREAD

**Issue by Ezio1212** [microsoft/TypeScript#37190] opened 2020-03-03 19:18 UTC
For example, We can use the following in es2015:

`Number.isInteger(undefined); // false`

but in lib.es2015.core.d.ts:
`interface NumberConstructor {`
`// some defination codes....`
` isInteger(number: number): boolean;`
`// some other def codes...`
`}`

thx

**Comment by nmain** [comment] 2020-03-03 19:27
Duplicate of https://github.com/microsoft/TypeScript/issues/34931

**Comment by Ezio1212** [comment] 2020-03-03 19:29
thanks, i will colse it.

**Closed** 2020-03-03 19:30 UTC
