### ISSUE TITLE
Type 'null' is not assignable to type 'Readonly<unknown>'

### ISSUE THREAD

**Issue by MichaelTontchev** [microsoft/TypeScript#50774] opened 2022-09-14 16:56 UTC
# Bug Report

### 🔎 Search Terms

Type 'null' is not assignable to type 'Readonly<unknown>'

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about null, unknown, and readonly. I used the TS playground to test from nightly back to 3.3.333

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220914#code/MYewdgzgLgBAhgLhgJQKZwCbgDYE8A8ArmANZggDuYAfDALwxiHbYDcQA)

### 💻 Code

`const a: Readonly<unknown> = null;`

### 🙁 Actual behavior

Type error: Type 'null' is not assignable to type 'Readonly<unknown>'

### 🙂 Expected behavior

No error. Null is readonly and should be assignable to unknown.

Assignments that *do* work:

```
const a: Readonly<null> = null;
const a: unknown = null;
```

**Comment by MartinJohns** [comment] 2022-09-14 17:04
Essentially a duplicate of #29793. `Readonly<>` is a mapped type, and the type `Readonly<unknown>` resolves to `{}`, as a result not allowing `null`.

**Comment by MichaelTontchev** [comment] 2022-09-16 17:21
@MartinJohns Thanks!

Hmm, it seems to be that, logically, we *would* want this behavior to be supported, no? Intuitively, `null` should match `Readonly<unknown>`.

Could we modify the definition of `Readonly`? Currently, it's defined as:

```
type Readonly<T> = {
    readonly [P in keyof T]: T[P];
};
```

It seems like the following captures the desired behavior:

```
declare type Primitive = string | number | boolean | bigint | symbol | undefined | null;

type ReadonlyObjectOrArray<T> = {
    readonly [P in keyof T]: T[P];
};

type Readonly<T> = unknown extends T
    ? Primitive | ReadonlyObjectOrArray<T>
    : ReadonlyObjectOrArray<T>;
```

[TS Playground link](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220914#code/CYUwxgNghgTiAEAXAngBwQBRgSwLbcWwDcEBeeAZ0RwDsBzeAH3hoFdcAjEGJ+Dge34QQUGrw7Y62Gol4VknIb1Y1QAM2khgvNhAgBuALAAoEynTwASiOD8aEZAHkOAK3CJHMAIIwYUZAA8ACoAfPDkAN4m8DHwcFC29sjwANoY8NLwANYgyPxq8EEAugBchWlFRsYAvlVmaJgw-Kj8FFrWCXYOwWHkKlk0-ADuYiAAHoggqhSF0bEA-PBYeATECMwdiQ7ObmAe3r7+PXMxZZtdTq7unj5+gaF1xmB2VPBQZVjNre02FwH9gxGvRYrD0j2eNFeHA+TRabWA5yS-xoA2GNGBAHIoBjwS9ZGAYV94YjugC0cCosZYm8ygBGAA0JlqJhMENewDKVFoDGYugg4XgAFkoIgABYAOj8qn4uAAFABKeABeC0+CLLEY+BlPm4yGyECEuE-TpIslAgXAfRAA)

**Comment by MartinJohns** [comment] 2022-09-17 11:55
That suggested type is **a lot** more complex. I'm not sure whether that results in a breaking change (which would be a no-go), but it would definitely result in reduced compiler performance - for a rare corner case.

**Closed** 2022-09-21 18:00 UTC
Labels: Duplicate
