### ISSUE TITLE
Support defining lengths of arrays in function parameters with mapped tuples

### ISSUE THREAD

**Issue by Roaders** [microsoft/TypeScript#28227] opened 2018-10-30 11:01 UTC
## Search Terms

mapped tuple

## Suggestion

Support the use of mapped tuples to define the length of arrays passed to a function

## Use Cases

The actual example that I working with currently is that I want to construct a list of items, I pass an array of constructors to a function and I want to also pass to the function a list of configuration objects for each constructor. I tried to do this with a mapped tuple but the constructor list is typed as an array rather than a tuple so the length is not honoured and configuration lists of any length are allowed by the compiler

## Examples

```
const myStringArray = ["one", "two", "three"];

type MapToBoolean<T extends string[]> = { [K in keyof T]: boolean };

function mapStrings<T extends string[]>(strings: T, modifyStrings: MapToBoolean<T>) {
}

mapStrings(myStringArray, []); // should fail compilation
mapStrings(myStringArray, [true, true]); // should fail compilation
mapStrings(myStringArray, [true, true, true]); // should pass compilation
mapStrings(myStringArray, [true, true, true, true]); // should pass compilation
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by AlCalzone** [comment] 2018-10-30 11:10
Duplicate of #26223?

**Comment by Roaders** [comment] 2018-10-30 11:15
> Duplicate of #26223?

I don't think so. I don't want to specify the length of the tuple, I want to support any length. I just want the length of the 2 arrays to be the same.

**Comment by jack-williams** [comment] 2018-10-30 13:53
If you contextually type your tuple then you get some of the errors you want:

```ts
const myStringArray: [string, string, string] = ["one", "two", "three"];

type MapToBoolean<T extends string[]> = { [K in keyof T]: boolean };

function mapStrings<T extends string[]>(strings: T, modifyStrings: MapToBoolean<T>) {
}

mapStrings(myStringArray, []); // should fail compilation - Does
mapStrings(myStringArray, [true, true]); // should fail compilation - Does
mapStrings(myStringArray, [true, true, true]); // should pass compilation - Does
mapStrings(myStringArray, [true, true, true, true]); // should pass compilation - Does NOT. 4 is not assignable to 3
```

I'm not sure whether the last one should be ok. I think the error seems reasonable.

**Comment by Roaders** [comment] 2018-10-30 14:01
@jack-williams - that would be fine if I could require a tuple type as the function argument and not accept arrays.

**Closed** 2019-07-13 00:02 UTC
Labels: Question
