### ISSUE TITLE
Readonly instances cannot have private members

### ISSUE THREAD

**Issue by parzh** [Microsoft/TypeScript#23419] opened 2018-04-15 16:38 UTC
**TypeScript Version:**  2.8.1

**Search Terms:** Readonly, freeze, Object.freeze, private

**Code**

There is a practice to freeze instances in the constructor, right before `return`ing them. But, unfortunately current implementation of the `Readonly` interface makes it impossible to do so, if there are `private` instance members of any kind, be it fields, accessors or methods.

```ts
class Thingy {
  private doubleIt() {
    return this.value * 2;
  }

  constructor(public value: number) {
    return Object.freeze(this); // Property 'doubleIt' is missing in type 'Readonly<this>'
  }
}
```

This enforces developers to use workarounds and local usage conventions.

**Expected behavior:**
No compile errors.

**Actual behavior:**
Compile error: `Property 'squareIt' is missing in type 'Readonly<this>'`

**[Playground Link](https://www.typescriptlang.org/play/#src=class%20Thingy%20%7B%0D%0A%20%20private%20doubleIt()%20%7B%0D%0A%20%20%20%20return%20this.value%20*%202%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20constructor(public%20value%3A%20number)%20%7B%0D%0A%20%20%20%20return%20Object.freeze(this)%3B%0D%0A%20%20%7D%0D%0A%7D)**

**Related Issues:**
#22315

**Comment by andy-ms** [comment] 2018-04-16 15:55
I'll mark this as a duplicate of #10725 -- although we should probably not have used `Readonly` in that case since as you can see it doesn't work.

**Comment by parzh** [comment] 2018-04-16 19:29
I see the referenced issue as related to this one, rather than duplicate of it.

You're talking about `Object.freeze()` returning `Readonly`? No, I think, that's fine. The strange part is that `readonly` can be applied to properties only, – that's strange IMO.

**Comment by andy-ms** [comment] 2018-04-16 19:33
See #16441.

**Comment by parzh** [comment] 2018-04-16 19:53
I see. Could you mark my issue as a duplicate of #16441 instead?

**Closed** 2018-04-16 19:54 UTC
Labels: Duplicate
