### ISSUE TITLE
Infer method argument types from interface.

### ISSUE THREAD

**Issue by sinclairzx81** [Microsoft/TypeScript#26806] opened 2018-08-31 06:52 UTC
Hi,

This has likely been asked before, and suspect there has probably been some consensus reached on the following. But curious with respect to the following implementation that seems to allow for breaking issues when not compiling in `strict` and `Parameter 'x' implicitly has an 'any' type` errors when compiling in strict when the type of `x` should be obvious.

```typescript
interface IFoo {
    add(a: number, b: number): number
}
// class satisfies interface (non-strict)
class Foo implements IFoo {
   // can't `a` and `b` be inferred to be of type `number` ? 
   public add(a, b) {
        return a + b
    }
}

const foo = new Foo()
foo.add("hello", "world") // allowed (non-strict)
```
Are there any future plans to perhaps have TS statically resolve the arguments `a` and `b` when implementing from an interface in this way?

Many Thanks

**Comment by mattmccutchen** [comment] 2018-08-31 13:11
Duplicate of #23911.

**Comment by sinclairzx81** [comment] 2018-09-03 11:42
@mattmccutchen thanks will track there.

**Closed** 2018-09-04 17:29 UTC
Labels: Duplicate
