### ISSUE TITLE
infer of selective types

### ISSUE THREAD

**Issue by Akimotorakiyu** [microsoft/TypeScript#39737] opened 2020-07-25 04:14 UTC
## Search Terms

infer of selective types

## Suggestion
infer of selective types

## Use Cases
```ts
interface FunInterface {
  < R,P>(params: P): R;
}

let fun: FunInterface ;

let p ="123";
fun<number>("123");
// should be equivalent with `fun<number, typeof p>(p)`
// should be equivalent with `fun<number, string>(p)`
```

#### one more thing, Generics by default
```ts
function name(p){
  return p
}
// should be  equivalent with
// function name<P>(p:P){
//  return p
// }

const aName = name("someName")
// type of aName is string
const aNumber = name(123)
// type of aNumber is number
```

## Examples

```ts
function deal<A extends unknown[], E>(event: E){
  return {
    event,
    fun:(fn:(...args:A))=>{
      eventBus.on(event,fn);
    }
  }
}

const eventName = "notify" as SomeEventType;

deal<[number]>(eventName );
// should be equivalent with `fun<[number], typeof eventName>(eventName );`
// should be equivalent with `fun<[number], SomeEventType>(eventName );`
```

#### one more thing, Generics by default
```ts
function name<A extends unknown[], B extends SomeType>(p1, a:A, p2:AKindType,  b: B){
  return {p1,a,p2,b}
}
// should be  equivalent with
// function name<A extends unknown[], B extends SomeType,T>(p1:T, a:A, p2:AKindType,  b: B){
//  return {p1,a,p2,b}
// }
```
## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-07-25 12:10
Sounds like a duplicate of #26242.

**Comment by Akimotorakiyu** [comment] 2020-07-25 14:27
@MartinJohns not the same.

**Comment by imachug** [comment] 2020-07-25 19:20
The first example looks like a duplicate, the second one might be new.

**Comment by RyanCavanaugh** [comment] 2020-07-29 20:16
The other part is a duplicate of #17428

**Closed** 2020-08-01 18:00 UTC
Labels: Duplicate
