### ISSUE TITLE
[TS2307]: Cannot find module, When package.json main field is directory name

### ISSUE THREAD

**Issue by wuzekang** [Microsoft/TypeScript#13406] opened 2017-01-11 03:27 UTC
**TypeScript Version:**  2.1.4

**Code**

```ts
import * as bencode from 'bencode';
```

**bencode module folder structure**

```txt
./node_modules/bencode
├── CHANGELOG.md
├── CONTRIBUTORS
├── lib
│   ├── decode.js
│   ├── encode.js
│   └── index.js
├── LICENSE.md
├── package.json
└── README.md
```

**package.json**

```json
{
...
  "main": "lib",
...
}
```

**Expected behavior:**
Compile pass

**Actual behavior:**
error TS2307: Cannot find module 'bencode'

**Comment by DanielRosenwasser** [comment] 2017-01-14 09:37
Duplicate of #12974.

**Closed by DanielRosenwasser** 2017-01-14 09:37 UTC
