### ISSUE TITLE
JS IntelliSense fails to treat `exports["default"]` the same as `exports.default`

### ISSUE THREAD

**Issue by YuCJ** [microsoft/TypeScript#32153] opened 2019-06-27 10:18 UTC
- VSCode Version: 1.35.1（1.35.1）
- OS Version: Mac OS Sierra 10.12.5（16F73）

Steps to Reproduce:

1. Given the repo with `package-consumer/` and `test-package/` https://github.com/YuCJ/vscode-issue-report
2. `cd test-package` and run `yarn link` or `npm link`
3. `cd ../package-consumer` and run `yarn link test-package` or `npm link test-package` to symlink the `test-package` to `package-consumer/node_modules`
4. Try named import and default import when editing `package-consumer/index.js`. And the IntelliSense works fined with named import but fails with default import. (Expect the properties to show in IntelliSense)

![螢幕快照 2019-06-27 下午6 19 14](https://user-images.githubusercontent.com/5386489/60258636-1efa0280-9908-11e9-8ecb-312f7fbffda9.png)

![螢幕快照 2019-06-27 下午6 01 48](https://user-images.githubusercontent.com/5386489/60258328-819ece80-9907-11e9-96dc-89defda080b6.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-06-28 00:03
Confirmed with typescript@3.6.0-dev.20190627

Seems to work fine if you use `exports.default = ...;` instead of `exports['default'] = ...`

**Comment by YuCJ** [comment] 2019-06-28 06:48
Thanks for checking, it works fine with `exports.default = ...` in my environment, too. But the `exports['default'] = ...` style  is the default output of `@babel/plugin-transform-modules-commonjs@7.4.4` (latest), so I guess this will be a common issue encountered by js developers.

I've not figured out why Babel choose to use the format as `exports['default']` (and it's not consistent with their document https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs ).

**Comment by andrewbranch** [comment] 2019-07-25 22:09
I started out by trying to make a fairly small, targeted fix for this, but it’s getting kind of ugly trying to keep it from leaking outside of JS and/or outside of module.exports. I think it might even make sense to allow assignment to element access in more cases, e.g., I don’t see why [expando properties on functions couldn’t happen via element access.](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABAMTnAFASkQbwFB4C+BqcAdACYwDOADgDYCGAngHKMC2ApogLyIAiUgIDceUpRoMW7bmPFoA2gIACAIyYALAQF0+g4WKA) But, that’s beyond the scope of what we’d want to add for 3.6 at this point. /cc @sandersn for thoughts.

**Comment by sandersn** [comment] 2019-07-26 18:05
Yeah, I think element access makes sense too. It's just not something that was there when I added the TS feature.

**Comment by andrewbranch** [comment] 2019-07-26 19:14
Ok, I'm bumping this to 3.7 as it's fairly feature-y. It's not a bug per se; we don't do special assignment on element access. Adding it is a feature, I guess.

**Closed** 2019-09-30 20:08 UTC
Labels: feature-request
