### ISSUE TITLE
Massive slowdown in compiling complicated union types

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/TypeScript#5849] opened 2015-12-01 05:39 UTC
This is the same code as what originally prompted #2997

While it isn't crashing because of infinite loops any more, it *has* become very slow with 1.7. If I pause it in the debugger I see the following stack repeating many times.

```
inferFromTypes [tsc.js] Line 15334	JavaScript
inferFromTypes [tsc.js] Line 15314	JavaScript
inferFromTypes [tsc.js] Line 15301	JavaScript
inferFromProperties [tsc.js] Line 15350	JavaScript
inferFromTypes [tsc.js] Line 15334	JavaScript
inferFromTypes [tsc.js] Line 15314	JavaScript
inferFromTypes [tsc.js] Line 15301	JavaScript
inferFromIndexTypes [tsc.js] Line 15380	JavaScript
inferFromTypes [tsc.js] Line 15337	JavaScript
inferFromProperties [tsc.js] Line 15350	JavaScript
```

Reduced test case:

```typescript
class Module {
	public members: { [name: string]: FFunction | Property };
}

class Namespace {
	public members: { [name: string]: Class | Enum };
}

class Class {
	public parent: Module | Namespace;

	public members: { [name: string]: Property | FFunction };
}

class Interface {
	public members: { [name: string]: Property | FFunction };
}

class FFunction {
	public parent: Module | Namespace | Class | Interface; // (1)
}

class Property {
	public parent: Module | Namespace | Class | Interface; // (2)
}

class Enum {
	public parent: Module | Namespace;

	public members: EnumMember[];
}

class EnumMember {
	public parent: Enum;
}

var members: (Property | FFunction)[];
members.map(member => "");
```

Compile with `tsc foo.ts` on node 4.2.2 x64 on Windows 7.

This takes ~18s on my machine. If I remove `Module` from the union type at (1), it drops to ~12s. Removing `Module` at (2) drops it to ~6s. And so on.

The original code is at https://github.com/Arnavion/libjass/blob/82f3706/build/typescript/ast.ts which has a much more complicated forest of types. It's been compiling for 5 minutes now, whereas it took ~2s with 1.6

**Comment by vladima** [comment] 2015-12-01 05:59
@Arnavion can you give a try to typescript@next. Seems that this issue is already fixed in master. I can confirm that it takes 17.50 s on my machine to compile your sample using release-1.7, however on master it takes only

**Comment by Arnavion** [comment] 2015-12-01 06:10
Yes, looks like it. The original code also takes ~2s with next, same as 1.6.

**Comment by Arnavion** [comment] 2015-12-01 06:28
Can the fix be backported to 1.7 or do I skip it and wait for 1.8?

**Comment by mhegazy** [comment] 2015-12-01 06:31
depends on the fix. @vladima do you know what is going on?

**Comment by vladima** [comment] 2015-12-01 07:05
yes:  https://github.com/Microsoft/TypeScript/pull/5738. If source and target types are unions or intersection then removing matching constituents from source and target sides significantly reduces amount of types that participate in type inference.

**Comment by Arnavion** [comment] 2015-12-02 00:58
Yes, cherry-picking that PR onto 1.7 fixes the issue (and introduces #5861 but that's a minor annoyance in comparison).

**Comment by mhegazy** [comment] 2015-12-02 01:11
@Arnavion is there a chance you can move to `typescript@next` directly?

**Comment by Arnavion** [comment] 2015-12-02 02:33
If you're asking because you don't want to backport it, that's fine. I have no problem staying with 1.6 until 1.8 is released. :)

**Comment by mhegazy** [comment] 2015-12-02 04:19
I am asking to figure out the logistics, porting it and publishing an npm is easy, but we will need to publish a VS 2012, VS 2015, and sublime text plugin updates and that all adds up.

**Comment by mhegazy** [comment] 2015-12-03 22:53
Let's port https://github.com/Microsoft/TypeScript/pull/5738 and https://github.com/Microsoft/TypeScript/pull/5895 to release-1.7 branch.

**Comment by ahejlsberg** [comment] 2015-12-03 23:44
I'm trying to understand why this got slower from 1.6 to 1.7? Vlad, did you look into that? I understand why the new union/intersection reduction in 1.8 makes it faster, but I'd like to know why it got slower in the first place.

**Comment by ahejlsberg** [comment] 2015-12-04 00:07
Ok, I now understand why it got slower. When inferring types, if the source and target are both non-generic object types we don't descend into the types because it we know it won't produce inferences. However, in 1.7 *all* classes are generic because of the implied `this` type argument, so we end up doing a *lot* more work. I'm going to give some thought to a fix. The union/intersection reduction isn't really the answer, it just so happens to help in this example.

**Comment by vladima** [comment] 2015-12-04 00:08
yes, this got slower in the  9438a4bce0375e30eaf2a01bb1d73536d8cd36e1

**Comment by ahejlsberg** [comment] 2015-12-04 00:31
Ok, I have a fix. I will putting up a PR shortly.

**Comment by ahejlsberg** [comment] 2015-12-04 00:43
I would recommend *not* back-porting the union/intersection type reduction, but instead back-porting the #5920 fix I just put up.

**Closed** 2015-12-04 01:11 UTC
Labels: Bug

**Comment by mhegazy** [comment] 2015-12-04 23:06
@Arnavion can you do us a big favor and give branch release-1.7 a quick test?

**Comment by Arnavion** [comment] 2015-12-05 00:46
Everything seems fine. Thanks!

**Comment by mhegazy** [comment] 2015-12-07 02:18
thanks @Arnavion!
