### ISSUE TITLE
Partial record key type checking failure

### ISSUE THREAD

**Issue by AntonOfTheWoods** [microsoft/TypeScript#48136] opened 2022-03-06 01:33 UTC
# Bug Report

### 🔎 Search Terms
typescript partial record key type checking failure

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "Common "Bugs" That Aren't Bugs"

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.6.2#code/C4TwDgpgBAsiDSEQBVzQLxQOQEMtQB9sAjfIrAYywG4AoUSKAZQFdiA1HAGxYgGdUjTAG9aUKADduvPgC4ofYACcAlgDsA5gG0AunQC+demlggAwgHs1wHOohLBGKKPHEcAE049+8gAo4lYBVuAB4AJQgKCyV3ELhEFDQAGmY2LxlHAD5MgyMAMxY1CiCrKBwCopK1AAocAGskeXikRwBKFyguCGAoBpAoTHqkOnEAelG+gewqaihxqEKogFsliGsoVbK1dzK+PhUNNS3+izyylOIoaKgKLZ3lsBUuHCqoPNsuPjEbq0UoNQgAHcACIvHBNcxWGx2BwmERQNyeaQ+ZxQLR9HTyYTHYAAC3UGgAkgB1HDWeS6KD6KlUgxAA

### 💻 Code

```ts
type MyKeyType = 'a' | 'b' | 'c';
type SubValuesType = {
  values: string[];
};

type MyContainerType = {
  badValues: Partial<Record<MyKeyType, SubValuesType>>;
};

function afunction(akey: MyKeyType){
  let key = akey;
  //key = 'c'; // uncomment me and assign any of a, b or c and compilation fails
  const newData: MyContainerType = { badValues: { [key]: { anythingIWant: [] } } };
}
```

### 🙁 Actual behavior

There is no type checking compilation error. I am able to assign an invalid type to `newData`

### 🙂 Expected behavior

Checking error. At the very least I would call this a MASSIVE "principle of least surprise" failure. If this is the expected behaviour, it is extremely unintuitive.

**Comment by RyanCavanaugh** [comment] 2022-03-08 17:41
Sort of a duplicate of #38663

I think we could get away with raising an error for `t = { [k]: v }` when `k` is a literal union type `"s1" | "s2" | "s3" ...` and `v` isn't assignable to the union `t["s1"] | t["s2"] | t["s3"] | ...` (intersection would be more sound, but impractical due to producing `never` a lot of the time). It'd be a breaking change but it's hard to see how that code wouldn't have an actual bug.

**Comment by AntonOfTheWoods** [comment] 2022-03-08 23:51
Sorry I missed the duplicate @RyanCavanaugh . Looking at the issue you refer to looks close enough to me. If the fix you think might be viable here would work there also, I'm definitely happy to close this.

**Comment by RyanCavanaugh** [comment] 2022-03-09 00:42
On second read, the issue I linked is definitely the same. I'll transfer the metadata

**Closed** 2022-03-09 00:43 UTC
Labels: Duplicate
