### ISSUE TITLE
Add option to default `this` to class type in class methods, rather than `any`

### ISSUE THREAD

**Issue by isaacs** [microsoft/TypeScript#56452] opened 2023-11-17 22:50 UTC
### 🔍 Search Terms

class method
this
inference
opt-in
strict

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Add a `implicitClassMethodThis` (pending bikeshedding, I have no opinions on that) tsconfig compilerOption, which defaults to `false` for backwards compatibility.

If set, then any class method that does not specify a `this` type in its declaration will implicitly have a `this` type of the class it's defined in, rather than `any` (as it currently is).

### 📃 Motivating Example

Consider this example:

```ts
class Square {
  size: number
  constructor(size: number) { this.size = size }
  area() { return this.size * this.size }
}

const { area } = new Square(2)
console.log(area()) // runtime error
```

With `implicitClassMethodThis` set, the above code would be equivalent to:

```ts
class Square {
  size: number
  constructor(size: number) { this.size = size }
  area(this: Square) { return this.size * this.size }
}
const { area } = new Square(2)
console.log(area())
// ^ The 'this' context of type 'void' is not assignable to method's 'this' of type 'Square'. (tsserver 2684)
```

### 💻 Use Cases

1. What do you want to use this for? Preventing accidentally calling class methods without proper `this` binding.
2. What shortcomings exist with current approaches? Need to manually add `this: ClassName` to all of the methods, or just be careful and deal with run-time errors, or add run-time checks to class methods, all of which are tedious and easy to forget or do inconsistently.
3. What workarounds are you using in the meantime? Manually adding `this:` type declarations, run-time checks, and just being careful.

**Comment by DanielRosenwasser** [comment] 2023-11-18 00:19
I believe that this is a duplicate of #7968.

**Closed** 2023-11-21 01:30 UTC
Labels: Duplicate
