### ISSUE TITLE
Relative reference in generated .d.ts file in a monorepo

### ISSUE THREAD

**Issue by wgcrouch** [microsoft/TypeScript#26863] opened 2018-09-03 15:55 UTC
When generating a .d.ts file, typescript is including a relative reference for an import, which is imported as a module.

```
import { a } from "@ts-bug/a";

export function b(text: string) {
  return a(text);
}
```

generated a definition file:

```
/// <reference path="../../a/index.d.ts" />
export declare function b(text: string): import("@ts-bug/a").AText;
```

In this case it is in a mono-repo which may be confusing things, but the reference should be the same as the import. 

**TypeScript Version:**  
3.0.3, but also happens with 3.1.0-dev.20180901

**Search Terms:**
relative reference paths
generated reference relative

**Code**
I have created a repo with a simple reproduction here https://github.com/wgcrouch/ts-bug

**Expected behavior:**
The reference `/// <reference types="@ts-bug/a" />`

**Actual behavior:**
The reference generated is `/// <reference path="../../a/index.d.ts" />`

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/26439

**Comment by RyanCavanaugh** [comment] 2019-03-13 20:52
Probably a duplicate of the linked related issue

**Comment by sebinsua** [comment] 2019-03-14 12:06
@RyanCavanaugh Yes - but [this one has a reproduction repository](https://github.com/wgcrouch/ts-bug) so it should be easier for somebody to get to the root cause on.

**Comment by andypillip** [comment] 2019-07-15 14:54
In my case the generated .d.ts file contains syntax errors – is that related to this issue?

```typescript
/// <reference path="../../../../../../../../node_modules/@types/moduleE/dist/index.d.ts" />

declare const myFunc: () => O<'moduleE'.E<any>>;
```

The above is invalid, hence definitely a bug.

The file causing this error is as follows:

```typescript
declare module 'moduleE' {
    export interface E<T> {
…
```

If I remove the `declare module`, it's at least generating an `@import()` around the module name.

**Comment by weswigham** [comment] 2019-08-13 22:16
@andypillip if you could open up a new issue with a repro, that's be great, it's definitely not (directly) related to the issue in the OP here.

**Closed** 2019-08-13 23:34 UTC
Labels: Bug, Domain: Declaration Emit, Fix Available
