### ISSUE TITLE
Type guard fails to make an array of full objects assignable to an array of partial objects

### ISSUE THREAD

**Issue by KSXGitHub** [microsoft/TypeScript#60167] opened 2024-10-08 06:36 UTC
### 🔎 Search Terms

array of full objects assignable to an array of partial objects.

### 🕗 Version & Regression Information

_(not a regression)_

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.2#code/JYOwLgpgTgZghgYwgAgJIhNA8gIwFYQJjIDeAUMpcjAPY0BcyIArgLY7QDaAuhVTnCiMAzmCigA5jzIBfMmVCRYiFFmZLcBIqT6VQmKJsJhhAfkboDRotLkLw0eEmQBlZjjUb8xnVWT7sbyJhRgBBKCg4AE8AHgAFYAQAaxjLQK0wABpkAHJaGhyAPkLZeRhmECJgGhBkMDgkiDcPdWgACgB9YXdPdONGZt7DILAASkYANxpgABNSOwgADwAHGihicsqwatrluGFhABFgKGMAGyi2mlbhjMYh6zHJ6bnyP2AYZCubx4A6ANuxmEo1IyAA9GDkPthNBiGAABZwYgAx7CfxokA0YgVGYQGCgCAzXR+OoNJo9G7fLwZEEQ5DQKBrRgAFSiyxQOTSgJs3GQAB9kDi8QSZjl0UwsVCDsAJCA4DgzigwDQ6myOQlkqkMH0iNkAET5PWFHg5YlyBYrNYbCpVGrIU4IU5IiDM+EQEBxaFUnVge4-EbjZBTWa+KgfL7XanGf7a7kmEEkcGQ6GwuqI5Gx1HizHYkC4-GYIkkqj1RqDSmJlEjELISM+mNWavIGS0yEI4BovYHCDCM2lIA

### 💻 Code

```ts
interface InnerObject {
    foo: number[]
    bar: string[]
}

interface OuterObject {
    innerObjects?: InnerObject[]
}

interface SubOuterObject {
    innerObjects: Array<Pick<InnerObject, 'foo'>>
}

function takeSubOuter(_subOuterObject: SubOuterObject): void {}

export function passDirectly(outerObject: OuterObject): void {
    if (outerObject.innerObjects) { // assert that innerObjects is not undefined
        takeSubOuter(outerObject) // error: Type 'InnerObject[] | undefined' is not assignable to type 'Pick<InnerObject, "foo">[]'
    }
}

export function recreateThenPass(outerObject: OuterObject): void {
    if (outerObject.innerObjects) { // assert that innerObjects is not undefined
        takeSubOuter({ innerObjects: outerObject.innerObjects }) // this passes
    }
}
```

### 🙁 Actual behavior

In `passDirectly`, the`if` type guard fails to make `outerObject` compatible with `SubOuterObject`, even though it should have proven that `outerObject.innerObjects` is not `undefined`.

### 🙂 Expected behavior

There should be no compiler errors.

**Comment by MartinJohns** [comment] 2024-10-08 06:54
Duplicate of #42384.

**Closed** 2024-10-11 01:32 UTC
Labels: Duplicate
