### ISSUE TITLE
Unable to export abstract class as default.

### ISSUE THREAD

**Issue by SuperPaintman** [Microsoft/TypeScript#13603] opened 2017-01-20 22:35 UTC
**TypeScript Version:**  2.1.4

**Code**

```ts
export default abstract class Broker extends EventEmitter {
  abstract async connect();

  abstract async send();
  abstract async listen();
}
```

```
| export default abstract class Broker extends EventEmitter {
|                         ~~~~~

src/broker.ts(3,25): error TS1005: ';' expected.
```

**Expected behavior:**
Unable to export abstract class as `default`.

**Actual behavior:**
Fix exporting abstract class as `default`.

**Comment by RyanCavanaugh** [comment] 2017-01-20 22:43
Duplicate of #3792, #7647, #8307, #9513, #10553, #11749, #11778, and probably more. Please do search before logging issues.

![image](https://cloud.githubusercontent.com/assets/6685088/22167987/94ce5804-df1e-11e6-9ad0-ed50bdacc851.png)

**Comment by SuperPaintman** [comment] 2017-01-20 22:50
Sorry

**Closed** 2017-01-20 22:50 UTC
Labels: Duplicate
