### ISSUE TITLE
Array/Observable filter does not infer chained type

### ISSUE THREAD

**Issue by topaxi** [Microsoft/TypeScript#19640] opened 2017-11-01 11:15 UTC
**TypeScript Version:**  2.6.1 using `strict: true`

**Code**

```ts
[true, true, false, null]
  .filter(thing => thing !== null)
  .map(thing => thing.toString())
```

**Expected behavior:**

Compiles

**Actual behavior:**

```
3 col 17 error| 2531[QF available]: Object is possibly 'null'.
```

**Comment by andy-ms** [comment] 2017-11-01 14:29
Looks like a duplicate of #5101.
A workaround would be to write `(thing): thing is boolean => thing !== null` that tells us that the expression is a type guard.
Another workaround that I've found useful is to write a `mapDefined` helper:
```ts
function mapDefined<T, U>(iter: Iterable<T>, mapFn: (x: T) => U | undefined): U[] {
    const out: U[] = [];
    for (const x of iter) {
        const res = mapFn(x);
        if (res) {
            out.push(res);
        }
    }
    return out;
}

mapDefined([true, true, false, null], thing => thing === null ? undefined : thing.toString());
```

**Comment by topaxi** [comment] 2017-11-01 14:43
I noticed this by a different case actually, probably should have posted that one.

```js
['foo', 'bar', null]
  .filter(Boolean)
  .map(s => s.toUpperCase());
```

This worked with TS ~2.3 and is not working anymore with TS ~2.6. I thought the above would be a simpler reproduction but it seems it is something completely different :) Thanks for your hint though, this helps but still required quite a few new guards in our codebase which worked in a previous TS version 😕

**Comment by andy-ms** [comment] 2017-11-01 16:08
I just tried that with `typescript@2.3` and it doesn't seem to work? I don't think `Boolean` has ever been considered a type predicate.

**Comment by topaxi** [comment] 2017-11-01 16:22
You're right doesn't work on arrays, we do have some rxjs observables where this works though, no idea what exactly is different there or if it's project specific.. I will report back later this week.

**Closed** 2017-11-17 17:35 UTC
Labels: Duplicate

**Comment by whitecolor** [comment] 2018-01-17 05:51
Not sure why this not working:
```
const list: (string | null)[] = ['A', null, 'C']

list.filter<string>((_) => _ !== null).map(x => x.)
```

![image](https://user-images.githubusercontent.com/736697/35027749-35febed6-fb74-11e7-9696-8a780f8d5c3e.png)

Tried latest dev 2.7 still not working and not inferring

**Comment by mhegazy** [comment] 2018-01-17 07:36
A user-defined type guard is not inferred automatically, a type annotation is expected. i.e.:

```ts
const list: (string | null)[] = ['A', null, 'C']

function isNotNull<T>(a: T | null): a is T { return a !== null; }

list.filter(isNotNull).map(x => x.)
```

**Comment by whitecolor** [comment] 2018-01-17 10:03
> A user-defined type guard is not inferred automatically, a type annotation is expected. i.e.:

It is good to hear, but still complicated, not clear whey it not possible to have auto inference here.

**Comment by andy-ms** [comment] 2018-01-17 15:29
@whitecolor See #5101
