### ISSUE TITLE
getOutliningSpans hangs on large, json-like file

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#27960] opened 2018-10-18 02:00 UTC
From https://github.com/Microsoft/vscode/issues/60677

**TypeScript Version:**  3.2.0-dev.20181017

**Search Terms:**
- getOutliningSpans
- fold / folding

**Code**
1. Open this file javaScript file in VS Code: [dict_en.txt](https://github.com/Microsoft/TypeScript/files/2489919/dict_en.txt)

1. Notice that  intellisense and other features do not work. 

**Bug**
This is caused by the `getOutliningSpans` request never returning. We do try to cancel the request on the VS Code side when you switch away from that file but it seems the TS Server does not pick up the cancellation

**Playground Link:** 

**Related Issues:**

**Comment by DanielRosenwasser** [comment] 2018-12-01 00:03
We can possibly pick an aribtrary high count of nodes to traverse and check the cancellation token ever `n` nodes traversed.

**Comment by weswigham** [comment] 2018-12-01 00:09
The cancellation token disk access is already throttled. We don't need to meter when we check it we just need to check it more.

**Comment by sheetalkamat** [comment] 2018-12-01 00:19
While at it I noticed that before carrying out operation we check for cancellation token and that is not throttled. (https://github.com/Microsoft/TypeScript/blob/master/src/server/session.ts#L556) we should use throttled cancellation token there as well.

**Comment by weswigham** [comment] 2018-12-01 01:21
So I think this is actually a dupe of #28540, because I'm tracking us as being stuck inside subtype reduction in the checker most of the time. If that's so, we have two candidate fixes up already, #28707 and #28727.

**Comment by juozhe** [comment] 2019-07-05 15:24
The problem with original file (dict-en.txt, or .js) is fixed for me in VS Code 1.36. I reported the original bug https://github.com/microsoft/vscode/issues/60677.

Thanks. If no other related problems are tracked under this ticket, it can be closed.

**Closed** 2019-07-05 18:46 UTC
Labels: Bug, Crash, Domain: TSServer
