### ISSUE TITLE
No extra space before and after brace when formatting inline JavaScript objects

### ISSUE THREAD

**Issue by alexanderby** [Microsoft/TypeScript#10282] opened 2016-08-11 09:15 UTC
- VSCode version 1.4.0

There seems to be no option to prevent inserting extra space after and before braces when formatting inline JS objects.
For example, when I expect
`var obj = { x: 5, y: 7 };`
to look like
`var obj = {x: 5, y: 7};`

**Comment by alexanderby** [comment] 2016-10-11 08:26
As an example this indentation is used in D3 https://github.com/d3/d3-collection/blob/master/src/entries.js

**Comment by OliverJAsh** [comment] 2016-11-24 13:27
Another use case is import statements, e.g. `import {x} from 'y';`

**Comment by mhegazy** [comment] 2016-12-16 06:07
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/9613 and https://github.com/Microsoft/TypeScript/issues/9224 respectively

**Closed by mhegazy** 2016-12-16 06:07 UTC
