### ISSUE TITLE
Type narrowing on global mutables is not reset after function call

### ISSUE THREAD

**Issue by garysoed** [microsoft/TypeScript#35972] opened 2020-01-03 01:03 UTC
**TypeScript Version:**  3.7.2

**Search Terms:** type narrowing global mutable

**Expected behavior:**

When a global mutable variable is modified by a function call, type narrowing on that variable should be reset.

Note that this also happens inside a class, with a mutable class property.

**Actual behavior:**

Type narrowing isn't reset so the code doesn't compile.

**Related Issues:**

**Code**
```ts
enum E {
    A,
    B,
}

function syncFn(): void {
    e = E.B;
}

let e: E = E.B;

function f(eInput: E): void {
    e = eInput;
    if (e === E.B) {
        return;
    }

    syncFn();
    if (e === E.B) {
        return;
    }
}

```

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ssl=23&ssc=1&pln=1&pc=1#code/KYOwrgtgBAolDeAoKKoEEA0zUCEsF9FEAzMEAYwBcBLAexCgGcBPCgMRAAoBKALigButagBME2FMCgBeWADocAbkSFEAG2CUowfnFkwFykmSp0GxTsACSIAA5hKuvoOFikqbTO037lZR+piKEsZaX0FbnEPDwAnTTAYkH9UVQ8Wdi5uZJRA4Kkw8JxI92iUOMoEpIkoQkIgA)

**Comment by MartinJohns** [comment] 2020-01-03 08:48
Duplicate of #9998.

**Closed** 2020-01-09 18:00 UTC
Labels: Duplicate
