### ISSUE TITLE
Support 'static' to be used with 'abstract' and generic type

### ISSUE THREAD

**Issue by k8w** [Microsoft/TypeScript#10603] opened 2016-08-30 08:16 UTC
**TypeScript Version:**  2.0.0

**Code**

``` ts
abstract Class BaseClass<T>{
    abstract static defaultValue:T;
    // ...
}

interface Format{
    //...
}

class ClassA extends BaseClass<Format>{
    static defaultValue:Format = { ... }
}
```

**Expected behavior:**
Can define static member in abstract class, so that force child classes contains it.
Such as `defaultProps` in `React.Component`

**Actual behavior:** 
Neither interface nor abstract class can achieve this.

**Comment by OliverJAsh** [comment] 2017-06-05 16:18
This is more general than the generic type use case:

``` js
  abstract class Base {
    abstract foo: string
    static bar: string
  }
  class BaseExtended extends Base {
    foo = '1'
    // expected error because static property is missing, but got none
    // static bar = '1'
  }
```

For context, I want this feature so I can properly type the static properties on my React class components. The React typings on DefinitelyTyped define a `Component` class, and a `ComponentClass` interface which includes the constructor and the static properties such as `propTypes`, `displayName`, and `defaultProps`. As far as I can see, there is currently no way to type check these static properties on the `ComponentClass` interface when defining a class component:

``` ts
  class ReactComponent extends Component<any, any> {
    // not type checked because this is defined in the ComponentClass interface, but
    // here we extend the Component class
    static displayName = 1
    render() {
      return <div>{this.props.name}</div>
    }
  }
```

If we had the feature requested here, we could consolidate the `ComponentClass` interface and the `Component` class into an abstract class with static properties.

**Comment by mhegazy** [comment] 2017-08-28 23:30
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/14600

**Comment by mhegazy** [comment] 2017-09-12 19:56
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-12 19:56 UTC
Labels: Duplicate
