### ISSUE TITLE
Inferred string union gets widened unexpectedly 

### ISSUE THREAD

**Issue by denis-sokolov** [microsoft/TypeScript#55156] opened 2023-07-25 23:52 UTC
# Bug Report

### 🔎 Search Terms
Property, field, string literal, return type, union, widened.

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about inference, widening, string union.
Tested with versions: 3.3.3 and 5.2.0-dev.20230720.

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.6#code/GYVwdgxgLglg9mABAUwB4AcA2MIygCgEoAuRAImDjjMQB9yAjAQwCcaBvAKER8ReSggWSALJMoACwB0LJmAAmcALZFEAHkQAGKQFZEAfnKVqiUmWZsA3JwC+nUJFgJEMJVhx5VXXnwFDR4tKyCsqqGtp6hhRUNGYWZNZ2nAD0yYgAQnCSiKzIRjF0jKxknFAAnuh5AKIY2LhQAEp+wogAvIhNgsIAKhXIauWVcMAotR5QAHylfYgAkm51eJ3+bR3NYL2VA33DLgvjUylp0Sb05sWcmAKIV1AAgqto7vVE1qmIAM5QLDBgAOaXa63dKrVzPTyEaxAA)

### 💻 Code
```ts
function explicit(): "foo" | "bar" {
    return Math.random() < 0.5 ? "foo" : "bar";
}
function implicit() {
    return Math.random() < 0.5 ? "foo" : "bar";
}

// Both are "foo" | "bar"
type ExplicitReturn = ReturnType<typeof explicit>
type ImplicitReturn = ReturnType<typeof implicit>

// "foo" | "bar"
let letA = explicit();
// string
let letB = implicit();
```

### 🙁 Actual behavior

Types of `letA` and `letB` are different.

### 🙂 Expected behavior

Types of `letA` and `letB` are the same.

The type signatures of `explicit` and `implicit` look identical to the user (`() => "foo" | "bar"`), but they have a different effect on the inference of other types.

This is connected to the fact that the binding is mutable. Same happens with object fields (`const obj = { field: implicit() }`), but does not happen with `const` bindings. Regardless of whether or not the mutable binding’s type should be widened, the behavior should probably be consistent between `letA`, `letB`, or a `letC = "foo" as "foo" | "bar"`.

**Comment by fatcerberus** [comment] 2023-07-26 00:14
The mutable binding is only half the story; the other half is that, unless annotated `as const`, string literals widen when assigned to a mutable binding.  The same thing happens here:

```ts
const foo = "foo";  // literal type "foo"
const bar: "foo" = "foo";  // ditto
let a = foo;  // string
let b = bar;  // "foo"
```

…which is by design.

I *am* a little surprised the widening flag survives past a function return, though.

**Closed** 2023-07-29 01:30 UTC
Labels: Not a Defect

**Comment by denis-sokolov** [comment] 2023-07-29 08:21
@RyanCavanaugh, could you please clarify this behavior? I am specifically interested in the invisible difference between the two functions, and not just the type widening.

**Comment by fatcerberus** [comment] 2023-07-29 14:10
@denis-sokolov There’s a special, invisible flag that literal types can have that determines whether they can be automatically widened to their primitive supertype in “widening” contexts (`let` variables, function returns, object literals, etc.).  The example you have there (`x as typeof x`) removes the widening flag, which may or may not be intentional: https://github.com/microsoft/TypeScript/issues/51723

To prevent a widening literal type from being inferred, you can write `"foo" as const`.  While potentially confusing, this behavior is ultimately by design.  There’s a long discussion about it here: https://github.com/microsoft/TypeScript/issues/49953

**Comment by fatcerberus** [comment] 2023-07-29 14:16
@RyanCavanaugh Function returns are normally widening contexts.  It seems a bit weird that, in the OP, a function is inferred as *itself* returning a widening type.  Is that intended, or should the return type have been widened to `string` there?

**Comment by denis-sokolov** [comment] 2023-07-29 14:27
Thank you, @fatcerberus. Your explanation and references help a lot to understand this. I am very familiar with widening, but I always assumed it was a property of certain operations involving mutable bindings, not a hidden flag on a type. I will join you, then, in questioning whether the function boundary should be a barrier for the widening flag. In my case I spent a notable amount of time debugging, because the source of the type and its use were far from each other, and I specifically used to treat function signatures as encapsulated.
