### ISSUE TITLE
type inference error in multi-olverloads function body

### ISSUE THREAD

**Issue by dardino** [Microsoft/TypeScript#25865] opened 2018-07-23 11:51 UTC
**TypeScript Version:**  2.9

**Search Terms:**
method overloads when pipe

**Code**

```ts
class C1 { P1: string; }
class C2 { P2: string; }
class C3 { P3: string; }

function a(value: C1 | null): string;
function a(value: C2 | null): string;
function a(value: C1 | C2 | null): string {
    return "";
}

var b = (value?: C1 | C2 | C3 | null | undefined): string => {
    if (value instanceof C1) return a(value);  // C1 : no error OK!
    if (value instanceof C2) return a(value);  // C2 : no error OK!
    return value ? value.P3 : ""; // : no error OK!
}

var c = (value?: C1 | C2 | C3 | null | undefined): string => {
    if (value instanceof C1 || value instanceof C2)        
        return a(value); // C1 | C2  --> not null or undefined, there is no reasons to give an error...
        // is a(C1) a valid call? YES
        // is a(C2) a valid call? YES
        // why error? !!KO!!
    return value ? value.P3 : ""; // no error OK!
}

```

**Expected behavior:**
no errors in the function "c" because is exactly the same as function "b"

**Actual behavior:**
error in function "c":
```
Argument of type 'C1 | C2' is not assignable to parameter of type 'C2'.
  Type 'C1' is not assignable to type 'C2'.
    Property 'P2' is missing in type 'C1'.
(parameter) value: C1 | C2
```

**Playground Link:** 
[PlayGround](http://www.typescriptlang.org/play/index.html#src=class%20C1%20%7B%20P1%3A%20string%3B%20%7D%0D%0Aclass%20C2%20%7B%20P2%3A%20string%3B%20%7D%0D%0Aclass%20C3%20%7B%20P3%3A%20string%3B%20%7D%0D%0A%0D%0Afunction%20a(value%3A%20C1%20%7C%20null)%3A%20string%3B%0D%0Afunction%20a(value%3A%20C2%20%7C%20null)%3A%20string%3B%0D%0Afunction%20a(value%3A%20C1%20%7C%20C2%20%7C%20null)%3A%20string%20%7B%0D%0A%20%20%20%20return%20%22%22%3B%0D%0A%7D%0D%0A%0D%0Avar%20b%20%3D%20(value%3F%3A%20C1%20%7C%20C2%20%7C%20C3%20%7C%20null%20%7C%20undefined)%3A%20string%20%3D%3E%20%7B%0D%0A%20%20%20%20if%20(value%20instanceof%20C1)%20return%20a(value)%3B%20%20%2F%2F%20C1%20%3A%20no%20error%20OK!%0D%0A%20%20%20%20if%20(value%20instanceof%20C2)%20return%20a(value)%3B%20%20%2F%2F%20C2%20%3A%20no%20error%20OK!%0D%0A%20%20%20%20return%20value%20%3F%20value.P3%20%3A%20%22%22%3B%20%2F%2F%20%3A%20no%20error%20OK!%0D%0A%7D%0D%0A%0D%0Avar%20c%20%3D%20(value%3F%3A%20C1%20%7C%20C2%20%7C%20C3%20%7C%20null%20%7C%20undefined)%3A%20string%20%3D%3E%20%7B%0D%0A%20%20%20%20if%20(value%20instanceof%20C1%20%7C%7C%20value%20instanceof%20C2)%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%20%20%20%20return%20a(value)%3B%20%2F%2F%20C1%20%7C%20C2%20%20--%3E%20not%20null%20or%20undefined%2C%20there%20is%20no%20reasons%20to%20give%20an%20error...%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20is%20a(C1)%20a%20valid%20call%3F%20YES%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20is%20a(C2)%20a%20valid%20call%3F%20YES%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20why%20error%3F%20!!KO!!%0D%0A%20%20%20%20return%20value%20%3F%20value.P3%20%3A%20%22%22%3B%20%2F%2F%20no%20error%20OK!%0D%0A%7D)

**Related Issues:** 
#25637
#25791
#25826

**Comment by j-oliveras** [comment] 2018-07-23 12:44
From [FAQs](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-am-i-getting-supplied-parameters-do-not-match-any-signature-error): A function or a method implementation signature is not part of the overloads.

Add another overload to function a:
```ts
function a(value: C1 | null): string;
function a(value: C2 | null): string;
function a(value: C1 | C2 | null): string;
function a(value: C1 | C2 | null): string {
    return "";
}
```

**Comment by AlCalzone** [comment] 2018-07-23 14:51
@j-oliveras that was going to be my first response too, but then I thought the error is a bit illogical.

In the line where the error occurs, we know that value is either a `C1` or a `C2`. For both options, an overload of `a` exists. There's probably some design limitation or intent behind this, but why should `((value: C1) => string) | ((value: C2) => string)` not be callable with a `C1 | C2`?

**Comment by j-oliveras** [comment] 2018-07-23 15:22
@AlCalzone In this case, it is duplicate of #14107 and #1805.

**Comment by AlCalzone** [comment] 2018-07-23 16:01
And possibly related: https://github.com/Microsoft/TypeScript/issues/7294
```ts
type Foo = ((val: number) => any) | ((val: string) => any);
let f: Foo;
f(1); // error: Type Foo lacks a call signature
```

**Comment by dardino** [comment] 2018-07-31 13:25
@j-oliveras I am not the owner of ".d.ts" file that describes the overloads. I can't add the overloads as you suggest.

**Closed** 2018-07-31 16:48 UTC
Labels: Duplicate
