### ISSUE TITLE
Narrowing type via Function Assertion loses numeric type

### ISSUE THREAD

**Issue by eyedean** [microsoft/TypeScript#37807] opened 2020-04-06 12:23 UTC
**TypeScript Version:**  3.9.0-dev.20200406

**Search Terms:** assertion, function, narrowing, numeric types

**Code**

```ts
// GOOD EXAMPLE
function f1(x: any): asserts x is number | undefined { }
let v1: number | string | undefined;
f1(v1)
type t1 = typeof v1; // t1 = number | undefined, as excepted

// BUGGY EXAMPLE
function f2(x: any): asserts x is 6 | undefined { }
let v2: number | string | undefined;
f2(v2)
type t2 = typeof v2; // t2 = undefined.  Expected to be 6 | undefined
```

**Expected behavior:** `t2` must be `6 | undefined`.

**Actual behavior:** `t2` is `undefined` only.

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play?ssl=10&ssc=52&pln=1&pc=1#code/GYVwdgxgLglg9mABMAjACgB4C5EEMwCeAlDrgM5kCmATlGYhojPWCALYBGNiAPouABNKwGGEoDEAb0QBfALAAoADaUoiAG4ocrTtz5ko1UQHNe-MEJFiBAbkWo0mooqgEADpURQUiALxf3SjhgDRQbRAB6CK8ffx0uajNBYVFxPHpKDAhKNyhxRQKFUEhYBGQAJkxSQhJ0qlp6RmZEADYkixTrKVlFFTV1cu12BLMDIzBTPmSrcTsiyoHnBVcPL3K-AI9gjXLwqLWN6dSBADpEVqZ6JTgDAEJFIA)

**Related Issues:** I went through the comments of the popular https://github.com/microsoft/TypeScript/pull/32695 by @ahejlsberg and also searched in the existing issues but couldn't find any similar problem being reported in the past.

FWIW, I ran into this trying to write a `assertIsInEnumValues` for Numeric Enums.  (related StackOverflow question: https://stackoverflow.com/a/61058457)

**Comment by jack-williams** [comment] 2020-04-06 13:54
I think this is a duplicate of #31156

**Comment by eyedean** [comment] 2020-04-06 14:33
@jack-williams thanks for commenting.  It's definitely not limited to `undefined` (I just tested and it has the same bug with `boolean` as well).  However,  I can definitely smell that "branded primitives" discussed at https://github.com/microsoft/TypeScript/pull/31206 might have caused it.

**Comment by sandersn** [comment] 2020-04-07 23:50
Yep, it's a duplicate of #31156 -- the unions on the source and target are the cause. Swapping `undefined` for `boolean` has the same problem.

**Closed by sandersn** 2020-04-07 23:50 UTC
