### ISSUE TITLE
Allow locally scoped temporary invalid types

### ISSUE THREAD

**Issue by glenjamin** [microsoft/TypeScript#46776] opened 2021-11-11 11:03 UTC
# Suggestion

## 🔍 Search Terms

temporary, transient

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

This suggestion is possibly a bit out there, it is inspired by the design of Clojure's [transients](https://clojure.org/reference/transients). It's possible I've overlooked something obvious and that there are existing patterns for this sort of code which I've just failed to find.

The idea would be to provide some way to mark some code as allowed to fail type checks, but with the expectation that at the end of the code, it is correct.

## 📃 Motivating Example

Consider this relatively common pattern (usually with a more complex operation than `toString`).

```ts
const obj1 = {a: 1, b: 2, c: 3};
const obj2: { [k in keyof typeof obj1]: string } = {};
let k: keyof typeof obj1;
for (k in obj1) {
  obj2[k] = String(obj1[k]);
}
```

This code doesn't work, because the initial value of `obj2` is invalid - but we don't have a valid value we can use instead - and after the loop the value of `obj2` satisfies the type.

## 💻 Use Cases

The current workarounds for this that I'm aware of usually involve extracting a helper function, and then using some type assertions inside that function to handle the transient state.

**Comment by whzx5byb** [comment] 2021-11-11 11:22
You could use `const obj2  = {} as { [k in keyof typeof obj1]: string };`

**Comment by MartinJohns** [comment] 2021-11-11 12:49
You can use a type assertion, as mentioned in the comment before, or alternatively just use `//  @ts-ignore` to ignore the error.

**Comment by glenjamin** [comment] 2021-11-11 13:02
I'm aware that there are ways to make typescript not check the code - but those open up the possibility of a programmer mistake.

The goal with my suggestion here was to allow a way to make typescript fully check the code, but allow the types to be invalid during an intermediary stage.

I have no idea how possible this is in a type-checking system, it was just something that occurred to me while writing the code and I wanted to write it down somewhere.

**Comment by andrewbranch** [comment] 2021-11-11 17:43
Duplicate of https://github.com/microsoft/TypeScript/issues/28503

**Closed** 2021-11-13 18:00 UTC
Labels: Duplicate
