### ISSUE TITLE
Cannot type-guard conditional extends WeakRef

### ISSUE THREAD

**Issue by HunterKohler** [microsoft/TypeScript#45626] opened 2021-08-29 21:55 UTC
# Bug Report

### 🔎 Search Terms

- WeakRef
- weakreference
- conditional
- conditional type
- conditional not assignable
- return type not assignable
- conditional typeguard
- instanceof 
- instanceof typeguard
- instanceof extends

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about:
    - Generics
    - Typeguards

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&ts=4.5.0-dev.20210826#code/PQKhCgAIUhJAzSADAbgQwDYFcCmTICWAzpGsgOo5oDWASjvEgDSQBOOALlqwHaQcALHJAAmOdvHE4eAYxwjIAewBGAKxwyOLRa34DWigO6F4UGAQ6QBaEspzTIAczStlaR8JmKMGDR3kAdJAAohhEOCzsXLzI6Nh4QSDA4PBYshwEinwAHmISADwAKgB8ABRxuABckIUAlNWFkDjZ-jwiJJQ09PD5BDySugCqxZAA-JCDkA2QAN5QkAsEiOWYuIQ8RBxosjiKiJ10DLWz8wtnkF4blnGQALyQFTgBeQyltQDc4KfnJpClAIRxY5zH6gvQGYw8HDGYKsAysUoAIgAwoosBgFDxFJYXgNpHJER9vucAL5fMFsTjcPhxT6k8lnKLUh6rHCfMlAA)

### 💻 Code

```ts
/**
 * If `value` is a `WeakRef`, return the dereferenced object, or throw if
 * it has been garbage collected. Else, return `value`. */
function xderef<T>(value: T): T extends WeakRef<infer U> ? U : T {
    if (value instanceof WeakRef) {
        const val = value.deref();

        if (!val) {
            throw new ReferenceError(value);
        }

        return val;
    }

    return value;
}
```

### 🙁 Actual behavior

Compiler reports, on the final return statement `return value`:
> Type 'T' is not assignable to type 'T extends WeakRef<infer U> ? U : T'.

### 🙂 Expected behavior

Compiler would recognize that `T` does not extend WeakRef, thus that `T` must only be compatible with itself.

**Comment by jcalz** [comment] 2021-08-30 02:23
duplicate of #33912

**Closed** 2021-09-03 18:00 UTC
Labels: Duplicate
