### ISSUE TITLE
In JS, `C.prototype = Object.create(B.prototype)` should behave like `extends`

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#22639] opened 2018-03-16 16:55 UTC
```ts
// @noEmit: true
// @allowJs: true
// @checkJs: true
// @Filename: a.js

// from enhanced-resolve
function T() {
    this.plugins = {}
}
T.prototype.plugin = function (name, f) {
    this.plugins[name] = f
}
function R(fs) {
    T.call(this)
    this.fs = fs
}
R.prototype = Object.create(T.prototype) // should create an extends: R extends T
R.prototype.resolve = function resolve(name) {
    this.plugin(name, p => p)
}
```

**Expected behavior:**
`R` behaves like `T` is its base class: `this.plugin` inside `resolve` should be legal.

**Actual behavior:**
Property 'plugin' does not exist on type '{ fs: any, resolve: (name: any) => void }'

**Comment by mhegazy** [comment] 2018-03-28 22:40
Duplicate of https://github.com/Microsoft/TypeScript/issues/18609

**Closed** 2018-04-12 16:27 UTC
Labels: Duplicate
