### ISSUE TITLE
Spreading breaks with any typed object and another key with undefined value.

### ISSUE THREAD

**Issue by cvle** [Microsoft/TypeScript#13388] opened 2017-01-10 14:20 UTC
**TypeScript Version:**  2.1.4 

**Code**

```ts
const a: any;
const c = { ...a, b: undefined };
```

**Expected behavior:**
`c` should be of type `any`.

**Actual behavior:**
Random variables across project are falsely marked as having implicitly an any type.
```
node_modules/@types/mocha/index.d.ts(20,5): error TS7008: Member 'reporter' implicitly has an 'any' type.
node_modules/@types/mocha/index.d.ts(29,5): error TS7008: Member 'grep' implicitly has an 'any' type.
node_modules/@types/mocha/index.d.ts(49,6): error TS7006: Parameter 'error' implicitly has an 'any' type.
node_modules/@types/mocha/index.d.ts(82,48): error TS7006: Parameter 'options' implicitly has an 'any' type.
node_modules/@types/mocha/index.d.ts(222,42): error TS7006: Parameter 'options' implicitly has an 'any' type.
node_modules/@types/recompose/index.d.ts(83,9): error TS7006: Parameter 'initialState' implicitly has an 'any' type.
node_modules/@types/recompose/index.d.ts(166,22): error TS7006: Parameter 'value' implicitly has an 'any' type.
node_modules/@types/recompose/index.d.ts(211,9): error TS7006: Parameter 'value' implicitly has an 'any' type.
node_modules/@types/recompose/index.d.ts(271,30): error TS7006: Parameter 'stream' implicitly has an 'any' type.
...
```

**Comment by mhegazy** [comment] 2017-01-10 18:09
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/12822. can you give `typescript@next` a try.

**Closed** 2017-01-10 18:09 UTC
Labels: Duplicate
