### ISSUE TITLE
Issue with Array.Map and Object.Assign

### ISSUE THREAD

**Issue by TomPridham** [Microsoft/TypeScript#15675] opened 2017-05-08 19:54 UTC
**TypeScript Version:**  2.2.2

**Code**

```ts
        const checks = [...Array(3)].map(Object.assign({}, {checked: false}));
        console.log(checks);
```

**Expected behavior:**
logs:[{checked:false}, {checked:false}, {checked:false}]

**Actual behavior:**
logs: [undefined, undefined, undefined]

**Comment by mhegazy** [comment] 2017-05-08 19:59
Duplicate of https://github.com/Microsoft/TypeScript/issues/8856

**Comment by mhegazy** [comment] 2017-05-22 22:34
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-05-22 22:34 UTC
Labels: Duplicate
