### ISSUE TITLE
Broken instanceof type guarding

### ISSUE THREAD

**Issue by nin-jin** [Microsoft/TypeScript#17424] opened 2017-07-26 06:49 UTC
**TypeScript Version:**  2.4.0

**Code**

```ts
class A { foo: string }
class B { bar: string }

function test(x : A | B) {
  if (x instanceof A) {
    console.log(x.foo);
  } else {
    console.log(x.bar); // Expected typeof x == A|B
  }
}

test({ foo: "Hello, world" }); // undefined
```

**Expected behavior:**

Error at this line:

```
    console.log(x.bar);
```

Because x can implement A (and not implement B) interface but do not be instance of A class.

**Actual behavior:**

No errors. Wrong result.

**Comment by ikatyang** [comment] 2017-07-26 06:57
Duplicate of #17344

**Comment by mhegazy** [comment] 2017-08-17 17:13
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-08-17 17:13 UTC
Labels: Duplicate

**Comment by nin-jin** [comment] 2017-08-17 18:54
My issue is not about nominal typing. My issue is about wrong logic. If `x` is instance of class `A`, then `x` implements interface `A`. But if `x` is not instance of `A, then `x` can implement and can implement not interface `A`. Be attentive! 

![](https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Venn_A_intersect_B.svg/350px-Venn_A_intersect_B.svg.png)

**Comment by mhegazy** [comment] 2017-08-17 19:00
@nin-jin, you are correct, except that most uses of this pattern assume that `A` and `B` are disjoint, and a check for inclusion in `A` implicitly checks for exclusion from `B` . you can see more about the rational for the current design in https://github.com/Microsoft/TypeScript/issues/1719#issuecomment-73746885

**Comment by nin-jin** [comment] 2017-08-17 19:22
In **most uses** `else` block assume that `B` is `any`. Why you broke logic for incorrect uses? You will take more and more issues about it until fix it.
