### ISSUE TITLE
Function autocomplete suggestions include those of incorrect type

### ISSUE THREAD

**Issue by Mike-Dax** [microsoft/TypeScript#57618] opened 2024-03-03 02:50 UTC
### 🔎 Search Terms

"function autocomplete", "function parameter autocomplete", 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about autocomplete suggestions.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gRgKygXigbwFBW1AZge3wC4oAiOAQwCdSMBfDDAeiagHUALCAOylDACW3AOZQA5AXxiANFAq5gEKny7jcYqAGMO1CpsVVZwVVQgBnYFHy4V0CYQ1gq+SFVBQBZ21e4AbEFZgwAL4vELeFACuwPia+AC2YL4QilC+nsCyFF4QAB6Q+hAAJgB0GHHcFlaIJPBIqGh4hCTk1KRQDBj80ACCKOhyJMBUkdAM3VAAQv2NcEMjY4y4kdz6Ibyh-gAqFADW5pMAFHNTAJTonRVVFBQkfQ2DfAsd5aHXJ9MPJ8OjLxibIB2+zMRxupwwQA

### 💻 Code

```ts
type A = { a: true }
type B = { b: true }

function onlyTakesB(b: B) {}

const aa: A = { a: true }
const ab: B = { b: true }

onlyTakesB(a)
//          ^| at this point while typing, `aa` is suggested incorrectly.
```

### 🙁 Actual behavior

When typing 'a', `aa` is suggested as the first result, because it is alphabetically earlier, despite it having the wrong type.

It's unhelpful to suggest an option that immediately results in a type-checkable error.

![image](https://github.com/microsoft/TypeScript/assets/13504878/6f48de86-f0de-426c-91be-d5e4187c9834)

### 🙂 Expected behavior

I'd expect `ab`, the variable in scope that has the correct type, to be suggested with priority. (I would expect options with incompatible types to not be suggested at all, implying a filter instead of a sort.)

When typing object property names, this kind of thing is inferred correctly.

**Comment by fatcerberus** [comment] 2024-03-03 03:10
Duplicate of https://github.com/microsoft/TypeScript/issues/57547.

**Comment by RyanCavanaugh** [comment] 2024-03-04 18:13
You can install the [IntelliCode for TS](https://devblogs.microsoft.com/typescript/intellicode-for-typescript-javascript/) extension to get some heuristic-based resorting

**Closed** 2024-03-07 01:16 UTC
Labels: Duplicate
