### ISSUE TITLE
forceConsistentCasingInFileNames flag issues when renaming files on OSX

### ISSUE THREAD

**Issue by Hotell** [Microsoft/TypeScript#26157] opened 2018-08-02 14:20 UTC
**TypeScript Version:**  2.9.2
**OS:** macOs HighSierra

**Search Terms:** forceConsistentCasingInFileNames

**Code**

**tsconfig:**

```json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "esnext",
    "target": "es5",
    "lib": [
      "dom",
      "es2018"
    ],
    "strict": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "suppressImplicitAnyIndexErrors": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "react",
    "jsxFactory": "React.createElement",
    "sourceMap": true,
    "outDir": "dist/esm5",
    "declaration": true,
    "declarationDir": "dist/types",
    "declarationMap": true,
    "stripInternal": true,
    "resolveJsonModule": true,
    "importHelpers": true
  },
  "include": [
    "./src"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "buildOnSave": false
}
```

**Reproduce the issue**

```sh
git clone https://github.com/Hotell/typescript-lib-starter && cd $_

mv src/Greeter.ts src/greeter.ts
mv src/__tests__/Greeter.spec.ts src/__tests__/greeter.spec.ts
```

```diff
// src/__tests__/greeter.spec.ts
+import { Greeter } from '../greeter'
-import { Greeter } from '../greeter'
```
![image](https://user-images.githubusercontent.com/1223799/43589842-dc27e67a-966f-11e8-8b7d-5b4fb5367c9b.png)

**Expected behavior:**

No errors

**Actual behavior:**

When `"forceConsistentCasingInFileNames": true` is set and user renames file `Greeter.tsx` -> `greeter.tsx`, he get's 

```
TS1149: File name '/Users/mhotell/Projects/devel/github/@Hotell/realma/src/greeter.tsx' differs from already included file name '/Users/mhotell/Projects/devel/github/@Hotell/realma/src/Greeter.tsx' only in casing
```

And it looks like the former file is cached somewhere somehow

![ts-issue-file-name-casing](https://user-images.githubusercontent.com/1223799/43589173-768908d6-966e-11e8-8993-e6e3b04b1b56.gif)

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/17617

**Comment by Hotell** [comment] 2018-08-02 14:29
Current hot fix:

```sh
mv src/greeter.ts src/greeter-tmp.ts
mv src/__tests__/greeter.spec.ts src/__tests__/greeter-tmp.spec.ts

git add .
git commit -m "casing fix"

mv src/greeter-tmp.ts src/greeter.ts
mv src/__tests__/greeter-tmp.spec.ts src/__tests__/greeter.spec.ts

git add .
git commit --amend
```

**Comment by mhegazy** [comment] 2018-08-02 23:48
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/19329

**Closed** 2018-12-15 18:00 UTC
Labels: Duplicate
