### ISSUE TITLE
TS7022 (implicity 'any' type) popping up in a random scenario

### ISSUE THREAD

**Issue by joshlang** [microsoft/TypeScript#59880] opened 2024-09-06 15:34 UTC
### 🔎 Search Terms

TS7022
TS7022: 'result' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

### 🕗 Version & Regression Information

Using typescript 5.5.4

### ⏯ Playground Link

[TS Playground](https://www.typescriptlang.org/play/?#code/CYUwxgNghgTiAEkoGdnwMIQJYgHYBd4BvAKHnmT2AAoAPALgvxi1wHN4AfeAV11ABmrEMACUjZM1ZsyFKnQlT2XXvxBDcIgDSIARo2qj4AXgB88AG4B7LGMbXbsgPRP4APQC0H+CBgwrMPBsViBoUADuUACe8FgC8FYWvhBWUMCxaHAAtokiJAC+JCRgVriSiCbE+fAoGNh4+CQQIIQMTCzK3HyCwunG8ABEAwDcJC7uXj5+AUEhYZExcfAA5P1Dyxnw2bnAY66e3r7+gcGhNQux8ctdahoiG1iZIDlJuyThABZYzfDUzDwgIykcjjA5TY6zM4RaLwfAfBAlUAZXDLQisGrwFJWAAORXIJTKhDgyB4EEI-TAADpKPw6KJnPtJkcZgAVADKAHYAAwAJh5jGWxNJ+AeWWx2DAWHwEBiH1q+Ci2IQyyguCiG104CgPEosUIwDm8FwVkIcqSGIVSpquGN+Cg+CwpWt6UeW3UvjwYBE8GAWDgYGlMRmrF9-sDsVwerQVnCkdYUqwUGwAC9fJS8fBaJUhWSGRNDtMToboYt4uEEGl0qqTfDAthNJnKkMCkA)

### 💻 Code

```
declare class Client {
  send(x: string | undefined): string
  send(x: string | undefined, cb: () => void): void
  // ^-- error goes away if overload is removed
}

const c = {} as Client
let x: string | undefined = "";
// ^-- error goes away if '= ""' is removed
// ^-- error goes away if '| undefined' is removed

while (true) {
  // ^-- error goes away the code isn't in a loop

  const result = c.send(x)
  // ^-- error TS7022: 'result' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

  x = result
  // ^-- error goes away if we add another line x = ""
}
```

### 🙁 Actual behavior

error TS7022: 'result' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

### 🙂 Expected behavior

`result` is of type string

### Additional information about the issue

This scenario is minimal..  But the actual scenario it was encountered in wasn't contrived, and is probably pretty common.  We were using cognito client from @aws-sdk/client-cognito-identity-provider and looping results, updating a PaginationToken.

**Comment by MartinJohns** [comment] 2024-09-06 15:38
Did you mix up actual and expected behavior? It's the first time I read someone actually expecting that error.

**Comment by joshlang** [comment] 2024-09-06 15:38
> Did you mix up actual and expected behavior? It's the first time I read someone actually expecting that error.

yes - fixed

**Comment by MartinJohns** [comment] 2024-09-06 15:50
Then it's essentially a duplicate of #50696 and many others.

**Comment by RyanCavanaugh** [comment] 2024-09-06 15:54
`result` really does have a circular dependency on itself

**Comment by joshlang** [comment] 2024-09-06 16:49
> `result` really does have a circular dependency on itself

Hrmm... Well, I can see how `result` being fed back into `x`... which is fed into the function which is called to initialize `result` could be seen that way

But ...really?

c.send has only a single parameter, which can match only a single function, which definitely returns `string`.  You'd think it'd be safe to realize "hey, this is a string".

But if there's technical specs/challenges to unravelling it... so be it.  Then I should have made it a "feature request" :)

**Comment by nmain** [comment] 2024-09-06 17:01
Resolving the overload needs the current CFG narrowed types of all parameters, ref https://github.com/microsoft/TypeScript/issues/35638#issuecomment-566158599.  Figuring out that the overload can be resolved without the narrowing in this specific case isn't something that can be easily applied in general.

**Comment by joshlang** [comment] 2024-09-06 19:03
I'm super curious...

```
Change
let x: string | undefined = "";
to
let x: string | undefined;
```

And the entire problem goes away.  It can magically resolve the overload, and do whatever other sorcery is required, all of a sudden.

**Comment by MartinJohns** [comment] 2024-09-06 19:13
> I'm super curious...
> 
> ```
> Change
> let x: string | undefined = "";
> to
> let x: string | undefined;
> ```
> 
> And the entire problem goes away. It can magically resolve the overload, and do whatever other sorcery is required, all of a sudden.

In one case the type of `x` is `string`, in the other case it's `string | undefined`.

**Comment by joshlang** [comment] 2024-09-06 19:22
> > I'm super curious...
> > ```
> > Change
> > let x: string | undefined = "";
> > to
> > let x: string | undefined;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And the entire problem goes away. It can magically resolve the overload, and do whatever other sorcery is required, all of a sudden.
> 
> In one case the type of `x` is `string`, in the other case it's `string | undefined`.

Interesting.

`let x: string | undefined = "" as string | undefined;`
or
`x = result as string | undefined`

Those both make the problem go away

but 
`x = (result as string | undefined)?.toString()`

makes the problem come back again

...Anyway, it's clearly just something that'll have to be worked around for now.

**Closed** 2024-09-09 01:32 UTC
Labels: Not a Defect
