### ISSUE TITLE
Type to invert optionality of properties

### ISSUE THREAD

**Issue by CzBuCHi** [microsoft/TypeScript#16173] opened 2017-05-31 14:56 UTC
add new mapped type: `Invert<T>` ... I do not know, how to explain it in english, so i use code:

```ts
// proposal syntax
type Invert<T> = {
    [P in keyof T]?: T[P];
    [P? in keyof T]: T[P];
};

// usage
type Original = {
    first: any;
    second?: any;
}

type Inverted = Invert<Original>;

// type Inverted is threated as if declared like this:
type Inverted = {
    first?: any; // first is optional becasue it was required in Original
    second: any; // second is required becasue it was optional in Original
}
```

example usage: react defaultProps - to ensure, that all optional props are declared.

```ts
type SomeProps = {
    name: string;
    point?: { x: number, y: number };
}

class Some extends React.Component<SomeProps, void> {
    // proposal usage
    static defaultProps: Invert<SomeProps> = {
        // here i get compiler error if do not specify property 'point'
    };

    // current usage (worst)
    static defaultProps: any = {
        // here i dont get any errors at all
    };

    // better
    static defaultProps: Partial<SomeProps> = {
        // here i dont get any errors if i dont specify point
        // but at least get compiler error for typo...
    };

    // even better
    static defaultProps: { name?: string; point: { x: number, y: number } } = {
        // here i get compiler error if do not specify property 'point' and for typo
        // but i was forced to create new type ...
    };
}
```
priority: really low, almost negative :) - but if it can be done and isnt too hard ...

**Comment by SaschaNaz** [comment] 2017-05-31 20:28
Interesting use case for me, but how about this way:

```ts
type Optional<T> = {
    [key in keyof T]?: T[key];
}

interface DefaultProps {
    point: { x: number, y: number };
}
interface SomeProps extends Optional<DefaultProps> {
    name: string;
}

var x: SomeProps = {
    name: 'abc' // error if missed
};
var y: DefaultProps = {
    point: { x: 0, y: 0 } // error if missed
};
```

**Comment by CzBuCHi** [comment] 2017-05-31 20:38
Yes that will work too ... but in the end u need to define two separated tytes...

**Comment by mhegazy** [comment] 2017-08-25 21:39
Duplicate of https://github.com/Microsoft/TypeScript/issues/13224

**Comment by CzBuCHi** [comment] 2017-08-26 10:32
@mhegazy i dont think this is a dupe,,.

both #13224 and #15012 are trying to make all properties required:
```ts
type Original = {
    first: any;
    second?: any;
}

type Result = {
    first: any;
    second: any;
}

im trying to 'flip' required flag on each property:
```ts
type Original = {
    first: any;
    second?: any;
}

type Result = {
    first?: any;        // because Original.first was required
    second: any;    // because Original.second was not required
}
```

but if u really think this is a dupe fell free to close it ...

**Comment by mhegazy** [comment] 2017-08-28 23:26
do you have a scenario where flipping optionality is required?

**Comment by CzBuCHi** [comment] 2017-08-29 06:17
@mhegazy look at my initial message ... bacically to have react component defaults required for optional props.

BTW: I think that i can achieve it by this code: (not tested)
```ts
module ISomeProps {
    export interface Req {
        first: any;
    }
    export interface Def {
        second:any;
    }
}
interface ISomeProps extends ISomeProps.Req, Partial<ISomeProps.Def> {}

class Some extends React.Component<ISomeProps, never> {
    static defaultProps: Partial<ISomeProps.Req> & ISomeProps.Def = {
        second: 42
    };
    
    ...
}
```

**Comment by Gerrit0** [comment] 2020-02-22 00:11
You can do this with existing TS features.

We first need two helpers.

```ts
type OptionalKeys<T> = {
    [K in keyof T]-?: undefined extends { [K2 in keyof T]: K2 }[K] ? K : never
}[keyof T]
type RequiredKeys<T> = Exclude<keyof T, OptionalKeys<T>>
```

The `RequiredKeys` helper is straightforward, but `OptionalKeys` is kind of tricky. Optionality is preserved if you don't specify `-?` or `+?` when using a mapped type. This lets us detect if a property is marked with `?` (as opposed to just being unioned with `undefined`).

That is, given:
```ts
type Original = {
    first: string;
    second?: number;
    req: any;
    opt?: any;
    unioned: string | undefined;
}
```

Then `OptionalKeys<Original> = 'second' | 'opt'`, which does not include `'unioned'`, even though it may be `undefined`

With these helpers, then `Invert` just becomes a simple intersection type.

```ts
type Invert<T> = {
    [K in OptionalKeys<T>]-?: NonNullable<T[K]>
} & {
    [K in RequiredKeys<T>]+?: T[K]
}
```

This *almost* gives you the exact behavior that the OP asks for, but TS will display the properties as an intersection. You can merge the intersection back into a single object type with a mapped type that does nothing..

```ts
type MergeIntersection<T> = { [K in keyof T]: T[K] }

type OptionalKeys<T> = {
    [K in keyof T]-?: undefined extends { [K2 in keyof T]: K2 }[K] ? K : never
}[keyof T]
type RequiredKeys<T> = Exclude<keyof T, OptionalKeys<T>>

type Invert<T> = MergeIntersection<{
    [K in OptionalKeys<T>]-?: NonNullable<T[K]>
} & {
    [K in RequiredKeys<T>]+?: T[K]
}>

type Original = {
    first: string;
    second?: number;
    req: any;
    opt?: any;
    unioned: string | undefined;
}

type InvertedTest = Invert<Original>;
// On hover shows:
// type InvertedTest = {
//     second: number;
//     opt: any;
//     first?: string | undefined;
//     req?: any;
//     unioned?: string | undefined;
// }
```

[Playground](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=30&pc=5#code/C4TwDgpgBAshBOBzCBJAdsBBnCBjYAlgPZoA8AKgHxQC8UA3lANoDSUBaUA1hCEQGZRyAXQBcQ1sKgBfALAAoBaEhQA8mEIkAhgBsWvLBWp16CqOeZsO3XgKHCAtAH5xAVzQATCPw4QPUCAAPTE8sBksAJnZOHj5BEXEWKOlJKCcoNnE0CAA3BAUU2LsRJXBoACUIAEdXAng-fRBDKlooAFFA3B1XL1Ii+IAaNQ1iNF1G5spKBVKVdDz4YCNWuCRUDGw8TTJTeQtLaOHt8YMjRxcoADkSS9cdHS0AIx0ICklp+WkoADIGMwtWIdKjU6g1TlRhABqC7kSQFD6zaCqeAERAcXStXb7HzwLDAcR4lFoRAAbn+5hwuBIHguaFcAFtHggyXsLPUquItGgQCz9kQNBcuTzyVB3KM-ATgETEFAAD6izzeXweFlyRTyZTQeYITAecgQPGtbWLUjI1HonSUFkAemtak4AAsiAsoFgnQB3LCiBS2qCaqDG3X6w0mH12-aU6lZBlM+A28MWfn4qBC+P7KA4vEXQkcGXy9xeHzZFVh9PswXctP7MUkPzZqW5uUKwvKtPSIA)

**Comment by RyanCavanaugh** [comment] 2024-03-04 22:31
We're not adding new utility types to the lib.

**Closed by RyanCavanaugh** 2024-03-04 22:31 UTC
Labels: Suggestion, Awaiting More Feedback

**Comment by jkomyno** [comment] 2024-03-07 03:04
> We're not adding new utility types to the lib.

Why? The `Invert` type defined [above](https://github.com/microsoft/TypeScript/issues/16173#issuecomment-589889174) is quite useful when it comes to e.g. providing default values to an object containing some partials.

**Comment by RyanCavanaugh** [comment] 2024-03-07 16:20
People don't agree with the "right" definition of any given utility type and get upset that we didn't use their version
