### ISSUE TITLE
Allow circular references in type aliases

### ISSUE THREAD

**Issue by samvv** [Microsoft/TypeScript#8408] opened 2016-05-01 15:13 UTC
Building on a [question I asked on StackOverlow](http://stackoverflow.com/questions/36966444/how-to-create-a-circularly-referenced-type-in-typescript/36967300#36967300), I was wondering if it would be a nice addition if it would be possible to define types recursively. If I am guessing correctly this wouldn't be too difficult to implement.

Example:

```ts
type Document = [number | string | Array<Document>]
```

Currently, according to the [spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.11.8), only classes and interfaces are allowed to reference themselves. Is there a reason for this?

> Classes and interfaces can reference themselves in their internal structure...

**Comment by malibuzios** [comment] 2016-05-01 16:13
Here are two related issues: #3496, #6230

**Comment by mhegazy** [comment] 2016-05-01 18:51
As @malibuzios noted, looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/6230

**Closed by mhegazy** 2016-05-01 18:51 UTC
