### ISSUE TITLE
type narrowing for common testing patterns

### ISSUE THREAD

**Issue by rkirov** [microsoft/TypeScript#9693] opened 2016-07-13 19:08 UTC
When using 'strictNullChecks' with common testing libraries (jasmine, chai), one cannot easily express the intent that below a `expect(result).toNotBeNull();` statement the object is non-null. The only solution that comes to mind is pervasive use of type assertion operator (!). Consider:

``` typescript
interface I {
  a: string;
  b: string;
  c: string;
}

declare function fnToTest(i: string): I|null;

function test() {
  let result: I|null = fnToTest('input');
  expect(result).toNotBeNull();
  expect(result!.a).toBe('foo');
  expect(result!.b).toBe('bar');
  expect(result!.c).toBe('buz');
}
```

I attempted to model the type of `expect` and `toNotBeNull` as:

``` typescript
interface Tos<T> {
  toBe(exp: T): void;
  toNotBeNull(): never;  // if T is null
  toNotBeNull(): void;   // if T is not null
}

declare function expect<T>(t: T): Tos<T>;
```

But I can't tell the type system to use a different function overload based on type of the type variable `T` (left in comments). Even if that was possible, I am also not sure if narrowing would propagate based on the never type.

**Comment by RyanCavanaugh** [comment] 2016-07-13 21:35
Open to ideas on what would be possible. One suggested workaround would be to write:
```ts
  expect(result).toNotBeNull();
  result = result!;
  expect(result.a).toBe('foo');
  expect(result.b).toBe('bar');
  expect(result.c).toBe('buz');
```
or even just
```ts
let result = fnToTest('input')!;
```
In test code like this where you're explicitly asserting the postconditions and depending on an external library to provide control flow, there's not a lot of value to be gained having the types be 100% accurate when 99% will do the job better.

**Comment by isiahmeadows** [comment] 2016-12-13 16:41
Partial (albeit broader) dupe of #8655.

**Comment by RyanCavanaugh** [comment] 2020-07-21 22:37
We've added assertion functions now and I don't think we'd go further without more feedback specific to patterns like this that indirect control flow away from the tested vlaues.

**Closed by RyanCavanaugh** 2020-07-21 22:37 UTC
Labels: Needs Proposal, Suggestion
