### ISSUE TITLE
support globs in tsconfig.json files property (or just file/directory exclusions)

### ISSUE THREAD

**Issue by JeroMiya** [Microsoft/TypeScript#1927] opened 2015-02-04 18:00 UTC
An extension to https://github.com/Microsoft/TypeScript/pull/1692

Our ts project uses a grunt-based build system, with bower dependencies for the application and node_modules for build-tools. We will need the ability to exclude node_modules and bower_components from the build by default (unless files are referenced via /// <reference path="..." />).

This causes an issue: we have end-to-end tests running in protractor, as well as unit tests running in jasmine, and unless we have the ability to exclude node_modules and bower_components, both will be parsed and we'll get duplicate definition errors.

In Visual Studio today, this is why we need to exclude both bower_components and node_modules from the project, because visual studio automatically parses all files in the project with no way to exclude them except to keep them out of the project altogether.

A number of third party tools have started to support tsconfig.json, and one thing I've noticed is that most of them support some sort of extension to tsconfig.json that supports file globs. I propose we just add support into the spec for file globs. For the version of typescript on npm, we can just depend on the appropriate file glob libraries in the npm ecosystem. For the Visual Studio embedded version of TypeScript, just embed the glob libraries that are needed statically in the installation.

As a fallback, if the notion of including a third party glob library is a non-starter, then the following fallback supporting a subset of the glob patterns would solve our problem at least partially.

Fallback:
Support both file and directory inclusions and exclusions in the files property:
```
files: [
  'app/', (equivalent to 'app/**/*.ts')
  '!e2e/', (equivalent to '!e2e/**/*.ts')
  '!node_modules/',
  '!app/bower_components/',
  '!app/vendor/fooLib/fooLib.ts'
]
```

**Comment by danquirk** [comment] 2015-02-04 22:29
We certainly talked about this for awhile. See Anders' comment here for one large concern: https://github.com/Microsoft/TypeScript/pull/1692#issuecomment-70262537

**Comment by JeroMiya** [comment] 2015-02-04 23:20
Yes, I've read that comment. Unfortunately, for larger and more complicated projects, the lack of these glob and exclusion patterns makes it impossible to use tsconfig.json at all. If editors support tsconfig.json, we would end up having to disable it due to various errors in mismatched configuration between e2e, unit tests, and the application. And, if the editor uses tsconfig.json to configure compile-on-save and auto-complete in a standard way (and doesn't support a way to override this in a custom project file format, or extension to tsconfig.json as is the case with atom-typescript for example), then we've lost all of that functionality as well.

Globs and exclusion patterns are just how large typescript projects are made managable. We manage it now with build tools like grunt and gulp which support globs and exclusions, but so far the editors and IDEs haven't been configurable in the same way, leading to messy workarounds. For example, in visual studio we have to exclude all the end to end tests from the main app project so it doesn't parse them and complain about duplicate identifiers. We then have a separate visual studio project which just includes the end to end tests. We should be doing the same thing with unit tests, but we decided not having jasmine type declarations visible from the application code was not worth creating a separate unit test project. I would rather edit files in the project all at once, like I would do in Sublime or Atom or Brackets.

**Comment by NoelAbrahams** [comment] 2015-02-05 10:31
@JeroMiya, perhaps the real problem here is how the projects are organised. I would consider moving the tests (both unit and end-to-end) to a separate project(s). IMO it's a better practise to keep tests and application code separate.

**Comment by JeroMiya** [comment] 2015-02-05 14:11
There are many style guides out there advocating for grouping files by feature. We've tried it both ways and find that grouping things by feature instead of by file type helps you be more productive, especially for larger projects with hundreds of features. You tend to work on a particular feature at a time, and it's a real pain to track down all the files related to that feature when they're spread out across multiple root directories. This way also encourages developers to write unit and end to end tests at the same time as changes to the code. I highly recommend it over splitting keeping test code separate from the application code.

Regardless, as a compiler, TypeScript should not be opinionated about project file organization.

**Comment by NoelAbrahams** [comment] 2015-02-05 14:27
Fair enough. We tried the grouping files by feature before moving the test cases out. Having test code in the same place as application code made it difficult to prototype features, because a lot of time was spent fixing compilation errors in the test cases.

**Comment by basarat** [comment] 2015-02-11 00:34
FYI [atom-typescript](https://atom.io/packages/atom-typescript) supports `filesGlob` as an optional extension to `files`. See [spec](https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md).

**Comment by NoelAbrahams** [comment] 2015-02-11 09:32
@basarat,

```JavaScript
    "filesGlob": [
        "./**/*.ts",
        "!node_modules/**/*.ts"
    ]
```

That looks like a nice feature, because it actually plays well with "files". I wonder what the objection from the TS team is to including this.

Perhaps the argument is: One cannot post the `tsconfig` to someone else to say "Hey, here's a description of all the files in my project".

**Comment by basarat** [comment] 2015-02-11 09:50
Just a note: whenever atom-typescript reads a file with `filesGlob` it expands the `files` in 'tsconfig.json' file so that people that are not using atom-ts will still get the correct list of files.

**Comment by rcollette** [comment] 2015-03-05 05:50
+1 
Globs are so common in use now.  There could be .ts files in bower components under my project which have already been compiled to js and may have been done with a different release of TS so I wouldn't want them recompiling.   I guess exclusion would handle the case but it just seems like once you support globs you won't need anything else.   

I think leaving this up to an IDE to edit, like atom-typescript,  is a bad idea.  You're basically asking every IDE to implement the logic to keep the tsconfig.json file up to date.

**Comment by bidiboom** [comment] 2015-04-03 08:05
I'm in the same case as @JeroMiya , complexe project (e2e, unit test and project code). The outDir option is really good to this kind of project so we can cleanly separate our TS code from the produce code : no accidental JS code modification by the team for example. And this glob option is almost mandatory for our kind of project due the number of file. Thanks to Gulp, we can handle this point but it can be really good to have this glob supported by the tscong file

**Comment by panuhorsmalahti** [comment] 2015-04-07 17:40
Globs are definitely needed. I don't see how I could manage the complex, multi-package TypeScript-based platform at work without globbing. Referencing every file by hand would be madness and require large amount of unnecessary work.

Globbing is especially useful when working with npm. I can depend on a npm package (which includes the type definitions), and then glob them in without knowing about the internals of that package.

Using the current setup in our project I can simply build package A, which consists of multiple modules, then require it from package B and glob the type definitions without any manual work even if the file structure of package A changes.

In theory the package A could output a single type definition file, but this is not supported by TypeScript, as each module of package A will create it's on .d.ts file. I already had to do a bit magic by writing a sort of "compiler" to make the .d.ts files ambient external declaration files automatically.

**Comment by park9140** [comment] 2015-04-18 01:05
@ahejlsberg, @basarat,  a few thoughts on this.

One major issue with, .net projects in general, is with source control systems and project files.  By inserting a file reference into your project file every time a new file is added to a folder you end up with additional and unnecessary churn in your repository.  

On larger projects with multiple teams working on them you constantly end up with conflicting changes to files like tsconfig.  As such in addition to unnecessary file churn we now have additional labor to manually merge changes to a file that could be automatically handled.

**Comment by basarat** [comment] 2015-04-18 01:12
> As such in addition to unnecessary file churn we now have additional labor to manually merge changes to a file that could be automatically handled.

Agreed and would be great to have `filesGlob` supported.

FWIW If its a merge commit just delete the `files` section and let atom-typescript regenerate it for you. If its a rebase I chose "keep both" at each level ;). YMMV. Definitely needs glob support.

**Comment by mhegazy** [comment] 2015-04-18 05:10
We would be open to taking a PR for excludes folders.

Our problem with globs is the complexity to support it, and we usually do not like to take dependencies on other packages as it limits our interoperability and system-independence. Having said so I think it is an important feature and indead does add value. Would be open to proposals here.

**Comment by basarat** [comment] 2015-04-18 07:33
So no for stuff like : https://github.com/aspnet/Home/wiki/Project.json-file#sources ? 

FWIW I don't have a big issue with the workaround we've managed :). An updating project file isn't a problem new or annoying to me personally.

**Comment by johnpapa** [comment] 2015-04-22 22:51
tldr; Wow, we need this to support glob patterns.

Here is my use case ... I have a project with a few 100 files in TS and several 3rd party libraries with a concatenated lib.d.ts file. I want intellisense everywhere with the least amount of friction.

Option 1) Add /// reference to every file to point to the lib.d.ts and leave the tsconfig's file array undefined so it reads all of my app TS. Downside ... every file has this extra line ... yuk (100's of places)

Option 2) Add a gulp task that creates the files array in the tsconfig.json with the 3rd party lib.d.ts and my .ts files (lots of them). Downside, a gulp task to keep up, but at least my code is untouched

Option 3) Add glob support to tsconfig's files array so I can do this 

```
files: ['lib.d.ts', '**/*.ts`]
```


I vote for option 3. So much easier and less friction for devs.

**Comment by dmorosinotto** [comment] 2015-04-24 00:35
+1 for globs in files with syntax for exclusion 
files: ["lib.d.ts", "**/*.ts", "!node_modules/**/*.ts"]

**Comment by elishnevsky** [comment] 2015-05-13 17:32
I see this issue is still open. Is support for glob patterns in tsconfig.json still being considered? That would make so many developers happy.

**Comment by CyrusNajmabadi** [comment] 2015-05-13 17:52
Is there a standard file-globbing specification anywhere?  If we do this, we'll need to ensure that the globbing works the same on unix/windows, and that likely means writing the code to understand it ourselves.

**Comment by danquirk** [comment] 2015-05-13 17:56
Ideally we could just use some existing thing like https://www.npmjs.com/package/glob rather than rolling our own :(

**Comment by CyrusNajmabadi** [comment] 2015-05-13 18:03
Ideally.  But can we use such packages from tsc.exe where we don't have access to node packages?

**Comment by ahejlsberg** [comment] 2015-05-13 18:20
Right, the issue is that tsc.exe and the VS language service aren't in a position to take a dependency on node.js and therefore we can't use the node.js glob package. My feeling is that our best option so far is what is suggested in #3043: An `exclude` property in tsconfig.json that specifies a list of files and folders to exclude when a `files` list isn't explicitly specified. The net effect is the same as globbing with the list `["**/*.ts"]` followed by a bunch of excludes. For example
```javascript
{
    exclude: ["node_modules", "tests"]
}
```
would be equivalent to the globbing pattern `["**/*.ts", "!node_modules/**/*.ts", "!tests/**/*.ts"]`.

**Comment by poelstra** [comment] 2015-05-13 18:23
> Is there a standard file-globbing specification anywhere?

@CyrusNajmabadi There's the well-known [`.gitignore`](http://git-scm.com/docs/gitignore), although that of course is the 'inverse' of e.g. Atom Typescript's filesGlob.

@danquirk That package seems to have problems completely excluding a directory (see e.g. https://github.com/TypeStrong/atom-typescript/issues/332), which is a must for excluding large node_modules folders. Additionally, it has had some breaking changes in the way it interprets its globs, and is apparently going to remove the negate-option.

**Comment by CyrusNajmabadi** [comment] 2015-05-13 18:24
Dan mentioned another possibility would be for us to just include glob.js in our compiler (if it was appropriately licensed).  Then we would at least have the same syntax/behavior as an extremely popular package in the node space.

**Comment by poelstra** [comment] 2015-05-13 18:33
@ahejlsberg Note that a pattern like `"!node_modules/**/*.ts"` would indeed lead to the same end-result, but will likely still traverse the full node_modules tree (because of the explicit `*.ts` at the end). Better would be e.g. just `"!node_modules/"` (or `"!node_modules/**"`, if it detects that as a prefix-pattern).

**Comment by ahejlsberg** [comment] 2015-05-16 18:52
Just put up #3188 that adds support for "exclude" in tsconfig.json.

**Comment by ejsmith** [comment] 2015-06-07 13:38
Exclude is not enough. Almost all other modern dev tools are supporting globbing. How can I say that I want all files from 2 folders and not include anything else without having to list individual files?

**Comment by ingo777** [comment] 2015-06-09 16:31
I think there is another use case which will not be fulfilled with an exclude option: `["**/*.ts", "!**/*.spec.ts"]`

**Comment by ejsmith** [comment] 2015-06-09 16:43
Yes, there are many scenarios that aren't covered by a simple exclusion.

**Comment by kpko** [comment] 2015-08-18 15:49
Hi,

is this still a thing? We have a huge typescript project and want to convert from the Visual Studio integrated typescript compilation to tsconfig.json files. We organized our files (mostly components) into many subfolders and it would be great if we could import them into the compilation without having to write hundreds of lines of "files" array items.

**Comment by panuhorsmalahti** [comment] 2015-08-18 16:15
Tip: you can use the "unofficial" glob property with e.g. atom-typescript and it works fine (the plugin will autocomplete all the files from the globs). It would be nice to get this into core, of course.

**Comment by awerlang** [comment] 2015-08-24 17:40
@kpko if you have a root folder from where you want to compile of files in subdirectories, just start `tsc` from that folder.

AFAIK, the current state doesn't handle well multiple input folders, and excluding unit and e2e tests inside feature folders.

**Comment by philpowers** [comment] 2015-08-24 20:47
tsconfig.json absolutely needs glob support!  There are just so many common use cases that are not covered by the very simple "exclude" support.

As a language that is supposed to make large-scale Javascript development more scalable and maintainable (and I do love TypeScript), it seems like being able to create a directory structure in whatever arbitrary format is most suitable to the project would be one of the most fundamental features. Currently this is NOT possible. Heck, even having basic wildcard support in both the "files" and "exclude" would be a big step in that direction.

**Comment by tjoskar** [comment] 2015-08-25 05:53
@philpowers +1, I totally agree! We need `glob` support.
However, typescript accepts pull request, right? So anyone who has a solution to the problem can make it real.

**Comment by mhegazy** [comment] 2015-08-25 19:56
@rbuckton submitted a PR for this (https://github.com/Microsoft/TypeScript/pull/3232), but got busy with other issues. if someone is willing to take over the PR, and add verification for it, please let us know.

**Comment by cjones26** [comment] 2015-08-28 15:19
@panuhorsmalahti Great tip, thank you!  Figured this would work but didn't actually try it until I saw your comment.

**Comment by jimthedev** [comment] 2015-09-21 18:12
Since there hasn't been movement on this in a month I would just echo what others have noted. 

An exclude property may accomplish some of the goals of globs but it does not go far enough. In fact I think it can give your team a false sense of security. It makes it too easy to break if you're working in a large team of devs of varying attention to detail. Someone drops a file in the root of the project and forgets to add it to the exclude? Bam you're in trouble. Team conventions are more often than not phrased like this: 'put all of your .ts files inside of ./app if you want them covered by code coverage'. Similarly, it would be helpful if typescript merged the filesGlob and files arrays for a really comprehensive solution to this problem.

**Comment by nickroberts** [comment] 2015-09-22 19:04
Please listen to the community and add support for `filesGlob`. It makes things so much easier. We have people using all sorts of editors and IDEs, and it we were to have glob functionality, it would clean our code up so much more, along with providing a better cross platform solution.

We can achieve this through the `npm` package `tsconfig-glob`, but we really would like a standard solution, where we didn't have to run a gulp task.

`atom-typescript` already does a nice job of this, although all it does is update the `files` array (so does `tsconfig-glob`). If the `files` array could just accept globs...WIN!

**Comment by mhegazy** [comment] 2015-09-24 04:06
This is on the list of features to support; that is why the issue is still open. The core team had limited resources, so we can not get to everything all the time. As mentioned in https://github.com/Microsoft/TypeScript/issues/1927#issuecomment-134720294, we are open to accepting help here.

**Comment by krimple** [comment] 2015-10-07 17:45
+1 for filesGlob support on tsc...  would be a great update.

**Comment by zdychacek** [comment] 2015-10-07 18:21
+1 globbing should be standard feature

**Comment by gentisaliu** [comment] 2015-10-09 16:40
+1

**Comment by m4cx** [comment] 2015-10-12 12:38
+1

**Comment by donaldpipowitch** [comment] 2015-10-13 07:35
Just want to point out that this sadly limits `jsconfig.json`, too. https://twitter.com/ErichGamma/status/653835875835604992

**Comment by AbubakerB** [comment] 2015-10-14 10:44
+1

**Comment by PLEEROCK** [comment] 2015-10-15 17:13
+1

**Comment by FlorianKoerner** [comment] 2015-10-18 13:56
+1

**Comment by marcosbasualdo** [comment] 2015-10-21 19:20
+1

**Comment by BretJohnson** [comment] 2015-10-21 21:17
+1 for filesGlob on tsc

**Comment by hrajchert** [comment] 2015-10-21 21:41
+1

**Comment by juergenzimmermann** [comment] 2015-10-25 09:16
:+1:

**Comment by Manuel-S** [comment] 2015-10-26 11:40
+57

**Comment by AngelMunoz** [comment] 2015-10-28 08:43
+1 :)

**Comment by ToddThomson** [comment] 2015-10-31 19:13
I've added file glob pattern matching to "files" in [TsProject](https://github.com/ToddThomson/tsproject). At any time you can use the setting "convertFiles" to have TsProject write the expanded source file set to the "files" property.

**Comment by Exagram** [comment] 2015-11-18 15:32
+1

**Comment by pankleks** [comment] 2015-11-19 21:49
+1

**Comment by glen-84** [comment] 2015-11-20 08:59
Whitelisting (include) is almost always better than blacklisting (exclude). It's easy to forget to exclude something, but things simply won't work unless you include them. However, listing every file manually is crazy, especially in larger projects. With the current options, there is just no flexibility.

@mhegazy, would you please consider adding this to the roadmap? It seems that a large part of the work has already been done in #3232, so perhaps it wouldn't take too long to finalize (for someone familiar with the code)?

**Comment by mhegazy** [comment] 2015-11-21 01:18
Not to sound like a broken record, but please see my reply in https://github.com/Microsoft/TypeScript/issues/1927#issuecomment-142804773. I believe adding [`exclude`](https://github.com/Microsoft/TypeScript/pull/3188) unblocked many scenarios, adding the full glob support is still open, but it is not on the top of the list of features that the core team is working on right now. If some one is interested to help out, we are open to accepting PRs.

**Comment by jpierson** [comment] 2015-11-23 22:11
+1

**Comment by falsandtru** [comment] 2015-11-26 17:50
+1 I already use globs with tsc.

**Comment by pope-tailors** [comment] 2015-12-23 18:01
+1

**Comment by wk-cof** [comment] 2015-12-23 18:02
+1

**Comment by heidgert** [comment] 2015-12-28 13:44
+1

**Comment by danikenan** [comment] 2015-12-29 09:29
+1

**Comment by Daskul** [comment] 2016-01-02 07:19
+1

**Comment by laholmes** [comment] 2016-01-04 10:31
+1

**Comment by SebastianSchenk** [comment] 2016-01-04 18:06
+1

**Comment by bartvanderwal** [comment] 2016-01-05 09:15
+1

**Comment by BernhardSchopper** [comment] 2016-01-05 09:43
+1

**Comment by eiweiss** [comment] 2016-01-05 10:43
+1

**Comment by romiem** [comment] 2016-01-05 17:23
+1 for filesGlob

**Comment by donaldpipowitch** [comment] 2016-01-05 20:13
Could this topic please be closed for discussion to stop more "+1"?

**Comment by samvloeberghs** [comment] 2016-01-12 09:32
@NoelAbrahams can you elaborate why testing should be seperated from your code? And more about why it's best practise? I for example put my unit test file right next to the file/code I'm testing. That saves me a lot of time and frustration looking for what code I'm testing exactly.

**Comment by NoelAbrahams** [comment] 2016-01-12 09:35
@samvloeberghs, quote from my comment above:

> Having test code in the same place as application code made it difficult to prototype features, because a lot of time was spent fixing compilation errors in the test cases.

**Comment by bartvanderwal** [comment] 2016-01-12 14:19
@samvloeberghs @NoelAbrahams I thought about this too.

### My fifty cents
I normally follow [John Papa's style](https://github.com/johnpapa/angular-styleguide#organizing-tests) to mix tests/specs and regular code. Otherwise you get two hierarchies within `app/` and `test/` that you also need to keep in sync.

However the standard .NET approach is to have a separate test folder (e.g. File -> New project -> ... 'Do you want to add a test project?'). And I guess if you need to add in a lot of extra dependencies for the test framework this might make sense.

The compilation issues that start when you change types can be considered one of the rawbacks of Typescript. The same safety net that is normally added value now holds you back. In old skool plain Javascript tests you could just use features like `it.skip(..)` or `describe.skip`. But for typescript now ofcourse you would need to really comment the test cases out again. Or alternatively you could take out the strict typing in your file and the `///<reference` s of external lib's (`d.ts`), though those are often implicit in editors.

Ofcourse some would also argue that you should strictly follow TDD's write-tests-first approach. In which case on a refactor you would also need to REwrite-tests-first. It obligates you to think about changes in spec/behaviour before making changes, which could result in better quality. But for real life projects it's hard to always stick to such strict ordering.

**Comment by krimple** [comment] 2016-01-12 14:24
Given there are so many people looking for a resolution, I realize that the team put it below other things on the priority list, but it makes zero sense to have to edit tsconfig.json every time I add a new TypeScript file to a project. This reminds me of Java Struts with the struts Config file. It is not flexible when you are working at speed and have to keep remembering to add a line to a file. 

I know, JS developers just finally got a module system, ES6 syntax, and good build tools to concatenate files like Webpack, etc., but still have this little annoyance that to me seems it should be easy to fix.

Ken

**Comment by glen-84** [comment] 2016-01-12 14:39
@krimple & others,

It's in development (https://github.com/Microsoft/TypeScript/pull/5980) and [scheduled](https://github.com/Microsoft/TypeScript/wiki/Roadmap#20) for TypeScript 2.0, so we just have to be patient.

**Comment by samvloeberghs** [comment] 2016-01-12 14:42
@glen-84 great! thx for the update

**Comment by krimple** [comment] 2016-01-12 15:15
Glen,

That's good news.  I am watching this because Angular 2 uses TypeScript extensively, and Angular developers want to get a jump on using it. Is TypeScript 2.0 going to be compatible with Angular 2 as it sits now, or will it bring breaking changes that will make us have to wait for the Angular team to upgrade to TypeScript 2?

**Comment by glen-84** [comment] 2016-01-12 19:05
> Is TypeScript 2.0 going to be compatible with Angular 2 as it sits now, or will it bring breaking changes that will make us have to wait for the Angular team to upgrade to TypeScript 2?

I'm not sure if anyone can really answer this right now (even the TS developers), as we still have to get through v1.8, but v2.0 is obviously a major version, so that does allow for BC breaks. I have the same amount of information as you do (from the roadmap, etc.).

However, I'm sure that the Angular developers will be keeping a close eye on TypeScript development. =)

**Comment by Fire-Dragon-DoL** [comment] 2016-01-17 21:26
Good point `tsconfig-glob` solves (mostly) the issue

**Comment by basarat** [comment] 2016-01-17 23:38
> Good point node package tsconfig-glob solves (mostly) the issue

atom-typescirpt internally uses the public package : https://github.com/TypeStrong/tsconfig so that its not atom-ts specific :rose:

**Comment by rezonant** [comment] 2016-01-24 22:28
+1

**Comment by robbatt** [comment] 2016-02-02 14:04
+1

**Comment by nhhockeyplayer** [comment] 2016-02-05 23:06
my filesglob isnt compiling all my app/**/*.ts
and I have to specify each file individually
is there something wrong with this ?

**Comment by Fire-Dragon-DoL** [comment] 2016-02-05 23:10
@nhhockeyplayer filesGlob is not standard, there is a tool that converts filesGlob pattern into `files` array, check a few posts earlier

**Comment by ToddThomson** [comment] 2016-02-06 21:12
TsProject supports file globs; minifies Typescript source; generates library and components packages and produces a single d.ts def file. file globs can be converted back to regular use for adherence to the standard.
TsProject is a NPM node package. I built it for my internal needs, but have and will add features that consumers need.

**Comment by aliatsis** [comment] 2016-03-05 02:09
+1

**Comment by MrJH** [comment] 2016-03-07 15:23
+1

**Comment by myusrn** [comment] 2016-03-08 23:14
does what is being proposed here allow me to have a projectroot/app/tsconfig.json and projectroot/scripts/tsconfig.json and in them, as well as projectroot/gulpfile.js tsc settings, specify an include of type definition files in their parent folders node_modules path, e.g. include ../node_modules/**/*.d.ts ?

**Comment by nenadvicentic** [comment] 2016-03-19 17:47
+1

For me, this would do the trick:

```
{
  ...
  "files": [
    "bower_components/**/dist/*.d.ts",
    "app"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by joshheyse** [comment] 2016-03-23 19:43
I'm not sure excludes: [] option is going to able to handle enough scenarios, especially if it is mutually exclusive of files: [].

A lot of our projects have the following structure
``` 
├── node_modules
├── src
│   ├── client
│   │   ├── tsconfig.json
│   ├── common
│   ├── server
│   │   ├── tsconfig.json
├── node_modules
├── typings
├── gulpfile.js
├── package.json
├── tsd.json
```

There are 2 tsconfig files, 1 for the browser and one for node, each with different compile settings and file subsets. 

Client tsconfig files: `['**/*.{ts,tsx,js,jsx}', '../common/**/*{ts,tsx,js,jsx}', '../../typings/browser.d.ts']`.
Server tsconfig files: `['**/*.{ts,js}', '../common/**/*{ts,js}', '../../typings/main.d.ts']`.

The tsconfig in the client directory should include all nested script files, plus the files in common and the browser typings.

The tsconfig in the server directory should include all nested script files, plus the files in common and the main (node) typings.

I haven't been able to come up with a combination of exclude or files (NON GLOB) that won't force me to be continuously managing the files array manually.

Currently we are maintaining the list of file manually. We tried to use atom-typescript to rewire the tsconfig, but it has problems with multiple tsconfig files in a single atom project. 

I don't understand why file globing rules can't be used, they can satisfy all the requirements using a standard simplistic rule set.

**Comment by glen-84** [comment] 2016-03-27 10:27
@myusrn - Good question. I'll need the same thing. I would be quite surprised if this was not supported.

@nenadvicentic - You would use the `include` key in future, and the `exclude` in your case would not be needed.

@joshheyse - You can also use `exclude` to exclude everything except the files that you need. So for the client you would have something like:

```json
"exclude": [
    "gulpfile.js",
    "node_modules",
    "src/server",
    "typings/main",
    "typings/main.d.ts"
]
```

A bit less to maintain, but still not ideal.

> I don't understand why file globing rules can't be used ...

See [my comment](https://github.com/Microsoft/TypeScript/issues/1927#issuecomment-170931593) above.

**Comment by jagt** [comment] 2016-04-03 17:01
I've just started looking into typescript and the most frustrating thing is to get the 'namespaces' to work. Turns out I'll have to list all my files in `tsconfig` and the namespace resolution order will be correct. If I don't have the `tsconfig` (I'm using VS2015) or I omit the `files` section, the namespace will just break and I'll end up with an very stupid error on runtime, caused by the files are concated in random order.

I really like how VS intergrates TypeScript and how the intellisense works almost like wring C#, but the whole thing around namespace and files glob is so irritating and I don't know why there's nobody doing anything with this.

**Comment by myusrn** [comment] 2016-04-03 19:39
@jagt i'm thinking that explicitly listing the files you want to compile in tsconfig.json is not the norm and that more often then not one relies on tsconfig.json processing to process all *.ts files found in that path and below it except for excluded entries.

As for namespace resolution I've never run into any issues around ordering.   I'm wondering if perhaps the matter here is not having a module loader in place, e.g. systemjs universal module loader, which as i understand it takes cares of loading import referenced namepaces.  Once typescript enables use of es6 oob module loader support in, in target: "es5" output, then i'd guess one shouldn't have to enable any module loader in order to get import referenced namespaces loaded in relevant order.

**Comment by jagt** [comment] 2016-04-05 16:18
@myusrn I'm sorry about my wording of my last post. It really gets me after searching here and there trying to resolve this weird issue. I'd give you a detailed walk-through of what I've encountered.

As I stated before I've just started looking into TypeScript and started a VS2015 TS project. The first thing I tried to do, after going through syntax and stuff, is to separate code into multiple files. I tried using Modules first, and noticed that it needs an third party module loader like require.js. I'm not that into front end and don't have interest into loader things, and I found out there's this thing called Namespace, which seems to fit my needs exactly, as all I want to do is simply separate my source into multiple files. I do what the doc says, separate my test Class into an other file, and import it from my entry file. It compiles fine but fails in the browser. I checked the compiled output and figured it put the generated class after the first import statement, which is obviously wrong.

After a while I figured I have two solutions, one is to add `<reference>`  comments, which I suppose is deprecated, and the other one to make it work is to manually list all my files in the `tsconfig.json`. If I do any of this the project will just work, and I'm sticking to the later one.

To make a long story short, I'm trying to find something like browserify in TS and figured that I can do that with namespace and listing files in `tsconfig.json`, which is kind of confusing.

Again thanks for your kind reply. I really like TypeScript and its VS integration, and despite of this issue (I had worse experience with other technologies :wink: ) most things goes where.

**Comment by myusrn** [comment] 2016-04-05 17:10
@jagt i haven't heard anything about use of /// <reference path="<path to .d.ts>" being deprecated and in fact you can see that's what i ended up using in https://github.com/myusrn/acxwithng2 and https://github.com/myusrn/dnxwithng2 main.ts files to allow me to use tsconfig.json with just excludes and still retain support for d.ts sources that exist in some of the excluded folders.

**Comment by dachibro** [comment] 2016-04-08 17:51
@myusrn +1

**Comment by thefabulousdev** [comment] 2016-04-25 20:08
+1, its already a year later :disappointed:

**Comment by trickpattyFH20** [comment] 2016-05-11 17:07
+1

**Comment by glen-84** [comment] 2016-05-11 17:20
@trickpattyFH20 Please use [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) now, instead of +1 comments.

**Comment by dmagoo** [comment] 2016-05-16 22:00
This would also be useful for avoiding ENOENT errors when using an editor that writes and removes backup files fairly often. I find it tripping over /.#file.ts which is often used by emacs.

**Comment by alexandrudima** [comment] 2016-06-01 08:22
For anyone interested in a workaround until `filesGlob` is added to `tsconfig.json`:

I've published [typescript-with-globs](https://www.npmjs.com/package/typescript-with-globs) that you can install side-by-side with `typescript` and you can begin using `filesGlob` in `tsconfig.json`.

After installing, you can use `tscg` (note the extra `g`) and it will first resolve the globs from `filesGlob` to the `files` section and then proceed to invoke `tsc`.

**Comment by mchambaud** [comment] 2016-06-01 18:56
@alexandrudima 👍

**Comment by glen-84** [comment] 2016-06-16 10:29
Shouldn't this be added to the `TypeScript 2.0` milestone (along with the PRs)?

**Comment by mhegazy** [comment] 2016-06-22 16:47
should be addressed by https://github.com/Microsoft/TypeScript/pull/8841.

**Closed by mhegazy** 2016-06-22 16:47 UTC
Labels: Committed, Fixed, Suggestion

**Comment by IAMtheIAM** [comment] 2017-09-15 20:15
Great, in case anyone wonder, the property for including files as well as globs is "include"
