### ISSUE TITLE
Lint rule for definite assignment assertions with immediate initialization

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#21207] opened 2018-01-16 20:53 UTC
```ts
var x!: number = 2;

class Class {
  a!: number = 10
}
```

Seems like a weird construct. In #20117 we said we should write a lint rule for this.

**Comment by ajafff** [comment] 2018-01-17 13:04
@DanielRosenwasser I just tried `typescript@next` and I get an error from typescript for both definite assignment assertions.

> A definite assignment assertion '!' is not permitted in this context.

That means there is no need for a lint rule for declarations with initializer.

---

I'm currently only linting for assertions that are unnecessary because the type is an undefined union:

```ts
let foo!: string | undefined; // unnecessary assertion
```

---

```ts
class Foo {
    prop!: string; // unnecessary assertion
    constructor() {
        this.prop = 1;
    }
}
```

To detect if a definite assignment assertion is unnecessary because the property is initialized in the constructor (see above), we'd need a new API (similar to #20221 but specialized for properties)

**Comment by mhegazy** [comment] 2018-01-17 17:40
@ajafff u are right about the new API. I think this can be lumped with #20221, asking if the property is definitely assigned at the end of the constructor.

**Comment by mhegazy** [comment] 2018-01-17 17:41
Marking as `Working as Intended` since the examples in the OP are already reported as errors.

**Closed** 2018-02-01 20:48 UTC
Labels: Working as Intended
