### ISSUE TITLE
Exporting function with property declaration causes invalid type emit

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#31918] opened 2019-06-15 10:10 UTC
**TypeScript Version:**  3.5.1

**Search Terms:**

function property declaration, emit, multiple

**Code**

```ts
export function foo () {

}
foo.x = 32;

export function bar () {

}
bar.x = 32;
```

**Expected behavior:**

Not have default exports

**Actual behavior:**

```ts
declare function foo(): void;
declare namespace foo {
    var x: number;
}
/*
A module cannot have multiple default exports.ts(2528)
__test-function.d.ts(10, 16): Another export default is here.
*/
export default foo;
declare function bar(): void;
declare namespace bar {
    var x: number;
}
/*
A module cannot have multiple default exports.ts(2528)
__test-function.d.ts(5, 16): The first export default is here.
*/
export default bar;

```

**Playground Link:** 

Playground does not generate .d.ts files

**Related Issues:**

**Comment by AnyhowStep** [comment] 2019-06-15 10:23
Actually, even having just one will make it use `export default`, which isn't what I want at all =/

**Comment by AnyhowStep** [comment] 2019-06-15 10:24
The solution seems to be,

```ts
function foo () {

}
foo.x = 32;

function bar () {

}
bar.x = 32;

export {foo, bar}
```

**Comment by AnyhowStep** [comment] 2019-06-15 10:31
It seems like this does not happen with TS 3.3

**Comment by fatcerberus** [comment] 2019-06-15 14:48
Related to, and possibly a duplicate of #31676, it looks like.

**Comment by AnyhowStep** [comment] 2019-06-15 19:01
Ah, yes, it is a duplicate of that. Thank you for finding it!

**Closed** 2019-06-15 19:01 UTC
