### ISSUE TITLE
Union on interfaces bypasses typecheck of property

### ISSUE THREAD

**Issue by akloeber** [Microsoft/TypeScript#29198] opened 2018-12-29 16:46 UTC
**TypeScript Version:**  Version 3.3.0-dev.20181229

**Search Terms:**
- union
- interface
- typecheck

**Code**

```ts
interface Foo {
  foo: 'FOO';
}

interface Bar {
  bar: 'BAR';
}

const o: Foo | Bar = {foo: 'FOO', bar: 'xxx'};
```

**Expected behavior:**
The assignment should raise an error as the value `'xxx'` for property `bar` does not match interface `Bar`.

**Actual behavior:**
Compilation succeeds.

**Comment by ajafff** [comment] 2018-12-29 20:55
Duplicate of #20863

**Comment by akloeber** [comment] 2018-12-30 10:37
@ajafff Yes, looks like a duplicate of #20863. Unfortunately I didn't find this issue although I spent some time looking through issues that sounded similar.

**Closed** 2019-01-06 18:00 UTC
Labels: Duplicate
