### ISSUE TITLE
Can't export abstract class by default

### ISSUE THREAD

**Issue by dempfi** [Microsoft/TypeScript#11778] opened 2016-10-21 09:30 UTC
**TypeScript Version:**  2.0.3

**Code**

```ts
export default abstract class SomeClass {
}
```

**Expected behavior:** The code above should result in export by default of abstract class `SomeClass`.

**Actual behavior:** Compiler throws an error `error TS1005: ';' expected.`. Export in new line works fine:
```ts
abstract class SomeClass {
}
export default SomeClass
```

**Comment by yortus** [comment] 2016-10-21 11:48
Duplicate of #3792 and others. Please be courteous to the team and [search for existing issues first](https://github.com/Microsoft/TypeScript/issues/11749#issuecomment-255186526). Note that comment was for another duplicate of this same issue opened just a day ago.

**Closed** 2016-10-21 12:10 UTC
