### ISSUE TITLE
RequestInit api change no longer compiles

### ISSUE THREAD

**Issue by vrachels** [Microsoft/TypeScript#19658] opened 2017-11-01 18:17 UTC
using typescript 2.6.1

lib.dom.d.ts defines RequestInit with:
headers?: Headers | string[][];

(used to be 'any')

the headers as object option no longer works in ie fetch(file, { ... headers: { Accept: ....} })

see also #18073

**Comment by mhegazy** [comment] 2017-11-01 19:56
Duplicate of https://github.com/Microsoft/TypeScript/issues/19656

**Closed** 2017-11-16 16:57 UTC
Labels: Duplicate
