### ISSUE TITLE
Can no longer write deep predicates in conditional types

### ISSUE THREAD

**Issue by geoffreytools** [microsoft/TypeScript#52271] opened 2023-01-17 12:25 UTC
# Bug Report

### 🔎 Search Terms

conditional types, generics, deep, predicate

### 🕗 Version & Regression Information

This changed between versions 4.8.4 and 4.9.4

### ⏯ Playground Link

[Playground link with the code bellow](https://www.typescriptlang.org/play?ts=4.9.4#code/C4TwDgpgBAYg9nAPAQQDRQEID4oF4oDaamAulBAB7AQB2AJgM5QCuNA1jXAO40El9QA-JgCGAJ0RF0GEjgBcUAOQQANgwiKAUJtCRREgCrkqtRi3acefPjnwGgA)

### 💻 Code

```ts
type Foo<A,B> = [A, B] extends unknown[][] ? Bar<[A, B]> : 'else'
//                                               ~~~~~~
// Type '[A, B]' does not satisfy the constraint 'unknown[][]'.

type Bar<T extends unknown[][]> = T
```
This is not limited to tuples
```typescript
type Foo<A> = Set<A> extends Set<unknown[]> ? Bar<Set<A>> : 'else'
//                                                ~~~~~
// Type 'Set<A>' does not satisfy the constraint 'Set<unknown[]>'.

type Bar<T extends Set<unknown[]>> = T
```

### 🙁 Actual behavior

There is a type error that literally contradicts the predicate of the conditional

### 🙂 Expected behavior

It should compile with no error

**Comment by jakebailey** [comment] 2023-01-20 06:19
Both of these compile in nightly (soon to be beta) as of #51621, so this looks to be a duplicate of #51614.

**Comment by geoffreytools** [comment] 2023-01-20 15:04
It's great that it is fixed but it must have been in a different PR, or maybe it was an unintentional side-effect, because these 2 issues are not related to me: the outcome of the conditional cannot be known here.

I feel that a test case should be added for this scenario if it hasn't been already.

**Comment by jakebailey** [comment] 2023-01-20 16:40
That PR definitely fixed it; I bisected to confirm before replying.

**Comment by jakebailey** [comment] 2023-01-20 18:38
I've also checked and it was #50397 which regressed this.

**Comment by jakebailey** [comment] 2023-01-20 18:56
Sent #52333 with a test.

**Closed** 2023-01-23 19:59 UTC
Labels: Bug
