### ISSUE TITLE
Wishlist: argument type inference for private methods and local functions

### ISSUE THREAD

**Issue by vivainio** [Microsoft/TypeScript#18912] opened 2017-10-03 17:00 UTC
**TypeScript Version:**  2.5

It should be possible to infer types of non-exported functions and private methods, as the types can be locally established by just looking at the file under compilation.

**Code**

```ts

function inferred(x):
  return x+x

// since we call the function with a number, we should be able to infer the type of x as number instead of "any"

const foo = inferred(2)

// complation should fail as no type can be inferred that supports both calls to 'inferred'.

const bar = inferred( { baz:1} )

```

**Comment by mhegazy** [comment] 2017-10-03 22:55
Duplicate of https://github.com/Microsoft/TypeScript/issues/15114, https://github.com/Microsoft/TypeScript/issues/14078, https://github.com/Microsoft/TypeScript/issues/15016, https://github.com/Microsoft/TypeScript/issues/17428, https://github.com/Microsoft/TypeScript/issues/15196

**Comment by mhegazy** [comment] 2017-10-19 19:53
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-19 19:53 UTC
Labels: Duplicate
