### ISSUE TITLE
respect createElement return type for JSX

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#59007] opened 2024-06-24 23:42 UTC
### 🔍 Search Terms

JSX createElement

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

respect type information for:

```ts

declare namespace React {
    function createElement<Ret extends JSX.Element, Props extends object> (
        component: (props: Props) => Ret,
        props: Props,
    ): Ret;
    namespace JSX {
        interface Element { o: null }
    }
}

function Component (x: {}) { return { o: null, a: null }; }

<Component /> satisfies { o: null, a: null };

```

### 📃 Motivating Example

to support framework write limit for children types, i.e. `<ul>` can only contain `<li>`;

even algebraic effect handler programming for required provide/inject context.

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

**Comment by MartinJohns** [comment] 2024-06-25 00:35
Duplicate of #21699.

**Closed** 2024-06-25 02:54 UTC
