### ISSUE TITLE
Using this in return type of static methods

### ISSUE THREAD

**Issue by pleerock** [Microsoft/TypeScript#15946] opened 2017-05-19 07:09 UTC
I want to implement a simple active record pattern:

```ts
class User extends Model {     

     id: number;
     name: string;

}
```

```ts
class Model {

    static findOneById(id: any): Promise<this> { // I want "this" to be "User", or "Blog", or any other class that extends Model
         return ...;
    }

}
```

usage:

```ts
const user = await User.findOneById(1); // I want type-safe user 
```

Is it possible?

**Comment by pleerock** [comment] 2017-05-19 07:12
If I'm not wrong `php` had similar issues until they introduced a `self` keyword for static methods -  `this` was referenced to current static class, and `self` for what Im describing right now (however Im not sure about, but I think it was so).

**Comment by mhegazy** [comment] 2017-05-19 16:44
Duplicate of https://github.com/Microsoft/TypeScript/issues/5863

**Closed by mhegazy** 2017-05-19 16:44 UTC
