### ISSUE TITLE
Return value with unknown key is not restricted

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#50173] opened 2022-08-04 00:35 UTC
# Bug Report

### 🔎 Search Terms

`return value` `unknown key`

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions __Version 4.7.4____ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
type FooEnv = {
  FOO: string;
};

type BarEnv = {
  BAR: string;
};

type EnvMap = {
  foo: FooEnv;
  bar: BarEnv;
};

function createFoobar<T extends keyof EnvMap>(
  _name: T,
  fn: (ctx: {}) => { env: EnvMap[T] }
) {
  return fn({});
}

createFoobar("foo", () => {
  return {
    env: {
      FOO: "",
      UNKNOWN: 42,
    },
  };
});
```

### Config
```json
{
  "exclude": ["dist"],
  "extends": "@tsconfig/node16-strictest-esm/tsconfig.json",
  "compilerOptions": {
    "noEmit": true
  }
}
```

### 🙁 Actual behavior

No error

### 🙂 Expected behavior

```ts
createFoobar("foo", () => {
  return {
    env: {
      FOO: "",
      // @ts-expect-error
      UNKNOWN: 42,
    },
  };
});
```

```
Type '{ FOO: string; UNKNOWN: number; }' is not assignable to type 'FooEnv'. 
Object literal may only specify known properties, 
and 'UNKNOWN' does not exist in type 'FooEnv'.
```

**Comment by jcalz** [comment] 2022-08-04 01:11
Duplicate of #241, most recent duplicate at #50064

**Closed** 2022-08-06 18:00 UTC
Labels: Duplicate
