### ISSUE TITLE
Incorrectly allowing the use of methods that the return value of Object.groupBy does not have

### ISSUE THREAD

**Issue by kurehajime** [microsoft/TypeScript#59156] opened 2024-07-06 01:14 UTC
### 🔎 Search Terms

Object.groupBy

### 🕗 Version & Regression Information

I tried with `5.2.2` and `5.6.0-dev.20240705`
To see what is happening, you need to add "esnext" to lib.

### ⏯ Playground Link

https://www.typescriptlang.org/ja/play/?ts=5.6.0-dev.20240705#code/MYewdgzgLgBAhgJwTAvDA2gZgDQwIy4AsuBMArLgJy4BMAugFCiSwgBGAVqjAPKcCmwKADoA5ghABXAA4AhAJ4AKRAlyL+ASlQA+GPxgBSGDVQo0ABhgB+GACJ+AN35hbMAFx2QAEy+2NAbgZ2DmEoEABlKAQASzBRRS0AekSYABUAC31QAFtpaIAbfmQ4fPyQAHcIGCh06IhhGAAJCsci3Br9NglKour07qq4MD0kEARhIM4rUIio2PiklIy6mGgC-JhRaKcqjpguioheoZGJcaA

### 💻 Code

```ts
const arr = [3, 1, 4, 1, 5, 9, 2]
const obj = Object.groupBy(arr, (e) => e % 2 === 0 ? "even" : "odd");
obj.toString() // The compiler allows this. However, the browser throws an error.
obj?.toString() // This still gives the browser an error.
```

### 🙁 Actual behavior

The value returned by "Object.groupBy" is an object with null as prototype and does not have toString(). However, TypeScript compilers allow this.

### 🙂 Expected behavior

If a non-existent method such as toString is used in the value returned by "Object.groupBy", the compiler will detect it.

**Comment by kurehajime** [comment] 2024-07-06 01:24
I noticed this after filing an Issue.
This code is more concise.

```
const obj = Object.create(null);
obj.toString()
```

**Comment by MartinJohns** [comment] 2024-07-06 02:47
Essentially a duplicate of #1108.

**Closed** 2024-07-10 01:49 UTC
Labels: Duplicate
