### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by goloveychuk** [Microsoft/TypeScript#17657] opened 2017-08-07 13:22 UTC
**TypeScript Version:**  2.4.2

Looks like I found why my project is not compiling.
https://raw.githubusercontent.com/facebook/immutable-js/master/type-definitions/Immutable.d.ts
This file is not compiling using
` ./node_modules/.bin/tsc immutable.d.ts`
Looks like it have some circular references. And, since you improved generics checks in previous releases, it should be related.

**Comment by ahejlsberg** [comment] 2017-08-07 13:50
Duplicate of #17070.

**Closed** 2017-08-07 13:52 UTC
Labels: Duplicate
