### ISSUE TITLE
Strange behaviour with 'void' as function argument

### ISSUE THREAD

**Issue by lifaon74** [microsoft/TypeScript#31645] opened 2019-05-29 08:14 UTC
**TypeScript Version:**  3.4.5, 3.5.0-rc and next

**Search Terms:**
void, function, argument, template

**Code**

```ts
class A<T> {
  constructor(a: T) {
  }
}

class B {
  constructor(a: void) {
  }
}


const a = new A<void>(); // error ! => variable 'a' should be optional !
const b = new B();
```

**Expected behavior:**
It's pretty hard to understand why with a template function having a 'void' type (in class *A*), the behaviour is not the same as the class *B*.
Allowing a developper to put 'void' as template and providing 0 argument is sometimes required.

The following 'solution' is not acceptable, because the variable `a` would always be optional where I want to have it optional only if **T** is *void*.
```ts
class A<T> {
  constructor(a?: T) {
  }
}
```

**Actual behavior:**
class A diverge from B even if the typing is conceptualy the same.

**Playground Link:**
https://www.typescriptlang.org/play/#src=class%20A%3CT%3E%20%7B%0D%0A%20%20constructor(a%3A%20T)%20%7B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20B%20%7B%0D%0A%20%20constructor(a%3A%20void)%20%7B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0Aconst%20a%20%3D%20new%20A%3Cvoid%3E()%3B%20%2F%2F%20error%20!%0D%0Aconst%20b%20%3D%20new%20B()%3B

**More examples:**
```ts
type CType<T> = T extends any[] ? T : void;

class C<T> {
  constructor(a: CType<T>) {
  }
}

const c = new C<number>(); // error !
```
```ts
function foo<T>(a: T): void {
}

foo<void>(); // error !
```

**Comment by jack-williams** [comment] 2019-05-29 09:55
Duplicate of #29131. 

The short answer is that arity checking that accounts for `void` is done _before_ generic instantiation.

**Comment by nmain** [comment] 2019-05-29 15:23
Workaround:

```ts
type Args<T> = T extends void ? [T?] : [T];

function foo<T>(...args: Args<T>): void;
function foo<T>(arg: T) { // separate declaration from implementation, so the implementation doesn't need to use rest params
}

foo<void>(); // works!
foo<number>(); // fails as expected
foo<number>(3); // works!
```


https://www.typescriptlang.org/play/#src=type%20Args%3CT%3E%20%3D%20T%20extends%20void%20%3F%20%5BT%3F%5D%20%3A%20%5BT%5D%3B%0D%0A%0D%0Afunction%20foo%3CT%3E(...args%3A%20Args%3CT%3E)%3A%20void%3B%0D%0Afunction%20foo%3CT%3E(arg%3A%20T)%20%7B%20%2F%2F%20separate%20declaration%20from%20implementation%2C%20so%20the%20implementation%20doesn't%20need%20to%20use%20rest%20params%0D%0A%7D%0D%0A%0D%0Afoo%3Cvoid%3E()%3B%20%2F%2F%20works!%0D%0Afoo%3Cnumber%3E()%3B%20%2F%2F%20fails%20as%20expected%0D%0Afoo%3Cnumber%3E(3)%3B%20%2F%2F%20works!%0D%0A%0D%0A

**Closed** 2019-05-31 18:00 UTC
Labels: Duplicate
