### ISSUE TITLE
ts-ignore is stripped from method in declaration output, causing downstream errors

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#44012] opened 2021-05-09 04:34 UTC
# Bug Report

### 🔎 Search Terms

ts-ignore stripped from declaration output

### 🕗 Version & Regression Information

Tried on 4.2.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=12&pc=27#code/MYGwhgzhAEBCkFNoG8BQ0PQGYHscAoA7ALmkIFcBbAIwQCcBKFAX1VdUIQHc5F8GAdLgIBGAEwBmJgHpp0HAGtUqUJBgAxPNAQAPAC4JCAExjwISNJmizoAAT0QAtAEsA5oRx0kOAG706zkYIMHoAFkgQboRgeuRe6JjCRKQQegGErkzIrOycPJoEgkkAROISxTJyikA)

### 💻 Code

```ts
class Base {
    foo(n: number) {}
}

new Base().foo(123) // ok

class Foo extends Base {
    // @ts-ignore overrides the signature
    foo(n: string) {}
}

new Foo().foo("123") // ok
```

Declaration output:

```ts
declare class Base {
    foo(n: number): void;
}
declare class Foo extends Base {
    foo(n: string): void; // ERROR here because ts-ignore comment is missing.
}
```

### 🙁 Actual behavior

A consumer of a library with this declaration output reports errors.

### 🙂 Expected behavior

The `@ts-ignore` comment should still be there, so that the types of the consumed library work the same as the library author wrote (without type errors on the `Foo` subclass).

**Comment by MartinJohns** [comment] 2021-05-09 05:28
Duplicate of #38628.

**Closed** 2021-05-12 18:00 UTC
Labels: Duplicate

**Comment by tjjfvi** [comment] 2021-05-13 03:14
A (possibly non-ideal) fix for this specific instance is
```ts
class Foo extends Base {
    /** @ts-ignore overrides the signature */
    foo(n: string) {}
}

// Emitted .d.ts
declare class Foo extends Base {
    /** @ts-ignore overrides the signature */
    foo(n: string): void;
}
```
