### ISSUE TITLE
[lodash @types/lodash] An issue with lodash typings causing TypeScript compilation error

### ISSUE THREAD

**Issue by nikbarseghyan** [microsoft/TypeScript#54638] opened 2023-06-13 18:02 UTC
### Description

I encountered TypeScript compilation errors related to the `@types/lodash` package. The errors occur in the `common.d.ts` file of the `@types/lodash` package during the build process.

### 🙁 Expected Behavior

 I expected(аfter upgrading to v5.1.3) the build process to complete without any TypeScript compilation errors associated with the `@types/lodash` package.
Because in my project we don't use lodash and @types/lodash. I cleared the cache, but that didn't help either.

### 🙁 Actual Behavior

During the build process, I encountered the following TypeScript compilation errors:

### 💻 Code

```ts
node_modules/@types/lodash/common/common.d.ts:194:15 - error TS2589: Type instantiation is excessively deep and possibly infinite.

194 interface Object<T> extends LoDashImplicitWrapper<T> {
~~

node_modules/@types/lodash/common/common.d.ts:206:15 - error TS2430: Interface 'ObjectChain<T>' incorrectly extends interface 'LoDashExplicitWrapper<T>'.
The types returned by 'entries().pop()' are incompatible between these types.
Type 'CollectionChain<string | T[keyof T]>' is missing the following properties from type 'ObjectChain<[string, any]>': assign, assignIn, assignInWith, assignWith, and 11 more.

206 interface ObjectChain<T> extends LoDashExplicitWrapper<T> {
~~~~~

Found 2 errors in the same file, starting at: node_modules/@types/lodash/common/common.d.ts:194
```

### Versions

- TypeScript version: 5.1.3
- `@types/lodash` package version: Not used

### Additional Information

I have tried the following solutions, but none of them resolved the issue:
- Updating dependencies to the latest versions.
- Clearing the Yarn cache.
- Reinstalling dependencies.
- Verifying the TypeScript configuration.

I would greatly appreciate any help or guidance to resolve this issue. If you have any suggestions, workarounds, or insights into the compatibility between Lodash typings and TypeScript, please let me know. Thank you!

**Comment by nikbarseghyan** [comment] 2023-06-13 18:07
Yes, I deleted `node_modules` and `yarn.lock` file but again get the same issue

**Comment by ahejlsberg** [comment] 2023-06-13 23:45
Duplicate of #54542.

**Closed** 2023-06-16 01:33 UTC
Labels: Duplicate
