### ISSUE TITLE
Indexed access of union type is unsafe

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#16042] opened 2017-05-23 20:16 UTC
**TypeScript Version:**  nightly (2.4.0-dev.20170523)

**Code**

```ts
interface A {
    data: number;
}
interface B {
    data: string;
}

function f<T extends A | B>(): T["data"] {
    return 11;
}
```

**Expected behavior:**

Compile error. `T` might be `B`, so `T["data"]` might not be assignable from a number.

**Actual behavior:**

No error.

**Comment by michaeljota** [comment] 2017-05-23 21:18
If T can extends for A `OR` B, data can be both `string` or `number`. 

I think you mean
```
interface A {
    data: number;
}
interface B {
    data: string;
}

function f<T extends A & B>(): T["data"] {
    return 11;
}
```
`&` it's actually a union. And it trows, as expected.

**Comment by andy-ms** [comment] 2017-05-23 21:20
Data can't be a `number` depending on the particular type `T`. It's important that `T extends A | B` does not mean `T = A | B`.

**Comment by rtpg** [comment] 2017-05-25 01:35
Is this maybe just a parsing issue? If this is parsed as `(T extends A) | B` then T["data"] is a number on account of `T extends A`.

I'm not quite sure that you can have a type that extends a union.

**Comment by andy-ms** [comment] 2017-05-25 02:31
TS is parsing a type *parameter* there, not a type, so `(T extends A) | B` isn't legal at that location.

**Comment by andy-ms** [comment] 2017-11-05 01:20
Turns out this has nothing to do with unions.
```ts
```ts
interface I {
	x: string;
	y: number;
}

function f<K extends keyof I>(key: K, i: I): I[K] {
	return "";
}

f("y", { x: "", y: 0 }).toPrecision(); // Run-time error
```

**Comment by mhegazy** [comment] 2017-11-06 17:16
Duplicate of https://github.com/Microsoft/TypeScript/issues/19412

**Closed** 2017-11-06 17:20 UTC
Labels: Duplicate
