### ISSUE TITLE
No data tooltips in Visual Studio 2015 Update 3

### ISSUE THREAD

**Issue by stalek71** [Microsoft/TypeScript#13265] opened 2017-01-03 12:55 UTC
**TypeScript Version:**  2.0.6
When I put  a breakpoint in fetchdata.ts file (line 18) I see "dynamic" version of typescript file on breakpoint hit and no any data tooltips are working (apear) there.
**Code**
I uploaded the whole solution to github here:
https://github.com/stalek71/TypeScript-Issue

**Expected behavior:**
Convenient navigation through data using data tips.

**Actual behavior:**
Data tooltips don't pop up when hovering over vars

**Comment by mhegazy** [comment] 2017-01-03 18:50
@sheetalkamat can you take a look?

**Comment by sheetalkamat** [comment] 2017-01-03 20:34
This is known issue and is caused by https://github.com/dotnet/roslyn/issues/11400 We will need to work around this by creating temporary files for the dynamic files. Will look into this soon.

**Comment by bstaley** [comment] 2017-03-02 14:35
I read the linked issue above and it's too bad they can't work towards resolving this issue. I 'reported a problem' in vs to try to help. I am using angular-cli which uses webpack to bundle files and I'm running into this same issue. Any update?

**Comment by novakf** [comment] 2017-03-31 13:00
Hello sheetalkamat,

is there any progress on this? Can we make a workaround on our own? I mean, to copy sources/maps to some location before we will start debugging?

If so, could you please describe which place files needs to be copied?

**Closed** 2018-05-11 15:49 UTC
Labels: External
