### ISSUE TITLE
ENOENT while running `gulp browserify`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#9893] opened 2016-07-22 14:53 UTC
```
[07:51:15] Requiring external module ts-node/register
(node:15128) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[07:51:16] Using gulpfile ~\work\TypeScript\Gulpfile.ts
[07:51:16] Starting 'built\local\lib.dom.d.ts'...
[07:51:16] Starting 'built\local\lib.dom.iterable.d.ts'...
[07:51:16] Starting 'built\local\lib.webworker.d.ts'...
[07:51:16] Starting 'built\local\lib.scripthost.d.ts'...
[07:51:16] Starting 'built\local\lib.es5.d.ts'...
[07:51:16] Starting 'built\local\lib.es2015.d.ts'...
[07:51:16] Starting 'built\local\lib.es2016.d.ts'...
[07:51:16] Starting 'built\local\lib.es2017.d.ts'...
[07:51:16] Starting 'built\local\lib.d.ts'...
[07:51:16] Starting 'built\local\lib.es6.d.ts'...
[07:51:16] Starting 'built\local\lib.es2015.core.d.ts'...
[07:51:16] Starting 'built\local\lib.es2015.collection.d.ts'...
[07:51:16] Starting 'built\local\lib.es2015.generator.d.ts'...
[07:51:16] Starting 'built\local\lib.es2015.iterable.d.ts'...
[07:51:16] Starting 'built\local\lib.es2015.promise.d.ts'...
[07:51:16] Starting 'built\local\lib.es2015.proxy.d.ts'...
[07:51:16] Starting 'built\local\lib.es2015.reflect.d.ts'...
[07:51:16] Starting 'built\local\lib.es2015.symbol.d.ts'...
[07:51:16] Starting 'built\local\lib.es2015.symbol.wellknown.d.ts'...
[07:51:16] Starting 'built\local\lib.es2016.array.include.d.ts'...
[07:51:16] Starting 'built\local\lib.es2017.object.d.ts'...
[07:51:17] Starting 'built\local\lib.es2017.sharedmemory.d.ts'...
[07:51:17] Starting 'scripts\processDiagnosticMessages.js'...
[07:51:17] Finished 'scripts\processDiagnosticMessages.js' after 175 ms
[07:51:17] Starting 'src\compiler\diagnosticInformationMap.generated.ts'...
[07:51:17] Finished 'src\compiler\diagnosticInformationMap.generated.ts' after 1.06 ms
[07:51:17] Starting 'generate-diagnostics'...
[07:51:17] Finished 'generate-diagnostics' after 8.21 μs
[07:51:17] Finished 'built\local\lib.es2017.object.d.ts' after 226 ms
[07:51:17] Finished 'built\local\lib.es2015.d.ts' after 281 ms
[07:51:17] Finished 'built\local\lib.dom.iterable.d.ts' after 291 ms
[07:51:17] Finished 'built\local\lib.es2015.collection.d.ts' after 271 ms
[07:51:17] Finished 'built\local\lib.scripthost.d.ts' after 288 ms
[07:51:17] Finished 'built\local\lib.es2016.d.ts' after 283 ms
[07:51:17] Finished 'built\local\lib.es2017.d.ts' after 282 ms
[07:51:17] Finished 'built\local\lib.webworker.d.ts' after 292 ms
[07:51:17] Finished 'built\local\lib.es2015.iterable.d.ts' after 271 ms
[07:51:17] Finished 'built\local\lib.es2015.proxy.d.ts' after 269 ms
[07:51:17] Finished 'built\local\lib.es2015.generator.d.ts' after 274 ms
[07:51:17] Finished 'built\local\lib.es2015.promise.d.ts' after 272 ms
[07:51:17] Finished 'built\local\lib.es2015.symbol.wellknown.d.ts' after 266 ms
[07:51:17] Finished 'built\local\lib.es2017.sharedmemory.d.ts' after 262 ms
[07:51:17] Finished 'built\local\lib.es2015.symbol.d.ts' after 269 ms
[07:51:17] Finished 'built\local\lib.es2016.array.include.d.ts' after 267 ms
[07:51:17] Finished 'built\local\lib.es2015.reflect.d.ts' after 272 ms
[07:51:17] Finished 'built\local\lib.es2015.core.d.ts' after 285 ms
[07:51:17] Finished 'built\local\lib.es5.d.ts' after 297 ms
[07:51:17] Finished 'built\local\lib.dom.d.ts' after 318 ms
[07:51:17] Finished 'built\local\lib.d.ts' after 356 ms
[07:51:17] Finished 'built\local\lib.es6.d.ts' after 360 ms
[07:51:17] Starting 'lib'...
[07:51:17] Finished 'lib' after 3.81 μs
[07:51:17] Starting 'built\local\typescriptServices.js'...
[07:51:25] Finished 'built\local\typescriptServices.js' after 7.75 s
[07:51:25] Starting 'browserify'...
Error: ENOENT: no such file or directory, open 'C:\Users\anhans\work\TypeScript\harness\virtualFileSystem.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.readFileSync (C:\Users\anhans\work\TypeScript\node_modules\sander\src\methodMakers\standardMethod.js:47:27)
    at Object.loadSync (C:\Users\anhans\work\TypeScript\node_modules\sorcery\src\Node.js:64:41)
    at C:\Users\anhans\work\TypeScript\node_modules\sorcery\src\Node.js:89:10
    at Array.map (native)
    at Object.loadSync (C:\Users\anhans\work\TypeScript\node_modules\sorcery\src\Node.js:83:31)
    at C:\Users\anhans\work\TypeScript\node_modules\sorcery\src\Node.js:89:10
    at Array.map (native)
```

**Comment by weswigham** [comment] 2016-07-22 18:24
@sandersn has mentioned seeing this before. (And then seeing it stop after
he does something else) Is this reproducible?

**Comment by sandersn** [comment] 2016-07-22 18:29
Notice that the path is wrong --missing `src` in `TypeScript\harness`: C:\Users\anhans\work\TypeScript\harness\virtualFileSystem.ts

However, I didn't see it this morning on my Windows laptop because the switch to tsconfig for harness in #9628 removes the offending code, I think.

(I did have to modify `tests/webTestServer.ts` to use `<reference types="node"/>` instead of `<reference path="../some/relative/path/to/node.d.ts"/>` in order to get `runtests-browser` to work.)

**Comment by weswigham** [comment] 2016-07-22 19:36
@sandersn I thought @yuit already merged a fix for that?

**Comment by sandersn** [comment] 2016-07-22 20:24
That's what I get for programming while sick. I didn't successfully pull master this morning on the stale repo on my laptop. So my code is a couple of weeks out of date.

**Comment by sandersn** [comment] 2016-07-22 20:35
Yup, now I repro this bug. I'll send out a fix right after I get the PR out for a bug I'm almost done with.

**Comment by sandersn** [comment] 2016-07-22 20:58
OK, fix is out.

**Closed** 2016-07-25 20:43 UTC
