### ISSUE TITLE
FETCH / Give The json() Function The Power To Use Generic Type

### ISSUE THREAD

**Issue by SamJbori** [microsoft/TypeScript#59950] opened 2024-09-12 09:08 UTC
### 🔍 Search Terms

json fetch casting

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

The `json `function definition to be changed to allow the ability to specify a type

This is a minimal change that will require changing the line `3186 `in the `lib.dom.d.ts`

from
`3186    json(): Promise<any>;
`
to
`3186    json<T = any>(): Promise<T>;
`

### 📃 Motivating Example

This simple change will allow calling the `json `function and organically feed the correct type instead of using type casting.

### 💻 Use Cases

1. What do you want to use this for? Calling the function without type casting.
2. What shortcomings exist with current approaches? Must use type casting.
3. What workarounds are you using in the meantime? Type casting.

**Comment by MartinJohns** [comment] 2024-09-12 09:14
Duplicate of #44603 / #30220. This has been rejected several times already.

**Closed** 2024-09-12 09:27 UTC
