### ISSUE TITLE
Decorators always transformed regardless of target

### ISSUE THREAD

**Issue by errorx666** [Microsoft/TypeScript#18713] opened 2017-09-23 01:44 UTC
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)
2.6.0-dev.20170922
**Code**

`tsconfig.json`
```json
{
	"compilerOptions": {
		"target": "esnext",
		"experimentalDecorators": true
	}
}
```

```ts
function foo() {
	return f => f;
}

@foo()
class Foo {}
```

**Expected behavior:**
Decorator is emitted as-is because target is `esnext`.

**Actual behavior:**
Decorator is transformed to `__decorate` call.

I want to let all of the ECMAScript features be transpiled by Babel.

**Comment by mhegazy** [comment] 2017-09-25 16:43
duplicate of https://github.com/Microsoft/TypeScript/issues/16882

**Comment by errorx666** [comment] 2017-09-25 17:00
So I need to wait for the new decorators proposal to be implemented?
Which is probably going to disrupt a lot of Angular code that depends on legacy decorators.

**Comment by mhegazy** [comment] 2017-09-25 17:14
> So I need to wait for the new decorators proposal to be implemented?

yes

> Which is probably going to disrupt a lot of Angular code that depends on legacy decorators.

We hope the roll-out will be coordinated with the Angular team to make sure the decorators can handle both versions of the proposal so only user-defined decorators would need to change.

> There's a legacy decorators Babel transform I intend to use here. I don't think it would break anything if you just output the decorators as they appear in the source, for esnext.

It is not only the transforms, the decorator implementation as it stands today can not be labeled `esNext`. once we implement the new proposal we can safely label it as such.

**Comment by mhegazy** [comment] 2017-10-09 17:17
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-10-09 17:17 UTC
Labels: Duplicate
