### ISSUE TITLE
Omit should distribute over union types

### ISSUE THREAD

**Issue by askvortsov1** [microsoft/TypeScript#47263] opened 2021-12-29 07:18 UTC
# Bug Report

### 🔎 Search Terms

omit union

### 🕗 Version & Regression Information

- This is the behavior in every version I tried since 3.5 where Omit was introduced, and I reviewed the FAQ for entries about omit

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBAglC8UDeAoK6oGcAWBDAThACYBcWw+AlgHYDmA3CmhpgPYC2Ew2NtZFAVwiNm6CAA8AxgBsBmSgDcIAFVYwymCr0YBfJqEhQAQgmSiseQqXJU6IjFg5cedMgDNc0zMKYOJMuUUVViMNLTsUPRQDaABhUzgAH2MRGKgAEVMAeXZKYAAeWIAaKAByHAJiUoA+EUlWak0oXDJMxFQHNk5uXn58ISLzf1l5JVV1MuwIQlLBqPrG4CgAI1bTDpYnHtcoDy8IQb8pEaDVUMnpiFnIoA)

### 💻 Code

```
type A = {
    shared: string;

    something: true;

    exclusiveToA: string;
}

type B = {
    shared: string;

    something: false;

    exclusiveToB: string;
}

type C = A | B;

type D = Omit<C, 'shared'>;

const a: D = {
    something: true,
    exclusiveToA: 'here',
}

const b: D = {
    something: false,
    exclusiveToB: 'here',
}
```

### 🙁 Actual behavior

`Omit` strips away properties of its union type operands that don't have common keys

### 🙂 Expected behavior

`Omit` should recursively distribute over union/product type expressions

**Comment by MartinJohns** [comment] 2021-12-29 07:32
Duplicate of #46361. Used search terms: `omit union` (same as you)

**Comment by askvortsov1** [comment] 2021-12-29 07:57
> Duplicate of #46361. Used search terms: `omit union` (same as you)

Huh, not sure how I missed that... Thanks!

**Closed** 2021-12-29 07:57 UTC

**Comment by MartinJohns** [comment] 2021-12-29 08:07
Probably just looked at the open issues? :-D If you add `in:title` you will find a lot more duplicates, with less noise.
