### ISSUE TITLE
throw error when use overload in object

### ISSUE THREAD

**Issue by chnliquan** [microsoft/TypeScript#43822] opened 2021-04-26 10:25 UTC
# Bug Report

### 🕗 Version & Regression Information

4.x

- This is a crash

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/FDAUG9gAhqHMCmAXUBDATnAXFAdgVwFsAjBdAShwAV0B7QgSwGcEAeAksgbQF0A+ANzRYAehFQETADYNcSALQATZqmJSE83AgAeCmVry0l+AA4aAxlNRMm8wgk7omwmGKgABJLYZxctdAgu8MhomDhMSOiycJRQNPTMbBFRuHC8gkFukvoKykyq6po6erIIhsZm8pbWtvaOzrBQbp7evv6BjdYAnrjmwSgY2FCouF2x8YwsrCNdfFCQjTABSPjouFBcgzxCjQC+wLvkAHSIKJH4COQCQA)

### 💻 Code

```ts
({
    get(arg: number): Promise<number[]>;
    // eslint-disable-next-line no-dupe-class-members
    // @ts-ignore
    get(arg: string): Promise<string[]>;
    // eslint-disable-next-line no-dupe-class-members
    // @ts-ignore
    async get(arg: any): Promise<any> {
      return [arg];
    }
}).get(true);
```

### 🙁 Actual behavior
when overload in object, it will throw error

### 🙂 Expected behavior
support overload in object

**Comment by MartinJohns** [comment] 2021-04-26 11:29
Duplicate of #32588.

**Closed** 2021-04-28 18:00 UTC
Labels: Duplicate
