### ISSUE TITLE
Simpler type annotation

### ISSUE THREAD

**Issue by raqystyle** [Microsoft/TypeScript#17366] opened 2017-07-24 04:05 UTC
### Summary

Sometimes, we have to specify arguments to functions that are not really needed. For example, in function intefaces.

### Actual 

As a dummy example, consider this snippet:

```ts
interface Functor<A> {
    fmap<B>(f: (x: A) => B): Functor<B>
}

interface MyFnInterface1<B, C> {
    (x: B, y: B): Promise<C>
}

interface MyFnInterface2<B, C> {
    (fn: (x: B, y: B) => C): Promise<C>
}
```

### Would be nice to have

The snippet above could be simplified as the following:

```ts
interface Functor<A> {
    fmap<B>((A) => B): Functor<B>
}

interface MyFnInterface1<B, C> {
    (B, B): Promise<C>
}

interface MyFnInterface2<B, C> {
    ((B, B) => C): Promise<C>
    ((B) => (B) => C): Promise<C>
}
```

or, even to this:

```ts
interface Functor<A> {
    fmap<B>(A => B): Functor<B>
}

interface MyFnInterface1<B, C> {
    (B, B): Promise<C>
}

interface MyFnInterface2<B, C> {
    ((B, B) => C): Promise<C>
    (B => B => C): Promise<C>
}
```

**Comment by gcnew** [comment] 2017-07-24 06:33
It has already been suggested numerous times. See https://github.com/Microsoft/TypeScript/issues/13152

**Comment by RyanCavanaugh** [comment] 2017-07-24 17:23
Duplicate of #3081

**Closed** 2017-07-24 17:24 UTC
Labels: Duplicate
