### ISSUE TITLE
Error: Debug Failure. False expression. in 'symbolToParameterDeclaration' during 'getCodeFixes'

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#22183] opened 2018-02-26 05:00 UTC
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.2
**VSCode Version** 1.20.1
**command requested**: getCodeFixes
**hitting sessions**: 107
**proportion of all sessions**: 0.011350376577914502
**five line hash**: 1e8389c784703a10a93b9c6a577e6b09
**stack**
```
Error: Debug Failure. False expression.
    at symbolToParameterDeclaration (tsserver.js:23555:26)
    at unknown (tsserver.js:23514:89)
    at Array.map (native)
    at signatureToSignatureDeclarationHelper (tsserver.js:23514:55)
    at createTypeNodesFromResolvedType (tsserver.js:23420:43)
    at createTypeNodeFromObjectType (tsserver.js:23311:35)
    at createAnonymousTypeNode (tsserver.js:23273:32)
    at typeToTypeNodeHelper (tsserver.js:23216:28)
    at Object.typeToTypeNode (tsserver.js:23048:41)
    at typeToString (tsserver.js:23027:40)
    at Object.writeType (tsserver.js:21009:24)
    at typeToString (tsserver.js:79309:21)
    at makeChange (tsserver.js:79242:38)
    at makeFix (tsserver.js:79239:70)
    at getCodeActionForVariableDeclaration (tsserver.js:79191:20)
    at getFix (tsserver.js:79149:65)
    at Object.getCodeActions (tsserver.js:79110:27)
    at unknown (tsserver.js:77219:33)
    at Object.forEach (tsserver.js:1431:30)
    at Object.getFixes (tsserver.js:77218:16)
    at unknown (tsserver.js:83366:35)
    at Object.flatMap (tsserver.js:1698:25)
    at Object.getCodeFixesAtPosition (tsserver.js:83364:23)
    at IOSession.Session.getCodeFixes (tsserver.js:90388:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89292:61)
    at unknown (tsserver.js:90553:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90544:28)
    at IOSession.Session.executeCommand (tsserver.js:90553:33)
    at IOSession.Session.onMessage (tsserver.js:90573:35)
    at Interface.<anonymous> (tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by andy-ms** [comment] 2018-03-14 15:35
Duplicate of #21804

**Closed by andy-ms** 2018-03-14 15:35 UTC
Labels: Bug, Source: Telemetry
