### ISSUE TITLE
Type of decorated class is not inferred correctly

### ISSUE THREAD

**Issue by DominikPalo** [Microsoft/TypeScript#16808] opened 2017-06-28 16:37 UTC
**TypeScript Version:**  2.4.1

I have a decorator to simplify writing of Angular 1.5 components/controllers:
```ts
import { extend, IComponentOptions } from 'angular';

export const Component = function(options: IComponentOptions): Function {
  return (controller: Function) => extend(options, {controller});
};
```

Then a component's controller looks like:
```ts
@Component({
    bindings: {
        foo: '=',
    },
    template: require('./templates/bar.html')
})
export class MyComponent {
  // controller body
}
```

In TS <=2.3 I can register these components with:
`ngModule.component('myComponent', MyComponent)`
(ngModule.component signature: `(name: string, options: IComponentOptions)`)

But with TS 2.4 I got an error (because of stricter checks on “weak types” functionality):
>   TS2559: Type 'type of MyComponent' has no properties in common with type 'IComponentOptions'.

I have to change registration of the component to:
`ngModule.component('myComponent', <any>MyComponent)` or `ngModule.component('myComponent', <IComponentOptions>MyComponent)`

But `MyComponent` is decorated with `@Component`, so it is already of `any` type (the angular `extend(...)` function from my decorator returns any) => explicit casting to `any` shouldn't be required.

**Comment by yortus** [comment] 2017-06-29 02:20
Duplicate of #4881?

**Comment by mikehaas763** [comment] 2017-07-12 23:24
A very similar thing is happening for me with 2.4.1 suddenly. I'm not using a decorator but I have a property bag of type `IComponentOptions` and having `controller: MyComponent` on that property bag results in the same error.

**Comment by mhegazy** [comment] 2017-09-08 16:56
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-08 16:56 UTC
Labels: Duplicate

**Comment by musasesay** [comment] 2017-11-23 06:45
| constructor(public navCtrl: NavController, public navParams: NavParams) {
-- | --
  | this.homePage = HomePage
  | this.categories=[];
