### ISSUE TITLE
Order of expressions in if block affect type narrowing from unknown

### ISSUE THREAD

**Issue by frederickfogerty** [microsoft/TypeScript#34334] opened 2019-10-14 11:50 UTC
**TypeScript Version:**  3.7-Beta

**Search Terms:** object null order type narrowing 

**Code**

```ts
const maybeObject: unknown = {};

if (maybeObject != null && typeof maybeObject === 'object') {
    Object.keys(maybeObject)
}

if (typeof maybeObject === 'object' && maybeObject != null) {
    Object.keys(maybeObject)
}
```
[Playground link](http://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=1&ssc=1&pln=9&pc=2#code/MYewdgzgLgBAtgQwJ4CMCmB5FArNwoBcMArmANZggDuYMAvDAN4C+A3AFDsCWAZjABSJUmHHlgBCBmGIAbGTABkCmFCQAHNCD5D0WXPnp0GAchCj8xgJRN2MOzD1iAdGTRIIg5LvNRL7Zpy8AqoaWvBeIvqwRiZmUcaKyjqRYjCSMNJy1oy29o74Lm4eyfm+-kA)

**Expected behavior:**

No type errors; `maybeObject` is correctly narrowed to `object` in both cases.

**Actual behavior:**

The first if block throws an error as `maybeObject` is incorrectly narrowed to `object | null`, whereas the second `maybeObject` is incorrectly narrowed.
```
No overload matches this call.
  Overload 1 of 2, '(o: {}): string[]', gave the following error.
    Argument of type 'object | null' is not assignable to parameter of type '{}'.
      Type 'null' is not assignable to type '{}'.
  Overload 2 of 2, '(o: object): string[]', gave the following error.
    Argument of type 'object | null' is not assignable to parameter of type 'object'.
      Type 'null' is not assignable to type 'object'.(2769)
```

**Playground Link:** http://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=1&ssc=1&pln=9&pc=2#code/MYewdgzgLgBAtgQwJ4CMCmB5FArNwoBcMArmANZggDuYMAvDAN4C+A3AFDsCWAZjABSJUmHHlgBCBmGIAbGTABkCmFCQAHNCD5D0WXPnp0GAchCj8xgJRN2MOzD1iAdGTRIIg5LvNRL7Zpy8AqoaWvBeIvqwRiZmUcaKyjqRYjCSMNJy1oy29o74Lm4eyfm+-kA

**Related Issues:** No

**Comment by jack-williams** [comment] 2019-10-14 13:45
Duplicate of #28131

**Closed** 2019-10-16 18:00 UTC
Labels: Duplicate
