### ISSUE TITLE
Read-only tuple or Set has wrong types in typescript/lib/lib.es2016.array.include.d.ts

### ISSUE THREAD

**Issue by alesmenzel** [microsoft/TypeScript#53584] opened 2023-03-30 10:50 UTC
# Bug Report

### 🔎 Search Terms

tuple, readonly, const, includes

### 🕗 Version & Regression Information

- This is a crash No
- This changed between versions - always like this from what I tested
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about includes, tuple
- I was unable to test this on prior versions because as const was added in version 4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.2#code/MYewdgzgLgBAGjAvDA2gcgGYhGgNDNAIwEMAnNAXRmIhlEigChG4A6ASzGABsBXAEwCmEABRFiALzQBKRgHo5MAHpKYHLnyGjpdABaDgAa1oB3fVH2lqMAObsAboLAx2UQQFsXtTjAuDfvAAO3IL4ECAw-OwQxNzcICacNtRgAJ4wIH5WgiHuTlC07sSGwr76apw8AsIiOhi8XFDs4DC8EDnCtBCV-rHcdH20FsSwMU0QGOylfr6pgaUmILzc-DCkglC8pM5QpLyCQA)

### 💻 Code

```ts
const X = ['foo', 'bar'] as const

X.includes('baz')
// Argument of type '"baz"' is not assignable to parameter of type '"foo" | "bar"'.(2345)
// .includes() checks whether a given item is in the tuple, so disallowing any other elements makes the .includes() function useless since all calls that satisfies the types would return true
```

### 🙁 Actual behavior

We cannot check whether elements are included in a read-only tuple.

### 🙂 Expected behavior

We can check whether elements are **not** included in a read-only tuple.

**Comment by MartinJohns** [comment] 2023-03-30 10:57
Duplicate of #14520.

**Comment by alesmenzel** [comment] 2023-03-30 11:16
Actually there is even better example

```tsx
const set = new Set(['foo', 'bar'] as const)
set.has('baz')
```

[Playground](https://www.typescriptlang.org/play?ts=5.0.2#code/MYewdgzgLgBBCmsC8MzwO4wMqIBQG0ByAMxBEIBoZCAjAQwCdCBdGOiGUSKASgCgEUAHQALdrlp0AXoX4B6OTACCDAOYBXALbwwsEMRhQAngAd41AET0pFwjACWHMCFjsI91WDo0ANuaggMCaMdNpQ8Aww+oam5oQWpCAWMAA+MFaMtkK4AEwAzAAsAKz8QA)

**Comment by MartinJohns** [comment] 2023-03-30 11:45
Still a duplicate of the linked issue. :-)

**Closed** 2023-04-02 18:00 UTC
Labels: Duplicate
