### ISSUE TITLE
Type checking modifier which allows interleaved support nominal and structural checking behaviours

### ISSUE THREAD

**Issue by wesleyolis** [Microsoft/TypeScript#24519] opened 2018-05-31 09:31 UTC
How about introduction a new type checking modifier operator, that is implemented for type checking only. Which would allow the best of both worlds, nominal an structural typing paradigms.

As far as I know '$' is not used for specially many yet, so how about allowing $ donate use nominal type checking for the following use cases.

I would prefer to have everything swapped around, but that could break alot of backwards compatibility, maybe it could be debated to have a global compiler and localised ts file setting

It may also be better to rather use a variable naming convention, that is prefixed with dollar, because then one explicit knows, what type of checking is being used... As may loos sight of things on which equality typechecking operator to use.

The compiler could also have auto correct mode for assignment to dollar assignment instead of the 

#### assignment:
$=
#### call signature only:
(index :$ {index :number} => void 
#### call signature and return:
(index :$ {index :number} $=> void 
#### return: 
(index : {index :number} $=> void 
#### type, implies nominal should also be used were , unless explicitly cast away..
type test $= testing;
#### variable, implies nominal should also be used were , unless explicitly cast away..
const var1 $= 'test'; 
let var1 $= 'test'; 
readonly var1 $= 'test'; 

#### assignment:
=
#### call signature only:
(index : {index :number} => void 
#### call signature and return:
(index : {index :number} => void 
#### return: 
(index : {index :number} => void 
#### type 
test = testing;
#### variable
const var1 = 'test'; 
let var1 = 'test'; 
readonly var1 = 'test'; 

### Casting away nominal type checking
For each nominal declare type their is an additional generated structure type name. The same behaviour as for classes, were their is a generated interface..
The $ identify must always be used in a type definition and assignments, so that it is explicitly obvious as to how type checking is being performed.

type nTypeA $= {a : string}; .nominal type
type nTypeB $= {a : string}; // nominal type
type TypeA = nTypeA or // structured type
type TypeA = typeof NTypeA //structured type

// type checking ensure consistence, that nominal type variable a $= must be used..

const varNa :$ nTypeA $= {a:'test'}
const varNb :$ nTypeB $= {a:'test'}

const varNa : nTypeA = varNa; //OK allow casting, : is not of form :$, 
const varNb : nTypeA = VarNb; //OK allow casting, : is not of form :$

const varA :$ nTypeB = varNb; // Error nominal type checking
const varB :$ nTypeA = varNa; // Error nominal type checking

const varA : TypeA = varNb; //OK
const varB : TypeA = VarNa; //OK

**Comment by andy-ms** [comment] 2018-05-31 15:04
Duplicate of #202, though in that case the type and not the type annotation is what's marked nominal, which makes more sense since it would be easy to forget to add `$` everywhere, and hard to read if you did remember.

**Closed** 2018-06-25 18:56 UTC
Labels: Duplicate
