### ISSUE TITLE
.then() breaks `Foo | undefined` => `Foo

### ISSUE THREAD

**Issue by connor4312** [microsoft/TypeScript#54712] opened 2023-06-19 22:21 UTC
# Bug Report

### 🔎 Search Terms

then undefined inference

### 🕗 Version & Regression Information

- This changed between versions 3.3.3333 and 3.5.1

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4F8BQcAzgJ4gLIwCu5Yw6IyA5hGBugBQCUAXMgApR0AW2BEIAHnYA+HMiisqURngDcyAvg7EyFbsgC8s7PmRnkCBkTDJhcAA6HkICAHdkAWQcTrUUE2QAH2QaABMIGFAIUIAaNExpblVTc0sQa2QAawgSJwByAAsIABti9Dzk8wsrGwREItCAeSgAOTcnO3sAOhYwDmySLmQAfmHkOFc4YBte9m4usCKQDihDWSguSvNOrvE+gbi6hAbmttcufFwuIA

(older versions of TS use `||` instead of `??` to the same effect

### 💻 Code

```ts
interface Foo {}
async function getFoo(): Promise<Foo> { return {}; }

(async () => {
    const map = new Map<string | undefined, Foo>();
    const key = 'hello';
    const cachedOrNew = map.get(key) ?? await getFoo().then(r => r);
    map.set(key, cachedOrNew)
})
```

### 🙁 Actual behavior

`cachedOrNew` is `Foo | undefined`

### 🙂 Expected behavior

`cachedOrNew` should be `Foo`

If you remove the `.then(r => r)` and assign the `await` expression to an intermediate variable first, it works

**Comment by Josh-Cena** [comment] 2023-06-20 00:59
Duplicate of https://github.com/microsoft/TypeScript/issues/54551

**Closed** 2023-06-20 14:31 UTC
