### ISSUE TITLE
Imports updated incorrectly for imported js file with extension

### ISSUE THREAD

**Issue by amitnovick** [microsoft/TypeScript#30550] opened 2019-02-24 12:19 UTC
Steps to Reproduce:
```js
// app.js
const lib = require('./lib.js');
// lib.js
module.exports = 1;
```
Now rename `lib.js` to `myLib.js`:
```js
// app.js
const lib = require('./lib.js/index.js'); // => Expected: './myLib.js'
// myLib.js
module.exports = 1;
```
Now rename `myLib.js` to `myMyLib.js`:
```js
// app.js
const lib = require('./lib.js/index.js.js'); // => Expected: './myMyLib.js'
// myMyLib.js
module.exports = 1;
```
**This misbehavior appeared when I updated to 1.31.1
This misbehavior didn't exist in 1.30.2**

Thanks for your time, appreciate your work!

**Comment by mjbvz** [comment] 2019-03-22 22:01
Confirmed on Typescript 3.4-rc

Require is being resolved properly but the edits returned for the file move are incorrect. This is with the default config:

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2016",
        "jsx": "preserve"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

**Comment by feelextra** [comment] 2019-03-23 13:48
Note I haven't tried this with TypeScript, but instead with JavaScript on VSCode.

My config of VSCode:
```
  "javascript.validate.enable": true,
  "javascript.updateImportsOnFileMove.enabled": "always",
  "javascript.implicitProjectConfig.checkJs": true
```

Without `jsconfig.json` file.

**Comment by feelextra** [comment] 2019-04-05 11:18
Closed by mistake: please Ignore that.

Confirmed on **version 1.33.0 of VSCode**

**Comment by elibarzilay** [comment] 2019-10-18 11:49
I just tried it in Emacs, and it looks like it's working fine.  To be specific, in case I'm doing something wrong:

1. I created a directory with the two files and a `tsconfig.json` with the above exact text.
2. Opened both in Emacs, and turned `tide-mode` on in both (and used `tide-restart-server` since it didn't do that when I switched the mode).
3. In `lib.js` I used `tide-rename-file` to rename it to `myLib.js`.
4. The result was the file being properly renamed, and the line in `app.js` modified correctly.

I turned on logging (following the suggested `TSS_LOG=-level verbose -file /tmp/tss.log` flags), and the logfile shows what looks like correct interaction:

    Info 124  [11:21:10.281] request:
    {"command":"getEditsForFileRename","seq":"5","arguments":{"oldFilePath":"/home/eli/x/lib.js","newFilePath":"/home/eli/x/myLib.js","file":"/home/eli/x/lib.js"}}
    Perf 125  [11:21:10.372] 5::getEditsForFileRename: elapsed time (in milliseconds) 91.0648
    Info 126  [11:21:10.372] response:
    {"seq":0,"type":"response","command":"getEditsForFileRename","request_seq":"5","success":true,"body":[{"fileName":"/home/eli/x/app.js","textChanges":[{"start":{"line":1,"offset":22},"end":{"line":1,"offset":30},"newText":"./myLib.js"}]}]}

@mjbvz: can you see if it's still happening?  I'll try to figure out installing vscode to try it there anyway.

**Comment by elibarzilay** [comment] 2019-10-24 21:53
I finally tried it with vscode, and indeed it's broken, but looking at the log there, I think that this is a problem with the way vscode does things.  The setup is the same I used in Emacs, except that I used `jsconfig.json` instead of `tsconfig.json` to make it work.  I opened both files and did the rename: that got me a bogus edit, but one that is different from the above:

    const lib = require("./myLib.js/index.js");

I then compared the two logs, looking for occurences of `myLib`.  In the Emacs case, the interaction looks fine (see previous comment).  But in the vscode case, it looks like *it* decides on the bogus text before it consults tsserver: in the below bits of the log, it looks to me like in 14 vscode tells tsserver about the bogus rename that it did, and later in 19 it sends the `getEditsForFileRename` request, and the response is the bogus text which is already there--?

    {"seq": 9, "type": "request", "command": "updateOpen", "arguments": {
        "changedFiles": [],
        "closedFiles": ["/home/eli/x/lib.js"],
        "openFiles": [{"file": "/home/eli/x/myLib.js", ...}]}}
    {"seq": 10, "type": "request", "command": "navtree", "arguments": {
        "file": "/home/eli/x/myLib.js"}}
    {"seq": 12, "type": "request", "command": "getOutliningSpans", "arguments": {
        "file": "/home/eli/x/myLib.js"}}
    {"seq": 13, "type": "request", "command": "configure", "arguments": {
        "file": "/home/eli/x/myLib.js",
        "formatOptions": {...},
        "preferences": {..., "allowRenameOfImportPath": true}}}
    {"seq": 14, "type": "request", "command": "updateOpen", "arguments": {
        "changedFiles": [
          {"fileName": "/home/eli/x/app.js",
           "textChanges": [{
               "newText": "./myLib.js/index.js",
               "start": {"line": 1, "offset": 22},
               "end": {"line": 1, "offset": 30}}]}],
        "closedFiles": [],
        "openFiles": []}}
    {"seq": 16, "type": "request", "command": "updateOpen", "arguments": {
        "changedFiles": [],
        "closedFiles": ["/home/eli/x/lib.js"],
        "openFiles": [{
            "file": "/home/eli/x/myLib.js",
            "fileContent": "module.exports = 1;\n",
            ...}]}}
    {"projectName": "/dev/null/inferredProject1*",
     "fileNames": [..., "/home/eli/x/app.js", "/home/eli/x/myLib.js"],
     "compilerOptions": {...},
     "typeAcquisition": {...},
     "unresolvedImports": [],
     "projectRootPath": "/home/eli/x",
     "kind": "discover"}
    {"seq": 17, "type": "request", "command": "getApplicableRefactors", "arguments": {
        "file": "/home/eli/x/myLib.js",
        "startLine": 1, ...}}
    {"seq": 19, "type": "request", "command": "getEditsForFileRename", "arguments": {
        "oldFilePath": "/home/eli/x/lib.js",
        "newFilePath": "/home/eli/x/myLib.js"}}
    {"seq": 0, "type": "response", "command": "getEditsForFileRename",
      "request_seq": 19, "success": true,
      "body": [{
          "fileName": "/home/eli/x/app.js",
          "textChanges": [{
              "start": {"line": 1, "offset": 22},
              "end": {"line": 1, "offset": 30},
              "newText": "./myLib.js/index.js"}]}]}

**Comment by mjbvz** [comment] 2019-11-14 19:27
@elibarzilay Sorry for the delay getting back to you.

I can also still repo this. Here's the trace that causes problems (renaming `old.js` -> `new.js`):

```
[Trace  - 11:24:08 AM] <semantic> Sending request: getEditsForFileRename (652). Response expected: yes. Current queue length: 0
Arguments: {
    "oldFilePath": "/Users/matb/projects/san/old.js",
    "newFilePath": "/Users/matb/projects/san/new.js"
}
[Trace  - 11:24:08 AM] <semantic> Response received: getEditsForFileRename (652). Request took 11 ms. Success: true 
Result: [
    {
        "fileName": "/Users/matb/projects/san/index.js",
        "textChanges": [
            {
                "start": {
                    "line": 3,
                    "offset": 20
                },
                "end": {
                    "line": 3,
                    "offset": 28
                },
                "newText": "./new.js/index.js"
            }
        ]
    }
]
```

It still seems to me like TS Server itself is generating an invalid code edit. On the VS Code side, we don't make any edits to `index.js` before asking the TS Server for the edits

**Closed** 2019-11-20 23:00 UTC
Labels: Bug, VS Code Priority
