### ISSUE TITLE
Exclude doesn't work with generics

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#21941] opened 2018-02-14 13:33 UTC
**TypeScript Version:** 2.8.0-dev.20180214

**Code**

```ts
type A = { A: number; B: number };
type ExcludeB<T> = Exclude<keyof T, 'B'>;
type B = ExcludeB<A>; // 'A' | 'B'
type C = Exclude<keyof A, 'B'>; // 'A'

function stripB<T>(key: T): Pick<T, Exclude<keyof T, 'B'>> {
    return null!;
}
stripB({A: 1, B: 1}) // -> {A: number, B: number}


```

**Comment by jcalz** [comment] 2018-02-14 16:01
Duplicate of #21929 ?

**Comment by ahejlsberg** [comment] 2018-02-14 17:10
Duplicate of #21862.

**Closed** 2018-02-28 21:41 UTC
Labels: Duplicate
