### ISSUE TITLE
 Nicer object destructuring in function declarations

### ISSUE THREAD

**Issue by uwinkler** [microsoft/TypeScript#52454] opened 2023-01-27 08:08 UTC
# Nicer object destructuring in function declarations

## 🔍 Search Terms
 
object destructuring function declarations

## ✅ Viability Checklist

My suggestion meets these guidelines (I guess):

* [ x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ x] This wouldn't change the runtime behavior of existing JavaScript code
* [x ] This could be implemented without emitting different JS based on the types of the expressions
* [x ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Object destruction in functions can be cumbersome. Using defaults makes it slightly easier, but it would be great if it could be written in a simpler way.

## 📃 Motivating Example

```ts
// The current way of doing object destructuring in function declarations
// is cumbersome, lengthy, and repetitive  
// 🥺
function Rectangle({
  width,
  height,
  fill
}: {
  width: number
  height: number
  fill: 'dark' | 'light'
}) {}
 

// 😍 ... maybe this could be done "nicer" by just providing the type?
function Rectangle({width:number, height:number, fill: 'dark' | 'light'}) {}

// 🤔 Currently, we can use defaults to achieve something along this line:
function Rectangle({width = 200, height = 200, fill = 'dark'}) { }
// ... , but `fill` would not be typed correctly 🥺 and maybe we don't want 
// to use default values in the first place

// 😍 Could this be the way to do it with correctly typed defaults? 
function Rectangle({width = 200, height = 200, fill: 'dark' | 'light' = 'dark'}) {}

// 😍 ...or kind of "mixed" mode? 
function Rectangle({width = 200, height = 200, fill: 'dark' | 'light'}) {}
```

## 💻 Use Cases

This is a common pattern in React code.

**Comment by MartinJohns** [comment] 2023-01-27 08:55
Duplicate of #29526.

**Closed** 2023-01-31 18:00 UTC
Labels: Duplicate
