### ISSUE TITLE
Indexing mapped type with union key returns bad function union

### ISSUE THREAD

**Issue by TheFireBlast** [microsoft/TypeScript#49506] opened 2022-06-12 19:04 UTC
# Bug Report

### 🔎 Search Terms

generic, mapped types, parameter, argument, union, never

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about mapped types
(Note: versions before `3.9.7` in the playground report the same error, just with a different message)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKg9gawgOygXigbyqSAuKAIgEFCoBfKAHyx3AgMICEzyBuKAek5u1waIBhVtVr9GAERG86+IgFFpY+owBiSviqIBxVmwBQ-WIhQAJAIbIAJgBsIAJwA8MAHzooACmAnkBeElQAMmU5GAoASnQ3SxADI38UAFlzMHdMfShMqABtMIBLVATkbMJ+QgBdcr8fC2s7J1cDdn19AGM4ZABnYBway1sHTrSoYi8fSMxKTgAqKAA6BahpzgoocyGi5LADdq6e7wDh8SJSVfXjAIN9bigAJQhOuBsANwfei7N++scSQjcaIq1AZOZh-a4rfpQABGEHaAFs3mMEARkBBXvZImg3M84HkrOCoAVuhBzFYoHAAGY4AAW0AgAA9IK1gBAyUjqodgpo5L9RKCIlE1sgQG0Ot0oNSvg53AdPnVBtlZcg5vxygZJfL7EiUOEODcHPY4PYCMR7ABzACuCOQPUpsmgAHIig7CUNkHAeutOnkzchzFC7O8wOZ7OYESz7OSqUYHaj0Q65gTiNZCVSAO7QUlkuFG6BK+1DDNQM0QHoGo0EeSM+wPb0dKBgQ1WC2tN7mKAW5B5etGYCSnp5IbeOBQeFgOz0941xsPFDARNAA)

### 💻 Code

```ts
type Token = { type: "A" } | { type: "B" }; //| { type: "C" } | { type: "D" } | { type: "E" } | { type: "F" } | { type: "G" };
type TokenHandler<T> = (token: Token & { type: T }) => any;
type TokenMap = {
    [T in Token["type"]]: TokenHandler<T>;
};

const tokenHandlers = { A(token) {} /* ... */ } as TokenMap;
const token = { type: "A" } as Token;

// Resolves to TokenHandler<"A"> | TokenHandler<"B">
// and becomes (tok: never) => void
// instead of the expected (tok: Token & { type: "A" | "B" }) => any
const handler = tokenHandlers[token.type];
handler(token); // error: Argument of type 'Token' is not assignable to parameter of type 'never'.
// And if we add more token types we get error: Expression produces a union type that is too complex to represent.
```

Making the function itself generic solves the error, but now we lose typing for the `token` parameter

##### [Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKg9gawgOygXigbyqSAuKAIgEFCBuKAQwIGdgAnAS2QHMoBfKAHyx3AgKEAQuSgAjAsgCuAWzER6HMgChc0eEmQAJSsgAmAGwUAeGAD50UU2YAUwRCgIaUUAGS81TjgEp0F3SAqarAOyACylGCWmMpQcVAA2jBQzCGaCYRqhAC62U6hOvpG9NYq7CrKAMZwyHQ4BbqGCjTRsfEA9O1QCvRw9AQACr2Q9KBQAOSU41B6cBAtyHDA3QAejHU1fJATzqju2J6wFOzjAHRtccR2ob7Y9BDAUvSo9pqnlMcXUJ1Qp3-KnEoLV2ETAKmqtWWrxcGAO-EEpA4VGBoQqPwASvM4AYAG7zeppFCFJolEiECw8XbE4rGYTk5Q-RriCDVGT42mInh02yvfKaNweeFETlEEQ+PxUZAgKo1OoAC0axUs0O0iuaCRVpzU2RUCqKCmumm8FB+iCAA)

```ts
type Token = { type: "A"; a: string } | { type: "B"; b: number };
type TokenHandler<T> = <T>(token: Token & { type: T }) => any;
type TokenMap = {
    [T in Token["type"]]: TokenHandler<T>;
};

const tokenHandlers = {
    // error: Property 'a' does not exist on type 'Token & { type: T; }'.
    A(token) { return token.a; }
    // ...
} as TokenMap;
const token = { type: "A" } as Token;

// Resolves to TokenHandler<"A"> | TokenHandler<"B">
// and becomes <"A" | "B">(tok: Token & { type: "A" | "B" }) => any
const handler = tokenHandlers[token.type];
handler(token); // ok
```

The only workaround I can think of is to cast every time it's indexed

```ts
// Resolves to TokenHandler<"A" | "B">
// and becomes (tok: Token & { type: "A" | "B" }) => any
const explicitCast = tokenHandlers[token.type] as TokenHandler<typeof token.type>;
explicitCast(token); // ok

// Avoids having to use cast everywhere, but adds runtime overhead
function getHandler<T extends Token["type"]>(tokenType: T) {
    return tokenHandlers[tokenType] as TokenHandler<T>;
}
const functionCast = getHandler(token.type);
functionCast(token);
```

### 🙁 Actual behavior

`TokenMap['A' | 'B']` resolves to `(tok: never) => any`

### 🙂 Expected behavior

`TokenMap['A' | 'B']` should resolve to `(tok: Token & { type: "A" | "B" }) => any`

**Comment by fatcerberus** [comment] 2022-06-12 20:09
Given that you have `TokenHandler<"A"> | TokenHandler<"B">`, this being a union implies the program doesn't know which one it is - so the only value you can safely call it with is `Token & { type: "A" & "B" }`--of which no value exists.  Hence `never`.  If it were `Token & { type: "A" | "B" }` then I could take `tokenHandlers[token.type]` and freely pass it the wrong type with no complaint from the compiler.

**Comment by jcalz** [comment] 2022-06-13 02:50
This looks like a duplicate of #30581, and the fix as described/implemented in #47109 involves refactoring to something like

```ts
type TokenTypes = "A" | "B" | "C"
type Token<K extends TokenTypes = TokenTypes> = { [P in K]: { type: P } }[K];
type TokenHandlers = {
    [K in TokenTypes]: (token: Token<K>) => any;
}

const tokenHandlers = { A(token) { } /* ... */ } as TokenHandlers;
const token = { type: "A" } as Token;

function handleToken<K extends TokenTypes>(token: Token<K>) {
    const handler = tokenHandlers[token.type];
    handler(token); // okay
}

handleToken(token); // okay
```

[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKg9gawgOxuCBnKBeKAiAQTygB98AhYsvAYTwChRJZEUAeAaSggA9gUAJlnhJU6LLhEo0kDAD4cUAN5QA2gAUoAS2RQOAXQBcyqEwjHNAXyiXVBgNyN0LUQAkAhsgEAbCACcJZXooELUuHRdpcSMoAApgVmRjKWROOQBKHAVPEEdLenoAYzhkDGBTRI8vXwDFFQJ4xMyVawB6ACooADoeqHbWmyh3YUrPH38MR2LS8oTROtN0Y0Jia2HI5Ed6ADMAV2RC4C0SqAALMd8Uzm4+QRHRGUw5RtFkxLTm4NDpsrOL-0UcxQVXGAVUQOQXTM+kcoT+1X8LxQ6XsUFaA0Q7hA9Hy9HOCJSSOQKLRGIQWPoQA)

**Comment by fatcerberus** [comment] 2022-06-13 03:30
Thanks @jcalz, I knew this was a job for correlated unions but couldn’t remember what those were actually *called* in order to search for the relevant issue. 😅

**Closed** 2022-06-15 20:00 UTC
Labels: Working as Intended

**Comment by Haroenv** [comment] 2023-07-18 09:38
It took me a while to understand what's going on in this case, but it's the closest to the situation I had so I'll share here too: 


```ts
const suites = {
  key1(_arg0: 11, _arg2: 12) {},
  key2(_arg0: 21) {},
  key3(_arg0: 31, _arg2: 32) {},
  key4(_arg0: 41, _arg2: 42) {},
  key5(_arg0: 51, _arg2: 52) {},
  key6(_arg0: 61, _arg2: 62) {},
  key7(_arg0: 71) {},
  key8(_arg0: 81, _arg2: 82) {},
};

type Tests = typeof suites;
type TestSuites = {
  [key in keyof Tests]: (
    setup: TestSetups[key],
    option: TestOptions[key]
  ) => void;
};
type TestSetups = {
  [key in keyof Tests]: Parameters<Tests[key]>[0];
};
type TestOptions = {
  [key in keyof Tests]: Parameters<Tests[key]>[1];
};

const setups: TestSetups = {
  key1: 11,
  key2: 21,
  key3: 31,
  key4: 41,
  key5: 51,
  key6: 61,
  key7: 71,
  key8: 81,
};

const options: TestOptions = {
  key1: 12,
  key2: undefined,
  key3: 32,
  key4: 42,
  key5: 52,
  key6: 62,
  key7: undefined,
  key8: 82,
};

(Object.keys(suites) as Array<keyof TestSuites>).forEach(
  <T extends keyof TestSuites>(key: T) => {
    const suite: TestSuites[T] = suites[key];
    suite(setups[key], options[key]);
  }
);
```

[playground](https://www.typescriptlang.org/play?ts=4.8.4#code/FAYw9gdgzgLgBFArgSxgUynAvHA3sOOAazQE8BGACgH0BDAJwHMAGALjnPIBo46mAmduX4BKPAF8uBYmX40GLdv3Jjck6SVIBmeUzZwt3XgsEHREqYU0AWXYrjWjfRqevm1lmaQCsd-d6cTdm93dSsyADY-dgjAgRjQz00Admi4ZJULDTIADjScuJd2HMTgcQBuYGAYUgAHNDgAFQwYTBwa+rAAMwQUdChKjobm2ABlPoxsPGkAbU04ZAgvbqaWqABddkppQig0GERa9hGYUf3DqDmydc9CMFqYZEhjloB5B6foK9J16TEsAB8cAAbmBkAATSoVap1YYtM4HWptaaEb4LJaaFYnDbsAAKDFoAFt9mh6FAADzY77rAEzZjrKGDWGrWDvR6QZH4VHzRbLHrYzZwfH0IkksmUtbU2nkBllSqgDnwPaIqAvMbnJFTLlechCbjZUimZRJMhadiGE2kazsRyW7zBfXhUgRGKOrzJdgZS05Yr66EK6Dwe7s6BqmBsz6cg26jj8S2mRAQcFoLqLNDgy1msyW60OOMG+1wEKWl1wCL5p0euCJ5OpiDp73FfP+yivABGACs0CAYAA6TRQShIVAYMS0TAAQXoItI5Mx-PhEygAJEva6YHoAFFaCAABbbQiUuBoAAe6CTmHnLNOS4BlE0x3+QO1hHAgd6I7D4xHl0a6ymw79NSlSELsExDhqlyaDccDBpG1IiCBcDiMAiHAEAA)


If I understand what's going on, it's because you can't rely on the original object you're using for the map, but have to create an intermediary type that also uses the keys to determine the type, thus "linking" the relationship of the types.

Thanks a lot @jcalz !
