### ISSUE TITLE
Not very helpful navtree labels for ES5 methods

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#31540] opened 2019-05-22 19:49 UTC
**TypeScript Version:**  3.5.0-dev.20190522

**Search Terms:**
- outline
- navtree

**Code**
For the javascript:

```ts
function A() { this.x = 1; }
A.prototype.initialize = function() {};

function B() { this.x = 1; }
B.prototype.initialize = function() {};

function C() { this.x = 1; }
C.prototype.initialize = function() {}; 
```

Look at the outline view in VS Code

![Screen Shot 2019-05-22 at 12 48 26 PM](https://user-images.githubusercontent.com/12821956/58203904-030f9b00-7c90-11e9-8483-5671a8477312.png)

**Bug:**
VS Code's outline uses the TypeScript `navtree` request. The response in this case does not provide very helpful labels for the `initialize` methods:

```
Result: {
    "text": "<global>",
    "kind": "script",
    "kindModifiers": "",
    "spans": [
        {
            "start": {
                "line": 1,
                "offset": 1
            },
            "end": {
                "line": 9,
                "offset": 41
            }
        }
    ],
    "childItems": [
        {
            "text": "A",
            "kind": "function",
            "kindModifiers": "",
            "spans": [
                {
                    "start": {
                        "line": 2,
                        "offset": 1
                    },
                    "end": {
                        "line": 2,
                        "offset": 29
                    }
                }
            ],
            "nameSpan": {
                "start": {
                    "line": 2,
                    "offset": 10
                },
                "end": {
                    "line": 2,
                    "offset": 11
                }
            }
        },
        {
            "text": "B",
            "kind": "function",
            "kindModifiers": "",
            "spans": [
                {
                    "start": {
                        "line": 5,
                        "offset": 1
                    },
                    "end": {
                        "line": 5,
                        "offset": 29
                    }
                }
            ],
            "nameSpan": {
                "start": {
                    "line": 5,
                    "offset": 10
                },
                "end": {
                    "line": 5,
                    "offset": 11
                }
            }
        },
        {
            "text": "C",
            "kind": "function",
            "kindModifiers": "",
            "spans": [
                {
                    "start": {
                        "line": 8,
                        "offset": 1
                    },
                    "end": {
                        "line": 8,
                        "offset": 29
                    }
                }
            ],
            "nameSpan": {
                "start": {
                    "line": 8,
                    "offset": 10
                },
                "end": {
                    "line": 8,
                    "offset": 11
                }
            }
        },
        {
            "text": "initialize",
            "kind": "method",
            "kindModifiers": "",
            "spans": [
                {
                    "start": {
                        "line": 3,
                        "offset": 1
                    },
                    "end": {
                        "line": 3,
                        "offset": 39
                    }
                }
            ],
            "nameSpan": {
                "start": {
                    "line": 3,
                    "offset": 13
                },
                "end": {
                    "line": 3,
                    "offset": 23
                }
            },
            "childItems": [
                {
                    "text": "initialize",
                    "kind": "function",
                    "kindModifiers": "",
                    "spans": [
                        {
                            "start": {
                                "line": 3,
                                "offset": 26
                            },
                            "end": {
                                "line": 3,
                                "offset": 39
                            }
                        }
                    ],
                    "nameSpan": {
                        "start": {
                            "line": 3,
                            "offset": 13
                        },
                        "end": {
                            "line": 3,
                            "offset": 23
                        }
                    }
                }
            ]
        },
        {
            "text": "initialize",
            "kind": "method",
            "kindModifiers": "",
            "spans": [
                {
                    "start": {
                        "line": 6,
                        "offset": 1
                    },
                    "end": {
                        "line": 6,
                        "offset": 39
                    }
                }
            ],
            "nameSpan": {
                "start": {
                    "line": 6,
                    "offset": 13
                },
                "end": {
                    "line": 6,
                    "offset": 23
                }
            },
            "childItems": [
                {
                    "text": "initialize",
                    "kind": "function",
                    "kindModifiers": "",
                    "spans": [
                        {
                            "start": {
                                "line": 6,
                                "offset": 26
                            },
                            "end": {
                                "line": 6,
                                "offset": 39
                            }
                        }
                    ],
                    "nameSpan": {
                        "start": {
                            "line": 6,
                            "offset": 13
                        },
                        "end": {
                            "line": 6,
                            "offset": 23
                        }
                    }
                }
            ]
        },
        {
            "text": "initialize",
            "kind": "method",
            "kindModifiers": "",
            "spans": [
                {
                    "start": {
                        "line": 9,
                        "offset": 1
                    },
                    "end": {
                        "line": 9,
                        "offset": 39
                    }
                }
            ],
            "nameSpan": {
                "start": {
                    "line": 9,
                    "offset": 13
                },
                "end": {
                    "line": 9,
                    "offset": 23
                }
            },
            "childItems": [
                {
                    "text": "initialize",
                    "kind": "function",
                    "kindModifiers": "",
                    "spans": [
                        {
                            "start": {
                                "line": 9,
                                "offset": 26
                            },
                            "end": {
                                "line": 9,
                                "offset": 39
                            }
                        }
                    ],
                    "nameSpan": {
                        "start": {
                            "line": 9,
                            "offset": 13
                        },
                        "end": {
                            "line": 9,
                            "offset": 23
                        }
                    }
                }
            ]
        }
    ]
}
```

**Comment by DanielRosenwasser** [comment] 2019-05-22 19:52
Duplicate of #31516.

**Closed by DanielRosenwasser** 2019-05-22 19:52 UTC
