### ISSUE TITLE
ts(2339)

### ISSUE THREAD

**Issue by thebinarysearchtree** [microsoft/TypeScript#47002] opened 2021-12-03 10:58 UTC
# Bug Report

### 🔎 Search Terms
ts(2339)

### 🕗 Version & Regression Information
4.5.2

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ts(2339)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBFCm0YF4YAoCUKB8MDeAUDDADbyzAkCW8YUA3ETANoCMANDAEycDMAugDoAtgEMADmkw58TYpRp0UMMPADuMACKiEmRsQC+GfTCoAzdAtpQshYsQBO5AK4OwMK3UEBzcgBUqYXg9JgMCAyA)

### 💻 Code

```ts
const test = () => {
  let client;
  [1, 2, 3].map(() => {
    client = new Date();
  });
  if (client) {
    return client.getTime();
  }
}
```

### 🙁 Actual behavior

JavaScript file.
ts(2339) on getTime as it doesn't recognise the assignment inside map.

### 🙂 Expected behavior

No error. The JavaScript runs and is valid and therefore should not have an error.

**Comment by MartinJohns** [comment] 2021-12-03 11:31
Another duplicate of #9998.

**Closed** 2021-12-05 18:00 UTC
Labels: Duplicate
