### ISSUE TITLE
The specified ITextSnapshot doesn't  belong to the correct TextBuffer

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#1153] opened 2014-11-13 16:06 UTC
Hi,

**VS**: 2013 Update 4 RC
**TS**: 1.3

I got an exception message box when hitting F12 on a `require` path. Following on from the exception the F12 continues to work correctly (i.e. navigates to the target path).

I am currently not able to reproduce this.

The entry from the activity log is below:

```XML
  <entry>
    <record>888</record>
    <time>2014/11/13 15:54:31.369</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentException: The specified ITextSnapshot doesn&apos;t 
belong to the correct TextBuffer.&#x000D;&#x000A;   
at Microsoft.VisualStudio.Text.SnapshotSpan.TranslateTo(ITextSnapshot targetSnapshot,
SpanTrackingMode spanTrackingMode)&#x000D;&#x000A;   
at TypeScriptLanguageService.Features.HighlightReferences.HighlightReferencesController.&lt;GetTags
&gt;d__7.MoveNext()&#x000D;&#x000A;   
at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;
d__5.MoveNext()
</description>
  </entry>
```

**Comment by mhegazy** [comment] 2015-01-21 23:09
This should be resolved in the latest release (1.4). please reopen if it still reproduces.

**Comment by NoelAbrahams** [comment] 2015-01-22 12:03
@mhegazy, just got this while editing a require path:

![image](https://cloud.githubusercontent.com/assets/1106823/5855228/c83f3f1c-a22d-11e4-812d-a41fb5dd28b1.png)

The entry from `ActivityLog.xml` appears to be the same:

```
System.ArgumentException: The specified ITextSnapshot doesn&apos;t belong to the correct TextBuffer.&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.SnapshotSpan.TranslateTo(ITextSnapshot targetSnapshot, SpanTrackingMode spanTrackingMode)&#x000D;&#x000A;   at TypeScriptLanguageService.Features.HighlightReferences.HighlightReferencesController.&lt;GetTags&gt;d__7.MoveNext()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__5.MoveNext()
```

> please reopen if it still reproduces

Ordinary users do not have privileges to reopen closed issues.

**Comment by paulvanbrenk** [comment] 2015-03-16 23:51
implemented a fix for the next TypeScript release for Visual Studio 2013, to prevent the crash. And added a some debugging code to help figure out why this may be happening.

**Closed by paulvanbrenk** 2015-03-16 23:51 UTC
Labels: Bug, Needs More Info

**Comment by frenklin** [comment] 2017-12-15 10:17
not sure if it's related to TypeScript but I got similar exception when editing cshtml file in VS2017 

System.ArgumentException: The specified ITextSnapshot doesn&apos;t belong to the correct TextBuffer.&#x000D;&#x000A; 

There is full error message
https://gist.github.com/frenklin/4f53700acedafd0b2418739a23972327

**Comment by paulvanbrenk** [comment] 2017-12-15 19:26
@frenklin your issue seems related to go `Microsoft.VisualStudio.Language.Intellisense.Implementation.GoToDefMouseHandler` which is different from this issue.. which version of VS are you using?

@armanio123 FYI

**Comment by frenklin** [comment] 2017-12-15 20:29
@paulvanbrenk, after yesterday's update to 15.5.2 it disappear. Unfortunately I don't know pervious version number. I think it happened when I have started editing cshtml file before syntax/type validation. After VS2017 was updated syntax/type validation works faster and it has finished before I did any changes. Anyway I can't reproduce it after update.
