### ISSUE TITLE
Using "implements" causes an issue with string literal types. "extends" does not.

### ISSUE THREAD

**Issue by dsifford** [Microsoft/TypeScript#10071] opened 2016-08-01 17:57 UTC
**TypeScript Version:**  nightly (2.0.0-dev.201xxxxx)

**[Relevant StackOverflow discussion](http://stackoverflow.com/questions/38687670/class-implements-another-class-getting-errors-looking-for-clarification)** 

**[Playground](https://www.typescriptlang.org/play/#src=class%20Test%20%7B%0D%0A%09someObj%3A%20%7B%0D%0A%09%09someString%3A%20'this'%7C'that'%7C'the%20other'%0D%0A%09%7D%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Test2%20implements%20Test%20%7B%0D%0A%09someObj%20%3D%20%7B%0D%0A%09%09someString%3A%20'this'%0D%0A%09%7D%0D%0A%7D)**

Kudos to @nitzantomer for looking into this

**Code**

```ts
// This is defined in a d.ts file. 
class Test {
    someObj: {
        someString: 'this'|'that'|'the other'
    };
}

// This is me actually using the class.
class Test2 implements Test {
    someObj = {
        someString: 'this'
    }
}
```

**Expected behavior:**
No error thrown. Using literal `'this'` as the value for `someObj.someString` correctly implements class.

**Actual behavior:** 
Error thrown.

```
Class 'Test2' incorrectly implements interface 'Test'.
  Types of property 'someObj' are incompatible.
    Type '{ someString: string; }' is not assignable to type '{ someString: "this" | "that" | "the other"; }'.
      Types of property 'someString' are incompatible.
        Type 'string' is not assignable to type '"this" | "that" | "the other"'.
          Type 'string' is not assignable to type '"the other"'.
```

**Comment by weswigham** [comment] 2016-08-01 18:21
@sandersn Was looking into a related issue before - contextually typing inherited methods - I believe this is similar.

**Comment by DanielRosenwasser** [comment] 2016-08-03 08:41
Duplicate of #1373 and #3667.

See @sandersn's PR and explanation of why we couldn't do this at https://github.com/Microsoft/TypeScript/pull/6118#issuecomment-216595207.

**Closed by DanielRosenwasser** 2016-08-03 08:41 UTC
