### ISSUE TITLE
Incorrect inference when using an optional argument 

### ISSUE THREAD

**Issue by ShayDavidson** [microsoft/TypeScript#57021] opened 2024-01-11 13:08 UTC
### 🔎 Search Terms

Inference, Return, Arguments, Parentheses, Identity Function.

### 🕗 Version & Regression Information

This reproduces in all available playground versions (tried down to 3.3.3), and also in 5.3.3.

### ⏯ Playground Link

[Link](https://www.typescriptlang.org/play?ts=5.3.3#code/C4TwDgpgBAygxgCwgWwIZQLxQEoTgewCcATAHgGdhCBLAOwHMAaKAV1oGtb8B3WgPigB6QVGT5i1AGbUIxKJML5kUItXp1UAG3lEowJFHKp20fJL0GIAD1TIwmiMylRqwKMXwRytAORu0JoYQtOQQAFBhoJCwwBBgAGJscMDU+LSkYVBQACrwSGhQ1rG0xOSwiCjoWHmVjGECWAAUqLQg+nT0AFysHFy8AJSYAgDemVCEEKgetJoghhVo3bkLqGMTU2mzevgAgiHcEITkAPzdjSYg5N0XZjk1aIMYAmycPLRhAL4RkkkpaYaxMCkZb5dBFYKlcqgzBQyp8RpjLKUOIANS03RggMStGSqXSILhdSy-QxWN+eOB91QI0R4wgwBYhFoANRWjGXzCwigAFEABo7ACyAAUADLcmBQABC3JFAHkAOqdTkiABy+BScGg+mgEwZTNkKgARgArPBuW5abQ-HF-EIuMrawy2CAAQhyBgkkkkh2CmrKqAmLloSq5AFooNwkNrCBHoCxQhZoAADXWM2hJqAXbhEOS6LhuRrHF1F-rKqDhyP0pAxg5QBCoABuWoMAfoLGQwTckl0jqTyLAGetuP+efVADooGrYhZUG5nABJdz4KBJoUB52xI6kKIQW7IECY1maFgQPgZiBN5mV5mO1vtzv20TUcjkDpOYA+Mp0b2ECZyAi-maWyNC6pZlvKsrYAA0jA3RJhc5AZs+QY-n+UCGqgoS5jeBh9isSZluGXBQHeHa0F2uh9oCg7kmkhFQMRKb0mmGZZjmYQECEbjZoQ7AdNyNh2A4ML9o0jSPAIjSjEiKzdNJWQkcAVDUIaLCxN0PgtG0CAdD4RJQB8+nALs+yHFcmYQJcQxQPJWQIbSXIAHrHBEClCCI2DigAqiK2RwQhGbkCwcCarIX60D+vrQJhK6zspqmxARbk7jkXhuFglA0AwhRWMUkI7rcCFQMcDEXocUAaVQJ4+LSnGUHoaVLGlMJ+IQ1W0qmTI2Q19VfFkhmfP0YFcvEOzziKsErgFj75ihhxoRhWEqDhybkPh9H1v6hBtmRFExlRcQ0TaeIcWk9VcLQ8pEHxDA7CJgKNAA+uQShVh01lSWMa2gnJtJxTQCUQBpWntAwenskZJnkAcRzXJZZRPDZtL2W5TkuW5Dked5vn+fDg6oNQmjhZFOLQEgpPuBAkioCwmjAA6y5UVl9BJQpKXZM1GXKdl4IlA64C7uYRUlbQZUxpVbUQDVbl1W4sSUE19VYK17VuZ1zLDD1bh9QZdQfENERAA)

### 💻 Code

This is a followup on https://github.com/microsoft/TypeScript/issues/49951 which @Andarist asked me to open a follow-up issue. Also relates to https://github.com/microsoft/TypeScript/issues/47599

Probably better to check the playground for code examples, but here's the TL;DR:

TYPES DECLERATIONS:
```typescript
type Schema = Record<string, unknown> // modified from original for the sake of the example, if it doesn't make sense

type StepFunction<
  TSchema extends Schema = Schema,
> = (anything: unknown) => {
  readonly schema: TSchema
  readonly toAnswers?: (keys: keyof TSchema) => unknown
}

function step<TSchema extends Schema = Schema>(
    stepVal: StepFunction<TSchema>,
  ): StepFunction<TSchema> {
    return stepVal
  }
```

EXAMPLES:
Notice the returned object of all functions is the same! The difference is in whether we have the argument for the `step` function or not. Note that if I do `Parameters<typeof myStepValue>` even when the argument is missing, it's inferred correctly (!)

```typescript
// WORKS: `keys` is inferred based on the `schema`
// - no argument for `step` function
// - no `return` keyword
const workingExample = step(() => ({
  schema: {
    attribute: 'anything',
  },
  toAnswers: keys => {
    // RESULT: `keys` inferred successfully as `attribute`
    type Test = string extends typeof keys ? never : 'true'
    const test: Test = 'true'
    return { test }
  },
}))
```

```typescript
// FAILS: `keys` is not inferred based on the `schema`
// - has argument for `step` function
const nonWorkingA = step(_something => ({
  schema: {
    attribute: 'anything',
  },
  toAnswers: keys => {
    // RESULT: `keys` failed to be inferred hence defaults to `string`
    type Test = string extends typeof keys ? never : 'true'
    const test: Test = 'true'
    return { test }
  },
}))
```

### 🙁 Actual behavior

Nested value's function argument cannot be inferred correctly.

If I change the property (`toAnswers`) from a function to a simple property, there are no inference issues.

### 🙂 Expected behavior

Nested value function argument should be inferred correctly regardless of the `return` keyword or declaring the arguments.

### Additional information about the issue

Like mentioned above, this is a followup on https://github.com/microsoft/TypeScript/issues/49951 and https://github.com/microsoft/TypeScript/issues/47599

**Comment by ShayDavidson** [comment] 2024-01-12 10:41
It's an inferred schema object (something like Zod).

**Comment by Andarist** [comment] 2024-01-12 11:20
Ye, I get that - but I wonder what's the nature of the outer `anything` parameter. It stays unused in this example.

I think the fix for this is introducing an extra inference pass on return expressions from context-sensitive functions. I was thinking first about extending the intra-expression inference to handle this but I think that would be a worse solution. It wouldn't handle `{ toAnswers, schema }` (consumer before producer).

It's funny-ish that the intra-expression inference is responsible for making this work:
```ts
type Schema = Record<string, unknown>;

type StepFunction<TSchema extends Schema = Schema> = (anything: unknown) => {
  readonly schema: (thing: number) => TSchema;
  readonly toAnswers?: (keys: keyof TSchema) => unknown;
};

function step<TSchema extends Schema = Schema>(
  stepVal: StepFunction<TSchema>,
): StepFunction<TSchema> {
  return stepVal;
}

const nowItsOk = step((_something) => ({
  schema: (thing) => ({
    attribute: "anything",
  }),
  toAnswers: (keys) => {
    keys;
    // ^?

    type Test = string extends typeof keys ? never : "true";
    const test: Test = "true"; // ok
    return { test };
  },
}));
```

Usually, context-sensitive functions make things to be inferred worse (like in your original example) - but this example above infers better when an extra context-sensitive function is included. This is a little bit unusual and purely related to how all of this is already nested in one context-sensitive function.

**Comment by ShayDavidson** [comment] 2024-01-12 11:45
Oh, I thought you meant for the inner `anything`. 

It's a `store` that allows to get data based on the inference of the schema, something like:

```typescript
type StoreFor<TSchema extends Schema> = {
  get: <T extends keyof TSchema>(key: T) => TSchema[T]
}


type StepFunction<
  TSchema extends Schema = Schema,
> = (store: StoreFor<TSchema>) => {
  readonly schema: TSchema
  readonly toAnswers?: (keys: keyof TSchema) => unknown
}
```

Still fails and demonstrated in [this playground link](https://www.typescriptlang.org/play?ts=5.3.3#code/C4TwDgpgBAygxgCwgWwIZQLxQEoTgewCcATAHgGdhCBLAOwHMAaKAV1oGtb8B3WgPigB6QVGT5i1AGbUIxKJML5kUItXp1UAG3lEowJFHKp20fJL0GIAD1TIwmiMylRqwKMXwRytAORu0JoYQtOQQAFCgkLDARBAAYkSkACrwSGhQ1sDBxOSwiCioAlgA3mFQUPQQwABcUMkZVlm0OVAmIGZQKflofAAUbbVJAJSYAl1pqADaSQC6YQC+YUuR0DBZYHFscMDU+LSkZZ2pBQ1NLcfpWBeojGFFUL2UsbVrsQmEydd8IxgCpeWECCoDy0TQgQzdVCDa6HQHAvZgvT4ACCIW4EEI5AA-LV+hAQORam0OuMCj8BGxODxaAslpItjs9oZ1p9Iadsrlrpg8hM+odypQIGAAGpaF7rTa0ba7faknq3cpDcVCyXSvas3lQf7lKCA4AsQi0ZlC0WaQ6LMLCKAAUQAGsiALIABQAMtaYFAAELWl0AeQA6tVLSIAHL4HZwaD6aB6g20WQqABGACs8G4OlptPSpYyQi5ctHDLYIABCToGCSSSQY4KR3KoQEuWhBq0AWig3CQ0cIHegLFCFmgAANY4ah618dwiHJdFw3L0sSXF0Ng1B252qkge+ioAhUAA3KMGBv0FjIYJuSS6QtDwVgcfZtVG2fhgB0UDDWQsqDczgAku4+BQEOToNsWWSYqQKwdMgIBrCaWgsBAfDjhAh5GhuRqFieZ4XvmojUOQ5B0EwLjAD4uR0NWhCAnIBA0WmiK9CWK6rv6vrYAA0jAtRDm05DjoRTbUbRUCJqgoQzlhBi3pCQ6ru2XBQDh560Jeui3usD4MjKClQEpI5VHG45tFOJBhAQIRuGZ7AkdaNh2A43J3r0vTkg82rkJCtTauUP5UNQiYsFktQ+KgtAgPoJE+AqUDzLFMSouQ6KYkS+K5L8Wr8hOBLZVaAB6WJLDqQgiNg7oAKoukkvH8eO5AsHAkayJRtDUbW0AScB-k0EFWTySVKydF4bhYJQNAMOyzQFuAEAdPxUBYvpaEYlAoVUEhPjZZZlB6CNgwjdyfiEJt2WjkaxR7btizlPFCxDKxVpxMif4ujxwF1fhc7CRioniZJKjScOXkTPJba7l1Kl4VePaaUK2k5rpO1uFwtD+kQtkMMiznrL0AD65BKJuJGjB5hwgwUPnZT1gXBRAoXhZFCDRbFd3lIlaIYoSOUZX82X8XlIiFdlgs4JV1W1elD6oNQmite1UrQEgivuBAkioCwmjAAWQGaRN9ADTqQ1JIdY0BZNmQcnos3zeli3LYePbrSdEBbSVyNXTUw27Vgx2nSV51ap7cXmrc8wPUsQA).

**Comment by ShayDavidson** [comment] 2024-01-12 11:47
As for adding a function - well, I could add it - but it's a breaking change for the consumers of my library hence I prefer to refrain from it 😅

**Comment by Andarist** [comment] 2024-01-12 11:50
> As for adding a function - well, I could add it - but it's a breaking change for the consumers of my library hence I prefer to refrain from it 😅

Oh, I certainly didn't imply that you should change this anyhow. I just forked ur example to demonstrate a TS behavior 😉 it was more convenient than having to retype the same thing with some dummy function names etc.

> It's a store that allows to get data based on the inference of the schema, something like:

Do you have any example of when this `store` would actually be used and when it's type argument would be inferred? My hot take on this example is that there is no easy way to make this one work. It's a circular dependency of sorts. Your return type might depend on this parameter but its type depends on that return type.

**Comment by ShayDavidson** [comment] 2024-01-12 11:59
Yes, I'll demonstrate how this is used in actual code more or less - I understand why this is confusing. 

The schema defined in my example is not the same schema defined for the `store`.

Imagine I'm writing a wizard flow, and I have a parent global schema, that I can get previously answered values through the store. Each step in the wizard can defined a sub-schema for transient answers (which is defined through the `schema` attribute). The `toAnswers` function simply takes these transients answers and needs to return an object that satisfies the parent schema partially. 

```
step((store) => ({
  schema: {
    fullName: string(),
  },
  toAnswers: (transientAnswers) => {
     return { firstName: transientAnswers.get('fullName').split(' ')[0] }
  },
}));
```

e.g. in this example you can assume I have a `store` argument that knows it supports only the parent-schema, which has `firstName` has an attribute, but is completely decoupled from the `schema` inside the step definition.

**Comment by ShayDavidson** [comment] 2024-01-12 12:01
To make things simpler - the step function is actually generated through something I call `StepCreator`, which literally accept the parent-schema as argument (so no need to do hard inference there):

```
const creator = new StepCreator({ parentSchema: { firstName: string(), lastName: string() }})

const step = creator.step((store) => {...}) // like the `step` function above. the `store` argument is typed based on the constructor params
```

**Comment by Andarist** [comment] 2024-01-12 12:03
> The schema defined in my example is not the same schema defined for the store.

Ah, ok - then the snipper in https://github.com/microsoft/TypeScript/issues/57021#issuecomment-1888949418 doesn't exactly show the real usage. Thanks for the explanation. 

If those are two different schemas then ye, it might work.

**Comment by RyanCavanaugh** [comment] 2024-01-12 21:24
This is basically #47599, specifically the part about

> Perform a more robust check to determine "true" context-sensitivity -- for example, produce: _a => 0 should not be contextually sensitive because the relational target (n: number) => T does not use T in a covariant position. There are multiple ways we could do this

**Comment by Andarist** [comment] 2024-01-12 22:24
I don't quite understand this quote here. Doesn't `_a => 0` use `T` in a covariant position? This `0` is a potential inference source for `T`.

Regardless, I think this particular issue here can be solved. The fix wouldn't have to rely on any change to context-sensitivity. It's just that returns from context-sensitive functions are not inferred from today (whereas annotated parameters are inferred from). Inferring from such returns recursively would fix this. I plan to make a PR for it soon-ish.

https://github.com/microsoft/TypeScript/issues/47599 was already mentioned in this thread but I find this umbrella issue to not be that helpful. All of the called-out examples in the first post work today. I understand that some of the ones posted below might still not work but it's quite hard to understand at a glance what still doesn't work. At the very least that first post could be revised to include those other broken examples.

**Comment by RyanCavanaugh** [comment] 2024-01-12 23:53
> Doesn't `_a => 0` use T in a covariant position? 

Poor wording on my part. What I mean there is that because `_a`'s corresponding position in `(n: number) => T` is `n: number`, which has no occurrence of `T`, then we can be sure that treating `_a => 0` as not-context-sensitive for the purposes of inferring `T` is safe.

**Closed** 2024-01-15 01:30 UTC
Labels: Duplicate

**Comment by ShayDavidson** [comment] 2024-01-15 06:45
@Andarist should have it been closed?

**Comment by Andarist** [comment] 2024-01-15 09:09
It has been marked as a duplicate of that umbrella issue - and many issues were linked to it as its duplicates. I think this one was nice since it focused on a more specific problem. I still think this one is fixable (I fixed it locally without breaking any test cases). It was a busy weekend for me though and I'm investigating a better fix than what I have so far. I'll report back when I'm done but it might take some days. TLDR: I still plan to open a PR fixing this 😉

**Comment by ShayDavidson** [comment] 2024-01-15 09:34
Amazing, thanks for your effort!

**Comment by ShayDavidson** [comment] 2024-02-11 08:18
Hey @Andarist - did you have any chance to look into this?
