### ISSUE TITLE
Let should not be allowed as identifier in let and const declaration

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#3664] opened 2015-06-29 01:18 UTC
In ES6 spec in section in [Let and Const Declaration](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-let-and-const-declarations)

> LexicalDeclaration : LetOrConst BindingList ;
> * It is a Syntax Error if the BoundNames of BindingList contains "let".
> * It is a Syntax Error if the BoundNames of BindingList contains any duplicate entries.

currently we allow
```typescript
let let = 10;
const let = 30;
```
which should be syntax error regardless of strict-mode.
Note: below shouldn't be a syntax error unless it is in strict-mode
```typescript
let = 10
var let = 20;
```

**Comment by DanielRosenwasser** [comment] 2015-06-29 01:24
Duplicate of #3475.

**Closed by DanielRosenwasser** 2015-06-29 01:24 UTC
Labels: Bug
