### ISSUE TITLE
strictNullChecks: `undefined` is not assignable to type script

### ISSUE THREAD

**Issue by alan-agius4** [Microsoft/TypeScript#16902] opened 2017-07-03 14:03 UTC
**TypeScript Version:**  2.4.1

**Code**

```ts

if (process.env.npm_config_argv !== undefined) {
const x = JSON.parse(process.env.npm_config_argv);
....
}
```

**Expected behavior:**
no errors as i am already doing a check

**Actual behavior:**
error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

**Comment by sylvanaar** [comment] 2017-07-03 15:29
This is fixed in the current dev build.

https://github.com/Microsoft/TypeScript/issues/15796

**Comment by coderfox** [comment] 2017-08-08 04:37
No, I have got the latest dev build `2.5.0-dev.20170807` and still found the bug occurring.

```typescript
const log = (data: string) => console.log(data);
if (process.env.npm_config_argv !== undefined) {
  log(process.env.npm_config_argv);
}
```

```
temp.ts(3,7): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
```

**Comment by kitsonk** [comment] 2017-08-08 14:35
It appears that index based types are not tracked when accessed, [only explicit properties](https://www.typescriptlang.org/play/#src=%2F%2F%20%40strictNullChecks%3A%20true%0A%0Adeclare%20const%20foo%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20string%20%7C%20undefined%3B%20baz%3A%20string%20%7C%20undefined%3B%20%7D%3B%0A%0Aif%20(foo.bar)%20%7B%0A%20%20foo.bar%3B%20%2F%2F%20string%20%7C%20undefined%0A%7D%0A%0Aif%20(foo.baz)%20%7B%0A%20%20foo.baz%3B%20%2F%2F%20string%0A%7D%0A).

```ts
// @strictNullChecks: true

declare const foo: { [key: string]: string | undefined; baz: string | undefined; };

if (foo.bar) {
  foo.bar; // string | undefined
}

if (foo.baz) {
  foo.baz; // string
}
```

**Comment by RyanCavanaugh** [comment] 2017-08-08 17:09
Duplicate of #17567

**Comment by mhegazy** [comment] 2017-08-23 16:48
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-08-23 16:48 UTC
Labels: Duplicate
