### ISSUE TITLE
Please provide autocomplete for <reference> and import paths

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#188] opened 2014-07-22 09:57 UTC
Hi,

Visual Studio (2013 Ultimate) provides intellisense for the src attribute for script elements, by reading the file system and displaying available files or folders.

![Image](http://www.imageurlhost.com/images/igi4eydgq04p74llpu7e.png)

It will be quite useful if similar functionality can be provided for `<reference>` and import statements:

```typescript

 <reference path="foo/    <--- here

import foo = require('foo/   <--- and here

```

**Comment by DanielRosenwasser** [comment] 2015-04-20 05:14
:+1:

**Comment by basarat** [comment] 2015-04-20 05:48
@NoelAbrahams btw atom-typescript will complete your references : https://github.com/TypeStrong/atom-typescript#relative-paths 

and even autocomplete external module "name" and "./path"s :rose:

**Comment by DanielRosenwasser** [comment] 2015-04-20 06:44
I don't know whether @ahmad-farid has actually gotten the chance to start on this, but @basarat, is this functionality something you think you could potentially contribute to TypeScript itself, or is it more tightly coupled to atom-typescript?

**Comment by basarat** [comment] 2015-04-20 07:01
> is it more tightly coupled to atom-typescript

Tightly coupled in that I do *poor* tokenization to detect these :
https://github.com/TypeStrong/atom-typescript/blob/d5fb4707b989f15d3be8d57cfa28d88af50b4702/lib/main/atom/typescriptGrammar.ts#L68-L76


The code to get these results is a bit simpler

* relative paths for reference / imports : https://github.com/TypeStrong/atom-typescript/blob/d5fb4707b989f15d3be8d57cfa28d88af50b4702/lib/main/lang/projectService.ts#L865-L871
* external modules names lookup : I actually asked and got this simple function : https://github.com/Microsoft/TypeScript/issues/2593#issuecomment-89130039

Doesn't have to be tightly coupled. But that's just how I wrote it as a TypeScript consumer and there can't be a copy paste PR. 

If someone were to PR this they would do the *am I in a reference comment/import string?* detection on `getCompletionInfo` and then do the lookups there. 

Also more possible hoops : https://github.com/Microsoft/TypeScript/pull/2173#issuecomment-89347414

**Comment by gautamsi** [comment] 2015-04-23 17:36
Can you not drag and drop for <reference> that seems far easier.

for import autocomplete I would suggest having another feature like "Copy Import Reference" in solution explorer right click on file and  then paste this in file which would write like 'import fileName = require("../dir/filename");'. This should keep track of relative paths and file name casing.

if someone can guide me where should I look for it in this source, I can try to add on.

**Comment by danquirk** [comment] 2015-04-23 18:46
The Visual Studio related code you would need to modify to make changes like this aren't open source at the moment.

We actually had drag and drop /// reference generation at some point but it's highly undiscoverable and doesn't scale very well (do you really want to drag and drop 5+ items from disparate parts of your solution in folders that may be closed in solution explorer?).

In any case, those sorts of interactions would be nice but it should also be easier to do in a keyboard focused workflow which autocomplete would help with.

**Comment by alexeagle** [comment] 2015-10-07 23:23
we have so many modules that walking the filesystem is not practical, and some of them are generated external module names, not files. So we would like to run a periodic indexing, and then somehow provide a list of these to the language services (eg. an RPC, or a file we stage on local disk, etc.)

**Comment by olmobrutall** [comment] 2016-02-06 10:58
+1 having auto complete on import will be awesome.

**Comment by billti** [comment] 2016-02-21 00:05
Still seeing a lot of requests for this, especially as now with VSCode and Salsa this is effectively a regression (i.e. they used to give completions on `require` for modules). I believe some non-Microsoft editors also provide support for this in TypeScript/JavaScript already. We should consider pulling this in (ping @mhegazy ).

**Comment by atifsyedali** [comment] 2016-03-02 16:46
Honestly, this is the only reason why I have to keep using Webstorm, which has built custom handlers for auto complete imports and references. And not just auto-complete, but auto-fixes as well.

We have around 25k lines of Typescript atm and it would be really nice if this feature can be pushed in so all other IDEs can adopt it.

**Comment by frederikschubert** [comment] 2016-03-09 07:12
We also need this feature. This is one of the biggest drawbacks coming from a Java world where a refactoring can easily be done using eclipse or intellij.

**Comment by mikepc** [comment] 2016-04-18 16:51
I would like to chime in here, while auto import completion is very helpful and nice to work with, I would like to point out that this feature is one of the reasons that web storm is less than optimal. Scanning node_modules on a continuous basis creates a significant memory and processing overhead that would slow down VSCode quite a bit I think.

In short -- I would love this feature, but not at the cost of the awesome speed of VSCode. As a lightweight editor, I expect to have speed, power, and flexibility at the cost of convenience. A slow IDE has a higher total cost of ownership due to it chugging constantly creating delays where a lighter-weight editor let's you burn through at a continuously uninterrupted pace.

**Comment by danquirk** [comment] 2016-04-18 19:19
@mikepc curiou whether you've used other implementations like https://packagecontrol.io/packages/AutoFileName and how you find its perf for the projects that WebStorm is struggling on.

**Comment by frederikschubert** [comment] 2016-04-18 19:36
I think that you can have a sophisticated algorithm for import completion that does not suffer from the performance problems you describe. One optimization would be to use the exclude field in the tsconfig to exclude files and folders from the autocompletion index. Now only project file paths will autocomplete. If someone imports a module from a dependency then typescript knows where this dependency is located. So the folder of the imported dependency gets also included in the index. The removal could be managed via reference counters for each dependency module.

**Comment by mikepc** [comment] 2016-04-18 20:03
I haven't any knowledge of the inner workings of the various methods of
package traversal, and if indeed it is possible to include it with only a
minor performance hit I would completely love having it added. I enjoy
using VSCode. I just want to continue to enjoy using it.

**Comment by rolandoldengarm** [comment] 2016-05-09 07:07
After reading this topic, I'm still not sure this will be implemented in VS Code? It's just annoying to do all of this manually every time.

**Comment by caseyhoward** [comment] 2016-05-09 16:52
This is by far my biggest time waster when working with typescript. If it can autocomplete my class name, it should be able to make sure there is an import statement for it. I end up taking an educated guess about the path and then adding "../" to it and waiting to see if the red swiggly goes away and repeating until it does.

It would also be nice to be able to "optimize imports" and automatically remove unused imports.

**Comment by fxck** [comment] 2016-05-17 15:48
Yes please, this is such a pain the in arse.

**Comment by daslicht** [comment] 2016-06-15 13:48
any news on this ?

**Comment by mhegazy** [comment] 2016-06-15 16:44
> any news on this ?

working on it. but nothing to report.

**Comment by Ciantic** [comment] 2016-06-22 16:24
Has there been agreement how this should work for imports?

I imagine this would be a nice user experience: in VS Code if I hit Ctrl+T (Type to search symbols project wide), and choose a symbol it would allow me to somehow generate import statement for it.

Unrelated, some reason the project wide symbol listin does not show me exported variables, e.g. `export let globalStyles = {}` is not in project wide Ctrl+T but it appears within file symbol listing.

**Comment by caseyhoward** [comment] 2016-06-22 16:32
@Ciantic That sounds good. I would rather have it when using Intellisense it automatically imports things that it autocompletes that aren't in scope. I would also like the option to clean up unused imports or either further functionality for sorting them. Another thing that would be nice is something like if you delete the last usage of something imported, the import statement gets removed.

**Comment by Sammons** [comment] 2016-07-04 23:28
I built this to stopgap the problem for myself https://marketplace.visualstudio.com/items?itemName=Sammons.ts-import-assistance, code is here: https://github.com/Sammons/ts-import-assistance. It is not super intelligent but it does what I need. Essentially I found no easy way to see which symbols were missing in the current document - so this is a command you can execute to search for and import the symbol you have highlighted.

**Comment by Taytay** [comment] 2016-08-22 17:20
I also came across and used this VS Code Plugin to help in the meantime: 
https://marketplace.visualstudio.com/items?itemName=steoates.autoimport

It helped _tremendously_ when I was switching a project from namespaces (internal modules) to external modules.

**Comment by rolandoldengarm** [comment] 2016-08-22 22:03
@Taytay Thanks, tried it, but it's causing my VS Code to hang.. Maybe my app is too big, but it's useless to me.

**Comment by Taytay** [comment] 2016-08-22 22:44
Oh dang @rolandoldengarm. Understood. (For what it's worth, I've found the author to be responsive in issues in case you want to pursue it.)

**Comment by buehler** [comment] 2016-08-23 05:16
@Taytay Thanks for the info, but I made my own extension ;-) currently I'm rewriting the logic to make it faster. I'm not using regex to parse through the files (like many others do), but use the typescript compiler to generate the AST of the source.
If you're interested, you'll find it here: https://marketplace.visualstudio.com/items?itemName=rbbit.typescript-hero

**Comment by iRoachie** [comment] 2016-08-25 03:39
@buehler This works great! Had no problems as yet. Definitely much faster than typing it all out.

**Closed** 2016-09-06 20:22 UTC
Labels: Accepting PRs, API, Effort: Moderate, Suggestion, Visual Studio

**Comment by Anjmao** [comment] 2016-10-17 09:57
I found very good solution for vscode https://github.com/buehler/typescript-hero

**Comment by aleksey-bykov** [comment] 2016-11-09 00:07
please what is the status of it? roadmap has it checked, but the nightly build doesn't show it

**Comment by mhegazy** [comment] 2016-11-09 00:20
how are you using the nightly build?

**Comment by daslicht** [comment] 2016-11-09 05:06
@mhegazy http://rostacik.net/2015/09/04/using-typescriptnext-nightly-package-dont-rely-on-save-dev-to-be-up-to-date/

**Comment by aleksey-bykov** [comment] 2016-11-09 15:14
@mhegazy i am using VSCode with the 
```
    "typescript.tsdk": "./node_modules/typescript/lib",
```
in the `.vscode/settings.json` pointing to the nightly build npm package (latest just updated)

there is no autocomplete for the module paths for imports

![image](https://cloud.githubusercontent.com/assets/937933/20143010/285047a6-a665-11e6-88b9-f572830d6794.png)


as you can see the autocomplete only shows an already seen text token not a name of a file on disc

**Comment by vlechemin** [comment] 2017-05-08 20:02
It works with relative paths, but not with "absolute paths" (combination of baseUrl and paths).
Any solution or work around to this problem?
Thanks
