### ISSUE TITLE
`string | undefined` not properly inferred as `string`

### ISSUE THREAD

**Issue by pickypg** [microsoft/TypeScript#46766] opened 2021-11-10 23:10 UTC
# Bug Report

Typescript complains that a variable may still be `undefined` after implicitly verifying that it is not `undefined` through a series of simple `if` statements.

### 🔎 Search Terms

`undefined` `implicit` `infer` `inferred`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `undefined`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.4#code/MYewdgzgLgBAJgUwGYEswLgZSgJzQcwEYYBeGACgA8B+ALhmjzHwBoYBPOh3AgSnsYFSAPhgBvAFAwYKJBQCElGADJlMee17ip0mAHo9MAEYgoACxgBDHAhgBXSAljkQOGAgC2AByiad0myg7HDAYAHJPH3YwgG4dAF93ABsIW1kKTW1dfUN2GQgGJyswOBglAH0PS3Zy41tUqH8YQODQ9jjpRIQU20lsgzL8wthLEo4hsFNhppaQso6YeIl4uIlQSFhEVHQsHmYAJlIKGgE91g4uQWZ+biZ8ESyZOXJFFTUNLT7dAZNzKxt7I5nK53N5fLwZk5WuFIr5YglkqkngpMl9pAMlCgCg1iqU8liYJNYA1IUE5pQFl0eo8AlC5u0EstVutoPBkGgMNg7gBmI5US5nNicU53G5Xe4kURfdIvJSqdSopo-UwWay2Bw4lxuWF+bKzUIRMHRSmItLPRX9XJDHGjUoVKo1OrTPV0tom7pItE5QYEm1jfEFInO3T6waWbFnSlMiRrcCsrYc3Z3ADqKHMAHk3GR+SKCEKBaLc8wHtLnq8AD7lhWfJWGcBpAoaopa0FRCEuskGnXwzqm5HkC3fK2+oq2n2BqYkjvQhm9j29Wvj4a48YEoNTkOu+aMlYxgDae4cCZ2bCP7JPMKNYQAumxDyVzxg2GFos-oreYHuwpQwm-f+F3zvb9-zPbYn3CH9r2vAA6JBXAAUUsYAzHIcg90oIU2AQSgvAQYAoAwa8tElR4WVgAA3SwkjsBBiDIY9OTOQgqCFXgFjImBKOohBDnox8kwIfYWI4NidA4riaN5PiwIE5huWEzRVmkFkQCSBBoKSEB8HIAADBjZKIcgABIxEoeI2BM9h4mImATIk2jEj3bDcPwjB6BM5y8II0oSF8ziqJowh4mvHTROUuNVPUzTtL0-iuUE4zTPM2yxCsmy7ICnjHM81y4HcsQcu80g-Ps-ZgtC9iIrUjStN0-T4rkxKzIs1LrKODLuO5bKcK8tyUsKjBirIeyupC0TrKAA)

I included four simple examples: three that use `&&` and fail to infer `x` (one with a workaround cast), and one that uses `||` and properly infers it.

### 💻 Code

```ts
const definedString1 = (x?: string, y?: string): string => {
  if (!x && !y) {
    // both are unset (or empty)
    return 'empty';
  } else if (y) {
    // y is set and x _may_ be set
    return y;
  } else {
    // x is set and y is not set
    return x; // <- error: Type 'string | undefined' is not assignable to type 'string'.
  }
};
```

### 🙁 Actual behavior

`x` is not inferred as a `string`

### 🙂 Expected behavior

`x` to be inferred as a `string`

**Comment by andrewbranch** [comment] 2021-11-11 01:11
I’m sure there’s a duplicate of this somewhere, but finding it will likely be harder than explaining it. When trying to get the narrowed type of `x`, we only look at what happens to `x`. What you’re asking for is for us to realize that the narrowed type of `x` also depends on what happens to `y`. This would be incredibly complex and expensive. Put another way, putting on the fuzzy goggles of the control flow analyzer when looking at `return x`, it looks something like this:

```ts
const definedString1 = (x?: string, y?: string): string => {
  if (!x && someOtherCondition()) {
    return 'empty';
  } else if (notRelevantToX()) {
    return y;
  } else {
    // How did we get here? `!x` could have been false *or* `someOtherCondition()` could have been false,
    // and then `notRelevantToX()` must have been false. None of these things lets us narrow `x`.
    return x;
  }
};
```

To get beyond this would likely require a huge rewrite of the control flow analyzer, and doing it performantly would be a huge challenge.

**Comment by pickypg** [comment] 2021-11-11 20:29
That makes sense. I just didn't see the error listed anywhere and figured maybe there was some magic that could be done (or, what I was really paranoid about: my logic was wrong).

Perhaps this could be added to the FAQ?

This particular example can also be reworked by thinking of it in reverse:

```ts
const definedString4 = (x?: string, y?: string): string => {
  if (y) {
    // y is set, x _may_ be set
    return y;
  } else if (x) {
    // y is not set, x is set
    return x;
  }

  // neither are set
  return 'empty';
};
```

**Closed** 2024-02-24 00:20 UTC
Labels: Design Limitation
