### ISSUE TITLE
Spreading possibly undefined variable results in empty object type union

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#18000] opened 2017-08-24 08:02 UTC
**TypeScript Version:**  2.5.1
**Code**

```ts
function foo(a: {[key: string]: string}, b?: {[key: string]: string}) {
    a = {...b, ...a};
}
```

**Expected behavior:**
No Error

**Actual behavior:**
```
Type '{} | { [x: string]: string; }' is not assignable to type '{ [key: string]: string; }'.
  Type '{}' is not assignable to type '{ [key: string]: string; }'.
    Index signature is missing in type '{}'.
```

**Comment by kitsonk** [comment] 2017-08-24 08:17
Just to note it works without error in [playground](http://www.typescriptlang.org/play/#src=const%20a%20%3D%20%7B%20a%3A%20'foo'%20%7D%3B%0Aconst%20b%20%3D%20undefined%3B%0A%0Aconst%20c%20%3D%20%7B%20...b%2C%20...a%20%7D%3B%0A%0Aconsole.log(c)%3B%0A).  Feels like some sort of regression.

**Comment by ajafff** [comment] 2017-08-24 08:49
I tested 2.4.2, 2.5.0 and 2.5.1. All of them produce this error.
So this must be a regression somewhere between 2.4.0 and 2.4.2

**Comment by jambonrose** [comment] 2017-09-12 15:32
I'm new to TypeScript, but enjoying it immensely - Thank you!

I believe I've just run into the same problem with typescript 2.5.2 .

```typescript
export interface IFormAction {
  type: FormActions // an enum not shown here
}
export interface IFormState {
  [formName: string]: {
    [fieldName: string]: string
  }
}
export interface IFormReducer {
  (state?: IFormState, action?: IFormAction): IFormState
}
export const reducer: IFormReducer = (
  state, action = { type: FormActions.none }
) => {
  const defaultState: IFormState = {}
  return {
    ...defaultState,
    ...state,
  }
}
```

```console
src/forms/reducer.ts(42,14): error TS2322: Type '(state: IFormState | undefined, action?: IFormAction | undefined) => {} | { [x: string]: { [field...' is not assignable to type 'IFormReducer'.
  Type '{} | { [x: string]: { [fieldName: string]: string; }; }' is not assignable to type 'IFormState'.
    Type '{}' is not assignable to type 'IFormState'.
      Index signature is missing in type '{}'.
```

As noted by @ajafff , this seems to be related to object spreads, as removing them removes the error.
```typescript
export const reducer: IFormReducer = (
  state, action = { type: FormActions.none }
) => {
  const defaultState: IFormState = {}
  return defaultState // compiles no problem
}
```

Note that explicitly adding `| {}` onto the relevant type appears to provide a workaround.

```typescript
export interface IFormReducer {
  (state?: IFormState, action?: IFormAction): IFormState | {}
}
// reducer uses spread as before, but compiles without issue
```

Hope this is helpful.

**Comment by jambonrose** [comment] 2017-09-12 16:28
I believe that #16694 and #17849 reference the same issue.

**Comment by mhegazy** [comment] 2017-10-09 20:52
Duplicate of #16694

**Closed by mhegazy** 2017-10-09 20:52 UTC
Labels: Bug
