### ISSUE TITLE
some suggestions about emitDecoratorMetadata

### ISSUE THREAD

**Issue by berbar** [microsoft/TypeScript#34560] opened 2019-10-18 09:56 UTC
**TypeScript Version:**  3.7.0-dev.20191009

**Search Terms:** 

It sets that **'emitDecoratorMetadata'** is true in the 'tsconfig.json'.

If the classes depend on one another, It will occur exception.

**Code**

```ts
function TestReflect()
{
    return function( target: any, methodName?: string ): any
    {
    }
}

class Apple
{
    // Need Banana
    @TestReflect()
    public Some( banana: Banana )
    {
    }
}

@TestReflect()
class Banana
{
    // Need Apple
    public constructor( apple: Apple )
    {
    }
}
```

**Expected behavior:**
```js
function TestReflect() {
    return function (target, methodName) {
    };
}
class Apple {
    Some(banana) {
    }
}
__decorate([
    TestReflect(),
    __metadata("design:type", Function),
    // __metadata("design:paramtypes", [Banana]),

    // i wish there is another new option to emit metadata like this
    // add a function '()=>Banana' into metadata
    __metadata("design:paramtypes:delay", [ ()=>Banana ] ),
    // or this
    // with more type informations
    __metadata("design:paramtypes:new", [ { GenericTypeDefinition: ()=>Banana, GenericArguments: [ () => Number ] }]),

    __metadata("design:returntype", void 0)
], Apple.prototype, "Some", null);
let Banana = class Banana {
    constructor(apple) {
    }
};
Banana = __decorate([
    TestReflect(),
    __metadata("design:paramtypes", [Apple])
], Banana);
```

**Actual behavior:**
```js
function TestReflect() {
    return function (target, methodName) {
    };
}
class Apple {
    Some(banana) {
    }
}
__decorate([
    TestReflect(),
    __metadata("design:type", Function),
    // it will occur exception here.
    // Uncaught ReferenceError: Banana is not defined.
    __metadata("design:paramtypes", [Banana]),
    __metadata("design:returntype", void 0)
], Apple.prototype, "Some", null);
let Banana = class Banana {
    constructor(apple) {
    }
};
Banana = __decorate([
    TestReflect(),
    __metadata("design:paramtypes", [Apple])
], Banana);
```

**Playground Link:**  

**Related Issues:**

**Comment by berbar** [comment] 2019-10-18 10:01
```js
    // option to emit the name of parameters
    __metadata("design:paramnames", [ "banana" ] ),
```

**Comment by MartinJohns** [comment] 2019-10-18 12:56
Looks like a duplicate of #27519.

**Closed** 2019-11-02 18:00 UTC
Labels: Duplicate
