### ISSUE TITLE
4.7.0 Node-ESM: Cannot find module 'react/jsx-dev-runtime' or its corresponding type declarations.

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#48632] opened 2022-04-10 07:08 UTC
# Bug Report

```
src/index.tsx:1:11 - error TS2307: Cannot find module 'react/jsx-dev-runtime' or its corresponding type declarations.

1 const a = <a></a>
```

### 🔎 Search Terms

`react/jsx-dev-runtime`

### 🕗 Version & Regression Information

I'm using 4.7.0-beta

### 💻 Code

> package.json

```json
{
  "type": "module",
  "dependencies": {
    "@types/react": "18",
    "typescript": "4.7.0-beta"
  }
}
```

> tsconfig.json

```jsonc
{
    "compilerOptions": {
        // "module": "NodeNext",
        "moduleResolution": "NodeNext",
        "jsx": "react-jsxdev",
        "skipLibCheck": true
    },
    "include": ["./src"]
}
```

```src/index.tsx
const a = <a></a>
```

> npx tsc -p .

### 🙁 Actual behavior

```
src/index.tsx:1:11 - error TS2307: Cannot find module 'react/jsx-dev-runtime' or its corresponding type declarations.
```

### 🙂 Expected behavior

No error

As you can see, https://cdn.jsdelivr.net/npm/@types/react@18.0.1/package.json there is no `"exports": { ... }` or `"type": "module"` in the package.json of `@types/react`, therefore, TypeScript should use old resolution in this dependency

**Comment by Manish3323** [comment] 2022-04-10 07:58
+1 to this.

in my tsconfig.json 
```json
"compilerOptions": {
    ...
    "module": "nodenext",
    "moduleResolution": "nodenext",
    "target": "esnext",
    ...
}
```
doesn't work.

changing moduleResolution to "node" fixs the issue as it doesn't raise the `Cannot find module '@rollup/plugin-node-resolve' or its corresponding type declarations.`
Resetting to node from nodenext isn't correct imo. pls correct me if i'm wrong.


My use case is this: 
To use `dynamic import()` in a vscode plugin. (it imports a module from type: "module" package).

**Comment by Jack-Works** [comment] 2022-04-10 11:15
@Manish3323 if you `changing moduleResolution to "node"`, you're actually closing the 4.7.0 Node ESM support.

**Comment by Manish3323** [comment] 2022-04-10 12:29
> @Manish3323 if you `changing moduleResolution to "node"`, you're actually closing the 4.7.0 Node ESM support.

Thanks, i understood. yes resetting to node from `nodenext` isn't correct.

**Comment by weswigham** [comment] 2022-04-11 23:33
Should be fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59838 . react17 on DT never got an export map added because react 17's export map didn't (at least originally) work with the new transform anyway - now that react 18 has dropped with an export map that actually exposes the `./jsx-runtime` related extensionless entrypoints, the DT types for 18 need that same export map structure.

**Comment by Jack-Works** [comment] 2022-04-12 03:31
hmm, but why TypeScript is performing `NodeNext` resolution on the `@types/react` package?  I think it should be based on the `package.json` of the dependency, otherwise, it requires all dependency to support the export map in their package.json.

**Comment by schmannie** [comment] 2022-04-12 06:02
+1 to this issue as well

I was about to post another issue as I couldn't find it with `esnext top level await imports types TS7016`, until I searched for `dynamic imports types`.

I'm building a front-end application using React, React DOM, TypeScript, and TSX -- and I'm unable to get type definitions to resolve for either of the React packages as well. The package this is happening in is an ESM package (with `"type": "module"` in `package.json`), which in turn is inside of an NPM workspace as `@cai/client` in `./packages/client`.

I'm using `react` and `react-dom` both at `>=18.0.0` -- same with my `@types/react` and `@types/react-dom` -- and my TypeScript is the latest available nightly `4.7.0-dev.20220408`.

NOTE: Visual Studio Code is fetching the types correctly, as `alt`+`click` takes me to the correct type definitions at `../../node_modules`, in my npm root -- above all of the other workspaces. `tsc` however doesn't.

---

<details>
  <summary>tsconfig.json</summary>

  ```json
  {
    "compilerOptions": {
      "lib": [
        "dom",
        "esnext"
      ],
      "module": "esnext",
      "moduleResolution": "nodenext",
      "target": "esnext",
      "allowJs": true,
      "esModuleInterop": true,
      "isolatedModules": true,
      "forceConsistentCasingInFileNames": true,
      "skipLibCheck": true,
      "jsx": "react-jsx",
      "strict": true,
      "sourceMap": true,
      "outDir": "./dist/esm",
      "paths": {
        "@cai/lib": [
          "../cai/lib/dist/esm"
        ],
      }
    },
    "include": [
      "src/**/*"
    ],
    "exclude": [
      "node_modules",
      "public",
      "dist"
    ]
  }
  ```
</details>


<details>
  <summary>index.tsx</summary>

  ```ts
  const React = await import('react');
  const { createRoot } = await import('react-dom/client');
  ```

</details>

<details>
  <summary>package.json</summary>

  ```json
  {
    "type": "module",
    "dependencies": {
      "react": "^18.0.0",
      "react-dom": "^18.0.0"
    },
    "devDependencies": {
      "@types/react": "^18.0.1",
      "@types/react-dom": "^18.0.0",
      "typescript": "^4.7.0-dev.20220408"
    }
  }
  ```

</details>

---

```
src/index.tsx:2:37 - error TS7016: Could not find a declaration file for module 'react-dom/client'. 'C:/Production/Programming/JavaScript/cai/node_modules/react-dom/client.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-dom` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-dom/client';`

2 const { createRoot } = await import('react-dom/client');
                                      ~~~~~~~~~~~~~~~~~~

src/index.tsx:17:3 - error TS7016: Could not find a declaration file for module 'react/jsx-runtime'. 'C:/Production/Programming/JavaScript/cai/node_modules/react/jsx-runtime.js' implicitly has an 'any' type.
  If the 'react' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react'

 17   <React.StrictMode>
      ~~~~~~~~~~~~~~~~~~
 18     <SocketsContext.Provider value={sockets}>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 20     </SocketsContext.Provider>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 21   </React.StrictMode>
    ~~~~~~~~~~~~~~~~~~~~~
```

**Comment by weswigham** [comment] 2022-04-12 11:08
`@types/react-dom`, meanwhile, has a PR outstanding to add explicit exports to it, to allow extensionless imports in esm, too.

**Comment by weswigham** [comment] 2022-04-12 20:32
I've confirmed the OP's issue is fixed with the latest DT publish of `@types/react`~

**Closed by weswigham** 2022-04-12 20:32 UTC
Labels: Needs Investigation
