### ISSUE TITLE
cannot match function signature with optional argument

### ISSUE THREAD

**Issue by jamesfancy** [microsoft/TypeScript#32494] opened 2019-07-20 02:37 UTC
I tried to write a `wrap` function to wrap a selector string or HTMLElement to jQuery object:

```ts
function wrap(selector: string | HTMLElement): JQuery {
    return $(selector);
}
```

There is a compiling error:

```nohighlight
test/testJQuery.ts:4:14 - error TS2345: Argument of type 'string | HTMLElement' is not assignable to parameter of type 'PlainObject<any>'.
  Type 'string' is not assignable to type 'PlainObject<any>'.

4     return $(selector);
               ~~~~~~~~


Found 1 error.
```

Two signatures of jQuery function can match a string argument or a HTMLELement argument:

```ts
$(html: string, ownerDocument_attributes?: Document | JQuery.PlainObject<any> | undefined): JQuery<HTMLElement>
``` 

This one can match a string argument and a optional argument. And another one for HTMLElement

```ts
$(element_elementArray: HTMLElement | ArrayLike<HTMLElement>): JQuery<HTMLElement>
```

So I tried to modify my `wrap` function:

```ts
function wrap2(selector: string | HTMLElement): JQuery {
    return typeof selector === "string"
        ? $(selector)
        : $(selector);
}
```

There is no error now. I am confused so that I do a experiment about union type to match the signatures with only one argument:

```ts
function warp3(selector: JQuery.PlainObject | HTMLElement): JQuery {
    return $(selector);
}
```

No error too!

So I think it's a bug about matching function signature witch has optional arguments.

**Comment by jcalz** [comment] 2019-07-20 15:43
When you create a new issue here, there is a [template](https://raw.githubusercontent.com/microsoft/TypeScript/d23d42263d1ae1a675b9c56455f1c8733282cc18/.github/ISSUE_TEMPLATE/Bug_report.md) you're supposed to fill out.   It asks you to provide self-contained code that reproduces the problem (meaning no external dependencies), along with a link to this code in [The Playground](https://www.typescriptlang.org/play/).    Since there is no such link I can't be sure of the following:

It looks like the function you're trying to call is [overloaded](https://www.typescriptlang.org/docs/handbook/functions.html#overloads), and it is a known issue that you cannot call multiple overloads of a function at once.  If so, this is a duplicate of #14107.  Good luck!

**Comment by jamesfancy** [comment] 2019-07-24 09:25
@jcalz sorry for my mistake. I hadn't care the template. Then I tryied some code in playground and was puzzled.

**TypeScript Version:**  3.5.1 (Playground Version)


**Search Terms:**

**Code**

```ts
interface PlainObject<T = any> {
  [key: string]: T;
}

interface IFun {
  <T extends Element>(selector: T | ArrayLike<T>): any;
  (selector: string): any;
  <T extends PlainObject>(selector: T): any;
}

let fun: IFun;

function main() {
  let a = "hello" as Element | string;
  // Argument of type 'string | Element' is not assignable to parameter of type 'PlainObject<any>'.
  // Type 'string' is not assignable to type 'PlainObject<any>'.
  fun(a);

  let b = "hello" as PlainObject | string;
  // No problem, WHY???
  fun(b);

  // I tried: PlainObject isn't compatible with string, vice versa. below...
  // Type 'string' is not assignable to type 'PlainObject<any>'.
  let x: PlainObject = "abcd" as string;
  // Type 'PlainObject<any>' is not assignable to type 'string'.
  let y: string = {} as PlainObject;
}

```

**Expected behavior:**

`fun(a)` should work, or `fun(b)` should not work.

**Actual behavior:**

Inconsistency between `fun(a)` and `fun(b)`

**Playground Link:** 

https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgAoBs6gPICMBWECYAPACrIC8ycIAngHzIDeAUMsgNoDWEdAXMgDOYKKADmAXUFkA3KwC+rVqEixEKAJIAxAK4gW7ZOWQQAHpBAATIcgCi6CAFsI4BgAohER8QD2UGWQAH2QAQSgoODoAGWBecgYASkFaOnkOT28iMH9BETEQcWSaenTjCnNLGzRMHAJsjy8fHIDkMmLU+SVWRzBkGH1BHX15VgGQYmBfAycsEHdEww5emipkACIAC290X3WaWwdnVz6Q-IkygHpLsKhxXRdwZF8YZDA6AAcUAHJzwuD7I5HmBvshgLYQL4+nAhEJgOIQHBcI43r5kB84JEXGpnq93l9kN8MHM8IRiCRUgxvgA6IzXNqfH5-cSg8HISHQ2HwxHIlA5N6MwnEupk0iUmlGcbuOCJUbLCB9XBrLY7PYHGok+rEAHMq43AByaI+UF8vKckv07lwsuUHHpZEFv1EElZEKhBzhCKRKP5+J+wpApOyFPoVNp8r6ZkEAaD2uo6yRCCs+xhwmdhT1DIJRNqga1YtDrvZ7phnp5PrRfsJzIlEeQAjTBXEa2YCnVMfzXVYQA

**Related Issues:** 

Maybe #14107

**Comment by jamesfancy** [comment] 2019-07-24 09:45
Strange. If I remove `ArrayLike<T>`, `fun(b)` report a error.

```ts
interface PlainObject<T = any> {
  [key: string]: T;
}

interface IFun {
  <T extends Element>(selector: T): any;  // <= removed `| ArrayLike<T>`
  (selector: string): any;
  <T extends PlainObject>(selector: T): any;
}

let fun: IFun;

function main() {
  let a = "hello" as Element | string;
  // Argument of type 'string | Element' is not assignable to parameter of type 'PlainObject<any>'.
  // Type 'string' is not assignable to type 'PlainObject<any>'.
  fun(a);

  let b = "hello" as PlainObject | string;
  // Argument of type 'string | PlainObject<any>' is not assignable to parameter of type 'PlainObject<any>'.
  // Type 'string' is not assignable to type 'PlainObject<any>'.
  fun(b);
}
```

**Comment by jack-williams** [comment] 2019-07-24 11:38
This looks to be caused by the way inference and checking works. I believe it is roughly:
1. infer a type for `T`.
2. check that the arguments satisfy the argument types when `T` is instantiated with the inference.

When doing type inference a string index type is used as an inference source for a target number index type. In this instance this means that the `any` string index type on `PlainObject` is used to infer the number index signature in `ArrayLike<T>`. When combining the inferences you get `T ~ any | string` which reduces to `any`.

After making this inference the instantiated signature is checked - this is trivially satisfied because you have:
```
(selector: any | ArrayLike<any>): any === (selector: any): any
```

The reason you get an error when removing `ArrayLike<T>` is because you no longer infer from a string index type to a number index type, and therefore you do not generate the inference candidate `any` for `T` which trivialises the signature.

Going back to your expectations: 
- `fun(a)` will not work as described by the issue in #14107.
- `fun(b)` will correctly give an error if you change your default value for `T`.
```ts
interface PlainObject<T = unknown> {
  [key: string]: T;
}
```
Using `any` in constraints is pervasive and best avoided - if possible.

**Comment by jamesfancy** [comment] 2019-07-26 05:46
Thank you, @jack-williams. 

But I am still unclear.

All of `any` string index type and `any` number index type cannot be infer to `ArrayLike<any>`, since they have not `length` property:

```ts
interface IStringIndex<T = any> { [key: string]: T; }
interface INumberIndex<T = any> { [key: number]: T; }

let obj: any;
let a: IStringIndex = obj as INumberIndex;  // OK
let b: INumberIndex = obj as IStringIndex;  // OK

// Property 'length' is missing in type 'IStringIndex<any>' but required in type 'ArrayLike<any>'.ts(2741)
let c: ArrayLike<any> = a;

// Property 'length' is missing in type 'INumberIndex<any>' but required in type 'ArrayLike<any>'.ts(2741)
let d: ArrayLike<any> = b;
```

So `PlainObject` which in my question shouldn't be inferred to `any`.

And,

`any` is not sub type of every type. (only `null`, `undefined` and `never` are, in document.)

Please watch following screenshot. 

![image](https://user-images.githubusercontent.com/3953094/61927630-100a7c80-afa8-11e9-85ee-f7a00236e2df.png)

There are two possibilities in my logic:

1) `<T extends Element>` is inferred to `<any>`, so in fact `any` can be seen as a sub type of `Element` ??

2) `b` is inferred to any as @jack-williams saied. I think it's not wirte, above. And here are some codes:

```ts
const b = "hello" as PlainObject | string;
const c: string = b;   // Not OK
const d = "hello" as any | string;
const e: string = d;  // OK
```

**Comment by jack-williams** [comment] 2019-07-26 09:37
> any is not sub type of every type. (only null, undefined and never are, in document.)

The `any` type _is_ assignable to _every_ type (except `never`).

> There are two possibilities in my logic:

The behaviour is caused by 1.

The type `T` is inferred as `any`, so we get an argument type of `any | ArrayLike<any>`. This type is simplified by the compiler to `any`, and the `any` type is assignable to `Element`, so you get no error.

**Comment by jamesfancy** [comment] 2019-07-27 03:59
I think I know what's the different between us.

> When doing type inference a string index type is used as an inference source for a target number index type. In this instance this means that the `any` string index type on `PlainObject` is used to infer the number index signature in `ArrayLike<T>`. When combining the inferences you get `T ~ any | string` which reduces to `any`.

- You think `b: PlainObject` CAN infer to `b: any`, so `(selector: T | ArrayLike<T>)` accept it.
- I think `b: PlainObject` SHOULD NOT infer to `any`.

In my opinion: 

- `{ [key: number]: any }` ⇒ `{ [key: string]: any }`, since `number` can convert to `string` exactly.
- `{ [key: string]: any}` ⇏ `{ [key: number]: any}`, since `string` CANNOT convert to `number` exactly. 
    I disagree this inference but it's true. And TSLint will warn while accessing.
    ```ts
    let x: { [key: string]: any } = { a1: "a1", a2: "a2" };
    let y: { [key: number]: any } = x;
    y[1] = "n1";
    let v1 = y["a1"];   // (no-string-literal)tslint(1)

    let z: { [key: string]: any } = y;
    let v = z[1];      // OK
    ```
    Don't care this rule now. Whatever the next rule is not true.
- `{ [key: number]: any}` ⇏ `ArrayLike<any>`, since it has NOT `length` property exactly.

**Comment by jack-williams** [comment] 2019-07-29 10:08
What I 'think' is not important and I have no opinion on this behaviour - I'm just trying to explain why you are seeing this.

This might give better results:
```ts
type UnArray<T> = T extends ArrayLike<infer U> ? U : T;

interface IFun {
  <T extends Element>(selector: UnArray<T>): any;
}
```

**Closed** 2019-07-31 18:00 UTC
Labels: Duplicate
