### ISSUE TITLE
Incorrect types within false condition

### ISSUE THREAD

**Issue by cns-solutions-admin** [microsoft/TypeScript#50194] opened 2022-08-05 09:16 UTC
# Bug Report

Typescript does not evaluate all conditions to determine actual types, if the condition is always false because of a literal "false".
Adding a "false &&" to a condition is often done during debugging.

### 🔎 Search Terms

false condition, type

### 🕗 Version & Regression Information

4.7.3, 4.7.4

### ⏯ Playground Link

none

### 💻 Code

```ts
function test(param?: string) {
  if (param) {
    return param.length;
  }
  return 0;
}

function brokenTest(param?: string) {
  if (false && param) {
    return param.length; // <= TS2532: Object is possibly 'undefined'.
  }
  return 0;
}

function workaroundTest(param?: string) {
  if (!true && param) {
    return param.length; // compiles
  }
  return 0;
}
```

### 🙁 Actual behavior

When adding a "false &&" to a condition of an if, the original condition is ignored for the type checks in the if block.

### 🙂 Expected behavior

It still compiles.

**Comment by MartinJohns** [comment] 2022-08-05 09:43
Duplicate of #26914.

**Closed** 2022-08-07 18:00 UTC
Labels: Duplicate
