### ISSUE TITLE
Missing space in documentation comment quick info

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#11341] opened 2016-10-04 01:41 UTC
Quick-info seems to be removing the space between the first two words of the second line of a documentation comment.

``` ts
/// <reference path="fourslash.ts" />

/////**
//// * Zero:
//// * It is a number.
//// */
////const zero = 0;
////
////const one = /**/zero;

verify.quickInfoAt("", "const zero: 0", "Zero:\nIt is a number.")
```

Fails with `expected 'Zero:\nItis a number.' to equal 'Zero:\nIt is a number.'`

**Comment by kpreisser** [comment] 2016-10-08 13:54
Hi,
we have the same issue in our product where we use the Monaco Editor with the TS Language Service, and created an TS declaration file that we specify as lib file:
![monaco-intellisense-space](https://cloud.githubusercontent.com/assets/13289184/19213543/f08a83ae-8d6e-11e6-921a-c9066f354be6.png)

```typescript
declare namespace codabix {
    // (...)
    class Node {
        // (...)
        /**
         * An array containing the child nodes.
         * 
         * Note: The array is live, which means changes on the underlying nodes will be reflected in this array.
         */
        readonly children: ReadonlyArray<Node>;
    }
}
```

Note, in that example it seems there are even two spaces removed ( `Note: The array is live` -> `Note:Thearray is live`).

However, the spaces are not always removed. For example, if I copy the above declaration, paste it into the editor (renaming `codabix` to `codabix2`), the spaces are shown correctly:
![monaco-intellisense-space2](https://cloud.githubusercontent.com/assets/13289184/19213566/4e906f22-8d6f-11e6-8986-73a254fb87f2.png)

Thanks!

**Comment by sandersn** [comment] 2016-11-11 22:19
Looks like a duplicate of #10987. The secret is that it only happens if the first word is "too short". See the bug and associated PR for a definition of too short.

**Closed by sandersn** 2016-11-11 22:19 UTC
Labels: Accepting PRs, Bug
