### ISSUE TITLE
Generating a String Array from a Union type

### ISSUE THREAD

**Issue by Momijiichigo** [microsoft/TypeScript#43668] opened 2021-04-14 04:49 UTC
# Suggestion
Hello!
- I suggest a syntax & feature which generates a list of strings from a Union type. 
- For some cases, script codes would be redundant when making & using a list of keys in pre-defined Map objects 
  - (ex: `SVGElementTagNameMap`)
  - see the example below.

## 🔍 Search Terms
- string array 
- list
- Union type
- `keyof`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
A syntax to generate lists of strings from Union Types.
For example (Could be different syntax):
```ts
type SVGTagName = keyof SVGElementTagNameMap  // 'altGlyph' | ... | 'use' | 'video' | 'view' | 'vkern'
const SVG_TAG_NAMES = Keys<SVGTagName>()  // ['altGlyph', ... , 'use', 'video', 'view', 'vkern']
```

## 📃 Motivating Example

When I try to judge if a string value is an SVG tag name by using an array list of SVG tag names,
I wanted to  use `keyof SVGElementTagNameMap` because I already use it in other parts of my code, 
But currently, I need to prepare whole another string list of SVG tags in my script.

Example:
```ts
type SVGTagName = keyof SVGElementTagNameMap  // using this in other parts of my code

//currently I need to put the following long list.
const SVG_TAG_NAMES = [
  'altGlyph',
  // ... long list of names
  'use',
  'video',
  'view',
  'vkern'
]

function isSVGTag(tagname: string): boolean {
  return SVG_TAG_NAMES.includes(string)
}
```
For the above case, if I could use a feature to generate a list of strings from Union type, the code would be neat and useful.

## 💻 Use Cases

With this feature, some codes would be neat and nice 😃

**Comment by MartinJohns** [comment] 2021-04-14 05:04
Duplicate of #13267.

**Closed** 2021-04-17 18:00 UTC
Labels: Duplicate
