### ISSUE TITLE
An argument type of a lambda is not inferred from a method return value in a derived c lass

### ISSUE THREAD

**Issue by dko-slapdash** [microsoft/TypeScript#31273] opened 2019-05-06 17:37 UTC
**TypeScript Version:** 
3.4.0-dev.201xxxxx

**Search Terms:**
typescript derived class return value inference

**Code**

```ts
// A pattern: derived class can provide some configuration to configure itself;
// the configuration is consumed by the Base class.
type Config<SomeVeryComplexTemplateWhichOnlyBaseAbstractionKnows> = {
    hook: (val: string) => boolean;
}

class Base {
    static getConfig(): Config<Base> { throw Error("override"); }
}

class Derive extends Base {
    static getConfig() {
        return { hook: val => !!val };
        // ^ error: Parameter 'val' implicitly has an 'any' type
    }
}
```

**Expected behavior:**
I'd expect that val has an inferred type `string`.

**Actual behavior:**
Parameter 'val' implicitly has an 'any' type

**Playground Link:**
[playground link](https://www.typescriptlang.org/play/index.html#src=type%20Config%3CSomeComplexGeneric%3E%20%3D%20%7B%0D%0A%20%20%20%20hook%3A%20(val%3A%20string)%20%3D%3E%20boolean%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Base%20%7B%0D%0A%20%20%20%20static%20getConfig()%3A%20Config%3CBase%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20throw%20Error(%22%22)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Derive%20extends%20Base%20%7B%0D%0A%20%20%20%20static%20getConfig()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%20hook%3A%20val%20%3D%3E%20!!val%20%7D%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0A%0D%0A%0D%0Aclass%20Base1%20%7B%0D%0A%20%20%20%20static%20configure(cfg%3A%20Config%3CBase%3E)%20%7B%0D%0A%20%20%20%20%20%20%20%20throw%20Error(%22%22)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Derive1%20extends%20Base1%20%7B%7D%0D%0A%0D%0ADerive1.configure(%7B%20hook%3A%20val%20%3D%3E%20!!val%20%7D)%0D%0A)

**Related Issues:**
I remember I read about something slightly close to this, but not this exact usecase.

**Motivation**
Of course we can explicitly provide the type in Derive, but imagine Config was not of a simple type, but of some very complex type which only Base class knows, how to infer. I.e. the type structure of Config could be very complex, and I don't want to inject knowledge about it to derived classes (but I want to validate the config structure though).

I know only one work-around for this behavior - switch from "returning the configuration in an overridden method" to "configure the class explicitly with a method call".

An example which works:

```ts
class Base2 {
    static configure(cfg: Config<Base>) { throw Error(""); }
}

class Derive2 extends Base2 {}
Derive2.configure({ hook: val => !!val });
// ^ val type is correctly inferred
```

But this work-around is ugly, because it forces us to configure synchronously (i.e. we can't do lazy configuration as in the top example).

**Comment by weswigham** [comment] 2019-05-08 22:13
Duplicate of #10570, kinda - intimately related, at least.

**Comment by dko-slapdash** [comment] 2019-05-09 21:46
Thanks. Wondering, is it really the only work-around for this pattern? Or there could be some better advices?

The only work-around I found to make things stateless and keep them strongly-typed is:

```tsc
class Base2 {
    static getConfig(): Config<Base> {
       throw Error("please override");
    }

    protected static configuration(cfg: Config<Base>) {
      return cfg; // no-op, just to enforce type inference
    }
}

class Derive2 extends Base2 {
    static getConfig() {
       return self.configuration({ hook: val => !!val });
       // ^ val is strongly-typed here, i.e. the type is correctly inferred
    }
}
```

**Closed** 2019-05-12 18:00 UTC
Labels: Duplicate
