### ISSUE TITLE
Incorrect types on Array.filter(n => !!n)

### ISSUE THREAD

**Issue by Fi1osof** [microsoft/TypeScript#41090] opened 2020-10-13 21:47 UTC
**TypeScript Version:**  4.0.2

**Search Terms:**
filter(), reduce()

**Code**

```ts
type MaybeValueArrayType = Array<number | undefined>;
type ValueArrayType = Array<number>;

const maybeValueArray: MaybeValueArrayType = [1,2,3, undefined];

const valueArrayType__ok = maybeValueArray.reduce((curr, next) => {
    if(next) {
        curr.push(next);
    }
    return curr;
}, [] as ValueArrayType);

const valueArrayType__OK_2: ValueArrayType = maybeValueArray as ValueArrayType;

// Realy OK???
const errorTypesArray: ValueArrayType = [
    1,2,3, 
    undefined, 
    // OK?
    null, 
    // OK too?
    {}
] as ValueArrayType;

// Why error with filter?
const valueArrayType__error: ValueArrayType = maybeValueArray.filter(n => !!n) ;
```

**Expected behavior:**
```ts
const valueArrayType__error: ValueArrayType = maybeValueArray.filter(n => !!n) ;
```
Should not return error due filter(n => !!n) returns only empty array or array with positive values, like via reduce example.

**Actual behavior:**
> Type '(number | undefined)[]' is not assignable to type 'ValueArrayType'. Type 'number | undefined' is not assignable to type 'number'. Type 'undefined' is not assignable to type 'number'.

**Playground Link:** 
https://www.typescriptlang.org/play?#code/C4TwDgpgBAsghiARhAanANgVwgQQE54IAq40AvFPoSADwB2mAtsnlAD5SZ0AmEAZgEs6EbgD4A3AChQkKGiy4CxUlApUE9JiwmTJAYwD2dAM7AojBMnnZ1IAFyxLqDDaUgSsigG0AjABoAJj8AZj9OHn4hEQBdKX0jUygANxdFag8IAH1MgwBrVXMnazSEADo8EUw9CAAKGr1MAjDhAA9gAEpVUSgAb0koAagBPhrWjt7+wamGglKwTGMAC1GINvapKYBfSYGK4Ea6KBm8KU2wr2ioOGM5VNsM9d1DEzMUhXvSbIB5AGlMgIcxQ+nkKSGc7zcVxuQLcGTiAHp4VAAEoQDAgKC-AD8OPiLygEAIBjwGWMtkBd1hKm8Oyg-iCoSgtK4vEEwm4YVpiMxPyxtIY6HQnKm3N+UGABgMfKmPW2l2utwh6VICKRAHVFhjCXhiVioAB3ATARZQQToYCEvnPRJvVzKyDZbXEilK5QgixgmHUUpmi14UZdKAAQiDdE6UiAA

**Comment by MartinJohns** [comment] 2020-10-14 05:35
Duplicate of #16069.

**Closed** 2020-10-16 18:00 UTC
Labels: Duplicate
