### ISSUE TITLE
Parameters<> does not preserve tuple names when used on a function with a destructured parameter

### ISSUE THREAD

**Issue by georeith** [microsoft/TypeScript#50726] opened 2022-09-12 14:06 UTC
# Bug Report

### 🔎 Search Terms

Parameters
Destructured
Named tuple

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about named tuples and parameters

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/LAKALgngDgpgBAeSmAlgewHYGc4F44DecWaAtjGABYoYDmAXHAEZpoA2MAhhnAL4DcoUDAAeUNACcwcAGYBXDAGNUmOJwAUMlBKxhGLdlwwAaYjEWYAJo10SatU50ZIV2AJSFewsZOnylrsya2rr6rBzcpljmVjZgdnSmRCTkVPZ8zsjo7p5CIKCQsHAACpwSnKRYAIJ4JWUVFDA6ADyFMGgyagB8guDQ8KXllQBCtYMNYE1Yrf0dzD2gQA)

### 💻 Code

```ts
type Options = { something: boolean };

export function a(first: boolean, second: string, a: Options) {}
export function b(first: boolean, second: string, { something }: Options) {}

type ParamsA = Parameters<typeof a>;
type ParamsB = Parameters<typeof b>;
```

### 🙁 Actual behavior

`ParamsA` is correctly typed as `[first: boolean, second: string, a: Options]`
`ParamsB` is typed as `[boolean, string, Options]` (loses the named tuples)

### 🙂 Expected behavior

type of `ParamsB` should have named tuples where appropriate

This is potentially linked to https://github.com/microsoft/TypeScript/issues/46493?

**Comment by fatcerberus** [comment] 2022-09-12 14:44
Looks like a straight-up duplicate of #46493, in fact.

**Closed** 2022-09-15 18:00 UTC
Labels: Duplicate
