### ISSUE TITLE
`satisfies` operator fails to recognize optional properties that are defined

### ISSUE THREAD

**Issue by UselessMnemonic** [microsoft/TypeScript#54836] opened 2023-06-29 23:36 UTC
# Bug Report

### 🔎 Search Terms

"partial"  "satisfies" "narrow"

### 🕗 Version & Regression Information

Tried on version 5.1.5

### ⏯ Playground Link

https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true#code/C4TwDgpgBAqgzhATlAvFA3gWAFBT1RCAQwBMB7AOwBsQoBLEgLijmETooHMAaHfA4uWq04ZALYQAggGNgdSswAUASlQA+KADcyDHAF8cOUJCgBZAK7AiAIyoQAPABUNaLLnwBaQqUo0oAbQBpegooAGsIEDIAMyhHAF1mRyD4-UNsaPMKWXlQ6W9gCHgkRQZmVnYuZWZi5Dd+aUpWKAoIAHda5gsrWwcABSJEOSIqe1q1Fwx6Eig9AG50-laOhEQAOlEJGTlKVCgVdSmAegAqKDWLqBOj2YXsPnxCYHNEUOXaliI5OGi6CDhYKs5ngjjdokQ6FQ4GlsEA

### 💻 Code

```ts
type User = {
    readonly id: string,
    readonly someAction: () => void
}

type UnfinishedUser = {
    id: string,
    someAction?: () => void
}

function createUser(id: string): User {
    const newUser: UnfinishedUser = { id };

    newUser.someAction = () => { /* ... */ };

    return newUser satisfies User;  // fails
}
```

### 🙁 Actual behavior

`newUser` does not satisfy `User`

### 🙂 Expected behavior

`newUser` should satisfy `User`

**Comment by jcalz** [comment] 2023-06-30 01:36
As far as I know, `existingVariable satisfies Type` has essentially no effect, so it's not surprising that `satisfies` isn't doing anything here.  I'd say `satisfies` is a red herring and the underlying issue is that assigning the `id` and `someAction` properties of `newUser` doesn't narrow `newUser` itself, and as such this is a duplicate of #42384.  If that were to be implemented then your code work start working (but you still wouldn't need `satisfies`).  For example:

```ts
// simulate #42384
function addProp<T extends object, K extends PropertyKey, V>(
    obj: T, k: K, v: V): asserts obj is T & Record<K, V> {
    Object.assign(obj, { [k]: v });
}

function createUser(id: string): User {
    const newUser: UnfinishedUser = { id };
    addProp(newUser, "someAction", () => { /* ... */ });
    return newUser satisfies User;  // okay
}

function createUser2(id: string): User {
    const newUser: UnfinishedUser = { id };
    addProp(newUser, "someAction", () => { /* ... */ });
    return newUser;  // still okay
}
```

[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgzhATlAvFA3gWAFBT1RCAQwBMB7AOwBsQoBLEgLijmETooHMAaHfA4uWq04ZALYQAggGNgdSswAUASlQA+KADcyDHAF8cOUJFgUAZhzpwAFhBLwkqDH3wNmrdl1658oiTLlKAH4lVRQNbV1sA2xDbAB6eJY6MQBXKiJgaABiABYAJgBmAA5cnDNUill5CihSEgAFRDIwAB4AFSgIAA8sihI4KDIAIwArCFluKABpLt6IfsGmlqRQaYgQKYA1NUUXPBHR5napgGtmaanNZi3lZiI4BERgQcP6Qc6AMigAJQmyRAkVqXKA7Zw+PAAeTGE2AADoHnA6JwKIpDlN0FAANqnAC6zE0UD0ygA3Po4hUqoFatJCJkIA5EIo3Cw2BxOHdYE9wfxpJRWFAKBAAO6M5gwcyWGx2RlOTEMIlkiF1EiNZpgRRC0VPKYAIj8UmqlF1UxU6gwUHiACooHC7VArUliUr+IRgKlELUtbK4JkrBYIINGSS8IkhqciCBybFsJSjTS6VlGflmUxWZ4OeLuVhlXyKALvU9xZKKFZbPZuWh5SRFfsVWqWpqRYy9QaAjUTVAzeELdbbfbHUTSXW3R6vc2niHLUlWHQqFRw5Ho0A)

**Comment by UselessMnemonic** [comment] 2023-06-30 06:28
I understand, I think what I'm looking for is more explicit type guards. Using `as` in the return statement, although subtle, better conveys the behavior I desire:

```ts
type User = {
    readonly id: string,
    readonly someAction: () => void
}

type UnfinishedUser = {
    id: string,
    someAction?: () => void
}

function createUser(id: string): User {
    const newUser: UnfinishedUser = { id };

    newUser.someAction = () => { /* ... */ };

    return newUser satisfies User as User;  // fails
}
```

This way I can assert that `newUser` does in fact satisfy `User` without `satisfies` having a  side-effect on the type itself. Still, definitely would depend on https://github.com/microsoft/TypeScript/issues/42384

**Closed** 2023-07-09 01:34 UTC
Labels: Duplicate
