### ISSUE TITLE
Inconsistency in getDocumentHighlights for import aliases

### ISSUE THREAD

**Issue by leeavital** [Microsoft/TypeScript#3688] opened 2015-06-30 22:06 UTC
For the file:

````typescript
import fs = require('fs');
import ws = fs.writeStream;
````

getDocumentHighlights will not find that the fs on line 1 is the same as the one on line 2.

But for the file:
````typescript
import fs = require('fs');
var ws = fs.writeStream;
````
 

----------------

I wrote a small program to demonstrate the problem.

````typescript
var ts = require('typescript');
var fs = require('fs');

var source = fs.readFileSync('test.ts').toString();
var sourceFile = ts.createSourceFile('test.ts', source, 1, false);

var host = {
  getCompilationSettings: function() {
      return {
          noResolve: true,
          target: ts.ScriptTarget.ES5
      };
  },
  getCurrentDirectory: function() {
    return '';
  },
  getDefaultLibFileName: function() {
    return "lib.d.ts"
  },
  getScriptFileNames: function() {
    return ['test.ts'];
  },
  getScriptIsOpen: function() {
    return true
  },
  getScriptVersion: function() {
    return "1"
  },
  getScriptSnapshot: function() {
    return {
      getLength: function() {
        return source.length;
      },
      getLineStartPositions: function () {
        return ts.computeLineStarts(source);
      },
      getText: function(start, end) {
        return source.substring(start, end);
      }
    };
  }
};

var documentRegistry = ts.createDocumentRegistry();
var languageServices = ts.createLanguageService(host, documentRegistry);

var importFS  = sourceFile.statements[0];
var highlights = languageServices.getDocumentHighlights('test.ts', importFS.name.pos + 1, ['test.ts']);
console.log(highlights[0].highlightSpans.length);
````

When `test.ts` contains the first example, it outputs 1. When `test.ts` contains the second example, it outputs 2.

**Comment by DanielRosenwasser** [comment] 2015-07-01 06:33
I assume this also means find-references and rename is also not working in this scenario.

**Comment by JKillian** [comment] 2015-08-31 17:27
There seem to be some related funny issues going on. When calling `getDocumentHighlights` on the position of the `hello` variable declaration in the following code snippet:
```typescript
// Incorrect case:

class HelloWorld {
    constructor(public name: string) { }
    sayHello() {
        return `Hello, ${this.name}!`;
    }
};

let hello = new HelloWorld("TSLint");
hello.sayHello();
```
 only the declaration is returned and not the usage on the next line. However, in the following code snippet, both uses are returned, correctly: 

```typescript
// Correct case:

class HelloWorld {
    constructor(public name: string) { }
    sayHello() {
        return `Hello, ${this.name}!`;
    }
};

if (true) {
    let hello = new HelloWorld("TSLint");
    hello.sayHello();
}
```

Also strangely, Sublime will correctly show both references in both cases. 

I've been trying to figure out the root cause but haven't been able to yet. I did notice that in the `getReferencesInNode` function the array of possible positions contains exactly the two actual positions in both the incorrect and correct case. However, there is a difference when finding the `relatedSymbol`:

```typescript
var referenceSymbol = typeChecker.getSymbolAtLocation(referenceLocation);
if (referenceSymbol) {
    var referenceSymbolDeclaration = referenceSymbol.valueDeclaration;
    var shorthandValueSymbol = typeChecker.getShorthandAssignmentValueSymbol(referenceSymbolDeclaration);
    var relatedSymbol = getRelatedSymbol(searchSymbols, referenceSymbol, referenceLocation);
    // relatedSymbol is undefined here in incorrect case, defined in the correct case
    if (relatedSymbol) {
        var referencedSymbol = getReferencedSymbol(relatedSymbol);
        referencedSymbol.references.push(getReferenceEntryFromNode(referenceLocation));
    }
    else if (!(referenceSymbol.flags & 67108864 /* Transient */) && searchSymbols.indexOf(shorthandValueSymbol) >= 0) {
        var referencedSymbol = getReferencedSymbol(shorthandValueSymbol);
        referencedSymbol.references.push(getReferenceEntryFromNode(referenceSymbolDeclaration.name));
    }
}
```


(Related to https://github.com/palantir/tslint/issues/570)

**Comment by DanielRosenwasser** [comment] 2015-08-31 17:39
@JKillian I'm not able to reproduce the error:

![image](https://cloud.githubusercontent.com/assets/972891/9585553/8fbd7be8-4fcc-11e5-87bd-26bec7d41256.png)

it's likely unrelated to the issue filed here, so if you're still seeing it, can you file a separate bug?

**Comment by JKillian** [comment] 2015-08-31 17:52
@DanielRosenwasser Created a new issue from my previous comment with a few details added: https://github.com/Microsoft/TypeScript/issues/4560

**Comment by JKillian** [comment] 2015-09-11 15:19
@leeavital The issue comes from this code:

```typescript
getScriptSnapshot: function() {
    return {
      getLength: function() {
        return source.length;
      },
      getLineStartPositions: function () {
        return ts.computeLineStarts(source);
      },
      getText: function(start, end) {
        return source.substring(start, end);
      }
    };
```

`getScriptSnapshot` can request snapshots for files other than `source`, so only returning code form `source` causes things to happen incorrectly.

**Comment by JKillian** [comment] 2015-09-14 15:41
My apologies, I think this is still a bug. I had assumed that our incorrect usage of the language services was the issue, but it doesn't seem like that's the case. FindReferences in Sublime doesn't mark both references. In addition, this fourslash test fails:

```typescript
/// <reference path='fourslash.ts' />

////import [|fs|] = require('fs');
////import ws = [|fs|].writeStream;

let ranges = test.ranges()
for (let range of ranges) {
    goTo.position(range.start);

    verify.renameLocations(/*findInStrings*/ false, /*findInComments*/ false);
}
```

**Comment by adidahiya** [comment] 2016-02-08 23:01
@DanielRosenwasser Any updates on this? Is the fix fairly involved?

**Comment by DanielRosenwasser** [comment] 2016-03-01 23:48
I'm honestly not sure, I'll try to find some time to work on this soon.

**Comment by DanielRosenwasser** [comment] 2016-03-01 23:52
I wonder if this is related to #4970.

**Comment by DanielRosenwasser** [comment] 2016-03-02 00:22
I think I might have a fix in a little bit actually. :smile:

**Comment by mhegazy** [comment] 2016-06-06 20:44
@JKillian is this still an issue? i believe it has been fixed in latest.

**Comment by JKillian** [comment] 2016-06-06 21:59
Verified that this is fixed in the latest nightly, thanks! Feel free to close this issue

**Comment by mhegazy** [comment] 2016-06-06 22:07
thanks!

**Closed by mhegazy** 2016-06-06 22:07 UTC
Labels: API, Bug
