### ISSUE TITLE
Generic type of varargs is inferred from only the first parameter

### ISSUE THREAD

**Issue by gomain** [microsoft/TypeScript#51273] opened 2022-10-22 17:17 UTC
# Bug Report

### 🔎 Search Terms

* varargs
* generic

##### This is a crash

No

##### This changed between versions ______ and _______

All version in the playground error. Versions 3.62 and earlier don't give meaningful error, i.e. just **Errors in code**.

##### This is the behavior in every version I tried, and I reviewed the FAQ for entries about ________

Yes. And there is no FAQ on this subject.

##### I was unable to test this on prior versions because _______

All version in the playground have been tested. Including Nightly.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20221022#code/C4TwDgpgBAglC8UDeUCGAuNA7EUC+A3AFCiRQBCCyUARpqjvsUQCYQDGANqgE7TsB7LAGdgaTDGJsuvfkNG1M5ZgDMArlnbAAlkKjBUAawgA1XjB4BzYQHkVAcQhYIPbewA8MAEr2AfAAoAOmDeawkeHlQQTx9fAEpkIigoQREBTghAzgFLf1DhOOI8IgB6EqgXHgEeABoobSwVF2FYHygVKoBbKCFOXGAAC2gVbR4FMAFhYW1gIRIjU3MrWwcnFzc8uppC0vKaNTEBQygAdyGsKGEwPlQWeeMzHgtrO0dnV3Yg4IBtVC2AXUKQA)

### 💻 Code

```ts
type A = { a: any };
type B = { b: any };

declare const a: A;
declare const b: B;

function takeVarArgsOfGeneric<ARG>(...args: Array<ARG>) {
  console.log(args);
}
// error, infers ARG from only the first position
takeVarArgsOfGeneric(a, b);
// but ok when spread
takeVarArgsOfGeneric(...[a, b]);
```

### 🙁 Actual behavior

Type error:
```
Argument of type 'B' is not assignable to parameter of type 'A'.
  Property 'a' is missing in type 'B' but required in type 'A'.
```
Inferred type:
```ts
function takeVarArgsOfGeneric<A>(...args: A[]): void
```

### 🙂 Expected behavior

Inferred type:
```ts
function takeVarArgsOfGeneric<A | B>(...args: (A | B)[]): void
```

**Comment by MartinJohns** [comment] 2022-10-22 20:50
Pretty sure it's a duplicate of #37673.

**Comment by gomain** [comment] 2022-10-24 04:22
Discussion in #37673 concludes that this is _working as intended_. Argument being that it is the same behaviour as a non-varargs variant.
```ts
// same issue when positioned
function takeMultipleGeneric<ARG>(first: ARG, second: ARG) {
  console.log(...arguments);
}
takeMultipleGeneric(a, b);
```
But doesn't go further into explaining why this would be the desired behaviour, if there is one it should make it into the FAQ.

Here I suggest it is not the desired behaviour both in the varags/rest and the multiple positions cases.

This is not exactly the same case though. When using the _rest_ syntax, the programmer gets to explicitly name and type the _rest_ parameter as an `Array` of something and would expect the type system to resolve types in the same way arrays are resolved. I.e.
```ts
function takeArrayOfGeneric<ARG>(args: Array<ARG>) { }
```
In the case of positioned parameters, this would be expecting typescript implicitly resolves the type of `arguments` which by specification is truly dynamic and rightfully have type being the equivalence of  `ArrayLike<any>`.

It should, however, be expected that the named positional parameters types are resolved as unions.

Is this a case of lacking unification #30134?

**Comment by RyanCavanaugh** [comment] 2022-10-25 16:39
Inference collects some number of candidates and then decides what to do with those candidates. In the case where 2 or more candidates are collected but no common type is found, it falls back to one of them and tries to process the call anyway. In the case where 1 candidate is collected, that's obviously the type argument's value.

So the question is whether a spreaded array should act like the code that collects 2 arguments or 1, and you can make a consistency-based argument *in either direction*:
```ts
// Direct call: Collects two candidates (A and B).
// Union is not automatically inferred from two disparate candidates (intended)
takeVarArgsOfGeneric(a, b);

// At issue: middle case behaves as the one above, or the one below?
takeVarArgsOfGeneric(...[a, b]);

// Indirected type: (A | B)[]
const arr = [a, b];
// Only one candidate is collected (A | B)
takeVarArgsOfGeneric(...arr);
// is same as
takeVarArgsOfGeneric<A | B>(...arr);
```

>  if there is one it should make it into the FAQ.

This isn't really frequently asked FWIW

**Comment by gomain** [comment] 2022-10-26 04:13
@RyanCavanaugh Thanks for explaining.

To recap. When you declare a function as
```ts
function takeTwoParametersOfType<T>(first: T, second: T) { ... }
```
you want the type system to enforce that `first` and `second` are indeed the same type, and fail otherwise. Had they resolved as unions, things like
```ts
function max<T>(first: T, second: T): T { ... }
```
would be useless.

On the other hand, if you declare
```ts
function takeSomeParametersOfType<T>(...params: Array<T>) { ... }
```
you get _same type enforcement_ when called using positioned variant (multiple candidates provided).
```ts
takeSomeParametersOfType(a, b); // Argument of type 'B' is not assignable to parameter of type 'A'
```
but don't when called using the spread variant as the type of the array (the single candidate) is resolved prior to resolving `T`.
```ts
takeSomeParametersOfType(...[a, b]); // ok, T is A | B
```

**Comment by TFTomSun** [comment] 2023-01-21 10:32
I have a similar use case, I try to infer a generic argument from an generic container array.

[TS Playground](
https://www.typescriptlang.org/play?ts=4.9.4&ssl=11&ssc=15&pln=11&pc=16#code/MYGwhgzhAEBqYgK4FMDCB7AdgFzAS02QCcAeAFQD4BvAKGmgAdEAjEPYaYLCbIxYbOiLQAFE1btoANwQoAXGQCUtevTrQAvjS00AJslBgiyTt2zQwcuLLRZcBYiUyIAts2IUA3HoPhjpzB5oZit4JFscfEJSHiICAHMvGhoAM0RMATwsaFwAa2R4IgBBIniIAHkUgHFkaPYSIoAlKooRADoOozKrEqIwAE8SMJQMSIdSJpaKRWgVaGNsRCJMC1KIAG0ABgBdNplw7y0AeiPoYiIhABpoAhTiGEnoFIuXaCwQfpyACxMUvCIggx0FA8IJMDQ8gUjCUypUanVgCIwNdmIpvCdgohzOhctAAO4-FYQBjGMC6CFgfKFGEVaq1YjsdoddbI4LbNFAA)

Is it somehow possible to solve that:
`
class ValueContainer<T>{
  public constructor (public value:T){
    
  }
}

declare const a: ValueContainer<number>;
declare const b: ValueContainer<string>;

function takeVarArgsOfGeneric<ARG>(...args: Array<ValueContainer<ARG>>) {
  return args[0].value;
}
// error, infers ARG from only the first possiton
takeVarArgsOfGeneric(a, b);
// but ok when spread
takeVarArgsOfGeneric(...[a, b]);
`

**Comment by RyanCavanaugh** [comment] 2023-01-24 00:42
Yes
```ts
type Helper1<T> = T extends { [n: number]: infer X } ? Helper2<X> : never;
type Helper2<T> = T extends ValueContainer<infer U> ? U : never;
function takeVarArgsOfGeneric<ARG>(...args: ARG & Array<ValueContainer<any>>): Helper1<ARG> {
```

**Closed** 2023-06-08 03:48 UTC
Labels: Not a Defect
