### ISSUE TITLE
Incorrect event property in Window

### ISSUE THREAD

**Issue by Avol-V** [Microsoft/TypeScript#8809] opened 2016-05-25 13:26 UTC
Property `event` in global object Window is [non-standard](https://developer.mozilla.org/en-US/docs/Web/API/Window/event) and must be removed from lib.d.ts because of possible errors in browsers that follow the standard (Mozilla Firefox, for example).

It's also an ability for potential wrong behavior in code (example below).

**TypeScript Version:** 

1.7.5 / current Git code.

**Code**

```ts
function someHandler( event: Event, additionalData: number ): void
{
	console.log( event, additionalData );
}

const onClick = (): void => someHandler( event, 1 ); // <-- forgot the argument `event`

element.addEventListener( 'click', onClick );
```

**Expected behavior:**

Error — `event` is not defined.

**Actual behavior:** 

Silence but code may work incorrectly and didn't work in some browsers.

**Comment by kitsonk** [comment] 2016-05-25 14:11
Essentially a duplicate of #1351 which deals with a lack of errors with referencing an accidental global versus a locally scoped variable or parameter.

"must be removed" is subjective, as it is non-standard, but it is present in many environments.

**Comment by mhegazy** [comment] 2016-05-25 17:03
closing in favor of #1351

**Closed by mhegazy** 2016-05-25 17:03 UTC
