### ISSUE TITLE
unintended never type after a null check

### ISSUE THREAD

**Issue by boopathi** [microsoft/TypeScript#44380] opened 2021-06-02 10:57 UTC
# Bug Report

Some code flows like functions passed to array methods are not considered as immediately invoked and any assignment to a variable inside the array methods are not captured in the outer scope. 

For example,

### 🔎 Search Terms

array methods, never, null check, assignment, variable assignment

### 🕗 Version & Regression Information

4.3.2

- This changed between versions **4.1.3** and **4.3.2**

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABBAhgZwKYEYAUBKRAbwFgAoRRAGwykQFsUAHALkQFkmAeNKAJxjABzADSIe-IQD5EAH0RgQlSogC88xZQDcZMhQDaAXQB0DRjnyrphek1XyMAd3ZMLAXzzbSuxDGCIcpogAhGoKSgQk5BSIAPQxNow+aPYAbhi83hQQCGhw1EaUcIIBTEaCNDgARLl0NAAWAoKVeB7ermTtXqSgkLAIyOgYAEwWkRTUtKasHIzcfI2i4o3ScmHKoRqe3uYEKlYJdmCOzmYE7vhbUb7+gSHq4USZsfGBMMkzT9lgufmFxaZlCrVOC1KANITNVpRTquIA)

### 💻 Code

```ts
let map: Map<string, string> | null = null;

[1].map(() => { map = new Map() });

if (map != null) {
  // map is never
  console.log(map.get("something"));
}
```

### 🙁 Actual behavior

In the above code, after the null check, the variable `map` is expected to be of type `Map<string,string>`, but the assignment inside the `Array.map` function isn't captured and is considered as `never`.

```
Property 'get' does not exist on type 'never'.(2339)
```

### 🙂 Expected behavior

The variable `map` is of the type `Map<string, string>`

**Comment by whzx5byb** [comment] 2021-06-02 11:02
Duplicate of https://github.com/microsoft/TypeScript/issues/44025

**Comment by fatcerberus** [comment] 2021-06-02 13:08
Root cause is #9998.

**Closed** 2021-06-04 18:00 UTC
Labels: Duplicate
