### ISSUE TITLE
Mapped tupples with generic constraints

### ISSUE THREAD

**Issue by npenin** [microsoft/TypeScript#55223] opened 2023-08-01 03:56 UTC
# Bug Report

### 🔎 Search Terms

mapped tupples generic constraints

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4#code/FAUwHgDg9gTgLgAgJYDs4hgMwIYGMQIDu2AzgLZwCeEIAPACoLjooAmJRpF1IAkiiTjYU+BgD4xwAN7AEchChCEAFKiRwk2ADYB5CAC4EylAFcyAIwwIAPgnNIA5qjgBKANoBdF4foBuWfJUNIamFhj+AL7AoJCwiM4YOPic5EF8AkIidIzMIGwcxKk8-ILCovQS0gFycFB6AMJQrCAkyt5GoZYwNnaOzu4e-vIIaYaF3DTiwFEx0PAjPAgQ2DDYZCDoMCQMTGAs7CkT6aVZtMKUYp5iCAC8CDl7eQeKAG4YnggA-AogbzAf+mq912+w4blQmCs9AAjB4vgg3DC3AByNLIjxwwHDB6ghEQqHQgA0yBQkO69AATHDvoiifcqQgsfIcU8wfjyXT2fTiVz6ABmakImHEykigWMoEs-J40kEnmy8kU+Vk+585VQgAsgtpIqVqpFWol2JBrJlKuFJPNet5astmvV5IArNqLaL9fcNSLnUbmSbpeCFfdOYG3TaHR7w-RHZGAGwuulu-kGr0iuM+uRSg4B83Bq2R228z12p2xyMAdnjurFyfu0fuMZFFfT9yBviAA)

### 💻 Code

```ts

export interface wasmtype<T extends wasmtypeInstance<T>>
{
    new(initialOp: (number | bigint)[]): T;
    type: number;
}

export interface wasmtypeInstance<T extends wasmtypeInstance<T>>
{
    toOpCodes(): (number | bigint)[];
    type: wasmtype<T>
}

export type parameters<T extends wasmtypeInstance<any>[]> = T extends never[] ? never[] :
    T extends [infer T1] ? [T1['type']] :
    T extends [infer T1, infer T2] ? [T1, T2] :
    T extends [infer T1, infer T2, infer T3] ? [T1, T2, T3] :
    T extends [infer T1, infer T2, infer T3, infer T4] ? [T1, T2, T3, T4] :
    T extends [infer T1, infer T2, infer T3, infer T4, infer T5] ? [T1, T2, T3, T4, T5] :
    T extends [infer T1, infer T2, infer T3, infer T4, infer T5, infer T6] ? [T1, T2, T3, T4, T5, T6] :
    T extends [infer T1, infer T2, infer T3, infer T4, infer T5, infer T6, infer T7] ? [T1, T2, T3, T4, T5, T6, T7] :
    T
    ;
```

### 🙁 Actual behavior

The compiler complains that T1 is not a wasmtypeInstance. 

### 🙂 Expected behavior

Since T1 extends wasmtypeInstance<any> (based on the generic constraint), T1['type'] should be an allowed structure as well. Ideally, it would return wasmtype<T1> because of the inference, but at least a wasmtype<any> as specified in the constraint is a must.

**Comment by npenin** [comment] 2023-08-01 04:04
a somehow connected usecase would be if your replace parameters with the following definition:
```ts
export type parameters<T extends wasmtypeInstance<any>[]> = T extends never[] ? never[] :
    T extends [infer T1] ? T1 extends wasmtypeInstance<T1> ? [T1['type']] : never :
    T extends [infer T1, infer T2] ? [T1, T2] :
    T extends [infer T1, infer T2, infer T3] ? [T1, T2, T3] :
    T extends [infer T1, infer T2, infer T3, infer T4] ? [T1, T2, T3, T4] :
    T extends [infer T1, infer T2, infer T3, infer T4, infer T5] ? [T1, T2, T3, T4, T5] :
    T extends [infer T1, infer T2, infer T3, infer T4, infer T5, infer T6] ? [T1, T2, T3, T4, T5, T6] :
    T extends [infer T1, infer T2, infer T3, infer T4, infer T5, infer T6, infer T7] ? [T1, T2, T3, T4, T5, T6, T7] :
    T
    ;
```

in the condition on T1 , the compiler is complaining about T1 not being a wasmtypeInstance, while it is part of the condition I am trying to validate.

**Comment by MartinJohns** [comment] 2023-08-01 06:27
Duplicate of #51108.

**Closed** 2023-08-01 06:55 UTC
