### ISSUE TITLE
Allow asynchronous methods in LanguageService class

### ISSUE THREAD

**Issue by manuth** [microsoft/TypeScript#40788] opened 2020-09-26 11:54 UTC
## Search Terms
  - `Language Service Plugin`
  - `Async`
  - `Asynchronous`
  - `getSemanticDiagnostics`

## Suggestion
Currenctly it doesn't seem to be possible to provide diagnostics in an asynchronous manner.
I'm working on a language service plugin which, sadly, depends on a linter which only provides asynchronous API. Cause of the LanguageService class only allowing synchronous calls (for example `getSemanticDiagnostics`) there is no way for me to provide diagnostics.

## Use Cases
This might be necessary if you'd like to provide diagnostics while having a linter which only provides asynchronous API.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-09-26 12:18
Duplicate of #29361?

**Comment by manuth** [comment] 2020-09-26 12:22
Thanks for the digging 😄
Though the `LanguageServiceHost` seems to be a different story than the `LanguageService` these two issues definitely seem to be connected to each other

**Comment by RyanCavanaugh** [comment] 2020-09-28 18:21
👍

**Closed by RyanCavanaugh** 2020-09-28 18:21 UTC
Labels: Duplicate
