### ISSUE TITLE
Add generic to AggregateError

### ISSUE THREAD

**Issue by wolfy1339** [microsoft/TypeScript#58457] opened 2024-05-07 15:20 UTC
### 🔍 Search Terms

aggregate error, generic

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Allow passing the type of the `AggregateError#errors` property via a type generic.

simply changing the declaration to something like so:
```ts
interface AggregateError<T = any> extends Error {
    errors: T[];
}
```

### 📃 Motivating Example

This new generic will allow you to type the `AggregateError#errors` property

### 💻 Use Cases

1. What do you want to use this for? Passing the type of the `errors` property of `AggregateError`
2. What shortcomings exist with current approaches? The `errors` property is typed as `any`
3. What workarounds are you using in the meantime? Using the external [`aggregate-error`](https://github.com/sindresorhus/aggregate-error) dependency

**Comment by MartinJohns** [comment] 2024-05-07 15:37
Duplicate of #54063.

**Closed** 2024-05-11 01:27 UTC
Labels: Duplicate
