### ISSUE TITLE
Suggestion: generic default

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#9321] opened 2016-06-23 01:05 UTC
Currently when using a generic and the type cannot be inferred, it fallbacks to `{}`. It would be nice if we can specify it. e.g.:

```ts
interface generic<T extends Anything default any> { ... }
interface generic<T extends Anything default {}> { ... }
interface generic<T extends Anything default SubClassOfAnything> { ... }
```

🌷 

EDIT: I recall there is an issue that complaint about it fallback to `<{}>` but I can't find it.

**Comment by mhegazy** [comment] 2016-06-23 01:30
Duplicate of https://github.com/Microsoft/TypeScript/issues/2175

**Closed by mhegazy** 2016-06-23 01:30 UTC
