### ISSUE TITLE
Allow function declarations to be typed

### ISSUE THREAD

**Issue by hdodov** [microsoft/TypeScript#39419] opened 2020-07-04 08:13 UTC
## Search Terms

set function declaration type

## Suggestion

To define a function type, we currently have to use function expressions:

```ts
type Fun<T> = (value: T) => T

export let foo: Fun<number> = function (value) {
	return value
}
```

My suggestion is to make that possible for function declarations as well:

```ts
export function foo: Fun<number> (value) {
	return value
}
```

## Use Cases

As a superset of JavaScript, TypeScript shouldn't enforce us to change the actual runtime logic in order to apply types. In this case, you're forced to use a function expression when a function declaration is fine.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by jcalz** [comment] 2020-07-04 21:03
Duplicate of #22063

**Closed** 2020-07-10 18:00 UTC
Labels: Duplicate
