### ISSUE TITLE
Can't access inner class from outer class

### ISSUE THREAD

**Issue by wheelerlaw** [Microsoft/TypeScript#14155] opened 2017-02-17 22:11 UTC
**TypeScript Version:**  2.0.8 

**Code**

```ts
export class Outer {
    outerProp: any;

    static builder = () => new Outer.Inner();

    private static Inner = class Inner {
        constructor() {}

        // Some setters go here

        build() {
            return new Inner(this);  // This line errors because of mismatched function parameters.
        }
    };

    protected constructor(builder: Outer.Inner) { //Errors on this line: TS2503:Cannot find namespace 'Outer'

    }
}

let anInstanceOfOuter = Outer.builder().build();
```

**Expected behavior:**
It shouldn't error. 
**Actual behavior:**
It's throwing a compiler error. There is a workaround, where I declare a namespace with the same name as `Outer` below the class, and put the inner class in there. But that won't work for 2 reasons:
- The inner class can't refer to protected outer class properties. 
- I can't export the outer class without having to export the inner class as well.

**Comment by mhegazy** [comment] 2017-02-18 00:56
Duplicate of https://github.com/Microsoft/TypeScript/issues/10017

**Closed by mhegazy** 2017-02-18 00:56 UTC
