### ISSUE TITLE
allow narrowing by subproperty

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#20127] opened 2017-11-18 09:15 UTC
```typescript
interface XA {
    isThis: true;
}
interface XB {
    isThis: false;
}
interface A {
    x: XA;
    a: string;
}
interface B {
    x: XB;
    b: number;
}
type C = A | B;
declare var c: C;
c.x.isThis === true ? c.a : c.b // <-- expected to work
```

**Comment by calebsander** [comment] 2017-11-18 18:01
I think you're expecting the compiler to be more intelligent than it is. The fact that `c.x.isThis === true` or `c.x.isThis !== true` is only used by the compiler to narrow the type of `c.x` to `XA` or `XB`. (You can see this by writing `c.x.isThis ? c.x : c.x` and hovering over the two `c.x` instances.) For whatever reason, the compiler doesn't go one step further and use this fact to narrow the type of `c`. You could just cast explicitly: `c.x.isThis ? (c as A).a : (c as B).b`

**Comment by aleksey-bykov** [comment] 2017-11-18 18:07
i understand what you are saying, i do want the compiler to be more intelligent and go one step further

**Comment by gcnew** [comment] 2017-11-18 21:41
The compiler currently does only "forward" narrowing i.e. the immediate parent and its children. This  issue requires narrowing of all parents of a discriminator property.

About two years ago I implemented it as part of my union/intersection PR. The change wasn't very complex but I'd expect the team to be reluctant to implement it, because it will have negative performance implications.

**Comment by mhegazy** [comment] 2017-11-21 07:54
The narrowing of the type of a variable through narrowing of one of its properties is tracked by https://github.com/Microsoft/TypeScript/issues/18758. the issue there as @gcnew noted is creating new types that were not there before.. narrowing has thus far been removing types from the possible type set for a value; but doing this for the parent/container value requires manufacturing some new types in the process, e.g.:

```ts
var x: { a: number | string };
if (typeof x.a === "number" ) {
   x // x should be `{ a: number }
}
```

this is rather a simple example, but demonstrates the issue. the current behavior `x.a`'s possible types are `number | string`, narrowing removes `string`, and leaves only `number.`. where as narrowing the type of `x` involves creating a new type that was not there before.

**Comment by mhegazy** [comment] 2017-11-21 07:55
Duplicate of https://github.com/Microsoft/TypeScript/issues/18758

**Closed** 2017-12-05 18:27 UTC
Labels: Duplicate
