### ISSUE TITLE
Wrong inlay hints for parameter names with `"typescript.inlayHints.parameterNames.enabled": "literals"`

### ISSUE THREAD

**Issue by segevfiner** [microsoft/TypeScript#55882] opened 2023-09-26 20:40 UTC
### 🔎 Search Terms

inlay hints, parameter names, VS Code, tsserver

### 🕗 Version & Regression Information

- This changed between versions 5.1.6 and 5.2.2

### ⏯ Playground Link

https://github.com/segevfiner/typescript-parameter-inlay-hints-issue

### 💻 Code

```ts
setTimeout(() => {
    console.log("Hello, World!");
}, 1000);
```

### 🙁 Actual behavior

The parameter hint for the second parameter shows as `callback:` in 5.2.2, which is wrong.

### 🙂 Expected behavior

It shows as `ms:`, which is correct.

### Additional information about the issue

VS Code 1.82.2.

This doesn't happen in 5.1.6. Which can be seen by switching the TypeScript version in the project to 5.1.6, and setting VS Code to use the workspace version.

**Comment by IllusionMH** [comment] 2023-09-26 22:33
Duplicate of #55866

Has almost same title as this one

**Closed** 2023-09-27 06:55 UTC
