### ISSUE TITLE
Can't use auto import when node_modules are named "node_modules"

### ISSUE THREAD

**Issue by lukaszurbanski** [microsoft/TypeScript#29629] opened 2019-01-17 10:53 UTC
- VSCode Version: 1.30.2 (1.30.2)
- OS Version: macOS Mojave 10.14.2

Steps to Reproduce:

1. Create new angular project using CLI
2. Install dependencies
3. Try to import module (eg. HttpClientModule)

Then no auto import is available. BUT!! if I change name from `node_modules/` to `node_modules2/ `then everything is fine. I've tried few "fixes" with no success.
Screens 
<img width="1309" alt="screenshot 2019-01-17 at 11 50 46" src="https://user-images.githubusercontent.com/4116552/51313612-4510a200-1a4e-11e9-8cbf-e134fe78dcbe.png">
<img width="1289" alt="screenshot 2019-01-17 at 11 50 07" src="https://user-images.githubusercontent.com/4116552/51313621-4c37b000-1a4e-11e9-8f17-e6c8c0ca2044.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-01-29 01:57
I confirmed this using TS 3.3-rc and a new angular app created from the CLI.

`HttpClientModule` is defined in `@angular/common/http`. Manually adding this import works but I don't see where the `http.d.ts` typings are exported in the `@angular/common` package's main `index.d.ts`

**Comment by aleclarson** [comment] 2019-01-29 23:40
Related: https://github.com/Microsoft/vscode/issues/67505

**Comment by aleclarson** [comment] 2019-01-30 00:56
Probably related: #29039

**Comment by andrewbranch** [comment] 2019-08-23 17:49
The reason renaming the node_modules folder works is that the default value of `exclude` in tsconfig.json includes `"node_modules"`. The practical effect of this is that TypeScript doesn’t know about anything inside node_modules until you import something in there—this is by design. (See #28773.)

It’s possible that’s what’s happening, but there’s not enough information here to know for sure yet. To test that theory, can you try adding an `import "@angular/common/http";` anywhere in your project? If, after that, auto-import for `HttpClientModule` works, then this is working as intended. If it doesn’t, then this is a bug.

**Comment by andrewbranch** [comment] 2019-10-01 21:56
> To test that theory, can you try adding an import "@angular/common/http"; anywhere in your project? If, after that, auto-import for HttpClientModule works, then this is working as intended. If it doesn’t, then this is a bug.

I just did this myself, and the auto-import for `HttpClientModule` shows up, which makes this expected behavior, and a duplicate of #30033 and #28773.

I will note, though, that despite our current stance that this is a “working as intended,” we are paying attention to the fact that users are frequently confused by this behavior and/or request that the behavior change, and I’m brainstorming ways to make the experience better. Just can’t promise anything specific yet.

**Closed** 2019-10-04 18:00 UTC
Labels: Domain: Completion Lists, Duplicate, Working as Intended

**Comment by Vinn55** [comment] 2022-09-17 17:07
I have the same issue with HttpClientModule. Just see no suggestion. https://github.com/microsoft/TypeScript/issues/29629#issuecomment-524404152
adding an import "@angular/common/http"; anywhere in my project, after that, auto-import for HttpClientModule works. I can't find what need to do.  For diff IDE only in VScode, we have this problem (auto-import suggestion, webstorm runs file indexation and maybe need update this process in VScode).
