### ISSUE TITLE
noUnusedLocals: errors on variables that are used

### ISSUE THREAD

**Issue by DickvdBrink** [Microsoft/TypeScript#9412] opened 2016-06-29 08:10 UTC
Version: 2.0.0-dev.20160629

Compile below code with --noUnused Locals
`tsc --noUnusedLocals test.ts`

```
class test {
    public testMethod() {
        var that = this;

        setTimeout(() => {
            that.testMethod();
        }, 100);
    }
}
```

**Expected**
No errors but got one for `test.ts(5,13): error TS6133: 'that' is declared but never used.`

**Comment by mhegazy** [comment] 2016-06-29 08:12
duplicate of https://github.com/Microsoft/TypeScript/issues/9403

**Closed by mhegazy** 2016-06-29 08:12 UTC
