### ISSUE TITLE
not "export" classes not visible inside single module + JS generation issue

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#2069] opened 2015-02-18 23:25 UTC
I have 2 .ts files:

A.ts
<code>
module nx {
class A { }
}
</code>

B.ts
<code>
module nx {
export class B { temp = new A(); }
}
</code>

In class B, I get error that class A is not known. I would assume that A should be known as it's in the same module as B.
Adding "export" to class A fixes the issue, but I don't wish class A to be visible externally.

The second issue I see is in generated JS file (note I have option Combine JavaScript output into single file set).

For above example (2 separate .ts files) I see:
<code>
var nx;
(function (nx) {
var A = ...
var nx;
(function (nx) {
var B = ...
</code>

When I put class A and B in single .ts file result looks better:
<code>
var nx;
(function (nx) {
var A = ...
var B = ...
</code>

I think tsc should generate 2'nd  result in both cases.

Thanks!

**Comment by mhegazy** [comment] 2015-03-24 17:15
This is by design. unless a declaration is marked as exported it will only be visible within the enclosing module declaration.

**Closed by mhegazy** 2015-03-24 17:15 UTC
