### ISSUE TITLE
No noUnusedLocals warning for recursive arrow function

### ISSUE THREAD

**Issue by Profesor08** [microsoft/TypeScript#57790] opened 2024-03-15 11:18 UTC
### 🔎 Search Terms

typescript recursive arrow function warning

### 🕗 Version & Regression Information

Version 5.3.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&useDefineForClassFields=true&allowUnreachableCode=true&allowUnusedLabels=true&downlevelIteration=true&noLib=true&noUnusedLocals=true&noUnusedParameters=true&experimentalDecorators=true&emitDecoratorMetadata=true&target=99&exactOptionalPropertyTypes=true&noFallthroughCasesInSwitch=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true&isolatedModules=true&inlineSourceMap=false&inlineSources=false&allowSyntheticDefaultImports=true&useUnknownInCatchVariables=true&allowArbitraryExtensions=true&resolvePackageJsonImports=true&resolvePackageJsonExports=true&allowImportingTsExtensions=false&allowUmdGlobalAccess=false&suppressImplicitAnyIndexErrors=true&importHelpers=true#code/N4KABGDGD2B2DOAXMAzWBGMBeMAKAlAFxgBG00ANgKYCGs2AfGKBBAE5WICub9a6BANzgwAX2EiUXWJEQBLOKlgAmAsTKVa9Fqw7deS1fmERxISdNkK+sAMxrS5anWYj2nHvURsuVE2OFRECA

### 💻 Code

```ts
{
  const fn1 = (): boolean => {
    return fn1();
  };

  function fn2(): boolean {
    return fn2();
  };

  function fn3(): boolean {
    return true;
  };
}

```

### 🙁 Actual behavior

fn1 has recursion, and this function is not used, but there is no warning. fn2, fn3 has warning.

### 🙂 Expected behavior

fn1, fn2, fn3 to have wanings

**Comment by MartinJohns** [comment] 2024-03-15 11:34
Duplicate of #45360. Used search terms: `recursive unused in:title`

**Closed** 2024-03-15 16:25 UTC
Labels: Duplicate
