### ISSUE TITLE
Private(set) keyword

### ISSUE THREAD

**Issue by FilipeBeck** [microsoft/TypeScript#46029] opened 2021-09-23 17:33 UTC
# Suggestion

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

A keyword (`private(set)`, maybe) to allow fields that are public for reading and private for writing.

Workaround:

```typescript
class MyClass {
  public readonly privateSetProp: number

  someMethod() {
    (this.privateSetProp as any) = 10
  }
}
```

**Comment by a-tarasyuk** [comment] 2021-09-23 17:37
Do you mean https://github.com/microsoft/TypeScript/pull/45021 / https://github.com/microsoft/TypeScript/issues/1534?

**Comment by MartinJohns** [comment] 2021-09-23 18:24
Duplicate of #37487.

**Comment by FilipeBeck** [comment] 2021-09-23 21:25
I used `private set`. Closing

**Closed** 2021-09-23 21:25 UTC
Labels: Duplicate
