### ISSUE TITLE
Module Not Found - Compiler does not lookup "index.js"

### ISSUE THREAD

**Issue by lusbuab** [Microsoft/TypeScript#13617] opened 2017-01-21 18:31 UTC
**TypeScript Version:**  2.1.5, next

**Code**

```ts
import { shallow } from 'enzyme'
```

**Expected behavior:**

Compiler does not throw a TS2307 module not found error.

**Actual behavior:**

Compiler does not find module "enzyme" because enzyme's package.json has `"main": "build"`. Apparently the compiler does not lookup `build/index.js`.

Manually changing enzyme's "main" to `build/index.js` resolves this compiler error.

There already was a similar issue with a resulting PR that partially solved the problem: #12748

**Comment by mhegazy** [comment] 2017-01-21 22:43
duplicate of https://github.com/Microsoft/TypeScript/issues/12198

**Closed** 2017-04-21 16:41 UTC
Labels: Duplicate
