### ISSUE TITLE
Type inference for partially specified generics

### ISSUE THREAD

**Issue by stof** [microsoft/TypeScript#40020] opened 2020-08-12 15:43 UTC
## Search Terms

generic inference

## Suggestion

When a function has several generic types and only one is specified, it seems like the following ones are assigned their default types rather than applying inference. This means that needing to specify the first type forces to specify them all to avoid loosing the benefits of the more precise inferred type for the second generic type.

It would be great that when specifying only partially the generic types for a call, the remaining ones could still benefit from type inference rather than always using their base type.

## Use Cases

The use case comes from https://github.com/fregante/delegate-it/pull/19 where I try to make the library nicer for type inference, but an expected usage for TS users would be to explicitly specify the first generic type (for which there is no smart inference possible) and let type inference do its work for the second one.

## Examples

I'm reproducing here the types from the PR above:

```ts
export type EventType = keyof GlobalEventHandlersEventMap;
type GlobalEvent = Event;
namespace delegate {
	export type Subscription = {
		destroy: VoidFunction;
	};
	export type EventHandler<TEvent extends GlobalEvent = GlobalEvent, TElement extends Element = Element> = (event: Event<TEvent, TElement>) => void;
	export type Event<TEvent extends GlobalEvent = GlobalEvent, TElement extends Element = Element> = TEvent & {
		delegateTarget: TElement;
	};
}

function delegate<TElement extends Element = Element, TEventType extends EventType = EventType>(
	base: EventTarget | Document | ArrayLike<Element> | string,
	selector: string,
	type: EventType,
	callback: delegate.EventHandler<TEvent, TElement>,
	type: TEventType,
	callback: delegate.EventHandler<GlobalEventHandlersEventMap[TEventType], TElement>,
	options?: boolean | AddEventListenerOptions
): delegate.Subscription {
     // [redacted]
}
export default delegate;
```

Here is 3 different usages:

```ts
import delegate from 'delegate-it';

delegate(document, '.js-comment-field', 'keydown', event => {
  const field = event.delegateTarget;
  const key = event.keyCode;
})

delegate<HTMLTextareaElement>(document, '.js-comment-field', 'keydown', event => {
  const field = event.delegateTarget;
  const key = event.keyCode;
})

delegate<HTMLTextareaElement, 'keydown'>(document, '.js-comment-field', 'keydown', event => {
  const field = event.delegateTarget;
  const key = event.keyCode;
})
```

In the first case, the event is properly inferred as using `KeyboardEvent` thanks to the `'keydown'` event type. That's where type inference shines. But we get `Element` as the type for the `field` variable because type inference cannot infer a better type there.
That's where the maintainer of the library would write code using the second syntax, where the generic type for the delegate target is specified explicitly. But doing that looses the inference of `KeyboardEvent` based on the `'keydown'` event type, going back to `KeyboardEvent | UIEvent | Event | AnimationEvent | MouseEvent | ...` for the event. This happens because it keeps using `keyof GlobalEventHandlersEventMap` as the `TEventType` generic rather than inferring it based on the `'keydown'` argument.
This would force writing the third ugly syntax (repeating `'keydown'`) to get both a precise type for `field` and for `event`

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

I'm not sure whether changing this would break existing Typescript code.

**Comment by awerlogus** [comment] 2020-08-12 19:11
duplicate: https://github.com/microsoft/TypeScript/issues/38499

**Comment by tadhgmister** [comment] 2020-08-12 19:46
technically this is a duplicate of #26242 since that is the suggestion and #38499 is just a misunderstanding that ends up linking to #26242

**Comment by stof** [comment] 2020-08-13 08:05
indeed. I missed that one in the search.

**Closed** 2020-08-23 18:00 UTC
Labels: Duplicate
