### ISSUE TITLE
Readonly array `includes` should take valid primitive type

### ISSUE THREAD

**Issue by tatemz** [microsoft/TypeScript#46035] opened 2021-09-23 21:30 UTC
# Bug Report

⚠️ I am not certain this is a bug, but it definitely feels unexpected. Feel free to re-categorize this as a question

When I define a ReadOnlyArray using the `as const` keyword, I would expect that I should be able to call `includes` with an appropriate primitive value.

### 🔎 Search Terms

readonly array includes
readonly array type guard

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAsgTQPoEkAqBROBlGBeGAbQHIAxEEYgGhmICEBDAJ2IF0YGIZRIoBuAFACoATwAOAU3giUUCQFt8MUZJAAzeMnRZshMAFd5AIwlNWggT2gwAlhDgy5iggApmAcwBcMfWADWYCAA7mAAlN4etlwOsgr4AHwCMMnK4hLqHEzu+HgEAETQTDZg7nkwAGTlmqiYOAB0xcAANvoAJhIQblmhfEA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

```ts
const MY_ITEMS = ['Foo', 'Bar'] as const;

type MyItem = typeof MY_ITEMS[number];

const isMyItem = (arg: unknown): arg is MyItem =>
    typeof arg === "string" && MY_ITEMS.includes(arg);
```

### 🙁 Actual behavior

```txt
Argument of type 'string' is not assignable to parameter of type '"Foo" | "Bar"'.(2345)
(parameter) arg: string
```

### 🙂 Expected behavior

I would expect that `.includes()` should take any primitive based on the underlying array type

**Comment by MartinJohns** [comment] 2021-09-23 21:36
Duplicate of #26255 / #14520.

**Closed** 2021-09-26 18:00 UTC
Labels: Duplicate
