### ISSUE TITLE
TS6133 triggered even when the 'using' keyword is used

### ISSUE THREAD

**Issue by fearthecowboy** [microsoft/TypeScript#55564] opened 2023-08-29 17:56 UTC
### 🔎 Search Terms

6133
TS6133
using 6133
using TS6133

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because `using` is a new feature.

### ⏯ Playground Link

https://www.typescriptlang.org/play?noUnusedLocals=true&target=9#code/BQZQngtgRg9gNgAgIYGdkDswEoB0ATASxQAcYUBTBBAfmoF4Fxp5gAiJ2OfI0i1rANwAoUJE7I0STLlRh0AYwAiPMpVoMOLdmPg5ZC5SVX9hQ+XFRoAYjBgIA3kKpV5MdCgAuAJwCu8jzBewFgOTs4ubijw5DhwMADmwADkAMJe5EgeBOjxSYJhVAC+BQgA2qLMiKgY2NxGFAC6waHhEe7RsQlshrzZ8SYlxcVCAGY+ClluCBBI2c0tCAD0iwjoMB6UHgAWmQgEHnto8elg5HgIMD4HwFLn5F5egWgA7lvk6KswALTjPhR4Xzi8iQcDQRAQ7yQUDgZwQWDCfz6CHSUR8XnklAY6HIzwQNhgwWEwxmc0EQA

### 💻 Code

```ts
(Symbol as any).dispose  ??= Symbol("Symbol.dispose");
(Symbol as any).asyncDispose ??= Symbol("Symbol.asyncDispose");

class Foo {
    constructor() {
      console.log('Creating');
    }
    [(Symbol as any).dispose]() {
      console.log("Disposing");
    }
}

function main()  {
  // note that it is greyed out (and errors when no-unused-locals is enabled )
  using resource = new Foo();
}

main();
```

### 🙁 Actual behavior

I get an error: ` 'resource' is declared but its value is never read.(6133)`

### 🙂 Expected behavior

Ideally the `using` keyword would, well, you know... make it so that local was marked as "used" so that it's not giving an error that I didn't use the thing that I explicitly specified was being used by using the `using` keyword. 

(that was fun 😄)

But seriously... I think the `using` keyword should count as "using" and not just a declaration.

**Comment by MartinJohns** [comment] 2023-08-29 18:07
Duplicate of #55538.

**Closed** 2023-09-01 01:27 UTC
Labels: Duplicate
