### ISSUE TITLE
typescript changing the type in scope using "as"

### ISSUE THREAD

**Issue by oniiichannnn** [microsoft/TypeScript#50385] opened 2022-08-21 03:36 UTC
# Suggestion

I run into this issue just now:
```ts
        function $CheckValue (CurrentValue: Array<any>, CheckingValue: Array<any>, type: "Array"):boolean; // <- here i specified that CurrentValue and CheckingValue will only be an array if the "type" is equal to "Array"
        function $CheckValue (CurrentValue: object, CheckingValue: object, type: "Object"):boolean;
        function $CheckValue (CurrentValue: Array<any>|object, CheckingValue: Array<any>|object, type:"Array"|"Object"):boolean {
            
            switch (type) {
                case "Array": {   // <- here, "type" is equals to "Array"
                 
                    let IsSimilar = false;

                    if (CurrentValue.length !== CheckingValue.length) return false; // <- but this line gives the error "Property 'length' does not exist on type 'object | any[]'. Property 'length' does not exist on type 'object'."

                } break;
            }

        }
```

so i want to suggest something like changing the type in scope only, for example:
```ts
function myfunc (input: string | number) {
  if (condition) {
    input as string;
    
    ...
  } else {
    input as number;
    
    ...
  }
}
```
of course in the example case, i can just check the type of the `input` but in my case, although i did that typescript does not know that my value(s) are an array and not a object

## 🔍 Search Terms

typescript scope only type

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

i'd like to see this suggestion implemented

## 💻 Use Cases

i'd use this so that i don't need to create a new variable whenever my type guard doesn't work

**Comment by oniiichannnn** [comment] 2022-08-21 03:37
I also tried
```ts
                    CheckingValue = CheckingValue as Array<any>;
                    CurrentValue = CheckingValue as Array<any>;

                    let IsSimilar = false;

                    if (CurrentValue.length !== CheckingValue.length) return false;
```
but it does not remove the error too

**Comment by fatcerberus** [comment] 2022-08-21 03:38
Duplicate of https://github.com/microsoft/TypeScript/issues/10421

**Closed** 2022-08-25 18:00 UTC
Labels: Duplicate
