### ISSUE TITLE
JScript Functions Support

### ISSUE THREAD

**Issue by impepc** [microsoft/TypeScript#57675] opened 2024-03-07 13:49 UTC
### ⚙ Compilation target

es3

### ⚙ Library

scripthost

### Missing / Incorrect Definition

JScript has functions, but it seems not supported in script-host.
https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/scripting-articles/6fw3zxcx(v=vs.84)

There are little bit differences ex. WScript.GetObject vs GetObject
https://stackoverflow.com/questions/21245480/wscript-getobject-does-not-work-but-getobject-does

Could support these functions in script-host?

- GetObject
- ScriptEngine
- ScriptEngineBuildVersion
- ScriptEngineMajorVersion
- ScriptEngineMinorVersion

### Sample Code

```TypeScript
WScript.GetObject("", "Excel.Application");  // correct in TypeScript, but this can't get ActiveWorkbook in JScript.
GetObject("", "Excel.Application").ActiveWorkbook;  // not correct in TypeScript, but this can get ActiveWorkbook in JScript.
```

**Comment by MartinJohns** [comment] 2024-03-07 13:54
Sounds like a duplicate of #42610.

**Comment by impepc** [comment] 2024-03-09 00:22
@MartinJohns 
Thank you.

@rubiesonthesky 
okay.
I found lib in DefinitelyTyped.
I would be better to send PR. thanks.
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/windows-script-host

**Closed** 2024-03-12 01:24 UTC
Labels: Duplicate
