### ISSUE TITLE
Cannot get ReturnType of protected class member

### ISSUE THREAD

**Issue by lennontu** [microsoft/TypeScript#45703] opened 2021-09-03 03:17 UTC
### Code
```ts
class A {
  a(): ReturnType<this['b']> { // it shows Private or protected member 'b' cannot be accessed on a type parameter.ts(4105)
    return this.b();
  }

  protected b(): any {
    return '';
  }
}

class B extends A {
  protected b(): number {
    return 1;
  }
}
```

how could I get ReturnType of protected class member

**Comment by MartinJohns** [comment] 2021-09-03 08:04
You forgot to fill out the issue template. Duplicate of #17362.

**Closed** 2021-09-03 08:25 UTC
