### ISSUE TITLE
Object.assign() allows overwriting readonly property

### ISSUE THREAD

**Issue by arendjr** [microsoft/TypeScript#35361] opened 2019-11-26 16:31 UTC
**TypeScript Nightly**
[Playground link](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191125#)

Compiler Options:
```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

**Input:**
```typescript
interface A {
    readonly b: boolean;
}

const a: A = { b: true };

a.b = false; // Correctly complains: Cannot assign to 'b' because it is a read-only property.

Object.assign(a, { b: false }); // No complaints.
```

**Output:**
```javascript
"use strict";
const a = { b: true };
a.b = false; // Correctly complains: Cannot assign to 'b' because it is a read-only property.
Object.assign(a, { b: false }); // No complaints.

```

**Expected behavior:**

`Object.assign(a, { b: false });` should complain with a message similar to the direct assignment.

**Comment by jcalz** [comment] 2019-11-26 19:06
Please note that the [bug report template](https://raw.githubusercontent.com/microsoft/TypeScript/master/.github/ISSUE_TEMPLATE/Bug_report.md) asks you to fill out **search terms** and **related issues**, both of which provide relevant context and shift some of the burden of researching an issue away from the overworked language maintainers.

Duplicate of #13347

**Comment by orta** [comment] 2019-11-27 21:19
I'll take the blame for that, the playground template didn't include those requests. It will on the next deploy https://github.com/orta/typescript-play/pull/34

Sorry @arendjr

**Closed** 2019-11-30 18:00 UTC
Labels: Duplicate
