### ISSUE TITLE
Type 'any[]' is not assignable to type '[any, any]' when constructing a Map from array of entries 

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#22870] opened 2018-03-25 21:15 UTC
During my work at https://github.com/webpack/webpack/pull/6862 I noticed this error. 

**TypeScript Version:**  2.7.8-rc

**Search Terms:** 

**Code**
https://github.com/webpack/webpack/blob/master/lib/util/objectToMap.js
```ts
function objectToMap(obj) {
	return new Map(Object.keys(obj).map(key => [key, obj[key]]));
};
```

**Expected behavior:**
No error

**Actual behavior:**

```

lib/util/objectToMap.js:9:17 - error TS2345: Argument of type 'any[][]' is not assignable to parameter of type 'Iterable<[any, any]>'.
  Types of property '[Symbol.iterator]' are incompatible.
    Type '() => IterableIterator<any[]>' is not assignable to type '() => Iterator<[any, any]>'.
      Type 'IterableIterator<any[]>' is not assignable to type 'Iterator<[any, any]>'.
        Types of property 'next' are incompatible.
          Type '{ (value?: any): IteratorResult<any[]>; (value?: any): IteratorResult<any[]>; }' is not assignable to type '{ (value?: any): IteratorResult<[any, any]>; (value?: any): IteratorResult<[any, any]>; }'.
            Type 'IteratorResult<any[]>' is not assignable to type 'IteratorResult<[any, any]>'.
              Type 'any[]' is not assignable to type '[any, any]'.
                Property '0' is missing in type 'any[]'.

9  return new Map(Object.keys(obj).map(key => [key, obj[key]]));
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by DanielRosenwasser** [comment] 2018-03-26 03:50
I think this looks like a duplicate of #11152

**Comment by MartinJohns** [comment] 2018-03-26 08:06
The tuple is inferred to be an array. As a temporary workaround you can just specify the exact type when calling `map`:

```
array.map<[Type1, Type2]>(key => [key, obj[key]])
```

That will make it explicit that you want a tuple.

**Comment by mhegazy** [comment] 2018-03-26 20:11
in  a .js file you can cast using `/** @type ... */`:

```js
function objectToMap(obj) {
	return new Map(Object.keys(obj).map(key => /** @type [string, string] */ ([key, obj[key]]));
};  
```

**Closed** 2018-04-10 20:50 UTC
Labels: Duplicate
