### ISSUE TITLE
Error "Target requires N element(s) but source may have fewer" with arguments of function

### ISSUE THREAD

**Issue by GTOsss** [microsoft/TypeScript#48486] opened 2022-03-30 15:19 UTC
# Bug Report

### 💻 Code

Here is ok:
```ts
type A = [...any[], boolean];
type B = [string, string, boolean];

let a: A = ['test', false];
let b: B = ['test', 'test', false];
a = b; // no errors
b = a; // error, it's ok
```

But why is error here?
```ts
type M = (...params: [...any[], boolean]) => void;

const m: M = (a: string, b: string, cn: boolean) => {} // error? why? 
```

### 🙁 Actual behavior

 Error: Target requires 3 element(s) but source may have fewer.

### 🙂 Expected behavior

No errors.

### Example
[Example here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAslC8UAUA6NYCGAnDBbAzgFxQDaaKGAdiCQLoA0UARgPYsA2EVtAlAgHxQAbiwCWAEwDcAWABQcgMYtK+YFFzE4iJBmKqsoygHNGTPcAPHGCysVYculPvEEBvAL5y5oSFACCCKTkVDQMzGyc3DKyPtAAQoEk+oYmUMlW4Q5RXrKcarr+iQDkwBCqRYwAZhjs+BC00XnMxAmIJCVlwBVQHeVVNXUNchiBTNFAA)

**Comment by MartinJohns** [comment] 2022-03-30 15:23
Duplicate of #48485.

**Comment by RyanCavanaugh** [comment] 2022-03-30 20:15
`m("", false);` is a legal call which would put a boolean in `b`, thus the error

**Comment by GTOsss** [comment] 2022-03-30 21:39
@RyanCavanaugh Yes, it working. But why I get error, and how describe type correctly?

**Comment by RyanCavanaugh** [comment] 2022-03-31 17:05
I'm not sure how to answer that. You have a round peg and you want to put it in a square hole. You can either make the peg square, or the hole round.

**Closed** 2022-04-02 20:00 UTC
Labels: Working as Intended
