### ISSUE TITLE
Bugs with enum (import and typing)

### ISSUE THREAD

**Issue by lucasmciruzzi** [Microsoft/TypeScript#3507] opened 2015-06-14 20:36 UTC
When I import a module that has an enum and then I pass a string variable as index, with the noImplicitAny flag set to true, I get an error of implicit any in the index signature.

### Examples:
**This works but it has an unwanted behavior detailed in the comment:**
````typescript
enum Foobar {
    "foo",
    "bar"
}

var consoleFoobar = (index: string) => {
    // output is of type any. It should be number if the index is string and string if the index is number
    var output = Foobar[index];
    console.log(output);
}
````
**This trows an error:**
````typescript
// a-module.ts
export enum Foobar {
    "foo",
    "bar"
}

// app.ts
import { Foobar } from "./a-module";

var consoleFoobar = (index: string) => {
    var output = Foobar[index]; // Error: Index signature of object type implicitly has an 'any' type.
    console.log(output);
}
````

**Comment by DanielRosenwasser** [comment] 2015-06-15 03:58
Sounds like a dupe of #1232. You may want to look into `--suppressImplicitAnyIndexErrors`.

```
--suppressImplicitAnyIndexErrors   Suppress noImplicitAny errors for indexing objects lacking index signatures.
```

See:
* [The wiki page on compiler options](https://github.com/Microsoft/TypeScript/wiki/Compiler-Options)
* @danquirk's [explanation/context of the issue](https://github.com/Microsoft/TypeScript/issues/1232#issuecomment-64510362)

**Comment by lucasmciruzzi** [comment] 2015-06-15 12:32
I don't want to suppress the implicit any errors (they are useful), the thing is that enum is trowing errors and it shuldn't.

Let's say I have an enum like this: `enum EnumExample { "value" }`. When I write `EnumExample[0]` I should get a string (`"value"` in this case) or undefined, and when I write `EnumExample["value"]` I should get a number (`0` in this case) or undefined. The bug is that I get an any if the enum is in the same file, and if I load the enum from a module, It trows an index error (error that doesn't trow if is in the same file).

**Comment by danquirk** [comment] 2015-07-08 19:37
@lucasmciruzzi with the latest bits in master I see the same behavior in both scenarios (the single file and multi file case). The type of ```output``` is any and no errors are reported.

See https://github.com/Microsoft/TypeScript/issues/592 for why we give an ```any``` here.

**Closed by danquirk** 2015-07-08 19:37 UTC
