### ISSUE TITLE
Strong typing for <Function>.length

### ISSUE THREAD

**Issue by Mantou1233** [microsoft/TypeScript#52206] opened 2023-01-12 14:44 UTC
# Suggestion

## 🔍 Search Terms

function lambda length strict typings

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I hope typescript can add strong typings on `<Function>.length`

## 📃 Motivating Example

```ts
function fn1(arg0: number, arg1: string, arg2: any) {}
type length = (typeof fn1).length // excepted as 3

function fn2(...args: any[]) {}
type length2 = (typeof fn2).length // excepted as 0 (like in runtime)

function fn3(arg0: number, arg1: any, ...args: any[] {}
type length3 = (typeof fn3).length // excepted as 2 (like in runtime)
```

## 💻 Use Cases

It would be meaningful and useful in typings, for instance, currying.

**Comment by MartinJohns** [comment] 2023-01-12 15:06
Duplicate of #20866 / #18422.

**Comment by RyanCavanaugh** [comment] 2023-01-12 17:48
It could in theory be `0 | 1 | 2 | 3`, but the usefulness of that would be almost nonexistent.

**Comment by Mantou1233** [comment] 2023-01-13 05:22
> It's legal to assign functions with fewer parameters to a callback having more parameters.
don’t see why this shouldn’t be implemented tho?

**Comment by fatcerberus** [comment] 2023-01-13 16:04
> don’t see why this shouldn’t be implemented tho?

Let's say you have the function type `(x: number) => string`.  Under this proposal its `.length` would be literal-typed as `1`.  However, the arrow function `() => "foo"` is assignable to that type, and its `.length` would be `0` at runtime, so the type would be wrong.

**Closed** 2023-01-15 18:00 UTC
Labels: Duplicate
