### ISSUE TITLE
Narrowing types based on property access

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#46219] opened 2021-10-05 02:12 UTC
# Suggestion

## 🔍 Search Terms

type narrowing based on property checks, similar to `in` operator.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code. I don't think so, because errors are currently produced, but now there would be narrowing instead of errors.
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Lot's of JS code uses duck typing. For example:

## 📃 Motivating Example

```ts
class Foo {
    bar: object = {}
    meth() {}
}

declare const f: Foo | Foo[]

if (f.bar) { // Error, bar property does not exist on Foo | Foo[]
  f.meth()
}
```
[playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ0PQEZgE4C5p4sArAU2ABdoBeFAX3UwFszKALACgEoHVHUAEwrhcZaMHgA7CNQBmhBEgA+cRAG0AuqlQBLOdE5yAdDly80GE6w49+QA)

## 💻 Use Cases

We can currently do something similar that actually works:

```ts
class Foo {
    bar: object = {}
    meth() {}
}

declare const f: Foo | Foo[]

if ('bar' in f) {
  f.meth()
}
```

[playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ0PQEZgE4C5p4sArAU2ABdoBeFAX3UwFszKALACgEoHVHUAEwrhcZaMHgA7CNQBmhBEgA+cRAG0AuqlQBLOdE4ByHLiPRdU6HN5oMcgHSsOPfkA)

But using a property check would allow us to write code like we can (and like currently exists) in plain JS. The `f.bar` check would behave similar to the `'bar' in f` check, and would narrow the type.

This would need to be limited to certain property types. For example, if `Foo.bar` were a number, then a value of `0` can make it result in a `false` even if the property exists. In this case TS would need to throw an error and would not be able to perform type narrowing in such cases.

If the type of `Foo.bar` is something that is always truthy (f.e. `bar: Record<Foo, Bar>` is always truthy) then type narrowing can be performed. The system would have to clearly report errors in cases when type narrowing can not be confidently performed based on the encountered type.

**Comment by MartinJohns** [comment] 2021-10-05 05:04
Duplicate of #39065.

**Comment by FilipeBeck** [comment] 2021-10-05 15:00
> You're wrongly assuming that just because a truthy bar property exists it must be a Foo object

```typescript
declare const f: Foo | Foo[]
```
If `f` is `Foo | Foo[]` and `bar` exists in `f`, then it is a instance of `Foo`. I don't see problems using `'bar' in f`, but the premise is true based on the type `Foo | Foo[]`.

**Comment by fatcerberus** [comment] 2021-10-05 15:13
Not necessarily:
```ts
interface Foo {
    foo: string;
}

interface Bar {
    foo: number;
    bar: string;
}

// not a valid `Bar` because `Bar` calls for `foo: number`.
// it IS a valid `Foo`, though!
const thing = { foo: "pig", bar: "cow" };
doIt(thing);

function doIt(foobar: Foo | Bar)
{
    if ('bar' in foobar) {
        foobar.foo;  // hover here - TS thinks it's a `Bar` and therefore that `foobar.foo` is a number
    }
}
```

**Comment by FilipeBeck** [comment] 2021-10-05 15:18
Yes, but, in this case, `f` is `Foo | Bar` and `Bar` has `foo` too. Now, in `Foo | Foo[]`, `Array<Foo>` does not have `foo`. Only `Foo` has `foo`. Look the playground link in issue description. The compiler sees `f` as `Foo` in `'bar' in f`

**Comment by FilipeBeck** [comment] 2021-10-05 15:19
As I said, based in type `Foo | Foo[]`, the premise is true

**Comment by fatcerberus** [comment] 2021-10-05 15:19
It's completely possible for `Foo[]` to have a `foo` property.  One can make subtypes of `Array`.

**Comment by FilipeBeck** [comment] 2021-10-05 15:19
> For example, if Foo.bar were a number, then a value of 0...

This is reason why `(if f.bar)` doesn't always work

**Comment by FilipeBeck** [comment] 2021-10-05 15:22
> It's completely possible for Foo[] to have a foo property. One can make subtypes of Array.

Yes. Look the playground link and do this. You will get a compiler error

**Comment by FilipeBeck** [comment] 2021-10-05 15:24
> One can make subtypes of Array.

`f` is `Foo | Foo[]` and not `Foo | ASubtypeOfArrayThatContainsAFooProperty`

**Comment by MartinJohns** [comment] 2021-10-05 15:24
```typescript
class Foo {
    bar: object = {}
    meth() {}
}

const f: Foo | Foo[] = Object.assign([], { bar: {} });

console.log(Array.isArray(f))
console.log('bar' in f)
```

Will print out `true` two times. [Playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ0PQEZgE4C5p4sArAU2ABdoBeFAX3UwFszKALACgEoHVHUweADsI1AGaEESAD5xEAbQC6taAHlSFSgDpIEAJYBzYZ2UAaFNjyFk9aPW4BuVIJER4IMtpDxDnAIK4uGAAntr6EIHBIZzi3Nyuoh5ePn4A5Di4adD6wtBxqEA)

**Comment by fatcerberus** [comment] 2021-10-05 15:26
`ASubtypeOfArrayThatContainsAFooProperty` *is assignable to* `Array`.  That was my point.

**Comment by FilipeBeck** [comment] 2021-10-05 15:27
> const f: Foo | Foo[] = Object.assign([], { bar: {} });

You are assing `bar` to `[]` using `Object.assing`. In `if('bar' in f)`, the compiler continue seeing `f` as `Foo`

**Comment by fatcerberus** [comment] 2021-10-05 15:27
I give up.

**Comment by fatcerberus** [comment] 2021-10-05 15:33
Only if we had Exact Types.  https://github.com/microsoft/TypeScript/issues/12936

**Comment by FilipeBeck** [comment] 2021-10-05 15:34
You want a type-based system not to consider the type because you can create "patches" to circumvent the typing

**Comment by MartinJohns** [comment] 2021-10-05 15:34
The compiler is **wrong** seeing it, as my example demonstrated. It sees it as `Foo`, when in fact it is **not** a `Foo`, but a `Foo[]`. Trying to access `meth()` will result in an error. This unsoundness is also mentioned in #34975.

**Comment by MartinJohns** [comment] 2021-10-05 15:38
And here's an example without `Object.assign`:

```typescript
type FooArrayWithBarProperty = Foo[] & { bar?: string }

const fooArrayWithBarProperty: FooArrayWithBarProperty = []
fooArrayWithBarProperty.bar = 'hello!'

const ff: Foo | Foo[] = fooArrayWithBarProperty;
if ('bar' in ff) {
    ff;
}
```

**Comment by FilipeBeck** [comment] 2021-10-05 15:38
Solution. Do right and don't use `Object.assign` to assign a property that does not exists in the type. Do not do "gambiarras"

**Comment by FilipeBeck** [comment] 2021-10-05 15:46
> And here's an example without Object.assign:

Try to call `ff.metch()` inside `if` block

**Comment by MartinJohns** [comment] 2021-10-05 15:50
> Try to call `ff.metch()` inside `if` block

Honestly, this is getting ridiculous. It's clear that you don't know what the heck you're talking about.

In the brief example you can't call `meth()` because TypeScript correctly narrows it to `never`. This is due to the behaviour of assignments narrowing the type of variables. TypeScript sees that a `Foo[]` is assigned, but no `Foo`. So trying to narrow it to `Foo` using `'bar' in ff` results in `never`, because it can't be a `Foo`.

If you take this behaviour out of the equation (e.g. by returning the value from a function) you will get the issue mentioned:

```typescript
class Foo {
    bar: object = {}
    meth() {}
}

type FooArrayWithBarProperty = Foo[] & { bar?: string }

const ff: Foo | Foo[] = getValue();
if ('bar' in ff) {
    // ff is narrowed to "Foo", but the value is actually a "Foo[]".
    // Calling meth() will result in an error.
    ff.meth();
}

function getValue(): Foo | Foo[] {
    const fooArrayWithBarProperty: FooArrayWithBarProperty = [];
    fooArrayWithBarProperty.bar = 'hello!';
    return fooArrayWithBarProperty;
}
```

[Playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ0PQEZgE4C5p4sArAU2ABdoBeFAX3UwFszKALACgEoHVHUlAJ4AHMnEQBBXLjBCA6gEsOAITwAFXPDG5htCfADaAXWgAyFNjwB+QhEq5FAOwDm0AcHhP70AGa-CBCQAHwMTfRc2ADUwEABXMh4AblRFX2hOAHIcXEzoZz9fXjRMaAB6MsL8mCc8LQB3MgATaEokACIg9oAabDjqDnEAN1iE6ugwKjjYkCEJ6E7EE3aAOiYMCugAYRnnN1YOHmh6xRAQaFwyCDiQagKwJ2gyGXhcNdL-FYOubhSBXziTioii80EilBi8US3ECiGgoSC4RKmE83movikMjkSlUGi0OmEsPg0lkCmU7DUuE02meejoJhSH0xpJxFLxNN0QhWOX0mXYZDO8AAhJlGZhLpQ4rhHhjiViybiqfjaUI-qggA)

**Closed** 2021-10-05 21:09 UTC
Labels: Duplicate

**Comment by FilipeBeck** [comment] 2021-10-05 22:53
> Honestly, this is getting ridiculous. It's clear that you don't know what the heck you're talking about.

I'm not saying that a type cannot have additional properties (I said the exact opposite [here](https://github.com/microsoft/TypeScript/issues/45975#issuecomment-926258598) myself). I'm saying the compiler is correct when handling `f` as `Foo` due to  `Foo[]` "not have" `'bar'` because it already behaves as expected. The compiler is optimistic and handles as _exact types_ with respect to the `in` operator. This is enough for the vast majority of cases if you use good programming practices. I never had any problems using `in` to determine the type, neither in my personal projects nor in my work.

This was explained here: https://github.com/microsoft/TypeScript/pull/15256#discussion_r154825541

> > For example, if Foo.bar were a number, then a value of 0...
> 
> This is reason why `(if f.bar)` doesn't always work

Yes, it is a duplicate and, even if it wasn't, the issue is incoherent and must be closed

**Comment by FilipeBeck** [comment] 2021-10-05 23:02
Maybe I might not have expressed myself well before because my english is more google than me. Sorry by the possible language mistakes.
