### ISSUE TITLE
JavaScript–TypeScript syntactic difference with shift operators

### ISSUE THREAD

**Issue by anematode** [microsoft/TypeScript#53710] opened 2023-04-09 17:04 UTC
# Bug Report

### 🔎 Search Terms

left shift, syntax ambiguity

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about incompatibilities between JavaScript and TypeScript

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.5.1#code/GYVwdgxgLglg9mABMAFAQwFyLCAtgIwFMAnAGkXyxwJIEpEBvAKEVcQEZEAeLxNFtmkQA+YYhT5aTAL5A)

### 💻 Code

```ts
function f(a: number, b: number) {
    1 << a
    a >> (b)
}
```

### 🙁 Actual behavior

Compiling with `tsc test.ts --noEmit false` yields

```js
function f(a, b) {
    1(b);
}
```

### 🙂 Expected behavior

Should yield (something equivalent to)

```js
"use strict";
function f(a,b) {
    1 << a
    a >> (b)
}```

**Comment by MartinJohns** [comment] 2023-04-09 17:21
Possibly a duplicate of #37760.

**Closed** 2023-04-12 18:00 UTC
Labels: Duplicate
