### ISSUE TITLE
Type narrowing of an object does not narrow parent union type containing the object

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#25631] opened 2018-07-13 06:29 UTC
**TypeScript Version:**  playground

**Search Terms:** narrowing

**Code**

```ts
enum Type {
  A,
  B
}

interface A {
  type: Type.A
}

interface B {
  type: Type.B
}

type AorB = {
  value: A
} | {
  value: B
  extra: {}
}

declare var aOrB: AorB

if (aOrB.value.type === Type.B) {
  const val: B = aOrB.value // OK
  aOrB.extra // not OK because it's missing in { value: A } but value cannot be A
}
```

**Expected behavior:**

The narrowing of `aOrB.value` to also narrow the type of `aOrB`.

**Actual behavior:**

`aOrB.extra` cannot be accessed because the compiler still believes it can be `{ value: A }` even though `value` has already been proven to not be `A`.

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=enum%20Type%20%7B%0A%20%20A%2C%0A%20%20B%0A%7D%0A%0Ainterface%20A%20%7B%0A%20%20type%3A%20Type.A%0A%7D%0A%0Ainterface%20B%20%7B%0A%20%20type%3A%20Type.B%0A%7D%0A%0Atype%20AorB%20%3D%20%7B%0A%20%20value%3A%20A%0A%7D%20%7C%20%7B%0A%20%20value%3A%20B%0A%20%20extra%3A%20%7B%7D%0A%7D%0A%0Adeclare%20var%20aOrB%3A%20AorB%0A%0Aif%20(aOrB.value.type%20%3D%3D%3D%20Type.B)%20%7B%0A%20%20const%20val%3A%20B%20%3D%20aOrB.value%20%2F%2F%20OK%0A%20%20aOrB.extra%20%2F%2F%20not%20OK%20because%20it's%20missing%20in%20%7B%20value%3A%20A%20%7D%20but%20value%20cannot%20be%20A%0A%7D%0A

**Comment by mhegazy** [comment] 2018-07-13 23:03
Duplicate of https://github.com/Microsoft/TypeScript/issues/18758

**Closed** 2018-07-25 19:13 UTC
Labels: Duplicate
