### ISSUE TITLE
const string is not recognized as string literal type in map function

### ISSUE THREAD

**Issue by k8w** [Microsoft/TypeScript#17959] opened 2017-08-22 09:29 UTC
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)
2.4.2
**Code**

```ts
type AABB = 'AA' | 'BB';
let arr: any[];
let arr2: AABB[] = arr.map(v => 'AA'); 
let arr3: AABB[] = arr.map(v => 'BB');
```

**Expected behavior:**
No Error

**Actual behavior:**
Error:
> Type 'string[]' is not assignable to type 'AABB[]'.

**Comment by kitsonk** [comment] 2017-08-22 10:38
Duplicate of #9659

**Comment by mhegazy** [comment] 2017-08-22 16:57
a better one is https://github.com/Microsoft/TypeScript/issues/11152

**Comment by mhegazy** [comment] 2017-09-05 17:05
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-05 17:05 UTC
Labels: Duplicate
