### ISSUE TITLE
How to write a generic function whose param/return types are class constructor functions?

### ISSUE THREAD

**Issue by yortus** [Microsoft/TypeScript#5163] opened 2015-10-08 05:18 UTC
I have a function that takes a class constructor as a parameter, and returns another class constructor of the same type. Internally, the provided constructor is subclassed and augmented, and the subclass is returned.

I'm having trouble finding a way to express this function in a generic, strongly-typed manner. Note the `//ERROR` comment in the repro code below:

Repro code:

```typescript
// Base type of the family of classes operated on by the augment() function
class FooClass { /*...*/ }


// ========== Works, but is not generic ==========
function augment(SuperClass: typeof FooClass): typeof FooClass {
    class SubClass extends SuperClass {
        /*...*/
    }
    return SubClass;
}
var FooClass2 = augment(FooClass);


// ========== Generic, but does not compile ==========
function genericAugment<T extends typeof FooClass>(SuperClass: T): T {
    class SubClass extends SuperClass { //ERROR: Type 'T' is not a constructor function type
        /*...*/
    }
    return SubClass;
}
```

I've tried a few other variations, but can't seem to find a way to express this pattern.

Is there any way to do it?

**Comment by billccn** [comment] 2015-10-08 13:37
See also #4693

**Comment by mhegazy** [comment] 2015-10-09 00:01
looks like a duplicate of #4890.

@ahejlsberg has a workaround in https://github.com/Microsoft/TypeScript/issues/4890#issuecomment-141879451 that should help modeling this, but ultimately you want to be able to extend a type parameter.

**Closed by mhegazy** 2015-10-09 00:01 UTC
