### ISSUE TITLE
member types, e.g. Tree<T>.Node

### ISSUE THREAD

**Issue by d180cf** [Microsoft/TypeScript#8106] opened 2016-04-15 02:46 UTC
Sometimes it's useful to declare new types within a class/interface, especially when it's a generic:

```ts
class Tree<T> {
  private type Node = { data: T, subnodes: Node[] };
  public root: Node = { data: null, subnodes: [] };
  ...
}
```

Such member types could be referred to as `Tree<T>.Node`.

**Comment by Arnavion** [comment] 2016-04-15 08:58
Previous discussion at #7061

**Comment by mhegazy** [comment] 2016-04-18 22:38
Duplicate of #7061 as noted by @Arnavion

**Closed** 2016-04-18 22:38 UTC
Labels: Duplicate
