### ISSUE TITLE
UInt8ClampedArray reported as a warning

### ISSUE THREAD

**Issue by isidorn** [Microsoft/TypeScript#4181] opened 2015-08-06 07:29 UTC
Have the following code:

var a3 = new Uint8ClampedArray(10000);

Notice a warning "Can not find name UInt8ClampedArray" (attachmend)
This should not be a warning, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray

Here's a screenshot using VSCode

![screen shot 2015-07-30 at 11 14 56](https://cloud.githubusercontent.com/assets/1926584/9106063/8c14bd2a-3c1d-11e5-82e7-f5f33653c2b5.png)

**Comment by kitsonk** [comment] 2015-08-06 10:24
Dupe of #1995

**Closed** 2015-08-06 17:33 UTC
Labels: Duplicate
