### ISSUE TITLE
Add `--listExplicitAny` or `--warnExplicitAny`

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#13316] opened 2017-01-06 06:54 UTC
Agree with @aluanhaddad in his comment about the backfire effect of `--noImplicitAny`
https://github.com/Microsoft/TypeScript/issues/11839#issuecomment-260829385

It would be nice to add `--listExplicitAny` or `--warnExplicitAny` flag to catch those unfortunate circumstances.

Doing a text search for `: any` may work, but I worry that there may be some case this simple text search is not sufficient.
Since the compiler has all the information needed, it may be better to let the compiler helping out here.

**Comment by DanielRosenwasser** [comment] 2017-01-06 17:06
Would find-all-references on built-in types be sufficient?

**Comment by unional** [comment] 2017-01-06 22:12
Do you mean it is available (or to be made available) in the compiler API or as a flag?

Will find-all-references differentiate between implicit any and explicit any?
^ will probably do not matter because the context of this discussion is to enable `--noImplicitAny`, thus all `any` are explicit.

It is probably a better route as it is more generic. 🌷

**Comment by DanielRosenwasser** [comment] 2017-01-06 23:15
It doesn't exist now, but I'd like it to.

Find all references would find explicit annotations and uses of `any`.

**Comment by unional** [comment] 2017-01-06 23:32
Feel free to change the title to reflect `find-all-reference` 🌷

**Comment by aluanhaddad** [comment] 2017-01-08 00:48
@unional thanks taking up the cause ❤️!

Being able to find all references on `any` would be great, so I'm all for that, but it would be really nice to have a `--warnExplicitAny` flag as you suggest in your opening post.
This could raise an error, or offer a codefix, whenever an explicit `any` adorns a declaration that would **not** otherwise be an implicit `any`.

**Comment by NN---** [comment] 2017-01-11 05:08
You can use TSLint https://palantir.github.io/tslint/rules/no-any/

**Comment by unional** [comment] 2017-01-12 01:31
@NN--- `tslint` does not allow you to just pass in a rule in the command line.
The purpose of this is to just run a check to see if there are any not appropriated `any` usage in the code.

In regular development, you would like to have this turned off so it won't distract the developers.

**Comment by mhegazy** [comment] 2017-01-13 17:57
What about `never` should we have a flag for it too? what about `void` in argument position? or `undefined` in function return positions? what about `JSON.parse` would it be marked as an error as well? what would be and what would not be..

I do not think we would add a flag like such, this seems to fall in the realm of style/lint tools. 

I do support enabling find all references for `any` (and other primitive types), we disallow them today to avoid noise, but seems artificial.

**Comment by mhegazy** [comment] 2017-01-13 17:59
Filed https://github.com/Microsoft/TypeScript/issues/13473 to track find all refs.

**Comment by unional** [comment] 2017-02-07 08:54
Close this as #13566 landed? How to use it?

**Comment by mhegazy** [comment] 2017-02-07 17:42
#13566 is in, but there is still a bug https://github.com/Microsoft/TypeScript/issues/13846. should be fixed for 2.2.1

**Closed by mhegazy** 2017-02-07 17:42 UTC
Labels: Out of Scope, Suggestion
