### ISSUE TITLE
Project dependency files remain locked indefinitely

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/TypeScript#29856] opened 2019-02-08 10:15 UTC
Issue Type: <b>Bug</b>

When I open a project in VS Code, VS Code will lock `node_modules` folders in my project dependencies, preventing me from running `npm install` successfully. This worked fine in 1.30.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3672)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.91GB (37.85GB free)|
|Process Argv|build-utils-ui/build-utils-ui.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal-formatter|ale|2.1.0
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.0
gitlens|eam|9.5.0
EditorConfig|Edi|0.12.8
JSDocTagComplete|Hoo|0.0.2
vscode-esformatter|how|1.6.0
output-colorizer|IBM|0.1.2
code-beautifier|mic|2.1.0
vscode-lebab|mrm|2.6.0
vscode-puglint|mrm|2.3.0
debugger-for-chrome|msj|4.11.1

(1 theme extensions excluded)

</details>

**Comment by falsandtru** [comment] 2019-02-18 17:04
See also https://github.com/Microsoft/vscode/issues/68576

This bug doesn't depend on extensions and seems to happen anywhere in the project directory.

**Comment by falsandtru** [comment] 2019-02-19 16:50
Today, on Ubuntu this bug appeared in my haskell project which has no .ts file.

**Comment by sheetalkamat** [comment] 2019-02-27 20:29
Closing this as this is duplicate of #29407

**Closed by sheetalkamat** 2019-02-27 20:29 UTC
Labels: Duplicate

**Comment by oliversalzburg** [comment] 2019-02-27 22:32
@sheetalkamat I didn't have this issue prior to the latest update, no @types folders are involved in the mix and this affects projects that don't use gulp at all. Are you sure this is related to #29407?

**Comment by jasonswearingen** [comment] 2019-03-10 15:05
@sheetalkamat ocasionally I also have the same issue as @oliversalzburg   the node_modules folder becomes locked, not the @types folder.  So I do not think this is a dupe of #29407

I only notice when doing a delendency reinstall (using ```yarn```) but I don't know if it's related, just when I notice it.

I used LockHunter on windows to determine the cause of the lock (tsserver, which helped me find this issue).

### speculative cause:
yesterday I commented out ```compileOnSave:true``` and ```composite:true``` in my ```tsconfig.json``` and I haven't seen the error occur since.   I will add an update if this turns out to not be the case.

**Comment by oliversalzburg** [comment] 2019-03-11 00:30
I remember there was a reply here, explaining to some degree that it is a dupe, but the reply seems to have been removed. Issue is still closed though :( I'll just wait for #29407 to be resolved, then I report again if the issue remains.

**Comment by falsandtru** [comment] 2019-03-11 00:38
Probably her fix will cover the cases provided here since she found the core problem: https://github.com/Microsoft/TypeScript/issues/29407#issuecomment-468020013
