### ISSUE TITLE
Allow custom static analysis, esp. for Jquery selectors

### ISSUE THREAD

**Issue by wizofaus** [Microsoft/TypeScript#2738] opened 2015-04-13 01:11 UTC
I'm using TypeScript quite heavily now, and loving the static/compile-time checking that I've always felt was sorely missing with JS-based development, but I'd love even more, especially for JQuery selectors.  E.g. if my .ts file is used by an .aspx or .html page I want to know when I've misspelled an ID or classname or pseudo-class in a jquery selector, or I've got the wrong syntax. I'd be happy to add this sort of thing myself (I understand it's not integral to TypeScript itself) but is there a plugin mechanism for TypeScript's static-analysis module to do this? Ideally I'd even be able to write it so that TypeScript knows the object type from a Jquery selector - e.g. if I use $("select").each((i,e)=>{ e.selectedIndex = -1 }) that should compile because the use of "select" means the element type is HTMLSelectElement.

**Comment by CyrusNajmabadi** [comment] 2015-04-13 05:25
>  if I use $("select").each((i,e)=>{ e.selectedIndex = -1 }) that should compile because the use of "select" means the element type is HTMLSelectElement.

Ideally, there would be some string-overload of $ that indicated that.  it should look something like:

```ts
declare function $(v: "select"): HTMLSelectElement { }
```

**Comment by danquirk** [comment] 2015-04-13 18:52
In general the VS HTML editor and backing JS/TS could be much more aware of one another's contents (and error/suggest things appropriately).

**Comment by mhegazy** [comment] 2015-12-10 03:16
Looks like a dupe of https://github.com/Microsoft/TypeScript/issues/3136

**Closed by mhegazy** 2015-12-10 03:16 UTC
Labels: Suggestion
