### ISSUE TITLE
Typescript can't recognize possible type in condition correctly

### ISSUE THREAD

**Issue by TopYar** [microsoft/TypeScript#47262] opened 2021-12-29 06:32 UTC
# Bug Report

Typescript doesn't recognize type in condition correctly. Please see the code section below

### 🔎 Search Terms

wrong type in condition typescript

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type checking in conditions

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/GYVwdgxgLglg9mABMAFAQwFyIM5QE4xgDmiAPomCADZUA0iARlrgcWRdVQJSIDeAUIiGIqAUyiIIzfISIBufoOExgiFAEI0iAGTbE6hlyXDhecSDxgFxxCrWajJkxEQBeRnMQB6L4gA8ALTIaDBU2IgA7jBQABaIACoAygBMAMzJyfwAvkA)

### 💻 Code

```ts
function f(a: string | null, b: string | null) {
    let c: string;

    if (!a && !b)
        return;

    if (!a)
        c = b; // <- fails with TS2322
}
```

### 🙁 Actual behavior

Typescript compiler fails with error:
```TS2322: Type 'string | null' is not assignable to type 'string'.   Type 'null' is not assignable to type 'string'.```

In second condition typescript thinks that ```b``` can be ```null``` (even though ```a``` is definitely ```null``` inside this condition). However, if ```b``` was also ```null```, typescript would proceed into the first condition.

### 🙂 Expected behavior

Typescript should recognize such condition flow and should not treat ```b``` as nullable in the second condition. So the code above should be compiled without any errors of type checking

**Comment by MartinJohns** [comment] 2021-12-29 07:55
This sounds like a duplicate of #37258.

**Closed** 2022-01-05 18:00 UTC
Labels: Duplicate
