### ISSUE TITLE
The child class should not be able to access the class field defined by the parent class via super

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#54054] opened 2023-04-28 12:49 UTC
# Bug Report

The child class should not be able to access the class field defined by the parent class via super

### 🔎 Search Terms

class field super parent

### 🕗 Version & Regression Information

Happens on 5.1.0-beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-beta#code/MYGwhgzhAEAq0G8BQ1XQGYEsCmIAm0AvNABQCURAfIgL5J2iQywBM02AHgC7YB2ezRCjTpyQtBOgQArgAdsAJwB0WXHnLDUdOkl7YA7nBbkV5IA)

### 💻 Code

```ts
class T {
    field = () => {}
}
class T2 extends T {
    f() {
        super.field()
//      ~~~~~~~~~~~
    }
}

new T2().f()
```

### 🙁 Actual behavior

No type error

### 🙂 Expected behavior

Type error.

`super` will look for the parent class, but the class field is always defined on the current instance.

**Comment by fatcerberus** [comment] 2023-04-28 13:09
I don’t think the type system can make this distinction of “it’s an instance property of `T` except in cases where `T` is subclassed” so this will likely be closed as a design limitation.

**Comment by Jack-Works** [comment] 2023-04-28 13:59
fix is available

**Comment by Jack-Works** [comment] 2023-04-28 14:00
> I don’t think the type system can make this distinction of “it’s an instance property of `T` except in cases where `T` is accessed through `super`” so this will likely be closed as a design limitation.

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/5390719/235168408-1eff618c-18ed-4b09-86b5-f0a1f34333b8.png">

TypeScript can

**Comment by Josh-Cena** [comment] 2023-04-28 20:56
Duplicate of https://github.com/microsoft/TypeScript/issues/35314

**Closed** 2023-06-03 23:05 UTC
Labels: Duplicate
