### ISSUE TITLE
Refactoring suggtion: convert to namespace import

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24044] opened 2018-05-10 22:53 UTC
## Search Terms
- Refactor
- import

## Suggestion
For the code:

```ts
import { a, b, c} from './xyz';

console.log(a, b, c);
```

Add a refactoring to convert the import to:

```ts
import * as xyz from './xyz';

console.log(xyz.a, xyz.b, xyz.c);
```

With a rename being triggered on `xyz`

## Use Cases
I can see this being useful:

- List of imports become too long and unmanageable.
- Make it clear in code where a name comes from

**Comment by andy-ms** [comment] 2018-05-10 23:43
Related to #22925 -- in my opinion that would be preferrable to have the user specify a # of named imports they'll accept and have them grouped/expanded every time they organize imports. With a refactoring they have to select each import that they want to group/ungroup individually.

**Comment by mjbvz** [comment] 2018-05-11 19:30
Yes managing this automatically would also be nice. However a refactor that I can trigger would also be useful, as there are some module that I always want to use namespace imports for. I originally opened this issue because I noticed myself converting a lot of imports like:

```ts
import {red, green blue} from 'vs/colors';
```

to:

```ts
import * as colors from 'vs/colors'
```

Even when only a single value is used from `vs/colors`, I prefer using the namespace for this module

**Comment by DanielRosenwasser** [comment] 2018-05-17 18:42
Looks like a duplicate of #19260

**Comment by cancerberoSgx** [comment] 2018-05-21 19:11
My humble opinion / question: 
 * If you only provide this refactor and not the reverse one (* to named import) then people might think TypeScript is promoting this kind of imports. Make sure you want to do that or provide the reverse transformation.
 * In [my experience developing typescript refactors](https://github.com/cancerberoSgx/typescript-plugins-of-mine), non named imports like the one you are suggesting could make it harder to navigate the AST for global refactors when you have to refactor imports / exports globally (think for example on refactors like move class to other file, move method to other class/interface, etc)

My two cents

**Closed** 2018-05-30 21:11 UTC
Labels: Awaiting More Feedback, Domain: Refactorings, Fixed, Suggestion
