### ISSUE TITLE
TS may parse type parameter lists as JSX

### ISSUE THREAD

**Issue by AlexStacker** [microsoft/TypeScript#26179] opened 2018-08-03 03:30 UTC
TS may mistakenly use generics as jsx，but it's ok on vscode.

**TypeScript Version:**  3.0.1

**Search Terms:**
jsx generics, class generics

**Code**

```ts
const a = <T = any>(): Array<T> => {
    return;
}
```

**Expected behavior:**

![image](https://user-images.githubusercontent.com/7822744/43622648-dca1664e-970f-11e8-8233-19feacd5e42d.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/7822744/43622677-06c25668-9710-11e8-9a58-c61ae11c6eeb.png)

**Playground Link:** 
compile errror:
https://agentcooper.github.io/typescript-play/?jsx=1#code/MYewdgzgLgBAhjAvDAPAFSfMBPAfACgEoAuGAQQCcK5t1cl6BvAWACgYOYKBTKAVwpgA3GwC+QA

but code on this is [OK ](http://www.typescriptlang.org/play/#src=const%20a%20%3D%20%3CT%20%3D%20any%3E()%3A%20Array%3CT%3E%20%3D%3E%20%7B%0D%0A%20%20%20%20return%3B%0D%0A%7D)

**Comment by basarat** [comment] 2018-08-03 03:55
Its known : https://basarat.gitbooks.io/typescript/content/docs/jsx/react.html#generic-functions 

I'm a user just like you just wanted to state that users have known this in the past :rose:

**Comment by AlexStacker** [comment] 2018-08-03 05:37
@basarat Thank you very much for your reply and solved my doubts. If the official can improve this problem, then I feel would be useful.

**Comment by DanielRosenwasser** [comment] 2018-08-03 15:07
I think we should be able to use lookahead to detect that we definitely have a type parameter list.

**Comment by RyanCavanaugh** [comment] 2018-08-03 15:46
We already do some lookahead to look for a comma after the `<T`; we also look for `=`. Note that `extends` is not a sufficient lookahead becase `<foo extends></foo>` is legal JSX

**Comment by jakebailey** [comment] 2023-07-11 19:29
This was fixed in #47112, so #47062 was a dupe of this one.

**Closed by jakebailey** 2023-07-11 19:29 UTC
Labels: Bug, Domain: JSX/TSX
