### ISSUE TITLE
--strictNullChecks typeguard of dectructured variable does not apply to its original value

### ISSUE THREAD

**Issue by vclav** [Microsoft/TypeScript#11175] opened 2016-09-27 10:30 UTC
**TypeScript Tools for Visual Studio:**  2.0.3.0

**Code**
````
if (someObj.prop) { // typeguard tests property with dot notation
    const { prop } = someObj; // destructure property to variable
    someFnThatDontAcceptUndefined( prop ) // error TS2532 Object possibly 'undefined'
}
```

this also does not work
```
const { prop } = someObj; // destructure
if (prop) { // typeguard test for destructured
    someFnThatDontAcceptUndefined( someObj.prop ) // use with dot notation leads to Error
}
```

**Expected behavior:**
Typeguard of property accesed via dotted notation would also apply to destructured property and vice versa.

**Actual behavior:** 
Properties destructured to variable are not tied to its value accessed via dotted notation and thus typeguard of one of them is not propagated to the other.

**Comment by Arnavion** [comment] 2016-09-27 17:30
Duplicate of #10846 which itself is a duplicate of #10065

**Closed** 2016-09-27 22:29 UTC
