### ISSUE TITLE
Array.concat() 's params wrong!!!

### ISSUE THREAD

**Issue by scp1513** [Microsoft/TypeScript#17447] opened 2017-07-27 09:13 UTC
**TypeScript Version:**  2.4.1

**Code**

```ts
let a: ReadonlyArray<number> = [];
let b: number[] = [];
// compile error
let c = b.concat(a);
// you see Array.concat() doesn't change the params
```

**Expected behavior:**

**Actual behavior:**

**Comment by MrKou47** [comment] 2017-07-27 11:27
```ts
let a: ReadonlyArray<number> = [];
let b: number[] = [];
let c = b.concat([...a]);
```
this will be ok.

**Comment by scp1513** [comment] 2017-07-27 11:36
@MrKou47 It works. thanks.

**Comment by arusakov** [comment] 2017-09-13 13:16
@RyanCavanaugh 
Code example generates error:
```
[ts]
Argument of type 'ReadonlyArray<number>' is not assignable to parameter of type 'number | number[]'.
  Type 'ReadonlyArray<number>' is not assignable to type 'number[]'.
    Property 'push' is missing in type 'ReadonlyArray<number>'.
```

Is it right definition for `push` method for `ReadonlyArray<T>`?
```
push(): never
```
 Also we need the same definitions for other methods, like pop and so on... Am I right?

**Comment by mhegazy** [comment] 2017-09-14 21:29
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by NaridaL** [comment] 2017-09-18 19:02
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/17076 and has been fixed by https://github.com/Microsoft/TypeScript/pull/17806.

**Closed** 2017-09-18 19:14 UTC
Labels: Accepting PRs, Bug, Domain: lib.d.ts
