### ISSUE TITLE
Wrong type on when using logical operators in nested conditions

### ISSUE THREAD

**Issue by SimonSimCity** [microsoft/TypeScript#58802] opened 2024-06-07 17:32 UTC
### 🔎 Search Terms

logical, operator, nested, condition

### 🕗 Version & Regression Information

- This is the behavior in every 5.x-version available on the playground (latest being 5.4.5). I've also tested some older versions, all with the same outcome.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.4.5#code/MYewdgzgLgBATgUwI4FcCWiIDkUFsBGCcMAvDABRgBcMYehcAlKQHy0DcAsAFA+iSwoCaKQoBDGnQJEYAHxgowAEwQAzNGARKANDHyT6M+YpXrNOmMAPTix5Wo1bmJNgG8eMT17Srxc+eT4MABkwZaMzO7cXjEwPhRBsvLAkR6xMQD0GTAAIiAwECC4CFAAFhoA5gB0NWnpAL4wCAA2EAgwUekxiKgYwjg25GKMXNFd9XVeE9z17EA

### 💻 Code

```ts
const requiresNumber = (n: number) => n;

const test = (a: number | undefined, b: number | undefined, c: number | undefined) => {
      if (a || (b && c)) {
        if (b || c) {
          // Do something...
        } else {
          requiresNumber(a);
                      // ^ Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
        }
      }
};
```

### 🙁 Actual behavior

It reports the variable `a` as `number | undefined`, but logically it can only be `number`.

### 🙂 Expected behavior

The variable `a` should be of type `number`.

### Additional information about the issue

It only runs the conditional code if `a` is truthy or `b` and `c`. The only possibility `a` could be `undefined` is when both `b` and `c` are set, which is also when it would enter the second if-condition, as either `b` or `c` are set. By this reasoning, `a` cannot be `undefined` in the else-case of the inner condition.

EDIT:

Funny enough, this works without complaints:
```ts
const requiresNumber = (n: number) => n;

const test = (a: number | undefined, b: number | undefined, c: number | undefined) => {
      if (a || (b && c)) {
        if (!a || (b && c)) throw new Error(); // <- This line was added.

        if (b || c) {
          // Do something...
        } else {
          requiresNumber(a);
        }
      }
};
```

**Comment by MartinJohns** [comment] 2024-06-07 17:49
Duplicate of #56221.

**Closed** 2024-06-10 01:31 UTC
Labels: Duplicate

**Comment by SimonSimCity** [comment] 2024-06-10 10:13
@RyanCavanaugh can we please reconsider closing this issue? I don't understand why adding the negated if-statement is helping it, if the algorithm for detecting the control flow can't narrow it down well enough, as you stated in the linked issue. I'm neither well enough into the algo. Somehow the system seems to be unable to detect `if (a || (b && c)) {}` but it can detect `if (!a || (b && c)) {}`, or do I get something wrong here?
