### ISSUE TITLE
Interface Default Values

### ISSUE THREAD

**Issue by wakaztahir** [microsoft/TypeScript#54979] opened 2023-07-12 03:24 UTC
# Suggestion

This will be a very useful feature If we could provide default values for interfaces , In Kotlin you can already do this using

```kotlin
interface Y {
val x : Int get() = 5
}
```

There's a stackoverflow question for this

https://stackoverflow.com/questions/35074365/typescript-interface-default-values

Syntax doesn't matter in this , as long as the values get declared inside the interfaces , The hacks in the stackoverflow answers feel like something I am not supposed to do , The best hack for this is basically destructuring like this

```typescript
foo({
        a,
        b=1,
        c=99,
        d=88,
        e                    
    }: Arguments)
```

This is not the best way to do this , First I need to declare the interface and then need to put a huge parameter list with default values in a function's definition , which makes it ugly

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

default values, default values interfaces

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Kotlin like default values for interfaces

The best syntax would be , This suggests x default value is "y" and when x value is not given "y" is used
```typescript
export interface AccordionColors {
  x : string = "y"
}
```

## 📃 Motivating Example

Components in React , have a lot of parameters and a lot of them need to be default , Declaring defaults in interfaces would make the process easier and tidier

## 💻 Use Cases

Components in React , have a lot of parameters and a lot of them need to be default , Declaring defaults in interfaces would make the process easier and tidier

This would also remove the need to make optional props like prop ?: string , when prop has a default value , The default can be used instead of no value

**Comment by fatcerberus** [comment] 2023-07-12 03:44
> This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

> This could be implemented without emitting different JS based on the types of the expressions

This needs to emit different values for an object literal depending on the interface used; it is *very much* in the category of type-directed emit and thus violates Non-Goal `#5` from https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals:

> 5. [Do not] Add or rely on run-time type information in programs, or **emit different code based on the results of the type system**. Instead, encourage programming patterns that do not require run-time metadata.

**Comment by fatcerberus** [comment] 2023-07-12 03:51
Seems like a duplicate of https://github.com/microsoft/TypeScript/issues/20391, more or less

**Closed** 2023-07-15 01:35 UTC
Labels: Suggestion, Out of Scope
