### ISSUE TITLE
When checking if two class types are assignable, don't check the assignability of their private member variables

### ISSUE THREAD

**Issue by vanchagreen** [microsoft/TypeScript#49144] opened 2022-05-17 06:17 UTC
# Suggestion

## 🔍 Search Terms

private member variables
assignability
contravariant

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When checking if two class types are assignable, don't check the assignability of their private member variables.

## 📃 Motivating Example
```
class Bag<T> {
    constructor(private fn: (a: T) => any) {}
}

let numberBag : Bag<number>;
let unionBag: Bag<number | string>;

unionBag = numberBag; // invalid, because 'string' is not assignable to 'number'
```
[playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBCYHMA8AVAfNA3gKGn6wA9gHYQAuATgK7BmEUAUADhQJYBuYZAptAGbEAXNAZhhKAJTQAvBjDEAnlMwBfbGuwhuZaMSoBbAEbcK8BNGFmkeoybQBuTduhVirEmcuJrB4xWgAPtDkbMQIDtjYru7EZjK6viZm9tAA9KnQrMScIKwAJgA00MbAYFQQvADkIVkIlZkwxIQ6kBCsCMRghlrQdNCVNn6VkdhkCky8AIIgIIQA7tx5Zijj3DDSCbb+QTVhjthEpDqGiDDCkxQUYApIVtOzC0uIKxMQaBgbANoAuo4nCBAAHRMcoACwYgySiAkjiAA)

I would expect the assignment above to be safe, even though Function types are contravariant in their arguments, because the `fn` member variable is private, and the inner `Bag` code only has access to an arbitrary `T`.

## 💻 Use Cases
The most common use-case I've run into is wanting to have a function in the client code that takes `Bag<unknown>` as a parameter:

```
function clientFn(bag: Bag<unknown>) {}

clientFn(numberBag); // invalid
```

My intent here is for the `clientFn` to explicitly not care about the inner `T`. Note that this could be fixed by using `any`, and while I don't like `any` in general, maybe this could be a good time for it?

Another use-case might be where client code wanted to create a list of Bags, where the `T`s are constrained to an allowable set:

```
// continued from above

type AllowedBagTypes = number | string;

const bags : Array<Bag≤AllowedBagTypes>> = [];
bags.push(numberBag);
```

Note, this can be fixed by changing the `AllowedBagTypes` type to `Bag<number> | Bag<string>`.

One final thing to note is that this `Bag` class breaks the client code only because of the private `fn` member variable. That means that adding such a variable to an otherwise working existing class could unexpectedly break client code.

---

I'm not 100% sure this is actually a safe suggestion, and I'd be very happy to be corrected if I'm wrong! I think most of the use-cases can be fixed by using `any` or by changing the types in the client code around, so this may not be a super valuable suggestion for the effort. But just figured I'd put it out there!

**Comment by jcalz** [comment] 2022-05-17 18:22
Duplicate of or very strongly related to #18499

Private members are visible to other instances of the same class.  If they didn't affect compatibility, things would explode.

```ts
class Bag<T> {
    constructor(private fn: (a: T) => any) { }
    foo() {
        const stringBag: Bag<string> = this; // error, for good reason
        //    ~~~~~~~~~ <-- Type 'Bag<T>' is not assignable to type 'Bag<string>'.
        stringBag.fn("oopsie");
    }
}

new Bag((x: number) => x.toFixed(1)).foo() // 💥 runtime error! x.toFixed is not a function
```
[Playground link to code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBCYHMA8AVAfNA3gKGn6wA9gHYQAuATgK7BmEUAUADhQJYBuYZAptAGbEAXNAZhhKAJTQAvBjDEAnlMzQAvrnx9ChBso358RUmWjk2xBPATCrSM6wsZp0MgAtWEANzQA9D+jcFBT0ADT89NAI2gAm0BTckCT6Br7++AB+mVlZ0EgAtHnQKApMvADktuhl0B7QxIQmkBCsCMRgAEYgvHQuJeW29o5lAHTJBoOWiMMCDABE2kzN3LMSnsnq6tjE3ADucIgMDAAewsRUALbtgVKy0EfDdABirEfc0QwAjBIS09q6qXEqMQyKxzrxAsEKABCO4PQjPV6xWr1Rr8IG0VhJbDY7FAA)

**Closed** 2022-05-20 20:00 UTC
Labels: Working as Intended
