### ISSUE TITLE
Inherited Constructors execute before sub class field initializations

### ISSUE THREAD

**Issue by arciisine** [Microsoft/TypeScript#13525] opened 2017-01-16 22:34 UTC
**TypeScript Version:**  2.1.5

**Code**

```ts
class Base {
  id:string;

  constructor(config:any) { 
      // Given a defined schema object, bind the inbound config to the current 
      //   instance, enforcing types and discarding unused fields
      bindToSchema(ObjectSchemaRegistry.get(this.constructor), this, config);
  }
}

class SubType extends Base {
   name:string = 'basic';
}
```

**Expected behavior:**
`new SubType({ name : 'test' }).name == 'test'`

**Actual behavior:**
`new SubType({ name : 'test' }).name == 'basic'`

The sub class field initialization executes after the base class constructor executes.  I'm not sure if this is 100% desirable but I can understand the reasoning for it.  If this is unchangeable, I would look for some way to execute the `bindToSchema` function after the sub class field initialization has occurred (barring making every use of the constructors call `bindToSchema` manually).

**Comment by vladima** [comment] 2017-01-17 17:45
duplicate of #10634?

**Comment by arciisine** [comment] 2017-01-17 17:50
Sounds like it, didn't come up in my search.  Is there any way to achieve this functionality (calling code after the constructors finish) without changing the order of construction?

**Comment by RyanCavanaugh** [comment] 2017-01-17 18:09
Nope. General pattern here is to have some convention like calling `this.init()` after `super` in the derived class constructors.

**Comment by arciisine** [comment] 2017-01-17 18:21
Understood, it just seems like an anti-pattern to have, what is essentially, a secondary constructor to compensate for the initialization of fields.  

I'm toying with using an inherited static member to act as the constructor (e.g. `Sub.new`, or `Sub.from`), but I'm not sure if relying on inheritance for static members is a good idea either.

**Comment by arciisine** [comment] 2017-01-18 05:00
So, playing around with some solutions, what I'm looking at is:

```ts
class BaseSchema {
  static new<T>(this: new () => T, data: any): T {
    return BindUtil.bindSchema(this, new this(), data);
  }
}
```

This then allows for
```ts
class Person extends BaseSchema {
  name: string = 'bob';
}

let person:Person = Person.new({});
```

**Closed** 2017-04-21 16:56 UTC
Labels: Question
