### ISSUE TITLE
SUGGESTION: more strict checks on write-only properties

### ISSUE THREAD

**Issue by YunHsiao** [microsoft/TypeScript#46039] opened 2021-09-24 03:57 UTC
# Suggestion

## 🔍 Search Terms

write-only properties
strict type check

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Write-only properties have not been the most type-checked area of the language (#21759), but in some cases though we can almost always tell it's not what's intended and throw some error messages in there.

## 📃 Motivating Example

The example below (playground link [here](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210910#code/MYGwhgzhAECC0G8BQ1XQA4CcCWA3MALgKbQD6u0AvNANoAMAugNxIpoREHS53QAUuAFzQAdgFcAtgCMimAJSI2aNAQAW2CADpy9BlW4tlAX1bKA5p2hhMmMAE9+c4QCUiYACYB7ESDsAecWlZGgYAPkVlZUxOMUwRaDUNbVxDNBMTJGBvCC4AD30RIgB3OD45FiRczR59AEY6JmgAeiboLJsiYC4xCDALSureAGpqeqYW6GwRduiu6B6+kj5oiDEQAhgp6AA5MG2IOQAaaCL1YFVoCFVPNfdRTy50SBgCO3QSc86AawBCViyRBBPCAiJoQJ4zHwqtZbHZykggA)) demonstrates a peculiar case that could definitely benefit from some type error messages, but the suitable situations may go well beyond this simple case and are open for discussion. 

```ts
class A {
    private _v = [0];

    set v0 (v: number) {
        this._v[0] = v;
    }

    get array (): Readonly<number[]> {
        return this._v;
    }
}

const x = new A();

x.v0 = 10; // correct usage
x.v0 += 10; // incorrect usage (results in NaNs), which should not pass type check!
```

**Comment by FilipeBeck** [comment] 2021-09-25 20:00
It is also allowing `const v0 = x.v0` without having accessor method

**Comment by andrewbranch** [comment] 2021-09-30 17:22
Duplicate of #21759 (and more directly #30852)—the problem is we don’t recognize this as write-only at all.

**Closed by andrewbranch** 2021-09-30 17:22 UTC
