### ISSUE TITLE
`this` type is not assignable to `NonNullable<this>`

### ISSUE THREAD

**Issue by athasach** [microsoft/TypeScript#22934] opened 2018-03-27 22:35 UTC
**TypeScript Version:**  2.8.1

**Search Terms:**  NonNullable, this

**Code**

```ts
class X {
    fn(): void {
        // Type 'this' is not assignable to type 'NonNullable<this>'.
        //  Type 'X' is not assignable to type 'NonNullable<this>'.
        const x: NonNullable<this> = this;
        //    ~
    }
}
```

**Expected behavior:**

A reference of type `this` should be assignable to a `NonNullable<this>` within a method.

**Actual behavior:**

`this` is not assignable to `NonNullable<this>`.

**Playground Link:**  

http://www.typescriptlang.org/play/#src=class%20X%20%7B%0D%0A%20%20%20%20fn()%3A%20void%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20x%3A%20NonNullable%3Cthis%3E%20%3D%20this%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A

**Related Issues:**

**Comment by aschmois** [comment] 2018-03-27 23:20
That's because a generic is a class definition not an instance. this is an instance. Your code should look like:
```javascript
class X {
    fn(): void {
        const x: NonNullable<X> = this;
    }
}
```

**Comment by RyanCavanaugh** [comment] 2018-03-27 23:44
@sandersn seems like a bug but I might be missing something extra-subtle

**Comment by aschmois** [comment] 2018-03-27 23:53
Why should dynamic objects be allowed as generic definitions?

**Comment by athasach** [comment] 2018-03-28 00:07
I may have whittled down the actual issue I was dealing with too much. Here is an example of the bug I was trying to be succinct with:

```ts
export class Entry<T extends Table> {
    private _table: T | null = null;
    createSubsetForDirectory(): void {
        const entry = new Entry<T>();
        // error TS2345: Argument of type 'Entry<T>' is not assignable to parameter of type 'Entry<NonNullable<T>>'.
        //  Type 'T' is not assignable to type 'NonNullable<T>'.
        //    Type 'Table' is not assignable to type 'NonNullable<T>'.
        this._table!.fn(entry);
        //              ~~~~~
    }
}


export abstract class Table {
    fn(directoryEntry: Entry<this>): this | null {
        return null;
    }
}
```

**Comment by athasach** [comment] 2018-03-28 00:10
@aschmois In this case, I'm using `this` as a polymorphic this type. See http://www.typescriptlang.org/docs/handbook/advanced-types.html#polymorphic-this-types

**Comment by RyanCavanaugh** [comment] 2018-03-28 00:13
@athasach that's actually a much more serious repro as it's a regression from 2.7. That code worked as far back as 2.0

**Comment by ahejlsberg** [comment] 2018-03-28 00:39
Pinging @weswigham. I suspect this is related to #22096.

**Comment by ahejlsberg** [comment] 2018-03-28 00:46
I will say that the current behavior doesn't seem totally wrong. In general, a type parameter `T` isn't assignable to `NonNullable<T>`. Rather, it is the other way around. And, in the specific example, the `this` instance *might* be `null` or `undefined` (although it is pretty unlikely).

**Comment by weswigham** [comment] 2018-03-28 01:08
> Pinging @weswigham. I suspect this is related to #22096.

This is just what falls out from conditional type assignability rules, I suppose. The example in the OP didn't use the `!` operator at all, so it really doesn't have anything to do with changing `!` to also use `NonNullable` (other than providing another place where people and see the behavior):

```ts
class X {
    fn(): void {
        // Type 'this' is not assignable to type 'NonNullable<this>'.
        //  Type 'X' is not assignable to type 'NonNullable<this>'.
        const x: NonNullable<this> = this;
        //    ~
    }
}
```

It seems like the issue is mostly that `NonNullable<T>` where `T`'s domain does not include `null` or `undefined` (because, eg, `T extends Table`) needs to collapse to just `T`, but right now it stays generic. @ahejlsberg I think this is something you changed right before the release actually - making conditional types stay generic more often?

**Comment by ahejlsberg** [comment] 2018-03-28 01:48
Yes, I did make a change where distributive conditional types are always deferred if the checked type is generic, but I think it stayed generic before as well.

It may be that that `!` operator should do a bit more work, i.e. remove `null` and `undefined` that are known to be present (as we used to do) and only return a `NonNullable<T>` if the resulting `T` could actually be nullable (which wouldn't be the case in the example above after we remove explicit `null` and `undefined`). I'm not sure it is feasible to have the `NonNullable<T>` type collapse as you suggest.

**Comment by weswigham** [comment] 2018-03-28 02:16
>  only return a NonNullable<T> if the resulting T could actually be nullable 

I'm pretty sure it'd be correct to (re)build that logic into conditional types in general at that point, since nothing about that logic would be specific to either null or undefined. One of the _motivating examples_ for conditional types is non-null types; it'd be off that `!` could do the right thing but a conditional type couldn't.

And again, the original issue doesn't involve `!` - the postfix operator is just another way to witness the same problem!

**Comment by ahejlsberg** [comment] 2018-03-28 16:36
@weswigham In principle I agree, but devising the exact logic by which this would happen isn't trivial. We currently defer resolution for distributive conditional types when the check type is generic. Even in cases where we know that the check will always go a certain way (e.g. because of a constraint), we *still* need to defer because the generic type may be instantiated to a union type that we want to distribute over. Only when we can conclude that distributing over a union wouldn't affect the outcome can we actually consider resolving early. I think it would pretty much amount to recognizing Exclude- and Extract-like types. It may be worth doing, but building it into the `getNonNullableType` function would definitely be simpler.

**Closed** 2023-07-11 00:10 UTC
Labels: Bug
