### ISSUE TITLE
Netdirect

### ISSUE THREAD

**Issue by ghost** [Microsoft/TypeScript#18594] opened 2017-09-20 12:15 UTC
Please fill the following out:

- Name: Netdirect
- Homepage url: http://www.netdirect.cz
- Brand Guidelines/Licensing: (or anything we need to know before using your logo)
- Logo: (svg if possible, pngs over 500x200px with transparent backgrounds are also acceptable)

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by DanielRosenwasser** [comment] 2017-09-21 09:11
@karolinaneumannova you haven't provided a logo. Can you please do so so that we can add it to our website?

**Comment by mhegazy** [comment] 2017-10-31 05:29
Duplicate of https://github.com/Microsoft/TypeScript/issues/18684

**Closed by mhegazy** 2017-10-31 05:29 UTC
Labels: Website Logo
