### ISSUE TITLE
Unable to Assign Type that Begins With '$$'

### ISSUE THREAD

**Issue by ASA2** [Microsoft/TypeScript#7080] opened 2016-02-14 18:33 UTC
TypeScript in Visual Studio is not allowing a type assignment if the the type begins with '$'. For example:

namespace $$ {
       export enum CUSTOMER_TYPE {
          domestic = 0,
          international = 1 
      }
}

let custType: $$.CUSTOMER_TYPE // <------- CAUSES TYPESCRIPT ERROR IN VISUAL STUDIO.

The '$' is a valid character.

**Comment by Arnavion** [comment] 2016-02-14 19:03
What exactly is the error?

Which version of Visual Studio and TypeScript gives you that error?I don't get any error from TS 1.7 nor TS 1.8 in VS 2015.

**Comment by ASA2** [comment] 2016-02-14 19:27
Getting "cannot find namespace '$$'" in VS 2015 with TS 1.8. The error only
occurs when referencing another namespace (in another file).

This works:

    namespace $$ {

        export enum VIEW_TYPE {

            STACKED = 0,

            TABBED

        }

    }

    let test: $$.VIEW_TYPE;

However, if namespace $$ is another namespace/file I get that error.

On Sun, Feb 14, 2016 at 2:04 PM, Arnav Singh <notifications@github.com>
wrote:

> What exactly is the error?
>
> Which version of Visual Studio and TypeScript gives you that error?I don't
> get any error from TS 1.7 nor TS 1.8 in VS 2015.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/TypeScript/issues/7080#issuecomment-183952315>
> .
>



-- 
*Lee Mellinger*
President & CEO
InfiniSuite, LLC
www.infinisuite.com
Mobile: 1.734.531.8702
Skype: leemellinger
LinkedIn: linkedin.com/in/leemellinger
<https://www.linkedin.com/in/leemellinger>

*Business Solutions for Cloud 2.0*

NOTICE: The information contained in this e-mail, and in any accompanying
documents, may constitute confidential and/or legally privileged
information. The information is intended only for use by the designated
recipient. If you are not the intended recipient (or responsible for the
delivery of the message to the intended recipient), you are hereby notified
that any dissemination, distribution, copying, or other use of, or taking
of any action in reliance on this e-mail is strictly prohibited. If you
have received this e-mail communication in error, please notify the sender
immediately and delete the message from your system.

**Comment by ASA2** [comment] 2016-02-14 20:22
Here's a better example that demonstrates the problem in one file:

var $$$ = test;

namespace test {

    export enum CUSTOMER_TYPE {

        reseller = 0,

        enduser = 1

    }

    // THIS WORKS

    let custType1: CUSTOMER_TYPE;

    // THIS DOES NOT WORK

    let custType2: $$$.CUSTOMER_TYPE;

}

Here's a screen shot:

[image: Inline image 1]



On Sun, Feb 14, 2016 at 2:27 PM, Lee Mellinger <
lee.mellinger@infinisuite.com> wrote:

> Getting "cannot find namespace '$$'" in VS 2015 with TS 1.8. The error
> only occurs when referencing another namespace (in another file).
>
> This works:
>
>     namespace $$ {
>
>         export enum VIEW_TYPE {
>
>             STACKED = 0,
>
>             TABBED
>
>         }
>
>     }
>
>     let test: $$.VIEW_TYPE;
>
> However, if namespace $$ is another namespace/file I get that error.
>
> On Sun, Feb 14, 2016 at 2:04 PM, Arnav Singh <notifications@github.com>
> wrote:
>
>> What exactly is the error?
>>
>> Which version of Visual Studio and TypeScript gives you that error?I
>> don't get any error from TS 1.7 nor TS 1.8 in VS 2015.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Microsoft/TypeScript/issues/7080#issuecomment-183952315>
>> .
>>
>
>
>
> --
> *Lee Mellinger*
> President & CEO
> InfiniSuite, LLC
> www.infinisuite.com
> Mobile: 1.734.531.8702
> Skype: leemellinger
> LinkedIn: linkedin.com/in/leemellinger
> <https://www.linkedin.com/in/leemellinger>
>
> *Business Solutions for Cloud 2.0*
>
> NOTICE: The information contained in this e-mail, and in any accompanying
> documents, may constitute confidential and/or legally privileged
> information. The information is intended only for use by the designated
> recipient. If you are not the intended recipient (or responsible for the
> delivery of the message to the intended recipient), you are hereby notified
> that any dissemination, distribution, copying, or other use of, or taking
> of any action in reliance on this e-mail is strictly prohibited. If you
> have received this e-mail communication in error, please notify the sender
> immediately and delete the message from your system.
>



-- 
*Lee Mellinger*
President & CEO
InfiniSuite, LLC
www.infinisuite.com
Mobile: 1.734.531.8702
Skype: leemellinger
LinkedIn: linkedin.com/in/leemellinger
<https://www.linkedin.com/in/leemellinger>

*Business Solutions for Cloud 2.0*

NOTICE: The information contained in this e-mail, and in any accompanying
documents, may constitute confidential and/or legally privileged
information. The information is intended only for use by the designated
recipient. If you are not the intended recipient (or responsible for the
delivery of the message to the intended recipient), you are hereby notified
that any dissemination, distribution, copying, or other use of, or taking
of any action in reliance on this e-mail is strictly prohibited. If you
have received this e-mail communication in error, please notify the sender
immediately and delete the message from your system.

**Comment by Arnavion** [comment] 2016-02-14 22:28
That has nothing to do with $ in the namespace name.

```typescript
namespace foo {
	export enum A { a };
}

var bar = foo;

var x = bar.A.a; // OK - bar.A is available in value position
var y: foo.A; // OK - foo.A is available in type position
var z: bar.A; // Error - Cannot find namespace bar - bar.A is not available in type position
```

This may or may not be a bug, but I'm also not sure it has anything to do with your original question, since your original question does not have namespaces being assigned with var.

**Comment by ASA2** [comment] 2016-02-14 22:33
Your right. It looks like you've replicated the real issue.  Thx.

On Sun, Feb 14, 2016 at 5:29 PM, Arnav Singh <notifications@github.com>
wrote:

> That has nothing to do with $ in the namespace name.
>
> namespace foo {
>     export enum A { a };
> }
> var bar = foo;
> var x = bar.A.a; // OK - bar.A is available in value positionvar y: foo.A; // OK - foo.A is available in type positionvar z: bar.A; // Error - Cannot find namespace bar - bar.A is not available in type position
>
> This may or may not be a bug, but I'm also not sure it has anything to do
> with your original question, since your original question does not have
> namespaces being assigned with var.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/TypeScript/issues/7080#issuecomment-183993263>
> .
>



-- 
*Lee Mellinger*
President & CEO
InfiniSuite, LLC
www.infinisuite.com
Mobile: 1.734.531.8702
Skype: leemellinger
LinkedIn: linkedin.com/in/leemellinger
<https://www.linkedin.com/in/leemellinger>

*Business Solutions for Cloud 2.0*

NOTICE: The information contained in this e-mail, and in any accompanying
documents, may constitute confidential and/or legally privileged
information. The information is intended only for use by the designated
recipient. If you are not the intended recipient (or responsible for the
delivery of the message to the intended recipient), you are hereby notified
that any dissemination, distribution, copying, or other use of, or taking
of any action in reliance on this e-mail is strictly prohibited. If you
have received this e-mail communication in error, please notify the sender
immediately and delete the message from your system.

**Comment by vladima** [comment] 2016-02-15 05:48
this is by design - variable declaration captures only value meaning of the merged entity. If you need to get all meanings - use `import`

```ts
namespace foo {
    export enum A { a };
}

var bar = foo;
var x = bar.A.a; // OK - bar.A is available in value position
var y: foo.A; // OK - foo.A is available in type position
var z: bar.A; // Error - Cannot find namespace bar - bar.A is not available in type position

import bar1 = foo;
var x = bar1.A.a; // OK - bar1.A is available in value position
var y: foo.A; // OK - foo.A is available in type position
var z: bar1.A; // OK - bar1.A is not available in type position
```

**Closed** 2016-02-16 04:23 UTC
Labels: By Design
