### ISSUE TITLE
Getter on class is present in inferred type from object-spreading instance

### ISSUE THREAD

**Issue by andrewbranch** [Microsoft/TypeScript#26279] opened 2018-08-07 22:27 UTC
**TypeScript Version:**  3.1.0-dev.20180807

**Search Terms:**
- object spread own enumerable
- object spread accessor
- getter object spread

**Code** ([playground](https://www.typescriptlang.org/play/index.html#src=class%20Phone%20%7B%0D%0A%20%20get%20number()%20%7B%0D%0A%20%20%20%20return%201234%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20getNumber()%20%7B%0D%0A%20%20%20%20return%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20phoneInstance%20%3D%20new%20Phone()%3B%0D%0Aconst%20phoneClone%20%3D%20%7B%20...phoneInstance%20%7D%3B))

```ts
class Phone {
  get number() {
    return 1234;
  }

  getNumber() {
    return 1234;
  }
}

const phoneInstance = new Phone();
const phoneClone = { ...phoneInstance };
```

**Expected behavior:**
The inferred type for `phoneClone` should be `{}`

**Actual behavior:**
The inferred type for `phoneClone` is `{ number: number }`

**Playground Link:** [playground](https://www.typescriptlang.org/play/index.html#src=class%20Phone%20%7B%0D%0A%20%20get%20number()%20%7B%0D%0A%20%20%20%20return%201234%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20getNumber()%20%7B%0D%0A%20%20%20%20return%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20phoneInstance%20%3D%20new%20Phone()%3B%0D%0Aconst%20phoneClone%20%3D%20%7B%20...phoneInstance%20%7D%3B)

**Related Issues:** 
- https://github.com/Microsoft/TypeScript/issues/13148
- https://github.com/Microsoft/TypeScript/issues/13409
- https://github.com/Microsoft/TypeScript/issues/24799

---

## Discussion

1. I realize that spreading a class instance is not desirable.
2. I also realize (after searching for dupes and reading similar issues for a couple hours) that there are design limitations around TS not tracking own/enumerable properties.

But, from what I understand, it makes a guess and correctly omits methods on classes from the inferred type of spreading an instance of that class. Since getters on classes are also on the prototype, it seems like inconsistent behavior that _methods_ are omitted from the inferred type but get/set accessors are not. Even though the compiler doesn’t _really_ track what properties are own enumerable, it seems like it could use similar heuristics to determine, in this simple case, that the getter won’t be present on the spread object.

P.S. – thanks for your time, and apologies in advance if this _does_ turn out to be a dupe that I couldn’t find 😬

**Comment by andy-ms** [comment] 2018-08-07 23:57
Duplicate of #24799. That one's still open as a bug.

**Closed** 2018-08-09 22:34 UTC
Labels: Bug, Fixed
