### ISSUE TITLE
Conditions for conditional types of function parameters don't propagate into function bodies

### ISSUE THREAD

**Issue by bb010g** [microsoft/TypeScript#50371] opened 2022-08-19 09:01 UTC
# Bug Report

Even when TypeScript proves that conditional type conditions hold, these proofs aren't fully propagated into the function body.

### 🔎 Search Terms

conditional type propagation witness entails function parameter

### 🕗 Version & Regression Information

- This is the behavior in every version I tried since v3.3.3, and I reviewed the FAQ for entries about conditional type condition propagation

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220819#code/JYOwLgpgTgZghgYwgAgJIBE5jgHgCoB8yA3gFDIXIAmWcAXMnqQL4DcpMAriAmMAPYhkAcwhhM2fMggAPSCCoBnNBNwBVAgBpkGgBQyGeAJQM1JcpShjOUITIB0NbO2alSCADZxFygILJgAFsABw8IQIhwZQxaHAAjfn4wuBAiMkpkBEFFMChOXn4oXWDOOI9gBGpaBgSkiBSjEjYWdk9vZQAhcwyskBy8gqLG4mbXUjAAT2CUAFkJmbhg5ABebsoAIjh1hl9NCwp1uO3kDr3XXpzkQPnFhjmFpdX0ja2GEAgAd2RfXVzOCCMewyh2O7y+pxabi4PD4giuEwAwtlOBEoDgANLSOSRJTIADWEAm-BgyHui20eCx8lxMUkGm0egJEzuN2CAG10QBdKk45SUgD8yExbwgADdoCYdGsKBcwMgAPoMTGrJmsZAAenVyFFcHKVACMBJAAMyeyuTyFHyjftMtk5TqPP9DCt4Q82UzOewMlYwDYhKJxLRdA7-kYXEA)

### 💻 Code

```ts
interface IData<T> {
    data: T
};
function getData<T extends IData<U>, U>(x: T): U {
    return x.data;
}

class A implements IData<boolean> {
    constructor(public data: boolean) {};
};
class B {
    constructor() {};
}

type MyMap = {
    "a": A,
    "b": B,
}
const myMap: MyMap = {
    "a": new A(true),
    "b": new B,
};

function myConsumer<K extends keyof MyMap, T extends IData<U>, U>(key: MyMap[K] extends T ? K : never): U {
    const _: K = key; // valid iff `MyMap[K] extends T`
    const value: T = myMap[key];
    return getData(value);
}
```

### 🙁 Actual behavior

TypeScript fails to type check this code, with the following error:
```
Type 'MyMap[MyMap[K] extends T ? K : never]' is not assignable to type 'T'.
  'T' could be instantiated with an arbitrary type which could be unrelated to 'MyMap[MyMap[K] extends T ? K : never]'.
```

### 🙂 Expected behavior

TypeScript successfully type checks this code. It can already prove that `MyMap[K] extends T` in order to bind `key` with type `K`.

**Comment by MartinJohns** [comment] 2022-08-19 11:46
Resolving of conditional types is deferred when they involve unbound type argumente. This is a design limitation.

**Comment by RyanCavanaugh** [comment] 2022-08-19 20:54
There's not really a great way to describe the sorts of behavior where functions want to talk about "keys `K` of type `T` where `T[K]` is assignable to `U`". You can perform the filtering operation and you can perform the lookup operation but TS doesn't carry over the higher-order information that `K' from keyof K in T where T[K] extends U` means the `T[K']` should behave as an arbitrary subtype of `U`.

See #48992

**Comment by DetachHead** [comment] 2022-09-20 06:01
assuming this is a simpler example of the same issue
```ts
type Foo<T extends string> = T extends string ? T : never

const makeFoo = <T extends string>(value: T): Foo<T> => value // error
```

**Comment by mengdu** [comment] 2023-02-16 06:38
Got a similar error

```ts
function foo<T extends true | false>(arg: T): T extends true ? string : number {
  return arg === true ? 'yes' : 0 // Type 'number' cannot be assigned to type 'T extends true? String: number'. ts(2322)
}
```
How to implement the function of Conditional Types? No example is found in the [document](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html).

**Comment by DetachHead** [comment] 2023-02-16 07:54
@mengdu i believe that's a different issue. it's caused by the fact that narrowing a value with a generic type doesn't necessarily mean it's safe to narrow the generic itself. this can be demonstrated by adding a second argument to your function:

```ts
type Foo<T extends string> = T extends string ? T : never

const makeFoo = <T extends string>(value: T): Foo<T> => value // error

function foo<T extends true | false>(arg: T, arg2: T): T extends true ? string : number {
    if (arg === true) {
        // these two lines have errors, because narrowing arg can't narrow T because it would be unsafe to do so
        const foo: true = arg2 //arg2 can be false
        return 'yes'
    } else {
        return 0
    }
}

foo(true, false)
```

see https://github.com/microsoft/TypeScript/issues/21732#issuecomment-1424824153 for another example

**Closed** 2024-02-24 00:19 UTC
Labels: Design Limitation

**Comment by bb010g** [comment] 2024-03-24 09:50
@RyanCavanaugh The initial test case still fails type check [on 5.5.0-dev.20240324](<https://www.typescriptlang.org/play?ts=5.5.0-dev.20240324#code/JYOwLgpgTgZghgYwgAgJIBE5jgHgCoB8yA3gFDIXIAmWcAXMnqQL4DcpMAriAmMAPYhkAcwhhM2fMggAPSCCoBnNBNwBVAgBpkGgBQyGeAJQM1JcpShjOUITIB0NbO2alSCADZxFygILJgAFsABw8IQIhwZQxaHAAjfn4wuBAiMkpkBEFFMChOXn4oXWDOOI9gBGpaBgSkiBSjEjYWdk9vZQAhcwyskBy8gqLG4mbXUjAAT2CUAFkJmbhg5ABebsoAIjh1hl9NCwp1uO3kDr3XXpzkQPnFhjmFpdX0ja2GEAgAd2RfXVzOCCMewyh2O7y+pxabi4PD4giuEwAwtlOBEoDgANLSOSRJTIADWEAm-BgyHui20eCx8lxMUkGm0egJEzuN2CAG10QBdKk45SUgD8yExbwgADdoCYdGsKBcwMgAPoMTGrJmsZAAenVyFFcHKVACMBJAAMyeyuTyFHyjftMtk5TqPP9DCt4Q82UzOewMlYwDYhKJxLRdA7-kYXEA>). Why was this closed as completed?
