### ISSUE TITLE
Remove tsconfig.json's "scripts" directory assumption

### ISSUE THREAD

**Issue by chrishensel** [Microsoft/TypeScript#6217] opened 2015-12-23 10:05 UTC
Hi, may I ask whether or not this can be made more flexible?

We have a project structure that puts the app's content inside the **wwwroot/app** directory that also contains the HTMLs etc, so having a seperate, forced "scripts" directory which outputs there is nothing more than an (unnecessary?) workaround.

The structure is like the following:
```
- wwwroot
  - app
    app.ts
    - module
      module.ts
      - controllers (*.ts)
      - services (*.ts)
      - views (*.html)
  index.html    
```

It would be great to have the tsconfig.json just in the "app" directory and it then compiles all .ts that are anywhere below that path, like it is the case with the tsconfig right now, however forced to expect them in the "scripts" dir.

Honestly, I think compile-on-save seems unnecessary given the presence of a tsconfig file. The regular way seems way better since when building the project it compiles the TS if missing, compile-on-save seems not to (plus you'd have to expect team members to make sure to enable it and go through all their files).

It would be a great help to be able to drop a tsconfig.json in **any** directory, not just the (seemingly) hard-coded "scripts" directory, or at least being able to adjust this path.

I tested this with the RC 1 Update 1 and it is quite unflexible there. If there is progress made in that area, please let me know.

Thanks in advance and best regards,
chris

**Comment by paulvanbrenk** [comment] 2015-12-23 20:07
This is something we're changing for the next version of the TypeScript tools. See e.g. #4714. So closing this as a duplicate of that more general request.

**Closed by paulvanbrenk** 2015-12-23 20:07 UTC

**Comment by chrishensel** [comment] 2015-12-24 18:36
Hi, thanks for the heads-up! Also thanks for noting the guidelines, I was not aware of that. Could you please point me to the guidelines, so I can read up on the whole **wwwroot** topic?

**Comment by paulvanbrenk** [comment] 2015-12-28 23:11
I don't think there is actually guidance yet.. (I may have to write that myself), but here are some useful docs:

http://docs.asp.net/en/latest/conceptual-overview/understanding-aspnet5-apps.html

https://github.com/Microsoft/TypeScript/wiki/Using-TypeScript-With-ASP.NET-5

**Comment by chrishensel** [comment] 2016-01-07 16:03
Thanks for your response!

Maybe just as a well-meant suggestion for the future, would it be possible for us developers to have a short "best practices" document (or similar), which quickly outlines the most important Do's and Don'ts? 

That's actually something that I'd really like to have, since the way how to use vNext has changed somewhat from alpha stage to now, and especially from the betas to the RC - for example, the use of "wwwroot" is **now** discouraged, but wasn't too long ago :)

In any case, thanks for your efforts and keep it up, I like it!
