### ISSUE TITLE
Typed function allows returning of objects with unknown properties

### ISSUE THREAD

**Issue by mpk** [Microsoft/TypeScript#20718] opened 2017-12-15 08:46 UTC
**TypeScript Version:**  2.6.2

**Code**

```ts
interface TestInterface {
    testValue: boolean;
}

let testFunc: () => TestInterface;

// Compiler allows returning unknown properties
testFunc = function() {
    return { testValue: true, otherValue: 7 };
}

// When the return type is explicitly specified, compiler warns about unknown properties
testFunc = function(): TestInterface {
    return { testValue: true, otherValue: 8 };
}
```

[Playground](https://www.typescriptlang.org/play/#src=interface%20TestInterface%20%7B%0D%0A%20%20%20%20testValue%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Alet%20testFunc%3A%20()%20%3D%3E%20TestInterface%3B%0D%0A%0D%0AtestFunc%20%3D%20function()%20%7B%0D%0A%20%20%20%20return%20%7B%20testValue%3A%20true%2C%20otherValue%3A%207%20%7D%3B%0D%0A%7D%0D%0A%0D%0AtestFunc%20%3D%20function()%3A%20TestInterface%20%7B%0D%0A%20%20%20%20return%20%7B%20testValue%3A%20true%2C%20otherValue%3A%208%20%7D%3B%0D%0A%7D)

**Expected behavior:**
Since the `testFunc` has type annotation that specifies return value `TestInterface`, I expect that I will be able to return only objects with properties specified in `TestInterface`. However, the compiler allows me to return properties not specified in `TestInterface`.

To achieve my expected behavior, I need to explicitly specify the function return value. I think the compiler should be able to infer this from the type annotation.

**Actual behavior:**
Compiler does not complain about unknown object properties.

**Comment by j-oliveras** [comment] 2017-12-15 11:05
This works as intended. See https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-structural-typing

**Comment by RyanCavanaugh** [comment] 2017-12-15 15:07
Duplicate of #7547

**Closed** 2017-12-19 17:47 UTC
Labels: Duplicate
