### ISSUE TITLE
String literal type unexpectedly widened to string

### ISSUE THREAD

**Issue by mspiess** [microsoft/TypeScript#54767] opened 2023-06-25 09:57 UTC
# Bug Report

### 🔎 Search Terms

- string literal type
- widen
- not assignable to

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about mapped types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0&ts=5.1.3#code/C4TwDgpgBAysBOBLAdgcwNIRAeQGYB4AVAPigF4oBRADwGMAbAVwBMJ8BrLAe1ykIBooAZxABbAEZd6xANwAoUJCgApIV2QAFLimAR4RUhUJQI1XcmZCoXcQCsItYHKhQA-FADeUANrooKWAQUDCw8AwBdAC4oAAMAegASD3QAXyTVdS0dPSJfcOIUmKgAH1jE5MKoFO84JDRMHAIScOcoaIBydvk5XEZkR0R1KFp4CABDXQzNbWRdfRIACk4QaNrghrCSAEpoqazZnJJPVpdR4EZ4ZDKk5cL5FKA)

### 💻 Code

```ts
type StringKeyOf<T> = Exclude<keyof T, symbol>;
type JsonPointer<T> = T extends object
  ? { [K in StringKeyOf<T>]: `/${K}${JsonPointer<T[K]>}` | `/${K}` }[StringKeyOf<T>]
  : '';

function createJsonPointer<T>(key: StringKeyOf<T>): JsonPointer<T> {
    return `/${key}`;
}
```

### 🙁 Actual behavior

Following error is emitted because `StringKeyOf<T>` is falsely widened to `string`:
```
Type '`/${string}`' is not assignable to type 'JsonPointer<T>'.
``` 

### 🙂 Expected behavior

I expected the code to type check as it does if the function's type parameter is replaced with a concrete type.

**Comment by MartinJohns** [comment] 2023-06-25 10:42
Duplicate of #33912.

**Comment by RyanCavanaugh** [comment] 2023-06-26 19:27
This is possible with a few workarounds. Critically, your conditional type can't be distributive.
```ts
type StringKeyOf<T> = Exclude<keyof T, symbol>;
type JsonPointer<T> = [T] extends [object]
  ? { [K in StringKeyOf<T>]: `/${K}${JsonPointer<T[K]>}` | `/${K}` }[StringKeyOf<T>]
  : '';

function createJsonPointer<T extends object>(key: StringKeyOf<T>): JsonPointer<T & object> {
    return `/${key}`;
}
```
There's an existing issue tracking the fact that you have to write the meaningless "`T & object`" in the type argument there for this to work

**Closed** 2023-06-29 01:33 UTC
Labels: Duplicate
