### ISSUE TITLE
tsc declaration-emits `any` type for self-referring class expressions

### ISSUE THREAD

**Issue by h-joo** [microsoft/TypeScript#56479] opened 2023-11-21 09:26 UTC
### 🔎 Search Terms

`declaration`, `any`, `class expressions`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 'any'

### ⏯ Playground Link

https://www.typescriptlang.org/play?jsx=0&module=1&ts=5.3.1-rc#code/MYewdgzgLgBAhjAvDYAbOEIwIIwN4BQMxMATgKZwAm4qAnvAFw5IxjkDuOAFAJQDcBAL5A

### 💻 Code

```ts
const a = class A {
    readonly a: A = new A();
}
```

### 🙁 Actual behavior

TSC emits the following declaration (I think due to literal types does not have a recursive representation): 
```ts
declare const a: {
    new (): {
        readonly a: any;
    };
};
```

### 🙂 Expected behavior

Either or both : 
- Whenver TypeScript is trying to print `any` type during declaration emit it should rather be an error.
- This should also be solved when TS is able to express the type of the class expression properly equivalent to class types.  So the actual "Expected behavior" should be decided by the TypeScript team on what the correct solution for these kind of pattern is, but either a solution is to provide a representation for class types, or allowing initializers in declaration emit for class expressions would both solve the issue.

### Additional information about the issue

This was noticed during the development of --IsolatedDeclarations, and we decided to not support declaration emit for class expressions as it was complicated an hacky to replicate what the current TSC is doing.

Related issue in terms of discrepancy between class declaration emit and class expression emit : https://github.com/microsoft/TypeScript/issues/56145

**Comment by fatcerberus** [comment] 2023-11-21 15:00
Kinda-sorta a duplicate of https://github.com/microsoft/TypeScript/issues/55832

**Comment by fatcerberus** [comment] 2023-11-21 15:17
> This should also be solved when TS is able to express the type of the class expression properly equivalent to class types.

That'd be https://github.com/microsoft/TypeScript/issues/41581, though I don't think *this case in particular* would ever be representable since the correct emit would nest forever.

**Comment by jakebailey** [comment] 2023-11-21 19:46
We should really create some sort of mega-issue for the things noted by isolated declarations; deduping them on very old issues is kinda unfortunate without some sort of tracking to indicate that these are very real things we were hoping to fix for isolated declarations and beyond.

**Closed** 2023-11-24 01:27 UTC
Labels: Duplicate
