### ISSUE TITLE
Playground fail to run code

### ISSUE THREAD

**Issue by ofir-zeitoun** [microsoft/TypeScript#51186] opened 2022-10-15 13:54 UTC
Playground is failing to run code. 
Thecode runs on node on vscode.

I get this error:
```
[ERR]: "Executed JavaScript Failed:" 
[ERR]: str.replace is not a function 
```
Code - dynamic builder patter: 
```
type Constructor<T> = new (...args: any[]) => T;

type RequireAtLeastOne<T> = {
  [K in keyof T]-?: Required<Pick<T, K>> &
    Partial<Pick<T, Exclude<keyof T, K>>>;
}[keyof T];

type ExcludeKeys<T, U> = {
  [Key in keyof T]: T[Key] extends U ? never : Key;
}[keyof T] &
  keyof T;

type ExcludeType<T, U> = Pick<T, ExcludeKeys<T, U>>;

type NonFunctionPropsToSetters<T, OrigT, NonFunctions = ExcludeType<T, Function>> = {
  // -? make optional as required, otherwize the function will be optional as well
  // Exclude<T, undefined> removes the undefined, so if you call the setter you should pass the actual value
  [Property in keyof NonFunctions as `set${Capitalize<string & Property>}`]-?: (value: Exclude<NonFunctions[Property], undefined>) => BuilderType<Omit<T, Property>, OrigT>;
};

type BuilderType<T extends {} | Constructor<T>, OrigT = T, NonFunctions = ExcludeType<T, Function>> = 
  NonFunctionPropsToSetters<T, OrigT> & 
    (NonFunctions extends RequireAtLeastOne<T>
    ?  {} : {
        build: () => OrigT;
      }) ;

function getBuilder<T extends {} | Constructor<T>>(
  ctor: Constructor<T>
): BuilderType<T> {
  const fields = new Object() as Record<string, unknown>;
  function build(): T {
    return Object.assign(Object.create(ctor.prototype), fields);
  };

  const builderProxy: BuilderType<T> = new Proxy({} as BuilderType<T>, {
    get: (obj: Record<string, unknown>, prop: string) => {
      if (prop === "build") {
        return build;
      }
      // name is like so: setCapitalizedPropertyName
      const propName = `${prop[3].toLowerCase()}${prop.substring(4)}`;
      return function (value: unknown): BuilderType<T> {
        console.log(`set ${value} into ${prop}`);
        fields[propName] = value;
        return builderProxy;
      };
    }
  }) as BuilderType<T>;
  return builderProxy;
}

class User {
  firstName!: string;
  lastName?: string;
  birthDate?: Date;

  constructor() {}

  print() {
    console.log(this.firstName);
    console.log(this.lastName);
    console.log(this.birthDate);
  }
}
const b1 = getBuilder(User);
const res1 = b1.setFirstName("aa").build();

console.log("b1: ", b1);
console.log("res1: ", res1);

res1.print();
const res2 = b1.setFirstName("a").build();
res2.print();
b1.setBirthDate(new Date()).setFirstName("aa").build().print();
```
[Playground link](https://www.typescriptlang.org/play?ts=4.8.4&ssl=107&ssc=33&pln=105&pc=1#code/FAFwngDgpgBAwgewHYGcQCcCuBjED0A8AKgHwwC8MSUA7jABQB0zAhugOYoBcMLSYAbQC6ASgpkiAbmChIsAEpQAjpgCW6KAEEQAGSgs0AeWrEylAN7AYMAQGkYqpDADWUMAgBmMIkIC0Afh5FFXUoABMCAAVVbGdiABoYWxIyADIraxhIthBVFgAbKJi4okSAUQAPbHzMMKgCV3cvUqSUkmkAXwFGz28haVloGErq2qhbNxQEmABVMxhLazs3Byce5qEeImWwIRgoCpAoJDCUWZh-KigANyh0GB4JsE7ut16fGHTrde8B8CGRjU6kQ5NM5hQssVpoCxk8pi05u0ZP9YAA5ZAAMUwSFwqmQkXQCAgKCICAAylAQEd0PDEoZ0Kp2C10UgsTjcsgzpQYcDQS02bjkCkIYsYAB6MUwAIwAC2LFcMCJHKQBV4Zw0IQ0YUSCBAAAs7jRVAAvWD62AebGCpxG-L5GAAI1gSrxKvtBhgNCgdoyEuGVSB9Ra2LqHkc4TIGhlCFuZ3NMBDUDD1G1MBQCAcXncmBg2AK9vjKEp1Jg2bTeoQmHyYRgEAMcYNvFwmFV1wKmCgGQEBKJd3Aqxcby8LIFyrOHoABkWQAAScxwFgQVQgAom+poBlIdifLKE6DocAkDoTvyBBhtmpQHg8+ojq1j7t7vu7RKJ5MRsTkMgAITU1buILQAQhgysu0w9vuh50gyTJIh0fxyDAv6qP+6CAUG+yHMcpwLB0MAAD7wJyGA4HghCkNBjJEBCzKYverpcv6oy8kB-L0UK8wZHe7KuhBJLksWdy0jA9JUWkMAZNY9DcdaZwHEcJxnMEagaNoegGCAxhBiQkkXNY5h4TwoqZJkDp-mEPD0J+ZCiUy0gmdYHRiAMfookh5kAaCwB+tY1HydhZwGQRRGoCRuD4KY8TeZK1i2dRlClNFmQyWOEI3uh0yjq6Ol+vMKUMZhCk4cpoRqfoRgmKQSXWJc+X4nu-EUlSQnTHFZB+nKJwsGRYC1k+B6qFAKDVQ8MB1UgfGkk11LCW14qSi6yCqhA-W5ENI2pPpI0mWZKEWQw1kiTBUjbTA8EyK5iHIahGUjX5WGKbhwWIKFWDheRJBRT5R1UTRX0xWNdE8ZyaUBmMGVscDSA5ZKeVA7JhUBTAJWqbo5WaZVMOZJcI2WN9JkdXwYTdfgvUrb2A3rfjmSPhT-aOIOTSA6y7GoGqMBTpSc4LkuK75GuBCnSZG6ONum0Qc+QswEeJ4BJZUvWH60pygqi1uuzGoqeEOrmugRqmjA8aWlDnoofaTqKhAyqqh6Xo+tTBOSkN-NICAvhhKoKAsA6+RQL41CHL4LuwEgCC+NimBFmEvhtjSCswBeHY8ONKC05BuxS4d111GhoIgWBLQSweYCfT9sHSNTHQjUZUu7dWlmHXFFcA45O54y3mR+mry2rYNw0OzYRf02sQ7M1lIOTtO3OLsuq6moLA-WCLW47kPYBSzLp7y4v837CgLtux7Xs+37Adu8HVBhxHUcx2w-cdyZidXmPrOp2vQiZ+I7l7Z5QH5yA4FVol0ouXU650krG2tDADwhIZSmHoCiHgL0NykQihRVYEBMAgB4AgB0AArKAuARBbAWCNDQIBMDoCcIYfBhCQCMHrIyJA9AaEENwIwbAGhupQAQXIRg5M8AohEIkRwmCQAiGbmdGQkDlQwHYJSbOdxiCI0ekFQiyCwpkVMCQegGR3pIOIm9LRVViHfxunyMgopsDEWgYNasjFqB0FYXQqy7NFDWPQBEZe7BXxIGcKHGg0N7LQNZo6cyVkSHGRgOQyh1DaHsMYewZhzj2GcP0Eceg71+GEkEXIYRtjvSnAkRkcB1hrGhTCT-dAPYKhgB4Io3OrF5iON3AgWp9AgoegaRDUuUT5HYIYLgvBQRCH4C8RgUWvj-EIECaXcmEAeDeMOlE6wqgvD0HmRQcglAABEdcwg7LECszIMSqGVOrMEkyVcHK7xVDKWAnsYD8wVOmRZlIeaz35qaMIa9UQsHubpMpNj5l-PuRCCcc55kCAAMxCEYHgHQMy7gLiLFZDokK9yMBQJgB03j6AABYRDHkuScyksSQkm3oE-Hg2JpmBNMd0ixpCblAtQAgX2jB8gIHYPQTmIAYBzifnhRweABXmHmceYpLKCn2IECC-5UA9iUCfiSkypynD7LuDU54gKzokuuWdMQXSPKNO0sE9V5yc7as6DIao9ZZhFnuKKMMNIQCgqgAAQkWRMrcwT8gaXdWebxwSHTqH1AAEW4WeSNRwBispQe9VxBkZDWBWiKpNulynpg5Vynl+pPaMBdWgd1UrMhZvZVATl3KEF6gLf64tCrS3xorVWvNtaUCMFDQePUMaoClqrlXLN-KHQAEYIT9IafQGYjrilDuiUNMdlBR1YspBidQDb7n0B2SwFghzO3hOKcActObq17JHTwHZiRR2zs5C23NW6NAoHPTAS986n2HsfSO7J6ab0VMfQAJghMu6ca7XXuq3bukQ+69pWWkAB79rtYPAGAwosNPbuH0Bab2qyUGQPrrdQqiDkHoPVisghkAsGgA)

**Comment by ofir-zeitoun** [comment] 2022-10-15 14:01
opened an issue in [Typescript-Website](https://github.com/microsoft/TypeScript-Website/issues/2567)

**Comment by MartinJohns** [comment] 2022-10-15 14:05
The playground has special logic behind `console.log()` to display objects as JSON (and other types). This collides with your proxy object.

**Comment by ofir-zeitoun** [comment] 2022-10-15 14:18
> 

this line: `"console.log(`set ${value} into ${prop}`);"` prints perfectlly

**Comment by MartinJohns** [comment] 2022-10-15 14:18
A simplified repo:

```typescript
const p = new Proxy({}, {
  get(t, p) {
    return t
  }
});

console.log(p);
```

A duplicate of or at least heavily related: https://github.com/microsoft/TypeScript-Website/issues/2356

**Comment by ofir-zeitoun** [comment] 2022-10-15 14:21
> A simplified repo:
> 
> ```ts
> const p = new Proxy({}, {
>   get(t, p) {
>     return t
>   }
> });
> 
> console.log(p);
> ```
> 
> A duplicate of or at least heavily related: [microsoft/TypeScript-Website#2356](https://github.com/microsoft/TypeScript-Website/issues/2356)

removed the console.log... it works :thinking:

**Comment by MartinJohns** [comment] 2022-10-15 14:24
Yes, like I said: The playground replaces / extends the original `console.log` in order to show the logs on the right side of the playground, and objects get special treatment.

**Comment by ofir-zeitoun** [comment] 2022-10-15 14:58
> 

So, how to override this?

**Closed** 2022-10-15 14:58 UTC
