### ISSUE TITLE
Plugin `create` and `onConfigurationChanged` config-confusion

### ISSUE THREAD

**Issue by manuth** [microsoft/TypeScript#37470] opened 2020-03-19 01:36 UTC
**TypeScript Version:**  3.7.x-dev.20200318

**Search Terms:**
* Plugin
* Configuration
* Global Plugin

**Code**
https://github.com/manuth/TypeScriptESLintPlugin/tree/2e55e4533755ec6cadce9b980e23c140494a1ddf

```ts
export = ({ typescript }) => {
    return {
        create: (createInfo) => {
            console.log(createInfo.config);
        },
        onConfigurationChanged: (config) => {
            console.log(config);
        }
}
```

When working with local plugins only, each time I update the `tsconfig.json`-file, `create` is invoked with its `createInfo.config` set to the configuration I set in the `tsconfig.json`-file.

When enabling the plugin globally, `creationInfo.config` is set to the `tsconfig.json`-file only the very first time. In all consequent invokations the `createInfo.config`-object looks as followed:
```
{ name: "typescript-eslint-plugin" }
```

It gets overwritten at this piece of code:
https://github.com/microsoft/TypeScript/blob/ba39113ab9cb58c03dcb3a2d2729f1b6bb01957d/src/server/project.ts#L1470-L1475

**Expected behavior:**
I'd expect TypeScript to invoke `onConfigurationChanged` each time a global configuration (a config-override) changes and to invoke `create` each time the plugin changes in `tsconfig.json` with `createInfo.config` set to the configuration inside the `tsconfig.json` file.

**Actual behavior:**
Though `onConfigurationChanged` is invoked each time a global configuration changes and `create` is called each time the `tsconfig.json`-file changes, the `createInfo.config`-object only contains the `tsconfig.json`-settings the very first time. That way I cannot load future changes that are made to the `tsconfig.json`.

**Comment by sheetalkamat** [comment] 2021-01-05 20:15
Duplicate of #28969

**Closed by sheetalkamat** 2021-01-05 20:15 UTC
Labels: Needs Investigation, Rescheduled
