### ISSUE TITLE
Assignments inside a lambda function ignored by strictNullChecks

### ISSUE THREAD

**Issue by rustane** [Microsoft/TypeScript#15766] opened 2017-05-11 15:25 UTC
**TypeScript Version:**  2.3.2

**Code**

```ts
let sum:(null|number) = null;
let numvals:number = 0;
let seriesGroup:number[] = [1];

_.each(seriesGroup, (metric:number) => {
    if (sum == null) sum = 0;
    sum += metric;
    numvals ++;
});

//statements that throw error TS2362:
if (sum!=null && numvals > 0) sum = sum / numvals;

//working code.
//if (numvals > 0 && sum == null) sum = 0; 
//if (sum!=null && numvals > 0) sum = sum / numvals;


```

**Expected behavior:**
After enabling the --strictNullChecks flag sum is seen as always being null instead of a number. Apparently due to assignment inside a lambda expression not being seen by the typescript compiler. NOTE: working code comment demonstrates assignment outside of the lambda produces the desired result. 

**Actual behavior:**
a typescript error is thrown by the typescript compiler.

$ tsc --strictNullChecks edstest.ts 
test.ts(13,37): error TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.
$ tsc --strictNullChecks edstest.ts

**Comment by andy-ms** [comment] 2017-05-11 15:51
This code *does* work if you use `let sum: number | undefined;` instead of `let sum:(null|number) = null;`.
But if you have an explicit initializer it looks like TypeScript's control flow thinks it's still `null` at the bottom, so after checking `sum!=null`, `sum` is of type `never`.

**Comment by mhegazy** [comment] 2017-05-11 16:48
Duplicate of https://github.com/Microsoft/TypeScript/issues/9998

**Comment by mhegazy** [comment] 2017-05-25 19:39
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-05-25 19:39 UTC
Labels: Duplicate
