### ISSUE TITLE
Intersection of type parameter and undefined is not never in 4.9

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#51041] opened 2022-10-03 12:47 UTC
# Bug Report

### 🔎 Search Terms

intersection never

### 🕗 Version & Regression Information

- This changed between versions 4.9.0-dev.20220914 and 4.9.0-dev.20220915

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220914#code/C4TwDgpgBAggQlAvFARDFUA+q4oFB4BmArgHYDGwAlgPalQAeAPACoD68UEDwEpAJgGdYcAHwAKAJRQA3nigKoAGwjAoAJwBMALiikIANwjqke4kqUBCKAENh7TgDIoZfhEJV9-AgF8oQA)

### 💻 Code

```ts
type AB = "A" | "B"

function x<T_AB extends AB>() {
    let r2: never = null! as T_AB & undefined

} 
```

### 🙁 Actual behavior

The assignment of `r2` fails with `Type 'T_AB & undefined' is not assignable to type 'never'.`. Since `T_AB` does not contain `undefined` in its constraint, the intersection should reduce to `never` (as it did in 4.8)

### 🙂 Expected behavior

The assignment should succeed.

**Comment by DanielRosenwasser** [comment] 2022-10-03 19:06
This does not fail though.

```ts
type AB = "A" | "B"

function f<T extends AB>(x: T & undefined) {
    let r2: never = x;
} 
```

I'm not sure how exactly it manifests, but the root cause is likely #50735 since that's [the only impactful PR that was merged on the 14th](https://github.com/microsoft/TypeScript/pulls?q=is%3Apr+is%3Aclosed+merged%3A2022-09-14). #50755 came a day before, but likely unrelated.

**Closed** 2022-10-19 22:46 UTC
Labels: Bug, Needs Investigation, Fix Available
