### ISSUE TITLE
exporting object and importing object property declared with jsdoc @enum leads to 'declared but its value is never read' 

### ISSUE THREAD

**Issue by gaurav5430** [microsoft/TypeScript#35348] opened 2019-11-24 18:07 UTC
*TS Template added by @mjbvz*

**TypeScript Version**: 3.8.0-dev.20191125

**Search Terms**
- jsdoc
- enum
- unused

*Original report below*

--- 

**repo**
1. create a file and export a variable with jsdoc enum annotation
`constants.js`
```
/**
 * @enum {string}
 */
const testString = {
  one: "1",
  two: "2"
};

export { testString };
```

2. import the variable using destructuring in another file and console.log it.
```
import { testString } from "./constants"; 
console.log(testString);
```

The above code leads to:
`'testString' is declared but its value is never read.`

The below works fine:
remove the @enum annotation.
OR
export the variable directly and not through an object
`export const testString = { ... }`

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
gitlens|eam|10.2.0
prettier-vscode|esb|3.9.0
git-graph|mhu|1.18.0
debugger-for-chrome|msj|4.12.1
react-proptypes-intellisense|OfH|1.0.3

</details>

**Comment by mjbvz** [comment] 2019-11-26 03:56
#35347 is a possible root cause of this but I want to make sure this problem is also verified

**Comment by elibarzilay** [comment] 2021-06-15 19:22
@gaurav5430, I tried to repro this now and didn't see any errors.  I used the two files from your example (`constants.js` and `index.js`) in an otherwise empty directory.  I used `--noEmit --allowJs index.js` and that worked fine.  I tried it with several versions down to v3.6.5, but all worked fine.

**Comment by elibarzilay** [comment] 2021-06-28 14:31
@gaurav5430: I'm going to close this since I couldn't find any way to reproduce it.  If you do have a way to recreate it, then please re-open it and ping me.

**Closed by elibarzilay** 2021-06-28 14:31 UTC
Labels: Bug, Rescheduled

**Comment by gaurav5430** [comment] 2021-06-28 21:18
Sure, thanks for investigating.

this was a minor inconvenience for some time and then it just disappeared with some vscode update I think.
