### ISSUE TITLE
Inconsistent truthiness narrowing involving never-return typed functions

### ISSUE THREAD

**Issue by tbonnke** [microsoft/TypeScript#47639] opened 2022-01-27 11:02 UTC
# Bug Report

The truthiness-narrowing involving a condition calling a `never`-return typed function seems inconsistent. Depending on whether the invoked function with `never`-return type is:

1. a class member of the *invoking* class
2. a class member of a new, *in-place instantiated instance*
3. a global function 

...the truthiness-narrowing of the involved type either works (case 1+3) or fails (case 2) for the subsequent code following the condition. (See code and playground below, sorry if code might have been even more concise).

### 🔎 Search Terms

* truthiness narrowing
* control flow analysis
* type narrowing
* Object is probably undefined

### 🕗 Version & Regression Information

Not sure if it's a regression, it rather seems like the general behaviour for "two of three cases" was introduced between 3.6.2 and 3.7.5:

  * `<= v3.6.2`: all three variants `defect()`, `works1()`, `works2()` fail with `Object possibly undefined`
  * `>= v3.7.5`: only `defect()` fails to compile

### ⏯ Playground Link

* [Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.7.5#code/PTAEAUCcFMAcGcBQBLAdgF2pAZgQwMbSgDCA9htAB7qgDeo2ppAXKKgK4C2ARlgNygAvokTZ2qfOmTlQAc2joyFagAoAlK3EATaNjTQtoAD4lymanVAx07SKgHDR4ydNSh0AC0ikA7gCEATyVzdHVWVGgANyw6RFB49y9fNmgfUABRSG9IdT5ER3wAG1x4eAys0kgoUlhcWVx0Stj4z29-ILMqUI0U6MhmhJak9uCu3LihfJEQUAAlOG8tdhdyRCKSsoBlUk5oABlSWWR8WIn42G9MSQNQLGzq2vrGyFZM++9HhqaAXhS0t8qDzqXxyajyZ1AOmw0EkYVAkVIyEMtAhg3w5HgNEklFAv3kik6qjBIkGg2Q2FAKgAhNi1ANSaSZgARUjQeCoADkNFQuAqaXQAVgRGw3k4oA5owsJm0un0Wg57lI4sl6AV5EKAVRDL+5XeNWBz3UADpWr5AirxtrJlr4uTKTT0JQ6SirYNmaz2Vy2Ly2u5BURoMhPFgbaT0ahMaBYLidQCqh8DZVxqHBrATcNzYTunkrY4rbhClhQtijYxSGDQDMACoedhlO6VAA0oAARAB5bgAKxhNGQZVgpFKyG4GtAMr0ES0Leb2NAmOQhUKoFIFIFQuVWeMY9QULlHIheYSPkqAGt4ABGOEIpH0sMYrGOmP4i3E0N26m029WmYAOR9vjQWRQGPSAzxTBJPD7I0G3jfUnkqdM2kzZRs1DQ8GQLIsVBLMsKxmNsT1wAJm1QJULlIEdoE4GdHx8EpvT5G4tF8NxGg3FC1VQDUDxJI9T3gAAmK9EWRUNw0jWc8QUF9wStd8HSdL9tV-f8fEA4D+PAoYkI6FDLW1dDSUwyBi0dUsmDwsACKIkiyO8SjqNAWc6LKHlGMMZifFYpUJSzTjuMGYRhCAA)

### 💻 Code

```ts
// Preps
interface Context { foo: number; }

function getContext(): undefined | Context { return; }

function throwByContext(): never {
    throw new Error();
}

class ErrorPropagator {
  throwByContext(): never {
      throwByContext();
  }
}

// Reproduction
class SomeLogic {

    protected errorPropagator: ErrorPropagator = new ErrorPropagator();

    defect(): void {
        const ctx = getContext();

        if (!ctx) {
            // Would expect this condition to narrow type of ctx to 'Context' only
            new ErrorPropagator().throwByContext();
        }

        if (!ctx) {
            // Would expect this condition to narrow type of ctx to 'Context' only, too
            const p = new ErrorPropagator();

            p.throwByContext();
        }

        alert(ctx.foo); // Error, Object is possibly undefined, ctx still of type 'Context | undefined'
    }

    works1(): void {
        const ctx = getContext();

        if (!ctx) {
            // Narrowing works
            this.errorPropagator.throwByContext();
        }

        alert(ctx.foo); // Okay, no problem, ctx was narrowed down to 'Context' only
    }

    works2(): void {
        const ctx = getContext();

        if (!ctx) {
            // Narrowing works
            throwByContext();
        }

        alert(ctx.foo); // Okay, no problem, ctx was narrowed down to 'Context' only
    }
}
```

### 🙁 Actual behavior

- `defect()`-member fails to compile, while `works1()` and `works2()` compile fine

### 🙂 Expected behavior

- IMO the `defect()`-member should also compile, because in terms of control flow and type analysis, the relevant narrowing `never`-return type is  the same for all three variants, but it only seem to work for two

**Comment by MartinJohns** [comment] 2022-01-27 11:08
Duplicate of #36753.

**Comment by tbonnke** [comment] 2022-01-27 11:11
Oh, failed to find that one, @MartinJohns, thank you for pointing out that fast, and sorry for the inconvenience.

**Closed** 2022-01-27 11:12 UTC
