### ISSUE TITLE
Incorrect union type narrowing with literal types

### ISSUE THREAD

**Issue by DCzajkowski** [microsoft/TypeScript#45661] opened 2021-08-31 16:51 UTC
# Bug Report

### 🔎 Search Terms

narrowing, union types, if branches.

### 🕗 Version & Regression Information

- This is not a crash
- This changed between versions 4.1.5 and 4.4.2 (works better, but still wrong)
- This is the behavior in every version I tried, and I reviewed the FAQ
- I was unable to test this on prior versions because I used the playground

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.4.2#code/C4TwDgpgBAShDOYD2A7eEBiSA2ATCATlALwBQUFUAPlAN7mWMUCWuAXFPMAcygOYBuBowC+w6nXFMorDlx78h0xgDdC8Zqg4oArgFsARoSVMRQ0vgDG2AIYFol1Fyj3ETiBzhu0mHPgIA2gC65qCQUFh4hCTiNPTKlLKc3LyCUkxqBBqoAPwcOij4AGa8ELgmorGSCSzsyQppNVCZ2SgcAEwVlGakpAD0AFQD5ANQACoAFszwUEU2zNgzNjMQAB6QlsBlUAAUAOQtmih7UEhFUGHQAAa6hoRXMjMoSMBQyxp8KDYG2NDASBdwNd2lcAJQAOhGfV6jjQryKfnUAEYOJF-MESC4EMgfOC9DYwDsdgiogRQSQAHzVSj2YA6AgoWaIghCESg8yDYZQUaTaZQXBIBBQZ7w+bYGSMgAs4KR4IArLsAO5TSwTR5QRUEVB8AA0MmAexmwAm0HgNj00GWbwMSDUoL1Bh0ooWM14UGl0vakO50NIsOcJP88HaqOZGOIWO86DxBKJgcI5OIVPiiXOOwARIdUOmJUzSVAAGQFvP+cFZxnEStQdrklPSWn0xnxlniMTiBsMkvGUhsjlDEbjKYzAVCkWzMW5j3g9pKlVqvma7V65gGo0mzjmy0zK7N+BIq56gBWOmcmpXW0ZuGYRSKhAgKGA2BAEKhMKc8OZ8AAzKHSeHIzi0b4oSxLMomybiNeuyZuoRw5m6za1ukFAdk2zJdG2jCoV2La9qQQA)

### 💻 Code

```ts
type ResponseFolder =
    | {
          id: string;
      }
    | {
          id: string;
          version: number;
      };

declare const response: ResponseFolder[];

type GenericFolder =
    | {
          id: string;
          version?: undefined;
      }
    | {
          id: string;
          version: 2;
      };

/**
 * This fails as expected ('version' of type `number` is not assignable to type `2`).
 */

const folders1: GenericFolder[] = response.map((folder) => {
    return folder;
});

/**
 * This does not fail in 4.1.5 (which is wrong, it's the same as above), but fails in 4.4.2.
 */

const folders2: GenericFolder[] = response.map((folder) => {
    if ("version" in folder && folder.version === 2) {
        return folder;
    }

    return folder;
});

/**
 * This does not fail in 4.4.2 (which is wrong, it's the same as `folders1`, just written differently).
 */

const folders3: GenericFolder[] = response.map((folder) => {
    if ("version" in folder) {
        return folder;
    }

    return folder;
});
```

### 🙁 Actual behavior

`folders3` assignment does not throw a compile error.

### 🙂 Expected behavior

`folders3` should fail on compilation, because `version` of type `number | <missing prop>` should not be assignable to version of type `2 | optional undefined`.

**Comment by MartinJohns** [comment] 2021-08-31 17:09
I believe this is a duplicate of #34975.

**Comment by DCzajkowski** [comment] 2021-08-31 18:22
I think the main problem in the case of this issue @MartinJohns is `return folder;` and `return "version" in folder ? folder : folder;` are identical, but TS interprets them differently.

**Comment by andrewbranch** [comment] 2021-08-31 23:14
This actually looks separate from the well-known `in` unsoundness... in the `if` block, `folder` shows up as `{ id: string, version: number }`, and after the block it shows up as `{ id: string }`. The unsoundness we expect is already apparent in that narrowing. But there’s something much more subtle going on here. The return type of the `map` callback is contextually typed by the `Folder[]` annotation on the const declaration, but its return type is not, in the end, `Folder`. The return type comes from the subtype reduction of the two return statements: `{ id: string, version: number } | { id: string }` reduces to `{ id: string }`, so the return of the `map` function is `{ id: string }[]` which is assignable to `Folder[]`.

I guess the unsoundness really at play here is just the one about aliasing and excess properties: [playground](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true&ts=4.4.2#code/C4TwDgpgBAYg9gGwCYQE5QLwCgq6gHygG8c8zcBLJALigGdhUKA7AcwG5Ty8A3NOinGYB+WgFdmKAGYsISTtwC+XAsRXcqtBkzYLuvfoOa0ATHrKLOWBBGBRmcYPGRpMxKJqgAiAIYAjAGMvABooPlQBIVovQF4NwAwdryhLLGtbKAArMQYAQWYASRp3T20WViS3BydEFFQrGzsparRaZxq3TJz8+SwgA). I don’t think this issue tells us anything we didn’t already know, but this was a pretty insidious example and it took me a minute to figure it out. It’s definitely not great. @MartinJohns got any more related/duplicates we can cross-reference with my analysis? 😁

**Comment by DCzajkowski** [comment] 2021-09-01 07:36
Oh, I get it now. Thank you for the in-depth analysis @andrewbranch. This was very invaluable to me.

As I understand in these cases it's safer to just type the callback's return type, not const's type (or both for a good measure).

```ts
const folders = response.map((folder): Folder => { /* ... */ })
```

In my mind this issue can be closed 🙂

**Closed** 2021-09-08 00:00 UTC
Labels: Question
