### ISSUE TITLE
Inappropriate string literal completions in object literals

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#11232] opened 2016-09-28 23:24 UTC
Found in https://github.com/Microsoft/vscode/issues/12667

```ts
var foo;

interface I {
    metadata: string;
    wat: string;
}

var x: I = {
    metadata: "/*$*/"
}
```

**Expected:** Completions of every identifier in the file, or no completions at all.
**Actual:** Completions of property names for the containing object literal's apparent type.

![image](https://cloud.githubusercontent.com/assets/972891/18935846/a42f9ed8-8597-11e6-8536-7451e5c3757c.png)

**Comment by mhegazy** [comment] 2016-09-29 05:28
https://github.com/Microsoft/TypeScript/issues/11044 seems like another duplicate of this issue

**Comment by DanielRosenwasser** [comment] 2016-10-02 20:11
That looks to me like an independent issue. `.` shouldn't be a completion character in that context, but should in others.

**Closed** 2016-10-06 00:02 UTC
Labels: Bug, VS Code Tracked
