### ISSUE TITLE
Inconsistent order in unions between tuple values 

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#45144] opened 2021-07-22 09:49 UTC
# Bug Report

### 🕗 Version & Regression Information

ts stable & nightly

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgjFAvFA2nAuighgOxOgbimJNJIHpyo4BYAKFElgCYlU4AaKZzXfIsqUrcoAH2r1G0GAGY2aLsy4zeeQoKjC54hOOaTw0gCzzO3ZVyOr+QqiZ1iR4mQaYwArKcUWoRru+t1YU8HPUdtXyA)
    
### 💻 Code

```ts
// The last comes first

type T1 = [1][any];             // 1
type T2 = [1, 2][any];          // 2 | 1
type T3 = [1, 2, 3][any];       // 3 | 1 | 2
type T4 = [1, 2, 3, 4][any];    // 4 | 1 | 2 | 3
type T5 = [1, 2, 3, 4, 5][any]; // 5 | 1 | 2 | 3 | 4
```

### 🙁 Actual behavior

In this snippet, a Tuple's last member always comes first in unions between its values

### 🙂 Expected behavior

```ts
type T2 = [1, 2, 3][any]; // 1 | 2 | 3
```

**Comment by MartinJohns** [comment] 2021-07-22 10:28
Essentially a duplicate of #17944.

**Closed** 2021-07-24 18:00 UTC
Labels: Duplicate
