### ISSUE TITLE
Inferred type shows up incorrectly in error messages and on hover (but type checking seems to be okay)

### ISSUE THREAD

**Issue by univerio** [Microsoft/TypeScript#21638] opened 2018-02-05 19:58 UTC
**TypeScript Version:**  2.7.1, 2.8.0-dev.20180204

**Search Terms:** type inference, indexed type

**Code**

```ts
declare function foo<T>(attrs: {[K in keyof T]: T[K]}): T;
let res = foo({id: ""});
res = foo({id: 1});
```

**Expected behavior:**

The error should be (as in 2.6)

```
index.ts(3,1): error TS2322: Type '{ id: number; }' is not assignable to type '{ id: string; }'.
  Types of property 'id' are incompatible.
    Type 'number' is not assignable to type 'string'.
```

**Actual behavior:**

The error is

```
index.ts(3,1): error TS2719: Type '{ id: any; }' is not assignable to type '{ id: any; }'. Two different types with this name exist, but they are unrelated.
  Types of property 'id' are incompatible.
    Type 'number' is not assignable to type 'string'.
```

And the reported type on hover is also not correct

![image](https://user-images.githubusercontent.com/1037172/35825749-a195e0a6-0a6b-11e8-81d2-69b08c521136.png)

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=declare%20function%20foo%3CT%3E(attrs%3A%20%7B%5BK%20in%20keyof%20T%5D%3A%20T%5BK%5D%7D)%3A%20T%3B%0D%0Alet%20res%20%3D%20foo(%7Bid%3A%20%22%22%7D)%3B%0D%0Ares%20%3D%20foo(%7Bid%3A%201%7D)%3B)

**Related Issues:**

**Comment by weswigham** [comment] 2018-02-06 21:28
Maybe a duplicate of #21382? It's very similar, at least.

**Comment by weswigham** [comment] 2018-02-06 21:35
Wait, no @mhegazy this is just the expected behavior for a deferred inferred type - right @sandersn?

**Comment by sandersn** [comment] 2018-02-06 21:58
Yes, I have a fix at #21311. Please review!

**Comment by sandersn** [comment] 2018-02-06 21:58
It's 50% smaller now that the display builder is gone, too.

**Comment by weswigham** [comment] 2018-02-27 23:08
@sandersn This issue should be marked as fixed now, right?

**Comment by sandersn** [comment] 2018-02-27 23:10
Yes. Good catch.

**Closed by sandersn** 2018-02-27 23:10 UTC
Labels: Bug
