### ISSUE TITLE
Union type doesn't match the description in the Handbook

### ISSUE THREAD

**Issue by cnshenj** [microsoft/TypeScript#51062] opened 2022-10-04 21:21 UTC
# Bug Report

### 🔎 Search Terms
union; widen; type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about union.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20221004#code/C4TwDgpgBAglC8UDeUCGAuKA7ArgWwCMIAnKAXwG4AoUSKAIQWSgM10JPOqoGMB7LAGdgaTHEQoMUAAwAaFpgCMXXgOEKGTSZjkbllVUJGpWsKAB9NE0TPmn91IA)

### 💻 Code
The [Handbook](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#defining-a-union-type) describes the union type:

> A union type is a type formed from two or more other types, representing values that may be _**any one of those types**_.

This means if we define `type T = A | B`, then its value can be any of `A`'s values, or any of `B`'s values. It implicitly means that if a value is not of type `A` or `B`, it is not a valid `T` value.

However, the code below shows that the same value is considered not `A`  and not `B`, but is `A | B`. This contradicts the Handbook. One of them needs to changed to match the other. To me, the Handbook seems to make more sense.

```ts
type A = { a: number };
type B = { b: number };

const a: A = { a: 0, b: 1 }; // Error, "b" not allowed
const b: B = { a: 0, b: 1 }; // Error, "a" not allowed
const ab: A | B = { a: 0, b: 1 }; // No error, although the value is not a valid A or B
```

### 🙁 Actual behavior

A value of `A | B` can be neither `A` nor `B`.

### 🙂 Expected behavior

A value of `A | B` should be either `A` or `B`.

**Comment by IllusionMH** [comment] 2022-10-04 22:20
Looks like duplicate of #20863

**Comment by MartinJohns** [comment] 2022-10-04 22:20
Duplicate of #20863.

The expected behavior is the actual behavior. Your value is both `A` and `B`, so it's also `A | B`. Excess property checks are more of a linter feature, but are not involved in the types.

**Comment by cnshenj** [comment] 2022-10-05 01:40
The explanation makes sense. Although it is not clear from the error that it is "regular" error or "linter" error.
A related question, I'm afraid there is probably already a duplicate but I can't find it:
```ts
type A = { a: number };
type B = { b: string };

function isA(value: A | B): value is A {
    return "a" in value;
}

function foo<T extends A | B, K extends keyof T>(value: T, key: K) {
    if (isA(value)) {
        value["a"] + 1; // OK, value["a"] is number
        value[key] + 1; // Error. What type should key be to make this line valid?
    }
}
```

**Comment by fatcerberus** [comment] 2022-10-05 02:48
> Although it is not clear from the error that it is "regular" error or "linter" error.

This error being misleading is one of my pet peeves (it says “not assignable” which is not strictly true when just looking at the types involved), but the full error text does hint at what’s really wrong:

> Object literal can only specify known properties

…meaning the assignment was rejected because you tried to assign a fresh object literal with too many properties for the type it’s being assigned to.  This check only applies to directly-assigned object literals; a regular type error will not include this text.  It is meant to 1) catch typos and 2) prevent you from specifying properties that you’ll immediately lose access to.

**Closed** 2022-10-07 20:00 UTC
Labels: Working as Intended
