### ISSUE TITLE
StrictNull check Tuple overflow

### ISSUE THREAD

**Issue by sebdoucet** [Microsoft/TypeScript#18253] opened 2017-09-05 16:20 UTC
**TypeScript Version:**  2.4.1

**Code**

```ts
const tuple: [string, number] = ["", 0];
const value = tuple[2];
```

**Expected behavior:**
Not compiling. You cant define a type based on what is currently define in the array.
This behavior broke the strict null check validation because this value should be undefined or the accessor non legit.

**Actual behavior:**
Compile and `value` as the type of all types defined in the tuple, in this case `string | number`.

**Comment by imcotton** [comment] 2017-09-05 16:47
> When accessing an element outside the set of known indices, a union type is used instead

from: [handbook#tuple](https://www.typescriptlang.org/docs/handbook/basic-types.html#tuple)

**Comment by sebdoucet** [comment] 2017-09-05 16:59
Because it's in the hanbook, that does not make more cense to me.

Why it's not at least a tuple combine with undefined. It broke strict null checking like `string | number | undefined`

**Comment by mhegazy** [comment] 2017-09-05 22:51
Duplicate of https://github.com/Microsoft/TypeScript/issues/6229

**Comment by mhegazy** [comment] 2017-09-20 20:04
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-20 20:04 UTC
Labels: Duplicate
