### ISSUE TITLE
TypeScript 2.3 does not import static member from classes 

### ISSUE THREAD

**Issue by jquintozamora** [Microsoft/TypeScript#15721] opened 2017-05-10 09:39 UTC
**TypeScript Version:**  2.3.1 and 2.3.2

**Actual behavior:**
I did update my project from TypeScript 2.2 to 2.3.1 (and 2.3.2) and I observed some missed imports from static members of classes.

**Code**
This is how I create and export the static members:
```ts
export class ViewerItemCardType {
    public static Big: ViewerItemCardType = new ViewerItemCardType(1, "big", 330, 660);
    public static Small: ViewerItemCardType = new ViewerItemCardType(3, "small", 100, 200);
    private constructor(
        public id: number,
        public name: string,
        public imageHeight: number,
        public imageWidth: number
    ) { }
}
```
Which is converted using TSC into:
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ViewerItemCardType = (function () {
    function ViewerItemCardType(id, name, imageHeight, imageWidth) {
        this.id = id;
        this.name = name;
        this.imageHeight = imageHeight;
        this.imageWidth = imageWidth;
    }
    return ViewerItemCardType;
}());
ViewerItemCardType.Big = new ViewerItemCardType(1, "big", 330, 660);
ViewerItemCardType.Small = new ViewerItemCardType(3, "small", 100, 200);
exports.ViewerItemCardType = ViewerItemCardType;
```

Here is how I import and use the static members:
```ts
import * as React from "react";
import ViewerItem from "../ViewerItem/ViewerItem";

import {ViewerItemCardType} from "../ViewerItem/ViewerItemCardType";

import { IViewerProps } from "./IViewerProps";
class Viewer extends React.Component<IViewerProps, {}> {
    public render() {
        const { id, article } = this.props;
        return (
            <ViewerItem {...article} typeSingleton={ViewerItemCardType.Big} />
        );
    }
}
export default Viewer;
```

Here is the code generated by TypeScript (which actually is missing the import).
Note that the generated code is trying to call ViewerItemCardType_1.ViewerItemCardType.Big but the variable ViewerItemCardType_1 wasn't actually imported properly.
```js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __assign = (this && this.__assign) || Object.assign || function(t) {
    for (var s, i = 1, n = arguments.length; i < n; i++) {
        s = arguments[i];
        for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
            t[p] = s[p];
    }
    return t;
};
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var ViewerItem_1 = require("../ViewerItem/ViewerItem");
var Viewer = (function (_super) {
    __extends(Viewer, _super);
    function Viewer() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Viewer.prototype.render = function () {
        var _a = this.props, id = _a.id, article = _a.article;
        return (React.createElement(ViewerItem_1.default, __assign({}, article, { typeSingleton: ViewerItemCardType_1.ViewerItemCardType.Big })));
    };
    return Viewer;
}(React.Component));
exports.default = Viewer;
```

My tsconfig:
```js
{
    "compilerOptions": {
        "target": "es5",                          
        "module": "commonjs",                     
        "jsx": "react",                          
        "declaration": false,                   
        "sourceMap": true,                        
        "strict": true,                          
        "typeRoots": [
            "./node_modules/@types"
        ],                                        
        "types": [
            "node",
            "react",
            "react-dom"
        ]                                        
    }
}
```

**Expected behavior:**
Create the variable ViewerItemCardType_1 in the generated js file. It was working fine in TypeScript 2.2.

Thanks!

**Comment by mhegazy** [comment] 2017-05-10 19:08
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/15469. should be fixed in `typescript@next` and in the next TS 2.3.3 release next week. 

can you give `typescript@next` a try and see if you are still running into issues?

**Closed** 2017-05-11 09:02 UTC
Labels: Duplicate
