### ISSUE TITLE
No error for duplicate type if one is exported

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#32216] opened 2019-07-02 13:22 UTC
**TypeScript Version:**  3.5.2

**Search Terms:** exported export duplicate type

**Code**

```ts
export type MyObject = {
    foo: string;
};

// Expected: error due to duplicate
// Actual: no error
type MyObject = {
    bar: string;
};
```

**Comment by falsandtru** [comment] 2019-07-04 11:07
Duplicate of #21913

**Comment by Andarist** [comment] 2023-02-13 10:51
This was fixed in 3.8. The issue can be closed.

**Closed** 2023-02-13 12:51 UTC
Labels: Bug
