### ISSUE TITLE
Add an option to preserve function names in generated JavaScript code

### ISSUE THREAD

**Issue by beevik** [Microsoft/TypeScript#14054] opened 2017-02-14 00:23 UTC
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Suggested feature**

Add a command-line option to preserve the names of class methods in generated JavaScript code.

**Detailed description**

Currently, when you compile something like the following TypeScript program:

```
class Foo {
    Bar(): void {}
}
```

it generates the following JavaScript:
```
var Foo = (function () {
    function Foo() {
    }
    Foo.prototype.Bar = function () { };
    return Foo;
}());
```

As you can see, the `Bar` method is declared as an anonymous function.

It would be nice if there were a compiler option (e.g., `--preserveFunctionNames`) that caused the compiler to generate the following code instead:
```
var Foo = (function () {
    function Foo() {
    }
    Foo.prototype.Bar = function Bar() { };
    return Foo;
}());
```

This change would make it possible to do proper inspection of function names at run-time. 

This is currently coming up as an issue on a project I'm working on. I'm attempting to integrate a JavaScript debugger (duktape's), and there's no way I can see to obtain the names of the methods currently on the call stack. Because of the way TypeScript generates code, the function names all show up as 'anonymous'.

**Comment by RyanCavanaugh** [comment] 2017-02-14 00:54
This is actually an ES6 spec compliance problem since ES6 class method names do get populated as expected. We won't be able to emit this when the name isn't a legal identifier but that should be rare

**Comment by mhegazy** [comment] 2017-02-14 05:18
Duplicate of https://github.com/Microsoft/TypeScript/issues/5611

**Closed** 2017-04-21 16:31 UTC
Labels: Duplicate
