### ISSUE TITLE
Compiler v2.1.4 generates erroneous JS code for class constructor

### ISSUE THREAD

**Issue by markvandenbrink** [Microsoft/TypeScript#12906] opened 2016-12-14 09:06 UTC
**TypeScript Version:**  2.1.4 (also tested with 2.2.0-dev.20161214)

**Code**

```ts
class A {
    constructor(fnSomething: () => void) {
        fnSomething();
    }
}

class B extends A {
    constructor() {
        super(() => {
            // Do something with `this`
            console.dir(this);
        });
    }
}
```

**Expected behavior:**
Since `this` is referenced within a function which is supplied as argument to the super constructor, the compiler cannot determine if `this` would be available when the function is invoked. So it should compile to the following valid ES5 JS code (which is the case before `v2.1.4`):

```js
function B() {
  var _this = this;
  return _super.call(this, function () {
    // Do something with `this`
    console.dir(_this);
  }) || this;
}
```

**Actual behavior:**
TypeScript 2.1.4 generates the following **invalid** ES5 code (`var _this = this;` is missing):
```js
function B() {
  return _super.call(this, function () {
    // Do something with `this`
    console.dir(_this);
  }) || this;
}
```

TypeScript 2.0.8 and lower generates the following **valid** ES5 code:
```js
function B() {
  var _this = this;
  _super.call(this, function () {
    // Do something with `this`
    console.dir(_this);
  });
}
```

**Comment by dardino** [comment] 2016-12-14 12:13
I have found a similar [issue](https://github.com/Microsoft/TypeScript/issues/12909)

**Comment by markvandenbrink** [comment] 2016-12-14 12:36
I think `SuperCaptureResult.ReplaceWithReturn` needs a review to address #12906 and #12909.

See:
https://github.com/Microsoft/TypeScript/blob/master/src/compiler/transformers/es2015.ts#L1006

I think the immediate return is not possible and should be:

```ts
var _this;
_this = _super.call(...) || this;
return _this;
```

**Comment by mhegazy** [comment] 2016-12-14 20:01
Duplicate of https://github.com/Microsoft/TypeScript/issues/12764

**Closed** 2016-12-14 20:02 UTC
Labels: Duplicate
