### ISSUE TITLE
Object access is allowed only with string literals when type is defined with { [key: string] ... }

### ISSUE THREAD

**Issue by micnic** [Microsoft/TypeScript#9930] opened 2016-07-25 15:41 UTC
**TypeScript Version:**  1.8.10

**Code**

```ts
let obj: { [key: string]: number } = {};

obj.prop = 123; // Property 'prop' does not exist on type '{ [key: string]: number; }'.

obj['prop'] = 123; // works fine
```

**Expected behavior**:
It's expected to be able to access the object properties by either way, string literal or property name, when the type is defined with `{ [key: string] ... }`

**Actual behavior**:
It's possible to access the object property only with the string literal when the type is defined with `{ [key: string] ... }`

**Comment by sandersn** [comment] 2016-07-25 16:02
This is a duplicate of #8859.

**Closed by sandersn** 2016-07-25 16:02 UTC
