### ISSUE TITLE
super call in an subclass arrow function property needs type error (prevents a runtime error)

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#49317] opened 2022-05-31 05:12 UTC
# Bug Report

### 🔎 Search Terms

super call subclass arrow function 

### 🕗 Version & Regression Information

- This is a crash (runtime, with no type error)
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _________

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ1oFsCmAXAFvACbQC80AFAJRkB8K6G0w8AdhPCNgHQjwDmFAOQJ43HAWJCqjAL6p5qUJBgAhMACdo2AB65srIjFEMMEwiXLU6pphACuAB2wbxeC9YD0n6AGVC9iAkAEbY0GDQuACeztoaGvAaADTQocBg9hBhBACWMABmYDkgMGC40Br2rLg5ONyMGCzsnDx8giKIbpJE0nIKqKis2ADu0Ooa1F0eVEA)

### 💻 Code

```ts
class Foo {
  method = () => {
    console.log('Foo.method')
  }
}

class Bar extends Foo {
  method = () => {
    super.method() // Should be a type error, because this fails at runtime.
    console.log('Foo.method')
  }
}

new Bar().method()
```

### 🙁 Actual behavior

No type error, but there is a runtime error. Here's the error in Chrome:

```js
TypeError: (intermediate value).method is not a function
```

### 🙂 Expected behavior

TypeScript can show a type error for this case.

**Comment by MartinJohns** [comment] 2022-05-31 05:44
Duplicate of #24678. Used search terms: `super property in:title`

**Comment by MartinJohns** [comment] 2022-05-31 05:44
Duplicate of #24678. Used search terms: `super property in:title`

**Comment by RyanCavanaugh** [comment] 2022-06-02 20:12
Same as #42214

**Closed** 2022-06-05 18:00 UTC
Labels: Duplicate
