### ISSUE TITLE
Record from noUncheckedIndexedAccess: false can't be expressed when noUncheckedIndexedAccess: true

### ISSUE THREAD

**Issue by safareli** [microsoft/TypeScript#48917] opened 2022-05-02 16:48 UTC
# Suggestion

Like with  ways for adding and removing optionality form properties `?/-`  there seams to be a need to remove the special undefinedness of properties introduced in noUncheckedIndexedAccess:true

## 🔍 Search Terms

noUncheckedIndexedAccess Record Array

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

With `noUncheckedIndexedAccess:false` we have a notion of `Record` that defines values, for all the possible properties. In practice there are not many actual values like that. Point of`noUncheckedIndexedAccess:true` was to automatically add `| undefined` type to result of property access so we are more type-safe automatically. 

The main TypeSafe use-case for the records which do have value for any possible key are Proxies. And looks like we have lost a way to express the those properly with `noUncheckedIndexedAccess:true`

## 💻 Use Cases
Imagine 
```ts
const val = new Proxy<{[k in string]: string}>({}, {
  get: (_, p) => p.toString().toUpperCase()
});

const foo = val.foo
```

with `noUncheckedIndexedAccess:false`, typer of `foo` is `string` tho with `noUncheckedIndexedAccess:true`, `foo` has type: `string | undefined` which is not correct.  here we know 100% that any value we read from `val`  via property access, must be `string`, but it can't be expressed using Typescript when `noUncheckedIndexedAccess:true`.

We can visualize what we lost using this table:

```
| noUncheckedIndexedAccess:false | Record<string,string> | Record<string,string | undefiend> | 
| noUncheckedIndexedAccess:true  | _____________________ | Record<string,string>             |
```

**Comment by jcalz** [comment] 2022-05-03 17:16
You note that, in practice, such proxy-all-the-things values are rare.  That seems to imply that this suggestion would only rarely help people.  Am I missing something?

**Comment by andrewbranch** [comment] 2022-05-03 18:12
Duplicate of https://github.com/microsoft/TypeScript/issues/47594

Also related: https://github.com/microsoft/TypeScript/issues/46969#issuecomment-984083995

**Comment by safareli** [comment] 2022-05-03 19:32
that kind of proxy might not be that common tho opting out from `noUncheckedIndexedAccess:true` per type level us usefull. i.e. you want noUncheckedIndexedAccess:true for 99% of the types but for some you don't. good use case for this is  importing class names from scss/css module file in react code

**Closed** 2022-05-06 18:00 UTC
Labels: Duplicate
