### ISSUE TITLE
Ts report a wrong comparison when a variable may be changed async.

### ISSUE THREAD

**Issue by HuberTRoy** [microsoft/TypeScript#57927] opened 2024-03-25 06:31 UTC
### 🔎 Search Terms

searched `This comparison appears to be unintentional because the types ... have no overlap.ts(2367)`

### 🕗 Version & Regression Information

ts: 5.3.2

### 💻 Code

      let acceptOrCancel: 'pending' | 'cancel' | 'pass' = 'pending';
      

      // I use antd Modal.
      Modal.confirm({
       ....
        onOk: () => {
          acceptOrCancel = 'pass';
        },
        onCancel: () => {
          acceptOrCancel = 'cancel';
        },
      });

      await waitForSomething({ func: () => acceptOrCancel !== 'pending' });
      
     // This comparison appears to be unintentional because the types '"pending"' and '"cancel"' have no overlap.ts(2367)
      if (acceptOrCancel === 'cancel') {
        return {
          status: false,
          msg: 'user reject sign',
        };
      }

### 🙁 Actual behavior

`Modal.confirm` will make a modal for user to ask if accept or not, It's async actually, but the function will return immediately. I have declare the type of the variable possible values and wait until the variable change, but Ts also report the error `This comparison appears to be unintentional because the types '"pending"' and '"cancel"' have no overlap.ts(2367)`

### 🙂 Expected behavior

Ts don't report the error.

**Comment by MartinJohns** [comment] 2024-03-25 06:39
Another duplicate of #9998.

**Comment by HuberTRoy** [comment] 2024-03-25 07:05
@MartinJohns 

So it's expected? Close the issue or not?

**Comment by MartinJohns** [comment] 2024-03-25 10:49
It's working as intended, yes. You can either close it yourself, or a TypeScript team member will mark this issue as duplicate and the bot will close it (or they close it directly).

**Closed** 2024-03-26 02:39 UTC
Labels: Duplicate
