### ISSUE TITLE
IntelliSense/autocomplete doesn't work for object keys

### ISSUE THREAD

**Issue by woophi** [microsoft/TypeScript#48984] opened 2022-05-06 06:00 UTC
# Bug Report

### 🔎 Search Terms
generics object keys, autocomplete

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ 
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/MYewdgzgLgBBCmAbewoH0BmYYF4YB4AVAGhgGkZ4APKeMAEwhgGt4BPEDGQgPgAp6AQyiCy7AFzkAlLh4wA3jAC+AbgBQa0JFgJkqTGDQB3AJZQAFmiEjcBEuUo06jFu07d+1wZPtexbSTIZHDlFVQ0oNgAHeBgAYRAAW0TwAHkAIwArW3k1GHzKZES6KAhJaAAnEzAAcwBtAF1iPIKTekkwAFdE9PgK9QKYMEFi8qgq2vUlDS1oGGAMzMkE5LSsnJb8pHhisFLJRubBtskARiOC4dGYAHIbtWm1XRR0LHwVlLBF0hvt3dKbvxfkUShAbjIAPQQmBGEAVZhMUrzcwoZgwdyRGIQJ7bfRvD5rTI-QF8O6Q6FgEAwQSdKAgUCJKLIWgaZ54wymCxWYSCPgLLI-P6g8EwKEwuEImAYarwNRAA)

### 💻 Code

```ts
const select_fn = <T, K extends keyof T>(dataKey: K) => { };

const select_fn_with_data = <T, K extends keyof T>(data: T, dataKey: K) => { };

type CommonObj = {
    elements: string[],
    id: number;
    name: string;
}

const cObj: CommonObj = {
    elements: [],
    id: 1,
    name: ''
}

select_fn<CommonObj, 'elements'>('elements') // works ts check of types
select_fn<CommonObj, ''>('') // no autocomplete, but shows error - Type '""' does not satisfy the constraint 'keyof CommonObj'

select_fn_with_data(cObj, 'elements') // works fine
```

### 🙁 Actual behavior

no keys in autocomplete

### 🙂 Expected behavior

when I provide an object type to the first generic param, I expect that autocomplete works and shows keys in the second generic param.

**Comment by MartinJohns** [comment] 2022-05-06 07:27
Sounds like a duplicate of #28662.

**Closed** 2022-05-08 18:00 UTC
Labels: Duplicate
