### ISSUE TITLE
inconsistent default type of empty array

### ISSUE THREAD

**Issue by dnalborczyk** [microsoft/TypeScript#46711] opened 2021-11-06 15:39 UTC
# Bug Report

empty array variables have a different default type depending if they are exported or not.

### 🕗 Version & Regression Information

typescript 4.4.4.

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=99#code/DYUwLgBAZg9jEF4IG0C6AoWMB0AHArgM4AWAFAIwCU66IAHrjAE6QDGMAdoZAEYCGTRCgz8meImSpA

https://www.typescriptlang.org/play?strictNullChecks=false&target=99#code/MYewdgzgLgBAZiEMC8MDaBdAUAkA6ABwFcIALACgEYBKLLAUwA8CQAnWUSWAIwENWU6bH1aESFGkA

### 💻 Code

```ts
// strict null check and noImplicitAny
const foo = [] // foo is type any[]
foo.push(1) // ok

export const bar = [] // bar is type never[]
bar.push(1) // Argument of type 'number' is not assignable to parameter of type 'never'.(2345)

// with noImplicitAny and no strict null
const foo = [] // foo is type any[]
foo.push(1) // ok

export const bar = [] // error: Variable 'bar' implicitly has an 'any[]' type.
bar.push(1)
```

### 🙁 Actual behavior

see code comments

### 🙂 Expected behavior

should use consistent default type for `vars` and `exported vars`.

**Comment by MartinJohns** [comment] 2021-11-06 17:19
Duplicate of #36987. Used search terms: `array empty in:title`

**Comment by dnalborczyk** [comment] 2021-11-06 18:31
> Duplicate of #36987. Used search terms: `array empty in:title`

I see I missed to bring my point across between all these different behaviors.

my initial issue was that the default types are different between `vars` and `exported vars`.

**Comment by andrewbranch** [comment] 2021-11-09 23:08
We don’t do auto array types for ambient or exported variables.

**Closed** 2021-11-12 20:00 UTC
Labels: Working as Intended
