### ISSUE TITLE
ES Module imports discarded when they include a type and a side-effect

### ISSUE THREAD

**Issue by KeithHenry** [Microsoft/TypeScript#28285] opened 2018-11-01 15:25 UTC
When an ES module syntax import has an explicit type and a side effect it is excluded from the output JS.

**TypeScript Version:**  3.2.0-dev.20181101

**Search Terms:**
- ES Modules
- Module resolution

**Code**
- `tsconfig.json` target ESNext
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext"
  }
}
```

- `source-component.ts` with an `export` and a side effect
```ts
export class SourceComponent extends HTMLElement {
    // Web component implementation   
}
customElements.define('source-component', SourceComponent);
```

- `missing-import.ts` that references the dependency as a type _and_ expects the side effect
```ts
import {SourceComponent} from './source-component.js';
const example = document.createElement('source-component') as SourceComponent;
```

**Expected behaviour:**

When output to `missing-import.js` the reference should be retained:
```js
import {SourceComponent} from './source-component.js';
const example = document.createElement('source-component');
```

An import as a side effect would be acceptable too:
```js
import './source-component.js';
const example = document.createElement('source-component');
```

**Actual behaviour:**

The `import` is stripped out:
```js
const example = document.createElement('source-component');
```

**Workaround:** 
Duplicate side effect `import` statements are retained:
```ts
import {SourceComponent} from './source-component.js';
import './source-component.js';
const example = document.createElement('source-component') as SourceComponent;
```

**Comment by weswigham** [comment] 2018-11-01 18:00
Duplicate of #9191 I imagine.

**Closed** 2018-11-01 18:04 UTC
Labels: Duplicate

**Comment by KeithHenry** [comment] 2018-11-01 22:41
@weswigham Certainly looks like it, only this is explicit ESNext modules and #9191 is referencing `require` - I assume that means a fix for `require` would be a fix for ESNext modules?

Only `require` is doing some mapping and ES Modules aren't - I think there's potentially a _much_ easier fix for this as for ESNext modules in TS you _have_ to include the `.js` suffix, so:

```
import { MyComponent } from './my-component'; // gets definition from my-component.d.ts
import { OtherComponent } from './other-component.js'; // doesn't need to check, always include in JS output
```

#9191 has been sitting round for _years_ without a fix because finding out whether the reference includes a side effect is incredibly difficult.

However this could be fixed by adding a special case for ESNext when an explicit `.js` file extension is present.

As a fix for this wouldn't necessarily be a fix for #9191 does this still count as a duplicate? Especially as #9191 is _never_ going to get fixed (`require` will get deprecated first) and ES Modules will become the standard?

**Comment by weswigham** [comment] 2018-11-01 23:35
Even if the import includes `.js` extension, we still look up an associated `.d.ts` file, and you might still only use the types from it. The presence of an extension doesn't change anything, really.

**Comment by KeithHenry** [comment] 2018-11-03 02:01
@weswigham yes, so for TS the extension is optional, but for JS missing the extension will throw an error. The _only_ reason to include the extension in TS is because you want the `import` to work in the JS output, and in that case you always want to retain it.

Imports with explicit `.js` extensions should _always_ be in the output.
