### ISSUE TITLE
Duplicate Documentation for `Float32Array`

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15883] opened 2017-05-16 18:20 UTC
From: https://github.com/Microsoft/vscode/issues/26762

**TypeScript Version:**  2.3.3-insiders.20170512

**Code**

```ts
Float32Array
```

Request `completionEntryDetails` for `Float32Array`

**bug**
Duplicate documentation is returned:

```
[Trace  - 11:16:33 AM] Sending request: completionEntryDetails (135). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/sand/mytsfile.ts",
    "line": 1,
    "offset": 13,
    "entryNames": [
        "Float32Array"
    ]
}
[Trace  - 11:16:33 AM] Response received: completionEntryDetails (135). Request took 2 ms. Success: true 
Result: [
    {
        "name": "Float32Array",
        "kindModifiers": "declare",
        "kind": "const",
        "displayParts": [
            {
                "text": "interface",
                "kind": "keyword"
            },
            {
                "text": " ",
                "kind": "space"
            },
            {
                "text": "Float32Array",
                "kind": "localName"
            },
            {
                "text": "\n",
                "kind": "lineBreak"
            },
            {
                "text": "const",
                "kind": "keyword"
            },
            {
                "text": " ",
                "kind": "space"
            },
            {
                "text": "Float32Array",
                "kind": "localName"
            },
            {
                "text": ":",
                "kind": "punctuation"
            },
            {
                "text": " ",
                "kind": "space"
            },
            {
                "text": "Float32ArrayConstructor",
                "kind": "interfaceName"
            }
        ],
        "documentation": [
            {
                "text": "A typed array of 32-bit float values. The contents are initialized to 0. If the requested number\nof bytes could not be allocated an exception is raised.",
                "kind": "text"
            },
            {
                "text": "\n",
                "kind": "lineBreak"
            },
            {
                "text": "A typed array of 32-bit float values. The contents are initialized to 0. If the requested number\nof bytes could not be allocated an exception is raised.",
                "kind": "text"
            },
            {
                "text": "\n",
                "kind": "lineBreak"
            },
            {
                "text": "A typed array of 32-bit float values. The contents are initialized to 0. If the requested number\nof bytes could not be allocated an exception is raised.",
                "kind": "text"
            }
        ],
        "tags": []
    }
]
```

**Comment by mhegazy** [comment] 2017-05-17 16:34
The problem is lib.es6.d.ts has 3 definitions of `interface Float64Array`, each with the same comment, so aggregating them results in the duplication. 
Not sure if there is a general fix here, since a symbol can have multiple declarations, and the comments can be different and there is not a clear way to say which comment is primary/secondary.. 

A fix for this specific case, is to make sure the library only has a comment on one declaration only.

**Comment by NaridaL** [comment] 2017-09-18 19:31
See https://github.com/Microsoft/TypeScript/pull/18555

**Closed** 2017-09-18 20:34 UTC
Labels: Accepting PRs, Bug, Domain: lib.d.ts, VS Code Tracked
