### ISSUE TITLE
Inferring function return type then use it instead of function itself

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#13159] opened 2016-12-24 18:11 UTC
Not sure if this is already possible with Typescript or it's being discussed (I can't even think about the keywords for the search). 

Suppose I have a type defines a function that returns a generic:

```ts
    type Function1<T1, R> = (t1: T1) => R;
    interface SomeWrapper<T>{ 
        index: T;
    }
```

I then accept it as a parameter in a function, inferring it's return value:

```ts
    export function funct<P, A1>(
        type: string,
        cb: Function1<A1, P>
    ): Function1<A1, SomeWrapper<P>>;
```

when `funct` is called, it then returns a new 'partial' function that returns a wrapped object:

```ts
const f1 = funct('string', (param1: string) => ({ param1 }))
// returns a function that when that f1('') => { index: { param1: '' } }, of type Function1
```

I want to pass this `f1` variable to another function, and it'll know the parameter type by inferring it (again):

```ts
   export function useFunct<V, A1, F extends Function1<A1, V>>(type: F, reduce: (current: F) => V): V; 
```

then when doing:

```ts
useFunct(f1, (param) => {
  // expect param to be of type string inferred from f1
  // it's of course a function, and not the value of the function
  return {
    param
  }
})
```
is it possible or it needs an implementation? if not, I think it would be like `returnOf` keyword (like `keyof`)

```ts
   export function useFunct<V, A1, F extends Function1<A1, V>>(type: F, reduce: (current: returnOf F) => V): V; 
```

**Comment by mhegazy** [comment] 2016-12-26 19:48
Possibly a duplicate of https://github.com/Microsoft/TypeScript/issues/10247

**Comment by pocesar** [comment] 2016-12-26 20:18
well I'm most interested in using the return value of the function, the function parameters can be already be inferred (with the interface and multiple arguments generics), it's a simpler case I think, an extra keyword, not HKTs

**Comment by mhegazy** [comment] 2016-12-26 20:24
https://github.com/Microsoft/TypeScript/issues/6606 tracks getting the return type of a function/constructor.

**Closed** 2016-12-26 21:38 UTC
Labels: Duplicate
