### ISSUE TITLE
Array.map() returns {[key:string]: string} when it should return {[key:T]: string}

### ISSUE THREAD

**Issue by navneetkarnani** [microsoft/TypeScript#45344] opened 2021-08-06 12:34 UTC
# Bug Report

### 🔎 Search Terms

array map reduce type inference
### 🕗 Version & Regression Information
Seen on all versions. I have tested on: 4.4.0-dev.20210806 in playground

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "This mapped type returns a primitive type, not an object type."

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEGMCcFMEMBdqlqA5teBRAdgN1AGYCu248AlgPbajwAWCoA7uQDasBQIoM8RkNWDUoAjAFbQyzcvVABraAE9Q5AM6hVRAA5bW5aABNQ2WAFtoXMEKO5YrIkjXJQAInCVTWoogPAD0SHJcQ2BKegDQW3toFwAaUEtaRS1ycDtWZS1ISnBoVVUAOmg8AG0TcwBdDndsVXg0DBx8AF5QAB4AFVBoAA9EbAN1OsDsVAA+AAoC6eLcADkzPIAuUAAlOANqDIBBSEhYRU6xgEoV9fdIA0744fJRsdBmh4BvDlB3hI+IajrjaCYAPLiR7dPALcyFUywLQTYyLR4vT5fD68fg0Z5lRYVFblJCwIbwEaoAC+AG43h9iccCjADERchMJlloLh4uB+JBjgjQK9kSiMGieaBpgVmazhdN2XtQGSKe8qeS5aBuAAhIioHFhVJIeiMFzYf5AsQuFTqbBhJJaJDnSiXa4aQl3cagETeNaSW1XW6jG6O+5K1ECP6A8Tk2WJAACAWykFUK16Vqkuvq4VcdGg7EoJtsgVgIlYSHTMA0dEoRFYRhgmlY9TuzncnjYCCoNAIsDY-Gg8VtaYzrCzJbLFZdSH1LICLmqP3qz1ApkU4K7oHTmZlIPQWDwEwA5PPF9vjuSgA)
)

### 💻 Code

```ts
// create a getEnv function that will
// return an object with key is supplied name
// and value is a "computed/derived/other value", 
// typically process.env[name]
const getEnv = <T extends string>(...envNames: ReadonlyArray<T>): Record<T, string> => {
    
    const newObj = envNames.map( name => { 
        return {[name]: name as string};
    }).reduce((prev, curr) => {
        return { ...prev, ...curr };
    });

    // Bug: notice that "newObj" is not type Record<T, string> but Record<string, string>
    return newObj;
};

// @errors: expect that the "hello" variable here should result in a compilation failure, or "hello" should be "never"
const { myName, hello } = getEnv('myName');
```

### 🙁 Actual behavior

array.map().reduce() returns object with type Record<string,string>

### 🙂 Expected behavior

array.map().reduce() should return object with type Record<T,string> because the "key" in the map function is limited by value scope to the values in "T"

**Comment by jcalz** [comment] 2021-08-06 14:44
This doesn't really have much to do with `Array.map()`.  You can reproduce the behavior like this:

```ts
function foo<K extends string>(k: K) {
    const o = { [k]: 123 }
    // const o: { [x: string]: number; }
    // not { [P in K]: number }
    // or more accurately { [P in K]: { [Q in P]: number } }[K]
};
```
[Playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcA8BpRBTAHlbMAEwGdESoAnGMAcwD4AKAawC5EMBKRAbwChEgxBAQVEcRAF5eiANrMAuuwCMAJgDMiAL4ChAej3DRUcex5zc7CtTpLEYEAFsARtkoBubbsEH7cE+ayAAqINBx2Di5uXkKIvnCUMsGhSBh2gQCKKYhBEU6uiVrasml8Wu58QA)

which makes this a duplicate of #13948 and/or #21030.

**Closed** 2021-08-08 18:00 UTC
Labels: Duplicate
