### ISSUE TITLE
those sneaky debugger statements make the compiler upset

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#4030] opened 2015-07-26 19:06 UTC
```typescript
function f1<r>(): r {
	throw new Error(String(Math.random())); // nothing to it so far
}

function f2<r>(): r {
	debugger;
	throw new Error(String(Math.random()));  // all hell breaks loose
}
```

live [demo](http://www.typescriptlang.org/playground#src=function%20f1%3Cr%3E()%3A%20r%20%7B%0D%0A%09throw%20new%20Error(String(Math.random()))%3B%20%2F%2F%20works%0D%0A%7D%0D%0A%0D%0Afunction%20f2%3Cr%3E()%3A%20r%20%7B%0D%0A%09debugger%3B%0D%0A%09throw%20new%20Error(String(Math.random()))%3B%20%20%2F%2F%20all%20hell%20breaks%20loose%0D%0A%7D%0D%0A%0D%0A)

**Comment by mhegazy** [comment] 2015-07-26 19:19
looks like a dupe of #1042

As i mentioned in https://github.com/Microsoft/TypeScript/issues/3647#issuecomment-115777566: 

This is because the compiler does not do control flow analysis at this point. it would be a restriction that can be relaxed once this support is added. 

As for now this is by design, as per the [section 6.3: function implementations](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#63-function-implementations) from the language spec:

> An explicitly typed function whose return type isn't the Void or the Any type must have at least one return statement somewhere in its body. An exception to this rule is if the function implementation **consists of a single 'throw' statement**.

**Closed** 2015-07-26 19:19 UTC
Labels: Duplicate
