### ISSUE TITLE
String literal inference not following if/else cases

### ISSUE THREAD

**Issue by y-nk** [microsoft/TypeScript#45397] opened 2021-08-10 07:19 UTC
# Bug Report

### 🔎 Search Terms

String literal if inference

### 🕗 Version & Regression Information

Tested with latest version in the playground

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqmAmBDYiBGAbaBeKByAZgPaG5QA+eqiATrgFB2iRQBixUOA3lEYQFxQAzsGoBLAHYBzKAF9G4aACEaHKNyrUBwsVNkMm0AKIA3COOCDVnOlDy8AdAFcEyCLgHdeggW0IBtAF1ZABobShonF2A3DygNbyhlakCQujl5ZgBZQngIdEsuMN4fYlDbDQEktIYAY0JxYSEzeBMzYFUAHgAVKAgAD2jxeEsAawgQQnwoVvNBAD4ACghTcwEu4KgwRBB0QkR4ARmLPy6AgEoOObUwgHobqBr0REFBURqoeFFBLeAagAteitgNU6HcoABaSFQ6E1RzAaEI8G1eqNaLCFiOcQ1YCieqdHr9QbDWBRNCYRbLNoCAAGABJOF0ZJEkNFqRsALY5PICbK5fInc6Xa62TDtLY7PYHaZAwR+AyTQFtAIAbgYtlEUyWQI4WBwBGIzNcuAu1lstjBfwg1GgXQAykI-oRHOh4FARuJCAB3TbbXb7KBfB6EajW7FxCA1RCOQTQDWK8w6vUOZwstxlM1g4CW8RQHq6pPEXAbLNWiBEa1QeVTcV+12Bo6y-UkIKev5vAGBzzEBK+FJyM1NIZHLVtDZdwgJPycvlBGRnML93r5WOaykJ-PhaiG6LG4UZ+6Wit2h1Ol1uj3emuSgOWOohiPtVARqMxgNTNftDe4DTbtNhc33CWOZ5rqm5FpWh5lsG0BVj6Er+vWMp+N+NC4C2bb-DeahxDQCRJH2-6Di0QIjuYY44dQk7Tnks7zrYcjpJm4ASNInrBiMggAISMBA6KYtiuLiAsTa-uB44CLgpBzgwTFgCxUBsdQHHcWiwAYliOL1MJP4pka5HFHgUlnEAA)

### 💻 Code

```ts
type Updatable = 'foo' | 'bar'

type Foo = { foo: string }
type Bar = { bar: string }

type Events = {
  'foo.update': { foos: Foo[] },
  'bar.update': { bars: Bar[] },
}

type Models = {
  foo: Foo,
  bar: Bar
}

const sendEvent = <T extends keyof Events>(event: T, payload: Events[T]) => {
  // classic dispatch event
}

// ----------cut----------

const testFunction = <T extends Updatable>(event: `${T}.update`, model: Models[T]) => {
  let payload: Events[typeof event];

  if (event === 'foo.update') {
    // here TS should know payload is correct because if event === 'foo.update',
    // then T === 'foo', therefore typeof payload is Events['foo'] which is { foos: Foo[] }
    sendEvent(event, { foos: [model] })
  }
  else if (event === 'bar.update') {
    // here TS should know payload is correct because if event === 'bar.update',
    // then T === 'bar', therefore typeof payload is Events['bar'] which is { bars: Bar[] }
    sendEvent(event, { bars: [model] })
  }
}

// typing works!
testFunction('foo.update', { foo: '' })

// typing works!
testFunction('bar.update', { foo: '' })
```

### 🙁 Actual behavior

There's an issue with type inference related to string literals.

### 🙂 Expected behavior

Typing should be inferred correctly

**Comment by jcalz** [comment] 2021-08-10 18:11
This is a duplicate of #27808 and/or #30851.

---

Without something like #27808, the type parameter `T` is allowed to be the full union, which breaks your intended constraint. Right now you can do the following call with your code, so the compiler's warning inside the implementation is technically correct:

```ts
// typing... doesn't work?
testFunction(Math.random() < 0.5 ? "foo.update" : "bar.update", { foo: "" }); // no error
```

---

But even if you can fix it, you'd still run into the problem in #30581.  Let's make `testFunction` take a union of rest arguments:

  type Args = { [T in Updatable]: [event: `${T}.update`, model: Models[T]] }[Updatable]
  // type Args = [event: "foo.update", model: Foo] | [event: "bar.update", model: Bar]

  const testFunction = (...[event, model]: Args) => { /*...*/ }

  testFunction('foo.update', { foo: '' }) // okay
  testFunction('bar.update', { foo: '' }) // error
  testFunction(Math.random() < 0.5 ? "foo.update" : "bar.update", { foo: "" }); // error

Now the call side is safe, but the compiler still has no idea inside the implementation that the types of `event` and `model` are correlated the way you want:

```ts
const testFunction = (...[event, model]: Args) => {
  let payload: Events[typeof event];

  if (event === 'foo.update') {
    sendEvent(event, { foos: [model] }) // error! Foo | Bar not assignable to Foo
  }
  else if (event === 'bar.update') {
    sendEvent(event, { bars: [model] }) // error! Foo | Bar not assignable to Bar
  }
}
```

You can work around this by using a single `args` rest argument as a [discriminated union](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions) without destructuring it: 

```ts
const testFunction = (...args: Args) => {
  if (args[0] === 'foo.update') {
    sendEvent(args[0], { foos: [args[1]] }) // okay
  }
  else if (args[0] === 'bar.update') {
    sendEvent(args[0], { bars: [args[1]] }) // okay
  }
}
```

Now everything works, but it's weird looking.

**Comment by y-nk** [comment] 2021-08-11 10:32
@jcalz Thanks so much for the explanation. It's really nice and with examples. Thank you :) 

For what you wrote on `Args`:

```
type Args = { [T in Updatable]: [event: `${T}.update`, model: Models[T]] }[Updatable]
// type Args = [event: "foo.update", model: Foo] | [event: "bar.update", model: Bar]

const testFunction = (...[event, model]: Args) => { /*...*/ }
```

I don't get how it's different from:

```
const testFunction = <T extends Updatable>(event: `${T}.update`, model: Models[T]) { /*...*/ }
```

In your version, you manually build a union of arguments that ends in: `[event: "foo.update", model: Foo] | [event: "bar.update", model: Bar]` but in mine, the only valid outcome are similarly `[event: "foo.update", model: Foo] | [event: "bar.update", model: Bar]` since the two parameters are bound by the `<T>` constraint?

Or is it a misinterpretation from my side and actually the `<T>` constraint results in a larger union for the function's arguments (notably `[event: "foo.update", model: Bar] | [event: "bar.update", model: Foo]`) ?

Or is it something related to string literals?

Thanks again

**Comment by jcalz** [comment] 2021-08-11 13:51
See this section:

> Without something like #27808, the type parameter `T` is allowed to be the full union, which breaks your intended constraint. Right now you can do the following call with your code, so the compiler's warning inside the implementation is technically correct:
> 
> ```ts
> testFunction(Math.random() < 0.5 ? "foo.update" : "bar.update", { foo: "" }); // no error
> ```

That can be called without errors, but you don't want it to be.  The type parameter `T` is not inferred to be `"foo"`, and it is not inferred to be `"bar"`... it is inferred to be `"foo" | "bar"`, the full union type to which it is constrained.  And therefore the parameters list looks like `[event: "foo.update" | "bar.update", model: Bar | Foo]`:

```ts
// IntelliSense:
// const testFunction: <"foo" | "bar">(event: "foo.update" | "bar.update", model: Bar | Foo) => void
```

There is currently no direct way in TypeScript to constrain type parameter `T` to one of a *set* of types.  `T extends ("foo" | "bar")` does not have that effect.  You want to say something like `(T extends "foo") | (T extends "bar")` but that's not valid TypeScript  This situation what #27808 is about.

**Closed** 2021-08-13 20:00 UTC
Labels: Working as Intended
