### ISSUE TITLE
Call on OR type rejected without obvious reason.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#11005] opened 2016-09-20 15:01 UTC
**TypeScript Version:**  2.0.2
**Code**

```ts
interface I1 {
	openEditor(input: string, options: string | number): void;
}

interface I2 {
	openEditor(input: string, options: string): void;
}

let part: I1 | I2;

part.openEditor('dirk', 'baeumer');
```

You get a compile error on part.openEditor. However I think the call should be accepted since the interface could be correctly merged.

**Comment by RyanCavanaugh** [comment] 2016-09-20 17:00
Duplicate of #7294

**Closed by RyanCavanaugh** 2016-09-20 17:00 UTC
Labels: Duplicate

**Comment by dbaeumer** [comment] 2016-09-21 07:56
@RyanCavanaugh @mhegazy just wanted to point out that the code above worked in 1.8.10. So in that regard it is not a dup of #7294

**Comment by RyanCavanaugh** [comment] 2016-09-21 19:28
There was a change in how we do subtype reduction. The type `I1 | I2` is actually somehwat meaningless (`I1` is strictly more general) and it was previously reduced immediately to `I1`, but that had other bad side effects (namely, if you narrow away `I1`, you'd get `never`instead of `I2`)
