### ISSUE TITLE
BUG : compiler Anonymous class 

### ISSUE THREAD

**Issue by renatoprogramer** [Microsoft/TypeScript#18515] opened 2017-09-15 21:13 UTC
**_Is Bug in compiler ?_** 

```
class Carro {

    public marcas() {
        // Anonymous class, and not working  "return new class{....}"  or "return class{....}"
        return class {

            private stars: Array<number>;

            public ford(stars: number) {
                this.stars.push(stars);
                return this;
            }
            public mercedes(stars: number) {
                this.stars.push(stars);
                return this;
            }
        }
    }
}
var a = new Carro();
var marcas = a.marcas();
var ab = new marcas();
ab.ford(3);
ab.mercedes(2);

```
**Output compile:** 

```
var Carro = (function () {
    function Carro() {
    }
    Carro.prototype.marcas = function () {
        return (function () {
            function class_1() {
            }
            class_1.prototype.ford = function (stars) {
                this.stars.push(stars);
                return this;
            };
            class_1.prototype.mercedes = function (stars) {
                this.stars.push(stars);
                return this;
            };
            return class_1;
        }());
    };
    return Carro;
}());
var a = new Carro();
var marcas = a.marcas();
var ab = new marcas();
ab.ford(3);
ab.mercedes(2);
```

Error: 

` Uncaught TypeError: Cannot read property 'push' of undefined
    at class_1.ford (<anonymous>:9:27)
    at <anonymous>:4:4`

**Comment by renatoprogramer** [comment] 2017-09-15 21:17
**Perfect compiler would be**

```
var Carro = (function () {
    function Carro() {
    }
    Carro.prototype.marcas = function () {
        return (function () {
            function class_1() {
            }

            class_1.prototype.stars = [];  /// COMPILE ADD <---------------------------------------------

            class_1.prototype.ford = function (stars) {
                this.stars.push(stars);
                return this;
            };
            class_1.prototype.mercedes = function (stars) {
                this.stars.push(stars);
                return this;
            };
            return class_1;
        }());
    };
    return Carro;
}());
var a = new Carro();
var marcas = a.marcas();
var ab = new marcas();
ab.ford(3);
ab.mercedes(2);

```

**Comment by mhegazy** [comment] 2017-09-15 21:22
Duplicate of https://github.com/Microsoft/TypeScript/issues/8476

**Comment by renatoprogramer** [comment] 2017-09-15 21:32
@mhegazy  This report is not duplicated because the compiler constructs the methods and forgets the attributes

**Comment by RyanCavanaugh** [comment] 2017-09-15 22:01
@renatoprogramer arrays are not automatically initialized

**Closed by RyanCavanaugh** 2017-09-15 22:01 UTC
Labels: Duplicate

**Comment by kitsonk** [comment] 2017-09-17 14:05
Especially adding a non-primative to a prototype is not a good thing.  ALL instances would share that non-primative instance, unless they initialised it in their constructor:

```js
var Carro = (function () {
    function Carro() {
    }
    Carro.prototype.marcas = function () {
        return (function () {
            function class_1() {
            }

            class_1.prototype.stars = [];  /// COMPILE ADD <---------------------------------------------

            class_1.prototype.ford = function (stars) {
                this.stars.push(stars);
                return this;
            };
            class_1.prototype.mercedes = function (stars) {
                this.stars.push(stars);
                return this;
            };
            return class_1;
        }());
    };
    return Carro;
}());
var a = new Carro();
var marcas = a.marcas();
var ab = new marcas();
ab.ford(3);
ab.mercedes(2);
var ab2 = new marcas();
console.log(ab.stars === ab2.stars); // true!!!! Not good!
console.log(ab.stars); // [3, 2]
console.log(ab2.stars); // [3, 2]!!!!!  Not good!
```

As Mohammed says, initialisers are optional (and for good reasons), detecting accessing an uninitialised property would be useful and is tracked by the issue mentioned.
