### ISSUE TITLE
Making incremental compilation API public

### ISSUE THREAD

**Issue by radiosterne** [Microsoft/TypeScript#30676] opened 2019-03-31 15:54 UTC
## Search Terms

incremental tsbuildinfo

## Suggestion

Make incremental compilation APIs, such as `performIncrementalCompilation`, `createIncrementalProgram`, and `createIncrementalCompilerHost` public to allow incremental compilation without running tsc.

## Use Cases

This would be useful for third-party typescript compilation utilities, such as Webpack loaders (see https://github.com/TypeStrong/ts-loader/issues/913, https://github.com/s-panferov/awesome-typescript-loader/issues/627).

Maybe I'm gravely mistaken and there is some other way to enable incremental compilation using `.tsbuildinfo`, but I'm unable to figure it out, so any suggestions would certainly be helpful.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment] 2019-04-02 18:48
Duplicate of #29978, which is 3.5-bound.

**Closed** 2019-04-05 18:00 UTC
Labels: Duplicate
