### ISSUE TITLE
No narrowing on condition captured by const variable

### ISSUE THREAD

**Issue by amannn** [microsoft/TypeScript#39996] opened 2020-08-11 14:10 UTC
**TypeScript Version:**  4.0.0-beta

**Search Terms:**

- "unnecessary null check"
- "derived boolean null check"

**Expected behavior:**

When a created variable contains a null check, using that boolean should be sufficient for safe access to the variable.

**Actual behavior:**

TypeScript needs an additional null check.

**Related Issues:**

**Code**
```ts
export default function foo(a: {b: boolean} | undefined) {
    const isNull = a == null;

    if (isNull) {
        return;
    }

    // Object is possibly 'undefined'.
    return a.b
}
```

<details><summary><b>Output</b></summary>

```ts
export default function foo(a) {
    const isNull = a == null;
    if (isNull) {
        return;
    }
    return a.b;
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.0.0-beta#code/KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnMhBABSoBccA3gEYPNWbCp4C+cAPnHxJkxPMAQBKJgCg48uATIBneMWUA5LJjgBeOKj3682gNwy5C4sjjV1WzJmmNLChVGAx0UPObc8LNw8vHwMAOmYZHiA)

**Comment by amannn** [comment] 2020-08-11 14:14
My apologies if this issue already exists, I couldn't find it with my search terms!

**Comment by MartinJohns** [comment] 2020-08-11 14:36
Duplicate of #12184.

**Comment by tom-sherman** [comment] 2020-08-11 16:36
You can use a type guard instead:

```typescript
function isNullish<T>(x: T | null | undefined): x is null | undefined {
    return x == null;
}

declare const x: number | undefined;

if (!isNullish(x)) {
    x // number
}
```

**Closed** 2020-08-16 18:00 UTC
Labels: Duplicate
