### ISSUE TITLE
Type of a variable that may mutate in a function is incorrectly refined as the initialized type

### ISSUE THREAD

**Issue by niieani** [microsoft/TypeScript#45929] opened 2021-09-17 09:00 UTC
# Bug Report

### 🔎 Search Terms

initialized type refinement

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about refinements (none)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/DYUwLgBAlgdlYC4IEEBOqCGBPAPDArgLYBGIqAfBAD4QBmGwAziBALx0PMBQXAxgPYxGkZmACScSOwAUAOnkZUAc0ZI0mXARJlyASjaUA3lwinokthEUquAXx6iJ8aQEYANBABMHgMy6uAPQB5vDQjBAw-ADulgDa7l6+ALqBwcT4kAAqWAAOIADKvKhQOSJgUMDAEGAAFrAA1uHwAOThAAb0TCBtHoz85oxQACYspMDREM1QtM0QqCC0sCCEIDCQobUNTWCtEPy01bksbTAgAG5kbTzTENKw8PqOknLy92D+QA)

### 💻 Code

```ts
let init: Array<number> | false = false

const setInit = (...args: Array<number>) => {
    init = args
}

setInit(1, 2, 3)
// init is now = [1, 2, 3]
// but TypeScript still thinks it's `false`, so inside below 'if' refinement it thinks it's of type `never`

if (init) setInit(...init)
//                   ^^^^ error, because `init` is of type: `never`
```

### 🙁 Actual behavior

A variable that is a union of two or more types is being assumed to only be the initialized type and refined to it, even though the actual type might change as a side effect of another function that's executed in the same scope.

### 🙂 Expected behavior

TypeScript should understand that the variable may be assigned to by a nested function that has access to that variable, and widen the type accordingly.

Alternatively, it should turn off automatic refinement based on the initializer value, when the value may be assigned to by any function that has access to it.

**Comment by MartinJohns** [comment] 2021-09-17 09:07
Another duplicate of #9998.

**Closed** 2021-09-19 18:00 UTC
Labels: Duplicate

**Comment by niieani** [comment] 2021-11-25 04:09
@MartinJohns this is related to, but isn't the same as #9998. 

IMO the problem is that TypeScript shouldn't assume that `init` is `false` in the cases when the type is explicitly specified by the user to be `false | Array<number>`. It's a different thing if the type were inferred, or was assigned after the declaration, but in this case, the user is explicit about the `init` type in the initializer.

**Comment by MartinJohns** [comment] 2021-11-25 07:35
@niieani This is exactly a duplicate of #9998. That issue causes the type checker to not recognize the assignment in your function.

That the type is narrowed ot `false` is the intended behaviour. Assigning a value to a variable narrows the variable to the type. You can opt-out from this behaviour using a type assertion: `let init: Array<number> | false = false as Array<number> | false`
