### ISSUE TITLE
tuple with const enums doesn't work

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#4421] opened 2015-08-23 18:45 UTC
```
const enum Types{ NAME=0, NODE=1 }  
var a: [string, Node];
a[Types.NODE].parentNode; // parentNode does not exists
a[1].parentNode;// that is works fine
```

**Comment by xLama** [comment] 2015-08-24 18:26
It does not work with no-const enum

**Comment by jbondc** [comment] 2015-08-28 14:17
Duplicate of #3411

**Comment by DanielRosenwasser** [comment] 2015-08-28 16:11
Thanks for catching that @jbondc

**Closed by DanielRosenwasser** 2015-08-28 16:11 UTC
Labels: Duplicate, In Discussion, Suggestion
