### ISSUE TITLE
Assign parameter names to values when calling a function to avoid setting of unneeded optional parameters

### ISSUE THREAD

**Issue by Pieter-1337** [microsoft/TypeScript#48318] opened 2022-03-18 09:06 UTC
# Suggestion

Parameter assignation when calling a function, to make code more readable and to omit optional parameters that would otherwise not need be defined in the function call

## 🔍 Search Terms

assign parameters calling function assignation optional omit

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When calling a function it is currently not possible to assign parameters to their defined param name in the calling function, this has as a result that when using optional parameters and you wish to use any optional parameter after the first optional parameter, that you would need to set a value to all optional parameter before the one you are setting.

This simply results in setting some optional parameters value equal to the values that were already set as either their default value or null in the function definition...

This is not very readable and causes clutter and is prone to error when multiple optional parameters are present on a function

## 📃 Motivating Example

Imagine following situation, we have a function with optional params
So either declared like this:

```
function exampleFunc(x: string, y?: string, z?: string): void{ 
//Logic here does not matter for the feature
}
```

Or declared like this:

```
function exampleFunc(x: string, y: string = null, z: string = null): void{ 
//Logic here does not matter for the feature
}
```
Now if I wish to call this function and I only want to set the x and z parameters I am obliged to set the y param to it's default value as shown below

`exampleFunc("someValue", null, "someValue");`

It would make more sense if I could call the function as stated below and omit the optional param I don't want to change the default value for...

`exampleFunc(x: "someValue", z: "someValue");`

This would omit the need to set the y parameter to null since it already is null (or any other value that was set in the function definition) by default...

Stackblitz example: https://stackblitz.com/edit/typescript-ckfrdm

I feel this would greatly improve readability and omit code clutter 

## 💻 Use Cases

I would like to be able to assign parameter names and set values to these names, in order to omit the setting of unneeded optional parameters.

Current shortcomings of this feature: => This feature not existing introduces the following shortcomings int TS code
-  code clutter, 
-  less readable, 
-  prone to error

Workaround: 

Pas an object as a param and destructure in the function call as shown below 

```
export interface INamedParameters {
  x: string;
  y?: string;
  z?: string;
}
```

```
function testFunc2({ x, y = null, z = null }: INamedParameters): void {
  if (!!y) {
    console.log('optional param y was passed in the params!');
  }
  if (!!z) {
    console.log('optional param z was passed in the params!');
  }
}

testFunc2({ x: 'test', z: 'someValue' } as INamedParameters);
```
As you can see x, y, z are settible in the object, yet not mandatory, in this manner we can simply pass an object of INamedParameters to our function with the properties that are relevant for the use case at hand

**Comment by whzx5byb** [comment] 2022-03-18 09:12
Duplicate of https://github.com/microsoft/TypeScript/issues/467

**Comment by MartinJohns** [comment] 2022-03-18 11:48
This is one of the features that needs to be supported by JavaScript first.

**Comment by fatcerberus** [comment] 2022-03-18 13:01
> I don't use any workaround as there are none

I mean, you can pass an object and destructure it, which is how this is usually done in vanilla JS too:
```ts
interface FooOptions {
    foo: string;
    bar: string;
    baz?: number;
}

function foo({ foo, bar, baz }: FooOptions) {
    console.log(foo, bar, baz);
}

// prints "fooey, bard, undefined"
foo({ foo: "fooey", bar: "bard" });
```

**Comment by Pieter-1337** [comment] 2022-03-18 13:05
> > I don't use any workaround as there are none
> 
> I mean, you can pass an object and destructure it, which is how this is usually done in vanilla JS too:
> 
> ```ts
> interface FooOptions {
>     foo: string;
>     bar: string;
>     baz?: number;
> }
> 
> function foo({ foo, bar, baz }: FooOptions) {
>     console.log(foo, bar, baz);
> }
> 
> // prints "fooey, bard, undefined"
> foo({ foo: "fooey", bar: "bard" });
> ```
 @fatcerberus yeah I added that to the stackblitz and the issue just now! thx for the info though.

Still feel it would be nice if we could just name the params like in C# for instance, oh well it'll do just fine with passing  the object and destructuring it indeed :)

**Comment by fatcerberus** [comment] 2022-03-18 13:34
For what it's worth, you don't need the cast `as INamedParameters`.  You *do* need to include your default values in the interface, though: [Playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgSQDlMBbYAEwAVMpThUoBnOAbwCg44QAuORmKMgDmAbg5wAngH5e-QUiFwAPnCQBXADYaxnAF4y+A4ctWbtbAL5s26NUmwwEEJHFT8AYnewAmABQsuABpJOABeUy1g3TCIjTgLXiI6Kho6BkYASl4ANwgEclZxBHQ4XwBCMokMws5ObGdGCA1gADoNCCFfAHIIMEdnTDiwVJIQgHdMZmHGRgpEFxgACzxh2hJGMq6MnXiikvKy3Wr2Wrh6pEbmto7u3v6kQbhV0jhoianJ2YLkV2WnkY2Wx2VisbDcME89j8AR4cC64K6UV4XUaZAAaoM1MAuvFtmwgA)

It'd be nice if you could write the types inline as `function foo({ foo: string, bar?: number }) {}`, but that doesn't work because it conflicts with the syntax for renaming destructured properties. 😢

**Comment by jcalz** [comment] 2022-03-18 16:30
You checked the box for 
> This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

but this is definitely a runtime feature.

**Closed** 2023-06-21 01:32 UTC
Labels: Suggestion, Out of Scope
