### ISSUE TITLE
Incorrect function argument inference on union

### ISSUE THREAD

**Issue by tgriesser** [microsoft/TypeScript#31931] opened 2019-06-16 17:17 UTC
Found some confusing/incorrect behavior where a function fulfills a member of a union type (oddly enough, due to the presence of the function's `name` property), but the function's argument is then incorrectly inferred from another union type it does not fulfill, rather than as `any`.

**TypeScript Version:**  3.6.0-dev.20190615

**Search Terms:**

incorrect union function type inference

**Code**

```ts
type Columns = {
  id: number
  name: string | null
}

class QueryBuilder {}
type QueryScope = (qb: QueryBuilder) => QueryBuilder
 
type AtLeastOne<T, U = { [K in keyof T]: Pick<T, K> }> = Partial<T> & U[keyof U]

function keyedFilter(filter: AtLeastOne<Columns>) {}
function scopedFilter(filter: QueryScope) {}
function keyedOrScopedFilter(filter: AtLeastOne<Columns> | QueryScope) {}

keyedFilter({}) // errors (correct)
keyedFilter({id: 1}) // valid (correct)
keyedFilter(() => {}) // valid, because of fn's "name" property (weird but ok?)
keyedFilter((q) => {}) // errors (with noImplicitAny) as "q" is implicitly "any" (ok?)

scopedFilter((q) => q) // valid (correct)
scopedFilter((q) => {}) // errors (correct)

keyedOrScopedFilter({}) // errors (correct)
keyedOrScopedFilter({id: 1}) // valid (correct)
keyedOrScopedFilter(q => q) // valid (correct)


keyedOrScopedFilter((q) => {}) 
// ^ **incorrect** - no error, matches {name: string} of the AtLeastOne<Columns>, 
// but also infers "q" as `QueryBuilder` rather than "any"
```

**Expected behavior:**

"q" in final `keyedOrScopedFilter` should be inferred as `any`, as it doesn't match `QueryScope` without a return value.

**Actual behavior:**

"q" is inferred as `QueryBuilder`, but does not pass for the `QueryScope` type in the union.

<img width="823" alt="Screen Shot 2019-06-16 at 12 24 29 PM" src="https://user-images.githubusercontent.com/154748/59566852-a6f02a80-9033-11e9-846a-cf9d9a0abbbc.png">

**Playground Link:** 

Be sure to toggle `--noImplicitAny` to see the discrepancy between `keyedFilter((q) => {})` and `keyedOrScopedFilter((q) => {})`

[Playground link](https://www.typescriptlang.org/play/index.html#src=type%20Columns%20%3D%20%7B%0D%0A%20%20id%3A%20number%0D%0A%20%20name%3A%20string%20%7C%20null%0D%0A%7D%0D%0A%0D%0Aclass%20QueryBuilder%20%7B%7D%0D%0Atype%20QueryScope%20%3D%20(qb%3A%20QueryBuilder)%20%3D%3E%20QueryBuilder%0D%0A%20%0D%0Atype%20AtLeastOne%3CT%2C%20U%20%3D%20%7B%20%5BK%20in%20keyof%20T%5D%3A%20Pick%3CT%2C%20K%3E%20%7D%3E%20%3D%20Partial%3CT%3E%20%26%20U%5Bkeyof%20U%5D%0D%0A%0D%0Afunction%20keyedFilter(filter%3A%20AtLeastOne%3CColumns%3E)%20%7B%7D%0D%0Afunction%20scopedFilter(filter%3A%20QueryScope)%20%7B%7D%0D%0Afunction%20keyedOrScopedFilter(filter%3A%20AtLeastOne%3CColumns%3E%20%7C%20QueryScope)%20%7B%7D%0D%0A%0D%0AkeyedFilter(%7B%7D)%20%2F%2F%20errors%20(correct)%0D%0AkeyedFilter(%7Bid%3A%201%7D)%20%2F%2F%20valid%20(correct)%0D%0AkeyedFilter(()%20%3D%3E%20%7B%7D)%20%2F%2F%20valid%20(because%20of%20fn's%20%22name%22%20property%2C%20weird%20but%20ok%3F)%0D%0AkeyedFilter((q)%20%3D%3E%20%7B%7D)%20%2F%2F%20errors%20(with%20noImplicitAny)%20as%20%22q%22%20is%20implicitly%20%22any%22%20(ok%3F)%0D%0A%0D%0AscopedFilter((q)%20%3D%3E%20q)%20%2F%2F%20valid%20(correct)%0D%0AscopedFilter((q)%20%3D%3E%20%7B%7D)%20%2F%2F%20errors%20(correct)%0D%0A%0D%0AkeyedOrScopedFilter(%7B%7D)%20%2F%2F%20errors%20(correct)%0D%0AkeyedOrScopedFilter(%7Bid%3A%201%7D)%20%2F%2F%20valid%20(correct)%0D%0AkeyedOrScopedFilter(q%20%3D%3E%20q)%20%2F%2F%20valid%20(correct)%0D%0A%0D%0A%0D%0AkeyedOrScopedFilter((q)%20%3D%3E%20%7B%7D)%20%0D%0A%2F%2F%20%5E%20**incorrect**%20-%20no%20error%2C%20matches%20%7Bname%3A%20string%7D%20of%20the%20union%2C%20%0D%0A%2F%2F%20but%20also%20infers%20%22q%22%20as%20%60QueryBuilder%60%20rather%20than%20%22any%22)

**Comment by RyanCavanaugh** [comment] 2019-06-17 15:50
This is behaving as intended.

The root cause of the confusion here is that functions have a `.name` property, so any function is a valid `AtLeastOne<Columns>` - rename `name` to `name2` in `Columns` and you'll see the error you expect, or add `call?: never;` to prevent functions from being assigned to `Columns`.

Contextual typing happens in an earlier phase and TS doesn't enforce that the overload that's selected is the one that provided the contextual type to the parameter - this is sort of a phase ordering problem but only situations like this actually cause an observable difference. In any case it doesn't really matter since, if the function isn't actually called, the type of the parameter is more effectively `never` and thus no runtime error can occur.

**Comment by tgriesser** [comment] 2019-06-17 17:09
> rename name to name2 in Columns and you'll see the error you expect, or add call?: never; to prevent functions from being assigned to Columns.

Thanks - I'm aware it goes away with `name2`, this was the minimum viable repo to demonstrate the behavior. Neat to know about `call?: never` - I hadn't considered that. I suppose that would also break if there were ever a column named `call` (edge case, of course, but I'm not always controlling the names of the auto-generated types). Is there no alternate approach to structurally differentiating between an object and a function?

> if the function isn't actually called, the type of the parameter is more effectively never and thus no runtime error can occur.

In this case, a runtime error is what caused me to dig into this further:

```ts
class ExampleCase {
  async countBy(params: AtLeastOne<DBTables[T]> | QueryScope): Promise<number> {
    let qb = this.builder(this.table)
    if (typeof params === 'function') {
      qb = params(qb)
    } else {
      qb = qb.where(params)
    }
    const rows = await qb.count()
    return parseInt(rows[0].count, 10) || 0
  }
}
```

which when called with:

```ts
new ExampleCase().countBy(qb => {
  qb.where({colA: 1}).orWhere({colB: 2}) // Note the missing "return here"
})
```

Because it passed the `.name` case, the contextual typing made it appear as though things were fine, even though they weren't, and the missing `return` then set `qb = undefined`.

I'll go ahead and close this out if this is indeed the intended behavior, just seemed a little odd.

**Closed** 2019-06-19 20:00 UTC
Labels: Working as Intended
