### ISSUE TITLE
Bug: Babel fails to compile the generated ES6 code

### ISSUE THREAD

**Issue by boris-kolar** [Microsoft/TypeScript#2638] opened 2015-04-06 20:15 UTC
There's a problem with the ES6 generated code when using inner classes. The code:
```javascript
// Bug.ts
module Stuff {
	export class Foo {
		constructor (message: string) {
			this.Message = "Hello, " + message
		}
		Message = ""
	}
	export module Foo {
		export class Bar {
		}
	}
}
var foo = new Stuff.Foo("World")
console.log(foo.Message)
```
compiled with `tsc -t ES6 Bug.ts` and then by `babel --no-highlight-code Bug.js` produces error:
```
TypeError: Bug.js: Line 10: Duplicate declaration "Foo"
   8 |     }
   9 |     Stuff.Foo = Foo;
> 10 |     var Foo;
     |         ^
  11 |     (function (Foo) {
  12 |         class Bar {
  13 |         }
```

**Comment by mhegazy** [comment] 2015-04-06 20:22
this is a duplicate of #2458. it is not the internal module that is causing the issue, it is the way a merged class/module is generated.

**Closed** 2015-04-06 21:20 UTC
Labels: Duplicate
