### ISSUE TITLE
minus operator `-` does not necessarily return a `number`

### ISSUE THREAD

**Issue by yukulele** [microsoft/TypeScript#56162] opened 2023-10-20 18:25 UTC
### 🔎 Search Terms

"minus operator", "minus bigint", "minus any"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "operator"

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=7#code/MYewdgzgLgBAhgLjmAnjAvDAjABjAKABsBTWAIwxgFo58KBqTAViA

### 💻 Code

```ts
const a:any = 10n
let b = -a
b += 5 
// - tsc: no error
// - run: can't convert BigInt to number
```

### 🙁 Actual behavior

`b` type is `number`

### 🙂 Expected behavior

`b` type should be `number | bigint`

### Additional information about the issue

Here's another example showing that other operators can potentially be affected
```ts
class A { [Symbol.toPrimitive] = () => 1n }

const a: A = new A()

const b = a.valueOf()
const c = -a
const d = ~a
// `b`, `c` and `d` types shound be `bigint`, right?
```
https://www.typescriptlang.org/play?target=7#code/MYGwhgzhAECC0G9oG0DKBPAtgIwPYgDoAXXABQCcBLTSoygNwFMBdaAXmgAoBKdgPmgBGAHbQAvgCgJwXMIhFoYAFxx20YYwDucHlJlyF2NWAL0wIAK6MA8gDNd++dGBqAtGGmynAEzUA-DwB6QOgAA2xQgBow4FDFYV9Q7ziidAAHRhgIAAtcCwTobEYw7EoAc0phIlCgA

**Comment by MartinJohns** [comment] 2023-10-20 18:35
Duplicate of #49558.

**Closed** 2023-10-23 01:26 UTC
Labels: Duplicate
