### ISSUE TITLE
Dev only code block

### ISSUE THREAD

**Issue by baanloh** [microsoft/TypeScript#39582] opened 2020-07-13 13:24 UTC
## Search Terms
dev only block

## Suggestion

Add some compiler instructions via comments to make a block of code ignored during compilation following conditions like production/development mode.

## Use Cases

In case you have some code that is used to get some information to debug, but you don't need to used this code in the production.

### Source
```ts
function foo(a: number, b: number) {
  // tsc block dev
  console.log(`foo: ${a} + ${b}`); // some debug information
  // tsc end block

  goo(); // this line will be ignored in prod mode, because the function goo is marked with "tsc function dev"

  return a + b;
}

// tsc function dev
function goo() {
  // this function will not exists in production mode.
  console.log("goo !");
}
```

### Dev mode
```ts
function foo(a, b) {
  console.log(`foo: ${a} + ${b}`); // some debug information
  goo(); // this line will be ignored in prod mode, because the function goo is marked with "tsc function dev"
  return a + b;
}

function goo() {
  // this function will not exists in production mode.
  console.log("goo !");
}
```

### Prod mode

```ts
function foo(a, b) {
  return a + b;
}
```

If the code is compiled in production mode, the compiler will ignore every line between `// tsc block dev` and `// tsc end block`, or every function or call to this function if the function is marked with `// tsc function dev`.

It's possible to have the same result using `if` statement. But this method have two advantage :
1) It's resolved at compile-time, or the `if` solution is runtime, so the emitted code is optimised.
2) The production code will be lighter without development-specific code.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment] 2020-07-13 13:28
Duplicate of #449.

**Closed** 2020-07-13 13:31 UTC
