### ISSUE TITLE
Weak generic constraint check

### ISSUE THREAD

**Issue by awerlogus** [microsoft/TypeScript#42145] opened 2020-12-29 12:48 UTC
**TypeScript Version:**  4.2.0-dev.20201222

**Search Terms:** generic constraint check

**Code**
```ts
type Emit<E extends string> = { emit<T extends E>(event: T): void }

type EmitAB = Emit<'a' | 'b'>
type EmitCD = Emit<'c' | 'd'>

declare const emitAB: EmitAB

// Actually: no error
// Expected: EmitAB is not assignable to EmitCD
const emitCD: EmitCD = emitAB
```

**Expected behavior:**
EmitAB is not assignable to EmitCD

**Actual behavior:**
No error

**Comment by andrewbranch** [comment] 2020-12-29 19:27
Note that neither the method nor the union types are necessary to repro:

```ts
type Emit<E extends number> = <T extends E>(event: T) => T

declare let emit0: Emit<0>;
declare let emit1: Emit<1>;

emit0 = emit1;
emit1 = emit0;
```

**Comment by DanielRosenwasser** [comment] 2021-01-11 07:56
I think that this is a duplicate of #31006 - @ahejlsberg can you confirm?

**Comment by DanielRosenwasser** [comment] 2021-01-11 07:58
Relevant design meeting might be #31132.

**Comment by awerlogus** [comment] 2021-01-11 08:25
It's hard to imagine that accessing some type in type level closure may cause so many problems

**Comment by DanielRosenwasser** [comment] 2021-01-26 19:53
I'm going to assume this is a duplicate.

**Closed** 2021-01-29 18:00 UTC
Labels: Duplicate
