### ISSUE TITLE
(🐞) No error when assigning to a member of a union that has different types in each part of the union

### ISSUE THREAD

**Issue by KotlinIsland** [microsoft/TypeScript#50384] opened 2022-08-21 02:37 UTC
# Bug Report

### 🔎 Search Terms

`union` `container` `assignment`

### 🕗 Version & Regression Information

v4.8.0-beta

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about: generic unions

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8CwAoa7oBcCEAuaAdgK4C2ARgKYBOqAvqqqJDAEKKoZZ7QSZUCWBAOZ0GKACYUmVCtBAVM0MPngAfaC1RgAdIoC80AERgefQUID8h1EA)

### 💻 Code

```ts
class A {
    t!: number
}

class B {
    t!: string
}

declare let a: A | B
a.t = "a string?"
```

### 🙁 Actual behavior

No error when assigning a `string` to the incompatible item of the union (`number`)

### 🙂 Expected behavior

An error regarding the invalid assignment.

**Comment by MartinJohns** [comment] 2022-08-21 19:45
Duplicate of #50249.

**Closed** 2022-08-28 18:00 UTC
Labels: Duplicate
