### ISSUE TITLE
Add JS format option to insert space before parentheses in function definition.

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#10733] opened 2016-09-06 21:04 UTC
_From @micktu on September 4, 2016 14:33_

VSCode version: 1.4.0

This is required by standardjs.com guidelines, but is not possible at the moment.

Example: `function myFunc () {`

_Copied from original issue: Microsoft/vscode#11520_

**Comment by waderyan** [comment] 2016-09-06 21:04
_From @dbaeumer on September 4, 2016 17:46_

@waderyan move to TS.

**Comment by mhegazy** [comment] 2016-12-15 22:32
Duplicate of https://github.com/Microsoft/TypeScript/issues/12234

**Closed by mhegazy** 2016-12-15 22:32 UTC
