### ISSUE TITLE
IntelliSense For Untyped Imports in TypeScript Files

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15286] opened 2017-04-20 05:58 UTC
From

**TypeScript Version:**  2.3.1-insider0416

**Code**

1. `npm install snoowrap`
2. In a ts file:

```ts
import * as snoowrap from 'snoowrap'

snoowrap.|
```

3. Trigger intellisense at the `|`

**Expected behavior:**
The import is of an `any` type so no type checking is performed on it.

However, if we instead use a js file with the exact same contents, we do get some suggestions:

<img width="622" alt="screen shot 2017-04-19 at 10 56 02 pm" src="https://cloud.githubusercontent.com/assets/12821956/25215598/658a0c02-2553-11e7-9bf9-57bedd0dfc12.png">

I would also expect these suggestions in TypeScript.

I was actually surprised that TypeScript picked up this IntelliSense for an untyped module in the first place. When was this feature added?

**Actual behavior:**
No suggestions are shown. This is consistent with the intellisense for other `any` types

**Comment by Meligy** [comment] 2017-05-01 05:58
Hello awesome TypeScript maintainer.
Any thoughts on this? Maybe a comment whether it's a bug or by design / expected?

Thanks a lot.

**Comment by mhegazy** [comment] 2017-05-01 16:50
The reason it works in `.js` file is because of the `node_module\snoowrap\dist\snoowrap.js` into your compilation by default.

I would not recommend doing so in a .ts project. you are better off runnign [dts-gen](https://github.com/Microsoft/dts-gen) on it, getting a d.ts and using that instead.

**Comment by Meligy** [comment] 2017-06-30 01:23
`dts-gen` sounds great in theory, but doesn't seem to work well sometimes including the sample package here. I wonder what TypeScript is doing different when processing .JS files in VS Code that I can apply to my `tsconfig.json` or something to get the same behavior. It just feels really funny when the intellisense works in untyped JS but not in typed territory!

**Comment by Meligy** [comment] 2017-06-30 03:06
A few more things:

- If there's a `tsconfig.json` that has `allowJs` set to true, and includes the `.js` file, it gets treated (correctly) as a TS file, but it means it loses intellisense
- When the file is treated as JavaScript file, we get hints from JSDoc, but when it's treated as TypeScript, we lose the JSDoc comments (makes sense in TypeScript in general, not 100% useful when importing a JS module though).

**Comment by mhegazy** [comment] 2017-08-29 19:41
> dts-gen sounds great in theory, but doesn't seem to work well sometimes including the sample package here.

I would say these bugs that should be fixed in dts-gen

> I wonder what TypeScript is doing different when processing .

nothing, it is just that there are many .js files out there, and including them all first results in little value, as the compiler does not usually get much out of them, and result in high resource utilization, in terms of memory and CPU.

> It just feels really funny when the intellisense works in untyped JS but not in typed territory!

For the .js file it is a best effort attempt. it may work for this specific library, but no guarantees on other ones. As i said, you are better off adding a .d.ts.

**Closed by mhegazy** 2017-08-29 19:41 UTC
Labels: VS Code Tracked, Working as Intended
