### ISSUE TITLE
"RangeError: Maximum call stack exceeded" on JSDoc typedef of function

### ISSUE THREAD

**Issue by michaelfig** [microsoft/TypeScript#39647] opened 2020-07-17 22:30 UTC
**TypeScript Version:**  Version 4.0.0-dev.20200717

**Search Terms:** Maximum call stack

**Code**

jsconfig.json:
```js
{
  "compilerOptions": {
    "noEmit": false,
    "emitDeclarationOnly": true,
  },
  "include": ["src/*.js"],
}
```

src/foo.js:
```js
/**
 * @typedef {import('./bar').bar} bar
 */
```

src/bar.js:
```js
export function bar() {
  return 'hello';
}
```

Run: `tsc -p jsconfig.json`

**Expected behavior:**

Generate .d.ts files, or at least, don't crash.

**Actual behavior:**

```
$ tsc -p jsconfig.json 
/Users/michael/.config/yarn/global/node_modules/typescript/lib/tsc.js:84647
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at getTypeOfFuncClassEnumModule (/Users/michael/.config/yarn/global/node_modules/typescript/lib/tsc.js:40811:25)
    at getTypeOfSymbol (/Users/michael/.config/yarn/global/node_modules/typescript/lib/tsc.js:40924:24)
    at getTypeFromJSDocValueReference (/Users/michael/.config/yarn/global/node_modules/typescript/lib/tsc.js:43656:33)
    at getTypeReferenceType (/Users/michael/.config/yarn/global/node_modules/typescript/lib/tsc.js:43642:33)
    at getTypeFromJSDocValueReference (/Users/michael/.config/yarn/global/node_modules/typescript/lib/tsc.js:43670:36)
    at getTypeReferenceType (/Users/michael/.config/yarn/global/node_modules/typescript/lib/tsc.js:43642:33)
    at getTypeFromJSDocValueReference (/Users/michael/.config/yarn/global/node_modules/typescript/lib/tsc.js:43670:36)
    at getTypeReferenceType (/Users/michael/.config/yarn/global/node_modules/typescript/lib/tsc.js:43642:33)
    at getTypeFromJSDocValueReference (/Users/michael/.config/yarn/global/node_modules/typescript/lib/tsc.js:43670:36)
    at getTypeReferenceType (/Users/michael/.config/yarn/global/node_modules/typescript/lib/tsc.js:43642:33)
```

**Playground Link:** 

Couldn't figure out how to do multiple JSDoc files in the playground.

**Related Issues:** 

Not that I could tell.

**Comment by orta** [comment] 2020-07-18 15:28
Thanks this is a dupe of https://github.com/microsoft/TypeScript/issues/36830

( It includes some workarounds too )

**Closed** 2020-07-20 18:00 UTC
Labels: Duplicate
