### ISSUE TITLE
Instanceof on empty class makes variable in else branch never

### ISSUE THREAD

**Issue by henkkuli** [Microsoft/TypeScript#10648] opened 2016-08-31 18:34 UTC
**TypeScript Version:**  nightly (2.1.0-dev.20160831)

**Code**

```ts
class Foo {
}
class Bar {
    public baz: string;
}

let a: Foo|Bar = undefined!;

if (a instanceof Foo) {
    // Some code
} else {
    a.baz = "";
}
```

**Expected behavior:**
No errors or at least error `Property 'baz' does not exist on type 'Foo|Bar'`.

**Actual behavior:** 
Error `Property 'baz' does not exist on type 'never'.`

**Comment by kitsonk** [comment] 2016-08-31 18:41
I am pretty sure this is covered in a number of other tickets, but don't have the time for the search foo...

Essentially instances of `Foo` and instances of `Bar` are structurally the same.  TypeScript's type system for various reasons is structurally typed, and because `Foo` and `Bar` are of compatible public structures, their instances are assignable to each other.  `instanceof` is the only nominal type checking in ECMAScript, but currently TypeScript still treats it as a structural guard, because of the way its type system works.  For TypeScript 2.1 the team continue to look at ways of dealing with `instanceof` in a nominal way, but allow the rest of the type system to work as designed.

So what is happening is that using instance of, you are eliminate both `Foo` and `Bar` from the type and resulting in a `never` type.  In order to work around this current limitation, you would need two classes where their public structure is incompatible for TypeScript to be able to discriminate them.

**Comment by mhegazy** [comment] 2016-08-31 22:02
Duplicate of https://github.com/Microsoft/TypeScript/issues/10422

**Closed** 2016-08-31 22:02 UTC
Labels: Duplicate
