### ISSUE TITLE
Untyped Imports Throw Error Until Type Definition is Created

### ISSUE THREAD

**Issue by alex-ayala** [Microsoft/TypeScript#12839] opened 2016-12-11 21:50 UTC
**TypeScript Version:**  2.1.4

**Code**
```ts
import * as React from 'react';
import Modal from 'react-modal';

export interface GreeterProps extends React.Props<Greeter> {
    whomToGreet: string;
    greeting?: string | (() => string);
}

export class Greeter extends React.Component {
    props: GreeterProps;
    state;
    constructor(props) {
        super(props);
        this.props = props;
        this.state = { isModalOpen: false }
    }

    closeModal () { this.setState({isModalOpen: false}); }

    render() {
        let g = this.props.greeting;

        let greeting = 'Hello';

        if (typeof g === 'string') {
            greeting = g;
        }
        else if (g) {
            greeting = g();
        }

        return <div>{greeting}, {this.props.whomToGreet}</div>;
        /*return (
            <Modal isOpen={this.state.isModalOpen} onRequestClose={this.closeModal}>
                <h1>Close Me With Escape Modal</h1>
                <button onClick={this.closeModal}>Close</button>
                <div>{greeting}, {this.props.whomToGreet}</div>
            </Modal>
        )*/
    }
}
```

package.json
```json
{
  "name": "jsx-demo",
  "version": "0.0.1",
  "description": "JSX in TypeScript Demo Project",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/Microsoft/TypeScriptSamples.git"
  },
  "keywords": [
    "jsx",
    "tsx",
    "typescript",
    "ts",
    "react"
  ],
  "author": "Ryan Cavanaugh (Microsoft)",
  "license": "Apache",
  "bugs": {
    "url": "https://github.com/Microsoft/TypeScriptSamples/issues"
  },
  "homepage": "https://github.com/Microsoft/TypeScriptSamples",
  "devDependencies": {
    "awesome-typescript-loader": "^3.0.0-beta.11",
    "http-server": "0.8.0",
    "source-map-loader": "^0.1.5",
    "typescript": "latest",
    "webpack": "^1.14.0"
  },
  "dependencies": {
    "jquery": "^2.1.4",
    "react": "^15.4.1",
    "react-modal": "^1.6.1"
  }
}
```
tsconfig.json
```json
{
    "compilerOptions": {
        "jsx": "react",
        "outDir": "bin",
        "module": "commonjs",
        "allowJs": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

**Expected behavior:**
With the release of 2.1.4, one of the major features in the release notes was the ability to allow for untyped imports, i.e. if the module is installed it can be used without having to define type definitions for it. TS should compile the above code (which has no type definitions anywhere in the project) without throwing any error message.

**Actual behavior:**
TS compiler throws error message: TS2307:Cannot find module 'react-modal'.

**Note**
I went ahead and created a public [BitBucket repo](https://bitbucket.org/Alex-ayala/ts_importany_issue/) replicating this issue using a simple example.

**Comment by aluanhaddad** [comment] 2016-12-12 01:12
I took a look and it really seemed like a bug, but I think it is intentional, if you look at https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#untyped-imports the example says, in a comment that this behavior
>// Succeeds if `node_modules/asdf/index.js` exists

It looks like the module resolution process is not reading the package.json file which declares that the entry point is `lib/index.js` and is simply looking for `react-modal/index.js`. 
This is definitely counter intuitive but I believe it is correct.

**Comment by alex-ayala** [comment] 2016-12-12 16:41
You're right @aluanhaddad! thanks for looking into this. To make this a bit more intuitive, should I open another issue to fix this so that the compiler just uses the entry point defined by the module itself, rather than always looking for an index.js at the root of the module? Also, I noticed that even though the imported module is brought in as any, trying to access an undefined function/property throws compiler errors. e.g. using this.setState({ /* someProps */ }) within a React.Component class throws the compiler error message: TS2339:Property 'setState' does not exist on type 'SomeReactComponent'. If the module has an implicit any type definition, and I have a class that extends that module, shouldn't the compiler ignore any undefined properties since it is possible that those properties exist within the parent?

**Comment by aluanhaddad** [comment] 2016-12-13 08:59
@alex-ayala looks like this is not intended! Glad I was wrong and I'm looking forward to seeing this work intuitively.

**Comment by tommytroylin** [comment] 2017-01-11 12:01
@aluanhaddad 
FYI.
In some packages the entry point in `package.json` is not a specified `foo/bar/index.js`, but something like `foo/bar.js` or even `foo/bar`.

check this package [nodemon](https://github.com/remy/nodemon)

I wish these cases can be supported.

Thank you in advance.

**Comment by andy-ms** [comment] 2017-02-02 16:14
The example you linked to seems to work just fine with `2.1.4`, but breaks with `2.1.1`. Could you verify that this works for you now?

**Comment by mhegazy** [comment] 2017-02-15 21:52
Closing for now. please reopen if the issue is still around.

**Closed by mhegazy** 2017-02-15 21:52 UTC
Labels: Bug, Needs More Info

**Comment by ondrowan** [comment] 2017-02-22 14:29
@mhegazy I still encounter this problem with [passport-google-oauth2](https://github.com/jaredhanson/passport-google-oauth2).

It defines main in `package.json` as:

```json
"main": "./lib",
```

When I import it in my code it says:

> error TS2307: Cannot find module 'passport-google-oauth20'.`

I'm using TS 2.1.6.

I've also created a repo with the simplest possible code to reproduce it: https://github.com/ondrowan/typescript-untyped-import-issue

**Comment by andy-ms** [comment] 2017-02-22 15:09
That works in `typescript@next`. See #13678.
