### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by Remco0570** [microsoft/TypeScript#58980] opened 2024-06-23 21:44 UTC
f46200bcb5be23df1b1bde25ce6f8bfb671212d1

**Comment by jcalz** [comment] 2024-06-23 21:46
Yes, code. This is working as intended.

**Comment by RyanCavanaugh** [comment] 2024-06-24 15:35
We were briefly considering a9b863a90c0834619fe81553d9ca821674 but yes, f46200bcb5be23df1b1bde25ce6f8bfb671212d1 is where we landed

**Closed by RyanCavanaugh** 2024-06-24 15:35 UTC
Labels: Unactionable
