### ISSUE TITLE
TS produces duplicate changes

### ISSUE THREAD

**Issue by asvetliakov** [Microsoft/TypeScript#21456] opened 2018-01-29 16:41 UTC
**TypeScript Version:**  2.7.0-dev.201xxxxx

TS version: **2.7.0-rc** / **2.7.0-nightly**
VS Code: 1.19.3
OS: macOS 10.13.2

**Problem**
Very often (but not always though), any TS operations which produce changes (rename, autoimport) are doing it for the same file twice, this results into the same file opened twice in VS code:
![screen shot 2018-01-29 at 17 30 10](https://user-images.githubusercontent.com/8881674/35521524-4386ea6a-051a-11e8-8eb5-ddc5599bafae.png)

(Rename operation in this file opened the twin of the same file but with ```~/.../ramble/``` path prefix)

Also looks these opened files are not syncronized - saving one file results into unable to save the other twin, since vs code tells that it content is differ than the saved one.

This didn't happen in TS 2.6

Looking into TS server log i noticed these lines (see ```/Users/``` vs ```/users/```):

```json
{
   "seq":0,
   "type":"response",
   "command":"rename",
   "request_seq":6390,
   "success":true,
   "body":{
      "info":{
         "canRename":true,
         "kind":"parameter",
         "displayName":"postscriptum",
         "fullDisplayName":"postscriptum",
         "kindModifiers":"",
         "triggerSpan":{
            "start":9461,
            "length":12
         }
      },
      "locs":[
         {
            "file":"/Users/asvetl/work/ramble/packages/backendjs/src/repositories/ChatCommunicationRepository.ts",
            "locs":[
               {
                  "start":{
                     "line":276,
                     "offset":40
                  },
                  "end":{
                     "line":276,
                     "offset":52
                  }
               },
               {
                  "start":{
                     "line":274,
                     "offset":73
                  },
                  "end":{
                     "line":274,
                     "offset":85
                  }
               },
               {
                  "start":{
                     "line":272,
                     "offset":15
                  },
                  "end":{
                     "line":272,
                     "offset":27
                  }
               }
            ]
         },
         {
            "file":"/users/asvetl/work/ramble/packages/backendjs/src/repositories/ChatCommunicationRepository.ts",
            "locs":[
               {
                  "start":{
                     "line":276,
                     "offset":40
                  },
                  "end":{
                     "line":276,
                     "offset":52
                  }
               },
               {
                  "start":{
                     "line":274,
                     "offset":73
                  },
                  "end":{
                     "line":274,
                     "offset":85
                  }
               },
               {
                  "start":{
                     "line":272,
                     "offset":15
                  },
                  "end":{
                     "line":272,
                     "offset":27
                  }
               }
            ]
         }
      ]
   }
}
```

Part of the log is available [here](https://pastebin.com/zCfbG8Un).

This is completely killing my workflow, i'd be glad to provide more info if you need.

**Comment by RyanCavanaugh** [comment] 2018-01-29 17:35
The assert triggered at line 40 in that log is probably the root cause here. Any more information on reproducing this would be great, though.

**Comment by mhegazy** [comment] 2018-07-02 22:47
Closing for now. please reopen if there is more information available.

**Closed by mhegazy** 2018-07-02 22:47 UTC
Labels: Bug, Needs More Info
