### ISSUE TITLE
require statement get lost after tsc --watch compile again

### ISSUE THREAD

**Issue by cncolder** [Microsoft/TypeScript#21960] opened 2018-02-15 08:46 UTC
**TypeScript Version:**  2.7.1

**Search Terms:** 

**Code**

```ts
// index.ts
import * as lib from './lib'

export const demo = () => {
    console.log(lib.seq)
}
```

```ts
// lib
export const seq = '/'
```

```json
{
    "compilerOptions": {
        "moduleResolution": "node",
        "module": "commonjs",
        "target": "es5",
        "lib": [
            "esnext"
        ]
    },
    "include": [
        "**/*.ts"
    ],
    "compileOnSave": true
}
```

```json
{
    "name": "typescript271-watch-bug",
    "private": true,
    "version": "0.0.1",
    "license": "MIT",
    "scripts": {
        "start": "tsc -w"
    },
    "devDependencies": {
        "@types/node": "^9.4.6",
        "typescript": "^2.7.1"
    }
}
```

**Run tsc --watch to generate .js files**

```console
npm start

> typescript271-watch-bug@0.0.1 start /Users/colder/Codes.localized/typescript271-watch-bug
> tsc -w
下午4:43:43 - Starting compilation in watch mode...


下午4:43:44 - Compilation complete. Watching for file changes.
```

**Expected behavior:**

`tsc -w` generate same result if code not modified.

**Actual behavior:**

The first time generate js:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var lib = require("./lib");
exports.demo = function () {
    console.log(lib.seq);
};
```

The second time lose require statement in js output.

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/* Pay attention at this line. The require statement disappeared. */
exports.demo = function () {
    console.log(lib.seq);
};
```

**Playground Link:** https://github.com/cncolder/typescript271-watch-bug

**Related Issues:**

**Comment by emraa** [comment] 2018-02-15 08:57
I'm seeing similar behaviour. Initial compile works fine, but when using tsc -w and recompiling after code change, it seems to leave out some imports/requires in generated code.

Reverting TS to version 2.6.2 solves this issue.

**Comment by cncolder** [comment] 2018-02-15 10:20
It seems `typescript@2.8.0-dev.20180215` has resolve this issue.

**Comment by mhegazy** [comment] 2018-02-15 17:27
Duplicate of https://github.com/Microsoft/TypeScript/issues/21478. Fix should be in `typescript@next` and in `typescript@2.7.2`.

**Closed** 2018-02-16 07:54 UTC
Labels: Duplicate
