### ISSUE TITLE
Object.keys is returning an array of strings instead of and [keyof T] array

### ISSUE THREAD

**Issue by pascalwilbrink** [microsoft/TypeScript#54470] opened 2023-05-31 11:34 UTC
# Suggestion
I would suggest that Object.keys returns a list of [keyof T] instead of an array of strings.

## 🔍 Search Terms
Object.keys

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 💻 Use Cases
you can chain directly, without the need to typecast.
Example:
`obj[Object.keys(obj)].{foo}`

**Comment by xiBread** [comment] 2023-05-31 11:47
Duplicate of https://github.com/microsoft/TypeScript/pull/12253

**Comment by MartinJohns** [comment] 2023-05-31 12:24
> ## 🔍 Search Terms
> Object.keys

I'm really surprised you didn't find any existing issue, given that there are so many about this.

**Comment by fatcerberus** [comment] 2023-05-31 13:35
> `obj[Object.keys(obj)].{foo}`

what the f💥

**Comment by RyanCavanaugh** [comment] 2023-05-31 14:53
https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript/55012175

**Closed by RyanCavanaugh** 2023-05-31 14:53 UTC
Labels: Duplicate
