### ISSUE TITLE
Type inference with JSDoc, @template and curried functions

### ISSUE THREAD

**Issue by RedGlow** [microsoft/TypeScript#36201] opened 2020-01-15 11:34 UTC
Issue Type: <b>Bug</b>

(I'm not completely sure this is the right place to report this bug, so point me to the correct place in case)

Let's take this JavaScript code:

```javascript
/**
 * @template T
 * @param {T} a 
 * @returns {(b: T) => T}
 */
const curriedFunction = a => b => b;

const text1 = "hello";
const text2 = "Mattia";

const text3 = curriedFunction(text1)(text2);
```

The types that VSCode infers are:
```typescript
const curriedFunction: <T>(a: T) => (b: T) => T
const text1: "hello"
const text2: "Mattia"
const text3: T
```
All types are correct expect for `text3`. In fact, if I look at the type instantiation for the `curriedFunction` call, I get this:
```typescript
const curriedFunction: <string>(a: string) => (b: T) => T
```

Now, it seems to me that the first `T` instantiation is correctly bound to `string`, but then the return value _doesn't_ get its `T` bound to the same template variable. Am I missing something, or this is the type that I should get?
```typescript
const curriedFunction: <string>(a: string) => (b: string) => string
```

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (17.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
gitlens|eam|10.2.0
vscode-npm-script|eg2|0.3.10
prettier-vscode|esb|3.18.0
vscode-import-cost|wix|2.12.0

</details>

**Comment by DanielRosenwasser** [comment] 2020-01-15 23:15
Looks like `T` isn't getting instantiated properly!

**Comment by IllusionMH** [comment] 2020-01-15 23:41
TBH `@templates` are not part of JSDoc by itself and proposed code is not valid in Closure Compiler (at least online version in Advanced mode will show an error).

To achieve proper checks in your case you'll need 2 generic types which AFAIK not possible with `@templates` syntax.
Even with `T` instantiated for nested function it still [behaves strange in JS](https://www.typescriptlang.org/play/index.html?useJavaScript=true#code/PQKhFgCgAIWgBALgTwA4FNoG8A8AVAPgAoBDALjwEpoBeA6IgIzOitvrwF8pZgoBjAPYA7AM6Jo-AK4AnGQEt0AEwBiU4f0TyRtaCXbRGBxgG4oAkeOiJ0AD0QBGXQCIAFugA2Hwc7OQhYhI29gBMLgCyJIhaJL7m-pZBdogAzLrScoqq6prawkTBjpQFySGUfgFWwoIAonKCMumyCspqGloiJfYOxQ4hKeVAA)

If you rely on TS checks only (because it's not valid CC code) you can utilize separate `.d.ts` file.

`helpers.d.ts`
```ts
type Nested<T> = (b: T) => T;

export type Curried = <T>(a: T) => Nested<T>;
```
`index.js`
```js
/** @type {import('./helpers').Curried} */
const curriedFunction = a => b => b;

const text1 = "hello";
const text2 = "Mattia";

const text3 = curriedFunction(text1)(text2);

const correctError = curriedFunction(text1)(123);
```

----

_I'm really curious if it's possible to achieve with JSDoc only and/or with one generic function, but in our case we had to use `.d.ts`  for similar tasks._

**Comment by sandersn** [comment] 2020-01-15 23:57
This has been a bug for a long time. Moving to 3.9.

**Comment by sandersn** [comment] 2020-01-16 00:53
@IllusionMH this should work; it's basically equivalent to the Typescript type `<T>(a: T) => (b: T) => T`. Our implementation of `@template` is based on Closure, except supporting Typescript types, not Closure types.

@RedGlow In the meantime here's a workaround:

```
/**
 * @type {<T>(a: T) => (b: T) => T}
 */
```

or even better:

```
/**
 * @type {(a: unknown) => <T>(b: T) => T}
 */
```

**Comment by IllusionMH** [comment] 2020-01-16 01:07
Tried `@type {<T>(a: T) => (b: T) => T}` in playground ([link from comment above](https://www.typescriptlang.org/play/index.html?useJavaScript=true#code/PQKhFgCgAIWgBALgTwA4FNoG8A8AVAPgAoBDALjwEpoBeA6IgIzOitvrwF8pZgoBjAPYA7AM6Jo-AK4AnGQEt0AEwBiU4f0TyRtaCXbRGBxgG4oAkeOiJ0AD0QBGXQCIAFugA2Hwc7OQhYhI29gBMLgCyJIhaJL7m-pZBdogAzLrScoqq6prawkTBjpQFySGUfgFWwoIAonKCMumyCspqGloiJfYOxQ4hKeVAA)), but it won't report error on call `curriedFunction(text1)(123)`.

Is it limitation of `checkJS` or not expected behavior?

On the other hand approach with `.d.ts` and `@type {import('./helpers').Curried}` has same result as `const curriedFunction: <T>(a: T) => (b: T) => T = a => b => b;`
[Playground](https://www.typescriptlang.org/play/index.html#code/MYewdgzgLgBMCuAnRBLApgEwGLzMKK4AXADwAqAfABQCGRZAlDALwUxUBGRMjLbZLGDT4wOIjgG4AsAChZoSLChoAHlACMggEQALNABt9ILdJkLoMZWoBM2gLI0oBGidnzwFq1ADMghMnRsXHxCMCovdQZw1ShrBlNzWDRkEEQAQQgAURUABzR8TD8kVEwcPAJwaLVIqnVrb3igA)

**Comment by sandersn** [comment] 2020-01-16 01:18
@IllusionMH that is also not expected. Can you file a new bug?

**Comment by zavr-1** [comment] 2020-01-28 18:39
@IllusionMH you're wrong as `@templates` are part of _Closure Compiler_: https://github.com/google/closure-compiler/wiki/Generic-Types

**Comment by IllusionMH** [comment] 2020-01-28 18:49
@zavr-1 I never said that `@templates` are not part of CC.

I said that: 
1. > `@templates` are not part of JSDoc by itself

    Because they are only valid in CC and TS

1. > proposed code is not valid in Closure Compiler

    Because CC will raise error on `@returns` type - `(b: T) => T` is invalid CC, but valid TS

Because it's only valid TS and no need to support CC - I proposed 2 TS "specific" solutions.

**Comment by zavr-1** [comment] 2020-01-28 18:50
@IllusionMH  what is jsdoc anyway? ;) plus it's not working in the compiler not because of templates but because of arrow functions which are not supported by CC
here's passing compilation 
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%250A%2520*%2520%2540template%2520T%250A%2520*%2520%2540param%2520%257BT%257D%2520a%250A%2520*%2520%2540returns%2520%257Bfunction(T)%253A%2520T%257D%250A%2520*%252F%250Aconst%2520curriedFunction%2520%253D%2520a%2520%253D%253E%2520b%2520%253D%253E%2520b%253B%250A%250Aconst%2520text1%2520%253D%2520%2522hello%2522%253B%250Aconst%2520text2%2520%253D%2520%2522Mattia%2522%253B%250A%250Aconst%2520text3%2520%253D%2520curriedFunction(text1)(text2)%253B

**Comment by zavr-1** [comment] 2020-01-28 18:56
@IllusionMH  and i'm sorry i said you were wrong about jsdoc. but i don't see jsdoc as an existing system, it's a living standard so if `@template` is used in CC and TS, it is part of jsdoc. jsdoc not software, it's a concept of annotating js isn't it. if jsdoc as a package doesn't support it, it only means that it's deficient and not up to date with current state of art.

**Comment by sandersn** [comment] 2020-04-06 17:20
Another workaround, which suggests that the problem is a fairly simple missing syntactic check:

```ts
/**
 * @template T
 * @param {T} a
 * @returns {(b: T) => T}
 */
function seq2(a) { return b => b }
```

Also, @IllusionMH `@type {<T>(a: T) => (b: T) => T}` is working for me when I tested it on master, 3.3 and 3.8.

**Comment by IllusionMH** [comment] 2020-04-06 17:26
@sandersn yep, that works as expected in editor, but I initially tested it in playground where it doesn't present errors in JS mode https://github.com/microsoft/TypeScript/issues/36494#issuecomment-580022512 and tracked in https://github.com/microsoft/TypeScript-Website/issues/203

**Comment by sandersn** [comment] 2020-04-06 21:56
When `getOuterTypeParameters` is called on `(b: T) => T`, it doesn't find its outer type parameter `T` because it doesn't recognise `const seq1 = a => a => b` as a location that might have type parameters. It does fine with `function seq2(a) { ... }` because functions are expected to have type parameters in TS.

**Closed** 2020-04-07 15:04 UTC
Labels: Bug, Domain: JSDoc, Domain: Type Inference, Effort: Difficult, Fix Available, checkJs, help wanted
