### ISSUE TITLE
Cascade operator

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/TypeScript#12017] opened 2016-11-03 09:10 UTC
I couldn't find this request in the issue backlog, so I'd like to request support for [method and property cascades](http://news.dartlang.org/2012/02/method-cascades-in-dart-posted-by-gilad.html), e.g. via the `..` operator, familiar from other languages like Dart.

While this is merely syntactic sugar, it's very convenient - take the following example:

```
function request(method: string, url: string, body?: string) : Promise<XMLHttpRequest> {
    return new Promise<XMLHttpRequest>(function (resolve, reject) {
        var xhr = new XMLHttpRequest()

        xhr.open(method, url)

        xhr.onload = function () {
            if (this.status >= 200 && this.status < 300) {
                resolve(xhr)
            } else {
                reject(xhr)
            }
        }

        xhr.onerror = function () {
            reject(new Error(`unable to complete ${method} request for: ${url}`))
        }
        
        xhr.send(body)
    })
}
```

We can discard the intermediary variable and references to it, so the above becomes:

```
function request(method: string, url: string, body?: string) : Promise<XMLHttpRequest> {
    return new Promise<XMLHttpRequest>(function (resolve, reject) {
        new XMLHttpRequest()
            ..open(method, url)
            ..onload = function () {
                if (this.status >= 200 && this.status < 300) {
                    resolve(xhr)
                } else {
                    reject(xhr)
                }
            }
            ..onerror = function () {
                reject(new Error(`unable to complete ${method} request for: ${url}`))
            }
            ..send(body)
    })
}
```

Dart having a very similar syntax, I believe this feature can basically be referenced 1:1 from Dart?

**Comment by aluanhaddad** [comment] 2016-11-03 10:05
Duplicate of #8536

**Closed** 2016-11-03 17:20 UTC
Labels: Duplicate
