### ISSUE TITLE
TypeScript diagnostics gets corrupted after typing `Map`

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#47895] opened 2022-02-13 08:02 UTC
Latest insider broke TS entirely for me. When writing a typed Map I get errors out of nowhere:

![Recording 2022-02-13 at 09 01 56](https://user-images.githubusercontent.com/900690/153744464-0df7a254-e191-4f80-8221-4f5467b36b24.gif)

**Comment by mjbvz** [comment] 2022-02-14 21:17
Here's a TS Server log of this happening:

[tsserver-log-Y1xK2u.zip](https://github.com/microsoft/TypeScript/files/8064066/tsserver-log-Y1xK2u.zip)

I reproduce this in the VS Code codebase by typing out `private map = new Map<string, number>()` in a class. This corrupted the diagnostics. A few seconds later I ran format and the document was incorrectly formatted

**Comment by andrewbranch** [comment] 2022-02-14 21:30
Possibly an incremental parsing bug? Probably best to start with a bisect and go from there.

**Comment by DanielRosenwasser** [comment] 2022-02-15 00:49
First appears in `typescript@4.4.0-dev.20210715` from what I can tell.

```ts
//// class C {
////     map = new Set<string, number>/*$*/
////
////     foo() {
////
////     }
//// }
```

Insert `()` at the `/*$*/` marker and expect no errors.

**Comment by DanielRosenwasser** [comment] 2022-02-15 01:16
Looking at [this search query](https://github.com/microsoft/TypeScript/pulls?q=is%3Apr+merged%3A2021-07-14..2021-07-15+is%3Aclosed+), this was likely caused by https://github.com/microsoft/TypeScript/pull/43005

**Comment by DanielRosenwasser** [comment] 2022-02-15 23:19
If we can, we should try to back-port this to 4.6.

**Closed** 2022-03-01 01:05 UTC
Labels: Bug, Fix Available
