### ISSUE TITLE
The type returned by Array.prototype.find() is not narrowed

### ISSUE THREAD

**Issue by exoRift** [microsoft/TypeScript#53488] opened 2023-03-24 17:43 UTC
# Bug Report

### 🔎 Search Terms

.find
narrow find

### 🕗 Version & Regression Information

5.0.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nKBeKBvAsAKCjqATASwGcBjAJwIFsCA7AQ2DjIC4oByAIzrLYBotcUAG50ANgFcIrGuMocIZLAF8oAHzQDchUhWr1GLdlwBefTThESpUIsAo0A5sqxYAZuJolgBODSh0iIgVgAGU7WgcoAAowbjpKVlt7BwBKNCU3Dy8fPwCgsmAAOVl5MmjYsnjpEoU01AzMTM9vXyh3T3K4hNgEAG0AXTrzKBJfWza4DzxkKAr4gDpXWjwomLSkAD5Z+e1yKloGJmQkFE5uNhSXbFwCV2iAQldJmjw0sghgcTIaK8E84OKcgUUSeU3mlkkaQA9FCoAAeKDEIiSX43O4g554HbEPZ6Q5lE6nLg8NL-AqA0oYsEQiDQ2EImiIMBkOAcUQQSjKIA)

### 💻 Code

```ts
type Foo = {
    discriminator: 'bar',
    value: number
} | {
    discriminator: 'baz',
    value: string
}

function assertString (param: string) {}
function assertNumber (param: number) {}

function func (param: Foo[]) {
    const found = param.find((p) => p.discriminator === 'bar')

    if (!found) return

    assertNumber(found.value) // < issue

    if (found.discriminator === 'bar') assertNumber(found.value) // < no problem
}
```

### 🙁 Actual behavior

The find does not narrow the returned type

### 🙂 Expected behavior

The logical flow SHOULD narrow it. Typescript IS capable of this. I understand the check is in another scope, but can't it be propagated upwards?

**Comment by MartinJohns** [comment] 2023-03-24 17:45
Duplicate of #38945 and others.

**Comment by MartinJohns** [comment] 2023-03-28 16:27
It's the same. `find()` has two overloads: one with a function returning just a `boolean`, this can't be used for narrowing because the `boolean` might have nothing to do with the type, and another with a function returning a type guard. The latter is used for narrowing, but you call the first overload with just a `boolean`.

Another related issue is #38390, although the discriminator case is not explicitly listed there.

**Closed** 2023-03-30 21:44 UTC
Labels: Duplicate
