### ISSUE TITLE
Error in detecting type if there is a OR logic in if

### ISSUE THREAD

**Issue by r1si** [microsoft/TypeScript#49973] opened 2022-07-20 13:49 UTC
# Bug Report
### 🔎 Search Terms
- detect type
- OR logic
- ||

### 🕗 Version & Regression Information
This appear in all recent TS.  (demo is with 4.4.4)

### ⏯ Playground Link

[Playground link with demo of bug](https://codesandbox.io/s/relaxed-wind-vfotf7?file=/src/index.ts)

### 💻 Code

All code  with comment is already in playground link watch error on line 19 of index.ts 
But here:

```ts
import { TypeOfMain, getMainObj } from "./external";

let mainObject: false | TypeOfMain = false;

mainObject = getMainObj();

const randomAlternative = Math.random();

// with OR in IF error on line 20

if (
  randomAlternative > 0.5 ||
  (mainObject && Number(mainObject.value) <= 250)
) {
  if (randomAlternative > 0.5) {
    console.log(`Error in random ${randomAlternative}`);
  } else {
    // error mainObject must be TypeOfMain not false
    console.log(`Error in main ${mainObject.value}`); // <--- Error
  }
}

// with double IF no error on line 31

if (randomAlternative > 0.5) {
  if (mainObject && Number(mainObject.value) <= 250) {
    if (randomAlternative > 0.5) {
      console.log(`Error in random ${randomAlternative}`);
    } else {
      // no error
      console.log(`Error in main ${mainObject.value}`);
    }
  }
}
```

### 🙁 Actual behavior

Error on line 19 mainObject must be TypeOfMain not false

### 🙂 Expected behavior

Like line 31

**Comment by MartinJohns** [comment] 2022-07-20 15:03
IMO it's a duplicate of #30869. Just more elaborate.

**Comment by RyanCavanaugh** [comment] 2022-07-20 15:22
We don't have any feasible way to detect logic like this. I haven't seen any real examples where the code can't be rewritten without double conditionals so this isn't something likely to be improved.

**Comment by r1si** [comment] 2022-07-20 15:36
@RyanCavanaugh
Indicate with a specific warning, all type evaluations within a if scope with an OR logic?
That is, the design limitation is clear, but if not indicated it is questionable

**Closed** 2024-02-24 00:19 UTC
Labels: Design Limitation
