### ISSUE TITLE
Inexact type inference when using spreading & union type

### ISSUE THREAD

**Issue by Maximebpro** [Microsoft/TypeScript#28843] opened 2018-12-04 13:17 UTC
There seems to have type inference issue when spreading objects where properties use union types and we use discrimination. Example worth 1000 words:

```
type AorB = 'A' | 'B';

type someAlphabet = {
  value: AorB;
}

const playWith = (alpha: someAlphabet) => {
  if (alpha.value === 'A') {
    alpha.value = 'B';
    return { ...alpha };
  } else {
    alpha.value = 'B';
    return { ...alpha };
  }
}

const playWithOk = (alpha: someAlphabet) => {
  if (alpha.value === 'A') {
    alpha.value = 'B';
    return { ...alpha, value: alpha.value };
  } else {
    alpha.value = 'B';
    return { ...alpha, value: alpha.value };
  }
}
```
Signature of `playWith` and `playWithOk` are different. `playWithOk` inferred correctly where `playWith` did not.

My example here is kinda stupid but seems to easily show the issue.
If necessary, I can try to bring a more realistic example inspired from my real-world code.

The primary pain point here is to have to "help" typescript check `value` type.

**Expected behavior:**
```
const playWith: (alpha: someAlphabet) => { value: "B"; }
const playWithOk: (alpha: someAlphabet) => { value: "B"; }
```
**Actual behavior:**
```
const playWith: (alpha: someAlphabet) => { value: AorB; }
const playWithOk: (alpha: someAlphabet) => { value: "B"; }
```
**Playground Link:** http://www.typescriptlang.org/play/#src=type%20AorB%20%3D%20'A'%20%7C%20'B'%3B%0D%0A%0D%0Atype%20someAlphabet%20%3D%20%7B%0D%0A%20%20value%3A%20AorB%3B%0D%0A%7D%0D%0A%0D%0Aconst%20playWith%20%3D%20(alpha%3A%20someAlphabet)%20%3D%3E%20%7B%0D%0A%20%20if%20(alpha.value%20%3D%3D%3D%20'A')%20%7B%0D%0A%20%20%20%20alpha.value%20%3D%20'B'%3B%0D%0A%20%20%20%20return%20%7B%20...alpha%20%7D%3B%0D%0A%20%20%7D%20else%20%7B%0D%0A%20%20%20%20alpha.value%20%3D%20'B'%3B%0D%0A%20%20%20%20return%20%7B%20...alpha%20%7D%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20playWithOk%20%3D%20(alpha%3A%20someAlphabet)%20%3D%3E%20%7B%0D%0A%20%20if%20(alpha.value%20%3D%3D%3D%20'A')%20%7B%0D%0A%20%20%20%20alpha.value%20%3D%20'B'%3B%0D%0A%20%20%20%20return%20%7B%20...alpha%2C%20value%3A%20alpha.value%20%7D%3B%0D%0A%20%20%7D%20else%20%7B%0D%0A%20%20%20%20alpha.value%20%3D%20'B'%3B%0D%0A%20%20%20%20return%20%7B%20...alpha%2C%20value%3A%20alpha.value%20%7D%3B%0D%0A%20%20%7D%0D%0A%7D

**Related Issues:**

**Comment by DanielRosenwasser** [comment] 2018-12-08 01:37
See #26645. Marking as a duplicate of #10065.

**Closed** 2018-12-12 10:00 UTC
Labels: Duplicate
