### ISSUE TITLE
Typescript incorrectly resolves discriminated unions of indexed types

### ISSUE THREAD

**Issue by bibachhetri** [microsoft/TypeScript#37052] opened 2020-02-26 19:12 UTC
**TypeScript Version:**  3.8-Beta

**Search Terms:** discriminated unions indexed types

**Expected behavior:**
`b1` should be assignable to `a1`

**Actual behavior:**
The following error `Type '"B"' is not assignable to type '"A"'`

**Code**
```ts
type TinyModel = {
    "A": "A" | "B";
    "B": "B";
}

type TinyId<T extends keyof TinyModel> = {
    type: TinyModel[T];
}

let a1: TinyId<"A">;
let b1: TinyId<"B">;

// Should be semantically equivalent to a1 & b1
let a2: { type: "A" | "B" };
let b2: { type: "B" };

function fn1() { a1 = b1; } // this should work, but doesn't
function fn3() { a2 = b2; }

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
let a1;
let b1;
// Should be semantically equivalent to a1 & b1
let a2;
let b2;
function fn1() { a1 = b1; } // this should work, but doesn't
function fn3() { a2 = b2; }

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ts=3.8-Beta&ssl=1&ssc=1&pln=19&pc=1#code/C4TwDgpgBAKglgOxAWQPYBMIBsoF4oDeAsAFBTlQBEAgpQFxW1QA+VAQpQNykXv1-cSAX1KlQkWIhABJdAB4YUCAA9gEBOgDOUANYQQqAGaSkaTFgB8eQjwriIDeKYzYA2jAC6gkSVJYIwFAAhgCMjlKycjSUFoL+gQBGYSYy8pQcsaIkAPTZUADKABaoAK5Y6FAJ0JoQALZBCMBwAMZBWFggSgCOJXAAbm3qgcCowSFQAGSVIX4BwQBMDARQ9gzRLHxQQnFzCYuEK+AOm9tZhiUIzU2oCFCGCCEAFACUB6HWSZxbULkrhXDaTTFMoVADuqAATjoADSVEqBdCoCCaBAAcmApHOl2ut3uAGYXm95h95l8fEA)

**Comment by jcalz** [comment] 2020-02-26 21:15
Haven't checked if this is a duplicate yet but whatever the issue is doesn't seem to have to do with discriminated unions (or even necessarily unions):
```ts
type Foo = {
    "a": unknown
    "b": string;
}

type Bar<T extends keyof Foo> = {
    type: Foo[T];
}

const err: Bar<"a"> = null! as Bar<"b">; // error
// Bar<"b"> is not assignable to Bar<"a">

const okay: { type: unknown } = null! as { type: string };
```

[Playground](https://www.typescriptlang.org/play/?ts=3.8-Beta#code/C4TwDgpgBAYg9nKBeKBvAsAKCjqAiAQzwC4oBXAOwGsK4B3CrXfAIxKgGdgAnASwoDmAbiwBfLFlCQoAIQLcAPABUoEAB7AIFACYcoVCCDgAzWAgB8yNE1xSIpeHADaSgLojM4zFgDGcClyq3NykcoqEeJYoFGQANrEAhFAEemEKeGzmQlAA9DlB3HDcWHmy8umZULx6tMDJHBy8AhQELLHQwIhpEeYSmH4BdXBUBCCkqFB2pJQ09BRQolYx8UkpaJPg9pw8-AIL2UA)

**Comment by RyanCavanaugh** [comment] 2020-02-26 22:17
Not sure why we're not falling back to structural comparison here.

Workaround
```
type TinyId<T extends keyof TinyModel> = T extends keyof TinyModel ? { type: TinyModel[T] } : never;
```

**Comment by ahejlsberg** [comment] 2020-02-26 23:12
I believe the issue here is that we measure indexed access types such as `TinyModel[T]` as invariant, and since `TinyId<T>` contains a property of such a type, we consider it to be invariant in `T`. Effectively our variance measurement is more conservative than a structural check in this case. We do have provisions for tagging measurements as unreliable (which causes a follow-up structural check in the failure case), but we only do that for certain mapped types and rest parameters. We could try to do it for indexed access types as well, but it may have undesirable performance impact.

**Comment by ahejlsberg** [comment] 2020-02-26 23:13
@weswigham Don't recall if you've experimented with this before.

**Comment by weswigham** [comment] 2020-02-27 01:15
`TinyModel[T]` is only covariant in `T` - but `"a"` and `"b"` are obviously not covariantly related; the issue is that variance reasoning about how `T` is possibly related between instances does not include any information from the constraint of `TinyModel[T]` as a whole (which requires information about `TinyModel` to be known). I don't think I've directly experimented with it, but adding `Unreliable` markers to access positions when the object type is non-generic should allow the structural fallback, yeah.

**Comment by mmorearty** [comment] 2020-02-27 01:25
It's also worth mentioning that the compiler behavior changed at some point. The code in the playground example compiles in TS 3.3.3, but not in TS 3.5.1. (Also, thanks for the workaround, @RyanCavanaugh!)

**Comment by ahejlsberg** [comment] 2020-02-28 15:26
@weswigham I does seem that when a type variable is used as the index type in an indexed access type, its variance effectively becomes unmeasurable (because a relation between property names implies nothing about a relation between the types of those properties).

**Comment by jchurchill** [comment] 2020-03-08 05:48
I've found a simpler workaround that doesn't involve conditional types: the type indexing must occur external to the definition of the object's shape. As an example, here's a slight modification to fix @jcalz 's example:

```ts
type Foo = {
    "a": unknown
    "b": string;
}

type BarInner<T> = { type: T };
type Bar<T extends keyof Foo> = BarInner<Foo[T]>;

const err: Bar<"a"> = null! as Bar<"b">; // no longer an error!
```

**Comment by ahejlsberg** [comment] 2020-10-26 15:39
I'm closing this as a design limitation. The core issue is that we conservatively measure most indexed access types as invariant, where structural comparisons might be less restrictive. For example, see my comment [here](https://github.com/microsoft/TypeScript/issues/32674#issuecomment-716192565).

**Closed** 2021-06-01 22:27 UTC
Labels: Design Limitation
