### ISSUE TITLE
Promise<T> should be Promise<T1,T2>

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#22162] opened 2018-02-24 01:00 UTC
Sorry if this is a dupe issue, but I am having trouble determining how to solve some typing issues surrounding promises.

If we have a method:

```typescript
 foo(bar) : Promise<boolean | string> {
   if(bar){
      return Promise.resolve(true);   // boolean type
    }
    return Promise.reject('a string');  // string type
 }
```
I am really really confused, why the typings for Promises don't take two parameters, should it not be:

```typescript
 foo(bar) : Promise<boolean, string> {    // use , instead of |
   if(bar){
      return Promise.resolve(true);   
    }
    return Promise.reject('a string');
 }
```

Currently, I am trying to solve this SO issue, and yet again the problem of specifying the different resolution types is coming up. I guess I just want to know why it is this way.

https://stackoverflow.com/questions/48954365/use-generics-to-specify-type-of-return-value/48958224

**Comment by jack-williams** [comment] 2018-02-24 01:26
Do you intend the second type (call it  `E`) to be the input type to the `catch`  or `onrejected` continuations? The input to these functions can also come from a `throw`, not just `Promise.reject`, and as TypeScript doesn't do effect typing it wont track this.

I think rather than making promises (pun intended) the checker can't keep, they just treat the error type as `any`.

**Comment by DanielRosenwasser** [comment] 2018-02-24 02:01
Looks like a duplicate of #5413 (#3834 is also possibly related?)

**Comment by ORESoftware** [comment] 2018-02-24 04:05
@jack-williams yeah `Promise<boolean,string>` means the resolved type is always a boolean, and the rejected type is always a string, nothing too crazy... lol...is it too much to ask? idk

**Closed** 2018-03-14 19:51 UTC
Labels: Duplicate
