### ISSUE TITLE
Variable is inferred incorrectly if modified in function within the scope

### ISSUE THREAD

**Issue by marcus13371337** [microsoft/TypeScript#56990] opened 2024-01-09 11:25 UTC
### 🔎 Search Terms

type inferring error

### 🕗 Version & Regression Information

I get the same error in `3.3.3` to `5.3.2`

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.3#code/ATDGHsDsGcBdgLYE8BiBXSpgF5gAoBKHAPmAG8AoEEAGwFN4BDALmDgCcBLSAc2AB9gkNDRo4hImgG4KVahBjxoEAA50AJikjjCJcnOrBG4gEQAjGoxMzDAXxkG2qjVsIPDsJGuABBcZ7VwADMjG2B7IA

### 💻 Code

```ts
  const myFunc = () => {
    let a: string | null = null;

    const scopedFn = () => {
      a = "bla";
    };

    scopedFn();

    type A = typeof a;
  };
```

### 🙁 Actual behavior

`type A` is inferred as `null`

### 🙂 Expected behavior

`type A` is inferred as `string | null`

**Comment by MartinJohns** [comment] 2024-01-09 11:40
Another duplicate of #9998.

**Closed** 2024-01-12 01:29 UTC
Labels: Duplicate
