### ISSUE TITLE
vscode will not auto import node modules packages correctly

### ISSUE THREAD

**Issue by dantman** [microsoft/TypeScript#30472] opened 2019-01-19 08:38 UTC
Issue Type: <b>Bug</b>

There was a similar issue to this in the past. However this is **NOT** a duplicate. The old issue was fixed with an upgrade to TypeScript 3.x and/or adding `"baseUrl": "."`. However **this** issue happens under TypeScript 3.2.2 and adding `"baseUrl": "."` does not fix it.

I disabled all my extensions and tested the same thing in the latest Insiders release. It still exists.

## Steps to reproduce

1. Open a new folder workspace
2. Use the following `package.json`
  ```json
  {
    "name": "vscode-auto-complete-issue",
    "version": "1.0.0",
    "license": "ISC",
    "dependencies": {
      "core-decorators": "^0.20.0"
    }
  }
  ```
3. `npm install`
4. Save the following to `jsconfig.json`
  ```json
  {
    "include": [
      "src/**/*"
    ],
    "compilerOptions": {
      "target": "esnext",
      "module": "es2015",
      "allowSyntheticDefaultImports": true,
      "experimentalDecorators": true
    }
  }
  ```
5. Use the following `src/test.js`
  ```js
  class Foo {
    @decorate()
    method() {}
  }
  ```
6. Use your intellisense keybinding (usually Ctrl+Space) after `@decorate` to autocomplete decorate with the function from core-decorators.

## What should happen
The line added should simply import `core-decorators`.
```js
import {decorate} from 'core-decorators';
```

## What actually happens
The import line uses a relative (`..`) path to the `node_modules` folder.
```js
import {decorate} from '../node_modules/core-decorators';
```

If you modify `jsconfig.json` to add `"baseUrl": "."` to `compilerOptions` the path will instead start with node_modules.
```js
import {decorate} from 'node_modules/core-decorators/index';
```

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|16.00GB (0.71GB free)|
|Process Argv|-psn_0_53261|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by mjbvz** [comment] 2019-03-18 21:12
Tested with TS 3.4.0-dev.20190316

This seems related to using ` "target": "esnext",` in the jsconfig. Here's a git repo with example project: https://github.com/mjbvz/ts-30472

**Comment by RyanCavanaugh** [comment] 2019-03-19 16:19
I'm inclined to say this is working as intended. The ES2015 module system doesn't specify that a bare name `foo` should resolve to a spine-located folder `node_modules/foo` - only CommonJS does. If you *actually* are using a file-based ES2015 module resolver, then the only correct path is the relative form `../node_modules/core-decorators`

**Comment by dantman** [comment] 2019-03-19 18:55
@RyanCavanaugh The ES2015 module system also does not say that the "main" from package.json should be looked up, that ".js" extensions can be stripped, or that a folder can have an "index.js" file.

So if you are really going with browser paths then `../node_modules/core-decorators` and `node_modules/core-decorators/index` are both still wrong, as in a browser the only path that will work is `node_modules/core-decorators/index.js`.

So clearly TypeScript is still going by file loader semantics.

> The ES2015 module system doesn't specify that a bare name `foo` should resolve to a spine-located folder `node_modules/foo` - only CommonJS does.

This is also incorrect. [CommonJS modules](http://wiki.commonjs.org/wiki/Modules/1.1.1) do not specify that bare modules come from a `node_modules` folder. CommonJS modules were not created by Node.js, we use node_modules because Node's implementation details became the de-facto standard for module resolution.

----

So currently this is definitely not working as intended. The paths are incorrect for plain es2015/browser imports. And they are also incorrect for Node style imports. And using `module: commonjs/es2015` doesn't tell you what module resolution style is being used because neither es2015 modules nor commonjs modules specify the path to the bare module as `node_modules`.

I would recommend defaulting to assuming Node.js style lookups. Because clearly other parts of typescript/vscode are already assuming that.

If you want to support relative browser style imports, then you'll need to add another property to specify what module lookup style is being used (url, commonjs (optional, with another property to define the conceptual namespace root), node style (includes node_modules as the root and package.json lookup)).

**Comment by RyanCavanaugh** [comment] 2019-03-19 20:05
> I would recommend defaulting to assuming Node.js style lookups

`module: commonjs` is the default! You have to manually specify a different module target to change this, which you did, and TypeScript took you at your word and stopped assuming that `node_modules` was something that could be looked up.

>  CommonJS modules do not specify that bare modules come from a node_modules folder

CommonJS is understood by TS to be "CommonJS as implemented by the overwhelmingly predominant CJS resolve, Node, which uses `node_modules` as a lookup location" because we do have to fill in the gaps of the "Unspecified" part of that wiki page.

**Comment by dantman** [comment] 2019-03-19 21:04
> `module: commonjs` is the default! You have to manually specify a different module target to change this, which you did, and TypeScript took you at your word and stopped assuming that `node_modules` was something that could be looked up.

I meant defaulting to Node.js style path lookups in all module types. Use module to specify the file format/syntax, not the path lookup. Just about all the module syntaxes can be used with multiple path lookup patterns. And use a different property which defaults to node style imports to specify what module resolution pattern to use. e.g. `"resolve-module": "node"` (default), `"resolve-module": "html"`.

----

Please also take into account that currently Node.js style lookups **is** the default / widest used module resolution pattern for es2015. The first ever implementation IIRC was Babel which just transpiled to CommonJS and even when better implementations were implemented (WebPack, Rollup, ESM, etc) they used Node.js lookups. The browser style lookups in browsers were only implemented well after large amounts of of code were already in production using es2015 modules with Node.js style module resolution. And I expect it is still true today that the majority of TypeScript/vscode users are writing ES2015 importing code using a Node.js module resolution.

So honestly the default module resolution for es2015 is Node style module resolution. Also worth noting, you don't even need a new property immediately for the vscode use case. vscode already has an "Input Module Specifier" setting that can be set to "relative" to force it to always use relative imports to node_modules which should make it compatible with browser imports. The majority of us who use Node.js module lookups however, don't have that level of control because "auto" is already the default and is where this bug is being encountered.

----

Honestly this feels a bit strange. Neither CommonJS nor ECMAScript specify where bare imports come from (CommonJS leaves the "conceptual module namespace root" unspecified and ECMAScript makes puts the entire resolution algorithm into an implementation-defined [HostResolveImportedModule](https://www.ecma-international.org/ecma-262/9.0/#sec-hostresolveimportedmodule)). For CommonJS, TypeScript's behaviour is to fill in the unspecified by assuming you are using the most common implementation (Node style module imports). But for ES2015, TypeScript's behaviour is to fill in the unspecified portion by assuming you are **not** using the most common implementation and to spit out something that is not correct for any of the current implementations.

**Comment by RyanCavanaugh** [comment] 2019-03-19 22:18
> spit out something that is not correct for any of the current implementations.

What loaders don't support relative paths?

**Comment by dantman** [comment] 2019-03-19 22:49
> > spit out something that is not correct for any of the current implementations.
> 
> What loaders don't support relative paths?

The current implementation does not output relative paths compatible with loaders other than Node.js/CommonJS. The only major implementation other than Node.js style module resolution is html/browser module resolution. html/browser module resolution does not support omitting `.js` or importing `index.js` from a directory path.

However the current implementation outputs `../node_modules/pkgname` by default for es2015 imports.

- This is wrong for **Node style imports** (should be `pkgname`) because while it works, it breaks the package's ability to change "main" and breaks node's ability to load from a higher level directory.
- It's extra wrong for **WebPack imports** because it bypasses `module`, which means that the ES2015 code will be importing CommonJS modules instead of ES2015 modules.
- And it's wrong for **browser imports** because the browser does not automatically resolve `index.js`, to be correct for browser imports the line needs to be `../node_modules/pkgname/index.js`. Likewise `node_modules/core-decorators/index` would also be wrong because the browser does not add `.js` to the url.

In this specific case TypeScript has also screwed up the import completely because `../node_modules/core-decorators/index.js` does not exist and so none of these imports will import anything. core-decorators's `main` is `lib/core-decorators.js`, so the correct relative import is actually `../node_modules/core-decorators/lib/core-decorators.js` and by attempting to convert the import to relative it has actually bypassed the module resolution that allows the module to be imported.

----

This of course brings up another point. Simply by virtue of being inside `node_modules` you are guaranteed that assuming browser style module resolution by default is wrong. Because even if you use browser style imports in your code, you are guaranteed that the stuff in `node_modules` which you do not control will be using bare imports, omitting the `.js`, and possibly contain CommonJS that the browser cannot handle.

**Comment by dantman** [comment] 2019-03-22 20:37
I've already explained why this cannot be working as intended. It should not be auto-closed.

**Comment by weswigham** [comment] 2019-03-22 22:08
I'm not sure how nobody in this thread mentioned it, but @dantman just set `"moduleResolution": "node"`. The commonjs module target implies it, the esnext and es6 module targets do not.

**Comment by dantman** [comment] 2019-03-22 22:47
Thank you @RyanCavanaugh!

@weswigham that already exists? I was pretty much going to say that 1/3 of this bug report is basically a feature request for exactly that. Neither the TypeScript tsconfig.json nor vscode tsconfig documentation lists that option. I suppose in that case this would be a request for documentation and a request that all tsconfig examples that set es2015 also include that so that defining it becomes standard practice.

Btw, what is the value if you are using browser style module resolution? Since 'html' or whatever we call it probably should be supported for those coding directly for type=module.

The other 2/3 of this issue would be:

- Whatever the default module resolution is for es2015 modules is, it probably warrants some sort of modification. Since auto-`index.js`/ext is a Node-style resolution feature. Also since changing baseUrl from absent to "." should not change `../node_modules/core-decorators` to `node_modules/core-decorators/index` (i.e. `../` should go away, but `/index` should not appear).
- For the core-decorators case, `../node_modules/core-decorators/index.js` does not exist so it's also the case that TypeScript picks the wrong main file to auto-import when a package declares a `types`/`typings` and puts it in a common location when it should be importing what is in `main`. `moduleResolution: node` will paper over this issue, but it will re-appear if someone has "Input Module Specifier" set to "relative".

Related, [Node.js ESM implementation](https://github.com/nodejs/modules/blob/master/doc/plan-for-new-modules-implementation.md) may be moving to a third resolution style where bare imports (`lodash`) are supported but imports use url encoding specifics instead of file path encoding specifics and by default extensions must be specified. So it's possible we may be adding a third resolution type down the road.

**Comment by weswigham** [comment] 2019-03-22 23:01
The option is listed on our [Compiler Options wiki page](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options.md). 🤷‍♀️

**Comment by dantman** [comment] 2019-03-22 23:59
> The option is listed on our [Compiler Options wiki page](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options.md). 🤷‍♀️

Ah. Ok, I see the issue. The issue was I just looked for tsconfig documentation and found https://www.typescriptlang.org/docs/handbook/tsconfig-json.html. But I looked for documentation on that page instead of going to the compiler options page, for which the only reference to is a link in a single paragraph on the entire page "*The "compilerOptions" property can be omitted, in which case the compiler’s defaults are used. See our full list of supported Compiler Options.*"

Oh also a related documentation note, `--moduleResolution` states the default is `module === "AMD" or "System" or "ES6" ? "Classic" : "Node"` while the Module Resolution documentation page uses `--module AMD | System | ES2015`. i.e. ES6 should be updated to ES2015.

I'll see if I can find any es2015 examples/documentation I may have used and get them to add moduleResolution.

**Comment by 951565664** [comment] 2019-06-18 11:30
It seems to happen in the file named by `index.js`, try to rename the file without index.js

**Comment by goldylucks** [comment] 2019-07-03 18:17
happened to me as well, fixed by commenting out `compilerOptions.target = es6`

```
// jsconfig.json
{
  "compilerOptions": {
    "experimentalDecorators": true
    // "target": "es6" // fucks up auto imports, 
  },
  "exclude": ["node_modules"],
  "include": ["src"],
  "files.exclude": {
    "**/.history": true
  }
}

```

**Comment by aflansburg** [comment] 2019-10-23 17:38
Remoing `compilerOptions.target = 'ES6'` also worked for me, but I wanted to know why. [This](https://www.typescriptlang.org/docs/handbook/compiler-options.html) helps to explain (see `--target` and `--module` options).

by default `target` will be `ES3` it seems, providing neither `target` nor `module` in `jsconfig.json` seems to mean that by default you would have: 
```
"target": "ES3",
"module": "CommonJS"
```
But that's just going off the defaults in the above link.

**Comment by plsloan** [comment] 2019-12-04 04:58
None of this is working for me. I created my project with create-react-app. Here is my jsconfig.json

`{
  "compilerOptions": { "target": "es3" },
  "exclude": ["node_modules"],
  "include": ["src/**/*"]
}`

**Comment by jscheel** [comment] 2020-01-06 21:21
I'm experiencing this issue as well. The package's entrypoint isn't being respected, so the import ends up being `packagename/dist/foo/bar`, instead of `packagename`

**Comment by andrewbranch** [comment] 2021-11-05 00:32
It looks to me like the answer to this issue was `moduleResolution` should be set to `node`. Since the original issue was opened, _so much_ has changed about auto imports, module resolution, and our documentation that I don’t think it’s useful to keep this open. @dooee, please read through the whole conversation to see if anything solves your problem. If not, open a new issue please. Thanks!

**Closed by andrewbranch** 2021-11-05 00:32 UTC
Labels: Suggestion, Awaiting More Feedback
