### ISSUE TITLE
I want to write explicit `.ts` file extension in typescript project, and let the compiled file to have `.js` extension.

### ISSUE THREAD

**Issue by xieyuheng** [microsoft/TypeScript#55346] opened 2023-08-13 08:28 UTC
### 🔍 Search Terms

explicit `.ts` file extension

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Add a config option to write explicit `.ts` file extension in typescript project, and let the compiled file to have `.js` extension.

### 📃 Motivating Example

It feels wrong to import `.ts` file as `.js` file in typescript project.

### 💻 Use Cases

1. What do you want to use this for?
  
   I want to write explicit `.ts` file extension in typescript project, and let the compiled file to have `.js` extension.

3. What shortcomings exist with current approaches?

   It feels wrong to import `.ts` file as `.js` file in typescript project.

4. What workarounds are you using in the meantime?

   Write `.js` file extension in typescript project.

**Comment by xiBread** [comment] 2023-08-13 09:33
https://www.typescriptlang.org/tsconfig#allowImportingTsExtensions

**Comment by xieyuheng** [comment] 2023-08-13 09:34
@xiBread That is only for `--noEmit` or `--emitDeclarationOnly`.

**Comment by MartinJohns** [comment] 2023-08-13 12:52
> * This wouldn't change the runtime behavior of existing JavaScript code

You wrongly checked this point. And the team has stated over and over and over again that they won't do import path rewriting.

**Comment by xieyuheng** [comment] 2023-08-13 18:19
@MartinJohns An new option will not change the runtime behavior of existing JavaScript code, because existing JavaScript code are not using this new option.

Importing TypeScript file with `.js` extension, is importing non existing file in TypeScript.

It is much worse then "doing import path rewriting" in TypeScript.

**Comment by xieyuheng** [comment] 2023-08-13 18:24
Without "import path rewriting", a TypeScript developer must either

1. Importing non exiting files using `.js` extension.

2. Importing files without extension, thus the generated files can not be use by the browse directly.
   The developer must use another tool to transform the files to use them in the browse.

**Comment by fatcerberus** [comment] 2023-08-13 18:50
> Importing TypeScript file with `.js` extension, is importing non existing file in TypeScript.

This exact discussion has been had a million times and the response from maintainers is always the same: TS is never going to rewrite import specifiers; in all cases you have to write the import that will work at runtime.

**Comment by fatcerberus** [comment] 2023-08-13 18:56
Duplicate of https://github.com/microsoft/TypeScript/issues/49083

**Closed** 2023-08-14 09:17 UTC

**Comment by MartinJohns** [comment] 2023-08-14 09:21
> 1. Importing non exiting files using `.js` extension.

Just FYI, you're importing modules, not files. Just very often the modules are provided by local files.

**Comment by xieyuheng** [comment] 2023-08-14 09:25
Thanks for the replies, I will try Deno to use `.ts` as the file extension.

**Comment by fatcerberus** [comment] 2023-08-14 13:50
> Just FYI, you're importing modules, not files. Just very often the modules are provided by local files.

This is such a great observation.  It's something you don't think about in day-to-day coding and when you do, it seems like it's just splitting hairs, but the distinction is *exactly* what makes the prospect of import path rewriting such a huge can of worms.

**Comment by xieyuheng** [comment] 2023-08-14 15:58
Isn't JavaScript has one module one file?

**Comment by RyanCavanaugh** [comment] 2023-08-21 18:22
I assure you we've thought about this for much longer than you think we have
