### ISSUE TITLE
Assign function to a larger parameters set, got TS2322

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#47115] opened 2021-12-12 01:58 UTC
# Bug Report

### 🔎 Search Terms

- `TS2322`
- `function parameters`

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
let f: (a: number, flag: number) => number;

f = (a: number, flag: 1) => 42;
console.log(f);
```

```ts
type JsonPrimitive = string | number | boolean | null;

function register(f: (...args: JsonPrimitive[]) => JsonPrimitive) {
  console.log(f);
}

register((a: number, b: number) => 42);
```

### 🙁 Actual behavior

```txt
TS2322: Type '(a: number, flag: 1) => number' is not assignable to type '(a: number, flag: number) => number'.
  Types of parameters 'flag' and 'flag' are incompatible.
    Type 'number' is not assignable to type '1'.
```

```txt
Argument of type '(a: number, b: number) => number' is not assignable to parameter of type '(...args: JsonPrimitive[]) => JsonPrimitive'.
  Types of parameters 'a' and 'args' are incompatible.
    Type 'JsonPrimitive' is not assignable to type 'number'.
      Type 'null' is not assignable to type 'number'.
```
### 🙂 Expected behavior

No error.

**Comment by fatcerberus** [comment] 2021-12-12 03:57
That's correct - function parameters are contravariant.  Under strictFunctionTypes, you can't assign a function that only accepts a `1` to a type that can be passed any number.  This is because someone may call `f(1, 2)` which your arrow function wouldn't be expecting (it wants `flag: 1`).

The second error is similar: You have a function that requires two numbers, but you're trying to assign it to a function type that can be passed any number of `JsonPrimitive`s.  A `JsonPrimitive` is not required to be a number, and if that wasn't enough, the caller is allowed to give you fewer parameters than your arrow function requires.

Both errors are correct and by design.

**Comment by loynoir** [comment] 2021-12-12 09:10
@fatcerberus 
Thanks for your detailed answer. 😃

Might I ask how to you implement register function's signature?
- A register function here is something like handler for `JSON-RPC`
- Forbid call with function, that which has parameter other than `JsonPrimitive`. For example, forbid
`register((a: Buffer, b: ArrayBuffer, c: Uint8Array) => boolean)`

**Comment by whzx5byb** [comment] 2021-12-13 13:07
> Might I ask how do you implement register function's signature?

You can use a generic function:
```ts
function register<T extends JsonPrimitive[]>(f: (...args: T) => JsonPrimitive) {
  console.log(f);
}
```

**Closed** 2021-12-14 13:15 UTC
Labels: Working as Intended
