### ISSUE TITLE
Incorrect type inferred when accessing nested tuples by chained indexes

### ISSUE THREAD

**Issue by benlesh** [microsoft/TypeScript#45686] opened 2021-09-01 22:14 UTC
# Bug Report

### 🔎 Search Terms

- Incorrect types arrays in tuples
- Nested tuples

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, including latest and I reviewed the FAQ for entries about things

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=21&ssc=2&pln=1&pc=1#code/C4TwDgpgBA0hIGcCCA7AJgNQIYBsCuECAPDADRQYB8UAvFANr0z0C65GrLLA3ALABQoSFABSeBMGz5CRKrQYcuffgIBmeFAGNgASwD2KKACM9AJwDWENCXaUAFGizAsALljxk6KQWJkK1AB9RcUlcH1lKAEo3ADc9HTQoAG8BKDSoHVUoOyRTUywQADodZDyChycsegAGFhqWSMjk1PTWzQMJKFNCPBxgeUdneuGARh4WtIBfKAgcBGgU-la2jv7uhF7gEYHK0fGl5bT2lE71zYAmHaHa+u4oAHp7qABJADkAYQB5ACVvgFF3gAVNwYCZQSYCCEqfjqLS6AxQADuZnMOhQAHMbP4Ks43HBEKhMGEZH45EExBJvDIqNEoHEEs0DmlMtlcvkiiU2eVBlUbrVGozDkdVl0en0rry6jcxspWtNZvNBULjqc9IiJbcHk9gAALaAAWyw6J0migaEyqgg3S0EDBKxOazFW3kpjV9BldvSKsdGz6lzorsRmseUC+vwBwIoUCCzBYYKhkyAA)

### 💻 Code

```ts
type KeysAndValues<K, V> = [[K[], V[]]];
type JustValues<V> = [V[]];

function borked<K, V>(data: KeysAndValues<K, V> | JustValues<V>): void {
    if (Array.isArray(data[0][0])) {
        const result = data[0][0][1];
    } else {
        const result1 = data[0][1];
        const result2 = data[0][0]; // INCORRECT: V
    }
}

function working<K, V>(data: KeysAndValues<K, V> | JustValues<V>): void {
    if (Array.isArray(data[0][0])) {
        const result = data[0][0][1];
    } else {
        const row = data[0]; // the magic difference
        const result1 = row[1];
        const result2 = row[0]; // CORRECT: V | K[]
    }
}
```

### 🙁 Actual behavior

For some reason, in the function `borked`, above, accessing `data[0][0]` infers the incorrect type of `V`, when it should be `V | K[]`. If you do what is in the function `working`, above, and pull `data[0]` out into a variable (`row`), then `row[0]` will result in the _correct_ type of `V | K[]`

### 🙂 Expected behavior

`result2` should be of type `V | K[]` in both the `working` and `borked` functions in the example.

**Comment by andrewbranch** [comment] 2021-09-02 18:52
I think my eyes are just tripping over all the square brackets, but can you explain _why_ you expect your expected behavior? Here’s what I see:

- `data[0][0]` is `K[] | V`. No argument here.
- Asking if that type is an array narrows it to `K[]`. This is unsound because it ignores the possibility that `V` itself is instantiated with an array type. Every other type that follows from this flawed assumption is technically wrong, the first of which is `result` as `K` in both functions. It should arguably be `unknown`, but that would be a bummer.
- In `working`, I think you just defeat the narrowing logic by grabbing a reference to a higher-up property than the one that was narrowed. (This will possibly be “fixed” by #38839.)

So, I think I agree with your conclusion (on technical grounds, but this is a known/desired unsoundness that we really don't want to get rid of without negated types), but I wonder if you used the same logic to get there, because the easier way to demonstrate my conclusion is just by saying that `result` should be `unknown` in both functions.

**Comment by benlesh** [comment] 2021-09-02 23:35
This is a minimal reproduction of a situation a co-worker hit. Basically this is some deserialized nonsense from a server and he wanted to add some type safety around it. (I actually pointed out to him that one type is a superset of the other) Either way, it seems like a strange technical error. I just wanted to bring it to your attention. I'm not sure how else this could manifest or even if it does. 🤷‍♂️

**Comment by andrewbranch** [comment] 2021-09-02 23:47
Well, ignore my explanation for the moment. Can you explain why _you_ expected your expected behavior? The flaw I pointed out in my explanation is fairly subtle, and if I take off my pedantic hat, the actual behavior looks correct to me.

**Comment by benlesh** [comment] 2021-09-03 13:58
Honestly, the structure/logic of the code doesn't really matter to me, that's just copy pasta from the code I was helping look at. It's the second part, and how it's effected by the `Array.isArray` check. 

1. The type system can't guarantee that the `V` generic won't be an array. So the `Array.isArray` check can't possibly narrow anything. If V is a known type or extends some non-Array, then it can _absolutely_ narrow it down, but there's no constraints in this code.
2. Since data[0] is ` V[] | [K[], V[]]`, Then I'd think `data[0][0]` should always be `V | K[]`. Why would pulling `data[0]` into it's own variable make a difference?

[Here's a more specific example](https://www.typescriptlang.org/play?#code/C4TwDgpgBA0hIGcCCA7AJgNQIYBsCuECAPDADRQYB8UAvFANr0z0C65GrLLA3ALABQoSFABSeBMGz5CRKrQYcuffgIBmeFAGNgASwD2KKACM9AJwDWENCXaUAFGizAsALljxk6KQWJkK1AB9RcUlcH1lKAEo3ADc9HTQoAG8BKDSoHVUoOwBCJFNTLBAAOh1kAqKHJyx6AAYWOpZIyOTU9PaAeg6oABUACzKoBD69PBw0FAByYCgAWydgCFNyIwhNLHFoEFGodamZgHM8LEKURYg29rSuqGA+pwoMhCgzJ-2oLEN8wpLLq80DBIPvJHM5Go1uFAbgBJAByAGEAPIAJWRAFF4T03Bg-gBfP4AlBArAg6rg+qQm5I1EYrGPILMFgCfH8IA)

```ts
type KeysAndValues<K, V> = [[K[], V[]]];
type JustValues<V> = [V[]];

function borked<K, V>(data: KeysAndValues<K, V> | JustValues<V>): void {
    if (!Array.isArray(data[0][0])) {
        // This shouldn't matter, because you can't guarantee
        // that V is or isn't an Array.
        const a = data[0][0]; // INCORRECT: V
    }
    const b = data[0][0]; // CORRECT: V | K[]
}
```



Put another way: This is only a problem generics, because generics _could_ be arrays -- or anything else -- in this case. If you add hard types, it doesn't have any issues, as the `Array.isArray` actually does make a bit of difference, [as you can see in this playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBA0hIGcCCA7AJgNQIYBsCuECAPDADRQYB8UAvFANr0z0C65GrLLA3ALABQoSFABSeBMGz5CRKrQYcuffgIBmeFAGNgASwD2KKBoBGegE4BrCGgAUaLMCwAuWPGTopBYhLM6UAc3IUPABbYwgzagAfUXFJXC8iYLCIygBKFwA3PR00KABvAShiqB1VKBskMzMsEAA6HWRq2rsHLHoABhZOljS0gqKSoc0DCSgzQjwcYHl7Rx6FgEYeQeKAXygIHARoQv4h4dGZiYQp4EXZtqWV-YPikZQxk7OAJkv5rp7uKAB6H6gAMIAeQASiCAKIAgAqLmS4TMqygawEyP4QA)

```ts
type KeysAndValues<K, V> = [[K[], V[]]];
type JustValues<V> = [V[]];

function unborked(data: KeysAndValues<string, number> | JustValues<number>): void {
    if (Array.isArray(data[0][0])) {
        const result = data[0][0][1];
    } else {
        const result1 = data[0][1];
        const result2 = data[0][0]; // CORRECT: number
    }
}
```

**Comment by benlesh** [comment] 2021-09-03 14:24
[Here's another way to put it that shows how this is broken](https://www.typescriptlang.org/play?#code/C4TwDgpgBA0hIGcCCA7AJgNQIYBsCuECAPDADRQYB8UAvFANr0z0C65GrLLA3ALABQoSFABSeBMGz5CRKrQYcuffgIBmeFAGNgASwD2KKACM9AJwDWENCXaUAFGizAsALljxk6KQWJkK1AB9RcUlcH1lKAEo3ADc9HTQoAG8BKDSoHVUoOwBCJFNTLBAAOh1kAqKHJyx6AAYWOpZIyOTU9PacCGAoLHlHZ0bG5Xb2zQMJKAB3Jz7qobaRnvlp4Hn+doBfAS3+IA)

![image](https://user-images.githubusercontent.com/1540597/132021236-4ad75780-4ab3-4d0e-87a4-b986e0399a31.png)

**Comment by andrewbranch** [comment] 2021-09-03 16:30
Ok right, we’re on the same page then. Because we don’t have negated types, there are all kinds of places we make unsound assumptions about what a type parameter is _not_. Consider an analogous example:

```ts
async function f<T extends { id: string }>(x: T | Promise<string>) {
  const awaited = await x; // T | string;
}
```

Here we assume that `await` cannot have an effect on the type `T` because `T` does not look like a Promise, so the `await` should just unwrap the `Promise<string>` or no-op on the `T`. But `T` is absolutely allowed to be instantiated with something Promise-like, as long as that Promise-like type also has an `id: string` property. Because `T` _might_ be Promise-like, the only sound type for `awaited` is `unknown`, because if `T` happens to be Promise-like, we have no idea what type it will resolve to. The only way to square this circle is using a negated type as a constraint for `T` as a way to say “has an `id` and does _not_ have a callable `then`.” But we have no way to express that, so we have to choose between being correct and being useful, and we choose utility.

The array case is the same. It’s often useful, though incorrect, to assume that `V` is not an array. If you know that it really might be in practice, you need to come up with some way to defeat the narrowing. One way might be to constrain it to something like `string | number | boolean | object | unknown[]` to make the compiler deal with the fact that it _really_ might be array-like.

> Why would pulling `data[0]` into it's own variable make a difference?

Because the narrowing engine is just not that smart. You narrowed on `data[0][0]`—we don’t recognize that this could imply anything about `data[0]`. You will only see refinements on `data[0][0]` and its sub-properties. Like I said, this will probably be fixed by https://github.com/microsoft/TypeScript/pull/38839, making our behavior here _consistently_ unsound. But you’ll always be able to find ways like this to defeat control flow narrowing.

**Closed** 2021-09-07 20:00 UTC
Labels: Working as Intended

**Comment by timbodeit** [comment] 2021-11-05 04:09
It seems to me that the type of `awaited` could be expressed more specifically than unknown as `string | (T extends Promise<infer U> ? U : T)`

> because if T happens to be Promise-like, we have no idea what type it will resolve to.

While we don't know what type it will resolve to, that doesn't mean we're completely unable to reason about it on a generic level and convey that information back to the calling context.

[Playground example](https://www.typescriptlang.org/play?#code/IYZwngdgxgBAZgV2gFwJYHsIwLbANYCmAyukgCYA8AKgHwAUAHgFwxUCULACgE7raogC1GAQbICEMiBg8+AoaghwC3GAFUaMAPzqYLWjADeAWABQMGNwLIE3LHWAB3YKmQwGbGKC8QwAbjMAXzNQSFhEFAwsOGBqemZWGAAfGV5+QQoQZG5FAHMaTxNzGChMLK9nVwIyGABeCpc3XEISckY2PxgAei6YLJyIXOSYOioRMQkpVLkMxWVVDW1dfTYzCysbOyM4dHQWJ0bqwIDTYNNSiHLgOvhgOgdwaBHPWs0ARgAmAGY2OjYO7q9HboLzIbKoABGCHEJXQ3CsUGQABswDA5iorDVvAADfp5YYQBDYCEqbEhR7hJCIqLwCFxRj6YaydJCPGDApGNawy5uA5VGr1PluBidHp9cGDYZULkbWxYQzA-aVcRkY5BMwXcoQm5wCH3UJPP51d7fX7-UVA3ag8FQmGKUrwgiIlFopQY6peaS4iVDFLM+QUQnElQ0MmmIA)

I'm trying to think of cases where an unsound lowering to `string | T` would be more useful than inferring `string | (T extends Promise<infer U> ? U : T)`.
Thinking about it this way both #45686 / #46534 as well as the [generic await example](https://github.com/microsoft/TypeScript/issues/45686#issuecomment-912664483) remind me of the way unions with undefined or null are treated. We have a `strictNullChecks` flag to let the user decide whether he wants the "utility" of just ignoring `undefined` and `null` or the "correctness" of always having full handling of possible `undefined` value cases enforced.

Should this issue perhaps be resolved in a similar way?
* Intended behavior in non strict mode: Make the unsound assumption, that a generic parameter `T` does not conform against a common parent type shared with other more explicitly declared types in the union.
* Strict behavior guarded behind a new strict checking flag: Account for the fact that generic parameters can also satisfy the same typeguards applying to other union members and enforce explicit handling of the case that they do.

--- 

On a more general note:

> so we have to choose between being correct and being useful, and we choose utility

@andrewbranch Does the TypeScript project have some more general policy on when to choose correctness vs utility documented somewhere, that I could read up on?

When running the TypeScript compiler with the `strict` flag being set, I would expect the compiler to not make any (intentional) unsound assumptions about the types in my code. Making unsound assumptions for increased usability would be a feature, I'd expect to be limited to non fully strict operating modes. Is that not the case / goal?
