### ISSUE TITLE
Make implicit this part of function signature.

### ISSUE THREAD

**Issue by Akhristenko** [Microsoft/TypeScript#29669] opened 2019-01-31 21:25 UTC
## Search Terms
implicit this method signature
## Suggestion
Include implicit **this** in method signature when **this** used in method body and we can infer **this** type.
## Use Cases 
This help us find cases when we pass method of object as callback without using bind.
## Examles
Let we have current class, function and class instance:
```TypeScript
class Test {
    str = "string";
    impl() {
        return this.str;
    }
    expl(this: Test) {
        return this.str;
    }
}

function test(cb: (this: void) => string) {
    alert(cb());
}

let obj = new Test();
```
If we write ` test(obj.expl)` we get compilation error.
In this code **this** inside impl() function infer to Test type
but if we write `test(obj.impl)` we don't get compilation error and get runtime error.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by ahejlsberg** [comment] 2019-02-01 14:22
Duplicate of #7968.

**Closed** 2019-02-01 19:32 UTC
Labels: Duplicate
