### ISSUE TITLE
{composed:boolean} is missing in Event and EventInit interface within lib.dom.d.ts

### ISSUE THREAD

**Issue by Hotell** [Microsoft/TypeScript#18233] opened 2017-09-03 18:21 UTC
**TypeScript Version:**  2.5.2 ( and all prior version to latest )

**Code**

[see error in TS playground](http://www.typescriptlang.org/play/index.html#src=class%20Foo%20extends%20HTMLElement%20%7B%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20super()%0D%0A%20%20%20%20%20%20%20%20this.attachShadow(%7Bmode%3A'open'%7D)%0D%0A%20%20%20%20%7D%20%20%0D%0A%20%20%20%20emitCustomEvent()%20%7B%0D%0A%20%20%20%20%20%20%20%20this.shadowRoot.dispatchEvent(new%20Event('hello'%2C%20%7Bbubbles%3A%20true%2C%20composed%3A%20true%7D))%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20emitCustomEventWithExtractedConfig()%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20worldEventConfig%20%3D%20%7Bbubbles%3A%20true%2C%20composed%3A%20true%7D%0D%0A%20%20%20%20%20%20%20%20this.shadowRoot.dispatchEvent(new%20Event('world'%2C%20worldEventConfig))%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A)

```ts
class Foo extends HTMLElement {
    constructor() {
        super()
        this.attachShadow({mode:'open'})
    }  
    emitCustomEvent() {
       // error
        this.shadowRoot.dispatchEvent(new Event('hello', {bubbles: true, composed: true}));
    }
    emitCustomEventWithExtractedConfig() {
        const worldEventConfig = {bubbles: true, composed: true}
        // no error --> ! this is strange behaviour of TSC, this should be error as well
        this.shadowRoot.dispatchEvent(new Event('world', worldEventConfig));
    }
}
```

**Expected behavior:**
`{composed:boolean}` should be defined ( this event config flag is needed when triggering custom events from shadow root to pierce outside the shadow.

Also what is very strange is that, when event config is initialized to a variable and used then as a reference within `Event` creation, TS won't throw error which is very strange behaviour indeed as from structure perspective, the `composed` property is still there and not allowed by current `dom.lib.ts`

**Actual behavior:**
add `{composed: boolean}` to Event and EventInit interfaces within `dom.lib.ts`

**Comment by kitsonk** [comment] 2017-09-04 09:36
Duplicate of: #17974 ([search is your friend](https://github.com/Microsoft/TypeScript/search?q=event+composed&type=Issues&utf8=%E2%9C%93))

Covered by PR: Microsoft/TSJS-lib-generator#284

**Comment by Hotell** [comment] 2017-09-04 09:54
thanks, although I didn't find related issue via search, and yes I always look before creating issues if there is already one/similar created.

Still I think there is bug, not related to Event type, which I've described as well:

> Also what is very strange is that, when event config is initialized to a variable and used then as a reference within Event creation, TS won't throw error which is very strange behaviour indeed as from structure perspective, the composed property is still there and not allowed by current dom.lib.ts

**Comment by kitsonk** [comment] 2017-09-04 10:13
The behaviour around why something [like this](http://www.typescriptlang.org/play/#src=interface%20FooOptions%20%7B%0A%20%20%20%20foo%3F%3A%20string%3B%0A%7D%0A%0Adeclare%20function%20foo(options%3F%3A%20FooOptions)%3A%20void%3B%0A%0Afoo(%7B%0A%20%20%20%20foo%3A%20'bar'%2C%0A%20%20%20%20bar%3A%20123%20%2F%2F%20error%0A%7D)%3B%0A%0Aconst%20options%20%3D%20%7B%20foo%3A%20'bar'%2C%20bar%3A%20123%20%7D%3B%0A%0Afoo(options)%3B%20%2F%2F%20no%20error%0A%0Aconst%20guardedOptions%3A%20FooOptions%20%3D%20%7B%20foo%3A%20'bar'%2C%20bar%3A%20123%20%7D%3B%20%2F%2F%20error%0A) behaves the way it does:

```ts
interface FooOptions {
    foo?: string;
}

declare function foo(options?: FooOptions): void;

foo({
    foo: 'bar',
    bar: 123 // error
});

const options = { foo: 'bar', bar: 123 };

foo(options); // no error

const guardedOptions: FooOptions = { foo: 'bar', bar: 123 }; // error
```

Has to do with the challenges of dealing with a structural type system.  IIRC prior to TypeScript 1.6, an object literal could have excess properties, as that is allowed in a structural type system.  That of course causes a lot of potentially unintentional mistakes (though if the interfaces are correct, excess properties shouldn't matter).  Because strictly speaking `{ foo: 'bar', bar: 123 }` is actually assignable to the type of `{ foo: string }`.

Because this can be _surprising_ the decision was made to check for excess properties on the assignment of the object literal, but follow the _right_ way of dealing with assignment in other locations.  This still means when you have a variable that is contextually typed, it follows the _proper_ assignment rules, but if you assert the type, instead of contextually infer it, the _fresh_ object literal type is checked to see if it has excess properties.

So this is _working as designed_.

**Comment by alan-agius4** [comment] 2017-09-05 09:19
So in the above, what you be the ideal way to remove excess properties?

using object deconstruction or just use type asserations?

Options 1
```
    const { genericErrorCode, ...betslipErrorConfig } = errorConfig;
        return {
            ...defaultConfig,
            ...betslipErrorConfig ,
            translationKey,
            code,
            data
        };
``` 

or Option 2
```ts

**Comment by kitsonk** [comment] 2017-09-05 09:42
> So, what you be the ideal way to remove excess properties?

Question is _why_ you need to remove excess properties... but there are many ways.  If you are trying to catch errors, guard the types when authoring "fresh" objects, like I did above:

```ts
const guardedOptions: FooOptions = { foo: 'bar', bar: 123 }; // error
```

**Comment by Hotell** [comment] 2017-09-05 09:52
First of thanks so much for thorough explanation @kitsonk didn't know that it works this way !

about:
> Question is why you need to remove excess properties... but there are many ways. If you are trying to catch errors, guard the types when authoring "fresh" objects, like I did above:

> const guardedOptions: FooOptions = { foo: 'bar', bar: 123 }; // error

Well now with this style, we are getting to "Java" style -> explicitly annotate that string is a string which is a big no no IMHO. ( even there are lint rules within TSLint that will error on this explicit annotation on Classes properties for instance )

Hopefully this can be resolved somehow in future releases of TS

**Comment by alan-agius4** [comment] 2017-09-05 10:13
@kitsonk I need to remove excessive properties, to make typescript compile, and from my example, there are the 2 options I showed above, either by removing through deconstruction or using `as`

**Comment by kitsonk** [comment] 2017-09-05 12:14
> Hopefully this can be resolved somehow in future releases of TS

It won't be _fixable_ until there is some level of support for co-variant parameters, which is a really difficult thing to introduce.  It can be surprising behaviour, but why it is surprising is to permit other functionality that would be really annoying if TypeScript didn't support.  This is explained in the FAQ [Why are function parameters bivariant?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant)

**Comment by mhegazy** [comment] 2017-09-20 20:04
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Closed by mhegazy** 2017-09-20 20:04 UTC
Labels: Duplicate
