### ISSUE TITLE
Error: No Project. in 'Object.ThrowNoProject' during 'quickinfo'

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#21797] opened 2018-02-09 01:19 UTC
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.1
**VSCode Version** 1.20.0-insider
**command requested**: quickinfo
**hitting sessions**: 1347
**proportion of all sessions**: 0.0050285023126630905
**stack**
```
Error: No Project.
    at Object.ThrowNoProject (tsserver.js:84179:23)
    at ProjectService.getDefaultProjectForFile (tsserver.js:87357:46)
    at IOSession.Session.getFileAndProjectWorker (tsserver.js:89734:87)
    at IOSession.Session.getFileAndProject (tsserver.js:89719:29)
    at IOSession.Session.getQuickInfoWorker (tsserver.js:89779:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:88934:61)
    at unknown (tsserver.js:90355:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90346:28)
    at IOSession.Session.executeCommand (tsserver.js:90355:33)
    at IOSession.Session.onMessage (tsserver.js:90375:35)
    at Interface.<anonymous> (tsserver.js:91576:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mhegazy** [comment] 2018-02-09 18:07
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/20629

**Closed by mhegazy** 2018-02-09 18:07 UTC
Labels: Bug, Source: Telemetry
