### ISSUE TITLE
Object is possible "undefined" even if it's already checked for string keys in object

### ISSUE THREAD

**Issue by zaqqaz** [Microsoft/TypeScript#22328] opened 2018-03-05 11:48 UTC
**TypeScript Version:**  2.6.2

**Search Terms:** 
TS2532, Object is possible "undefined", generic, string

**Code**

```ts
export type CommonBets<BetSpot extends string> = {
    [K in BetSpot]?: number;
};

// 1 
export function calculateTotalAmountInCommonCase(bets: CommonBets<string>): number {
    let total = 0;
    for (const spot in bets) {
        if (bets.hasOwnProperty(spot) && bets[spot] !== undefined) {
            total += bets[spot];  // TS2532: Object is possible "undefined"
        }
    }

    return total;
}

// 2
export function calculateTotalAmountInSpecificCase(bets: CommonBets<"variantA"|"variantB">): number {
    let total = 0;
    for (const spot in bets) {
        if (bets.hasOwnProperty(spot) && bets[spot] !== undefined) {
            total += bets[spot]; // Al good 👍
        }
    }

    return total;
}
```

**Expected behavior:**
As it's already checked all should be fine both cases.
**Actual behavior:**
 TS2532: Object is possible "undefined" in first case

![uuu](https://user-images.githubusercontent.com/2823336/36973467-cfd11280-207b-11e8-8071-48c349dd947b.png)

**Comment by jcalz** [comment] 2018-03-05 15:18
Maybe related to or duplicate of #10530?   I don't think bracket notation triggers control flow narrowing at all (not even for string literal properties).  The workaround here is to assign `bets[spot]` to a new variable:

```ts
for (const spot in bets) {
      let bs: number | undefined
      if (bets.hasOwnProperty(spot) && (bs = bets[spot]) !== undefined) {
          total += bs;  // okay
      }
  }
```

Your second example only works if you don't turn on `--noImplicitAny`; the compiler doesn't have any idea what type `bets[spot]` might be, because TypeScript lacks [exact types](https://github.com/Microsoft/TypeScript/issues/12936), and the type of `bets` only specifies that the keys `variantA` and `variantB` correspond to `number | undefined`.  It does not preclude that there might be other properties with other value types.  For example, this compiles with no errors:

```ts
const bets = {
  variantA: 1,
  variantB: 2,
  unexpectedStuff: "whoopsie"
}
calculateTotalAmountInSpecificCase(bets); // bad at runtime!!
```

Suggestion: turn on `--noImplicitAny` (good idea in general) and guard against weirdness by actually checking for `number`:

```ts
for (const spot in bets) {
      let bs: {}
      if (bets.hasOwnProperty(spot) && typeof (bs = (bets as any)[spot]) === 'number') {
          total += bs; // okay
      }
  }
```

**Comment by zaqqaz** [comment] 2018-03-05 15:37
@jcalz thanks ;) You're absolutely right, except one thing, I have turned on `noImplicitAny `, but it's related to `suppressImplicitAnyIndexErrors` which turned off.

**Closed** 2018-03-22 15:41 UTC
Labels: Duplicate
