### ISSUE TITLE
Trivially narrow down single type value widen the other value type

### ISSUE THREAD

**Issue by tylim88** [microsoft/TypeScript#57200] opened 2024-01-28 00:48 UTC
### 🔎 Search Terms

Trivially narrow down single type value widen the other value type

### 🕗 Version & Regression Information

tested on 5.3.3 and nightly

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.3#code/MYewdgzgLgBA2gawKYE8A0MBuBDANgVyQF0YBeeE7CGfMBMEAdzBivgHJt2Mx8BbAEZIATjAA+MaMICWYAOZEAUIukAzGAApkKMqXKd2MAGRGYUFAAckIdTgJJd+3oJHsAlDADeimL5ihIWAEyLDxCHz8Aeki-GAA9AH5FAF8YJFwIB29YgOgYYPI7cNjo2MSUxSA

### 💻 Code

```ts
const [key, value] = [] as unknown as ['a', number | string]

if (key === 'a' && typeof value === 'number') {
    const b = value
    //    ^?
} else {
    const b = value
    //    ^?
}
```

### 🙁 Actual behavior

![image](https://github.com/microsoft/TypeScript/assets/5227509/07ec5789-79a1-4043-ad36-9c04e59cf3a0)

`key === 'a' ` always result in true and typescript **should** know this

which mean the only way to enter the `else` case is when `typeof value !== 'number'`, and the only possible type is `string`

but what happen is TS widen the type instead

### 🙂 Expected behavior

`b` in the `else` case should be `string`

**Comment by MartinJohns** [comment] 2024-01-28 01:28
Duplicate of #57063.

**Closed** 2024-01-28 01:38 UTC
