### ISSUE TITLE
Proposal: Static constructors

### ISSUE THREAD

**Issue by nin-jin** [Microsoft/TypeScript#8727] opened 2016-05-21 09:17 UTC
Example:

```ts
class Component {
    static all : Array<typeof Component>
    static constructor() {
        Component.all.push( this )
    }
}

class MyButton extends {}
class MyCheckbox extends {}
class MyRadio extends {}

console.assert( Component.all[0] === MyButton , 'registration MyButton' )
console.assert( Component.all[1] === MyCheckbox , 'registration MyChackbox' )
console.assert( Component.all[2] === MyRadio , 'registration MyRadio' )
```

This not works. But we have workaround:

```ts
/// Support for static constructors
var __extends = ( Sub , Sup ) => {
	for( var prop in Sup ) if( Sup.hasOwnProperty( prop ) ) Sub[ prop ] = Sup[ prop ]
	Sub.prototype = Object.create( Sup.prototype )
	Sub.prototype.constructor = Sub
	if( Sub.initializer ) Sub.initializer()
};

class Component {
	static all : Array<typeof Component> = []
	static initializer() {
		Component.all.push( this )
	}
}

class MyButton extends Component {}
class MyCheckbox extends Component {}
class MyRadio extends Component {}

console.assert( Component.all[0] === MyButton , 'registration MyButton' )
console.assert( Component.all[1] === MyCheckbox , 'registration MyChackbox' )
console.assert( Component.all[2] === MyRadio , 'registration MyRadio' )
```

But:
* This is hack.
* `initializer` calls only on descendant classes.

We can use decorators:

```ts
class Component {
	static all : Array<typeof Component> = []
	static register( comp : typeof Component ) {
		Component.all.push( comp )
	}
}

@ Component.register
class MyButton extends Component {}

@ Component.register
class MyCheckbox extends Component {}

@ Component.register
class MyRadio extends Component {}

console.assert( Component.all[0] === MyButton , 'registration MyButton' )
console.assert( Component.all[1] === MyCheckbox , 'registration MyChackbox' )
console.assert( Component.all[2] === MyRadio , 'registration MyRadio' )
```

But:
* Too more code.
* User may forget to register component and don't understand why his code not works.

**Comment by basarat** [comment] 2016-05-24 06:19
Static constructors have been asked before : https://github.com/Microsoft/TypeScript/issues/265

Where the pattern was recommended https://basarat.gitbooks.io/typescript/content/docs/tips/staticConstructor.html :rose:

**Comment by mhegazy** [comment] 2016-05-24 18:42
indeed a duplicate of #265. closing.

**Closed by mhegazy** 2016-05-24 18:42 UTC

**Comment by nin-jin** [comment] 2016-05-24 20:01
@basarat, Dependency on caring user - antipattern.
