### ISSUE TITLE
Discriminating unions doesn't work as expected along with function literal types

### ISSUE THREAD

**Issue by pptang** [microsoft/TypeScript#45482] opened 2021-08-17 03:24 UTC
# Bug Report

I'm not sure if this is a bug or expected behavior, but I cannot find the corresponding documentation or related issues, if there is a duplicate issue of this, please let me know, thank you!

### 🔎 Search Terms

- Discriminating unions
- function type annotation

### 🕗 Version & Regression Information

I switched between all versions available in the playground and it seems to be the same behavior.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.3.3&ssl=53&ssc=2&pln=2&pc=1#code/FAFwngDgpgBAMgewIYBMCWA7A5jAvDAb2BhgGcQkQoAuGAcgBtl1s6BuYAXw9ElkVRQUeQsTIUqtRsyHsxKSklrkATpiwduwXtBgAlKKQCuDECIEscAH3gyUPAGZGMAYxBoEGGAHcEKgNbqAGpQKqQeGAAUAJS0BsamomIA9MkwEEikpClpKlAgRipeRCSpJOKUNPRMgih0ADQ55QoUUi1IDU2c2qVpGVlNeQVFor3l5JVSNZadY91NLggAthBoDLChKn4wkZkwUAAe0G5C0WJDhcViJBOS1czqs82KbYpP3fPgugBizm4R8RMZnwMTwAD59IYgTxFhhyDAMJ4AOp+QLYEJhCK0X6udyeQGJEHRcFJMb9bJjC4jEowMo3CRVaS1J50mDtV4UFlpeZkzIU2m5fKXUYC8YMqYPViNOY9UWImCLFZrSgRfYqLYqc5C6nXCp3JkzaXPVr0drvLjAIA)

### 💻 Code

- Working version
```ts
type Loading = {
  state: 'loading';
};

type Loaded = {
  state: 'loaded';
  data: string;
};

type Result = Loading | Loaded;

function workingVersion(): Result {

  // pass
  // return {
  //   state: 'loaded',
  //   data: 'data',
  // }

  // pass
  // return {
  //   state: 'loading',
  // }

  // compile error (as expected)
  return {
    state: 'loading',
    data: 'data',
  }
}
```

- Non-working version
```ts
type Result = Loading | Loaded;

type FunctionResult = () => Result;

const nonWorkingVersion: FunctionResult = () => {

  // pass
  // return {
  //   state: 'loaded',
  //   data: 'data',
  // }

  // pass
  // return {
  //   state: 'loading',
  // }

  // no compilation error (but I expect to receive compile error)
  return {
    state: 'loading',
    data: 'data',
  }
}
```

### 🙁 Actual behavior

For the non-working version example I put above, it doesn't show any compile error even though the returned structure doesn't match any possibility of my discriminated union type `Result`.

### 🙂 Expected behavior

I expect the non-working version (which function type annotation is used) should work the same as working version example I put above.

**Comment by MartinJohns** [comment] 2021-08-17 06:07
Duplicate of #39635 / #241 and many many many many many more.

**Comment by MartinJohns** [comment] 2021-08-17 08:34
Additionally, this behaviour is unrelated to unions.

        type Result = { a: string }
        type GetResult = () => Result

        const getResult: GetResult = () => ({ a: '', b: '' })

No return type is provided for the anonymous function, so it is inferred. In this case it's inferred to be `{ a: string, b: string }`, and the type of the function is `() => { a: string, b: string }`. When assigning this to the variable the compiler will check if this type is assignable to `GetResult`, which it is: No properties are missing or incompatible.

You can get the behaviour you want by adding at type annotation to your function:

    const getResult: GetResult = (): Result => ({ a: '', b: '' }) // Now an error

**Comment by pptang** [comment] 2021-08-17 08:43
@MartinJohns Thanks for the clear explanation! I'll close this issue accordingly 🙏🏼

**Closed** 2021-08-17 08:43 UTC
