### ISSUE TITLE
Imports  auto-update replaces relative path with alias-path

### ISSUE THREAD

**Issue by wclr** [microsoft/TypeScript#28488] opened 2018-10-23 12:20 UTC
- I've renamed file `ChartWheel.ts` -> `ChartWheel2.ts`
- Vscode/ts updated import relative paths like `./ChartWheel` -> `~/client/cycles/ChartArea/ChartWheel2`
- I would expect `./ChartWheel` ->  `./ChartWheel2`
tsconfig compiler options have following config for paths:
```
   "baseUrl": ".",
    "paths": {
      "~/*": ["./apps/*"],
    }
```

So is it possible for vscode/ts to keep existing import path "style" the same while updating imports?

btw is it more correct to create issues on auto-import in TS repo?

**Comment by mjbvz** [comment] 2018-11-12 19:54
Try setting `"typescript.preferences.importModuleSpecifier": "relative"`. This should make ts prefer using relative paths for quick fixes and auto imports (although we will continue to understand both paths styles)

@andy-ms By default do we prefer using `paths` over relative paths?

**Comment by andy-ms** [comment] 2018-11-12 22:57
As of #25803 we should prefer the relative path when it's shorter, so I would consider this a bug.  I can't reproduce this problem in a simple project containing just `apps/client/cycles/ChartArea/user.ts` and `apps/client/cycles/ChartArea/ChartWheel.ts` and the compiler options posted above.

@whitecolor It would help if you could provide a specific repro for this. The only things that should matter are the path of the importing file, the path of the imported file, and the `tsconfig.json`. Also be sure you're testing with `typescript@next` ([set up](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions) instructions for vscode).

**Comment by RyanCavanaugh** [comment] 2019-07-15 21:31
@whitecolor can you provide the requested info and unassign yourself? Thanks!

**Comment by mjbvz** [comment] 2021-02-17 22:29
Closing as not actionable without more information. We've also made a lot of fixes and improvements since it was opened

If you see this again with VS Code 1.53+ and TypeScript 4.15+, please let us know

**Closed by mjbvz** 2021-02-17 22:29 UTC
Labels: Needs More Info
