### ISSUE TITLE
Provide Intellisense for module import

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#10092] opened 2016-08-02 13:33 UTC
_From @SetTrend on January 21, 2016 14:56_

TypeScript module exports can be fairly opaque in regard to their exports. Particularly when modules grow bigger.

With bigger modules (particularly with modules exporting other modules' exports) it becomes very hard to see which entities a module actually is exporting.
<br/>
##### So I suggest to provide an Intellisense feature for module imports, which
1. provides a file browser dropdown box displaying valid module files
2. provides a module browser dropdown box displaying an imported module's exported entities

<br/>
#### The first part of the suggestion I propose to work like `LINQ`:

After entering the keyword `from` and hitting the [TAB] key, a file browser dropdown should be displayed, listing all valid module files. After confirming a file from the dropdown box, VS Code should automatically create a full `import {} from "[...]"` statement, move the cursor position between the curly braces and display a dropdown box listing all the exports of that module.
<br/>
##### Here's a visualization:

![provide intellisense for import](https://cloud.githubusercontent.com/assets/9283914/12483755/17e59744-c057-11e5-9992-599d511cf826.gif)

<br/>
#### The second part of the suggestion I propose to work like common Intellisense:

Everytime when hitting [CTRL]+[SPACE] from within the curly braces of an `import` statement, dropdown box (2) should be displayed, listing the module's exported entities. Selecting an entry should then add the selected export entity to the list of already imported entities within the curly braces.

_Copied from original issue: Microsoft/vscode#2153_

**Comment by dbaeumer** [comment] 2016-08-02 13:34
_From @atifsyedali on March 2, 2016 20:39_

We have around 25k lines of Typescript with hundreds of Typescript modules, and we use CommonJS style module imports.

Not having Intellisense for module import as described here is the main reason why we don't use VS Code. Would be really nice if you can add this (or push the Typescript team to provide it on a language service level :) )

**Comment by dbaeumer** [comment] 2016-08-02 13:34
_From @Haemoglobin on July 16, 2016 8:58_

:+1:

**Comment by dbaeumer** [comment] 2016-08-02 13:34
This is actually a feature that has to come from the tsserver.

**Comment by SetTrend** [comment] 2016-08-02 14:47
Not quite a dupe, as #2371 is about changing the syntax, whereas this issue is about providing a list of exported symbols recursively.

Shouldn't be to complex. First implementation iteration:

1. Load the `.ts` file mentioned in the `from`,
1. enumerate and return all the `export`s,
1. enumerate all re-exports and execute (1.) on them.

**Comment by mhegazy** [comment] 2016-09-29 23:59
https://github.com/Microsoft/TypeScript/issues/188 provides completions for module names and `/// <reference path`. We already have completions for module exports, i.e. `import { | } from "someModule"`.  Would these cover this request?

I am not too crazy about typing `from` first, since it is really a different syntax. and i do agree that this would have been a better module import syntax, but this is really a question to TC39 members.

**Comment by SetTrend** [comment] 2016-09-30 10:16
Thanks, Mohamed,

yes, the [typescript-hero](https://github.com/buehler/typescript-hero) VS Code extension seems to be right the thing I've been looking for.

Thanks for sharing this link with me! :grinning: :+1: 

/cc: @dbaeumer

**Comment by waderyan** [comment] 2016-11-18 23:05
It seems like #188 covers this request. @dbaeumer can you check it out? If it does then we can close this issue.

**Comment by dbaeumer** [comment] 2016-11-21 19:49
@waderyan no not exactly the same. He has a nice suggestion of using snippets to create import statements. The major problem is that if write a new import statement then you do `import {} from 'fs'` and then you have to move the cursor back into {} to complete symbols. This is not very user friendly and I like his suggestion. But that might need a combination of work on our end (extend the snippet UI) and may be API on the tsserver.

**Comment by mhegazy** [comment] 2016-12-15 21:23
this should be covered by https://github.com/Microsoft/TypeScript/issues/7849

**Closed by mhegazy** 2016-12-15 21:23 UTC
Labels: VS Code Tracked

**Comment by waderyan** [comment] 2016-12-16 19:03
@mhegazy this actually looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/12243

See my comment in that issue. I propose we reopen one of these.
