### ISSUE TITLE
Typescript does not work with defaults

### ISSUE THREAD

**Issue by jantimon** [Microsoft/TypeScript#16354] opened 2017-06-08 08:09 UTC
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)
[Try it yourself using this Playground Link](http://www.typescriptlang.org/play/index.html#src=function%20fancyMethod(%7B%20option1%20%3D%20true%20%7D%3A%20%7B%20option1%3F%3A%20boolean%20%7D%20%3D%20%7B%7D)%20%7B%0A%20%20%20%20console.log(option1)%3B%0A%7D%0A%0AfancyMethod(%22abc%22)%3B%0AfancyMethod(false)%3B%0AfancyMethod(42)%3B)

**Code**

```ts
    function fancyMethod({ option1 = true }: { option1?: boolean } = {}) {
        console.log(option1);
    }
    
    fancyMethod("abc");
    fancyMethod(false);
    fancyMethod(42);
```

**Expected behavior:**

Typescript will let me know that `"abc"` or `false` or `42` are not of type  `{ option1?: boolean }`.

**Actual behavior:**

No type error is shown

**Comment by ikatyang** [comment] 2017-06-08 08:38
Possible duplicate of #7485, and it was said that was fixed by #16047.

See https://github.com/Microsoft/TypeScript/issues/16247#issuecomment-306031885

But it seems primitive types are still not considered a weak type.

**Comment by jantimon** [comment] 2017-06-08 08:41
Thanks for your feedback :)

Is there any way to find out the current playground version number?
Is there a nightly playground?

**Comment by ikatyang** [comment] 2017-06-08 08:51
You can see the version in the console.
![image](https://user-images.githubusercontent.com/8341033/26919973-16c62d38-4c6a-11e7-962e-e09cd24160da.png)

But I think it will be v2.3.3+ based on #16131, so weird.

And selectable playground version is track by #15662.

**Closed** 2017-06-08 16:13 UTC
Labels: Duplicate
