### ISSUE TITLE
Update Variable Type After a Type Narrowing

### ISSUE THREAD

**Issue by titouandk** [microsoft/TypeScript#58913] opened 2024-06-18 14:57 UTC
### 🔍 Search Terms

narrowing, type, variable, redefinition

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

TypeScript should understand that the type of a variable has changed, following a type narrowing:

![type-narrowing](https://github.com/microsoft/TypeScript/assets/5413308/237dbe2f-f3b7-4279-87fd-f6b1c092f26d)
 

Playground link:
https://www.typescriptlang.org/play/?#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVzAQygGdgAVCMTNASQBMAKNYAG2YDV9mlgAuOVANYoIAdxQBKPiiQBbAEbAocAN4AoAJDNg8GBSp04AXjhNWHLsADcqjQHpbJ-ER0Q4zqJhQBzOJgR4IIiJMOS0NPzh6GABPMGAIf11KGlojQ2MAIml5RQzxFQ11JP1U42KUgDpdAGUYD296cWt1AF8bdQio2PjEvRS4AEJ0uAz3Ty88gvUigAsoUTgUYBE4AFEoeah6DOoUADdOTFTy31o85raNcoMyvroKojBmTBhtiryAbQAGAF1m69KcAAcrIFFAKgRiMBdq8AU12p0QTlwZgiED8ECondaOJ8mppjA5gslit1pt6AADXYHZ7HPqnEYAEmUAJaGQp8Na7Sg2iQUFwAOsbSAA

### 📃 Motivating Example

TypeScript does not understand that the type of a variable has changed following a type narrowing.

The type of a variable is announced as the type with which the variable has been declared - even if its type has been refined since via type narrowing.

### 💻 Use Cases

What workarounds are you using in the meantime?

Creating a copy of the variable. TypeScript understands the type of the new variable.

**Comment by MartinJohns** [comment] 2024-06-18 15:10
Duplicate of #27706.

**Closed** 2024-06-21 01:30 UTC
Labels: Duplicate
