### ISSUE TITLE
In operator narrowing does not work when key is a variable

### ISSUE THREAD

**Issue by peterHakio** [microsoft/TypeScript#56822] opened 2023-12-18 14:36 UTC
### 🔎 Search Terms

In narrowing, as type, type inference

### 🕗 Version & Regression Information

I have tried  on 5.1.6 and on nightly typescript

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.0-dev.20231218#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBZJcWD1RpaSCoABqDGg7EgAAp4NIAFaQKn5UAAbwY+U47EQ0m+AF9+MkKDBuHzBKhKJxmABKAWKEoI0CsmVykReDncqnq-makqgJyofGGrk81AAbT10QAugBuc0S8HQQQoM0Wy10m2gLjcSAyziQbgekoSxRxinmaleZh0xnMyAAJnZdt5AqFIrFkulsuifIARAxywAfcvScum83a3Wl1wZJK51CNgNW4NG+1O1vuz3e30antBsheUPhjJRmOgONx4IqHDNDxT0CIeB9BjA9g0L5uMzMdgMVP8WDQdSJPfwPQG0DlgCiqwYiAW+nLSWx5fADlQAByYQADlIAkcsghUAB5L4yHeX1+FTI5UEcBRXGkPBA23HRhiwfQUAQRBoWES4jwkHdohEAwOGxBYmFYDgeCCEogA

### 💻 Code

```ts
function getValue(object: {a:number}, field: string) {
  if (field in object) {
    return object[field];
  } else {
    return undefined;
  }
}
function getValue2(object: {a:number}, field: "a"|"b") {
  if (field in object) {
    return object[field];
  } else {
    return undefined;
  }
}
```

### 🙁 Actual behavior

<img width="951" alt="image" src="https://github.com/microsoft/TypeScript/assets/145982428/9948a508-c918-4aca-ac06-eca3aef1b9c4">

### 🙂 Expected behavior

Naturally i would expect this compile without errors or at least give me a suggested fix like: 
```
function getValue(object: {a:number}, field: string) {
  if (field in object) {
    return object[field as keyof typeof object];
  } else {
    return undefined;
  }
}
```

**Comment by MartinJohns** [comment] 2023-12-18 15:14
Duplicate of #52311. Please don't post screenshots in place of code or error messages, it makes reading your issue fairly difficult and is not very inclusive.

**Comment by RyanCavanaugh** [comment] 2023-12-19 20:46
I don't understand what the expected result is here. `field in object` doesn't mean `field` is `'a"`. What would the function return? This isn't a bug and the implied suggested change would be wrong.

**Closed** 2023-12-22 01:27 UTC
Labels: Question
