### ISSUE TITLE
Improve error message for using value as type

### ISSUE THREAD

**Issue by evmar** [Microsoft/TypeScript#29778] opened 2019-02-06 17:29 UTC
**TypeScript Version:**  3.4.0-dev.20190206

**Search Terms:** "cannot find name" type error

**Code**

If you use a type as a value you get a nice error message:

```ts
type t = number;
let x = t;
// error TS2693: 't' only refers to a type, but is being used as a value here.
```

But if you do the same thing in reverse, you get a really confusing one:

```ts
let t = 3;
let x: t;
// error TS2304: Cannot find name 't'.
```

**Expected behavior:**

Error message should say something more like the type one.

**Actual behavior:**

Error message suggests there is no 't' in scope at all, which is very confusing especially when you have imported t from some other file and you thought it was a type.

**Playground Link:** 

https://www.typescriptlang.org/play/#src=%0D%0Afunction%20goodError()%20%7B%0D%0A%20%20%20%20type%20t%20%3D%20number%3B%0D%0A%20%20%20%20let%20x%20%3D%20t%3B%20%2F%2F%20good%20error%20message%0D%0A%7D%0D%0A%0D%0Afunction%20badError()%20%7B%0D%0A%20%20%20%20let%20t%20%3D%203%3B%0D%0A%20%20%20%20let%20x%3A%20t%3B%20%2F%2F%20bad%20error%20message%0D%0A%7D

**Related Issues:**

There are some around this same problem with namespaces I think, like 
https://github.com/Microsoft/TypeScript/issues/26391 or https://github.com/Microsoft/TypeScript/issues/12075

I think this issue is more broadly complaining about issues in this area:
https://github.com/Microsoft/TypeScript/issues/27630
But the issue I'm filing here is very specific and concrete, with an easy repro.

This issue discusses some suggested fixes for this issue, but I think first we need to fix the error message.
https://github.com/Microsoft/TypeScript/issues/28975

**Comment by DanielRosenwasser** [comment] 2019-02-06 19:19
Duplicate of #28975?

**Comment by evmar** [comment] 2019-02-06 20:06
Hm, that one is really close.  But it is saying we should suggest a specific fix, and is bogged down in how it's hard to pick the right fix.  Here I'm asking to at least fix the error message (without necessarily suggesting a fix), so #28975 I guess would be follow-on work from that.

**Comment by DanielRosenwasser** [comment] 2019-02-06 23:32
Seems small enough to avoid the bikeshed 🚲🏠.

**Comment by dragomirtitian** [comment] 2019-02-07 00:08
@DanielRosenwasser  Would the message `'t' refers to a value, but is being used as a type here.` be too similar to the reverse message ? (`'t' only refers to a type, but is being used as a value here.`)

**Closed** 2019-02-14 21:14 UTC
Labels: Experience Enhancement, Suggestion, good first issue, help wanted

**Comment by DanielRosenwasser** [comment] 2019-02-14 23:18
Thanks for the PR @dragomirtitian!
