### ISSUE TITLE
Switch inside for loop is converting to intersection

### ISSUE THREAD

**Issue by apacheli** [microsoft/TypeScript#47459] opened 2022-01-15 21:44 UTC
# Bug Report

When using a `switch` statement inside of a loop, it creates weird intersection issues, which should be union types. This causes issues where types are `never`, or just not correct in general.

### 🔎 Search Terms

switch case, loop, union intersection, assigning

### 🕗 Version & Regression Information

TypeScript 4.5

### ⏯ Playground Link

[playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCJzHZBvAUMg5ADwC5kBnMKUAcwG59CBPMkAVwFsAjaBw5EAHswAGWCQocADZlsyABYQpUwWS6DBUiHBDIAvgz25cCKXHLk0GLHn5sADgBMMEABTPMZdJgCUORvwEMIJQyK4IgiCUyADWEEzIoMgecH62gRnkAO7iCPJhcUxpARmlCOYoAERElSQlpYHl5FVMtf4NHYRg8sDkANqFALrIALzJ1gPxg3TIAPSzyGBM9ihjIBAAbtDIPOVszYng0M0IYMCRyIIwyFLi0NLk9Z2BXFDaMXzP-EZPnU0ttV+HX+yEqQlEd0kUja6S+GS0YGQGzgUAAjKNFj1+kMZvNkBEoG9TotlihesgsGwQOcQECvgikSiAEwYlKTJjTOYLB6CfEhImIpYrRKWHkU5BUml057ItEY2VM3ELbrk8nmcjAGggOBcLTSzoq7FTVkTHFcnZsQVYkUCYQAGkSiJoEDAAHJLBEQFsoJBHIcwLydP7jhBTlK4aVXu9PhGjF846UEwQjEYgA)

### 💻 Code

```ts
  update(data: Partial<Message>) {
    for (const key in data as Message) {
      switch (key) {
        case "content":
        case "tts": {
          const z = data[key]!;
          let g = this[key]!;
          g = z;
          this[key] = data[key]!;
          break;
        }

```

`z` is assignable to `g`, but `data[key]` is not assignable to `this[key]` despite being exactly the same type. `key` is already narrowed down to the correct keys `"content" | "tts"`.

### 🙁 Actual behavior

When using intelisense, it seems that type is correctly using `|`. However, when TRULY assigning to `this` it seems to have created a union instead (`&` is not correct).

### 🙂 Expected behavior

It should stay as a union instead.

**Comment by jcalz** [comment] 2022-01-16 02:56
#30769 is why this is happening, and this issue is probably a duplicate of #32693

**Closed** 2022-01-21 18:00 UTC
Labels: Duplicate
