### ISSUE TITLE
Type inference doesn't work for switch-case of 'constructor' property

### ISSUE THREAD

**Issue by Sgt-Nukem** [microsoft/TypeScript#31961] opened 2019-06-18 12:19 UTC
## Search Terms
constructor type inference switch case

## Suggestion
Let a `switch (XXX.constructor)` correctly infer types in `case` blocks.

## Example
c.f. the following snippet (the `Router` is the Angular Router btw)

![image](https://user-images.githubusercontent.com/4144388/59680831-acd04200-91d2-11e9-9dc4-43336937b316.png)

In `case NavigationError:` block it should be clear that `event` is indeed a `NavigationError` instance and I would like to get IntelliSense for that.

As NavigationError has an `error` property (c.f. following image) I would expect to get that shown in the IntelliSense tooltip in the image above -- but I get `console.error()` only!

![image](https://user-images.githubusercontent.com/4144388/59681226-ae4e3a00-91d3-11e9-99e0-d1398d648c90.png)

**Comment by nmain** [comment] 2019-06-18 12:53
There's nothing special about `switch` here; the pattern `foo.constructor` just isn't recognized for narrowing at all: https://www.typescriptlang.org/play/#src=declare%20var%20e%3A%20Event%3B%0D%0A%0D%0Aif%20(e%20instanceof%20MouseEvent)%20%7B%0D%0A%20%20e.pageX%3B%20%2F%2F%20works%0D%0A%7D%0D%0A%0D%0Aif%20(e.constructor%20%3D%3D%3D%20MouseEvent)%20%7B%0D%0A%20%20e.pageX%3B%20%2F%2F%20doesn't%20work%0D%0A%7D%0D%0A

Duplicate of https://github.com/microsoft/TypeScript/issues/23274

**Closed** 2019-06-28 18:00 UTC
Labels: Duplicate

**Comment by murbanowicz** [comment] 2021-04-13 05:59
As #23274 does not fix the case for `switch` I think this one should be re-opened.
