### ISSUE TITLE
Awaited return type of generic parameter not assignable to itself

### ISSUE THREAD

**Issue by wbt** [microsoft/TypeScript#50251] opened 2022-08-10 03:25 UTC
# Bug Report

### 🔎 Search Terms
generic function parameter 2322 return type 

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the [FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ) for entries about functions and common bugs that aren't bugs
- I was unable to test this on versions before 4.5 because the `Awaited` keyword didn't exist.

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYhwGMAWEBOMCuA7BwCWA9llALxQAUAUFDVHgCYRb4BmeaAXFFhgLYBGaSgEpSAPigAFVAV54AzhAA884KjxYA5mIDcUAPT62ADwj0oAclXqtF7gWBR8ZpwShgAhqg+94aJ+AQ8nTBnqiOBCxQ8ni8YAA2eGwIHvhEUCwEqFAQxj4JEJSgkFCMvAQwGhAAjKRQAErwGKhYACqBSnCIKOjYuIRYugb6UjJyiipqGtpFgaUQ5ZVYEABMdQCCAO4eeMBmSo3AzW0dXchomDhpg0OG1tOUHvIgOBl911Ca8HuoACILBCU1FoMByxj2WHowTOPUu-XSZBhF3eA0oYiotAy8HO6CwXBgABpgTQGExWOxUFweAI0ETRFxpLIFMotjs9vQDk0Wu1IJ0xPyoABvYlQeLweblADM+J0IrFjlQQQw8UcZA8212WO6Fyw5FJzCSFOEekMivkyscCigHmiUy0IsVRxaUDNFpN+gAovV6gB5epQVoAZRWkpWKy4POgVjtmjsVqwDmt8himiwHn4YtcARKFlZu32h2Okb5YgsIsMAEliMAUFByvgAG6paZg-JigmihzBcqKkKlIjQTa7JBOWuulXWyGj6CO47Z6BWm3FaCMdQNlwsMZ0YBEzGGfgYRw16AxOJi7K5NsniALYKJADWC8c8iQBGV9CwFkcglHMiHWknHJUBkSkoE2FBj2yPN2U5J0Tl5GAJEXct9FPApbRsTQoCyaJZHgJAWx7aAEFkApjA7GtUj7cCqOPdwxmZF0uWWcx+BAUdF2eV4WBRdIzQIeJ12CYACAAOkoABfIA)

### 💻 Code

```ts
type FetcherFunction = (
    identifier: number
) => Promise<string>; //fixed 'string' not tied to parameter types is part of simplification for example
type demoFine1 = ReturnType<FetcherFunction>; // Promise<string>
type demoFine2 = Awaited<ReturnType<FetcherFunction>>; //string
async function getterDemo<
    F extends FetcherFunction = FetcherFunction
>(
    fetcherFn: F,
    identifier: number,
) : Promise<Awaited<ReturnType<F>>> {
    let demo3: F;
    let result = await fetcherFn(identifier); //result is a string
    return result; //ERROR TS2322: Type 'string' is not assignable to type 'Awaited<ReturnType<F>>'
    //In the motivating example, lots more is done with the result and the return type is a type derived from it,
    //but the simpler example seems like it shouldn't be throwing an error: whether Awaited<ReturnType<F> is a
    //simple string or something more complex, that is what the promise returned by this async function resolves to.
}
```

### 🙁 Actual behavior
Error as noted.

### 🙂 Expected behavior
No TS2322 error; the above code works fine. The awaited return type of fetcherFn should be assignable to the return (resolve) value, which is the awaited return type of that function type.

**Comment by MartinJohns** [comment] 2022-08-10 08:37
The issue is the deferred resolving of conditional types involving unbound type parameters. Get rid of `ReturnType<>` and it will work fine.

**Closed** 2022-08-21 20:00 UTC
Labels: Working as Intended
