### ISSUE TITLE
Add "Optimize imports" feature to language service

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#14743] opened 2017-03-20 09:43 UTC
WebStorm has very helpful feature - Optimize Imports, that just remove unused imports, but doesn't touch barely imports.
Also it merge same module imports into one and sort by import names
```ts
import {foo} from './module';
import {bar} from './module';
// optimize to 
import {bar, foo} from './module';
```

![optimize imports](https://cloud.githubusercontent.com/assets/3171573/24094159/6df5a5a2-0d68-11e7-9a7b-51e04ade79ca.gif)

**Comment by mhegazy** [comment] 2017-03-20 20:42
Duplicate of https://github.com/Microsoft/TypeScript/issues/10020

**Closed** 2017-04-21 16:55 UTC
Labels: Duplicate
