### ISSUE TITLE
Opting out for super call requirement?

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#9503] opened 2016-07-04 09:42 UTC
**TypeScript Version:**  master branch

**Code**

```ts
class EVE extends HTMLElement {
  constructor() {
    return document.createElement("sn-eve"); // Error
  }
}

let eve: EVE;
eve = document.createElement("sn-eve"); // No error
```

**Expected behavior:**
It should work if a constructor function return an object which is structurally compatible with the declared class.

**Actual behavior:** 
Error: Constructors for derived classes must contain a 'super' call.

**Workaround:**

```ts
class EVE extends HTMLElement {
  constructor() {
    if ({} === undefined) {
      super();
    }
    return document.createElement("sn-eve");
  }
}
```

**Comment by kitsonk** [comment] 2016-07-04 11:17
In plain [JavaScript](https://jsfiddle.net/o0x14fhL/):

```javascript
class EVE extends HTMLElement {
  constructor() {
    super(); // TypeError: Illegal Constructor
    return document.createElement("sn-eve");
  }
}

let eve1 = new EVE();

let eve2 = document.createElement("sn-eve");
```

So not only is it "unwanted", if `super()` is called, it will throw, so TypeScript is requiring invalid ES6 syntax.

**Comment by MattiasBuelens** [comment] 2016-07-04 18:22
What's the point of making `EVE` a class when you cannot add methods or properties to it, or even extend it? It is not sufficient for a class constructor to create an object that is structurally compatible with the class's interface. At a minimum, the class's prototype must be in the prototype chain of the constructed object, i.e. `eve1 instanceof EVE` should be `true`.

**Comment by SaschaNaz** [comment] 2016-07-04 18:37
@MattiasBuelens I can:

```ts
class EVE extends HTMLElement {
  constructor() {
    if ({} === undefined) {
      super();
    }
    const tempThis = document.createElement("sn-eve");
    Object.setPrototypeOf(tempThis, EVE.prototype);
    return tempThis;
  }
  eve() {
    return 3;
  }
}

console.log(new EVE().eve()) // 3
```

**Comment by MattiasBuelens** [comment] 2016-07-04 20:41
@SaschaNaz Okay, I guess that works. What about a subclass of `EVE` that needs to the `super` constructor, and then do some other things in its own constructor? How would this work:
````js
class DerivedEVE extends EVE {
    constructor() {
        super();
        this.foo = "bar";
    }
}
```

I mean sure, you can probably find some roundabout way to make `this` refer to the return value of the super constructor. But really: would you still describe `EVE` as being a class at that point? Can it be used as a class everywhere?

I just don't see the value of being able to not call `super()` from a constructor for regular ES6-style classes. As for your use case of custom elements: unfortunately it's not as simple as creating an element and messing with its prototype (for example, would you expect `<sn-eve>` to work in HTML code?) [The spec for custom elements](https://www.w3.org/TR/custom-elements/) is still being worked on and it'll probably use ES6 classes in some way, but there's more to it.

**Comment by SaschaNaz** [comment] 2016-07-05 05:29
`<sn-eve>` will work as `HTMLUnknownElement on HTML code, and I can freely style it and append any child nodes to serve my purpose. Subclassing it unfortunately requires the same prototype hack.

I have to admit that it's not simple but it still is ES6, and if TypeScript still want to require it then it should do on TSLint not on the compiler.

**Comment by DanielRosenwasser** [comment] 2016-07-05 19:54
I think that this a duplicate of #7285, so I'll redirect the convo to there.

**Closed by DanielRosenwasser** 2016-07-05 19:54 UTC
