### ISSUE TITLE
Wrong typecheck for tagged union with deeply placed tag

### ISSUE THREAD

**Issue by cattingcat** [microsoft/TypeScript#49443] opened 2022-06-08 20:36 UTC
# Bug Report

### 🕗 Version & Regression Information
Stable (v4.7.2) and nightly (v4.8.0-dev.20220608 )

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220608#code/PTAEBcE8AcFNQMoEsC20A28C8oDe4BDAcwC5QByAQXIF9QAfPQ0igIVoG4AoECGeSgBNBAHgShYAD3CwAdoIDOiVBlgA+UDnFSZ8pfmJkqtUAH5EoAGR5oBSOgD2BQWVkBXFACNYAJzpkEbh4wAGMHWQVwUAUAJjIhUWQ0TA0cXGDQTMzmI2oAGgys0Ft7JxdQAEYC3hog3jCIh0wAOkciAApYgEogrig4UABpWABrTTwUWEIyAxZjGjpGXEnppkM2Wlq+-lAE4ZGxCWk5RSHR1IsdE-0VghmcimoFswtrXBLHZ1cPbz9QAO4-Xg+xi4z2oxE+zUHEyvCBZxGoLSt3u63meWKdk+5XcXl8iwmUzuazm7AWvQAZm5ZCFwEhwqAKQ4HKB2iMyPsuhzRqD0kUFAB3JDgEIAC1ZI2at2azC6eC4RSKIQICngxhICsVWp8UzcPlk8q1RqyzVNIwKxuNHzKZCqmstoC2xuVqo2GodmR14D1BpG3CKNC4ga4DUioER3MR4z5WRRJNy5AxNAtWWtX0qBS2IfCYcRFUjSMNsaJqNJicdmaCoaasFaDg6iJ62caLTabJiFR6QA)

### 💻 Code

```ts
type Kek = {meta: {tag: 'A'}} | {meta: {tag: 'B'}};
type AddKek<S extends Kek> = S extends {meta: {tag: 'A'}} ? S & {payload: number} : S;
type Kek2 = AddKek<Kek>;  // type Kek2 = {meta: {tag: 'A'}, payload: number} | {meta: {tag: 'B'}};


function foo (k: Kek): Kek2 {
    switch (k.meta.tag) {
        case 'A':
            return {
                ...k,
                payload: 1,
            };
        case 'B':
            return k; // impossible to return k, problem with typecheck
    }
}

const k2: Kek2 = {
    meta: {tag: 'A', },
    payload: 1,
};

const k21: Kek2 = {
    meta: {tag: 'B', },
};
```

### 🙁 Actual behavior
Type 'Kek' is not assignable to type 'Kek2'.
  Type '{ meta: { tag: "A"; }; }' is not assignable to type 'Kek2'.
    Type '{ meta: { tag: "A"; }; }' is not assignable to type '{ meta: { tag: "A"; }; } & { payload: number; }'.
      Property 'payload' is missing in type '{ meta: { tag: "A"; }; }' but required in type '{ payload: number; }'.(2322)
input.tsx(13, 66): 'payload' is declared here.

### 🙂 Expected behavior
Typechecks successfully

**Comment by cattingcat** [comment] 2022-06-08 20:44
Instead of ```case 'B'``` there could be ```default```

**Comment by jcalz** [comment] 2022-06-08 21:53
You didn't fill out the whole template:

>🔎 Search Terms
> What search terms did you use when trying to find an existing bug report?
>  List them here so people in the future can find this one more easily.

TS doesn't support nested discriminated unions.  Duplicate of #18758

**Closed** 2022-06-11 18:00 UTC
Labels: Duplicate
