### ISSUE TITLE
Change the meaning of `?` from "undefined | T" to not `in` or T

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#32115] opened 2019-06-26 20:50 UTC
## Use Cases

```ts
const obj = {
    a? :string
    b :undefined | string
};
if ( 'a' in obj ) { /* obj.a is string, but currently it is undefined or string */ }
if ( 'b' in obj ) { /* obj.b is undefined or string */ }
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by sandersn** [comment] 2019-06-26 21:12
Typescript doesn't distinguish between missing and undefined. If it did, `missing` would be a subtype of `undefined`. So far the complexity hasn't been worth it.

Duplicate of #12400

**Closed by sandersn** 2019-06-26 21:12 UTC
