### ISSUE TITLE
add support for "export * as"

### ISSUE THREAD

**Issue by bcherny** [Microsoft/TypeScript#7754] opened 2016-03-31 21:33 UTC
foo.ts:
```ts
export const a = 1
export const b = 2
```

bar.ts:
```ts
// error!
export * as foo from './foo'

// ok
import * as foo1 from './foo'
export const foo = foo1
```

**Comment by vladima** [comment] 2016-03-31 22:11
duplicate of #4813

**Closed by vladima** 2016-03-31 22:11 UTC
Labels: Duplicate
