### ISSUE TITLE
`import type` should not need runtime modules support

### ISSUE THREAD

**Issue by antoinep92** [microsoft/TypeScript#44549] opened 2021-06-11 08:49 UTC
# Suggestion

## 🔍 Search Terms

import type
module
--outFile

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Intuitively I expect `import type` to be a compile-time only construct. This is currently not really the case, because using `import type` triggers the compiler into thinking we are using ES modules.

## 📃 Motivating Example

Consider this `test.ts`:
```ts
import type { mkdir as mkdir_proto } from 'fs';
const { mkdir } = require('fs') as { mkdir: typeof mkdir_proto };
```
This to compile to a `ŧest.js` which is more or less:
```js
"use strict";
const { mkdir } = require('fs');
```
Which *does not* use ES modules. Nevertheless, the compiler refuses to compile this if modules are disabled, e.g.
`tsc test.ts --outFile test.js --target es2020` fails with:
```
error TS6131: Cannot compile modules using option 'outFile' unless the '--module' flag is 'amd' or 'system'.

1 import type { mkdir as mkdir_proto } from 'fs';
```
Which makes me think the compilers treats `import` and `import type` the same way.

## 💻 Use Cases

This is clearly not a showstopper, more of an optimization. One use-case is trying to build simple Node.JS scripts, written in typescript as a single file (with the `--outFile` flag), in order to deploy each script as a single javascript file, that I can run natively on a Node.JS server with no typescript support (no tsc or ts-node installed).
Since the script only has dependency to node's standard library, I was not expecting typescript to refuse to compile as a single file.

We can work arround by defining a `tsconfig.json` and building in a directory, then extracting the js file generated in that build/ dir. And I realize there are a lot of issues around here about packaging as a single file. But in this case, there is no concatenation required at all. This is just about `import type` triggering typescript into thinking we are using modules, when we really aren't.

As I said, this is clearly not critical, and I have no idea if this would be easy to implement. So it's really just a suggestion :)

**Comment by MartinJohns** [comment] 2021-06-11 09:16
Essentially a duplicate of #41513 and #41562, with a possible solution discussed at #41567.

As soon as you're using the `import` or `export` statements you're dealing with modules. This is by design.

**Comment by antoinep92** [comment] 2021-06-11 09:52
I see, thanks, and sorry for the duplicate.
For future reference, this explains the rationale: https://github.com/microsoft/TypeScript/pull/35200#issuecomment-645565073

Although it leaves unanswered the question of how to reference modules, and in particular type modules from script :(

**Comment by MartinJohns** [comment] 2021-06-11 10:51
> Although it leaves unanswered the question of how to reference modules, and in particular type modules from script :(

That has been answered in the linked issues. In short: You can't. At least currently not.

**Comment by Jamesernator** [comment] 2021-06-12 04:41
> > Although it leaves unanswered the question of how to reference modules, and in particular type modules from script :(
> 
> That has been answered in the linked issues. In short: You can't. At least currently not.

This isn't entirely true, although it's kinda awkward without proper import. Basically you can use:

```js
type MkdirProto = typeof import("fs")["mkdir"];
```

This isn't too bad to be honest, although becomes tedious if you want a lot of types as there's no destructuring or such to speak of in the type system. So you'll need a `type ImportedType = ...` for each and every imported type.

**Comment by antoinep92** [comment] 2021-06-12 07:16
Ah excellent thanks. I saw that from some other comments but wasn't aware this syntax wasn't considered a module import as opposed to import type. Is this documented somewhere ?

**Closed** 2021-06-14 07:07 UTC
Labels: Duplicate
