### ISSUE TITLE
Improve null checks for callback functions that are called immediately

### ISSUE THREAD

**Issue by alexpomsft** [Microsoft/TypeScript#20275] opened 2017-11-27 08:53 UTC
It's common to write these wrapper functions that do something interesting.  In the case below I've created a monitor function that spits out some console output for a generic function to invoke.  We use this pattern often for monitoring for reliability and performance of various calls, particularly those that hit a network endpoint.

As you can see, add takes an object that defines an optional number.  Before invoking monitor and the inner function, it's sometimes nice and needed to check for null values.  Unfortunately TypeScript isn't quite smart enough to carry that null check down to the inner callback, even though it's invoked immediately.

Is it possible to add this support? 

```ts
async function monitor<T>(fn: () => Promise<T>, scenario: string): Promise<T> {
    console.log(scenario + " started");
    try {
        const ret = await fn();
        console.log(scenario + " success");
        return ret;
    } catch (e) {
        console.log(scenario + " failure");
        throw e;
    }
}

async function add(args: { num?: number }): Promise<number> {
    if (args.num === undefined) {
        return Promise.reject("fail");
    }

    // this if fine
    args.num++;

    return await monitor(async () => {
        // error: args.num may be undefined
        return args.num + 1;
    }, "add");
}

add({ num: 5 });
```

**Comment by mhegazy** [comment] 2017-11-27 19:26
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/11498

**Closed** 2017-12-12 18:21 UTC
Labels: Duplicate
