### ISSUE TITLE
Arrow function forgets result of scope typecheck when using "this"

### ISSUE THREAD

**Issue by zachHixson** [microsoft/TypeScript#54203] opened 2023-05-09 21:11 UTC
# Bug Report

### 🔎 Search Terms

"Type checking arrow function bug," "typescript callback this bug,"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "this," proposals

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBA6gTgewHYHMDyAjAVhAxsKAXigG8A3AQwBsBXCALiiRoFsMI4BfAbgChRIUAMII4cPMEw58RUkgosGUAM7A4AS1Q9evAGY0k+dcijrlIsRIAUCbIwpIQASka2sp5cNHj8UiaV4oIKhxYBo4JCg3ADp5RT5OHX1DYGNI3Goqc0yMClwAaytcDEYrOKVVDVQnQgA+MgR1ABMXKAbmgOCoYqsAcmAIVV6nBKSDIxMwRAwqCBYAMXHU5CtgAAszRgsfSWx-AB9YRFQ-fFb2ps7ggHpr+TEEAHcoJqfI9egBaGUEKEeIXriKJIKggP6ifKaFB-dTrLyWXx7fDKQLBdS6KBWACEZm21nWZicThCEDCET4qKCuGQP1m0SoCBQqw2yliCggxNuBM8jwhnl0mggABooBQedBeTQqJcIAAPSD4CBNHRdDJULJCHJ5Qpldk1WokSldKDctmKWTlbhQW4AFRZJrWiEeng4iDgIogZAg7zWCBoKDWUAARNygypfVLLuwoBg-Ugo2CPqKHs9khMkCLHmsONBYb1PMoFej1EqTb9o0nqQiCF8jZwRrxOEA)

### 💻 Code

```ts
type WrongObject = {value: number};
type CorrectObject = {name: string};

function isCorrect(obj: any): obj is CorrectObject {
    return obj.name;
}

function callsCallback(cb: (name: string)=>void): void {
    cb('test');
}

function problemFunction(this: CorrectObject | WrongObject): void {
    //check type
    if (!isCorrect(this)) return;

    console.log(this.name) //this works fine, as we would expected

    callsCallback((name)=>{
        this.name = name; //This throws error, even though "this" should be bound by the arrow function, where it's specified to be the correct type
    });
}
```

### 🙁 Actual behavior

After correctly narrowing the type of `this` using type coercion (I think that's the proper term) it works correctly in the local scope, but an arrow function which is declared in the same scope won't know what `this` is. Replacing the `this: CorrectObject | WrongObject` argument in `problemFunction` with `myValue: CorrectObject | WrongObject` works as expected, it's only broken when using `this`.

### 🙂 Expected behavior

Arrow functions bind `this` in the scope which they're declared, therefore if an object is determined to be of a certain type above where the arrow function is declared, and in the same scope, the arrow function should inherently know what `this` is.

**Comment by fatcerberus** [comment] 2023-05-09 21:21
Duplicate of #9998 (local narrowing is lost at closure boundaries).  Haven’t seen one of these in a while. 😄

> type coercion (I think that's the proper term)

No, just type narrowing.  Coercion implies you actually convert the value to the proper type.  Like what happens when you do `String(num)`

**Comment by fatcerberus** [comment] 2023-05-09 21:26
> Replacing … with an argument … works as expected

This bears some explanation: Despite the concerns discussed in #9998, an exception is made specifically for function parameters as long as they are not reassigned anywhere the function.  That exception doesn’t extend to other local variables (or `this`), however.

**Comment by zachHixson** [comment] 2023-05-09 22:11
So, is this expected behavior?

**Comment by RyanCavanaugh** [comment] 2023-05-10 14:55
I think this is effectively a bug, since `this` and `const`s have identical immutability, and the example with const works
```ts
function problemFunction(this: CorrectObject | WrongObject): void {
  const self = this;
    //check type
    if (!isCorrect(self)) return;

    console.log(this.name) //this works fine, as we would expected

    callsCallback((name)=>{
        self.name = name; // ok
    });
}
```

**Comment by fatcerberus** [comment] 2023-05-10 15:00
Huh, TIL narrowing of `const` isn't subject to #9998.

> since `this` and `const`s have identical immutability, and the example with `const` works

Yep, also the special exclusion for non-reassigned parameters should extend to `this`.

**Closed** 2023-05-24 22:57 UTC
Labels: Bug, Help Wanted
