### ISSUE TITLE
String enum record can't accessed by declared index.

### ISSUE THREAD

**Issue by Ailrun** [Microsoft/TypeScript#17702] opened 2017-08-09 20:48 UTC
**TypeScript Version:**  2.4.2

**Code**

Run following code with `--noImplicitAny` option.

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
enum HTTPError {
  CLIENT_ERROR = 'CLIENT_ERROR',
  SERVER_ERROR = 'SERVER_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}

// Example 1
type RequestErrorsMap = Readonly<Record<HTTPError, string>>;
const requestErrorsMap: RequestErrorsMap = {
  CLIENT_ERROR: 'Client has problem.',
  SERVER_ERROR: 'Server has problem.',
  UNKNOWN_ERROR: 'Unknown problem occurs.',
};

declare const index: HTTPError;

requestErrorsMap[index]; // Example 1.1
requestErrorsMap[index as 'CLIENT_ERROR' | 'SERVER_ERROR' | 'UNKNOWN_ERROR']; // Example1.2

// Example 2
type EM = {
  [K in HTTPError]: string;
};
const em: EM = {
  CLIENT_ERROR: 'Client has problem.',
  SERVER_ERROR: 'Server has problem.',
  UNKNOWN_ERROR: 'Unknown problem occurs.',
};

declare const i: HTTPError;

em[i]; // Example 2.1
em[i as 'CLIENT_ERROR' | 'SERVER_ERROR' | 'UNKNOWN_ERROR']; // Example2.2
```

**Expected behavior:**
example 1.1, 1.2, 2.1 and 2.2 pass type check

**Actual behavior:**
only 1.2 and 2.2 pass type check

This makes an issue when dealing with js libraries. (whose type is from lib def file)

**Comment by mhegazy** [comment] 2017-08-21 19:37
looks like a duplicate of 17288

**Closed** 2017-09-05 18:22 UTC
Labels: Duplicate
