### ISSUE TITLE
Cannot "import { NameValueUnits } from"

### ISSUE THREAD

**Issue by kevinpas** [Microsoft/TypeScript#4076] opened 2015-07-29 20:36 UTC
Note: I am not trying to get help fixing my code.  I am only reporting what I think is a bug in typescript.

See branch "AddVS15" of https://github.com/kevinpas/Klib6

There are two imports in the startup file "Klib6/Tests/Core/CoreTests.ts". If you comment out the second one you can successfully run and debug/step through the tests in the startup file.

If you uncomment the second import and uncomment the two lines near the bottom:
 //var units = "mm";
 //var nameValueUnits = new NameValueUnits( name, value, units );

when you try to run it you get the exception (on win7):

Debugger listening on port 5858
 module.js:338
 throw err;
 ^
 Error: Cannot find module 'NameValue'
 at Function.Module._resolveFilename (module.js:336:15)
 at Function.Module._load (module.js:278:25)
 at Module.require (module.js:365:17)
 at require (module.js:384:17)
 at Object. (C:\ ... \Git\GitHub\Klib6\Source\Core
 \NameValueUnits.js:46:19)
 at Module._compile (module.js:460:26)
 at Object.Module._extensions..js (module.js:478:10)
 at Module.load (module.js:355:32)
 at Function.Module._load (module.js:310:12)
 at Module.require (module.js:365:17)
 Press any key to continue...

**Comment by kevinpas** [comment] 2015-07-29 20:44
In the branch AddVS15 of https://github.com/kevinpas/Klib6 

there is a Tools folder.  In that folder there is a vs 15 project that should be used.

**Comment by mhegazy** [comment] 2015-07-29 23:05
This is a node issue. it can not find a module "NameValue" the issue is that you are using module "NameValue" without a relative path, which tells node to find a package with this name.

in NameValueUnits.ts change 
```ts
import { NameValue } from "NameValue";
```

to 
```ts
import { NameValue } from "./NameValue";
```

I understand that you wanted the compiler to flag this instead figuring it out yourself. If you have a proposal on how to do that we would be open to discussing it.

**Comment by kevinpas** [comment] 2015-07-29 23:31
It is a difficult problem.

But it doesn't seem to be the natural intent of the new import keyword.  I have no suggestions other than passing import another parameter telling it the callers perspective.

**Comment by DanielRosenwasser** [comment] 2015-07-30 16:03
Is this a duplicate of #294 or related to #2338?

**Comment by mhegazy** [comment] 2015-07-30 18:20
I believe they are related. I wounder if #2338 will fix this. pinging @vladima.

**Comment by kevinpas** [comment] 2015-07-31 23:54
Merged my branch back into master.

**Comment by mhegazy** [comment] 2016-02-22 20:14
this should be working correctly today. please reopen if this is not the case.

**Closed by mhegazy** 2016-02-22 20:14 UTC
Labels: Needs Proposal, Suggestion
