### ISSUE TITLE
No IntelliSense for default export of static member in TypeScript.

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#22885] opened 2018-03-26 19:43 UTC
_From @cnshenj on March 23, 2018 23:29_

- VSCode Version: 1.21.1
- OS Version: Windows 10 x64

Steps to Reproduce:
"foo.ts"
```
export class Foo {
    public static instance = new Foo();
    public bar: string = "Jack";
}

export default Foo.instance;
```

"test.ts"
```
import foo from "foo";
function test() { console.log(foo.bar); }
```

In "test.ts", when you type `.` after `foo`, there is no IntelliSense suggestion. Also, hovering over symbol `foo` doesn't show any type information.

If I change "foo.ts" export statement to the following, then it works:
```
const foo = Foo.instance;
export default foo;
```

TypeScript compiler can compile both versions without any error.

This could be a TypeScript issue instead of VSCode issue, please triage.

_Copied from original issue: Microsoft/vscode#46450_

**Comment by mjbvz** [comment] 2018-03-26 19:43
_From @vscodebot[bot] on March 23, 2018 23:29_

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
- [addSelectionToNextFindMatch doesn't respect multi selection (#42998)](https://www.github.com/Microsoft/vscode/issues/42998) 
- [TypeScript: import choices missing (#43446)](https://www.github.com/Microsoft/vscode/issues/43446) 
- [onDebugInitialConfigurations activates very eager. (#39696)](https://www.github.com/Microsoft/vscode/issues/39696) 
- [Terminal: can't call `#sendText` with a long text (#38137)](https://www.github.com/Microsoft/vscode/issues/38137)

**Comment by mjbvz** [comment] 2018-03-26 19:44
The specific error in `foo.ts` is:

```
message: ''Foo' only refers to a type, but is being used as a namespace here.'
at: '6,16'
source: 'ts'
code: '2702'
```

**Comment by andy-ms** [comment] 2018-03-26 22:29
Somehow we don't issue the diagnostic when in services.
```ts
/// <reference path="fourslash.ts" />

////class C { static x = 0; };
////export default C.x;

verify.noErrors(); // Should fail
```

**Comment by andy-ms** [comment] 2018-03-26 22:31
Duplicate of #14980

**Closed** 2018-04-10 20:50 UTC
Labels: Duplicate
