### ISSUE TITLE
Incorrectly parsed object destructuring assignment with short-hand properties

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#5035] opened 2015-09-30 10:52 UTC
```typescript
function drawES5Chart(options) {
    options = options === undefined ? {} : options;
    var size: any,
        radius: any;
    let cords: any;
    ({size = "big", cords = { x: 0, y: 0 }, radius = 25} = options); // here
    console.log(size, cords, radius);
}
```

As far as I see in spec, that's allowed for object destructuring assignment, in form of:
```
AssignmentProperty[Yield] :
    IdentifierReference[?Yield] Initializer[In,?Yield]opt
```

**Comment by mhegazy** [comment] 2015-09-30 16:46
//CC: @DanielRosenwasser

**Comment by vladima** [comment] 2015-09-30 17:01
yes, we are wrong here. Grammar allows it and Babel can handle this correctly.
```ts
let x;
( {x:x = 1} = {x: 1} );
( {x = 1} = {x: 1} )
```
the problem is that expression on the LHS is parsed as regular object literal so in case of regular property assignment it will be interpreted as object literal with property `x` that has initializer `x = 1`. Later in the checker we can recognize this syntactic pattern and deal with it correctly. However in case of shorthand property assignments: `{x = 1}` is not correct object literal expression so we cannot parse it as such and error.

**Comment by ahejlsberg** [comment] 2015-09-30 23:24
We need to modify the parser to parse the *CoverInitializedName* production (I would suggest by allowing an initializer in a `ShortHandPropertyAssignment`) and then generate grammar errors if the production is found to occur as a non-LHS expression. Shouldn't be too hard.

**Comment by zhuravlikjb** [comment] 2015-10-01 08:41
Also note that the same problem exists with the destructuring pattern of for-of loop (perhaps, due to the same reasons):
```typescript
var s;
for ({s = 5} of q) {            
}
```

**Comment by johnlindquist** [comment] 2015-10-09 21:53
Same applies for computed properties in destructuring:
```
({[`${field}`]:word})=> word.startsWith(letter)
```

Babel says: 
```
(function (_ref) {
  var word = _ref["" + field];
  return word.startsWith(letter);
});
```
TypeScript says:
```
(function (_a, word) {
    var _a = [("" + field)];
    return word.startsWith(letter);
});
```

**Comment by vladima** [comment] 2015-10-09 22:40
#4917 already tracks computed properties in destructuring

**Closed** 2015-10-11 05:39 UTC
Labels: Bug
