### ISSUE TITLE
Type incorrectly inferred as `never`

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#47021] opened 2021-12-04 06:05 UTC
# Bug Report

### 🔎 Search Terms

never type incorrect

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.5.2#code/DYUwLgBAZg9jBcEAUSCUEC8A+CBnMATgJYB2A5ugD4QCuJAJiFKSPZrQ0y-QNwBQfKHQDGYIjBIQARgEMCaCAG8+EVdDjsF2CAHIAEiGDAYEAOowCwejv4BfAbPmp+RKMlgx0ytepho7AkA

### 💻 Code

```ts
let foo: (() => string) | undefined = undefined;

function bar() {
    foo = () => 'Hello World';
}

bar();
if (foo) {
    foo();
}
```

### 🙁 Actual behavior

`foo` is `never`

### 🙂 Expected behavior

`foo` is `() => string`

**Comment by MartinJohns** [comment] 2021-12-04 06:07
Aaaaaand another duplicate of #9998!

**Closed** 2021-12-09 18:00 UTC
Labels: Duplicate
