### ISSUE TITLE
Object entry remains typed as undefined after assignment

### ISSUE THREAD

**Issue by Ionaru** [microsoft/TypeScript#33073] opened 2019-08-25 15:38 UTC
**TypeScript Version:**  3.7.0-dev.20190824

**Search Terms:**
Object is possibly undefined
TS2532

**Code**

```ts
interface IData {
  data: number;
}

interface IMyObject {
  [index: string]: IData | undefined;
}

const myObject: IMyObject = {};
const objectKey = 'something';

myObject[objectKey] = {
  data: 5
}

console.log(myObject[objectKey].data); // TS2532: Object is possibly 'undefined'
```

**Expected behavior:**
Code compiles without error.

**Actual behavior:**
Error: `TS2532: Object is possibly 'undefined'.` on `myObject[objectKey]`

**Playground Link:** 
http://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgJIBE5jsg3gKGWQBMs4AuZEAVwFsAjaAbnwF999RJZEVUBZAJ4B5egCsICMHkLIA2qGIQAHpQDOYKKADmAXUoYyyAD7JqIJTFARiLdvgQB7EBuS0R4yWANDREqcgAvHisLE4u0o6eUgDSEIJByADkao60EGAAFjpJLPjufl5yUf5gcYK6iQREpNiUAKxsHOGpADYQAHStjtoAFAXRYMWD5bodtXAAlExAA

**Related Issues:** 
#13778, #17960, #26599, #29642

It seems related issues have been around for a long time, in addition issue #26599 was closed as a "wontfix". This is weird to me because it seems Typescript should be able to detect that `objectKey` has not changed between the object assignment and query.

**Comment by AnyhowStep** [comment] 2019-08-25 19:12
If anyone else is looking for a workaround,
```ts
interface IData {
  data: number;
}

interface IMyObject {
  [index: string]: IData | undefined;
}

const myObject: IMyObject = {};
const objectKey = 'something';

myObject.something = {
  data: 5
}

console.log(myObject.something.data);
```
[Playground](http://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgJIBE5jsg3gKGWQBMs4AuZEAVwFsAjaAbnwF999RJZEVUBZAJ4B5egCsICMHkLIA2qGIQAHpQDOYKKADmAXUoYyyAD7JqIJTFARiLdvgQB7EBuS0R4yWANDREqcgAvHisLE4u0o6eUgDSEIJByADkao60EGAAFjpJLPjufl4AdKnpWTqJBESk2JQArGwc4akANhBFLY7aABQF0WAlaRnZINpFNXAAlExAA)

Just don't use string literals/constants. Use dot notation instead.

**Comment by Ionaru** [comment] 2019-08-25 19:29
> Just don't use string literals/constants. Use dot notation instead.

Good solution, but doesn't work when `objectKey` is a variable :)

What I posted is just a demonstration of the issue, in most cases the object keys are not constant but variables or parameters passed to a function.

**Comment by fatcerberus** [comment] 2019-08-26 03:02
If the key is truly variable, then this is related to #31445: TS isn't equipped to understand that two mentions of `obj[key]` access the same property in both places; since it doesn't even know *that*, it doesn't make sense to perform any narrowing on it.

**Comment by sandersn** [comment] 2019-08-29 16:22
Yep, duplicate of #31445 (and some others).

**Closed by sandersn** 2019-08-29 16:22 UTC
Labels: Duplicate
