### ISSUE TITLE
Support arbitrary module namespace identifier names

### ISSUE THREAD

**Issue by mhmd-22** [microsoft/TypeScript#52092] opened 2023-01-04 02:07 UTC
# Suggestion

The new  ES2022 standard allows to use string literals in module exports and imports:

```javascript
import {"\0 any unicode" as foo} from "";
export {foo as "\0 any unicode"};
```
Ref: https://github.com/tc39/ecma262/pull/2154

This feature is supported in NodeJS since v16(2021) and I have been using this feature but typescript complains about invalid syntax and I don't see this feature in the roadmap?.

## 🔍 Search Terms
String literals import and export

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by IllusionMH** [comment] 2023-01-04 03:45
Duplicate of #40594

**Comment by mhmd-22** [comment] 2023-01-04 16:30
I have been searching hours for similar issue. Anyways, This issue still open from 2 years ago, any update or plan to support it next versions?

**Closed** 2023-01-04 16:30 UTC
