### ISSUE TITLE
Wrong enum type inference (narrowing) in async scope

### ISSUE THREAD

**Issue by MrCelestis** [microsoft/TypeScript#56633] opened 2023-12-01 07:23 UTC
### 🔎 Search Terms

enum type inference narrowing async bug

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (3.3.3, 5.3.2, nightly 5.4.0), and I reviewed the FAQ for entries about enum type inference, async and enum narrowing.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.2#code/MYewdgzgLgBApmArgWxgZRMuUAWBLMAcxgG8B6MiAQyxgCM4cqA3PEAJ3pFxgDMOYYKlDzM4MKmAAmMUJFgIUEAFAw1MAIIAaVeoBCygL6rlwADZUIEGADEQIUrrUQAXOkzZ8RGAF53WXAJCADoNAG4jZVNwaD57X0E4AHdbewAKAEoImGVLAE8wYD5EQpFwPkzHdTiQYOs-DACvEL1s9SokqjxYAAV2TDwIOGD2OAgQMzFM4NwENMqfAD4auoTGzyDQrIp+WutBmEIQIJgoBwZ-DaJQiV4oOE4OrpEiJxg8Xhg03dWfP8vAtcNBlSBQ6IhYDgHuIACpoCRWFBjU5MWA-eoNDyAloSaQo4Qo6EAcmsYAcIDE7AsAAcYElujgAc1Qm9qqMoIh2GBTuxEHA2mpjGzsJzubwqGYhhFDEA

### 💻 Code

```ts
const enum Something {//same behavior both for native and const enums
    A,
    B
}
 
class Foo {
    s: Something = Something.A;
}

const foo = new Foo();
 
async function f() {
    foo.s = Something.B;
    await Promise.resolve().then(() => foo.s = Something.A);//foo.s is going to be Something.A after awaiting
    if (foo.s === Something.A) {//but here TS assumes that foo.s == Something.B and that there's no overlap with Something.A
        return true;
    }
    return false;
}
```

### 🙁 Actual behavior

Code fails to compile with error "This comparison appears to be unintentional because the types 'Something.B' and 'Something.A' have no overlap."

### 🙂 Expected behavior

Code is expected to compile

**Comment by MartinJohns** [comment] 2023-12-01 07:35
Another duplicate of #9998.

**Closed** 2023-12-04 01:29 UTC
Labels: Duplicate
