### ISSUE TITLE
Compiler outputting suboptimal declarations

### ISSUE THREAD

**Issue by jiaweihli** [Microsoft/TypeScript#2015] opened 2015-02-12 00:53 UTC
I'm working on a library using TypeScript called [monapt](https://github.com/jiaweihli/monapt).  I have a grunt task to compile multiple files and concatenate them together.  However, the output definition has some potential downsides. (I can't remember exactly what they are at the moment, but hopefully someone else can shed some light on this)  

Here is a common manual fix I need to do every time before release: https://github.com/jiaweihli/monapt/commit/0da8b09c64f9870a815c389eac1a0dd38e4f65fe

**Comment by danquirk** [comment] 2015-02-12 00:59
You want #17?

**Comment by jiaweihli** [comment] 2015-02-12 01:36
Yes, a combination of that and having `declare module` statements use the string-ified name of the module.

**Comment by danquirk** [comment] 2015-02-12 01:52
Yeah, that would be part of supporting multi-file modules correctly. Gonna close this as a duplicate of that.

**Closed by danquirk** 2015-02-12 01:52 UTC
