### ISSUE TITLE
Incorrect type narrowing after Array.isArray typeguard on union with generic

### ISSUE THREAD

**Issue by timbodeit** [microsoft/TypeScript#46534] opened 2021-10-26 10:35 UTC
# Bug Report

### 🔎 Search Terms

* label:Bug typeguard
* label:Bug narrow* incorrect 

### 🕗 Version & Regression Information

* This is the behavior in every version I tried, and I reviewed the FAQ for entries about "Bugs" that have existed in TS for a long time
* I tested versions:
    * v3.3.33333 ([playground](https://www.typescriptlang.org/play?ts=3.3.3#code/GYVwdgxgLglg9mABAGzgcwMpQE4zGgQQGciQBbAB1gQAo8KQoAuRInPNASkQG8BYAFCJhiCAiJxkAUwB0qNDQAGAFQCeFKa1VspZRDCKsQ2TVAAWAQyiIo6qXGCIAJD3qMAvohoWA1hcQA5C62Gg76YAxQ7gHcZCBsiABGmgFsuPgBipwA3ILugqCQ1EhQUmwAPACSAHx0EYwsaRwA2gC6iAA+iJXc-EL6jjQE2NgWqjIGw6OqdZGcvYIiIvJY6YQk5FTwYLOMzQAMrTmLiPkCZ6VsNM0AjABMAMwALACsR7kCQA))
    * v4.4.4 ([playground](https://www.typescriptlang.org/play?ts=4.4.4#code/GYVwdgxgLglg9mABAGzgcwMpQE4zGgQQGciQBbAB1gQAo8KQoAuRInPNASkQG8BYAFCJhiCAiJxkAUwB0qNDQAGAFQCeFKa1VspZRDCKsQ2TVAAWAQyiIo6qXGCIAJD3qMAvohoWA1hcQA5C62Gg76YAxQ7gHcZCBsiABGmgFsuPgBipwA3ILugqCQ1EhQUmwAPACSAHx0EYwsaRwA2gC6iAA+iJXc-EL6jjQE2NgWqjIGw6OqdZGcvYIiIvJY6YQk5FTwYLOMzQAMrTmLiPkCZ6VsNM0AjABMAMwALACsR7kCQA))
    * v4.5.0-dev.202111026 ([playground](https://www.typescriptlang.org/play?ts=4.5.0-dev.20211026#code/GYVwdgxgLglg9mABAGzgcwMpQE4zGgQQGciQBbAB1gQAo8KQoAuRInPNASkQG8BYAFCJhiCAiJxkAUwB0qNDQAGAFQCeFKa1VspZRDCKsQ2TVAAWAQyiIo6qXGCIAJD3qMAvohoWA1hcQA5C62Gg76YAxQ7gHcZCBsiABGmgFsuPgBipwA3ILugqCQ1EhQUmwAPACSAHx0EYwsaRwA2gC6iAA+iJXc-EL6jjQE2NgWqjIGw6OqdZGcvYIiIvJY6YQk5FTwYLOMzQAMrTmLiPkCZ6VsNM0AjABMAMwALACsR7kCQA))

### ⏯ Playground Link

* v3.3.33333 ([playground](https://www.typescriptlang.org/play?ts=3.3.3#code/GYVwdgxgLglg9mABAGzgcwMpQE4zGgQQGciQBbAB1gQAo8KQoAuRInPNASkQG8BYAFCJhiCAiJxkAUwB0qNDQAGAFQCeFKa1VspZRDCKsQ2TVAAWAQyiIo6qXGCIAJD3qMAvohoWA1hcQA5C62Gg76YAxQ7gHcZCBsiABGmgFsuPgBipwA3ILugqCQ1EhQUmwAPACSAHx0EYwsaRwA2gC6iAA+iJXc-EL6jjQE2NgWqjIGw6OqdZGcvYIiIvJY6YQk5FTwYLOMzQAMrTmLiPkCZ6VsNM0AjABMAMwALACsR7kCQA))
* v4.4.4 ([playground](https://www.typescriptlang.org/play?ts=4.4.4#code/GYVwdgxgLglg9mABAGzgcwMpQE4zGgQQGciQBbAB1gQAo8KQoAuRInPNASkQG8BYAFCJhiCAiJxkAUwB0qNDQAGAFQCeFKa1VspZRDCKsQ2TVAAWAQyiIo6qXGCIAJD3qMAvohoWA1hcQA5C62Gg76YAxQ7gHcZCBsiABGmgFsuPgBipwA3ILugqCQ1EhQUmwAPACSAHx0EYwsaRwA2gC6iAA+iJXc-EL6jjQE2NgWqjIGw6OqdZGcvYIiIvJY6YQk5FTwYLOMzQAMrTmLiPkCZ6VsNM0AjABMAMwALACsR7kCQA))
* v4.5.0-dev.202111026 ([playground](https://www.typescriptlang.org/play?ts=4.5.0-dev.20211026#code/GYVwdgxgLglg9mABAGzgcwMpQE4zGgQQGciQBbAB1gQAo8KQoAuRInPNASkQG8BYAFCJhiCAiJxkAUwB0qNDQAGAFQCeFKa1VspZRDCKsQ2TVAAWAQyiIo6qXGCIAJD3qMAvohoWA1hcQA5C62Gg76YAxQ7gHcZCBsiABGmgFsuPgBipwA3ILugqCQ1EhQUmwAPACSAHx0EYwsaRwA2gC6iAA+iJXc-EL6jjQE2NgWqjIGw6OqdZGcvYIiIvJY6YQk5FTwYLOMzQAMrTmLiPkCZ6VsNM0AjABMAMwALACsR7kCQA))

### 💻 Code

```
function logStringAssumption(input: string) {
    console.log(`Type system is sure that typeof ${input} (aka '${typeof input}') must be 'string'`);
}
function test<I>(input: string[] | I) {
  if (Array.isArray(input)) {
      logStringAssumption(input[0]);
  }
}
test([12345]);
```

### 🙁 Actual behavior

* In line 6 of the code above (line 8 in the screenshot), `input` is inferred to be of type `string[]`
* Passing `input[0]` into `logStringAssumption` compiles successfully

<img width="1194" alt="Screen Shot 2021-10-26 at 12 09 13" src="https://user-images.githubusercontent.com/4222754/138861315-90a421ac-999b-48cf-b382-abd7b1b44ae8.png">

### 🙂 Expected behavior

* The typechecker should account for the fact, that `I` can be some other array type such as `number[]`
* In line 6, `input` should be inferred to be of type `string[] | (I & any[])`
* Passing `input[0]` should not compile as `any` is not assignable to `string`

**Comment by andrewbranch** [comment] 2021-11-04 21:29
Duplicate of https://github.com/microsoft/TypeScript/issues/45686

**Closed** 2021-11-07 18:00 UTC
Labels: Duplicate
