### ISSUE TITLE
VSCode and intellisense are broken and unstable

### ISSUE THREAD

**Issue by CyriacBr** [microsoft/TypeScript#32033] opened 2019-06-20 14:17 UTC
- VSCode Version: 1.35.5
- OS Version: Linux Elementary OS

Steps to Reproduce:

1. Open a TS project with VSCode.
2. Either:
  *Remove the node_modules folder
  *Reinstall/delete/add a new npm package
  *Use npm/yarn link
3. Intellisense breaks. When removing packages, you will get a bunch of errors, which is normal. But installing back everything doesn't update TS state.  
Somehow VSCode bugs and gets stuck at a previous state. In the case of `npm link` sometimes it doesn't recognize the package being added.
When that happens, in most cases, TS server shuts down and any Intellisense feature is infinitely "Loading..." when required.
Though, sometimes things work out when I trigger autocomplete and everything is back to normal.

I have to restart VSCode or the TS Server all the time to refresh intellisense.
It just seems that VSCode cannot reliably react to any kind of file changes.

It's been like that since forever as far as I recall, however, the last few updates just made things worse I guess. I've never had a 100% reliable TS experience.
With the latest update, syntax highlighting stops working randomly too.

Does this issue occur when all extensions are disabled?: Yes it does.

**Comment by mjbvz** [comment] 2019-06-21 22:00
@sheetalkamat I suspect this is related to the file watcher. Simple repo:

1. Create a new angular project `ng new app`
1. Open in VS Code and open a ts file
1. Now delete `node_modules`
1. Intellisense hangs for ~a minute
1. Now npm install
1. Another hang

In the larger VS Code repo, doing these steps can cause the server to get into a state where it never seems to finish loading

**Comment by venky76v** [comment] 2019-07-02 18:15
Hi, I too seem to have this issue. Open a newly created Angular repo in VS code, don't know if this is related to any extennsion. Intellisense doesn't seem to work at all. All I get is "Loading...". Sometimes is works randomly, other times it doesn't all. This is a productivity killer and it is very annoying.

![image](https://user-images.githubusercontent.com/14880307/60536271-ca86c680-9cfd-11e9-9cfc-8b2e69a40bd6.png)

**Comment by CyriacBr** [comment] 2019-07-03 22:35
@sheetalkamat If that can help, I found that refreshing the tsconfig.json (ie, deleting a character, undoing and saving the file) makes TS works again like usual. 
But it's still annoying to do so every time you `yarn add` something and TS breaks.

@venky76v When that happens, do you see the "Initializing TS/JS languages features" at the bottom-left in the status bar? If so then that's normal that Intellisense doesn't work right after opening an Angular repo because VSCode needs to initialize the TS features first.

**Comment by OneCyrus** [comment] 2019-07-03 22:42
we have this issue as well. changing some types lead to a „stuck“ typescript experience. changing between integrated and workspace version (basically restarting typescript) fixes the issue until it breaks again.

**Comment by venky76v** [comment] 2019-07-04 13:26
> @sheetalkamat If that can help, I found that refreshing the tsconfig.json (ie, deleting a character, undoing and saving the file) makes TS works again like usual.
> But it's still annoying to do so every time you `yarn add` something and TS breaks.
> 
> @venky76v When that happens, do you see the "Initializing TS/JS languages features" at the bottom-left in the status bar? If so then that's normal that Intellisense doesn't work right after opening an Angular repo because VSCode needs to initialize the TS features first.

Hi, As soon as I open a Angular repo, I see the initializing JS/TS features on the status bar. After this the message is gone. Now opening a ts file, say app.component.ts file and type this. + control + spacebar, all I see "Loading..." like so below:
![image](https://user-images.githubusercontent.com/14880307/60669832-346eaf80-9e67-11e9-9722-7ca24a950773.png)

If I leave the VS window and come back to it after a few minutes, like write this reply and then come back and hit control + space bar, I see the intellisense working. This is a productivity killer and it also kills your flow of throught, as well the behavior being totally inconsistent.

![image](https://user-images.githubusercontent.com/14880307/60670033-a646f900-9e67-11e9-9293-11e944451562.png)

**Comment by CyriacBr** [comment] 2019-07-05 11:39
> Hi, As soon as I open a Angular repo, I see the initializing JS/TS features on the status bar. After this the message is gone. Now opening a ts file, say app.component.ts file and type this. + control + spacebar, all I see "Loading..." like so below:

I see. This is not really the issue I am describing. I suggest you look into others issue. I recall saying something similar.  
The problem that @OneCyrus and I are facing is that Typescript breaks when a file changes.  

Just right now I cloned a git monorepo. Naturally, the packages were not installed, so Typescript was signaling 'modules not found' left and right. Even after I ran yarn and lerna to bootstrap and link all the packages in the repo Typescript was still stuck at its previous state. I again had to reload the TS server.

**Comment by Morphexe** [comment] 2019-07-12 12:28
Not 100% sure if related - but seems to fit -, but I have been finding that ts server and tsc sometimes will just stop listening for file changes, as in, if you make a change to a file, it doesn't get picked up to trigger a incremental compilation.

**Comment by sheetalkamat** [comment] 2019-07-31 22:38
This seems to be Linux and potentially macOs specific issue and result of https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_inodes inode watching. Looking into fix for this issue. Thanks

**Comment by svipas** [comment] 2019-09-29 22:39
I can confirm I have this issue and I can agree it's related to file watching. I'm using macOS 10.14.6.

**Comment by sheetalkamat** [comment] 2019-12-10 21:23
https://github.com/microsoft/TypeScript/pull/35615#issuecomment-564263744 is the fix for this. Feel free to try it out and provide feedback. Thanks

**Closed** 2019-12-11 21:27 UTC
Labels: Bug, Fix Available
