### ISSUE TITLE
Error:(6, 21) TS2307: Cannot find module 'normalize-num'.

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#29256] opened 2019-01-04 10:39 UTC
**TypeScript Version:**  3.3.0-dev.201xxxxx

**Search Terms:**

**Code**

ide is idea 2018.3.3

tsc -v
Version 3.3.0-dev.20190101

Error:(6, 21) TS2307: Cannot find module 'normalize-num'.

![image](https://user-images.githubusercontent.com/167966/50683966-e65f2780-104e-11e9-9236-c0daa398d8a8.png)

https://github.com/bluelovers/ws-node-novel
```
/workspace root
　/node_modules
　　normalize-num
　/packages
　　/node-novel-normalize
　　　index.ts
　tsconfig.json
```

- [tsconfig.json]()
- [num-normalize](https://github.com/bluelovers/num-normalize)
- [packages/node-novel-normalize](https://github.com/bluelovers/ws-node-novel/tree/master/packages/node-novel-normalize)

**Expected behavior:**

> no error

**Actual behavior:**

> Error:(6, 21) TS2307: Cannot find module 'normalize-num'.

**Playground Link:** 

**Related Issues:**

**Comment by ajafff** [comment] 2019-01-04 11:05
If you really want someone to diagnose your build failures, you should at least provide enough information to reliably reproduce it. Simply linking to a repository is far from sufficient.

**Comment by bluelovers** [comment] 2019-01-04 11:42
im not realy wanna someone handle this fail,
but i guess this is a unknow **random** bug

because `str-util` can be found, but `normalize-num` can't

and this error not always happen, it like today no error, tomorrow it got this error

**Comment by weswigham** [comment] 2019-01-04 20:35
> and this error not always happen, it like today no error, tomorrow it got this error

I downloaded your repro, ran `lerna bootstrap`, and also had no issues 🤷‍♂️  Does it happen after you do some specific editing or something?

> ide is idea 2018.3.3

Though I was using vscode (on windows), to be honest, so my environment's a bit different

**Comment by RyanCavanaugh** [comment] 2021-12-16 00:46
Closing due to lack of repro

**Closed by RyanCavanaugh** 2021-12-16 00:46 UTC
Labels: Needs More Info
