### ISSUE TITLE
Wrong intellisense popup travels with cursor

### ISSUE THREAD

**Issue by ackvf** [Microsoft/TypeScript#25266] opened 2018-06-27 11:10 UTC
**TypeScript Version:**  `2.9.2` and `3.0.0-dev.20180626`

**Search Terms:** 
jsx props intellisense moves with cursor

**Code**

```ts
import Table from 'antd/lib/table'
//...
render() {
  return (
    <Table.Column render={(){/*<- cursor between braces*/}}/>
  )
}
```

**Expected behavior:**

Expected is that intellisense popup disappears.

**Actual behavior:**

![prop-intellisense](https://user-images.githubusercontent.com/2313018/41970327-b747e41c-7a0a-11e8-9773-a8ad89a1e2f3.png)

_last screen is ctrl+space invoked on `render` so that two(three) popups are now visible_

**Playground Link:** 

https://github.com/ackvf/typescript-repro/tree/render-prop

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/25265

**Comment by mhegazy** [comment] 2018-06-28 00:31
this looks like a duplicate of #25265 or at least the same underlying cause.

**Comment by ackvf** [comment] 2018-06-28 10:48
Ok, I was not sure that the ghost popup is really tied to the same cause, so I created two issues.

**Closed** 2018-07-12 18:46 UTC
Labels: Duplicate
