### ISSUE TITLE
Add support for asyncronous assertion functions and methods

### ISSUE THREAD

**Issue by Nokel81** [microsoft/TypeScript#48309] opened 2022-03-17 16:04 UTC
# Suggestion

## 🔍 Search Terms

- assertion
- method
- function
- async
- promise

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow functions and methods of the signature `(...args: any[]) => Promise<asserts condition>` which mean that `condition` is true if the promise resolves.

## 📃 Motivating Example

Sometimes it is necessary to call asynchronous functions to make sure that some field is assigned. For instance, a somewhat common pattern is to have an `async ensureFieldX(): Promise<void>` method and it would be nice if typescript knew that after that method has resolved (and not rejected).

```typescript
class Foo {
  private bar: string | undefined;

  async getBar(): Promise<string> {
    await this.ensureBar();

    return this.bar;
  }

  private async ensureBar(): Promise<asserts this is (Foo & { bar: string })> {
     ...
  }
}
```

## 💻 Use Cases

See motivating example...

Could also be extended to asynchronous user defined type guards but I don't think that is as important.

**Comment by whzx5byb** [comment] 2022-03-17 18:49
In this case you could use logical assignment as workaround:
```ts
class Foo {
  private bar: string | undefined;

  async getBar(): Promise<string> {
    return this.bar ||= await this.createBar();
  }

  private async createBar(): Promise<string> {
     //...
  }
}
```

**Comment by Nokel81** [comment] 2022-03-17 19:09
You could indeed but that is a bit cumbersome.

**Comment by MartinJohns** [comment] 2022-03-17 19:13
Duplicate of #37681.

**Closed** 2022-03-17 19:16 UTC
