### ISSUE TITLE
SUGGESTIONS: getters/setters in interface

### ISSUE THREAD

**Issue by dungdm93** [Microsoft/TypeScript#11878] opened 2016-10-27 02:20 UTC
It'd be cool feature if we could  using getter/setter (accessors) in interfaces. For example:

```typescript
interface I {
    get name(): string;
}

class C1 implements I {
    public name: string = "Batman";
}

class C2 implements I {
    get name(): string {
        return "Superman";
    }
}

class C3 implements I {
    public readonly name: string = "Iron Man";
}

let i: I = { name: "Thor" };
```

**Comment by wallverb** [comment] 2016-10-27 03:37
Hmmm,

Is there something wrong with

```ts
interface I {
    name: string;
}

class C1 implements I {
    public name: string = "Batman";
}

class C2 implements I {
    get name(): string {
        return "Superman";
    }
}

class C3 implements I {
    public readonly name: string = "Iron Man";
}

let i: I = { name: "Thor" };
```

**Comment by RyanCavanaugh** [comment] 2016-10-27 04:37
What's the difference between this and `readonly name: string` supposed to be?

**Comment by HerringtonDarkholme** [comment] 2016-10-27 05:41
There is runtime difference. getter has `get` function in descriptors, but readonly does not necessarily have.
But this is runtime difference, so adding this to type system is contrary to TypeScript's design, isn't it?

**Comment by dungdm93** [comment] 2016-10-27 08:06
@RyanCavanaugh `readonly` indicate **un-reassignable** property. While `getter` can be used as **computed** property. For examble:
```ts
class Person {
    public firstName: string;
    public lastName: string;

    constructor(firstName: string, lastName: string) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    public get fullName() {
        return `${this.firstName} ${this.lastName}`;
    }
}

let p: Person = new Person("Bruce", "Wayne");
alert(p.fullName);

p.firstName = "Clark";
p.lastName = "Kent";
alert(p.fullName);
```

**Comment by kitsonk** [comment] 2016-10-27 08:11
@dungdm93 but that makes no difference from an interface perspective. `p.fullName` is of a type string and cannot be assigned a value.  What difference would it make from an interface perspective?

**Comment by dungdm93** [comment] 2016-10-27 08:20
@kitsonk OK. maybe my example make confused.
So about if I wan to declare **setter only Interface**?

**Comment by kitsonk** [comment] 2016-10-27 08:26
Then it is a dupe of #11596 or #10196 or #3757 or many other ones.

**Comment by dungdm93** [comment] 2016-10-27 09:53
Using `readonly` in interface make people so confused.
From my aspect, allow `getter`/`setter` declared in interface make more sense.
[Reference](https://github.com/Microsoft/TypeScript/issues/10196#issuecomment-256589098)

**Comment by kitsonk** [comment] 2016-10-27 10:07
Why is it confusing?

The interface describes the types of an interface, not the implementation, the the ability to assign values.  You are suggesting that the interface should concern itself with implementation details?  That is unsound.

For example, from an interface perspective what is the difference between a getter only property that returns a string and a non-writable property that has a value of string?  Why would the interface be concerned about that distinction?

**Comment by dungdm93** [comment] 2016-10-27 12:09
I'm not mean the interface should care about implementation details itself.

`readonly` in class and interface have difference meaning. In the class, it define an un-reassignable property. However, in the interface, it declare a abstract `getter`. For the distinction, un-reassignable property contain implementation details, while abstract getter is not. So that is why it make many people confusing at the first time.

So my suggestion is allow abstract getter **act the same as** `readonly` work in interface. You can consider it as more sensible alternative syntax. Furthermore, there are no `writeonly` keyword to declare abstract setter, but using this syntax you can.

**Comment by kitsonk** [comment] 2016-10-27 12:30
In regards to `writeonly` Mohammed expressed that it is so obscure that the feeling is that it isn't worth the overhead in modelling it in the type system. (see: #11596)  But if you feel there is real world value in such a use case, then I would add your arguments to that issue.

Again, as far as read only, what is the difference between:

```
interface Foo {
    readonly foo: string;
}

class FooA implements Foo {
    readonly foo: string;
    constructor() {
        Object.defineProperty(this, 'foo', {
            value: 'bar',
            writable: false,
            enumerable: true,
            configurable: true
        });
    }
}

class FooB implements Foo {
    get foo(): string {
        return 'bar';
    }
}
```

Answer is nothing.  There is more than one way of implementing a read only property in JavaScript, therefore the interface shouldn't be concerned about implementation.

**Comment by RyanCavanaugh** [comment] 2016-10-27 17:24
Just to say this explicitly, because there seems to be some confusion: `readonly` is not `const`!. It has never meant `const` and it would be straight-out wrong to conflate the two. A custom `Stack` implementation, for example, would have a `readonly` `length` property, but it wouldn't be `const` (unless you wanted the stack to always be empty)

**Closed by RyanCavanaugh** 2016-10-27 17:24 UTC
Labels: Duplicate

**Comment by dungdm93** [comment] 2016-10-28 01:50
@RyanCavanaugh So sad. I just wanna interface support a feature of class:
```ts
abstract class Abstract {
    abstract set foo(value: string);
    abstract get bar(): string;
}

class Concrete implements Abstract { // Make class be interface => It's work
    private f: string;
    private b: string;

    set foo(value: string) {
        this.f = value;
    }

    get bar(): string {
        return this.b;
    }
}
```

Why we can't declare like:
```ts
interface Abstract {
    set foo(value: string);
    get bar(): string;
}
```

**Comment by mhegazy** [comment] 2016-10-28 22:49
An interface represents a contract, a shape, not how it is implemented. 

In JS there are two ways to implement properties, either as property declarations, or as accessors. From the user of the object perspective it does not matter.

Consider this:

```ts
var i1 = {
    p: 1
};

var i2 = {
    get p() { return 1; }
    set p(v) { }
};
```

From the user perspective, both `i1` and `i2` have the same shape. they have a property called `p` on them that is a `number`, and you can both read it and write it. how they are implemented is not martial for the user.

Thus the type is:
```ts
interface I {
    p: number;
}
```
hope this makes it clear.
