### ISSUE TITLE
TypeError: Cannot redefine property: default

### ISSUE THREAD

**Issue by zhinanchendd01** [microsoft/TypeScript#38679] opened 2020-05-20 08:09 UTC
**TypeScript Version:**  3.9.3

**Code**

file1.js
```js
module.exports = {
  default: {
    log() {
    }
  },
}

```

file2.ts
```ts
import file1 from './file1'
file1.log()
```

**Actual behavior:**

```
TypeError: Cannot redefine property: default
```

**Related Issues:** #38552

**Comment by joeldenning** [comment] 2020-05-25 02:24
This is likely a duplicate of https://github.com/microsoft/TypeScript/issues/38540

**Comment by weswigham** [comment] 2020-05-27 17:50
I actually can't reproduce the issue in the OP - @zhinanchendd01 is there more context to this? Or a specific set of compiler options? I've tried both with and without `esModuleInterop` on, and can't replicate your result.

**Comment by malord** [comment] 2020-05-31 13:15
I just had this with TypeScript 3.9.3. This is my tsconfig.json:

```
{
  "compilerOptions": {
    "target": "es2018",
    "module": "commonjs",
    "outDir": "./lib",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true
  },
  "exclude": [
    "test"
  ]
}
```

I found out that this fails:

```
import sequelize, { Op, Sequelize } from 'sequelize';
```

But this works:

```
import { Op, Sequelize } from 'sequelize';  
import sequelize from 'sequelize';
```

**Comment by Johnvict** [comment] 2020-05-31 19:09
> I just had this with TypeScript 3.9.3. This is my tsconfig.json:
> 
> ```
> {
>   "compilerOptions": {
>     "target": "es2018",
>     "module": "commonjs",
>     "outDir": "./lib",
>     "rootDir": "./src",
>     "strict": true,
>     "esModuleInterop": true
>   },
>   "exclude": [
>     "test"
>   ]
> }
> ```
> 
> I found out that this fails:
> 
> ```
> import sequelize, { Op, Sequelize } from 'sequelize';
> ```
> 
> But this works:
> 
> ```
> import { Op, Sequelize } from 'sequelize';  
> import sequelize from 'sequelize';
> ```

This solved the whole thing.. Thank you

**Comment by aecorredor** [comment] 2020-06-01 00:06
Same exact thing is happening to me with sequelize right after going from `3.8.3` to `3.9.3`. Is this expected or is it a regression?

**Comment by aecorredor** [comment] 2020-06-01 00:16
Just saw there's a fix already in #38540

**Comment by zhinanchendd01** [comment] 2020-06-02 03:37
my `tsconfig.json`
```json
{
	"compileOnSave": true,
	"compilerOptions": {
		"target": "es2018",
		"module": "commonjs",
		"esModuleInterop": true,
		"outDir": "dist",
		"baseUrl": "src",
	},
	"exclude": ["dist", "node_modules"]
}

```

`logger.js`
```js
const info = (...args) => {
  console.log(...args)
}

const debug = (...args) => {
  console.debug(...args)
}

module.exports = { info, debug }

module.exports.default = { info, debug }
```

`index.ts`

this failed: 
```ts
import * as logger from './logger'
logger.debug('debug 1')
// TypeError: Cannot redefine property: default
```

this can work:
```ts
import logger from './logger'
logger.debug('debug 1')
```

@weswigham

**Comment by zhinanchendd01** [comment] 2020-06-02 04:15
`logger.js`
```js
const info = (...args) => {
  console.log(...args)
}

const debug = (...args) => {
  console.debug(...args)
}

module.exports.default = { info, debug }
```

`index.ts`

```ts
import logger from './logger'
logger.info('info')
// TypeError: logger_1.default.info is not a function

console.log(logger)
// { default: { info: [Function: info], debug: [Function: debug] } }
```

**Comment by kherock** [comment] 2020-06-04 15:33
This actually appears to be fixed for my code in v3.9.4, but it's not currently published to npm with the `latest` tag.

**Comment by MaciekBaron** [comment] 2020-06-05 17:47
> But this works:
> 
> ```
> import { Op, Sequelize } from 'sequelize';  
> import sequelize from 'sequelize';
> ```

I have exactly the same issue – for some reason I cannot write:

    import parse, { domToReact } from 'html-react-parser';

I have to split it into two lines.

**Closed** 2020-06-08 20:01 UTC
Labels: Needs Investigation, Needs More Info

**Comment by TranDinhKhang** [comment] 2020-08-04 10:35
This helps me. 
```
    "typescript": "3.9.7",
    "tslib": "1.13.0"
```
