### ISSUE TITLE
TS does not know about the existence of the window.fetch?

### ISSUE THREAD

**Issue by acopalipsis** [Microsoft/TypeScript#8966] opened 2016-06-04 10:46 UTC
`window.fetch(...)`  

> error TS2304: Cannot find name 'fetch'.

**Comment by kitsonk** [comment] 2016-06-04 11:58
Fetch is only just coming to Edge 14.  The tool located at [Microsoft/TSJS-lib-generator](https://github.com/Microsoft/TSJS-lib-generator) is what deals with generating the library off of Edge with certain modifications and overrides.  That then is what is checked into TypeScript.

**Comment by mhegazy** [comment] 2016-06-04 18:22
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mhegazy** [comment] 2016-06-04 19:47
if you do not mind, we would like to keep this issue open.

**Comment by basarat** [comment] 2016-06-05 01:55
I've used `whatwg-fetch` typings https://github.com/alm-tools/alm/blob/c7d31e48864a96379fabe27d1bb507ccce3e9319/src/typings.json#L28 with both https://github.com/github/fetch and https://www.npmjs.com/package/node-fetch :rose:

**Comment by styfle** [comment] 2016-06-18 14:02
@basarat Correct there is a [fetch.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/whatwg-fetch/whatwg-fetch.d.ts) that works quite well.

One thing to consider is that `fetch` relies on a `Promise`. So using target=ES5 will complain about `Promise` missing:

> error TS2304: Cannot find name 'Promise'.

Are there different versions of `lib.d.ts` depending on the `target` param? If so, then `fetch` should only be added to ES6 target.

**Comment by priyajeet** [comment] 2016-10-12 01:42
Any updates on this? Thanks

**Comment by kitsonk** [comment] 2016-10-12 06:58
It is open as accepting PR with a Milestone of the community (noted by the labels and milestone on the right of the issue), which is an indication that the core TypeScript do not currently have the resources to address this as a priority, but anyone in the community is more than welcome to contribute it.

**Comment by andy-ms** [comment] 2016-10-21 14:43
Duplicate of #4948

**Closed by andy-ms** 2016-10-21 14:43 UTC
Labels: Accepting PRs, Domain: lib.d.ts, Suggestion

**Comment by mhgamework** [comment] 2017-03-28 09:06
Any updates on this? I am unable to find a working fetch dts file, am i missing something.

**Comment by andy-ms** [comment] 2017-03-28 14:40
@mhgamework In the latest TypeScript, fetch is available with [`--lib dom`](http://www.typescriptlang.org/docs/handbook/compiler-options.html).
