### ISSUE TITLE
Bug for typescript editor 1.7.6.0 for visual studio 2015:

### ISSUE THREAD

**Issue by kennywangjin** [Microsoft/TypeScript#6605] opened 2016-01-25 07:56 UTC
Text editor for typescript 1.7.6.0 in visual studio 2015 can not response to keyboard inputs (numbers and words, but tab/enter still work).
It just happened. I even have not notice when it happened. I have reset vs settings and also restart the computer. It's still dead. Please help to check. Thanks in advance.

**Comment by snerks** [comment] 2016-01-25 19:06
Possible duplicate of [#6392](https://github.com/Microsoft/TypeScript/issues/6392 "Possible dupe of #6392?")?

**Comment by DanielRosenwasser** [comment] 2016-01-25 19:13
Yup, thanks for digging that up @snerks!

**Closed by DanielRosenwasser** 2016-01-25 19:13 UTC
