### ISSUE TITLE
Tagged union not narrowed when using a constant to index the discriminating property

### ISSUE THREAD

**Issue by zlotnleo** [microsoft/TypeScript#45183] opened 2021-07-26 15:21 UTC
# Bug Report
### 🔎 Search Terms
tagged union narrowing bracket notation

### 🕗 Version & Regression Information
The bug exists on all versions of TS in the playground (3.3.3, 3.5.1, 3.6.3, 3.7.5, 3.8.3, 3.9.7, 4.0.5, 4.1.5, 4.2.3, 4.3.5, 4.4.0-beta and nightly 4.4.0-dev.20210726)

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZgGwIYHMBySC2BTGBeGAcgEsIAxZFQgbgFgAoBqATwAdcBBARnxgG8GMGAG1EqDDgC6ALhhQATgFdsAGkExo84mBQAFeSFazN2lAwC+DJm04AmXgPpDRlCdhnwkCCKvVhFmABG2PL6hrL+QSEWVvQs7DAcvNwwAD6JtnSM9AD0OTAA8gDSDKCQsAAmIFAcwMDYEBC8ABRIshwAlPgAfDBIAHSkFKgwAPx9-SY6YawwsgORwaEGrFkMeYUl9GXQMIHySMAA1tg1dQ0QADLEUCFeLW2JXXi9SMIk5JSEkmMTU3orOYTRYhGZrXL5ACi8gM8gg0nW+RmIRYRH+M0IMCqDRgYGqMGwAA9SLBwHIbEQOIR+oihDBkfJUYR0StMdimnjYESSTAyfFcIQOLZqYjaQymSDloY2SAcZyCcTdnyKYKRRC6eLmERJRisbKOfjuUqwOSEoKuGqdrB9ocTmd6o0AMLgXYEVrtZ6vFziLDuX4DFmGIELAJLMGxIA)

### 💻 Code

```ts
const flagName = 'isFlag';

type A1 = {
  [flagName]: true,
  stringProp: string
}

type A2 = {
  [flagName]: false,
  numberProp: number
}

type A = A1 | A2;

// OK
const dotAccess = (a: A) => a.isFlag ? a.stringProp : a.numberProp;

// OK
const bracketAccessLiteral = (a: A) => a['isFlag'] ? a.stringProp : a.numberProp;

// Errors:
// Property 'stringProp' does not exist on type 'A'.
//   Property 'stringProp' does not exist on type 'A2'.
//
// Property 'numberProp' does not exist on type 'A'.
//   Property 'numberProp' does not exist on type 'A1'.
const bracketAccessConst = (a: A) => a[flagName] ? a.stringProp : a.numberProp;
```

### 🙁 Actual behavior

Using bracket notation with a `const string` property name has a different effect on type narrowing compared to using the property name or bracket notation with a string literal.

### 🙂 Expected behavior

I'd expect `bracketAccessConst` in the example above to type check in the same way `bracketAccessLiteral` does.

**Comment by zlotnleo** [comment] 2021-07-26 15:29
The same behaviour is seen when instead of using a `boolean` to discriminate the union, an `enum` or a `string` is used. See examples below:
<details>
<summary>Using string</summary>

[Playground link](https://www.typescriptlang.org/play#code/MYewdgzgLgBAZgGwIYHMBySC2BTGBeGAckVUIG4BYAKGqgE8AHXAQQEZ8YBvamGAbRLos2ALoAuIklaEANDxjQATgEswKAAqKQDCUtUpqAX2q1GLAEwduVXgORCc4yednywAV0wAjbIs3aJD29fIxMqeiYYZg42GAAfKPNKGioAelSYAHkAaWpQSFgAExAoZmBgbAgIDgAKJAlmAEp8AD4YJAA6QXw8AkIpQhgAfnaOvTV-BhgJTqCfPy0GZOp0rNyqfOgYL0UkYABrbFLyyogAGWUoXyQEWvqo5rw2pD5ie0IRHr6B4dHxjUW01Gc18k2WaQyAFFFFpFBAxCsMpNfPQiP9JoNipUYGASjBsAAPZRbcAwCK4QjMQgdRG8GDIxSowjoxaYkDY3GwQnE2Ck8lEZguGkQ2kMpkghbaNkcvHcklgMlmAXU2m8MV0IgSjEwLHVTn4onyxWRSnSYWbWA7PaHY4VKoAYXAWwIdQaj2edlQGEcX0k0l+nRZ2iBs088zBYSAA)

```ts
const flagName = 'flag';

type A1 = {
  [flagName]: 'a1',
  stringProp: string
}

type A2 = {
  [flagName]: 'a2',
  numberProp: number
}

type A = A1 | A2;

// OK
const dotAccess = (a: A) => a.flag === 'a1' ? a.stringProp : a.numberProp;

// OK
const bracketAccessLiteral = (a: A) => a['flag'] === 'a1' ? a.stringProp : a.numberProp;

// Errors:
// Property 'stringProp' does not exist on type 'A'.
//   Property 'stringProp' does not exist on type 'A2'.
//
// Property 'numberProp' does not exist on type 'A'.
//   Property 'numberProp' does not exist on type 'A1'.
const bracketAccessConst = (a: A) => a[flagName] === 'a1' ? a.stringProp : a.numberProp;
```

</details>

<details>
<summary>Using enum</summary>

[Playground link](https://www.typescriptlang.org/play#code/MYewdgzgLgBAZgGwIYHMBySC2BTGBeGAckVUIG4BYAKGuzAFdMYARASwmACdXNWwkoITjADeMAGpIE9bAEYANBKkyATDAC+1alACeAB1wBBWflHUYMANol0WbAF0AXC3ZcefAUIB0k6XPnmMNDcYCgACpwges7BfCjUmjRUugYwhmoEIoHWyLY4Ti4c3Lz8gpw+ytgqAVQWDJgARticEVHO9U2cCVrJ+kamxjAAPmkqlEkA9BMwAPIA0tSgkLAAJiBQhsDA2BAQpgAUSM6GAJT4AHwwSF42+HgEbEXupd6+MiYA-FdesaGtejBnNcOs1-uNqFNZgsqEtoDAGpwkMAANbYDZbHYQAAyrCgzSkByOaTOeEuSEsxFyhHsdwermKHjKFT8n2+v3CkQBQK8IJanPBVEhAFFOJFOBBHBDpv9mroiOz-oQYGsdjAwOsYNgAB7sWDgGApXCEQyELxSiwwGWcOWEBWcpUqvbq2Da3UwfWGojpU1S81Wm28xXKkCq52anVwj19L0+wXTCz+nREQP24OhjWuyNgA3R42yWOw2AIpGo9HbXYAYXAcIIh2OJLJOVQGHytMKbhKnnKbzkMC+1ztUUB3xTUQFQA)

```ts
const flagName = 'flag';

enum Discriminator { Value1, Value2 }

type A1 = {
  [flagName]: Discriminator.Value1,
  stringProp: string
}

type A2 = {
  [flagName]: Discriminator.Value2,
  numberProp: number
}

type A = A1 | A2;

// OK
const dotAccess = (a: A) => a.flag === Discriminator.Value1 ? a.stringProp : a.numberProp;

// OK
const bracketAccessLiteral = (a: A) => a['flag'] === Discriminator.Value1 ? a.stringProp : a.numberProp;

// Errors:
// Property 'stringProp' does not exist on type 'A'.
//   Property 'stringProp' does not exist on type 'A2'.
//
// Property 'numberProp' does not exist on type 'A'.
//   Property 'numberProp' does not exist on type 'A1'.
const bracketAccessConst = (a: A) => a[flagName] === Discriminator.Value1 ? a.stringProp : a.numberProp;
```

</details>

**Comment by andrewbranch** [comment] 2021-07-26 23:37
Duplicate of #10530

**Closed** 2021-07-29 18:00 UTC
Labels: Duplicate
