### ISSUE TITLE
Object spreading a `Record<string, any>` gives wrong type

### ISSUE THREAD

**Issue by golopot** [Microsoft/TypeScript#30538] opened 2019-03-22 08:04 UTC
**TypeScript Version:**  3.4.0-dev.20190322

**Search Terms:**
object spread, Record, index signature 

**Code**

```ts
const fn = (a: Record<string, any>) => {
  const obj = { p: 1, ...a };

  obj.foo; // ts-error: Property 'foo' does not exist on type '{ p: number; }'
};

const fn2 = (a: { [_: string]: any }) => {
  const obj = { p: 1, ...a };

  obj.foo; // ts-error: Property 'foo' does not exist on type '{ p: number; }'
};
```

**Expected behavior:**

`obj` has type `{p: number} & Record<string, any>`.

This matches how typescript handles Object.assign.

**Actual behavior:**

Type of object-spreaded thing is ignored.

**Playground Link:** 

[link](https://www.typescriptlang.org/play/#src=const%20fn%20%3D%20(a%3A%20Record%3Cstring%2C%20any%3E)%20%3D%3E%20%7B%0D%0A%20%20const%20obj%20%3D%20%7B%20p%3A%201%2C%20...a%20%7D%3B%0D%0A%0D%0A%20%20obj.foo%3B%20%2F%2F%20ts-error%3A%20Property%20'foo'%20does%20not%20exist%20on%20type%20'%7B%20p%3A%20number%3B%20%7D'%0D%0A%7D%3B%0D%0A%0D%0Aconst%20fn2%20%3D%20(a%3A%20%7B%20%5B_%3A%20string%5D%3A%20any%20%7D)%20%3D%3E%20%7B%0D%0A%20%20const%20obj%20%3D%20%7B%20p%3A%201%2C%20...a%20%7D%3B%0D%0A%0D%0A%20%20obj.foo%3B%20%2F%2F%20ts-error%3A%20Property%20'foo'%20does%20not%20exist%20on%20type%20'%7B%20p%3A%20number%3B%20%7D'%0D%0A%7D%3B%0D%0A)

**Related Issues:**

**Comment by ajafff** [comment] 2019-03-22 09:58
This is a duplicate of #27273

**Closed** 2019-03-29 18:00 UTC
Labels: Duplicate
