### ISSUE TITLE
JSON.parse(null) is valid

### ISSUE THREAD

**Issue by dilyanpalauzov** [microsoft/TypeScript#43815] opened 2021-04-25 09:29 UTC
For `JSON.parse(null)` TypeScript says “Argument of type 'null' is not assignable to parameter of type 'string'.”

But all implementations I tried accept `JSON.parse(null)` and return null.

# Bug Report

### 🔎 Search Terms
`JSON.parse()`

### 🕗 Version & Regression Information
No regression.

### 🙁 Actual behavior

Error message.

### 🙂 Expected behavior

No error

**Comment by IllusionMH** [comment] 2021-04-25 10:11
Duplicate of #43232 and many other issues. 
Search terms `JSON parse null`

**Closed** 2021-04-25 10:24 UTC
