### ISSUE TITLE
Variable and Constant declarations (block/global) should be declared on common js/umd/amd/System exports same as functions

### ISSUE THREAD

**Issue by igorzg** [microsoft/TypeScript#41360] opened 2020-11-01 22:03 UTC
**TypeScript Version:**  4.x,   3.x,   2.x

**Search Terms:**
 variable / constant declarations on exports ignored using commonjs, amd, umd, System module on ES2015, ES2016, ES2017, ES2018, ES2019, ES2020
**Expected behavior:**
Variable and Constant declarations (block/global) should be declared on exports (it should behave same as function declarations)
```ts
let Injectable = () => console.log(Injectable.name);
exports.Injectable = Injectable;

var Injectable = () => console.log(Injectable.name);
exports.Injectable = Injectable;

const Injectable = () => console.log(Injectable.name);
exports.Injectable = Injectable;
```

**Actual behavior:**
```ts
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Injectable = void 0;
exports.Injectable = () => console.log(exports.Injectable.name);
```

**Related Issues:**
No

**Code**
```ts
export let Injectable = () => console.log(Injectable.name);
export const Injectable = () => console.log(Injectable.name);
export var Injectable = () => console.log(Injectable.name);
```
typescript ignores var, let, const declarations on export which should not be the case.

<details><summary><b>Output</b></summary>

```ts
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Injectable = void 0;
exports.Injectable = () => console.log(exports.Injectable.name);
```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2015",
    "jsx": "React",
    "module": "commonjs"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?target=2&jsx=0&module=1&ts=4.0.5#code/FAUwHgDg9gTgLgAgDYkQSQHYCsQGM4CGARiggLwIAUAlOQHwK5QYDOUKAdElAOaWY58xThgIBbENQDcwYAHoAVAmB1VCHiAwgYBOCBaMoAExAAuWQCIArixAIWcGAEt8FmQHkiguBxMAzJy0ABRgoCG04AE9KcGh4FgAaBAsAfRT9AFljKxQLJIBvBAA3AiQrMwRHcoQAX2lQSFg4Fg4BPEISOwoiqCcjBAAGGVimlrahTvIqWjIGJlZ2EC5eGMb41ux24SXRCXrZVQYS5225eYcCDEQTXCQCHTgnZgNKEihcAGs5Hm4iUtoWAALKA5fpEOwfEAQRCBQwmWQodCbCakCg0eiGBacbh8cYdETiSTDNbNDbebZTPHbGTAY4IKmTNEzObPRbLXHI-E7Qn1EbrBmo+mc6myc5I8mM6YY85snH8YWdDi7IkNOKkgVdIUSlA0w72YGghAQZxXZIaiwIIhWGHXKD6BAYKCIcG4Ag2OzHJwUpwGR3XPB3GAgIwqNRMMRiZhYAxOHiOoMGY5JRFJMUIG6B3RPVgIZgIPmIADugJcgP1IKQ-T9lrscEBdldtg4wAUclkQA)

**Comment by MartinJohns** [comment] 2020-11-01 22:20
Duplicate of #39819.

**Closed** 2020-11-14 18:00 UTC
Labels: Duplicate
