### ISSUE TITLE
Add `Omit` as a known interface

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#30455] opened 2019-03-18 04:45 UTC
## Search Terms

`Omit`

## Suggestion

Add the following type to lib.d.ts: 

```ts
type Omit<ObjectType, KeysType extends keyof ObjectType> = Pick<ObjectType, Exclude<keyof ObjectType, KeysType>>;
```

## More 
Origin : https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-420919470

From : https://github.com/sindresorhus/type-fest/blob/0226ef2092ee2b07a8714c832d106da659877a8f/index.d.ts#L75 `Please open new issues on TypeScript about making it built-in.`. I searched but couldn't find an issue, so here it is :rose:

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by j-oliveras** [comment] 2019-03-18 11:28
Duplicate of #19569?

**Comment by weswigham** [comment] 2019-03-18 20:22
Not really? That was back when there was only a hairy mapped-type based definition of `Omit` which we didn't particularly like, so didn't want to add.

**Comment by nmain** [comment] 2019-03-19 14:39
Eventually that issue was closed after conditional types were added.  @ahejlsberg made https://github.com/Microsoft/TypeScript/pull/21847 and said:
> We did not include the `Omit<T, K>` type because it is trivially written as `Pick<T, Exclude<keyof T, K>>`

**Comment by dragomirtitian** [comment] 2019-03-19 15:44
@nmain  My 2¢, trivial for some magic for others, I would argue all build-in mapped and conditional types are trivial to write but that does not make them any less useful. Having a common set of types makes code easier to understand across projects. `Omit` is also simpler to understand for newer typescript devs and they don't have to do conditional type math when looking at a definition, they just care about the behavior of the type.

**Comment by sindresorhus** [comment] 2019-03-20 06:53
I personally use `Omit` much more often than the other [built-in helper types](https://github.com/sindresorhus/type-fest#built-in-types).

**Comment by jeremiergz** [comment] 2019-03-21 21:38
Totally agree, I end up declaring that `Omit` type in almost every project.
It's like `Record<string, string>` could be written `{ [k: string]: string}`. I prefer the `Record` helper, same feeling about this one.

**Comment by SleeplessByte** [comment] 2019-03-21 22:36
I've used `Omit` in every single project and every single time I have to look it up, because `Pick<T, Exclude<keyof T, K>>` isn't trivial to recall; if many people use it in every project, it make sense to make it part of `lib.d.ts` right?

> It's like Record<string, string> could be written { [k: string]: string}. I prefer the Record helper, same feeling about this one.

That's not the same; and it's not even close.

**Comment by jeremiergz** [comment] 2019-03-21 23:02
> That's not the same; and it's not even close.

How so? Isn't it better to explain your train of thought when you say someone's wrong?...

**Comment by SleeplessByte** [comment] 2019-03-21 23:24
> > That's not the same; and it's not even close.
> 
> How so? Isn't it better to explain your train of thought when you say someone's wrong?...

Sorry, I thought you knew and were making an analogy for the sake of making one. Here is the example:

Let's say you have some data, or a type without an indexer:
```typescript
const data = {
  name: 'myfile.txt',
  path: '/path/to/foo'
}
```

And a function `lengths` that maps over all the keys in the input, and assigns the length of the value:
```typescript
function lengths<T extends { [x: string]: string }>(input: T): Record<keyof T, number>;
```

Now the result of this function will be `Record<keyof typeof data, number>` and therefore `Record<'name' | 'path', number>`:
```typescript
const result = lengths(data)
// => const length: Record<"name" | "path", number>

result.name
// => 10

result['foo']
// => Element implicitly has an 'any' type because type 'Record<"name" | "path", number>' has no index signature.ts(7017)
```

If it were the same as `{ [k: string]: string}`, the latter would have worked. Instead you get a typesafe (keys) object!

**Comment by SleeplessByte** [comment] 2019-03-21 23:28
> > That's not the same; and it's not even close.
> 
> How so? Isn't it better to explain your train of thought when you say someone's wrong?...

Sorry, you're right!

What I should have said is that it's better to compare `Record<keyof K, string>` to `{ [P in K]: string }`

**Comment by fabiospampinato** [comment] 2019-03-22 14:21
The [docs](https://www.typescriptlang.org/docs/handbook/advanced-types.html)' reasoning about this is:

> We did not include the Omit<T, K> type because it is trivially written as Pick<T, Exclude<keyof T, K>>

I'm not so sure about the triviality of it, especially for new TS devs, but IMHO this isn't a good reason for not including Omit, to me it feels like saying that if I have this code:

```js
return collection.map ( item => item.foo () );
```

I don't really need `map` because it's trivial to do the same with `forEach`:

```js
const result = [];
collection.forEach ( item => result.push ( item.foo () ) );
return result;
```

I mean yeah, it's trivial, but am I supposed to write such ugly code every time or am I supposed to redefine `map` every time?

**Closed** 2019-04-04 17:37 UTC
Labels: Committed, In Discussion, Suggestion

**Comment by DanielRosenwasser** [comment] 2019-04-04 17:38
This is now 3.5-bound! :rocket:

You can try it out with our next nightly release.

**Comment by leidegre** [comment] 2019-04-07 05:32
For those curious how the `Omit` type is used, you can find that information [here](https://stackoverflow.com/a/48216010/58961).

**Comment by NoelAbrahams** [comment] 2019-04-09 12:02
The naming of this is rather unfortunate. I mean to say, what exactly is the difference between the words "Omit" and "Exclude"? They are essentially synonyms with a minor nuance.

The definition we have used is `ExcludeProperty`.

```ts
/**
 * Exclude from T those types that are assignable to U
 */
type Exclude<T, U> = T extends U ? never : T;

/**
 * From T remove the properties K
 * E.g. ExcludeProperty<{ a: number, b: string }, 'b'> => { a: number }
 */
type ExcludeProperty<T, K extends keyof T> = Pick<T, Exclude<StringKeyOf<T>, K>>;
```

**Comment by sindresorhus** [comment] 2019-04-10 17:02
For everyone watching this issue, note that the `Omit` type that was added is not the strict one suggested here. See: https://github.com/Microsoft/TypeScript/issues/30825.
