### ISSUE TITLE
Emit runtime code that checks bang operator

### ISSUE THREAD

**Issue by alamothe** [microsoft/TypeScript#47123] opened 2021-12-12 21:05 UTC
# Suggestion

Currently, TypeScript's bang operator `!` is simply discarded when generating JS code. This is unfortunate, as such errors will either not be caught at runtime at all (producing unwanted behavior) or caught later on, when the property of the result is being accessed (in which case, the resulting stack trace does not point to the root cause).

TypeScript should add a compiler flag to throw errors at runtime for bang operator when the value is null or undefined.

This is well-established practice in other programming languages. 

## 🔍 Search Terms

typescript runtime error bang non-null assertion operator (!) emit actual non-null & non-undefined checks into the resulting JS JavaScript

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

```tsx
parseFloat(input!)
```
Then use the resulting value to guide a spaceship full of astronauts to land on Mars.

## 💻 Use Cases

I expect that 90+% of new TypeScript projects would want this behavior, and 50+% of existing projects would switch to this behavior within 1 year.

**Comment by MartinJohns** [comment] 2021-12-12 22:48
> [x] This could be implemented without emitting different JS based on the types of the expressions
> [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
> [x] This feature would agree with the rest of TypeScript's Design Goals.

You should check these points again. This is definitely out of scope for TypeScript.

The purpose of the `!` operator is lack of type-safety, it's an opt-out from the nullability checks.

**Comment by MartinJohns** [comment] 2021-12-12 22:50
This is a duplicate of #20217.

**Comment by alamothe** [comment] 2021-12-13 18:57
It is opt-out at compile time, not at runtime.

**Closed** 2021-12-16 18:00 UTC
Labels: Duplicate
