### ISSUE TITLE
[playground] target's <select> does not mirror url's target= param

### ISSUE THREAD

**Issue by Jamesernator** [microsoft/TypeScript#47972] opened 2022-02-20 03:14 UTC
# Bug Report

### 🔎 Search Terms

playground, target, url

### 🕗 Version & Regression Information

The current version of the TypeScript Playground.

### ⏯ Playground Link

This is an example of a link that doesn't mirror:

[target set to ESNext](https://www.typescriptlang.org/play?target=99)

### 🙁 Actual behavior

Despite having `target=99` in the url, the `<select>` for Target shows other values (not always consistently `ES3` either). i.e.:

![Screenshot 2022-02-20 4 06 55 PM](https://user-images.githubusercontent.com/8518303/154826894-b6524043-ed10-4b8e-8930-8413f53a1032.png)

### 🙂 Expected behavior

The `<select>` should mirror the current status of the url. Other tsconfig options seem to work fine, dunno why just this on isn't.

**Comment by MartinJohns** [comment] 2022-02-20 07:48
Duplicate of https://github.com/microsoft/TypeScript-Website/issues/1136.

**Closed** 2022-02-25 18:00 UTC
Labels: Duplicate
