### ISSUE TITLE
DateConstructor: Argument of type 'string | number' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by alan-agius4** [Microsoft/TypeScript#21758] opened 2018-02-08 11:24 UTC
**TypeScript Version:**  2.7.1

**Search Terms:** DateConstructor

**Code**

```ts
export let x: string | number;
export const date = new Date(x);
```

**Expected behavior:**
No error

**Actual behavior:**
Argument of type 'string | number' is not assignable to parameter of type 'string'.
Type 'number' is not assignable to type 'string'.

**Comment by j-oliveras** [comment] 2018-02-08 12:14
Duplicate of #20936 and #20900.

**Closed** 2018-02-08 20:22 UTC
Labels: Duplicate
