### ISSUE TITLE
Multiline ES6 syntax import formatting

### ISSUE THREAD

**Issue by kuon** [Microsoft/TypeScript#4899] opened 2015-09-21 14:39 UTC
I am now experimenting with the ES6 import syntax (at least I think it's ES6) and I noticed that the following is formatted, in my opinion, wrongly:

```typescript
import {
Controller as UploadController,
State as UploadState
} from './controllers/upload';
```

should be:

```typescript
import {
    Controller as UploadController,
    State as UploadState
} from './controllers/upload';
```

**Comment by SaschaNaz** [comment] 2015-09-21 16:58
Should be fixed by #4609

**Comment by kuon** [comment] 2015-09-21 18:25
Yes it seems to be fixed looking at the PR. Thanks!

**Comment by DanielRosenwasser** [comment] 2015-09-21 19:50
Let's leave this open until the issue goes in.

**Comment by DanielRosenwasser** [comment] 2015-09-21 19:51
Duplicate of #4516.

**Closed by DanielRosenwasser** 2015-09-21 19:51 UTC
Labels: Duplicate
