### ISSUE TITLE
Ama Vira Kian

### ISSUE THREAD

**Issue by alirezatc** [Microsoft/TypeScript#4817] opened 2015-09-16 07:39 UTC
Please fill the following out:

- Name: آما ویرای کیان
- Homepage url: http://amasystem.ir/
- Brand Guidelines/Licensing: http://amasystem.ir/
- Logo: http://amasystem.ir/Assets/Image/ama-vira-logo-b.png

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by alirezatc** [comment] 2015-09-16 07:43
![ama-vira-logo-big](https://cloud.githubusercontent.com/assets/12410725/9899031/4e55a9bc-5c6c-11e5-9996-70647c3a1e34.png)

**Comment by mhegazy** [comment] 2015-10-21 04:24
duplicate of #5000

**Closed by mhegazy** 2015-10-21 04:24 UTC
