### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined in computeLineStarts

### ISSUE THREAD

**Issue by btakita** [microsoft/TypeScript#40747] opened 2020-09-24 16:36 UTC
Release version 4.0.3

```
(cd dom-lib-loader && tsc)
```
Results:
```
/work/project/node_modules/.pnpm/typescript@4.0.3/node_modules/typescript/lib/tsc.js:6040
        while (pos < text.length) {
                          ^
TypeError: Cannot read property 'length' of undefined
    at computeLineStarts (/work/project/node_modules/.pnpm/typescript@4.0.3/node_modules/typescript/lib/tsc.js:6040:27)
    at Object.getLineStarts (/work/project/node_modules/.pnpm/typescript@4.0.3/node_modules/typescript/lib/tsc.js:6093:60)
    at getCurrentLineMap (/work/project/node_modules/.pnpm/typescript@4.0.3/node_modules/typescript/lib/tsc.js:79723:59)
    at emitDetachedCommentsAndUpdateCommentsInfo (/work/project/node_modules/.pnpm/typescript@4.0.3/node_modules/typescript/lib/tsc.js:83011:94)
    at emitBodyWithDetachedComments (/work/project/node_modules/.pnpm/typescript@4.0.3/node_modules/typescript/lib/tsc.js:82884:17)
    at emitSourceFile (/work/project/node_modules/.pnpm/typescript@4.0.3/node_modules/typescript/lib/tsc.js:81753:21)
    at pipelineEmitWithHint (/work/project/node_modules/.pnpm/typescript@4.0.3/node_modules/typescript/lib/tsc.js:79800:24)
    at pipelineEmit (/work/project/node_modules/.pnpm/typescript@4.0.3/node_modules/typescript/lib/tsc.js:79756:13)
    at print (/work/project/node_modules/.pnpm/typescript@4.0.3/node_modules/typescript/lib/tsc.js:79690:13)
    at Object.writeFile (/work/project/node_modules/.pnpm/typescript@4.0.3/node_modules/typescript/lib/tsc.js:79674:13)
```

The project build:
```
tsc -b $dirs -W
```
Results:
```
[9:31:08 AM] Starting compilation in watch mode...

error TS6059: File '/work/project/libs/dom-lib-loader/index.ts' is not under 'rootDir' '/work/project/libs/chat-ui'. 'rootDir' is expected to contain all source files.

error TS6307: File '/work/project/libs/dom-lib-loader/index.ts' is not listed within the file list of project '/work/project/libs/chat-ui/tsconfig.json'. Projects must list all files or use an 'include' pattern.

[9:31:10 AM] Found 2 errors. Watching for file changes.
```

**Comment by btakita** [comment] 2020-09-24 18:30
Issue was caused by importing from a relative path instead of the full package name.

chat-ui/index.ts
```ts
import '../dom-lib-loader'
```

rather than tho correct import
```ts
import '@prefix/dom-lib-loader'
```

**Comment by andrewbranch** [comment] 2020-09-24 21:50
Can you provide an example project that crashes this way?

**Comment by Bobris** [comment] 2021-01-29 01:16
Have same problem I have workaround for typescript.js file:

```
                ts.Debug.assert(declarationTransform.transformed.length === 1, "Should only see one output from the decl transform");
                // Inserted next line
                declarationTransform.transformed[0].text = declarationTransform.transformed[0].text || "";
                printSourceFileOrBundle(declarationFilePath, declarationMapPath, declarationTransform.transformed[0], declarationPrinter, {
```

Cannot send repro because I don't know how to simplify and anonymize closed source code.

Problem is that declaration emit does not contains `text` (is undefined) which is needed for comments or trivia emits. It is used in watcher which generates declarations only for detection of "shape change". Input program contains semantic errors.

**Comment by YousefED** [comment] 2021-04-19 16:45
I'm running into the same issue on v4.2.4

**Comment by p0wl** [comment] 2021-04-21 14:35
ran into this issue today with 4.2.4, workaround is here: https://github.com/microsoft/TypeScript/issues/41717#issuecomment-781128223

So if two folders have the same package.json name, it fails

**Comment by andrewbranch** [comment] 2021-04-21 16:39
Huh, #41717 seems to be an exact duplicate of this, but the discussion there has been way more useful, so I’m going to close this one. Thanks for linking @p0wl!

**Closed by andrewbranch** 2021-04-21 16:39 UTC
Labels: Needs More Info
