### ISSUE TITLE
Insert "* " if enter new line inside a JsDoc comment

### ISSUE THREAD

**Issue by zhengbli** [Microsoft/TypeScript#4982] opened 2015-09-26 06:32 UTC
Current if entering a new line inside ad JsDoc comment, nothing is inserted in the new line.
![gif](https://cloud.githubusercontent.com/assets/1171301/10116153/9c4bb62a-63dd-11e5-876a-609c87897ab4.gif)

**Comment by paulvanbrenk** [comment] 2015-09-28 17:50
Duplicate of #4430

**Closed by paulvanbrenk** 2015-09-28 17:50 UTC
Labels: Bug
