### ISSUE TITLE
Add support custom TSX transformation

### ISSUE THREAD

**Issue by LabEG** [Microsoft/TypeScript#6375] opened 2016-01-06 16:09 UTC
TypeScript support only two way of TSX transformation:
1. Preserve. I can compile to preserve and process file by classic JSX transform. This way support many framework.
2. React. This is hard coded transformation only for React. This way is not honest in relation to other frameworks.

I want to use TSX view on difference frameworks, such as angular 1/2, mithril, vanilajs and others. Maybe well be better make not a hard coded transformation? Maybe better way well be make customizable transformation rule, based on d.ts.

**Comment by RyanCavanaugh** [comment] 2016-01-06 17:58
This turns out to be a lot of work for the sake of a minor convenience. Is there anything actually blocking you from using Preserve + the normal tool for the job?

**Comment by mhegazy** [comment] 2016-01-07 18:10
Duplicate of #3788

**Closed by mhegazy** 2016-01-07 18:10 UTC
