### ISSUE TITLE
Maybe support for assign resolution in constructors

### ISSUE THREAD

**Issue by kidcosmic** [Microsoft/TypeScript#28688] opened 2018-11-27 18:12 UTC
## Search Terms

assign

## Suggestion

my constructors usually follow the pattern:
```
class It {
  prop1: string
  prop2: string
  constructor(props: It) {
    (_ || Object).assign(this, props);
  }
}
```
With this though, I get the error
```
property 'prop1' has no initializer and is definitely not assign in the constructor
```
Though it is.

Typing out all properties in constructor, constructor params and class vars is sadly redundant.

Typescript apparently has the inner workings for assignment awareness, can this be extended to assigning functions?

## Use Cases

Above
I'm sure other people can find some dope use cases for an assign type descriptor.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment] 2018-11-28 06:58
Duplicate of #26792

**Closed** 2018-12-12 10:00 UTC
Labels: Duplicate
