### ISSUE TITLE
Duplicate auto import suggestions with re-exports

### ISSUE THREAD

**Issue by jgoz** [Microsoft/TypeScript#19889] opened 2017-11-09 22:36 UTC
**TypeScript Version:**  2.7.0-dev.20171109

(Using VS Code 1.18.0)

**Code**

`env.ts`:
```ts
export isDevelopmentEnvironment = true;
```

`util.ts`:
```ts
export * from "./env";
```

`index.ts`:
```ts
export * from "./util";
```

`test.ts`:
```ts
if (isDev) // open import suggestions menu
```

**Expected behavior:**

See 3 options for `isDevelopmentEnvironment`, one for the source and two for re-exports.

**Actual behavior:**

See 3 options for `isDevelopmentEnvironment`, but all of them are for the `index` export.

Trace output for completions from tsserver:

![image](https://user-images.githubusercontent.com/132233/32632929-b711233a-c562-11e7-9ac3-e431a53161de.png)

**Comment by mhegazy** [comment] 2017-11-10 21:51
seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/19694

**Comment by jgoz** [comment] 2017-11-10 21:57
Yeah, these are all subtle variations of the same issue. This one is for an in-project re-export; I can think of situations where I would want either the outer-most or the inner-most export, so the duplication isn't a problem for me. It's that the duplicates all point to the same (outer) export.

**Closed** 2017-11-16 19:15 UTC
Labels: Duplicate
