### ISSUE TITLE
Request: destructuring types 

### ISSUE THREAD

**Issue by 00ff0000red** [microsoft/TypeScript#40724] opened 2020-09-23 20:32 UTC
## Suggestion

Object destructuring syntax on types.

## Use Cases

This, when used correctly, can reduce code verbosity or improve readability.
There are no shortcomings that exist with current approaches, yet this can still improve upon it nonetheless.

## Examples

It would be used exactly as object restructuring would, yet proceeded by the TypeScript "type" keyword.
Ex: array destructuring
```ts
declare type T, H;
...
function f(x: T): H { ... };

type [ param0 ] = Parameters<typeof f>;
let value: param0;
...
f(value);
```

Ex: object destructuring
```ts
type Library = {
    T: ...,
    H: ...,
    A: {
        B: ...
    }
};
...
type {
    H,
    A: {
        B
    }
} = Library;

// now these types are declared in the current scope

let x: H;

async function getDataFromLibrary(something: B): H {
    ...
};
```

## Checklist

My suggestion meets these guidelines:

* [ ✓ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ✓ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ✓ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ✓ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ~ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by andrewbranch** [comment] 2020-09-23 21:52
Duplicate of #13135

**Closed** 2020-09-23 22:19 UTC
Labels: Duplicate
