### ISSUE TITLE
Error with combining Array types? Error: Cannot invoke an expression whose type lacks a call signature

### ISSUE THREAD

**Issue by khusamov** [Microsoft/TypeScript#15315] opened 2017-04-22 07:07 UTC
**TypeScript Version:**  2.2.1

**Code**

```ts
function getHandler(handlers: number[] | string[]): any {
    return handlers.map(handler => handler);
}
```

**Expected behavior:**
Without error!

**Actual behavior:**
Error text:
> error TS2349: Cannot invoke an expression whose type lacks a call signature. 
> Type '{ (this: [string, string, string, string, string], callbackfn: (value: string, 
> index: number, ...' has no compatible call signatures.

**Comment by mhegazy** [comment] 2017-04-24 16:43
Duplicate of https://github.com/Microsoft/TypeScript/issues/7294

**Comment by mhegazy** [comment] 2017-05-08 19:23
This issue seems to have been already addressed or is unactionable at the moment. I am auto-closing it for now.

**Closed by mhegazy** 2017-05-08 19:23 UTC
Labels: Duplicate
