### ISSUE TITLE
`Array.prototype.includes` should be narrow on union of enum types instead of throwing

### ISSUE THREAD

**Issue by mtsoltan** [microsoft/TypeScript#49906] opened 2022-07-14 14:56 UTC
# Suggestion

## 🔍 Search Terms

`includes`, `enum` (https://github.com/microsoft/TypeScript/issues/46085 is relevant but not what this is discussing)

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

`Array.prototype.includes` should be able to narrow down on a union of enum types instead of throwing:
```
TS2345: Argument of type 'SomeEnum | SomeOtherEnum' is not assignable to parameter of type 'SomeEnum'.   Type 'SomeOtherEnum.C' is not assignable to type 'SomeEnum'.
```

## 📃 Motivating Example

```typescript
export enum SomeEnum {
    A = 'aaa',
    B = 'bbb'
}

export enum SomeOtherEnum {
    C = 'ccc',
    D = 'ddd'
}


  function someFunction(somePossibleValue: SomeEnum | SomeOtherEnum) {
    if (Object.values(SomeEnum).includes(somePossibleValue)) { // <--- Includes signature should be changed so this narrow the type at compile time
      return 'some result'; // <--- Inside the if-body, the type of somePossibleValue should be successfully narrowed down
    }
    if (Object.values(SomeOtherEnum).includes(somePossibleValue)) { // <--- Includes signature should be changed so this narrow the type at compile time
      return 'some other result'; // <--- Inside the if-body, the type of somePossibleValue should be successfully narrowed down
    }

    throw new Error('On neither'); // <--- I understand this cannot be figured out at compile time because .includes cannot execute at compile time
  }
```

## 💻 Use Cases

Allowing checks on something that could be possibly one of multiple enums.

**Comment by MartinJohns** [comment] 2022-07-14 15:00
Duplicate of https://github.com/microsoft/TypeScript/issues/26255 / https://github.com/microsoft/TypeScript/issues/14520.

**Comment by MartinJohns** [comment] 2022-07-14 15:02
Duplicate of https://github.com/microsoft/TypeScript/issues/26255 / https://github.com/microsoft/TypeScript/issues/14520.

**Comment by mtsoltan** [comment] 2022-07-14 16:10
:facepalm: I should've searched more before opening an issue. Apparently this has more to do with `Array.prototype.includes` in general, and not just with how it acts on enums. Feel free to close if you feel this would fork the discussion to pointless directions.

**Closed** 2022-07-16 18:00 UTC
Labels: Duplicate
