### ISSUE TITLE
Extend Event interfaces with Element target

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#21622] opened 2018-02-05 08:01 UTC
Events handlers in several interfaces such as Window, Document and so on can be safely typed with 'target: Element' instead of of 'target: EventTarget'

Before:
```ts
interface Event { target: EventTarget; }
interface UIEvent extends Event { ... }
interface MouseEvent extends UIEvent { ... }

interface DocumentEventMap extends GlobalEventHandlersEventMap {
 "click": MouseEvent;
}
```

After:
```ts
interface Event<Target = EventTarget>{ target: Target; }
interface UIEvent<Target = EventTarget> extends Event<Target> {  }
interface MouseEvent<Target = EventTarget> extends UIEvent<Target> { }

interface DocumentEventMap extends GlobalEventHandlersEventMap {
 "click": MouseEvent<Element>
}
```

**Expected behavior:**
Type of event.target should be 'Element' in relevant event handlers.

**Actual behavior:**
Type is always EventTarget which requires type assertions.

**Comment by mhegazy** [comment] 2018-02-12 20:03
Duplicate of https://github.com/Microsoft/TypeScript/issues/299

**Closed** 2018-02-26 20:42 UTC
Labels: Duplicate
