### ISSUE TITLE
strictNullChecks should enforce property initialization

### ISSUE THREAD

**Issue by alhugone** [Microsoft/TypeScript#14289] opened 2017-02-24 11:29 UTC
**TypeScript Version:**  2.1.1

**Code**

```ts
class MyClass {
    private _myProp1: string;
    private _myProp2: number;

    public GetMyProp1(): string {
        return this._myProp1;
    }

    public GetMyProp2(): number {
        return this._myProp2;
    }
}

let myClass = new MyClass();
let myString: string = myClass.GetMyProp1(); // myString is undefined
let myNumber: number = myClass.GetMyProp2(); // myNumber is undefined

```

**Expected behavior:**
Should not compile:
Error: 'myProp1' - Default initialization to undefined, but type 'undefined' is not assignable to type 'string'.

**Actual behavior:**
compiles and properties are undefined

**Comment by mhegazy** [comment] 2017-02-24 19:55
Duplicate of https://github.com/Microsoft/TypeScript/issues/8476

**Closed** 2017-03-07 17:35 UTC
Labels: Duplicate
