### ISSUE TITLE
Suport single file compilation with --project tsconfig.json

### ISSUE THREAD

**Issue by cdalexndr** [microsoft/TypeScript#41865] opened 2020-12-07 23:04 UTC
## Search Terms

tsconfig.json single file compilation

## Suggestion
`tsc --project tsconfig.json somefile.ts`

## Use Cases
Inter-operability with third party libraries that use tsconfig.json.
This way, you can manually compile using same configuration file.

## Examples

` tsc --project tsconfig.json --outFile bundle.js sourcefile.ts`
manually compile a bundle
## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

Related: https://github.com/Microsoft/TypeScript/issues/5858

**Comment by RyanCavanaugh** [comment] 2020-12-08 01:08
I don't understand the use case. You can already use configuration file inheritance to share a common tsconfig file for settings purposes. Does this mean that the file list would *replace* the files listed in the tsconfig, or *augment* it? Maybe this is a duplicate of #27379

**Comment by cdalexndr** [comment] 2020-12-08 09:40
I don't use a file list in tsconfig.json.
Instead of creating a new tsconfig file just for manual usage, I would like for the compiler to get the settings from tsconfig.json and use them when compiling input files.

**Comment by RyanCavanaugh** [comment] 2020-12-08 16:29
Gotcha, thanks. That'd be the same as #27379 then

**Closed** 2020-12-08 16:59 UTC
Labels: Duplicate
